### ISSUE TITLE
偶现：树节点很多时拖动问题

### ISSUE THREAD

**Issue by startStudy1** [antvis/G6#1001]
例子： https://antv-g6.gitee.io/zh/examples/tree/compactBox

现象： 在树图中单击左键拖拽， 一直按住不动，然后不停的移动鼠标，一段时间后抬起左键，移动鼠标，
树还是会跟着移动。

注：这个现象是偶发的。当自定义节点，节点内容较多，并且节点的宽度占比更大时，偶发的频率增加。
浏览器：chrome最新版本

**Comment by luoyelusheng** [comment]
兄弟 我正在研究自定义树节点的功能 能否把你研究好的给我瞅瞅 感谢思密达

**Comment by startStudy1** [comment]
可参考下面这个代码， 节点的事件可自定义
https://antv-g6.gitee.io/zh/examples/tree/compactBox ，把下面的代码直接复制到这个地址

import G6 from '@antv/g6';

const width = document.getElementById('container').scrollWidth;
const height = document.getElementById('container').scrollHeight || 500;
var COLLAPSE_ICON = function COLLAPSE_ICON(x, y, r) {
  return [['M', x, y], ['a', r, r, 0, 1, 0, r * 2, 0], ['a', r, r, 0, 1, 0, -r * 2, 0], ['M', x + 2, y], ['L', x + 2 * r - 2, y]];
};
var EXPAND_ICON = function EXPAND_ICON(x, y, r) {
  return [['M', x, y], ['a', r, r, 0, 1, 0, r * 2, 0], ['a', r, r, 0, 1, 0, -r * 2, 0], ['M', x + 2, y], ['L', x + 2 * r - 2, y], ['M', x + r, y - r + 2], ['L', x + r, y + r - 2]];
};
const config = {
  o_width: 200, // 最外框宽度
  o_height: 122, // 最外框高度
  m_height: 64, // 主要内容区的高度，即一个项目的背景颜色
  padding: 8, // padding值
  fontSize: 12, // 字体大小
  titleHeight: 22, // 上面标题的高度
  titleColor: '#1F1F1F', // 上面标题的颜色
  titileKey: 'title',
  rightRadius: 6, // 右边的收缩聚合 marker的大小
  borderRadius: 2,  //边框radious
  titleBack: 'rgba(0,0,0,0.08)', // 标题背景色
  mBack: ['rgba(38,121,244,0.08)', 'rgba(1,184,170,0.08)'], // 内容区背景
  mBeforeBack: ['#2679F4', '#01B8AA'], // 内容区前面的背景
  mBeforeWidth: 2,  // 内容区前面的宽度
  mTitleColor: '#1F1F1F', // 内容区的标题
  mTitleKey: 'name',  // 内容区的标题key
  mLabelTitleColor: ' #5C5C5C', // 内容区的label的颜色
  mLabel1Title: '分级汇总金额：', // 内容区的label的标题
  mLabel1Key: 'sumPrice', // 内容区的label的内容key
  mCount: 1, // 内容区label的个数
  btmTitle: '查看科目分级', // 底部文字
  btmTitleColor: '#427CAC' // 底部文字颜色
}
 
 G6.registerNode('tree-node', {
    drawShape: function drawShape(cfg, group) {
      
      var rect = group.addShape('rect', {
        attrs: {
          fill: '#fff',
        //  stroke: '#666',
          shadowBlur: 2,
          shadowOffsetX: 0,
          shadowOffsetY: 1,
          borderRadius: 2,
          shadowColor: 'rgba(0, 0, 0, 0.24)'
        }
      });
      
      var hasChildren = cfg.children && cfg.children.length > 0;
      const content = cfg.title //.replace(/(.{19})/g, '$1\n');
      // 最上面的标题
      group.addShape('text', {
        attrs: {
          text: content,
          x: config.padding,
          textBaseline: 'top',
          y: config.titleHeight / 2 - config.fontSize / 2,
          fontSize: config.fontSize,
          fill: config.titleColor
        }
      })
       // 标题背景色
       const rect1 = group.addShape('rect', {
          attrs: {
            fill: config.titleBack,
            x: 0,
            y: 0,
            borderRadius: config.borderRadius,
            width: config.o_width,
            height: config.titleHeight
          }
        });
     	if (hasChildren) {
        group.addShape('marker', {
          attrs: {
            x: config.o_width - config.rightRadius * 2 - config.padding,
            y: config.titleHeight / 2,
            r: config.rightRadius,
            symbol: COLLAPSE_ICON,
            stroke: config.titleColor,
            lineWidth: 1
          },
          className: 'collapse-icon'
        });
      }
    
      // 下面内容区
      const {project=[]} = cfg
      const projectHei = project.map((el, i) => {
        const mHeight = config.fontSize * (config.mCount + 1) + config.padding * (config.mCount + 2)
        const y = config.titleHeight + config.padding + (mHeight + config.padding) * i
        // 项目名称
        const text1 = group.addShape('text', {
          attrs: {
            text: el[config.mTitleKey] || '--',
            x: config.padding * 2 + config.mBeforeWidth,
            y: y + config.padding,
            textBaseline: 'top',
            fontSize: config.fontSize,
            fill: config.mTitleColor
          }
        })
        // label1 
        const label1 = group.addShape('text', {
          attrs: {
            text: config.mLabel1Title || '--',
            x: config.padding * 2 + config.mBeforeWidth,
            y: y + config.padding + config.fontSize + config.padding,
            textBaseline: 'top',
            fontSize: config.fontSize,
            fill: config.mLabelTitleColor
          }
        })
       	group.addShape('text', {
          attrs: {
            text: el[config.mLabel1Key] || '--',
            x: label1.getBBox().maxX,
            y: y + config.padding + config.fontSize + config.padding,
            textBaseline: 'top',
            fontSize: config.fontSize,
            fill: config.mLabelTitleColor
          }
        })
        // 背景
        const rect = group.addShape('rect', {
          attrs: {
            fill: config.mBack[i],
            x: config.padding,
            y,
            width: config.o_width - config.padding * 2,
            height: mHeight
          }
        })
        // 背景前面部分
        group.addShape('rect', {
          attrs: {
            fill: config.mBeforeBack[i],
            x: config.padding,
            y: y,
            width: config.mBeforeWidth,
            height: mHeight
          }
        })
        
        
        return rect
      })
      
      const text = group.addShape('text', {
        attrs: {
          text: config.btmTitle,
          x: config.padding,
          textBaseline: 'top',
          y: projectHei[projectHei.length - 1].getBBox().maxY + config.padding,
          fontSize: config.fontSize,
          fill: config.btmTitleColor
        }
      })
      
     // console.log(hrefHeight)
       rect.attr({
          x: 0,
          y: 0,
          width: config.o_width,
          height: text.getBBox().maxY + config.padding
        })
      
      return rect;
    }
  }, 'single-shape');
G6.registerEdge('hvh', {
  draw(cfg, group) {
    const startPoint = cfg.startPoint;
    const endPoint = cfg.endPoint;

    const shape = group.addShape('path', {
      attrs: {
        stroke: '#333',
        path: [
          ['M', startPoint.x, startPoint.y],
          ['L', startPoint.x + (endPoint.x - startPoint.x) / 2 , startPoint.y],
          ['L', startPoint.x + (endPoint.x - startPoint.x) / 2 , endPoint.y],
          ['L', endPoint.x, endPoint.y]
        ]
      }
    });
    return shape;
  }
});
const graph = new G6.TreeGraph({
  container: 'container',
  width,
  height,
  pixelRatio: 2,
  modes: {
    default: ['drag-canvas', 'zoom-canvas']
  },
  defaultNode: {
    shape: 'tree-node',
    anchorPoints: [[0, 0.5], [1, 0.5]]
  },
  defaultEdge: {
    shape: 'hvh'
  },
  edgeStyle: {
    default: {
      stroke: '#C2C2C2',
      lineWidth: 2
    }
  },
  layout: {
    type: 'compactBox',
    direction: 'LR',
    getId: function getId(d) {
      return d.id;
    },
    getHeight: function getHeight() {
      return 16;
    },
    getWidth: function getWidth() {
      return 84;
    },
    getVGap: function getVGap() {
      return 54;
    },
    getHGap: function getHGap() {
      return 100;
    }
  }
});

const data = {
  id: 1,
  title: '分级1',
  project: [
    {
      id: 11,
      name: '项目1',
      sumPrice: 2000,
    },
    {
      id: 12,
      name: '项目2',
      sumPrice: 2000,
    },
  ],
  children: [
    {
      id: 2,
      title: '分级1-1',

      project: [
        {
          id: 11,
          name: '项目1',
          sumPrice: 223
        }
      ],
      children: [
        {
          id: 4,
          title: '分级1-1-1',

          project: [
            {
              id: 11,
              name: '项目1',
              sumPrice: 223
            }
          ]
        }
      ]
    },
    {
      id: 3,
      title: '分级1-2',
      project: [
        {
          id: 11,
          name: '项目1',
          sumPrice: 223
        }
      ]
    }
  ]
}
G6.Util.traverseTree(data, function(item) {
  item.id = item.title;
});
graph.data(data);
graph.render();
graph.fitView();

**Comment by baizn** [comment]
应该是个 BUG，后面排查下。
PS：没鼠标真不好复现。

**Comment by startStudy1** [comment]
> 应该是个 BUG，后面排查下。
> PS：没鼠标真不好复现。

好的，谢谢。

**Comment by YealZoy** [comment]
这个 bug 解决了吗？  我这边是 自定义节点   也是偶尔出现这种情况
单击某节点 然后 移动 鼠标  那个节点 也跟随移动

**Comment by Yanyan-Wang** [comment]
新版本解决类似问题：https://github.com/antvis/G6/issues/3998
