### ISSUE TITLE
东西是好东西，但这文档。。。

### ISSUE THREAD

**Issue by vFire** [antvis/G6#1009]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

实在是有点让人蛋疼。。。版本混乱，文档说明也相当混乱，示例代码和实际代码完全不符合，到后来大量的代码需要我自己看源代码方能找到，举个非常简单的例子，Treegraph完全不成熟，minimap找了好久文档和Issue，终于知道要退回之前一个版本才能用。。。然后，graph.findAllByState这个函数也早就有变化了，需要两个参数才能用，而文档中就一个参数，折腾半天看了代码才知道参数变成两个了，。。。我滴天哪。。。能不能整整好再发布呀。。。无论如何，东西做的很好，但这文档也该规范规范了……

**Comment by baizn** [comment]
你看的哪里的文档呢？

**Comment by scaletimes** [comment]
@vFire 感谢提供反馈，也欢迎你一起来共建G6，我们一起让这件事情变得更美好一些
