### ISSUE TITLE
TypeError: Cannot read property 'enhance.d3.mapper' of undefined

### ISSUE THREAD

**Issue by bnerDY** [antvis/g6#101]
<img width="1044" alt="screen shot 2017-11-27 at 10 34 32 am" src="https://user-images.githubusercontent.com/5085327/33248197-a6cc2d3a-d35e-11e7-98b2-cacd26c52828.png">

通过import之后貌似找不到Plugins.

**Comment by TomHuangCN** [comment]
import Plugins from '@antv/g6-plugins';

**Comment by haoDean** [comment]
```javascript
import Plugins from '@antv/g6-plugins';
```
版本为：`@antv/g6-plugins@1.0.2`
已经引入但是还是报相同错误
`TypeError: Cannot read property 'layout.dagre' of undefined`

**Comment by TomHuangCN** [comment]
由于一些打包的问题，`import Plugins from '@antv/g6-plugins';` 不会注册到 G6.Plugins。npm环境下只能这么实例化：

```js
import Plugins from '@antv/g6-plugins';
const dagre = new Plugins['layout-dagre']({
			rankdir: 'LR',
			nodesep: 100,
			ranksep: 100,
		});
```
