### ISSUE TITLE
节点的宽度不固定，如何设置节点之间的线长度为固定值

### ISSUE THREAD

**Issue by crystalwm** [antvis/G6#1011]
* **G6 Version**: 3.2.4
* **Platform**:
* **Mini Showcase(like screenshots)**:

![02450CCF-7939-4DD2-9BEA-17F0FB80C850](https://user-images.githubusercontent.com/7902025/70126287-aca9fd00-16b3-11ea-8224-a650d5ae918d.png)
* **CodePen Link**:

节点的宽度不固定，如何设置节点之间的线长度为固定值，compatBox中的选项我都有配置，但是并没有达到我想要的选项。

**Comment by Yanyan-Wang** [comment]
getWidth 根据节点真实的宽度返回，getHGap 设置固定的值。

**Comment by controllerz** [comment]
我用脑树图， 设置getWidth,但是getHGap 还是有问题，
![image](https://user-images.githubusercontent.com/22693880/173756048-25192155-fb22-4077-baf8-9c13870d6ed2.png)
![image](https://user-images.githubusercontent.com/22693880/173756183-871a7009-c9b3-48cb-8bc5-7225f6d628aa.png)
