### ISSUE TITLE
分组拖动，鼠标总是重新跳至分组的右下角大约 1/4 处

### ISSUE THREAD

**Issue by maomaoispan** [antvis/G6#1013]
![{CA87B913-3749-4DDE-B0C9-4DFECF61592F}_20191205155506](https://user-images.githubusercontent.com/3338967/70215126-bac15180-1777-11ea-822f-8d46adc78af5.jpg)

箭头开始点为鼠标点击拖动点，箭头终点为拖动开始之后鼠标的位置，不管从分组的任何位置开始拖动，鼠标最终都会重新调整到大约箭头所在的位置（右下角）

**Comment by maomaoispan** [comment]
![{CA87B913-3749-4DDE-B0C9-4DFECF61592F}_20191205155506](https://user-images.githubusercontent.com/3338967/70215126-bac15180-1777-11ea-822f-8d46adc78af5.jpg)

箭头开始点为鼠标点击拖动点，箭头终点为拖动开始之后鼠标的位置，不管从分组的任何位置开始拖动，鼠标最终都会重新调整到大约箭头所在的位置（右下角）

**Comment by LongCatIsaac** [comment]
楼主解决了吗，解决了分享一下解法

**Comment by Yanyan-Wang** [comment]
带有全新节点分组 Combo 机制的 v3.5 发布了。demos：
内置 combos: https://g6.antv.vision/zh/examples/item/defaultCombos
自定义 combos: https://g6.antv.vision/zh/examples/item/customCombo
Combo 的布局: https://g6.antv.vision/zh/examples/net/comboForce
Combo 的交互: https://g6.antv.vision/zh/examples/interaction/combo

文档可以通过 [G6 官网](https://g6.antv.vision/zh) 上方的搜索栏搜索“combo”查看。
