### ISSUE TITLE
ie11下不能使用的解决方法

### ISSUE THREAD

**Issue by dbfu** [antvis/G6#1014]
* **G6 Version**:3.2.3
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:
![image](https://user-images.githubusercontent.com/32224358/70143520-d3c5f600-16d6-11ea-81e3-ed0546486bc9.png)
如上图：ie11不兼容箭头函数的语法，只要把这里改成普通function就行了

**Comment by Yanyan-Wang** [comment]
感谢您的解决方案。
还可以参考一下这个教程：https://g6.antv.vision/zh/docs/manual/FAQ/supportIE
