### ISSUE TITLE
紧凑树图，可以动态加载其非根节点的父节点吗？怎么操作呢？如下data想动态添加unRoot的父节点

### ISSUE THREAD

**Issue by qianqianjie1** [antvis/G6#1022]
const data = {
  isRoot: false,
  id: 'unRoot',
  style: {
    fill: 'red'
  },
  children: [{
    id: 'SubTreeNode1',
    raw: {},
    children: [{
      id: 'SubTreeNode1.1'
    }, {
      id: 'SubTreeNode1.2',
      children: [{
        id: 'SubTreeNode1.2.1'
      }, {
        id: 'SubTreeNode1.2.2'
      }, {
        id: 'SubTreeNode1.2.3'
      }]
    }]
  }, {
    id: 'SubTreeNode2',
    children: [{
      id: 'SubTreeNode2.1'
    }]
  }, {
    id: 'SubTreeNode3',
    children: [{
      id: 'SubTreeNode3.1'
    }, {
      id: 'SubTreeNode3.2'
    }, {
      id: 'SubTreeNode3.3'
    }]
  }, {
    id: 'SubTreeNode4'
  }, {
    id: 'SubTreeNode5'
  }, {
    id: 'SubTreeNode6'
  }]
};

**Comment by Yanyan-Wang** [comment]
是什么意思呢？希望给一些现有节点增加一个父元素？这样的话这些现有节点不就有了多个父节点？这不符合树图的数据结构呢。
