### ISSUE TITLE
Graph的updateItem(item, model)无法Update shape:modelRect的节点

### ISSUE THREAD

**Issue by BnuzLeo** [antvis/G6#1025]
modelRect节点的其他属性都可以修改，唯独label修改不了，代码如下
![issue](https://user-images.githubusercontent.com/24950212/70377763-404d2900-1953-11ea-991c-2e15009f6b97.png)
**修改前：**
![issue1](https://user-images.githubusercontent.com/24950212/70377770-4ba05480-1953-11ea-84d5-2119eadb644e.png)
**修改后：**  
label的style修改成功了并且显示，label在Object中修改成功，但是在UI上并未显示，而且不知道为什么往上移动了。
![issue2](https://user-images.githubusercontent.com/24950212/70377771-51963580-1953-11ea-8fa5-d8763cd8330e.png)

**Comment by baizn** [comment]
modelRect 节点重写了drawLabel 方法的，可以通过下面的方式去单独更新：
```
graph.on('node:click', evt => {
  const { item } = evt
  const group = item.get('group')
  const label = group.findByClassName('node-label')
  
  label.attr({
    text: 'xxx',
    fill: 'red',
    fontSize: 18
  })
  graph.paint()
})
```
具体参考这里：https://codesandbox.io/s/black-firefly-nrx63

**Comment by BnuzLeo** [comment]
> modelRect 节点重写了drawLabel 方法的，可以通过下面的方式去单独更新：
> 
> ```
> graph.on('node:click', evt => {
>   const { item } = evt
>   const group = item.get('group')
>   const label = group.findByClassName('node-label')
>   
>   label.attr({
>     text: 'xxx',
>     fill: 'red',
>     fontSize: 18
>   })
>   graph.paint()
> })
> ```
> 
> 具体参考这里：https://codesandbox.io/s/black-firefly-nrx63

谢谢你的答复~~
