### ISSUE TITLE
graph 默认给定空data会报 Uncaught TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by yuanxiaoyu** [antvis/G6#1026]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

graph 默认给定空data会报 Uncaught TypeError: Cannot read property '0' of null
![image](https://user-images.githubusercontent.com/7258569/70401599-5d751b00-1a6b-11ea-902c-cd7f727bf5da.png)

**Comment by baizn** [comment]
哪个版本呢？ 
https://g6.antv.vision/zh/examples/tree/compactBox  在官网中这里试下呢，空数据没报错。
或者提供个在线demo。

**Comment by yuanxiaoyu** [comment]
https://g6.antv.vision/zh/examples/net/dagreFlow   把data里的 nodes  edges改成空数组
![image](https://user-images.githubusercontent.com/7258569/70501225-73143e80-1b58-11ea-983b-dd252fe4694a.png)
鼠标在绘图区移动，问题出现 @baizn

**Comment by yuanxiaoyu** [comment]
版本为  3.2.4

**Comment by baizn** [comment]
是个 BUG，当为空数据时候，如果配置了 fitView 就会报错。

**Comment by Arlisol** [comment]
> 遇到了同样的问题，请问有什么临时方案吗

现在是加了一层给罩住了，在鼠标本来就在画布区域时可能不能避免触发两个报错，不过之后就没问题了，希望有更好的解决方案

**Comment by baizn** [comment]
下个版本修复，详见 https://github.com/antvis/G6/pull/1116

**Comment by flyaaaaaaaa** [comment]
我现在的版本是3.3.5，还是会报这个错误

**Comment by smilelight** [comment]
3.4.0也会报这个错误
