### ISSUE TITLE
桑吉图去哪了？简介里有桑吉图的动图

### ISSUE THREAD

**Issue by matianjun1** [antvis/G6#1027]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**: 
![image](https://user-images.githubusercontent.com/13162925/70409903-53154a00-1a88-11ea-9b9f-74975c95f355.png)

* **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
需要的话，暂时先看一下这里：https://antv-2018.alipay.com/zh-cn/g6/3.x/demo/graphql/sankey.html

少量 demo 新官网正在迁移中
