### ISSUE TITLE
G6 group 分组更新无效

### ISSUE THREAD

**Issue by zhoustudent** [antvis/G6#1031]
G6 group分组我用changeData 或者用updateItem都无效，请告知下如何更新group

**Comment by Yanyan-Wang** [comment]
目前节点分组的机制是一个临时的方案，存在很多问题。节点分组的问题都会在下个月的新版本中解决，我们正在重新设计和实现节点分组的新机制。

**Comment by Yanyan-Wang** [comment]
带有全新节点分组 Combo 机制的 v3.5 发布了。demos：
内置 combos: https://g6.antv.vision/zh/examples/item/defaultCombos
自定义 combos: https://g6.antv.vision/zh/examples/item/customCombo
Combo 的布局: https://g6.antv.vision/zh/examples/net/comboForce
Combo 的交互: https://g6.antv.vision/zh/examples/interaction/combo

文档可以通过 [G6 官网](https://g6.antv.vision/zh) 上方的搜索栏搜索“combo”查看。
