### ISSUE TITLE
G6 dagre布局有误

### ISSUE THREAD

**Issue by EvilChxm** [antvis/G6#1032]
* **G6 Version：latest**:
* **Google Chrome**:

*
* **https://codepen.io/evilchxm/pen/KKwVLLy**:

后续是两条链，但是31节点与32节点的定位计算是否有误？

![image](https://user-images.githubusercontent.com/13961307/70507529-8549a900-1b67-11ea-9007-37219f3586cf.png)

上图是渲染出来的，下图是实际我拖拽两个节点后的两条链。

![image](https://user-images.githubusercontent.com/13961307/70507230-e7ee7500-1b66-11ea-9289-8e0343a99575.png)

**Comment by Yanyan-Wang** [comment]
这应该是这个算法本身计算的结果，不是 G6 的问题。

**Comment by Shu-Ji** [comment]
@Yanyan-Wang 这确实是 G6 的 bug，提了一个 PR 修复。
