### ISSUE TITLE
自定义Dagre 流程图想做像树图一样的收缩行为怎么做呢？

### ISSUE THREAD

**Issue by qianqianjie1** [antvis/G6#1033]

**Comment by yeyu1271** [comment]
同问，想要像树一样的层级，但节点间可能会相互连，收缩操作好像就实现不了

**Comment by lsd1** [comment]
可以通过更新节点数据的方式去实现，给节点绑定事件，触发事件时更新他的子节点

**Comment by Yanyan-Wang** [comment]
因为 Dagre 处理的不是树结构，子节点可能会有两个上级节点，所以无法统一去控制收缩。你可以根据自己的需求，在监听节点点击事件的时候，把需要隐藏的节点 node.hide() 掉。
