### ISSUE TITLE
o[i] is not a constructor

### ISSUE THREAD

**Issue by yangdecai1111** [antvis/G6#1036]
![image](https://user-images.githubusercontent.com/49257960/70589194-13766b80-1c0a-11ea-991f-9838cb1324d3.png)
如上图，我每次打开页面的时候，只要用到g6的就会报这个错，请大神帮忙解决。

**Comment by baizn** [comment]
打开什么页面 ？ https://g6.antv.vision/zh 打开官网和官网中的demo也报错？

**Comment by Yanyan-Wang** [comment]
是否使用了 SVG 并且存在 fontSize 小于 12 的文字？

**Comment by csandanov** [comment]
I have the same error when I use a custom node from examples (the first one) https://g6.antv.vision/en/examples/shape/customNode#svgDom

**Comment by Yanyan-Wang** [comment]
> I have the same error when I use a custom node from examples (the first one) https://g6.antv.vision/en/examples/shape/customNode#svgDom

Could you pls provide an online demo, by Codepen.io or some online platforms else you like.

**Comment by lx70770** [comment]
`renderer: 'svg',`
渲染方式改为svg就好了

**Comment by wysdddh** [comment]
厉害了
