### ISSUE TITLE
设置指定边和节点隐藏了，再changeData(),隐藏的边又出来了，节点没有，怎么做能让边也保持隐藏

### ISSUE THREAD

**Issue by qianqianjie1** [antvis/G6#1037]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by baizn** [comment]
调用hide方法。

**Comment by qianqianjie1** [comment]
边数据模型里描述隐藏属性的配置是什么呢

**Comment by baizn** [comment]
数据模型里面没有这个配置，你这个 case 能否提供个在线demo呢？

**Comment by wangxiaogang94** [comment]
好像换个布局，隐藏的节点和变都重新出来了

**Comment by Yanyan-Wang** [comment]
写一个在线 demo 看一下吧
