### ISSUE TITLE
updateItem时无效

### ISSUE THREAD

**Issue by langhuaxing** [antvis/G6#1041]
当shape为ModelRect时
  graph.updateItem( Nodeid, {
                label: "some text"
            });
更新label时无效，
bug,bug,bug

**Comment by Yanyan-Wang** [comment]
非常感谢，确实是一个 bug，将会尝试修复。

**Comment by wfk007** [comment]
更新description，stateIcon也无效

**Comment by Yanyan-Wang** [comment]
在 G6 3.3 以后已修复，现已更新到 v3.4。
