### ISSUE TITLE
downloadImg下载图片报错

### ISSUE THREAD

**Issue by weiweibupt** [antvis/G6#1049]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

downloadImg下载图片报错，Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.求解答

**Comment by Yanyan-Wang** [comment]
写一个在线的 demo 看一下，这样不知道是什么问题呢

**Comment by weiweibupt** [comment]
> 写一个在线的 demo 看一下，这样不知道是什么问题呢

非常感谢您的回答~ 已经没问题了，  周六那天下载就报这个错，昨天今天又可以正常下载图片了，但是我什么也没改
