### ISSUE TITLE
npm中最新版本有3.2.4，为什么tags标签中没有对应的版本？

### ISSUE THREAD

**Issue by GitHub-wk** [antvis/G6#1059]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by baizn** [comment]
之前几个版本没打 tags， 目前最新版本是 3.2.5，打了对应的tags。

**Comment by GitHub-wk** [comment]
之前版本可以也打上tag吗
