### ISSUE TITLE
调用 updateNodesPositon 方法报错

### ISSUE THREAD

**Issue by zunyiGuo** [antvis/g6#106]
![image](https://user-images.githubusercontent.com/19794320/33312782-744a2ac0-d3ee-11e7-9a61-c1018b5541af.png)

**Comment by TomHuangCN** [comment]
写个 codepen ？ https://codepen.io/pen/

**Comment by zunyiGuo** [comment]
https://codepen.io/anon/pen/eePjpK

**Comment by TomHuangCN** [comment]
1. updateNodesPositon => updateNodesPosition 文档上拼写错误十分抱歉
1. 你这个逻辑不需要调用这个方法

**Comment by zunyiGuo** [comment]
再请教下，怎么在操作后更新布局呢？

**Comment by TomHuangCN** [comment]
net.layout() // 这个接口还没开发，1.2.1 版本中有提供
