### ISSUE TITLE
g6.js:9 Uncaught TypeError: n.addEdge is not a function

### ISSUE THREAD

**Issue by CodeBoySun** [antvis/G6#1062]
If this error is caused by adding more nodes which is over max

**Comment by qm8956** [comment]
这个可以从数据的那里看出超过最大值了呢

**Comment by qm8956** [comment]
![E5C67778-8782-4f7b-900A-BD391A5E56AD](https://user-images.githubusercontent.com/18099332/74045265-6486be00-4a07-11ea-80ba-18c20744a4a3.png)
[官方demo](https://codesandbox.io/s/admiring-northcutt-6gelv)， 如果再edges中id存在，并且id再1-8之间就会造成同样的错误，这应该是个bug吧
