### ISSUE TITLE
在svg的渲染模式下调用toFront方法导致节点丢失

### ISSUE THREAD

**Issue by Sql544** [antvis/G6#1067]
* **G6 Version 3.2.4**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

import G6 from '@antv/g6';

const data = {
  nodes: [{
    id: 'node1',
    x: 100,
    y: 200
 },{
    id: 'node2',
    x: 300,
    y: 200
 }],
  edges: [{
    id: 'edge1',
    target: 'node2',
    source: 'node1'
 }]
};
const graph = new G6.Graph({
  renderer: 'svg',
  container: 'mountNode',
  width: 500,
  height: 500
});
graph.on('node:mouseenter', (e) => { 
  e.item.toFront();
})
graph.read(data);

直接run一下上面的代码可复现，移入之后节点消失

**Comment by Yanyan-Wang** [comment]
排查后发现是底层渲染引擎 G 3.x 的原因。等待 G 修复后更新。谢谢

**Comment by Yanyan-Wang** [comment]
暂时可以通过在每次 toFront 之后手动调用 graph.paint() 重新绘制一下

**Comment by Yanyan-Wang** [comment]
v3.4 之后的 svg 不会出现报错并消失的情况，但目前 svg 的 toFront 不生效，下个小版本修复。归并到 https://github.com/antvis/G6/issues/1305
