### ISSUE TITLE
demo link not exist!

### ISSUE THREAD

**Issue by wbpmrck** [antvis/g6#107]
this demo is missed:https://antv.alipay.com/zh-cn/g6/1.x/demo/04-editor/perventLink.html

<img width="1177" alt="miss_demo" src="https://user-images.githubusercontent.com/1442515/33354640-d1eb9500-d4ee-11e7-8d4c-63b2445507cd.png">

**Comment by TomHuangCN** [comment]
will add this week

see here for a moment: https://codepen.io/DoriTong/pen/yPRqOv
