### ISSUE TITLE
fitView导致页面元素过大,size失效

### ISSUE THREAD

**Issue by Rain20199** [antvis/G6#1073]
当用fitview时 页面节点少的时候,会被放大,这个怎么控制？

**Comment by Yanyan-Wang** [comment]
fitView 可以理解为“把一个图片放大”，即所有的内容等比例放大。

如果你只想让所有元素的平均中心移动到画布中心，而不放缩元素，可以尝试 graph.moveTo（https://g6.antv.vision/zh/docs/api/Graph/#movetox-y） 或者 graph.translate（https://g6.antv.vision/zh/docs/api/Graph/#translatedx-dy）

但这两个方法只是在平移画布，在图的坐标范围超出屏幕范围的情况下，会有超出的部分。另一个方案可以自己遍历一遍数据，找出最大最小坐标及范围，将数据中的坐标进行归一化到 [0, 屏幕宽度] 和 [0, 屏幕高度] 中。然后重绘一下图。
