### ISSUE TITLE
边动画'line-dash'样例中，设置duration时间不起作用

### ISSUE THREAD

**Issue by lingodan** [antvis/G6#1074]
在项目中调试line-dash样例，发现设置动画时间不起作用，剩下的两种动画（circle-running，line-growth） duration参数设置正常工作。
https://codepen.io/Yanyan-Wang/pen/yLLJJoJ

**Comment by Yanyan-Wang** [comment]
你好。你可能需要理解一下 line-dash 的原理，它是虚线数每一帧往前移动一个元素，不论设置多少 duration，每一帧都是移动一个。如果想变慢，可以尝试每两帧/多帧往前移动一个元素。变快同理。
