### ISSUE TITLE
在umi下使用extraBabelIncludes无法转化箭头函数

### ISSUE THREAD

**Issue by qizhancheng** [antvis/G6#1075]
配置
`es5ImcompatibleVersions: true,`
 `extraBabelIncludes: [path.resolve('node_modules/@antv')],`

无法转化build下的g6.js内：
h=new Map(t.map((n,r)=>[u(n,r,t),n]));

**Comment by baizn** [comment]
是个BUG，下个 TS 版本会修复这个问题！

**Comment by Yanyan-Wang** [comment]
目前在 G6 中没有 new Map 了
