### ISSUE TITLE
zoom过小时，canvas-zoom失效

### ISSUE THREAD

**Issue by wangxiaogang94** [antvis/G6#1077]
数据量很大，minzoom=0.01，当zoom小于0.03时，fitView后，canvas-zoom失效。去掉minzoom时，fitview失效。
下面是代码，拷贝到官网demo就可以。
import G6 from '@antv/g6';

const width = document.getElementById('container').scrollWidth;
const height = document.getElementById('container').scrollHeight || 500;
const graph = new G6.Graph({
  container: 'container',
  width,
  height,
  minZoom:0.001,
  layout: {
    type: 'force',
     onLayoutEnd: () => {
          console.log('布局完成');
          graph.fitView(20);
        },
  },
        modes: {
        default: [
          'activate-relations',
          'drag-canvas',
          'drag-node',
          'zoom-canvas',
        ]
      },
  defaultNode: {
    size: 15,
    color: '#5B8FF9',
    style: {
      lineWidth: 2,
      fill: '#C6E5FF'
    }
  },
  defaultEdge: {
    size: 1,
    color: '#e2e2e2'
  }
});

fetch('https://gw.alipayobjects.com/os/antvdemo/assets/data/relations.json')
  .then(res => res.json())
  .then(data => {
  const nodes = data.nodes;
  for(let i =0;i<200;i+=1){nodes.push({id:1+999})}
    graph.data({
      nodes: nodes,
      edges: data.edges.map(function(edge, i) {
        edge.id = 'edge' + i;
        return Object.assign({}, edge);
      })
    });
    graph.render();

    graph.on('node:dragstart', function(e) {
      graph.layout();
      refreshDragedNodePosition(e);
    });
    graph.on('node:drag', function(e) {
      refreshDragedNodePosition(e);
    });
    graph.on('node:dragend', function(e) {
      e.item.get('model').fx = null;
      e.item.get('model').fy = null;
    });
  });

function refreshDragedNodePosition(e) {
  const model = e.item.get('model');
  model.fx = e.x;
  model.fy = e.y;
}

**Comment by wangxiaogang94** [comment]
找到原因了。源码里zoom-canvas限定了minzoom为0.01

**Comment by Yanyan-Wang** [comment]
因为默认有最大最小放缩值。可以在 zoom-canvas 配置项或者 graph 配置项里更改 minZoom 和 maxZoom：https://g6.antv.vision/zh/docs/manual/middle/states/defaultBehavior/#zoom-canvas

**Comment by yuhang1995** [comment]
> 可以在zoom-canvas配置项或图形配置项里更改minZoom和maxZoom：[https](https://g6.antv.vision/zh/docs/manual/middle/states/defaultBehavior/#zoom-canvas) ://g6.antv.vision/zh/docs/manual/middle/states/defaultBehavior/#zoom [-帆布](https://g6.antv.vision/zh/docs/manual/middle/states/defaultBehavior/#zoom-canvas)

在脑树图中，设置了最小缩放和最大缩放，在数据过多后，缩放也会失效

**Comment by Yanyan-Wang** [comment]
> > 可以在zoom-canvas配置项或图形配置项里更改minZoom和maxZoom：[https](https://g6.antv.vision/zh/docs/manual/middle/states/defaultBehavior/#zoom-canvas) ://g6.antv.vision/zh/docs/manual/middle/states/defaultBehavior/#zoom [-帆布](https://g6.antv.vision/zh/docs/manual/middle/states/defaultBehavior/#zoom-canvas)
> 
> 在脑树图中，设置了最小缩放和最大缩放，在数据过多后，缩放也会失效

是否已经达到了最小/最大的缩放倍率？
