### ISSUE TITLE
HTML node can not autoscale when canvas scaled!

### ISSUE THREAD

**Issue by wbpmrck** [antvis/g6#108]
RT,when i use HTML custom node,and scroll to scale the whole canvas:
- the normal node can scale perfectly
- the html node stay the origin size,can not scale.

![scale_error](https://user-images.githubusercontent.com/1442515/33355011-8e6e2e44-d4f0-11e7-8fe5-9935da02a919.png)

**Comment by TomHuangCN** [comment]
not support yet
