### ISSUE TITLE
drag事件

### ISSUE THREAD

**Issue by wushu843639932** [antvis/G6#1080]
鼠标在node节点上按下拖拽移动，一旦拖拽到其他DOM元素上，然后放开鼠标，在经行鼠标移动时，canvas画布就会随着鼠标经行移动，我看了鼠标在进入DOM元素上松开鼠标后，并没有触发dragend事件，有什么方法可以解决吗

**Comment by SaberInoryKiss** [comment]
canvas:dragend，拖拽画布，用这个。老哥好好查文档呀，https://antv-g6.gitee.io/zh/docs/api/Event

**Comment by wushu843639932** [comment]
> canvas:dragend，拖拽画布，用这个。老哥好好查文档呀，https://antv-g6.gitee.io/zh/docs/api/Event

@SaberInoryKiss 见#903说是一个bug,

**Comment by SaberInoryKiss** [comment]
@wushu843639932 哦哦，看到了，这个东西我也遇到了23333

**Comment by wushu843639932** [comment]
@SaberInoryKiss 你怎么解决的啊

**Comment by baizn** [comment]
同 #903  是个BUG，3.3 版本中修复。
