### ISSUE TITLE
modelRect节点的descriptionCfg好像不管用

### ISSUE THREAD

**Issue by yangcomes** [antvis/G6#1082]
modelRect节点，想改变描述的字体，但是改变descriptionCfg好像不管用呢，放在style里面或外面都不行，fill和stroke都配了也不行呢。

**Comment by yangcomes** [comment]
{
    id: 'n_3',
    x:70,
    y:70,
shape : 'modelRect',
    label : '完成',
    description : 88,

    descriptionCfg : {
     style: {
      fill : '#F00',
      stroke : '#0F0',
     },
     fill : '#F00',
     stroke : '#0F0',

    }
   },

**Comment by Yanyan-Wang** [comment]
抱歉，这个功能在下个版本中发布。目前 description 是固定的样式。

**Comment by Yanyan-Wang** [comment]
新版本已支持
