### ISSUE TITLE
不给一个节点设置坐标时，导致其他所有节点都会随机在画布上生成

### ISSUE THREAD

**Issue by SaberInoryKiss** [antvis/G6#1084]
* **G6 Version**:^3.2.4
* **Platform**:
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/39288809/71353515-3f9fce00-25b4-11ea-8701-2ccb953d3307.png)

* **CodePen Link**:https://codepen.io/saberinorykiss/pen/XWJREXJ

当我给一个节点设置为undefined时，将会导致所有节点都会在画布上随机生成，正常情况不应该是node2节点坐标固定，node1随机生成吧？

**Comment by SaberInoryKiss** [comment]
每一次刷新页面，两个节点都会重新随机生成

**Comment by Yanyan-Wang** [comment]
这确实是一个可以改善的问题。目前的判断方式是看节点数据中的第一个节点是否含有位置信息，如果没有且没有配置布局方法则全部 random。准备在后面的版本中解决。谢谢

**Comment by Yanyan-Wang** [comment]
V3.2.6 已支持
