### ISSUE TITLE
fitView不生效

### ISSUE THREAD

**Issue by wuh** [antvis/G6#1085]
请帮忙看看这里使用了fitView后为什么没有缩放到能够查看到所有的节点呢？感觉还是有BUG呢
![1](https://user-images.githubusercontent.com/624533/71386824-62b99480-262b-11ea-9b9d-5397dd4c4bd4.png)
![2](https://user-images.githubusercontent.com/624533/71386855-a6140300-262b-11ea-83e0-6d6c50899dfe.png)

**Comment by Yanyan-Wang** [comment]
因为这是力导向布局，节点位置、范围每一帧都会有变化，不适合使用 fitView ，否则会出现节点忽大忽小的状况。如果希望控制力导向布局的范围，建议配置 layout 的 center，并通过每一帧的回调函数移回超出屏幕的节点：https://g6.antv.vision/zh/examples/net/forceDirected#forceConstrainedInRect
