### ISSUE TITLE
鼠标点击分组，怎么获取点击的分组对象，id，及model，实在没找着，thanks！

### ISSUE THREAD

**Issue by maomaoispan** [antvis/G6#1086]
```
this.graph.on('group:click', event => {
            const item = event.target
            console.log(item)
            const model = item ? item.getModel() : null
            console.log(model)
 })
```
这样不起作用，

```
this.graph.on('click', event => {
            const item = event.target
            console.log(item)
            const model = item ? item.getModel() : null
            console.log(model)
 })
```
这样没有model

**Comment by baizn** [comment]
目前 3.x 中只能获取到 group 的名称、id 等基本数据，通过 target 判断，现在 group 不是一个 Item 。

**Comment by zhoustudent** [comment]
> 目前 3.x 中只能获取到 group 的名称、id 等基本数据，通过 target 判断，现在 group 不是一个 Item 。

您好，想问下我在一个node节点中添加了多个shape，当我点击这个节点的时候我如何确定是点击了哪个shape呢，麻烦看到的话还请及时回一下，在线急等

**Comment by baizn** [comment]
> > 目前 3.x 中只能获取到 group 的名称、id 等基本数据，通过 target 判断，现在 group 不是一个 Item 。
> 
> 您好，想问下我在一个node节点中添加了多个shape，当我点击这个节点的时候我如何确定是点击了哪个shape呢，麻烦看到的话还请及时回一下，在线急等

通过 target 来判断，建议给每个添加的shape加一个name或className属性区分
