### ISSUE TITLE
节点点击报错

### ISSUE THREAD

**Issue by lxfu** [antvis/G6#1087]
* **G6 Version**: "3.2.5",
* **Platform**:  mac
* **Mini Showcase(like screenshots)**: 
![CA653F21-B0EC-4835-B282-5EC4293FBDB3](https://user-images.githubusercontent.com/20291784/71413476-536b3300-268d-11ea-8f5a-a3c47afb4015.png)

![5648ADD0-50ED-4F39-A8B6-C33286E062C4](https://user-images.githubusercontent.com/20291784/71413539-9c22ec00-268d-11ea-8622-0409c9ad5a7d.png)

* **CodePen Link**:  https://antv-g6.gitee.io/zh/examples/shape/basic#circle

实例化时添加modes: {default: ['collapse-expand']}，点击点击报错，源码src/behavior/collapse-expand.js里面应该做下容错处理。

**Comment by lxfu** [comment]
点击节点，不是点击点击！

**Comment by Yanyan-Wang** [comment]
除了加了 modes 还有别的操作吗？ 我这里没有复现

**Comment by lxfu** [comment]
> 除了加了 modes 还有别的操作吗？ 我这里没有复现

没有，就设置了modes: {default: ['collapse-expand']}，我这里每次都报错，打开控制台看看呢？

**Comment by Yanyan-Wang** [comment]
试了几次都没有诶😅
