### ISSUE TITLE
插件相关问题

### ISSUE THREAD

**Issue by LeToNode** [antvis/g6#109]
近期在针对G6进行图形方面的可用性方面的调研，发现图库本身还是想做得更多的，目前提供的内容已经能够满足部分场景的使用了，我有几个问题想

1. template.analysis.maxSpanningForest 的属性配置（包含连线方式，锚点位置等信息）和点击菜单可否进行自定义？
2.连线间锚点位置和连接线箭头样式的示例太简单了。
3.能否提供相对完善的文档方便进行自定义方面的插件和模板开发。

**Comment by TomHuangCN** [comment]
1.1 连线方式及锚点参考 [自定义形]()https://antv.alipay.com/zh-cn/g6/1.x/tutorial/custom-shape.html 文档。
1.2 菜单自定义用 nodeToolCfg 这个配置项。[maxspanningforest](https://antv.alipay.com/zh-cn/g6/1.x/api/plugins.html#_template.analysis.maxSpanningForest--最大生成森林图分析模版)
2. 可以构造自定义箭头 https://antv.alipay.com/zh-cn/g6/1.x/tutorial/custom-shape.html#_自定义箭头
3. 目前自定义的主要方式还是利用参考这篇文档[自定义形]()https://antv.alipay.com/zh-cn/g6/1.x/tutorial/custom-shape.html ，配合[绘图引擎](https://antv.alipay.com/zh-cn/g6/1.x/api/canvas.html)，进行二次开发
