### ISSUE TITLE
Minimap: 将图放大到一定程度，拖拽minimap,画布移动不到对应位置

### ISSUE THREAD

**Issue by szwc** [antvis/G6#1093]
* **G6 Version **:
3.1.4-beta.1
* **Platform**:
win7   chrome 79.0.3945.88
* **Mini Showcase(like screenshots)**:

![image](https://user-images.githubusercontent.com/22705781/71467790-f099a900-27fe-11ea-9011-42ce285c0a42.png)

* **CodePen Link**:

**Comment by jiangyangchang** [comment]
同问，这个问题解决了吗？

**Comment by szwc** [comment]
> 同问，这个问题解决了吗？

更新到新版本就可以了
