### ISSUE TITLE
请问使用了changeData()方法之后，页面好像会不会自动进行渲染？

### ISSUE THREAD

**Issue by feng-java** [antvis/G6#1099]
* **G6 Version**: 3.0.4
* **Platform**: 
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

我的需求是后端通过websocket给前端推送节点的执行状态，前端实时的修改数据，并交给G6渲染图形。
刚开始每次都graph.clear数据，并且重新调用graph.render方法渲染，因为渲染频率较高，所以基本卡死，所以想尝试使用changeData方法修改数据，测试这样会不会卡
请问使用changeData()方法，会自动重新渲染页面吗？
以及我这种场景，使用什么样的方法会减轻浏览器的负担，不至于太卡？

**Comment by baizn** [comment]
数据变了就会重新渲染。数据量大小呢？

**Comment by feng-java** [comment]
150个node，也是一百多条edge，会是因为卡吗？为什么我这边的图没有变化。。。

**Comment by Yanyan-Wang** [comment]
写一个在线 demo 看一下吧

**Comment by feng-java** [comment]
那请问一下，changedata方法渲染的速度，跟render渲染的速度，本质上会有很大区别吗？我这个涉及到节点的状态频繁改变，重新渲染视图，所以渲染频率比较高，想找一个合适的方式渲染，可以介绍一个比较好的方式吗？------------------ 原始邮件 ------------------
发件人: "Yanyan Wang"<notifications@github.com>
发送时间: 2019年12月30日(星期一) 上午10:26
收件人: "antvis/G6"<G6@noreply.github.com>;
抄送: "feng-java"<81099173@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [antvis/G6] 请问使用了changeData()方法之后，页面好像会不会自动进行渲染？ (#1099)



写一个在线 demo 看一下吧
 
&mdash;

**Comment by Yanyan-Wang** [comment]
changeData 会做 diff，如果新数据中存在与旧数据 id 相同的节点，那么就不会被改变了。你的场景是不是只是已有节点样式的变化？而不是全量更换全新的数据？

**Comment by feng-java** [comment]
是的，我的场景是已有节点的样式的变化。我现在的用法是先调用graph.clear()清除数据，再调用render(data)将修改样式后的数据渲染了以下，我的节点后面可能会到好几千，每次这样重新渲染可能比较卡，请问有比我这个方式更好的方式解决这个场景吗？

**Comment by Yanyan-Wang** [comment]
只是已有节点样式变化的话可以用 graph.updateItem，不用全部删掉重新添加。

G6 近期将发布迁移了底层渲染引擎的新版本，届时会有局部渲染，将会提升性能。

**Comment by caojin24** [comment]
更新底层渲染引擎的版本发布了？

**Comment by hhlcom** [comment]
> 只是新增节点样式的变化的话可以用graph.updateItem，不用全部删掉重新添加。
> 
> G6 近期将发布迁移的新版本，届时将呈现出更高的性能。
updateItem更新数据之后，当前数据的视图可以根据updateItem的数据重新进行自定义节点得绘制么(只针对于updateItem的这个节点单独)，现在貌似好像没有什么办法
