### ISSUE TITLE
生态树例子是空白的

### ISSUE THREAD

**Issue by Hongbo-Miao** [antvis/g6#110]
生态树例子目前是空白的。

https://antv.alipay.com/zh-cn/g6/1.x/demo/tree/dendrogram.html

BTW, awesome library!

![image](https://user-images.githubusercontent.com/3375461/33463128-8a2dd914-d5f0-11e7-97fa-e983dd79b14a.png)

**Comment by TomHuangCN** [comment]
下个版本会修复（每周周一发）
