### ISSUE TITLE
请问渲染页面如何不改变这次的画布的大小以及位置？

### ISSUE THREAD

**Issue by feng-java** [antvis/G6#1102]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

问题背景：画布中节点比较多，需要放大了来看，在看的过程中，由于后台数据实时的改变，会更新画布的数据源，触发了重新渲染，页面又跑到别的地方去了。
如何在更新数据源，渲染页面之后不改变页面的拖放比例以及正在观看的位置呢？

**Comment by baizn** [comment]
这个需要自己保存下当前比例及位置，有新数据时候渲染后恢复到当前配置，另外可以考虑使用子图布局，看这个 https://g6.antv.vision/zh/examples/net/layoutMechanism#subgraphLayout  能解决你的问题不？

**Comment by feng-java** [comment]
您好，我的图使用的是dagre层次布局，我在给的网址文档中没有找到如何获取当前比例及位置的方法，请问dagre层次布局如何获取当前比例及位置？
另外，没有太看明白子图布局的含义及场景。有空的话可以解释一下，谢谢。

**Comment by Yanyan-Wang** [comment]
graph.getZoom() 获取当前画布缩放比例，和使用何种布局无关：https://g6.antv.vision/zh/docs/api/Graph/#getzoom 。

节点位置在布局后已经存储到节点的 model 上面。

子图布局在布局时仅考虑一部分元素：https://g6.antv.vision/zh/docs/manual/middle/layout/#%E5%AD%90%E5%9B%BE%E5%B8%83%E5%B1%80 。

**Comment by wanlibing** [comment]
> * **G6 Version**:
> * **Platform**:
> * **Mini Showcase(like screenshots)**:
> * **CodePen Link**:
> 
> 问题背景：画布中节点比较多，需要放大了来看，在看的过程中，由于后台数据实时的改变，会更新画布的数据源，触发了重新渲染，页面又跑到别的地方去了。
> 如何在更新数据源，渲染页面之后不改变页面的拖放比例以及正在观看的位置呢？

你好，我也在找类似解决方案，请问解决了吗？

**Comment by Kido-200** [comment]
因为数据源更新导致的zoom，位置改变不会触发viewportchange。

我通过监听viewportchange实时获取图的矩阵，  再在afterrender事件里graph.getGroup().setMatrix(martix);  解决了。
