### ISSUE TITLE
关于window._的问题

### ISSUE THREAD

**Issue by shepiguai** [antvis/G6#1106]
* **G6 Version**:3.0.5-beta.7
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

3.0.5-beta.7之后的版本把_(lodash)挂载window下，本人的项目也把_(underscore)挂载window下，lodash的_覆盖了underscore的_，请问G6能不要把_挂载在window下吗,3.0.5-beta.7之前的版本没有这个问题
![企业微信截图_86498db5-238e-4f29-947e-cb32f85924af](https://user-images.githubusercontent.com/25193960/71616268-48b22000-2bf0-11ea-9728-4ad3f6950bd1.png)

**Comment by baizn** [comment]
的确是个问题，3.3 版本中我们修复一下

**Comment by wangchengcheer** [comment]
请问这个问题修复了吗？@baizn

**Comment by baizn** [comment]
下周发布 3.5.11 修复，详见 https://github.com/antvis/G6/pull/1782
