### ISSUE TITLE
使用iconfont图标无效

### ISSUE THREAD

**Issue by yuhaijian** [antvis/G6#1108]
把文档中使用iconfont的代码复制到本地使用运行了一遍，并不能生成对应的图标，还是显示Unicode码。iconfont.css引入正常。
![1577956027(1)](https://user-images.githubusercontent.com/18440666/71659381-57304100-2d82-11ea-84aa-8a31138e98f6.jpg)

**Comment by spacetoz** [comment]
我也遇到这个问题了

**Comment by yuhaijian** [comment]
我解决了，是它官网文档上没有说清楚，text的值是iconfont.css里的content，然后在 \ 后面加上u就可以了。例: text: '\ue91f'

**Comment by spacetoz** [comment]
好的，谢谢您，我去试一下。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yuhaijian"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月7日(星期二) 上午9:09
收件人:&nbsp;"antvis/G6"<G6@noreply.github.com&gt;;
抄送:&nbsp;"赵瑞虎"<zofmailbox@foxmail.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [antvis/G6] 使用iconfont图标无效 (#1108)




我解决了，是它官网文档上没有说清楚，text的值是iconfont.css里的content，然后在 \ 后面加上u就可以了。例: text: '\ue91f'

**Comment by Yanyan-Wang** [comment]
感谢指正
