### ISSUE TITLE
请添加内置Behavior中click-select的选中回调

### ISSUE THREAD

**Issue by TNG-China** [antvis/G6#1109]
![image](https://user-images.githubusercontent.com/21065884/71660650-b2643280-2d86-11ea-8a4c-0eda2fe3346d.png)

缺少回调无法获取多个选中的节点

**Comment by baizn** [comment]
TS 版本中已解决，https://github.com/antvis/G6/blob/dev-3.3/src/behavior/click-select.ts#L60
TS版本目前在紧张测试中，敬请期待！

**Comment by Yanyan-Wang** [comment]
新版本已发布。
