### ISSUE TITLE
G6绘制关系图谱，自定义节点（自定义图片节点），不能拖动图片节点

### ISSUE THREAD

**Issue by frontendWangqun** [antvis/G6#1114]
G6绘制关系图谱，自定义节点（自定义图片节点），不能拖动图片节点，当不自定义节点的时候就可以随意拖动节点，当自定义节点的时候不能拖动，麻烦解答一下

* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
麻烦写一个在线 demo 看一下

**Comment by yomie123** [comment]
同样的问题，3.2.5版本可以拖动，之后升级了之后就不行了

**Comment by Yanyan-Wang** [comment]
自定义节点的 shape 中需要增加 draggable: true 配置。见：https://g6.antv.vision/zh/docs/manual/FAQ/upgradeGuide/#%E5%A2%9E%E5%8A%A0%E5%9B%BE%E5%BD%A2
