### ISSUE TITLE
dagre layout gets different result with different order of edges

### ISSUE THREAD

**Issue by InfiniteSword** [antvis/G6#1115]
* **G6 Version**: 3.2.7
* **Platform**: 
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://codesandbox.io/s/nice-bhaskara-5839z

**nodes**
```
[
  {
    id: "node1"
  },
  {
    id: "node2"
  },
  {
    id: "node3"
  },
  {
    id: "node4"
  }
]
```
**edges**
```
[
  {
    source: "node1",
    target: "node2"
  },
  {
    source: "node1",
    target: "node3"
  },
  {
    source: "node2",
    target: "node4"
  },
  {
    source: "node1",
    target: "node4"
  },
  {
    source: "node3",
    target: "node4"
  }
]
```
**result**
![image](https://user-images.githubusercontent.com/10394516/71811579-0b4a0880-30b0-11ea-8167-d0373ca8a41c.png)

Just exchange edges[3] & edges[4]:

**edges**
```
[
  {
    source: "node1",
    target: "node2"
  },
  {
    source: "node1",
    target: "node3"
  },
  {
    source: "node2",
    target: "node4"
  },
  {
    source: "node3",
    target: "node4"
  },
  {
    source: "node1",
    target: "node4"
  }
]
```
**result**
![image](https://user-images.githubusercontent.com/10394516/71811693-56641b80-30b0-11ea-9119-2b3c8921ca4f.png)

**Comment by Yanyan-Wang** [comment]
Dagre is an ordering-aware layout algorithm. 

Dagre in G6 depends on the [dagre.js](https://github.com/dagrejs/dagre), which implements several (papers)[https://github.com/dagrejs/dagre/wiki#recommended-reading]. 

For the reason why it is ordering-aware, please refer to one of these papers: [Gansner, et al., "A Technique for Drawing Directed Graphs"](http://www.graphviz.org/Documentation/TSE93.pdf)

**Comment by InfiniteSword** [comment]
But it's hard to figure out how does this algorithm calculate the layout. 

The second one above has already lost some 'edge' information: 

![image](https://user-images.githubusercontent.com/10394516/71948525-3dbc4880-320b-11ea-8b5c-4da7dc311c69.png)

Is there any good way to sort the edges?

**Comment by Yanyan-Wang** [comment]
Checkout this issue of dagre: https://github.com/dagrejs/dagre/issues/145.
It is a limitation of this algorithm. The issue has been opened 2014 and not been solved yet.
I think G6 will not solve this problem since we only depend on it.
