### ISSUE TITLE
vue 里面g6-plugins用不了

### ISSUE THREAD

**Issue by ysjsgzq** [antvis/g6#112]
![tim 20171204153938](https://user-images.githubusercontent.com/16972323/33541246-5d9d29ba-d909-11e7-97c3-34b80c27990a.png)

**Comment by JunningCui** [comment]
react也用不了。昨天install的就不行，之前的可以

**Comment by Carrotzpc** [comment]
react 遇到了同样的问题

**Comment by TomHuangCN** [comment]
重新安装一下，1.0.2
```js
@antv/g6-plugins@1.0.2
```

**Comment by JunningCui** [comment]
@TomHuangCN T安了，也没有解决这个问题，是这个版本有问题吗
