### ISSUE TITLE
G6.registerArrow

### ISSUE THREAD

**Issue by lsd1** [antvis/G6#1123]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
请描述清楚问题和需求。。

**Comment by lsd1** [comment]
为什么现在不能注册箭头，我看语雀的文档上有这个方法，但是在3.14版本却无法使用该方法

**Comment by Yanyan-Wang** [comment]
你说的是这个吗：https://www.yuque.com/antv/g6/esxg39
这个是设计文档，只是可能考虑提供这样的接口。目前一直都没有提供注册箭头，最新文档请参考官网。
