### ISSUE TITLE
树图相邻节点高亮交互activate-relations会因为收缩展开交互collapse-expand导致BUG

### ISSUE THREAD

**Issue by lsd1** [antvis/G6#1128]
* **G6 Version**: 3.1.4-beta.1
* **Platform**:  win10 chrome 65.0.3325.181
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://codepen.io/lsd-stone/pen/RwNMZYR

当触发 展开和收缩子节点后，相邻节点高亮有BUG，节点出现严重偏移。

**Comment by Yanyan-Wang** [comment]
v3.3.1 以后的版本已经没有这个问题。现在最新版本是 v3.4
https://codepen.io/Yanyan-Wang/pen/LYVdLwG
