### ISSUE TITLE
[Bug report] 子节点位置偏移错误

### ISSUE THREAD

**Issue by zoneus** [antvis/G6#1130]
* **G6 Version**:
* **platform**:chrome浏览器
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/30338668/72134375-df37cb80-33be-11ea-8f62-38d6fef614ac.png)

* **CodePen Link **:https://codesandbox.io/s/blazing-browser-8uc4p?fontsize=14&hidenavigation=1&theme=dark

先点击shape节点，将其收缩。再将graph节点收缩再展开，可以看到它的节点跑到上面去了

**Comment by Yanyan-Wang** [comment]
感谢指正，官网 demo 实现有误。即将修复，正确版暂时请看：https://codesandbox.io/s/filesystem-collapse-n2m4n
