### ISSUE TITLE
fill如何使用渐变色gradient

### ISSUE THREAD

**Issue by howhw** [antvis/G6#1132]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by hyhyy** [comment]
同求 目前是使用img实现渐变色背景 如果有style实现的话最简单

**Comment by Yanyan-Wang** [comment]
https://www.yuque.com/antv/g6/smhvyn#a9fc2d0f

**Comment by hmgjwn** [comment]
v5.0.21版本，径向渐变没有正确生效，渐变中心及渐变半径都无法控制
