### ISSUE TITLE
fittingString函数对于中文字符不兼容

### ISSUE THREAD

**Issue by GitHub-wk** [antvis/G6#1136]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

fittingString(str, maxWidth, fontSize)函数对于参数str为纯中文或纯英文时，返回的字符串长度一样。但是中文与英文界面占的宽度是不一样的（10个中文字符的长度>10个英文字符的长度）

**Comment by Yanyan-Wang** [comment]
确实存在这个问题，因为中英文每个“字”的宽度不同。这是个工具方法，在 G6 3.3 正式版中将修复这个问题。

若使用旧版 G6，可以自己写一下这个方法：
const fittingString = (str, maxWidth, fontSize) => {
    const unitWidth = 1.3;
    const fontWidth = fontSize * unitWidth;
    maxWidth = maxWidth * 2;
    const width = calcStrLen(str) * fontWidth;
    const ellipsis = '…';
    if (width > maxWidth) {
      let widthSum = 0, charCount = 0;
      const max = Math.floor((maxWidth - 10) / fontWidth);
      while (widthSum <= max) {
        if (str.charCodeAt(charCount) > 0 && str.charCodeAt(charCount) < 128) {
          widthSum++;
        } else {
          widthSum += 2;
        }
        charCount++;
      }
      if (str.length > charCount - 1) {
        const result = str.substring(0, charCount - 1) + ellipsis;
        return result;
      }
    }
    return str;
  };
