### ISSUE TITLE
save函数的一个bug: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by feng5** [antvis/g6#114]
https://antv.alipay.com/zh-cn/g6/1.x/demo/other/anchor-attr.html 这个例子。

在73行的 `net.render()` 之后增加
```
net.on('itemremove',function(){
	net.save();
});
```
运行后鼠标全选节点和边，然后delete删除，报错 `Uncaught TypeError: Cannot read property 'get' of undefined`，详细
```
Uncaught TypeError: Cannot read property 'get' of undefined
    at VM207 g6.min.js:8
    at Object.each (VM207 g6.min.js:5)
    at t (VM207 g6.min.js:8)
    at t._saveSource (VM207 g6.min.js:8)
    at t.save (VM207 g6.min.js:6)
    at <anonymous>:62:6
    at VM207 g6.min.js:3
    at Object.each (VM207 g6.min.js:5)
    at t.fire (VM207 g6.min.js:3)
    at t.removeItem (VM207 g6.min.js:6)
```

**Comment by feng5** [comment]
本来打算通过itemremove事件在删除边之后将对应的描点更新为 `linkable: true` 的，不过这个事件触发之后edge已经销毁无法获取该edge的相关信息，因此想通过遍历来更新，没想到这时候save方法出错了.

**Comment by TomHuangCN** [comment]
1. 目前的 itemremove 真实含义是 beforeitemremove，应该是能拿到 edge 相关信息的
2. net.save 报错是 bug ，下个版本修复

**Comment by feng5** [comment]
```
net.on('itemremove',function(ev){
	console.log(ev);
});
```
拿到的item属性都是空的而且 `destroyed: true`,  应该是 afteritemremove吧？

**Comment by TomHuangCN** [comment]
你打个断点。console.log 出来的当前状态肯定是destroyed的，没毛病
