### ISSUE TITLE
画布中的节点怎么监听到画布外来的拖拽事件

### ISSUE THREAD

**Issue by Iamsuler** [antvis/G6#1143]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

如图，我想把画布外的那个“+”按钮拖拽到画布内，然后能监听到我是在哪个节点上面释放。
![image](https://user-images.githubusercontent.com/26576925/72439621-3df7ad80-37e2-11ea-8ef7-1f46ca3e5596.png)

**Comment by baizn** [comment]
用 graph.on('drop', evt => {})

**Comment by Iamsuler** [comment]
这个方法只是监听画布的拖动后释放的drop，并不能监听外部拖动到画布内然后释放的drop时间。
请见 https://codepen.io/iamsuler/pen/xxbaLwg

**Comment by blacksola** [comment]
在画布的div上添加dragover事件，当外部节点拖拽到画布div中的触发div的dragover事件的时候手动触发graph的canvas:mousemove事件
