### ISSUE TITLE
画布使用 alttab 之后就没办法拖动，需要再按crtl界面才能规避

### ISSUE THREAD

**Issue by cofjee** [antvis/G6#1148]
如题， 再windows下 使用alt-tab切换程序之后，就没办法拖动了，只有再按ctrl界面才能使用

**Comment by Yanyan-Wang** [comment]
新版本尝试一下：https://g6.antv.vision/zh/examples/tree/compactBox
我们这边 mac 测试没问题。暂时没有 windows 电脑，麻烦你先看下有没有问题。
