### ISSUE TITLE
力导向布局中（force），自定义linkDistance的每个迭代里拿不到data数据中自己加的属性

### ISSUE THREAD

**Issue by keepAwayFrom404** [antvis/G6#1154]
* **G6 Version： 3.2.3**:
* **Platform：mac mini 10.14.4**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

问题：
我想根据在edge里定义的weight属性来自定义每条边的长度，但是在每个迭代里拿不到weight参数
原因：
G6的力导向布局时引用了d3的，它传递给linkDistance的参数时被重写了的而不是数据本身
愿景：
希望能拿到自定义的数据
问题演示：
https://codepen.io/keepawayfrom404/pen/zYxmOgy

**Comment by Yanyan-Wang** [comment]
在 3.4.1 修复，已发布

**Comment by chaegumi** [comment]
最新版的3.5.5在vuejs中使用，打开了workerEnable之后获取不到d的值，还报错

```javascript

layout: {
        type: "force",
        linkDistance: (d: any) => {
           console.log(d);

        //   return 100;
        },
        preventOverlap: true,
        workerEnabled: true // 加了这个会报failed to load SourceMap，然后d连打印都没打印，去掉workerEnabled就可以打印
      }

```
