### ISSUE TITLE
create-react-app --template typescript Cannot find module '@antv/g6'

### ISSUE THREAD

**Issue by HaloWang** [antvis/G6#1155]
* **G6 Version**:
`3.3.0-beta`
* **Platform**:
```
macOS 10.15.2 (19C57)
yarn v1.19.1
node v12.14.0
vscode Version: 1.41.1
```
* **Mini Showcase(like screenshots)**:
```
cd Desktop
npx create-react-app foobar --template typescript
cd foobar
yarn add @antv/g6@3.3.0-beta
yarn start
```
open `App.tsx`
add `import G6 from '@antv/g6'`
error:
<img width="461" alt="Screen Shot 2020-01-19 at 15 37 36" src="https://user-images.githubusercontent.com/7344724/72676938-a5a74480-3ad1-11ea-9d80-147b81655d25.png">
<img width="338" alt="Screen Shot 2020-01-19 at 15 38 39" src="https://user-images.githubusercontent.com/7344724/72676948-cec7d500-3ad1-11ea-8f74-16d55748f960.png">

* **CodePen Link**:

**Comment by baizn** [comment]
是个BUG，文件路径不对，更新到3.3.0-beta.2就可以了。
