### ISSUE TITLE
无法自定义拓展item类型

### ISSUE THREAD

**Issue by laidaxian** [antvis/G6#1157]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

我查看了源码，例如我需要扩展一个继承于item的class(比如node,edge)，举例需要扩展group。G6里面group的方式是一种源码侵入式的方式，改了很多的源码去适配它（非常多的if else，而且不是继承于item）。所以比如我还需要扩展一个这样类似的group，而且我想在结构上更完整一些，因为我认为它应该也应该继承于item，那我不得不重写源码的很多方法去覆盖它，这非常不合理。例如下面我重写了graph和controller里面的一些方法，当然有些能用钩子完成的我就用的是钩子。
![image](https://user-images.githubusercontent.com/26853867/72677500-0cc7f780-3ad8-11ea-9895-b198f579aa26.png)
还有的问题是，我既然扩展的是继承于item，但是g6并没有把item这个类暴露出来，导致我不得不重写一个结构相似的item类.
![image](https://user-images.githubusercontent.com/26853867/72677540-7d6f1400-3ad8-11ea-96ff-f7fe91de2832.png)
同时修改源码有些部分是直接取的Gobal[$(type)+'Statestyles' ],而如果不扩展Gobal会导致直接报错:如下item.js
Global[self.getType() + GLOBAL_STATE_STYLE_SUFFIX]如果取不到值，不应该继续取state的值，会导致报错。
```
public getStateStyle(state) {
    const self = this;
    // Global.nodeStateStyle
   // 这里Global[self.getType() + GLOBAL_STATE_STYLE_SUFFIX]如果取不到值，不应该继续取state的值，会导致报错。
    const globalStyle = Global[self.getType() + GLOBAL_STATE_STYLE_SUFFIX][state];
    const styles = this.get('styles');
    const defaultStyle = styles && styles[state];
    // 状态名 + style（activeStyle) 存储在 item 中，如果 item 中不存在这些信息，则使用默认的样式
    const fieldName = state + NAME_STYLE;
    return Util.mix({}, globalStyle, defaultStyle, self.get(fieldName));
  }
```

**Comment by baizn** [comment]
接下来G6 会重构 group 的实现，会考虑是否把group当成item来处理，G是6 3.3.0-beta版本已经发布了，有兴趣的话你可以基于TS版本提个pr，将group当成一个item来做。
