### ISSUE TITLE
canvas渲染和svg不兼容

### ISSUE THREAD

**Issue by laidaxian** [antvis/G6#1159]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

我发现反而canvas很多的实现，在svg里面都是有bug的，比如边带有弧度的箭头，我用svg和arc的边shape，渲染出来的边箭头正常，在canvas反而不行。
用canvas和quadratic（原本不支持弧度，我自己做了点拓展），canvas正常，到了svg反而不行。
还有image的clipcfg 在不同渲染引擎下表现形式也不一样。
like this
https://codepen.io/laidaxian/pen/QWwZXQQ

**Comment by baizn** [comment]
建议使用 canvas 渲染，G6 3.3以后暂不支持 SVG 渲染。

**Comment by laidaxian** [comment]
> 建议使用 canvas 渲染，G6 3.3以后暂不支持 SVG 渲染。

您看下这个codeopen的demo，是用canvas模式渲染，但是箭头并不是和预期的一样显示

**Comment by vellengs** [comment]
@baizn 
> G6 3.3以后暂不支持 SVG 渲染。
只是暂时，还是以后都不支持了？

**Comment by baizn** [comment]
暂时的，3.4 版本就会支持 SVG 渲染。

**Comment by Yanyan-Wang** [comment]
v3.4 已发布，尝试一下看？
