### ISSUE TITLE
如何让node支持拖拽改变形状

### ISSUE THREAD

**Issue by wbpmrck** [antvis/g6#116]
RT,比如在这个demo里，只有node1可以拖拽改变形状，其他2个不行。是什么原因？

https://antv.alipay.com/zh-cn/g6/1.x/demo/other/htmlnode.html

**Comment by wbpmrck** [comment]
上面的例子不太好，他是css控制的，看这个图编辑器的demo,为什么里面的形状拖拽之后，大小无法改变
https://antv.alipay.com/zh-cn/g6/1.x/demo/other/editor.html

**Comment by wbpmrck** [comment]
=.=,我自己试验了一下，在draw的时候需要根据cfg.size去重绘是吧（文档里并没有说明cfg的参数是什么时候生成的...)
但是还有个小问题，node的位置(x,y),每次画好之后，都会有一些偏移，请问这是为什么

![step1](https://user-images.githubusercontent.com/1442515/33605705-c4e85cba-d9f5-11e7-8b9b-d23ef3b93828.png)
![step2](https://user-images.githubusercontent.com/1442515/33605709-c921dd9c-d9f5-11e7-9e87-6d7a88c738b5.png)

**Comment by TomHuangCN** [comment]
默认图形都是以 cfg.x cfg.y 为中心节点。所以相应的行为也是以中心变形的。
构造自定义节点时，设置成以 cfg.x、cfg.y 就不会偏移了～

**Comment by wbpmrck** [comment]
我改成cfg.x,cfg.y也还是不行。而且断点调试的时候，拖动变形之后触发的draw里面，cfg.x和cfg.y都是0

```javascript
draw(cfg, group) {
            const shape = group.addShape('rect', {
                attrs: {
                    x: cfg.x,
                    y: cfg.y,
                    width: cfg.size?cfg.size[0]:80, //根据实际拖拽的大小来处理
                    height: cfg.size?cfg.size[1]:80, //根据实际拖拽的大小来处理
                    fill: '#fff',
                    stroke: 'green'
                }
            });
            return shape;
        },
```

![e1](https://user-images.githubusercontent.com/1442515/33642587-8a8a4af8-da75-11e7-980c-1a0e0771f793.png)

**Comment by TomHuangCN** [comment]
rect 绘图属性（attrs）里的x，y是指矩形的左上角。要这么玩才行。

至于为什么是0，0，因为图坐标是赋在group的变换上的。所以对其子元素而言，其中点坐标就是 0，0

```js
const width = cfg.size?cfg.size[0]:80;
const height = cfg.size?cfg.size[1]:80;
            const shape = group.addShape('rect', {
                attrs: {
                    x: cfg.x-width/2,
                    y: cfg.y-height/2,
                    width, //根据实际拖拽的大小来处理
                    heigh, //根据实际拖拽的大小来处理
                    fill: '#fff',
                    stroke: 'green'
                }
            });
```

**Comment by wbpmrck** [comment]
感谢，按照你的代码来写，是ok的。是不是这么理解：

>  rect绘制指定的(x,y)是rect左上角相对于`所在group区域的中心点`的偏移？

- (x,y)=(0,0)就表示矩形的左上角刚好在所在group区域的中心（而不是左上角)
- (x,y)=(0-width/2,0-height/2)就表示矩形的左上角刚好在所在group区域的左上角？

**Comment by TomHuangCN** [comment]
![img_20171207_094121r](https://user-images.githubusercontent.com/6113694/33694438-115e8a90-db33-11e7-8370-0a36a51938b9.jpg)
