### ISSUE TITLE
fillOpacity 与 opacity希望统一。

### ISSUE THREAD

**Issue by Leannechn** [antvis/G6#1161]
fillOpacity 优先级高与opacity，在updateItem时 内置的defaultStyle 会被赋值。这时候修改状态就要同时设置opacity 和 fillOpacity两个。
![image](https://user-images.githubusercontent.com/6812138/72681853-8ffe4300-3b02-11ea-9582-19ad02f91990.png)

**Comment by Yanyan-Wang** [comment]
opacity 是整体的透明度，包括描边和填充。fillOpacity 只是填充的透明度。你说的这个现象可以写一个在线 demo 给我们排查一下吗？

**Comment by Yanyan-Wang** [comment]
新版本中已经去除内置的状态样式设置。
