### ISSUE TITLE
节点分组功能设计

### ISSUE THREAD

**Issue by baizn** [antvis/G6#1163]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

目前版本中的分组功能是针对分析和展示场景下设计的，也支持了创建空组，但不是真正的一个 Item，也不支持自定义分组、分组上的复杂交互等。

我们期望一个完整到的分组功能应该具备以下功能：
![image](https://user-images.githubusercontent.com/9443867/72772488-01dba700-3c3f-11ea-998e-4123b52364e1.png)

大家另外还有什么诉求，欢迎补充一下，感谢！

**Comment by ColinChen2** [comment]
图布局的分组上面确实很丰富了。但是对于树图布局，就不太适用了。
树图布局本身父节点就是一个分组，但是我们有两种情况：
1.  辅助作用：和目前图布局一样，只是显示几个节点有特殊关系，有背景有边界的多边形。不改变任何结构。
2. 调整结构：需要调整树的分支结构

期望的功能有
初始分组：
       提供分组拖动的behavior
创建分组：
       可以选取几个节点，创建新的分组
拖入分组：
       将一个分支或节点可以拖入到另外一个分支或节点

**Comment by baizn** [comment]
@ColinChen2  调整结构：需要调整树的分支结构 这个能详细描述下吗？

**Comment by sansanxwk** [comment]
希望分组的gtoupStyle这一块能尽快完善一下,官网的api中介绍:
groupStyle 用于指定分组在默认（default）、交互过程中（hover）及收起（collapse）状态下的样式。
然而hover属性并未支持.(亦或是使用方式不对?希望详细完善一下api.)

**Comment by ColinChen2** [comment]
@baizn 比如树里，父节点有三个子节点。现在我拖第三个子节点进入第二个子节点。然后就多了一层。第三个子节点就变成了第二个字节点的子节点。像这样：

   0         -》    0
1 2 3            1    2 
                          3
那树形结构接变了。

**Comment by 2012shenghua** [comment]
希望支持自定义样式，和自定义行为，分组收缩后支持节点的组合展示

**Comment by 2012shenghua** [comment]
希望支持自定义样式，和自定义行为，分组收缩后支持节点的组合展示

**Comment by BensonLam** [comment]
节点分组可以自定义样式太少了 很不美观 香菇蓝瘦

**Comment by baizn** [comment]
> 希望支持自定义样式，和自定义行为，分组收缩后支持节点的组合展示

下个版本全都会支持的。

**Comment by caojin24** [comment]
各个分组的样式 自定义功能支持了吗？

**Comment by baizn** [comment]
> 各个分组的样式 自定义功能支持了吗？

3.5 支持

**Comment by miomio-xiao** [comment]
> > 各个分组的样式 自定义功能支持了吗？
> 
> 3.5 支持

3.5大概会在什么时候发布？
