### ISSUE TITLE
工程eslint 的遵守情况比较糟糕。

### ISSUE THREAD

**Issue by vellengs** [antvis/G6#1164]
![image](https://user-images.githubusercontent.com/5743338/72800197-bc8c9900-3c81-11ea-97ae-461009b4ba5d.png)

**Comment by baizn** [comment]
按照 umijs 的eslint 来的。
```
module.exports = {
  extends: [require.resolve('@umijs/fabric/dist/eslint')],
  globals: {
    $: true,
    _: true,
  },
  rules: {
    'no-bitwise': 0,
  },
};
```

**Comment by vellengs** [comment]
但是 vscode 仍然报错了呢？

**Comment by vellengs** [comment]
![image](https://user-images.githubusercontent.com/5743338/72801282-273ed400-3c84-11ea-9bdc-14e58dfb1af4.png)
我不得不补上这些。

**Comment by vellengs** [comment]
另外增加的这些项在 ‘@umijs/fabric/dist/eslint’ 未找到忽略项，难道我哪里没设置好？

**Comment by vellengs** [comment]
![image](https://user-images.githubusercontent.com/5743338/72801650-eb583e80-3c84-11ea-83c7-2183e747f7a7.png)
另外这种代码真的比较糟糕，是确实需要调整的。

**Comment by baizn** [comment]
> ![image](https://user-images.githubusercontent.com/5743338/72801282-273ed400-3c84-11ea-9bdc-14e58dfb1af4.png)
> 我不得不补上这些。

可能与VSCode配置有关吧，本地是好的。

**Comment by baizn** [comment]
> ![image](https://user-images.githubusercontent.com/5743338/72801650-eb583e80-3c84-11ea-83c7-2183e747f7a7.png)
> 另外这种代码真的比较糟糕，是确实需要调整的。

欢迎提 PR。
