### ISSUE TITLE
setItemActived 方法设置了item高亮，但是鼠标挪到节点上才生效

### ISSUE THREAD

**Issue by 185942983** [antvis/g6#117]
tree.setItemActived(item, true)   
 当鼠标挪到根节点 或者 设置active的节点上 （必须是包含子节点的节点） 才生效

**Comment by TomHuangCN** [comment]
1. 写个 code pen 复现一下
2. 设置高了不需要setItemActived，使用事件，tree.update(ev.item, model) 一下就好了

**Comment by 185942983** [comment]
怎么给item对象 修改shape属性呢

**Comment by TomHuangCN** [comment]
shape.attr('xx', xx)
