### ISSUE TITLE
[3.3.0-beta.2] Edge类型与实际情况不符

### ISSUE THREAD

**Issue by ObservedObserver** [antvis/G6#1170]
* **G6 Version**: 3.3.0-beta.2
* **Platform**: MacOS Chrome
* **Mini Showcase(like screenshots)**:
```js
graph.current.edge(function (edge) {
        return {
          ...edge,
          size: 2 + edge.targetNode.get('model')['value'] * 8 // edge.targetNode is undefined at runtime
        }
      });
```
这段代码运行时会报错，这是由于edge.targetNode是undefined导致的。

TS给出的提示中，当前版本的edge.target是string类型，而edge.targetNode是Node类型。但实际运行时，edge.target是包含节点详细信息的对象，而targetNode不存在。

**Comment by baizn** [comment]
在 edge 方法中，参数表示的是数据中的edge，此时还没有 targetNode，target是一个字符串，表示节点的ID。

**Comment by ObservedObserver** [comment]
![image](https://user-images.githubusercontent.com/22167673/78340141-243b5a80-75c8-11ea-967c-723fa809eb65.png)
打印显示target不是string类，是targetNode。
