### ISSUE TITLE
用怎样的方法获取到已经添加的text的值，并且怎样修改在节点上的Text的文本内容，谢谢

### ISSUE THREAD

**Issue by Johnnylee1992** [antvis/g6#118]
![_20171207161321](https://user-images.githubusercontent.com/34331221/33705084-e6d5185c-db69-11e7-8f5c-668750de47b4.png)
在绘制椭圆度的时候添加了个Text文本，后期怎样才能修改原来的text内容；
![_20171207160712](https://user-images.githubusercontent.com/34331221/33705079-e2478874-db69-11e7-977a-ee3fa18baa9d.png)

**Comment by TomHuangCN** [comment]
比较标准的做法是画文本和图形的时候，用 cfg.model 里的数据。然后事件里调用 net.update(ev.item, model)

**Comment by Johnnylee1992** [comment]
在click事件里面调用的net.updatwe(ev.item, model)方法，是将cfg.model的数据更新，这样会导致一问题，我在修改其他节点的文本内容时，之前修改的节点内容也会同步改变，请问可以采取哪种发法可以避免。

**Comment by TomHuangCN** [comment]
update 之前 ev.item.getModel()  拿出之前的数据，merge 一下

**Comment by TomHuangCN** [comment]
没很明白为什么其它节点内容会变？ 写个codepen？

**Comment by Johnnylee1992** [comment]
![default](https://user-images.githubusercontent.com/34331221/33812719-5671412a-de5a-11e7-8b9c-00e84e56ecb1.PNG)
![default](https://user-images.githubusercontent.com/34331221/33812720-5c0aba76-de5a-11e7-9498-6b43c8e7c4bf.PNG)
![daima](https://user-images.githubusercontent.com/34331221/33812896-7eeefe8e-de5b-11e7-8467-e4def4998ac6.PNG)
第二张图修改椭圆的text内容名字，之前修改的两个rect的text 内容 在调用update()的时候全部都变成最后一次修改的名字

**Comment by Johnnylee1992** [comment]
https://codepen.io/xiaopang-1992/pen/NXKNaN
点击添加节点，左击弹出菜单框，在扩展名输入修改文本，点击菜单里的保存按钮；
实际上是点击保存的时候 update()方法重新渲染了所有的修改过的节点，这里怎么实现只更新当前的节点

**Comment by TomHuangCN** [comment]
1. 不要用私有属性及方法，这些接口不做保证
2. https://codepen.io/DoriTong/pen/YYKWKz?editors=1010

```js
        saveMenu.on('click', () => {//点击保存按钮，修改text內容
            const value = extensionName.val(); //获取到菜单中扩展名的value
            net.update(ev.item, {
              value,
            });
            menu.hide();
        });
```

**Comment by Johnnylee1992** [comment]
1.官方文档提供的接口，我没找到，￣□￣｜｜
2.用您下面提供的方法，问题依然存在，无法修改内容

**Comment by Johnnylee1992** [comment]
已经解决了，找到了个方法，将ev.item 替换成 net.getActived() (获取到当前活动的节点)就OK了，
`saveMenu.on('click', () => {//点击保存按钮，修改text內容
            const value = extensionName.val(); //获取到菜单中扩展名的value
            net.update(net.getActived(), {
                id: value
            });
            menu.hide();
        });`
