### ISSUE TITLE
点击缩进树形图非叶子节点时，图形渲染异常

### ISSUE THREAD

**Issue by DaleYuan** [antvis/G6#1182]
* **G6 Version**:3.2.0
* **Platform**:Chrome
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/8158629/73913182-53e42400-48f1-11ea-82ad-07977b69d4bc.png)

* **CodePen Link**:https://riddle.alibaba-inc.com/riddles/68e2186d

如图所示，点击非叶子节点的时候，渲染出的图形存在异常；在点击叶子节点时则没有这样的情况。
详细情况已经跟 十吾 沟通过了，已经确认是 bug，麻烦尽快处理一下，非常感谢！

**Comment by baizn** [comment]
这样就可以了，参考这里 https://riddle.alibaba-inc.com/riddles/3427e34f

**Comment by DaleYuan** [comment]
Thanks~
