### ISSUE TITLE
请问是否可以添加双击事件？

### ISSUE THREAD

**Issue by sunscheung** [antvis/g6#119]
目前貌似只有单击事件：itemclick，这样会使得用户想要拖拽节点或者边 与 单击获取节点或边获取信息冲突 。如果支持双击事件itemdbClick，可以有效避免。
例如：
 
![image](https://user-images.githubusercontent.com/9931345/33747216-b1dd3e48-dbfc-11e7-84ca-a5bf1870fa10.png)
![image](https://user-images.githubusercontent.com/9931345/33747218-b4938570-dbfc-11e7-8dec-7f58d9684e94.png)

@TomHuangCN

**Comment by TomHuangCN** [comment]
有基础的双击事件。至于击中了什么在事件对象ev里判断一下

graph.on('dblclick', function(ev){});        // 鼠标左键双击事件

**Comment by sunscheung** [comment]
谢谢!是支持的。
