### ISSUE TITLE
升级 3.3 之后，之前的程序崩溃了

### ISSUE THREAD

**Issue by wangmingquan** [antvis/G6#1203]
贵司发布3.3版本后，程序崩溃

* **G6 Version**:3.3
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/7565294/74218293-c0419780-4ce4-11ea-833a-e2f3f18c47a5.png)

![image](https://user-images.githubusercontent.com/7565294/74217543-b6b73000-4ce2-11ea-9fd9-24d5fb71b486.png)

之前采用的 ^3.1 的方式，暂时锁在 ~3.2 得以解决

**Comment by Yanyan-Wang** [comment]
请问是否有涉及到升级指南中的代码。如果没有，是否能够定位到问题？

我们的兼容性计划：https://github.com/antvis/G6/issues/1206

**Comment by wangmingquan** [comment]
未涉及到指南中的代码，今天也看完了升级指南，依然没解决问题。
另外，我用的是自定义节点：


```javascript
G6.registerNode('html', {
      draw (cfg, group) {
        const htmlShape = group.addShape('dom', {
          attrs: {
            x: 0,
            y: 0,
            width: cfg.width,
            height: cfg.height,
            html: cfg.html
          }
        });
        return htmlShape;
      }
    });
```

不知道是否跟这个有关系？

**Comment by Yanyan-Wang** [comment]
3.3 暂时不支持 SVG 了，如果需要使用，只能先锁定在 3.2.x 版本上。这个我们马上会补充到升级指南中。后续我们也会考虑支持 SVG 的。给您带来不便敬请谅解。

**Comment by Yanyan-Wang** [comment]
3.4 已发布，支持 SVG
