### ISSUE TITLE
G6 3.3.0 兼容问题

### ISSUE THREAD

**Issue by baizn** [antvis/G6#1206]
致 G6 尊敬的用户：

G6 3.3.0 正式版今天已经发布，对于没有锁版本（最真诚）的 G6 用户来说，升级到最新版后会直接报错，导致之前运行良好的程序直接奔溃，对此我们表示歉意。

我们准备了一份[升级指南](https://g6.antv.vision/zh/docs/manual/FAQ/upgradeGuide)，指导各位升级，参考升级指南文档，您可以在最短的时间内完成升级。

> 注意：G6 3.3.0 不支持 SVG 渲染。

为了提升升级效率，我们已经发布 G6 3.3.1，解决以下问题：
**G6 层兼容**
1. ✅TreeGraph 改名的函数全部兼容 => 已兼容
• ✅changeLayout 修改为 updateLayout；
• ✅refreshLayout 修改为 layout。
2. ✅自定义节点和边 registerNode 和 registerEdge 不继承任何值时必须重写 draw => 已兼容
3.  ✅继续兼容 findByClassName => 已兼容

**G 层相关**
1. 每个 shape 要有 name，draggable => 需要用户指定
2. ✅animate 的 onFrame 用法 => 已兼容
3. ✅setZIndex 不存在了 => 已兼容
4. ✅element 上支持矩阵变化函数 => 已兼容
• 平移函数 translate
• 移动函数 move
• 缩放函数 scale
• 旋转函数 rotate
• 以 (0, 0) 点为中心的旋转函数 rotateAtStart

大家可能会有这样的疑问，既然有 breaking change，为什么不发布为 G6 4.0？我们是基于以下几点考虑的：
1. 本次改动绝大部分都是纯工程和代码层面的，对用户来说，没有功能上增强；
2. 考虑到 G6 从 1.0 升级到 2.0，2.0 升级到 3.0 都是不兼容升级，如果我们贸然地在功能没有特别增强、架构没有调整的的基础上升级 4.0 会给用户操作困扰，担心 G6 4.0 会不会又是完全不兼容之前的版本；
3. 本次发布只有很少地几处不兼容，参考升级指南，可以很快地升级过来；
4. 我们计划是将交互语法迁移过来以后再升级为 G6 4.0 ，此时交互方面将完全不同于现在的 Behavior；
5. 最后我们也不愿意快速地升级大版本号，更希望是和用户一起成长，一步一个脚印，脚踏实地地将 G6 的打磨好。

G6 升级指南：https://g6.antv.vision/zh/docs/manual/FAQ/upgradeGuide
G6 3.3.0 性能实验：https://www.yuque.com/antv/blog/wqas6s
G6 3.3.0 发布稿：https://www.yuque.com/antv/g6/chgp2b

您在升级过程中遇到任何问题，请通过 issue 或 交流群里面沟通，我们将第一时间协助您解决。

**Comment by denglouhen** [comment]
那请问官网的API教程稳定是否对差异有进行同步更新？

**Comment by Yanyan-Wang** [comment]
> 那请问官网的API教程文档是否对差异有进行同步更新？

现在官网（https://g6.antv.vision）上是 3.3 的内容，3.2.x 的内容可以在右上角切换。
![image](https://user-images.githubusercontent.com/29593318/74306909-d9a71a00-4d9e-11ea-9456-d9c5ac4773db.png)

另外，官网也提供了升级指南（http://localhost:8000/zh/docs/manual/FAQ/upgradeGuide）

**Comment by Yanyan-Wang** [comment]
G6 3.3.1 已发布，解决了大部分兼容问题，checklist 请看楼主

**Comment by syrahcava** [comment]
在3.3.5版本上折腾了两天自定义节点的事件上，看到这篇文章的标注点，必须指定name和draggable，真是热泪盈眶啊，今天下午已经着手考虑要从G重写目前需求的编辑器了。。。

**Comment by littlesky007** [comment]
> 重写

想问下，新版本中使用鼠标画两个Node的连线如何实现，1.x使用beginAdd，新版本如何使用

**Comment by Yanyan-Wang** [comment]
> 在3.3.5版本上折腾了两天自定义节点的事件上，看到这篇文章的标注点，必须指定name和draggable，真是热泪盈眶啊，今天下午已经着手考虑要从G重写目前需求的编辑器了。。。

嗯嗯，这是底层 G 升级原因，现在 G 的图形需要指定 draggable 才可以允许在有拖动的监听。
