### ISSUE TITLE
focusPoint的使用方法？

### ISSUE THREAD

**Issue by liuqiao1** [antvis/g6#121]
`/**
 * 聚焦某点
 * @param  {Object} point 点
 */
graph.focusPoint(point);`

我是这样用的：tree.focusPoint(tree.find(‘b64823’));
b64823是一个node的Id。我的目的是以这个node为中心。
但是效果并不是如此，整张图缩到了页面左上角，同时minimap也无法使用了。
不知道为何现在上传不了图片？
我猜是我的使用方法不对？

**Comment by TomHuangCN** [comment]
1. focusPoint 目前只接收图坐标 {x,y}
2. minmap 应该是报错了吧
3. 上传图片？

**Comment by liuqiao1** [comment]
focusPoint({x: xValue, y: yValue})
这样用就没有问题了。
建议改进一下API文档哦~
