### ISSUE TITLE
单元测试跑不通

### ISSUE THREAD

**Issue by vellengs** [antvis/G6#1214]
![image](https://user-images.githubusercontent.com/5743338/74395854-568fcd80-4e4b-11ea-9293-d0cde4d80b26.png)

我看目前CI 由于 electron 的原因无法加入测试流程，但是不跑完测试提交代码是不是也不妥？

**Comment by Yanyan-Wang** [comment]
肯定是可以跑通的呀，怀疑是你本地没有重新安装依赖，或者有旧的依赖遗留。建议先跑一下 npm update
