### ISSUE TITLE
流程图间的箭头位置乱了，没改代码，怀疑是版本升级问题

### ISSUE THREAD

**Issue by llfylwg** [antvis/G6#1215]
* **G6 Version**:3.2.9
* **Platform**:mac
* **Mini Showcase(like screenshots)**: 如标题描述
* **CodePen Link**:

**Comment by llfylwg** [comment]
建议升级能够最大性兼容之前的版本，无法做兼容的也应该在升级日志中有说明

**Comment by Yanyan-Wang** [comment]
麻烦提供一下升级前后的图的截图。现在正在修复兼容问题

**Comment by baizn** [comment]
> 建议升级能够最大性兼容之前的版本，无法做兼容的也应该在升级日志中有说明

参考这里，https://g6.antv.vision/zh/docs/manual/FAQ/upgradeGuide  如果有没覆盖到的，麻烦反馈给我们，多谢！

**Comment by jeezlee** [comment]
![image](https://user-images.githubusercontent.com/7425684/74517883-ecac1c80-4f4d-11ea-8deb-8dd7057e274c.png)  边设置箭头之后拖动会出现这种现象

**Comment by Yanyan-Wang** [comment]
> ![image](https://user-images.githubusercontent.com/7425684/74517883-ecac1c80-4f4d-11ea-8deb-8dd7057e274c.png) 边设置箭头之后拖动会出现这种现象

这是底层渲染引擎局部渲染的 bug，正在修复中。可以先这样关闭局部渲染：
graph.get('canvas').set('localRefresh', false);

对于这样的小规模图，关闭局部渲染不会产生影响。

感谢反馈。

**Comment by Yanyan-Wang** [comment]
v3.3.7 已修复该问题。
