### ISSUE TITLE
3.3.0 拖拽/缩放 报错

### ISSUE THREAD

**Issue by FreeRide-Joe** [antvis/G6#1216]
复现步骤：
1. 边箭头 使用自定义箭头
2. 边文本 开启 autoRotate
3. 拖拽/缩放，控制台就会报错

报错信息：
![image](https://user-images.githubusercontent.com/16112889/74398134-96f24a00-4e51-11ea-9922-f4e79a6866c6.png)

复现地址：https://codepen.io/Joe_/full/ZEGbwoz

**Comment by Yanyan-Wang** [comment]
感谢，正在修复中

**Comment by Yanyan-Wang** [comment]
v3.3.2 已修复。感谢反馈。
