### ISSUE TITLE
group群组节点在fitView模式下拖拽位置和鼠标位置不一致

### ISSUE THREAD

**Issue by sansanxwk** [antvis/G6#1218]
* **G6 Version**: 3.3
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

group分组节点在fitView模式下拖拽位置和鼠标位置不一致.
补充:不仅是fitView模式下,缩放画布后也会不一致.

**Comment by LongCatIsaac** [comment]
解决了吗，能分享下解决解法吗

**Comment by Yanyan-Wang** [comment]
目前节点分组的机制是一个临时的方案，存在很多问题。节点分组的问题都会在下个月的新版本中解决，我们正在重新设计和实现节点分组的新机制。

**Comment by Yanyan-Wang** [comment]
带有全新节点分组 Combo 机制的 v3.5 发布了。demos：
内置 combos: https://g6.antv.vision/zh/examples/item/defaultCombos
自定义 combos: https://g6.antv.vision/zh/examples/item/customCombo
Combo 的布局: https://g6.antv.vision/zh/examples/net/comboForce
Combo 的交互: https://g6.antv.vision/zh/examples/interaction/combo

文档可以通过 [G6 官网](https://g6.antv.vision/zh) 上方的搜索栏搜索“combo”查看。

**Comment by lichengzhong** [comment]
我也遇到了这个问题  ，怎么解决呢？  v 863849467
