### ISSUE TITLE
网图图类是否支持动画效果？

### ISSUE THREAD

**Issue by Jarryham** [antvis/g6#122]
网图图类是否支持像canvas那样的动画设置实现动画效果，例如可设置每个节点的循环动画。

**Comment by TomHuangCN** [comment]
1. 图形库有动画接口 https://antv.alipay.com/zh-cn/g6/1.x/api/canvas.html#_%E5%8A%A8%E7%94%BB-animate 
2. 用html节点可用css 动画 https://antv.alipay.com/zh-cn/g6/1.x/demo/other/htmlnode.html

**Comment by Jarryham** [comment]
1、图形库的动画接口只适用于canvas上的节点对象，net上的节点对象并不支持吧；
2、只能以html节点的方式添加动画了；

**Comment by TomHuangCN** [comment]
1. https://antv.alipay.com/zh-cn/g6/1.x/tutorial/custom-shape.html 配合自定义图形，能用canvas动画
