### ISSUE TITLE
官网的圆点延边运动示例运行结果与图不符

### ISSUE THREAD

**Issue by denglouhen** [antvis/G6#1227]
这是官网的codesandbox直接点开的链接，https://codesandbox.io/s/0y7ud
运行结果是圆点只跑了1次并且线坑坑洼洼的。

**Comment by Yanyan-Wang** [comment]
官网的国内镜像更新有延迟，网络允许的话优先还是看非国内镜像：

https://g6.antv.vision/zh/examples/scatter/edge 

上面点开的 codesandbox：https://codesandbox.io/s/npnje
