### ISSUE TITLE
点击tree-node时，如何区分点中的是node主体部分还是 treeButton?

### ISSUE THREAD

**Issue by liuqiao1** [antvis/g6#123]
如图：
![image](https://user-images.githubusercontent.com/16732082/33873350-9af28d44-df55-11e7-8c29-2703f8ac0d3b.png)

因为偶然发现点中treebutton时，destroyed值为true, 所以我现在是这样写的：
` tree.on('click', ev => { 
           if(ev.itemType == 'edge')return;//点中边
           if(ev.item.destroyed)return;//点中小圆圈
}
          `
这样写，效果上没问题，但是控制台会报错：
![image](https://user-images.githubusercontent.com/16732082/33873482-1aa46044-df56-11e7-8e4e-0c1377c4736c.png)

不知道有没有更好的办法？

**Comment by TomHuangCN** [comment]
```js
tree.on('click', ev=>{
console.log(ev.shape.get('class'))
});
```
用 class 判断一下
