### ISSUE TITLE
G6 3.3.x 升级后无法生成网格线（Grid插件问题）

### ISSUE THREAD

**Issue by winyuan** [antvis/G6#1230]
- **G6 Version**: 
  - 3.3.0
  - 3.3.1
  - 3.3.2
- **Platform**:
  - Chrome
- **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/26686411/74632029-67b54300-5199-11ea-9c83-ef72eaab4b0b.png)

如标题所述：使用 3.3.x 的方式调用 G6 内嵌的 Plugins  - Grid 未生成（无报错）。

场景复现：
借助官网的[图表演示](https://g6.antv.vision/zh/examples/shape/defaultEdges)
将右侧的代码块删除，粘贴下方代码进行复现：
```javascript
import G6 from '@antv/g6';

const data = {
  nodes: [{
    id: '0',
    x: 150,
    y: 100
  }, {
    id: '1',
    x: 350,
    y: 300
  }],
  edges: [
    {
      source: '0',
      target: '1'
    }]
};

const grid = new G6.Grid()
const width = document.getElementById('container').scrollWidth;
const height = document.getElementById('container').scrollHeight || 500;
const graph = new G6.Graph({
  container: 'container',
  width,
  height,
  plugins: [ grid ]
});

// graph.addPlugin(grid) 用这种方法也无法生成网格

graph.data(data);
graph.render();
```

**Comment by Yanyan-Wang** [comment]
插件引入方式在 3.3.x 中不同了，详见：https://g6.antv.vision/zh/docs/manual/FAQ/upgradeGuide#%E6%8F%92%E4%BB%B6-plugins

这是由于 3.3.x TS 重构中我们改变了打包方式，给您带来不便敬请谅解。

**Comment by winyuan** [comment]
> 插件引入方式在 3.3.x 中不同了，详见：https://g6.antv.vision/zh/docs/manual/FAQ/upgradeGuide#%E6%8F%92%E4%BB%B6-plugins
> 
> 这是由于 3.3.x TS 重构中我们改变了打包方式，给您带来不便敬请谅解。

您好，我确实是通过 3.3.x 的方式引入的：
Step1：
```javascript
import G6 from '@antv/g6';
```
Step2：
```javascript
const grid = new G6.Grid()
``` 
Step3：
```javascript
const graph = new G6.Graph({
  container: 'container',
  width,
  height,
  plugins: [ grid ]
});
```
不过还是没有生成网格线，不知是不是我的使用方式错了（完整代码负载该 issue 第一条评论）？
官方文档 3.3.1 版本：
![image](https://user-images.githubusercontent.com/26686411/74700170-bcaa9500-523d-11ea-9358-6ac5b15132ae.png)
![image](https://user-images.githubusercontent.com/26686411/74700186-c3d1a300-523d-11ea-91ad-843dc5f3d23a.png)

感谢！

**Comment by Yanyan-Wang** [comment]
官网现在是 3.3.1，插件有问题。

3.3.2 和后续版本修复了：https://codesandbox.io/s/grid-b00g8

官网今天会更新

**Comment by winyuan** [comment]
> 官网的容器有问题，grid 被遮盖了。
> 
> 在其他环境下应该是没问题的：https://codesandbox.io/s/grid-b00g8

已验证，确实是因为 g6-grid 容器层级引起的。

感谢！

**Comment by LiuYnag** [comment]
> > 官网的容器有问题，grid 被遮盖了。
> > 在其他环境下应该是没问题的：https://codesandbox.io/s/grid-b00g8
> 
> 已验证，确实是因为 g6-grid 容器层级引起的。
> 
> 感谢！

麻烦问一下，这个网格被遮盖的问题现在怎么解决的啊，要自己写样式去修改那个z-index为-1的值么？我这边现在也遇到同样的问题了。

**Comment by saint3347** [comment]
![image](https://user-images.githubusercontent.com/7347133/102038818-36ca8c80-3e03-11eb-91b0-08d0b05d0925.png)
遇到同样的问题……

**Comment by Yanyan-Wang** [comment]
对，需要修改 z-index

**Comment by CHENJIAMIAN** [comment]
`css
>>> .g6-grid-container {
  z-index: 0 !important;
}

>>> #容器 canvas {
  z-index: 1;
  position: relative;
}
`
