### ISSUE TITLE
can not listent "canvas:dragend",when i release mouse on other element(like node) 

### ISSUE THREAD

**Issue by laidaxian** [antvis/G6#1231]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

当我拖拽canvas画布的时候，鼠标快速移动，如果在其它元素（比如说节点）上面释放鼠标，canvas:dragend事件不会被触发，所以canvas:mousemove事件没有被关闭。效果就是已经抬起鼠标后，整个canvas画布一直跟着移动。
我试着监听原生的canvas dom事件，发现mouseup事件会被触发，所以估计是G库内部的事件处理导致了这个bug

**Comment by laidaxian** [comment]
> * **G6 Version**:3.2.6
> * **Platform**:macos
> * **Mini Showcase(like screenshots)**:截图也无法体现效果
> * **CodePen Link**:任意图例都能重现
> 
> （同时开启drag-canvas,drag-node behavior）当我拖拽canvas画布的时候，鼠标快速移动，如果在其它元素（比如说节点）上面释放鼠标，canvas:dragend事件不会被触发，所以canvas:mousemove事件没有被关闭。效果就是已经抬起鼠标后，整个canvas画布一直跟着移动。
> 我试着监听原生的canvas dom事件，发现mouseup事件会被触发，所以估计是G库内部的事件处理导致了这个bug

**Comment by Yanyan-Wang** [comment]
这个问题在 3.3.x 中已经修复。

**Comment by laidaxian** [comment]
> 这个问题在3.3.x中已经修复。

我在3.3.0版本测试后，仍然有这个问题呢

**Comment by vellengs** [comment]
我在
https://graphin.antv.vision/zh/GraphinStudio
示例中也能重现这个问题。
