### ISSUE TITLE
渲染重绘Bug.

### ISSUE THREAD

**Issue by vellengs** [antvis/G6#1234]
重现地址:
https://g6.antv.vision/zh/examples/net/layoutMechanism#dataChange

![0001](https://user-images.githubusercontent.com/5743338/74819952-24dfa080-533c-11ea-98bb-923d29de0c8b.jpg)

**Comment by vellengs** [comment]
拖拽一个点，让自动弹回，就出这样的问题了。

**Comment by Yanyan-Wang** [comment]
局部渲染机制造成的问题。不过 G6 内部在 changeData 的时候应该清空一下画布，这样可以避免这个问题。下个版本修复。

感谢反馈。

**Comment by ILuZhangKun** [comment]
> 局部渲染机制造成的问题。不过 G6 内部在 changeData 的时候应该清空一下画布，这样可以避免这个问题。下个版本修复。
> 
> 感谢反馈。

hello，修复似乎没有起作用
