### ISSUE TITLE
changeData后使用focusItem报错

### ISSUE THREAD

**Issue by xhay1122** [antvis/G6#1235]
任意demo在changeData后在执行focusItem 都会抛出异常。
graph.changeData({
    id:'jjjjx',
    children:[]
  })
 graph.focusItem('jjjjx')

**Comment by Yanyan-Wang** [comment]
是否是 3.3.0 - 3.3.4 版本？是否报这样的错：
Uncaught TypeError: Cannot read property '0' of null

如果是的话，3.3.5 已修复。感谢反馈。
