### ISSUE TITLE
使用 changeData 渲染不出分组

### ISSUE THREAD

**Issue by baizn** [antvis/G6#1236]
- **G6 Version**: 3.3.5
- **Platform**: MAC
- **Mini Showcase(like screenshots)**:
- **CodePen Link**: https://g6.antv.vision/zh/examples/interaction/nodeGroup

使用如下方式可以正常渲染分组：
```
graph.data(data)
graph.render()
```

但当使用 graph.changeData(data) 时就不能正常渲染出分组。

**Comment by Heheroes** [comment]
如何是想新增分组使用renderCustomGroup({})
