### ISSUE TITLE
在react项目中使用@antv/g6，在执行build命令打包时报错

### ISSUE THREAD

**Issue by limmy-zh** [antvis/G6#1237]
- **G6 Version**:   3.2.8
- **Platform**: 在react项目中使用@antv/g6，在执行build命令打包时报如下错误：

Failed to minify the code from this file:
     ./node_modules/@antv/g6/build/g6.js:9:97840

- **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/28913969/74918179-ac441700-5403-11ea-8c53-0d59f74bb387.png)

- **CodePen Link**:

**Comment by flyaaaaaaaa** [comment]
这个要改成全局引用，我也出现这个问题了，但不知道要怎么改，我的在dva下的项目

**Comment by Yanyan-Wang** [comment]
请问用了哪个版本的 G6

**Comment by limmy-zh** [comment]
> 请问用了哪个版本的 G6

目前用的3.2.8，但我试了其他版本从3.1.0开始往上的版本都报一样的错

**Comment by baizn** [comment]
这个是压缩代码的时候报的错，是 webpack 压缩代码的插件的不兼容某些写法，换一个压缩插件就可以了。
