### ISSUE TITLE
npm run build报错

### ISSUE THREAD

**Issue by flyaaaaaaaa** [antvis/G6#1238]
配置文件改成这样后
![image](https://user-images.githubusercontent.com/39297257/74920720-95072880-5407-11ea-841d-36a6e4caba47.png)
引用后提示找不到包，怎么引用

**Comment by Yanyan-Wang** [comment]
请问用了哪个版本的 G6

**Comment by flyaaaaaaaa** [comment]
已经通过之前你给的方法解决了，在webpack中配置extraBabelIclnclude,用的版本是最新版本的
