### ISSUE TITLE
Uncaught TypeError: n.addEdge is not a function

### ISSUE THREAD

**Issue by mkarimv** [antvis/G6#1239]
I have an issue when load data before render()
In the object graph the data is loading and at n node it stops and i have this error 
Uncaught TypeError: n.addEdge is not a function

**Comment by Yanyan-Wang** [comment]
Which version are you using?

Are there Number type of nodes' 'id's in your data? In G6, String type is required for 'id's. So as to 'source's and 'target's for edges.

**Comment by chinloyal** [comment]
@Yanyan-Wang I am having the same issue as well, I changed all the id's to string but I am still getting the same error.

Using version 3.3.6

**Comment by mkarimv** [comment]
The ID must be unique than source and target.

**Comment by chinloyal** [comment]
I fixed the issue by removing the id field I had one the edges. @mkarimv @Yanyan-Wang

**Comment by Yanyan-Wang** [comment]
Is the id you removed not unique?

**Comment by chinloyal** [comment]
@Yanyan-Wang Yes it was, I actually added it back but instead of just returning the integer as a string I appended 'e_' on it for edge, I also do the same for nodes ('n_') and groups ('g_').

**Comment by Yanyan-Wang** [comment]
Could you pls provide an online demo? With codepen like this: https://codepen.io/Yanyan-Wang/pen/mdbYZvZ , or any other platform you like.

**Comment by FFengIll** [comment]
I also meet this problem.
In my case, the id is not string (but a object like special-int),
then the edge cause error.
> if no edge, then no error; any one edge will case error again.

**Comment by Yanyan-Wang** [comment]
The id of a node and an edge MUST be UNIQUE STRINGs.

**Comment by emmaqiu** [comment]
> The id of a node and an edge MUST be UNIQUE STRINGs.

Is it possible to add number type to id？
