### ISSUE TITLE
怎样在cfg.model 添加到节点的新的属性

### ISSUE THREAD

**Issue by Johnnylee1992** [antvis/g6#124]
节点名称使用text:cfg.model; 而model里面只有shape，id 和坐标，怎么样在model里面添加新的属性，在改变text的内容时不影响model里面的数据保存关系

**Comment by TomHuangCN** [comment]
model 就是你传入的的数据，改不了。

你save的时候复制一个data吧，把你要的东西的拷贝一份就好了

**Comment by Johnnylee1992** [comment]
每一个节点都有自己不同的属性，需在保存的时候将这个些属性一并保存下来，需要在另一个页面渲染；
我怎么可以将弹出框的属性，在save的时候一并保存，现在data里面的节点信息只有 shape x y id;
![default](https://user-images.githubusercontent.com/34331221/34030705-11635d1e-e1a9-11e7-9e15-e3b10334bf07.png)
![data](https://user-images.githubusercontent.com/34331221/34030716-1a9f0040-e1a9-11e7-8a99-a2ec3693639e.png)

**Comment by TomHuangCN** [comment]
save 只会save model 里的数据。你要把画图所用的属性（弹出框里的属性）全部跟model绑定。才能save出一副一摸一样的图，去另一个画布画

**Comment by Johnnylee1992** [comment]
非常感谢，已经将属性绑定给节点
