### ISSUE TITLE
@antv/g6 @ 2.1.0版本 火狐浏览器下滚动鼠标滚轮，有向图无法缩放，其它浏览器正常，升级最新版3.x成本太高，2.x哪个版本修改了该兼容性问题呢

### ISSUE THREAD

**Issue by 1039958384** [antvis/G6#1240]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by baizn** [comment]
升级到 2.x 的最新版本看下，如果没修复的话你参考缩放的 Behavior 重新改下，应该是Firefox不兼容某个属性导致的。
