### ISSUE TITLE
力导向图多个节点群，拖拽某两个以上节点到一块之后，其他节点会仿真的距离远的离谱，有没有方法，可以避免这一现象。

### ISSUE THREAD

**Issue by 1107407264** [antvis/G6#1242]
![TIM截图20200221165404](https://user-images.githubusercontent.com/61303341/75018926-ef1cf200-54ca-11ea-898c-304457415cf9.png)

![aaa](https://user-images.githubusercontent.com/61303341/75018988-0f4cb100-54cb-11ea-92d2-0b834437ded9.png)

**Comment by Yanyan-Wang** [comment]
因为 force 依赖 d3-force，只能通过调参看是否能减缓这个问题。可以尝试新版本的 force2 不存在这个问题。3.x -> 4.x 升级指南：
http://g6.antv.antgroup.com/manual/faq/upgradeguide
https://github.com/antvis/G6/issues/2525
