### ISSUE TITLE
官方示例文字过长...功能实现的问题

### ISSUE THREAD

**Issue by jiangyangchang** [antvis/G6#1245]
function strLen(str) {
  let len = 0;
  for (let i = 0; i < str.length; i++) {
    if (str.charCodeAt(i) > 0 && str.charCodeAt(i) < 128) {
      len++;
    } else {
      len += 2;
    }
  }
  return len;
}

function fittingString(str, maxWidth, fontSize) {
  const fontWidth = fontSize * 1.3; // 字号+边距
  maxWidth = maxWidth * 2; // 需要根据自己项目调整
  const width = strLen(str) * fontWidth;
  const ellipsis = '…';
  if (width > maxWidth) {
    const actualLen = Math.floor((maxWidth - 10) / fontWidth);
    const result = str.substring(0, actualLen) + ellipsis;
    return result;
  }
  return str;
}

fittingString方法中const result = str.substring(0, actualLen) + ellipsis;  中文为2个长度，这里均考虑为1个长度，导致宽度限制不准确。

**Comment by Yanyan-Wang** [comment]
该方法已经在 v3.3.x 中废弃。可以自己实现一下。
