### ISSUE TITLE
3.3.x 版本  drag-node   behavior 无效，

### ISSUE THREAD

**Issue by huxiaoyun** [antvis/G6#1247]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:
https://codesandbox.io/s/laughing-engelbart-w7mlo?fontsize=14&hidenavigation=1&theme=dark

降级到 3.2.10 版本 drag-node 交互恢复正常

**Comment by Yanyan-Wang** [comment]
自定义节点要在 addShape 的时候为图形加上 name 和 draggable:true，详见升级指南：https://g6.antv.vision/zh/docs/manual/FAQ/upgradeGuide

**Comment by zwfun** [comment]
升到3.4.0都没修复
