### ISSUE TITLE
在缩放和拖动中会出现轨迹的线条

### ISSUE THREAD

**Issue by bieao-coding** [antvis/G6#1248]
可以尝试下面代码解决：
graph.get('canvas').set('localRefresh',false);  关掉局部渲染

**Comment by EmiyaYang** [comment]
是指这个吗? 官网demo都出现了
![image](https://user-images.githubusercontent.com/22047765/75604837-f02bd000-5b17-11ea-882f-83fd0992ce0c.png)

**Comment by Yanyan-Wang** [comment]
这个问题正在修复中，遇到这个问题的同学可以先这样 graph.get('canvas').set('localRefresh',false); 关掉局部渲染

**Comment by Yanyan-Wang** [comment]
v3.3.7 已修复残影问题。

**Comment by mhfe123** [comment]
4.0.4版本还是遇到了这个问题，不加那一行代码就会出残影，不知道是不是我写的代码有问题呀，问题复现：https://stackblitz.com/edit/react-ysh6tp?file=index.js
