### ISSUE TITLE
节点分组嵌套，层数多于2时，外层标题被遮挡

### ISSUE THREAD

**Issue by ESnail** [antvis/G6#1251]
https://codesandbox.io/s/gifted-sara-lzum6?fontsize=14&hidenavigation=1&theme=dark
关于节点分组嵌套多层（2层以上），外层标题被遮挡。具体看groups，有4层，但是完全看不到外面两层了。
版本：3.2.8，3.3.5

**Comment by Yanyan-Wang** [comment]
带有全新节点分组 Combo 机制的 v3.5 发布了。demos：
内置 combos: https://g6.antv.vision/zh/examples/item/defaultCombos
自定义 combos: https://g6.antv.vision/zh/examples/item/customCombo
Combo 的布局: https://g6.antv.vision/zh/examples/net/comboForce
Combo 的交互: https://g6.antv.vision/zh/examples/interaction/combo

文档可以通过 [G6 官网](https://g6.antv.vision/zh) 上方的搜索栏搜索“combo”查看。
