### ISSUE TITLE
在配置项中animate:true的情况下导致group位置错误

### ISSUE THREAD

**Issue by qqqaaassshu** [antvis/G6#1252]
当配置项中包含animate:true的情况
`const graph = new G6.Graph({
    ...
    animate:true,
    ....
});
....
graph.addItem('group', {
    groupId: 'xxxx000999',
    nodes: [
        'node1'
    ],
    type: 'circle',
    title: '',
});
`
会导致group在左上方 并不会去包裹节点

**Comment by Yanyan-Wang** [comment]
目前节点分组的机制是一个临时的方案，存在很多问题。节点分组的问题都会在下个月的新版本中解决，我们正在重新设计和实现节点分组的新机制。

**Comment by Yanyan-Wang** [comment]
带有全新节点分组 Combo 机制的 v3.5 发布了。demos：
内置 combos: https://g6.antv.vision/zh/examples/item/defaultCombos
自定义 combos: https://g6.antv.vision/zh/examples/item/customCombo
Combo 的布局: https://g6.antv.vision/zh/examples/net/comboForce
Combo 的交互: https://g6.antv.vision/zh/examples/interaction/combo

文档可以通过 [G6 官网](https://g6.antv.vision/zh) 上方的搜索栏搜索“combo”查看。
