### ISSUE TITLE
TreeGraph无法监听 beforelayout/afterlayout？

### ISSUE THREAD

**Issue by xhay1122** [antvis/G6#1253]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**: https://codesandbox.io/s/purple-snow-hdj0t

**Comment by Yanyan-Wang** [comment]
TreeGraph 目前有 beforerefreshlayout 和 afterrefreshlayout 这两个事件。下个小版本增加和 Graph 统一的 beforelayout/afterlayout。
