### ISSUE TITLE
iconfont引入后第一次无法正常显示

### ISSUE THREAD

**Issue by kkltmoyu** [antvis/G6#1256]
环境：浏览器：69.0.3497.100，Win 7 64 ，
         G6版本：3.3.6
        Vue版本：2.6.11

问题描述：页面加载直接渲染自定义的Node，Node中通过group.addShape添加text，引入的iconfont第一次无法正常显示，刷新页面后可以正常显示。
demo地址：https://kkltmoyu.github.io/g6-demo/#/
源码地址： https://github.com/kkltmoyu/g6-demo

PS：正常显示后如需复现，需清除浏览器缓存

**Comment by kkltmoyu** [comment]
这个问题没人管吗？

**Comment by crystalwm** [comment]
应该和G6无关，在我的项目中用iconfont没有这个问题。我看了一些你的demo，感觉是时序问题，G6的代码运行了，但是font还没有加载

**Comment by kkltmoyu** [comment]
> 应该和G6无关，在我的项目中用iconfont没有这个问题。我看了一些你的demo，感觉是时序问题，G6的代码运行了，但是font还没有加载

其实一开始我也和你想的一样，由于iconfont没加载完就已经渲染完canvas了导致图标识别不出来，我本地测试过，提前iconfont.css的加载，然后在mounted声明周期里面settimeout了5秒后运行，结果发现还是这样，不过我当时的测试过程没有体现在这个demo里面

**Comment by crystalwm** [comment]
你需要调研一下用vue cli打包项目如何加载iconfont资源问题。你可以把setTimeout时间设置更长一些。
在我的项目中，用webpack打包vue项目，iconfont是可以和G6一起使用，没有你出现的问题。iconfont资源文件需要提前加载好。

**Comment by kkltmoyu** [comment]
好我看下，多谢回复

**Comment by anywhy** [comment]
遇到同样的问题，第一次不显示，拖动画布或节点就显示了。

**Comment by kkltmoyu** [comment]
我觉得和我用的vue cli无关，vue cli3 默认启用了prefetch加载，而且自定义icon在canvas显示不出来，但是用 <i> 标签就能显示，说明iconfont文件已经加载完成了，具体demo明天更上了

**Comment by baizn** [comment]
第一次加载进来这样，icon 是不是这样子的呢？
![image](https://user-images.githubusercontent.com/9443867/76955987-28237780-694e-11ea-9294-314f02c7384a.png)

**Comment by kkltmoyu** [comment]
> 第一次加载进来这样，icon 是不是这样子的呢？
> ![image](https://user-images.githubusercontent.com/9443867/76955987-28237780-694e-11ea-9294-314f02c7384a.png)
![image](https://raw.githubusercontent.com/kkltmoyu/g6-demo/master/src/assets/pic.PNG)
在我这里是这个样子的，下面的显示的是方框。原本这个问题是百分之一百复现，但是现在因为demo页面加入了i标签，现在首次加载是有一定几率出现，未找到规律

**Comment by linkai0001** [comment]
我刚好也遇到此问题， canvas 渲染方式会有问题，  svg 是正常的， 可以先尝试使用 svg 渲染方式

**Comment by kkltmoyu** [comment]
> 我刚好也遇到此问题， canvas 渲染方式会有问题， svg 是正常的， 可以先尝试使用 svg 渲染方式

这个方法我没尝试过，我最后采用的方式是第一次进来的时候调用refresh()方法
`
setTimeout(() => {
					this.graph.refresh();
				}, 500)
`
PS：svg绘制节点数量比较大会有性能问题吧？

**Comment by Yanyan-Wang** [comment]
暂时没有找到原因，可以先这样解决：
graph.render(); 之后加这段代码：
```javascript
setTimeout(() => {
  graph.paint();
}, 16);
```

**Comment by Simmon12** [comment]
> setTimeout(() => { this.graph.refresh(); }, 500)

你是怎么判断是第一进来的？

**Comment by flycran** [comment]
我也遇到了这个问题，按照文档中[AntvG6 iconfont注意事项第三项](https://antv-g6.gitee.io/zh/docs/manual/advanced/iconfont#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)说的添加代码并没有什么用处，甚至把时间再加长到几秒钟也无济于事
```ts
setTimeout(() => {
  graph.paint();
}, 16);
```
但是我使用`document.fonts.load`来强制加载字体是有效的。
```ts
document.fonts.load('12px YouFontName').then(() => {
  graph.refresh()
})
```
这样做的优势很明显，因为这段代码一定会在字体加载后立即执行，而不是固定在多少毫秒后执行。
我建议把这一段写进文档，用于代替[AntvG6 iconfont注意事项第三项](https://antv-g6.gitee.io/zh/docs/manual/advanced/iconfont#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)
