### ISSUE TITLE
TreeGraph的findById和removeChild咨询

### ISSUE THREAD

**Issue by xhay1122** [antvis/G6#1257]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:  https://codesandbox.io/s/little-fire-nk17i

当节点折叠时，使用findById方法无法获取到node的实例，但是findDataById能获取到数据
在调用removeChild时，折叠的元素也不能删除。

这两个API就是这么设计的吗？

**Comment by Yanyan-Wang** [comment]
是的，折叠的元素暂时从 graph 上被删去了。但是 data 还是存在的。
