### ISSUE TITLE
registerNode注册节点时只能完全创建新图形，无法修改现有图形

### ISSUE THREAD

**Issue by Jeffery-Young** [antvis/g6#126]
RT, 当使用registerNode注册节点时，目前仅提供draw、afterDraw供绘制、添加绘制新图形。
而更多的场景，是想基于已有的rect图形修改，比如定义颜色、样式等。

在文档中未发现相关说明，是否有计划提供？

**Comment by TomHuangCN** [comment]
```js
net.node().style(model=>{
  return obj;
})
```
