### ISSUE TITLE
希望是节点上文本能够也有捕获事件

### ISSUE THREAD

**Issue by font-end-hcq** [antvis/G6#1262]
原因是：以前点击树形节点的文字内容，使用ev.target.get('className') 还能打印出 node-label呢 现在不行了
结论是：底层的图形捕获逻辑有变化，希望是节点上文本的不捕获事件，全部由 keyShape 捕获。希望可以考虑一下怎么设计比较好

**Comment by Yanyan-Wang** [comment]
将在 v3.3.7 中解决
