### ISSUE TITLE
请问一下，自定义边的层级怎么调整，当边高亮的时候，高亮的颜色在没有高亮颜色的下面

### ISSUE THREAD

**Issue by big-MuMu** [antvis/G6#1263]
![image](https://user-images.githubusercontent.com/26105552/75621490-0006eb00-5bd0-11ea-9ff8-fe89bf525f24.png)

**Comment by Yanyan-Wang** [comment]
和内置是一样的：
https://g6.antv.vision/zh/examples/interaction/highlight
https://g6.antv.vision/zh/docs/manual/middle/elements/elementIndex
