### ISSUE TITLE
Why is there no option to prevent overlapping of groups?

### ISSUE THREAD

**Issue by chinloyal** [antvis/G6#1264]
- **G6 Version**: 3.3.6
- **Platform**: Linux

I also cannot prevent nodes from being dragged out of a group without disabling the drag completely?

**Comment by Yanyan-Wang** [comment]
For now, Group in G6 only has some basic function and some simple interactions.

We plan to re-design and refactor it in v3.5.

**Comment by laubonghaudoi** [comment]
I have this issue too, hope there will be a fix as soon as possible.

**Comment by JyotsnaC** [comment]
When is v3.5 release?

**Comment by Yanyan-Wang** [comment]
v3.5 is released. Try it here:
Built-in combos: https://g6.antv.vision/en/examples/item/defaultCombos
Custom combos: https://g6.antv.vision/en/examples/item/customCombo
Combo with layout: https://g6.antv.vision/en/examples/net/comboForce
Combo behaviors: https://g6.antv.vision/en/examples/interaction/combo

For the docs, you can search 'combo' with the search bar on the top of our website.
