### ISSUE TITLE
新版本polyline连线混乱

### ISSUE THREAD

**Issue by RenektonZ** [antvis/G6#1265]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
麻烦给出图片或者在线链接。

考虑设置边的连入点，还可以根据需求自己计算控制点。例如：https://g6.antv.vision/zh/examples/case/customFlow

**Comment by RenektonZ** [comment]
![1583288154645](https://user-images.githubusercontent.com/28641573/75838592-4ee79700-5e01-11ea-8b75-381548e3fc78.jpg)

**Comment by Yanyan-Wang** [comment]
谢谢，这边会跟踪排查。
