### ISSUE TITLE
G6在1.2.8版本支持 group.addShape('arc'); 但是在3.*.*版本此接口得不到支持，阅读文档，没有得到好的解决方案

### ISSUE THREAD

**Issue by congwa** [antvis/G6#1266]

**Comment by congwa** [comment]
需要自定义曲线的时候来用，有没有自定义曲线的示例

**Comment by Yanyan-Wang** [comment]
arc 已经被去除了。只能自己使用 path 来实现，规则和 SVG(https://developer.mozilla.org/zh-CN/docs/Web/SVG/Tutorial/Paths) 一样。
