### ISSUE TITLE
使用minimap时，数据量过大时，导致节点，画布拖拽严重卡顿，切换minmap属性type也一样

### ISSUE THREAD

**Issue by taffar** [antvis/G6#1267]
使用minimap时，数据量过大时，导致节点，画布拖拽严重卡顿,切换minmap属性type也一样

**Comment by Yanyan-Wang** [comment]
数量有多大？约有多少个图元？使用 minimap 后，有两个画布同时在刷新，相当于有两倍的图元在操作，在数据量大时卡顿是正常的。

**Comment by Yanyan-Wang** [comment]
Fixed by 3.4.5.

使用了 debounce 以降低 minimap 的渲染频率。
