### ISSUE TITLE
下载图片只能下载可视化部分

### ISSUE THREAD

**Issue by taffar** [antvis/G6#1268]
下载图片只能下载可视化部分，很尴尬

**Comment by Yanyan-Wang** [comment]
具体什么意思呢？下载的是画布上的内容。

**Comment by taffar** [comment]
比如内容滚轮放大后，超出视口，再下载图片就不是完整的内容了，只能下载视口范围内的部分。
想要的效果是，无论怎么操作，下载下来都是完整的内容

**Comment by Yanyan-Wang** [comment]
目前设计的机制就是下载当前画布上的内容呢。可以在下载之前 graph.fitView()，先进行自适应。

**Comment by luckydogM** [comment]
可以弄一个隐藏的minimap尺寸设置和画布尺寸一致，然后保存图片的时候保存minimap的画布就可以保存真实尺寸的图片了，但是要设置一个最大值，浏览器有最大像素限制

**Comment by Yanyan-Wang** [comment]
现在有 downloadFullImage 这个 API 了，可以下载全图
