### ISSUE TITLE
浏览器缩放设置为低于100% 树形图中节点的点击事件无法触发正确的点击事件

### ISSUE THREAD

**Issue by WXG9722** [antvis/G6#1269]
- **G6 Version**: 3.3.6
- **Platform**: Ubuntu Windows MAC Chrome浏览器
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:
https://g6.antv.vision/zh/examples/tree/mindmap

浏览器缩放为80% 树形图节点点击事件无法触发或触发位置错误 官网就可以复现

步骤 1: 将浏览器缩放比例设置为低于100%
步骤 2: 打开官网链接 进入树形图 点击节点 无法触发正确的点击事件

**Comment by Yanyan-Wang** [comment]
![80percent-tree](https://user-images.githubusercontent.com/29593318/75749042-d084e980-5d5b-11ea-8468-a6818c206dc1.gif)

没有发现异常呀？

**Comment by WXG9722** [comment]
> ![80percent-tree](https://user-images.githubusercontent.com/29593318/75749042-d084e980-5d5b-11ea-8468-a6818c206dc1.gif)
> 
> 没有发现异常呀？

先设置缩放比例 再进入官网 或缩放比例之后刷新官网 
缩放指的是不是canvas缩放 是浏览器缩放
![image](https://user-images.githubusercontent.com/43609464/75766341-fa4e0880-5d7b-11ea-85a3-81e84b3093c0.png)

**Comment by Yanyan-Wang** [comment]
对的，录屏就是缩小了浏览器的比例。然后也尝试了一下你说的缩小比例之后再刷新页面，还是没有复现呢。测试环境：chrome

你的是什么浏览器？

**Comment by WXG9722** [comment]
> 对的，录屏就是缩小了浏览器的比例。然后也尝试了一下你说的缩小比例之后再刷新页面，还是没有复现呢。测试环境：chrome 版本 80.0.3987.122（正式版本） （64 位）
> 
> 你的是什么浏览器？

Chrome版本 80.0.3987.132（正式版本） （64 位）
我是ubuntu系统 我同事的mac也用的Chrome 也不行

**Comment by WXG9722** [comment]
> 对的，录屏就是缩小了浏览器的比例。然后也尝试了一下你说的缩小比例之后再刷新页面，还是没有复现呢。测试环境：chrome 版本 80.0.3987.122（正式版本） （64 位）
> 
> 你的是什么浏览器？

刚才试了一下 ubuntu的Chrome Firefox不行 mac的Chrome可以

**Comment by Liuqing650** [comment]
同样遇到浏览器缩放后无法交互到正确节点，节点感知区域和绘制区域错位，不再一起了，请求激活这个bug
