### ISSUE TITLE
行为模式设置了 wheelZoom 不能用滚轮缩放

### ISSUE THREAD

**Issue by zunyiGuo** [antvis/g6#127]
https://antv.alipay.com/zh-cn/g6/1.x/demo/other/mode.html

发现还需要再加一个 'clickFocus' 就可以用了

**Comment by huarse** [comment]
+1，我也被这个搞了好久，希望文档更新一下

**Comment by sparkle777** [comment]
请问clickFocus加到哪里？上面的链接已经不可用了
