### ISSUE TITLE
'collapse-expand-group' behaviour does not work

### ISSUE THREAD

**Issue by chinloyal** [antvis/G6#1270]
- **G6 Version**: 3.3.6
- **Platform**: Linux
- **Mini Showcase(like screenshots)**:
- **CodePen Link**: https://codesandbox.io/s/2pe82

The codepen link is an example of yours, in the documentation it says double click to collapse or expand groups

> Manipulate the Group
> 
> The built-in Behaviors drag-group, collapse-expand-group, and drag-node-with-group allow user to manipulate the group:
> 
>     Drag the group;
>     Unrelate the node and its group by dragging the node out of the group;
> 
>     Double click to expand/collapse the group:
>         When the group is collapsed, the edges linked to the inner nodes will link to the group;
>         When the group is expanded, the related edges are restored.
>     When user is dragging a node, the node's group will be highlighted; when the node is dragged to another group, the corresponding group will be highlighted

However double clicking does not work, is there an event on groups where I could just call `graph.collapseGroup('group1')`? I haven't seen any in the documentation.

**Comment by Yanyan-Wang** [comment]
Thanks for feedback. It is a bug which will be resolved in next version (v3.3.7).
