### ISSUE TITLE
3.3.x 节点设置 shadowBlur 拖动会有残影

### ISSUE THREAD

**Issue by FreeRide-Joe** [antvis/G6#1272]
复现步骤：

1. 节点设置shadowBlur 
2. 拖动节点

残影情况：
![image](https://user-images.githubusercontent.com/16112889/75754819-5870f080-5d68-11ea-9a10-f51f66878924.png)

复现地址：https://codepen.io/Joe_/full/abOymVP

**Comment by AILINGANGEL** [comment]
我也遇到了这个问题

**Comment by Yanyan-Wang** [comment]
这个问题正在修复中，遇到这个问题的同学可以先这样 graph.get('canvas').set('localRefresh',false); 关掉局部渲染

合并到 issue： https://github.com/antvis/G6/issues/1248

**Comment by zmcode** [comment]
2023年了, 这个问题还没修复
![image](https://user-images.githubusercontent.com/48686959/225539471-344d18f5-8feb-4234-83ea-ce38c65cfdc5.png)
