### ISSUE TITLE
能否提供一个获取画布大小的方法？

### ISSUE THREAD

**Issue by lulei90** [antvis/G6#1273]
现有导出图片功能只支持将可视区域之内的渲染成图片，导致部分可视区外的元素无法被正常导出。在3.3版本之前还能通过svg渲染，拿到实际大小去改变可视区大小来实现这一功能，升级到3.3版本后无法使用svg渲染，导致之前导出完整图片的需求无法被满足。能否提供一个获取实际元素大小的方法，或者说是能直接提供导出完整图片的方法，这种需求在实际业务中还是比较常见的

**Comment by Yanyan-Wang** [comment]
在 graph.fitView 之后，所有内容都会被自适应到适口范围内

**Comment by lulei90** [comment]
> 在graph.fitView之后，所有内容都会被适应到适口范围内

fitView在画布很大的情况下无法满足内容适配到可视区域内，并且缩放后的图下载后完全无法使用
