### ISSUE TITLE
canvas.get('pixelRatio')返回undefined

### ISSUE THREAD

**Issue by AILINGANGEL** [antvis/G6#1274]
在任意demo里都可以测试当前画布的pixelRatio值变成了undefined
![image](https://user-images.githubusercontent.com/28471649/75756629-f31efe80-5d6b-11ea-9d52-759b379e4853.png)

**Comment by Yanyan-Wang** [comment]
这个已经废弃了，图会自己根据当前的 pixelRatio 进行调整，不需要用户传入 pixelRatio 到图的实例中了
