### ISSUE TITLE
五阶贝塞尔曲线，怎么绘制？

### ISSUE THREAD

**Issue by bluce** [antvis/G6#1275]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
没有内置，自己自定义。在自定义边中，使用 group.addShape('path', { attrs: {}}); 添加图形， attrs 里面的 path 属性规则和 SVG 一样: https://developer.mozilla.org/zh-CN/docs/Web/SVG/Tutorial/Paths
