### ISSUE TITLE
能否提供一个获取画布大小的方法？

### ISSUE THREAD

**Issue by lulei90** [antvis/G6#1276]
大数据量的情况下，很多数据被渲染到可视区外。现有导出图片功能只支持将可视区域之内的渲染成图片，导致部分可视区外的元素无法被正常导出。在3.3版本之前还能通过svg渲染，拿到实际大小去改变可视区大小来实现这一功能，升级到3.3版本后无法使用svg渲染，导致之前导出完整图片的需求无法被满足。使用fitView方法在大数据量情况下也无法完全适配，或者显示的很小导出的图片无法正常使用。希望能提供一个获取画布大小的方法，这样可以在导出画布前将可视区变化满足全部展示后在进行下载

**Comment by Yanyan-Wang** [comment]
graph.get('group').getCanvasBBox() 可以拿到图的包围盒，里面有最大最小坐标以及宽高。

**Comment by Nancy2013** [comment]
> graph.get('group').getCanvasBBox() 可以拿到图的包围盒，里面有最大最小坐标以及宽高。

你好，想问下，在@antv/g6  v5.0.1版本中 graph.get('group')提示不存在，可以通过什么方式获取画布元素高度，然后重置画布的大小
