### ISSUE TITLE
更新note节点配置，label属性不能从有内容字符串变为空字符串

### ISSUE THREAD

**Issue by linchan** [antvis/G6#1277]
在input框里面输入字符，node的label属性可以更新为填写的内容；
当我删除input框里面的字符的时候，只要没删除到最后一位，label都可以变更，当删除最后一位字符，label没变法变更，还保留最后一位字符。
<el-input  v-model="label"></el-input>

update（）{
  node.update(
                        {
                            label :this.label
                        }
                    )
}

**Comment by Yanyan-Wang** [comment]
感谢反馈，v3.3.7 已修复。
