### ISSUE TITLE
关于自定义节点中图片的问题

### ISSUE THREAD

**Issue by 10168075** [antvis/g6#128]
麻烦问下，我使用脑图编辑器案例的树图结构，所有节点都是自定义的节点，如果自定义节点HTML中存在img（src是base64转码过），则页面首次加载时图片不能在节点内正常显示，而是出现在节点外面，刷新页面后可以正常显示（代码可以在最后下载，demo.txt，后缀名改为html打开就可以了），如下图：
![image](https://user-images.githubusercontent.com/34783421/34317165-8c7ebcba-e7e3-11e7-9efb-5bb0d3799ba2.png)
![image](https://user-images.githubusercontent.com/34783421/34317169-a5024586-e7e3-11e7-98b8-c9820bcf2cbc.png)

但是在Safari浏览器中刷新也不行，请问有没有解决的办法，谢谢。
另外，还有几个问题，还要请教下：
# 1、想改变鼠标放在空白区域和放在节点上的不同鼠标形状，请问能不能实现；
# 2、点击图的空白区域不放可以拖动画布，能不能点击图中的节点时不放也能拖动画布；
# 3、点击树图中的线时，线两头会出现方框box，能不能去掉（在折叠按钮隐藏的情况下，showButton: false）
![image](https://user-images.githubusercontent.com/34783421/34317195-2aabb154-e7e4-11e7-8f70-65a37b661762.png)

# 4、添加节点时，想在已添加的节点中间插入节点，能不能实现：如下图：
![image](https://user-images.githubusercontent.com/34783421/34317115-6050f0b4-e7e2-11e7-84ce-3411b1f59cf5.png)

# 5、在1.2.1版本中，自定义节点内容修改后（tree.update一个节点后），其他节点不能选中，1.1.6版本可以正常选中其他节点，如下图：

![image](https://user-images.githubusercontent.com/34783421/34317149-252e9fd0-e7e3-11e7-96bc-1c3bfadb6a52.png)

[demo.txt](https://github.com/antvis/g6/files/1583884/demo.txt)

**Comment by TomHuangCN** [comment]
首先，写 codepen 吧，txt 太难同步了。


1.  animate: false; stroke: null; 解决图片换行问题

```js
animate: false,
```

```js
    var nodeStyle = {
		lineWidth: 1,
		stroke: null
    };
```

2. 鼠标形状问题

```js
const el = net.get('el'); // 拿到最上层canvas的dom ，再配合mouseenter mouseleave 事件改变手型
```

3. 移除边控制点

```js
G6.Global.edgeControlPointStyle  = null
```

4. 自己控制，插入元素所在 children 数组里的顺序

5. 没懂，单独写一个 codepen 描述问题

**Comment by 10168075** [comment]
https://codepen.io/mengchao666/pen/JMbarE
还是要麻烦看下，图片换行的问题，第一次加载的时候图片还是不在节点内，刷新页面后可以正常显示，再次进入页面也可以正常显示，但是清除缓存后再刷新页面又不行（谷歌浏览器）
![image](https://user-images.githubusercontent.com/34783421/34335044-adf45900-e986-11e7-877f-2273f138c47c.png)

**Comment by TomHuangCN** [comment]
我这边看貌似是因为边框占了位置。storke null 以下就好了

```js
    var nodeStyle = {
		lineWidth: 1,
		stroke: null
    };
```

或者你直接加个  `nowrap` 就好了啊

```css
.nodediv{
  white-space:nowrap;
}
```

**Comment by 10168075** [comment]
1、不是边框占了位置，和边框没关系的，你去掉边框看到显示正常了，是因为有缓存了，清除缓存再加载还是那样；
2、 white-space:nowrap;更不行，直接文字图片都不在节点范围内了，之前还知识图片不在节点范围内：
![image](https://user-images.githubusercontent.com/34783421/34367277-86729460-eae3-11e7-8999-a3f5baa45012.png)

**Comment by TomHuangCN** [comment]
我这里挺难复现你这个问题的（safari 下也无法稳定复现）。设置 `cssSize: true` 后内部会自动去获取这个dom节点宽高。然后设置为该节点的宽高。根据目前的情况看，应该是第一次图片没加载下来，导致初始宽高计算有误。考虑一下通过一些做法，在图片加载完把img的width和height预先设置好，再渲染

**Comment by 10168075** [comment]
好的，谢谢。

**Comment by 10168075** [comment]
还要麻烦问下，
1、移动端不能点住空白区域拖拽画布，有没有解决办法？
2、另外，移动端的tree.on('click',function(){})事件，有没有类似于fastclick之类的方法，因为点击一下，会触发很多次click事件。

**Comment by TomHuangCN** [comment]
暂时没有考虑移动端。没有封装移动端的事件

**Comment by 10168075** [comment]
还有问题麻烦问下：
1、当我在移动端使用时，能否有方法在touch事件中使画布能够移动，就像PC上的鼠标点击空白区域拖动画布的效果；
2、关于矩阵只有一些api文档，有没有关于matrix的方法的示例，比如graph.updateMatrix方法和matrix.translate方法的示例等；
谢谢！

**Comment by 10168075** [comment]
移动端树图移动问题已解决；
另外想麻烦问下，矩阵在G6中的含义，是不是所有tree和net都可以理解为一个矩阵，节点的移动、图的布局都是操作的矩阵？
谢谢。

**Comment by TomHuangCN** [comment]
矩阵不是g6里的概念，是底层图形库的概念，可以翻翻图形学看看变换的概念
