### ISSUE TITLE
如何重新渲染当前节点

### ISSUE THREAD

**Issue by AILINGANGEL** [antvis/G6#1280]
如何重新创建当前节点，比如说最开始节点的样子是A,我调用某个方法把节点的样子变成B

**Comment by Yanyan-Wang** [comment]
item.update，或者全图更新数据 graph.changeData

在文档和 API 中有全面介绍，可以多看看

**Comment by AILINGANGEL** [comment]
我的节点是我自定义的，如下图：
![image](https://user-images.githubusercontent.com/28471649/76065860-6a040380-5fc7-11ea-9a27-0efa1131821a.png)

我自定义节点的时候，如果该节点有children我就会渲染+和-的icon；现在我点击孩子节点(没有我自定义的+和-)，我拿到了数据并且给节点添加children，这时这个节点应该重新渲染一次画出我定义的+和-。我调用了 update, updateItem, updateChild 所有能局部更新的方法都不行。但是如果把当前节点的父节点的 - 点击一次收起，然后再点击一次 + 展开，孩子节点就重新渲染了，会出现+。

但是我期望的操作是，我点击孩子节点动态给它添加孩子之后，能重新把我的自定义节点渲染一下，出现+ 号
