### ISSUE TITLE
如何重新渲染自定义节点

### ISSUE THREAD

**Issue by AILINGANGEL** [antvis/G6#1283]
我的节点是我自定义的，如下图：
![image](https://user-images.githubusercontent.com/28471649/76065860-6a040380-5fc7-11ea-9a27-0efa1131821a.png)

我自定义节点的时候，如果该节点有children我就会渲染+和-的icon；现在我点击孩子节点(没有我自定义的+和-)，我拿到了数据并且给节点添加children，这时这个节点应该重新渲染一次画出我定义的+和-。我调用了 update, updateItem, updateChild 所有能局部更新的方法都不行。但是如果把当前节点的父节点的 - 点击一次收起，然后再点击一次 + 展开，孩子节点就重新渲染了，会出现+。

但是我期望的操作是，我点击孩子节点动态给它添加孩子之后，能重新把我的自定义节点渲染一下，出现+ 号

_Originally posted by @AILINGANGEL in https://github.com/antvis/G6/issues/1280#issuecomment-595659908_

**Comment by Yanyan-Wang** [comment]
这个提供一个在线的 demo 看一下吧，这样不好定位到问题。

**Comment by baizn** [comment]
> 但是我期望的操作是，我点击孩子节点动态给它添加孩子之后，能重新把我的自定义节点渲染一下，出现+ 号

可以在添加完child数据后，使用 updateItem 更新一下当前节点。

**Comment by AILINGANGEL** [comment]
demo 地址:https://codesandbox.io/s/holy-bush-r5w5h
点击任意一个孩子节点，然后会动态给这个节点添加孩子。希望当前这个节点能重新渲染出+和-的icon。

**Comment by AILINGANGEL** [comment]
> > 但是我期望的操作是，我点击孩子节点动态给它添加孩子之后，能重新把我的自定义节点渲染一下，出现+ 号
> 
> 可以在添加完child数据后，使用 updateItem 更新一下当前节点。

试过了，没用

**Comment by baizn** [comment]
有两种方式实现：
1. 自定义节点时候不继承 single-node，则每次更新都会重新 draw；
2. 自定义节点时继承了 single-node，如果 updateItem 时需要节点有变化（增删元素），则需要实现 update方法。
![image](https://user-images.githubusercontent.com/9443867/76178974-3c4fd200-61f4-11ea-8aee-b6e884e88701.png)
