### ISSUE TITLE
如何根据后端返回数据渲染节点状态？

### ISSUE THREAD

**Issue by Wyq188300047** [antvis/G6#1284]
想根据后端返回数据（例如携带selected属性），在自定义节点初始化时根据自带属性直接渲染节点状态，请问该写在哪里？

**Comment by Yanyan-Wang** [comment]
可以在拿到数据图渲染之后，遍历一遍 graph.getNodes(), 然后把带有 selected 属性的节点设置一下状态：
graph.setItemState(item, 'selected', true);
