### ISSUE TITLE
graph.off 不生效 版本3.2.7

### ISSUE THREAD

**Issue by djif007** [antvis/G6#1285]
- **G6 Version**:3.2.7
- **Platform**:MAC
- **Mini Showcase(like screenshots)**: graph.off('node:click');
- **CodePen Link**:

通过graph.removeEvent可以达到效果，但是这个方法后续不会暴露

**Comment by Yanyan-Wang** [comment]
v3.2.x 可以使用 graph.removeEvent 或 graph.off('node:click', fn)

v3.3 以后可以使用 graph.off('node:click', fn) 或 graph.off('node:click')

文档正在补充中。
