### ISSUE TITLE
如何在drawShape方法中判断父节点与孩子节点的相对位置

### ISSUE THREAD

**Issue by AILINGANGEL** [antvis/G6#1292]
![image](https://user-images.githubusercontent.com/28471649/76229456-304c2a80-625d-11ea-88ce-fe14a826d939.png)

如上图所示，想通过判断父节点是在孩子节点的右边还是左边，从而决定展开和收起的marker的位置，如果父节点在子节点的右边，那么子节点的marker就应该放在子节点的左侧。如上图节点a和节点b所示，节点a是节点b的孩子节点，但是使用mindmap布局节点a渲染在了父节点b的左侧，因此想让节点a的maker放在文字的左边。

在drawShape中使用了下面的方法拿位置，console.log出来发现不太对。
![image](https://user-images.githubusercontent.com/28471649/76229778-b4061700-625d-11ea-9d40-890fcb7928dd.png)
![image](https://user-images.githubusercontent.com/28471649/76229840-cb450480-625d-11ea-8453-2aec959929f9.png)

**Comment by Yanyan-Wang** [comment]
在第一次绘制的时候，还没有布局信息，所以会出现拿不到位置的情况。

可以尝试在 afterDraw 里面去拿，然后根据相对位置关系更新一下 shape 的位置。就和复写 drawShape 差不多：https://g6.antv.vision/zh/docs/manual/advanced/custom-node
