### ISSUE TITLE
rank-same for Dagre node

### ISSUE THREAD

**Issue by csandanov** [antvis/G6#1298]
- **G6 Version**:  latest
- **Platform**: Chrome macOS
- **Mini Showcase(like screenshots)**:  [graph image](https://user-images.githubusercontent.com/1058233/76308750-0dbe1e00-62fe-11ea-8fdf-e7392bae5ee5.png)
- **CodePen Link**: https://codesandbox.io/s/focused-sinoussi-i8593

Hi, in the referenced example why is node **`a`** is not on the same rank (level) as nodes **`h`** and **`c`**? Is there a way to change that behavior? Or override the rank? For example, DOT language has the option `rank-same`. See the example below and the [result](https://user-images.githubusercontent.com/1058233/76309124-b0769c80-62fe-11ea-958b-c0c3264d9952.png). 
```
digraph G {
    rankdir = LR;
    splines=ortho
    node [shape=box ]
    a
    b
    c
    d
    i
    f
    g
    h
    i
    j
    k
    a -> d
    d -> g
    c -> {b e f}
    b -> d
    e -> g
    f -> g
    h -> {i j k}
    {rank=same; a c h}
    {rank=same; b e f i j k}
}
```

**Comment by Yanyan-Wang** [comment]
The dagre layout in G6 depends on [dagrejs](https://github.com/dagrejs/dagre), which does not support the configuration you asked.

If you have any good idea to support this demand, welcome PRs.
