### ISSUE TITLE
如何在自定义节点中设置锚点的位置

### ISSUE THREAD

**Issue by AILINGANGEL** [antvis/G6#1299]
![image](https://user-images.githubusercontent.com/28471649/76326928-4d97fc00-6324-11ea-9861-27b31e4e1197.png)
![image](https://user-images.githubusercontent.com/28471649/76327031-702a1500-6324-11ea-8dcf-49af0f78f7ef.png)
上图的节点是自定义的，当将这些节点放到图根节点的左侧时候，锚点看起来依然在[0, 0.5]的位置，求问如何在drawShape中设置放到左边的节点的锚点在[1, 0.5]的位置
ps:使用的是mindmap这种图

**Comment by Yanyan-Wang** [comment]
你是想把 Multi-layer feedforward neural network 这个节点链接到 Modeling Methods 的右边吗？

**Comment by AILINGANGEL** [comment]
> 你是想把 Multi-layer feedforward neural network 这个节点链接到 Modeling Methods 的右边吗？

不是的。这几个节点有一个父节点（regression），这个regression的点是Modeling Methods的孩子节点，并且位于Modelling Methods的左侧。现在被 Multi-layer feedforward neural network 节点给覆盖了。因为有设置getHGap，现在这几个节点的锚点在左侧，他们和父节点regression的距离为getHGap返回的值，但是这个距离不够长，所以被遮住了。我现在希望这几个节点的锚点可以是他们的右侧(1, 0.5)的地方。
PS: 我有给每个节点设置isLeft属性，并且在getSide地方根据这个属性是否为true决定是展示在左侧还是右侧。但是这个getSide返回left好像不代表锚点就会是节点的右侧？

**Comment by AILINGANGEL** [comment]
> 你是想把 Multi-layer feedforward neural network 这个节点链接到 Modeling Methods 的右边吗？

不用了，搞定了，是我的Hgap设置的不够，锚点是对的。
