### ISSUE TITLE
文字竖排如何实现（不是单行旋转）

### ISSUE THREAD

**Issue by zhanown** [antvis/G6#1300]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
目前没有内置的支持。可以处理一下数据中的文字，每个字换行。类似这样 https://g6.antv.vision/zh/examples/shape/label

**Comment by hWwXx** [comment]
最后是怎么解决的

**Comment by avrinfly** [comment]
文本里加换行符，类似下面这样
https://codesandbox.io/s/g6-wen-ben-shu-pai-kd0rpm
