### ISSUE TITLE
g6  @antv/g6/lib/types/index.d.ts  中type类型报错

### ISSUE THREAD

**Issue by ybrelax** [antvis/G6#1303]
![WK1%2%2BP@1T`6%(~O)M$S](https://user-images.githubusercontent.com/31029938/76431572-b5b21500-63ec-11ea-88eb-e00e457dc067.png)

**Comment by Yanyan-Wang** [comment]
是否传了不对应的参数类型？

**Comment by ybrelax** [comment]
> 是否传了不对应的参数类型？

今天换了3.3.1的包正常，但是3.4版本的包有问题。3.4版本中的index.d.ts确实出现了这个情况

**Comment by Yanyan-Wang** [comment]
请问你是如何使用导致的这个错误呢？我们这里复现一下然后定位问题在哪。

**Comment by ybrelax** [comment]
> 请问你是如何使用导致的这个错误呢？我们这里复现一下然后定位问题在哪。
我又试了以下
![Uploading image.png…]()
3.4.0 会出现这样的问题
3.3.1 没有问题

**Comment by ybrelax** [comment]
> 请问你是如何使用导致的这个错误呢？我们这里复现一下然后定位问题在哪。
![image](https://user-images.githubusercontent.com/31029938/76631746-26883700-657d-11ea-8fd7-305b9eff1987.png)

3.4.0 会出现这样的问题
3.3.1 没有问题
