### ISSUE TITLE
请问V3 支持支持自定义的groupType吗，类似于registerGroup 这样的api

### ISSUE THREAD

**Issue by 2012shenghua** [antvis/G6#1307]
- **G6 Version**: v3.4.0
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
3.4 暂时不支持。3.5 会重新设计节点分组相关，之后会支持。

**Comment by JyotsnaC** [comment]
When is the expected release date for  3.5 ?

**Comment by Yanyan-Wang** [comment]
v3.5 is released. Try it here: 
Built-in combos: https://g6.antv.vision/en/examples/item/defaultCombos
Custom combos: https://g6.antv.vision/en/examples/item/customCombo
Combo with layout: https://g6.antv.vision/en/examples/net/comboForce
Combo behaviors: https://g6.antv.vision/en/examples/interaction/combo

For the docs, you can search 'combo' with the search bar on the top of [our website](https://g6.antv.vision/zh).
