### ISSUE TITLE
统一分层布局 DAGRE 节点颜色配置问题

### ISSUE THREAD

**Issue by sunscheung** [antvis/g6#131]
请问下节点我设置颜色是红色，但是显示的是边框红色，而节点内部颜色是很淡的颜色，
![image](https://user-images.githubusercontent.com/9931345/34347590-9919e126-ea3f-11e7-9638-77127284650b.png)
这样的话，我设置颜色就不是自己真正设置的颜色了，有什么属性可以控制整个节点都是配置的实际颜色
@TomHuangCN

**Comment by TomHuangCN** [comment]
net.node().style({fill: 'red', 'stroke':'blue'})

**Comment by sunscheung** [comment]
我没表述好，net.node().style({fill: 'red', 'stroke':'blue'})这样是整体设置，
其实每个节点可能是不同颜色，所以用的color

**Comment by TomHuangCN** [comment]
写回调
```js
net.node().style(model=>{
  return {fill: 'red', 'stroke':'blue'};
})
```

**Comment by sunscheung** [comment]
这个fill和直接加color属性效果是一样的，边框的颜色才是我设置的颜色，节点内部颜色还是很淡。

![image](https://user-images.githubusercontent.com/9931345/34369709-2ba28e76-eaf9-11e7-8fce-3373c6734887.png)

**Comment by sunscheung** [comment]
加上这个属性  fillOpacity: 1  就行
谢谢 @TomHuangCN

**Comment by gostfather** [comment]
style的属性你在哪看到的?

**Comment by sunscheung** [comment]
@gostfather    看扫码业务里的代码 
https://antv.alipay.com/zh-cn/g6/1.x/demo/flow/saoma.html

**Comment by gostfather** [comment]
好的,感谢
