### ISSUE TITLE
G6@3.4.0 切换 mode 后，当前 mode 中 绑定事件未触发

### ISSUE THREAD

**Issue by FreeRide-Joe** [antvis/G6#1312]
复现步骤：
1. 在节点上按下鼠标左键（此时mode会切换为 addEdge）
2. 移动鼠标（鼠标左键未松开），add-edge 中绑定的 mousemove 事件未触发，鼠标松开后才会触发 mousemove

3.3.7 和 3.4.0 都有此问题，3.2.0 是正常的

具体代码见以下链接

复现地址：https://codepen.io/Joe_/full/qBdoMGX

**Comment by Yanyan-Wang** [comment]
3.3.x 之后的版本把 mousemove、mouseup 与 dragstart、drag、dragup 区分开了。你这里的场景应该属于 drag 和 dragup，因为鼠标是没有松开的情况下拖动。

**Comment by FreeRide-Joe** [comment]
@Yanyan-Wang 

你好，我是想实现 在A节点上按下鼠标，移动鼠标到B节点上，松开鼠标，然后添加一条连接AB的边。

但是 dragend 事件作用在被拖曳的元素上，event.target 始终是 A节点，无法从event 中获取鼠标松开时所在元素的信息，从而无法得知 鼠标是否移动到了B节点上

这种情况应该怎么处理呢？

**Comment by Yanyan-Wang** [comment]
dragend 的时候可以判断一下鼠标松开的位置，附近是否有节点。需要自己通过坐标来计算最近的节点。

**Comment by FreeRide-Joe** [comment]
@Yanyan-Wang 
感谢回答。

我换了个方式，添加了 node:drop 事件，当鼠标在节点上松开的时候就会触发，再 结合 dragend 就能判断 鼠标松开时的具体情况了
