### ISSUE TITLE
有没有defaultZoom  这样设置初始化放大比例的方法

### ISSUE THREAD

**Issue by 2012shenghua** [antvis/G6#1313]
- **G6 Version**: 
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
没有。可以在 graph.render 之后调用一下 graph.zoom()

https://g6.antv.vision/zh/docs/api/Graph/#zoomratio-center
