### ISSUE TITLE
dagre布局使用changeData添加数据后，节点位置发生对调

### ISSUE THREAD

**Issue by hujinbo** [antvis/G6#1314]
问题描述：dagre布局，使用changeData添加数据，两次渲染数据前面的节点/边顺序没有改变。第二次的数据是在第一次的基础上追加的（只添加了一个节点和一条边），但是重新渲染后，节点“图表1”和“图表2”的位置发生了对调。

- **G6 Version**: 3.3.6
- **Platform**: 
- **Mini Showcase(like screenshots)**: ![问题](https://user-images.githubusercontent.com/29507557/76726718-f8794180-678c-11ea-874b-ba22ac2dbc33.gif)
- **CodePen Link**: https://codesandbox.io/s/cranky-pond-dthio

**Comment by big-MuMu** [comment]
解决了吗

**Comment by hujinbo** [comment]
> 解决了吗

还没解决

**Comment by Yanyan-Wang** [comment]
G6 的 dagre 依赖了外部库 https://github.com/dagrejs/dagre
这个库也有提这个问题但是大概是算法机制的原因始终没有解决：https://github.com/dagrejs/dagre/issues/189

该算法会遍历数据生成树，可能是增加了节点之后生成树的遍历顺序有变化，导致了最终结果的差异。

**Comment by yingpengsha** [comment]
请问有替代方案吗🥺

**Comment by x-cold** [comment]
#189

**Comment by x-cold** [comment]
https://github.com/dagrejs/dagre/issues/189#issuecomment-927009920

**Comment by Nicklaus6** [comment]
> 

试了不行

**Comment by Yanyan-Wang** [comment]
新版本已支持数据增量时尽可能保持原始顺序
3.x -> 4.x 升级指南
http://g6.antv.antgroup.com/manual/faq/upgradeguide
https://github.com/antvis/G6/issues/2525
