### ISSUE TITLE
renderer为svg的模式下，自定义节点类型用html的情况下无法触发node:click事件

### ISSUE THREAD

**Issue by Tronsfey** [antvis/G6#1315]
- **G6 Version**:3.4
- **Platform**:mac
- **Mini Showcase(like screenshots)**:
- **CodePen Link**: https://codesandbox.io/s/intelligent-stallman-f4f4l

如题，renderer为svg的时候，自定义节点类型用html的情况下点击节点时候，可以正常触发canvas：click和click事件，但是无法触发node:click事件。

**Comment by Yanyan-Wang** [comment]
HTML 节点需要直接在 DOM 上面绑定事件，不要使用 G6 的事件。

**Comment by Tronsfey** [comment]
给个简单dom事件处理这种情况的demo
https://codesandbox.io/s/svg-render-node-click-not-working-hbe37

**Comment by Yanyan-Wang** [comment]
> 给个简单dom事件处理这种情况的demo
> https://codesandbox.io/s/svg-render-node-click-not-working-hbe37

👍感谢提供 demo

另外，简单的监听也可以直接写到 dom 图形的 html 字段里面。
