### ISSUE TITLE
g6 3.4版本 切换模式增加点和边，增加边时拖拽带箭头的line，会有残留的箭头痕迹留下

### ISSUE THREAD

**Issue by zaki1991** [antvis/G6#1317]
- **G6 Version**:3.4
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
v3.4.1 修复，已发布。可以看下还有没有问题，如果还有问题麻烦回复在这里
