### ISSUE TITLE
自定义了一个drag行为，对节点进行mousedown时切换mode为drag时，触发mousemove时获取不到当前mousedown的item对象，item为null。这种情况时有时无

### ISSUE THREAD

**Issue by hahaVang** [antvis/G6#1319]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
需要提供一下在线 demo，具体看看自定义的 drag 是怎么写的

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
