### ISSUE TITLE
node:mouseenter and other graph events do not work for DOM nodes

### ISSUE THREAD

**Issue by UnchartedBull** [antvis/G6#1321]
- **G6 Version**: 1.4.0
- **Platform**: MacOS 10.15.3, Google Chrome 80.0.3987.132 64-bit
- **Mini Showcase(like screenshots)**: n.a.
- **CodePen Link**: https://codesandbox.io/s/crazy-kowalevski-wybn4

Any of the `graph.on('node:*')` event listener do not work with HTML DOM elements. I copied your example DOM Elements and created a `node:mouseenter` listener, which doesn't get triggered if I move over a DOM NOde. Once I convert one of the nodes to a normal rect the event is working fine for that node and the event is shown in the console. The other node still doesn't trigger the event. You can easily test this by just hovering over the the two nodes. The right one will output a message in the console (rect-node), while the other one won't (dom-node).

How can I make this work? Is this intended to not work with DOM elements? I didn't find anything about that in the documentation.

**Comment by Yanyan-Wang** [comment]
G6 in the demo you show is v3.4.

DOM elements do not support the built-in events of G6, pls use the original HTML DOM events instead. 

The document was just updated: https://g6.antv.vision/en/docs/api/shapeProperties#dom-svg

**Comment by UnchartedBull** [comment]
Sorry somehow thought of 1.4 instead of 3.4

Ah ok, thanks for updating the docs!
