### ISSUE TITLE
调用changeData方法后，隐藏的边又显示出来，隐藏的节点则可以保持隐藏状态

### ISSUE THREAD

**Issue by hujinbo** [antvis/G6#1323]
问题描述：在Demo中，点击“隐藏节点”，调用node.hide() edge.hide()节点正常隐藏。点击“改变数据”调用changeData方法后，节点能隐藏，但是边又显示出来了。
应该跟此问题一样：https://github.com/antvis/G6/issues/1037

- **G6 Version**: 3.3.6
- **Platform**:
- **Mini Showcase(like screenshots)**:  ![问题2](https://user-images.githubusercontent.com/29507557/76942474-c4428400-6938-11ea-9e97-4f8d698bdf8d.gif)
- **CodePen Link**: https://codesandbox.io/s/strange-morse-nu2ie

**Comment by baizn** [comment]
是个 BUG，下个版本修复，详见[这里](https://github.com/antvis/G6/pull/1324/files#diff-76cf0eb5e3d8032945f1ac79ffc5e815R86)。

**Comment by Yanyan-Wang** [comment]
v3.4.2 已发布，已修复。
