### ISSUE TITLE
Grid 插件适配问题

### ISSUE THREAD

**Issue by rockSandy** [antvis/G6#1327]
- **G6 Version**: 3.3.5
- **Platform**: 
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

Grid 插件在 changeSize， zoomIn 之后没有覆盖整个画布
另外，希望Grid 可以支持自定义图片

**Comment by Yanyan-Wang** [comment]
- Grid 在 changeSize zoomIn 的问题 v3.4.4 已修复；
- v3.4.4 支持使用自定义图片作为 Grid，详见文档：https://g6.antv.vision/zh/docs/api/Plugins#grid。
