### ISSUE TITLE
G6 3.X节点如何拖动边来缩放大小和改变形状

### ISSUE THREAD

**Issue by cym-heu** [antvis/G6#1333]
这个功能g6 1.x还有，g6 3.x好像已经没了

**Comment by Yanyan-Wang** [comment]
现在没有这个功能，G6 目前定位主要是展示+分析+轻编辑场景。这种重编辑的场景推荐用 AntV X6，刚刚开源的一个图编辑库。

**Comment by cym-heu** [comment]
请问x6和G6可以在同一个画布上搭配使用吗

**Comment by Yanyan-Wang** [comment]
目前不可以的哦
