### ISSUE TITLE
2.x、3.x如何实现手动画两个Node之间的连线

### ISSUE THREAD

**Issue by littlesky007** [antvis/G6#1334]
在1.x版本中，可以使用Net.beginAdd鼠标拖动，添加两个Node之间的连线，问下，在2.x和3.x如何实现？有没有相应替代函数？

**Comment by Yanyan-Wang** [comment]
3.x 看一下这个例子
https://g6.antv.vision/zh/examples/interaction/setMode
https://g6.antv.vision/zh/docs/manual/advanced/mode-and-custom-behavior
