### ISSUE TITLE
关于Behavior 能否提供一个初始化回调函数呢？

### ISSUE THREAD

**Issue by Liuqing650** [antvis/G6#1336]
- **G6 Version**: 3.4.0
- **Platform**: ubuntu 16.04
- **Mini Showcase(like screenshots)**:
- **CodePen Link**: https://codepen.io/Liuqing650/pen/vYOzxaN

在 Behavior 注册中，按照目前的文档好像是支持以下几类事件
通用事件、Node事件、Edge事件及Canvas事件回调
参考文档： https://www.yuque.com/antv/g6/event-api

在某些特殊时候需要监听 时机事件类，例如在添加一个Item时触发 `afteradditem` 等，
目前参考源码中能做到这一情况的貌似只能在 getEvents去实现，但显得非常不妥当
```ts
G6.registerBehavior('behaviorName', {
  getEvents() {
   // 执行初始化函数...
    setTimeout(() => this.init.call(this), 0);
    return {
      'mousemove': 'onMouseMove'
    }
  },
  init() {
    this.graph.on('afteradditem', () => {
      console.log('初始化和监听一些东西');
    });
  }
})
```

所以，请问能否考虑提供一个初始化的回调函数呢？

**Comment by Liuqing650** [comment]
这里应该没有init，有相关操作应该写成一个Plugin，希望补充一些Plugin实现的文档说明

**Comment by Yanyan-Wang** [comment]
希望自己触发一些事件的话，可以这样：
graph.emit('xxxx', {
// some params
});

感谢提醒，后续会完善文档

**Comment by Superzzw1994** [comment]
你好，请问下，在自定义Behavior执行结束后想抛出一些参数是不是只能用这个graph.emit()，比如说自定义了一个框选操作，在框选结束后想抛出被框选到的id，谢谢。
