### ISSUE TITLE
在html里直接引用js后，节点动画没有效果，是还需要额外引用什么辅助js吗，我引用的antv.g6-3.2.3

### ISSUE THREAD

**Issue by LookForwordTomorrow** [antvis/G6#1339]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
怎么使用的动画？

**Comment by LookForwordTomorrow** [comment]
![image](https://user-images.githubusercontent.com/40135607/77300281-bd48b680-6d28-11ea-94d2-0175301c8423.png)

**Comment by LookForwordTomorrow** [comment]
![image](https://user-images.githubusercontent.com/40135607/77300317-cc2f6900-6d28-11ea-8717-479915a924bd.png)

**Comment by LookForwordTomorrow** [comment]
按照官方文档，在react安装依赖包可以完美呈现，但是直接引用js会无效

**Comment by Yanyan-Wang** [comment]
https://codepen.io/Yanyan-Wang/pen/VwLGEbK
对照一下看有什么不同，是不是 cdn 地址或 G6 版本错了，这种动画的写法是 3.3 后支持的
https://gw.alipayobjects.com/os/antv/pkg/_antv.g6-3.4.2/dist/g6.min.js
