### ISSUE TITLE
初始化使用svg移动Group问题

### ISSUE THREAD

**Issue by qiuliang1** [antvis/G6#1340]
- **G6 Version**: 3.4.2
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by qiuliang1** [comment]
移动Group后，位置并没有fang放置在鼠标指定位置

G6 Version:3.4.2
Mini Showcase(like screenshots):
![image](https://user-images.githubusercontent.com/35951262/77385832-4234de00-6dc4-11ea-9b38-ee15e9b6e952.png)

**Comment by Yanyan-Wang** [comment]
目前节点分组的机制是一个临时的方案，存在很多问题。节点分组的问题都会在下个月的新版本中解决，我们正在重新设计和实现节点分组的新机制。

**Comment by Yanyan-Wang** [comment]
带有全新节点分组 Combo 机制的 v3.5 发布了。demos：
内置 combos: https://g6.antv.vision/zh/examples/item/defaultCombos
自定义 combos: https://g6.antv.vision/zh/examples/item/customCombo
Combo 的布局: https://g6.antv.vision/zh/examples/net/comboForce
Combo 的交互: https://g6.antv.vision/zh/examples/interaction/combo

文档可以通过 [G6 官网](https://g6.antv.vision/zh) 上方的搜索栏搜索“combo”查看。
