### ISSUE TITLE
使用TreeGraph时，默认一些子节点collapsed为false，当点击父节点的时候展示，怎么通过配置将页面再次适配，现在展开还是按之前比例，有些子节点显示不全

### ISSUE THREAD

**Issue by LookForwordTomorrow** [antvis/G6#1341]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
展开之后调用一下 fitView

**Comment by LookForwordTomorrow** [comment]
顺便再问一下
![image](https://user-images.githubusercontent.com/40135607/77404963-753f9780-6ded-11ea-9d59-1285ce4d6b37.png)
这个node-label是一个具体的值吗？我想当hover的时候设置一下当前节点的字体颜色，应该怎么设置

**Comment by LookForwordTomorrow** [comment]
![image](https://user-images.githubusercontent.com/40135607/77405114-addf7100-6ded-11ea-8b86-abb10441d708.png)

**Comment by Yanyan-Wang** [comment]
node-label 是节点内子图形的 name，'node-label' 是内置的 modelRect 的 label 图形的 name，'text-shape' 是其他内置节点的 label 的 name。如果是自定义节点就是在 addShape 的时候指定 name。

这里文档写法有点问题，想要设置 hover 状态的 node-label 的样式：
hover: {
    // ... keyShape 该状态下的样式
   // name 为 node-label 的图形该状态下的样式
    'node-label': {
      fill:'#f00'
    },
  },

**Comment by LookForwordTomorrow** [comment]
![image](https://user-images.githubusercontent.com/40135607/77410858-8d67e480-6df6-11ea-8b02-3aad2bfcdf47.png)

**Comment by LookForwordTomorrow** [comment]
![image](https://user-images.githubusercontent.com/40135607/77410904-9ce72d80-6df6-11ea-94ec-1b1c30b26fcb.png)
是这样吗，但是代码无效
