### ISSUE TITLE
v3.4.0 未导出shape对象

### ISSUE THREAD

**Issue by MYSUMMERLORD** [antvis/G6#1343]
在最新版本中，G6未导出shape对象，是放到其他什么地方导出，还是给去掉了呢，麻烦大佬解惑

**Comment by Yanyan-Wang** [comment]
导出 shape 对象是什么意思？你是怎么调用的？

**Comment by MYSUMMERLORD** [comment]
v3.4.0
![image](https://user-images.githubusercontent.com/9947530/77432126-9f5a7f00-6e18-11ea-8837-8653fefc63aa.png)
v3.1.3
![image](https://user-images.githubusercontent.com/9947530/77432334-e0eb2a00-6e18-11ea-881f-468f549ab370.png)

之前的项目代码中有用到shape，代码如下所示
![image](https://user-images.githubusercontent.com/9947530/77432515-214aa800-6e19-11ea-9e51-1c6adde47cd6.png)

现在升级到3.4.0之后，貌似没有暴露出shape对象了

**Comment by MYSUMMERLORD** [comment]
> 导出 shape 对象是什么意思？你是怎么调用的？

导出shape对象是说，G6在v3.4.0版本没有Shape这个属性。
在之前的版本上，我是这样调用的
`G6.Shape.registerFactory('anchor', {
    defaultShapeType: 'marker'
  });
  G6.Shape.registerAnchor('single-anchor', G6.Util.mix({}, SingleShapeMixin, {}))
   `

麻烦大佬给解惑，是处于某些考虑把Shape属性去掉了？还是其他什么原因呢

**Comment by Yanyan-Wang** [comment]
G6 的定位现在是图可视化和分析场景，也支持一些轻编辑场景。一些重编辑场景就不是 G6 擅长的，转交给兄弟产品 AntV X6。

现在 G6 内部把 Shape 这种偏基础绘图层的东西包起来了，没有暴露出来给用户使用。要使用 Anchor 的画也是直接作为节点的一部分：
https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/circle/#linkpoints
https://g6.antv.vision/zh/docs/manual/middle/elements/anchorpoint

**Comment by woleicom** [comment]
希望官网能提供下3.1.3版本的文档，x6现在还不完善，导致之前的项目都没有文档可以查看维护
