### ISSUE TITLE
求助关于线和自定义节点没有完美连接上

### ISSUE THREAD

**Issue by Liuqing650** [antvis/G6#1345]
- **G6 Version**: 3.4.0
- **Platform**: ubuntu 16.04
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

hi, 我在使用G6的过程中遇到一个小问题，就是自定义了一个平行四边形，但边似乎只能接触到 Bbox区域，导致没能在样式上直接和图形连接起来，看起来缺乏体验感，能否提供一个解决方案呢？不胜感激。

![flow](https://liuqing650.github.io/view/imgs/flow.png)

图片可能预览不到，点击此链接应该可见
[https://liuqing650.github.io/view/imgs/flow.png](https://liuqing650.github.io/view/imgs/flow.png)

**Comment by Yanyan-Wang** [comment]
节点的 anchorPoints 的 x 和 y 方向都可以任意值。可以类似这样设置
```javascript
anchorPoints: [
        [0.2, 0.5],
        [0.8, 0.5],
      ],
```

https://g6.antv.vision/zh/docs/manual/middle/elements/anchorpoint
