### ISSUE TITLE
建议：Tooltip允许修改OFFSET的值，同时可以优化下节点在界面右下角时的体验

### ISSUE THREAD

**Issue by smallp** [antvis/G6#1347]
当节点在界面右下角时，Tooltip信息框右下角几乎与鼠标重叠，点击时容易点到信息框而非节点上去。建议将`const OFFSET = 12;`改成可以配置的，同时`x -= (bbox.width);`改成`x -= (bbox.width)-OFFSET;`，这样体验会好些。
如果可以的话，这边可以提供PR。

**Comment by Yanyan-Wang** [comment]
感谢，欢迎 pr～
