### ISSUE TITLE
树形图拖动问题，空白区域可以拖动，节点文字无法拖动

### ISSUE THREAD

**Issue by masoncat** [antvis/G6#1348]
可以参考官网示例： https://g6.antv.vision/zh/examples/tree/compactBox

预期是，画布内任何地方，都可以响应拖动。

**Comment by Yanyan-Wang** [comment]
文本属于节点的一部分，只有拖动的 target 是画布的时候才能拖动画布。因为如果配置了 drag-node，在节点上拖动就需要响应到拖动节点。

**Comment by masoncat** [comment]
> 文本属于节点的一部分，只有拖动的 target 是画布的时候才能拖动画布。因为如果配置了 drag-node，在节点上拖动就需要响应到拖动节点。

这个可以禁止掉么？因为画布中大部分是节点上的文字，无法拖动的情况比较多。。。
我没有拖拽节点的需求，希望类似冒泡的形式，触发canvas的拖动事件

**Comment by Yanyan-Wang** [comment]
那目前只能用户用比较 hack 的方法来做：

```javascript
graph.getNodes().forEach(node => {
  const group = node.get('group');
  group.get('children').forEach( shape => {
    shape.set('capture', false);
  })
});
```

**Comment by masoncat** [comment]
但是点击事件也没有了。。

**Comment by Yanyan-Wang** [comment]
这样的话，以目前的机制应该就比较麻烦了，可能需要自定义 behavior。一个折衷的方法，只把文本 shape 的 capture 设置成 false。

v4.0 预计今年下半年发布，到时候会有一个 feature 是交互语法，到时候的交互会更自由，这些比较绕的交互就都能 handle 了。
