### ISSUE TITLE
Bezier 性质解释和应用

### ISSUE THREAD

**Issue by TomHuangCN** [antvis/g6#135]
### 端点性质

![image](https://user-images.githubusercontent.com/6113694/34414743-e99ea0ae-ec25-11e7-8d57-b39346040856.png)

> 释义：意味着第一个控制点和最后一个控制点，恰好是曲线的起始点和终点。

### 一阶导数

![image](https://user-images.githubusercontent.com/6113694/34415046-7c19b594-ec27-11e7-9577-24fa8d0ecff1.png)

> 释义：意味着第一个控制点和第二个控制点所在连线是第一个控制点所在的曲线切线；意味着最后一个控制点和倒数第二个控制点所在连线是最后一个控制点所在的曲线切线。

> 意义：无需求导运算便可得到首尾两个端点的切线

> 应用：画箭头

![image](https://user-images.githubusercontent.com/6113694/34415231-77c7f8ec-ec28-11e7-833f-4eee19823a7c.png)

### 对称性

![image](https://user-images.githubusercontent.com/6113694/34415294-cca66c2c-ec28-11e7-9083-7e66ea6a5b67.png)

> 释义：可以证明，假如保持n次Bezier曲线控制多边形的顶点位置
不变，而把次序颠倒过来，则此时曲线仍不变，只不过曲线
的走向相反而已（这个之前分享时讲错了，）

### 分割性

![image](https://user-images.githubusercontent.com/6113694/34415855-ca7fda48-ec2b-11e7-915f-00a6dae0deed.png)

> 释义：非常奇妙的性质，在对一个贝塞尔曲线的包多边形进行等比划分，并连线后发现，图中A、F、I和E是曲线AE的三阶贝塞尔曲线的控制点；E、J、H和D是曲线ED的三阶贝塞尔曲线的控制点。而且曲线长度也被等比划分！

> 应用：Path 动画中贝塞尔曲线数量对齐。（做统一的 path 动画再图形线转曲线过后，要将前后两段曲线需要用相等数量的贝塞尔曲线表示，才可继续做插值。）

[贝塞尔曲线详解&&工具包](http://pomax.github.io/bezierjs/)

**Comment by Narip2** [comment]
对称性的走向是指什么啊

**Comment by bluce** [comment]
五阶贝塞尔曲线，怎么绘制？
