### ISSUE TITLE
使用cdn源码的方式加载源码，ie中会报错，有没有支持ie中加载的源码（里面没有es6语法的）

### ISSUE THREAD

**Issue by LookForwordTomorrow** [antvis/G6#1353]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by LookForwordTomorrow** [comment]
或者有没有在ie中展示的解决方案

**Comment by Yanyan-Wang** [comment]
这个可以解决吗：https://g6.antv.vision/zh/docs/manual/FAQ/supportIE

**Comment by Yanyan-Wang** [comment]
你好，由于长时间没有回复所以先关闭这个 PR 了。
