### ISSUE TITLE
使用changeData渲染后，节点会自动会自动变小

### ISSUE THREAD

**Issue by a88053443** [antvis/G6#1355]
- **G6 Version**: 3.4.2
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**: https://codesandbox.io/s/flamboyant-smoke-qhcob

使用changeData渲染后，节点会自动变小，期望节点形状无变化

**Comment by Yanyan-Wang** [comment]
可以把自定义节点最后一个参数 'circle' 去掉。写了第三个参数为 'circle' 代表是要继承内置的 circle 类.因为你没复写 update 函数，所以在更新的时候会去调用父类 circle 的 update 函数，按照父类的规则去更新。但实际上你想按照你复写的 draw 方法去更新。
