### ISSUE TITLE
最新版本的G6的流程图endArrow样式有bug

### ISSUE THREAD

**Issue by harry0071** [antvis/G6#1356]
[codesandbox在线预览](https://codesandbox.io/s/intelligent-sky-8ejk5?fontsize=14&hidenavigation=1&theme=dark)

当G6是最新版本(3.4.3)时，endArrow无法正常渲染，如下图所示
![20200326170416.jpg](https://i.loli.net/2020/03/26/veI1DGMm6AaJkFj.jpg)

手动将G6版本号切换到3.3.7，endArrow就能正常显示了
![20200326170553.jpg](https://i.loli.net/2020/03/26/oMxrhX4iPn9H3Q8.jpg)

**Comment by Yanyan-Wang** [comment]
新版本的自定义箭头相对坐标系有变化，看下这个文档：
https://g6.antv.vision/zh/docs/manual/advanced/custom-edge/#4-%E8%87%AA%E5%AE%9A%E4%B9%89%E7%AE%AD%E5%A4%B4
