### ISSUE TITLE
edgeStateStyles change data bug

### ISSUE THREAD

**Issue by luckyyyyy** [antvis/G6#1357]
- **G6 Version**: 3.4.4
- **Platform**:macOS

因为自动刷新会changedata，然后线的状态无法复原了。

```js
      edgeStateStyles: {
        active: {
          stroke: '#000',
          opacity: 1,
        },
        inactive: {
          color: '#969696',
          opacity: 0.1,
        },
      },
```

**Comment by Yanyan-Wang** [comment]
graph.setItemState(item, 'active', false) 这样也不能复原了吗

**Comment by luckyyyyy** [comment]
> graph.setItemState(item, 'active', false) 这样也不能复原了吗

稍等中午搞个示例 有点忙最近 还没时间全看

**Comment by luckyyyyy** [comment]
> graph.setItemState(item, 'active', false) 这样也不能复原了吗

不好意思晚了些

https://codesandbox.io/s/g6-demo-bbvu2

**Comment by Yanyan-Wang** [comment]
确实有问题，并且发现在这里 graph.clearItemStates 或 graph.setItemState 会报错。 
尽快修复。

**Comment by Yanyan-Wang** [comment]
Fixed by v3.4.5.
