### ISSUE TITLE
Error in groupStyle when using Typescript

### ISSUE THREAD

**Issue by laubonghaudoi** [antvis/G6#1358]
- **G6 Version**: latest
- **Platform**: Windows
- **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/11172180/77706287-30e40100-6f7f-11ea-9120-4cc2073738b9.png)

- **CodePen Link**: https://codesandbox.io/s/ngyos

I tried to replicate the official demo of [customizing `groupStyle`](https://g6.antv.vision/en/docs/manual/advanced/create-node-group#groupstyle) in Typescript. But whenever I add this `groupStyle` object
```typescript
  groupStyle: {
    default: {},
    hover: {},
    collapse: {},
  },
```
I got the above error. I have tested that this issue only exists in Typescript. When I switched back to javascript, the error disappears.

Also, if I pass an empty object of `groupStyle` like below, the error was gone too:
```typescript
  groupStyle: {}
```

By the way, typescript support for G6 doesn't seem very good now. I hope there is a Typescript version for all example codes and demos, like the Ant Design docs.

**Comment by baizn** [comment]
please upgrade g6 version to 3.4.4 https://github.com/antvis/G6/pull/1365
