### ISSUE TITLE
拖动节点有Bug，使用微信截图（CTRL+A）后无法拖动

### ISSUE THREAD

**Issue by hujinbo** [antvis/G6#1359]
问题描述：开启drag-canvas拖动画布的情况下，画布能正常拖动，但如果使用微信截图工具（快捷键CTRL+A）对页面进行截图后，就无法再次拖动画布。

- **G6 Version**: 3.4.2
- **Platform**:
- **Mini Showcase(like screenshots)**:  ![问题3](https://user-images.githubusercontent.com/29507557/77710729-c5934100-7009-11ea-88ee-158d782d6eed.gif)

- **CodePen Link**: https://codesandbox.io/s/cranky-pond-dthio

**Comment by Yanyan-Wang** [comment]
请问你的操作系统是？

**Comment by hujinbo** [comment]
Windows 10 专业版

**Comment by Yanyan-Wang** [comment]
那你的浏览器是？我用 mac + chrome 使用钉钉的 Ctrl+A 没有复现出来，没有 windows 电脑以及不让装微信，暂时无法测试是不是因为微信或者 windows 的原因。。

之前有过一个类似问题：windows alt+tab 切换到浏览器其他标签，回来以后就不能拖动画布了，这是因为交互里面有检测键盘 keydown 来判断事件是否开始，如果切换到别的页面可能会导致没有正常的 keyup。但是这个 3.4.1 已经修复了。你试一下你那里使用 alt+tab 切换标签是否也会触发这个问题呢？

**Comment by hujinbo** [comment]
> 那你的浏览器是？我用 mac + chrome 使用钉钉的 Ctrl+A 没有复现出来，没有 windows 电脑以及不让装微信，暂时无法测试是不是因为微信或者 windows 的原因。。
> 
> 之前有过一个类似问题：windows alt+tab 切换到浏览器其他标签，回来以后就不能拖动画布了，这是因为交互里面有检测键盘 keydown 来判断事件是否开始，如果切换到别的页面可能会导致没有正常的 keyup。但是这个 3.4.1 已经修复了。你试一下你那里使用 alt+tab 切换标签是否也会触发这个问题呢？

我用的是chrome，我这边试了，我这边版本3.4.2 alt+tab也会有这个问题，但是不是切换到每个应用都会，比如切换好idea然后再切换回去，还是能拖拽。但如果切换到钉钉，再切换回去就不能拖拽了。

**Comment by hujinbo** [comment]
刚试了下在windows + chrome 将钉钉截图修改为的 Ctrl+A 也不会出现无法拖动的情况，但是微信会存在这种情况。

**Comment by hujinbo** [comment]
@Yanyan-Wang 3.4.7仍存在这个问题，windows alt+tab 切换到钉钉应用，聊天框输入文字后，返回g6画布无法拖动。
https://codesandbox.io/s/cranky-pond-dthio
![拖拽问题](https://user-images.githubusercontent.com/29507557/79830908-faac6c80-83d8-11ea-9a26-847aeea752b0.gif)

**Comment by Hugo-seth** [comment]
我刚刚也发现了这个问题，切换应用后返回无法拖动画布

**Comment by Yanyan-Wang** [comment]
v3.4.8 已修复
