### ISSUE TITLE
minimap插件展示数据不全

### ISSUE THREAD

**Issue by masoncat** [antvis/G6#1360]
- **G6 Version**: latest
- **Platform**: 
- **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/30170642/77714354-c6c96b80-7013-11ea-87ef-8df77770c262.png)

- **CodePen Link**: https://codesandbox.io/s/hardcore-antonelli-k1wno?fontsize=14&hidenavigation=1&theme=dark

**Comment by Yanyan-Wang** [comment]
你的意思是这个图片上 minimap 的蓝线框中内容与当前图上的可见视图不对应吗？在 demo 链接中如何操作出现呢，刚刚拖动了一下似乎没有复现。

**Comment by masoncat** [comment]
我通过拖动minimap的蓝线框，无法看到所有的数据。
预期是在minimap中来回滚动，就可以看到所有的，而不需要再拖动当前视图。

**Comment by Yanyan-Wang** [comment]
我在你这个 demo 中是可以的呀。是不是因为控制台或者左边的代码部分使得右边的画面空间不够。

**Comment by masoncat** [comment]
![image](https://user-images.githubusercontent.com/30170642/77737787-a1efeb00-7049-11ea-9859-621c95800977.png)

你看，这部分再往上，是看不到的（除非拖动一下主视图）。
我在应用中，还会不断的异步加载数据，然后minimap没办法显示所有的数据了。。

**Comment by Yanyan-Wang** [comment]
这个是通过什么样的操作出现的呢

**Comment by masoncat** [comment]
进入demo，然后拖动缩略框到上方，没有多余操作。
![image](https://user-images.githubusercontent.com/30170642/77814757-19c42100-70ef-11ea-9fb3-cc254fb506e5.png)

**Comment by Yanyan-Wang** [comment]
Fixed by 3.4.5.
