### ISSUE TITLE
3.4.0版本之后边的defaultEdge中endArrow配置fill无效

### ISSUE THREAD

**Issue by QDMarkMan** [antvis/G6#1361]
- **G6 Version**: 3.4.X
- **Platform**: Windows
- **Mini Showcase(like screenshots)**:
- **CodePen Link**: [https://codesandbox.io/s/g6-demo-ztvcx](https://codesandbox.io/s/g6-demo-ztvcx)

3.4.X

```js
defaultEdge: {
    size: 1,
    color: "#e2e2e2",
    style: {
      endArrow: {
        path: "M 0,0 L 8,4 L 8,-4 Z",
        fill: "red"
      }
    }
  }
```

**Comment by Yanyan-Wang** [comment]
3.4.2 是好的，3.4.3 有问题，下个小版本修复

**Comment by Yanyan-Wang** [comment]
v3.4.4 已修复。
