### ISSUE TITLE
缩小图时grid同时缩小

### ISSUE THREAD

**Issue by QDMarkMan** [antvis/G6#1362]
- **G6 Version**:  3.4.x
- **Platform**: Windows
- **Mini Showcase(like screenshots)**:  
![image](https://user-images.githubusercontent.com/18100675/77729090-cdb6a500-7038-11ea-93b9-9dc917ad9cf2.png)

- **CodePen Link**: [https://codesandbox.io/s/g6-demo-ztvcx](https://codesandbox.io/s/g6-demo-ztvcx)

**Comment by Yanyan-Wang** [comment]
你说的是 grid 吗？

**Comment by QDMarkMan** [comment]
> 你说的是 grid 吗？

嗯嗯是的 写错了

**Comment by QDMarkMan** [comment]
Gird插件还有另外一个问题就是频繁调用修改容器宽度并调用changeSize之后, 有很大几率会出宽度和图不一致的情况。
![image](https://user-images.githubusercontent.com/18100675/77735536-b631e900-7045-11ea-81bb-7815a0b9c05f.png)

**Comment by Yanyan-Wang** [comment]
这个问题下个小版本会修复

**Comment by Yanyan-Wang** [comment]
v3.4.4 已修复。
