### ISSUE TITLE
3.4.2版本 group不支持fitview配置，初始化时还是会撑到画布外面去

### ISSUE THREAD

**Issue by zaki1991** [antvis/G6#1364]
- **G6 Version**:3.4.2
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
目前节点分组的机制是一个临时的方案，存在很多问题。节点分组的问题都会在下个月的新版本中解决，我们正在重新设计和实现节点分组的新机制。

**Comment by JyotsnaC** [comment]
Can you please let us know the 3.5 release date?

**Comment by Yanyan-Wang** [comment]
v3.5 is released. Try it here:
Built-in combos: https://g6.antv.vision/en/examples/item/defaultCombos
Custom combos: https://g6.antv.vision/en/examples/item/customCombo
Combo with layout: https://g6.antv.vision/en/examples/net/comboForce
Combo behaviors: https://g6.antv.vision/en/examples/interaction/combo

For the docs, you can search 'combo' with the search bar on the top of [our website](https://g6.antv.vision/en).
