### ISSUE TITLE
G6树图，state状态丢失

### ISSUE THREAD

**Issue by CoderPXin** [antvis/G6#1367]
- **G6 Version**: 3.4.3
- **Platform**: window chrome
- **Mini Showcase(like screenshots)**:
- **CodePen Link**: https://codesandbox.io/s/l3009

1. 先折叠子节点，然后折叠子node的父节点
2. 展开父节点，子节点上的state样式消失。

**Comment by Yanyan-Wang** [comment]
目前树图收起和展开的机制是：收起时删掉子节点的 item，展开时再加上。所以收起再展开会重新创建子节点，原来的 state 就不存在了。

想要实现上面的效果，可以这样：
```javascript
graph.on('afterlayout', () => {
  graph.getNodes().forEach( node => {
    graph.setItemStates(node, 'expanded', node.getModel().collapsed);
  });
});
```

因为 collapse-expand 每次会在增删节点之后调用 layout，所以上面代码就是在布局之后重新设置一下所有节点的 expanded 状态。

**Comment by Yanyan-Wang** [comment]
感谢，这是一个很好的问题，我们回头会加到官网 FAQ 中

**Comment by CoderPXin** [comment]
@Yanyan-Wang 好的，感谢解答
