### ISSUE TITLE
求问如何画一个扇形或者一个任意角度的圆弧？

### ISSUE THREAD

**Issue by zhoustudent** [antvis/G6#1368]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

G6 Version: 3.4.2
Platform: mac
Mini Showcase(like screenshots): 暂无
CodePen Link:
group.addShape('arc', {
        attrs: {
          x: 0,
          y: 0,
          r: (size[0] + 4) / 2,
          startAngle: -Math.PI * (1 / 2),
          endAngle: -Math.PI * (1 / 2) + (+cfg.baseData.cpu_full_cores / 10) * 2 * Math.PI,
          clockwise: false,
          stroke: 'red',
          cursor: 'pointer',
          lineWidth: 3,
        },
      });

**Comment by Yanyan-Wang** [comment]
arc 图形在 3.3 之后被取消了，可以用 path 绘制，规则和 svg path一样：https://developer.mozilla.org/zh-CN/docs/Web/SVG/Tutorial/Paths

可以参考：https://g6.antv.vision/zh/examples/shape/customNode#pieChart
