### ISSUE TITLE
ant design pro配合使用时报_g2.default.Net is not a constructor的错误

### ISSUE THREAD

**Issue by gsgsdtc** [antvis/g6#137]
在使用ant design pro时，使用了G6，但是一直一下的错误。
index.js?f7ab:24 Uncaught TypeError: _g2.default.Net is not a constructor

`import g6 from '@antv/g6';
import React, { PureComponent } from 'react';

import styles from './index.less';

let uniqueId = 0;
function generateUniqueId() {
  return `rc-g6-${uniqueId++}`;
}

class FlowEditor extends PureComponent {
  constructor(props, context) {
    super(props, context);
    this.graph = null;
    this.graphId = generateUniqueId();
  }

  componentDidMount() {
    this.initGraph();
    alert('hello world');
  }

  initGraph() {
    const graph = new g6.Net({
      id: this.graphId,
    });
    this.graph = graph;
    this.graph.render();
    this.graph.autoZoom();
  }

  render() {
    return (<div className={styles.component} id={this.graphId} />);
  }
}

export default FlowEditor;`

**Comment by gsgsdtc** [comment]
不使用npm，直接引入文件可以使用，只是不知道问什么。刚开始使用nodeJS，可能不是太熟悉

**Comment by mutouzdl** [comment]
请问你解决了吗？我也遇到这个问题

**Comment by linlinNB** [comment]
大佬，我也遇到了这个问题，请问你解决了吗？

**Comment by mutouzdl** [comment]
@linlinNB 
我解决了，是版本问题，npm下载的是2.0版本，g6没有Net对象。
把webpack里的g6版本改回1.2.0，再npm install一下就好了。

**Comment by linlinNB** [comment]
@mutouzdl 谢谢，大佬，问题已经解决了。真的是太谢谢了
