### ISSUE TITLE
G6源码跑起来会error formatting block { SyntaxError: Unexpected token, expected "," (3:9)

### ISSUE THREAD

**Issue by crystalwm** [antvis/G6#1372]
- **G6 Version**:  3.4.4
- **Platform**: Linux
- **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/7902025/78004790-2fdf1500-736d-11ea-9a3b-ebc2da16b8e6.png)

- **CodePen Link**:

我是用npm安装的package，然后npm run start
源码跑起来会报错

需要什么设置吗？

**Comment by Yanyan-Wang** [comment]
你是用了 master 上的源码吗？npm run start 是启动官网。你是需要做什么？

**Comment by crystalwm** [comment]
> 你是用了 master 上的源码吗？npm run start 是启动官网。你是需要做什么？

对的master的源码，看到代码里面有react 和 G6一起使用，想跑一下代码看看效果

**Comment by Yanyan-Wang** [comment]
npm run start 是启动官网，要使用这个需要用 yarn 安装一下。
想看 react + G6 可以看这个：
https://g6.antv.vision/zh/docs/manual/middle/g6InReact
https://g6.antv.vision/zh/docs/manual/introduction/#%E5%8F%8B%E6%83%85%E9%93%BE%E6%8E%A5
