### ISSUE TITLE
数据源的 nodes 节点中配置 labelCfg-> style ，页面运行异常

### ISSUE THREAD

**Issue by linkai0001** [antvis/G6#1374]
![311078006ebb7ffc931485a7efaef68](https://user-images.githubusercontent.com/24260681/78016840-f1058b00-737d-11ea-919a-8aabe6c0408a.png)

代码片段：
 
![912c2e5d33d11b4619265094d57bfc7](https://user-images.githubusercontent.com/24260681/78017314-a6384300-737e-11ea-906c-834f4c84a10d.png)

如上使用了 labelCfg 配置节点文本样式, 对象中使用 style , 页面将运行异常! 
这个问题在 3.4.0 之前的版本不会出现, 在 3.4.0后续版本 包括 3.4.0 的版本都会有问题

**Comment by Yanyan-Wang** [comment]
能否写一个在线 demo，我在官网 demo 中没能复现出来
![image](https://user-images.githubusercontent.com/29593318/78093072-fc02fe80-7403-11ea-9c65-1d7e064459fa.png)

**Comment by linkai0001** [comment]
> 能否写一个在线 demo，我在官网 demo 中没能复现出来
> ![image](https://user-images.githubusercontent.com/29593318/78093072-fc02fe80-7403-11ea-9c65-1d7e064459fa.png)

hello 
问题代码已提交至 https://github.com/linkai0001/g6-demo01 ，
通过  cnpm install,  npm start 安装启动
![d76684f6a4cc35d5b88001e0692a0cc](https://user-images.githubusercontent.com/24260681/78097615-50f84200-740f-11ea-874f-5e9283b7cba4.png)

**Comment by Yanyan-Wang** [comment]
svg 渲染下 fontSize 小于 12 会报错，这个问题已知，是底层渲染引擎有些问题，正在排查修复中。
合并到 https://github.com/antvis/g/issues/453

**Comment by linkai0001** [comment]
好的，感谢

**Comment by zhoustudent** [comment]
哈喽，想问下，我在节点的labelCfg中设置offset，但无效，这个可以解决么，我的也是3.4.0版本

**Comment by Yanyan-Wang** [comment]
> 哈喽，想问下，我在节点的labelCfg中设置offset，但无效，这个可以解决么，我的也是3.4.0版本

position 是什么？offset 对于 position 是 center 的情况下是不生效的
