### ISSUE TITLE
如何阻止特定节点（边）被删除

### ISSUE THREAD

**Issue by BernardZhang** [antvis/G6#1376]
版本 3.2

设置了快捷键删除【delete】,但是针对特殊节点想阻止删除动作，是否有方法可以阻止删除。
文档上找到了 beforeremoveitem 事件回调，但是没有发现有类似evt.preventDefault 或return false 的方式来阻止删除行为。

期望：设置了delete 删除快捷键，需要能支持特定情况下可以阻止删除动作。

**Comment by Yanyan-Wang** [comment]
delete 是调用了 graph.removeItem 吗，调用之前判断一下 item 是不是不能删除不就可以了么？
