### ISSUE TITLE
节点与边的层级问题

### ISSUE THREAD

**Issue by linkai0001** [antvis/G6#1377]
问题：
当我配置好鼠标移动至边线时，让边线展示在最上层，实际并未发生，边线依然在最下层

问题截图：
![38d15ab42c8300c6c189afcca2f3d8e](https://user-images.githubusercontent.com/24260681/78028155-236cb380-7391-11ea-8c1a-ce5314f26f8e.png)

关键代码
![image](https://user-images.githubusercontent.com/24260681/78028010-e7d1e980-7390-11ea-81e4-0633beb83e16.png)
`graph.on('edge:mouseenter', ev => {

            debugger
            // 获得鼠标当前目标边
            const edge = ev.item;
            // 该边的起始点
            const source = edge.getSource();
            // 该边的结束点
            const target = edge.getTarget();
            // 先将边提前，再将端点提前。这样该边两个端点还是在该边上层，较符合常规。
            edge.toFront();
            source.toFront();
            target.toFront();
            // 注意：必须调用以根据新的层级顺序重绘
            graph.paint();
        });`
完整代码：
`import React,{useEffect, useState} from 'react';
import G6 from '@antv/g6';

export default function () {

    // 通过 React.userRef 函数的 current 获取绑定 ref 的元素
    const ref = React.useRef();
    let data = {
        // 点集
        nodes: [{
            id: 'node1', // String，该节点存在则必须，节点的唯一标识
            x: 100,      // Number，可选，节点位置的 x 值
            y: 100,       // Number，可选，节点位置的 y 值
            label: "新增",
            class: "n0",
            // 设置节点的形状
            shape: "modelRect",
            // 节点中文本样式和其他配置
            labelCfg: {
                // 文本在元素中的位置
                positions: "center",
                /*style: {
                    fontSize: 10
                }*/
            }

        },{
            id: 'node2', // String，该节点存在则必须，节点的唯一标识
            x: 300,      // Number，可选，节点位置的 x 值
            y: 100,       // Number，可选，节点位置的 y 值
            label: "编辑",
            class: "n1",
            shape: "rect"
        }],
        // 边集
        edges: [{
            source: 'node1', // String，必须，起始点 id
            target: 'node2',  // String，必须，目标点 id
            label: "连接",
            class: "e0",
            shape: "cubic-horizontal",
            style: {
                lineWidth: 2,
                endArrow: true
            }
        }]
    };

    useEffect(() => {

        // 使用 defaultNode 和 defaultEdge 实现默认配置(全局配置)
        let graph = new G6.Graph({
            container: ref.current,
            width: 400,
            height: 400,
            renderer: "svg",
            // 节点不同状态下的样式集合
            nodeStateStyles: {
                // 鼠标移至上方时状态
                hover: {
                    cursor:"pointer"
                },
                // 鼠标单击时状态
                click: {
                    stroke: "green",
                    lineWidth: 3
                }
            },
            // 边线不同状态下的样式集合
            edgeStateStyles: {
                // 鼠标移至上方时状态
                hover: {
                    cursor:"crosshair"
                },
                // 鼠标单击时状态
                click: {
                    stroke: "green",
                    lineWidth: 3
                }
            },
            modes: {
                // 支持 拖拽，缩放 内置交互行为(画布和节点)
                default: [ 'drag-canvas', 'zoom-canvas', 'drag-node' ],  // 允许拖拽画布、放缩画布、拖拽节点
            },
            groupByTypes: false
        });
        graph.on("node:mouseenter", e=> {
            const nodeItem = e.item;
            graph.setItemState(nodeItem, 'hover', true);
        });
        graph.on("node:mouseleave", e=> {
            const nodeItem = e.item;
            graph.setItemState(nodeItem, 'hover', false);
        });
        graph.on("node:click", e=> {
            // 将所有当前是 click 状态的节点和边线设置为非 click
            const clickNodes = graph.findAllByState('node', 'click');
            clickNodes.forEach(cn => {
                graph.setItemState(cn, 'click', false);
            });
            const clickEdges = graph.findAllByState('edge', 'click');
            console.log("clickEdges", clickEdges);
            clickEdges.forEach(ce => {
                graph.setItemState(ce, 'click', false);
            });
            const nodeItem = e.item;  // 获取被点击的节点元素对象
            graph.setItemState(nodeItem, 'click', true); // 设置当前节点的 click 状态为 true
        });

        graph.on("edge:mouseenter", e=> {
            const nodeItem = e.item;
            graph.setItemState(nodeItem, 'hover', true);
        });
        graph.on("edge:mouseleave", e=> {
            const nodeItem = e.item;
            graph.setItemState(nodeItem, 'hover', false);
        });
        graph.on("edge:click", e=> {
            // 将所有当前是 click 状态的边线和节点设置为非 click
            const clickNodes = graph.findAllByState('node', 'click');
            clickNodes.forEach(cn => {
                graph.setItemState(cn, 'click', false);
            });
            const clickEdges = graph.findAllByState('edge', 'click');
            clickEdges.forEach(ce => {
                graph.setItemState(ce, 'click', false);
            });
            const nodeItem = e.item;  // 获取被点击的节点元素对象
            graph.setItemState(nodeItem, 'click', true); // 设置当前节点的 click 状态为 true
        });
        graph.data(data);
        graph.render();

        // 配置节点和边线的层级
        const nodes = graph.getNodes();
        nodes.forEach(node=> {
            // toFront 表示节点在前, 变现在后
            node.toFront();
        });
        graph.paint();

        // 鼠标进入节点事件
        graph.on('edge:mouseenter', ev => {

            debugger
            // 获得鼠标当前目标边
            const edge = ev.item;
            // 该边的起始点
            const source = edge.getSource();
            // 该边的结束点
            const target = edge.getTarget();
            // 先将边提前，再将端点提前。这样该边两个端点还是在该边上层，较符合常规。
            edge.toFront();
            source.toFront();
            target.toFront();
            // 注意：必须调用以根据新的层级顺序重绘
            graph.paint();
        });

        /*graph.on('edge:mouseleave', ev => {
            // 获得图上所有边实例
            const edges = graph.getEdges();
            // 遍历边，将所有边的层级放置在后方，以恢复原样
            edges.forEach(edge => {
                edge.toBack();
            });
            // 注意：必须调用以根据新的层级顺序重绘
            graph.paint();
        });*/

        /*graph.on('node:mouseenter', ev => {
            // 获得鼠标当前目标节点
            const node = ev.item;
            // 获取该节点的所有相关边
            const edges = node.getEdges();
            // 遍历相关边，将所有相关边提前，再将相关边的两个端点提前，以保证相关边的端点在边的上方常规效果
            edges.forEach(edge => {
                edge.toFront();
                edge.getSource().toFront();
                edge.getTarget().toFront();
            });
            // 注意：必须调用以根据新的层级顺序重绘
            graph.paint();
        });*/

        /*graph.on('node:mouseleave', ev => {
            // 获得图上所有边实例
            const edges = graph.getEdges();
            // 遍历边，将所有边的层级放置在后方，以恢复原样
            edges.forEach(edge => {
                edge.toBack();
            });
            // 注意：必须调用以根据新的层级顺序重绘
            graph.paint();
        });*/
    },[]);
    return (
        <React.Fragment>
            <div ref={ref}></div>
        </React.Fragment>
    )
}`

**Comment by Yanyan-Wang** [comment]
我看到你代码逻辑里面，mouseenter 的时候先把边 toFront，然后又把两个端点 toFront 了呀？
```javascript
// 先将边提前，再将端点提前。这样该边两个端点还是在该边上层，较符合常规。
        edge.toFront();
        source.toFront();
        target.toFront();
```

**Comment by linkai0001** [comment]
> 我看到你代码逻辑里面，mouseenter 的时候先把边 toFront，然后又把两个端点 toFront 了呀？
> 
> ```js
> // 先将边提前，再将端点提前。这样该边两个端点还是在该边上层，较符合常规。
>         edge.toFront();
>         source.toFront();
>         target.toFront();
> ```

是呀，就是默认情况下，在画布展示中，我会让 "节点" 的层级高于 "边线"， 当我鼠标移动至"边线"时，我要让边线的层级高于"节点"， 代码逻辑是这么写的

**Comment by linkai0001** [comment]
> 我看到你代码逻辑里面，mouseenter 的时候先把边 toFront，然后又把两个端点 toFront 了呀？
> 
> ```js
> // 先将边提前，再将端点提前。这样该边两个端点还是在该边上层，较符合常规。
>         edge.toFront();
>         source.toFront();
>         target.toFront();
> ```
hello ，刚调整了代码，依然还是未出现"边线"高于"节点"的效果
![02f3fa4ef550e09fbbafdebb7bdf698](https://user-images.githubusercontent.com/24260681/78096369-f3aec180-740b-11ea-97f6-0b79a66a3a1b.png)
![311cb179e05944d2ff0017795eb203a](https://user-images.githubusercontent.com/24260681/78096375-f6111b80-740b-11ea-960c-138f0d8435a2.png)
![0edcfd8d746a637641b7e1a997caf10](https://user-images.githubusercontent.com/24260681/78096438-22c53300-740c-11ea-8ce9-3e6c51a675e0.png)

`import React,{useEffect} from 'react';
import G6 from '@antv/g6';
import "../../assets/css/common/public.css";

export default function () {

    // 通过 React.userRef 函数的 current 获取绑定 ref 的元素
    const ref = React.useRef();
    let data = {
        // 点集
        nodes: [{
            id: 'node1', // String，该节点存在则必须，节点的唯一标识
            x: 100,      // Number，可选，节点位置的 x 值
            y: 100,       // Number，可选，节点位置的 y 值
            label: "新增",
            class: "n0",
            // 设置节点的形状
            type: "modelRect",
            style: {
                cursor: "pointer"
            },
            // 节点中文本样式和其他配置
            labelCfg: {
                // 文本在元素中的位置
                positions: "center",

            },
            // anchorPoint 配置，右上角 0 0 ， 左下角 1 1， 按比例向x,y 轴计算边线和节点交接点
            anchorPoints: [
                [0.5,1],
                [1,0.5],
                [0.5,0],
                [0,0.5]
            ]

        },{
            id: 'node2', // String，该节点存在则必须，节点的唯一标识
            x: 300,      // Number，可选，节点位置的 x 值
            y: 100,       // Number，可选，节点位置的 y 值
            label: "编辑",
            class: "n1",
            type: "rect",
            style: {
                cursor: "pointer"
            },
            anchorPoints: [
                [0.5,0],
                [1,0.5],
                [0.5,1],
                [0,0.5]
            ]
        }],
        // 边集
        edges: [{
            source: 'node1', // String，必须，起始点 id
            target: 'node2',  // String，必须，目标点 id
            label: "连接",
            class: "e0",
            type: "cubic-horizontal",
            strokeOpacity: 0.5,
            sourceAnchor: 1,
            targetAnchor: 1,
            style: {
                lineWidth: 2,
                endArrow: true,
                cursor: "crosshair"
            }
        }]
    };

    useEffect(() => {

        // 使用 defaultNode 和 defaultEdge 实现默认配置(全局配置)
        let graph = new G6.Graph({
            container: ref.current,
            width: 400,
            height: 400,
            renderer: "svg",
            groupByTypes: false,
            modes: {
                // 支持 拖拽，缩放 内置交互行为(画布和节点), click-select 用于节点的多选
                // tooltip 实现节点文本提示， edge-tooltip 实现了边线文本提示
                default: [ 'drag-canvas', 'zoom-canvas', 'drag-node','click-select',{
                    type: "tooltip",
                    formatText(model) {
                        return model.label;
                    }
                },{
                    type: "edge-tooltip",
                    formatText(model) {
                        return model.label;
                    }
                },"activate-relations"],
            }
        });

        graph.data(data);
        graph.render();

        // 配置节点和边线的层级(节点的"层级"高于"边线")
        const nodes = graph.getNodes();
        nodes.forEach(node=> {
            node.toFront();
        });
        graph.paint();

        // 配置鼠标进入边线时，"边线"层级高于"节点"
        graph.on('edge:mouseenter', ev => {
            const edge = ev.item;
            const source = edge.getSource();
            const target = edge.getTarget();
            source.toFront();
            target.toFront();
            edge.toFront();
            graph.paint();
        });

        // 配置鼠标离开边线时， "节点"层级高于"边线"
        /*graph.on('edge:mouseleave', ev => {
            const edges = graph.getEdges();
            edges.forEach(edge => {
                edge.toBack();
            });
            graph.paint();
        });*/

        // 配置鼠标进入节点时， "节点"层级高于"边线"
        /*graph.on('node:mouseenter', ev => {
            const node = ev.item;
            const edges = node.getEdges();
            edges.forEach(edge => {
                edge.toFront();
                edge.getSource().toFront();
                edge.getTarget().toFront();
            });
            graph.paint();
        });*/

        // 配置鼠标离开节点时，"节点"层级高于"边线"
        /*graph.on('node:mouseleave', ev => {
            const edges = graph.getEdges();
            edges.forEach(edge => {
                edge.toBack();
            });
            graph.paint();
        });*/
    },[]);
    return (
        <React.Fragment>
            <div ref={ref}></div>
        </React.Fragment>
    )
}`

**Comment by Yanyan-Wang** [comment]
svg 的 toFront 目前有问题，合并到 #1305

**Comment by Yanyan-Wang** [comment]
canvas 渲染应该没问题的

**Comment by linkai0001** [comment]
好的，感谢
