### ISSUE TITLE
Cannot use G6 with React

### ISSUE THREAD

**Issue by jshuadvd** [antvis/G6#1378]
- **G6 Version**:
`@antv/g6": "3.4.0", (Have tried @latest too)`
- **Platform**:
`OSX 10.15.3`
- **Mini Showcase(like screenshots)**:
```
yarn add @antv/g6
Open file to include
import G6 from "@antv/g6"
yarn start
```

Whenever I `import G6 from "@antv/G6"; ` and run `yarn start` I get the following error.

```
node_modules/@antv/g6/dist/g6.min.js:24:315787: Unexpected token, expected "," (24:315787)
  22 |  * Based on Underscore.js 1.8.3 <http://underscorejs.org/LICENSE>
  23 |  * Copyright Jeremy Ashkenas, DocumentCloud and Investigative Reporters & Editors
> 24 |  */(function(){var o="Expected a function",a="__lodash_placeholder__",u=[["ary",128],["bind",1],["bindKey",2],["curry",8],["curryRight",16],["flip",512],["partial",32],["partialRight",64],["rearg",256]],s="[object Arguments]",c="[object Array]",f="[object Boolean]",h="[object Date]",l="[object Error]",d="[object Function]",p="[object GeneratorFunction]",g="[object Map]",v="[object Number]",y="[object ...

```

`25 | //# sourceMappingURL=g6.min.js.map`

**Comment by baizn** [comment]
use G6 with react, please refer to [this demo](https://github.com/baizn/g6-in-react)

**Comment by jshuadvd** [comment]
Are you saying that we have to use umi in order to use this lib with React? The issue starts when I import the library before even creating a basic graph. Is there some sort of config file or guidance you can provide for babel or parcel?

**Comment by laubonghaudoi** [comment]
I am using pure react without umi and it works fine. Maybe you should look into that demo.

**Comment by baizn** [comment]
> @baizn hi :) Are you saying that we have to use umi in order to use this lib with React? The issue starts when I import the library before even creating a basic graph. Is there some sort of config file or guidance you can provide for babel or parcel?

umi is optional，we will provide a demo with webpack & babel.

**Comment by jshuadvd** [comment]
@baizn great! Any idea when that will  be?

**Comment by baizn** [comment]
@jshuadvd remove umi dependencies,   add webpack & babel dependencies  https://github.com/baizn/g6-in-react
