### ISSUE TITLE
G6支持节点（包含子节点）拖动放到另一个节点下吗

### ISSUE THREAD

**Issue by shiwuqi** [antvis/G6#1379]
- **G6 Version**:3.4.4
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
树图还是节点分组

**Comment by shiwuqi** [comment]
> 树图还是节点分组

树图

**Comment by Yanyan-Wang** [comment]
没有内置方法，需要自定义交互，比较复杂，自定义交互可以参考: https://g6.antv.vision/zh/docs/manual/advanced/custom-behavior
