### ISSUE TITLE
注册节点时添加text 的shape，如何进行旋转

### ISSUE THREAD

**Issue by zhoustudent** [antvis/G6#1380]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

G6 Version:3.4.3
Platform: mac
Mini Showcase(like screenshots): 无
CodePen Link: 无

**Comment by Yanyan-Wang** [comment]
需要使用矩阵进行旋转，参考 G6 中 edge 上的 text 旋转的逻辑：
https://github.com/antvis/G6/blob/484a9b310f7659bd7843e2e2b5d706f165271b8a/src/shape/edge.ts#L250
