### ISSUE TITLE
single-shape是G6 node内置的吗?为什么我没找到相关的介绍文档

### ISSUE THREAD

**Issue by laolaolulu** [antvis/G6#1384]
- **G6 Version**:3.2.10
- **Platform**:windows node
- **Mini Showcase(like screenshots)**:
![TIM截图20200402094058](https://user-images.githubusercontent.com/33310261/78203337-4bf7c900-74c9-11ea-8625-ae9c21f87458.png)

- **CodePen Link**:https://antv-g6.gitee.io/zh/examples/net/dagreFlow#basicDagre

请问这个deom中的'single-shape'是什么意思？我的理解G6.registerNode('sql'  是自定义名称为sql节点样式，而后面的single-shape是继承，而我在deom中也没见single-shape的定义；我看了G6自带的节点也没此内容

**Comment by Yanyan-Wang** [comment]
这个是所有内置节点的基类。可以不用了解。你也可以换成继承 rect 或者 circle 之类的内置节点。
