### ISSUE TITLE
canvas:mouseup 事件问题

### ISSUE THREAD

**Issue by linkai0001** [antvis/G6#1385]
canvas:mouseup 事件是一个特别重要的事件，他将实现"外部元素"拖拽至画布中在鼠标释放后触发，此时我将写入节点至画布中。经过验证，在 3.2.0 到 3.2.9 版本，或3.2.0 版本之前的版本，这个事件能触发。然后再 3.3.0 包括3.3.0 后续的版本就不会被触发。这个将使我无法实现想要的功能额。

**Comment by DeepVince** [comment]
请问您怎么解决的？我这边也出现了类似的问题，在自定义的behavior中canvas:mouseup事件无法监听到

**Comment by linkai0001** [comment]
我是实现拖拽， 鼠标进入画布时，触发进入事件，并在当前的上下文中设置一个标识。canvas:mouseup 鼠标在画布上释放，我试了没有效果， 后面改为  mouseup ,  也就意味着只要是画布，节点，边线鼠标释放都会进入， 为了区分标识就起到作用了额。

**Comment by DeepVince** [comment]
谢谢，用mouseup后解决了
