### ISSUE TITLE
请问G6布局方式有按容器比例来布局的吗？

### ISSUE THREAD

**Issue by laolaolulu** [antvis/G6#1386]
- **G6 Version**:3.2.10
- **Platform**:windows node
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

例如我有个 rect node,我想将节点的长宽设置为容器长宽的百分之10

**Comment by laolaolulu** [comment]
还有边的那个自定义动画效果很好，能内置进去吗？https://antv-g6.gitee.io/zh/examples/scatter/edge#edge

**Comment by Yanyan-Wang** [comment]
拿到你的容器大小，根据这个去设置节点的 size 就可以了呀。

动画的定制性比较强，对于通用的动画我们会考虑内置的。
