### ISSUE TITLE
The custom node can't be drag by mouse separated

### ISSUE THREAD

**Issue by NorthBei** [antvis/G6#1388]
- **G6 Version**: 3.4.4
- **Platform**: Mac Chrome / Safari
- **Mini Showcase(like screenshots)**:
![in](https://user-images.githubusercontent.com/15665709/78222263-824c3d00-74f7-11ea-8a3c-c0716ca21d8f.gif)

- **CodePen Link**: https://codesandbox.io/s/hgrny

I installed the G6 package with version 3.4.4
cause I want to use the custom node feature
I just try to copy/paste the code which I found in offical document and run
(offical document code: https://g6.antv.vision/en/examples/shape/customNode)
at result, the node can't be drag seperate, just can be drag together

I have found the old issue and document, and check the `draggable` attr was given as `true` in the `cfg` of `group.addShap`

BTW, the offical document  of addshapetype's cfg argument (https://g6.antv.vision/en/docs/api/Group/#addshapetype-cfgs)
doesn't provide the info about `draggable` attribute

How can I solve this problem ?
Thanks for ur help!

**Comment by Yanyan-Wang** [comment]
DOM elements do not support the built-in events of G6, pls use the original HTML DOM events instead.

Pls checkout this issue: https://github.com/antvis/G6/issues/1321

**Comment by Yanyan-Wang** [comment]
And thanks for reminding us to update the document about addShape cfg
