### ISSUE TITLE
单词错误，详情如下

### ISSUE THREAD

**Issue by leejay1992** [antvis/g6#139]
页面 ： https://antv.alipay.com/zh-cn/g6/1.x/demo/flow/saoma.html

<img width="945" alt="test" src="https://user-images.githubusercontent.com/15710933/34479395-76de87a4-efe1-11e7-95dd-601b57538e90.png">

**Comment by TomHuangCN** [comment]
兄弟，好眼神

**Comment by leejay1992** [comment]
因为我在把这些demo走一遍 然后再做开发😜

**Comment by TomHuangCN** [comment]
fixed
