### ISSUE TITLE
graph.data wont read data 

### ISSUE THREAD

**Issue by johnvehr** [antvis/G6#1391]
if I call and pass in an object like so

graph.data({id: 'whatver',children: []) 

It works the graph renders no problem 

when I call 

graph.data(returned_data_from_api) 

I get nothing graph will only show one node. Now if I copy that return value so literally is the same and then paste it in, it works....like the first example....its the most bizarre thing I have ever experienced and I am sure it is a stupid fix

**Comment by Yanyan-Wang** [comment]
Hi, is the API which returns the returned_data_from_api asynchronous?

**Comment by johnvehr** [comment]
> Hi, is the API which returns the returned_data_from_api asynchronous?
Yes

**Comment by johnvehr** [comment]
Solution for me is - one I needed to wait for my async data before calling new Graph and to the second problem I am just bringing back the newly created item from redux and using the graph add item if item does not currently exists

**Comment by xiaofengqqcom123** [comment]
version 3.7.1
can‘t get react state
