### ISSUE TITLE
自定义节点无法拖拽,其他原生节点拖拽没问题

### ISSUE THREAD

**Issue by Go-Way** [antvis/G6#1392]
const getNodeConfig = node => {
  const config = {
    basicColor: '#5B8FF9',
    fontColor: '#333333',
    borderColor: '#ffffff',
    bgColor: '#ffffff'
  }
  return config
}

const nodeBasicMethod = {
  createNodeBox: (group, config, width, height) => {
  /* 最外面的大矩形 */
    const container = group.addShape('rect', {
      attrs: {
        x: 0,
        y: 0,
        width,
        height
      }
    })
    /* 矩形 */
    group.addShape('rect', {
      attrs: {
        x: 3,
        y: 0,
        width,
        height,
        fill: config.bgColor,
        stroke: config.borderColor,
        radius: 2
      }
    })
    return container
  },
  /* 生成树上的 marker */
  createNodeMarker: (group, anchorPoints, x, y) => {
    if (anchorPoints) {
      anchorPoints.forEach((item, index) => {
        const offset = x + index * 58
        group.addShape('rect', {
          attrs: {
            x: offset,
            y,
            width: 42,
            height: 24,
            fill: '#E8F0FA',
            lineWidth: 1,
            cursor: 'pointer',
            fontColor: '#00A0F7'
          },
          className: 'collapse-icon'
        })
        group.addShape('text', {
          attrs: {
            x: offset + 8,
            y: y + 12,
            width: 42,
            height: 24,
            textAlign: 'left',
            textBaseline: 'middle',
            fill: '#00A0F7',
            cursor: 'pointer',
            text: item.name
          },
          className: 'collapse-icon'
        })
      })
    }
  }
}

G6.registerNode(
  'card-node',
  {
    drawShape: (cfg, group) => {
      const config = getNodeConfig(cfg)
      /* 最外面的大矩形 */
      const container = nodeBasicMethod.createNodeBox(
        group,
        config,
        248,
        138
      )
      /* name */
      group.addShape('text', {
        attrs: {
          text: cfg.name,
          x: 19,
          y: 19,
          fontSize: 14,
          fontWeight: 700,
          textAlign: 'left',
          textBaseline: 'middle',
          fill: config.fontColor,
          cursor: 'pointer'
        }
      // tooltip: cfg.name,
      })

      /* 下面的文字 */
      group.addShape('text', {
        attrs: {
          text: cfg.keyInfo,
          x: 19,
          y: 45,
          fontSize: 14,
          textAlign: 'left',
          textBaseline: 'middle',
          fill: config.fontColor,
          cursor: 'pointer'
        }
      })

      const hasChildren = cfg.children && cfg.children.length > 0
      if (hasChildren) {
        nodeBasicMethod.createNodeMarker(group, cfg.anchorPointsValue, 16, 98)
      }
      return container
    }
  }
)

 data: [{
      id: 'endNode',
      name: 'cardNodeApp',
      keyInfo: 'this is sub root',
      x: 600,
      y: 250,
      children: [
        {
          name: 'sub'
        }
      ],
      anchorPointsValue: [
        {
          name: '肯定',
          value: 'submit'
        },
        {
          name: '拒绝',
          value: 'submit'
        },
        {
          name: '否定',
          value: 'submit'
        },
        {
          name: '默认',
          value: 'submit'
        }
      ],
      shape: 'end-node'
    },
    {
      id: 'circle',
      label: 'Circle_2',
      x: 450,
      y: 350,
      anchorPoints: [
        [0.5, 1],
        [0, 0.5],
        [0.5, 0],
        [1, 0.5]
      ],
      shape: 'circle'
    }
  ],

**Comment by Yanyan-Wang** [comment]
自定义节点 addShape 时要加上 draggable: true 和 name 属性：https://g6.antv.vision/zh/docs/manual/FAQ/upgradeGuide/#%E5%A2%9E%E5%8A%A0%E5%9B%BE%E5%BD%A2

**Comment by Go-Way** [comment]
是的，感谢您的帮助


| |
西湖龙王
|
|
long871921962@163.com
|
签名由网易邮箱大师定制


在2020年04月3日 11:11，Yanyan Wang<notifications@github.com> 写道：

自定义节点 addShape 时要加上 draggable: true 和 name 属性：https://g6.antv.vision/zh/docs/manual/FAQ/upgradeGuide/#%E5%A2%9E%E5%8A%A0%E5%9B%BE%E5%BD%A2

**Comment by yitjhy** [comment]
`G6.registerNode('dom-node', {
            draw: (cfg, group) => {
                return group.addShape('dom', {
                    attrs: {
                        width: cfg.size[0],
                        height: cfg.size[1],
                        html: `
        <div onclick="alert('Hi')" style="background-color: #fff; border: 2px solid #5B8FF9; border-radius: 5px; width: ${cfg.size[0]-5}px; height: ${cfg.size[1]-5}px; display: flex;">
          <div style="height: 100%; width: 33%; background-color: #CDDDFD">
            <img alt="" style="line-height: 100%; padding-top: 6px; padding-left: 8px;" src="https://gw.alipayobjects.com/mdn/rms_f8c6a0/afts/img/A*Q_FQT6nwEC8AAAAAAAAAAABkARQnAQ" width="20" height="20" />
          </div>
          <span style="margin:auto; padding:auto; color: #5B8FF9">${cfg.label}</span>
        </div>
          `
                    },
                    draggable: true,
                    name: 'circle-shape'
                });
            },
        });`


我的加了为啥也没起作用

**Comment by yitjhy** [comment]
```javascript
G6.registerNode('dom-node', {
            draw: (cfg, group) => {
                return group.addShape('dom', {
                    attrs: {
                        width: cfg.size[0],
                        height: cfg.size[1],
                        // 传入 DOM 的 html，带有原生 onclick 事件
                        html: `
        <div onclick="alert('Hi')" style="background-color: #fff; border: 2px solid #5B8FF9; border-radius: 5px; width: ${cfg.size[0]-5}px; height: ${cfg.size[1]-5}px; display: flex;">
          <div style="height: 100%; width: 33%; background-color: #CDDDFD">
            <img alt="" style="line-height: 100%; padding-top: 6px; padding-left: 8px;" src="https://gw.alipayobjects.com/mdn/rms_f8c6a0/afts/img/A*Q_FQT6nwEC8AAAAAAAAAAABkARQnAQ" width="20" height="20" />
          </div>
          <span style="margin:auto; padding:auto; color: #5B8FF9">${cfg.label}</span>
        </div>
          `
                    },
                    draggable: true,
                    name: 'circle-shape'
                });
            },
        });




我的加了为啥没起作用。。。。求解啊，请问楼主解决了吗

**Comment by lzy110223** [comment]
我也是 自定义DOM节点无法拖拽 版本3.5.3 并且配有draggable： true 和name属性 怎么解决
