### ISSUE TITLE
G6 的数据不可以用重复的 id。id 一定是 unique string。谢谢回复！请问我在 layout 的getId方法里面，返回节点id拼上其父id，让这个返回值唯一，这样也不可以吗？

### ISSUE THREAD

**Issue by youmin** [antvis/G6#1393]
G6 的数据不可以用重复的 id。id 一定是 unique string

_Originally posted by @Yanyan-Wang in https://github.com/antvis/G6/issues/1389#issuecomment-608206327_

**Comment by Yanyan-Wang** [comment]
不行的，那样只是在布局算法中 id 唯一了，但是在整个图的其他操作里的 id 还是不唯一的。
