### ISSUE TITLE
外层容器css缩放，导致无法正常拖拽节点

### ISSUE THREAD

**Issue by yuanxiaoyu** [antvis/G6#1395]
G6 Version: 3.4.4

Platform: macbook pro 10.15.3

Mini Showcase(like screenshots):
![Image text](https://user-images.githubusercontent.com/25719069/73809174-5f5e1f00-480d-11ea-9a0d-83441d6d4e4e.gif)

g6

CodePen Link: https://codepen.io/dongxing/project/editor/XWjMaN

在对body设置transformScale后，无法正确获取节点的位置，导致无法正确拖拽节点

#container {
    transform: scale(1.2);
}

参考 https://github.com/antvis/G6/issues/1175#issuecomment-584016055 问题依旧

**Comment by Yanyan-Wang** [comment]
底层渲染引擎 G 的 bug，正在修复中

**Comment by Yanyan-Wang** [comment]
v3.4.10 已修复，使用下面代码按需开启：

```javascript
graph.get('canvas').set('supportCSSTransform', true);
```
