### ISSUE TITLE
canvas  渲染方式无法拖拽节点问题

### ISSUE THREAD

**Issue by linkai0001** [antvis/G6#1396]
当渲染方式为 canvas ，并且浏览器屏幕比例缩小时，会出现无法拖拽节点问题，当设置为 svg ，似乎是正常的
g6 版本为3.4.4

问题代码：
`import React from 'react';
import G6 from '@antv/g6';

class IndexComponent extends React.Component {

    componentDidMount() {
        let data = {
            // 点集
            nodes: [{
                id: 'node1', // String，该节点存在则必须，节点的唯一标识
                x: 100,      // Number，可选，节点位置的 x 值
                y: 100,       // Number，可选，节点位置的 y 值
                label: "新增",
                class: "n0",
                // 设置节点的形状
                shape: "modelRect",
                // 节点中文本样式和其他配置
                labelCfg: {
                    // 文本在元素中的位置
                    positions: "center"
                }
            },{
                id: 'node2', // String，该节点存在则必须，节点的唯一标识
                x: 300,      // Number，可选，节点位置的 x 值
                y: 100,       // Number，可选，节点位置的 y 值
                label: "编辑",
                class: "n1",
                shape: "rect"
            }],
            // 边集
            edges: [{
                source: 'node1', // String，必须，起始点 id
                target: 'node2',  // String，必须，目标点 id
                label: "连接",
                class: "e0",
                shape: "cubic-horizontal",
                style: {
                    lineWidth: 2,
                    endArrow: true
                }
            }]
        };

        // 配置网格
        const grid = new G6.Grid();
        // 使用 defaultNode 和 defaultEdge 实现默认配置(全局配置)
        let graph = new G6.Graph({
            container: document.querySelector("#flow"),
            width: 400,
            height: 500,

            modes: {
                // 支持 拖拽，缩放 内置交互行为(画布和节点)
                default: [ 'drag-canvas', 'zoom-canvas', 'drag-node' ],  // 允许拖拽画布、放缩画布、拖拽节点
            },
            plugins: [grid]
        });
        graph.data(data);
        graph.render();
    }

    render() {
        return (
            <React.Fragment>
                <div id = "flow"></div>
            </React.Fragment>
        )
    }
}

export default IndexComponent;`

**Comment by Yanyan-Wang** [comment]
我这里没有复现呢。是否是拖拽到了文本？modelRect 的文本上面不会响应拖拽事件。

**Comment by linkai0001** [comment]
hello ,  你可以尝试 缩小至90%， 然后刷新页面，然后再拖拽， 我的似乎是避险
步骤：
浏览器缩小至90% > 刷新页面 >  尝试拖拽

![image](https://user-images.githubusercontent.com/24260681/78630443-4edd2a00-78cc-11ea-9474-2b5a83b9037b.png)

**Comment by linkai0001** [comment]
modelRect 内置节点的文本是否也附上拖拽事件呢， 这个确实也是我想问的问题

**Comment by Yanyan-Wang** [comment]
按照你说的步骤操作还是没有复现：https://codepen.io/Yanyan-Wang/pen/YzXmaqa?__cf_chl_jschl_tk__=2db1189705beff97eec9ed6e685a8a9dc5f93db8-1586234907-0-AR-pQIPd4y5VMlitJGmNq4gli54boEsNBLC9q_sBxEVLb1c4Zd52fOab-_1UdLAy9V5OpEx-2N9u-5eP87jmHuBZdCS75BF6jlALoQ8zyd7Bf6jj7WaymN_hj5f2KeSk6NGsWAIHzM3ikHZvFOeblcA_Hw2oRdjaFLrujdLI1HvvoNpJFQO2yGedoUJD0hi0uSjTpZs3KUIwyoMCvwiyYEvVKTYPJtlf3E-vadu01LF7hc7bFmoMWRmWCcDUJR2V5jf8Y9c5rVuJhQ3X4YMj9h7neNYNXYQGjqH6NFHcZjErSH8Zv7mGGsGLe6C-t0elZcWL_HtXe2c4UK2h2lYfNnA

**Comment by Yanyan-Wang** [comment]
modelRect 文本加上拖拽暂时可以通过自己拿到节点的文本图形设置：
```javascript
graph.getNodes().forEach(node => {
  const text = node.get('group').find(element => element.get('className') === 'node-label');
  text.set('draggable', true);
});
```

后面会考虑是否内置开启。

**Comment by linkai0001** [comment]
好的感谢， 刚才使用了你提交的在线项目， 也有此问题额，用谷歌和IE测试了额， 拖拽 rect 节点额。 拖拽 modelRect  节点是没有问题的

**Comment by linkai0001** [comment]
[20200407_130617.zip](https://github.com/antvis/G6/files/4442122/20200407_130617.zip)
如上是我录制的问题视频，基于你的在线项目，你可以看下

**Comment by Yanyan-Wang** [comment]
你的操作系统是？

**Comment by linkai0001** [comment]
原来是在 windwos 上的谷歌(版本 78.0.3904.108)和IE上测试了, 是不可以的， 刚才我在 mac 的谷歌上测试，也是存在此问题额

**Comment by baizn** [comment]
没有复现

**Comment by baizn** [comment]
更新到最新版本，如果还有这个问题，麻烦提供个在线可复现的demo
