### ISSUE TITLE
自定义 fonticon 节点后,   canvas 渲染方式问题

### ISSUE THREAD

**Issue by linkai0001** [antvis/G6#1398]
自定义 fonticon 节点后,   canvas 渲染方式会在第一次启动时显示如下的符号，在拖拽或二次刷新页面后， 将显示 fonticon，  svg 不存在此问题额。

![image](https://user-images.githubusercontent.com/24260681/78421722-69c15b80-768c-11ea-9153-c1a19ba2896d.png)

完整代码
`import React from 'react';
import G6 from '@antv/g6';
import "../../config/behavior";
import "../../config/behavior";
import "../../config/node";

class IndexComponent extends React.Component {

    componentDidMount() {

        const COLOR = '#40a9ff';
        const graph = new G6.Graph({
            container: 'flow',
            width: 800,
            height: 600,
            modes: {
                default: ['collapse-expand', 'drag-canvas', 'drag-node'],
            },
            defaultNode: {
                backgroundConfig: {
                    backgroundType: 'circle',
                    fill: COLOR,
                    stroke: 'LightSkyBlue',
                },
                type: 'iconfont',
                size: 12,
                style: {
                    fill: '#fff',
                },
                labelCfg: {
                    style: {
                        fill: COLOR,
                        fontSize: 12,
                    },
                },
            }
        });
        const data = {
            nodes: [
                {
                    id: "node01",
                    x: 100,
                    y: 100,
                    text: '\ue6f9',
                    label: 'hello'
                }
            ]
        }

        graph.data(data);
        graph.render();
    }

    componentWillUnmount() {
        // emitter.removeListener(this.eventEmitter);
    }

    render() {
        return (
            <React.Fragment>
                <div id="flow" style={{width: '100%', height: '100%'}}></div>
            </React.Fragment>
        )
    }
}

export default IndexComponent;`

`import G6 from '@antv/g6';

// import diamondNode from "./diamond-node";
// import iconFontNode from "./icon-font-node";
//G6.registerNode("diamond-node", diamondNode());
// G6.registerNode("iconfont", iconFontNode());

G6.registerNode('iconfont', {
    draw(cfg, group) {
        console.log("cfg",cfg, group)
        const {
            backgroundConfig: backgroundStyle,
            style,
            labelCfg: labelStyle,
        } = cfg;

        if (backgroundStyle) {
            group.addShape('circle', {
                attrs: {
                    x: 0,
                    y: 0,
                    r: cfg.size,
                    ...backgroundStyle,
                },
                // must be assigned in G6 3.3 and later versions. it can be any value you want
                name: 'circle-shape',
            });
        }

        const keyShape = group.addShape('text', {
            attrs: {
                x: 0,
                y: 0,
                fontFamily: 'iconfont', // 对应css里面的font-family: "iconfont";
                textAlign: 'center',
                textBaseline: 'middle',
                text: cfg.text,
                fontSize: cfg.size,
                ...style,
            },
            // must be assigned in G6 3.3 and later versions. it can be any value you want
            name: 'text-shape1',
        });
        const labelY = backgroundStyle ? cfg.size * 2 : cfg.size;

        group.addShape('text', {
            attrs: {
                x: 0,
                y: labelY,
                textAlign: 'center',
                text: cfg.label,
                ...labelStyle.style,
            },
            // must be assigned in G6 3.3 and later versions. it can be any value you want
            name: 'text-shape1',
        });
        return keyShape;
    },
});`

**Comment by Yanyan-Wang** [comment]
暂时没有找到原因，可以先这样解决：
graph.render(); 之后加这段代码：
```javascript
setTimeout(() => {
  graph.paint();
}, 16);
```

**Comment by caojin24** [comment]
3.4.7版本 按上面的设置 没有生效

**Comment by Simmon12** [comment]
> 暂时没有找到原因，可以先这样解决：
> graph.render(); 之后加这段代码：
> 
> ```js
> setTimeout(() => {
>   graph.paint();
> }, 16);
> ```

同，3.4.7版本 按上面的设置 没有生效，该怎么解决

**Comment by pfdgithub** [comment]
使用 `fontFamily: 'iconfont'` 绘制出现方框，是因为初次绘制时字体文件尚未加载完成。  
可想办法提前触发加载字体文件，比如在应用初始化时添加一个隐藏字体图标。

**Comment by like-Lime** [comment]
解决了吗，有方案吗
