### ISSUE TITLE
g6动态效果，切换到浏览器其他页签一段时间后，返回改动态效果图的问题

### ISSUE THREAD

**Issue by liuv1118** [antvis/g6#140]
g6制作的动态效果图，例如下面图中流动的白色圆点
http://antvis.github.io/g6/demo/01-businessFlow/sign-flow.html
当将此页面打开后，不关闭，然后切换到其他浏览器页签，在其他页签停留一段时间后（建议停留时间长一些），再回到当前g6动态效果图的页签，会出现浏览器内存溢出现象或者出现动态效果卡住的相关问题。求解

**Comment by TomHuangCN** [comment]
bug , 于下个版本修复

**Comment by TomHuangCN** [comment]
fixed in 1.2.3

**Comment by deke1521** [comment]
这个BUG在_antv.g6-3.0.2中又复现了。
