### ISSUE TITLE
antVg6 在ie浏览器上，只要引入就一直加载

### ISSUE THREAD

**Issue by xiaohu12685** [antvis/G6#1400]
1. 已尝试：https://g6.antv.vision/zh/docs/manual/FAQ/supportIE
![image](https://user-images.githubusercontent.com/30620913/78472107-f2adc500-7768-11ea-9e43-bc877290f388.png)
![image](https://user-images.githubusercontent.com/30620913/78472110-fb9e9680-7768-11ea-9b47-dcf00b70704f.png)

**Comment by baizn** [comment]
请升级到 3.4.9 版本 https://github.com/antvis/G6/pull/1541
