### ISSUE TITLE
minimap does not behave correctly when canvas is dragged and nodes are out of view

### ISSUE THREAD

**Issue by enodr** [antvis/G6#1401]
Using the default example: https://g6.antv.vision/en/examples/tool/minimap

If you drag the canvas so that the nodes are not in the viewport anymore, the minimap does not reflect correctly the current view.

![image](https://user-images.githubusercontent.com/10436257/78499053-a6ee2200-774e-11ea-8dc3-784ef972b96a.png)

**Comment by xiaohu12685** [comment]
graph.fitView();

**Comment by enodr** [comment]
Minimap plugin on X6 behaves as expected. Maybe the code should be merged in G6?

https://observablehq.com/@jiazhewang/introduction-to-antv#X6Demo

**Comment by Yanyan-Wang** [comment]
For performance reasons, the minimap in G6 is updated only when the viewport is changed by dragging or zooming the canvas, but not dragging a node. In this case, drag the canvas after dragging the node will trigger the minimap update.

Do you think it is necessary to update minimap after 'dragend' event happens on a node? Users' suggestions are always the best input for us.

**Comment by enodr** [comment]
I don't think it is a problem with dragging nodes. The problem occurs when dragging the canvas so that the nodes becomes out of view. The minimap should then be updated as if the viewport has been zoomed out, or viewport has been expanded.
Please have a look at the X6 minimap plugin as it has the good behavior:
https://observablehq.com/@jiazhewang/introduction-to-antv#X6Demo
Even though this demo does not support canvas dragging, you can see that when a node is out of the viewport, the minimap is updated as if the viewport has been expanded.

**Comment by Yanyan-Wang** [comment]
Fixed by 3.4.5.

**Comment by enodr** [comment]
This works perfectly now in 3.4.5, thanks for the update.
