### ISSUE TITLE
Bug when adding nodes in a group of type rect and groupType=circle

### ISSUE THREAD

**Issue by enodr** [antvis/G6#1402]
When a graph is instantiated with no groupType (default = circle), adding nodes to a group of type 'rect' using graph.add() leads to bug when moving the group. The group cannot be moved on the canvas and the rectangle gets stuck.

Bug can be seen here, just try to move the group rectangle:
https://codesandbox.io/s/nice-sky-5tgbt

Edit: when instanting the graph with groupType = 'rect', then adding a group of type 'circle' with graph.add() then the group also behaves very strange (nodes are placed outside the group when moving).  See example: https://codesandbox.io/s/trusting-tu-1py7j

Code snippet to reproduce the bug with no groupeType defined (default=circle):
`const nodes = ["node1", "node2"];
graph.addItem("group", {
  groupId: "xxxx000999",
  nodes,
  type: "rect",
  title: {
    text: "The title text",
    stroke: "",
    fill: "",
    offsetX: 10,
    offsetY: 0
  }
});`

**Comment by Yanyan-Wang** [comment]
All the problems about group will be solved next month with new mechanism, we are re-designing and implementing now.

**Comment by JyotsnaC** [comment]
@Yanyan-Wang : Which release will have groups re-designed?

**Comment by baizn** [comment]
V 3.5。
doc：https://g6.antv.vision/zh/docs/manual/middle/combo
