### ISSUE TITLE
节点的labelCfg中offset为什么配置无效？

### ISSUE THREAD

**Issue by zhoustudent** [antvis/G6#1404]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

G6 Version: 3.4.0
Platform: mac
Mini Showcase(like screenshots): 无
CodePen Link: 无
![image](https://user-images.githubusercontent.com/22286864/78626524-9c07ce80-78c1-11ea-8063-b90c2fb6b340.png)
`label: item.name,
  labelCfg: {
       position: index % 2 === 0 ? 'bottom' : 'top',
       offset: (index + 2) % 4 === 0 || (index + 1) % 4 === 0 ? 20 : 5,
   },`

**Comment by Yanyan-Wang** [comment]
写成在线 demo 吧，这样无法定位问题。

**Comment by zhoustudent** [comment]
找到问题所在了，抱歉哈

**Comment by mrcluo** [comment]
@zhoustudent 你好啊，请问是怎么解决的，我也遇到了offset失效了
