### ISSUE TITLE
G6 关系预判的场景与逻辑

### ISSUE THREAD

**Issue by Cuipeihua9** [antvis/G6#1405]
开发方你好，我在阅读https://antv-g6.gitee.io/zh/docs/manual/cases/relations 文档时遇到一个问题，
G6的图分析提供了关系预判功能，有关这个功能的应用场景与预判逻辑能否写得再详细些，举个具体的例子？
基于目前文档的描述，感觉这个功能属于给不相干的两个实体间主观赋予了一个自定义关系，从而判断其他实体间的关系，但是这个虚线部分又是怎么生成的？完全不理解其中的逻辑，文档中的图片感觉也不是连贯的demo。
希望你们能够帮忙写清楚，谢谢！

**Comment by Yanyan-Wang** [comment]
这个不是 G6 提供的功能，这个是第三方基于 G6 做的一个应用。里面的逻辑根据你的业务需求来定，这个文档里面没有细说应该是省略掉了一些涉密部分。

另外，文档和 demo 以这个网址为准：https://g6.antv.vision/zh
中文镜像可能会有延迟。
