### ISSUE TITLE
Tooltip在右下角时很容易导致鼠标在tooltip展示内，导致点击不到节点

### ISSUE THREAD

**Issue by lwba21190** [antvis/G6#1409]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
Fixed by 3.4.5.

Tooltip 支持配置 offset。详见 pr：https://github.com/antvis/G6/pull/1414
