### ISSUE TITLE
force layout在稳定前改变edge状态后无法还原的问题

### ISSUE THREAD

**Issue by Enivia** [antvis/G6#1418]
在force布局中监听edge的mouseenter和mouseleave事件。
mouseenter时，设置hover状态为true；mouseleave时设置hover状态为false。
1. force布局稳定之前：鼠标移入，hover状态为true时edge高亮；移出，hover重置为false时edge依然为高亮状态。
2. force布局稳定之后表现正确。

[code sandbox](https://codesandbox.io/s/blissful-wildflower-ingnk)

**Comment by Yanyan-Wang** [comment]
尝试一下 3.5.1，应该没有问题了。
