### ISSUE TITLE
arc边箭头在SVG中正常，在canvas中不生效

### ISSUE THREAD

**Issue by Enivia** [antvis/G6#1419]
- **G6 Version**: 3.4.4
- **Platform**: windows
- **Code Sandbox**: https://codesandbox.io/s/stoic-carson-i734t

**Comment by Yanyan-Wang** [comment]
谢谢，是一个底层渲染引擎的已知问题，正在修复中

**Comment by GuaoGuao** [comment]
请问这个问题有别的解决办法吗

**Comment by Yanyan-Wang** [comment]
渲染引擎在当前版本暂时无法修复这一问题。可以使用 quadratic cubic 等贝塞尔曲线边代替 arc。
