### ISSUE TITLE
image

### ISSUE THREAD

**Issue by CodeCute** [antvis/g6#142]
当node的type是
image下无法resizeNode

![default](https://user-images.githubusercontent.com/17939853/34513076-3817cb5a-f0a1-11e7-90ea-1617f4e260b2.png)

`    G6.registerNode('house', {
        draw:function(cfg, group) {
            return group.addShape('image', {
                attrs: {x: cfg.x-64, y: cfg.y-64, width: 128, height: 128,sx:64, sy:64,  swidth: 128, sheight: 128, img: './house.png'},
            });
        },
        getAnchorPoints:function () {return null;}
    });`
类似上面自定义了宽高的节点 好像都不可以拖动大小了……

**Comment by TomHuangCN** [comment]
无法定位你的问题，写 codepen

**Comment by TomHuangCN** [comment]
无法定位你的问题，写codepen
