### ISSUE TITLE
Usage of minimap plugin with force layout makes slow rendering

### ISSUE THREAD

**Issue by enodr** [antvis/G6#1420]
When using the minimap plugin with an animated layout like force, the rendering becomes really slow.

Is there an option to control the rendering options of minimap ? It could help to only refresh every x seconds, or pause rendering while animation is running.

**Comment by Yanyan-Wang** [comment]
How many nodes in your graph? And what is the renderer?

We are improving the performance of minimap now. v.3.4.5 will be released today.

Use 'canvas' renderer for graph and 'delegate' or 'keyShape' type for minimap temporally.

**Comment by enodr** [comment]
About 200 nodes and 200 edges, using canvas renderer.

Can you elaborate on how to pass delegate or keyShape types for minimap? I am instantiating like this:
`const minimap = new G6.Minimap({ container: graphDOM, size: [150, 100],  className: "my-minimap", });`

then I pass plugins = [minimap] when creating the graph

**Comment by Yanyan-Wang** [comment]
```
const minimap = new G6.Minimap({
  container: graphDOM,
  size: [150, 100],
  className: "my-minimap",
  type: 'delegate'
});
```

Checkout the API here: 
https://g6-v3-2.antv.vision/en/docs/api/Plugins/#configuration

**Comment by enodr** [comment]
Thanks. Performance of minimap with static layout is fine, but when using force animated layouts then it's very slow. I guess there isn't much to do about it, it's limitations of canvas. Can't wait for webgl to increase performance.

**Comment by Yanyan-Wang** [comment]
Fixed by 3.4.5. Minimap will be updated after the layout is done.

**Comment by Yanyan-Wang** [comment]
It is achieved by using debounce to reduce the frequency of the minimap's  rendering

**Comment by enodr** [comment]
This works perfectly now in 3.4.5, thanks for the update.
