### ISSUE TITLE
求助：关于模拟点击graph 节点

### ISSUE THREAD

**Issue by brightgems** [antvis/G6#1423]
在我设计的页面中，在G6图表外有DOM表格，希望点击表格中的一行后，模拟graph节点的点击行为。请问应该怎么实现？

**Comment by Yanyan-Wang** [comment]
点击节点会触发什么事件？

**Comment by brightgems** [comment]
点击后触发node:click事件，后来发现模拟用用户在SVG上点击坐标位置可能不行。最后通过eventBus调用node:click事件的绑定函数解决了。

**Comment by Yanyan-Wang** [comment]
方便的话可以给出解决问题示例代码，帮助后面遇到这个问题的同学一起学习。

**Comment by taoxiaohang** [comment]
请问具体是怎么实现的
