### ISSUE TITLE
如何兼容ie10以下

### ISSUE THREAD

**Issue by xiaohu12685** [antvis/G6#1424]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
不兼容，正常的交互和渲染只支持到 ie11

**Comment by xiaohu12685** [comment]
好的
上次的问题解决了
![image](https://user-images.githubusercontent.com/30620913/84635869-6701a300-af26-11ea-9962-52ea7eb0f700.png)

**Comment by canifindyou** [comment]
怎么样才能在ie低版本中正常使用

**Comment by xiaohu12685** [comment]
> 怎么样才能在ie低版本中正常使用

参考一下这个：https://g6.antv.vision/zh/docs/manual/FAQ/supportIE
