### ISSUE TITLE
需求：批量的更新，全量的更新

### ISSUE THREAD

**Issue by wangxiaogang94** [antvis/G6#1425]
目前批量更新只能是遍历来做，或者changeData。如果遍历来做页面分分钟卡死，如果changeData的话又会重新布局影响到当前的节点分布。

**Comment by 123Assassin** [comment]
+1

**Comment by TLYTLX** [comment]
+1   全量更新数据+切换布局  若遍历addItem 3k条线要14s左右，changeData对布局切换有影响  会出现节点空白状态

**Comment by wangxiaogang94** [comment]
有解决办法了
const item = e.item;
const graph = this.graph;

const autoPaint = graph.get('autoPaint');
graph.setAutoPaint(false);

// graph.setItemState(item, 'selected', true);
// 在这里循环就好

graph.paint();
graph.setAutoPaint(autoPaint);

**Comment by Yanyan-Wang** [comment]
现在支持在 changeData 之前先调用 destroyLayout，这样 changeData 之后，不会重新布局，原来的节点位置是不会被改变的。参考 API: https://g6.antv.vision/zh/docs/api/graphFunc/layout/#destroylayout
related to https://github.com/antvis/G6/issues/2140

**Comment by wgm7512** [comment]
@Yanyan-Wang TreeGraph 布局呢？

**Comment by wgm7512** [comment]
@Yanyan-Wang TreeGraph如何保持更新数据不影响布局呢?
