### ISSUE TITLE
moveTo和translate函数问题

### ISSUE THREAD

**Issue by kkltmoyu** [antvis/G6#1426]
这两个移动画布的函数描述中：“画布移动到指定坐标”的画布指的是画布中心点还是画布左上角？

**Comment by Yanyan-Wang** [comment]
moveTo 是指包围盒的左上角移动到指定位置。
translate 是指移动一段相对的距离，参数代表移动向量，所以没有相对于画布中心还是左上角的区分。

两个函数目前存在问题。正在修复中

**Comment by Yanyan-Wang** [comment]
v3.4.7 已修复
