### ISSUE TITLE
How to use antv g6 with vue cli 

### ISSUE THREAD

**Issue by quanghuynguyen1902** [antvis/G6#1427]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by enodr** [comment]
g6 works perfectly with Vue. Create a new project and install g6:
```
vue create testapp
cd testapp
npm install @antv/g6
```
In your vue component:
```
<template>
<div ref="canvas"></div>
</template>
[...]
<script>
import G6 from "@antv/g6";
[...]
const graph = new G6.Graph({container: this.$refs.canvas, ...});
```

**Comment by quanghuynguyen1902** [comment]
should I  put " const graph ... " into mounted() to run
