### ISSUE TITLE
when use to node(nodeFn)

### ISSUE THREAD

**Issue by quanghuynguyen1902** [antvis/G6#1428]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

graph.node(node => {
  return {
    id: node.id,
    type: 'rect',
    style: {
      fill: 'blue',
    },
  };
});

graph.data(data);
graph.render();
########################
code in https://g6.antv.vision/en/docs/api/Graph/#nodenodefn

**Comment by Yanyan-Wang** [comment]
What is the problem you got?

**Comment by quanghuynguyen1902** [comment]
I can use it to change size specific node ?

**Comment by Yanyan-Wang** [comment]
```javascript
graph.node(node => {
  return {
    id: node.id,
    type: 'rect',
// assign size here
    size: [100, 200],
    style: {
      fill: 'blue',
// or assign height and width here, height and width in style have higher priority than size
      width: 100,
      height: 200
    },
  };
});
```

**Comment by quanghuynguyen1902** [comment]
```javascript
graph.node(node => {
  return {
    id: node.id,
    type: 'rect',
if node.id == 1 {
    size: [100, 200],
    style: {
      fill: 'blue',
    },
  };
}
});
```
##############################
my example code is wrong or not wrong?

**Comment by Yanyan-Wang** [comment]
this function must be called before graph.render(). It will not take effect otherwise.
