### ISSUE TITLE
demo文件引入的问题：鸢尾花的demo中 是否忘记了引入了d3.js的cdn 文件，因为在39行使用了d3, 没有引入d3的话， demo在本地运行会报错

### ISSUE THREAD

**Issue by leejay1992** [antvis/g6#143]

**Comment by leejay1992** [comment]
<img width="1240" alt="zero" src="https://user-images.githubusercontent.com/15710933/34547615-627e47d4-f137-11e7-9a50-897c3a101da5.png">

**Comment by TomHuangCN** [comment]
d3 的script 在下面

**Comment by leejay1992** [comment]
看到了在 css 之后， 希望可以这其他的CDN一起放着 免得像我这样的人给忘记了😂

**Comment by TomHuangCN** [comment]
上面的 script 是自动生成的。d3 不在官方的脚本列表里，所以是demo单独写的，所以在下面了
