### ISSUE TITLE
怎么导入导出

### ISSUE THREAD

**Issue by Lyqxyz** [antvis/G6#1432]
怎么导出数据和导入数据

**Comment by Yanyan-Wang** [comment]
读取数据：graph.data(data): https://g6.antv.vision/zh/docs/api/Graph/#datadata

导出当前数据：graph.save(): https://g6.antv.vision/zh/docs/api/Graph/#save

导出图片：graph.downloadImage(): https://g6.antv.vision/zh/docs/api/Graph/#downloadimagename-backgroundcolor

**Comment by youmin** [comment]
> 读取数据：graph.data(data): https://g6.antv.vision/zh/docs/api/Graph/#datadata
> 
> 导出当前数据：graph.save(): https://g6.antv.vision/zh/docs/api/Graph/#save
> 
> 导出图片：graph.downloadImage(): https://g6.antv.vision/zh/docs/api/Graph/#downloadimagename-backgroundcolor

如果元素很多超出画布了有办法显示全吗？或者我缩小了让画布显示全了，可以设置图片的清晰度之类的吗？因为导出图片后放大不清晰
