### ISSUE TITLE
Render nodes automatically on screen

### ISSUE THREAD

**Issue by djamaile** [antvis/G6#1433]
So, for as far as I know you have to give nodes defined positions, to render them. Is it possible to give these nodes automatically x and y position? These would help with rendering data from a backend source where you don't know how many nodes you will have. 

Specifically talking about this example: https://g6.antv.vision/en/examples/scatter/edge

**Comment by Yanyan-Wang** [comment]
Use layouts, there are lots of layout algorithms in G6:

https://g6.antv.vision/en/docs/manual/middle/layout
