### ISSUE TITLE
[BUG]树形节点高度不一致，导致重叠

### ISSUE THREAD

**Issue by hellosean1025** [antvis/G6#1434]
树形节点高度不一致，导致重叠，如何解决？
尝试使用 layout getHeight  getVGap 无法解决。

在线示例：https://codesandbox.io/s/objective-banzai-fgeix?file=/index.js
图片展示：
![image](https://user-images.githubusercontent.com/17695103/79057200-36d12600-7c91-11ea-8614-6b2445cb5c8d.png)

**Comment by Yanyan-Wang** [comment]
通过 getHeight  getVGap 可以解决的，再调整一下自定义节点里面图形的位置。另外，数据里面最好给节点唯一的 string  id

https://codesandbox.io/s/busy-elgamal-z1817?file=/index.js

**Comment by hellosean1025** [comment]
感谢
