### ISSUE TITLE
怎么自适应html node节点的宽高呢

### ISSUE THREAD

**Issue by BusyHe** [antvis/G6#1435]
![image](https://user-images.githubusercontent.com/17348825/79060043-3184d300-7cb3-11ea-8818-4b1f92adce93.png)
![image](https://user-images.githubusercontent.com/17348825/79060045-38abe100-7cb3-11ea-994e-8dd2a2e00c50.png)
![image](https://user-images.githubusercontent.com/17348825/79060046-482b2a00-7cb3-11ea-82db-a5980c6f413e.png)

**Comment by BusyHe** [comment]
我把让width和height自适应html节点内容

**Comment by hellosean1025** [comment]
@BusyHe 你是怎么支持 html 的啊？我看官网文档没有 dom shape

**Comment by BusyHe** [comment]
> @BusyHe你是怎么支持html的啊？我看官网文档没有dom shape

![image](https://user-images.githubusercontent.com/17348825/79066552-66ad1780-7ceb-11ea-9763-ac6c65ccfd03.png)

**Comment by Yanyan-Wang** [comment]
可以使用 CSS 来控制，和写一般的 HTML 一样。

**Comment by BusyHe** [comment]
@Yanyan-Wang 能举个例子吗

**Comment by Yanyan-Wang** [comment]
https://codepen.io/Yanyan-Wang/pen/WNQvZPO

**Comment by BusyHe** [comment]
![image](https://user-images.githubusercontent.com/17348825/79116743-d985c380-7dbb-11ea-829d-962f2c712011.png)
@hellosean1025 还是有个限定的区域的
