### ISSUE TITLE
svg 渲染方式下使用 clear 方法, 导致新增的边线或节点问题

### ISSUE THREAD

**Issue by linkai0001** [antvis/G6#1437]
svg 渲染方式，在 clear() 清空画布元素后， 在次使用连线会出现箭头失效问题， 而 canvas 渲染方式无此问题。 svg 的渲染方式在执行 clear()后对于新增节点也会有问题，比如新加节点(modelRect)会变得透明，通过定位是因为节点中加入了 style 样式, 样式中配置了阴影效果导致（这就不提供代码了），应该和 箭头失效是同个原因  ， clear 清除了什么数据导致。 
如果改用 canvas ， canvas 又存在其他问题， 相关也提了 issues 单了， 似乎还未解决额，这个问题有什么临时解决方案吗？

操作步骤：
1.  运行代码后先点击“添加边线”
2.  点击清空画布上元素按钮
3. 添加边线按钮

![dbf92b058ed023181d3c5d82c2d178f](https://user-images.githubusercontent.com/24260681/79066064-7cb8d900-7ce7-11ea-9eb5-6d3aa11c46e1.png)
![4af10010793b9e2bbffd3904bf89717](https://user-images.githubusercontent.com/24260681/79066067-7dea0600-7ce7-11ea-8dfd-09322ae350bb.png)
![df84c081c038c3b8672f5f38a8bab17](https://user-images.githubusercontent.com/24260681/79066070-804c6000-7ce7-11ea-84db-95d43a075d72.png)

代码如下：

`import React from 'react';
import G6 from '@antv/g6';

export default class Index extends React.Component{

    componentDidMount() {

        const grid = new G6.Grid();
        this.graph = new G6.Graph({
            container: document.querySelector("#flow"),
            width: 400,
            height: 400,
            groupByTypes: false,
            fitView: true,
            fitViewPadding: 20,
            // 交互模式有两种 ， 分别是 default 和  edit , 默认为 default
            modes: {
                default: [ 'drag-canvas', 'zoom-canvas', "drag-node","add-node"],
            },
            nodeStateStyles: {
                active: {
                    stroke: "green",
                    lineWidth: 3
                }
            },
            renderer: 'svg',
            plugins: [grid]
        });
        this.graph.data(this.getNodes());
        this.graph.render();
        this.edge = null;
    }

    addEdge() {

        this.graph.addItem("edge",{
            target: "0",
            source: "1",
            sourceAnchor: [0],
            targetAnchor: [0],
            style: {
                endArrow: true,
                lineWidth: 2
            }
        });
    }

    getNodes () {
        let data = {
            nodes: [
                {
                    id: '0',
                    type: "modelRect",
                    label: '测试01',
                    x: 100,
                    y: 100,
                    linkPoints: {
                        top: true,
                        bottom: true,
                        left: true,
                        right: true,
                        fill: 'white',
                        size: 14,
                        stroke: "#bae7ff"
                    },
                },{
                    id: '1',
                    type: "modelRect",
                    label: '测试02',
                    x: 200,
                    y: 200,
                    linkPoints: {
                        top: true,
                        bottom: true,
                        left: true,
                        right: true,
                        fill: 'white',
                        size: 14,
                        stroke: "#bae7ff"
                    },
                }
            ]
        };
        return data;
    }

    clearItem() {
        this.graph.clear();
        let nodes = this.getNodes().nodes;
        this.graph.addItem("node",nodes[0]);
        this.graph.addItem("node",nodes[1]);
    }
    
    render() {
        return (
            <React.Fragment>
                <div id="flow"></div>
                <button onClick={this.addEdge.bind(this)}>添加边线</button>
                <button onClick={this.clearItem.bind(this)}>清空画布上元素</button>
            </React.Fragment>
        )
    }
}`

**Comment by linkai0001** [comment]
或者有无代替 clear()  函数的 api , 并且不会出现该问题， 使用 graph.data([]);  graph.render() 也是会出现如上问题

**Comment by Yanyan-Wang** [comment]
SVG 渲染器下确实存在不少问题，底层渲染引擎暂时无法解决这些问题，针对上述问题，两个解决方案：
1. 使用 graph.destroy 并重新创建图示例、重新 graph.data graph.render ，代替 graph.clear，则不会出现上述问题
2. 使用 canvas 渲染器，相比于 svg，它的性能要强很多，并且没有各种 bug……

当前版本(3.x、4.x)暂时不会考虑 SVG 问题的修复，底层渲染引擎正在大升级，我们也将在新版本接入新渲染引擎，届时应当可以解决 SVG 各种 bug
