### ISSUE TITLE
树形节点 addShape dom ，无法使用树形节点内置的折叠功能

### ISSUE THREAD

**Issue by hellosean1025** [antvis/G6#1439]
问题：点击节点无法折叠子节点，如果将 dom 节点换成 rect 节点，没问题

![image](https://user-images.githubusercontent.com/17695103/79082836-613be580-7d5c-11ea-811a-84f5032ea012.png)

示例：https://stackblitz.com/edit/g6tree

**Comment by Yanyan-Wang** [comment]
https://g6.antv.vision/zh/docs/api/shapeProperties/#dom-svg

![image](https://user-images.githubusercontent.com/29593318/79086822-07451b00-7d70-11ea-8fd4-d0d879ed4486.png)

**Comment by hellosean1025** [comment]
@Yanyan-Wang 那使用dom事件，怎么触发节点折叠功能？

**Comment by Yanyan-Wang** [comment]
设置节点数据 collapsed:false, 然后调用 graph.layout()

参考一下源码实现方式 https://github.com/antvis/G6/blob/1cd5dd1fe56efbabedc3622ec572e21ee810bbde/src/behavior/collapse-expand.ts#L29
