### ISSUE TITLE
_g2.default.Net is not a constructor

### ISSUE THREAD

**Issue by linlinNB** [antvis/g6#144]
![image](https://user-images.githubusercontent.com/22005231/34555144-2e34d0cc-f16b-11e7-8322-629e22d98dbd.png)
![image](https://user-images.githubusercontent.com/22005231/34555153-3bbc3a46-f16b-11e7-9422-bc6e78a68e01.png)
请问这是什么情况，菜鸟正在崩溃中

**Comment by linlinNB** [comment]
![image](https://user-images.githubusercontent.com/22005231/34555253-b66e75d8-f16b-11e7-8bcb-a734423a54a9.png)
![image](https://user-images.githubusercontent.com/22005231/34555277-c1350acc-f16b-11e7-87dc-f73c59e86cff.png)
这是本人引入方式，请各位大佬看一下，本人实在不知道怎们引入了

**Comment by TomHuangCN** [comment]
import G6 from '@antv/g6' 呀

再确认一下依赖的是 G6 1.x

**Comment by linlinNB** [comment]
好的，我重装下G6的1.x版本，主要上面的引用方式我都尝试了，所以很崩溃。。。。泪奔

**Comment by linlinNB** [comment]
好的，谢谢大佬，问题解决了。在npm安装的2.0测试版，回退到1.2.0解决了问题，希望在官方文档能给出相关的说明。
