### ISSUE TITLE
Quadratic 和 cubic 类型的边支持用户自定义 curveOffset

### ISSUE THREAD

**Issue by caoyi0905** [antvis/G6#1442]
目前只有 `arc` 类型的边支持用户自定义 `curveOffset`，但是我翻了一下对应的 [源码](
https://github.com/antvis/G6/blob/29b390647a5c964735a9f5eb15b69c849f4eedf1/src/shape/edge.ts#L420)，其实 `Quadratic` 和 `cubic` 类型的边也是有 `curveOffset` 属性的，也是可以拓展支持用户自定义 `curveOffset`。希望能添加一下该功能，谢谢！

**Comment by Yanyan-Wang** [comment]
v3.4.7 已支持
