### ISSUE TITLE
3.4.5 的group.addShape('dom',options)时dom对象找不到，和官网示例好像不一样

### ISSUE THREAD

**Issue by smallpotato37** [antvis/G6#1443]
这个是我本地跑出来的：
![g6当前版本](https://user-images.githubusercontent.com/40469855/79094110-0371c280-7d89-11ea-9565-3370b8ac3d1f.png)
这个是官网示例：
![g6版本问题](https://user-images.githubusercontent.com/40469855/79094121-0b316700-7d89-11ea-823a-ab34e6bd64f8.png)

代码用的就是官方的示例，当然不排除是不是我搞错了啥……

**Comment by Yanyan-Wang** [comment]
https://codepen.io/Yanyan-Wang/pen/KKdpZPY

对照一下看有什么不同

**Comment by smallpotato37** [comment]
> https://codepen.io/Yanyan-Wang/pen/KKdpZPY
> 
> 对照一下看有什么不同

sorry看漏了render“svg”模式
