### ISSUE TITLE
图表决策bug

### ISSUE THREAD

**Issue by zhujianxiong** [antvis/G6#1444]
图表决策半径不能随文字的长度增大或者换行：https://codesandbox.io/s/36fxo?file=/index.js；
目前文字过多会溢出球的外面；期待文字过多能随着半径增加或者换行显示等优化

**Comment by Yanyan-Wang** [comment]
可以在自定义节点里，拿节点数据的 label 去根据当前半径 format 一下，加换行符。

同样可以在自定义节点里，拿 label 长度调整圆半径。
