### ISSUE TITLE
How to make the graph listen to external events?

### ISSUE THREAD

**Issue by laubonghaudoi** [antvis/G6#1447]
- **G6 Version**: Latest
- **Platform**: Windows
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

I would like to add a refresh button, so that whenever I click the button the `graph.refreshLayout(true);` is called and the graph is refreshed. How can I do this? It seems that G6 can only listen to events within the graph, like `node: click` or `edge:click`. 

I tried to make an `onClick` function like this, passing the graph as a parameter:
```javascript
const onClick = (graph) => (event) => {
    graph.refreshLayout(true);
}
```
But the `graph` is always `null`. So is there a way to make the graph listen to external button clicking events?

**Comment by Yanyan-Wang** [comment]
Is the button a DOM node? Did you bind the onClick function to the DOM node?

**Comment by laubonghaudoi** [comment]
No, I am using G6 in React and the button in an React component. I am using arrow functions in the react component so there is no need to bind the function. The code structure is like this:
```typescript
import { Button } from 'antd';

type Props = {
  data: any;
};

const TreeGraph: React.FC<Props> = props => {
  const ref = React.useRef<HTMLDivElement>(null);
  let graph: any = null;

  const bindEvents = () => {
    graph.on("node:click", (event: any) => {
      // Events
    });
  };

  useEffect(() => {
    if (!graph) {
      graph = TopicTreeGraph(ref);

      graph.node((node: any) => {
        return {
          labelCfg: {
            position:
              node.children && node.children.length > 0 ? "left" : "right"
          }
        };
      });

      graph.data(props.data);
      graph.render();

      bindEvents();
    }
  }, []);

  const onClick = (graph: any) => (event: React.MouseEvent) => {
    graph.refreshLayout(true);
  }

  return (
    <div ref={ref} id="graph">
      <Button style={{ position: "absolute" }} onClick={onClick(graph)}>Refresh</Button>
    </div>
  )
}

```
So is there and way to bind the button's `onClick` event in the `bindEvents` functions?

**Comment by laubonghaudoi** [comment]
Update:

I think I found a way to update the graph, like the codes below. However, the button only works for a few times. After clicking and refreshing for 3+ times, the graph becomes null again and clicking the button doesn't have any response.
```typescript
import { Button } from 'antd';

type Props = {
  data: any;
};

const TreeGraph: React.FC<Props> = props => {
  const ref = React.useRef<HTMLDivElement>(null);
  let graph: any = null;

  const bindEvents = () => {
    graph.on("click", onClick());
  };

  useEffect(() => {
    if (!graph && ref.current) {
      graph = new G6.TreeGraph({
        // Graph configs
      });

      graph.data(props.data);
      graph.render();

      bindEvents();
    }
  }, []);

  const onClick = () => {
    if (graph) graph.refreshLayout(true);
  };

  return (
    <div ref={ref} id="graph">
      <Button style={{ position: "absolute" }} onClick={onClick(graph)}>Refresh</Button>
    </div>
  )
}
```

**Comment by Yanyan-Wang** [comment]
Why do you need the `graph.on('click', onClick()); `? I think you want to click a button to refresh the layout. But it looks like that you want to click the graph to call refreshLayout.

I just implement it here: https://codesandbox.io/s/lingering-fast-982hf?file=/src/App.js
I'm not sure it is the result you want.

**Comment by laubonghaudoi** [comment]
Thank you very much for your implementation Actually I did try that in the first place. But as I stated in the issue description, after clicking the button for a few times, the `graph` object became null so the button stopped working. Is this a bug or anything wrong with my codes?

**Comment by laubonghaudoi** [comment]
@Yanyan-Wang I think I found the cause of this weird bug, I recorded a gif for this, the graph is on the left and the console output on the right:

![demo](https://user-images.githubusercontent.com/11172180/79253023-6c177880-7e37-11ea-9d61-dd634f9d1b5e.gif)

I log the graph object every time I click the reset button. So you can see the first two clicks by clicking the button and double clicking the canvas do work. However, right **after I hovered the node** and showed the node tooltip(which is an antd card component), the graph became null. So clicking the button won't refresh anymore, but double clicking the canvas still refreshes the graph.

So the problem here is, why hovering the node will turn the graph into null?

**Comment by Yanyan-Wang** [comment]
I implemented the tooltip like this, it seems work well: https://codesandbox.io/s/lingering-fast-982hf?file=/src/App.js

could you pls provide an online demo like the link above?

**Comment by laubonghaudoi** [comment]
> I implemented the tooltip like this, it seems work well: https://codesandbox.io/s/lingering-fast-982hf?file=/src/App.js
> 
> could you pls provide an online demo like the link above?

I think I finally found out the problem, and here is my implementation: https://codesandbox.io/s/keen-cartwright-qw13g?file=/src/App.js

There is only one critical difference between your codes and mine, and that is, I put the `let graph=null;` declaration inside the component, instead of outside as a global variable. And thats why the graph becomes null every time the node is hovered, because the component is rerendered while the graph is not recreated. Thank you so much for your help and this really solves my issue.
