### ISSUE TITLE
动态新增树图，调用layout刷新时，父节点位置不变，导致子节点重叠

### ISSUE THREAD

**Issue by linshuzhen** [antvis/G6#1452]
![image](https://user-images.githubusercontent.com/31116700/79318041-162af980-7f39-11ea-8cfb-f63bcbff428b.png)
![image](https://user-images.githubusercontent.com/31116700/79318090-27740600-7f39-11ea-816c-aadc4abb23be.png)
第一次刷新之后子节点重叠  收起再展开就是正常的
![image](https://user-images.githubusercontent.com/31116700/79318195-3ce93000-7f39-11ea-9433-801f86df7efe.png)

**Comment by linshuzhen** [comment]
测试地址
http://39.108.213.139/#/

**Comment by linshuzhen** [comment]
相关代码如下


<template>
  <div class="app-container topology-view">
    <div id="container" />
  </div>
</template>
<script>
import G6 from '@antv/g6'

export default {
  name: 'TopologyView',
  components: {
  },
  props: {},
  data() {
    return {
      mockData: {
        name: '项目',
        color: '#e6a23c',
        collapsed: false, // 是否展开
        checked: true, // 是否选中
        id: 'project',
        hasChildren: true, // 是否有子节点
        children: [
          {
            name: '工作流1',
            id: 'workflow1',
            color: '#ff9041',
            checked: false,
            collapsed: false,
            hasChildren: true,
            children: [
              {
                name: '任务1-1',
                id: 'task1-1',
                color: '#ff9041',
                checked: true
              },
              {
                name: '任务1-2',
                id: 'task1-2',
                color: '#3390ff',
                checked: false
              }
            ]
          },
          {
            name: '工作流2',
            id: 'workflow2',
            color: '#3390ff',
            collapsed: false,
            checked: true,
            hasChildren: true,
            children: [
              {
                name: '任务2-1',
                id: 'task2-1',
                color: '#ff9041',
                checked: true
              },
              {
                name: '任务2-2',
                id: 'task2-2',
                color: '#3390ff',
                checked: false
              }
            ]
          },
          {
            name: '工作流3',
            id: 'workflow3',
            color: '#3390ff',
            collapsed: true,
            checked: true,
            hasChildren: true,
            children: []
          }
        ]
      }
    }
  },
  computed: {},
  watch: {},
  created() {},
  mounted() {
    this.init()
  },
  methods: {
    // 初始化
    async init() {
      // await this.fetchData()
      G6.registerNode('workflow-node', {
        /**
         * 绘制节点/边，包含文本
         * @param  {Object} cfg 节点的配置项
         * @param  {G.Group} group 节点的容器
         * @return {G.Shape} 绘制的图形，通过node.get('keyShape') 可以获取到
         */
        draw(cfg, group) {
          const { checked, color, collapsed, id, name, hasChildren } = cfg

          // node rect
          const rect = group.addShape('rect', {
            attrs: {
              fill: color,
              stroke: '#fff'
            },
            name: 'rect-shape'
          })

          // node text
          const content = name.replace(/(.{19})/g, '$1\n')
          const text = group.addShape('text', {
            attrs: {
              text: content,
              x: 0,
              y: 0,
              textAlign: 'left',
              textBaseline: 'middle',
              fill: '#fff'
            },
            name: 'rect-shape'
          })
          const bbox = text.getBBox()

          // checked rect
          group.addShape('rect', {
            attrs: {
              x: bbox.maxX + 6,
              y: bbox.maxY - 12,
              // r: 8,
              width: 10,
              height: 10,
              stroke: color,
              fill: '#fff',
              cursor: 'pointer',
              isCheckShape: true
            }
          })

          // checked text
          group.addShape('text', {
            attrs: {
              x: bbox.maxX + 12,
              y: bbox.maxY - 6,
              width: 5,
              height: 5,
              textAlign: 'center',
              textBaseline: 'middle',
              text: checked ? '√' : '',
              fontSize: 16,
              cursor: 'pointer',
              fill: checked ? color : '#fff',
              isCheckShape: true
            }
          })

          if (hasChildren) {
            // collapsed circle
            group.addShape('circle', {
              attrs: {
                x: bbox.maxX - bbox.width / 2 + 8,
                y: bbox.maxY - bbox.height / 2 + 12,
                r: 5,
                width: 10,
                height: 10,
                stroke: color,
                fill: '#fff',
                isCollapseShape: true
              }
            })

            // collapsed text
            group.addShape('text', {
              attrs: {
                x: bbox.maxX - bbox.width / 2 + 8,
                y: bbox.maxY - bbox.height / 2 + 13,
                width: 10,
                height: 10,
                textAlign: 'center',
                textBaseline: 'middle',
                text: collapsed ? '+' : '-',
                fontSize: 16,
                fill: color,
                cursor: 'pointer',
                isCollapseShape: true
              }
            })
          }
          rect.attr({
            x: bbox.minX - 4,
            y: bbox.minY - 6,
            width: bbox.width + 26,
            height: bbox.height + 12,
            id: id
          })
          return rect
        },
        setState(type, value, item) {
          const group = item.getContainer()
          const [
            ,
            ,
            CheckedShape,
            CheckedText,
            ExpandShape,
            ExpandText
          ] = group.get('children')
          const model = item.getModel()
          if (type === 'expand') {
            // 更新expand按钮
            const { collapsed } = model
            if (ExpandText) {
              const {
                attrs: { stroke }
              } = ExpandShape
              if (!collapsed) {
                ExpandText.attr({
                  text: '-',
                  fill: stroke
                })
              } else {
                ExpandText.attr({
                  text: '+',
                  fill: stroke
                })
              }
            }
          } else if (type === 'checked') {
            // 更新checked按钮
            const { checked } = model
            if (CheckedText) {
              const {
                attrs: { stroke }
              } = CheckedShape
              if (!checked) {
                CheckedText.attr({
                  text: '',
                  fill: stroke
                })
              } else {
                CheckedText.attr({
                  text: '√',
                  fill: stroke
                })
              }
            }
          }
        }
      })
      const width = document.getElementById('container').scrollWidth
      const height = document.getElementById('container').scrollHeight || 500
      const graph = new G6.TreeGraph({
        id: 'container',
        container: 'container',
        width,
        height,
        fitView: 'autoZoom',
        modes: {
          default: [
            // {
            //   type: 'collapse-expand',
            //   onChange(item, collapsed) {
            //     // const data = item.getModel()
            //     // data.collapsed = collapsed
            //     return false
            //   },
            // },
            'drag-canvas',
            'zoom-canvas'
          ]
        },
        defaultNode: {
          type: 'workflow-node',
          anchorPoints: [
            [0.5, 1],
            [0.5, 0]
          ]
        },
        defaultEdge: {
          type: 'cubic-vertical',
          style: {
            stroke: '#A3B1BF'
          }
        },
        layout: {
          type: 'compactBox',
          direction: 'TB',
          // 指定节点ID
          getId: function getId(d) {
            return d.id
          },
          // 指定节点高度
          getHeight: function getHeight() {
            return 16
          },
          // 指定节点宽度
          getWidth: function getWidth() {
            return 16
          },
          // 指定节点之间的垂直间距
          getVGap: function getVGap() {
            return 20
          },
          // 指定节点之间的水平间距
          getHGap: function getHGap() {
            return 50
          }
        }
      })
      // G6.Util.traverseTree(this.mockData, (item) => {
      //   item.id = item.name
      // })
      graph.data(this.mockData)
      graph.render()

      // 隐藏根节点和关联边
      const localNode = graph.findById('project')
      localNode.hide()
      const edges = localNode.getEdges()
      for (const edge of edges) {
        edge.hide()
      }
      // console.log('localNode', localNode, edges)

      // 点击节点
      graph.on('node:click', async evt => {
        const { item, target } = evt
        const {
          attrs: { isCollapseShape, isCheckShape }
        } = target
        if (isCollapseShape) {
          // 点击展开/收起按钮
          const nodeId = item.get('id')
          const sourceData = graph.findDataById(nodeId)
          const children = sourceData.children
          // 判断是否有子节点
          if (!children || children.length === 0) {
            // 无子节点 无操作 返回
            if (!sourceData.hasChildren) {
              return
            }
            // 有子节点数据 但未获取数据 请求接口
            const childData = [
              {
                name: '任务3-1',
                id: 'task3-1',
                color: '#ff9041',
                checked: true
              },
              {
                name: '任务3-2',
                id: 'task3-2',
                color: '#3390ff',
                checked: false
              }
            ]
            sourceData.children = childData
            graph.changeData()
          }
          const collapsed = !sourceData.collapsed
          item.getModel().collapsed = collapsed
          graph.layout()

          graph.setItemState(item, 'expand', true)
          if (collapsed) {
            graph.setItemState(item, 'expand', false)
          }
        } else if (isCheckShape) {
          // 点击选中/未选按钮
          const model = item.getModel()
          model.checked = !model.checked
          graph.setItemState(item, 'checked', true)
          if (model.checked) {
            graph.setItemState(item, 'checked', false)
          }
        } else {
          console.log('item', item.getModel())
        }
      })
    },
    // 获取数据
    async fetchData() {},
    // 渲染页面
    render() {}
  }
}
</script>
<style lang="scss" scoped>
.topology-view {
  visibility: initial;
  #container {
    width: 100%;
    height: 100%;
  }
}
</style>

**Comment by linshuzhen** [comment]
相关代码如下：
<template>
  <div class="app-container topology-view">
    <div id="container" />
  </div>
</template>
<script>
import G6 from '@antv/g6'

export default {
  name: 'TopologyView',
  components: {
  },
  props: {},
  data() {
    return {
      mockData: {
        name: '项目',
        color: '#e6a23c',
        collapsed: false, // 是否展开
        checked: true, // 是否选中
        id: 'project',
        hasChildren: true, // 是否有子节点
        children: [
          {
            name: '工作流1',
            id: 'workflow1',
            color: '#ff9041',
            checked: false,
            collapsed: false,
            hasChildren: true,
            children: [
              {
                name: '任务1-1',
                id: 'task1-1',
                color: '#ff9041',
                checked: true
              },
              {
                name: '任务1-2',
                id: 'task1-2',
                color: '#3390ff',
                checked: false
              }
            ]
          },
          {
            name: '工作流2',
            id: 'workflow2',
            color: '#3390ff',
            collapsed: false,
            checked: true,
            hasChildren: true,
            children: [
              {
                name: '任务2-1',
                id: 'task2-1',
                color: '#ff9041',
                checked: true
              },
              {
                name: '任务2-2',
                id: 'task2-2',
                color: '#3390ff',
                checked: false
              }
            ]
          },
          {
            name: '工作流3',
            id: 'workflow3',
            color: '#3390ff',
            collapsed: true,
            checked: true,
            hasChildren: true,
            children: []
          }
        ]
      }
    }
  },
  computed: {},
  watch: {},
  created() {},
  mounted() {
    this.init()
  },
  methods: {
    // 初始化
    async init() {
      // await this.fetchData()
      G6.registerNode('workflow-node', {
        /**
         * 绘制节点/边，包含文本
         * @param  {Object} cfg 节点的配置项
         * @param  {G.Group} group 节点的容器
         * @return {G.Shape} 绘制的图形，通过node.get('keyShape') 可以获取到
         */
        draw(cfg, group) {
          const { checked, color, collapsed, id, name, hasChildren } = cfg

          // node rect
          const rect = group.addShape('rect', {
            attrs: {
              fill: color,
              stroke: '#fff'
            },
            name: 'rect-shape'
          })

          // node text
          const content = name.replace(/(.{19})/g, '$1\n')
          const text = group.addShape('text', {
            attrs: {
              text: content,
              x: 0,
              y: 0,
              textAlign: 'left',
              textBaseline: 'middle',
              fill: '#fff'
            },
            name: 'rect-shape'
          })
          const bbox = text.getBBox()

          // checked rect
          group.addShape('rect', {
            attrs: {
              x: bbox.maxX + 6,
              y: bbox.maxY - 12,
              // r: 8,
              width: 10,
              height: 10,
              stroke: color,
              fill: '#fff',
              cursor: 'pointer',
              isCheckShape: true
            }
          })

          // checked text
          group.addShape('text', {
            attrs: {
              x: bbox.maxX + 12,
              y: bbox.maxY - 6,
              width: 5,
              height: 5,
              textAlign: 'center',
              textBaseline: 'middle',
              text: checked ? '√' : '',
              fontSize: 16,
              cursor: 'pointer',
              fill: checked ? color : '#fff',
              isCheckShape: true
            }
          })

          if (hasChildren) {
            // collapsed circle
            group.addShape('circle', {
              attrs: {
                x: bbox.maxX - bbox.width / 2 + 8,
                y: bbox.maxY - bbox.height / 2 + 12,
                r: 5,
                width: 10,
                height: 10,
                stroke: color,
                fill: '#fff',
                isCollapseShape: true
              }
            })

            // collapsed text
            group.addShape('text', {
              attrs: {
                x: bbox.maxX - bbox.width / 2 + 8,
                y: bbox.maxY - bbox.height / 2 + 13,
                width: 10,
                height: 10,
                textAlign: 'center',
                textBaseline: 'middle',
                text: collapsed ? '+' : '-',
                fontSize: 16,
                fill: color,
                cursor: 'pointer',
                isCollapseShape: true
              }
            })
          }
          rect.attr({
            x: bbox.minX - 4,
            y: bbox.minY - 6,
            width: bbox.width + 26,
            height: bbox.height + 12,
            id: id
          })
          return rect
        },
        setState(type, value, item) {
          const group = item.getContainer()
          const [
            ,
            ,
            CheckedShape,
            CheckedText,
            ExpandShape,
            ExpandText
          ] = group.get('children')
          const model = item.getModel()
          if (type === 'expand') {
            // 更新expand按钮
            const { collapsed } = model
            if (ExpandText) {
              const {
                attrs: { stroke }
              } = ExpandShape
              if (!collapsed) {
                ExpandText.attr({
                  text: '-',
                  fill: stroke
                })
              } else {
                ExpandText.attr({
                  text: '+',
                  fill: stroke
                })
              }
            }
          } else if (type === 'checked') {
            // 更新checked按钮
            const { checked } = model
            if (CheckedText) {
              const {
                attrs: { stroke }
              } = CheckedShape
              if (!checked) {
                CheckedText.attr({
                  text: '',
                  fill: stroke
                })
              } else {
                CheckedText.attr({
                  text: '√',
                  fill: stroke
                })
              }
            }
          }
        }
      })
      const width = document.getElementById('container').scrollWidth
      const height = document.getElementById('container').scrollHeight || 500
      const graph = new G6.TreeGraph({
        id: 'container',
        container: 'container',
        width,
        height,
        fitView: 'autoZoom',
        modes: {
          default: [
            // {
            //   type: 'collapse-expand',
            //   onChange(item, collapsed) {
            //     // const data = item.getModel()
            //     // data.collapsed = collapsed
            //     return false
            //   },
            // },
            'drag-canvas',
            'zoom-canvas'
          ]
        },
        defaultNode: {
          type: 'workflow-node',
          anchorPoints: [
            [0.5, 1],
            [0.5, 0]
          ]
        },
        defaultEdge: {
          type: 'cubic-vertical',
          style: {
            stroke: '#A3B1BF'
          }
        },
        layout: {
          type: 'compactBox',
          direction: 'TB',
          // 指定节点ID
          getId: function getId(d) {
            return d.id
          },
          // 指定节点高度
          getHeight: function getHeight() {
            return 16
          },
          // 指定节点宽度
          getWidth: function getWidth() {
            return 16
          },
          // 指定节点之间的垂直间距
          getVGap: function getVGap() {
            return 20
          },
          // 指定节点之间的水平间距
          getHGap: function getHGap() {
            return 50
          }
        }
      })
      // G6.Util.traverseTree(this.mockData, (item) => {
      //   item.id = item.name
      // })
      graph.data(this.mockData)
      graph.render()

      // 隐藏根节点和关联边
      const localNode = graph.findById('project')
      localNode.hide()
      const edges = localNode.getEdges()
      for (const edge of edges) {
        edge.hide()
      }
      // console.log('localNode', localNode, edges)

      // 点击节点
      graph.on('node:click', async evt => {
        const { item, target } = evt
        const {
          attrs: { isCollapseShape, isCheckShape }
        } = target
        if (isCollapseShape) {
          // 点击展开/收起按钮
          const nodeId = item.get('id')
          const sourceData = graph.findDataById(nodeId)
          const children = sourceData.children
          // 判断是否有子节点
          if (!children || children.length === 0) {
            // 无子节点 无操作 返回
            if (!sourceData.hasChildren) {
              return
            }
            // 有子节点数据 但未获取数据 请求接口
            const childData = [
              {
                name: '任务3-1',
                id: 'task3-1',
                color: '#ff9041',
                checked: true
              },
              {
                name: '任务3-2',
                id: 'task3-2',
                color: '#3390ff',
                checked: false
              }
            ]
            sourceData.children = childData
            graph.changeData()
          }
          const collapsed = !sourceData.collapsed
          item.getModel().collapsed = collapsed
          graph.layout()

          graph.setItemState(item, 'expand', true)
          if (collapsed) {
            graph.setItemState(item, 'expand', false)
          }
        } else if (isCheckShape) {
          // 点击选中/未选按钮
          const model = item.getModel()
          model.checked = !model.checked
          graph.setItemState(item, 'checked', true)
          if (model.checked) {
            graph.setItemState(item, 'checked', false)
          }
        } else {
          console.log('item', item.getModel())
        }
      })
    },
    // 获取数据
    async fetchData() {},
    // 渲染页面
    render() {}
  }
}
</script>
<style lang="scss" scoped>
.topology-view {
  visibility: initial;
  #container {
    width: 100%;
    height: 100%;
  }
}
</style>

**Comment by Yanyan-Wang** [comment]
后面有 graph.layout() ，前面就不要调用 changeData 了
![image](https://user-images.githubusercontent.com/29593318/79325650-21cfed80-7f44-11ea-9ec3-3e3dcda096a8.png)
