### ISSUE TITLE
edge改变样式，polyline类型的连线路径计算会乱，刷新又正常了

### ISSUE THREAD

**Issue by Go-Way** [antvis/G6#1455]
配置：
defaultEdge: {
    shape: 'polyline',
    style: {
      radius: 20,
      offset: 45,
      endArrow: true,
      lineWidth: 1,
      stroke: '#C2C8D5'
    }
  }

**Comment by Yanyan-Wang** [comment]
提供一下在线 demo ，以及现在使用的 G6 版本号

**Comment by Go-Way** [comment]
方便加个微信、铤钉吗，没法在线提供一个demo

**Comment by Yanyan-Wang** [comment]
不是很方便，脱敏之后在 codepen.io 或者 codesandbox.io 里面就可以了

**Comment by Yanyan-Wang** [comment]
你好，新版本应该改进过 polyline。由于长时间没有回复所以先关闭这个 PR 了。
