### ISSUE TITLE
使用changeData更新数据,在自定义节点的afterDraw中cfg配置没有更新

### ISSUE THREAD

**Issue by hb592086309** [antvis/G6#1456]
- **G6 Version**:3.4.4
- **Platform**:windows
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

我用changeData去更新数据，某个节点的的属性来标识是否开启节点动画，当属性发生变化时，在afterDraw 的中此属性无变化

**Comment by hb592086309** [comment]
> * **G6 Version**:3.4.4
> * **Platform**:windows
> * **Mini Showcase(like screenshots)**:
> * **CodePen Link**:
> 
> 我用changeData去更新数据，某个节点的的属性来标识是否开启节点动画，当属性发生变化时，在afterDraw 的中此属性无变化

**Comment by Yanyan-Wang** [comment]
提供一下在线 demo

**Comment by hb592086309** [comment]
已解决，是因为更新数据中关注字段缺失，当数据发生变化时，需要传个null才会变化属性，直接不传该字段不会发生变化。
