### ISSUE TITLE
使用registerLayout遇到的class extends相关问题

### ISSUE THREAD

**Issue by claneo** [antvis/G6#1458]
- **G6 Version**:
3.4.7
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:
https://codesandbox.io/s/damp-smoke-wtqwm

最近尝试实现一个自定义layout ，发现一直报`The layout method: someLayout does not exist! Please specify it first.`的错误，经过研究发现g6在registerLayout时会对传入的class extends

g6的代码看起来使用tsc编译的，tsc编译后extends相关逻辑中super动作有这么一句

```js
var _this = _super.call(this) || this;
```

然而babel转译class后的代码中有一个`_classCallCheck`阻止class被当作普通函数调用

```js
function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }
```

有什么好的解决办法吗

**Comment by Yanyan-Wang** [comment]
看这个代码不是很明白你的目的，你想要实现另外一个布局继承之前的自定义布局 'someLayout'？

**Comment by claneo** [comment]
抱歉没描述清楚

假设我实现了并注册了一个自定义布局

```js
G6.registerLayout('someLayout', {}, SomeLayout)
```

在g6源代码`registerLayout`函数中会基于传入的class生成一个新的class

https://github.com/antvis/G6/blob/edb6517b349626f8f1c4b287585ed94bd4485a45/src/layout/layout.ts#L70-L90

而这段代码会被typescript编译为

```js
var GLayout =
/** @class */
function (_super) {
  __extends(GLayout, _super);

  function GLayout(cfg) {
    var _this = _super.call(this) || this;

    var self = _this;
    var props = {};
    var defaultCfg = self.getDefaultCfg();
    mix(props, defaultCfg, layout, cfg);
    each(props, function (value, key) {
      self[key] = value;
    });
    return _this;
  }

  return GLayout;
}(layoutCons);
```

而在create-react-app等类似的项目配置中，SomeLayout这个class会被babel编译为

```js
"use strict";

function _instanceof(left, right) { if (right != null && typeof Symbol !== "undefined" && right[Symbol.hasInstance]) { return !!right[Symbol.hasInstance](left); } else { return left instanceof right; } }

function _classCallCheck(instance, Constructor) { if (!_instanceof(instance, Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

var SomeLayout = function SomeLayout() {
  _classCallCheck(this, SomeLayout);
};
```

于是g6在执行到下面这个地方尝试实例化时，就会报错

https://github.com/antvis/G6/blob/d3428dc269cc886e6084a563335abed78f09b311/src/graph/controller/layout.ts#L164-L171

**Comment by Yanyan-Wang** [comment]
问题是你为什么要把 SomeLayout 放在第三个参数？第三个参数代表的是被继承的布局名字。我理解的是你应该把 SomeLayout 放在 registerLayout 的第二个参数。

**Comment by claneo** [comment]
我在尝试对内置的ForceLayout的excute方法进行一些修改，确实按照文档是应该在第二个参数传入自定义layout，但是这样需要把ForceLayout的其他方法复制一遍，之后我发现了这种用法，所以尝试了一下：

https://github.com/antvis/G6/blob/7f405939915841676bb7d8c445d54bd9ba2bfa90/src/layout/index.ts#L33

我了解这个使用方法并没有在文档中提及，所以只是提出下疑问

**Comment by Yanyan-Wang** [comment]
我还是有点迷惑。。那你第三个参数继承 'force' ，然后第二个参数里面复写 execute 不就可以了吗？

**Comment by claneo** [comment]
好的，明白了

**Comment by NirvanaChow** [comment]
> 
> 
> 问题是你为什么要把 SomeLayout 放在第三个参数？第三个参数代表的是被继承的布局名字。我理解的是你应该把 SomeLayout 放在 registerLayout 的第二个参数。

内置布局的注册，就是把LayoutClass放在了第三个参数：

https://github.com/antvis/G6/blob/855f1b778256d07b90fe8053c95a419a87a686bd/src/layout/index.ts#L37

第二个参数似乎只能接收一个简单对象，如果我把自定义的布局定义成一个类，放在第二个参数就无法传入此类或者此类的实例。

请问是否可以像注册内置布局一样，直接传入自定义布局的类完成注册？

**Comment by NirvanaChow** [comment]
> 
> 
> > 问题是你为什么要把 SomeLayout 放在第三个参数？第三个参数代表的是被继承的布局名字。我理解的是你应该把 SomeLayout 放在 registerLayout 的第二个参数。
> 
> 内置布局的注册，就是把LayoutClass放在了第三个参数：
> 
> https://github.com/antvis/G6/blob/855f1b778256d07b90fe8053c95a419a87a686bd/src/layout/index.ts#L37
> 
> 第二个参数似乎只能接收一个简单对象，如果我把自定义的布局定义成一个类，放在第二个参数就无法传入此类或者此类的实例。
> 
> 请问是否可以像注册内置布局一样，直接传入自定义布局的类完成注册？

发现问题原因了，把类Ctor作为第三个参数传入，报错是因为class上面没有实现getDefaultCfg/init/execute三个方法。加上这三个方法，或者自定义类继承自BaseLayout类，就可以了。

BaseLayout没有从index导出，引入的时候需要写到明细目录
`import {BaseLayout} from "@antv/g6/lib/layout/layout";`
