### ISSUE TITLE
自定义边：垂直折线的示例代码的效果和图不一致

### ISSUE THREAD

**Issue by Plortinus** [antvis/G6#1459]
- **G6 Version**:3.4.7
- **Platform**:MACOS
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:https://codesandbox.io/s/happy-bird-yzjke?file=/index.js

自定义垂直折线边的教程是：
https://antv-g6.gitee.io/zh/docs/manual/advanced/custom-edge

想要的效果：
<img width="211" alt="WX20200417-112406@2x" src="https://user-images.githubusercontent.com/20693993/79528990-11cc2100-809e-11ea-8a9b-38c6a1d6b2e9.png">
实际用代码实现后的效果图：
<img width="458" alt="WX20200417-112418@2x" src="https://user-images.githubusercontent.com/20693993/79529018-24465a80-809e-11ea-872b-f0b01e38550a.png">

第一个节点没有在中间，如何解决？

**Comment by Yanyan-Wang** [comment]
因为你的布局设置了 align: 'DL'，代表了对齐方式，把这个去掉就好了，
