### ISSUE TITLE
state 样式切换出现问题

### ISSUE THREAD

**Issue by jinliming2** [antvis/G6#1460]
- **G6 Version**: 3.4.7
- **Platform**: Linux Kernel 5.4.28
- **Mini Showcase(like screenshots)**:
- **CodeSandbox Link**: https://codesandbox.io/s/silly-lamarr-ettsi?file=/src/App.js

1. 所有 node 默认处于 opacity 0.5 半透明，node1 带着 highlight 状态，显示为半透明红色
1. 鼠标移动到任意 node 上，node 的透明度被设置为 1 不透明，鼠标移开后恢复
1. 鼠标移动到 node1 上，此时 node1 包含两个状态，理想状态下应该显示为不透明的红色，但是实际上显示为不透明的蓝色
1. 鼠标离开 node1，此时 node1 恢复为只包含 highlight 状态，应该显示为半透明红色，却显示的是半透明蓝色

**Comment by baizn** [comment]
stateStyles 建议不要写到 defaultNode，目前保留这种方式，是老版本遗留问题，后面会移除这种方式。
使用以下方式设置状态：
```
   graph = new G6.Graph({
       // ...
        defaultNode: {
          size: 20,
          style: {
            lineWidth: 2,
            stroke: '#5B8FF9',
            fill: '#C6E5FF',
            opacity: 0.5,
          },
        },
        nodeStateStyles: {
          highlight: {
            stroke: '#f5222d',
            fill: '#fcc7ca',
          },
          focused: {
            opacity: 1,
          },
        },
      });
```

另外设置元素的状态，建议使用 graph.setItemState(item, 'stateName', true) 。
