### ISSUE TITLE
自定义一个事件，对节点进行mousedown时切换mode为另一个自定义的mode

### ISSUE THREAD

**Issue by yuhaijian** [antvis/G6#1461]
- G6 Version: 3.4.4

- CodePen Link: https://codepen.io/pen?template=yLYOvJB

自定义一个事件，对节点进行mousedown时切换mode为另一个自定义的mode，在那个mode里的mousemove事件，无法持续的监听到，只在mousedown的一瞬间监听到一次，然后需要鼠标松开之后才能继续监听到move事件。无法即时的监测到画布的mousemove、mouseup等事件。

**Comment by Yanyan-Wang** [comment]
在拖拽过程中的 move 应该用 drag 监听而不是 mousemove

**Comment by yuhaijian** [comment]
谢谢，那这方面的知识在文档中的哪里能够找到详细的说明呢？
