### ISSUE TITLE
install不成功，3.0.0版本install成功，但是升级升不上去，会卡在fsevents@1.2.12，然后报超时

### ISSUE THREAD

**Issue by lqzkl** [antvis/G6#1466]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
你把 npm 镜像换成  cnpm 试一下。看是不是网络问题。为什么要先安装 3.0.0 再升级呢？为什么不直接安装最新版本？

**Comment by lqzkl** [comment]
好的
