### ISSUE TITLE
Not collision node

### ISSUE THREAD

**Issue by quanghuynguyen1902** [antvis/G6#1469]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

how to render node but not collision node
![Screenshot from 2020-04-20 20-51-03](https://user-images.githubusercontent.com/39359294/79759371-cbe6b580-8348-11ea-8141-13b89f724665.png)

in image, my node is collision.

**Comment by Yanyan-Wang** [comment]
If you are using force layout, assign preventOverlap: true and other related configurations shown in doc: https://g6.antv.vision/en/docs/api/layout/Graph#force
demo: https://g6.antv.vision/en/examples/net/forceDirected
