### ISSUE TITLE
无法获取scale滚动率事件和自定义节点自适应相关的样式

### ISSUE THREAD

**Issue by linlinNB** [antvis/g6#147]
第一个问题，当前的API中无法通过内ev对象，获取相关的scalue 滚动率事件。因为当前的需求要满足流程图重新渲染后，重新定位到上一次进行操作的节点的位置和对应的滚动率上，所以这一点很无奈。。。。
第二个问题，自定义节点无法跟着scale滚动率自适应相关的位置，比如插入h1标签后，放大越大，原本的位置就开始发生空隙。

**Comment by TomHuangCN** [comment]
1.

```js
net.getScale(); // 获取当前画布缩放倍率
```

2.

若对缩放有高要求，请用 canvas 定义节点

**Comment by linlinNB** [comment]
@TomHuangCN 那我位移节点的时候，应该按照ev的x,,y坐标还是domX，domY的坐标？同时利用Matrix.translate是否可以做到仿射平移？如何结合net的scale达到仿射的效果？

**Comment by linlinNB** [comment]
大佬，出现了下面的问题，无论我使用dom坐标点，还是x，y属性，结合Matrix的translate方法和scale方法都无法位移到上一次节点？请问，是不是移动的方法有问题，还是通过ev的坐标点的原因？

**Comment by TomHuangCN** [comment]
你如果矩阵变换那套真的熟的话，做这个真不难

https://codepen.io/DoriTong/pen/eybzva?editors=0010

**Comment by linlinNB** [comment]
ok，谢谢大佬
