### ISSUE TITLE
改变画布大小时，gird不会自动更新

### ISSUE THREAD

**Issue by GitHub-wk** [antvis/G6#1474]
https://github.com/antvis/G6/blob/ed4df8d41278e55b5f6bb72e025579c258ef779b/src/plugins/grid/index.ts#L67

当调用graph.changeSize方法会改变canvas大小，grid的width和height不会自动更新。

**Comment by Yanyan-Wang** [comment]
哪个版本 G6？更新到最新应该是支持到

**Comment by GitHub-wk** [comment]
哦哦，3.2.5的版本。看最新版本是修复了哈

**Comment by Yanyan-Wang** [comment]
是的。升级的时候注意一下：
https://g6.antv.vision/zh/docs/manual/FAQ/upgradeGuide
