### ISSUE TITLE
darge布局，fitview在大于一定宽度下生效

### ISSUE THREAD

**Issue by renhongchao** [antvis/G6#1475]
版本：3.4.3
平台：Windows
darge部署
modelRect节点
现象：
  fitView: true,
  fitViewPadding: [ 20, 40, 50, 20 ],
配置在宽度大于一定数值时生效（1100）
1000的时候不生效
想了解下这块应该如何配置使fitView生效，是否和图中节点数相关

**Comment by Yanyan-Wang** [comment]
如果图本身大小和宽度正好合适的时候就不会生效了。
写个在线 demo 看下。

**Comment by renhongchao** [comment]
> 如果图本身大小和宽度正好合适的时候就不会生效了。
> 写个在线 demo 看下。

下面这个   100的时候fitView不生效，200的时候生效

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Tutorial Demo</title>
</head>
<body>
  <div id="mountNode"></div>
  
  <script src="https://gw.alipayobjects.com/os/antv/pkg/_antv.g6-3.4.3/dist/g6.min.js"></script>
  <script>
    const graph = new G6.Graph({
      container: 'mountNode',
      width: 100,
      height: 500,
      fitView: true,
      fitViewPadding: [ 20, 40, 50, 20 ],
      modes: {
            default: ['drag-canvas', 'drag-node',"zoom-canvas",]
      },
      layout: {
          type: 'dagre',
          rankdir: 'TB',
          // 可选，默认为图的中心
          nodesep: 3,
          // 可选
          ranksep: 30,
          // 可选
          controlPoints: true
        },
      defaultNode: {
        size: 30,
        labelCfg: {
          style: {
            fill: '#fff'
          }
        }
      },
      defaultEdge: {
        labelCfg: {
          autoRotate: true
        }
      },
    });
		const main = async () => {
      const response = await fetch(
        'https://gw.alipayobjects.com/os/basement_prod/6cae02ab-4c29-44b2-b1fd-4005688febcb.json'
      );
      const remoteData = await response.json();
      const nodes = remoteData.nodes;
      const edges = remoteData.edges;
      nodes.forEach(node => {
        if (!node.style) {
          node.style = {};
        }
        node.style.lineWidth = 1;
        node.style.stroke = '#666';
        node.style.fill = 'steelblue';
        switch (node.class) {
          case 'c0': {
            node.shape = 'circle';
            break;
          }
          case 'c1': {
            node.shape = 'rect';
            node.size = [ 35, 20 ];
            break;
          }
          case 'c2': {
            node.shape = 'ellipse';
            node.size = [ 35, 20 ];
            break;
          }
        }
      });
      edges.forEach(edge => {
        if (!edge.style) {
          edge.style = {};
        }
        edge.style.lineWidth = edge.weight;
        edge.style.opacity = 0.6;
        edge.style.stroke = 'grey';
      });

      graph.data(remoteData);
      graph.render();
    };
    main();
  </script>
</body>
</html>

**Comment by Yanyan-Wang** [comment]
graph 默认最小缩放系数 minZoom 是 0.2，在宽度是 100 的时候这个需要的缩放系数太小了。可以配置 graph 的 minZoom 小一些，比如 minZoom: 0.05

**Comment by renhongchao** [comment]
> graph 默认最小缩放系数 minZoom 是 0.2，在宽度是 100 的时候这个需要的缩放系数太小了。可以配置 graph 的 minZoom 小一些，比如 minZoom: 0.05

100的时候，添加 minZoom: 0.05确实可以fitView了，但是zoom-canvas失效了，帮忙看下，滚轮放大不了

**Comment by Yanyan-Wang** [comment]
zoom-canvas 也有一个 minZoom 需要设置一下 https://g6.antv.vision/zh/docs/manual/middle/states/defaultBehavior/#zoom-canvas

**Comment by renhongchao** [comment]
可用，多谢
