### ISSUE TITLE
锚点怎么定义到节点内容中？

### ISSUE THREAD

**Issue by imhxc** [antvis/G6#1484]
G6 中多条边连接到某个“节点”的时候，需要设置对应的锚点，但是锚点只能在这个“节点”的描边上添加，没办法将锚点设置到“节点”中的任意位置。

所以问一下，怎么自由设置“边”的接入坐标点。

**Comment by Yanyan-Wang** [comment]
https://g6.antv.vision/zh/docs/manual/middle/elements/anchorpoint

这个相对坐标可以指定任意位置
