### ISSUE TITLE
Dendogram collapse issue with many child nodes

### ISSUE THREAD

**Issue by renjiie** [antvis/G6#1485]
Hi I tried the vertical dendogram with antv g6 but for more children nodes the collapse is not working properly. On click of the node it is not getting collapsed. For the demo data it is working
My code link is in : https://codesandbox.io/s/dendogram-antv-5v4y7?file=/src/treeGraph.js

**Comment by Yanyan-Wang** [comment]
The id of each node MUST be UNIQUE.

e.g. Following code assigns unique id for each node rather than name which might not unique. 

```javascript
let count = 0;
G6.Util.traverseTree(data1, subtree => {
  subtree.id = `node-${count}`;
  count++;
  return true;
});
```

**Comment by renjiie** [comment]
@Yanyan-Wang  thank you saved me big time
