### ISSUE TITLE
数据更新时，registerEdge 中的afterDraw方法没触发

### ISSUE THREAD

**Issue by hb592086309** [antvis/G6#1486]
- **G6 Version**:3.4.4
- **Platform**:win
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:https://codesandbox.io/s/focused-smoke-yzcy9?file=/src/App.js

你好，请问当数据发生变化时，我调用changedata 或者updateItem 都不会触发registerEdge 中的afterDraw方法，
如demo中 ，我需要动态的改变样式，和一些自定义元素，当我测试时发现，样式会修改，但afterDraw方法没有随的数据的变化而触发，导致我在改方法中绘制的图形没有得到更新，这是为什么？

**Comment by Yanyan-Wang** [comment]
如果你的自定义节点指定了第三个参数，也就是说指定了继承某个内置节点，而自定义节点又没有复写 update 方法的话，更新会走父类 update 方法，不会走 draw 和 afterDraw。如果你要每次更新都走 draw 方法，就把 update 方法复写为 undefined，或者不继承（但是你的 demo 里需要用到父类的 getPoint 方法）

**Comment by hb592086309** [comment]
> 如果您的自定义例程指定了第三个参数，则指定被继承自另一个内置例程，而自定义例程又没有复写update方法的话，更新会走父类update方法，不会走draw和afterDraw。如果你要每次更新都走draw方法，就把update方法复写为undefined，或者不继承（但是你的demo里需要用到父类的getPoint方法）
> 
> 这里的“注意”里面有描述：[https](https://g6.antv.vision/zh/docs/manual/advanced/custom-node) ://g6.antv.vision/zh/docs/manual/advanced/custom-node[](https://g6.antv.vision/zh/docs/manual/advanced/custom-node)

感谢，我把update方法复写为undefined，解决了之前的问题。还有个问题，此时动画时间大于更新数据的频率，现在会出现动画运动到一半，从头再播放的情况，有什么办法可以在运动中更新数据吗

**Comment by Yanyan-Wang** [comment]
可以在 animate 里面指定开始的位置是上次结束的位置
