### ISSUE TITLE
节点隐藏如何同时隐藏相关的边

### ISSUE THREAD

**Issue by zhaokgithub** [antvis/G6#1487]
节点隐藏如何同时隐藏相关的边？
目前使用item.hide()实现节点的隐藏，我想要将与这个节点相关的边也隐藏应该如何操作呢？

**Comment by Yanyan-Wang** [comment]
通过 graph 来调用
graph.hideItem(item): https://g6.antv.vision/zh/docs/api/Graph#hideitemitem
