### ISSUE TITLE
G6 3.4.7通过拓展内置节点rect来自定义一个节点afterDraw 被调用了两次，这是正常的吗？

### ISSUE THREAD

**Issue by qinmao** [antvis/G6#1488]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
写在线 demo 看一下

**Comment by qinmao** [comment]
https://codepen.io/qinmao/pen/abvJmyL?editors=1111

**Comment by qinmao** [comment]
> 写在线 demo 看一下

https://codepen.io/qinmao/pen/abvJmyL?editors=1111

**Comment by Yanyan-Wang** [comment]
有两个节点当然是运行两次啦
