### ISSUE TITLE
shape.animate有API文档吗？

### ISSUE THREAD

**Issue by liuqingchao** [antvis/G6#1489]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
参考底层渲染引擎提供的相关 API：https://g.antv.vision/zh/docs/api/general/element/#%E5%8A%A8%E7%94%BB%E6%96%B9%E6%B3%95

**Comment by liuqingchao** [comment]
> 
> 
> 参考底层渲染引擎提供的相关 API：https://g.antv.vision/zh/docs/api/general/element/#%E5%8A%A8%E7%94%BB%E6%96%B9%E6%B3%95

谢谢
