### ISSUE TITLE
minimap放缩移动导致图形消失

### ISSUE THREAD

**Issue by DorothyGuan** [antvis/G6#1492]
- **G6 Version**:
3.4.7
- **Platform**:
mac chrome 81.0.4044.122
- **Mini Showcase(like screenshots)**:

样例分三个步骤：

1. 适当放缩工作区内图形，移动缩略图中框框，缩略图和图形正常联动；
1. 把工作区内图形放的很大，移动缩略图中框框，框在图形范围中可以正常联动，一旦框移动出图形范围外，工作区中的图形就完全消失了，即使再把缩略图中的框移回到图形范围内也看不到工作区内的图形了；
2. 接步骤2，再把工作区内图形放缩回正常大小（仅能靠缩略图中框的大小来判断），移动缩略图中框框，现在在工作区内已经完全看不到图形了。

[demo.mov.zip](https://github.com/antvis/G6/files/4537327/demo.mov.zip)
(我录了个简单的视频demo)

- **CodePen Link**:

官网案例：https://antv-g6.gitee.io/zh/examples/tool/minimap
或 https://codesandbox.io/s/vpmpm?file=/index.js

**Comment by Yanyan-Wang** [comment]
经排查，与 minimap 无关，只要是图形区域被平移到视野范围外，就会出现无法恢复的情况。已确定是底层渲染引擎的问题，我们会尽快修复。

**Comment by Yanyan-Wang** [comment]
可以先把局部渲染关掉临时解决这个问题：
```javascript
graph.get('canvas').set('localRefresh', false);
```
底层渲染引擎正在排期修复中。

**Comment by fancyboynet** [comment]
这个问题解决了吗

**Comment by Yanyan-Wang** [comment]
本周发小版本修复

**Comment by Yanyan-Wang** [comment]
v3.5.3 已解决。
