### ISSUE TITLE
扩展默认节点的时候能否提供一个函数支持修改节点的options

### ISSUE THREAD

**Issue by hzyhbk** [antvis/G6#1493]
现在通过 `G6.registerNode` 来扩展默认节点的时候，好像无法只修改样式，要么就只能全部重写 `options` 选项，要么就只能在数据中动态配置。

在看源码的过程中发现有个 `getShapeStyle` 方法可以使用，但是这个方法中 `const style: ShapeStyle = mix({}, defaultStyle, strokeStyle, cfg.style);` 还是从数据中获取的style。

在使用 [GGEditor](https://github.com/alibaba/GGEditor) 过程中，他的自定义节点提供了 [`getCustomConfig` ](https://github.com/alibaba/GGEditor/blob/master/src/shape/nodes/bizNode.ts#L45-L47)方法，会将这个方法返回的节点样式和 options 中设置的样式进行组合，这样我扩展默认节点的时候就可以支持只修改样式了，希望G6官方也能支持这种方式

**Comment by Yanyan-Wang** [comment]
支持的呀，可以这样写：https://codepen.io/Yanyan-Wang/pen/xxwrgVB

**Comment by hzyhbk** [comment]
@Yanyan-Wang 
您上面给出的例子是需要自己重写drawShape方法的，我的意思是类似下面这样
```js
G6.registerNode(
  'sql',
  {
    getCustomConfig(){
      return {
        size: [100, 40],
        labelCfg: {
          style: {
            fill: 'red',
          }
        }
      }
    }
  },
  'modelRect',
);
```
G6 内置的 modelRect 图形的[ options ](https://github.com/antvis/G6/blob/master/src/shape/nodes/modelRect.ts#L15-L22)配置 

通过上面的改动，这个sql自定义图形完全继承 modelRect , 就只是修改了size 和 文本样式配置。

现在的自定义方式，如果我自己重写了 sql 这个图形的 options，那 modelRect 默认的options就都不生效了。

**Comment by Yanyan-Wang** [comment]
目前这个应该只能通过全局配置或者配置到数据中了。可以考虑作为 G6 的一个新 feature。

但是因为目前有上述有替代方案，所以近期应该暂时不会排期做这个功能，非常欢迎社区共建～

**Comment by hbrls** [comment]
翻了一下代码，好像并没有用到 `options` 这个参数，白传了。

这段代码是无效的：

```
G6.registerNode(
    'mycircle',
    {
        options: {
            size: 40,
            style: {
                fill: 'red',
            }
        }
    },
    'circle',
);
```

这段代码是有效的：

```
const REGISTER_NODE_OPTIONS = {
    options: {
        size: 40,
        style: {
            fill: 'red',
        }
    }
};
const formattedNodes = nodes.map(n => {
    const formatted = Object.assign({}, n);
    if (n.type === 'mycircle') {
        Object.assign(formatted, REGISTER_NODE_OPTIONS);
    }
    return formatted;
});
```
