### ISSUE TITLE
arc type cursor pointer 不生效且无法监听到鼠标事件

### ISSUE THREAD

**Issue by Enivia** [antvis/G6#1495]
- **G6 Version**:3.4.7
- **Platform**:windows
- **CodePen Link**:https://codesandbox.io/s/boring-bartik-pj7m4?file=/src/App.js

**Comment by Yanyan-Wang** [comment]
经排查，底层渲染引擎关于带有 'A' 的路径拾取和事件有问题，正在加紧修复中，可以先使用 quadratic 代替。

**Comment by Yanyan-Wang** [comment]
当前版本(3.x、4.x)暂时不会考虑 SVG 问题的修复，底层渲染引擎正在大升级，我们也将在新版本接入新渲染引擎，届时应当可以解决 SVG 各种 bug
