### ISSUE TITLE
自定义endArrow 无法添加stateStyle ?

### ISSUE THREAD

**Issue by CoderPXin** [antvis/G6#1496]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

codesandbox : https://codesandbox.io/s/blue-architecture-dyqw9?file=/index.js

![image](https://user-images.githubusercontent.com/10238526/80352852-13b89000-88a7-11ea-92ab-f466da4bf01b.png)

**Comment by CoderPXin** [comment]
不为endArrow设置fill和storke就可以跟着边的属性改变

**Comment by xialvjun** [comment]
只为 endArrow 设置 path, 不设置 fill 和 stroke, 也不会让其跟着边的属性改变...自己主动设置 stateStyle 也无效.... 只有在 设置 `defaultEdge.style.endArrow = true` 时, 其才会随边的属性改变.
