### ISSUE TITLE
一部分节点位置固定，另外的不固定且分散均匀不重叠，如何实现？

### ISSUE THREAD

**Issue by liuqingchao** [antvis/G6#1498]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

不固定的节点最好是力导向效果那种，分布在父节点周围，均匀不重叠

**Comment by Yanyan-Wang** [comment]
使用力导向布局，想要固定的节点设置 fx fy 为你想要固定的位置

这个例子是拖动后固定位置，可以参考一下
https://g6.antv.vision/zh/examples/net/forceDirected#basicForceDirectedDragFix_

**Comment by gongpingwa00** [comment]
![image](https://user-images.githubusercontent.com/23349869/207002937-d6b5ad3f-a579-48b0-95cd-c10d840e2fad.png)
为什么拖动节点时其他节点不跟着被拖动的节点走呢,而是向着相反的方向走,这个有什么解决办法吗,比如边长默认为150,拖动0节点时其他节点都在0节点周围150的位置

**Comment by gongpingwa00** [comment]
![image](https://user-images.githubusercontent.com/23349869/207002937-d6b5ad3f-a579-48b0-95cd-c10d840e2fad.png)
为什么拖动节点时其他节点不跟着被拖动的节点走呢,而是向着相反的方向走,这个有什么解决办法吗,比如边长默认为150,拖动0节点时其他节点都在0节点周围150的位置
