### ISSUE TITLE
建议官网给出类似绘制复杂节点的例子

### ISSUE THREAD

**Issue by aoto** [antvis/g6#150]
如：
![image](https://user-images.githubusercontent.com/2315342/35134175-a30fdb80-fd0f-11e7-90d7-0740b130426e.png)
类似设计在中后台系统中很常见。

现在官网的例子是这样的：
![image](https://user-images.githubusercontent.com/2315342/35134211-dd9f1360-fd0f-11e7-9d62-203fca138dcf.png)

是不是有点随意了。

谢谢

**Comment by TomHuangCN** [comment]
1. 教程只是给出一个思路，用户自行举一反三，不需要多复杂。
2. 复杂案例见 Demo Gallery
  * https://antv.alipay.com/zh-cn/g6/1.x/demo/gallery/iris-flower.html
  * https://antv.alipay.com/zh-cn/g6/1.x/demo/gallery/us-cpi.html
  * https://antv.alipay.com/zh-cn/g6/1.x/demo/gallery/sequence.html

**Comment by richard1225** [comment]
是不打算维护了吗？3.0的文档一塌糊涂。不行就直接关了，不要浪费大家的学习时间了好不好？

**Comment by baizn** [comment]
@richard1225  [3.0的文档](https://www.yuque.com/antv/g6/default-node)哪里有问题，麻烦具体指出来一下，文档中存在的不足，我们会不断改善，多谢！

**Comment by richard1225** [comment]
> @richard1225 [3.0的文档](https://www.yuque.com/antv/g6/default-node)哪里有问题，麻烦具体指出来一下，文档中存在的不足，我们会不断改善，多谢！

最简单的来说，我无法从文档中找到怎么给cubic加箭头，api样例里面全是函数名了事，怎么调用example都没有。。。还有神奇的shape参数，2.0有，3.0突然又没了，给的demo又是2.0了。。

**Comment by richard1225** [comment]
真的。。光看文档的话，恐怕只有你们内部人士能看懂了

**Comment by richard1225** [comment]
我说的加箭头当然不是在数据上加，是在registerEdge里面加，找了半天没找到，样式配置attr怎么写也没有个详细说明，这不是最基本的吗？

**Comment by baizn** [comment]
3.0 里面没有registerEdge，目前官网上的demo样式上可能和2.0的类似，实现都是使用3.0实现的，样式里面所有可配置的都在这里：https://www.yuque.com/antv/g6/gs4gno
