### ISSUE TITLE
当连线(Edge)样式包含lineDash时，箭头(Arrow)渲染异常

### ISSUE THREAD

**Issue by guozhaolong** [antvis/G6#1500]
- **G6 Version**: 3.4.7
- **Platform**: Chrome 81
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

![image](https://user-images.githubusercontent.com/1046601/80440952-67c18400-893c-11ea-9dbc-ec6bf46eb788.png)
```
getShapeStyle(cfg) {
  ........
  return {
    path,
    ...style,
    lineDash: [5,5],
    endArrow: {
      path: 'M 0,0 L 6,-2 Q 5 0,6 2 Z'
    }
  }
}
```

**Comment by Yanyan-Wang** [comment]
可以配置一下 endArrow 的样式。若不配置默认会使用边的样式

```javascript
endArrow: {
   path: 'M 0,0 L 6,-2 Q 5 0,6 2 Z',
   fill: '#F6BD16',
   lineDash: [0, 0],
}
```
