### ISSUE TITLE
如何在初始化时让所有节点都隐藏？

### ISSUE THREAD

**Issue by liuqingchao** [antvis/G6#1501]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
如果你想全图隐藏，可以直接把 graph 的根图形分组整个隐藏： graph.get('group').hide()。但是后面要显示的时候也要把这个 group 先 show 出来： graph.get('group').show()。

如果不是全图隐藏，在 graph.render 之后遍历节点去隐藏：
```javascript
// ...
graph.render();
graph.getNodes().forEach(node => {
  graph.hideItem(node); // 隐藏节点的同时隐藏相关边
  // node.hide(); // 仅隐藏节点本身，相关边不受到影响
});
```
关于 graph.hideItem 和 item.hide API 参见:
https://g6.antv.vision/zh/docs/api/Graph#hideitemitem
https://g6.antv.vision/zh/docs/api/nodeEdge/Item#hide
