### ISSUE TITLE
Feature Request: Search Box to focus on Node

### ISSUE THREAD

**Issue by dit7ya** [antvis/G6#1504]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

Thanks for this amazing project. Would it be possible to have a search box that would let us focus a node by reorganizing the layout to put it in the center?

Also, I noticed that note labels are not searchable using the regular browser search tools. Is there a way to circumvent it?

**Comment by Yanyan-Wang** [comment]
G6 provides the [graph.focus(node)](https://g6.antv.vision/en/examples/interaction/position) API for translating the graph to make the focused node in the center. 

Also, we have the [radial layout](https://g6.antv.vision/en/examples/net/radialLayout#basicRadial) to make the other nodes to be placed around the focused node according to their shortest path lengths.

And the [graph search API)](https://g6.antv.vision/en/docs/api/Graph#findtype-fn) may help you to search a node or an edge by its id.

About the search box, it is out of the range of G6. But it will be easy to use a DOM input box to combine the abilities above to implement the 'node/edge search box'.
