### ISSUE TITLE
rect类型分组未完全包裹住所有的节点和边

### ISSUE THREAD

**Issue by Tronsfey** [antvis/G6#1505]
- **G6 Version**:latestest 3.4.8
- **Platform**: mac
- **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/4178124/80485166-7aaf7500-898b-11ea-914a-bb3181b0b656.png)

- **CodePen Link**:
https://codesandbox.io/s/nice-shaw-1rnhf?file=/index.js

**Comment by Yanyan-Wang** [comment]
目前节点分组考虑其大小时仅考虑内部节点的 keyShape。可以通过在实例化图时配置 groupStyle 里的下面这些参数调整节点分组的边距：
```javascript
const graph = new G6.Graph({
  // ... 其他配置项
  groupStyle: { // 节点分组的样式
    default: { // 节点分组在无状态下的默认样式
      disCoefficient: 2,
      minDis: 100,
      maxDis: 100,
    }
  },
});
```
