### ISSUE TITLE
Violation of Content Security Policy due to numericjs

### ISSUE THREAD

**Issue by albrechtjohannes** [antvis/G6#1506]
- **G6 Version**: 3.4.8
- **Platform**: Chrome 81
- **Mini Showcase(like screenshots)**: 
<img width="896" alt="Screen Shot 2020-04-28 at 14 43 15" src="https://user-images.githubusercontent.com/553521/80488827-40c87980-895f-11ea-8116-f3eba3b52339.png">

For the mds layouting algorithm, G6 makes use of numericjs. The numericjs uses the Function() constructor in many places and this leads to the issue displayed in the screenshot. Do you know if the numericjs dependency can be removed easily, as it is only used in 2 places? 

Thanks and best regards

**Comment by Yanyan-Wang** [comment]
The numericjs is required. Maybe this error can be addressed by configuring your project.

**Comment by albrechtjohannes** [comment]
The only option I see is, to add unsafe-eval to the CSP headers or removing the CSP headers completely, which is both forbidden by our security guidelines as it makes the site more vulnerable.

**Comment by adelyafatykhova** [comment]
@Yanyan-Wang we did some more research into numericjs and believe it would be valuable for g6 to replace it with [ml-matrix](https://www.npmjs.com/package/ml-matrix).

Please see pull request #1577 for more details.

Using ml-matrix, not only does the graph become CSP compliant, but there are also improvements in terms of typescript support, maintenance, and the SVD algorithm.

**Comment by Yanyan-Wang** [comment]
Thank you @adelyafatykhova .

The problem is solved by 3.5.1.
