### ISSUE TITLE
svg，更改数据源时调用clear，箭头丢失

### ISSUE THREAD

**Issue by Enivia** [antvis/G6#1508]
- **G6 Version**:3.4.8
- **Platform**:windows
- **CodePen Link**:https://codesandbox.io/s/amazing-bose-wo0hg?file=/src/App.js

更新数据源时方法调用：`clear()`,`changeData()`,`refresh()`

**Comment by Yanyan-Wang** [comment]
changeData 不需要调用 graph.clear() 以及 graph.refresh() ，调用 changeData 就可以完成数据更换和图的刷新。

svg 渲染方式下画布清空后再添加带箭头图形确实有问题，已经报给底层同学。不过这个应该不影响你这里的使用，只需要调用 changeData 即可。
