### ISSUE TITLE
Treegraph will not use TreeGraphData.data as nodeconfig

### ISSUE THREAD

**Issue by Kacxxia** [antvis/G6#1509]
- **G6 Version**:  3.4.4
- **Platform**: windows10
- **Mini Showcase(like screenshots)**:
![1](https://user-images.githubusercontent.com/15980971/80560602-20a6c200-8a14-11ea-8ade-73690a0de8d1.png)
![2](https://user-images.githubusercontent.com/15980971/80560590-108ee280-8a14-11ea-824d-4863f5d05b78.png)

- **CodePen Link**:
https://g6.antv.vision/en/examples/tree/dendrogram#basicDendrogram

As the first screenshot shows, Treegraph is actually using TreeGraphData itself as nodeconfig, maybe we should improve the TreeGraphData type definition(screenshot 2)

**Comment by Yanyan-Wang** [comment]
You are right, thanks. We will improve it in next small version.

**Comment by weichaozhan** [comment]
> You are right, thanks. We will improve it in next small version.
What's the reason for interface **TreeGraphData** does not have a **type** attribute

**Comment by Yanyan-Wang** [comment]
Fixed by v3.4.10.
