### ISSUE TITLE
Force Layout中通过addItem增加的节点不指定x和y时，会出现边交叉的情况，如何避免？

### ISSUE THREAD

**Issue by liuqingchao** [antvis/G6#1510]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by liuqingchao** [comment]
layout: {
        type: 'force',
        preventOverlap: true
      }
addItem后有几率出现节点重叠的情况

**Comment by Yanyan-Wang** [comment]
addItem 不会触发重新布局，需要手动调用一下 graph.layout()

**Comment by liuqingchao** [comment]
加了graph.layout()了，不加的话，addItem的节点不显示
但是边和节点还是会重叠，有没有节点分布的算法啊？

**Comment by Yanyan-Wang** [comment]
写个在线 demo 看一下

**Comment by liuqingchao** [comment]
不会，没写过，自己写了个算法，效果还行

**Comment by yfzm01** [comment]
addItem之后直接updateLayout换一个布局，没起作用，该如何解决
