### ISSUE TITLE
自定义边动画里，onFrame(ratio)用不了

### ISSUE THREAD

**Issue by slsasa** [antvis/G6#1513]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by slsasa** [comment]
自定义边动画里，onFrame(ratio)用不了
G6 Version: ^2.2.6

**Comment by Yanyan-Wang** [comment]
建议尽快升级到最新。最新版本动画的用法：https://g6.antv.vision/zh/docs/manual/advanced/animation#%E8%BE%B9%E5%8A%A8%E7%94%BB
