### ISSUE TITLE
I see that API changes frequently between versions, so which version should I choose in production use.

### ISSUE THREAD

**Issue by seymoe** [antvis/G6#1514]
- **G6 Version**: 3.4.8
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

目前官网 默认是 3.4.8 的文档，是否意味着可以直接使用 3.4.x 作为生产投入，因为注意到版本间的API变动很大，特别是在自定义相关的变动很大，比如我想自定义锚点、给锚点加 behavior，找不到
能够使用的示例或代码参考，一些开源代码是基于3.0版本的无法使用。

**Comment by baizn** [comment]
3.2 与 3.3 区别较大，3.3 以上都是兼容的，具体参考这里：https://g6.antv.vision/zh/docs/manual/FAQ/upgradeGuide

**Comment by seymoe** [comment]
@baizn 已经找到了我想要实现的效果的解决方法，感谢回复，先关了。
