### ISSUE TITLE
3.4.7版本后changeData会导致元素原有state丢失

### ISSUE THREAD

**Issue by Enivia** [antvis/G6#1515]
- **G6 Version**:3.4.7+
- **Platform**:windows
- **CodeSandBox**:https://codesandbox.io/s/dynamic-data-test-nl3x0?file=/package.json

**Comment by baizn** [comment]
(⊙o⊙)… https://github.com/antvis/G6/issues/1357  正常情况下changeData 后不应该保留原有状态 ，因为changeData后有某个state的节点可能都会不存在。如果changeData后还需要保留指定节点的state，可以在changeData前缓存state值，changeData后使用 graph.setItemState(item, 'stateName', true) 恢复。
