### ISSUE TITLE
React build failing on including antv g6 latest version

### ISSUE THREAD

**Issue by renjiie** [antvis/G6#1517]
- **G6 Version**: "@antv/g6": "^3.4.8",
- **Platform**: "linux"
- **Mini Showcase(like screenshots)**: 
```[INFO] Creating an optimized production build...
[INFO] Failed to compile.
[INFO] 
[INFO] Failed to minify the code from this file: 
[INFO] 
[INFO]          ./node_modules/@antv/g6/dist/g6.min.js:16:183001 
```
During the react build the antvg6 failed to minify and causing issues .
My dependencies :
```
"@antv/data-set": "^0.11.4",
 "@antv/g6": "^3.4.8",
"react": "^16.5.2",
"react-dom": "^16.5.2",
"sass-loader": "^7.1.0",
"style-loader": "0.19.0",
"styled-components": "^4.4.1",
"webpack": "3.8.1",
"webpack-dev-server": "2.11.3",
```

**Comment by Yanyan-Wang** [comment]
Try the latest version v4.0.3 pls

**Comment by Yanyan-Wang** [comment]
Hi, dear user. Since there was no response for a long time, we cannot figure out the answer of the problem you described. If there is new progress, feel free to open a new issue.
