### ISSUE TITLE
ES6 syntax in G6.min.js breaks IE11 support

### ISSUE THREAD

**Issue by Zangr** [antvis/G6#1522]
- **G6 Version**:
3.4.4
- **Platform**:
IE11, Any OS
- **Mini Showcase(like screenshots)**:

**JS Error in IE11**
<img width="396" alt="Screen Shot 2020-05-01 at 6 03 24 PM" src="https://user-images.githubusercontent.com/6811562/81028757-9907eb80-8e37-11ea-9512-347d69945f60.png">

**Cause**
```
  "main": "lib/index.js",
  "module": "es/index.js",
  "browser": "dist/g6.min.js", // <====== I will break your IE11 support ^-^
```

Current package.json of G6 includes a "browser" config that takes precedence over "main" and "module" when we include g6 as a dependency on a web project. Unfortunately, there is an arrow function usage in "dist/g6.min.js" from its dependency d3-force introduced in [this commit](https://github.com/antvis/G6/commit/e42e8d950a257fb0bba99cfe06b5b109eda17f25). Arrow function is not supported by IE11 so the bundle JS file will error out. As G6 claims to support IE11, we should find a way to fix it. 

References:
https://github.com/webpack/webpack/issues/4674
https://github.com/defunctzombie/package-browser-field-spec

**Proposed Solution**
I think we should either transpile d3-force artifacts when we build g6.min.js or remove the "browser" config completely. I'm not sure why we need to directly use g6.min.js since it will introduce duplication of code from commonly used libraries like lodash, d3, etc to the bundle depending on G6. I'd appreciate it if someone can explain more here.

**Workaround**
If you are using ejected Webpack config you can add a rule to skip “browser” config as the one shown below:
```
{
  test: /@antv\/g6/,
  loader: require.resolve('babel-loader'),
  resolve: { mainFiles: ['module', 'main'] },
}
```
If that does not work for you, you can try options provided [here](https://g6.antv.vision/en/docs/manual/FAQ/supportIE).

cc @chenshuai2144 @Yanyan-Wang

**Comment by baizn** [comment]
please upgrade to version 3.4.9 https://github.com/antvis/G6/pull/1541

**Comment by Zangr** [comment]
Thank you @baizn for the quick fix. Closing this issue.
