### ISSUE TITLE
react里怎么初始化G6

### ISSUE THREAD

**Issue by jmolboy** [antvis/g6#153]
react里怎么初始化G6

**Comment by TomHuangCN** [comment]
原生 js 怎么初始化，就怎么初始化呗。

看下这个：https://codesandbox.io/s/p3jry6w230

**Comment by leavest** [comment]
> 原生 js 怎么初始化，就怎么初始化呗。
> 
> 看下这个：https://codesandbox.io/s/p3jry6w230

想学习一下怎么在react里初始化G6，链接打开就报错
![image](https://user-images.githubusercontent.com/30454841/51669865-520a3400-2000-11e9-9ee0-e047fcaa6219.png)

**Comment by trexguo** [comment]
最新版API已经改了，没有G6.Net了 @leavest
