### ISSUE TITLE
拖动画布和鼠标在节点上的时候怎么把鼠标变成小手状？

### ISSUE THREAD

**Issue by orzzt** [antvis/G6#1533]
拖动画布的时候或者是鼠标移动到节点上的时候如何能够让鼠标拥有cursor: pointer的效果？
G6版本：3.4.1

**Comment by baizn** [comment]
https://g6.antv.vision/zh/docs/api/shapeProperties/#%E9%80%9A%E7%94%A8%E5%B1%9E%E6%80%A7
shape.attr('cursor', 'pointer')
