### ISSUE TITLE
网图部署中的一些问题

### ISSUE THREAD

**Issue by evilxh** [antvis/g6#154]
1.网图编辑中，在画布上的某个区域禁止绘制节点！在确定区域后，在生命周期函数里面注册节点的时候区域进行判断，但是该节点只是不显示在画布上，但是在实际该节点数据是存在的，在保存的时候此数据依然存在；
`
 G6.registerNode('rect', {
        draw(cfg, group) {
            if (cfg.model.x < 800) {
                const width = cfg.size ? cfg.size[0] : 80;
                const height = cfg.size ? cfg.size[1] : 80;
                const shape = group.addShape('rect', {
                    attrs: {
                        x: cfg.x - width / 2,
                        y: cfg.y - height / 2,
                        width, //根据实际拖拽的大小来处理
                        height, //根据实际拖拽的大小来处理
                        fill: cfg.model.color,
                        stroke: 'black',
                    }
                });
                drawText(cfg, group);
                return shape;
            }else{
                alert('此区域不能绘制图形')
            }
        },
        AnchorPoints
    }, 'rect');
`
2.节点之间的关系使用arrow来连接，怎么样实现某两个节点禁止连接

**Comment by TomHuangCN** [comment]
1. draw 方法里本来就不该做这种事情
2. https://codepen.io/DoriTong/pen/yPRqOv

**Comment by evilxh** [comment]
非常感谢！那在画布的某一个区域禁止拖入节点或者不能生成节点，怎样处理比较好

**Comment by TomHuangCN** [comment]
```js
net.on('itemadd', ev=>{
  const item = ev.item;
  const model = item.getModel();
  net.remove()  // 判断一下  model.x、model.y remove 一下
});
```

**Comment by evilxh** [comment]
谢谢 通哥!问题已经处理，还有个问题请教下!
我给两个节点用arrow 连接起来，怎样在连接结束后，通过判断让这个连接线arrow 变色（update（））？ 非常感谢

**Comment by TomHuangCN** [comment]
监听一下 dragedgeend

参考一下这个例子：https://codepen.io/DoriTong/pen/yPRqOv
