### ISSUE TITLE
官网代码演示 2 ：自定义带有收缩/扩展按钮的节点的代码有bug

### ISSUE THREAD

**Issue by hanshanfeixue** [antvis/G6#1540]
https://g6.antv.vision/zh/examples/tree/customItemTree#customTree，该部分提供的demo代码，在父节点点击关闭之后，子节点的开合状态会被覆盖；复现步骤：点击节点B闭合，点击B的父节点A闭合，再点击A打开，这时候会发现B节点是开合状态但是B没有子元素，这时候点击B，会展开子元素C，此时B的按钮开合状态没变，依然是开图标。

**Comment by Yanyan-Wang** [comment]
Fixed by v3.4.10.
