### ISSUE TITLE
请问如何在自定义node中获取graph对象

### ISSUE THREAD

**Issue by rainrcn** [antvis/G6#1542]
请问如何在自定义node中获取graph对象，特别是在draw方法内想要获取graph对象

**Comment by baizn** [comment]
获取不到，draw 时可能还没有实例化 Graph，问题是你在 draw 中获取 graph 对象干嘛呢？

**Comment by huangmb** [comment]
同一楼，我这边是在draw方法中某些自定义事件动态更新节点尺寸，并且调整树图的布局，需要treeGraph的refreshLayout方法
