### ISSUE TITLE
Bug: Edge Type "quadradic" does not follow a symmetrical curve

### ISSUE THREAD

**Issue by raray** [antvis/G6#1544]
**G6 Version**: 3.4.9

**Platform**: Mac Chrome

**Screenshot**: 
![image](https://user-images.githubusercontent.com/1738632/81422198-4456c000-9118-11ea-9def-0c02ba476b90.png)

**CodeSandbox Link**: https://codesandbox.io/s/magical-wilbur-zgzx3?file=/index.js

**Steps to reproduce:**
1. Create an edge with type `'quadradic'` with a `curveOffset` > `0`.

**Expected Result**:
A quadratic curve whose apex is equidistant from each endpoint.

**Actual Result**:
The apex of the curve is biased towards one endpoint.

**Comment by Yanyan-Wang** [comment]
Thanks, we have located the problem and it will be solved next in version 3.4.10.

**Comment by Yanyan-Wang** [comment]
Fixed by v3.4.10.
