### ISSUE TITLE
请问如何保持一个一直可连线的状态？

### ISSUE THREAD

**Issue by Jarryham** [antvis/g6#155]
网图编辑需要进行节点间的连线时，需要促发按钮然后绘制线，但是只能绘制一次，再一次绘制，需要再次促发按钮才能绘制，有没办法保持可连线的状态，而不需要再次点击按钮？
https://antv.alipay.com/zh-cn/g6/1.x/demo/other/editor.html

**Comment by TomHuangCN** [comment]
https://antv.alipay.com/zh-cn/g6/1.x/demo/editor/editor-extend1.html

**Comment by zarte** [comment]
@TomHuangCN  你好这个文档有备份站吗？现在打不开了
