### ISSUE TITLE
TreeGraph 使用updateItem更新节点数据后 save获取到的数据还是原来的数据

### ISSUE THREAD

**Issue by wleven** [antvis/G6#1551]
- **G6 Version**:3.4.9
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:https://codepen.io/wleven/pen/KKdoOgd

 TreeGraph 
 使用updateChild更新的话，源数据已经更新，但是页面没有刷新
 使用updateItem更新的话，页面显示数据已经更新，但是 save获取到的数据还是原来的数据

**Comment by Yanyan-Wang** [comment]
树图用 updateChild 比较合理，这样写可以更新：

```javascript
graph.on("node:click", (evt) => {
  const node = evt.item;
  const model = node.getModel();
  graph.updateChild({ label: "123" }, model.parent);
// 此处该节点本身就是根节点，所以也可以直接写 graph.updateChild({ label: "123" });
  const d = graph.save();
  console.log(d);
});
```

**Comment by wleven** [comment]
> 树图用 updateChild 比较合理，这样写可以更新：
> 
> ```js
> graph.on("node:click", (evt) => {
>   const node = evt.item;
>   const model = node.getModel();
>   graph.updateChild({ label: "123" }, model.parent);
> // 此处该节点本身就是根节点，所以也可以直接写 graph.updateChild({ label: "123" });
>   const d = graph.save();
>   console.log(d);
> });
> ```

如果子节点的话 model.parent是undefined

**Comment by Yanyan-Wang** [comment]
如果数据中没有记录 parent，那么可以通过 node.get('parent') 拿到父节点实例。

这个问题的解法详见 #1554
