### ISSUE TITLE
rect类型节点是否可以在属性中设置，只显示某一个border?

### ISSUE THREAD

**Issue by lvyong** [antvis/G6#1552]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
可以在 style 里设置 fillOpacity: 0 让填充透明
https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/rect/#%E6%A0%B7%E5%BC%8F%E5%B1%9E%E6%80%A7-style
