### ISSUE TITLE
TreeGraph 子节点数据应该怎么更新,使用updateChild还是updateItem,有点迷惑

### ISSUE THREAD

**Issue by wleven** [antvis/G6#1554]
- **G6 Version**:3.4.9
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:https://codepen.io/wleven/pen/KKdoOgd

#1322 这里说更新现有节点的样式、文本等直接使用 graph.updateItem(item, model)。
updateChild 这个主要用来增删子节点。

那我就用updateItem来更新，发现#1551 这个问题,这里又说树图用 updateChild 比较合理

然后我就有点蒙了,有几个问题

问题1：不管是根节点还是子节点 `model.parent` 返回值都是`undefined`,这样做的话整棵树都会更新掉
```
graph.on("node:click", (evt) => {
  const node = evt.item;
  const model = node.getModel();
  graph.updateChild({ label: "123" }, model.parent);
// 此处该节点本身就是根节点，所以也可以直接写 graph.updateChild({ label: "123" });
  const d = graph.save();
  console.log(d);
});
```

问题2：如果只更新某一个子节点,使用`updateChild`的话页面视图不更新,save拿到的数据还是更新前的数据，要第二次触发`node:click`事件`save`才能获取到更新后的数据,这里应该怎么处理

```
graph.on("node:click", (evt) => {
  const node = evt.item;
  const model = node.getModel();
  console.log({parent:model.parent})
  graph.updateChild({ label: "123",id:"1" }, "root");
  console.log(graph.save());
});
```
问题3: 更新子树的数据到底用`updateChild`还是`updateItem`,现在这两个方式都有问题,
使用updateChild更新子节点的话，数据第二次触发才拿到新数据，而且视图没有刷新
使用updateItem更新子节点的话，页面显示数据已经更新，但是 save获取到的数据还是原来的数据

**Comment by Yanyan-Wang** [comment]
感谢你的 issue，#1551 中的解释确实不妥。下面解释可能会更清晰一些：

> 不管是根节点还是子节点 model.parent 返回值都是 `undefined`

抱歉，上面写法有误，如果数据中没有记录 `parent`，那么可以通过 `node.get('parent')` 拿到父节点实例；

### 关于 save
树图与一般图 `save` 逻辑不同，一般图 `save` 时会遍历所有元素拿到每一个元素的 model https://github.com/antvis/G6/blob/d4b4feb2c55bf5f139754acf5e28ada13d5e4071/src/graph/graph.ts#L1087
但树图只是返回原数据 `graph.get('data')`
https://github.com/antvis/G6/blob/d4b4feb2c55bf5f139754acf5e28ada13d5e4071/src/graph/tree-graph.ts#L554


### 关于 updateItem
树图数据结构与一般图的数据结构有所不同，因此在设计时，树图的 `updateItem` 不会将新内容写入原数据 `graph.get('data')`
```javascript
graph.on("node:click", (evt) => {
  const node = evt.item;
  // 不会触发重新布局，只会更新响应节点的样式
  graph.updateItem(node, {
    label: '123'
  })
  console.log(save());
});

const save = () => {
  const nodes = [], edges = []
  graph.getNodes().forEach(node => {
    nodes.push(node.getModel());
  });
  graph.getEdges().forEach(edge => {
    edges.push(edge.getModel());
  });
  return { nodes, edges };
}
```

### 关于 updateChild
`updateChild` 会更新以 `parent` 为根的全部子树，所以要获取到整个子树的数据，在里面找到需要修改的部分。这样会比较麻烦。但是因为修改了数据，所以 `graph.save()` 的时候返回的数据是修改过的
```javascript
graph.on("node:click", (evt) => {
   const node = evt.item;
   const model = node.getModel();
   const parent = node.get('parent');
   const subtree = parent.getModel();
   subtree.children[0].label = '123';
 // updateChild 会触发图的重新布局
   graph.updateChild(subtree, parent.id);
   console.log(graph.save());
});
```

详见：https://codepen.io/Yanyan-Wang/pen/abvKOxx

**Comment by wleven** [comment]
> 感谢你的 issue，#1551 中的解释确实不妥。下面解释可能会更清晰一些：
> 
> > 不管是根节点还是子节点 model.parent 返回值都是 `undefined`
> 
> 抱歉，上面写法有误，如果数据中没有记录 `parent`，那么可以通过 `node.get('parent')` 拿到父节点实例。
> 
> ### 关于 save
> 树图与一般图 `save` 逻辑不同，一般图 `save` 时会遍历所有元素拿到每一个元素的 model
> 
> https://github.com/antvis/G6/blob/d4b4feb2c55bf5f139754acf5e28ada13d5e4071/src/graph/graph.ts#L1087
> 
> 
> 但树图只是返回原数据 `graph.get('data')`
> https://github.com/antvis/G6/blob/d4b4feb2c55bf5f139754acf5e28ada13d5e4071/src/graph/tree-graph.ts#L554
> 
> ### 关于 updateItem
> 树图数据结构与一般图的数据结构有所不同，因此在设计时，树图的 `updateItem` 不会将新内容写入原数据 `graph.get('data')`
> 
> ```js
> graph.on("node:click", (evt) => {
>   const node = evt.item;
>   // 不会触发重新布局，只会更新响应节点的样式
>   graph.updateItem(node, {
>     label: '123'
>   })
>   console.log(save());
> });
> 
> const save = () => {
>   const nodes = [], edges = []
>   graph.getNodes().forEach(node => {
>     nodes.push(node.getModel());
>   });
>   graph.getEdges().forEach(edge => {
>     edges.push(edge.getModel());
>   });
>   return { nodes, edges };
> }
> ```
> 
> ### 关于 updateChild
> `updateChild` 会更新以 `parent` 为根的全部子树，所以要获取到整个子树的数据，在里面找到需要修改的部分。这样会比较麻烦。但是因为修改了数据，所以 `graph.save()` 的时候返回的数据是修改过的
> 
> ```js
> graph.on("node:click", (evt) => {
>    const node = evt.item;
>    const model = node.getModel();
>    const parent = node.get('parent');
>    const subtree = parent.getModel();
>    subtree.children[0].label = '123';
>  // updateChild 会触发图的重新布局
>    graph.updateChild(subtree, parent.id);
>    console.log(graph.save());
> });
> ```
> 
> 详见：https://codepen.io/Yanyan-Wang/pen/abvKOxx
感谢~~~~
