### ISSUE TITLE
minimap插件显示位置不准bug 。

### ISSUE THREAD

**Issue by sl798970799** [antvis/G6#1556]
文档minimap地址
https://g6.antv.vision/zh/examples/tool/minimap/#%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97
缺陷描述：
minimap插件显示位置不准bug 。
操作步骤
1先把画布缩小 
2一直拖拽到最右边
3再把画布方法
4再把画布拖回 ，画布一片空白。

**Comment by Yanyan-Wang** [comment]
合并到 #1492
