### ISSUE TITLE
是否有计划支持鱼骨图?

### ISSUE THREAD

**Issue by dd1994** [antvis/G6#1559]
鱼骨图也是一种挺常用的图

**Comment by Yanyan-Wang** [comment]
暂时没有排期，可以通过自定义布局完成

**Comment by yanzhangshuai** [comment]
请问有鱼骨图的自定义布局Demo吗

**Comment by yanzhangshuai** [comment]
> 暂时没有排期，可以通过自定义布局完成

请问你们有鱼骨图的自定义布局Demo吗

**Comment by yumaopiaoa** [comment]
![1668153345209](https://user-images.githubusercontent.com/34874601/201292972-0157e8d3-353d-448d-9454-11f5572d0016.png)
想做个这样的鱼骨图，但是好像没有案例

**Comment by shoushou70** [comment]
> 但是好像没有案例

请问，你们后面实现了鱼骨图吗？用啥实现的
