### ISSUE TITLE
使用React next.js框架引入G6报错

### ISSUE THREAD

**Issue by ZhangWeiIBM** [antvis/g6#156]
import G6 from '@antv/g6';

ReferenceError: document is not defined

**Comment by ZhangWeiIBM** [comment]
补充说明：next.js 是react的一个服务器端渲染框架，在服务器端自然找不到全局对象document, 现在我个人的解决方案是在componentDidMount()生命周期中fetch一个静态html，不知道Antd官方是否能出一个解决方案。

**Comment by TomHuangCN** [comment]
G6 没有考虑服务端渲染

**Comment by 2012shenghua** [comment]
不用那么麻烦的， dynamic导入就可以了

**Comment by 2012shenghua** [comment]
不用那么麻烦的， dynamic导入就可以了

**Comment by 2012shenghua** [comment]
不用那么麻烦的， dynamic导入就可以了
