### ISSUE TITLE
Bug: Edge type "quadratic" produces irregular results when combined with layout type "circular"

### ISSUE THREAD

**Issue by raray** [antvis/G6#1561]
**G6 Version**: 3.4.9

**Platform**: Mac Chrome

**Screenshot**: 
![image](https://user-images.githubusercontent.com/1738632/81706557-b8090d80-9435-11ea-821b-3fc6b651d551.png)

**CodeSandbox Link**: https://codesandbox.io/s/serverless-currying-e7i1k?file=/index.js

**Steps to reproduce:**
1. Create a graph with layout type "circular"
2. Add 4 nodes
3. Create edges of type "quadratic" between different pairs of nodes with a `curveOffset` > 0.

**Expected Result**:
The curves of the edges should have equivalent shapes.

**Actual Result**:
One curve has a much smaller offset than the other

Possibly related to #1544.

**Comment by Yanyan-Wang** [comment]
Fixed by v3.4.10.
