### ISSUE TITLE
节点的类型是type还是shape？

### ISSUE THREAD

**Issue by weishell** [antvis/G6#1564]
在https://g6.antv.vision/zh/docs/manual/tutorial/elements 中数据结构中标注的节点元素的类型是type，但是使用type会无效果，在https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/defaultNode 上显示的又是shape

**Comment by weishell** [comment]
在 https://g6.antv.vision/zh/docs/manual/tutorial/elements 中数据结构中标注的节点元素的类型是type，但是使用type会无效果，在https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/defaultNode  上显示的又是shape

**Comment by Yanyan-Wang** [comment]
新版本推荐使用 type 来指定，shape 也是兼容的，但以后会被废弃。在旧版本（3.3 之前）中是用 shape 指定的。你用的是哪个版本的 G6？

**Comment by weishell** [comment]
> 新版本推荐使用 type 来指定，shape 也是兼容的，但以后会被废弃。在旧版本（3.3 之前）中是用 shape 指定的。你用的是哪个版本的 G6？
那就对了，我用的低于3.3，是照着官网上看的，3.1.0，明白了，谢谢。
