### ISSUE TITLE
节点固定位置设置无效

### ISSUE THREAD

**Issue by zhaokgithub** [antvis/G6#1565]
使用fruchterman布局想要初始化图时候，实现某两个节点位置固定，其他节点按fruchterman分布，但是将两个节点设置x y坐标后仍然按照不规则布局

找到官方文档中一句话：
当实例化图时没有配置 layout 时：
若数据中节点有位置信息（x 和 y），则按照数据的位置信息进行绘制；
若数据中节点没有位置信息，则默认使用 Random Layout 进行布局。

那这个意思是如果我layout中使用的fruchterman布局的化是不是我自定义位置就无法实现了呢？

**Comment by Yanyan-Wang** [comment]
若实例化图时配置了布局，无论数据中节点有无位置信息，都会按照布局来确定位置。

如果你想固定某个节点位置，可以在布局完成后手动修改一下节点位置：
```javascript
graph.on('afterlayout', e => {
  graph.updateItem(node, {
    x: ...,
    y: ....
  });
});
```

注意该监听要写在 graph.render() 之前。

**Comment by zhaokgithub** [comment]
好的 多谢

**Comment by zhaokgithub** [comment]
> 若实例化图时配置了布局，无论数据中节点有无位置信息，都会按照布局来确定位置。
> 
> 如果你想固定某个节点位置，可以在布局完成后手动修改一下节点位置：
> 
> ```js
> graph.on('afterlayout', e => {
>   graph.updateItem(node, {
>     x: ...,
>     y: ....
>   });
> });
> ```
> 
> 注意该监听要写在 graph.render() 之前。

好的 多谢
