### ISSUE TITLE
插件plugins:[grid]，使用网格插件不起作用

### ISSUE THREAD

**Issue by welsonLover** [antvis/G6#1566]
- **G6 Version**:3.4.9
- **Platform**: Mac Chrome(版本 81.0.4044.138)
- **Mini Showcase(like screenshots)**:
#### JS代码
```javascript
let grid = new G6.Grid();
      self.graph = new G6.Graph({
        container: 'flowChart', // 容器ID
        width: 800, // 画布宽
        height: 400, // 画布高
        modes: {
          // Defualt mode
          default: ['drag-node', 'click-select'],
          // Adding node mode
          addNode: ['click-add-node', 'click-select'],
          // Adding edge mode
          addEdge: ['click-add-edge', 'click-select']
        },
        plugins: [grid]
      });
```

#### HTML 代码 HTML codes
```html
<div id="flowChart"></div>
```
- **CodePen Link**:
描述：页面网格没有展示出来，引入方式：npm install --save @antv/g6，导入： import G6 from '@antv/g6';

**Comment by Yanyan-Wang** [comment]
审查一下元素看有没有被其他东西盖住了。

[示例](https://codepen.io/Yanyan-Wang/pen/mdbYZvZ?__cf_chl_jschl_tk__=2847be5f3862b9ae207a1a3f080ff6230abc143a-1589383063-0-AY1zuA0TuNiTwiiEUsN4SkuVfeaQWTRXxSOLoW1sElVpotk_PH3uqJQ5rbS3XE7KVktDkLgBqHWwEMKXp0VRr8G8PH0DKn4AOKlBaTU7DXDbmmtu6xLvXNCH1yOL6khx06MDPSwEJqg0ojw376xWhrkPsICi_oFdlEbsGum4QQipBDi4D5GHfQAC-XbwJB1pBzYK4dzoJm_EEWFBNt_n90K7rG3lCYuUKOWHNafqO1jxwof0cE7wedZ6BxMTXivFz0BW2I6BmSozfURNrEiLv8hNQg2rSLhMa-poYMJvRJqFtriSw66yDxGk6bWoCN7-J1S2Jq_MYS2b1wllkrpmWB0Qmoo08yTzv6IQHPZeNWVJ)

**Comment by welsonLover** [comment]
```html
<div style="position: absolute;left: 0px;top: 0px;right: 0px;bottom: 0px;overflow: hidden;/* z-index: -1; */width: 800px;height: 400px;">
  <div class="g6-grid" style="position: absolute; transform-origin: 0% 0% 0px; background-image: url(&quot;data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAiIGhlaWdodD0iNDAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGRlZnM+PHBhdHRlcm4gaWQ9ImdyaWQiIHdpZHRoPSI0MCIgaGVpZ2h0PSI0MCIgcGF0dGVyblVuaXRzPSJ1c2VyU3BhY2VPblVzZSI+PHBhdGggZD0iTSAwIDEwIEwgNDAgMTAgTSAxMCAwIEwgMTAgNDAgTSAwIDIwIEwgNDAgMjAgTSAyMCAwIEwgMjAgNDAgTSAwIDMwIEwgNDAgMzAgTSAzMCAwIEwgMzAgNDAiIGZpbGw9Im5vbmUiIHN0cm9rZT0iI2UwZTBlMCIgb3BhY2l0eT0iMC4yIiBzdHJva2Utd2lkdGg9IjEiLz48cGF0aCBkPSJNIDQwIDAgTCAwIDAgMCA0MCIgZmlsbD0ibm9uZSIgc3Ryb2tlPSIjZTBlMGUwIiBzdHJva2Utd2lkdGg9IjEiLz48L3BhdHRlcm4+PC9kZWZzPjxyZWN0IHdpZHRoPSIxMDAlIiBoZWlnaHQ9IjEwMCUiIGZpbGw9InVybCgjZ3JpZCkiLz48L3N2Zz4=&quot;); width: 4000px; height: 2000px; left: 0px; top: 0px;"></div>
</div>
```

这里面有个z-index: -1 导致我这个网格看不见，应该怎样配置

**Comment by Yanyan-Wang** [comment]
把盖在上面的东西移下去

**Comment by renqian1011** [comment]
@Yanyan-Wang 你给的案例加栅格化背景，多次拖动画布，就会鼠标放不下去了

**Comment by renqian1011** [comment]
@Yanyan-Wang 你给的案例加栅格化背景，多次拖动画布，就会鼠标放不下去了

**Comment by Yanyan-Wang** [comment]
> @Yanyan-Wang 你给的案例加栅格化背景，多次拖动画布，就会鼠标放不下去了

什么意思？

**Comment by renqian1011** [comment]
你们可以尝试随便点击画布或者节点，然后拖拽，不要常规测试，略微暴力测试，然后就能出现不能停止拖拽事件

**Comment by renqian1011** [comment]
> > @Yanyan-Wang 你给的案例加栅格化背景，多次拖动画布，就会鼠标放不下去了
> 
> 什么意思？
你们可以尝试随便点击画布或者节点，然后拖拽，不要常规测试，略微暴力测试，然后就能出现不能停止拖拽事件

**Comment by Yanyan-Wang** [comment]
> > > @Yanyan-Wang 你给的案例加栅格化背景，多次拖动画布，就会鼠标放不下去了
> > 
> > 
> > 什么意思？
> > 你们可以尝试随便点击画布或者节点，然后拖拽，不要常规测试，略微暴力测试，然后就能出现不能停止拖拽事件


没能复现，你的操作系统和浏览器是？

**Comment by jumodada** [comment]
设置一个相对定位就好了
