### ISSUE TITLE
使用HVH之后，箭头隐藏了

### ISSUE THREAD

**Issue by ayiaq1** [antvis/g6#157]
https://codepen.io/anon/pen/LewwQa?editors=0010#anon-login

G6.registEdge('arrow', {
  afterDraw: function(cfg, group, keyShape) {
    return afterDrawEdgeFun(cfg, group, keyShape);
  }
}, 'HVH');
net.edge().color('#34b8e2').shape('arrow');
使用折线，自定义箭头之后，拖动方块箭头在内部了，我希望不管怎么拖动，箭头都能显示在方框外,现在使用HVH折线之后就不行了，如果不自定义图形就可以随便拖动箭头都能指向其他位置的锚点

**Comment by TomHuangCN** [comment]
https://antv.alipay.com/zh-cn/g6/1.x/tutorial/custom-shape.html#_%E8%87%AA%E5%AE%9A%E4%B9%89%E7%AE%AD%E5%A4%B4

**Comment by sunny920406** [comment]
官方文档里
 G6.registerEdge(name, {
  // 绘制
  draw: function(cfg, group){
    return keyShape;
  },
  // 绘制后执行
  afterDraw: function(cfg, group, keyShape){

  }
});
 G6.registerEdge 这个方法没有没有第三个参数，楼主 G6.registEdge 这个方法是自己定义的？
