### ISSUE TITLE
safari浏览器显示阴影兼容问题

### ISSUE THREAD

**Issue by fively** [antvis/G6#1571]
设置shape阴影属性，在safari上显示有问题，
属性代码：
shadowColor: 'rgba(67,107,255,0.4)',
shadowBlur: 15,
shadowOffsetX: 2,
shadowOffsetY: 6

<img width="254" alt="15BD8A88-A272-4E9B-97F4-4176CD639809" src="https://user-images.githubusercontent.com/37909490/81902116-2e526f00-95f2-11ea-9d2d-edc5bd69035b.png">

**Comment by Yanyan-Wang** [comment]
麻烦提供一个在线 demo。codepen.io 或其他平台都可以

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
