### ISSUE TITLE
大数量节点重叠覆盖

### ISSUE THREAD

**Issue by IS917** [antvis/G6#1572]
- **G6 Version**:3.4.4
- **Platform**:mac
请问节点数据比较多的时候，如何实现等距离平铺开，而不是重叠覆盖的形式？
<img width="1118" alt="屏幕快照 2020-05-14 15 47 52" src="https://user-images.githubusercontent.com/12396976/81907521-7a091680-95fa-11ea-913b-adf55e0fbba8.png">
<img width="1037" alt="屏幕快照 2020-05-14 15 50 49" src="https://user-images.githubusercontent.com/12396976/81908313-aa04e980-95fb-11ea-8e1c-740adc1974d3.png">

**Comment by Yanyan-Wang** [comment]
使用了什么布局算法。部分算法可以配置 preventOverlap，看一下文档

**Comment by IS917** [comment]
> 使用了什么布局算法。部分算法可以配置 preventOverlap，看一下文档

使用的是fruchterman，preventOverlap是不是只能保证结点 不重叠，但是不能保证合适间距的前提下把所有数据平铺开吧？  canvas面板是可拖拽的，结点等间距平铺的效果更好

**Comment by Yanyan-Wang** [comment]
fruchterman 没有 preventOverlap 这个配置项，也可能是这个数据量需要更多的迭代次数才能使节点分散一些。force 和 radial 可以配置 preventOverlap。还有一些布局中有 linkDistance 可以考虑配置一下
