### ISSUE TITLE
Group高度计算逻辑与文档不符

### ISSUE THREAD

**Issue by VajraFate** [antvis/G6#1574]
# 问题
发现`minDis`实际值与文档不符，导致Groups高度计算出错
#  背景
由于项目需求，本人需要计算group的 高度与宽度，以便后续进行groups定位。依据文档`groupType `指定为 'rect'  时的`minDis`，计算出的高度与文档说明不符合。
![image](https://user-images.githubusercontent.com/24877950/81928816-74bac480-9618-11ea-8744-2262fa591c63.png)

## 计算逻辑
按照上述文档说明，进行了以下计算
``` javascript
const minDis = 30
// 假设计算出BBox1 的高度为boxHeight = 100
const boxHeight = 100;
const groupHeight = boxHeight + 2 * minDis;
// groupHeight: 160
```
但是视图实际测量结果，Group的高度136，与本人计算不符合。

## 原因
查看group的相关代码发现，`minDis实际padding距离为 30 * 0.6  = 18`，进行了`defaultStyle.disCoefficient = 0.6` 这个系数相乘。导致了实际minDis与实际不符合，最终导致Group高度与实际不符合。
`https://github.com/antvis/G6/blob/d90ff65f876b3185ad92c2151765165fdbf12ea3/src/graph/controller/customGroup.ts#L234

## 期望
1. minDis实际结果存在偏差，希望大佬能对`disCoefficient`进行说明~
2. 目前缺少group相关属性获取和定位的方法，导致要对Groups操作复杂度较高。希望能G6后续能支持更多Group相关api，减少类似手动计算Group属性的开发成本。

- **G6 Version**: ^3.2.6

**Comment by Yanyan-Wang** [comment]
你好。disCoefficient 是调整 padding 的系数，可以在 group 数据或者实例化图时 groupStyle 里面配置。请问你计算 Group 高度的原始需求是什么呢？现在的节点分组设计上有些问题，我们将在下周发布全新的节点分组机制 Combo。

**Comment by VajraFate** [comment]
感谢你的回复，我将disCoefficient设置为1可以解决问题了，非常期待Combo分组机制。
关于计算 Group 高度的原始需求，情景是需要对多个**gruops按照一定规律去进行排列布局**，保证每个group之间**不重叠**，具体思路如下：
1.  统计每个groups中node数，按照上述逻辑计算出每个groups的`height`与`width`
2.  遍历groups，设置每个groups左上角起始位置的x,y轴为groupOriginX，groupOriginY。
3. 每个group中的node，依据groups的起始位置，按照一定规律设置其中node节点的具体位置。


假设目前需要将groups如下图自上而下排列，具体计算代码如下：
![image](https://user-images.githubusercontent.com/24877950/82010822-c198ac80-96a5-11ea-86c5-2c3050dcbd0a.png)


```javascript

 const groupsList = [
      {
        groupId: 1,
        nodes: [
          {
            id: 'node1',
          },
          {
            id: 'node2',
          },
        ],
      },
      {
        groupId: 2,
        nodes: [
          {
            id: 'node3',
          },
          {
            id: 'node4',
          },
        ],
      },
    ];
    const groupsMarginBottom = 20;
    const nodes = [];
    // 记录组排序位置
    let currentGroupY = 0;
    // 遍历gruops进行，groups宽高、原始位置计算，计算node具体坐标。
    groupsList.map(group => {
      group.originY = currentGroupY;
      group.originX = 0;
      group.width = nodeSize + minDis * 2;
      group.height = group.nodes.length * nodeSize + minDis * 2;
      group.nodes.map((node, index) => {
        node.x = group.originX + minDis + 0.5 * nodeSize;
        node.y = group.originY + minDis + 0.5 * nodeSize  + index * nodeSize;
        nodes.push({
          ...node,
          groupId: group.groupId,
        });
      });
      currentGroupY += (group.height + groupsMarginBottom);
    });

    ...
    graph.data({ ...nodes }); // 加载数据

```

**Comment by Yanyan-Wang** [comment]
Combo 和 Node/Edge 一样都是一个实例了，可以获取到实例的 bbox。另外还有专门针对 Combo 设计的力导向布局方法。
