### ISSUE TITLE
g6中的节点能否支持双击事件？

### ISSUE THREAD

**Issue by ruanyi** [antvis/g6#158]
最近一个项目中有使用到antv/g6来画工作流流程图，遇到一个问题：目前g6支持的事件只有以下几种：
net.on('itemmousedown', ev => {
 
});
net.on('itemmouseup', ev => {
 
});
net.on('itemmouseenter', ev => {
 
});
net.on('itemmouseleave', ev => {
  
});
请问：是否支持双击事件？如果支持，请问该如何写？

**Comment by ruanyi** [comment]
补充下：这个需求的背景：是在画dag图时，node与node之间拉线，跟单击事件，很容易混在一起，所以，期望补充支持双击事件？

**Comment by TomHuangCN** [comment]
有双击事件 dblclick

**Comment by ruanyi** [comment]
万分感谢！！
