### ISSUE TITLE
edge的label添加背景颜色并没有生效

### ISSUE THREAD

**Issue by yfzm01** [antvis/G6#1580]
需要给edge的label添加一个背景颜色，按照FAQ“设置节点或边的背景”章节的方法设置，代码如下：
defaultEdge: {
          shape: 'line',
          style: {
            stroke: '#ccc',
            lineAppendWidth: 3,
            cursor: 'pointer',
            //lineDash: [2]
          },
          labelCfg: {
            refY: 5, 
            autoRotate: true, // 边上的标签文本根据边的方向旋转
            style: {
              fontSize: 8,
              background: {
                fill: 'green',
                stroke: 'green',
                padding: [3, 2, 3, 2],
                radius: 2,
                lineWidth: 3,
              }
            }
          },
        }
并没有生效，不管是3.4.8版本还是3.4.10版本

**Comment by Yanyan-Wang** [comment]
https://g6.antv.vision/zh/examples/shape/labelBg#edgeBg

你好，可以对照一下看有什么不同
