### ISSUE TITLE
各group能够自己自定义设置groupStyle吗？

### ISSUE THREAD

**Issue by caojin24** [antvis/G6#1581]
现在设置groupStyle是写在new G6.graph的配置里面，跟defaultNode同级。现在有需求需要不同的分组边框的颜色 不一样。能不能通过以下代码实现
groups: [
    {
      id: 'group1',
      title: {
        text: '我的群组1',
        stroke: '#444',
        offsetX: -20,
        offsetY: 30,
      },
      style:{...},
    },
    {
      id: 'group2',
      title: {
        text: '群组2',
        stroke: '#444',
        offsetX: -20,
        offsetY: 30,
      },
    style:{...},
    },
  ],

**Comment by baizn** [comment]
升级到 3.5 版本，使用 Combo，https://g6.antv.vision/zh/docs/manual/middle/combo
