### ISSUE TITLE
When the starting point of an edge appears outside the canvas, the edge's animation will disappeared!

### ISSUE THREAD

**Issue by claudewowo** [antvis/G6#1584]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/great-gareth-s6qpz)

### Steps to reproduce
open the link, the animation between node3 and node4 is stoped, drag canvas to right, the node3 will show, and the animation will be fine.

打开链接, 节点3和4之间的动画停止了, 拖拽画布节点3出现时动画又正常了!

### What is expected?
if the edge is inside of the canvas, the animation will play.

只要边没有完全隐藏  动画都应该正常播放.

### What is actually happening?
when the starting point of an edge appears outside the canvas, the animation will stoped!

当边动画起始点落在画布之外, 动画就不能正常播放了!

| Environment | Info |
|---|---|
| g6 | 3.4.10 |
| System | mac 10.15.4 |
| Browser | 81.0.4044.138 |

---
I need an anmation from one node to another.

给边添加动画时出现了这种问题

**Comment by Yanyan-Wang** [comment]
暂时可以通过关闭局部渲染来解决：
```javascript
graph.get('canvas').set('localRefresh', false)
```

**Comment by Yanyan-Wang** [comment]
v3.5.3 已解决。
