### ISSUE TITLE
TreeGraph使用自定义dom节点时会报错

### ISSUE THREAD

**Issue by visaWang** [antvis/G6#1586]
renderer已设置成svg，报错信息：
![image](https://user-images.githubusercontent.com/19553693/82322122-90531000-9a08-11ea-9152-5edcbee5222c.png)

**Comment by visaWang** [comment]
找到了问题：svg模式下必须设置node的size属性，不然会报错，文档好像也没写

**Comment by Yanyan-Wang** [comment]
可以提供一个在线 demo 看下吗

**Comment by Yanyan-Wang** [comment]
应该是你的自定义节点 draw 方法或者其他复写的方法里面使用到了 cfg.size，如果没定义肯定会报错的。只要是自定义节点里面用到的 cfg 属性，在外面就要对应的传值，或者在方法内部要做判空处理。
