### ISSUE TITLE
双击画布，再拖动画布，松开鼠标时，无法跳出拖动状态，没有任何报错信息

### ISSUE THREAD

**Issue by jihaiying** [antvis/G6#1590]
- **G6 Version**:^3.4.9
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
麻烦给出复现的在线 demo。

这个 demo 是正常的：https://codepen.io/Yanyan-Wang/pen/mdbYZvZ

**Comment by CoderPXin** [comment]
上面的demo可以复现，连续点击画布多次，就会出现一直处于画布拖动状态。

**Comment by CoderPXin** [comment]
> 麻烦给出复现的在线 demo。
> 
> 这个 demo 是正常的：https://codepen.io/Yanyan-Wang/pen/mdbYZvZ

上面的demo可以复现，连续点击画布多次，就会出现一直处于画布拖动状态。

**Comment by zc-1028** [comment]
> > 麻烦给出复现的在线 demo。
> > 这个 demo 是正常的：https://codepen.io/Yanyan-Wang/pen/mdbYZvZ
> 
> 上面的demo可以复现，连续点击画布多次，就会出现一直处于画布拖动状态。
> 
> 1. 先连续点击画布，尽量在短时间内多点击几次
> 2. 紧接着点击一次画布后移动鼠标画布就会跟着鼠标移动了。

遇到一样的问题，macos偶尔复现，Windows可以复现， g6-3.5.2版本 Chrome浏览器
