### ISSUE TITLE
TreeGraph findById获取不到被折叠的节点

### ISSUE THREAD

**Issue by xdddst** [antvis/G6#1593]
TreeGraph的节点折叠以后，通过findById拿不到。且从版本2.2升级为3.4版本以后，原来2.2版本通过

model获取的collapsedParent和parent等也无法拿到了。

业务场景：
     实际场景中因为数据较多，树的节点会很多，有时候用户为查看方便会折起来一些节点。同时为了方便用户在一堆树节点中快速找到想要的节点，我们在右上角给他提供了一个搜索，搜出节点以后，聚焦到该节点（如果它的父节点被折叠了，则拿到被折叠的父节点先展开 再聚焦到该子节点），目前3.4版本这样折起来的节点通过findById无法获取；且通过model拿不到该节点被折叠的父节点id（之前在2.2版本可以拿到）。无法满足。

**Comment by baizn** [comment]
树图折叠起来以后就没有渲染了，可以通过 「findDataById](https://g6.antv.vision/zh/docs/api/TreeGraph#finddatabyidid-target)方法查找到具体数据，然后把节点的所有父节点都展开，调用 layout 一下。
