### ISSUE TITLE
网格在felx布局错位问题

### ISSUE THREAD

**Issue by hqzh** [antvis/G6#1594]
[在线地址](https://codesandbox.io/s/grid-c176r?file=/index.html)

可以看到右侧的空白
![微信截图_20200519163152](https://user-images.githubusercontent.com/26128706/82537138-20fe2d00-9b7c-11ea-91af-3370f29f48c2.png)

**Comment by Yanyan-Wang** [comment]
似乎是 grid 的容器的 left:0px 导致的，可以先调用如下代码解决：

```javascript
grid.getContainer().style.left = null;
```

**Comment by hqzh** [comment]
这样x和y位置不对了

**Comment by hqzh** [comment]
> 似乎是 grid 的容器的 left:0px 导致的，可以先调用如下代码解决：
> 
> ```js
> grid.getContainer().style.left = null;
> ```

感谢

**Comment by hqzh** [comment]
@Yanyan-Wang 用了这个无法改变窗口大小自适应了

**Comment by Yanyan-Wang** [comment]
那么这样呢：

```javascript
grid.getContainer().style.left = `${menu.clientWidth}px`;
```

**Comment by hqzh** [comment]
这样也是要在窗口监听的回调下一直设置值，和null没区别，感觉应该grid组件处理

**Comment by kooriookami** [comment]
给container容器加上样式position: relative;

**Comment by hqzh** [comment]
> 给container容器加上样式position: relative;

你进在线例子试，是不行的

**Comment by gongran** [comment]
![image](https://user-images.githubusercontent.com/8361267/103122649-1086d580-46bc-11eb-91b6-bbc268a1a130.png)
grid.getContainer() undefined

**Comment by Yanyan-Wang** [comment]
> ![image](https://user-images.githubusercontent.com/8361267/103122649-1086d580-46bc-11eb-91b6-bbc268a1a130.png)
> grid.getContainer() undefined

Only after you assign the plugin to the graph instance, the plugin will be inited

**Comment by Yanyan-Wang** [comment]
题主问题在新版本中已不存在
