### ISSUE TITLE
子图布局不生效，子图布局的相关文档不够详细

### ISSUE THREAD

**Issue by tongorz** [antvis/G6#1595]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

子图布局相关的文档不够详细，模仿官网示例尝试如下，子图布局似乎并不生效。
不知道是不是使用姿势哪里出了问题，小白用户感谢大佬的解答。

`import G6 from "@antv/g6";

const data = {
  nodes: [
    { id: "node0", label: "node0", x: 100, y: 100},
    { id: "node1", label: "node1", x: 100, y: 400 },
    { id: "node2", label: "node2", x: 400, y: 400 },
    { id: "node3", label: "node3", x: 400, y: 100 },
    { id: "node10", label: "node10", issub: true},
    { id: "node11", label: "node11", issub: true},
    { id: "node12", label: "node12", issub: true},
    { id: "node13", label: "node13", issub: true}
  ],
  edges: [
    { source: "node0", target: "node1" },
    { source: "node0", target: "node2" },
    { source: "node0", target: "node3" },
    { source: "node1", target: "node10" ,issub: true},
    { source: "node1", target: "node11" ,issub: true},
    { source: "node1", target: "node12" ,issub: true},
    { source: "node1", target: "node13" ,issub: true}
  ]
};
var graph = new G6.Graph({
  container: "container",
  width: 1000,
  height: 1000,
  fitView: true,
  fitViewPadding: 40,
  modes: {
    default: ["drag-node"]
  },
  defaultNode: {
    size: 20,
    style: {
      fill: "#C6E5FF",
      stroke: "#5B8FF9"
    }
  },
  defaultEdge: {
    size: 1,
    color: "#e2e2e2"
  }
});
graph.data(data);
graph.render();
// subgraph
const newnodes = []
const newedges = []
for(let i of data.nodes) {
  if (i['issub']) {
    newnodes.push(i)
  }
}
for(let i of data.edges) {
  if (i['issub']) {
    newedges.push(i)
  }
}
setTimeout(function() {
const subgraphLayout = new G6.Layout['force']({
  center: [700, 700],
  linkDistance: 70,
  preventOverlap: true,
  nodeSize: 20,
  tick: function tick() {
    graph.positionsAnimate();
  }
})
subgraphLayout.init({
  edges: newedges,
  nodes: newnodes
});
subgraphLayout.execute();
},1000)`

**Comment by Yanyan-Wang** [comment]
参与布局的节点和边也要是合法的格式，你的 newedges 里面存在边的 source 或 target 不存在于 newnodes 里
