### ISSUE TITLE
如何在不改变原布局的情况下增加节点

### ISSUE THREAD

**Issue by zhaokgithub** [antvis/G6#1596]
使用Fruchterman布局方式，点击节点会新增节点，使用的是graph.changeData()，这样会重新刷新布局，有没有方式在不改变原布局基础上增加新节点的。

**Comment by Yanyan-Wang** [comment]
graph.addItem 可以增加单个节点，不会触发重新布局

**Comment by zhaokgithub** [comment]
这个我知道主要是我每次需要新增多个节点 是不是只能循环调用呢

**Comment by zhaokgithub** [comment]
另外补充个疑问 你们节点中的x y到底是指哪块的坐标呢？为什么我数据中定义的x y在render之后节点中的x y不一样

**Comment by gafish** [comment]
#2236 
在 changeData 前执行 destroyLayout 可以满足你的需求
