### ISSUE TITLE
G6 的Edge中文字的位置实在难调

### ISSUE THREAD

**Issue by Liuqing650** [antvis/g6#160]
```
G6.registerEdge('treeEdge', {
  draw(cfg, group) {
      const node = {
        x: (cfg.points[0].x + cfg.points[1].x) / 2,
        y: (cfg.points[0].y + cfg.points[1].y) / 2
      };
      group.addShape('text', {
        attrs: {
          x: node.x,
          y: node.y,
          fill: '#f00',
          lineWidth: 100,
          text: cfg.label.text,
          textAlign: 'left',
          textBaseline: 'top'
        }
      });
    return group.addShape('polyline', {
      attrs: {
        points: [
          [cfg.points[0].x, cfg.points[0].y],
          [cfg.points[1].x, cfg.points[1].y]
        ],
        stroke: '#222',
        lineWidth: cfg.size
      }
    });
  }
});
```
调试出去的位置，最后一层的子级位置勉强合得上，靠近顶级的节点位置完全歪的，并且非常不好控制。希望这里直接支持HTML吧，还有 edge  的label 中text 外好像是被一个矩形包住，但是无法设置矩形的颜色，边线等，也是非常难堪

**Comment by TomHuangCN** [comment]
1. 边 label 背景色的配置 https://antv.alipay.com/zh-cn/g6/1.x/api/global.html#_edgeLabelRectStyle
2. html 在文本处理确实比 canvas 要简单的多，但在 G6 是基于canvas基于G（AntV 技术栈的绘图引擎）的，不会开太多类似 html 这样有点 hack 的口子。使用 G6 定义节点的前提是用户接受我们的绘图库 G ，设计上控制图形的复杂度，开发上有能力基于 G 开发。否则可以考虑其它技术栈。
3. 求其次，浏览器环境下 html 就在那里，就算 g6 内部不支持，也拦不住用户去用。

**Comment by Liuqing650** [comment]
@TomHuangCN  问题解决了，很抱歉，文档没有读懂，draw ， afterDraw相互配合即可。期待文档有较多的属性举例或用法。
