### ISSUE TITLE
执行脚本demos报错

### ISSUE THREAD

**Issue by ljy423897608** [antvis/G6#1600]
- **G6 Version**:3.5.0
- **Platform**:window10
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

报错日志：ERROR in [at-loader] ./stories/Tree/component/flow-tree.tsx:384:38    TS2339: Property 'y' does not exist on type 'unknown'.
在文件ModelConfig类没有endPoint和startPoint属性吧？

**Comment by Yanyan-Wang** [comment]
感谢提醒，3.5.1 将在 EdgeConfig 中增加这两个类型。之后类似 flow-tree.tsx 这个例子中使用 endPoint startPoint 需要指定参数类型 cfg: EdgeConfig

**Comment by Yanyan-Wang** [comment]
3.5.1 已修复。

**Comment by Yanyan-Wang** [comment]
3.5.1 已修复。
