### ISSUE TITLE
createCombo动态增加分组报错

### ISSUE THREAD

**Issue by yfzm01** [antvis/G6#1601]
1.
graph.data(
  nodes: [
    {
      id: 'node1',
      x: 250,
      y: 150
    },
    {
      id: 'node2',
      x: 350,
      y: 150
    },
  ]
);
graph.render();
graph.createCombo('combo1', ['node1', 'node2']);会报错：Cannot read property 'push' of undefined；
重现地址：https://codepen.io/yfzm01/pen/OJydaoq

2.如果在初始化的时候先添加任意一个分组：
graph.data(
  nodes: [
    {
      id: 'node1',
      x: 250,
      y: 150
    },
    {
      id: 'node2',
      x: 350,
      y: 150
    },
  ],
  combos: [{
    id: 'combo',
    label: 'Combo'
  }]
);
graph.render();
然后再graph.createCombo('combo1', ['node1', 'node2']);就可以正常添加分组。重现地址：https://codepen.io/yfzm01/pen/gOaqQyE

**Comment by Yanyan-Wang** [comment]
3.5.1 已修复。
