### ISSUE TITLE
Angular (click) in edge

### ISSUE THREAD

**Issue by AlejandroMartinItop** [antvis/G6#1602]
I want to display a drawer when the user click a edge. It's possible to render a component with that attribute?. Or there is other way?. I checked the documentation and don't saw nothing similar.

**Comment by Yanyan-Wang** [comment]
Add the edge:click listener and control your DOM:

graph.on('edge:click' , e=> {
  // show up your drawer DOM
});

**Comment by AlejandroMartinItop** [comment]
Thank you, but that is not the way that I want. Because, my drawer is a component from Ng Zorro and the way that it works is with a boolean, and I can't make referend inside the graph.on

The drawer:
```
<nz-drawer [nzClosable]="false" [nzVisible]="visible" nzPlacement="right" nzTitle="Basic Drawer" (nzOnClose)="close()">
    <button nz-button nzType="danger" (click)="createNode('type1')">Type-1</button>
    <button nz-button nzType="danger" (click)="createNode('type2')">Type-2</button>
    <button nz-button nzType="danger" (click)="createNode('type3')">Type-3</button>
</nz-drawer>
```

I'm using a Typescript file:
This is possible?

```
visible:boolean = false

ngOnInit(): void {
   this.render()
  }

render(){
  graph.on('edge:click' , e=> {
  // change visible to true
  });
}
```
