### ISSUE TITLE
使用addShape添加的image无法裁剪

### ISSUE THREAD

**Issue by yfzm01** [antvis/G6#1604]
想在内置的circle节点上面添加圆形头像，使用了registerNode进行拓展，在afterDraw回调函数使用group.addShape添加的image不支持裁剪，重现地址：https://codepen.io/yfzm01/pen/vYNPyjX

**Comment by Yanyan-Wang** [comment]
裁剪是 G6 内部为 image 节点做的，image 类型的图形直接配置 clipCfg 是不行的。可以参考 G6 的做法: https://github.com/antvis/G6/blob/7b0aad3a9e3ae690f48f6c51fa4b85b715b8e808/src/shape/nodes/image.ts#L66

**Comment by leecj** [comment]
裁剪image shape
```javascript
      const avatar = group.addShape('image', {...});
      avatar.setClip({
        type: "circle",
        attrs: {
          r: 15,
          y: 0,
          x: 0
        }
      });
```
