### ISSUE TITLE
node节点下的子节点或edge下的子节点无法触发plugins的“node:XXX”或者“edge:XXX”事件？

### ISSUE THREAD

**Issue by woleicom** [antvis/G6#1606]
node节点下的子节点或edge下的子节点无法触发plugins的“node:XXX”或者“edge:XXX”事件？

**Comment by Yanyan-Wang** [comment]
你好，不是很明白你说的 “node 节点下的自节点或 edge 下的自节点” 是什么意思。可以写一个在线 demo 描述一下

**Comment by woleicom** [comment]
就是node下面的子node无法触发node:dragstart node:drag  node:dragend事件。暂时用了这种的node:mouse替代了 ，希望新版本可以支持下
