### ISSUE TITLE
Not check variable "comboTrees" avaiability in file  g6/lib/graph/graph.js

### ISSUE THREAD

**Issue by YuancaiDing** [antvis/G6#1607]
- **G6 Version**: 3.5.0
- **Platform**: NodeJs, Vue
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

For the source file g6/lib/graph/graph.js, there are many line of code to call the variable "comboTrees", the existing code are not checking comboTrees avaiability.

lib/graph/graph.js: 897
  - comboTrees.push(newCombo);
  + comboTrees && comboTrees.push(newCombo);

Line 1311
   comboTrees.forEach(function (ctree) {

Line 1348
   comboTrees && comboTrees.forEach(function (ctree) {

Line 1405
   if (comboTrees && !parentId && treeToBeUncombo) 

Line 2216,2219, 2369 2372 
Line 2632
 - comboTrees.forEach(function (cTree) {
 + comboTrees &&  comboTrees.forEach(function (cTree) {

**Comment by Yanyan-Wang** [comment]
Thanks, we will improve it in the next small version.

**Comment by Yanyan-Wang** [comment]
solved by 3.5.1.
