### ISSUE TITLE
3.x如何获取当前click状态为true的节点

### ISSUE THREAD

**Issue by hqzh** [antvis/G6#1608]
看3以前的版本直接有del方法，最新版本我如何删除节点
```js
graph.on("keyup", ev => {
      if(ev.code === 'Backspace'){
           // 想在这里通过按键删除选中的节点，但是不知道怎么获取
       }
});
```

**Comment by baizn** [comment]
使用 `graph.findAllByState('node', 'selected')` 获取所有选中的节点，再使用 `graph.removeItem` 删除，具体参考这里：https://g6.antv.vision/zh/docs/api/Graph#findallbystatetype-state
