### ISSUE TITLE
edge type为 arc的时候 鼠标mouseover 没有反应

### ISSUE THREAD

**Issue by caojin24** [antvis/G6#1610]
代码：import G6 from '@antv/g6';

/**
 * 该案例演示如何使用内置折线 arc
 * by 十吾
 */

const data = {
  nodes: [
    {
      id: '0',
      x: 150,
      y: 50,
    },
    {
      id: '1',
      x: 350,
      y: 250,
    },
    {
      id: '2',
      x: 250,
      y: 50,
    },
    {
      id: '3',
      x: 250,
      y: 250,
    },{
      id: '4',
      x: 350,
      y: 50,
    },
    {
      id: '5',
      x: 450,
      y: 250,
    },{
      id: '6',
      x: 450,
      y: 50,
    },
    {
      id: '7',
      x: 550,
      y: 250,
    },
  ],
  edges: [
    // 内置弧线
    {
      id: 'edge0-->edge1',
      source: '2',
      target: '3',
      curveOffset: -20,
    },
    // 配置内置折线的弯折弧度、端点最小距离
    {
      id: 'edge1-->edge2',
      source: '0',
      target: '3',
      curveOffset: -50,
    },
     {
      id: 'edge2-->edge3',
      source: '4',
      target: '3',
      curveOffset: -50,
    },
    {
      id: 'edge4-->edge4',
      source: '6',
      target: '3',
      curveOffset: -50,
    },
    
  ],
};

const width = document.getElementById('container').scrollWidth;
const height = document.getElementById('container').scrollHeight || 500;
const graph = new G6.Graph({
  container: 'container',
  width,
  height,
  linkCenter: true,
  defaultNode: {
    size: 45,
    style: {
      fill: '#DEE9FF',
      stroke: '#5B8FF9',
    },
  },
  defaultEdge: {
    type: 'arc',
    style: {
      stroke: '#F6BD16',
    },
    labelCfg: {
      autoRotate: true,
      refY: -10,
    },
  },
  modes: {
    // 支持的 behavior
    default: ['drag-node'],
  },
});

graph.data(data);
graph.render();
graph.on('edge:mouseover', (e) => {console.log(e)})

鼠标滑过不会触发事件。 如果type改为line 则能正常触发

**Comment by Yanyan-Wang** [comment]
arc 目前有问题，用 quadratic 代替

**Comment by caojin24** [comment]
这个大概什么时候 修复好？ 现在项目中 有一特殊场景必须用到半圆弧形

**Comment by Yanyan-Wang** [comment]
非常抱歉，当前版本(3.x、4.x)依赖的底层渲染引擎暂时不会考虑 SVG 问题的修复，渲染引擎目前正在大升级，我们也将在新版本接入新渲染引擎，届时应当可以解决 SVG 各种 bug
