### ISSUE TITLE
节点的显示隐藏的过渡动画怎么实现啊

### ISSUE THREAD

**Issue by luichooy** [antvis/G6#1612]
- **G6 Version**: 3.5.0
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

请教一下，切换节点或者边的显示隐藏状态时，怎么实现过渡动画？

显示隐藏的切换使用的是： `graph.showItem(node)`和 `graph.hideItem(node)`，此时应该改变了 node 的 visible 属性，但是在自定义节点实现动画的时候，不知道重写哪一个方法？请问可以给个示例吗？

**Comment by Yanyan-Wang** [comment]
可以尝试以下步骤：

1. 通过自定义节点复写 setState 以响应状态（state）变化，并使用该自定义节点。参考：https://g6.antv.vision/zh/examples/scatter/stateChange

2. 需要隐藏节点时，触发该节点的某个状态，如：
```javascript
graph.setItemState(node, 'fading', true);
```

3. 在自定义节点的 setState 中，节点上所有图形以动画形式响应 fading 状态，如
```javascript
item.get('group').get('children').forEach(shape =>{
  shape.animate({
    opacity: 0, // 动画结束时最终的透明度
    //... 可以有其他属性
  }, {
    duration: 500, // 动画持续时间
  // ...其他配置项
  })
});
```

4. 使用 setTimeout ，在动画结束后调用 graph.hideItem(node)，如
```javascript
setTimeout(() => {graph.hideItem(node)}, 500);
```

显示节点逻辑类似。
