### ISSUE TITLE
调用addItem方法报错：p.getType is not a function

### ISSUE THREAD

**Issue by jason1ee** [antvis/G6#1613]
- **3.5.0**:
- **windows10**:
- **调用addItem方法报错：p.getType is not a function**:
- **https://codepen.io/jason1ee/pen/KKdYVMd**:

![image](https://user-images.githubusercontent.com/1962046/83022897-ca529080-a05e-11ea-8521-5b7de9505cda.png)

**Comment by yfzm01** [comment]
我也遇到这个问题，然后把onClick方法稍微改动就可以了，改黑色粗体部分
this.edge = graph.addItem('edge', {
        source: model.id,
        target: **_model.id_**
      });

**Comment by jason1ee** [comment]
> 我也遇到这个问题，然后把onClick方法稍微改动就可以了，改黑色粗体部分
> this.edge = graph.addItem('edge', {
> source: model.id,
> target: **_model.id_**
> });

我这里的需求是想实现用鼠标点击连线，按照g6曾经的demo示例是给target一个坐标实现的。但现在g6 3.5版本不支持target传入坐标了，传入id是可以的。

**Comment by yfzm01** [comment]
@jason1ee 你按我的方法改，可以实现同样的需求

**Comment by SagittariusZhu** [comment]
# src/graph/controller/item.ts
`      if (target.getType() === 'combo') model.isComboEdge = true`
当target为点坐标时报错，只能设置为和source一样的ID，不知道是故意的还是bug，但导致gg-editor的behavior用不了了。

**Comment by yfzm01** [comment]
@SagittariusZhu 既然updateItem的target可以指定为坐标，那么addItem的target也应该可以指定为坐标，所以应该是一个bug

**Comment by Yanyan-Wang** [comment]
下个小版本修复

**Comment by Yanyan-Wang** [comment]
3.5.1 已修复。
