### ISSUE TITLE
chrome49框选不生效

### ISSUE THREAD

**Issue by hxyvipno1** [antvis/G6#1615]
内置behavior ‘brush-select’在chrome49浏览器下不可用，拖拽框没出现，换用高版本的chrome浏览器，一样的代码，可拖拽框选。

**Comment by hxyvipno1** [comment]
貌似是49浏览器的键盘事件的兼容性有些bug，当将trigger设置为‘drag’，是可框选的，设置为‘ctrl’、‘shift’不可框选

**Comment by baizn** [comment]
那这个我们就不处理了，后面有问题再排查，多谢！
