### ISSUE TITLE
动态增加自定义的node的问题

### ISSUE THREAD

**Issue by withlin** [antvis/G6#1616]
- **G6 Version**:
  3.5.0
- **Platform**:
   windows
- **Mini Showcase(like screenshots)**:
  
![image](https://user-images.githubusercontent.com/22409551/83113777-ae043180-a0fa-11ea-920f-71407558248a.png)

- **CodePen Link**:
https://codesandbox.io/s/rough-glade-5i2l9?from-embed=&file=/index.ts

描述:
当点击第一个node的时候新增一个node。这个node是自定义的，不是自定义的node可以渲染出来。比如rect这些默认的type。

**Comment by Yanyan-Wang** [comment]
请提供最小复现例子，你给的例子太复杂了，找问题效率很低。并且它现在并没有显示任何东西在画布上。
