### ISSUE TITLE
调用changeData画布空白问题

### ISSUE THREAD

**Issue by Tang-Js** [antvis/G6#1617]
- **G6 Version**: 3.4.7
- **Platform**: Windows

步骤：
画布有开启拖拽交互，当自定义的节点超出当前画布高度，为了能看到超出部分，拖拽画布到最底部，此时添加一个节点，调用changeData更新数据，这时候画布空白，导致所有节点丢失无法找到

**Comment by Yanyan-Wang** [comment]
请提供一下复现在线 demo

**Comment by Okabe-Kurisu** [comment]
我也遇到了，minimap上有内容但是canvas里面啥都没有，需要反复缩放有几率恢复

**Comment by Tang-Js** [comment]
在线demo地址：http://134.175.28.61:8080/g6/

**Comment by Yanyan-Wang** [comment]
> 在线demo地址：http://134.175.28.61:8080/g6/

在这个地址先把画布网上拖，直到节点超出上边界，然后再往下拖，直到节点超出下便捷，然后点击添加节点按钮，再将画布向上拖一些，就能看到两个节点垂直排列，是这样操作的吗？没有复现到画布空白。

**Comment by Tang-Js** [comment]
不是，节点上面有一个展开的按钮，先点击展开，然后拖动画布（不是拖拽节点）到最下面，直到看到展开的最下面，然后再点击新增节点，

**Comment by baizn** [comment]
> 不是，节点上面有一个展开的按钮，先点击展开，然后拖动画布（不是拖拽节点）到最下面，直到看到展开的最下面，然后再点击新增节点，

@Tang-Js 按你描述的这样操作后，你缩小一下画布，就会看到添加的效果。
![image](https://user-images.githubusercontent.com/9443867/83386168-216cb280-a41d-11ea-822a-64ec867b0e81.png)

PS：添加完以后，调用graph.fitView()，或者调用 graph.focusItem() 将新增加的画布移到画布中间，就不会出现这种问题，如果上面不是期望的效果，检查一下代码逻辑。

**Comment by Yanyan-Wang** [comment]
缩小之后还需要再拖动一下就能看到

**Comment by Tang-Js** [comment]
我试试fitView这种方式吧，缩小后有时候也会找不到，拉半天都没有，再新增也没有

**Comment by Yanyan-Wang** [comment]
应该是因为展开第一个节点后它很长，增加节点的时候，第一个节点被收起来了，新增节点增加在被收起后的第一个节点的下面，导致它的实际位置在画布上方很远的位置。

**Comment by Tang-Js** [comment]
是这样的，这时候不管怎么拉，怎么新增都不会出现

**Comment by Yanyan-Wang** [comment]
应该 G6 的 drag-canvas 交互做了限制，当 graph 完全超出画布的时候就限制不让拖动了，这是为了限制用户在交互的时候将图无限拖拽出画布。你这种情况可以用 fitView、 focusItem、translate、moveTo 等方式把画布调整回来。3.5.1 还将会增加 fitCenter，用于把 graph 的中心对齐到 canvas 中心。

**Comment by Tang-Js** [comment]
好的，我试试，辛苦解答

**Comment by lilongllong** [comment]
> minimap上有内容但是canvas里面啥都没有

我也遇到这个问题，想问下如何解决的？
