### ISSUE TITLE
renderer为svg时lineAppendWidth失效

### ISSUE THREAD

**Issue by LiuGuodong1314** [antvis/G6#1618]
- **G6 Version**: 3.5.10
- **Platform**: windows
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

renderer为svg时lineAppendWidth失效

**Comment by Yanyan-Wang** [comment]
请给出在线复现 demo

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
