### ISSUE TITLE
3.5.0版本有bug

### ISSUE THREAD

**Issue by MengyanGuo** [antvis/G6#1619]
**错误信息**
TypeError: Cannot read property 'set' of undefined
   
  at t.innerAddChild (umi.e94152fc.js:1)
     
  at umi.e94152fc.js:1
      
 at t.default (umi.e94152fc.js:1)
      
 at t.innerAddChild (umi.e94152fc.js:1)
     
（3.4.10版本没问题）

**Comment by Yanyan-Wang** [comment]
请给出复现在线 demo

**Comment by MengyanGuo** [comment]
> 请给出复现在线 demo

[https://codesandbox.io/s/sleepy-dust-sk5vu](https://codesandbox.io/s/sleepy-dust-sk5vu)

**Comment by Yanyan-Wang** [comment]
数据节点 id 有重复，id 必须要 unique。

destroy 看下有没有异步的逻辑没结束，还有问题再提带有在线 demo 的 issue。
