### ISSUE TITLE
自定义dom节点  事件监听不到

### ISSUE THREAD

**Issue by zhaokgithub** [antvis/G6#1621]
在react中使用g6自定义dom节点  当给onclick绑定方法test()  时候报错:
test is not a function
 具体代码如下：
import G6 from '@antv/g6';

/**
 *  该案例演示如何使用 G6 自定义 DOM 节点
 *  by 十吾
 *
 */

/**
 * 注册一个带有 DOM 的节点
 */
    var test = function(){alert('eee')}

G6.registerNode('dom-node', {
  draw: (cfg, group) => {
    var test = function(){alert('eee')}
    const shape = group.addShape('dom', {
      attrs: {
        width: cfg.size[0],
        height: cfg.size[1],
        html: `
        <div onclick="test()" style="background-color: #fff; border: 2px solid #5B8FF9; border-radius: 5px; width: ${cfg.size[0] - 5}px; height: ${cfg.size[1] - 5}px; display: flex;">
          <div style="height: 100%; width: 33%; background-color: #CDDDFD">
            <img alt="" style="line-height: 100%; margin-left: 7px;" src="https://gw.alipayobjects.com/mdn/rms_f8c6a0/afts/img/A*Q_FQT6nwEC8AAAAAAAAAAABkARQnAQ" width="20" height="20" />  
          </div>
          <span style="margin:auto; padding:auto; color: #5B8FF9">${cfg.label}</span>
        </div>
          `
      },
      draggable: true
    });
    return shape;
  }
}, 'single-node');

/** 数据 */
const data = {
  nodes: [
    {
      id: 'node1',
      x: 100,
      y: 200,
      label: 'Homepage',
    },
    {
      id: 'node2',
      x: 300,
      y: 200,
      label: 'Subpage',
    },
  ],
  edges: [
    {
      source: 'node1',
      target: 'node2',
    },
  ],
};

const width = document.getElementById('container').scrollWidth;
const height = document.getElementById('container').scrollHeight || 500;
const graph = new G6.Graph({
  container: 'container',
  width,
  height,
  renderer: 'svg',
  linkCenter: true,
  defaultNode: {
    type: 'dom-node',
    size: [120, 40]
  }
});

graph.data(data);
graph.render();

**Comment by Yanyan-Wang** [comment]
这个在文档中已经说明：

https://g6.antv.vision/zh/docs/api/nodeEdge/shapeProperties#dom-svg

**Comment by Yanyan-Wang** [comment]
可以在 graph.render() 之后拿到 DOM 元素加监听：
```javascript
const domNode = document.getElementById('dom-node')
domNode.addEventListener('click',function(e){
   // do something
})
```

**Comment by diligent-rookie** [comment]
我也遇到了，请问您是怎么解决的。
`                group.addShape('dom', {
                  draggable: true,
                  attrs: {
                    x: -110,
                    y: -75,
                    width: 15,
                    height: 15,
                    zIndex: 999,
                    html: `<div
                    class="test"
                    onclick="alert('Hi')"
                    style="cursor:pointer;background-color: #f0f;width:15px;height:15px;"
                    >6</div>`
                  },
                });`
我看官方例子就是这么写的啊，是哪出了问题吗

**Comment by ColinChen2** [comment]
使用HTML inline js的方式： https://stackoverflow.com/questions/22001674/inline-javascript-onclick-function
