### ISSUE TITLE
How to use .focusItem() with animation?

### ISSUE THREAD

**Issue by mostopalove** [antvis/G6#1626]
The `graph.focusItem(item.id)` works well, but how to use it with animation as it written in [docs](https://g6.antv.vision/en/docs/api/Graph#focusitemitem)? 

> This operation can be used as easing animation after searching a node.

- **G6 Version**: 3.4.7
- **Platform**: Mac OS Catalina

**Comment by michaelalemu** [comment]
I found an example in the docs which shows how to focus a node with animation, but it does not use graph.focusItem(): https://g6.antv.vision/en/examples/interaction/position

**Comment by mostopalove** [comment]
@michaelalemu yes, I've seen it but I need to know how do it with native G6 mechanism

**Comment by mostopalove** [comment]
@michaelalemu okay, I cant use animation with `graph.focusItem(item.id)`. But can I use animation with `graph.zoomTo()`?

**Comment by Yanyan-Wang** [comment]
new feature for v3.5.3: [graph.focusItem(item, animate, animateCfg)](https://g6.antv.vision/en/docs/api/Graph/#focusitemitem-animate-animatecfg)
