### ISSUE TITLE
下载图片后自定义click事件无效 

### ISSUE THREAD

**Issue by zhaokgithub** [antvis/G6#1627]
调用downloadFullImage下载图片之后，之前定义的click事件无效

**Comment by Yanyan-Wang** [comment]
请提供复现在线 demo

**Comment by zhaokgithub** [comment]
import G6 from '@antv/g6';

fetch('https://gw.alipayobjects.com/os/antvdemo/assets/data/algorithm-category.json')
  .then(res => res.json())
  .then(data => {
    const width = document.getElementById('container').scrollWidth;
    const height = document.getElementById('container').scrollHeight || 500;
    const graph = new G6.TreeGraph({
      container: 'container',
      width,
      height,
      linkCenter: true,
      modes: {
        default: [
          {
            type: 'collapse-expand',
            onChange: function onChange(item, collapsed) {
              const data = item.get('model').data;
              data.collapsed = collapsed;
              return true;
            },
          },
          'drag-canvas',
          'zoom-canvas',
        ],
      },
      defaultNode: {
        size: 26,
        style: {
          fill: '#C6E5FF',
          stroke: '#5B8FF9',
        },
      },
      defaultEdge: {
        style: {
          stroke: '#A3B1BF',
        },
      },
      layout: {
        type: 'compactBox',
        direction: 'RL',
        getId: function getId(d) {
          return d.id;
        },
        getHeight: () => {
          return 26;
        },
        getWidth: () => {
          return 26;
        },
        getVGap: () => {
          return 20;
        },
        getHGap: () => {
          return 30;
        },
        radial: true,
      },
    });

    graph.node(function(node) {
      return {
        label: node.id,
      };
    });

    graph.data(data);
    graph.render();
    graph.fitView();
  graph.on('node:click',function(node){
    alert('xiazai')
    graph.downloadFullImage('test',{backgroundColor:'#fff'})
  })
  });
//点击图片下载后 节点点击就没有用了 现在我用downloadImage是没问题的

**Comment by zhaokgithub** [comment]
我找到导致此问题的原因了 ：
当我们使用fitView布局时候，如果使用downloadFullImage下载图会导致重新更新canvas布局，当时此时没有重新渲染，导致我们看到的图和实际图所在canvas上的位置是不同的。如果我在下载之后调用graph.render() graph.fitView()可以解决这个问题，但是会导致canvas重新绘制（页面闪烁），这个我不知道如何解决了。

**Comment by Yanyan-Wang** [comment]
经排查发现是 downloadFullImage 的时候操作矩阵不当导致原图矩阵也发生了变化，所以发生了原图实际位置变化的问题。下个小版本解决 3.5.2

**Comment by zhaokgithub** [comment]
多谢

**Comment by Yanyan-Wang** [comment]
v3.5.2 已发。
