### ISSUE TITLE
TreeGraph提供了展开分组、收起分组的API吗，急急急急！！！！！！！

### ISSUE THREAD

**Issue by sunshine824** [antvis/G6#1628]
在TreeGraph官网稳定里没找到

**Comment by Yanyan-Wang** [comment]
Combo 吗，和一般图的 Combo 是一样的
https://g6.antv.vision/zh/docs/manual/middle/combo

**Comment by jyxnn** [comment]
可以看这个例子 https://antv-g6.gitee.io/zh/examples/case/decisionTree
