### ISSUE TITLE
初始化之后如果动画没有结束直接调用fitView会出现绘图异常

### ISSUE THREAD

**Issue by QDMarkMan** [antvis/G6#1631]
- **G6 Version**: ^3.5.0
- **Platform**: Windows10/Chrome
- **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/18100675/83604749-3fffb480-a5a9-11ea-836c-14b7f984ad2c.png)

- **CodePen Link**: [https://codesandbox.io/s/g6-demo-ztvcx?file=/index.js:5394-5401](https://codesandbox.io/s/g6-demo-ztvcx?file=/index.js:5394-5401)

动画没结束的情况下去调用fitView会出现绘图异常， 延迟500ms 或者是禁用动画是没问题的,

**Comment by Yanyan-Wang** [comment]
带有动画时，图的 bbox 是在动态改变的，这是 fitView 不能拿到准确的 bbox。建议在动画完成后调用 fitView，可以利用 G6 的时机监听动画结束：

```javascript
graph.on('afteranimate', e => {
  graph.fitView(20);
})
```

**Comment by QDMarkMan** [comment]
> 带有动画时，图的 bbox 是在动态改变的，这是 fitView 不能拿到准确的 bbox。建议在动画完成后调用 fitView，可以利用 G6 的时机监听动画结束：
> 
> ```js
> graph.on('afteranimate', e => {
>   graph.fitView(20);
> })
> ```

多谢
