### ISSUE TITLE
todataURL 不识别iconfont,并且生成的图片只有可视范围内的内容

### ISSUE THREAD

**Issue by szwc** [antvis/G6#1633]
- **G6 Version**:
3.5.0
- **Platform**:
- **Mini Showcase(like screenshots)**:
画布中
![canvas](https://user-images.githubusercontent.com/22705781/83726398-0ea0ea80-a676-11ea-8574-90447809ca2f.png)

todataURL生成的图
![todataurl](https://user-images.githubusercontent.com/22705781/83726363-047eec00-a676-11ea-8154-242ac16d3f5f.png)

- **CodePen Link**:

画布中用到了iconfont，但是用toDataURL生成的图片不识别，并且如果画布中的内容超出了可视范围，生成的图片只包含可视范围内的内容

**Comment by Yanyan-Wang** [comment]
导出整个图用 [graph.downloadFullImage](https://g6.antv.vision/zh/docs/api/Graph/#downloadfullimagename-imageconfig)

iconfont 的问题我们后面再排查一下

**Comment by szwc** [comment]
> 导出整个图用 [graph.downloadFullImage](https://g6.antv.vision/zh/docs/api/Graph/#downloadfullimagename-imageconfig)
> 
> iconfont 的问题我们后面再排查一下

现在的需求是想把图片直接存到后台去，不需要导出，只需要把画布转成url字符串。。

**Comment by Yanyan-Wang** [comment]
那你只能参考一下 G6 downloadFullImage 的实现了，里面的 dataURL 应该就是你想要的

https://github.com/antvis/G6/blob/cdddab71640c9de00ce1e04f80e1874ae1c896a0/src/graph/graph.ts#L1914

**Comment by szwc** [comment]
好的，我看看

**Comment by Yanyan-Wang** [comment]
v3.5.3 提供了 toFullDataURL 的方法，可以生成 url 字符串了。参见 [toFullDataUrl API](https://g6.antv.vision/zh/docs/api/Graph#tofulldataurlcallback-type-imageconfig)
