### ISSUE TITLE
animate重复执行

### ISSUE THREAD

**Issue by tangshengzhi** [antvis/G6#1634]
G6 Version:
3.4.9
Platform:
windows chrome63

bug描述：animate这一块发现个问题，在stopAnimate调用的时候，animations会清空，但是动画的动作会延迟结束，会导致一个问题就是：

当我stopAnimate的时候，再执行animate动作，会导致之前的interval不会清空，导致同时跑两个动画，就会导致动画执行加快等现象

**Comment by Yanyan-Wang** [comment]
麻烦提供一个在线 demo

**Comment by tangshengzhi** [comment]
https://codepen.io/tangshengzhi/pen/JjdzjRq
点击线就开始动画，点击空白区域取消动画

**Comment by Yanyan-Wang** [comment]
应该是因为 animate 相关函数都是异步的，导致 stopAnimate 后立即执行动画会出现这种情况，可以加 16ms 的延迟。（16ms 是一次屏幕刷新时间）。
```javascript
      setTimeout(() => {
        this.animate(item)
      }, 16);
```

**Comment by tangshengzhi** [comment]
@Yanyan-Wang  问题的根源是下一次的动画开始时上一次动画如果没有结束，那么就会导致同时跑两个定时器。上一次动画我已经发指令停掉了。这明显是有问题的。即便是延时的，也应该在16ms停掉第一个定时器
