### ISSUE TITLE
graph如何根据视窗大小重绘图形

### ISSUE THREAD

**Issue by shirleyYing** [antvis/G6#1635]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

graph如何根据视窗大小重绘图形，比如手动改变浏览器视窗大小，图形根据最新的宽高重新render

**Comment by Yanyan-Wang** [comment]
监听视窗变化，然后 [graph.changeSize](https://g6.antv.vision/zh/docs/api/Graph/#changesizewidth-height)

**Comment by winddies** [comment]
@Yanyan-Wang 你好，changeSizw 是只能改变画布大小吧？如何让图形重新渲染呢？比如我画布大小改变后，所有的节点的尺寸也相应的变化，这个怎么处理？

**Comment by Nekosandesu** [comment]
changeSize 只改变画布大小，不管图的重绘... 单独使用没用...
