### ISSUE TITLE
当存在selected状态的节点时，拖拽其他节点，delegate永远是selected状态的节点

### ISSUE THREAD

**Issue by kooriookami** [antvis/G6#1642]
- **G6 Version**:
3.5.2
- **Platform**:
win10 chrome 82
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:
https://codesandbox.io/s/eager-shadow-vnzqt

当选择circle1时拖拽circle2即可复现

**Comment by Yanyan-Wang** [comment]
`"drag-node"` 这个 behavior 的设定是默认拿目前画布上是 `'selected'` 状态的节点进行拖拽。如果你不想让 `selected` 的节点被拖拽，可以配置 `drag-node` 的 `selectedState` 为其他状态名：

https://g6.antv.vision/zh/docs/manual/middle/states/defaultBehavior#drag-node

**Comment by kooriookami** [comment]
emm 3.5.3还是3.5.4你们把这个问题修好了。。

**Comment by QoVoQ** [comment]
https://github.com/antvis/G6/blob/9d4d17f48c26cfac69605d7ea646c8547b81d5be/src/behavior/drag-node.ts#L323-L328

既然在方法`updatePositions`中更新的是`this.targets`的位置

https://github.com/antvis/G6/blob/9d4d17f48c26cfac69605d7ea646c8547b81d5be/src/behavior/drag-node.ts#L393-L404

那么在方法`calculationGroupPosition`中计算delegate rect信息也应该由`this.targets`来确定吧


Bug Fix Solution:
https://github.com/antvis/G6/blob/9d4d17f48c26cfac69605d7ea646c8547b81d5be/src/behavior/drag-node.ts#L401-L404
将上面4行代码换成`const nodes = this.targets`，就能修复这个bug了
