### ISSUE TITLE
antv g6 render slow

### ISSUE THREAD

**Issue by 3132811382** [antvis/G6#1643]
antv 在渲染方式为svg，edges超过300多条的时候，渲染流程图很卡，请问是什么原因

**Comment by Yanyan-Wang** [comment]
SVG 本身的性能就是很差的，推荐用 canvas

**Comment by jason1ee** [comment]
> SVG 本身的性能就是很差的，推荐用 canvas

2000个点+1000条边，用graphin力导图做可视化展示，初次渲染耗时比D3长。
已经用canvas渲染了，还尝试过enableWorker选项，也没见好转，请问还有那些手段可优化性能呢？

**Comment by Yanyan-Wang** [comment]
> > SVG 本身的性能就是很差的，推荐用 canvas
> 
> 2000个点+1000条边，用graphin力导图做可视化展示，初次渲染耗时比D3长。
> 已经用canvas渲染了，还尝试过enableWorker选项，也没见好转，请问还有那些手段可优化性能呢？

渲染时间主要是和图上元素数量相关，你用 D3 的时候是否每个节点上的图形数量和用 G6 或 Graphin 时一样呢？G6 和 Graphin 上一个节点上可能除了主要图形，还有文本、icon 等其他图形。可以在布局阶段（力导向布局结束前每一帧迭代都会重绘布局，非常频繁的渲染），可以把文本等其他图形隐藏（自定义节点时，设置图形 visible 为 false 可以让它不参与渲染），布局结束后（`graph.on('afterlayout', () => {...})`） 再显示这些隐藏的图形。

布局性能方面，G6 的 force 就是引用的 D3 的 force，性能应该没有区别。Graphin 的 force 目前是自研的，会有更多个性化的配置，但是目前速度不如 D3 的 force。现在 G6 正在做 GPU 版本的布局算法，较大、大规模数据情况下，布局计算速度提升很大。过几个月稳定后会发布。

**Comment by yangjialing** [comment]
> > > SVG 本身的性能就是很差的，推荐用 canvas
> > 
> > 
> > 2000个点+1000条边，用graphin力导图做可视化展示，初次渲染耗时比D3长。
> > 已经用canvas渲染了，还尝试过enableWorker选项，也没见好转，请问还有那些手段可优化性能呢？
> 
> 渲染时间主要是和图上图形数量、频繁渲染相关，你用 D3 的时候是否每个节点上的图形数量和用 G6 或 Graphin 时一样呢？G6 和 Graphin 上一个节点上可能除了主要图形，还有文本、icon 等其他图形。可以在布局阶段（力导向布局结束前每一帧迭代都会重绘布局，非常频繁的渲染），可以把文本等其他图形隐藏（自定义节点时，设置图形 visible 为 false 可以让它不参与渲染），布局结束后（`graph.on('afterlayout', () => {...})`） 再显示这些隐藏的图形。
> 
> 布局性能方面，G6 的 force 就是引用的 D3 的 force，性能应该没有区别。Graphin 的 force 目前是自研的，会有更多个性化的配置，但是目前速度不如 D3 的 force。现在 G6 正在做 GPU 版本的布局算法，较大、大规模数据情况下，布局计算速度提升很大。过几个月稳定后会发布。

请问在绘制之前 beforepaint设置超过边界就隐藏可以吗？，
