### ISSUE TITLE
缩小后如果图超出了容器边界，再放大不会复原

### ISSUE THREAD

**Issue by zc-1028** [antvis/G6#1644]
- **G6 Version**:3.5.0
- **Platform**:macos
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

鼠标指针放在图容器边缘进行缩小，当缩小到整个图超出容器边界看不到的时候，再放大，图也不会再出现了

**Comment by Yanyan-Wang** [comment]
Duplicate to #1492
