### ISSUE TITLE
updateItem 影响 linkPoints 样式

### ISSUE THREAD

**Issue by Yanyan-Wang** [antvis/G6#1646]
- **G6 Version**: 3.5.2
- **Platform**: MacOS
- **Mini Showcase(like screenshots)**:  
- **CodePen Link**: 
在下面官网链接中增加如下代码即可复现：
```javascript
graph.on('canvas:click', e=>{
  graph.updateItem(graph.getNodes()[0], {
    style: {
      stroke: '#f00'
    }
  })
});
```
https://g6.antv.vision/zh/examples/item/defaultNodes 

应该是因为 shape/node.ts 中 `updateLinkPoints` 拿到的样式不正确，如果 updateItem 传入的新样式中没有指定 linkPoints ，将会使用 options 中的样式，忽略了在实例化图时配置的全局样式。

使用下面代码代替则会使得 linkPoints 更新，从而保持原来样式，但这是不对的：
```javascript
graph.on('canvas:click', e=>{
  graph.updateItem(graph.getNodes()[0], {
    style: {
      stroke: '#f00'
    }
  })
});
```

另外，实例化图时 defaultNode 中配置 linkPoints 的 size 是圆点的半径，而 updateItem 时指定的 size 是直径。需要统一。

**Comment by jvpoucke** [comment]
TreeGraph data is not updated after graph.updateItem

**Comment by Yanyan-Wang** [comment]
> TreeGraph data is not updated after graph.updateItem either.
> Occurs on 3.4.10 too
> Does not occur on 3.4.9

I think it is not the same problem as this one. Pls provide an online demo and open another issue for this problem.

**Comment by Yanyan-Wang** [comment]
Solved by v3.5.3.
