### ISSUE TITLE
3.5.0往上的版本g6.min.js文件编码有问题

### ISSUE THREAD

**Issue by hxyvipno1** [antvis/G6#1648]
- **G6,3.5.0以上**:
- **引用直接报错**:
存在编码错误  ，js会报错
`("['鈥橾","g")`

**Comment by Yanyan-Wang** [comment]
报错信息是什么？

**Comment by hxyvipno1** [comment]
> 报错信息是什么？
报错提示 鈥橾不识别，对比3.4版本，改成['â€™]就好了

**Comment by Yanyan-Wang** [comment]
cdn 引入的吗？试一下把<meta charset="utf-8" />加入到你<head>标签内，错误可能是因为浏览器没有能识别正则中的UTF-8字符

**Comment by hxyvipno1** [comment]
我是把cdn的js复制到内网的，直接引用线上是没问题的，但是下载下来引用本地的就会报错，跟utf-8没关系
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="./g6.min.js"></script>
</head>
<body>
    <div id="container"></div>
</body>
<script>
    var graph = new G6.Graph({
  container: 'container', // String | HTMLElement，必须，在 Step 1 中创建的容器 id 或容器本身
  width: 800, // Number，必须，图的宽度
  height: 500, // Number，必须，图的高度
});
</script>
</html>
报错：Uncaught SyntaxError: Invalid regular expression: /['鈥橾/: Unterminated character class

**Comment by Yanyan-Wang** [comment]
使用你提供的这个代码，且引用本地 g6.min.js ，在 chrome 和火狐上没报错，safari 不加 utf-8 的 meta 报错，加上就不会报错了。你用的什么浏览器
