### ISSUE TITLE
改变state后，afterDraw定义的动画消失

### ISSUE THREAD

**Issue by ghoshorn** [antvis/G6#1652]
1. 提交问题前，请先阅读 https://antv.alipay.com/zh-cn/g6/1.x/index.html 上的文档。
===> 这个已经打不开了

- **G6 Version**: 3.5.1
- **Platform**: Mac
- **Mini Showcase(like screenshots)**:
![2020-06-09 10-09-29 2020-06-09 10_09_49](https://user-images.githubusercontent.com/7859403/84098270-65714000-aa39-11ea-805e-3ffc346b3c57.gif)

- **CodePen Link**:

demo code shows below:

import G6 from '@antv/g6';

const img_str = 'data:image/webp;base64,UklGRq4FAABXRUJQVlA4IKIFAABwHwCdASo8ADwAPiEMhEGhhv6rQAYAgS2NHsdCq/4D8AOoA64OEUAj/XPxVwyvRGvyO/gGxN/t3oK/1X6zesX3L/p/RP/2HCgKAB9AGeAbCB+AGwAbQBtA/8c/m/4PYHTonm+SzRH6B9sv2i/rOZC+G/ln9l/ML/GdoD7APcA/TD+09QDzAfrX+vHYM9AD+Uf0zrAPQA/bH0vv2t+CH9qf2R+A39e6X098/I7IAcLcs8Gjmc/9T7gPbX9H+wJ+rPVV9En9ZmBI5oUiYhkYHIVjRr9hzCTPcV5Rs/wjjIHkxPgtr/3ALZSuUm146HHwqQVA23hnnqH/4aJ/k4v4hU6RBZ0AAAD+//8ARPyL9yWIlAbWBAD0oKSqlYWreuRa3Oj02u+TvSQS8iwMYewUYTWLDNp9wOlFJaWnqE+za35UwUXuDAT6T0I4fwY+u+qrRVhl+S1ir4X7BQiNswug5AX+MjQcXEeUwfSIEUT+DFPCr+BUiwTbFxLni7fv61vRbmXoauLz4tiqOFTzEGP8tNXP5+H7mZVGfNjIxapT3FGUtqBdp/SD5cTOYOkn2fawkpqpCSqf2+CfiGWtIF673fEzlk/hIbWDhQ81C/ddxLn609d/5efckbdZ8HZbhhVmM82/Uat7CFmw1SH5xCxRxEEhjpf1EP1Xn5q9VZfm1+OFTab/MN67Xha8K//5oVBlMgZALE653X0fas/+2xMqiyCu5Wa7PHsCwbBwqROfNmzi4LPOTjkFPHVKDD1Nfj4/sul6cANdF68rf2jszlyZsUUoLTP7H3swSroc3ssNXSRVAcYd7+iBZpfoAYWvKgnr+Hv62fHZX5ZbjYbYzVjq6fsXkubto858NuUx4+ILb5y7dP6W3/IYVeUSF0yZseKIZhOMs9BBf5uB2Y3Ott//+1OG7hYINzcqigrzWAOJbSmVw3G0ULywkobx+rvfk8VmZFzQGgP/+4T74mp/vsZyM1NLguiTO2gNO05tcpXwveq5mrcweXrJ/bRZDmU2KBrnXhkXq+735c+UHTFq4h4jMOPm5shKioB6XaqhUf3DJlMg8937g/SKjrgD0H5sNm0/k4FfilBbcrsjc3dd6cwEYJo3CNhe3SpNJ2geNXyV4/hq/BZXZ1kiVknjmf5cUx7Tv/9Sb+fQ/DgAsRNSz1wiVodiLjP7aVrkxbWx5gJ8U/j0o1Ipm/nyDZRPrQXmbPAcy1eDDejxTDBKe42ElHpC2QlFdhOedsp4i9QVjt8EqWGy1YzPaGqZhCVg/LWt8/+4BmiCzNGtpR21MGJf4kI/n/1sbe36e1QBCBAx4EVfTM82ZM2lh0P189e7eY0A3NzXWVrUek8SEn+DYYCQeEaC5hDHGreFHT1baY6KyrFx3G9oMm3fLrCqmNjFRnZa3LB/5m8FgCpq9B/1OCLRE5GzVTZnVzj/4V38PgCIpX16Kznijf01+MkDeS9oCF2hEXQ9tr+mPLrjGy4Cg5fyLgyCj1fUq33nMf79Svli2h83m3gqkoxJcXvBetFQP8V/gRjBNGmFXK5TfwLhbolWEjDqUGK3n+hxzQLif9zreYO88EIRTUNbzE1/Sn7rBEtjB0uawNje5OubWsB62SOlMZoZpxrDbMb4UvQrODPhSafmhcYe9zm/dHxssMfUthhDKjyMhoRhngPjbzfGXmIV2Omgrn/zbefK/PawUGSH6x4Qk4HCN4/X8S+XCf51JJtOQeHST/yfwg69uMkE07SONnhGUrL6j5oQn6JI+zkaH/H/P/Ti/pfOTfAWxQNiMvWX08mqbuUweFSQ/G5YUP/uCvZAXutf1+Nhl2jj/n4/fPOihPjwvfFnnjOaQvs9PSpF33d+396LASZ3IID/4UP4pf9eOMXw82ccoUUUHX6MfBWyBDvARCrdPmerUwKwW+lBIAe1dsAAAA==';
const table_icon = img_str;
const icon_size=40;

const Util = G6.Util;
const data = {
  nodes: [
    {
      id: 'node3',
      x: 400,
      y: 100,
      size: [40, 40],
      type: 'inner-animate',
      img:
        img_str,
      label: 'Image Rotate',
      labelCfg: {
        position: 'right',
      },
    },
    {
      id: 'node4',
      x: 300,
      y: 300,
      type: 'table-node-loading',
      label: 'No Animation',
      labelCfg: {
        position: 'bottom',
      },
    },
  ],
  edges: [  ],
};

// Image animation
G6.registerNode(
  'inner-animate',
  {
    afterDraw(cfg, group) {
      group.attr('opacity', 0.2);
      const size = cfg.size;
      const width = size[0] - 12;
      const height = size[1] - 12;
      const image = group.addShape('image', {
        attrs: {
          x: -width / 2,
          y: -height / 2,
          width,
          height,
          img: cfg.img,
        },
        name: 'image-shape',
      });
      image.animate(
        ratio => {
          const matrix = Util.mat3.create();
          const toMatrix = Util.transform(matrix, [['r', ratio * Math.PI * 2]]);
          return {
            matrix: toMatrix,
          };
        },
        {
          repeat: true,
          duration: 3000,
          easing: 'easeLinear',
        },
      );
    },
  },
  'circle',
);

G6.registerNode(
  'table-node',
  {
    options: {
      style: {},
      stateStyles: {
        hover: {},
        selected: {
          // fill: 'red',
          'selected-border': {
            stroke: '#4288c9'
          },
          'node-label': {
            fill: 'white'
            // stroke: 'red',
            // shadowColor: 'green',
            // shadowBlur: 10
          },
          'node-label-rect': {
            fill: '#4288c9'
            // stroke: 'red',
            // shadowColor: 'green',
            // shadowBlur: 10
          }
        }
      }
    },
    draw: (cfg, group) => {
      const defaultNodeSize = 30
      const nodeSize = cfg.size || 30
      const [nodeColorFg, nodeColorBg] = ['#30acab', '#cfedee']

      // main circle node background
      const node = group.addShape('circle', {
        attrs: {
          r: nodeSize,
          fill: nodeColorBg
        },
        name: 'main'
      })

      const icon_group=group.addShape('image', {
          attrs: {
              x: 0,
              y: 0,
              width: defaultNodeSize,
              height: defaultNodeSize,
              img: table_icon,
          },
          draggable: true,
      });
      icon_group.translate(-defaultNodeSize/2,-defaultNodeSize/2);
      const icon_radio = nodeSize / defaultNodeSize * 0.9;
      icon_group.scale(icon_radio, icon_radio);

      group.addShape('path', {
          attrs: {
              path: [
                  ['M', -icon_size, icon_size],
                  ['L', icon_size, icon_size],
                  ['L', icon_size, -icon_size],
                  ['L', -icon_size, -icon_size],
                  ['L', -icon_size, icon_size],
                  ['Z'],
              ],
              lineWidth: 1,
              fill: 'green',
          },
          name: 'table-icon',
          draggable: true,
      });

      // node label and label background
      const nodeLabelRect = group.addShape('rect', {
        attrs: {
          label: cfg.label,
          stroke: 'transparent',
          fill: 'transparent',
          labelCfg: {
            style: {
              fill: 'black',
              fontSize: 14
            }
          },
          x: -50,
          y: nodeSize + 8,
          width: 100,
          height: 20
        },
        name: 'node-label-rect'
      })
      const nodeLabel = group.addShape('text', {
        attrs: {
          x: 0,
          y: nodeSize + 20,
          fill: 'black',
          text: cfg.label,
          fontSize: 12,
          textAlign: 'center'
        },
        name: 'node-label'
      })

      const { height } = nodeLabel.getBBox()
      const { width } = nodeLabel.getBBox()
      nodeLabelRect.setAttr('width', width)
      nodeLabelRect.setAttr('height', height)
      nodeLabelRect.setAttr('x', -width / 2)

      group.addShape('rect', {
        attrs: {
          x: -nodeSize,
          y: -nodeSize,
          width: nodeSize * 2,
          height: nodeSize * 2,
          stroke: 'transparent'
        },
        name: 'selected-border'
      })

      return node
    }
  },
  'circle'
);

G6.registerNode(
  'table-node-loading',
  {
    options: {
      style: {},
      stateStyles: {}
    },
    afterDraw(cfg, group, rst) {
      group.attr('opacity', 0.2)
      const table_loading_icon = group.addShape('image', {
        attrs: {
          x: -8,
          y: -8,
          img: img_str,
        },
        name: 'table-loading-icon',
      })
      table_loading_icon.animate(
        ratio => {
          const matrix = Util.mat3.create()
          const toMatrix = Util.transform(matrix, [['r', ratio * Math.PI * 2]])
          return {
            matrix: toMatrix,
          }
        },
        {
          repeat: true,
          duration: 1000,
          easing: 'easeLinear',
        },
      )
    },
  },
  'table-node'
);

const width = document.getElementById('container').scrollWidth;
const height = document.getElementById('container').scrollHeight || 500;
const graph = new G6.Graph({
  container: 'container',
  width,
  height,
  modes: {
          default: [
            {
              type: 'brush-select',
              includeEdges: false,
            },
            'drag-node',
            'drag-canvas',
            'zoom-canvas',
          ]
        },
  defaultNode: {
    style: {
      fill: '#DEE9FF',
      stroke: '#5B8FF9',
    },
  },
  defaultEdge: {
    style: {
      lineWidth: 1,
      stroke: '#b5b5b5',
    },
  },
});
graph.data(data);
graph.render();

**Comment by Yanyan-Wang** [comment]
image 图形没指定 width height
