### ISSUE TITLE
自定义布局内无法异步更新节点位置

### ISSUE THREAD

**Issue by NirvanaChow** [antvis/G6#1653]
- **G6 Version**:3.5.2
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

我想要自定义一个布局，类似force布局，需要在一段时间后才能达到平衡。
如果直接循环计算，将导致界面被阻塞，希望能够像force布局一样看到结点移动的动画效果。
我在自定义布局内部通过requestAnimationFrame实现类似d3的tick逻辑，但是界面无法更新。
发现force布局更新是通过下面代码实现的。
https://github.com/antvis/G6/blob/855f1b778256d07b90fe8053c95a419a87a686bd/src/graph/controller/layout.ts#L151
但是这里条件判断是强识别了layoutType为'force'。
https://github.com/antvis/G6/blob/855f1b778256d07b90fe8053c95a419a87a686bd/src/graph/controller/layout.ts#L145

这里定义布局的地方，无法获取graph实例，因此不能在布局类里面调用graph.refreshPositions

这里能否将判断条件修改成
`if (layoutCfg.tick) {...}`
或者指定defaultLayoutCfg上的某个指定属性，用于判断是否在每个tick的回调时执行refreshPositions？

**Comment by Yanyan-Wang** [comment]
这个应该不需要改动源码，你给你的自定义布局传回调函数 ：
```javascript
onTick: () => {
  graph.refreshPositions();
}
```

甚至都可以不叫 onTick 或者 tick 这些名字。然后在你的每次迭代后调用 onTick 应该就可以了，源码的 controller 的判断不会影响的。

**Comment by NirvanaChow** [comment]
理解您的意思，考虑过这种用法。
但是有个问题是，布局的使用者给布局的定义者传回调函数。
假如团队里面是开发者A开发的自定义布局，而开发者B使用这个布局，A需要告诉B，你要传给我一个callback，这里面调一下refreshPosition。后面可能开发者C也要用这个布局，然后A还得再给C说一下-。-

我的理解，我作为自定义布局的开发者，对外提供的tick回调，是给使用者提供在每一个迭代的时候能嵌入使用者自定义逻辑的能力，也就是对外提供的机会，而不应该是要求使用者协助我来做什么。
换句话说，假如使用者没有特殊的需求，是不是应该能让使用者在不提供这个callback的情况下能够正常使用。

**Comment by Yanyan-Wang** [comment]
很好的提议，欢迎提 PR。考虑下个小版本加
