### ISSUE TITLE
Is it possible to get full image of graph as url?

### ISSUE THREAD

**Issue by mostopalove** [antvis/G6#1657]
- **G6 Version**: 3.4.7
- **Platform**: Mac OS Catalina

There is `.downloadFullImage()` function which can save all graph as .png.
But I need to save it as .pdf.
The `.toDataURL()` function  return url only image in canvas but not full of graph.
How can I solve this problem?

It would be nice to have more option for saving graph as a file.

**Comment by baizn** [comment]
https://stackoverflow.com/questions/23681325/convert-canvas-to-pdf ？

**Comment by mostopalove** [comment]
@baizn graph is bugger than canvas

**Comment by Yanyan-Wang** [comment]
It is a new feature for v3.5.3: [graph.toFullDataURL](https://g6.antv.vision/en/docs/api/Graph#tofulldataurlcallback-type-imageconfig)
