### ISSUE TITLE
BUG? Node select change: the event has selected items being empty by mistake

### ISSUE THREAD

**Issue by jvpoucke** [antvis/G6#1658]
- **G6 Version**: 3.4.9
- **Platform**: Mac OS, firefox and chrome

Have graph listen on node changes.
Like this.
graph.on('nodeselectchange', (event: IG6GraphEvent) => {
                this.selectNodeId =
                event['selectedItems'] && event['selectedItems'].nodes.length > 0
                    ? event['selectedItems'].nodes[0].getModel().id
                    : null;
            if (!this.selectNodeId && event.target && event.target.getModel()) {
                // BUG??? so, sometimes selected nodes is empty, but target is not. Strange...
                console.log('Fallback selected node');
                this.selectNodeId = event.target.getModel().id;
            }
});

It occurs one the last node when an item has been deleted from the graph.

**Comment by Yanyan-Wang** [comment]
Could you pls provide an online demo?

**Comment by jvpoucke** [comment]
It is fixed in 3.5.3

**Comment by jvpoucke** [comment]
> Could you pls provide an online demo?

Well, if you just have a graph with multiple nodes, after graph.removeChild(nodeId); the click-select does not seem to work. Multiple nodes get selected after that.

**Comment by Yanyan-Wang** [comment]
It seems that you are using a TreeGraph since you call `graph.removeChild(nodeId)` but not `graph.removeItem(nodeId)`. So I implement it as you described. But I did not see the problem in the following codepen demo:

https://codepen.io/Yanyan-Wang/pen/MWKexVq

**Comment by jvpoucke** [comment]
Yes indeed. I will try to reproduce the bug that I have on codepen. 
In the meantime, I see that it has something to do with a mouseover-call on a Behabior (when I remove that part, everything works fine). So you helped me get in the right direction already, thanks.

**Comment by jvpoucke** [comment]
Can you please re-open the issue?
I managed to reproduce on https://angular-ivy-e1h8zs.stackblitz.io 

See add-node-tree.ts for comments.

You need to shift-click a node and drag it under another one. Then, click on other nodes -> they stay selected
