### ISSUE TITLE
扩展现有节点不写draw方法绘制不了

### ISSUE THREAD

**Issue by kooriookami** [antvis/G6#1660]
- **G6 Version**:
3.5.2
- **Platform**:
win10 chrome83
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:
https://codesandbox.io/s/objective-almeida-lr0ig

官网的例子，https://g6.antv.vision/zh/docs/manual/advanced/custom-node#%E6%89%A9%E5%B1%95-shape
期望应该能画出形状，实际上没有。
另外为什么扩展节点继承的是single-edge而不是single-node，希望解答

**Comment by Yanyan-Wang** [comment]
这里文档有误，应该是 single-node。对于 single-node 继承方法的描述也有误，版本更新后有些部分的文档没有及时更新。刚刚更新了一下。
另外，如果继承 single-node 的话是需要复写 draw 方法的，继承其他内置节点不是必须复写 draw 方法。

感谢指正。
