### ISSUE TITLE
不设置stateStyle不会触发自定义节点的setState方法

### ISSUE THREAD

**Issue by xinheHuang** [antvis/G6#1661]
- **G6 Version**:  3.5.3
- **Platform**: Windows/Mac
- **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/6908883/84293844-e97f1100-ab7a-11ea-9edb-b2da14f2d9e4.png)

- **CodePen Link**:

在这个提交（https://github.com/antvis/G6/commit/9d521e1a356d0d95633ee56590efb94b93647778 ）中，加了如上的判断，导致现在如果没有设置stateStyle的自定义节点，不会触发setState的方法。 这个改动是符合预期的吗？文档中并没有提及到。
![image](https://user-images.githubusercontent.com/6908883/84294228-74600b80-ab7b-11ea-9f81-4be6d289db4a.png)

**Comment by Yanyan-Wang** [comment]
确实不大合理，下个小版本修复。

**Comment by baizn** [comment]
3.5.4 已发布，修改了这个问题
