### ISSUE TITLE
设置了ContextMenu后，点击右键会先出来浏览器自带的右键菜单

### ISSUE THREAD

**Issue by hardyfan** [antvis/G6#1662]
我用edge最新的浏览器，调试Graphin的示例代码（https://codesandbox.io/s/graphin-components-context-menu-tgpkb?from-embed=&file=/src/styles.css:0-75）时发现一个问题：点击右键菜单时会先弹出浏览器自带的右键菜单。由于配置的代码仅仅是JSX语法的：
`<Graphin data={data}>
        <ContextMenu options={options} />
      </Graphin>`

无法对事件进行阻止。建议在实现的代码里，对右键菜单里增加对默认事件的阻止代码：
`e.preventDefault()`

**Comment by Yanyan-Wang** [comment]
可以将 issue 提到 graphin 仓库下 https://github.com/antvis/graphin/issues
