### ISSUE TITLE
更新3.5.3版本后setItemState方法不生效

### ISSUE THREAD

**Issue by 426-330** [antvis/G6#1663]
更新3.5.3版本以后 graph.setItemState(item, state, value) 不生效了。

**Comment by Yanyan-Wang** [comment]
应该是 stateStyles 写的位置不对。不能写在实例化图的配置项 defaultNode 里面，这个用法很早就废除了。应该写在 nodeStateStyles 中

https://g6.antv.vision/zh/docs/manual/middle/states/state/#%E9%85%8D%E7%BD%AE-state-%E6%A0%B7%E5%BC%8F

**Comment by Yanyan-Wang** [comment]
或者看一下 #1661  是不是和你的情况一样

**Comment by 426-330** [comment]
确实是 #1661 这个问题，我现在都改成 node.setState 方法了。。。

**Comment by baizn** [comment]
@426-330  3.5.4 修复了这个问题，麻烦更新下版本。
