### ISSUE TITLE
Circle节点linkPoints背景可以设置图标

### ISSUE THREAD

**Issue by chenchuans** [antvis/G6#1664]
在Circle节点使用[linkPoinks](https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/circle#linkpoints)时，只能设置圆点大小，背景颜色，可以支持圆点添加背景图标吗？
![linkPoinks](https://user-images.githubusercontent.com/30582495/84354266-24bd2680-abf3-11ea-99db-f412d4f3c439.png)

**Comment by Yanyan-Wang** [comment]
默认节点的 linkPoints 是圆图形。

需要绘制带图片的 linkPoints 需要自定义节点，自己加上 image 图形。

**Comment by evanoxu** [comment]
> 默认节点的 linkPoints 是圆图形。
> 
> 需要绘制带图片的 linkPoints 需要自定义节点，自己加上 image 图形。

@Yanyan-Wang 
1.自定义节点(registerNode) 里面如何设置 自定义的linkPoints？
2.自定义的linkPoints 是否遵行锚点(anchorPoints)设置？

**Comment by yuxinmei** [comment]
> > 默认节点的 linkPoints 是圆图形。
> > 需要绘制带图片的 linkPoints 需要自定义节点，自己加上 image 图形。
> 
> @Yanyan-Wang
> 1.自定义节点(registerNode) 里面如何设置 自定义的linkPoints？
> 2.自定义的linkPoints 是否遵行锚点(anchorPoints)设置？

请问解决了吗 我也需要在自定义节点里自定义linkPoints
