### ISSUE TITLE
目前G6没有编辑器的对齐线功能, 怎样调用G6自定义实现创建对齐线功能?

### ISSUE THREAD

**Issue by iDerekLi** [antvis/G6#1670]
- **G6 Version**: 3.5.3

请问目前G6没有编辑器的对齐线功能, 怎样调用G6自定义实现创建对齐线功能?

**Comment by Yanyan-Wang** [comment]
G6 目前没有对齐线的功能，只有一个 grid 插件只是绘制了带格子的图片作为背景。G6 目前的定位是图可视化与分析，重编辑场景推荐使用 AntV 旗下另一个开源引擎 [X6](https://github.com/antvis/X6)，它有丰富的编辑功能包括对齐线
