### ISSUE TITLE
rankdir on comboforce layout

### ISSUE THREAD

**Issue by JyotsnaC** [antvis/G6#1672]
- **G6 Version**: 3.5.3
- **Platform**: MacOS
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

Can I specify rankDir for comboforce layout. The reason I ask is when ever I refresh the page the layout is changing from LR -> TB -> RL -> BT . Again I have names to the nodes and everytime i refresh I see a different view.

**Comment by Yanyan-Wang** [comment]
comboForce layout is a kind of force-directed layout, it cannot be specified rankDir. 
As all the force-directed based layout, its result rely on the input nodes' positions. If you want a stable layout result, try specify the nodes' initial positions (x and y) in the data.nodes with fixed value like: 
```
const data = {
  nodes: [{
    id: 'node0',
    x: 10,
    y: 10
  }, {
    id: 'node1',
    x: 20,
    y: 10
  },
  ...
  ],
  edge: [...]
}
```

With the fixed initial positions, force-directed layout will produce basically the same layout result.
