### ISSUE TITLE
Is it possible to get a full graph in vector format?

### ISSUE THREAD

**Issue by mostopalove** [antvis/G6#1674]
- **G6 Version**: 3.5.3
- **Platform**: MacOS Catalina 10.15.5

It would be nice to have possibility get image of the graph in vector/visio format (.vsdx)
Or add support for more than four types of data (`.xml` for example)

**Comment by Yanyan-Wang** [comment]
For now, we only provides the API for image URL, jpeg, png, bmp formats by [graph.toDataURL](https://g6.antv.vision/en/docs/api/Graph#todataurltype-backgroundcolor), [graph.downloadImage](https://g6.antv.vision/en/docs/api/Graph#downloadimagename-backgroundcolor), graph.downloadFullImage(https://g6.antv.vision/en/docs/api/Graph#downloadfullimagename-type-imageconfig)

Ge the JSON format of the graph data by [graph.save()](https://g6.antv.vision/en/docs/api/Graph/#save)

And we welcome PRs to extend G6 with more possibilities.:)

**Comment by mostopalove** [comment]
Is it possible to get raw graph data with all elements on graph? Even custom elements.
