### ISSUE TITLE
G6 如何在nextjs中应用，求详细教程

### ISSUE THREAD

**Issue by mxy2316868975javascript** [antvis/G6#1676]
TypeError: G6.Graph is not a constructor

const G6 = dynamic(() => import('@antv/g6'), {
  ssr: false
});

**Comment by lzy110223** [comment]
你可以把G6组件分离出去 异步引入G6的组件 
const G6Component = dynamic(
  () => import('../xxx/Components/G6Component '),
  { ssr: false }
)

**Comment by mxy2316868975javascript** [comment]
> 你可以把G6组件分离出去 异步引入G6的组件
> const G6Component = dynamic(
> () => import('../xxx/Components/G6Component '),
> { ssr: false }
> )

不管用，我就是这么用的

components =>
import * as G6 from '@antv/g6';
export default G6;

业务 =>
const G6 = dynamic(() => import('@components/Graph/Service-Relation'), {
  ssr: false
});

console.log('G6', G6);
TypeError: G6.Graph is not a constructor

![image](https://user-images.githubusercontent.com/15233384/84636428-29514a00-af27-11ea-9cf6-07fbc88b6620.png)

const graph = new G6.Graph({
      container: 'container',
      width,
      height,
      defaultNode: {
        type: 'rect',
        labelCfg: {
          position: 'center'
        },
        style: {
          fill: '#DEE9FF',
          stroke: '#1890FF'
        }
      },
      defaultEdge: {
        color: '#1890FF'
      },
      modes: {
        default: [
          // 'drag-canvas',
          'drag-group',
          'drag-node-with-group',
          'collapse-expand-group'
        ]
      },
      groupType: 'circle'
    });

**Comment by lzy110223** [comment]
https://github.com/lzy110223/nextg6 你看一下我的demo吧 我运行没问题的
