### ISSUE TITLE
BUG: Inaccurate pixel ratio for small screens.

### ISSUE THREAD

**Issue by mostopalove** [antvis/G6#1677]
- **G6 Version**: 3.5.3
- **Platform**: Windows 10
- **Mini Showcase(like screenshots)**: 
On small screens, the image looks blurry.
This is better seen when zooming in on the browser, see screenshot. (increase in the screenshot by 300%)
![image_2020-06-14_18-32-31](https://user-images.githubusercontent.com/49098339/84597734-a8cf1280-ae6e-11ea-9400-0e7162d39193.png)
Screen resolution: 1600x1200

The situation is better when using `renderer: 'svg'`

**Comment by Yanyan-Wang** [comment]
Try to set the pixelRatio manually to see if it is improved: 
```javascript
graph.get('canvas').set('pixelRatio', x); // x is the pixelRatio number
```

**Comment by mostopalove** [comment]
@Yanyan-Wang this is a solution to the problem!
