### ISSUE TITLE
Combo的样式不能正确显示

### ISSUE THREAD

**Issue by xcj01010203** [antvis/G6#1678]
- **G6 Version**:3.5.4
- **Platform**:reactjs
- **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/20202711/84607240-c340d480-aede-11ea-8e73-d04796d4f5a1.png)

- **CodePen Link**:
import React, { useEffect } from 'react';
import { Card } from 'antd';
import G6 from '@antv/g6';

let graph = null;
function AllRelation(props) {
  const data = {
    nodes: [
      {
        id: 'node1',
        x: 250,
        y: 150,
        comboId: 'combo'
      },
      {
        id: 'node2',
        x: 350,
        y: 150,
        comboId: 'combo'
      },
    ],
    combos: [{
      id: 'combo',
      label: 'Combo'
    }]
  };

  const ref = React.useRef(null);
  useEffect(() => {
    const width = ref.current.scrollWidth;
    const height = ref.current.scrollHeight || 500;
    if (!graph) {
      const graph = new G6.Graph({
        container: ref.current,
        width,
        height,
        // translate the graph to align the canvas's center, support by v3.5.1
        fitCenter: true,
        // Set groupByTypes to false to get rendering result with reasonable visual zIndex for combos
        groupByTypes: false,
        defaultCombo: {
          type: 'circle',
          style: {
            lineWidth: 1,
          },
          labelCfg: {
            refY: 10,
            position: 'top',
            style: {
              fontSize: 18,
            }
          }
        },
        modes: {
          default: ['drag-canvas', 'drag-node', 'drag-combo', 'collapse-expand-combo'],
        },
        comboStateStyles: {
          // the style configurations for the hover state on the combo
          hover: {
            lineWidth: 3
          },
        },
        nodeStateStyles: {
          // the hover configurations for the hover state on the node
          hover: {
            lineWidth: 3
          },
        },
      });
      
      graph.data(data);
      graph.render();
    }
  }, []);

  return (
    <div>
      <Card title="业务组">
        <div ref={ref}></div>
      </Card>
    </div>
  );
}

export default AllRelation;

按照官方示例，绘制Combo图时，分组的圆圈中内部填充色和边框都没有显示；

**Comment by Yanyan-Wang** [comment]
v3.5.4 构建问题。升级到 v3.5.5 就可以了
