### ISSUE TITLE
G6打包后报了一个这样的错误 TypeError: t[i] is undefined 

### ISSUE THREAD

**Issue by Liuqing650** [antvis/g6#168]
开发过程之中没有报错，在打包之后，出现了
TypeError: t[i] is undefined 
这个错误，请问是如何造成的。

**Comment by TomHuangCN** [comment]
本地重新安装一下依赖？

**Comment by Liuqing650** [comment]
webpack 压缩代码后会出现此错误，不压缩则不会，使用的 `webpack.optimize.UglifyJsPlugin` 压缩的代码。是否问题出自 G6 本身呢

**Comment by Liuqing650** [comment]
webpack 版本太低导致了，webpack 1 版本会有这个错误。
