### ISSUE TITLE
dagre layout 下，用 combo 连接 node 的时候显示错乱，没有按照 LR 方向显示

### ISSUE THREAD

**Issue by K0I** [antvis/G6#1680]
- **G6 Version**: 3.5.3
- **Platform**: mac
- **Mini Showcase(like screenshots)**: 
- **CodePen Link**: https://codesandbox.io/s/laughing-sea-hq4ry

dagre layout 下，用 combo 连接 node 的时候显示错乱，没有按照 LR 方向显示
注：资金准备(combo)连接回滚(node)、提交(node)的时候

**Comment by K0I** [comment]
![1592214993621](https://user-images.githubusercontent.com/9019114/84644357-a5508f80-af31-11ea-87d9-5e2b705c343f.jpg)
预期效果是这样的

**Comment by Yanyan-Wang** [comment]
Combo 本身不会参与布局，链接到 Combo 的边也不会。参与布局计算的只有所有节点以及节点之间的边。想要达到上图效果可以尝试增加 Combo 内部节点到外部节点的边，并且把这些边的透明度设置为 0。

**Comment by K0I** [comment]
> Combo 本身不会参与布局，链接到 Combo 的边也不会。参与布局计算的只有所有节点以及节点之间的边。想要达到上图效果可以尝试增加 Combo 内部节点到外部节点的边，并且把这些边的透明度设置为 0。

谢谢！
