### ISSUE TITLE
扩展节点的label不显示

### ISSUE THREAD

**Issue by kooriookami** [antvis/G6#1681]
- **G6 Version**:
3.5.5
- **Platform**:
win10 chrome84
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:
https://codesandbox.io/s/dazzling-leftpad-6bvb6

示例可以看到，rect节点label正常显示，扩展节点label不显示

**Comment by Yanyan-Wang** [comment]
因为你复写的 draw 方法，没有给它加 label 呀，当然不会显示了。你可以把 `draw` 改成 `drawShape`。

**Comment by kooriookami** [comment]
> 因为你复写的 draw 方法，没有给它加 label 呀，当然不会显示了。你可以把 `draw` 改成 `drawShape`。

em。。那文档里是不是该体现一下这种用法
