### ISSUE TITLE
behavior类型申明文件中，不支持自定义事件

### ISSUE THREAD

**Issue by GitHub-wk** [antvis/G6#1682]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

export interface BehaviorOption {
  getEvents(): {
    [key in G6Event]?: string;
  };
  getDefaultCfg?(): object;
  shouldBegin?(e?: IG6GraphEvent): boolean;
  shouldUpdate?(e?: IG6GraphEvent): boolean;
  shouldEnd?(e?: IG6GraphEvent): boolean;
  bind?(e: IGraph): void;
  unbind?(e: IGraph): void;
  [key: string]: unknown;
}

behavior类型申明文件中  [key in G6Event]?: string，不支持自定义事件

**Comment by Yanyan-Wang** [comment]
RegisterBehavior 可以自定义交互，G6Event 已经包含了所有[基本事件](https://g6.antv.vision/zh/docs/api/Event)，你还需要什么事件呢？

**Comment by GitHub-wk** [comment]
一些自定义事件，通过graph.emit('custom-event')，然后在自定义behavior中接收的。自定义事件的触发源比如说是一个按钮的点击。

**Comment by baizn** [comment]
@GitHub-wk  可以详细描述下你的业务场景吗，我们在实际业务中没有碰到你这种需求，另外可以提个 pr

**Comment by GitHub-wk** [comment]
我们的场景是实现了一个类似gg-editor的功能，左侧拖拽节点到画布中。实现这个的方式，我们采用了自定义behavior，左侧的拖拽会触发一个在graph上的自定义事件，然后自定义behavior中会接收这个事件

**Comment by baizn** [comment]
> 我们的场景是实现了一个类似gg-editor的功能，左侧拖拽节点到画布中。实现这个的方式，我们采用了自定义behavior，左侧的拖拽会触发一个在graph上的自定义事件，然后自定义behavior中会接收这个事件

这种场景你可以继承 G6 的Behavior 类型，通过下面这种方式实现：
```
interface CustomEvent extends {
  // custom event
}
getEvents(): { [key in CustomEvent]?: string } {

}
```

G6 内部约束这个的目的一方面是为了规范事件，另一方面为了有类型提示方便开发者。
