### ISSUE TITLE
内置modelRect节点bug

### ISSUE THREAD

**Issue by Tang-Js** [antvis/G6#1687]
- **G6 Version**: 3.5.3
- **Platform**: Windows 10
- **question**: 
正常展示如下：
![image](https://user-images.githubusercontent.com/35561895/84724990-22284b80-afbc-11ea-9943-adf193726fe6.png)
非正常展示如下：
![image](https://user-images.githubusercontent.com/35561895/84724962-0de44e80-afbc-11ea-84db-ea2f9bb58c3b.png)
出现步骤：
重复点击几次就会出现这种情况，透明后再也无法选中

**Comment by Yanyan-Wang** [comment]
请给出复现在线 demo
