### ISSUE TITLE
官网文档错误

### ISSUE THREAD

**Issue by superwzx** [antvis/G6#1689]
- **G6 Version**: 3.5.3
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

https://g6.antv.vision/zh/docs/api/nodeEdge/Combo#removenodenode-string--inode
removeNode(node: string | INode)  这个方法实际传string无效，对照你们的源码：
 
```
  /**
  * 向 Combo 中移除指定的节点
  * @param node 节点实例
  * @return boolean 移除成功返回 true，否则返回 false
  */
  removeNode(node: INode): boolean {
    const nodes = this.getNodes();
    const index = nodes.indexOf(node);
    if (index > -1) {
      nodes.splice(index, 1);
      return true;
    }
    return false;
  }
```
另外这个方法不能删除combo中的node，还是需要通过graph.removeItem来删除，这个方法设计的用途是什么？

**Comment by Yanyan-Wang** [comment]
确实只能传节点实例，文档会尽快修改，感谢提醒。

这个只是用来把该节点从该 combo 中移除，并不是删除这个节点。移除后该节点仍然存在但是不再属于这个 combo。
