### ISSUE TITLE
请问什么时候能开源呢？开源会方便大家DEBUG和完善文档

### ISSUE THREAD

**Issue by LaiHuanMin** [antvis/g6#169]
因为看官方的文档有些地方不太懂，像shape为html 我只想单纯的添加对象到data.edges里面。然而我没能从官方文档和例子里找到，后来在反混淆的JS代码里面找到html的shape对象插入html字符串是html属性，如下图
![image](https://user-images.githubusercontent.com/24793529/36145599-cf75c2ac-10ec-11e8-950a-c6ca773c82a5.png)

还有group.addShape({})，这个参数里面除了attrs具体还有哪些呢？我在反混淆的代码里找到zIndex，但是好像也没有用。。。

  
G6还是挺不错的！但是想问问啥时候能够开源呢？

**Comment by TomHuangCN** [comment]
1.  group.addShape 是绘图引擎的接口，参考这个文档：

https://antv.alipay.com/zh-cn/g6/1.x/api/canvas.html

2.  G6 暂时没有开源计划
