### ISSUE TITLE
dagre layout 下，combo 内的 node 可以在同一水平线上吗

### ISSUE THREAD

**Issue by K0I** [antvis/G6#1691]
- **G6 Version**: 3.5.3
- **Platform**: mac
- **Mini Showcase(like screenshots)**:
- **CodePen Link**: https://codesandbox.io/s/lingering-wind-twy4x

预期效果是：
![image](https://user-images.githubusercontent.com/9019114/84814073-82160500-b043-11ea-9c44-3063842fb416.png)

**Comment by Yanyan-Wang** [comment]
这就不算是 rankdir: 'TD' 的 dagre 了，更像 [rankdir: 'LR' 的 dagre](https://g6.antv.vision/zh/examples/net/dagreFlow#lrDagre)。但是既有从左往右又有从上往下是满足不了的，只能自定义布局。
