### ISSUE TITLE
combo内连接node的虚线被显示为实线

### ISSUE THREAD

**Issue by cometor** [antvis/G6#1692]
- **G6 Version**: 3.5.5
- **Platform**: Windows 10
- **Mini Showcase(like screenshots)**: 
 双击combo折叠，然后再双击combo展开，边A->B和A->C的虚线会显示成实线
- **CodePen Link**: https://codepen.io/cometor/pen/MWwNVdm

操作前：
![image](https://user-images.githubusercontent.com/3225799/84844703-85c67d80-b07d-11ea-830e-ebb159bb6ad4.png)

双击Combo折叠，再展开：
![image](https://user-images.githubusercontent.com/3225799/84844618-531c8500-b07d-11ea-9060-96c9e09a6807.png)

**Comment by Yanyan-Wang** [comment]
下个小版本修复

**Comment by Yanyan-Wang** [comment]
v3.5.8 已修复。现在最新版本 v3.5.9。
