### ISSUE TITLE
combo折叠展开后，edge消失未显示

### ISSUE THREAD

**Issue by cometor** [antvis/G6#1693]
- **G6 Version**:3.5.5
- **Platform**:Windows 10
- **Mini Showcase(like screenshots)**:见CodePen链接，绘制后对combo操作，edge不显示

1、初次绘制：
![image](https://user-images.githubusercontent.com/3225799/84846429-603b7300-b081-11ea-8bf6-afe42f195459.png)

2、双击折叠inner：
![image](https://user-images.githubusercontent.com/3225799/84846499-8cef8a80-b081-11ea-9eb0-bec054232f52.png)

3、双击折叠outer，再双击展开，`A->inner` 边消失：
![image](https://user-images.githubusercontent.com/3225799/84846555-a85a9580-b081-11ea-93ad-62227d0947df.png)

- **CodePen Link**:https://codepen.io/cometor/pen/XWXNJwX

**Comment by Yanyan-Wang** [comment]
下个小版本修复

**Comment by Yanyan-Wang** [comment]
3.5.7 已修复。
