### ISSUE TITLE
销毁Graph后tooltip仍显示

### ISSUE THREAD

**Issue by cometor** [antvis/G6#1696]
- **G6 Version**:3.5.5
- **Platform**:Windows 10
- **Mini Showcase(like screenshots)**:

1、见CodePan示例，首先将鼠标焦点移到任一个节点上，显示tooltip

![image](https://user-images.githubusercontent.com/3225799/84852605-e068d500-b08f-11ea-9234-3eb3b7277349.png)

2、4s后，定时器会调用并销毁Graph，但tooltip仍存在

![image](https://user-images.githubusercontent.com/3225799/84852668-02625780-b090-11ea-863b-2ce65ad13ce9.png)

- **CodePen Link**:https://codepen.io/cometor/pen/mdVOJog

**Comment by Yanyan-Wang** [comment]
下个小版本修复

**Comment by Yanyan-Wang** [comment]
3.5.7 已修复。
