### ISSUE TITLE
如何实现一条环形边，即源点source和目标点target为同一个点

### ISSUE THREAD

**Issue by zzz111** [antvis/g6#17]
"edges": [
          {
            "type": "type1",
            "source": "系统一",
            "id": "32cb9f22",
            "value": 30,
            "active": true,
            "target": "系统二"
          }
]

**Comment by TomHuangCN** [comment]
暂时没实现，预计下个小版本加上。加上会通知你

**Comment by TomHuangCN** [comment]
1.0.3 已支持画环
