### ISSUE TITLE
Font property not used?

### ISSUE THREAD

**Issue by jvpoucke** [antvis/G6#1700]
The https://github.com/antvis/G6/blob/master/src/types/index.ts LabelConfig does not include a "font" (font family) property, where the docs says it should be included.
Docs: https://g6.antv.vision/en/docs/manual/middle/elements/nodes/defaultNode#style v 3.5.6

**Comment by Yanyan-Wang** [comment]
Sorry, the docs should be updated as soon as possible. Use `fontFamily` instead, corresponds to [font-family in CSS](https://www.w3schools.com/css/css_font.asp).
