### ISSUE TITLE
Layout dagre switch side of nodes

### ISSUE THREAD

**Issue by AlejandroMartinItop** [antvis/G6#1701]
When I add a node and render again the graph, the nodes change their side.

![e13ffeb7fb61a12ce605d81d35ffcd1f](https://user-images.githubusercontent.com/65715529/84925125-618c9000-b0c1-11ea-8abe-ac8bc84273e3.gif)

**Comment by Yanyan-Wang** [comment]
I did not reproduce the problem: https://codepen.io/Yanyan-Wang/pen/LYGxjGw

**Comment by chenluli** [comment]
应该是和 #1314 同样的问题

**Comment by Yanyan-Wang** [comment]
duplicated to  #1314
