### ISSUE TITLE
拖拽节点时，label 产生轨迹阴影

### ISSUE THREAD

**Issue by lvqq** [antvis/G6#1703]
- **G6 Version**: v3.5.2
- **Platform**: MacOS 0.15.3、Chrome 83
- **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/29809148/84988607-df5da380-b174-11ea-99f0-9a16bb9d3d9a.png)
- **CodePen Link**: https://codepen.io/lvqq/pen/abdBPYb

在使用布局例如 force、darge 等时，拖拽节点，字母 gjpqy 会出现如上轨迹阴影

**Comment by Yanyan-Wang** [comment]
关联 #1519

**Comment by clown-helang** [comment]
遇到相同问题，请问有解决方案了吗？

**Comment by yh418807968** [comment]
> 关联 #1519

你好~在手机上遇到了相同的问题，但没有用这个库，没找到这个issue对应的commit，能分享下是啥问题导致的，咋解决的不，万分感激！
