### ISSUE TITLE
3.1.3升级到3.3.3，原来挂载在window上的graph实例被去掉

### ISSUE THREAD

**Issue by MYSUMMERLORD** [antvis/G6#1704]
在g6的v3.3.1版本中，new Graph的时候会把得到的graph实例挂载在window对象上，这样任意地方都能访问到该graph实例。v3.3.3是出于什么原因不把graph实例挂载在window对象上了呢？如果我想在afterDraw方法中用graph实例进行一些处理，现在该如何做呢

- **G6 Version：**  3.3.3:
- **Platform：** windows 
- **Mini Showcase(like screenshots)**:

![111111](https://user-images.githubusercontent.com/9947530/84990066-2f3d6a00-b177-11ea-9be9-86164d3b8c4d.png)

- **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
挂载在 window 上肯定是不正确的做法，因为项目中如果有多个 graph 实例，就会相互覆盖。建议项目中自己管理这些需要全局使用的变量。
