### ISSUE TITLE
随机偶尔出现，所有node都还在0，0位置，没有布局出来；但是minimap可以显示出正确layout出来的graph

### ISSUE THREAD

**Issue by ghoshorn** [antvis/G6#1705]
![layout?](https://user-images.githubusercontent.com/7859403/85087658-9b1fe100-b210-11ea-9790-51872a396bab.png)
不能稳定复现，随机很偶尔的出现，所有node都还在0，0位置，没有布局出来；但是minimap可以显示出正确layout出来的graph
和采用的layout似乎没有关系，force/dagre/radial等都有可能出现。
有哪里可以打开G6的debug开关，看到更详细的log嘛？console中没有出现错误信息

- **G6 Version**:3.5.1
- **Platform**:Mac
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
请给出复现的在线 demo。

也可以先尝试一下：
```
setTimeout(() => {
  graph.paint();
}, 16)
```

**Comment by ghoshorn** [comment]
> 请给出复现的在线 demo。
> 
> 也可以先尝试一下：
> 
> ```
> setTimeout(() => {
>   graph.paint();
> }, 16)
> ```

在线demo很难重现问题。我这边基本上也是刷新个几十到一百多次，才能复现一次。但是又看到迷minimap显示完好，所有想问下，有可能是哪里出了问题，或者有能打开详细log的方法嘛？

**Comment by ghoshorn** [comment]
<img width="1167" alt="layout_nodes_data" src="https://user-images.githubusercontent.com/7859403/85112830-ddfdab00-b248-11ea-8ef3-c17cd196c867.png">
（初始时nodes都是没有位置信息的）可以从console里看到，graph里保存的nodes里，x,y这些位置信息都已经更新过了，但是canvas上仍然都在0，0的位置。
graph.paint()没有效果。

**Comment by ghoshorn** [comment]
@Yanyan-Wang

**Comment by Yanyan-Wang** [comment]
无法复现我也需要看一下你是怎么实现的。

或者试一下这个，在 render 前调用
```
graph.on('afterlayout', e => {
  graph.refreshPositions();
});
```

**Comment by ghoshorn** [comment]
`
import React from 'react'
import G6 from '@antv/g6'
import { AppProps } from '../../rootApp/app'
import './Canvas.css'
import './registerShape'
import GraphActions from './actions'
import './style.scss'

import emptyIcon from '../../assets/icons/canvas/empty.png'
const emptyText = "You haven't added any tables yet. Drag and drop from the Data Catalog panel to add \n tables to the applications"
const emptyData = {
  nodes: [
    {
      id: 'emptyIcon',
      type: 'image',
      width: 200,
      height: 200,
      img: emptyIcon,
      label: emptyText,
      labelCfg: {
        position: 'bottom',
        offset: 30,
        style: {
          fill: 'grey',
          textAlign: 'center',
          lineHeight: 20,
        }
      }
    }
  ],
  edges: [],
}

export default class Canvas extends React.Component<AppProps> {
  private graph: object | undefined

  private graphActions: typeof GraphActions | undefined

  constructor(props: Readonly<AppProps>) {
    super(props)
  }

  componentDidMount() {
    if (!this.graph) {
      this.graph = new G6.Graph({
        container: this.props.refNodeId,
        width: 1000,
        height: 600,
        animate: true,
        minZoom: this.props.minZoom || 0.2,
        maxZoom: this.props.maxZoom || 3,
        modes: this.props.modes || {
          default: [
            {
              type: 'brush-select',
              includeEdges: false,
            },
            'drag-node',
            'drag-canvas',
            'zoom-canvas',
          ]
        },
        defaultNode: this.props.defaultNode || {
          type: 'table-node',
        },
        layout: this.props.layout || {
          type: 'radial',
          preventOverlap: true,
          nodeSize: 20,
          nodeSpacing: 50,
        },
        plugins: this.props.plugins || [],
      })
      this.graphActions = new GraphActions(this.graph)
    }

    this.graph.data(emptyData)

    this.graph.render()

    if (this.props.onRef) {
      this.props.onRef(this)
    }

  }

  render() {
    return (
      <div className="canvas">
      </div>
    )
  }
}
`

调用：
`
import React from 'react'
import classnames from 'classnames'
import G6 from '@antv/g6'
import { Spin } from 'antd'
import Canvas from '../../lib/Canvas'
import { AppProps } from '../../rootApp/app'
import { getGraphDataFromModel } from './TableCanvasActions'
// import { data } from './mockData/data'
import './style.scss'


const minimap = new G6.Minimap({
  size: [200, 100],
  className: 'minimap',
  type: 'default',
})

export default class TableCanvas extends React.Component<AppProps> {
  private graph: object

  private graphActions: object


  constructor(props: Readonly<AppProps>) {
    super(props)
  }

  componentDidMount() {
    this.setState({
      isLoading: true,
    })
    this.props.proxy?.get('/api/model/tables').then((res) => {
      const data = getGraphDataFromModel(res)
      this.graph.changeData(data)
      this.setState({
        isLoading: false,
      })
      this.graph.updateLayout({
        type: 'force',
        alphaDecay: 0.012,
        linkDistance: 100,
        nodeStrength: -280,
        preventOverlap: true,
        collideStrength: 1,
        nodeSpace: 10,
        onLayoutEnd: () => {
          this.graph.addPlugin(minimap)
        },
      })
    })



  onRef = (ref: { graph: object; graphActions: object }) => {
    this.graph = ref.graph
    this.graphActions = ref.graphActions
  }


  render() {
    return (
      <div
        className={classnames('table-canvas-container', {
          full: this.state.isLoading,
        })}
      >
        {this.state.isLoading && <Spin id="table-canvas-spin" />}
        <Canvas
          onRef={this.onRef}
          refNodeId="table-canvas"
          minZoom={0.1}
          maxZoom={3}
          modes={{
            default: [
              {
                type: 'brush-select',
                includeEdges: false,
              },
              'drag-node',
              'drag-canvas',
              'zoom-canvas',
            ],
          }}
          defaultNode={{ type: 'table-node' }}
          layout={{
            type: 'radial',
            preventOverlap: true,
            nodeSize: 20,
            nodeSpacing: 50,
          }}
          // data={data}
        />
      </div>
    )
  }
}
`

**Comment by ghoshorn** [comment]
@Yanyan-Wang 
当出问题的时候，手动调用graph.refreshPositions();并没有什么反应。

主要是这两个文件，无关的删掉了一些。辛苦了~
[TableCanvas.zip](https://github.com/antvis/G6/files/4803767/TableCanvas.zip)

**Comment by Yanyan-Wang** [comment]
写成在线 demo 吧。不方便下载文件

**Comment by ghoshorn** [comment]
@Yanyan-Wang 
https://stackblitz.com/edit/react-dqwsgh
简化了一下，本来是在componentDidMount里的。
paint, refreshPositions, 都不能让canvas重绘出正确的graph。但是resize的时候changeSize可以使其正确的画出来。

**Comment by Yanyan-Wang** [comment]
> 或者有能打开详细log的方法嘛？

项目内可以引用 G6 的 es 产物这样可以 debug 到源码。`import G6 from '@antv/G6/es'`。log 应该没有的，这个应该没有出现报错。minimap 上图形的位置正确的话，说明布局结果是正确的。
看了一下你提供的在线 demo ，写法没有问题，有可能与局部刷新有关，这样把它关掉：
```javascript
graph.get('canvas').set('localRefresh', false);
```
在 render 前调用。

**Comment by ghoshorn** [comment]
> > 或者有能打开详细log的方法嘛？
> 
> 项目内可以引用 G6 的 es 产物这样可以 debug 到源码。`import G6 from '@antv/G6/es'`。log 应该没有的，这个应该没有出现报错。minimap 上图形的位置正确的话，说明布局结果是正确的。
> 看了一下你提供的在线 demo ，写法没有问题，有可能与局部刷新有关，这样把它关掉：
> 
> ```js
> graph.get('canvas').set('localRefresh', false);
> ```
> 
> 在 render 前调用。

好的，多谢，我加上再试试。另外再问下，render之后还可以再次enable局部刷新的吧？ 以保证后面nodes太多的性能问题

**Comment by Yanyan-Wang** [comment]
可以的，最好延迟一些（比如 16ms 或更大）设置，因为渲染都是异步的。
