### ISSUE TITLE
动态渲染数据后，如何根据画布元素的高度重置画布的大小

### ISSUE THREAD

**Issue by zhujinrui** [antvis/G6#1707]
初始化时，写死了container的初始高度和和宽度，想要在页面渲染完后，再获取canvas子元素的高度来重置画布的大小，偶尔出现画布高度加载不全的情况。应该是此时画布的元素还没全部加载完。将画布重置逻辑放到 afterlayout回调函数中，没执行到。
graph.on('afterlayout', () => {
      const canvas = graph.get('canvas');
      const children = canvas.get('children');
      const box = children[0].getCanvasBBox();
       graph.changeSize(box.width,  box.height);
   })
没反应

**Comment by Yanyan-Wang** [comment]
afterlayout 要在 render 之前调用。否则 render 中布局已经执行完了才绑上监听就会监听不到。
```
graph.on('afterlayout', () => {
const group = graph.get('group');
const box = group.getCanvasBBox();
graph.changeSize(box.width, box.height);
})
```

**Comment by Nancy2013** [comment]
> afterlayout 要在 render 之前调用。否则 render 中布局已经执行完了才绑上监听就会监听不到。
> 
> ```
> graph.on('afterlayout', () => {
> const group = graph.get('group');
> const box = group.getCanvasBBox();
> graph.changeSize(box.width, box.height);
> })
> ```

你好，想问下，在@antv/g6  v5.0.1版本中 graph.get('group')提示不存在，可以通过什么方式获取画布元素高度，然后重置画布的大小

**Comment by zhujinrui** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
