### ISSUE TITLE
鼠标单击节点左键，控制台会输出TypeError: this.graph.findDataById is not a function，这是什么原因？

### ISSUE THREAD

**Issue by littlekuo** [antvis/G6#1708]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
提供一下复现的在线 demo

**Comment by baizn** [comment]
findDataById 是 TreeGraph 上的方法，Graph 上面没有这个方法

**Comment by GentlemanSu** [comment]
请问这个问题解决了吗，我也遇到了这个问题

**Comment by Lee-bro** [comment]
modes: {
    default: [
      {
        // 定义展开/收缩行为
        type: 'collapse-expand',
      },
      'drag-canvas',
    ],
  },
我也遇到过，是因为在modes里写了collapse-expand行为，这是树图布局的行为，用在一般布局里会报错。删掉就好了
