### ISSUE TITLE
html类型节点的放大缩小问题

### ISSUE THREAD

**Issue by liuzhiyong2012** [antvis/g6#171]
html类型节点在放大和缩小过程中，除了关键形会放大和缩小外，html节点不能完美地放大和缩小，请问有办法解决吗？

**Comment by TomHuangCN** [comment]
html 节点不支持缩放，需要缩放要用 canvas 节点

**Comment by zx8887** [comment]
其实还是挺好实现的。你自定义节点里面先画canvas节点，然后再画一个html节点。然后draw的时候获取canvas节点的size去设置html节点的高宽就行了。。
