### ISSUE TITLE
新增节点填充色失效

### ISSUE THREAD

**Issue by cofjee** [antvis/G6#1710]
新增节点填充色概率性变成透明色
![image](https://user-images.githubusercontent.com/20319834/85190514-b57abd00-b2eb-11ea-83b0-37c03b645778.png)

- **G6 Version**:  3.5.6
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by cofjee** [comment]
发现，如果nodeStatestyle里面定义的fill 跟 registNode里面的fill定义一样的话就会出现这个问题，具体原因看代码没看出来。

**Comment by Yanyan-Wang** [comment]
麻烦提供一下在线复现 demo

**Comment by baizn** [comment]
应该和 https://github.com/antvis/G6/issues/1741 这个是同一个原因，3.5.11 发布后你更新到最新看下

**Comment by Yanyan-Wang** [comment]
v3.5.11 已发布
