### ISSUE TITLE
How to configure compatibility with mobile devices?

### ISSUE THREAD

**Issue by mostopalove** [antvis/G6#1711]
Is it possible to manage the graph from a mobile phone?
How to use the built-in graph behavior on mobile devices?

- **G6 Version**: 3.5.3
- **Platform**: iOS/Android

**Comment by JohnnyLuv** [comment]
same

**Comment by crystalwm** [comment]
webview

**Comment by crystalwm** [comment]
you can try the webview to load the graph  on the mobile phone

**Comment by Yanyan-Wang** [comment]
zoom in/out works on mobile in v4.2.1 now
