### ISSUE TITLE
Are there way ? Not use "graph.on" to get information of nodes highlighted

### ISSUE THREAD

**Issue by quanghuynguyen1902** [antvis/G6#1712]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

I use global variable 'dblclick_node' and when  use graph.on("dbclick:node"),  I save information node clicked to "dblclick_node", console.log still working but "dblclick_node" is undefined when I use at another time. That means "dblclick_node" didn't save information 

```javascript
     graph.on("node:dblclick", function(e) {
        const item = e.item;
        let node_selected = {
          id: item._cfg.model.id,
          name: item._cfg.model.name,
          so_hieu: item._cfg.model.so_hieu,
          loai_van_van: item._cfg.model.loai_van_ban,
          ngay_ban_hanh: item._cfg.model.ngay_ban_hanh,
          tinh_trang: item._cfg.model.tinh_trang
         }
       this.dbclick_node = node_selected;
      console.log(node_selected)
        };)
```

**Comment by Yanyan-Wang** [comment]
I'm not sure if this assignment was called before you use `dblclick_node` in your program. If so, it should work.

And another possible reason is whether the `this` is the correct pointer, maybe you can console it to verify.

**Comment by quanghuynguyen1902** [comment]
graph.on('afteractivaterelations', e => {
  // e.item is the highlighted node
  // e.action is 'activate' or 'deactivate' to indicates whether you are hovering or leaving the node
});

I doesn't use that function. Are you get the example?

**Comment by Yanyan-Wang** [comment]
> graph.on('afteractivaterelations', e => {
> // e.item is the highlighted node
> // e.action is 'activate' or 'deactivate' to indicates whether you are hovering or leaving the node
> });
> 
> Are you get the example about that function ?


It is triggered by behavior [activate-relations](https://g6.antv.vision/en/docs/manual/middle/states/defaultBehavior#activate-relations).
