### ISSUE TITLE
使用布局的图的combo存在收起展开后位置还原的问题

### ISSUE THREAD

**Issue by yfzm01** [antvis/G6#1713]
拖动分组到任意位置，双击收起，再双击展开，发现分组里面的节点位置被还原到拖动前的位置，而不是拖动后的位置。只要是使用了布局的都存在这个问题，无论是force，circular，grid。不使用布局的不存在这个问题。这算是bug吗，用户体验十分不友好.
重现地址：https://codepen.io/yfzm01/pen/gOPmKmX。
操作步骤：
1.拖动分组到任意位置
2.双击收起
3.再次双击展开

**Comment by Yanyan-Wang** [comment]
上述重现地址 404 (Page Not Found)

如果使用内置 behavior [collapse-expand-combo](https://g6.antv.vision/zh/docs/manual/middle/states/defaultBehavior#collapse-expand-combo)，每次收缩展开会触发重新布局，这个是为了根据现有内容进行布局使其紧凑。如果你不想这样，可以监听 combo:click 或者 combo:dblclick 自己调用 [graph.collapseExpandCombo](https://g6.antv.vision/zh/docs/api/Graph#collapseexpandcombocombo)

**Comment by yfzm01** [comment]
@Yanyan-Wang 按照你说的双击调用graph.collapseExpandCombo，收起的时候组内的子节点是不见了，但是组的宽高并没有变化，好的用户体验不是收起的时候组缩小，展开的时候组撑开吗？有什么好的处理方案吗
