### ISSUE TITLE
边的状态样式，在移动相关节点前后表现不一致

### ISSUE THREAD

**Issue by wqcstrong** [antvis/G6#1715]
- **G6 Version**: 3.5.6
- **Platform**: MacOS 10.15.5
- **Mini Showcase(like screenshots)**:
    1. 点击边，边获取select状态样式变成红色；
    2. 鼠标移出边，点击画布，边移除select状态样式；
    3. 重复上述两步，状态样式的获取和表现都没问题；
    4. 移动任意节点
    5. 点击边，边获取select状态样式变成红色；
    6. 鼠标移出边，select样式丢失。（与期望的不一致）
- **CodePen Link**: [codepen link](https://codepen.io/WQC/pen/gOPmdbb?editors=1010)

**Comment by baizn** [comment]
是个 BUG，下个版本修复。

**Comment by Yanyan-Wang** [comment]
v3.5.8 已修复。
