### ISSUE TITLE
mouseleave在锚点上move和内部move的时候也会触发？

### ISSUE THREAD

**Issue by jumodada** [antvis/G6#1717]
- **G6 Version**:3.5.2
- **codesandbox Link**:https://codesandbox.io/s/g6-test-5i3tg

问题
- 监听的mouseleave事件，在锚点上hover的时候或者在元素内部move的时候也会触发这个事件。
- 移出元素的时候`event.type`是`mouseleave`。但是上诉的情况type是mouseenter，在anchor-active文件里面打印可以看出来。 而且`type==='mouseenter'`的情况是用setTimeout延时在下一个tick里面打印的。

**Comment by Yanyan-Wang** [comment]
链接代码报错，anchor-shape.js 为空

**Comment by jumodada** [comment]
> 链接代码报错，anchor-shape.js 为空

很抱歉，下午改的时候没有保存。现在可以了，麻烦看看，在anchor-active里面的console.log。

**Comment by Yanyan-Wang** [comment]
3.x 之后不支持这种注册 anchor 的方式来写。
其实只需要在自定义节点里面通过 addShape 增加小圆形作为 anchor 即可。指定各个小图形的 name，在监听 graph.on('node:mouseenter', evt ={}) graph.on('node:mouseleave', evt ={}) 中的 evt.target.get('name') 可以判断当前操作的是哪个图形，然后作出不同响应。例子：https://codepen.io/Yanyan-Wang/pen/dyGWXZe?editors=0010

若使用的是内置节点，有 linkPoints 可以直接用。https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/circle#linkpoints

**Comment by jumodada** [comment]
> 3.x 之后不推荐这种注册 anchor 的方式来写。
> 
> 其实只需要在自定义节点里面通过 addShape 增加小圆形作为 anchor 即可。指定各个小图形的 name，在监听 graph.on('node:mouseenter', evt ={}) graph.on('node:mouseleave', evt ={}) 中的 evt.target.get('name') 可以判断当前操作的是哪个图形，然后作出不同响应。例子：https://codepen.io/Yanyan-Wang/pen/dyGWXZe?editors=0010
> 
> 若使用的是内置节点，有 linkPoints 可以直接用。https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/circle#linkpoints

明白了，非常感谢。昨天搞了一下午，现在算是解决了
