### ISSUE TITLE
Tooltip 位置显示有问题

### ISSUE THREAD

**Issue by mxy2316868975javascript** [antvis/G6#1724]
![image](https://user-images.githubusercontent.com/15233384/85400080-6e5e2780-b58a-11ea-9f4c-a3e7876225ad.png)

![image](https://user-images.githubusercontent.com/15233384/85400107-79b15300-b58a-11ea-8241-8c1b705db743.png)

请问一下是我的姿势用的不对吗

**Comment by mxy2316868975javascript** [comment]
tooltip 与 节点 间隔很大

**Comment by Yanyan-Wang** [comment]
提供一下在线 demo

**Comment by morLight** [comment]
tooltip的dom是和画布canvas在同一级，并且tooltip是absolute定位，所以你试试限定canvas父元素盒子的宽高和画布相同，并且设置相对定位

**Comment by Yanyan-Wang** [comment]
对原理感兴趣可以看一下这篇文章：https://www.yuque.com/antv/g6-blog/gp2dxk

**Comment by mxy2316868975javascript** [comment]
我把代码放到codesandbox上显示是没问题的，可能是项目中的样式覆盖掉了，有什么方法debug吗？

**Comment by mxy2316868975javascript** [comment]
> 提供一下在线 demo

我把代码放到codesandbox上显示是没问题的，可能是项目中的样式覆盖掉了，有什么方法debug吗？

**Comment by Yanyan-Wang** [comment]
那就用常规的前端 debug 方法看看哪里覆盖了。

**Comment by beizhedenglong** [comment]
> tooltip的dom是和画布canvas在同一级，并且tooltip是absolute定位，所以你试试限定canvas父元素盒子的宽高和画布相同，并且设置相对定位

**Comment by beizhedenglong** [comment]
> tooltip的dom是和画布canvas在同一级，并且tooltip是absolute定位，所以你试试限定canvas父元素盒子的宽高和画布相同，并且设置相对定位

thanks!!!! 这个库用的我太蛋疼了！
