### ISSUE TITLE
graph.setItemState如果两次都设置为true则第二次不会生效

### ISSUE THREAD

**Issue by zimudehub** [antvis/G6#1727]
描述一下业务场景，当用graph.setItemState(item,'type',true)设置了某个节点的状态为true，然后因为一些需求在该节点true状态下手动修改了某些样式时，然后再次调用graph.setItemState(item,'type',true)想回到修改之前的样式时,这时graph.setItemState(item,'type',true)不生效，需要先调用graph.setItemState(item,'type',false)然后再调用graph.setItemState(item,'type',true)才生效，不知道官方在设计的时候，这是不是故意这么设计的，如果是的话想讨教一下这么设计的理念。

**Comment by baizn** [comment]
是这样设计的，如果已经存在某种状态，则不允许再设置 https://github.com/antvis/G6/blob/master/src/graph/controller/item.ts#L430

> 然后因为一些需求在该节点true状态下手动修改了某些样式时

这个就是另一个状态了。
