### ISSUE TITLE
Bug: createCombo() with parentId cause display abnormally

### ISSUE THREAD

**Issue by bpqd** [antvis/G6#1729]
使用createCombo方法创建带有parentId的嵌套组合时，导致组合的显示异常。

Using createCombo method with parentId parameter will cause combos to display abnormally.

- **G6 Version**: 3.5.7
- **Reproduction Link**: https://stackblitz.com/edit/react-j8eec5?file=index.js

**Comment by Yanyan-Wang** [comment]
下个小版本解决
