### ISSUE TITLE
G6 中数据过长，如何下载完整图像？

### ISSUE THREAD

**Issue by Liuqing650** [antvis/g6#173]
这个问题为 `canvas` 的一个问题，遇到了感觉难以解决，想请教是否有处理方法。
使用G6树形图的时候，少量数据时下载的图形较为清晰，一旦数据量过于庞大时(最小缩放比例都超出画布范围)，此时如果需要下载该图像的时候，往往下载的图像只有画布中的数据，且应为数据庞大，造成数据显示的很小，非常模糊。

下载图片
[https://codepen.io/Liuqing650/pen/jZeabr](https://codepen.io/Liuqing650/pen/jZeabr)

**Comment by TomHuangCN** [comment]
感觉你应该在产品的设计层面屏蔽问题

**Comment by Liuqing650** [comment]
好的，谢谢

**Comment by fuyuZERO** [comment]
我也有这个问题，有什么解决办法么？

**Comment by Liuqing650** [comment]
@fuyuZERO d3.js 去做，`canvas` 受浏览器最大宽度限制，能扩展的宽度有限
