### ISSUE TITLE
treeGraph点击详情展开树节点，并且updateItem更新同层节点的下，y，是节点下移，但是一旦收缩，展开子节点，同级的节点就重合

### ISSUE THREAD

**Issue by yangjialing** [antvis/G6#1733]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by yangjialing** [comment]
1，G6是最新版本
2，谷歌和火狐
3，  

> 
>  展开详情
>       // 下方的节点下移
>       leftNodes.forEach(leftNode => {
>         leftNode.getModel().y = leftNode.getBBox().y + 80;
>         graph.updateItem(leftNode, {
>           y: leftNode.getBBox().y + nodeHeight - cfg.nodeHeight
>         });
>       });


 伸缩，展开，
```
 {
        type: "collapse-expand",
        // 判断是否开始伸缩
        shouldBegin: function shouldBegin(e) {
          console.log(
            "shouldBegin",
            e.target.get("className") === "collapse-icon"
          );
          // 点击 node 禁止展开收缩，只有在点击到的是伸缩icon的时候才允许伸缩
          return e.target.get("className") === "collapse-icon";
        },
        // 伸缩状态发生改变
        onChange: function onChange(item, collapsed) {
          const icon = item.get("group").findByClassName("collapse-icon-num");
          icon.attr("text", collapsed ? item.getModel().children.length : "-");
        }
      },
```
期望结果：
希望同级节点不重叠在一起

CodePen Link: [(https://codesandbox.io/s/quirky-khayyam-wb99v?file=/index.js:9139-9375)](url)

**Comment by yangjialing** [comment]
CodePen Link: https://codesandbox.io/s/quirky-khayyam-wb99v?file=/index.js:9139-9375

**Comment by Yanyan-Wang** [comment]
每个节点必须有 unique string id

**Comment by Yanyan-Wang** [comment]
可以配置 layout 的 getHeight 使每个节点在布局上占大一些的高度空间。
