### ISSUE TITLE
图未能在画布居中请问是什么原因，我按照官网的属性加上也无效

### ISSUE THREAD

**Issue by mxy2316868975javascript** [antvis/G6#1734]
![image](https://user-images.githubusercontent.com/15233384/85940208-a62feb00-b94d-11ea-998a-8ec8e0fe6d6b.png)
![image](https://user-images.githubusercontent.com/15233384/85940238-d7a8b680-b94d-11ea-99c6-9af62684b1af.png)
![image](https://user-images.githubusercontent.com/15233384/85940244-e2634b80-b94d-11ea-8288-b73d29d6725e.png)

**Comment by Yanyan-Wang** [comment]
请给出复现的在线 demo。

如果使用了 force 布局，它是异步执行的，需要在布局完成后再调用 graph.fitView(). 
```
graph.on('afterlayout', e => {
  graph.fitView();
})

如需要每次迭代渲染都在画布内部，参考 https://g6.antv.vision/zh/examples/net/forceDirected#forceConstrainedInRect

**Comment by mxy2316868975javascript** [comment]
https://codesandbox.io/s/silly-tereshkova-ld5pu?file=/config.js   这是复现demo @Yanyan-Wang

**Comment by Yanyan-Wang** [comment]
我这儿看到是居中的，你看看你那儿是不是图容器的宽度设置得超过父容器了，审查元素看下。

![image](https://user-images.githubusercontent.com/29593318/85944418-244dbb00-b969-11ea-85f3-3565f5bb867a.png)


另外，fitView 和 fitCenter 用一个就行。区别参见: https://g6.antv.vision/zh/docs/api/Graph#g6graph
