### ISSUE TITLE
图未能在画布居中请问是什么原因，我按照官网的属性加上也无效

### ISSUE THREAD

**Issue by mxy2316868975javascript** [antvis/G6#1737]
https://codesandbox.io/s/silly-tereshkova-ld5pu?file=/config.js 

![image](https://user-images.githubusercontent.com/15233384/85946133-bf985d80-b974-11ea-955e-2398ad99690f.png)

并没有居中

**Comment by mxy2316868975javascript** [comment]
![image](https://user-images.githubusercontent.com/15233384/85946133-bf985d80-b974-11ea-955e-2398ad99690f.png)

**Comment by Yanyan-Wang** [comment]
应该是因为第一次绘制边的时候，还没有布局，节点没有 x y 信息，边也就没有正确的路径位置，导致第一次 afterDraw 的时候，startPoint 是 (-100.5, 0)。可以看到每次刷新的时候，边上那个蓝色圆点会先闪现在左上角，然后回到边上。因此第一次绘制完成的时候实际上图的范围是从 (-100.5, 0) 开始的，fitView 的时候计算的图 bbox 大小是第一次绘制的大小。考虑这样改：

方法一：
实例化图时不要配置 fitView 和 fitCenter。render 语句后 setTimeout 16ms（一次绘制的事件） 调用 fitVIew：
```javascript
graph.render();
setTimeout(() => {
  graph.fitView();
}, 16)
```
这个方法有一个问题是每次刷新的时候会稍微闪一下。

方法二：
afterDraw 方法里使用 setTimeout 延后添加带动画的 circle，这样可以保证在添加 circle 图形的时候已经有了正确的节点位置：

```javascript
G6.registerEdge(
  "circle-running",
  {
    afterDraw(cfg, group) {
      setTimeout(() => {
        const shape = group.get("children")[0];
        let startPoint = shape.getPoint(0);
        const circle = group.addShape("circle", ...
        circle.animate( ...
      }, 16);
    }
  },
  "cubic"
);
```
