### ISSUE TITLE
G6 支持第三方组件库的icon吗？ （ps: 非icnofont，自己公司的组件库的icon）

### ISSUE THREAD

**Issue by zhangmengyi** [antvis/G6#1738]
如题所示。

**Comment by Yanyan-Wang** [comment]
Canvas 不支持。SVG 渲染引擎的话，自定义节点可以用 [DOM 图形](https://g6.antv.vision/zh/docs/api/nodeEdge/shapeProperties#dom-svg)，但是只支持原生 DOM。

用图片是可以的，几种[内置节点](https://g6.antv.vision/zh/examples/item/defaultNodes)可以在中间放一个图片作为 icon。[自定义节点](https://g6.antv.vision/zh/examples/item/customNode)也可以自行添加 image 图形。

另外就是可以做成 [Iconfont 使用](https://g6.antv.vision/zh/docs/manual/advanced/iconfont)。
