### ISSUE TITLE
求问G6，最新版+，如何能把溢出文本，用...表示，并且悬浮提示出现全部内容

### ISSUE THREAD

**Issue by zhangmengyi** [antvis/G6#1739]
如题
![image](https://user-images.githubusercontent.com/30336413/85950207-09417200-b98e-11ea-9c31-3ea730665ff3.png)

**Comment by Yanyan-Wang** [comment]
超长文本处理 demo：https://g6.antv.vision/zh/examples/item/label#labelLen
然后把未处理前文本用 tooltip 展示：https://g6.antv.vision/zh/examples/tool/tooltip

**Comment by zhangmengyi** [comment]
添加后，悬浮框位置，不在鼠标附近。
![image](https://user-images.githubusercontent.com/30336413/85966030-2c513d80-b9f1-11ea-877b-18610c506088.png)

**Comment by Yanyan-Wang** [comment]
应该和你容器 DOM 的定位方式有关系。
