### ISSUE TITLE
updateItem更新一个有状态样式stateStyle的shape，会导致后续通过addItem添加此shape类型的originStyle异常

### ISSUE THREAD

**Issue by zc-1028** [antvis/G6#1741]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

`ItemBase.prototype.getShapeStyleByName = function (name) {
    var _this = this;

    var group = this.get('group');
    var currentShape = this.getKeyShape();

    if (name) {
      currentShape = group.find(function (element) {
        return element.get('name') === name;
      });
    }

    if (currentShape) {
      var styles_1 = {}; // 这里要排除掉所有 states 中样式

      var states = this.get('states');
      states.map(function (state) {
        var style = _this.getStateStyle(state);

        for (var key in style) {
          if (!isPlainObject(style[key])) {
            if (!RESERVED_STYLES.includes(key)) {
              RESERVED_STYLES.push(key);
            }
          } else {
            var subStyle = style[key];

            for (var subKey in subStyle) {
              if (!RESERVED_STYLES.includes(subKey)) {
                RESERVED_STYLES.push(subKey);
              }
            }
          }
        }
      });
      each(currentShape.attr(), function (val, key) {
        if (RESERVED_STYLES.indexOf(key) < 0) {
          styles_1[key] = val;
        }
      });
      return styles_1;
    }

    return {};
  };`
更新一个有状态样式（比如stroke）的shape之后，RESERVED_STYLES会加上stroke，后续添加此shape类型的originStyle就会没有stroke属性了，不知道有没有理解错

**Comment by Yanyan-Wang** [comment]
可以写一个复现的在线 demo 看一下

**Comment by zc-1028** [comment]
> 可以写一个复现的在线 demo 看一下
https://codepen.io/zc-1028/pen/vYLLXgV?editors=1010
先依次点击前三个按钮 然后最后一个点两下

**Comment by Ynewtime** [comment]
这个 bug 我也遇到很多次... 之前用的规避方案是手动重新注册一个自定义节点，然后在 afterDraw 方法中手动更新 shape 的 style

**Comment by zc-1028** [comment]
@Yanyan-Wang

**Comment by Yanyan-Wang** [comment]
尽量下个小版本修复

**Comment by Ireliana** [comment]
这个问题修复了吗？

**Comment by Yanyan-Wang** [comment]
v3.5.11 已修复
