### ISSUE TITLE
Mini Map taking the whole horizontal space in the canvas

### ISSUE THREAD

**Issue by JyotsnaC** [antvis/G6#1743]
- **G6 Version**: 3.5.7
- **Platform**: MacOS 
- **Mini Showcase(like screenshots)**:
- **CodePen Link**: https://codesandbox.io/s/vpmpm

When I add mini map it is taking away the space in the container. Is there a way I can add mini map outside the div container.
<img width="997" alt="Screen Shot 2020-06-28 at 11 49 58 PM" src="https://user-images.githubusercontent.com/274296/85974154-693e1580-b99a-11ea-9342-72a57de0bd14.png">

**Comment by Yanyan-Wang** [comment]
Maybe just set the position of DOM with classname 'g6-minimap' to 'absolute' and assign top/bottom/left/right for it:
```
insertCss(`
  .g6-minimap {
    position: absolute;
    top: 10px;
  }
//...
`);
```
