### ISSUE TITLE
如何生成问题中图的结构样式

### ISSUE THREAD

**Issue by hb1005642457** [antvis/G6#1745]
![微信图片_20200629155257](https://user-images.githubusercontent.com/32795466/85987806-bb297e80-ba20-11ea-81ea-01b68cd3f7fe.png)
如上图，在node定义的是modelRect，edge定义的是polyline，layout 的type dendrogram，这种情况下如何生成上面图片中的结构，假设有三级数据。

**Comment by Yanyan-Wang** [comment]
dendrogram 适用于树图。一般图考虑用 dagre 布局。polyline 可以自己指定 controlPoints 来决定弯曲位置，可以直接在数据中指定；也可以自定义折线边，类似：https://g6.antv.vision/zh/examples/item/customEdge#customPolyline2
