### ISSUE TITLE
自定义 dom 问题

### ISSUE THREAD

**Issue by LENZAKON** [antvis/G6#1746]
hello，自定义 dom 节点，内置的 behavior：drag-node 及 自定义的 behavior 无效，请问这需要怎么处理吗？

**Comment by LENZAKON** [comment]
demo: https://codesandbox.io/s/wizardly-shape-0f7h4?file=/index.js:1465-1477

**Comment by Yanyan-Wang** [comment]
DOM 图形节点不支持 G6 内部事件。文档中已经说明：https://g6.antv.vision/zh/docs/api/nodeEdge/shapeProperties#dom-svg
需要使用原生事件模拟，例如：https://g6.antv.vision/zh/examples/item/customNode#svgDom

推荐使用 Canvas，在自定义节点的时候使用各种图形组合， Canvas 性能比 SVG 好。
