### ISSUE TITLE
E2E test cases for G6 using Canvas

### ISSUE THREAD

**Issue by shrivathsagkumar** [antvis/G6#1749]
I am using G6, I wanted to know how to perform E2E test cases if I am using G6 to be rendered in Canvas element.

**Comment by Yanyan-Wang** [comment]
Which kind of test? Maybe you can refer to [G6's test cases](https://github.com/antvis/G6/tree/master/tests/unit). We have lots of test cases about interaction, rendering, calculation, and other aspects.

For example, about interactions, trigger the mouseenter event by:
https://github.com/antvis/G6/blob/fc24b0dc865ec96b4fdd6a2ec2e2b21d6654f8db/tests/unit/behavior/activate-relations-spec.ts#L90

**Comment by shrivathsagkumar** [comment]
We are using G6 for showing nodes, edges, combos on the canvas. We want to automate the visual testing for the nodes, edges & combos. We are looking for a tool like cypress/protractor to achieve the same. Do you have a recommendation?

**Comment by Yanyan-Wang** [comment]
I don't know if there is any tools like cypress/protractor for canvas. But I think you can achieve it by triggering the interactions and events with `graph.emit` and `setTimeout`.
