### ISSUE TITLE
快速点击多次画布后，拖动画布异常

### ISSUE THREAD

**Issue by zc-1028** [antvis/G6#1750]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:https://codepen.io/Yanyan-Wang/pen/mdbYZvZ

之前关闭的一个issue，先快速单击三下画布，再拖动

**Comment by Yanyan-Wang** [comment]
我这里没出现异常。会出现什么样的异常？你的操作系统和浏览器是？

**Comment by zc-1028** [comment]
> 我这里没出现异常。会出现什么样的异常？你的操作系统和浏览器是？

点击三下后，再次按下拖动画布不会动，释放鼠标按键，画布会跟随光标动。macOS/Chrome 81

**Comment by Yanyan-Wang** [comment]
我按照你的描述操作还是没有出现，我的是 macOS/Chrome 83，应该不会有差别。firefox 70，safari 12.1.1  也都没复现。也许你可以录制一下屏幕我看下是不是我操作得不对。

**Comment by zc-1028** [comment]
> 我按照你的描述操作还是没有出现，我的是 macOS/Chrome 83，应该不会有差别。firefox 70，safari 12.1.1 也都没复现。也许你可以录制一下屏幕我看下是不是我操作得不对。

点击三下之后应该是选中了什么东西，这个时候复制粘贴会发现有个换行符，并且再拖动的时候光标附近有个地球的icon

**Comment by Yanyan-Wang** [comment]
确定是你发的这个 codepen 链接就能复现吗？我赋值粘贴是会有个换行符，但是再拖动没有地球 icon 出现。

**Comment by zc-1028** [comment]
> 确定是你发的这个 codepen 链接就能复现吗？我赋值粘贴是会有个换行符，但是再拖动没有地球 icon 出现。


[demo.mov.zip](https://github.com/antvis/G6/files/4849863/demo.mov.zip)
这是录屏 麻烦看下哈

**Comment by Yanyan-Wang** [comment]
这个压缩包下载不下来，可能是公司电脑会检测风险

**Comment by Enivia** [comment]
> 确定是你发的这个 codepen 链接就能复现吗？我赋值粘贴是会有个换行符，但是再拖动没有地球 icon 出现。

实际上是user select焦点在其它地方。可以通过在画布周围放一个input框复现。
拖动时，鼠标经过input使其内容被选中，在被选中时松开鼠标再拖动就会出现画布随鼠标移动的情况。
[codepen](https://codepen.io/EniviaQ/pen/gOPXXom)

**Comment by Yanyan-Wang** [comment]
> > 确定是你发的这个 codepen 链接就能复现吗？我赋值粘贴是会有个换行符，但是再拖动没有地球 icon 出现。
> 
> 实际上是user select焦点在其它地方。可以通过在画布周围放一个input框复现。
> 拖动时，鼠标经过input使其内容被选中，在被选中时松开鼠标再拖动就会出现画布随鼠标移动的情况。
> [codepen](https://codepen.io/EniviaQ/pen/gOPXXom)

似乎有一定概率会出现这个情况，我操作了几十次只复现了一次。是否有必现的操作姿势？

**Comment by Enivia** [comment]
> 似乎有一定概率会出现这个情况，我操作了几十次只复现了一次。是否有必现的操作姿势？

是可以百分百复现的，按照原楼主的操作多次点击画布后拖动，我这边也很容易复现画布随鼠标移动的情况。
![input.gif](https://i.loli.net/2020/07/02/ElwTxvOmFfKpjPN.gif) 
![多次点击.gif](https://i.loli.net/2020/07/02/Pe7c6NqQgvt9YHb.gif)

**Comment by Yanyan-Wang** [comment]
我发现了一个我这里可以必现的姿势，按住 control 拖一次，然后松开再拖一次。我跟进一下看看

**Comment by Yanyan-Wang** [comment]
定位到问题是因为三次点击画布会选中 grid 插件的 DOM 元素，导致拖拽的时候是在拖拽 grid DOM 元素，使画布拖拽某些行为判断失效。下个小版本会把 grid DOM 加上 `user-select: none` 属性禁止拖拽，这个三次点击再拖拽画布异常的问题就可以解决。

而且这个问题是与浏览器版本、设置相关，在有些浏览器下不容易复现，特别是附近有输入框的情况。这是由于有些浏览器设置是默认禁止 DOM 被拖拽的，就不会出现画布拖拽异常的情况。G6 会尽量把内置 DOM 都通过 `user-select: none`  禁止拖拽，而用户在实现时应当避免画布拖拽范围内放置其他允许拖拽的 DOM。

**Comment by Yanyan-Wang** [comment]
v3.5.10 已修复

**Comment by zhangbing3** [comment]
这个问题还存在的，拖动元素，鼠标出了父窗体到外围dom，windows电脑就会，mac电脑目前是不会的。

**Comment by zhangbing3** [comment]
把画布周围的dom全部是设置成了user-select: none，问题解决了。
