### ISSUE TITLE
minimap的蓝色框展现不完全

### ISSUE THREAD

**Issue by zwhrcx0612** [antvis/G6#1751]
minimap的蓝色框框，左边和上边出去了，怎么能够让它始终在框框内
![image](https://user-images.githubusercontent.com/34915727/86108567-e500a500-baf5-11ea-92b2-4c508ad1d85a.png)
![image](https://user-images.githubusercontent.com/34915727/86108577-e9c55900-baf5-11ea-9396-9dec06e2c946.png)

**Comment by Yanyan-Wang** [comment]
设计上就是这样的，代表主图的内容范围就是蓝框内的范围。蓝框的长款比永远与主图一致，超出部分隐藏。
