### ISSUE TITLE
[Feature Request] combo 在 dagre 下互斥 & combo 节点内部间距配置

### ISSUE THREAD

**Issue by xuguangheng** [antvis/G6#1752]
- **G6 Version**: 3.5.0
- **Platform**: Mac OS
- **Mini Showcase(like screenshots)**: 

- **CodePen Link**:

目前在 ``dagre`` layout 里面使用 ``combo`` 的时候，``combo``会叠在一起。
<img width="809" alt="Screen Shot 2020-06-30 at 4 54 39 PM" src="https://user-images.githubusercontent.com/45193488/86105831-69512900-baf2-11ea-8c32-252de5fe16e9.png">

又因为``dagre``的节点排列没有考虑到``combo``的问题，所以即使手动挪开``combo``，一个``combo``内部的节点之间的间距可能会很远。
<img width="795" alt="Screen Shot 2020-06-30 at 4 55 25 PM" src="https://user-images.githubusercontent.com/45193488/86105919-84bc3400-baf2-11ea-8b70-b057aa6ea1a6.png">

希望``dagre`` 可以支持combo互斥的配置，以及combo内部节点间距的配置。
如果能够支持这个feature的话，combo或许可以用来解决  #1462 。

**Comment by Yanyan-Wang** [comment]
短期内暂时不会支持，欢迎 PR。目前可以看下这里的解法 https://github.com/antvis/G6/issues/1747
