### ISSUE TITLE
在TreeGraph中能否使用combo

### ISSUE THREAD

**Issue by cofjee** [antvis/G6#1753]
treegraph是extend graph的，
但是它的data结构中没用定义combos数组，且layout是走自己一套没有去查看combo是否定义。
但是从graph打印情况来看的话是有combo的，请问treegraph中能使用combo吗？如果可以有例子吗?

- **G6 Version**:  3.5.6
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
TreeGraph 暂不支持 combo，短期内也没有排期计划支持，欢迎社区 PR。

暂时可以用 Graph 的 dagre 布局模拟树，在 dagre 中使用 combo 需要注意布局算法只与节点和边的关系有关，不会考虑 combo 信息，参考 https://github.com/antvis/G6/issues/1747。

**Comment by cofjee** [comment]
> TreeGraph 暂不支持 combo，短期内也没有排期计划支持，欢迎社区 PR。
> 
> 暂时可以用 Graph 的 dagre 布局模拟树，在 dagre 中使用 combo 需要注意布局算法只与节点和边的关系有关，不会考虑 combo 信息，参考 [https://github.com/antvis/G6/issues/1747。](https://github.com/antvis/G6/issues/1747%E3%80%82)

如果改成drgre布局，绘图速度以及性能会下降吗？
