### ISSUE TITLE
打包后运行报错

### ISSUE THREAD

**Issue by az674lqs** [antvis/G6#1756]
Uncaught TypeError: Super expression must either be null or a function
    at g6.min.js:31541
    at g6.min.js:31540
    at Module.e.exports (g6.min.js:31539)
    at n (g6.min.js:14)
    at e.exports (g6.min.js:50)
    at Object.<anonymous> (g6.min.js:4)
    at p ((index):1)
    at Module.638 (index.tsx:24)
    at p ((index):1)
    at Object.284 (actions.ts:58)

**Comment by Yanyan-Wang** [comment]
引用 es 产物看看
```
import G6 from '@antv/g6/es'
```

**Comment by az674lqs** [comment]
可以了，感谢

**Comment by webMasterMrBin** [comment]
> 引用 es 产物看看
> 
> ```
> import G6 from '@antv/g6/es'
> ```

这个原因具体是为什么呢 我在自己的项目 只有在production环境下 build完 会报错   在开发环境 直接 import G6 from 'g6'就没问题   跟g6默认导出的模块类型有关么

**Comment by webMasterMrBin** [comment]
> > 引用 es 产物看看
> > ```
> > import G6 from '@antv/g6/es'
> > ```
> 
> 这个原因具体是为什么呢 我在自己的项目 只有在production环境下 build完 会报错 在开发环境 直接 import G6 from 'g6'就没问题 跟g6默认导出的模块类型有关么 @Yanyan-Wang

已解决

![image](https://user-images.githubusercontent.com/25171709/93737614-395b8280-fc16-11ea-91dc-84ba464e7d42.png)
这个报错原因是webpack4 production build的uglyfyPlugin 的配置
https://github.com/airbnb/react-with-styles/issues/151
https://github.com/mishoo/UglifyJS/issues/3015   

在我使用的项目中根本原因是用的g6 导出的默认的是取 browser字段的文件 即已经丑化过  build完的文件
![image](https://user-images.githubusercontent.com/25171709/93737774-96573880-fc16-11ea-85d6-631fb41135ec.png)

在项目中webpack4的默认压缩会对 源文件做二次丑化即报该issue错误, 因此手动指定  module 或者 main路径下就可以了
![image](https://user-images.githubusercontent.com/25171709/93737875-dfa78800-fc16-11ea-903b-9d576689cb58.png)

**Comment by heyang1014** [comment]
请问下你是怎么解决的，我也遇到这个问题了。改了产物的引入还是不行

**Comment by yaowencurry** [comment]
> 请问下你是怎么解决的，我也遇到这个问题了。改了产物的引入还是不行

你解决了吗？
