### ISSUE TITLE
cdn访问404

### ISSUE THREAD

**Issue by mxy2316868975javascript** [antvis/G6#1758]
<script src="https://gw.alipayobjects.com/os/antv/pkg/_antv.g6-{$3.5.7}/dist/g6.min.js"></script>
  
![image](https://user-images.githubusercontent.com/15233384/86373846-7454b680-bcb6-11ea-850d-24dabbf075cc.png)

**Comment by Yanyan-Wang** [comment]
访问最新的 3.5.9 吧 https://gw.alipayobjects.com/os/antv/pkg/_antv.g6-3.5.2/dist/g6.min.js
