### ISSUE TITLE
@antv/g6 3.5.9 树形结构图报错

### ISSUE THREAD

**Issue by ben-Run** [antvis/G6#1760]
版本：@antv/g6 3.5.9
问题描述：如图所示，建立了多个树形节点之后，点击展开，缩小，会报错，在3.5.7 不存在报错
正常展开 如图
![image](https://user-images.githubusercontent.com/17672822/86437422-2207aa00-bd37-11ea-8108-168c25d5719c.png)
报错截图

线条没有了，而且报错
![image](https://user-images.githubusercontent.com/17672822/86437702-9fcbb580-bd37-11ea-8d04-facb3c0b9bce.png)

![image](https://user-images.githubusercontent.com/17672822/86437672-8e82a900-bd37-11ea-959a-3540d5bd4f32.png)

**Comment by Yanyan-Wang** [comment]
请提供一下复现在线 demo

**Comment by Yanyan-Wang** [comment]
应该是因为你的节点 id 不是 string。节点 id 必须是唯一的 string

**Comment by ben-Run** [comment]
好的，谢谢

**Comment by ben-Run** [comment]
@Yanyan-Wang   好的，谢谢

**Comment by ben-Run** [comment]
@Yanyan-Wang 应该是因为你的节点 id 不是 string。节点 id 必须是唯一的 string。 
id 是string的number 也会出现这个问题，后面我是拼接了真正的字符串进去就好了。
