### ISSUE TITLE
downloadFullImage 调用报错

### ISSUE THREAD

**Issue by MwumLi** [antvis/G6#1761]
- **G6 Version**: 3.5.9
- **Platform**: Mac Chore
- **Mini Showcase(like screenshots)**:  
<img width="1368" alt="sc_20200704144145" src="https://user-images.githubusercontent.com/6889433/86506720-b0962d00-be04-11ea-8143-1f5bc16ab5b8.png">

- **CodePen Link**: 无
- **复现步骤**: 官网任意一个 demo render 之后添加下面代码:  
```javascript
graph.downloadFullImage('default_graph', {
            backgroundColor: '#fff',
            padding: [30, 15, 15, 15]
    }, 'image/png')
```

**Comment by Yanyan-Wang** [comment]
参数顺序不对，看下 API：https://g6.antv.vision/zh/docs/api/Graph#downloadfullimagename-type-imageconfig

**Comment by MwumLi** [comment]
@Yanyan-Wang 你看看你发的文档的示例
![image](https://user-images.githubusercontent.com/6889433/87165880-53671380-c2fd-11ea-862e-7f05ffbad5ae.png)

**Comment by JoMartinezZhu** [comment]
导出的图片为空白
