### ISSUE TITLE
边使用线性渐变报错

### ISSUE THREAD

**Issue by MwumLi** [antvis/G6#1762]
- **G6 Version**: 3.5.9
- **Platform**: Mac Chrome
- **Mini Showcase(like screenshots)**: 
![image](https://user-images.githubusercontent.com/6889433/86507043-8b56ee00-be07-11ea-914c-8053c70baa15.png)

- **CodePen Link**: 无在线链接
- **复现**: 以上基于官网同心圆布局 demo 修改, 只加一行边的线性渐变设置, 但是在官网没报错, 你可以直接在 stackblitz 即可看到错误

**Comment by Yanyan-Wang** [comment]
请提供复现在线 demo

**Comment by baizn** [comment]
没有复现，如下图
![image](https://user-images.githubusercontent.com/9443867/87132173-13d20480-c2c8-11ea-8633-43faf79c5866.png)
