### ISSUE TITLE
无法禁用combo渲染动画

### ISSUE THREAD

**Issue by Tronsfey** [antvis/G6#1763]
- **G6 Version**:3.5.9
- **Platform**:mac
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:https://codesandbox.io/s/combo-animation-disable-error-cd3c4?file=/index.js

期望禁用combo背景的渲染动画，设置animate:false之后发现无效

**Comment by Yanyan-Wang** [comment]
可以暂时这样达到目的： L47
https://codesandbox.io/s/combo-animation-disable-error-3ligv?file=/index.js

**Comment by Tronsfey** [comment]
> 可以暂时这样达到目的： L47
> https://codesandbox.io/s/combo-animation-disable-error-3ligv?file=/index.js

好的，实测这个可以禁用combo的渲染动画，刚好也在试自定义combo来解决；

看源码里面默认combo里面的options.animate是true的，这块应该要跟graph的options.animate关联起来比较合理吧？

**Comment by Yanyan-Wang** [comment]
是的，后面 G6 内部修改一下
