### ISSUE TITLE
自定义节点

### ISSUE THREAD

**Issue by zhaokgithub** [antvis/G6#1764]
我想问下自定义节点支持定义class么？官方的demo没有这块的说明

**Comment by Yanyan-Wang** [comment]
你的原始需求是什么

**Comment by zhaokgithub** [comment]
自定义dom节点的html中的style比较复杂想提取到class中

**Comment by Yanyan-Wang** [comment]
我的理解是你想要给自定义节点的 DOM 图形添加 class 属性，让它可以受外部 css 控制？

这个 demo 中的 DOM 图形 html 属性中有配置 class
https://g6.antv.vision/zh/examples/item/customNode#svgDom

外部 CSS 可以控制，加 important 是因为自定义节点的时候写的样式属性会被转成内联样式，优先级更高。
```
import insertCss from 'insert-css';
insertCss(`
  .dom-node {
    background: #f00 !important;
  }
`);
```
