### ISSUE TITLE
Dom图形对canvas元素的支持

### ISSUE THREAD

**Issue by michaelguo1991** [antvis/G6#1765]
- **G6 Version**: 3.5.10
- **Platform**: Mac OS
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

#### 问题
renderer为svg模式下，Dom图形是否可以支持canvas元素

#### 背景
希望可以在Node节点上绘制echarts图表，threejs的3D图形；两者底层都是canvas绘制

#### 尝试
1. 将有上下文的canvas元素传递给dom的html属性，失败
https://codesandbox.io/s/gallant-smoke-mdqo0?file=/src/registerShape.js
2. 用比较hack的做法，初始化时将html属性置空，下次渲染时拿到dom容器渲染；
  可以绘制出来，但移动画布的时候就会消失
https://codesandbox.io/s/suspicious-sun-9vurn?file=/src/registerShape.js

#### 可能原因
感觉是[下图](https://github.com/antvis/g/blob/master/packages/g-svg/src/shape/dom.ts)中的el.innerHTML赋值方式，会把canvas的context丢失
![image](https://user-images.githubusercontent.com/2106440/86692929-cf7f0400-c03c-11ea-877a-6f53db9645e5.png)

#### 可能方案
1. 是否可以让dom图形的html属性，支持函数，并将容器作为参数，类似于这样
![image](https://user-images.githubusercontent.com/2106440/86694985-b5462580-c03e-11ea-894c-be6a117b52f7.png)

2. 是否可以提供自定义图形的方式，使用方自己去定义基础图形的绘制方式

**Comment by Yanyan-Wang** [comment]
> 是否可以让dom图形的html属性，支持函数，并将容器作为参数，类似于这样

目前没有这个排期，欢迎社区 PR

> 是否可以提供自定义图形的方式，使用方自己去定义基础图形的绘制方式

自定义节点可以自己绘制图形的，推荐用 canvas 版本在自定义节点里面添加图形来画一个图表。类似 demo：https://g6.antv.vision/zh/examples/item/customNode#barChart


年底可能会做和 AntV G2 的打通，到时候应该能够支持用 G2 的图表作为节点。当然，我们非常欢迎社区 PR 🤩。

**Comment by michaelguo1991** [comment]
了解了，多谢
