### ISSUE TITLE
请问下，怎么在节点里显示类似于echarts中的折线图这种的图表呢？

### ISSUE THREAD

**Issue by wrh4585** [antvis/G6#1766]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

是否可以考虑增加在节点上显示类似于echarts或者g2这种的图表的示例？如折线图，柱状图。官方示例中有提供图表的，但是和需求差异较大？是否需要使用自定义的dom节点来实现，具体怎么实现？

**Comment by Yanyan-Wang** [comment]
目前只能使用官网示例的方式，自定义节点，根据数据添加各种图形来绘制一个统计图表。

**Comment by wrh4585** [comment]
使用dom节点的方式，可以在初始化节点的时候显示出来echarts图表，节点也有设置 draggable: true，但是拖动节点时，会将自定义的dom节点里的echarts图表删掉，查看element元素，echarts的canvas元素整个都被删除了，这是因为g6的设计实现里，有对canvas的特殊处理么？

**Comment by Yanyan-Wang** [comment]
目前没有提供这个功能，年底可能会做和 AntV G2 的打通，到时候应该能够支持用 G2 的图表作为节点。

现在建议类似 demo：https://g6.antv.vision/zh/examples/item/customNode#barChart 这样用 canvas 模式下自定义节点添加图形自己画一个图表。

当然，我们非常欢迎社区 PR 🤩

**Comment by wrh4585** [comment]
> 目前没有提供这个功能，年底可能会做和 AntV G2 的打通，到时候应该能够支持用 G2 的图表作为节点。
> 
> 现在建议类似 demo：https://g6.antv.vision/zh/examples/item/customNode#barChart 这样用 canvas 模式下自定义节点添加图形自己画一个图表。
> 
> 当然，我们非常欢迎社区 PR 🤩

好的，我在研究下看看

**Comment by wrh4585** [comment]
> > 目前没有提供这个功能，年底可能会做和 AntV G2 的打通，到时候应该能够支持用 G2 的图表作为节点。
> > 现在建议类似 demo：https://g6.antv.vision/zh/examples/item/customNode#barChart 这样用 canvas 模式下自定义节点添加图形自己画一个图表。
> > 当然，我们非常欢迎社区 PR 🤩
> 
> 好的，我在研究下看看

不好意思，忘记问一个事情，目前节点的anchorPoints，支持在节点内部么？我看现在的节点上的anchor都在节点的边上。

**Comment by Yanyan-Wang** [comment]
anchorPoints 可以任意位置 https://g6.antv.vision/zh/docs/manual/middle/elements/anchorpoint

linkPoints 默认是在边缘上，自定义节点可以画小圆形到任意位置
