### ISSUE TITLE
comboForce Layout is not consistent

### ISSUE THREAD

**Issue by JyotsnaC** [antvis/G6#1767]
G6 Version: 3.5.10
Platform: MacOS
Mini Showcase(like screenshots):
CodePen Link: [Link to the issue](https://codesandbox.io/s/gracious-hamilton-pdh5v)
Layout is not consistent in the comboForce Layout. How can I make layout consistent.

As [suggested](https://github.com/antvis/G6/issues/1672) on adding initial values of x and y do not solve the issue

**Comment by Yanyan-Wang** [comment]
ok, will be fixed by next small version

**Comment by Yanyan-Wang** [comment]
Fixed by 3.5.11
