### ISSUE TITLE
Left to right in Grid view

### ISSUE THREAD

**Issue by JyotsnaC** [antvis/G6#1768]
- **G6 Version**: 3.5.10
- **Platform**: MacOS
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

Can I have nodes aligned from right to left in Grid view layout

**Comment by Yanyan-Wang** [comment]
As listed in the [Grid Layout API](https://g6.antv.vision/zh/docs/api/layout/Graph#grid), it does not support to lay the nodes from right to left. But you can do a post-processing to make a symmetric layout as: 
```
// the axis of symmetry
const symmetryX = graph.get('width') / 2;
// call it before graph.render() to bind listener for afterlayout
graph.on('afterlayout', e => {
  graph.getNodes(node => {
    const model = node.getModel();
    model.x = 2 * symmetryX - model.x;
  });

  // refresh positions
  graph.refreshPositions();
});
```
