### ISSUE TITLE
自定义 combo 无法拖动

### ISSUE THREAD

**Issue by huxiaoyun** [antvis/G6#1769]
- **G6 Version**:  3.5.10
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

https://riddle.alibaba-inc.com/riddles/f129a963

**Comment by Yanyan-Wang** [comment]
因为 combo 的更新逻辑比较复杂，建议通过 afterDraw 、afterUpdate 方法来扩展内置 combo：
https://riddle.alibaba-inc.com/riddles/10a6a8d8

**Comment by huxiaoyun** [comment]
感谢~
