### ISSUE TITLE
G6 节点嵌套问题

### ISSUE THREAD

**Issue by oangy** [antvis/g6#177]
是否可以在某一Node节点中，添加其他Node及Edge，作为一个整体。

![71519805287_ pic](https://user-images.githubusercontent.com/12290338/36776813-1ce2aa6c-1ca2-11e8-8bd4-7a298e563aa4.jpg)

**Comment by Glitiki** [comment]
我也遇到了这个问题，不知道你是怎么解决的。

**Comment by oangy** [comment]
@Glitiki 并没有解决，准备换插件。jsPlumb支持嵌套

**Comment by TomHuangCN** [comment]
2.0 会有群组的概念

2.0 明天（6月6号）开源 && 发布
