### ISSUE TITLE
显示器设置dpr为小数时，图形模糊

### ISSUE THREAD

**Issue by zdfsilence** [antvis/G6#1770]
- **G6 Version**: 3.5.0
- **Platform**: pc
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

现在很多高清笔记本，默认缩放200%，dpr是2。但是用户使用时习惯调成150%或者175%。导致dpr为1.5或者1.75.

查看G6源码发现

```javascript
    /**
     * 获取屏幕像素比
     */
    Canvas.prototype.getPixelRatio = function () {
        var pixelRatio = this.get('pixelRatio') || util_1.getPixelRatio();
        // 不足 1 的取 1，超出 1 的取整
        return pixelRatio >= 1 ? Math.floor(pixelRatio) : 1;
    };
```

目前是强行修改window.devicePixelRatio为向上取整。不知道有没有什么别的办法？

**Comment by Yanyan-Wang** [comment]
升级到最新版本，已经改为向上取整。

也可以手动设置 pixelRatio，直接在实例化图的适配配置 pixelRatio 即可。

**Comment by mostopalove** [comment]
> 升级到最新版本，已经改为向上取整。
> 
> 也可以手动设置 pixelRatio，直接在实例化图的适配配置 pixelRatio 即可。

Can you add code example?

**Comment by soom-lupulus** [comment]
> > 升级到最新版本，已经改为向上取整。
> > 也可以手动设置 pixelRatio，直接在实例化图的适配配置 pixelRatio 即可。
> 
> Can you add code example?

do like this, it'll work well

```js
new G6.Graph({
  ...other options,
 pixelRatio: Math.ceil(window.devicePixelRatio)
})
```
