### ISSUE TITLE
默认结点是否可以增加显示与隐藏功能

### ISSUE THREAD

**Issue by wangwpf** [antvis/G6#1771]
Hi:
     自定义结点上可以通过 visible 来设置结点的显示与隐藏,  希望默认结点也可以增加这个功能

**Comment by Yanyan-Wang** [comment]
[graph.hideItem()](https://g6.antv.vision/zh/docs/api/Graph#hideitemitem-stack)，[graph.showItem()](https://g6.antv.vision/zh/docs/api/Graph#showitemitem-stack)

或 [item.hide()](https://g6.antv.vision/zh/docs/api/nodeEdge/Item#hide)，[item.show()](https://g6.antv.vision/zh/docs/api/nodeEdge/Item#show)

**Comment by Yanyan-Wang** [comment]
希望在节点/边数据中配置 visible: false / true 来控制初次渲染是否隐藏元素

**Comment by baizn** [comment]
> 希望在节点/边数据中配置 onlyShowKeyShape: false / true 来控制初次渲染是否隐藏其他非 keyShape，从而降低首次渲染成本。同时需要设计一个开关，在需要时将其他图形展示出来。

这个建议作为实例化 Graph 时的一个配置项。

**Comment by Yanyan-Wang** [comment]
> 希望在节点/边数据中配置 visible: false / true 来控制初次渲染是否隐藏元素

v3.6.1 已支持
