### ISSUE TITLE
react中使用G6，提示___default.a.TreeGraph is not a constructor，什么问题啊 用不了辐射树吗

### ISSUE THREAD

**Issue by 1478773579** [antvis/G6#1773]
下边代码，TreeGraph的配置内容是拿的Graph的，但是也应该不会报TreeGraph不是构造器吧，并且打印G6也没有找到TreeGraph

`import React, { Component, useEffect} from 'react'
import { Input, Card, Row, Col, Button, Icon} from 'antd'
import ReactDOM from 'react-dom';
import G6 from '@antv/g6';
import fetch from 'dva/fetch'
const RelationShap = ()=>{
    const ref = React.useRef(null);
    let graph = null
    useEffect(()=>{
        fetch('https://gw.alipayobjects.com/os/antvdemo/assets/data/algorithm-category.json')
        .then(res => res.json())
        .then(data => {
            console.log(G6)
            if (!graph) {
          graph = new G6.TreeGraph({
              container: ReactDOM.findDOMNode(ref.current),
            width: 750,
            height: 750,
            linkCenter:true,
            modes: {
              default: [
                {
                  type: 'collapse-expand',
                  onChange: function onChange(item, collapsed) {
                    const data = item.get('model').data;
                    data.collapsed = collapsed;
                    return true;
                  },
                },
                'drag-canvas',
                'zoom-canvas',
              ],
            },
            defaultNode: {
              size: 26,
              style: {
                fill: '#C6E5FF',
                stroke: '#5B8FF9',
              },
            },
            defaultEdge: {
              style: {
                stroke: '#A3B1BF',
              },
            },
            layout: {
              type: 'dendrogram',
              direction: 'LR',
              nodeSep: 20,
              rankSep: 100,
              radial: true,
            },
          });
      
          graph.node(function(node) {
            return {
              label: node.id,
            };
          });
            graph.data(data);
            graph.render();
            graph.fitView();
          
        } 
              
        });

    },[])
    return(
        <div ref={ref}></div>
    )
}`

**Comment by Yanyan-Wang** [comment]
看下你用的 G6 哪个版本

**Comment by 1478773579** [comment]
> 看下你用的 G6 哪个版本

"version": "3.5.10"

我换了TreeGraph的配置项，然后就能工作了，怎么也不应该报TreeGraph不是构造器的错，以下是修改的配置项：
 useEffect(()=>{
      if(!graph) {
        graph = new G6.TreeGraph({
          container: ref.current,
          width: 500,
          height: 500,
          modes: {
            default: ['drag-canvas']
          },
          defaultEdge: {
            shape: 'cubic-horizontal',
            style: {
              stroke: '#A3B1BF'
            }
          },
          defaultNode: {
            shape: 'rect',
            labelCfg: {
              style: {
                fill: '#000000A6',
                fontSize: 10
              }
            },
            style: {
              stroke: '#72CC4A',
              width: 150
            }
          },
          layout: {
            type: 'dendrogram', 
            direction: 'LR',    
            nodeSep: 50,     
            rankSep: 200      
          }
        })
      }
      graph.data(treeData)
      graph.render()
    }, [])
    return(
        <div ref={ref}></div>
    )

**Comment by Yanyan-Wang** [comment]
我没看出这两个代码片段的配置有什么本质上的不同，前一个片段我复制到官网 demo 中也是可以运行并且没有报错的呀

**Comment by 1478773579** [comment]
> 我没看出这两个代码片段的配置有什么本质上的不同，前一个片段我复制到官网 demo 中也是可以运行并且没有报错的呀

玄学吧
