### ISSUE TITLE
关于G6 的combo使用 polyline  连接线的问题

### ISSUE THREAD

**Issue by weicheng123456** [antvis/G6#1775]
G6 Version:
3.5.9
Platform:
vue、window、chrom
Mini Showcase(like screenshots):
CodePen Link：https://codepen.io/weicheng123456/pen/ExPLbww?editors=1010
G6 的combo使用 polyline  连接线的问题，始终无法在combo的最外部发出连接线，而是一直在combo里面。

**Comment by Yanyan-Wang** [comment]
v3.5.11 已修复
