### ISSUE TITLE
自定义节点setstate生命周期不起作用

### ISSUE THREAD

**Issue by zhaokgithub** [antvis/G6#1776]
版本3.5.3

自定义节点中设置了setstate,然后监听click事件改变state，并没有进入setstate中
代码如下：
import G6 from "@antv/g6";

/**
 * Custom a pie chart node
 * by Shiwu
 *
 */
const lightBlue = "#5b8ff9";
const lightOrange = "#5ad8a6";

// register a pie chart node
G6.registerNode("pie-node", {
  draw: (cfg, group) => {
    const radius = cfg.size / 2; // node radius
    const inPercentage = 1 / 3; // the ratio of indegree to outdegree
    const inAngle = inPercentage * Math.PI * 2; // the anble for the indegree fan
    const inArcEnd = [radius * Math.cos(inAngle), radius * Math.sin(inAngle)]; // the end position for the in-degree fan
    let isInBigArc = 1,
      isOutBigArc = 0;
    if (inAngle > Math.PI) {
      isInBigArc = 0;
      isOutBigArc = 1;
    }
    console.log(inArcEnd);
    // fan shape for the in degree
    const fanIn = group.addShape("path", {
      attrs: {
        path: [
          ["M", inArcEnd[1], -radius / 2],
          ["A", radius, radius, 0, 0, 0, -inArcEnd[1], -radius / 2],
          ["L", 0, 0],
          ["Z"]
        ],
        lineWidth: 0,
        fill: lightOrange
      },
      name: "in-fan-shape"
    });
    group.addShape("path", {
      attrs: {
        path: [
          ["M", 0, radius],
          ["A", radius, radius, 0, 0, 0, inArcEnd[1], -radius / 2],
          ["L", 0, 0],
          ["Z"]
        ],
        lineWidth: 0,
        fill: "red"
      },
      name: "in-fan-shape"
    });
    group.addShape("path", {
      attrs: {
        path: [
          ["M", -inArcEnd[1], -radius / 2],
          ["A", radius, radius, 0, 0, 0, 0, radius],
          ["L", 0, 0],
          ["Z"]
        ],
        lineWidth: 0,
        fill: "blue"
      },
      name: "in-fan-shape"
    });
    // draw the fan shape
    // 返回 keyshape
    return fanIn;
  },
  setState: (name, val, node) => {
    console.log("test");
    console.log(name);
  }
});

const data = {
  nodes: [
    {
      id: "pie1",
      size: 80,
      inDegree: 80,
      degree: 360,
      x: 150,
      y: 150
    },
    {
      id: "pie2",
      size: 80,
      inDegree: 280,
      degree: 360,
      x: 350,
      y: 150
    }
  ],
  edges: [
    {
      source: "pie1",
      target: "pie2"
    }
  ]
};
const width = document.getElementById("container").scrollWidth;
const height = document.getElementById("container").scrollHeight || 500;
const graph = new G6.Graph({
  container: "container",
  width,
  height,
  // translate the graph to align the canvas's center, support by v3.5.1
  fitCenter: true,
  linkCenter: true,
  defaultNode: {
    type: "pie-node"
  }
});
// 点击时选中，再点击时取消
graph.on("node:click", ev => {
  const node = ev.item;
  graph.setItemState(node, "selected", !node.hasState("selected")); // 切换选中
});

graph.data(data);
graph.render();

注：最新好像版本没有发现这个问题

**Comment by baizn** [comment]
这个应该是之前版本的一个BUG，更新到最新版本
