### ISSUE TITLE
拖拽画布事件（drag-canvas）出现异常

### ISSUE THREAD

**Issue by itWorkergg** [antvis/G6#1783]
鼠标左键点击画布进行拖拽的时候，同时点击右键，然后再同时松开左右两键，然后再进行鼠标左键拖拽画布，然后松开左键之后画布依然随着鼠标进行移动，需要双击之后才不会跟随鼠标进行移动，麻烦帮忙看下，大佬们。

**Comment by Yanyan-Wang** [comment]
哪个版本的 G6

**Comment by warplan** [comment]
+1

**Comment by itWorkergg** [comment]
> 哪个版本的 G6

^3.4.8

**Comment by Yanyan-Wang** [comment]
更新到最新试一下，3.5.11

**Comment by itWorkergg** [comment]
> 更新到最新试一下，3.5.11

好的，我试下，谢谢啦

**Comment by zhoustudent** [comment]
想问下大家在3.5.5版本的g6进行拖拽的时候，偶发频率较高的出现拖拽画布时画布出现层叠现象
![image](https://user-images.githubusercontent.com/22286864/88931069-ec5ece00-d2ae-11ea-97bf-dce2e08aa097.png)这个图片是我从官网上试出来的

**Comment by itWorkergg** [comment]
禁用局部渲染方法试下：/** * 暂时先关闭G6的局部渲染，后续等待官方解决
 * 拖拽节点经过其他节点，将会在节点上出现花边线条
 * https://github.com/antvis/G6/issues/1381
 */
public get(param: any) {
  this.innerGraph.get(param).set('localRefresh', false);
}



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "纯纯的loser"<notifications@github.com&gt;; 
发送时间: 2020年7月30日(星期四) 晚上9:52
收件人: "antvis/G6"<G6@noreply.github.com&gt;; 
抄送: "神龙小子"<908843012@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [antvis/G6] 拖拽画布事件（drag-canvas）出现异常 (#1783)





 
想问下大家在3.5.5版本的g6进行拖拽的时候，偶发频率较高的出现拖拽画布时画布出现层叠现象
 这个图片是我从官网上试出来的

**Comment by Yanyan-Wang** [comment]
> 想问下大家在3.5.5版本的g6进行拖拽的时候，偶发频率较高的出现拖拽画布时画布出现层叠现象
> ![image](https://user-images.githubusercontent.com/22286864/88931069-ec5ece00-d2ae-11ea-97bf-dce2e08aa097.png)这个图片是我从官网上试出来的

v3.6 试下，还有问题的话新开 issue，该问题与这个 issue 无关了

**Comment by warplan** [comment]
@Yanyan-Wang 最新的版本3.7.1还是有这个问题
