### ISSUE TITLE
How to take an event from context menu?

### ISSUE THREAD

**Issue by mostopalove** [antvis/G6#1786]
- **G6 Version**: 3.5.3
- **Platform**: MacOS Catalina 10.15.5

Do you have any mechanism to work with context menu as in [this](https://g6.antv.vision/en/examples/tool/contextMenu) example?
How I can add some listeners and take information from node to this context menu?

**Comment by Yanyan-Wang** [comment]
The parameter of the callback of the G6's event contains the manipulated item. And here goes a single way to bind click listener for the menu and get the information of the clicked node

```
// a global variable stores the currentclicked node
let clickedNode;
// add a click listener to the li DOM of the context menu
firstLi.addEventListener('click', e => {
  console.log('clicking first li', clickedNode.getID());
});

raph.on('node:contextmenu', evt => {
  // evt.item is the clicked node
  clickedNode = evt.item;
  // ...
```

**Comment by mostopalove** [comment]
@Yanyan-Wang thanks a lot! It's saved me
