### ISSUE TITLE
双指滑动的示例代码升级版本后少了缩放的功能

### ISSUE THREAD

**Issue by wanghansong** [antvis/G6#1790]
- **G6 Version**: 3.5.1
- **Platform**: mac
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

双指滑动画布的示例代码在3.1.0版本的时候是有『双指滑动画布+双指缩放』的功能，但是升级g6版本后双指缩放功能失效，并且会卡死

官方的demo：https://codesandbox.io/s/v0w1o
可以在上面demo里切换版本对比下双指缩放功能，3.1.0版本有双指缩放，3.5.10没有了

**Comment by wanghansong** [comment]
发现是示例里`const pixelRatio = canvas.get('pixelRatio');`这块得到的值是undefined

**Comment by Yanyan-Wang** [comment]
pixelRatio 旧版本中需要在实例化图时手动配置到图上，新版本不需要用户配置，会自动获取了。这里也不再需要除以 pixelRatio

```
graph.zoomTo(ratio, {
   x: point.x,
  y: point.y,
});
```
