### ISSUE TITLE
getViewCenter bug

### ISSUE THREAD

**Issue by double-headed-eagle** [antvis/G6#1791]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

在代码 src/graph/controller/view.ts的viewController的getViewCenter的代码中,算中心点的代码为
private getViewCenter(): Point {
    const padding = this.getFormatPadding();
    const { graph } = this;
    const width: number = graph.get('width');
    const height: number = graph.get('height');
    return {
      x: (width - padding[2] - padding[3]) / 2 + padding[3],
      y: (height - padding[0] - padding[2]) / 2 + padding[0],
    };
  }
其中的x: (width - padding[2] - padding[3]) / 2 + padding[3]**应该为**x: (width - padding[1] - padding[3]) / 2 + padding[3]

**Comment by Yanyan-Wang** [comment]
非常感谢，下个小版本修复

**Comment by Yanyan-Wang** [comment]
v3.5.11 已修复
