### ISSUE TITLE
ie 11 not working in asp.net webform

### ISSUE THREAD

**Issue by Tony518** [antvis/G6#1792]
- **G6 Version**:3.5.10
- **Platform**: Asp.net webform
- **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/15099434/87399055-61f94780-c5e9-11ea-8a0d-cc1a144ed540.png)

- **CodePen Link**:

I use G6 in my asp.net webform application to show the bpm process!
it works well in Chrome, but not working in IE.
I tried to download the source code and rebuild the code and copy the dist code to my application, it's not working too,  then i see the "**Object.assign**" is still in g6.min.js.  
I see the official solution to compatible with IE is for vue,react,umi... but not for asp.net webforms.
I appreciate your help. thanks.

**Comment by richardchen85** [comment]
G6 can not support IE @Tony518

**Comment by Tony518** [comment]
> es6 is not working on IE，use polyfill please @Tony518

Thanks richard,
Do you mean I download the source code of G6, and add polyfill then rebuild?

**Comment by richardchen85** [comment]
@Tony518 You can import `babel-polyfill` before import G6
