### ISSUE TITLE
compactBox 在升级过程中报错 t.source.getID is not a function 

### ISSUE THREAD

**Issue by wanghansong** [antvis/G6#1797]
- **G6 Version**: 3.5.10
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

今天将g6从3.1.0升级到3.5.10过程中，画的一颗紧凑树报错`t.source.getID is not a function`
* 原因：升级后的版本要求树每个节点id必须是字符串，数字类型的会出这个问题，3.1.0旧版的id可以是数字，所以在升级过程中导致报错。

把id处理成字符串后就没有这个报错了，翻了下issues里没有人提这个问题，今天踩坑记录下，方便后来者

**Comment by yuanguandong** [comment]
我也遇到了，谢谢

**Comment by Jabinzou** [comment]
这个问题在3.8.0还没有修复啊
