### ISSUE TITLE
ModelRect label and description aren't cut when too long

### ISSUE THREAD

**Issue by Angelus1383** [antvis/G6#1798]
- **G6 Version**:3.5.10
- **Platform**: reactjs
- **Mini Showcase(like screenshots)**: 
<img width="1124" alt="Schermata 2020-07-15 alle 15 55 38" src="https://user-images.githubusercontent.com/5064028/87554362-56268780-c6b4-11ea-8f17-63ac22d59adc.png">

- **CodePen Link**: https://codesandbox.io/s/competent-wave-bcupy?fontsize=14&hidenavigation=1&theme=dark

Using the modelRect built-in node, when the label and/or description lengths exceed the size of the rect they are not cut like shown in documentation.

**Comment by Yanyan-Wang** [comment]
Since most users want to break or deal with the long label by themself, we cancel the automatic cutting. Try these ways to solve the problem, which will be more free.

https://g6.antv.vision/zh/examples/item/label
https://g6.antv.vision/zh/examples/item/label#labelLen1
