### ISSUE TITLE
可以开源内部注册的边的实现源码吗？

### ISSUE THREAD

**Issue by sunny920406** [antvis/g6#180]
版本G6 1.2.3
目前使用了到了 内部注册的边VHV，但是发现这个计算出的布局还是有些问题，我想试下如下的连线
![image](https://user-images.githubusercontent.com/8424604/36844268-f686952c-1d8c-11e8-89f0-695f9a22f1e2.png)，所以想参考下VHV是怎么画的

**Comment by TomHuangCN** [comment]
明天开源 2.0
