### ISSUE TITLE
自定义Combo官方示例加上minimap无法更新

### ISSUE THREAD

**Issue by wanghansong** [antvis/G6#1800]
- **G6 Version**: 3.5.10
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**: https://codesandbox.io/s/damp-sunset-cekm8?file=/index.js

在下面的官方示例加了个最简单的minimap，然后在展开折叠combo时，minimap无法跟随更新
https://g6.antv.vision/zh/examples/item/customCombo#cRect

https://codesandbox.io/s/damp-sunset-cekm8?file=/index.js

**Comment by wanghansong** [comment]
![combo](https://user-images.githubusercontent.com/19324560/87644817-37d98e00-c77f-11ea-9d4a-d5f4536a181a.png)

**Comment by Yanyan-Wang** [comment]
combo 收缩展开没有设计触发 minimap 更新

**Comment by wanghansong** [comment]
> combo 收缩展开没有设计触发 minimap 更新

那有什么办法手动出发minimap更新吗

**Comment by Yanyan-Wang** [comment]
调用收缩/展开后，手动触发一下 afterrender 时机试试

```
graph.emit('afterrender')
```

**Comment by wanghansong** [comment]
> 调用收缩/展开后，手动触发一下 afterrender 时机试试
> 
> ```
> graph.emit('afterrender')
> ```

第一次emit的时候还是不更新，第二次展开折叠后可以正常更新

**Comment by wanghansong** [comment]
有没有什么强制刷新minimap的，让minimap跟最后canvas渲染的结果一样

**Comment by Yanyan-Wang** [comment]
这个就是在强制刷新了。如果有动画，要在动画结束后触发
```
graph.on('afteranimate', e => {
graph.emit('afterrender');
});
```

或者 settimeout

**Comment by wanghansong** [comment]
> settimeout

对于在折叠前有些自定义的操作而言，监听'afteranimate'不一定好用，可以用settimeout
