### ISSUE TITLE
上下文菜单模块，如果modes设置为drag-canvas时，移动画布后，右击菜单位置没有跟随移动，出现错乱。

### ISSUE THREAD

**Issue by 1195002442** [antvis/G6#1801]
- **G6 3.4.3**:
上下文菜单模块，如果modes设置为drag-canvas时，移动画布后，右击菜单位置没有跟随移动，出现错乱。
  modes: {
    default: ['drag-node','drag-canvas'],
  },
![QQ截图20200716160722](https://img-blog.csdnimg.cn/20200716160826513.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzM3MjMzMDIz,size_16,color_FFFFFF,t_70)

canvas:dragend，canvas:dragenter  拖动画布时候，这两个方法会各自被触发两次。

**Comment by Yanyan-Wang** [comment]
请提供复现在线 demo

**Comment by Yanyan-Wang** [comment]
官方 demo 可如下修改

```
graph.on('node:contextmenu', evt => {
  evt.preventDefault();
  evt.stopPropagation();
  
  conextMenuContainer.style.left = `${evt.canvasX + 20}px`; // 把这里的 evt.x 改为 evt.canvasX
  conextMenuContainer.style.top = `${evt.canvasY}px`;  // 把这里的 evt.y 改为 evt.canvasY
});
```
