### ISSUE TITLE
如何自定义combo折叠后的位置

### ISSUE THREAD

**Issue by wanghansong** [antvis/G6#1802]
- **G6 Version**: 3.5.10
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

单个combo中有几百个节点情况下，折叠combo后就超出视窗了，得到图里到处找，因此想自定义combo折叠后的位置

**Comment by wanghansong** [comment]
提供上面问题的一个在线demo
https://codesandbox.io/s/g6-combo-e3ry4?file=/src/components/HelloWorld.vue

**Comment by Yanyan-Wang** [comment]
我看到在这个 demo 中收缩左侧 combo 后还在视窗中呀

**Comment by wanghansong** [comment]
> 我看到在这个 demo 中收缩左侧 combo 后还在视窗中呀

我在demo里手动兼容了下，在调用`collapseExpandCombo`前把所有节点位置移动到了第一个节点位置，所以combo折叠后才会在第一个节点位置。如果没有做这个兼容就是上面我说的出现combo折叠位置很难找

**Comment by Yanyan-Wang** [comment]
因为 combo 折叠默认是放在内部所有节点位置的中心位置的。你这样处理挺好的。以后我们可能考虑加入一个 feature 指定向某个方向或向中心收缩。

**Comment by LincolnPack** [comment]
如何自定义combo 初始位置，类似node ,x ,y

**Comment by wanghansong** [comment]
> 如何自定义combo 初始位置，类似node ,x ,y

可以通过定义combo里面初始节点的位置，combo位置计算是基于里面节点

**Comment by Yanyan-Wang** [comment]
空 combo 是可以指定 x y 来确定位置的。非空 combo 的位置是由内部元素决定的
