### ISSUE TITLE
如何在树状图中使用combo

### ISSUE THREAD

**Issue by 425765923** [antvis/G6#1804]

**Comment by Yanyan-Wang** [comment]
树图不支持 combo

**Comment by 425765923** [comment]
> 树图不支持 combo，考虑用一般图 + Dagre 布局看是否能替代：https://g6.antv.vision/zh/examples/net/dagreFlow#dagreCombo

目前就是使用一般图 + Dagre，但是又遇到了combo中出现不属于该分组的节点，只是因为combo的大小刚好覆盖到了他，而如果使用sortByCombo，又不美观了，请问这种情况要怎么解决呢
![image](https://user-images.githubusercontent.com/27410042/87892789-9dc06100-ca70-11ea-89e0-6bbf1436c36f.png)

**Comment by Yanyan-Wang** [comment]
combo 的大小和位置取决于内部元素的位置。可以在布局后自行调整节点位置使同 combo 节点靠近。
