### ISSUE TITLE
关于 TreeGraph，树形结构脑图是否支持一键展开叶子节点、一键收缩之类

### ISSUE THREAD

**Issue by ben-Run** [antvis/G6#1806]
看了下api 没有看到有控制展开跟收缩的接口

**Comment by Yanyan-Wang** [comment]
使用 collapse-expand behavior。

[demo](https://g6.antv.vision/zh/examples/tree/compactBox#basicCompactBox)

[dos](https://g6.antv.vision/zh/docs/manual/middle/states/defaultBehavior#collapse-expand)
