### ISSUE TITLE
How does it possible to change size of graph canvas with data dynamically?

### ISSUE THREAD

**Issue by mostopalove** [antvis/G6#1808]
- **G6 Version**: 3.5.3
- **Platform**: MacOS 10.15.5

Is it possible to resize a graph instance with rendered data?

This code does not work:
`const container = document.getElementById(this.idDomElement);`
`this.graph.get('canvas').set('width', container.offsetWidth);`
`this.graph.get('canvas').set('height', container.offsetHeight);`

**Comment by Yanyan-Wang** [comment]
```
graph.changeSize(width, height)
```
