### ISSUE TITLE
combo折叠后箭头错乱的问题

### ISSUE THREAD

**Issue by wanghansong** [antvis/G6#1809]
- **G6 Version**: 3.5.10
- **Platform**: mac
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

combo在折叠的时候有的监听会折回，显示的不太正常，这个有啥补救方法吗
https://codesandbox.io/s/g6-combo-e3ry4?file=/src/components/HelloWorld.vue

**Comment by wanghansong** [comment]
![image](https://user-images.githubusercontent.com/19324560/87892625-2a1e5400-ca70-11ea-8d67-cd2e57dcc735.png)

**Comment by JyotsnaC** [comment]
edge type: quadratic  does not have the problem. Hope that solves your problem

**Comment by wanghansong** [comment]
> edge type: quadratic does not have the problem. Hope that solves your problem

thank you very much. it works. however, quadratic type doesn't satisfy my ui design... 
the ui looks a little ugly using quadratic edge

**Comment by Yanyan-Wang** [comment]
v3.5.11 已修复

**Comment by wanghansong** [comment]
> v3.5.11 已修复

哥，你这个修复的时候把`collapseExpandCombo`方法关掉了吗，我上面的demo怎么点击加减号收缩不起来了

**Comment by wanghansong** [comment]
> v3.5.11 已修复

还有建议测下tooltip是否正常，我昨天升级到3.5.11的时候看到tooltip显示的位置好像不太正常

**Comment by wanghansong** [comment]
@Yanyan-Wang 请问下这个issue的问题发版解决了吗
