### ISSUE TITLE
G6 graph 视图更新， minimap 未随之更新

### ISSUE THREAD

**Issue by Baron-zhu** [antvis/G6#1811]
- **G6 Version**: 3.5.9
- **Platform**: React
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
请提供复现在线 demo

**Comment by 1193538012** [comment]
https://codesandbox.io/s/ancient-wood-np3l2?file=/index.js   
我这也是，力导向图中，这个minimap没有变化。

**Comment by Yanyan-Wang** [comment]
> https://codesandbox.io/s/ancient-wood-np3l2?file=/index.js
> 我这也是，力导向图中，这个minimap没有变化。

会在布局完成后刷新 minimap 的，minimap 频繁刷新会有性能问题

**Comment by Yanyan-Wang** [comment]
为了提升性能，minimap 是做了一些 debounce 和不必要时不刷新的操作。例如 force 布局时，会在布局完成后再刷新 minimap。若还有其他地方希望手动触发 minimap 刷新，可以调用

```
graph.emit('afterrender')
```

由于题主长期未更新，暂时关闭，若还有问题可随时新建 issue。
