### ISSUE TITLE
G6的新插件ToolBar，有详细的API吗？现在使用官方例子上的撤销不管用。

### ISSUE THREAD

**Issue by 1193538012** [antvis/G6#1812]
- **G6 Version**:3.5.10
- **Platform**: windows
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:
链接 https://codesandbox.io/s/dark-hill-r16yv?file=/index.html
例子上的toolbar.undo();（撤销操作）没起作用。
重做、放大、缩小、适应屏幕、实际大小这些功能没有相应的API。

**Comment by Yanyan-Wang** [comment]
还没有正式开放

**Comment by 1193538012** [comment]
> 还没有正式开放

好的，这个功能看起来非常不错😁，最近几个版本就能出吗？

**Comment by baizn** [comment]
> > 还没有正式开放
> 
> 好的，这个功能看起来非常不错😁，最近几个版本就能出吗？

3.6 版本中可以用，https://g6.antv.vision/zh/examples/tool/toolbar

**Comment by liuz666** [comment]
3.8.5版本的案例中只有撤销、新增的演示。放大、缩小的、等比例这些都没有，code是什么也不清楚。
https://g6.antv.vision/zh/examples/tool/toolbar#self-toolbar

**Comment by MartinGsus99** [comment]
请问toolbar有接口吗？想统一一下UI
