### ISSUE TITLE
G6实现边动画

### ISSUE THREAD

**Issue by Protagonistss** [antvis/G6#1814]
- **G6 Version**: 3.5.10
- **Platform**: macos
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:
g6的边动画中的圆点运动能否是startPoint to endPoint的运动，而不是像示例中那样 point to point，这块的思路，我去翻了语雀和文档，没找到相关的思路，求赐教！！！

**Comment by Protagonistss** [comment]
``

**Comment by Protagonistss** [comment]
G6 Version: 3.5.10
Platform: macos
Mini Showcase(like screenshots):
CodePen Link:
g6的边动画中的圆点运动能否是startPoint to endPoint的运动，而不是像示例中那样 point to point，这块的思路，我去翻了语雀和文档，没找到相关的思路，求赐教！！！

**Comment by Yanyan-Wang** [comment]
示例就是从 startPoint  to endPoint 啊。见 L14，L27：https://g6.antv.vision/zh/examples/scatter/edge

另外，语雀文档不再维护，文档全部看官网。

**Comment by Protagonistss** [comment]
> G6 Version: 3.5.10
> Platform: macos
> Mini Showcase(like screenshots):
> CodePen Link:
> g6的边动画中的圆点运动能否是startPoint to endPoint的运动，而不是像示例中那样 point to point，这块的思路，我去翻了语雀和文档，没找到相关的思路，求赐教！！！

**Comment by Protagonistss** [comment]
<img width="449" alt="Screen Shot 2020-07-22 at 11 04 16 AM" src="https://user-images.githubusercontent.com/39770514/88129624-1eb36000-cc0b-11ea-962c-41f13c02605d.png">

类似这种行为！！！ @Yanyan-Wang
