### ISSUE TITLE
官网新插件 Menu 根据官网的例子跟着做报错

### ISSUE THREAD

**Issue by 929496959** [antvis/G6#1815]
G6 Version:3.5.10
Platform: windows
浏览器:Google 84 版本
错误信息:
core.js:6228 ERROR TypeError: Cannot read property 'getModel' of null
    at e.onMenuShow (g6.min.js:23)
    at e.n (g6.min.js:15)
    at a (g6.min.js:15)
    at e.t.emit (g6.min.js:15)
    at t.onCanvasEvents (g6.min.js:23)
    at e.n (g6.min.js:15)
    at a (g6.min.js:15)
    at e.t.emit (g6.min.js:15)
    at an (g6.min.js:15)
    at t._emitEvent (g6.min.js:15)
我的配置:
const menu = new Menu({
      getContent(graph?: IGraph) {
        return `<ul>
          <li title='1'>测试02</li>
          <li title='2'>测试02</li>
          <li>测试02</li>
          <li>测试02</li>
          <li>测试02</li>
        </ul>`;
      },
      handleMenuClick(target: HTMLElement, item: Item) {
        console.log(target, item);
      },
    });
    this.graph = new Graph({
      container: 'canvasPanel',
      // renderer: 'svg',
      width,
      height,
      modes: {
        // 支持的 behavior
        default: ['drag-canvas', 'zoom-canvas', 'drag-node'],
        edit: ['click-select'],
      },
      plugins: [menu],
    });

**Comment by Yanyan-Wang** [comment]
请给出复现在线 demo
