### ISSUE TITLE
combo 内部节点拖出后，combo 更新，链接的边未更新

### ISSUE THREAD

**Issue by huxiaoyun** [antvis/G6#1817]
- **G6 Version**:  3.5.10
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

https://riddle.alibaba-inc.com/riddles/cfe79601

**Comment by Yanyan-Wang** [comment]
暂时可以通过 edge.refresh() 手动刷新。下个版本修复。

**Comment by huxiaoyun** [comment]
https://riddle.alibaba-inc.com/riddles/cfe79601
使用 edge.refresh 不生效，反而更新出错了。

![image](https://user-images.githubusercontent.com/4345248/88247849-d448e680-ccd1-11ea-9313-b06a8d14b909.png)


![image](https://user-images.githubusercontent.com/4345248/88247855-da3ec780-ccd1-11ea-95db-85508a43f4d2.png)
