### ISSUE TITLE
combo 之间增加边失败

### ISSUE THREAD

**Issue by huxiaoyun** [antvis/G6#1818]
- **G6 Version**: 3.5.10
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:
https://riddle.alibaba-inc.com/riddles/1c37dd63

combo 与节点之间可添加边成功，
节点节点之间可添加边成功。

behaviors 中第一次 combo: click 事件会触发成功，选择target 时，combo:click 无法触发。

**Comment by Yanyan-Wang** [comment]
因为新增的边的层级比 combo 高，所以你在第二次点击 combo 的时候，实际上是触发了 edge:click 而没有触发到它下层的 combo。在实例化图时配置 groupByTypes: false 可解。

**Comment by huxiaoyun** [comment]
v3.5.11 使用  groupByTypes: false  有问题，点击 combo 能触发 onClick 事件，但是会触发两次
详细可见：https://riddle.alibaba-inc.com/riddles/1c37dd63
