### ISSUE TITLE
配置以SVG渲染树后，自定义dom节点drag-node不起作用

### ISSUE THREAD

**Issue by MirrorHuang** [antvis/G6#1822]
BUG

- **G6 Version**:3.5.2
- **Platform**:Chrome  83.0.4103.116
- **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/15670982/88129529-e744b380-cc0a-11ea-9b66-05af21fbf33d.png)
![image](https://user-images.githubusercontent.com/15670982/88129888-c6309280-cc0b-11ea-82c7-4954d3f1594e.png)

- **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
![image](https://user-images.githubusercontent.com/29593318/88133276-3d6a2480-cc14-11ea-9321-f2b4c3817e60.png)


https://g6.antv.vision/zh/docs/api/nodeEdge/shapeProperties#dom-svg

[demo](https://g6.antv.vision/zh/examples/item/customNode#svgDom)


建议用 canvas。svg 能做的 canvas 基本都能做。
