### ISSUE TITLE
[bug]使用子图布局，即new G6.Layout('force')，再执行layout，worker没有走new的流程，导致workerenabled无作用

### ISSUE THREAD

**Issue by TLYTLX** [antvis/G6#1823]
- **G6 Version**:  3.5.10
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
子图布局暂时不支持 webworker

**Comment by TLYTLX** [comment]
> 子图布局暂时不支持 webworker

有计划几时支持嘛，另外想问下updatelayout('force')这种，虽然支持webworker 但是每次tick都会refreshpositions，这么设计的原因是什么呢,这样界面上还是会出现中间位置的过程，为什么不考虑算法完全算好位置再出来呢 后续是否会加个这样的配置呢

**Comment by Yanyan-Wang** [comment]
> > 子图布局暂时不支持 webworker
> 
> 有计划几时支持嘛，另外想问下updatelayout('force')这种，虽然支持webworker 但是每次tick都会refreshpositions，这么设计的原因是什么呢,这样界面上还是会出现中间位置的过程，为什么不考虑算法完全算好位置再出来呢 后续是否会加个这样的配置呢

子图布局的 webworker 暂时没有计划支持，看看社区有没有朋友愿意贡献一下

新版本中，很多力导家族的布局都可以支持计算完成后再渲染，通过配置布局的 animate: false 即可。例如 force2:
http://g6.antv.antgroup.com/examples/net/forceDirected/#basicForce2
(这个 demo 里面 animate: true)
