### ISSUE TITLE
[BUG] graph 中新增的边随机消失，重新设置布局后恢复

### ISSUE THREAD

**Issue by Dustone-JavaWeb** [antvis/G6#1824]
- **G6 Version**:3.4.5
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

在新增edge时调用graph.addItem()后，调用graph.getEdges() 对节点进行遍历（实现关联边高亮显示），有几率导致刚刚新增完成且已经显示的edge消失，其他的edge不受影响，在调用graph.updateLayout() 重新布局后消失的edge恢复显示

![image](https://user-images.githubusercontent.com/35624201/88245322-65678f80-ccc9-11ea-8a3c-8d25b09c72e8.png)
![image](https://user-images.githubusercontent.com/35624201/88245327-67c9e980-ccc9-11ea-93df-4a0124eabb61.png)
边消失（控制台没有任何报错信息）
![image](https://user-images.githubusercontent.com/35624201/88245334-6c8e9d80-ccc9-11ea-9fa1-56de76abc71c.png)
重设布局后
![image](https://user-images.githubusercontent.com/35624201/88245342-744e4200-ccc9-11ea-9b83-73de986b1a1b.png)

**Comment by Yanyan-Wang** [comment]
先升级到最新版本 3.5.11，还有问题就提供一下复现在线 demo

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
