### ISSUE TITLE
树图节点中设置collapsed，导致展开收起动画不正常

### ISSUE THREAD

**Issue by demonskp** [antvis/G6#1827]
- **G6 Version**:
3.5.9 3.5.10 3.5.11
- **Platform**:
windows Chrome
- **Mini Showcase(like screenshots)**:
请直接看图
![g6-bug](https://user-images.githubusercontent.com/25999019/88266503-e80c4100-cd01-11ea-994a-ceabf0198ac1.gif)

- **CodePen Link**:
https://codesandbox.io/s/sleepy-browser-4xoc2

在初始数据上配置了**"collapsed": true**

加载后正常 所有节点都如愿收起来了

但是在点击展开它的时候  播放的是收起的动画  再次点击 没有动画  之后点击 播放的动画和结果都是正确的了

在3.5.11 这个版本  点击会一直是收起的动画

我提供了CodePan案例 可以复现

**Comment by Yanyan-Wang** [comment]
3.5.9、3.5.10 出现这个的原因是你的节点没有唯一的 string  id。你把 id 赋值为 name，但数据里没有 name，导致所有节点的 id 都是 undefined。

3.5.11 本身有些问题。3.5.12 已经修复

**Comment by demonskp** [comment]
谢谢了，自己没注意
