### ISSUE TITLE
[bug] 缩放画布后拖动节点位置偏移

### ISSUE THREAD

**Issue by kooriookami** [antvis/G6#1829]
- **G6 Version**:
3.5.11
- **Platform**:
win10 64 chrome84
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:
https://codesandbox.io/s/optimistic-ptolemy-gbo03

放大或缩小画布后，拖动节点，定位会偏移，在3.5.10版本中是好着的

**Comment by Yanyan-Wang** [comment]
3.5.12 已修复
