### ISSUE TITLE
Edges between the nodes are not consistent

### ISSUE THREAD

**Issue by kravinash13** [antvis/G6#1831]
G6 Version: 3.5.10
Platform: MacOS
Mini Showcase(like screenshots):
CodeSandbox Link: [Scenario1](https://codesandbox.io/s/edges-wtrxj?file=/index.js:4332-4336) , [Scenario 2,](https://codesandbox.io/s/dagre-edges-n0j78?file=/index.js) [Scenario 3](https://codesandbox.io/s/dawn-star-6hck9?file=/index.js)

When the nodes are of type "rect", the edges start and end towards the side of the nodes, whereas not in custom nodes.

**Comment by Yanyan-Wang** [comment]
Use `anchorPoints` to control the start and end port of the edges.

 [doc](https://g6.antv.vision/en/docs/manual/middle/elements/anchorpoint)

You can configure `anchorPoints`, `sourceAnchor`, `targetAnchor` while instantiating a graph like this [demo](https://codesandbox.io/s/pensive-voice-5wcl3?file=/index.js), or in each node data and edge data.
