### ISSUE TITLE
npm run site:build Error: Reducers may not dispatch actions

### ISSUE THREAD

**Issue by qq403925754** [antvis/G6#1832]
ERROR #11321  PLUGIN

"@antv/gatsby-theme-antv" threw an error while running the createPages lifecycle:

Reducers may not dispatch actions.

  Error: Reducers may not dispatch actions.
  
  - redux.js:214 dispatch
    [g6]/[_redux@4.0.5@redux]/lib/redux.js:214:13
  
  - index.js:64 action
    [g6]/[_gatsby@2.20.24@gatsby]/dist/redux/index.js:64:88
  
  - index.js:14 Object.dispatch
    [g6]/[_redux-thunk@2.3.0@redux-thunk]/lib/index.js:14:16
  
  - index.js:45 dispatch
    [g6]/[_gatsby-cli@2.12.65@gatsby-cli]/lib/reporter/redux/index.js:45:9
  
  - redux.js:483 Object.createLog
    [g6]/[_redux@4.0.5@redux]/lib/redux.js:483:12
  
  - reporter.js:168 Reporter.warn.text [as warn]
    [g6]/[_gatsby-cli@2.12.65@gatsby-cli]/lib/reporter/reporter.js:168:41
  
  - patch-console.js:22 Console.console.warn.args [as warn]
    [g6]/[_gatsby-cli@2.12.65@gatsby-cli]/lib/reporter/patch-console.js:22:14
  
  - utils.js:449 Object.warn
    [g6]/[_xstate@4.11.0@xstate]/lib/utils.js:449:26
  
  - StateNode.js:1313 
    [g6]/[_xstate@4.11.0@xstate]/lib/StateNode.js:1313:29
  
  - Array.map
  
  - StateNode.js:1311 StateNode.formatTransitions
    [g6]/[_xstate@4.11.0@xstate]/lib/StateNode.js:1311:18
  
  - StateNode.js:321 StateNode.get [as transitions]
    [g6]/[_xstate@4.11.0@xstate]/lib/StateNode.js:321:51
  
  - StateNode.js:296 StateNode.get [as on]
    [g6]/[_xstate@4.11.0@xstate]/lib/StateNode.js:296:36
  
  - StateNode.js:230 
    [g6]/[_xstate@4.11.0@xstate]/lib/StateNode.js:230:93
  
  - Array.forEach
  
  - StateNode.js:230 StateNode._init
    [g6]/[_xstate@4.11.0@xstate]/lib/StateNode.js:230:45
  

failed createPages - 12.143s

**Comment by Yanyan-Wang** [comment]
Are you trying to start the G6 website locally? If so, try:
`rm -rf node_modules`
`yarn install`
`npm start`

**Comment by qq403925754** [comment]
It seems to be an error of gatsby。I can't resolve it。

**Comment by Yanyan-Wang** [comment]
Why do you want to start the website?

**Comment by qq403925754** [comment]
Because I want to read the document outline.

**Comment by Yanyan-Wang** [comment]
> Are you trying to start the G6 website locally? If so, run:
> `rm -rf node_modules`
> `yarn install`
> `npm start`

Did you try the commands above?

**Comment by qq403925754** [comment]
It's not help.But I upgrade gatsby@lastest.It's work!

**Comment by Yanyan-Wang** [comment]
That's great! I'm gonna close this issue.
