### ISSUE TITLE
拖拽image节点位置更新不符合

### ISSUE THREAD

**Issue by hunkid** [antvis/G6#1833]
- **G6 Version**:3.5.11
- **Platform**:chrome&Edge
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

在graph缩的尺度比较大的时候，拖拽节点，节点更新位置与鼠标位置不一致，应该是比例没有算进去，导致鼠标移动比较小的距离，节点却移动比较大（此处我用的node type为image，size设置为100）

**Comment by Yanyan-Wang** [comment]
更新到 3.5.12 已经解决
