### ISSUE TITLE
使用分组collapse-expand-group收起后，子节点仍然显示

### ISSUE THREAD

**Issue by zhouzhiyang-git** [antvis/G6#1834]
使用的是https://g6.antv.vision/zh/examples/interaction/nodeGroup#rect此处提供的demo，请帮忙定位下
![image](https://user-images.githubusercontent.com/68043832/88369597-f5d5cb00-cdc2-11ea-8e46-841a95492c6d.png)

**Comment by Yanyan-Wang** [comment]
Group 即将被废除，请使用 combo
