### ISSUE TITLE
连线的控制点

### ISSUE THREAD

**Issue by 426-330** [antvis/G6#1836]
![image](https://user-images.githubusercontent.com/2107423/88374380-40a81080-cdcc-11ea-9a67-2285f430a49f.png)
请问如何实现这种效果，在线上添加控制点，拖拽点改变线的轨迹，谢谢。

**Comment by Yanyan-Wang** [comment]
重编辑场景推荐使用 X6

一定要用 G6 做的话，尝试改变边的 controlPoints ，然后更新边的 path 图形
