### ISSUE TITLE
[bug] storybook demo，npm run demo；开启了workerenabled的fruchterman，控制台报错,原因是webpack配置问题

### ISSUE THREAD

**Issue by TLYTLX** [antvis/G6#1839]
- **G6 Version**: 3.5.10
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by TLYTLX** [comment]
解决方案：
在storybook的webpack.config.js的awesome-typescript-loader前面加上配置：
config.module.rules.push({
    test: /\.worker\.ts$/,
    exclude: /(node_modules)/,
    use: [
      {
        loader: 'worker-loader',
        options: {
          inline: true
        },
      },
      {
        loader: 'awesome-typescript-loader'
      },
    ],
  });

如果有更好的方案，期望能在下个版本的源码中看到

**Comment by Yanyan-Wang** [comment]
使用 webworker 必须要使用打包后的 G6。npm run build，然后在使用 webworker 的 demo 中引入打包后的 G6
