### ISSUE TITLE
drag-node 拖拽的范围如何限制在初始化的容器内

### ISSUE THREAD

**Issue by zhangtaoBqteam** [antvis/G6#1840]
- **G6 Version**: 3.5.12
- **Platform**:  mac OS
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

在设置modes为drag-node后，拖拽节点会超出初始化的容器，看了官网的几个例子也是会这样，有没有参数可以限制节点拖拽的范围在初始化容器内部呢？

**Comment by Yanyan-Wang** [comment]
可以仿照 [drag-node](https://github.com/antvis/G6/blob/master/src/behavior/drag-node.ts) 自定义交互，在拖拽过程中判断是否超出了容器。[自定义交互 demo](https://g6.antv.vision/zh/examples/interaction/customBehavior)。[自定义交互教程](https://g6.antv.vision/zh/docs/manual/advanced/custom-behavior)。

**Comment by ahouvideo** [comment]
> * **G6 Version**: 3.5.12
> * **Platform**:  mac OS
> * **Mini Showcase(like screenshots)**:
> * **CodePen Link**:
> 
> 在设置modes为drag-node后，拖拽节点会超出初始化的容器，看了官网的几个例子也是会这样，有没有参数可以限制节点拖拽的范围在初始化容器内部呢？

你好，请问你有解决这个限制节点拖拽的范围了吗？？

**Comment by zhangtaoBqteam** [comment]
自定义一下drag-node的交互事件，在里面根据canvas和client的坐标判断一下是否超出当前的可视范围就好啦

**Comment by ahouvideo** [comment]
> 自定义一下drag-node的交互事件，在里面根据canvas和client的坐标判断一下是否超出当前的可视范围就好啦

目前需要  限制节点拖拽在当前combo的移动范围，是否可以看一下你设置的demo呢

**Comment by zhangtaoBqteam** [comment]
不好意思哈，公司内部代码不太方便分享，思路就是之前说的那样子，不是很复杂的


------------------------------------------------------------------
发件人：ahouvideo <notifications@github.com>
发送时间：2020年12月23日(星期三) 15:28
收件人：antvis/G6 <G6@noreply.github.com>
抄　送：张涛 <zhangtao@bqteam.com>; Author <author@noreply.github.com>
主　题：Re: [antvis/G6] drag-node 拖拽的范围如何限制在初始化的容器内 (#1840)


G6 Version: 3.5.12
Platform: mac OS
Mini Showcase(like screenshots):
CodePen Link: 
在设置modes为drag-node后，拖拽节点会超出初始化的容器，看了官网的几个例子也是会这样，有没有参数可以限制节点拖拽的范围在初始化容器内部呢？
你好，请问你有解决这个限制节点拖拽的范围了吗？？

**Comment by ahouvideo** [comment]
好的好的。谢谢谢谢

**Comment by ahouvideo** [comment]
> 不好意思哈，公司内部代码不太方便分享，思路就是之前说的那样子，不是很复杂的
> […](#)
> ------------------------------------------------------------------ 发件人：ahouvideo <notifications@github.com> 发送时间：2020年12月23日(星期三) 15:28 收件人：antvis/G6 <G6@noreply.github.com> 抄　送：张涛 <zhangtao@bqteam.com>; Author <author@noreply.github.com> 主　题：Re: [antvis/G6] drag-node 拖拽的范围如何限制在初始化的容器内 (#1840) G6 Version: 3.5.12 Platform: mac OS Mini Showcase(like screenshots): CodePen Link: 在设置modes为drag-node后，拖拽节点会超出初始化的容器，看了官网的几个例子也是会这样，有没有参数可以限制节点拖拽的范围在初始化容器内部呢？ 你好，请问你有解决这个限制节点拖拽的范围了吗？？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

好的好的，谢谢谢谢
