### ISSUE TITLE
实现节点的拖拽缩放，调用updateItem方法，节点的视图没有更新。

### ISSUE THREAD

**Issue by wrh4585** [antvis/G6#1843]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

需要实现节点的拖拽缩放功能，drag事件和dragend事件中调用updateItem方法，节点的视图没有更新。从控制台打印节点数据，发现节点已经为变化后的值，调用refreshItem方法，refresh方法。paint方法等，都不能刷新视图。
另外，X6目前在哪里可以查看官方文档？

**Comment by Yanyan-Wang** [comment]
为什么不使用内置的 drag-node behavior？https://g6.antv.vision/zh/docs/manual/middle/states/defaultBehavior/#drag-node
要自己写也没问题，在这个[链接](https://g6.antv.vision/zh/examples/net/dagreFlow)下方增加如下代码就能看到效果：
```
graph.on('node:drag', e => {
  graph.updateItem(e.item, {
    x: e.x,
    y: e.y
  })
});
```

[X6 官网](https://x6.antv.vision/zh)

**Comment by wrh4585** [comment]
我可能没表述清楚，是通过拖拽节点的右下角，实现节点的大小改变，并不是说要把节点拖着跑，自定义的节点，在节点中增加了一个图标用以做拖拽的标识。。有内置的直接用多好的，也不需要费心的自己实现了啊。

**Comment by Yanyan-Wang** [comment]
那你提供一个复现在线  demo 看下
