### ISSUE TITLE
G6是否支持在tooltip上进行复制粘贴操作？ 很多时候鼠标还没有移动到tooltip就已经消失了

### ISSUE THREAD

**Issue by caojin24** [antvis/G6#1844]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
内置 tooltip 的显示和隐藏的触发事件是 mouseenter 和 mouseleave。可以自己写一个 DOM 实现类似 tooltip 的效果，触发隐藏可能是点击空白处。自己定义的 DOM 放置在节点周围的挂载方式参考 https://www.yuque.com/antv/g6-blog/gp2dxk#HjQrZ
