### ISSUE TITLE
大数量的树图是否可以一个完整的demo，能看到效果

### ISSUE THREAD

**Issue by yangjialing** [antvis/G6#1845]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by baizn** [comment]
多少数据量呢，能否提供一份测试的数据？

**Comment by LLLuojp** [comment]
> 多少数据量呢，能否提供一份测试的数据？
几千个节点时，拖拽画布 和 minimap 都会非常卡顿，很不友好。
