### ISSUE TITLE
点击收起combo，使用changeData方法更换数据源，之后无法展开combo，展开后又会收回，请帮忙定位一下

### ISSUE THREAD

**Issue by zhouzhiyang-git** [antvis/G6#1847]
![image](https://user-images.githubusercontent.com/68043832/88535122-faf17f00-d03b-11ea-94c3-91e876967942.png)

使用changeData 和 read都不行，同时会在上面的位置报错，请帮忙定位下是不是bug，感谢

![image](https://user-images.githubusercontent.com/68043832/88535231-2a07f080-d03c-11ea-98f7-034ae63f74aa.png)

- **G6 Version**: 3.5.12
- **Platform**: Edge
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
请提供复现在线 demo

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
