### ISSUE TITLE
The "node:drop" event never gets triggered, "drop" event gets triggered twice

### ISSUE THREAD

**Issue by morficus** [antvis/G6#1848]
- **G6 Version**: 3.5.12
- **Platform**: Chrome
- **Mini Showcase(like screenshots)**:
- **CodePen Link**: https://codepen.io/morficus/pen/YzwbKYV

I have tried setting up listeners to the `node:drop` event on both the graph as well as on combos, but it never gets triggered.

On the main Graph
```
graph.on('node:drop', ev => {
  console.log('graph node:drop')
  document.getElementById('logoOutput').append('graph node:drop || ')
})
```

As part of a custom Combo
```
    shape.on('node:drop', ev => {
      console.log('customCombo node:drop')
     document.getElementById('logoOutput').append('customCombo node:drop || ')
    })
```

Using the CodePen link above, you can see how the regular `drop` event gets triggered as expected but `node:drag` never gets called. I can also see that the `drop` event gets triggered twice on the Graph element.

**Comment by Yanyan-Wang** [comment]
`combo:drop` but not `node:drop` should be listened since the `drop` event happens on the item to be dropped onto.
```
      graph.on('combo:drop', ev => {
        console.log('combo:drop')
        document.getElementById('logoOutput').append('combo:drop || ')
      })
```

You can also listen to `shape-name:drop` (where your shape's name is 'epoch' in your demo) for the single shape in the combo as:
```
      graph.on('epoch:drop', ev => {
        console.log('shape epoch:drop')
        document.getElementById('logoOutput').append('shape epoch:drop || ')
      });
```

And the node will receive `node:dragend` while dropping:
```
      graph.on('node:dragend', ev => {
        console.log('node:dragend')
        document.getElementById('logoOutput').append('node:dragend || ')
      })
```


See the complete demo [here](https://codepen.io/Yanyan-Wang/pen/NWxVbLO?editors=0010).

**Comment by morficus** [comment]
> since the drop event happens on the item to be dropped onto.
ahh that makes sense. 

I also did not realize I could do `shape-name:drop`. that is super helpful. thank you!
