### ISSUE TITLE
需求：dagre支持设置每层最多节点数，超过则换行展示

### ISSUE THREAD

**Issue by joychen1015** [antvis/G6#1853]
问题：现有的dagre的布局，若每层节点数过多时，图拓展非常宽，感觉显示不够友好。

需求：可否支持设置每层最多节点数；若超过，则节点换行展示。

如果自己想要实现一个这样的功能的话，是建议重新自定义LayOut，还是基于现有的dagre上进行改造？

非常感谢

**Comment by Yanyan-Wang** [comment]
G6 的 dagre 依赖了外部库 https://github.com/dagrejs/dagre 不支持换行。

建议布局完成后处理一下这种情况即可，其实布局只是在更改节点数据中的 x 和 y，可以通过监听 afterlayout 调整布局后的结果：

```
graph.on('afterlayout', e => {
  data.nodes.forEach(node => {
 // 以节点平移 (10, 10) 为例
    node.x = node.x + 10;
    node.y = node.y + 10;
  });
});
```
