### ISSUE TITLE
导入 G6 模块失败 （Vite、Typescript、Vue3、ESM）

### ISSUE THREAD

**Issue by Auxxxxlx** [antvis/G6#1854]
Vue3、ESM、TS、Vite

好像是 /@modules/@antv/util/lib/index.js 的 ES module 导出有问题
- **G6 Version**: 最新版
- **Platform**: macOS
- **Mini Showcase(like screenshots)**:  https://github.com/Auxxxxlx/animated-octo-succotash
<img width="956" alt="截屏2020-07-29 02 25 29" src="https://user-images.githubusercontent.com/13865581/88705960-c87e7980-d142-11ea-8627-809ec029b054.png">

**Comment by Auxxxxlx** [comment]
原因已经找到，因为@andv/g6/es 下的模块混用了非es模块的包，导致在纯 es module 的开发环境（vite、snowpack）下，导入失败。

具体原因：引入 比如 @andv/util、@antv/g-base 内的模块时，不是引入的对应的 @andv/util/esm 而是引入的 @andv/util/lib。

比如以下文件：
@andv/g6/es/behavior/behavior.js
```javascript
import { clone, each, wrapBehavior } from '@antv/util/lib';
```
应该改成
```javascript
import { clone, each, wrapBehavior } from '@antv/util/esm';
```

还有：@andv/g6/es/behavior/click-select.js
```javascript
import each from '@antv/util/esm/each';
```
应该改成
```javascript
import each from '@antv/util/esm/each';
```
类似有不少文件有很多需要改。

**Comment by baizn** [comment]
```
import { clone, each, wrapBehavior } from '@antv/util/lib';
```
类似使用了 lib 目录下的我们都会改成下面这样
```
import { clone, each, wrapBehavior } from '@antv/util';
```

> @antv/g6/es 下的模块混用了非es模块的包，导致在纯 es module 的开发环境（vite、snowpack）下，导入失败。

依赖的有些包本身就没有提供 es 模块，可以看下能否从编译工具层面解决这个问题，目前我们还不会只考虑纯 es module 的情况。

**Comment by Auxxxxlx** [comment]
@baizn  我通过 vite 的 optimzieDeps 可以对 @antv/g6 进行 pre build, 然后引入的问题可以解决，然后是下面这个问题可能需要 @antv/g6 这边解决一下，
vite 对 `@antv/g6` 进行 pre build 之后，控制台报如下错误，`不支持 require 语法`
<img width="370" alt="截屏2020-07-29 20 35 09" src="https://user-images.githubusercontent.com/13865581/88800603-0333f080-d1db-11ea-97e8-a5cad1f803e6.png">，

我看了下 @antv/g6/lib/index.js 发现如下代码：
<img width="703" alt="截屏2020-07-29 20 37 14" src="https://user-images.githubusercontent.com/13865581/88800794-4b531300-d1db-11ea-99fe-c998e9882d55.png">

这里对 package.json 使用 require 导入，使得 vite pre build 之后，也无法像 _interopRequireDefault 包裹的 require 的其他模块一样正确被处理。

**Comment by Miantang** [comment]
我遇到情况类似，
我发现这些代码模块，使用非ESM引入是这种写法
![image](https://user-images.githubusercontent.com/3156907/119625931-4849a300-be3d-11eb-9d8d-47e19bd58094.png)

`require("graphlib")`会被正常编译，但
typeof require === "function" 理应为true,实际未被编译
我的临时解决方案是
vite.config.js
`
if (command === 'build') {
    config.define = {
      'typeof require': '\'function\'',
    };
  }
`

如果有其他优雅的方案，欢迎后来者告知

**Comment by RSzyh** [comment]
@Miantang 我在build过程中遇到的，用了rollup插件 [@rollup/plugin-commonjs](https://www.npmjs.com/package/@rollup/plugin-commonjs)，把出现问题的包加进去就解决了
```javascript
{
  plugins: [
    commonjs({
      include: ['node_modules/graphlib/**/*', 'node_modules/dagre/**/*'],
    }),
  ]
}
```
看打包结果是插件重新生成了一个 require 方法，在没有配置的情况下它没有作用，但是可以解决这个场景下 `typeof require === 'function'` 判断的问题

![image](https://user-images.githubusercontent.com/24315632/122727901-1f84c400-d2aa-11eb-9106-0c5fe8a9e004.png)


![image](https://user-images.githubusercontent.com/24315632/122727661-d896ce80-d2a9-11eb-909d-0006ca1788b4.png)
