### ISSUE TITLE
Dagre布局，连接不同大小的节点时，间距不是对齐均分分配

### ISSUE THREAD

**Issue by heyang1014** [antvis/G6#1856]
在使用Darge布局时，自定义节点大小一致时，布局会是均分且对称分布的。但节点大小不一致时会存在不对称均分。
如果想要对称均分是不是不能定义layout，需要在数据中指定节点的位置，还是可以使用Darge布局，后面利用updateItem去更新节点位置

![image](https://user-images.githubusercontent.com/38655040/88751874-246cf080-d18b-11ea-9ab6-dbbcbe53abed.png)

![image](https://user-images.githubusercontent.com/38655040/88751902-32227600-d18b-11ea-8686-4d99779fb874.png)

上述图只是修改了节点类型，用的Darge布局。需要对称分布且节点大小不一致时是需要自定义节点坐标还是有其他办法

**Comment by Yanyan-Wang** [comment]
如果你没有配置 dagre 布局的 getWidth 的话，就是对称分布的呀

![image](https://user-images.githubusercontent.com/29593318/88786092-a4fc1300-d1c4-11ea-8a17-0f803394cdc3.png)
