### ISSUE TITLE
Lock/fixed Combo position

### ISSUE THREAD

**Issue by morficus** [antvis/G6#1857]
- **G6 Version**: 3.6.0
- **Platform**: MacOS + Chrome
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

Is it possible to "lock" a Combo in a specific position so that adding or removing nodes do not update its position? I have tried to create a custom layout as well as a custom Combo with no-op for `updateShape`, but this did not work. 

Also, what is the difference between Combo and Group? Is there a time when it is better to use Group in place of Combo?

**Comment by morficus** [comment]
Just for reference, I am trying to create a layout such as this one: 
![sample](https://user-images.githubusercontent.com/718799/88757880-14c2bd00-d135-11ea-8d32-ae260bc8d745.png)

**Comment by Yanyan-Wang** [comment]
Empty combo's x and y can be assigned in the data or by calling graph.updateItem(combo, {x, y}).

For the combo which is not empty, the position and size depend on its children items. There is a boolean configuration `onlyChangeComboSize` for `'drag-node'` and `'drag-combo'`, `onlyChangeComboSize: true` means users are not allowed to drag a combo or node out of its parent combo, while the parent combo's size will be changed to be able to contain the dragged item.

**Comment by Yanyan-Wang** [comment]
The node group will be discarded soon since the combo has covered the abilities of node group.

**Comment by lichunli6456** [comment]
我也是要做这种布局，请问有办法锁定组合的位置吗

**Comment by marspalLiu** [comment]
> Just for reference, I am trying to create a layout such as this one:
> ![sample](https://user-images.githubusercontent.com/718799/88757880-14c2bd00-d135-11ea-8d32-ae260bc8d745.png)

Hello sir, have you completed this layout？Can I refer to your implementation？
