### ISSUE TITLE
请问自定义锚点时，registerAnchor方法不存在，怎么扩展？

### ISSUE THREAD

**Issue by Kang127** [antvis/G6#1858]
- **G6 Version**:3.6.0
- **Platform**:react
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
3.x 不再支持 registerAnchor。G6 重新定位为图可视化与分析引擎，仅支持轻编辑场景。重编辑需求请使用 [AntV X6](https://x6.antv.vision/)。

在 3.x 版本的 G6 中，Anchor 可以通过 anchorPoints 指定，见 [节点的连接点 anchorPoint](https://g6.antv.vision/zh/docs/manual/middle/elements/anchorpoint)。内置节点的上、下、左、右锚点视觉表达是 [linkPoints](https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/circle/#linkpoints)。自定义节点可以自己随意绘制图形来代表视觉上的锚点。
