### ISSUE TITLE
拖动时鼠标经过checkbox，拖动异常

### ISSUE THREAD

**Issue by Enivia** [antvis/G6#1859]
- **G6 Version**: latest
- **Platform**: windows
- **Mini Showcase(like screenshots)**: ![bug.gif](https://i.loli.net/2020/07/30/JdhGUgZstVfe9H1.gif)
![bug2.gif](https://i.loli.net/2020/07/30/1D63MmEeLrPBxg2.gif)
- **CodeSandbox Link**: https://codesandbox.io/s/charming-rain-h58my?file=/index.js

拖动时鼠标经过disabled状态的checkbox时松开鼠标 会导致节点/画布随鼠标移动。

**Comment by Yanyan-Wang** [comment]
mac 没复现，windows Microsoft Edge 84、FireFox、Chrome 84 没复现。

你用的什么浏览器？之前修复过类似问题 https://github.com/antvis/G6/issues/1750#issuecomment-652766754

先确认一下是不是最新版本

**Comment by Enivia** [comment]
g6@3.6.0，windows chrome 84，mac均可复现。checkbox/radio的disabled状态都不会相应mouseup事件。
demo见上面的CodeSandbox链接。拖动状态下，鼠标在checkbox/radio上面释放能够复现这个问题。

**Comment by Yanyan-Wang** [comment]
我们在拖拽时，若将元素拖出画布，会监听画布外的事件，释放鼠标时终止拖拽。因为 disabled 状态的 input 不相应任何事件，所以没办法绑定监听来做到在它上面释放鼠标时终止拖拽。只能尽量避免在画布周围放置这类 disabled 的 input。

**Comment by zhangbing3** [comment]
我的外围还没有输入框，在windows电脑拖出去画布，松开鼠标，然后点击画布就一直是选中状态了。
