### ISSUE TITLE
设置文本背景，文本在节点右侧时，padding无法正常生效

### ISSUE THREAD

**Issue by webpawn** [antvis/G6#1861]
![image](https://user-images.githubusercontent.com/45424583/88900492-046c2880-d282-11ea-926f-809b01aae6da.png)
如官网实例所示，文本无法在背景中居中

**Comment by Yanyan-Wang** [comment]
暂时通过调整 padding: [2, 2, 0, 2] 满足一下。我们再跟进问题。
