### ISSUE TITLE
dom自定义节点实现拖拽

### ISSUE THREAD

**Issue by Qingkongji** [antvis/G6#1864]
- **G6 Version**:3.6.0
- **Platform**: chrome
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:  https://g6.antv.vision/zh/examples/item/customNode#svgDom

使用dom进行自定义节点时，如果要设置可拖拽的话，注册时设置draggable，并且在modes里的default添加drag-node就可以了吗？我在上面链接的demo里添加modes后还是无法拖拽，还需要添加dom事件吗？

**Comment by baizn** [comment]
DOM 节点不支持这些事件，有交互的话建议还是用非 DOM 的方式定义。
