### ISSUE TITLE
`anchorPoints` doesn't seem to work for combos.

### ISSUE THREAD

**Issue by kravinash13** [antvis/G6#1865]
- **G6 Version**: 3.6.0
- **Platform**: MacOS
- **Mini Showcase(like screenshots)**:
- **CodePen Link**: [Link](https://codesandbox.io/s/dawn-star-6hck9?file=/index.js)

Can we control the start and end of the edges for combos?
As `anchorPoints` doesn't seems to work for the combos. When we collapse the combos the start of the edges doesn't follow  the `anchorPoints`. Any suggestions or solutions to achieve the same?

**Comment by Yanyan-Wang** [comment]
Try to set the `sourceAnchor` and `targetAnchor` for defaultEdge

![image](https://user-images.githubusercontent.com/29593318/89024137-37ccb700-d357-11ea-9f3d-2fd0070f01aa.png)
