### ISSUE TITLE
贝塞尔连线与箭头

### ISSUE THREAD

**Issue by LENZAKON** [antvis/G6#1867]
![image](https://user-images.githubusercontent.com/23180703/89005576-66d33080-d337-11ea-81c3-27dcd680f641.png)

https://codesandbox.io/s/jolly-bogdan-zefwp?file=/index.js

hello，请问有办法让黄色的连接线 endPoint 的位置位于灰色箭头的最上面横线的中间吗？而不是节点的中间

**Comment by Yanyan-Wang** [comment]
箭头的坐标系是根据所在位置边的切线确定的。可以自己写 path 路径做倾斜 https://g6.antv.vision/zh/docs/manual/advanced/custom-edge#4-%E8%87%AA%E5%AE%9A%E4%B9%89%E7%AE%AD%E5%A4%B4

**Comment by LENZAKON** [comment]
如果期望箭头是垂直的，是没法控制边的结束点的么？

**Comment by LENZAKON** [comment]
> 箭头的坐标系是根据所在位置边的切线确定的。可以自己写 path 路径做倾斜 https://g6.antv.vision/zh/docs/manual/advanced/custom-edge#4-%E8%87%AA%E5%AE%9A%E4%B9%89%E7%AE%AD%E5%A4%B4

如果期望箭头是垂直的，是没法控制边的结束点的么？

**Comment by Yanyan-Wang** [comment]
这个不是边结束点的问题，箭头是放在边结束点的位置的，也就是说箭头位置取决于边结束点，边不能根据箭头来决定结束位置。

可以用 `curvePosition` 调整 `cubic-vertical` 的控制点位置，让贝塞尔曲线形状变化一下，结束位置看起来更“垂直”与节点。例如
```
defaultEdge: {
  //...
  curvePosition: [0.9, 0.1], // 默认是 [0.5, 0.5]
}
```
