### ISSUE TITLE
力导向图设置防止重叠，渲染后再拖拽失效

### ISSUE THREAD

**Issue by 1193538012** [antvis/G6#1868]
- **G6 Version*3.6.0*:
- **Platform*windows*:
- **Mini Showcase(like screenshots)**:
- **CodePen Link: https://codepen.io/1193538012/pen/yLemyjb **:
刚开始渲染后是不重叠的，但是渲染后再拖拽节点至其他节点上，还是会覆盖。
如果给节点拖拽后添加graph.render()，虽然会不重叠，但是体验很差（比如拖拽时缩放了画布，重新渲染的话会自己放大）。
想用G6实现graphin的这种效果，
     1.拖拽后以拖拽的节点为中心，其他节点跟着他过来。
     2.拖拽时其他的节点不动。
https://gs-share-cn-shanghai.aliyuncs.com/index8b5ab67a3e754e02a77aae7871465031.html#/?mock=true&source=graphin

**Comment by Yanyan-Wang** [comment]
https://g6.antv.vision/zh/examples/net/forceDirected#forceDirectedPreventOverlap
