### ISSUE TITLE
插件destoryBug 

### ISSUE THREAD

**Issue by yehuozhili** [antvis/G6#1870]
复现地址： https://codesandbox.io/s/twilight-wave-ue4r7?file=/src/App.js

![8ec5a8e002f0579ab12854a3b699733](https://user-images.githubusercontent.com/34372936/89130575-7f5e6900-d538-11ea-8ff9-6eaa69e3453b.png)

destroy graph时报错，大概看了下，是插件destroy报错，应该是插件会去找IPluginBaseConfig里的canvas字段，但是没有canvas。
试了下plugin放入useEffect也会报错。
也许我destroy方法不对？

**Comment by Yanyan-Wang** [comment]
你 destroy 了两次。

把 graph 声明成全局变量，在 useEffect 里面判断如果 graph 存在了就不要继续执行。

**Comment by yehuozhili** [comment]
我将graph声明了全局变量，useEffect里判断或者不判断还是会报同样的错，可以给个不报错demo吗？

**Comment by yehuozhili** [comment]
> 你 destroy 了两次。
> 
> 把 graph 声明成全局变量，在 useEffect 里面判断如果 graph 存在了就不要继续执行。

这问题关的也太快了吧 ，而且正常来说，不是应该destroy逻辑里进行判断，而不应该使用者进行判断？

**Comment by Yanyan-Wang** [comment]
![image](https://user-images.githubusercontent.com/29593318/89498262-7d263400-d7f0-11ea-9045-60245a2e517e.png)

声明全局变量也是常规用法，否则每次渲染组件都会创建一个 graph

**Comment by yehuozhili** [comment]
好的谢谢
