### ISSUE TITLE
请问下Menu插件如何针对画布事件和节点事件和连接事件如何区分目前好像就只能是节点事件可能用

### ISSUE THREAD

**Issue by 929496959** [antvis/G6#1871]
请问下Menu插件如何针对画布事件和节点事件和连接事件如何区分目前好像就只能是节点事件可能用

**Comment by Yanyan-Wang** [comment]
节点和边都能用：https://g6.antv.vision/zh/examples/tool/contextMenu

画布的 menu 可以自己写一个 DOM 控制显示隐藏即可，挂载方式参考：https://www.yuque.com/antv/g6-blog/gp2dxk#HjQrZ
