### ISSUE TITLE
Combo doesn't work at all

### ISSUE THREAD

**Issue by laubonghaudoi** [antvis/G6#1872]
- **G6 Version**: v3.6.0
- **Platform**: macOS Catalina 10.15.6 and Windows 10
- **Mini Showcase(like screenshots)**:
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/11172180/89147904-03026080-d50d-11ea-9953-179d1c78b539.png">

- **CodePen Link**:
Unnecessary codes are omitted:
```ts
const data = {
  nodes: [
    {
      id: 'node1',
      comboId: 'combo'
    },
    {
      id: 'node2',
      comboId: 'combo'
    },
  ],
  combos: [{
    id: 'combo',
    label: 'Combo'
  }]
};

const graph = new G6.Graph({
  container: 'container',
  width,
  height,
  // translate the graph to align the canvas's center, support by v3.5.1
  fitCenter: true,
  // Set groupByTypes to false to get rendering result with reasonable visual zIndex for combos
  groupByTypes: false,
  defaultCombo: {
    type: 'circle',
    style: {
      lineWidth: 1,
    },
    labelCfg: {
      refY: 10,
      position: 'top',
      style: {
        fontSize: 18,
      }
    }
  },
  modes: {
    default: ['drag-canvas', 'drag-node', 'drag-combo', 'collapse-expand-combo'],
  },
});

```

I am trying to replicate the example codes of combos [here](https://g6.antv.vision/en/examples/item/defaultCombos), but it never works for me. The error message is shown in the screenshot. Whenever I change the data fields from `combos` to `groups` and `comboId` to `groupId` (substituting everything about combos into groups), it works properly. Also, if I remove all `combos` from the data, leaving only nodes and edges, it runs fine as well. I am using TypeCcript 3.8.3 and maybe this is an TypeScript related error?

Another feature request: I hope all example codes can be written in TypeScript in the future, or at least provide a TypeScript version of the example codes.

**Comment by Yanyan-Wang** [comment]
Be sure that each node in the data has unique string id, and the each edge's source and target both exist in the `nodes` of data. 

If your code works on our website, it won't be a bug of G6. Maybe you can replicate your problem in codesandbox.io and share the link to me so that I can locate the problem.

**Comment by laubonghaudoi** [comment]
Finally I figured out why it breaks. Because one of my nodes shares the same id with the combo, like this:
```ts
nodes: [
    {
        id: "id1",
        comboId: "id1"
    },
    {
        id: "id2",
        comboId: "id1"
    },
],
combos: [
    {
         id: "id1"
    }
]
```
So the comboId must not be the same as the node id, right?

**Comment by Yanyan-Wang** [comment]
Yes, we will try to emphasize this problem in docs and warn the users in console.
