### ISSUE TITLE
力导向图可以设置边不重叠吗？

### ISSUE THREAD

**Issue by 1193538012** [antvis/G6#1873]
![image](https://user-images.githubusercontent.com/42637805/89154035-b82e2a80-d598-11ea-9530-5a60c5e63625.png)

- **G6 Version*3.6.0*:
- **Platform*windows*:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
没有直接指定边不可重叠的参数，但是你这个图明显布局没有收敛，或者 linkDistance 太长了
