### ISSUE TITLE
使用group作为keyShape注册node，拖动时行为怪异

### ISSUE THREAD

**Issue by zuiidea** [antvis/G6#1874]
- 注册`node`时，返回`keyShape`为`group`，拖动时频繁出现回弹怪异效果：

```js
G6.registerNode('iconfont', {
  draw(cfg, group) {
    const { backgroundAttrs, iconAttrs, labelAttrs, id } = cfg
    const nodeGroup = group.addGroup({
      id: `nodeGroup__${id}`,
      name: 'node-group',
      draggable: true,
      attrs: {
        cursor: 'move',
      },
    })

    nodeGroup.addShape('circle', {
      attrs: {
        x: 0,
        y: 0,
        r: cfg.size,
        cursor: 'move',
        ...backgroundAttrs,
      },
      draggable: true,
      name: 'circle-shape',
    })

    nodeGroup.addShape('text', {
      attrs: {
        x: 0,
        y: 0,
        fontFamily: 'graph_iconfont',
        textAlign: 'center',
        textBaseline: 'middle',
        text: cfg.text,
        fontSize: cfg.size / 2,
        cursor: 'move',
        ...iconAttrs,
      },
      draggable: true,
      name: 'text-iconfont',
    })

    const labelY = cfg.size + 4
    group.addShape('text', {
      attrs: {
        x: 0,
        y: labelY,
        textAlign: 'center',
        ...labelAttrs,
      },
      name: 'text-label',
    })

    return nodeGroup
  },
})

```
- 效果演示

![未命名](https://user-images.githubusercontent.com/16070518/89161350-13661a00-d5a5-11ea-920d-c86e2a3a7a5e.gif)

- 在线示例

[![Edit React G6 Force Graph Drag Issue](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-g6-force-graph-drag-issue-hldw9?fontsize=14&hidenavigation=1&theme=dark)

**Comment by Yanyan-Wang** [comment]
keyShape 就是 shape，不是 group

**Comment by zuiidea** [comment]
@Yanyan-Wang 找到原因了，由于开启 `animate` 造成的，开启 `animate` 后，拖动节点时，`force` 计算会有大概`0.5s` 的 delay，这里可以关注一下。
上例描述的 `keyShape` 指的是`circle-shape `及`text-iconfont` 组成的 `group`，若只返回`circle-shape `或`text-iconfont`，拖动时会造成部分区域无法`focus`。

**Comment by Yanyan-Wang** [comment]
> 由于开启 animate 造成的，开启 animate 后，拖动节点时，force 计算会有大概0.5s 的 delay，这里可以关注一下。

谢谢，后续有时间会跟进下。

> 上例描述的 keyShape 指的是circle-shape 及text-iconfont 组成的 group，若只返回circle-shape 或text-iconfont，拖动时会造成部分区域无法focus。

无法 focus 的问题，把 addShape 的图形都加上 capture: true，如果是无法拖动，加上 draggable: true。这些属性和 name、attrs 平级
