### ISSUE TITLE
自定边的labelAutoRotate属性不生效

### ISSUE THREAD

**Issue by chenbj2333** [antvis/G6#1876]
- **G6 Version**: 3.6.0
- **Platform**: chrome
- **CodePen Link**: https://codesandbox.io/s/evtfv

官网的自定义边的第三个例子，文字并没有跟着线自动旋转

**Comment by Yanyan-Wang** [comment]
你的自定义边绘制逻辑中没有控制旋转的逻辑，就不会旋转呀。内置边写好了跟随便旋转的逻辑才可以的。

可以这样写：

```
const label = group.addShape('text', {...});
label.rotateAtStart(rotate); // rotate 是旋转角度，根据边的斜率确定
```

**Comment by WFSMYH** [comment]
label.rotateAtStart(rotate); // rotate 是旋转角度，根据边的斜率确定

边的斜率如何获取呢？

**Comment by Jaydar** [comment]
let radian = Math.atan((startPoint.y - endPoint.y) / ((startPoint.x - endPoint.x)));
startLabel.rotateAtStart(radian);

**Comment by auuunya** [comment]
> let radian = Math.atan((startPoint.y - endPoint.y) / ((startPoint.x - endPoint.x))); startLabel.rotateAtStart(radian);

为啥使用这个确定斜率之后，移动节点文本自己原地旋转？
