### ISSUE TITLE
问题：同一个父节点下新增节点组，位置有偏移

### ISSUE THREAD

**Issue by heyang1014** [antvis/G6#1877]
新增前：
![71596448033_ pic](https://user-images.githubusercontent.com/38655040/89170186-d94f4500-d5b1-11ea-887f-dd183be2d324.jpg)

点击添加添加条件：
![81596448093_ pic](https://user-images.githubusercontent.com/38655040/89169982-9a20f400-d5b1-11ea-920e-b1de556a9ceb.jpg)

添加后查看graph.save()中的数据发现新增的节点和之前存在节点Y坐标不同，请问有什么办法能让新增节点和之前存在节点对齐

**Comment by heyang1014** [comment]
已解决

**Comment by yanyu0517** [comment]
请问这个问题如何解决的？

**Comment by yanyu0517** [comment]
mark下，给edges数组中的对象增加weight
```
edges: [{
    source: 'source',
    target: 'target',
    weight: 1
}]
```
