### ISSUE TITLE
beforeremoveitem  回调缺乏详情节点信息

### ISSUE THREAD

**Issue by monijiang** [antvis/G6#1878]
- **G6 Version**: 3.5.9
- **Platform**: react
- **Mini Showcase(like screenshots)**: https://codepen.io/monijiang/pen/RwabKBL
- **CodePen Link**: https://codepen.io/monijiang/pen/RwabKBL

删除节点后的回调返回只有{item:{_cfg:null,destroyed: true}}，无法得知具体哪个节点被删除了。
之前使用的3.4.7版本是有节点信息的

**Comment by monijiang** [comment]
这个返回以前_cfg就是null,但是item的实例之前是有一个私有属性defaultCfg,通过这个属性也可以得知删除的节点信息。在版本的更新中，该字段被去除了

**Comment by Yanyan-Wang** [comment]
下个小版本给返回的 item 赋值为被删除节点的 model

**Comment by Yanyan-Wang** [comment]
v3.6.1 已修复
