### ISSUE TITLE
问题：darge布局同一父节点向上对齐的问题

### ISSUE THREAD

**Issue by heyang1014** [antvis/G6#1879]
问题描述：darge的自上而下布局，期望同一个父节点下，子节点是向上对齐的。多余的连线是放在下面的
<img width="613" alt="WeChat1afc53f5383cad3ba495460b4ec8a98c" src="https://user-images.githubusercontent.com/38655040/89247869-d8b1bf80-d640-11ea-8d2a-c6f4c15060d4.png">
期望图中1，2对应的和3，4对齐，左边的整体向上对齐。
初始数据是两边都是两个，点击在右边多插入了一个节点

**Comment by Yanyan-Wang** [comment]
G6 的 dagre 布局引用了外部库 https://github.com/dagrejs/dagre/wiki

该库不支持这种对齐方式，考虑利用 G6 布局的可独立执行机制，构建虚拟数据（增加一个对称的节点到虚拟数据中）并布局。例如

https://codepen.io/Yanyan-Wang/pen/rNeBZry

**Comment by 895433995** [comment]
给1和3设置weight等于2，别的不设置，试试

**Comment by heyang1014** [comment]
> 给1和3设置weight等于2，别的不设置，试试
没懂你意思，设置weight？大佬指导下，就剩沉底的问题困扰着

**Comment by git119** [comment]
遇到同样的问题，寻求帮助，谢谢
