### ISSUE TITLE
地铁Demo图，点击放大变形

### ISSUE THREAD

**Issue by liuyuchuan** [antvis/G6#1880]
- **G6 Version**: 3.6.0
- **Platform**: Mac , Google
- **Mini Showcase(like screenshots)**:
- **CodePen Link**: https://g6.antv.vision/zh/examples/case/metroLines

question：
案例图，点击放大，地铁流线变形了。
![image](https://user-images.githubusercontent.com/12453224/89367964-f0ef1080-d70c-11ea-996a-6bed3abe9867.png)

**Comment by Yanyan-Wang** [comment]
什么点击放大？

**Comment by liuyuchuan** [comment]
![image](https://user-images.githubusercontent.com/12453224/89368027-1da32800-d70d-11ea-8cb2-507c45210bae.png)

**Comment by liuyuchuan** [comment]
图片放到Github上面挂掉了，我现在丢在CSDN上面，下面是链接地址：

图一：
https://img-blog.csdnimg.cn/20200805111840927.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L0xfTHljb3M=,size_16,color_FFFFFF,t_70

图二：
https://img-blog.csdnimg.cn/20200805111820246.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L0xfTHljb3M=,size_16,color_FFFFFF,t_70

**Comment by Yanyan-Wang** [comment]
这个要根据实际需求去调整一下背景图片的尺寸。这个 demo 就是一个简单示例，这里设置了背景是 100% 平铺导致的：

```
graph.get('container').style.background = '#000';
graph.get('container').style.backgroundImage =
  'url("https://gw.alipayobjects.com/mdn/rms_f8c6a0/afts/img/A*G23iRqkiibIAAAAAAAAAAABkARQnAQ")';
graph.get('container').style.backgroundSize = 'auto 100%';
```

**Comment by liuyuchuan** [comment]
好的，多谢。
