### ISSUE TITLE
destroy的时候不能粗暴的把g6-tooltip给全部清除掉

### ISSUE THREAD

**Issue by zhong1158414332** [antvis/G6#1882]
G6 Version: v3.6.0
Platform: react
我在一个页面中同时存在了两个Graph，都添加了tooltip，这个时候destroy其中某一个Graph，代码就会粗暴的把所有的g6-tooltip给清除掉，另外一个就产生了异常没有tooltip了。

**Comment by Yanyan-Wang** [comment]
下个小版本修复

**Comment by Yanyan-Wang** [comment]
v3.6.1 已修复

**Comment by Elias-cug** [comment]
> v3.6.1 已修复
目前3.8.0还是存在这个问题，使用plugins创建tooltip
