### ISSUE TITLE
目前可以实现缩放时点边的lineWidth，点的Fontsize固定吗

### ISSUE THREAD

**Issue by zuiidea** [antvis/G6#1884]
问题：
- 希望缩放时点边的lineWidth，点的Fontsize固定，不随`zoom-canvas`的缩放而改变

演示效果：

![未命名](https://user-images.githubusercontent.com/16070518/89285874-bee59c00-d683-11ea-8249-3da048cc718a.gif)

演示地址：

[![Edit React G6 Force Graph Style Issue](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-g6-force-graph-style-issue-dfmdo?fontsize=14&hidenavigation=1&theme=dark)

**Comment by Yanyan-Wang** [comment]
https://g6.antv.vision/zh/docs/manual/middle/states/defaultBehavior#zoom-canvas


`fixSelectedItems` 可以固定选中状态的元素

**Comment by zuiidea** [comment]
@Yanyan-Wang 这里指的是一种通用的需求，不仅限于状态和缩小时固定状态，举个例子，比如节点的标签，对于用户来讲，能够可阅读才是重要的，画布放大，标签随着放大会使图形变得更乱。
- 比如 Echarts的边的大小和标签，在缩放时是不会变化的
https://echarts.apache.org/examples/zh/editor.html?c=graph

**Comment by Yanyan-Wang** [comment]
感谢建议，欢迎 PR。

**Comment by Elias-cug** [comment]
> 感谢建议，欢迎 PR。

这个优化项有加吗

**Comment by GPXNB** [comment]
> 感谢建议，欢迎 PR。

都2022年了，上面的优化项有了吗～

**Comment by gpxCode** [comment]
> 

大佬，都2022年了，上面的优化项有了吗～

**Comment by gpxCode** [comment]
> 感谢建议，欢迎 PR。

大佬，都2022年了加👆这个优化项了吗？
