### ISSUE TITLE
求助：重新编辑下问题。以compactBox类型的 V图谱为例。getVGap计算的永远是某个节点距离其下方节点的距离(不管此节点是在中心点的上方或下方)。这样的话，就导致单独设置某些节点的getVGap时，最终图谱呈现效果，中心点的上方和下方有明显的差异。是不是可以考虑以中心节点作为分割，其下方的节点，getVGap改变为计算本身节点与上方节点的距离。这样效果就会符合预期。下面留言有详细截图说明(其实左右在使用getHGap时同理)

### ISSUE THREAD

**Issue by d623141153** [antvis/G6#1885]
- **G6 Version**:最新的版本与之前的版本都是这样
- **Platform**: mac，windows
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

<img width="428" alt="截屏2020-08-05上午10 20 39" src="https://user-images.githubusercontent.com/25069302/89364573-5a6b2100-d705-11ea-9bb1-feaf5782833e.png">
<img width="370" alt="截屏2020-08-05上午10 25 44" src="https://user-images.githubusercontent.com/25069302/89364889-175d7d80-d706-11ea-9929-41359749b5e8.png">

**Comment by Yanyan-Wang** [comment]
https://g6.antv.vision/zh/examples/tree/compactBox#basicCompactBox

这个不管是 V 还是 H 都是有效果的。看下是不是因为你 fitView 了导致看不出来效果

**Comment by d623141153** [comment]
您好，感谢回复🙏！
我在官方示例上写了demo，呈现如下图所示，截图有明确注释
<img width="1603" alt="截屏2020-08-05上午11 31 28" src="https://user-images.githubusercontent.com/25069302/89368970-68be3a80-d70f-11ea-86c5-d4eee9f953c4.png">

**Comment by d623141153** [comment]
基本总结一下就是， 朝下方向设置的间距，最终呈现都是本身与其子级的间距
但朝上方向设置的间距，就是本身与其父级的间距（这是预期想要的效果）

**Comment by d623141153** [comment]
理解了一下，这个图是被看作一个整体的，所以间距代码执行的方向就永远是由上至下的，所以想改变 “Classification” 与 “Modeling Methods” 之间的间距 就要设置 “Modeling Methods” 的 getVGap，但这样的话 “Consensus” 与 “Modeling Methods” 之间的间距就跟着变了。。。。。。
请教一下，现在这个版本，可以通过其他代码实现如上图所示的改变 “Classification” 与 “Modeling Methods” 之间的间距，但不改变 “Consensus” 与 “Modeling Methods” 之间的间距吗？

**Comment by d623141153** [comment]
> https://g6.antv.vision/zh/examples/tree/compactBox#basicCompactBox
> 
> 这个不管是 V 还是 H 都是有效果的。看下是不是因为你 fitView 了导致看不出来效果
您好，感谢回复🙏！
我在官方示例上写了demo，呈现如下图所示，截图有明确注释
<img width="1603" alt="截屏2020-08-05上午11 31 28" src="https://user-images.githubusercontent.com/25069302/89382158-e93f6400-d72c-11ea-9e80-f33428bca4f6.png">

**Comment by d623141153** [comment]
> > https://g6.antv.vision/zh/examples/tree/compactBox#basicCompactBox
> > 这个不管是 V 还是 H 都是有效果的。看下是不是因为你 fitView 了导致看不出来效果
> > 您好，感谢回复🙏！
> > 我在官方示例上写了demo，呈现如下图所示，截图有明确注释
> 
> <img alt="截屏2020-08-05上午11 31 28" width="1603" src="https://user-images.githubusercontent.com/25069302/89382158-e93f6400-d72c-11ea-9e80-f33428bca4f6.png">

其实结果就是，想改变 “Classification” 与 “Modeling Methods” 之间的间距，就要设置 “Modeling Methods” 的 getVGap，但这样的话 “Consensus” 与 “Modeling Methods” 之间的间距就跟着变了。
目前的情况就是，图谱设置的getVGap，都是其本身与其下方的节点的距离。
因此当图谱朝下时，就不符合自己的预期效果。不知道我解释的清楚不。。。。。。
所以请教一下，现在这个版本，可以通过其他代码实现如上图的只改变 “Classification” 与 “Modeling Methods” 之间的间距，但不改变 “Consensus” 与 “Modeling Methods” 之间的间距吗？

**Comment by kangtaoKT** [comment]
是的，假如一个父节点连接的子节点往下，又要设置子节点与父节点的竖向间距不同，实际上设置不了，因为往上只有一个父节点，控制着所有子节点的间距。
