### ISSUE TITLE
G6 中内置的 contextMenu,handleMenuClick回调函数有bug 

### ISSUE THREAD

**Issue by LincolnPack** [antvis/G6#1887]
G6 中内置的 contextMenu,handleMenuClick回调函数有bug ，
点击（右击）节点或者边的时候，handleMenuClick会多次调用。 节点历史记录没有清除。

**Comment by evan-guo** [comment]
我也遇到了这个问题，坑了我一个下午。。。菜单点击的时候，事件会触发多遍，而且是次数叠加的，第一次2，第二次4，这样叠加下去。。我现在是改了源码，o && n.addEventListener("click", (function (e) {o(e.target, t.item)}))改成 o && n.addEventListener("click", (function (e) {o(e.target, t.item)}),{once:true}) 。但是还是always触发两遍，把触发的回调函数(function (e) {o(e.target, t.item)})抽出去之后，结果因为打包的是严格模式不能拿到event事件我鈤

**Comment by LincolnPack** [comment]
hi.兄弟，加个qq交流一下

**Comment by Yanyan-Wang** [comment]
下个小版本修复

**Comment by LincolnPack** [comment]
嘿嘿，几时发布下个小版本。

**Comment by Yanyan-Wang** [comment]
下周吧

**Comment by shengxiaoliang** [comment]
我也遇到这个问题了

**Comment by Yanyan-Wang** [comment]
v3.6.1 已修复

**Comment by LincolnPack** [comment]
fix: menu plugin with clickHandler problem;
版本3.6.1中右击菜单handleMenuClick仍有bug；

操作：多次在同一个节点右击，改变menu菜单位置
现象：此时点击菜单项，触发handleMenuClick回调（仍然会多次触发此回调）

分析：可能出现这个bug 的原因时因为多次右击节点，没有清除上一次的事件绑定。造成事件多次绑定 。
结果：应该在每次显示菜单的时候，清除之前绑定的事件。

**Comment by xialvjun** [comment]
v3.6.1 仍然有此 bug...
```ts
g.on(G6Event.CONTEXTMENU, (e: any) => {
  e.preventDefault();
  console.log(0, e);
})
g.on(G6Event.NODE_CONTEXTMENU, (e: any) => {
  e.preventDefault();
  console.log(1, e);
})
```
在节点上右键, 显示 001
