### ISSUE TITLE
registernode时的anchorPoints怎么显示

### ISSUE THREAD

**Issue by nicewahson** [antvis/G6#1890]
- **G6 Version**:
3.6.0
- **Platform**:
mac
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:
https://codesandbox.io/s/epic-liskov-tcipc?file=/index.js

现在不能看到有圆圈的显示 是缺什么码

**Comment by Yanyan-Wang** [comment]
这样写 

https://codesandbox.io/s/nervous-rosalind-n1ete
