### ISSUE TITLE
G6内置插件Menu的handleMenuClick函数BUG，多次叠加触发

### ISSUE THREAD

**Issue by evan-guo** [antvis/G6#1891]
在使用插件Menu的时候，点击右键菜单项，总是会在单次点击的基础上叠加前面触发的次数。在官方的上下文菜单实例中，已经有体现。如下是官方文档给的实例，这里的handleMenuClick，每次打印的次数都会比前面多一次。初步认为可能是addEventListener的监听事件叠加绑定了。而且菜单消失时的removeEventListener不知为何没有生效，导致出现的这个问题。

const contextMenu = new G6.Menu({
  getContent(graph) {
    console.log('graph',graph)
    return `<ul>
      <li title='1'>测试01</li>
      <li title='2'>测试02</li>
      <li>测试03</li>
      <li>测试04</li>
      <li>测试05</li>
    </ul>`;
  },
  handleMenuClick: (target, item) => {
    console.log(target, item)
  }
});

**Comment by evan-guo** [comment]
目前初步解决问题，将源码内onMenuShow的addEventListener("click", (function (e) {o(e.target, t.item)})) 中的回调方法抽出来，塞入this里面，使监听函数成为唯一，问题解决。猜测是因为闭包原因，使每次为事件添加的监听函数都不是同一个，导致在事件上不停叠加。而且onMenuHide函数里的removeEventListener操作，解绑的是var e = this.get("handleMenuClick")这个函数！所以前后绑定解绑的函数不一致~出现了这个问题

**Comment by LincolnPack** [comment]
我用的vue-cli 在g6 依赖包是在node_modules里面，源码修改以后不起作用，估计是vue用的是g6的dist文件

**Comment by Yanyan-Wang** [comment]
下个小版本修复

**Comment by Yanyan-Wang** [comment]
v3.6.1 已修复
