### ISSUE TITLE
G6 力导向图不支持fitView

### ISSUE THREAD

**Issue by wolful** [antvis/G6#1894]
- **G6 Version**: 3.6.0
- **Platform**: / 
- **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/11292892/89525861-6d6f1580-d819-11ea-8922-9a0b608e3890.png)

- **CodePen Link**: 直接在官方demo上render()下方添加fitVIew()，整个canvas会白掉, https://g6.antv.vision/zh/examples/net/forceDirected#forceDirectedFunctionalParams

**Comment by Yanyan-Wang** [comment]
因为在 render 下执行 fitView 的时候图还没有收敛。两种方式：

- 在布局完成后调用 fitView
```
graph.on('afterlayout', e=> {
  graph.fitView()
})
```

- 为 force 加 onTick 做限制，布局过程中不超出范围：
https://g6.antv.vision/zh/examples/net/forceDirected#forceConstrainedInRect

**Comment by wolful** [comment]
> 因为在 render 下执行 fitView 的时候图还没有收敛。两种方式：
> 
> * 在布局完成后调用 fitView
> 
> ```
> graph.on('afterlayout', e=> {
>   graph.fitView()
> })
> ```
> 
> * 为 force 加 onTick 做限制，布局过程中不超出范围：
>   https://g6.antv.vision/zh/examples/net/forceDirected#forceConstrainedInRect

可以了，afterLayout后fitView会闪一下，这个可优化吗

**Comment by Yanyan-Wang** [comment]
那就尝试第二个方法吧
