### ISSUE TITLE
graph.createCombo创建的combo内部nodes会重复

### ISSUE THREAD

**Issue by sdhr27** [antvis/G6#1896]
- **G6 Version**: 3.6.0
- **Platform**: windows
- **Mini Showcase(like screenshots)**: ![image](https://user-images.githubusercontent.com/37827411/89628212-8ede0900-d8ce-11ea-9868-c2032ea44422.png)
- **CodePen Link**: https://stackblitz.com/edit/react-j8eec5-mbkwab?file=index.js

使用graph.createCombo创建combo后，直接查看、使用combo.getChildren、combo.getNodes()均会得到重复的nodes

**Comment by Yanyan-Wang** [comment]
谢谢，下个小版本修复

**Comment by Yanyan-Wang** [comment]
v3.6.1 已修复

**Comment by sdhr27** [comment]
测试后有一个小问题，所创建的combo包含的nodes的comboId并没有同时更新，导致通过graph.createCombo创建的分组内部的nodes第一次无法拖出，是必须要手动更新所包含nodes的comboId么？
