### ISSUE TITLE
dagre布局

### ISSUE THREAD

**Issue by 895433995** [antvis/G6#1901]
请问dagre布局能不能根据某一个属性来进行排序，比如现在是从上往下布局，然后我需要根据某一个属性来控制每一个分支的左右顺序。或者有没有别的布局方式来实现

**Comment by 895433995** [comment]
![image](https://user-images.githubusercontent.com/39820191/89755772-2764cb00-db13-11ea-8bdb-16cd8dbf7bb4.png)
能否将图中的分支按条件顺序从左往右排列

**Comment by Yanyan-Wang** [comment]
dagre 引用了外部库 https://github.com/dagrejs/dagre

排序是按照图的结构启发式遍历来的，没有提供自定义顺序的参数。只能在布局完成后再自己设计策略调整一下节点的坐标
```
graph.on('afterlayout', e=> {
  graph.getNodes().forEach(node => {
    graph.updateItem(node, {
      x: ...
      y: ...
    })
  });
});

**Comment by heyang1014** [comment]
和我做的东西一样，可以设置同列的顺序，通过edges的边在数组中的顺序来改变。大佬留个联系方式给你说

**Comment by chengwenxin** [comment]
> 和我做的东西一样，可以设置同列的顺序，通过edges的边在数组中的顺序来改变。大佬留个联系方式给你说

wx 18821709973，大佬方便交流吗

**Comment by 1634228212** [comment]
> 和我做的东西一样，可以设置同列的顺序，通过edges的边在数组中的顺序来改变。大佬留个联系方式给你说

大佬方便交流吗 wx15079201898

**Comment by xw-xw12** [comment]
> 和我做的东西一样，可以设置同列的顺序，通过edges的边在数组中的顺序来改变。大佬留个联系方式给你说

大佬 我想了解下
