### ISSUE TITLE
使用css的transform中的rotate方法旋转画布，导致图谱内节点的点击事件触发位置都错乱了，现在G6有旋转画布的api吗？项目有个横屏查看的需求

### ISSUE THREAD

**Issue by d623141153** [antvis/G6#1907]
- **G6 Version**: 最新版本
- **Platform**: ios 和 android
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by d623141153** [comment]
使用 renderer: 'svg' 渲染是好的

**Comment by Yanyan-Wang** [comment]
我理解横屏查看应该是直接页面横屏吧，不需要把画布横屏吧？

你现在是怎么旋转画布的，可以给个在线复现 demo

**Comment by d623141153** [comment]
> 我理解横屏查看应该是直接页面横屏吧，不需要把画布横屏吧？
> 
> 你现在是怎么旋转画布的，可以给个在线复现 demo

不是跟随页面横屏的，是通过transform的rotate，再改变画布的width和height，来达到横屏的效果
但旋转后，canvas渲染的图谱，节点的点击功能全部失效，用svg渲染是正常的

**Comment by Yanyan-Wang** [comment]
在官网任意 demo 最后加上以下代码没有复现：
```
graph.get('group').rotate(Math.PI / 2);
graph.moveTo(0, 0)
```

例如在这个 demo 后面增加上面两行代码：https://g6.antv.vision/zh/examples/tree/compactBox

可以写个在线 demo 看下
