### ISSUE TITLE
新插件ToolBar能在原来的基础上添加自定义的方法吗？

### ISSUE THREAD

**Issue by 1193538012** [antvis/G6#1908]
- **G6 Version**:3.6.0
- **Platform**:windows
- **Mini Showcase(like screenshots)**:
- **CodePen Link**: https://codesandbox.io/s/happy-keldysh-354ul

https://g6.antv.vision/zh/examples/tool/toolbar#toolbar
您好，TollBar工具栏有两个问题：
1.能在默认工具栏的事件上调用自己的方法吗？
![image](https://user-images.githubusercontent.com/42637805/89865071-9b6ca500-dbdf-11ea-80c6-849d6c66de1f.png)
上边两种方法点击两次才能触发，下边四个方法调用直接报错了。
2.能在默认的工具栏上再加上自定义的按钮吗？

https://codesandbox.io/s/suspicious-dan-vje9z
3.自带的撤销和回退，什么条件下能触发撤销呢？触发的条件能自己控制吗？比图拖动节点不触发，只有新增或者删除节点才触发。          我这种新增的连线信息就撤销不回去.

**Comment by lingengbiao** [comment]
`const toolbar = new G6.ToolBar({
        container: toolBarDom,
        className: 'toolbar-inner',
        getContent: () => {
          return `
                  <ul>
                    <li code='add'>增加节点</li>
                    <li code='undo'>撤销</li>
                    <li code='redo'>回退</li>

                    <li code='zoomOut'>放大</li>
                    <li code='zoomIn'>缩小</li>
                    <li code='realZoom'>实际大小</li>
                    <li code='autoZoom'>自动大小</li>
                  </ul>
                `
        },
        handleClick: (code, graph) => {
          switch (code) {
            case 'add':
              graph.addItem('node', {
                id: 'node5',
                label: 'node5',
                x: 300,
                y: 150,
              })
              break
            case 'undo':
              toolbar.undo()
              break
            case 'redo':
              toolbar.redo()
              break
            default:
              toolbar.handleDefaultOperator(code, graph)
          }
        }
      });`

**Comment by liuz666** [comment]
> toolbar.handleDefaultOperator(code, graph)

报错提示没有 toolbar.handleDefaultOperator(code, graph)这个方法。

**Comment by Yanyan-Wang** [comment]
> > toolbar.handleDefaultOperator(code, graph)
> 
> 报错提示没有 toolbar.handleDefaultOperator(code, graph)这个方法。

这个是 private 方法，handleClick 里面调用自己的方法用 this.xxx 应该就可以
