### ISSUE TITLE
Mouseover Event 导致的性能问题

### ISSUE THREAD

**Issue by zuiidea** [antvis/G6#1909]
鼠标在点边移动时，导致内存跑满，性能直线下降

**复现例子**：
官网示例，https://g6.antv.vision/zh/examples/interaction/highlight#activateRelations

**效果演示**：
![image](https://user-images.githubusercontent.com/16070518/89892131-ca4b4100-dc08-11ea-9293-4a04e56985c1.png)

**Comment by Yanyan-Wang** [comment]
升级到 3.6.1-beta 试一下

**Comment by zuiidea** [comment]
有一些的效果
