### ISSUE TITLE
自定义节点继承内置节点（非single-node）时，定义options报错

### ISSUE THREAD

**Issue by wqcstrong** [antvis/G6#1910]
- **G6 Version**: 3.6.0
- **Platform**: chrome 84.0.4147.105
- **Mini Showcase(like screenshots)**: 
    - 问题排查
        - 自定义节点方法的第三个参数指定了内置节点类型如果是 `rect` ( 或者其他内置节点类型，除了single-node )、并且第二个参数中包含值为空对象的options属性时，g6内部会执行 `rect.drawLinkPoints`，由于传递的对象包含了值为空对象的 `options` 属性，覆盖了内部的 `rect` 的 `options`，导致 `rect.drawLinkPoints` 函数在执行 `this.getOptions(cfg).linkPoints` 返回undefined，进而导致后续代码报错。个人理解 `linkPoints` 属性为可选项，故建议优化。
- **CodePen Link**: [codepen.io](https://codepen.io/WQC/pen/BaKopmo?editors=1011)

**Comment by baizn** [comment]
下个版本修复，详见 https://github.com/antvis/G6/pull/1928

**Comment by baizn** [comment]
升级到 3.7可以.0
