### ISSUE TITLE
自定义删除行为下click-select模式卸载报错

### ISSUE THREAD

**Issue by yehuozhili** [antvis/G6#1918]
复现地址：https://codesandbox.io/s/elastic-jennings-4oz35?file=/src/App.tsx

点击删除模式，然后随便删除个节点就会出现。

大概看了下，是click-select模式卸载问题，拿到了item后那个item的cfg是空，destroy是true，然后取type会找cfg，就直接报错。

去掉click-select模式不会报错。

或许可能是我删除方式不对？

**Comment by baizn** [comment]
mode为del时是不需要加 click-select 这个 Behavior 的。
另外 click-select 这个里面处理 node:click 漏掉了节点已经被 destroy 的情况，下个版本修复。
