### ISSUE TITLE
hi, 想问一下，官方有考虑bpmn的扩展么

### ISSUE THREAD

**Issue by hjdshu** [antvis/G6#1919]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
这个我理解是一种应用场景，不会内置在 G6 中。G6 提供基础的图可视化功能，用户可以使用各种的节点类型、边类型、布局方式、combo 来实现一个 bpmn 图。
