### ISSUE TITLE
fix: menu plugin with clickHandler problem; 版本3.6.1中右击菜单handleMenuClick仍有bug

### ISSUE THREAD

**Issue by LincolnPack** [antvis/G6#1921]
fix: menu plugin with clickHandler problem; 
版本3.6.1中右击菜单handleMenuClick仍有bug；

操作：多次在同一个节点右击，改变menu菜单位置
现象：此时点击菜单项，触发handleMenuClick回调（仍然会多次触发此回调）

分析：可能出现这个bug 的原因时因为多次右击节点，没有清除上一次的事件绑定。造成事件多次绑定 。

**Comment by LincolnPack** [comment]
应该在每次展示menu时，清除之前绑定的事件。

**Comment by xinghalo** [comment]
3.6.2这个问题还没修复吧？目前有什么办法可以解决吗
