### ISSUE TITLE
3.61版本Menu插件，菜单项点击回调多次触发

### ISSUE THREAD

**Issue by Icemanzzt** [antvis/G6#1922]
对着官网的例子来写，出现以下问题：
1.多次右键点击打开Menu，点击菜单项，触发多次回调。
2.单次点击打开Menu，点击菜单项，Menu关闭后，菜单项的点击事件移除失败。再次打开Menu点击菜单项，又会触发多次回调。

可能原因：
1.每次点击右键，菜单项点击事件被重复监听。
2.Menu关闭后，移除事件监听失败。

**Comment by baizn** [comment]
下个版本修复 https://github.com/antvis/G6/pull/1923

**Comment by baizn** [comment]
同 https://github.com/antvis/G6/issues/1921， 这个先关闭了
