### ISSUE TITLE
自定义节点更新label后，画布特别卡顿，整个画布崩溃

### ISSUE THREAD

**Issue by abmayTop** [antvis/G6#1925]
item.update({})/this.graph.updateItem('node', {})
使用这个两个尝试改变自定义节点的label后， 新建出来的节点会消失掉，然后出现画面错位，等一些列问题

- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by baizn** [comment]
麻烦提供一个可复现的在线 demo

**Comment by abmayTop** [comment]
demo比较困难 我可以详细描述一下么？
首先这个时一个vue项目，如果我点击编辑修改了某个对象的label，调用的item.update()/this.graph.updateItem这两个方法其中一个。
![image](https://user-images.githubusercontent.com/52235128/90587603-5a424980-e20c-11ea-8929-4d01a7359d62.png)
这个时候表现依旧正常，但是如果我点击新建，再次新建一个demo之后，页面就会卡顿，包括对象消失，画面崩溃
![image](https://user-images.githubusercontent.com/52235128/90588082-6084f580-e20d-11ea-92ea-3b87a73ea705.png)

这部分的代码是这样子的
```            this.graph.on('node:click', event => {
                const { item, target } = event;
                const targetType = target.get('type');
                const name = target.get('name');

                let mode = this.graph.getCurrentMode();

                if (targetType === 'text') {
                    if (name === 'add-item') {
                        // this.$refs.pickout.addRelate();
                        this.graph.addItem('node', { id: uuid(), label: '静态demo', img: '' });
                    } else if (name === 'edit-item') {
                        // this.$refs.pickout.editRelate(item._cfg.id);
                        // this.$refs.pickout.editInfos(item._cfg.id);
                        this.editNode = item;
                        item.update({ label: 'jjj' });
                        // this.graph.updateItem(this.graph.findById(item._cfg.id), { label: 'bello' });
                    }
}```

**Comment by Yanyan-Wang** [comment]
使用的哪个版本的 G6？ 更新到最新版本或者 3.6.1-beta 看一下

**Comment by abmayTop** [comment]
已经更新 但是依旧不能解决这个问题

**Comment by Yanyan-Wang** [comment]
尝试以下方案：

- 确定 node_modules 里面的 G6 版本是 3.6.1-beta
- 必须确定所有节点和边的 id 都是唯一的 string
- 给 this.graph.addItem('node', { id: uuid(), label: '静态demo', img: '' }) 第二个参数加上 x，y
- 确定自定义节点的 draw 方法中不存在非法的值
- 以上方法都不行的话，尝试 graph.get('canvas').set('localRefresh', false)，在 graph.render() 之前调用

**Comment by zuiidea** [comment]
这个问题跟我遇到的一个问题有点相似：
当设置 `fitView` 为 `true` 时出现渲染花屏，缩放失效，取消 `fitView` 参数则正常

**效果演示：**
![屏幕录制-2020-08-25-下午4 31 32](https://user-images.githubusercontent.com/16070518/91152259-55d8cd80-e6f1-11ea-9379-9ca64a37ed82.gif)


**在线代码演示：**
[![Edit React G6 Multi-Graph Fitview](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-g6-multi-graph-fitview-6h3e4?fontsize=14&hidenavigation=1&theme=dark)

**Comment by Yanyan-Wang** [comment]
> 这个问题跟我遇到的一个问题有点相似：
> 当设置 `fitView` 为 `true` 时出现渲染花屏，缩放失效，取消 `fitView` 参数则正常

force 用 fitView 没啥用，因为它是不断变化的，而 fitView 只是在第一次渲染的时候进行了缩放。可以在布局完成之后（监听 graph.on('afterlayout', e => {});）调用 graph.fitView，但是这样会导致布局完成时的一次闪烁。更好的办法是在每次迭代就约束节点位置不超过一个范围，demo： https://g6.antv.vision/zh/examples/net/forceDirected#forceConstrainedInRect

**Comment by zaiMoe** [comment]
遇到过类似的问题，在调用`updateItem`之前，节点带有`hover/selected`状态（改变stroke属性值），接着调用，然后拖拽一个新的节点到画布上，就会出现描边不见的情况。然后拖拽这个锚点，画布就异常了。初步定位到，新拖拽进来的节点，stroke属性好像缺失了。规避方法是在`updateItem`之前先`clearItemStates`一下
