### ISSUE TITLE
节点的层级问题？

### ISSUE THREAD

**Issue by wrh4585** [antvis/G6#1927]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

这样的场景，在画布中有若干节点，节点为动态添加的，新添加的节点总是在最上层（假如有五个节点依次添加，则最早添加的为第一层，最后添加的为第五层）。选中某个节点后，可以将其下移一层或者上移一层。但是调用toFront()/toBack()方法，是将选中的节点直接置为最顶层或者最底层。有什么方法可以实现节点层级每次上移或者只下移一层？
G6目前的toFront()/toBack()方法是只能将节点置于最底或最顶层么？

**Comment by Yanyan-Wang** [comment]
> G6目前的toFront()/toBack()方法是只能将节点置于最底或最顶层么？

是的，目前没有细致控制节点到那一层到 API。但也可以通过底层方法实现，

```
    const nodeContainerGroup = graph.get('nodeGroup'); // 获得存储节点图形分组的组
    const nodeGroups = nodeContainerGroup.get('children'); // 获得所有节点的图形分组
    nodeGroups[0].set('zIndex', 10); // 把第 0 个节点的图形分组 zIndex 设置为 10
    nodeContainerGroup.sort() // 排序
```


但是 sort 方法效率比 toFront()/toBack() 低

**Comment by gaoxs1985** [comment]
动态添加节点可以直接添加到最底层吗？ @Yanyan-Wang
