### ISSUE TITLE
引入了iconfont之后通过downloadFullImage下载下来的svg的icon显示异常(为一个小方块)

### ISSUE THREAD

**Issue by jqxismygit** [antvis/G6#1935]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

如题

**Comment by Yanyan-Wang** [comment]
请提供在线复现 demo

**Comment by jqxismygit** [comment]
我这边codepen比较慢，提供一个最小可复现仓库: https://github.com/jqxismygit/g6-download-bug

**Comment by Yanyan-Wang** [comment]
应该是需要先将 iconfont 转换为 svg 才可以正常导出，否则其实在 svg 文件中是 <text> 标签，导出后会被认为是乱码

https://github.com/antvis/G6/blob/6b1d62c5a92b66c34e72fcfded896a53d89914f2/src/graph/graph.ts#L2270

https://www.sarasoueidan.com/blog/icon-fonts-to-svg/

**Comment by jqxismygit** [comment]
谢谢，我试试
