### ISSUE TITLE
graph中的属性不应该为private

### ISSUE THREAD

**Issue by yehuozhili** [antvis/G6#1940]
https://github.com/antvis/G6/blob/master/src/graph/graph.ts#L99

正常取是可以从graph上取到cfg的，但是使用ts时会提示cfg为priviate只能在类上取到。

需要取cfg的场景是这样：从后端获取数据，然后用户修改图像后上传数据，此时好像没什么比较好的api去取数据，使用cfg可以拿到最新的。  

也许我api用的不对？或者这个情况不应该这么操作？

**Comment by Yanyan-Wang** [comment]
graph.save() 可以拿到当前最新数据
