### ISSUE TITLE
tooltip在canvas缩小的时候，位置出现很大的改变，有什么办法根据鼠标位置去显示tooltip的位置吗

### ISSUE THREAD

**Issue by hxj123** [antvis/G6#1941]
如题，有人遇到过这个问题吗

**Comment by Yanyan-Wang** [comment]
你用的是 tooltip 插件吗，先用 tooltip behavior 代替 https://g6.antv.vision/zh/docs/manual/middle/states/defaultBehavior/#tooltip

下个小版本修复

**Comment by hxj123** [comment]
> 你用的是 tooltip 插件吗，先用 tooltip behavior 代替 https://g6.antv.vision/zh/docs/manual/middle/states/defaultBehavior/#tooltip
> 
> 下个小版本修复

这个问题同样在移动canvas时存在，你们也可以注意一下。我之前有试过tooltip behavior，但是这里也有些问题，offset设置鼠标偏移量后，这个tooltip的位置还是没办法固定，有时离鼠标非常近靠在一起，有时又有点远，按道理来说，应该是固定与鼠标之间的距离才对

**Comment by Yanyan-Wang** [comment]
着急的话可以自己写一个 DOM ，监听鼠标事件控制位置和显示隐藏。挂在方式参考 https://www.yuque.com/antv/g6-blog/gp2dxk#lDY8R

**Comment by Yanyan-Wang** [comment]
v3.6.2 已修复
