### ISSUE TITLE
有办法实现点击节点显示linkpoints，失去焦点时隐藏linkpoints吗？

### ISSUE THREAD

**Issue by hxj123** [antvis/G6#1943]
如题，有人写过类似的需求吗？试过attr设置属性，但是不生效

**Comment by Yanyan-Wang** [comment]
如果是内置节点，在 node:click / canvas:click 监听里面更新节点配置就可以了
```
graph.updateItem(node, {
  linkPoints: {
    top: true, // false 将其隐藏
  }
});
```

如果是自定义事件，监听点击事件，拿到节点上图形分组，在组中找到对应图形，控制显示隐藏

graph.on('node:click', e=> {
  const node = e.item;
  const group = node.getContainer();
  const shapes = group.get('children');
  shapes.forEach(shape => {
    if (shape.get('name') === .....) { // 使用 name 判断是否是 linPoints 的图形
      shape.show();
    }
  })
});

**Comment by hxj123** [comment]
> 如果是内置节点，在 node:click / canvas:click 监听里面更新节点配置就可以了
> 
> ```
> graph.updateItem(node, {
>   linkPoints: {
>     top: true, // false 将其隐藏
>   }
> });
> ```
> 
> 如果是自定义事件，监听点击事件，拿到节点上图形分组，在组中找到对应图形，控制显示隐藏
> 
> graph.on('node:click', e=> {
> const node = e.item;
> const group = node.getContainer();
> const shapes = group.get('children');
> shapes.forEach(shape => {
> if (shape.get('name') === .....) { // 使用 name 判断是否是 linPoints 的图形
> shape.show();
> }
> })
> });

感谢回答，使用updateItem会出现图形闪烁的效果，请问有办法避免吗

**Comment by Yanyan-Wang** [comment]
可以写个在线 demo 看下
