### ISSUE TITLE
changeSize

### ISSUE THREAD

**Issue by shichuanpo** [antvis/G6#1944]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
What is the problem?

**Comment by Yanyan-Wang** [comment]
API about graph.changeSize: https://g6.antv.vision/en/docs/api/Graph/#changesizewidth-height

**Comment by Yanyan-Wang** [comment]
好的呢
