### ISSUE TITLE
Combo size does not update after combo.removeChild()

### ISSUE THREAD

**Issue by michaelalemu** [antvis/G6#1945]
- **G6 Version**: 3.6.1
- **Platform**:
- **Mini Showcase(like screenshots)**:
<img width="270" alt="Bildschirmfoto 2020-08-19 um 23 55 16" src="https://user-images.githubusercontent.com/6313162/90693687-8d6df280-e277-11ea-8e06-6cac5191f7ec.png">
<img width="318" alt="Bildschirmfoto 2020-08-19 um 23 55 31" src="https://user-images.githubusercontent.com/6313162/90693693-8fd04c80-e277-11ea-859f-fae3c8def498.png">

- **CodePen Link**: https://codesandbox.io/s/gifted-noether-f0sg0

Hello,

after calling `combo.removeChild()` the size of combo is not updated. I have already tried `graph.updateCombos()`, `graph.refresh()`, `graph.refreshPositions()`, `graph.paint()`. What could I be doing wrong?

In order to reproduce, visit CodePen link, left-click on a node, then move the combo to see that the node has been removed from the combo (also check the console), but it will not render accordingly.

Expected outcome: Combo size should update

<img width="187" alt="Bildschirmfoto 2020-08-20 um 00 16 22" src="https://user-images.githubusercontent.com/6313162/90695251-64029600-e27a-11ea-8bc2-5aee2a4d650f.png">

It works as expected when I call `graph.data()` followed by `graph.render()` (right-click on node1 to see). However, this does not apply to my use case, where I work with many nodes and the view is reset each time.

**Comment by Yanyan-Wang** [comment]
Only the behaviors of the graph will lead to size updating for combos. Try `graph.updateComboTree(node)` instead.

https://g6.antv.vision/en/docs/api/Graph/#updatecombotreeitem-parentid
