### ISSUE TITLE
Degree 布局切换到其他布局时，边的位置无法完全重置

### ISSUE THREAD

**Issue by zuiidea** [antvis/G6#1950]
**问题**

`Degree` 布局切换到其他布局时，边的位置无法完全重置，导致显示怪异，其他布局相互切换时则没这问题，如`Force`到`concentric`

**效果显示**

![屏幕录制-2020-08-20-下午5 32 03](https://user-images.githubusercontent.com/16070518/90755004-3adf1580-e30d-11ea-8c04-7b8a47c046cd.gif)

**在线Demo**

[![Edit React G6 Dagre Layout Change Other Layout](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-g6-dagre-layout-change-other-layout-5j4vd?fontsize=14&hidenavigation=1&theme=dark)

**其他**

我本地使用`npm run demos` 复写 Demo 排查问题时，本地的`storybook`保存重载时，页面会切换到第一个路由，我打开方式不对？如果要参与贡献，有引导的文档吗？

**Comment by Yanyan-Wang** [comment]
从 dagre 切换到其他布局的时候，把 edges 数据里面的 controlPoints 删掉一下。或者配置 dagre 布局的配置项 controlPoints: false。当 controlPoints: true 时，布局会计算 controlPoints 并写入到数据中，导致在其他布局时，之前计算到 controlPoints 还在数据中，边就会根据这个 controlPoints 来计算路径。
