### ISSUE TITLE
Maximum call stack size exceeded     at Object.e.getMergedRegion

### ISSUE THREAD

**Issue by tenderjk** [antvis/G6#1953]
当数据源nodes个数超过一万四接近一万五左右会出现Maximum call stack size exceeded     at Object.e.getMergedRegion报错

**Comment by Yanyan-Wang** [comment]
这个例子有 55000 个节点，可以对照一下：https://g6.antv.vision/zh/examples/performance/perf#moreData
- 首先排查一下数据格式是否正确，节点有唯一的 string id，边的 source 和 target 都存在于节点中；
- 是否使用了布局算法？大规模的布局目前建议不要在前端计算；
- 大规模图上，尽量减少图元，也就是说，一个节点/边的图形组成尽量不要复杂。

**Comment by tenderjk** [comment]
数据格式正确
没有使用布局算法
一个节点由差不多八个图形+一个文本组成
我想问题可能是出在节点组成上了
当我想要全部展示这些数据节点时，有什么方案可以解决，是不是需要根据画布坐标进行数据源的切换？

**Comment by Yanyan-Wang** [comment]
建议在大规模的图上，用最简单的组成来表达一个节点，或者在自定义节点中，把不重要的图形先隐藏（shape.hide()），在详细看一个节点，比如说放大后，再显示这一节点的所有图形(每个图形 shape.show())

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
