### ISSUE TITLE
Cannot find module '@babel/types' or its corresponding type declarations.

### ISSUE THREAD

**Issue by fengzi2016** [antvis/G6#1958]
- **G6 Version**: 3.6.1-beta
- **Platform**: macOS
- **Mini Showcase(like screenshots)**:  npm start error

- **CodePen Link**: 

没改代码，npm run start报错 Cannot find module '@babel/types' or its corresponding type declarations.

**Comment by Yanyan-Wang** [comment]
yarn install 试试
