### ISSUE TITLE
autopaint设置为false，additem后不调用paint仍旧会绘制

### ISSUE THREAD

**Issue by TLYTLX** [antvis/G6#1961]
- **G6 Version**: 3.5.12 / 3.6.x
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
3.5 以后采用自动局部渲染机制，通过 addItem, updateItem, removeItem 等 API 对 Graph 上的元素进行更新都将会进行增量式地局部更新。

**Comment by TLYTLX** [comment]
> 3.5 以后采用自动局部渲染机制，通过 addItem, updateItem, removeItem 等 API 对 Graph 上的元素进行更新都将会进行增量式地局部更新。

那想问下我如何监听到页面渲染完成，再对某些节点tofront呢，有暴露哪个事件吗

**Comment by Yanyan-Wang** [comment]
请问大量节点 addItem 的话，为什么不直接用 graph.data(data) graph.render() 呢？render 有 afterrender 时机事件。该问题一起合并到 #1964  吧
