### ISSUE TITLE
节点hover状态切换 setState('hover', false)时 iamge会一闪

### ISSUE THREAD

**Issue by byMoya** [antvis/G6#1963]
- **G6 Version**: 3.6.2
- **Platform**: window/chrome
- **Mini Showcase(like screenshots)**:
- **CodePen Link**: https://g6.antv.vision/zh/examples/tree/customItemTree

**Comment by byMoya** [comment]
升级3.6.2出现这问题 之前3.5.7没有

**Comment by baizn** [comment]
下个版本修复，详见 https://github.com/antvis/G6/pull/1968

**Comment by baizn** [comment]
升级到 3.7.0
