### ISSUE TITLE
在additem等api是默认局部自动渲染时，是否有全部item绘制完emit事件出来呢，目前是想视图全部绘制完以后再对某些节点tofront

### ISSUE THREAD

**Issue by TLYTLX** [antvis/G6#1964]
- **G6 Version**: 3.5.12
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
全部调用完成后调用 node.toFront 不能满足需求吗？

加入每个节点都会有 afteradditem 时机事件被触发。 https://g6.antv.vision/zh/docs/api/Event#afteradditem

**Comment by TLYTLX** [comment]
不能，因为有部分数据先add node，再对该部分数据updatelayout；这个时候渲染了部分数据了，然后再进行子图布局，子图布局中add包括部分node和全部edge，完了以后想对最开始的部分node tofront，但是由于edge是在子图中添加，所以edge依然可能会在node上面的可能性

**Comment by Yanyan-Wang** [comment]
是为了解决边在节点上面的问题吗？

**Comment by TLYTLX** [comment]
是的  想要节点在边上面

**Comment by TLYTLX** [comment]
> 是为了解决边在节点上面的问题吗？

是的 想要节点在边上面

**Comment by TLYTLX** [comment]
> 是为了解决边在节点上面的问题吗？

我看源码 局部渲染是settimeout 我把front写在settimeout里面 这样可以  有更好的解决办法吗

**Comment by Yanyan-Wang** [comment]
你在实例化图的时候把 groupByType 设置为 false 了吗？是因为有 combo？

**Comment by TLYTLX** [comment]
> 你在实例化图的时候把 groupByType 设置为 false 了吗？是因为有 combo？

并没有combo，纯node和edge，分组用node实现的（因为combo x y位置以及size不太好自由控制）代码基本实现如下：
1. addItem('node', {})等n个节点
2. updateLayout 这n个节点
3. 对剩下的数据算好位置后，additem m个节点，x条边，进行子图布局
4. 最后对最开始添加的n个节点和后面加的m个节点 tofront， m个节点效果正常，n个节点存在在线下面的情况

**Comment by Yanyan-Wang** [comment]
那就把 groupByType 设置为 true，这样节点永远都会在边的上面

**Comment by Yanyan-Wang** [comment]
那实例化图时不要设置 groupByTypes 或者把它设置为 true。这样节点全部会在边的上面

**Comment by TLYTLX** [comment]
> 那实例化图时不要设置 groupByTypes 或者把它设置为 true。这样节点全部会在边的上面

这样子我用node仿的group也会在上面哈哈哈  展开的node（作用是group）想要在下面  我这个要求是不是很过分

**Comment by Yanyan-Wang** [comment]
其实我不是很能明白你的场景为什么找到最开始添加的 n 个节点 toFront 不可以满足，是否能够提供一个复现在线 demo，我看一下解决方案。

**Comment by TLYTLX** [comment]
> 其实我不是很能明白你的场景为什么找到最开始添加的 n 个节点 toFront 不可以满足，是否能够提供一个复现在线 demo，我看一下解决方案。

涉及的代码有点多 我晚点来搞下，或者你先看看我上面说的代码基本实现，看看能不能明白我的问题？

**Comment by Yanyan-Wang** [comment]
不是很明白，还是提供一下在线 demo 吧

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
