### ISSUE TITLE
采用x,y坐标固定布局，进行约600节点渲染延迟为5s，能否进一步减少渲染时间

### ISSUE THREAD

**Issue by ipangkang** [antvis/G6#1969]
- **G6 Version**:3.6.0
- **Platform**: macos catalina 10.15
- **Mini Showcase(like screenshots)**: 
- **CodePen Link**:

Hi,

针对大规模（1000+）数据，进行node:click或drag等交互行为时，出现6秒以上延迟。尝试过setAutoPaint(false);graph.paint()的方式，延迟降不下去。 是否是因为在交互行为中有setItemState或addItem等在3.6版本后会进行自动重绘的方法？如果在现版本上取消自动重绘功能 或是  降低版本后能否设置取消自动重绘并降低延迟？ 是否存在除renderByGroup以外的局部渲染方法，由于仅存在个别item进行位置样式更新，changeData()效果应该不太好。

Thank you~

**Comment by ipangkang** [comment]
我看到node.setState 及 clearState等方法，在功能上与graph.setItemState or clearItemState 类似， 请问这两种方法在渲染速度上哪一种更占优呢？谢谢！！

**Comment by Yanyan-Wang** [comment]
首先，升级到 3.6.2 性能更佳。

不论是否是 3.6.2，600 个节点不应该会出现这么长时间的延迟，看下这个 demo（7167 个节点，5421 条边。每个节点带有一个文本。总计 19755 个图元），hover 时有状态和样式变化 https://g6.antv.vision/zh/examples/performance/perf#eva

渲染的效率主要和画布上图元数量有关，在超大规模情况下，尽量减少每个节点的图元组成。另外，文本是最消耗性能的一种图元。

在 3.6.2 中，进阶提高拾取效率可以开启 quickHit（将不拾取文本）：
```
graph.get('canvas').set('quickHit', true) 
```

**Comment by ipangkang** [comment]
Hi,  

感谢您的帮助，在查看了[https://g6.antv.vision/zh/examples/performance/perf#eva](url)后，注意到其实该画布大小仅在1000以内。我对我的代码进行了测试，发现是我的画布设置的过大了，height 在 20000左右， width在 6000左右。通过调整画布大小，使其稳定在height 8000以下。在此情况下，我发现渲染速度大幅提高，到了几乎能够即时响应的地步。

但是由于在我代码里，画布随消息数量增加会变大，因此在个别情况下，依然会存在1-2秒的响应延迟。请问能否固定画布大小，通过graph.zoomTo()设置不同zoomrate，使得不管消息数量的多少，在视图范围内的每个节点的大小能够保持一致呢。

Thank you~

**Comment by Yanyan-Wang** [comment]
graph.zoom 和 graph.zoomTo 可以想像成把 canvas 当作整体图片在缩放。如果你希望节点大小不被缩放，那其实就是控制布局范围啊，既然你的 x y 已经存在，那就只需要把所有节点的 x y 归一化到画布范围即可。graph 的 width height 和它的 DOM 容器大小一致就好，不会出现 8000、 20000 的 DOM 容器的吧。
