### ISSUE TITLE
tree.node().label 不能单独修改文字颜色吗？

### ISSUE THREAD

**Issue by huyawei** [antvis/g6#197]
```js
            tree.node()
                .label(function (obj) {
                    return {
                        text: obj.label,
                        fill: '#ff0000'
                    }
                })
```
net 似乎没问题

**Comment by woshiguabi** [comment]
吐槽下这个问题.
翻了下源码,当源数据obj中有label属性时会覆盖掉nodeMapper中的label channel,也就是在源数据中文本字段名不能使用label,换成其他名字后正常.
是否应该覆盖这个问题没有正确答案,毕竟会有需要源数据覆盖掉mapper的场景,但我觉得应该在文档中写清楚,以免造成困扰

**Comment by TomHuangCN** [comment]
感谢吐槽！文档会持续改进～ （也欢迎给我们的文档（https://github.com/antvis/site）提 PR 哈） @woshiguabi wo
