### ISSUE TITLE
node的mousedown按下会转换成drag事件，无法监听mousemove和mouseup事件

### ISSUE THREAD

**Issue by hxj123** [antvis/G6#1971]
可以禁用drag事件吗，现在有个需求是在node上鼠标按下，然后移动出现连线，到另一个node上松开，实现两个node之间的连线

**Comment by Yanyan-Wang** [comment]
这不就是 drag 吗，用 dragstart drag dragend 监听不行么？

另外，3.6.2 有内置 behavior 了：https://g6.antv.vision/zh/examples/interaction/createEdge#drag

**Comment by hxj123** [comment]
> 这不就是 drag 吗，用 dragstart drag dragend 监听不行么？
> 
> 另外，3.6.2 有内置 behavior 了：https://g6.antv.vision/zh/examples/interaction/createEdge#drag

dragend的时候拿不到目标节点

**Comment by hxj123** [comment]
> > 这不就是 drag 吗，用 dragstart drag dragend 监听不行么？
> > 另外，3.6.2 有内置 behavior 了：https://g6.antv.vision/zh/examples/interaction/createEdge#drag
> 
> dragend的时候拿不到目标节点

感谢回复

**Comment by Yanyan-Wang** [comment]
> > 这不就是 drag 吗，用 dragstart drag dragend 监听不行么？
> > 另外，3.6.2 有内置 behavior 了：https://g6.antv.vision/zh/examples/interaction/createEdge#drag
> 
> dragend的时候拿不到目标节点

目标节点是 node:drop 监听到的
