### ISSUE TITLE
页面带滚动条时，tooltip位置仍是滚动之前的位置，没有展示在节点旁边

### ISSUE THREAD

**Issue by Lollipopls** [antvis/G6#1972]
G6 Version:3.6.2
![image](https://user-images.githubusercontent.com/28340418/91120193-ac311680-e6c7-11ea-8930-7bd46dae256e.png)

**Comment by Yanyan-Wang** [comment]
请提供一个在线 demo

**Comment by Yanyan-Wang** [comment]
建议 graph 大小不要超过其 DOM 容器大小，通过 drag-canvas 或者这种自定义交互来平移画布（类似滚动条的交互）https://g6.antv.vision/zh/examples/interaction/customBehavior

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
