### ISSUE TITLE
firefox 浏览器下自定义节点通过group.addShape添加image图形后，节点被白色层覆盖，点击画布拖拽后才显示正常

### ISSUE THREAD

**Issue by asevenm** [antvis/G6#1974]
- **G6 Version**: 3.5.9
- **Platform**: firefox 79.0
- **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/22423693/91130361-1fde1e00-e6de-11ea-83a3-887887360dcb.png)

**Comment by Yanyan-Wang** [comment]
升级到 3.7.0 试试。不行的话请提供一个在线复现 demo

**Comment by asevenm** [comment]
> 升级到 3.7.0 试试。不行的话请提供一个在线复现 demo

https://codesandbox.io/s/peaceful-christian-qdtvm 升级到3.7.0仍然还是有这个问题

**Comment by asevenm** [comment]
> > 升级到 3.7.0 试试。不行的话请提供一个在线复现 demo
> 
> https://codesandbox.io/s/peaceful-christian-qdtvm 升级到3.7.0仍然还是有这个问题

windows 上的Firefox有这个问题

**Comment by Yanyan-Wang** [comment]
是右上角这个小房子的图片吗？我在 windows firefox 下是可以显示的呢

![image](https://user-images.githubusercontent.com/29593318/91246536-a9472c00-e782-11ea-97c0-394bdb812258.png)

**Comment by asevenm** [comment]
> 是右上角这个小房子的图片吗？我在 windows firefox 下是可以显示的呢
> 
> ![image](https://user-images.githubusercontent.com/29593318/91246536-a9472c00-e782-11ea-97c0-394bdb812258.png)
默认是显示这样的（我在好几个windows上都是这样，Firefox是最新版本）
![image](https://user-images.githubusercontent.com/22423693/91247052-f11a8300-e783-11ea-8ece-e6d70a84ccf0.png)
拖动画布之后能正常显示
![image](https://user-images.githubusercontent.com/22423693/91247121-1effc780-e784-11ea-8945-ff283e1b52b0.png)

**Comment by lmsccc** [comment]
似乎在firefox下阴影的渲染有问题 @Yanyan-Wang

**Comment by asevenm** [comment]
> 我们项目也遇到了这个问题，我看你的节点应该也使用到了阴影，将阴影去掉后问题解决 @asevenm

好的，我 试试

**Comment by asevenm** [comment]
> 似乎在firefox下阴影的渲染有问题 @Yanyan-Wang

我这里的表现是添加了image图形，并且使用了阴影会有这个问题

**Comment by Yanyan-Wang** [comment]
在 render 后执行下面代码看看是否能够解决呢？

```
    setTimeout(() => {
      graph.paint()
    }, 16)
```

**Comment by asevenm** [comment]
> 在 render 后执行下面代码看看是否能够解决呢？
> 
> ```
>     setTimeout(() => {
>       graph.paint()
>     }, 16)
> ```

尝试过了，没起作用

**Comment by jinyutao0818** [comment]
解决了么？我这边也遇到了这样的问题

**Comment by asevenm** [comment]
> 解决了么？我这边也遇到了这样的问题

暂时的解决方案就是在特定的浏览器上用border代替阴影效果
