### ISSUE TITLE
定义锚点箭头就不见了，而且polyline如何能是直角呢，实在找不到文档啦

### ISSUE THREAD

**Issue by Lollipopls** [antvis/G6#1977]
3.6.2版本
![image](https://user-images.githubusercontent.com/28340418/91146595-b106c200-e6e9-11ea-9549-42c3a039eab2.png)

**Comment by Yanyan-Wang** [comment]
> 定义锚点箭头就不见了

请提供在线复现 demo

> polyline如何能是直角

不设置 radius。 https://g6.antv.vision/zh/docs/manual/middle/elements/edges/polyline/#%E9%85%8D%E7%BD%AE%E9%A1%B9%E8%AF%B4%E6%98%8E

**Comment by Lollipopls** [comment]
是这种直角哈
![image](https://user-images.githubusercontent.com/28340418/91148633-84a07500-e6ec-11ea-89e1-8b551edb7656.png)

**Comment by Lollipopls** [comment]
目前只能是钝角

**Comment by Yanyan-Wang** [comment]
这种就不要使用 dagre 的自动 controlPoints，也就是说在配置 dagre 的时候，controlPoints: false。然后先看下自动计算的 polyline 弯折是否能满足要求。如果不行的话，自己根据两个端点的位置指定每条边 controlPoints 的位置，看这个情况你是需要每条边的 controlPoints 是 [{ x: sourceNode.x, y: targetNode.y }]，使用 graph.updateItem(edge, { controlPoints: ... }) 来更新 edge 即可。

**Comment by Lollipopls** [comment]
设置了锚点之后箭头就不见了呢

**Comment by Yanyan-Wang** [comment]
写在线 demo 看下

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
