### ISSUE TITLE
多个Force Graph同时渲染时，可能出现不符预期的不同效果

### ISSUE THREAD

**Issue by zuiidea** [antvis/G6#1978]
**场景：**
- 多个Force Graph同时渲染，若数据一致时，当Graph 1处于迭代计算时，调整 Graph 2位置，Graph 1位置会不符预期的同步Graph 2的位置。

**效果演示：**
![屏幕录制-2020-08-25-下午3 51 25 (1)](https://user-images.githubusercontent.com/16070518/91148833-e6f97580-e6ec-11ea-9db9-f36e1b7eb22f.gif)

**在线演示：**

[![Edit React G6 Multi-Graph sync](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-g6-multi-graph-sync-vohsn?fontsize=14&hidenavigation=1&theme=dark)

**Comment by Yanyan-Wang** [comment]
不要使用同一个数据的对象引用，若果要使用相同的数据，深拷贝一份数据再使用。因为布局是会把 x y 写入到源数据中的，如果两个图的源数据是同一个对象，就会互相影响了。
