### ISSUE TITLE
没有办法把画布上的元素导出为矢量图吗？

### ISSUE THREAD

**Issue by AngelDaShiXiong** [antvis/G6#1979]
downloadImage(name)只能导出为图片，并不能无限放大，而且只会导出当前屏幕上显示的元素，这点有点坑啊

**Comment by heyang1014** [comment]
+1,downloadfullimage下载下来太模糊了，节点多几个放大就看不清楚了，有没有什么办法设置下载的图片更加高清

**Comment by Yanyan-Wang** [comment]
downloadFullImage 了解一下
https://g6.antv.vision/zh/docs/api/Graph/#downloadfullimagename-type-imageconfig

实在不行的话，也可以拿到 graph 的画布 DOM，自己用 canvas 的 API 想办法导出。const canvas = graph.get('canvas').get('el')

graph 本身的渲染方式是 svg 时才能导出 svg。

**Comment by AngelDaShiXiong** [comment]
好的感谢
