### ISSUE TITLE
combo如何使用Dagre布局实现类似数据库排列

### ISSUE THREAD

**Issue by wanghansong** [antvis/G6#1982]
- **G6 Version**: 3.5.10
- **Platform**: mac
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

使用combo的Dagre布局时，combo内部的节点排列并不规则

想实现类似下面图这样的效果，不知道该怎么个思路

![图](https://user-images.githubusercontent.com/718799/88757880-14c2bd00-d135-11ea-8d32-ae260bc8d745.png)

**Comment by wanghansong** [comment]
我有个思路：将combo作为节点传入dagre库获取坐标轴，然后各个combo下的子元素以这个坐标轴为基准再进行坐标计算、渲染

**Comment by Yanyan-Wang** [comment]
dagre 目前支持根据 combo 信息对同层节点进行排序，demo：https://g6.antv.vision/zh/examples/net/dagreFlow#dagreCombo

有别的方式的话欢迎 PR。
