### ISSUE TITLE
layout布局支持指定某些节点在上面，某些节点在下面的功能吗？

### ISSUE THREAD

**Issue by zhensherlock** [antvis/G6#1983]
G6 Version: 3.6.1
Platform: mac
Mini Showcase(like screenshots):
CodePen Link:

layout布局支持指定某些节点在上面，某些节点在下面的功能吗？
![image](https://user-images.githubusercontent.com/3541162/91251064-2a0b2580-e78d-11ea-82ff-04f4fefa4eea.png)

**Comment by Yanyan-Wang** [comment]
树图布局 indented 和 mindmap 支持 getSide 配置项，可以根据节点数据返回 'left' 或 'right'，具体参考文档 https://g6.antv.vision/zh/docs/manual/middle/layout#mindmap

文档中没有提及的配置项的话就没有了。
