### ISSUE TITLE
canvas画布拖动的时候grid没有跟着一起动，有方法可以实现吗？

### ISSUE THREAD

**Issue by lmsccc** [antvis/G6#1984]

**Comment by Yanyan-Wang** [comment]
内置的 grid 是一个带有 background-image 的 div。目前 G6 没有排期做 grid 跟随画布拖动。可以考虑自己实现一个 DOM 放置在 canvas 后面。可以参考源码 https://github.com/antvis/G6/blob/master/src/plugins/grid/index.ts
