### ISSUE TITLE
getConnectedComponents 图中的连通分量方法，返回的数据格式不对

### ISSUE THREAD

**Issue by wsb260** [antvis/G6#1986]
- **G6 Version**: 3.6.2
- **Platform**:
- **Mini Showcase(like screenshots)**: 调用getConnectedComponents()方法后获取的连通图数据
  + 期望返回结果：[['A', 'B', 'C', 'D', 'E', 'F'], ['G', 'H']]
  + 实际返回值:[[e,e,e,e,e,e],[e,e]]
- **CodePen Link**:https://g6.antv.vision/zh/docs/api/Algorithm#getconnectedcomponents

**Comment by chenluli** [comment]
文档有误，返回的是节点实例不是节点 ID， #1989 订正。感谢反馈。
