### ISSUE TITLE
缩放之后清晰度可以调整么

### ISSUE THREAD

**Issue by Lollipopls** [antvis/G6#1990]
![image](https://user-images.githubusercontent.com/28340418/91311073-39b65880-e7e5-11ea-889f-6e426d732cff.png)

**Comment by Yanyan-Wang** [comment]
应该不会这样的，哪个版本 G6？提供一下在线复现 demo。issue 需要更多的信息，才能高效定位和解决问题。

**Comment by Lollipopls** [comment]
版本是：3.6.2

**Comment by Yanyan-Wang** [comment]
实例化图的时候设置一下 pixelRatio: 2 或者更高的数值试下，还不行的话需要提供一下在线 demo。

**Comment by Yanyan-Wang** [comment]
能够解决问题吗？

**Comment by Lollipopls** [comment]
好用啦  万分感谢！3.7版本也是需要设置之后才清楚

**Comment by Yanyan-Wang** [comment]
如果不设置 pixelRatio 按理说会自动获取屏幕像素比率的。
