### ISSUE TITLE
动态改变数据后 combo edge 的起始点有问题

### ISSUE THREAD

**Issue by Hugo-seth** [antvis/G6#1992]
- **G6 Version**: 3.7.0
- **Platform**:  windows 10
- **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/17878774/91381989-483f5700-e85b-11ea-84d0-1bd583b5e979.png)
- **CodePen Link**: https://codesandbox.io/s/interesting-dan-orwbs?file=/index.js

**Comment by Yanyan-Wang** [comment]
使用 combo 时，需要在实例化图时配置 groupByTypes: false，否则边的层级可能会高于 combo。

这里的「注意」有提及
https://g6.antv.vision/zh/docs/manual/middle/elements/combos/defaultCombo

**Comment by Hugo-seth** [comment]
CodePen Link: https://codesandbox.io/s/interesting-dan-orwbs?file=/index.js
设置  groupByTypes: false 后，问题依旧存在
 
![image](https://user-images.githubusercontent.com/17878774/91400735-bf341a00-e872-11ea-84f0-5f8c2c767623.png)

**Comment by Hugo-seth** [comment]
@Yanyan-Wang 麻烦再看一下，谢谢

> CodePen Link: https://codesandbox.io/s/interesting-dan-orwbs?file=/index.js
> 设置 groupByTypes: false 后，问题依旧存在
> 
> ![image](https://user-images.githubusercontent.com/17878774/91400735-bf341a00-e872-11ea-84f0-5f8c2c767623.png)
