### ISSUE TITLE
自定义节点，修改宽度后，edge被遮挡

### ISSUE THREAD

**Issue by xiaofengqqcom123** [antvis/G6#1993]
version：3.6.1
节点初始状态：
![image](https://user-images.githubusercontent.com/29247931/91394195-03bcb700-e86d-11ea-8f3c-f6ef23862910.png)
添加hover事件后，节点宽度修改：
![image](https://user-images.githubusercontent.com/29247931/91394275-16cf8700-e86d-11ea-8931-d98749cb7d88.png)
线被遮挡，问如何修改线？

**Comment by Yanyan-Wang** [comment]
需要看下你的 anchorPoints 是如何设置的。提供一下复现在线 demo

**Comment by xiaofengqqcom123** [comment]
@Yanyan-Wang demo地址： https://codesandbox.io/s/suspicious-mountain-u7g09?file=/Node.js

**Comment by Yanyan-Wang** [comment]
看下这样实现：https://codesandbox.io/s/nice-dubinsky-s2w3q?file=/Node.js
