### ISSUE TITLE
删除canvas画布视口外的group 报错了

### ISSUE THREAD

**Issue by asevenm** [antvis/G6#1994]
- **G6 Version**: 3.7.0
- **Platform**: 
- **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/22423693/91395291-77f75a80-e86d-11ea-80af-1c131915dcce.png)

- **CodePen Link**:
https://codesandbox.io/s/frosty-fast-yedjw?file=/src/App.js

**Comment by Yanyan-Wang** [comment]
删除图形分组使用 group.remove();

**Comment by Yanyan-Wang** [comment]
经排查，由于底层渲染引擎做了画布视口外的裁剪优化导致了这个问题，下个版本修复。暂时可以通过隐藏节点或者隐藏 group 来达到目的，graph.hideItem(node) 或 group.hide();。隐藏后的内容将不参与渲染

**Comment by asevenm** [comment]
> 经排查，由于底层渲染引擎做了画布视口外的裁剪优化导致了这个问题，下个版本修复。暂时可以通过隐藏节点或者隐藏 group 来达到目的，graph.hideItem(node) 或 group.hide();。隐藏后的内容将不参与渲染
好的
