### ISSUE TITLE
TreeGraph tb布局子集垂直

### ISSUE THREAD

**Issue by zhengbaofeng** [antvis/G6#1995]
![C2165724-069E-4b63-803A-70358CE085D5](https://user-images.githubusercontent.com/17873219/91408882-2e137200-e877-11ea-8713-36aceb78841c.png)
如图这种下面最子集垂直排列。文档上好像没对子集布局的描述

**Comment by Yanyan-Wang** [comment]
红圈部分类似这个布局 https://g6.antv.vision/zh/examples/tree/indented#hIntended

整个图看起来是 compactBox 布局和 indented 布局的拼合。但是现在 TreeGraph 不支持子图布局，Graph 支持。建议生成两个 TreeGraph，然后尝试加一条边拼起来。

**Comment by zhengbaofeng** [comment]
好的谢谢，我试下，

**Comment by hexinnnn** [comment]
@zhengbaofeng 您好，您这边解决了吗按这个思路
