### ISSUE TITLE
toolbar中的redo和undo是否支持在graph实例上调用

### ISSUE THREAD

**Issue by zhangtaoBqteam** [antvis/G6#1996]
toolbar中有redo和undo的操作，这两个是否可以在graph实例进行操作，我在graph实例的类型IGraph上好像没有看到这两个方法，如果没有是否可以支持一下

**Comment by Yanyan-Wang** [comment]
Graph 上目前没有提供这两个 API，只是维护两个 stack，可以从 stack 里面拿出数据来 changeData 来实现。可以参考一下这里的实现

https://github.com/antvis/G6/blob/a8a654e22f5ba45aa3c74812cf57980f3e464d6e/src/plugins/toolBar/index.ts#L234

https://github.com/antvis/G6/blob/a8a654e22f5ba45aa3c74812cf57980f3e464d6e/src/plugins/toolBar/index.ts#L182

**Comment by zhangtaoBqteam** [comment]
好的，谢谢
