### ISSUE TITLE
节点通过setState改变了形状，此时，从该节点往外出的线没变，导致节点过宽，盖住了线，求问怎么更新这条线重新画

### ISSUE THREAD

**Issue by zhoustudent** [antvis/G6#1997]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

G6 Version: 3.5.5
Platform:
Mini Showcase(like screenshots):
CodePen Link:

**Comment by Yanyan-Wang** [comment]
看下这个 issue 是不是类似 https://github.com/antvis/G6/issues/1993

另外，建议更新到最新版本
