### ISSUE TITLE
【催更】求更新3.7.0的CDN引用

### ISSUE THREAD

**Issue by WongBaba** [antvis/G6#1998]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
已发，感谢提醒。

**Comment by Yanyan-Wang** [comment]
https://gw.alipayobjects.com/os/antv/pkg/_antv.g6-3.7.0/dist/g6.min.js
