### ISSUE TITLE
Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by xiaofengqqcom123** [antvis/G6#1999]
version：antv/G6 3.70
添加点击事件报错：
TypeError: Cannot read property 'filter' of undefined
![image](https://user-images.githubusercontent.com/29247931/91419312-dc261880-e885-11ea-8b3c-13bd2ef17b44.png)

demo:https://codesandbox.io/s/suspicious-mountain-u7g09?file=/index.js:506-511

**Comment by Yanyan-Wang** [comment]
还是和你的自定义节点实现有关，这个地方的 defaultNode 可能是 null。可以判断不是 null 再调用 removeChild。

![image](https://user-images.githubusercontent.com/29593318/91421725-da118900-e888-11ea-98f1-59d258a09fdb.png)

或者使用 issue 里面我提供的实现方式就没问题了 https://github.com/antvis/G6/issues/1993
