### ISSUE TITLE
Tree有办法可以方便的翻转所有边吗

### ISSUE THREAD

**Issue by ShikiRyougi** [antvis/g6#20]
Tree 的direction 只能改变布局方向，没法改变边的指向，类似晋级赛这种图是从children指向parent的，现在g6有api实现这样的效果吗?
@leungwensen

**Comment by leungwensen** [comment]
目前没有针对晋级赛的图做定制，只能通过自定义边的方式来做： https://antv.alipay.com/g6/demo/06-other/custom-arrow.html 类似这样，画树边的时候 tree.edge().shape('customized-edge'); 把边的shape指定为自定义边就好了。
