### ISSUE TITLE
如何释放G6绘画所占用的内存？在快速地绘制比较多且类型不一样的画布之后，页面会导致卡顿

### ISSUE THREAD

**Issue by LaiHuanMin** [antvis/g6#200]
因为用户会频繁的快速的查看各种G6绘制的图表（时序图，树图，网图等等20来个类型，且数据量都比较大），频率大概是一秒2次左右，并且是同一个地方，因此会频繁的创建Net实例并直接移除Net实例所对应的DOM元素。    
现在问题是，在比较频繁地创建Net实例和直接移除DOM元素之后，页面会导致十分卡顿，而且本身应用也是单应用。即使采用了隐藏的方式也会导致浏览器内存占用直线上升，因为数据量是特别大的，直接移除DOM貌似不太行。    
想问一下，有没有类似于`net.destroy()`这样的方法进行释放呢？因为我感觉绘画之后Net实例一直在占用着一部分内存，最终可能有内存泄漏的问题，谢谢！

**Comment by TomHuangCN** [comment]
按理 net.destroy ，会销毁所有 net 创建的东西，以及 net 自己，应该是你其它地方哪里还引用这 net 导致它没被释放

**Comment by LaiHuanMin** [comment]
好的，我尝试一下

**Comment by EmmaYXY** [comment]
> 按理 net.destroy ，会销毁所有 net 创建的东西，以及 net 自己，应该是你其它地方哪里还引用这 net 导致它没被释放

我给插件 tooltip 的 getContent 的配置赋了一个方法，这个方法内部引用了方法代码所在的vue组件，在vue组件的beforeDestroy钩子中调用了net.destroy和removePlugin，但是内存中依旧存在这个vue组件，是因为什么呢？
