### ISSUE TITLE
G6中使用G2提供的包@antv/chart-node-g6无法安装下来

### ISSUE THREAD

**Issue by wsb260** [antvis/G6#2001]
- **G6 Version**:3.7.0
- **Platform**:
window  node版本是12.18.1 
- **Mini Showcase(like screenshots)**:
G6中使用G2提供的包@antv/chart-node-g6无法安装下来
相关依赖包都安装不了，错误提示太多无法粘贴
- **CodePen Link**:
https://www.yuque.com/antv/g6-blog/pwg00q
https://www.npmjs.com/package/@antv/chart-node-g6

**Comment by baizn** [comment]
把 npm 镜像换成国内的试下，还不行的话关键错误信息粘贴出来。
