### ISSUE TITLE
使用addShape添加的image

### ISSUE THREAD

**Issue by ZouXueLiang** [antvis/G6#2002]
插入本地图片没有效果

**Comment by Yanyan-Wang** [comment]
请使用网络资源。或者把图片转换成 base64 字符串

https://g6.antv.vision/zh/docs/manual/advanced/keyconcept/shape-and-properties/#%E5%9B%BE%E7%89%87%E5%9B%BE%E5%BD%A2-image

**Comment by ZouXueLiang** [comment]
谢谢。已解决。
顺道提一个兼容优化 :IE不兼容event.path 导致toolbar失效。
 //在ie/edge重写composedPath方法
                    (function(e, d, w) {
                        if (!e.composedPath) {
                            e.composedPath = function() {
                                if (this.path) {
                                    return this.path;
                                }
                                var target = this.target;

                                this.path = [];
                                while (target.parentNode !== null) {
                                    this.path.push(target);
                                    target = target.parentNode;
                                }
                                this.path.push(d, w);
                                return this.path;
                            }
                        }
                    })(Event.prototype, document, window);
