### ISSUE TITLE
过多Combo会造成性能问题

### ISSUE THREAD

**Issue by MuZiRuoYi** [antvis/G6#2004]
- **G6 Version**: 3.6.1
- **Platform**: win10 16G
- **CodePen Link**: https://codepen.io/muziruoyi/pen/JjXNwaX
- **数据量**：2400 node，2000 edge，200 combo

截图：
![image](https://user-images.githubusercontent.com/9068060/91519357-f400a980-e924-11ea-8799-e619fa8a615d.png)

问题：
combo过多会造成性能上问题，如果去掉combo则会变得性能大增。

**Comment by Yanyan-Wang** [comment]
是的，combo 的管理需要维护一个嵌套的树结构，每次查询、更新等操作都需要递归遍历树、更新树。下个小版本优化尽量减少 sortCombos 的调用。

**Comment by MuZiRuoYi** [comment]
这里会造成界面卡住没法操作，如果渲染慢不卡住界面，能展示一个loading状态也可以暂时解决一下，这个可以怎么来实现吗？
另外自定义布局可以怎么使用workerEnabled？

**Comment by Yanyan-Wang** [comment]
你的节点数量有多少，这个布局应该不需要太长时间。应该就是因为 combo 太多耗时操作造成的

**Comment by MuZiRuoYi** [comment]
是的，就是combo造成的，那么有方式可以防止卡死界面吗？

**Comment by Yanyan-Wang** [comment]
我看到你的布局似乎和 grid 布局很相似，这个布局应该不需要太长时间吧。如果需要 worker 布局的话，只需要在实例化图时配置 layout 为你的自定义布局的时候，配置 workerEnabled 应该就可以的。

卡斯应该就是因为 combo 太多耗时操作造成的，这两天会发个小版本提升一下 combo 性能，到时候再试试。

**Comment by MuZiRuoYi** [comment]
期待新版本。

提供一种解决方案是把combo拆开：
自定义了一些特殊的节点来承载combo的操作，所以布局就仅是节点布局，不存在combo了；
combo非操作部分在布局后通过计算拿到combo宽高等属性；
然后通过：`group.addShape('rect', {})`来手动绘制combo其他仅样式部分，再通过toBack修改层级。
这样可以大幅提高性能。

**Comment by Yanyan-Wang** [comment]
v3.7.1 已发布

**Comment by Yanyan-Wang** [comment]
上面 demo 我试了一下 3.7.1 初次渲染可以快很多。
