### ISSUE TITLE
书结构自定义节点和边超过边界会消失问题ii

### ISSUE THREAD

**Issue by WongBaba** [antvis/G6#2007]
- **G6 Version**: 3.6.2，3.7.0
- **Platform**: 
- **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/44690857/91531823-fde3d600-e93f-11ea-9d22-e5bb4e9e7b0b.png)

- **CodePen Link**:

node 和 edge 使用了案例https://g6.antv.vision/zh/examples/case/metroLines ， 里自定义的node和edge后，
modes: {
                        default: [
                            'drag-canvas',
                            'zoom-canvas',
                        ],
                    },

移动树结构超过容器边界后的 边和节点会消失，3.6.2和3.7.0的cdn有这个问题，3.6.0的没有

**Comment by Yanyan-Wang** [comment]
提供一个复现的在线 demo 吧

**Comment by WongBaba** [comment]
> 提供一个复现的在线 demo 吧

https://pan.baidu.com/s/11tlHdtaf45KnxwtWCxLa2w 提取码:4i8s
服务器手机连不上，公司网络不允许，凑合用网盘看一下吧，弄成单个html了
公

**Comment by Yanyan-Wang** [comment]
这个我们公司笔记本不可以下载的

**Comment by WongBaba** [comment]
> 这个地址我们公司笔记本不可以下载的。你可以写到自己的 github 仓库里

https://github.com/WongBaba/KINS-SYSTEM/blob/master/g6_demo.html 再看下

**Comment by 429365799** [comment]
在 `graph.render()` 之前加上 `graph.get('canvas').set('localRefresh', false);` 暂时关闭局部渲染可以解决，从 3.6.1-beta 开始就会出现这个问题，等一波修复吧

**Comment by Yanyan-Wang** [comment]
v3.7.3 已修复
