### ISSUE TITLE
toolBar的undo和redo操作，redo过程中会因为edge没有source节点而导致失败

### ISSUE THREAD

**Issue by LiuYnag** [antvis/G6#2009]
https://codesandbox.io/s/stoic-water-jyukp
这个是我改造官网的例子做的效果。
操作流程是点击两次undo操作后节点和线会清空掉。
然后再点两次redo操作就会报出警告：index.js:27 The source or target node of edge e4 does not exist!
具体原因大概是在redo过程中由于要重新添加edge的数据，
但此时edge线的source节点还不存在，导致了edge线的加载失败
请问这种问题有什么好的解决方式么？

**Comment by Yanyan-Wang** [comment]
是因为 redo undo 里面数据记录有问题。v3.7.1 已修复
