### ISSUE TITLE
自定义节点用于树图时，总是右边先渲染，左边很短

### ISSUE THREAD

**Issue by xuedaobian** [antvis/G6#2010]
[codepen链接 ](https://codesandbox.io/s/elated-monad-eudnk?file=/index.js)

**Comment by Yanyan-Wang** [comment]
compactBox 布局的 getHGap 可以根据不同节点数据返回不同数值，代表水平方向上的距离，例如：

![image](https://user-images.githubusercontent.com/29593318/91553974-d9e4bc80-e960-11ea-8b93-424557d19fab.png)

布局参数参见官网文档 https://g6.antv.vision/zh/docs/api/layout/TreeGraph#compactbox-%E7%B4%A7%E5%87%91%E6%A0%91%E5%B8%83%E5%B1%80

**Comment by xuedaobian** [comment]
现在的问题是，我应该是统一定义了水平距离了，但是他表现的不一样呀，这是我不懂的

**Comment by xuedaobian** [comment]
我在单一修改的时候，发现只能修改和它上一层的距离，和children的距离仍然不会变化
