### ISSUE TITLE
自定义节点挂载到tree graph上，距离不定，修改getHGap只能修改其与父级数据的关系，不能改变其和children的距离。

### ISSUE THREAD

**Issue by xuedaobian** [antvis/G6#2011]
[codepen链接](https://codesandbox.io/s/elated-monad-eudnk?file=/index.js:3897-3904)

**Comment by Yanyan-Wang** [comment]
那就设置自节点的 getHGap 不能满足需求吗？

**Comment by xuedaobian** [comment]
事实上我设置了，只是我不知道是什么样的原因导致的变化

**Comment by Yanyan-Wang** [comment]
该参数是设置节点与父的距离。还有一个参数 getWidth 可以尝试一下。

**Comment by xuedaobian** [comment]
ok

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。

**Comment by xuedaobian** [comment]
你好，我已经收到你的邮件。
