### ISSUE TITLE
Grid网格错位

### ISSUE THREAD

**Issue by hxj123** [antvis/G6#2012]
![image](https://user-images.githubusercontent.com/28498564/91655338-72ef1100-eae2-11ea-87b8-643eea8fca64.png)

插件grid网格不会根据canvas的位置自动覆盖，如图右下角是canvas的区域，左边和上边都是工具栏，自定义的dom节点，加上grid后，grid的位置会直接跑到左上角，右下角会出现空白，代码如下
`const grid = new G6.Grid()`
`const graph = new G6.Graph({
  plugins: [grid]
})`

**Comment by Yanyan-Wang** [comment]
grid 是一个放置在 canvas 后面的，带有背景图片的 DOM，position: absolute。可以暂时自己拿到 grid 的 DOM 调整一下 top 和 left，其 class 为 'g6-grid-container'。

下个小版本修复。

**Comment by person001** [comment]
我在combo布局下使用网格背景，没有显示。调整g6-grid-container的z-index为0，显示，但是盖过画布，画布不能操作，请问如何处理！

**Comment by gouzixing** [comment]
> 我在combo布局下使用网格背景，没有显示。调整g6-grid-container的z-index为0，显示，但是盖过画布，画布不能操作，请问如何处理！

同问
