### ISSUE TITLE
节点高亮时如何隐藏没有高亮的节点文本？求大佬

### ISSUE THREAD

**Issue by YC725968** [antvis/G6#2013]
一、在进行节点高亮时，如何高亮时隐藏没有高亮的节点文本，求大佬解答哈，看文档里实在是找不到。
二、问题比较低级，右键菜单的事件冒泡如何阻止啊。

**Comment by Yanyan-Wang** [comment]
- 隐藏节点中的某图形可以参考 https://g6.antv.vision/zh/examples/tool/fisheye 中的 91 行；
- 原始需求是什么？如果是想节点上局部相应邮件菜单，可以写 shouldBegin 判断，return true 就是可以出现菜单，return false 反之。文档有描述 https://g6.antv.vision/zh/docs/api/Plugins#menu
