### ISSUE TITLE
更新边edge的样式时报错

### ISSUE THREAD

**Issue by wrh4585** [antvis/G6#2015]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

更新边edge报错。
选中边，通过一个颜色选择器选择颜色后，拿到选中边的model，对其中的style的stroke进行赋值，然后调用updataItem方法，不生效。refreshItem()也不生效。最后修改实现方法---拿到边edge的keyShape，然后使用keyShape.attr()对style的stroke进行赋值，在调用refreshItem（）依然不起作用。使用updateItem()时可以生效，但不能传递model值，否则也不生效。但是不传递model值会报source undefined的错误。
请问正确的更新边的样式的操作是怎样的？

**Comment by Yanyan-Wang** [comment]
G6 哪个版本？并且麻烦提供复现在线 demo

**Comment by wrh4585** [comment]
G6版本是3.6.1，自定义的边，继承polyline。

**Comment by Yanyan-Wang** [comment]
升级到最新版本（3.7.0）。不能确定问题原因，请提供一下复现在线 demo，可以写在 codesandbox.io 或者 codepen.io。例如：https://codepen.io/Yanyan-Wang/pen/mdbYZvZ

**Comment by wrh4585** [comment]
我先升级下，在确定下原因，目前虽然有保存，但是可以完成对边的颜色、实线虚线的设置。
