### ISSUE TITLE
如何给hover状态的节点，添加tooltip

### ISSUE THREAD

**Issue by xiaofengqqcom123** [antvis/G6#2016]
需求：hover状态下，如何给节点中的某shape，添加tooltip？
demo： https://codesandbox.io/s/musing-cdn-9o37z?file=/index.js

**Comment by Yanyan-Wang** [comment]
这里有点问题，下个小版本修复。今天或明天发布

**Comment by xiaofengqqcom123** [comment]
版本升级到V3.7 仍存在问题~ 
版本antv/g6@2.2.6中可以~
需求：自定义节点（shape A 包裹着 shape B）中，想hover到 shape B时，展示下拉框~
问题：从shape A 滑动至 shape B时，无法获取到这个事件~

**Comment by xiaofengqqcom123** [comment]
> 版本升级到V3.7 仍存在问题~
> 版本antv/g6@2.2.6中可以~
> 需求：自定义节点（shape A 包裹着 shape B）中，想hover到 shape B时，展示下拉框~
> 问题：从shape A 滑动至 shape B时，无法获取到这个事件~

demo：https://codesandbox.io/s/musing-cdn-9o37z?file=/Node.js

**Comment by Yanyan-Wang** [comment]
你给的链接中，把 G6 依赖再刷新一下就可以了
