### ISSUE TITLE
TreeGraph多个state冲突问题

### ISSUE THREAD

**Issue by StarkShang** [antvis/G6#2021]
使用TreeGraph的时候遇到如下问题，请大佬解答。
1. 设置了"hover"和"select"两种状态：
```
stateStyles: {
            "hover": {
                "stroke": "red"
            },
            "selected": {
                "stroke": "yellow"
            }
}
```
2. 设置了mouseenter、mouseleave、node:click三个事件
mouseenter事件，设置"hover"状态graph.setItemState(node, "hover", true)
node:click事件，设置"select"状态graph.setItemState(node, "select", true)
mouseenter事件，取消"hover"状态graph.setItemState(node, "hover", false)

期望效果：鼠标进入node，node边框为红色；此时点击鼠标，node边框变为黄色；鼠标离开node，node边框保留黄色
实际效果：鼠标进入node，node边框为红色；此时点击鼠标，node边框变为黄色；鼠标离开node，node边框无色（默认样式）

通过node.getStates()打印node的状态，如下
初始状态：[]
鼠标进入node：["hover"]
鼠标点击node：["hover", "select"]
鼠标离开node：["select"]
鼠标再次进入node：["select", "hover"]
鼠标再次离开node：["select"]

好像state数据和预期的一样，但是实际效果和预期不同。

**Comment by Yanyan-Wang** [comment]
使用的哪个版本的 G6？请提供复现在线 demo。这个例子和你说的正确逻辑是一样的：https://g6.antv.vision/zh/examples/item/defaultNodes

**Comment by baizn** [comment]
更新到最新版本，这个是之前版本一个bug，最新版本中已经修复了。
