### ISSUE TITLE
动态添加的 Combo Edge 起始点有问题

### ISSUE THREAD

**Issue by Hugo-seth** [antvis/G6#2023]
- **G6 Version**: 3.7.0
- **Platform**:  windows 10
- **Mini Showcase(like screenshots)**:
 ![image](https://user-images.githubusercontent.com/17878774/91400735-bf341a00-e872-11ea-84f0-5f8c2c767623.png)
- **CodePen Link**: https://codesandbox.io/s/interesting-dan-orwbs?file=/index.js
已设置 groupByTypes: false

**Comment by Yanyan-Wang** [comment]
默认情况下，combo 的边将会连接到 combo 的中心，有两个解决方案：
- 为 combo 设置 anchorPoints，即边的连接位置，和节点设置 anchorPoints 的方法相同，文档：http://g6.antv.antgroup.com/manual/middle/elements/nodes/anchorpoint

例如
```
anchorPoints: [
      [0.5, 1],
      [0.5, 0],
    ]
```
- 设置 combo 的透明度为不透明，看不到它连到中心
