### ISSUE TITLE
拖拽画布有痕迹留下

### ISSUE THREAD

**Issue by Lollipopls** [antvis/G6#2024]
version:3.7.0
![image](https://user-images.githubusercontent.com/28340418/91929372-d3639580-ed10-11ea-9ed6-ed2f5496abea.png)

**Comment by Yanyan-Wang** [comment]
请提供复现在线 demo

**Comment by HuChundong** [comment]
graphInstance.get('canvas').set('localRefresh', false) 可以解决。
官方之前说会修复局部刷新，但是一直没修复

**Comment by Yanyan-Wang** [comment]
可以尝试一下 v4.0.2，字体的残留问题已经修复了，你这里的问题不是很确定是否修复

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
