### ISSUE TITLE
拖拽偶尔会出现流程图悬浮问题，双击才可以放下

### ISSUE THREAD

**Issue by Lollipopls** [antvis/G6#2025]
version:3.7.0

![image](https://user-images.githubusercontent.com/28340418/91929904-078b8600-ed12-11ea-8b94-86113cd88bcc.png)

**Comment by Yanyan-Wang** [comment]
issue 麻烦提供复现在线 demo ，否则效率很低

**Comment by HuChundong** [comment]
界面上其他的div的选中设置为none可解决
