### ISSUE TITLE
G6使用G2图表的问题

### ISSUE THREAD

**Issue by wrh4585** [antvis/G6#2026]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

G6使用G2图表的问题
很欣喜的看到G6支持自定义节点时可以使用图表了。咱看官方的示例时，发现图表中没有axis、Tooltip、legend等。
https://antv-g6.gitee.io/zh/examples/item/customNode#pointChartNode
此示例中设置了tooltip，但是未显示，不确定是否是目前不支持axis、Tooltip、legend 等组件；

**Comment by baizn** [comment]
Axis 是支持的，Tooltip 也是支持的，可以通过 `view.interaction("tooltip") ` 开启，但目前有个坐标不准的问题，其他组件暂时没有支持，在我们这边没有很多的业务场景，暂时还不确定加那些组件，你这边方便的话可以把你们的业务诉求描述一下，另外是通过 https://github.com/antvis/chart-node-g6 这个库让节点中支持图表的，有兴趣的话可以直接提 PR。

**Comment by wrh4585** [comment]
目前是使用G6来实现编辑器的功能，即设置一些节点，使用时将需要的节点添加到对应的画布中，然后配置节点的一些属性，例如节点的大小、边框、填充色等。然后需要使用到图表。图表需要在拖动到画布时请求数据，根据数据渲染出对应的图表。然后编辑完成后将画布上的数据保存，将保存的数据作为展示的源数据。
展示页为一个新的页面，根据编辑时保存的数据，将对应节点的位置等渲染到新的页面。图表类的需要展示为图表，包括图表的各种基础性的功能。类似于自定义了一个网页，但是不适应常规的html的布局，而是使用G6来进行渲染。
功能上类似于https://guozhaolong.github.io/wfd/。将左侧的节点拖入画布。在右上角进行预览（查看）。

**Comment by baizn** [comment]
> 目前是使用G6来实现编辑器的功能，即设置一些节点，使用时将需要的节点添加到对应的画布中，然后配置节点的一些属性，例如节点的大小、边框、填充色等。然后需要使用到图表。图表需要在拖动到画布时请求数据，根据数据渲染出对应的图表。然后编辑完成后将画布上的数据保存，将保存的数据作为展示的源数据。
> 展示页为一个新的页面，根据编辑时保存的数据，将对应节点的位置等渲染到新的页面。图表类的需要展示为图表，包括图表的各种基础性的功能。类似于自定义了一个网页，但是不适应常规的html的布局，而是使用G6来进行渲染。
> 功能上类似于https://guozhaolong.github.io/wfd/
> 将左侧的节点拖入画布。在右上角进行预览（查看）。

那这个你要不看下能不能根据你们需求，把图表节点的组件功能完善一下，提交个 PR。

**Comment by wrh4585** [comment]
我这边还在看G2，后续如果使用到了这个，根据情况吧，看看是否能修改到满足需求，可以的话，还是蛮倾向于提个PR，贡献点力量

**Comment by Yanyan-Wang** [comment]
> 我这边还在看G2，后续如果使用到了这个，根据情况吧，看看是否能修改到满足需求，可以的话，还是蛮倾向于提个PR，贡献点力量

欢迎欢迎

**Comment by linxner** [comment]
> Axis 是支持的，Tooltip 也是支持的，可以通过 `view.interaction("tooltip") ` 开启，但目前有个坐标不准的问题，其他组件暂时没有支持，在我们这边没有很多的业务场景，暂时还不确定加那些组件，你这边方便的话可以把你们的业务诉求描述一下，另外是通过 https://github.com/antvis/chart-node-g6 这个库让节点中支持图表的，有兴趣的话可以直接提 PR。
这个定位不准的问题能修复吗？或者有没有其他方法解决这个定位的问题呢？
