### ISSUE TITLE
能否提供单个节点或边导出为图片的api

### ISSUE THREAD

**Issue by CSNight** [antvis/G6#2028]
- **G6 Version**: 3.7.0
- **Platform**: 
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

能否提供单个节点或边导出为图片API？现在只提供了整个graph导出为图片。
这个需求主要是为了一些自定义的节点或边在后续开发中做缩略图提供给其他系统使用

**Comment by Yanyan-Wang** [comment]
目前不考虑支持这个 API，欢迎社区贡献
