### ISSUE TITLE
updateitem 只想更新label 但是图片也重绘了  导致图片会出现闪烁现象

### ISSUE THREAD

**Issue by Yiliayouyou** [antvis/G6#2029]
demo如下：点击图片节点 只希望更新label 但是图片闪烁了一下  如果页面上有很多节点的话 闪烁很严重
https://codepen.io/yiliayouyou/pen/ExKwZGo
浏览器环境：chrome 版本 85.0.4183.83（正式版本） （64 位）

之前浏览器为chrome 80.x的时候不会有这么严重的闪烁问题
有没有办法只更新label样式  图片不会重新渲染

**Comment by Yanyan-Wang** [comment]
这样可以单独更新一个图形：

```
  graph.on('node:click', evt => {
    const node = evt.item;
    const group = node.getContainer();
    const label = group.find(e => e.get('name') === 'text-shape');
    label.attr('fill', 'red');
  });
```
