### ISSUE TITLE
加入边动画后，视图放大超过容器，节点会被隐藏

### ISSUE THREAD

**Issue by xueyuwan** [antvis/G6#2030]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
请提供复现在线 demo

**Comment by xueyuwan** [comment]
仓库地址 https://gitee.com/xueyuwan/g6   home 页面，感谢

**Comment by Yanyan-Wang** [comment]
如果数据量不大的话，可以先把局部渲染关掉

graph.get('canvas').set('localRefresh', false);

我们后续再排查

**Comment by Yanyan-Wang** [comment]
v3.7.3 已修复

**Comment by xueyuwan** [comment]
感谢，问题已解决
