### ISSUE TITLE
动画时，zoom-canvas导致item丢失

### ISSUE THREAD

**Issue by superwzx** [antvis/G6#2031]
- **G6 Version**:3.7.0
- **Platform**:macos10.15.6  chrome84.0.4147.135
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:https://36y39.csb.app/

动画时放大缩小画布导致item丢失，详情见演示链接。
![image](https://user-images.githubusercontent.com/1204064/92061459-f3ef2680-edc8-11ea-9f3f-622da9b48922.png)

**Comment by Statfine** [comment]
拖动出可视区域之后，再拖回来也会丢失，而且图标也丢失了
