### ISSUE TITLE
升级到3.7.0版本后，自定义DOM节点报错

### ISSUE THREAD

**Issue by wrh4585** [antvis/G6#2032]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

如题，在升级到3.7.0版本后，注册自定义的DOM节点，提示
![image](https://user-images.githubusercontent.com/45685551/92061690-7f68b780-edc9-11ea-8bfe-ac8dd8125821.png)
断点到该位置，发现该构造方法里不存在DOM类型。是将此类型删掉了么？
![image](https://user-images.githubusercontent.com/45685551/92061631-5ea06200-edc9-11ea-8aa3-86cc652ecbf2.png)

**Comment by Yanyan-Wang** [comment]
是不是实例化图的时候没配置 renderer: 'svg'

还有问题请提供在线 demo

**Comment by wrh4585** [comment]
设置了 renderer: 'svg'。目前在做使用自定义G2图表的事情，G2图表可以满足需要的话，就不需要自定义的DOM了。业务需求就是需要将charts图表加入到节点中。
谢谢回复

**Comment by Yanyan-Wang** [comment]
写个在线 demo 吧。这里看起来是没用 svg 引擎才会没有 DOM 的图形。

G2 图标可以看下这个能不能满足 https://g6.antv.vision/zh/examples/item/customNode#lineChartNode
