### ISSUE TITLE
火狐下，g6自定义的double-finger-drag-canvas事件无法上下滚动

### ISSUE THREAD

**Issue by yangjialing** [antvis/G6#2033]
谷歌是可以的，但是火狐不支持
链接：https://g6.antv.vision/zh/examples/interaction/customBehavior，官网有demo，鼠标滚轮无法上下滚动

期望，鼠标滚轮事件能支持上下滚动

**Comment by Yanyan-Wang** [comment]
该 demo 更新了哈。在火狐里面获取坐标的方法会不大一样

if (!y && navigator.userAgent.indexOf('Firefox') > -1) y = (-ev.wheelDelta * 125) / 3
