### ISSUE TITLE
右键冒泡点击事件

### ISSUE THREAD

**Issue by YC725968** [antvis/G6#2035]
demo地址:   https://codepen.io/yc725968/pen/XWdzmWm

在该demo中右键菜单当点击第二个li菜单按钮时会产生事件冒泡，该怎么阻止冒泡？感谢

**Comment by YC725968** [comment]
在该例子中自由套索工具也是失效的

**Comment by Yanyan-Wang** [comment]
你的 demo 的 switch 每个 case 没有 break 呀，执行完第一个接着就会执行第二个了。这跟冒泡没关系。

lassp-select 的 trigger: 'ctrl' 可能和你电脑上的 control 键的 key 值不同。我这里是 mac ，改成 trigger: 'control' 就可以了。先确定一下你的键盘按键的值是什么

**Comment by YC725968** [comment]
你好，感谢你的解答，成功解决问题。在上面的例子中，当我激活当前高亮点时，把图形上的文本标签的透明度设置为低，但当我点击画布时，有些文本标签就不显示，这个问题该怎么解决，高亮时文本标签呢。点击画布时显示所有标签呢？

**Comment by YC725968** [comment]
active: {
            opacity: 1,
            'text-shape': {
              // fill:'red',
              fontSize: 15,
              opacity: 1
            }
          },
          inactive: {
            opacity: 0.2,
            'text-shape': {
              // fill:'red',
              // fontSize:30,
              opacity: 0
            }
          }

**Comment by Yanyan-Wang** [comment]
其他问题的话，再开新的 issue 吧。并提供在线 demo
