### ISSUE TITLE
Minimap中文字旋转后显示异常

### ISSUE THREAD

**Issue by BG5FD** [antvis/G6#2038]
将G6图表中的节点label旋转之后，在MInimap上面的显示异常，旋转度数扩大了两倍
G6 Version: 3.2.9
Platform: chrome,
Mini ShowCase: 
![image](https://user-images.githubusercontent.com/27286190/92195560-e8226380-ee9f-11ea-928f-438b1f10e5f8.png)

CodePen Link: https://codesandbox.io/s/optimistic-grass-ggbtq?file=/index.html,

**Comment by Yanyan-Wang** [comment]
使用新版本即可：https://codesandbox.io/s/beautiful-bell-rjyg7?file=/index.html

升级指南：https://g6.antv.vision/zh/docs/manual/FAQ/upgradeGuide
