### ISSUE TITLE
label问题

### ISSUE THREAD

**Issue by YC725968** [antvis/G6#2039]
demo 地址：https://codepen.io/yc725968/pen/XWdzmWm
在该demo中激活几点时label标签是通过intive和inactive设置隐藏和显示，如何在取消选中节点后显示所有的标签，或者有没有其他的办法？

**Comment by Yanyan-Wang** [comment]
应该是 opacity: 0 被判断成了没有这个属性，后面 G6 里面修一下。目前可以在 inactive 里面设置 label 的 opacity: 0.0001 暂时解决一下这个问题

**Comment by YC725968** [comment]
好的，麻烦修复时告知一声哦，感谢！

**Comment by YC725968** [comment]
目前在边label中使用opacity:0.0001和0 都是失效的
