### ISSUE TITLE
dagre图如何手动设置combo位置

### ISSUE THREAD

**Issue by Zhouqchao** [antvis/G6#2040]
- **G6 Version**: 3.7.0
- **Platform**: Mac
- **Mini Showcase(like screenshots)**:
![业务需求图](https://tva1.sinaimg.cn/large/007S8ZIlgy1giehxfx1itj30q80gitg9.jpg)
![dagre流程图，待完成](https://tva1.sinaimg.cn/large/007S8ZIlgy1giehxw17f0j308u0du74r.jpg)

- **CodePen Link**:
https://codepen.io/Tom_chao/pen/MWyOozy?editors=1010

业务需求是实现一个拓扑图（见图一）。每个combo包含n个节点，每个节点可能会连接另一个combo。目前使用的是dagre流程图布局，但是布局位置好像有点问题（见图二），我想手动定位combo位置，但是没效果。请问如何用g6实现“业务需求图”中的效果，能提供思路也好，谢谢。

**Comment by Yanyan-Wang** [comment]
combo 位置和大小是由内部节点的位置和大小确定的，除了空 combo 外，其他 combo 不能指定位置。功能设计上是这样的。要改变 combo 位置，改变内部节点位置即可

**Comment by Zhouqchao** [comment]
> combo 位置和大小是由内部节点的位置和大小确定的，除了空 combo 外，其他 combo 不能指定位置。功能设计上是这样的。要改变 combo 位置，改变内部节点位置即可

好的，谢谢🙏
