### ISSUE TITLE
3.7.1版本grid网格定位偏移问题

### ISSUE THREAD

**Issue by CSNight** [antvis/G6#2042]
G6 3.7.1
https://github.com/antvis/G6/blob/b8480940ac285c06bd5c6abecc6333a322051f56/src/plugins/grid/index.ts#L50

这里采用offsetTop 和offetLeft会导致 如果容器没有position定位的话 会导致grid错误的偏移 offsetTop应该是计算的父级dom中含有position定位的父级与当前容器之间的距离

**Comment by Yanyan-Wang** [comment]
麻烦提一个复现的在线 demo

**Comment by CSNight** [comment]
> 麻烦提一个复现的在线 demo

https://codepen.io/csnight/pen/rNeJQyg

**Comment by Yanyan-Wang** [comment]
该问题在 4.x 中已不存在，请试用 4.7.15
