### ISSUE TITLE
【bug】toolbar 默认的“恢复”功能节点/边 形状丢失

### ISSUE THREAD

**Issue by Rranran** [antvis/G6#2043]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/purple-surf-526bs?file=/src/index.js)

### Steps to reproduce
1. 点击“添加节点”；页面新建一个矩形
2. 点击“撤销”；矩形删除
3. 点击“恢复”；页面恢复的形状为圆形（默认值）
```js
  if (stack && this.get('enabledStack')) {
      this.pushStack('add', (0, _tslib.__assign)((0, _tslib.__assign)({}, item.getModel()), {
        type: type
      }));
    }
```

上面这个逻辑 push 的时候 type 是 addItem 的第一个参数，为 node/edge/combo
后面处理的时候使用它覆盖了 item.getModel() 中的type，导致“恢复”操作形状丢失

| Environment | Info |
|---|---|
| g6 | 3.7.0 |
| System | window |
| Browser | chrome85 |

**Comment by Yanyan-Wang** [comment]
好的，感谢提醒，下个小版本修复。另外，addItem 的时候加上 unique string 作为 id 可以避免和其他在撤销和恢复时节点产生混淆。
