### ISSUE TITLE
Antvis G6 in Nuxtjs

### ISSUE THREAD

**Issue by NguyenNamUET** [antvis/G6#2044]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gallant-lewin-3vb73?file=/pages/test.vue)

### Steps to reproduce
Install antvis G6

import G6 from '@antv/g6' in any Nuxt pages and components

=> Result in error document is not defined  

| Environment | Info |
|---|---|
| g6 | 3.7.1 |
| System | Ubuntu 18.04 |
| Browser | Chrome Firefox (latest) |

---
Can you add detail import and usage of Antvis G6 in Nuxtjs and Vuejs?

**Comment by baizn** [comment]
AntV G6 in react：https://github.com/baizn/g6-in-react

**Comment by Yanyan-Wang** [comment]
Hi, dear user. Since there was no response for a long time, we cannot figure out the answer of the problem you described. If there is new progress, feel free to open a new issue.
