### ISSUE TITLE
官网中文版生态树 demo 页面拖拽文本出现甩尾现象

### ISSUE THREAD

**Issue by Meowu** [antvis/G6#2045]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g6.antv.vision/zh/examples/tree/dendrogram#tbDendrogram](https://g6.antv.vision/zh/examples/tree/dendrogram#tbDendrogram)

### Steps to reproduce
1. 打开上述链接；
2. 随意拖拽树图；
3. 被拖拽离开的区域会残留边缘节点文本
![wnuD4s.png](https://s1.ax1x.com/2020/09/07/wnuD4s.png)

| Environment | Info |
|---|---|
| g6 | 3.7.1 |
| System | macOS 10.14.6 |
| Browser | Chrome Version 85.0.4183.83 (Official Build) (64-bit) |

**Comment by Yanyan-Wang** [comment]
我这里 macOS 10.14.5 Chrome 84.0.4147.89 没有复现，试一下使用无痕浏览器打开然后打开控制台后，在刷新按钮上右击，选择清空缓存并硬性重新加载试试呢？还有问题的话，可以暂时先把局部渲染关闭：

graph.get('canvas').set('localRefresh', false) ，在 graph.render 之前调用

**Comment by Meowu** [comment]
我在公司的黑苹果发现的，回家用 MBP 同样版本和 Chrome 一样的版本也发现了同样的问题，而且只在中文版下面出现，切换到英文版就正常。
也使用 Firefox 测试了没问题。
