### ISSUE TITLE
g6 节点分组Combo有力导布局‘comboForce’ 这个布局是针对分组的，能否新增一些api专门为分组内的节点布局 

### ISSUE THREAD

**Issue by LincolnPack** [antvis/G6#2047]
g6 节点分组Combo有力导布局‘comboForce’ 这个布局是针对分组的，能否新增一些api专门为分组内的节点布局 

例如：
节点分组用comboForce布局
分组内的节点用其他布局如：流程布局。

**Comment by Yanyan-Wang** [comment]
暂时没有专门针对 combo 内部的布局，但是可以使用子图布局功能，拿出 combo 内的节点进行布局，参考 https://g6.antv.vision/zh/examples/net/layoutMechanism#subgraphLayout

**Comment by LincolnPack** [comment]
子图布局可以用任何图布局（非树图布局），子图布局为何不支持数图布局，

**Comment by Yanyan-Wang** [comment]
新增 comboCombined 布局支持配置内外不同的布局：http://g6.antv.antgroup.com/examples/net/comboLayout/#comboCombined

树图布局的子图布局在当前版本没有计划支持
