### ISSUE TITLE
mac 触摸板 无法放大缩小 图

### ISSUE THREAD

**Issue by lgoldfish** [antvis/G6#2049]

**Comment by Yanyan-Wang** [comment]
请按照 issue 模版提供 G6 版本号、在线复现 demo，否则 issue 将被关闭。

**Comment by JohnnyLuv** [comment]
> _No description provided._

mac触摸板是双指上划、下滑模拟滚动缩放的

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
