### ISSUE TITLE
自定义节点采用JSX方式无法支持对应其他配置方法如setState

### ISSUE THREAD

**Issue by lulei90** [antvis/G6#2051]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现在使用JSX方式自定义节点无法设置其他相关配置方法

### What does the proposed API look like?
G6.registerNode("xxx", {
  draw（cfg，group）{
   retrun JSX
 },
 ...
}）

**Comment by Yanyan-Wang** [comment]
可以的啊，只要你在  JSX 的定义里面使用相应的样式字段。

另外，能用 Graph 上的 API 就不要用 item 自己的 API。比如 setState 应该使用 graph.setItemState

**Comment by lulei90** [comment]
> 可以的啊，只要你在 JSX 的定义里面使用相应的样式字段来绘制。
> 
> 另外，能用 Graph 上的 API 就不要用 item 自己的 API。比如 setState 应该使用 graph.setItemState

我看了Shape的源码，如果第二配置项使用的是字符串或方法，是没有办法再去设置例如afterDraw，和setState方法的
![image](https://user-images.githubusercontent.com/10334832/92470160-9ca5e780-f208-11ea-83c3-2a27cd8bb8a0.png)
