### ISSUE TITLE
使用registerNode自定义节点时，如果采用JSX形式，无法设置afterDraw、setState等配置

### ISSUE THREAD

**Issue by lulei90** [antvis/G6#2055]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
支持registerNode在采用JSX的形式时能设置对应的其他钩子函数、如afterDraw、update、setState...等
![image](https://user-images.githubusercontent.com/10334832/92471330-59e50f00-f20a-11ea-860e-fc30f6028191.png)

### What does the proposed API look like?
G6.registerNode("relationship",cfg=>jsx,{afterDraw(){...},setState(){...}},'extendedNodeName')

**Comment by mxz96102** [comment]
你好，能了解一下具体的使用场景吗，我这里看一下怎么透出这个钩子函数比较好呢

**Comment by lulei90** [comment]
> 你好，能了解一下具体的使用场景吗，我这里看一下怎么透出这个钩子函数比较好呢

采用JSX设置的自定义节点，想去通过设置对应的节点状态去触发一些对应的节点动画和样式调整，由于使用了JSX的方式导致无法定义其对应的钩子函数，现在只能通过循环查找节点后挨个去设置

**Comment by mxz96102** [comment]
好的，我会尽快开发透出这几个函数，当初没有考虑到太自由的使用场景

**Comment by lulei90** [comment]
> 好的，我会尽快开发透出这几个函数，当初没有考虑到太自由的使用场景

并且貌似使用JSX自定义的节点，无法显示的设置`draggable:false` `visible:false`等配置，现在是想在初始化阶段通过对应数据配置项来显示或隐藏部分信息，在使用JSX时发现无法实现
```jsx
<text name="text" visible="false">xxx<text>
````

**Comment by mxz96102** [comment]
应该是因为转换的问题，visible="", draggable=""的时候才会起效，感谢你的反馈，尽快处理一下

**Comment by mxz96102** [comment]
#2092

**Comment by mxz96102** [comment]
#2092 在这里解决了～

**Comment by baizn** [comment]
更新到 3.8.0 版本
