### ISSUE TITLE
节点动画和drag-canvas、zoom-canvas、drag-node等配合使用时bug

### ISSUE THREAD

**Issue by lulei90** [antvis/G6#2056]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/modest-goldwasser-4247p?file=/index.js:6429-6470)

### Steps to reproduce
拖拽画布或者放大，当节点超过显示区后再通过拖拽或者缩小让节点重新回到可视区后，非动画节点和边会不显示
操作过程如下：
![test](https://user-images.githubusercontent.com/10334832/92475493-0ecdfa80-f210-11ea-87be-2f519f9e6ae4.gif)
正常情况如下：
![image](https://user-images.githubusercontent.com/10334832/92475111-733c8a00-f20f-11ea-9efb-d1d42ec7a750.png)
通过放大让图超过显示区，然后通过缩小让图重新回到可视区后：
![image](https://user-images.githubusercontent.com/10334832/92475190-9109ef00-f20f-11ea-8f5a-419a1b03146e.png)

| Environment | Info |
|---|---|
| g6 | 3.7.1 |
| System | - |
| Browser | - |

**Comment by Yanyan-Wang** [comment]
合并到 #2031
