### ISSUE TITLE
Incorrect polyline edge path in dagre layout with custom dom node

### ISSUE THREAD

**Issue by bohdanzhylavskyi** [antvis/G6#2057]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/bosco/pen/bGpLRaj](https://codepen.io/bosco/pen/bGpLRaj)

### Steps to reproduce
Just look at it

| Environment | Info |
|---|---|
| g6 | 3.7.1 |
| System | Windows 10 |
| Browser | Chrome |

**Comment by Yanyan-Wang** [comment]
The edge paths look correct. But it seems that nodes are clipped. Is it the problem you mean?

**Comment by bohdanzhylavskyi** [comment]
If i use that code but with default node, i have that result:
![image](https://user-images.githubusercontent.com/12056012/92501348-15a43f80-f207-11ea-8a41-5f5522e29d63.png)
As you can see, edge is correct on that picture, but if I use custom dom node, the edge looks different (picture in previous post)

**Comment by Yanyan-Wang** [comment]
It is caused by the wrong origin of the custom node, replace the addShape part by:
```
        const shape = group.addShape('dom', {
          attrs: {
            x: -cfg.size[0]/2, // move the shape to make the center of the DOM rect align to the origin of the custom node
            y: -cfg.size[1]/2, // move the shape to make the center of the DOM rect align to the origin of the custom node
            width: cfg.size[0],
            height: cfg.size[1],
            html: `
                <div class='my-node'></div>
            `
          }
      });
```

**Comment by bohdanzhylavskyi** [comment]
it's working, thank you
