### ISSUE TITLE
Incorrect arrows if using svg renderer

### ISSUE THREAD

**Issue by bohdanzhylavskyi** [antvis/G6#2059]
Please, look at demo: [https://codepen.io/bosco/pen/mdPXxBw](https://codepen.io/bosco/pen/mdPXxBw). If use default renderer (not svg), arrows are painting correctly.

**Comment by Yanyan-Wang** [comment]
The coordinate system of the arrows in SVG renderer is inverse comparing to canvas renderer, try the path `'M 0,0 L -8,4 L -8,-4 Z'` instead. And there are some other problems in svg arrow, e.g. `fill` in style does not take effect.

We suggest to use the Canvas renderer instead, which has better performance and less bugs.

**Comment by bohdanzhylavskyi** [comment]
It is working, thanks
