### ISSUE TITLE
TreeGraph自定义树图，怎么才能拖动节点

### ISSUE THREAD

**Issue by sjh0824** [antvis/G6#2060]
官方案例中 https://g6.antv.vision/zh/examples/tree/customItemTree
怎样拖动节点，位置随意变化
找了文档没有找到

这个可以实现吗，如果可以怎么才能？

![image](https://user-images.githubusercontent.com/18656791/92563615-6caf2080-f2aa-11ea-9319-1f98aeb62154.png)

**Comment by Yanyan-Wang** [comment]
'drag-node' 内置交互，实例化图时配置在 modes 的 default 里，和 drag-canvas 类似 
https://g6.antv.vision/zh/docs/manual/middle/states/defaultBehavior/#drag-node
