### ISSUE TITLE
打包后出错

### ISSUE THREAD

**Issue by xuedaobian** [antvis/G6#2061]
- **G6 Version**: 3.7
打包后引入g6出错，但未在控台打印，跟踪到的。
引入方式是 
` import G6 from '@antv/g6'` 
造成该组件空空如也
救救

**Comment by Yanyan-Wang** [comment]
node_modules 里面确定安装了吗

**Comment by xuedaobian** [comment]
确定的，开发环境没有问题，build之后才出错了
![image](https://user-images.githubusercontent.com/38198170/92581826-bf94d200-f2c2-11ea-9303-bf9e2e7b5bb5.png)

**Comment by xukanfeng1989** [comment]
可能是在生产环境用UglifyJsPlugin压缩后引起的

**Comment by Yanyan-Wang** [comment]
报错内容贴一下

**Comment by xuedaobian** [comment]
不明白为什么，再次打包又恢复了，有点玄学了
