### ISSUE TITLE
自定义节点由多个Shape组成，右键菜单如何定位鼠标所在位置的Shape

### ISSUE THREAD

**Issue by gaoxs1985** [antvis/G6#2063]
- **G6 Version**:3.7.0
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

自定义节点添加了多个shape，需求是不同的shape右键菜单相同选项的执行逻辑不相同，
现在的menu菜单的getContent(e)方法中，e.target是能获取到鼠标所在的shape，但在handleMenuClick中就无法获得了，能否提供一个解决思路？
谢谢

**Comment by Yanyan-Wang** [comment]
那么不同 shape 返回的 getContent 就应该不相同。handleMenuClick 相当于已经是对当前菜单的 DOM 的操作了

**Comment by gaoxs1985** [comment]
示例代码：https://codepen.io/gaoxs1985/pen/OJNvKJv
示例为类似ER图，想法是在字段上通过右键删除对应字段，需要删除整行，现在的处理方式是通过在字段shape上存储索引信息，在getContent中动态添加操作索引作为code，handleMenuClick 通过索引判断需要操作的内容，个人觉得这个处理逻辑很笨重，是否有更好的处理思路？

**Comment by Yanyan-Wang** [comment]
这个方法也没什么问题。再简单点的方法可能就是有一个全局变量，在 shouldBegin 或者 getContent 里面记录当前点击的 shape，然后在 handleMenuClick 中根据这个全局变量来删除。

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
