### ISSUE TITLE
使用changeData后有有一条边渲染不出来

### ISSUE THREAD

**Issue by Elias-cug** [antvis/G6#2064]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vigilant-lamarr-b97in?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
graph.changeData(this.topoData2)

| Environment | Info |
|---|---|
| g6 | 3.7.1 |
| System | win10 |
| Browser | 谷歌83.0.4103.97 |

**Comment by Yanyan-Wang** [comment]
因为第一份数据 topoData 里设置了 E002 这条边的 opacity 是 0

**Comment by Elias-cug** [comment]
感谢回答，我把 topoData2 中 节点 id 和 边 id 换成和 topoData 中不一样的 id 解决了这个问题。就是说之前的数据会对change后的数据带来影响（现在情况是id一样会带来问题）。然后，改正之后还出现的一个问题是，我反复changData(topoData) changeData(topoData2) 时 这样的话运行时出现了错误，TypeError: Cannot read property 'destroyed' of undefined"和Cannot read property 'hasState' of undefined。我在上面的demo链接做了修改，可以查看。

**Comment by Yanyan-Wang** [comment]
这个问题应该是切换数据时带有 combo 的边造成的 bug，下个小版本修复。

另外，看到你 demo 里面的 TODO 要切换成 svg，用 renderer: 'svg' ，小写的 svg 就可以。不过还是建议使用 canvas。svg 的性能差而且渲染上会有一些问题
