### ISSUE TITLE
通过监听控制边上鼠标的状态，鼠标移入可以改变状态，鼠标移除无法改变状态

### ISSUE THREAD

**Issue by gaoxs1985** [antvis/G6#2066]
- **G6 Version**:3.7.0
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

Demo
https://codepen.io/gaoxs1985/pen/ExKEmxb

**Comment by Yanyan-Wang** [comment]
graph.update 里面去更新边的样式，cursor 指的就是鼠标在边上的样式，出来以后鼠标就不在边上了。可以通过以下方式复原：
```
graph.get('canvas'),setCursor('default')
```
