### ISSUE TITLE
图搜索：搜素到指定节点居中高亮显示

### ISSUE THREAD

**Issue by crystalwm** [antvis/G6#2068]
**需求：**
在搜索框中输入查询，会出来一个搜索结果的list，然后从list中选择一条记录。 graph中会把选择的节点高亮和居中显示。（类似于搜索地图信息的workflow）

**问题：**
搜索到节点，高亮这个状态可以做到。
**但是居中显示有什么办法吗？有什么好的建议？**

我目前想到的一种方案是结合leaflet，还没有尝试过，不知道是否可以成功

**Comment by Yanyan-Wang** [comment]
https://g6.antv.vision/zh/examples/interaction/position

**Comment by Woomay** [comment]
搜索节点是需要自己自定义toolbar组件么

**Comment by daidaic** [comment]
搜索到节点高亮怎么做到的啊

**Comment by daidaic** [comment]
搜索到节点高亮怎么做到的啊
