### ISSUE TITLE
火狐使用group.addShapeup添加image图片不显示

### ISSUE THREAD

**Issue by jinyutao0818** [antvis/G6#2070]

**Comment by Yanyan-Wang** [comment]
请提供复现在线 demo，否则我们难以排查原因，该 issue 将会被关闭。

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
