### ISSUE TITLE
Drag canvas or nodes out of range. The custom shape disappeared

### ISSUE THREAD

**Issue by qunzi0214** [antvis/G6#2072]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/qunzi0214/vue-g6-editor](https://github.com/qunzi0214/vue-g6-editor)

### Steps to reproduce
1. git clone https://github.com/qunzi0214/vue-g6-editor
2. npm install 
3. npm run serve
4. drag node or canvas  out of range
5. the shape disappeared

| Environment | Info |
|---|---|
| g6 | 3.7.1 |
| System | - |
| Browser | - |

---
- performance right in antv/g6@3.6.1 
- performance wrong in antv/g6@3.6.2

**Comment by Yanyan-Wang** [comment]
please provide a minimum show case.

**Comment by qunzi0214** [comment]
> please provide a minimum show case.

Here is the minimum show case.

https://github.com/qunzi0214/g6-issue-demo.git

i think the problem is cause by animated shape

`` /src/g6-config/customNode.js:76 `` - `` /src/g6-config/customNode.js:95 ``
