### ISSUE TITLE
需求：不用svg渲染的方式，node里要展现带滚动条的div如何实现

### ISSUE THREAD

**Issue by zfen0913** [antvis/G6#2073]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

- **G6 Version**:3.7.1
- **Platform**:与平台无关
- **Mini Showcase(like screenshots)**:
1、一个rect节点，左键单击需唤出另一个节点，该节点内有一个可能比较长的列表，需要滚动条展示，点击里面的列表项会对图上其他元素交互
2、我在svg渲染模式下实现dom节点，可以实现第1点的需求，但我的数据量比较大，svg性能没有canvas好，canvas模式下有什么办法可以画出这样的图形吗
3、本想用上下文菜单，但这个只能右键唤出，我需要左键单击，且节点添加后，需点击节点里的元素，与图中其他元素交互

请问canvas模式下是否有办法实现该需求？
本想上传图片，奈何一直传不上去....

**Comment by baizn** [comment]
应该是实现不了类似 DOM 中滚动条效果的，但可以以下两种方式来实现：
1、滑动加载数据；
2、列表底部加一个加载更多按钮，点击加载数据。

节点中不同部分的点击是可以区分开的，具体参考这个DEMO：https://g6.antv.vision/zh/examples/interaction/partialResponse

**Comment by Yanyan-Wang** [comment]
还可以参考右键菜单的形式，监听 graph.on('node:click' 显示一个类似菜单的带滚动条的悬浮 DOM。悬浮 DOM 挂载方式参考 https://www.yuque.com/antv/g6-blog/gp2dxk

**Comment by zfen0913** [comment]
> 还可以参考右键菜单的形式，监听 graph.on('node:click' 显示一个类似菜单的带滚动条的悬浮 DOM。悬浮 DOM 挂载方式参考 https://www.yuque.com/antv/g6-blog/gp2dxk

谢谢，这样确实可以实现显示带滚动条的div，但有个问题，悬浮的dom无法根据画布的缩放而变化。当我设置了graph为fitView: true时，无法获取节点缩放后的尺寸，只能设置悬浮的dom的宽度为节点原始宽度，有点突兀。

但也是一种解决方案，非常感谢！

**Comment by zfen0913** [comment]
> 应该是实现不了类似 DOM 中滚动条效果的，但可以以下两种方式来实现：
> 1、滑动加载数据；
> 2、列表底部加一个加载更多按钮，点击加载数据。
> 
> 节点中不同部分的点击是可以区分开的，具体参考这个DEMO：https://g6.antv.vision/zh/examples/interaction/partialResponse

谢谢！
1、滑动加载数据具体指什么呢？监听鼠标滚轮事件？
2、我通过在列表底部加了两个翻页的按钮，再监听按钮点击事件来刷新节点里具体内容，实现了这个功能，非常感谢！
