### ISSUE TITLE
Comments in English

### ISSUE THREAD

**Issue by GrandSchtroumpf** [antvis/G6#2074]
- [X] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.
(I'm sorry if this issue has already been raised, but as issues are also in Chinese, I cannot say if it's the case...)

### What problem does this feature solve?
When overring the methods & properties, comments displayed by vscode are in Chinese.

### What does the proposed API look like?
Write comments in English.

**Comment by Yanyan-Wang** [comment]
Thanks, we will supplement the English version comments incrementally.
