### ISSUE TITLE
自定义节点无法通过node:mouseenter改变鼠标样式吗？

### ISSUE THREAD

**Issue by gaoxs1985** [antvis/G6#2075]
- **G6 Version**:3.7.0
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

https://codepen.io/gaoxs1985/pen/LYNmEve
还是需要其他特殊配置？

**Comment by baizn** [comment]
节点是自定义的，那就需要把传进去的属性在定义的时候用到
![image](https://user-images.githubusercontent.com/9443867/93035232-0beb6380-f66f-11ea-9eda-27c10e30a12f.png)
