### ISSUE TITLE
更新节点样式问题

### ISSUE THREAD

**Issue by YC725968** [antvis/G6#2076]
在上个版本3.中，更新节点样式没问题，在3.7.1中，更新节点的样式无法立即变更，只有在点击下一个节点时才会更新上一个节点的样式。更新size可以立即更新，更新样式必须点击下一个节点时才会更新！有解决办法吗？
 changeColor() {
      console.log('nodeitem', this.evitem)
      const autoPaint = this.graph.get('autoPaint')
      this.graph.setAutoPaint(false)
      this.graph.updateItem(this.evitem, {
        style: {
          fill: 'red',
          lineWidth: 6,
        },
        // size:80
      }),
      this.graph.paint()
      this.graph.setAutoPaint(autoPaint)
      this.dialogVisible = false
      this.evitem = {}
    },

**Comment by baizn** [comment]
能提供个可以复现的demo吗？ 
我在官网 DEMO 上试了没问题的
![image](https://user-images.githubusercontent.com/9443867/93034884-1d803b80-f66e-11ea-884c-1fd23ea0e4bf.png)

**Comment by YC725968** [comment]
你好,我的项目是vue的，在上面的例子中，颜色已经获取到了，节点的大小可以更新，但是就是style不起作用，这个是上面问题呢？上个版本没问题，在线的vue有点不好构造啊。。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/G6"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月14日(星期一) 上午9:39
收件人:&nbsp;"antvis/G6"<G6@noreply.github.com&gt;;
抄送:&nbsp;"奋斗小青年"<1003190045@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [antvis/G6] 更新节点样式问题 (#2076)





 
能提供个可以复现的demo吗？
 我在官网 DEMO 上试了没问题的

**Comment by YC725968** [comment]
你好，找到原因了！在次感谢！！

**Comment by YC725968** [comment]
点击更改节点填充颜色，在双击更改节点填充颜色，不不会立即更改

**Comment by lovexp1** [comment]
我也遇到这个问题了，请问是什么原因呢？ @YC725968
