### ISSUE TITLE
IE11 fruchterman workerEnabled 不渲染

### ISSUE THREAD

**Issue by shuihan03** [antvis/G6#2077]
- **G6 Version**: 3.7.1
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

IE 11 fruchterman 在配置workerEnabled=true时绘制不出图形，workerEnable=false时，虽然卡顿，但是能渲染出图形。
chrome都可以正常渲染图形。

**Comment by Yanyan-Wang** [comment]
IE 11 有些 worker 特性不支持
![image](https://user-images.githubusercontent.com/29593318/93038160-d34f8800-f676-11ea-94f1-e8d0e996ce68.png)
