### ISSUE TITLE
node的mousedown事件，如何区分按下的是左键还是右键

### ISSUE THREAD

**Issue by MYSUMMERLORD** [antvis/G6#2079]
- **G6 Version**: 3.6.1
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

![image](https://user-images.githubusercontent.com/9947530/93037943-3a207180-f676-11ea-8277-6bd4651e78d8.png)
如题，希望收到大佬回复，谢谢

**Comment by Yanyan-Wang** [comment]
你的原始需求是什么？如果你是想监听点击事件，左键是 node:click， 右键可以用 node:contextmenu 监听。

**Comment by MYSUMMERLORD** [comment]
原始需求就是监听mousedown左键按下的事件，作为连线的起点。

**Comment by MYSUMMERLORD** [comment]
右键也已经监听了，做了其他功能

**Comment by MYSUMMERLORD** [comment]
node:contextmenu 已经监听了，做了其他功能。

**Comment by MYSUMMERLORD** [comment]
目前就是因为发现mousedown右键按下的时候，也触发了作为连线起点这个功能，以及node:contextmenu这个事件，所以才想用mousedown事件只监听左键，让事件和功能做到一一对应

**Comment by Yanyan-Wang** [comment]
事件参数里有一个 defaultPrevented 对象，可以用里面的 button 判断，对应关系参考 https://blog.csdn.net/hustlick0/article/details/27888067
