### ISSUE TITLE
TreeGraph使用updateItem更新节点信息时，位置会变更

### ISSUE THREAD

**Issue by xxxgitone** [antvis/G6#2082]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/frosty-river-49869?file=/index.js)

### Steps to reproduce
我将官网的一个例子中增加节点操作，改成变更文本操作，点击后，发现节点位置会变更。

![image](https://user-images.githubusercontent.com/19681723/93050887-3ac90000-f696-11ea-8e0f-05be894213c4.png)

| Environment | Info |
|---|---|
| g6 | 3.6.1 |
| System | mac 10.15.5 |
| Browser | chrome 85 |

**Comment by Yanyan-Wang** [comment]
可将自定义节点的 udpate 函数复写为 undefined，否则会使用被继承的父类的 update 函数来更新节点。

另外，自定义节点的 keyShape 为 rect 时，最好将 x y 各减去宽高一半，让节点的自身坐标系原点对齐 rect 的中心位置（x:0 y:0 时，节点自身坐标系原点在 rect 左上角）

**Comment by xxxgitone** [comment]
@Yanyan-Wang 非常感谢
