### ISSUE TITLE
【bug】toolbar 放大缩小后，undo后，节点/边 形状丢失

### ISSUE THREAD

**Issue by xiaofengqqcom123** [antvis/G6#2084]
demo：https://codesandbox.io/s/laughing-almeida-z9rhh?file=/src/index.js

操作：
点击toolbar中的，放大缩小
点击“重做”；图形删除
点击“撤销”；页面恢复的形状为圆形（默认值）
![image](https://user-images.githubusercontent.com/29247931/93056035-6bad3300-f69e-11ea-89b2-e0ba0d04f1b4.png)

**Comment by Yanyan-Wang** [comment]
谢谢，下个版本解决

**Comment by Yanyan-Wang** [comment]
3.7.3 已修复
