### ISSUE TITLE
画布更新布局以后，调用fitCenter 无效

### ISSUE THREAD

**Issue by LincolnPack** [antvis/G6#2085]

**Comment by LincolnPack** [comment]
graph.updateLayout(layout);  之后，调用 graph.fitCenter(); 无效

**Comment by Yanyan-Wang** [comment]
请提供复现在线 demo

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。

**Comment by damaohub** [comment]
> graph.updateLayout(layout); 之后，调用 graph.fitCenter(); 无效
解决了吗？遇到了同样的问题
