### ISSUE TITLE
Not the same vertical distance between a node of  neighbor level  and edge from node to node of not neighbor level (polyline edge type)

### ISSUE THREAD

**Issue by bohdanzhylavskyi** [antvis/G6#2086]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/bosco/pen/LYNrjEV](https://codepen.io/bosco/pen/LYNrjEV)

### Steps to reproduce
Run demo

| Environment | Info |
|---|---|
| g6 | 3.7.2 |
| System | Windows 10 |
| Browser | Chrome |

---
As you can see, here vertical distance between the edge from node1 to node4 is not the same as the vertical distance of edge from node1 to node2 (or from node2 to node4). Is it possible to make that distance equals (for polyline edge type), or I need to implement a custom edge type?

**Comment by Yanyan-Wang** [comment]
The edge's bending positions depend on the controlPoints which is automatically calculated by the dagre layout with `controlPoints: true`. So we'd better to find another way to achieve the requirement.

The space between nodes with same level can be adjusted by `nodesepFunc` which is a configuration of dagre. Try to custom the return value according to the node data, e.g.

```
nodesepFunc: (d) => {
      if (d.id === '3') return 80;
      return -20;
    },
```

**Comment by bohdanzhylavskyi** [comment]
Thanks. Would be good to have that behaviour by default
