### ISSUE TITLE
Provide the complete list of events

### ISSUE THREAD

**Issue by GrandSchtroumpf** [antvis/G6#2087]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Types don't provide the complete list of events. And documentation seems not to be up-to-date.

### What does the proposed API look like?
As it's super difficult to maintain documentation up to date, using types is a better solution to provide inline documentation.
You can use string literal to define the complete list of event : 
```typescript
const events = ['click', 'node:click', 'edge:click', 'aftercreateedge', ...] as const;
type Events = (typeof events)[number];

// Graph class : 
class Graph ... {
  on(event: Events, callback: Function)
}
```
Or even better : 
```typescript
interface EventMap {
  click: (event: IG6GraphEvent) => void;
  aftercreateedge: (event: { edge: EdgeConfig }) => void;
  ...
}
const events: Readonly<Extract<keyof EventMap, string>[]>  = ['click', 'node:click', 'edge:click', 'aftercreateedge', ...] as const;

// Graph class : 
class Graph ... {
  on<E extends Extract<keyof EventMap, string>>(event: E, callback: EventMap[E]);
}
```

**Comment by Yanyan-Wang** [comment]
Thanks, we will improve it soon.

**Comment by Yanyan-Wang** [comment]
Here goes the list: https://g6.antv.vision/en/docs/api/Event

**Comment by GrandSchtroumpf** [comment]
Thanks, this list doesn't include event like `aftercreateedge` for example. Now, I know I have to look into the Built-in Behavior page to find them. But it took me half a day to find out it was there, and I'm not even sure I cover all events with these two pages.
Don't get me wrong, the documentation is already amazing and I'm impressed how complete it is. But I think using string literals would make your life easier 😉

**Comment by Yanyan-Wang** [comment]
Yes, that's true. Thanks again.

**Comment by Yanyan-Wang** [comment]
We have improved the documents and completed event docs. But for the event ts types, since the Event name can be custom type like 'xxx-shape-name:mouseenter' or 'myxxxevent', it is not enumerable.

Thanks for your suggestions. And welcome to create issues for more advices.

**Comment by GrandSchtroumpf** [comment]
Thanks, maybe the new Template String literal from Typescript 4.1 could help generating the string's names : 
https://devblogs.microsoft.com/typescript/announcing-typescript-4-1-beta/#template-literal-types
You could have something like 
```typescript
type Shapes = 'node' | 'edge' | ...;
type Events = 'mouseenter' | ...;
type AllEvents = `${Shapes}:${Events}`; // 'node:mouseenter' | 'edge:mouseenter' | ...
```
