### ISSUE TITLE
Bug：graphic.js内的扩展运算符报错

### ISSUE THREAD

**Issue by Kellercai** [antvis/G6#2089]
- 版本：
   - G6：3.1.3
   - babel-loader：^7.1.1
   - webpack: ^3.6.0
   - vue: ^2.5.2
- 报错日志：
```
 error  in ./node_modules/@antv/g6/src/util/graphic.js

Module parse failed: Unexpected token (247:8)
You may need an appropriate loader to handle this file type.
|       return {
|         rotate: rad,
|         ...result
|       };
|     }
```
- 暂时的解决方式：
https://github.com/antvis/G6/blob/f2eef8e59107f92f71e7c47cfa73635bb9fc2b14/src/util/graphic.ts#L273-L287

将以上代码的```...result```改为result的所有属性值赋值。

- 期望：
正常编译成功

**Comment by Yanyan-Wang** [comment]
这个应该是你的项目 webpack 的配置问题，支持 `...` 这样的扩展运算符即可

**Comment by Kellercai** [comment]
> 这个应该是你的项目 webpack 的配置问题，支持 `...` 这样的扩展运算符即可

应该不是我项目webpack中的问题，目前项目中使用扩展运算符正常，使用其他第三方的扩展运算符也是正常的

.babelrc
```
{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "browsers": ["> 1%", "last 2 versions", "not ie <= 8"]
      }
    }],
    "stage-2"
  ],
  "plugins": ["transform-vue-jsx", "transform-runtime"]
}
```

**Comment by Yanyan-Wang** [comment]
那 G6 很多其他地方都用了 `...` 没有报错吗。要不你试一下引用 es 产物

```
import G6 from '@antv/g6/es';

```

**Comment by Kellercai** [comment]
> 那 G6 很多其他地方都用了 `...` 没有报错吗。要不你试一下引用 es 产物
> 
> ```
> import G6 from '@antv/g6/es';
> ```

![image](https://user-images.githubusercontent.com/20681598/93195318-b0f36280-f77b-11ea-896c-3929f1c3a573.png)
引用没有这个模块哦，是不是版本不一样呢？目前就发现g6下的那个文件有报这个问题，其他的都是正常的

**Comment by longxiaofei** [comment]
Hi, 最后是通过什么方式解决的呢？

**Comment by Kellercai** [comment]
> Hi, 最后是通过什么方式解决的呢？

暂时无法解决该问题，只能通过手动更改那个文件的```...result```扩展运算符为普通属性值

**Comment by longxiaofei** [comment]
> > Hi, 最后是通过什么方式解决的呢？
> 
> 暂时无法解决该问题，只能通过手动更改那个文件的`...result`扩展运算符为普通属性值

1. 添加全局的babel配置，babel.config.js文件
```
module.exports = {
  presets: [
    '@vue/app'
  ]
}
```

2. 检查webpack的配置，确定`babel-loader`会编译`node_modules/@antv/g6`里的.js文件
3. `npm run serve`根据提示缺啥装啥。

**Comment by Kellercai** [comment]
> > > Hi, 最后是通过什么方式解决的呢？
> > 
> > 
> > 暂时无法解决该问题，只能通过手动更改那个文件的`...result`扩展运算符为普通属性值
> 
> 1. 添加全局的babel配置，babel.config.js文件
> 
> ```
> module.exports = {
>   presets: [
>     '@vue/app'
>   ]
> }
> ```
> 
> 1. 检查webpack的配置，确定`babel-loader`会编译`node_modules/@antv/g6`里的.js文件
> 2. `npm run serve`根据提示缺啥装啥。

谢谢您的解答，但是这种方式我先前尝试几次都是没有办法解决的。
