### ISSUE TITLE
能否设置node的comboId不改变（node不能拖出当前combo）

### ISSUE THREAD

**Issue by miaopassi** [antvis/G6#2090]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在需要对combo中的节点进行手动布局，并且不希望改变节点的comboId时，使用现有的方法是将节点在已渲染出来的combo中进行小范围拖拽操作，如果在调整过程中combo的范围缩小，那么再次调整节点位置时，对于经常自定义节点位置的用户来说体验不佳。
期望实现：在拖拽combo中的节点时，不改变comboId，根据节点的新布局来动态改变combo的区域。

### What does the proposed API look like?
可选combo的某一属性，设置comboId不改变，实现后在现有的功能基础上，就自然实现了根据combo中的节点布局自适应完成combo的更新。

**Comment by miaopassi** [comment]
此外，能否支持在此情形下，设置combo之间不可嵌套呢，即combo之间互斥

**Comment by Yanyan-Wang** [comment]
drag-node 有一个 `onlyChangeComboSize` https://g6.antv.vision/zh/docs/manual/middle/states/defaultBehavior#drag-node

**Comment by miaopassi** [comment]
> drag-node 有一个 `onlyChangeComboSize` 参数就是干这个的 https://g6.antv.vision/zh/docs/manual/middle/states/defaultBehavior#drag-node

好的，谢谢。
