### ISSUE TITLE
可以通过获取 canvas 对象，自己绘制节点样式吗？如果可以在哪里能获取到 canvas 对象？

### ISSUE THREAD

**Issue by Elias-cug** [antvis/G6#2093]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
更个性化绘制节点，而不是内置节点的拼接

### What does the proposed API look like?
希望可以在 afterDraw(cfg, group) 这里获取 当前节点或者边的 canvas 对象。操作 canvas 实现自己的绘制

**Comment by Yanyan-Wang** [comment]
什么是内置节点的拼接？group.addShape 可以添加任意图形，相当于自己绘制了呀。提供的 shape 有 https://g6.antv.vision/zh/docs/api/nodeEdge/shapeProperties

**Comment by Elias-cug** [comment]
比如我想自定义一个节点，节点的描边需要不同的颜色。而stroke只能最多提供渐变，如果能像canvas那样操作，就很方便。

**Comment by Yanyan-Wang** [comment]
添加 path 也是一样的吧

**Comment by Elias-cug** [comment]
是一个边上，需要绘制不同的颜色段。类似于一个边上一部分stroke是白色，一部分是黑色。所以需要画两个半径、位置相同的不完整圆，拼起来。我现在在看svg里面的path可以不可以解决。现在有一个需求就是通过边颜色的占比，表示服务器的拥挤情况。

**Comment by Yanyan-Wang** [comment]
canvas 也有 path 图形的。svg 性能不如 canvas

**Comment by Elias-cug** [comment]
是的我想用canvas的path画，但是我获取不到canvas对象，没法操作。api文档只有 svg path的api。所以我开始问afterDraw(cfg, group)这个默认传参能获取节点的canvas重新绘制吗

**Comment by Yanyan-Wang** [comment]
不是的呀，G6 使用 canvas 渲染引擎的情况下，也可以添加 path 图形：

group.addShape('path', {
  attrs: {
    //... 其他属性
    path: ...
    stroke: ...
  }
}

**Comment by Elias-cug** [comment]
是的我看的就是这个，但是文档给的配置是参考svg。

path | String / Array | 线条路径，可以是 String 形式，也可以是线段的数组。格式参考：SVG path
-- | -- | --

**Comment by Yanyan-Wang** [comment]
是的，只是说格式参考 svg，如果实例化图的时候配置了 renderer: 'canvas' 或没有配置 renderer，这个最终会使用 canvas 绘制

**Comment by Elias-cug** [comment]
好的，还是觉得能获取到节点或边的一个画布对象比较好，这样的话就可以使用很多属性，来完全用canvas或者svg的方式画图

**Comment by Yanyan-Wang** [comment]
这些都被封装了，如果你拿到画布对象自己去画的话，上层没办法管理的。addShape 基本上就和用画布对象画差不多了

**Comment by Elias-cug** [comment]
好的，了解了

**Comment by baizn** [comment]
> 是的我想用canvas的path画，但是我获取不到canvas对象，没法操作。api文档只有 svg path的api。所以我开始问afterDraw(cfg, group)这个默认传参能获取节点的canvas重新绘制吗

graph.get('canvas') 就获取到 Canvas 对象了，但通过 group.addShape() 效果和通过Canvas绘制一样的
