### ISSUE TITLE
如何动态修改一个节点样式?

### ISSUE THREAD

**Issue by ShikiRyougi** [antvis/g6#21]
我希望点击一个节点改变这个节点的一些样式 onClick事件里应该怎样写呢?是改变节点属性然后graph.refresh/update吗？
最开始我的想法是graph.edge().style('id', id => id === activeId ? 'custom-style': '')
但是发现我在onClick里面写什么都不会重新设置一遍style
现在有点蒙 不知道应该是具体用什么思路搞这件事

**Comment by TomHuangCN** [comment]
你的是rerender的思路。数据模型里是支持设置style的 
```js
onClick(function(ev){
  net.update(ev. {
    style: {}
  });
});
```
