### ISSUE TITLE
使用Canvas节点如何实现复杂的布局，并能实现友好的交互

### ISSUE THREAD

**Issue by JacobYChan** [antvis/g6#210]
HTML节点可扩展性强，能实现比较好的交互，但是缩放功能比较受限，于是想到了canvas节点，但是canvas节点使用比较受限制，怎么能实现复杂一点的布局呢，又能交互起来，比如下图：

文字布局比较多，样式也不一样，然后能点击+弹出自定义菜单
<img width="593" alt="2018-04-10 9 30 13" src="https://user-images.githubusercontent.com/18413888/38531458-7573c1b4-3ca2-11e8-87ca-75e8048e35b2.png">

**Comment by zx8887** [comment]
```javascript
    /* 节点图形注册 */
    registerNodes() {
      let _this = this;
      G6.registerNode("appNode", {
        draw(cfg, group) {
          const model = cfg.model;
          let appColor = _this.getColor(model.status);
          let size = cfg.size;
          let aWidth = 80;
          let aHeigth = 80;
          if (size) {
            aWidth = aHeigth = size[0] > size[1] ? size[0] : size[1];
            aWidth = size[0];
            aHeigth = size[1];
          }
          const shape = group.addShape("rect", {
            attrs: {
              x: cfg.x,
              y: cfg.y,
              width: aWidth,
              height: aHeigth,
              radius: 10,
              fill: appColor,
              fillOpacity: model.highlight ? 0.3 : 0.05,
              stroke: appColor
            }
          });
          group.addShape("html", {
            attrs: {
              width: aWidth,
              height: aHeigth,
              color: appColor,
              padding: "10px",
              boxShadow: model.highlight ? `0 0 12px 0 ${appColor}` : "",
              html: this.getHtml(cfg)
            }
          });
          return shape;
        },
        getHtml(cfg) {
          const model = cfg.model;
          let icon = _this.getIconByType(model.type);
          let color = _this.getColor(model.status);
          let fontSize = model.fontSize || 12;
          const dom = G6.Util.createDOM(
            `<div class="draw-graph-app">
                  <svg class="draw-graph-app-icon" aria-hidden="true">
                    <use xlink:href="#${icon}" fill="${color}"></use>
                  </svg>
                  <div class="draw-graph-app-text" style="font-size:${fontSize}px">
                    ${model.text}
                  </div>
              </div>`
          );
          return dom;
        },
        afterDraw(cfg, group, keyShape) {},
        getAnchorPoints() {
          return [
            [0, 0.25],
            [0, 0.5],
            [0, 0.75],
            [1, 0.25],
            [1, 0.5],
            [1, 0.75],
            [0.25, 0],
            [0.5, 0],
            [0.75, 0],
            [0.25, 1],
            [0.5, 1],
            [0.75, 1]
          ];
        }
      });
    }
..........
```
```javascript
 /* 右键菜单处理 */
      this.g6Obj.on("contextmenu", function(ev) {
        let type = ev.itemType;
        if (type === undefined || type === "node") {
          let appMenuRef = _this.$refs.appMenu;
          if (type === undefined) {
            appMenuRef = _this.$refs.graphMenu;
          }
          let appMenuDom = appMenuRef.$el;
          let domEvent = ev.domEvent;
          appMenuDom.children[0].style.left = domEvent.x + "px";
          appMenuDom.children[0].style.top = domEvent.y + "px";
          if (type === undefined) {
            _this.graphMenuShow = true;
          } else {
            _this.appSelected = ev.item;
            _this.appMenuShow = true;
          }
        }
      });
```
刚好我研究出来了，我的做法是先画canvas节点，然后再画html节点，完美实现各种扩展要求，还有菜单那个得监听当前鼠标的坐标。给你代码片段你自己发挥你的想象吧。。。。
真心期待G6的开发人员能写出一些复杂的DEMO，或者是完善下api。。。这些东西我各种控制台里面打出来研究的。。。不过还好，不是太难。
PS:我用的是VUE+element-ui。

**Comment by zx8887** [comment]
效果图如下：
![1](https://user-images.githubusercontent.com/13731281/39510899-f9d87dbe-4e1d-11e8-94d7-c354b69b7548.png)

**Comment by liekkas** [comment]
@zx8887 自定义节点里的图片能不能跟随缩放？

**Comment by zx8887** [comment]
@liekkas 可以的。我现在能无限放大和缩小。而且自定义变形图片也会跟着放大缩小的

**Comment by liekkas** [comment]
@zx8887 请教下如何实现，难在这块了，谢谢啦！

**Comment by liekkas** [comment]
@zx8887 已经实现了，多谢！

**Comment by liekkas** [comment]
@zx8887 选中节点缩放是可以的，但用鼠标滚轮的方式不能缩放。

**Comment by TomHuangCN** [comment]
其实，html 也是支持矩阵变换的，只是当初各种原因没做。 2.0 里已经实现了。 图编辑器是巨复杂的场景，要实现好的交互，打磨一点点细节就会耗费大量的精力。我们目前精力，只能沉淀自己平时业务中做过的场景，把比较有价值的个别场景沉淀下来提供给大家。

**Comment by zx8887** [comment]
@liekkas 我的是可以的哟，我图片是根据外层div比例缩小放大的，外层div又是通过draw来动态变换大小的。

**Comment by zx8887** [comment]
![test](https://user-images.githubusercontent.com/13731281/39740805-decd1448-52c9-11e8-94b1-4ef75c87a6a6.gif)
上动图给你看。代码就是上面的代码

**Comment by zx8887** [comment]
@TomHuangCN html我知道是可以缩放的，之所以我在html之前又加了个canvas节点。是为了在minimap插件里面可以显示。。顺道问一问，minimap有什么方法能实现显示edge。。。。thx

**Comment by zx8887** [comment]
@JacobYChan 你可以理解为model是你自定义对象，你在update节点的时候，修改里面的fontSize就OK了。。我的这个代码字体缩放没有改变大小的，只是能自定义大小。因为如果要根据缩放来调整字体大小，算法有点麻烦，目前我做的是固定文字显示长度，超出部分...

**Comment by zx8887** [comment]
@TomHuangCN 哥。我是被迫学习前端的。之前一直做java后台。。。目前还在学习前端各种框架和技术，估计达不到你们的要求。。。。

**Comment by TomHuangCN** [comment]
可以转啊，基础好就行，前端欢乐多 :-) @zx8887

**Comment by zx8887** [comment]
@TomHuangCN 谢兄弟赏识。。。我个人觉得以目前的水平也只能应聘demo编写师，有没有这个职位嘛，哈哈哈

**Comment by zx8887** [comment]
@JacobYChan 我之前尝试过字体缩放，但是效果不是太好，还有一种方式我觉得应该能行，我没尝试，就是动态监听鼠标滚轮事件
```javascript
graph.on('mousewheel', function(ev){});      // 鼠标滚轮事件
```
然后动态设置html节点的transform:scale()缩放属性。。
我觉得应该行。但是我这个场景不适合，因为有minimap需要展示canvas节点，transform:scale()的缩放比例估计很难和canvas的缩放比例匹配。

**Comment by goodwinfame** [comment]
@zx8887 思路不错，通过监听滚轮事件批量更新net.nodes.model，node在draw方法中拿到scale后设置transform即可。

**Comment by TomHuangCN** [comment]
大家还是喜欢用 dom，但 dom 还是或多或少会有些问题。
G6 2.0 已经对 dom 节点做了很多优化，但有些地方处理的还不够完美。所以还没发布到文档里。

等晚些时候，处理的完美些，争取在 G6 2.1 把 dom 节点发布出来

**Comment by sherlockwang** [comment]
DOM落地这个事儿在G6 2.1里有了吗？

**Comment by zx8887** [comment]
兄弟，还是用canvas话吧，字也是画出来的，无线缩放，要交互画个html里面包含svg图标，记录好id，在afterDraw里面document.getElementById绑定事件吧，我就这么做的。

**Comment by sherlockwang** [comment]
> 兄弟，还是用canvas话吧，字也是画出来的，无线缩放，要交互画个html里面包含svg图标，记录好id，在afterDraw里面document.getElementById绑定事件吧，我就这么做的。

估计也只能这样了，不知道为什么我在G6 Editor里设定的renderer属性死活不生效……大哥可以写G6 Editor的文档了，感觉你用的已经比开发的人强了👍

**Comment by zx8887** [comment]
> > 兄弟，还是用canvas话吧，字也是画出来的，无线缩放，要交互画个html里面包含svg图标，记录好id，在afterDraw里面document.getElementById绑定事件吧，我就这么做的。
> 
> 估计也只能这样了，不知道为什么我在G6 Editor里设定的renderer属性死活不生效……大哥可以写G6 Editor的文档了，感觉你用的已经比开发的人强了👍

我现在只用1.X。。。2.X没用。本来想用editor的。但是闭源+商业。。就只能老老实实1.X自己写一个editor了

**Comment by RolkerMan** [comment]
> ![test](https://user-images.githubusercontent.com/13731281/39740805-decd1448-52c9-11e8-94b1-4ef75c87a6a6.gif)
> 上动图给你看。代码就是上面的代码

你好，好奇一个与该issue无关的问题。
请问你这个编辑器是如何实现的，看起来功能很强大！

**Comment by zx8887** [comment]
> > ![test](https://user-images.githubusercontent.com/13731281/39740805-decd1448-52c9-11e8-94b1-4ef75c87a6a6.gif)
> > 上动图给你看。代码就是上面的代码
> 
> 你好，好奇一个与该issue无关的问题。
> 请问你这个编辑器是如何实现的，看起来功能很强大！

自己手动实现的。。vue   Elementui
