### ISSUE TITLE
changeSize 后没有重绘

### ISSUE THREAD

**Issue by JohnnyLuv** [antvis/G6#2101]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g6.antv.vision/zh/docs/api/Graph/#changesizewidth-height](https://g6.antv.vision/zh/docs/api/Graph/#changesizewidth-height)

### Steps to reproduce
监听横屏竖屏，changeSize 后没有重绘，画布中的节点依旧是原来的宽高

| Environment | Info |
|---|---|
| g6 | 3.7.3 |
| System | macos 10.15.6 |
| Browser | chrome 85.0.4183.102 |

**Comment by Yanyan-Wang** [comment]
changeSize 只是改变画布大小，不会改变节点大小

**Comment by JohnnyLuv** [comment]
![image](https://user-images.githubusercontent.com/16729778/93299109-1b151180-f827-11ea-8744-fb0ccd74d150.png)
![image](https://user-images.githubusercontent.com/16729778/93299144-2a945a80-f827-11ea-8bee-a2675c18aff2.png)
嗯我描述有问题，是监听横屏竖屏后 changeSize() 后画布宽高没有更新

**Comment by JohnnyLuv** [comment]
> changeSize 只是改变画布大小，不会改变节点大小

![image](https://user-images.githubusercontent.com/16729778/93299109-1b151180-f827-11ea-8744-fb0ccd74d150.png)
![image](https://user-images.githubusercontent.com/16729778/93299144-2a945a80-f827-11ea-8bee-a2675c18aff2.png)
嗯我描述有问题，是监听横屏竖屏后 changeSize() 后画布宽高没有更新

**Comment by JohnnyLuv** [comment]
而且 fitView(padding) 方法也没有生效，是不是我的渲染时机不对呢

**Comment by JohnnyLuv** [comment]
```js
function resizeHandle() {
  WRef.current = document.body.offsetWidth
  HRef.current = document.body.offsetHeight
  console.log(WRef.current, HRef.current)
  // console.log(myGraph.current)
  if (myGraph.current) {
    myGraph.current.changeSize(WRef.current, HRef.current)
    myGraph.current.fitCenter()
  }
}

window.addEventListener('resize', () => resizeHandle())
```

**Comment by Yanyan-Wang** [comment]
宽高应该是更新了，你可以审查一下元素。我理解你是想要重新布局，调用一下 graph.layout()

**Comment by JohnnyLuv** [comment]
> 宽高应该是更新了，你可以审查一下元素。我理解你是想要重新布局，调用一下 graph.layout()

```js
```

**Comment by Yanyan-Wang** [comment]
如果你的布局不是在实例化的时候配置到图上的，那需要再给布局实例一下新的宽高

**Comment by CAILeiz** [comment]
老哥，我现在也遇到这个问题了，有解决方案吗
