### ISSUE TITLE
请问可以通过自定义布局方式实现辐射布局吗？这个辐射布局源码比较复杂，ts文件不太能看懂

### ISSUE THREAD

**Issue by Xingkong4183** [antvis/G6#2103]

**Comment by Yanyan-Wang** [comment]
原始需求是什么？改造辐射布局？

**Comment by Xingkong4183** [comment]
对，因为内置辐射算法在面临数据节点很多时无法避免节点重叠。另外，需要对辐射中心点进行一种算法计算。现在内置的辐射布局文件涉及三个TS文件，初次学习感觉改造吃力

**Comment by Yanyan-Wang** [comment]
避免重叠尝试配置 preventOverlap: true， 并且把 maxPreventOverlapIteration 设置大一些，默认是 200。如果真的一圈摆不下，就调大 unitRadius。

要改造肯定要看懂本身算法啦，主要是 ./src/layout/radial/radial.ts 这个文件，可以直接把 G6 代码拉下来尝试在源码里面改然后提 PR，我们可以一起看
