### ISSUE TITLE
edge setSource()后，edge model里的source没有改变，graph保存后再打开，edge恢复原样

### ISSUE THREAD

**Issue by qqbearqq** [antvis/G6#2104]
<div id="mountNode"></div>
<button onclick="test()">test</button>
<script src="https://gw.alipayobjects.com/os/antv/pkg/_antv.g6-3.7.1/dist/g6.min.js"></script>
<script>
    let item = null;
    const data = {
        nodes: [
            {
                id: 'node1',
                label: 'node1',
                x: 100,
                y: 200,
            },
            {
                id: 'node2',
                label: 'node2',

                x: 300,
                y: 200,
            },
            {
                id: 'node3',
                label: 'node3',

                x: 300,
                y: 300,
            },
        ],
        edges: [
            {
                source: 'node1',
                target: 'node2',
            },
        ],
    };
    const graph = new G6.Graph({
        container: 'mountNode', 
        width: 800,
        height: 500,
    });
    graph.data(data);
    graph.render();
    graph.on('node:click', function (e) {
        item = e.item;
    });
    function test() {
        let edgeItem = graph.getEdges()[0];
        edgeItem.setSource(item);
        graph.refresh();
        let newData = graph.save();
        console.log(edgeItem);
        setTimeout(function () {
            graph.read(newData)
        }, 1000)
    }
</script>

**Comment by Yanyan-Wang** [comment]
能使用 graph 的 API 就不要使用 item 自身的 API，item 自身 API 可能不会被 graph 统一管理到。

graph.updateItem(edge, {
  source: 'new-source-node-id'
});

**Comment by qqbearqq** [comment]
收到~谢谢
