### ISSUE TITLE
调用graph.update方法后，节点没有重新绘制

### ISSUE THREAD

**Issue by asevenm** [antvis/G6#2105]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/elated-wildflower-ipthl?file=/src/App.js)

### Steps to reproduce
观察两秒后节点的变化
文档中有提到update方法后会调用draw方法重绘  [文档](https://antv-g6.gitee.io/zh/docs/manual/middle/elements/nodes/custom-node#%E4%BC%98%E5%8C%96%E6%80%A7%E8%83%BD)

| Environment | Info |
|---|---|
| g6 | 3.7.0 |
| System | - |
| Browser | - |

**Comment by Yanyan-Wang** [comment]
自定义节点复写 udpate 为 undefined，这样节点更新的时候才会走你复写的 drawShape 方法，否则会走被继承的父节点类型的 update 方法

```
G6.registerNode('name', {
  drawShape(cfg, group) {...},
  update:undefined
}, 'extendedNodeName'
)
```

**Comment by ljc0910** [comment]
建议完善下这部分文档，这个问题搞得脑壳疼@Yanyan-Wang
