### ISSUE TITLE
combo或者组，如何在将其中的节点拖出后，combo的大小保持不变？

### ISSUE THREAD

**Issue by wrh4585** [antvis/G6#2106]
combo或者组，如何在将其中的节点拖出后，combo的大小保持不变？
目前看官方示例，节点移出combo后，combo会自动改变大小，如何使其不改变大小？

**Comment by Yanyan-Wang** [comment]
见 https://github.com/antvis/G6/issues/2090

提 issue 之前可以先搜一下有没有类似的问题～
