### ISSUE TITLE
一键展开全部节点

### ISSUE THREAD

**Issue by zwygithub** [antvis/G6#2110]
使用type: 'collapse-expand',收缩多个节点后，希望通过一个按钮[ 展开全部节点 ]一键展开，而不是一个个展开，这个有方法吗

**Comment by mxz96102** [comment]
可以设置数据中所有子树根节点的 collapsed 属性为true，并调用 treeGraph.layout() 使之生效；

**Comment by zwygithub** [comment]
希望点击一键展开时，不仅子节点展开，之前点击收缩的孙子节点也展开，有代码吗

**Comment by zwygithub** [comment]
我的代码：中间一段没找到方法。。。
{
              type: 'collapse-expand',
              onChange: function onChange(item, collapsed) {
                  var data = item.get('model')
                  var icon = item.get('group').find(element => element.get('name') === 'collapse-icon')
                  if (collapsed) {
                    icon.attr('symbol', EXPAND_ICON)
                  } else {
                    icon.attr('symbol', COLLAPSE_ICON)
                  }
                  data.collapsed = collapsed
                  return true
               }
}
...
const toolbar = new G6.ToolBar({
        className: 'g6-toolbar-ul',
        getContent: () => {
          return `
    <ul>
      <li code='openAll'>[ 展开全部节点 ]</li>
    </ul>
  `
        },
        handleClick: (code, graph) => {
          if (code === 'openAll') {
           // 这里怎么做：collapsed 及icon



            graph.layout()
          }
        }
      })

**Comment by Yanyan-Wang** [comment]
如果你的数据中很多节点被收起，可以递归数据把每个节点的 collapsed 设置为 false

**Comment by zwygithub** [comment]
递归中collapsed 设置为 false是可以的，但是collapse-icon存在问题

**Comment by Yanyan-Wang** [comment]
如果是自定义节点，且复写 update 方法为 undefined，每次 layout 会走 draw 方法更新节点，可以在 draw 方法里判断 collapsed 属性，然后给定相对应的 icon
