### ISSUE TITLE
在angular8.1.3安装完G6，程序运行报错，但是报错完可以继续运行。

### ISSUE THREAD

**Issue by Justicialsunknight** [antvis/G6#2112]
错误提示ERROR in node_modules/@antv/g6/lib/algorithm/structs/stack/index.d.ts(5,9): error TS1086: An accessor cannot be declared in an ambient context.
希望有人能解决一下疑问。

**Comment by Yanyan-Wang** [comment]
看下是不是同样的问题 https://github.com/storybookjs/storybook/issues/9463#issuecomment-575077542

**Comment by JyotsnaC** [comment]
I was able to fix this by adding `"skipLibCheck": true,` in your tsconfig.json
