### ISSUE TITLE
changeSize is not worked on window client resize

### ISSUE THREAD

**Issue by JohnnyLuv** [antvis/G6#2113]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-bs3m88?file=index.js](https://stackblitz.com/edit/react-bs3m88?file=index.js)

### Steps to reproduce
as you see at the demo link

| Environment | Info |
|---|---|
| g6 | 3.7.3 |
| System | macOs Catalina 10.15.6 |
| Browser | Chrome 85.0.4183.102 |

**Comment by Yanyan-Wang** [comment]
I saw it worked in your demo.

**Comment by JohnnyLuv** [comment]
> I saw it worked in your demo.

but items not covered after the graph resized

**Comment by baizn** [comment]
> > I saw it worked in your demo.
> 
> but items not covered after the graph resized

change items size when graph resized ？

**Comment by Yanyan-Wang** [comment]
try to call `graph.fitView()` after `graph.layout`

**Comment by JohnnyLuv** [comment]
> > > I saw it worked in your demo.
> > 
> > 
> > but items not covered after the graph resized
> 
> change items size when graph resized ？

thx reply first!
this is my code
```
function resizeHandle() {
  WRef.current = document.body.offsetWidth
  HRef.current = document.body.offsetHeight
  console.log(WRef.current, HRef.current)
  // console.log(myGraph.current)
  if (myGraph.current) {
    myGraph.current.changeSize(WRef.current, HRef.current)
    myGraph.current.layout() // add line
    myGraph.current.fitCenter()
  }
}
```
i was reset the canvas's size then the wrap node resized every time,
and call `fitView` after `layout`,
the canvas was resize and worked,
but the nodes and edges not covered the canvas.

same problem with the [Reproduction link](https://stackblitz.com/edit/react-bs3m88?file=index.js) now

**Comment by JohnnyLuv** [comment]
> try to call `graph.fitView()` after `graph.layout`

if the nodes and edges was more than enough, the problem will obvious

**Comment by JohnnyLuv** [comment]
i got it.
pc worked but mobile not.
