### ISSUE TITLE
是否支持 设置某一节点在最左侧？

### ISSUE THREAD

**Issue by xiaofengqqcom123** [antvis/G6#2114]
版本：3.7.3
treegraph中，设置根节点在最左侧 或 最右侧，例如：
![image](https://user-images.githubusercontent.com/29247931/93454712-ee87f500-f90d-11ea-8aa7-f5328e809175.png)

查了下，只看到focusItem~

**Comment by mxz96102** [comment]
设置direction https://g6.antv.vision/zh/examples/tree/compactBox/API
不知道符不符合你的预期

**Comment by xiaofengqqcom123** [comment]
> 设置direction [g6.antv.vision/zh/examples/tree/compactBox/API](https://g6.antv.vision/zh/examples/tree/compactBox/API)
> 不知道符不符合你的预期

不能哎~ 
我们的需求是：根节点有父节点（通过箭头方向控制~）和子节点， 父节点在左侧，子节点在右侧~
可能会存在的场景：
1. 有父有子：此时需要根节点在中心
2. 有父无字：此时需要根节点在右侧
3. 无父有子：此时需要根节点在左侧

**Comment by mxz96102** [comment]
可以看一下脑图树，他getSide可以决定节点在哪一个方向：
https://g6.antv.vision/zh/examples/tree/mindmap

**Comment by xiaofengqqcom123** [comment]
@mxz96102 不是哪个方向的问题~ 
treegraph里，如何控制根节点在展示在最左侧、最右侧、中心？

**Comment by mxz96102** [comment]
我觉得还是需要分析一下数据，然后决定direction

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
