### ISSUE TITLE
高亮相邻节点在click方式激活后，拖动非点击的节点，该节点相连边在取消高亮后仍保留inactive的样式

### ISSUE THREAD

**Issue by linyif2** [antvis/G6#2115]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/mosily/pen/bGpxgWN](https://codepen.io/mosily/pen/bGpxgWN)

### Steps to reproduce

1. 点击BBB节点，进入高亮相邻节点效果；
2. 拖动除BBB以外的任意节点；
3. 点击画布空白处退出高亮状态，发现拖动的节点直接相连的边样式没有还原，且state已取消。

| Environment | Info |
|---|---|
| g6 | 3.7.3 |
| System | - |
| Browser | - |

---
目前发现样式还原是部分无效部分正常，以下为尝试过的样式和结果。
边本体：opacity(×)；stroke(√)；
边文本：opacity(×)；fill(×)；

**Comment by Yanyan-Wang** [comment]
在 defaultEdge 里面去给定在 inactive 状态下会发生变化的字段默认状态的值即可，
```
  defaultEdge: {
    type: "quadratic",
    style: {
      lineWidth: 3,
      lineAppendWidth: 6,
      stroke: "r(0.5, 0.5, 0.3) 0:#ffffff 1:#c2e7b0",
      opacity: 1 // 给默值
    },
    labelCfg: {
      autoRotate: true,
      style: {
        fill: '#000' // 给默值
      }
    }
  },
```
