### ISSUE TITLE
调用graph.layout，节点的位置出现了突变（具体请看codesandbox示例）

### ISSUE THREAD

**Issue by asevenm** [antvis/G6#2117]
- **G6 Version**: 3.7.0
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:  https://codesandbox.io/s/elated-wildflower-ipthl
真实业务中，流程图某个节点可能会有多个分支，每次向该节点添加节点都要手动计算位置的话感觉太复杂了，所以直接调用layout重新布局一次，但是位置出现了突变，请问是否有较好的方法解决这个问题

**Comment by Yanyan-Wang** [comment]
我看到你的 demo 中对图上的节点做了很多增删操作，事实上，图的结构发生了很大的变化，所以布局算法计算出来的节点位置就会变化比较大。dagre 布局是基于图数据做了贪心的算法，数据结构的不同就会导致最后布局节点排序、位置的不同。这里建议在实例化图的时候配置 animate: true，起码它变化的时候能看出来是怎么变的。。

**Comment by asevenm** [comment]
> 我看到你的 demo 中对图上的节点做了很多增删操作，事实上，图的结构发生了很大的变化，所以布局算法计算出来的节点位置就会变化比较大。dagre 布局是基于图数据做了贪心的算法，数据结构的不同就会导致最后布局节点排序、位置的不同。这里建议在实例化图的时候配置 animate: true，起码它变化的时候能看出来是怎么变的。。

嗯明白，谢谢
