### ISSUE TITLE
点击使用changeData()方法切换数据时，点击第一次正常切换画布效果，点击第二次画布就会出现问题，是因为没有给之前画布作删除的原因吗？

### ISSUE THREAD

**Issue by Xingkong4183** [antvis/G6#2118]

**Comment by baizn** [comment]
你具体是怎么写的呢？提供一个可复现的在线demo

**Comment by Xingkong4183** [comment]
> 你具体是怎么写的呢？提供一个可复现的在线demo

https://codesandbox.io/s/modest-mccarthy-tk787?file=/index.js类似于这种，点击之后节点位置有变化

**Comment by Yanyan-Wang** [comment]
是出现什么问题？
如果是节点样式发生了变化的问题，可以在自定义节点里复写 udpate 方法为 undefined
```

G6.registerNode(
  "icon-node",
  {
    update: undefined
  }, 'rect');
```
