### ISSUE TITLE
tooltip的位置会在画布特定位置计算错误

### ISSUE THREAD

**Issue by gaoxs1985** [antvis/G6#2119]
- **G6 Version**:3.7.3
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

![GIF 2020-9-18 16-15-57](https://user-images.githubusercontent.com/2238640/93573962-5f8ce280-f9ca-11ea-965d-9734f2495056.gif)

demo:  https://codepen.io/gaoxs1985/pen/ExKeBpo

画布不是满屏幕，是在一个框架下

另外，自定义节点，tooltip显示内容想根据鼠标所在的shape显示，有实现办法吗？formatText无法根据鼠标位置改变内容吧？

**Comment by Yanyan-Wang** [comment]
> tooltip的位置会在画布特定位置计算错误

用插件的形式即可

```
const tooltip = new G6.Tooltip({
  
      formatText: function formatText(model) {
        const text = 'description: ' + model.description;
        return text;
      },
      offsetX: 220, // 根据画布左侧到浏览器左边界设定
      offsetY: 60, // 根据画布上侧到浏览器上边界设定
})
``` 

> tooltip显示内容想根据鼠标所在的shape显示

参考 demo https://g6.antv.vision/zh/examples/tool/tooltip#tooltipPluginLocal
其中 getContent 的参数 e.target 可以判断是在哪个 shape 上

**Comment by Yanyan-Wang** [comment]
另外，我看到你的自定义节点用的都是基本图形，推荐用 canvas 模式，性能比 svg 高很多

**Comment by gaoxs1985** [comment]
好的,我试一下
之前尝试过用canvas模式,有些小细节调整起来很麻烦,例如选择状态的边框问题,内部图形的位置计算问题
功能完善后再去考虑优化的问题
先谢过了
