### ISSUE TITLE
自定义编辑边

### ISSUE THREAD

**Issue by lingengbiao** [antvis/G6#2120]
要实现类似下面这张编辑边的功能，有什么思路？
[https://gojs.net/latest/samples/blockEditor.html](https://gojs.net/latest/samples/blockEditor.html)

![微信图片_20200918174544](https://user-images.githubusercontent.com/13961366/93583703-d203bf80-f9d6-11ea-950d-7f4420e56546.png)

**Comment by Yanyan-Wang** [comment]
图的重编辑场景推荐使用 AntV 团队另外一个开源库 AntV X6 https://x6.antv.vision/

G6 适合做图展示与分析，以及轻量级的图编辑。这个需求的编辑属性已经很高了，不是 G6 着重的部分。

**Comment by TelfyC** [comment]
现在版本这个能实现了吗，因为考虑到X6整体的可定制化没有g6高，所以可能还是更偏g6一点
