### ISSUE TITLE
Method to update the config on a graph

### ISSUE THREAD

**Issue by GrandSchtroumpf** [antvis/G6#2122]
- [X] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Using `graph.set(config)` doesn't update the behavior of the canvas. Here is an example : 
```typescript
graph.set({
  modes: {
    default: ['drag-canvas', 'zoom-canvas']
  }
});
// Canvas still cannot be dragged or zoomed
```
I could use `graph.addBehaviors` & `graph.removeBehaviors` but I would have to iterate over each behavior, remove the old one, and add the new one, while I "just" want to set a new set of behaviors.
Also if I want to apply multiple changes on many config field I would have to apply a specific method per field of the config.

### What does the proposed API look like?
Something like `updateConfig(config)` that would set the config & update the canvas. Or a stand alone method to update the canvas with the current config.
Thanks :)

**Comment by Yanyan-Wang** [comment]
Thanks. That is a good suggestion, we will improve it latter.

P.S. `graph.removeBehaviors` and  `graph.addBehaviors` is able to remove an array of behaviors like this:

```
graph.addBehaviors(['brush-select', 'click-select'], 'default');
graph.removeBehaviors(['brush-select', 'click-select'], 'default');
```

https://g6.antv.vision/en/docs/api/Graph#removebehaviorsbehaviors-modes

**Comment by GrandSchtroumpf** [comment]
Thx, yes I know that `addBehaviors` & `removeBehaviors` support array. In my case I want to `set` the behavior. To achieve that you need to do something like: 
```typescript
setBehavior(behaviors: string[], mode: string) {
  const current = graph.get('modes')[mode];
  if (current) {
    graph.removeBehaviors(current, mode);
    graph.addBeahviors(behaviors, mode);
  }
}
```
It works for one key. But in the case I'm describing above, I need to do that for every field of the `GraphOptions`.
The other advantage would be to batch changes, the code above run twice the rendering while it could do it only once.

If you can point me out in the code where is the logic to update the canvas after a change in the options I can write a Pull Request for this feature, if it's ok for you.

**Comment by Yanyan-Wang** [comment]
v4.1.0-beta.1 has supported graph.updateBehavior(behavior, newCfg, mode) ✅

**Comment by Yanyan-Wang** [comment]
v4.1.0 is released
