### ISSUE TITLE
changedata方法切换数据源时报错：Uncaught TypeError: Cannot read property 'destroyed' of undefined。

### ISSUE THREAD

**Issue by Xingkong4183** [antvis/G6#2123]

**Comment by baizn** [comment]
切换数据源时 graph 实例已经被销毁了，请检查下用法，如果还有问题，麻烦提供一个可复现的在线demo

**Comment by Xingkong4183** [comment]
> 切换数据源时 graph 实例已经被销毁了，请检查下用法，如果还有问题，麻烦提供一个可复现的在线demo

https://codesandbox.io/s/suspicious-sound-dsvcm?file=/index.js
demo如上，不知为何报错。

**Comment by baizn** [comment]
> > 切换数据源时 graph 实例已经被销毁了，请检查下用法，如果还有问题，麻烦提供一个可复现的在线demo
> 
> https://codesandbox.io/s/suspicious-sound-dsvcm?file=/index.js
> demo如上，不知为何报错。

细节检查一下 tableData 中 edges 的数据，把 edges 去掉就没问题，看下是不是边中某个id在nodes中不存在

**Comment by noonehide** [comment]
所以是为啥？

**Comment by noonehide** [comment]
target找不到会报这个错？
