### ISSUE TITLE
console warning with g6Layout.worker.js.map

### ISSUE THREAD

**Issue by JohnnyLuv** [antvis/G6#2125]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g6.antv.vision/zh/docs/manual/getting-started](https://g6.antv.vision/zh/docs/manual/getting-started)

### Steps to reproduce
1.create a new project ant import g6
2.see it on console

| Environment | Info |
|---|---|
| g6 | 3.7.3 |
| System | macos 10.15.6 |
| Browser | safari 15610.1.28.1.9, 15610 |

**Comment by JohnnyLuv** [comment]
<img width="591" alt="image" src="https://user-images.githubusercontent.com/16729778/93731892-b3cdd780-fc01-11ea-85eb-13aa138cf543.png">

**Comment by Yanyan-Wang** [comment]
Are you importing '@antv/g6/es'? Import '@antv/g6' instead if you need to layout with worker.

**Comment by JohnnyLuv** [comment]
sure im using the `workerEnabled` options like the api documents, what can i do and let it work
may i have a demo with the `workerEnabled ` case?
thx!

**Comment by Yanyan-Wang** [comment]
here goes the demo https://codesandbox.io/s/romantic-fire-9ojrs

**Comment by JohnnyLuv** [comment]
> here goes the demo https://codesandbox.io/s/romantic-fire-9ojrs

i import `'@antv/g6'` not `@antv/g6/es` in my obj of create-react-app cli.

ok, the console warning only printout with safari. chrome worked.
