### ISSUE TITLE
联合使用 tooltip 和 drag-canvas 时，拖拽画布后，tooltip的位置会发生比较大的改变

### ISSUE THREAD

**Issue by lunaMoon1010** [antvis/G6#2129]
- **G6 Version**:  3.6.0
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by mxz96102** [comment]
有截图或者在线codepen的例子吗，比较不能理解这个issue标题的具体问题呢

**Comment by lunaMoon1010** [comment]
> 有截图或者在线codepen的例子吗，比较不能理解这个issue标题的具体问题呢
