### ISSUE TITLE
Minimap可以固定大小吗

### ISSUE THREAD

**Issue by yangjialing** [antvis/G6#2130]
放大到一个定程度，Minimap的蓝色框变成一个特别小的框，可否固定蓝色框的大小

例子，https://g6.antv.vision/zh/examples/tool/minimap，

缩到很小，蓝色框只剩下一条线

期望：minimap可以固定宽度高度，可以有参数来设置最小，最大宽高度

**Comment by yangjialing** [comment]
例子，https://g6.antv.vision/zh/examples/tool/minimap，
缩到很小，蓝色框只剩下一条线

**Comment by mxz96102** [comment]
框的大小都是zoom对应的，你的期望是zoom不改变，还是zoom变框也不变呢

**Comment by yangjialing** [comment]
> 框的大小都是zoom对应的，你的期望是zoom不改变，还是zoom变框也不变呢

zoom缩放超过一定大小，蓝色框固定摸一个高度，宽度

**Comment by mxz96102** [comment]
viewportClassName这个配置项可以配置蓝色框的classname，通过max-width，max-height，min-width，min-height限制下试试？

**Comment by mxz96102** [comment]
https://codesandbox.io/s/bitter-snow-5fog0 这个是一个简单的例子
