### ISSUE TITLE
一般图布局中，有能较好支持1万条以上的节点数据吗？

### ISSUE THREAD

**Issue by Xingkong4183** [antvis/G6#2131]

**Comment by baizn** [comment]
参考这里 https://g6.antv.vision/zh/examples/performance/perf  
数据量大的情况下建议先将位置计算好再渲染

**Comment by yangjialing** [comment]
> 参考这里 https://g6.antv.vision/zh/examples/performance/perf
> 数据量大的情况下建议先将位置计算好再渲染

如果是树图的话，请问怎么计算

**Comment by baizn** [comment]
> > 参考这里 https://g6.antv.vision/zh/examples/performance/perf
> > 数据量大的情况下建议先将位置计算好再渲染
> 
> 如果是树图的话，请问怎么计算

一样的，就用树图的布局算法先在后端计算好坐标信息

**Comment by Xingkong4183** [comment]
> 树图的布局算法先在后端计算好坐标信息

这意思是大数据量情况下后端返回节点数据和坐标信息，前端只做按位置渲染节点和边吗

**Comment by Xingkong4183** [comment]
> > > 参考这里 https://g6.antv.vision/zh/examples/performance/perf
> > > 数据量大的情况下建议先将位置计算好再渲染
> > 
> > 
> > 如果是树图的话，请问怎么计算
> 
> 一样的，就用树图的布局算法先在后端计算好坐标信息

这种制约前端做大数据布局，是浏览器还是计算机的性能限制呢？有解决的办法吗

**Comment by baizn** [comment]
这些计算都是用计算机 CPU 计算的，会有性能瓶颈，使用GPU计算能好点，布局 G6 后面会支持使用 GPU 计算。
