### ISSUE TITLE
拖拽画布，如何获取平移量呢？

### ISSUE THREAD

**Issue by xiaofengqqcom123** [antvis/G6#2132]
需求：
点击某节点，在下面弹框~
画布移动时，弹框位置要调整
![image](https://user-images.githubusercontent.com/29247931/93852383-84dc6200-fce4-11ea-8f53-99d1967fb02d.png)

**Comment by JohnnyLuv** [comment]
勾股定理

**Comment by mxz96102** [comment]
通过graph来得到这个节点，再根据这个节点的x，y，通过[graph.getClientByPoint](https://g6.antv.vision/zh/docs/api/Graph#getclientbypointx-y)获取位置，然后调整弹框，

**Comment by lunaMoon1010** [comment]
> 通过graph来得到这个节点，再根据这个节点的x，y，通过[graph.getClientByPoint](https://g6.antv.vision/zh/docs/api/Graph#getclientbypointx-y)获取位置，然后调整弹框，
你好，我也遇到了类似的问题，我想问的是获取位置后怎么调整弹框（ToolTip）的位置呢，有对应的API没有呀。

**Comment by xiaofengqqcom123** [comment]
我们项目是react，只实例化了一次G6，所以在bindevents中，是无法拿到组件state中的值的，是否显示弹框，是根据node model确定的。基于上面，获取目标节点，需要遍历所有的node发自我的华为手机-------- 原始邮件 --------发件人： Dominic Ming <notifications@github.com>日期： 2020年9月22日周二 下午4:14收件人： antvis/G6 <G6@noreply.github.com>抄送： xiaofeng <1944681023@qq.com>, Author <author@noreply.github.com>主    题： Re: [antvis/G6] 拖拽画布，如何获取平移量呢？ (#2132)

通过graph来得到这个节点，再根据这个节点的x，y，通过graph.getClientByPoint获取位置，然后调整弹框，

**Comment by mxz96102** [comment]
一般来说会在组件里面存一个graph的refer，在组件mount的时候去bindevent，这样可以在时间里面setState，或者直接获取this.state

**Comment by xiaofengqqcom123** [comment]
学习了，我试下～发自我的华为手机-------- 原始邮件 --------发件人： Dominic Ming <notifications@github.com>日期： 2020年9月22日周二 晚上7:49收件人： antvis/G6 <G6@noreply.github.com>抄送： xiaofeng <1944681023@qq.com>, Author <author@noreply.github.com>主    题： Re: [antvis/G6] 拖拽画布，如何获取平移量呢？ (#2132)

一般来说会在组件里面存一个graph的refer，在组件mount的时候去bindevent，这样可以在时间里面setState，或者直接获取this.state
