### ISSUE TITLE
包版本与github上版本不一致？

### ISSUE THREAD

**Issue by xiaofengqqcom123** [antvis/G6#2133]
最新的 @antv/g6版本是3.7.3，
从github下载的 @antv/g6源码版本是3.80
![image](https://user-images.githubusercontent.com/29247931/93958699-a2afd280-fd89-11ea-9482-6ba96bbc22a8.png)

需求：排查线上js报错时，定位到g6，但是从github中下载的g6里没有这行代码，例如：
![image](https://user-images.githubusercontent.com/29247931/93958809-e4d91400-fd89-11ea-836f-3e71bdeeb178.png)

**Comment by baizn** [comment]
3.8.0 本周发布，目前包的最新版本是 3.7.3
