### ISSUE TITLE
G6.registerNode use modelRect as template 有个小问题

### ISSUE THREAD

**Issue by buildJava** [antvis/G6#2134]
如果自定义配置时不写descriptionCfg 或者 labelCfg 会导致label无法生成控制台 报错如下：
vue.runtime.esm.js?a593:1888 TypeError: Cannot read property 'offset' of undefined
    at Object.drawLabel (g6.min.js?ca03:15)
    at Object.draw (g6.min.js?ca03:15)
    at Object.draw (g6.min.js?ca03:15)
    at e.t.drawInner (g6.min.js?ca03:15)
    at e.t.draw (g6.min.js?ca03:15)
    at e.t (g6.min.js?ca03:15)
    at new e (g6.min.js?ca03:15)
    at t.addItem (g6.min.js?ca03:15)
    at e.addItem (g6.min.js?ca03:15)
    at e.add (g6.min.js?ca03:15)
应该是没有对这两个值取默认值，烦请修复

// 审批节点
  G6.registerNode('audit-node', {
    options: nodeConfig
  }, 'modelRect')

// Task节点 NodeConfig 通用配置
  const nodeConfig = {
    // 节点基本属性
    size: [150, 35],
    style: {
      radius: 5,
      stroke: '#1890FF',
      fill: '#FFFFFF'
    },
    label: '审批节点',
    labelCfg: {
      style: {
        fill: '#595959',
        fontSize: 14
      },
      offset: 30
    },
    descriptionCfg: {
      style: {
        fontSize: 12,
        fill: '#bfbfbf'
      },
      paddingTop: 0
    },
    // 状态属性
    stateStyles: {
      hover: {
        stroke: '#BAE7FF',
        lineWidth: 8,
        strokeOpacity: 0.6
      }
    },
    // 左侧矩形边属性
    preRect: {
      show: true,
      width: 4,
      fill: '#1890FF',
      radius: 2
    },
    // 图标属性
    logoIcon: {
      show: true,
      img: require('@/assets/nodeimg/audit.svg'),
      width: 16,
      height: 16,
      offset: -5
    },
    // 状态属性
    stateIcon: {
      show: true,
      img: require('@/assets/nodeimg/audit.svg'),
      width: 16,
      height: 16,
      offset: -5
    }
  }

**Comment by baizn** [comment]
已修复，更新到 3.8.0 版本
