### ISSUE TITLE
drag-zoom有没有方法超过某个范围不让他拖拽了

### ISSUE THREAD

**Issue by yangjialing** [antvis/G6#2136]
drag-zoom有没有方法超过某个范围不让他拖拽了

**Comment by baizn** [comment]
drag-node ? 目前没有这个功能，后面我们可以加上

**Comment by yangjialing** [comment]
> drag-node ? 目前没有这个功能，后面我们可以加
说错了，是拖拽画布

**Comment by luckydogM** [comment]
可以自己写一个behavior，然后拖拽的时候判断边界范围

**Comment by Yanyan-Wang** [comment]
drag-canvas 目前的设计是当图内容的「左边界」到达视口的「右边界」时，就不可以再拖拽了，上下左右类似。
