### ISSUE TITLE
Angular lib

### ISSUE THREAD

**Issue by GrandSchtroumpf** [antvis/G6#2137]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

Hello, sorry for creating an issue for that. I didn't know how to share it with you.
I've built an [Angular library for @antv/g6](https://github.com/dappsnation/ng-antv)
It helps Angular developer create G6 graph in a angular-ish way.

It's still in version 0.0.1, but it has all the basic features. I've created an online editor to try it out : 
https://ng-antv.netlify.app/graph

I'll keep updating it with new features, and maybe try it out with other antv libraries !

Thanks for your amazing work, I've quite enjoyed building the lib around @antv/g6.

**Comment by baizn** [comment]
Great，we will share [ng-antv](https://github.com/dappsnation/ng-antv) with other developers by adding a link to the [AntV G6 official website](https://g6.antv.vision/en/docs/manual/introduction#links)

**Comment by GrandSchtroumpf** [comment]
Awesome thanks !
