### ISSUE TITLE
There is no trigger for node click event

### ISSUE THREAD

**Issue by PoojaUppalapati** [antvis/G6#2138]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/g6-reproduction-template-uvzdf)

### Steps to reproduce
I would like to write unit test for a G6 custom Behavior that is registered for node click. There is no way to trigger the Behavior from unit test.
For example, if I need to trigger an event to click on a combo to expand it then I use graph.expandCombo. If I need to trigger an event to click a node, then there is no trigger available.

| Environment | Info |
|---|---|
| g6 | 3.7.3 |
| System | - |
| Browser | - |

**Comment by baizn** [comment]
https://g6.antv.vision/en/docs/manual/FAQ/upgradeGuide#adding-a-shape

we highly recommend you to assign name and draggable when adding a shape. If not, the shapes will not response some interactive events. Adding these two property as below:

```
G6.registerNode('customNode', {
  draw(cfg, group) {
    const keyShape = group.addShape('rect', {
      attrs: {
        // ... The attributes of the graphic shape
      },
      draggable: true, // Allow this shape to be dragged
      name: 'key-shape', // Not unique, you can assign any string value to it
    });
    const circle = group.addShape('circle', {
      attrs: {
        // ... The attributes of the graphic shape
      },
      draggable: true, // Allow this shape to be dragged
      name: 'circle-shape', // Not unique, you can assign any string value to it
    });
    return keyShape;
  },
});
```

**Comment by Yanyan-Wang** [comment]
refer to the graph.emit as in G6's unit tests
 https://github.com/antvis/G6/blob/cdda02ff0d6eb042c8999d1dcbdcb21c21c7a5c4/tests/unit/behavior/select-spec.ts#L35

or event simulator https://github.com/antvis/G6/blob/cdda02ff0d6eb042c8999d1dcbdcb21c21c7a5c4/tests/unit/behavior/drag-node-spec.ts#L4
