### ISSUE TITLE
更新数据但不更新布局的方法？

### ISSUE THREAD

**Issue by monijiang** [antvis/G6#2140]
使用updateLayout方法应用布局后，新增两个随机位置节点，之后的changeData()方法调用，将使两个新节点直接应用布局。如果存在需要更新数据，但新增数据不应用布局。还有其他的实现方法吗？

**Comment by Yanyan-Wang** [comment]
增加节点可以用 graph.addItem

**Comment by monijiang** [comment]
可以有比较多的数据更改，需要调用类似changeData()方法来重新渲染，变动数据不希望应用布局，原有数据才应用

**Comment by Yanyan-Wang** [comment]
可以尝试用内部的方法在 changeData 之前销毁布局：
``` 
graph.get('layoutController').layoutMethod.destroy();
```

下个小版本提供一个 graph 上的方法用于销毁布局

**Comment by monijiang** [comment]
layoutMethod这个属性貌似只在treeGraph示例上进行了赋值，graph实例上并没有

**Comment by Yanyan-Wang** [comment]
Graph 上如果你没有配置布局的话，就没有
