### ISSUE TITLE
graph.updateItem动态设置边（edge）的stateStyles不生效，但是动态设置节点（node）的stateStyles生效

### ISSUE THREAD

**Issue by gb853940223** [antvis/G6#2142]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/gb853940223/graph.updateItem](https://github.com/gb853940223/graph.updateItem)

### Steps to reproduce
1、根据g6官方快速入手教程，生成一个demo。
2、设置node和edget的default和stateStyles样式
3、通过graph.on(node:click)和graph.on(edge:click)绑定事件
4、通过两个按钮绑定updateItem事件
5、点击按钮触发updateItem(clickNode, model)和updateItem(clickEdge, model)时，发现node生效，但是edge不生效

| Environment | Info |
|---|---|
| g6 | 3.6.0 |
| System | window10 |
| Browser | chrome  v85.0.4183.102 |

**Comment by baizn** [comment]
![image](https://user-images.githubusercontent.com/9443867/94124390-82663d80-fe87-11ea-9087-a7996f9a2a9b.png)
如果是改变状态参考上图，还不行的话麻烦提供一个在线可复现的demo

**Comment by gb853940223** [comment]
https://github.com/gb853940223/graph.updateItem，你可以打开这个地址，然后把index.html文件下载下来，打开。
1、click一个node，再点击“切换节点”，此时选中node的样式会发生变化。
2、click一个edge，再点击“切换边”，此时选中edge的样式不会发生变化。

**Comment by baizn** [comment]
更新到3.8.1
