### ISSUE TITLE
TypeError n.path is undefined in Firefox on toolbar button click.

### ISSUE THREAD

**Issue by rohitsahu4** [antvis/G6#2143]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cocky-thompson-iplhz)

### Steps to reproduce
Click on any of the toolbar button in firefox.

| Environment | Info |
|---|---|
| g6 | 3.7.3 |
| System | Windows 10 |
| Browser | Mozilla Firefox V79 |

**Comment by valenzhou** [comment]
_Uncaught TypeError: n.path is undefined_
I also encountered this problem in Firefox. 

Environment | Info
-- | --
g6 | 3.7.3
System | macOS Big Sur 11.0.1
Browser | Mozilla Firefox 83.0
