### ISSUE TITLE
文档中方法名错误

### ISSUE THREAD

**Issue by wrh4585** [antvis/G6#2145]
如题，文档中 getOriginStyle() 方法的示例，方法名与此方法不一致。
![image](https://user-images.githubusercontent.com/45685551/94124528-b3467280-fe87-11ea-909b-164689c0fa65.png)
https://antv-g6.gitee.io/zh/docs/api/nodeEdge/Item/#getoriginstyle

**Comment by baizn** [comment]
多谢，官网重新发布后就OK，详见 https://github.com/antvis/G6/pull/2149
