### ISSUE TITLE
自定义节点，自定义update方法，setItemState、updateItem都使用的时候有冲突

### ISSUE THREAD

**Issue by Rranran** [antvis/G6#2148]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/old-meadow-znuly?file=/src/index.js)

### Steps to reproduce
1. 使用case1、鼠标离开之后样式没有还原
2. 使用case2、符合预期结果

测试了一下，只有case2的流程能达到预期结果

| Environment | Info |
|---|---|
| g6 | 3.7.3 |
| System | window |
| Browser | chrome85 |

**Comment by mxz96102** [comment]
因为你自定义了update，这个逻辑没有闭环，所以导致了case1的问题，在case1的update函数加上这个试试呢
node.getKeyShape().attr({ stroke: cfg.stroke || "#30BF78" });

**Comment by baizn** [comment]
复写了 update 后，就要实现完整
