### ISSUE TITLE
请问如何判断是否有元素处于激活状态。

### ISSUE THREAD

**Issue by oangy** [antvis/g6#215]

**Comment by liekkas** [comment]
@oangy 奇怪你是如何发现这个API的，官网API文档都没找到

**Comment by oangy** [comment]
![image](https://user-images.githubusercontent.com/12290338/39630910-58dcc290-4fe3-11e8-8a9f-3ee368384258.png)

@liekkas del方法是删除激活子项，把它打印出来就知道了
