### ISSUE TITLE
内置的drag-node可以在拖拽结束的时候抛出节点的信息吗？比如x,y坐标

### ISSUE THREAD

**Issue by Superzzw1994** [antvis/G6#2150]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
将一个节点拖拽到另一个节点身上，根据节点类型和位置来判断可否将节点添加到另一个节点内部。

### What does the proposed API look like?
可以像自定义behavior一样自定义事件并在结束时graph.emit一个自定义事件把需要的参数抛出

**Comment by baizn** [comment]
下个小版本支持

**Comment by Yanyan-Wang** [comment]
A 节点放置到 B 身上，可以监听 node:drop，里面的参数可以判断当前 B 节点信息
```
graph.on('node:drop', e => {
 // 判断 e.item 的信息
})
```

**Comment by Superzzw1994** [comment]
> A 节点放置到 B 身上，可以监听 node:drop，里面的参数可以判断当前 B 节点信息
> 
> ```
> graph.on('node:drop', e => {
>  // 判断 e.item 的信息
> })
> ```
