### ISSUE TITLE
polyline 报错

### ISSUE THREAD

**Issue by asevenm** [antvis/G6#2152]
- **G6 Version**: 3.7.0
- **Platform**:
- **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/22423693/94237254-24962c00-ff41-11ea-99ae-4e71226eb163.png)

- **CodePen Link**:

**Comment by asevenm** [comment]
demo:  https://codesandbox.io/s/quizzical-antonelli-j9m3i?file=/src/App.js 
g6：版本3.8.0

**Comment by Yanyan-Wang** [comment]
自定义边中复写 update 函数为 undefined 即可：
```
G6.registerEdge("flow-polyline-round", {
     update: undefined,
    // ...
}, 'polyline');
```
