### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by xfy196** [antvis/G6#2154]
![image](https://user-images.githubusercontent.com/45205025/94254034-c07f6200-ff58-11ea-8f77-5b1404c388f0.png)
l可不可以实现这个效果

**Comment by Yanyan-Wang** [comment]
可以尝试用 Graph 的自定义布局以及子图布局实现，布局实现的成本较高。
https://g6.antv.vision/zh/examples/net/layoutMechanism
https://g6.antv.vision/zh/examples/net/layoutMechanism#customBigraph

其他文本样式、边样式使用自定义节点/边可以实现。 https://g6.antv.vision/zh/examples/item/customNode
