### ISSUE TITLE
smooth-convex: e.unshift is not a function

### ISSUE THREAD

**Issue by mkomu** [antvis/G6#2155]
- **G6 Version**: the latest release
- **Platform**: firefox/linux
- **Mini Showcase(like screenshots)**: See the hull second example here: https://g6.antv.vision/en/examples/interaction/hull#changeMembers
- **CodePen Link**: Click codesandbox link from the second example of hull example

The second hull example from the project web page is not working, it gives the following error:

TypeError
t.unshift is not a function

The problem originates from type: 'smooth-convex' in the source code. If you google for the error, you find something about jquery but I don't know if it is case.

**Comment by Yanyan-Wang** [comment]
The problem does not occur in the official website, could you pls provide an minimum reproduced online demo?

**Comment by Yanyan-Wang** [comment]
Hi, dear user. Since there was no response for a long time, we cannot figure out the answer of the problem you described. If there is new progress, feel free to open a new issue.

**Comment by mkomu** [comment]
Hi @Yanyan-Wang,

did you try to click the link above: https://g6.antv.vision/en/examples/interaction/hull#changeMembers

It's giving the error immediately. I think that *is* the official website you mentioned? It is weird that example code on the official website is crashing?

The sandbox link from g6.antv.vision is this:

https://codesandbox.io/s/uh8oh
