### ISSUE TITLE
Dagre diagram with combo group creates overlapping areas.

### ISSUE THREAD

**Issue by selenecodes** [antvis/G6#2158]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://observablehq.com/d/88b667ca22289d5b](https://observablehq.com/d/88b667ca22289d5b)

### Steps to reproduce
- Doubleclick the combo group so that it closes
- Witness the combo group overlapping with "sql_file2"

| Environment | Info |
|---|---|
| g6 | 3.8.0 |
| System | Ubuntu 18.04 |
| Browser | 85.0.4183.83 (Official Build) (64-bit) |

**Comment by Yanyan-Wang** [comment]
hi, I did not see the overlapping after closing the combo
![image](https://user-images.githubusercontent.com/29593318/95704746-769ab980-0c84-11eb-9b4d-ac4103c87854.png)

**Comment by selenecodes** [comment]
Hmm weird since it is overlapping for me on Chrome Desktop but not Chrome Mobile.

Chrome Desktop (86.0.4240.75):
![Screenshot from 2020-10-12 13-09-44](https://user-images.githubusercontent.com/20491756/95740125-3f300b00-0c8c-11eb-894f-7b44fc9c901b.png)

Chrome Mobile:
![Screenshot_20201012-131126](https://user-images.githubusercontent.com/20491756/95740304-89b18780-0c8c-11eb-8b66-179cebf36edf.jpg)

Expected result:
![Screenshot from 2020-10-12 13-17-38](https://user-images.githubusercontent.com/20491756/95740728-558a9680-0c8d-11eb-941d-d805c666d975.png)

**Comment by clojj** [comment]
Any news on this issue ?

**Comment by Yanyan-Wang** [comment]
solved by v4.7.15
