### ISSUE TITLE
How to create combo in treeMap？

### ISSUE THREAD

**Issue by kibbon** [antvis/G6#2160]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/festive-golick-y8jiq?file=/src/index.js)

### Steps to reproduce
直接访问页面即可，可以看到createCombo无法对树图节点生效（类似的还有group, hull）

| Environment | Info |
|---|---|
| g6 | 3.8.0 |
| System | Mac |
| Browser | Chrome |

---
预期：可在树图中通过使用combo/group/hull或其他方式，使得部分同级节点布局位置相近并可实现关联样式

**Comment by baizn** [comment]
树图暂时不支持 Combo 和 hull，看下能否按照这种形式实现你的需求 https://g6.antv.vision/zh/examples/net/dagreFlow#dagreCombo

**Comment by baizn** [comment]
combo 可以直接使用 graph.createCombo API创建，hull 可以使用 graph.createHull API 创建，参考这个demo：https://codesandbox.io/s/pqfsx?file=/index.js

你提供的demo报错的原因：
1. graph.createCombo 要放到 read 后面；
2. 提供的 id 数组中存在一个不存在的id combo2。
