### ISSUE TITLE
Minimap拖拽蓝框的时候，鼠标移出minimap容器后，蓝框就不随鼠标移动了，需要松开鼠标，重新拖拽蓝框。 希望跟节点的拖拽一样，鼠标移出浏览器再移回来能正常使用。

### ISSUE THREAD

**Issue by qiangshushu** [antvis/G6#2161]
Minimap拖拽蓝框的时候，鼠标移出minimap容器后，蓝框就不随鼠标移动了，需要松开鼠标，重新拖拽蓝框。
希望跟节点的拖拽一样，鼠标移出浏览器再移回来能正常使用。

**Comment by baizn** [comment]
这个需要再讨论一下，Minimap主要用途之一是用来导航图中的元素，它的交互范围正常情况下是被限定在容器内的。

**Comment by Yanyan-Wang** [comment]
感谢建议，v3.8.3 已支持
