### ISSUE TITLE
这句语法是怎么来的？辐射布局算法

### ISSUE THREAD

**Issue by Xingkong4183** [antvis/G6#2162]
if (nodes) {
    nodes.forEach((node, i) => {
      nodeMap[node.id] = i;
      **const row: number[] = [];**
      console.log(row);
      matrix.push(row);
    });
  }
上面这句代码const row: number[] = [];它在定义之后如何接受的值呢？因为浏览器打印row出来就有值了，求解释！

**Comment by Yanyan-Wang** [comment]
请给出更多信息，这是哪里的代码？可能是有个同名变量 row？

**Comment by Yanyan-Wang** [comment]
猜测上述代码可能是 adjacent-matrix 或者 util 中的。

如果是的话，这里只是在初始化 matrix，下面的代码往 matrix 中填内容了。js 的此类变量是引用，后面填的内容实际上填到了跟 ‘row’ 指向相同的位置。如果你要看 const row: number[] = []; 这句话之后 row 的值，应该在下一行加 debugger，才能看到这一时刻的 row 的值。
