### ISSUE TITLE
Console error : This item exists already. Be sure the id is unique. 

### ISSUE THREAD

**Issue by JyotsnaC** [antvis/G6#2163]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vkheq)

### Steps to reproduce
If you inspect in console. there is a warning that is being thrown when ever there is a click on the canvas. " This item exists already. Be sure the id is unique". How can we avoid this ?

| Environment | Info |
|---|---|
| g6 | 3.8.0 |
| System | Mac Os latest |
| Browser | Chrome latest |

**Comment by Diaskhan** [comment]
When u add a node to graph u must be sure that node have unique  I'd. 
https://antv-g6.gitee.io/en/docs/manual/getting-started

In the code that u provided I don't see filling I'd property!

**Comment by JyotsnaC** [comment]
@Diaskhan : I have no changes [Example of Performance](https://g6.antv.vision/en/examples/performance/perf#eva). Not sure why you are not seeing the ID but if you see line number 73 the link to the [data](https://gw.alipayobjects.com/os/basement_prod/0b9730ff-0850-46ff-84d0-1d4afecd43e6.json) has nodes specified clearly

**Comment by Diaskhan** [comment]
Have u check there is unique ID in the data json ?

**Comment by JyotsnaC** [comment]
@Diaskhan : yes I did check and ID's are unique. Also the easiest way to do is open the json file and search for "id":"1" you will find just one entry

**Comment by baizn** [comment]
![image](https://user-images.githubusercontent.com/9443867/95539764-d04f7980-0a21-11eb-8fa8-8289732110e5.png)
![image](https://user-images.githubusercontent.com/9443867/95539805-ecebb180-0a21-11eb-8551-0962bd3175cb.png)

@JyotsnaC  This is a public data source, there are many id's not unique

**Comment by pyQianYi** [comment]
I think you have configured the getId function in layout. I also encountered the same error prompt as you. The consequence is that there is a problem in expanding and folding. When I remove the getId function, it returns to normal
