### ISSUE TITLE
请问edge可以上下两侧显示文字么？

### ISSUE THREAD

**Issue by Superzzw1994** [antvis/G6#2167]
![10DF8F7D-F2AE-4CB3-8276-76F62865CCF3](https://user-images.githubusercontent.com/20533727/95473857-18858200-09b7-11eb-9bdc-c361adf93115.png)

就想图里这样。

**Comment by baizn** [comment]
可以的，参考这里 https://g6.antv.vision/zh/examples/case/customFlow
