### ISSUE TITLE
力导向布局，约束节点布局范围的例子中，如果开启webworker，节点布局不正确

### ISSUE THREAD

**Issue by wFanhua** [antvis/G6#2169]

**Comment by wFanhua** [comment]
代码演示 7 ：约束在一定范围内进行力导向布局。

**Comment by mxz96102** [comment]
你好，因为webworker里面传函数还没有支持，所以webworker模式onTick不起效

**Comment by wFanhua** [comment]
> 你好，因为webworker里面传函数还没有支持，所以webworker模式onTick不起效

但我看源码中，layout 配置中的 onTick 回调还是会执行的
