### ISSUE TITLE
扩展边，使用 afterDraw(cfg, group时，startPoint和endPoint坐标都为NaN

### ISSUE THREAD

**Issue by Elias-cug** [antvis/G6#2171]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/brave-pine-9env4?file=/src/index.js)

### Steps to reproduce
有一个需求就是，边上的信息展示形式需要定制。在使用afterDraw时获取到的坐标值都是NaN

| Environment | Info |
|---|---|
| g6 | 3.8.0 |
| System | win10 |
| Browser | 谷歌83.0.4103.97 |

**Comment by baizn** [comment]
应该是 codeSandbox 控制台的问题，你在 G6 官网上面看下 https://g6.antv.vision/zh/examples/item/customEdge，
浏览器中打印出来是正常的。
![image](https://user-images.githubusercontent.com/9443867/95643537-5f23cb00-0ae2-11eb-8683-d2492059a002.png)

**Comment by Elias-cug** [comment]
不是控制台的问题，如果node不设置坐标，使用drage布局自动计算坐标，获取到的坐标值就是NaN

**Comment by smilelight** [comment]
遇到了类似的问题，不过是在刚开始绘制的时候就报错了。同样的代码好像之前运行还正常。
![](https://lightsmile-img.oss-cn-beijing.aliyuncs.com/g6_bug.png)
![](https://lightsmile-img.oss-cn-beijing.aliyuncs.com/g6_bug2.png)

**Comment by auuunya** [comment]
> 不是控制台的问题，如果node不设置坐标，使用drage布局自动计算坐标，获取到的坐标值就是NaN

你好 请问你这个问题解决了吗？我也遇到了这样的问题，节点不设置坐标，使用drage计算的时候 自定义边是获取不到起始点和终止点的坐标
