### ISSUE TITLE
节点拥有state时，执行changeData导致节点样式卡在之前的state

### ISSUE THREAD

**Issue by StarkShang** [antvis/G6#2173]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wizardly-bash-0ify6)

### Steps to reproduce
1. node:click事件设置节点state为selected（selected状态表现为节点背景呈紫色），同时在该节点添加子节点，并执行changeData；
2. ~~在线demo中发现新问题，点击节点执行changeData后，初始节点类型更改了；~~
3. mouseenter事件中打印了节点现有的state，可以观察到样式被卡住的节点其实已经没有对应的state；

| Environment | Info |
|---|---|
| g6 | 3.8.0 |
| System | - |
| Browser | - |

**Comment by StarkShang** [comment]
猜测该问题与两个因素相关：
1. 节点数据的类型是一个类，不是普通的object；
2. 自定义节点的设置不对

**Comment by baizn** [comment]
把下面这段放到 graph.data 前面，或者去掉。
```
graph.node(function (node) {
  return {
    label: node.id,
    labelCfg: {
      offset: 10,
      position: "right"
    }
  };
});
```
具体参考这里：https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/defaultNode/#%E4%BD%BF%E7%94%A8-graphnode

**Comment by StarkShang** [comment]
@baizn 根据上面修改后，问题2得以解决 但是问题1仍然存在。

**Comment by baizn** [comment]
> @baizn 根据上面修改后，问题2得以解决 但是问题1仍然存在。

具体什么问题？

**Comment by StarkShang** [comment]
@baizn 就是节点拥有state时，执行changeData方法会导致节点样式卡在之前的state
比如例子里面，点击节点会新增子节点并执行changeData方法。这时候被点击的节点的state就卡住了。

**Comment by Yanyan-Wang** [comment]
state 卡住是什么意思，我这里看到点击之前 hover 到一个节点上，是这样：
![image](https://user-images.githubusercontent.com/29593318/103391668-8cb66880-4b55-11eb-939d-f1e93f21a1c9.png)

点击之后是这样：
![image](https://user-images.githubusercontent.com/29593318/103391673-963fd080-4b55-11eb-89d4-a5977fde82e1.png)

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
