### ISSUE TITLE
minimap把隐藏的内容展示出来了，导致图和minimap不一致

### ISSUE THREAD

**Issue by overpowerFish** [antvis/G6#2174]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/9297265b](https://riddle.alibaba-inc.com/riddles/9297265b)

### Steps to reproduce
打开就能看到

| Environment | Info |
|---|---|
| g6 | 3.7.3 |
| System | - |
| Browser | Chrome版本 86.0.4240.75（正式版本） (x86_64) |

**Comment by Yanyan-Wang** [comment]
经排查，发现是 svg 渲染下会出现该情况。下个小版本修复

看到你的自定义节点其实用 canvas 完全可以，且 canvas 性能更好，自由度更高，svg 渲染引擎目前有一些问题。而且这里主画布和 minimap 都会渲染，所以是双倍渲染性能的开销
