### ISSUE TITLE
树图能实现多对一吗？

### ISSUE THREAD

**Issue by fanrax** [antvis/G6#2176]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://www.baidu.com](http://www.baidu.com)

### Steps to reproduce
11

| Environment | Info |
|---|---|
| g6 | 3.8.0 |
| System | window7 |
| Browser | chrome |

---
11

**Comment by fanrax** [comment]
![Uploading 3955D46A-83AD-4598-8EC1-78384DD2BB70.png…]()

**Comment by fanrax** [comment]
或者我如果用流程图来写的话，需要怎么在中间添加一个新节点

**Comment by baizn** [comment]
> 或者我如果用流程图来写的话，需要怎么在中间添加一个新节点

graph.addItem

**Comment by Yanyan-Wang** [comment]
多对一具体什么场景？多个父节点连接到一个子节点？如果是这样的话，这个数据就不是一个树图数据，不应该使用树图展示

**Comment by webmrxu** [comment]
https://antv-g6.gitee.io/zh/examples/net/dagreFlow
这个demo有多对一，一对多
如果要实现多对多，还是有问题

**Comment by fanrax** [comment]
> https://antv-g6.gitee.io/zh/examples/net/dagreFlow
> 这个demo有多对一，一对多
> 如果要实现多对多，还是有问题

这个已经不属于树图了  研究了下 树图是不能多对一的  要靠一般图

**Comment by fanrax** [comment]
> 多对一具体什么场景？多个父节点连接到一个子节点？如果是这样的话，这个数据就不是一个树图数据，不应该使用树图展示

嗯   我找过了  树图就没这种设定

**Comment by fanrax** [comment]
> > 或者我如果用流程图来写的话，需要怎么在中间添加一个新节点
> 
> graph.addItem

谢谢  已经在用这个了
