### ISSUE TITLE
extending edges with additional shapes

### ISSUE THREAD

**Issue by N3XT0R** [antvis/G6#2178]
Hey Guys,
at first a very nice library you have build here.

At Second: 
how its possible to extend existing edges by more shapes? Your Documentation on customizing them has not enough information about things like adding more shapes or else. 

I've tried to add a shape with following code:

```javascript
G6.registerEdge("dataLabelsEdge", {
                options: {
                    style: {
                        stroke: "#000"
                    }
                },
                labelAutoRotate: true,
                labelPosition: 'center',
                refX: 0,
                refY: 0,
                // Response the states change
                afterDraw(cfg, group) {
                    const shape = group.get('children')[0];
                    const startPoint = shape.getBBox();
                    if (cfg.data && cfg.data.status) {
                        // the left label
                        group.addShape("text", {
                            attrs: {
                                text: 'Status: ' + cfg.data.status,
                                fill: "#595959",
                                textAlign: "start",
                                textBaseline: "middle",
                                x: startPoint.x + 10,
                                y: startPoint.y - 10
                            },
                            name: "left-text-shape"
                        });
                    }
                    console.log(group);
                },
            }, 'line');
```

It seems that the Position of the shape is outside of the edge-element:
![image](https://user-images.githubusercontent.com/1297846/95665212-7f896f00-0b4e-11eb-84df-a55fce8a1574.png)

**Comment by baizn** [comment]
startPoint.x and startPoint.y are the top-left coordinates，ref to the demo：https://codesandbox.io/s/fast-dream-d9rto

**Comment by N3XT0R** [comment]
thanks for that example, it is very helpful to understand how to create own additional shapes on an extended edge.  maybe it could be useful to add this information to the documentation, too ? :)

**Comment by Yanyan-Wang** [comment]
> thanks for that example, it is very helpful to understand how to create own additional shapes on an extended edge. maybe it could be useful to add this information to the documentation, too ? :)

Thanks for your suggestion, we will improve the docs soon.
