### ISSUE TITLE
自定义节点可以继承于自定义的节点吗？

### ISSUE THREAD

**Issue by StarkShang** [antvis/G6#2179]
自定义节点继承时，具体继承了哪些东西？draw方法似乎是覆盖了，因此不能继承父节点绘制的内容？

**Comment by StarkShang** [comment]
![image](https://user-images.githubusercontent.com/11701842/95669808-1ab62f00-0bb7-11eb-9a42-22ab2b65c57e.png)
看了一下源码，是没有定义的字段会进行继承，已定义的字段就会被覆盖。
这样是不是无法复用自定义节点创建的图形？

**Comment by mxz96102** [comment]
你好，请问是怎么复用呢，如果是想要类似组件的复用，可以试试jsx定义节点方案呢

**Comment by mxz96102** [comment]
定义的例子在这里 ：https://codesandbox.io/s/g6-node-maker-yofk8?file=/src/index.js
官网使用方法在这里： https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/jsx-node
