### ISSUE TITLE
不能在移动端进行拖动吗？直接在移动端的qq打开官网的demo不能拖动

### ISSUE THREAD

**Issue by qikong333** [antvis/G6#2180]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://antv-2018.alipay.com/zh-cn/g6/3.x/demo/tree/tree-compact-box.html](https://antv-2018.alipay.com/zh-cn/g6/3.x/demo/tree/tree-compact-box.html)

### Steps to reproduce
直接在移动端的qq打开官网的demo不能拖动

| Environment | Info |
|---|---|
| g6 | 3.8.1 |
| System | 移动端 |
| Browser | 移动端qq浏览器 |

**Comment by mxz96102** [comment]
https://stackoverflow.com/questions/1517924/javascript-mapping-touch-events-to-mouse-events
参考这个方法，加一下移动端时间转发才可以，默认是没有移动端支持的

**Comment by baizn** [comment]
drag-canvas 是支持移动端拖拽的，drag-node 和 zoom-canvas 后面也会支持。

**Comment by qikong333** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Moyee"<notifications@github.com&gt;; 
发送时间: 2020年10月12日(星期一) 中午11:17
收件人: "antvis/G6"<G6@noreply.github.com&gt;; 
抄送: "1513372833"<1513372833@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [antvis/G6] 不能在移动端进行拖动吗？直接在移动端的qq打开官网的demo不能拖动 (#2180)





 
drag-canvas 是支持移动端拖拽的，drag-node 和 zoom-canvas 后面也会支持。
