### ISSUE TITLE
树形图连接线绘制bug

### ISSUE THREAD

**Issue by M-smilexu** [antvis/G6#2183]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vigorous-field-fzduw)

### Steps to reproduce
树形图修改初始化图形参数为 defaultEdge: { type: 'polyline' } 后，连接线绘制效果有问题，具体可以查看 demo。

| Environment | Info |
|---|---|
| g6 | 3.8.1 |
| System | - |
| Browser | - |

**Comment by Yanyan-Wang** [comment]
经排查，目前折线算法在起点/终点节点坐标为负数时有问题，可以暂时先将所有节点平移使其没有负数坐标，后续我们再跟进修复这个问题。

例如：
```
graph.getNodes().forEach(node => {
  const {x, y} = node.getModel();
  graph.updateItem(node, {
    x: x + 1000,
    y: y + 1000
  });
});
graph.fitView();
```

**Comment by sanmao3** [comment]
g6-4.0.3遇到同样的问题，请问什么时候可以修复更新

**Comment by sanmao3** [comment]
@Yanyan-Wang 用你提供的方法临时处理，会产生一个新问题：'collapse-expand'模式下，点击节点，整个树图飞出画布了

**Comment by Yanyan-Wang** [comment]
v4.1.7 修复了
