### ISSUE TITLE
树状图的节点addShape 一个dom 添加不上click事件

### ISSUE THREAD

**Issue by lgy1159** [antvis/G6#2184]

**Comment by Yanyan-Wang** [comment]
dom 图形不支持 G6 事件，需要使用原生 DOM 事件
文档有标注：https://g6.antv.vision/zh/docs/api/nodeEdge/shapeProperties#dom-svg
demo：https://g6.antv.vision/zh/examples/item/customNode#svgDom

**Comment by lgy1159** [comment]
> dom 图形不支持 G6 事件，需要使用原生 DOM 事件
> 文档有标注：https://g6.antv.vision/zh/docs/api/nodeEdge/shapeProperties#dom-svg
> demo：https://g6.antv.vision/zh/examples/item/customNode#svgDom

你换成Tree试试

**Comment by lgy1159** [comment]
> dom 图形不支持 G6 事件，需要使用原生 DOM 事件
> 文档有标注：https://g6.antv.vision/zh/docs/api/nodeEdge/shapeProperties#dom-svg
> demo：https://g6.antv.vision/zh/examples/item/customNode#svgDom

new G6.TreeGraph

**Comment by Yanyan-Wang** [comment]
应该是因为树图默认会加上 animate，因为 dom 节点每次更新图的时候都会被销毁再重新创建，所以在 animate 之后，原来绑定了事件的节点被销毁了，重新创建的节点没有绑定上事件。两种解决方案：
1. 在实例化图的时候关闭树图的动画，`animate: false`
2. 在 animate 之后再绑定事件，如下，在 render() 之前调用
```
graph.on('afteranimate', e => {
  bindClickListener();
});
```
