### ISSUE TITLE
更新视口外的节点报错

### ISSUE THREAD

**Issue by asevenm** [antvis/G6#2188]
- **G6 Version**:3.7.0，3.8.1
- **Platform**:
- **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/22423693/95945601-666a1200-0e1d-11eb-8c20-5d051235fec8.png)

- **CodePen Link**:

**Comment by asevenm** [comment]
定位的问题是应该是调用了group.addGroup方法导致

**Comment by asevenm** [comment]
> 定位的问题是应该是调用了group.addGroup方法导致

demo: https://codesandbox.io/s/shy-sound-pm4ke?file=/src/App.js

**Comment by Yanyan-Wang** [comment]
谢谢，3.8.3 已修复
