### ISSUE TITLE
G6 要怎么更新节点样式，除了在创建节点attrs 里面 之外 还有其他方法吗

### ISSUE THREAD

**Issue by ZOEWANGCHINA** [antvis/g6#219]
net.update(item, {
                // do someting
              });
这个 里面 只能 更新 size，label 和x，y  其他的color ，fill ，radius 该如何更新呢

**Comment by zx8887** [comment]
你可以用自带的图形，配个html节点创建最终的节点，我就是这么搞定的。

**Comment by SHINEWANGCHINA** [comment]
谢谢，我可以修改了，我定义了一个值，update 里面去 更新这个值， 数据会放到 model里面，可以修改
