### ISSUE TITLE
构造Dagre图，edge配置label属性，渲染时会抛出异常

### ISSUE THREAD

**Issue by xkn1ght** [antvis/G6#2190]
## Reproduction link
https://codesandbox.io/s/eager-wilbur-spr34?file=/src/App.js

## Steps to reproduce
1. 在构造data.edges时加上label属性
2. 导致render函数调用失败

Environment | Info
-|-
G6 | 3.7.1
Browser | 86.0.4240.75（正式版本） (x86_64)

因为在chorme 85版本并没有复现这个bug，所以推测是chrome升级了，底层渲染的API `getPointAtLength` 逻辑改变了。
## 一些资料
> [chromium升级的代码变动](https://source.chromium.org/chromium/chromium/src/+/b36d94ab63e3958829be9070da6b6a8f534c97b6:third_party/blink/renderer/core/svg/svg_geometry_element.cc;dlc=e7cc9815ae925e05e2ae723d993993cad48ec5cf)

codesandbox中复现的错误
![image](https://user-images.githubusercontent.com/42573813/95979666-91b92500-0e4e-11eb-9bb8-372690918a2f.png)
chorme的更改代码：
![image](https://user-images.githubusercontent.com/42573813/95979610-777f4700-0e4e-11eb-939e-5b60c9ac8e1d.png)
添加代码抛出的异常和codesandbox的报错一致。

**Comment by baizn** [comment]
感谢反馈，可以跟踪这个 https://github.com/antvis/g/issues/634 issue 的进展。
