### ISSUE TITLE
自定义节点，无法拖拽（官网实例）

### ISSUE THREAD

**Issue by emmaqiu** [antvis/G6#2191]
自定义节点，无法实现拖拽
@antv/g6: "3.8.1"

G6.registerNode(
  "dom-node",
  {
    draw: (cfg, group) => {
      const stroke = cfg.style ? cfg.style.stroke || "#5B8FF9" : "#5B8FF9";
      const shape = group.addShape("dom", {
        attrs: {
          width: cfg.size[0],
          height: cfg.size[1],
          html: `
        <div id=${
          cfg.id
        } class='dom-node' style="background-color: #fff; border: 2px solid ${stroke}; border-radius: 5px; width: ${cfg
            .size[0] - 5}px; height: ${cfg.size[1] - 5}px; display: flex;">
          <div style="height: 100%; width: 33%; background-color: #CDDDFD">
            <img alt="" style="line-height: 100%; margin-left: 7px;" src="https://gw.alipayobjects.com/mdn/rms_f8c6a0/afts/img/A*Q_FQT6nwEC8AAAAAAAAAAABkARQnAQ" width="20" height="20" />  
          </div>
          <span style="margin:auto; padding:auto; color: #5B8FF9">${
            cfg.label
          }</span>
        </div>
          `
        },
        draggable: true,
        name: "shape"
      });
      return shape;
    }
  },
  "single-node"
);

/** 数据 */
const data = {
  nodes: [
    {
      id: "node1",
      x: 10,
      y: 100,
      label: "Homepage"
    },
    {
      id: "node2",
      x: 200,
      y: 100,
      label: "Subpage"
    }
  ],
  edges: [
    {
      source: "node1",
      target: "node2"
    }
  ]
};

const graphContainer = document.getElementById("container");
const width = graphContainer.scrollWidth;
const height = (graphContainer.scrollHeight || 500) - 100;

const descriptionDiv = document.createElement("div");
descriptionDiv.innerHTML = `由于打包问题，本 demo 的 111-113 行被暂时注释。需要您在代码栏中打开 111-113 行的注释以得到自定义 DOM 节点正确的交互。<br /> Due to the packing problem of the site, we have to note the line 111-113 of this demo temporary. Unnote them to see the result of custom DOM node with interactions please.`;
const container = document.getElementById("container");
graphContainer.appendChild(descriptionDiv);

const graph = new G6.Graph({
  container: "container",
  width,
  height,
  // translate the graph to align the canvas's center, support by v3.5.1
  fitCenter: true,
  renderer: "svg",
  linkCenter: true,
  modes: {
    // 支持的 behavior
     default: ['zoom-canvas', 'drag-canvas', 'drag-node'],
  },
  defaultNode: {
    type: "dom-node",
    size: [120, 40]
  }
});

graph.data(data);
graph.render();

**Comment by Yanyan-Wang** [comment]
自定义 dom 节点不能使用 G6 的事件，只能使用 DOM 的原生事件，在文档中已经注明。建议使用 canvas，性能更好，自由度更高。
