### ISSUE TITLE
Toolbar 是否可以去掉不需要的功能,例如说去掉撤销按钮,只保留其他的功能

### ISSUE THREAD

**Issue by mxy2316868975javascript** [antvis/G6#2192]
![image](https://user-images.githubusercontent.com/15233384/95998618-9fc76f80-0e67-11eb-871b-e946036c28b3.png)

**Comment by mxy2316868975javascript** [comment]
如何配置呢

**Comment by baizn** [comment]
不支持配置，但可以通过修改 css 样式去隐藏。
![image](https://user-images.githubusercontent.com/9443867/96411581-42db0900-121b-11eb-929b-fb1953614a89.png)
