### ISSUE TITLE
3.6.0版本拖拽报错

### ISSUE THREAD

**Issue by sunshine824** [antvis/G6#2194]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://www.sunshine.com](http://www.sunshine.com)

### Steps to reproduce

| Environment | Info |
|---|---|
| g6 | 3.6.0 |
| System | - |
| Browser | Chrome 86.0.4240.80（正式版本） (x86_64) |

---
以前3.6.0版本拖拽正常，今天重新更新依赖之后导致拖拽报错，Uncaught TypeError: s.getBBoxMethod(...) is not a function

!(https://gitee.com/sunshine824/smart_admin_ui/blob/master/drag_bug.png)

**Comment by Yanyan-Wang** [comment]
请提供一下最小复现的在线 demo，上面那个地址打开后显示 “This Site Is Under Construction and Coming Soon.”

**Comment by sunshine824** [comment]
问题解决了，是因为我用cnpm加载的包导致了报错，用npm加载就行了，感谢
