### ISSUE TITLE
使用create-edge可以创建于默认边类型不同的边吗？

### ISSUE THREAD

**Issue by GentlemanSu** [antvis/G6#2195]
在defaultEdge中定义边的类型为polyline，想用create-edge创建line类型的边应该怎么操作？，求大佬指导

**Comment by mxz96102** [comment]
如果在边里面指定了type会覆盖defaultEdge的设定

**Comment by Yanyan-Wang** [comment]
目前可以在边创建完成之后，通过 graph.updateItem 去更改 type:
 ```
graph.on('aftercreateedge', e => {
  graph.updateItem(e.edge, {
    type: 'line'
  });
});
```

下个小版本可以考虑在 create-edge 添加一个边配置的配置项
