### ISSUE TITLE
希望在force布局中支持按照节点属性进行group分组

### ISSUE THREAD

**Issue by wFanhua** [antvis/G6#2196]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
force布局能实现https://observablehq.com/@john-guerra/force-in-a-box的效果

### What does the proposed API look like?
无

**Comment by wFanhua** [comment]
主要是webworker中，自定义布局不支持webworker

**Comment by Yanyan-Wang** [comment]
看下这个：https://g6.antv.vision/zh/examples/net/forceDirected#forceConstrainedInRect

可以改造这个例子，在 onTick 里面判断节点数据中的某个属性，然后约束到不同的区域中

**Comment by wFanhua** [comment]
> 看下这个：https://g6.antv.vision/zh/examples/net/forceDirected#forceConstrainedInRect
> 
> 可以改造这个例子，在 onTick 里面判断节点数据中的某个属性，然后约束到不同的区域中

但这个要在onTick中实现，webworker不支持layout中的函数配置

**Comment by Yanyan-Wang** [comment]
G6 的 force 现在不支持其他方式的聚类了，后续可以考虑增加这个 feature。目前，fruchterman 可以配置 clustering： https://g6.antv.vision/zh/examples/net/furchtermanLayout#fruchtermanClustering

**Comment by wFanhua** [comment]
> G6 的 force 现在不支持其他方式的聚类了，后续可以考虑增加这个 feature。目前，fruchterman 可以配置 clustering： https://g6.antv.vision/zh/examples/net/furchtermanLayout#fruchtermanClustering

我可以试着提个PR，之前自己这边布局是已经实现了，但卡在webworker部分，自定义布局无法支持webworker

**Comment by Yanyan-Wang** [comment]
赞，欢迎 pr 🎊🎊

**Comment by Yanyan-Wang** [comment]
已经发布 3.8.3，demo 在此 https://g6.antv.vision/zh/examples/net/forceDirected#forceClustering

再次感谢 pr！
