### ISSUE TITLE
当同一页面有多张图时，使用tooltip插件提示边信息，一张图destroy后，另一张tooltip值变为null

### ISSUE THREAD

**Issue by Elias-cug** [antvis/G6#2197]
当同一页面有多张图时，使用tooltip插件提示边信息，一张图destroy后，另一张tooltip值变为null

**Comment by Yanyan-Wang** [comment]
请提供一个最小的复现在线 demo

**Comment by Yanyan-Wang** [comment]
尝试了一下，没能复现：https://codepen.io/Yanyan-Wang/pen/wvWzdOZ?editors=0010

如果还有问题的话，请给出最小复现在线 demo，再开一个 issue。

提 issue 麻烦按照 issue 模版给出全量信息，否则效率低下。
