### ISSUE TITLE
图形path绘制不正确

### ISSUE THREAD

**Issue by lin2006yuo** [antvis/G6#2198]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antvg6-tvigq)

### Steps to reproduce
复制svg的`path`到Shape的`path`属性中，绘制出来的结果和svg不一致

| Environment | Info |
|---|---|
| g6 | 3.8.1 |
| System | - |
| Browser | - |

---
发现修复方法复制一遍`M`command，见demo

**Comment by areyouse7en** [comment]
怎么能够方便的对path进行位移和缩放呢？

**Comment by lin2006yuo** [comment]
> 怎么能够方便的对path进行位移和缩放呢？

官方提供了变换方法
```typescript
let matrix = shape.getMatrix()
if (!matrix) matrix = mat3.create() as number[]
const newMatrix = G6.Util.transform(matrix, [
['t', 20,20], 
['s', 0.5,0.5],
])
shape.setMatrix(newMatrix)
```
