### ISSUE TITLE
版本3.7.1 graph.addItem（） 方法 1137行 添加stack时，自定义node类型会被type覆盖 

### ISSUE THREAD

**Issue by qqbearqq** [antvis/G6#2199]
版本3.7.1 graph.addItem（） 方法 1137行 添加stack时，自定义node类型会被type覆盖 

if (stack && this.get('enabledStack')) {
      const addedModel = {
        ...item.getModel(),
        **type**
      }
。。。

这里的type不用加吧

**Comment by Yanyan-Wang** [comment]
升级到最新版本，已经改掉了
