### ISSUE TITLE
使用过程中频繁改变节点状态会报错undefined

### ISSUE THREAD

**Issue by liwenliang** [antvis/G6#2200]
![image](https://user-images.githubusercontent.com/1535458/96336009-1d30f100-10af-11eb-9332-37c165a20040.png)
圆框内是我加的代码，调试用的

**Comment by liwenliang** [comment]
如何能避免这个问题？
![image](https://user-images.githubusercontent.com/1535458/96336051-7dc02e00-10af-11eb-9b09-d011db17db06.png)

**Comment by Yanyan-Wang** [comment]
请提供最先复现在线 demo

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
