### ISSUE TITLE
自定义双击节点创建新的边卡顿

### ISSUE THREAD

**Issue by liaoluying** [antvis/G6#2201]
从3.7.1升级到3.8.1后，自定义双击节点创建新的边会出现延迟卡顿。

**Comment by liaoluying** [comment]
> 从3.7.1升级到3.8.1后，自定义双击节点创建新的边会出现延迟卡顿。

拖拽节点也会出现卡顿，都是在升级到3.8.1后出现的

**Comment by baizn** [comment]
麻烦信息提供全面一点，或者提供一个在线demo

**Comment by liaoluying** [comment]
> 麻烦信息提供全面一点，或者提供一个在线demo

https://codesandbox.io/s/distracted-wiles-t2try?file=/src/components/HelloWorld.vue

**Comment by Yanyan-Wang** [comment]
在该例子中，拖拽节点没发现卡顿。创建边有卡顿，由于 polyline 的算法在新版本中进行更新，加入了较多运算，在移动鼠标的过程中频繁重计算，所以有卡顿。
