### ISSUE TITLE
使用create-edge 进行连线操作时, 删除该边的source 节点, 会导致崩溃. 

### ISSUE THREAD

**Issue by mochase** [antvis/G6#2202]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/runtime-mountain-zn07q?file=/src/index.js)

### Steps to reproduce
使用create-edge创建边时(click模式),  点击source节点后, 通过removeItem()删除该节点, 会导致应用崩溃

| Environment | Info |
|---|---|
| g6 | 3.8.1 |
| System | - |
| Browser | - |

---
具体场景: 当用户无意中点击节点开始连线操作时, 这时比如通过右键菜单栏删除该节点, 会导致崩溃. 
是否有api能取消连线操作, 绕过这个问题? 或者有api手动的dispatch click event来绕过. 尝试过dispatch原生的MouseEvent, 似乎没有用.

**Comment by Yanyan-Wang** [comment]
删除节点之前删掉这条正在增加的边就可以了。可以通过 create-edge 的两个时机事件来辅助管理
`'beforecreateedge'`, `'aftercreateedge'`

**Comment by mochase** [comment]
> 删除节点之前删掉这条正在增加的边就可以了。可以通过 create-edge 的两个时机事件来辅助管理
> `'beforecreateedge'`, `'aftercreateedge'`
> 
> ```
> graph.on('beforecreateedge'`, e => {
>    // 记录 e.edge 为正在增加的边
> });
> graph.on('aftercreateedge'`, e => {
>    // 增加边完成
> });
> ```

尝试过在删点之前先删除掉那条临时边, 依然报错, 可以看更新后的那个例子

**Comment by Yanyan-Wang** [comment]
好的谢谢，这里在内部判断一下这个边界情况。下个小版本修复
