### ISSUE TITLE
图算法 webWorker 支持

### ISSUE THREAD

**Issue by zuiidea** [antvis/G6#2203]
### What problem does this feature solve?
图算法可能耗时较长，导致页面卡住，如 pageRank 算法，一是需要webWorker支持，其次是异步支持。当前 pageRank 算法内应用到了graph 实例的一些API，graph 实例在copy到worker上可能有点问题，看能否提供一个纯算法的API。

### What does the proposed API look like?
例如：
`getPageRank(graph, epsilon, linkProb).then(result => console.log(result))`

**Comment by Yanyan-Wang** [comment]
很好的建议，也欢迎社区 pr～

**Comment by lulei90** [comment]
现有业务也有这个需求，使用findAllPath在节点数量多的情况，页面就直接处于不可用的情况

**Comment by Yanyan-Wang** [comment]
感谢 @zuiidea , @antv/algorithm 已支持 worker 异步计算

**Comment by kevindurant-source** [comment]
有相关的文档说明吗，我没找到相应的图算法的webworker说明文档
