### ISSUE TITLE
建议给插件添加获取Graph对象的功能

### ISSUE THREAD

**Issue by AtomicGu** [antvis/G6#2204]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
这个功能是为了解决多个Graph对象共用一个插件（比如右键菜单）的问题。这样的话我们就可以在全局范围内const一个G6.Menu对象，然后在各图片初始化构造的时候把这个const传过去就行了，因为在插件的回调中可以获得Graph对象。
而现在，我只能在每构造一个Graph对象时同时构造一堆插件，绑定每个插件的this，通过this获得Graph对象。

### What does the proposed API look like?
希望插件的回调能像Behavior一样，通过this能获取到Graph对象（我在Menu的handleMenuClick中console.log出来是undefined）

**Comment by Yanyan-Wang** [comment]
this.get('graph') 应该可以拿到 graph 对象的呀

**Comment by AtomicGu** [comment]
上代码~
```HTML
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Proving Ground</title>
  </head>
  <body>
    <script src="https://gw.alipayobjects.com/os/lib/antv/g6/3.8.1/dist/g6.min.js"></script>
    <div id="container" style="border: solid; height: 600px" />
    <script>
      const menu = new G6.Menu({
        itemTypes: ["node"],
        handleMenuClick(target, item) {
          console.log(this);
          // console.log(this.get("graph")) 这行会抛异常
        },
      });

      const container = document.getElementById("container");

      const graph = new G6.Graph({
        container: container,
        width: container.clientWidth,
        height: container.clientHeight,
        fitView: true,
        plugins: [menu],
      });

      graph.data({
        nodes: [
          {
            id: "1",
            x: 0,
            y: 0,
          },
          {
            id: "2",
            x: 100,
            y: 100,
          },
        ],
        edges: [{ source: "1", target: "2" }],
      });
      graph.render();
    </script>
  </body>
</html>
```
@Yanyan-Wang 
这段代码log出来的this是window，我希望它能log出来一个graph的上下文对象，这样就可以实现一次创建（实例化），到处使用了。

**Comment by Yanyan-Wang** [comment]
哦, `menu.get('graph')` 这样是可以的。handleMenuClick 方法是绑定到 dom 元素上的，所以 this 不是 menu。

**Comment by AtomicGu** [comment]
@Yanyan-Wang 好的👌，虽然通过把箭头函数与Graph绑定在一起创建的办法也能实现这个需求，但是我不清楚这样做的开销是多大，如果方便实现的话希望能考虑一下我的建议。

**Comment by baizn** [comment]
通过 menu.get('graph') 获取 Graph 对象，
```
handleMenuClick(target, item) {
    console.log(this);
 // console.log(this.get("graph")) 这行会抛异常
```

这里的 this 是 Window 对象。
