### ISSUE TITLE
关于iconfont彩色图标无法显示？

### ISSUE THREAD

**Issue by Kang127** [antvis/G6#2205]
使用iconfont时，把style去掉页面上会是透明颜色，肉眼看不见。赋值一个颜色后，就丢失了原本的彩色。我想要显示原本的彩色，请问这个怎么解决？
                    const keyShape = group.addShape('text', {
                        attrs: {
                            x: cfg.x,
                            y: cfg.y,
                            fontFamily: 'iconfont', // 对应css里面的font-family: "iconfont";
                            textAlign: 'center',
                            textBaseline: 'middle',
                            text: cfg.text,
                            fontSize: 40,
                            style: {
                                 fill: 'red',//这里去掉会变成透明
                            },
                        },
                    });

**Comment by Kang127** [comment]
![JX 8S96Y`R0)RM1{QYRFX`A](https://user-images.githubusercontent.com/48777757/96537541-1b427a00-12c9-11eb-8a71-79d860b0c1fd.png)

**Comment by Yanyan-Wang** [comment]
addShape 的时候 fill 不用包在 style 里，和 x y 平级。

**Comment by Kang127** [comment]
> addShape的时候fill不用包在style里，和xy平级。

是的，这里原本是一个对象，我粘贴多了。请问怎么显示原本的彩色?

**Comment by Yanyan-Wang** [comment]
iconfont 的目的不是为了自由的切换颜色吗，如果要用原本颜色其实就是一个 image 了。一定要用 iconfont 的话，就取个色给 fill 好了。

**Comment by Kang127** [comment]
> iconfont的目的不是为了自由的切换颜色吗，如果要用原本颜色其实就是一个图片了。一定要用iconfont的话，就取个色给fill好了。
iconfont里面是ui上传的彩色图标，fill不能设置多个颜色吧

**Comment by Yanyan-Wang** [comment]
可以设置渐变色，其他的不行了。如果是这样，其实不算是 iconfont 了，iconfont 本质上是一个 text，一个 text 每个比划肯定不能设置不同的颜色呀，除非用多个 text 去拼，每个字就可以不一样颜色。这种需求还是用 image 吧

**Comment by Kang127** [comment]
> 可以设置等级色，其他的不行了。如果是这样，其实不算是iconfont了，iconfont本质上是一个文本，一个文本每个比划肯定不能设置不同的颜色呀，除非使用多个文本去拼，每个字就可以不一样颜色。这种需求还是用image吧
恩，好的，今天就是测试一下iconfont能不能满足，感觉image没有iconfont性能高

**Comment by Yanyan-Wang** [comment]
>恩，好的，今天就是测试一下iconfont能不能满足，感觉image没有iconfont性能高

这个不一定
