### ISSUE TITLE
可不可以出一个较为全面的配制清单

### ISSUE THREAD

**Issue by qiaozhi520** [antvis/G6#2206]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现在的文档有是一个教程，我并不是每次都需要去看那些东西，里面的配制清单省略了很多，而且没有搜索功能，还分了级，每次找配制都要找很久，特别浪费时间，文档里的链接也有问题，比如我点击查看 g6中的mode文档，跳转后还是当前界面，能跳转过去查看，清单里又是省略了大部分，让人有些摸不着头脑，开发的项目大多都不是从头开始开发，很多时候修改一个东西我只是需要知道这个参数是干嘛的就行

### What does the proposed API look like?
出一个配制清单，简单明了，方便查阅

**Comment by Yanyan-Wang** [comment]
https://g6.antv.vision/zh/docs/api/Graph

**Comment by Yanyan-Wang** [comment]
官网上方有搜索栏
