### ISSUE TITLE
怎么实现一个多对多的关系图谱

### ISSUE THREAD

**Issue by zgentle** [antvis/G6#2207]
![image](https://user-images.githubusercontent.com/43197224/96553626-032e2300-12e8-11eb-8dc0-4b62d2960d57.png)

类似这样的

**Comment by Yanyan-Wang** [comment]
dagre 布局或自定义布局

**Comment by webmrxu** [comment]
好像是没有这种实现，只能实现，一对多，或者多对一

**Comment by Yanyan-Wang** [comment]
树图 TreeGraph 在数据结构上就规定了不可以多对多，一个节点有且仅有一个父节点。上图可以用一般图 Graph，用 dagre 布局或自定义布局

**Comment by Huichifangqiu** [comment]
麻烦问下最后实现没

**Comment by webmrxu** [comment]
没有



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月4日(周五) 晚上7:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [antvis/G6] 怎么实现一个多对多的关系图谱 (#2207)




 
麻烦问下最后实现没
