### ISSUE TITLE
请问这种从dom向画布拖dom生成canvas节点的功能有例子吗？

### ISSUE THREAD

**Issue by Superzzw1994** [antvis/G6#2210]
请问，节点的x,y是相对于画布原点的x,y吗？鼠标相对于页面的clientX,clientY和dom节点到页面的left和top怎么菜能转化为画布上的坐标呢？如果画布拖动的话，坐标是如何计算的？
<img width="1439" alt="WeChatd56f00129f3edceb492168d12e06dab5" src="https://user-images.githubusercontent.com/20533727/96663155-b3506a00-1382-11eb-95bf-9f4d6d83e798.png">

**Comment by baizn** [comment]
参考这里：https://g6.antv.vision/zh/docs/manual/introduction#%E5%8F%8B%E6%83%85%E9%93%BE%E6%8E%A5
