### ISSUE TITLE
combo动态连线效果

### ISSUE THREAD

**Issue by Kang127** [antvis/G6#2211]
请问，怎么在页面动态操作两个combo连接到一起（点击一个combo，拉着线点击另一个combo，然后两个combo连接到一起，需要这个效果，并非直接链接到一起），找了好久，没有找到demo

**Comment by Yanyan-Wang** [comment]
这个 demo 通过自定义交互实现节点之间创建边，可以仿造这个 demo，在 combo 上做监听。
https://g6.antv.vision/zh/examples/interaction/setMode

内置的 create-edge behavior 也是节点之间创建边，后续可以加上在 combo 间、combo 与节点间创建边的 feature
https://g6.antv.vision/zh/examples/interaction/createEdge

**Comment by secret1base** [comment]
> 这个 demo 通过自定义交互实现节点之间创建边，可以仿造这个 demo，在 combo 上做监听。 https://g6.antv.vision/zh/examples/interaction/setMode
> 
> 内置的 create-edge behavior 也是节点之间创建边，后续可以加上在 combo 间、combo 与节点间创建边的 feature https://g6.antv.vision/zh/examples/interaction/createEdge

在这两个例子中没有看到combo的动态连线功能
