### ISSUE TITLE
node:click和edge:click监听事件冲突

### ISSUE THREAD

**Issue by Kang127** [antvis/G6#2213]
我同时监听了node和edge的click事件，当我拖拽着一条线向一个node上放的时候，不会触发node的click事件，请问这个怎么解决？
      //监听点击节点。创建连线
        graph.current.on('node:click', (e) => {
            alert(1);
            creatEdge(e);
        });
        //监听创建连线时点击了空白，将删除此条连线
        graph.current.on('edge:click', (e) => {
            const currentEdge = e.item;
            if (edgeObj.current.addingEdge && edgeObj.current.edge === currentEdge) {
                graph.current.removeItem(edgeObj.current.edge);
                edgeObj.current.edge = null;
                edgeObj.current.addingEdge = false;
            }
        });

**Comment by Kang127** [comment]
@Yanyan-Wang 帮忙看一下，当鼠标拖着线的时候，node的click事件不会触发（已经把edge的click事件去掉，此时鼠标上带着连线）

**Comment by baizn** [comment]
参考这个 DEMO：https://g6.antv.vision/zh/examples/interaction/setMode
或者使用 create-edge 这个behaviors

**Comment by Kang127** [comment]
> 参考这个 DEMO：https://g6.antv.vision/zh/examples/interaction/setMode
> 或者使用 create-edge 这个behaviors
我就是参考这个demo写的，我本地就是有问题，找不到什么问题，只要鼠标上带有连线，就无法触发click事件。没有使用create-edge 的原因是，我要将combo和node连接。
目前我想到的解决办法是，更新连线的时候将坐标偏移1像素，就能解决这个问题。

**Comment by baizn** [comment]
只要鼠标上带有连线，就无法触发click事件是因为你鼠标在线上的，点击的时候触发的是 edge:click， 那你那种方案也可以的。
