### ISSUE TITLE
关于destroyPlugin

### ISSUE THREAD

**Issue by Superzzw1994** [antvis/G6#2215]
请问自定义plugin里面的destroyPlugin应该做些什么？
我现在自定义了一个插件，在G6容器组件卸载的时候执行graph.destory，但是下一次进入G6容器组件自定义的plugin的initPlugin没有执行，只在G6容器组件第一次渲染的时候执行了，请问是什么原因？

**Comment by Superzzw1994** [comment]
第二个问题，在组件卸载的时候，将存有 G6的ref实例置空即可解决。

**Comment by baizn** [comment]
destroyPlugin 中主要清除 initPlugin 中创建的 Plugin的 DOM 容器、如果有变量的话，也需要将这些变量值重置到初始化状态。
如 Tooltip 的 destroy 方法：
```
public destroy() {
    const tooltip = this.get('tooltip');

    if (tooltip) {
      let container: HTMLDivElement | null = this.get('container');
      if (!container) {
        container = this.get('graph').get('container');
      }
      container.removeChild(tooltip);
    }
  }
```

**Comment by Superzzw1994** [comment]
好的，谢谢大佬。

**Comment by handsomeCarl** [comment]
@baizn  您好 我想问一下自定义的 plugins 怎么能更新，因为拖拽的plugins 是根据条件变得

**Comment by yyxhqm** [comment]
您好，我也想问一下，plugins里面的TimeBar如何更新数据，时间轴的数据和图表的数据想同步更新

**Comment by JoseZhangSH** [comment]
> 您好，我也想问一下，plugins里面的TimeBar如何更新数据，时间轴的数据和图表的数据想同步更新

你好，我也遇到同样的问题，想问下你解决这个问题了吗？
