### ISSUE TITLE
节点收缩后的位置不在视野中时报错

### ISSUE THREAD

**Issue by CristinaTAT** [antvis/G6#2216]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/infallible-chandrasekhar-uwb71)

### Steps to reproduce
（将画布拖动至左上角后）点击 'click me!'即可

| Environment | Info |
|---|---|
| g6 | 3.8.1 |
| System | - |
| Browser | - |

**Comment by baizn** [comment]
是底层渲染引擎一个 BUG https://github.com/antvis/g/issues/638 ， 修复了 G6 同步更新后就可以解决。

**Comment by Yanyan-Wang** [comment]
v3.8.3 已修复
