### ISSUE TITLE
请问下通过锚点连接两个节点

### ISSUE THREAD

**Issue by Superzzw1994** [antvis/G6#2217]
<img width="365" alt="WeChat9b3a57306e30eef71e4f0e6433e90499" src="https://user-images.githubusercontent.com/20533727/96846970-2fcb7180-1485-11eb-8214-0a47f4144484.png">

请问，这种节点间通过按住锚点拉一条线来连线，从锚点拉出来的线用什么画？自定义edge还是path？
有例子吗？
谢谢。

**Comment by Yanyan-Wang** [comment]
用这个例子改造 https://g6.antv.vision/zh/examples/interaction/setMode

在锚点图形上做监听
