### ISSUE TITLE
官方例子里的点击节点创建边卡顿

### ISSUE THREAD

**Issue by Superzzw1994** [antvis/G6#2220]
https://github.com/antvis/G6/issues/2201
https://antv-g6.gitee.io/zh/examples/interaction/setMode

请问现在有解决方案吗？

**Comment by Yanyan-Wang** [comment]
没有感觉到卡顿。你的浏览器和操作系统是什么

**Comment by Superzzw1994** [comment]
chrome,mac，3.8.1版本G6，拖拽生成polyline卡顿。

**Comment by Yanyan-Wang** [comment]
创建边的过程中先用 'line'，创建完成后通过 graph.updateItem 更新为 'polyline' 可以作为替代方案。

**Comment by ounana** [comment]
遇到了类似的问题，创建线的时候mousemove过程卡顿。发布到线上卡本地开发不卡，其他同事的mac有开发阶段卡的问题，我的电脑是mac,chrome。
