### ISSUE TITLE
是否支持toolbar自定义组件渲染

### ISSUE THREAD

**Issue by emmaqiu** [antvis/G6#2223]
G6版本：3.8.1；
Vue版本： 2.6；

是否可以支持自定义组件渲染toolbar，支持点击事件交互
demo: https://codesandbox.io/s/elegant-sky-dk532?file=/src/App.vue

**Comment by baizn** [comment]
支持，参考这个：https://g6.antv.vision/zh/examples/tool/toolbar#self-toolbar
