### ISSUE TITLE
graph只响应container中的key*事件或者node增加node:key*事件

### ISSUE THREAD

**Issue by xiaohundun** [antvis/G6#2225]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在脑图外部使用快捷键不会被脑图响应

### What does the proposed API look like?
期望增加node:key*事件
```javascript
graph.on("node:keyup", (event) => {
}
```

**Comment by Yanyan-Wang** [comment]
`graph.on('keyup', e => {})` 事件是有的，请再详细描述一下你的原始需求。

**Comment by xiaohundun** [comment]
> `graph.on('keyup', e => {})` 事件是有的，请再详细描述一下你的原始需求。

是有这个事件绑定，但是这个绑定会响应所有地方触发的键盘事件（即使当前焦点已经在画布外面），能否做到只响应画布里的或者节点上的键盘事件呢？

**Comment by xiaohundun** [comment]
绑定canvas的交互事件，在合适的时候绑定与解绑keyup事件

**Comment by StarkShang** [comment]
@Yanyan-Wang 是否只监听canvas处于focus状态下的键盘事件  或者在keyup事件中如何判断当前是否canvas被激活？
否则操作页面上其他元素时候也会触发canvas的键盘事件

**Comment by jiaoguanwen** [comment]
same question

**Comment by Yanyan-Wang** [comment]
可以监听 graph.on('focus', e => {}), graph.on('blur', e => {}) 记录图的激活状态
