### ISSUE TITLE
node:click 在清空画布重新渲染之后 点击事件会多次触发

### ISSUE THREAD

**Issue by fanrax** [antvis/G6#2226]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://www.baidu.com](http://www.baidu.com)

### Steps to reproduce
    graph.clear()
    graph.read(data)

 graph.on("node:click", evt => {})

| Environment | Info |
|---|---|
| g6 | 3.8.1 |
| System | windows7 |
| Browser | chrome |

**Comment by Yanyan-Wang** [comment]
没有复现。请给出最小复现在线 demo

**Comment by fanrax** [comment]
代码  如下  每次更新完数据都重新渲染画布  先clear() 然后read(data)
![812073F6-CDCC-4fd8-A2EB-53E0AFA88F67](https://user-images.githubusercontent.com/39158061/97398869-e8caf980-1926-11eb-900c-39d3dac49056.png)
图中的on:click中点击会触发下面的console
第一次点击的效果如下
![3B08ABB5-97DB-4382-BAF5-E9FE9F4B3750](https://user-images.githubusercontent.com/39158061/97398954-1617a780-1927-11eb-9afc-1f05c0d03205.png)
第二次点击的效果如下
![BBD51537-DAE8-415e-A4A2-6A32CF464CD4](https://user-images.githubusercontent.com/39158061/97398991-292a7780-1927-11eb-8e1a-9fca8a9e66ec.png)
主要问题就是为什么我在更新完数据重新渲染画布的时候点击事件触发了2次？
如果第三次点击这个事件会触发6次  总感觉是什么东西没有完全清除干净

**Comment by Yanyan-Wang** [comment]
写成在线 demo 吧

**Comment by fanrax** [comment]
不好意思 耽误了这么多天才回复，这个是我自己的问题，主要原因是在清除画布的同时忘记清除相应的方法了    这上面的事件绑定是和addeventListener一样的     ，我在加了解除绑定（graph.off）之后功能就好了

**Comment by Yanyan-Wang** [comment]
好的呢，解决了就好，那就先关闭了
