### ISSUE TITLE
tooltip 如何延迟显示

### ISSUE THREAD

**Issue by WGL878420** [antvis/G6#2227]
tooltip 展示的数据需要从后端获取 不想鼠标一滑动就获取展示 tooltip ，当鼠标不动的一段时间后展示tooltip。如何配置延迟？

**Comment by Yanyan-Wang** [comment]
暂时没有提供内置的这个能力，可以考虑今后添加，也欢迎 pr。
现在可以通过自己监听 node:mouseenter 或者 node:mousemove 等事件，在节点的位置上放置一个 dom 作为你的 tooltip，这样可以自己加 debounce 或者 throttle。放置 dom 的方法参考：https://g6.antv.vision/zh/docs/manual/advanced/coordinate-system

**Comment by WGL878420** [comment]
好的
