### ISSUE TITLE
svg模式下箭头显示bug

### ISSUE THREAD

**Issue by 18710123784** [antvis/G6#2229]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g6.antv.vision/zh/examples/tree/customItemTree](https://g6.antv.vision/zh/examples/tree/customItemTree)

### Steps to reproduce
设置renderer: 'svg'剪头就会显示错误

| Environment | Info |
|---|---|
| g6 | 3.8.0 |
| System | - |
| Browser | - |

![image](https://user-images.githubusercontent.com/23441784/97149129-40425b80-17a7-11eb-9300-4c331a0f2734.png)
![image](https://user-images.githubusercontent.com/23441784/97149154-489a9680-17a7-11eb-94cc-d015a71ec76e.png)

**Comment by Yanyan-Wang** [comment]
svg 箭头的自身坐标系与 canvas 的 x 方向相反，参考这个文档：https://g6.antv.vision/zh/docs/manual/middle/elements/edges/custom-edge#4-%E8%87%AA%E5%AE%9A%E4%B9%89%E7%AE%AD%E5%A4%B4

svg 的箭头相当于旧版本自定义箭头的坐标系（左图），canvas 在新版本中的坐标系如右图
![image](https://user-images.githubusercontent.com/29593318/97251821-982ea000-1843-11eb-923f-b896e3c1096d.png)

**Comment by 18710123784** [comment]
> svg 箭头的自身坐标系与 canvas 的 x 方向相反，参考这个文档：https://g6.antv.vision/zh/docs/manual/middle/elements/edges/custom-edge#4-%E8%87%AA%E5%AE%9A%E4%B9%89%E7%AE%AD%E5%A4%B4
> 
> svg 的箭头相当于旧版本自定义箭头的坐标系（左图），canvas 在新版本中的坐标系如右图
> ![image](https://user-images.githubusercontent.com/29593318/97251821-982ea000-1843-11eb-923f-b896e3c1096d.png)

这文档是不是加个标注啊，不然不知道

**Comment by 18710123784** [comment]
fill参数失效，箭头没有填充

**Comment by zk923852367** [comment]
终于找到了问题
