### ISSUE TITLE
With the standard solution of line break inside <text> using \ n, tags <tspan> shown as string and rendered

### ISSUE THREAD

**Issue by nika-sukhorukova** [antvis/G6#2231]
- **G6 Version**: 3.2.15
- **Platform**: ReactJS

I am working with rendering an element to canvas. Label text is added using group.addShape
During work, a problem arose: I need to wrap the label on two lines inside the <text> tag. In your documentation, I found an indication that if the label is too long, I need to use the standard line break indication with \ n
however, then I have a problem that the entire layout inside the <text>, namely the <tspan> is completely displayed as a string in my component ... Is there any way to add wrapped text via addShape (text)

**Comment by Yanyan-Wang** [comment]
Check out this demo pls: https://g6.antv.vision/zh/examples/item/label#labelLen1
And see if there is any different between your implementation and this demo

**Comment by nika-sukhorukova** [comment]
The problem is I am using the group.label method for rendering
 group.addShape ('text', {
attrs: {
text: group.labelText (this is where the label line goes, and if there is a line that needs to be wrapped, the whole tspan layout goes to the line)
},

It looks something like this <text>&lt;tspan x="45.25" dy="0em"&gt;CHAR&lt;/tspan&gt;&lt;tspan x="45.25" dy="1em"&gt;INDEX&lt;/tspan&gt;</text>

**Comment by Yanyan-Wang** [comment]
You'd better update the G6 to the latest version v4.0.2. And, I'm not sure whether the method `group.labelText` exist in v3.2.x. But in latest version, `text` should be a string but not HTML DOMs

**Comment by Yanyan-Wang** [comment]
Hi, dear user. Since there was no response for a long time, we cannot figure out the answer of the problem you described. If there is new progress, feel free to open a new issue.
