### ISSUE TITLE
ModelConfig中的stateStyles能否与setState共存

### ISSUE THREAD

**Issue by zhandouxiaojiji** [antvis/G6#2232]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
用stateStyles定义图形的状态样式非常方便，但有些地方不得不要用到setState来自定，但是一旦设置了setState，stateStyles的定义就失效了，必须所有的样式都要在setState重定义。是否可以提供一个方法能够在setState内设置stateStayles的样式。

### What does the proposed API look like?
```typescript
import G6 from '@antv/g6';
G6.registerNode(
  'TreeNode',
  {
    options: {
      type: 'rect',
      labelCfg: {
        style: {
          fill: 'blue',
          fontSize: 10
        }
      },
      style: {
        fill: "white",
      },
      stateStyles: {
        selected: {
          'main-box': {
            stroke: 'black',
            lineWidth: 3,
          },
        },
        hover: {
          stroke: 'white',
          lineWidth: 3,
        },
      },
    },
    setState: (name, value, item) => {
      if(name == "customState") {
        // todo 
      } else {
        item.setStateStyle(name, value);
      }
    } 
  }
)
```
代码中的customState是自定义的状态样式，而用新的API, setStateStyle来设置其它在stateStyles中已经定义好样式

**Comment by Yanyan-Wang** [comment]
复写 setState 就覆盖了内置的 setState 方法中对状态样式的更新逻辑。复写 setState 的原始需求是什么呢

**Comment by zhandouxiaojiji** [comment]
比如图标的切换，stateStyles貌似做不到吧？只能复写setState，但是其它简单的状态样式可以用stateStyles配置，如果都在setState里写，就得写很多if else，swith之类的，还要找到相应的形状，感觉不是很方便

**Comment by Yanyan-Wang** [comment]
可以的，可以指定 shape 的 name 更改它的样式
```
'TreeNode-icon': {
  img: 'https://gw.alipayobjects.com/mdn/rms_f8c6a0/afts/img/A*wCxXSK4eWPoAAAAAAAAAAAAAARQnAQ'
}
```
其他更多额外的样式修改也可以通过 graph.updateItem 来更新

**Comment by zhandouxiaojiji** [comment]
了解，感谢解答
