### ISSUE TITLE
Unable to render node when using node type extended from modelRect with a description

### ISSUE THREAD

**Issue by francisfeng** [antvis/G6#2235]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/broken-surf-scovr?file=/index.js)

### Steps to reproduce
Use the link in CodeSandbox and uncomment line 39 in index.js. The node would disapper without any console errors.

I found something similar in this issue: https://github.com/antvis/G6/issues/2134.

| Environment | Info |
|---|---|
| g6 | 3.8.2 |
| System | macOS 10.15 |
| Browser | Chrome Version 86.0.4240.111 |

**Comment by Yanyan-Wang** [comment]
thanks, it will be fixed in 3.8.3

**Comment by Yanyan-Wang** [comment]
fixed, checkout 3.8.3
