### ISSUE TITLE
有只更新图数据，不更新图状态和布局的方法吗

### ISSUE THREAD

**Issue by emmaqiu** [antvis/G6#2236]
请问有只更新图数据，不更新图状态（例如click状态）和布局（例如拖动了节点以后的布局）的方法吗

**Comment by Yanyan-Wang** [comment]
数据被替换之后，相当于重新生成的节点，之前节点状态就不会保留了。

如果要保留布局，v3.8.3 增加了 graph.clearLayout，可以在 changeData 之前调用，就是销毁布局方法，在 changeData 之后不会用之前的布局方法进行布局。你可以记录一下 changeData 之前数据中节点的 x y（也就是之前布局的结果），赋值到新数据对应的节点上，这样 changeData 之后就会使用新数据中的 x y 信息来放置节点。 

[clearLayout 文档](https://g6.antv.vision/zh/docs/api/Graph#destroylayout)

**Comment by emmaqiu** [comment]
> 数据被替换之后，相当于重新生成的节点，之前节点状态就不会保留了。
> 
> 如果要保留布局，v3.8.3 增加了 graph.clearLayout，可以在 changeData 之前调用，就是销毁布局方法，在 changeData 之后不会用之前的布局方法进行布局。你可以记录一下 changeData 之前数据中节点的 x y（也就是之前布局的结果），赋值到新数据对应的节点上，这样 changeData 之后就会使用新数据中的 x y 信息来放置节点。
> 
> [clearLayout 文档](https://g6.antv.vision/zh/docs/api/Graph#destroylayout)



> clearLayout

1.文档里没有clearLayout，有destroyLayout
2.不管是调用clearLayout还是destroyLayout，提示报错（版本：3.8.3）：
Uncaught TypeError: graph.destroyLayout is not a function
    at eval (index.js? [sm]:422)

**Comment by gafish** [comment]
> > 数据被替换之后，相当于重新生成的节点，之前节点状态就不会保留了。
> > 如果要保留布局，v3.8.3 增加了 graph.clearLayout，可以在 changeData 之前调用，就是销毁布局方法，在 changeData 之后不会用之前的布局方法进行布局。你可以记录一下 changeData 之前数据中节点的 x y（也就是之前布局的结果），赋值到新数据对应的节点上，这样 changeData 之后就会使用新数据中的 x y 信息来放置节点。
> > [clearLayout 文档](https://g6.antv.vision/zh/docs/api/Graph#destroylayout)
> 
> > clearLayout
> > @Yanyan-Wang  谢谢, 但有问题：
> > 1.文档里没有clearLayout，有destroyLayout
> > 2.不管是调用clearLayout还是destroyLayout，提示报错（版本：3.8.3）：
> > Uncaught TypeError: graph.destroyLayout is not a function
> > at eval (index.js? [sm]:422)

我用的 @antv/g6 4.1.12，我把graph实例在控制台打印出来看了下，确实只有 destroyLayout，我猜想是把 clearLayout 重命名为了 destroyLayout，而且经过实践也证明了我的猜想，功能是一样的，用 destroyLayout 解决了你提到的问题，我也遇到类似的问题，在你这个issues下找到了解决办法
