### ISSUE TITLE
通过鼠标在线上(edge)添加折点(ControlPoint) ，需要确定新加的折点在 ControlPoints数组中的位置

### ISSUE THREAD

**Issue by acodeman** [antvis/G6#2238]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
鼠标在线上点击添加折点时，很难确定新加入的折点在 ControlPoints数组中位置，导致线在绘制的时候会不是按照用户要求绘制

### What does the proposed API look like?
给定坐标polint(x,y) 能够返回 point 在 edge.ControlPoints 数组中的位置。

**Comment by Yanyan-Wang** [comment]
暂不考虑支持这一需求，欢迎社区共建～

图编辑的需求建议使用 AntV/X6 http://x6.antv.antgroup.com/
