### ISSUE TITLE
组合撤销时，拖拽的过程也记录到了undoStack中，导致undo时无法一步撤销到上一个拖拽状态

### ISSUE THREAD

**Issue by qiangshushu** [antvis/G6#2239]
自定义组合或者使用内置组合都会存在此问题，undoStack中增加了多条记录，单个节点拖拽没有问题。undoStack中只增加了一条记录。

**Comment by Yanyan-Wang** [comment]
请提供最小复现的在线 demo

**Comment by qiangshushu** [comment]
> 请提供最小复现的在线 demo

`
/*
* 粘贴到这里面  https://g6.antv.vision/zh/examples/tool/toolbar
* 然后尝试拖拽组合后，再按撤销
*/  

import G6 from '@antv/g6';
import insertCss from 'insert-css';

// 我们用 insert-css 演示引入自定义样式
// 推荐将样式添加到自己的样式文件中
// 若拷贝官方代码，别忘了 npm install insert-css
insertCss(`
  .g6-component-toolbar li {
    list-style-type: none !important;
  }
`);

const data = {
  nodes: [
    {
      id: '0',
      label: 'node-0',
      x: 100,
      y: 100,
      description: 'This is node-0.',
      subdescription: 'This is subdescription of node-0.',
      comboId: 'combo1'
    },
  ],
  combos:[{
      id: 'combo1'
  }]
};
const width = document.getElementById('container').scrollWidth;
const height = document.getElementById('container').scrollHeight || 500;

const toolbar = new G6.ToolBar();

const graph = new G6.Graph({
  container: 'container',
  width,
  height,
  linkCenter: true,
  plugins: [toolbar],
  // 设置为true，启用 redo & undo 栈功能
  enabledStack: true,
  defaultNode: {
    size: [80, 40],
    type: 'rect',
    style: {
      fill: '#DEE9FF',
      stroke: '#5B8FF9',
    },
  },
  defaultEdge: {
    style: {
      stroke: '#b5b5b5',
      lineAppendWidth: 3,
    },
  },
  modes: {
    default: ['drag-node','drag-combo'],
  },
});
graph.data(data);
graph.render();`

**Comment by Yanyan-Wang** [comment]
谢谢，下个小版本会跟进一下

**Comment by Yanyan-Wang** [comment]
最新版本修复成改变 combo 层级会被记录到 stack 中了，但是和移动节点是两个步骤，也就是说，当移动一个节点进入一个 combo，需要点 undo 两次才会回到未移动节点且不属于 combo 的情况。暂时还没有想到完美解决该问题的方案

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
