### ISSUE TITLE
G6的网图编辑器中  改变了节点数据，重新渲染页面时旧的Dom没删除 怎么解决

### ISSUE THREAD

**Issue by NuliNuli** [antvis/g6#224]
G6的网图编辑器中  改变了节点数据，重新渲染页面时旧的Dom没删除 怎么解决？旧的dom未删除，导致网图出现了很多个，只有最后一个的是数据修改过的  这应该怎么处理

**Comment by TomHuangCN** [comment]
调销毁方法啊，net.destroy()
