### ISSUE TITLE
当渲染的shape为图片的时候，一直在请求拿图片数据。特别消耗浏览器性能

### ISSUE THREAD

**Issue by wustzhaohui** [antvis/G6#2242]
- **G6 Version**: 3.2.3
- **Platform**: Chrome86.0.4240.111（正式版本） (x86_64)
- **Mini Showcase(like screenshots)**: 
![image](https://user-images.githubusercontent.com/19912085/97426413-69512080-194e-11eb-9acd-67a3958c9038.png)
![image](https://user-images.githubusercontent.com/19912085/97426536-900f5700-194e-11eb-941e-f3167e4bdb38.png)

- **CodePen Link**: [https://codepen.io/fred_zhao/pen/abZExEx](点击跳转)

**Comment by wustzhaohui** [comment]
做Promise处理是为了可以处理图片异常然后给到图片的默认值

**Comment by Yanyan-Wang** [comment]
应该是异常图片在渲染引擎内部没有处理。目前在给到 G6 图片之前，先检查一下异常图片吧

**Comment by wustzhaohui** [comment]
> 应该是异常图片在渲染引擎内部没有处理。目前在给到 G6 图片之前，先检查一下异常图片吧

。。。。我做了处理了，特意用promise处理了。。但是无限请求太可怕了，这个有解决方案么

**Comment by wustzhaohui** [comment]
> 应该是异常图片在渲染引擎内部没有处理。目前在给到 G6 图片之前，先检查一下异常图片吧

能处理下你们钉钉交流群的加群请求么？好久了都没有人通过

**Comment by wustzhaohui** [comment]
解决方案是在图片加载的时候处理一层，将图片转换成base64。然后再给到graph渲染。

**Comment by Yanyan-Wang** [comment]
> > 应该是异常图片在渲染引擎内部没有处理。目前在给到 G6 图片之前，先检查一下异常图片吧
> 
> 能处理下你们钉钉交流群的加群请求么？好久了都没有人通过

两个钉钉群都满了。。。。。有问题的话，建议还是在 issue 里提，我们看到的话会及时处理

**Comment by Yanyan-Wang** [comment]
> 解决方案是在图片加载的时候处理一层，将图片转换成base64。然后再给到graph渲染。

下个小版本我们内置处理掉
