### ISSUE TITLE
Force Layout中通过addItem增加的节点不指定x和y时，新添加进来的节点都是在[0,0]的位置，如何让新的节点位置是按照设施的布局方式分布的？场景是点击节点去拓展下层节点，希望之前的节点位置保持不变

### ISSUE THREAD

**Issue by cmh974007991** [antvis/G6#2243]
layout: {
                    type: 'force',
                    preventOverlap: true,
                    linkDistance: 200,
                    nodeSpacing: 60,
             }

**Comment by Yanyan-Wang** [comment]
addItem 之后再调用一下布局 graph.layout()，之前有位置的节点应该会以之前的位置为输入，在之前的位置上做微调

**Comment by Yanyan-Wang** [comment]
比如在这个例子中 https://g6.antv.vision/zh/examples/net/forceDirected

加这一段代码

```

    graph.on('canvas:click', e=>{
      graph.addItem('node', {
        id: `${Math.random}`
      });
      graph.layout();
    })
```
