### ISSUE TITLE
请问是否可以设置dagre布局的rank（层级）。

### ISSUE THREAD

**Issue by ColinCLL** [antvis/G6#2245]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
比如简单来说，类似，git主分支复制一条副分支出来之后主分支不提交了，在副分支提交。那么整个记录只有一条线，但应该岔开显示。是否有类似机制设置rank

### What does the proposed API look like?
可以主动设置rank分级

**Comment by Yanyan-Wang** [comment]
dagre 是 G6 引用了一个开源的库（https://github.com/dagrejs/dagre），专门做 dagre 布局，这个能力这个库没有。你的意思是希望第一层节点和第二层节点不对齐吗？如果是这样的话，有一个 hack 的方法，加一个透明的节点，和第二层节点的连接方式一样，相当于用一个透明节点占个位。

**Comment by ColinCLL** [comment]
谢谢你提供的方法。
另外的记得dagre好像是有。
https://github.com/dagrejs/dagre/issues/54
```js
g.addNode(0,  { label: 'TOP',       nodeclass: 'type-TOP',rank:'same_0' });
g.addNode(1,  { label: 'S',         nodeclass: 'type-S',rank:'same_1' });
g.addNode(2,  { label: 'NP',        nodeclass: 'type-NP',rank:'same_1' });
g.addNode(3,  { label: 'DT',        nodeclass: 'type-DT', rank:'same_2' });
```

我好像记得是有的。

**Comment by Yanyan-Wang** [comment]
看起来他们可能没有在他们的 wiki 上更新这个 feature，后面 G6 尝试一下看

**Comment by Cookie923** [comment]
> 谢谢你提供的方法。
> 另外的记得dagre好像是有。
> [dagrejs/dagre#54](https://github.com/dagrejs/dagre/issues/54)
> 
> ```js
> g.addNode(0,  { label: 'TOP',       nodeclass: 'type-TOP',rank:'same_0' });
> g.addNode(1,  { label: 'S',         nodeclass: 'type-S',rank:'same_1' });
> g.addNode(2,  { label: 'NP',        nodeclass: 'type-NP',rank:'same_1' });
> g.addNode(3,  { label: 'DT',        nodeclass: 'type-DT', rank:'same_2' });
> ```
> 
> 我好像记得是有的。

最新版本（v0.8.5）没有addNode这个方法了，好像也不支持rank了…
主动设置层级这块，大佬，这块你是怎么实现的？

**Comment by Yanyan-Wang** [comment]
目前版本已经支持在节点数据中配置 rank，来指定节点在 dagre 布局中的层级，欢迎试用

**Comment by xinxin2015** [comment]
> 目前版本已经支持在节点数据中配置 rank，来指定节点在 dagre 布局中的层级，欢迎试用

有没有文档或者样例，我看DagreLayout实现中没找到有关rank的信息

**Comment by Yanyan-Wang** [comment]
> > 目前版本已经支持在节点数据中配置 rank，来指定节点在 dagre 布局中的层级，欢迎试用
> 
> 有没有文档或者样例，我看DagreLayout实现中没找到有关rank的信息

嗷写错了，不是 rank，指定层级用 layer http://g6.antv.antgroup.com/api/graphlayout/dagre#%E6%8C%87%E5%AE%9A%E8%8A%82%E7%82%B9%E5%B1%82%E7%BA%A7

**Comment by MwumLi** [comment]
> > > 目前版本已经支持在节点数据中配置 rank，来指定节点在 dagre 布局中的层级，欢迎试用
> > 
> > 
> > 有没有文档或者样例，我看DagreLayout实现中没找到有关rank的信息
> 
> 嗷写错了，不是 rank，指定层级用 layer http://g6.antv.antgroup.com/api/graphlayout/dagre#%E6%8C%87%E5%AE%9A%E8%8A%82%E7%82%B9%E5%B1%82%E7%BA%A7

这个文档现在在哪里呢？点过去啥都看不到，搜索 layer 也搜索不到

**Comment by MwumLi** [comment]
找到了，自 G6 v4.5.0 起支持。  
http://g6.antv.antgroup.com/api/graph-layout/dagre#%E6%8C%87%E5%AE%9A%E8%8A%82%E7%82%B9%E5%B1%82%E7%BA%A7

> > > > 目前版本已经支持在节点数据中配置 rank，来指定节点在 dagre 布局中的层级，欢迎试用
> > > 
> > > 
> > > 有没有文档或者样例，我看DagreLayout实现中没找到有关rank的信息
> > 
> > 
> > 嗷写错了，不是 rank，指定层级用 layer http://g6.antv.antgroup.com/api/graphlayout/dagre#%E6%8C%87%E5%AE%9A%E8%8A%82%E7%82%B9%E5%B1%82%E7%BA%A7
> 
> 这个文档现在在哪里呢？点过去啥都看不到，搜索 layer 也搜索不到
