### ISSUE TITLE
清空edge线的状态时，会出现线的状态清空，画布上线的样式未及时更新问题

### ISSUE THREAD

**Issue by fively** [antvis/G6#2246]
初始化时设置默认样式：
```
defaultEdge: {
    style: {
        lineAppendWidth: 10,
        cursor: 'pointer'
    },
    labelCfg: {
        style: {
            fill: '#BFBFBF',
            cursor: 'pointer',
            fontSize: 12,
            background: {
                fill: '#ffffff',
                padding: [2, 2, 2, 2],
                radius: 2,
                textAlign: 'center'
            }
        }
    }
},
edgeStateStyles: {
    selected: {
        stroke: '#2F5AFF',
        lineWidth: 2
    },
    hover: {
        stroke: '#2F5AFF',
        lineWidth: 2
    }
},
```
点击线时设置线的样式selected。
点击画布时，做清空线的状态问题：`this.graph.clearItemStates(edge)`
问题1：清空后画布上的线未及时取消selected状态。
问题2：线的label设置内容后，再次设置label=null时，画布上线的label未及时清空

目前暂时“问题1”的解决方式：
添加了个default样式，
```
edgeStateStyles: {
    default: {
        stroke: '#D9D9D9',
        lineWidth: 1
    },
    selected: {
        stroke: '#2F5AFF',
        lineWidth: 2
    },
    hover: {
        stroke: '#2F5AFF',
        lineWidth: 2
    }
},
```
清空线的状态后，对线添加default状态：`this.graph.setItemState(edge, 'default', true)`

“问题2”的解决方式：删除线，重新画线

希望得到官方支持，以上两个问题看如何解决更合理？

**Comment by Yanyan-Wang** [comment]
两个问题没有复现：https://codesandbox.io/s/laughing-meitner-7mqtx?file=/index.js

在这个 demo 中，点边会设置边的 selected 状态，点击画布清空状态。点击节点，设置边的 label

可以 fork 上面链接这个 demo，复现出你的问题

**Comment by Heheroes** [comment]
这个问题是存在的，按照官方示例添加节点和线的高亮状态，鼠标划出节点之后只有节点的状态复原了，线没复原，把官网图表示例交互=>高亮相邻节点=>自定义高亮的代码复制下来，问题就会出现。
function clearAllStats() {
        graph.setAutoPaint(false);
        graph.getNodes().forEach(function (node) {
          graph.clearItemStates(node);
        });
        graph.getEdges().forEach(function (edge) {
          graph.setItemState(edge, "defaultStyle", true);  // 添加此行代码  edgeStateStyle里添加一个自定义一个默认状态。
          graph.clearItemStates(edge);
        });
        graph.paint();
        graph.setAutoPaint(true);
      }
目前在清楚edge状态之前，在新增一个默认状态可以解决。

**Comment by Yanyan-Wang** [comment]
v4.0.2 可以试一下

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。

**Comment by yangnuowei88** [comment]
必现的一个bug
