### ISSUE TITLE
G6 registerNode 为正方形，怎么添加文本

### ISSUE THREAD

**Issue by alexpande** [antvis/g6#225]
G6 registerNode 为正方形，怎么添加文本
G6.registNode('customNode1', {
    draw(cfg, group) {
      const shape = group.addShape('rect', {
        attrs: {
          x: cfg.x - 40,
          y: cfg.y - 40,
          width: 80,
          height: 80,
          stroke: 'gray'
        }
      });
      return shape;
    }
  }, 'customNode1');

**Comment by TomHuangCN** [comment]
https://antv.alipay.com/zh-cn/g6/1.x/api/canvas.html#_%E6%96%87%E6%9C%AC-text
