### ISSUE TITLE
IGraph.on(evt, callback) 里的 callback 类型推断是否可以更加精确? 以及是否能够暴露更多类型接口?

### ISSUE THREAD

**Issue by hacker0limbo** [antvis/G6#2250]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-antv-g6-bug-befn5?file=/src/DemoGraph.tsx)

### Steps to reproduce
在做事件监听之后, event handler 的类型推断是否可以更加精确? 比如最简单的一个例子如下:

```typescript
// import { IG6GraphEvent } from "@antv/g6";
import { IG6GraphEvent } from "@antv/g6/lib/types";

graph.on('node:mouseenter', (evt: IG6GraphEvent) => {
  console.log(evt.item)
})
```

上述代码使用 typescript 有以下几个问题:

- 这里的 `on` 监听事件之后, 原则上 `evt` 应该为 [`IG6GraphEvent`](https://github.com/antvis/G6/blob/649d41132641f7c71da3a528d2b140ab6be75391/src/types/index.ts#L14), 但是似乎 `on` 里推断出来的仅仅为简单的 `Function` 类型. 原因猜测为: 查看了一下 `Graph` 的类型定义 [`IGraph`](https://github.com/antvis/G6/blob/649d41132641f7c71da3a528d2b140ab6be75391/src/interface/graph.ts#L33), 是继承了一个 [`EventEmitter`](https://github.com/antvis/event-emitter/blob/master/src/index.ts#L20). 这里 `on` 里的 `callback` 类型确实为 `Function`, 所以是否可以优化为更精确的 `IG6GraphEvent`?
- `IG6GraphEvent` 这个类型定义似乎并没有在 `@antv/g6` 默认导出, 我需要手动到编译之后的 `@antv/g6/lib/types` 里导入. 不知道我这样的导入是否正确或者后续有计划会暴露更多的接口类型?

| Environment | Info |
|---|---|
| g6 | 3.8.3 |
| System | - |
| Browser | - |

**Comment by Yanyan-Wang** [comment]
感谢，接下来的小版本会跟进一下
