### ISSUE TITLE
请问如何在树状图中实现悬停或双击等操作来显示一些补充的内容

### ISSUE THREAD

**Issue by zhoulukuan** [antvis/G6#2251]
树状图的节点一般比较简略，我希望在交互中加入一些补充说明内容。例如节点可能是：
根节点：水果
一级节点：苹果，香蕉，橘子
二级节点：苹果下，红苹果、青苹果等
在不影响折叠功能的前提下，可否添加自定义的补充内容？例如在青苹果的节点上悬停或者双击，可以显示我自定义的说明内容：颜色是青的苹果，果酸含量更高，味道酸甜。在不进行上述交互的时候，仅展示正常的节点内容。
目前支持实现类似的功能吗？

**Comment by Yanyan-Wang** [comment]
你说的应该是 tooltip 吧，看下这个 demo https://g6.antv.vision/zh/examples/tool/tooltip

**Comment by zhoulukuan** [comment]
@Yanyan-Wang 您好，使用之后tooltip会覆盖掉树状图的默认操作，导致双击展开/折叠节点不可用，请问如何避免？

**Comment by Yanyan-Wang** [comment]
你为什么要写两个 modes？都放在同一个 modes 下面啊

**Comment by zhoulukuan** [comment]
> 你为什么要写两个 modes？都放在同一个 modes 下面啊

可以了，谢谢
