### ISSUE TITLE
在Vite搭建的Vue项目中报错“GET http://localhost:3000/@modules/@antv/matrix-util/esm/mat3 net::ERR_ABORTED 500 (Internal Server Error)”

### ISSUE THREAD

**Issue by djytwy** [antvis/G6#2254]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/djytwy/vtu_vue3_vite](https://github.com/djytwy/vtu_vue3_vite)

### Steps to reproduce
启动项目，点击/g6进入G6页面 
![image](https://user-images.githubusercontent.com/30172796/97945584-ed7a2c80-1dc2-11eb-8429-cf19b8932ad9.png)

| Environment | Info |
|---|---|
| g6 | 3.8.3 |
| System | mac OS 10.15 |
| Browser | chrome 86.0.4240.111（正式版本） (x86_64) |

**Comment by Yanyan-Wang** [comment]
看下 node_modules 里面有没有@antv/matrix-util 这个包

**Comment by djytwy** [comment]
有的

**Comment by ycjcl868** [comment]
vite 不能直接使用吧，需要转成 esm

**Comment by Yanyan-Wang** [comment]
v4.0.2 试一下看

**Comment by djytwy** [comment]
> v4.0.2 试一下看

看了 #2338 问题解决了，谢谢

**Comment by djytwy** [comment]
太久远了，我记得我当时升级了ANTV，然后配置了vite.config.ts就行了
