### ISSUE TITLE
树图点击节点收缩时报错： Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by lgy1159** [antvis/G6#2256]
g6.min.js:15 Uncaught TypeError: Cannot read property 'length' of undefined
    at t (g6.min.js:15)
    at Object.t [as clearChanged] (g6.min.js:15)
    at e._drawRegion (g6.min.js:15)
    at g6.min.js:15

**Comment by Yanyan-Wang** [comment]
一定要确保每个节点都有唯一的、string 类型的字符串。

确定上述条件没问题后，如果还出现这个问题，请提供一下最先复现的在线 demo

**Comment by paradox010** [comment]
同出现这个问题，这个问题出现在：当某个节点的子节点过多占满屏幕时，收缩子节点会导致其他节点的位置都没了。（当屏幕足够大/节点足够小的时候，其他同级节点还在屏幕上就不会有这个问题）

**Comment by Yanyan-Wang** [comment]
> 收缩子节点会导致其他节点的位置都没

麻烦提供一下最小复现的在线 demo

**Comment by paradox010** [comment]
> > 收缩子节点会导致其他节点的位置都没
> 
> 麻烦提供一下最小复现的在线 demo

https://codesandbox.io/s/angry-bartik-7mfzm?file=/index.js
我测了一下，3.8.2版本以下，都会有这个bug，升到3.8.3就没事了

**Comment by Yanyan-Wang** [comment]
好的，最新版本没有这个问题就 ok，先关闭咯

**Comment by HuColin** [comment]
@antv/G6 4.8.24 同出现这个问题，在自定义节点的 setState 中，在对 group 进行 addShape 的时候
我的操作是（通过 addShape 给自定义节点添加边框）快速 hover 自定义节点来快速重复执行 setState，期间有大量 shape 的创建/销毁行为
之后浏览器爆出`Uncaught TypeError: Cannot read property 'length' of undefined` 的异常，通过定位发现如下位置抛出异常
<img width="833" alt="image" src="https://github.com/antvis/G6/assets/16102181/485b5077-03f2-40a8-bf6f-858d09f1db29">
这里 `cfg.children` 为 undefined，但是仍然调用自身递归，在下一步 for 循环的时候， `undefined.length` 报错
定位到应该是 g-canvas 库中 `clearChanged` 函数在 for 循环的时候没有对 children 判断是否为空
<img width="738" alt="image" src="https://github.com/antvis/G6/assets/16102181/929bf3f2-a3a8-459a-894a-ef532199da79">
