### ISSUE TITLE
graph.add添加节点

### ISSUE THREAD

**Issue by Kang127** [antvis/G6#2257]
使用graph.add方法，添加一个节点，节点内容是：一个长方形，里边是一张图片，请问这个可以实现吗？这个是动态添加的，初始化的时候画布上是空的。（只添加图片的话，没办法触发节点选中的效果）

**Comment by Yanyan-Wang** [comment]
可以自定义节点，参考这个例子右边那个节点  'inner-animate'，把动画去掉就行了
https://g6.antv.vision/zh/examples/scatter/node
