### ISSUE TITLE
lineHeight config in modelRect doesn't seem to work

### ISSUE THREAD

**Issue by francisfeng** [antvis/G6#2258]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cold-sky-grulx)

### Steps to reproduce
Changing `lineHeight` in `labelCfg` or `descriptionCfg` has no effect on the style of the node. Neither `lineHeight: 2` nor `lineHeight: 24px` worked.

| Environment | Info |
|---|---|
| g6 | 3.8.3 |
| System | macOS 10.15 |
| Browser | Chrome Version 86 |

**Comment by Yanyan-Wang** [comment]
Are you trying to make the description move down? If so, try `paddingTop`of `descriptionCfg`. [docs](https://g6.antv.vision/en/docs/manual/middle/elements/nodes/built-in/modelRect#descriptioncfg)

The lineHeight won't affect the positions of the shapes in the node. You can imagine that all the shapes are absolute positioned.

**Comment by francisfeng** [comment]
I see. And `paddingTop` can be negative, which is a surprise.

What I am really trying to do is to remove a little bit of space between label and description while keeping those two aligned in the middle. Simply changing `paddingTop` has no effect on the label.

I managed to acheive the desired style by utilizing `textBaseline`  in `labelCfg` and `descriptionCfg`. 

Just a small problem. The `label` positioned differently between not providing a  `description`  property and providing an empty description, which it's a little unexpected.
