### ISSUE TITLE
元素样式的继承问题

### ISSUE THREAD

**Issue by suziwen** [antvis/G6#2259]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/suziwen/pen/rNLrjjb](https://codepen.io/suziwen/pen/rNLrjjb)

### Steps to reproduce
我期望 a 节点最终样式是 **红色虚线边框** ,但显示的却是红色**实线**边框.

a 节点的 `lineDash` 样式并没有继承 `defaultNode` 里设置的 `lineDash`

| Environment | Info |
|---|---|
| g6 | 3.8.3 |
| System | linux |
| Browser | chrome |

---
怀疑是 G6 代码里没有对 style 等多级层属性进行深度合并继承, 而只是简单的覆盖继承.

**Comment by Yanyan-Wang** [comment]
是的，数据中的配置优先级高，会覆盖全局配置，文档中有说明：

https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/defaultNode#%E8%8A%82%E7%82%B9%E7%9A%84%E9%85%8D%E7%BD%AE%E6%96%B9%E6%B3%95

https://g6.antv.vision/zh/docs/manual/tutorial/elements#2-%E5%9C%A8%E6%95%B0%E6%8D%AE%E4%B8%AD%E9%85%8D%E7%BD%AE
