### ISSUE TITLE
toolTip里写回调函数返回值怎么写？

### ISSUE THREAD

**Issue by JacobYChan** [antvis/g6#226]
this.net.node().tooltip((obj) => {
        let arr =[]
       if(obj.type === 'double') {
         arr = [{'name': obj.name}, {'name2': obj.name2}]
       } else {
         arr = [{'name': obj.name}]
       }
        return arr
      })

比如我想根据model里某些字段进行判断来显示不同的toolTip，toolTip可能包含两个字段，这种场景应该怎么写？

**Comment by wangzhe110** [comment]
有没有有了告诉我

**Comment by JacobYChan** [comment]
我看g2里是要定义一个itemTpl，toolTip的返回值才有效
具体代码如下：
let itemTpl = '<li data-index={index} style="margin-bottom:4px;">'
              + '<span style="background-color:{color};" class="g2-tooltip-marker"></span>'
              + '{name}<br/>'
              + '<span style="padding-left: 16px">数值：{count}</span><br/>'
              + '<span style="padding-left: 16px">占比：{percent}</span><br/>'
              + '</li>'
this.chart.tooltip({
          showTitle: false,
          crosshairs: false,
          itemTpl: itemTpl
        })
然后再在一个判断tooltip,
this.net.node().tooltip('metricName*percent*count', (metricName, percent, count) => {
              return {
                name: metricName,
                percent: parseFloat(percent * 100).toFixed(2) + '%',
                count: count
              }
            })

不知道G6是怎么样设计的

**Comment by TomHuangCN** [comment]
g6 这个做得比较简单（简陋），返回二维数组 

```js
return [
  [name, value]
]
```
