### ISSUE TITLE
自定义边（path）的交互不起作用问题

### ISSUE THREAD

**Issue by emmaqiu** [antvis/G6#2260]
G6版本：3.8.3
demo：https://codesandbox.io/s/admiring-bird-yso3w?file=/index.js
问题：自定义边（path）, 交互不起作用
1.初始化后不是边的所有区域都有有效交互（例如demo中的hover效果，只有靠近右边节点的边区域有hover效果，靠近左边的边区域不起作用）
2.若拖动节点后，hover交互全部失效

**Comment by Yanyan-Wang** [comment]
底层渲染引擎的带 “A” 的路径貌似有点问题，试一下改成用 “C”，贝塞尔曲线模拟这个弧形看能不能满足你的需求

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
