### ISSUE TITLE
g6 layout  force布局  workerEnabled=true报错

### ISSUE THREAD

**Issue by shifengyun** [antvis/G6#2263]
Uncaught (in promise) DOMException:failed to execute 'postMessage' on 'Worker':[Object Object] could not be cloned

**Comment by Yanyan-Wang** [comment]
官网上没有出现这个问题。是如何出现的？是不是用了没构建之前的 G6 源码？需要 build 之后才能使用 worker

**Comment by shifengyun** [comment]
在vue3中   数据源是proxy对象    要转化为原始对象

**Comment by Yanyan-Wang** [comment]
> 在vue3中 数据源是proxy对象 要转化为原始对象

这样就可以解决了是吧？

**Comment by Yanyan-Wang** [comment]
我理解你的意思应该是这样就可以解决了吧，先关闭了，如果还有问题的话随时开新 issue

**Comment by edgexie** [comment]
@shifengyun 你好，怎么解决的，我也遇到了

**Comment by lulei90** [comment]
> 官网上没有出现这个问题。是如何出现的？是不是用了没构建之前的 G6 源码？需要 build 之后才能使用 worker

官网上面直接添加workerEnabled:true也是无效的
![Uploading image.png…]()

**Comment by wuhaoyue** [comment]
配置：![image](https://user-images.githubusercontent.com/69661496/229456514-7f2fe5e8-7daf-4dce-aae3-ca539854e10c.png)。
g6版本： "@antv/g6": "^4.8.8",。
使用的是vite+vue3。
报错信息：
![image](https://user-images.githubusercontent.com/69661496/229457122-a511c5e2-c113-4a8f-9a40-8e0c3f92668b.png)

**Comment by Yanyan-Wang** [comment]
更新一下 G6 版本到 4.8.9，已经解决

**Comment by wuhaoyue** [comment]
你好，g6自定义dom节点不支持使用svg吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Yanyan Wang ***@***.***&gt;
发送时间: 2023年4月8日 19:17
收件人: antvis/G6 ***@***.***&gt;
抄送: 吴杰 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [antvis/G6] g6 layout  force布局  workerEnabled=true报错 (#2263)





 
更新一下 G6 版本到 4.8.9，已经解决

**Comment by ninjaaaaah** [comment]
> 更新一下 G6 版本到 4.8.9，已经解决

仍然在 antv/g6 版本 4.8.14 上遇到错误。

**Comment by Heart-clearing** [comment]
do not use a reactive data as the parameter of graph.data in vue3.
use graph.data(toRaw(your reactive data)),I solved the problem with this way

**Comment by MoyuGua** [comment]
> do not use a reactive data as the parameter of graph.data in vue3. use graph.data(toRaw(your reactive data)),I solved the problem with this way

I use toRaw and check data again , but i not solved the problem
