### ISSUE TITLE
Is it possible to get a full graph in format for export?

### ISSUE THREAD

**Issue by mostopalove** [antvis/G6#2266]
Is it possible to get raw graph data with all elements on graph? Even custom elements.
It is necessary for creation custom import.

**Comment by Yanyan-Wang** [comment]
If you want to output the raw data, try `graph.save()`.

**Comment by mostopalove** [comment]
@Yanyan-Wang Yes, but this is not graphical data. I need graphics data to create an alternate import method. I need information about all graphic objects on the canvas.

**Comment by Yanyan-Wang** [comment]
By `graph.getGroup()`, you can get all the graphics groups and shapes on the canvas, but they are G(our rendering engine) objects. You might need to format them by yourself. About the objects of G, ref to https://g.antv.vision/en/docs/guide/introduce  (Sorry it is in Chinese, maybe you can translate the page automatically by some chrome plugins)

P.S. get all the attributes of a shape by shape.attr().

**Comment by mostopalove** [comment]
It didn't work for me, I attach the error.
_graph.getGroup is not a function:_
<img width="416" alt="Снимок экрана 2020-11-24 в 10 20 15" src="https://user-images.githubusercontent.com/49098339/100067310-c7cec900-2e3e-11eb-984f-56a47ed08bda.png">

**Comment by mostopalove** [comment]
@Yanyan-Wang can you give me an example to call it?

**Comment by Yanyan-Wang** [comment]
Which version of G6 are you using?

**Comment by mostopalove** [comment]
3.5.3

> Which version of G6 are you using?

**Comment by Yanyan-Wang** [comment]
you'd better update it to the latest version v4.0.2. Call graph.get('group') instead if you are still going to use v3.5.3

**Comment by mostopalove** [comment]
@Yanyan-Wang I am getting an Observer instance, but I need information about all the graphic objects on the canvas.
<img width="414" alt="Снимок экрана 2020-11-27 в 14 54 15" src="https://user-images.githubusercontent.com/49098339/100451859-c01e5700-30c0-11eb-9c6d-b4ac1e0984af.png">

**Comment by Yanyan-Wang** [comment]
```
const group = graph.getGroup();
const children = group.get('children') // the children are the shapes and the sub graphics group of the root group. if a child is a group, call children = group.get('children') to get its children continually
```

**Comment by Yanyan-Wang** [comment]
Hi, dear user. Since there was no response for a long time, we cannot figure out the answer of the problem you described. If there is new progress, feel free to open a new issue.

**Comment by mostopalove** [comment]
@Yanyan-Wang  Sorry for waiting. This is still not the result I expected. I want the node data with all the additional elements that I add during the rendering process. The data returned by the above function is not enough to create a vector import functionality.
