### ISSUE TITLE
希望G6可以支持移动端节点拖动/I hope that G6 can support the node-drag events for mobile devices.

### ISSUE THREAD

**Issue by xjx0106** [antvis/G6#2267]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
希望G6可以支持移动端，可以在移动端的图视图里拖动节点
I hope that G6 can support the node-drag events for mobile devices so that users are able to drag nodes by fingers on the android or ios devices.

### What does the proposed API look like?
/*这只是一个拖动事件的需求，类似于目前G6的canvas的拖动。你们团队可以自定代码的。*
/* this is a drag-event need, just like canvas-drag event do, so your team just define the code in your own way. */

**Comment by xjx0106** [comment]
anyone concerned about this issue...?? :(

**Comment by wulinsheng123** [comment]
any look like this libray ?

**Comment by wulinsheng123** [comment]
did you solve this problem ?

**Comment by wulinsheng123** [comment]
@xjx0106

**Comment by xjx0106** [comment]
@wulinsheng123 I use a webview component in react-native(android) and put g6 web page in it to bypass this issues.
