### ISSUE TITLE
在Vue中使用报错：TypeError: n.getDefaultCfg is not a function

### ISSUE THREAD

**Issue by phoenixgao** [antvis/G6#2268]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/happy-frost-ri4r3?file=/src/components/HelloWorld.vue)

### Steps to reproduce
初始化G6.Graph({...})即报错。见Sandbox链接中代码。

| Environment | Info |
|---|---|
| g6 | 3.8.3 |
| System | - |
| Browser | - |

**Comment by jean-lee** [comment]
const graph = new G6.Graph({
      container: this.$refs.container,
      width: 500,
      height: 600,
    });
    // graph.data(data);
    // graph.render();
    graph.read(data);

**Comment by phoenixgao** [comment]
@jean-lee  嗯，谢谢~~我看了很久才发现 所以一发现就惭愧得赶快close了 😹
