### ISSUE TITLE
在ie11中 后台报错 “对象不支持“getBBox”属性或方法”，请问怎么样才能兼容ie11

### ISSUE THREAD

**Issue by canifindyou** [antvis/G6#2271]
<!DOCTYPE html>
<html lang="en">

	<head>
		<meta charset="UTF-8">
		<title>流程图自定义元素</title>
		<style>
		</style>
	</head>

	<body>
		<button id="btn" style=" margin-left: 50%;transform: translateX(10px);">切换分支</button>
		<div class="box">
			<div id="mountNode"></div>
		</div>

		<script>
		</script>
		
		<script src="https://cdn.bootcdn.net/ajax/libs/babel-polyfill/7.12.1/polyfill.js"></script>
		<script src="https://gw.alipayobjects.com/os/lib/antv/g6/3.8.1/dist/g6.min.js"></script>
		
		
		
		<script>

        function computerText(){
                    var str ="这是一个测试数据信息过长"
                    var sArr = str.split("")
                    var len = sArr.length
                    if(len>=4){
                     sArr.splice(4, 0, "\n"); 
                    }
                    
                     return sArr.join("")
                }
			//测试数据
			var nodeArr = []

			var jd = [{
					"nodeId": "start",
					"nodeName": "开始",
					"relatedIds":[{id:"转折一",text:"测试数据"}]
				},
				{
					"nodeId": "转折一",
					"revision": 1,
					"nodeName": "转折一",
					"groupId": "4",
					"groupName": "申请人",
					"taskKey": "sq",
					"relatedIds": [{id:"准入申请",text:"测试数据"}, {id:"接样",text:"测试数据二"},],
					"flag": 1 //菱形标识
				}, {
					"nodeId": "准入申请",
					"revision": 1,
					"nodeName": "准入申请",
					"groupId": "4",
					"groupName": "申请人",
					"taskKey": "sq",
					"relatedIds":  [{id:"转折二",text:"测试数据"}],
				}, {
					"nodeId": "接样",
					"revision": 1,
					"nodeName": "接样",
					"groupId": "4",
					"groupName": "申请人",
					"taskKey": "sq",
					"relatedIds":  [{id:"转折二",text:"测试数据"}],
				}, {
					"nodeId": "自动分配分析模板",
					"revision": 1,
					"nodeName": "自动分配分析模板",
					"groupId": "4",
					"groupName": "申请人",
					"taskKey": "sq",
					"relatedIds":[{id:"化验分析",text:"测试数据"}],
				},
				{
					"nodeId": "转折二",
					"revision": 1,
					"nodeName": "转折二",
					"groupId": "4",
					"groupName": "申请人",
					"taskKey": "sq",
					"relatedIds": [{id:"分析单自动结束",text:"测试数据"},{id:"化验分析",text:"测试数据"}],
					"flag": 1 //菱形标识
				}, {
					"nodeId": "分析单自动结束",
					"revision": 1,
					"nodeName": "分析单自动结束",
					"groupId": "4",
					"groupName": "申请人",
					"taskKey": "sq",
					"relatedIds": [{id:"结束",text:"测试数据"}],
				}, {
					"nodeId": "化验分析",
					"revision": 1,
					"nodeName": "化验分析",
					"groupId": "4",
					"groupName": "申请人",
					"taskKey": "sq",
					"relatedIds": [{id:"结束",text:"测试数据"}],
				}, {
					"nodeId": "结束",
					"nodeName": "结束",
					"relatedIds": []
				},

			]
			//添加节点
			jd.forEach(function(item) {
				if (item.flag == 1) {
					nodeArr.push({
						id: item.nodeId,
						"shape": "diamond",
						"size": [50, 40],
						"label": "转折",
						"spjy": 123, //审批建议
						"source": item.nodeId,
						"next": constructNodes(item.relatedIds),
						linkPoints: {
							top: true,
							bottom: true,
							left: true,
							right: true,
							size: 5,
							fill: '#fff'
						},
						anchorPoints: [
							[0, 0.5],
							[1, 0.5]
						]
					})
				} else if (item.nodeName == "结束") {
					nodeArr.push({
						"id": item.nodeId,
						"shape": "circle",
						"size": 50,
						"label": "结束",
						"spjy": 123, //审批建议
					})
				} else if (item.nodeName == "开始") {
					nodeArr.push( //开始节点 固定添加开始节点
						{
							"id": item.nodeId,
							"label": "开始",
							"shape": "circle",
							"size": 50,
							"source": item.nodeId,
							"next": constructNodes(item.relatedIds)
						}
					)
				} else {
					nodeArr.push({
						id: item.nodeId,
						"borderStatus": computeColor(item.revision, item.outcome), //边框颜色值
						"backColor": compoteBackColor(item.revision), //左上角背景色
						"nowStatus": item.nodeName, //当前所在流程节点
						"name": item.assigneeName,
						"time": item.completedTime,
						"size": [200, 120],
						"spjy": item.approvalComments, //审批建议
						"source": item.nodeId,
                        "next": constructNodes(item.relatedIds), //指向的下一节点数组
					})
				}
			})

			//数据源结构
			var data = {
				nodes: [],
				edges: []
			};
			data.nodes = nodeArr;
			console.log(data)
			//渲染流程图
			constructEdage(jd);
			var gh = renderFn(data);
            //构造节点
            function constructNodes(arr){
                if(!arr){
                    return
                }
              var nodeArr = []
              arr.forEach(function(item){
                  nodeArr.push(item.id)
              })
              return nodeArr
            }
			//构造边连接
			function constructEdage(jd) {
				var edges = []
               
				jd.forEach(function(item) {
					if (item.relatedIds) {
						item.relatedIds.forEach(function(d, index){
							edges.push({
								source: item.nodeId,
								target: String(d.id),
                                label:d.text
							})
						})
					}
				})
				data.edges = edges;
                console.log(data)
			}
			//判断边框颜色值
			function computeColor(r, c) {
				if (r) {
					if (r == 1) {
						return '#FFC125'
					};
					if (r == 2) {
						if (c == 1 || c == 2) {
							return '#169bd5'
						};

					};

					if (c == 3 || c == 4 || c == 5) {
						return '#FF4500'
					}

					if (r == 3) {
						if (c == 2 || c == 1) {
							return '#169bd5'
						}
					}
				} else {
					return '#e0e0e0'
				};
			}
			//通过节点出现的次数 计算层级 设置画布高度
			function computeCount(e) {
				var count = 0;
				var maxCount = 0;
				var countArr = [];
				for (let i = 0; i < e.length; i++) { //遍历边对应的id 对"source"进行计数

					for (let j = 0; j < e.length; j++) {
						if (e[i].source == e[j].source) {
							count++;
						}
					}
					if (maxCount < count) {
						maxCount = count;
					}
					if (count > 1 && countArr.indexOf(count) < 0) {
						countArr.push(count);
					}
					count = 0;
				}
				var sum = 0;
				countArr.forEach(function(item) {
					sum += item;
				})
				console.log(countArr)

				return maxCount;

			}
			//计算上标识背景色
			function compoteBackColor(r) {
				if (r == 1 || !r) {
					return '#d1d1d1'
				};
			};

			function renderFn(data) {
				//计算层级
				var floorCount = computeCount(data.edges);
				console.log(floorCount);
				//画布宽度 在更改节点宽度时，需根据具体节点宽度对画布进行调整（节点宽度调整以后需要对节点之间的连线长度进行调整）
				var canvansWidth = (data.nodes.length) * 240;
				//保持画布宽度与容器宽度相同
				document.getElementById("mountNode").style.width = canvansWidth + "px";
				var canvansHeight = floorCount * 220;
				//保持画布高度与容器高度相同
				document.getElementById("mountNode").style.height = canvansHeight + "px";

				// 创建 G6 图实例
				const graph = new G6.Graph({
					renderer: 'svg',
					container: 'mountNode', // 指定图画布的容器 id
					// 画布宽高
					// fitView:true,
					// fitViewPadding: [ 20, 40, 50, 20 ],
					width: canvansWidth,
					height: canvansHeight,
					pixelRatio: 100,
					maxZoom: 0.9,
					animate: true,
					layout: {
						type: 'dagre', //层级自动布局
						rankdir: 'LR', // 从左向右渲染
						align: 'UL', // 可选
						nodesep: 20, // 节点层距离（上下）
						ranksep: 30, // 节点之间距离（左右）
						controlPoints: true,
						//  preventOverlap: true, 
					},
					defaultNode: {
						shape: "dom-node"
					},
					defaultEdge: {
						// shape: 'quadratic',
						shape: 'polyline',
						style: {
							endArrow: true,
							// radius: 5,
							// offset: 30,
							stroke: '#000',
							lineWidth: 2
						},
                        labelCfg: {
                            refY: 10,
                            }
					}
				});
				
                            // <div id=${cfg.id} class='dom_node' style="background-color: #fff; border: 1px solid ${cfg.borderStatus}; border-radius: 5px; width: ${cfg.size[0] - 5}px; height: ${cfg.size[1] - 5}px; display: inline-block;">
                            // <span class="smallStatus" style="background:${cfg.backColor}">${cfg.nowStatus}</span>
                            // <p  class="nodeItem first_item" ><span style="display: inline-block; float: left;">${cfg.nowStatus == "申请" ? "申请":"审批"}人:</span><span class="text_right">${cfg.name || ""}</span></p>
                            // <p class="nodeItem"><span >审批时间:</span><span style="display: inline-block; padding-left:1px" class="text_right">${cfg.time || " "}</span></p>
                            // <p class="nodeItem"><span style="display: inline-block; float: left;">审批意见:</span><span class="nodeText text_right">${cfg.spjy || " "}</span> </p>
                            // </div>
                        
				//重定义节点样式自定义节点
				G6.registerNode('dom-node', {
					draw: function(cfg, group){
						const htmlShape = group.addShape('dom', {
							attrs: {
								width: cfg.size[0],
								height: cfg.size[1],
								x: -cfg.size[0] / 2,
								y: -cfg.size[1] / 2,
								html:"<div>23456789</div>"
							},
						}, "rect");
						return htmlShape;
					},
					getAnchorPoints:function () {
						return [
							[0, 0.5], // 左侧中间
							[1, 0.5], // 右侧中间
							// [0.5, 1], // 上侧中间
							// [0.5, 0], // 下侧中间
							// [0, 0], // 右侧中间
							// [0, 1], // 右侧中间
						];
					},
				});
               
				//加载数据
				graph.data(data)
				// 渲染图
				graph.render();
				//返回实例对象，需要再刷新视图时，调用销毁对象方法
				return graph;
			}
		</script>
	</body>
	<style>
		body {
			margin: 0;
			padding: 0;
			width: 100%;
			height: 100%;
		}

		.box {
			width: 1800px;
			height: 550px;
			overflow-x: scroll;
			border: 1px solid #eee;
			white-space: nowrap;
			position: absolute;
			position: absolute;
			top: 50%;
			left: 50%;
			right: 0;
			bottom: 0;
			transform: translate(-50%, -50%);

		}

		.nodeItem {
			width: 195px;
			text-align: left;
			text-indent: 0.5em;
			color: gray;
			margin-bottom: 4px;
			word-wrap: break-word;
			word-break: break-all;
			font-size: 10px;
			overflow: hidden;

		}

		.dom_node {
			display: inline-block;
			vertical-align: middle;
			text-align: left;
			border: 1px solid lightgrey;
			border-radius: 5px;
			height: 130px;
			position: relative;
			overflow: hidden;
			width: 210px;
			font-size: 10px;
		}

		.first_item {
			margin-top: 22px;
		}

		.smallStatus {
			display: inline-block;
			position: absolute;
			top: 0;
			left: 0;
			background: #eee;
			height: 20px;
			padding: 0 5px 0 5px;
			font-size: 12px;
			border-radius: 3px 0 0 0;
			background: #169bd5;
			opacity: 0.9;
			border: 1px #fff solider;
			color: #fff
		}

		.nodeText {
			display: inline-block;
			width: 120px;
			white-space: normal;
			/* word-break: normal; */
			display: inline-block;
			word-wrap: break-word;
			overflow: hidden;
			padding: 0 0 5px 0;
			height: 35px;
			overflow-y: auto;
		}

		.text_right {
			color: #000
		}

		.nodeText::-webkit-scrollbar {
			width: 2px;
			height: 1px;
		}

		.nodeText::-webkit-scrollbar-thumb {
			border-radius: 10px;
			-webkit-box-shadow: inset 0 0 5px #eee;
			background: #535353;
		}

		.nodeText::-webkit-scrollbar-track {
			-webkit-box-shadow: inset 0 0 5px #fff;
			border-radius: 10px;
			background: #EDEDED;
		}
	</style>

</html>

**Comment by Heheroes** [comment]
getBBox是svg的方法吧，ie11如果支持画布渲染就应该是你的使用方式有问题。我记得是addItem或者remove的时候直接传对象会报这个错，你add或者remove之前先findById(节点Id)拿到节点

**Comment by canifindyou** [comment]
> getBBox是svg的方法吧，ie11如果支持画布渲染就应该是你的使用方式有问题。我记得是addItem或者remove的时候直接传对象会报这个错，你add或者remove之前先findById(节点Id)拿到节点


具体怎么操作，可以提示一下吗

**Comment by mark0325** [comment]
我也遇到这个问题了，你现在解决了吗？

**Comment by Yanyan-Wang** [comment]
由于 IE 浏览器不支持 foreignObject，所以出现了这个问题……

**Comment by Yanyan-Wang** [comment]
不再考虑支持 IE，因为 IE 已经下架啦
