### ISSUE TITLE
node type 为circle，并添加icon，怎么给添加的icon图片设置透明度

### ISSUE THREAD

**Issue by Elias-cug** [antvis/G6#2272]

**Comment by Yanyan-Wang** [comment]
直接在 icon 这个对象配置项里面加上 opacity: 0.2

**Comment by Elias-cug** [comment]
icon
![image](https://user-images.githubusercontent.com/38312452/98933075-23ce4f00-251b-11eb-992c-f1d1f7a0c924.png可以这样吗

**Comment by Elias-cug** [comment]
这个在nodeStateStyles里怎么设置
