### ISSUE TITLE
Several issues when dynamically adding Combo

### ISSUE THREAD

**Issue by spengjie** [antvis/G6#2273]
- **G6 Version**: 3.8.3
- **Platform**: Chrome 86.0.4240.183 (Official Build) (64-bit)
- **Mini Showcase(like screenshots)**: 参见CodePen
- **CodePen Link**: https://codepen.io/spengjie/pen/ExyOEyE

存在以下问题：
1. 先使用addItem动态添加Combo，再使用addItem动态添加Node，Node的comboId为刚添加的Combo，Node会显示到Combo下面。不设置groupByTypes为false，即使用默认值true时，没有问题。
2. 使用ICombo.addChild为动态添加的Combo添加子Node后，子Node没有显示到Combo中。但是当拖动Combo时，子Node会跟着一起被拖动。使用了updateCombos，也没有产生效果。目前发现只有通过graph.changeData(graph.save())的方式才可以刷新为正确的显示效果。

**Comment by Yanyan-Wang** [comment]
感谢

> 1. Node会显示到Combo下面

这个问题已经在修复了，下个新的版本就可以看到正确效果 

> 使用ICombo.addChild为动态添加的Combo添加子Node

任何对元素对操作尽可能使用 Graph 的 API 来做，对元素单独操作就可能会导致没有被全局管理到。

**Comment by spengjie** [comment]
@Yanyan-Wang 感谢回复。

> 任何对元素对操作尽可能使用 Graph 的 API 来做，对元素单独操作就可能会导致没有被全局管理到。

尝试过使用updateItem，但是发现对Node修改或添加comboId没有效果。刚发现可以通过updateComboTree做到。

**Comment by FxPixels** [comment]
> 感谢
> 
> > 1. Node会显示到Combo下面
> 
> 这个问题已经在修复了，下个新的版本就可以看到正确效果
> 
> > 2. 使用ICombo.addChild为动态添加的Combo添加子Node
> 
> 任何对元素对操作尽可能使用 Graph 的 API 来做，对元素单独操作就可能会导致没有被全局管理到。

所以应该要怎么做？
