### ISSUE TITLE
使用rotate旋转后，zoom-canvas失效，图谱不能放大或缩小

### ISSUE THREAD

**Issue by 52jaden** [antvis/G6#2277]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/uneke)

### Steps to reproduce
项目中之前用的是3.6.0的版本，升级到最新的3.8.3，这个问题依然存在
在官方示例上，最下面添加了两行代码
graph.get('group').rotate(Math.PI / 2)
graph.moveTo(0,0)
实现rotate后，图谱不能放大或缩小了

| Environment | Info |
|---|---|
| g6 | 3.8.3 |
| System | mac |
| Browser | chrome、edge均存在 |

**Comment by Yanyan-Wang** [comment]
谢谢，是个 bug，接下来会跟进一下

**Comment by d623141153** [comment]
> 谢谢，是个 bug，接下来会跟进一下

大概什么时间会修复呢，我们这边项目需求要做调整

**Comment by d623141153** [comment]
> 谢谢，是个 bug，接下来会跟进一下

大佬，这个还没有修复吗

**Comment by Yanyan-Wang** [comment]
经排查，是由于旋转后矩阵的取值方式应该与旋转前不同，但目前由于没有考虑到用户会旋转画布，所以取缩放系数都是取的 matrix[0].

目前可以这样进行旋转和缩放：

旋转：
```
        const center = [250, 250]; // 图的中心
        let matrix = graph.getGroup().getMatrix() || [1, 0, 0, 0, 1, 0, 0, 0, 1];
// 以图中心为旋转中心
        matrix = transform(matrix, [
          ['t', -center, -center],  // 先平移到中心
          ['r', Math.PI / 2], // 旋转
          ['t', center, center], // 再平移回去
        ]);
        graph.getGroup().setMatrix(matrix)
```

缩放：
```
// 可监听滚轮 graph.on('onWheel', e => {...}); 进行缩放
        let matrix = graph.getGroup().getMatrix() || [1, 0, 0, 0, 1, 0, 0, 0, 1];
// 同样以图中心为缩放中心，也可以改为 e.x, e.y 作为缩放中心
        mat3.translate(matrix, matrix, [-center.x, -center.y]);  // 平移到中心
        mat3.scale(matrix, matrix, [2, 2]); // 缩放 2 倍
        mat3.translate(matrix, matrix, [center.x, center.y]); // 平移回去
        graph.getGroup().setMatrix(matrix)
```

**Comment by WGL878420** [comment]
![image](https://user-images.githubusercontent.com/28598698/130376229-e44ecc6e-014c-4d78-a5cd-163bb0fd288f.png)
为啥t rantransfor报错啊
![image](https://user-images.githubusercontent.com/28598698/130376246-75dc906a-c2ba-430f-962f-137ef8caaf21.png)
![image](https://user-images.githubusercontent.com/28598698/130376255-e616e838-8c90-4a70-9417-18f0c8d36c89.png)

**Comment by Yanyan-Wang** [comment]
> graph.get('group').rotate(Math.PI / 2)
> graph.moveTo(0,0)

请另开 issue 并提供一下在线复现 demo 哈

**Comment by Yanyan-Wang** [comment]
由于旋转画布这个操作比较少见，没有计划支持该需求

**Comment by LeaveZzz** [comment]
自己使用graph.getGroup().setMatrix设置旋转矩阵之后，与矩阵相关的API全乱套了，focus、zoomTo等等。而且缩放操作时缩放中心并不是设置的center的位置。后续会支持内置的旋转画布操作吗？
