### ISSUE TITLE
自定义交互，只能在定义graph之前registerBehavior？ 

### ISSUE THREAD

**Issue by lgy1159** [antvis/G6#2278]
https://g6.antv.vision/zh/examples/interaction/customBehavior
![image](https://user-images.githubusercontent.com/45023840/98905367-469a3c80-24f6-11eb-92bb-869d592081e2.png)

**Comment by Heheroes** [comment]
应该是你的方式不对

**Comment by Yanyan-Wang** [comment]
可以通过 const { graph } = this 拿到 graph 实例，这个 graph 是这个 behavior 被挂载到的 graph。可以参考内置 behavior 的实现：https://github.com/antvis/G6/tree/master/src/behavior
