### ISSUE TITLE
自定义DOM节点报错

### ISSUE THREAD

**Issue by asevenm** [antvis/G6#2279]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/friendly-goodall-s1e6y?file=/src/shape/shape.js)

### Steps to reproduce
请查看demo链接

| Environment | Info |
|---|---|
| g6 | 3.8.3 |
| System | - |
| Browser | - |

**Comment by Heheroes** [comment]
new G6 创建实例的时候，在里面加一项 renderer:'svg'
