### ISSUE TITLE
如何删除一个groupId群组

### ISSUE THREAD

**Issue by Heheroes** [antvis/G6#2282]
![1605232928680](https://user-images.githubusercontent.com/46218273/99020251-0b9d1500-2599-11eb-84cd-35e97056cd09.jpg)

整个页面的所有节点和群组都是动态更新的。 当我点击一个域翻页的时候，希望把上一页数据延伸出来的数据删掉。但是节点删掉之后，分组的框还在，如何进行删除

**Comment by Yanyan-Wang** [comment]
推荐使用 combo，customGroup 已经不推荐使用，下个版本会被删除。关于 combo 的操作可以看这里：https://g6.antv.vision/zh/docs/api/items/comboMethods
