### ISSUE TITLE
nodeStateStyles的可用配置项api文档不全，怎么同时给标签，和图形配置

### ISSUE THREAD

**Issue by Elias-cug** [antvis/G6#2284]

**Comment by Yanyan-Wang** [comment]
标签也是一个图形，图形的 name 是 key，value 是样式就是为这个图形指定状态样式了。内置节点的话，标签的 name 是 'text-shape'

请按照这个文档的描述配置：https://g6.antv.vision/zh/docs/manual/middle/states/state#%E9%85%8D%E7%BD%AE-state-%E6%A0%B7%E5%BC%8F

**Comment by Elias-cug** [comment]
好的，circle中添加的icon，在nodeStateStyles中给image-shape设置opacity不生效

**Comment by Elias-cug** [comment]
好了，因该叫circle-icon

**Comment by Elias-cug** [comment]
非常感谢

**Comment by Yanyan-Wang** [comment]
嗯嗯 ，不清楚 name 的时候可以把图形打印出来看一下。node.getContainer() 可打印出节点的图形分组，children 中就是所有图形。
