### ISSUE TITLE
初始化的时候两条数据的坐标位置相同，但是渲染的位置不同，有解决办法吗？

### ISSUE THREAD

**Issue by GKLL** [antvis/G6#2285]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当初始化数据重合时，期望在一个位置展示

### What does the proposed API look like?
期望初始位置相同，渲染的位置也相同

**Comment by GKLL** [comment]
是N条数据的坐标全部相同时，数据不重合

**Comment by Yanyan-Wang** [comment]
你有配置布局吗？提供一下在线复现 demo 吧
