### ISSUE TITLE
移动端的drag-canvas无效

### ISSUE THREAD

**Issue by Houliang0239** [antvis/G6#2289]
在webview 上 使用G6，的确已经触发了touchmove事件，但是drag是无效的，希望能够提供解决方案

**Comment by Yanyan-Wang** [comment]
提供一下 G6 版本号。最新版本应该支持了的

**Comment by Houliang0239** [comment]
3.6.2,接手的老项目，我去尝试一下升级，目前是自己去写了一套移动端的放缩和拖拽。。。

**Comment by Yanyan-Wang** [comment]
嗯嗯，升级到最新应该就支持了

**Comment by txlwll** [comment]
最新版 4.0.2 移动端的缩放和拖拽都失效
