### ISSUE TITLE
Edges between combos are not updated when combo size changes (using .update() method)

### ISSUE THREAD

**Issue by sklinov** [antvis/G6#2290]
- [ V] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antv-g6-hide-nodes-ihmz2?file=/src/App.tsx:3615-3637)

### Steps to reproduce
Click on `Hide nodes` button and see that edge between combos (the blue one) is attached to the wrong position (not to the borders of combo and not to the anchor points defined above in graph options).

| Environment | Info |
|---|---|
| g6 | 3.8.4 |
| System | Windows 10 |
| Browser | Chrome 86.0.4240.198 |

---
This happens when I change combos' padding to visually fit in the label within combo when all the nodes are hidden by using `combo.update({padding: ...})`

**Comment by Yanyan-Wang** [comment]
Use `graph.update.item(combo, {padding:...})` instead

**Comment by sklinov** [comment]
@Yanyan-Wang Unfortunately, if you mean `graph.update(combo, {padding: ...})` or `graph.updateItem(combo, {padding: ...})` - none of them solve the problem

**Comment by Yanyan-Wang** [comment]
Sorry for the quick input, I meant `graph.updateItem(combo, {padding:...})`
Try this demo [HERE](https://codepen.io/Yanyan-Wang/pen/QWEoJBW?__cf_chl_jschl_tk__=cb57fe5e4e8b9b6d90d1cbe50885c329aec854e5-1605581710-0-AcFNe037MG6NXsuChJm6ou1szzzZVOJHW-EiWRhAkc09o6hEg1QANhngy-jlX-4GpP3OGlmNN0AFCOBQvxV58Mh6aO-klnvyryrMMnjiJMlEk9eeBCP6WZt4X0CIMIr0TsO0BbwCOHHPddpAlXEQqdPRu6H-iBgiq-kYpD2vCKFACQHRIvlYwRrY2PeyrZ8nH7Uz78TgPfWPTnAQvRcTBmwwB-1cRs647gmbf4qm63qUovUngH1AZ-ois3DcGmjwMZtsVZyGbvHIJisNaDtoOHFliUf0WSgQg-YfWn7RWgX7KLzqocsEVKiVqxEs2EJAWz3nLSPJ143glJG9INWDOKI) and click the canvas to update the combo padding:

**Comment by sklinov** [comment]
@Yanyan-Wang I see, but somehow in my case, that doesn't take effect.
![0225A362-92AF-43BD-86BE-2E53A0244F59](https://user-images.githubusercontent.com/38185977/99346652-eec55200-28b6-11eb-9137-875a3ec9eea2.GIF)

**Comment by Yanyan-Wang** [comment]
It might be a bug for rect type combo. We will try to fix it as soon as possible

**Comment by Yanyan-Wang** [comment]
update to v4.1.4 and see this demo pls: https://codesandbox.io/s/antv-g6-hide-nodes-forked-r1jr8?file=/src/App.tsx

note that call graph.data(data) graph.render() or graph.read(data) only at the first time you render the graph. If you wanna change the whole data, call graph.changeData(newData) instead.
