### ISSUE TITLE
请问如何拿到 缩小/放大 画布后，节点移动的距离呢？

### ISSUE THREAD

**Issue by LENZAKON** [antvis/G6#2291]

**Comment by LENZAKON** [comment]
（节点可通过滚轮移动的）以这个自定义 behavior 为例https://antv-g6.gitee.io/zh/examples/interaction/customBehavior#dragCanvasTwoFingers

**Comment by Yanyan-Wang** [comment]
你的原始需求是什么？为什么需要缩放后的节点距离？实际上缩放节点的位置是没有改变的，是整个坐标系在缩放，可以看下这篇文章 https://g6.antv.vision/zh/docs/manual/advanced/coordinate-system

**Comment by LENZAKON** [comment]
已经解决了，十分感谢
