### ISSUE TITLE
更新到最新版本后，画布节点模糊了

### ISSUE THREAD

**Issue by motingxing18** [antvis/G6#2292]
之前用的版本为3.5.0，由于拖动画布时报Unable to preventDefault inside passive event listener invocation，因此更新到最新版本已解决问题，结果问题非但没解决，还出现画布节点模糊情况，请问我该怎么操作，谢谢！！

**Comment by motingxing18** [comment]
![image](https://user-images.githubusercontent.com/71166209/99208655-0c81b100-27fc-11eb-9181-5c18faedc606.png)

**Comment by Yanyan-Wang** [comment]
在实例化图的时候确保没有配置 pixelRatio: 1。删掉这个以后，如果还是模糊的话，配置 pixelRatio: 2

**Comment by motingxing18** [comment]
拖动画布 控制台报 Unable to preventDefault inside passive event listener invocation （g6.min.js?d35b:15 ）错误，这个还是解决不了
