### ISSUE TITLE
如何增大type:line内置边的监听事件范围

### ISSUE THREAD

**Issue by ipangkang** [antvis/G6#2295]
我尝试通过lineAppendWidth的大小 扩大了边的监听范围。但是如何使得边的文本也能加入拖拽范围呢？

![image](https://user-images.githubusercontent.com/56474549/99223159-f33e2c00-281e-11eb-82c9-ad36a2a5d19a.png)

黄框范围内是lineAppendWidth的监听范围，但是拖拽红框内没有反应。

**Comment by baizn** [comment]
将边上文本的 capture 设置为 false，文档参考这里：https://g6.antv.vision/zh/docs/api/Group/#groupaddgroupcfg
![image](https://user-images.githubusercontent.com/9443867/100198419-c97bb800-2f36-11eb-8358-c316febec2e7.png)
