### ISSUE TITLE
不支持IE 11 ？

### ISSUE THREAD

**Issue by leochan2017** [antvis/g6#230]
您好，非常感谢AntV团队提供的JS库。

这个库很强大，但是可能有一点点美中不足？

不支持IE 11 ?

打开官方DEMO的时候，无法完整显示出来。

控制台报错如下图：

![8d890f5dedc8aad6d68e981d85ab6193](https://user-images.githubusercontent.com/9588096/39347912-90f8fdc2-4a27-11e8-8938-cb0c8b05297d.png)

希望您能在百忙之中抽空看下，谢谢哦

**Comment by TomHuangCN** [comment]
是 ie 对 es6 语法部分不支持的问题

你自己本地环境重新打包后ie上应该是能跑的
