### ISSUE TITLE
少量数据绘制用时2.4+ms

### ISSUE THREAD

**Issue by Heheroes** [antvis/G6#2303]
数据量大概在100条以内，time timeEnd查看 这个函数执行时间2万多毫秒。浏览器内存经常暴涨，页面容易崩溃。什么原因
draw(data) {
      // 判断是否已经创建实例
      if (this.g.cfg) {
        this.g.clear();
        this.g.destroy();
      }
      const width = document.getElementById('container').scrollWidth;
      const height = document.getElementById('container').scrollHeight;
      this.cvsWidth = width;
      insertCss(`
          .g6-tooltip {
            border: 1px solid #e2e2e2;
            border-radius: 4px;
            font-size: 14px;
            color: #000;
            background-color: rgba(255, 255, 255, 0.9);
            padding: 10px 8px;
            box-shadow: rgb(174, 174, 174) 0px 0px 10px;
            text-align:left;
          }
      `);
      const graph = new G6.Graph({
        container: 'container',
        width,
        height,
        groupType: 'rect',
        modes: {
          default: [
            'drag-canvas',
            {
              type: 'tooltip',
              formatText: function formatText(model) {
                if (!model.paging) {
                  return 'ip：' + model.label;
                } else {
                  return model.label;
                }
              },
              offset: 30
            }
          ]
        },
        defaultNode: {
          type: 'rect',
          size: [100, 30],
          style: {
            stroke: '#666',
            lineWidth: 1
          }
        },
        defaultEdge: {
          type: 'polyline',
          style: {
            radius: 10,
            offset: 30,
            endArrow: true,
            stroke: '#72C8E1',
            lineWidth: 2
          }
        },
        nodeStateStyles: {
          highlight: {
            opacity: 1
          }
        },
        edgeStateStyles: {
          defaultStyle: {
            opacity: 1,
            lineWidth: 2,
            stroke: '#72C8E1'
          },
          highlight: {
            opacity: 1,
            lineWidth: 3,
            stroke: 'pink'
          },
          dark: {
            opacity: 0
          }
        }
      });
      this.g = graph;
      function clearAllStats() {
        graph.setAutoPaint(false);
        graph.getNodes().forEach(function(node) {
          graph.clearItemStates(node);
        });
        graph.getEdges().forEach(function(edge) {
          graph.setItemState(edge, 'defaultStyle', true);
          graph.clearItemStates(edge);
        });
        graph.paint();
        graph.setAutoPaint(true);
      }
      // 移入元素 高亮相关关系（ 需要前提定义各项stateStyle ）
      graph.on('node:mouseenter', function(e) {
        const item = e.item;
        graph.setAutoPaint(false);
        graph.getNodes().forEach(function(node) {
          graph.clearItemStates(node);
          graph.setItemState(node, 'dark', true);
        });
        graph.setItemState(item, 'highlight', true);
        graph.getEdges().forEach(function(edge) {
          if (edge.getSource() === item) {
            graph.setItemState(edge.getTarget(), 'dark', false);
            graph.setItemState(edge.getTarget(), 'highlight', true);
            graph.setItemState(edge, 'highlight', true);
            edge.toFront();
          } else if (edge.getTarget() === item) {
            graph.setItemState(edge.getSource(), 'dark', false);
            graph.setItemState(edge.getSource(), 'highlight', true);
            graph.setItemState(edge, 'highlight', true);
            edge.toFront();
          } else {
            graph.setItemState(edge, 'highlight', false);
            graph.setItemState(edge, 'dark', true);
          }
        });
        graph.paint();
        graph.setAutoPaint(true);
      });
      graph.on('node:mouseleave', clearAllStats);
      graph.data(data); // 加载数据
      graph.render(data);
      //  node 节点单击事件
      const self = this;
      graph.on('node:click', function(evt) {
        const node = evt.item;
        const model = node.getModel();
        // const group = node.getContainer();
        if (model.paging && model.prev) {
          if (self.paging[model.paging] && self.paging[model.paging] === 1) {
            self.$message('当前已经是第一页');
          } else {
            self.paging[model.paging]--;
            self.pagingHandle(model, graph);
          }
        } else if (model.paging && model.next) {
          if (!self.paging[model.paging]) {
            self.paging[model.paging] = 2;
          } else {
            self.paging[model.paging]++;
          }
          self.pagingHandle(model, graph);
        } else {
          self.cvsLoading = true;
          self.showChildren(graph, model);
        }
      });
    },

**Comment by Yanyan-Wang** [comment]
写成在线 demo 看下，这样看不出原因
