### ISSUE TITLE
使用updateItem更新边后，边上的箭头没有随之更新，问题还挺严重

### ISSUE THREAD

**Issue by AtomicGu** [antvis/G6#2304]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/g6-bug-report-2-lznjb)

### Steps to reproduce
看图：
![1](https://user-images.githubusercontent.com/49391101/99395411-57deb100-291b-11eb-8caf-6bd0e20f75ed.gif)

| Environment | Info |
|---|---|
| g6 | 3.8.5 |
| System | - |
| Browser | - |

**Comment by AtomicGu** [comment]
是个GIF图

**Comment by Yanyan-Wang** [comment]
在上方 demo 中直接拖拽一个节点吗？我这里箭头是跟随的。有什么特殊操作吗？还有你的系统和浏览器提供一下

**Comment by AtomicGu** [comment]
@Yanyan-Wang 不是直接拖，gif图右边是firefox的控制台，我输了两条指令（见图），把边updateitem了一下，取消了箭头，然后再拖，就成这样了。

**Comment by Yanyan-Wang** [comment]
暂时先这么去除箭头吧，可能是 false 判断有问题：
```

        graph.updateItem(graph.getEdges()[0], {
          style: {
            endArrow: {
              path: ""
            },
          }
        });
```

**Comment by Yanyan-Wang** [comment]
v4.0.2 已解决
