### ISSUE TITLE
求求你们让G6.Menu也能用于右键点击画布吧！

### ISSUE THREAD

**Issue by AtomicGu** [antvis/G6#2305]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现在的Menu类只能用于node、edge、combo，就是没有画布……，我偷偷试了写canvas，没有用😭，求求你们让它也支持画布吧，真的可以方便很多哇！而且我觉得应该不难实现吧~

见图片：
![图片](https://user-images.githubusercontent.com/49391101/99399801-1d781280-2921-11eb-8830-a2d31e97cc20.png)

### What does the proposed API look like?
Menu初始化时候允许的itemTypes里加上"canvas"一项。

**Comment by Yanyan-Wang** [comment]
下个版本会加的，你要是着急的话，可以监听 graph.on('canvas:contextmenu', e=>{}) 然后自己挂一个 DOM 上去。挂载方式参考 https://g6.antv.vision/zh/docs/manual/advanced/coordinate-system

**Comment by gouzixing** [comment]
现在也有这个需求 请问现在menu插件更新了吗
