### ISSUE TITLE
请问g6有没有办法让某条分支固定最右侧展示

### ISSUE THREAD

**Issue by jxustdin** [antvis/G6#2308]
同一个网关下有多条分支，怎么能让其中某一条分支在最右侧呢？

**Comment by Yanyan-Wang** [comment]
不是很明白你的需求。我理解可以自定义布局，参考 https://g6.antv.vision/zh/examples/net/layoutMechanism#customBigraph

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
