### ISSUE TITLE
控制兄弟节点关闭的手风琴效果

### ISSUE THREAD

**Issue by xueyuwan** [antvis/G6#2309]
需求：树图，点击第二层节点，其兄弟节点关闭。
![image](https://user-images.githubusercontent.com/20057364/99473586-d07a5780-2985-11eb-98b1-03328be300c7.png)

实现：操作节点的属性，然后重新渲染。
![image](https://user-images.githubusercontent.com/20057364/99473764-336bee80-2986-11eb-8443-779a65049e69.png)

问题：这种方式实现，点击三级节点后点二级节点，再点击三级节点会报错，如图。
![image](https://user-images.githubusercontent.com/20057364/99473539-b80a3d00-2985-11eb-8281-8e66c154e11a.png)
请问我的方法有什么问题？开启collapse-expand的状态下，实现特定层级兄弟元素折叠有什么好的方案吗？感谢

**Comment by Yanyan-Wang** [comment]
请提供复现的在线最小 demo。可以写在 codepen.io

**Comment by xueyuwan** [comment]
https://codepen.io/xueyuwan/pen/xxONZNa


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/G6"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月19日(星期四) 下午2:22
收件人:&nbsp;"antvis/G6"<G6@noreply.github.com&gt;;
抄送:&nbsp;"万雪雨"<1213287572@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [antvis/G6] 控制兄弟节点关闭的手风琴效果 (#2309)





 
请提供复现的在线最小 demo。可以写在 codepen.io

**Comment by Yanyan-Wang** [comment]
我打开以后点击第三层的节点，再点第二层节点，再点第三层节点，没报错。你说报错的具体操作是啥

**Comment by xueyuwan** [comment]
点击第二层"A医院"，再点击A医院的子节点"应用一（含有子节点）",然后再点击A医院就会报错。感谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/G6"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月20日(星期五) 下午2:03
收件人:&nbsp;"antvis/G6"<G6@noreply.github.com&gt;;
抄送:&nbsp;"万雪雨"<1213287572@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [antvis/G6] 控制兄弟节点关闭的手风琴效果 (#2309)





 
我打开以后点击第三层的节点，再点第二层节点，再点第三层节点，没报错。你说报错的具体操作是啥

**Comment by Yanyan-Wang** [comment]
你已经自己处理 node:click 去控制展开和收起了，就不要配置 'collpase-expand' 了，这样就不会报错了。

开始时“A医院”原本就是展开的状态，点击“A医院”应该没有其他要收起的吧。
