### ISSUE TITLE
miniMap缩略图插件只显示node？能不能显示edge

### ISSUE THREAD

**Issue by zx8887** [antvis/g6#231]
![22](https://user-images.githubusercontent.com/13731281/39511114-dce011d0-4e1e-11e8-8286-f6d8a09cebe3.png)
如图，使用miniMap插件，发现之显示node，不显示edge。。。有点尴尬呀。
有没有什么设置可以让其所见？

**Comment by TomHuangCN** [comment]
这个没留口子，只显示节点，当初就这么设计的。
