### ISSUE TITLE
树图自定义边的颜色

### ISSUE THREAD

**Issue by xueyuwan** [antvis/G6#2310]
![image](https://user-images.githubusercontent.com/20057364/99474242-2d2a4200-2987-11eb-9a48-40861589f0f0.png)
如图:红、黄状态的数据，想让对应的边随状态改变颜色，请问树图如何实现？

**Comment by Yanyan-Wang** [comment]
graph.updateItem(edge, {
  style: {
    stroke: '#f00'
  }
})
