### ISSUE TITLE
初始数据非空，使用addItem添加的节点id不唯一

### ISSUE THREAD

**Issue by Liiyue** [antvis/G6#2312]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/liiyue/pen/xxOeYrN](https://codepen.io/liiyue/pen/xxOeYrN)

### Steps to reproduce
1. 点击'添加节点'；
2. 控制台查看打印出来的graph数据，可以发现新增的node的id为'node1',与原始数据重复。

| Environment | Info |
|---|---|
| g6 | 3.8.3 |
| System | - |
| Browser | - |

---
const data = {
  nodes: [
    {
      id: 'node1',
      x: 100,
      y: 200,
    },
    {
      id: 'node2',
      x: 300,
      y: 200,
    },
  ],
  edges: [
    {
      source: 'node1',
      target: 'node2',
    },
  ],
};

const graph = new G6.Graph({
  container: 'mountNode', 
  width: 800, // Number，必须，图的宽度
  height: 500, // Number，必须，图的高度
});

graph.read(data);

function handleNodeAdd() {
  graph.addItem('node',{
    x: 500,
    y: 200
  });
  console.log(graph.save());
}

**Comment by Yanyan-Wang** [comment]
必须自己为增加的元素指定 id。可以用 G6.Util.uniqueId() 生成
