### ISSUE TITLE
采用树图布局时，使用内置"click-select"和"drag-node"事件。先使节点处于被选中状态后，再拖动节点，该节点的选中状态的样式会一直保留不消失

### ISSUE THREAD

**Issue by yinggang-dong-innovis** [antvis/G6#2313]
使用v3.8.3，创建树图布局的视图。modes添加"drag-node"和"click-select"。
先选中一个节点元素，元素样式为“nodeStateStyles”中设置的样式。
此时，拖动该节点，再选中其他节点或点击该节点自身，正常情况该节点的选中样式消失，但是目前该节点的选中样式会一直存在。

**Comment by Yanyan-Wang** [comment]
v4.0.2 已解决
