### ISSUE TITLE
火狐、Safari浏览器使用工具栏插件无效果，请问如何支持这两款浏览器？

### ISSUE THREAD

**Issue by W-Rick** [antvis/G6#2315]
![image](https://user-images.githubusercontent.com/38304544/99658137-0872bf00-2a9a-11eb-9428-954cd0a23cfa.png)
操作无效果

**Comment by Yanyan-Wang** [comment]
应该是个 bug，接下来会跟进一下

**Comment by baizn** [comment]
感谢 @zjgyb  的 PR https://github.com/antvis/G6/pull/2456，下个发布就会修复这个问题。
