### ISSUE TITLE
移动端点击节点报错

### ISSUE THREAD

**Issue by a51427051** [antvis/G6#2316]
版本：3.8.4
问题：移动端点击节点报错，缩放canvas报错
环境：浏览器的手机模式，移动端
报错信息：
![image](https://user-images.githubusercontent.com/34834453/99659086-520fd980-2a9b-11eb-9225-674c2b2b8788.png)
demo: https://sc5lp.csb.app/

**Comment by baizn** [comment]
升级到最新版

**Comment by a51427051** [comment]
还是有报错，具体可以看demo，已升级到最新版本

**Comment by txlwll** [comment]
遇到一样的问题

**Comment by Yanyan-Wang** [comment]
fixed by 4.1.8

**Comment by a51427051** [comment]
@Yanyan-Wang 
版本：4.1.8
问题：移动端点击节点不触发点击事件

**Comment by Yanyan-Wang** [comment]
> @Yanyan-Wang
> 版本：4.1.8
> 问题：移动端点击节点不触发点击事件

https://github.com/antvis/G6/issues/2629#issuecomment-780999876

**Comment by a51427051** [comment]
> > @Yanyan-Wang
> > 版本：4.1.8
> > 问题：移动端点击节点不触发点击事件
> 
> [#2629 (comment)](https://github.com/antvis/G6/issues/2629#issuecomment-780999876)

完美解决，感谢回复
