### ISSUE TITLE
怎么关闭force型关系图的初始化动画效果？

### ISSUE THREAD

**Issue by shi900384** [antvis/G6#2317]
要做一个复杂的人员关系图谱，开了不重叠preventOverlap。但因为节点实在太多，关系较复杂，导致初始化时会动来动去不停的调整节点的位置，动画效果卡的不行。请问什么属性可以关掉这种动画，一进来就是最终效果？

**Comment by Yanyan-Wang** [comment]
关掉动画，应该会计算并白屏很长时间。刚刚发布了 G6 4.0.0-beta.1 版本，里面有一个 gForce 支持 GPU 布局，大规模图上速度会快很多，配置 layout: {type: 'gForce', gpuEnabled: true} 就可以。GPU 版本的布局在迭代过程中不会渲染，计算完之后再出现。gForce 也有 cpu 版本，效果和现在你用的 force 效果类似

**Comment by shi900384** [comment]
多谢大佬👍



发自我的黑鲨手机在 Yanyan Wang <notifications@github.com>，2020年11月20日 下午6:44写道：
关掉动画，应该会计算并白屏很长时间。刚刚发布了 G6 4.0.0-beta.1 版本，里面有一个 gForce 支持 GPU 布局，大规模图上速度会快很多，配置 layout: {type: 'gForce', gpuEnabled: true} 就可以。GPU 版本的布局在迭代过程中不会渲染，计算完之后再出现。gForce 也有 cpu 版本，效果和现在你用的 force 效果类似

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/antvis/G6/issues/2317#issuecomment-731093331",
"url": "https://github.com/antvis/G6/issues/2317#issuecomment-731093331",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
