### ISSUE TITLE
import { transform } from '@antv/matrix-util'; 3.8.5官网例子中旋转transfrom怎么没有这个方法了？？

### ISSUE THREAD

**Issue by pollux2015** [antvis/G6#2319]
![image](https://user-images.githubusercontent.com/11935278/99782513-374d6b80-2b54-11eb-8231-5283a5c1ca18.png)
![image](https://user-images.githubusercontent.com/11935278/99782544-43d1c400-2b54-11eb-92ae-e2bdd6574a25.png)

**Comment by pollux2015** [comment]
这是官网3.8.5 G6的文档
![image](https://user-images.githubusercontent.com/11935278/99782926-bf337580-2b54-11eb-94f0-12bfcfe4f2b2.png)

**Comment by Yanyan-Wang** [comment]
有的，你要安装 @antv/matrxi-util 这个包

**Comment by Moxiuzhu** [comment]
我现在安装最新版本的g6也是找不到这个transfrom方法，请问你是怎么找到的？有安装@antv/matrix-util 这个包，但是这个包导出没有transfrom方法欸

**Comment by Yanyan-Wang** [comment]
import { ext } from '@antv/matrix-util';
const transform = ext.transform;

**Comment by XiuzhuMo** [comment]
谢谢你了，我也找到了，但是算radial文本的角度好难，第一层好不容易算好了，展开第二层全乱了欸





------------------ 原始邮件 ------------------
发件人: Yanyan Wang ***@***.***&gt;
发送时间: 2021年4月1日 17:36
收件人: antvis/G6 ***@***.***&gt;
抄送: M17 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[antvis/G6] import { transform } from ***@***.***/matrix-util'; 3.8.5官网例子中旋转transfrom怎么没有这个方法了？？ (#2319)





 
import { ext } from ***@***.***/matrix-util';
 const transform = ext.transform;
