### ISSUE TITLE
在vue中使用，npm run serve 后报一个js依赖没有找到的错

### ISSUE THREAD

**Issue by LeeAnteng** [antvis/G6#2326]
This dependency was not found:

* https://cdn.jsdelivr.net/npm/@webgpu/glslang@0.0.15/dist/web-devel/glslang.js in ./node_modules/_@antv_g6@4.0.0@@antv/g6/dist/g6.min.js

To install it, you can run: npm install --save https://cdn.jsdelivr.net/npm/@webgpu/glslang@0.0.15/dist/web-devel/glslang.js

npm install --save https://cdn.jsdelivr.net/npm/@webgpu/glslang@0.0.15/dist/web-devel/glslang.js
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: https://cdn.jsdelivr.net/npm/@webgpu/glslang@0.0.15/dist/web-devel/glslang.js.
npm ERR! package.json npm can't find a package.json file in your current directory.

**Comment by wangyixiang-556** [comment]
同样缺失

**Comment by HuChundong** [comment]
还没修复吗，也遇到了

**Comment by lmd3385** [comment]
还没修复么？我也遇到这个情况

**Comment by IronPillar-Sheng** [comment]
+1

**Comment by Yanyan-Wang** [comment]
如果安装一下这个可以吗？npm install --save https://cdn.jsdelivr.net/npm/@webgpu/glslang@0.0.15/dist/web-devel/glslang.js

**Comment by wangyixiang-556** [comment]
换个版本就行了 我现在是3.5.11

**Comment by HuChundong** [comment]
> 如果安装一下这个可以吗？npm install --save https://cdn.jsdelivr.net/npm/@webgpu/glslang@0.0.15/dist/web-devel/glslang.js

安装不上的

**Comment by Yanyan-Wang** [comment]
> 换个版本就行了 我现在是3.5.11

这个版本也太老了，上一个最新的是 3.8.5

**Comment by Yanyan-Wang** [comment]
npm install --save @webgpu/glslang@0.0.15 这样呢

**Comment by wangyixiang-556** [comment]
> > 换个版本就行了 我现在是3.5.11
> 
> 这个版本也太老了，上一个最新的是 3.8.5

除了最新版 应该都没事

**Comment by Yanyan-Wang** [comment]
> > > 换个版本就行了 我现在是3.5.11
> > 
> > 
> > 这个版本也太老了，上一个最新的是 3.8.5
> 
> 除了最新版 应该都没事

嗯，因为 4.0 加了 GPU 并行计算布局

**Comment by HuChundong** [comment]
> npm install --save @webgpu/glslang@0.0.15

可以安装上这个包，但是报相同的错误

**Comment by Yanyan-Wang** [comment]
> > npm install --save @webgpu/glslang@0.0.15
> 
> 可以安装上这个包，但是报相同的错误

嗯我这里排查下，着急的话先用 3.8.5

**Comment by Yanyan-Wang** [comment]
glslang 依赖问题升级 G6 到 4.0.1 即可
