### ISSUE TITLE
ie自定义节点 不在vue框架中怎么兼容ie11

### ISSUE THREAD

**Issue by canifindyou** [antvis/G6#2327]

**Comment by canifindyou** [comment]
官方大佬，看到了请给点提示吧，拯救一下菜鸡

**Comment by Yanyan-Wang** [comment]
https://g6.antv.vision/zh/docs/manual/FAQ/supportIE

**Comment by canifindyou** [comment]
> https://g6.antv.vision/zh/docs/manual/FAQ/supportIE
这个是在框架内解决的吧，我现在是一个单页面 index.html 使用自定义节点 ie中一直报错 “对象不支持“getBBox”属性或方法” 是不是ie中不支持自定义节点的使用呀

**Comment by Yanyan-Wang** [comment]
内置节点是可以的吗？实在不行就考虑降级。写一个复现的在线 demo 我看看

**Comment by canifindyou** [comment]
> 内置节点是可以的吗？实在不行就考虑降级。写一个复现的在线 demo 我看看
内置节点是可以的，可以绘制出来

**Comment by canifindyou** [comment]
> 内置节点是可以的吗？实在不行就考虑降级。写一个复现的在线 demo 我看看

[内置节点测试没有问题，只是自定义的出现了这个问题]

**Comment by Yanyan-Wang** [comment]
不再考虑支持 IE 浏览器，因为 IE 已经下架啦
