### ISSUE TITLE
G6在uni-app中使用，文件无法引入，提示第三方库太大，有其他方式吗

### ISSUE THREAD

**Issue by canifindyou** [antvis/G6#2328]

**Comment by Yanyan-Wang** [comment]
请给出提示信息

**Comment by canifindyou** [comment]
> 请给出提示信息

目前遇到的提示信息   “[警告] `common\g6.js` 文件体积超过 500KB，已跳过压缩以及 ES6 转 ES5 的处理，手机端使用过大的js库影响性能。”    是这个警告，说库太大了，请问如果我想使用这个库，有没有好的解决办法

**Comment by Yanyan-Wang** [comment]
你需要在手机端使用吗？4.0 因为引入 gpu 的依赖所以比较大，可以试一下 3.8.5

**Comment by canifindyou** [comment]
> 你需要在手机端使用吗？4.0 因为引入 gpu 的依赖所以比较大，可以试一下 3.8.5

目前使用的版本就是 https://gw.alipayobjects.com/os/lib/antv/g6/3.8.1/dist/g6.min.js 

> 你需要在手机端使用吗？4.0 因为引入 gpu 的依赖所以比较大，可以试一下 3.8.5

目前换了版本还是这个问题，是不是这个不适用uni-app

**Comment by Yanyan-Wang** [comment]
如果是包太大的问题导致不能用在移动端，那目前来看应该就是不合适了。以后会把 G6 功能做拆包

**Comment by webmrxu** [comment]
如何拆包，这个优化会在哪个版本实现？现在依赖包打包出来快1M，有什么好对解决办法优化下，现在只使用了流程图这个demo代码

**Comment by Yanyan-Wang** [comment]
拆包这个暂时还没有排期，应该会在半年内完成改造

**Comment by Yanyan-Wang** [comment]
拆包已经完成，最新版本 v4.2.1。核心功能在 @antv/g6-core 当中。内置元素在 @antv/g6-element。现在 @antv/g6-mobile 已经发布一个 beta 版，后面会更好地支持移动端和小程序
