### ISSUE TITLE
G6@4.0.0 开发环境下加载远程代码导致无法使用

### ISSUE THREAD

**Issue by zuiidea** [antvis/G6#2329]
G6@4.0.0 开发环境下加载远程代码导致无法使用，可能跟这个别名设置有关 [182c345](https://github.com/antvis/G6/commit/182c345014b6b35ac89201151e99094bbe4600b0#diff-a6f3904c41211be170d9b0eb87e49ea8d02d0fd5a7224d6772174b425dacf90f)，导致输出的npm包里也有加载远程的代码。

![image](https://user-images.githubusercontent.com/16070518/99929579-add2af00-2d88-11eb-9a5e-b02ae11579c7.png)

- 代码示例
```js
import G6 from '@antv/g6';
console.log(G6);
```

- 报错信息
```js
./node_modules/@antv/g6/dist/g6.min.js
Module not found: Can't resolve 'https://cdn.jsdelivr.net/npm/@webgpu/glslang@0.0.15/dist/web-devel/glslang.js' in '/home/react-app/node_modules/@antv/g6/dist'
```

**Comment by mumu-evanchen** [comment]
同样的问题
```
./node_modules/@antv/g6/dist/g6.min.js
Module not found: Error: Can't resolve 'https://cdn.jsdelivr.net/npm/@webgpu/glslang@0.0.15/dist/web-devel/glslang.js' in 'D:\zhuiyi\nlp-platform-web\node_modules\@antv\g6\dist'
```

**Comment by HunterHeroHan** [comment]
+1

**Comment by qq2575896094** [comment]
+1

**Comment by heroFan** [comment]
+1

**Comment by xiaoiver** [comment]
问题是依赖的 `g-webgpu` 造成的，已经发布了 `v0.5.1` 修复。
等待 `g6` 发布 bugfix 版本 `v4.0.1`。

**Comment by baizn** [comment]
4.0.1 已发布，麻烦更新到 4.0.1，多谢！
