### ISSUE TITLE
Set node size based on label automatically

### ISSUE THREAD

**Issue by ketys-from-meiro** [antvis/G6#2331]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I wanna build some graph visualization with nodes and labels placed inside them, but I don't know, how the labels can be long, because they're loaded dynamically. It would be nice to have some node settings so its proportions will be calculated automatically.

### What does the proposed API look like?
something like
```
size: "auto",
labelCfg: {
  textWrap: "wrap",
  maxWidth: 200
}
```

**Comment by Yanyan-Wang** [comment]
Are you using a built-in node type or custom node type? It will be free to control the keyShape's size according to the bounding box of text shape in `draw` like this: 
```
G6.registerNode('your-node-type', {
  draw: (cfg, group) = {
    const keyShape = group.addShape('rect', {
      attrs: {
          x: 0,
          y: 0,
          width: 10,
          height: 10,
          fill: '#f00'
     }
    })

    if (cfg.label) {
      const label = group.addShape('text', {
        attrs: {
            text: cfg.label,
            x: 0,
            y: 0,
            fill: '#f00'
        }
      })
    
       const labelBBox = label.getBBox();
       keyShape.attrs({
         width: labelBBox.width,
        height: labelBBox.height
      })
    }
    return keyShape;
  },
... other overrode functions
})
```

Or you can update the node item after rendering:
```
graph.getNodes().forEach(node => {
  // find the text shape by its name
  const labelShape = node.getContainer().find(e => e.get('name') === 'text-shape');
  // get the bounding box of the label
  const labelBBox = labelShape.getBBox();
  graph.updateItem(node => {
    size: [labelBBox.width, labelBBox.height],
    // or set the style, whose width and height has higher priority than size:
    style: {
      width: labelBBox.width,
      height: labelBBox.height
   }
  });
});

```

**Comment by ketys-from-meiro** [comment]
Wow, thank you a lot, this is exactly what I was looking for, had to tweak your code a bit, but it works ;)

**Comment by curious-broccoli** [comment]
if someone finds this issue, in 5.x https://github.com/antvis/G6/pull/6347#issuecomment-2357515570 should work
