### ISSUE TITLE
Parcel with g6: Unexpected token, expected ","

### ISSUE THREAD

**Issue by Madeorsk** [antvis/G6#2332]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/parcel-g6-example-tdmzj)

### Steps to reproduce
Install parcel-bundler (yarn global add parcel-bundler for example), then do yarn build on the example repository. It will fail.

| Environment | Info |
|---|---|
| g6 | 4.0.0 |
| System | - |
| Browser | - |

---
I cannot add g6 to a project where I use parcel. Is it a problem of parcel or g6?

```
🚨  /home/madeorsk/[...]/js/app/node_modules/@antv/g6/dist/g6.min.js:29:1503348: Unexpected token, expected "," (29:1503348)
```

**Comment by Yanyan-Wang** [comment]
I'm not sure if it will help, but just update to v4.0.2 pls

**Comment by Madeorsk** [comment]
Same with v4.0.2

```
/home/madeorsk/[...]/node_modules/@antv/g6/dist/g6.min.js:30:1575799: Unexpected token, expected "," (30:1575799)
```

However, it was working on 3.0.0. Something changed since and it is not working anymore.
