### ISSUE TITLE
当画布容器有外部元素时，火狐浏览器minimap拖动失效问题

### ISSUE THREAD

**Issue by hongshou** [antvis/G6#2337]
- **G6 Version**:  ^3.8.5
- **Platform**: firefox
- **Mini Showcase(like screenshots)**: 
![minimap(firefox)-Issue](https://user-images.githubusercontent.com/52767719/100043093-a9b99680-2e47-11eb-929b-0c0cbd49bc7c.gif)

- **CodePen Link**:  https://codepen.io/hongshou/pen/jOrgQLZ

**Comment by hongshou** [comment]
Anyone answered?

**Comment by YealZoy** [comment]
have you solved this problem, brother?

**Comment by hongshou** [comment]
> have you solved this problem, brother?

No...I've blocked this feature on Firefox〒▽〒

**Comment by Yanyan-Wang** [comment]
新版本已解决（v4.1.8）：https://codepen.io/Yanyan-Wang/pen/mdOEyvr

fixed by v4.1.8
