### ISSUE TITLE
请问在treegraph中可否指定点位x,y位置，我尝试指定没有生效

### ISSUE THREAD

**Issue by niceyida** [antvis/G6#2339]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
TreeGraph 的初始位置是由配置的布局计算而得。需要改变节点位置可以在首次渲染完成后用 graph.updateItem, 例如：

    graph.on('canvas:click', e => {
      graph.updateItem(graph.getNodes()[0], {
        x: 100, y:0
      })
    })
