### ISSUE TITLE
右键菜单，上下文菜单给在节点上添加了右键选项后，还希望在节点以外能看到浏览器自带的‘复制图片’，‘图片另存为’

### ISSUE THREAD

**Issue by zwygithub** [antvis/G6#2340]
plugins: [ contextMenu],在节点上添加右键菜单后，还希望有之前没有右键菜单时的浏览器自带功能（‘复制图片’，‘图片另存为’），有什么好的方法吗

**Comment by Yanyan-Wang** [comment]
可以在 contextMenu 的 itemTypes 中加上 'canvas'，然后在 getContent 中判断是否是画布上的右击，若是则出现带有下载图片的 DOM，然后在 handleMenuClick 中调用 graph.downloadFullImage

https://g6.antv.vision/zh/examples/tool/contextMenu#contextMenu

**Comment by zwygithub** [comment]
谢谢，为什么  plugins: [contextMenu],itemTypes: ['node', 'edge', 'canvas']，把例子里边的const contextMenu = new G6.Menu。。这些放在我的代码里，还是只在节点上有event，找不到在画布上的event

**Comment by Yanyan-Wang** [comment]
itemTypes: ['node', 'edge', 'canvas'] 这个是配置咋 new G6.Menu 的配置项里的，你看下上面的例子

**Comment by zwygithub** [comment]
没有配置在外边，就是按照例子复制过去的contextMenu

**Comment by Yanyan-Wang** [comment]
升级到最新版本，3.x 的这个插件应该是不支持 canvas 的菜单的

**Comment by zwygithub** [comment]
谢谢可以了，浏览器的右键图片复制(Y)可以实现吗

**Comment by Yanyan-Wang** [comment]
没有内置功能，考虑自己处理
