### ISSUE TITLE
graph.read(data)节点的位置没有根据数据里面的x,y参数来布局

### ISSUE THREAD

**Issue by CoderQuixote** [antvis/G6#2341]
graph.read(data)节点的位置没有根据数据里面的x,y参数来布局

**Comment by Yanyan-Wang** [comment]
TreeGraph 还是 Graph ，请按 issue 模版给出复现在线 demo

**Comment by Heheroes** [comment]
graph.data(data)
graph.render()
这样写呢。

**Comment by Yanyan-Wang** [comment]
如果你配置了 layout 的话，就会用配置的布局来计算了。没有配置且 data 节点中有 x y 才会根据数据来放置节点。且上述机制适用于 Graph 而非 TreeGraph，如果是 TreeGraph 必须先配置 layout，要更新节点位置可以通过 graph.updateItem(node, {x: 100, y: 100}) 这样来指定

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
