### ISSUE TITLE
在层次布局中。不属于组合的节点展示在了组合框中

### ISSUE THREAD

**Issue by Elias-cug** [antvis/G6#2344]
代码演示：https://codesandbox.io/s/vigilant-lamarr-b97in?fontsize=14&hidenavigation=1&theme=dark&file=/src/index.js
版本：3.8.0
win10
谷歌

**Comment by Yanyan-Wang** [comment]
因为 combo 的大小和位置是根据其包含的内容决定的，对于跨层的节点的布局位置不会有影响，所以现在是包含了1、3 层节点，2层节点没有排出去。。dagre 的 sortByCombo 只能处理同一层有相同 combo 的节点尽可能靠近。你这个情况的话，目前可能只能自己处理一下节点的位置了

**Comment by Elias-cug** [comment]
好的，晓得你是谁了，哈哈。谢谢

**Comment by Elias-cug** [comment]
combo内部可以布局吗

**Comment by Elias-cug** [comment]
然后有没有什么好的建议处理这种情况，现在返回的节点是不确定的

**Comment by YealZoy** [comment]
好多节点啊 这是要一个一个循环计算吗，层级 也很多 问题是   位置 相合了 数据 就自动 进入到那个combo里面了， 有没有什么好的处理方法

**Comment by YealZoy** [comment]
先添加的元素 会根据后添加的元素 定位 得拿到数据 重新计算位置

**Comment by Yanyan-Wang** [comment]
> 好多节点啊 这是要一个一个循环计算吗，层级 也很多 问题是 位置 相合了 数据 就自动 进入到那个combo里面了， 有没有什么好的处理方法

终端用户手动拖拽节点进入到 combo 内部才会被属于该 combo。如果你不希望手动拖拽之后改变 combo 的层次关系，可以在 drag-node 和 drag-combo 中设置 onlyChangeComboSize: true

**Comment by Yanyan-Wang** [comment]
dagre + combo 改进咯，升级到 v4.1.13-beta.3 试用，配置 dagre 布局 sortByCombo: true
