### ISSUE TITLE
当给最外层的Combo加入animate后，cpu占用率上升

### ISSUE THREAD

**Issue by xuzhijun** [antvis/G6#2346]
- **G6 Version**: 3.8.3
- **Platform**: 虚拟机 windows 7 64位，chrome 87
- **CodePen Link**: https://codesandbox.io/s/gifted-hooks-entjj?file=/src/App.vue

描述：画布中有几十个Node，最多3层Combo，当给最外层Combo加入animate时，cpu占用率升高，特别是在虚拟机里cpu占用90%以上。
在macbook air中，使用chrome 87，cpu也从动画前的1%上升到30%左右

**Comment by Yanyan-Wang** [comment]
动画的消耗是比较高的

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
