### ISSUE TITLE
 graph.setItemState 高亮之后 drag-canvas'  'zoom-canvas' 无效，卡顿

### ISSUE THREAD

**Issue by zhangrui3191** [antvis/G6#2349]
点击节点高亮关联节点，鼠标事件会卡顿或无响应

 graph.setItemState(nodeItem, 'hover', false)
        graph.setAutoPaint(false)
        graph.getNodes().forEach(function (node) {
          graph.clearItemStates(node)
          graph.setItemState(node, 'dark', true)
        })
        graph.setItemState(nodeItem, 'dark', false)
        graph.setItemState(nodeItem, 'highlight', true)
        graph.getEdges().forEach(function (edge) {
          if (edge.getSource() === nodeItem) {
            graph.setItemState(edge.getTarget(), 'dark', false)
            graph.setItemState(edge.getTarget(), 'highlight', true)
            graph.setItemState(edge, 'hover', false)
            edge.toFront()
          } else if (edge.getTarget() === nodeItem) {
            graph.setItemState(edge.getSource(), 'dark', false)
            graph.setItemState(edge.getSource(), 'highlight', true)
            graph.setItemState(edge, 'hover', false)
            edge.toFront()
          } else {
            graph.setItemState(edge, 'hover', true)
            edge.toFront()
          }
        })

**Comment by zhangrui3191** [comment]
dagre 布局

**Comment by Yanyan-Wang** [comment]
提供一个复现在线 demo 吧

**Comment by zhangrui3191** [comment]
[https://github.com/antvis/G6/issues/2349#issuecomment-733589438](url)

**Comment by zhangrui3191** [comment]
[https://codesandbox.io/s/nice-dawn-5juzr?file=/src/App.vue](url)

**Comment by zhangrui3191** [comment]
- **G6 Version*3.8.5*:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **dome链接*https://codesandbox.io/s/nice-dawn-5juzr?file=/src/App.vue*:

**Comment by Yanyan-Wang** [comment]
你在你的 `openStats` 函数里设置了 `graph.setAutoPaint(false);`，去掉能缩放了。另外代码里也需要优化一下，尽量减少重复的操作。936 行应该是 `canvas:click`
