### ISSUE TITLE
Tooltip not shown for combo (using tooltip plugin)

### ISSUE THREAD

**Issue by sklinov** [antvis/G6#2351]
- [V] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antv-tooltip-plugin-combo-t5cgy?file=/index.js)

### Steps to reproduce
Hover on any `node` or `edge` to see that `tooltip` is shown as expected.
But when you hover on `combo` `tooltip` is NOT shown and the `itemTypes: ['node', 'edge', 'combo']` and the debugging shows that `getContent(e:IG6GraphEvent)` function is not fired.

| Environment | Info |
|---|---|
| g6 | 4.0.1 |
| System | Windows 10 |
| Browser | Chrome  87.0.4280.66 |

---
It's a fork of example on the official documentation except that combos are added.
https://g6.antv.vision/en/examples/tool/tooltip#tooltipPlugin

**Comment by Yanyan-Wang** [comment]
Thanks, will be fixed by next small version

**Comment by Yanyan-Wang** [comment]
v4.0.2 已解决
