### ISSUE TITLE
自定义节点，锚点在内部，使用polyline链接，边显示异常

### ISSUE THREAD

**Issue by HuChundong** [antvis/G6#2352]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/HuChundong/g6demo](https://github.com/HuChundong/g6demo)

### Steps to reproduce
直接run项目即可，初始化状态下边不显示，拖动之后显示异常

| Environment | Info |
|---|---|
| g6 | 4.0.1 |
| System | macos |
| Browser | edge87 |

---
按照最短路径正常查找边

**Comment by Yanyan-Wang** [comment]
v4.1.7 修复了
