### ISSUE TITLE
删除group

### ISSUE THREAD

**Issue by Heheroes** [antvis/G6#2353]
这个节点删除之后 group怎么删除，求解决。问题很久了，combo满足不了项目需求
<img width="801" alt="demo" src="https://user-images.githubusercontent.com/46218273/100317153-d1029600-2ff6-11eb-80d2-ba885bdf6a4c.png">

**Comment by Heheroes** [comment]
源码里
const nodeItem = findById(item) 
removeItem(item)   如果item为字符串并且找不到节点实例 ，为删除组。
直接 removeItem(groupId)会报错   还是得提前findById(groupId)
但是这样删除group并不会生效

**Comment by baizn** [comment]
什么需求 Combo 满足不了，group 4.0已经删了，不能满足需求的如果是 combo 功能缺失我们会增加上去的。
删除 group 用 removeItem，参考这里 https://g6-v3-2.antv.vision/zh/docs/api/Graph/#removeitemitem  删除不了看下是不是 groupID不对

**Comment by Heheroes** [comment]
> 什么需求Combo满足不了，group 4.0已经减少了，不能满足需求的如果是combo功能缺失我们会增加上去的。delete
> group用removeItem，参考这里[https://g6-v3-2.antv.vision/zh/ docs / api / Graph /＃removeitemitem](https://g6-v3-2.antv.vision/zh/docs/api/Graph/#removeitemitem) 删除不了看下是不是groupID不对

TypeError: Cannot read property 'getModel' of undefined  => 调用graph.removeItem(groupId)会报这个错。参数传节点就不会报错。groupId也没错

**Comment by Heheroes** [comment]
> 什么需求 Combo 满足不了，group 4.0已经删了，不能满足需求的如果是 combo 功能缺失我们会增加上去的。
> 删除 group 用 removeItem，参考这里 https://g6-v3-2.antv.vision/zh/docs/api/Graph/#removeitemitem 删除不了看下是不是 groupID不对

combo 内节点数量变量会自动向中间缩放，这样会影响位置，可不可以新增一个控制是否自动缩放的属性

**Comment by Heheroes** [comment]
![remogroup](https://user-images.githubusercontent.com/46218273/100338082-1cc33880-3013-11eb-86ef-323e986418a1.jpg)
