### ISSUE TITLE
Where does self in layout.worker.ts come from?

### ISSUE THREAD

**Issue by StarkShang** [antvis/G6#2354]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/antvis/G6/blob/master/src/layout/worker/layout.worker.ts](https://github.com/antvis/G6/blob/master/src/layout/worker/layout.worker.ts)

### Steps to reproduce
I am wondering where is the definition of the self object;
in line 80 of [layout.worker.ts](https://github.com/antvis/G6/blob/master/src/layout/worker/layout.worker.ts)

```typescript
const ctx: Worker = self as any;
```

| Environment | Info |
|---|---|
| g6 | 4.0.1 |
| System | - |
| Browser | - |

**Comment by Yanyan-Wang** [comment]
Refer to https://stackoverflow.com/questions/50210416/webpack-worker-loader-fails-to-compile-typescript-worker
