### ISSUE TITLE
在Treegraph中 当节点的label字数超过一定长度 ，会出现节点size异常的问题

### ISSUE THREAD

**Issue by niceyida** [antvis/G6#2355]
如果在Treegraph画布中，收缩只剩两个节点，且其中一个节点的label长度超过一定字数 大概是6个字以上，此时，作适应画布的操作会引起节点的size异常的大的问题，请问有没有什么解决方法或者思路？

**Comment by Yanyan-Wang** [comment]
请给出现在复现 demo

**Comment by niceyida** [comment]
[demo.zip](https://github.com/antvis/G6/files/5605896/demo.zip)

**Comment by niceyida** [comment]
请问有复现到现象吗？ 我查看issue列表没有看到类似问题

**Comment by Yanyan-Wang** [comment]
可以给出最小的在线 demo 吗，下载文件我们这不是很方便的呢

**Comment by niceyida** [comment]
https://niceyida.github.io/project/demo.html 
先点击天一路集散场 ，再点击左上角适应页面按钮，即可看到现象

**Comment by niceyida** [comment]
请问有复现到现象吗 有没有方法解决这个问题

**Comment by Yanyan-Wang** [comment]
节点看起来变大跟 label 长度没啥关系吧？fitView 的意思就是让图上的内容缩放到能够填充视窗。如果你不希望这样的话，就调用 graph.fitCenter 而不是 graph.fitView 就行

**Comment by niceyida** [comment]
但是把label变短这个现象就消失了  采用fitcenter会按照实际大小 就会显得有点太小了

**Comment by Yanyan-Wang** [comment]
fitView 也可以传 padding 进去 fitView(50) 这样

**Comment by niceyida** [comment]
加上fitView(padding)是可以解决某些情况下触发过大， 但是会引起更多的异常显示，
比如加上fitView(padding)  就会导致原本正常显示的树图都会很小 。

**Comment by niceyida** [comment]
fitView 的意思就是让图上的内容缩放到能够填充视窗 但是收缩为一个节点的时候它的显示是正常大小，两个的时候就会很大，这看起来好像是有问题的

**Comment by Yanyan-Wang** [comment]
按理来说应该是填充了视窗，节点数量少的时候变大是正常的。一个节点的时候没有填充应该是有问题的，后面会跟进一下。这个问题已经和该 issue 不大相关了哈，这个 issue 就先关了。
