### ISSUE TITLE
用G6.registerNode这个方法如何注册自定义图片的shape？

### ISSUE THREAD

**Issue by RenektonZ** [antvis/g6#236]

**Comment by TomHuangCN** [comment]
用 html 节点 https://antv.alipay.com/zh-cn/g6/1.x/demo/other/htmlnode.html

**Comment by RenektonZ** [comment]
结合森林图的话一直会报错，g6-plugins.min.js:4 Uncaught TypeError: Cannot read property 'hide' of undefined

**Comment by RenektonZ** [comment]
weight权重是什么？没有具体的说明文档啊
