### ISSUE TITLE
node: rect 能否控制显示某一个border ?

### ISSUE THREAD

**Issue by DevinWell1ee** [antvis/G6#2361]
内置节点rect能否只展示某一边？

**Comment by Heheroes** [comment]
如果想只显示一个边框，可以试试自定义节点。参照demo示例 https://g6.antv.vision/zh/examples/item/customNode#card

**Comment by Yanyan-Wang** [comment]
内置的节点类型和图形没有支持单个 border ，可以按照 @Heheroes 同学提到的问题实现哈
