### ISSUE TITLE
是否支持移动端

### ISSUE THREAD

**Issue by txlwll** [antvis/G6#2362]
最新版本在移动端上是否可以拖拽，移动端放大后页面会出现有滚动条

**Comment by baizn** [comment]
支持移动端和小程序的 G6 版本目前正在开发中，预计年后就会发布。

**Comment by Yanyan-Wang** [comment]
已发布 @antv/g6-mobile，欢迎试用

**Comment by biology-w** [comment]
> 已发布 @antv/g6-mobile，欢迎试用

g6-mobile是单独库嘛？ 有手机端文档吗
