### ISSUE TITLE
提供一个清除所有节点状态量的 api

### ISSUE THREAD

**Issue by liyangzw** [antvis/G6#2363]

**Comment by liyangzw** [comment]
好比我点击某个节点，当前节点新增一个属性，别的接点取消这个属性

**Comment by Heheroes** [comment]
nodeStateStyles: {}或者 edge的state状态api都有。你自己设置好对应的状态值，getNodes获取所有节点遍历，setItemState和clearItemStats用来设置状态和清楚状态。具体的自己看看文档示例或者api
