### ISSUE TITLE
drag-canvas移动端不能使用

### ISSUE THREAD

**Issue by Charon01** [antvis/G6#2366]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/charon01/pen/JjRjZqp?editors=1111](https://codepen.io/charon01/pen/JjRjZqp?editors=1111)

### Steps to reproduce
移动端下使用drag-canvas

| Environment | Info |
|---|---|
| g6 | 4.0.2 |
| System | android |
| Browser | - |

---
pc端可以，但是移动端下无法移到，移动端下是否支持？

**Comment by gaojinwei** [comment]
通过touch事件registerBehavior自己实现

**Comment by fangoo** [comment]
请问移动端拖动的功能解决了么，能否贴出来看看呢

**Comment by Yanyan-Wang** [comment]
升级到最新版本，可以支持移动端拖动画布哦。v4.2.1
