### ISSUE TITLE
当画布先创建一个自定义图片节点，brush-select设置的的背景颜色和透明度就会失效，显示的是一个不透明的白框

### ISSUE THREAD

**Issue by CoderQuixote** [antvis/G6#2368]

**Comment by CoderQuixote** [comment]
https://github.com/CoderQuixote/welabx-g6.git demo地址麻烦看一下，谢谢

**Comment by CoderQuixote** [comment]
![捕获111](https://user-images.githubusercontent.com/9650008/100630724-e0227480-3365-11eb-8b0a-171a36983b2c.PNG)

**Comment by CoderQuixote** [comment]
![111222捕获](https://user-images.githubusercontent.com/9650008/100630968-3099d200-3366-11eb-90f2-db5dce98e905.PNG)
上面的截图先创建图形是正常的，下面这个图先创建图片节点的时，brush-select创建的brush背景和fill样式失效，并且选择完区域之后不消失

**Comment by Yanyan-Wang** [comment]
麻烦实现一个最小复现的在线 demo，在一整个项目找问题效率实在太低

**Comment by CoderQuixote** [comment]
用dom元素重写了brush-select里面的brush解决了这个问题，问题的原因后面再看

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
