### ISSUE TITLE
如何阻止G6的ctrl+v和ctrl+c的默认复制粘贴或者其他一些自带的事件？

### ISSUE THREAD

**Issue by 405go** [antvis/g6#237]
因为我需要在复制粘贴的操作还需要增加一些业务逻辑，所以我想禁用默认的复制粘贴。

**Comment by 405go** [comment]
this.net.on('keydown', (ev) => {
      if (ev.ctrlKey) {
        if (ev.keyCode === 67) {
          // 复制
          console.log('复制')
        }
        if (ev.keyCode === 86) {
          // 粘贴
          console.log('粘贴')
        }
      }
}
我需要重写复制粘贴，但是怎么阻止g6的复制粘贴操作

**Comment by qjs2000** [comment]
在自己的代码里面重写copy和paste函数
    net.copy = function() {};
    net.paste = function() {};
