### ISSUE TITLE
4.0.2版本，rect类型节点hover状态位置漂移

### ISSUE THREAD

**Issue by iamoldli** [antvis/G6#2370]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/intelligent-https-vwcl6)

### Steps to reproduce
4.0.2版本中，如果节点类型是rect，当通过节点的mouseenter以及mouseleave实现hover功能时，mouseleave之后节点位置会漂移。

| Environment | Info |
|---|---|
| g6 | 4.0.2 |
| System | windows |
| Browser | Microsoft Edge 87.0.664.47 |

**Comment by Heheroes** [comment]
<img width="857" alt="截屏2020-12-01 下午2 12 22" src="https://user-images.githubusercontent.com/46218273/100703853-5f07c380-33df-11eb-9905-d3e5df6c61e1.png">
我打开你的在线demo没有发现问题，我用的chrome。你是只在ie下会出现吗

**Comment by iamoldli** [comment]
我试了Chrome，版本86.0.4240.198也有这个问题
![1](https://user-images.githubusercontent.com/7851430/100705984-1f42db00-33e3-11eb-9358-a867587699be.gif)

**Comment by Yanyan-Wang** [comment]
正在修复。4.0.3 将会解决

**Comment by Yanyan-Wang** [comment]
4.0.3 已解决。看起来 codesandbox 上包的版本更新速度没这么快。可以在本地 update 最新包试一下。
