### ISSUE TITLE
关于combo大小动态计算

### ISSUE THREAD

**Issue by Heheroes** [antvis/G6#2373]
可否加一个属性控制是否动态计算。如果为false，则第一次渲染之后大小固定不会再变化。可视化的好多项目需求都对应指定时间和位置信息，如果动态计算combo大小。一旦内部节点发生变化，combo大小变化会导致位置变化。甚至导致多个y轴并列的组合内节点一起改变时部分区域叠加产生覆盖视觉 @Yanyan-Wang

**Comment by Yanyan-Wang** [comment]
如果 combo 大小和位置不变化，增加的内部节点可能在视觉上不在 combo 中。我理解最好的解决方案是不是 combo 大小位置发生变化后，其他 combo 相应地调整位置，以腾出足够空间。

**Comment by Heheroes** [comment]
> 如果 combo 大小和位置不变化，增加的内部节点可能在视觉上不在 combo 中。我理解最好的解决方案是不是 combo 大小位置发生变化后，其他 combo 相应地调整位置，以腾出足够空间。

比如我项目中不存在增加，第一次渲染后只会进行节点删除。因为我有翻页操作。会删除当前页渲染下一页。添加只会在展示当前节点子关系时添加一个新的combo和内节点放到固定位置。我认为在很多复杂的需求中。是否自动改变大小让使用者自己选择，更为方便。当然我也理解你们的初衷是更智能化。如果不能添加控制属性，我不知道您有没有什么更好的解决方案帮助我目前的困境，感谢

**Comment by Heheroes** [comment]
> 如果 combo 大小和位置不变化，增加的内部节点可能在视觉上不在 combo 中。我理解最好的解决方案是不是 combo 大小位置发生变化后，其他 combo 相应地调整位置，以腾出足够空间。

目前我的项目中，自己在画布上添加了时间区域背景。而且数据量很大，坐标都是根据时间计算好固定到某个区域。同一时间会并列y轴增加。就已经渲染好了之后，每个combo域不想在动。除非删除combo。

**Comment by baizn** [comment]
会存在拖动 combo 中节点的交互吗？ 还是说你只需要删除 combo 中节点，不会有拖动 combo、拖动 combo 中节点等这些交互？

**Comment by Heheroes** [comment]
> 会存在拖动 combo 中节点的交互吗？ 还是说你只需要删除 combo 中节点，不会有拖动 combo、拖动 combo 中节点等这些交互？

不允许拖动，因为坐标渲染前已经计算好，位置不会变化。我现在是以域划分，可以理解为画布上都是group标签。一个大节点group。里面有具体的节点列表。我的节点列表是计算的固定位置对应着固定时间段。我只要画布新增节点就会有对应的域也就是group或者combo。删除有两种情况。一是删除这个分组和底下的所有节点。而是删除这个分组下所有的节点在渲染新的节点列表也就是翻页。目前我用的旧版本的group。所有需求都可以实现，但是出现一个bug。就是删了右侧的group总是会留一块在画布上。就好像擦黑板一个字只擦了一半

**Comment by Heheroes** [comment]
<img width="344" alt="demo" src="https://user-images.githubusercontent.com/46218273/100977819-7c25c900-357c-11eb-8280-e19a1505c358.png">
@Yanyan-Wang @baizn bug是这样的。我下午有时间写个在线demo贴上
