### ISSUE TITLE
why id of data can't be number?

### ISSUE THREAD

**Issue by beizhedenglong** [antvis/G6#2374]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/g6-ix66f)

### Steps to reproduce
just open the demo link

| Environment | Info |
|---|---|
| g6 | 4.0.2 |
| System | - |
| Browser | - |

**Comment by Yanyan-Wang** [comment]
It is designed to be that. I think there is no cost for users to use string instead of number for id. If you are worried about generating unique ids, try G6.Util.uniqueId()

**Comment by beizhedenglong** [comment]
The app was crashed directly. I can’t find any clue from the error message.

**Comment by Yanyan-Wang** [comment]
Thanks, we will try to add warning message for this situation.
