### ISSUE TITLE
style中使用inline导致定位异常

### ISSUE THREAD

**Issue by HuChundong** [antvis/G6#2375]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/keen-gagarin-b4jkd)

### Steps to reproduce
每个节点内，有上中下三个锤子放置的group，每个group内有 左中右三个水平放置的text，前两个text设置inline，第三个不设置
第二个group不是从左侧开始，而是从第一个group的末尾开始计算

| Environment | Info |
|---|---|
| g6 | 4.0.3 |
| System | - |
| Browser | - |

---
垂直的三个元素，应该都是从左侧开始计算位置，遇到不是inline的元素，offset x这个变量 应该要重置

**Comment by mxz96102** [comment]
这个应该是因为 group 没有按照一个 shape 来进行定位，所以两个隔着 group的元素被判定为同级元素了，我修复一下

**Comment by HuChundong** [comment]
> 这个应该是因为 group 没有按照一个 shape 来进行定位，所以两个隔着 group的元素被判定为同级元素了，我修复一下

就算不加group也有问题
<a inline><a inline><a><b inline><b inline><b>

理论上应该是
a a a
b b b

但是实际上4.0.3版本会输出
 a a a
       b b b

**Comment by mxz96102** [comment]
……我没有注意到你有元素是白色的，那我重新看一下

**Comment by HuChundong** [comment]
> ……我没有注意到你有元素是白色的，那我重新看一下
你看一下那个demo里面，createText这个方法，可以把group去掉，相当于生成 9个 text，中间有两个是非 inline的元素，偏移计算是有问题的。
另外问一下，开发环境node你们用的是那个版本啊，本机下载不到 electron的指定版本
