### ISSUE TITLE
使用create-edge行为，然后对刚创建好的edge进行remove后报错

### ISSUE THREAD

**Issue by biggbb777** [antvis/G6#2376]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/brave-wind-9tih1?file=/src/index.js)

### Steps to reproduce
按住shift拖拽触发create-edge行为进行边的创建。
当source为combo, target为node时，发生报错。

'Cannot read property 'keyShape' of null'
'Cannot read property 'type' of null'

| Environment | Info |
|---|---|
| g6 | 4.0.3 |
| System | - |
| Browser | - |

---
业务场景: 需求为node和combo之间不能进行连线（combo和combo之间才可以）。

1. 当边的source为node，target为combo时，我使用了shouldBegin来限制边的创建（这成功了)。
2. 当边的source为combo, target为node时，我无法在shouldBegin时限制边创建，所以我监听了'aftercreateedge'事件以便在边创建好之后，删除这个我不需要的边，但是这样做却发生了报错。我试过在shouldEnd中禁止边创建的结束，但是不行，会有边残留的问题（具体见demo，多试几次就会出问题了）

**Comment by Yanyan-Wang** [comment]
在 removeItem 之前包一个 setTimeout 即可
```
    setTimeout(() => {
      graph.removeItem(e.edge);
    }, 0)
```

应该是与底层渲染引擎在渲染上做了 debounce 有关

**Comment by 313392073** [comment]
![1642472391(1)](https://user-images.githubusercontent.com/26107293/149859664-9cd9d133-4e1c-4b19-8355-c4b3c8facba2.jpg)
请问一下这个问题解决了吗 我这边加了定时器还是没有解决

**Comment by 7hao123** [comment]
请求把这个加入文档里面，找了好久都找不到这个问题怎么解决，终于解决了，谢谢
