### ISSUE TITLE
请问在treegraph模型中采用radial布局 可以不让它按照圆形辐射吗，调整为随机或者不规则的向外辐射

### ISSUE THREAD

**Issue by niceyida** [antvis/G6#2378]

**Comment by Yanyan-Wang** [comment]
不是很明白如何不规则向外辐射。TreeGraph 有两种 radial：dendrogram 和 compactBox 两种布局的变形。前者是所有叶子节点在同一层，后者是深度相同的节点在同层。除此之外树图没有提供其他 radial 的形式。如果你用 Graph 的话，可以自定义布局

**Comment by niceyida** [comment]
两种深度的我都试过了 就想问问有没有方法让它不是呈标准圆形向外辐射 在treegraph中
