### ISSUE TITLE
drag-canvas does not work if user started dragging on a node

### ISSUE THREAD

**Issue by konstantinjdobler** [antvis/G6#2379]
- Create G6.Graph with "drag-canvas" option
- The graph can only be dragged when the user starts dragging on the empty space, but not when he starts on a node or an edge

Is this expected behaviour? If so, how could I make it work with nodes & edges too?

**Comment by baizn** [comment]
this is expected behaviour，if you want to drag canvas and node,   Create G6.Graph with "drag-canvas, drag-node" option.
Currently don't support drag edge

**Comment by Yanyan-Wang** [comment]
The drag event will be caught by the operated item(node or edge). The interaction is designed to be that only when the drag event is caught by the canvas but not a node or an edge, the canvas is dragged. If you wanna disable drag event on nodes or edges, try this way:

```
graph.getNodes().forEach(node => {
  const group = node.getContainer();
  group.set('capture', false);
})

```
Similar to edges.

**Comment by konstantinjdobler** [comment]
Thank you for your help, indeed this works! However, this prevents the capturing of all events by nodes and edges. Is there a way to only prevent the capturing of drag events?

**Comment by Radomir-Drukh** [comment]
If you are looking how to do it in 2023, here is an example 
`
graph.on('edge:dragstart', (event: IG6GraphEvent) => {
  event.target = graph.get('canvas');
  graph.emit('canvas:dragstart', event);
 });
`

**Comment by gionkunz** [comment]
I needed to add targetType additionally:

```
    this.#graph.on('combo:dragstart', (event: IDragEvent) => {
      if (this.#graph) {
        event.targetType = 'canvas';
        event.target = this.#graph.getCanvas() as any;
        this.#graph.emit('canvas:dragstart', event);
      }
    });
```
