### ISSUE TITLE
G6自定义图形对IE支持问题

### ISSUE THREAD

**Issue by jcllove** [antvis/g6#238]
例子：http://antv.alipay.com/zh-cn/g6/1.x/demo/flow/saoma.html
自定义图形使用getHtml返回一个定义好的DOM元素，这个方法的实现使用G6.Util.createDOM()创建元素，然后appendChild()添加元素，但是在IE环境中对嵌套元素是有问题的，只能识别一层关系，必须使用document.createElement()的方式才能正确识别，希望改进G6.Util.createDOM()对IE的实现。

var e = G6.Util.createDOM('&lt;div class="node-container-list"&gt;&lt;span&gt;a&lt;/span&gt;&lt;span&gt;b&lt;/span&gt;&lt;/div&gt;');
container.appendChild(e); 
 // 结果&lt;container&gt;&lt;div class="node-container-list"&gt;&lt;/div&gt;&lt;/container&gt;, 内部span元素不会被IE识别

IE需要如下方式:
	var div = document.createElement('div');
	var span1 = document.createElement('span');
	var span2 = document.createElement('span');
	span1.appendChild(document.createTextNode('a'));
	span2.appendChild(document.createTextNode('b'));
	div.appendChild(span1);
	div.appendChild(span2);

       container.appendChild(div);  // 这种方式IE识别

**Comment by jcllove** [comment]
修改

**Comment by TomHuangCN** [comment]
感谢反馈，会排期改进。

**Comment by TomHuangCN** [comment]
这个是用 innerHtml 做的，经测，没有这个兼容性问题。
