### ISSUE TITLE
拖拽画布时，画布的移动需立即响应，而不是延迟响应。

### ISSUE THREAD

**Issue by Heqingsong** [antvis/G6#2380]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在地图业务开发时，因业务场景需要，需在地图上方叠加一层G6的图层进行关系数据显示。当地图移动时，G6图层会跟着进行移动。

目前遇到的问题是：

当鼠标按下时轻微移动4 - 5 个屏幕像素后，G6的画布才会跟着进行移动，在界面上当用户缩放的地图为全球级别时，用户拖动地图已经移动到很远的距离了，G6才会突然响应，造成卡顿的用户视觉体验。

希望解决的方式：

当鼠标按下时，只要用户鼠标位置发生轻微移动，画布就立即进行响应。

### What does the proposed API look like?
API功能不变。

**Comment by Heqingsong** [comment]
打开官方任意demo，按下鼠标轻微移动 4 - 5 像素的距离就能重现该问题。

**Comment by baizn** [comment]
这样处理是为了在触摸板下处理点击和拖拽事件，使用触摸板时，很多时候点击下去会有几像素的偏差，如果把这种当成拖拽和用户预期是不符的。正常拖拽画布是没有问题的，轻微拖拽误差在 3-4 像素内会认为是点击，如果还持续，那就按拖拽来处理了。逻辑上应该是没有问题的，你上面提到的拖动地图很远后，G6 才响应，能提供一个在线 demo 吗

**Comment by Heqingsong** [comment]
![QQ20201203-113543-HD](https://user-images.githubusercontent.com/3097338/100960724-d19dae00-355b-11eb-8756-d398fe99be64.gif)

@baizn

**Comment by Heqingsong** [comment]
我想要实现的是，当我鼠标按下进行拖拽的时候，画布就能立即进行响应

官方这个案例也是能重现的
https://g6.antv.vision/zh/examples/interaction/zoomCanvasFixItem#fixItem

**Comment by Heqingsong** [comment]
![uri1t-4paaw](https://user-images.githubusercontent.com/3097338/100964466-aa4adf00-3563-11eb-916d-944afffd9a09.gif)

**Comment by Caozefu** [comment]
把地图也设置成延迟响应试试

**Comment by Heqingsong** [comment]
@baizn 这个问题官方会在下一个版本中进行修复吗？建议可以判定一下，如果是PC设备上就立即响应拖拽操作，如果是触摸板下就保持原逻辑不变。拜托啦🙏  😢

**Comment by Yanyan-Wang** [comment]
暂不考虑支持这一需求，可以考虑自己监听 mousedown mousemove mouseup 来模拟拖拽事件，并调用 graph.move 之类的方法平移
