### ISSUE TITLE
graph.updateItem更新节点id，重绘后，graph.findById(新id) 输出为undefine，并且重绘中drawShape中的group里的id为初始化id，导致group中定义的anchor及anchor事件中的父id也为初始化的id

### ISSUE THREAD

**Issue by Abbyzhoum** [antvis/G6#2381]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/objective-sea-keyqx?file=/src/App.vue)

### Steps to reproduce
1. 打开console控制台看输出， 双击 if101 橙色节点， 双击后有抽屉弹出，修改 节点ID字段 为任意字段，如 if12345，此操作 updateItem中的 id 字段（重绘）
2. 长按 橙色 if12345 节点的右侧瞄点 使其与 js1234567节点的左侧瞄点连接
3. console控制台输出 group 中的ID 与 节点 node.get('Model').id   不一致，且连接线中 source字段 为旧Id，若 修改 source 为新ID，则连接线不显示

| Environment | Info |
|---|---|
| g6 | 3.5.2 |
| System | mac |
| Browser | Chrome |

---
关键文件说明：
① 绘制连接线的逻辑在 src/graph/behavior/dragEdge.js 中实现
② 更新节点信息在 src/components/DetailPanel.vue 中实现，具体的方法名为 updatePanel()
③ 自定义节点在 src/graph/shape/node.js  中实现

期望结果，① 重绘后的 group 中的ID应为更新后的 节点ID
               ② 连接线的source 应为 更新后的 节点ID

**Comment by baizn** [comment]
graph.updateItem 不支持更新 ID 的，ID 是节点的唯一标识，新的 ID 说明该节点不存在，需要通过 addItem 添加。

**Comment by baizn** [comment]
拖拽连线的DEMO请参考这里：https://g6.antv.vision/zh/examples/interaction/setMode#setMode

**Comment by Abbyzhoum** [comment]
好的，谢谢
