### ISSUE TITLE
node:click event After clicking the node, click elsewhere and "Maximum call stack size exceeded" will appear

### ISSUE THREAD

**Issue by ychlgdr** [antvis/G6#2383]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ychlgdr/simulatorfront](https://github.com/ychlgdr/simulatorfront)

### Steps to reproduce
click any node,then click another node or canvas

| Environment | Info |
|---|---|
| g6 | 4.0.3 |
| System | Windows10 1909 |
| Browser | chrome 87.0.4280.66 |

error image 
![image](https://user-images.githubusercontent.com/39005242/100990991-78e70900-358d-11eb-980d-a4635a036453.png)

**Comment by Yanyan-Wang** [comment]
it is might be a bug of image node with states, will be fixed soon.

**Comment by ychlgdr** [comment]
> Thanks. It is might be a bug of image node with states, will be fixed soon.

Thank you

**Comment by summerLoveqq** [comment]
这个问题修复了么？如果修复了是在哪个版本修复的？现在想用4.x的功能用不了......

**Comment by Yanyan-Wang** [comment]
> 这个问题修复了么？如果修复了是在哪个版本修复的？现在想用4.x的功能用不了......

如果你不是用 image 类型的节点的话，没有影响的

**Comment by summerLoveqq** [comment]
> > 这个问题修复了么？如果修复了是在哪个版本修复的？现在想用4.x的功能用不了......
> 
> 如果你不是用 image 类型的节点的话，没有影响的

就是想要用image节点类型啊.....，然后还想做image节点的动画，3.X版本好像不行

**Comment by sunhanmin4213** [comment]
Uncaught RangeError: Maximum call stack size exceeded   现在节点是图像的，使用 brush-select出现这个报错，怎么修改啊

**Comment by Yanyan-Wang** [comment]
下个小版本会修复的，这两周内发布

**Comment by Yanyan-Wang** [comment]
v4.1.0-beta.1 已解决，欢迎试用
It has be en

**Comment by Yanyan-Wang** [comment]
正式版 4.1.0 已发布
v4.1.0 is released
