### ISSUE TITLE
G6Plugins['tool.d3.mapper']undefined

### ISSUE THREAD

**Issue by qq2575896094** [antvis/G6#2384]
升级到4.0.3后, G6Plugins['tool.d3.mapper']为undefined

**Comment by Yanyan-Wang** [comment]
嗯？一直也没有过这个吧。你是从哪个古老的版本上来的吗？

**Comment by mxz96102** [comment]
G6 3.0以后已经不支持这个插件了，如果要解决方案的话，建议自己看d3-legend和d3-scale实现一下，当初2.0版本实现看这里https://github.com/antvis/G6/blob/2.0.1/plugins/tool.d3.mapper/index.js
