### ISSUE TITLE
配置defaultEdge的labelCfg 背景后，边Label背景样式显示异常

### ISSUE THREAD

**Issue by Heqingsong** [antvis/G6#2387]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/agitated-shadow-x8338?file=/index.html)

### Steps to reproduce
当两个节点位置一致，并且两点之间存在边的情况下会出现该BUG

| Environment | Info |
|---|---|
| g6 | 4.0.3 |
| System | mac  |
| Browser | 版本 88.0.4324.27 |

---
修复该BUG

**Comment by Heqingsong** [comment]
![image](https://user-images.githubusercontent.com/3097338/101140179-911e5d00-364d-11eb-8f17-114b28bff1fb.png)

**Comment by Yanyan-Wang** [comment]
v4.1.0-beta.1 已解决，欢迎试用

**Comment by Yanyan-Wang** [comment]
正式版 4.1.0 已发布
