### ISSUE TITLE
TreeGraph下的onChange方法内使用addChild或者removeChild时，同时展开节点后，node位置会自动调节，但edge的位置不对

### ISSUE THREAD

**Issue by d623141153** [antvis/G6#2388]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/eager-browser-lhq3c?file=/index.js)

### Steps to reproduce
链接示例中，请点击图的右侧节点，先关闭再展开（因为右侧的节点有多个，展开收起会触发node位置的自动变化)，
但是线的位置就不会自动调节
在很早以前的版本(3.0)没有这个问题
最新及较新的版本都有这个问题
使用refreshLayout也没用

| Environment | Info |
|---|---|
| g6 | 4.0.3 |
| System | mac and windows |
| Browser | chrome edge等 |

**Comment by Yanyan-Wang** [comment]
应该和渲染引擎升级之后有 debounce 集中处理有关系。目前解决方案是：在你代码中 addChild 外包一层 setTimeout 即可
```
setTimeout(e => {
  graph.addChild(
    {
       id: `新添加的测试节点${Math.random()}`
    },  item
   );
}, 16)
```

**Comment by Yanyan-Wang** [comment]
上面加了 random 是为了多次添加节点的 id 不重复

**Comment by monolithed** [comment]
The same problem with `removeChild`

```ts
model.children?.forEach(() => {
      setTimeout(() => graph.removeChild(item.id), 0);
});
```
