### ISSUE TITLE
3.8版本group严重bug

### ISSUE THREAD

**Issue by Heheroes** [antvis/G6#2389]
> 版本 3.8.3
> 浏览器 chrome

老版本group删除存在bug
演示demo: https://codepen.io/heheroes/pen/eYdpabw

**Comment by Yanyan-Wang** [comment]
建议改为使用 combo，[文档](https://g6.antv.vision/zh/docs/manual/middle/elements/combos/defaultCombo)，group 被废弃。如果一定要使用的话，把局部渲染关掉可以解决这个问题：graph.get('canvas').set('localRefresh', false)
