### ISSUE TITLE
treeGraph画图节点重合

### ISSUE THREAD

**Issue by zhoustudent** [antvis/G6#2390]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/peaceful-dawn-d6vtj?file=/src/index.js)

### Steps to reproduce
更新数据就会偶现节点重合问题
![image](https://user-images.githubusercontent.com/22286864/101304503-5568da80-387b-11eb-8062-3381a3fe91e3.png)

| Environment | Info |
|---|---|
| g6 | 3.8.1 |
| System | 11.0.1 mac |
| Browser | - |

**Comment by Yanyan-Wang** [comment]
在你的 demo 中怎么复现？

必须确保所有节点的 id 都是唯一的 string 类型。

**Comment by zhoustudent** [comment]
知道原因了，是由于我这没做节流导致新老数据都会render，从而出现重合，多谢多谢
