### ISSUE TITLE
使用click-select行为，点击combo后拖拽，其大小会持续改变

### ISSUE THREAD

**Issue by biggbb777** [antvis/G6#2391]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/brave-wind-9tih1?file=/src/index.js)

### Steps to reproduce
1. 点击combo
2. 对刚刚点击的combo进行拖拽
3. 在拖拽过程中combo会发生持续性大小变化

| Environment | Info |
|---|---|
| g6 | 4.0.3 |
| System | - |
| Browser | - |

---
不太清楚为何会发生这样的情况。如果可以的话能在选中再进行拖拽时，让combo大小不发生变化吗？（但需要在node放入combo后，combo自动扩大）

**Comment by GPL1** [comment]
我也是，暂时这样解决的。禁止bomo选中。其他node可以选中

**Comment by GPL1** [comment]
{
                type: 'click-select',
                shouldBegin: (e) => {
                  if (e.item && e.item.getModel().children) {
                    return false;
                  } else {
                    return true;
                  }
                }
              },

**Comment by biggbb777** [comment]
> 我也是，暂时这样解决的。禁止bomo选中。其他node可以选中

这样确实可以，但是我这边需求可能还是得让combo有一个选中状态，有时候就不太能避免

**Comment by Yanyan-Wang** [comment]
v4.1.0-beta.1 已解决，欢迎试用

**Comment by Yanyan-Wang** [comment]
正式版 4.1.0 已发布

**Comment by biggbb777** [comment]
> 正式版 4.1.0 已发布

好的👌，非常感谢。
