### ISSUE TITLE
官方决策树demo里面 第三个节点第一次点击展开为何“+”不变“-”？事件在setState中 关闭状态点展开并不响应

### ISSUE THREAD

**Issue by SupaFan** [antvis/G6#2392]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g6.antv.vision/zh/examples/case/decisionTree#index](https://g6.antv.vision/zh/examples/case/decisionTree#index)

### Steps to reproduce
官方决策树demo里面 第三个节点第一次点击展开“+ ”不变“-”，事件在setState中 关闭状态点展开并不响应

| Environment | Info |
|---|---|
| g6 | 4.0.3 |
| System | - |
| Browser | - |

**Comment by Yanyan-Wang** [comment]
谢谢，应该是个 bug，从未设置过的状态默认是 false 的，第一次设置 collpase 状态为 false，被判断为状态没有改变，因此没有进入 setState。接下来会跟进一下

**Comment by Yanyan-Wang** [comment]
v4.1.0-beta.1 已解决，欢迎试用

**Comment by Yanyan-Wang** [comment]
正式版 4.1.0 已发布

**Comment by AlisonZXQ** [comment]
> 正式版 4.1.0 已发布

windows不兼容吗？
