### ISSUE TITLE
边hover状态不对

### ISSUE THREAD

**Issue by Common-zhou** [antvis/G6#2393]
当设置边的hover状态时，边上的label有问题，且渲染有问题。
具体描述:
在3.8.2版本中：力导向布局中，当拖动节点，一直到布局完成，如果鼠标移动到边上，它的hover状态不会消失(鼠标移开后)。在最新版本(4.0.3)中已解决。
但4.0.3布局完成后，鼠标放到边上，边的label行为不正确。
且卡顿。demo如下。

https://codesandbox.io/s/elated-pine-md1s5?file=/package.json

**Comment by Yanyan-Wang** [comment]
谢谢，是个 bug，接下来会跟进一下

**Comment by Yanyan-Wang** [comment]
下个小版本会修复，预计两周内

**Comment by Common-zhou** [comment]
> 下个小版本会修复，预计两周内

好的 辛苦了

**Comment by Yanyan-Wang** [comment]
v4.1.0-beta.1 已解决，欢迎试用

**Comment by Yanyan-Wang** [comment]
正式版 4.1.0 已发布
