### ISSUE TITLE
老项目用的v2版本的，现在打算使用v4版本，不影响之前v2的功能，有办法让v2和v4共存吗？

### ISSUE THREAD

**Issue by 2012shenghua** [antvis/G6#2395]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
两个版本都在 package.json 写好并且都安装以后，引入的时候写 @antv/g6/lib 或者 @antv/g6/es 应该就可以指定引入的是 v4

**Comment by 2012shenghua** [comment]
包名相同的话，写在后面的会把写在前面的覆盖掉

**Comment by Yanyan-Wang** [comment]
试试看这个 https://meixg.cn/2019/12/25/npm-module-diff-version/

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
