### ISSUE TITLE
使用addChild新增节点时新增的子节点展开但是会立马收回，重复添加则永远有一个节点不显示但是占位

### ISSUE THREAD

**Issue by Lcjcode9413** [antvis/G6#2397]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/silent-star-rpwvw?file=/index.js)

### Steps to reproduce
随意点击某个节点即可重现

| Environment | Info |
|---|---|
| g6 | 4.0.3 |
| System | win |
| Browser | chrome |

**Comment by Yanyan-Wang** [comment]
参考这里：https://codesandbox.io/s/eloquent-mahavira-g1mm8

且一定要注意不管是输入的 data 还是新增的节点数据，节点 id 必须是唯一的 string。

**Comment by Lcjcode9413** [comment]
> 参考这里：https://codesandbox.io/s/eloquent-mahavira-g1mm8
> 
> 且一定要注意不管是输入的 data 还是新增的节点数据，节点 id 必须是唯一的 string。

给一个节点批量添加子节点，这个操作有没有代码模板可以参考呢？graph.addChild(Any[],parent).子节点数据以数组方式传入不可以吗？

**Comment by Yanyan-Wang** [comment]
related to: https://github.com/antvis/G6/issues/2432
