### ISSUE TITLE
polyline类型 拖拽创建连线 卡顿问题

### ISSUE THREAD

**Issue by gary1in** [antvis/G6#2398]
4.0.2版本 使用polyline类型的线 拖拽创建的时候严重卡顿，官网demo上试了一下也是如此。换过浏览器和别的电脑环境出现的情况一样
https://g6.antv.vision/zh/examples/interaction/createEdge#drag

**Comment by Yanyan-Wang** [comment]
polyline 在不指定 controlPoints 时，将使用 A* 自动寻径算法，性能开销极大。建议自定义 polyline 根据起点终点简单指定折线。例如：http://g6.antv.antgroup.com/examples/item/customEdge/#customPolyline2
