### ISSUE TITLE
Tooltip is not implemented for Combo

### ISSUE THREAD

**Issue by mkomu** [antvis/G6#2399]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

It would nice to get also Tooltip plugin to support Combo objects, not only Nodes and Edges.

**Comment by Yanyan-Wang** [comment]
It supports combo, update to the latest version and add 'combo' into the configure `itemTypes` of Tooltip plugin.

**Comment by mkomu** [comment]
Great, thanks!

**Comment by L924553229** [comment]
> It supports combo, update to the latest version and add 'combo' into the configure `itemTypes` of Tooltip plugin.



> It supports combo, update to the latest version and add 'combo' into the configure `itemTypes` of Tooltip plugin.

new G6.Tooltip 与内置的 tooltip 插件有何不同么? 因为发现内置的 tooltip 不支持 Combo.
