### ISSUE TITLE
Hull fails with a single node member

### ISSUE THREAD

**Issue by mkomu** [antvis/G6#2400]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

The latest version of G6 has a bug when a hull has only a single member. For instance, if you change the example from here:

https://g6.antv.vision/en/examples/interaction/hull/API

...to include only a single member in the hull, and rendering the graph just fails.

**Comment by Yanyan-Wang** [comment]
Thanks, we will fix it as soon as possible

**Comment by Yanyan-Wang** [comment]
It has been fixed by 4.1.0-beta.1

**Comment by mkomu** [comment]
Thanks!

**Comment by Yanyan-Wang** [comment]
v4.1.0 is released
