### ISSUE TITLE
老项目v2升级到v4, 如何兼容forceAtlas2布局

### ISSUE THREAD

**Issue by qq2575896094** [antvis/G6#2401]
请问, 在从老项目中升级到v4版本上来, 如何兼容之前的forceAtlas2布局

**Comment by Yanyan-Wang** [comment]
后面会考虑把这个布局算法放到 v4 当中。现在用 v4 的话可以用类似的三种力导向布局 force gForce fructerman，后两者还支持 gpu

**Comment by Yanyan-Wang** [comment]
v4.2.5 已增加 forceAtlas2 https://g6.antv.vision/zh/docs/api/graphLayout/forceAtlas2/#gatsby-focus-wrapper
