### ISSUE TITLE
如何判断isInPointOut和isInPoint已经被连线

### ISSUE THREAD

**Issue by lixianyu-icon** [antvis/G6#2402]
- **G6 3.0.2**:  
- **双输入节点、双输出节点类型如果已经有一根连线了，我怎么判断已连的线是连接到哪个锚点上的？我这里需要做限制，一个锚点只能连一根线**:

**Comment by Yanyan-Wang** [comment]
啥意思，isInPointOut 和 isInPoint 是啥？请按照 issue 模版来提问。。

**Comment by lixianyu-icon** [comment]
> 啥意思，isInPointOut 和 isInPoint 是啥？请按照 issue 模版来提问。。
