### ISSUE TITLE
Force 布局无法停止迭代

### ISSUE THREAD

**Issue by zuiidea** [antvis/G6#2403]
问题描述：
1. 使用force布局时，若布局未完全完成迭代时，使用`forceSimulation.stop()`暂停布局生效
2. 若force布局已完全完成一次布局，即是触发`onLayoutend`时，使用`forceSimulation.stop()`暂停布局无效

图1：`stop`成功的效果
![stop](https://user-images.githubusercontent.com/16070518/101597047-1bd9d000-3a31-11eb-8381-5830db1567f5.gif)

图2：`stop`失败的效果
![unstop](https://user-images.githubusercontent.com/16070518/101597050-1e3c2a00-3a31-11eb-9127-327d269a9af3.gif)

在线演示：

[![Edit Stop Force Layout](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/stop-force-layout-gq89t?fontsize=14&hidenavigation=1&theme=dark)

**Comment by Yanyan-Wang** [comment]
把 if (forceLayout.ticking) 判断去掉即可

**Comment by zuiidea** [comment]
😂
