### ISSUE TITLE
G6可否增加一个可使用第三方动画库的功能,  如  rc-tween-one 中现有的动画

### ISSUE THREAD

**Issue by hyuanyuanlisiwei** [antvis/G6#2404]
G6可否增加一个可使用第三方动画库的功能,  如  rc-tween-one 中现有的动画.

自己写好多动画状态好复杂.

**Comment by Yanyan-Wang** [comment]
短期内没有考虑支持。canvas 和 css 的机制也完全不一样，引入也不能使用的。
