### ISSUE TITLE
可否增加一些内置的节点增删改查的动效状态

### ISSUE THREAD

**Issue by huyy5566** [antvis/G6#2406]
请问G6可否内置一些节点边显示隐藏的动效状态,  提高用户体验.   谢谢

**Comment by baizn** [comment]
能把具体需求列一下吗？ 动效状态具体是哪些

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
