### ISSUE TITLE
自定义布局 G6.registerLayout 中 getDefaultCfg() 不起作用.

### ISSUE THREAD

**Issue by jxj666** [antvis/G6#2407]
版本    "@antv/g6": "^3.8.5",
getDefaultCfg api 是否被废弃?
实例: https://codesandbox.io/s/great-fog-gnc5d

**Comment by Yanyan-Wang** [comment]
感谢反馈，我们正在修复。

**Comment by Yanyan-Wang** [comment]
新版本中已无此问题，感谢报告
