### ISSUE TITLE
beginAdd 可以连续操作吗？画出第一条连先后，可以直接进行第二条连线的操作

### ISSUE THREAD

**Issue by luoyong1989** [antvis/g6#241]
1. beginAdd 可以连续操作吗？如 画出第一条连先后，不用再去点击一下添加连线的按钮可以直接进行第二条连线的操作。
2. 怎么样才能监听到 连线真正被绘制的事件了。当监听"**itemadd**"的时候是在鼠标按下是触发的。

**Comment by gostfather** [comment]
我用mouseup..你可以试试
