### ISSUE TITLE
可否增强combo布局机制

### ISSUE THREAD

**Issue by huyy5566** [antvis/G6#2411]
只针对combo 可以单独使用 层次 环形  层次  力导等常用布局.
而combo中的node 也可以单独设置常用布局.

**Comment by Yanyan-Wang** [comment]
目前还没有合理的方案。欢迎 pr

**Comment by Yanyan-Wang** [comment]
新版本中新增了 comboCombined 布局，可自由配置内外不同的布局算法
demo：http://g6.antv.antgroup.com/examples/net/comboLayout/#comboCombined
文档：http://g6.antv.antgroup.com/api/graphlayout/combocombined
