### ISSUE TITLE
setState is slow

### ISSUE THREAD

**Issue by zxch3n** [antvis/G6#2413]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/youthful-wildflower-stv1y?file=/index.js)

### Steps to reproduce
hover 到每个节点，严重掉帧

| Environment | Info |
|---|---|
| g6 | 4.0.3 |
| System | macOS |
| Browser | Chrome |

---
节点的 setState 过慢，单个节点 setState 耗时高达 0.5ms

**Comment by zxch3n** [comment]
`setTimeout` and `clearTimeout` in `StateController` take up a lot of time when updating state

https://github.com/antvis/G6/blob/master/src/graph/controller/state.ts#L100-L108

**Comment by zxch3n** [comment]
Why not using immutable to handle state? deepMix is causing a lot of performance problem.

**Comment by Yanyan-Wang** [comment]
the performance of setState is improved! welcome to try the latest version
