### ISSUE TITLE
求助树布局如何修改节点间距离，getVGap设置0或负值无效

### ISSUE THREAD

**Issue by feng-1234567** [antvis/G6#2415]
![image](https://user-images.githubusercontent.com/75930046/102008034-9758bb80-3d68-11eb-8ed1-b8095331b5cd.png)
需求如图：中心节点上下连接点进行点击可分别收起上下子节点。
方案一：设计上下连接点为子节点，则如何对子节点进行定位？
方案二：如何自定义收起时隐藏部分子节点？
或者有其他方法实现，求助各位大佬~

**Comment by Yanyan-Wang** [comment]
为什么要用节点来代表连接点？直接用节点的 linkPoint 就行，https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/built-in/rect#linkpoints

然后监听 linkPoint 图形的点击事件，参考 https://g6.antv.vision/zh/examples/case/decisionTree#index。
