### ISSUE TITLE
Fruchterman 聚类布局渲染速度太慢

### ISSUE THREAD

**Issue by gametheworld** [antvis/G6#2416]
600+的点渲染至少要40秒，跪求优化方案，数据因为敏感不好放demo

![image](https://user-images.githubusercontent.com/6021628/102013666-99347600-3d8c-11eb-83b9-600eb667dbfe.png)

**Comment by Yanyan-Wang** [comment]
你的一个节点只是这样的圆形？那应该渲染不会慢的。使用了什么布局算法吗？可能是布局算法慢，用 4.x 可以用 GPU 版本的 fruchterman 和 gforce，速度会快很多。 https://g6.antv.vision/zh/docs/api/graphLayout/fruchterman/#layoutcfggpuenabled

**Comment by gametheworld** [comment]
> 你的一个节点只是这样的圆形？那应该渲染不会慢的。使用了什么布局算法吗？可能是布局算法慢，用 4.x 可以用 GPU 版本的 fruchterman 和 gforce，速度会快很多。 https://g6.antv.vision/zh/docs/api/graphLayout/fruchterman/#layoutcfggpuenabled

`graph = new G6.Graph({
      container: ref.current,
      width,
      height,
      layout: {
         type: 'fruchterman',//
        speed: 5,
        gravity:15,
        clustering: true,
      },
      animate: true,
      defaultNode: {
        size: 10,
      },
      defaultEdge: {
        style: {
          endArrow: {
            path: 'M 0,0 L 8,4 L 8,-4 Z',
            fill: '#e2e2e2',
          },
        },
      },

      modes: {
        default: [
          'drag-node',
          'drag-canvas',
          {
            type: 'tooltip',
            formatText: function formatText(model) {
              const data=model;
                if(model.name){
                  let str="姓名："+data.name+"<br/>";
                  str=str+"性别：" +data.gender+"<br/>";
                  str=str + "级别：" +data.type+"<br/>";
                  str=str + "院校：" +data.company_name+"("+data.college+")"+"<br/>";
                  str=str +"专业：" + data.major_name+"<br/>";
                  str=str+"获奖：" + data.t2Type.join(',');
                  return str;
                }
                return null;
            },
            shouldUpdate: function shouldUpdate() {
              return true;
            },
          },
        ],
      },
    });`
![image](https://user-images.githubusercontent.com/6021628/102061093-f8969280-3e2d-11eb-8c33-4db496593f6f.png)
node根据数据显示size大小，加载至少1分钟
这是我的配置

**Comment by gametheworld** [comment]
> 你的一个节点只是这样的圆形？那应该渲染不会慢的。使用了什么布局算法吗？可能是布局算法慢，用 4.x 可以用 GPU 版本的 fruchterman 和 gforce，速度会快很多。 https://g6.antv.vision/zh/docs/api/graphLayout/fruchterman/#layoutcfggpuenabled
下面是我单个node的对象
`{
      "id": "123",
      "label": "",
      "cluster": "中国画学院",
      "job_number": "123",
      "name": "张三",
      "gender": "男",
      "asState": "在职",
      "company_name": "中国画学院",
      "major_name": "中国画",
      "college": "本校",
      "type": "博士导师",
      "t2Type": [‘先进工作者’],
      "get_titme": "",
      "style": {
        "fill": "#C2C8D5",
        "stroke": "#5D7092"
      },
      "size": 25
    },`

**Comment by gametheworld** [comment]
> 你的一个节点只是这样的圆形？那应该渲染不会慢的。使用了什么布局算法吗？可能是布局算法慢，用 4.x 可以用 GPU 版本的 fruchterman 和 gforce，速度会快很多。 https://g6.antv.vision/zh/docs/api/graphLayout/fruchterman/#layoutcfggpuenabled

我发现问题了，我图画出来了，但是 type: 'fruchterman', 力导图。聚类就非常慢，我聚类是用的 company_name 这个字段，如果我换成id会不会快一点？


![image](https://user-images.githubusercontent.com/6021628/102072289-a446df00-3e3c-11eb-9a9e-328de15ddc53.png)

**Comment by Yanyan-Wang** [comment]
跟用什么字段没关系，fruchterman 算法本身不快，用 GPU 版本就行

**Comment by gametheworld** [comment]
> PU 版本就



> 跟用什么字段没关系，fruchterman 算法本身不快，用 GPU 版本就行

我开了gpu的配置，但是还是卡

**Comment by linyj1996** [comment]
不展示label就会快很多，如果label开启，不管label的内容是什么，性能都会降低非常多

**Comment by gametheworld** [comment]
> 不展示label就会快很多，如果label开启，不管label的内容是什么，性能都会降低非常多

感谢老哥，你有微信吗，给你发个红包，我把label注释了就快很多了，感谢！感谢！！感谢！！！
![image](https://user-images.githubusercontent.com/6021628/102079086-ff7dcf00-3e46-11eb-969c-b4ad75c67f3e.png)

**Comment by Yanyan-Wang** [comment]
如果是第一次渲染慢可能是布局计算的问题。4.x 才支持 GPU，之前的版本开了 gphEnabled 也使用 CPU 在算的。

如果用了 GPU 还是慢，就是渲染的问题。在比较大规模的图上，每个节点上的图形尽可能少一些。

在交互上面如果比较卡，drag-canvas 和 zoom-canvas 都有策略优化，就是在交互过程中，文本等非 keyShape 会被隐藏，详见 配置项 enableOptimize  https://g6.antv.vision/zh/docs/manual/middle/states/defaultBehavior/#zoom-canvas
