### ISSUE TITLE
drag-canvas 和 zoom-canvas的enableOptimize兼容有问题，能否优化

### ISSUE THREAD

**Issue by linyj1996** [antvis/G6#2419]
当zoom-canvas时，在item还是只有keyShape的时候drag canvas，整个图将一直都只展示keyShape，反过来操作也一样
![image](https://user-images.githubusercontent.com/54074964/102160303-275d4900-3ec0-11eb-91d7-d1be0fbdc8e9.png)

![image](https://user-images.githubusercontent.com/54074964/102160376-4a87f880-3ec0-11eb-8acd-dc5cf5257ec4.png)

**Comment by Yanyan-Wang** [comment]
感谢反馈，我会跟进一下这个问题

**Comment by Yanyan-Wang** [comment]
v4.1.1 现在已经把 zoom-canvas 的 setTimeout 时间改得比较短，测试了一下应该很难很难会触发这种情况。可以试一下。如果有更好的方案也欢迎 pr 哦
