### ISSUE TITLE
Graph 和 TreeGraph 怎样动态转换？

### ISSUE THREAD

**Issue by hllinc** [antvis/G6#2422]
使用 new G6.Graph() 创建的 graph，现在想让它应用树布局，也就是 TreeGraph 中的 compactBox 等布局方式，有什么高效的方式可以实现它俩的动态转换吗？

**Comment by Yanyan-Wang** [comment]
鉴于不同的数据结构，目前没有内置的方法进行转换。目前只能自己转换一下数据，然后用不同的实例呈现

**Comment by hllinc** [comment]
> 鉴于不同的数据结构，目前没有内置的方法进行转换。目前只能自己转换一下数据，然后用不同的实例呈现

Got it.
