### ISSUE TITLE
G6决策图想要加个图例，如何设置

### ISSUE THREAD

**Issue by lukaiNB** [antvis/G6#2423]

**Comment by pomelo-nwu** [comment]
图例G6 没有提供内置的组件，但是这个可以在业务端做，根据图元素，节点和边的类型，渲染出一个legend组件，并且将颜色映射出来，也可以自定义加上 点击 highlight或者 remove 交互

**Comment by Yanyan-Wang** [comment]
参考例子：

https://g6.antv.vision/zh/examples/case/australiaFire/#index
https://g6.antv.vision/zh/examples/algorithm/algoDemos#gaddi
