### ISSUE TITLE
基本 Combo 力导向布局

### ISSUE THREAD

**Issue by gametheworld** [antvis/G6#2424]
https://g6.antv.vision/zh/examples/net/comboForce#basicComboForce

const data = {
  nodes: [
...
....
]
}
第一个问题：手动的吧nodes中的数据复制粘贴多分，页面渲染就图了；
第二个问题：之前我提过issues，统一也是600+个点，我配置了
workerEnabled: true, 会报错，

![image](https://user-images.githubusercontent.com/6021628/102196024-4c6ead80-3efa-11eb-8346-1557af65e197.png)
实际是有是个的combo
但是坐标问题都显示在一起在，下图这个大是我手动拖动出来的，大类的combo显示有问题，二级的node也显示有问题，坐标位置不是随机的、、、、脑壳疼，今天搞了一天了，是在解决不了。。。跪求
![image](https://user-images.githubusercontent.com/6021628/102196153-77f19800-3efa-11eb-8da6-5751458dece3.png)

**Comment by gametheworld** [comment]
这种子级布局为什么不能随机？
![image](https://user-images.githubusercontent.com/6021628/102204060-54cbe600-3f04-11eb-89e3-e7fcc23a80d8.png)

**Comment by baonanhai** [comment]
https://github.com/antvis/G6/issues/2567， 我也有这个问题，同时打开防止覆盖的选项会有性能问题

**Comment by Yanyan-Wang** [comment]
请尝试新版支持的 comboCombined 布局，支持配置内外不同的布局算法
demo：http://g6.antv.antgroup.com/examples/net/comboLayout/#comboCombined
文档：http://g6.antv.antgroup.com/api/graphlayout/combocombined
