### ISSUE TITLE
求助树图如何实现垂直方向的自定义子节点分布？

### ISSUE THREAD

**Issue by feng-1234567** [antvis/G6#2425]
示例中看到了脑图树支持自定义子节点分布，但只有水平方向的，如何实现垂直方向的自定义节点分布呢？

**Comment by feng-1234567** [comment]
已解决，紧凑树布局使用getSide方法自定义设置即可。
文档建议：
API教程内树图布局菜单，getSide方法仅在脑图树中列出，其他布局内未说明，建议添加

**Comment by pomelo-nwu** [comment]
@feng-1234567 欢迎提PR到文档中哈
