### ISSUE TITLE
graph.destroy memory leak

### ISSUE THREAD

**Issue by zxch3n** [antvis/G6#2427]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce

`graph.destroy()` when force layout is working will keep the `tick()` method runnning

https://github.com/antvis/G6/blob/346a80458f95ede7742d26b7e9da601f4cda16ac/src/layout/force/force.ts#L218-L229

| Environment | Info |
|---|---|
| g6 | 4.0.3 |
| System | macOS |
| Browser | Chrome |

---

**Comment by Yanyan-Wang** [comment]
Thanks, we are fixing it.

**Comment by Yanyan-Wang** [comment]
It is fixed by 4.1.1.
