### ISSUE TITLE
combo如何设置固定的大小呢!!!!!!!!!

### ISSUE THREAD

**Issue by Feboboo** [antvis/G6#2428]
combo 能设置固定的大小吗？
![image](https://user-images.githubusercontent.com/54396390/102296547-82f30980-3f88-11eb-8094-f114734c6791.png)
一行最多五个，我做根据节点数量不同 做了不同的padding。但是现在看起来还是有点问题。。。。。 能直接写死combo的大小吗

**Comment by Yanyan-Wang** [comment]
combo 的位置和大小是根据内部节点的位置和大小来决定的，目前不支持写死。有一个 hack 的方法，可以在没层的左右各加一个透明度为 0 的节点，“撑住” combo 大小。也就是这些虚拟节点的 style.opacity = 0

**Comment by ahouvideo** [comment]
> combo 能设置固定的大小吗？
> ![image](https://user-images.githubusercontent.com/54396390/102296547-82f30980-3f88-11eb-8094-f114734c6791.png)
> 一行最多五个，我做根据节点数量不同 做了不同的padding。但是现在看起来还是有点问题。。。。。 能直接写死combo的大小吗

你好，请问您现在有写 设置固定的combo大小的方法了吗

**Comment by Feboboo** [comment]
> combo 的位置和大小是根据内部节点的位置和大小来决定的，目前不支持写死。有一个 hack 的方法，可以在没层的左右各加一个透明度为 0 的节点，“撑住” combo 大小。也就是这些虚拟节点的 style.opacity = 0

这里的节点是动态渲染的。。。 你说的好像是个办法。不过我已经通过别的手段实现了需求。

**Comment by Feboboo** [comment]
> > combo 能设置固定的大小吗？
> > ![image](https://user-images.githubusercontent.com/54396390/102296547-82f30980-3f88-11eb-8094-f114734c6791.png)
> > 一行最多五个，我做根据节点数量不同 做了不同的padding。但是现在看起来还是有点问题。。。。。 能直接写死combo的大小吗
> 
> 你好，请问您现在有写 设置固定的combo大小的方法了吗

没有啊

**Comment by Feboboo** [comment]
> > combo 能设置固定的大小吗？
> > ![image](https://user-images.githubusercontent.com/54396390/102296547-82f30980-3f88-11eb-8094-f114734c6791.png)
> > 一行最多五个，我做根据节点数量不同 做了不同的padding。但是现在看起来还是有点问题。。。。。 能直接写死combo的大小吗
> 
> 你好，请问您现在有写 设置固定的combo大小的方法了吗

没有。。。。

**Comment by Yanyan-Wang** [comment]
v4.2.0 提供了固定 combo 大小的方法，可以设置 combo 的 fixSize: https://g6.antv.vision/zh/docs/manual/middle/elements/combos/defaultCombo/#combo-%E7%9A%84%E9%80%9A%E7%94%A8%E5%B1%9E%E6%80%A7
