### ISSUE TITLE
g6  以 x  y 坐标保存节点 返回以后不能正常拖拽，需要自定义布局，求解。。。

### ISSUE THREAD

**Issue by lichengzhong** [antvis/G6#2431]
g6  以 x  y 坐标保存节点 返回以后不能正常拖拽，需要自定义布局，求解。。。
另外点击两个节点，需要增加一条线，那就是改变edges的数据，这个我实现了，那选中的节点都是图片，怎么体现他是选中的状态呢？？？？

**Comment by lichengzhong** [comment]
https://gitee.com/lichengzhong/G6.git

**Comment by lichengzhong** [comment]
现在想根据节点的X坐标和y坐标进行画布的保存，可以反显，现在我没有给他layout布局，一拖拽的时候，线条会特别的长。只要给一个layout布局就可以拖拽了。这种情况下应该怎么解决呢？自定义布局吗？

**Comment by Yanyan-Wang** [comment]
麻烦给出复现在线 demo

**Comment by Yanyan-Wang** [comment]
由于图片节点没有秒变、填充色。考虑用透明度表示不同状态

**Comment by lichengzhong** [comment]
现在问题解决掉了，是因为坐标的类型写错了，非常感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yanyan Wang"<notifications@github.com&gt;; 
发送时间: 2020年12月18日(星期五) 下午3:05
收件人: "antvis/G6"<G6@noreply.github.com&gt;; 
抄送: "李诚忠"<863849467@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [antvis/G6] g6  以 x  y 坐标保存节点 返回以后不能正常拖拽，需要自定义布局，求解。。。 (#2431)





 
由于图片节点没有描边、填充色。考虑用透明度表示不同状态
