### ISSUE TITLE
在TreeGraph中动态对某个节点批量添加子节点到底用什么操作，add操作还是update操作？能不能给一个批量添加子节点节点的代码模板。

### ISSUE THREAD

**Issue by Lcjcode9413** [antvis/G6#2432]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cocky-bohr-ftokd)

### Steps to reproduce
在点击树节点的时候批量新增子节点的操作，新增子节点的数据原型是数组对象，要怎么操作。

| Environment | Info |
|---|---|
| g6 | 4.0.3 |
| System | win |
| Browser | chrome |

**Comment by Yanyan-Wang** [comment]
### updateChild(data, parentId)

更新数据，差量更新子树。data 是一个子树数据。若该子树的根节点不存在与当前树数据中，将该子树添加到 parentId 节点的子节点中。若该子树的根节点已经存在，则更新该子树数据。若希望更新或增加 parentId 节点下所有子节点，请使用 [updateChildren]()。二者区别图示如下：
<img src='https://gw.alipayobjects.com/mdn/rms_f8c6a0/afts/img/A*2_78TIFt7OoAAAAAAAAAAAAAARQnAQ' alt='img' width=400 />
<img src='https://gw.alipayobjects.com/mdn/rms_f8c6a0/afts/img/A*h2PkRKunMokAAAAAAAAAAAAAARQnAQ' alt='img' width=400 />

**参数**

| 名称   | 类型   | 是否必选 | 描述       |
| ------ | ------ | -------- | ---------- | ----------------- |
| data   | TreeData | true     | 子树的数据 |
| parentId | String | false  | 父节点 ID |

<span style="background-color: rgb(251, 233, 231); color: rgb(139, 53, 56)"><strong>⚠️ 注意:</strong></span> 当 `parentId` 参数为空时，则全量更新。

**用法**

```javascript
const data = {
  id: 'sub1',
  children: [
    {
      id: 'subTree1',
      children: [...]
    },
    {
      id: 'subTree2',
      children: [...]
    }
  ]
};

treeGraph.updateChild(data, 'root')
```


### updateChildren(data, parentId)

更新数据，差量更新子树中的所有子节点。data 是一个子树数据数组。若希望更新或增加一个 parentId 节点的子节点，请使用 [updateChild]()。二者区别图示如下：
<br />
<img src='https://gw.alipayobjects.com/mdn/rms_f8c6a0/afts/img/A*2_78TIFt7OoAAAAAAAAAAAAAARQnAQ' alt='img' width=400 />
<img src='https://gw.alipayobjects.com/mdn/rms_f8c6a0/afts/img/A*h2PkRKunMokAAAAAAAAAAAAAARQnAQ' alt='img' width=400 />

**参数**

| 名称   | 类型   | 是否必选 | 描述       |
| ------ | ------ | -------- | ---------- | ----------------- |
| data   | TreeData[] | true  | 子树的数据数组 |
| parentId | String | true  | 父节点 ID |

**用法**

```javascript
const data = [
  {
    id: 'subTree1',
    children: [...]
  },
  {
    id: 'subTree2',
    children: [...]
  }
];

treeGraph.updateChildren(data, 'root')
```

**Comment by Yanyan-Wang** [comment]
updateChild 的文档在官网 API 上有的  https://g6.antv.vision/zh/docs/api/treeMethods/#updatechilddata-parent

updateChildren 马上会更新上去

**Comment by wanghao1993** [comment]
我也是一样的问题，更新后，使用layout会立马展开 然后又自动收回去。

**Comment by dnf5320** [comment]
> 我也是一样的问题，更新后，使用layout会立马展开 然后又自动收回去，我设置了collapse为false，所以就就出现了诡异的画面，子节点的位置上空白的，但是占位了，且是展开的符号，但是没有节点。必须要再点击一次才行。

需要自己生成一个唯一 id 就可以了，不然就会出现你描述的问题。
