### ISSUE TITLE
同时使用drag-node与activate-relations时，连线的label位置错乱

### ISSUE THREAD

**Issue by fangdachn** [antvis/G6#2435]
测试地址： https://codesandbox.io/s/competent-dan-cpk9q?file=/index.js
复现步骤：拖动节点 => 点击空白外 => 标签回到之前位置
      modes: {
        default: [
          'drag-node',
          {
            type: 'activate-relations',
            trigger: 'click',
          },
        ],
      },

**Comment by gaojinwei** [comment]
目测是拖拽节点后，重置边的原始样式时，对非keyShape的位置没更新，G6/item/item  setOriginStyle

**Comment by Yanyan-Wang** [comment]
下个小版本会修复，预计两周内

**Comment by Yanyan-Wang** [comment]
4.1.0-beta.1 已解决，欢迎试用

**Comment by Yanyan-Wang** [comment]
正式版 4.1.0 已发布

**Comment by a515978292** [comment]
4.3.5版本中 这个问题又出现了
