### ISSUE TITLE
自定义文字会影响拖拽

### ISSUE THREAD

**Issue by samuelhsin** [antvis/G6#2438]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/infallible-cloud-l820l?file=/src/App.js)

### Steps to reproduce
当游标到字上，无法拖拽

| Environment | Info |
|---|---|
| g6 | 4.0.3 |
| System | - |
| Browser | - |

**Comment by Yanyan-Wang** [comment]
添加 text 图形的时候加上 `draggable: true`，和 `attrs` 平级
