### ISSUE TITLE
使用force进行布局，有时候图展示不出来，打印graph对象，里面的坐标是NAN

### ISSUE THREAD

**Issue by ychlgdr** [antvis/G6#2440]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ychlgdr/simulatorfront](https://github.com/ychlgdr/simulatorfront)

### Steps to reproduce
npm run serve  预期结果是在页面左侧有图像，但绘图失败，控制台打印了graph对象，里面的node坐标均为NAN

| Environment | Info |
|---|---|
| g6 | 4.0.3 |
| System | Windows10 1909 |
| Browser | chrome 87.0.4280.66 |

![image](https://user-images.githubusercontent.com/39005242/102582749-2fc2b780-413e-11eb-8c16-5daa048b04fd.png)

**Comment by Yanyan-Wang** [comment]
请提供一个复现在线 demo，我用你链接里的数据放在官网 demo 里没有复现

**Comment by ychlgdr** [comment]
> 请提供一个复现在线 demo，我用你链接里的数据放在官网 demo 里没有复现

抱歉，已经解决了，猜想是因为配置的过程中访问了不存在的信息导致的

**Comment by Yanyan-Wang** [comment]
好的，那 issue 我就关闭咯
