### ISSUE TITLE
combo拖拽后会导致与其他combo重叠和覆盖

### ISSUE THREAD

**Issue by ahouvideo** [antvis/G6#2445]
modes: {
    default: ['drag-combo', 'drag-canvas', 'zoom-canvas',{
        type: 'drag-node',
        // enableDelegate: true,
        onlyChangeComboSize:true,        
      },],
  },

给节点设置拖拽后，可以改变combo的大小。但是想要解决 combo和combo之间不重叠和覆盖的问题

**Comment by Yanyan-Wang** [comment]
拖拽节点 combo 大小被终端用户改变，会覆盖到其他没动的 combo 应该是正常的吧。不是很理解你的需求，提供一下最小复现 demo

**Comment by ahouvideo** [comment]
> 拖拽节点 combo 大小被终端用户改变，会覆盖到其他没动的 combo 应该是正常的吧。不是很理解你的需求，提供一下最小复现 demo

已经设置拖动combo后重新布局了，主要是不想要combo之间被覆盖。目前暂时解决，谢谢解答

**Comment by Yanyan-Wang** [comment]
好的，有好的方案也欢迎共建到 G6 中哦。那就先关闭这个 isue 了，再有问题随时开新 issue 哦
