### ISSUE TITLE
RangeError: Maximum call stack size exceeded when fitView: true in Chrome

### ISSUE THREAD

**Issue by sklinov** [antvis/G6#2447]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antv-large-number-of-nodes-xhio7?file=/src/index.js:765-778)

### Steps to reproduce
When the graph has a large number of nodes (>150000) and `fitView: true` the script crashes with an error
```
RangeError: Maximum call stack size exceeded
    at e.getCanvasBBox (https://xhio7.csb.app/node_modules/@antv/g6/dist/g6.min.js:16:179475)
    at eval (https://xhio7.csb.app/node_modules/@antv/g6/dist/g6.min.js:16:179401)
    at e.default (https://xhio7.csb.app/node_modules/@antv/g6/dist/g6.min.js:16:100517)
    at e.getCanvasBBox
    ...
```
It happens in Chrome (Firefox is ok except for numerous warnings about decreased performance).
Probably it's the same problem as described [in this issue](https://stackoverflow.com/questions/18308700/chrome-how-to-solve-maximum-call-stack-size-exceeded-errors-on-math-max-apply) and looks like it comes from the adjacent `antv` util library using `Math.max.apply(...)`.

To see the difference set `const MAX_NODES = 1000;` and it works fine and then on `const MAX_NODES = 150000;` it crashes.
Also you can set `fitView: false` to see that problem goes away.

| Environment | Info |
|---|---|
| g6 | 4.0.3 |
| System | Windows 10 |
| Browser | 87.0.4280.88 |

**Comment by Yanyan-Wang** [comment]
solved by v4.7.16. When the nodes num reaches the `optimizeThreshold` on graph instance (1000 by default), the `fitView` will fit the graph according to the positions of the 4 corner nodes instead of   `getCanvasBBox` to avoid the problem.
