### ISSUE TITLE
自定义 registerNode 这是我没想到。。。大佬我花一天时间看这个，结果。。。。

### ISSUE THREAD

**Issue by gametheworld** [antvis/G6#2450]
![image](https://user-images.githubusercontent.com/6021628/102866341-0ec9d180-4472-11eb-8e4b-8e4fb5788cfa.png)
你可能不知道我是怎么调试的。。。。。

![image](https://user-images.githubusercontent.com/6021628/102866566-6cf6b480-4472-11eb-82ba-ac7304474864.png)

所有配置相同，只是在nodes数据上不同  最后发现type是关键词。。。。
![image](https://user-images.githubusercontent.com/6021628/102866745-ba732180-4472-11eb-86d9-196bbc47b92f.png)

大佬们？？？真的是吧人搞死了，我在g6上面耗费的时间 80% 的都是猜各种属性、各种定义，各种api，开源甚忧啊。真心是项目时间周期太匆忙了，g6的文档也是着实把我坑了一把，

**Comment by Yanyan-Wang** [comment]
??
https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/defaultNode#%E8%8A%82%E7%82%B9%E7%9A%84%E9%80%9A%E7%94%A8%E5%B1%9E%E6%80%A7

文档上有写啊

**Comment by luckydogM** [comment]
成功被你逗笑了
