### ISSUE TITLE
请问节点类型为rect时，icon不显示

### ISSUE THREAD

**Issue by Kang127** [antvis/G6#2451]
根据这个示例：https://g6.antv.vision/zh/examples/item/defaultNodes#rect
需求是：在react中显示一个icon，其他的形状不适配，请问这个怎么解决？

**Comment by Yanyan-Wang** [comment]
rect 节点没有设置 icon，文档中没有提到的配置项就是没有的 https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/built-in/rect#%E9%85%8D%E7%BD%AE%E9%A1%B9%E8%AF%B4%E6%98%8E

需要一个矩形加一个图片的节点，可以继承 rect 节点并进行自定义，参考 https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/custom-node/#%E6%B7%BB%E5%8A%A0%E5%8A%A8%E7%94%BB

**Comment by Kang127** [comment]
ok,谢谢

**Comment by Kang127** [comment]
我自定义了一个节点，图片添加进去了。修改节点大小的时候，怎么更新其中的图片大小？
刚才用了afterUpdate 和update，试了好多种办法，自定义节点中的图片大小还是不能改变。
请问应该用哪个方法？ @Yanyan-Wang

**Comment by Yanyan-Wang** [comment]
复写 update: undefined。然后在 draw 方法的 addShape('image' 的时候就考虑使用 cfg 里面的字段控制大小
