### ISSUE TITLE
jsx节点refreshLayout方法耗时较长

### ISSUE THREAD

**Issue by luckydogM** [antvis/G6#2452]
新插入7个jsx自定义节点，在treegraph文件中的layout方法中断点调试 layoutmethod方法耗时100ms+，innerUpdateChild方法耗时160ms+，每个jsx节点的draw方法耗时平均14ms+，   有什么方法能优化一下性能呢

**Comment by mxz96102** [comment]
能提供一下具体结构我看一下吗，我看一下主要是生成Draw耗时还是Update失效

**Comment by luckydogM** [comment]
额，因为信息安全原因不能复制代码进来。。。，我断点主要是draw方法里的compileXML方法耗时长

**Comment by luckydogM** [comment]
我试了一下比较简单的jsx结构，只有一个group嵌套一个rect标签compilerXML方法的耗时也是在8ms+

**Comment by mxz96102** [comment]
compileXML应该是因为调用了XML编译这个过程会比较长，我看看有没有什么方法可以改进

**Comment by mxz96102** [comment]
请问一下你是在什么框架下使用G6的呢，最近会出一些针对框架的自定义解决方案不知道有没有帮助

**Comment by luckydogM** [comment]
Vue框架

**Comment by mxz96102** [comment]
接下来的版本会推出依赖vue和react的定义节点方案，写法基本不变，性能应该有提升

![image](https://user-images.githubusercontent.com/15213473/103065931-ba019480-45f2-11eb-94cd-4954ac14d89c.png)

**Comment by luckydogM** [comment]
好的，等新版本出来我再试一下

**Comment by Yanyan-Wang** [comment]
react-node 已出，欢迎试用 https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/react-node
