### ISSUE TITLE
大图批量更新元素时，如何优化耗时

### ISSUE THREAD

**Issue by zuiidea** [antvis/G6#2453]
在大图场景下，批量更新元素外观属性耗时较长，随元素量线性增长。有什么好的方式可以减少耗时。

- [Issues](https://github.com/antvis/G6/issues/1425) 中有提到设置`autoPaint`做批量更新，经测试是无效的。

```
graph.setAutoPaint(false);
```

![image](https://user-images.githubusercontent.com/16070518/102981956-b9aac000-4544-11eb-93fb-81182740eb56.png)

- 在线在线代码演示：

[![Edit update large nodes](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/update-large-nodes-gq89t?fontsize=14&hidenavigation=1&theme=dark)

**Comment by mxz96102** [comment]
可以尝试自定义节点update优化一下？
https://6h00d.csb.app/
![image](https://user-images.githubusercontent.com/15213473/103068323-e075fe80-45f7-11eb-9ede-79af94a88b45.png)

**Comment by Yanyan-Wang** [comment]
现在已经不需要用户控制 autoPaint 了。楼上方法挺好的。

还有一种极致的优化，可以个位数毫秒内更新完成：https://codesandbox.io/s/update-large-nodes-forked-p6lvk?file=/src/App.js

直接拿到 shape 去更新样式，但是这样将完全脱离 graph 的管理，可能导致如果有状态更新时行为不符合预期。如果你这里是简单的更新节点上图形的一些样式，可以考虑我刚刚这个链接的做法。

**Comment by zuiidea** [comment]
@Yanyan-Wang 👍👍  可以讲一下使用`graph.update`方法，是哪个环节导致耗时过长的吗
