### ISSUE TITLE
activate-relations问题，如果边数据带label属性，并且展示边的label值，鼠标多次在节点上悬浮移开，边上的label会消失

### ISSUE THREAD

**Issue by bt9396118** [antvis/G6#2454]
activate-relations问题，如果边数据带label属性，并且展示边的label值，鼠标多次在节点上悬浮移开，边上的label会消失。该问题出现次数不定，有时候要十几次才会出现，有时候一两次就出现，出现的次数可能跟图元的个数以及布局有关，但最终都会出现
目前测试4.0.3版本有这个问题，3.8.5未发现该问题。
使用的测试例子就是官方的”[内置的高亮节点](https://g6.antv.vision/zh/examples/interaction/highlight#activateRelations)“

我目前需要GPU以及web worker帮助渲染节点，所以使用的是4.0.3版本，但希望最新版本能尽快解决该问题，最好能有一个配置属性或者提供方法，使得高亮节点时可以控制显示还是隐藏边上的label，而不是现在这样突然的消失。

**Comment by Yanyan-Wang** [comment]
请提供最小复现 demo

**Comment by bt9396118** [comment]
最小复现demo是https://codesandbox.io/s/elated-colden-rfhwb

**Comment by gdhlaosan** [comment]
我也出现了这个问题，找了好久还以为是我代码的问题

**Comment by gdhlaosan** [comment]
希望能尽快解决，很影响用户体验

**Comment by bt9396118** [comment]
> 希望能尽快解决，很影响用户体验

我通过自定义activate-relations的afteractivaterelations事件，大概能避免这个问题，但是我还是觉得官方可以看看这个问题，我当时也是找了好久才发现4以上版本都有这个问题，而3.x没有，如果你的需求展示的节点不多，对性能要求不高，可以降到3.x使用

**Comment by gdhlaosan** [comment]
> > 希望能尽快解决，很影响用户体验
> 
> 我通过自定义activate-relations的afteractivaterelations事件，大概能避免这个问题，但是我还是觉得官方可以看看这个问题，我当时也是找了好久才发现4以上版本都有这个问题，而3.x没有，如果你的需求展示的节点不多，对性能要求不高，可以降到3.x使用

好的，感谢

**Comment by Yanyan-Wang** [comment]
v4.1.0-beta.1 已修复，欢迎试用。下周会发布正式版本

**Comment by Yanyan-Wang** [comment]
正式版 4.1.0 已发布
