### ISSUE TITLE
为什么x,y的起始点不是左上角，而是节点的中心点？

### ISSUE THREAD

**Issue by qingchiapp** [antvis/G6#2457]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://jsrun.net/ssIKp/edit](http://jsrun.net/ssIKp/edit)

### Steps to reproduce
基础demo，将x和y改成0 ，则发现node1无法完全展示

| Environment | Info |
|---|---|
| g6 | 4.0.3 |
| System | - |
| Browser | - |

**Comment by baizn** [comment]
x y 是指节点在画布上的坐标，对于 circle 来说，就是圆心的位置，(0, 0) 是画布的左上角。
要让节点展示到画布左上角，x y 需要设置为半径的值。
![image](https://user-images.githubusercontent.com/9443867/103199191-42e73b80-4925-11eb-8cb1-6e709a8d0115.png)

**Comment by qingchiapp** [comment]
> x y 是指节点在画布上的坐标，对于 circle 来说，就是圆心的位置，(0, 0) 是画布的左上角。
> 要让节点展示到画布左上角，x y 需要设置为半径的值。
> ![image](https://user-images.githubusercontent.com/9443867/103199191-42e73b80-4925-11eb-8cb1-6e709a8d0115.png)

既然在web生态，为什么不能遵循html的标准呢，让人头疼，弄个宽高算来算去的，比html麻烦多了

**Comment by Yanyan-Wang** [comment]
> > x y 是指节点在画布上的坐标，对于 circle 来说，就是圆心的位置，(0, 0) 是画布的左上角。
> > 要让节点展示到画布左上角，x y 需要设置为半径的值。
> > ![image](https://user-images.githubusercontent.com/9443867/103199191-42e73b80-4925-11eb-8cb1-6e709a8d0115.png)
> 
> 既然在web生态，为什么不能遵循html的标准呢，让人头疼，弄个宽高算来算去的，比html麻烦多了

但是这个是canvas标准呀老哥，svg也是这样的，你咋不说他们不遵循html标准

**Comment by qingchiapp** [comment]
> > > x y 是指节点在画布上的坐标，对于 circle 来说，就是圆心的位置，(0, 0) 是画布的左上角。
> > > 要让节点展示到画布左上角，x y 需要设置为半径的值。
> > > ![image](https://user-images.githubusercontent.com/9443867/103199191-42e73b80-4925-11eb-8cb1-6e709a8d0115.png)
> > 
> > 
> > 既然在web生态，为什么不能遵循html的标准呢，让人头疼，弄个宽高算来算去的，比html麻烦多了
> 
> 但是这个是canvas标准呀老哥，svg也是这样的，你咋不说他们不遵循html标准

那只能怪我无知，没用过那些东西，但真心感觉 这个标准不如html的好用，你们能不能考虑加个全局配置，自己决定是用哪套坐标标准

**Comment by Yanyan-Wang** [comment]
你想象一下图上有矩形有圆形，然后指定了同样的y坐标希望它们对齐，但是因为rect原点在左上角，圆原点在中心，就会看起来不对齐了，还要为了对齐再去调整坐标会更复杂。所以G6统一节点原点在中心。

你要是感兴趣也可以提pr

**Comment by qingchiapp** [comment]
> 你想象一下图上有矩形有圆形，然后指定了同样的y坐标希望它们对齐，但是因为rect原点在左上角，圆原点在中心，就会看起来不对齐了，还要为了对齐再去调整坐标会更复杂。所以G6统一节点原点在中心。
> 
> 你要是感兴趣也可以提pr

好吧，我可能被您说服了，我大概想了想这玩意好像和html是不太一样，html能父元素控制子元素，这玩意就是自己控制自己，谢谢耐心解答，以后关于这个问题有疑问再回复您吧，目前没有疑问了，谢谢

**Comment by cnryb** [comment]
我用的是矩形，碰到这个问题了。查了好一圈才发现不能变更坐标的定位点。

**Comment by afan0228** [comment]
怎么才能垂直居中对齐呢，textBaseline: 'middle'还是靠上
![image](https://user-images.githubusercontent.com/8581365/170748075-b1d4685d-2fbb-4773-af1c-3c73c7d93bf1.png)
