### ISSUE TITLE
需求：添加配置，自定义节点菜单模块，添加是否自动调整菜单位置

### ISSUE THREAD

**Issue by cay588** [antvis/G6#2461]
- **G6 Version**: ^4.0.3
- **Platform**: 
- **Mini Showcase(like screenshots)**:
- **CodePen Link**: [https://github.com/antvis/G6/blob/cdda02ff0d6eb042c8999d1dcbdcb21c21c7a5c4/src/plugins/menu/index.ts#L139](url)

在   // when the menu is (part of) out of the canvas
    if (x + bbox.width > width) {
      x = e.canvasX - bbox.width - offsetX + graphLeft;
    }
    if (y + bbox.height > height) {
      y = e.canvasY - bbox.height - offsetY + graphTop;
    }
的时候能否添加一个配置，是否需要自动调整位置。我不需要执行这段逻辑，这一段代码加个控制。

因为在自定义环形菜单后，由与自动调整导致菜单偏移问题，截图如下：
正常的情况：
![正常](https://user-images.githubusercontent.com/22816042/103115829-fe4a6e80-469e-11eb-809a-e99ac1fb50b5.png)
![正常](https://ftp.bmp.ovh/imgs/2020/12/090d2f66d1079166.png)
[https://ftp.bmp.ovh/imgs/2020/12/090d2f66d1079166.png](url)
周围空间足够却偏移：
![偏移](https://user-images.githubusercontent.com/22816042/103115942-7153e500-469f-11eb-8d21-932a7d109805.png)
![偏移](https://ftp.bmp.ovh/imgs/2020/12/f0ae11e812277313.jpg)
[https://ftp.bmp.ovh/imgs/2020/12/090d2f66d1079166.png](url)
（图床不得劲，一直挂。。。）

**Comment by Yanyan-Wang** [comment]
请提供最小复现在线 demo

**Comment by cay588** [comment]
换了个方法实现，已通过contextmenu 挂载自定义dom解决。
