### ISSUE TITLE
更改选中效果时，样式恢复到初始的bug

### ISSUE THREAD

**Issue by Kang127** [antvis/G6#2462]
例如，lable的字体大小初始是20px，通过graph.updateItem修改为50。
然后选中此node，再取消此node，这个时候lable的字体大小会变成初始的20px。
复现地址：https://stackblitz.com/edit/react-k87jet?file=index.js
复现代码中的第87行放开能解决，但是这样应该有问题。（点击画布取消的时候需要遍历所有的node）

**Comment by Yanyan-Wang** [comment]
v4.1.0-beta.1 已解决，欢迎试用

**Comment by Yanyan-Wang** [comment]
正式版 4.1.0 已发布
