### ISSUE TITLE
可以给graph expandCombo 和 collapseCombo 时 添加 回调事件吗   (I want add some events callback when the graph expandCombo and collapseCombo )

### ISSUE THREAD

**Issue by YealZoy** [antvis/G6#2463]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我这边想在graph expandCombo 和 collapseCombo 的时候 设置vedges的样式 (I want set the vedges style when the graph's combo expand collapse )

### What does the proposed API look like?
graph.on('beforeExpandCombo',callback(args))
graph.on('afterExpandCombo',callback(args))
graph.on('beforeCollapseCombo',callback(args))
graph.on('afterCollapseCombo',callback(args))

**Comment by Yanyan-Wang** [comment]
感谢建议，下个小版本会加上，两周内发布

**Comment by Yanyan-Wang** [comment]
4.1.1 已加上
