### ISSUE TITLE
需求：自定义菜单：能否直接appendChild(dom)，这样在自定义dom里面可以随意绑定各种事件。

### ISSUE THREAD

**Issue by cay588** [antvis/G6#2464]
[https://github.com/antvis/G6/blob/cdda02ff0d6eb042c8999d1dcbdcb21c21c7a5c4/src/plugins/menu/index.ts#L111](url)
  if (isString(menu)) {
      menuDom.innerHTML = menu;
    } else {
      menuDom.innerHTML = menu.outerHTML; // 这一行
    }
这里的代码把 dom 对象又转成HTML，再innerHTML进去，导致绑定的事件都没了。
而且现有的事件只有click，满足不了客户稀奇古怪的需求呀

**Comment by Yanyan-Wang** [comment]
那可以自己写一个 dom，graph.on('contextmenu', () => {显示自己写的 DOM})。挂载方式参考 https://g6.antv.vision/zh/docs/manual/advanced/coordinate-system

**Comment by cay588** [comment]
@Yanyan-Wang 谢谢，已通过”contextmenu“方式实现需求
