### ISSUE TITLE
"export 'IInteractorService' was not found in './services/interactor/IIteractorService'

### ISSUE THREAD

**Issue by aisujian** [antvis/G6#2465]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/antvis/G6](https://github.com/antvis/G6)

### Steps to reproduce
warning  in ./node_modules/@antv/g-webgpu-core/es/index.js

| Environment | Info |
|---|---|
| g6 | 4.0.3 |
| System | macos 11.1 |
| Browser | chrome  87.0.4280.88 |

![image](https://user-images.githubusercontent.com/33425635/103129039-49ca4000-46d2-11eb-9ac8-61d3005c4404.png)

**Comment by Yanyan-Wang** [comment]
Fixed  by 4.1.1

**Comment by cccRaim** [comment]
问题依然存在。
issue is still exist;

**Comment by Yanyan-Wang** [comment]
> 问题依然存在。
> issue is still exist;

删掉全部 node_modules 再装一下，最新 4.1.4。这个问题是 G6 依赖的 g-webgpu 的问题，如果只是更新 G6 一个包，node_modules 里面可能会有旧版本的 g-webgpu

**Comment by AlexandrShcherbakov93** [comment]
Have this issue too, right now

**Comment by dash7ou** [comment]
Have this issue too, Nowww
WTF?

**Comment by Yanyan-Wang** [comment]
fixed by v4.1.10
