### ISSUE TITLE
combo超过三级展开闭合有问题

### ISSUE THREAD

**Issue by liuliang218** [antvis/G6#2468]
默认所有combo，子combo都是闭合状态
combo超过三级，展开一级二级combo后，闭合一级combo,在展开一级combo,   里面的本来是闭合状态的子combo都自动展开了

**Comment by liuliang218** [comment]
combo超过三级  显示先后顺序会乱 本应该置后的 都跑到最前面了

**Comment by Yanyan-Wang** [comment]
请提供最小复现在线 demo

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
