### ISSUE TITLE
想请教一下，树图怎么获取节点的父节点

### ISSUE THREAD

**Issue by hxj123** [antvis/G6#2469]
看了api文档，好像没有找到对应的接口

**Comment by baizn** [comment]
node.get('parent')，你把节点打印出来就可以看得到它所有的属性，都可以通过 get('xxx') 拿到
![image](https://user-images.githubusercontent.com/9443867/103199545-0cf68700-4926-11eb-8c82-cfd97088fb90.png)

**Comment by hxj123** [comment]
> node.get('parent')，你把节点打印出来就可以看得到它所有的属性，都可以通过 get('xxx') 拿到
> ![image](https://user-images.githubusercontent.com/9443867/103199545-0cf68700-4926-11eb-8c82-cfd97088fb90.png)

感谢～
