### ISSUE TITLE
用什么方法可以获取到Combo内的边edges

### ISSUE THREAD

**Issue by yuNewStudent** [antvis/G6#2470]
用什么方法可以获取到Combo内的边edges
![1609125450(1)](https://user-images.githubusercontent.com/39002248/103187159-4b784b80-48fe-11eb-8bff-92d9e3e45423.jpg)

**Comment by baizn** [comment]
没有直接获取的方法，可以先通过 combo.getNodes() 拿到节点点，再通过节点的 getSource 和 getTarget 方法获取边
