### ISSUE TITLE
内建 dagre 布局不支持自定义位置

### ISSUE THREAD

**Issue by samuelhsin** [antvis/G6#2471]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/serene-waterfall-ti8ij?file=/src/App.js)

### Steps to reproduce
内建 dagre 部局不支持自定义位置

| Environment | Info |
|---|---|
| g6 | 4.0.3 |
| System | - |
| Browser | - |

**Comment by Yanyan-Wang** [comment]
什么意思？如果你需要使用数据中的 x y，不指定 layout 即可

**Comment by samuelhsin** [comment]
那為什麼內建力導圖就可以指定自定義的位置

https://g6.antv.vision/zh/docs/manual/middle/layout/graph-layout/#force

当实例化图时没有配置布局时：

若数据中节点有位置信息（x 和 y），则按照数据的位置信息进行绘制；
若数据中节点没有位置信息，则默认使用 Random Layout 进行布局。

**Comment by samuelhsin** [comment]
那想问一下，如果我的图操作步骤是：
1. 一开始资料要按图节点的位置去排列
2. 透过 updateLayout 方法经过 dagre 布局 format 
3. 透过 changeData 更新资料 => 此时需要根据图节点的位置去排列

请问有办法在updateLayout完后，清空 instance 里的设定的 layout 设定吗，让它变回可以依图节点位置排列

**Comment by Yanyan-Wang** [comment]
我理解你的意思是，先布局一次，然后更新数据的时候，保持上一次的布局结果，不要重新布局是吗？graph.destroyLayout 在 changeData 之前调用可以销毁布局 https://g6.antv.vision/zh/docs/api/graphFunc/layout/#destroylayout

**Comment by samuelhsin** [comment]
好的，这个方式我理解了
那再问一下为什么我使用了 updateLayout 后，render 方法仍然是使用最初的 layout 设定？

**Comment by samuelhsin** [comment]
@Yanyan-Wang 再请问一下 read 方法跟 changeData 方法有什么不一样？

**Comment by Yanyan-Wang** [comment]
>  read 方法跟 changeData 方法有什么不一样？

read 是读取数据和渲染使用，全量完全重新读入所有的数据。changeData 是更换数据，会做 diff，增量地去改变节点/边。

> 为什么我使用了 updateLayout 后，render 方法仍然是使用最初的 layout 设定？

这个应该是 G6 在 updateLayout 的时候，没有把新的配置项做好更新，后面会修复一下
