### ISSUE TITLE
在第二次render后将无法进行执行createHull

### ISSUE THREAD

**Issue by linyj1996** [antvis/G6#2472]
节点集轮廓渲染完成后，再执行一次graph.render()，轮廓消失，这时想要重新执行graph.createHull渲染新的轮廓，直接报错，this.getCanvas()和this.getChildren()这些都是undefined，求解
![image](https://user-images.githubusercontent.com/54074964/103188594-06571800-4904-11eb-9e50-5b5b8bf3c7c7.png)
![image](https://user-images.githubusercontent.com/54074964/103188613-2090f600-4904-11eb-8b84-8abc3fa9af28.png)

**Comment by Yanyan-Wang** [comment]
为什么要第二次调用 graph.render()？请提供最小复现的在线 demo

**Comment by linyj1996** [comment]
https://codesandbox.io/s/vibrant-haze-rmyzr?file=/index.js

**Comment by linyj1996** [comment]
重新render是因为在一些场景下下需要重新渲染新的数据，当第二次render时，hullGroup被destroy掉，但graph.get('hullGroup')还是能拿到这个被destroy的group,只是他无法addGroup了

**Comment by Yanyan-Wang** [comment]
这种情况下请使用  graph.changeData()。不过现在 changeData 没有清空之前的 hulls，可以手动先清空一下 graph.removeHull(hullId)，下个版本在 changeData 的时候清空所有 hulls

另外，id 一定要是 string 哦
