### ISSUE TITLE
4.03 dagre布局调用layou后，边的路径

### ISSUE THREAD

**Issue by rojiny** [antvis/G6#2473]
![正常](https://user-images.githubusercontent.com/16874378/103202711-24397280-492e-11eb-9224-9b9fae415357.png)
![错误](https://user-images.githubusercontent.com/16874378/103202718-28659000-492e-11eb-8746-a19f1aaa3ca5.png)
图1为没调用layout方法前呈现的图，图2为调用layout方向后呈现的图。
其中“财务审批”到“部门审批”的边指定了sourceAnchor与targetAnchor,其它边都没指定anchor,边的类型为polyline。
希望调用layout后“财务审批”到“部门审批”的边按图1的路径呈现

版本：4.03
浏览器版本：chrome 87.0.4280.88

**Comment by Yanyan-Wang** [comment]
把 dagre layout 的 controlPoints 设置为 false
