### ISSUE TITLE
render 方法无视 updateLayout 后的结果，仍然使用初始化的 layout 设定

### ISSUE THREAD

**Issue by samuelhsin** [antvis/G6#2476]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jovial-sid-mzn7o?file=/src/App.js:3588-3604)

### Steps to reproduce
render 方法无视 updateLayout 后的结果，仍然使用初始化的 layout 设定
改变 LR 部局 再重载资料

| Environment | Info |
|---|---|
| g6 | 4.0.3 |
| System | - |
| Browser | - |

**Comment by Yanyan-Wang** [comment]
使用 changeData 更换数据
