### ISSUE TITLE
G6自定义节点中不支持symbol格式的svg？

### ISSUE THREAD

**Issue by lixianyu-icon** [antvis/G6#2477]
`<svg class="icon svg-icon" aria-hidden="true" width="16" height="16">
     <use :xlink:href="'#'+ o.icon"></use>
</svg>  `
在自定义节点类型时使用上面所述的这种方式定义icon好像不起作用，请问是不支持吗？

**Comment by Yanyan-Wang** [comment]
自定义 html 节点吗？请提供最小复现的在线 demo

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
