### ISSUE TITLE
节点的x和y在compactBox布局，里面x和y是不准确的

### ISSUE THREAD

**Issue by stewingeded** [antvis/G6#2479]
https://user-images.githubusercontent.com/47906505/103255962-59919f00-49c6-11eb-957a-a9a3b429efe9.MP4

- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://jsrun.net/rFIKp/edit](http://jsrun.net/rFIKp/edit)

### Steps to reproduce
注销draw函数里面的 x和y值 画出的图是紧凑的，但是 如果加上x，y值 画出的图是四散的，console一下节点的x，y ，和画出的xy 在紧凑的案例里面 x和y是经过了加工，是不准确的。

| Environment | Info |
|---|---|
| g6 | 4.0.3 |
| System | mac |
| Browser | chrome |

**Comment by Yanyan-Wang** [comment]
1. 节点位置是由节点的图形分组的矩阵控制的，draw 方法中打印 group.getMatrix()，数组中的 [6] 和 [7] 就是节点的 x y，这样是为了总体控制节点位置。

2. 节点内部图形的位置根据节点自身的坐标系定位，自定义节点的时候，addShape 增加图形时的 x y 只需要考虑相对于自身坐标系  [0, 0] 坐标。比如说一个 circle，它的 x y 是它的圆形位置，只需要指定为 x:0, y:0

3. 与 circle 不同，rect 图形的 x y 是指它的左上角，所以 addShape 增加 rect 图形时，x y 应各减去其宽高的一半，如 x: -width / 2, y: -height / 2

4. 布局的紧凑程度应根据布局的参数来调整，https://g6.antv.vision/zh/docs/api/treeGraphLayout/compactBox

**Comment by stewingeded** [comment]
> 1. 节点位置是由节点的图形分组的矩阵控制的，draw 方法中打印 group.getMatrix()，数组中的 [6] 和 [7] 就是节点的 x y，这样是为了总体控制节点位置。
> 2. 节点内部图形的位置根据节点自身的坐标系定位，自定义节点的时候，addShape 增加图形时的 x y 只需要考虑相对于自身坐标系  [0, 0] 坐标。比如说一个 circle，它的 x y 是它的圆形位置，只需要指定为 x:0, y:0
> 3. 与 circle 不同，rect 图形的 x y 是指它的左上角，所以 addShape 增加 rect 图形时，x y 应各减去其宽高的一半，如 x: -width / 2, y: -height / 2
> 4. 布局的紧凑程度应根据布局的参数来调整，https://g6.antv.vision/zh/docs/api/treeGraphLayout/compactBox

CompactBox布局可以自己修改节点的x，y吗  ，比如 拦截excute执行后的数据，afterExcute，把自己的坐标x，y放进去。我描述一下场景，最近的项目是创建了一个CompactBox布局的树，每个节点是一个一些卡片信息，但是有链性关系。随着深入的链性，导致图越来越大，用户想要自己可以拖动后，拖出自己想要的x，y。然后保存。下次渲染就是他的样式。我想的是两个方案，1，通过改变CompactBox的x，y实现画图（这个没有相关api）  2，第二次渲染可以通过自定义布局来做，但是自定义布局 ，没有CompactBox布局这种树的例子，然后可以看我另一个问题。https://github.com/antvis/G6/issues/2489。谢谢

**Comment by Yanyan-Wang** [comment]
graph.updateItem(graph.getNodes()[0], {
    x: 100,
    y: 100
  })
如果有动画，要在 graph.on('afteranimate', () => {}) 中更新

**Comment by stewingeded** [comment]
> graph.updateItem(graph.getNodes()[0], {
> x: 100,
> y: 100
> })
> 如果有动画，要在 graph.on('afteranimate', () => {}) 中更新

谢谢，已经解决，加载完毕后，锁定不让他展开合并，或者删除节点等一系列导致触发重新计算的x，y的操作，我们手动的改变了x，y。通过updateItem
