### ISSUE TITLE
G6层级树在vue中使用，无法使用鼠标滚轮缩放

### ISSUE THREAD

**Issue by Comlet** [antvis/g6#248]
在使用G6分层树的时候，复制它的demo代码到我的代码里，出现一个问题，就是在它html文档上能够实现鼠标滚轮放大缩小，但是到vue中的时候，鼠标滚轮没有用，哪里出了问题呢？

**Comment by TomHuangCN** [comment]
应该可以把，G6 是基于原生 JS 写的，不依赖任何第三方 UI 框架
