### ISSUE TITLE
TreeGraph修改连接线样式

### ISSUE THREAD

**Issue by Youmyin** [antvis/G6#2482]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
辐射型布局无法控制方向，因此只能选择方向可控的树图布局，但是TreeGraph类型，其data格式不包含对edge的描述，无法使用source或者Target来修改两点间连接线的样式，所以希望TreeGraph能够修改edge的样式

### What does the proposed API look like?
希望TreeGraph的辐射树能拥有一般Graph的配置边的功能

**Comment by babyyage** [comment]
did you solve this problem?

**Comment by CahierX** [comment]
可以通过进行自定义
```
graph.edge((edge) => {
  return {
    id: edge.id,
    source:'xxx,
    target:'xxxx',
    type: 'polyline',
    style: {
      fill: 'steelblue',
    },
  };
});

```
