### ISSUE TITLE
辐射型布局如何控制辐射方向和辐射角度

### ISSUE THREAD

**Issue by Youmyin** [antvis/G6#2484]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当树结构变成辐射树的时候，需要将direction改为RL，最终的辐射树每一层总是会辐射成一个圈，即使是在数据很少的情况下，比如第二层只有4个节点，但是任然会呈一个圈状辐射出去，这样就浪费了页面布局，会显得很空旷。如果使用普通的radial布局，辐射方向是随意的，当我想要从顶至下，范围为0-180°的一个半圆形布局时无法实现

### What does the proposed API look like?
给radial的layout增加两个属性
（1）direction----方向
         类似树图的几个方向的定义，比如从上至下辐射，从左至右辐射等
（2）angle-----角度
         把辐射限定在一个范围内，参数类型为Array,包括开始角度和结束角度，如果范围较小而数据过多会发生重叠，可以nodeSize进行碰撞检测失效，提供此辐射方向下比较合适的辐射角度

**Comment by Yanyan-Wang** [comment]
感谢意见，由于该 feature 需求量不大，暂时没有考虑进行排期支持。所以欢迎社区共建。

**Comment by Youmyin** [comment]
那请问有没有什么办法介意可以优化辐射型布局呢？

我需要将布局变成这样
[cid:image002.png@01D6DEA1.EB8D8670]

但是直接使用辐射型布局变成了这样
[cid:image005.png@01D6DEA1.EB8D8670]

如何调整参数或者其他什么配置可以达到图一的效果呢？辐射树试过了，但是辐射树也是环状的不能呈半圆形，而辐射型布局无法从上至下布局

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Yanyan Wang<mailto:notifications@github.com>
发送时间: 2020年12月30日 11:41
收件人: antvis/G6<mailto:G6@noreply.github.com>
抄送: Youmyin<mailto:RiyouGer@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [antvis/G6] 辐射型布局如何控制辐射方向和辐射角度 (#2484)


感谢意见，由于该 feature 需求量不大，暂时没有考虑进行排期支持。所以欢迎社区共建。

―
