### ISSUE TITLE
树图收起状态丢失

### ISSUE THREAD

**Issue by hxj123** [antvis/G6#2485]
官网例子：https://g6.antv.vision/zh/examples/tree/indented#intendAlignTop

1. 如下图，当子节点有收起状态
![image](https://user-images.githubusercontent.com/28498564/103272637-5ca58300-49f8-11eb-81e7-6a628addaa3e.png)

2.父节点收起再展开
![image](https://user-images.githubusercontent.com/28498564/103272824-c3c33780-49f8-11eb-8590-afc153008ca8.png)

3.子节点的收起/展开按钮状态丢失
![image](https://user-images.githubusercontent.com/28498564/103272744-95ddf300-49f8-11eb-89fb-ffde891c8fdf.png)

这里应该怎么保留子节点收起/展开状态？

**Comment by xuanaxuan** [comment]
有个afterlayout方法

**Comment by Yanyan-Wang** [comment]
这个 demo 已经修复正确
