### ISSUE TITLE
自定义布局 如果数据传的是普通布局的可以打印出来数据，如果，传的是tree类型数据，就打印不出来数据

### ISSUE THREAD

**Issue by stewingeded** [antvis/G6#2489]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://jsrun.net/65IKp/edit](http://jsrun.net/65IKp/edit)

### Steps to reproduce
graph.data(data1) 可以有数据，graph.data(data2) 没有数据，看console

| Environment | Info |
|---|---|
| g6 | 4.0.3 |
| System | mac |
| Browser | chrome |

**Comment by Yanyan-Wang** [comment]
在你 demo 连接中没看到 data1 data2，怎么打印的数据

**Comment by stewingeded** [comment]
> 在你 demo 链接中没看到 data1 data2，怎么打印的数据
http://jsrun.net/65IKp/edit  以前编辑的没保存，自定义布局的时候 ，当tree数据源，G6.registerLayout('bigraph-layout', {
  execute() {
    const self = this;
    console.log(JSON.stringify(self))
    
  },
});
console不到node的数据。

**Comment by Yanyan-Wang** [comment]
data2 的数据结构是树呀，跟 data1 不一样。。G6.Graph 不会处理 data2 这种树数据的。要展示树图用 G6.TreeGraph，但 TreeGraph 暂不支持自定义布局
