### ISSUE TITLE
contextMenu右键点击出现菜单时，菜单不在当前点击节点下方，出现错位

### ISSUE THREAD

**Issue by zwygithub** [antvis/G6#2491]

**Comment by Yanyan-Wang** [comment]
请提供最先复现的在线 demo

**Comment by zwygithub** [comment]
G6.registerNode(
        'tree-node',
        {
          drawShape: function drawShape(cfg, group) {
            const rect = group.addShape('rect', {
              attrs: {
                fill: '#D44545'
              },
              name: 'rect-shape'
            })
            if (cfg.position === 'center') {
            
              var content = cfg.name.replace(/(.{19})/g, '$1\n')
              const text = group.addShape('text', {
                attrs: {
                  text: content,
                  x: 0,
                  y: 0,
                  textAlign: 'left',
                  textBaseline: 'middle',
                  fontSize: 14,
                  fill: '#fff'
                },
                name: 'rect-shape'
              })
              const bbox = text.getBBox()
              rect.attr({
                radius: 4,
                fill: '#D44545',
                x: bbox.minX - 10,
                y: bbox.minY - 10,
                width: bbox.width + 20,
                height: bbox.height + 20
              })
              return rect
            } else {
              const circle = group.addShape('circle', {
                attrs: {
                  fill: '#fff',
                  size: 30
                },
                size: 30,
                name: 'rect-shape'
              })
              var content2
              if (cfg.name) {
                content2 = cfg.name.replace(/(.{19})/g, '$1\n')
              } else if (cfg.relatedProduct) {
                content2 = cfg.relatedProduct.replace(/(.{19})/g, '$1\n')
              }
              const text = group.addShape('text', {
                attrs: {
                  text: content2,
                  x: 0,
                  y: 0,
                  textAlign: 'left',
                  fontSize: 14,
                  textBaseline: 'middle',
                  fill: '#fff'
                },
                name: 'rect-shape'
              })
              const bbox = text.getBBox()
              text.attr({
                x: bbox.minX + 10,
                y: bbox.minY - 6,
                width: bbox.width,
                height: bbox.height + 12
              })
              if (!cfg.children) {
                if (cfg.position === 'left') {
                  text.attr({
                    x: bbox.maxX - bbox.width - 10,
                    y: bbox.minY - 6,
                    width: bbox.width,
                    height: bbox.height + 12
                  })
                  circle.attr({
                    x: bbox.maxX,
                    y: bbox.minY - 8,
                    r: 10,
                    fill: '#fff'
                  })
                  if (cfg.countUp) {
                    var number = group.addShape('text', {
                      attrs: {
                        text: cfg.countUp,
                        x: bbox.maxX,
                        y: 0,
                        textAlign: 'center',
                        fontSize: 14,
                        textBaseline: 'middle',
                        fill: '#1581B7'
                      },
                      name: 'rect-shape'
                    })
                    number.attr({
                      x: bbox.maxX,
                      y: bbox.minY - 6,
                      width: bbox.width - 5,
                      height: bbox.height + 12
                    })
                  }
                } else {
                  text.attr({
                    x: bbox.minX + 10,
                    y: bbox.minY - 8,
                    width: bbox.width,
                    height: bbox.height + 12
                  })
                  circle.attr({
                    x: bbox.minX,
                    y: bbox.minY - 8,
                    r: 10,
                    fill: '#fff'
                  })
                  if (cfg.countUp) {
                    number = group.addShape('text', {
                      attrs: {
                        text: cfg.countUp,
                        x: -2,
                        y: 0,
                        fontSize: 14,
                        textAlign: 'center',
                        textBaseline: 'middle',
                        fill: '#1581B7'
                      },
                      name: 'rect-shape'
                    })
                    number.attr({
                      x: bbox.minX,
                      y: bbox.minY - 6,
                      width: bbox.width - 5,
                      height: bbox.height + 12
                    })
                  }
                }
              }
              if (cfg.name) {
                return text
              } else if (cfg.relatedProduct) {
                rect.attr({
                  radius: 4,
                  fill: '#1581B7',
                  x: bbox.minX - 15,
                  y: bbox.minY - 25,
                  width: bbox.width + 30,
                  height: bbox.height + 20
                })
                return rect
              }
            }
          }
        },
        'single-node'
      )
const contextMenu = new G6.Menu({
        getContent(graph) {
          return `<ul>
            <li id='menu4'>产品详情</li>
          </ul>`
        },
        handleMenuClick: (target, item) => {
          if (target.id === 'menu4') {
          }
        },
        offsetX: 26,
        // 需要加上父级容器的 padding-top 24 、画布兄弟元素高度、与自身偏移量 10
        offsetY: 10,
        // the types of items that allow the menu show up
        // 在哪些类型的元素上响应
        itemTypes: ['node', 'canvas']
      })

var graph = new G6.TreeGraph({
        container: box,
        // width,
        // height,
        modes: {
          default: [
            'drag-canvas',
            'zoom-canvas'
          ]
        },
        defaultNode: {
          size: 40,
          type: 'tree-node',
          anchorPoints: [
            [0, 0.5],
            [1, 0.5]
          ]
        },
        defaultEdge: {
          type: 'cubic-horizontal'
        },
        plugins: [], // contextMenu
        layout: {
          type: 'mindmap',
          direction: 'H',
          linkDistance: 100,
          preventOverlap: true, // 设置防止重叠
          getHeight: () => {
            return 16
          },
          getWidth: () => {
            return 60
          },
          getVGap: () => {
            return 12
          },
          getHGap: () => {
            return 60
          },
          getSide: (d) => {
            if (d.data.position === 'left') {
              return 'left'
            }
            return 'right'
          }
        }
      })
      this.graph = graph


this.data = {
            name: 'xin',
            code: '1',
            position: 'center',
            children: [
              {
                'children': [
                  {
                    'id': '3',
                    'primaryCode': 'SS',
                    'relatedCode': 'PS',
                    'relatedProduct': '合作',
                    'importance': 3,
                    'countUp': 0,
                    'countDown': 1,
                    'position': 'left'
                  }
                ],
                'name': '主体',
                'position': 'left'
              },
              {
                'children': [
                  {
                    'id': '2',
                    'primaryCode': 'Ssss',
                    'relatedCode': 'PS11',
                    'relatedProduct': '互联网',
                    'importance': 4,
                    'countUp': 4,
                    'countDown': 0,
                    'position': 'right'
                  }
                ],
                'name': '技术服务',
                'position': 'right'
              }
            ]
          }

**Comment by Yanyan-Wang** [comment]
给出在线的 demo，不要这样贴代码，效率很低的

**Comment by aMiing** [comment]
好像绝对定位下，设置了容器的top>0/margin-top/padding-top之后，就会出现错位现象？menu位置计算是不是没有考虑这个问题啊


我还有个menu溢出的问题
