### ISSUE TITLE
当label在节点上方的时候，label会有残影

### ISSUE THREAD

**Issue by lmsccc** [antvis/G6#2492]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/LH_CHEN/pen/MWjQaKQ](https://codepen.io/LH_CHEN/pen/MWjQaKQ)

### Steps to reproduce
拖动label在节点上方的节点，会出现残影

| Environment | Info |
|---|---|
| g6 | 4.0.3 |
| System | windows10 |
| Browser | chrome 72 |

**Comment by lmsccc** [comment]
这个demo是来自于https://github.com/antvis/G6/issues/1519#issuecomment-645116958，更换了G6版本问题依然存在

**Comment by lmsccc** [comment]
只有中文label会有这样的问题

**Comment by lmsccc** [comment]
实际项目使用3.7.0版本也是有这个问题

**Comment by Yanyan-Wang** [comment]
用和容器一样的字体应该就可以

fontFamily:
              typeof window !== 'undefined'
                ? window.getComputedStyle(document.body, null).getPropertyValue('font-family') ||
                  'Arial, sans-serif'
                : 'Arial, sans-serif',

**Comment by lmsccc** [comment]
>

> 
> 
> 用和容器一样的字体应该就可以
> 
> fontFamily:
> typeof window !== 'undefined'
> ? window.getComputedStyle(document.body, null).getPropertyValue('font-family') ||
> 'Arial, sans-serif'
> : 'Arial, sans-serif',

无论是您的代码还是强制指定字体，都不能解决
![企业微信截图_20210114175202](https://user-images.githubusercontent.com/25736473/104574650-3edf4b80-5691-11eb-9698-384f0c761df3.png)

**Comment by Yanyan-Wang** [comment]
似乎和特定的显示器和浏览器也有关系。还是不行的话，只能关闭局部渲染：
graph.get('canvas').set('localRefresh', false)

**Comment by edgexie** [comment]
在最新版的火狐 86.0.1 上， 我也遇到同样的问题，我的需求是鼠标选中node，label变粗。然后拖动节点会留影。
![image](https://user-images.githubusercontent.com/18474752/112593601-b0323c00-8e42-11eb-978b-885faf71df59.png)

**Comment by lmsccc** [comment]
> 
> 
> 在最新版的火狐 86.0.1 上， 我也遇到同样的问题，我的需求是鼠标选中node，label变粗。然后拖动节点会留影。
> ![image](https://user-images.githubusercontent.com/18474752/112593601-b0323c00-8e42-11eb-978b-885faf71df59.png)

你可以试一下在label背后加一个白色的Rect包住他，这样似乎可以增大局部刷新的面积

**Comment by edgexie** [comment]
> 似乎和特定的显示器和浏览器也有关系。还是不行的话，只能关闭局部渲染：
> graph.get('canvas').set('localRefresh', false)

这一招管用，但点多了 会不会性能问题。

**Comment by Yanyan-Wang** [comment]
关闭局部渲染会影响性能，这个问题底层渲染引擎正在修复。临时的解决方案就是先关闭局部渲染

**Comment by Yanyan-Wang** [comment]
遇到以上问题，尝试几个解决方案：
1. 检查节点中的图形，包括文本图形，样式配置中是否存在非法值，例如 null NaN 等；
2. 尽量使用整数座位数值型的样式值，例如 r width height fontSize 等
3. 使用浏览器字体作为 labelCfg.style.fontFamily
4. 给文本增加白色描边，如
labelCfg: {
  style: {
    stroke: '#fff',
    lineWidth: 4
  }
}

5. 以上方法都不奏效，关闭局部渲染 graph.get('canvas').set('localRefresh', false);  这个方法可能导致性能有所降低
