### ISSUE TITLE
new G6.TreeGraph的时候怎么在G6.registerEdge里获取G6.registerNode事件里cfg也就是当前树形结构的数据

### ISSUE THREAD

**Issue by HaHaaaaaaaaaa** [antvis/G6#2493]
自定义边的时候，我需要给边的label加上树形结构里的一个字段，但是G6.registerEdge里的方法我试了几个都拿不到，请问怎么能获取到对应的树形结构数据呢？现在我用this.graph.edge给边加上对应字段的话，需要递归树结构获取对应ID拿到对应字段，性能消耗太大。

**Comment by Yanyan-Wang** [comment]
是需要拿到节点数据？treeGraph.findDataById: https://g6.antv.vision/zh/docs/api/treeMethods#finddatabyidid-target
更新边的 label：graph.updateItem(edge, {label: 'new label'});

**Comment by HaHaaaaaaaaaa** [comment]
> 是需要拿到异步数据？treeGraph.findDataById：[https](https://g6.antv.vision/zh/docs/api/treeMethods#finddatabyidid-target)
> ://g6.antv.vision/zh/docs/api/treeMethods#finddatabyidid-target更新边的标签：graph.updateItem（边缘，{标签：“新标签” }）;
能在自定义边的时候就获取到对应数据吗？G6.registerEdge的时候 这时还没创建treeGraph的实例

**Comment by Yanyan-Wang** [comment]
原始需求是什么，需要拿到树数据做什么呢

**Comment by HaHaaaaaaaaaa** [comment]
公司下有子公司，需求要在边上加上公司对该子公司的占股百分比，需要从树数据里拿到占股百分比信息

**Comment by HaHaaaaaaaaaa** [comment]
> 原始需求是什么，需要拿到树数据做什么呢

公司下有子公司，需求要在边上加上公司对该子公司的占股百分比，需要从树数据里拿到占股百分比信息

**Comment by Yanyan-Wang** [comment]
可以通过渲染完成之后，计算好每个边需要的值，然后通过 graph.updateItem 来更新到自定义边上。当然，自定义边上要有相对应的处理逻辑
