### ISSUE TITLE
如何让边的层级高于节点的层级呢？当设置groupByTypes: false后，在mouseup事件中返回的参数event中的item属性就一直是edge，而不是node节点。所以想问一下还有其他方法嘛？

### ISSUE THREAD

**Issue by yumenglong** [antvis/G6#2494]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
边的层级高于节点的层级

### What does the proposed API look like?
希望api中有属性可以设置node和edge的层级的设置

**Comment by zuiidea** [comment]
- [节点与边的层级](https://g6.antv.vision/zh/docs/manual/middle/elements/methods/elementIndex/#step-2-%E5%B0%86%E8%8A%82%E7%82%B9%E6%94%BE%E7%BD%AE%E5%9C%A8%E8%BE%B9%E4%B8%8A%E5%B1%82
)

```
edge.toFront();
```

**Comment by yumenglong** [comment]
用edge.toFront();前提不是得把groupByTypes设置成false嘛？能不能在渲染边，节点的时候设置层级呢

**Comment by yumenglong** [comment]
1、把groupByTypes设置成false，然后再使用edge.toFront(); 确实可以提高edge的层级，但是这样会导致添加边到节点上失败。
例如：这个例子中，groupByTypes设置成false后，边就连不上node上了：
https://codepen.io/yumenglong/pen/qBaxVed

**Comment by Yanyan-Wang** [comment]
> 1、把groupByTypes设置成false，然后再使用edge.toFront(); 确实可以提高edge的层级，但是这样会导致添加边到节点上失败。
> 例如：这个例子中，groupByTypes设置成false后，边就连不上node上了：
> https://codepen.io/yumenglong/pen/qBaxVed

用新版本的 create-edge behavior 就可以了 https://g6.antv.vision/zh/examples/interaction/createEdge#click
