### ISSUE TITLE
如何将自定义的shape的事件挂载到graph上

### ISSUE THREAD

**Issue by linyj1996** [antvis/G6#2496]
demo: https://codesandbox.io/s/vibrant-haze-rmyzr?file=/index.js

**Comment by Yanyan-Wang** [comment]
什么自定义事件？怎么自定义事件的呢？ demo 中没看出来

**Comment by linyj1996** [comment]
之前的demo不小心改到了，新的demo:https://codesandbox.io/s/vibrant-haze-rmyzr?file=/index.js

**Comment by Yanyan-Wang** [comment]
只有在节点/边/combo 这样的图元素上的图形可以被 graph.on('shapename:eventname', e ={}) 监听到， https://codesandbox.io/s/throbbing-rain-q2kii?file=/index.js:727-743

你这里的 path-shape:click 相当于直接绘制到 canvas 上的图形，graph 监听不会管理到它们

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
