### ISSUE TITLE
监听节点移动的时候，能不能重新渲染已经生成边的path吗？（边是g6内置的cubic-vertical）

### ISSUE THREAD

**Issue by yumenglong** [antvis/G6#2501]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决已生成边的弯曲度（path）

### What does the proposed API look like?
no

**Comment by Yanyan-Wang** [comment]
不是非常理解，应该可以通过更新边的参数来控制弯曲程度 https://g6.antv.vision/zh/docs/manual/middle/elements/edges/built-in/cubic#%E9%85%8D%E7%BD%AE%E9%A1%B9%E8%AF%B4%E6%98%8E

还是有问题的话，请给出最小复现的在线 demo

**Comment by yumenglong** [comment]
1、动态更新curveOffset属性值的话，如何根据两个节点的位置，计算该属性的值呢？例如 ：下图两个节点的位置是这样：
![image](https://user-images.githubusercontent.com/17467365/103396592-19215500-4b6f-11eb-8967-1d04e4495962.png)
2、而我现在是在生成边的时候已经把curveOffset属性设置了，就成这样了，我想实现上图的那种效果：
![image](https://user-images.githubusercontent.com/17467365/103396676-7ddcaf80-4b6f-11eb-86a1-d36f5932cff6.png)

**Comment by Yanyan-Wang** [comment]
我理解你这里不是要改变边的形状，而是要更新边的 sourceAnchor，endAnchor。在节点拖拽结束之后，计算一下两个节点离得最近的两个 anchorPoint 作为边的 sourceAnchor 和 endAnchor

**Comment by Yanyan-Wang** [comment]
你想实现的是带红框的效果还是带网格背景的效果。带红框的效果就是我上面说的更新 anchor，详见 https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/anchorpoint/#gatsby-focus-wrapper

**Comment by yumenglong** [comment]
> 你想实现的是带红框的效果还是带网格背景的效果。带红框的效果就是我上面说的更新 anchor，详见 https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/anchorpoint/#gatsby-focus-wrapper

你好， 我想实现的是带网格的效果，红框的效果是我目前已经实现的，不是很满意，边和箭头的交接处不是很满意。

**Comment by yumenglong** [comment]
1、拖拽节点的时候，边和箭头好像脱离了感觉，如下图：
![image](https://user-images.githubusercontent.com/17467365/104294477-2e489d00-54fa-11eb-8b4b-8a329006fb4f.png)
https://codepen.io/yumenglong/pen/gOwBaYG?editors=0010
2、我想实现这种边的效果，就是怎么拖动节点的时候，边和箭头不要分离。
https://x6.antv.vision/zh/examples/showcase/practices#algo-flow
3、我看了两者渲染方式不同，所以我想问问，G6的边能实现像2实例中的样子吗？

**Comment by Yanyan-Wang** [comment]
用 cubic 而不是 cubic-vertical， 就可以通过更改边的 curveOffset 和 curvePosition 来改变边的弯曲程度和弯曲位置。配置项说明见 https://g6.antv.vision/zh/docs/manual/middle/elements/edges/built-in/cubic#%E9%85%8D%E7%BD%AE%E9%A1%B9%E8%AF%B4%E6%98%8E

**Comment by yumenglong** [comment]
curveOffset 我怎么设置这个值，弯曲程度好像都没有发生很大变化呢？curveOffset设的值可以举个例子吗？
![image](https://user-images.githubusercontent.com/17467365/104552738-4c3a0d00-5674-11eb-8b6a-3eede441efea.png)
例如下方这个效果：
![image](https://user-images.githubusercontent.com/17467365/104552905-a2a74b80-5674-11eb-8c23-47af1101fe00.png)

**Comment by Yanyan-Wang** [comment]
用 cubic 而不是 cubic-vertical 才能设置 curveOffset，方向相反可以用负值

**Comment by yumenglong** [comment]
我改了  我用的就是cubic， 但是curveOffset设置之后，效果不明显呢

**Comment by Yanyan-Wang** [comment]
有变化但是不明显是吗？调整幅度大一些呢，比如 100 200

**Comment by yumenglong** [comment]
调大也不明显。
![image](https://user-images.githubusercontent.com/17467365/104557922-fa49b500-567c-11eb-9398-766c29ed59de.png)
![image](https://user-images.githubusercontent.com/17467365/104557929-fd44a580-567c-11eb-8948-4bcab81677ac.png)

**Comment by Yanyan-Wang** [comment]
那应该是边类型不是 cubic，看下是不是别的地方被设置成了 cubic-vertical 或者 cubic-horizontal 之类的

**Comment by yumenglong** [comment]
没有呢 亲  
https://codepen.io/yumenglong/pen/gOwBaYG?editors=0010

**Comment by yumenglong** [comment]
这个代码功能中，只用了cubic的边。没有用其他类型的边
https://codepen.io/yumenglong/pen/gOwBaYG?editors=0010

**Comment by Yanyan-Wang** [comment]
在你代码的 507 行加上 curveOffset: 300 即可
