### ISSUE TITLE
自定义图片节点在图的modes配置设置activate-relations的问题

### ISSUE THREAD

**Issue by summerLoveqq** [antvis/G6#2505]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/g6-reproduction-template-uvzdf?file=/src/index.js)

### Steps to reproduce
import G6 from "@antv/g6";

const data = {
  nodes: [
    {
      id: "node1",
      x: 100,
      y: 200,
      type: "image"
    },
    {
      id: "node2",
      x: 300,
      y: 200
    },
    {
      id: "node3",
      x: 400,
      y: 400
    }
  ],
  edges: [
    {
      id: "edge1",
      target: "node2",
      source: "node1"
    },
    {
      id: "edge2",
      target: "node2",
      source: "node3"
    }
  ]
};
const graph = new G6.Graph({
  container: "root",
  width: 500,
  height: 500,
  modes: {
    default: ["drag-canvas", "drag-node", "activate-relations"]
  }
});
graph.read(data);

| Environment | Info |
|---|---|
| g6 | 4.0.4 |
| System | - |
| Browser | - |

---
拖动会报错，悬浮的时候，如果点是图片节点，不会像普通节点一样置于底层

**Comment by Yanyan-Wang** [comment]
image 节点报错问题 4.1.0-beta.1 已解决。普通节点也不会置于顶层，可以自己控制 node.toFront

**Comment by Yanyan-Wang** [comment]
正式版 4.1.0 已发布
