### ISSUE TITLE
node.type改为image时，若指定了size，则clipCfg（circle）不生效

### ISSUE THREAD

**Issue by rwsbillyang** [antvis/G6#2507]
- **G6 Version**:
4.0.3
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:   https://g6.antv.vision/zh/examples/net/radialLayout#sortRadial
在上面的demo演示链接中：

将node.type改为 image， 给node指定size情况下则裁切不生效：
```javascript
data.nodes.forEach((node) => {
//添加以下代码:
  node.size = [20,20];//注释掉可以圆形裁切（但无法达到缩小图片目的），保留则不裁切
  node.type= 'image', 
  node.clipCfg = {
        show: true,
        type: 'circle',
        r: 20
      }
  node.img = 'https://gw.alipayobjects.com/mdn/rms_f8c6a0/afts/img/A*mpPvTKdP7cIAAAAAAAAAAABkARQnAQ';
//添加以上代码，将节点修改为image，并且圆形裁切，不生效；除非注释掉:  node.size = [20,20]; 

  node.style = {
    lineWidth: 4,
    fill: '#fff',
    stroke: colors[node.sortAttr2] || colorsObj[node.sortAttr2],
  };
});
```

根据官方文档：https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/built-in/image ，使用方法应该没有错。

**Comment by Yanyan-Wang** [comment]
应该是因为你设置的 r 太大了，node.size 里面的值是 image 的长和宽。clipCfg 的 r 是裁剪的半径。你把 r 设置成 5 就能看到效果了

**Comment by rwsbillyang** [comment]
多谢解答，测试了一下，将r的值设置为size的一半，效果较好。
