### ISSUE TITLE
缩进树是否可以加一个拖拽的功能

### ISSUE THREAD

**Issue by BabyMing** [antvis/G6#2509]
请问缩进树是否有计划加一个节点拖拽的功能？

**Comment by Yanyan-Wang** [comment]
modes 里面加 'drag-node' 即可，所有 graph 都是一样的，跟使用什么布局以及哪种 graph 没有关系。
如果有自定义节点的话，可能被拖拽的图形 addShape 的时候要加上 draggable: true ，和 name、attrs 平级

**Comment by BabyMing** [comment]
https://ant-design.gitee.io/components/tree-cn/#components-tree-demo-draggable
我想要的是这种效果，可以实现吗？

**Comment by Yanyan-Wang** [comment]
类似这个吧 https://g6.antv.vision/zh/examples/interaction/moveSubtree#dragSubtree
只是 layout 换成 indented

**Comment by BabyMing** [comment]
非常感谢您！antv越来越棒了

**Comment by avrinfly** [comment]
> 类似这个吧 https://g6.antv.vision/zh/examples/interaction/moveSubtree#dragSubtree 只是 layout 换成 indented

请问这个示例是被取消了么，这个链接打不开了

**Comment by Yanyan-Wang** [comment]
> > 类似这个吧 https://g6.antv.vision/zh/examples/interaction/moveSubtree#dragSubtree 只是 layout 换成 indented
> 
> 请问这个示例是被取消了么，这个链接打不开了

https://g6.antv.antgroup.com/examples/interaction/treeBehavior/#dragSubtree
