### ISSUE TITLE
自定义二分图布局使用 activate-relations 事件， label值不展示

### ISSUE THREAD

**Issue by Johnsstt** [antvis/G6#2512]
自定义二分图布局使用activate-relations事件，鼠标第一次移动上展示对应的label值，再次移动到节点上时，label值不展示
![11111](https://user-images.githubusercontent.com/3023129/103536297-363a8880-4ecd-11eb-9eca-78cf7d400a96.gif)

**Comment by Yanyan-Wang** [comment]
升级到 4.1.0 应该已经解决。还是不行的话，麻烦提供在线最小复现 demo
