### ISSUE TITLE
dagre layout abnormal after combo unexpanded

### ISSUE THREAD

**Issue by Tronsfey** [antvis/G6#2514]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/serene-kowalevski-6tevy?file=/index.js)

#### Steps to reproduce

1. unexpand combo2，dagre layout rankdir seems changed to 'RL'
![image](https://user-images.githubusercontent.com/4178124/103616615-b4e40400-4f67-11eb-822d-695c770bd5ed.png)

#### Steps to reproduce

1. unexpand combo2 and combo3
2. expand combo2
![image](https://user-images.githubusercontent.com/4178124/103616858-2b810180-4f68-11eb-91be-be034bb5ff09.png)

| Environment | Info |
|---|---|
| g6 | 4.0.4 |
| System | - |
| Browser | - |

**Comment by JyotsnaC** [comment]
I am facing the same problem as well. I am on G6 4.1.12

**Comment by Yanyan-Wang** [comment]
solved by v4.7.15
