### ISSUE TITLE
Dagre - Ability to know when the layout calculation is finished on the worker thread when enableWorker = true

### ISSUE THREAD

**Issue by 1994benc** [antvis/G6#2517]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
It'd be nice if we could get an event for when the layout is done calculating in the worker thread and the graph UI has actually been rendered so we can disable our loading indicator and show the rendered graph properly. Currently, while the layout is being calculated on the worker thread, the graph UI is not organized nicely (the nodes are overlapped on top of each other) and, even after 'afterrender' has been fired, the graph UI has not rendered with the layout yet until after a moment later

### What does the proposed API look like?
Fire an event called 'after-worker-layout' after the layout has been calculated on the worker thread.
OR  fire the 'afterlayout' after the layout has actually been calculated on the worker thread.

**Comment by Yanyan-Wang** [comment]
You can add a listener for the timing event 'afterlayout' like this:
```
graph.on('afterlayout', e => {
  console.log('layout end')
})
```

Note that it should be binded before `graph.render()`

**Comment by Yanyan-Wang** [comment]
as shown in the demo, when the layout is finished, the text of the tip on the top is changed to 'done':
https://g6.antv.vision/zh/examples/net/furchtermanLayout#fruchtermanWebWorker
