### ISSUE TITLE
当节点类型为 'image'图片时，如何给 图片设置背景颜色

### ISSUE THREAD

**Issue by ahouvideo** [antvis/G6#2519]
defaultNode: {
          type: "image",
          size: 20,
          color: "#5B8FF9",

          style: {
            lineWidth: 10,
            // fill: "#C6E5FF",
            background: {
              fill: "#ffffff",
              stroke: "green",
              padding: [3, 2, 3, 2],
              radius: 2,
              lineWidth: 3,
            },
          },

毫无作用。。。。

**Comment by baizn** [comment]
图片不能设置背景颜色……

**Comment by shannonchou** [comment]
如果把node size 设置大于图片size，图片周围的空白区域也不能设置背景色吗?
