### ISSUE TITLE
多个内置图形组成一个group 新的图形，该怎么改变新图形的大小

### ISSUE THREAD

**Issue by ZOEWANGCHINA** [antvis/g6#252]
多个内置图形组成一个group 新的图形，该怎么改变新图形的大小。
![image](https://user-images.githubusercontent.com/4970143/40635650-aab1c3b0-632d-11e8-90ff-89c114c9a9fc.png)
类似这个，要如何缩放这个图形。

**Comment by ZOEWANGCHINA** [comment]
// 获取组属性
            let box = group.getBBox();    
       // 图组缩放
            let sx = cfg.size[0]/box.width //x轴缩放量 现宽度/原宽度
            let sy = cfg.size[1]/box.height // y轴缩放量 现长度/原长度
            group.scale(sx,sy);

这样写可以实现，但是拖动缩放的时候 x,y 会跟着动。 不会在原来的距离里面缩放。

**Comment by TomHuangCN** [comment]
套多一个 group，应该能解决

```js
const newGroup = group.addGroup();
```
