### ISSUE TITLE
G6导出图片可以自定义背景妈？项目有个加水印的需求

### ISSUE THREAD

**Issue by 52jaden** [antvis/G6#2521]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
导出图谱的图片时，可以添加水印，防止盗图

### What does the proposed API look like?
导出图片的api，可以自定义背景

**Comment by Yanyan-Wang** [comment]
可以加水印 https://g6.antv.vision/zh/docs/api/graphFunc/watermarker
但是现在用 downloadImage 或 downloadFullImage 下载图片不会带有水印。可以自己用 html2canvas 之类的工具导出图片

**Comment by d623141153** [comment]
> html2canvas

我现在使用的就是这种方案，但是html2canvas之类的工具实现不了 downloadFullImage 的效果，下载的图都不是完整的，全是可视区域内的。想截完整的就要在截图前调用fitView，但如果图谱复杂、节点特别多的话，fitView后图就会变得很小，下载下来，截的图肯定也很小，再放大看肯定就不清晰了，没啥使用价值了

**Comment by Yanyan-Wang** [comment]
或许用 G6 的 toFullDataURL 导出 base64 图片，然后放到一个 div 中，然后再和现在 G6 的水印一起 html2canvas 就可以

 https://g6.antv.vision/zh/docs/api/graphFunc/download#graphtofulldataurlcallback-type-imageconfig

**Comment by Yanyan-Wang** [comment]
4.2.5 起支持下载图片带水印，感谢社区同学 @xiaohu12685 贡献

**Comment by lunoob** [comment]
请问一下，你是怎么解决的呢

**Comment by lunoob** [comment]
师兄，这也埋得太深了⑧，文档一字都没提及😵
