### ISSUE TITLE
同时使用zoom-canvas与activate-relations时，缩放无效

### ISSUE THREAD

**Issue by zhangxiaoshang** [antvis/G6#2523]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gracious-brown-43v1p?file=/index.js)

### Steps to reproduce
- 1. 使用重现DEMO中 dataSimple 数据时，功能正常
- 2.使用重现DEMO中 dataset 数据时，缩放正常，但是当点击节点，高亮关系后，画布缩放无效

| Environment | Info |
|---|---|
| g6 | 4.0.4 |
| System | - |
| Browser | - |

---
不清楚是数据有bug还是因为数据复杂触发了g6的bug

**Comment by Yanyan-Wang** [comment]
升级到 4.1.0 即可
