### ISSUE TITLE
G6 4.10.0 版本目前没有看到一个source 对应多个target 这个支持吗

### ISSUE THREAD

**Issue by cor0ps** [antvis/G6#2526]
最近遇到构建图，一个source 对应  多个  target   G6支持吗
比如：
[

source:"n1",
target:{"n2","n3","n4"}
]

**Comment by Yanyan-Wang** [comment]
分成多条边就可以了呀
edges: [
{source:"n1", target: "n2"},
{source:"n1", target: "n3"},
{source:"n1", target: "n4"}
]

没有直接的支持
