### ISSUE TITLE
custom Toolbar undo not work

### ISSUE THREAD

**Issue by xiaofengqqcom123** [antvis/G6#2527]
demo: https://codesandbox.io/s/hopeful-yalow-rs3iz?file=/index.js
code: 

```
const toolbar = new G6.ToolBar({
  handleClick: (code, graph) => {
    debugger;
    switch (code) {
      case "undo":
        console.log("getUndoStack", graph.getUndoStack());
        toolbar.undo();
        break;
      case "redo":
        toolbar.redo();
        break;
      default:
        break;
    }
  }
});
```
not work

**Comment by Yanyan-Wang** [comment]
It works in your demo. Drag a node and click the undo button.

**Comment by xiaofengqqcom123** [comment]
咋这么尴尬，提供了个正常的

**Comment by Yanyan-Wang** [comment]
所以是没有问题吗？没有问题的话，这个 issue 就关掉咯？

**Comment by xiaofengqqcom123** [comment]
好的好的发自我的华为手机-------- 原始邮件 --------发件人： Yanyan Wang <notifications@github.com>日期： 2021年1月8日周五 下午2:23收件人： antvis/G6 <G6@noreply.github.com>抄送： xiaofeng <1944681023@qq.com>, Author <author@noreply.github.com>主    题： Re: [antvis/G6] custom Toolbar undo not work (#2527)

所以是没有问题吗？没有问题的话，这个 issue 就关掉咯？
