### ISSUE TITLE
树形图表中，子节点过多，树形结构庞大。在交互上是否能最小节点集合成一个大的节点?并对里面的节点进行交互

### ISSUE THREAD

**Issue by ChLiaoXiang** [antvis/G6#2528]
在项目中碰到子节点过多，某子节点要拖入其他父节点！树形比较密集，有可以直接把最终子节点放入一个大的节点集合，然后可以对集合中的节点进行拖拽到其他的父节点的方式嘛？

**Comment by Yanyan-Wang** [comment]
拖拽更改树结构 demo：https://g6.antv.vision/zh/examples/interaction/moveSubtree#dragSubtree
考虑结合 lasso 选择或者 brush 框选：
https://g6.antv.vision/zh/examples/interaction/select#lasso
https://g6.antv.vision/zh/examples/interaction/select#brush

**Comment by ChLiaoXiang** [comment]
打了很多错别字，不好意思啊!  其实想要的最终目的是这样子的
![image](https://user-images.githubusercontent.com/38313204/103970424-3378b580-51a3-11eb-9acb-8e1c79a51569.png)；
现在完成效果如下，最后的子节点希望是一个集合，最后集合的子节点可以跟其他父节点进行交互！
![image](https://user-images.githubusercontent.com/38313204/103970512-64f18100-51a3-11eb-951f-7f19db4c5760.png)；

**Comment by Yanyan-Wang** [comment]
emm，那最简单的办法应该是把一个叶子节点自定义成一行节点的样子，也就是那一行叶子节点就用一个节点表示

**Comment by ChLiaoXiang** [comment]
尝试的时候发现-如果我把直接做成一个节点，那么我对他的操作就是一个整体操作了！真是目的还是想对他做一个单一的操作！想把叶节点拖入到其他父结点中，成为其他的父节的子节点！

**Comment by Yanyan-Wang** [comment]
那你把数据结构改变一下，同一行的叶子节点变成后者是前者的子节点，除了每行第一个跟真正的父节点连接，其他都把前一个叶子节点作为副节点

**Comment by Yanyan-Wang** [comment]
> 那你把数据结构改变一下，同一行的叶子节点变成后者是前者的子节点，除了每行第一个跟真正的父节点连接，其他都把前一个叶子节点作为副节点

副节点 -> 父节点

**Comment by ChLiaoXiang** [comment]
> > 那你把数据结构改变一下，同一行的叶子节点变成后者是前者的子节点，除了每行第一个跟真正的父节点连接，其他都把前一个叶子节点作为副节点
> 
> 副节点 -> 父节点

这种方法在数据结构不断的修改上来实现，确实还不错，后面点我去尝试下数据的修改！

我现在使用的方法是group.addShape  遍历生成shape 节点，然后根据坐标知道表里的shape的index，通过坐标转换来实现碰撞，修改对应的节点数据，但是现在遇到一个问题graph.refresh() 不能更新图表内容，用graph.render()更新，操作感觉很突兀！

**Comment by Yanyan-Wang** [comment]
是什么情况下需要更新图表的内容？


另外，最近新增了一个合并同类兄弟节点的 demo，跟你的解法不大一样，给大家参考：https://g6.antv.vision/zh/examples/interaction/treeBehavior#collapseSlibing
