### ISSUE TITLE
4.1.0启动项目时报错

### ISSUE THREAD

**Issue by DankeF** [antvis/G6#2529]
使用框架：Angular 9.1.0

现象：
g6昨天升级到4.1.0后，在启动项目时会报如下错误：

![image](https://user-images.githubusercontent.com/29647627/103970298-db41b380-51a2-11eb-9d62-b1c403e4e1e9.png)

之前使用4.0.4版本时没有这个错误。因为4.1.0解决了边label重影的问题，所以升级到了4.1.0

**Comment by Yanyan-Wang** [comment]
看一下pinned issue，应该是你的类型引用方式问题

**Comment by DankeF** [comment]
> 看一下固定的问题，应该是你的类型引用方式问题

我在我的文件里只是这样引用了：
import G6 from '@antv/g6';

**Comment by Yanyan-Wang** [comment]
看下有没有什么地方有自动引用了类型文件。或者是这个 registerBehavior 的地方截图看下

**Comment by DankeF** [comment]
> 看下有没有什么地方有自动引用了类型文件。或者是这个 registerBehavior 的地方截图看下

项目里没有其他地方引用g6了。下面是registerBehavior的地方：
node_modules\@antv\g6\node_modules\@antv\g6-pc\lib\index.d.ts

我暂时上传不了图片了，不好意思，在这个文件的245行。麻烦您看下。

**Comment by Yanyan-Wang** [comment]
node_modules 进去相关路径看下，这个 index.d.ts 里面应该有 export default 的

**Comment by DankeF** [comment]
@antv/g6-core/lib/behavior 路径下的index.d.ts里面内容：
```
import Behavior from './behavior';
export default Behavior;
```

**Comment by Yanyan-Wang** [comment]
似乎是你项目的 ts 配置不认识这种写法

https://stackoverflow.com/questions/54766706/moment-has-no-exported-member-default

**Comment by DankeF** [comment]
> 似乎是你项目的 ts 配置不认识这种写法
> 
> https://stackoverflow.com/questions/54766706/moment-has-no-exported-member-default

不好意思，我按照您给出的链接，在tsconfig.json 或 tsconfig.app.json中设置了"allowSyntheticDefaultImports": true，但还是在启动项目时报哪个错误。

**Comment by Yanyan-Wang** [comment]
再搜索一下看看有没有别的解法，应该是项目配置的原因，或者是 ts 版本的问题

**Comment by DankeF** [comment]
能请问下您用的ts版本是多少呢？我把ts设成和您一样试试。

**Comment by DankeF** [comment]
> 再搜索一下看看有没有别的解法，应该是项目配置的原因，或者是 ts 版本的问题

能请问下您用的ts版本是多少呢？我把ts设成和您一样试试。

**Comment by Nevermind-s** [comment]
Hi, 
I Have the same issue with: 

- Angular: 9.1.7
- Antv/g6: 4.1.1
- ts: 3.8.3

I also tried the "allowSyntheticDefaultImports": true in tsconfig.json, but still not working for me. Any help?

**Comment by Yanyan-Wang** [comment]
typescript v3.9.7

**Comment by DankeF** [comment]
> typescript v3.9.7

您好，我还是没有解决这个报错。
我有个疑问，github上packages/pc/src/index.ts这个文件和项目里node_modules\@antv\g6-pc\lib\index.d.ts这个文件里面写法不一样，并没有用  
`registerBehavior: typeof import("@antv/g6-core/lib/behavior").default.registerBehavior;`
这样的写法，而是在文件开始直接引入
`import { registerBehavior,... } from '@antv/g6-core';`

我把项目里node_modules\@antv\g6-pc\lib\index.d.ts这个文件的
`registerBehavior: typeof import("@antv/g6-core/lib/behavior").default.registerBehavior;`
修改为
`registerBehavior: typeof registerBehavior;`
并在文件开始引入
`import { registerBehavior } from '@antv/g6-core';`
项目是可以顺利启动的。

**Comment by Nevermind-s** [comment]
Hi guys,

I fixed it by adding `"skipLibCheck": true` to tsconfig.json. I'm not sure it's the best way to do it maybe and upgrade of the Angular and ts version would fix it as well.

**Comment by DankeF** [comment]
> Hi guys,
> 
> I fixed it by adding `"skipLibCheck": true` to tsconfig.json. I'm not sure it's the best way to do it maybe and upgrade of the Angular and ts version would fix it as well.

Hello,
Can you tell me which version Angular and TS are upgraded to fix this problem?
Think You

**Comment by Nevermind-s** [comment]
Hello, 

For your Angular version (9.1.0), don't upgrade it you can just add `"skipLibCheck": true` to tsconfig.json and it will work like a charm.

**Comment by DankeF** [comment]
> Hello,
> 
> For your Angular version (9.1.0), don't upgrade it you can just add `"skipLibCheck": true` to tsconfig.json and it will work like a charm.

think you

**Comment by baizn** [comment]
> Hi guys,
> 
> I fixed it by adding `"skipLibCheck": true` to tsconfig.json. I'm not sure it's the best way to do it maybe and upgrade of the Angular and ts version would fix it as well.

@Nevermind-s  thanks, We will release version 4.1.2 today to fix this problem

**Comment by Yanyan-Wang** [comment]
v4.1.3 已修复

fixed by v4.1.3
