### ISSUE TITLE
关于g6调用antDesignPro的方法问题

### ISSUE THREAD

**Issue by zhaxingaz** [antvis/g6#253]
我尝试在g6的itemclick事件方法中调用模态框展示方法，运行结果提示找不到该方法，同时也获取不了this.state数据，是我的姿势不对吗？？？

**Comment by zhaxingaz** [comment]
代码片段：
net.on('itemclick', function (ev) {
  this.setState({
    visible: true,
  });
});
当执行点击事件时报错：找不到this.setState

**Comment by ZOEWANGCHINA** [comment]
在外面 let _this = this;  你打印一下 这两个this 应该指向不一样。

**Comment by zhaxingaz** [comment]
@ZOEWANGCHINA 看来这个东西只能单独使用了
