### ISSUE TITLE
> 1、把groupByTypes设置成false，然后再使用edge.toFront(); 确实可以提高edge的层级，但是这样会导致添加边到节点上失败。

### ISSUE THREAD

**Issue by yumenglong** [antvis/G6#2531]
> 1、把groupByTypes设置成false，然后再使用edge.toFront(); 确实可以提高edge的层级，但是这样会导致添加边到节点上失败。
> 例如：这个例子中，groupByTypes设置成false后，边就连不上node上了：
> https://codepen.io/yumenglong/pen/qBaxVed

用新版本的 create-edge behavior 就可以了 https://g6.antv.vision/zh/examples/interaction/createEdge#click

_Originally posted by @Yanyan-Wang in https://github.com/antvis/G6/issues/2494#issuecomment-752916540_

**Comment by yumenglong** [comment]
create-edge   在自定义节点上能用吗？我怎么添加不成功呢？

**Comment by Yanyan-Wang** [comment]
应该没影响，你把你的自定义节点放到 demo 上试一下。有问题就提供在线 demo

**Comment by yumenglong** [comment]
1、当把trigger: 'click'时，可以点击节点添加边，边的层级是高于节点的。这个是没有问题的。
![image](https://user-images.githubusercontent.com/17467365/104160814-b82a3480-542c-11eb-9e48-3eb295fe1411.png)

![image](https://user-images.githubusercontent.com/17467365/104160689-7f8a5b00-542c-11eb-9d0f-a24250e68558.png)

2、问题是：trigger: 'drag'的时候，添加边就有问题了，并且我想从节点1的一个点拖出一条线到节点2的一个点上。
用type:'create-edge', 好像只能作用在节点上，不能作用在我自定义的这个锚点的shape上。如果我通过自定义事件，addItem添加边的话，边的层级又会低于节点。
https://codepen.io/yumenglong/pen/qBaxVed

**Comment by Yanyan-Wang** [comment]
> 1、当把trigger: 'click'时，可以点击节点添加边，边的层级是高于节点的。这个是没有问题的。
> ![image](https://user-images.githubusercontent.com/17467365/104160814-b82a3480-542c-11eb-9e48-3eb295fe1411.png)
> 
> ![image](https://user-images.githubusercontent.com/17467365/104160689-7f8a5b00-542c-11eb-9d0f-a24250e68558.png)
> 
> 2、问题是：trigger: 'drag'的时候，添加边就有问题了，并且我想从节点1的一个点拖出一条线到节点2的一个点上。
> 用type:'create-edge', 好像只能作用在节点上，不能作用在我自定义的这个锚点的shape上。如果我通过自定义事件，addItem添加边的话，边的层级又会低于节点。
> https://codepen.io/yumenglong/pen/qBaxVed


https://codepen.io/Yanyan-Wang/pen/eYdLqyE?editors=0010

**Comment by yumenglong** [comment]
![image](https://user-images.githubusercontent.com/17467365/104278286-511b8700-54e3-11eb-8e10-04b982dc7c74.png)
https://codepen.io/yumenglong/pen/qBaxVed

**Comment by yumenglong** [comment]
![image](https://user-images.githubusercontent.com/17467365/104278541-bcfdef80-54e3-11eb-8cdb-1afb23b7ad37.png)

**Comment by Yanyan-Wang** [comment]
我把我的 demo 改成 drag 了。你对照下看呢：https://codepen.io/Yanyan-Wang/pen/eYdLqyE?editors=0010

**Comment by yumenglong** [comment]
对， 我是要用drag 拖出来一条线的，不能用click的 亲

**Comment by yumenglong** [comment]
我是要在锚点的shape上拖出来一条线，链接到另一个节点的锚点shape上，所以我要用drag事件的，

**Comment by Yanyan-Wang** [comment]
我的那个 demo 是从锚点 drag 出来的呀，你看下

**Comment by yumenglong** [comment]
![image](https://user-images.githubusercontent.com/17467365/104279496-5d084880-54e5-11eb-80b3-b842a7d6aaa8.png)
这个地方是click  是吧？  设置成click后， 我上面说的target也是没有的   亲

**Comment by Yanyan-Wang** [comment]
> ![image](https://user-images.githubusercontent.com/17467365/104279496-5d084880-54e5-11eb-80b3-b842a7d6aaa8.png)
> 这个地方是click 是吧？ 设置成click后， 我上面说的target也是没有的 亲

我改成 trigger: 'drag' 了呀，交互上看有不满足的地方吗？没有 target 有啥影响吗？

**Comment by yumenglong** [comment]
1、我需要获取shouldBegin和shouldEnd   时，返回的 坐标 x， y
2、在添加边的时候，更新边的开始位置和结束位置。
3、如果取不到target我就  获取不到坐标了，另外这里是不是也限制不住了呢。
![image](https://user-images.githubusercontent.com/17467365/104280498-fe43ce80-54e6-11eb-961a-fe7a40eb47a6.png)

**Comment by yumenglong** [comment]
![image](https://user-images.githubusercontent.com/17467365/104280575-17e51600-54e7-11eb-8f8d-162fe071b86d.png)

**Comment by yumenglong** [comment]
或者说，用creat-edge创建边的时候，还可以用其他方法指定边的     开始连接点和结束连接点，我主要是想让边的  开始位置是在锚点的shape上，结束位置 也是在另一个节点的锚点的shape上。

**Comment by yumenglong** [comment]
类似与这个效果：
https://x6.antv.vision/zh/examples/showcase/practices#algo-flow

**Comment by Yanyan-Wang** [comment]
因为 groupByTypes 是 false，所以不论是 click 还是 drag，最终结束的动作都是被刚创建的处于最上层的 edge 拾取到，G6 内部是在结束动作时找到距离当前鼠标位置最近的节点最为边的 target 节点，所以没有给到 shouldEnd target，因为事实上结束动作的 target 是当前边的 path 而不是你期望的 target 节点上的图形。这一点确实应该在 G6 中优化一下，考虑这种情况。目前，可以像我这样写，会比较麻烦，但是还是可以实现：https://codepen.io/Yanyan-Wang/pen/eYdLqyE?editors=0010

后面我们再考虑一下怎么优化 create-edge。也欢迎社区 pr

**Comment by yumenglong** [comment]
> 因为 groupByTypes 是 false，所以不论是 click 还是 drag，最终结束的动作都是被刚创建的处于最上层的 edge 拾取到，G6 内部是在结束动作时找到距离当前鼠标位置最近的节点最为边的 target 节点，所以没有给到 shouldEnd target，因为事实上结束动作的 target 是当前边的 path 而不是你期望的 target 节点上的图形。这一点确实应该在 G6 中优化一下，考虑这种情况。目前，可以像我这样写，会比较麻烦，但是还是可以实现：https://codepen.io/Yanyan-Wang/pen/eYdLqyE?editors=0010
> 
> 后面我们再考虑一下怎么优化 create-edge。也欢迎社区 pr

好的，万分感谢，回答我这么久的问题，我去看一下

**Comment by Yanyan-Wang** [comment]
没问题的话先关掉咯，有问题再开新的哈
