### ISSUE TITLE
快速双击节点时，也会触发两次单击事件

### ISSUE THREAD

**Issue by samuelhsin** [antvis/G6#2533]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/festive-fermat-52vy4?file=/src/App.js)

### Steps to reproduce
点击节点两下，console会打印出

single click => 两次
double click => 一次

但是应该只需要 double click 一次就好了

代码：
g6.on("node:dblclick", () => {
  console.log("double click");
});

g6.on("node:click", () => {
  console.log("single click");
});

| Environment | Info |
|---|---|
| g6 | 4.1.1 |
| System | - |
| Browser | - |

**Comment by liononon** [comment]
是的，也遇到了这个问题

**Comment by ylm-hmt** [comment]
ok

**Comment by Yanyan-Wang** [comment]
MDN 的标准就是 dblclick 也会触发两次 click：https://codepen.io/Yanyan-Wang/pen/KKgYvxG?editors=1000

我们和标准保持一致

**Comment by hhlcom** [comment]
> MDN 的 dblclick 也是标准触发两次点击：[https://codepen.io/Yanyan-Wang/pen/KKgYvxGeditors=1000](https://codepen.io/Yanyan-Wang/pen/KKgYvxG?editors=1000)
> 
> 我们和标准保持一致
有什么办法可以避免一下么

**Comment by rmd1710714107** [comment]
> MDN 的标准就是 dblclick 也会触发两次 click：https://codepen.io/Yanyan-Wang/pen/KKgYvxG?editors=1000
> 
> 我们和标准保持一致

可是你给的那个例子虽然双击会触发单击事件，但是最后双击事件也会被触发。可是现在G6会把双击事件覆盖掉，也就是只触发两次单击事件后就没有下文了。
