### ISSUE TITLE
线上构建，多版本出现G6内部依赖包@antv/g-webgpu-core 无法找到

### ISSUE THREAD

**Issue by jumpingFinger** [antvis/G6#2534]
Tnpm 还是npm 都无法找到该依赖包
![image](https://user-images.githubusercontent.com/36480878/104015786-1c13e980-51f0-11eb-82a7-3a44c858ae58.png)

**Comment by Yanyan-Wang** [comment]
现在再试一下， g-webgpu-core 0.5.2 刚发的包，前面没有 sync 到 tnpm
