### ISSUE TITLE
⭐️ 💌 G6: 致用户的一封信，寻求社区贡献者！⭐️

### ISSUE THREAD

**Issue by Yanyan-Wang** [antvis/G6#2535]
# G6: 致用户的一封信，寻求社区贡献者！

致尊敬的 G6 用户：

大家好。

至今，G6 已发展了约三年。非常感谢三年来大家的信赖与支持。随着图可视化的广泛应用，G6 的使用量也迅速增长，随之而来的是更多的需求，GitHub Issues 增速大幅升高，我们看到了大家对图可视化的热情，以及该领域未来的一片蓝海。作为 G6 开发者的我们深感欣喜，更坚定了我们发展好 G6 的决心。

近来，G6 社区蓬勃发展，也有不少用户为 G6 提供了优秀的 Pull Requests，即使是修改一个错字、一个符号，我们都非常感激。由于身负技术与业务双重压力，G6 核心开发者们常常很难快速抽身解决 issues。因此，**我们希望有更多热爱图可视化、热爱开源的小虎斑们一起把 G6 建设得更好！**我们更将定期从共建者中选出幸运 contributor，送出**「🎊 AntV 纪念品礼包🎊」**。如果你有兴趣加入 AntV，我们更是非常欢迎（**简历可发送邮件至 antv@antfin.com**）！

图可视化与分析引擎 G6，期待你的一份力量！

我们选出了一些功能需求，如果你有兴趣，就在评论区认领吧～同时，我们也将公开官方的需求排期列表。
当然，如果你有自己的需求，也可以评论在下方，我们择优录入表格。
对列表有任何问题也可以在评论区提问哦。

### 2020 年度优秀贡献者

经过过去一年的试运行，我们收到了不少社区同学的 PR，每位同学都非常认真地为 G6 添砖加瓦，AntV G6 团队备感荣幸。从这些同学中，我们选出了 2020 年度贡献最多的三位社区同学：@ColinChen2、@zuiidea、@xiaohu12685。他们已获得 AntV 定制 AntV Outstanding Contributor 奖杯，并收到了 AntV 纪念品礼包。

欢迎更多社区同学加入到我们的大家庭中来！2021 年我们将继续运行该机制～也许下一个 AntV Outstanding Contributor 就是你！

###  等待认领的需求们

| Index | Tag | 具体描述 | 相关 issue | 认领用户 | 是否解决 |
| --- | --- | --- | --- | --- | --- |
| 0 | `图算法` | 图算法的 GPU 支持 |  |  |  |
| 1 | `图算法` | 图算法的 webworker 支持 | https://github.com/antvis/G6/issues/2203 | @zuiidea  | ✅  @antv/algorithm@0.1.0-beta |
| 2 | `图算法` | 最短路径支持返回多条最短路径 | https://github.com/antvis/G6/issues/2297 | @feikerwu | ✅  @antv/algorithm@0.1.0-beta |
| 3 | `图布局` | radial layout 支持指定起始和终止角度 | https://github.com/antvis/G6/issues/2484 |  |  |
| 4 | `图布局` | combo layout 优化 |  |  |  |
| 5 | `图布局` | 同时配置多个子图布局 | https://github.com/antvis/G6/issues/1462 |  @ColinChen2  |   ✅   @antv/g6@4.2.2 |
| 6 | `图布局` | 自研 dagre | 目前 dagre 依赖外部库，新需求难以支持 https://github.com/antvis/G6/issues/1701|  |  |
| 7 | `兼容性` | 浏览器兼容性测试 ie11，firefox |  |  |  |
| 8 | `兼容性` | minimap 在火狐上的问题 | https://github.com/antvis/G6/issues/2337 | @zjgyb | ✅  @antv/g6@4.1.8 |
| 9 | `兼容性` | 火狐自定义 double-finger-drag-canvas 失效 | https://github.com/antvis/G6/issues/2033 |  |   ✅    demo 修复 |
| 10 | `导出图片` | 导出图片带水印 | [https://github.com/antvis/G6/issues/2521](https://github.com/antvis/G6/issues/2521) | @xiaohu12685 |  ✅   @antv/g6@4.2.5 |
| 11 | `导出图片` | 导出单个节点图片 | https://github.com/antvis/G6/issues/2028 |  |  |
| 12 | `动画` | 状态支持动画配置 | https://github.com/antvis/G6/issues/2406 |  |  |
| 13 | `动画` | moveTo 带动效 |  |  | ✅   @antv/g6@4.3.3 |
| 14 | `插件` | grid 网格背景在 flex 布局下错位问题 | https://github.com/antvis/G6/issues/1594 | @zxccvms  |  |
| 15 | `交互` | drag-node 在节点拖拽过程中，自适应相关边上 label 的截断展示 |  | @xdddst  |  |
| 16 | `交互` | drag-canvas 拖动 emit 的事件回调中增加一个位置差参数，去记录一次拖动开始位置和拖动结束位置的位置差（dx、dy），用于做撤销重做 |  | @xdddst  |  |
| 17 | `交互` | 鼠标 hover 和点击进行上下游链路的高亮。用于dagre布局自底向上或自顶向下的探索，避免其他路径的干扰、一步步聚焦 |  | @xdddst  |  |
| 18 | 性能 | 将计算量较大的一些函数放在 Web Worker 中计算  |   | @sklinov |  |
| 19 | `图算法` | LOUVAIN 返回固定的社区 ID |  | @zuiidea  | ✅  @antv/algorithm@0.1.6 |
| 20 | `图布局` | CompactBox 树图布局优化 | https://github.com/antvis/G6/issues/2537 | @lmsccc  |  |
| 21 | `插件` | 时间轴支持配置控制按钮 |https://github.com/antvis/G6/issues/2581 |  |  |
| 22 | `树图` | 同一个画布中支持多棵树 |https://github.com/antvis/G6/issues/2690 |  |  |

### 官方近半年已排期需求

| Index | Tag | 模块 | 说明 | 是否完成 | 版本号 |
| --- | --- | --- | --- | --- | --- |
| 0 | `架构调整&拆包` | layout | 10+ 种布局 | ✅ | 4.1.1 |
| 1 | `架构调整&拆包` | algorithm | 10+ 图算法 | ✅ | 4.1.1 |
| 2 | `架构调整&拆包` | core | G6 Core， 只提供最基础的渲染、状态和自定义机制 | ✅ | 4.1.1 |
| 3 | `架构调整&拆包` | pc | G6 PC 实现 | ✅ | 4.1.1 |
| 4 | `架构调整&拆包` | g6 | 统一入口，先抛出g6-pc。后续将抛出 g6-mobile，并根据使用环境自动选择 | ✅ | 4.1.1 |
| 5 | `架构调整&拆包` | elements | G6 默认提供的节点和边类型 | ✅ | 4.1.1 |
| 6 | `架构调整&拆包` | plugins | G6 插件 | ✅ | 4.1.1 |
| 7 | `架构调整&拆包` | chart-node-g6 | 支持 G2 统计图表 | ✅ | 3.8.5 |
| 8 | `架构调整&拆包` | site | G6 官网 | ✅ | 4.1.1 |
| 9 | `体验优化` | Behavior 优化 | zoom-canvas 与 drag-canvas 在 enableOptimize 时冲突 | ✅ | 4.1.1 |
| 10 | `体验优化` | Combo | 新类型 Combo，允许加载更多节点，支持混动混合点击加载更多两种交互 |  |  |
| 11 | `体验优化` | Combo | 支持固定大小的 Combo | ✅ | 4.2.0 |
| 12 | `体验优化` | 合并边 DEMO | 同类型，同方向的边自动合并，显示条数 |  |  |
| 13 | `体验优化` | 文本换行 | 节点和边上 label 自动换行 |  |  |
| 14 | `体验优化` | 图例 | 增加图例 | ✅  | 4.3.0 |
| 15 | `易用性` | G6 支持 React 节点 | 节点支持渲染 antd 等 React 组件 |  |  |
| 16 | `易用性` | 节点定义 DEMO | 提供一个使用 React 定义节点的Demo，收集用户反馈后再考虑是否 G6 默认支持 |  |  |
| 17 | `易用性` | 3+ 图组件 | 提供开箱即用的图组件 |  |  |
| 18 | `性能优化` | 折线 | 折线性能优化 |  |  |
| 19 | `性能优化` | setState | setState 性能优化 |  |  |
| 20 | `时序分析` | 场景方案 | 探索时序分析 |  |  |
| 21 | `时序分析` | 时间轴 | 时间轴功能优化，可筛选边 |✅ | 4.2.1 |
| 22 | `时序分析` | 时间轴开放能力 | 时间轴组建 AntV 通用化 |  |  |
| 23 | `布局` | 智能推荐布局 | 支持 4 种布局智能推荐 | ✅  | 4.3.0 |
| 24 | `布局` | 布局优化 | 关系扩散布局 |  |  |
| 25 | `布局` | ForceAtlas2 | ForceAtlas2 布局 |✅ | 4.2.5 |
| 26 | `布局` | Combo 布局 | Combo 布局优化 |  |  |
| 27 | `G6 mobile` | G6 mobile H5 版本 | 完成核心功能的建设，可以为业务方提供高频组件 |  |  |
| 28 | `G6 mobile` | beta 版本 | 发布 beta 版本 |  |  |
| 29 | `G6 mobile` | 1.0 版本 | 发布 1.0 版本 | ✅  |  |
| 30 | `设计` | 图可视化设计体系 |  |  |  |
| 31 | `GraphMaker 2.0` | GraphMaker 2.0 发布 | 可视化创建及配置节点 |  |  |
| 32 | `易用性` | 数据处理 | 支持多格式的图数据转，及连接数据库 |  |  |
| 33 | `易用性` | 异常处理 |  |  |  |
| 34 | `易用性` | 对齐线  |  | ✅  | 4.3.0  |
| 35 | `性能优化` | 包体积优化 | 降低到 1M 以下，全面支持按需加载 |  |  |
| 36 | `性能优化` |  | 元素更新性能 |  |  |
| …… |  |  |  |  |  |

**Comment by ColinChen2** [comment]
@Yanyan-Wang 你们新的重构版本这么快就出来了！！！👍
第5个问题本来就是我提的，那就我来试试吧。至于后续怎么交流呢，技术方案出来之后找谁呢？

**Comment by Yanyan-Wang** [comment]
> @Yanyan-Wang 你们新的重构版本这么快就出来了！！！👍
> 第5个问题#1462, 本来就是我提的，那就我来试试吧。至于后续怎么交流呢，技术方案出来之后找谁Review呢？

wow，感谢。共建者可加钉钉群：
![image](https://user-images.githubusercontent.com/29593318/104144861-f2c9a800-53ff-11eb-95ca-c20eaee7f2b3.png)

前期方案可以在群里交流，后面就是 github 提 pr 大家一起 cr 和讨论～

**Comment by xdddst** [comment]
1、behavior drag-node优化：边的label节点拖动过程中，做了fittingRelativeEdeges，根据两个节点间的距离，去自适应相关边的展示（做截断展示...）；
2、behavior drag-canvas优化：中拖动 emit 的事件回调中增加一个位置差参数，去记录一次拖动开始位置和拖动结束位置的位置差（dx、dy），用于做撤销重做；
3、鼠标hover和点击进行子图锁定，可沉淀为一个mode，用于自底向上的探索，避免其他路径的干扰、一步步聚焦。

**Comment by zuiidea** [comment]
@Yanyan-Wang 需求19里是 Louvain 返回固定的社区 ID，需要改一下~

**Comment by Yanyan-Wang** [comment]
> @Yanyan-Wang 需求19里是 Louvain 返回固定的社区 ID，需要改一下~

好的

**Comment by feikerwu** [comment]
#2297 最短路径支持返回多条最短路径:  在另外一个algorithm修复了，麻烦抽空看看～

**Comment by Yanyan-Wang** [comment]
> #2297 最短路径支持返回多条最短路径: 在另外一个algorithm仓库修复了，[antvis/algorithm#6](https://github.com/antvis/algorithm/pull/6) 麻烦抽空看看～

感谢，今天发布了 @antv/algorithm@0.1.0-beta 版本哈

**Comment by yzq1979** [comment]
增加地图布局分析功能呀，这个很多场合急需的。

**Comment by lmsccc** [comment]
第20个需求我并没有认领哦，麻烦确认一下是不是弄错了 @Yanyan-Wang

**Comment by zxccvms** [comment]
使用了3.7.1的版本 不知道现在的版本是否已经修复 
1、grid网格插件 拖拽画布 就会发现网格不会跟随画布走 且 部分地方没有网格
2、用dagre模块封装的dagreLayout中的execute方法 一言难尽。。。

**Comment by zxccvms** [comment]
使用了3.7.1的版本 不知道现在的版本是否已经修复 
1、grid网格插件 拖拽画布 就会发现网格不会跟随画布走 且 部分地方没有网格
2、用dagre模块封装的dagreLayout中的execute方法 一言难尽。。。

**Comment by zxccvms** [comment]
需求14

**Comment by Yanyan-Wang** [comment]
> 需求14

进展如何～

**Comment by carveybunt** [comment]
`ReactDOM` 能开源下吗？想看下实现原理，然后找人弄一个`VueDom`。

**Comment by zhang-maxwell** [comment]
> 
+1，同诉求

**Comment by zhang-maxwell** [comment]
>  @carveybunt  ReactDOM 能开源下吗？想看下实现原理，然后找人弄一个VueDom。

+ 1，同想法
