### ISSUE TITLE
undo && redo ，demo 失效

### ISSUE THREAD

**Issue by xiaofengqqcom123** [antvis/G6#2538]
文档地址：https://g6.antv.vision/zh/docs/api/graphFunc/stack
demo地址：https://github.com/antvis/G6/blob/master/src/plugins/toolBar/index.ts#L184 已失效
![image](https://user-images.githubusercontent.com/29247931/104157732-b3fb1880-5426-11eb-911a-a689c4aea5a7.png)

需求： 如何 调用 undo ?

**Comment by Yanyan-Wang** [comment]
因为刚刚完成拆包，源码文件位置有改动，见：
undo： 
https://github.com/antvis/G6/blob/33482dcd59f6cbe534812649f24f45f12b564da3/packages/plugin/src/toolBar/index.ts#L208
redo：
https://github.com/antvis/G6/blob/33482dcd59f6cbe534812649f24f45f12b564da3/packages/plugin/src/toolBar/index.ts#L295

**Comment by xiaofengqqcom123** [comment]
谢谢，已找到

**Comment by xiaofengqqcom123** [comment]
建议把文档地址，改下~

**Comment by Yanyan-Wang** [comment]
嗯嗯好的，我们会尽快更新官网
