### ISSUE TITLE
Net 类画图片的时候，只能是绝对路径吗，如下，直接写 shape: './file/***.png' ，会在页面上变成 rect。如果想把shape 变为本地的相对路径，该怎么写，谢谢大神了

### ISSUE THREAD

**Issue by Yaids** [antvis/g6#254]
"nodes": [
    {
      "shape": "https://zos.alipayobjects.com/rmsportal/UQZWYYDegebxkadaciod.png",
      "label": "销售/处理 商品",
      "x": 760,
      "y": 450,
      "id": "7e2xc643",
      "size": [
        139,
        124
      ]
    },
    {
      "shape": "https://zos.alipayobjects.com/rmsportal/ZLXQVmQrwOvZgYOYMJcP.png",
      "label": "存入仓库",
      "x": 500,
      "y": 450,
      "id": "7e2bcqz3",
      "size": [
        124,
        122
      ]
    },
    {
      "shape": "https://zos.alipayobjects.com/rmsportal/vtsvLRkKyqgdeCUbzMaI.png",
      "label": "收到货物并检查",
      "x": 500,
      "y": 80,
      "id": "1e23c643",
      "size": [
        95,
        150
      ]
    },
    {
      "shape": "https://zos.alipayobjects.com/rmsportal/EchvJdFiaKqaUoaDSJRS.png",
      "label": "运送装置",
      "x": 760,
      "y": -30,
      "id": "9372784b",
      "size": [
        99,
        65
      ]
    },
    {
      "shape": "https://zos.alipayobjects.com/rmsportal/RSNIlcihcKtrXbJKYjCV.png",
      "label": "配送员",
      "x": 760,
      "y": 180,
      "id": "7e72c643",
      "size": [
        88,
        126
      ]
    },
    {
      "shape": "https://zos.alipayobjects.com/rmsportal/vtsvLRkKyqgdeCUbzMaI.png",
      "label": "打包并分配 ",
      "x": 500,
      "y": 750,
      "id": "afe45117",
      "size": [
        95,
        150
      ]
    },
    {
      "shape": "https://zos.alipayobjects.com/rmsportal/kmjjtiERUwnvDEOrlidg.png",
      "label": "派送员",
      "x": 760,
      "y": 640,
      "id": "7e2b1643",
      "size": [
        105,
        122
      ]
    },
    {
      "shape": "https://zos.alipayobjects.com/rmsportal/EchvJdFiaKqaUoaDSJRS.png",
      "label": "运送装置",
      "x": 760,
      "y": 850,
      "id": "7e098c43",
      "size": [
        99,
        65
      ]
    }
  ],

**Comment by TomHuangCN** [comment]
用 html 节点
