### ISSUE TITLE
svg dom元素定义class不显示

### ISSUE THREAD

**Issue by zhaokgithub** [antvis/G6#2541]
需求：自定义DOM节点实现滚动效果
现象：chrome70 以上的渲染没问题，chrome70以下的版本元素页面加载但是没有显示

**Comment by Yanyan-Wang** [comment]
请给出最小复现的在线 demo

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
