### ISSUE TITLE
Dagre类型，LR布局，希望节点能提供对齐方式

### ISSUE THREAD

**Issue by noonehide** [antvis/G6#2542]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
LR布局，相同节点类型，长度不一致，会中心对齐，不会左对齐或者右对齐

### What does the proposed API look like?
nodeAligin: left

![image](https://user-images.githubusercontent.com/12743022/104407401-79b38780-559c-11eb-9756-593b275fbb26.png)

**Comment by Yanyan-Wang** [comment]
需要左对齐的话，就是在自定义节点的时候，addShape 时的 x y 不要与节点大小有关，比如说 rect 的 x: 0, y: 0

**Comment by noonehide** [comment]
> 需要左对齐的话，就是在自定义节点的时候，addShape 时的 x y 不要与节点大小有关，比如说 rect 的 x: 0, y: 0

我试了下，shape里面的attrs属性都设置了x:0,y:0。还是居中
![image](https://user-images.githubusercontent.com/12743022/104416078-1a5e7300-55ae-11eb-9457-176c8b124d41.png)

**Comment by Yanyan-Wang** [comment]
哦 path 不是通过 x y 来确定位置的了，是根据 path 字段里面定义的路径来的，把 path 的路径 x 对齐到 0 就可以

**Comment by Yanyan-Wang** [comment]
ok 了么？

**Comment by noonehide** [comment]
> ok 了么？
可以了，我在所有的自定义节点外面都套了个rect

**Comment by meikang123** [comment]
![image](https://user-images.githubusercontent.com/16129828/155102743-60c94cc7-410d-4acb-be49-f3f1a4a403d3.png)
const dir = 'TB'设置后  不是居中的  自定义的
