### ISSUE TITLE
v4.1.1 版本下 registerNode自定义节点不成功

### ISSUE THREAD

**Issue by Slp-slp** [antvis/G6#2543]
v4.1.1 版本下 registerNode自定义节点不成功
在demo中更新为v4.1.1 注册节点样式都不在了
demo：https://www.yuque.com/antv/g6/zmfur7

**Comment by Slp-slp** [comment]
`
G6.registerNode('node', {
  drawShape: function drawShape(cfg, group) {
    console.log('111111111111111画画')
      const width = cfg.style.width;
      const stroke = cfg.style.stroke;
      const rect = group.addShape('rect', {
        attrs: {
          x: -width / 2,
          y: -15,
          width,
          height: 30,
          radius: 15,
          stroke,
          lineWidth: 0.6,
          fillOpacity: 1,
          fill: '#fff'
        }
      });
      const point1 = group.addShape('circle', {
        attrs: {
          x: -width / 2,
          y: 0,
          r: 3,
          fill: stroke
        }
      });
      const point2 = group.addShape('circle', {
        attrs: {
          x: width / 2,
          y: 0,
          r: 3,
          fill: stroke
        }
      });
      return rect;
    },
    getAnchorPoints: function getAnchorPoints() {
      return [[0, 0.5], [1, 0.5]];
    },
    update: function (cfg, item) {
      const group = item.getContainer()
      const children = group.get('children')
      const node = children[0]
      const circleLeft = children[1]
      const circleRight = children[2]

      const {style: {stroke}, labelStyle} = cfg

      if (stroke) {
        node.attr('stroke', stroke)
        circleLeft.attr('fill', stroke)
        circleRight.attr('fill', stroke)
      }
    }
  },
  'single-shape'
);
`

**Comment by Yanyan-Wang** [comment]
官网上很多例子都是自定义节点，也是 4.1.1 没啥问题呢 https://g6.antv.vision/zh/examples/case/customFlow#customFlow
不成功提供一下最小复现的在线 demo

另外，所有文档在官网上看，语雀上的已经不维护了

**Comment by Slp-slp** [comment]
谢谢，我再试一下~

**Comment by Yanyan-Wang** [comment]
好的，有问题的话开 issue 需要提供一下在线复现最小 demo 哦，这个 issue 就先关闭了

**Comment by Wangoutsmart** [comment]
应该是new G6.Graph你使用了shape属性，在v4废弃了，应该改为type
