### ISSUE TITLE
请问，我的生态树节点非常多，当所有的节点都打开时，页面放不下，是否可以做成在不适用缩放的情况下，使画布有滚动的效果？

### ISSUE THREAD

**Issue by BabyMing** [antvis/G6#2544]

**Comment by Yanyan-Wang** [comment]
就是 drag-canvas ，或者想用滚轮的话参考 https://g6.antv.vision/zh/examples/interaction/customBehavior#dragCanvasTwoFingers

**Comment by WongBaba** [comment]
我项目也有跟你一样的设计，我项目禁用了缩放和拖动树功能，实现方案是：设置树图的渲染方式为svg，将画布大小设置为0px或其他方式不可见，然后获取实际渲染出的树图宽高tree_dom.width  和 tree_dom.height
`
let tree_dom = document.querySelector("g").getBoundingClientRect()
graph.changeSize(tree_dom.width + 50 + 170, tree_dom.height + 100)
graph.fitView()
`

然后将宽高略微增加一些并重新设置画布大小，刷新画布，就可以得到一棵足够展示所有节点的树图

**Comment by WongBaba** [comment]
我项目也有跟你一样的设计，我项目禁用了缩放和拖动树功能，实现方案是：设置树图的渲染方式为svg，将画布大小设置为0px或其他方式不可见，然后获取实际渲染出的树图宽高tree_dom.width  和 tree_dom.height
`
let tree_dom = document.querySelector("g").getBoundingClientRect()
graph.changeSize(tree_dom.width + 50 + 170, tree_dom.height + 100)
graph.fitView()
`

然后将宽高略微增加一些并重新设置画布大小，刷新画布，就可以得到一棵足够展示所有节点的树图

**Comment by WongBaba** [comment]
我项目也有跟你一样的设计，我项目禁用了缩放和拖动树功能，实现方案是：设置树图的渲染方式为svg，将画布大小设置为0px或其他方式不可见，然后获取实际渲染出的树图宽高tree_dom.width  和 tree_dom.height
`
let tree_dom = document.querySelector("g").getBoundingClientRect()
graph.changeSize(tree_dom.width + 50 + 170, tree_dom.height + 100)
graph.fitView()
`

然后将宽高略微增加一些并重新设置画布大小，刷新画布，就可以得到一棵足够展示所有节点的树图

**Comment by WongBaba** [comment]
我项目也有跟你一样的设计，我项目禁用了缩放和拖动树功能，实现方案是：设置树图的渲染方式为svg，将画布大小设置为0px或其他方式不可见，然后获取实际渲染出的树图宽高tree_dom.width  和 tree_dom.height
`
let tree_dom = document.querySelector("g").getBoundingClientRect()
graph.changeSize(tree_dom.width + 50 + 170, tree_dom.height + 100)
graph.fitView()
`

然后将宽高略微增加一些并重新设置画布大小，刷新画布，就可以得到一棵足够展示所有节点的树图

**Comment by Yanyan-Wang** [comment]
其实外容器小一些，然后画布大一些，就可以利用浏览器的滚动条了嘛
