### ISSUE TITLE
有办法做 圆形嵌套节点视图吗？

### ISSUE THREAD

**Issue by steveyang331** [antvis/G6#2545]
类似这样的。

https://nivo.rocks/bubble

有一个类似的视图 ，叫 compound nodes, 但它是 长方形的。 

![image](https://user-images.githubusercontent.com/16850883/104446598-a89a1f80-55d5-11eb-973e-f855d3bc1205.png)

有办法做 **圆形**+嵌套+节点视图吗？

**Comment by Yanyan-Wang** [comment]
https://g6.antv.vision/zh/examples/interaction/combo#circle

**Comment by steveyang331** [comment]
G6 貌似是我所知道的 唯一一个支持 圆形 嵌套节点视图的。
