### ISSUE TITLE
有办法自定义combo在collapse时的图形和样式吗

### ISSUE THREAD

**Issue by CathyZYF** [antvis/G6#2546]
我们有这样一个拓扑图的需求，拓扑图上有很多节点，节点用字体图标来实现，有一种节点(子网)可以展开，展开后把子网内部的节点呈现出来，
如果用combo来实现这一功能，在节点闭合的时候，如何自定义其样式为一个节点（字体图标）呢？

**Comment by Yanyan-Wang** [comment]
自定义 combo ，然后和这个例子里更新 + 与 - 类似，在 afterUpdate 里面去根据当前是展开还是收起状态，修改图形
https://g6.antv.vision/zh/examples/interaction/combo#cCircle

**Comment by CathyZYF** [comment]
> 自定义 combo ，然后和这个例子里更新 + 与 - 类似，在 afterUpdate 里面去根据当前是展开还是收起状态，修改图形
> https://g6.antv.vision/zh/examples/interaction/combo#cCircle

谢谢反馈，我刚上手G6不久，还想问一下，在afterUpdate里可以做到隐藏/显示一部分shape吗？或者能提供一个修改图形的实例代码吗？

**Comment by Yanyan-Wang** [comment]
可以的，跟 demo 类似的方法根据 shape 的 name 拿到 shape 之后，调用 shape.hide()  隐藏，shape.show() 显示，shape.remove() 删除

**Comment by CathyZYF** [comment]
```
G6.registerCombo('window',{
    drawShape(cfg,group){
        const self = this
        const style = self.getShapeStyle(cfg)
        const mainRect = group.addShape('rect',{
            attrs:{
                ...style,
                x:0,
                y:0,
                width:style.width,
                height:style.height
            },
            draggable:true,
            name:'combo-keyShape'
        })
        const icon =group.addShape('text',{
              attrs:{
                  x:0,
                  y:0,
                  fill:'#1296db',
                  fontSize: 50,
                  lineHeight:50,
                  textBaseline: 'middle',
                  text:'\uea01',
                  fontFamily:'phoenix-icon'
              },
              draggable:true,
              name:'combo-icon'
          })
        return mainRect
    },
    afterUpdate(cfg,combo){
        const self = this
        const group = combo.get('group');
        const mainRect = group.find((ele) => ele.get('name') === 'combo-keyShape');
        const icon = group.find((ele) => ele.get('name') === 'combo-icon');
        if(cfg.collapsed){
            mainRect.hide()
            icon.show()
        }else {
            mainRect.show()
            icon.hide()
        }
    }
},'rect')
```

以上是我的代码，在闭合状态下将mainRect这个keyShape隐藏了，现在的问题，闭合状态下拖拽combo元素，画布上出现重影，请问这个和我把keyShape隐藏了有关系吗？

**Comment by Yanyan-Wang** [comment]
嗯嗯是的，因为 keyShape 决定了元素的 bbox，然后局部渲染是根据 bbox 来确定哪一块内容需要更新，keyShape 被隐藏之后可能就导致 bbox 计算错误了。你试一下把 keyShape 替换掉呢？

**Comment by CathyZYF** [comment]
好像不对，我把afterUpdate里
```
 // if(cfg.collapsed){
  //     mainRect.hide()
  //     icon.show()
  // }else {
  //     mainRect.show()
  //     icon.hide()
  // }
```
这段隐藏keyShape的代码注销了，再回到画布上，还是有重影的

**Comment by Yanyan-Wang** [comment]
提供复现在线最小 demo 我看一下吧

**Comment by CathyZYF** [comment]
[https://codepen.io/cathyzyf/pen/MWjzoaz](url)

似乎和添加了closeMarker和openMarker有关

**Comment by CathyZYF** [comment]
刚才查看了其他issue，把局部渲染关闭就好啦
`graph.get('canvas').set('localRefresh', false);`

**Comment by Yanyan-Wang** [comment]
如果你数据量小的话没什么问题。数据量比较大的情况下，开启局部渲染性能会好一些。有重影的问题可以再复现一下，我看看具体是因为什么

**Comment by CathyZYF** [comment]
> 如果你数据量小的话没什么问题。数据量比较大的情况下，开启局部渲染性能会好一些。有重影的问题可以再复现一下，我看看具体是因为什么

谢谢你的回应，我在上面已经把demo的url放出来了

**Comment by Yanyan-Wang** [comment]
我看了一下你的 demo ，应该是你 addShape('marker' 的时候没有指定 r 造成的，如果你不希望这个 marker 显示，可以用 shape.hide 来隐藏，不要不写 r 哈，因为这些是必要的参数，如果不写就会造成 bbox 计算失败
