### ISSUE TITLE
工具方法 Util示例代码错误

### ISSUE THREAD

**Issue by C-Hungry** [antvis/G6#2548]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g6.antv.vision/zh/docs/api/Util](https://g6.antv.vision/zh/docs/api/Util)

### Steps to reproduce
进入工具方法 Util

G6.Uitl.processParallelEdges(data.edges, offsetDiff, multiEdgeType, singleEdgeType, loopEdgeType);

这句话G6.Uitl错误，应为G6.Util

| Environment | Info |
|---|---|
| g6 | 4.1.1 |
| System | - |
| Browser | - |

**Comment by Yanyan-Wang** [comment]
好的谢谢

**Comment by Yanyan-Wang** [comment]
已修复哈
