### ISSUE TITLE
求教：TreeGraph的height和width是否可以动态控制大小呢？也就是画布的大小动态控制？

### ISSUE THREAD

**Issue by BabyMing** [antvis/G6#2549]

**Comment by Yanyan-Wang** [comment]
graph.changeSize https://g6.antv.vision/zh/docs/api/graphFunc/transform/#graphchangesizewidth-height

TreeGraph 继承 Graph

**Comment by BabyMing** [comment]
我已经找到changeSize 这支api，但是 我在react中动态改变大小之后，会生成多个图？有解法吗？
