### ISSUE TITLE
怎么限制一个锚点只能链接出来一条线？

### ISSUE THREAD

**Issue by yumenglong** [antvis/g6#255]
例如：锚点A上链接到了节点B上以后，则锚点A 就不能再链接到其他节点上。
官方给的linkable，是不允许线被链接到
![qq 20180601154124](https://user-images.githubusercontent.com/17467365/40828154-663dc580-65b2-11e8-84c6-0e5bf330ea49.png)

**Comment by TomHuangCN** [comment]
这个 g6-editor 1.0 会给出解决方案
