### ISSUE TITLE
polyline 路径获取

### ISSUE THREAD

**Issue by Hejifei** [antvis/G6#2550]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g6.antv.vision/zh/examples/item/customEdge#customPolyline2](https://g6.antv.vision/zh/examples/item/customEdge#customPolyline2)

### Steps to reproduce
你好 我想实现 plyline拖拽的功能，但是我不知道如何获取polyline当前的路线

| Environment | Info |
|---|---|
| g6 | 4.1.0 |
| System | mac |
| Browser | chrome |

**Comment by Yanyan-Wang** [comment]
你需要从哪里获取？从边的 item 获取的话，item.getKeyShape().attr('path') 是当前边的 path

**Comment by Hejifei** [comment]
好的 谢谢 我想问下 想实现polyline拖拽 我要用到这个例子中的
https://g6.antv.vision/zh/examples/item/defaultEdges#polyline3
controlPoints嘛
我的实现流程是 edge:mouseenter 添加节点拖拽，然后修改path赋值给 controlPoints 嘛 有别的简便点的方法嘛

**Comment by Yanyan-Wang** [comment]
如果是非常重度的图编辑需求，比较建议用 X6 实现 https://x6.antv.vision/。G6 还是更偏向于图展示与分析的场景，对于较大规模的图性能好一些。

**Comment by Hejifei** [comment]
好的 谢谢
