### ISSUE TITLE
设置双击 Combo 收起和展开 Combo时不重新布局报错

### ISSUE THREAD

**Issue by DankeF** [antvis/G6#2551]
版本：G6 4.1.1

我在modes的default里面设置双击 Combo 收起和展开 Combo时不重新布局报错：

![image](https://user-images.githubusercontent.com/29647627/104571243-d3e04580-568d-11eb-8d8e-c51cca529962.png)

但是这个设置是可以生效的，原因是ModeOption类型中没有relayout属性。希望可以在ModeOption中添加relayout属性：
`relayout?: boolean`

**Comment by Yanyan-Wang** [comment]
好的，只是 ts 报错是吧，下个小版本加上。

**Comment by DankeF** [comment]
> 好的，只是 ts 报错是吧，下个小版本加上。

对，只是ts报错，麻烦了。

**Comment by Yanyan-Wang** [comment]
v4.1.3 已修复
