### ISSUE TITLE
当线设置流动动画时，多节点的树图展开或收起有明显的抖动现象，节点有动画时，也有这样的问题

### ISSUE THREAD

**Issue by 52jaden** [antvis/G6#2553]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/epic-firefly-y8eik?file=/index.js)

### Steps to reproduce
在官方示例的紧凑树上添加了线的动画，展开或收时，出现明显的抖动现象
在我之前用的3.0.x的老版本包时， 没有这个问题，升级后的版本都有

| Environment | Info |
|---|---|
| g6 | 4.1.1 |
| System | mac windows |
| Browser | 常用浏览器都是这样 |

**Comment by d623141153** [comment]
这个问题，有进展吗

**Comment by Yanyan-Wang** [comment]
建议在展开收起动作前后暂停和继续动画
```
  graph.on('node:mousedown', e => {
    graph.getEdges().forEach(edge => edge.getKeyShape().pauseAnimate())
  })
  graph.on('collapseitem', e => {
    graph.getEdges().forEach(edge => edge.getKeyShape().resumeAnimate())
  })
```
