### ISSUE TITLE
polyline bug

### ISSUE THREAD

**Issue by Didiwei1314** [antvis/G6#2554]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dreamy-kalam-9rv9k?file=/index.js)

### Steps to reproduce
3.8.0及以上版本，新创建的node坐标为负数时，polyline连线错位

| Environment | Info |
|---|---|
| g6 | 4.1.1 |
| System | - |
| Browser | - |

**Comment by Yanyan-Wang** [comment]
v4.1.7 修复了
