### ISSUE TITLE
圆环图在Minimap中不居中

### ISSUE THREAD

**Issue by BG5FD** [antvis/G6#2555]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/admiring-beaver-n9s6j?file=/index.js:0-5829)

### Steps to reproduce
圆环图在Minimap中不居中

| Environment | Info |
|---|---|
| g6 | 4.1.1 |
| System | win10 |
| Browser | chrome v87 |

![image](https://user-images.githubusercontent.com/27286190/104691683-a228b680-5741-11eb-9c30-196c0c1ae5d1.png)

**Comment by Yanyan-Wang** [comment]
谢谢，下个小版本将会修复

**Comment by Yanyan-Wang** [comment]
v4.1.3 已修复
