### ISSUE TITLE
使用 registerEdge 报 cannot read offset of undefined

### ISSUE THREAD

**Issue by fengChongxiu** [antvis/G6#2556]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/aged-fast-1wk53?file=/index.js)

### Steps to reproduce
直接打开页面就可以看到

| Environment | Info |
|---|---|
| g6 | 4.1.1 |
| System | - |
| Browser | - |

---
routeCfg: {
  offset: 0
}
在 options 里增加上述配置就可以了，虽然不知道 routeCfg 是什么意思，建议完善下文档

**Comment by Yanyan-Wang** [comment]
好的。其实是因为内置 polyline 的 options 会有一个 routeCfg 配置项是存储了默认的路径路由的一些参数， 通过 registerEdge 继承了 polyline 且复写了 options，从你写的 options 取到的 routCfg 是 undefined，再从里面取属性就会报错了。我在 G6 内部判空处理一下，下个小版本修复。

**Comment by Yanyan-Wang** [comment]
v4.1.4 已修复
