### ISSUE TITLE
Ability to resize graph canvas on the fly

### ISSUE THREAD

**Issue by 1994benc** [antvis/G6#2558]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
If we could resize the graph canvas on the fly and have its content be responsive, we would be able to use G6 graphs in re-sizable containers. For example, in a dashboard that allows users to resize graph containers. The graph then should responds to the new size. 

Currently, we could only re-create the graph when the container's size changes, which is not desirable because it's impossible to have nodes and edges animate into their new positions when the canvas size changes.

### What does the proposed API look like?
Let graph be an instance of a G6 Graph.
graph.resizeCanvas(newWidth: number, newHeight: number)

OR
Since the graph's width and height are specified in it's Graph Options, we could let users update them on the fly without recreating a new instance of G6 Graph, like this:

graph.updateGraphOptions(newGraphOptions: GraphOptions)

**Comment by Yanyan-Wang** [comment]
There is an API `graph.changeSize(width, height)` which can be called in the listener of `window.onresize` just like every demo in the website. e.g. line 601 in https://g6.antv.vision/zh/examples/case/decisionTree#index
