### ISSUE TITLE
2群满了希望再增加一个群

### ISSUE THREAD

**Issue by SOVLOOKUP** [antvis/G6#2560]

**Comment by Yanyan-Wang** [comment]
由于人力有限，群里答疑已经无法维护，所以决定不再新建群里。如有问题请在 GitHub Issue 中提出。

**Comment by Yanyan-Wang** [comment]
并一定要提供最小在线复现 demo 哦

**Comment by baizn** [comment]
G6 两个答疑群里面都会有部分人员会不定期退出，申请加入即可，申请里面稍微填写一下，审核的时候会让真正有业务需求的人员优先加入。
