### ISSUE TITLE
给tooltip里面的内容 设置点击跳转事件 出现无法触发问题

### ISSUE THREAD

**Issue by ahouvideo** [antvis/G6#2561]
需要给tooltip里面的提示内容 设置点击跳转事件， 会出现稍微离开一下节点后提示框无法显示 从而 导致提示框内容的点击事件无法触发。请问这个问题有处理方法吗

**Comment by Yanyan-Wang** [comment]
tooltip 设计用意就是为了 hover 节点出现，移出就消失的。我理解你的需求应该是右击 contextmenu 更适用 https://g6.antv.vision/zh/examples/tool/contextMenu#contextMenu。

或者就是自己监听 node:mouseenter 去添加一个 DOM，然后再根据你想要的时机隐藏这个 DOM。交互效果类似 AntV 官网第二屏的树图叶子节点 hover 出现的卡片 https://antv.vision/zh。
其代码在 https://github.com/antvis/antvis.github.io/blob/b9e1f5fe87de991b77509e03c740893a3a7bd352/site/components/DecisionTree/DecisionTree.tsx#L809
