### ISSUE TITLE
combo内存在空的子combo时，展开收缩外层combo出现错误

### ISSUE THREAD

**Issue by CathyZYF** [antvis/G6#2562]
- **G6 Version**: 4.1.1
- **Platform**: codePen
- **CodePen Link**:https://codepen.io/cathyzyf/pen/JjRxREK?editors=1111

如codePen示例所示，外层combo(ID:2044)中包裹了一个空的子combo(ID:2046)，此时双击外层combo，收缩后视图出现错误，无法还原。

**Comment by Yanyan-Wang** [comment]
谢谢，下个小版本修复

**Comment by Yanyan-Wang** [comment]
v4.1.2 已修复
