### ISSUE TITLE
克隆g6项目后，执行yarn bootstrap 遇到问题

### ISSUE THREAD

**Issue by 2012shenghua** [antvis/G6#2564]
fatal error: 'vips/vips8' file not found

**Comment by 2012shenghua** [comment]
![Uploading image.png…]()

**Comment by 2012shenghua** [comment]
![image](https://user-images.githubusercontent.com/15325522/104891372-cd164300-59ab-11eb-9c45-ffaaa182c203.png)

**Comment by 2012shenghua** [comment]
带佬帮忙看下

**Comment by 2012shenghua** [comment]
`fatal error: 'vips/vips8' file not found`

**Comment by 2012shenghua** [comment]
`warning "workspace-aggregator-bc8a3b66-6cc3-4deb-a69b-6c05e78decb7 > @antv/g6-core > father > @storybook/theming > @emotion/styled > @emotion/styled-base@10.0.31" has unmet peer dependency "react@>=16.3.0".
[4/4] 🔨  Building fresh packages...
[15/20] ⠠ sharp
[-/20] ⠠ waiting...
[-/20] ⠠ waiting...
[-/20] ⠠ waiting...
error /Users/hua/pdd/project/G6/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments: 
Directory: /Users/hua/pdd/project/G6/node_modules/sharp
Output:
info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.5/libvips-8.10.5-darwin-x64.tar.br
ERR! sharp read ECONNRESET
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/install for required dependencies
gyp info it worked if it ends with ok
gyp info using node-gyp@4.0.0
gyp info using node@15.5.1 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/Users/hua/pdd/project/G6/node_modules/libnpm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/hua/pdd/project/G6/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/hua/pdd/project/G6/node_modules/libnpm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/hua/.node-gyp/15.5.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/hua/.node-gyp/15.5.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/hua/pdd/project/G6/node_modules/libnpm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/hua/.node-gyp/15.5.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/hua/pdd/project/G6/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
  LIBTOOL-STATIC Release/nothing.a
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
../src/common.cc:24:10: fatal error: 'vips/vips8' file not found
#include <vips/vips8>
         ^~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/sharp/src/common.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/hua/pdd/project/G6/node_modules/libnpm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (node:events:376:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:284:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/hua/.nvm/versions/node/v15.5.1/bin/node" "/Users/hua/pdd/project/G6/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/hua/pdd/project/G6/node_modules/sharp




Process stalled
Active handles:
  - WriteStream
  - WriteStream
  - ReadStream
  - Socket
  - Socket
  - ChildProcess
lerna ERR! yarn install --mutex network:42424 --non-interactive --no-package-lock --no-ci exited 1 in 'g6'
lerna ERR! yarn install --mutex network:42424 --non-interactive --no-package-lock --no-ci exited 1 in 'g6'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by Yanyan-Wang** [comment]
你是怎么运行的？

**Comment by 2012shenghua** [comment]
> 你是怎么运行的？
我看是lerna项目，就找到package.json里执行
`yarn bootstrap`
和`npm run bootstrap`
都不行

**Comment by Yanyan-Wang** [comment]
先安装一下，然后再 bootstrap

1. npm i
2. npm run bootstrap
3. npm run build:all

**Comment by 2012shenghua** [comment]
按照步骤执行，npm run bootstrap 还是遇到这个问题了

**Comment by Yanyan-Wang** [comment]
你看下是否有 yarn.lock 文件，删掉这个，然后分别运行 npm run clean，npm run clean:modules，然后再试一下上面的步骤。不行的话，看一下这个 issue 呢 https://github.com/lovell/sharp/issues/1882#issuecomment-534266128

**Comment by 2012shenghua** [comment]
感谢帮助，项目已经安装了
不过在在site 里面运行 npm start 时遇到个问题

**Comment by 2012shenghua** [comment]
![image](https://user-images.githubusercontent.com/15325522/105660045-21b64280-5f05-11eb-89c8-f5b8a067389d.png)

**Comment by 2012shenghua** [comment]
@Yanyan-Wang

**Comment by 2012shenghua** [comment]
已解决，gatsby 从2.31.1 降到2.31.0 解决了，不过保留对于这个包版本的疑问

**Comment by Yanyan-Wang** [comment]
感谢你提出的问题和方案。暂时先关闭了
