### ISSUE TITLE
新增边的层级问题 加了combo之后新增边的层级会在初始化边的下面

### ISSUE THREAD

**Issue by JadeAgile** [antvis/G6#2565]
codepen链接：https://codepen.io/JadeAgile/pen/xyJgRG
问题描述：createCombo之后新增的边会在初始化边的下面 注释掉createCombo之后线的层级正常
需求：希望createCombo之后保持线的层级
请问有什么解决办法吗？

**Comment by Yanyan-Wang** [comment]
有 combo 的情况下，为了保证节点和 combo 层级正常，应该在实例化图的时候设置 groupByTypes: false 

有了 combo 之后，combo 内部节点的层级将会被提升，与之相关的边的层级也会随之变化。

如果想单独提升某个节点/边层级，可以用 item.toFront()， item.toBack()。

**Comment by JadeAgile** [comment]
> 有 combo 的情况下，为了保证节点和 combo 层级正常，应该在实例化图的时候设置 groupByTypes: false
> 
> 有了 combo 之后，combo 内部节点的层级将会被提升，与之相关的边的层级也会随之变化。
> 
> 如果想单独提升某个节点/边层级，可以用 item.toFront()， item.toBack()。

感谢回复，我的问题解决啦~
