### ISSUE TITLE
Combos with comboForce layout performance issue

### ISSUE THREAD

**Issue by goseign** [antvis/G6#2567]
用 comboForce layout 时, 如果节点数超过150用了combos ，图就不会显示出来，JS console 也没有错误提示

**Comment by Yanyan-Wang** [comment]
请给出最小复现的在线 demo

**Comment by goseign** [comment]
I forked from your online custom Combo sample:
https://codesandbox.io/s/elated-sammet-nw8vj

It has only 99 nodes.

If you remove the layout config (i used 'comboForce' type), it can show, but the layout is not idea.

**Comment by baonanhai** [comment]
我这边使用的时候也是，comboForce布局默认的情况下，combo和node都糊在一起了，打开防止combo和node重叠后，页面会失去响应，且过一段时间恢复后，页面也是空白的。node数量大概300+，边的数量是600+

**Comment by ohhoney1** [comment]
特别是边稍微多一点时，50条边就绘制不出来了

**Comment by Yanyan-Wang** [comment]
尝试最新的 combo 布局算法： comboCombined，可以自由配置内部、外部布局
demo：http://g6.antv.antgroup.com/examples/net/comboLayout/#comboCombined
文档：http://g6.antv.antgroup.com/api/graphlayout/combocombined
