### ISSUE TITLE
【BUG】G6设置边 label style background 后，再次更改节点位置会导致label background位置计算错误！

### ISSUE THREAD

**Issue by Heqingsong** [antvis/G6#2568]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/musing-carson-u9voo?file=/index.html)

### Steps to reproduce
链接打开后能直接看到。

| Environment | Info |
|---|---|
| g6 | 4.1.3 |
| System | MAC OS |
| Browser | 版本 88.0.4324.27 |

---
因需求需要动态调整节点位置，但因两点之间关系上有label需要显示，故重现该问题！

**Comment by Yanyan-Wang** [comment]
v4.1.3 已解决，cdn 地址 https://gw.alipayobjects.com/os/antv/pkg/_antv.g6-4.1.3/dist/g6.min.js
