### ISSUE TITLE
drag-canvas behavior 配置 shouldBegin 不生效，在 return false 的情况下还是能拖动 canvas

### ISSUE THREAD

**Issue by fengChongxiu** [antvis/G6#2571]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/friendly-cloud-oj35d?file=/index.js)

### Steps to reproduce
打开页面，拖动 canvas 即可复现

| Environment | Info |
|---|---|
| g6 | 4.1.4 |
| System | - |
| Browser | - |

**Comment by Yanyan-Wang** [comment]
谢谢，下个小版本会修复

**Comment by Yanyan-Wang** [comment]
v4.1.5 已修复
