### ISSUE TITLE
De facto way of dynamically changing data in dagre graph

### ISSUE THREAD

**Issue by andreasnett** [antvis/G6#2572]
Hello,
thanks for this library, it is very nice. 
I'm trying to implement G6 into my react application where the nodes that are contained in the graph will be updated by user interaction with the app.
I got it working like this 
```
function App() {
  const ref = useRef();
  const [data, setData] = useState(data_import);
  const [graph, setGraph] = useState();
  useEffect(() => {
    const graf = new G6.Graph({
      container: ref.current,
      width: 1000,
      height: 600,
      layout: {
        type: "dagre",
        rankdir: "TB", // The center of the graph by default

        nodesep: 10,
        ranksep: 20,
        controlPoints: true,
      },
    });
    graf.data(data);
    graf.render();
    setGraph(graf);
  }, []);
  useEffect(() => {
    if (graph) graph.changeData(data);
  }, [data]);

  const handleClick = () => {
    setData({
      ...data,
      nodes: [...data.nodes, { id: "node7", label: "node7" }],
    });
    console.log(graph);
  };
  return (
    <div className="App">
      <header className="App-header">
        <div ref={ref}></div>
        <button onClick={handleClick}>Click me</button>
      </header>
    </div>
  );
}

export default App;
```

However, I feel like this is quite the hacky solution and am therefore wondering if there is any better way of doing this?

**Comment by Yanyan-Wang** [comment]
If you are adding a few items into the graph, call graph.addItem instead. For updating some items, call graph.updateItem.

graph.changeData is suitable for changing the whole dataset.

**Comment by andreasnett** [comment]
The question here was rather the way the graph is initialized. It seems suboptimal

**Comment by Yanyan-Wang** [comment]
Why do you think it is a hacky solution?
