### ISSUE TITLE
menu定位问题，某些情况下会溢出容器

### ISSUE THREAD

**Issue by aMiing** [antvis/G6#2574]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
在图上右键，会出现menu溢出的问题。原因可能是menu只会出现在鼠标的右上或者右下，在适当情况下应该适当平移，比如上面或者下面溢出的情况下。如图所示：
![image](https://user-images.githubusercontent.com/39857637/105135439-fc9f8980-5b2a-11eb-9c97-687da48e38db.png)

相同的菜单在cytoscape上会平移。
希望能够修改，谢谢！

| Environment | Info |
|---|---|
| g6 | 4.1.4 |
| System | - |
| Browser | - |

**Comment by baizn** [comment]
没有考虑到这种情况，我们后面修复一下，如果你有兴趣的话，欢迎提个 PR

**Comment by Yanyan-Wang** [comment]
目前 menu 插件已增加躲避上下左右边界的逻辑，如果菜单太长还是出现超出容器的情况，可以考虑自己增加 DOM，浮于最上层，DOM 挂载方式参考：http://g6.antv.antgroup.com/manual/advanced/coordinate-system
