### ISSUE TITLE
文档问题：图元素item类相关文档缺失

### ISSUE THREAD

**Issue by qaz19971125** [antvis/G6#2575]
`Item`是`G6`中绘图元素实例，在文档中多次出现。

例如：
1. 自定义元素 `G6.registerX()`中的`setState(name, value, item)`
2. 自定义`Behavior`中的事件处理函数的回调参数`evt.item`
3. `graph.on(eventName, (evt) => {})`中的`evt.item`

相关文档在项目中是存在的，但是在文档网站上并没有被渲染出来

![Snipaste_2021-01-20_16-37-30](https://user-images.githubusercontent.com/48019473/105151167-9a518380-5b40-11eb-8798-b35f25adbfa7.png)
![Snipaste_2021-01-20_16-41-32](https://user-images.githubusercontent.com/48019473/105151175-9c1b4700-5b40-11eb-91d7-13682c766a1a.png)

**Comment by Yanyan-Wang** [comment]
好的，谢谢，会尽快修复

**Comment by Yanyan-Wang** [comment]
官网已更新，https://g6.antv.vision/zh/docs/api/Items/itemMethods
