### ISSUE TITLE
Error: Failed to resolve entry for package "@antv/g6-plugin". The package may have incorrect main/module/exports specified in its package.json

### ISSUE THREAD

**Issue by tianxing0923** [antvis/G6#2577]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/antvis/G6/tree/master/packages/plugin](https://github.com/antvis/G6/tree/master/packages/plugin)

### Steps to reproduce
使用vite构建工具，启动报 Failed to resolve entry for package "@antv/g6-plugin". The package may have incorrect main/module/exports specified in its package.json 错误

去node_modules/@antv/g6-plugin查看package.json，里面有配置"module": "es/index.ts"，但目录下没有es文件夹

| Environment | Info |
|---|---|
| g6 | 4.1.4 |
| System | Windows 10 |
| Browser | Chrome 87.0.4280.141 |

**Comment by Yanyan-Wang** [comment]
fixed by v4.1.5
