### ISSUE TITLE
能否提供chart-node-g6的cdn引用包？或者单独的js？

### ISSUE THREAD

**Issue by WongBaba** [antvis/G6#2578]
能否提供chart-node-g6的cdn引用包？或者单独的js？

**Comment by WongBaba** [comment]
![image](https://user-images.githubusercontent.com/44690857/105208726-f8538a80-5b83-11eb-87a7-77deb8db12c2.png)
尝试npm安装也失败了，公司内网项目没有使用webpack，都是使用的离线js，刚好卡在这一步了

**Comment by baizn** [comment]
https://gw.alipayobjects.com/os/antv/pkg/_antv.chart-node-g6-0.0.4/dist/g6ChartPlugin.min.js
