### ISSUE TITLE
在combo中存在空的子combo，在保存图时，子combo没有children

### ISSUE THREAD

**Issue by CathyZYF** [antvis/G6#2580]
[https://codepen.io/cathyzyf/pen/MWjzoaz](https://codepen.io/cathyzyf/pen/MWjzoaz)

如实例所示，combo1中包含一个空的combo2,将节点拖拽进combo2，点击保存后，控制台输出的combo2数据里没有children

**Comment by Yanyan-Wang** [comment]
其实原本 combos 里面就不会有 children，只是内部用于计算挂到数据上的。graph.save() 的数据结构和 graph 读入的数据结构一样的，combo 以及 node 的嵌套关系是根据 node 中的 comboId 或 combo 的 parentId 来准确表达的。
