### ISSUE TITLE
demo里节点动画的inner animate不会动

### ISSUE THREAD

**Issue by Veigar-C** [antvis/G6#2582]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g6.antv.vision/zh/examples/scatter/node#node](https://g6.antv.vision/zh/examples/scatter/node#node)

### Steps to reproduce
就是图片转动那个，以为是线上问题，放到本地也不行，甚至拖拽改节点会卡顿

| Environment | Info |
|---|---|
| g6 | 4.1.4 |
| System | win10 |
| Browser | chrome |

**Comment by Veigar-C** [comment]
再问个这种图片动画的节点是无法拖拽的吗

**Comment by Yanyan-Wang** [comment]
把 line198 的 `const matrix = Util.mat3.create();` 改成`const matrix = [1, 0, 0, 0, 1, 0, 0, 0, 1]` 即可。应该是 Util.mat3.create 返回值的类型问题。

可以拖动，自定义节点的时候给需要相应拖拽的图形加上  draggable: true，与 attrs 平级
