### ISSUE TITLE
Uncaught TypeError: Cannot read property 'set' of undefined

### ISSUE THREAD

**Issue by ainihaotian** [antvis/G6#2583]
TypeError: Cannot read property 'set' of undefined
e.innerAddChild

.yarn/cache/@antv-g6-npm-4.1.4-6c204a2b69-c76dc8eb97.zip/node_modules/@antv/g6/dist/g6.min.js:16
请教下，项目报这个错，不清楚是什么原因，是不是g6的问题。

**Comment by Yanyan-Wang** [comment]
需要提供在线复现 demo

可能是你的数据中 id 不是唯一的字符串

**Comment by Yanyan-Wang** [comment]
解决了没有？

**Comment by ainihaotian** [comment]
非常感谢，解决了，有两个id是undefined导致的



---Original---

**Comment by Yanyan-Wang** [comment]
好的，那就关掉咯

**Comment by ainihaotian** [comment]
好的谢谢



---Original---
