### ISSUE TITLE
移动端缩放功能频繁出现向四周漂移的情况

### ISSUE THREAD

**Issue by Way-Ho** [antvis/G6#2585]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/relaxed-cohen-ednql?file=/src/index.js)

### Steps to reproduce
只需要在移动端开启缩放功能就可以复现，多试几次会出现，pc端是正常的，移动端频繁出现缩放后漂移的情况，初步判断是拖拽功能影响了，目前处于无法使用的情况

| Environment | Info |
|---|---|
| g6 | 4.1.4 |
| System | ios |
| Browser | 微信 |

**Comment by Yanyan-Wang** [comment]
fixed by v4.1.9
