### ISSUE TITLE
请问有网友相互交流学习的作品展示社区网站吗？

### ISSUE THREAD

**Issue by Zhouqchao** [antvis/G6#2586]
请问有没有类似echarts网友作品展示的社区网站[Echarts Gallery](https://www.makeapie.com/explore.html)？方便大家分享学习和实现各种丰富有趣的效果。谢谢。
![image](https://user-images.githubusercontent.com/24250131/105437459-16141300-5c9c-11eb-902e-919f59a25083.png)

**Comment by Yanyan-Wang** [comment]
暂时没有，如果有意向的话，非常欢迎开 issue 放上在线 demo，我们择优放到官网上，也会标识上传者名

**Comment by Yanyan-Wang** [comment]
类似 https://g6.antv.vision/zh/examples/item/label#copyLabel ，在代码中 @ 了作者
