### ISSUE TITLE
怎么在 svelte 中使用 G6 ? 

### ISSUE THREAD

**Issue by steveyang331** [antvis/G6#2590]
svelte  https://svelte.dev/ 

谢谢

**Comment by Yanyan-Wang** [comment]
G6 就是把图渲染在一个 Canvas 标签上，如果它支持 Canvas 标签的话，应该没有什么区别吧

**Comment by baizn** [comment]
G6 是个 JS 库，在任何框架中使用时按照普通的 JS 库的方式使用就可以，参考这里：https://codesandbox.io/s/old-cloud-qrcb6?file=/App.svelte
