### ISSUE TITLE
如何控制 dagre 节点的层次？

### ISSUE THREAD

**Issue by huntye1** [antvis/G6#2592]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
例子：https://codesandbox.io/s/gracious-butterfly-sru9o?file=/index.js 
如何控制1、4、7在同一层次。

### What does the proposed API look like?
如果有的话，望告知，如果没有期望有相关API可以控制。

**Comment by baizn** [comment]
没有相关 API 控制，另外 1 4 7 本身就不在同一层次啊，7 是 4 的子级。

**Comment by Yanyan-Wang** [comment]
duplicated to https://github.com/antvis/G6/issues/2245
