### ISSUE TITLE
请问,导出图片模糊需要有什么解决方案吗?

### ISSUE THREAD

**Issue by lytlucky** [antvis/G6#2593]
graph.downloadImage("graph", "png", "#ffffff");

**Comment by Yanyan-Wang** [comment]
实例化图的时候设置 pixelRatio: 2，还是模糊的话可以逐渐增大试试

**Comment by Yanyan-Wang** [comment]
解决了么？

**Comment by mostopalove** [comment]
@Yanyan-Wang Can you explain mechanism of working with pixelRatio in new version as https://g6.antv.vision/en/docs/manual/FAQ/upgradeGuide#pixelratio
I have a problem with devices using the system's default zoom. The image looks blurry.

**Comment by Yanyan-Wang** [comment]
> @Yanyan-Wang Can you explain mechanism of working with pixelRatio in new version as https://g6.antv.vision/en/docs/manual/FAQ/upgradeGuide#pixelratio
> I have a problem with devices using the system's default zoom. The image looks blurry.

Get the `window.devicePixelRatio` in the rendering engine

**Comment by whathave** [comment]
缩小比例后再下载，图片模糊有什么可以解决的吗
