### ISSUE TITLE
在graph布局后调用fitView无效

### ISSUE THREAD

**Issue by CathyZYF** [antvis/G6#2594]
[https://codepen.io/cathyzyf/pen/vYXwwZm](https://codepen.io/cathyzyf/pen/vYXwwZm)

如示例所示，点击“布局”按钮后自动调整为环形布局，此时我在afterlayout的回调里设置了graph.fitView，但貌似没有起作用，必须在下次手动点击“手动适应”后才真正让布局自适应画布

**Comment by Yanyan-Wang** [comment]
谢谢，暂时可以通过下面这种方式实现，下个小版本修复一下：

```
graph.on('afterlayout',()=>{
  setTimeout(() => {
    graph.fitView()
  }, 0)
})
```

**Comment by Yanyan-Wang** [comment]
你的 demo 貌似被改过了，看不到原来的复现了，麻烦再提供一下

**Comment by CathyZYF** [comment]
> 你的 demo 貌似被改过了，看不到原来的复现了，麻烦再提供一下

改回来了，点进去看看吧

**Comment by Yanyan-Wang** [comment]
fixed by 4.2.2
