### ISSUE TITLE
registerNode的option与extendShapeType合并

### ISSUE THREAD

**Issue by q774221810** [antvis/G6#2595]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现在的option是直接覆盖extendShapeType，很多属性需要自己补上，不能采用默认

### What does the proposed API look like?
能采用extendShapeType的默认值

**Comment by Yanyan-Wang** [comment]
你的意思是你在自定义节点时写的 options 希望和被继承的内置节点的 options 做 deep mix 是吗

**Comment by q774221810** [comment]
@Yanyan-Wang 是的

**Comment by q774221810** [comment]
@Yanyan-Wang 我发现有一个getCustomConfig，这个应该可以了
