### ISSUE TITLE
Ability to update all node's properties at once without freezing the canvas

### ISSUE THREAD

**Issue by 1994benc** [antvis/G6#2596]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This feature would improve performance when there's a need to update all nodes' data and/or properties at once to the same value. For example, I want to be able to update all nodes with a property 'zoomLevel' which corresponds to the level of zoom of the canvas so that all nodes update their font sizes at different zoom levels. Currently I have to loop through all the nodes in the graph and update them using graph.updateItem. This freezes up the canvas when the update is happening.

### What does the proposed API look like?
One possible solution is if there is a way to update defaultNode of the graph. Or an interface attached to the graph instance to update all nodes.

**Comment by Yanyan-Wang** [comment]
You can modify the fontSize in the nodes' data and call graph.refresh to refresh all the items with their data. e.g.

```
data.nodes.forEach(node => {
  node.labelCfg = {
    style: {
      fontSize: 20
     // other configurations for label style
    }
    // other configurations for label
  }
})
graph.refresh()
```
