### ISSUE TITLE
在首次渲染时，afterrender事件的回调没有执行

### ISSUE THREAD

**Issue by CathyZYF** [antvis/G6#2598]
[https://codepen.io/cathyzyf/pen/vYXwwZm](https://codepen.io/cathyzyf/pen/vYXwwZm)

如示例所示，只有当手动调用render方法时，afterrender事件才会调用，并且回调执行了两次
在页面首次渲染时，并未触发afterrender。
ps.最近提了好多issue,都得到了回应，感觉开发团队很认真，谢谢你们的支持^_^

**Comment by pomelo-nwu** [comment]
可以更改下代码执行顺序，afterlayout的emit在布局的时候，因此事件的兼听则明应该在graph.render 之前，否则时间池里没有这个事件，自然用户也监听不到
![image](https://user-images.githubusercontent.com/10703060/105655849-df3c3800-5efb-11eb-9ec0-e4e9890d64fe.png)
