### ISSUE TITLE
更新数据后,边的箭头会消失

### ISSUE THREAD

**Issue by HaHaaaaaaaaaa** [antvis/G6#2599]
使用G6.registerEdge自定义边时加上endArrow: true（开启结尾箭头）
随后更新数据 使用graph.changeData() 图表重新渲染成功，但是边的结尾箭头消失了

**Comment by Yanyan-Wang** [comment]
请给出最小复现在线 demo

**Comment by HaHaaaaaaaaaa** [comment]
> 请指定最小复现在线demo

http://jsrun.net/pwaKp/edit
点击第一个根节点的页 更新数据 然后我的边箭头就消失了

**Comment by Yanyan-Wang** [comment]
底层 svg 渲染引擎有比较多的问题，建议还是使用 canvas 渲染，我看你这里的节点也不复杂，canvas 可以很轻松绘制这样的自定义节点的。点击监听事件也可以通过 node:click 里面判断是否点击的 target 是“页”图形来进行反馈，参见 [响应节点局部事件](https://g6.antv.vision/zh/examples/interaction/partialResponse#partialNode)。而且 canvas 的性能要比 svg 高很多

**Comment by HaHaaaaaaaaaa** [comment]
> 快照svg呈现引擎有比较多的问题，建议还是使用canvas渲染，我看你这里的例程也不复杂，canvas可以很轻松地布局这样的自定义定义的。单击监听事件也可以通过node：click里面判断是否点击的target是“页面”图形来进行反馈，视为[响应的局部事件](https://g6.antv.vision/zh/examples/interaction/partialResponse#partialNode)。而且canvas的性能要比svg高很多
canvas渲染之前试了，右下页数多的时候位置定位不好弄，还有背景画网格的话要怎么用group.addShape('rect', {})画呢？

**Comment by HaHaaaaaaaaaa** [comment]
> 底层 svg 渲染引擎有比较多的问题，建议还是使用 canvas 渲染，我看你这里的节点也不复杂，canvas 可以很轻松绘制这样的自定义节点的。点击监听事件也可以通过 node:click 里面判断是否点击的 target 是“页”图形来进行反馈，参见 [响应节点局部事件](https://g6.antv.vision/zh/examples/interaction/partialResponse#partialNode)。而且 canvas 的性能要比 svg 高很多

canvas渲染之前试了，右下页数多的时候位置定位不好弄，还有背景画网格的话要怎么用group.addShape('rect', {})画呢？

**Comment by Yanyan-Wang** [comment]
shape.getCanvasBBox可以拿到图形的包围盒辅助你定位

背景网格用grid插件
