### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by L-David** [antvis/g6#260]
Is there an English documentation for the library, if not is there any plan to create it?

**Comment by TomHuangCN** [comment]
English documentation work will begin at November this year.

By the way, G6 will open source the day after tomorrow, hha~

**Comment by emilingerslev** [comment]
The project looks very promising, so really look forward to some English resources on it 👍  Will the website also get translated into English?

**Comment by TomHuangCN** [comment]
yes it will
