### ISSUE TITLE
双击事件被单击事件覆盖

### ISSUE THREAD

**Issue by CathyZYF** [antvis/G6#2601]
[https://codepen.io/cathyzyf/pen/GRjbEyP](https://codepen.io/cathyzyf/pen/GRjbEyP)

如demo所示，在combo上双击，会先触发单击事件，从而捕获不到双击事件

建议：判断是否为单击或双击时，是不是应该设置一个时间差，小于时间差的为双击，其余才为单击？

**Comment by Yanyan-Wang** [comment]
根据 MDN 的标准，dblclick 也会触发 click 的，见例子： https://codepen.io/Yanyan-Wang/pen/KKgYvxG?editors=1000

我们和标准保持一致哈

**Comment by 584sentiment** [comment]
我也遇到了同样的问题，双击的时候只触发了两次单击事件，双击事件没有触发，有什么方法可以解决吗，单击和双击事件我都要用到
