### ISSUE TITLE
g6.min.js在ie11下报错： “Proxy”未定义。 @antv/g6版本是4.1.4。

### ISSUE THREAD

**Issue by diangongdianzi** [antvis/G6#2602]

**Comment by diangongdianzi** [comment]
使用@antv/g6 4.1.4版本，在ie11下报错：“Proxy”未定义。

**Comment by baizn** [comment]
ie11 不支持 Proxy 对象，需要配置 polyfill，参考这里https://stackoverflow.com/questions/45285992/es6-proxy-polyfill-for-ie11

**Comment by onlycc** [comment]
> ie11 不支持 Proxy 对象，需要配置 polyfill，参考这里https://stackoverflow.com/questions/45285992/es6-proxy-polyfill-for-ie11

Angular框架该如何配置呢？

**Comment by jeeSolersun** [comment]
@diangongdianzi 您好，请问这个问题解决了没？我的项目使用dva-cli创建，@antv/g6的版本是4.1.7。试过加入babel-polyfill或@babel/polyfill仍未解决，同求解决办法，谢谢！

**Comment by KellenHe** [comment]
@baizn  我也遇到这个问题了，使用babel打包了，还是报proxy不支持，在IE11上，定位是下面的代码
`var Layouts = new Proxy({}, {
  // tslint:disable-line
  get: function get(target, propKey) {
    return getLayoutByName(propKey);
  },
  set: function set(target, propKey, value) {
    registy_registerLayout(propKey, value);
    return true;
  }
});`
