### ISSUE TITLE
Force node position by custom edge

### ISSUE THREAD

**Issue by andreasnett** [antvis/G6#2603]
Hello, I want to implement a custom edge. When two nodes have the relation that causes this type of edge, it is important that they are positioned at the same height.

Is there any way to force the node positioning based on the type of edge? If not, how should I proceed with implementing this?

An alternative solution for me would be that a custom node can consist of independent nodes in such a way that edges can appear from only one of the nodes within as well as the combination of them.

**Comment by Yanyan-Wang** [comment]
You can update the node to a certain position by calling:

```
graph.updateItem(node, {
  x: 100,
  y: 200
}
```

**Comment by andreasnett** [comment]
What about the dagree diagram where x and y positions are given "behind the scenes"? Could I extract the x,y from one node and position the other in accord to this?

**Comment by Yanyan-Wang** [comment]
> What about the dagree diagram where x and y positions are given "behind the scenes"? Could I extract the x,y from one node and position the other in accord to this?



Yes. Just call the `updateItem` any where after layout

**Comment by andreasnett** [comment]
Is there an afterLayoutUpdate or equivalent that I should use? If not, what type of event should I be listening to?

**Comment by andreasnett** [comment]
Doing this seems to have no effect. When console.log'ing the source and target, the only x/y positions I find are inside _cfg: { bboxCache: {}}

**Comment by andreasnett** [comment]
This reinstates the seperation issue I asked about in an earlier thread. Having two nodes n1, n2 positioned next to each other, having a relation from n1 to n3, n3 is by default positioned in the rank below n1 and n2. Moving the node up to the same rank as n1 and n2 (like referenced in this thread), n2 does not change its position

**Comment by Yanyan-Wang** [comment]
> Is there an afterLayoutUpdate or equivalent that I should use? If not, what type of event should I be listening to?

There are several timing events in G6 https://g6.antv.vision/en/docs/api/Event/#timing-events, where you can listen to the  'afterlayout' event by `graph.on('afterlayout', e => {});`

Whether some nodes are positioned in the same level can be told from the y-position in the node models.

Whether two nodes are connected can be told from node.getNeighbors. [getNeighbors API](https://g6.antv.vision/en/docs/api/Items/nodeMethods#nodegetneighborstype)

Just design your own rules for the position adjustment and calculate the new positions in the listener of 'afterlayout'

**Comment by andreasnett** [comment]
I think maybe combos make it easier. But edges with combos as source doesn't sort positioning of target

**Comment by andreasnett** [comment]
https://codesandbox.io/s/jovial-elion-2tf87?file=/index.js can this behavior be changed?

**Comment by andreasnett** [comment]
Another possible solution to my problem:
Polyline intersection of edge1: n1-->n3 and edge2: n2-->n3 can be used if the algorithm could be given a preference for where to put the direction change. I believe this could be implemented here: https://github.com/antvis/G6/blob/04aa3f2a637b1d259ab17dbcc4bdaed4db968c2e/packages/element/src/edges/router.ts#L324

So that, the intersection line in the picture can be moved up.

![Image](https://user-images.githubusercontent.com/42800422/106264995-b632e480-6226-11eb-8416-6b77fe7b5ecc.png)

**Comment by Yanyan-Wang** [comment]
The routes of the edges will not affect the nodes' positions, they are determined by the nodes' positions.

**Comment by Yanyan-Wang** [comment]
Maybe just remove the edges (p1, p3) and (p2, p3) in first time dagre layout, after layout, you could add the edges back by `graph.addItem`.

**Comment by andreasnett** [comment]
Thanks Yanyan, this is really helpful.
Is there any way to move a node out of the document flow? Like position absolute

**Comment by andreasnett** [comment]
It seems I can not find a solution to that. This can however be handled in the `afterlayout`. Causes some more code but it is a functional solution.

**Comment by andreasnett** [comment]
So this only works if you propagate through all nodes that are descendants of descendants of this "combined edge"
