### ISSUE TITLE
当 radius 属性指定比较大时，元素的样式显示不符合预期

### ISSUE THREAD

**Issue by fengChongxiu** [antvis/G6#2604]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/friendly-cloud-oj35d?file=/index.js)

### Steps to reproduce
点开页面即可看到

| Environment | Info |
|---|---|
| g6 | 4.1.4 |
| System | - |
| Browser | - |

**Comment by Yanyan-Wang** [comment]
我看到你 demo 中的样式似乎是正常的，你说的是谁的 radius？边还是节点？不符合预期是啥样？你的预期啥样？

**Comment by fengChongxiu** [comment]
抱歉，开始忘记保存了，现在打开 CodeSandbox 应该可以看到了
在给节点设置一个比较大的 radius 时，节点的圆角样式很奇怪，如下图
![image](https://user-images.githubusercontent.com/17736007/105815681-45a18300-5fee-11eb-8336-8754fdae663e.png)
li
预期的到的是和 dom 一样的效果，如下图
![image](https://user-images.githubusercontent.com/17736007/105815791-6964c900-5fee-11eb-9f55-47761eff4751.png)

**Comment by Yanyan-Wang** [comment]
radius 不要超过 min(width/2, height/2)

**Comment by fengChongxiu** [comment]
这个限制可以通过别的方式绕过去吗？

**Comment by Yanyan-Wang** [comment]
就是在自定义节点的时候判断一下就可以了呀? 暂时没有其他的办法
