### ISSUE TITLE
CompactBox树布局里面的节点折叠后，查找不到被折叠节点

### ISSUE THREAD

**Issue by gymschen** [antvis/G6#2606]
节点加上collapsed属性，折叠后。使用graph.getNodes()，取得所有元素，但是只能拿到没有折叠起来的节点。
请问要怎么拿到所有节点?

**Comment by Yanyan-Wang** [comment]
树折叠之后实际上是 change data 了，图上的节点实例只有目前显示在画布上的节点。可以通过 graph.save() 获得所有的数据。但是实例的话只有画布上的

**Comment by Yanyan-Wang** [comment]
另外，graph.findDataById 可以通过 id 找到相关节点的数据
