### ISSUE TITLE
关于setMode的一个疑问

### ISSUE THREAD

**Issue by Veigar-C** [antvis/G6#2607]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/g6-layout-grid-koe1p)

### Steps to reproduce
demo 可以重现。

是想实现默认鼠标框选节点，然后按住空格拖拽画布 的功能。

但是如果拖拽期间我触发了空格之类的操作，鼠标框选的块不会消失

尝试过调用 render /  refresh / paint 都不太理想

| Environment | Info |
|---|---|
| g6 | 4.1.4 |
| System | win10 |
| Browser | chrome |

**Comment by Yanyan-Wang** [comment]
这个确实应该在 G6 内部做一下处理，下个小版本应该会修复一下。暂时你可以在 setMode 之前调用一下：
```
  const rect = graph.get('canvas').find(e => e.get('name') === 'brush-shape')
  if (rect) rect.remove()
```

手动清除这个图形。graph.paint() 不需要调用
