### ISSUE TITLE
polyline在负坐标中拐点不正确

### ISSUE THREAD

**Issue by guoxiaoman-gxm** [antvis/G6#2608]
通过节点的锚点动态添加polyline时，节点的坐标为正时没有问题，但是在负坐标下会出现拐点错误的情况
![sh](https://user-images.githubusercontent.com/62195286/105847612-c83f3800-6018-11eb-83f8-c3827f9505b2.png)
这是线上实例，麻烦帮忙看一下
https://codesandbox.io/s/fast-fast-4rxc2?file=/index.js

Environment | Info
-- | --
g6 | 4.1.4
System | win10
Browser | chrome

**Comment by guoxiaoman-gxm** [comment]
这是线上实例，麻烦帮忙看一下
https://codesandbox.io/s/fast-fast-4rxc2?file=/index.js

Environment | Info
-- | --
g6 | 4.1.4
System | win10
Browser | chrome

**Comment by Yanyan-Wang** [comment]
谢谢，这是一个已知问题，我们会尽量排期修复。着急的话…暂时先把节点移动到正数坐标下

**Comment by guoxiaoman-gxm** [comment]
辛苦了

**Comment by Yanyan-Wang** [comment]
v4.1.7 修复了
