### ISSUE TITLE
修改自定义combo的配置数据后，视图没有更新

### ISSUE THREAD

**Issue by CathyZYF** [antvis/G6#2609]
[https://codepen.io/cathyzyf/pen/WNGVxxm](https://codepen.io/cathyzyf/pen/WNGVxxm)

如demo所示，图中的combo1是一个自定义的combo,在input里输入新的label名称，点击按钮修改后，combo上方的label没有发生更新。

ps. 在公司代码上测试了一下，视图不更新和执行updateItem后没有走registerCombo里的draw方法有关系，而其他的自定义形状（比如registerNode）在执行updateItem后都调用了对应的draw方法

**Comment by Yanyan-Wang** [comment]
继承了内置 combo 会走被继承 combo 的 update 方法和 drawLabel 方法，如果你想要完全自己画 label，可以复写这两个方法为
```
  drawLabel: () => {},
  update: undefined
```
和 draw 平级

**Comment by CathyZYF** [comment]
谢谢，其实我的主要诉求，让combo随着它的model的更新而刷新，不只是刷新label，还需要刷新整改combo的样式。
请问这个update设为undefined以后，registerCombo里的afterUpdate是不是就不执行了呢

**Comment by Yanyan-Wang** [comment]
> 谢谢，其实我的主要诉求，让combo随着它的model的更新而刷新，不只是刷新label，还需要刷新整改combo的样式。
> 请问这个update设为undefined以后，registerCombo里的afterUpdate是不是就不执行了呢


应该不会，afterUpdate 应该还是会执行的。你 demo 里除了 label 更新有问题外，其他的更新应该会被正确执行。有发现不正常的情况再发一下 demo

**Comment by CathyZYF** [comment]
[https://codepen.io/cathyzyf/pen/WNGVxxm](https://codepen.io/cathyzyf/pen/WNGVxxm)

在这个demo里，我在点击按钮后希望combo收缩时的图标变为红色，结果是没有变色。
在加上update:undefined以后，图标的确变色了，但图形的展示出现了错乱（收缩的图形和展开的图形同时显示出来了）

**Comment by Yanyan-Wang** [comment]
因为你没继承 update，就会执行被继承 combo 的 update 嘛，被继承 combo 的 update 没有使用你这里自己写的颜色属性 itemColor ，你要颜色更新就在 afterUpdate 里面 L138 下加上 fill: cfg.itemColor || '#0080FF'。你自己定义的属性名 G6 不认识的嘛

**Comment by CathyZYF** [comment]
> 因为你没继承 update，就会执行被继承 combo 的 update 嘛，被继承 combo 的 update 没有使用你这里自己写的颜色属性 itemColor ，你要颜色更新就在 afterUpdate 里面 L138 下加上 fill: cfg.itemColor || '#0080FF'。你自己定义的属性名 G6 不认识的嘛

懂了，谢谢！
