### ISSUE TITLE
strokeOpacity 和 opacity 同时设置时，得到的效果有点不符合预期

### ISSUE THREAD

**Issue by fengChongxiu** [antvis/G6#2612]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/friendly-cloud-oj35d?file=/index.js:5033-5035)

### Steps to reproduce
直接建页面代码即可

| Environment | Info |
|---|---|
| g6 | 4.1.4 |
| System | - |
| Browser | - |

---
不知道是不是 bug，期待同时设置了 strokeOpacity 和 opacity 时，strokeOpacity 起作用

**Comment by Yanyan-Wang** [comment]
没有在你的代码中看到有设置透明度

opacity 控制整个图形的透明度，strokeOpacity 控制描边透明度，fillOpacity 控制填充透明度。且 strokeOpacity 和 fillOpacity 优先级高于 opacity。如果同时设置了 opacity 和 strokeOpacity，且没有设置 fillOpacity，表现为填充为 opacity，描边为 strokeOpacity

**Comment by Yanyan-Wang** [comment]
这里可能是 strokeOpacity 是 1 的时候被认为是默认状态没有设置值了，设置为 0.999 可以发现就是正常的。不过你这里如果要分开填充色和描边色的透明度可以用 fillOpacity 和 strokeOpacity，就不要用 opacity 了

**Comment by fengChongxiu** [comment]
好的，这个辛苦修一下吧

**Comment by Yanyan-Wang** [comment]
底层渲染引擎的问题，短期内可能没有人力排期修复
