### ISSUE TITLE
使用modelRect时，updateItem后点击节点样式出错

### ISSUE THREAD

**Issue by biggbb777** [antvis/G6#2613]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cocky-goldstine-es2vz?file=/src/index.js)

### Steps to reproduce
1. 首先点击demo中的“To Update Item”按钮，以更新节点的label值 (或其他值）
2. 见到节点的label值更新后，连续多次点击节点，会出现样式的错乱

![image](https://user-images.githubusercontent.com/44860359/105978812-efa40c80-60cd-11eb-8bd3-6947f3ce3fe6.png)

| Environment | Info |
|---|---|
| g6 | 4.1.4 |
| System | - |
| Browser | - |

---
平时点击modelRect不会出问题，只有当使用updateItem方法之后，点击节点后会出现样式的错误。

**Comment by Yanyan-Wang** [comment]
谢谢，下个小版本会修复

**Comment by Yanyan-Wang** [comment]
v4.1.5 已修复了哈
