### ISSUE TITLE
文档描写错误

### ISSUE THREAD

**Issue by lovexp1** [antvis/G6#2615]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g6.antv.vision/zh/docs/api/graphFunc/stack](https://g6.antv.vision/zh/docs/api/graphFunc/stack)

### Steps to reproduce
pushStack(action, data, stackType)方法中stackType 描写错乱，且默认值应该是'undo'

| Environment | Info |
|---|---|
| g6 | 4.1.3 |
| System | - |
| Browser | - |

![image](https://user-images.githubusercontent.com/44965220/106099388-8d064b80-6175-11eb-9a63-ed273706a2fc.png)

**Comment by Yanyan-Wang** [comment]
已经修复了哈，谢谢
