### ISSUE TITLE
 Cannot find type definition file for '_gl-matrix@3.3.0@gl-matrix'.  1 /// <reference types="_gl-matrix@3.3.0@gl-matrix" />

### ISSUE THREAD

**Issue by COLDkl** [antvis/G6#2616]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/antvis/G6](https://github.com/antvis/G6)

### Steps to reproduce
 Follow the demo given by the official website   import G6 from '@antv/g6';

| Environment | Info |
|---|---|
| g6 | 4.1.4 |
| System | "typescript": "~3.8.3" |
| Browser | - |

---
import G6 from '@antv/g6';  npm run build
![image](https://user-images.githubusercontent.com/29770349/106105827-94caed80-617f-11eb-9d7a-d7d2290851f9.png)

![image](https://user-images.githubusercontent.com/29770349/106105858-9f858280-617f-11eb-9a2e-eec95d7c4bcc.png)

**Comment by andreasnett** [comment]
Try updating typescript, this does not happen for me using v~3.9.5

**Comment by onlycc** [comment]
对于这种第三方包的错误影响到了项目的构建，可以通过设置tsconfig.json文件来跳过对第三方包的校验。

设置参数："skipLibCheck":true, 即可

**Comment by Yanyan-Wang** [comment]
gl-matrix 第三方包没有类型定义。可以通过上面两个朋友的回答避免。

**Comment by Yanyan-Wang** [comment]
请升级到 v4.1.10，该问题已解决

**Comment by wunaidage** [comment]
still seeing this in 4.1.12

**Comment by Newfffff** [comment]
> 对于这种第三方包的错误影响到了项目的构建，可以通过设置tsconfig.json文件来跳过对第三方包的校验。
> 
> 设置参数："skipLibCheck":true, 即可

![image](https://user-images.githubusercontent.com/22338828/110074024-70d07c80-7dbb-11eb-84f6-859636e21cf0.png)

**Comment by burtonator** [comment]
Why is this closed? All the workarounds here are hacks.

**Comment by linfanxxxx** [comment]
"@antv/g6": "^4.3.6",
    "typescript": "~3.8.3"
仍然存在报错

**Comment by HuoZhengtang** [comment]
"@antv/g6": "^4.3.6",
"typescript": "~4.0.2"

仍然存在报错

**Comment by SuLiang2016** [comment]
"@antv/g6": "4.2.0"
"typescript": "3.9.9"

依然会有问题，需要怎么解决？

**Comment by SuLiang2016** [comment]
> "@antv/g6": "4.2.0" "typescript": "3.9.9"
> 
> 依然会有问题，需要怎么解决？

使用了"skipLibCheck":true ，有更好的方式请告知
