### ISSUE TITLE
请问节点、链路和combo三者的id是否都必须唯一？

### ISSUE THREAD

**Issue by CathyZYF** [antvis/G6#2617]
### This item exists already. Be sure the id 6425 is unique.

以上是g6在我的项目里报的错，看上去是链路的id和combo的id重复导致的，想确认一下，节点链路和combo的id是否必须唯一？若有重复，会有什么后果吗？

**Comment by Yanyan-Wang** [comment]
是的，都要唯一的，否则graph.findById可能就找错元素了
