### ISSUE TITLE
自定义节点时，扩展rect，afterDraw无法group.addShape，rect类型节点

### ISSUE THREAD

**Issue by qingchiapp** [antvis/G6#2618]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://jsrun.net/z3aKp](http://jsrun.net/z3aKp)

### Steps to reproduce
修改为group.addShape 类型为img可以，rect类型不可

| Environment | Info |
|---|---|
| g6 | 4.1.4 |
| System | - |
| Browser | - |

**Comment by Yanyan-Wang** [comment]
在你的 demo 中不是画出 rect 了吗？
![image](https://user-images.githubusercontent.com/29593318/106353473-be257e00-6325-11eb-94b5-bf1ad7d5f528.png)

另外，addShape 没有 style，fill 之类的属性都平铺在 attrs 里面，https://g6.antv.vision/zh/docs/api/shapeProperties

**Comment by qingchiapp** [comment]
> 在你的 demo 中不是画出 rect 了吗？
> ![image](https://user-images.githubusercontent.com/29593318/106353473-be257e00-6325-11eb-94b5-bf1ad7d5f528.png)
> 
> 另外，addShape 没有 style，fill 之类的属性都平铺在 attrs 里面，https://g6.antv.vision/zh/docs/api/shapeProperties

只有一个rect，我理解应该是有两个rect

**Comment by Yanyan-Wang** [comment]
有的，你把 fill 改对，然后把挡住画布的控制台往下拉一点，x 150，y 200 太远了
