### ISSUE TITLE
Using X6 connectors and routers in G6 dagre layout 

### ISSUE THREAD

**Issue by PoojaUppalapati** [antvis/G6#2619]
- **G6 Version**: 4.1.3

Where can I find examples on using X6 edge connectors and routers in G6 dagre layout?

**Comment by Yanyan-Wang** [comment]
They are separated libraries, there are no examples for combining usage. All the demos are on the official websites
https://g6.antv.vision/en/examples/gallery
https://x6.antv.vision/en/examples/gallery/
