### ISSUE TITLE
BUG: delete tree node throw error, node id not suppose number type.

### ISSUE THREAD

**Issue by ruoru** [antvis/g6#262]
i am use G6 tree component with react, my node which id created by me, they will throw error when delete it.

1. my data like this 
```js
{
  id: 'root',
  name: 'xxx',
  children: [{
    id: 'nanna',
    name: 'asdasd',
    children: [...],
  }, {
    id: 'nanna',
    name: 'asdasd',
    children: [...],
  }]
}
```

2. but when i delete node in tree, there throw an error, and will delete all the tree:
```error
TypeError: Cannot set property 'lineWidth' of nulldatavis-g6-1.1.6.js:5 Uncaught TypeError: Cannot set property 'lineWidth' of null
    at d._setAttr (datavis-g6-1.1.6.js:5)
    at d.attr (datavis-g6-1.1.6.js:5)
    at main-v0.0.0.js:1
    at datavis-g6-1.1.6.js:4
    at Object.each (datavis-g6-1.1.6.js:4)
    at t.fire (datavis-g6-1.1.6.js:4)
    at onMouseMove (datavis-g6-1.1.6.js:6)
    at HTMLCanvasElement.n (datavis-g6-1.1.6.js:4)
```

3. case other: when add a new node with create new id by G6 not me, delete this node will not error. 

any help will be very grateful.

**Comment by ruoru** [comment]
i am find my mistake, node id only suppose string, not number, this is a bug, please fix it.

**Comment by TomHuangCN** [comment]
2.0 has already fix it
