### ISSUE TITLE
g6-core 包里指定的 browser 属性在对应的包里找不到文件

### ISSUE THREAD

**Issue by fengChongxiu** [antvis/G6#2620]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
无重现地址，见页面截图
![image](https://user-images.githubusercontent.com/17736007/106345647-ada4e180-62ec-11eb-9013-64ed731eb4ce.png)

### Steps to reproduce
见页面截图
![image](https://user-images.githubusercontent.com/17736007/106345648-b1d0ff00-62ec-11eb-93bd-8d00355af585.png)

| Environment | Info |
|---|---|
| g6 | 4.1.6 |
| System | - |
| Browser | - |

**Comment by fengChongxiu** [comment]
补充说明，在使用 rollup 打包时，如果 @rollup/plugin-node-resolve 配置了 browser： true，那么在打包的时候，rollup 会把 g6-core 当成 external dependency 处理，原因就是 g6-core 包里没有 dist 文件夹

**Comment by Yanyan-Wang** [comment]
尝试一下 v4.1.7
