### ISSUE TITLE
ControllerCfg Language Issue

### ISSUE THREAD

**Issue by Wathsara** [antvis/G6#2622]
@Yanyan-Wang I have raised the question regarding changing the text in Issue #2597. You have mentioned that its fixed in version 4.1.5 and its working fine.
![image](https://user-images.githubusercontent.com/31571237/106348619-8569b280-62ed-11eb-96dc-65c001be308c.png)

But whenever I tick the checkbox. The language changes to another Chinese word and then it never changes back to the Configured text.

When Check
![image](https://user-images.githubusercontent.com/31571237/106348720-4ab44a00-62ee-11eb-85b6-c56e91b78ba2.png)

When Uncheck after check
![image](https://user-images.githubusercontent.com/31571237/106348728-5b64c000-62ee-11eb-943e-474b40adaf33.png)

**Comment by Yanyan-Wang** [comment]
Ops, try 4.1.7 pls.
