### ISSUE TITLE
Edges from combos puts target in next rank

### ISSUE THREAD

**Issue by andreasnett** [antvis/G6#2625]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
It would be really helpful to allow for edges from a grouping of nodes to put the target node in the next rank. It would make sense if this was the case, and should maybe be the default case. 

### What does the proposed API look like?
```
const graph = new G6.Graph({
  ...otherconfig,
  layout: {
    sortRankByCombo: boolean,
    },
})
```

**Comment by andreasnett** [comment]
Could this feature be added by simply having another parameter here? 
https://github.com/antvis/G6/blob/master/packages/core/src/graph/controller/layout.ts#L112

**Comment by Yanyan-Wang** [comment]
The question is not so clear for me. Do you mean adjust the dagre layout with combo information? Try dagre layout and config `sortByCombo` to be true with v4.1.13-beta.3

**Comment by andreasnett** [comment]
So the error is that when giving an edge from a combo to some node, this doesn't put the target node in the next rank. I.e. they stay on the same y-pos.

**Comment by andreasnett** [comment]
I can't seem to find the src I used when first requesting this, so it seems now this issue goes both ways. Edges between combos and nodes don't affect each others rank. See this [CodeSandbox](https://codesandbox.io/s/antv-tooltip-plugin-combo-forked-fk1ss?file=/index.js) for an illustration.

**Comment by andreasnett** [comment]
@Yanyan-Wang could this be possible? Notice how node-3 pointing to combo 2 doesn't affect the position of combo 2

**Comment by Yanyan-Wang** [comment]
upgrade @antv/layout to 0.3.6, problem solved
