### ISSUE TITLE
G6的combo的label设置background-color

### ISSUE THREAD

**Issue by q774221810** [antvis/G6#2626]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
能像设置节点或边的label背景一样设置 combo的label背景
 labelCfg: {
    style: {
      fill: "#313131",
      background: {
        fill: "#ffffff",
        stroke: "green",
        padding: [3, 2, 3, 2],
        radius: 2,
        lineWidth: 3,
      },
    },
  },
对combo的好像没啥用

### What does the proposed API look like?
`
 labelCfg: {
    style: {
      fill: "#313131",
      background: {
        fill: "#ffffff",
        stroke: "green",
        padding: [3, 2, 3, 2],
        radius: 2,
        lineWidth: 3,
      },
    },
  },
`

**Comment by Yanyan-Wang** [comment]
暂不支持，可以自定义 combo 实现

**Comment by q774221810** [comment]
@Yanyan-Wang 在哪里方法可以复写这个QAQ

**Comment by q774221810** [comment]
自己在drawShape根据label的位置group.addShape一个rect应该就可以了

**Comment by q774221810** [comment]
@Yanyan-Wang 为什么自定义combo自带动画啊。。。怎么取消

**Comment by Yanyan-Wang** [comment]
> 自己在drawShape根据label的位置group.addShape一个rect应该就可以了

是的。然后可以用 shape.toFront shape.toBack 来调整图形的层级

**Comment by Yanyan-Wang** [comment]
> @Yanyan-Wang 为什么自定义combo自带动画啊。。。怎么取消

实例化图的时候可以把 animate: false 配置到 defaultCombo 上
