### ISSUE TITLE
TreeGraph设置collapse-expand模式，同时设置节点的hover事件，发现hover会让collapse-icon展示不正确

### ISSUE THREAD

**Issue by oooofeiger** [antvis/G6#2628]
在g6提供的树状图demo中加了hover事件之后bug可以复现，地址https://g6.antv.vision/zh/examples/tree/customItemTree#customTree
```
//graph新增如下配置：
nodeStateStyles:{
        hover: {
          fill: '#063250',
          stroke:'#154D77'
        }
      }


//新增hover事件
graph.on('node:mouseenter', (evt) => {
  const { item } = evt;
  graph.setItemState(item, 'hover', true);
});

graph.on('node:mouseleave', (evt) => {
  const { item } = evt;
  graph.setItemState(item, 'hover', false);
});
```

###点击节点折叠或展开的同时移出鼠标，发现节点的折叠标志显示不正确

**Comment by oooofeiger** [comment]
有解决的办法，在hover事件中重新设置icon的状态

**Comment by Yanyan-Wang** [comment]
看下这个例子哈：
https://codesandbox.io/s/dry-frost-7x9kw

几个关键点：
1. （由于在外部控制图形的更新可能会导致样式没有被统一控制）把更新 icon 的 symbol 放在复写 update 方法中，由节点统一控制，而不是放在 onChange 中。
2. （经过上面修改，发现 icon 可以正确显示，但是更新后会有一个灰色的方块错误显示）例子中 keyShape 的 name 和 label 的 name 写成了一样的，把 label 的 name 换一个。
