### ISSUE TITLE
移动端节点点击事件失效问题

### ISSUE THREAD

**Issue by WongBaba** [antvis/G6#2629]
- **G6 Version**: 3.8.4  -  4.1.5
- **Platform**:  win10
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

在3.8.4之后的版本上移动端增加缩放画布modes时，节点的点击事件无法被响应，在graph.on(node:click)  方法第一行console  e对象，都没有任何反应，是否有方法在移动端既能缩放画布又能响应点击事件？

以上问题发生在chrome浏览器切换到移动端模式，当切换成pc端时点击事件是没问题的

官网样例：https://g6.antv.vision/zh/examples/interaction/zoomCanvasFixItem#fixItem
在页面切换到移动端时，点击事件也失效了，当把样例的zoom-canvas去掉就正常了

**Comment by WongBaba** [comment]
搞了2天，想了个临时解决方案
参考了https://github.com/antvis/G6/issues/816， 发现使用zoom-canvas时，可以识别drag的touch事件，在finger-drag-canvas这个自定义行为中增加每次拖动的距离变量，当每次拖动小于30px，则将该次行为判定为是【点击】，转而识别当前e对象是在节点上还是画布上，如果是在节点上这触发节点的点击事件

`G6.registerBehavior('finger-drag-canvas', {
  dragging: false,
  offset:0,
  getEvents() {
    return {
      touchstart: 'onDragStart',
      touchmove: 'onDrag',
      touchend: 'onDragEnd'
    };
  },
  onDragStart(e) {
    const self = this;
    self.dragging = false;
    self.offset=0;

    const clientX = +e.clientX;
    const clientY = +e.clientY;

    this.origin = {
      x: clientX,
      y: clientY
    };
  },
  onDrag(e) {
    const { graph } = this;
    if (!this.dragging) {
      this.dragging = true;
    }
    this.updateViewport(e);
  },
  onDragEnd(e) {
    if (this.enableOptimize) {
      const edges = graph.getEdges();
      for (let i = 0, len = edges.length; i < len; i++) {
        const shapes = edges[i].get('group').get('children');
        if (!shapes) continue;
        shapes.forEach(shape => {
          shape.show();
        });
      }
      const nodes = graph.getNodes();
      for (let j = 0, nodeLen = nodes.length; j < nodeLen; j++) {
        const container = nodes[j].getContainer();
        const children = container.get('children');
        for (const child of children) {
          const isKeyShape = child.get('isKeyShape');
          if (!isKeyShape) {
            child.show();
          }
        }
      }
    }
    this.updateViewport(e);
    this.dragging = false;
    // 这里开始识别点击事件
    if(this.offset<30){
        // 触发点击事件（或者依靠e.target，e.type去做相应的业务操作）
    }


  },
  updateViewport(e) {
    const { origin } = this;
    const clientX = +e.clientX;
    const clientY = +e.clientY;

    if (isNaN(clientX) || isNaN(clientY)) {
      return;
    }
    let dx = clientX - origin.x;
    let dy = clientY - origin.y;
    if (this.get('direction') === 'x') {
      dy = 0;
    } else if (this.get('direction') === 'y') {
      dx = 0;
    }
    this.origin = {
      x: clientX,
      y: clientY
    };
    const width = graph.get('width');
    const height = graph.get('height');
    const graphCanvasBBox = graph.get('canvas').getCanvasBBox();
    if (
      (graphCanvasBBox.minX <= width && graphCanvasBBox.minX + dx > width) ||
      (graphCanvasBBox.maxX >= 0 && graphCanvasBBox.maxX + dx < 0)
    ) {
      dx = 0;
    }
    if (
      (graphCanvasBBox.minY <= height && graphCanvasBBox.minY + dy > height) ||
      (graphCanvasBBox.maxY >= 0 && graphCanvasBBox.maxY + dy < 0)
    ) {
      dy = 0;
    }
    if (dx === 0 && dy === 0) return;
    // 增加拖动距离统计
    this.offset += Math.abs(dx) + Math.abs(dy)
    graph.translate(dx, dy);
  }
});`

**Comment by zarte** [comment]
@WongBaba 
点击节点会触发两次咋处理？画布也有一次。

**Comment by WongBaba** [comment]
> @WongBaba
> 点击节点会触发两次咋处理？画布也有一次。

尝试打印一下这两次点击事件的对象e，看这两个对象属性有什么不同，通过属性不同区分节点和画布对象，给与分别的响应

**Comment by zarte** [comment]
@WongBaba 
e.target一样。。。点击画布空白地方就只会触发一次，自定义节点。

**Comment by WongBaba** [comment]
> @WongBaba
> e.target一样。。。点击画布空白地方就只会触发一次，自定义节点。

我的项目没有出现这个情况，回老家也没带电脑文档都没法查，实在不行做个防抖吧

**Comment by Yanyan-Wang** [comment]
移动端检测点击事件应该用 node:touchstart / edge:touchstart / canvas:touchstart

**Comment by WongBaba** [comment]
> 移动端检测点击事件应该用 node:touchstart / edge:touchstart / canvas:touchstart

node:touchstart  这个事件可以到移动端使用，但是会被drag-canvas和zoom-canvas误触，要实现真正意义上的移动端节点点击事件还是得自己再自定义一个Behavior

**Comment by PeakGao-Shanshan** [comment]
移动端node:contextmenu也不生效
