### ISSUE TITLE
【移动端】通过api多次调用graph.zoomTo后无法通过手势缩小

### ISSUE THREAD

**Issue by Way-Ho** [antvis/G6#2630]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/white-breeze-302b5?file=/src/index.js)

### Steps to reproduce
通过手机浏览器打开后，多点击几次，然后就会发现无法通过手势缩小

| Environment | Info |
|---|---|
| g6 | 4.1.7 |
| System | ios14 |
| Browser | Safari |

**Comment by crystalwm** [comment]
你多次调用zoomTo函数的目的是为了控制缩放范围吗？
如果是的，可以直接在Graph 配置中设置
```js
const graph = new G6.Graph({
  container: "root",
  minZoom: 1,
  maxZoom: 20,
  width: 500,
  height: 500,
  modes: { default: ["zoom-canvas", "drag-canvas"] }
});
```

**Comment by Way-Ho** [comment]
不是的哈，我是缩放范围我设置了的，我的需求是：双击可以放大，手势可以放大和缩小，目前调用zoomTo函数是为了做双击放大

**Comment by Yanyan-Wang** [comment]
fixed by 4.1.8
