### ISSUE TITLE
zoom-canvas配置shouldBegin后不无效

### ISSUE THREAD

**Issue by Way-Ho** [antvis/G6#2631]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sad-rubin-8uofw?file=/index.js:4342-4353)

### Steps to reproduce
打开链接，点击一下即可发现，和https://github.com/antvis/G6/issues/2571  是类似的问题

| Environment | Info |
|---|---|
| g6 | 4.1.7 |
| System | ios14 |
| Browser | Safari |

**Comment by Yanyan-Wang** [comment]
4.1.8 已修复
