### ISSUE TITLE
隐藏的节点调用showItem以后，相关边没有及时显示

### ISSUE THREAD

**Issue by CathyZYF** [antvis/G6#2632]
[https://codepen.io/cathyzyf/pen/JjRxREK](https://codepen.io/cathyzyf/pen/JjRxREK)

如demo所示，id为1的节点默认visible为false,点击按钮后，将node1展示出来，但node1与node2的链接线没有同步显示，直到我对1进行操作（拖拽）后才显示出来

**Comment by Yanyan-Wang** [comment]
在数据中设置节点的 false 将只隐藏该节点，相当于调用 node.hide()。graph.hideItem(node) 将会同时隐藏节点和它相关的边。

这里其实在没有点击“显示”之前，边也是可见的。只不过由于该节点被隐藏了，没有参与初始化位置（x，y）和渲染，所有边拿不到端点位置而导致计算边的路径失败，所以边也没有显示出来…然后在点击了“显示”之后，节点虽然画出来了，但是它的 model 里还是没有 x y，所以边还是没显示。

如果你在 visible:false 的节点数据上给一个初始的 x y 就会看到正常的逻辑。

所以这里是两个问题：

- G6 应该内部处理 show 节点时，若节点 model 没有位置信息，则给一个 random 值。

- 你这里如果是希望一开始隐藏一个节点并隐藏相关边的话，需要调用 graph.hideItem(node)。

**Comment by Yanyan-Wang** [comment]
> G6 应该内部处理 show 节点时，若节点 model 没有位置信息，则给一个 random 值。

v4.2.1 已修复。
