### ISSUE TITLE
工具栏组件，在没有操作的时候，点击置灰的撤销图标，点击后撤销和返回图标被点亮，但是点击又没有效果

### ISSUE THREAD

**Issue by W-Rick** [antvis/G6#2635]
工具栏组件，在没有操作的时候，点击置灰的撤销图标，点击后撤销和返回图标被点亮，但是点击又没有效果。
点击前：
![image](https://user-images.githubusercontent.com/38304544/106582514-068ba880-657f-11eb-8c23-6b1d88fb4e86.png)
点击后：
![image](https://user-images.githubusercontent.com/38304544/106583269-dee91000-657f-11eb-930f-e6cfbb3a23a0.png)
正常理解，应该是没有操作应该一直保持置灰状态。
麻烦看看这是不是一个问题，谢谢！

**Comment by baizn** [comment]
是个bug，下个版本修复，感谢反馈！
