### ISSUE TITLE
Problems in document pictures

### ISSUE THREAD

**Issue by leixhao** [antvis/G6#2636]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://www.yuque.com/antv/g6-blog/nnmqbk#ST1aK](https://www.yuque.com/antv/g6-blog/nnmqbk#ST1aK)

### Steps to reproduce
In the last picture below the "zero to one graph theory algorithm" module, the demonstration content is the shortest path algorithm, but it seems that the distance of 0-10-22 is significantly shorter than that of 0-16-22. Is this a picture error or?

| Environment | Info |
|---|---|
| g6 | 4.1.7 |
| System | win10 |
| Browser | chrome最新版 |

**Comment by Yanyan-Wang** [comment]
0-10-22 and 0-16-22 are both the shortest path for 0 to 22. The demo only shows one of it.

The shortest path means the path who has shortest distance in graph data but not in Euclidean space.
