### ISSUE TITLE
有没有能够调整tooltip位置的方法？

### ISSUE THREAD

**Issue by oooofeiger** [antvis/G6#2637]
如题，有没有能够调整tooltip位置的方法？offset不能满足

**Comment by Yanyan-Wang** [comment]
https://g6.antv.vision/zh/examples/tool/tooltip#tooltipPlugin

offsetX，offsetY

怎么个不满足法？麻烦提供一下最小复现在线 demo

**Comment by oooofeiger** [comment]
就是想让tooltip框相对节点固定，不需要它跟随光标移动，现在好像没法实现这个效果

**Comment by Yanyan-Wang** [comment]
也许可以通过 mousemove 的时候强制设置这个 DOM 为当前节点的位置

**Comment by Yanyan-Wang** [comment]
或者是自己定义一个 DOM 并只在 node:mouseenter 时指定该 DOM 的位置为节点位置，不相应 node:mousemove。效果参见 AntV 主官网第二屏的决策树例子：https://antv.gitee.io/zh，源码：https://github.com/antvis/antvis.github.io/blob/57ab741834ef46d409c4d0d3b2eaa7a71e34e8e3/site/components/DecisionTree/DecisionTree.tsx#L1137

也欢迎社区小伙伴为内置 tooltip 增加 feature 哦
