### ISSUE TITLE
no tags and no description in this repositories commit.

### ISSUE THREAD

**Issue by ruoru** [antvis/g6#264]
1. i can not find which commit is version 2.0.
2. document no version as demo.
3. we are greet open source code, i am ver like [mind map demo](https://antv.alipay.com/assets/dist/3.0.0/g6/1.x/editor/mind.html), good.

**Comment by TomHuangCN** [comment]
1. G6 will open source as a graph base visualization framework tomorrow.
2. Mind map is one part of G6-Editor which will not open source this time, however you can still use it.

 demo code: https://github.com/antvis/g6-editor/blob/master/demos/mind.html
