### ISSUE TITLE
registerBehavior 的 onWheel 事件失效？代码 是从 官网cv下来的，请问可能会是什么原因造成的？

### ISSUE THREAD

**Issue by BabyMing** [antvis/G6#2640]
G6.registerBehavior('double-finger-drag-canvas', {
        getEvents: function getEvents() {
          return {
            wheel: 'onWheel'
          };
        },

        onWheel: function onWheel(ev: any) {
          if (ev.ctrlKey) {
            const canvas = graph_new.get('canvas');
            const point = canvas.getPointByClient(ev.clientX, ev.clientY);
            let ratio = graph_new.getZoom();
            if (ev.wheelDelta > 0) {
              ratio = ratio + ratio * 0.05;
            } else {
              ratio = ratio - ratio * 0.05;
            }
            graph_new.zoomTo(ratio, {
              x: point.x,
              y: point.y
            });
          } else {
            const x = ev.deltaX || ev.movementX;
            const y = ev.deltaY || ev.movementY;
            console.log('ev', x, y)
            graph_new.translate(-x, -y);
          }
          ev.preventDefault();
        }
      });

**Comment by Yanyan-Wang** [comment]
请提供最小复现的在线 demo

**Comment by yizhengfeng-jj** [comment]
> G6.registerBehavior('double-finger-drag-canvas', {
> getEvents: function getEvents() {
> return {
> wheel: 'onWheel'
> };
> },
> 
> ```
>     onWheel: function onWheel(ev: any) {
>       if (ev.ctrlKey) {
>         const canvas = graph_new.get('canvas');
>         const point = canvas.getPointByClient(ev.clientX, ev.clientY);
>         let ratio = graph_new.getZoom();
>         if (ev.wheelDelta > 0) {
>           ratio = ratio + ratio * 0.05;
>         } else {
>           ratio = ratio - ratio * 0.05;
>         }
>         graph_new.zoomTo(ratio, {
>           x: point.x,
>           y: point.y
>         });
>       } else {
>         const x = ev.deltaX || ev.movementX;
>         const y = ev.deltaY || ev.movementY;
>         console.log('ev', x, y)
>         graph_new.translate(-x, -y);
>       }
>       ev.preventDefault();
>     }
>   });
> ```

遇到同样问题，原因是版本不一样，你看看你自己的版本，3.2.x的系列好像不只是onWheel了，升级到4.1.x试试
