### ISSUE TITLE
求助：更新边的样式失败

### ISSUE THREAD

**Issue by CathyZYF** [antvis/G6#2641]
这个问题在codePen上没有复现出来，但在我的开发环境一直出现
大致流程是这样的：通过传回的edgeData.lineStyle进行更新，根据edgeData.lineStyle设置边的样式(solid：实线，dash：虚线，arrow：箭头)

现在的问题是，如果在一条边上原本有endArrow箭头的样式，在更新为虚线或者实线以后，箭头仍然存在（在刚刚更新完时是没有箭头了，但鼠标移入画布的一瞬间，箭头又会出现），想求助一下，看看有可能是什么原因造成的？

以下是我开发环境的代码
```
let obj = {
    stroke:edgeData.color,
    lineWidth:edgeData.size
}
switch (edgeData.lineStyle) {
case 'solid':
    obj.lineDash = []
    obj.endArrow = false
    break
case 'dash':
    obj.lineDash = [10,10]
    obj.endArrow = false
    break
case 'arrow':
    obj.endArrow={
        path: 'M 0,0 L 20,10 L 20,-10 Z', // 自定义箭头路径
        d: -r ,// 偏移量
        fill: edgeData.color,
        stoke:edgeData.color
    }
    obj.lineDash = []
    break
}
this.graph.updateItem(item,{
    ...edgeData,
    style:obj
})
```

其中的edgeData长这样：
```

let edgeData= {  // 根据item.getModel()创建一个新对象edgeData,用来监听用户对样式的操作
    id:model.id,
    size:model.size,
    color:model.color,
    lineStyle:model.lineStyle
}
```

**Comment by Yanyan-Wang** [comment]
写成在线 demo，否则很难排查。在线 demo 没复现的话，首先看版本号是不是一致的

**Comment by baizn** [comment]
node_modules 全部删了，重新装一遍，估计是存在多个版本导致的

**Comment by CathyZYF** [comment]
> node_modules 全部删了，重新装一遍，估计是存在多个版本导致的

我试了一下，删除了node_modulse和package-lock.json，然后重新安装依赖，再进入项目，还是不行😟

**Comment by Yanyan-Wang** [comment]
可能是状态样式管理的问题。暂时可以通过在更新箭头之前清空一下 originStyle：

graph.getEdges()[0].set('originStyle', {});

不过需要注意的是，此时这条边上最好不要有状态，否则可能会有问题

**Comment by CathyZYF** [comment]
谢谢，问题解决了

**Comment by Yanyan-Wang** [comment]
v4.2.0 已修复
