### ISSUE TITLE
请问，多条边时，连接线为折线时出现重叠情况怎么解决？

### ISSUE THREAD

**Issue by Zhouqchao** [antvis/G6#2642]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现在有个需求，每个combo可能会输出多条连接线，连接到另一个combo中的某个节点，每个节点同时只能存在一个连接线。
但是当combo输出的多条连接线为折线时，会出现连接线部分重叠情况，不知道该如何解决？

G6 Version: 3.7.0

Platform: Mac

Mini Showcase(like screenshots):
![连接线为折线时，出现重叠情况](https://tva1.sinaimg.cn/large/008eGmZEgy1gnbjy17x80j31120remzv.jpg)
CodePen Link:
[G6实现拓扑图多条边为折线时出现重叠问题](https://codepen.io/Tom_chao/pen/NWbGEVv)

### What does the proposed API look like?
我暂时的想到的思路是设置多个开始连接点，每个连接点对应一个连接线，然后动态计算折线的转折点位置，但是想不出该用什么API如何实现？

**Comment by Zhouqchao** [comment]
> 设置 anchorPoints [g6.antv.vision/zh/docs/manual/middle/elements/nodes/anchorpoint/#gatsby-focus-wrapper](https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/anchorpoint/#gatsby-focus-wrapper)
> 
> anchorPoints 位置可以是 0-1 范围内任意值

 可以设置多个起始连接点了，但是多条边折线部分还是会有重叠。
![image](https://user-images.githubusercontent.com/24250131/106876918-2f44a700-6713-11eb-9ef2-589306d77177.png)
请问这种情况该怎么解决？需要基于polyline实现自定义边，然后动态设置每条边的折线的转折点位置吗？

**Comment by Yanyan-Wang** [comment]
我想比较简单的方法可能是在全部绘制完成之后，更新一下边的 anchorPoints，找到不同边上 x 相同的 anchorPoint，修改它们的 x

**Comment by Zhouqchao** [comment]
> 我想比较简单的方法可能是在全部绘制完成之后，更新一下边的 anchorPoints，找到不同边上 x 相同的 anchorPoint，修改它们的 x

好的，谢谢。
