### ISSUE TITLE
I want to underline/line-through a label

### ISSUE THREAD

**Issue by csouchet** [antvis/G6#2643]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When a new **Node** or a new **Edge** is defined, or at the new **Graph** instantiating, it's possible to configure the label style with _fontSize_, _fontFamily_ and other properties. But it's not possible to configure the CSS property _text-decoration_ who makes the label _**line-through**_, _**underline**_ and _**overline**_.

Same for the **Text shape**.

### What does the proposed API look like?
I propose to add the new property _textDecoration_ to the **Text shape**, who corresponds to the property in CSS is _text-decoration_, like it's done for _font-variant_ and the other CSS font properties.

**Comment by Yanyan-Wang** [comment]
Since the basic shapes are corresponding to the those in Canvas API, where the text-decoration is not supported, G6 won't consider it into text shape too.

But you can still achieve it by adding a path shape under/trough the text.

**Comment by Yanyan-Wang** [comment]
Hi, dear user. Since there was no response for a long time, we cannot figure out the answer of the problem you described. If there is new progress, feel free to open a new issue.

**Comment by danieljd** [comment]
Add a path shape under the text could be a solution. But if the length of the text is not sure, how can I know the length of a path shape
