### ISSUE TITLE
Resizing container based on it's content

### ISSUE THREAD

**Issue by CaptainFreak** [antvis/G6#2645]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently at least am not aware of a way to have a container that gets resized based on its content. We always have to give exact values for the width and height of the container.

### What does the proposed API look like?
An option to make the container flexible to contain the graphs.

**Comment by CaptainFreak** [comment]
`fitView` won't work as it just resizes the  graph itself in the given fixed container size

![image](https://user-images.githubusercontent.com/20478531/106999875-fbb65b00-67ac-11eb-9ba7-09d369fa200b.png)

VS

![image](https://user-images.githubusercontent.com/20478531/106999869-f5c07a00-67ac-11eb-9e22-4d5fb3a5e749.png)

**Comment by Yanyan-Wang** [comment]
For now, users can only resize the container by themselves after the graph size changing. e.g. call graph.getGroup().getCanvasBBox() to get the actual width and height of the graph content.

The feature is not in the current official schedule. We welcome PRs from communities to contribute

**Comment by CaptainFreak** [comment]
Thanks a lot, this works for now.
