### ISSUE TITLE
关于轮廓包裹的一个疑问

### ISSUE THREAD

**Issue by Veigar-C** [antvis/G6#2646]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/g6-layout-grid-koe1p?file=/index.js)

### Steps to reproduce
似乎只有初始的时候，开启布局后，节点会被裹入
尝试以下都不会：
1. 在开启轮廓前移动某个节点，这个节点不会被裹入
2. 开启后再关闭，移动某个节点，再开启这个节点也不会被裹入

所以我想将调整完的布局保存时，回显数据后开启轮廓包裹时，看起来似乎createHull没有生效的感觉。。
有什么方法可以解决？

再补充下：
因为有改变combo样式的需求，所以将combos设为空了，但似乎combos存在时，轮廓包裹是有效的

| Environment | Info |
|---|---|
| g6 | 4.1.7 |
| System | win10 |
| Browser | chrome |

**Comment by Yanyan-Wang** [comment]
我大致看了两眼你的代码，会不会裹入完全是根据你给的 members 决定的，跟移动不移动没关系啊，你代码 Line120 这里拖动节点后 filter 出来的 members 就变了，因为被拖动的那个节点的 comboId 没了，我没具体看是什么原因，总之是和你操作了 data 有关系。

**Comment by Veigar-C** [comment]
看了下Log，确实comboId丢失了，所以createHull没有加入改节点ID，导致生成的包裹有问题。
数据应该 graph.save()取的，尝试在node加入 comboId 的backup，发现是可以取到的，
应该是移动后该节点后， graph.save().nodes 对应这个节点的comboId丢失了，
能定位到问题就行，我做个backup解决。。
