### ISSUE TITLE
It's very complicated to contribute

### ISSUE THREAD

**Issue by csouchet** [antvis/G6#2647]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Contribution: Some commands from the root ReadMe don't work.](Contribution: Some commands from the root ReadMe don't work.)

### Steps to reproduce
From the root directory:

- $ npm install --> OK

- $ npm run bootstrap --> Error
```shell
make: *** [nbind.target.mk:157: Release/obj.target/nbind/sources/Config.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/gitpod/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.4.0-1024-gcp
gyp ERR! command "/home/gitpod/.nvm/versions/node/v14.15.4/bin/node" "/home/gitpod/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /workspace/G6/node_modules/yoga-layout
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yoga-layout@1.9.3 build:node: `npm run copy-sources && autogypi && node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm   CXX(target) Release/obj.target/nbind/sources/yoga/Yoga.o
  CXX(target) Release/obj.target/nbind/sources/Config.o
make: Leaving directory '/workspace/G6/node_modules/yoga-layout/build'
ERR! Failed at the yoga-layout@1.9.3 build:node script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

- $ npm run build:all  ---> Doesn't run the react-node package. Is it normal ? If Yes, what is the order to run these commands ?

- $ cd ./packages/core
$ npm run watch ---> Ok, but what is the next step. Is there a port / an app to call ? How to test manually ?

- $ npm test ---> Nothing appends, and never finished
```shell
> g6@ test /workspace/G6
> npm run test:core && npm run test:element && npm run test:plugin && npm run test:pc

> g6@ test:core /workspace/G6
> cd ./packages/core && npm run test

> @antv/g6-core@0.0.9 test /workspace/G6/packages/core
> jest

Test Suites: 0 of 36 total
Tests:       0 total
Snapshots:   0 total
Time:        873s
```

- npm test -- --watch ./tests/unit/algorithm/find-path-spec ---> Nothing appends, and never finished
```shell
> g6@ test /workspace/G6
> npm run test:core && npm run test:element && npm run test:plugin && npm run test:pc "--watch" "./tests/unit/algorithm/find-path-spec"

> g6@ test:core /workspace/G6
> cd ./packages/core && npm run test

> @antv/g6-core@0.0.9 test /workspace/G6/packages/core
> jest

Test Suites: 0 of 36 total
Tests:       0 total
Snapshots:   0 total
Time:        87s
```

- DEBUG_MODE=1 npm test -- --watch ./tests/unit/algorithm/find-path-spec
```shell
> g6@ test /workspace/G6
> npm run test:core && npm run test:element && npm run test:plugin && npm run test:pc "--watch" "./tests/unit/algorithm/find-path-spec"

> g6@ test:core /workspace/G6
> cd ./packages/core && npm run test

> @antv/g6-core@0.0.9 test /workspace/G6/packages/core
> jest

Test Suites: 0 of 36 total
Tests:       0 total
Snapshots:   0 total
Time:        32s
```

- $ npm run demos ---> Error
```shell
npm ERR! missing script: demos

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gitpod/.npm/_logs/2021-02-05T13_29_48_740Z-debug.log
```

| Environment | Info |
|---|---|
| g6 | 4.1.7 |
| System | - |
| Browser | - |

---
Also, there is no technical documentation. So it's very complicated to understand wich code is used for which features :(
And I tried to join a G6 Communication Group, but all the text is in Chinese. So I gave up.

**Comment by Yanyan-Wang** [comment]
Switch the node to version 10.23.2 for yoga-layout, which is used in react-node. Or just rebase the master, the react-node package has been ignore while bootstrap

**Comment by Yanyan-Wang** [comment]
It is a problem after the new react-node package recently and we are trying to make it do not affect the other packages.

BTW, thanks for contributing!
