### ISSUE TITLE
create-edge模式，每次重新添加的边的时候，id都是从edge1开始问题

### ISSUE THREAD

**Issue by yumenglong** [antvis/G6#2649]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/yumenglong/pen/xxEQdZJ](https://codepen.io/yumenglong/pen/xxEQdZJ)

### Steps to reproduce
1、从“话术节点123456”上的一个锚点，拉出来一条线到“话术节点2”上
2、点击保存
3、F12中，看到打出来的保存的数据，边的id会用相同

| Environment | Info |
|---|---|
| g6 | 3.7.3 |
| System | win10 |
| Browser | 谷歌 |

---
怎么样在用“create-egde”的时候修改边的id，并且是在aftercreateedge中能获取修改后的id，而不是生成的边的id。

**Comment by Yanyan-Wang** [comment]
更新到最新版本就可以了

**Comment by Yanyan-Wang** [comment]
最新 4.1.8
