### ISSUE TITLE
升级声明

### ISSUE THREAD

**Issue by TomHuangCN** [antvis/g6#265]
开源前夕，关了大家所有的 issues 有感：

由于本次升级，架构全部调整

![image](https://user-images.githubusercontent.com/6113694/40987273-bedd1f5e-691a-11e8-99e2-4117a8ab5b55.png)

可能原来 1.0 的用户如果要迁移到 2.0 会有一段时间阵痛期，先表示抱歉。**但请大家相信，轻装简行，是为了能去更远的远方。**

如需要 1.x 文档，请留言，我们会尽快提供。

**Comment by cike8899** [comment]
大致看了下，文档有不少改动，比如Net的api没了，可以提供下吗？

**Comment by sunny920406** [comment]
楼主 需要1.2.8 的文档呢

**Comment by TomHuangCN** [comment]
这周会放到旧版网站里

**Comment by yumenglong** [comment]
刚刚用了两周，功能刚开发完，就更新了个大版本，我的心情啊哦呀。。。需要1.2.8的文档哦

**Comment by wued2017** [comment]
需要1.2.8 的文档啊，2.0好像没找到image了。。。

**Comment by TomHuangCN** [comment]
今天会放到旧版站点

**Comment by TomHuangCN** [comment]
1.x 文档：http://antvis.github.io/g6/doc/index.html

**Comment by yumenglong** [comment]
666

**Comment by KylenXu** [comment]
net的东西好像基本都整合到graph上了

**Comment by TomHuangCN** [comment]
G6 层没有 Net 的概念了。 @ZOEWANGCHINA

**Comment by jzoe** [comment]
@TomHuangCN 

2.0的文档中，很多API中选项的作用、默认值、枚举值这些都没有说明，希望能尽快完善相关文档。

另外像 1.x 版本中 edge 内置的shape: smooth 中应该是一个很基础的需求，如果2.0版本中希望以插件的形式注入的话，建议可以提供一个官方的实现。而不是让大家自己去 register 一个 edge。

**Comment by jzoe** [comment]
@TomHuangCN 

1. 关于坐标的文档中 https://antv.alipay.com/zh-cn/g6/1.x/tutorial/detail-coord.html 没有说明坐标轴的原点（X与Y轴交点）的位置，这个位置是如何确定的呢？

2. 另外想知道如何获取1.x版本的源码呢？我看代码仓库中只有6月6号后提交的代码了。

想看看1.x源码中 smooth 类型的 edge 是如何实现的。1.x版本中紧凑树的例子中通过 `tree.edge().shape('smooth');` 的方式设置的 edge 渲染的比较优美。
![image](https://user-images.githubusercontent.com/11612990/41392510-94ffee9a-6fd3-11e8-8f58-749e5b01e33e.png)

现在2.0版本中的紧凑树例子 https://antv.alipay.com/zh-cn/g6/1.x/demo/gallery/gallery-tree-compact-box.html 中用下面方式注册edge
```js
G6.registerEdge('smooth', {
  getPath: function getPath(item) {
    var points = item.getPoints();
    var start = points[0];
    var end = points[points.length - 1];
    var hgap = Math.abs(end.x - start.x);
    if (end.x > start.x) {
      return [['M', start.x, start.y], ['C', start.x + hgap / 4, start.y, end.x - hgap / 2, end.y, end.x, end.y]];
    }
    return [['M', start.x, start.y], ['C', start.x - hgap / 4, start.y, end.x + hgap / 2, end.y, end.x, end.y]];
  }
});
```
但渲染的效果差强人意
![image](https://user-images.githubusercontent.com/11612990/41392556-f87f5af0-6fd3-11e8-8eed-96b6723a5669.png)

我自己也用这个 edge 定义生成的紧凑树，edge的坐标有点乱
![image](https://user-images.githubusercontent.com/11612990/41392718-0200c392-6fd5-11e8-8ef0-fe30acc603d1.png)

**Comment by TomHuangCN** [comment]
上面两个问题，单独开两个 issue 吧 @jzoe

**Comment by aimagic** [comment]
改动不小 , 何不顺便把所有 behaviour 改成 behavior ?

**Comment by shengbeiniao** [comment]
刚好公司正要开始做一个编辑器，发现2.0的G6太鸡肋，根本没法实现交互，大神， 求1.0的文档，现在看官网的示例demo全是404 
比如:http://antvis.github.io/g6/demo/04-editor/perventLink.html

**Comment by zx8887** [comment]
@shengbeiniao +1

**Comment by wued2017** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
+1



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    发自网易邮箱大师                


    在2018年6月26日 16:05，ByronZheng<notifications@github.com> 写道： 


@shengbeiniao +1

**Comment by shengbeiniao** [comment]
求G6 1.2.8的插件文档，发现和2.0插件不兼容~~

**Comment by gorkys** [comment]
1.x 文档：http://antvis.github.io/g6/doc/index.html   无法打开了？？？

**Comment by cike8899** [comment]
1.x 文档没了 能否把之前的放开？ @TomHuangCN

**Comment by yumenglong** [comment]
1.2.8的文档没有了呢，页面地址404，如果以后该文档不维护了，能不能给个可以下载的线下文档呢？ @TomHuangCN

**Comment by goodwinfame** [comment]
已经用1.x开发了较复杂业务，文档没了真是维护的灾难。希望提供离线文档。

**Comment by Yanyan-Wang** [comment]
> 已经用1.x开发了较复杂业务，文档没了真是维护的灾难。希望提供离线文档。

https://antvis.github.io/old-site/g6/doc/tutorial/start/base.html

> 1.2.8的文档没有了呢，页面地址404，如果以后该文档不维护了，能不能给个可以下载的线下文档呢？ @TomHuangCN



> 1.x 文档没了 能否把之前的放开？ @TomHuangCN

https://antvis.github.io/old-site/g6/doc/tutorial/start/base.html

**Comment by Yanyan-Wang** [comment]
1.x 文档地址：https://antvis.github.io/old-site/g6/doc/tutorial/start/base.html

不再维护 1.x 的新需求与 issues。如有需求强烈建议升级。

**Comment by testteam001** [comment]
@TomHuangCN  跪求g6 1.2.8文档

**Comment by gorkys** [comment]
@testteam001 上面的链接可以打开，如果你不能打开就科学上网一下。
