### ISSUE TITLE
updateLayout开启gpu渲染，布局完成之后页面上会残留某次迭代的图像

### ISSUE THREAD

**Issue by aMiing** [antvis/G6#2651]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/aMiing/vue-g6](https://github.com/aMiing/vue-g6)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/39857637/107174307-dae84280-6a04-11eb-9618-cdcf7e943f20.png)

但如果不用gpu渲染，怎么样对布局过程进行加速呢？

| Environment | Info |
|---|---|
| g6 | 4.1.8 |
| System | - |
| Browser | - |

**Comment by Yanyan-Wang** [comment]
麻烦提供最小复现的在线 demo 吧

**Comment by aMiing** [comment]
不好意思，再次定位后发现不是api的问题
