### ISSUE TITLE
G6脑图树渲染特定数据的树会持续报错

### ISSUE THREAD

**Issue by changedi** [antvis/G6#2652]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g6.antv.vision/zh/examples/tree/mindmap#hRightMindmap](https://g6.antv.vision/zh/examples/tree/mindmap#hRightMindmap)

### Steps to reproduce
import G6 from '@antv/g6';

fetch('https://gw.alipayobjects.com/os/antvdemo/assets/data/algorithm-category.json')
  .then((res) => res.json())
  .then((data) => {
    let x = JSON.parse('{"data":{"id":2,"name":"p2","children":[{"id":3,"name":"p3","children":[{"id":6,"name":"p6"},{"id":7,"name":"p7"}]},{"id":5,"name":"p5","children":[{"id":8,"name":"p8"}]},{"id":4,"name":"p4"}]}}');
    let d = x.data;
    const container = document.getElementById('container');
    const width = container.scrollWidth;
    const height = container.scrollHeight || 500;
    const graph = new G6.TreeGraph({
      container: 'container',
      width,
      height,
      modes: {
        default: [
          {
            type: 'collapse-expand',
            onChange: function onChange(item, collapsed) {
              // const data = item.get('model');
              // data.collapsed = collapsed;
              return true;
            },
          },
          'drag-canvas',
          'zoom-canvas',
        ],
      },
      defaultNode: {
        size: 26,
        anchorPoints: [
          [0, 0.5],
          [1, 0.5],
        ],
      },
      defaultEdge: {
        type: 'cubic-horizontal',
      },
      layout: {
        type: 'mindmap',
        direction: 'H',
        getHeight: () => {
          return 16;
        },
        getWidth: () => {
          return 16;
        },
        getVGap: () => {
          return 10;
        },
        getHGap: () => {
          return 100;
        },
        getSide: () => {
          return 'right';
        },
      },
    });

    let centerX = 0;
    graph.node(function (node) {
      if (node.id === 'Modeling Methods') {
        centerX = node.x;
      }

      return {
        label: node.id,
        labelCfg: {
          position:
            node.children && node.children.length > 0
              ? 'right'
              : node.x > centerX
              ? 'right'
              : 'left',
          offset: 5,
        },
      };
    });

    graph.data(d);
    graph.render();
    graph.fitView();

    if (typeof window !== 'undefined')
      window.onresize = () => {
        if (!graph || graph.get('destroyed')) return;
        if (!container || !container.scrollWidth || !container.scrollHeight) return;
        graph.changeSize(container.scrollWidth, container.scrollHeight);
      };
  });

| Environment | Info |
|---|---|
| g6 | 4.1.7 |
| System | macOS 10.15.6 |
| Browser | Google Chrome 版本 87.0.4280.141（正式版本） (x86_64) |

---
Uncaught TypeError: e.source.getID is not a function
    at t.getModel (styles-718729eb881b2810d2db.js:1)
    at styles-718729eb881b2810d2db.js:1
    at d (styles-718729eb881b2810d2db.js:1)
    at t.refreshPositions (styles-718729eb881b2810d2db.js:1)
    at Object.onFrame (styles-718729eb881b2810d2db.js:1)
    at et (styles-718729eb881b2810d2db.js:1)
    at styles-718729eb881b2810d2db.js:1
    at styles-718729eb881b2810d2db.js:1
    at k (styles-718729eb881b2810d2db.js:1)

**Comment by Yanyan-Wang** [comment]
id 必须是唯一的字符串

https://antv-g6.gitee.io/zh/docs/manual/middle/elements/nodes/defaultNode#%E8%8A%82%E7%82%B9%E7%9A%84%E9%80%9A%E7%94%A8%E5%B1%9E%E6%80%A7
