### ISSUE TITLE
dagre: nodesepFunc not working when workerEnabled == true

### ISSUE THREAD

**Issue by 1994benc** [antvis/G6#2653]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/distracted-ganguly-39tom?file=/src/index.js)

### Steps to reproduce
1. set workerEnabled = true in dagre config 
2. nodesepFunc is not called

| Environment | Info |
|---|---|
| g6 | 4.1.8 |
| System | - |
| Browser | - |

**Comment by Yanyan-Wang** [comment]
Since the web-worker could only read the plain variables but not functions, the `nodesepFunc` is not available for worker mode.

**Comment by 1994benc** [comment]
hi, thanks for your answer. Currently, if we want to vary nodesep depending on node properties and have web  worker enabled, do you know any workaround forr this?

**Comment by Yanyan-Wang** [comment]
For now, it can be only assigned to a constant if you wanna run dagre in web-worker
