### ISSUE TITLE
自定义树  折叠/展开 图标显示错误

### ISSUE THREAD

**Issue by fantian007** [antvis/G6#2654]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://v.antfin.com/zh-cn/g6/3.x/demo/tree/custom-tree.html](http://v.antfin.com/zh-cn/g6/3.x/demo/tree/custom-tree.html)

### Steps to reproduce
1. 点击Classification 折叠，图标变为  +
2. 再点击根节点折叠，再点击根节点展开，Classification 节点的图标变为 - 了，显示不正确
3. Classification 的节点应该是  +

| Environment | Info |
|---|---|
| g6 | 4.1.7 |
| System | mac pro 16 |
| Browser | chrome |

**Comment by Yanyan-Wang** [comment]
emm，你看的这个官网也太考古了，最新官网看这里哈：https://antv-g6.gitee.io/zh/examples/tree/customItemTree#customTree

**Comment by fantian007** [comment]
额，百度排名旧版高，给他加个重定向呗



---原始邮件---
发件人: "Yanyan Wang"<notifications@github.com&gt;
发送时间: 2021年2月18日(周四) 上午10:50
收件人: "antvis/G6"<G6@noreply.github.com&gt;;
抄送: "赵永盛"<1562743134@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [antvis/G6] 自定义树  折叠/展开 图标显示错误 (#2654)




 
emm，你看的这个官网也太考古了，最新官网看这里哈：https://antv-g6.gitee.io/zh/examples/tree/customItemTree#customTree
