### ISSUE TITLE
为什么4.1.8版本在开启svg渲染模式下，不给g元素提供id?

### ISSUE THREAD

**Issue by yizhengfeng-jj** [antvis/G6#2656]
- **G6 Version**:
4.1.8
- **Platform**
mac
谷歌70
- **Mini Showcase(like screenshots)**:
```javascript
treeGraph = new G6.TreeGraph({
        container: container.current,
        width: 1280,
        height: 500,
        pixelRatio: 2,
        renderer: "svg",
        // fitView: true,
        // autoPaint: true,
        modes: {
          default: ["collapse-expand", "drag-canvas", "zoom-canvas"]
        }})
```
- **CodePen Link**:
https://codesandbox.io/s/svg-test-2dpzc

- **问题**
1: 为什么4.1.8 版本在开启svg渲染模式下，不给g元素设置id哇，3.2.9就设置了，导致升级出错了。
2: 项目有一个需求用的是3.2.9。但是现在需要新做一个需求，发现3.2.9已经不能满足了，但是如果升级的话，会有兼容问题，一般怎么解决啊，盼回，感谢

**Comment by Yanyan-Wang** [comment]
设置 id 的目的是什么？原始需求是啥

**Comment by yizhengfeng-jj** [comment]
> 设置 id 的目的是什么？原始需求是啥

3.2.9版本是给了id,之前的同事利用document.getElementById(id)操作了dom,现在没有id就报错了。还有很感谢你这么及时的回复，其实我更想知道我提出的问题第二点，你们一般遇到这种情况是怎么解决的。

**Comment by Yanyan-Wang** [comment]
因为是大版本升级，难免会有 breaking change，升级指南参考下面几个文档：

https://antv-g6.gitee.io/zh/docs/manual/FAQ/upgradeGuide

https://github.com/antvis/G6/issues/2525

**Comment by Yanyan-Wang** [comment]
想要获得指定的图形分组的话，可以通过节点获得，比如希望获得 id 为 node1 的节点的图形分组：

const group = graph.findById('node1').getContainer() 

再获得该分组中的 name 为 'circle-shape' 的图形：

const shape = group.find(e => e.get('name') === 'circle-shape')

这一步是基于绘制节点时，addShape 时给了图形 name 属性。内置节点的每个图形都会给 name，自定义节点如果希望能够找到图形，也需要在绘制节点时，addShape 中设置好 name。

**Comment by Yanyan-Wang** [comment]
图形及图形分组文档：

https://antv-g6.gitee.io/zh/docs/manual/middle/elements/shape/shape-and-properties
https://antv-g6.gitee.io/zh/docs/manual/middle/elements/shape/graphics-group

**Comment by Yanyan-Wang** [comment]
如果这个问题 ok 的话，先关闭这个 issue 了哈，有问题随时新开 issue
