### ISSUE TITLE
Performance issue with dagre layout when using it with polyline

### ISSUE THREAD

**Issue by ankitachdhr145** [antvis/G6#2658]
View with edges takes a lot of time to load with dagre layout and polyline. Moreover the expansion and collapse functionality of combos are effected as well. It takes lot of time to collapse/expand.

Snippet:
layout: {
        type: "dagre",
        rankdir: "LR",
        nodesepFunc: () => 10,
        ranksepFunc: () => 100,
      },

defaultEdge: {
        type: 'polyline',
        size: 1,
        color: "#000000",
        style: {
          radius: 10,
          offset: 30,
          endArrow: true,
        },
        sourceAnchor: 1,
        targetAnchor: 0,
      },

We have 60 nodes and source has one value and target varies for all nodes. 
Example:
 {
      source: '15',
      target: '28',
    },
    {
      source: '15',
      target: '29',
    },
    {
      source: '15',
      target: '30',
    },
{
      source: '15',
      target: '31',
    },
    {
      source: '15',
      target: '32',
    },

Version: 4.1.8    
I suspect its polyline algo which is delaying the collapse and expansion and page load.

**Comment by Yanyan-Wang** [comment]
We suggest you config `controlPoints: true `to the dagre layout, which enables the controlPoints calculation for polylines in the dagre layout algorithm instead of A* router algorithm for generating polylines without controlPoints.

And we are also trying to improve the performance of A* algorithm implementation now.

**Comment by ankitachdhr145** [comment]
When we mark controlPoints: true. It will be no more 'polyline' edge it will be a 'line' and we need 'polyline' edges. But I have now calculated the control points from respective location of nodes. Array of control points did help me to enhance performance but it came with other issues. When we collapse combos, edges disappear or converts into 'line'. I am trying to figure out this one and will wait for your release with the improvements as well. Thanks for the reply.

**Comment by ankitachdhr145** [comment]
When we mark controlPoints: true in layout. It will be no more 'polyline' edge it is a combination of 'line' & 'polyline' edges when we have large number of nodes. But we only need 'polyline' edges. However, I have now calculated the control points from respective location of nodes. Array of control points did help me to enhance performance but it came with other issues. When we collapse combos, edges disappear or converts into 'line'. I am trying to figure out this one and will wait for your release with the improvements as well. Thanks for the reply.

**Comment by Yanyan-Wang** [comment]
Try v4.1.13-beta.3, there are some minor improvements. To prevent frequent re-calculation for polylines while dragging nodes, you can assign `enableDebounce: true` and `enableOptimize: true` to `drag-node` behavior, where `enableOptimize` will hide the related polyline edges while dragging nodes.

**Comment by ankitachdhr145** [comment]
We are not using drag-node behavior at all. We have only ["zoom-canvas", "drag-canvas"].
And I tried with the new version unfortunately the browser crashed again for a scenario where we have 625 nodes.

**Comment by Yanyan-Wang** [comment]
you could also assign `enableOptimize: true` to `drag-canvas` and `zoom-canvas` to hide shapes beside keyShapes to enhance the performance

**Comment by Yanyan-Wang** [comment]
improved by v4.8.1
