### ISSUE TITLE
2.0的自动缩放没起作用

### ISSUE THREAD

**Issue by wanghaolu** [antvis/g6#266]
2.0官网示例的缩放好像没反应呢

**Comment by wanghaolu** [comment]
https://antv.alipay.com/zh-cn/g6/1.x/demo/gallery/gallery-tree-compact-box.html

这个，树，我看代码里面是设置了自动缩放的

**Comment by TomHuangCN** [comment]
你是指 autoZoom ？

https://antv.alipay.com/zh-cn/g6/1.x/api/graph.html#_fitView

**Comment by nsuedu** [comment]
请问怎么设置 初始的缩放比例呢 @ @TomHuangCN

**Comment by TomHuangCN** [comment]
https://antv.alipay.com/zh-cn/g6/1.x/api/graph.html#_zoom @nsuedu

**Comment by nsuedu** [comment]
@TomHuangCN 你说的这个方法是 graph上的，  可我使用Net.zoom(num)没有作用， net没有继承这个方法么
