### ISSUE TITLE
graph.updateItem(item, model, stack)中model为空时报错

### ISSUE THREAD

**Issue by BG5FD** [antvis/G6#2660]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/great-christian-pf532?file=/index.js)

### Steps to reproduce
graph.updateItem这个api在官网文档上显示的是model，stack非必填，但是model不填的情况下会报错。
在上述提供的例子中点击节点即可复现
报错结果如下图所示
![image](https://user-images.githubusercontent.com/27286190/108470266-a86ffc80-72c4-11eb-80c3-cbe661ad98e1.png)

| Environment | Info |
|---|---|
| g6 | 4.1.7 |
| System | win10 |
| Browser | chrome v87 |

**Comment by Yanyan-Wang** [comment]
官网文档有误哈，stack 是选填，前两个必填。感谢指正，文档会尽快修复

**Comment by BG5FD** [comment]
ok，明白了
