### ISSUE TITLE
子节点可以是从+号那里出来么，现在的节点是从父节点本身出来的。

### ISSUE THREAD

**Issue by yizhengfeng-jj** [antvis/G6#2664]
- version
antv g6 4.1.8
- chrome
70
- 例子
https://g6.antv.vision/zh/examples/case/decisionTree#index
- 问题
子节点可以是从+号那里出来么，现在的节点是从父节点本身出来的。

**Comment by Yanyan-Wang** [comment]
不支持的

**Comment by yizhengfeng-jj** [comment]
> 不支持的

感谢你每次及时的回复，今后会考虑用配置项支持下么

**Comment by Yanyan-Wang** [comment]
G6 团队暂时没有对这个的排期哦～ 不过我们非常欢迎社区 PR，如果社区有小伙伴感兴趣，可以参与共建，在这个地方回复 https://github.com/antvis/G6/issues/2535

**Comment by yizhengfeng-jj** [comment]
> G6 团队暂时没有对这个的排期哦～ 不过我们非常欢迎社区 PR，如果社区有小伙伴感兴趣，可以参与共建，在这个地方回复 #2535

哈哈哈哈哈  明白了 我先用明白了再说 感谢了
