### ISSUE TITLE
create-edge模式，添加边的时候，1、偶尔会报错/ 2、从节点一中拉出来线到节点二时，只能拉出来一条边，再此拉的时候就不会触发shouldEnd方法

### ISSUE THREAD

**Issue by yumenglong** [antvis/G6#2665]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/yumenglong/pen/xxEQdZJ?editors=1010](https://codepen.io/yumenglong/pen/xxEQdZJ?editors=1010)

### Steps to reproduce
从节点一中拉出来线到节点二

| Environment | Info |
|---|---|
| g6 | 4.1.8 |
| System | win10 |
| Browser | 谷歌 |

![image](https://user-images.githubusercontent.com/17467365/108591784-666ab780-73a5-11eb-8ef0-21c1a85c0306.png)
![image](https://user-images.githubusercontent.com/17467365/108591786-69fe3e80-73a5-11eb-88e2-597da4387dfd.png)

**Comment by yumenglong** [comment]
补充：

拉线到节点2中 除了小蓝点其他的位置会触发shouldEnd方法，就是拉到小蓝点上不会触发

**Comment by Yanyan-Wang** [comment]
因为你设置的边的 lineAppendWidth 太宽了，导致 drop 事件被前一条边捕获，lineAppendWidth 我改成 1 就正常了

**Comment by yumenglong** [comment]
> 因为你设置的边的 lineAppendWidth 太宽了，导致 drop 事件被前一条边捕获，lineAppendWidth 我改成 1 就正常了

好的  谢谢，

我又发现一个问题，4.1.8版本生成边之后，返回的边的对象中没有返回sourceAnchorIndex和targetAnchorIndex。
https://codepen.io/yumenglong/pen/xxEQdZJ?editors=1010

![image](https://user-images.githubusercontent.com/17467365/108650017-86ab8b00-74f9-11eb-9135-c5c4eed117d6.png)

**Comment by Yanyan-Wang** [comment]
看截图你是在打印之后才 updateItem 给到 targetAnchor 的。updateItem 之后 e.edge.getModel() 里面就会有的
