### ISSUE TITLE
最新版g6与l7冲突

### ISSUE THREAD

**Issue by wisdomsuper** [antvis/G6#2666]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/icy-hill-kd56v?file=/index.jsx)

### Steps to reproduce
去掉G6依赖l7恢复正常

提示

Error
Cannot apply @injectable decorator multiple times.

| Environment | Info |
|---|---|
| g6 | 4.1.10 |
| System | - |
| Browser | - |

---
在一个月前没有问题，今天重新下载依赖后，出现了这个问题
antv/g-webgpu-core/es/inversify.config.js
antv/l7-core/es/inversify.config.js

两处都引用了decorate(injectable(), EventEmitter);

**Comment by wisdomsuper** [comment]
将g6退回4.1.8版本就会恢复正常

**Comment by Yanyan-Wang** [comment]
v4.1.12 修复了哈
