### ISSUE TITLE
设置enabledStack=true，后 crea-edge交互创建表为什么会报错

### ISSUE THREAD

**Issue by fubb-github** [antvis/G6#2667]

**Comment by Yanyan-Wang** [comment]
请提供最小复现的在线 demo

**Comment by fubb-github** [comment]
> 请提供最小复现的在线演示
/*
* 图标示例--->创建边的例子中加入 enabledStack: true 后，创建边功能失效
*/

import G6 from '@antv/g6';

const data = {
  nodes: [
    { id: 'node1', x: 350, y: 200 },
    { id: 'node2', x: 350, y: 250 },
    { id: 'node3', x: 100, y: 200 },
  ],
};
const descriptionDiv = document.createElement('div');
descriptionDiv.innerHTML = 'Click the source and target node to create a new edge.';
const container = document.getElementById('container');
container.appendChild(descriptionDiv);

const width = container.scrollWidth;
const height = (container.scrollHeight || 500) - 20;
const graph = new G6.Graph({
  container: 'container',
  width,
  height,
  linkCenter: true,
  modes: {
    default: ['create-edge'],
  },
  defaultEdge: {
    type: 'quadratic',
    style: {
      stroke: '#F6BD16',
      lineWidth: 2,
    },
  },
enabledStack: true
});

graph.data(data);
graph.render();

graph.on('aftercreateedge', (e) => {
  const edges = graph.save().edges;
  G6.Util.processParallelEdges(edges);
  graph.getEdges().forEach((edge, i) => {
    graph.updateItem(edge, edges[i]);
  });
});

if (typeof window !== 'undefined')
  window.onresize = () => {
    if (!graph || graph.get('destroyed')) return;
    if (!container || !container.scrollWidth || !container.scrollHeight) return;
    graph.changeSize(container.scrollWidth, container.scrollHeight - 20);
  };

**Comment by Yanyan-Wang** [comment]
在 aftercreateedge 中，将 graph.updateItem(edge, edges[i]); 替换为 
```
graph.updateItem(edge, {
  curveOffset: edges[i].curveOffset,
  curvePosition: edges[i].curvePosition
})
```

即可，因为更新整个 edges[i] 的话，有很多其他不需要更新的属性在 stack 的时候也被拷贝了。
