### ISSUE TITLE
2.0版本怎么自定义布局

### ISSUE THREAD

**Issue by littleH1** [antvis/g6#267]
之前版本实现代码

>

            let Layout = G6.Layout;
            let margin = 60;
            let height = 1000 - 2 * margin;
            let width = window.innerHeight - 2 * margin;
            let layout = new Layout.Flow(data);
            nodes = layout.getNodes();
            nodes.map(function(node) {
                let x = node.x * width + margin;
                let y = node.y * height + margin;
                node.x = y;
                node.y = x;
            });

更新了2.0之后要怎么自定义布局

**Comment by TomHuangCN** [comment]
布局接口：https://antv.alipay.com/zh-cn/g6/1.x/api/graph.html#_layout
示例：https://codepen.io/DoriTong/pen/gKLxOY
布局算法：https://github.com/dagrejs/dagre
