### ISSUE TITLE
onWheel 事件在火狐上获取不到x滚动距离？

### ISSUE THREAD

**Issue by yizhengfeng-jj** [antvis/G6#2674]
- version
antv g6 4.1.8
- 火狐
63
- 例子
https://g6.antv.vision/zh/examples/interaction/customBehavior
- 问题
onWheel 事件在火狐上获取不到x滚动距离，打印了下ev信息，并没有想要的，看了一下例子，只能大概设置一下Y的信息

**Comment by Yanyan-Wang** [comment]
火狐浏览器似乎就没有给到滚轮时间 y 的滚动数据，用火狐打开任意网站，把浏览器宽度调小，用触控板滚动只能让网页内容上下滚动，不能左右滚动。

所以如果要兼容火狐，可能需要用户自己对比一下每次 wheel 事件中的 clientX 做判断

**Comment by yizhengfeng-jj** [comment]
> 火狐浏览器似乎就没有给到滚轮事件 y 的滚动数据，用火狐打开任意网站，把浏览器宽度调小，用触控板滚动只能让网页内容上下滚动，不能左右滚动。
> 
> 所以如果要兼容火狐，可能需要用户自己对比一下每次 wheel 事件中的 clientX 做判断
感谢回复，好的

**Comment by Yanyan-Wang** [comment]
那先关掉咯，有问题再开 issue 哈
