### ISSUE TITLE
g6 内部依赖的 g-webgpu-core 的 es module 有问题

### ISSUE THREAD

**Issue by fengChongxiu** [antvis/G6#2675]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
无，见截图

### Steps to reproduce
![image](https://user-images.githubusercontent.com/17736007/108831635-5bae5d80-7605-11eb-808d-0a48f36dec86.png)
![image](https://user-images.githubusercontent.com/17736007/108831649-623cd500-7605-11eb-8809-6d2a5b3e8b3c.png)
![image](https://user-images.githubusercontent.com/17736007/108831682-6ec12d80-7605-11eb-995d-b327b84691af.png)

在使用 rollup 打包时，会报上图的错误，查看 g-webgpu-core 模块，发现 index.js 里依赖了 ISystem 导出的 ISystem, 但是ISystem 模块里实际上没有任何内容

| Environment | Info |
|---|---|
| g6 | 4.1.8 |
| System | - |
| Browser | - |

**Comment by fengChongxiu** [comment]
还有个问题想确认下哈，当我在 rollup 的配置里指定 mainFields: ['module'] 时，
在打包到 g6 这个模块时，会加载 es 模块，但是在加载到 g6-core 这个模块时，由于 package.json 里指定了 browser 字段，就会去加载 dist 下面的文件，但是这个时候外面的 ts 声明就没了，这个问题应该怎么解决呢，我理解是不是在 g6 的 package.json 里也加一个 browser 的字段

**Comment by xiaoiver** [comment]
好的我用 rollup 验证一下，这种仅包含接口的文件应该写成 `d.ts` 的，我尽快修复

**Comment by baizn** [comment]
g6-core package.json 里面没有 browser 字段，打包时也没有打 dist 文件

**Comment by Yanyan-Wang** [comment]
已修复
