### ISSUE TITLE
drag-node 行为有问题，onlyChangeComboSize设定为true, 还是会发生加入别个群组

### ISSUE THREAD

**Issue by samuelhsin** [antvis/G6#2676]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/still-shadow-znpfk?file=/src/App.js)

### Steps to reproduce
把分支节点1拖拽到分支节点3，且完全重合分支节点3的位置，分支节点1就会加入分支节点3的群组，完全无视onlyChangeComboSize

| Environment | Info |
|---|---|
| g6 | 4.1.12 |
| System | - |
| Browser | - |

**Comment by cwtuan** [comment]
+1
