### ISSUE TITLE
怎么修改combo的布局？

### ISSUE THREAD

**Issue by cis1124** [antvis/G6#2677]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在做一个类似项目架构的图，希望以combo作为基本单位来布局，edge也是要连接combo的，包含一些子节点，子节点不用连线。发现combo布局很乱，里面的节点也排列重叠。

### What does the proposed API look like?
可以自定义combo的layout吗？combo内部的节点该怎么控制排列。

**Comment by Yanyan-Wang** [comment]
内置布局有 comboForce，combo 位置是根据内部节点的位置来决定的。自定义布局实际上也是在修改节点的坐标，从而影响 combo 位置

**Comment by wunaidage** [comment]
请问如何在combo内部进行布局?比如comboA用GForce, comboB使用circle

**Comment by Yanyan-Wang** [comment]
> 请问如何在combo内部进行布局?比如comboA用GForce, comboB使用circle

可以尝试使用子图布局，官网上可以搜一下哈

**Comment by wunaidage** [comment]
> > 请问如何在combo内部进行布局?比如comboA用GForce, comboB使用circle
> 
> 可以尝试使用子图布局，官网上可以搜一下哈

谢谢,如果两个子图有交叉节点,或者说一个节点属于两个子图,该如何进行布局呢

**Comment by Yanyan-Wang** [comment]
建议使用两个子图布局之后，把这个重复节点的坐标取一个平均值，或者加权平均

**Comment by Yanyan-Wang** [comment]
之前的版本 G6 给布局的数据很只有 nodes 和 edges，v4.2.1 中把 combos 和与 combo 相关的边也传给了布局。自定义布局的时候可以使用它们了

**Comment by Cyer** [comment]
> 之前的版本 G6 给布局的数据很只有 nodes 和 edges，v4.2.1 中把 combos 和与 combo 相关的边也传给了布局。自定义布局的时候可以使用它们了

@Yanyan-Wang  v4.3.6 获取不到 combo 相关的边， 在 v4.2 下没有问题
