### ISSUE TITLE
关于g6使用worker导入unpkg的脚本的问题

### ISSUE THREAD

**Issue by YanYuanFE** [antvis/G6#2678]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
![image](https://user-images.githubusercontent.com/17774285/108940785-f141ff80-768e-11eb-9e3e-04c252aa360f.png)

### Steps to reproduce
我注意到，g6使用worker导入了一个外部链接的脚本，如果项目部署在内网环境下（与外网隔离的环境），这种方式是否会影响使用？

| Environment | Info |
|---|---|
| g6 | 4.1.9 |
| System | mac |
| Browser | chrome最新 |

**Comment by lxfu1** [comment]
这仅用于特殊布局， 内网环境下用到的话先使用自定义布局，后续会解掉。

**Comment by baizn** [comment]
下个版本会修复掉这个问题，内网环境我们会提供一个入口，把这个链接转成内网链接传进来。

**Comment by baizn** [comment]
layout 配置，设置 workerEnabled 为 true 时，可以通过 workerScriptURL 来指定脚本地址。
