### ISSUE TITLE
使用addItem添加的节点无法使用getNodeDegree

### ISSUE THREAD

**Issue by lmsccc** [antvis/G6#2679]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hungry-frost-todbb?file=/index.js)

### Steps to reproduce
使用了官方的DEMO，然后使用addItem手动添加了一个节点，其ID为9，然后我在window下挂载了graph，在控制台使用window.g.getNodeDegree查找id === 9 节点的度，在4.1.12版本中报错，在3.7.0中返回0

| Environment | Info |
|---|---|
| g6 | 4.1.12 |
| System | windows10 |
| Browser | firefox 85 |

**Comment by lmsccc** [comment]
请问这是BUG还是我遗漏了什么操作？

**Comment by lmsccc** [comment]
@baizn 您好，我看了一下您的修复方式，似乎只是考虑到了新增节点未连线的情况？还有一种情况是addItem新增节点，然后与现有节点连线，再获取新节点的度，此时该新节点的入度或者出度肯定有一个不是0的。我之前debug过，好像是通过addItem添加的节点并不存在于graph的data中，导致计算度的时候出错。

**Comment by Yanyan-Wang** [comment]
4.1.13 修复了哈
