### ISSUE TITLE
拖拽节点进入子网时的问题

### ISSUE THREAD

**Issue by CathyZYF** [antvis/G6#2680]
项目里有这样的需求：批量选中一片区域的节点，希望将这些节点批量放入新建的combo中，由于新建combo比较小，而选中节点的面积比较大，最终的效果是combo识别不了这个操作，反复拖拽多次后才能将这些节点放入子网。请问这种问题，有办法在应用层面优化一下吗？

**Comment by Yanyan-Wang** [comment]
拖拽进入 combo 是根据光标的位置决定的，如果拖拽释放时光标在 combo 内部，则会进入 combo。应该和节点分布面积关系不大

**Comment by Yanyan-Wang** [comment]
请问该问题进展如何

**Comment by Yanyan-Wang** [comment]
请问该问题进展如何

**Comment by CathyZYF** [comment]
谢谢关注，按照你的提示，每次拖拽时将光标置于子网上方，就没有这个问题了

**Comment by Yanyan-Wang** [comment]
那先关掉咯，有问题再开 issue 哈
