### ISSUE TITLE
combo设置了size最小大小后，combo里的node会居中显示，可以设置不让node居中显示吗？

### ISSUE THREAD

**Issue by lichunli6456** [antvis/G6#2682]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
如果有几个设置了size最小大小的combo并排一行，combo里的node设置了坐标后，因为node总是居中显示，这几个combo不会并排在一条线上，

### What does the proposed API look like?
可以设置combo里的node显示位置，不用总是居中

**Comment by Yanyan-Wang** [comment]
combo 的位置由内部元素的位置决定，combo 默认 padding 上下左右是统一值，可以改一下 padding 试试

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。

**Comment by PmcFizz** [comment]
我也遇到了这个问题，请问题主解决了吗？即使将combo 的padding 设置为 [0,0,0,0] 依然是 节点居中，而且会影响到combo的位置。 @Yanyan-Wang @lichunli6456
