### ISSUE TITLE
希望左键点击出现菜单，点击菜单做功能。（就是将右键上下文菜单功能改成左键弹出）

### ISSUE THREAD

**Issue by zwygithub** [antvis/G6#2686]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
右键上下文菜单功能改成左键弹出

### What does the proposed API look like?
插件plugin里边菜单分左键呼出或右键呼出

**Comment by Yanyan-Wang** [comment]
看看社区有没有小伙伴有兴趣做一下哈，还是比较简单的。

你这儿着急使用的话，其实可以自己监听 node:click 然后添加一个 DOM 就好，挂载方式参见 https://g6.antv.vision/zh/docs/manual/advanced/coordinate-system
