### ISSUE TITLE
React 下 树布局 indented 布局错乱

### ISSUE THREAD

**Issue by SunGuoQiang123** [antvis/G6#2687]
首先，建 issue 的链接报错，无法去链接里报错

![image](https://user-images.githubusercontent.com/17311301/109130077-47e13380-778c-11eb-9e86-b8243253c2fb.png)

问题：
react 下 使用树布局中的 indented 布局会错乱～
https://codesandbox.io/s/adoring-hofstadter-ec5ht?file=/index.js

**Comment by Yanyan-Wang** [comment]
demo 中似乎没有渲染出来

**Comment by SunGuoQiang123** [comment]
> demo 中似乎没有渲染出来

![image](https://user-images.githubusercontent.com/17311301/109270687-5e999000-7849-11eb-9dc1-8707d471a5f8.png)
应该要zoom到屏幕中

**Comment by Yanyan-Wang** [comment]
没问题呀，这个不会跟用什么前端框架有关系的。调整一下布局参数 indent: 200
