### ISSUE TITLE
相同类型节点合并

### ISSUE THREAD

**Issue by c1105590204** [antvis/G6#2688]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
节点数量过多时，显示非常混乱

### What does the proposed API look like?
可以把相同类型的节点合并在一起，并用角标显示合并数量，可以关闭和展开这些合并的节点

**Comment by Yanyan-Wang** [comment]
树图可以 collapse-expand，一般图可以用 combo

**Comment by c1105590204** [comment]
> 树图可以 collapse-expand，一般图可以用 combo

不是对树图下所有的子节点collapse-expand，而是把同一个节点下的子节点，相同类型的合并成一个，有点类似下面这种，但是不知道树图可以这么用不
https://antv-g6.gitee.io/zh/examples/net/dagreFlow#dagreCombo

**Comment by Yanyan-Wang** [comment]
combo 适用于一般图。树图如果要收起相同类型节点需要自己做一些操作，比如把相同类型节点数据处理成一个节点，自定义节点绘制角标，用处理后的数据 changeData

**Comment by c1105590204** [comment]
> combo 适用于一般图。树图如果要收起相同类型节点需要自己做一些操作，比如把相同类型节点数据处理成一个节点，自定义节点绘制角标，用处理后的数据 changeData

这样试过了，遇到的问题是展开和关闭是的动画看起来不对，比如展开的时候，现在的动画是合并的节点回到父节点，展开的节点从父节点向下扩散成子节点，但是预期的动画应该是直接由合并的节点向两边扩散成展开的节点（树是从上往下的）

**Comment by Yanyan-Wang** [comment]
我理解你的处理方法和我说的不一样，我的意思不是用树的 collapse-expand ，而是自己控制数据，把需要合并的节点在数据里用一个节点替换，然后点击的时候，再把这个节点替换成多个原有的节点

**Comment by c1105590204** [comment]
> 我理解你的处理方法和我说的不一样，我的意思不是用树的 collapse-expand ，而是自己控制数据，把需要合并的节点在数据里用一个节点替换，然后点击的时候，再把这个节点替换成多个原有的节点

我用的方法就是你说的这样，并没有用树的collapse-expand ，功能也实现了，问题出在动画上，比如展开的时候，是一个节点回到父节点，多个节点从父节散出来，理想中的效果应该是，直接从一个节点向两边散开成为多个节点。

不过我找到另外一个解决方法，通过layout->getHGap方法，可以控制部分节点的横向间距，实现向两边扩散或者向中间合拢的效果。
`
getHGap: e => {
            //水平间隔
            let index = _this.customAnimData.animNodeIds.indexOf(e.id)
            if (index > -1 && index < _this.customAnimData.animNodeIds.length - 1) {
              return _this.customAnimData.currentSpan
            }
            return 20
          }
`

但是方法比较取巧，还是希望可以出一个类似一般图的combo那样收起来的功能。

最后我发现另外一个问题，当开启连接线的动画的时候（流动的虚线），collapse-expand的时候界面会闪一下。

**Comment by Yanyan-Wang** [comment]
棒！ 感兴趣的话可以沉淀一个 demo 哦，写在 codesandbox 之类的都可以，我们可以把它放在官网上方便社区大家一起学习哈，会署名的哦。

**Comment by c1105590204** [comment]
> 棒！ 感兴趣的话可以沉淀一个 demo 哦，写在 codesandbox 之类的都可以，我们可以把它放在官网上方便社区大家一起学习哈，会署名的哦。

乐意分享这个思路
https://codesandbox.io/s/xfc7e?file=/src/App.vue

**Comment by Yanyan-Wang** [comment]
官网增加了一个 demo，有相似需求的同学可以参考一下 https://g6.antv.vision/zh/examples/interaction/treeBehavior#collapseSlibing
