### ISSUE TITLE
能否支持统一画布绘制多颗决策树

### ISSUE THREAD

**Issue by dyj7** [antvis/G6#2690]

**Comment by doc-DJJ** [comment]
同一

**Comment by baizn** [comment]
可以考虑一下，先排期到需求列表中……
有兴趣的话，欢迎提 PR，参考这里：https://github.com/antvis/G6/issues/2535

**Comment by Yanyan-Wang** [comment]
暂时可以通过绘制一个“假的”根节点，连接各个决策树的根节点，然后把“假的”根节点和相关边设置为透明的，或者 graph.hideItem 将其隐藏
