### ISSUE TITLE
unable to start application after adding G6 

### ISSUE THREAD

**Issue by wunaidage** [antvis/G6#2691]
I use angular 9 +  ts 3.8.3 + G6 4.1.12
first seeing 
![image](https://user-images.githubusercontent.com/12276316/109334446-bb3b8180-782e-11eb-80a3-faaf30081f15.png)
after investigation in github I added `skipLibCheck` to true
the compile error gone but in developer tool of Chrome, there's another error blocking
![image](https://user-images.githubusercontent.com/12276316/109334850-3f8e0480-782f-11eb-9594-072cdd37e262.png)

**Comment by Yanyan-Wang** [comment]
Try v4.1.13 pls

**Comment by wunaidage** [comment]
just tried 4.1.13-beta.3 get the same error before 
![image](https://user-images.githubusercontent.com/12276316/109451557-ad971f00-7a1b-11eb-853e-2b0f79824e68.png)

**Comment by baizn** [comment]
What is the content of the project `tsconfig` file? Please refer to the following configuration.
```
{
  "compilerOptions": {
    "outDir": "build/dist",
    "module": "esnext",
    "target": "esnext",
    "lib": ["esnext", "dom"],
    "sourceMap": true,
    "baseUrl": ".",
    "jsx": "react",
    "allowSyntheticDefaultImports": true,
    "moduleResolution": "node",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true,
    "allowJs": true,
    "experimentalDecorators": true,
    "strict": false,
    "esModuleInterop": true
  },
  "exclude": [
    "node_modules",
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest",
    "tslint:latest",
    "tslint-config-prettier"
  ]
}
```

 If an error is reported, can you provide an online reproducible demo, such as codepen,

**Comment by wunaidage** [comment]
Hi thanks for replying. 
after file per file check I finally figured out what happened.
it is due to the application's browser support settings in `.browserslistrc` or `browserslist` file.
the `cannot read property 'webpackChunkAlgorithm'` error will happen if you opt-in to support IE.
if your angular application have to support IE, you might need to drop this library. Sad Story.
@Yanyan-Wang @baizn

**Comment by baizn** [comment]
Thank you very much. Could you give G a PR, and add a file about how to use G6 in angular under [the folder](https://github.com/antvis/G6/tree/master/packages/site/docs/manual/FAQ) here

For how to support IE, we will update the document later. If you have a solution, you can help update [the file](https://github.com/antvis/G6/blob/master/packages/site/docs/manual/FAQ/supportIE.en.md).

**Comment by wunaidage** [comment]
> Thank you very much. Could you give G a PR, and add a file about how to use G6 in angular under [the folder](https://github.com/antvis/G6/tree/master/packages/site/docs/manual/FAQ) here
> 
> For how to support IE, we will update the document later. If you have a solution, you can help update [the file](https://github.com/antvis/G6/blob/master/packages/site/docs/manual/FAQ/supportIE.en.md).

Thank you! PR created https://github.com/antvis/G6/pull/2725

**Comment by 973782523** [comment]
```ts
Error: node_modules/@antv/g6-core/lib/index.d.ts:1:23 - error TS2688: Cannot find type definition file for '_gl-matrix@3.3.0@gl-matrix'.

1 /// <reference types="_gl-matrix@3.3.0@gl-matrix" />
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/@antv/g6-core/lib/item/node.d.ts:68:5 - error TS2416: Property 'getUpdateType' in type 'Node' is not assignable to the same property in base type 'INode'.
  Type '(cfg: ModelConfig) => UpdateType' is not assignable to type '(cfg?: ModelConfig | undefined) => UpdateType'.
    Types of parameters 'cfg' and 'cfg' are incompatible.
      Type 'ModelConfig | undefined' is not assignable to type 'ModelConfig'.
        Type 'undefined' is not assignable to type 'ModelConfig'.

68     getUpdateType(cfg: ModelConfig): UpdateType;
       ~~~~~~~~~~~~~


Error: node_modules/@antv/g6-core/lib/util/index.d.ts:1:23 - error TS2688: Cannot find type definition file for '_gl-matrix@3.3.0@gl-matrix'.

1 /// <reference types="_gl-matrix@3.3.0@gl-matrix" />
```
angular 12   "@antv/g6": "^4.3.6"
Package. json adds the.browserslistrc file

**Comment by Sammion** [comment]
> ```ts
> Error: node_modules/@antv/g6-core/lib/index.d.ts:1:23 - error TS2688: Cannot find type definition file for '_gl-matrix@3.3.0@gl-matrix'.
> 
> 1 /// <reference types="_gl-matrix@3.3.0@gl-matrix" />
>                         ~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> 
> Error: node_modules/@antv/g6-core/lib/item/node.d.ts:68:5 - error TS2416: Property 'getUpdateType' in type 'Node' is not assignable to the same property in base type 'INode'.
>   Type '(cfg: ModelConfig) => UpdateType' is not assignable to type '(cfg?: ModelConfig | undefined) => UpdateType'.
>     Types of parameters 'cfg' and 'cfg' are incompatible.
>       Type 'ModelConfig | undefined' is not assignable to type 'ModelConfig'.
>         Type 'undefined' is not assignable to type 'ModelConfig'.
> 
> 68     getUpdateType(cfg: ModelConfig): UpdateType;
>        ~~~~~~~~~~~~~
> 
> 
> Error: node_modules/@antv/g6-core/lib/util/index.d.ts:1:23 - error TS2688: Cannot find type definition file for '_gl-matrix@3.3.0@gl-matrix'.
> 
> 1 /// <reference types="_gl-matrix@3.3.0@gl-matrix" />
> ```
> 
> angular 12 "@antv/g6": "^4.3.6"
> Package. json adds the.browserslistrc file

Did you fix this issue?

My env is angular 11.0.4 and g6 4.3.6 has the same issue.

Anyone know how to fix this?

**Comment by 973782523** [comment]
> > ```ts
> > 错误：node_modules / @ antv / g6 - core / lib / index 。d 。ts : 1 : 23  - 错误TS2688：无法 找到 类型 定义 文件 为 '_gl矩阵@ 3.3.0 @ GL-矩阵' 。
> > 
> > 1  /// <引用类型= “_ GL-矩阵@ 3.3.0 @ GL-矩阵”/> 〜
> >                         〜〜〜〜〜〜〜〜〜〜〜〜〜〜〜〜〜〜〜〜〜〜〜〜〜错误: node_modules / @ antv / g6 - core / lib / item
> > 
> > 
> > /节点。d 。ts : 68 : 5  - 错误TS2416：房产 “getUpdateType” 在 类型 “节点”是不是 分配 到 了 同一个 属性 的 基础 型 “的inode” 。
> >   类型 '（CFG：ModelConfig）=>更新类型'是不是 分配 到 输入 '（CFG ?: ModelConfig |未定义）=>更新类型' 。
> >     类型 的 参数 “CFG” 和 “CFG” 是 不相容的。
> >       输入 '模型配置| 不明确的'   输入 'ModelConfig' 。
> >         键入 “未定义”是不是 分配 到 键入 “ModelConfig” 。
> > 
> > 68      getUpdateType ( cfg : ModelConfig ) : UpdateType ; 
> >        ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
> > 
> > 
> > 错误：node_modules / @ antv / g6 - core / lib / util / index 。d 。ts : 1 : 23  - 错误TS2688：无法 找到 类型 定义 文件 为 '_gl矩阵@ 3.3.0 @ GL-矩阵' 。
> > 
> > 1  /// <reference types="_gl-matrix@3.3.0@gl-matrix" />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > angular 12 "@antv/g6": "^4.3.6"
> > 包。json 添加 .browserslistrc 文件
> 
> 你解决了这个问题吗？
> 
> 我的 env 是 angular 11.0.4，g6 4.3.6 也有同样的问题。
> 
> 有人知道怎么修这个东西吗？
> 
> ```
> Error: node_modules/@antv/g6-core/lib/util/index.d.ts:1:23 - error TS2688: Cannot find type definition file for '_gl-matrix@3.3.0@gl-matrix'.
> 
> 1 /// <reference types="_gl-matrix@3.3.0@gl-matrix" />
>                         ~~~~~~~~~~~~~~~~~~~~~~~~~~
> node_modules/@antv/g6-core/lib/index.d.ts:1:23 - error TS2688: Cannot find type definition file for '_gl-matrix@3.3.0@gl-matrix'.
> 
> 1 /// <reference types="_gl-matrix@3.3.0@gl-matrix" />
> ```
Hi. Did you figure it out

**Comment by 973782523** [comment]
I have solved the problem and need to add "skipLibCheck":true to tsconfig.json

**Comment by zhangyangeng** [comment]
> I have solved the problem and need to add "skipLibCheck":true to tsconfig.json

oh~Thank you，it's useful
