### ISSUE TITLE
Dagre Layout with sortbyCombo with multipleCombos  is not working

### ISSUE THREAD

**Issue by JyotsnaC** [antvis/G6#2692]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/thirsty-cherry-23dg5?file=/index.js)

### Steps to reproduce
In the above sandobox the version used is 4.1.13-beta.3 . As you see there are Parent Combos in Dagre layout and the sortByCombo does not work if there are parent Combos

| Environment | Info |
|---|---|
| g6 | 4.1.13.beta.3 |
| System | Mac Os latest |
| Browser | Chrome latest |

**Comment by Yanyan-Wang** [comment]
Thanks for reporting, fixed by v4.1.13
