### ISSUE TITLE
⭐️📖 G6 使用案例收集 ( Example Contribution Wanted ) 📖⭐️

### ISSUE THREAD

**Issue by mxz96102** [antvis/G6#2694]
### 缘由 Cause

G6 现在已经正式迈入了4.0+时代，我们很欣慰的看到有越来越多的人使用G6，承蒙各位厚爱，G6目前也在越来越多的场景被使用。与此同时，G6原来的图表案例就相形见绌了，还停留在一个比较基本的案例阶段，他只是展示了一些基本的原子功能案例。所以在这里，我们向社区的各位发出请求，为了让对G6的使用方案有更好的沉淀，希望大家提供自己实际的使用案例，我们将会修改为G6官网的案例，并且附上你的署名，让你的案例在G6官网可以帮助更多的人。

G6 has now officially entered the 4.0+ era and we are pleased to see that more and more people are using G6, and thanks to your love, G6 is now being used in more and more scenarios. At the same time, G6's original diagramming examples are dwarfed by the fact that it is still at a rather basic case stage, he only shows some basic examples of atomic functionality. So here we send out a request to everyone in the community to provide their own actual use cases in order to allow a better sinking of the use scenarios for G6, which we will modify for the G6 website and include your byline so that your cases can help more people on the G6 website.

### 怎样贡献 How To Contribute

> 我们强烈推荐使用codesandbox这样的在线代码平台来贡献你的案例，这样可以让我们更直观的了解你的案例，并且能更好的转化为官网的案例。

> We highly recommend using an online code platform such as codesandbox to contribute your case, as this will give us a more visual understanding of your case and will translate better into the official website.

首先我们推荐使用G6的code sandbox的案例，你需要fork这个案例，在这个案例上进行开发。

Firstly we recommend using the G6 code sandbox case, you will need to fork this case and develop on it.

[![Edit sharp-moore-xci4e](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sharp-moore-xci4e?fontsize=14&hidenavigation=1&theme=dark&view=preview)

写好案例保存后，从github新建issue，选择Example Contribution模版，按步骤完成填写。

Once you have written your case and saved it, create a new issue from Github, select the Example Contribution template and follow the steps to complete it.

**Comment by lijunping365** [comment]
基于 G6 的大数据血缘分析产品：OpenLineage：https://openbytecode.com/openLineage/front/
A graph analysis product based on G6: https://openbytecode.com/openLineage/front/
github：https://github.com/lijunping365/Open-Lineage-Web

![v1 0 0-2](https://user-images.githubusercontent.com/53156279/235862618-e7d567ba-c00f-4916-800c-552ede53629c.png)

**Comment by Martin2037** [comment]
基于G6的Web3可视化交易追溯和被盗分析产品：**「ByteHunter」**，支持ERC20、ERC721以及五条主流EVM公链
官网：https://bytehunter.site
Dashboard（交易追溯+被盗分析）：https://console.bytehunter.site
![image](https://user-images.githubusercontent.com/63692237/237009395-90d09641-1178-4ec4-8547-29a961e6ff24.png)
