### ISSUE TITLE
感觉graph实例缺少一个获取当前视口中心的x,y坐标的方法

### ISSUE THREAD

**Issue by CathyZYF** [antvis/G6#2695]
项目中的一个需求，在刷新数据，重新调用render方法后，保持之前的比例和视口位置，目前只能获取比例，没办法获取视口的位置。

或者有什么替代方法能实现这个要求吗？ @Yanyan-Wang

**Comment by Yanyan-Wang** [comment]
视口中心的 canvas 坐标是 [width/2, height/2]，其中 width height 是实例化图给的值。然后要把 clientXY 转换成 pointXY 可以用现有的 API，参考 https://g6.antv.vision/zh/docs/manual/advanced/coordinate-system

**Comment by Yanyan-Wang** [comment]
v4.2.1 提供了两个新的 API

- getGraphCenterPoint 获取图内容的中心点渲染坐标系下坐标 
- getCanvasByPoint 获取视口中心点渲染坐标系下坐标

详见文档：
https://g6.antv.vision/zh/docs/api/graphFunc/coordinate#graphgetgraphcenterpoint
https://g6.antv.vision/zh/docs/api/graphFunc/coordinate#graphgetviewportcenterpoint
