### ISSUE TITLE
npm run build:site TypeError: Cannot set property 'typescript' of undefined

### ISSUE THREAD

**Issue by zhuolyang** [antvis/G6#2696]
- **G6 Version**: 4.1.13
- **Platform**: centos7 x64
- **Mini Showcase(like screenshots)**:
![newscreen100082129](https://user-images.githubusercontent.com/34100047/109609957-0fb06b00-7b67-11eb-81c6-3b8974379f11.jpg)

- **CodePen Link**:

下载4.1.13版本代码，执行
npm install
npm run bootstrap
npm run build:site
访问本地site的 图标示例，页面闪现后报错 Cannot set property 'typescript' of undefined

>TypeError: Cannot set property 'typescript' of undefined
registerLanguage
node_modules/monaco-editor/esm/vs/basic-languages/_.contribution.js:42
  39 | }
  40 | export function registerLanguage(def) {
  41 |     var languageId = def.id;
> 42 |     languageDefinitions[languageId] = def;
  43 |     languages.register(def);
  44 |     var lazyLanguageLoader = LazyLanguageLoader.getOrCreate(languageId);
  45 |     languages.setMonarchTokensProvider(languageId, lazyLanguageLoader.whenLoaded().then(function (mod) { return mod.language; }));
View compiled
Module../node_modules/monaco-editor/esm/vs/basic-languages/typescript/typescript.contribution.js
node_modules/monaco-editor/esm/vs/basic-languages/typescript/typescript.contribution.js:6
  3 |  *  Licensed under the MIT License. See License.txt in the project root for license information.
  4 |  *--------------------------------------------------------------------------------------------*/
  5 | import { registerLanguage } from '../_.contribution.js';
> 6 | registerLanguage({
  7 |     id: 'typescript',
  8 |     extensions: ['.ts', '.tsx'],
  9 |     aliases: ['TypeScript', 'ts', 'typescript'],
View compiled
__webpack_require__
/root/Demos/site/webpack/bootstrap:832
  829 | };
  830 | 
  831 | // Execute the module function
> 832 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
  833 | 
  834 | // Flag the module as loaded
  835 | module.l = true;
View compiled
fn
/root/Demos/site/webpack/bootstrap:129
  126 | 		);
  127 | 		hotCurrentParents = [];
  128 | 	}
> 129 | 	return __webpack_require__(request);
  130 | };
  131 | var ObjectFactory = function ObjectFactory(name) {
  132 | 	return {
View compiled
./include-loader!./node_modules/monaco-editor/esm/vs/editor/editor.api.js
./node_modules/monaco-editor/esm/vs/editor/editor.api.js?1119:80
__webpack_require__
/root/Demos/site/webpack/bootstrap:832
  829 | };
  830 | 
  831 | // Execute the module function
> 832 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
  833 | 
  834 | // Flag the module as loaded
  835 | module.l = true;
View compiled
fn
/root/Demos/site/webpack/bootstrap:129
  126 | 		);
  127 | 		hotCurrentParents = [];
  128 | 	}
> 129 | 	return __webpack_require__(request);
  130 | };
  131 | var ObjectFactory = function ObjectFactory(name) {
  132 | 	return {
View compiled
Module../node_modules/monaco-editor/esm/vs/basic-languages/fillers/monaco-editor-core.js
node_modules/monaco-editor/esm/vs/basic-languages/fillers/monaco-editor-core.js:1
__webpack_require__
/root/Demos/site/webpack/bootstrap:832
  829 | };
  830 | 
  831 | // Execute the module function
> 832 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
  833 | 
  834 | // Flag the module as loaded
  835 | module.l = true;
View compiled
fn
/root/Demos/site/webpack/bootstrap:129
  126 | 		);
  127 | 		hotCurrentParents = [];
  128 | 	}
> 129 | 	return __webpack_require__(request);
  130 | };
  131 | var ObjectFactory = function ObjectFactory(name) {
  132 | 	return {
View compiled
Module../node_modules/monaco-editor/esm/vs/basic-languages/_.contribution.js
node_modules/monaco-editor/esm/vs/basic-languages/_.contribution.js:1
__webpack_require__
/root/Demos/site/webpack/bootstrap:832
  829 | };
  830 | 
  831 | // Execute the module function
> 832 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
  833 | 
  834 | // Flag the module as loaded
  835 | module.l = true;
View compiled
fn
/root/Demos/site/webpack/bootstrap:129
  126 | 		);
  127 | 		hotCurrentParents = [];
  128 | 	}
> 129 | 	return __webpack_require__(request);
  130 | };
  131 | var ObjectFactory = function ObjectFactory(name) {
  132 | 	return {
View compiled
Module../node_modules/monaco-editor/esm/vs/basic-languages/javascript/javascript.contribution.js
node_modules/monaco-editor/esm/vs/basic-languages/javascript/javascript.contribution.js:1
__webpack_require__
/root/Demos/site/webpack/bootstrap:832
  829 | };
  830 | 
  831 | // Execute the module function
> 832 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
  833 | 
  834 | // Flag the module as loaded
  835 | module.l = true;
View compiled
fn
/root/Demos/site/webpack/bootstrap:129
  126 | 		);
  127 | 		hotCurrentParents = [];
  128 | 	}
> 129 | 	return __webpack_require__(request);
  130 | };
  131 | var ObjectFactory = function ObjectFactory(name) {
  132 | 	return {
View compiled
./include-loader!./node_modules/react-monaco-editor/node_modules/monaco-editor/esm/vs/editor/editor.api.js
./node_modules/react-monaco-editor/node_modules/monaco-editor/esm/vs/editor/editor.api.js?4aeb:78
__webpack_require__
/root/Demos/site/webpack/bootstrap:832
  829 | };
  830 | 
  831 | // Execute the module function
> 832 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
  833 | 
  834 | // Flag the module as loaded
  835 | module.l = true;
View compiled
fn
/root/Demos/site/webpack/bootstrap:129
  126 | 		);
  127 | 		hotCurrentParents = [];
  128 | 	}
> 129 | 	return __webpack_require__(request);
  130 | };
  131 | var ObjectFactory = function ObjectFactory(name) {
  132 | 	return {
View compiled
Module../node_modules/react-monaco-editor/lib/editor.js
node_modules/react-monaco-editor/lib/editor.js:1
__webpack_require__
/root/Demos/site/webpack/bootstrap:832
  829 | };
  830 | 
  831 | // Execute the module function
> 832 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
  833 | 
  834 | // Flag the module as loaded
  835 | module.l = true;
View compiled
fn
/root/Demos/site/webpack/bootstrap:129
  126 | 		);
  127 | 		hotCurrentParents = [];
  128 | 	}
> 129 | 	return __webpack_require__(request);
  130 | };
  131 | var ObjectFactory = function ObjectFactory(name) {
  132 | 	return {
View compiled
Module../node_modules/react-monaco-editor/lib/index.js
node_modules/react-monaco-editor/lib/index.js:1
__webpack_require__
/root/Demos/site/webpack/bootstrap:832
  829 | };
  830 | 
  831 | // Execute the module function
> 832 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
  833 | 
  834 | // Flag the module as loaded
  835 | module.l = true;
View compiled
fn
/root/Demos/site/webpack/bootstrap:129
  126 | 		);
  127 | 		hotCurrentParents = [];
  128 | 	}
> 129 | 	return __webpack_require__(request);
  130 | };
  131 | var ObjectFactory = function ObjectFactory(name) {
  132 | 	return {
View compiled
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.
 
请问如何解决，可以在本地查看 G6 website 图表示例？

**Comment by Yanyan-Wang** [comment]
node_modules 里面有 monaco-editor 重复的版本，删除旧的一个版本

**Comment by zcolin** [comment]
依然碰见此问题，“node_modules 里面有 monaco-editor 重复的版本，删除旧的一个版本”，这个请问如何操作，我现在在node_modules中发现有三个此库关联的 
![image](https://user-images.githubusercontent.com/5196936/112142782-fb193d00-8c11-11eb-9b33-a6438c617e1f.png)
不知该如何删除？
在所有的package.json中也没有发现谁进行的引用。谢谢

**Comment by zcolin** [comment]
请问如何解决的？
