### ISSUE TITLE
Force Layout 自定义 forceSimulation 问题

### ISSUE THREAD

**Issue by songhn233** [antvis/G6#2697]
**G6 Version**: 4.1.13

`layoutCfg.forceSimulation` 中可以指定自定义 force 方法，但是无法获取图配置中的边和节点信息

```js
import * as d3Force from 'd3-force'

layout: {
  type: 'force',
  forceSimulation: d3Force
    .forceSimulation()
    .nodes(this.nodes)
    .force(
      'center',
      d3Force.forceCenter(this.center[0], this.center[1])
    )
    .force('charge', d3Force.forceManyBody())
    .force(
      'link',
      d3Force
      .forceLink()
      .id(d => d.id)
      .links(this.edges)
    )
}
```
如何在 `forceSimulation` 中使用图的边和节点等配置信息？

**Comment by Yanyan-Wang** [comment]
原始需求是什么

**Comment by songhn233** [comment]
需求是重写 `overlapProcess` 这个防碰撞方法，即修改 `d3Force.forceCollide()` 里的参数，但是没有方便的方法所以想通过 `forceSimulation` 来修改，但是仿照原布局添加后无法正常渲染，`forceSimulation` 的实现是有什么特殊要求吗，我在文档中没有找到

**Comment by Yanyan-Wang** [comment]
重写防止碰撞来达到什么目的？现在通过配置 preventOverlap: true 可以防止碰撞的

一定要改 forceSimulation 的话，需要比较 hack 的方法，从 graph 中拿到这个对象去修改

**Comment by songhn233** [comment]
重写碰撞是想让图呈现松散的结构，通过修改 `nodeSize` 也可以达到这样的效果，但是数据中会有不同大小的节点，想让大节点拥有更大的碰撞力，这样是不是需要通过修改 `nodeStrength` 来实现类似的效果

**Comment by Yanyan-Wang** [comment]
如果不指定 nodeSize 的话，会自动取数据中的 size 字段哈。同时还可以用  nodeSpacing 传入函数的形式辅助。nodeStrength 也可以传入函数调整不同节点的斥力，应该也可以达到效果，要注意一下 nodeStrength 负数代表的节点斥力

**Comment by songhn233** [comment]
好的，感谢
