### ISSUE TITLE
更新到 4.1.13 版本后 mindmap 类型树图布局发生错乱

### ISSUE THREAD

**Issue by Rickeyhyq** [antvis/G6#2698]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fragrant-water-hgr0x?file=/src/index.js)

### Steps to reproduce
抱歉没有重现链接
本地开发使用 4.1.7 版本，更新到 4.1.13 后树图布局发生错乱，如图所示
<img width="529" alt="企业微信截图_2aef0c2f-8248-4029-b2bc-5c0d00f7e120" src="https://user-images.githubusercontent.com/25759404/109623015-b1d84f00-7b77-11eb-98d2-bdd7393daee2.png">

降级到 4.1.7 之后预期的布局
<img width="465" alt="企业微信截图_a5df9184-1cf2-4b7d-8b43-687818a634c6" src="https://user-images.githubusercontent.com/25759404/109623055-ba308a00-7b77-11eb-842c-b344b58648cc.png">

layout: {
   type: 'mindmap',
   direction: 'H',
   getVGap: function getVGap() {
      return 120;
   },
   getHGap: function getHGap() {
      return 200;
    },
},

| Environment | Info |
|---|---|
| g6 | 4.1.13 |
| System | MacOS 10.15.7 |
| Browser | Microsoft Edge 86.0.622.69  |

**Comment by Yanyan-Wang** [comment]
是不是 sourceAnchor 和 targetAnchor 设置反了？还是写一下在线复现链接吧，否则难以排查问题呢

**Comment by Rickeyhyq** [comment]
两个版本的代码没有任何区别，4.1.7 是在本地运行的，包版本是一开始开发的时候下载的，生产环境发布的时候重新npm install, 由于 package.json 里面的版本号不是固定死的，今天更新了4.1.13版本之后就变成这样了， sourceAnchor 和 targetAnchor 我没有设置，复现的 demo 有时间我写一下

**Comment by Rickeyhyq** [comment]
复现链接里面代码已更新，应该找到问题所在了，label 文字太长了，但是不清楚为什么已经用 fittingString 方法处理过换行以及最多展示两行文字了，但貌似还是按原来的长度来布局的

**Comment by Yanyan-Wang** [comment]
应该和 label 长度无关，我这边发现是 4.1.13 修复 cubic 的时候的一个遗漏，下个版本会修复一下。着急的话可以先用 4.1.12 版本

**Comment by Gaays** [comment]
> 应该和 label 长度无关，我这边发现是 4.1.13 修复 cubic 的时候的一个遗漏，下个版本会修复一下。着急的话可以先用 4.1.12 版本
你好，请问g6从4.1.8更新到4.1.12项目运行时报以下几个错误是什么情况？我尝试删除node_modules重新安装也不行。
![image](https://user-images.githubusercontent.com/44692140/109743388-93239800-7c0b-11eb-8d07-d22dbede375e.png)

**Comment by Yanyan-Wang** [comment]
> > 应该和 label 长度无关，我这边发现是 4.1.13 修复 cubic 的时候的一个遗漏，下个版本会修复一下。着急的话可以先用 4.1.12 版本
> 
> 你好，请问g6从4.1.8更新到4.1.12项目运行时报以下几个错误是什么情况？我尝试删除node_modules重新安装也不行。
> ![image](https://user-images.githubusercontent.com/44692140/109743388-93239800-7c0b-11eb-8d07-d22dbede375e.png)

可能是 ts 版本太老了。但这些都是 warning，没啥影响吧

**Comment by Gaays** [comment]
> > > 应该和 label 长度无关，我这边发现是 4.1.13 修复 cubic 的时候的一个遗漏，下个版本会修复一下。着急的话可以先用 4.1.12 版本
> > 
> > 
> > 你好，请问g6从4.1.8更新到4.1.12项目运行时报以下几个错误是什么情况？我尝试删除node_modules重新安装也不行。
> > ![image](https://user-images.githubusercontent.com/44692140/109743388-93239800-7c0b-11eb-8d07-d22dbede375e.png)
> 
> 可能是 ts 版本太老了。但这些都是 warning，没啥影响吧

项目会跑不起来
同时控制台会报错
![image](https://user-images.githubusercontent.com/44692140/109749607-f1557880-7c15-11eb-8b99-f1077c14ae85.png)

**Comment by Yanyan-Wang** [comment]
麻烦新开一个 issue 描述以下你的问题哈，目前看起来跟这个 issue 无关。

**Comment by Yanyan-Wang** [comment]
> > > > 应该和 label 长度无关，我这边发现是 4.1.13 修复 cubic 的时候的一个遗漏，下个版本会修复一下。着急的话可以先用 4.1.12 版本
> > > 
> > > 
> > > 你好，请问g6从4.1.8更新到4.1.12项目运行时报以下几个错误是什么情况？我尝试删除node_modules重新安装也不行。
> > > ![image](https://user-images.githubusercontent.com/44692140/109743388-93239800-7c0b-11eb-8d07-d22dbede375e.png)
> > 
> > 
> > 可能是 ts 版本太老了。但这些都是 warning，没啥影响吧
> 
> 项目会跑不起来
> 同时控制台会报错
> ![image](https://user-images.githubusercontent.com/44692140/109749607-f1557880-7c15-11eb-8b99-f1077c14ae85.png)

麻烦新开一个 issue 描述一下你的问题哈，目前看起来跟这个 issue 无关。

**Comment by Yanyan-Wang** [comment]
上述两个问题都在 v4.1.15 解决了哈
