### ISSUE TITLE
G6的render方法是阻塞的么？如何在nodejs端让它一直阻塞，直到图片渲染完成？

### ISSUE THREAD

**Issue by cookiespiggy** [antvis/G6#2699]
const graph = new G6.Graph({
        container: 'mountNode',
        width: 1000,
        height: 600,
        layout: {
            type: 'circular',
            center: [200, 200], // 可选，默认为图的中心
            radius: null, // 可选
            startRadius: 10, // 可选
            endRadius: 100, // 可选
            clockwise: false, // 可选
            divisions: 5, // 可选
            ordering: 'degree', // 可选
            angleRatio: 1, // 可选
        },
    });
    // 读取数据
    graph.data(data);
    // 渲染图
    graph.render();

**Comment by Yanyan-Wang** [comment]
是的

**Comment by cookiespiggy** [comment]
require('@antv/g6') 直接报找不到document了

**Comment by Yanyan-Wang** [comment]
G6 会使用到 document，需要创建容器和 canvas

**Comment by cookiespiggy** [comment]
我通过jsdom解决了，但是现在有个问题，同样的数据，我用d3的力导向布局就很漂亮，但是用g6的force，默认的配置不怎么好看，d3的中心力，弹簧力，电荷力和定位力怎么配置呀

**Comment by cookiespiggy** [comment]
发现了一种现象，在服务端跑g6的布局，force或者gforce布局，视图的结果和grid布局是一致的

**Comment by Yanyan-Wang** [comment]
应该没有运行到正确的 layout，现在是什么版本

**Comment by cookiespiggy** [comment]
我用的是umd的最新版本，也就是npm i @antv/g6 last版本， 但是dist目录下，g6.min的文件日期是1987年的。可以配置日志输出么？我发现新版本没有日志输出了

**Comment by cookiespiggy** [comment]
其他的布局都是可以正确运行的，就是force个gforce这两个的布局有些问题

**Comment by Yanyan-Wang** [comment]
force 是异步的

**Comment by cookiespiggy** [comment]
ok 那我直接用d3去tick了 thx~
