### ISSUE TITLE
使用addItem添加的节点无法正常获取其度

### ISSUE THREAD

**Issue by lmsccc** [antvis/G6#2700]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/practical-edison-5jnqw?file=/index.js)

### Steps to reproduce
在例子中控制台输入g.getNodeDegree('9', 'in') ,回车，在4.1.13中得0，在3.7.3中得1，3.7.3才是期望的结果

| Environment | Info |
|---|---|
| g6 | 4.1.13 |
| System | windows10 |
| Browser | new edge 88 |

**Comment by lmsccc** [comment]
关联 #2679

**Comment by Yanyan-Wang** [comment]
v4.2.1 已解决
