### ISSUE TITLE
'__spreadArray' is not exported from 'tslib'.

### ISSUE THREAD

**Issue by qqxiaofeizhu** [antvis/G6#2702]
![image](https://user-images.githubusercontent.com/23719266/109770856-14dceb00-7c37-11eb-9826-402c7b85fb4f.png)
但是在tslib中没有找到__spreadArray，只有__spreadArrays
![image](https://user-images.githubusercontent.com/23719266/109770950-3342e680-7c37-11eb-8d71-109d24cbfcd1.png)

**Comment by yzStrive** [comment]
+1
![image](https://user-images.githubusercontent.com/32640035/109779946-74d88f00-7c41-11eb-870b-db445df8034f.png)

**Comment by resurrexi** [comment]
This error seems to be related to 4.1.13. I didn't get the error after downgrading to 4.1.12.

**Comment by baizn** [comment]
This __spreadArray method is not available in the lower version of tslib, such version 1.14.x or 2.0.1

**Comment by qqxiaofeizhu** [comment]
> This __spreadArray method is not available in the lower version of tslib, such version 1.14.x or 2.0.1

ts

**Comment by ankitachdhr145** [comment]
+1 in 4.1.13

**Comment by qqxiaofeizhu** [comment]
单独安装tslib到最新的版本，即可解决这个问题

**Comment by huoyuhao** [comment]
> 单独安装tslib到最新的版本，即可解决这个问题
我使用的vue3 ，单独安装 "tslib": "^1.14.1",仍然报错
