### ISSUE TITLE
修改 edge state 能否修改 label 样式

### ISSUE THREAD

**Issue by songhn233** [antvis/G6#2703]
通过修改 `edgeStateStyles` 可以设置激活 state 时边的样式，但是边相应的 label 无法在其中修改样式

**Comment by Yanyan-Wang** [comment]
可以通过指定图形的 name 来修改 label 图形的样式，比如 
edgeStateStyles: {
    active: {
     ...
      'text-shape': {
        fill: "#f00",
         ...
      }
    },
}

内置边的 label 图形的 name 都是 'text-shape'。自定义节点/边的话，要看你 addShape 时给响应图形指定的 name 是什么

参见  https://g6.antv.vision/zh/docs/manual/middle/states/state/#%E9%85%8D%E7%BD%AE-state-%E6%A0%B7%E5%BC%8F
