### ISSUE TITLE
tooltip可以设置鼠标单击显示吗？

### ISSUE THREAD

**Issue by lichunli6456** [antvis/G6#2704]
tooltip现在是鼠标移入节点的时候显示出来，现在有个需求，要把鼠标移入显示提示，改为鼠标单击节点再显示，可以设置么？

**Comment by Yanyan-Wang** [comment]
那你说的提示就是 tooltip，点击节点可以自己挂载一个 DOM 或者用右击出来的 contextmenu 组件。

自己挂载方式参考 https://antv-g6.gitee.io/zh/docs/manual/advanced/coordinate-system

**Comment by Yanyan-Wang** [comment]
v4.2.1 支持 trigger:click  了，见 demo：https://g6.antv.vision/zh/examples/tool/tooltip#tooltipClick
