### ISSUE TITLE
如何将自定节点中的keyShape的节点类型从rect更新为ellipse

### ISSUE THREAD

**Issue by semdy** [antvis/G6#2706]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
原本节点类型为rect，后续交互将rect更新为ellipse

| Environment | Info |
|---|---|
| g6 | 4.0.3 |
| System | - |
| Browser | - |

**Comment by Yanyan-Wang** [comment]
自定义节点的话，建议就不用这个图形作为 keyShape，可以画一个透明的等大的矩形作为 keyShape。然后需要被改的 rect 不是 keyShape，可以删掉，然后重新 addShape 一个图形

group.find(e => e.get('name') === '你的 rect 的 name').remove();
group.addShape(新的图形)

**Comment by semdy** [comment]
尝试过这方式，会有个问题，react之上有文本的，addShape之后会盖住文本，如何调整文本跟shape的zIndex。
我现在的实现方式是：注册两个自定义节点，一个keySpae为react，另一个keyShape为ellipse，然后去切换自定义节点的type就可以了。

**Comment by Yanyan-Wang** [comment]
可以用 shape.toFront shape.toBack 

切换 type 的方式也挺好的

**Comment by semdy** [comment]
感谢
