### ISSUE TITLE
节点 shape 属性应用失败

### ISSUE THREAD

**Issue by EmiyaYang** [antvis/G6#2715]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[ https://antv-issue-helper.surge.sh]( https://antv-issue-helper.surge.sh)

### Steps to reproduce
打开 repo 可以看到节点形状是圆的，与官网示例不一致，shape 属性没有应用上去。

| Environment | Info |
|---|---|
| g6 | 4.1.16 |
| System | - |
| Browser | - |

---
将 g6 降级至 v3 可以解决。

**Comment by Yanyan-Wang** [comment]
没有看到你的复现 demo。你指定节点类型用的 shape 字段吗？4.x 改成用 type 字段指定
