### ISSUE TITLE
自定义树 折叠/展开 连线错误

### ISSUE THREAD

**Issue by QBSymbol** [antvis/G6#2721]
### Implementation

树节点自定义 连线也是自定义
在数据比较多的节点点击展开和收缩时候 树节点间的连线全都乱乱
layout代码：
const defaultLayout = {
      type: 'mindmap',
      center: [200, 200],
      direction: 'H',
      getId: function getId(d) {
        return d.id;
      },
      getHeight: function getHeight() {
        return 16;
      },
      getWidth: function getWidth() {
        return 16;
      },
      getVGap: function getVGap() {
        return 55;
      },
      getHGap: function getHGap() {
        return 130;
      },
      getSide: function getSide(d) {
        if (d.data.nodeType === 'investment') {
          return 'left'
        }
        return 'right'
      }
    };

自定义连线代码：
G6.registerEdge('flow-line', {
      draw(cfg, group) {
        const startPoint = cfg.startPoint;
        const endPoint = cfg.endPoint;
        const { style } = cfg;
        let defaultPathConfig = [
          ['M', startPoint.x, startPoint.y],
          ['L', (startPoint.x + endPoint.x) / 2, (startPoint.y)],
          ['L', (startPoint.x + endPoint.x) / 2, (endPoint.y)],
          ['L', endPoint.x, endPoint.y]
        ];
        const shape = group.addShape('path', {
          attrs: {
            stroke: style.stroke,
            endArrow: 'investment' === cfg.targetNode._cfg.model.nodeType ? '' : style.endArrow,
            path: defaultPathConfig,
          },
        });

        return shape;
      },
    });

**Comment by baizn** [comment]
麻烦提供一个在线 demo，我们排查一下

**Comment by QBSymbol** [comment]
在线演示react demo：https://qbsymbol.github.io/g6-demo/dist/#/
非react项目demo：https://qbsymbol.github.io/g6-demo/flow.html

**Comment by Yanyan-Wang** [comment]
一模一样的数据吗？是否有重复的节点 id ，id 是否是 string 类型。有没有另外通过 addItem 加的边

**Comment by baizn** [comment]
> > 麻烦提供一个在线 demo，我们排查一下
> 
> 非react demo中是没有问题的 但是在react的demo中多点几回连线就乱乱

那应该是 react 中状态处理的问题，你看下连线乱了的时候数据是不是对的，useEffect 中控制渲染的条件也排查下

**Comment by QBSymbol** [comment]
> > > 麻烦提供一个在线 demo，我们排查一下
> > 
> > 
> > 非react demo中是没有问题的 但是在react的demo中多点几回连线就乱乱
> 
> 那应该是 react 中状态处理的问题，你看下连线乱了的时候数据是不是对的，useEffect 中控制渲染的条件也排查下

>>
目前在pc端能正常使用 移动端收起和展开是不正常的 目前支持移动端吗？

**Comment by QBSymbol** [comment]
> 一模一样的数据吗？是否有重复的节点 id ，id 是否是 string 类型。有没有另外通过 addItem 加的边

数据是一样的 没有通过 addItem 加的边

**Comment by Yanyan-Wang** [comment]
升级到最新版本试试，我在新版版用你贴的代码试了下没有问题了。但是因为看不到完整代码不清楚是否和其他部分代码又关系，猜测是有可能展开收起动画过程中，有对数据的额外操作
