### ISSUE TITLE
自定义布局execute方法里取不到edges

### ISSUE THREAD

**Issue by cis1124** [antvis/G6#2722]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com](https://github.com)

### Steps to reproduce
	  graphData.edges = [
        { source: "combo_13", target: "combo_14" },
        { source: "combo_13", target: "combo_15" },
        { source: "combo_14", target: "combo_16" },
        { source: "combo_15", target: "combo_16" },
        { source: "combo_13", target: "combo_17" },
        { source: "combo_17", target: "combo_16" },
      ];
      graphData.combos = [
        { id: "combo_13" },
        { id: "combo_14" },
        { id: "combo_15" },
        { id: "combo_16" },
        { id: "combo_17" },
      ];
      G6.registerLayout("level-layout", {
        /**
         * 定义自定义行为的默认参数，会与用户传入的参数进行合并
         */
        getDefaultCfg() {
          return {};
        },
        /**
         * 执行布局
         */
        execute() {
          console.log("exe:");
          var self = this;
          console.log(self);
          var edges = self.edges;
          var combos = self.combos;
          console.log("edges:");
          console.log(edges);
          console.log("combos:");
          console.log(combos);
        },
        /**
         * 根据传入的数据进行布局
         * @param {object} data 数据
         */
        layout(data) {
          console.log("layout:");
          console.log(data);
        },
        /**
         * 更新布局配置，但不执行布局
         * @param {object} cfg 需要更新的配置项
         */
        updateCfg(cfg) {
          console.log("updateCfg:");
          console.log(cfg);
        },
        /**
         * 销毁
         */
        destroy() {},
      });
      this.graph = new G6.Graph({
        container: "mountNode",
        width: 1600,
        height: 700,
        //linkCenter: true,
        layout: {
          type: "level-layout",
        },
        defaultNode: {
          style: {
            //fill: '#steelblue',
            //stroke: '#eaff8f',
            lineWidth: 3,
          },
        },
        controlPoints: true,
      });
      this.graph.data(graphData);
      this.graph.render();
    },

| Environment | Info |
|---|---|
| g6 | 4.1.16 |
| System | ubuntu |
| Browser | chrome |

---
我想自定义关于combo的布局，但是在execute方法里取到的edges为空，而页面却有edge。
请问是什么原因，如何在里面获得edge？
我在vue里面使用的。

**Comment by Yanyan-Wang** [comment]
https://g6.antv.vision/zh/examples/net/layoutMechanism#customBigraph

可以拿到 edges 的啊。不行的话，提供复现的在线 demo。
跟什么框架也无关

**Comment by cis1124** [comment]
@Yanyan-Wang 我测试了一下，
如果edge的source和target 是nodes的话，可以取到，
如果edge的source和target是combos的话，无法取到。
我现在的edges都是连接combos的，现在在自定义布局里面要怎么取得edges

**Comment by Yanyan-Wang** [comment]
确实是，G6 内部处理了一下只传了两端都是节点的边给到布局。下个版本可以修改一下。

现在你可以不用自定义布局，直接拿到数据去计算节点的 x y 然后挂到节点数据上，再渲染，其实是一样的效果。

**Comment by cis1124** [comment]
@Yanyan-Wang 好的，了解了，多谢。
