### ISSUE TITLE
create-edge与click-select冲突，同时设置时，点击节点高亮失效

### ISSUE THREAD

**Issue by fubb-github** [antvis/G6#2727]
### Contributor

import G6 from '@antv/g6';

const data = {
  nodes: [
    { id: 'node1', x: 350, y: 200, type:'kgNode' },
    { id: 'node2', x: 350, y: 400, type:'kgNode' },
    { id: 'node3', x: 100, y: 200, type:'kgNode' },
    { id: 'node4', x: 20, y: 20 },
  ],
};
const descriptionDiv = document.createElement('div');
descriptionDiv.innerHTML = 'Click the source and target node to create a new edge.';
const container = document.getElementById('container');
container.appendChild(descriptionDiv);

G6.registerNode('kgNode', {
    draw(cfg, group) {
      const cr = 30
      // 背景
      let circle = group.addShape('circle', {
        attrs: {
          x: 0,
          y: 0,
          r: cr,
          cursor: 'pointer',
          fill: cfg.style.fill ? cfg.style.fill : 'green',
          stroke: cfg.style.stroke ? cfg.style.stroke : 'purple',
          lineWidth: cfg.style.lineWidth ? cfg.style.lineWidth : 2,
        },
        name: 'circle-shape',
        draggable: true
      })

      return circle;
    },
    setState(name, value, item) {
      const group = item.getContainer();
      const shape = group.get('children')[0];
      if (name === 'active') {
        if (value) {
          shape.attr('lineWidth', shape.attr('lineWidth') * 2)
        } else {
          shape.attr('lineWidth', 2)
        }
      }
      if (name === 'selected') {
        if (value) {
          shape.attr('stroke', 'blue')
        } else {
          shape.attr('stroke', 'purple')
        }
      }
    }
  })

const width = container.scrollWidth;
const height = (container.scrollHeight || 500) - 20;
const graph = new G6.Graph({
  container: 'container',
  width,
  height,
  linkCenter: true,
  modes: {
    default: ['drag-node', 'zoom-canvas', 'click-select'],
  },
  defaultEdge: {
    type: 'quadratic',
    style: {
      stroke: '#F6BD16',
      lineWidth: 2,
    },
  },
  edgeStateStyles: {
            active: {
              stroke: 'red',
              lineWidth: 4,
            },
            selected: {
              stroke: 'blue',
              shadowBlur: 0,
              shadowColor: "",
            }
          },
});
let flag = false

// 设置鼠标移动或离开节点的样式事件
        graph.on('node:mouseenter', evt => {
          const nodeItem = evt.item;
          if(nodeItem.getModel().id == 'node4') {

          }else {
          graph.setItemState(nodeItem, 'active', true);
          }
        })
        graph.on('node:mouseleave', evt => {
          const nodeItem = evt.item
          if(nodeItem.getModel().id == 'node4') {

          }else {
          graph.setItemState(nodeItem, 'active', false)
          }
        })
        graph.on('node:click', evt => {
          // 先将所有当前状态是click的节点、边置为非click状态
          const nodeItem = evt.item
          flag = !flag
          if(nodeItem.getModel().id == 'node4') {
            if (flag) {
              graph.addBehaviors({
                type: 'create-edge',
              }, 'default');
              graph.on('aftercreateedge', (e) => {
                const edges = graph.save().edges;
                G6.Util.processParallelEdges(edges);
                graph.getEdges().forEach((edge, i) => {
                  graph.updateItem(edge, {
                    curveOffset: edges[i].curveOffset,
                    curvePosition: edges[i].curvePosition,
                  });
                });
              });
            } else {
              graph.removeBehaviors('create-edge', 'default');
              graph.off('aftercreateedge')
            }
          }else {
          graph.setItemState(nodeItem, 'selected', true)
          nodeItem._cfg.edges.forEach(edge => {
            graph.setItemState(edge, 'selected', true)
          });
          }
        })
        // 设置鼠标移动或离开边的样式事件
        graph.on('edge:mouseenter', evt => {
          const edgeItem = evt.item;
          graph.setItemState(edgeItem, 'active', true);
        })
        graph.on('edge:mouseleave', evt => {
          const edgeItem = evt.item
          graph.setItemState(edgeItem, 'active', false);
        })
        graph.on('edge:click', evt => {
          // 先将所有当前状态是click的节点、边置为非click状态
          const edgeItem = evt.item;
          graph.setItemState(edgeItem, 'selected', true);
        })

        graph.on('click', (ev) => {
          graph.getNodes().forEach(node => {
            graph.clearItemStates(node);
          });
          graph.getEdges().forEach(edge => {
            graph.clearItemStates(edge);
          });
        });

graph.data(data);
graph.render();

if (typeof window !== 'undefined')
  window.onresize = () => {
    if (!graph || graph.get('destroyed')) return;
    if (!container || !container.scrollWidth || !container.scrollHeight) return;
    graph.changeSize(container.scrollWidth, container.scrollHeight - 20);
  };

**Comment by Yanyan-Wang** [comment]
把  node:click 里面的 graph.setItemState(nodeItem, 'selected', true) 去掉。因为在 click-select behavior 里面，会判断已经是 selected 状态的节点就恢复为 selected false。
