### ISSUE TITLE
表单绑定节点的model值，只更新后但是视图中文字没有更新

### ISSUE THREAD

**Issue by chunfeilvlv** [antvis/G6#2729]
使用一下方法添加文字， 表单绑定节点的model中sub，值更新后，使用 this.graph.updateItem(item, { [key]: value });方法，但是视图中文字没有更新
group.addShape('text', {
      attrs: {
        text: cfg.sub,
        x: -10,
        y: 30,
        fontSize: 11,
        fontWeight: 400,
        textAlign: 'left',
        textBaseline: 'middle',
        fill: 'rgba(0,0,0,0.45)',
        cursor: 'pointer',
      },
      name: 'name-text-shape',
    });

**Comment by Yanyan-Wang** [comment]
这个 addShape 是在 draw 方法里写的吗？update 的时候会走 update 方法的，没有复写 update 的话会走父类的 udpate，如果你希望 update 的时候重新走一遍 draw，就把 udpate 复现为 undefined

**Comment by chunfeilvlv** [comment]
addShape是在基类里afterDraw里面写的，调用this.graph.updateItem(item, { [key]: value })时afterDraw里面的addShape是不是不会触发更新？

**Comment by chunfeilvlv** [comment]
> 这个 addShape 是在 draw 方法里写的吗？update 的时候会走 update 方法的，没有复写 update 的话会走父类的 udpate，如果你希望 update 的时候重新走一遍 draw，就把 udpate 复现为 undefined

addShape是在基类里afterDraw里面写的，调用this.graph.updateItem(item, { [key]: value })时afterDraw里面的addShape是不是不会触发更新？

**Comment by Yanyan-Wang** [comment]
是的，把 update 复写为 undefined

**Comment by chunfeilvlv** [comment]
> 是的，把 update 复写为 undefined

我在当前自定义的节点设置update ：undefined,没有效果，为什么绑定原有的配置label可以更新，但是addShape文本时里面的文字不可以？麻烦大佬给个样例呗！

**Comment by Yanyan-Wang** [comment]
> > 是的，把 update 复写为 undefined
> 
> 我在当前自定义的节点设置update ：undefined,没有效果，为什么绑定原有的配置label可以更新，但是addShape文本时里面的文字不可以？麻烦大佬给个样例呗！

在哪里设置的 update: undefined？要在自定义节点里复写，和 draw、drawShape 平级。再有问题请提供在线复现 demo

**Comment by Yanyan-Wang** [comment]
解决了么？

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
