### ISSUE TITLE
如何通过点击按钮出发节点node的click?

### ISSUE THREAD

**Issue by confidence68** [antvis/g6#273]
例如，点击左侧菜单，右侧相应的node选中，选中样式就是点击的clickActive 样式

![qq 20180606164721](https://user-images.githubusercontent.com/3736355/41027328-4e701106-69a9-11e8-83cb-75b590070ab5.png)

点击左侧按钮，右侧相应node选中，如何实现？

**Comment by TomHuangCN** [comment]
请重新新建一个 issue，并按照模版提交，感谢。
