### ISSUE TITLE
4.2版本下circle型Combo在折叠情况下连线显示异常

### ISSUE THREAD

**Issue by zlc-Moon** [antvis/G6#2731]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/zlc-moon/pen/Pobxvbj](https://codepen.io/zlc-moon/pen/Pobxvbj)

### Steps to reproduce
g6版本 4.2
由官网例子：https://antv-g6.gitee.io/zh/examples/item/defaultCombos#circle
添加两个edges及combo的collaged: true属性后发生该问题
![image](https://user-images.githubusercontent.com/61084457/110655950-7afadc80-81fa-11eb-9765-d04774b02c62.png)
codepen地址：https://codepen.io/zlc-moon/pen/Pobxvbj

该问题发生在4.2版本下，同样的代码，在4.1.16上，可正常显示。

![image](https://user-images.githubusercontent.com/61084457/110656141-a2ea4000-81fa-11eb-9593-53a59d96813f.png)

| Environment | Info |
|---|---|
| g6 | 4.2.0 |
| System | Windows 10 |
| Browser | chrome |

**Comment by Yanyan-Wang** [comment]
谢谢。应该是修改 rect 连线异常的时候牵连到了……下个小半修复

**Comment by Yanyan-Wang** [comment]
v4.2.1 已解决
