### ISSUE TITLE
Minimap cursor icon while dragging [Chrome on Windows 10]

### ISSUE THREAD

**Issue by 1994benc** [antvis/G6#2732]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g6.antv.vision/en/examples/tool/minimap#minimap](https://g6.antv.vision/en/examples/tool/minimap#minimap)

### Steps to reproduce
On the minimap, drag the handler to pan around the map. While dragging, the mouse cursor icon turns into a forbidden icon (a circle with a slash). I don't see this happen in firefox. Seems to only happen in Chrome on Windows 10

| Environment | Info |
|---|---|
| g6 | 4.2.0 |
| System | Windows 10 |
| Browser | Chrome |

**Comment by Yanyan-Wang** [comment]
Does it affect the use of the Minimap?

**Comment by 1994benc** [comment]
The minimap still works but it affects the UX. The forbidden cursor icon makes our users think that they should not be dragging the minimap

**Comment by Yanyan-Wang** [comment]
Fixed by 4.2.1
