### ISSUE TITLE
Getting issue with this.graph.render(): TypeError: Cannot read property 'stateStyles' of undefined

### ISSUE THREAD

**Issue by ankitachdhr145** [antvis/G6#2735]
Version: 4.2.0
In order to solve the issue: https://github.com/antvis/G6/issues/2658 
We have defined our own polyline control points using following method until we dont get a fix.

graph.edge((edge) => {
  return {
    id: edge.id,
    type: 'polyline',
    style: {
      fill: 'steelblue',
    },
  };
});

But when we call this.graph.render() on any expansion/collapsion of combos(we are expanding on "combo:click") we are getting following error and all the edges disappear. This error doesnt come if we dont use the graph.edge((edge)) method. Error details are as below:

status-manager.service.ts:56 **TypeError: Cannot read property 'stateStyles' of undefined**
    at ItemController.addItem (item.js:67)
    at Graph.AbstractGraph.addItem (graph.js:1107)
    at Graph.AbstractGraph.add (graph.js:1174)
    at graph.js:1362
    at each (each.js:10)
    at Graph.AbstractGraph.render (graph.js:1361)
    at Graph.<anonymous> (home.component.ts:505)
    at doEmit (index.js:61)
    at Graph.push.../../node_modules/@antv/event-emitter/esm/index.js.EventEmitter.emit (index.js:64)
    at EventController.onCanvasEvents (event.js:139)

**Comment by Yanyan-Wang** [comment]
Please provide a reproduced online demo

**Comment by ankitachdhr145** [comment]
Sure I will try to replicate. But for your information we expand the combo on 

this.graph.on("combo:click", (e) => {
      this.graph.collapseExpandCombo(e.item);
      this.graph.render();
      }
});

**Comment by ankitachdhr145** [comment]
We can close this issue as it was an issue from our side we were having an explicit check for 'edge.isVedge(); which was coming as undefined. Sorry and thanks :)
