### ISSUE TITLE
tooltip 提示框左边边缘设置一个最小left值为0，不然会超左边就看不到内容了

### ISSUE THREAD

**Issue by yh0210** [antvis/G6#2736]
g6版本 3.0的bug

[官网示例，提示框文字多输点](https://g6.antv.vision/zh/examples/tool/tooltip#tooltip)

![image](https://user-images.githubusercontent.com/31431699/110888369-fa85ca00-8326-11eb-8cf1-ef24ea1b5720.png)

**Comment by Yanyan-Wang** [comment]
这个是由于右侧已经不够的情况下，将 tooltip 调整到了鼠标点击处的左侧。建议长文本的 tooltip 做一下换行

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
