### ISSUE TITLE
怎么通过其他dom去控制画布的缩放

### ISSUE THREAD

**Issue by dlspacezero** [antvis/G6#2737]

**Comment by dlspacezero** [comment]
我想实现一个通过画布左上角的加号按钮去控制画布的缩放,有api能实现这个功能吗

**Comment by xdddst** [comment]
> 我想实现一个通过画布左上角的加号按钮去控制画布的缩放,有api能实现这个功能吗

https://g6.antv.vision/zh/docs/api/graphFunc/transform/#graphzoomratio-center
