### ISSUE TITLE
RangeError: Maximum call stack size exceeded on clone.ts

### ISSUE THREAD

**Issue by goseign** [antvis/G6#2738]
RangeError: Maximum call stack size exceeded
    at t (clone.ts:3)
    at t (clone.ts:21)
    at t (clone.ts:21)
    at t (clone.ts:21)
    at t (clone.ts:21)
    at t (clone.ts:21)
    at t (clone.ts:21)
    at t (clone.ts:21)
    at t (clone.ts:21)
    at t (clone.ts:21)

import isArray from './is-array';
var clone = function (obj) {
    if (typeof obj !== 'object' || obj === null) {
        return obj;
    }
    var rst;
    if (isArray(obj)) {
        rst = [];
        for (var i = 0, l = obj.length; i < l; i++) {
            if (typeof obj[i] === 'object' && obj[i] != null) {
                rst[i] = clone(obj[i]);
            }
            else {
                rst[i] = obj[i];
            }
        }
    }
    else {
        rst = {};
        for (var k in obj) {
            if (typeof obj[k] === 'object' && obj[k] != null) {
                rst[k] = clone(obj[k]);
            }
            else {
                rst[k] = obj[k];
            }
        }
    }
    return rst;
};
export default clone;
//# sourceMappingURL=clone.js.map

**Comment by goseign** [comment]
While using graph.changeData(data)

**Comment by Yanyan-Wang** [comment]
Which version of G6 are you using? Please provide an online reproduced demo.

**Comment by goseign** [comment]
4.2.0, I will prepare when I have time.

From: Yanyan Wang ***@***.***>
Date: Sunday, March 14, 2021 at 7:28 PM
To: antvis/G6 ***@***.***>
Cc: Xu Bin ***@***.***>, Author ***@***.***>
Subject: Re: [antvis/G6] RangeError: Maximum call stack size exceeded on clone.ts (#2738)

Which version of G6 are you using? Please provide an online reproduced demo.

**Comment by goseign** [comment]
I think the problem is this API (setItemState):
clusters.forEach( (node) => {
  const clusterNode = graph.findById(node.cluster);
 
  if (clusterNode)
    graph.setItemState(cluster, "muted", true);
}
It works fine after i replace it with:
  graph.updateItem(clusterNode, {
    style: {
       opacity: 0.2,
    },
 }); 

Not a lot of nodes though.

**Comment by mxz96102** [comment]
In my opinion, the problem is your data has a circular reference somewhere cause the clone StackOverflow, check your data through console.log before you render

**Comment by Yanyan-Wang** [comment]
> I think the problem is this API (setItemState):
> clusters.forEach( (node) => {
> const clusterNode = graph.findById(node.cluster);
> 
> if (clusterNode)
> graph.setItemState(cluster, "muted", true);
> }
> It works fine after i replace it with:
> graph.updateItem(clusterNode, {
> style: {
> opacity: 0.2,
> },
> });
> 
> Not a lot of nodes though.

I need an online reproduced demo to figure out the problem.

**Comment by Qiupengcheng** [comment]
I have the same problem too.

It occurs when I use plugin `Tooltip` and call `graph.changeData(data)`.
(使用tooltip插件，在某处调用changeData的时候，必现)

version: 4.2.1

**Comment by Yanyan-Wang** [comment]
> I have the same problem too.
> 
> It occurs when I use plugin `Tooltip` and call `graph.changeData(data)`.
> (使用tooltip插件，在某处调用changeData的时候，必现)
> 
> version: 4.2.1

请给出最小复现的在线 demo

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。

**Comment by pwpow** [comment]
> In my opinion, the problem is your data has a circular reference somewhere cause the clone StackOverflow, check your data through console.log before you render

确实是这样，若需要访问节点的父节点，可使用evt.item._cfg.parent

**Comment by chinaxcy** [comment]
我也遇到这个问题了，就是在收展节点时出现的

**Comment by podf** [comment]
Version 4.7.3 
Error: Maximum call stack size exceeded 
这个问题在困扰了我两天了已经， 我的布局中存在combo，若把combo数据剔除则渲染正常。 所以官方是否可以从combo布局入手来解决社区中大量用户存在栈溢出的问题，以至于图无法渲染。

**Comment by jsteenkamp** [comment]
Version 4.8.17
Error: Maximum call stack size exceeded

I am using `comboCombined` layout

1. If I do not interact with graph and save using `data = graph.save()` and then load using `graph.changeData(data)` it works however the graph layout is different.

2. If I interact with the graph with any events where I change combo/node/edge state and save and then load I get the call stack error. I use `item.update( ... )`, `item.setState( ...)`, `item.clearStates( ... )`, `item.toFront()`, `item.toBack()` in most interactions.

I tested the data before save using `JSON.stringify(data)` and this is fine in 1 however for 2 it returns a circular reference error. I have not inspected items in detail but it looks like changing item creates a circular reference.
