### ISSUE TITLE
有闭合节点功能吗

### ISSUE THREAD

**Issue by wolfboys** [antvis/g6#274]
首先非常非常感谢您的无私奉献,作为开发者向你们学习
目前我有个工作流的图形展示,一直找不到一个合适的js展示效果,下图是一个比较丑的展示
![963b80e9-7f30-4f6d-94d1-782c1ca81dfa](https://user-images.githubusercontent.com/13284744/41032642-96babb7a-69b6-11e8-9561-6c0fccabdbd1.png)

其中涉及到节点的闭合(b,c节点同时指向子节点d),看了文档和表例.里面貌似都没有这张多个节点闭合的，只有节点往下无限展开的示例.还请指示,谢谢

**Comment by TomHuangCN** [comment]
不是很明白闭合节点的含义，不过你这个场景，应该不难：https://codepen.io/DoriTong/pen/ZRJLOR?editors=1010
