### ISSUE TITLE
g6 使用自带layout 提示不存在

### ISSUE THREAD

**Issue by zhangxinjie2017** [antvis/G6#2740]
layoutMethod = new Layout[layoutType](layoutCfg);  返回undefined  ；请问下哪些原因会导致会导致的。

**Comment by Yanyan-Wang** [comment]
哪个版本的 G6 ？请提供一下最小在线复现 demo

**Comment by zhangxinjie2017** [comment]
"@antv/g6": "4.1.12" 排查出来了, 是importScripts（'https://unpkg.com/@antv/layout@lastes/dist/dist/layout.min.js'）这行代码 引入失败报错的，因为是内网开发；
我想知道什么情况下需要引入这个，因为在不同项目中，有的会这个报错，有的不会报错

**Comment by Yanyan-Wang** [comment]
因为现在在 worker 中，layout 包是打包成 umd 之后使用的。这个外网地址内网访问不到，可以自己传入内网的地址给到 worker的 importScripts

**Comment by Yanyan-Wang** [comment]
另外，更新一下最新版本

**Comment by Yanyan-Wang** [comment]
应该是使用了 workerEnabled 的情况下会报错
