### ISSUE TITLE
使用RobotFramework进行自动化测试时，如何获取G6中的子元素？

### ISSUE THREAD

**Issue by zhouguanxing** [antvis/G6#2742]
如下图，我需要获取图中的子元素，但是目前只能获取整个G6画布, 
该问题需要如何处理？ 谢谢！
![image](https://user-images.githubusercontent.com/31557028/111246537-6460e500-8641-11eb-8358-61846a4957bc.png)

**Comment by Yanyan-Wang** [comment]
基于 Canvas 的内容不是 DOM 元素，审查是审查不到的。graph.getGroup() 可以拿到所有图形分组和图形

**Comment by zhouguanxing** [comment]
> 基于 Canvas 的内容不是 DOM 元素，审查是审查不到的。graph.getGroup() 可以拿到所有图形分组和图形

谢谢！
