### ISSUE TITLE
Dagre类型，TB布局，节点不能中心对齐

### ISSUE THREAD

**Issue by whu-luojian** [antvis/G6#2743]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g6.antv.vision/zh/docs/manual/middle/layout/graph-layout#dagre](https://g6.antv.vision/zh/docs/manual/middle/layout/graph-layout#dagre)

## 布局：
```
layout: {
     type: 'dagre',
     rankdir: 'TB',
     nodesep: 60,
     ranksep: 30,
     controlPoints: false
}
```

## 节点绘制：

有两个矩形：一个 width 为 40，一个 width 为 100

<img width="349" alt="屏幕截图 2021-03-16 163028" src="https://user-images.githubusercontent.com/20733943/111278813-f46c5200-8674-11eb-9957-86b9a9b805fd.png">

## 结果

节点并未中心对齐，而是左对齐

<img width="275" alt="屏幕截图 2021-03-16 163219" src="https://user-images.githubusercontent.com/20733943/111279019-35fcfd00-8675-11eb-9021-a044ddec63f8.png">

| Environment | Info |
|---|---|
| g6 | 4.2.1 |
| System | - |
| Browser | - |

**Comment by Yanyan-Wang** [comment]
自定义节点时，rect 的 x y 各减去 width  和 height 的一半

x: - width / 2,
y: -height / 2

**Comment by whu-luojian** [comment]
x, y 是节点中心！
