### ISSUE TITLE
nodeStateStyles不能设置node size

### ISSUE THREAD

**Issue by lmhgithi** [antvis/G6#2745]
nodeStateStyles不能设置node size
以及设置fontWeight在第一次变更state的时候，text-shape（即label）的fontweight只会变到500，而不是我希望的700，之后才会正常。
```
  nodeStateStyles: {
    customHighlight: {
      size:14,    //想要变更node size无效
      'text-shape': {
        fontSize: 13,
        fontWeight: 700,
      },
    },
    dark: {
      opacity: 0.2,
      'text-shape': {
        opacity: 0.2,
        fontSize: 11,
      },
    },
  },
```

**Comment by Yanyan-Wang** [comment]
no de S ta te

**Comment by Yanyan-Wang** [comment]
nodeStateStyles 设置的是各个状态下的 style。size 字段不在 style 中。关于大小的 style 可以设置 r （circle）或者 width height （rect）。

第二个问题我试了一下是正常的，有问题的话提供一下在线复现 demo

**Comment by lmhgithi** [comment]
设置r确实可以了~谢谢~
第二个问题暂时还提供不了demo，先设置500凑合吧
