### ISSUE TITLE
360极速版兼容模式下搜索功能无效

### ISSUE THREAD

**Issue by 601075074** [antvis/G6#2746]
- **G6 Version**:3.8.3
- **Platform**:360极速版兼容模式
- **Mini Showcase(like screenshots)**:

- **CodePen Link**:

下面是搜索这块的代码，360极速版兼容模式下找不到节点，其他模式都是好的，希望能知道原因
  // 搜索
  const search = nodeInfo => {
    if (graph) {
      if (nodeInfo) {
        const { path } = nodeInfo;
        // path = '0|'+path;
        const pathArr = path.split('|');
        const ids = nodeInfo.path;
        pathArr.pop();
        G6.Util.traverseTree(graph.cfg.data, item => {
          const itemData = item;
          itemData.collapsed = true;
          pathArr.forEach(v => {
            if (itemData.ids === v) {
              itemData.collapsed = false;
            }
          });
        });
        graph.changeData(graph.cfg.data);
        const node = graph.findById(ids);
        if (!node) return;
        graph.setItemState(node, 'click', true);
        graph.fitCenter();

        graph.focusItem(node, true);
        // 一键收起可点击
        collapseNum = 0;
        // 侧边栏展开
        backData.id = nodeInfo.id;
        backData.desc = nodeInfo.description;
        getAtlasData(backData);
      } else {
        message.warning('暂无搜索结果');
      }
    }
  };

**Comment by Yanyan-Wang** [comment]
不是很清楚，看下控制台有没有报错。打印出来 node 看下，看下是没有找到还是其他原因

**Comment by 601075074** [comment]
昨天已经发现是findById这个方法找不到节点，实际上是有这个节点的，但是经过resize之后找不到了，具体原因还不清楚，我这边不知道为啥没法登陆GitHub了，所以忘记关闭了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/G6"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月18日(星期四) 下午3:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [antvis/G6] 360极速版兼容模式下搜索功能无效 (#2746)





 
不是很清楚，看下控制台有没有报错。打印出来 node 看下，看下是没有找到还是其他原因

**Comment by Yanyan-Wang** [comment]
是和 resize 有关系么？跟浏览器没关系么

**Comment by 601075074** [comment]
对的，在resize函数里面重新走了一遍&nbsp; &nbsp;new G6.TreeGraph 然后就找不到对应的节点了。因为这边有一个需求浏览器全屏，但是全屏之后canvas大小没有重置，所以用了resize，如果有较好的办法触发重置canvas大小，麻烦告知一下，文档里面提供的类似graph.refreshLayout(true)等方法都没有效果




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/G6"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月18日(星期四) 下午3:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [antvis/G6] 360极速版兼容模式下搜索功能无效 (#2746)





 
是和 resize 有关系么？跟浏览器没关系么

**Comment by Yanyan-Wang** [comment]
TreeGraph 中的节点如果是被收起来了 collapsed 的状态下，是不能通过 graph.findById 找到的，应该可以通过 
 graph.findDataById 找到 https://g6.antv.vision/zh/docs/api/treeMethods#finddatabyidid-target。不清楚是不是这个原因。还有就是看下 id 有没有被改过

**Comment by 601075074** [comment]
你提供的方法是4.0之后的版本的，我这个项目去年只有3.0版本的时候做的，顺便问一句，升级到4.0会有影响嘛，有没有升级日志


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/G6"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月18日(星期四) 下午4:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [antvis/G6] 360极速版兼容模式下搜索功能无效 (#2746)





 
TreeGraph 中的节点如果是被收起来了 collapsed 的状态下，是不能通过 graph.findById 找到的，应该可以通过
 graph.findDataById 找到 https://g6.antv.vision/zh/docs/api/treeMethods#finddatabyidid-target。不清楚是不是这个原因。还有就是看下 id 有没有被改过

**Comment by Yanyan-Wang** [comment]
有一定的 breaking change ，需要一些修改，参考：

3.3 之前的版本先参考：https://g6.antv.vision/zh/docs/manual/FAQ/upgradeGuide
升级到 4.1 以上：https://github.com/antvis/G6/issues/2525

**Comment by 601075074** [comment]
OK，了解，抽空新开分支升级一下。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/G6"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月18日(星期四) 下午4:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [antvis/G6] 360极速版兼容模式下搜索功能无效 (#2746)





 
有一定的 breaking change ，需要一些修改，参考：
 
3.3 之前的版本先参考：https://g6.antv.vision/zh/docs/manual/FAQ/upgradeGuide
 升级到 4.1 以上：#2525

**Comment by 601075074** [comment]
这种因为节点高度问题导致的布局重叠有什么解决办法嘛，GitHub卡住了，试试这里能问不


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/G6"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月18日(星期四) 下午5:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [antvis/G6] 360极速版兼容模式下搜索功能无效 (#2746)





 
Closed #2746.
