### ISSUE TITLE
是否有支持透视表格的计划？

### ISSUE THREAD

**Issue by xlhtc007** [antvis/G6#2747]
现在可视化图的解决方案有很多，但是支持配置化报表的方案很少，咱们是否有计划支持数据驱动的报表配置方案

**Comment by Yanyan-Wang** [comment]
G6 解决图可视化问题，表格不在 G6 的范畴中。AntV 正在建设 S2，专注交叉表，可以关注一下

**Comment by xingwanying** [comment]
> 现在可视化图的解决方案有很多，但是支持配置化报表的方案很少，咱们是否有计划支持数据驱动的报表配置方案

S2 已正式开源，专注做多维分析表，可以关注下官网： 

https://antv-s2.gitee.io/
