### ISSUE TITLE
为什么开启控制台后，运行性能就会下降非常多

### ISSUE THREAD

**Issue by lmhgithi** [antvis/G6#2748]
![image](https://user-images.githubusercontent.com/40905590/111566664-8b055400-87d8-11eb-9c30-2a7292f25d24.png)

enter后面是毫秒数，对操作进行了计时，300以上是我开启控制台，100以下是我关闭控制台~

**Comment by lmhgithi** [comment]
补充一下，操作是更新graph中node的state

**Comment by Yanyan-Wang** [comment]
浏览器打开控制台之后会做更多的监控的事情，所以会吃性能
