### ISSUE TITLE
IE 下载图片报错（我是同域没有跨域）

### ISSUE THREAD

**Issue by csspmini-web** [antvis/G6#2752]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
在 IE11 使用 downloadfullimage 

| Environment | Info |
|---|---|
| g6 | 4.2.1 |
| System | - |
| Browser | ie11 |

**Comment by Yanyan-Wang** [comment]
报的什么错误？请给出最小复现的在线 demo

**Comment by csspmini-web** [comment]
> 报的什么错误？请给出最小复现的在线 demo

就是 canvas  被污染了，所有 ie 都会这样，只有 svg 会这样，目前只能转base64 解决

**Comment by Yanyan-Wang** [comment]
不再考虑兼容 IE，因为 IE 已经下架啦
