### ISSUE TITLE
普通的graph或者layout为'force'的graph是否可以配置避免标签重叠

### ISSUE THREAD

**Issue by lmhgithi** [antvis/G6#2753]
如题~当节点多起来后，标签（label）非常容易重叠，如果一个个判断，再给每个标签一个offset会非常麻烦

**Comment by lmhgithi** [comment]
另外一个想问：现在mac触摸板两指拖动是放大缩小，可否设置两指拖动为拖拽画布

**Comment by Yanyan-Wang** [comment]
目前只能通过写 nodeSpacing 函数，根据文本长度预判文本图形的大小（例如利用 Util.getLetterWidth 与 Util.getTextSize 进行预估，但不非常精准。https://g6.antv.vision/zh/examples/item/label#labelLen），return 这个值。

nodeSpacing: (d) => {
  return  G6.Util.getLetterWidth(d.label, fontSize);
}

**Comment by lmhgithi** [comment]
谢谢解答~
