### ISSUE TITLE
文档：图算法 Algorithm DFS BFS算法参数说名有误

### ISSUE THREAD

**Issue by lanteng007** [antvis/G6#2754]
第一个参数应该是graphData（原图数据）而不是Graph （G6 Graph 实例）

具体请看算法代码实现，连接：https://github.com/antvis/algorithm/blob/master/packages/graph/src/bfs.ts

**Comment by Yanyan-Wang** [comment]
感谢指正，已经修复。

在 4.1.0 之前，大部分算法传入的是 graph 实例，4.1.0 之后改为传入图数据
