### ISSUE TITLE
[Question] Can we scroll the canvas on mouse wheel?

### ISSUE THREAD

**Issue by ankitachdhr145** [antvis/G6#2755]
I came across zoom functions on wheel scroll. But is it possible to scroll the canvas(y-axis) on wheel scroll. If yes how it is possible if one can provide a code snippet. I tried playing around with deltaX as zero but I think either it is not working or am not doing it correctly. Thanks in advance

**Comment by Yanyan-Wang** [comment]
https://g6.antv.vision/zh/examples/interaction/customBehavior#dragCanvasTwoFingers
