### ISSUE TITLE
使用force或者gForce布局时，渲染结束后想聚焦到指定节点

### ISSUE THREAD

**Issue by lmhgithi** [antvis/G6#2758]
我在onLayoutEnd中查找并focusItem好像并没有用~有比较好的实践吗

**Comment by Yanyan-Wang** [comment]
可以聚焦的呀，要在布局完全停止之后才会被调用 https://codesandbox.io/s/adoring-zhukovsky-negls
不行的话提供在线复现 demo

**Comment by lmhgithi** [comment]
我找到问题了，我用的是gForce，当我gpuEnabled: true,的时候，这个focus会执行，但是会跑偏~不知道怎么解决，不想要force收敛的动画~

**Comment by lmhgithi** [comment]
@Yanyan-Wang 所以如果用force布局的话~我有办法关掉初始化动画吗？

**Comment by Yanyan-Wang** [comment]
force 不能关掉动画，可以用 gForce 或者 4.2.3 forceAtlas2 https://g6.antv.vision/zh/docs/api/graphLayout/forceAtlas2

**Comment by Yanyan-Wang** [comment]
> 我找到问题了，我用的是gForce，当我gpuEnabled: true,的时候，这个focus会执行，但是会跑偏
> 不知道怎么解决，不想要force收敛的动画

需要在布局完成之后再使用 focus。可以监听 afterlayout

**Comment by lmhgithi** [comment]
感谢大佬解答~我试一试~
