### ISSUE TITLE
Large Graph Exploration report an error...

### ISSUE THREAD

**Issue by MuYs** [antvis/G6#2759]
Uncaught (in promise) TypeError: Cannot read property 'size' of undefined

**Comment by mxz96102** [comment]
Pls provide more information, a line of exception does not give any clue

**Comment by MuYs** [comment]
Open the G6 official website chart example and Opening the "Gallery/Large Graph Exploration" console will also report this error= =

**Comment by Yanyan-Wang** [comment]
I found it was due to the LOUVAIN algorithm which has some incorrect changes in @antv/algorithm. I will fix it soon.

**Comment by Yanyan-Wang** [comment]
Fixed, clear the browser cache and try it again.

In your project, update the @antv/algorithm to 0.1.6 will fix the problem

**Comment by MuYs** [comment]
ok,Problem solved,thanks!
