### ISSUE TITLE
Disappearing edges when combos are collapsed

### ISSUE THREAD

**Issue by brishable** [antvis/G6#2760]
**Description:**
In a multi-level combo/node graph with edges, the connection between nodes to combos isn't preserved when they are collapsed. 

For example in the provided code:

- node 1(in combo A) has connections to four other nodes including node 4 and node 5 in combo C.
- if you collapse combo C, there should be a connection between node 1 and combo C, but there isn't
- The same is for node 3 and combo E

We also have observed that there are edges between two combos where the nodes inside them aren't related, we haven't reproduced that issue here as the data is small.

Attached, please find the screenshots and the code

[G6-disapearing-edges.js.txt](https://github.com/antvis/G6/files/6188511/G6-disapearing-edges.js.txt)

![image](https://user-images.githubusercontent.com/9823697/112126962-41947a80-8bc5-11eb-9d0e-fea7bed3bac1.png)
![image](https://user-images.githubusercontent.com/9823697/112126999-49541f00-8bc5-11eb-861a-ef24587f3a89.png)

**Comment by Yanyan-Wang** [comment]
please provide an online demo on codepen.io or codesandbox.io

**Comment by brishable** [comment]
Hello, here is a demo: https://codesandbox.io/s/floral-moon-ihg4k

**Comment by Yanyan-Wang** [comment]
> Hello, here is a demo: https://codesandbox.io/s/floral-moon-ihg4k
> 
> Alternatively, I have attached the script as a file as well.
> [G6-disapearing-edges.js.txt](https://github.com/antvis/G6/files/6195993/G6-disapearing-edges.js.txt)

I saw empty files in https://codesandbox.io/s/floral-moon-ihg4k
Did you forget to save?

**Comment by brishable** [comment]
I gave you edit access and thought you'd see it there. Can you try it now, please?

**Comment by Yanyan-Wang** [comment]
fixed by 4.2.5

**Comment by brishable** [comment]
Thank you, I will test it
