### ISSUE TITLE
#2696 × TypeError: Cannot set property 'typescript' of undefined

### ISSUE THREAD

**Issue by zcolin** [antvis/G6#2761]
![image](https://user-images.githubusercontent.com/5196936/112144362-15541a80-8c14-11eb-9a8e-63f21c11d6f9.png)
npm run build:site

依然碰见此问题，“node_modules 里面有 monaco-editor 重复的版本，删除旧的一个版本”，这个请问如何操作，我现在在node_modules中发现有三个此库关联的 
![image](https://user-images.githubusercontent.com/5196936/112142782-fb193d00-8c11-11eb-9b33-a6438c617e1f.png)
不知该如何删除？
在所有的package.json中也没有发现谁进行的引用。
其中react-monaco-editor的node_modules中的monaco-editor是0.23.0，而根目录node_modules中的monaco-editor是0.21.3，我尝试直接删除react-monaco-editor的node_modules中的monaco-editor删除或者根目录node_modules中的monaco-editor删除之后编译就会报错。也尝试了直接更改yarn.lock中的monaco-editor版本，直接用0.23.0并且确定在根目录的node_modules中已经安装了0.23.0,但是也是编译报错。

综上，确实是无能为力了，望赐教

**Comment by Yanyan-Wang** [comment]
使用 npm i 安装的么，安装之后在 IDE 的目录里面应该可以看到这样的：
![image](https://user-images.githubusercontent.com/29593318/112267085-e7bcaf00-8caf-11eb-825a-ff57f389a4a6.png)

往下拉找到 _monaco-editor，下面的截图是我这里已经删掉了 0.21.3 版本，用 npm i 没有删过的状态下，这个 0.23.0 上方应该还有一个 0.21.3，右击它，选择删除
![image](https://user-images.githubusercontent.com/29593318/112267201-0f137c00-8cb0-11eb-81d8-85f3418c6327.png)

**Comment by zcolin** [comment]
![image](https://user-images.githubusercontent.com/5196936/112403077-b5ab5b80-8d48-11eb-8055-4e545882e355.png)
![image](https://user-images.githubusercontent.com/5196936/112403109-c5c33b00-8d48-11eb-914d-63c9df558254.png)
我的装完之后是这样的，之前我一直用webstorm的（看着你的node_module不同特地换了vscode看了一下，这个现实版本号是装什么插件了么）。所以还是没有看见两个版本号。而且node_modules是都装在了根目录下面。site的子目录的node_modules只有一个.bin目录

**Comment by Yanyan-Wang** [comment]
你是在 site 这个目录下 npm i 的吗，

cd packages/site
npm i

**Comment by zcolin** [comment]
是在siite这个目录，我的npm一直报错“npm ERR! cb() never called!”，cache clean、删node_modules、删代理都不行，所以用yarn安装的。

**Comment by Yanyan-Wang** [comment]
yarn 装了之后是看不到有几个版本同时被安装的。npm 报错可能是 node 或者 npm 版本问题，看下这个：https://stackoverflow.com/questions/15393821/npm-err-cb-never-called

**Comment by zcolin** [comment]
首先非常感谢您耐心的指导，问题已经解决，中间碰到了几个问题，我简单说明一下：
1 不使用yarn，需要使用npm安装（虽然我npm之后没有手动删除旧版本，并且在node_moudles中只有一个0.21.3的版本，但是确实不再报错，具体原因我不想再搞了- -！）。
2 在site的目录中将"site:build": "npm run site:clean && GATSBY=true gatsby build --prefix-paths",中的“GATSBY=ture”移除。
3 安装python最新版本。
4 “npm ERR! cb() never called!”是将淘宝源换成官方源解决。
5 使用“梦想网页资源下载器”下载项目中用到的外网资源（包括json、css、js、图片登），然后放置于项目中，全局搜索用到资源的地方进行路径替换。

以上之后，可以完成内网部署。

**Comment by Yanyan-Wang** [comment]
好的，恭喜恭喜。我们也是在实践中发现 npm 安装在 node_modules 中的版本会更清晰一些…感谢提供解决步骤，可以帮助到后面遇到问题的小伙伴。那么先关闭 issue 了
