### ISSUE TITLE
Canvas top is inaccessible with minimap when fitCenter is true

### ISSUE THREAD

**Issue by ankitachdhr145** [antvis/G6#2764]
https://codepen.io/Yanyan-Wang/pen/mdbYZvZ

In the above tutorial if you add a line at 77, something like below:
fitCenter: true,
plugins: [ minimap, grid ] 

And then use the minimap to view the bottom of graph and afterwards try to view the top of the graph then you wont be able to access the top as shown in minimap at all. The views are not same as in the box and canvas. Top part becomes inaccessible with minimap when fitCenter is set to true. For more illustration refer the below screenshot:
Note: We cant use fitView for our requirement
![image](https://user-images.githubusercontent.com/60146248/112301613-69094700-8c9a-11eb-957f-14b8599868a1.png)

Expected behavior should be: 
![image](https://user-images.githubusercontent.com/60146248/112301710-84745200-8c9a-11eb-9000-c782e94ddfd3.png)

**Comment by Yanyan-Wang** [comment]
I have changed the demo with new version of G6 (4.2.3) and add the `fitCenter: true` to the graph, pls view it again and see if the problem still occur in the demo.

**Comment by ankitachdhr145** [comment]
For me the small box which I used to navigate to top and bottom has just disappeared from the minimap. I tried refreshing the window and changed it to incognito too.
![image](https://user-images.githubusercontent.com/60146248/112454018-8ef52100-8d58-11eb-9e57-7e496ff7377f.png)
Moreover, I upgraded version in my project as well but issue still exists. We have combos and its a vertically growing data. Initially you will have 2 boxes and once you expand you can have 50-60 rows or more. After first expansion its very difficult to access the top with minimap. Works well with drag canvas or mouse scroll. But with minimap it is not accessible.

**Comment by Yanyan-Wang** [comment]
> For me the small box which I used to navigate to top and bottom has just disappeared from the minimap

it is due to the viewport is too large to show on the minimap. Zoom-in the main graph and you will see the viewport box shows  up again.

For the problem you described in your project, please provide a reproduced online demo

**Comment by ankitachdhr145** [comment]
We were not able to replicate so closing it for now.
