### ISSUE TITLE
double-finger-drag-canvas 的滚动，图片是否可以限制滚动区域

### ISSUE THREAD

**Issue by BabyMing** [antvis/G6#2767]
double-finger-drag-canvas 的onwheel  是无限滚动的，请问是否可以限制一下滚动的范围，不要让图片全部滚动出画布？

**Comment by Yanyan-Wang** [comment]
可以，这是自定义交互，参考内置 drag-canvas 中对拖拽画布区域限制的实现去改一下这个自定义交互
https://github.com/antvis/G6/blob/4ae2226b1602f56a0d23a817dfbcbf7229019769/packages/pc/src/behavior/drag-canvas.ts#L62

**Comment by Yanyan-Wang** [comment]
v4.2.6 新增内置交互 scroll-canvas，即内置 double-finger-drag-canvas，且支持 drag-canvas 的配置 scalableRange
