### ISSUE TITLE
angular js项目使用g6需怎样兼容ie

### ISSUE THREAD

**Issue by dyj7** [antvis/G6#2770]

**Comment by baizn** [comment]
参考这里：https://g6.antv.vision/zh/docs/manual/FAQ/angular-support

**Comment by doc-DJJ** [comment]
这里指的是Angular 9以上版本
而我的项目的版本是angular js也就是angular1.x版本

**Comment by doc-DJJ** [comment]
我现在的项目可以使用g6，但不兼容ie，我想知道怎么才能兼容ie

**Comment by Yanyan-Wang** [comment]
IE 的兼容 FAQ 看看呢？https://g6.antv.vision/zh/docs/manual/FAQ/supportIE

**Comment by Yanyan-Wang** [comment]
不再考虑兼容 IE，因为 IE 已经下架啦
