### ISSUE TITLE
拖动使用方框代替元素，可否复制拖动元素的样式和文字？

### ISSUE THREAD

**Issue by penxu** [antvis/G6#2771]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vibrant-sun-u5hbc)

### Steps to reproduce
            {
                type: "drag-node",
                enableDelegate: true,
                delegateStyle: {
                  fill: "red"
                }
              }

| Environment | Info |
|---|---|
| g6 | 3.8.0 |
| System | ios |
| Browser | chorme |

---
设置的拖动使用方框代替元素， 只有方框，只能修改边框和填充颜色这些，想复制拖动元素的全部样式和文字？请问能否实现或者实现方式是怎样呢？

**Comment by Yanyan-Wang** [comment]
这种就是 enableDelegate: false ，直接拖动原来的节点了

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
