### ISSUE TITLE
TypeError: layoutMethod is not a function

### ISSUE THREAD

**Issue by BabyMing** [antvis/G6#2772]
var self = this;
  328 | var data = self.get('data');
  329 | var layoutMethod = self.get('layoutMethod');
> 330 | var layoutData = layoutMethod(data, self.get('layout'));
      | ^  331 | var animate = self.get('animate');
  332 | self.emit('beforerefreshlayout', {
  333 |   data: data,

在graph.render()的时候，
node_modules/@antv/g6-pc/es/graph/tree-graph.js:330
这个js文件的330行报错：TypeError: layoutMethod is not a function
反复查证数据是没有问题的，请问是什么原因呢？

**Comment by Yanyan-Wang** [comment]
哪个版本？看下安装的 G6、antv/layout 分别都是什么版本

**Comment by BabyMing** [comment]
"@antv/g6": "^4.2.3",
    "@antv/layout": "^0.1.12",

**Comment by 2020AD** [comment]
> 哪个版本？看下安装的 G6、antv/layout 分别都是什么版本

"@antv/g6": "^4.2.3",
"@antv/layout": "^0.1.12",

**Comment by Yanyan-Wang** [comment]
麻烦给一下复现在线 demo

**Comment by wsb260** [comment]
节点拖动报错，这个问题更新版本之后就有了，还咩有修复吗？你们官网的例子就是报错的，https://g6.antv.vision/zh/examples/net/forceDirected#basicForceDirected

**Comment by ColinChen2** [comment]
@wsb260 你说得对，官方例子还没来得及改，😆
你可以先参照那个例子改成
```
    graph.render();
---  const forceLayout = graph.get('layoutController').layoutMethod;
    graph.on('node:dragstart', function (e) {
      graph.layout();
      refreshDragedNodePosition(e);
    });
    graph.on('node:drag', function (e) {
+++  const forceLayout = graph.get('layoutController').layoutMethods[0];
      forceLayout.execute();
      refreshDragedNodePosition(e);
    });
```

**Comment by Yanyan-Wang** [comment]
> 节点拖动报错，这个问题更新版本之后就有了，还咩有修复吗？你们官网的例子就是报错的，https://g6.antv.vision/zh/examples/net/forceDirected#basicForceDirected

官网实例已修复

**Comment by Yanyan-Wang** [comment]
> "@antv/g6": "^4.2.3",
> "@antv/layout": "^0.1.12",

提供一下复现 demo 呢？我这边没有复现

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
