### ISSUE TITLE
增加点边数据时，如何不改变之前的布局，实现真实的增量增加

### ISSUE THREAD

**Issue by tiannengyu** [antvis/G6#2773]
https://g6.antv.vision/zh/examples/case/largeGraph#index
示例中，看到增加节点使用的就是changeData。
但我在使用changeData时，之前的布局全都改变了。
如何可以增量添加，不改变之前布局

**Comment by Yanyan-Wang** [comment]
使用的也是 force 或者 gForce 吗？保证 changeData 给的新数据，相同节点的 x y 与之前的布局结果相同

**Comment by javaNaruto** [comment]
> 使用的也是 force 或者 gForce 吗？保证 changeData 给的新数据，相同节点的 x y 与之前的布局结果相同

我用的是gForce，有一个奇怪的现象是新增点在布局的时候会出现抖动的现象，gForce的参数设置怎样才能合理

**Comment by Yanyan-Wang** [comment]
gForce 是一种力导向布局，节点在力的作用下移动位置，到达力平衡状态时停止布局。新增节点会破坏当前力平衡的状态，从而可能出现抖动，属于正常现象

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
