### ISSUE TITLE
G6 polyline 类型的线 当节点多时 连线会不重叠

### ISSUE THREAD

**Issue by libaibuzai** [antvis/G6#2774]
![image](https://user-images.githubusercontent.com/39814390/112784399-338ea000-9084-11eb-9880-420f32467830.png)

换成别的线都不会出问题 只有polyline类型的不行
请问该怎么解决？

**Comment by libaibuzai** [comment]
![image](https://user-images.githubusercontent.com/39814390/112785122-dc89ca80-9085-11eb-830c-4c3be8f7163c.png)
其他类型的线 都没有问题

**Comment by libaibuzai** [comment]
下面是实例的配置：

graph = new G6.TreeGraph({
            container: 'container',

            width: width,
            height: height,

            fitView: true,
            animate: false,
            linkCenter: false,
            defaultNode: {
              type: 'flow-rect',
            },
            defaultEdge: {
              type: 'polyline', // cubic-horizontal 水平 贝塞尔曲线 line: 直线 polyline: 折线
              style: {
                offset: 10, // 拐弯处距离节点最小距离
                radius: 3, // 拐弯处的圆角弧度，若不设置则为直角
                lineWidth: 2,
                stroke: '#4C8AF6',
              },

              source: '3',
              target: '4',
            },
            layout: {
              type: 'compactBox',
              direction: 'LR',
              dropCap: false,
              indent: 300,
              getHeight: () => {
                return rectConfig.height;
              },
              getWidth: () => {
                return rectConfig.width + 40;
              },
            },
            padding: [20, 50],
            defaultLevel: 3,
            defaultZoom: 1,
            modes: {
              default: ['zoom-canvas', 'drag-canvas'],
            },
            plugins: [tooltip, minimap],
          });

**Comment by Yanyan-Wang** [comment]
你是希望重叠还是不重叠？polyline 是会根据两端节点的相对位置自动动态规划巡经的，不一定会重合

**Comment by libaibuzai** [comment]
我是希望 重叠在一起

**Comment by libaibuzai** [comment]
或者 需要怎么规避 不重合这个问题呢

**Comment by Yanyan-Wang** [comment]
内置的折线一般会用在节点没有分布这么规则的情况下。你这里这种规则的折线可以自定义，自己计算一下需要拐弯的位置，然后给到 path：
https://g6.antv.vision/zh/examples/item/customEdge#customPolyline2

像这个例子意思就是从 startPoint 开始，画直线到 (endPoint.x / 3 + (2 / 3) * startPoint.x, startPoint.y)，再画直线到 (endPoint.x / 3 + (2 / 3) * startPoint.x, endPoint.y)，再画直线到 endPoint
['M', startPoint.x, startPoint.y],
  ['L', endPoint.x / 3 + (2 / 3) * startPoint.x, startPoint.y],
  ['L', endPoint.x / 3 + (2 / 3) * startPoint.x, endPoint.y],
  ['L', endPoint.x, endPoint.y],

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
