### ISSUE TITLE
自定义linkpoint显示，悬浮在锚点拖拽节点后，该节点无法选中无法拖动，并且hover selected这些事件都无法触发

### ISSUE THREAD

**Issue by ShaocongZheng** [antvis/G6#2779]
自定义linkpoint显示，悬浮在锚点拖拽节点后，该节点无法选中无法拖动，并且hover selected这些事件都无法触发，但其他节点均正常。不用“drag-node” behavior的话能触发hover selected事件，推测是drag-node有点问题
### Implementation
- __G6 version__: 4.2.1
- __Platform__: chrome
- __codesandboxlink__: https://codesandbox.io/s/sweet-joliot-zsw9f?file=/src/components/Graph.vue

**Comment by Yanyan-Wang** [comment]
G6 内部有在 drag-node 中处理 isAnchorPoint: true 的不允许拖拽，如果你希望你的画的 linkPoint 允许拖拽，就不设置 isAnchorPoint: true 就好了。另外，不清楚什么地方在拖拽 linkPoint 结束的时候把节点图形分组的 capture 设置为 false 了，我在你代码里这样加了一句设置就好了：

  this.graph.on('node:dragend', e => {
    e.item.getContainer().set('capture', true)
  });

**Comment by ShaocongZheng** [comment]
加了capture那个设置果然可以了，非常感谢！isAnchorPoint: false的话拖拽锚点图形就会跟着动了，但是需要实现的效果是，拖拽图形锚点来连线，拖拽图形其他位置移动图形。

**Comment by Yanyan-Wang** [comment]
好的。解决了就行
