### ISSUE TITLE
使用层次布局的时候，下面这个报错是为什么？ 层次布局对于数据有特殊要求嘛？？

### ISSUE THREAD

**Issue by dlink-chenqingyun** [antvis/G6#2784]
![image](https://user-images.githubusercontent.com/63584079/113374591-fd149600-939f-11eb-8289-3a99aba6f5b1.png)

报错信息：
Uncaught Error: Not possible to find intersection inside of the rectangle

**Comment by baizn** [comment]
麻烦提供一个在线 demo

**Comment by dlink-chenqingyun** [comment]
刷新刷新这bug 又出不来了， dbcliK 会触发两次 click 事件，有方法避免么？

**Comment by Yanyan-Wang** [comment]
dblclick 在 mdn 标准里是会触发两次 click 的
