### ISSUE TITLE
edge.getTarget(...).getModel is not a function

### ISSUE THREAD

**Issue by wsb260** [antvis/G6#2785]
通过改变modes切换成type: "create-edge"创建边，在拉伸边的时候报错edge.getTarget(...).getModel is not a function

具体报错代码在graph.js里
    each(edges, function (edge) {
      var sourceModel = edge.getSource().getModel();
      var targetModel = edge.getTarget().getModel();

      if (updatedNodes[sourceModel.id] || updatedNodes[targetModel.id] || edge.getModel().isComboEdge) {
        edge.refresh();
      }
    });

**Comment by Yanyan-Wang** [comment]
请提供复现在线 demo

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
