### ISSUE TITLE
layout为force类型时，模式create-edge创建边，在拉边的时候报错e.getTarget(...).getModel is not a function

### ISSUE THREAD

**Issue by wsb260** [antvis/G6#2786]
layout为force类型时，模式create-edge创建边，在拉边的时候报错e.getTarget(...).getModel is not a function

demo：https://g6.antv.vision/zh/examples/interaction/createEdge#drag  在里面添加代码 
```
  layout: {
          type: "force",
          linkDistance: 120,
          preventOverlap: true,
        }
```
会报错 
> e.getTarget(...).getModel is not a function

**Comment by Yanyan-Wang** [comment]
fixed by 4.2.6
