### ISSUE TITLE
Bug with Node location after linking from Сombo to this Node

### ISSUE THREAD

**Issue by alyuev** [antvis/G6#2788]
- **G6 Version**: v4.2.5
- **Platform**: Windows 10
- **Mini Showcase(like screenshots)**:
- **CodePen Link**: [https://jsfiddle.net/alyuev/ev3uno5d/4/](https://jsfiddle.net/alyuev/ev3uno5d/4/)

Here is bug (or feature?) with Node 3 location after linking from Сombo to this Node 3 on dagre layout. 

```
      const data = {
        nodes: [
        { id: '1', label: "1"},
        { id: '2', label: "2", comboId: 'Combo',},
        { id: '3', label: "3"},
        ],
        edges: [
        { source: '1', target: '2' },
        { source: 'Combo', target: '3' },
        ],
  	combos: [{ id: 'Combo', label: 'Combo'},],
	};
```

But Console is show such log:
"G6 Warn Tips: The edge with source %cCombo%c and target %c3%c does not completely exist in the ID of the node.", "font-size: 20px; color: red;", "", "font-size: 20px; color: red;", ""

The Node 3 drown at top of graph. Why? I expected to see it on the third level.

**Comment by baizn** [comment]
the wran tips message is a bug,  Combo only supports comboForce layout
Demo：https://g6.antv.vision/zh/examples/net/dagreFlow#dagreCombo
Docs：https://g6.antv.vision/zh/docs/manual/middle/layout/graph-layout#combo-force

**Comment by Yanyan-Wang** [comment]
Dagre in G6 depends on the https://github.com/dagrejs/dagre. The ranks of the nodes relates to the edges between nodes but not combos. The combos, which are parents of nodes or combos in dagre, only affects the order of nodes with the same rank.
