### ISSUE TITLE
拖动节点时，被线穿过的节点中的文本会闪烁

### ISSUE THREAD

**Issue by yanliang-code** [antvis/G6#2789]
win10 chrome89
如下图，拖动红框内节点时，e0-2线会穿过绿框节点，此时文本会一会消失一会显示（若没重现，请多个角度试试）
<img width="371" alt="question" src="https://user-images.githubusercontent.com/60208330/113512798-dec5ba80-9598-11eb-877c-730f5e23ed51.png">
在线例子  https://codepen.io/yanliang-code/pen/wvgeBoL

**Comment by baizn** [comment]
这个问题有可能是底层渲染引擎的一个问题，我们后面排查一下，你可以临时先把半径值设置大一点，如下面这样：
```
 node.clipCfg = {
      show: true,
      type: "circle",
      r: 60
    };
```

r 值稍微大一点，就不会出现上面的问题。

**Comment by baizn** [comment]
@xiaoiver  看下是不是 G 局部渲染的问题，r 设置为 50 就会有问题，设置为 60、100 等就不会有问题

**Comment by yanliang-code** [comment]
好的，希望尽快修复，谢谢

**Comment by Yanyan-Wang** [comment]
与局部渲染有关，尝试关闭局部渲染可解决 graph.get('canvas').set('localRefresh', false)

**Comment by Yanyan-Wang** [comment]
已修复
