### ISSUE TITLE
Request for ability to set rank level for node for dagre mode

### ISSUE THREAD

**Issue by alyuev** [antvis/G6#2790]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

It will be good to have ability to set rank level for node for dagre mode. Like it has visjs.
Look at https://visjs.github.io/vis-network/docs/network/nodes.html
and find there:

"level | Number | undefined | When using the hierarchical layout, the level determines where the node is going to be positioned."

I think "rank level" will be the same as "level" option in visjs.

The exapmple of defferent level here:
https://visjs.github.io/vis-network/examples/network/layout/hierarchicalLayoutUserdefined.html

Node 2 on the next level, not as 10, 7, 12.

**Comment by Yanyan-Wang** [comment]
The dagre algorithm in G6 depends on https://github.com/dagrejs/dagre, the ranks are calculated automatically and not assignable in this lib. Same issue in dagrejs/dagre: https://github.com/dagrejs/dagre/issues/289

**Comment by Yanyan-Wang** [comment]
duplicated to https://github.com/antvis/G6/issues/2245
