### ISSUE TITLE
官方demo中旋转方式不是基于中心点旋转，如何实现

### ISSUE THREAD

**Issue by yanliang-code** [antvis/G6#2791]
win10 chrome89
参考 https://antv-g6.gitee.io/zh/examples/scatter/node#node 中的旋转实现方法，发现此方法不是完全的基于中心点进行旋转的；具体实现 https://codepen.io/yanliang-code/pen/MWJowvG
求如何实现基于节点的中心点进行旋转

**Comment by Yanyan-Wang** [comment]
因为你的图片没有中心对齐，我画了几条从节点中心出发，等长的线段在这里例子中 https://codepen.io/Yanyan-Wang/pen/KKavOpE?editors=0010

![image](https://user-images.githubusercontent.com/29593318/113800769-1e9fc400-978a-11eb-9ae7-f9f4323f9948.png)

**Comment by yanliang-code** [comment]
好的，多谢
