### ISSUE TITLE
graph.on("afterlayout") in version 4.2.5

### ISSUE THREAD

**Issue by brishable** [antvis/G6#2793]
We have some functionality to align the elements on the graph when combos are expanded/collapsed and we trigger that with `graph.on("afterlayout" e =>{ }) `

It is called when the graph first loads but we also want it to be triggered when combos are expanded and collapsed as well.

It was working fine with version 4.2.0 of G6 but I recently upgraded the version to 4.2.5 and that isn't happening anymore.

**Comment by Yanyan-Wang** [comment]
You could add listener for `'aftercollapseexpandcombo'`

**Comment by brishable** [comment]
> You could add listener for `'aftercollapseexpandcombo'`

Thank you, we will try it.
