### ISSUE TITLE
g63.x.x升级到4.x.x，edge中source 和 target值怎么支持位置对象

### ISSUE THREAD

**Issue by lQei** [antvis/G6#2795]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/g6-reproduction-template-uvzdf?file=/src/index.js)

### Steps to reproduce
edges中使用{source: {x: 100,y: 350},target: {x: 200,y: 350}},会有警告提示。我在之前使用的是3.x.x的版本，支持此种写法。当前升级到4.x.x，会有警告提示，而且会影响到代码程序的执行。我注意到这个警告是在validation.js中执行的，我把这个判断去掉，目前看来都正常。请问我当前可以怎么处理？如果全部更改逻辑，source和target全部使用字符串的话，工作量较大

| Environment | Info |
|---|---|
| g6 | 4.2.5 |
| System | win10 |
| Browser | Google Chrome 版本 86.0.4240.193（正式版本） （64 位） |

**Comment by Yanyan-Wang** [comment]
是什么目的要使用一个没有起始节点和结束节点的边？这种应该不算一个边，如果你只想画一条直线可以直接在 graph 的图形分组里面增加一条直线路径 
 graph.getGroup().addShape('path', ...) 图形属性详见 https://g6.antv.vision/zh/docs/api/shapeProperties#%E7%BA%BF%E6%9D%A1-path

**Comment by lQei** [comment]
![image](https://user-images.githubusercontent.com/20189143/113802084-a71f6400-978c-11eb-9a28-6113875ef248.png)
我需要绘制这种图形，都是直线连接。需要一些辅助的线条

**Comment by Yanyan-Wang** [comment]
哪些是辅助线条？

**Comment by lQei** [comment]
比如下面的图形，它的连接关系我是这样设置的：
![image](https://user-images.githubusercontent.com/20189143/113803409-126a3580-978f-11eb-8f35-afda4e3663cf.png)
![image](https://user-images.githubusercontent.com/20189143/113803431-20b85180-978f-11eb-94fb-7399dbc3038f.png)

**Comment by Yanyan-Wang** [comment]
我理解你这里 edges 里的第 2、4、6、7 条边的 source 都可以指定到节点上。第 3、5 是为了绘制水平的一条线，可以通过 addShape 的方式来添加直线路径

**Comment by lQei** [comment]
好的，谢谢。如果通过加直线路径来处理的话，代码的调整会比较大。我注意到在validation.js中有一段代码：
var nonEdges = (edges || []).find(function (edge) {
    return !nodeIds.includes(edge.source) || !nodeIds.includes(edge.target);
  });

  if (nonEdges) {
    console.warn("G6 Warn Tips: The edge with source %c" + nonEdges.source + "%c and target %c" + nonEdges.target + "%c does not completely exist in the ID of the node.", 'font-size: 20px; color: red;', '', 'font-size: 20px; color: red;', '');
    return false;
  }
graph.js中有一段代码：
each(edges, function (edge) {
      var sourceModel = edge.getSource().getModel();
      var targetModel = edge.getTarget().getModel();

      if (updatedNodes[sourceModel.id] || updatedNodes[targetModel.id] || edge.getModel().isComboEdge) {
        edge.refresh();
      }
    });

我目前把这两段代码注释掉了，从简单测试上来看，没有其他的影响。请问这种方式可行吗，有没有其他的隐患。

**Comment by lQei** [comment]
我之前的版本是3.x.x，开发环境正常，打包部署之后，g6报错。使用g63.8.5版本也是这样的问题。请问一下，这个问题怎么解决。详见issuehttps://github.com/antvis/G6/issues/2796

**Comment by baizn** [comment]
这个 PR https://github.com/antvis/G6/pull/2792 里面修复了，本周会发布个小版本，只是警告信息，不会影响运行的，

**Comment by Yanyan-Wang** [comment]
fixed by 4.2.6
