### ISSUE TITLE
vue项目打包部署之后，g6报错

### ISSUE THREAD

**Issue by lQei** [antvis/G6#2796]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/g6-reproduction-template-uvzdf?file=/src/index.js)

### Steps to reproduce
在vue项目中，使用g6。开发环境正常。打包部署之后报错。报错如下：
chunk-libs.1e4b3d2e.js:53 TypeError: undefined is not iterable!
chunk-libs.1e4b3d2e.js:40 TypeError: Super expression must either be null or a function

| Environment | Info |
|---|---|
| g6 | 3.8.5 |
| System | win10 |
| Browser | Google Chrome 版本 86.0.4240.193（正式版本） （64 位） |

**Comment by Yanyan-Wang** [comment]
vue 不是很清楚，先确定一下是否是因为 G6，去掉 G6 看下还会不会报错。https://gitmemory.com/issue/vuejs/composition-api/109/526837881

**Comment by lQei** [comment]
去掉G6的引入之后不会报错。只要有import G6 from '@antv/g6'，就会报错

**Comment by liqi007** [comment]
angular11 添加G6引用也报错

Error: node_modules/@antv/g6-core/lib/index.d.ts:1:23 - error TS2688: Cannot find type definition file for '_gl-matrix@3.3.0@gl-matrix'.

**Comment by Yanyan-Wang** [comment]
Angular 看这里：https://github.com/antvis/G6/issues/2691#issuecomment-788164317
https://g6.antv.vision/zh/docs/manual/FAQ/angular-support

**Comment by liqi007** [comment]
删除\node_modules\@antv\g6-core\lib\util\index.d.ts和\node_modules\@antv\g6-core\lib\index.d.ts第一行后不报错能正常运行

**Comment by Yanyan-Wang** [comment]
> 删除\node_modules@antv\g6-core\lib\util\index.d.ts和\node_modules@antv\g6-core\lib\index.d.ts第一行后不报错能正常运行

为啥要删啊？看我发的链接里的解决方案

**Comment by liqi007** [comment]
@Yanyan-Wang 链接中的解决方法不能解决问题

**Comment by Yanyan-Wang** [comment]
https://github.com/antvis/G6/issues/2691 这个 issue 应该跟你一样的，先 skipLibCheck: true，然后再按后面步骤来

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
