### ISSUE TITLE
gForce布局中的gpuEnabled在无GPU机器下是否兼容

### ISSUE THREAD

**Issue by zzyjiaxinmomo** [antvis/G6#2797]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
项目中使用g6的gForce布局，想要通过gpuEnabled参数提升性能，但是手头没有无GPU机器测试，想问一下兼容性如何。是否会因为开启GPU而导致渲染报错等问题。

### What does the proposed API look like?
期望能够确认在无GPU的机器上开启GPU渲染，是否兼容

**Comment by Yanyan-Wang** [comment]
兼容，会自动降级。

**Comment by b627360067** [comment]
有GPU的机器上最终渲染结果与无GPU的机器上最终渲染结果不一致呢？是bug吗？
