### ISSUE TITLE
Disapearing edges when combos are expanded/collapsed -- reopening #2760

### ISSUE THREAD

**Issue by brishable** [antvis/G6#2798]
- G6 Version: v4.2.5
- Platform: Windows 10

**Description:** 
When combos are expanded and collapsed, edges are disappearing. I reported an issue previously [https://github.com/antvis/G6/issues/2760]( ) and received a fix with version 4.2.5 of G6. 
The new version fixed the issue for the example code that I provided but it didn't solve all our problems.

This time, I used a large set of data to reproduce the issue that we are facing so it may take time to load and render, apologies.

In the example code: We have three combos. 
1. **ROOT** – every other combo and node is contained inside it. There is just one 
2. **PARENT** – this is a second-level combo that is inside the ROOT and will have other combos. We have 6 of them in the example code.
3. **CHILD** – these combos are children of PARENT and they’ll contain NODES.
I also added some elementary logic to position the nodes on the canvas. Moreover, Child combos that have more than one node are collapsed.

To reproduce the issue, please do either of the following. `activate relations` is enabled to help to observe it.
**CASE 1**: 
-	Hover over transaction “ABCD” in PARENT 7 and you will notice that it has two connections to a node and combo that belong to PARENT 5 combo.
-	Now collapse “PARENT 5” combo and hover over transaction ABCD … the edges are gone

**CASE 2**: 
-	Collapse both combos “PARENT 5 and PARENT 0”
-	All other edges from the remaining combos will disappear

The example code is on code sandbox: [https://codesandbox.io/s/elated-jepsen-hg8zn?file=/index.js](https://codesandbox.io/s/elated-jepsen-hg8zn?file=/index.js)

**Comment by Yanyan-Wang** [comment]
fixed by 4.2.6

**Comment by brishable** [comment]
Thank you, I will test it

**Comment by brishable** [comment]
**G6 Version: 4.2.6
OS: Windows 10**
**Example code:** [](https://codesandbox.io/s/new-paper-dz5q8?file=/index.js)

Hello,

Whilst the new release (version 4.2.6) fixed the issue for the example code that we provided earlier, the issue of the missing edge didn't really go away. 

I have a new example code here to reproduce a new issue. 

We have different kinds of graphs with various complexities and I was hoping that you'd give us a generic fix that works for all. 

Steps to reproduce the issue in this new example code. 

The graph is fairly simple (It has only 6 nodes and 5 edges). 

1. If you hover over the NODE5 you will see that it has three connections. one of which is to NODE1 which is inside combo COMBTKT5.

2. Now collapse combo COMBQISB (which is the parent of NODE5) and you'll see that all the three connections to the node inside it disappear. 

3. Collapse COMBTKT5 and you'll see an edge drawn between COMBQISB and COMBTKT5.
4. Collapse COMBTUH3 and you'll also see that an edge is drawn between COMBQISB and COMBTUH3 
5. Following the same trend if you collapse COMBTUH4 an edge will be drawn between COMBQISB and COMBTUH4. But
	A. The two edges that were created in the previous steps (3,4) were removed. 
	B. In addition, a new edge is drawn from COMBTUH4 to COMBTTIT -- which is unexpected. 

Can you look into this issue, please?
