### ISSUE TITLE
文档有误

### ISSUE THREAD

**Issue by meikidd** [antvis/g6#28]
[使用教程 - 自定义图形](https://antv.alipay.com/g6/doc/tutorial/start/custom-shape.html) 介绍内部自定义节点有 4 种， 而 [API - G6](https://antv.alipay.com/g6/api/index.html) 说有 7 种。

![image](https://user-images.githubusercontent.com/376338/28397662-9f50edbe-6d35-11e7-904c-a5dae2d891f3.png)

**Comment by TomHuangCN** [comment]
thx～
