### ISSUE TITLE
mindmap  H 布局 绘制 折线 脑图  折线错位 不重叠

### ISSUE THREAD

**Issue by proHUZhiYong** [antvis/G6#2800]
![微信图片_20210408120342](https://user-images.githubusercontent.com/34712940/113967161-064fa800-9863-11eb-8cc8-9618f6e032ca.png)

使用官方例子
https://g6-v3-2.antv.vision/zh/examples/tree/mindmap#hMindmap
完整代码
`import G6 from '@antv/g6';

fetch('https://gw.alipayobjects.com/os/antvdemo/assets/data/algorithm-category.json')
  .then(res => res.json())
  .then(data => {
  console.log(data)
    const width = document.getElementById('container').scrollWidth;
    const height = document.getElementById('container').scrollHeight || 500;
    const graph = new G6.TreeGraph({
      container: 'container',
      width,
      height,
      pixelRatio: 2,
      modes: {
        default: ['drag-canvas', 'zoom-canvas' ]
      },
      defaultNode: {
        shape:'rect',
        anchorPoints: [[ 0, 0.5 ], [ 1, 0.5 ]],
        style: {
          fill: '#000',
          stroke: '#000'
        }
      },
      defaultEdge: {
        shape: 'tree_line',
        style: {
          stroke: '#A3B1BF'
        }
      },
      layout: {
        type: 'mindmap',
        direction: 'H',
        getId: function getId(d) {
          return d.id;
        },
        getHeight: () => {
          return 16;
        },
        getWidth: () => {
          return 16;
        },
        getVGap: () => {
          return 10;
        },
        getHGap: () => {
          return 50;
        }
      }
    });
		G6.registerNode('rect', {
      draw(cfg, group) {
          const rect = group.addShape("rect", {
            attrs: {
              fill: "#050f31",
              stroke: "#3e6dc0"
            }
          });
          const context = cfg.id;
          const text = group.addShape("text", {
            attrs: {
              text: context,
              x: 0,
              y: 0,
              textAlign: "center",
              textBaseline: "middle",
              fill: "#fff"
            }
          });
          const bbox = text.getBBox();
          rect.attr({
            x: bbox.minX - 4,
            y: bbox.minY - 6,
            width: bbox.width + 8,
            height: bbox.height + 12
          });
          return rect;
        }
    });
  G6.registerEdge('tree_line', {
    getPath(points){
      const startPoint = points[0];
      const endPoint = points[1];
      return [
        [ 'M', startPoint.x, startPoint.y ],
        [ 'L', endPoint.x / 3 + 2 / 3 * startPoint.x, startPoint.y ],
        [ 'L', endPoint.x / 3 + 2 / 3 * startPoint.x, endPoint.y ],
        [ 'L', endPoint.x, endPoint.y ]];
    },
   	getShapeStyle(cfg) {
    const startPoint = cfg.startPoint;
    const endPoint = cfg.endPoint;
    let points = [ startPoint ]; // 添加起始点
    // 添加结束点
    points.push(endPoint);
    const path = this.getPath(points);
    const style = G6.Util.mix({}, G6.Global.defaultEdge.style, {
      stroke: '#BBB',
      lineWidth: 1,
      path,
      endArrow: {
        path: 'M 6,0 L -6,-6 L -3,0 L -6,6 Z',
        d: 6
      }
    }, cfg.style);
    return style;
  }
  }, 'tree_line');
    

    graph.data(data);
    graph.render();
    graph.fitView();
  });
`

**Comment by Yanyan-Wang** [comment]
polyline 自动计算的，有特定规则可以自定义折线，参考：
https://g6.antv.vision/zh/examples/item/customEdge#customPolyline

**Comment by Yanyan-Wang** [comment]
duplicated to https://github.com/antvis/G6/issues/2774
