### ISSUE TITLE
The comboId remains in the node after graph.uncombo()

### ISSUE THREAD

**Issue by wenyuan** [antvis/G6#2801]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g6.antv.vision/zh/examples/item/defaultCombos](https://g6.antv.vision/zh/examples/item/defaultCombos)

### Steps to reproduce
Use [Official Demo](https://g6.antv.vision/zh/examples/item/defaultCombos), just paste the following code in completely.  
(使用[官方 Demo](https://g6.antv.vision/zh/examples/item/defaultCombos)，将下述代码完整粘贴进去即可。)

Run and see the printed results, after `graph.uncombo('combo');`, `combo` object has been removed, but the id of the deleted combo is still stored in node(`comboId` in node).  
(运行，查看先后的打印结果，在执行 `graph.uncombo('combo');` 方法后，`combos` 数组是空数组了，但原来的子节点中 `comboId` 依旧存储着被删 combo 的 id。)

Example: 

```javascript
import G6 from '@antv/g6';

const data = {
  nodes: [
    {
      id: 'node1',
      x: 250,
      y: 150,
      comboId: 'combo',
    },
    {
      id: 'node2',
      x: 350,
      y: 150,
      comboId: 'combo',
    },
  ],
  combos: [
    {
      id: 'combo',
      label: 'Combo',
    },
  ],
};

const graph = new G6.Graph({
  container: 'container',
  width: 500,
  height: 300,
  modes: {
    default: ['drag-canvas', 'drag-node', 'drag-combo', 'collapse-expand-combo'],
  }
});

graph.data(data);
graph.render();

// before uncombo()
console.log(graph.save());
// after uncombo()
setTimeout(() => {
  graph.uncombo('combo');
  console.log(graph.save());
}, 3000 )
```

| Environment | Info |
|---|---|
| g6 | 4.2.5 |
| System | windows |
| Browser | chrome 88 |

---
Expectation: comboId will be removed or set the value empty or null after uncombo.  
(期望：combo 对象被拆解后，其子节点的 comboId 属性能够被删除或者复制为 空或 null)

**Comment by Yanyan-Wang** [comment]
fixed by 4.2.6
