### ISSUE TITLE
g6-mobile中如何处理点击事件

### ISSUE THREAD

**Issue by emeiziying** [antvis/G6#2803]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/g6-reproduction-template-uvzdf?file=/src/index.js)

### Steps to reproduce
请问在小程序中使用g6-mobile时候，应该如何绑定touchmove等事件？

| Environment | Info |
|---|---|
| g6 | 4.2.5 |
| System | - |
| Browser | - |

**Comment by emeiziying** [comment]
似乎是调用emitEvent有问题

**Comment by Yanyan-Wang** [comment]
graph.on('touchstart', e => {console.log('touch')})
graph.on('touchmove', e => {console.log('touch move')})
graph.on('touchend', e => {console.log('touch end')})

**Comment by xiaoqiang66** [comment]
你好，我怎么没有找g6-mobile这个文件呀

**Comment by emeiziying** [comment]
> 你好，我怎么没有找g6-mobile这个文件呀

https://github.com/antvis/G6/tree/mobile/packages/mobile

**Comment by emeiziying** [comment]
> graph.on('touchstart', e => {console.log('touch')})
> graph.on('touchmove', e => {console.log('touch move')})
> graph.on('touchend', e => {console.log('touch end')})

小程序中应该怎么处理呢？

**Comment by openwayne** [comment]
> > graph.on('touchstart', e => {console.log('touch')})
> > graph.on('touchmove', e => {console.log('touch move')})
> > graph.on('touchend', e => {console.log('touch end')})
> 
> 小程序中应该怎么处理呢？

移动端定义了不一样的事件模型，对于移动端来说，目前@antv/g6-mobile@0.0.1-beta.16 是屏蔽了基础的touch透传，而是通过pan事件来进行处理

```
  graph.on('panstart', e => {console.log('touch')})
  graph.on('panmove', e => {console.log('touch move')})
  graph.on('panend', e => {console.log('touch end')})

```
支付宝端建议搭配

**Comment by openwayne** [comment]
https://github.com/openwayne/g6-component-alipay

https://github.com/openwayne/g6-component-wx

组件地址
