### ISSUE TITLE
Force Click Node

### ISSUE THREAD

**Issue by CaptainFreak** [antvis/G6#2804]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I am looking for a way to programmatically click a Node. Not sure if there is already a way to do so.

### What does the proposed API look like?
// while giving node configuration if the nodes will be rendered as clicked and onClick event function will be triggered.

node.clicked = true

**Comment by Yanyan-Wang** [comment]
graph.on('node:click', e => {...});

**Comment by Yanyan-Wang** [comment]
https://g6.antv.vision/en/docs/api/Event

**Comment by Yanyan-Wang** [comment]
If you just want a node response some functions called in node click listener, why not just call the functions directly?

**Comment by CaptainFreak** [comment]
Haha, Exactly, that's what I did just before your initial answer! I just needed a bit of coffee to come to that.

**Comment by CaptainFreak** [comment]
Thanks for being responsive here, really appreciate it.
