### ISSUE TITLE
Errors when building G6 due the dependency g-canvas

### ISSUE THREAD

**Issue by JyotsnaC** [antvis/G6#2806]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/g6-reproduction-template-uvzdf)

### Steps to reproduce
building my product with G6 as dependency

ERROR in <path>/node_modules/@antv/g-canvas/esm/group.js 57:23-26
"export 'max' was not found in '@antv/util'
ERROR in /<path>/node_modules/@antv/g-canvas/esm/group.js 59:23-26
"export 'max' was not found in '@antv/util'
ERROR in /<path>/node_modules/@antv/g-canvas/esm/util/draw.js 309:14-17
"export 'max' was not found in '@antv/util'
ERROR in <path>/node_modules/@antv/g-canvas/esm/util/draw.js 310:14-17
"export 'max' was not found in '@antv/util'
ERROR in <path>/node_modules/@antv/g-canvas/esm/group.js 56:23-26
"export 'min' was not found in '@antv/util'
ERROR in<path>/node_modules/@antv/g-canvas/esm/group.js 58:23-26
"export 'min' was not found in '@antv/util'
ERROR in <path>/node_modules/@antv/g-canvas/esm/util/draw.js 307:14-17
"export 'min' was not found in '@antv/util'
ERROR in <path>/node_modules/@antv/g-canvas/esm/util/draw.js 308:14-17
"export 'min' was not found in '@antv/util'

| Environment | Info |
|---|---|
| g6 | 4.2.5 |
| System | Mac Os latest |
| Browser | Chrome latest |

**Comment by Yanyan-Wang** [comment]
what is the version num of the @antv/g-canvas ? It looks exported in @antv/util:

https://github.com/antvis/util/blob/e9cfba942db6905ffccf460bf0f78ff35e3541a4/packages/util/src/index.ts#L48

![image](https://user-images.githubusercontent.com/29593318/114332029-ea584900-9b77-11eb-8637-c912062e429e.png)

**Comment by zzfGood** [comment]
your can try this:
```
import G6 from '@antv/g6/dist/g6.min.js'
```

if you want to have type, you can global decale like this:
```
declare module '@antv/g6/dist/g6.min.js' {
  const content: typeof import('@antv/g6')
  export default content
}

```

**Comment by Yanyan-Wang** [comment]
Hi, dear user. Since there was no response for a long time, we cannot figure out the answer of the problem you described. If there is new progress, feel free to open a new issue.
