### ISSUE TITLE
可以通过点击toolbar中的某个图标来实现创建边的动作吗？

### ISSUE THREAD

**Issue by JhonYoung** [antvis/G6#2808]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当前需求如下：
鼠标移入节点，节点旁边展示toolbar. 点击toolbar中的图标，创建边。

当前文档中 create-edge 只能通过click, drag 节点来创建边。如何实现上述，点击图标（非节点）触发创建边的动作？

### What does the proposed API look like?
![image](https://user-images.githubusercontent.com/8284773/114310684-2b237400-9b1e-11eb-980c-75c5767b86d8.png)

**Comment by Yanyan-Wang** [comment]
可以自定义 toolbar 功能 https://codesandbox.io/s/sharp-frog-p6zyo
然后自己控制创建边的逻辑，就和内置 create-edge 无关

**Comment by JhonYoung** [comment]
> 可以自定义 toolbar 功能 https://codesandbox.io/s/sharp-frog-p6zyo
> 然后自己控制创建边的逻辑，就和内置 create-edge 无关

期望实现的效果是 类似于创建边的效果，从一个节点引申出一条点，当点击另一个节点时，完成边的创建。
见截图，有个连线的动作。

![Uploading image.png…]()

**Comment by Yanyan-Wang** [comment]
https://codepen.io/yumenglong/pen/xxEQdZJ?editors=1010

可以把你这里的 toolbar 两个按钮作为节点的一部分绘制，然后类似这个例子中从 anchorPoint 拖拽出一条边，就是在 create-edge 里面的 shouldBegin 里判断是不是点到了允许创建边的按钮上

**Comment by JhonYoung** [comment]
> https://codepen.io/yumenglong/pen/xxEQdZJ?editors=1010
> 
> 可以把你这里的 toolbar 两个按钮作为节点的一部分绘制，然后类似这个例子中从 anchorPoint 拖拽出一条边，就是在 create-edge 里面的 shouldBegin 里判断是不是点到了允许创建边的按钮上

thx. 我试一下给您这边反馈

**Comment by Yanyan-Wang** [comment]
是否可以解决？

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
