### ISSUE TITLE
LOUVAIN 自动聚类算法，示例不产生效果

### ISSUE THREAD

**Issue by javaNaruto** [antvis/G6#2809]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g6.antv.vision/zh/examples/algorithm/algoDemos#louvain](https://g6.antv.vision/zh/examples/algorithm/algoDemos#louvain)

### Steps to reproduce
点击自动聚类按钮，无算法结果产生的绘图效果

| Environment | Info |
|---|---|
| g6 | 4.2.5 |
| System | - |
| Browser | - |

---
https://g6.antv.vision/zh/largegraph，根据此示例仿写了一个demo，在调用LOUVAIN算法后的结果，集群边的起点id和终点id不能与集群点id匹配，控制台会报不存在某个起点或终点

**Comment by javaNaruto** [comment]
目前再次测试，同样的数据传入算法，得出的结果不同，是否与版本有关系？
结果1：集群点边数据能对应上
结果2：集群点id从1开始递增，集群边上的起点终点id在集群点中基本对应不上

**Comment by Yanyan-Wang** [comment]
感谢反馈，例子一会会修复。

> 目前再次测试，同样的数据传入算法，得出的结果不同，是否与版本有关系？
最新版本应该 cluster 的 id 是递增的，且 clusterEdges 中边的 source 和 target 也是对应 cluster 中递增的 id

**Comment by Yanyan-Wang** [comment]
官网例子已经修复，louvain 中使用的数据被深拷贝，需要将样式赋值到对应远数据上
