### ISSUE TITLE
现在是否已经剔除了以前版本 topo图线条可以编辑的功能

### ISSUE THREAD

**Issue by stonerao** [antvis/g6#281]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by TomHuangCN** [comment]
是的，目前 G6 就是一个渲染关系图的底层框架。上层图编辑器的交互功能都会放到 [G6-Editor](https://yuque.com/antv/g6-editor) 这个项目里。
