### ISSUE TITLE
brush-select与lasso-select共有的缺陷

### ISSUE THREAD

**Issue by Raven2049** [antvis/G6#2810]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/raven2049/pen/rNjGOBr](https://codepen.io/raven2049/pen/rNjGOBr)

### Steps to reproduce
1、摁住shift键开始框选combo1中的四个node，此时combo2为收缩状态，中有两个node为不可见状态
![image](https://user-images.githubusercontent.com/33887949/114339150-20e99000-9b87-11eb-8ad6-54e306add300.png)

2、双击combo2展开，可以看到combo2中有节点也被一起选中了（前提是框选的时候框到了某些节点的位置）
![image](https://user-images.githubusercontent.com/33887949/114339194-33fc6000-9b87-11eb-94e8-b7e5930d64a8.png)

| Environment | Info |
|---|---|
| g6 | 4.2.5 |
| System | win10 20H2 |
| Browser | edge chromium 89.0.774.75 x64 |

---
我当前开发的项目一个需求是框选节点组成combo，这可以解决，因为我可以在组成combo之前筛选掉不可见的节点；
但是现在的问题是，如果带着combo2中被选中节点一起拖到Combo外，那个combo2中的节点会消失掉；如果一起拖到另一个Combo内，也会消失，但是将那个Combo合并再展开是可以看到的

我现在想要做的是不想选中这些不可见的节点，或者多个节点一起拖动完可以遍历节点信息，如果是invisible就禁止update

**Comment by Raven2049** [comment]
解决了，在brush-select或lasso-select的shouldUpdate属性中配置函数就行了

**Comment by Yanyan-Wang** [comment]
今天会发布小版本修复这个问题
