### ISSUE TITLE
uni-app使用G6-mobile时还是警告文件体积过大，这样会影响性能。并且按照官方案例运行页面直接空白

### ISSUE THREAD

**Issue by xiaoqiang66** [antvis/G6#2812]
G6-mobile是否能支持uni-app

**Comment by baizn** [comment]
@openwayne  看下这个问题？

**Comment by openwayne** [comment]
1、针对包体积过大的问题，今天会发布一个版本，减少80k左右，但是G6Mobile本身体积还是有点大，建议在分包中使用，这样不占用主包的包大小。
2、针对G6Mobile，可以参考
https://github.com/openwayne/g6-component-alipay 
https://github.com/openwayne/g6-component-wx 
这两个组件，组件中做过一些兜底，uni-app的组件，我们争取在这周补充一个组件和demo。
