### ISSUE TITLE
使用布局预测功能，通过调用const { predictLayout, confidence } = await GraphLayoutPredict.predict(data);实现，浏览器报‘Unexpected reserved word’错误

### ISSUE THREAD

**Issue by javaNaruto** [antvis/G6#2813]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g6.antv.vision/zh/docs/manual/middle/layout/ai-layout#gatsby-focus-wrapper](https://g6.antv.vision/zh/docs/manual/middle/layout/ai-layout#gatsby-focus-wrapper)

### Steps to reproduce
const { predictLayout, confidence } = await GraphLayoutPredict.predict(data);浏览器报‘Unexpected reserved word’错误

| Environment | Info |
|---|---|
| g6 | 4.2.6 |
| System | - |
| Browser | - |

**Comment by baizn** [comment]
@semious  看下这个问题 ……

**Comment by javaNaruto** [comment]
能提供一个使用此布局的demo吗，官网上没有

**Comment by xdddst** [comment]
> 能提供一个使用此布局的demo吗，官网上没有

https://codesandbox.io/s/sharp-keller-hsvwc?file=/index.tsx

**Comment by javaNaruto** [comment]
> > 能提供一个使用此布局的demo吗，官网上没有
> 
> https://codesandbox.io/s/sharp-keller-hsvwc?file=/index.tsx

感谢回复
