### ISSUE TITLE
更新边的箭头样式失败

### ISSUE THREAD

**Issue by CathyZYF** [antvis/G6#2814]
[https://codepen.io/cathyzyf/pen/oNBqezO](https://codepen.io/cathyzyf/pen/oNBqezO)

如该案例所示，链路上原本存在startArrow(绿色)和endArrow(红色)，点击remove Arrow按钮，理论上应该去掉两个arrow，但执行完updateItem后，startArrow没有去掉
使用G6版本：4.2.5

**Comment by baizn** [comment]
下个小版本修复

**Comment by Yanyan-Wang** [comment]
fixed by 4.2.7
