### ISSUE TITLE
如何在graph绑定的event里读取react组件里的参数？

### ISSUE THREAD

**Issue by lmhgithi** [antvis/G6#2818]
除了用ref还有别的方法吗

**Comment by lmhgithi** [comment]
比如我在react组件里定义了一个方法，这个方法里使用了当前组件的入参。然后我想在graph的on node:mouseenter里用这个方法，用的时候拿不到方法所在组件的参数~

**Comment by baizn** [comment]
拿不到，你可以通过其他方式把所需要的参数缓存一下，然后在 graph.on 中使用。
