### ISSUE TITLE
G6通过proxy-polyfill兼容IE11后，控制台提示其他警告

### ISSUE THREAD

**Issue by yanliang-code** [antvis/G6#2821]
chrome 正常显示结果并运行，IE11 提示如图问题，无法正常渲染显示

<img width="596" alt="2021-04-14_231026" src="https://user-images.githubusercontent.com/60208330/114734464-cf075c80-9d76-11eb-9e6c-196195f55112.png">

**Comment by sllRoy** [comment]
我也遇到类似问题

**Comment by Yanyan-Wang** [comment]
不再考虑兼容 IE，因为 IE 已经下架啦
