### ISSUE TITLE
在G6的Graph中不能使用imageMiniMap。

### ISSUE THREAD

**Issue by donga-q** [antvis/G6#2823]
在G6的Graph中使用imageMiniMap，在绘图后不调用updateGraphImg()更新minimap的情况下，imageminiMap内部的视窗不能拖动；只能拖动主图，然后imageminimap的视窗跟着动；然后如果在graph.render()绘图后，调用updateGraphImg()更新minimap的情况下，拖动imageminMap内部的视窗，主图会直接卡死，没有报错信息。（官网示例是treeGraph）.下面是我的实例代码
const container = document.getElementById('container');
	const width = container.scrollWidth;
	const height = (container.scrollHeight || 500) - 110;
	const imageMiniMap = new G6.ImageMinimap({
		height: 400,
		graphImg: './data/A_DcGMQ7AN3Z0AAAAAAAAAAABkARQnAQ.jfif',
	});
	const graph = new G6.Graph({
		container: document.getElementById('container'),
		width,
		height,
		background: 'cadetblue',
		layout: {
			type: 'gForce',
			linkDistance: 300,
			nodeStrength: 5000,
			edgeStrength: 200,
			preventOverlap: true,
			nodeSize: 5,
			gpuEnabled: true
		},
		defaultNode: {
			size: 20,
			labelCfg: {
				position: 'bottom',
			}
		},
		minZoom: 0.02,
		maxZoom: 100000,
		modes: {
			default: ['zoom-canvas', 'drag-canvas']
		},
		plugins: [imageMiniMap]
	});

	fetch('./data/test100.json')
		.then((res) => res.json())
		.then((data) => {
			graph.data(data);
			graph.render();
		}).then(() => {
			imageMiniMap.updateGraphImg("./data/imageMiniMap.png")
		})

**Comment by ufresh2013** [comment]
楼主怎么解决的
