### ISSUE TITLE
两点间全部路径算法，算法结果无问题，在遍历边给边添加highlight状态时，部分边未成功

### ISSUE THREAD

**Issue by javaNaruto** [antvis/G6#2824]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/loving-yalow-mwneu?file=/index.js)

### Steps to reproduce
算法结果的路径无误，在选择较远两点，部分路径的highlight状态未激活，通过debugger看是进入到graph.setItemState(edge, 'highlight', true);这一步，但是最后的图未展示出效果

| Environment | Info |
|---|---|
| g6 | 4.2.6 |
| System | - |
| Browser | - |

**Comment by javaNaruto** [comment]
![image](https://user-images.githubusercontent.com/48909573/114834402-1804f280-9e03-11eb-8bdf-0db592afa417.png)

**Comment by Yanyan-Wang** [comment]
因为你在遍历其他 path 的时候，line97 行又把某些边的状态变成 inactive 了

**Comment by javaNaruto** [comment]
> 因为你在遍历其他 path 的时候，line97 行又把某些边的状态变成 inactive 了

感谢回复
