### ISSUE TITLE
调用collapseExpandCombo方法之后，edges渲染错乱，另外触发重新布局之后，dagre布局异常

### ISSUE THREAD

**Issue by Tronsfey** [antvis/G6#2825]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/floral-leaf-2ci08?file=/index.js)

### Steps to reproduce
直接查看codesandbox的demo

| Environment | Info |
|---|---|
| g6 | 4.2.6 |
| System | - |
| Browser | - |

收起combo C之后，连到C内部的edges渲染异常了
![image](https://user-images.githubusercontent.com/4178124/114867775-c4f16680-9e27-11eb-83f2-a12b0560fe39.png)

收起combo D之后，触发重新布局，布局错乱
![image](https://user-images.githubusercontent.com/4178124/114867803-cd49a180-9e27-11eb-81c7-769cf22ac0ac.png)

**Comment by Yanyan-Wang** [comment]
边错乱问题已修复 by 4.2.7

布局错乱是由于 combo 本身不会参与布局计算，布局计算的是节点位置。非空 Combo 的位置仅由内部节点位置决定。空 combo 可指定位置。

**Comment by Tronsfey** [comment]
https://codesandbox.io/s/floral-leaf-2ci08?file=/index.js

1、升级到4.2.7版本之后，edge在combo收起之后错乱的问题消失了，但是出现edge跟combo重叠的情况。
![image](https://user-images.githubusercontent.com/4178124/115707096-f2e32780-a3a0-11eb-945d-39c6def94f7b.png)

2、收起combo之后触发布局，布局错乱的问题还是存在
![image](https://user-images.githubusercontent.com/4178124/115707113-f9719f00-a3a0-11eb-9661-2d3301f0bc9b.png)
