### ISSUE TITLE
Combos that are collapsed initially - Animation is they are opened and closed

### ISSUE THREAD

**Issue by JyotsnaC** [antvis/G6#2826]
- [x ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/headless-water-ljqu2?file=/index.js)

### Steps to reproduce
You can use the above link or any built in combo and one of the combo is collapsed

combos: [
    {
      id: "combo",
      label: "Combo",
      collapsed: "true"
    }
  ]
As you see the collapsed in true for the combo but the combo has an animation that it is expanded first and it is collapsed . This is a big problem as there are at least 1000 nodes per combo and when ever we draw all the combos looks as if they are dancing.

![Screen Recording 2021-04-15 at 4 50 29 PM](https://user-images.githubusercontent.com/274296/114943715-0a079f80-9e0c-11eb-90e1-04cb066d2b04.gif)

This is in reference to the discussion
| Environment | Info |
|---|---|
| g6 | 4.2.6 |
| System | Mac Os latest |
| Browser | Chrome latest |

**Comment by Yanyan-Wang** [comment]
will be fixed by next small version
