### ISSUE TITLE
Animation for Combos expanding and collapsing

### ISSUE THREAD

**Issue by JyotsnaC** [antvis/G6#2827]
- [X ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently there is very basic animation for combos expand. Would like to understand is there any way we could achieve the smooth transition for combos expand or collapse

### What does the proposed API look like?
We are trying to build set of combos and nodes insides combos in a grid fashion. Below is the Animated video that I am refereeing to and what the transition looks like . White rectangles are combos and gray rectangles are nodes

![topology_expandCombo_animation](https://user-images.githubusercontent.com/274296/114944436-32dc6480-9e0d-11eb-8a43-872f7c500746.gif)

**Comment by Yanyan-Wang** [comment]
Thanks, good suggestion. But it is not in our plan for now. Welcome contributions from communities.

**Comment by JyotsnaC** [comment]
Thank you for your suggestion. will contribute.
