### ISSUE TITLE
如何在离开画布时让tooltip隐藏

### ISSUE THREAD

**Issue by lmhgithi** [antvis/G6#2829]
在graph布局中，如果有node在画布边缘，并且我应用了tooltip作为plugin，在我的鼠标从画布边缘的node移出画布时，tooltip没有隐藏。

**Comment by Yanyan-Wang** [comment]
下个小版本即将修复

**Comment by Yanyan-Wang** [comment]
fixed by 4.2.7

**Comment by liuhaha5** [comment]
4.3.11也有这个bug
