### ISSUE TITLE
Losing combo styling and unable to deactivate-relations after enabling activate relations on click 

### ISSUE THREAD

**Issue by brishable** [antvis/G6#2830]
**G6 Version: 4.2.6
OS: Windows 10**
Example code: [https://codesandbox.io/s/ecstatic-ganguly-mhhc0?file=/index.js](https://codesandbox.io/s/ecstatic-ganguly-mhhc0?file=/index.js)

I enabled “activate-relations” on the graph and set the trigger mechanism to be on “click”.

**NB: When the activate-relation trigger is not set to click**  `//trigger: "click"` **the style of combos and edges is restored as soon as you leave the node**

Expected behavior:
•	When I click on a particular node we want the relations to be seen 
•	When I click somewhere else, for instance on the canvas I want all the activated, blue edges to be replaced by normal edges and the graph to return to its original view 

**Issue 1:**
1.	If you click over node “NODE5” you will see that its connections to three other nodes are activated and the rest is grayed out which is okay
2.	If you click over the canvas to deactivate the relations, the blue lines are replaced by normal lines, but the background color and styling of combos are lost. I don’t seem to be able to get it back.

**Issue 2:**
1.	Reload the page
2.	If you collapse one of the combos, “COMBTUH4” for instance, and click on the node “NODE5” then you will see the relations activated to the currently collapsed combo and two other nodes.
3.	If you click on the canvas to de-activate the relations, the two activated edges connected to the nodes are replaced by normal lines but the one from the node “NODE5” to combo “COMBTUH4” is not.
4.	And we have lost the initial styling of combos, like their fill color in this case.
The only thing that seems to work is to do `graph.render()` on canvas click but it will redraw the whole graph, change zoom level …  and it takes time especially in large graphs. 

Are these bugs or is there any way to get it working without calling graph.render()?

**Comment by Yanyan-Wang** [comment]
will be fixed by next small version

**Comment by Yanyan-Wang** [comment]
fixed by 4.2.7
