### ISSUE TITLE
使用官网给自定义dom节点绑定监听事件未生效问题

### ISSUE THREAD

**Issue by voidCreate** [antvis/G6#2832]
代码链接：
https://riddle.alibaba-inc.com/riddles/new 
希望帮忙看下问题

init() {
      const that = this;
      G6.registerNode(
          'tree-node',
          {
            drawShape: function drawShape(cfg, group) {
              
              const content = cfg.facilityName + ': ' + cfg.name;
              const html = `
                <div id=${
                  cfg.id
                } class='dom-node' style="background-color: #fff; border: 2px solid #666; border-radius: 5px; width: ${
                  170
                }px; height: ${45 - 5}px; display: flex;"
                >
                  <div style="height: 100%; background-color: #CDDDFD">
                    <img alt="" style="line-height: 100%; margin-left: 7px;" src="https://gw.alipayobjects.com/mdn/rms_f8c6a0/afts/img/A*Q_FQT6nwEC8AAAAAAAAAAABkARQnAQ" width="20" height="20" />  
                  </div>
                  <span style="margin:auto; padding:auto; color: #5B8FF9;">${content}</span>
                </div>
              `
              const shape = group.addShape('dom', {
                attrs: {
                  y: -20,
                  width: 155,
                  height: 40,
                  html: html,
                },
                draggable: true,
              });
              const bbox = shape.getBBox();
              const hasChildren = cfg.children && cfg.children.length > 0;
              if (hasChildren) {
                group.addShape('circle', {
                  attrs: {
                    x: bbox.maxX + 5,
                    y: 0,
                    r: 10,
                    fill: '#5B8FF9',
                  },
                  name: 'circle-shape',
                });
                group.addShape('text', {
                  attrs: {
                    x: bbox.maxX + 5,
                    y: 0,
                    r: 6,
                    textAlign: 'center',
                    textBaseline: 'middle',
                    text: cfg.collapsed ? '+' : '-',
                    fontSize: 16,
                    cursor: 'pointer',
                    fill: 'rgba(0, 0, 0, 0.25)',
                    stroke: '#666',
                    lineWidth: 2,
                    // html: <Icon type="add-circular" />
                  },
                  name: 'collapse-text',
                  modelId: cfg.id
                });
              } else {
                group.addShape('circle', {
                  attrs: {
                    x: bbox.maxX + 5,
                    y: 0,
                    r: 10,
                    fill: '#5B8FF9',
                  },
                  name: 'circle-shape',
                });
                group.addShape('text', {
                  attrs: {
                    x: bbox.maxX + 5,
                    y: 0,
                    r: 6,
                    textAlign: 'center',
                    textBaseline: 'middle',
                    text: !cfg.collapsed ? '+' : '-',
                    fontSize: 16,
                    cursor: 'pointer',
                    fill: 'rgba(0, 0, 0, 0.25)',
                    stroke: '#666',
                    // html: <Icon type="add-circular" />
                  },
                  name: 'collapse-text',
                  modelId: cfg.id
                });
              }
              return shape;
            },
            update: (cfg, item) => {
              const group = item.getContainer();
              const text = group.find((e) => e.get('name') === 'collapse-text');
              text.attr('text', cfg.collapsed ? '+' : '-')
            },
          },
          'single-node',
        );
          
          const container = document.getElementById('topology');
          const width = container.scrollWidth;
          const height = 500;
          const graph = new G6.TreeGraph({
            container: 'topology',
            renderer: 'svg',
            width,
            height,
            animate: true,
            modes: {
              default: [
                {
                  type: 'collapse-expand',
                  onChange: function onChange(item, collapsed) {
                    console.log(item, 'itemm', collapsed)
                    const data = item.get('model');
                    graph.updateItem(item, {
                      collapsed,
                    });
                    data.collapsed = collapsed;
                    return true;
                  },
                },
                'drag-canvas',
                'zoom-canvas',
              ],
            },
            defaultNode: {
              type: 'tree-node',
              // anchorPoints: [
              //   [0, 0.5],
              //   [1, 0.5],
              // ],
            },
            defaultEdge: {
              type: 'cubic-horizontal',
              style: {
                stroke: '#A3B1BF',
              },
            },
            layout: {
              type: 'compactBox',
              direction: 'LR',
              getId: function getId(d) {
                return d.id;
              },
              getHeight: function getHeight() {
                return 16;
              },
              getWidth: function getWidth() {
                return 50;
              },
              getVGap: function getVGap() {
                return 20;
              },
              getHGap: function getHGap() {
                return 200;
              },
            },
          });
          graph.data(this.props.data[0]);
          graph.render();
          graph.fitView();

          const listener = (dom) => {
            console.log('11111', 'listener')
          }

          const bindClickListener = () => {
            const domNodes = document.getElementsByClassName('dom-node');
            console.log(domNodes, 'domNodes')
            for (let i = 0; i < domNodes.length; i++) {
              const dom = domNodes[i];
              // open the following lines pls!
              dom.addEventListener('click', (e) => {
                listener(dom);
              });
            }
          };
          graph.on('node:click', ev => {
            console.log('1111')
          })
            
          
          bindClickListener();
          
          graph.on('afterupdateitem', (e) => {
            console.log('22222')
            return bindClickListener();
          });
    
          graph.on('afterrender', (e) => {
            console.log('3333333')
            return bindClickListener();
          });

          if (typeof window !== 'undefined')
            window.onresize = () => {
              if (!graph || graph.get('destroyed')) return;
              if (!container || !container.scrollWidth || !container.scrollHeight) return;
              graph.changeSize(container.scrollWidth, container.scrollHeight);
            };
    }

**Comment by baizn** [comment]
使用 DOM 自定义的节点不支持 graph.on 绑定， 可以使用原生 dom 的事件绑定方式。

**Comment by voidCreate** [comment]
我使用原生dom事件进行绑定时，会报is not defined，所以我又使用了在render后监听绑定click事件，以下是我的两个demo

原生绑定demo：

const listener = (dom) => {
        console.log('11111', 'listener')
      }
      G6.registerNode(
        'tree-node',
        {
          draw: (cfg, group) => {
            const content = cfg.facilityName + ': ' + cfg.name;
            const html = `
              <div id=${
                cfg.id
              } class='dom-node' style="background-color: #fff; border: 2px solid #666; border-radius: 5px; width: ${
                170
              }px; height: ${45 - 5}px; display: flex;"
              onclick="listener()"
              >
                <div style="height: 100%; background-color: #CDDDFD">
                  <img alt="" style="line-height: 100%; margin-left: 7px;" src="https://gw.alipayobjects.com/mdn/rms_f8c6a0/afts/img/A*Q_FQT6nwEC8AAAAAAAAAAABkARQnAQ" width="20" height="20" />  
                </div>
                <span style="margin:auto; padding:auto; color: #5B8FF9;">${content}</span>
              </div>
            `
            const shape = group.addShape('dom', {
              attrs: {
                y: -20,
                width: 155,
                height: 40,
                html: html,
              },
              draggable: true,
            });
            const bbox = shape.getBBox();
            const hasChildren = cfg.children && cfg.children.length > 0;
            if (hasChildren) {
              group.addShape('circle', {
                attrs: {
                  x: bbox.maxX + 5,
                  y: 0,
                  r: 10,
                  fill: '#5B8FF9',
                },
                name: 'circle-shape',
              });
              group.addShape('text', {
                attrs: {
                  x: bbox.maxX + 5,
                  y: 0,
                  r: 6,
                  textAlign: 'center',
                  textBaseline: 'middle',
                  text: cfg.collapsed ? '+' : '-',
                  fontSize: 16,
                  cursor: 'pointer',
                  fill: 'rgba(0, 0, 0, 0.25)',
                  stroke: '#666',
                  lineWidth: 2,
                  // html: <Icon type="add-circular" />
                },
                name: 'collapse-text',
                modelId: cfg.id
              });
            } else {
              group.addShape('circle', {
                attrs: {
                  x: bbox.maxX + 5,
                  y: 0,
                  r: 10,
                  fill: '#5B8FF9',
                },
                name: 'circle-shape',
              });
              group.addShape('text', {
                attrs: {
                  x: bbox.maxX + 5,
                  y: 0,
                  r: 6,
                  textAlign: 'center',
                  textBaseline: 'middle',
                  text: !cfg.collapsed ? '+' : '-',
                  fontSize: 16,
                  cursor: 'pointer',
                  fill: 'rgba(0, 0, 0, 0.25)',
                  stroke: '#666',
                  // html: <Icon type="add-circular" />
                },
                name: 'collapse-text',
                modelId: cfg.id
              });
            }
            return shape;
          },
          update: (cfg, item) => {
            const group = item.getContainer();
            const text = group.find((e) => e.get('name') === 'collapse-text');
            text.attr('text', cfg.collapsed ? '+' : '-')
          },
        },
        'single-node',
        );
  // const container = document.getElementById('topology');
  const width = this.container.scrollWidth;
  const height = 500;
  const graph = new G6.TreeGraph({
    container: this.container,
        // container: this.container,
    width,
    height,
    // translate the graph to align the canvas's center, support by v3.5.1
    // fitCenter: true,
    renderer: 'svg',
    linkCenter: true,
    modes: {
      default: [
        // {
        //   type: 'collapse-expand',
        //   onChange: function onChange(item, collapsed) {
        //     console.log(item, 'itemm', collapsed)
        //     const data = item.get('model');
        //     this.graph.updateItem(item, {
        //       collapsed,
        //     });
        //     data.collapsed = collapsed;
        //     return true;
        //   },
        // },
        'drag-canvas',
        'zoom-canvas',
      ],
  },
    defaultNode: {
      type: 'tree-node',
      size: [120, 40],
    },
    defaultEdge: {
      type: 'cubic-horizontal',
      style: {
        stroke: '#A3B1BF',
    },
},
layout: {
  type: 'compactBox',
  direction: 'LR',
  getId: function getId(d) {
    return d.id;
  },
  getHeight: function getHeight() {
    return 16;
  },
  getWidth: function getWidth() {
    return 50;
  },
  getVGap: function getVGap() {
    return 20;
  },
  getHGap: function getHGap() {
    return 200;
  },
}, 
  });
  graph.data(this.data[0]);
  graph.render();
  graph.fitView();
  
  
  监听绑定demo：
  
  const listener = (dom) => {
        console.log('11111', 'listener')
      }
      G6.registerNode(
        'tree-node',
        {
          draw: (cfg, group) => {
            const content = cfg.facilityName + ': ' + cfg.name;
            const html = `
              <div id=${
                cfg.id
              } class='dom-node' style="background-color: #fff; border: 2px solid #666; border-radius: 5px; width: ${
                170
              }px; height: ${45 - 5}px; display: flex;"
              onclick="listener()"
              >
                <div style="height: 100%; background-color: #CDDDFD">
                  <img alt="" style="line-height: 100%; margin-left: 7px;" src="https://gw.alipayobjects.com/mdn/rms_f8c6a0/afts/img/A*Q_FQT6nwEC8AAAAAAAAAAABkARQnAQ" width="20" height="20" />  
                </div>
                <span style="margin:auto; padding:auto; color: #5B8FF9;">${content}</span>
              </div>
            `
            const shape = group.addShape('dom', {
              attrs: {
                y: -20,
                width: 155,
                height: 40,
                html: html,
              },
              draggable: true,
            });
            const bbox = shape.getBBox();
            const hasChildren = cfg.children && cfg.children.length > 0;
            if (hasChildren) {
              group.addShape('circle', {
                attrs: {
                  x: bbox.maxX + 5,
                  y: 0,
                  r: 10,
                  fill: '#5B8FF9',
                },
                name: 'circle-shape',
              });
              group.addShape('text', {
                attrs: {
                  x: bbox.maxX + 5,
                  y: 0,
                  r: 6,
                  textAlign: 'center',
                  textBaseline: 'middle',
                  text: cfg.collapsed ? '+' : '-',
                  fontSize: 16,
                  cursor: 'pointer',
                  fill: 'rgba(0, 0, 0, 0.25)',
                  stroke: '#666',
                  lineWidth: 2,
                  // html: <Icon type="add-circular" />
                },
                name: 'collapse-text',
                modelId: cfg.id
              });
            } else {
              group.addShape('circle', {
                attrs: {
                  x: bbox.maxX + 5,
                  y: 0,
                  r: 10,
                  fill: '#5B8FF9',
                },
                name: 'circle-shape',
              });
              group.addShape('text', {
                attrs: {
                  x: bbox.maxX + 5,
                  y: 0,
                  r: 6,
                  textAlign: 'center',
                  textBaseline: 'middle',
                  text: !cfg.collapsed ? '+' : '-',
                  fontSize: 16,
                  cursor: 'pointer',
                  fill: 'rgba(0, 0, 0, 0.25)',
                  stroke: '#666',
                  // html: <Icon type="add-circular" />
                },
                name: 'collapse-text',
                modelId: cfg.id
              });
            }
            return shape;
          },
          update: (cfg, item) => {
            const group = item.getContainer();
            const text = group.find((e) => e.get('name') === 'collapse-text');
            text.attr('text', cfg.collapsed ? '+' : '-')
          },
        },
        'single-node',
        );
  const width = this.container.scrollWidth;
  const height = 500;
  const graph = new G6.TreeGraph({
    container: this.container,
        // container: this.container,
    width,
    height,
    // fitCenter: true,
    renderer: 'svg',
    linkCenter: true,
    modes: {
      default: [
        {
          type: 'collapse-expand',
          onChange: function onChange(item, collapsed) {
            console.log(item, 'itemm', collapsed)
            const data = item.get('model');
            this.graph.updateItem(item, {
              collapsed,
            });
            data.collapsed = collapsed;
            return true;
          },
        },
        'drag-canvas',
        'zoom-canvas',
      ],
  },
    defaultNode: {
      type: 'tree-node',
      size: [120, 40],
    },
    defaultEdge: {
      type: 'cubic-horizontal',
      style: {
        stroke: '#A3B1BF',
    },
},
layout: {
  type: 'compactBox',
  direction: 'LR',
  getId: function getId(d) {
    return d.id;
  },
  getHeight: function getHeight() {
    return 16;
  },
  getWidth: function getWidth() {
    return 50;
  },
  getVGap: function getVGap() {
    return 20;
  },
  getHGap: function getHGap() {
    return 200;
  },
}, 
  });
  graph.data(this.data[0]);
  graph.render();
  graph.fitView();

  const bindClickListener = () => {
    const domNodes = document.getElementsByClassName('dom-node');
    console.log(domNodes, 'domNodes', graph)

    for (let i = 0; i < domNodes.length; i++) {
      const dom = domNodes[i];
      // open the following lines pls!
      dom.addEventListener('click', (e) => {
        console.log(e, 'eeee')
        listener(dom);
      });
    }
  };
    
  
  bindClickListener();
  
  graph.on('afterupdateitem', (e) => {
    console.log('22222')
    return bindClickListener();
  });

  graph.on('afterrender', (e) => {
    console.log('3333333')
    return bindClickListener();
  });

  // this.graphRender();

  if (typeof window !== 'undefined')
    window.onresize = () => {
      if (!graph || graph.get('destroyed')) return;
      if (!this.container || !this.container.scrollWidth || !this.container.scrollHeight) return;
      graph.changeSize(this.container.scrollWidth, this.container.scrollHeight);
    };
}

**Comment by Yanyan-Wang** [comment]
render 之前 dom 还没绘制出来所以绑定不上，所以要 render 之后再绑定。使用后者可以的，但需要注意的是，每次更新图，包括节点的更新、视口的更新，都会导致 DOM 的销毁和重绘，因此此前绑定的监听将会失效，需要重新绑定。这里监听 afterupdateitem 使再次绑定监听也是这个目的。你这里使用到树图，树图默认是有动画的，动画的每一帧都是在更新图，即销毁和重新绘制 DOM，所以需要在动画结束之后重新绑定监听：

graph.on('afteranimate', (e) => {
return bindClickListener();
});

这样就可以了。
