### ISSUE TITLE
自定义combo的label怎么设置

### ISSUE THREAD

**Issue by lichunli6456** [antvis/G6#2833]
自定义combo为rect，label没有显示出来，label要怎么设置呢

**Comment by Yanyan-Wang** [comment]
自定义 combo？https://g6.antv.vision/zh/examples/item/customCombo#cRect

内置 combo 配置 label。有问题的话请给出在线复现 demo

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
