### ISSUE TITLE
How does it possible to filter data?

### ISSUE THREAD

**Issue by mostopalove** [antvis/G6#2837]
Is there an example of data filtering code for charts as described in the documentation?
https://g6.antv.vision/en/docs/manual/cases/relations/#data-filtering

**Comment by Yanyan-Wang** [comment]
you could achieve it by assembling `hideItem` and `showItem`:

graph.getNodes().forEach(node => {
  if (node.xxx some condition) {
    graph.hideItem(node)
  } else {
    graph.showItem(node)
  }
})

API of these two functions: https://g6.antv.vision/zh/docs/api/graphFunc/item#graphshowitemitem-stack

**Comment by mostopalove** [comment]
@Yanyan-Wang Is this the correct behavior for a compactBox graph? When the function `graph.hideItem(node)` is called, the node is hidden, but the array of its children is still present on the graph?

**Comment by Yanyan-Wang** [comment]
Yes, when hide a node with hideItem, only the manipulated node and related edges will be hidden in the same time. If you want to hide the whole sub tree, try to traverse sub tree and hide every node, or just collapse the subtree first, and then hide then root of the subtree, e.g.:

      node.getModel().collapsed = true
      graph.layout();
      graph.hideItem(node)

**Comment by mostopalove** [comment]
@Yanyan-Wang  Thank you! But how can I align the graph structure after filtering like this? See screenshot before and after filtering.

Before filter:
![Before filter](https://user-images.githubusercontent.com/49098339/115739084-4b60f780-a396-11eb-8a5f-936855bcb920.jpg)
After filter:
![After filter](https://user-images.githubusercontent.com/49098339/115739125-51ef6f00-a396-11eb-9ba1-77d8f74e6933.jpg)

**Comment by Yanyan-Wang** [comment]
It might be related to the custom node, please provide a simple reproduced online demo, and I will try to figure it out

**Comment by Yanyan-Wang** [comment]
Hi, dear user. Since there was no response for a long time, we cannot figure out the answer of the problem you described. If there is new progress, feel free to open a new issue.
