### ISSUE TITLE
自定义布局

### ISSUE THREAD

**Issue by leosxie** [antvis/G6#2839]
- **G6 Version**:4.2.6
- **Platform**: mac
- **Mini Showcase(like screenshots)**:
-  目前支持：new G6.Layout.dagre类似的子布局。
-  期望：能否支持使用树进行子布局，比如new G6.Layout. dendrogram

**Comment by Yanyan-Wang** [comment]
目前没有开放与 Graph 相同 API 的树图布局。树图布局是另外一个库，可以这样使用

import Hierarchy from '@antv/hierarchy';
const layoutData = Hierarchy['dendrogram'](treeGraphData, layoutConfig);

**Comment by Yanyan-Wang** [comment]
duplicated to https://github.com/antvis/G6/issues/2831
