### ISSUE TITLE
graph.render() moves the alignment

### ISSUE THREAD

**Issue by ankitachdhr145** [antvis/G6#2840]
There is an issue with collapsing a combo and moving it to a desired x & y coordinates after collapse with graph.render(). Code is available in sandbox at: **https://codesandbox.io/s/heuristic-shaw-oi7fz?file=/index.js**
when you run the code then go to "parent 5" and collapse it. Since for our requirement we have to pull the parent 5 to the top after collapse. In order to do so we have to call graph.render() because the x & y are not updated to our desired location until we don't call render(). when render is called the whole view moves/refreshes instead of just the selected combo getting collapsed and moving it to the top.

How this is achievable without moving the view with render() or any other method instead of graph.render() which pulls the combo to our desired location? we already tried graph.refreshPositions(). It didnt work.

Note: we cant only use graph.expandCollapseCombo() on collapse method because it collapses the combo in the middle of all its children whereas we want the combo to collapse and move to the top instead of the middle location.

- Zoom in to "Parent 5" and double click on "Parent 5" to collapse

![image](https://user-images.githubusercontent.com/60146248/115397250-2f1e5880-a1e6-11eb-8615-c4148aff131a.png)

- View gets changed instead of the combo getting collapsed and moving to the top
![image](https://user-images.githubusercontent.com/60146248/115397112-04340480-a1e6-11eb-962a-fe53b9a6e8c1.png)

**Comment by Yanyan-Wang** [comment]
https://codesandbox.io/s/serene-night-bb7mn?file=/index.js

Try this way and see if it is the result you want

**Comment by ankitachdhr145** [comment]
Thanks I think this will solve our issue
