### ISSUE TITLE
官方文档说明不足

### ISSUE THREAD

**Issue by RequireSun** [antvis/G6#2841]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/custom-node#5-%E4%BD%BF%E7%94%A8-dom-%E8%87%AA%E5%AE%9A%E4%B9%89%E8%8A%82%E7%82%B9](https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/custom-node#5-%E4%BD%BF%E7%94%A8-dom-%E8%87%AA%E5%AE%9A%E4%B9%89%E8%8A%82%E7%82%B9)

### Steps to reproduce
自定义 DOM 类型节点的特性，只在 svg 的渲染模式下可用，但官网文档并未说明，我自己摸索了半个多小时才找到原因

| Environment | Info |
|---|---|
| g6 | 4.2.6 |
| System | - |
| Browser | - |

**Comment by Yanyan-Wang** [comment]
好的，感谢反馈，这个文档会尽快完善这一点。之前是在这里写的，https://g6.antv.vision/zh/docs/api/shapeProperties#dom-svg 
 可能太远了

**Comment by Yanyan-Wang** [comment]
文档已更新
