### ISSUE TITLE
export 'LayoutWorker' was not found in '../../layout/worker/layout.worker'

### ISSUE THREAD

**Issue by qiuyeduxin** [antvis/G6#2842]
import G6 from '@antv/g6' @4.2.6版本

webpack报警告
WARNING in ./node_modules/@antv/g6-pc/es/graph/controller/layout.js 73:20-32
"export 'LayoutWorker' was not found in '../../layout/worker/layout.worker'
![image](https://user-images.githubusercontent.com/10897871/115495458-3dc64780-a29a-11eb-82ce-c8244262c891.png)

看起来是LayoutWorker export时候的问题，如何解决

**Comment by qiuyeduxin** [comment]
发现问题是 因为源码中 
![image](https://user-images.githubusercontent.com/10897871/115497593-87189600-a29e-11eb-9fc7-8822e6ee5d6d.png)
实际上应该是：
import LayoutWorker from '@antv/g6-pc/es/layout/worker/layout.worker' 而不是 { LayoutWorker }

**Comment by qiuyeduxin** [comment]
希望官方看一下这个问题

**Comment by Yanyan-Wang** [comment]
layout.worker.ts 中不是 export default 所以应该是 import { LayoutWorker } 呀 https://github.com/antvis/G6/blob/c216d5732ff8647547024b03df8fba3f7bcba80b/packages/pc/src/layout/worker/layout.worker.ts#L8。

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。

**Comment by ayiaq1** [comment]
+1， 4.2.7版本复现 
![image](https://user-images.githubusercontent.com/3860498/119285258-3bc61e80-bc74-11eb-8581-24a6a7d783c3.png)

**Comment by julius19910613** [comment]
+1 4.4.1 TS环境下复现

**Comment by laozhu** [comment]
使用 @ant-design/charts + umijs 时遇到同样的问题。

**Comment by liao02x** [comment]
@ant-design/charts 从1.0.13版本升级到更高时，因为@ant-design/charts的依赖更新遇到同样的问题

看了几天发现问题出在.worker.js这个后缀上。我们的业务也在使用web worker，根据web worker一般规范，web worker脚本才会使用.worker.js后缀，web worker相关的loader会匹配到这个文件。然而[这里官方的代码](https://github.com/antvis/G6/blob/c216d5732ff8647547024b03df8fba3f7bcba80b/packages/pc/src/layout/worker/layout.worker.ts#L8)是用来辅助创建web worker的，并不是真正的web worker脚本，经过相关loader处理后会出问题。

解决方法是在项目内限定loader的处理范围，同时希望官方能规范相关后缀的使用 @Yanyan-Wang
