### ISSUE TITLE
请问一个图中添加了timebar插件后， 需要重新刷新timebar数据会重复生成两个图，是叠加不是覆盖。但是使用this.graph.destroy();  再重新生成图会空白，有原因吗

### ISSUE THREAD

**Issue by BensonLam** [antvis/G6#2843]
请问一个图中添加了timebar插件后， 需要重新刷新timebar数据会重复生成两个图，是叠加不是覆盖。但是使用this.graph.destroy();  再重新生成图会空白，有原因吗

**Comment by Yanyan-Wang** [comment]
请给出在线复现 demo

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
