### ISSUE TITLE
Combo 重叠问题

### ISSUE THREAD

**Issue by L924553229** [antvis/G6#2847]
Combo 下只包含两个子 Combo, 子 Combo 出现重叠现象

示例: https://g6.antv.vision/zh/examples/net/comboForce#basicComboForce 中如下修改:
`nodes: [],
  edges:[],
  combos: [
      {
          id: 'a',
          label: 'Combo A',
      },
      {
          id: 'b',
          label: 'Combo B',
          parentId: 'a',
      },
      {
          id: 'c',
          label: 'Combo c',
          parentId: 'a',
      }
  ]`

**Comment by Yanyan-Wang** [comment]
由于 combo 位置大小由内部节点的位置决定，而布局计算的都是节点位置。你所说的这种情况因为没有节点，所以空 combo 的位置是随机的，并不是由布局算法计算出来的。但是空 combo 是可以通过在 combo 数据中写入 x 和 y 指定位置的。

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
