### ISSUE TITLE
案例“自定义复杂树图样式”拖动时会有乱的线条绘制，污染画布

### ISSUE THREAD

**Issue by atdow** [antvis/G6#2848]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://antv-g6.gitee.io/zh/examples/tree/customItemTree#customTree](https://antv-g6.gitee.io/zh/examples/tree/customItemTree#customTree)

### Steps to reproduce
拖动树图时会有乱的线条绘制，污染画布
![008d6ad339a6f61749772708f55ad69](https://user-images.githubusercontent.com/52809115/115647395-4aa87100-a356-11eb-9559-a752126c2bc2.png)

| Environment | Info |
|---|---|
| g6 | 4.2.6 |
| System | win10 |
| Browser | choreme |

**Comment by xiang130** [comment]
![](https://i.bmp.ovh/imgs/2021/04/9071318d31dd49ba.png)
我也遇到类似的情况，同求相关解决方式！！！

**Comment by iamsuyi** [comment]
我也遇到过。。mark
![image](https://user-images.githubusercontent.com/5397248/118767210-0ace9e00-b8b0-11eb-8ddd-268b7e8b9a08.png)

**Comment by xiang130** [comment]
//关闭局部渲染
graph.get('canvas').set('localRefresh', false);
之前参考的这个，你可以看下#2492

**Comment by xiang130** [comment]
但据说关闭局部渲染会影响性能，目前临时的解决方案就是先关闭局部渲染

**Comment by Yanyan-Wang** [comment]
遇到以上问题，尝试几个解决方案：
1. 检查节点中的图形，包括文本图形，样式配置中是否存在非法值，例如 null NaN 等；
2. 尽量使用整数座位数值型的样式值，例如 r width height fontSize 等
3. 使用浏览器字体作为 labelCfg.style.fontFamily
4. 给文本增加白色描边，如
labelCfg: {
  style: {
    stroke: '#fff',
    lineWidth: 4
  }
}

5. 以上方法都不奏效，关闭局部渲染 graph.get('canvas').set('localRefresh', false);  这个方法可能导致性能有所降低
