### ISSUE TITLE
树图布局      canvas画图高度 随着我的内容的高度 显示不同的自适应高度

### ISSUE THREAD

**Issue by somggud** [antvis/G6#2849]
canvas画图高度随着我的内容的高度而显示不同的自适应高度，而不是内容多了采用放大缩小方式展示，这个可以实现吗

**Comment by Yanyan-Wang** [comment]
graph.getGroup().getCanvasBBox() 可返回当前图内容的 bbox 信息，里面可以拿到宽高。拿到宽高之后再去调整容器大小，然后 graph.changeSize(width, height)
