### ISSUE TITLE
紧凑树等树图折叠时希望可以有不同颜色等标志表示该节点是折叠收起状态

### ISSUE THREAD

**Issue by atdow** [antvis/G6#2850]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
默认的紧凑树等树图折叠时希望可以有不同颜色等标志表示该节点是折叠收起状态，而不用使用group.addShape自定义来实现

### What does the proposed API look like?
效果如下图所示：
![b2b9e0ca7fba55d71d22a58d72eec2f](https://user-images.githubusercontent.com/52809115/115676117-d8e61c80-a381-11eb-8b1b-74ee5f569711.png)

**Comment by Yanyan-Wang** [comment]
可以设置内置节点的状态样式，并在折叠之后更新节点状态，如监听 itemcollapsed，更新节点：
graph.on('itemcollapsed', e => {
  graph.setItemState(e.item, 'xxx', e.collapsed);
})

事件文档：https://g6.antv.vision/zh/docs/api/Event#itemcollapsed
节点状态管理文档：https://g6.antv.vision/zh/docs/manual/advanced/state-new/#gatsby-focus-wrapper

**Comment by atdow** [comment]
```js
// 使用该api
graph.on('itemcollapsed', e => {
     graph.setItemState(e.item, 'selected', e.collapsed);
})
```
第一次折叠的是子类：
![image](https://user-images.githubusercontent.com/52809115/115696974-b9f18580-a395-11eb-8eb7-e67e7539bb89.png)
第二次折叠父类：
![image](https://user-images.githubusercontent.com/52809115/115697126-dab9db00-a395-11eb-89d0-5b7920477057.png)
第三次展开父类，子类是折叠状态，但是没有折叠的状态显示：
![image](https://user-images.githubusercontent.com/52809115/115697683-56b42300-a396-11eb-8296-4bfef6e73c08.png)

**Comment by Yanyan-Wang** [comment]
树的折叠和展开实际上会将被折叠的节点删去，展开时再加上。所以原来的状态就不在了。
可以在 itemcollapsed 里面遍历节点，数据中 collapsed 为 true 的设置状态

**Comment by atdow** [comment]
这样子的话其实不是很方便，因为折叠的状态显示其实是很有必要的，默认的时候感觉应该支持这样的特性，不用再手动去实现。
