### ISSUE TITLE
聚焦边位置不准确

### ISSUE THREAD

**Issue by junping1991** [antvis/G6#2853]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/clever-yalow-sxxcn?file=/index.js)

### Steps to reproduce
点击边，未将边定位到画布中间。
再次点击无效。
点击点，准确定位点到画布中间。

| Environment | Info |
|---|---|
| g6 | 4.2.6 |
| System | - |
| Browser | - |

**Comment by Yanyan-Wang** [comment]
下个小版本将修复

**Comment by Yanyan-Wang** [comment]
fixed by 4.3.0
