### ISSUE TITLE
activate-relations throws exception and breaks graph

### ISSUE THREAD

**Issue by brishable** [antvis/G6#2854]
**Version: 4.2.7
OS: Windows 10
Browser: Chrome latest**

Link to Sandbox: [https://codesandbox.io/s/ecstatic-ganguly-mhhc0?file=/index.js](https://codesandbox.io/s/ecstatic-ganguly-mhhc0?file=/index.js)

Description:
When activate relations is enabled (both with click and mouseenter) it throws an exception and breaks the graph. 
It works until you expand or collapse a combo but once you expand/collapse the graph is practically unusable.

**Steps to reproduce**
1. click on any node - activate relations works 
2. collapse any combo
3. click on any node to activate relations --- exception is thrown 

![image](https://user-images.githubusercontent.com/9823697/115834791-e51bb980-a415-11eb-82d1-d38b3b42225c.png)

activate-relations worked fine for earlier versions of G6

**Comment by Yanyan-Wang** [comment]
thanks, will be fixed by next small version

**Comment by Yanyan-Wang** [comment]
fixed by 4.3.0
