### ISSUE TITLE
graph.render()的回调问题

### ISSUE THREAD

**Issue by Lcyame** [antvis/G6#2855]
graph.render()是一个异步函数，有需求在其渲染完成后再执行方法。
例如：
graph.read(data);
let dataUrl = graph.toDataURL();
当画布中存在图片元素时， graph.toDataURL();生成的链接为空白。

所以需要一个同步方法或监听方法在画布渲染完毕后再执行。

![QQ截图20210423172803](https://user-images.githubusercontent.com/29159379/115852324-86c4fa00-a45a-11eb-863e-a95b66caa148.png)

**Comment by JyotsnaC** [comment]
You can try adding these calls after rendering the layout with below code

```
this.graph.on("afterlayout", e => { 
  graph.read(data);
  let dataUrl = graph.toDataURL();
}
```

**Comment by Lcyame** [comment]
> 您可以使用以下代码渲染布局后尝试添加这些调用
> 
> ```
> this.graph.on("afterlayout", e => { 
>   graph.read(data);
>   let dataUrl = graph.toDataURL();
> }
> ```

多谢回复！但是没有作用！

**Comment by Lcyame** [comment]
我的意思是画布中的元素图片是网络图片时，在渲染完毕后需要有一个方法来判断，以保证生成的dataurl不是空白图片

**Comment by Yanyan-Wang** [comment]
你说的图片是内置节点的 icon 吗，还是自定义节点。img 属性可以传 js 的 Image 对象，你可以使用原生 js Image 对象的 API 全部 onload 之后再传给 G6

**Comment by Lcyame** [comment]
> 你说的图片是内置节点的 icon 吗，还是自定义节点。img 属性可以传 js 的 Image 对象，你可以使用原生 js Image 对象的 API 全部 onload 之后再传给 G6

感谢回复，用的是自定义节点，icon的img用的是网络图片，我之前按你的思路试过了，好像不起作用啊


![1](https://user-images.githubusercontent.com/29159379/115981519-f952e880-a5c6-11eb-97a6-e97f89eb85ee.png)
![2](https://user-images.githubusercontent.com/29159379/115981520-fc4dd900-a5c6-11eb-8488-df8814b07f83.png)

**Comment by Lcyame** [comment]
来位大神解决一下吧，救救孩子

**Comment by Yanyan-Wang** [comment]
如果用 base64 的话应该没有这个问题。还有，新版支持了用 iconfont

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
