### ISSUE TITLE
Latest deployment of G6 version: 4.2.0 is breaking a few things because of the internal dependencies version upgrade

### ISSUE THREAD

**Issue by sandeepydhh** [antvis/G6#2857]
Latest deployment of G6 version: 4.2.0 is breaking the following things:

- Edges in the graph are getting merged and are becoming thick bulk lines occupying huge space on the canvas making the combos & nodes invisible behind them.
- activate relations isn't working & is throwing the following error:
![image](https://user-images.githubusercontent.com/9195929/115920243-3362a400-a47a-11eb-81cd-2c84c26571b2.png)

Previous deployments of version: 4.2.0 were working fine & these issues weren't there.
Following dependencies got updated in yarn.lock file & could be the cause for these breakages:
![image](https://user-images.githubusercontent.com/9195929/115920480-8c323c80-a47a-11eb-8299-874db5956400.png)

**Comment by Yanyan-Wang** [comment]
could you please provide online reproduced demos for these two issues?

**Comment by Yanyan-Wang** [comment]
> Edges in the graph are getting merged and are becoming thick bulk lines occupying huge space on the canvas making the combos & nodes invisible behind them.

is it duplicated to https://github.com/antvis/G6/issues/2856 ?

**Comment by Yanyan-Wang** [comment]
Hi, dear user. Since there was no response for a long time, we cannot figure out the answer of the problem you described. If there is new progress, feel free to open a new issue.
