### ISSUE TITLE
(BUG) Functions "item.getModel()" or "item.get('model')" do not always return full data. 

### ISSUE THREAD

**Issue by mostopalove** [antvis/G6#2858]
The following code will return data (e.g. anchorPoints, img, labelCfg, style) only for the last open subtree for graph with type collapse-expand.
`const nodes = graph.getNodes().map(n => n.get('model'))`

**Comment by Yanyan-Wang** [comment]
please provide an online reproduced demo

**Comment by mostopalove** [comment]
@Yanyan-Wang I'm afraid it will be difficult to do, since my graph is automatically supplemented with data from the server and the whole system cannot be shown online.

**Comment by Yanyan-Wang** [comment]
Is it possible to reproduce the issue with smallest dataset and minimum implementation? Without that, it is hard to figure out the problem.

**Comment by mostopalove** [comment]
@Yanyan-Wang When I did this, I saw that there was no such error on the new version. But since I noticed, I can not help but share an example of the code. Sorry for the quality of the code, since all these are torn pieces from the project and assembled on the go.
https://codepen.io/mostopalove/pen/QWdodNW

You can see that for version 3.8.5 not all data is returned in the console. For version 4.2.7, everything is ok.

**Comment by Yanyan-Wang** [comment]
So, it is solved? We suggest the users to follow the latest version ;)

For tree graph, if a subtree is collapsed, the hidden nodes will not in graph.getNodes(). If you wanna print all the data, try console.log(graph.save())

**Comment by Yanyan-Wang** [comment]
Hi, dear user. Since there was no response for a long time, we cannot figure out the answer of the problem you described. If there is new progress, feel free to open a new issue.
