### ISSUE TITLE
g6的依赖项中有些license不友好。有什么解决办法吗？例如：@antv/g-webgpu

### ISSUE THREAD

**Issue by diangongdianzi** [antvis/G6#2860]

**Comment by diangongdianzi** [comment]
https://www.npmjs.com/package/@antv/g-webgpu

**Comment by Yanyan-Wang** [comment]
AntV 的都是 MIT 协议，这边会补充一下。还有别的依赖有这样的问题吗？

**Comment by diangongdianzi** [comment]
打印了一下antv/g6de 依赖树如下所示，发现其确实间接依赖了@antv/g-webgpu。而@antv/g-webgpu的license是isc的。
+-- @antv/g6@4.2.7
| `-- @antv/g6-pc@0.2.7
|   +-- @antv/layout@0.1.12
|   | +-- @antv/g-webgpu@0.5.5
|   | | +-- @antv/g-webgpu-core@0.5.6
|   | | | +-- eventemitter3@4.0.7 deduped
|   | | | +-- gl-matrix@3.3.0 deduped
|   | | | +-- inversify@5.1.1 deduped
|   | | | +-- inversify-inject-decorators@3.1.0 deduped
|   | | | +-- probe.gl@3.3.1 deduped
|   | | | `-- reflect-metadata@0.1.13 deduped
|   | | +-- @antv/g-webgpu-engine@0.5.6
|   | | | +-- @antv/g-webgpu-core@0.5.6 deduped
|   | | | +-- @webgpu/glslang@0.0.15
|   | | | +-- @webgpu/types@0.0.31 deduped
|   | | | +-- gl-matrix@3.3.0 deduped
|   | | | +-- hammerjs@2.0.8 deduped
|   | | | +-- inversify@5.1.1 deduped
|   | | | +-- inversify-inject-decorators@3.1.0 deduped
|   | | | +-- probe.gl@3.3.1 deduped
|   | | | +-- reflect-metadata@0.1.13 deduped
|   | | | `-- regl@1.7.0

**Comment by Yanyan-Wang** [comment]
感谢 @xiaoiver
