### ISSUE TITLE
Can the dagre layout provide control of the number of nodes at the same level?

### ISSUE THREAD

**Issue by KaiyueNi** [antvis/G6#2861]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
If the number of downstream nodes of a node is too much, the image rendered by dagre layout greatly exceeds the screen, can you provide a way to limit the number of nodes

### What does the proposed API look like?
layout: {
        type: 'dagre', 
        rankdir: 'LR', 
        nodesep: 6, 
        ranksep: 80, 
        targetnum: 10 //Limit the number of downstream of each node that can be displayed at the same level
        targetsep: 10 //Display in layers after exceeding the limit. This is the layer spacing
  },

**Comment by KaiyueNi** [comment]
![pic](https://user-images.githubusercontent.com/29427470/116031992-6fbc1d00-a691-11eb-87a7-b289ea1fb24c.jpg)

**Comment by Yanyan-Wang** [comment]
you could assign layer in node data now, v4.7.x
![image](https://user-images.githubusercontent.com/29593318/203789818-455047f3-7002-4f9d-803a-edcbdcd4d978.png)
