### ISSUE TITLE
minimap在主图放大拖动点的情况下变得特别小，基本不能使用

### ISSUE THREAD

**Issue by donga-q** [antvis/G6#2863]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cnmql)

### Steps to reproduce
基于demo链接：
1.利用缩放功能放大主图
2.拖动主图顶点
3.此时观察minimap变成了很小的一点点，主图放大的越大，minimap越小。

| Environment | Info |
|---|---|
| g6 | 4.2.6 |
| System | win10 |
| Browser | chrome-78.0.3904.108 |

**Comment by Yanyan-Wang** [comment]
Fixed by 4.3.2
