### ISSUE TITLE
【求助贴】折线边路径重合，导致看起来存在"重复绘制"的问题

### ISSUE THREAD

**Issue by DearGaz** [antvis/G6#2864]
![微信图片_20210426144941](https://user-images.githubusercontent.com/41284640/116040482-ab111880-a69e-11eb-99c8-a2fde8658bcf.png)

如图

有节点A、B、C 

有边 A -> B 和 A -> C

A->C 这条边实际渲染出来的效果跟A->B 及中间路径上的边重合了。

**Comment by Yanyan-Wang** [comment]
如果是自动生成的 polyline，可以自己拿到相关的边更新 controlPoints，或者自定义折线 https://g6.antv.vision/zh/examples/item/customEdge#customPolyline

**Comment by DearGaz** [comment]
@Yanyan-Wang 感谢 
但是  “自己拿到相关边“这一步就不是很轻松  这种情况不属于图布局上的自动优化么？

**Comment by Yanyan-Wang** [comment]
如果是 dagre 的话，开启 dagre 自带的 controlPoints: true 会自动巡径

**Comment by DearGaz** [comment]
@Yanyan-Wang 是指这个配置么？https://g6.antv.vision/zh/docs/api/graphLayout/dagre#layoutcfgcontrolpoints  
倒没有特殊配置  所以应该就是开启（默认）的

**Comment by DearGaz** [comment]
用的也是dagre

**Comment by Yanyan-Wang** [comment]
> @Yanyan-Wang 是指这个配置么？https://g6.antv.vision/zh/docs/api/graphLayout/dagre#layoutcfgcontrolpoints
> 倒没有特殊配置 所以应该就是开启（默认）的

是这个属性，不过文档好像写错了，controlPoints 默认是 false。

**Comment by DearGaz** [comment]
哦~ 这样啊  我试试
