### ISSUE TITLE
g6的边和节点连接 必须通过 anchorPoints 来实现不同的位置吗，能否以鼠标点为锚点吗

### ISSUE THREAD

**Issue by bingyuea** [antvis/G6#2869]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
节点与边连接 anchorPoints不够灵活

### What does the proposed API look like?
能否直接指定坐标点，而不是通过getLinkPoint 获取最近的锚点

**Comment by Yanyan-Wang** [comment]
实例化图时配置 linkCenter: true 就会全部连接到节点中心。如果要用鼠标点击的位置为连接点，就在点击的时候更新 anchorPoints

**Comment by bingyuea** [comment]
点击的坐标能转化为anchorPoint吗 怎么转化 有api吗

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Yanyan Wang ***@***.***&gt;
发送时间: 2021年4月28日 19:48
收件人: antvis/G6 ***@***.***&gt;
抄送: 饼yue ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[antvis/G6] g6的边和节点连接 必须通过 anchorPoints 来实现不同的位置吗，能否以鼠标点为锚点吗 (#2869)

**Comment by Yanyan-Wang** [comment]
graph.on('node:click', e => {e.x e.y 就是鼠标点击位置}) 要把 e.x e.y 转换为和节点的相对位置，就是 e.item.getModel() 里面的 x y 和 e.item.getBBox() 的相对位置，更新到节点的 anchorPoints 数组里 graph.updateItem(item, {anchorPoints: ....})。

**Comment by Yanyan-Wang** [comment]
相对位置的相关概念可参考：https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/anchorpoint/#gatsby-focus-wrapper

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
