### ISSUE TITLE
树状图默认展示级别，设置的不管用，请问怎么回事

### ISSUE THREAD

**Issue by kellykelly28** [antvis/G6#2871]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
什么意思？不是很明白。写个在线 demo 看下？

**Comment by yflabc** [comment]
设置data的collapsed 是可以的呀 我已经实现了层级切换

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
