### ISSUE TITLE
Graph with combos - Minimap is broken

### ISSUE THREAD

**Issue by JyotsnaC** [antvis/G6#2872]
- [ x ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vigilant-solomon-yxxrp?file=/index.js)

### Steps to reproduce
When all the combos are collapsed and the type of the minimap is delegate or keyshape . The minimap is empty. You can see the minimap refelcting the contents for fairly a second and the screen goes blank

![Screen Recording 2021-04-30 at 8 33 12 PM](https://user-images.githubusercontent.com/274296/116825480-25391580-ab55-11eb-934e-4b6a3156d6b8.gif)

| Environment | Info |
|---|---|
| g6 | 4.2.7 |
| System | Mac Os latest |
| Browser | Chrome latest |

**Comment by Yanyan-Wang** [comment]
Fixed by 4.3.2
