### ISSUE TITLE
桑基图demo中指定 registerEdge的extendShapeType为“single-edge”后，桑基图的边变成了线条～

### ISSUE THREAD

**Issue by li379395535** [antvis/G6#2874]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qhzjy?file=/index.js:5813-5824)

### Steps to reproduce
在桑基图DEMO中，注册边时指定“extendShapeType”为“single-edge”。

| Environment | Info |
|---|---|
| g6 | 4.2.7 |
| System | - |
| Browser | - |

---
背景：希望将高亮状态应用到桑基图的边上，但是默认不会实现shape的setState，所以想通过继承原有shape的方式得到状态设置相关功能（shapeBase没有export出来，所以无法直接使用）.

**Comment by Yanyan-Wang** [comment]
可以复写 update 方法为 undefined，因为继承了 single-edge 之后就继承了它的 update 方法，所以有问题。
update: undefined 和 draw 方法平级

**Comment by li379395535** [comment]
> 可以复写 update 方法为 undefined，因为继承了 single-edge 之后就继承了它的 update 方法，所以有问题。
> update: undefined 和 draw 方法平级

谢谢，已经解决。 “ update: undefined 和 draw 方法平级”，再麻烦问下，这句话应该怎么理解啊。。。
