### ISSUE TITLE
Stroke on the image node shape

### ISSUE THREAD

**Issue by safinn** [antvis/G6#2875]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I don't think it is currently possible to add a stroke on an image node. I may have missed something but It would be nice if this was supported rather than having to make a custom node.

### What does the proposed API look like?
style: {
  stroke: '#ff0000',
  lineWidth: 5,
}

**Comment by safinn** [comment]
I will give that a shot thank you. After looking at some examples I also managed to create a custom node based on the image node and included a circle behind it.

10 May 2021 07:49:43 Yanyan Wang ***@***.***>:

**Comment by Yanyan-Wang** [comment]
We won't consider add this feature to image node in v4.x now. Anyone has this requirement could refer to the two solutions mentioned above. And we also welcome Pull Request from community ;)
