### ISSUE TITLE
detectDirectedCycle,detectAllCycles is not a function

### ISSUE THREAD

**Issue by javaNaruto** [antvis/G6#2876]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/loving-yalow-mwneu?file=/index.js)

### Steps to reproduce
引入detectDirectedCycle，detectAllCycles 算法控制台报错

| Environment | Info |
|---|---|
| g6 | 4.2.7 |
| System | - |
| Browser | - |

**Comment by Yanyan-Wang** [comment]
fixed by 4.3.0

**Comment by javaNaruto** [comment]
> fixed by 4.3.0

请问4.3.0什么时候发版呢

**Comment by Yanyan-Wang** [comment]
已经发了呀

**Comment by javaNaruto** [comment]
好的，谢谢
