### ISSUE TITLE
4.2.7版本报警告

### ISSUE THREAD

**Issue by Superzzw1994** [antvis/G6#2877]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/epic-tdd-dgicc?file=/src/index.js)

### Steps to reproduce
WARNING in ./node_modules/@antv/g6-plugin/es/timeBar/index.js 148:19-29
export 'Canvas' (imported as 'GSVGCanvas') was not found in '@antv/g-svg' (possible exports: default)

4.2.7版本初始化G6后 报警告
| Environment | Info |
|---|---|
| g6 | 4.2.7 |
| System | macOS |
| Browser | chrome |

**Comment by Yanyan-Wang** [comment]
@antv/g-svg 是有导出 Canvas 的呀，
https://github.com/antvis/g/blob/e7fc2999e668a024b45a7dc9eefff04bd544775e/packages/g-svg/src/index.ts#L5

你现在是哪个版本的 @antv/g-svg

**Comment by Superzzw1994** [comment]
这是我的依赖， 没有单独安装  @antv/g-svg， G6依赖里面的g-svg是 0.5.6版本的。
  "dependencies": {
    "@antv/g6": "^4.2.7",
    "@emotion/react": "^11.1.5",
    "@emotion/styled": "^11.1.5",
    "lodash-es": "^4.17.21",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "typescript": "^4.2.3"
  },

这是全部的警告信息。


WARNING in ./node_modules/@antv/g6-pc/es/graph/graph.js 73:19-29
export 'Canvas' (imported as 'GSVGCanvas') was not found in '@antv/g-svg' (possible exports: default)
 @ ./node_modules/@antv/g6-pc/es/index.js 3:0-34 25:0-206 28:9-14
 @ ./node_modules/@antv/g6/es/index.js 1:0-29 2:0-10 3:0-28 3:0-28 4:15-17
 @ ./src/components/flow/index.tsx 46:0-26 88:26-34
 @ ./src/index.tsx 46:0-37 84:38-42

WARNING in ./node_modules/@antv/g6-pc/es/graph/graph.js 299:43-53
export 'Canvas' (imported as 'GSVGCanvas') was not found in '@antv/g-svg' (possible exports: default)
 @ ./node_modules/@antv/g6-pc/es/index.js 3:0-34 25:0-206 28:9-14
 @ ./node_modules/@antv/g6/es/index.js 1:0-29 2:0-10 3:0-28 3:0-28 4:15-17
 @ ./src/components/flow/index.tsx 46:0-26 88:26-34
 @ ./src/index.tsx 46:0-37 84:38-42

WARNING in ./node_modules/@antv/g6-pc/es/graph/graph.js 384:43-53
export 'Canvas' (imported as 'GSVGCanvas') was not found in '@antv/g-svg' (possible exports: default)
 @ ./node_modules/@antv/g6-pc/es/index.js 3:0-34 25:0-206 28:9-14
 @ ./node_modules/@antv/g6/es/index.js 1:0-29 2:0-10 3:0-28 3:0-28 4:15-17
 @ ./src/components/flow/index.tsx 46:0-26 88:26-34
 @ ./src/index.tsx 46:0-37 84:38-42

WARNING in ./node_modules/@antv/g6-plugin/es/minimap/index.js 538:19-29
export 'Canvas' (imported as 'GSVGCanvas') was not found in '@antv/g-svg' (possible exports: default)
 @ ./node_modules/@antv/g6-plugin/es/index.js 3:0-32 13:0-129 18:11-18
 @ ./node_modules/@antv/g6-pc/es/plugin/index.js 1:0-37 2:15-21
 @ ./node_modules/@antv/g6-pc/es/index.js 8:0-30 11:14-28 12:11-22 13:15-30 14:11-22 15:14-28 16:14-28 17:14-28 18:14-28 19:19-38 20:21-42 21:15-30 38:11-25 39:8-19 40:12-27 41:8-19 42:11-25 43:11-25
 @ ./node_modules/@antv/g6/es/index.js 1:0-29 2:0-10 3:0-28 3:0-28 4:15-17
 @ ./src/components/flow/index.tsx 46:0-26 88:26-34
 @ ./src/index.tsx 46:0-37 84:38-42

WARNING in ./node_modules/@antv/g6-plugin/es/timeBar/index.js 148:19-29
export 'Canvas' (imported as 'GSVGCanvas') was not found in '@antv/g-svg' (possible exports: default)
 @ ./node_modules/@antv/g6-plugin/es/index.js 8:0-32 13:0-129 23:11-18
 @ ./node_modules/@antv/g6-pc/es/plugin/index.js 1:0-37 2:15-21
 @ ./node_modules/@antv/g6-pc/es/index.js 8:0-30 11:14-28 12:11-22 13:15-30 14:11-22 15:14-28 16:14-28 17:14-28 18:14-28 19:19-38 20:21-42 21:15-30 38:11-25 39:8-19 40:12-27 41:8-19 42:11-25 43:11-25
 @ ./node_modules/@antv/g6/es/index.js 1:0-29 2:0-10 3:0-28 3:0-28 4:15-17
 @ ./src/components/flow/index.tsx 46:0-26 88:26-34
 @ ./src/index.tsx 46:0-37 84:38-42

webpack 5.24.4 compiled with 5 warnings in 16960 ms
ℹ ｢wdm｣: Compiled with warnings.

**Comment by Superzzw1994** [comment]
@Yanyan-Wang

**Comment by Yanyan-Wang** [comment]
可能是 webpack 5 打包的原因，设置 "skipLibCheck": true 可以把这个检查跳过，应该不会影响使用的

**Comment by Superzzw1994** [comment]
好的，谢谢~
