### ISSUE TITLE
destroy、updateLayout对于画布大小的影响

### ISSUE THREAD

**Issue by TF-1992** [antvis/G6#2878]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我初始默认使用的force布局，然后点击按钮切换到dagre布局（一个节点对应上百、千个节点），最后在切换回force布局。切换的同时使用graph.destroy摧毁了画布重新生成或者updateLayout更新布局的的两种方式，但是画布里面的大小还是已dagre为标准的大小，并没改变成force布局实际所需的画布大小。导致切换成force布局时与初始效果差异很大。

### What does the proposed API look like?
有没有重置画布内部大小的api或者有其他实现的方式吗？

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
