### ISSUE TITLE
npm run demos storybook显示空白

### ISSUE THREAD

**Issue by candy-Tong** [antvis/G6#2880]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/antvis/G6](https://github.com/antvis/G6)

### Steps to reproduce
1. git clone https://github.com/antvis/G6
2. npm run bootstrap
3. npm run build:all
4. npm run demos

storybook显示空白
![](https://markdown-1252756644.cos.ap-guangzhou.myqcloud.com/20210507162206.png)

| Environment | Info |
|---|---|
| g6 | 4.2.7 |
| System | win10 |
| Browser | chrome 90.0.4430.85 |

---
node v12.14.1

**Comment by Yanyan-Wang** [comment]
storybook 在 4.x 弃用了。需要测试可以写测试用例，跑命令 DEBUG_MODE=1 npm test -- --watch ./tests/unit/xxx/xxx-spec
