### ISSUE TITLE
node:click equivalent for touch

### ISSUE THREAD

**Issue by 1994benc** [antvis/G6#2881]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Allow users to tap on G6 items (nodes, edge, etc.) on touch devices. 
Currently there is nothing similar to "node:click" event for touch screen, resulting in inability to use G6 fully on touch devices.

### What does the proposed API look like?
An event similar to node:click (i.e. 'node:tap') when users tap a node on a touch screen device

**Comment by Yanyan-Wang** [comment]
Try the following code:

```
    graph.on("node:touchstart", (e) => {
      console.log("touchstart");
    });
```
