### ISSUE TITLE
ModelRect 文本过长，超出节点宽度，如何处理超出显示省略号 ...

### ISSUE THREAD

**Issue by 905868332** [antvis/G6#2882]
ModelRect 文本过长，超出节点宽度，如何处理超出显示省略号 ...

**Comment by Yanyan-Wang** [comment]
https://g6.antv.vision/zh/examples/item/label#labelLen

**Comment by 905868332** [comment]
> https://g6.antv.vision/zh/examples/item/label#labelLen

多谢

**Comment by evanoxu** [comment]
> https://g6.antv.vision/zh/examples/item/label#labelLen

@Yanyan-Wang 这个只能初始化的时候做处理？如果是文本内容动态修改了要怎么处理？
