### ISSUE TITLE
4.2.7版本的树图收缩问题

### ISSUE THREAD

**Issue by weicheng123456** [antvis/G6#2883]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g6.antv.vision/zh/examples/tree/compactBox#tbCompactBox](https://g6.antv.vision/zh/examples/tree/compactBox#tbCompactBox)

### Steps to reproduce
树图：设置linkCenter时折线方向。使用4.0版本后，数据如果多的话树的收缩折叠收缩就很卡。
如果使用。这个版本之前，树的折叠就不会卡。但是 linkCenter时折线方向问题是存在的。

| Environment | Info |
|---|---|
| g6 | 4.2.7 |
| System | - |
| Browser | - |

---
树图：设置linkCenter时折线方向。使用4.0版本后，数据如果多的话树的收缩折叠收缩就很卡。
如果使用。这个版本之前，树的折叠就不会卡。但是 linkCenter时折线方向问题是存在的。

**Comment by Yanyan-Wang** [comment]
因为 A* 巡径算法复杂度比较高，在折叠收缩过程中节点是动画着改变位置的，所以边会被频繁的更新和计算，所以会卡。可以动画开始的时候将所有边隐藏，动画完成后再显示。例如

```
    graph.on('beforeanimate', e => {
      graph.getEdges().forEach(edge => {
        edge.hide()
      })
    })

    graph.on('afteranimate', e => {
      graph.getEdges().forEach(edge => {
        edge.show()
        edge.refresh()
      })
    })

    // ...
```

**Comment by weicheng123456** [comment]
自从更新完 图的linkCenter时折线方向问题后。数据多的话，就会变得很慢很卡。不知道什么原因

**Comment by Yanyan-Wang** [comment]
如上述
> 因为 A* 巡径算法复杂度比较高，在折叠收缩过程中节点是动画着改变位置的，所以边会被频繁的更新和计算，所以会卡
