### ISSUE TITLE
Dagre layout: edges being covered by nodes

### ISSUE THREAD

**Issue by 1994benc** [antvis/G6#2884]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/determined-moser-dz9qe?file=/src/index.js)

### Steps to reproduce
1. create a G6 graph with dagre layout
2. In graph options, set anchorPoints [
      [0.5, 0],
      [0.5, 1]
    ]
3. In graph options, set defaultNode size  [450, 150]
4. register a custom node (see codesandbox link)

Result: Dagre layout is behaving unexpectedly when a parent node is linked to a grand child node; the edge goes behind a child node, making user think that the parent is also connected to the child, which is not true.

For example, in the codesandbox, edge (source = alpa_file1, target = sql_file1) goes behind alps_file2

| Environment | Info |
|---|---|
| g6 | 4.2.7 |
| System | - |
| Browser | - |

**Comment by Yanyan-Wang** [comment]
Try to use the 'polyline' for defaultEdge and set  `controlPoints: true` for dagre. The edge will be routed by dagre algorithm

**Comment by Yanyan-Wang** [comment]
Hi, dear user. Since there was no response for a long time, we cannot figure out the answer of the problem you described. If there is new progress, feel free to open a new issue.
