### ISSUE TITLE
Top is still not accessible with minimap

### ISSUE THREAD

**Issue by ankitachdhr145** [antvis/G6#2885]
Sandbox link: https://codesandbox.io/s/heuristic-shaw-oi7fz?file=/index.js
We are on the top as per "minimap" using the box navigator but if you see in the screenshot we cant still see the top in the real graph.

Steps to replicate: 

1. Zoom in the graph 
2. Use the box navigator in the minimap to navigate to the top

![image](https://user-images.githubusercontent.com/60146248/117851443-a051a880-b286-11eb-922c-6d4a89657b88.png)

**Comment by Yanyan-Wang** [comment]
See the scroll bar on the right of your page, the canvas is too large, so the page is scrolled down

**Comment by ankitachdhr145** [comment]
We don't have scroller in our project. So without scroller user cant navigate to the top using "minimap". There is no other way to access the top with minimap without scroller/mousewheel scroll for this case?

**Comment by ankitachdhr145** [comment]
Even if you scroll up then also some part of the graph is truncated in the top which you can only access with mouse scroll.
![image](https://user-images.githubusercontent.com/60146248/117941426-5b6f5580-b30a-11eb-9519-947d2def63b0.png)

**Comment by ankitachdhr145** [comment]
Hi Team,

Is there any update on this issue?

**Comment by Yanyan-Wang** [comment]
Sorry, I miss this issue. Will be fixed by 4.3.5

**Comment by Yanyan-Wang** [comment]
related to https://github.com/antvis/G6/pull/3009/commits/22c5e87112a58930321840fbc887abb02554f9f1

**Comment by ankitachdhr145** [comment]
Thanks Yanyan we will wait for the update
