### ISSUE TITLE
layout 为dagre节点为100多个的时候页面卡顿

### ISSUE THREAD

**Issue by tianxiumei** [antvis/G6#2886]
https://codesandbox.io/s/beautiful-mountain-58hz8?file=/index.js

**Comment by Yanyan-Wang** [comment]
renderer: 'svg' 代表用的 svg 渲染，svg 的性能差，建议用 canvas。改成 canvas 之后会快非常多。我看你这个 demo 节点也不复杂，canvas 完全可以做的。

数据量比较大的情况下，建议尽量避免全局的重新渲染。比如 activate-relations， drag-canvas, zoom-canvas。后两者可以配置 enableOptimize: true 开启优化，在更新过程中隐藏非节点 keyShape 以外的节点，结束之后再显示

**Comment by tianxiumei** [comment]
renderer: 'svg'  是因为我想要标签可以旋转，我没有看到canvas可以实现这个功能

**Comment by tianxiumei** [comment]
感觉 fitView 情况下这个节点太多还是会超出是吗

**Comment by Yanyan-Wang** [comment]
> renderer: 'svg' 是因为我想要标签可以旋转，我没有看到canvas可以实现这个功能

可以的

> 感觉 fitView 情况下这个节点太多还是会超出是吗

设置 graph 的 minZoom 小一些，比如 0.000001
