### ISSUE TITLE
树图数据多时页面卡死

### ISSUE THREAD

**Issue by weicheng123456** [antvis/G6#2887]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cold-breeze-ve0df?file=/index.js)

### Steps to reproduce
树图数据多时页面卡死

| Environment | Info |
|---|---|
| g6 | 4.2.7 |
| System | - |
| Browser | - |

**Comment by Yanyan-Wang** [comment]
polyline 自动巡径算法复杂度很高，大规模图建议用其他类型的边，最简单的是 line。你的这个 demo 换成 line 之后就能出来。要用 polyline 的话可以简单自定义而不用内置自动寻径算法的 polyline，例如 https://g6.antv.vision/zh/examples/item/customEdge#customPolyline

**Comment by weicheng123456** [comment]
我是自定义节点，但是现在数据庞大。总节点数可能达到一万左右，边数量更是有可能上十万条，line 也是一样的卡啊。怎么

**Comment by weicheng123456** [comment]
> polyline自动巡线算法复杂度很高，大规模图建议用其他类型的边，最简单的是line。你的这个演示换成line之后就会出来。要用polyline的话可以简单自定义而不用内置自动寻径算法的折线，例如https://g6.antv.vision/zh/examples/item/customEdge#customPolyline

drag  和  zoom 时候卡顿怎么解决啊？

**Comment by Yanyan-Wang** [comment]
drag 和 zoom 可以开启优化，在拖拽过程中隐藏非节点 keyShape 的图形，zoom-canvas 和 drag-canvas 的 enableOptimize

https://g6.antv.vision/zh/docs/manual/middle/states/defaultBehavior#zoom-canvas
https://g6.antv.vision/zh/docs/manual/middle/states/defaultBehavior#drag-canvas

**Comment by weicheng123456** [comment]
> drag 和 zoom 可以开启优化，在拖拽过程中隐藏非节点 keyShape 的图形，zoom-canvas 和 drag-canvas 的 enableOptimize
> 
> https://g6.antv.vision/zh/docs/manual/middle/states/defaultBehavior#zoom-canvas
> https://g6.antv.vision/zh/docs/manual/middle/states/defaultBehavior#drag-canvas
开启的，Update更新函数也重写了的。但在拖拽好缩放的时候依旧很卡。目前节点(自定义的)大约3000，

**Comment by Yanyan-Wang** [comment]
在比较大规模的情况下，就建议尽量用简单的图形来表达节点和边，节点上的图形数量越少越好。在详细视图的时候再展示节点的详细内容。

数据量达到成千上万的时候，用户看和分析这个可视化也是很困难的，建议做更多的筛选过滤和方案上的优化。

目前我们也在计划 webgl 渲染引擎，后续会做更多性能上的提升。

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
