### ISSUE TITLE
addItem方法针对包含comboId的节点，在添加当前节点到comboTrees是clone未添加depth属性的model副本，导致sortCombos方法中 构建depthMap数组出现错误

### ISSUE THREAD

**Issue by weiliang0121** [antvis/G6#2888]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cranky-voice-9do7h?file=/src/index.js)

### Steps to reproduce
见链接

| Environment | Info |
|---|---|
| g6 | 4.2.7 |
| System | Mac 11.1 |
| Browser | chrome 90 |

---
需要在动态添加节点的过程中，节点不会被combo遮挡

**Comment by Yanyan-Wang** [comment]
感谢报告，下个版本会修复。感觉这么仔细看了源码都可以提 pr 了哈哈～
