### ISSUE TITLE
在gForce布局拖动点不能更新点坐标，在force布局中可以

### ISSUE THREAD

**Issue by javaNaruto** [antvis/G6#2889]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gforce-mwneu?file=/index.js)

### Steps to reproduce
type为gForce情况拖动节点，更新节点坐标不生效，而type为force的情况下可以（在sandbox中修改type进行对比）

| Environment | Info |
|---|---|
| g6 | 4.2.7 |
| System | - |
| Browser | - |

**Comment by javaNaruto** [comment]
gForce拖动节点会抖动不能控制

**Comment by Yanyan-Wang** [comment]
你是说拖拽节点吗？我这里试着在你的 demo 中拖拽节点，好像是正常的呢

**Comment by javaNaruto** [comment]
> 你是说拖拽节点吗？我这里试着在你的 demo 中拖拽节点，好像是正常的呢

布局稳定后，拖拽节点到其他位置，我期望他能停在那个位置，但是节点弹回去了，我在node:drag事件里更新了节点的位置，实际效果并不是如此。反而当type为force的时候却可以

**Comment by Yanyan-Wang** [comment]
那你希望拖拽一个节点的时候，其他节点跟着调整位置吗？

**Comment by javaNaruto** [comment]
是的

**Comment by javaNaruto** [comment]
期望是拖拽节点，更新节点位置的效果和force拖拽节点一样

**Comment by javaNaruto** [comment]
期望是拖拽节点的效果和force一样

**Comment by Yanyan-Wang** [comment]
gforce 目前没有提供 force 这类 fx fy 固定坐标的方法，每次拖拽的时候被拖拽的节点还是会被布局算法计算位置，所以会和用户拖拽的位置冲突

**Comment by javaNaruto** [comment]
请问这个后续能支持吗

**Comment by Yanyan-Wang** [comment]
会考虑的，不过暂时还没有排期
