### ISSUE TITLE
TreeGraph图 layout类型 为 indented 时，该如何设置节点间距？

### ISSUE THREAD

**Issue by evanoxu** [antvis/G6#2890]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/antvis/G6](https://github.com/antvis/G6)

### Steps to reproduce
问题图：
![image](https://user-images.githubusercontent.com/3927965/118229666-fa3cb300-b4be-11eb-80fd-15c67046d8f4.png)

1. TreeGraph 中 layout 设置如下：
```
layout: {
          type: 'indented', // 布局类型
          direction: 'LR',    // 自左至右布局，可选的有 H / LR / RL
          dropCap: false,
          indent: 300,
}
```
2. 图中节点为自定义节点

3. 图中箭头位置可视：节点重叠了。
4. 我现在该如何设置 节点的间距？

| Environment | Info |
|---|---|
| g6 | 4.2.7 |
| System | - |
| Browser | - |

**Comment by Yanyan-Wang** [comment]
https://g6.antv.vision/zh/docs/api/treeGraphLayout/indented

配置 getHeight 函数返回节点高度

**Comment by evanoxu** [comment]
> https://g6.antv.vision/zh/docs/api/treeGraphLayout/indented
> 
> 配置 getHeight 函数返回节点高度

@Yanyan-Wang 这边的内容是动态展示的，如果设置了节点高度就定死了。

**Comment by Yanyan-Wang** [comment]
可以把动态的高度写到节点数据里面，比如挂在 node.size, 然后 getHeight 里面 return node.size[1] ，节点高度有更新的时候重新调用一下 graph.layout() 应该就可以

**Comment by evanoxu** [comment]
> 可以把动态的高度写到节点数据里面，比如挂在 node.size, 然后 getHeight 里面 return node.size[1] ，节点高度有更新的时候重新调用一下 graph.layout() 应该就可以

嗯，大概明白了。
谢谢。
