### ISSUE TITLE
注册节点时指定fillOpacity, setItemState未生效

### ISSUE THREAD

**Issue by li379395535** [antvis/G6#2892]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qhzjy?file=/index.js:4170-4210)

### Steps to reproduce
注册节点时指定fillOpacity, 后续setItemState都无法改变node的opacity和fillOpacity

| Environment | Info |
|---|---|
| g6 | 4.2.7 |
| System | - |
| Browser | - |

---
期望的结果：希望节点初始状态下是有一定透明度的

**Comment by mxz96102** [comment]
这个demo期望的效果是什么样呢，现在感觉这个交互看起来没有问题

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
