### ISSUE TITLE
在 dagre 中使用自定义节点的 combo 布局位置无法调整

### ISSUE THREAD

**Issue by furylee** [antvis/G6#2893]
### Implementation
在 dagre 中使用自定义节点的 combo,布局为什么这么怪异,无论多少节点,都只能竖着,有没有办法横着?看了示例实在是没看到怎么调整的,只好来这里提问了

https://codesandbox.io/s/competent-elgamal-q9vhv

**Comment by Yanyan-Wang** [comment]
不是很明白，你期待的是 combo 内部节点横着吗？因为节点属于哪一列取决于节点直接的邻接关系，目前这个例子中，combo 内部的节点都没有边所以被作为第一列的节点。也可以通过增加透明的边来改变这个布局

**Comment by furylee** [comment]
> 不是很明白，你期待的是 combo 内部节点横着吗？因为节点属于哪一列取决于节点直接的邻接关系，目前这个例子中，combo 内部的节点都没有边所以被作为第一列的节点。也可以通过增加透明的边来改变这个布局

我不知道是否可以这么用,就是一个combo就是一个节点,里面的子节点都不会有邻接关系,如果不可以这么用,我想知道这个透明的边是指的内部节点有邻接关系,只不过边是透明的是吧?

**Comment by furylee** [comment]
> 不是很明白，你期待的是 combo 内部节点横着吗？因为节点属于哪一列取决于节点直接的邻接关系，目前这个例子中，combo 内部的节点都没有边所以被作为第一列的节点。也可以通过增加透明的边来改变这个布局

大佬有什么解答方案吗,在这里卡住好久了

**Comment by Yanyan-Wang** [comment]
> > 不是很明白，你期待的是 combo 内部节点横着吗？因为节点属于哪一列取决于节点直接的邻接关系，目前这个例子中，combo 内部的节点都没有边所以被作为第一列的节点。也可以通过增加透明的边来改变这个布局
> 
> 我不知道是否可以这么用,就是一个combo就是一个节点,combo里面的子节点都不会有邻接关系,如果不可以这么用,我想知道这个透明的边是指的内部节点有邻接关系,只不过边是透明的是吧?

是的，现在 combo + dagre 也在优化过程中，将来会支持你说的这种需求。目前是需要内部节点有邻接关系但把这些边设置为透明的

**Comment by furylee** [comment]
@Yanyan-Wang 
`
const getTemplate = (cfg) => {
      const children = `
      <div class="line" title="${cfg.bizData.invocationType}">${cfg.bizData.invocationType}</div>
      <div class="line" title="${cfg.bizData.identity}">${cfg.bizData.identity}</div>
      <div style="display: flex;align-items: center"><input type="checkbox">mock</input><input style="width: 100px"/></div>
      <div class="line btn" onclick="console.log(event.target)">详细信息</div>
      `
      
      return `
          <div class="gbox" style="height: 198px;border:1px solid #2196f3;border-radius:5px;">
              <div class="t-box">${cfg.id}</div>
              <div class="b-box">
                ${children}
              </div>
            </div>`
    }
`
没办发绑定外部方法吗?

**Comment by Yanyan-Wang** [comment]
你是说绑定监听吗，参考这个例子：https://g6.antv.vision/zh/examples/item/customNode#svgDom

如果考虑渲染性能的问题，建议还是用 canvas

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
