### ISSUE TITLE
请问registerLayout中layout函数的用法

### ISSUE THREAD

**Issue by Superzzw1994** [antvis/G6#2894]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
请问registerLayout中的layout()什么情况下会执行？ graph.layout()执行的是init和excute

### What does the proposed API look like?
谢谢。

**Comment by Yanyan-Wang** [comment]
内置的布局 layout 方法也是调用的 init 和 execute，目的是在单独使用布局的时候可以直接调用 layout 来代替调用 init 和 execute，比如

const force = new G6.Layout({ type: 'force' })
force.layout(data); // = force.init(data); force.execute()

自定义布局的 layout 是否要实现根据自己需要，并不是必须的

**Comment by Superzzw1994** [comment]
![Lark20210518-095628](https://user-images.githubusercontent.com/20533727/118578833-784ed180-b7bf-11eb-848c-042b1fedc114.png)
![Lark20210518-095611](https://user-images.githubusercontent.com/20533727/118578832-784ed180-b7bf-11eb-9a27-7f2a66244840.png)
请问下，这两种是不是不需要自定义布局啊，自己算下坐标就可以吧？
还有  自定义布局里面的init钩子 里面可以对数据进行操作吗？ excute钩子里面 好像不可以 this.nodes = 新的nodes这种操作,只可以 遍历nodes直接修改node的属性？
谢谢！
@Yanyan-Wang

**Comment by Yanyan-Wang** [comment]
如果是静态的数据，可以直接计算好 x y 放入数据即可。实际上，布局也就是在计算 x y 然后写入数据，本质上是一样的。

this.nodes 应该是可以的吧，不确定你说的是哪种情况，可以写在线 demo 看下

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
