### ISSUE TITLE
有办法实时获取获取到边长度吗

### ISSUE THREAD

**Issue by hxj123** [antvis/G6#2895]
有一个需求，边上要显示label，label超出要加省略号，边的长度不固定，随着边的变长变短，label要自动变长变短，超出保持省略号，这个需求目前有办法做吗

**Comment by Yanyan-Wang** [comment]
可以拿到两个端点的坐标计算欧几里得距离呀。

const { x: srcX, y: srcY } = edge.getSource().getModel()
const { x: tgtX, y: tgtY } = edge.getTarget().getModel()
……

**Comment by hxj123** [comment]
> 可以拿到两个端点的坐标计算欧几里得距离呀。
> 
> const { x: srcX, y: srcY } = edge.getSource().getModel()
> const { x: tgtX, y: tgtY } = edge.getTarget().getModel()
> ……

感谢回答，目前是没办法监听边的长度变化对吧，那这个需求做起来很麻烦，得监听节点拖动事件，在获取连接节点的边，实时计算边的长度

**Comment by Yanyan-Wang** [comment]
原始需求是什么

**Comment by javaNaruto** [comment]
> 原始需求是什么

拖拽节点的同时监听到边的长度变化，边上文本较长的时候可以根据边长度来展示文本内容

**Comment by Yanyan-Wang** [comment]
那应该就是监听 node:drag 事件，拿到相关的边，计算 label 长度和当前边长度，进行文本的截取

graph.on('node:drag', e => {
   const node = e.item
   const relatedEdges = node.getEdges();
   // ... 遍历 relatedEdges 的边，edge.source() edge.target() 拿到两端节点，计算当前距离，再根据距离和 label 长度更新边的 label
});

**Comment by Yanyan-Wang** [comment]
也许以后可以把这个作为一个配置项放到 drag-node 内置 behavior 中

**Comment by javaNaruto** [comment]
> 那应该就是监听 node:drag 事件，拿到相关的边，计算 label 长度和当前边长度，进行文本的截取
> 
> graph.on('node:drag', e => {
> const node = e.item
> const relatedEdges = node.getEdges();
> // ... 遍历 relatedEdges 的边，edge.source() edge.target() 拿到两端节点，计算当前距离，再根据距离和 label 长度更新边的 label
> });

是的，目前我们就是这么处理的

**Comment by javaNaruto** [comment]
> 也许以后可以把这个作为一个配置项放到 drag-node 内置 behavior 中

这个配置非常友好
