### ISSUE TITLE
边动画效果

### ISSUE THREAD

**Issue by DankeF** [antvis/G6#2896]
G6 边的动画效果是否可以设置成这种效果。
如果可以，我没在文档中找到相应的设置，我设置出来的动画都是需要等待一遍的动画结束后才进行下一次的动画。
如果现在不支持这种效果，能否在下个版本中支持？非常感谢！！！

ps：不好意思上传不了效果动图，效果是，边上有圆点沿着边运动，是不分开始和结束的。无限循环。而不是需要等待一遍的动画结束后才进行下一次的动画。

**Comment by DankeF** [comment]
![截图](https://user-images.githubusercontent.com/29647627/118576471-2d32bf80-b7bb-11eb-9990-298acac8982f.PNG)

**Comment by Yanyan-Wang** [comment]
你说的应该就是类似这个效果：

https://g6.antv.vision/zh/examples/case/newsDemo#metroLines

**Comment by DankeF** [comment]
> 你说的应该就是类似这个效果：
> 
> https://g6.antv.vision/zh/examples/case/newsDemo#metroLines

对对对，差不多，我需要的就是匀速无限循环就好，我看看实例代码，谢谢啦！！！

**Comment by Yanyan-Wang** [comment]
不用谢，那就先关闭 issue 了，有问题再随时开

**Comment by chaoji90** [comment]
[https://codesandbox.io/p/sandbox/charming-leaf-kpm55u](url)
请问为什么现在无法运行了，是因为版本问题么？
