### ISSUE TITLE
vite项目引入g6报错了

### ISSUE THREAD

**Issue by taolei1990** [antvis/G6#2897]

**Comment by songhn233** [comment]
请提供更具体的信息

测试在 vite vanilla 预设下正常 dev & build

**Comment by taolei1990** [comment]
来自 魅族 16s







重庆中联信息产业有限责任公司&nbsp;

中联区卫事业部&nbsp; -- 陶磊

Tel: 17623565180 &nbsp;&nbsp;

QQ: 751821617








&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/G6"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月19日(星期三) 凌晨1:15
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [antvis/G6] vite项目引入g6报错了 (#2897)





 
请提供更具体的信息
 
测试在 vite vanilla 预设下正常 dev &amp; build

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。

**Comment by taolei1990** [comment]
谢谢 已经解决了 是vue3 的生命周期稍微有点变化 在合适生命周期创建图表就没问题&nbsp;



来自 魅族 16s







重庆中联信息产业有限责任公司&nbsp;

中联区卫事业部&nbsp; -- 陶磊

Tel: 17623565180 &nbsp;&nbsp;

QQ: 751821617








&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yanyan ***@***.***&gt;; 
发送时间: 2021年5月31日(星期一) 上午10:53
收件人: ***@***.***&gt;; 
抄送: " ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [antvis/G6] vite项目引入g6报错了 (#2897)





 
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
