### ISSUE TITLE
[Timebar模块]设置柱子宽度linewidth显示有问题 

### ISSUE THREAD

**Issue by iamsuyi** [antvis/G6#2898]
demo:
https://codesandbox.io/s/romantic-jackson-zeh1n?file=/index.js
![image](https://user-images.githubusercontent.com/5397248/118789941-dd8dea00-b8c7-11eb-95d8-7cdb21c19735.png)
设置为10，不仅宽度变为10，x轴那边高度也变成10了。
希望只改成柱子宽度，有什么解决方法吗？谢谢。

**Comment by Yanyan-Wang** [comment]
fixed by v4.3.2. lineWidth 指描边粗细，因为这里的 bar chart 柱子整个是一个 path，所以改变 lineWidth 会改变所有的描边粗细。v4.3.2 为 interval.style 加入了 barWidth 属性，用以指定柱子的粗细。
