### ISSUE TITLE
Dagre + Combo 如何实现类似同级非关联上下分布, 有关联的链式

### ISSUE THREAD

**Issue by L924553229** [antvis/G6#2899]
**G6 Version**: 4.2.6
**Mini Showcase(like screenshots)**: 
**CodePen Link**: https://g6.antv.vision/zh/examples/net/dagreFlow#lrDagreUL

**Comment by Yanyan-Wang** [comment]
这个吗？https://g6.antv.vision/zh/examples/net/dagreFlow#dagreCombo

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
