### ISSUE TITLE
如何添加节点内局部自定义事件

### ISSUE THREAD

**Issue by meikidd** [antvis/g6#29]
非常喜欢 G6 ，给项目组点赞。

我想要捕获节点的局部点击事件，请问一下如何实现呢？我们要实现一个自定义节点，捕获类似 tree 节点右侧的 "+" 号的点击事件。目前从文档和示例来看，只能获取到 node 和 edge 这个级别的事件。

**Comment by TomHuangCN** [comment]
ev.shape 是拾取的具体图形。

**Comment by meikidd** [comment]
thx
