### ISSUE TITLE
在树图布局下 拖拽某一节点  怎样使其子节点也跟随移动？

### ISSUE THREAD

**Issue by babyyage** [antvis/G6#2900]

**Comment by Yanyan-Wang** [comment]
需要监听 node:drag，然后拿到被拖拽节点的数据，根据移动的差量遍历子树更新每个字节点的位置。

这儿有个例子是拖拽子树改变树结构，和上述原理不同，不是直接改变子树节点坐标的。拖拽过程中是用的 delegate。也许也可以参考一下：https://g6.antv.vision/zh/examples/interaction/treeBehavior#dragSubtree

**Comment by babyyage** [comment]
好的 谢谢  我尝试一下  @Yanyan-Wang

**Comment by babyyage** [comment]
> 需要监听 node:drag，然后拿到被拖拽节点的数据，根据移动的差量遍历子树更新每个字节点的位置。
> 
> 这儿有个例子是拖拽子树改变树结构，和上述原理不同，不是直接改变子树节点坐标的。拖拽过程中是用的 delegate。也许也可以参考一下：https://g6.antv.vision/zh/examples/interaction/treeBehavior#dragSubtree

你好 以后的版本可以把 这条issue看作需求 加进去吗？  我监听了node:drag ， 监听某一节点的drag 可以通过其坐标 更改其子节点的坐标  但是每拖动一下父节点（子节点数量不确定）就会遍历字节点list修改其坐标    这样会导致卡顿   而且页面还会有阴影   目前没找到合适的方案

**Comment by Yanyan-Wang** [comment]
写了一个 demo，可以满足需求： https://codesandbox.io/s/wonderful-moore-65ytjv?file=/index.js
