### ISSUE TITLE
fitView没有用

### ISSUE THREAD

**Issue by eynait1010** [antvis/G6#2901]
项目是react + ts 
当使用Minimap布局的时候，按照官网的例子写，fitView没有用。
当不掉用fitView时：
![image](https://user-images.githubusercontent.com/50448236/118816028-6155cf80-b8e4-11eb-96a3-b4ccfb422db1.png)
当调用fitfitView时：
![image](https://user-images.githubusercontent.com/50448236/118816213-86e2d900-b8e4-11eb-865f-06ff93681fd9.png)
什么都没有渲染出来 我的代码是根据这个写的
https://g6.antv.vision/zh/examples/tree/mindmap#hRightMindmap

**Comment by eynait1010** [comment]
[index2.tsx.zip](https://github.com/antvis/G6/files/6508869/index2.tsx.zip)
这是我的代码

**Comment by songhn233** [comment]
fitView 应该依赖于图配置中的 width 和 height 值，所以在初始化时需要指定，比如

```js
graph = new G6.TreeGraph({
  container: ref.current,
  fitView: true,
  width: 800,
  height: 600,
}
```

**Comment by eynait1010** [comment]
如果图配置没有制定 width 和 height， fitView就不生效
我没有设置宽高是因为想让他继承容器https://github.com/antvis/G6/issues/2780

**Comment by songhn233** [comment]
> 如果图配置没有制定 width 和 height， fitView就不生效
> 我没有设置宽高是因为想让他继承容器#2780

这应该是 [initCanvas](https://github.com/antvis/G6/blob/master/packages/pc/src/graph/graph.ts#L61) 中获取到容器大小进行初始化，但并没有设置图配置中的 width 与 height，所以 fitView 获取不到。

后续应该会修复这个问题，现在你想要继承容器可以像 #2780  一样初始化时设置 width 为 clientWidth，height 同理。

**Comment by Yanyan-Wang** [comment]
fixed by v4.3.2
