### ISSUE TITLE
gForce布局使用和未使用GPU的布局效果能否一致？

### ISSUE THREAD

**Issue by javaNaruto** [antvis/G6#2902]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gpu-mwneu?file=/index.js)

### Steps to reproduce
gForce布局在启用和未启用GPU的布局效果不一致，且在启用GPU时，布局效果不好，有节点重叠问题及部分点拉扯的很远

| Environment | Info |
|---|---|
| g6 | 4.3.0 |
| System | - |
| Browser | - |

**Comment by L924553229** [comment]
或者如何让 Combo 支持 xy 坐标

**Comment by javaNaruto** [comment]
怎样保证GPU开启时，gForce布局效果最优？目前看来设置的参数在GPU开启情况下感觉没生效

**Comment by Yanyan-Wang** [comment]
gpu 下 preventOverlap 暂不支持。gravity 没生效是个 bug，下个小版本会修复

**Comment by javaNaruto** [comment]
开启GPU的布局在计算完成之后能达到不开启GPU时布局稳定后的样子吗？

**Comment by Yanyan-Wang** [comment]
除了 preventOverlap 之外，修复之后应该会是一样的

**Comment by javaNaruto** [comment]
好的，后续我会跟进这个issue

**Comment by Yanyan-Wang** [comment]
GPU 版本缺失 Gravity 等参数 fixed by 4.3.2. 同时支持了 gForce 和 fruchterman 布局固定节点位置（通过在节点数据中写入 fx 和 fy）

**Comment by javaNaruto** [comment]
下个小版本本周能发吗？

**Comment by javaNaruto** [comment]
> GPU 版本缺失 Gravity 等参数 fixed by 4.3.2. 同时支持了 gForce 和 fruchterman 布局固定节点位置（通过在节点数据中写入 fx 和 fy）

gpu开启后，绘图效果依旧和未开启不一致

**Comment by javaNaruto** [comment]
> GPU 版本缺失 Gravity 等参数 fixed by 4.3.2. 同时支持了 gForce 和 fruchterman 布局固定节点位置（通过在节点数据中写入 fx 和 fy）

4.3.2，gpu开启后，绘图效果依旧和未开启不一致

**Comment by javaNaruto** [comment]
特别是节点数少的情况

**Comment by Yanyan-Wang** [comment]
就你 demo 中这个例子来看，应该是一样的了，只不过没开启 GPU 的版本是迭代完成之后 fitView，所以一开始的动画过程中整个图看起来比较大。完成之后结果一样的呀

**Comment by javaNaruto** [comment]
![image](https://user-images.githubusercontent.com/48909573/119772899-763cef00-bef2-11eb-9fdd-758663a696de.png)
外围是差不多了，中间还是有很多节点叠在一起，我预期的结果是至少点不会在一个位置重叠多个，且这里七十多个节点就有十多个节点重叠，数据量大了后，重叠现象更严重

**Comment by Yanyan-Wang** [comment]
是你上面那个链接吗？我点进去看的结果和你的截图不一样

**Comment by javaNaruto** [comment]
你刷新几次看看，或者你看到的截图一下，我这边再给你写个demo

**Comment by javaNaruto** [comment]
https://codesandbox.io/s/demo-8fjnd?file=/index.js
类似于这样的效果，我这边的数据大部分会有一个中心节点周围连了一圈的节点

**Comment by javaNaruto** [comment]
这样沟通起来有点麻烦，能添加您的联系方式吗，

**Comment by Yanyan-Wang** [comment]
刷新了几次看到的都是这样的结果

![image](https://user-images.githubusercontent.com/29593318/119778191-c9667000-bef9-11eb-9ce9-e7dc446ffa41.png)

> https://codesandbox.io/s/demo-8fjnd?file=/index.js
这个链接中的 GPU 结果是：
![image](https://user-images.githubusercontent.com/29593318/119778294-eac75c00-bef9-11eb-9452-f829daa481f5.png)

**Comment by javaNaruto** [comment]
不好意思，定位到了是我本地node_modules的包的问题，我在同事电脑上试了没问题，感谢您的耐心解答

**Comment by JiangGeGe123** [comment]
我这边也有一样的现象，在2000个节点左右，布局时间陡降，中心很多节点挤在一起没有分散开
