### ISSUE TITLE
【报错】vue3 - import { __spreadArray } from "tslib"

### ISSUE THREAD

**Issue by huoyuhao** [antvis/G6#2904]
vue3安装"@antv/g6": "^4.3.0"然后报错如下：

 > node_modules/@antv/algorithm/es/dijkstra.js:1:9: error: No matching export for import "__spreadArray"
    1 │ import { __spreadArray } from "tslib";

**Comment by songhn233** [comment]
删除 `node_modules` 和 `.lock` 文件重新安装依赖，并单独安装最新的 tslib 呢？

**Comment by Imanpc** [comment]
@antv/g6@3.x 升级到@antv/g6@4.3.0 遇到了同样编译问题，记录解决方案：
1、npm cache clean --force
2、删除 node_modules 和  package-lock.json 文件
3、重新安装依赖。

**Comment by Yanyan-Wang** [comment]
应该是 typescript 版本问题，你的版本可能不认识 `...` 这个符号，升级 typescript 到 4.2.2 看看

**Comment by huoyuhao** [comment]
> 删除 `node_modules` 和 `.lock` 文件重新安装依赖，并单独安装最新的 tslib 呢？

非常感谢，确实是tslib版本过低（1.14.1），导致tslib文件中为import { __spreadArrays } from "tslib"
安装最新版本，已经解决该问题。
非常感谢

**Comment by huoyuhao** [comment]
> @antv/g6@3.x 升级到@antv/g6@4.3.0 遇到了同样编译问题，记录解决方案：
> 1、npm cache clean --force
> 2、删除 node_modules 和 package-lock.json 文件
> 3、重新安装依赖。

不知道为什么重新操作没有安装符合版本的tslib，导致仍然报错。
