### ISSUE TITLE
Request to remove Index signatures from typescript definitions

### ISSUE THREAD

**Issue by jfstephe** [antvis/G6#2905]
- [ x ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
It's not possible to implement many of the common interfaces (NodeConfig, ModelConfig etc) without implementing an Index Signature.([key: string]: unknown;)
This seems unnecessary, unintuitive and prevents strong typing of the classes.

The aim is to create a MyNodeConfig class that extends the functionality of NodeConfig (for example), adding custom properties and the like.

### What does the proposed API look like?
Just remove the following from the TS type definitions :-)

```
([key: string]: unknown;
```

If you agree to this I'm happy to provide a PR.

**Comment by Yanyan-Wang** [comment]
Thanks! We are looking forward the pull requests from communities.

Since NodeConfig is the TS type of the node data, we leave `[key: string]: unknown` for free node configurations so that the users have no need to extend the type for their data. Maybe the users would like to extend the type to achieve the goal?

**Comment by jfstephe** [comment]
Absolutely! Although including this would mean that it would potentially break a lot projected (and some rightly so as it would highlight errors).

If you are ok with this I'll look into creating the PR.

**Comment by Yanyan-Wang** [comment]
It brings breaking changes, we should consider to put it into a big version upgrading.

**Comment by dagadbm** [comment]
could you explain how I could create my own type ?
