### ISSUE TITLE
Cannot read property 'setAutoPaint' of undefined

### ISSUE THREAD

**Issue by 905868332** [antvis/G6#2906]
Cannot read property 'setAutoPaint' of undefined

**Comment by Yanyan-Wang** [comment]
What's meaning?

**Comment by 905868332** [comment]
> What's meaning?

在 vue 中使用 G6

**Comment by 905868332** [comment]
> What's meaning?

在 vue 中使用 G6
this.graph = new G6.Graph({})
this.graph .setAutoPaint(false)  --   报错  setAutoPaint undefined
this.graph.getNodes() --  报错 getNodes undefined
-----
如果直接声明变量如：
const graph = new G6.Graph({})
graph .setAutoPaint(false) -- 正常
graph.getNodes() -- 正常

**Comment by Yanyan-Wang** [comment]
提供一下在线复现 demo 呢

**Comment by 905868332** [comment]
> 提供一下在线复现 demo 呢

鼠标移入事件的一个功能
`this.graph = new G6.Graph({
      container: 'container',
      width,
      height: this.graphHeight,
      // fitView: true,
      fitCenter: true,
      layout: {
        preventOverlap: true,
        type: 'bigraph-layout',
        biSep: 500,
        nodeSep: 50
      },
      animate: true,
      defaultNode: {
        type: 'modelRect',
        size: [200, 60],
        style: {
          radius: 5,
          stroke: '#69c0ff',
          fill: '#ffffff',
          lineWidth: 1,
          fillOpacity: 1
        },
        // label configurations
        labelCfg: {
          style: {
            fill: '#595959',
            fontSize: 14
          },
          offset: 20
        },
        // left rect
        preRect: {
          show: true,
          width: 4,
          fill: '#40a9ff',
          radius: 2
        },
        // configurations for the four linkpoints
        linkPoints: {
          top: false,
          right: false,
          bottom: false,
          left: false,
          // the size of the linkpoints' circle
          size: 10,
          lineWidth: 1,
          fill: '#72CC4A',
          stroke: '#72CC4A'
        },
        logoIcon: {
          show: false
        },
        stateIcon: {
          show: false
        }
      },
      defaultEdge: {
        size: 1,
        color: '#e2e2e2'
      },
      modes: {
        default: [
          'drag-canvas'
        ]
      },
      nodeStateStyles: {
        highlight: {
          lineWidth: 2,
          stroke: '#1890ff',
          fill: '#e6f7ff'

        },
        dark: {
        }
      },
      edgeStateStyles: {
        highlight: {
          stroke: '#1890ff'
        }
      }
    })
    const graph = this.graph
    this.graph.data(this.data)
    this.graph.on('node:mouseenter', function(e) {
      const item = e.item
      this.graph.setAutoPaint(false)
      this.graph.getNodes().forEach(function(node) {
        this.graph.clearItemStates(node)
        this.graph.setItemState(node, 'dark', true)
      })
      this.graph.setItemState(item, 'dark', false)
      this.graph.setItemState(item, 'highlight', true)
      this.graph.getEdges().forEach(function(edge) {
        if (edge.getSource() === item) {
          this.graph.setItemState(edge.getTarget(), 'dark', false)
          this.graph.setItemState(edge.getTarget(), 'highlight', true)
          this.graph.setItemState(edge, 'highlight', true)
          edge.toFront()
        } else if (edge.getTarget() === item) {
          this.graph.setItemState(edge.getSource(), 'dark', false)
          this.graph.setItemState(edge.getSource(), 'highlight', true)
          this.graph.setItemState(edge, 'highlight', true)
          edge.toFront()
        } else {
          this.graph.setItemState(edge, 'highlight', false)
        }
      })
      this.graph.paint()
      this.graph.setAutoPaint(true)
    })`
![微信截图_20210521091359](https://user-images.githubusercontent.com/29794128/119067537-ef30d800-ba14-11eb-9fc6-b20e48998faf.png)

**Comment by Yanyan-Wang** [comment]
在监听里面用你上面定义的 graph 而不是 this.graph，this 的指向不一样了

**Comment by 905868332** [comment]
> 在监听里面用你上面定义的 graph 而不是 this.graph，this 的指向不一样了

懵了 哈哈哈哈哈 多谢
