### ISSUE TITLE
TreeGraph 节点通过data设置隐藏后，能不能不占画布位置呀？

### ISSUE THREAD

**Issue by evanoxu** [antvis/G6#2907]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/awesome-roentgen-5kk2w?file=/src/index.js)

### Steps to reproduce
通过data设置显隐参数(isInit) 后，initScene 节点能隐藏，但是会在画布中占位。如图。
<img width="696" alt="0D490D69-09AF-4A5C-97C0-A6982FE1CEDA" src="https://user-images.githubusercontent.com/3927965/118954232-2610da80-b990-11eb-8667-7ed2edab4dc1.png">
有什么方式可以 即 能 隐藏节点 又 不会占位 呢？

| Environment | Info |
|---|---|
| g6 | 4.2.7 |
| System | Mac |
| Browser | Chrome |

**Comment by Yanyan-Wang** [comment]
可以更新数据，https://g6.antv.vision/zh/docs/api/treeMethods#updatechildrendata-parentid

**Comment by evanoxu** [comment]
> 可以更新数据，https://g6.antv.vision/zh/docs/api/treeMethods#updatechildrendata-parentid

没明白。。。怎么用呀？是隐藏完，又把整个数据update一下吗？

**Comment by Yanyan-Wang** [comment]
updateChildren 用法 demo：https://g6.antv.vision/zh/examples/interaction/treeBehavior#collapseSlibing
跟你场景不一样，只是演示用法

不想破坏原始 data 缓存一份就好

**Comment by songhn233** [comment]
> updateChildren 用法 demo：https://g6.antv.vision/zh/examples/interaction/treeBehavior#collapseSlibing
> 跟你场景不一样，只是演示用法
> 
> 不想破坏原始 data 缓存一份就好

我觉得这个方法有些问题。按照给的 demo: https://codesandbox.io/s/awesome-roentgen-5kk2w?file=/src/index.js

```js
graph.updateChildren([
  {
    id: "60a600b4d3665a1d33c62d51",
    label: "asfasdf"
  }
], '6095fc1bdb4bf15a0829f2ce')
```
后依然是
![image](https://user-images.githubusercontent.com/47357585/119165490-1c6e9c00-ba90-11eb-935e-94f6ea8b8f0d.png)

但如果此时更新 `asfasdf` 节点的 id，就会按照预期布局
![image](https://user-images.githubusercontent.com/47357585/119165616-44f69600-ba90-11eb-9025-b4d71ab4722f.png)

目前解决方法感觉只能在改变数据的同时更新 id

**Comment by evanoxu** [comment]
> > updateChildren 用法 demo：https://g6.antv.vision/zh/examples/interaction/treeBehavior#collapseSlibing
> > 跟你场景不一样，只是演示用法
> > 不想破坏原始 data 缓存一份就好
> 
> 我觉得这个方法有些问题。按照给的 demo: https://codesandbox.io/s/awesome-roentgen-5kk2w?file=/src/index.js
> 
> ```js
> graph.updateChildren([
>   {
>     id: "60a600b4d3665a1d33c62d51",
>     label: "asfasdf"
>   }
> ], '6095fc1bdb4bf15a0829f2ce')
> ```
> 
> 后依然是
> ![image](https://user-images.githubusercontent.com/47357585/119165490-1c6e9c00-ba90-11eb-935e-94f6ea8b8f0d.png)
> 
> 但如果此时更新 `asfasdf` 节点的 id，就会按照预期布局
> ![image](https://user-images.githubusercontent.com/47357585/119165616-44f69600-ba90-11eb-9025-b4d71ab4722f.png)
> 
> 目前解决方法感觉只能在改变数据的同时更新 id

@songhn233 你说的更新id 还是 updateChildren这个吗？

**Comment by songhn233** [comment]
@evanoxu 是的，就是在 updateChildren 的同时修改这些要保留的数据的 id，或者在 remove 之后修改其他点的 id 应该也可以达到预期效果。

**Comment by evanoxu** [comment]
> @evanoxu 是的，就是在 updateChildren 的同时修改这些要保留的数据的 id，或者在 remove 之后修改其他点的 id 应该也可以达到预期效果。

@songhn233 不好意思哦，我试了好多次。都没办法试出你所说的方式。能在我DEMO基础上改一下给我看看吗？

**Comment by Yanyan-Wang** [comment]
```
graph.updateChildren(
    [
      {
        id: "60a600b4d3665a1d33c62d51",
        label: "asfasdf"
      }
    ],
    "6095fc1bdb4bf15a0829f2ce"
  );
```

可以实现的哦
