### ISSUE TITLE
TreeGraph可以高亮线吗？

### ISSUE THREAD

**Issue by eynait1010** [antvis/G6#2908]
如题，如果我点击了一个children节点点，可以把这个点到根节点之间的所有线改变样式吗
像下图一样
![image](https://user-images.githubusercontent.com/50448236/118980349-f7a0f880-b9ab-11eb-9518-b0d1ea53ba83.png)

**Comment by songhn233** [comment]
预设没有提供这个功能。可以自行实现。

大体思路就是监听 node:click 得到节点的 id，之后从根节点 bfs/dfs 找到目标 id 同时维护一个路径栈，之后修改栈中边的状态来设置高亮。

**Comment by eynait1010** [comment]
谢谢songhn大佬

这个我做出来了 我没有用bfs/dfs，我用的是根据当前节点，一步步去获得路径上的edge和node（因为看到有edge.getTarget()这个api，就想试一试，思路是可以的），存成一个数组，然后遍历这个数组改变edge/node的样式

**Comment by babyyage** [comment]
> 谢谢songhn大佬
> 
> 这个我做出来了 我没有用bfs/dfs，我用的是根据当前节点，一步步去获得路径上的edge和node（因为看到有edge.getTarget()这个api，就想试一试，思路是可以的），存成一个数组，然后遍历这个数组改变edge/node的样式

大佬 有demo么
