### ISSUE TITLE
第一次打开，连线会出现错乱问题，强制刷新后就恢复了

### ISSUE THREAD

**Issue by sanjinhub** [antvis/G6#2909]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://demo.w5.io](http://demo.w5.io) admin 12345678

### Steps to reproduce
剧本列表 -》 创建剧本 -》拖动连线(设计剧本)

![WechatIMG4324](https://user-images.githubusercontent.com/53846155/119077631-3922b980-ba27-11eb-808a-f76ea154b856.jpeg)

| Environment | Info |
|---|---|
| g6 | 3.7.3 |
| System | - |
| Browser | - |

---

**Comment by Yanyan-Wang** [comment]
1. 建议升级到最新版本
2. 还有问题需要提供一下最小复现的在线 demo，这个例子这么大个系统也没有代码不知道问题在哪里

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
