### ISSUE TITLE
使用jsx方式绘制节点后，可以自定义AnchorPoints吗？

### ISSUE THREAD

**Issue by eynait1010** [antvis/G6#2910]
没有在官网中看到这种例子，但是我感觉这个应该是一个很常见的需求，如下图
![image](https://user-images.githubusercontent.com/50448236/119323608-7ac69500-bcb1-11eb-86ea-2ede441c447f.png)
我有试着在nodes数据中改变锚点，如下：
![image](https://user-images.githubusercontent.com/50448236/119323892-c416e480-bcb1-11eb-8436-cd4e5c42b7de.png)
但是没有用

**Comment by mxz96102** [comment]
定义节点的时候('node-type', {
  jsx: 你的定义,
  getAnchorPoints() // 这个函数定义anchorPoints
})

**Comment by eynait1010** [comment]
done
