### ISSUE TITLE
组件外部的自定义行为 如何调用组件props中的的方法.

### ISSUE THREAD

**Issue by hyuanyuanlisiwei** [antvis/G6#2912]
组件外部的自定义行为 如何调用组件props中的的方法.

**Comment by Yanyan-Wang** [comment]
不是很明白，请提供复现在线 demo

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
