### ISSUE TITLE
G6框架有没有计划更新个添加背景图功能？

### ISSUE THREAD

**Issue by W-Rick** [antvis/G6#2913]
G6框架有没有计划更新个添加背景图功能？目前有个设置grid背景，虽然可以上传背景图，但是无法设置按照鼠标位置中心缩放，也无法拖拽画布，使用导出功能也无法把背景图导出来，非常的鸡肋。我需要自定义背景图，然后还能够自由缩放，并且能够在背景图，进行节点、链路增、删、改、查以及批量操作等。作为数据关系框架，我认为这个功能使用场景还是很多的，比如地理位置的关系，全球飞线图，设备网络拓扑图，楼层设备关系等等。希望作者能够好好考虑一下完善这一块。

**Comment by Yanyan-Wang** [comment]
在背景图进行节点、链路增、删、改、查以及批量操作是指什么？

如果是地理位置相关的场景，需要结合地图的功能，暂时不会考虑在 G6 层面去做。

**Comment by W-Rick** [comment]
如下图所示：
![image](https://user-images.githubusercontent.com/38304544/119428952-71383e00-bd40-11eb-94e3-b8845eb7924b.png)
蓝色背景为自定义的背景图，里面有划分几个区域。。。目前只能基于节点设置一个image 类型的node ，但是由于其本身是node，就无法对他上面的其他node进行操作，例如批量框选等。所以，希望能够支持一个在下层canvas里面，增加一个自定义背景图功能。这并不是要结合传统的地理地图，仅仅是一个背景图，有时候，我们需要上传一个楼层图，来做整个楼层的拓扑分析。

PS：之前查阅issus，说设置个grid，可以支持自定义背景图，但是根本没法用 ，和添加一个div背景图没什么区别，无法实现缩放，拖拽canvas和导出背景图

**Comment by Yanyan-Wang** [comment]
grid 的定位就是添加一个 div 背景的作用。需要实现你说的这个功能，可以直接在图的根图形分组上加一些图形：
graph.getGroup().addShape('image', {
  attrs: {
    ...
  }
})

**Comment by W-Rick** [comment]
这边按照你的方法添加上了背景图，但是背景图上无法进行brush-select 框选，以及背景图拖拽，我做了线上Demo，还请帮忙看一下：
https://codesandbox.io/s/polished-tdd-nnoeu?file=/src/App.js
示意图如下：
![image](https://user-images.githubusercontent.com/38304544/119449109-cdad5480-bd64-11eb-88a8-97727b7427ed.png)

**Comment by Yanyan-Wang** [comment]
因为拖拽行为被 image 图形捕获了，而不是画布，所以画布没有响应拖拽。可以给这个图形加上 capture: false 禁止它响应事件。和 attrs 平级

**Comment by W-Rick** [comment]
已实现此功能，谢谢！建议把这个功能写到文档中去，目前感觉对背景图这一块描述得很少。

**Comment by yk329** [comment]
可以实现拖拽画布时，其他节点正常移动，但是添加的这个背景shape固定不动吗？

**Comment by qianfeii** [comment]
@Yanyan-Wang 请问下新版本里getGroup 方法已被移除。还有别的方法可以添加根图形设置背景图吗？需求是和这个一样的，背景图也需要拖拽 缩放的
