### ISSUE TITLE
多个treegraph可以挂载到一个graph吗， 想用minimap组件有一个全局的视角，或者有取巧的方式可以达到这个效果吗

### ISSUE THREAD

**Issue by eynait1010** [antvis/G6#2915]
后端返回的八组数据，每一组都要是一个treeGraph。
想把他们渲染到一个treeGraph，但是他们没有交点。
图形效果大概是这样
![image](https://user-images.githubusercontent.com/50448236/119428506-96787c80-bd3f-11eb-957d-a6830fa75dce.png)
因为数据量很大，有几万个点，所有没有选择其他图，选择了树图
有什么办法可以把这些treeGraph挂载到一个graph上吗？

我目前面临的需求是：
1.有八组数据没有交点
2.数据量大概在1w+
3.每一组数据的层级关系和结构都很类似
4.要有全局搜索功能（这个有方案了）
5.要有minimap

**Comment by eynait1010** [comment]
昨晚想了一晚，也没有好的办法。
如果用Gagre，会很麻烦，要做展开折叠功能，要保证六组数据的结构相似且平行
自己写minimap也会也很多情况要考虑，肯定没有官方插件这么顺滑。。。。

**Comment by Yanyan-Wang** [comment]
我觉得 1w 的数据即使展示出来用户也没法看和分析的，建议在可视化方案上面再设计一下，比如做一下过滤、展示局部等。前端性能也不一定能够达到非常顺畅的交互，更何况加上一个 minimap，相当于复制了一遍图上的元素。另外，建议在大规模数据展示的时候尽可能选择简单的节点/边，不要增加太多的图形。

至于多棵树，目前 G6 还不支持多棵树，有一个比较 hack 的方法就是创建一个透明的假节点，连接到所有树的根节点，把所有树连接成一棵树。但是这种方式现在应该没法把树如你草图那样排列。

**Comment by eynait1010** [comment]
嗯嗯 最后决定展示局部数据
