### ISSUE TITLE
[Feature] Providing method to stop/pause/resume a single animation

### ISSUE THREAD

**Issue by lakca** [antvis/G6#2916]
如题，现在只能一次性**暂停/恢复/停止**元素所有动画，可否提供方法可以操作**单个动画**？

比如让 `animate` 函数返回 `animation.id`。

P.S. 当前只能通过 hack 的方法在`attrs`中加入自维护的 `id` 来筛选 `animations`，进而进行操作，但这种底层操作依赖库内部代码结构的稳定性。

**Comment by Yanyan-Wang** [comment]
shape.stopAnimate() 可以终止单个图形的动画

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
