### ISSUE TITLE
[Feature] Providing method to selective expansion in treegraph 选择性展开子树

### ISSUE THREAD

**Issue by pwpow** [antvis/G6#2917]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
By displaying the selected subtree instead of expanding all the subtrees, the complexity of the graph is reduced and the user can focus easily.
通过展示选定的子树，而非展开所有子树，降低图的复杂度，便于用户聚焦。

### What does the proposed API look like?
Add a new example to define the node so that it has the interaction of selecting child nodes.新增示例，定义节点，使其拥有选择子节点的交互。

**Comment by pwpow** [comment]
> 在子树的根数据上配置 collapsed: true 即不展开该子树

需求是通过新增节点交互，使得用户可以选择节点下的部分子树进行展开

**Comment by Yanyan-Wang** [comment]
这个交互可以在应用层面自己实现
