### ISSUE TITLE
Failed to execute 'importScripts' on 'WorkerGlobalScope'

### ISSUE THREAD

**Issue by TF-1992** [antvis/G6#2919]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在内网环境中， 出现这样的错误，发现初步判断是workerEnabled开启以后，会调用unpakg.com里面的一个js，导致报错。Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://unpkg.com/@antv/layout@latest/dist/layout.min.js' failed to load.
    at blob:http://localhost/5d2fd138-9477-46d1-8888-dc9119fac0ef:1:1

### What does the proposed API look like?
为啥已经通过npm打包了，不使用本地的文件，还要调用外网的？

**Comment by Yanyan-Wang** [comment]
可以下载这个脚本并上传到你们内网的地址，然后配置给 graph layout 的 workerScriptURL。workerScriptURL 可配置的目的就是为了不能访问外网地址的情况下使用的

**Comment by TF-1992** [comment]
@Yanyan-Wang 就是现在我使用downloadImage 这个进行截图，在图数据很多的情况，点击截图出现报错了，那种情况要如何解决呢
![image](https://user-images.githubusercontent.com/83797961/119951088-26335a80-bfce-11eb-8895-11539be3bad1.png)

**Comment by Yanyan-Wang** [comment]
> @Yanyan-Wang 就是现在我使用downloadImage 这个进行截图，在图数据很多的情况，点击截图出现报错了，那种情况要如何解决呢
> ![image](https://user-images.githubusercontent.com/83797961/119951088-26335a80-bfce-11eb-8895-11539be3bad1.png)

这个问题貌似和 issue 原问题没关系？可以新开 issue
过多图形下载爆栈，只能减少绘制的内容再下载图片

**Comment by Ming-z-y** [comment]
![image](https://github.com/antvis/G6/assets/94295125/f2daf060-627f-4dd9-b0c0-04e16bae1082)
请问一下这种如何解决呢
