### ISSUE TITLE
label拖拽的时候有残影

### ISSUE THREAD

**Issue by eynait1010** [antvis/G6#2920]
![image](https://user-images.githubusercontent.com/50448236/119651857-00844500-be58-11eb-8d30-d1ad92e8b746.png)
"@antv/g6": "^4.3.0",
macbook pro 2019

**Comment by eynait1010** [comment]
Google Chrome | 90.0.4430.212&nbsp;(正式版本)&nbsp;(x86_64)
-- | --

**Comment by Yanyan-Wang** [comment]
两个解决方案试试看：
1. 为节点文本设置字体，就是在 labelCfg.style.font 设置一下
2. 关闭局部渲染 graph.get('canvas').set('localRefresh', false)

**Comment by eynait1010** [comment]
关闭局部更新后解决
