### ISSUE TITLE
阻止节点点击的冒泡事件

### ISSUE THREAD

**Issue by Mason-Tc** [antvis/G6#2921]
graph.on('node:click',(evt)=>{
     console.log(evt.item)
})
document.addEventListener('click',(e)=>{
     console.log('document)
})
如何阻止node:click事件的冒泡，使document的点击事件不触发？

**Comment by Yanyan-Wang** [comment]
evt.preventDefault();

**Comment by Mason-Tc** [comment]
> evt.preventDefault();

我试了，没效果啊，大兄弟

**Comment by cshmam** [comment]
G6 v4.2.6以后的版本，事件出现传递问题，比如触发node:contextmenu事件，同时会收到node:mouseleave、node:mouseout事件

**Comment by songhn233** [comment]
> > evt.preventDefault();
> 
> 我试了，没效果啊，大兄弟

evt.stopPropagation()

**Comment by Mason-Tc** [comment]
> > > evt.preventDefault();
> > 
> > 
> > 我试了，没效果啊，大兄弟
> 
> evt.stopPropagation()
也没效果，一般能想到的办法我都试了

**Comment by Mason-Tc** [comment]
> > > evt.preventDefault();
> > 
> > 
> > 我试了，没效果啊，大兄弟
> 
> evt.stopPropagation()
也没效果，一般能想到的办法我都试了

**Comment by cshmam** [comment]
> G6 v4.2.6以后的版本，事件出现传递问题，比如触发node:contextmenu事件，同时会收到node:mouseleave、node:mouseout事件
发生这个的问题是node:contextmenu事件后，增加piePlot，同时会收到node:mouseleave、node:mouseout事件;

**Comment by Mason-Tc** [comment]
> > G6 v4.2.6以后的版本，事件出现传递问题，比如触发node:contextmenu事件，同时会收到node:mouseleave、node:mouseout事件
> > 发生这个的问题是node:contextmenu事件后，增加piePlot，同时会收到node:mouseleave、node:mouseout事件;
大概就是node:mouseleave,node：mouseout等事件也要阻止冒泡行为？

**Comment by cshmam** [comment]
> > > G6 v4.2.6以后的版本，事件出现传递问题，比如触发node:contextmenu事件，同时会收到node:mouseleave、node:mouseout事件
> > > 发生这个的问题是node:contextmenu事件后，增加piePlot，同时会收到node:mouseleave、node:mouseout事件;
> > > 大概就是node:mouseleave,node：mouseout等事件也要阻止冒泡行为？

使用G6 v4.2.6一切都正常，但是之后的版本就有问题；你的问题可以尝试使用v4.2.6看是否正常；

**Comment by Yanyan-Wang** [comment]
> > G6 v4.2.6以后的版本，事件出现传递问题，比如触发node:contextmenu事件，同时会收到node:mouseleave、node:mouseout事件
> > 发生这个的问题是node:contextmenu事件后，增加piePlot，同时会收到node:mouseleave、node:mouseout事件;

麻烦提供一下复现 demo，我尝试仅添加这三个监听，触发 contextmenu 并没有触发后两个

**Comment by cshmam** [comment]
> > > G6 v4.2.6以后的版本，事件出现传递问题，比如触发node:contextmenu事件，同时会收到node:mouseleave、node:mouseout事件
> > > 发生这个的问题是node:contextmenu事件后，增加piePlot，同时会收到node:mouseleave、node:mouseout事件;
> 
> 麻烦提供一下复现 demo，我尝试仅添加这三个监听，触发 contextmenu 并没有触发后两个
右键点击节点，弹出piePlot（此piePlot是创建一个dom的方式），需要在node:mouseleave时消失此piePlot；但是发现node:contextmenu，创建piePlot，同时会收到node:mouseleave事件；做了其它的测试，比如node:dblclick,创建piePlot,也同样会收到node相关的node:mouseout或node:mouseout事件； G6 v4.2.6不会有该问题；

**Comment by cshmam** [comment]
> > > G6 v4.2.6以后的版本，事件出现传递问题，比如触发node:contextmenu事件，同时会收到node:mouseleave、node:mouseout事件
> > > 发生这个的问题是node:contextmenu事件后，增加piePlot，同时会收到node:mouseleave、node:mouseout事件;
> 
> 麻烦提供一下复现 demo，我尝试仅添加这三个监听，触发 contextmenu 并没有触发后两个

右键点击节点，弹出piePlot（此piePlot是创建一个dom的方式），需要在node:mouseleave时消失此piePlot；但是发现node:contextmenu，创建piePlot，同时会收到node:mouseleave事件；做了其它的测试，比如node:dblclick,创建piePlot,也同样会收到node相关的node:mouseout或node:mouseout事件； G6 v4.2.6不会有该问题；

**Comment by Mason-Tc** [comment]
> > > G6 v4.2.6以后的版本，事件出现传递问题，比如触发node:contextmenu事件，同时会收到node:mouseleave、node:mouseout事件
> > > 发生这个的问题是node:contextmenu事件后，增加piePlot，同时会收到node:mouseleave、node:mouseout事件;
> 
> 麻烦提供一下复现 demo，我尝试仅添加这三个监听，触发 contextmenu 并没有触发后两个



> > > > G6 v4.2.6以后的版本，事件出现传递问题，比如触发node:contextmenu事件，同时会收到node:mouseleave、node:mouseout事件
> > > > 发生这个的问题是node:contextmenu事件后，增加piePlot，同时会收到node:mouseleave、node:mouseout事件;
> > > > 大概就是node:mouseleave,node：mouseout等事件也要阻止冒泡行为？
> 
> 使用G6 v4.2.6一切都正常，但是之后的版本就有问题；你的问题可以尝试使用v4.2.6看是否正常；

<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<script src="https://gw.alipayobjects.com/os/lib/antv/g6/4.2.6/dist/g6.min.js"></script>
	</head>
	<body>
		<div id="container"></div>
		<script type="text/javascript">
			window.onload=function(){
				let data={
					nodes:[
						{
							id: 'node',
							x: 100 ,
							y: 100
						},
					]
				}
				const graph = new G6.Graph({
					container: 'container',
					width: 200,
					height: 200,
				});
				graph.read(data);
				let box = document.getElementById('box');
				graph.on('node:click',(evt)=>{
					evt.stopPropagation()
					evt.preventDefault()
					evt.bubbles=false
					evt.cancelBubble=true
					console.log('node')
				})
				document.addEventListener('click',(e)=>{
					console.log('document')
				})
			}
		</script>
	</body>
</html>
还是不行呀，你有不冒泡的Demo么? 十分感谢

**Comment by cshmam** [comment]
> > > > G6 v4.2.6以后的版本，事件出现传递问题，比如触发node:contextmenu事件，同时会收到node:mouseleave、node:mouseout事件
> > > > 发生这个的问题是node:contextmenu事件后，增加piePlot，同时会收到node:mouseleave、node:mouseout事件;
> > 
> > 
> > 麻烦提供一下复现 demo，我尝试仅添加这三个监听，触发 contextmenu 并没有触发后两个
> 
> > > > > G6 v4.2.6以后的版本，事件出现传递问题，比如触发node:contextmenu事件，同时会收到node:mouseleave、node:mouseout事件
> > > > > 发生这个的问题是node:contextmenu事件后，增加piePlot，同时会收到node:mouseleave、node:mouseout事件;
> > > > > 大概就是node:mouseleave,node：mouseout等事件也要阻止冒泡行为？
> > 
> > 
> > 使用G6 v4.2.6一切都正常，但是之后的版本就有问题；你的问题可以尝试使用v4.2.6看是否正常；
> 
> <script src="https://gw.alipayobjects.com/os/lib/antv/g6/4.2.6/dist/g6.min.js"></script>
> <script type="text/javascript"> window.onload=function(){ let data={ nodes:[ { id: 'node', x: 100 , y: 100 }, ] } const graph = new G6.Graph({ container: 'container', width: 200, height: 200, }); graph.read(data); let box = document.getElementById('box'); graph.on('node:click',(evt)=>{ evt.stopPropagation() evt.preventDefault() evt.bubbles=false evt.cancelBubble=true console.log('node') }) document.addEventListener('click',(e)=>{ console.log('document') }) } </script> 还是不行呀，你有不冒泡的Demo么? 十分感谢

使用方式，click应该是基础事件先触发，node:click是属于G6自定义的事件

**Comment by Yanyan-Wang** [comment]
> > > > G6 v4.2.6以后的版本，事件出现传递问题，比如触发node:contextmenu事件，同时会收到node:mouseleave、node:mouseout事件
> > > > 发生这个的问题是node:contextmenu事件后，增加piePlot，同时会收到node:mouseleave、node:mouseout事件;
> > 
> > 
> > 麻烦提供一下复现 demo，我尝试仅添加这三个监听，触发 contextmenu 并没有触发后两个
> 
> 右键点击节点，弹出piePlot（此piePlot是创建一个dom的方式），需要在node:mouseleave时消失此piePlot；但是发现node:contextmenu，创建piePlot，同时会收到node:mouseleave事件；做了其它的测试，比如node:dblclick,创建piePlot,也同样会收到node相关的node:mouseout或node:mouseout事件； G6 v4.2.6不会有该问题；

piePlot 是一个 dom，鼠标进入另一个 dom，视为鼠标离开节点，没毛病吧

**Comment by cshmam** [comment]
> > > > > G6 v4.2.6以后的版本，事件出现传递问题，比如触发node:contextmenu事件，同时会收到node:mouseleave、node:mouseout事件
> > > > > 发生这个的问题是node:contextmenu事件后，增加piePlot，同时会收到node:mouseleave、node:mouseout事件;
> > > 
> > > 
> > > 麻烦提供一下复现 demo，我尝试仅添加这三个监听，触发 contextmenu 并没有触发后两个
> > 
> > 
> > 右键点击节点，弹出piePlot（此piePlot是创建一个dom的方式），需要在node:mouseleave时消失此piePlot；但是发现node:contextmenu，创建piePlot，同时会收到node:mouseleave事件；做了其它的测试，比如node:dblclick,创建piePlot,也同样会收到node相关的node:mouseout或node:mouseout事件； G6 v4.2.6不会有该问题；
> 
> piePlot 是一个 dom，鼠标进入另一个 dom，视为鼠标离开节点，没毛病吧

 首先，切换到G6 v4.2.6没有这个问题；另外piePlot的数据没有加入到graph的data.nodes中， const piePlot = new Pie("pieplot", {
        appendPadding: 10,
        data, ...  ,使用的piePlot.render()；并且piePlot中间是空的，下面就是节点，而且鼠标并没有移动；

**Comment by cshmam** [comment]
> > > > > > G6 v4.2.6以后的版本，事件出现传递问题，比如触发node:contextmenu事件，同时会收到node:mouseleave、node:mouseout事件
> > > > > > 发生这个的问题是node:contextmenu事件后，增加piePlot，同时会收到node:mouseleave、node:mouseout事件;
> > > > 
> > > > 
> > > > 麻烦提供一下复现 demo，我尝试仅添加这三个监听，触发 contextmenu 并没有触发后两个
> > > 
> > > 
> > > 右键点击节点，弹出piePlot（此piePlot是创建一个dom的方式），需要在node:mouseleave时消失此piePlot；但是发现node:contextmenu，创建piePlot，同时会收到node:mouseleave事件；做了其它的测试，比如node:dblclick,创建piePlot,也同样会收到node相关的node:mouseout或node:mouseout事件； G6 v4.2.6不会有该问题；
> > 
> > 
> > piePlot 是一个 dom，鼠标进入另一个 dom，视为鼠标离开节点，没毛病吧
> 
> 首先，切换到G6 v4.2.6没有这个问题；另外piePlot的数据没有加入到graph的data.nodes中， const piePlot = new Pie("pieplot", {
> appendPadding: 10,
> data, ... ,使用的piePlot.render()；并且piePlot中间是空的，下面就是节点，而且鼠标并没有移动；

不过，看起来后续的版本确实如你所说，在节点上弹出piePlot后，就认为节点移出了，因为显示节点信息的tooltip随着弹出的pieplot也消失了。在G6 v4.2.6上tooltip是不会消失的。个人觉得，人为把事件处理成这样，有点不适应；因为之前使用d3，以svg的方式实现此效果，也没有触节点发鼠标移动的事件；

**Comment by Yanyan-Wang** [comment]
v4.3.3 处理了内置 tooltip，鼠标从节点上进入 tooltip，tooltip 不会消失。

如果有自己加的 DOM 而不是使用内置 tooltip，可以仿照这种方式处理 https://github.com/antvis/G6/blob/29db6d2a71e6d4c204f1b8bf59f2123d56c53ac4/packages/plugin/src/tooltip/index.ts#L104

**Comment by furylee** [comment]
> graph.on('node:click',(evt)=>{
> console.log(evt.item)
> })
> document.addEventListener('click',(e)=>{
> console.log('document)
> })
> 如何阻止node:click事件的冒泡，使document的点击事件不触发？
我也发现没用,倒是用了另外一种办法,把你的容器加上事件监听,在那里阻止
