### ISSUE TITLE
关于type=image时,getUpdateItem更新

### ISSUE THREAD

**Issue by TF-1992** [antvis/G6#2926]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://www.baidu.com](http://www.baidu.com)

### Steps to reproduce
getUpdateItem(node, obj) {
      graphG6.updateItem(node, {
        style: {
          lineWidth: obj.lineWidth,
          stroke: obj.stroke
        },
        labelCfg: {
          style: {
            fill: '#000',
            fontSize: 4,
            background: obj.background
          }
        }
      })
    }
const obj = {
        fill: '#000',
        size: 6,
        lineWidth: 2,
        stroke: '#f00',
        background: {
          fill: '#efd39c',
          padding: [1]
        }
      }
      graphG6.on('nodeselectchange', (e) => {
        const nodes = e.selectedItems.nodes
        const edges = e.selectedItems.edges
        self.nodeSelect = nodes
        self.edgeSelect = edges
        nodes.forEach((item) => {
          self.getUpdateItem(item, obj)
        })
      })
在type使用默认的情况下使用nodeselectchange获取选中的item，框选更新样式正确，type=image框选就会出现下面图中显示

| Environment | Info |
|---|---|
| g6 | 4.3.2 |
| System | windos |
| Browser | Google Chrome 88.0.4324.190 |

---
![image](https://user-images.githubusercontent.com/83797961/120155944-fd0c0780-c223-11eb-9622-34408ef8228a.png)
![image](https://user-images.githubusercontent.com/83797961/120156164-48beb100-c224-11eb-8e25-f51c6895953c.png)
![image](https://user-images.githubusercontent.com/83797961/120155957-01382500-c224-11eb-945c-23530ccd8236.png)

**Comment by Yanyan-Wang** [comment]
请给出最小复现在线 demo

**Comment by TF-1992** [comment]
http://125.70.116.46:8250/tool-ip-mac/login

**Comment by Yanyan-Wang** [comment]
> http://125.70.116.46:8250/tool-ip-mac/login

你这个地址我访问不了呢

**Comment by TF-1992** [comment]
> > http://125.70.116.46:8250/tool-ip-mac/login
> 
> 你这个地址我访问不了呢

可以了

**Comment by Yanyan-Wang** [comment]
一直显示在加载中诶，最好是能让我看到代码的最小复现 demo，否则很难排查问题呢

**Comment by TF-1992** [comment]
> 一直显示在加载中诶，最好是现在能看到的小复演示，代码排查问题呢

有邮箱吗？我邮箱发你

**Comment by TF-1992** [comment]
zhualin@yocoyt.com

**Comment by Yanyan-Wang** [comment]
复现到 codepen.io 上吧

**Comment by TF-1992** [comment]
> 复现到codepen.io上吧

https://codepen.io/tf-1992/pen/GRWQJMK

**Comment by Yanyan-Wang** [comment]
这个 demo 看起来没有那个图片消失的问题，更新的时候图片因为需要重载所以会闪烁一下。但是这个 demo 中有 label 消失的问题，我发现是和设置了 nodeStateStyles 中的 select 有关，因为 brush-select 会设置被选中的节点的状态为 select，响应 nodeStateStyles.select 的样式，其实你这里不需要用这个样式，因为你对节点直接做了 update，所以把这个 nodeStateStyles.select 去掉就能解决 label 消失的问题

下面这个链接我简化了你的 demo，按住 shift 框选可以看出效果

https://codepen.io/Yanyan-Wang/pen/OJpvovE?editors=1000

**Comment by TF-1992** [comment]
> 这个 demo 看起来没有那个图片消失的问题，更新的时候图片因为需要重载所以会闪烁一下。但是这个 demo 中有 label 消失的问题，我发现是和设置了 nodeStateStyles 中的 select 有关，因为 brush-select 会设置被选中的节点的状态为 select，响应 nodeStateStyles.select 的样式，其实你这里不需要用这个样式，因为你对节点直接做了 update，所以把这个 nodeStateStyles.select 去掉就能解决 label 消失的问题
> 
> 下面这个链接我简化了你的 demo，按住 shift 框选可以看出效果
> 
> https://codepen.io/Yanyan-Wang/pen/OJpvovE?editors=1000

还是之前demo的路径，就是点击切换布局以后，在画布中宽、高被拉伸的很大，这个要怎么实现成初始的加载出来的效果呢？

**Comment by Yanyan-Wang** [comment]
fitView 设置为 false。或改用 fitCenter: true 只会移动图到中心不会缩放。

和 tittle 问题不同，有新问题的话可以新开 issue
