### ISSUE TITLE
G6 Graph是否支持多色图标问题

### ISSUE THREAD

**Issue by zmbxy95** [antvis/G6#2927]
最近看了对比了一些可视化的框架、引擎，总结来说，G6的交互API真的对我很有吸引力，但是唯一的不足，貌似不支持多色图标（哪怕是svg图标），当然可能使用DOM，自定义节点可以实现，但是需要自己添加各种交互，那么就是去了其亮点，很吸引我的交互API。

不知道是否有其他方式，能够在保留优秀的交互API基础上，提供一些多色图标的支持。会持续关注！

**Comment by songhn233** [comment]
svg 图标可以用 image 节点来 [实现](https://g6.antv.vision/zh/examples/item/defaultNodes#image)，多色图标你可以自己找一些或者用 iconfont 之类的服务。

而且假如自定义节点的话预设的交互应该也不用自己实现，可以选择 [继承的节点](https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/custom-node) 然后再自定义。

**Comment by zmbxy95** [comment]
添加iconfont节点，是通过字体图标的方式加进去，对于简单的icon还好，复杂点的，显示效果就不太又好了，其次自定义的节点，倒是可以添加path，但svg图标，想要正常显示，除非是按照需要的尺寸设计好，否则显示效果也不好（我目前看到的是这样的，不知道是不是我用的问题），主要就是尺寸显示问题，毕竟svg可以很容易的，也能够很好的进行缩放吗。

如果不需要一些状态的切换显示等，对于图标的需求，使用image节点甚至字体图标问题倒是不大，但差就差在这里了。

顺便可以提一下，我们需要搞一个网络节点的拓扑，但通常这类需求的图标想要好看、显示一个立体效果，多以多色图标为主，在加上状态切换，目前实在是想用，但是总差了点。

**Comment by Yanyan-Wang** [comment]
图形的渐变填充或描边可以看这个：https://g6.antv.vision/zh/docs/manual/middle/elements/advanced-style/gradient/#gatsby-focus-wrapper

**Comment by zmbxy95** [comment]
![image](https://user-images.githubusercontent.com/50108232/120276507-5be58580-c2e5-11eb-9be6-bfe7edb6cb55.png)
![image](https://user-images.githubusercontent.com/50108232/120276532-656eed80-c2e5-11eb-9932-1a6544671f5f.png)
![image](https://user-images.githubusercontent.com/50108232/120276569-715aaf80-c2e5-11eb-847b-3e0ee0e0a9a5.png)

看了一下，但是感觉还是达不到我的预期效果（当然，不排除我不太会用渐变填充和描边绘制复杂图形）。
图片是从iconfont上找的，我想要的效果也是类似这些的。

**Comment by Yanyan-Wang** [comment]
这种的感觉还是放图片吧，要自己画图形也太复杂了

**Comment by zmbxy95** [comment]
但是放图片，颜色什么的只能提前搞好，然后每一种图标都得准备个三四张的，然后状态切换图片，要是有需求，还得增删图片。

**Comment by Yanyan-Wang** [comment]
其实 path 图形的路径定义方式和 SVG 类似，都是用 L M A 之类的指令，你看下能不能把你这些 SVG 转换为 Path。虽然 path 中已经定义好了坐标，但是它大小和位置的话可以通过控制图形的矩阵来缩放，获取矩阵 const matrix = shape.getMatrix() || [1, 0, 0, 0, 1, 0, 0, 0, 1]，应用矩阵 shape.applyMatrix(matrix)

不过我看你的截图不像是渐变色，有些是不同的区域内填充不同颜色

**Comment by zmbxy95** [comment]
确实如此，其实主要就是在svg的坐标上。回头我试一下看看。

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。

**Comment by zmbxy95** [comment]
我试了一下，通过矩阵的方式可以实现，但是需要注意的是，注意连接线的位置要进行适当的调整，否则连接线的位置不正确，从这方面来说，我想，如果未做处理，可能后续的交互等，也会存在一些矩阵变换后带来的问题（具体未试过）。

另外也可以将svg path全部转换成 canvas命令，然后对数据直接进行放大缩小调整，这样可以不用考虑连接线的问题。就是相对直接通过矩阵缩放来调整（需要转换计算出适当大小的canvas path）稍麻烦点，但好在后续交互等，都不需要考虑节点的矩阵变换问题。
