### ISSUE TITLE
vue 使用 import "@antv/g6" 性能问题

### ISSUE THREAD

**Issue by ChenZengui** [antvis/G6#2928]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/特殊原因代码无法公开.html](https://github.com/特殊原因代码无法公开.html)

### Steps to reproduce
我是使用vue导入的G6，使用方式是
import G6 from "@antv/g6";
每次打开页面或者刷新页面需要较长时间，3s左右，
使用chrome的性能分析，是G6加载消耗很大。

下面是截图链接
![image](https://user-images.githubusercontent.com/20455914/120182978-ac0b0c00-c241-11eb-82fc-1c3856984672.png)

有什么方法可以解决吗？

| Environment | Info |
|---|---|
| g6 | 4.3.2 |
| System | win10 |
| Browser | chrome 91.0.4472.77 |

**Comment by Yanyan-Wang** [comment]
数据量大吗？renderer 是？布局用的是什么？自定义节点是否有很多图形？

**Comment by ChenZengui** [comment]
什么节点都没有的情况下也是一样，没有自定义节点。使用electron打开的页面，页面内就是一个div加载graph。我跟踪看到是import阶段耗时2-3s，还没有到渲染阶段。

**Comment by Yanyan-Wang** [comment]
不会吧，页面应该都 build 好了不会在页面运行的时候再去加载包吧

**Comment by ChenZengui** [comment]
在页面build之前加载，刷新一下页面又会重新build。就是在require G6以及递归找G6的依赖时候会慢。通过使用v8-compile-cache也没有效果。

**Comment by songhn233** [comment]
听起来感觉是构建工具的问题啊，能不能把相关配置列一下

**Comment by ChenZengui** [comment]
https://github.com/ChenZengui/electron-g6-demo，这是一个简单demo，运行起来之后，F5刷新就能跟踪到。

**Comment by songhn233** [comment]
> [https://github.com/ChenZengui/electron-g6-demo，这是一个简单demo，运行起来之后，F5刷新就能跟踪到。](https://github.com/ChenZengui/electron-g6-demo%EF%BC%8C%E8%BF%99%E6%98%AF%E4%B8%80%E4%B8%AA%E7%AE%80%E5%8D%95demo%EF%BC%8C%E8%BF%90%E8%A1%8C%E8%B5%B7%E6%9D%A5%E4%B9%8B%E5%90%8E%EF%BC%8CF5%E5%88%B7%E6%96%B0%E5%B0%B1%E8%83%BD%E8%B7%9F%E8%B8%AA%E5%88%B0%E3%80%82)

无法复现？

![image](https://user-images.githubusercontent.com/47357585/120427445-7f233a00-c3a4-11eb-9d45-ed3903f8162e.png)

load 事件基本在 500ms 左右触发，属于正常范围。

![image](https://user-images.githubusercontent.com/47357585/120427589-bbef3100-c3a4-11eb-802e-772675aa1550.png)

performance 情况也正常，耗时和引入的 element ui 差不多。

**Comment by ChenZengui** [comment]
![image](https://user-images.githubusercontent.com/20455914/120430880-41291480-c3aa-11eb-8529-71602eeda758.png)
你好，我这边所有机器测试的结果都这样。测试时看到CPU消耗情况，几次波峰都是F5刷新的时候，大概峰值30%。
![image](https://user-images.githubusercontent.com/20455914/120431747-800b9a00-c3ab-11eb-9209-2d43677b2a0a.png)

**Comment by ChenZengui** [comment]
已经解决了。webpack对于import 'module'引入得模块默认方式是在index.js文件中加入require完成引入，实质页面运行时会循环找依赖，完成模块加载。想要的打包方式是将模块的依赖和模块代码一起生成js脚本嵌入index.js文件，这样页面运行时不用再去加载模块找文件。
一种解决方法是直接import 'module的入口js文件'，另一种方式是import '模块打包好的/dist/js文件'。
我使用  import G6 from "@antv/g6/dist/g6.min.js" 解决。

**Comment by Yanyan-Wang** [comment]
> 已经解决了。webpack对于import 'module'引入得模块默认方式是在index.js文件中加入require完成引入，实质页面运行时会循环找依赖，完成模块加载。想要的打包方式是将模块的依赖和模块代码一起生成js脚本嵌入index.js文件，这样页面运行时不用再去加载模块找文件。
> 一种解决方法是直接import 'module的入口js文件'，另一种方式是import '模块打包好的/dist/js文件'。
> 我使用 import G6 from "@antv/g6/dist/g6.min.js" 解决。

赞！
