### ISSUE TITLE
dagre布局，首次渲染edge没有正常显示

### ISSUE THREAD

**Issue by fengsir** [antvis/g6#293]
* **G6 Version**:2.0.0
* **Platform**:Web
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://codepen.io/fengsir/pen/RJoLZV

dagre布局，首次渲染edge没有正常显示
![image](https://user-images.githubusercontent.com/1988974/41213642-27a418fa-6d79-11e8-813c-483c81671287.png)
分别拖拽后显示正常
![image](https://user-images.githubusercontent.com/1988974/41213666-56c5aaa4-6d79-11e8-915e-e15abf1a2892.png)

**Comment by TomHuangCN** [comment]
已修复
