### ISSUE TITLE
请教下graph.focusItem()怎么用，应该放在什么地方？

### ISSUE THREAD

**Issue by wb-sylyie** [antvis/G6#2930]
请教下graph.focusItem()怎么用，应该放在什么地方？
在graph.render()之后，不起作用，传入的参数item为Object
![image](https://user-images.githubusercontent.com/73209802/120294521-dcfa4800-c2f8-11eb-9341-4c1e988d4343.png)

**Comment by songhn233** [comment]
你应该是直接将 data.nodes 里的 node 对象传入了 focusItem，但其实在实际中是通过 itemMap 来处理节点的，所以结构会有区别，你可以通过 
```js
const node = graph.get('itemMap')['Decision trees']
```
来获取指定的节点对象，之后
```js
graph.focusItem(node)
```

**Comment by songhn233** [comment]
如果没有其他问题这个 issue 可以先关闭了
