### ISSUE TITLE
TreeGraph渲染问题

### ISSUE THREAD

**Issue by eynait1010** [antvis/G6#2932]
TreeGraph
node type为image时，渲染出来的节点不清楚
![image](https://user-images.githubusercontent.com/50448236/120421108-441b0980-c398-11eb-82f9-128e387f836e.png)
但是当放大时，图片清晰度还挺高
![image](https://user-images.githubusercontent.com/50448236/120421299-9eb46580-c398-11eb-97e9-927343272cc5.png)

这个有办法优化吗?

**Comment by Yanyan-Wang** [comment]
图是梨花的时候设置一下 pixelRatio: 2 或者更大的值试试

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
