### ISSUE TITLE
ER graph node scroll not working on firefox

### ISSUE THREAD

**Issue by ltraccount** [antvis/G6#2933]
Hello all, 
Please note that when opening ER example on your official site using **Firefox** browser, the node scroll is not working
https://g6.antv.vision/en/examples/case/simpleCase#ER

**Comment by Yanyan-Wang** [comment]
The scroll event of firefox seems different from other browsers, process the event as here Line 31 https://g6.antv.vision/en/examples/interaction/customBehavior#dragCanvasTwoFingers

**Comment by Yanyan-Wang** [comment]
The problem of ER demo is fixed.

**Comment by ltraccount** [comment]
Thank you
