### ISSUE TITLE
g6里面的文字可以旋转吗

### ISSUE THREAD

**Issue by homestylew** [antvis/G6#2934]
文字可以旋转吗

**Comment by homestylew** [comment]
类似3旋转

**Comment by Yanyan-Wang** [comment]
你是要单独控制文本图形的旋转，还是边文本跟随边方向旋转（边 labelCfg 配置 autoRotate: true）？

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
