### ISSUE TITLE
安装提示不可用版本，实际使用有什么影响么？

### ISSUE THREAD

**Issue by jeffreyyjp** [antvis/G6#2935]
![image](https://user-images.githubusercontent.com/17985592/120597872-2cb34d80-c478-11eb-8f2b-ded24b49d950.png)

**Comment by Yanyan-Wang** [comment]
没有影响。不过建议升级到最新版本

**Comment by Yanyan-Wang** [comment]
g-canvas 0.5.9 不可用提示已恢复
