### ISSUE TITLE
调用 graph.layout 方法特别慢

### ISSUE THREAD

**Issue by fengChongxiu** [antvis/G6#2936]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
无
我使用的是 dagre layout
大概四百个节点，通过 addItem，removeItem 新加/删除节点后，调用 graph.layout 大概需要 5~6s, 有啥好的快速的方案嘛

| Environment | Info |
|---|---|
| g6 | 4.2.7 |
| System | mac |
| Browser | - |

**Comment by fengChongxiu** [comment]
![image](https://user-images.githubusercontent.com/17736007/120629209-27fe9180-c498-11eb-9fed-f8c2936f35e1.png)
我自己打点看下来性能瓶颈在于 edge.refresh()

**Comment by Yanyan-Wang** [comment]
用的 polyline 吗？

**Comment by fengChongxiu** [comment]
对的，改成 直线或曲线速度就上来了，或者 routeCfg 里 simple 传 true 也可以，应该是避障那边比较耗时

**Comment by Yanyan-Wang** [comment]
polyline 自动巡径算法比较复杂，如果卡的话建议用 simple 或者其他类型的边

**Comment by fengChongxiu** [comment]
嗯，我自己使用了自定义边
