### ISSUE TITLE
如何记录上次移动后的画布位置

### ISSUE THREAD

**Issue by cpa0701** [antvis/G6#2937]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
无法通过moveTo结合x,clientX,canvasX的方法来恢复上次保存时画布移动的位置

### What does the proposed API look like?
可以恢复上次保存时画布移动的位置

**Comment by Yanyan-Wang** [comment]
可以保存移动前后的矩阵：
const matrix graph.getGroup().getMatrix();

恢复时，应用矩阵 graph.getGroup().applyMatrix(matrix)

**Comment by cpa0701** [comment]
> 可以保存移动前后的矩阵：
> const matrix graph.getGroup().getMatrix();
> 
> 恢复时，应用矩阵 graph.getGroup().applyMatrix(matrix)

applyMatrix貌似没这个方法呀

**Comment by Yanyan-Wang** [comment]
setMatrix

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
