### ISSUE TITLE
Have an edge point to the centre of another edge

### ISSUE THREAD

**Issue by andreasnett** [antvis/G6#2938]
I assume this can be done by calling graph.updateItem and set the target to an {x, y} that is the center of the edge.
The center of the edge can be calculated by having access to the target edge, which can be done at click events. However, I am not sure where I should do this to have access to both the graph, to call updateItem, as well as the target edge. When the edge is clicked, a event is fired in my app that adds this relation to the redux store. I think it should be done with afterDraw, but here I can't access graph.updateItem

**Comment by andreasnett** [comment]
I currently solve this by having a "helper node" that has 0.01 width and height that can be targeted, but this messes with the layout as the node introduces a new layer of depth

**Comment by Yanyan-Wang** [comment]
Why do you need such an edge? Could you pls introduce your original requirements?

**Comment by andreasnett** [comment]
The app I am developing is for text analysis purposes where edges pointing to edges is a visualization of relevance argument

**Comment by andreasnett** [comment]
I discovered that updateItem in afterrender could not solve the problem

**Comment by Yanyan-Wang** [comment]
> The app I am developing is for text analysis purposes where edges pointing to edges is a visualization of relevance argument

So the other end of this type of edge is a node?

**Comment by andreasnett** [comment]
Yes correct

**Comment by andreasnett** [comment]
In my code I reposition the node that is supposed to point to the center of the edge in afterrender. This does not stop the node from taking up space in the layout.
Is there any way to stop the node from using this space?

I also would still love a solution without using a hidden "helper node"

**Comment by Yanyan-Wang** [comment]
We say the edge is a relation between two objects(nodes) in graph. Actually, The 'edge' you described does not meet the such a definition. 

But to achieve the requirement, I will suggest you to add the edge with two end nodes first, and in afterrender, call the following code to update the edge to point to a coordinate:

graph.updateItem(edge, {
  target: { x: 0, y: 0 } // fill it with the coordinate of the center of the pointed edge
})

**Comment by andreasnett** [comment]
Thanks, I'll try that, but do you have any ideas on how I can prevent the node and relation to alter the layout?

**Comment by andreasnett** [comment]
I'm thinking the best way to do this is to remove the node from the document flow

**Comment by andreasnett** [comment]
> We say the edge is a relation between two objects(nodes) in graph. Actually, The 'edge' you described does not meet the such a definition.
> 
> But to achieve the requirement, I will suggest you to add the edge with two end nodes first, and in afterrender, call the following code to update the edge to point to a coordinate:
> 
> graph.updateItem(edge, {
> target: { x: 0, y: 0 } // fill it with the coordinate of the center of the pointed edge
> })

This works but the node still shifts the layout
