### ISSUE TITLE
Minimap Navigation Issues in Firefox and Safari

### ISSUE THREAD

**Issue by JoshSuttorBC** [antvis/G6#2939]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g6.antv.vision/en/examples/tool/minimap#minimap](https://g6.antv.vision/en/examples/tool/minimap#minimap)

### Steps to reproduce
Safari: Attempt to click and drag within the blue box on the minimap. Nothing happens
Firefox: Click near edge of blue box on minimap and move mouse quickly off of edge. The minimap moves, but only as long as the cursor does not leave the blue box. The larger and slower the graph is, the more visible the issue.

| Environment | Info |
|---|---|
| g6 | 4.2.7 |
| System | Widnows 10, OSX, Linux |
| Browser | Firefox 89.0, Safari 14.1.1 |

---
In Safari, the issue is clear and obvious. In Firefox, the issue is most noticeable on large graphs. When the blue box is small and the system is slow, the minimap becomes unusable. This functionality works as expected in Chromium-based browsers (Chrome, Edge, etc).

**Comment by JoshSuttorBC** [comment]
Issue in Firefox:
https://user-images.githubusercontent.com/85309587/120691174-1efbc900-c474-11eb-9e8e-f9e278f1ac68.mov
Issue in Safari:
https://user-images.githubusercontent.com/85309587/120691211-26bb6d80-c474-11eb-96e7-efb7c976051c.mov

**Comment by Yanyan-Wang** [comment]
solved by 4.7.16
