### ISSUE TITLE
在vue中引入插件会报错

### ISSUE THREAD

**Issue by JanWing1995** [antvis/g6#294]
* **G6 Version**: 2.0.0
* **G6 Plugins**: 1.0.9
* **Platform**:vscode 
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/24390317/41220335-a546f70e-6d93-11e8-85b1-f23a67b4ad1b.png)

安装：  `npm install @antv/g6-plugins --save`     
引入： `import Plugins from '@antv/g6-plugins'`  

安装正常，但是引入的时候就开始报错（如上图所示）
还没开始使用，就已经报错了

**Comment by TomHuangCN** [comment]
官方的插件目前维护在 G6 的主仓库里，如果要使用官方提供的插件，只需要安装 `@antv/g6` 即可。

```bash
npm install @antv/g6 --save
```

可以按需要引入

```js
const G6 = require('@antv/g6');
const Minimap = require('@antv/g6/plugins/tool.minimap/');
```

也可以全部引入

```js
const G6 = require('@antv/g6');
const G6Plugins = require('@antv/g6/plugins/');
```

**Comment by BusyHe** [comment]
+1
![image](https://user-images.githubusercontent.com/17348825/43309820-6cd92c4a-91b8-11e8-87d2-277949d3cc7c.png)

**Comment by TomHuangCN** [comment]
```js
const G6 = require('@antv/g6');
const G6Plugins = require('@antv/g6/build/plugins.js');
```

用 build 后的吧

**Comment by BusyHe** [comment]
@TomHuangCN 
用了build后的
![image](https://user-images.githubusercontent.com/17348825/43310613-a6a6784a-91ba-11e8-8298-02daf45a0a77.png)
