### ISSUE TITLE
如何获取和设置边的层级,  如何判断 combo 是单击还是双击事件

### ISSUE THREAD

**Issue by L924553229** [antvis/G6#2940]
- **G6 Version**:4.2.6
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
什么意思？这是两个问题吗？

**Comment by L924553229** [comment]
> 什么意思？这是两个问题吗？

您好, 这是两个问题;

1. 第一个问题场景是: 有两条线一条被 combo 遮盖一部分, 另一条完全在 combo 上
    要实现的效果 : 鼠标移入的时候,无论哪条线都要在最上层,移出的时候需要返回原位置, 这个时候就需要获取和设置边的层级
2.第二个问题场景是: 同一个combo绑定单击和双击两种事件,在双击的时候不想触发单击事件,这就需要区分事件种类

谢谢

**Comment by Yanyan-Wang** [comment]
1. 控制层级使用 edge.toFront() edge.toBack() 会比较好

2. 由于 MDN 标准是 dblclick 会触发两次 click，所以 G6 遵循了这个事件标准。不过你可以通过在 click 里面 setTimeout 判断是不是段时间内有第二次点击事件，来决定是否执行 click 响应内容

**Comment by L924553229** [comment]
好的,谢谢
这个 Issues 可以关闭了

**Comment by hhlcom** [comment]
> 1. 控制
多少毫秒内的两次点击算是双击呢
