### ISSUE TITLE
求助，TreeGraph支持两个根节点吗，并且两个根节点有重复连接的子节点

### ISSUE THREAD

**Issue by Huichifangqiu** [antvis/G6#2941]

**Comment by Yanyan-Wang** [comment]
树图的每个节点有且仅有一个父节点。目前，TreeGraph 只能有一个根节点，这个后面可能会支持多棵树，但不会支持一个节点有多个父节点。其实你可以用 mindmap 布局，把那两个节点放在根节点上方，其他子树在下方。然后上面两个节点的边箭头不用 endArrow 而用 startArrow，就能模拟你想要的效果

**Comment by Yanyan-Wang** [comment]
duplicated to https://github.com/antvis/G6/issues/2690
