### ISSUE TITLE
G6使用流水线布局时，destroy后，重新画图，tooltip功能缺失

### ISSUE THREAD

**Issue by shangdanning** [antvis/G6#2942]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lucid-hoover-cg4jf?file=/src/index.js)

### Steps to reproduce
参照链接

| Environment | Info |
|---|---|
| g6 | 4.3.2 |
| System | macOS Big Sur 11.2.3 |
| Browser | chrome 版本 90 |

> [](url)

**Comment by Yanyan-Wang** [comment]
似乎和用流水线布局无关。在 graph destroy 的时候，tooltip 对象也被 destroy 了，所以 draw 里面 tooltip 也要重新 new 一下

**Comment by shangdanning** [comment]
> 似乎和用流水线布局无关。在 graph destroy 的时候，tooltip 对象也被 destroy 了，所以 draw 里面 tooltip 也要重新 new 一下

哦哦哦，确实是这样，刚试了，就在上面的CodeSandbox上改好啦～～
ps谢谢你～这几天天天盼着回复，就是没来看一眼。。：）

**Comment by Yanyan-Wang** [comment]
解决了就好，先 close 咯
