### ISSUE TITLE
目前的layout能否支持两个dagre布局？

### ISSUE THREAD

**Issue by will2codefresher** [antvis/G6#2943]
我在官网找到一个类似的例子，通过创建新的 force 布局，改变部分节点的布局。是否可以支持有两个dagre，还是需要自定义局部的布局？

const dagreLayout2 = new G6.Layout.force({}) ;
我直接替换成
const dagreLayout2 = new G6.Layout.dagre({}) ;
出现编译问题？
此处两个问题：
1. 是否可以直接使用2种dagre布局？
2. 如果不能直接使用2种dagre，自已经仿照dagre简单实现一个别名布局是否可行？

**Comment by Yanyan-Wang** [comment]
类似这个
https://g6.antv.vision/zh/examples/net/layoutMechanism#sublayoutPipes

也可以自定义布局

**Comment by will2codefresher** [comment]
用pipes ，配置dagre + grid 实现了，谢谢。
