### ISSUE TITLE
在vue中使用updateItem更新子节点label时  数据更新 但是页面不更新 应该怎么处理？

### ISSUE THREAD

**Issue by babyyage** [antvis/G6#2946]

**Comment by Yanyan-Wang** [comment]
请给出复现在线 demo

**Comment by babyyage** [comment]
> 请给出复现在线 demo

你好 我反复测试一下  找到原因了  是因为我重写了 update方法引起的。     这样的情况下 怎么处理比较好呢

**Comment by babyyage** [comment]
已解决

**Comment by Gzbox** [comment]
> 已解决

请问您是如何解决的？

**Comment by babyyage** [comment]
> > 已解决
> 
> 请问您是如何解决的？

开始以为是个bug  但是后来自测修改 发现不是api的问题   你可以用这个   this.graph.updateItem(节点Id, { label: ‘更新后的label’ })
