### ISSUE TITLE
G6，使用 updateItem 改变 位置x，y，如何增加过渡动画

### ISSUE THREAD

**Issue by 905868332** [antvis/G6#2947]
G6，使用 updateItem 改变 位置x，y，如何增加过渡动画

**Comment by Yanyan-Wang** [comment]
// 在节点图形分组上使用动画 API，第一个参数为目标样式，第二个参数可配置动画参数
node.getContainer().animate({ matrix: [1, 0, 0, 0, 1, 0, toX, toY, 1] }, { duration: 300, easing: 'easeLinear' });
// 同步数据中的 x y
node.getModel().x = toX;
node.getModel().y = toY;

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
