### ISSUE TITLE
(ask): Can we render circle packing?

### ISSUE THREAD

**Issue by ibreakthecloud** [antvis/G6#2948]
I want to use G6 because it has so many good features and good performance. 
All I want to know is:
Is it possible to get this sort of graph (circle packing):

![image](https://user-images.githubusercontent.com/18168330/121109676-e2580680-c7c0-11eb-87df-a7163a408c74.png)

ref: https://vasturiano.github.io/circlepack-chart/example/flare/

I know there is something called `type: 'comboForce'` but that fails to generate layout when data size is large.

**Comment by Yanyan-Wang** [comment]
G6 does not support it yet
