### ISSUE TITLE
click-select交互行为

### ISSUE THREAD

**Issue by Raven2049** [antvis/G6#2949]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://antv-g6.gitee.io/zh/examples/interaction/select#click](https://antv-g6.gitee.io/zh/examples/interaction/select#click)

### Steps to reproduce
我是直接在文档上修改查看的。当画布上有combo和node的时候，首先选中一个node，接下来选中一个combo，结果是前一个node并不会被反选，不知道这是feature还是bug，如果是feature是否可以加一个可关闭这个特性的选项，该特性有点影响我现在的业务并且我暂时没想到比较容易的解决办法
![QQ图片20210608100936](https://user-images.githubusercontent.com/33887949/121111627-d19ba500-c841-11eb-8093-dbf636e94ea5.png)

| Environment | Info |
|---|---|
| g6 | 4.3.3 |
| System | win10 |
| Browser | edge chromium 91.0.864.41  |

**Comment by Yanyan-Wang** [comment]
下个小版本修复，着急的话可以在 combo 点击的时候手动清空节点选中状态
graph.on('combo:click', e => {
  graph.findAllByState('node', 'selected').forEach(sNode => graph.setItemState(sNode, 'selected', false));
});

同理，在 node 点击的时候清空 combo 选中状态

**Comment by Yanyan-Wang** [comment]
4.3.4 已修复
