### ISSUE TITLE
[Example] 通过直接在节点的锚点上拖拉添加edge

### ISSUE THREAD

**Issue by Trick93** [antvis/G6#2950]
### Description

由于查看文档发现，虽然官方有提供相关的 behaviors ，即 [create-edge](https://g6.antv.vision/zh/docs/manual/middle/states/defaultBehavior#create-edge) 来在某个节点上直接拖拽拉出线添加边。但在节点本身可以自由拖拽移动的情况下，就有冲突了。

因此该例子是利用节点的 `linkPoints` ，当鼠标点击在 `linkPoints` 上 ，则可以拖拉出线到另外一个节点的 `linkPoints`，完成连线。

附上关于 [linkPoints](https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/built-in/circle/#linkpoints) 和 [anchorPoint](https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/anchorpoint)

### Implementation

[![Edit elated-moon-s9cyo](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/elated-moon-s9cyo?fontsize=14&hidenavigation=1&theme=dark&view=preview)

**Comment by mxz96102** [comment]
感谢你的贡献，现在我们官网有一个例子，感觉和这个比较相似，https://antv-g6.gitee.io/zh/examples/interaction/createEdge#drag-link-point 请问两者实现有什么区别吗～

**Comment by Trick93** [comment]
> 感谢你的贡献，现在我们官网有一个例子，感觉和这个比较相似，https://antv-g6.gitee.io/zh/examples/interaction/createEdge#drag-link-point 请问两者实现有什么区别吗～

不好意思，可能那时候之前看的旧文档没有下面两个例子，后面更新了没发现

看了下实现上差不多，只不过我这边例子是单独自定义了一个 `behavior` 来达到目的。这边觉得重复就关了哈，不好意思！

**Comment by Yanyan-Wang** [comment]
还是感谢贡献，有新想法随时沟通哦
