### ISSUE TITLE
Improve developer contribution process

### ISSUE THREAD

**Issue by jfstephe** [antvis/G6#2951]
- [ x ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Creating a PR for this project is painful. Building the app is not straight forward.

Building this on Ubuntu doesn't work. Would be good to know what environment you run the npm commands in.

yarn isn't a dependency so when eventually I tried powershell I had to globally install that too.

Also, the tests fail for me in web-worker related code.  I was running on node v15.11.0 but again... no minimum version is specified so I don't know if this is ok or not?!?

### What does the proposed API look like?
Clearer instructions   working tests please!

**Comment by Yanyan-Wang** [comment]
we run npm run build on mac. What is the error message on your Ubuntu?

**Comment by ensconced** [comment]
What is the current correct version of node to use for the project? Could we add a `.nvmrc` file?
Also, after a fresh clone of the repo and running `npm install` I get this error message - it seems like we have conflicting requirements for the tslint version.

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: g6@undefined
npm ERR! Found: tslint@6.1.3
npm ERR! node_modules/tslint
npm ERR!   tslint@"^6.1.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer tslint@"^5.11.0" from tslint-config-airbnb@5.11.2
npm ERR! node_modules/tslint-config-airbnb
npm ERR!   tslint-config-airbnb@"^5.11.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/ensconced/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ensconced/.npm/_logs/2022-08-27T16_41_19_519Z-debug-0.log
```
