### ISSUE TITLE
在ios手机中使用toFullDataURL返回的 dataUrl 字符串放在img中显示为空白，安卓手机中浏览器没有问题。

### ISSUE THREAD

**Issue by csx0309** [antvis/G6#2953]
在ios手机中使用toFullDataURL有时返回的 dataUrl 字符串显示为空白，有时可以正常显示图片，安卓浏览器没有问题，感觉在ios中返回的dataUrl 有问题。

**Comment by csspmini-web** [comment]
> 在ios手机中使用toFullDataURL有时返回的 dataUrl 字符串显示为空白，有时可以正常显示图片，安卓浏览器没有问题，感觉在ios中返回的dataUrl 有问题。

可能是你要导出的图片太大了，长/宽超过了极限值， 你可以试试把 zoom 改小点 再导出

**Comment by Yanyan-Wang** [comment]
看下是否有报错

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
