### ISSUE TITLE
对节点图形进行旋转后，连接点没有跟着一起旋转改变位置？

### ISSUE THREAD

**Issue by hushaoyu** [antvis/G6#2954]
![image](https://user-images.githubusercontent.com/25758091/121351095-f7b66780-c95d-11eb-8d45-aca720f31568.png)

**Comment by hushaoyu** [comment]
节点内image keyShape旋转代码：
`const group = e.item.getContainer();
                    group.find(child => {
                        child.rotate(Math.PI / 36)
                    })`
`if (matrix) {
                                    rect.setMatrix(matrix)
                                }`

**Comment by Yanyan-Wang** [comment]
连接点是相对于当前绘制完成后的 bbox 的
