### ISSUE TITLE
在给顶点添加边框后，拖动顶点之后，边距离顶点边缘存在空隙

### ISSUE THREAD

**Issue by void0720** [antvis/G6#2955]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g6.antv.vision/zh/examples/performance/perf#eva](https://g6.antv.vision/zh/examples/performance/perf#eva)

### Steps to reproduce
1、鼠标移入顶点后给顶点增加边框（增加边框越大效果越明显）
2、拖拽顶点后松开鼠标
3、鼠标指针移出顶点
4、出现顶点连线（起点或者终点）会和被拖拽顶点边缘有空隙，空隙大小为边框粗细

| Environment | Info |
|---|---|
| g6 | 4.3.2 |
| System | macOS Big Sur 11.4 |
| Browser | Google Chrome 91.0.4472.77 |

![image](https://user-images.githubusercontent.com/25167509/121358225-048a8980-c965-11eb-8439-f652480e35c6.png)

**Comment by Yanyan-Wang** [comment]
没能复现 https://codesandbox.io/s/lingering-fire-icfsg?file=/index.js，请提供最小复现 demo

**Comment by void0720** [comment]
打开drag-node就可以复现了，复现地址如下：
https://codesandbox.io/s/quirky-frog-fbk35?file=/index.js

**Comment by void0720** [comment]
需要拖动任何一个顶点后即可复现

**Comment by Yanyan-Wang** [comment]
应该是因为描边加粗之后，节点 bbox 变大并存入缓存，鼠标移出描边恢复之后，没有清空缓存重新计算 bbox 导致，可以这样解决，看 L34～37
https://codesandbox.io/s/modest-moore-6qghz
