### ISSUE TITLE
【通过自定义布局实现了】pipes混合布局连线、锚点紊乱

### ISSUE THREAD

**Issue by will2codefresher** [antvis/G6#2956]
其实是三级树的嵌套，一二级使用dagre上下布局，第三级需要展示更多内容，本来是计划使用右向的darge，但是多个darge紊乱，第三级使用了grid布局，如下：
![image](https://user-images.githubusercontent.com/12540372/121475417-f76aaa80-c9f7-11eb-8f77-3d527b558eef.png)
但是如果再嵌套一级时，结构就乱了，如下；
![image](https://user-images.githubusercontent.com/12540372/121478548-bb394900-c9fb-11eb-9ab7-5b677000e7b9.png)
绿色所示为嵌套的一级，如果再嵌套，就完全乱了，

目前有2个问题，
1. 嵌套多了之后，锚点紊乱，本来应该是上中、右中两个锚点，但是全部到一个上中锚点
2. dagre紊乱
感觉跟grid的begin会影响布局，但是其机制不是很清楚

这种dagre + grid，并且嵌套布局是否可以通过G6实现呢？
源码地址： https://gitee.com/codefresher/mind-on-g6.git

**Comment by Yanyan-Wang** [comment]
位置混乱问题：pipe 布局之间不会互相考虑占用的位置，这个需要用户给定每个布局参数来防止每个子图的重叠，也就是说每块 grid 的 begin 的配置要考虑上面 dagre 的布局情况。

锚点问题：可以指定一下边的 sourceAnchor 和 targetAnchor

**Comment by will2codefresher** [comment]
通过自定义布局实现了

**Comment by 799531161** [comment]
> 通过自定义布局实现了

老哥，能看看自定义实现的源码吗，我也要做一样效果的布局，谢谢啦
