### ISSUE TITLE
有时 拖拽节点到另外一个节点上面  监听dragnodeend事件获取不到targetItem

### ISSUE THREAD

**Issue by babyyage** [antvis/G6#2957]
![image](https://user-images.githubusercontent.com/28697181/121513064-03b52e80-ca1d-11eb-9c70-d437bfecdd6b.png)
有时 拖拽节点到另外一个节点上面 监听dragnodeend事件获取不到targetItem
上图两个节点的重合区域很大了   但是还是获取不到targetitem
监听node:dragover 也获取不到
请问拖拽的原理是怎样的
以下是demo
https://codesandbox.io/s/divine-fast-thory?file=/src/components/HelloWorld.vue:323-331

**Comment by babyyage** [comment]
@Yanyan-Wang 你好 麻烦有时间看一下这个issue呗

**Comment by songhn233** [comment]
dragnodeend 事件中的 target 预期效果和你理解的不一样，在没有 combo 的情况下 [肯定为空](https://github.com/antvis/G6/blob/master/packages/pc/src/behavior/drag-node.ts#L272)，如果想获取拖拽后 drop 到的节点，可以参考 #2150

**Comment by Yanyan-Wang** [comment]
可以监听 node:dragenter 或者 node:drop，参数中的 item 为“被放置到”的节点

**Comment by babyyage** [comment]
> 可以监听 node:dragenter 或者 node:drop，参数中的 item 为“被放置到”的节点

嗯  这两个监听事件我也试过了   drag:enter有时都不会触发这个事件    node:drop 有时item为null 也是挺奇怪的    最后我换了其他的方式 可以实现了

**Comment by babyyage** [comment]
> dragnodeend 事件中的 target 预期效果和你理解的不一样，在没有 combo 的情况下 [肯定为空](https://github.com/antvis/G6/blob/master/packages/pc/src/behavior/drag-node.ts#L272)，如果想获取拖拽后 drop 到的节点，可以参考 #2150

嗯  不太理解其中原理   但是尝试过 把被拖拽的节点与drop节点尽量重叠面积保持比较大的情况下  基本上都是能获取到target的  不过后来也没用combo换了其他的思路 实现了
