### ISSUE TITLE
血缘图的示例图是不是给的不对

### ISSUE THREAD

**Issue by Zhb932647086** [antvis/G6#2958]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g6.antv.vision/zh/docs/design/template](https://g6.antv.vision/zh/docs/design/template)

### Steps to reproduce
无

| Environment | Info |
|---|---|
| g6 | 4.3.3 |
| System | - |
| Browser | - |

---
在设计体系-模板-血缘图模块中，说明了'数据流入节点可以有多个，是主节点的父节点，表示数据来源；',也就是子节点可以有多个父，但是给的设计示意图是一个树图，树图子节点好像是不可以有多个父节点的，这样是不是有问题。

**Comment by Yanyan-Wang** [comment]
这种情况会考虑这样的树图：https://g6.antv.vision/zh/examples/tree/mindmap#hMindmap
把左侧的分支的边用 startArrow，右边的分支的边用 targetArrow

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
