### ISSUE TITLE
节点排版问题

### ISSUE THREAD

**Issue by noonehide** [antvis/G6#2959]
![111](https://user-images.githubusercontent.com/12743022/121518348-f602a780-ca22-11eb-8c8c-81d118c86e19.png)
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/trusting-thunder-0d6di?file=/src/index.js)

### Steps to reproduce
直接可以看到，某些节点的后续节点的位置，没有与自己在同一水平线。

| Environment | Info |
|---|---|
| g6 | 4.2.6 |
| System | mac |
| Browser | chrome |

**Comment by noonehide** [comment]
Dagre布局，可不可以配置sortBy: data?

**Comment by Yanyan-Wang** [comment]
不支持，依赖的 dagrejs https://github.com/dagrejs/dagre

**Comment by fruit5566** [comment]
遇到同样的问题

**Comment by xidiansll** [comment]
has the same problem.

**Comment by Yanyan-Wang** [comment]
新版本中已不存在 demo 中问题哈
