### ISSUE TITLE
G6 容器大小变化后如何重绘？

### ISSUE THREAD

**Issue by endink** [antvis/g6#296]
已经尝试：
setFitView : 无效
refresh: 已经没有这个方法
layout: 无效
autosize: 无效

尽快整理一下文档吧，非常酷的项目！

**Comment by endink** [comment]
对了，其实非常需要 "legend" 这种功能，虽然 behavior 可以得到鼠标事件回调，但是自己绘制一个优雅弹出效果还是很困难（原谅我不是专业前端），希望统一提供一下吧！

**Comment by TomHuangCN** [comment]
changeSize 会自动重绘

**Comment by TomHuangCN** [comment]
legend 可以那这个先用着 https://github.com/antvis/g6/blob/master/plugins/tool.d3.mapper/index.js
