### ISSUE TITLE
vite 打包出现报错。发布的项目页面进不去。

### ISSUE THREAD

**Issue by yang867381349** [antvis/G6#2961]
![image](https://user-images.githubusercontent.com/20942938/121661165-81894080-cad6-11eb-88a9-e3779470391d.png)
![image](https://user-images.githubusercontent.com/20942938/121661253-98c82e00-cad6-11eb-9d5c-e5827db62ed9.png)

**Comment by wooodchen** [comment]
me too

**Comment by wooodchen** [comment]
额，试了各种rollup插件，虽然没消除这个提示，但是能用了。需要插件`rollup-plugin-node-rosolve`和`rollup-plugin-commonjs`
在`vite.config.js`中如下配置
```javascript
import resolve from 'rollup-plugin-node-resolve'
import commonjs from 'rollup-plugin-commonjs'
...
export default defineConfig({
    plugin: [
        ...,
        resolve(),
        commonjs(),
        ...
})
```
亲试可用

**Comment by Yanyan-Wang** [comment]
@wooodchen 感谢提供方案，已加入官网 FAQ 文档并在文档中 at 你咯！https://g6.antv.vision/zh/docs/manual/FAQ/vite-support

**Comment by humbinal** [comment]
> 额，试了各种rollup插件，虽然没消除这个提示，但是能用了。需要插件`rollup-plugin-node-rosolve`和`rollup-plugin-commonjs` 在`vite.config.js`中如下配置
> 
> ```js
> import resolve from 'rollup-plugin-node-resolve'
> import commonjs from 'rollup-plugin-commonjs'
> ...
> export default defineConfig({
>     plugin: [
>         ...,
>         resolve(),
>         commonjs(),
>         ...
> })
> ```
> 
> 亲试可用

按照这个配置了之后，所有页面都打不开了，出现如下错误：
```
Uncaught TypeError: Jk is not a function
    at vendor.c0313e67.js:4
```

**Comment by luxferrew** [comment]
Please update vite to latest version(2.8.x at present) 

[node-resolve plugin is covered by vite](https://vite-rollup-plugins.patak.dev/#node-resolve), and you don't need add this plugin

[commonjs plugin is included in vite](https://vite-rollup-plugins.patak.dev/#commonjs), you can set operation in [build.commonjsoptions](https://cn.vitejs.dev/config/#build-commonjsoptions)

But it can't fix another issue, I also have the issue [#3284](https://github.com/antvis/G6/issues/3284) when I build my project by vite(rollup).

If anyone has the same problem, maybe would fix by setting config like this :

```
// vite.config.ts

{
  resolve: {
    alias: [
      {
          find: /^@antv\/g6/,
          replacement: path.resolve(
            __dirname,
            './node_modules/@antv/g6/dist/g6.min.js',
          ),
        },
    ]
  }
}
```

And this could help me solve my production build...

**Comment by qwfy5287** [comment]
> ly1991 发了解决方法 
> That's because of @rollup/plugin-commonjs which the vite depends on, the v21.0.0 version of the plugin has a breaking change: [https://github.com/rollup/plugins/blob/master/packages/commonjs/CHANGELOG.md](url), just add the following config to your vite.config.js will solve the problem @qwfy5287
> 
> ```js
> build: {
>       commonjsOptions: {
>           ignoreTryCatch: false,
>       },
>   },
> ```

**Comment by Hiliyanbo** [comment]
> 
可真是是太有用了！
