### ISSUE TITLE
changeData on comboForce layout breaks the graph

### ISSUE THREAD

**Issue by ibreakthecloud** [antvis/G6#2962]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/suspicious-diffie-67rtj?file=/src/index.js)

### Steps to reproduce
after few seconds call graph.changeData with new data and graph will break

| Environment | Info |
|---|---|
| g6 | 4.3.3 |
| System | - |
| Browser | - |

**Comment by ibreakthecloud** [comment]
in comboForce graph, when it's changeData is called, whole graph gets broken. On doing console log of graph.save() after changeData is called, it looks something like below:
![image](https://user-images.githubusercontent.com/18168330/121964389-585bf080-cd20-11eb-82bc-ccda62586fc9.png)


Here, coordinates of all the nodes, edges and combos are `NaN`

**Comment by songhn233** [comment]
This bug should be related to combo config and `comboForce` layout method, if using other layouts it can't reproduce.

So you can use `graph.render()` instead of `graph.refresh()` or switch to other layouts to solve the problem.

Then waiting for the bug can be fixed :)

**Comment by ibreakthecloud** [comment]
> This bug should be related to combo config and `comboForce` layout method, if using other layouts it can't reproduce.
> 
> So you can use `graph.render()` instead of `graph.refresh()` or switch to other layouts to solve the problem.
> 
> Then waiting for the bug can be fixed :)

For other layouts like `force`, `grid`, etc , it is working fine. It's only breaking for `comboForce`. And I cannot use other layouts because I need the "Combo" feature

**Comment by Yanyan-Wang** [comment]
Fixed. Upgrade @antv/layout to 0.1.15 pls.
