### ISSUE TITLE
demo url is wrong

### ISSUE THREAD

**Issue by ghoshorn** [antvis/G6#2963]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://antv-g6.gitee.io/en/docs/api/Event](https://antv-g6.gitee.io/en/docs/api/Event)

### Steps to reproduce
the "demo" href url is wrong in page https://antv-g6.gitee.io/en/docs/api/Event for
canvas:dragstart	Activated when user begins to drag the canvas. This event is applied on the dragged canvas. Demo.

which contains a context menu demo link

| Environment | Info |
|---|---|
| g6 | 4.3.3 |
| System | - |
| Browser | - |

**Comment by babyyage** [comment]
https://antv-g6.gitee.io/en/examples/tool/contextMenu

**Comment by songhn233** [comment]
I think it just a typo reference to chinese docs. No demo for the `convas:dargstart`.

**Comment by Yanyan-Wang** [comment]
thanks, fixed. The demo is for contextmenu
