### ISSUE TITLE
路径节点 设置 draggable 后，drag-node 不能拖拽节点

### ISSUE THREAD

**Issue by NARUTOne** [antvis/G6#2966]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/g6-path-node-draggable-mk5hy)

### Steps to reproduce
点击节点空白不能拖拽，文本加上了draggable 所以可以拖拽
![image](https://user-images.githubusercontent.com/18441915/122538716-67f97300-d059-11eb-9b87-77cd78591952.png)

| Environment | Info |
|---|---|
| g6 | 4.3.3 |
| System | - |
| Browser | - |

**Comment by NARUTOne** [comment]
@Yanyan-Wang 你好 麻烦有时间看一下这个issue哈 😄

**Comment by Yanyan-Wang** [comment]
因为 path 拾取的是边缘。要可以拾取，可以加个填充色， fill: '#fff'，想填充透明，可以加 fillOpacity: 0

**Comment by NARUTOne** [comment]
![image](https://user-images.githubusercontent.com/18441915/122702793-bc336b80-d282-11eb-95ad-978f422c8811.png)
如图鼠标触发文本和边框path会正常触发active状态，也可以拖拽节点，但是 触发节点内部空白区域就不能触发active状态，也不能拖拽，不好意思，由于我们这边还有一些行为模式和一些其他业务代码，我上面的示例没有完全复现我这边的场景，这种情况一般会是什么原因导致的呢@Yanyan-Wang  🇶🇦

**Comment by NARUTOne** [comment]
svg渲染下就是正常的，可以正常拾取触发

**Comment by Yanyan-Wang** [comment]
如上述，path 是否填充？再看下自定义节点内部还有没有其它图形

**Comment by NARUTOne** [comment]
@Yanyan-Wang   复现了，示例里加上了，发现加了 弧度path就不行，麻烦看看哈，谢谢

**Comment by NARUTOne** [comment]
![image](https://user-images.githubusercontent.com/18441915/122713485-594ccf00-d298-11eb-8774-db0ecfa20c70.png)

**Comment by Yanyan-Wang** [comment]
path 带有 A 的是有些问题，尽量避免使用。你这里为什么不使用带圆角的矩形？rect 图形配置 radius: 4

**Comment by NARUTOne** [comment]
我现在是用rect + radius 实现的，只是提出这个issue询问下确认下问题原因，是这种带A的路径有点问题呗，好的，谢谢，后续有修复我再更新下

**Comment by NARUTOne** [comment]
@Yanyan-Wang   底层渲染引擎 path 带有 A 的有点问题，是指G这个库吗，这个后续有修复计划吗 ❓

**Comment by Yanyan-Wang** [comment]
> @Yanyan-Wang 底层渲染引擎 path 带有 A 的有点问题，是指G这个库吗，这个后续有修复计划吗 ❓

是的，后面会修复，只是在做 G 的大升级，可能还没确定具体什么时候修复

**Comment by Yanyan-Wang** [comment]
非常抱歉，当前版本(3.x、4.x)依赖的底层渲染引擎暂时不会考虑 SVG 问题的修复，渲染引擎目前正在大升级，我们也将在新版本接入新渲染引擎，届时应当可以解决 SVG 各种 bug
