### ISSUE TITLE
Fruchterman开启gpuEnabled:true,无法拖拽节点

### ISSUE THREAD

**Issue by huangtangtang** [antvis/G6#2972]
采用GPU版本的fruchterman，无法拖拽节点，想要实现和force基础力导向拖拽节点的效果，请问该如何实现？
https://g6.antv.vision/zh/examples/net/forceDirected#basicForceDirected
```
const container = document.getElementById('container');
const width = container.scrollWidth;
const height = container.scrollHeight || 500;
const graph = new G6.Graph({
  container: 'container',
  width,
  height,
  modes: {
    default: ['drag-canvas', 'drag-node'],
  },
  layout: {
    type: 'fruchterman',
    gravity: 5,
    speed: 5,
    gpuEnabled: true,
    // for rendering after each iteration
    //gpuEnabled:true,
    tick: () => {
      graph.refreshPositions()
    }
  },
  animate: true,
  defaultNode: {
    size: 30,
  },
});
graph.data(data);
graph.render();
graph.on('node:dragstart', function (e) {
    graph.layout();
    refreshDragedNodePosition(e);
  });
  graph.on('node:drag', function (e) {
    const forceLayout = graph.get('layoutController').layoutMethods[0];
    forceLayout.execute();
    refreshDragedNodePosition(e);
  });
  graph.on('node:dragend', function (e) {
    e.item.get('model').fx = null;
    e.item.get('model').fy = null;
  });
if (typeof window !== 'undefined')
  window.onresize = () => {
    if (!graph || graph.get('destroyed')) return;
    if (!container || !container.scrollWidth || !container.scrollHeight) return;
    graph.changeSize(container.scrollWidth, container.scrollHeight);
  };
  function refreshDragedNodePosition(e) {
  const model = e.item.get('model');
  model.fx = e.x;
  model.fy = e.y;
}

```

**Comment by javaNaruto** [comment]
我在gfForce，GPU的情况下也是如此，我认为是拖拽的过程中布局已经稳定，所以拖动才看到的是卡顿的效果。

**Comment by huangtangtang** [comment]
> 我在gfForce，GPU的情况下也是如此，我认为是拖拽的过程中布局已经稳定，所以拖动才看到的是卡顿的效果。
那就是无法实现正常的拖拽效果，更无法实现像force布局拖拽节点的效果了

**Comment by javaNaruto** [comment]
> > 我在gfForce，GPU的情况下也是如此，我认为是拖拽的过程中布局已经稳定，所以拖动才看到的是卡顿的效果。
> > 那就是无法实现正常的拖拽效果，更无法实现像force布局拖拽节点的效果了

是的，不能通过调用布局方法来实现，只能通过多选，框选的方式拖动。我们自己的业务也有类似的需求，通过把期望选中的点设置为selected状态来进行拖动

**Comment by huangtangtang** [comment]
> > > 我在gfForce，GPU的情况下也是如此，我认为是拖拽的过程中布局已经稳定，所以拖动才看到的是卡顿的效果。
> > > 那就是无法实现正常的拖拽效果，更无法实现像force布局拖拽节点的效果了
> 
> 是的，不能通过调用布局方法来实现，只能通过多选，框选的方式拖动。我们自己的业务也有类似的需求，通过把期望选中的点设置为selected状态来进行拖动

好的，谢谢解答

**Comment by Yanyan-Wang** [comment]
因为开启 GPU 之后，布局是在 GPU 中计算完成后才能更新渲染到 canvas 上的，不像 CPU 计算一样可以每次迭代都渲染。所以开启 GPU 之后，只能等到拖拽完成之后再去 GPU 计算，完成后统一更新

CPU 拖拽过程刷新布局：https://codesandbox.io/s/festive-butterfly-efx35

GPU 拖拽完成后刷新布局：https://codesandbox.io/s/festive-butterfly-efx35

**Comment by javaNaruto** [comment]
> 因为开启 GPU 之后，布局是在 GPU 中计算完成后才能更新渲染到 canvas 上的，不像 CPU 计算一样可以每次迭代都渲染。所以开启 GPU 之后，只能等到拖拽完成之后再去 GPU 计算，完成后统一更新
> 
> CPU 拖拽过程刷新布局：https://codesandbox.io/s/festive-butterfly-efx35
> 
> GPU 拖拽完成后刷新布局：https://codesandbox.io/s/festive-butterfly-efx35

感谢解答

**Comment by huangtangtang** [comment]
> 因为开启 GPU 之后，布局是在 GPU 中计算完成后才能更新渲染到 canvas 上的，不像 CPU 计算一样可以每次迭代都渲染。所以开启 GPU 之后，只能等到拖拽完成之后再去 GPU 计算，完成后统一更新
> 
> CPU 拖拽过程刷新布局：https://codesandbox.io/s/festive-butterfly-efx35
> 
> GPU 拖拽完成后刷新布局：https://codesandbox.io/s/festive-butterfly-efx35

谢谢
