### ISSUE TITLE
force力导向，如何设置圆形

### ISSUE THREAD

**Issue by huangtangtang** [antvis/G6#2973]
想要实现d3力导向的效果， https://observablehq.com/@d3/disjoint-force-directed-graph
请问g6怎么实现这个效果？

**Comment by huangtangtang** [comment]
@Yanyan-Wang 你好，麻烦看下，这个如何实现，谢谢

**Comment by Yanyan-Wang** [comment]
fruchterman。如果用 force 可以尝试加这两个参数，相当于加了一个中心力 clustering: true, clusterFociStrength: 0.1。后者是中心力大小可以自行调整。然后在数据里面给所有点一个一样的 cluster 
data.nodes.forEach(node => {
      node.cluster = 'c0';
    })

**Comment by huangtangtang** [comment]
> fruchterman。如果用 force 可以尝试加这两个参数，相当于加了一个中心力 clustering: true, clusterFociStrength: 0.1。后者是中心力大小可以自行调整。然后在数据里面给所有点一个一样的 cluster
> data.nodes.forEach(node => {
> node.cluster = 'c0';
> })
十分感谢解答。 
我还有一个疑问：如果数据特别多，数据显示不全，怎么让这个圆渲染出来的时候就适应当前视图大小，我设置了fitView: true,数据是先渲染一段时间，再去适应视图，整个图有个过渡的效果，效果不理想。我想要渲染的过程，像 https://observablehq.com/@d3/disjoint-force-directed-graph 一样，怎么做呢？

**Comment by javaNaruto** [comment]
@Yanyan-Wang 请问gForce能设置clustring，clusterFociStrength这些参数吗，我这边的业务期望能达到这样的效果
![image](https://user-images.githubusercontent.com/48909573/123926276-4f288000-d9be-11eb-8bef-8b5cbca7bbd6.png)

**Comment by Yanyan-Wang** [comment]
> > fruchterman。如果用 force 可以尝试加这两个参数，相当于加了一个中心力 clustering: true, clusterFociStrength: 0.1。后者是中心力大小可以自行调整。然后在数据里面给所有点一个一样的 cluster
> > data.nodes.forEach(node => {
> > node.cluster = 'c0';
> > })
> > 十分感谢解答。
> > 我还有一个疑问：如果数据特别多，数据显示不全，怎么让这个圆渲染出来的时候就适应当前视图大小，我设置了fitView: true,数据是先渲染一段时间，再去适应视图，整个图有个过渡的效果，效果不理想。我想要渲染的过程，像 https://observablehq.com/@d3/disjoint-force-directed-graph 一样，怎么做呢？

因为布局计算完成之前，是没法知道最终的图大小的，所以没法一开始就适配。但是可以参考这里去增加一下约束：https://g6.antv.vision/zh/examples/net/forceDirected#forceConstrainedInRect

**Comment by Yanyan-Wang** [comment]
> @Yanyan-Wang 请问gForce能设置clustring，clusterFociStrength这些参数吗，我这边的业务期望能达到这样的效果
> ![image](https://user-images.githubusercontent.com/48909573/123926276-4f288000-d9be-11eb-8bef-8b5cbca7bbd6.png)

https://g6.antv.vision/zh/docs/api/graphLayout/gforce#layoutcfggetcenter

**Comment by javaNaruto** [comment]
> > @Yanyan-Wang 请问gForce能设置clustring，clusterFociStrength这些参数吗，我这边的业务期望能达到这样的效果
> > ![image](https://user-images.githubusercontent.com/48909573/123926276-4f288000-d9be-11eb-8bef-8b5cbca7bbd6.png)
> 
> https://g6.antv.vision/zh/docs/api/graphLayout/gforce#layoutcfggetcenter

能给一个示例吗，我自己调参数始终达不到那个效果，我想要周围点均匀分布在中心点，整个图的绘图效果也接近
![image](https://user-images.githubusercontent.com/48909573/124057760-ad0aa580-da5a-11eb-96a8-d94da700ef04.png)
预期效果
![image](https://user-images.githubusercontent.com/48909573/124058024-299d8400-da5b-11eb-80d4-2196b356b69b.png)
![image](https://user-images.githubusercontent.com/48909573/124058101-4afe7000-da5b-11eb-8620-b1640dada665.png)

**Comment by Yanyan-Wang** [comment]
你那个图好像 linkDistance 太小了，全部挤在一起

**Comment by javaNaruto** [comment]
linkDistance调整了确实可以，但是点多的情况就会所有小集群点拥挤在一起，之前通过dgree来调整nodeStrength，但是图依然不够分散。是不是forceAtlas2算法才支持这种？之前我们调研的vis-network使用的是forceAtlas2,绘图效果就是这样，但是在g6的gForce中始终调不出这样的效果
![image](https://user-images.githubusercontent.com/48909573/124101788-486b3d00-da92-11eb-9809-fbb911744b8a.png)

**Comment by Yanyan-Wang** [comment]
G6 现在也有 force atlas 2。你可以换成这个试试。每种力导向的力模型不一样，效果也会有所不同

**Comment by javaNaruto** [comment]
> G6 现在也有 force atlas 2。你可以换成这个试试。每种力导向的力模型不一样，效果也会有所不同

之前有调研过，配置参数不一样，绘图时图不会动态变化，而且不支持GPU。而且绘图效果也不和这个一致

**Comment by huangtangtang** [comment]
已解决

**Comment by palytoxin** [comment]
@huangtangtang 怎么解决的？
