### ISSUE TITLE
image节点添加状态state

### ISSUE THREAD

**Issue by javaNaruto** [antvis/G6#2974]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在图中同时存在普通节点和image节点时，选普通节点和image的节点有同样的选中效果

### What does the proposed API look like?
例如选中：imageNode.setState('selected', true)

**Comment by Yanyan-Wang** [comment]
因为 image 图形没有描边和填充色，要达到类似效果可能需要自定义节点，给 image 后面再加一个 rect。不过你也可以设置 nodeStateStyles 的 selected 为透明度变化、大小变化等 image 图形有的样式

**Comment by javaNaruto** [comment]
目前已修改为icon来添加节点图标，感谢解答

**Comment by Yanyan-Wang** [comment]
好的。先关闭了
