### ISSUE TITLE
执行graph.read()后，canvas的监听事件全部失效

### ISSUE THREAD

**Issue by tuchongyang** [antvis/G6#2977]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://tuchongyang.github.io/g6-demo](https://tuchongyang.github.io/g6-demo)

### Steps to reproduce
监听事件canvas:mousedown开始能执行，当执行完changeData后mousedown事件就失效了。
```
const graph = ref({})
        onMounted(()=>{
            graph.value = getGraph()
            graph.value.on('canvas:mousedown',(e)=>{
              alert('canvas mousedown')
            })
        })
        const changeData = ()=>{
            const data = {
              nodes: [
                { id: 'node1', label: 'node1', },
                { id: 'node2', label: 'node2', },
              ],
              edges: [
                { source: 'node1', target: 'node2', },
              ],
            };
            graph.value.read(data);
        }
```

| Environment | Info |
|---|---|
| g6 | 4.3.3 |
| System | windows10 |
| Browser | 91.0.4472.114 |

**Comment by tuchongyang** [comment]
vue版本是3.0。测试过node和edge的事件都正常，唯独canvas失效，包括click、contextmennu等

**Comment by Yanyan-Wang** [comment]
用 graph.changeData() 代替 read 呢

**Comment by tuchongyang** [comment]
初始没有数据时，直接用changeData会报错。
先用render，后用changeData，canvas的事件一样的失效了。

已更新到[测试案例](https://tuchongyang.github.io/g6-demo)

**Comment by Yanyan-Wang** [comment]
第一次渲染要用 read 呀，后面更新数据用 changeData。你的 demo 我看不到代码

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。

**Comment by tuchongyang** [comment]
@nulltrue 没有解决，我后来换了一种方案，切换数据后，重新初始化整个graph

**Comment by archersado** [comment]
碰巧也遇到了这个问题，楼上应该是用了 vue 的响应式对象，在下面这一行判断的时候，canvas 对象被 proxy 包裹了，导致逻辑没进去

https://github.com/antvis/G6/blob/master/packages/pc/src/graph/controller/event.ts#L135

**Comment by Alduin-Y** [comment]
> 碰巧也遇到了这个问题，楼上应该是用了 vue 的响应式对象，在下面这一行判断的时候，canvas 对象被 proxy 包裹了，导致逻辑没进去
> 
> https://github.com/antvis/G6/blob/master/packages/pc/src/graph/controller/event.ts#L135

您好 我也遇到这个问题了 确实是canvas对象被proxy包裹了，我是将graph存在vuex里面，再取出来用就是proxy类型了，解决方法就是将graph以参数的形式在函数之间传递，它就还是object .....不过我想求教一下有没有更好的方法解决? 谢谢

**Comment by archersado** [comment]
> > 碰巧也遇到了这个问题，楼上应该是用了 vue 的响应式对象，在下面这一行判断的时候，canvas 对象被 proxy 包裹了，导致逻辑没进去
> > https://github.com/antvis/G6/blob/master/packages/pc/src/graph/controller/event.ts#L135
> 
> 您好 我也遇到这个问题了 确实是canvas对象被proxy包裹了，我是将graph存在vuex里面，再取出来用就是proxy类型了，解决方法就是将graph以参数的形式在函数之间传递，它就还是object .....不过我想求教一下有没有更好的方法解决? 谢谢

在使用之前 toRaw 一下，确保是原始对象，可以封装一下，用个计算属性，我们这边由于封装了一层，放在 provide/inject 里了

**Comment by Alduin-Y** [comment]
> > > 碰巧也遇到了这个问题，楼上应该是用了 vue 的响应式对象，在下面这一行判断的时候，canvas 对象被 proxy 包裹了，导致逻辑没进去
> > > https://github.com/antvis/G6/blob/master/packages/pc/src/graph/controller/event.ts#L135
> > 
> > 
> > 您好 我也遇到这个问题了 确实是canvas对象被proxy包裹了，我是将graph存在vuex里面，再取出来用就是proxy类型了，解决方法就是将graph以参数的形式在函数之间传递，它就还是object .....不过我想求教一下有没有更好的方法解决? 谢谢
> 
> 在使用之前 toRaw 一下，确保是原始对象，可以封装一下，用个计算属性，我们这边由于封装了一层，放在 provide/inject 里了

感谢 非常好用 啊哈哈👍

**Comment by LeeYuze** [comment]
![Image](https://github.com/user-attachments/assets/f9eb5512-a991-4740-8a4d-944774ace63c)这么写可以继续监听canvas事件，太强了楼上的大佬们

**Comment by LeeYuze** [comment]
太强了，只要把Graph实例不放在vue3的响应式里就行

**Comment by hustcc** [comment]
不如封装个 vue 组件开源出来，发到 npm， 一次性避坑～
