### ISSUE TITLE
重新install之后，怎么无法用G6了？

### ISSUE THREAD

**Issue by evanoxu** [antvis/G6#2978]
![image](https://user-images.githubusercontent.com/3927965/123074603-09156e80-d44a-11eb-97f8-3b96c499674d.png)

**Comment by evanoxu** [comment]
@mxz96102 '@antv/g6-react-node': 1.4.0 版本是正常的吗？

**Comment by Yanyan-Wang** [comment]
哪个版本升级到哪个版本？请提供一下复现在线 demo

**Comment by evanoxu** [comment]
> 哪个版本升级到哪个版本？请提供一下复现在线 demo

@Yanyan-Wang

**Comment by evanoxu** [comment]
@Yanyan-Wang

**Comment by mxz96102** [comment]
发了个1.4.1 严格的从g6和g6-core引入类型，看看能不能解决了

**Comment by evanoxu** [comment]
> 发了个1.4.1 严格的从g6和g6-core引入类型，看看能不能解决了

正常了。

**Comment by evanoxu** [comment]
@mxz96102 试着重新tnpm install “g6” 与 “g6-react-node” 还是不行呀，还是报了上图的错。
![image](https://user-images.githubusercontent.com/3927965/124058442-f6a7c000-da5b-11eb-87f0-9f32de9aec6d.png)

当前项目上G6版本：
"@antv/g6": "4.3.3",
"@antv/g6-react-node": "1.4.1",

**Comment by mxz96102** [comment]
如果这样建议tnpm update，我在codesandbox写了个例子感觉没有遇到你的问题，https://codesandbox.io/s/g6-react-node-3jrs5

**Comment by evanoxu** [comment]
> 如果这样建议tnpm update，我在codesandbox写了个例子感觉没有遇到你的问题，https://codesandbox.io/s/g6-react-node-3jrs5

能整成TreeGraph吗？我试着改成TreeGraph，一堆报错。

**Comment by Yanyan-Wang** [comment]
> > 如果这样建议tnpm update，我在codesandbox写了个例子感觉没有遇到你的问题，https://codesandbox.io/s/g6-react-node-3jrs5
> 
> @mxz96102 神奇，我试着在例子（ https://codesandbox.io/s/g6-react-node-forked-1cmsl?file=/src/index.js ）里 获取getBBox 是都正常的。。。
> 为啥放到项目里就报错了。
> ![image](https://user-images.githubusercontent.com/3927965/124064664-d1b94a00-da67-11eb-994e-e6f070d05583.png)

确认一下 node_moduels 里的版本，删干净再装下看

**Comment by evanoxu** [comment]
更新到以下版本：
"@antv/g6": "4.3.4",
"@antv/g6-react-node": "1.4.2",

终于正常了。
