### ISSUE TITLE
G6 graph toFullDataUrl 导出图片 图片质量不清晰

### ISSUE THREAD

**Issue by sanmuw** [antvis/G6#2979]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我们使用G6做了跟学习脑图的案件，里面有图片导出功能，可是图片导出的质量不高，不清晰。

### What does the proposed API look like?
    const imageConfig = {
      backgroundColor: '#fff4bf',
    };    
graphRef.current.toFullDataURL(
      (res: string) => {
        // app的一个分享微信的封装API
        browserShareActivityCommon({
          shareType: 'image',
          thumbUrl: res,
          thumbType: 'base64Image',
          platforms: [1],
        });
      },
      'image/jpeg',
      imageConfig, 
    );

**Comment by Yanyan-Wang** [comment]
你的图范围很大么？

试一下实例化 graph 的时候把 pixelRatio 设置 2 或者 3 看看

**Comment by sanmuw** [comment]
@Yanyan-Wang 
首先先谢谢你的解答。
是的范围很大，pixelRatio 我都试过了
export const graphConfig = {
  pixelRatio: 2,
  modes: {
    default: [
      { type: 'drag-canvas', allowDragOnItem: true },
      { type: 'zoom-canvas', sensitivity: 1, minZoom: 0, maxZoom: 1.5 },
    ],
  },
  defaultNode: {
    type: 'rect',
    size: 26,
    anchorPoints: [
      [0, 0.5],
      [1, 0.5],
    ],
  },
  defaultEdge: {
    type: 'cubic-horizontal',
    style: {
      stroke: '#E7C082',
    },
  },
  layout: {
    type: 'compactBox',
    direction: 'H',

    getHeight: ({ type }: { type: string }) => {
      if (type === 'courseNode') {
        return 60;
      }
      if (type === 'chapterNode') {
        return 35;
      }

      return 270;
    },
    getWidth: ({ type }: { type: string }) => {
      if (type === 'courseNode') {
        return 101;
      }
      if (type === 'chapterNode') {
        return 79;
      }
      return 245;
    },
    // getVGap: () => 0,
    getHGap: () => 90,
  },
};

**Comment by zhongyue2332** [comment]
貌似是默认取了window.devicePixelRatio，而且配置项pixelRatio也不生效，可以暂时用这个方法：
`getImg() {
      window.oldRatio = window.devicePixelRatio;
      window.devicePixelRatio = 2;
      this.graph.downloadFullImage("导出图片", "image/png", {
        padding: [30, 15, 15, 15]
      });
      setTimeout(() => {
        window.devicePixelRatio = window.oldRatio;
      }, 100);
    }`

**Comment by sanmuw** [comment]
> 貌似是默认取了window.devicePixelRatio，而且配置项pixelRatio也不生效，可以暂时用这个方法：
> 
> ```
> getImg() {
>       window.oldRatio = window.devicePixelRatio;
>       window.devicePixelRatio = 2;
>       this.graph.downloadFullImage("导出图片", "image/png", {
>         padding: [30, 15, 15, 15]
>       });
>       setTimeout(() => {
>         window.devicePixelRatio = window.oldRatio;
>       }, 100);
> }
> ```

@zhongyue2332 你试过了？

**Comment by zhongyue2332** [comment]
> > 貌似是默认取了window.devicePixelRatio，而且配置项pixelRatio也不生效，可以暂时用这个方法：
> > ```
> > getImg() {
> >       window.oldRatio = window.devicePixelRatio;
> >       window.devicePixelRatio = 2;
> >       this.graph.downloadFullImage("导出图片", "image/png", {
> >         padding: [30, 15, 15, 15]
> >       });
> >       setTimeout(() => {
> >         window.devicePixelRatio = window.oldRatio;
> >       }, 100);
> > }
> > ```
> 
> @zhongyue2332 你试过了？

是的，我就是遇到同样的问题，这个方法导出后的图片文件更大，清晰度也有提高
