### ISSUE TITLE
元素很多时 downloadFullImage 导出图片失败

### ISSUE THREAD

**Issue by csspmini-web** [antvis/G6#2980]
1.如果是报错导致的下载失败，控制台会有以下信息：
Uncaught (in promise) RangeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': Out of memory at ImageData creation

2.如果下载的图片无法打开，一般是因为 toDataURL 返回 的值 是 `'data:,'`

```js
dataURL = canvasDom.toDataURL(type); 
```

**Comment by xgxm13** [comment]
1的问题有解决吗，我也遇到了，就是数据很多的情况下才有这个报错
![image](https://user-images.githubusercontent.com/26291172/123927274-408e9880-d9bf-11eb-810b-0f307d06364f.png)
![image](https://user-images.githubusercontent.com/26291172/123927385-6156ee00-d9bf-11eb-9928-3a9d5c4abb88.png)

**Comment by Yanyan-Wang** [comment]
数据量太大时导致 canvas API 调用内存不足。尝试先 fitView 再 download 呢

**Comment by xgxm13** [comment]
> fitView

这个不行，但是我把画布缩小到一定比例不会报错了
`
graph.zoomTo(0.35, {
      x: 800,
      y: 100
    });
`
这样搞也有坏处，就是下载的图不太清晰

**Comment by Yanyan-Wang** [comment]
graph.getCanvasBBox() 打印看下有多大？

**Comment by csspmini-web** [comment]
【最终发现了多种不同情况图片下载失败或异常】

情况一：
未能对“CanvasRenderingContext2D”执行“getImageData”：创建ImageData时内存不足（这种比较易懂）

情况二：
数据量大时也能下载图片，也没有【情况一】中的报错，但是下载的图片内容为空，断点查看是发现 G6 内部最终处理后的图片内容  居然返回了 'data:,' 

情况三：
发现某些元素中含有  NaN 的值，导致下载不了图片，也没有任何报错，G6 内部也没有 警告日志

情况四：
数据量大时可以下载图片，但是会出现某些 node 节点【图标】会丢失，如果把zoom 改小，或者把图片质量降低，图片内容就不会有节点丢失

**Comment by csspmini-web** [comment]
> > fitView
> 
> 这个不行，但是我把画布缩小到一定比例不会报错了
> `graph.zoomTo(0.35, { x: 800, y: 100 });`
> 这样搞也有坏处，就是下载的图不太清晰

fitView 没有用的
