### ISSUE TITLE
Last selected node and its relations to be activated after expand collapse of combo

### ISSUE THREAD

**Issue by ankitachdhr145** [antvis/G6#2981]
We want to call activate relations for a last selected node even after user expands or collapse the combo.

this.graph.on('afteractivaterelations', (e) => {     
      if(e.item._cfg.type === "node"){
        this.nodeSelected = e.item;
      }
 });

I have stored the last selected node item in this.nodeSelected. Now when user expands or collapse a combo we want all the relations activated for the last selected node. So how we can activate relations for this globally selected node item after expand/collapse of combo?

Version: 4.3.3

**Comment by Yanyan-Wang** [comment]
If the node is a descendant of the combo, the related edges will be hidden and virtual edges connecting to the combo will be created while collapsing the combo. If you want to activate the corresponding virtual edges, you have to set the activate state for the edges that related to the manipulated combo, try to call `combo.getEdges()`. 

When expanding the combo, the virtual edges will be destroyed and the original edges will be restored, `node.getEdges()` returns the related edges and you could set them to activate state.

**Comment by ankitachdhr145** [comment]
Thanks fir the reply I will try do it.
