### ISSUE TITLE
v4.3.3 contextmenu 配置 trigger:'click' 无效

### ISSUE THREAD

**Issue by cherrow** [antvis/G6#2982]
配置为左键单击打开 (trigger: 'click') 后没有生效，配置为右键单击 (trigger: 'contextmenu') 是生效的

在官网示例中即可复现：https://g6.antv.vision/zh/examples/tool/contextMenu

![image](https://user-images.githubusercontent.com/25573811/123255330-4b11e380-d522-11eb-82af-50611833ed67.png)

**Comment by cherrow** [comment]
可以看到 contextmenu 的元素已经创建，但是单击并没有改变 visibility 的属性值
![image](https://user-images.githubusercontent.com/25573811/123256446-8e208680-d523-11eb-911d-7a8c64764764.png)

**Comment by Yanyan-Wang** [comment]
感谢报告问题，下个小版本将会修复

**Comment by Yanyan-Wang** [comment]
fixed by 4.3.4
