### ISSUE TITLE
G6 updateLayout 不能更新 自定义布局 

### ISSUE THREAD

**Issue by rogerluo410** [antvis/G6#2983]
自定义布局 了一个布局， like: flow,
初始化使用是没问题的，
先 updateLayout到一个内建的布局，例如， grid,
再 updateLayout到自定义布局 flow， 就不成功了。。

请问是什么问题？

**Comment by Yanyan-Wang** [comment]
请给出最小在线复现 demo

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
