### ISSUE TITLE
设置自定义combo的collapsed为true以后，最开始进入时依然表现为展开

### ISSUE THREAD

**Issue by CathyZYF** [antvis/G6#2984]
[codepen案例](https://codepen.io/cathyzyf/pen/ZEegapQ)

如案例中所示，combo是自定义的，并且在combo数据中设置了collapsed为true，但在每次刷新页面时，combo首先表现为展开，然后才会收缩，页面在node较多时会出现卡顿现象

期望效果： 若数据设置了collapsed为true，在渲染时应该直接渲染为关闭状态，而不是从展开过渡到关闭

**Comment by Yanyan-Wang** [comment]
感谢报告问题，可以先这样处理：

在 render 之前先设置节点不可见
data.nodes.forEach(node => {
  node.visible = false;
})

不过我看到你 demo 中的版本号是 4.1.3，换成 4.3.3 不会出现加上上述代码后节点位置异常问题

**Comment by CathyZYF** [comment]
> 感谢报告问题，可以先这样处理：
> 
> 在 render 之前先设置节点不可见
> data.nodes.forEach(node => {
> node.visible = false;
> })
> 
> 不过我看到你 demo 中的版本号是 4.1.3，换成 4.3.3 不会出现加上上述代码后节点位置异常问题

谢谢解答，我们现在的解决方法就是给对应的nodes加上visible=false，但加上后发现与节点相连的链路依然存在😂,然后我们给对应的链路也设置了visible=false，这样处理过后，发现 初始为collapse的combo在 最初加载 时仍然有一个反应的过程，延时大概3秒才能正确加载出combo之间的链路，这些都是数据量在500个nodes时出现的（我们的combo和node都是自定义的）

**Comment by Yanyan-Wang** [comment]
是的，因为要正确计算出 combo 的位置，需要一开始有节点的位置，所以初次渲染的时候会先渲染了一下节点，然后再收缩 combo。刚发的 4.3.4 把这个时间缩短了一些，你试试看会不会好一点。但是没有完全去除。

**Comment by CathyZYF** [comment]
> 是的，因为要正确计算出 combo 的位置，需要一开始有节点的位置，所以初次渲染的时候会先渲染了一下节点，然后再收缩 combo。刚发的 4.3.4 把这个时间缩短了一些，你试试看会不会好一点。但是没有完全去除。

谢谢！

**Comment by csspmini-web** [comment]
如果无论有没有子节点， combo 的大小/位置都不强制根据 子节点来计算位置和尺寸就好了
