### ISSUE TITLE
图数据导出不同格式

### ISSUE THREAD

**Issue by songhn233** [antvis/G6#2985]
支持导出和导入不同格式的图数据，例如 GraphML、GEXF 等格式。

官方排期 issue 中有类似的描述，如果目前优先级不高的话我可以完成一部分格式。

不知道是直接放进 g6-pc 里还是拆成一个单独的库？

**Comment by Yanyan-Wang** [comment]
赞！感谢感谢，可以写在 g6-core 的 util 里面，单独做一个数据处理的 util 文件

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
