### ISSUE TITLE
自定义边展示问题

### ISSUE THREAD

**Issue by 15279622069** [antvis/G6#2987]
G6版本:3.0.5;

G6.registerEdge('line-arrow', {
    draw(cfg, group) {
        const { startPoint, endPoint } = cfg
        const keyShape = group.addShape('path', {
            attrs: {
                path: [
                    ['M', startPoint.x, startPoint.y],
                    ['L', endPoint.x / 3 + 2 / 3 * startPoint.x, startPoint.y],
                    ['L', endPoint.x / 3 + 2 / 3 * startPoint.x, endPoint.y],
                    ['L', endPoint.x, endPoint.y]
                ],
                stroke: '#BBB',
                lineWidth: 1,
                startArrow: {
                    path: 'M 6,0 L -6,-6 L -3,0 L -6,6 Z',
                    d: 6
                },
                endArrow: {
                    path: 'M 6,0 L -6,-6 L -3,0 L -6,6 Z',
                    d: 6
                },
                className: 'edge-shape'
            }
        });
        return keyShape
    }
});

![image](https://user-images.githubusercontent.com/35129628/123599779-8c5b0980-d828-11eb-9f04-cb63ff23ddde.png)

**Comment by Yanyan-Wang** [comment]
因为 endArrow startArrow 的方向取的是边两端位置上的切线斜率，你这里两头都是横着的线，所以箭头也是躺着的

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
