### ISSUE TITLE
Graph initiates with overlapping combos

### ISSUE THREAD

**Issue by bsansone** [antvis/G6#2988]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gifted-stonebraker-pelp0)

### Steps to reproduce
Load the graph, should happen right away. Screenshot attached.

| Environment | Info |
|---|---|
| g6 | 4.3.3 |
| System | Linux |
| Browser | Chrome |

---
I'm hoping that when using combos, I am able to create a default, good looking graph layout, but am unable to do so because of this bug.

Screenshot:

![image](https://user-images.githubusercontent.com/16868336/123707797-cbee1980-d859-11eb-934d-876e6a67f780.png)

**Comment by Yanyan-Wang** [comment]
Thanks for reporting, I will try to fix it in next small version

**Comment by Yanyan-Wang** [comment]
fixed by 4.3.4

**Comment by bsansone** [comment]
@Yanyan-Wang Thanks for the quick fix! I just noticed another bug in my example sandbox above after upgrading to 4.3.4. After expanding the combo `aaa`, if you move the combo while expanded, after releasing your mouse drag, the combo size will shrink smaller than the area made by the nodes within. Want me to make a new issue for this?

# Before dragging:
![image](https://user-images.githubusercontent.com/16868336/124154081-a729ba00-da84-11eb-8c9d-798c985bc9ec.png)

# After dragging:
![image](https://user-images.githubusercontent.com/16868336/124154025-98db9e00-da84-11eb-9ec9-879290a17e23.png)
