### ISSUE TITLE
drag-node模式下，自定义节点不能拖动，@antv/g6 v4.3.3

### ISSUE THREAD

**Issue by 775146061** [antvis/G6#2989]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sleepy-microservice-oysck?file=/src/index.js)

### Steps to reproduce
点击拖动节点蓝色区域能拖动，而点击节点文字区域则不能拖动，请问如何解决这种情况，使点击文字区域也能拖动。

| Environment | Info |
|---|---|
| g6 | 4.3.3 |
| System | win10 |
| Browser | 谷歌91.0.4472.124 |

**Comment by songhn233** [comment]
```jsx
<text draggable={true} style={{ textAlign: 'center', marginTop: -20, fill: '#282E3B' }} name='label'>角色</text>  
```
增加 draggable [配置](https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/custom-node#%E7%BB%98%E5%88%B6%E5%9B%BE%E5%BD%A2)
