### ISSUE TITLE
tree 的实例继承了 zoom()方法，但是没有继承getZoom方法

### ISSUE THREAD

**Issue by EthanWan** [antvis/g6#299]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by EthanWan** [comment]
2.0 是可以的  1.2.7 不可以。请问1.2.7中有什么方法可以拿到当前zoom值

**Comment by TomHuangCN** [comment]
tree.getMatrix()[0]
