### ISSUE TITLE
'position:relative' on DOM node causes the node to positioned incorrectly in Safari

### ISSUE THREAD

**Issue by 1994benc** [antvis/G6#2990]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/distracted-northcutt-0mmw3?file=/src/index.js)

### Steps to reproduce
Add style position:relative to a html element of a Dom node
the element is positioned incorrectly in Safari

This does not appear to be an issue with other browsers

| Environment | Info |
|---|---|
| g6 | 4.3.3 |
| System | macOS Big Sur 11.4 |
| Browser | Safari 14.1.1 |

**Comment by Yanyan-Wang** [comment]
That is strange... @xiaoiver please take a look.

P.S. Try react-node or customizing node with JSX with SVG renderer
https://g6.antv.vision/en/docs/manual/middle/elements/nodes/jsx-node/

**Comment by 1994benc** [comment]
@Yanyan-Wang @xiaoiver 
FYI, this could be related to this foreignObject bug in Safari https://bugs.webkit.org/show_bug.cgi?id=23113
We haven't come up with a workaround though. Any ideas?

**Comment by Yanyan-Wang** [comment]
![image](https://user-images.githubusercontent.com/29593318/124229243-e2d58a00-db3f-11eb-9361-3633b53414ef.png)

LOL. The bug looks exist for a long time. 

But, what is the `position:relative` for? If you want to move the div, try to assign x and y for the "dom" shape, e.g.:

```
const shape = group.addShape("dom", {
      attrs: {
        width: cfg.size[0],
        height: cfg.size[1],
        x: 10,
        y: 20,
        html: `...`
      },
      draggable: true
    });
```

**Comment by 1994benc** [comment]
Hi the reason we need this is to be able to reuse existing components as nodes.
Do you have any plans for a workaround in G6? Or maybe we should update the documentation so people are clearly aware of this?

**Comment by Yanyan-Wang** [comment]
Yes, Thanks, I have added it into the docs: https://g6.antv.vision/en/docs/api/shapeProperties#dom-svg
