### ISSUE TITLE
调用changeData后，节点停在布局的初始位置

### ISSUE THREAD

**Issue by javaNaruto** [antvis/G6#2993]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/summer-night-ry1cg?file=/index.js)

### Steps to reproduce
这个链接的demo没体现出来，但是在项目中确实出现过问题，如截图所示：

在初始图中有部分节点，双击某个节点扩展出新的节点和边，调用changeData(data),data是旧数据和新数据合并的新数据，有时会出现新的节点停在布局的初始位置，但出现的频率比较高，布局使用的是gForce,启用GPU布局。

| Environment | Info |
|---|---|
| g6 | 4.3.3 |
| System | - |
| Browser | - |
![0a49558cd30bad419a73d90bb235e888](https://user-images.githubusercontent.com/48909573/123923070-3b2f4f00-d9bb-11eb-910c-3c39b74b659f.png)

**Comment by Yanyan-Wang** [comment]
手动调用一下 graph.layout() 试试

**Comment by javaNaruto** [comment]
依旧有这样的情况，但是不是每次都出现的，我多次双击扩展节点就回遇到这样的情况，有时一两次就出现

**Comment by Yanyan-Wang** [comment]
可能和异步计算有关，尝试在 graph.on('afterrender', e => {}); 里面调用 graph.layout()

**Comment by javaNaruto** [comment]
changeData之后并不会进入到afterrender事件，只有第一次调用graph.data()时进入该事件

**Comment by Yanyan-Wang** [comment]
哦哦，先试一下 setTimeout(() => {...}, 1000) 里面调用一下看，确定一下是否是异步计算的原因

**Comment by duyuntao** [comment]
我也出现了同样的问题

**Comment by Yanyan-Wang** [comment]
麻烦提供一下最小复现 demo，否则很难排查

**Comment by javaNaruto** [comment]
> 哦哦，先试一下 setTimeout(() => {...}, 1000) 里面调用一下看，确定一下是否是异步计算的原因

还是会有这样的情况

**Comment by Yanyan-Wang** [comment]
如果没开 GPU 就不会出现该情况是么

**Comment by javaNaruto** [comment]
> 如果没开 GPU 就不会出现该情况是么

对的，我观察了一下，最初节点的位置就如图中一样横排出现，然后被力拉走了之后运动到最终的位置

**Comment by duyuntao** [comment]
好像worker和GPU同时开启的时候出现这个问题

**Comment by Yanyan-Wang** [comment]
切换之后把节点数据打出来看下，那些节点数据里面 x y 是啥样的，是一横排的坐标还是正常的坐标

**Comment by javaNaruto** [comment]
> 切换之后把节点数据打出来看下，那些节点数据里面 x y 是啥样的，是一横排的坐标还是正常的坐标

是一横排的坐标，y坐标是一样的

**Comment by Yanyan-Wang** [comment]
刚发了一个 @antv/g6-pc@0.3.5-beta，node_modules 删掉 @antv/g6-pc@0.3.5，单独安装 @antv/g6-pc@0.3.5-beta 试试看。不确定是否能够解决，因为没法复现我这里没办法测试

**Comment by javaNaruto** [comment]
> 刚发了一个 @antv/g6-pc@0.3.5-beta，node_modules 删掉 @antv/g6-pc@0.3.5，单独安装 @antv/g6-pc@0.3.5-beta 试试看。不确定是否能够解决，因为没法复现我这里没办法测试

还有个情况之前没有提到，双击调用的是changeData，出现横排之后的每一次双击，新的节点都会横排排列

**Comment by javaNaruto** [comment]
> 刚发了一个 @antv/g6-pc@0.3.5-beta，node_modules 删掉 @antv/g6-pc@0.3.5，单独安装 @antv/g6-pc@0.3.5-beta 试试看。不确定是否能够解决，因为没法复现我这里没办法测试

更新了@antv/g6-pc@0.3.5，依旧会出现这个问题

**Comment by javaNaruto** [comment]
我的nodeStrength设置的很大，可能跟这个有影响，但是我觉得既然不开GPU的情况没有出现，那我设置值再大也不应该影响布局

**Comment by void0720** [comment]
我也遇到这个问题了，横着排成一行，而且只要出现一次，后面的就都会排成一行了

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于我们没有得到可追踪复现的 demo，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
