### ISSUE TITLE
项目中使用workerEnabled控制台报错，@antv/g6 v4.3.3

### ISSUE THREAD

**Issue by javaNaruto** [antvis/G6#2994]
![1bf2163a903d9e45b7826ca23a638805](https://user-images.githubusercontent.com/48909573/123924197-4b93f980-d9bc-11eb-9abb-387b41cf15c8.png)

**Comment by javaNaruto** [comment]
在gForce布局参数中设置workerEnabled: true，控制台报此错误

**Comment by Yanyan-Wang** [comment]
你是在内网环境使用的么

**Comment by javaNaruto** [comment]
是的

**Comment by Yanyan-Wang** [comment]
那可以把这个地址的文件下载下来放在内网地址传给图实例化的时候的 layout 的 importScripts

https://unpkg.com/@antv/layout@latest/dist/layout.min.js

**Comment by javaNaruto** [comment]
好的，我试一下

**Comment by Yanyan-Wang** [comment]
解决了没有

**Comment by javaNaruto** [comment]
> 解决了没有

这样引入意味着我要手动new一个layout对象吗？

**Comment by Yanyan-Wang** [comment]
> > 解决了没有
> 
> 这样引入意味着我要手动new一个layout对象吗？

不用啊，只不过是替换了一下外网连接而已

**Comment by JiangGeGe123** [comment]
> 

layout: {
          ...G6MapLayout.force,
          workerEnabled: true,
          nodeSpacing: mapData?.layout?.nodeSpacing || 20,
          nodeSize: (d: any) => {
            return d.size;
          },
          importScripts:'../../layout.min.js'
        },
这样吗？

**Comment by weblaowu** [comment]
> > 
> 
> layout: { ...G6MapLayout.force, workerEnabled: true, nodeSpacing: mapData?.layout?.nodeSpacing || 20, nodeSize: (d: any) => { return d.size; }, importScripts:'../../layout.min.js' }, 这样吗？
> 
> 还是不行呢

解决了吗？

**Comment by Yanyan-Wang** [comment]
尝试把 layout.min.js 传到内网环境的 cdn 上来引用而不是本地文件

**Comment by Arthre** [comment]
> 那可以把这个地址的文件下载下来放在内网地址传给图实例化的时候的 layout 的 importScripts
> 
> https://unpkg.com/@antv/layout@latest/dist/layout.min.js

我试过用 importScripts 来设置本地文件，但是它没有效果。
当我把 importScripts 改成 workerScriptURL 却可以！
[示例](url https://codesandbox.io/s/g6-7m4zws?file=/src/App.vue)

**Comment by Yanyan-Wang** [comment]
嗷，应该是 `workerScriptURL` ，记错了……
