### ISSUE TITLE
g6 canvas带滚动条的自适应怎样实现？

### ISSUE THREAD

**Issue by yanghuixia** [antvis/G6#2995]
对于全屏的canvas或者带有滚动条的canvas，都能实现缩放窗口时里面的canvas能自适应窗口大小；
缩放窗口时调用resize函数，里面添加changesize(width,height),高度怎样去动态计算呢？有滚动条的canvas

**Comment by Yanyan-Wang** [comment]
查一下怎么获取 DOM 的高度

**Comment by Yanyan-Wang** [comment]
![image](https://user-images.githubusercontent.com/29593318/124093118-21107200-da8a-11eb-8755-6177cb8aee54.png)

**Comment by yanghuixia** [comment]
谢谢回答，我再把我的问题说清楚一下，现在我有很多包含x,y坐标的node，但是全屏显示的话node样式很小，不满足我的需求，所以我就自己先去计算heightMin heightMax，也就是全部节点的y坐标的最大最小值，他们的差值就是我想要的带有滚动条的实际的高。
<img width="295" alt="Screen Shot 2021-07-02 at 2 51 44 PM" src="https://user-images.githubusercontent.com/43085189/124233070-0818c700-db45-11eb-9b66-36e82484518f.png">
然后我初始的高度直接取
<img width="521" alt="Screen Shot 2021-07-02 at 3 01 52 PM" src="https://user-images.githubusercontent.com/43085189/124234309-71e5a080-db46-11eb-8382-a1fa9cf39a51.png">
我用比例计算的缩放比例
我在resize的时候也用这样的方法，可以实现缩放的自适应，但是有时会在缩放后刷新一下页面，上下会留白，原因是高度又取了初始高度。这样的效果不好，所以想问下，对于这种带滚动条的自适应页面，g6有没有好的处理方式呢？
