### ISSUE TITLE
drag-canvas 和 zoom-canvas的enableOptimize兼容有问题

### ISSUE THREAD

**Issue by duyuntao** [antvis/G6#2996]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/delicate-lake-hwe56)

### Steps to reproduce
1 缩放canvas 隐藏非 keyShape
2 拖拽canvas 之前隐藏被放出

| Environment | Info |
|---|---|
| g6 | 4.3.3 |
| System | - |
| Browser | - |

**Comment by Yanyan-Wang** [comment]
缩放过程中隐藏，缩放完成后会显示出来。拖拽也是一样。看 demo 没有问题呀

**Comment by duyuntao** [comment]
> 缩放过程中隐藏，缩放后会显示出来。拖拽也一样。看演示没有问题呀

缩放到0.5以下的时候隐藏并且不会显示出来，因为设置了optimizeZoom，但是拖拽后打破了optimizeZoom的设置

**Comment by Yanyan-Wang** [comment]
感谢报告，下个小版本将会修复

**Comment by Yanyan-Wang** [comment]
fixed by 4.3.4
