### ISSUE TITLE
Add local file images into nodes and combos 

### ISSUE THREAD

**Issue by brishable** [antvis/G6#2998]
I have searched on the issues page and couldn't find this issue.

When Adding a shape to the combo, an image specifically we can do this.

```
group.addShape('image', {
  attrs: {
    x: 0,
    y: 0,
    img: 'https://g.alicdn.com/cm-design/arms-trace/1.0.155/styles/armsTrace/images/TAIR.png',
  },
  // must be assigned in G6 3.3 and later versions. it can be any value you want
  name: 'image-shape',
});

```
Is it possible to set the src of the image to a local file? Something like 

`img: './image.png'`

**Comment by Yanyan-Wang** [comment]
You could use some tool to transform the local image into base64 and configure `img` with the base64 value

**Comment by brishable** [comment]
That worked, thank you.
