### ISSUE TITLE
[Example] 超长文本，hover展示完整内容并提供复制功能

### ISSUE THREAD

**Issue by WontonCat** [antvis/G6#2999]
### Description

超长文本进行缩略处理后，用户无法查看完整内容，且render为canvas时文本无法复制。

在该例子中，鼠标移入文本区域则显示该区域文本的完整内容，并出现LOGO，点击LOGO即可实现复制功能。

### Implementation

https://codesandbox.io/s/modest-bardeen-nq7mf?file=/index.js

**Comment by Yanyan-Wang** [comment]
赞！感谢！

**Comment by mxz96102** [comment]
我们会尽快整理收录进交互案例

**Comment by Yanyan-Wang** [comment]
已加入官网 DEMO，并在 demo 代码中 @ 你啦，再次感谢

https://g6.antv.vision/zh/examples/item/label#copyLabel
