### ISSUE TITLE
自定义节点中设置stateStyles不生效

### ISSUE THREAD

**Issue by pollux2015** [antvis/G6#3002]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/agitated-diffie-7xy8e?file=/src/index.js)

### Steps to reproduce
1. registerBehavior 自定义了一个behavior 在onNodeClick时候graph.setItemState(item, 'active', true);
2. registerNode 自定义节点, 在配置的options:{} 中设置了active的样式， 但是没有生效
3. 具体请看codesandbox例子

| Environment | Info |
|---|---|
| g6 | 4.3.4 |
| System | mac |
| Browser | 90.0.4430.212 |

![image](https://user-images.githubusercontent.com/11935278/124083454-721b6880-da80-11eb-91c6-4e76b39b46f2.png)
![image](https://user-images.githubusercontent.com/11935278/124083492-80698480-da80-11eb-9d44-51294e197b5b.png)
![image](https://user-images.githubusercontent.com/11935278/124083511-87909280-da80-11eb-9927-e33a5e3f3bfe.png)

**Comment by Yanyan-Wang** [comment]
要继承一下内置节点哈，否则设置状态的方法没有继承下来，就不会被运行到了。 registerNode 第三个参数代表继承的内置节点，可以是 'single-node'（所有内置节点的基类） 或者 'circle' 等

**Comment by pollux2015** [comment]
@Yanyan-Wang 可以了 感激
