### ISSUE TITLE
树图和基本的图样可以一起用吗？或者树图怎么自定布局？或者基本的图可以实现折叠展开的功能吗？

### ISSUE THREAD

**Issue by QDSG** [antvis/G6#3004]
我现在有个需求就是有的节点可能没有线，但是有部分节点需要展开折叠的功能，但是两个图又不能在一张画布实现，现在就是很迷惑不知道该怎么弄，但是我试了一下好像树图的布局不支持自定义。。。也可能是我学艺不精。。。。

**Comment by Yanyan-Wang** [comment]
树图暂不支持自定义布局。可以自己计算需要收起来的节点，传给图的数据去掉这些点然后 graph.changeData。展开同理

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
