### ISSUE TITLE
在自定义节点draw方法中, group.addGroup().addShape() 创建的形状, stateStyles无法还原

### ISSUE THREAD

**Issue by pollux2015** [antvis/G6#3005]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/bold-fast-d6hlr)

### Steps to reproduce
1. 在draw里面新建一个shape  const leftGroup = group.addGroup({ id: "left-pie" }).addShape();
2. 自定义事件中设置为active graph.setItemState(item, "active", true);
3. registerNode 中配置 stateStyles 当active为true 样式生效
4. 移除active没有还原样式

** chrome报错 在 originStyle_1[p][key] 中无法找到对应的name的默认options **
** 直接创建 group.addShape(); 创建的没有问题 **
** group.addGroup({ id: "left-pie" }).addShape() 创建的有问题** 

| Environment | Info |
|---|---|
| g6 | 4.3.4 |
| System | mac |
| Browser | 90.0.4430.212 |

---
具体请查看demo
![image](https://user-images.githubusercontent.com/11935278/124100965-8025b500-da91-11eb-82a6-54932fd49346.png)

![image](https://user-images.githubusercontent.com/11935278/124101159-a8151880-da91-11eb-8cee-66667f45672d.png)

**Comment by Yanyan-Wang** [comment]
目前应该状态样式的设置只遍历到 group 下平铺的图形

**Comment by pollux2015** [comment]
好的，建议文档里面备注一下免得踩坑。。。

**Comment by Yanyan-Wang** [comment]
好的，谢谢建议

**Comment by Yanyan-Wang** [comment]
文档补充啦：https://g6.antv.vision/zh/docs/manual/middle/states/state#%E9%85%8D%E7%BD%AE-state-%E6%A0%B7%E5%BC%8F
