### ISSUE TITLE
G6的兼容性问题，ie上面无法正常渲染，

### ISSUE THREAD

**Issue by wangxiaoming-1997** [antvis/G6#3007]
vue项目，版本3.2.8

**Comment by wangxiaoming-1997** [comment]
![image](https://user-images.githubusercontent.com/59142297/124120468-65117000-daa6-11eb-88b2-6f2528544784.png)
![image](https://user-images.githubusercontent.com/59142297/124120530-75294f80-daa6-11eb-92f0-762d5d0735bf.png)
这是报错信息

**Comment by Yanyan-Wang** [comment]
https://g6.antv.vision/zh/docs/manual/FAQ/supportIE

还是不行的话建议尝试更新版本

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。

**Comment by lllllxt** [comment]
> https://g6.antv.vision/zh/docs/manual/FAQ/supportIE
> 
> 还是不行的话建议尝试更新版本

https://g6.antv.vision/zh/docs/manual/FAQ/supportIE#vuecli
这个方案在3.8.5下可以， 4.3.6的不行了( 没有尝试4.x其他版本 初次使用的我几乎崩溃了 ) ，IE11报错：语法错误
 ```
message:
    Syntax error
number:
    -2146827286
description:
    Syntax error
```

**Comment by aibotian** [comment]
3.8.3 都可以支持IE， 换到4.x.x版本就不支持IE了
