### ISSUE TITLE
packages/site项目下面运行 npm run start报错

### ISSUE THREAD

**Issue by yellowjian** [antvis/G6#3008]
git clone G6 project
npm i 
npm run bootstrap
cd package/site
npm i
npm run start
出现如下报错
![image](https://user-images.githubusercontent.com/17594267/124130335-3cdb3e80-dab1-11eb-8e55-3e1b1d842342.png)

**Comment by Yanyan-Wang** [comment]
删掉 node_modules 重新安装一下呢？也有可能是内存不够，给项目分配的内存调整大一些试试

export NODE_OPTIONS=--max_old_space_size=12000

**Comment by yellowjian** [comment]
> 删掉 node_modules 重新安装一下呢？也有可能是内存不够，给项目分配的内存调整大一些试试
> 
> export NODE_OPTIONS=--max_old_space_size=12000

@Yanyan-Wang 重试过还是不行，但是在mac 下面是可行的，在window10 下面出现的这个问题

**Comment by Yanyan-Wang** [comment]
加大内存了么。log 里面看下有没有有用的信息

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
