### ISSUE TITLE
Dagre layout ignores node custom positions

### ISSUE THREAD

**Issue by ltraccount** [antvis/G6#3010]
- **G6 Version**: 4.3.4
- **Platform**: Window, Chrome
- **Mini Showcase(like screenshots)**:
- **CodePen Link**: https://codesandbox.io/s/gallant-ives-8rn3u

I tried to set x and y in node data, but dagre layout is ignoring them
In this example: https://codesandbox.io/s/gallant-ives-8rn3u, I am setting x and y in node Id: 0

**Comment by ltraccount** [comment]
any help please @yuanchuan

**Comment by ltraccount** [comment]
Any help please @Yanyan-Wang

**Comment by Yanyan-Wang** [comment]
Layout configuration has higher priority to the position in node data. We support `nodesFilter` for layout config on the graph instance now. Try to filter out the nodes with x and y in the data. e.g.

```
layout: {
  ... // other configurations
  nodesFilter: d => !d.x && !d.y
}
```
