### ISSUE TITLE
forceAtlas2 布局当子节点超过100个，所有子节点会覆盖重合 

### ISSUE THREAD

**Issue by damowangzhu** [antvis/G6#3011]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sweet-boyd-ovh1w?file=/src/index.js)

### Steps to reproduce
一个父节点， 100 个子节点， 这100 个节点会重合

| Environment | Info |
|---|---|
| g6 | 4.3.4 |
| System | - |
| Browser | - |

---
一个父节点，少于100个子节点 显示正常的离散布局；当子节点超过100个后，所有的子节点都会重合。

``` 正常的布局
let data = {
  nodes: [],
  edges: []
};

// 当子节点不大于100个时候，布局离散正常
for (let i = 0; i < 100; i++) {
  data.nodes.push({
    id: String(i),
    label: String(i)
  });

  data.edges.push({
    source: "0",
    target: String(i)
  });
}

graph.data(data);
graph.render();
```

```
let data = {
  nodes: [],
  edges: []
};

// 当子节点超过100后，所有的子节点会重合
for (let i = 0; i < 101; i++) {
  data.nodes.push({
    id: String(i),
    label: String(i)
  });

  data.edges.push({
    source: "0",
    target: String(i)
  });
}

graph.data(data);
graph.render();
```

**Comment by unicode6674** [comment]
超过100 会自动剪枝的，
**prune** 
_类型： boolean
默认值：false
是否必须：false
说明：是否开启自动剪枝模式。默认情况下，当节点数量大于 100 时它将会被激活。注意，剪枝能够提高收敛速度，但可能会降低图的布局质量_

**Comment by fruit5566** [comment]
> 超过100 会自动剪枝的，
> **prune**
> _类型： boolean 默认值：false 是否必须：false 说明：是否开启自动剪枝模式。默认情况下，当节点数量大于 100 时它将会被激活。注意，剪枝能够提高收敛速度，但可能会降低图的布局质量_

prune:false 没用，因为超过100会自动开启，demo上有写 prune: false

**Comment by unicode6674** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    无论你是true 还是false当超过 100， 都会给你设置为true , 看源码 ***@***.*** /layout/lib/layout/forceAtlas2/index.d.ts, 应该是151 行 源码：if (!self.prune && nodeNum > 100)    self.prune = true;
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                shuai19940910
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2021年07月7日 ***@***.***> 写道： 




超过100 会自动剪枝的，
prune
类型： boolean 默认值：false 是否必须：false 说明：是否开启自动剪枝模式。默认情况下，当节点数量大于 100 时它将会被激活。注意，剪枝能够提高收敛速度，但可能会降低图的布局质量

prune:false 没用，因为超过100会自动开启，demo上有写 prune: false

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by fruit5566** [comment]
> font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } 无论你是true 还是false当超过 100， 都会给你设置为true , 看源码 ***@***.*** /layout/lib/layout/forceAtlas2/index.d.ts, 应该是151 行 源码：if (!self.prune && nodeNum > 100) self.prune = true; shuai19940910 ***@***.*** 签名由 网易邮箱大师 定制 在2021年07月7日 ***@***.***> 写道： 超过100 会自动剪枝的， prune 类型： boolean 默认值：false 是否必须：false 说明：是否开启自动剪枝模式。默认情况下，当节点数量大于 100 时它将会被激活。注意，剪枝能够提高收敛速度，但可能会降低图的布局质量 prune:false 没用，因为超过100会自动开启，demo上有写 prune: false —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

嗯 是的，感谢~ 问下在issure标签上  1 task done 或者 1 task 是什么意思 ?

**Comment by Yanyan-Wang** [comment]
下个版本修一下配置项

**Comment by Yanyan-Wang** [comment]
@antv/layout 发了 0.1.17，更新这个包试试看。prune 默认 undefined，如果设置了 false 就不会自动检测 100 个点调整 prune 了

**Comment by damowangzhu** [comment]
> @antv/layout 发了 0.1.17，更新这个包试试看。prune 默认 undefined，如果设置了 false 就不会自动检测 100 个点调整 prune 了

嗯 谢谢

**Comment by fruit5566** [comment]
> @antv/layout 发了 0.1.17，更新这个包试试看。prune 默认 undefined，如果设置了 false 就不会自动检测 100 个点调整 prune 了

@antv/layout  0.1.17 和  0.1.18 如果显示设置prune:false,  或者true. 画布白屏 ，如果设置prune: undefined 或者不设置，100个点会重合
