### ISSUE TITLE
G6 树图在节点未展开时无法确定所需滚动条的高度导致图片展示不全

### ISSUE THREAD

**Issue by highkick12** [antvis/G6#3012]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

G6版本：4.3.3 ，树图，scroll方式
1，树图无法知道展开时的高度，有什么办法能获取吗？（当前不知道展开的高度，写死值很大的情况下，页面scroll方式出现卡顿）
2，为何scroll和drag两个方式，drag能拖拽看到节点全局而不受限于canvas大小，scroll的方式会受制于canvas宽高呢

**Comment by highkick12** [comment]
配置如下：   
         defaultConfig: {
                modes: {
                    default: [
                        {
                          type: 'scroll-canvas',
                        },
                        'view-control',
                        {
                            type: 'tooltip',
                            formatText: function formatText(model) {
                                if (model.tooltip && model.tooltip != '') {
                                    model.string = '';
                                    model.tooltip.forEach(function(item){
                                        if (item.url && item != '') {
                                            model.string = model.string + `<a style="height: 20px; color: #68C1D7; display: block" href=${item.url} target="_blank">${item.text}</a>`;
                                        } else {
                                            model.string = model.string + `<p style="width: 400%; display: block; word-break: break-all;" href=${item.url} target="_blank"><font color=${item.color === undefined ? "#696969": item.color}>${item.text}</font></p>`;
                                        };
                                    })
                                    return `<div style="font-size:12px;
                                                border: 1px solid #e2e2e2;
                                                border-radius: 4px;
                                                padding: 10px 8px;
                                                background-color: rgba(255, 255, 255, 0.9);
                                                color: #68C1D7;
                                                position: relative;
                                                left: -50px;
                                                box-shadow: rgb(174, 174, 174) 0px 0px 10px">` + model.string + `</div>`;
                                }
                                else {
                                    return '';
                                }
                            },
                            shouldUpdate: function shouldUpdate() {
                                return true;
                            },
                        },
                        ]
                },
                fitView: false,
                // animate: true,
                defaultNode: {
                    shape: 'flow-rect',
                },
                defaultEdge: {
                    shape: 'cubic-horizontal',
                    style: {
                    stroke: '#CED4D9',
                    },
                },
                layout: {
                    type: 'indented',
                    direction: 'LR',
                    dropCap: false,
                    // 横向长度
                    indent: 500,
                    getHeight: () => {
                        // 竖向长度
                        return 100;
                    },
                },
            },
            config: {
                padding: [20, 50],
                defaultLevel: 3,
                defaultZoom: 0.8,
            }

**Comment by yanghuixia** [comment]
你好，获取树图展开时的高度我是这样获取的，在graph.on("collapse-text:click", (e) => {}里面定义一个展开收缩树图的方法，这个方法里面获取你要点击的tree id,并collapsed == true(false)来判断要收缩还是展开，展开tree高度=它subtree的个数*单个tree的高度（也就是你的getHeight）+ （subtree的个数-1）*subtree的垂直方向的间隔，收缩的话同理，width亦同理。最后用graph.changeSize去调整这个width，height就可以了

**Comment by Yanyan-Wang** [comment]
不是很明白，scroll 不就是为了让超出视窗的部分移出来吗？和 drag 没什么不同啊。请提供一下复现 demo

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
