### ISSUE TITLE
drag-node 行为，字符串类型座标 导致节点消失，代码层面没有报错

### ISSUE THREAD

**Issue by SLin0218** [antvis/G6#3015]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/flamboyant-mcnulty-20v0c?file=/src/index.js)

### Steps to reproduce
1、缩放后  移动之前画布外的节点 会回到原点
原因是由于后台返回数据是字符串类型的，由于没有报错，一下没有发现问题

| Environment | Info |
|---|---|
| g6 | 4.3.4 |
| System | Mac OS |
| Browser | Brave  1.26.74 Chromium: 91.0.4472.124（正式版本） (x86_64) |

**Comment by Yanyan-Wang** [comment]
下个小版本加个强转

**Comment by Yanyan-Wang** [comment]
fixed by 4.3.5
