### ISSUE TITLE
BUG：树的节点增加动画样式后，展开或收起子树时，树图自带的展开动画会闪烁

### ISSUE THREAD

**Issue by WontonCat** [antvis/G6#3016]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/busy-shape-6jn9x)

### Steps to reproduce
点击树的任意节点，收起或展开子树即可

| Environment | Info |
|---|---|
| g6 | 4.3.3 |
| System | macOS 11.2.3 |
| Browser | Google Chrome 版本 91.0.4472.106（正式版本） (arm64) |

**Comment by Yanyan-Wang** [comment]
参考解决方案：https://github.com/antvis/G6/issues/2553
