### ISSUE TITLE
自定义behavior配置shouldBegin不生效，shouldBegin没有执行

### ISSUE THREAD

**Issue by damnright** [antvis/G6#3017]
自定义behavior配置shouldBegin不生效，shouldBegin没有执行

**Comment by Yanyan-Wang** [comment]
自定义 behavior 的 shouldBegin 需要在你自己的函数逻辑里面去判断，参考  https://github.com/antvis/G6/blob/a74ffbd3d9a10b688ee52886d31397feff887771/packages/pc/src/behavior/drag-canvas.ts#L118
