### ISSUE TITLE
画布较小时，并且设置 fitView: true 。 移动整个画布，会出现轨迹/重影

### ISSUE THREAD

**Issue by Quelle-0** [antvis/G6#3018]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g6.antv.vision/zh/examples/case/simpleCase#ER](https://g6.antv.vision/zh/examples/case/simpleCase#ER)

### Steps to reproduce
如上，官网中ER图的 demo，再加一个属性 fitView: true 。之后拖拽整个ER图，出现重影

| Environment | Info |
|---|---|
| g6 | 4.3.4 |
| System | Mac |
| Browser |  91.0.4472.114 |

**Comment by Quelle-0** [comment]
![image](https://user-images.githubusercontent.com/41176559/124566669-da4dbe00-de75-11eb-9144-b529f9ce3f93.png)

**Comment by csspmini-web** [comment]
数据量少的时候，关闭局部刷新吧

**Comment by Yanyan-Wang** [comment]
底层正在升级准备统一解决残影问题，duplicated to https://github.com/antvis/G6/issues/2492
