### ISSUE TITLE
G6 自定义node， text 不自动换行

### ISSUE THREAD

**Issue by MagicalSun** [antvis/G6#3019]
代码如下：   
 G6.registerNode(
      'fault-node',
      (cfg) => `
        <group>
          <rect keyshape="true">
      
            <rect style={{ width: 150, height: 55, stroke: ${cfg.color}, fill: #ffffff, radius: [0, 0, 6, 6], 
              flexWrap:'wrap', 
              }}>

              <text style={{ marginTop: 5, marginLeft: 4, marginRight: 4, fill: '#333', 
                flex: 1,
                }}>{{dsc}}</text>

            </rect>
          </rect>
          
        </group>`
      );

**Comment by WontonCat** [comment]
官网关于超长文本的解决方案在这里，可以参考一下
https://g6.antv.vision/zh/examples/gallery#category-%E8%B6%85%E9%95%BF%E6%96%87%E6%9C%AC

**Comment by mxz96102** [comment]
你好，jsx和react-node不是一个方案，想使用flex属性请使用react-node

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
