### ISSUE TITLE
npm下载g6-plugins然后使用import导入g6-plugins报错 TypeError: (0 , a.registNode) is not a function

### ISSUE THREAD

**Issue by oooofeiger** [antvis/g6#302]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

npm下载g6-plugins然后使用import导入g6-plugins报错 TypeError: (0 , a.registNode) is not a function

**Comment by TomHuangCN** [comment]
官方的插件目前维护在 G6 的主仓库里，如果要使用官方提供的插件，只需要安装 `@antv/g6` 即可。

```bash
npm install @antv/g6 --save
```

可以按需要引入

```js
const G6 = require('@antv/g6');
const Minimap = require('@antv/g6/plugins/tool.minimap/');
```

也可以全部引入

```js
const G6 = require('@antv/g6');
const G6Plugins = require('@antv/g6/plugins/');
```
