### ISSUE TITLE
Losing combo and node color after activate-relations

### ISSUE THREAD

**Issue by brishable** [antvis/G6#3021]
When activate-relations is enabled by combo/node click the color of all combos and nodes is set to white until activate relations is disabled with a click on the canvas.

**Link to example code:**  [https://codesandbox.io/s/ecstatic-ganguly-mhhc0?file=/index.js](https://codesandbox.io/s/ecstatic-ganguly-mhhc0?file=/index.js)

**How to reproduce:** 

- The combos have different colors 
- Click on any node to activate relations 
- You will see that all the combos/nodes background color is changed to white

**Expected behavior:** 
•	Combos and nodes to retain their colors regardless of activate relations enabled or disabled.

**Comment by Yanyan-Wang** [comment]
The default  'active' and 'inactive' styles are taking effect when you are using active-relations with default configurations. You could assign different `activeState` and 'inactiveState' for active-relations behavior and design your own state styles in `comboStateStyles`, `nodeStateStyles`, and `edgeStateStyles`:

![image](https://user-images.githubusercontent.com/29593318/125720649-969844b7-2235-4b9c-b138-dda21c863995.png)
