### ISSUE TITLE
删除包含节点的轮廓后，拖动节点报错。再次创建轮廓，拖动轮廓内部的节点会被移动到轮廓外，并且控制台报错

### ISSUE THREAD

**Issue by junping1991** [antvis/G6#3022]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/eager-hugle-zhdqz?file=/index.js)

### Steps to reproduce
1、鼠标左键单击画布空白处，创建轮廓；
2、拖动节点，节点仍被轮廓包裹；
3、再次单击画布空白处，删除轮廓；
4、拖动节点，报错；
5、再次单击画布，再次创建轮廓；
6、拖动节点，节点不再被轮廓包裹。

| Environment | Info |
|---|---|
| g6 | 4.3.3 |
| System | - |
| Browser | chrome |

---
希望：删除轮廓后，拖动节点不报错，然后再次创建轮廓，拖动节点，节点能被轮廓包裹

**Comment by Yanyan-Wang** [comment]
因为你的 afterupdateitem 监听绑定在 canvas:click 里面啊，这样即使之前创建的 hull 被销毁了，之前绑定的 afterudpateitem 监听仍然会执行，但那时候里面的 hull1 hull2 hull3 已经销毁了。这样写就行了

https://codesandbox.io/s/angry-volhard-m8mz1
