### ISSUE TITLE
Hovering over edges has issues

### ISSUE THREAD

**Issue by erlebach** [antvis/G6#3023]
- **G6 Version**:  4.3.4
- **Platform**: MacosX
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

I created a minimal working example, which can be accessed on github at `https://github.com/erlebach/G6_hover_MWE.git`. In the demo, there are four nodes and two disconnected edges. Hovering over nodes changes their color, and the nodes return to their default state when their shape is exited. Edge hover does not work. "When the mouse enters the edge, the state changes. However, the state does not refer back to its default value upon exiting the edge. 

I have not found any demo showing this bug. If I made an error, I would love to understand what I did wrong. 

Never mind: I found an error in my code. I had: 
// Mouse leave an edge
graph.on("edge:mouseleave", (e) => {
  const edgeItem = e.item;
  graph.setItemState(nodeItem, "hover", false);
});

and it should have been: 

// Mouse leave an edge
graph.on("edge:mouseleave", (e) => {
  const edgeItem = e.item;
  graph.setItemState(edgeItem, "hover", false);
});

Thank you, 

    Gordon

**Comment by erlebach** [comment]
Anybody there?

**Comment by Yanyan-Wang** [comment]
you bind twice node:mouseleave but no edge:mouseleave

https://github.com/erlebach/G6_hover_MWE/blob/cfaa31692cd845e5919be604a734bf7ad76f8fc6/index.js#L73
https://github.com/erlebach/G6_hover_MWE/blob/cfaa31692cd845e5919be604a734bf7ad76f8fc6/index.js#L84
