### ISSUE TITLE
官网提供的创建边的样例有问题，改变例子中的渲染引擎为svg后，连接点默认可见

### ISSUE THREAD

**Issue by mirkcale** [antvis/G6#3024]
链接地址：https://g6.antv.vision/zh/examples/interaction/createEdge#click-link-point，
改变例子中的渲染引擎为svg后，连接点默认可见

**Comment by Yanyan-Wang** [comment]
![image](https://user-images.githubusercontent.com/29593318/125726721-1e2b75c3-125c-498a-b39a-0eaf9c81db72.png)

没有复现

**Comment by mirkcale** [comment]
![image](https://user-images.githubusercontent.com/19788310/128602332-04b281a6-2329-4c32-9c7c-3e1c2b884dc2.png)

抱歉没有说清楚是哪个例子，这个例子还能复现，“点击端点上的子图形”

**Comment by mirkcale** [comment]
@Yanyan-Wang
