### ISSUE TITLE
自定义节点，通过setState设置selected样式，registerBehavior自定义node:click事件，点击时边框变为蓝色，鼠标移开时又恢复到之前的颜色？？

### ISSUE THREAD

**Issue by chunfeilvlv** [antvis/G6#3026]
自定义节点的state

setState: (name, value, item) => {
        const group = item.getContainer()
        // console.log('group', group)
        if (name === 'show-anchor') {
            // console.log('group.getAnchor', group.getAnchor())
            // console.log('name,value,item', name, value, item)
            if (value) {
                group.showAnchor()
            } else {
                group.clearAnchor()
            }
            // 节点选中状态
        } else if (name === 'selected') {
            console.log('执行选中', value)
            const current = item.getModel()
            const rect_shape = group.find((element) => element.get('name') === 'rect-shape')
            const left_circle_icon = group.find((element) => element.get('name') === 'left-circle-icon')
            if (value) {
                rect_shape.attr('fill', 'rgba(26,174,232,0.04)')
                rect_shape.attr('stroke', 'rgba(24,144,255,1)')
                left_circle_icon && left_circle_icon.attr('stroke', 'rgba(24,144,255,1)')
            } else {
                rect_shape.attr('stroke', current.nodeError ? ERROR_COLOR : '#999999')
                rect_shape.attr('fill', '#fff')
                left_circle_icon && left_circle_icon.attr('fill', '#fff')
            }
            // 节点hover状态
        }
        else if (name === 'hover') {
            const current = item.getModel()
            const rect_shape = group.find((element) => element.get('name') === 'rect-shape')
            const left_circle_icon = group.find((element) => element.get('name') === 'left-circle-icon')
            if (value) {
                rect_shape.attr('fill', 'rgba(26,174,232,0.04)')
                rect_shape.attr('stroke', 'rgba(24,144,255,1)')
                left_circle_icon && left_circle_icon.attr('stroke', 'rgba(24,144,255,1)')

            } else {
                rect_shape.attr('stroke', current.nodeError ? ERROR_COLOR : '#999999')
                rect_shape.attr('fill', '#fff')
                left_circle_icon && left_circle_icon.attr('stroke', '#fff')
            }
        }
        // graph.setAutoPaint(true);
    },

export default function (G6) {
    G6.registerBehavior('node:click', {
        getDefaultCfg () {
            return {
                multiple: true,
            }
        },
        getEvents () {
            return {
                // 'node:mouseover': 'onNodeMouseOver',
                // 'node:mouseleave': 'onNodeLeave',
                'node:click': 'onClick',
            }
        },
        onClick (e) {
            console.log('node click', e)
            const graph = this.graph
            const item = e.item         
            graph.getNodes().forEach(function (node) {
                graph.clearItemStates(node, ['selected','active', 'hover'])
            })
            // 置点击的节点状态 'active' 为 true
            graph.setItemState(item, 'selected', true)
        },       
    })
}

**Comment by Yanyan-Wang** [comment]
请提供在线复现 demo
