### ISSUE TITLE
[Example] 时序图方案

### ISSUE THREAD

**Issue by WontonCat** [antvis/G6#3027]
### Description
本案例中，时序图的绘制思路是将其拆分为三类点线连接关系绘制，分别为：
1. 连接Object的LifeLine
2. 连接Activation的MessageLine
3. Object自调用的线（本案例中暂未绘制）

本案例并非时序图实现的最佳方案，只是提供一个思路，期望早日找到完美解决方案。

### Implementation
https://codesandbox.io/s/elated-robinson-59jsi?file=/index.js

**Comment by mxz96102** [comment]
感谢你的贡献～我们将尽快检验收录

**Comment by Yanyan-Wang** [comment]
已收录至官网 demo。再次感谢，欢迎更多社区案例贡献。http://g6.antv.antgroup.com/examples/case/graphDemos/#sequence
