### ISSUE TITLE
Can we assign a React Component in the innerHTML in the getContent function of G6.menu?

### ISSUE THREAD

**Issue by AChaoZJU** [antvis/G6#3029]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

As the [document](https://antv-g6.gitee.io/en/docs/api/Plugins/#configuration-6) says, the getContent function returns `HTMLDivElement / string`.

Can we use React Component in the getContent function of G6.menu?
### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nervous-nash-xzqdq?file=/index.js)

### Steps to reproduce
I try to assign a React Component in the innerHTML but it does not work.
![Screen Shot 2021-07-09 at 14 28 17](https://user-images.githubusercontent.com/17509647/125033604-19704f00-e0c2-11eb-856b-73bdd06ed5fd.png)

```
const contextMenu = new G6.Menu({
    getContent(evt) {
    const outDiv = document.createElement("div");
    outDiv.style.width = "180px";
    outDiv.innerHTML = `<Menu />`;
    return outDiv;
  },
  handleMenuClick: (target, item) => {
    console.log(target, item);
  },
  // offsetX and offsetY include the padding of the parent container
  offsetX: 16 + 10,
  offsetY: 0,
  itemTypes: ["node", "edge", "canvas"]
});
```

| Environment | Info |
|---|---|
| g6 | 4.3.4 |
| System | macOS 10.15.6 |
| Browser | Chrome 91.0.4472.77 |

**Comment by mxz96102** [comment]
getContent is basically only for vanillaJS, If you want to use react try to use React DOM mount component on outDiv instead of return a string

**Comment by AChaoZJU** [comment]
> getContent is basically only for vanillaJS, If you want to use react try to use React DOM mount component on outDiv instead of return a string

Thanks! The solution works well!
```
const contextMenu = new G6.Menu({
    getContent(evt) {
    const outDiv = document.createElement("div");
    ReactDOM.render(<Menu />, outDiv)
    return outDiv;
  },
  handleMenuClick: (target, item) => {
    console.log(target, item);
  },
  // offsetX and offsetY include the padding of the parent container
  offsetX: 16 + 10,
  offsetY: 0,
  itemTypes: ["node", "edge", "canvas"]
});
```
``
