### ISSUE TITLE
增加 非鼠标事件触发节点或边 tooltip 的api , 

### ISSUE THREAD

**Issue by unicode6674** [antvis/G6#3031]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
例如我在图之外给某个节点/边添加属性后， 在没有鼠标事件，需要用户在图上以tooltip 的形式感知一下， 

### What does the proposed API look like?
例如 graph.tooltipFoucs(node/nodeId, offset, )

**Comment by Yanyan-Wang** [comment]
这个内置 tooltip 不会考虑，可以自己加 DOM 来实现。或者模拟鼠标触发事件 graph.emit('node:mouseenter', {item, target});
