### ISSUE TITLE
根据表单项的选择高亮某个节点，并支持重置

### ISSUE THREAD

**Issue by XdyGoGo** [antvis/G6#3032]
我通过registerNode自定义节点
并用drawShape绘制
内部方法使用了多个addShape绘制内容并最终返回一个外边框rect

现在有需要需要根据控件的选择来高亮对应的框
也就是addShape添加的东西需要改变样式
nodeStateStyles只能定制被返回的那个addShape
如果在setState里设置状态的话，又面临状态恢复的问题
尽管可以通过read方式重置
但这种方式会将用户之前的操作状态也一并去除（比如缩放）
如果继续这种方式，必然需要记忆用户之前的操作状态并恢复，复杂度增加

所以想看看有没有更简便的方式

**Comment by Yanyan-Wang** [comment]
> nodeStateStyles只能定制被返回的那个addShape 

不是的，可以指定图形设置状态样式，见https://g6.antv.vision/zh/docs/manual/advanced/state-new#%E5%AD%90%E5%9B%BE%E5%BD%A2%E7%8A%B6%E6%80%81%E6%A0%B7%E5%BC%8F

**Comment by XdyGoGo** [comment]
解决了，谢谢
