### ISSUE TITLE
如何在节点上显示徽标

### ISSUE THREAD

**Issue by Youmyin** [antvis/G6#3034]
- **G6 Version**: 4.3.4
- **Platform**: windows10
- **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/54265150/125240299-85e68a80-e31c-11eb-9a3e-54465889a75a.png)

我想在节点右上角显示徽标，在Antv graphin中有这个功能，但是graphin的功能目前还没有g6完善，所以决定还是用在g6实现。

我的节点类型是image,是一张不规则形状的图片，现在想在右上角显示徽标，请问怎样实现这个需求呢？

**Comment by javaNaruto** [comment]
找到这个节点的Group，把右上角这个shape添加上去就OK了，首先你得搞懂group怎么玩的。

**Comment by Youmyin** [comment]
感谢！

**Comment by Yanyan-Wang** [comment]
自定义节点可以为所欲为
