### ISSUE TITLE
can we have the svgs as a nodes in g6? is there any way to have just nodes as SVG?

### ISSUE THREAD

**Issue by pandyamarut** [antvis/G6#3035]

**Comment by Yanyan-Wang** [comment]
configure renderer: 'svg' to graph instance, all the elements will be rendered by svg.

**Comment by pandyamarut** [comment]
@Yanyan-Wang Yes that would do but for some instances it just hangs the browser. Can't canvas render the nodes as html ? Can't we draw them in canvas ?
