### ISSUE TITLE
TreeGraph  中在不破坏整体布局的情况下  怎样使根几点居中显示？？

### ISSUE THREAD

**Issue by babyyage** [antvis/G6#3036]
TreeGraph  中在不破坏整体布局的情况下  怎样使根几点居中显示？？

**Comment by Yanyan-Wang** [comment]
平移图？graph.move 或 graph.moveTo

**Comment by ityoung** [comment]
> move

没有`graph.move`方法；
`graph.moveTo`会导致部分节点被遮挡没法通过滚轮向上滚动了

**Comment by ityoung** [comment]
此处需要一个 scrollTo 的方法
