### ISSUE TITLE
brush-select与drag-combo，冲突怎么解决

### ISSUE THREAD

**Issue by yanghuixia** [antvis/G6#3037]
canvas中node所属的combo可以拖动，当配置brush-select，在combo上面选中多个node时，会触发drag-combo，导致没法多选，只能在combo外侧多选，这样的怎么解决呢？

**Comment by Yanyan-Wang** [comment]
brush-select 只能在空白处开始选

**Comment by yanghuixia** [comment]
> brush-select 只能在空白处开始选

好的，谢谢
