### ISSUE TITLE
g6 'compactBox'紧凑树  direction: 'V'方向上下布局 如何控制上下节点数量

### ISSUE THREAD

**Issue by trace59** [antvis/G6#3038]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g6.antv.vision/zh/examples/tree/compactBox#tbCompactBox](https://g6.antv.vision/zh/examples/tree/compactBox#tbCompactBox)

### Steps to reproduce
- 'compactBox'紧凑树 ，direction: 'V'方向上下布局，控制上面仅展示一个根节点，其余节点在下面展示

| Environment | Info |
|---|---|
| g6 | 4.3.4 |
| System | mac |
| Browser | chorme |

 
![image](https://user-images.githubusercontent.com/24761764/125430139-f0e3cf26-12b7-4d1c-89fa-d9bbb54d8363.png)

**Comment by Yanyan-Wang** [comment]
可以配置 getSide，参考 https://g6.antv.vision/zh/docs/api/treeGraphLayout/mindmap#layoutcfggetside

compactBox 文档少了这个参数，会尽快补充
