### ISSUE TITLE
图像加载时在左上角卡顿一下才调整至页面中心

### ISSUE THREAD

**Issue by Youmyin** [antvis/G6#3040]
- **G6 Version**: 4.3.4
- **Platform**: windows

将图像放到子组件中，引入到父组件，父组件页面加载的时候，图像总是卡在容器左上角，卡一下才跳到中间来
![image](https://user-images.githubusercontent.com/54265150/125549528-d09ed913-adfb-4c47-a106-9f93ae5127ba.png)

**Comment by Yanyan-Wang** [comment]
请提供复现在线 demo

**Comment by baihech** [comment]
我也是。。。

**Comment by baihech** [comment]
调用graph.refreshPositions();方法可以让node平铺在canvas上，然后再回归到正确位置。
`graph.render();
 graph.refreshPositions();
`

**Comment by Youmyin** [comment]
> 调用graph.refreshPositions();方法可以让node平铺在canvas上，然后再回归到正确位置。
> `graph.render(); graph.refreshPositions(); `

我是一个树形图，调用graph.refreshPositions()直接把树节点全部拉成一条直线了，虽然不跳了，但是直接卡在左上角不动了哎(╥﹏╥)

**Comment by baihech** [comment]
看下控制台是不是报错了

**Comment by Yanyan-Wang** [comment]
如果是树图的话，可能是因为布局还在计算过程中，所以会在左上角，等待布局计算完成才移动到正确的位置上

**Comment by Yanyan-Wang** [comment]
如果出现该问题, 请尝试升级 G6 到最新(目前是4.3.6)
