### ISSUE TITLE
官网示例里树图展开图标显示不正确

### ISSUE THREAD

**Issue by hb592086309** [antvis/G6#3041]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g6.antv.vision/zh/examples/tree/indented#intendAlignTop](https://g6.antv.vision/zh/examples/tree/indented#intendAlignTop)

### Steps to reproduce
先收缩子节点，再收缩父节点，然后展开父节点，此时子节点的图标显示错误

| Environment | Info |
|---|---|
| g6 | 4.3.4 |
| System | - |
| Browser | - |

---
想要展开时显示正确的图标

**Comment by Yanyan-Wang** [comment]
感谢报告，已经修复
