### ISSUE TITLE
degre图使用changeData后边绘制异常

### ISSUE THREAD

**Issue by Nekosandesu** [antvis/G6#3042]
- [√] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/stoic-hill-wi0k9?file=/src/index.js)

### Steps to reproduce
1. 打开Demo链接后发现正常渲染了
2. 取消setInterval部分的注释，更新之后，图里的边就变得很奇怪

| Environment | Info |
|---|---|
| g6 | 4.3.4 |
| System | - |
| Browser | - |

**Comment by Nekosandesu** [comment]
这是正常情况：
![image](https://user-images.githubusercontent.com/32799721/125581501-6e083c60-f19e-4f11-923d-6c1c1cc3d208.png)
这是调用changeData更新后的异常情况：
![image](https://user-images.githubusercontent.com/32799721/125581588-c08df7c3-50d8-4339-a2ce-87d747e47286.png)
因为我这边是一个页面使用这个图，这个页面每隔几秒会重新请求数据刷新页面。

**Comment by Nekosandesu** [comment]
我通过打断点初步排查出问题了，因为我的edges没有给id，所以每次diff的时候，因为第二次的边全部生成random的id，跟第一次的对不上了，所以就走了addItem而不是updateItem。这里是不是建议改成true呢，或者给点儿说明呢。
![image](https://user-images.githubusercontent.com/32799721/125596638-348274ea-63a4-438a-9af8-06bb11b1062f.png)

addItem里面我没有再去排查，按道理就算id不一样，前后两次配置相同，边的形状也不应该变化呀。

**Comment by Yanyan-Wang** [comment]
好的，感谢报告。因为如果刷新数据之后没有相同的 id，G6 内部无法判断是不是同一条边。

上面那张正确的图边的 controlPoints 是怎么给的呢？

**Comment by Nekosandesu** [comment]
> 好的，感谢报告。因为如果刷新数据之后没有相同的 id，G6 内部无法判断是不是同一条边。
> 
> 上面那张正确的图边的 controlPoints 是怎么给的呢？

没有配置controlPoints这项

**Comment by Nekosandesu** [comment]
我还发现了一些问题：调用changeData的时候，边没有提供id时，自定义节点渲染有问题；提供了id时，报错：
![image](https://user-images.githubusercontent.com/32799721/125756823-268311ba-be36-464d-9997-b7dd595e7f9a.png)

**Comment by Yanyan-Wang** [comment]
> > 好的，感谢报告。因为如果刷新数据之后没有相同的 id，G6 内部无法判断是不是同一条边。
> > 上面那张正确的图边的 controlPoints 是怎么给的呢？
> 
> 没有配置controlPoints这项

那是怎么出现的折线？是配置了 dagre 的 controlPoints: true 吗

> 我还发现了一些问题：调用changeData的时候，边没有提供id时，自定义节点渲染有问题；提供了id时，报错

这个好像跟 ID 关系不大，能否提供一个复现在线 demo

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
