### ISSUE TITLE
legend render函数的错误会导致图例不会清空

### ISSUE THREAD

**Issue by luckjoke** [antvis/G6#3043]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ecstatic-ellis-07p04?file=/src/index.js)

### Steps to reproduce
无

| Environment | Info |
|---|---|
| g6 | 4.3.4 |
| System | - |
| Browser | - |

---
在使用legend 的changeData函数时发现的问题，原先的图例没有消失，导致图例不断增加，后发现changeData使用了render函数，其中会读取之前的图例信息并再次加入到新的图例中。

**Comment by SunnyWWQ** [comment]
请问有解决方案么？

**Comment by gouzixing** [comment]
请问有解决方案吗

**Comment by Yanyan-Wang** [comment]
当前版本已不存在上述问题
