### ISSUE TITLE
Restrict Canvas drag area to a certain area

### ISSUE THREAD

**Issue by 1994benc** [antvis/G6#3044]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
For consistency with the ability to restrict zooming to a certain range, I think maybe there should be an option to restrict how much users can drag (pan) the canvas. I ran into issues where our users drag the nodes out of view too far. And we would like to restrict the area in which the users can drag the canvas to only the areas the nodes are visible 

### What does the proposed API look like?
perhaps 
- allow specification 'allow drag range' (i.e. how far can users pan the canvas away from the center point?)?
- allow option for infinite dragging too

**Comment by Yanyan-Wang** [comment]
https://g6.antv.vision/en/docs/manual/middle/states/defaultBehavior#drag-canvas

https://g6.antv.vision/en/docs/manual/middle/states/defaultBehavior#scroll-canvas


scalableRange

**Comment by Yanyan-Wang** [comment]
Hi, dear user. Since there was no response for a long time, we cannot figure out the answer of the problem you described. If there is new progress, feel free to open a new issue.
