### ISSUE TITLE
Moving combo while expanded, after releasing mouse drag, the combo will shrink but the nodes will stay visible

### ISSUE THREAD

**Issue by bsansone** [antvis/G6#3045]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gifted-stonebraker-pelp0)

### Steps to reproduce
1. Drag collapsed combo
2. Click to expand combo, nodes within combo should become visible
3. Drag expanded combo
4. Combo collapses after mouse release, nodes stay visible

| Environment | Info |
|---|---|
| g6 | 4.3.4 |
| System | Linux |
| Browser | Chrome |

**Comment by Yanyan-Wang** [comment]
That is because you assign collapsed: true to all the combos at line 77. The graph.combo function is not for initiating but will be called before every re-render. Try to assign collapsed: true to combo data for initiation instead pls

data.combos.forEach(combo => {
  combo.collapsed = true;
});
