### ISSUE TITLE
文档中图形或图形分组变化部分章节的示例是否需要更新一下

### ISSUE THREAD

**Issue by zmbxy95** [antvis/G6#3046]
![image](https://user-images.githubusercontent.com/50108232/125718522-6830372f-337a-445c-8da9-3856558611ff.png)
如图中标注，@antv/matrix-util 3.0.4中没有导出transform，或者API已经发生变更，文档未更新。

**Comment by Yanyan-Wang** [comment]
感谢指正, 已经修改。transform 可这样引入：

import { ext } from '@antv/matrix-util';
const transform = ext.transform;
