### ISSUE TITLE
drag-canvas may not refresh canvas after zoom-canvans in force graph

### ISSUE THREAD

**Issue by luckjoke** [antvis/G6#3047]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/strange-einstein-k6zjo?file=/index.js)

### Steps to reproduce
无

| Environment | Info |
|---|---|
| g6 | 4.3.4 |
| System | - |
| Browser | - |

---
![image](https://user-images.githubusercontent.com/48207219/125725995-992c3d62-9403-4b32-a4c4-ab4f41aa6392.png)

In my project I configured the following configuration：sensitivity，maxZoom，minZoom，enableOptimize，optimizeZoom in zoom-canvas.
When I enlarge the graph and then try to drag canvas, it fails to auto refresh the canvas. Only I zoom again, canvas refresh

**Comment by Yanyan-Wang** [comment]
The `fontSize` should be a number

**Comment by Yanyan-Wang** [comment]
https://g6.antv.vision/en/docs/manual/middle/elements/edges/defaultEdge#label-and-labelcfg
