### ISSUE TITLE
【pushStack】Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ue360** [antvis/G6#3049]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nifty-babbage-5q8uc)

### Steps to reproduce
批量记录入栈操作

| Environment | Info |
|---|---|
| g6 | 4.3.4 |
| System | - |
| Browser | - |

**Comment by Yanyan-Wang** [comment]
push 的应该是节点数据，而不是节点 item，节点 item 有很多的引用不能 clone。

  graph.pushStack('update', {
    after: {
       nodes: nodes.map(nodeItem => ({...nodeItem.getModel()}))
    }
  });

**Comment by ue360** [comment]
谢谢，可以了
