### ISSUE TITLE
允许自定义TreeLayout

### ISSUE THREAD

**Issue by qqabcv520** [antvis/G6#3050]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
允许自定义TreeLayout，便于自定义树的样式，比如呈放射状

### What does the proposed API look like?
`G6.registerLayout`或者`G6.registerTreeLayout`

**Comment by Yanyan-Wang** [comment]
放射状可以配置布局 radial: true https://g6.antv.vision/zh/docs/api/treeGraphLayout/compactBox#layoutcfgradial

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
