### ISSUE TITLE
G6 双击节点如何避免创建自环边？

### ISSUE THREAD

**Issue by jeffreyyjp** [antvis/G6#3051]
我的交互模式只有一个默认模式，其下有个交互行为为 **create-edge**，**trigger** 设置的为 **click**。
但现在双击任意节点时，会创建自环边。如何避免创建自环边呢，我通过监听节点的 **dblclick** 事件，但不知如何进一步操作。

**Comment by Yanyan-Wang** [comment]
也许可以在 dblclick 里面删去刚刚增加的边

**Comment by jeffreyyjp** [comment]
@Yanyan-Wang 试过在 dblclick 里删去刚增加的自环边，但会引起整个画布异常

**Comment by Yanyan-Wang** [comment]
什么异常? 提供一下在线 demo 呢?

**Comment by SterbenJ** [comment]
在  `create-edge` 中配置一下可以避免，首先在绘制起点的钩子中记录一下 `startNode` ，接着在绘制终点的钩子中对比即可
```js
shouldBegin(e) {
  graph.startNode = e.item;
  return true;
},
shouldEnd(e) {
  if (e.item === graph.startNode) {
    return false;
  }
  graph.startNode = null;
  return true;
},
```

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
