### ISSUE TITLE
急求！！g6的状态如何设置label和labelCfg！

### ISSUE THREAD

**Issue by had60** [antvis/G6#3052]
1.stateStyles只能设置fill,stroke等属性，如何设置label的属性，比如边上关系的value，opacity等等
2.g6的节点样式如何能够设置成类似Graphin的badges的样式呢
万分感谢！！

**Comment by Yanyan-Wang** [comment]
https://g6.antv.vision/zh/docs/manual/advanced/state-new#%E5%AD%90%E5%9B%BE%E5%BD%A2%E7%8A%B6%E6%80%81%E6%A0%B7%E5%BC%8F

可以参考 Graphin 节点样式进行自定义

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。

**Comment by mooction** [comment]
```js
  nodeStateStyles: {
    hover: {
      opacity: 0.6,
      'text-shape': {
        opacity: 0.6,
      },
    },
    click: {
      stroke: '#000',
      'text-shape': {
        fill: '#000',
      },
    },
  },
```

子节点中 `name` 属性值可以从源码中查到。

**Comment by wangjingithub** [comment]
请问下这个text-shape是什么意思，设置了没有效果啊
