### ISSUE TITLE
zoom 后面版本会不会支持 语义缩放， 现在是 几何缩放

### ISSUE THREAD

**Issue by unicode6674** [antvis/G6#3054]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
zoom 后面版本会不会支持 语义缩放， 现在是 几何缩放
例子链接：  https://bl.ocks.org/mbostock/3680957， 

### What does the proposed API look like?
zoom-canvas-semantic

**Comment by unicode6674** [comment]
例子链接： https://bl.ocks.org/mbostock/3680957 （末尾无逗号）

**Comment by Yanyan-Wang** [comment]
意思是缩放过程中元素大小不变？现在的 zoom-canvas 支持配置 fixSelectedItems

https://g6.antv.vision/zh/docs/manual/middle/states/defaultBehavior#zoom-canvas

**Comment by unicode6674** [comment]
有一些受限制， 尝试了下， 有几个问题：
1、只支持一种状态下的节点， 例如 selected 节点， 实际使用场景下， 有可能存在多种state 状态的节点，而且会有多种交互模式 mode,
2, 就目前的fixSelectedItems 配置实现， 当缩小的时候， 某种状态下的节点能够保证大小不变， 但是整体放大， 该状态节点还是正常放大

**Comment by Yanyan-Wang** [comment]
fixSelectedItems 的目的是不要让关注的节点/边内容在缩小的时候看不清楚，所以放大的时候没有管它。如果你需要所有节点/边都做缩放时的自动调整，可以参照 zoom-canvas 来实现一个自定义的画布缩放 behavior

zoom-canvas 源码：https://github.com/antvis/G6/blob/master/packages/pc/src/behavior/zoom-canvas.ts

自定义 behavior 文档：https://g6.antv.vision/zh/docs/manual/middle/states/custom-behavior

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
