### ISSUE TITLE
when we add the nodes on -- onclick event, in gForce layout, there's a wild animation where node comes from the top of the screen. Is there anyway to stop that? 

### ISSUE THREAD

**Issue by pandyamarut** [antvis/G6#3060]
setting `animate` as false is not helping. Help and direction will be appreciated. Thanks

**Comment by pandyamarut** [comment]
In my case I am using gForce layout, but when we add new nodes on :`onclick` the nodes are always are moving @Yanyan-Wang

**Comment by Yanyan-Wang** [comment]
Please provide an online reproduced demo

**Comment by Yanyan-Wang** [comment]
I guess you could assign initial positions (x and y in the data) for the newly added nodes, then the x and y will be the beginning positions for the new nodes

**Comment by Yanyan-Wang** [comment]
Hi, dear user. Since there was no response for a long time, we cannot figure out the answer of the problem you described. If there is new progress, feel free to open a new issue.
