### ISSUE TITLE
节点内容滚动时，画布会跟随一起滚动

### ISSUE THREAD

**Issue by Quelle-0** [antvis/G6#3062]
### Reproduction link
[https://g6.antv.vision/zh/examples/item/customNode#scrollNode](https://g6.antv.vision/zh/examples/item/customNode#scrollNode)

### Steps to reproduce
官方demo
1、graph实例，设置模式：
modes: {
    default: ['dice-er-scroll', 'drag-node', 'drag-canvas',
    {
      type: 'scroll-canvas',
      direction: 'y',
    },
    ],
  }
2、此时demo左边的节点有滚动条，向下滚动左边节点中的内容，可以清楚看到画布也在向下滚动

| Environment | Info |
|---|---|
| g6 | 4.3.4 |
| System | macOS Catalina 10.15.6 |
| Browser | Chrome 92.0.4515.107 |

---
期望结果：画布可以滚动，但滚动节点内容时，画布不会随着一起滚动

**Comment by Quelle-0** [comment]
补上录屏：
https://user-images.githubusercontent.com/41176559/127259137-0e0313c5-9f38-4a54-836a-2cbb7f34a60f.mov

**Comment by mxz96102** [comment]
这个插件和scroll-canvas是冲突的，我们看一下解法

**Comment by Yanyan-Wang** [comment]
为 scroll-canvas 新增了配置项 `allowDragOnItem` 以配置在元素上进行滚轮，是否发生响应，请关注，
https://github.com/antvis/G6/pull/4093

**Comment by Yanyan-Wang** [comment]
v4.7.16 已支持
