### ISSUE TITLE
combo内的node的边的层级怎么更改

### ISSUE THREAD

**Issue by damnright** [antvis/G6#3063]
combo内的node和combo外node相连的edge，combo收缩后edge始终在node上层，如何使其在node下面

**Comment by Yanyan-Wang** [comment]
edge item 可以调用 edge.toFront edge.toBack, node 也是。

前提是实例化图的时候配置了 groupByTypes: false

**Comment by damnright** [comment]
> edge item 可以调用 edge.toFront edge.toBack, node 也是。
> 
> 前提是实例化图的时候配置了 groupByTypes: false

但是combo中的node和combo外node相连时，收缩combo，此时edge item调用toBack无效，edge层级始终高于外面的node

**Comment by Yanyan-Wang** [comment]
如果是这个边遮挡到了它的终点的话，建议不要 linkCenter: true

**Comment by Yanyan-Wang** [comment]
当前版本应该不存在上述问题了。再有问题可以带上在线 demo 新开 issue
