### ISSUE TITLE
[Example] registerNode click-select and stateStyles can not show

### ISSUE THREAD

**Issue by baihech** [antvis/G6#3064]
### Implementation

https://codesandbox.io/s/practical-wescoff-zzlor

**Comment by baihech** [comment]
树图的自定义节点click-select和stateStyles无效

**Comment by Yanyan-Wang** [comment]
因为 setState 被复写了，而且没有继承内置的节点。registerNode 第三个参数可以填 'single-node' 或者 'circle' 就是继承内置的这种节点

**Comment by baihech** [comment]
> 因为 setState 被复写了，而且没有继承内置的节点。registerNode 第三个参数可以填 'single-node' 或者 'circle' 就是继承内置的这种节点

了解了，setState 默认行为要加上，对么？

**Comment by Yanyan-Wang** [comment]
setState 是用来响应状态设置的, 可以继承内置的就不用自己写, 如果不继承的话需要自己实现才可以
