### ISSUE TITLE
image和updateChildren冲突

### ISSUE THREAD

**Issue by baihech** [antvis/G6#3065]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g6.antv.vision/zh/examples/tree/indented#intendAlignTop](https://g6.antv.vision/zh/examples/tree/indented#intendAlignTop)

### Steps to reproduce
```
group.addShape('image', {
              attrs: {
                img:"base64图片",
                x: 18   nodeOrigin.x,
                y: nodeOrigin.y   68,
              },
              name: 'flag-shape',
            });

 graph.updateChildren([], node.id);
```

使用 graph.refreshItem(item); graph.changeData(); 可以正常加载子节点

| Environment | Info |
|---|---|
| g6 | 4.3.4 |
| System | - |
| Browser | - |

**Comment by baihech** [comment]
https://github.com/antvis/G6/issues/2911

**Comment by Yanyan-Wang** [comment]
出现了什么问题？请提供复现的在线 demo

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
