### ISSUE TITLE
treeGraph支持在节点上添加兄弟节点吗？或者说有其他办法来解决这个问题？

### ISSUE THREAD

**Issue by auuunya** [antvis/G6#3067]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/g6-treegraph-83jj0)

### Steps to reproduce
rt

| Environment | Info |
|---|---|
| g6 | 4.3.4 |
| System | - |
| Browser | chrome |

---
是否可以在树图添加一个兄弟节点，类似于demo中，目前已知问题：
1. 添加兄弟节点必须指定位置，不然所有兄弟节点都在0,0上，是否可以不指定让其自己展示在兄弟节点上边或者下边？
2. 如果子节点达两个以上，顺序点击之后整个图会乱；

![image](https://user-images.githubusercontent.com/19323736/127457048-cdc27224-f996-4e96-8db3-6204bc3c5785.png)

**Comment by auuunya** [comment]
![image](https://user-images.githubusercontent.com/19323736/127457153-c33cd4f3-13d4-4ed6-8a14-3cb2b539e362.png)

这是想要实现的效果

**Comment by auuunya** [comment]
使用dagre实现此图，会出现新增节点始终出现在最下方
[demo](https://codesandbox.io/s/peaceful-sun-83jj0-forked-umvq8)

![image](https://user-images.githubusercontent.com/19323736/127457450-59bae97a-378d-4700-9617-dbfd780954ec.png)

有什么办法可以让其展示在点击的节点的附近吗？

**Comment by Yanyan-Wang** [comment]
TreeGraph 每个非根节点有且仅有一个父节点，根节点没有父节点。

dagre 是根据结构自动计算的，目前正在改造和升级，后面应该可以支持指定顺序之类的
