### ISSUE TITLE
如何combo、edge、node的层级设置

### ISSUE THREAD

**Issue by zmbxy95** [antvis/G6#3069]
从文档中看，三者的层级是按照一定的规则来的设置的。元素实例倒是可以设置node、edge的层级，但貌似不包含combo。

如果想要设置三者固定的层级关系，比如node > edge > combo，有什么办法做吗？

**Comment by Yanyan-Wang** [comment]
首先实例化图的时候配置 groupByTypes: false。然后对于每种元素 node/edge/combo 对象都可以调用 item.toFront() 或者 item.toBack()

**Comment by Yanyan-Wang** [comment]
groupByTypes: false 可以自由控制每个元素的 toFront toBack

**Comment by zmbxy95** [comment]
现在节点加入到combo后，拖拽combo，节点也可以跟随移动，也就是说，某些行为下，combo和其内的item是绑定在一起的，我的意思是，如何让combo和节点之间完全独立开，让他们之间没有这种联系。

**Comment by zmbxy95** [comment]
这个有办法做到吗？麻烦给个回复呗，如果不行，我再想别的办法。

**Comment by Yanyan-Wang** [comment]
啊那还要 combo 干啥，直接画个大节点在图上就好了？
