### ISSUE TITLE
force布局下节点与线分离得问题

### ISSUE THREAD

**Issue by zouliuyun** [antvis/G6#3070]
- **G6 Version**:

![image](https://user-images.githubusercontent.com/6251153/127623946-bfa1db57-d92c-4f92-a81f-f16e48ba4cda.png)

- **Mini Showcase(like screenshots)**:
- 节点较多时异常

![image](https://user-images.githubusercontent.com/6251153/127624022-e653d5f1-1017-4958-8874-dcf8e56cf547.png)

- 关联节点较少时正常
![image](https://user-images.githubusercontent.com/6251153/127624146-e0245d99-0606-48e6-b59d-7fa2b38d60c3.png)

- **CodePen Link**:
https://codesandbox.io/s/cocky-hermann-x7lcw?file=/index.js

**Comment by Yanyan-Wang** [comment]
官网 demo 没问题，对比一下哪里不一样呢？

**Comment by Yanyan-Wang** [comment]
请升级一下 G6 (目前最新 4.3.6)

尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
