### ISSUE TITLE
自定义多标签边，拖拽节点，边上文本无法跟随更新

### ISSUE THREAD

**Issue by SLin0218** [antvis/G6#3072]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wizardly-snyder-u3vjq)

### Steps to reproduce
自定义边，添加text图像后，使用 drag-canvas 后无法拖动 label

| Environment | Info |
|---|---|
| g6 | 4.3.4 |
| System | - |
| Browser | - |

**Comment by SLin0218** [comment]
```
const labelStart = group.addShape("text", {
        attrs: {
            text: cfg.labelStart,
            stroke: cfg.style?.stroke || "#000",
            textAlign: "start",
            textBaseline: "bottom",
            x,
            y,
        },
        draggable: true,
        name: "labelStart",
});
```

**Comment by Yanyan-Wang** [comment]
拖动 label 啥意思？边本来就不能拖拽呀。如果你意思是拖拽节点，边上文本跟随更新的话，设置 update: undefined，和 afterDraw 平级

**Comment by SLin0218** [comment]
@Yanyan-Wang 谢谢 就是这个意思
