### ISSUE TITLE
Calculating neighbors without rendering

### ISSUE THREAD

**Issue by erlebach** [antvis/G6#3074]
I have read in data into a graph, using `graph.data(data)`, and woul like to take advantage of various graph methods such as `neighbors`, `inDegree`, etc.  However, this does not appear to be possible without rendering first, which I wish to avoid. Of course, I can duplicate code from G6 and modify it, but that should not be necessary. So, how does one transfer data to the internal structures of G6 (adjacency matrices, neighbors, etc.) without actually performing the rendering. One approach would be to first make all the nodes invisible.. But Antv/G6 might have some built-in functionality. Thank you.

**Comment by Yanyan-Wang** [comment]
Refer to this repo pls https://github.com/antvis/algorithm

**Comment by Yanyan-Wang** [comment]
Hi, dear user. Since there was no response for a long time, we cannot figure out the answer of the problem you described. If there is new progress, feel free to open a new issue.
