### ISSUE TITLE
Edge that be marked as comboEdge are missing when read edges from layout algorithm

### ISSUE THREAD

**Issue by GreyPlane** [antvis/G6#3076]
**What problem does this feature solve?**

+ missing edges cause some layout(at least dagre) completely not working when has some edges from combo to node and vice versa.
+  algorithm itself(eg. dagre) seems support layout graph that mix connect edge and it's parent, and some other algorithm lib(eg. ELK's layered layout) seems support it perfectly too.

**What does the proposed API look like?**

just pass it into edges or some new prop like comboEdges

**Comment by Yanyan-Wang** [comment]
Yes, only the comboForce layout will consider the comboEdge. And for dagre, we are going to modify it and it is in progress

**Comment by pjxxcc** [comment]
@Yanyan-Wang 你好，我尝试自定义layout，但是发现在init和execute方法中接收到的edges缺失了连接到combo的edge。
请问有什么办法不过滤和combo相关的edge么，至少在自定义layout中不应该过滤掉任何edge

**Comment by Yanyan-Wang** [comment]
> @Yanyan-Wang 你好，我尝试自定义layout，但是发现在init和execute方法中接收到的edges缺失了连接到combo的edge。 请问有什么办法不过滤和combo相关的edge么，至少在自定义layout中不应该过滤掉任何edge

现在自定义布局中可以拿到 comboEdges、vedges 等

**Comment by Yanyan-Wang** [comment]
We have a new layout for combo graph named ComboCombined, have a try
- demo: https://g6.antv.antgroup.com/examples/net/comboLayout/#comboCombined
- API: https://g6.antv.antgroup.com/en/api/graphlayout/combocombined
