### ISSUE TITLE
Low performance on forceAtlas2

### ISSUE THREAD

**Issue by florian-stoica-tlabs** [antvis/G6#3078]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/withered-bash-fi58n?file=/src/index.js:995-1008)

### Steps to reproduce
My data contains: 2585 nodes and 3669 edges
 
 Rendering took 1m 38s
 
 I do aim to render a force directed graph I did look over the documentation and over the performance usecases but in the performance usecases the positioning of the graph is already computed so the lib's job remains to display directly. 
The graph that I will present will be changed depending on filters added by the user...such filter might limt the data but the above example is most of an middle sized graph.
The graph is not editable but changing filter params is most common so the layout needs to be redone and waiting over 1m after new data(data may be completly different) comes in seems quite long.

Also tried 'force' layout with workerEnabled for that case it was faster but the nodes were too close together nodeSpacing function was never called.

If there is any way that I can render this nicely and improved that would be nice.

| Environment | Info |
|---|---|
| g6 | 4.3.4 |
| System | - |
| Browser | - |

**Comment by Yanyan-Wang** [comment]
The performance usecases aim to show the performance of rendering. 

workerEnabled is just put the computation to a worker which will not block the UI, but it will not speed up the computation.

For the large graph layout, first, try gpuEnabled: true for gForce or fruchterman, which are also force-directed algorithms with different force models, and they support gpu parallel computing. Second, if the data is too large to be realtime computed by front-end, we suggest you to do the layout computing on the server instead.

**Comment by florian-stoica-tlabs** [comment]
@Yanyan-Wang Thanks for the response, will try the above and see where I will get with it.

For layout computing on the server-side can you recommend something (using Java server side)?

**Comment by Yanyan-Wang** [comment]
Maybe try node.js? And the @antv/layout may be available on node.

**Comment by Yanyan-Wang** [comment]
Hi, dear user. Since there was no response for a long time, we cannot figure out the answer of the problem you described. If there is new progress, feel free to open a new issue.
