### ISSUE TITLE
combo初始化全部设置为combo.collapsed = true时，combo重叠

### ISSUE THREAD

**Issue by yuzhu0223** [antvis/G6#3079]

**Comment by Yanyan-Wang** [comment]
你是说用了什么布局吗？如果不是的话，combo 在 collapsed 状态下可以设置 x y 调整一下

**Comment by yuzhu0223** [comment]
用的是comboForce布局。x,y的话是给node节点设置吗，给combo设置的没效果

**Comment by Yanyan-Wang** [comment]
comboForce 的话应该不会吧？你看下这个例子 https://codesandbox.io/s/nostalgic-jennings-m29yy

 > 如果不是的话，combo 在 collapsed 状态下可以设置 x y 调整一下

记错了，是 combo 为空时是可以设置 x y 的。内部有节点的话，它会根据内部节点位置来计算自己的大小和位置

**Comment by Yanyan-Wang** [comment]
欢迎试用新增的 comboCombined
- demo: https://g6.antv.antgroup.com/examples/net/comboLayout/#comboCombined
- API: https://g6.antv.antgroup.com/api/graphlayout/combocombined

尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
