### ISSUE TITLE
需要为 minimap 插件增加一个 destroy 行为

### ISSUE THREAD

**Issue by pinggod** [antvis/g6#308]
* **G6 Version**: 2.0.1
* **Platform**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
* **Mini Showcase(like screenshots)**: none
* **CodePen Link**: none

希望提供一个 Minimap 插件的 destroy 方法销毁现有的 minimap 节点，便于在重复创建 G6 实例时同步更新  Minimap 实例。

**Comment by TomHuangCN** [comment]
已修复
