### ISSUE TITLE
原先node之间的edge是虚线，每个combo都折叠起来之后，虚线变成实线了，这个要怎么处理继续保持虚线？且是否能combo折叠起来之后，让edge也折叠为一根edge

### ISSUE THREAD

**Issue by yuzhu0223** [antvis/G6#3080]

**Comment by Yanyan-Wang** [comment]
combo edge 应该使用的是 defaultEdge 里定义的样式。如果要用某些特定样式，可以配置一下 defaultEdge。

如果折叠后起点终点一致的话，现在应该是合并成一条的吧

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
