### ISSUE TITLE
[功能要求] 树图布局 缩进树Indented 的 indent 属性支持设置function 

### ISSUE THREAD

**Issue by pwpow** [antvis/G6#3081]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
根据节点属性，动态设置缩进

### What does the proposed API look like?
indent 属性支持function设置

**Comment by Yanyan-Wang** [comment]
该功能官方暂时没有排期，欢迎社区小伙伴参与共建哦～

**Comment by pwpow** [comment]
> 该功能官方暂时没有排期，欢迎社区小伙伴参与共建哦～

是否有相关文档，便于入门并参与共建

**Comment by Yanyan-Wang** [comment]
这里有一个寻找共建着的 issue ，有意向可以加一下群，然后回复一下你想加的 feature，我添加到表格里并 at 你。https://github.com/antvis/G6/issues/2535 

这里有一个 G6 的简单的开发者快速开始：https://github.com/antvis/G6/blob/master/README.md#development

树图布局是在另外一个仓库 @antv/hierarchy https://github.com/antvis/hierarchy，你说的这个功能应该是要加到这个库里

**Comment by pwpow** [comment]
> 这里有一个寻找共建着的 issue ，有意向可以加一下群，然后回复一下你想加的 feature，我添加到表格里并 at 你。#2535
> 
> 这里有一个 G6 的简单的开发者快速开始：https://github.com/antvis/G6/blob/master/README.md#development
> 
> 树图布局是在另外一个仓库 @antv/hierarchy [https://github.com/antvis/hierarchy，你说的这个功能应该是要加到这个库里](https://github.com/antvis/hierarchy%EF%BC%8C%E4%BD%A0%E8%AF%B4%E7%9A%84%E8%BF%99%E4%B8%AA%E5%8A%9F%E8%83%BD%E5%BA%94%E8%AF%A5%E6%98%AF%E8%A6%81%E5%8A%A0%E5%88%B0%E8%BF%99%E4%B8%AA%E5%BA%93%E9%87%8C)

直接提PR么，还是需要先在群里知会？
