### ISSUE TITLE
IE上g6自定义事件报错，节点渲染不出来

### ISSUE THREAD

**Issue by lichunli6456** [antvis/G6#3082]
vue/cli2.x项目
IE上出不来

![111](https://user-images.githubusercontent.com/34017585/129036027-da269825-ad25-4341-8a16-70cd17c63105.jpg)

**Comment by Yanyan-Wang** [comment]
图片好像没上传成功，看不到

**Comment by lichunli6456** [comment]
不好意思，才更新图片

**Comment by Yanyan-Wang** [comment]
其它浏览器是可以的么

**Comment by liuqing519** [comment]
> 其它浏览器是可以的么

我也遇到类似的问题，其他浏览器可以，ie报错，请问这个问题解决了吗，如何解决

**Comment by Yanyan-Wang** [comment]
不再考虑支持 IE，因为 IE 已经下架啦～
