### ISSUE TITLE
TreeGraph 左上角隐藏

### ISSUE THREAD

**Issue by zfha** [antvis/G6#3083]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

<img width="961" alt="企业微信截图_c4777151-3b58-41fb-886e-f7d3f52e2d70" src="https://user-images.githubusercontent.com/4082233/128118029-3cea4ba9-f113-4d7d-bfd4-aa7dc28a83dc.png">

### Reproduction link
[https://g6.antv.vision/zh/examples/case/treeDemos#decisionTree](https://g6.antv.vision/zh/examples/case/treeDemos#decisionTree)

### Steps to reproduce
去掉 fitView=true

| Environment | Info |
|---|---|
| g6 | 4.3.5 |
| System | - |
| Browser | - |

**Comment by zfha** [comment]
我期望从左上到右下排布，所以去掉fitView=true，结果导致所上交元素隐藏一部分

**Comment by auuunya** [comment]
toMove移动或者加padding

**Comment by Yanyan-Wang** [comment]
moveTo(x, y) 可以把图的左上角对齐到你指定的 x y 上。
