### ISSUE TITLE
Fruchterman 布局的 API描述错误

### ISSUE THREAD

**Issue by zmbxy95** [antvis/G6#3084]
![image](https://user-images.githubusercontent.com/50108232/128144785-b40ec460-1c29-460f-9238-2fefb00623b9.png)

**Comment by zmbxy95** [comment]
位置：
![image](https://user-images.githubusercontent.com/50108232/128145018-dca49b68-7cff-43de-868e-8b8e502b5379.png)

**Comment by Yanyan-Wang** [comment]
感谢报告，马上修复
