### ISSUE TITLE
请问下有没有类似dispatchEvent的功能，看到现在只有on和off事件

### ISSUE THREAD

**Issue by Laochake96** [antvis/G6#3085]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
某些场景下主动触发事件回调

### What does the proposed API look like?
graph.dispatch("r-collapse-text:click"); // r-collapse-text可以是Node Edge 或者 Shape
或者target.disPatchEvent(event)之类的形式

**Comment by Yanyan-Wang** [comment]
graph.emit('r-collapse-text:click', e) 可以触发这个事件

**Comment by Laochake96** [comment]
> graph.emit('r-collapse-text:click', e) 可以触发这个事件

可以了哈感谢～  graph.emit('r-collapse-text:click', {item, shape}), 模拟完后可以了，  这个emit事件文档如果可以补充一下就更好了呢～

**Comment by Yanyan-Wang** [comment]
好的，感谢建议
