### ISSUE TITLE
mousemove and mouseup not working correctly on nodes/combos if mouse button is held down on move

### ISSUE THREAD

**Issue by JoshSuttorBC** [antvis/G6#3086]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mousedownplusmousemove-7lrfd?file=/src/index.js)

### Steps to reproduce
Try clicking and dragging on the canvas. Now try clicking and dragging on the node. The same behavior is defined for both. 

| Environment | Info |
|---|---|
| g6 | 4.3.0 |
| System | MacOS Big Sur (maybe others) |
| Browser | tested in chrome 92.0.4515.107, firefox 92.0.4515.107, safari 14.1.2 |

---
I have a case where I need to define special behavior for when I click and drag on a combo/node. In my sandbox, I have mousedown, mousemove, and mouseup defined for canvas and node. On canvas and on text that is placed on the nodes, when I hold in the primary mouse button while moving the mouse, everything triggers as expected. On nodes, however, if I hold click and move the mouse, mousedown occurs as expected, but mousemove is not triggered, and mouse up does not get triggered when I release mouse click. Mouseup does get triggered on nodes if I never move the mouse while click is held. The issue is also present for combos. The issue seems to be worse on Safari.

**Comment by Yanyan-Wang** [comment]
please replace mousedown mousemove and mouseup by dragstart drag and dragend

**Comment by JoshSuttorBC** [comment]
Thanks for your swift response. I oversimplified my use case to most easily show the bug. But there are reasons that I am trying to use these specific events. The drag events do not trigger on text that is placed on combos and nodes. I can get something working roughly the way that I need to by defining both the 3 mouse events and the 3 drag events with the same code. Essentially, this makes the mouse events handle text and the drag events handle other shapes. But this causes inconsistent behavior when using tooltips. When dragging on text, the tooltip moves with the combo. When dragging on the rest of the combo, the tooltip stays put, and if the cursor intersects with the tooltip while dragging, the drag event is no longer triggered. I also have need for my events to start on mousedown instead of dragstart, so having separate code for mousedown and dragstart unnecessarily complicates things. Fixing the mouse related events should solve my issues.

**Comment by Yanyan-Wang** [comment]
I think the problem is, `node:mousemove` is not triggered when the mouse is down on node, we will try to figure it out but I think it may take some time because we are short of maintainers now…… And we welcome PRs from communities!

Quick solutions: 

Are you using custom node and custom combo? If so assign draggable: true to the inner shapes, such as the texts, the inner shapes will response the drag events too. P.S. `draggable` has the same level with attrs.

For tooltip, you can call `tooltip.hide()` in the listener of `combo:dragstart` and `node:dragstart`

**Comment by Kido-200** [comment]
> combo

我也遇到了这个问题，我想实现的是点击一个节点，然后按住鼠标移动的时候有一条线连接节点和鼠标位置，移到另一个节点松手就把两个节点连一起。
mousedown里addItem虽然跑了，但canvas里看不见这条线，并且move事件一开始会触发一下后面就不会被调用了。鼠标抬起后线和move事件都正常了

https://codesandbox.io/s/quizzical-night-ymsvnf?file=/src/App.tsx

**Comment by Kido-200** [comment]
> I think the problem is, `node:mousemove` is not triggered when the mouse is down on node, we will try to figure it out but I think it may take some time because we are short of maintainers now…… And we welcome PRs from communities!
> 
> Quick solutions:
> 
> Are you using custom node and custom combo? If so assign draggable: true to the inner shapes, such as the texts, the inner shapes will response the drag events too. P.S. `draggable` has the same level with attrs.
> 
> For tooltip, you can call `tooltip.hide()` in the listener of `combo:dragstart` and `node:dragstart`


combo

我也遇到了这个问题，我想实现的是点击一个节点，然后按住鼠标移动的时候有一条线连接节点和鼠标位置，移到另一个节点松手就把两个节点连一起。
mousedown里addItem虽然跑了，但canvas里看不见这条线，并且move事件一开始会触发一下后面就不会被调用了。鼠标抬起后线和move事件都正常了

https://codesandbox.io/s/quizzical-night-ymsvnf?file=/src/App.tsx

**Comment by Kido-200** [comment]
> > I think the problem is, `node:mousemove` is not triggered when the mouse is down on node, we will try to figure it out but I think it may take some time because we are short of maintainers now…… And we welcome PRs from communities!
> > Quick solutions:
> > Are you using custom node and custom combo? If so assign draggable: true to the inner shapes, such as the texts, the inner shapes will response the drag events too. P.S. `draggable` has the same level with attrs.
> > For tooltip, you can call `tooltip.hide()` in the listener of `combo:dragstart` and `node:dragstart`
> 
> 我也遇到了这个问题，我想实现的是点击一个节点，然后按住鼠标移动的时候有一条线连接节点和鼠标位置，移到另一个节点松手就把两个节点连一起。 mousedown里addItem虽然跑了，但canvas里看不见这条线，并且move事件一开始会触发一下后面就不会被调用了。鼠标抬起后线和move事件都正常了
> 
> https://codesandbox.io/s/quizzical-night-ymsvnf?file=/src/App.tsx

照着源码里的drag-node.ts写解决了，不用custom node也行

**Comment by Yanyan-Wang** [comment]
solved by v4.8.0
