### ISSUE TITLE
IE11下，svg渲染模式，自定义dom节点报错，对象不支持 getBBox

### ISSUE THREAD

**Issue by mark0325** [antvis/G6#3088]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/mark0325/g6-ie11](https://github.com/mark0325/g6-ie11)

### Steps to reproduce
IE11 下直接报错，对象不支持 getBBox

| Environment | Info |
|---|---|
| g6 | 4.3.5 |
| System | win10 |
| Browser | IE 11 |

**Comment by mark0325** [comment]
@Yanyan-Wang  这个不需要处理，自定义DOM节点是通过foreignObject标签实现的，但是IE11这个糟糕的浏览器不支持foreignObject标签，不知道你们可有解决方案，如果没有，希望再文档上说明下

**Comment by Yanyan-Wang** [comment]
是的，目前没有什么方案。如果可以的话，尽量用 canvas 呢，其实它的自由度很高的

**Comment by SS-13** [comment]
>
请问我也遇到这个问题， renderer改成成canvas 直接报 s[i] is not a constructor
svg 和 canvas的配置方式不一样的吗
