### ISSUE TITLE
自定义节点不会自动调整间距，导致覆盖（React custom-made node will overlap each other）

### ISSUE THREAD

**Issue by jasontianxie** [antvis/G6#3089]
使用react方式创建的节点https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/react-node
![企业微信截图_20210805111903](https://user-images.githubusercontent.com/24238063/128285562-377a06fa-d9d9-476e-8266-17ceb0d70348.png)

**Comment by mxz96102** [comment]
因为react-node不会更改节点本身的定义大小，所以需要你在node里面加上size: [width, height]这样的信息来辅助布局

**Comment by jasontianxie** [comment]
好的，谢谢

> 因为react-node不会更改节点本身的定义大小，所以需要你在node里面加上size: [width, height]这样的信息来辅助布局
