### ISSUE TITLE
2.0 注册文档

### ISSUE THREAD

**Issue by Slardar888** [antvis/g6#309]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

基于1.x版本做了一个简易版编辑器，迭代到2.0，关于注册的文档个人能力有限不是很明白，也希望g6-editor进展顺利能尽早开源让我们更多学习。感谢。

**Comment by TomHuangCN** [comment]
努力中
