### ISSUE TITLE
Text文本超长时，后面的内容覆盖了前面的内容（if text too long，it will overlap previous text in react custom-made node）

### ISSUE THREAD

**Issue by jasontianxie** [antvis/G6#3090]
在react定义https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/react-node
的节点中使用了多个Text组件，当后面的Text组件中的文本超长时，会覆盖掉前面文本的内容
![企业微信截图_20210805112203](https://user-images.githubusercontent.com/24238063/128286047-c0a0f87d-8f4c-43ff-9c57-e78c1d8b7679.png)

**Comment by mxz96102** [comment]
请问能提供一下sample吗，我这边无法了解到底是哪个元素Text溢出导致的
（还有就是不建议有大量的Text，性能上有一点问题）

**Comment by jasontianxie** [comment]
`const Log = ({ cfg }: {cfg: ModelConfig}) => {
    const { meta } = cfg
    const data = (meta as {data: IDataDetail | undefined}).data
    return (
      <Group>
        <Rect
          style={{
            width: 600,
            height: 'auto',
            fill: '#fff',
            stroke: '#ddd',
            shadowColor: '#eee',
            shadowBlur: 30,
            radius: [8],
            justifyContent: 'center',
            padding: [18, 0],
            margin: [0, 0, 0, -300]
          }}
        >
          {data?.details.concat({color: getResultColor(data?.details), key: '结论', value: data.result})?.map((item: ISoloDetail) => 
            {
              return (
              <Text key={item.key} style={{ fill: item.color, fontSize: 16, margin: [12, 24] }}>
                {fittingString(`${item.key} : ${item.value}`, 600, 20)} //这里做了一下换行，参考的这里https://g6.antv.vision/zh/examples/item/label#labelLen1
              </Text>
              )
            }
          )}
        </Rect>
      </Group>
    );
  };
G6.registerNode('log', {...createNodeFromReact(Log), getAnchorPoints() {
    return [
      [0.5, 0], // top
    ];
  }});
`

**Comment by jasontianxie** [comment]
`const Log = ({ cfg }: {cfg: ModelConfig}) => {
    const { meta } = cfg
    const data = (meta as {data: IDataDetail | undefined}).data
    return (
      <Group>
        <Rect
          style={{
            width: 600,
            height: 'auto',
            fill: '#fff',
            stroke: '#ddd',
            shadowColor: '#eee',
            shadowBlur: 30,
            radius: [8],
            justifyContent: 'center',
            padding: [18, 0],
            margin: [0, 0, 0, -300]
          }}
        >
          {data?.details.concat({color: getResultColor(data?.details), key: '结论', value: data.result})?.map((item: ISoloDetail) => 
            {
              return (
              <Text key={item.key} style={{ fill: item.color, fontSize: 16, margin: [12, 24] }}>
                {fittingString(`${item.key} : ${item.value}`, 600, 20)} 
              </Text>
              )
            }
          )}
        </Rect>
      </Group>
    );
  };
G6.registerNode('log', {...createNodeFromReact(Log), getAnchorPoints() {
    return [
      [0.5, 0], // top
    ];
  }});
`

**Comment by jasontianxie** [comment]
这里是节点的定义
![企业微信截图_20210805143114](https://user-images.githubusercontent.com/24238063/128302443-45e342ab-ad13-4274-b7f6-1beb1e618064.png)
这里是注册节点
![企业微信截图_20210805143129](https://user-images.githubusercontent.com/24238063/128302510-33ae7461-030c-4dab-811f-4e74c0caf356.png)
文本换行，参考了https://g6.antv.vision/zh/examples/item/label#labelLen1

**Comment by jasontianxie** [comment]
目前想到的是动态设置marginTop ？
![企业微信截图_20210805145002](https://user-images.githubusercontent.com/24238063/128304577-f384fa03-c872-4ebb-b26f-31cda02d60c0.png)
