### ISSUE TITLE
focusItem() not working correctly after changing data using graph.read() or graph.changeData()

### ISSUE THREAD

**Issue by ptm108** [antvis/G6#3091]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/frosty-breeze-yjf3j?file=/src/index.js)

### Steps to reproduce
1. graph.read(initialData)
2. graph.read(newData) -> triggered by external event/click
3. graph.find('node') 
4. graph.focusItem(node)

| Environment | Info |
|---|---|
| g6 | 4.3.5 |
| System | - |
| Browser | - |

---
Hi all, first of all, thanks for the awesome library. 

I'm using antv with React (v17.0.2) and I'm encountering an issue with focusItem not working correctly after changing the graph data. I'm using a dagre layout changing the data using graph.read() or graph.changeData(), and searching   focusing on a node after changing data. 

focusItem is working well when data is not changed, but after data is changed focusItem just moves to the top right of the canvas

**Comment by mxz96102** [comment]
Notice that using changeData or read is an async process, so suggest you to focus it on graph after render

**Comment by mxz96102** [comment]
in your code it work when write like this
```js
setTimeout(() => {
  graph.changeData(data2);
}, 1000)

// simulate changing of data + focusItem
setTimeout(() => {

  const node = graph.find("node", (node) => {
    return node.get("model").id === "node10";
  });
  console.log(node);
  graph.focusItem(node, true, {
    easing: "easeCubic",
    duration: 500
  });
}, 5000);
```

**Comment by mxz96102** [comment]
using a hook is also a choice: https://g6.antv.vision/zh/docs/api/Event#%E6%97%B6%E6%9C%BA%E4%BA%8B%E4%BB%B6

**Comment by ptm108** [comment]
Thank you very much! Got it to work with the afterrender hook 
```javascript
  useEffect(() => {
    if (graph && focus) {
      graph.on("afterrender", (e) => {
        const node = graph.find("node", (node) => {
          return node.get("model").title === focus;
        });
        if (!node) return;
        console.log(node);
        graph.focusItem(node, true, {
          easing: "easeCubic",
          duration: 500,
        });
        graph.setItemState(node, "selected", true);
      });
    }
  }, [focus]);
```
