### ISSUE TITLE
G6插件ToolBar的handleClick父组件传的值不会更新

### ISSUE THREAD

**Issue by QDSG** [antvis/G6#3093]
子组件：

```
const toolbar = new G6.ToolBar({
    position: {
        x: 500,
        y: 600,
    },

    handleClick: (code, graph) => {
        if(handleToolClick) {
            handleToolClick(code, graph, toolbar)
        }
    }
});
```

这儿尝试通过父组件中的handleToolClick方法自定义实现工具栏中的功能

父组件：
```
import { connect } from 'react-redux';
const mapStateToProps = ({ graphReducer }) => {
    const { operationStack } = graphReducer;
    return {
        operationStack,
    };
}   //获取operationStack的值
export default connect(mapStateToProps)(( { operationStack} ) => {
    ...
    const handleToolClick = (code, graph, toolbar) => {
        console.log(operationStack)
    }
    ...
})
```
operationStack这个值是存储在项目的react-redux中的
结果打印出来的值，一直是定义operationStack时的初值，在改变了operationStack值之后这边打印出来的还是初值，在operationStack的值改变以后这个方法没有同步到数据

想实现的需求：画布的撤回改为一次性操作的撤回，而不是单个操作的撤回，所以我设置了一个值用来存放每次操作的步数，这样撤回的时候就可以通过调用指定次数的撤回/回退，从而达到同样的效果

看了源码也没搞懂为什么这边的值只获取到了初值就没了,求大佬指点[鞠躬][感谢]

**Comment by Yanyan-Wang** [comment]
建议在 handleClick 里面去 setState 一个信号值，然后在 useEffect 里面监听这个信号值变化调用后面的函数

**Comment by QDSG** [comment]
> 建议在 handleClick 里面去 setState 一个信号值，然后在 useEffect 里面监听这个信号值变化调用后面的函数
我解决啦，感谢🙏
