### ISSUE TITLE
点击流程图每一个节点无法无法再展示一个流程图，数据和Id都能获取到但是无法更新到dom

### ISSUE THREAD

**Issue by ayouyouy** [antvis/G6#3094]
需求介绍：初始化进入界面展示一个总数据流程图，点击每一个节点在右侧展示这个节点的详细流程图
问题：  当点击节点的时候详细流程图无法显示，日志打印显示数据有获取到，id也有获取到但是页面上流程图无法显示
代码：
[问题代码.docx](https://github.com/antvis/G6/files/6937563/default.docx)

**Comment by Yanyan-Wang** [comment]
请提供在线  demo 哦

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
