### ISSUE TITLE
Watermark is on exported image even though documentation states it should not

### ISSUE THREAD

**Issue by genert** [antvis/G6#3097]
Quoting the [watermarking documentation](https://antv-g6.gitee.io/en/docs/api/graphFunc/watermarker):

>Add image water markers for the graph. **Note that, images downloaded by downloadImage or downloadFullImage will not contains the water markers.**

The last part states that images downloaded to do not contain water markers.

However, this is incorrect as the code clearly includes watermark into the downloadable image:

https://github.com/antvis/G6/blob/ccce26182f2f3b3c6bdc61dc86ae3031c69cca32/packages/pc/src/graph/graph.ts#L353

This results the following exported image:
![sandbox_graph_screenshot (3)](https://user-images.githubusercontent.com/1218788/128488026-810512c1-12b8-481d-8794-915bc43d319d.png)

Either correct the documentation, or make it optional to include watermarks on the exported image.

**Comment by Yanyan-Wang** [comment]
Thanks for reporting, we will fix the docs as soon as possible
