### ISSUE TITLE
多个布局使用pipes报错

### ISSUE THREAD

**Issue by emmaiu** [antvis/G6#3099]
nodeA属于布局a, 其中nodeA连线的nodeB属于布局b, 使用pipes报错：
at math.js:
error:  graph layout failed, TypeError: Cannot set property '8' of undefined 
报错的原因是nodeA属于布局a, 但与nodeA相连的nodeB属于布局b, 在edges循环时找不到对应的nodeMap里值报错，渲染布局失败

**Comment by Yanyan-Wang** [comment]
https://g6.antv.vision/zh/examples/net/layoutMechanism#sublayoutPipes

这个例子好像没有报错？是否有复现的在线 demo？

**Comment by ColinChen2** [comment]
可以给你demo链接吗？
现在的策略是可以配置nodesFilter和edgesFilter。但是他们都是可选的。
nodesFilter默认是所有的node都可以。
edgesFilter默认是source和target都存在才可以通过。
