### ISSUE TITLE
item.updatePosition() is not working

### ISSUE THREAD

**Issue by dany-pa** [antvis/G6#3100]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/item-updateposition-is-not-working-871s9?file=/src/components/HelloWorld.vue)

### Steps to reproduce
just run codeSandbox

| Environment | Info |
|---|---|
| g6 | 4.3.4 |
| System | - |
| Browser | - |

---
Hello!
I want to draw two graphs. Blue graph is main, and gray graph need to be position inside the blue blocks.
![image](https://user-images.githubusercontent.com/82453071/128755407-b7bfca0f-a32e-4b61-af6a-ad470e04af64.png)

But now i can draw only like this:
![image](https://user-images.githubusercontent.com/82453071/128755527-ee4d1f52-6a45-4c87-8fc1-652d90f2b310.png)

My graph config:

```javascript
const graph = new G6.Graph({
    container: "container",
    width: 800,
    height: 500,
    fitView: true,
    animate: true,
    modes: {
        default: ["drag-canvas", "zoom-canvas"]
    },
    plugins: [minimap],
    layout: {
        pipes: [
            {
                type: "dagre",
                rankdir: "TB",
                nodesep: 30,
                ranksep: 15,
                controlPoints: true,
                nodesFilter: node => {
                    return node.graph == "main";
                }
            },
            {
                type: "circular",
                nodesFilter: node => {
                    return node.graph !== "main";
                }
            }
        ]
    },
    defaultEdge: {
        type: "polyline",
        style: {
            stroke: "#808080",
            lineWidth: 1
        }
    }
});
```

And after 
```javascript
graph.data(data);
graph.render();
```

I tried to position gray graph inside the blue graph:
```javascript
const rect1 = graph.findById('rect1').getModel();
const secondRect1 = graph.findById('secondRect1');
secondRect1.updatePosition({
    x: rect1.x,
    y: rect1.y,
})
```

But it's do nothing. In the console.log i see, that value is change, but on the screen nothing changes.
I tried all methods for update canvas that i find, but it's do nothing too.

```javascript
graph.refresh()
graph.refreshPositions()
graph.paint()
```

How can i fix it?

**Comment by Yanyan-Wang** [comment]
```
graph.updateItem(nodeId, {
  x: some value
  y: some value
})
```

**Comment by Yanyan-Wang** [comment]
Since the pipe layout is asynchronous, you should use the coordinates in graph.on('afterlayout', e => {});

```
graph.on('afterlayout', e => {
    const rect1 = graph.findById("rect1").getModel();
    const secondRect1 = graph.findById("secondRect1");
    graph.updateItem(secondRect1, {
      x: rect1.x,
      y: rect1.y,
    })
})
```

**Comment by dany-pa** [comment]
Thank you very much!
