### ISSUE TITLE
两个节点可以做双向箭头吗，label不一样的两根

### ISSUE THREAD

**Issue by QDSG** [antvis/G6#3102]
我看双向的可以画出来，但是label不一样，两根的话可能edge就是两个数据。。。但是我试一下会把前一个的label覆盖掉。。。
需求：通过箭头描述两个节点的关系，比如有两个节点A、B，A->B是一种关系，B->A是另一种关系
求大佬帮忙🙏

**Comment by Yanyan-Wang** [comment]
那就是画两条平行边吧？https://g6.antv.vision/zh/examples/item/multiEdge#multiEdges

**Comment by QDSG** [comment]
> 那就是画几条边吧？https://g6.antv.vision/zh/examples/item/multiEdge#multiEdges

没看到没看到，感谢🙏🙏
