### ISSUE TITLE
你好，关于官网文档的列子链接，404 not Found

### ISSUE THREAD

**Issue by zhuibo66** [antvis/G6#3103]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g6.antv.vision/zh/docs/api/Graph](https://g6.antv.vision/zh/docs/api/Graph)

### Steps to reproduce
下面这几个列子，都是404 not Found
基础动画教程：https://g6.antv.vision/zh/docs/manual/advanced/animation#animatecfg
Graph 内置布局：https://g6.antv.vision/zh/docs/api/G6/common/graphLayout

| Environment | Info |
|---|---|
| g6 | 4.3.5 |
| System | - |
| Browser | - |

**Comment by Yanyan-Wang** [comment]
感谢报告，已经修复～
