### ISSUE TITLE
使用create-edge创建边，类型为arc，quadratic，cubic会出现空白或者直接是直线的样式

### ISSUE THREAD

**Issue by lavenderMF** [antvis/G6#3104]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g6.antv.vision/zh/examples/interaction/createEdge#click-link-point](https://g6.antv.vision/zh/examples/interaction/createEdge#click-link-point)

### Steps to reproduce
官方文档上的例子直接创建边，创建类型为arc，quadratic，cubic会出现空白，拖动错乱或者直接是直线的样式

| Environment | Info |
|---|---|
| g6 | 4.3.4 |
| System | - |
| Browser | chrome |

**Comment by Yanyan-Wang** [comment]
例子中的 processParallelEdgesOnAnchorPoint 这个函数处理了当两个 anchorPoints 之间只有一条边的时候，绘制为直线
