### ISSUE TITLE
Edges position not properly set after dragging 

### ISSUE THREAD

**Issue by zhuweiji** [antvis/G6#3105]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pedantic-pike-3b3tx?file=/src/index.js)

### Steps to reproduce
Code:
1. Create on mouseleave event
2. Loop over all edges in graph and set their state during this event

Program:
1. Drag a node and let go
2. Once mouse leaves node, edges will become messed up

| Environment | Info |
|---|---|
| g6 | 4.3.5 |
| System | Windows 10 |
| Browser | On both Latest Edge/Chrome |

**Comment by zhuweiji** [comment]
Addition:
Clearing item states on canvas:click events triggers the bug too

**Comment by Yanyan-Wang** [comment]
duplicated to #3118
