### ISSUE TITLE
一张graph里面多个图可以设置距离包括排列吗？

### ISSUE THREAD

**Issue by XiangLi-coder** [antvis/G6#3106]
我在一个画板里面画一个graph，但是因为数据原因，数据与数据之间是有不同的分组的，如下面这样：
![image](https://user-images.githubusercontent.com/59185544/128999404-48f8cea4-641c-46c8-bb68-4fa7d49f834d.png)
但是这里的距离和排列都无法调整，这是放大之后的样子。
![image](https://user-images.githubusercontent.com/59185544/128999495-b60fed35-e296-43f3-a8d6-95f1cc37dc7e.png)
建议后续可以看下这个功能哈。

**Comment by Yanyan-Wang** [comment]
dagre 布局的话可以设置 ranksep nodesep。排序的话，因为使用者一般有自己的排序逻辑，建议按照自己的排序逻辑调整节点 x y 位置

**Comment by NasusLi** [comment]
> dagre 布局的话可以设置 ranksep nodesep。排序的话，因为使用者一般有自己的排序逻辑，建议按照自己的排序逻辑调整节点 x y 位置

我尝试了设置dagre布局中节点的x, y值，但是没有用呀，最终data.nodes里面的x，y值还是排列之后的。

**Comment by NasusLi** [comment]
> dagre 布局的话可以设置 ranksep nodesep。排序的话，因为使用者一般有自己的排序逻辑，建议按照自己的排序逻辑调整节点 x y 位置

我还在你们那个dagre图例中尝试修改了x，y值也是没有用的

**Comment by Yanyan-Wang** [comment]
> 我尝试了设置dagre布局中节点的x, y值，但是没有用呀，最终data.nodes里面的x，y值还是排列之后的。

需要在布局完成之后去设置，更新节点 x y graph.updateItem，否则会被布局覆盖

**Comment by NasusLi** [comment]
> > 我尝试了设置dagre布局中节点的x, y值，但是没有用呀，最终data.nodes里面的x，y值还是排列之后的。
> 
> 需要在布局完成之后去设置，更新节点 x y graph.updateItem，否则会被布局覆盖

谢谢

**Comment by NasusLi** [comment]
> > 我尝试了设置dagre布局中节点的x, y值，但是没有用呀，最终data.nodes里面的x，y值还是排列之后的。
> 
> 需要在布局完成之后去设置，更新节点 x y graph.updateItem，否则会被布局覆盖

我这边写了一下，发现还是无法更新布局呀，您可以帮忙看下吗？代码是这样的，我在你们官网的图例上面也用了updateItem，也是一样没办法更新布局。
![image](https://user-images.githubusercontent.com/59185544/131249777-56186489-d639-4694-952d-d49e1bfd16df.png)

**Comment by Yanyan-Wang** [comment]
这个是在布局完成之后去做的吗? 写一个在线的 demo 吧?

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
