### ISSUE TITLE
如何实现三维力导向图?

### ISSUE THREAD

**Issue by youdianfan** [antvis/G6#3107]
可以用自定义实现下面的,三维效果吗?
预览地址:  https://windschaser.github.io/force-three/
仓库地址:  https://github.com/windschaser/force-three

**Comment by youdianfan** [comment]
@Yanyan-Wang

**Comment by Yanyan-Wang** [comment]
短时间内不会考虑 3d graph vis

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
