### ISSUE TITLE
2.0版本中，通过npm安装后，如何import插件？

### ISSUE THREAD

**Issue by jzoe** [antvis/g6#311]
* **G6 Version**: 2.0.1
* **Platform**: npm
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

G6的基础类可以通过下面的方式引入，但是Plugin应该如何 import 引入呢？
```js
import G6 from '@antv/g6';

const graph = new G6.Graph({
  container: 'mountNode',
  width: 600,
  height: 300
});
```

试了下面的几种方法都不行：
```js
const pl = require("node_modules/@antv/g6/plugins/your-want-import")
import * as Plugin from '@antv/g6/build/toolMinimap'

```
都报如下的错误：
```js
./node_modules/@antv/g6/build/toolMinimap.js
Module not found: Can't resolve 'G6' in 'C:\Users\admin\Desktop\git\test-g6\node_modules\@antv\g6\build'
```

如果直接引用 G6.Plugins ，看G6初始化的时候只是把Plugins设置为{}，那这样拿到的是undefined的
```js
const Plugin = G6.Plugins["tool.minimap"]; //undefined
    const plugin = new Plugin({
      container: "minimap",
      width: 180,
      height: 120,
    });
```

**Comment by TomHuangCN** [comment]
官方的插件目前维护在 G6 的主仓库里，如果要使用官方提供的插件，只需要安装 `@antv/g6` 即可。

```bash
npm install @antv/g6 --save
```

可以按需要引入

```js
const G6 = require('@antv/g6');
const Minimap = require('@antv/g6/plugins/tool.minimap/');
```

也可以全部引入

```js
const G6 = require('@antv/g6');
const G6Plugins = require('@antv/g6/plugins/');
```

**Comment by jzoe** [comment]
我昨天也试过，用这种方式引入的时候也会报错

![image](https://user-images.githubusercontent.com/11612990/41392296-706a36fe-6fd2-11e8-9938-010dc48137f5.png)

**Comment by TomHuangCN** [comment]
源码是 es7 的，直接引入源码，你需要用 es7 的 loader。

**Comment by jzoe** [comment]
O_O 对于我这个非职业前端来说太复杂了，找了几个前端的同事帮忙看，也都有点懵。

**Comment by TomHuangCN** [comment]
你是用 webpack 吗？是的话，打包配置文件加这个：

```js
  module: {
    rules: [
      {
        test: /\.js$/,
        // exclude: /(node_modules|bower_components)/,
        use: {
          loader: 'babel-loader',
          options: {
            babelrc: true
          }
        }
      }
    ]
  },
```

**Comment by jzoe** [comment]
这个就是g6项目里的配置吧，我今天看到了，参考那边的试了一下，没成功。我明天再搞个测试的项目放 git 上好了。

**Comment by tianlaixhh** [comment]
最终怎么解决的呢？我在react中也遇到了

**Comment by beijingdhy** [comment]
话说有解决方案了吗

**Comment by dxq613** [comment]
正在改，提供个编译后的版本。

**Comment by TomHuangCN** [comment]
version: 2.0.4

```js
const G6 = require('@antv/g6');
require('@antv/g6/build/plugins');
```

**Comment by TomHuangCN** [comment]
要调试，要源码引入的话，只能各位自己配置 webpack 了

**Comment by jzoe** [comment]
Thanks! @TomHuangCN  等晚点有空的时候测试一把！

**Comment by spengjie** [comment]
@BusyHe 遇到过相同问题。问题原因是在外面执行这些代码时，定义的DOM还没有被创建出来，所以肯定找不到id为minimap的DOM。需要将代码放到mounted中。不能直接放到外面。

**Comment by zsl1549** [comment]
@spengjie  import G6 from '@antv/g6'; 引入就报错 什么鬼呀。55555555 求大哥们给解答.
![image](https://user-images.githubusercontent.com/32888522/49263183-5f81c280-f484-11e8-8791-4f4250beff7d.png)@all

**Comment by luoandy** [comment]
@

> @BusyHe 遇到过相同问题。问题原因是在外面执行这些代码时，定义的DOM还没有被创建出来，所以肯定找不到id为minimap的DOM。需要将代码放到mounted中。不能直接放到外面。

同样遇见过这个  咋解决啊

**Comment by luoandy** [comment]
![image](https://user-images.githubusercontent.com/20121275/49267889-8c8ba080-f497-11e8-9d65-15ce44133b73.png)
解决了

**Comment by spengjie** [comment]
> @spengjie import G6 from '@antv/g6'; 引入就报错 什么鬼呀。55555555 求大哥们给解答.
> ![image](https://user-images.githubusercontent.com/32888522/49263183-5f81c280-f484-11e8-8791-4f4250beff7d.png)@ALL

删除node_modules文件夹，重新npm install。如果还不行，把npm-package-lock.json也删了，再试一次应该就可以了。
