### ISSUE TITLE
npm 引入包报警告：The requested module './interfaces' contains conflicting star exports for the name '__esModule' with the previous requested module './types'

### ISSUE THREAD

**Issue by Manon103** [antvis/G6#3113]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/antvis/G6/](https://github.com/antvis/G6/)

### Steps to reproduce
1、新建一个项目，对antv/g6进行封装，封装后打包，发布npm包
2、在其他项目中通过yarn 安装该包，运行后报警告

| Environment | Info |
|---|---|
| g6 | 4.3.5 |
| System | mac os  |
| Browser | chrome  92.0.4515.107 |

---
"@antv/g6"："4.3.5",
"webpack": "5.36.0",
"webpack-cli": "^4.5.0"

**Comment by Manon103** [comment]
![image](https://user-images.githubusercontent.com/48952030/129301253-7e334caa-c1cd-4c36-8791-28b5ace26ee2.png)
![image](https://user-images.githubusercontent.com/48952030/129301273-07177bd4-f954-4626-aa51-5fe3389a8b8a.png)

**Comment by Yanyan-Wang** [comment]
是不是在项目中定义导出了和 G6 interface 里面定义的类型名称相同了

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
