### ISSUE TITLE
JSX element in G6 Tooltip

### ISSUE THREAD

**Issue by crslegend** [antvis/G6#3114]
- **G6 Version**: 4.3.4
- **Platform**: windows 10
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

Hi, i would like to know whether is it possible to include a jsx element to G6's tooltip as I would like to use AntDesign's tooltip, icons and button. Currently i understand i can pass in string HTML to the content of the tooltip, but it will be better if i could pass in the JSX element instead. Is that possible?

**Comment by Yanyan-Wang** [comment]
We will only support plain HTML for now. And we welcome  PRs from community for this feature. But you could custom your own DOM instead the built-in tooltip plugin. About how to amount the custom DOM, refer to: http://g6.antv.antgroup.com/en/manual/advanced/coordinate-system
