### ISSUE TITLE
如何在树图的边上获取节点中的信息

### ISSUE THREAD

**Issue by ahqrt** [antvis/G6#3115]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
let i = 0;
graph.edge(function ( edge) {
  console.log(edge)
  i  ;
  return {
    type: 'cubic-horizontal',
    color: '#A3B1BF',
    label: i,
  };
});

案例中的edge label 是使用的固定的值，假如我需要的值是要从上面的node中数据，要如何处理呢，案例是这个
https://antv-g6.gitee.io/zh/examples/tree/customItemTree#treeEdgeLabel

### What does the proposed API look like?
我希望在边处理的函数中可以拿到节点的信息

**Comment by Yanyan-Wang** [comment]
graph.getEdges(edge => {
  const sourceNodeModel = edge.getSource().getModel();
  const targetNodeModel = edge.getTarget().getModel();

  graph.updateItem(edge, {
    label: ....
  })
})

**Comment by feikerwu** [comment]
> 

这种处理方式在树图的节点缩起后，边上label会消失
