### ISSUE TITLE
在angular中无法使用fruchterman布局

### ISSUE THREAD

**Issue by yxzyxzyxz** [antvis/G6#3116]
- **G6 Version**:4.3.5
- **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/20411380/129513234-f2e28009-c744-4384-9c0e-a0a3fbb0c7e5.png)

- **CodePen Link**:

demo地址：https://gitee.com/yxzyxz/g6-chart-hull.git
graph配置：` const graph = new G6.Graph({
      container: 'container',
      width,
      defaultNode: {
        type: 'image',
        size: [100],
        clipCfg: {
          show: true,
          type: 'circle',
          r: 20
        },
        labelCfg: {
          position: 'bottom',
          offset: 10,
          style: {
            fill: '#666',
          },
        },
      },
      animate: true,
      height,
      modes: {
        default: ['drag-canvas', 'zoom-canvas', 'lasso-select'],
      },
      layout: {
        type: 'fruchterman',
        gravity: 2,
        preventOverlap: true,
        speed: 5,
        clustering: true,
        linkDistance: 60,
        nodeStrength: -10,
        edgeStrength: 0.1,
        gpuEnabled: true,
        workerEnabled: true
      },
    });`

在angular中使用fruchterman等聚类的布局时，一直无法计算完成布局

**Comment by Yanyan-Wang** [comment]
升级到 4.3.6 试试呢

**Comment by yxzyxzyxz** [comment]
4.3.6已经可以了

**Comment by dlink-chenqingyun** [comment]
> 升级到 4.3.6 试试呢

我的 angualr12 +  g6 4.3.6  frushterman 布局还是用不了
