### ISSUE TITLE
g6的依赖版本种有的协议不友好，有没有好的解决办法, 例如: @webgpu/glslang

### ISSUE THREAD

**Issue by haohailiang** [antvis/G6#3117]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
G6的依赖版本树中依赖了@webgpu/glslang@0.0.15包，该包的协议为glslang/LICENSE.txt，https://github.com/KhronosGroup/glslang/blob/master/LICENSE.txt, 其中包括了GPL协议，这个有办法解决下吗

### What does the proposed API look like?
其他修改为其他协议的依赖的包，这样代码不用必须开源了

**Comment by Yanyan-Wang** [comment]
有没有可替代的包呢

**Comment by Prostan** [comment]
Hi @Yanyan-Wang. Is it possible to add the license to @webgpu/glslang library since we could not use antvis/G6 due to license issue?

**Comment by Yanyan-Wang** [comment]
> Hi @Yanyan-Wang. Is it possible to add the license to @webgpu/glslang library since we could not use antvis/G6 due to license issue?

Sorry, @webgpu/glslang does not belong to our team, we are not able to do that.
