### ISSUE TITLE
改变edge的状态后出现连接偏移

### ISSUE THREAD

**Issue by 313812245** [antvis/G6#3118]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/bold-smoke-bksf8?file=/index.js)

### Steps to reproduce
拖拽节点，点击空白处

| Environment | Info |
|---|---|
| g6 | 4.3.5 |
| System | win10 |
| Browser | Chrome |

**Comment by Yanyan-Wang** [comment]
先用 4.3.4 吧，下个小版本会修复

**Comment by 313812245** [comment]
4.3.4的scroll-canvas有问题

**Comment by 313812245** [comment]
> 先用4.3.4吧，下个小版本会修复

4.3.4也是一样哦

**Comment by Yanyan-Wang** [comment]
> 4.3.4的scroll-canvas有问题

啥问题

**Comment by Yanyan-Wang** [comment]
> > 先用4.3.4吧，下个小版本会修复
> 
> 4.3.4也是一样哦

链接切换成 4.3.4 不会有边的偏移问题呀

**Comment by 313812245** [comment]
> > 4.3.4的scroll-canvas有问题
> 
> 啥问题

4.3.5修复了，滚动出可视区域就回不来的问题

**Comment by 313812245** [comment]
> > > 先用4.3.4吧，下个小版本会修复
> > 
> > 
> > 4.3.4也是一样哦
> 
> 链接切换成 4.3.4 不会有边的偏移问题呀

我再试试

**Comment by Yanyan-Wang** [comment]
> > > 4.3.4的scroll-canvas有问题
> > 
> > 
> > 啥问题
> 
> 4.3.5修复了，滚动出可视区域就回不来的问题

下周发小版本修复 4.3.5 的这个边的问题
