### ISSUE TITLE
复制小米关系图代码并使用本地data运行报错： Cannot read property 'isVisible' of undefined

### ISSUE THREAD

**Issue by oooofeiger** [antvis/g6#312]
* **G6 Version**: 2.0.0
* **Platform**: windows
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://codepen.io/oooofeiger/pen/yEXbKz

**Comment by TomHuangCN** [comment]
数据格式问题，数据要处理成 G6 能接收的格式。
