### ISSUE TITLE
通过updateItem更新节点位置后，节点连接断开

### ISSUE THREAD

**Issue by wuxie0ne** [antvis/G6#3120]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/suspicious-elgamal-ws7qx)

### Steps to reproduce
在布局静止后拖动A或B节点，C节点的位置通过updateItem更新后，C节点相关的连接断开。

4.3.4 的版本并没有这个问题

![image](https://user-images.githubusercontent.com/33979202/129540339-95bfc607-3410-4f15-9e73-6a48d015b3c7.png)

| Environment | Info |
|---|---|
| g6 | 4.3.5 |
| System | Windows10 |
| Browser | Chrome |

**Comment by Yanyan-Wang** [comment]
duplicated to #3118
