### ISSUE TITLE
animate: true属性突然不生效，并且无法正常渲染图型

### ISSUE THREAD

**Issue by windyboyy** [antvis/G6#3123]
这是我的配置项，当animate:true时，图形无法渲染，animate:false时，一切正常，版本4.3.4
initG6() {
      const graph = new G6.Graph({
        container: `network-${this.id}`, // String | HTMLElement，必须，在 Step 1 中创建的容器 id 或容器本身
        width: this.width, // Number，必须，图的宽度
        height: this.width, // Number，必须，图的高度
        modes: {
          default: ['drag-canvas', 'drag-node'],
        },
        layout: {
          type: 'circular',
          radius: this.width * 0.4,
          center: [this.width / 2, this.width / 2],
        },
        animate: true,
        defaultNode: {
          type: 'image',
          label: 'tango',
        },
        defaultEdge: {
          style: {
            stroke: '#6B470F',
            endArrow: true,
            startArrow: false,
            lineWidth: 1,
            strokeOpacity: 0.5,
          },
        },
      });
      graph.data(this.routeData); // 读取 Step 2 中的数据源到图上
      graph.render(); // 渲染图
      this.$emit('get-graph', graph);
    },

**Comment by Yanyan-Wang** [comment]
请提供复现的在线 demo

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
