### ISSUE TITLE
How to change z-index of edge

### ISSUE THREAD

**Issue by dany-pa** [antvis/G6#3124]
- [X] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/edge-z-index-871s9?file=/src/components/HelloWorld.vue)

### Steps to reproduce
Just run the codeSandbox

| Environment | Info |
|---|---|
| g6 | 4.3.4 |
| System | Windows |
| Browser | Google Chrome 92.0.4515.131 |

---

> Blue rects is main graph.
> Gray rects is subgraph.

I don't understad why all lines stick to the left edge of each node?
![image](https://user-images.githubusercontent.com/82453071/129612504-13c4edb2-ce2f-4a14-8e75-98291f78d33a.png)

And i want to see line over any node. Now lines of the subgraph draws under the node of the main graph.
How can i change z-index of line?
![image](https://user-images.githubusercontent.com/82453071/129612554-f5063f98-a38c-4723-82be-a7908a2693db.png)

**Comment by Yanyan-Wang** [comment]
> I don't understad why all lines stick to the left edge of each node?

you could set anchorPoints for the nodes and sourceAnchor and targetAnchor for the edges, refer to https://g6.antv.vision/en/docs/manual/middle/elements/nodes/anchorpoint/#gatsby-focus-wrapper


> And i want to see line over any node. Now lines of the subgraph draws under the node of the main graph.
How can i change z-index of line?

Assign groupByTypes: false for graph instance and call edge.toFront() or node.toBack() to controll the z-index

**Comment by Yanyan-Wang** [comment]
Hi, dear user. Since there was no response for a long time, we cannot figure out the answer of the problem you described. If there is new progress, feel free to open a new issue.
