### ISSUE TITLE
移动端不支持drag-node

### ISSUE THREAD

**Issue by youdianfan** [antvis/G6#3127]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/g6-reproduction-template-uvzdf)

### Steps to reproduce
无法在手机网页上拖拽node节点

| Environment | Info |
|---|---|
| g6 | 4.3.5 |
| System | 安卓 |
| Browser | qq浏览器 |

**Comment by Yanyan-Wang** [comment]
有点小问题，下个小版本修复
