### ISSUE TITLE
我想问一下怎么能让拖拽节点的这个操作不入栈

### ISSUE THREAD

**Issue by QDSG** [antvis/G6#3128]
因为想实现添加删除节点的撤回，感觉拖拽的加进去得撤回好几次才能撤回上一次操作
本来想的把撤回的源文件粘过来改一下，但是想知道有没有别的方法。。。
求大佬帮忙🙏🙏

**Comment by Yanyan-Wang** [comment]
下个小版本为 drag-noce behavior 加一个 enableStack 配置项，设置为 false 则不入栈
