### ISSUE TITLE
坐标轴原点的位置是如何确定的呢？

### ISSUE THREAD

**Issue by jzoe** [antvis/g6#313]
* **G6 Version**: 2.0
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

@TomHuangCN 

关于坐标的文档中 https://antv.alipay.com/zh-cn/g6/1.x/tutorial/detail-coord.html 没有说明坐标轴的原点（X与Y轴交点）的位置，这个位置是如何确定的呢？

**Comment by TomHuangCN** [comment]
https://www.yuque.com/antv/g6/custom-node#ko7wyq
