### ISSUE TITLE
自定义边的radius设置无效，怎么解决？

### ISSUE THREAD

**Issue by yanghuixia** [antvis/G6#3134]
https://g6.antv.vision/zh/examples/item/customEdge#customPolyline

**Comment by Yanyan-Wang** [comment]
这个例子中的自定义边把 path 路径已经写完整了，没有圆角的逻辑。需要圆角需要参考这里的写法在拐角的地方加 Q 指令：https://github.com/antvis/G6/blob/8072ad50a498bea76cdb36c7d5f03aeb445af10a/packages/element/src/edges/polyline-util.ts#L446
