### ISSUE TITLE
树图中，changeData 后，布局能否保持原状？

### ISSUE THREAD

**Issue by xiaofengqqcom123** [antvis/G6#3135]
期望：当 changeData 后，页面布局不会变化
版本：4.3.5
测试用例：https://codesandbox.io/s/brave-bush-7cplr?file=/index.js

**Comment by Yanyan-Wang** [comment]
把 fitView: true 配置到图上，不要在第一次渲染后调用 graph.fitView，因为这样的话只会在第一次渲染后 fitView，而 changeData 的时候没有 fitView

**Comment by xiaofengqqcom123** [comment]
> 把 fitView: true 配置到图上，不要在第一次渲染后调用 graph.fitView，因为这样的话只会在第一次渲染后 fitView，而 changeData 的时候没有 fitView

存在的问题：
1. 使用fitview 后，会自动布局，比如之前节点大小为 30px，自动布局后变成了 10px，不可接受
2. 操作顺序：任意拖拽 => changeData => fitview, 此时布局会居中。能否changeData后，回到用户拖拽位置？

**Comment by luokerenGIT** [comment]
> 把 fitView: true 配置到图上，不要在第一次渲染后调用 graph.fitView，因为这样的话只会在第一次渲染后 fitView，而 changeData 的时候没有 fitView
我用树图changeData有如下几个问题（有个定时器changeData）：
1.树图使用changeData之后怎么保持collapse-expand的状态
2.拖拽树图之后，再changeData，怎么保持坐标
3.怎么让动画只在第一次出现，而不是每次出现或者直接关掉动画
