### ISSUE TITLE
连接线修改状态后label出现偏移，label背景消失

### ISSUE THREAD

**Issue by 313812245** [antvis/G6#3136]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/determined-hooks-y7b9c?file=/index.js)

### Steps to reproduce
鼠标移入带有label的线条后移出

| Environment | Info |
|---|---|
| g6 | 4.3.5 |
| System | win10 |
| Browser | Chrome |

**Comment by 313812245** [comment]
4.3.4是直接消失的

**Comment by Yanyan-Wang** [comment]
请为 addShape 添加的图形增加不重复的 name 字段，代替 className，和 attrs 同级

**Comment by 313812245** [comment]
> 请为 addShape 添加的图形增加不重复的 name 字段，代替 className，和 attrs 同级

好的，谢谢
