### ISSUE TITLE
移动combo到另一个combo时无法合并

### ISSUE THREAD

**Issue by 313812245** [antvis/G6#3137]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/floral-sun-p3ovn?file=/index.js:946-956)

### Steps to reproduce
移动combo

| Environment | Info |
|---|---|
| g6 | 4.3.5 |
| System | win10 |
| Browser | Chrome |

---
只在开启groupByTypes且drag-combo开启enableDelegate时才会

**Comment by Yanyan-Wang** [comment]
我在你的 demo 中尝试了，可以合并呀？

**Comment by Yanyan-Wang** [comment]
步开 enableDelegate 也可以合并。groupByTypes 默认就是 true，使用 Combo 时建议设置为 false

**Comment by 313812245** [comment]
> 我在你的 demo 中尝试了，可以合并呀？

我测试时有时可以，大概率是不可以的，不知道什么原因

**Comment by 313812245** [comment]
> 步开 enableDelegate 也可以合并。groupByTypes 默认就是 true，使用 Combo 时建议设置为 false

不开enableDelegate是没有问题的

**Comment by Yanyan-Wang** [comment]
> 我测试时有时可以，大概率是不可以的，不知道什么原因

一个 combo 移入另一个 combo 的判断条件是鼠标拖拽释放的时候，鼠标的位置是在父 combo 内部的。这个和电脑上拖拽文件进入文件夹的逻辑一样

**Comment by Manon103** [comment]
> > 我测试时有时可以，大概率是不可以的，不知道什么原因
> 
> 一个 combo 移入另一个 combo 的判断条件是鼠标拖拽释放的时候，鼠标的位置是在父 combo 内部的。这个和电脑上拖拽文件进入文件夹的逻辑一样

题主给的链接是无法合并的，我的也是，enableDelegate中是否使用了capture？因为开启enableDelegate后，drop事件根本没有进入

**Comment by Yanyan-Wang** [comment]
好的, 我会跟进一下
