### ISSUE TITLE
使用setInterval 更新 graph.updateLayout， 如果node没有 edge 会超出画布，导致元素不可见

### ISSUE THREAD

**Issue by lebornjose** [antvis/G6#3139]

**Comment by lebornjose** [comment]
https://codesandbox.io/s/3p9qk?file=/index.js

**Comment by Yanyan-Wang** [comment]
因为力导布局在力的控制下，节点之间的排斥力会导致游离的节点逐渐远离，可以参考这里写一下约束让节点运动过程中不超出去 https://g6.antv.vision/zh/examples/net/forceDirected/#forceConstrainedInRect
