### ISSUE TITLE
2.0版本能否增加一些默认的edge实现，如1.x版本中的smooth？

### ISSUE THREAD

**Issue by jzoe** [antvis/g6#314]
* **G6 Version**: 2.0
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

@TomHuangCN 

1.x版本中紧凑树的例子中通过 `tree.edge().shape('smooth');` 的方式设置的 edge 渲染的比较优美。
![image](https://user-images.githubusercontent.com/11612990/41392510-94ffee9a-6fd3-11e8-8f58-749e5b01e33e.png)

现在2.0版本中的紧凑树例子 https://antv.alipay.com/zh-cn/g6/1.x/demo/gallery/gallery-tree-compact-box.html 中用下面方式注册edge
```js
G6.registerEdge('smooth', {
  getPath: function getPath(item) {
    var points = item.getPoints();
    var start = points[0];
    var end = points[points.length - 1];
    var hgap = Math.abs(end.x - start.x);
    if (end.x > start.x) {
      return [['M', start.x, start.y], ['C', start.x + hgap / 4, start.y, end.x - hgap / 2, end.y, end.x, end.y]];
    }
    return [['M', start.x, start.y], ['C', start.x - hgap / 4, start.y, end.x + hgap / 2, end.y, end.x, end.y]];
  }
});
```
但渲染的效果差强人意
![image](https://user-images.githubusercontent.com/11612990/41392556-f87f5af0-6fd3-11e8-8eed-96b6723a5669.png)

我自己也用这个 edge 定义生成的紧凑树，edge的坐标有点乱
![image](https://user-images.githubusercontent.com/11612990/41392718-0200c392-6fd5-11e8-8ef0-fe30acc603d1.png)

另外想如何获取1.x版本的源码呢？我看代码仓库中只有6月6号后提交的代码了。

想看看1.x源码中 smooth 类型的 edge 是如何实现的。

**Comment by TomHuangCN** [comment]
这种比较简单的边，2.0 还是内置了。例子的边的控制点是 hgap/4 换成 hgap/2 就解决了 
https://codepen.io/DoriTong/pen/OomgNN
