### ISSUE TITLE
如何绘制环形文本？

### ISSUE THREAD

**Issue by Fiv5** [antvis/G6#3140]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
更丰富的展现形式。

### What does the proposed API look like?
目前我能想到的一种方式是遍历文本，对每个字符都建立一个 TextShape ，然后通过 transform 控制角度，但这种做法个人觉得有点 low 也过低低效，想询问下有没有其他办法？

**Comment by Yanyan-Wang** [comment]
暂时没有提供沿着一个路径绘制文本的方式

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
