### ISSUE TITLE
删除combo里的nodo后报错

### ISSUE THREAD

**Issue by 313812245** [antvis/G6#3141]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/friendly-einstein-r5t76?file=/index.js)

### Steps to reproduce
删除节点后回退

| Environment | Info |
|---|---|
| g6 | 4.3.5 |
| System | win10 |
| Browser | Chrome |

---
移动combo后回退也有问题，如何能一步回退到初始拖动位置？

**Comment by Yanyan-Wang** [comment]
下个小版本会修复
