### ISSUE TITLE
我尝试自定义combo的出栈入栈功能遇到报错，求解答

### ISSUE THREAD

**Issue by 313812245** [antvis/G6#3144]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hidden-bash-muwbw?file=/index.js:11246-11261)

### Steps to reproduce
删除最外层combo，撤回后再重置或者移动最外层combo时报错

| Environment | Info |
|---|---|
| g6 | 4.3.6 |
| System | win10 |
| Browser | Chrome |

---
当我删除最里层的combo是正常的

**Comment by Manon103** [comment]
加一，组合的删除操作入栈的时候只入了组合信息，并未记录节点位置等信息，导致节点不存在，组合重新生成时报错

**Comment by 313812245** [comment]
> 加一，组合的删除操作入栈的时候只入了组合信息，并未记录节点位置等信息，导致节点不存在，组合重新生成时报错

目前我把comboTrees一起存入栈中倒是可以解决。
https://codesandbox.io/s/distracted-carlos-xg1lk?file=/index.js

**Comment by Yanyan-Wang** [comment]
当前版本已不存在上述问题～（目前最新 4.7.16）
