### ISSUE TITLE
通过拖拽同时添加自定义节点和combo，仅渲染自定义节点

### ISSUE THREAD

**Issue by wuxinhuiaiwll** [antvis/G6#3145]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/trusting-robinson-qii2v)

### Steps to reproduce
通过拖拽同时添加自定义节点和combo，仅渲染自定义节点。通过graph.save()查看数据，combo已被创建。此时当手动拖动画布内任意节点该combo会渲染出来。
为了方便复现，Demo中用定时器模拟异步添加的过程。

另，已尝试使用graph.refresh()和graph.paint()，均无法更新画布使得combo成功渲染。通过graph.save()获取最新数据后调用graph.render()可以渲染出正确的节点和combo，但有无法接受的combo绘制动画。故demo中不包含此部分的复现。

| Environment | Info |
|---|---|
| g6 | 4.3.5 |
| System | macos Big Sur 11.1 |
| Browser | chrome 92 |

**Comment by Yanyan-Wang** [comment]
可以在创建完成后调用一下 graph.updateCombos()
