### ISSUE TITLE
滑动画布,请求接口分页加载数据

### ISSUE THREAD

**Issue by youdianfan** [antvis/G6#3147]
### What problem does this feature solve?
拖动画布,请求接口分页加载数据

### What does the proposed API look like?
拖动画布,请求接口分页加载数据

需求：滑动画布的时候,再远程请求接口获取数据.

下面这个的demo 找不到了

参考这个demo https://g6.antv.vision/zh/examples/interaction/loadData

**Comment by Yanyan-Wang** [comment]
增加节点逻辑类似这个?: https://g6.antv.vision/zh/examples/tree/customItemTree#customEdgeTree

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
