### ISSUE TITLE
img and shape lost

### ISSUE THREAD

**Issue by clk6666666** [antvis/G6#3148]
![image](https://user-images.githubusercontent.com/53636068/130767912-8c9af5e3-70b0-456c-8e6e-142ea800c2ff.png)

**Comment by Yanyan-Wang** [comment]
See the warning and checkout the id for nodes and edges, the 'id' should be unique strings

**Comment by Yanyan-Wang** [comment]
Hi, dear user. Since there was no response for a long time, we cannot figure out the answer of the problem you described. If there is new progress, feel free to open a new issue.
