### ISSUE TITLE
G6.registerEdge里边的颜色要怎么动态改变呢

### ISSUE THREAD

**Issue by omissyouyou** [antvis/G6#3149]
graph.setItemState(edge, 'hover', true)
edgeStateStyles: {
        hover: {
          stroke: '#1890ff',
        }
}
用这个方法没法改掉自定义树图中的边的颜色，要用哪种方法改好呢

**Comment by Yanyan-Wang** [comment]
registerEdge 继承一个内置边, 第三个参数写 'line'

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
