### ISSUE TITLE
请问怎么禁用节点拖拽？我拖拽节点后，节点是复制，而不是移动

### ISSUE THREAD

**Issue by HM007** [antvis/g6#315]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by HM007** [comment]
在初始化配置的时候，如果加上animate 节点拖拽就会变成复制
 var net = new G6.Net({
        // animate:true,
        id: 'mountNode', // 容器ID
        fitView: 'cc', // 画布显示位置，cc为水平垂直居中显示；
        grid:null,//是否显示网格
        height: window.innerHeight // 画布高
    });

**Comment by TomHuangCN** [comment]
编码问题，请按照模版提 issue
