### ISSUE TITLE
dagre布局，rankdir为LR，两个流程图左右展示

### ISSUE THREAD

**Issue by w1wenya** [antvis/G6#3150]
layout使用的dagre，rankdir为LR，数据里面有combo分组，当只有一个分组数据的时候是从左到右，但是要是有两个分组，分组是上下关系，分组里面的node是左右。但是我希望分组时左右布局，分组里面也是左右。
![image](https://user-images.githubusercontent.com/15921910/130903782-011389f8-7c82-4212-897b-a35e2a6d85d5.png)

**Comment by Yanyan-Wang** [comment]
参考 https://github.com/antvis/G6/issues/3164

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
