### ISSUE TITLE
在边上创建一个运动的箭头元素时，如何使箭头始终指向当前边的切线方向？

### ISSUE THREAD

**Issue by frostace** [antvis/G6#3151]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
如案例：https://g6.antv.vision/zh/examples/scatter/edge/  中所示，我将案例中的原点替换成了一个箭头，但这个箭头始终都是朝左的。如何能够使该箭头始终指向当前边的切线方向？
codesandbox: https://codesandbox.io/s/boring-surf-emgbk?file=/index.js

### What does the proposed API look like?
技术咨询。

**Comment by Yanyan-Wang** [comment]
https://codesandbox.io/s/young-pine-v37sw?file=/index.js
