### ISSUE TITLE
changeData方法执行有时候node不展示

### ISSUE THREAD

**Issue by w1wenya** [antvis/G6#3152]

**Comment by Yanyan-Wang** [comment]
啥意思? 请完整描述一下问题呢?

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。

**Comment by wenyuan** [comment]
某种场景下的解决方案：graph.changeData(data) 调用后，紧跟着调用下 graph.refresh()
