### ISSUE TITLE
bug: 使用mindmap时，树结构定位偏移

### ISSUE THREAD

**Issue by huangkairan** [antvis/G6#3154]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://www.google.com](http://www.google.com)

### Steps to reproduce
无

| Environment | Info |
|---|---|
| g6 | 4.3.6 |
| System | macos bigsur 11.2.3 |
| Browser | chrome 92.0 |

---
见视频

**Comment by Yanyan-Wang** [comment]
请提供复现在线 demo
