### ISSUE TITLE
brush-select似乎有个bug

### ISSUE THREAD

**Issue by wtjperi2003** [antvis/G6#3156]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://www.baidu.com](http://www.baidu.com)

### Steps to reproduce
第二次开始的框选,在mousemove一开始就会把之前框选的节点去掉selected状态，这个不对把。
![2021-08-27-15-46-01](https://user-images.githubusercontent.com/10322892/131092955-be58e504-35b8-4d63-a417-d7cd5a379a9e.gif)

| Environment | Info |
|---|---|
| g6 | 4.3.6 |
| System | win10 |
| Browser | chrome92.0.4515.159 |

**Comment by Yanyan-Wang** [comment]
我觉得这个是正常的逻辑啊. 你在电脑桌面上框选文件, 也是这个逻辑呀

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。

**Comment by huikai-web** [comment]
![image](https://github.com/antvis/G6/assets/63175605/a23796fd-edae-47db-b8dc-501ff0a87ce1)
![image](https://github.com/antvis/G6/assets/63175605/49ab38c0-0084-4d56-b912-8b4f56893ff0)
