### ISSUE TITLE
渲染105个自定义节点就会很卡顿

### ISSUE THREAD

**Issue by 775146061** [antvis/G6#3157]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/epic-http-ksoib?file=/src/index.js)

### Steps to reproduce
见重现demo

| Environment | Info |
|---|---|
| g6 | 4.3.3 |
| System | win10 |
| Browser | 谷歌91.0.4472.124 |

---
有没有办法对自定义节点的渲染性能优化一下

**Comment by 775146061** [comment]
> 我是mac，你这个demo在我机器上显示的挺流畅的，我现在要做5000左右的节点和关系，也需要自定义节点，不知道效果如何

跟电脑也有关系的，不过我换了vis-network性能好多了，动画效果更流畅，连线也不快纵横交错

**Comment by Yanyan-Wang** [comment]
我这里看还是挺流畅的. 尝试升级到 4.3.6, 性能有一定的提升. jsx 的编译也会有点慢, 看你自定义的这个节点还挺简单的, 可以考虑就直接用正常的自定义方式.

**Comment by 775146061** [comment]
> 我这里看还是挺流畅的. 尝试升级到 4.3.6, 性能有一定的提升. jsx 的编译也会有点慢, 看你自定义的这个节点还挺简单的, 可以考虑就直接用正常的自定义方式.

好的。其实还有另外一个问题，就是力导向布局后，线段交叉程度太高了，图谱之间的关系看起来不直观

**Comment by Yanyan-Wang** [comment]
看下你说的布局效果呢？力导向有很多参数可以配置，会对最终效果有比较大影响

**Comment by 775146061** [comment]
> 看下你说的布局效果呢？力导向有很多参数可以配置，会对最终效果有比较大影响

https://codesandbox.io/s/epic-http-ksoib?file=/src/index.js

**Comment by Yanyan-Wang** [comment]
> > 我这里看还是挺流畅的. 尝试升级到 4.3.6, 性能有一定的提升. jsx 的编译也会有点慢, 看你自定义的这个节点还挺简单的, 可以考虑就直接用正常的自定义方式.
> 
> 好的。其实还有另外一个问题，就是力导向布局后，线段交叉程度太高了，图谱之间的关系看起来不直观


1. 考虑调整样式的层次，不要所有内容都突出，下面例子我淡化了边及其 label 颜色
2. 根据数据的结构调整参数，例如下面例子我根据节点度数调整的 linkDistance
3. 调整收敛条件让计算经过更多的迭代次数

https://codesandbox.io/s/upbeat-goodall-sofyd?file=/src/index.js

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
