### ISSUE TITLE
minimap 支持不生成 edge

### ISSUE THREAD

**Issue by Fiv5** [antvis/G6#3158]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
有时候图中数据量很大的情况下，minimap 的绘制压力会加大，尽管可以设置 type 为 'keyShape' 或 'delegate'，但因为也要绘制边会影响性能，而边在缩略图中几乎是不可见的。

目前 Minimap 会获取主图中的 group 进行 clone ，并按比例绘制各个边和节点，是否可以只获取 node group 进行绘制？

### What does the proposed API look like?
Minimap 配置支持选项 `edges: false` 以避免边的绘制

**Comment by Yanyan-Wang** [comment]
可以考虑增加这个配置项, 不过暂时不在官方排期当中, 欢迎社区共建 ~

**Comment by Yanyan-Wang** [comment]
v4.7.16 支持为 minimap 配置 hideEdge: boolean 从而控制是否在 minimap 上显示边

**Comment by Ourydy** [comment]
> v4.7.16 支持为 minimap 配置 hideEdge: boolean 从而控制是否在 minimap 上显示边

能不能支持配置egde样式，现在缩略图的边感觉太细了，都看不太清，想在缩略图上体现连线关系，又不想影响主图
