### ISSUE TITLE
Dagre布局怎么设置边不重叠

### ISSUE THREAD

**Issue by zaki1991** [antvis/G6#3159]
![image](https://user-images.githubusercontent.com/9986571/131285693-1b9d50bd-989e-4aa1-9340-8ec59518c38d.png)
图中guangzhou到shenzhen有一条线，shenzhen到shanghai有一条线，guangzhou到shanghai有一条线，但是guangzhou到shanghai的线被挡住了，有什么配置可以让这些线都不重叠吗

**Comment by Yanyan-Wang** [comment]
dagre 布局配置 controlPoints: true, 并设置 defaultEdge 的 type: 'polyline'

**Comment by lyhper** [comment]
> dagre 布局配置 controlPoints: true, 并设置 defaultEdge 的 type: 'polyline'

三阶贝塞尔曲线有办法避免重叠吗？ @Yanyan-Wang

**Comment by Yanyan-Wang** [comment]
> > dagre 布局配置 controlPoints: true, 并设置 defaultEdge 的 type: 'polyline'
> 
> 三阶贝塞尔曲线有办法避免重叠吗？ @Yanyan-Wang

没有也，目前 dagre 为每条边计算了一个 controlPoints，三阶被三儿曲线需要两个 controlPoints

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
