### ISSUE TITLE
how to use ... to show a long text in g6 shape?

### ISSUE THREAD

**Issue by hendrickhan** [antvis/G6#3162]
when the text is too big that overflow the area of the g6  shape, I would like to have a xyz... present the overflow.
![Screenshot from 2021-09-01 15-20-37](https://user-images.githubusercontent.com/9595258/131678962-14cb8fc2-377e-4e8f-935d-58665f3f917e.png)

**Comment by Yanyan-Wang** [comment]
https://g6.antv.vision/en/examples/gallery#category-%E8%B6%85%E9%95%BF%E6%96%87%E6%9C%AC

**Comment by Yanyan-Wang** [comment]
Hi, dear user. Since there was no response for a long time, we cannot figure out the answer of the problem you described. If there is new progress, feel free to open a new issue.
