### ISSUE TITLE
dagre布局下使用quadratic连线方式时，部分线连不上节点

### ISSUE THREAD

**Issue by GuanJdoJ** [antvis/G6#3163]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/g6-dagre-quadratic-frzzo?file=/src/App.js)

### Steps to reproduce
如示例

| Environment | Info |
|---|---|
| g6 | 4.3.6 |
| System | Mac |
| Browser | Chrome |

---
![image](https://user-images.githubusercontent.com/30386473/131791444-bce0dfa6-c1f2-47a7-8072-bb41f43baa44.png)

当关系比较少时（把data注释打开）显示没有问题，当有交叉时就出现此问题了，把quadratic换成line也没问题，然后另外我还申请了加入g6交流钉钉群，麻烦通过一下（昵称是GuanJ）

**Comment by Yanyan-Wang** [comment]
controlPoints: false 

钉钉群满了, 通过也加不进去了……

**Comment by GuanJdoJ** [comment]
> controlPoints: false
> 
> 钉钉群满了, 通过也加不进去了……

controlPoints: false设置后edge比较像直线，请问如何让线的弧度像上方截图那样呢，
然后我申请的是二群，我看人数只有953人啊

<img width="545" alt="image" src="https://user-images.githubusercontent.com/30386473/132155730-861d5fb3-b687-49f5-a477-3ca4b19b1d17.png">

**Comment by GuanJdoJ** [comment]
还想问下，连线能结合d3使用吗，想按照import { curveBasis } from 'd3-shape';来绘制连线可以吗
这个是用curveBasis的连线方式结合svg做的，但是当节点和关系过多时渲染很慢，想用g6实现类似的效果
<img width="973" alt="image" src="https://user-images.githubusercontent.com/30386473/132470555-e0a5751f-47b5-4a9c-a77a-0058d54dfe33.png">

**Comment by Yanyan-Wang** [comment]
那把边 type 换成 polyline，然后设置 radius: 250 你看下效果能不能满足

defaultEdge: {
          type: "polyline",
          style: {
            stroke: "#ffb203",
            lineWidth: 3,
            radius: 250,
}
}

**Comment by GuanJdoJ** [comment]
我是通过自定义布局，重写了execute()里面
![image](https://user-images.githubusercontent.com/30386473/134797764-769a9fde-e0ff-4d07-8946-cb6e801dc201.png)
在edge中设置了points，然后在自定义edge中根据points和d3的createLine在初始化时做出了我想要的布局，但是这样的话节点在拖动时points是不会改变的，那我的自定义edge就不动了，难道我还要去自定义drag behavior，在拖动节点时去获取graph然后改变points这样才能实现吗，请问还有别的思路吗

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
