### ISSUE TITLE
Combo与Node用Edge连接时，无法上下布局

### ISSUE THREAD

**Issue by wjxfhxy** [antvis/G6#3164]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/quizzical-torvalds-xslyw)

### Steps to reproduce
见Demo链接 https://codesandbox.io/s/quizzical-torvalds-xslyw

| Environment | Info |
|---|---|
| g6 | 4.3.6 |
| System | - |
| Browser | - |

---
我们业务上希望，Edge能把Combo与Node链接起来，并且上下布局，而不是左右布局

**Comment by Yanyan-Wang** [comment]
这里因为 combo 的边没有考虑到 dagre 布局当中. 两个方案:

1. 增加一条边连接 combo 内部的那个节点到外面的节点, 并设置这条边的 style opacity: 0
graph.addItem('edge', {
  source: 'xxx',
  target: 'yyy',
  style: {
    opacity: 0
  }
})
2. 考虑自定义布局, 自己计算了节点位置给到节点数据 x y 就可以

**Comment by wjxfhxy** [comment]
通过修改edge与combo的层次关系解决了
