### ISSUE TITLE
强制刷新后，跳转到另一个页面，dom中没有canvas

### ISSUE THREAD

**Issue by chen-i** [antvis/G6#3165]
这个是刷新页的canvas信息
![可以显示](https://user-images.githubusercontent.com/37339618/131947347-12a01685-06b6-425b-9051-acd24d56eaa7.png)

这个是跳转页的canvas信息
![不能显示](https://user-images.githubusercontent.com/37339618/131947632-5bcb23d6-cdf0-4322-8f39-92ec1b0f65b1.png)

线上环境不强制刷新也会出现这个问题，这个问题没有在官方的案例中出现，是不是我哪里配置有问题？

**Comment by Yanyan-Wang** [comment]
不是很清楚, 没有遇到过……

**Comment by chen-i** [comment]
跳转到另一个页面， dom 里面的canvas 没被清除， 但是 调用graph.destroy() 后，canvas被清除了，还是会这样；
目前只能通过刷新解决
