### ISSUE TITLE
force抖动

### ISSUE THREAD

**Issue by eynait1010** [antvis/G6#3166]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://baidu.com](http://baidu.com)

### Steps to reproduce
无论是第一次渲染，还是更新视图
graph总会在最后零点几秒抖动一下
配置什么属性可以优化一下吗

| Environment | Info |
|---|---|
| g6 | 4.3.4 |
| System | mac |
| Browser | - |

---
无论是第一次渲染，还是更新视图
graph总会在最后零点几秒抖动一下
配置什么属性可以优化一下吗

**Comment by eynait1010** [comment]
抖动 ： 整体向右移动了几像素

**Comment by eynait1010** [comment]
我把fitCenter注释掉后 就没有这个问题了

**Comment by Yanyan-Wang** [comment]
因为 fitCenter 是要计算当前图的包围盒大小的, 但 force 布局过程中, 包围盒的大小总是在不断变化的, 所以得在布局完成之后 fitCenter, 这就导致了布局完成之后的突然变化
