### ISSUE TITLE
紧凑树布局, LR模式下，最右边展示的label会有部分不展示，而且拖拽不展示的内容绘制有问题

### ISSUE THREAD

**Issue by lovinglili** [antvis/G6#3168]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
https://github.com/lovinglili/xxxG6Demo

### Steps to reproduce
- 拖拽即可看到，右边文案绘制有问题

| Environment | Info |
|---|---|
| g6 | 4.3.6 |
| System | mac |
| Browser | google ,版本81.0.4044.138 |

![image](https://user-images.githubusercontent.com/37522681/131988871-2a113903-f3c7-4207-9a13-3a820f1f3eb2.png)

**Comment by Yanyan-Wang** [comment]
https://github.com/antvis/G6/issues/2492

**Comment by lovinglili** [comment]
参考以往issure已解决
