### ISSUE TITLE
graph.focusItem sends item to bottom left corner

### ISSUE THREAD

**Issue by andreasnett** [antvis/G6#3169]
This happened after updating to 4.3.6.
It seems a bug with the new update

**Comment by Yanyan-Wang** [comment]
I did not reproduce it on G6 website, could you pls provide an online reproduced demo?

**Comment by Yanyan-Wang** [comment]
Hi, dear user. Since there was no response for a long time, we cannot figure out the answer of the problem you described. If there is new progress, feel free to open a new issue.
