### ISSUE TITLE
关于使用html自定义node节点，当字段过多溢出高度如何定义出现滚动条？

### ISSUE THREAD

**Issue by chunpingY** [antvis/g6#317]
为了实现一个类似数据关系表的结构，展示表名和表的字段，当表的字段较多超出字段区高度时能够出现滚动条。我不知道rect是否支持出现滚动条，没找到属性。于是使用html自定义了一个node。虽然当字段超出高度时确实出现了滚动条，但是无法选中滚动条滚动,同理我想实现点击标题栏某个按钮时，下面字段区域不显示。也无法点击。只能选中整个node,请问如何解决？
            
代码：  //自定义node
 G6.registerNode('table',{
        cssSize:true,
        getHtml: function getHtml(cfg){
         let model=cfg.model;
         let fields="";
         Util.each(model.fields,function(field, i){
              fields+=field.field+"<br>";
         });
         let container = Util.createDOM('<div class="node-container"></div>');
         let titledom=Util.createDom('<div class="node-title"><div class="node-title-icon"></div><div class="node-titlename"><span>' + model.name + '</span></div> <div class="node-title-icont"></div><div class="node-title-close"></div>');
         let tabledom=Util.createDom('<div class="node-table">'+fields +'</div>');
         container.appendChild(titledom);
         container.appendChild(tabledom);

         return container;
        }
      },'html');

     样式仅贴滚动条部分
    
 .node-table{
      width:100%;
      height:80px;
      overflow-y:scroll;
    }

**Comment by TomHuangCN** [comment]
没啥办法。

因为 1.0 种 html 节点是在 canvas 画布下面的，节点 dom 的事件拿不到

**Comment by dd1994** [comment]
@TomHuangCN 请问 3.0 下这种情况该如何做呢
