### ISSUE TITLE
modes的type为drag-node时设置shouldEnd为false时第一次拖拽结束依然更新node的位置

### ISSUE THREAD

**Issue by qq591053991** [antvis/G6#3173]
如题：当modes的type为drag-node时设置shouldEnd为false时第一次拖拽结束依然更新node的位置
关键代码：
```
modes: {
    default: [
      {
        type: "drag-node",
        shouldEnd: () => false
      }
    ]
  }
```
最小复现：https://codesandbox.io/s/friendly-meninsky-s7rxz?file=/index.js:4194-4677

**Comment by Yanyan-Wang** [comment]
谢谢报告，尽量在下个小版本修复
