### ISSUE TITLE
The force layout cannot be switched.

### ISSUE THREAD

**Issue by palytoxin** [antvis/G6#3174]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/infallible-snowflake-snlhr)

### Steps to reproduce
在html中点击layout1，layout2可以看到布局切换开始鬼触跳动，并且切换不会成功

| Environment | Info |
|---|---|
| g6 | 4.3.6 |
| System | Linux |
| Browser | Version 93.0.4577.63 (Official Build) (64-bit) |

---
如果默认是gForce的布局， layout2还是force,切换就能正常

**Comment by Yanyan-Wang** [comment]
请提供一下在线的最小 demo 呢？这样效率高些。可以用 codesandbox.io
