### ISSUE TITLE
脑图子节点右侧对齐，左侧不对齐

### ISSUE THREAD

**Issue by lisyzz** [antvis/G6#3175]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/lisyzz/test1.git](https://github.com/lisyzz/test1.git)

### Steps to reproduce
图形渲染后，右侧的子节点纵向整齐排列，左侧的比较散乱

| Environment | Info |
|---|---|
| g6 | 4.3.3 |
| System | - |
| Browser | - |

**Comment by Yanyan-Wang** [comment]
请提供一下在线的最小 demo 呢？这样效率高些。可以用 codesandbox.io

**Comment by lisyzz** [comment]
> 请提供一下在线的最小 demo 呢？这样效率高些。可以用 codesandbox.io

用codesandbox还原时自定义节点使用了drawshape，两侧节点排列是正常的，而使用jsx的话左侧节点排列就会混乱。我是用的是vue，请问是使用了jsx这个原因导致的吗？

**Comment by Yanyan-Wang** [comment]
> > 请提供一下在线的最小 demo 呢？这样效率高些。可以用 codesandbox.io
> 
> 用codesandbox还原时自定义节点使用了drawshape，两侧节点排列是正常的，而使用jsx的话左侧节点排列就会混乱。我是用的是vue，请问是使用了jsx这个原因导致的吗？

截图我看下是怎样的不对齐呢？可能是自定义节点的时候需要调整中心坐标

**Comment by lisyzz** [comment]
我把getWidth从文本宽度改成固定值之后解决了，想请教一下getWidth函数return出去的值跟自定义节点时设置的width属性是怎样的关系呢？因为我以为getWidth是控制节点的宽度，但是事实上自定义节点设置width后看起来它影响的是节点的水平间距

**Comment by Yanyan-Wang** [comment]
自定义节点的 width 应该不会影响到布局计算出来的节点位置

**Comment by lisyzz** [comment]
![image](https://user-images.githubusercontent.com/90182926/134696545-677d7e38-063d-4137-b41a-5db07d9da647.png)
![image](https://user-images.githubusercontent.com/90182926/134696778-49cadda9-cc6c-4ad6-9871-66c5f4e91fa9.png)
![image](https://user-images.githubusercontent.com/90182926/134696831-ad4fe792-e047-4d41-85c5-25739f507303.png)
![image](https://user-images.githubusercontent.com/90182926/134696968-2b8b6afd-449d-484a-b0e4-29e252117ac9.png)
![image](https://user-images.githubusercontent.com/90182926/134697039-199366fb-46b5-429b-a312-c8edb5ad87e2.png)
您看，我修改了getWidth的值，但是节点的宽度没有改变，改变的是节点的位置，我不确定是我哪里出现的问题

**Comment by Yanyan-Wang** [comment]
布局配置中的 getWidth 影响的是该节点在布局中所占的位置。而自定义节点中的 width 控制的是节点的样式。

**Comment by Yanyan-Wang** [comment]
它们之间在内部没有直接关联。只是用户在使用的时候一般会参考节点的真实样式上的大小来配置布局

**Comment by lisyzz** [comment]
好的，了解了，感谢您的解答
