### ISSUE TITLE
Image Minimap 中用到的图片，如何生成？

### ISSUE THREAD

**Issue by xiaofengqqcom123** [antvis/G6#3176]

**Comment by Yanyan-Wang** [comment]
这个一开始的需求是因为主图和 minimap 两个画布会有双倍的性能开销，因此做了图片 minimap，这得要求提前生成好图片，可以是后端生成的简略图，也可以提前用 graph.downloadFullImage 生成一个简略的图概览。如果你的图有更新，还得更新这个图片。所以它可能只适用于某些特定场景

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
