### ISSUE TITLE
gForce布局不支持设置nodeSize

### ISSUE THREAD

**Issue by palytoxin** [antvis/G6#3178]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gforce-nodesize-issue-p9hll?file=/index.js)

### Steps to reproduce
看文档中有nodeSize配置项。但更改layout中的nodeSize,对生成图没有影响，自定义节点后 node的大小不是较大，配置nodeSize还是重叠到了一起

| Environment | Info |
|---|---|
| g6 | 4.3.6 |
| System | - |
| Browser | Version 93.0.4577.63 (Official Build) (64-bit) |

**Comment by Yanyan-Wang** [comment]
节点之间力的参数默认比较大，可以调小点试试 nodeStrength: 50

**Comment by Yanyan-Wang** [comment]
自定义节点重叠的话，提供一下在线 demo 呢？

**Comment by palytoxin** [comment]
### 测试链接
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gforce-nodesize-issue-p9hll?file=/index.js)

改了一下上面的demo。项目中用image,demo就改成圆了
调整size仿佛没什么改变
defaultNode: {
    size: 108,
    type: 'flow-node-warning'
  }

**Comment by Yanyan-Wang** [comment]
首先这个节点半径还是挺大的，你想你的画布宽高大概也就是 500～1000 的样子，但这里一个节点的直径就有 108 了，你可以看下不 fitView 的情况下，每个节点很大的。建议每个节点 20～30 就差不多了

在布局初始化的时候，根据画布的大小会先给节点一个初始在画布范围内的位置，作为力导向布局的输入，而这个初始位置是限制在画布范围内的，初始位置是会比较大程度影响最终布局效果的。所以最终收敛的时候因为节点又很大就施展不开。

然后力导向的参数是很多的，多个参数都会影响这个防止重叠的效果。节点半径调小点，然后尝试调整下面这一套参数，应该效果还可以：

  layout: {
    type: "gForce",
    gpuEnabled: true,
    preventOverlap: true,
    nodeSize: 20,
    nodeSpacing: 100,
    minMovement: 0.2,
    linkDistance: 120,
  },

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
