### ISSUE TITLE
uncombo 未触发 removeItem事件

### ISSUE THREAD

**Issue by NARUTOne** [antvis/G6#3179]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/event-umcombo-removeitem-8olkk)

### Steps to reproduce
调用`graph.uncombo(id)` 未触发 `afterremoveitem` 事件

| Environment | Info |
|---|---|
| g6 | 4.3.6 |
| System | - |
| Browser | - |

**Comment by Yanyan-Wang** [comment]
谢谢报告，下个小版本将修复
