### ISSUE TITLE
节点间的链接个数，方向怎么限制？

### ISSUE THREAD

**Issue by cike8899** [antvis/g6#318]
net 一个节点怎么限制自己不能链接自己，两个节点怎么限制方向是单向的，并且只能链接一条线？ @TomHuangCN

**Comment by TomHuangCN** [comment]
具体场景是什么呢？要在哪个阶段限制？

G6 就是一个关系图的绘制引擎，本身没有限制功能

**Comment by cike8899** [comment]
在两个node间连线的时候,两个节点间只容许有一个edge,这个怎么限制？

**Comment by TomHuangCN** [comment]
得知道你是怎么添加的，才知道你该怎么限制。

G6 本身没有限制接口，你传什么画什么

**Comment by cike8899** [comment]
在编辑的时候，通过拖动两个节点的锚点添加edge，在两个节点间已存在一条edge时，如何限制不能添加第二条 ，
是不是节点的model定义的时候应该有属性去限制能不能自己连接自己，通过属性限制该节点连接的个数，
@TomHuangCN

**Comment by TomHuangCN** [comment]
是在用 G6-Editor ?

**Comment by cike8899** [comment]
不是，是1.2.8版本 @TomHuangCN
