### ISSUE TITLE
angular12   G6 V4.3.6   force,gForce，fruchterman 布局 没用

### ISSUE THREAD

**Issue by dlink-chenqingyun** [antvis/G6#3181]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/empty-firefly-hzzl6?file=/src/app/app.component.ts)

### Steps to reproduce
(0 , color.default) is not a function  咋会报错啊

| Environment | Info |
|---|---|
| g6 | 4.3.6 |
| System | - |
| Browser | - |

**Comment by Yanyan-Wang** [comment]
你这个 demo 里少了个依赖 color

**Comment by Yanyan-Wang** [comment]
![image](https://user-images.githubusercontent.com/29593318/133441814-c48292b1-e64e-43a4-9cb2-dd12635aa18e.png)

左侧依赖列表增加一下就正常了

**Comment by dlink-chenqingyun** [comment]
angular12 使用 fruchterman 布局时，节点如果存在坐标，绘制过程会会有很明显的卡顿。如果节点再复杂点，比如使用了图片。此时如果不使用 gpuEnable , 布局就不会生效。
