### ISSUE TITLE
TreeGraph使用focusItem不好使

### ISSUE THREAD

**Issue by seed008** [antvis/G6#3182]
使用focusItem当前节点也不能到屏幕的中间位置

**Comment by Yanyan-Wang** [comment]
我在官网中测试表现正常。请提供复现的在线 demo

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
