### ISSUE TITLE
布局后，用removeItem删除报错

### ISSUE THREAD

**Issue by wenjing0456** [antvis/G6#3183]
如图，调用removeItem报错，不能删除
![image](https://user-images.githubusercontent.com/19699804/132811092-7f0083c4-79dd-4e54-9367-6a41efd2db88.png)

**Comment by Yanyan-Wang** [comment]
请提供一下复现的在线 demo

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
