### ISSUE TITLE
IE11 打包错误

### ISSUE THREAD

**Issue by kailong321200875** [antvis/G6#3184]
在vue项目中，用IE打开会出现以下问题：

![image](https://user-images.githubusercontent.com/32283845/132814463-a8dee6b3-2f8a-4da0-be2c-c25b06a6cd7f.png)
IE上无法识别class类，请问这个需要怎么处理

**Comment by Yanyan-Wang** [comment]
报错信息是什么

**Comment by kailong321200875** [comment]
> 报错信息是什么

就是我上面的截图，在ie11上没有把 es6转为es5

**Comment by Yanyan-Wang** [comment]
https://www.cxyzjd.com/article/qq_38277033/85061811

**Comment by Yanyan-Wang** [comment]
不再考虑支持 IE，因为 IE 已经下架啦
