### ISSUE TITLE
The source or target node of edge edge794 does not exist!   

### ISSUE THREAD

**Issue by kui913941251** [antvis/G6#3185]
新建了一个流程图之后，再次进入新建页面就报这个黄色警告(含有初始化的默认节点)，但是线还是正确的的连上了，不过保存的时候就提示没有连接上线

**Comment by Yanyan-Wang** [comment]
如果是新的边， 每次新建都更新下新边的 id， 不要用重复的边 id

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
