### ISSUE TITLE
请问G6的Menu要想实现这样的效果，能提供一下思路吗？

### ISSUE THREAD

**Issue by xujinxing1996** [antvis/G6#3186]
<img width="489" alt="g6-menu" src="https://user-images.githubusercontent.com/20754758/132852680-cc611a34-0a0b-4418-8a20-98fdbb0e3000.png">

**Comment by xujinxing1996** [comment]
右键点击，弹出这个菜单

**Comment by xujinxing1996** [comment]
> 如果能够用 DOM 实现的话，就是在右击的时候设置这个 DOM 的位置并将它显示出来就好，DOM 浮层挂载方式详见 https://g6.antv.vision/zh/docs/manual/advanced/coordinate-system#%E6%82%AC%E6%B5%AE-dom-%E6%8C%82%E8%BD%BD%E5%9C%A8-body-%E4%B8%8A
> 
> 如果想用图的画布来绘制的话，需要掌握一些基础渲染引擎 @AntV/G 绘制图形的 API,
> https://g6.antv.vision/zh/docs/api/Group
> https://g6.antv.vision/zh/docs/api/shapeMethods
> 将图形加入到 delegate 图形分组 graph.get('delegateGroup') 中, 简单示例：
> 
> const delegateGroup = graph.get('delegateGroup')
> // 在delegate 分组中创建一个图形分组放菜单图形
> const menuGroup = delegateGroup.addGroup();
> // 添加一些图形
> menuGroup.addShape('circle', {
> attrs: {
> //...
> }
> })
> 添加的图形可以参考 https://g6.antv.vision/zh/docs/api/shapeMethods
> 
> 这个扇形的绘制方式可以参考：
> 
> https://github.com/antvis/G6/blob/94b98ee3b36ac2347d2e4cb5526d7b7f868ccbfa/packages/element/src/nodes/donut.ts#L175
> 
> 
> 添加一条弧形的 path 图形，并设置其 lineWidth 为这个外圈半径和内圈半径之差
好的，谢谢，我参考的donut.ts画出来了。

**Comment by mmchao** [comment]
大哥，用path画扇形，G6是不是存在不能捕捉这个扇形事件的bug啊

>

**Comment by zhaochengxiang** [comment]
> 扇形

e.target可以获取到当前shape

**Comment by 37-Ricardo** [comment]
> > 如果能够用 DOM 实现的话，就是在右击的时候设置这个 DOM 的位置并将它显示出来就好，DOM 浮层挂载方式详见 https://g6.antv.vision/zh/docs/manual/advanced/coordinate-system#%E6%82%AC%E6%B5%AE-dom-%E6%8C%82%E8%BD%BD%E5%9C%A8-body-%E4%B8%8A
> > 如果想用图的画布来绘制的话，需要掌握一些基础渲染引擎 @AntV/G 绘制图形的 API,
> > https://g6.antv.vision/zh/docs/api/Group
> > https://g6.antv.vision/zh/docs/api/shapeMethods
> > 将图形加入到 delegate 图形分组 graph.get('delegateGroup') 中, 简单示例：
> > const delegateGroup = graph.get('delegateGroup')
> > // 在delegate 分组中创建一个图形分组放菜单图形
> > const menuGroup = delegateGroup.addGroup();
> > // 添加一些图形
> > menuGroup.addShape('circle', {
> > attrs: {
> > //...
> > }
> > })
> > 添加的图形可以参考 https://g6.antv.vision/zh/docs/api/shapeMethods
> > 这个扇形的绘制方式可以参考：
> > https://github.com/antvis/G6/blob/94b98ee3b36ac2347d2e4cb5526d7b7f868ccbfa/packages/element/src/nodes/donut.ts#L175
> > 
> > 添加一条弧形的 path 图形，并设置其 lineWidth 为这个外圈半径和内圈半径之差
> > 好的，谢谢，我参考的donut.ts画出来了。

大哥怎么做到弧形上设置不同的点击事件的
