### ISSUE TITLE
Multiple style associated with states can't coexist in an item

### ISSUE THREAD

**Issue by arcogabbo** [antvis/G6#3187]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/immutable-architecture-sb0nf?file=/src/index.js)

### Steps to reproduce
Applying state B(with a style associated) on a node/edge which already have a state A with a given style will cancel state A style completely.

| Environment | Info |
|---|---|
| g6 | 4.3.6 |
| System | - |
| Browser | - |

---
I wanted to find a way to apply more states to a node/edge with multiple styles. e.g. given a node i wanted to apply stroke style with state A and fill style with state B but the styles can't coexist apparently. Any help is appreciated. Thanks for all your work.

**Comment by Yanyan-Wang** [comment]
1. use `nodeStateStyles` on graph instance instead  of `stateStyles` in `defaultNode`. 
2. use `graph.updateItem` instead of `node.setState`

**Comment by arcogabbo** [comment]
Thank you @Yanyan-Wang .
