### ISSUE TITLE
react 引用3.0以上的版本，本地运行没有问题，但是build的时候会报错打包失败

### ISSUE THREAD

**Issue by sunfuqiangSir** [antvis/G6#3188]
![image](https://user-images.githubusercontent.com/32285163/133038777-d5c38310-75ca-48ed-b996-34abb0d1c3fa.png)

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
