### ISSUE TITLE
dagre布局，rankdir在TB和LR来回切换时，combo会互相重叠，fitView也不生效

### ISSUE THREAD

**Issue by DankeF** [antvis/G6#3189]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/winter-star-4bmz8)

### Steps to reproduce
初始化时布局是dagre，rankdir: 'LR'，显示是正确的。然后点击toolbar上的“dagre上下布局”后，combo会重叠，然而在初始化时已经设置了sortByCombo: true，并且fitView也没有生效。

这个问题在toolbar上点击的“dagre上下布局”和“dagre左右布局”互相切换时都会体现。

有意思的是在从“dagre上下布局”切换到“dagre左右布局”或者从“dagre左右布局”切换到“dagre上下布局”，然后在继续点击后者按钮，图会一次次的向正确演变，大概点击4次图就会正确。

| Environment | Info |
|---|---|
| g6 | 4.3.6 |
| System | - |
| Browser | - |

**Comment by Yanyan-Wang** [comment]
combo 这块的刷新存在一些问题，现在没有很好的解法，暂时这样能够少许缓解

切换布局之后调用
  setTimeout(() => {
    graph.updateCombos();
  }, 300)

**Comment by DankeF** [comment]
> 组合这块的刷新存在一些问题，现在没有很好的解法，暂时能够缓解
> 
> 切换布局之后调用
> setTimeout(() => {
> graph.updateCombos();
> }, 300)

我尝试用您提供的方法，combo确实不重叠了，但是combo的内边距仍然不正常，这可能是您说的只能暂时的缓解。

![image](https://user-images.githubusercontent.com/29647627/133545059-4d99e76e-c047-4ffd-b85b-a1109991164a.png)


在您回复前这两天，我尝试了在切换布局之后调用
setTimeout(() => {
  graph.rander();
}, 0)
可以直接让图的位置和combo显示正确，只不过切换显得很生硬。

**Comment by DankeF** [comment]
您好，我还有个问题。能否动态的让combo显示或不显示？

**Comment by Yanyan-Wang** [comment]
> 您好，我还有个问题。能否动态的让combo显示或不显示？

graph.hideItem(combo) 

graph.showItem(combo)

**Comment by Yanyan-Wang** [comment]
目前版本中已无上述问题
