### ISSUE TITLE
Add license information for react-node

### ISSUE THREAD

**Issue by GTRanger** [antvis/G6#3190]
Currently the package `@antv/g6-react-node` is [not licensed](https://www.npmjs.com/package/g6-react-node) which makes it a potential risk to include in any commercial application. Given that G6 itself is under the MIT license and that react-node is just an abstraction around G6 nodes for simplifying the integration with React, I believe it should be similarly licensed.

**Comment by mxz96102** [comment]
@antv/g6-react-node is under G6/packages so it's licensed under MIT with the same [LICENSE](https://github.com/antvis/G6/blob/master/LICENSE) file in root, feel free to use

**Comment by GTRanger** [comment]
I understand that, but as far as npm is concerned, the package is unlicensed. Since `@antv/g6` and `@antv/g6-react-node` are two separate packages, any company using their own internal npm mirror to distribute open source code that matches their license policies is unlikely to include `@antv/g6-react-node` in their mirror for this reason. Since `@antv/g6-react-node` is an optional component on top of `g6` and is not included as a core package, it should have an explicit, rather than implicit, license.
