### ISSUE TITLE
怎样避免边上的文字重叠

### ISSUE THREAD

**Issue by skyliao1** [antvis/G6#3191]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://snhbc.csb.app/](https://snhbc.csb.app/)

### Steps to reproduce
edges里面的lable会重叠 关系特别复杂的时候，有什么边上的文字防重叠的碰撞机制吗
![image](https://user-images.githubusercontent.com/16840152/133207196-956f5b60-852e-4f82-a4a0-ba35fb1f261c.png)
| Environment | Info |
|---|---|
| g6 | 4.3.6 |
| System | windows 10 |
| Browser | chrome |

**Comment by Yanyan-Wang** [comment]
考虑下边上文本随边角度旋转？ autoRotate: true https://g6.antv.vision/zh/docs/manual/middle/elements/edges/defaultEdge#%E6%A0%87%E7%AD%BE%E6%96%87%E6%9C%AC-label-%E5%8F%8A%E5%85%B6%E9%85%8D%E7%BD%AE--labelcfg

**Comment by skyliao1** [comment]
![image](https://user-images.githubusercontent.com/16840152/133573253-8565715c-acef-412b-b444-5b5b0a0f86d8.png)
加上去以后效果确实改善很多但是还是会有少部分重叠的文字

**Comment by Yanyan-Wang** [comment]
没有太好的办法避免，考虑把文本改成不在边的中间而在结束的地方，这个需要自定义边。参考：https://g6.antv.vision/zh/examples/item/customEdge#edgeMulLabel

或者给边的文本加一个描边，即使重叠也不会很花
labelCfg: {
  style: {
    stroke: '#fff',
    lineWidth: 2
  }
}

**Comment by Yanyan-Wang** [comment]
> 考虑把文本改成不在边的中间而在结束的地方，这个需要自定义边。参考：

可以配置边：
      labelCfg: {
        position: 'start', // 'center' 'end'
      }

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。

**Comment by wuzengduo** [comment]
有没有一种在连线的时候可以避让连线上的 label 的配置？类似避让节点那样的。
我遇到了类似的情况，加了 autoRotate: true，改变 labelCfg: {
position: 'start', // 'center' 'end'
}不同的数据，都还会是有不同程度的重叠情况出现
