### ISSUE TITLE
获取折线的拐点集合

### ISSUE THREAD

**Issue by Lcyame** [antvis/G6#3193]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

![微信截图_20210915140941](https://user-images.githubusercontent.com/29159379/133380273-f8511aa4-a160-4c55-8b3c-b0704ad42297.png)

生成polyline时没有指定controlPoints,在页面渲染完毕后如何获取到自动生成的拐点集合？

**Comment by Lcyame** [comment]
![微信截图_20210915140941](https://user-images.githubusercontent.com/29159379/133380246-9df84726-535d-4f8f-a3df-3e463d3a736f.png)

**Comment by Yanyan-Wang** [comment]
自动计算的边上没有去记录这个控制点位置，只能通过 keyShape 的路径来得到了 edge.getKeyShape().attr('path')

**Comment by Lcyame** [comment]
> 自动计算的边上没有去记录这个控制点位置，只能通过 keyShape 的路径来得到了 edge.getKeyShape().attr('path')

有这样一个需求，用户在拖动多个节点时，如上图的两个同时拖动时，在某些情况下折线的path会发生变化，用户希望能把path记录一下，只要两个节点相对位置不变，固定折线的path

**Comment by Yanyan-Wang** [comment]
按理说相对不动的话，应该不会动。如果要这样的话，就记住 path 重新给到 keyShape 的 attr 一下就好

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
