### ISSUE TITLE
combos如何实现卡片式群组

### ISSUE THREAD

**Issue by jike132** [antvis/G6#3194]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
能够实现基于combos布局，同时可以实现combos内部单独布局

### What does the proposed API look like?
能够实现基于combos布局，同时可以实现combos内部单独布局

**Comment by Yanyan-Wang** [comment]
可以自定义布局，G6.registerLayout，计算节点的 x y
https://g6.antv.vision/zh/docs/api/registerLayout

**Comment by jike132** [comment]
![IMG_20210915_151849](https://user-images.githubusercontent.com/13427462/133564168-84596371-e468-412a-8552-8144a7300466.jpg)
实现这种好像不太方便

**Comment by jike132** [comment]
![IMG_20210915_151849](https://user-images.githubusercontent.com/13427462/133564382-9ad73c2f-b893-486b-a922-83381c7debdf.jpg)

**Comment by jike132** [comment]
这样的卡片，怎么实现，使用dom节点很容易实现样式，但是整个卡片变成了整体，使用combo样式和布局都很难实现

**Comment by Yanyan-Wang** [comment]
还可以吧，就是内部的节点位置确定 x y 就好。combo 样式也需要自定义，一个矩形加两个文本和一个 icon

**Comment by jike132** [comment]
可以提供个复杂点的自定义combo案例吗，我试了下，combo添加图片特别麻烦

**Comment by Yanyan-Wang** [comment]
你这个截图上好像没有需要图片的地方吧？

**Comment by jike132** [comment]
里边添加方框位置特别不好计算，能不能获取默认文字位置，我按官网说明计算位置，渲染出的结果并不一致

**Comment by sxpdy8571** [comment]
大佬，我也想搞这个可视化操作，但是 combo 和 node 的位置不好控制，有没有可以参考的例子，急

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
