### ISSUE TITLE
树图如何增加combo？

### ISSUE THREAD

**Issue by mumu-evanchen** [antvis/G6#3200]

**Comment by Yanyan-Wang** [comment]
树图不支持哦

**Comment by mumu-evanchen** [comment]
> 树图不支持哦

![image](https://user-images.githubusercontent.com/10756444/134307256-d82212ed-5d55-49b9-aa87-93be7aaf0448.png)
![image](https://user-images.githubusercontent.com/10756444/134307420-f37f1d2e-ee7e-495f-8948-c5f1358350d2.png)

请问要在图1的情况下实现图2中的效果，有没有间接实现的思路

**Comment by Yanyan-Wang** [comment]
那可以直接绘制背景，往根图形分组上添加图形
graph.get('group').addShape('rect', {
...
})

图形属性参见：https://g6.antv.vision/zh/docs/api/shapeProperties

**Comment by mumu-evanchen** [comment]
> 那可以直接绘制背景，往根图形分组上添加图形
> graph.get('group').addShape('rect', {
> ...
> })
> 
> 图形属性参见：https://g6.antv.vision/zh/docs/api/shapeProperties

group增加shape可以画出背景，但会让节点范围变大，现考虑用原生svg画这个流程，谢谢解答
