### ISSUE TITLE
menu插件使用click方式后边点击事件无效

### ISSUE THREAD

**Issue by Nancyeah** [antvis/G6#3201]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nifty-williams-g66hl?file=/src/index.js)

### Steps to reproduce
1

| Environment | Info |
|---|---|
| g6 | 4.3.7 |
| System | macOS 11.5.2 |
| Browser | 版本 93.0.4577.82（正式版本） (x86_64) |

**Comment by Yanyan-Wang** [comment]
感谢报告，下个小版本会修复
