### ISSUE TITLE
拖拉combo到另外一个combo分组时，能否判断当前combo是否可以嵌套再嵌套上

### ISSUE THREAD

**Issue by lavenderMF** [antvis/G6#3202]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
判断combo是否可嵌套

### What does the proposed API look like?
无

**Comment by Yanyan-Wang** [comment]
暂时不行哦，目前只有 shouldUpdate 可以判断正在被拖拽的 combo 是否符合条件，return true 或 false。欢迎社区共建

**Comment by Yanyan-Wang** [comment]
v4.3.8 的 drag-combo 支持了 shouldEnd，第二个参数是 newParent, 释放时检测到的新父 combo item
