### ISSUE TITLE
Calling changeData multiple times causes undefined errors

### ISSUE THREAD

**Issue by JSuttor** [antvis/G6#3203]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://sorry_not_a_link_please_see_steps_to_reproduce](https://sorry_not_a_link_please_see_steps_to_reproduce)

### Steps to reproduce
Unfortunately, recreating in a sandbox is not feasible. I have tried, but the issue requires too complex of a system. However, I do have a good understanding of the issue and would like to propose a code change. I see no regressions from this change, but obviously it needs further testing from you guys.

| Environment | Info |
|---|---|
| g6 | 4.3.7 |
| System | Widnows 10, OSX, Linux |
| Browser | all |

---
My project has a lot of nested combos. For performance reasons within the graph and in our API, we add children to the graph at the point of combo expansion. We also have a search feature which can expand out to a specified point in our combo hierarchy. This necessitates the ability to add multiple levels of our data to a parent combo at the same time and expand them all at the same time. The way I have found to do this requires that we expand from the top down. I add data to our highest level combo, perform the expansion on that combo, then call changeData so that the graph reflects these changes, then move to the next child being expanded and do the same. Add the data, perform the expansion, then changeData. This works perfectly for my needs, except that G6 throws a lot of errors. Following the code in G6, the problem occurs within /g6-core/es/graph/controller/item.js in ItemController.prototyple.addItem. Near the end of the function you call graph.collapseItem(item) within a setTimeout. The setTimeout is what is causing this issue. If changeData is called multiple times in quick succession, within the graph.js changeData function, item.destroy is called on the combos. So by the time the timeout for the previous changeData call is complete and collapseCombo is called, the combo is destroyed. I tried removing the setTimeout in item.js and just calling collapseCombo, and it fixes all of my issues. I see no issues appearing due to this change. In fact, in some cases it results in some minor performance improvements when adding a lot of combos at once. Would it be possible for someone to determine the reason for this setTimeout and look into making this change if no regression is caused? As of yet I have found no other way to circumvent this issue.

**Comment by Yanyan-Wang** [comment]
The hidden nodes will not be calculated in layout algorithms. So, the `setTimeout` to `collapseCombo` aims to make sure the nodes to be hidden by collapsed parent combo are placed at correct positions by layout. And then the collapsed combo will be placed correctly to since the combo position depends on its children.

I will add `if (!item.destroyed)` inside `setTimeout` in next small version to solve this problem. Thanks for repoert

**Comment by JSuttor** [comment]
I added that line to test and that does fix my issue. Thank you for the swift response! So that will be in 4.3.7? And do you have a rough estimate for the release of that update?
