### ISSUE TITLE
手机 IOS系统版本15.0 自带Safari 浏览器 渲染node的label就会卡死页面

### ISSUE THREAD

**Issue by youdianfan** [antvis/G6#3206]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/adoring-cherry-5hk0w?file=/index.js:8160-8165)

### Steps to reproduce
在实际代码项目中,渲染node的label字段,页面就会卡死.
注释之后,代码又正常渲染.
手机访问demo又是可以正常渲染
![image](https://user-images.githubusercontent.com/27018910/134328203-cf5fc895-f198-4482-aa88-dab3fbbcbe94.png)

| Environment | Info |
|---|---|
| g6 | 4.3.7 |
| System | IOS |
| Browser | Safari |

**Comment by hustcc** [comment]
旧版本的 iOS 不会卡死吗？

**Comment by wangkailang** [comment]
遇到了同样的问题，google 后也有收集到相关问题：

- [Safari 15 Beta G2Plot JSChart Cannot Render](https://developer.apple.com/forums/thread/685866)
- [Total canvas memory use exceeds the maximum limit - iOS 15 beta with Safari](https://developer.apple.com/forums/thread/687866)
- https://bugs.webkit.org/show_bug.cgi?id=229231

MacOS safari 15.0 版本可以通过禁用 `Canvas Rendering` 暂时修复这个问题，手机和平板上目前没有好的解决办法：
![image](https://user-images.githubusercontent.com/6942517/134607541-06e3ad45-5029-4acb-afb8-bcbaa37cb929.png)

**Comment by youdianfan** [comment]
@wangkailang  可以通过G6.registerX自定义node元素,给对象添加一个title属性,自己去实现下,在元素上addShape一个文本. 不要给label字段赋值

**Comment by youdianfan** [comment]
@hustcc  旧版本不会,诡异的问题.

**Comment by youdianfan** [comment]
@yuanchuan  希望可以关注处理下.

**Comment by youdianfan** [comment]
@Yanyan-Wang  希望可以关注下处理下.

**Comment by Yanyan-Wang** [comment]
据 @hustcc 排查是 IOS15 上时候  -apple-system 字体会有问题，但是 G6 内部没有使用这个字体，怀疑是 canvas 没有设置字体的时候，会直接取浏览器的默认字体，而 IOS 的浏览器默认字体是  -apple-system

**Comment by youdianfan** [comment]
@Yanyan-Wang OK,我明天验证一下，感谢您的回复！

**Comment by Yanyan-Wang** [comment]
也许配置一下 labelCfg.style.fontFamily 为其它的字体可以解决

**Comment by youdianfan** [comment]
@Yanyan-Wang   感觉解答回复,已经验证了,确实是字体导致的,设置下labelCfg.style.fontFamily就可以解决了

**Comment by youdianfan** [comment]
@wangkailang   可以尝试下设置fontFamily 试试.

**Comment by youdianfan** [comment]
@Yanyan-Wang  建议官方设置下默认普惠体

**Comment by hustcc** [comment]
G2 遇到类似的问题，是字体带来的，参考 https://github.com/antvis/G2/issues/3635

**Comment by youdianfan** [comment]
@hustcc  感谢回复，问题已解决！
