### ISSUE TITLE
使用 g6-react-node 渲染时，在循环输出(map)的时候会报错

### ISSUE THREAD

**Issue by evanoxu** [antvis/G6#3207]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/bold-margulis-6sxi9?file=/src/index.js)

### Steps to reproduce
相关版本：
"@antv/g6": "4.3.4",
"@antv/g6-react-node": "1.4.2",

步骤：
在react里，for循环可以用map代替，但是为什么我在一个<Rect key={data.i}></Rect>加上key值后，就报错了：TypeError: Element is not a function getShapeFromReact ？
![image](https://user-images.githubusercontent.com/3927965/134328827-80a9b000-970a-4952-b983-6de606d4c9f6.png)

| Environment | Info |
|---|---|
| g6 | 4.3.4 |
| System | mac |
| Browser | chrome |

**Comment by mxz96102** [comment]
已发布更新修复）

**Comment by evanoxu** [comment]
@mxz96102 我该怎么更新？我发现我重新install下来的还是版本还是没变呀？

**Comment by yangcong1012** [comment]
请问解决了吗？我更新到最新版本了也还是这个报错
