### ISSUE TITLE
how to remove the line dash around the Edge arrow?

### ISSUE THREAD

**Issue by hendrickhan** [antvis/G6#3211]
g6 version :     "@antv/g6": "^4.3.7",

![image](https://user-images.githubusercontent.com/9595258/134687511-f9a105b7-dcf1-4094-a123-0d940533b687.png)

how to remove the line dash around the arrow?

I can do it by adding lineDash:[0,0]
      endArrow: {
          path: arrowPath,
          d,
          fill: '#acaeaf',
          lineDash: [0, 0],
        },
however ts reports error:
'lineDash' does not exist in type 'ArrowConfig',

is there any more cleaner solution?

many thanks!

**Comment by Yanyan-Wang** [comment]
try strokeOpacity: 0 for endArrow, and I will add lineDash to ArrowConfig in next small version

**Comment by hendrickhan** [comment]
It seems that strokeOpacity is also not in ArrowConfig. Anyway, thanks a lot for the fix.

**Comment by Yanyan-Wang** [comment]
yes, also fixed by v4.3.11
