### ISSUE TITLE
g6官网上的视图控制栏怎么开启

### ISSUE THREAD

**Issue by daidaic** [antvis/G6#3213]
现在要用到搜索功能,看到官网上有个视图控制栏有搜索,但是并没有文档写如何开启..
<img width="1478" alt="111" src="https://user-images.githubusercontent.com/47729929/134790443-76852ac5-b44a-4524-a830-2184fd88ab80.png">
谢谢

**Comment by Yanyan-Wang** [comment]
这个是建议的视觉规范。G6 没有提供搜索功能。因为一般搜索都是按照业务逻辑来写的，搜索后找到对应的节点/边的 id，然后可以使用 graph.focusItem 把图平移到改节点和边对齐到画布中心。然后使用 graph.setItemState 设置搜索到的元素的状态

**Comment by daidaic** [comment]
好的
