### ISSUE TITLE
react-node 如何实现自定义高亮

### ISSUE THREAD

**Issue by GuanJdoJ** [antvis/G6#3214]
如果使用jsx自定义节点，配合
`graph.on('node:mouseenter', function(e){
                graph.setItemState(e.item, 'highlight', true);
})`
可以设置state，来控制鼠标悬浮节点和关联节点的高亮
如果使用react-node该如何配置呢，我尝试了下面这种写法没有作用
`G6.registerNode('rect-xml2', {
    options: {
        stateStyles: {
            highlight: {
                opacity: 1,
            },
            dark: {
                opacity: 0.2,
                'title': {
                    opacity: 0.2
                },
                'img': {
                    opacity: 0.2
                },
            },
        },
    },
    ...createNodeFromReact(Card)
})`

**Comment by GuanJdoJ** [comment]
@yuanchuan @mxz96102

**Comment by mxz96102** [comment]
react node已经脱离了原来的节点state体系，推荐使用node里面的数据来进行定义，定义一个highlight: boolean, 来修改style，参考一下事件使用案例？ https://dicegraph.github.io/g6-react-node/example/event

**Comment by GuanJdoJ** [comment]
> react node已经脱离了原来的节点state体系，推荐使用node里面的数据来进行定义，定义一个highlight: boolean, 来修改style，参考一下事件使用案例？ https://dicegraph.github.io/g6-react-node/example/event

懂你意思，我试了一下，但我这里Circle的onMouseEnter事件没有触发，麻烦看下哪里有问题
https://giy20.csb.app/

**Comment by GuanJdoJ** [comment]
> > react node已经脱离了原来的节点state体系，推荐使用node里面的数据来进行定义，定义一个highlight: boolean, 来修改style，参考一下事件使用案例？ https://dicegraph.github.io/g6-react-node/example/event
> 
> 懂你意思，我试了一下，但我这里Circle的onMouseEnter事件没有触发，麻烦看下哪里有问题
> https://giy20.csb.app/

链接复制错了 ～～！ https://codesandbox.io/s/customer-react-node-g6-giy20

**Comment by GuanJdoJ** [comment]
还有个问题想问一下，如果用jsx自定义节点，可以做到像react-node一样每个shape都有独立的触发事件吗，比如我一个节点由图片和label两部分组成，点击图片时展示节点详情，点击label时跳转到相应node @mxz96102

**Comment by mxz96102** [comment]
可以的，定义一下name="" 通过判断事件触发shape的name来判断就好

**Comment by GuanJianSayWeee** [comment]
麻烦看下这个 我这里Circle的onMouseEnter事件为啥没有触发 @mxz96102 
https://codesandbox.io/s/customer-react-node-g6-giy20

**Comment by GuanJdoJ** [comment]
知道了，当创建好Graph后，如果需要使用在节点内定义的事件，需要设置appenAutoShapeListener(graph)
https://www.yuque.com/docs/share/e1cb2776-ed13-45bb-8172-69b1d3db2fc2
