### ISSUE TITLE
使用updateChildren 后 Node节点会发生位移或变形，甚至是nodeModel 中自定义的数组内容都被清空了

### ISSUE THREAD

**Issue by Ailichiyann** [antvis/G6#3215]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://065bw.csb.app/](https://065bw.csb.app/)

### Steps to reproduce
想通过不刷新整体的方式 （graph.data）（graph.render），实时更新每个节点具体的内容变化，但是发现单独使用 updateChildren，updateChild，addChild 这些API 节点都会错乱 ，甚至是在nodeModel中自定义的 数组 （childrenBackups） 都被清空了。请问一下 我需要做到这个效果的话，应该怎么做比较好呢？在线等，急~  谢谢大佬解答

| Environment | Info |
|---|---|
| g6 | 4.3.8 |
| System | - |
| Browser | - |

**Comment by Ailichiyann** [comment]
如果点击节点下的展开按钮 ，nodeModel 中定义的 childrenBackups数组都会被添加到 children中
![1632641190(1)](https://user-images.githubusercontent.com/44226134/134798157-12912a4a-0894-406c-9aa6-b2498a992777.jpg)
点击 ‘updateChildren’ 刷新数据 按钮后 
节点数据发生错乱了 
![1632641345(1)](https://user-images.githubusercontent.com/44226134/134798201-9bccd465-6c62-4598-9a23-68f6bcbdf35a.jpg)

**Comment by Yanyan-Wang** [comment]
你要更新的是一个节点上的内容，还是一整棵子树，还是一个节点的所有子节点？

更新单个节点内容 graph.updateItem

**Comment by Ailichiyann** [comment]
> 你要更新的是一个节点上的内容，还是一整棵子树，还是一个节点的所有子节点？
> 
> 更新单个节点内容 graph.updateItem

更新一整棵树上的内容

**Comment by Yanyan-Wang** [comment]
我打开你的 demo 好像点击那个按钮，出来了下面那个节点，但没有出现截图那个圆点呢？

**Comment by Yanyan-Wang** [comment]
solved by v4.7.16
