### ISSUE TITLE
新增轮廓包裹成员报错！

### ISSUE THREAD

**Issue by AmieJing** [antvis/G6#3218]
节点2-3个，如果点击某个节点新增节点，会出现这种报错！！
![image](https://user-images.githubusercontent.com/37952540/134836165-370d5aa1-93b6-4c18-b3bf-b3b69ad6c975.png)

**Comment by AmieJing** [comment]
https://codesandbox.io/s/lively-shape-nzu79?file=/src/components/HelloWorld.vue

**Comment by Yanyan-Wang** [comment]
创建点的时候先给一个初始坐标
const item = graph.addItem("node", {
            id: "node" + i,
            x: Math.random() * 100,
            y: Math.random() * 100
          });

否则由于内部节点有非法的坐标导致轮廓的路径可能计算失败

**Comment by AmieJing** [comment]
如果节点数量多，在创建或者更新轮廓包裹的时候，有什么办法可以加快渲染吗？
