### ISSUE TITLE
自定义注册html类型的node时，自定义node上的js事件会丢失

### ISSUE THREAD

**Issue by jzoe** [antvis/g6#322]
* **G6 Version**: 1.2.8
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

需要实现一个自定义的 tree 节点，采用下面这种扩展 html 节点的方式来实现。

```js
G6.registNode(
      'customNode',
      {
        cssSize: true,
        getHtml(cfg) {
          // TODO 这2种方式都会导致 DbNodeCard 组件上的事件丢失
          const dom = G6.Util.createDOM(`<div id="customNode" style="width: 300px; height: 150px"></div>`);
          const { model } = cfg;
          ReactDOM.render(<MyCustomNode currentNode={model} />, dom);
          return dom;
        },
      },
      'html'
    );
```

但我在 MyCustomNodecurrentNode 上的绑定的非 0级 DOM 事件，如 Button 的 onClick 事件或者 tooltip 等都丢失了。请问这是因为 g6 中对事件冒泡做了什么特殊处理吗？该如何做才能不丢失绑定的js事件呢？

**Comment by TomHuangCN** [comment]
https://www.yuque.com/antv/g6/wm3aid
