### ISSUE TITLE
Tree Graph数据更新时，数据渲染动画如何关闭

### ISSUE THREAD

**Issue by zmbxy95** [antvis/G6#3220]
如视频中所示，使用updateChild更新数据时，节点渲染会有一个从根节点出现得过渡动画效果，如果不想要这个动画，或者仅在更新数据时，不想要这个效果，要如何设置？

https://user-images.githubusercontent.com/50108232/134841197-96859eb8-24ba-46eb-8d57-9d655cd118a4.mp4

**Comment by Yanyan-Wang** [comment]
图实例配置 animate: false

**Comment by zmbxy95** [comment]
那么是否可以在某些特定的操作下开启动画呢，现在看效果是一个全局的配置，Graph实例一经实例化，其中的参数就不能再次更改。

**Comment by zmbxy95** [comment]
对于这个问题，有一点个人想法。

在使用上，作为初次加载有这样动画效果没问题，如果每次更新数据都需要仍有这样的动画效果，因为每次都会有个很明显的刷新效果，呈现上就会显得很别扭。

但在对图做一些操作时，还是更希望有一些过渡效果在内，这样会显得整个操作更润滑一些，而一点过渡/动画效果都没有，整个操作下来就会显得很生硬。

有注意到，在代码中，updateChild最终的更新操作，落在graph.layout()上，其中animate属性取的是graph示例中的属性值，也就是全局配置的结果，是否可以考虑像fitView属性那样，在操作中允许暂时覆盖全局的属性值设置，比如：
```javascript
public layout(fitView?: boolean, animate?: boolean) {
    // ...
    // const animate: boolean = self.get('animate');
    if (animate == null) {
        animate = self.get('animate');
    }
    // ...
}
```
