### ISSUE TITLE
force力导向图使用自定义node rect图形,如何设置才能防止元素重叠?

### ISSUE THREAD

**Issue by youdianfan** [antvis/G6#3222]
### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/busy-northcutt-cvhj4?file=/index.js)

### Steps to reproduce
已经设置了preventOverlap参数

| Environment | Info |
|---|---|
| g6 | 4.3.8 |
| System | IOS |
| Browser | Safari |

![image](https://user-images.githubusercontent.com/27018910/134848605-93aef2ec-811a-4dab-8ee7-0fa50f132f4d.png)

**Comment by youdianfan** [comment]
@Yanyan-Wang   我尝试设置了几个参数,还是会重叠.
size属性,设置的是当前每个文本宽度

-节点大小（直径）。用于碰撞检测。若不指定，则根据传入的节点的 size 属性计算。

**Comment by ColinChen2** [comment]
这是个数学问题啊，一个圆包裹正方形。
node.size =  nodeWidth * Math.sqrt(2);

**Comment by youdianfan** [comment]
@ColinChen2  大佬牛逼,这样也会增加每个nodeSpacing的间距,不想那么分散, 设置linkDistance会好一点

**Comment by yaojin2070** [comment]
你好, 我想问下, 线会跟其他的线重叠, 这个该怎么解决
