### ISSUE TITLE
拖拽完，其他方法里graph 再去update 其他属性， x,y 会再移动一次

### ISSUE THREAD

**Issue by ZOEWANGCHINA** [antvis/g6#323]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

拖拽完，再去更新 fill 属性，x，y又会移动一次。
CodePen Link： https://codepen.io/anon/pen/qKpyQM#anon-login

**Comment by ZOEWANGCHINA** [comment]
拖拽完点，改变颜色按钮，按钮要往下拉一点才能看到。

**Comment by KylenXu** [comment]
update任意属性好像会重制坐标

**Comment by ZOEWANGCHINA** [comment]
有什么解决方法吗 @KylenXu

**Comment by TomHuangCN** [comment]
https://codepen.io/DoriTong/pen/xaddMJ?editors=1010

 看下这个教程：https://www.yuque.com/antv/g6/custom-node#ko7wyq
