### ISSUE TITLE
g6引用websocket实时更新节点,如何让位置不发生变化

### ISSUE THREAD

**Issue by daidaic** [antvis/G6#3230]
如图当前是旧节点图
<img width="1090" alt="Snipaste_2021-09-29_15-41-43" src="https://user-images.githubusercontent.com/47729929/135224684-ac3cb85f-c91e-4861-ac65-81ed85cf2b46.png">

当我新增一个节点,节点位置就发生了变化
<img width="1108" alt="new" src="https://user-images.githubusercontent.com/47729929/135225038-1ed80d3b-840e-480d-865b-9e543bd868df.png">

如何让节点位置不发生变化呢...

**Comment by Pulset** [comment]
同样遇到了这个情况

**Comment by ityoung** [comment]
@yuanchuan +1，如何能让协同编辑的其他用户不受影响、保持在当前位置呢？

**Comment by ityoung** [comment]
官方文档只提到了`graph.getViewPortCenterPoint`方法，通过该方法获取到的position不清楚是什么；
而后想到`focusItem`方法，查看了源码后发现调用的是 `ViewController.focusPoint()`

最终实现数据变更保持位置不变：

```
const clientPosition = state.graph.getViewPortCenterPoint()
// update data received from websocket (such as graph.updateChildren)
graph.get('viewController').focusPoint(clientPosition)
```

**Comment by yuanchuan** [comment]
@ityoung 为什么这个项目总是有人 @ 我 😯  我几年前是用过 G6，不过早已经弃坑

**Comment by ityoung** [comment]
> @ityoung 为什么这个项目总是有人 @ 我 hushed 我几年前是用过 G6，不过早已经弃坑

sorry... 你跟管理员昵称有一滴点儿像，at错了...
