### ISSUE TITLE
4.3.11版本设置shadowOffsetX属性的问题

### ISSUE THREAD

**Issue by huanghaoming** [antvis/G6#3234]
shape.attr("shadowOffsetX", -3);    ok

shape.attr("shadowOffsetX", "-3");  不ok。。。minimap会消失。。。。

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
