### ISSUE TITLE
如何在轮廓包裹的边缘加文字信息？

### ISSUE THREAD

**Issue by AmieJing** [antvis/G6#3239]
类似下图：
![image](https://user-images.githubusercontent.com/37952540/136639525-491e6b46-16f2-44cf-8345-6ab45cb1d016.png)

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
