### ISSUE TITLE
流程编辑器可以自定义吗

### ISSUE THREAD

**Issue by muziling** [antvis/g6#324]
https://antv.alipay.com/assets/dist/3.0.0/g6/1.x/editor/base.html  
这个流程编辑器，左侧的节点可以自定义吗，看了HTML源代码，好像是要手动生成svg图片。
节点的属性只有名称尺寸颜色，可以自定义吗，
最后编辑完成后， 怎么获取编辑好的数据。 

这部分文档没找到，不知道是不是找漏了。

**Comment by wmhh1129** [comment]
+1 有同样的需求。

**Comment by TomHuangCN** [comment]
https://github.com/antvis/g6-editor/blob/master/demos/rc-components/ModelFlowEditor.jsx#L19
