### ISSUE TITLE
How to debug node state change?

### ISSUE THREAD

**Issue by lianghx-319** [antvis/G6#3241]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://antv-issue-helper.surge.sh/](https://antv-issue-helper.surge.sh/)

### Steps to reproduce
In my case, I don't know why state was clear after calling graph.changeSize. I want a way to debug what changes states actually

| Environment | Info |
|---|---|
| g6 | 4.3.11 |
| System | - |
| Browser | - |

**Comment by Yanyan-Wang** [comment]
Please provide an online reproduced demo? I cannot reproduce the problem

**Comment by lianghx-319** [comment]
Oh, I am so sorry. It is too long for me. Maybe reopen it if I can provider more detail.
