### ISSUE TITLE
自环边在开启GPU时显示不出来

### ISSUE THREAD

**Issue by QyMTE3** [antvis/G6#3246]
{
  type: 'gForce',
  workerEnabled: true,
  gpuEnabled: true,
}

布局配置如上，这种情况下自环边的path全部都是NaN，关掉这两个就正常了，但数据太多关掉后卡顿很严重，请帮忙解答下，多谢。

**Comment by QyMTE3** [comment]
不好意思，没外网权限给不了在线的demo

忘了提及一点，边是自定义的，因为需要在头尾加点特殊图形，代码大概如下，不知道能不能复现：
`
      afterDraw(cfg, group) {
        afterDraw(cfg, group)
        cfg.style.startArrow = {
  path: `
    M 4, -5
    L 4 -5
    L 4 5
    L 4 5
    Z
    M 7, -5
    L 7 -5
    L 7 5
    L 7 5
    Z
    M 10, -5
    L 10 -5
    L 10 5
    L 10 5
    Z
  `
}
        cfg.style.endArrow = {
          path: `${G6.Arrow.triangle(10, 10, 0)}
          M 14, -5
          L 14 -5
          L 14 5
          L 14 5
          Z
          M 17, -5
          L 17 -5
          L 17 5
          L 17 5
          Z
          M 20, -5
          L 20 -5
          L 20 5
          L 20 5
          Z`,
          fill: GRAY,
          lineWidth: 0
        }
      }
`

我昨天试了下换成 force 就没问题，当然也可能是少了gpuEnabled吧

**Comment by Yanyan-Wang** [comment]
没看懂你的这个配置，startArrow endArrow 为啥是在 afterDraw 里面配给 cfg？这样没用的吧，要一开始就配置到 defaultEdge 或者边数据里面去。另外，这个肩头的路径为啥不是字符串？还有 endArrow 的 path 到底是 G6.Arrow.triangle 还是路径？

**Comment by Yanyan-Wang** [comment]
尽量用你提供的内容改了一下 demo 还是没能复现：https://codesandbox.io/s/friendly-wozniak-n4h29?file=/index.js

建议 startArrow endArrow 还是不要这样去配置

**Comment by QyMTE3** [comment]
https://g6.antv.vision/zh/docs/manual/middle/elements/edges/custom-edge

**Comment by QyMTE3** [comment]
> startArrow endArrow 为啥是在 afterDraw 里面配给 cfg？

https://g6.antv.vision/zh/docs/manual/middle/elements/edges/custom-edge
我是看这个教程写的扩展现有边，只是在基础线条上加两端的箭头，那箭头应该写到draw()里面吗？

> 要一开始就配置到 defaultEdge 或者边数据里面去

这个没用到，是因为有多条不同样式的边，每一种的两端箭头都不太一样。
所以想着统一写进一个自定义边的文件里面了。

> 这个肩头的路径为啥不是字符串？

path: \`string\`
写的是模板字符串，之前没注意\`字符需要转义下
