### ISSUE TITLE
updateItem方法更新edge的endArrow，出现内存泄漏的问题

### ISSUE THREAD

**Issue by GuaoGuao** [antvis/G6#3249]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sleepy-wescoff-jft41?file=/src/components/HelloWorld.vue)

### Steps to reproduce
updateItem方法更新带endArrow的edge，出现内存泄漏的问题，大量循环浏览器报out of memory，去掉endArrow就不报错

| Environment | Info |
|---|---|
| g6 | 4.3.11 |
| System | windows |
| Browser | 任意 |

**Comment by Yanyan-Wang** [comment]
感谢报告，接下来会尝试修复

**Comment by y00251390** [comment]
请问这个bug最终解决了吗
