### ISSUE TITLE
polyline 在收起的 combo 中拖动， 展开后不会更新位置

### ISSUE THREAD

**Issue by maqi1520** [antvis/G6#3250]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/distracted-banach-vn177?file=/index.js)

![image](https://user-images.githubusercontent.com/9312044/137256705-f89aa8cb-0ede-4373-9679-f05c543ac777.png)

### Steps to reproduce
1、点击combo 收起
2、拖动combo
3、点击combo 展开

| Environment | Info |
|---|---|
| g6 | 4.3.11 |
| System | mac |
| Browser | chrome 92.0.4515.159（正式版本） (x86_64) |

**Comment by aKaigege** [comment]
> 感谢报告，接下来会尝试修复。
> 
> 临时解决方案：
> 
> ```
> graph.on('aftercollapseexpandcombo', e => {
>   if (e.action !== 'expand') return;
>   const combo = e.item;
>   combo.getEdges().forEach(edge => {
>     edge.refresh();
>   })
> })
> ```

这个方法可以解决但是 拖动中明显感觉到卡顿，请问有什么别的方法性能更好一点？

**Comment by Yanyan-Wang** [comment]
v4.7.17 已解决

**Comment by licc12** [comment]
还有一个类似问题：切换复合布局（外部布局darge， 内部布局grid），含combo节点，不点击，直接切换darge布局方向，之后再点开combo, 此时combo展开的位置还是之前的位置。

我临时解决方案是调用graph.render()强制刷新一下，就好了。
