### ISSUE TITLE
拖动图形至画布区域外后,插件出现异常情况

### ISSUE THREAD

**Issue by panct** [antvis/G6#3254]
案例描述:

拖动图形至画布区域外,释放鼠标,再次进入画布区域拖动图形,无法再拖动图形,松开鼠标,在画布上移动鼠标,画布会跟随鼠标移动

猜想:可能是拖拽超出画布区域后，图形的拖拽事件未结束,导致再次进入画布区域内操作出现问题

请问下有解决方案吗?

我这边目前使用的G6版本是"@antv/g6": "^4.2.7"

**Comment by Yanyan-Wang** [comment]
请给出复现在线 demo ？

**Comment by Yanyan-Wang** [comment]
我这边用 mac chrome 你的链接中没能复现问题。你的是什么浏览器？有可能是有些浏览器拖拽画布出去的时候会选中其他 DOM 元素的文字，看下能不能把附近的文字关闭可选

**Comment by panct** [comment]
> 我这边用 mac chrome 你的链接中没能复现问题。你的是什么浏览器？有可能是有些浏览器拖拽画布出去的时候会选中其他 DOM 元素的文字，看下能不能把附近的文字关闭可选

可能是demo的测试区域有点小,不太还复现这个问题,这个在本地运行的时候，确实也不是每次都能复现这个问题,但是这个问题确实是存在的,我看了下源码，貌似不能通过画布的实例对象调用某个函数清除元素的drag-node的behavior动作

**Comment by panct** [comment]
> 我这边用 mac chrome 你的链接中没能复现问题。你的是什么浏览器？有可能是有些浏览器拖拽画布出去的时候会选中其他 DOM 元素的文字，看下能不能把附近的文字关闭可选

我这边是在windows的chrome浏览器上出现这个问题的
