### ISSUE TITLE
Deprecated DOMMouseScroll event in wheel Event API

### ISSUE THREAD

**Issue by dvkuznietsov** [antvis/G6#3256]
- [X] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://antv-g6.gitee.io/zh/examples/interaction/customBehavior](https://antv-g6.gitee.io/zh/examples/interaction/customBehavior)

### Steps to reproduce
1) Open demo
2) Try to pan the graph
3) It pans only up/down, in debugger the event is legacy DOMMouseScroll instead of WheelEvent

| Environment | Info |
|---|---|
| g6 | 4.3.11 |
| System | MacOS Catalina 10.15.7 |
| Browser | Firefox 93 |

---
Apparently Event API uses `onmousewheel` event listener instead of `wheel` event listener

**Comment by Yanyan-Wang** [comment]
solved by v4.8.0
