### ISSUE TITLE
官网图表示例无法打开，报“演示代码报错，请检查”（Cannot set properties of undefined (setting 'typescript')），但国内镜像可以打开。

### ISSUE THREAD

**Issue by blueju** [antvis/G6#3259]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g6.antv.vision/zh/examples/case/graphDemos#christmasBubbles](https://g6.antv.vision/zh/examples/case/graphDemos#christmasBubbles)

### Steps to reproduce
antv官网→g6→图表示例→报错

| Environment | Info |
|---|---|
| g6 | 4.4.0 |
| System | Win10 |
| Browser | Edge最新版 |

**Comment by Yanyan-Wang** [comment]
感谢报告，已修复。请清一下缓存再试试
