### ISSUE TITLE
官网图表示例报错

### ISSUE THREAD

**Issue by cai-zhuo** [antvis/G6#3260]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g6.antv.vision/zh/examples/case/graphDemos#christmasBubbles](https://g6.antv.vision/zh/examples/case/graphDemos#christmasBubbles)

### Steps to reproduce
g6官网 =》 图表示例 =》 任意图表

| Environment | Info |
|---|---|
| g2 | 4.1.31 |
| System | - |
| Browser | - |

**Comment by Yanyan-Wang** [comment]
已经修复了，请清空缓存刷新试试
