### ISSUE TITLE
圆形节点  多锚点时，如何让贝塞尔曲线连接点的切线与圆形节点上锚点的切线 始终保持垂直

### ISSUE THREAD

**Issue by damnright** [antvis/G6#3261]
圆形节点  多锚点时，如何让贝塞尔曲线连接点的切线与圆形节点上锚点的切线 始终保持垂直。
![111](https://user-images.githubusercontent.com/17570651/138039500-ffe8b4ae-11e0-4dd8-bcfa-f460722981a9.png)
如图所示 圆形节点的边上有64个等分锚点，如何使连接边垂直于锚点切线，这样看上去很怪。

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
