### ISSUE TITLE
drag-combo的behavior的配置项

### ISSUE THREAD

**Issue by lavenderMF** [antvis/G6#3262]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g6.antv.vision/zh/docs/manual/middle/states/defaultBehavior#drag-combo](https://g6.antv.vision/zh/docs/manual/middle/states/defaultBehavior#drag-combo)

### Steps to reproduce
shouldupdate配置项跟文档描述的不一致

| Environment | Info |
|---|---|
| g6 | 4.3.8 |
| System | win |
| Browser | chrome |

**Comment by Yanyan-Wang** [comment]
这里应该代码写错了，应该是 this.shouldUpdate.call(this, evt)，下个小版本将会修复

**Comment by Yanyan-Wang** [comment]
已经修复，谢谢
