### ISSUE TITLE
是否有方法更新combo的大小（不是固定大小fixSize）

### ISSUE THREAD

**Issue by yangmiao13160** [antvis/G6#3263]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?

1、combo里面有若干个node，删除其中的一个或多个后，combo的width和height不会更新，需要用户手动移动combo中的node，宽高才会更新。
2：combo在折叠后，如果移动了combo位置，再展开后，combo的大小会变成默认的大小，而不是通过combo内节点的位置计算的大小，需要用户手动移动combo中的node，宽高才会更新。

### What does the proposed API look like?
能够让开发者手动调用一个函数来实现combo的大小更新呢？
目前已试过combo.refresh()是达不到我想要的效果。

**Comment by user-lihai** [comment]
我也遇见过这个问题，收起的时候可以控制大小，但是展开的时候有时候不会包裹住内部的节点，不知道楼主有没有遇见过这个问题
