### ISSUE TITLE
节点频繁update时，节点里面的图片会闪，有什么解决办法吗

### ISSUE THREAD

**Issue by damnright** [antvis/G6#3268]
节点频繁update时，节点里面的图片会闪，有什么解决办法吗？节点的draw方法频繁调用，每次都是完全重绘。

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。

**Comment by csspmini-web** [comment]
> 



> 节点频繁update时，节点里面的图片会闪，有什么解决办法吗？节点的draw方法频繁调用，每次都是完全重绘。

registerNode  时可以在 创建 imageShape 时 在 attrs 中存一个图片的原始路径 oriImgPath，

然后在 registerNode 的自定义元素中调用 update 时判断 新的 cfg.img 是否等于  attrs.oriImgPath，

如果不相等再去 imageShape.attr({ img: img, oriImgPath: img })
