### ISSUE TITLE
使用updateLayout切换布局时报错layout failed

### ISSUE THREAD

**Issue by lghuahua** [antvis/G6#3272]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/lghua/pen/VwzpqaK](https://codepen.io/lghua/pen/VwzpqaK)

### Steps to reproduce
1. 使用fruchterman类型布局，并设置gpuEnabled为true
2. 使用updateLayout更新为forceAtlas2布局

控制台输出 Web-Worker layout error! layout forceAtlas2-gpu not found 并报错 layout failed

| Environment | Info |
|---|---|
| g6 | 4.3.11 |
| System | win10 |
| Browser | Google Chrome  94.0.4606.81 |

**Comment by mxz96102** [comment]
需要在更新布局时候gpuEnabled: true, updateLayout是进行了config的mix而不是replace

**Comment by Yanyan-Wang** [comment]
forceAtlas2 不可使用 GPU，更新时更新 gpuEnabled: false

**Comment by lghuahua** [comment]
> 需要在更新布局时候gpuEnabled: true, updateLayout是进行了config的mix而不是replace

是不是在mix之后将无用的配置移除更好呢

**Comment by Yanyan-Wang** [comment]
solved by v4.7.16
