### ISSUE TITLE
contextmenu 挂载自定义dom，如何固定位置（不随点击位置变动）

### ISSUE THREAD

**Issue by damaohub** [antvis/G6#3273]
换了个方法实现，已通过contextmenu 挂载自定义dom解决。

_Originally posted by @cay8 in https://github.com/antvis/G6/issues/2461#issuecomment-752883027_
如何把环形中心点定位到node的中心？

**Comment by Yanyan-Wang** [comment]
node 坐标很容易得到的，节点点击事件中 e.item.getModel() 即可得到节点数据

**Comment by Yanyan-Wang** [comment]
挂载自定义 DOM 参考
https://g6.antv.vision/zh/docs/manual/advanced/coordinate-system

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
