### ISSUE TITLE
labelCfg.style.background.padding of edge, while set value like [10,20,10,20], the position is not right.

### ISSUE THREAD

**Issue by NameIsYearMonthDay** [antvis/G6#3274]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Wrong location
@antv\g6-core\lib\element\edge.js 

line 249

"x: bbox.minX - padding[2]" maybe "x: bbox.minX - padding[3]"

| Environment | Info |
|---|---|
| g6 | 4.3.4 |
| System | - |
| Browser | - |

---
You may need to check padding of other items

**Comment by ltraccount** [comment]
any update on this?

**Comment by Yanyan-Wang** [comment]
thanks, will be fixed ASAP

follow the duplicated issue https://github.com/antvis/G6/issues/3346
