### ISSUE TITLE
combo能否，像树形一样由上而下的层次布局，同一级别的保持在同一水平线上，且里面的combo里面的node也尽量在同一水平线上

### ISSUE THREAD

**Issue by yuzhu0223** [antvis/G6#3276]

**Comment by Yanyan-Wang** [comment]
使用 dagre，并开启 sortByCombo

https://g6.antv.vision/zh/examples/net/dagreFlow#dagreCombo

**Comment by yuzhu0223** [comment]
有没有那种level为1时在一层，level为2时在第二层这样子，不是单纯的只在同一层

**Comment by Yanyan-Wang** [comment]
目前 dagre 已支持为节点配置 layer 以指定层级: https://g6.antv.antgroup.com/api/graphlayout/dagre#%E6%8C%87%E5%AE%9A%E8%8A%82%E7%82%B9%E5%B1%82%E7%BA%A7

**Comment by yuzhu0223** [comment]
但是如果同一层级不同combo之间存在edge，或者高层级指向低层级时存在edge时，布局会错乱，这种情况怎么办呢
