### ISSUE TITLE
同一层级同时展开多个节点会出现错位情况

### ISSUE THREAD

**Issue by cookiemommy** [antvis/G6#3277]
![image](https://user-images.githubusercontent.com/28150141/139029648-60a0b379-4693-4c99-b65d-333a1b157bb0.png)

[https://codesandbox.io/embed/epic-johnson-pze77?fontsize=14&hidenavigation=1&theme=dark](url)

使用的是自定义节点,数据是官网案例的mock数据,自己增加了一些子节点,ID是唯一的;
多次展开"出现问题1"和"出现问题2"这两个节点的子节点,就会出现截图的情况~请大佬赐教

**Comment by snakeninja110** [comment]
这个我也遇到过，不用svg渲染就行

**Comment by Yanyan-Wang** [comment]
SVG 性能比较差，频繁展开收起带有动画可能因为更新速度不够快而导致动画被下一个动作中断，因此出现上述问题。建议可改为 canvas 渲染

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
