### ISSUE TITLE
how to add display flex style to G6 canvas?

### ISSUE THREAD

**Issue by hendrickhan** [antvis/G6#3279]
how to add display flex style to G6 canvas?
in order to make the canvas adjustable, i want to add
style={{
display: 'flex',
}}
to g6 canvas element, but i don't see anywhere the style can be configured in GraphOptions? What is the best way to do it?

Many thanks!

**Comment by Yanyan-Wang** [comment]
Hi, dear user. Since there was no response for a long time, we cannot figure out the answer of the problem you described. If there is new progress, feel free to open a new issue.
