### ISSUE TITLE
version4.3.11 官方示例中的transform操作得到的矩阵为[NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN]

### ISSUE THREAD

**Issue by sinanIndex** [antvis/G6#3280]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://antv-g6.gitee.io/zh/docs/manual/middle/elements/shape/transform/#transformts](https://antv-g6.gitee.io/zh/docs/manual/middle/elements/shape/transform/#transformts)

### Steps to reproduce
另外提供代码复现：https://codesandbox.io/embed/laughing-jasper-oejhy?fontsize=14&hidenavigation=1&theme=dark

去掉 rect.setMatrix(newMatrix);就可以正常显示了

完全使用上面的官网页面最底下的示例，但是引入evt，把transform改成evt.transform，这样渲染到屏幕上之后，屏幕无法进行任何操作，打印newMatrix发现是[NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN]。
![image](https://user-images.githubusercontent.com/52593312/139177445-73578b51-4979-4403-9ec1-3685706f1571.png)

打印matrix是
![image](https://user-images.githubusercontent.com/52593312/139177219-68e73c72-dc09-43b0-84b9-099c09f64a02.png)

目前进行transform操作只能使用下面的方法分步进行了：
 rect.translate(100, 50)
 rect.rotate(Math.PI / 4)
 rect.scale(0.5, 2)

@antv/matrix-util 版本为3.0.4。

另外顺便吐槽下，这个代码里面怎么给const定义的matrix赋值。。。

| Environment | Info |
|---|---|
| g6 | 4.3.11 |
| System | macos 11.4 |
| Browser | chrome 95.0.4638.54（正式版本） (x86_64) |

**Comment by Yanyan-Wang** [comment]
应该是 mat3.create() 的问题，直接初始化为 [1, 0, 0, 0, 1, 0, 0, 0, 1] 就好了

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
