### ISSUE TITLE
使用image作为节点背景出现的bug

### ISSUE THREAD

**Issue by had60** [antvis/G6#3283]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/had60/pen/ExvwgQd](https://codepen.io/had60/pen/ExvwgQd)

### Steps to reproduce
1.使用image作为节点背景后，使用clipCfg进行切割会出现节点显示的问题，导致关系线出现问题，如图。
2.关系线能够使用改变锚点位置的方法进行解决，但是该image节点（circle）的相应区域还是为原未切割的图片（rect）。

![issue_pic2](https://user-images.githubusercontent.com/63271766/139572010-8b289da7-b877-4a89-b48c-aef482f478f4.jpg)
![issue_pic1](https://user-images.githubusercontent.com/63271766/139571908-03f00b64-4716-483b-b206-2bedc47d30ee.jpg)

| Environment | Info |
|---|---|
| g6 | 4.3.11 |
| System | - |
| Browser | - |

**Comment by mxz96102** [comment]
clipCfg并不会改变原来shape的本质，所以建议加一个看不见的circle作为keyshape

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
