### ISSUE TITLE
@antv/g6 + vite v2.6.4 打包后浏览器报错, 但是 vite v2.5.1 没问题。

### ISSUE THREAD

**Issue by qwfy5287** [antvis/G6#3284]
### 问题描述

这个问题在vite上面也提了，好几天还没有处理，发到这边试试。希望有大佬能解决。

@antv/g6

# with v2.6.4
执行命令

yarn build
yarn serve

在浏览器上报错, console error
```
Uncaught TypeError: Cannot read property 'Graph' of undefined
```

# with v2.5.1  is ok

### 示例代码

https://github.com/qwfy5287/g6-build-error

### 系统信息

```shell
mac
```

### 包管理器

yarn

**Comment by loveholly** [comment]
我们也遇到了这个问题，版本号2.0.0

**Comment by Hertbertt** [comment]
同遇到，是否有解决方案了

**Comment by cool-518** [comment]
同样的问题

**Comment by iqshen** [comment]
同样的问题

**Comment by qwfy5287** [comment]
@loveholly @Hertbertt @cool-518 @iqshen 

临时解决方法
```
can use import G6 from '@antv/g6/dist/g6.min'
this solution could only be temporary
```

**Comment by kputnins** [comment]
`import G6 from "@antv/g6/dist/g6.min";` wroked like a charm

**Comment by i7eo** [comment]
magic !!!

**Comment by xiziliang** [comment]
在index.html 中加上
`<script>window.require = Boolean;</script>`，可以解决g6打包的问题，但是我又遇到了别的问题

**Comment by pengxiaotian** [comment]
Solution：   https://github.com/antvis/G6/issues/2961

**Comment by qwfy5287** [comment]
> Solution： #2961

看起来也是没有，从根本解决问题。 

根据错误提示，G6官方应该能解决才对。

**Comment by pengxiaotian** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by pengxiaotian** [comment]
> 

但是已经被官方收到 FAQ了， https://g6.antv.vision/zh/docs/manual/FAQ/vite-support

**Comment by rockyEnum** [comment]
顶，我也遇到这个问题了

**Comment by luxferrew** [comment]
Solution: [#2961 ](https://github.com/antvis/G6/issues/2961#issuecomment-1041016015)

**Comment by qwfy5287** [comment]
> ly1991 发了解决方法 
> That's because of @rollup/plugin-commonjs which the vite depends on, the v21.0.0 version of the plugin has a breaking change: [https://github.com/rollup/plugins/blob/master/packages/commonjs/CHANGELOG.md](url), just add the following config to your vite.config.js will solve the problem @qwfy5287
> 
> ```js
> build: {
>       commonjsOptions: {
>           ignoreTryCatch: false,
>       },
>   },
> ```

**Comment by luxferrew** [comment]
@qwfy5287 
hhhh 原来要显式声明
当时在声明文件中看到注释里default为false就没尝试
因为这个bug就是
`g6 >>> layout >>> dagrejs >>> graphlib`
最后的graphlib在try catch里引起的
