### ISSUE TITLE
树布局能否实现两个方向相反的树拥有共同的叶子节点？

### ISSUE THREAD

**Issue by JYShaw** [antvis/G6#3285]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当前场景：
两个树拥有**共同的叶子节点**，一个树的方向是**LR**，另一个方向是**RL**。

实际的场景比较复杂，但核心的问题简化后如下图所示：

![](https://i.loli.net/2021/11/02/qLFty5viKIlUJjE.jpg)

因为节点数量较多，层次不确定，难以手动计算坐标

### What does the proposed API look like?
希望两个treeGraph对象能配置关联项，根据children的id来确定共同叶子节点

**Comment by Yanyan-Wang** [comment]
你这个不是个树图，就用 Graph 就行了，dagre 布局

**Comment by JYShaw** [comment]
> 你这个不是个树图，就用 Graph 就行了，dagre 布局

谢谢

**Comment by xmBryant24** [comment]
请问一下《树布局能否实现两个方向相反的树拥有共同的叶子节点？》这个问题解决了吗，我现在也有这么个需求，毫无头绪😭
