### ISSUE TITLE
G6 力导布局使用webworker后，drag nodes受到影响

### ISSUE THREAD

**Issue by candy-Tong** [antvis/G6#3286]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g6.antv.vision/zh/examples/net/forceDirected#forceDirectedPreventOverlap](https://g6.antv.vision/zh/examples/net/forceDirected#forceDirectedPreventOverlap)

### Steps to reproduce
1. 直接使用g6力导布局demo，加上配置开启 webwork
2. drag节点，会发现很难拖动节点

![image](https://user-images.githubusercontent.com/20377280/139780106-6be89b93-dd25-4f2c-9fd7-2b5a9887bfe3.png)

| Environment | Info |
|---|---|
| g6 | 4.4.0 |
| System | win10 |
| Browser | chrome 90.0.4430.85 |

**Comment by mxz96102** [comment]
![image](https://user-images.githubusercontent.com/15213473/141086521-cd43cc99-96ac-441d-a79c-c75964f3ed5a.png)
如果需要后续力导布局交互，请在首次布局结束后关闭worker

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
