### ISSUE TITLE
Edge label is misplaced

### ISSUE THREAD

**Issue by ltraccount** [antvis/G6#3287]
I see that this could be fixed on 4.3.8, but anyway I have updated to 4.3.11 and its still happening

**Reproduction lin**k
See the misplaced label between nodes alps_file1 and alps_file2
https://codesandbox.io/s/peaceful-kilby-75kzq?file=/index.js

Environment | Info
-- | --
g6 | 4.3.11
System | win10
Browser | Chrome

**Comment by Yanyan-Wang** [comment]
I did not get it, graph in your demo looks correct. The node with id '4' has the same label with node '1' in the data

**Comment by Yanyan-Wang** [comment]
Hi, dear user. Since there was no response for a long time, we cannot figure out the answer of the problem you described. If there is new progress, feel free to open a new issue.
