### ISSUE TITLE
combo的fixCollapseSize不生效

### ISSUE THREAD

**Issue by damnright** [antvis/G6#3288]
自定义combo时  同时设置了size和fixCollapseSize，combo的半径在收缩和展开时始终是size。

**Comment by damnright** [comment]
好像只是circle不生效   rect是有效的

**Comment by damnright** [comment]
官网的示例就有这个问题
[https://g6.antv.vision/zh/examples/item/customCombo#cCircle](url)

**Comment by damnright** [comment]
circle类型的combo 设置padding也无效

**Comment by damnright** [comment]
combo的keyshape设置dragable为false也无效  是被重写了吗

**Comment by Yanyan-Wang** [comment]
dragable -> draggable

**Comment by Yanyan-Wang** [comment]
你贴的这个官网示例是自定义 combo，内置的 combo 应该可以

**Comment by Yanyan-Wang** [comment]
自定义的要么就在 drawShape 里面判断 cfg 中的 collapsed，如果是 true，就给个固定的 r

**Comment by damnright** [comment]
谢谢~draggable拼写没错的，这里打错了，自定义combo的keyshape的draggable设为false是不生效的

**Comment by Yanyan-Wang** [comment]
如果你希望所有 combo 都不能拖拽的话，不配置 drag-combo behavior 就可以了哈。如果你希望部分 combo 不能被拖拽的话，可以为 drag-combo 配置 shouldUpdate 函数，根据参数判断如果不可以拖拽返回 false，否则返回 true

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
