### ISSUE TITLE
关于事件对象中 currentItem

### ISSUE THREAD

**Issue by aimagic** [antvis/g6#329]
* **G6 Version**: 2.0.0

改写 [使用教程 / 自定义交互 / 简单交互](https://antv.alipay.com/zh-cn/g6/1.x/tutorial/custom-interaction.html#_%E7%AE%80%E5%8D%95%E4%BA%A4%E4%BA%92) 例子中的事件部分:
```javascirpt
let dx, dy
graph.on('node:dragstart', ({ currentItem, x, y }) => {
  dx = currentItem.getModel().x - x
  dy = currentItem.getModel().y - y
})
graph.on('node:drag', function({ currentItem, x, y }) {
  this.update(currentItem, {
    x: x + dx,
    y: y + dy,
  })
})
```
不做 node = ev.item, 不判断 node &&, 不重置 node = void 0, 改用 ev.currentItem, 似乎也能工作
那么,
- 这种用法是否正确? 有无隐患?
- 是否推荐用于除了拖动之外的事件? (注意到 currentItem 是 "**drag 拖动**子项")
- 有没有更好的用法可以进一步省略所有信号量?

**Comment by TomHuangCN** [comment]
* 正确，无隐患 
* 这个问题没看懂
* 从代码简洁角度，暂时你这个是比较好的方案

**Comment by aimagic** [comment]
第 2 个问题搞清楚了, currentItem 属性 ( 和 currentItem 属性 ) 只在
- dragstart
- drag
- dragend
- dragenter
- dragleave
- drop

这几个和拖动相关的事件中存在, 表示拖着的对象, 在其它事件里没有

**Comment by aimagic** [comment]
API 文档里关于事件对象有几个属性没有提及:
- click, mousedown 和拖动相关的事件对象有 button 属性
- mouseenter, dragenter 有 fromItem, fromShape 属性
- frontEvObj 属性, 它是不是一个内部属性?
