### ISSUE TITLE
开始运行后ml-matrix报错

### ISSUE THREAD

**Issue by mie-jordan** [antvis/G6#3292]
node_modules\ml-matrix\matrix.js Unexpected token (930:4)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (930:4)

安装的系统要求的ml-matrix@6.5.0

**Comment by Yanyan-Wang** [comment]
应该是你的项目的 babel 需要配置一下，具体浏览器搜索一下

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
