### ISSUE TITLE
changeData 删除 combo 内的节点导致报错

### ISSUE THREAD

**Issue by Cyer** [antvis/G6#3293]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/quiet-field-gsiyf)

### Steps to reproduce
changeData 中 itemMap 遍历的顺序会导致报错，如果 combo 在 node remove 的前面执行了 destroy 则不会报错。

![image](https://user-images.githubusercontent.com/24714116/140315621-8b79a7ae-2ed3-4065-9702-bdec8bb41998.png)

| Environment | Info |
|---|---|
| g6 | 4.3.11 |
| System | - |
| Browser | - |

**Comment by hllinc** [comment]
come on!

**Comment by Yanyan-Wang** [comment]
solved by v4.7.16
