### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'viewController')

### ISSUE THREAD

**Issue by hendrickhan** [antvis/G6#3294]
when i call graph.changeSize(width, height); 

sometimes i got 

Uncaught TypeError: Cannot read properties of null (reading 'viewController')

in the console.

Any idea why it happens?

**Comment by mxz96102** [comment]
Is there any chance you call it when graph init not ready or it's already destroied?

**Comment by Yanyan-Wang** [comment]
if (graph && !graph.destroyed) {
  ...
}
