### ISSUE TITLE
dagre: nodeSep and zIndex is not working 

### ISSUE THREAD

**Issue by Pulset** [antvis/G6#3295]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/optimistic-bush-pfgig?file=/index.js)

### Steps to reproduce
I use registerEdge and layout is dagre, but nodeSep and zIndex is not working 

| Environment | Info |
|---|---|
| g6 | 4.4.0 |
| System | mac os |
| Browser | chrome |

**Comment by Yanyan-Wang** [comment]
nodeSep -> nodesep


there is no parameter named 'zIndex' for dagre 
https://g6.antv.vision/en/docs/api/graphLayout/dagre
