### ISSUE TITLE
建议将快速上手示例代码中的 shape 调整为 type 或去掉，避免造成误解

### ISSUE THREAD

**Issue by iceytea** [antvis/G6#3296]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/compassionate-lalande-5lxm7?from-embed)

### Steps to reproduce
[快速上手](https://g6.antv.vision/zh/docs/manual/getting-started)的页面
<img width="1088" alt="屏幕截图 2021-11-05 150526" src="https://user-images.githubusercontent.com/77133362/140479010-93777190-629c-4d23-9fa2-2e02ccbd1ce1.png">

提供的示例里面，shape 字段应该代表展示的图形，但官方文档中并没有提到 shape 字段，实际情况下设置 shape 也没有用处。

官方文档提到表达类似含义的字段为 type
使用 shape 容易造成误解，建议换成表达同样含义的 type，或者去掉该字段

| Environment | Info |
|---|---|
| g6 | 4.4.0 |
| System | - |
| Browser | - |

---
快速上手：https://g6.antv.vision/zh/docs/manual/getting-started

节点配置文档：https://g6.antv.vision/zh/docs/api/Graph/#graphoptionsdefaultnode

**Comment by Yanyan-Wang** [comment]
好的感谢提示

**Comment by Yanyan-Wang** [comment]
已修改
