### ISSUE TITLE
布局为层次(dagre)模式下，边重合

### ISSUE THREAD

**Issue by qiYuei** [antvis/G6#3298]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/autumn-sunset-qdoy1?file=/src/index.js)

### Steps to reproduce
初始化时，线重合。如果使用nodesepFunc 控制到不重叠，节点分布距离会特别大。
场所1 有三条连线
1->3
1->7
1->2
目前  1->2线与 1->7边重合。

--------------------
打开data数据中的 id8 和id9注释
边交叉

| Environment | Info |
|---|---|
| g6 | 4.3.11 |
| System | window10 |
| Browser | Chrome/92.0.4515.107 |

---
期望节点间连线补不重合，且不交叉 。

期望类似这种效果
![image](https://user-images.githubusercontent.com/48666945/140702317-ea76e399-c3a8-4716-bfea-6bf8b7ad80b8.png)

**Comment by mxz96102** [comment]
建议使用polyline，他会读取dagre布局里面的折线点：
![image](https://user-images.githubusercontent.com/15213473/141065441-23c058ed-da51-4ad1-8191-8eb00727158c.png)

**Comment by qiYuei** [comment]
> 建议使用polyline，他会读取dagre布局里面的折线点： ![image](https://user-images.githubusercontent.com/15213473/141065441-23c058ed-da51-4ad1-8191-8eb00727158c.png)

谢谢大佬回答！！！请问贝塞尔曲线是不支持 节点与线不重合嘛，对于折线来说贝塞尔曲线更美观点点。虽然折线可以通过radius来将它圆滑但是还是感觉有点怪怪

**Comment by mxz96102** [comment]
贝塞尔曲线呢主要是不会绕开其他节点，他的边计算是无关上下文的，你可以改写一个依据edge信息的point来贝塞尔的边。
