### ISSUE TITLE
TreeGraph的第三层超过一万个节点时，页面只显示一条竖线，向上向下拖拽也看不到第三层

### ISSUE THREAD

**Issue by BabyMing** [antvis/G6#3299]

**Comment by mxz96102** [comment]
可能达到了树图布局的上线，请问树图1w个叶子结点是什么样的场景呢，我们看看有没有可能通过交互优化

**Comment by BabyMing** [comment]
> 可能达到了树图布局的上线，请问树图1w个叶子结点是什么样的场景呢，我们看看有没有可能通过交互优化

> 
#

- **我们是三层的treegraph，第三层挂载的子设备，当子设备数量超过10000个的时候，就会只显示一条线******
- 
![微信图片_20211110174705](https://user-images.githubusercontent.com/40626690/141090260-fd9d7cba-aa8c-4ecc-9267-814cf1690661.png)

**Comment by Yanyan-Wang** [comment]
1w个节点就算画出来也看不清吧？建议从产品层做一下设计。比如过滤、分页等

https://g6.antv.vision/zh/examples/interaction/pagination#treePagination

**Comment by Yanyan-Wang** [comment]
从上面截图来看，似乎那条线是一条很长的边，应该后后面的子节点太多，撑开得太大。尝试设置布局的节点间距小一些、展开一个分支的时候收起其他内容、子节点过多时做 filter /省略/分页等

尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
