### ISSUE TITLE
关于removeBehaviour方法失效

### ISSUE THREAD

**Issue by wizali** [antvis/g6#33]
hi
我的流程是这样的：
  进入页面后，默认是complicated模式，点击“编辑”按钮后，切换到“edit”模式，我初始化net的时候，没有设置默认的“modes”字段。
现在的问题是：切换到“edit”模式后，双击画布报错，错误原因是“shortcut”这个行为。
我现在这样做：
```
function openEdit() {
  console.log('进入编辑模式');

  net.changeMode('edit');
  net.removeBehaviour('shortcut', 'edit');
  net.removeBehaviour('clickActive', 'edit');
}
```
但是双击画布以后还是会报错。
或者麻烦告诉我你们默认设置的“edit”模式都包括什么行为？我自定义一下“modes”字段。

**Comment by TomHuangCN** [comment]
https://antv.alipay.com/g6/api/net.html#modes
