### ISSUE TITLE
tooltip的content不支持修改

### ISSUE THREAD

**Issue by bingyuea** [antvis/G6#3300]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
tooltip的content不支持修改，初始化之后getContent可以修改content 

### What does the proposed API look like?
tooltip的content可以支持修改

**Comment by Yanyan-Wang** [comment]
可以描述一下原始需求吗

**Comment by bingyuea** [comment]
比如如下代码，我初始化tooltip组件，但后续其他地方想修改tooltip content字段的内容，此时没有办法修改（没有update方法）
`
 const tooltip = new G6.Tooltip({
          offsetX: 10,
          offsetY: 20,
          getContent (event) {
            const outDiv = document.createElement('div')
            outDiv.style.width = '180px'
            const model = event.item.getModel()
            outDiv.innerHTML = `<div><span style = 'width: 30px;display: inline-block'>名称</span>：${name}</div><div><span style = 'width: 30px;display: inline-block'>idx</span>：${model.idx}</div> `
            return outDiv
          },
          itemTypes: ['node', 'edge']
        })
        _t.plugins.tooltip = tooltip
`

**Comment by Yanyan-Wang** [comment]
根据 model 内容填充 content，不能满足需求吗？最差的办法可以 removePlugin 再重新 new 一个 addPlugin 到 graph 中

**Comment by bingyuea** [comment]
> 

恩 那只能addPlugin了

**Comment by image72** [comment]
@bingyuea @Yanyan-Wang 

我目前做了一个实现，有需要的可以自己修改

```jsx
// 显示 
const addTooltip = (model) => {
    const tooltip = new G6.Tooltip({
      getContent(ev) {
        // const model = ev.item._cfg.model;
        const {
          id = 0,
          title,
          refNum = 0,
          refByNum = 0,
          refNonFullTextNum = 0,
          refByNonFullTextNum = 0,
          relationId = 0,
        } = model;
        return `<div class="citeRelation-tooltip">
        <p>${model.title}</p>
        <p>参考文献: ${refNum}篇&nbsp;<span class="text-dim">(${refNonFullTextNum}篇无全文)</span></p>
        <p>被引: ${refByNum}篇&nbsp;<span class="text-dim">(${refByNonFullTextNum}篇无全文)</span></p>
        <p class="justify-end">
          <a class="btn" pid=${id} target="_blank" href="/pdf-view?docId=${model.id}&docType=1">阅读全文</a>&emsp;
          <a class="btn primary" rid=${model.id}>完整关系链</a>
        </p>
      </div>`;
      },
      offsetX: -130,
      trigger: "click",
      offsetY: -55,
      itemTypes: ["node"],
    });
    graph.addPlugin(tooltip);
    graph.initPlugins();
    return tooltip;
  };

  graph.on("node:click", (ev) => {
    ev.propagationStopped;

    const item = ev.item;
    graph.setItemState(item, "hover", true);
    // nodeClick(item);
    const { id } = item._cfg;
    nodeUpdate(id).then((res) => {
      // graph.updateItem(item, res);
      const tooltip = addTooltip(res);
      tooltip.showTooltip(ev);
    });
  });


// 隐藏

  const removeTooltip = () => {
    const plugins = graph.get("plugins");
    plugins
      .filter((plugin) => plugin.showTooltip)
      .forEach((plugin) => graph.removePlugin(plugin));
  };

  graph.on("tooltipchange", (ev) => {
    if (ev.action === "hide") {
      removeTooltip();
    }
  });
```
