### ISSUE TITLE
ComboForce布局下空的子Combo拖动后会消失

### ISSUE THREAD

**Issue by KeonYamato** [antvis/G6#3303]
- **G6 Version**: 4.3.11
- **Platform**: Chrome
- **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/28222772/141066583-084134c0-ce21-47ac-8b6b-8733c0defe8f.png)
- **CodePen Link**: https://codesandbox.io/s/keen-engelbart-fsfq1?file=/index.html

当使用ComboForce布局时，如果元素无连接状态，且子节点为空，拖动后会消失。
如案例所示，拖动Combo2后Combo2消失。

**Comment by Yanyan-Wang** [comment]
应该是一开始 combo 没有位置信息，拖动后跑到了别的地方，缩小画布之后可以看到。下个版本会尝试修复

**Comment by Yanyan-Wang** [comment]
该问题在当前版本已不存在
