### ISSUE TITLE
4.4.0啥时候发布啊，有几个bug

### ISSUE THREAD

**Issue by damnright** [antvis/G6#3304]
4.4.0啥时候发布啊，有几个bug

**Comment by Yanyan-Wang** [comment]
4.4.0-beta.0 可以先试下，你是说 4.4.0-beta.0 有 bug 吗？可以提出来我发正式版之前一起修复

**Comment by damnright** [comment]
4.4.0-beta.0 用npm更新，  引用报错呢，看了下是没有dist文件夹

**Comment by Yanyan-Wang** [comment]
4.4.1 试试

**Comment by Yanyan-Wang** [comment]
4.5.0 已经发布了哈。如果有遇到什么问题或者 bug，开 issue 直接描述哈
