### ISSUE TITLE
combo折叠后所有连线并在一起变成很粗的线不美观

### ISSUE THREAD

**Issue by sicun7** [antvis/G6#3306]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/cometor/pen/MWwNVdm](https://codepen.io/cometor/pen/MWwNVdm)

### Steps to reproduce
示例里我只建了两个节点, 线就很明显变粗了, 我试过了, 如果加更多的节点, 线太粗了, 非常不美观. 请问有什么配置可以在combo折叠的时候只显示一条线么

| Environment | Info |
|---|---|
| g6 | 4.3.11 |
| System | - |
| Browser | - |

**Comment by 15821171161** [comment]
有解决吗

**Comment by Yanyan-Wang** [comment]
defaultEdge 的 style 里面可以配置 lineWidth 的哈，会影响的合并边的～
