### ISSUE TITLE
要求追加家族谱系的功能

### ISSUE THREAD

**Issue by TinManGo** [antvis/G6#3308]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决了一系列的需要展现家族谱系的需求，例如人物关系、遗传病研究、族谱展示等方面的展示问题。

### What does the proposed API look like?
仿照GO.JS中的
// n: name, s: sex, m: mother, f: father, ux: wife, vir: husband, a: attributes/markers
{ key: -10, n: "Paternal Grandfather", s: "M", m: -33, f: -32, ux: -11, a: ["A", "S"] }
可以设置父母的连线，设置妻子或丈夫的连线，以及颜色标注，死亡标注等。

**Comment by Yanyan-Wang** [comment]
啥意思？我理解你想要的东西可以通过 G6 提供的能力组装而得

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。

**Comment by TinManGo** [comment]
是的但是对于我这个新手来讲还是很困难，我记得介绍中在2021下半年有家族谱系的规划，可是目前还没有。

**Comment by Yanyan-Wang** [comment]
可以参考这几个 demo：
https://g6.antv.antgroup.com/examples/case/treeDemos/#indentedTree
https://g6.antv.antgroup.com/zh/examples/case/treeDemos/#knowledgeTreeGraph
