### ISSUE TITLE
请问有没有类似er图的布局功能

### ISSUE THREAD

**Issue by qq919006380** [antvis/G6#3309]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决了常用的业务布局问题

### What does the proposed API look like?
在layout中添加一个er图布局

**Comment by Yanyan-Wang** [comment]
有的，@antv/layout 中的 er 可以尝试下，似乎还没有正式抛出

**Comment by Yanyan-Wang** [comment]
https://github.com/antvis/layout/tree/master/src/layout/er

**Comment by Yanyan-Wang** [comment]
Hi, dear user. Since there was no response for a long time, we cannot figure out the answer of the problem you described. If there is new progress, feel free to open a new issue.
