### ISSUE TITLE
使用toFullDataURL和toDataURL定时生成图片，当浏览器tab页在当前页是生成的图片正常，切换到浏览器其他tab页则生成的图片空白

### ISSUE THREAD

**Issue by lavenderMF** [antvis/G6#3310]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/antvis/G6/blob/master/packages/pc/src/graph/graph.ts#L248](https://github.com/antvis/G6/blob/master/packages/pc/src/graph/graph.ts#L248)

### Steps to reproduce
使用toFullDataURL和toDataURL定时生成图片，当浏览器tab页在当前页是生成的图片正常，切换到浏览器其他tab页则生成的图片空白

| Environment | Info |
|---|---|
| g6 | 4.4.1 |
| System | win |
| Browser | chrome |

---
还未确认是否是canvas生成的问题还是G6有做相关处理导致
![image](https://user-images.githubusercontent.com/19815805/142182719-9524d79d-aaeb-40eb-8030-1cce40d523f0.png)

**Comment by Yanyan-Wang** [comment]
什么意思？点了下载之后切换到其他 tab 页面吗？

**Comment by lavenderMF** [comment]
不好意思 标题没写清楚 是setInterval定时调用toFullDataURL和toDataURL生成图片 chrome浏览器没有在当前的tab页 导出的图片是空白的

**Comment by Yanyan-Wang** [comment]
那可能就是切换之后就得不到原来页面的上下文了，所以得不到画布上的内容了
