### ISSUE TITLE
Menu插件handleMenuClick函数如何获取graph实例对象

### ISSUE THREAD

**Issue by brusehht** [antvis/G6#3312]
在Vue框架下使用G6，在使用右键菜单的过程中，handleMenuClick函数只能够到item对象本身，也无法够到this对象，如果要执行全局的增删改操作，就必须要获取graph实例对象，不知道如何获取相关对象。我另一个issue中https://github.com/antvis/G6/issues/2204看到也有朋友提到类似问题，但似乎没有解决，这里再提一下，请各位大神协助。

**Comment by Yanyan-Wang** [comment]
handleMenuClick 第三个参数是 graph
