### ISSUE TITLE
AntV的canvas的drag and drop，会导致整个canvas无法正常使用

### ISSUE THREAD

**Issue by ghoshorn** [antvis/G6#3313]
https://user-images.githubusercontent.com/7859403/142365481-b77ec1ce-909f-48fa-beb6-e0301dcda258.mov

使用最简单的官方样例即可reproduce （Windows specific， Mac没问题）
https://antv-g6.gitee.io/en/examples/net/dagreFlow#basicDagre

步骤：拖拽canvas的空白处，拖到canvas画布外，松开鼠标。后面再拖拽画布，就可以发现canvas已经不能正常相应了。

**Comment by Yanyan-Wang** [comment]
duplicated to https://github.com/antvis/G6/issues/1750
