### ISSUE TITLE
如何自动计算新节点位置

### ISSUE THREAD

**Issue by rmd1710714107** [antvis/G6#3317]
每次我添加新节点的时候必须指定节点的x，y值，这样节点才会加在我想要的地方。如果不指定节点就会自动加在左上角，**我想问一下有没有办法让新增加的节点根据初始化图实例时选择的布局方式自动计算位置**，而不是我手动指定。

**布局配置**

``` javascript
layout: {
          type: 'dagre', 
},
```

**Comment by mxz96102** [comment]
走changeData变更数据会自动重新布局 or 加入节点后重新布局

**Comment by rmd1710714107** [comment]
> 走changeData变更数据会自动重新布局 or 加入节点后重新布局

ok,明白了，感谢
