### ISSUE TITLE
自定义节点内通过循环添加shape，在触发事件后第一个shape被重绘为最后一个shape

### ISSUE THREAD

**Issue by KeonYamato** [antvis/G6#3319]
版本：4.3.11
浏览器： Chrome
问题描述： 自定义节点内通过循环添加shape，在触发事件后第一个shape被重绘为最后shape。
一个自定义节点rect中通过循环添加子shape，然后当触发事件时（如“mouseleave”，“click”)，节点内子shape的第一个shape被重绘为最后一个shape，但是却保留原来的相对坐标。
![image](https://user-images.githubusercontent.com/28222772/142989852-1916d88c-e9c0-4e0b-9040-e3939e9bed4f.png)
![image](https://user-images.githubusercontent.com/28222772/142990207-8908d21a-060b-45d0-8006-7f4eb373d347.png)

示例链接：https://codesandbox.io/s/misty-snowflake-mqcbm?file=/index.html

示例中为text shape，其他shape第一个添加的图形则会消失。

如果draw函数中有两次循环添加，第二次循环添加的shape不会出现这个bug，而第一次循环添加的第一个图形会变为第二次循环最后一个图形，如图：
![image](https://user-images.githubusercontent.com/28222772/142991002-a96c3a88-9777-48eb-804d-8f89f11a347e.png)

**Comment by Yanyan-Wang** [comment]
请为不同的图形设置不同的 name。否则在设置状态样式以及复原的时候可能会因为 name 相同而导致样式使用在不合理的图形上。

**Comment by KeonYamato** [comment]
> 请为不同的图形设置不同的 name。否则在设置状态样式以及复原的时候可能会因为 name 相同而导致样式使用在不合理的图形上。

原来如此，谢谢🙏
