### ISSUE TITLE
自定义边getPath的返回值是什么意思

### ISSUE THREAD

**Issue by mabelyong** [antvis/g6#332]
* **G6 Version**:  2.0.3-beta.1

```javascript
G6.registerEdge('VH', {
  getPath: function getPath(item) {
    var points = item.getPoints();
    var start = points[0];
    var end = points[points.length - 1];
    return [['M', start.x, start.y], ['L', start.x, end.y], ['L', end.x, end.y]];
  }
});
```
最后return返回出来的坐标点是怎么用的，有没有具体的说明，自定义HVH边是怎么实现的，1.x版本是内置的，这个版本删掉了？？

**Comment by ascoders** [comment]
`[['M', start.x, start.y], ['L', start.x, end.y], ['L', end.x, end.y]]`

的意思是画一条 L 线，M 表示移动，L 表示画线。这都是 SVG 的基础语法，G6 稍微封装了下。

这种语法一共有 10 个，详情见：https://www.jianshu.com/p/c819ae16d29b。
