### ISSUE TITLE
添加combo后，执行undo操作无效

### ISSUE THREAD

**Issue by niechengyang** [antvis/G6#3323]
我在代码里执行了添加combo的操作，在执行undo操作时，发现undo栈里将combo的算子其实是隐藏起来了，真正执行的是显示那些组合的算子，这样算子就一个一个的被显示出来，而创建的combo还撤销不掉，能不能undo的时候还原上一步的操作呢

**Comment by Yanyan-Wang** [comment]
v4.7.17 已支持
