### ISSUE TITLE
G6怎么实现决策图

### ISSUE THREAD

**Issue by 18300618319** [antvis/G6#3324]
![image](https://user-images.githubusercontent.com/26192378/143408151-5b238ad6-65c9-4a17-85e9-b047af13e7a4.png)

**Comment by 18300618319** [comment]
可以实现这个吗

**Comment by Yanyan-Wang** [comment]
自定义节点、自定义边，基本可以实现。布局和边类似  https://g6.antv.vision/zh/examples/case/treeDemos#customFlow

**Comment by 18300618319** [comment]
实现不了呀
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/G6"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月3日(星期五) 中午11:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [antvis/G6] G6怎么实现决策图 (Issue #3324)





 
自定义节点、自定义边，基本可以实现。布局和边类似  https://g6.antv.vision/zh/examples/case/treeDemos#customFlow
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Yanyan-Wang** [comment]
看看文档，多尝试一下，应该可以哈

**Comment by 18300618319** [comment]
中间还有乘号和减号是实现不了的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/G6"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月3日(星期五) 下午3:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [antvis/G6] G6怎么实现决策图 (Issue #3324)





 
看看文档，多尝试一下，应该可以哈
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Yanyan-Wang** [comment]
简单复刻了一个上图的 demo：http://g6.antv.antgroup.com/zh/examples/case/treeDemos/#decisionTree2
