### ISSUE TITLE
在移动端minimap不支持手势拖拉？

### ISSUE THREAD

**Issue by qq707631575** [antvis/G6#3327]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
1.移动端拖拉minimap的框，并不能拖动。
2.还有，拖拉时候的鼠标样式能不能自定义改一下？目前拖拉的时候鼠标样式是禁用的样式

| Environment | Info |
|---|---|
| g6 | 4.0.4 |
| System | - |
| Browser | - |

**Comment by Yanyan-Wang** [comment]
移动端可能无法响应 DOM 的 'dragstart' 'drag' 'dragend' 事件。移动端图可视化推荐 @antv/f6 。

希望用 G6 的话，可能需要参考这里自定义 minimap：https://github.com/antvis/G6/blob/master/packages/plugin/src/minimap/index.ts

这里的 Line 109, 151, 189 给 DOM 绑定的是 'dragstart' 'drag' 'dragend' 事件

**Comment by Yanyan-Wang** [comment]
鼠标样式可以考虑通过拿到拖拽狂的 DOM 修改其 CSS 来做到。拖拽框的 DOM class 可以通过配置项 viewportClassName 来指定，若不指定则默认为 'g6-minimap-viewport'
