### ISSUE TITLE
自定义流程图能否收缩节点？

### ISSUE THREAD

**Issue by qq707631575** [antvis/G6#3328]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
避免全流程节点太多影响视觉

### What does the proposed API look like?
全流程图，多节点，有开始节点和结束节点，中间的那些节点可收缩

**Comment by mxz96102** [comment]
没有自带的功能，只能提供一个思路，用一个点代替中间的点，点击收起吧这一个点和其他点替换

**Comment by qq707631575** [comment]
> 没有自带的功能，只能提供一个思路，用一个点代替中间的点，点击收起吧这一个点和其他点替换

当前也只能这样了，移动端下minimap是都有配置可以让他可以拖动？

**Comment by Yanyan-Wang** [comment]
移动端 minimap 拖拽问题在 https://github.com/antvis/G6/issues/3327 讨论
