### ISSUE TITLE
怎么动态控制edge

### ISSUE THREAD

**Issue by damnright** [antvis/G6#3329]
怎么实现：给边添加bend point和control point，然后通过拖动point去控制边的弯折程度、方向，有没有实现思路啊

**Comment by mxz96102** [comment]
G6默认不提供边的编辑功能，只能通过自定义交互+自定义边来进行，难度较大
不过推荐你可以看看X6: https://antv-x6.gitee.io/zh/examples/edge/tool#vertices
他对于编辑更加友好

**Comment by Yanyan-Wang** [comment]
图编辑场景推荐使用 @antv/x6
