### ISSUE TITLE
关于2.x。。。

### ISSUE THREAD

**Issue by zx8887** [antvis/g6#333]
* **G6 Version**: 1.2.8
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

厉害了。许久没关注G6（在弄后台业务逻辑），今天上来一看更新到了2.0。
那么问题来了，之前写的代码是否就废了，Net已被移出，还有很多细节还没看。
但是最让我感兴趣的是可视化的editor，因为之前一直在自己捣鼓，官方出了一个让我情何以堪。
那么问题又来了，我是继续捣鼓我的1.X版本，还是拥抱官方版本。。。
看了一会官方Editor，提出几个问题、建议（因为太激动了，我还没仔细研究，如果有或者错请见谅）

1. Editor是否能自定义注册node（html节点）和edge

2. Editor是否集成了统一布局插件，我看了下官方文档貌似没有对应的API

3. e....刚刚看到了前言。。 **当前 G6-Editor 仅用于学习交流，商业使用需要得到授权**。。。。好吧。我只有自己捣鼓2.x的自定义可视化吧。

希望自己捣鼓遇到问题能在这里得到各路大神的指导，不说了，板砖去。

最后，放一张自己捣鼓的1.x可视化编辑界面，希望能够顺利迁移到2.x

![Image](https://user-images.githubusercontent.com/13731281/41764667-6e2a6428-7634-11e8-91e3-4af7c94768cb.gif)

**Comment by zx8887** [comment]
请问有木有商业授权的价格。哈哈

**Comment by zx8887** [comment]
希望2.0的文档早日完善。还有期待2.1的dom节点！！！

**Comment by shengbeiniao** [comment]
我最近也在捣鼓2.0的可视化编辑，可以一起研究啊~

**Comment by zx8887** [comment]
@shengbeiniao 可以可以，我目前等文档完善点，不然没多少时间看源码，还有1.x我做得差不多了。迁移到2.x看样子估计有点费力。。。。得推翻了重来。。

**Comment by Slardar888** [comment]
咱们版本一样，我是做了一个潮流图编辑器，对线和节点的要求比较多，都需要数据驱动，矩阵旋转问题兄弟遇到了么？

**Comment by zx8887** [comment]
@Slardar888 我这个就是设备拓展图，暂时没遇见矩阵旋转问题，倒是基本上把文档看了个遍，该试的功能都试了一遍。

**Comment by Slardar888** [comment]
好的吧，最近在搞这个，原型链上有些方法文档没有，只能自己慢慢看了。

**Comment by TomHuangCN** [comment]
* 2.x 架构调整，到时 1.x 的迁移成本较大。对于 1.x 的老用户肯定是有伤害的，这个必须道歉。、
* G6-Editor 目前的成熟度确实较低，详细接口还在与内部用户打磨中。顺利的话预计明年能开源。
* 至于沿用 1.x 还是基于 2.x G6 自己开发编辑器。还是用 G6-Editor 。这个由你们根据实际情况而定。

作为 G6 主程，我个人推荐大家看 G6 和一些 G6 插件的源码，直接基于 G6 二次开发上层的编辑功能。这样可能目前比较可持续发展的做法，对个人能力的提升也有很大帮助。

**Comment by TomHuangCN** [comment]
接口的话一定不要直接看代码就用了，一定要使用文档上发布的接口，这些接口我们是有做不变更保证的。其它接口是不做保证的。如果接口不够用，可以起 issue 提。 @Slardar888

**Comment by shengbeiniao** [comment]
@TomHuangCN  我感觉做开源并不是简单把代码开放整个生态就能发展起来，如果能把设计思想、算法、架构还有一些核心的功能点也开源的话，非常利于社区的成长，G6里面太多的自定义事件做消息传递，看源码、调试实在痛苦，还有动态绑定机制，有点反常规，举个栗子

Node的事件注册，是监听graph，用"node:click"的形式，感觉非常奇怪，想createjs这样的动画库，都是把shape作为一个对象，自己绑定监听，和html里面的button绑定没啥区别，也非常容易扩张，结果我看了源码graph集成event，在调试的时候非常麻烦，经常不知道arguments怎么传递的，比如这段controller/event.js
```
_registerMouseEvents() {
    const graph = this.graph;
    const self = this;
    const el = graph.getMouseEventWarrper();
    const _events = this._domEvents;
    Util.each(MouseEventTypes, item => {
      _events.push(Util.addEventListener(el, item, ev => {
        const oldEventObj = this._currentEventObj;
        this._oldEventObj = oldEventObj;
        this._processEventObj(ev);
        const currentEventObj = this._currentEventObj;

        // emit simulate events like click, dragstart, dragend, drop, dtagover,  mouseenter, mouseleave
        self._simulateEvents(ev, oldEventObj, currentEventObj);

        // emit normal events
        if ([ EVENT.MOUSELEAVE, EVENT.MOUSEENTER ].indexOf(ev.type) !== -1) {
          self._triggerEvent(CANVAS + ev.type);
        }
        self._triggerEvent(ev.type);

        if (ev.type === EVENT.MOUSELEAVE) {
          // trigger canvas dragleave when out of canvas , user can clear things that record by themselves
          if (this._dragging) {
            self._triggerEvent(EVENT.DRAGLEAVE, Util.mix({}, currentEventObj, { item: null, shape: null, currentItem: this._dragEventObj.item, currentShape: this._dragEventObj.shape }));
          }
          self._initEventStates();
        }
      }));
    });
  }
```
要想理解这两个对象，非常头疼
        const oldEventObj = this._currentEventObj;
        this._oldEventObj = oldEventObj;

**Comment by TomHuangCN** [comment]
感谢反馈。目前团队正在做一些布道类的事情，设计思想，架构，算法方面的东西，整个 AntV 技术栈后续都会逐步透出。下面详聊一下 G6 的事件机制。

传统基于捕获，冒泡，在单个 shape 上绑定事件的机制，在 dom 盛行的年代，确实得到了很大的推广，确实也比较好用，易于理解。

我们最初也实现过一整套这经典的事件机制，但实践过程中发现，这种机制往往会滥用，导致一些严重的性能问题。所以最后只保留事件委托给父元素，由父元素统一触发。

由于我们是 canvas 技术栈，所以有些鼠标事件需要自己模拟。

oldEventObj 和 currentEventObj 分别是上一次鼠标事件对应的模拟事件对象，和当前鼠标事件模拟的事件对象。

**Comment by shengbeiniao** [comment]
@TomHuangCN ￣□￣｜｜原来是已经填过坑了
