### ISSUE TITLE
边流动动画速度叠加

### ISSUE THREAD

**Issue by yunzzi** [antvis/G6#3330]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/beautiful-pond-i93nk?file=/src/index.js)

### Steps to reproduce
实现边流动状态切换效果是发现了边的流动速度会叠加的问题：   
1.点击中心节点，所有边流动。
2.再点击其中一条边，先清空所有边流动状态（因为可能有很多节点和边的情况，所以用这种方式），再设置该条边流动，此时发现流动速度叠加。
3.任何一条边如果是running状态，如果是先清除running，再设置running，都会有这样的问题。

是哪里写的不对吗？
这种情况下该怎么避免流动速度叠加呢？

| Environment | Info |
|---|---|
| g6 | 4.5.0 |
| System | win10 |
| Browser | google 95.0.4638.69（正式版本） （64 位） |

**Comment by Yanyan-Wang** [comment]
可能是底层渲染引擎的 stopAnimate 有些问题（不过你代码里写成了 stopAnimation）。
通过 pauseAnimate 和 resumeAnimate 代替，可以解决：


G6.registerEdge(
  "can-running",
  {
    setState(name, value, item) {
      const shape = item.get("keyShape");
      if (name === "running") {
        const hasAnimation = shape.get('animating');
        if (hasAnimation) {
          shape.pauseAnimate();
          shape.attr("lineDash", null);
        }
        if (value) {
          let index = 0;
          if (hasAnimation) shape.resumeAnimate()
          else shape.animate(/*...some params */);
        }
      }
    }
  },
  "cubic-horizontal"
);

**Comment by yunzzi** [comment]
@Yanyan-Wang 蟹蟹大佬！
