### ISSUE TITLE
关于自定义节点旋转Group,旋转过后,移动节点会恢复到初始角度

### ISSUE THREAD

**Issue by SeuHkx** [antvis/G6#3331]
1.在自定义节点中,给group设置了旋转角度, 但当点击节点移动的时候,会自动恢复到默认的角度,查看group的矩阵,被复原了.请问是需要设置什么属性或者把属性挂载在什么对象上面吗?
2.点击拖拽的节点是使用的内置的drag-node
![123](https://user-images.githubusercontent.com/5221292/143813316-27ea789f-a2bc-4584-93b4-a2c12c130ba7.gif)

**Comment by mxz96102** [comment]
因为移动节点是做了节点的矩阵平移，所以建议在定义节点给的group里面再套一层group再做变化，不然容易会被变换移除了

**Comment by SeuHkx** [comment]
> 因为移动节点是做了节点的矩阵平移，所以建议在定义节点给的group里面再套一层group再做变化，不然容易会被变换移除了

1.还有就是group的初始的矩阵和单图元的初始矩阵为什么不一样呢?能否解答一下疑惑呢?
group的矩阵[1, 0, 0, 1, 0, 0, 0, 0, 1]
官网旋转例子矩阵 [1, 0, 0, 0, 1, 0, 0, 0, 1]
2.初始化的状态旋转中心是没问题, 但改变了长宽 中心点就偏移了,这个中心点怎么能够设置回来呢?

![12345](https://user-images.githubusercontent.com/5221292/144190371-a4445f56-9469-41e6-a7ae-da53ec74c422.gif)

**Comment by Yanyan-Wang** [comment]
未设置过的图形/图形分组的矩阵都是 null，使用矩阵需要使用单位矩阵进行计算后应用到图形/图形分组上。节点的在外层图形分组 node.getContainer() 的矩阵有值是因为，节点的位置是通过矩阵来设置的，所以节点已经被内部设置了矩阵。

进行旋转一般使用下面代码，其中 (x, y) 是旋转中心坐标，我理解你拉伸之后，旋转中心应该变了
            matrix = transform(matrix, [
              ['t', -x, -y], // 先将旋转中心移到自身坐标系的原点
              ['r', rotate], // 旋转
              ['t', x, y], // 再移回来
            ]);

**Comment by SeuHkx** [comment]
> 未设置过的图形/图形分组的矩阵都是 null，使用矩阵需要使用单位矩阵进行计算后应用到图形/图形分组上。节点的在外层图形分组 node.getContainer() 的矩阵有值是因为，节点的位置是通过矩阵来设置的，所以节点已经被内部设置了矩阵。
> 
> 进行旋转一般使用下面代码，其中 (x, y) 是旋转中心坐标，我理解你拉伸之后，旋转中心应该变了 matrix = transform(matrix, [ ['t', -x, -y], // 先将旋转中心移到自身坐标系的原点 ['r', rotate], // 旋转 ['t', x, y], // 再移回来 ]);

解决了, 动态计算了拉伸的偏移量
感谢

**Comment by zzjjbbaa** [comment]
> > 未设置过的图形/图形分组的矩阵都是 null，使用矩阵需要使用单位矩阵进行计算后应用到图形/图形分组上。节点的在外层图形分组 node.getContainer() 的矩阵有值是因为，节点的位置是通过矩阵来设置的，所以节点已经被内部设置了矩阵。
> > 进行旋转一般使用下面代码，其中 (x, y) 是旋转中心坐标，我理解你拉伸之后，旋转中心应该变了 matrix = transform(matrix, [ ['t', -x, -y], // 先将旋转中心移到自身坐标系的原点 ['r', rotate], // 旋转 ['t', x, y], // 再移回来 ]);
> 
> 解决了, 动态计算了拉伸的偏移量 感谢

大佬，能否分享下你的解决方案
