### ISSUE TITLE
layout 布局算法影响自定义边的效果

### ISSUE THREAD

**Issue by wflixu** [antvis/G6#3332]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/trusting-hellman-104rf?file=/src/index.js)

### Steps to reproduce
1. 默认不设置 layout 配置项，自定义边正常
2. 添加layout配置，如设置成 type:'force',自定义边显示不正常（重现用例中已经注释掉了，启用layout只需放开注释）

| Environment | Info |
|---|---|
| g6 | 4.5.0 |
| System | macos v 12.0.1 |
| Browser | 96.0.4664.55（正式版本） (arm64) |

**Comment by wflixu** [comment]
如果不启用layout，效果是这样的：
![image](https://user-images.githubusercontent.com/37231473/143823758-712c4942-532a-4518-8ea9-73e627e8baf3.png)

设置layout:{type:'force'} 后，自定义边效果错乱

![image](https://user-images.githubusercontent.com/37231473/143823862-51f25feb-4a13-41c5-88bb-5cbf28af35ac.png)

为了自定义平行线多线，自定义边用了 2个path shape

```
 G6.registerEdge(
    "th-cw-l750-2",
    {
      options: {
        style: {}
      },
      draw(cfg, group) {
        const startPoint = cfg.startPoint;
        const endPoint = cfg.endPoint;
        // console.log("th-cw-l750-2", startPoint, endPoint);
        const shape = group.addShape("path", {
          attrs: {
            stroke: "#FA800A",
            lineWidth: 12,
            path: [
              ["M", startPoint.x, startPoint.y],
              ["L", endPoint.x, endPoint.y]
            ],
            ...(cfg.style ?? {})
          },
          name: "th-cw-l7501"
        });
        group.addShape("path", {
          attrs: {
            stroke: "white",
            lineWidth: 4,
            path: [
              ["M", startPoint.x, startPoint.y],
              ["L", endPoint.x, endPoint.y]
            ],
            ...(cfg.style ?? {})
          },
          name: "th-cw-l75012"
        });
        return shape;
      },

      update(cfg, edge) {
        // const startPoint = cfg.startPoint;
        // const endPoint = cfg.endPoint;
        // // this.draw(cfg,group)
        // console.log("th-cw-l750-2 update", startPoint, endPoint, edge);

        return edge;
      }
    }
    // 'single-edge',
  );
```

**Comment by Yanyan-Wang** [comment]
你的 demo 中有两个自定义边，蓝色的那个没有问题。和布局没关系，即使你配置了拖拽节点 behavior，拖拽节点也不能使橙色的边跟随更新。原因是橙色边的自定义边中实现了 update 方法，使得更新的时候调用了这个 update 方法，而你写的 update 方法里没有做任何更新的操作。把 update 方法删掉，更新的时候会走 draw 方法，就可以正常更新了

**Comment by wflixu** [comment]
> 蓝色的那个没有问题

没注意update 方法，谢谢回复
