### ISSUE TITLE
设置边上文本背景的示例中，会出现文本与背景偏离的样式问题

### ISSUE THREAD

**Issue by zmbxy95** [antvis/G6#3333]
如第一张图中所示为4.3.2版本，显示正常，拖动节点，也显示正常。
![image](https://user-images.githubusercontent.com/50108232/143824453-85f86832-c1c5-425c-bd5d-54edaab510b6.png)
打开codesandbox，选择4.5.0版本，文本与背景显示偏离
![image](https://user-images.githubusercontent.com/50108232/143824500-f35993c8-1ee4-4e26-ab96-95232d6513c0.png)

**Comment by zmbxy95** [comment]
这个问题是解决了吗？我看现在的4.5.1版本好像没问题了

**Comment by Yanyan-Wang** [comment]
v4.5.2 已修复
