### ISSUE TITLE
如何调整,让右边 alps_file3 节点与左边 alps_file2 节点处于同一水平位置？

### ISSUE THREAD

**Issue by wjxfhxy** [antvis/G6#3334]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/affectionate-northcutt-6b9md?file=/src/index.js)

### Steps to reproduce
demo如连接所示，如何让右边 alps_file3 节点与左边 alps_file2 节点处于同一水平位置？

| Environment | Info |
|---|---|
| g6 | 4.5.0 |
| System | - |
| Browser | - |

**Comment by Yanyan-Wang** [comment]
在节点数据中可以指定该节点的层级 layer。例如在  alps_file3 节点数据中配置 layer: 1

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
