### ISSUE TITLE
focusItem() 之后为什么treegrph 会向右下方以后，而不在视图的中心

### ISSUE THREAD

**Issue by BabyMing** [antvis/G6#3335]
useDeepCompareEffect(() => {
    setTimeout(() => {
      if (topology_data?.id && graph_new) {
        if(!node_id.node && !node_id.update){
          graph_new.data(topology_data);
          graph_new.render();
          graph_new?.fitCenter()
        }else if(node_id.node && !node_id.update){
          graph_new.refresh();
          graph_new.focusItem(node_id.node, true, {
            easing: "easeCubic",
            duration: 500,
          })
        }else if(node_id.node && node_id.update) {
         //在这一步会移动到右下角。。。
          graph_new.changeData(topology_data);
          try {
            graph_new.focusItem(node_id.node, true, {
              easing: "easeCubic",
              duration: 500,
            })
            graph_new.setItemState(node_id.node, "selected", true);
          } catch (error) {
            graph_new.render();
            graph_new?.fitCenter()
          }
        }
      }
    }, 500)
  }, [graph_new, topology_data, node_id]);

**Comment by Yanyan-Wang** [comment]
请提供在线复现 demo

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
