### ISSUE TITLE
层次布局支持自定义顶点

### ISSUE THREAD

**Issue by Duanzh** [antvis/G6#3337]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
希望可以指定某个node为层次布局的顶点

### What does the proposed API look like?
item.toTop()

**Comment by Yanyan-Wang** [comment]
使用 dagre 布局的话，可以在节点数据中指定每个节点的层级，layer: 0

**Comment by Duanzh** [comment]
![image](https://user-images.githubusercontent.com/13288185/144962454-5c6ac564-a563-4037-8367-091d0697fcec.png)
![image](https://user-images.githubusercontent.com/13288185/144962545-e8767fae-2944-4308-9fef-ba1f9ebf9f0e.png)

在节点中指定layer的话，会出现报错（如图2所示）：
The following error may be caused by improper layer setting, please make sure your manual layer setting does not violate the graph's structure:

**Comment by Yanyan-Wang** [comment]
这个层级的指定目前不能违背层次布局的原则：按照边的流向排列方向。也就是说，对于一条边来说 source 的 layer 应当小于 target 的 layer。它一般用于满足这个条件下的层级指定。

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
