### ISSUE TITLE
webpack can't pack G6 with UglifyJs

### ISSUE THREAD

**Issue by hopepan** [antvis/G6#3338]
<img width="834" alt="1638350664(1)" src="https://user-images.githubusercontent.com/5117803/144207509-b3618a8c-0571-40dc-bd5a-0806417a011e.png">
An exception was thrown as the screen dump above when npm build with webpack, which pointed out the UglifyJs has some conflict with G6, am I right? how can I fix it? thx

**Comment by Yanyan-Wang** [comment]
https://www.programmersought.com/article/50451305517/

**Comment by Yanyan-Wang** [comment]
Hi, dear user. Since there was no response for a long time, we cannot figure out the answer of the problem you described. If there is new progress, feel free to open a new issue.
