### ISSUE TITLE
关于group旋转问题

### ISSUE THREAD

**Issue by Slardar888** [antvis/g6#334]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

版本是1.2.8，addShape方法生成的对象的旋转是基于父元素的，我想根据自身坐标添加一个角度属性。实现一个可以跟随折线移动，方向为当前线切线向方的箭头。

**Comment by TomHuangCN** [comment]
https://www.yuque.com/antv/g6/custom-edge#xgnras
