### ISSUE TITLE
mindmap children怎么传边的数据？

### ISSUE THREAD

**Issue by yangyipeng888** [antvis/G6#3340]
脑图中自定义边  但是传graph.data的data只有children字段，怎么传边的数据呢

**Comment by Yanyan-Wang** [comment]
TreeGraph 的边就是树图的数据结构的嵌套关系解析来的，不需要另外传边。且，树图不可以有环

**Comment by garygao12580** [comment]
> 脑图中自定义边 但是传graph.data的data只有children字段，怎么传边的数据呢

树图中 graph.data不能指定边的数据，边是根据children自动生成的。如果要改边的一些属性，可以在 `graph.render`之前 调用`graph.edge`方法，在回调中动态设置 边的属性。
`graph.edge((edge) => ({
     a: 1,
     b:2,
}))`

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
