### ISSUE TITLE
使用registerNode自定义时报错

### ISSUE THREAD

**Issue by i7eo** [antvis/G6#3343]
我想使用registerNode来做一个新的结点，这个新节点中只是使用内置图形进行一些组合。但是在 `registerNode` 中使用 `group.addShape('diamond', { //...})` 会 crash 。使用 `rect`/ `circle` 就正常。。。

复现链接：https://codesandbox.io/s/youthful-silence-659vv?file=/index.js:660-687
上述链接中的代码是从官网例子而来

**Comment by Yanyan-Wang** [comment]
addShape 添加的图形就这些： https://g6.antv.vision/zh/docs/api/shapeProperties

没有 'diamond' 图形，有一种叫 'diamond' 的内置节点，请注意区分“节点”和“图形“。
想添加 'diamond' 图形，可以使用 marker 图形，https://g6.antv.vision/zh/docs/api/shapeProperties#%E6%A0%87%E8%AE%B0%E5%9B%BE%E5%BD%A2-marker

**Comment by i7eo** [comment]
> addShape 添加的图形就这些： https://g6.antv.vision/zh/docs/api/shapeProperties
> 
> 没有 'diamond' 图形，有一种叫 'diamond' 的内置节点，请注意区分“节点”和“图形“。 想添加 'diamond' 图形，可以使用 marker 图形，https://g6.antv.vision/zh/docs/api/shapeProperties#%E6%A0%87%E8%AE%B0%E5%9B%BE%E5%BD%A2-marker

好的😢
