### ISSUE TITLE
问题：@antv/g6-pc 包的目的是什么？ ------- Question: What is the purpose of the `@antv/g6-pc` package?

### ISSUE THREAD

**Issue by cliffordfajardo** [antvis/G6#3344]
`@antv/g6-pc` 包的目的是什么？
我注意到 `@antv/g6` 所做的唯一一件事就是导入 `@antv/g6-pc` 并对其进行装饰。

![picture](https://user-images.githubusercontent.com/6743796/144532832-194776d7-8adc-444e-b34a-a95fd969d72a.png)

我只是好奇，因为我正在调试依赖于这个 NPM 包的库之一

@Yanyan-Wang @elaine1234 @baizn 

之后请随时关闭此问题，以免弄乱真正的问题 😄

Does the G6 team speak/comprehend English  as well❓
I am curious,  because I want to make your lives easier when reading PR comments or questions on here with the limited time everyone has (I can use google translate if that makes things easier)

<details>
   <summary> UPDATE: Answer (English)</summary>
   
The purpose of unpacking is to expand to the mobile terminal. The interaction and rendering in the pc are all designed on the pc side. If you extend the mobile terminal, there may be a g6-mobile package, which is similar to the pc package, but all the interaction and rendering in it are designed on the mobile terminal. For example, click will become touch/tap, etc.

But currently we recommend users to use @antv/f6 on the mobile terminal
</details>

**Comment by Yanyan-Wang** [comment]
拆包的目的是为了可扩展到移动端。pc 里面的交互、渲染等都以 pc 端来设计的。如果扩展移动端，可能有一个 g6-mobile 包，和 pc 包类似，但里面所有的交互、渲染都以移动端来设计，比如 click 会变成 touch/tap 等

**Comment by Yanyan-Wang** [comment]
但目前我们推荐用户在移动端使用 @antv/f6

**Comment by cliffordfajardo** [comment]
谢谢
