### ISSUE TITLE
采用 G6.registerBehavior() 注册的自定义行为，keyup、keydown事件怎么清除监听？

### ISSUE THREAD

**Issue by kui913941251** [antvis/G6#3345]
我在注册一个自定义行为的时候，监听了keyup事件，但是退出组件后好像没有清除，再次进入会叠加监听事件。

**Comment by kui913941251** [comment]
版本为3.5.2

**Comment by Yanyan-Wang** [comment]
请提供在线复现 demo


强烈建议尽快升级，现在最近是 4.5.0

**Comment by kui913941251** [comment]
> 请提供在线复现 demo
> 
> 强烈建议尽快升级，现在最近是 4.5.0

好的，我之前就像升级来着，但是这是用的别人封装好了的，里面有一些依赖像 

import { shapeBase } from '@antv/g6/lib/shape/shapeBase'
import Shape from '@antv/g6/lib/shape/shape'

等等这些在lib文件夹下面的引入在新版里面找不到呢。

**Comment by kui913941251** [comment]
@Yanyan-Wang 

> 请提供在线复现 demo
> 
> 强烈建议尽快升级，现在最近是 4.5.0

好的，我之前就像升级来着，但是这是用的别人封装好了的，里面有一些依赖像

import { shapeBase } from '@antv/g6/lib/shape/shapeBase'
import Shape from '@antv/g6/lib/shape/shape'

等等这些在lib文件夹下面的引入在新版里面找不到呢。

**Comment by Yanyan-Wang** [comment]
类型引用升级参考：https://github.com/antvis/G6/issues/2525

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
