### ISSUE TITLE
Edge labe padding bug

### ISSUE THREAD

**Issue by YuancaiDing** [antvis/G6#3346]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/g6-reproduction-template-uvzdf?file=/src/index.js)

### Steps to reproduce
in core/src/element/edge.ts

 in this function getLabelBgStyleByPosition()
line 247:
    const style = {
      ...backgroundStyle,
      width: backgroundWidth,
      height: backgroundHeight,
      x: bbox.minX - padding[2],   <---- should be padding[1]
      y: bbox.minY - padding[0],
      rotate: 0,
    };

| Environment | Info |
|---|---|
| g6 | 4.5.0 |
| System | - |
| Browser | - |

**Comment by Yanyan-Wang** [comment]
I think it should be padding[3] ? since padding array means [padding-top, padding-right, padding-bottom, padding-left]

**Comment by YuancaiDing** [comment]
Agreed , should be  padding[3]

**Comment by YuancaiDing** [comment]
Just found same issue reported before: https://github.com/antvis/G6/issues/3274

**Comment by Yanyan-Wang** [comment]
thanks, will be fixed ASAP

**Comment by Yanyan-Wang** [comment]
fixed by v4.5.1
