### ISSUE TITLE
clone.ts Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by chinaxcy** [antvis/G6#3347]
在加入collapse-expand时发生该问题，初步断定应该和传入数据有关，用example的数据没问题，用自己的树形数据，渲染没问题，但是在collapse-expand时发生

**Comment by chinaxcy** [comment]
已经解决

**Comment by juncocoa** [comment]
怎么解决的，问题出在哪儿？我也遇到了

**Comment by chinaxcy** [comment]
> 怎么解决的，问题出在哪儿？我也遇到了

保证你的数据结构是纯净的，如官方那个样子
