### ISSUE TITLE
根据dva框架创建的项目无法解析G6的ES6语法

### ISSUE THREAD

**Issue by nsuedu** [antvis/g6#335]
./node_modules/@antv/g6/plugins/tool.minimap/index.js
Module parse failed: Unexpected token (18:6)
You may need an appropriate loader to handle this file type.
|         return graph;
|       },
|       ...this.options
|     });
|     graph.on('afterchange', () => {

**Comment by TomHuangCN** [comment]
```js
...this.options
```

应该是你的 loader 识别不了这种写法，改一下 babel 的配置

**Comment by oangy** [comment]
@nsuedu 遇到了同样的问题，请教下怎么解决的。

**Comment by nsuedu** [comment]
在 webpack 配置文件中加上一行   "  extraBabelIncludes: ["node_modules/@antv"],"

**Comment by nsuedu** [comment]
@oangy

**Comment by 475533819** [comment]
@nsuedu 
![image](https://user-images.githubusercontent.com/35600665/70609572-fdce6980-1c3c-11ea-830e-18d63fe0d145.png)
![image](https://user-images.githubusercontent.com/35600665/70609591-06bf3b00-1c3d-11ea-81bd-abedca0caa98.png)
我加了，但是不行哎

**Comment by nsuedu** [comment]
@475533819   看看这个:https://github.com/sorrycc/blog/issues/68
