### ISSUE TITLE
Tooltip支持动态Dom内容

### ISSUE THREAD

**Issue by cfool** [antvis/G6#3351]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
部分场景下，tooltip需要展示的内容是异步获取。在数据获取过程中，tooltip需要展示loading信息，并且在获取数据后变更为具体的提示信息。
具体到vue技术栈下，tooltip的内容有可能是一个组件的挂载元素。

### What does the proposed API look like?
对当前API无影响。 在tooltip的展示逻辑里进行支持。

**Comment by zhaochengxiang** [comment]
今天正在处理这个问题,我们可以通过下面的方式,自定义tooltip

const floatDOM = createDom(`
  <div id="test-dom" style="
      position: absolute; 
      border: 1px solid #e2e2e2;
      font-size: 12px;
      color: #545454;
      background-color: rgba(255,255,255,0.9);
      padding: 10px 8px;
      box-shadow: rag(174,174,174) 0px 0px 10px;
    "
  >
  </div>
`);


graph.on('node:mouseenter', function (e) {
    const item = e.item;
    const model = item.getModel();
    const { x, y } = model; // 获得该节点的位置，对应 pointX/pointY 坐标
    const canvasXY = graph.getCanvasByPoint(x, y);

    floatDOM.innerHTML = `${model.label}`;

    const zoom = graph.getZoom();

    floatDOM.style.left = `${canvasXY.x+(60*zoom)}px`;
    floatDOM.style.top = `${canvasXY.y+(40*zoom)}px`;
  });

**Comment by Yanyan-Wang** [comment]
related to https://github.com/antvis/G6/pull/3352

**Comment by Yanyan-Wang** [comment]
duplicated to https://github.com/antvis/G6/issues/3850
