### ISSUE TITLE
复杂自定义节点hover更改节点背景色

### ISSUE THREAD

**Issue by qq707631575** [antvis/G6#3353]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://.com](http://.com)

### Steps to reproduce
1

| Environment | Info |
|---|---|
| g6 | 4.0.0 |
| System | - |
| Browser | - |

---
鼠标移入，hover，更改节点背景色，不想修改自定义节点其他元素，也不想重新绘制这个节点，因为重新整个节点绘制如果有图片元素的话会闪一下，所以我只想要更新这个一定义节点的背景色。试过不重绘制图片元素，但是会覆盖它导致看不到原先的图片元素了。请问如何更新样式才可以？

**Comment by Yanyan-Wang** [comment]
https://g6.antv.vision/zh/docs/manual/advanced/state-new
