### ISSUE TITLE
registerEdge，自定义边，可以使用内置边，只修改颜色吗？

### ISSUE THREAD

**Issue by longflying** [antvis/G6#3354]
我要对树结构的线使用不同颜色，我如果自定义边的情况下就需要设置path，但是我只想使用默认的cubic-horizontal 边，只是想修改边的颜色，我应该如何设置？

**Comment by Yovven** [comment]
hello ，请问是怎么处理的呢，我也想使用默认的cubic-horizontal 边，然后边加个 icon
