### ISSUE TITLE
代码流程繁杂

### ISSUE THREAD

**Issue by 2012shenghua** [antvis/G6#3356]
学习你们官网代码是怎么部署的，我看修改site/examples需要npm run site:clean 之后再执行npm start 才能看到效果，可以直接保存能看到效果吗？

**Comment by Yanyan-Wang** [comment]
start 之后，修改site中的代码后保存，会热更新。但是因为页面比较多，会比较慢

**Comment by Yanyan-Wang** [comment]
最近我们迁移官网到 dumi，在 site 目录下 npm install 后 npm start 即可运行。欢迎试用
