### ISSUE TITLE
使用drag-node拖拽节点，tooltip位置如何能跟随一起改变

### ISSUE THREAD

**Issue by xiziliang** [antvis/G6#3357]

**Comment by xiziliang** [comment]
https://user-images.githubusercontent.com/54427136/145538769-4a2e6d40-fdef-4ab7-8b07-65716555edfd.mov

**Comment by xiziliang** [comment]
@Yanyan-Wang

**Comment by Yanyan-Wang** [comment]
内置设计的逻辑是拖拽的时候 tooltip 会隐藏的，因为认为拖拽过程中 tooltip 一直在的话会干扰交互。不知道你这个 tooltip 是怎么写的呢？

**Comment by xiziliang** [comment]
我就是正常写的，使用的内置的Behavior

```
{
      type: 'tooltip',
      formatText: this.getTooltip as any,
      offset: 40,
      shouldBegin: (e) => {
        const name = e.target.get('name');
        return !['collapsed-text-rect','collapsed-icon-rect'].includes(name);
      },
}
```

**Comment by damnright** [comment]
可以不同tooltip ，然后tip写到节点本身里 ，绑定事件触发后显示节点的tip元素即可

**Comment by Yanyan-Wang** [comment]
> 我就是正常写的，使用的内置的Behavior
> 
> ```
> {
>       type: 'tooltip',
>       formatText: this.getTooltip as any,
>       offset: 40,
>       shouldBegin: (e) => {
>         const name = e.target.get('name');
>         return !['collapsed-text-rect','collapsed-icon-rect'].includes(name);
>       },
> }
> ```

看下官网上的拖拽是会隐藏的。如果你的不会，请提供一下版本号，以及在线复现 demo

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
