### ISSUE TITLE
发现一个bug，空combo的children为undefined

### ISSUE THREAD

**Issue by damnright** [antvis/G6#3358]
画布新建一个空的combo，combo的children为空数组，然后调用graph.save()导出数据，再用graph.changeData()或graph.read()加载数据，combo的children变为undefined

**Comment by damnright** [comment]
还有，通过代码给combo添加子节点：
e.item.addChild(dragItem);
              graph.updateComboTree(dragItem.get('id'), e.item.get('id'));
              graph.updateCombos();
有时combo的children不会更新，有时会更新，只能调用graph.changeData(graph.save())才能恢复正常

**Comment by damnright** [comment]
新创建的combo children是不更新的，创建后调用graph.changeData(graph.save())，children才会正常更新

**Comment by damnright** [comment]
新增的第一个combo是正常的  第二个就开始异常了  combo的children属性不会变

**Comment by Yanyan-Wang** [comment]
创建一个空 combo ，children 为空数组，是自己指定的？children 是内部生成的，自己指定没用

**Comment by damnright** [comment]
> 

自己指定或者内部生成，children都是undefined

**Comment by Yanyan-Wang** [comment]
children 不是用户指定的，所以按理说用户应该不用在意它是空数组还是 undefined

**Comment by damnright** [comment]
> 

这里有没有办法通过combo的model的一个属性去获取combo的子节点

**Comment by Yanyan-Wang** [comment]
combo.getChildren() 可以获取到它的子节点和子 combo。这里的 combo 是 item

**Comment by SterbenJ** [comment]
这个问题我也遇到了。
新建的 combo 中 `children` 会随着加入子节点改变，但是导入的 combo 不会，这样行为不一致很容易造成隐性的问题。
比如我们这边有个场景需要调用 graph.save() 来获得所有数据与服务端交互，其中 combo 需要读取其 `children` 把子节点的部分信息发送给服务端，开发时发现偶尔会出现子节点数据丢失的问题，debug 好久才发现是这个原因🤣...

**Comment by Yanyan-Wang** [comment]
因为 combo 数据不是设计为一个 children 嵌套的形式，G6 的 GraphData 数据格式中，只通过节点的 comboId，combo 的 parentId 来指定父 combo。所以不建议用户去使用内部生成的 children 属性。后面 G6 也会逐步完成数据隔离～

**Comment by J-Django-Github** [comment]
我也遇到了这样的问题，自定义编辑好一个G6图后保存到数据库，获取的数据用graph.read()去调用展示，combo的children就变成了undefined，目前没找到解决办法。。。听上述意思combo的children是内部自动生成不建议用户去设置，但是我后面给graph.read()赋值的时候，我怎么去指定combo的的子节点有哪些呢？
