### ISSUE TITLE
How to align collapsed combos?

### ISSUE THREAD

**Issue by mostopalove** [antvis/G6#3359]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/mostopalove/pen/XWejaLL](https://codepen.io/mostopalove/pen/XWejaLL)

### Steps to reproduce
Case 1:
1) just open the example by link
2) try to collapse and un-collapse the combos by clicking on "+" button
result : They are disordered.

When closing and opening combos, they are arranged in a chaotic order.
It is necessary to set their alignment to the top left corner (in my case).

<img width="525" alt="Снимок экрана 2021-12-12 в 22 21 57" src="https://user-images.githubusercontent.com/49098339/145728249-d16a6254-fb8d-4871-ab03-08c9b26aa79c.png">

<img width="525" alt="Снимок экрана 2021-12-12 в 22 21 57" src="https://user-images.githubusercontent.com/49098339/145728329-7634928b-c213-4800-9281-e62f668ef839.png">

| Environment | Info |
|---|---|
| g6 | 4.2.7 |
| System | MacOS |
| Browser | latest |

---
Please provide a working example based on my code that's in the example.

**Comment by mostopalove** [comment]
The first case easy to fix. If you need drag canvas by clicking on the some element you can use allowDragOnItem flag
https://g6.antv.vision/en/docs/manual/middle/states/defaultBehavior#drag-canvas

The second case is still actual.
When closing and opening combos, they are arranged in a chaotic order.
It is necessary to set their alignment to the left (in my case).

**Comment by mostopalove** [comment]
@Yanyan-Wang is there some sort of combo sorting mechanism?

**Comment by Yanyan-Wang** [comment]
G6 layout the combo graph with the uncollapsed data by default. And you could call graph.layout after render to re-layout the collapsed combos to achieve the goal:

```
graph.on('afterrender', e => {
  graph.layout()
})  
```

P.S. bind the listener before `graph.render`
