### ISSUE TITLE
使用iconfont 拖动之后会导致画布变脏

### ISSUE THREAD

**Issue by luokerenGIT** [antvis/G6#3360]
![image](https://user-images.githubusercontent.com/53746488/145662033-8614f106-e251-41b4-844d-5fdb28c2020f.png)
这个问题有解决的办法吗？

**Comment by luokerenGIT** [comment]
急求解决办法

**Comment by Yanyan-Wang** [comment]
一般原因是图形中有非法的属性。可以提供下复现在线 demo。或者简单粗暴的方法是给节点增加一个比这个 iconfont 稍为大一点点的 rect 在其后面

**Comment by zmbxy95** [comment]
> 一般原因是图形中有非法的属性。

问一下，这里面的非法属性是指的未定义的一些属性吗？

**Comment by luokerenGIT** [comment]
> 一般原因是图形中有非法的属性。可以提供下复现在线 demo。或者简单粗暴的方法是给节点增加一个比这个 iconfont 稍为大一点点的 rect 在其后面

我在初始化之后加了个2秒的延时，重新render了一次就好了。关于这块还是希望有机会优化下
你说的这个加非法属性确实也会导致，之前遇到过，例如size:80写成了size[40,40]会导致画布脏了。
感谢
