### ISSUE TITLE
官网实例，若一次性生成的节点较多，控制台一直打印 [Violation] 'setInterval' handler took <N>ms

### ISSUE THREAD

**Issue by AmieJing** [antvis/G6#3366]
官网实例，一次性生成的节点较多，控制台一直打印 [Violation] 'setInterval' handler took <N>ms 和[Violation] 'requestAnimationFrame' handler took <N>ms
![image](https://user-images.githubusercontent.com/37952540/145790321-acc14cd1-3415-4651-96ea-288d5b6c8a6f.png)

**Comment by Yanyan-Wang** [comment]
请提供在线复现 demo

**Comment by AmieJing** [comment]
https://codesandbox.io/s/vibrant-mendeleev-6ixgo?file=/src/components/HelloWorld.vue
![image](https://user-images.githubusercontent.com/37952540/146140097-3a74b060-be14-463b-9dc5-e56d28a60020.png)

**Comment by Yanyan-Wang** [comment]
https://stackoverflow.com/questions/42218699/chrome-violation-violation-handler-took-83ms-of-runtime/44824402#44824402

应该不影响运行，只是优化提示。在较早期的 chrome 中才会出现。

**Comment by AmieJing** [comment]
确实不影响运行，不应该是Chrome版本问题，我查了浏览器是最新版本
![image](https://user-images.githubusercontent.com/37952540/146331335-c8994bcd-771d-4d16-a89c-8431e60cc935.png)

**Comment by CodingJzy** [comment]
这个会造成页面卡顿，即使我离开了这个页面

**Comment by CodingJzy** [comment]
请问怎么解决

**Comment by xc741852963** [comment]
如果我想有一个10w+的数据量级 请问使用哪个api
