### ISSUE TITLE
Combo overlaps after collapsing using 'dagre' layout.

### ISSUE THREAD

**Issue by mostopalove** [antvis/G6#3367]
- [ ] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/mostopalove/pen/OJxbYXg](https://codepen.io/mostopalove/pen/OJxbYXg)

### Steps to reproduce
1. collapse "Combo 1" by double click
Result: Combo overlapped.

| Environment | Info |
|---|---|
| g6 | 4.3.11 |
| System | MacOS 11.6 |
| Browser | Chrome 96.0.4664.93 |

<img width="622" alt="Снимок экрана 2021-12-13 в 18 02 25" src="https://user-images.githubusercontent.com/49098339/145846061-51ca9110-1729-43ae-af16-2631a7f25628.png">
<img width="638" alt="Снимок экрана 2021-12-13 в 18 02 34" src="https://user-images.githubusercontent.com/49098339/145846084-623b8404-7969-4aa3-bc33-409049689d01.png">

**Comment by Yanyan-Wang** [comment]
solved by v4.7.15
