### ISSUE TITLE
G6 2.0是不是取消了beginAdd方法？？

### ISSUE THREAD

**Issue by zx8887** [antvis/g6#337]
* **G6 Version**:2.0
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:
1.x中net中有一个很方便的方法，beginAdd，但是2.0中看了下源码和api都没有。。难道要自己实现？
还有，统一布局插件是否还存在。

**Comment by ZOEWANGCHINA** [comment]
换成add了

**Comment by ZOEWANGCHINA** [comment]
我看了一下，拖动节点的边来缩放节点大小这种的，真的要自己实现了。你有找到吗？

**Comment by zx8887** [comment]
@ZOEWANGCHINA 感觉迁移代码好多工作量，之前的很多现成的方法没了。而且2.0是基于ES7。。目前遇见各种问题，昨天半业余前端的我来说，有点痛苦。。。
