### ISSUE TITLE
4.5.1 版本升级导致低版本浏览器报错 n.flat is not a function

### ISSUE THREAD

**Issue by webmrxu** [antvis/G6#3379]
### 描述问题

原因：由于在package.json 中使用 ^  ，版本自动升级到4.5.1 ，导致tree 图展示异常，造成这个的原因是4.5.1版本中使用了flat，没有写兼容性代码导致低版本浏览器报错。 具体的你们可以搜索 "n.flat"  这个关键词找到对应的代码。

也是找了好久才发现为什么前天还好好的版本今天就不行了。抱歉由于是内部项目，无法截图，不能描述更多细节。

ps：感谢G6团队的贡献和开源。

### 您的示例网站或应用程序

无

### 列出如何重现错误的步骤

找个低版本浏览器，生成tree图，大概在低于 chrome 68版本，不支持flat的浏览器就会有问题。

### 预期行为

tree 图展示正常

### 平台

- 操作系统： [Windows]
- 网页浏览器: [Google Chrome]
- 版本: [低于68版本的chrome ]

**Comment by Yanyan-Wang** [comment]
是 @antv/layout 包中使用了 flat，已经兼容，重新安装一下即可
