### ISSUE TITLE
changeData 导致图片节点不显示

### ISSUE THREAD

**Issue by cagen** [antvis/G6#3382]
### 描述问题

使用 graph.changeData 方法，会导致 data 中的同一图片不显示

### 您的示例网站或应用程序

https://codesandbox.io/s/fp42g

### 列出如何重现错误的步骤

该例子改造自 example
1. 点击任意节点，触发 click 事件
2. 发现图片消失

### 预期行为

期望图片仍旧显示

### 屏幕截图或视频
<img width="455" alt="image" src="https://user-images.githubusercontent.com/5174809/146770803-1a3102e5-a95c-4ccf-8f10-a56768239a8e.png">

### 平台

- 操作系统： [macOS]
- 网页浏览器: [Google Chrome]
- 版本: [96.0.4664.110]

### 其他背景

之前使用 4.3.3 并没有此问题，升级到 4.5.0 以上出现此问题

**Comment by lyl2019** [comment]
真实数据渲染前，先置空graph数据，graph.changeData({
  nodes: [],
  edges: []
})

**Comment by Yanyan-Wang** [comment]
当前版本已不存在上述问题，目前最新版本 4.7.15
