### ISSUE TITLE
chrome中 拖动minimap出现绿色加号

### ISSUE THREAD

**Issue by xiaoxigua-web** [antvis/G6#3383]
### Describe the bug

![image](https://user-images.githubusercontent.com/24602445/146856193-7a4b8584-2945-4a7e-88ab-c04625611726.png)

### Your Example Website or App

https://g6.antv.vision/zh/examples/tool/minimap#minimap

### Steps to Reproduce the Bug or Issue

按住鼠标拖动

### Expected behavior

希望不要出现加号

### Platform

系统：macOS Mojave 10.14.6 
chrome 版本  96.0.4664.110
Version: 4.5.1

**Comment by Yanyan-Wang** [comment]
请升级版本以解决问题～
