### ISSUE TITLE
changeData导致'create-edge'报错

### ISSUE THREAD

**Issue by luokerenGIT** [antvis/G6#3384]
### Describe the bug

使用'create-edge'modes,点击第一个节点，拖出线条还没有连接其他节点的时候，定时器刷新调用changeData方法，图会报错，后面其他操作也会异常
![image](https://user-images.githubusercontent.com/53746488/146864293-b8bdb1b3-ec11-4c58-b4de-d0e310b6648b.png)

### Your Example Website or App

https://g6.antv.vision/zh/examples/interaction/createEdge#click-link-point

### Steps to Reproduce the Bug or Issue

使用'create-edge'modes,点击第一个节点，拖出线条还没有连接其他节点的时候，定时器刷新调用changeData方法，图会报错，后面其他操作也会异常
![image](https://user-images.githubusercontent.com/53746488/146864293-b8bdb1b3-ec11-4c58-b4de-d0e310b6648b.png)

### Expected behavior

期望不报错，不影响后续操作。

### Platform

Chrome

**Comment by Yanyan-Wang** [comment]
暂时可通过调用 changeData 之前先删除被创建出来的这条边。create-edge behavior 配置 edgeConfig 或 getEdgeConfig 给新建边设置 id，通过 graph.findById 找到这条边，graph.removeItem 删除

**Comment by luokerenGIT** [comment]
> 暂时可通过调用 changeData 之前先删除被创建出来的这条边。create-edge behavior 配置 edgeConfig 或 getEdgeConfig 给新建边设置 id，通过 graph.findById 找到这条边，graph.removeItem 删除

首页感谢积极的回答，但是删除之后还是同样的错误
也确定通过id拿到了这个edge，remove之后，这个edge也被销毁了，但是还是包同样的错误
![image](https://user-images.githubusercontent.com/53746488/147043874-765f8863-ed13-4d4e-949a-3991c24d2e8c.png)

![image](https://user-images.githubusercontent.com/53746488/147043757-ad9c7856-f2b3-4439-bf28-ee4cc16f4b20.png)
![image](https://user-images.githubusercontent.com/53746488/147043790-42c10790-6eb8-420c-b0bb-6adb749b8aaf.png)

**Comment by Yanyan-Wang** [comment]
v4.5.2 已修复

**Comment by luokerenGIT** [comment]
> v4.5.2 已修复

收到，感谢，👍👍👍👍👍👍
