### ISSUE TITLE
文本对齐方式和配置项不一致

### ISSUE THREAD

**Issue by kaipengHan** [antvis/G6#3388]
## 节点的文本样式属性
1. textAlign：设置为left，文本到右边； 设置为right，文本到左边；设置top和bottom也是相反；而且文本会超出节点；
2. textBaseline： 设置为top，是bottom的效果；设置为bottom，是top的效果；
3. lineHeight：设置不生效

*以上属性单独设个和组合设置都会产生同样的效果*

### 您的示例网站或应用程序

https://codesandbox.io/s/priceless-mcnulty-ykqmq?file=/src/App.js

### 列出如何重现错误的步骤

1. React中使用G6;
2. 设置节点的文本配置项中的标签样式如下属性
3. `textAlign:'right',textBaseLine:'top',lineHeight:100`

### 预期行为

期望看到：节点中的文本应该右上的位置
实际看到：节点中的文本实际在左下的位置，行高没生效，文字超出节点

### 屏幕截图或视频

![image](https://user-images.githubusercontent.com/49121336/146910616-a91aec21-8dc5-46a0-84a8-9d36cf6f5d08.png)
![image](https://user-images.githubusercontent.com/49121336/146910672-1912efe3-7c0c-403a-94fa-4ca2a3691ef6.png)

### 平台

- 操作系统： [Windows]
- 网页浏览器: [Google Chrome]
- 版本: [react:16.8.6  @antv/g6:4.5.1 ]

**Comment by Yanyan-Wang** [comment]
这个 textAlign 是指文本对其到它图形指定的 d y 的方式，内置 rect 节点中的文本 x y 在节点中心，所以 textAlign: 'right' 的话，这个文本的右侧对其到节点中心。其他都是同理
