### ISSUE TITLE
TreeGraph changeData之后左边偏移，动画重复执行

### ISSUE THREAD

**Issue by luokerenGIT** [antvis/G6#3390]
### Describe the bug

![image](https://user-images.githubusercontent.com/53746488/147054547-0c8cecc3-c0df-4c9a-ba4e-300d9fba0376.png)

1.每次changeData之后动画都再执行一次
2.拖动画布之后，再changeData，图会回到初始的中心点，在官方文档看getGraphCenterPoint可以获取中心点，但是没找到设置中心点的方法，如果可以设置，手动设置中心点应该可以解决这个问题

### Your Example Website or App

https://g6.antv.vision/zh/examples/tree/dendrogram#basicDendrogram

### Steps to Reproduce the Bug or Issue

![image](https://user-images.githubusercontent.com/53746488/147054547-0c8cecc3-c0df-4c9a-ba4e-300d9fba0376.png)

1.每次changeData之后动画都再执行一次
2.拖动画布之后，再changeData，图会回到初始的中心点，在官方文档看getGraphCenterPoint可以获取中心点，但是没找到设置中心点的方法，如果可以设置，手动设置中心点应该可以解决这个问题

### Expected behavior

期望动画只在初始化的时候执行
拖动画布在changgedata中心点不变，或者有手动设置的api

### Platform

Chrome

**Comment by Yanyan-Wang** [comment]
在 changeData 之前可以获取一下图内容左上角坐标 
const bbox = graph.getGroup().getCanvasBBox()
const leftTop = {
  x: bbox.minX,
  y: bbox.minY
}

然后在 changeData 之后使用 graph.moveTo，把图移到 leftTop 位置上

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
