### ISSUE TITLE
A layout's presets are ignored by .changeData()

### ISSUE THREAD

**Issue by steveHornseyDeveloper** [antvis/G6#3392]
### Describe the bug

I am struggling to add nodes to a DAGRE graph without reseting the positions of all nodes on the graph. I have tried adding the nodes with both .addItem() and .changeData(). When changeData is used all nodes moved by the user get reverted back to the initial positions determined by the DAGRE layout even when presets is set on the layout

### Your Example Website or App

https://stackblitz.com/edit/react-hkcunr-szq8dg

### Steps to Reproduce the Bug or Issue

1. go to https://stackblitz.com/edit/react-hkcunr-szq8dg
2. Move node 1
3. Wait 5000ms for timeout to occur

### Expected behavior

I expect the new nodes to be added to the graph, and the node that I moved to still be in the same location pre the new nodes being added

### Screenshots or Videos

https://user-images.githubusercontent.com/21181628/147128727-b3919145-7bbe-48f5-9ec0-0e8d7b31cf1d.mov

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

If there is a way of adding nodes to a graph without resetting the position of all other nodes in the graph then please let me know!

Thank you

**Comment by Yanyan-Wang** [comment]
The preset in the dagre is used for keeping the relative positions between nodes in levels. If you wanna keep the node position moved by the user, maybe record the position and restore by graph.updateItem('0', {x, y}) after changeData or afterLayout

**Comment by steveHornseyDeveloper** [comment]
Great, thank you for getting back to me. We've made the decision to add some custom node positioning logic which respects user moved nodes rather than using a g6 layout
