### ISSUE TITLE
labelCfg的autoRotate值为false时，padding值不生效

### ISSUE THREAD

**Issue by Leuchy** [antvis/G6#3397]
### 问题描述

labelCfg的autoRotate值为false时，padding值不生效
详见复现步骤

### 重现链接

https://g6.antv.vision/zh/examples/item/labelBg#edgeBg

### 重现步骤

1. 将demo中的autoRotate改为false

实际结果：
label上的文字并未居中，设置的padding值被忽略

### 预期行为

label上的文字居中显示

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
当前版本已不存在上述问题～
