### ISSUE TITLE
2.0的锚点问题

### ISSUE THREAD

**Issue by zx8887** [antvis/g6#340]
* **G6 Version**: 2.0
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

1.x的锚点是可以显示的，而且可以改变其样式，下面是1.x的代码
![image](https://user-images.githubusercontent.com/13731281/41885726-d21111ea-792b-11e8-9d57-75e9920a35d0.png)

2.0设置了锚点，然后找了下api和看了下源码，没有显示锚点的相关操作，请问是否取消显示锚点及设置锚点样式的功能了？如果需要自定义显示，能否实现

**Comment by shengbeiniao** [comment]
同问，在g6-editor中有anchor的监听事件，但G6没有，只有node、edge等

**Comment by shengbeiniao** [comment]
楼主，我实现了anchor的展示、隐藏，详见
https://github.com/antvis/g6/issues/326

**Comment by zx8887** [comment]
@shengbeiniao 谢兄弟。。但是现在项目进度问题，暂时取消研究2.0了。代码迁移太难了。。后续等2.0完善了再来弄。你们先上。

**Comment by shengbeiniao** [comment]
@zx8887 我也放弃2.0了，目前2.0也就只能画画图，做编辑没啥希望

**Comment by zx8887** [comment]
@shengbeiniao 1.x的我该试的功能基本上都试了。有问题可以找我哈。相互交流交流。。

**Comment by shengbeiniao** [comment]
@zx8887 哥们，微信发你邮箱了
