### ISSUE TITLE
设置了activate-relations，edgeLabel包含background的时候，拖动节点，background位置错乱

### ISSUE THREAD

**Issue by isee15** [antvis/G6#3400]
### 问题描述

<img width="497" alt="bug" src="https://user-images.githubusercontent.com/10377426/147211382-fd131e16-81e6-4eac-947a-ae04a5e373c0.png">

### 重现链接

https://codesandbox.io/s/v055g?file=/index.js

### 重现步骤

1. https://codesandbox.io/s/v055g?file=/index.js 
2. 拖拽一下node

### 预期行为

期望edgelabel的background能正确刷新

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.5.0]

**Comment by Yanyan-Wang** [comment]
v4.5.2 已修复
