### ISSUE TITLE
'compactBox' does not exist! Please specify it first.

### ISSUE THREAD

**Issue by hackftz** [antvis/G6#3401]
### 问题描述

https://g6.antv.vision/zh/examples/tree/customItemTree#customEdgeTree

the demo i used in react frame, but got this error info, please check it and repair it, ok?

### 重现链接

https://g6.antv.vision/zh/examples/tree/customItemTree#customEdgeTree

### 重现步骤

just copy the code in the demo in ant react frame project

### 预期行为

repair it

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]
mac

**Comment by Yanyan-Wang** [comment]
你是不是没安装完整依赖，或者把 compactBox 布局用在了 Graph 上而不是 TreeGraph

**Comment by hackftz** [comment]
👌
