### ISSUE TITLE
树图数据结构能否用最短路径算法

### ISSUE THREAD

**Issue by tuhongwei** [antvis/G6#3405]
### 问题描述

我的树图的数据结构是这种：
{
 'category': 'A',
  'tooltip': '',
  'description': '',
  'label': '...',
  'name': '...',
  'parent': '0',
  'id': '1',
  'children': []
}
有什么办法用算法中的最短路径算法吗

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
G6.Algorithm.findShortestPath 可以寻找 graph 数据结构的最短路径，可以将树图数据转换为一般图数据之后，使用这个算法。

treeGraph.getNodes().map(node => node.getModel())
treeGraph.getEdges().map(edge => edge.getModel())
可以得到点边数据集
