### ISSUE TITLE
官方示例：Dagre流程布局在CodeSandBox中打开报错

### ISSUE THREAD

**Issue by CocoChen917** [antvis/G6#3406]
### Describe the bug

官网页面： https://g6.antv.vision/zh/examples/net/dagreFlow#dagreCombo
外链codeSandBox报错页面: https://codesandbox.io/s/1ezg7?file=/index.js:2293-2304（点击Enable sortByCombo按钮）

### Your Example Website or App

 https://codesandbox.io/s/1ezg7?file=/index.js:2293-2304

### Steps to Reproduce the Bug or Issue

 https://codesandbox.io/s/1ezg7?file=/index.js:2293-2304 点击Enable sortByCombo按钮

### Expected behavior

和官网示例一样的behavior

### Platform

Browser： Chrome

**Comment by ydylh** [comment]
I have the same problem as you, you can try @antv/g6@4.0.3

**Comment by CocoChen917** [comment]
> I have the same problem as you, you can try @antv/g6@4.0.3

4.0.3 still have problem ( because of "sortByCombo" I guess ),thanks anyway

**Comment by Yanyan-Wang** [comment]
fixed, upgrade @antv/layout to v0.1.31 pls
