### ISSUE TITLE
我用最新的create-react-app创建了一个Ts的模板项目，仅仅是引入G6，终端就报了非常多的error，但是项目能运行

### ISSUE THREAD

**Issue by moderateMan** [antvis/G6#3407]
### Describe the bug

我用最新的create-react-app创建了一个Ts的模板项目，仅仅是引入G6，终端就报了115的error，但是项目能运行

### Your Example Website or App

nothing

### Steps to Reproduce the Bug or Issue

1. npx create-react-app demo--template typescript
2. yarn add @antv/g6
3. 引入

### Expected behavior

期望的结果是不要在终端爆密密麻麻的错

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/85022930/147384818-d01a75c6-d866-42af-9aed-74c3fbb1680d.png)

### Platform

- OS: [Windows,]
- Browser: Chrome]
- Version: [96.0.4664.110]

**Comment by Yanyan-Wang** [comment]
这不是 error，是 warning。可能是配置原因导致找不到 G6 其他依赖的 sourcemap，如果你不想让它们出现在你的终端中，参考这个 vscode 的配置方法：https://github.com/microsoft/vscode/issues/102042#issuecomment-656402933

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
