### ISSUE TITLE
设置transform:scale()样式之后节点的事件无法触发

### ISSUE THREAD

**Issue by kaipengHan** [antvis/G6#3412]
### 问题描述

给父级元素设置transform:scale(1.1)样式之后，每个节点的部分区域无法触发绑定的事件

### 重现链接

https://codesandbox.io/s/antv-g6-transform-7t2vw?file=/src/App.js

### 重现步骤

1. 给包裹canvas任意父级元素设置transform:scale(1.2)样式
2. 分别点击节点左边部分和右边部分
3. 左边部分和左边框外的一部分（和设置scale的值有关系）可以触发事件，右边部分不能

### 预期行为

当设置的缩放之后，节点的触发事件的位置应该跟随节点本身

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.4.1, 4.5.1]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/49121336/147730321-e5457cca-49f9-447d-a8e0-f963678dba3b.png)
红色区域可触发事件，蓝色区域不可触发事件

**Comment by Yanyan-Wang** [comment]
暂时还没有找到解决方案，建议如果需要缩放画布，使用 graph.zoomTo 或 graph.zoom

**Comment by Yanyan-Wang** [comment]
通过配置 graph.get('canvas').set('supportCSSTransform', true) 可以解决
