### ISSUE TITLE
hull disfunction after  timebar enabled

### ISSUE THREAD

**Issue by a1947z** [antvis/G6#3417]
### Describe the bug

Hull is working in below code. 
But if we import timebar by adding "plugins: [timebar]" in  G6.Graph definition , the hull will be disfunction.

### Your Example Website or App

https://codesandbox.io/s/timebar-hull-issue-in-g6-npft6?file=/index.js

### Steps to Reproduce the Bug or Issue

1. visit the cdoe in https://codesandbox.io/s/timebar-hull-issue-in-g6-npft6?file=/index.js
2. the hull is working 
3. Un-comment //plugins: [timebar] in line 84
4. Timebar showed but the hull is gone

### Expected behavior

As a user, I expect to see hull even after timebar enabled

### Platform

- OS: [Windows]
- Browser: [Chrome]
- Version: [96.0.4664.110]

**Comment by Yanyan-Wang** [comment]
find the centerNodes inside the 'afterlayout', and when the layout is done, the hull will show up.

`let centerNodes = graph.getNodes().filter((node) => node.getModel().value < 30);`

that is because  some of the centerNodes are filtered out by the timebar if you call it before 'afterlayout', and the hull cannot find them.

**Comment by a1947z** [comment]
thanks, it is fixed

**Comment by a1947z** [comment]
It is partly fixed to move hull members definition according to event "afterlayout" but a new issue coming:
1) success: the hull can be showed together with timebar
2) failed: the hull can not dynamically change with node moving

To fixe 2) , I added hull1.updateData for event "afterupdateitem" as  below code showed: 
```
graph.on("afterlayout", () => {
  let centerNodes = graph
    .getNodes()
    .filter((node) => node.getModel().value < 30);
  const hull1 = graph.createHull({
    id: "centerNode-hull",
    type: "bubble",
    members: centerNodes,
    padding: 10
  });
  graph.on("afterupdateitem", (e) => {
    hull1.updateData(hull1.members);
  });
});
```
### Steps to Reproduce the new issues

1. I forked a new v2 show this new issue, please visit the code in https://codesandbox.io/s/timebar-hull-issue-in-g6-v2-hdnef
2. moving one of the node in hull, the hull can be auto-fiting according the node change
3. Un-comment //plugins: [timebar] in line 84
4. Timebar showed but the hull is gone. An exception showed if I change the time bar:
```
TypeError
Cannot read properties of null (reading 'remove')
    at Hull.updateData (https://npft6.csb.app/node_modules/
antv/g6-core/es/item/hull.js:151:33
Graph.eval
/index.js:115:10
  112 |     padding: 10
  113 |   });
  114 |   graph.on("afterupdateitem", (e) => {
> 115 |     hull1.updateData(hull1.members);
      |          ^
  116 |   });
  117 | });
  118 | 
```

**Comment by a1947z** [comment]
fixed this issue after I reading a similar resoluton report from https://github.com/antvis/G6/issues/3022 


```
graph.on("afterlayout", () => {
  let centerNodes = graph
    .getNodes()
    .filter((node) => node.getModel().value < 30);
  const hull1 = graph.createHull({
    id: "centerNode-hull",
    type: "bubble",
    members: centerNodes,
    padding: 10
  });
  graph.on("afterupdateitem", (e) => {
    const hulls = graph.getHulls();
        hulls && Object.keys(hulls).forEach(hullKey => {
          const hull = hulls[hullKey]
          hull.updateData(hull.members);
        })
  });
});
```
