### ISSUE TITLE
toolbar视图控制器中怎么显示缩放比例，我看介绍中有，但是没有详细文档

### ISSUE THREAD

**Issue by huyanhu6261** [antvis/G6#3418]
### 问题描述

toolbar视图控制器中怎么显示缩放比例，我看介绍中有，但是没有详细文档

### 重现链接

https://codesandbox.io/s/dark-hill-r16yv?file=/index.html

### 重现步骤

toolbar视图控制器中怎么显示缩放比例，我看介绍中有，但是没有详细文档

### 预期行为

toolbar视图控制器中怎么显示缩放比例，我看介绍中有，但是没有详细文档

### 平台

toolbar视图控制器中怎么显示缩放比例，我看介绍中有，但是没有详细文档

**Comment by Yanyan-Wang** [comment]
内置的 toolbar 没有现实缩放比例，可以自己根据 graph.getZoom() 返回值写上

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
