### ISSUE TITLE
图形shape及其属性的文档错误（rect）

### ISSUE THREAD

**Issue by jingjingsu1** [antvis/G6#3422]
### 问题描述

文档地址: 
https://g6.antv.vision/zh/docs/manual/middle/elements/shape/shape-and-properties/#%E7%9F%A9%E5%BD%A2%E5%9B%BE%E5%BD%A2-rect

rect 的 X和Y应该是矩形中心的位置坐标吧
https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/defaultNode　节点总览有进行说明是中心位置

### 重现链接

https://g6.antv.vision/zh/docs/manual/middle/elements/shape/shape-and-properties/#%E7%9F%A9%E5%BD%A2%E5%9B%BE%E5%BD%A2-rect

### 重现步骤

１.　打开Ｇ６的文档
２.　搜索ｒｅｃｔ　查看配置项

### 预期行为

文档应该是正确的才对

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
和 circle 不同，rect 的 x y 是左上角坐标

**Comment by Yanyan-Wang** [comment]
节点 x y 是中心坐标，原因是 rect 类型的节点在内置实现的时候把 rect 图形的 x y 设置为了 x: -width / 2, y: -height/2
