### ISSUE TITLE
vite环境下typescript严格打包出现getUpdateType类型错误bug

### ISSUE THREAD

**Issue by XiaoDaiGua-Ray** [antvis/G6#3423]
### Describe the bug

vite环境下typescript严格打包出现getUpdateType类型错误bug
提示错误：node_modules/@antv/g6-core/lib/item/node.d.ts:68:5 - error TS2416: Property 'getUpdateType' in type 'Node' is not assignable to the same property in base type 'INode'.

### Your Example Website or App

https : //stackoverflow.com/help/mcve/zanwu

### Steps to Reproduce the Bug or Issue

vite环境typescript严格模式下打包出现此问题

### Expected behavior

<img width="1147" alt="WeChat10278f3f51d4adc9c9a1ed71a869f26c" src="https://user-images.githubusercontent.com/51957438/148201759-e9ad48a6-a098-4b9f-ac5b-6d9607ec34a7.png">

### Screenshots or Videos

<img width="1147" alt="WeChat10278f3f51d4adc9c9a1ed71a869f26c" src="https://user-images.githubusercontent.com/51957438/148201650-62d07dc5-ae7d-4fe4-b47a-5f21fc202a80.png">

### Platform

macOS
vite：2.4.3

**Comment by Yanyan-Wang** [comment]
收到，下个小版本修复

**Comment by Yanyan-Wang** [comment]
v4.5.2 已修复
