### ISSUE TITLE
Incorrect complex fruchterman layout rendering when GPU accelerated

### ISSUE THREAD

**Issue by AgustinBanchio** [antvis/G6#3424]
### Describe the bug

When a Fruchterman layout graph has complex data and is GPU accelerated, the layout is incorrectly rendered.

Sometimes it doesn't show at all and you need to pan and scroll around to see it, and it's all squashed in a diagonal line. See attached screenshot.

This can be replicated with the GPU layout example for complex data.

It doesn't happen on every machine. It runs correctly on other Windows PCs or on a MacBook.

My guess is that it has to do with the actual Graphics Adapter or driver? Nvidia Drivers on Windows?

Tried on different browsers, with no extensions or add-ons, tried replacing direct x with open GL and the issue still persisted.

### Your Example Website or App

https://g6.antv.vision/en/examples/net/gpuLayout#fruchtermanComplexData

### Steps to Reproduce the Bug or Issue

Go to https://g6.antv.vision/en/examples/net/gpuLayout#fruchtermanComplexData.
See the rendered layout.

### Expected behavior

The layout should be rendered correctly and not squashed

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/19520160/148232730-931eef3e-91e1-4ad8-b2d3-af6535bb094c.png)

### Platform

- OS: Windows 10
- Browser: Chrome (Edge and Firefox also have the same issue.)
- Version: 97.0.4692.71
- GPU: Nvidia GeForce 3090 with latest windows 10 drivers

### Additional context

Maybe someone with a similar graphics card and setup can try to reproduce and find the issue.

We are having the same issues with M1 and M1Pro MacBooks

**Comment by xiaoiver** [comment]
I rewrote it with WebGPU which has native support for compute shader, can you reproduce this bug?
https://antv-g-next.gitee.io/zh/examples/gpgpu#fruchterman

I guess this bug caused by WebGL textures on your device.

**Comment by BinX-Suse** [comment]
We have same issue while using it on Linux, M1 Mac, and some Windows.

**Comment by AgustinBanchio** [comment]
Hi, in the link you sent I'm seeing the following (with the same machine that had the issues):
![image](https://user-images.githubusercontent.com/19520160/153265848-ef560a3f-abf0-453d-b20f-b3a939f68eb9.png)

Is that what I'm supposed to be seeing?
The graph looks like just blue lines.

**Comment by xiaoiver** [comment]
> Hi, in the link you sent I'm seeing the following (with the same machine that had the issues): ![image](https://user-images.githubusercontent.com/19520160/153265848-ef560a3f-abf0-453d-b20f-b3a939f68eb9.png)
> 
> Is that what I'm supposed to be seeing? The graph looks like just blue lines.

It seems that all the nodes are not rendered correctly.

**Comment by AgustinBanchio** [comment]
It looks like the only problem is the layout calculation, not the actual rendering.

Is this being looked at?

To avoid the issue we are forced to use `gpuEnabled: false` when creating the graph. But for fruchterman it's really slow. 

> I rewrote it with WebGPU which has native support for compute shader, can you reproduce this bug? [antv-g-next.gitee.io/zh/examples/gpgpu#fruchterman](https://antv-g-next.gitee.io/zh/examples/gpgpu#fruchterman)
> 
> I guess this bug caused by WebGL textures(our current implementation based on WebGL texture mapping) on your device.

Will this WebGPU change be released soon or was it just an experiment to see if it worked?

**Comment by McKenzieJDan** [comment]
Had a similar issue over the weekend - disabling `gpuEnabled: false` is a work around for now but it's also a lot slower so not ideal. Also interested in the progress of this thanks!

**Comment by rookie-luochao** [comment]
How long is the problem expected to be solved?
