### ISSUE TITLE
removeItem删除多个的时候不好使，并且undo不能一次撤销多个

### ISSUE THREAD

**Issue by broXue** [antvis/G6#3425]
### 问题描述

removeItem删除多个的时候不好使，并且undo不能一次撤销多个
` graph.getNodes().forEach((node: any) => {
      if(node.getStates('yourStateName').includes('yourStateName')){
        mapCanvasGraph.removeItem(node.getModel().id);
      }
    });
`

### 重现链接

1

### 重现步骤

就是选中页面的多个节点，然后点击删除，不能选择删除，然后点击撤销undo的时候会一个一个撤销，不能撤销上一步删除的几个基点

### 预期行为

希望删除的时候能删除干净，比如我删除了4个，然后我调用undo的时候，恢复之前删除的4个节点

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by 313392073** [comment]
请问你解决了吗  我这边新增的节点一个个点击删除 会报错

**Comment by MorningStarHu** [comment]
我这里也是报错 有什么规避办法吗
