### ISSUE TITLE
自定义边的label(文本标签)设置后不显示

### ISSUE THREAD

**Issue by wenyuan** [antvis/G6#3428]
### 问题描述

注册自定义边时：

* 如果重写了 `draw()` 方法，边的 `label` 无法正常显示。
* 如果没有重写 `draw()` 方法，边的 `label` 可以正常显示。

为了排除是我编写的 `draw()` 方法有问题，复现时，使用了官方的多个 demo 示例代码进行试验，均存在该问题。

### 重现链接

https://g6.antv.vision/zh/examples/item/customEdge#customPolyline2

### 重现步骤

**复现步骤**：

1. 进入官方文档的[自定义折线 2](https://g6.antv.vision/zh/examples/item/customEdge#customPolyline2)这一页面。
2. 在代码的第 68 行前面插入 `label` 属性。
![image](https://user-images.githubusercontent.com/26686411/148517849-bb87fc30-f15d-470a-9ec1-e82154e007f1.png)
3. 此时该连线上没有按预期的显示出文本标签。
4. 进入官方文档的[自定义折线](https://g6.antv.vision/zh/examples/item/customEdge#customPolyline)这一页面。
5. 在代码的第 77 行前面插入 `label` 属性，此时可以显示出文本标签。
6. 两个官方DEMO的区别是，前者在注册自定义 edge 时重写了 `draw()` 方法，后者未重写该方法。

**个人猜测**：

除了使用上述代码复现，我还尝试了其他官方示例和自己写的自定义连线，问题均出现在重写 `draw()`  方法上，怀疑该 bug 和这个行为有关（仅是猜测，时间有限未进行源码级别的 debug）。

**关于版本**：

* 上述官方示例采用的是 4.3.7 版本，存在该问题。
* 通过 [CodeSandbox](https://codesandbox.io/s/brave-sky-zfnxz?file=/index.js) 切换版本后，4.3.0 - 4.5.1 中均存在该问题。更早的版本存在 Breaking Change 故无法测试。

### 预期行为

自定义连线的标签可以正常显示。

### 平台

- 操作系统: Windows 10
- 网页浏览器: Google Chrome
- G6 版本: 4.3.0 - 4.5.1

**Comment by duyunzhi** [comment]
我也遇到了这个问题，自定义线只要不继承内置线，label位置就会正确，但是不继承内置线的话 线不能跟随node显示和隐藏，可以通过监听`afteritemvisibilitychange`事件来解决。

**Comment by Yanyan-Wang** [comment]
如果复写了 draw 方法，意味着所有的绘制逻辑被重新定义，自定义的 draw 方法里面没有绘制文本的逻辑，就不会绘制文本了呀。

如果你想复用父类型的绘制文本逻辑的话，把 draw 方法改成 drawShape，并且 regiseterEdge 方法第三个参数需要继承一个内置类型。

**Comment by Yanyan-Wang** [comment]
> 但是不继承内置线的话 线不能跟随node显示和隐藏

这个不应该呀，写个在线demo看下呢

**Comment by licc12** [comment]
> > 但是不继承内置线的话 线不能跟随node显示和隐藏
> 
> 这个不应该呀，写个在线demo看下呢

drawShape只会重新绘制Edge的shape不会影响shape上的文本，如果只是想重新绘制边那就把draw改成drawShape。否则还需要添加一个label的shape：

`
group.addShape('text', {
          attrs: {
            x: cfg.startPoint.x + (cfg.endPoint.x - cfg.startPoint.x) / 2,
            y: cfg.startPoint.y + (cfg.endPoint.y - cfg.startPoint.y) / 2,
            text: cfg.label, // 这里就是你传进去的label
            textAlign: 'center',
            textBaseline: 'middle',
            fill: '#fff',
            fontSize: 10,
          },
          name: 'edge-label',
        });
`
如果用drawShape的话上面这个不就不用添加了，直接继承指定内置的那个了
