### ISSUE TITLE
以图算法中的示例代码引入Algorithm失败

### ISSUE THREAD

**Issue by DevRickLin** [antvis/G6#3429]
### 问题描述

GADDI 图模式匹配的示例透过如下方式引入Algorithm：
`import G6, { Algorithm } from '@antv/g6'`
但在我实际操作中，以上引入方法会报以下类型检查错误：

> 类型“IAlgorithm”上不存在属性“GADDI”。ts(2339)

以下是我通过编译的引入方式：
`import Algorithm from "@antv/algorithm";`

[该示例的页面链接](https://g6.antv.vision/zh/docs/api/Algorithm)

### 重现链接

https://codesandbox.io/s/recursing-sound-yq4d7?file=/src/App.js

### 重现步骤

1.透过`import G6, { Algorithm } from '@antv/g6'`引入Algorithm
2.以`const { GADDI } = Algorithm`试图取得GADDI函数

### 预期行为

本应透过示例代码的方式取得该算法的函数，却得到类型错误。

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Firefox]
- G6 版本: [4.5.1]
- typescript版本:[4.5.4]
- react版本:[17.0.2]

**Comment by Yanyan-Wang** [comment]
demo 中没有看到报错呢

**Comment by DevRickLin** [comment]
demo中没有遇到一样的报错

**Comment by Yanyan-Wang** [comment]
看下是不是版本问题呢？IAlgorithm 这里面是有 GADDI 的https://github.com/antvis/algorithm/blob/8d6b159a5e94373a1292659f46ab1e61646f5528/packages/graph/src/types.ts#L88

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。

**Comment by Banana-energy** [comment]
![image](https://github.com/antvis/G6/assets/49467518/03a2c26d-756e-4f67-ab2c-da0a3e9a6ad1)
仍然有问题
