### ISSUE TITLE
g6editor,我想改变左边itempannel图标（svg图，通过路径设定），如何实现啊

### ISSUE THREAD

**Issue by kingwubin** [antvis/g6#343]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by wmhh1129** [comment]
+1，https://antv.alipay.com/assets/dist/3.0.0/g6/1.x/editor/base.html，现在能否实现左边的图片是自定义svg图片，或者任意格式的图片也可以，希望予以解答。

**Comment by wmhh1129** [comment]
有同样的需求，[https://antv.alipay.com/assets/dist/3.0.0/g6/1.x/editor/base.html](url)，现在能否实现左边的图片是自定义svg图片，或者任意格式的图片也可以，希望予以解答。

**Comment by liekkas** [comment]
参考G6-Editor的例子，用Flow.registerNode来实现
```
// k 均值聚类
Flow.registerNode('k-means', {
  label: 'k 均值聚类',
  color_type: '#1890FF',
  type_icon_url: 'https://gw.alipayobjects.com/zos/rmsportal/czNEJAmyDpclFaSucYWB.svg',
  state_icon_url: 'https://gw.alipayobjects.com/zos/rmsportal/MXXetJAxlqrbisIuZxDO.svg',
  // 设置锚点
  anchor: [
    [ 0.5, 0, {
      type: 'input'
    }], // 上面边的中点
    [ 0.5, 1, {
      type: 'output'
    }] // 下边边的中点
  ]
}, 'model-card');
```
