### ISSUE TITLE
官网 fisheye 中的disabled 和 enable的不能来回切换？

### ISSUE THREAD

**Issue by Miever1** [antvis/G6#3433]
### Describe the bug

https://g6.antv.vision/zh/examples/tool/fisheye#fisheye 官网演示 fisheye 中的插件的添加和禁用只能切换1次？

### Your Example Website or App

null

### Steps to Reproduce the Bug or Issue

[https://g6.antv.vision/zh/examples/tool/fisheye#fisheye](演示)

### Expected behavior

可以进行多次切换

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
看了一下应该只是例子的代码中，申明 fisheye 需要改成 let 即可。将会尽快更新官网

**Comment by Yanyan-Wang** [comment]
已经修复，谢谢报告
