### ISSUE TITLE
Dagre层次布局设置nodesepFunc，ranksepFunc不生效

### ISSUE THREAD

**Issue by yanhan569046480** [antvis/G6#3438]
### 问题描述

shadow节点要跟原有的结点重叠在一起，有一定的错位，放在不同的图层上，真正像影子一样，用不同颜色来表示。

![04dace31ba8c67a25f48ddbe17a491d](https://user-images.githubusercontent.com/1505382/148880728-f8ef501f-7548-4cd6-af04-4911bfd69def.png)

左下角那个灰色的节点就是shadow节点，现在只能改颜色而无法重叠和错位，我试图通过nodesepFunc，ranksepFunc来实现，但是并没有生效。如下图：
![image](https://user-images.githubusercontent.com/1505382/148880848-6eab8045-f90d-4b45-90f6-93fedae10758.png)
tagLabel是shadow标记，如果有值则横向和纵向的间距非常小，即类似重叠和错位的效果。
![image](https://user-images.githubusercontent.com/1505382/148880858-759afd5a-0b0f-49b9-affd-5ce5c58ef78a.png)

### 重现链接

同问题描述

### 重现步骤

同问题描述

### 预期行为

同问题描述

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome]
- G6 版本: [3.8.5]

### 补充说明（可选）

我尝试过将G6版本升到最新，仍然是这样

**Comment by Yanyan-Wang** [comment]
我理解你只是想要达到一个节点上有一个影子一样的效果？这种为啥要用另外一个节点来表示呢？一个节点就是表示一个物体，用来表达另一个物体的影子是不合理的呀。可以直接用节点样式的 shadow 相关样式，用在上面那个红色节点上。如果 shadow 效果不理想，建议自定义节点，在 drawShape 方法里面增加一个灰色 circle 在红色 circle 的下面。自定义节点参考官网文档

**Comment by yanhan569046480** [comment]
就是两个结点有强关系，比如：主从结点，集群结点（同一个服务有多个实例），IoT里的影子设备，等等。这种需求应该不算小众哈😀 @Yanyan-Wang

**Comment by yanhan569046480** [comment]
已通过手动计算节点坐标的方式解决
