### ISSUE TITLE
画force图的时候，在代码不动的情况下偶尔正常运行，偶尔报错

### ISSUE THREAD

**Issue by Shelley-Xie** [antvis/G6#3439]
### 问题描述

在画力导图的时候，代码完全没有变动，但偶尔会报错Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://unpkg.com/@antv/layout@latest/dist/layout.min.js' failed to load. 

导致本来应该画几百个点的图，只会出现一个所有点重合在一起的大点。但这个问题是偶尔出现的，有的时候又自己能恢复正常

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.5.1]

**Comment by Yanyan-Wang** [comment]
worker 的布局会使用 https://unpkg.com/@antv/layout@latest/dist/layout.min.js 这个脚本，如果你的网络不能访问到这个脚本就会报错。你可以把脚本下载下来放到你项目始终能访问到的地方，把地址配置到 layout 的 workerScriptURL 上

**Comment by Yanyan-Wang** [comment]
不过你下载下来的话比较难保证一直访问到 latest

**Comment by Shelley-Xie** [comment]
> worker 的布局会使用 https://unpkg.com/@antv/layout@latest/dist/layout.min.js 这个脚本，如果你的网络不能访问到这个脚本就会报错。你可以把脚本下载下来放到你项目始终能访问到的地方，把地址配置到 layout 的 workerScriptURL 上



还是很慢，我现在下载到本地了并放到项目的public目录下，请问我将其放在本地该如何使用呢？把项目下的文件地址配置到 layout 的 workerScriptURL 上，显示failed loaded

**Comment by Arthre** [comment]
> > workerScriptURL
> 
> <img alt="image" width="539" src="https://user-images.githubusercontent.com/29218661/168541598-fa007df8-640a-4270-a58b-8bcd3bfbe829.png">

这个`workerScriptURL`是在哪里配置的？

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
