### ISSUE TITLE
使用 DOM 自定义节点 示例报错

### ISSUE THREAD

**Issue by y2293456** [antvis/G6#3440]
### 问题描述

使用文档案例创建dom节点报错：
![image](https://user-images.githubusercontent.com/58577110/148932536-ace94869-2498-48f4-a8fb-02dcbda9b87d.png)

![image](https://user-images.githubusercontent.com/58577110/148932464-762479c4-1bcf-4fdd-9c47-a622484e82e7.png)

![image](https://user-images.githubusercontent.com/58577110/148932428-8172d8ea-858c-46c9-8471-e3739a6bc235.png)

### 重现链接

https://codesandbox.io/embed/sad-hypatia-jkkb8?fontsize=14&hidenavigation=1&theme=dark

### 重现步骤

按照 https://antv-g6.gitee.io/zh/docs/manual/middle/elements/nodes/custom-node/#5-%E4%BD%BF%E7%94%A8-dom-%E8%87%AA%E5%AE%9A%E4%B9%89%E8%8A%82%E7%82%B9 文档步骤即可复现

### 预期行为

期望正常运行

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
graph 实例化时需要配置 renderer: 'svg',
![image](https://user-images.githubusercontent.com/29593318/151646884-1e91b7d8-7dd4-454e-b372-9f09967e858d.png)
