### ISSUE TITLE
打包后报错

### ISSUE THREAD

**Issue by zhxqc** [antvis/G6#3441]
### 问题描述

本地调试正常，build上线后报错

### 重现链接

、

### 重现步骤

本地调试正常，build上线后报错

### 预期行为

正常展示

### 平台

- 操作系统: macOS
- 网页浏览器: chrome   97.0.4692.71
- G6 版本: 
"@antv/g6": "4.5.2",
"insert-css": "^2.0.0",
"vue": "3.2.26",
"vite": "2.7.10",

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/35363368/148942550-53356a41-2bf1-4c64-b6eb-5b48f98869ba.png)

**Comment by zhxqc** [comment]
可能是打包问题，vite降到2.5.10后部署成功，错误消失

**Comment by GroupOfStar** [comment]
npm install vite@2.5.10 解决了
