### ISSUE TITLE
GForce布局开启workerEnabled，afterrender勾子不触发

### ISSUE THREAD

**Issue by zfamz** [antvis/G6#3446]
### 问题描述

GForce布局开启workerEnabled，afterrender勾子不触发。在官网文档中没找到有关的说明。
还有个问题： 当数据量比较大时，大概8千图元以上。gpuEnabled 和 workerEnabled 同时开启会造成图像渲染不处理。

### 重现链接

https://codesandbox.io/s/silly-saha-336vm

### 重现步骤

1. 进入页面
2. 打开控制台， 没有输出 afterrender
3. 注释layout 中的 workerEnabled
4. 查看控制台， 有 afterrender 输出

### 预期行为

当workerEnabled: true， afterrender勾子触发

### 平台

- 网页浏览器: [Google Chrome 97]
- G6 版本: [4.5.0 ]

**Comment by Yanyan-Wang** [comment]
感谢报告，我们会尽快修复

**Comment by ziijiawen** [comment]
G6 版本: [4.6.4]

使用dagre布局  afterrender依然不生效 这个版本也还没修复类似的问题吗？

**Comment by Yanyan-Wang** [comment]
当前版本中已不存在上述问题
