### ISSUE TITLE
官方示例配置下，G6.TreeGraph树图的初始位置不正常

### ISSUE THREAD

**Issue by HiWayne** [antvis/G6#3449]
### Describe the bug

`G6.TreeGraph`实例的初始位置不正常，十分偏上，只有少量底部能在canvas中出现，于是不得不使用`treeGraph.moveTo`修正。

自己的[可在线运行demo](https://replit.com/@HiWayne/antv-in-react#src/App.jsx)和[官方示例](https://github.com/baizn/g6-in-react)中的`/pages/tree/index.js`均能复现。另外如果这只是feature的话，为什么不默认在(0, 0)或(50%, 50%) ？

@antv/g6 复现版本：
1. 自己：v4.5.2
2. 官方：v3.8.5

node版本：
1. 自己：v12.22.6
2. 官方：v12.18.0

react版本：
1. 自己：v17.0.2
2. 官方：v16.14.0

### Your Example Website or App

https://replit.com/@HiWayne/antv-in-react#src/App.jsx

### Steps to Reproduce the Bug or Issue

1. 打开或刷新页面
2. 可以看到tree的初始位置停留不正常，仅有少部分出现在canvas区域中

### Expected behavior

符合心智模型的效果应该如图：
![image](https://user-images.githubusercontent.com/42726028/149475574-74b8e5a4-aef4-4f16-ac60-3d4c71691a9e.png)

实际自己的[可在线运行demo](https://replit.com/@HiWayne/antv-in-react#src/App.jsx)运行效果如图（可能因为版本从3 -> 4，所以相同配置下节点由方形变成圆形，这点可以忽略）：
![image](https://user-images.githubusercontent.com/42726028/149475834-483c8867-4958-4bd2-9f5e-827ac08745e9.png)

实际[官方示例](https://github.com/baizn/g6-in-react)运行效果如图：
![image](https://user-images.githubusercontent.com/42726028/149473209-102b873a-ab5f-4011-8362-91eb084359e4.png)

### Platform

- OS: macOS Catalina 10.15.7
- Browser: Chrome
- Browser Version: 96.0.4664.110（正式版本） (x86_64)

**Comment by Yanyan-Wang** [comment]
链接不是官网示例哈

render 之后调用 graph.fitView() ，参考官网 demo https://g6.antv.vision/zh/examples/tree/compactBox#basicCompactBox

**Comment by HiWayne** [comment]
> 

https://antv-g6.gitee.io/zh/docs/manual/getting-started#react-%E4%B8%AD%E4%BD%BF%E7%94%A8-g6

这个应该是官方文档吧

![image](https://user-images.githubusercontent.com/42726028/151952642-53c30894-86d5-40c4-b099-49d5ee927e8e.png)

点击Demo就是那个github仓库

**Comment by HiWayne** [comment]
> 链接不是官网示例哈
> 
> render 之后调用 graph.fitView() ，参考官网 demo https://g6.antv.vision/zh/examples/tree/compactBox#basicCompactBox

这个应该是官方文档吧：https://antv-g6.gitee.io/zh/docs/manual/getting-started#react-%E4%B8%AD%E4%BD%BF%E7%94%A8-g6

![image](https://user-images.githubusercontent.com/42726028/151952642-53c30894-86d5-40c4-b099-49d5ee927e8e.png)

点击Demo就是那个github仓库

**Comment by gotounix** [comment]
@Yanyan-Wang 
我从4.5.5版本升级到4.6.x版本后，发现 `GraphOptions.fitView` 和 `GraphOptions.fitCenter` 设置为 `true`，都无效了。

是只能手动调用 `graph.fitView()` 才可以吗？

**Comment by Yanyan-Wang** [comment]
升级到最新版本试试，我在官网上配置 fitView: true 是可以的。
P.S. gitee 地址的官网同步不过去了，现在可以访问这个新的地址，速度非常快，并且都是第一时间更新：https://g6.antv.antgroup.com/
