### ISSUE TITLE
使用graph.update改变线的属性会使线伸入节点中心而不是在边缘

### ISSUE THREAD

**Issue by oooofeiger** [antvis/g6#345]
* **G6 Version**:2.0.0
* **Platform**:windows
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:https://codepen.io/oooofeiger/pen/mKQrRR

移入节点触发事件，改变线的属性然后线条会伸入节点内部，怎么解决这一问题

**Comment by oooofeiger** [comment]
有没有哪位老哥碰到过类似问题啊

**Comment by TomHuangCN** [comment]
原因是 d3 会篡改 edge 的 source 和 target 。传入 simultation 之前复制一遍边就行了

![image](https://user-images.githubusercontent.com/6113694/42928753-c1139ac4-8b6a-11e8-9c1f-67dc09aaa00b.png)

```js
edges = G6.Util.cloneDeep(edges);
```
