### ISSUE TITLE
收起节点，图消失

### ISSUE THREAD

**Issue by CMILY** [antvis/G6#3456]
### 问题描述

在树图中，收起一个含有较多子节点的节点时，图会消失
监听事件，自动调用fitCenter不起作用，只有手工点击按钮，触发fitCenter，才能重新出现。

### 重现链接

https://codesandbox.io/s/reverent-forest-20fyi?file=/index.js

### 重现步骤

1、收起节点：Regression
2、图丢失，需要拖动许久，才能找回图

### 预期行为

收起节点后，图能在视窗中显示。且监听afterlayout调用fitCenter时，图能居中

### 平台

- 操作系统: Win10
- 网页浏览器: Google Chrome
- G6 版本: 4.5.2

**Comment by Yanyan-Wang** [comment]
可以把 fitCenter 放在 afteranimate 事件监听里面调用哈。因为树图默认有动画， afterlayout 只是布局计算完成，还没有动画变化节点位置完成，所以 fitCenter 无法计算出正确的位置。afteranimate 之后就可以了

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。

**Comment by CMILY** [comment]
问题解决，感谢
