### ISSUE TITLE
引入g6打包后vue组件报错

### ISSUE THREAD

**Issue by JCqiu** [antvis/G6#3458]
### Describe the bug

写了一个vue3组件 build 后打开游览器访问这个组件游览器报错TypeError: Cannot read properties of undefined (reading 'constant')，如果不使用g6 build完成后就不会报错

### Your Example Website or App

https://stackblitz.com/edit/vue-ebuw2p?file=src%2Fcomponents%2FHelloWorld.vue

### Steps to Reproduce the Bug or Issue

打包完成后打开游览器访问

### Expected behavior

希望是我的代码问题，但现在找不到错误原因

### Screenshots or Videos

build后，打印G6都会报错
![image](https://user-images.githubusercontent.com/16211027/149883379-fee901f4-eb58-49b2-9487-7758f07cf795.png)
![image](https://user-images.githubusercontent.com/16211027/149883396-2bbfdc65-b651-4551-8ac1-98afa2f0554b.png)
不使用就不会报错

### Platform

- OS: Windows10
- Browser: Chrome
- Version: 97.0.4692.71

**Comment by JCqiu** [comment]
![image](https://user-images.githubusercontent.com/16211027/149883906-5eb8c7e0-e643-4aee-a555-97674cecd32e.png)
只是import G6 不使用G6就不会报错

**Comment by daiwanxing** [comment]
https://github.com/antvis/G6/issues/3441 和这个问题类似
