### ISSUE TITLE
调用G6.changeData 不传参报错

### ISSUE THREAD

**Issue by daiwanxing** [antvis/G6#3459]
### 问题描述

https://antv-g6.gitee.io/zh/docs/api/graphFunc/data#graphchangedatadata-stack。

官方文档上写着不传参会沿用旧的数据源更新。但是我通过调用该API不传参数后发现控制台打印如下日志:  ` G6 Error Tips: the data must be defined`

仔细查阅了源码发现这个错误的原因在于changeData时会内部调用dataValidation这个方法，并将data传进去，如果data不传，那不就对数据源验证失败了吗？

![image](https://user-images.githubusercontent.com/37327614/149891705-85fa8ad5-9c02-4074-919f-d1603bbbbf2e.png)
![image](https://user-images.githubusercontent.com/37327614/149891729-75b71ffa-3eda-44d0-a237-bc5317603329.png)

### 重现链接

/

### 重现步骤

/

### 预期行为

期望运行正常

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
好的感谢反馈，会尽快修复
