### ISSUE TITLE
官网样式链接404

### ISSUE THREAD

**Issue by Miever1** [antvis/G6#3464]
### Describe the bug

[Edge](https://g6.antv.vision/en/docs/api/Items/edgeProperties)，官网 Edge 中 style 中 The complete configurations is listed in: Shape Properties 中的链接 404

### Your Example Website or App

https://g6.antv.vision/en/docs/api/Items/edgeProperties

### Steps to Reproduce the Bug or Issue

check describe

### Expected behavior

can open the style link

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
感谢报告，我们会尽快修复

**Comment by Yanyan-Wang** [comment]
已修正，再次感谢
