### ISSUE TITLE
移动端自定义html节点，render配置为svg后，所有事件失效

### ISSUE THREAD

**Issue by AIXGEEK** [antvis/G6#3468]
### Describe the bug

移动端自定义html节点，render配置为svg后，所有事件失效

### Your Example Website or App

安卓、苹果设备

### Steps to Reproduce the Bug or Issue

移动端自定义html节点，render配置为svg后，所有事件失效

### Expected behavior

移动端自定义html节点，render配置为svg后，所有事件失效

### Platform

- OS: IOS、Android
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
html+svg 节点不支持 G6 交互事件，需要使用原生事件：https://g6.antv.vision/zh/docs/api/shapeProperties#dom-svg
例子：https://g6.antv.vision/zh/examples/item/customNode#svgDom

建议用 canvas 替代，可以尝试 jsx 节点：https://g6.antv.vision/zh/examples/item/customNode#jsxNode

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
