### ISSUE TITLE
销毁画布时报错TypeError: Cannot read properties of null (reading 'removeChild')

### ISSUE THREAD

**Issue by lengyuxian** [antvis/G6#3472]
### 问题描述

树形组件，在销毁画布时，一直报错，如下图：
![image](https://user-images.githubusercontent.com/29294854/150454882-d0805e2b-b407-4fcc-b489-ebd393116764.png)
代码如下：
![image](https://user-images.githubusercontent.com/29294854/150455108-1078f6b2-cd94-4104-a09f-153077ad9b2c.png)
![image](https://user-images.githubusercontent.com/29294854/150455160-54084ebf-872f-4dce-94ee-816e80f86dc2.png)

### 重现链接

暂无

### 重现步骤

1、进入页面，编辑树图数据
2、离开页面
3、报错

### 预期行为

1、离开页面时正常销毁画布，不报错

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]Windows
- 网页浏览器: [Google Chrome, Safari, Firefox]Google Chrome
- G6 版本: [4.5.1 ... ]最新

**Comment by Yanyan-Wang** [comment]
if (this.graph && !this.graph.destroyed) graph.destroy()

**Comment by yyxhqm** [comment]
请问这个问题解决了吗？我也遇到了destroy一直报错的问题，Failed to execute 'removeChild' on 'Node'

**Comment by iyanming** [comment]
@Yanyan-Wang 还是不行。。
if(graph && !graph.destroyed) {
        graph.destroy(); // 销毁
  }

**Comment by iyanming** [comment]
if(graph && !graph.destroyed) {
        try {
          graph.destroy(); // 销毁
        } catch (error) {
        }
}
暂时这么处理了
