### ISSUE TITLE
重绘时图集中在中心

### ISSUE THREAD

**Issue by sunshinewangyingni** [antvis/G6#3476]
### 问题描述

绘制关系图时，大概有2000个节点，初次进入或者刷新后进入都正常，返回首页二次进入或者跳入下一页返回此页面时出现所有点线聚集在一起，大概在中心位置的一个情况。 #

### 重现链接

暂无

### 重现步骤

1从首页进入点击
2跳转至该页面正常（关系图页面，初次进链接进入正常，如果时返回首页再进来就出现所有点线集中在中心的问题）
3 进入下个页面
4 返回上个页面（关系图页面所有点线集中在中心）
graph.destroy()和graph.clear()都试过，无效

### 预期行为

无论什么时候进入，或者返回该界面，都能正常绘制

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

暂无

### 补充说明（可选）

1从首页进入点击
2跳转至该页面正常（关系图页面，初次进链接进入正常，如果时返回首页再进来就出现所有点线集中在中心的问题）
3 进入下个页面
4 返回上个页面（关系图页面所有点线集中在中心）
graph.destroy()和graph.clear()都试过，无效

**Comment by Yanyan-Wang** [comment]
请提供在线复现 demo

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
