### ISSUE TITLE
设置水印后怎么取消，达到一个切换

### ISSUE THREAD

**Issue by zqzq-zq** [antvis/G6#3478]
### 问题描述

项目需求需要设置水印和取消水印，达到切换得目的，官网api只有setTextWaterMarker，没有取消

### 重现链接

无

### 重现步骤

项目需求需要设置水印和取消水印，达到切换得目的，官网api只有setTextWaterMarker，没有取消

### 预期行为

项目需求需要设置水印和取消水印，达到切换得目的，官网api只有setTextWaterMarker，没有取消

### 平台

Windows

### 补充说明（可选）

无

**Comment by Yanyan-Wang** [comment]
好的，后面考虑加一个关闭 API，现在暂时可以这样关闭：

const canvas = graph.get('graphWaterMarker');
canvas.destroy();
graph.set('graphWaterMarker', undefined);

**Comment by Yanyan-Wang** [comment]
v4.7.16 支持 setTextWaterMarker 和 setImageWaterMarker 第一个参数传 undefined，即可删除当前水印
