### ISSUE TITLE
How to set the default zoom?

### ISSUE THREAD

**Issue by monolithed** [antvis/G6#3487]
### 问题描述

The **minZoom** and **maxZoom** are intermediate properties. Where is the **defaultZoom** property?

### 重现链接

https://codesandbox.io/s/nifty-pine-f7eu2?file=/index.js

### 重现步骤

Zoom out

### 预期行为

No zooming

### 平台

- 操作系统: [macOS.]
- 网页浏览器: [Google Chrome, Safari]
- G6 版本: [latest]

**Comment by Yanyan-Wang** [comment]
Call `graph.zoomTo(defaultZoom)` after `graph.render()`

**Comment by monolithed** [comment]
@Yanyan-Wang , thanks but what about `graph.fitView`?

Does not work (the same result):

```js
graph.render();
graph.zoomTo(2)
graph.fitView();
```


it works, but graph.fitView is not applied:

```js
graph.render();
graph.fitView();
graph.zoomTo(2)
```

**Comment by Yanyan-Wang** [comment]
fitView means fit the graph to the view port, why do you want to fitView and zoomTo in the same time?

**Comment by monolithed** [comment]
@Yanyan-Wang I used the graph.fitView property to center my Graph. You can comment the graph.fitView() line at the end of file my example to see what I mean.
