### ISSUE TITLE
Memory leak identified while expand/collapse combos

### ISSUE THREAD

**Issue by mohanavalli-sv** [antvis/G6#3489]
### Describe the bug

When graph is rendered  based on the expand /collapse of custom combos , even after collapsing the combos there is an increase in  heap size and nodes are not getting collected . Performance issues while dynamically loading data on combo clicks .

### Your Example Website or App

https://codesandbox.io/s/modest-dust-ln1bt?file=/src/app/app.component.html

### Steps to Reproduce the Bug or Issue

1.Expand the combo
2.Collapse the combo
3.Repeat the above steps 
4.Start the performance recording
5.Repeat step 1 
6.Repeat step 2.
7.Stop the performance recording
8.Take a look at the chart for the JSHeap and Nodes.

### Expected behavior

As a user I expect to see the JSHeap and Nodes go down once the combo is collapsed.

### Screenshots or Videos

![Screen Shot 2022-01-28 at 3 51 18 PM](https://user-images.githubusercontent.com/98620502/151629110-2a96600e-56c8-4d04-9dba-6080a01b81cf.png)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
Hi, dear user. Since there was no response for a long time, we cannot figure out the answer of the problem you described. If there is new progress, feel free to open a new issue.
