### ISSUE TITLE
单独创建combo设置样式后不生效

### ISSUE THREAD

**Issue by zqzq-zq** [antvis/G6#3490]
### 问题描述

单独创建一个combo，里面不包含任何node,运行时调用updateItem更新combo得fill 设置后没有实时生效，必须拖拽以下才能看到修改后得样式，另外鼠标移到更新后得combo，又恢复原样了。

### 重现链接

无

### 重现步骤

单独创建一个combo，里面不包含任何node,运行时调用updateItem更新combo得fill 设置后没有实时生效，必须拖拽以下才能看到修改后得样式，另外鼠标移到更新后得combo，又恢复原样了。

### 预期行为

单独创建一个combo，里面不包含任何node,运行时调用updateItem更新combo得fill 设置后没有实时生效，必须拖拽以下才能看到修改后得样式，另外鼠标移到更新后得combo，又恢复原样了。

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]
windows

**Comment by Yanyan-Wang** [comment]
写一个在线复现 demo 看下呢

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
