### ISSUE TITLE
G6中的树，数据过多的时候会出现位置错乱的问题

### ISSUE THREAD

**Issue by allny** [antvis/G6#3498]
### Describe the bug

<img width="832" alt="add02e291cff3c9616f6cf0672341d7" src="https://user-images.githubusercontent.com/28054513/152945284-fcfc25cf-1830-43d6-bcdd-b4795f78cf59.png">
如图所示，单有线段文字没有了

### Your Example Website or App

https://codesandbox.io/s/vibrant-chebyshev-1in71?file=/index.html

### Steps to Reproduce the Bug or Issue

1.点击最后一个节点，会在后面追加数据。然后就会出现错乱的问题

### Expected behavior

不出现这种错乱

### Screenshots or Videos

![Uploading add02e291cff3c9616f6cf0672341d7.png…]()

### Platform

Windows11
 Chrome
- Version: [97.0.4692.99]

**Comment by Yanyan-Wang** [comment]
出现这种情况一般是节点存在不合法 id，
1. 节点 id 存在重复
2. 节点 id 缺失
3. 节点 id 不是 string

**Comment by Yanyan-Wang** [comment]
看了下你发的 demo，把 graph.layout() 去掉即可，updateChildren 内部会调用重新布局。

**Comment by allny** [comment]
> 把你下发的demo，把会的layout()去掉，更新Child内部重新结构。

 去掉graph.layout() 还是会出现，你重新刷新页面看看。一开始我也并未添加graph.layout()  但是因为出现错乱，所以才选择加上graph.layout() 。

**Comment by limit00** [comment]
遇到类似的问题，子节点的数量超过一定值好像就会出现，请问该如何解决？

**Comment by Yanyan-Wang** [comment]
应该是布局的计算时间和动画产生了冲突，动画开始的时候实际上大数据量的布局还没有计算完成。建议在展开大量节点的时候，把动画关掉：graph.set('animate', false)，展开完成后再开启

**Comment by frontend-afei** [comment]
感谢，关掉动画就可以了！

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
