### ISSUE TITLE
如何将rect节点的label对齐到左上角

### ISSUE THREAD

**Issue by YuchenWell** [antvis/G6#3500]
### 问题描述

是否有提供接口实现实现类似的效果？

### 重现链接

https://codesandbox.io/s/mtfy5

### 重现步骤

下面的配置会让标签位于节点中间对齐
```js
labelCfg: {
  position: 'top',
  offset: 5,
},
```

是否有其它方法实现需要的效果？

或者支持设置topLeft或者offset支持分开设置xy？
```js
labelCfg: {
  position: 'topLeft',
  offsetX: 0,
  offsetY: 5,
},
```

### 预期行为

允许将rect节点的label对齐到左上角

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![企业微信截图_16443883403663](https://user-images.githubusercontent.com/25000956/153134901-cbadd6ce-b7de-48c6-bdde-a1117fac3e1b.png)

**Comment by Yanyan-Wang** [comment]
labelCfg: {
  position: 'top',
  style: {
    textAlign: 'left',
    x: -width / 2 // width 是节点的宽
  }

},
