### ISSUE TITLE
edges链接导致combo布局

### ISSUE THREAD

**Issue by conan51551** [antvis/G6#3501]
### 问题描述

因为从中间node直接连接到结尾node，导致combo的布局显示问题。如图中显示，编号为2的combo盖住了编号为3的combo

### 重现链接

https://codesandbox.io/s/new

### 重现步骤

展示的问题

### 预期行为

我希望看到每个combo都是从左至右的布局,如图二所示

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/15792782/153178330-446dad84-8b50-4d58-b13c-a979862f174d.png)

![image](https://user-images.githubusercontent.com/15792782/153180767-812a9e06-c69f-4e8f-9093-66db3c03f06f.png)

**Comment by Yanyan-Wang** [comment]
dagre 布局吗？配置 sortByCombos true 了吗？

**Comment by conan51551** [comment]
![image](https://user-images.githubusercontent.com/15792782/154601713-39689d7a-bac1-4d1a-90c3-c7d435c40f49.png)
加了还是重叠的

**Comment by conan51551** [comment]
![image](https://user-images.githubusercontent.com/15792782/154602948-b5cefc02-b8e7-4ee7-9a2f-04daf5ad4e54.png)
现在问题是，我以为是我自定义了edges造成的，但是我把自定义的删除了，这个combo还是重合的

**Comment by conan51551** [comment]
> dagre 布局吗？配置 sortByCombos true 了吗？

还是有问题

**Comment by Yanyan-Wang** [comment]
目前的 dagre 还没发完全处理这种带分组的情况，sortByCombos 只能缓解。目前新的 dagre+combo 正在开发中，本周应该可以出 beta 版本

**Comment by conan51551** [comment]
好的，期待！

**Comment by meiliujun** [comment]
![image](https://user-images.githubusercontent.com/7381228/170977094-95030338-d6e8-4b44-b10c-3b9d2e6bc085.png)
有collapsed:true的 combo 元素布局就有点问题了啊

**Comment by Yanyan-Wang** [comment]
请尝试当前最新版本，再有问题请提供一下在线复现 demo
