### ISSUE TITLE
collapseExpandCombo 后调用 updateLayout 方法，导致自定义布局拿到的数据是不完整的

### ISSUE THREAD

**Issue by simplejason** [antvis/G6#3508]
### Describe the bug

1、初始数据 {nodes: [{id: '0'}, ]}
2、点击图标收起 combo
3、自定义 layout execute 方法拿到的数据，收起 combo 下的 node 不见了，导致期望按照原始数据和 combo 属性状态 重新布局时拿不到

```javascript
// 原始数据
const data = {
  nodes: [
    {id: '0', comboId: 'combo0'},
    {id: '1'}
  ],
combos: [{id: 'combo0'}]
}

// collapseExpandCombo 后调用 updateLayout
// 自定义布局的 execute 方法拿到的数据 0 节点消失了，变成了下面的数据
{
  nodes: [
    {id: '1'}
  ],
combos: [{id: 'combo0'}]
}```

### Your Example Website or App

https://codesandbox.io/s/gallant-phoebe-bsbgx

### Steps to Reproduce the Bug or Issue

1、初始数据 nodes 10个
2、点击图标收起 combo
3、自定义 layout execute 方法拿到的数据，收起 combo 下的 node 不见了，导致期望按照原始数据和 combo 属性状态 重新布局时拿不到

### Expected behavior

updateLayout 后 自定义布局 execute 方法能拿到完整的数据

### Screenshots or Videos

_No response_

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]


### Additional context

_No response_

**Comment by Yanyan-Wang** [comment]
默认 nodes 里面放的是显示在画布上的节点，因为一般布局只会考虑显示的节点。需要那些被隐藏的节点的话，尝试自定义布局复写 init 函数：

public init(data) {
    this.nodes = data.nodes || [];
    this.edges = data.edges || [];
    this.combos = data.combos || [];
    this.comboEdges = data.comboEdges || [];
    this.hiddenNodes = data.hiddenNodes || []; // 被隐藏的节点
    this.hiddenEdges = data.hiddenEdges || []; // 被隐藏的边
  }

**Comment by simplejason** [comment]
> 

打印出来发现隐藏的 combos 归属到了 hiddenEdges 里，看上去并不是期望的行为。请问这一步是在哪 set 的，g6 里？我在 G6 和 layout 库均没有找到对应的代码 :(
![image](https://user-images.githubusercontent.com/11643113/153526811-1bd5204c-7933-4cea-b75d-7dc2a0ae1423.png)

**Comment by simplejason** [comment]
> G6
> 
> https://github.com/antvis/G6/blob/d86be427bfe0a5c611ba5f1386fe0f68f4dab9dc/packages/core/src/graph/controller/layout.ts#L115
> 
> line 157 写错了

OK，这个有计划修掉吗？看起来只需要按以下修复即可
```diff
if (!comboItem.isVisible()) {
- hiddenEdges.push(model);
+ hiddenCombos.push(model);
  continue;
}
```
