### ISSUE TITLE
如何在GPU Fruchterman 小数据中使节点显示隐藏

### ISSUE THREAD

**Issue by 54955901** [antvis/G6#3511]
### 问题描述

节点上我需要显示与隐藏，我现在不确定该使用怎样的API或者自定义的方法去实现他。

### 重现链接

https://riddle.alibaba-inc.com/riddles/d1214d04

### 重现步骤

点击节点没办法实现显示隐藏

### 预期行为

节点可以显示隐藏，类似辐射图一样，可以有动画的显示隐藏一个节点与它的子节点

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
graph.showItem(node)
graph.hideItem(node)

API 都可以从官网查到哈。带动画的话，需要通过为图形增加动画，动画完成后再调用上述 API。图形增加动画参考：
```
      node.getContainer().animate(
        (ratio) => {
          return {
            opacity: 1 - ratio // 透明度逐渐降低
          };
        },
        {
          repeat: false,
          duration: 500,
          easing: 'easeCubic',
          callback: () => {}
        },
      );
```

showItem 和 hideItem 可以在 callback 里面去调用，或者在外面 setTimeout 500 再调用

和使用什么布局，是否用 GPU 应该没有关系哈

**Comment by 54955901** [comment]
> 已经完成了需求，感谢回复
