### ISSUE TITLE
zoomto和enableOptimize、optimizeZoom不兼容

### ISSUE THREAD

**Issue by limingkang** [antvis/G6#3512]
### 问题描述

当我初始化设置图谱如下`  {
              type: 'zoom-canvas',
              enableOptimize: true,
              optimizeZoom: 0.9,
            },`

使用zoomTo方法把图谱缩放到0.3， 没有自动隐藏非 keyShape

### 重现链接

http://

### 重现步骤

1. 图谱初始化设置
`            {
              type: 'zoom-canvas',
              enableOptimize: true,
              optimizeZoom: 0.9,
            },`
2. 页面加入一个按钮，点击之后通过zoomTo方法设置zoom到0.3
3. 页面没有自动隐藏非 keyShape

### 预期行为

期望页面会随着zoomTo设置缩放比例的不同自动显示或者隐藏非 keyShape

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
zoomTo 是 Graph 上的 API，隐藏/显示图形是 zoom-canvas 这个 behavior 的优化。两个是相互独立的哈。如果你想要 zoomTo 也有隐藏/显示图形的效果的话，可以参考这里的实现：

https://github.com/antvis/G6/blob/d86be427bfe0a5c611ba5f1386fe0f68f4dab9dc/packages/pc/src/behavior/zoom-canvas.ts#L182
