### ISSUE TITLE
切换节点文字位置，文字位置出现错误

### ISSUE THREAD

**Issue by daichaofan** [antvis/G6#3513]
### Describe the bug

切换节点文字labelCfg的position配置，更新节点后，文字位置错误

### Your Example Website or App

https://codesandbox.io/s/relaxed-wilbur-sd0eq?file=/index.js

### Steps to Reproduce the Bug or Issue

1、点击left
2、点击bottom
3、节点文字位置错误

### Expected behavior

切换节点文字位置，节点文字位置正确

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 4.5.5]

### Additional context

与之前版本比较发现是updateLabel时实现改动，之前版本updateLabel计算样式会融合全局nodeLabel样式

**Comment by Yanyan-Wang** [comment]
收到，会尽快修复。暂时可以这样避免问题：

![image](https://user-images.githubusercontent.com/29593318/155453353-532c6c7c-6909-4bb6-9c4a-26087dec8a8b.png)
