### ISSUE TITLE
Setting edge as inactive does not change the opacity of edge labels (将边设为不活跃不会改变边标签的透明度)

### ISSUE THREAD

**Issue by dukesun99** [antvis/G6#3514]
### 问题描述

Setting edge as inactive does not change the opacity of edge labels. Please help to check if this is intended and if yes, any suggested directions to change it?
将边设为不活跃不会改变边标签的透明度。请帮忙查看下是否是一个预期中的行为，如果是，请问有什么建议的方法去更改这个行为呢？

### 重现链接

https://codesandbox.io/s/loving-banach-zch3t?file=/App.tsx

### 重现步骤

1. Enter the attached link
2. Hover mouse onto "路径-1" and "路径-2"

1. 进入上面的链接
2. 悬浮鼠标到"路径-1"和"路径-2"上

### 预期行为

I expect to see the edge labels fade out along with the edges, and I see the edges fade out but label stays.
我期待看到边标签和边一起淡出，我实际看到边淡出但是标签保留不变。

### 平台

- 操作系统: Windows
- 网页浏览器: Google Chrome
- G6 版本: 4.5.5

- OS: Windows
- Browser: Google Chrome
- G6 Version: 4.5.5

### 补充说明（可选）

I notice it when using Graphin, but I think this is a G6 implementation thus I ask here. Sorry if it is the wrong place.

我在用Graphin这个库时候遇到的，但是我认为这是G6的部分，所以我在这里发了issue。如果不是正确的地方很抱歉。

**Comment by Yanyan-Wang** [comment]
这个应该是 graphin 的这种边类型自己定义的状态样式哈，inactive 状态的时候没有设定文本图形的样式 ，可以到 graphin 的 issue 里面提下看。
