### ISSUE TITLE
通过状态管理顶点样式时，修改顶点图标，会干扰其他顶点，导致被影响的顶点无法修改样式。

### ISSUE THREAD

**Issue by junping1991** [antvis/G6#3515]
### 问题描述

点击一个顶点，给顶点添加状态（自定义状态），再通过状态找到该点，将该点修改通过图标展示，会将该点的颜色附到另一个顶点上（nodes数组中该点的上一个顶点），导致这个顶点的颜色就改边不了了。

### 重现链接

https://codesandbox.io/s/distracted-cray-vy0cx?file=/index.js

### 重现步骤

1、单击label为1的点；
2、点击’修改图标‘按钮；
3、单击label为0的点；

### 预期行为

我期望看到：
 点0的颜色为自己的颜色，点击更改颜色，能改为红色。
我实际看到：
点0的颜色变为了点1的颜色，点击更改颜色，点0的颜色没有改边。

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.2 ... ]

### 屏幕截图或视频（可选）

https://user-images.githubusercontent.com/48952401/153791652-f1ae0508-9356-4f5a-b371-bed3ddb5973f.mp4

### 补充说明（可选）

自定义顶点样式，通过状态管理的顶点，在修改图标时就会出现这样的问题，修改其他样式不会，然后如果顶点没有添加过状态也不会出现这个问题。

**Comment by Yanyan-Wang** [comment]
理论上不建议动态修改节点的 id 和 type。然后 image 节点没有 fill 属性，这里的问题可以通过更新节点为 image 的时候将 fill 设置为 undefined 解决
```
graph.updateItem(item[0], {
    type: "image",
    style: {
      fill: undefined
    },
    img:
       "https://gw.alipayobjects.com/os/s/prod/antv/assets/image/logo-with-text-73b8a.svg"
  });
```

**Comment by junping1991** [comment]
您好，您的邮件我已经收到，谢谢！

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。

**Comment by junping1991** [comment]
您好，您的邮件我已经收到，谢谢！
