### ISSUE TITLE
期望使用downloadFullImage、downloadImage下载图片时，支持下载带水印的图片。

### ISSUE THREAD

**Issue by lt296812252** [antvis/G6#3516]
### 问题描述

当前使用的4.5.4版本，试了下，下载的图片没有水印。

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

window

**Comment by Yanyan-Wang** [comment]
graph.downloadImageWatermark

**Comment by Yanyan-Wang** [comment]
有的呀，设置了 graph.setTextWaterMarker 的话，下载的时候就会带的
