### ISSUE TITLE
期望框选线的一部分，就可以选中该线

### ISSUE THREAD

**Issue by xinxincat** [antvis/G6#3517]
### 问题描述

目前默认行为是：完全框选中线才可以选中该条线

### 重现链接

无需

### 重现步骤

设置brush-select模式，框选多个节点以及线，选框需要完全覆盖线才可以选中线

### 预期行为

通过框选线的一部分 就可以选中线

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
好提议。看下社区有没有小伙伴愿意共建一下哈，给 brush-select 增加一个模式，用户可以通过参数配置
