### ISSUE TITLE
边把中间的图形遮挡住了 请问该怎么解决

### ISSUE THREAD

**Issue by xiaoxigua-web** [antvis/G6#3518]
### 问题描述

<img width="810" alt="image" src="https://user-images.githubusercontent.com/24602445/153977895-ed6ea683-3074-498f-bd2a-3b7846ee7803.png">

### 重现链接

https://g6.antv.vision/zh/examples/tool/minimap#minimap

### 重现步骤

无

### 预期行为

期待不遮挡

### 平台

- 操作系统: [macOS, ..]
- 网页浏览器: [Google Chrome,]
- G6 版本: [4.5.1 ... ]

**Comment by simplejason** [comment]
[元素高级操作-节点与边的层级](https://g6.antv.vision/zh/docs/manual/middle/elements/methods/elementIndex#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95)
```javascript
const nodes = graph.getNodes();
// 遍历节点实例，将所有节点提前。
nodes.forEach((node) => {
  node.toFront();
});
// 更改层级后需要重新绘制图
graph.paint();
```

**Comment by xiaoxigua-web** [comment]
> [元素高级操作-节点与边的层级](https://g6.antv.vision/zh/docs/manual/middle/elements/methods/elementIndex#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95)
> 
> ```js
> const nodes = graph.getNodes();
> // 遍历节点实例，将所有节点提前。
> nodes.forEach((node) => {
>   node.toFront();
> });
> // 更改层级后需要重新绘制图
> graph.paint();
> ```

谢谢 不过我中间这个是个矩形 不是节点 是通过 增加额外图形 加上去的 https://g6.antv.vision/zh/docs/manual/middle/elements/edges/custom-edge

**Comment by simplejason** [comment]
> > [元素高级操作-节点与边的层级](https://g6.antv.vision/zh/docs/manual/middle/elements/methods/elementIndex#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95)
> > ```js
> > const nodes = graph.getNodes();
> > // 遍历节点实例，将所有节点提前。
> > nodes.forEach((node) => {
> >   node.toFront();
> > });
> > // 更改层级后需要重新绘制图
> > graph.paint();
> > ```
> 
> 谢谢 不过我中间这个是个矩形 不是节点 是通过 增加额外图形 加上去的 https://g6.antv.vision/zh/docs/manual/middle/elements/edges/custom-edge

应该没什么区别，要么提升 node 层级，要么降低 edge 层级，自定义边也是继承了 edge

**Comment by Yanyan-Wang** [comment]
因为边的 path 和边上其他图形是在一个图形分组里的，所以同一条边上的内容只能在同一层级。只能把被遮挡的那条边整个做一下 toFront： edge.toFront()

另外的思路是给边的路径图形加上透明度，使遮挡不那么严重。或者改变边的 controlPoints，让它形状变化一些，避免两条边特别靠近的情况

**Comment by cliffordfajardo** [comment]
似乎@xiaoxigua-web 可能正在寻找一种设置，它可以让 G6 意识到任何边缘重叠并自动分散间距以防止重叠，而无需在代码中强制设置此逻辑。

可能类似于 [antv/X6 库](https://github.com/antvis/x6)
- 演示：https://x6.antv.vision/en/examples/gallery#category-Router
- 文档：https://x6.antv.vision/en/docs/api/registry/router/#gatsby-focus-wrapper

我确实看到了这一点，我认为这种情况对其他人来说很常见，但我的假设是，要做到这一点，需要事先进行大量计算？

笔记：
我缺乏关于 X6 内部的技术背景，它可能超出了本次谈话的范围。 只需在这里为对话和学习做出贡献。


--------
### English

It seems like what @xiaoxigua-web was maybe looking for was a setting that would make G6 aware of any edge overlap and automatically spread the spacing out to prevent overlap without the need to imperatively set this logic up in the code.

Perhaps similar to [antv/X6 library ](https://github.com/antvis/x6)
- Demo: https://x6.antv.vision/en/examples/gallery#category-Router
- Docs: https://x6.antv.vision/en/docs/api/registry/router/#gatsby-focus-wrapper

I do see this I see this scenario being common for others, but my assumption is that it would take lots of computation before hand to make this happen?

Note:
I lack technical context on X6 internals & its likely out of scope for this conversation. Simply here to contribute to the conversation & learn as well.
