### ISSUE TITLE
updateLayout({type: "force"})不起作用

### ISSUE THREAD

**Issue by yfzm01** [antvis/G6#3520]
### 问题描述

updateLayout其他任何布局都可以，但是力导向图就没动静

### 重现链接

https://codesandbox.io/s/tender-resonance-h0mqe?file=/index.js

### 重现步骤

setTimeout(() => {
  graph.updateLayout({
    type: "circular"
  });
}, 3000);

setTimeout(() => {
  graph.updateLayout({
    type: "grid"
  });
}, 6000);

setTimeout(() => {
  graph.updateLayout({
    type: "dagre"
  });
}, 9000);
以上都能起作用，下面的定时器执行了，但是不会updateLayout为力导向图
setTimeout(() => {
  graph.updateLayout({
    type: "force"
  });
}, 12000);

### 预期行为

 graph.updateLayout({
    type: "force"
  });
能起作用

### 平台

- 网页浏览器: [Google Chrome]
- G6 版本: [4.5.5]

**Comment by nishuer** [comment]
我目前是这样做的，更新到力导布局前，先销毁当前布局就可以生效 `graph.destroyLayout()`
因为你实例化配置里面默认设置了 type: 'force'，可能力导布局存在某种数据缓存机制，数据没有变化就把所有节点过滤了，不参与布局。具体等官方解答。

**Comment by yfzm01** [comment]
> 我目前是这样做的，更新到力导布局前，先销毁当前布局就可以生效 `graph.destroyLayout()` 因为你实例化配置里面默认设置了 type: 'force'，可能力导布局存在某种数据缓存机制，数据没有变化就把所有节点过滤了，不参与布局。具体等官方解答。

graph.destroyLayout()会报错，我在官网看了，没有这个api

**Comment by Yanyan-Wang** [comment]
大概是楼上所说的原因，这个地方可能判断有误：
https://github.com/antvis/G6/blob/d86be427bfe0a5c611ba5f1386fe0f68f4dab9dc/packages/core/src/graph/graph.ts#L2356

可以通过楼上方法暂时解决，会尽快修复

**Comment by Yanyan-Wang** [comment]
当前版本中已不存在上述问题
