### ISSUE TITLE
自定义带圆角折线边，弧度计算问题

### ISSUE THREAD

**Issue by chi-gao** [antvis/G6#3521]
### 问题描述

你好，我使用g6参考 polyline的圆角计算逻辑，实现了自己的自定义边，但是遇到 当两个节点y坐标 相差小于弧度时，边的拐角 和 弧度展示有问题，参考下图
![image](https://user-images.githubusercontent.com/24784430/154185822-9c2f4067-e003-4638-8084-221c73680284.png)

请问该如何修改计算逻辑，尽可能避免这种情况。代码请参考 **重现链接**

### 重现链接

https://codesandbox.io/s/nervous-moser-rf188k?file=/src/index.js

### 重现步骤

直接参考demo即可，第二层最后一个子节点的边 有问题。

### 预期行为

产生平滑的曲线

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by garygao12580** [comment]
有人帮忙看看嘛🥺

**Comment by Yanyan-Wang** [comment]
可能短期内还没有时间解决，是否能根据两端 y 方向距离调整下 radius

**Comment by garygao12580** [comment]
> 

这个时候是不是 radius 等于 两端y坐标对差值一半会好一些？

**Comment by zcjpass** [comment]
请问这个问题是否解决，我也遇到了

**Comment by chi-gao** [comment]
> 请问这个问题是否解决，我也遇到了

还木有，我这边还没找到好的办法

**Comment by Aarebecca** [comment]
这种情况建议采用三次贝塞尔曲线，并适当设置控制点位置
