### ISSUE TITLE
内置donut怎么按住色板拖拽

### ISSUE THREAD

**Issue by wl1532502541** [antvis/G6#3527]
### 问题描述

donut配置了icon后，按住中间的icon可以拖动，按住周围的色板不能拖动，对donut的style设置（cursor:pointer）色板也不能生效

### 重现链接

。

### 重现步骤

defaultNode: {
    type: 'donut',
    style: {
      lineWidth: 0,
      cursor: 'pointer',
      'z-index': '122'
    },
    labelCfg: {
      position: 'bottom'
    },
    size: 40,
    icon: {
      show: true,
      img: HTTP_IMG,
      height: 20,
      width: 20,
      cursor: 'pointer'
    },
    donutColorMap: {
      success: '#61DDAA',
      fail: '#F08BB4',
      unknown: '#65789B'
    }
  }

### 预期行为

donut配置了icon后，按住中间的icon可以拖动，按住周围的色板不能拖动，对donut的style设置（cursor:pointer）色板也不能生效

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by wl1532502541** [comment]
> 你好 @wl1532502541 ， 您能否提交一个最小的“codesandbox”链接来重现您面临的挑战？
> 
> 创建一个代码框链接可以显着帮助“G6”团队，让他们能够快速可视化并与您面临的挑战进行交互。
> 
> G6 维护人员在帮助维护这个很棒的开源库之外还有全职工作，因此任何帮助团队更容易查看您的错误的帮助表示赞赏。 否则，由于您通过不提供“codesanbox”链接为 G6 团队引入的额外挑战，预计响应时间会变慢。
> 
> 我们非常感谢您提交错误报告； 我希望你能理解我们善意的意图🙏🙂
> 
> ### English translation:
> Hi,
> 
> Would you be able to submit a minimal "codesandbox" link to reproduce the challenge you are facing? Creating a codesandbox link significantly helps the "G6" team by you enabling them to quickly visualize and interact with the challenge you are facing.
> 
> G6 maintainers have full time jobs outside of helping maintain this awesome open souce library, so any help to make it easier for the team to look at your bug is appreciated. Otherwise, expect slower response times due to the additional challenge you are introducing for the G6 team by not providing a "codesanbox" link.
> 
> We really do appreciate your submitting a bug report; I hope you understand our well meaning intentions 🙏🙂

感谢，链接：https://codesandbox.io/s/g6-donut-issue-d4iij6
其中user这个点的色板只有1种颜色，其他的点不止1种。然后user这个点的色板失去了对于 拖动 和 设置"cursor:pointer"样式 的响应。
![1645357726(1)](https://user-images.githubusercontent.com/60176594/154841026-08b10f3a-14a8-442d-ad0b-f79fca5e086b.png)
![image](https://user-images.githubusercontent.com/60176594/154841049-9fee2d1b-2028-4684-a108-19a9f1e755b6.png)
![1645357849(1)](https://user-images.githubusercontent.com/60176594/154841096-88518dcf-045a-4992-b073-ef69187de835.png)
![image](https://user-images.githubusercontent.com/60176594/154841103-b2784e87-6720-44b2-ac8c-fe345775f1f3.png)

**Comment by wl1532502541** [comment]
我想我找到原因了，当只有一个颜色的时候添加的色板（代码见图2）没有添加'draggable:true',也没有将用户设置的style放进去（如图1），请问这是疏忽还是有别的考虑特意这么写的。有可能原本的考虑是已有的circle有这2个属性，但被层级在更上面的色板给覆盖掉了所以点不了。
源代码链接：https://github1s.com/antvis/G6/blob/6c0bc69e213705e0f6a0eff0d9c0cc59da6bd9a0/packages/element/src/nodes/donut.ts
![image](https://user-images.githubusercontent.com/60176594/154942014-24ca132b-39c0-4568-bfa7-81837c131131.png)
![image](https://user-images.githubusercontent.com/60176594/154941861-14f1fe09-72e8-4923-8e06-a77af09f2595.png)

**Comment by Yanyan-Wang** [comment]
谢谢报告，我们会尽快修复
