### ISSUE TITLE
graph.updateBehavior在第二次执行时不生效

### ISSUE THREAD

**Issue by colaiven** [antvis/G6#3530]
### Describe the bug

我在vue2.0中使用
```
var  i = 1;
test(){
        const direction = i % 2 === 0 ? 'x':'y';
        console.log(direction)
        this.graph.updateBehavior('drag-canvas', { direction: direction }, 'default');
        i++;
}
````
第一次执行test()，更改了拖拽画布的方向为X，第二次再执行时，输出为Y，但拖拽还是只能X，我试过了在第二次更改Mode的其他配置项都不会生效。
目前我的解决方法是先removeBehaviors()，再addBehaviors()，这样每次执行都是有效果的！

### Your Example Website or App

还在开发中

### Steps to Reproduce the Bug or Issue

1.设置默认的Mode  并设置Behavior
2.使用updateBehavior更改默认Mode  Behavior的配置项

### Expected behavior

每次updateBehavior都应该生效

### Platform

- OS: Windows
- Browser: edge
- Version: 98.0.1108.56 (官方内部版本) (64 位)

### Additional context

万分感谢

**Comment by Yanyan-Wang** [comment]
请提供下在线复现 demo 呢

**Comment by colaiven** [comment]
> 请提供下在线复现 demo 呢

抱歉  是我使用问题，我是先updateBehavior再setMode导致的  
打扰了

**Comment by colaiven** [comment]
> 请提供下在线复现 demo 呢

抱歉  是我使用问题，我是先updateBehavior再setMode导致的  
打扰了
