### ISSUE TITLE
Invert enableDelegate

### ISSUE THREAD

**Issue by monolithed** [antvis/G6#3532]
### 问题描述

The current behavior looks like an [anti-pattern](https://ant.design/docs/spec/direct#Drag-and-Drop) and is not expected in most cases. 
I suggest changing the behavior or adding an option to invert it (move target node instead of empty rectangle):

<img width="1052" alt="Screenshot 2022-02-23 at 00 49 17" src="https://user-images.githubusercontent.com/803674/155225851-f4ed3f80-6e96-49b4-8e10-858c08799046.png">

**Comment by Yanyan-Wang** [comment]
Thanks for your suggestion. We welcome contributors from communities to contribute the feature~

**Comment by cliffordfajardo** [comment]
@monolithed - can you add more context regarding this issue?

For example
- Where does this image come from? (is that an image from your own app, G6 docs?)
- What G6 API's are you using or referring to?
- Can you provide a reproducible codesanbox of this issue?

Editing your original question would be helpful and give other readers & G6 team more context about the situation as not everyone has context or familiarity with your unique situation

Thanks 🙏

**Comment by monolithed** [comment]
@cliffordfajardo 
>  Where does this image come from? (is that an image from your own app, G6 docs?)

It's a hand made image :) 

> Can you provide a reproducible codesanbox of this issue?

https://codesandbox.io/s/tender-flower-sueryz

The current behaviour is:

![Group 11](https://user-images.githubusercontent.com/803674/156901215-2959c73f-f2cb-4d34-a863-6528e259caeb.png)


The suggested behaviour is:

![Group 22](https://user-images.githubusercontent.com/803674/156901230-062ffd4d-3498-4f31-849d-226000e9f8cb.png)
