### ISSUE TITLE
arc类型边无法选中

### ISSUE THREAD

**Issue by colaiven** [antvis/G6#3535]
### Describe the bug

见视频文件

### Your Example Website or App

还在开发中

### Steps to Reproduce the Bug or Issue

见视频

### Expected behavior

无

### Screenshots or Videos

https://user-images.githubusercontent.com/46585176/155291982-65eed109-5e3e-4fb4-9a68-c77c1eb8c4b6.mp4

### Platform

- OS: Windows
- Browser: Chrome

**Comment by Yanyan-Wang** [comment]
arc 边是带有 ‘A’ 标签的路径图形，底层渲染引擎在这种路径的事件上存在一定问题。建议换成 quadratic 或者 cubic 类型的边。

**Comment by Yanyan-Wang** [comment]
非常抱歉，当前版本(3.x、4.x)依赖的底层渲染引擎暂时不会考虑 SVG 问题的修复，渲染引擎目前正在大升级，我们也将在新版本接入新渲染引擎，届时应当可以解决 SVG 各种 bug
