### ISSUE TITLE
graph.updateItem()更新节点label position，显示出现偏移

### ISSUE THREAD

**Issue by colaiven** [antvis/G6#3536]
### Describe the bug

使用graph.updateItem取更新任意节点的label的position，显示出现偏移
![image](https://user-images.githubusercontent.com/46585176/155320632-7f49bce0-92cb-4a52-9b69-dc6862ddb34c.png)
完整代码见step

### Your Example Website or App

还在开发中

### Steps to Reproduce the Bug or Issue

```java
import G6 from '@antv/g6';

const data = {
  nodes: [
    {
      id: 'circle0',
      label: 'Circle',
      x: 250,
      y: 150,
    },
  ],
};

const width = document.getElementById('container').scrollWidth;
const height = document.getElementById('container').scrollHeight || 500;
const graph = new G6.Graph({
  container: 'container',
  width,
  height,
  fitCenter: true,
  defaultNode: {
    type: 'circle',
    size: [90],
    labelCfg: {
      position: 'bottom',
    },
    icon: {
      show: true,
    },
  },
});

graph.data(data);
graph.render();

const positions = ['center','right','top','left','bottom'];
let i = 0;
setInterval(function(){
   graph.updateItem("circle0", {
      id: 'circle',
      label: 'Circle',
      labelCfg:{
        position:positions[i]
      },
      x: 250,
      y: 150,
    });
    i++;
    if(i>4){
        i=0
    }
},1000)

```

### Expected behavior

试过render能解决问题  但是我的图表中存在大量图片节点，而我只想更新某一个节点label的位置，全图render不太科学

### Screenshots or Videos

https://user-images.githubusercontent.com/46585176/155321191-5f5b43c4-cc6f-4e36-bd08-7f3762d5759a.mp4

### Platform

- OS: Windows

### Additional context

none

**Comment by Yanyan-Wang** [comment]
duplicated to https://github.com/antvis/G6/issues/3513
