### ISSUE TITLE
请问如果实现边 连接 另一边的中间呢？

### ISSUE THREAD

**Issue by xueshixiang** [antvis/G6#3537]
### 问题描述

如题，看了官方的文档没有找到对应的例子。

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

<img width="301" alt="Snipaste_2022-02-24_01-24-49" src="https://user-images.githubusercontent.com/39337448/155373187-52473488-ca97-4c70-b424-9c4a43f90a29.png">

**Comment by Yanyan-Wang** [comment]
不可以，关系图上，关系（边）是连接实体（节点）的
