### ISSUE TITLE
plugin menu如何异步加载数据？

### ISSUE THREAD

**Issue by solfKwolf** [antvis/G6#3538]
### 问题描述

部分场景下，menu需要展示的内容是异步获取。menu插件似乎并没有钩子在渲染菜单内容前来正常加载数据

### 重现链接

无

### 重现步骤

 无

### 预期行为

希望menu能支持异步加载

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
没看懂诶，你能具体描述下吗，举个例子，提供下在线 demo 之类的
