### ISSUE TITLE
更新边属性defaultEdge方法有吗

### ISSUE THREAD

**Issue by xiahongyuan** [antvis/G6#3544]
### 问题描述

更新边属性defaultEdge方法有吗

### 重现链接

 CodeSandbox

### 重现步骤

，，

### 预期行为

。

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by garygao12580** [comment]
可以试试 `graph.set('defaultEdge', {})`

**Comment by Yanyan-Wang** [comment]
更新全局的 defaultEdge 可以用楼上的办法。更新单个节点 graph.updateItem
