### ISSUE TITLE
旋转有连线的节点，如何更新连线的连接点？

### ISSUE THREAD

**Issue by hushaoyu** [antvis/G6#3547]
### 问题描述

旋转节点后，节点之间的连线没有跟随旋转进行变化。

### 重现链接

https://codesandbox.io/s/g6-update-star-lic2pj?file=/src/App.js:3324-3332

### 重现步骤

点击旋转矩形，移动矩形，矩形之间的连线没有跟随旋转进行旋转。

### 预期行为

节点旋转后，节点之间的连线自动跟随旋转进行定位。

### 平台

- 操作系统: Windows
- 网页浏览器: Google Chrome 98.0.4758.102
- G6 版本: 本地环境 G6 4.3.4

**Comment by Yanyan-Wang** [comment]
不支持，可以去改节点的 anchorPoints https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/anchorpoint/#gatsby-focus-wrapper

**Comment by hushaoyu** [comment]
> 不支持，可以去改节点的 anchorPoints https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/anchorpoint/#gatsby-focus-wrapper

可以的，感谢！

**Comment by zzjjbbaa** [comment]
> > 不支持，可以去改节点的 anchorPoints https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/anchorpoint/#gatsby-focus-wrapper
> 
> 可以的，感谢！

大哥，你怎么解决的
