### ISSUE TITLE
Combos -- On initial page, combos are rendered much  larger than required

### ISSUE THREAD

**Issue by cliffordfajardo** [antvis/G6#3550]
### Describe the bug
When I load the page, my combo's size's are rendered really big, but after I drag a combo, the canvas repaints and renders the all the combo's in the more appropriate correct looking size

### Your Example Website or App
- https://codesandbox.io/s/elastic-shaw-nwc3m3?file=/index.js

### Steps to Reproduce the Bug or Issue
1. Load the page & observe that the combo sizes are really big, despite `collapsed: true` enabled on combo object.
2. Drag any combo on the page to trigger a repaint of the layout, which will repaint the combos in their correct size

I have also tried the following: 
- I also tried using different layouts, `comboForce`, `grid`, `comboCombined` and the same behavior occurs, regardless of the layout.
- I have specified `x` and `y` values for my combos
- I have enabled / disabled adding a default size to the combo like this: `defaultCombo : {size: 40, ...}`, but still has no effect

For example:
https://codesandbox.io/s/elastic-shaw-nwc3m3?file=/index.js

https://user-images.githubusercontent.com/6743796/156073401-e41b4556-a316-404a-81cf-4a6b1a03253e.mp4

### Expected behavior
As a user using Combos, i expect that the canvas renders the combos in their correct size, otherwise it becomes really confusing trying to expand a combo and then see it shrink like this:

<details>
<summary>Demo video</summary>

https://user-images.githubusercontent.com/6743796/156074548-01a0d824-aa9d-49bc-a990-44afd45a62fb.mp4
</details>

### Platform
- G6 version: 4.6.0-beta4 (happening for non-beta versions as well)
- OS: MacOS
- Browser: Google Chrome latest version
- Version:  98.0.4758.109

**Comment by Yanyan-Wang** [comment]
Looks like the combos were not updated correctly with initial collapsed and layout. I will fix it ASAP. You could solve this problem temporary by call the following lines after graph.render()

```
setTimeout(() => {
  graph.getCombos().forEach(combo => {
    graph.updateCombo(combo);
  })
}, 0);
```

**Comment by cliffordfajardo** [comment]
@Yanyan-Wang - it looks like this commit solved this issue - thank you
- https://github.com/antvis/G6/pull/357

BEFORE (left side) ---- AFTER (right side)
https://user-images.githubusercontent.com/6743796/158395245-d0fd6123-7a50-433d-b8a0-15600381dd78.mp4
