### ISSUE TITLE
Combos -- `relayout:true` causes nodes to disappear from view

### ISSUE THREAD

**Issue by cliffordfajardo** [antvis/G6#3551]
### Describe the bug
When collapsing an open combo, when `relayout: true` is enabled, it causes all other combos in view to disappear from view  despite that there is space in view to keep them in view

### Your Example Website or App
- https://codesandbox.io/s/icy-snowflake-nqdzxx

### Steps to Reproduce the Bug or Issue
1. Load the codesandbox.
2. Collapse one of the open combos by double clicking on it
3. After combo shrinks, all other combos that were previously in view dissapear

Codesanbox: https://codesandbox.io/s/icy-snowflake-nqdzxx?file=/src/index.tsx

https://user-images.githubusercontent.com/6743796/156076437-cce0fa9f-1670-4e85-aa24-11060cb4f8fb.mp4

### Expected behavior
When `relayout: true` is set, it should not cause combos that we're previously in view to completely go out of view, especially if there is sufficient space in the canvas viewport to keep the combo in view.
- [G6 Combo Relayout documentation](https://g6.antv.vision/en/docs/manual/middle/elements/combos/defaultCombo#collapse-expand-combo)

### Platform
- G6 version: 4.6.0-beta4 (happening for non-beta versions as well)
- OS: MacOS
- Browser: Google Chrome latest version
- Version:  98.0.4758.109

**Comment by cliffordfajardo** [comment]
Question
Is the behavior of `relayout: true` suppose to look something like this ideally?

## Concepts (not from G6)

![CleanShot 2022-01-10 at 19 20 40](https://user-images.githubusercontent.com/6743796/148875745-3030527a-5309-42b1-bf64-f470f031893c.gif)

![CleanShot 2022-02-28 at 15 48 41](https://user-images.githubusercontent.com/6743796/156078156-c6e48105-c292-482e-ada4-99e0909abaa5.gif)

## References
- [Circular combo example](https://cambridge-intelligence.com/spot-alerts-network-topologies-graph-visualization/)
- [rectangular combo example](https://cambridge-intelligence.com/product-updates-rectangular-combos/)

**Comment by Yanyan-Wang** [comment]
After collapsing/expanding, the size of the combo changes, and the layout is re-calculated according to the current conditions, e.g. size of combos, visible nodes and edges, etc. That leads to the position changes of the 'disappear' items. Turn on animate: true on the graph instance you will see the position changing.

Actually, it should be optimized to keep the continuity of observation. The comboForce should consider to enlarge the 'mass' of the unchanged items to keep the positions as much as possible. I will try to optimize it

**Comment by Yanyan-Wang** [comment]
Use `'comboCombined'` instead with latest version of @antv/layout and @antv/g6. `'comboForce'` is not suggested anymore since it does not perform well on most real cases.

And I will try to add some demos to the website as the videos you provided . Follow the progress about it on the issue https://github.com/antvis/G6/issues/3588
