### ISSUE TITLE
请问一下，力导向布局时数据量大，布局每次都在不停的计算节点xy坐标，然后刷新视图就会很卡顿，在哪里修改能避免这样，在所有节点计算完成后再一次性布局

### ISSUE THREAD

**Issue by xiahongyuan** [antvis/G6#3552]
### 问题描述

请问一下，力导向布局时数据量大，布局每次都在不停的计算节点xy坐标，然后刷新视图就会很卡顿，在哪里修改能避免这样，在所有节点计算完成后再一次性布局

### 重现链接

 CodeSandbox

### 重现步骤

。

### 预期行为

。。

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]
。

**Comment by Yanyan-Wang** [comment]
gFroce、fruchterman 可以开启 webworkerEnabled 或者 gpuEnabled，达到关闭动画的效果。在 g6 v4.6.0 版本中你还可以为 gForce 配置 animate: false 来关闭动画

**Comment by Yanyan-Wang** [comment]
最近新增了 force2， 性能不错哦，欢迎试用。force2 页可以通过 animate: false 来关闭布局动画


尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
