### ISSUE TITLE
节点Icon颜色是否可以自定义或能否支持icon类型

### ISSUE THREAD

**Issue by Miever1** [antvis/G6#3553]
### 问题描述

想在节点hover的时候更改icon的颜色，现在circle中的icon好像只支持图片，用起来及其不方便

### 重现链接

https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/built-in/circle/#%E5%9B%BE%E6%A0%87-icon

### 重现步骤

如题

### 预期行为

希望可以更改节点icon颜色

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
可以用 icon 的，详见文档：https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/built-in/circle/#%E5%9B%BE%E6%A0%87-icon

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
