### ISSUE TITLE
animated edge 在图表销毁/react component销毁之后依旧还在

### ISSUE THREAD

**Issue by IsKaros** [antvis/G6#3555]
### 问题描述

元素动画中，边上做点的动画在react组件销毁，切换页面之后还是有在做动画。
这个可以通过浏览器的开发者工具-性能面板可以看到一直有占用cpu。官网的demo就有这个问题。

### 重现链接

https://antv-g6.gitee.io/zh/examples/gallery#category-%E8%BE%B9%E5%8A%A8%E7%94%BB

### 重现步骤

1.进入带有边动画的页面
2.图表渲染完后，返回上一个页面
3.打开开发者工具的performance面板

### 预期行为

我期望组件销毁之后动画就不再执行，图表相关的任何动画都不再执行。实际却是切换页面的时候，动画还是在进行，CPU被占用，当动画的边特别多的时候，CPU占用率会很高。

### 平台

- 操作系统: [ Windows]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.0.3 ]

### 屏幕截图或视频（可选）

![performance](https://user-images.githubusercontent.com/45893455/156318535-da70e091-0180-4c62-ac2d-df0c8a4e7c90.png)

**Comment by damnright** [comment]
同样遇到了这个问题   目前的解决方法是销毁时手动调用shape.stopAnimate();
但及时是这样   定时器timer依然在运行并占用cpu
![捕获2](https://user-images.githubusercontent.com/17570651/178956671-aa2c5e3e-be9a-4b83-b8bb-c1ab2d5f37da.PNG)

**Comment by ShowCreator** [comment]
我也遇到相同情况手动调用shape.stopAnimate();   任然还占有少量cpu
