### ISSUE TITLE
ModelRect logoIcon 支持动态的svg图么，比如动态的loading

### ISSUE THREAD

**Issue by sampsonliu** [antvis/G6#3556]
### 问题描述

ModelRect logoIcon 支持动态的svg图么，比如动态的loading

### 重现链接

https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/built-in/modelRect

### 重现步骤

如题

### 预期行为

ModelRect logoIcon 支持动态的svg图么，比如动态的loading

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
可以试试放一个 gif，不行的话可以自己控制动画

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
