### ISSUE TITLE
Unable to parse color from object [247,249.7,255]

### ISSUE THREAD

**Issue by shangeyao** [antvis/G6#3557]
### Describe the bug

Only import G6 from '@antv/g6', then cause the error below:
![image](https://user-images.githubusercontent.com/42203474/156505759-27416f8b-98cb-4dbf-ae7d-8f8eef808ce0.png)

### Your Example Website or App

Above

### Steps to Reproduce the Bug or Issue

Above

### Expected behavior

Above

### Platform

- OS: macOS
- Browser: Chrome
- Vue version: 2.5.17
- g6 version: 4.6.0

**Comment by Yanyan-Wang** [comment]
How did you assign color?

We support string like 'rgb(rvalue, gvalue, bvalue)' or hexadecimal string format color

**Comment by lonelyzou** [comment]
@shangeyao 老哥解决了吗，我按照官方案例也是报这个错

**Comment by Yanyan-Wang** [comment]
在线复现 demo 给下呢？

**Comment by lonelyzou** [comment]
我预估的没错的话好像是color.js这个包搞的鬼

**Comment by Yanyan-Wang** [comment]
> > 我预估的没错的话好像是color.js这个包搞的鬼
> 
> 请问一下怎么解决的？

发个在线复现 demo 看下？

**Comment by seveneElevenup** [comment]
vue版本：2.5.2
g6版本：4.7.14

***@***.***/g6";



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/G6"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月18日(星期五) 下午5:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [antvis/G6] Unable to parse color from object [247,249.7,255] (Issue #3557)





   
我预估的没错的话好像是color.js这个包搞的鬼
  
请问一下怎么解决的？
  
发个在线复现 demo 看下？

**Comment by seveneElevenup** [comment]
> > > 我预估的没错的话好像是color.js这个包搞的鬼
> > 
> > 
> > 请问一下怎么解决的？
> 
> 发个在线复现 demo 看下？

vue版本：2.5.2
g6版本：4.7.14
引入g6即报错。import G6 from "@antv/g6";
报错：vue-router.esm.js:2113 Error: Unable to parse color from object [247,249.7,255]
    at new Color (index.js:49:1)
    at Color (index.js:11:1)
    at mixColor (color.js:12:15)
    at getColorsWithDefaultTheme (color.js:21:1)
    at getColorsWithSubjectColor (color.js:154:1)
    at ./node_modules/_@antv_g6-pc@0.7.14@@antv/g6-pc/es/global.js (global.js:5:41)
    at __webpack_require__ (bootstrap 48dee3b9b7a5536a6709:707:1)
    at fn (bootstrap 48dee3b9b7a5536a6709:112:1)
    at ./node_modules/_@antv_g6-pc@0.7.14@@antv/g6-pc/es/graph/graph.js (graph.js:1:1)

**Comment by seveneElevenup** [comment]
> > > 我预估的没错的话好像是color.js这个包搞的鬼
> > 
> > 
> > 请问一下怎么解决的？
> 
> 发个在线复现 demo 看下？

@Yanyan-Wang 
![image](https://user-images.githubusercontent.com/50972125/202674874-1ee854d8-c6a2-4d53-b37b-f1d383315450.png)

**Comment by seveneElevenup** [comment]
在react中是正常的哦

**Comment by Yanyan-Wang** [comment]
需要看下这个颜色的数组一开始是怎么传进去的，大家给个在线复现 case 吧？

**Comment by ruinuola** [comment]
我也遇到了同样的问题，换个版本重新安装一下就好了

**Comment by zhangshengpeng** [comment]
这个问题还没修好吗，我装的4.8.23版本还存在这个问题，哪个版本是好的
