### ISSUE TITLE
使用dagre布局，当节点的宽度不同时，不能正确居中

### ISSUE THREAD

**Issue by brinkr** [antvis/G6#3559]
### 问题描述

![image](https://user-images.githubusercontent.com/17120037/156524251-abc73044-3efb-43b1-a3a2-331bf2fc6ffb.png)
如图所示，中间的"+"节点因为宽度和其他节点不一样，其实是左对齐的，怎样设置成居中，和“开始”“结束”两个节点同一个中轴线？

### 重现链接

无

### 重现步骤

如图

### 预期行为

如图所示

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/17120037/156524251-abc73044-3efb-43b1-a3a2-331bf2fc6ffb.png)

**Comment by Yanyan-Wang** [comment]
尝试将自定义节点的自身坐标原点移动到中心，及节点内部所有图形的 x 减去节点宽度一半，y 减去节点高度一半

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。

**Comment by ealldy** [comment]
> 尝试将自定义节点的自身坐标原点移动到中心，及节点内部所有图形的 x 减去节点宽度一半，y 减去节点高度一半

节点内有很多其他的图形的话，整体位移很麻烦，能对group进行位移吗

**Comment by ealldy** [comment]
> 尝试将自定义节点的自身坐标原点移动到中心，及节点内部所有图形的 x 减去节点宽度一半，y 减去节点高度一半

@Yanyan-Wang 请问如何对自定义节点的自身左边进行移动？
