### ISSUE TITLE
Error: 'GridLayout' is not exported by node_modules/_@antv_layout@0.2.0@@antv/layout/lib/index.js, imported by node_modules/_@antv_g6-pc@0.6.0@@antv/g6-pc/es/layout/index.js

### ISSUE THREAD

**Issue by feylee** [antvis/G6#3560]
### 问题描述

![image](https://user-images.githubusercontent.com/37130608/156707809-901ed377-6892-4680-ab1b-e79004d53e57.png)
Error: 'GridLayout' is not exported by node_modules/_@antv_layout@0.2.0@@antv/layout/lib/index.js, imported by node_modules/_@antv_g6-pc@0.6.0@@antv/g6-pc/es/layout/index.js

### 重现链接

无

### 重现步骤

本地构建失败
tnpm run build

### 预期行为

npm包更新为最新的版本，构建失败
使用指定的版本可构建成功
![image](https://user-images.githubusercontent.com/37130608/156708734-f66d6832-7b7c-48d9-b1ba-e157f098d164.png)

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by AlphaYoung111** [comment]
同样问题，我还在打包的时候使用skipLibCheck也不行，请问问题解决了嘛

**Comment by TT527** [comment]
@Yanyan-Wang

**Comment by TT527** [comment]
> 同样问题，我还在打包的时候使用skipLibCheck也不行，请问问题解决了嘛

目前就在包里那个报错的index.js/ts 引入 from '@antv/layout/lib' -> 改成 from '@antv/layout'

**Comment by AlphaYoung111** [comment]
将g6锁定版本未4.5.0好像就可以了

**Comment by wangyq0313** [comment]
"@antv/g6": "4.3.5", 可以
