### ISSUE TITLE
期望legend图例插件可以动态修改值，现在设置后，展示不正确

### ISSUE THREAD

**Issue by SunnyWWQ** [antvis/G6#3561]
### 问题描述

legend图例无法动态改变data，设置后出现图例叠加的情况

### 重现链接

https://codesandbox.io/s/9eq6ws

### 重现步骤

1. 设置legend
2. 使用legend.changeData()，给legend替换新值

### 预期行为

期望legend图例插件可以动态修改值，现在设置后，多个图例重叠

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.2 ... ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/30210239/156712521-ecdaa1fb-25dc-4217-98c1-4789f728f8c9.png)

**Comment by 12138mICHAEL1111** [comment]
请问这有解决办法吗

**Comment by gouzixing** [comment]
同问 这个问题可以解决吗 btw 楼上有人有替代解决方案吗
