### ISSUE TITLE
node节点里面是图片的时候，拖动改变节点位置，再使用 撤销 工具，图片会消失

### ISSUE THREAD

**Issue by donzel-lin** [antvis/G6#3564]
### 问题描述

node节点里面是图片的时候，拖动改变节点位置，再使用 撤销 工具，图片会消失

### 重现链接

https://codesandbox.io/s/eloquent-http-9b3u88?file=/index.js

### 重现步骤

设置节点node type为image
移动节点
点击撤销 工具

### 预期行为

撤销后，图片可以正常展示

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by xiohao** [comment]
大佬，解决了吗？求方法

**Comment by Aarebecca** [comment]
在最新 4.x 版本中，该问题已修复。
