### ISSUE TITLE
Support for edge selection in builtin behavior `click-select` & typo

### ISSUE THREAD

**Issue by leonardodalinky** [antvis/G6#3565]
### 问题描述

您好！我最近在使用 G6 的过程中发现 `click-select` 内置行为只支持 node/combo 的选择，不知道在接下来的几个版本内会不会加入对 edge 的选择。我发现 `brush-select` 中的 `includeEdges` 选项已经满足了这个功能，简单的仿照这个选项拓展一下应该就好了？或者说之后我有时间提个 PR？

还有 `click-select` 的[实现](https://github.com/antvis/G6/blob/master/packages/pc/src/behavior/click-select.ts)中有个小 typo 出现在了 warning 文本中：
```typescript
console.warn(
    "Behavior brush-select 的 trigger 参数不合法，请输入 'drag'、'shift'、'ctrl' 或 'alt'",
);
```
应该改为：
```typescript
console.warn(
    "Behavior click-select 的 trigger 参数不合法，请输入 'drag'、'shift'、'ctrl' 或 'alt'",
);
```

### 重现链接

null

### 重现步骤

null

### 预期行为

null

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
欢迎 pr～
