### ISSUE TITLE
鼠标移入移出节点如何修改鼠标样式？

### ISSUE THREAD

**Issue by qq707631575** [antvis/G6#3569]
### 问题描述

通过修改canvas的cursor并且加上了important都会被g6内置方法给清除，请问如何能修改鼠标样式？

### 重现链接

www.baidu.com

### 重现步骤

G6关系图，鼠标移入移出节点

### 预期行为

希望能修改鼠标样式

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
可以在节点的 style 里面配置 cursor

**Comment by tianqingfish** [comment]
@Yanyan-Wang 怎么在拖动的时候给画布canvas配置 cursor 呢？我尝试在canvas:dragstart事件里去修改最后也会被清除掉。

**Comment by Yanyan-Wang** [comment]
比如说拖拽画布的过程中需要用 'grab'，可以这样做：
```
graph.on('canvas:drag', e => {
  graph.get('canvas').get('el').style.cursor = 'grab'
})
graph.on('canvas:dragend', e => {
  graph.get('canvas').get('el').style.cursor = 'default'
})
```

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。

**Comment by Dawnwangzi** [comment]
@Yanyan-Wang 也许应该是，如果设置了可以拖拽画布，默认的cursor就应该是grab来表示当前是可以拖的状态，而不是grag触发了再去设置成grab。
