### ISSUE TITLE
请教下G6的registerNode中的draw函数返回值类型问题

### ISSUE THREAD

**Issue by ghost** [antvis/G6#3572]
### 问题描述

现在我的自定义节点是由多个path组成的（这些path是从svg多色图标来的，也就是说不同的path，颜色会有些不同）。这些path共同组成了一个节点图标，我把它们都放在一个group里面，也就是说在draw函数中，我先group.addGoup，添加了一个group，然后将这些path，都放到了这个group里，想的是将group作为一个整体的节点返回。

但是现在要求的返回值类型是一个IShape，而不能是一个IGroup，这个有什么办法吗？

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

无

**Comment by zmbxy95** [comment]
补充：我看文档中对返回值的用处说明是：返回一个绘制的图形作为 keyShape，通过 node.get('keyShape') 可以获取。
但是不知道如果只是返回图形的一部分，是否存在某些操作下，对整个节点的操作有些不太友好的影响。

**Comment by Yanyan-Wang** [comment]
keyShape 是作为计算相关边的连接位置、计算节点的包围盒的重要依据。请不要返回“面积”比较小的一部分图形。建议你放一个和你节点内部所有可以认为是组成 keyShape 的图形合并起来的大小差不多的 circle 或者 rect 在你的图形下面，可以设置 opacity: 0 或者设置白色作为背景，然后将这个图形作为 draw 方法的返回值。层级放到最下面的方法是：const keyShape = addShape(...); keyShape.toBack();

**Comment by zmbxy95** [comment]
还有一个问题，自定义节点的draw方法的定义是 `draw: (cfg?: ModelConfig, group?: IGroup) => IShape;`.

在用TS的时候，会发现`cfg`和`group`都是可选输入的，也就是说，在TS的语法检查里，返回值可能是一个IShape或者undefind。想问一下，这个在什么情况下会不提供cfg和group两个参数，如果没有这两个参数，应当如何返回一个IShape。

**Comment by zmbxy95** [comment]
@Yanyan-Wang 哈喽，第一个问题，我已经理解了，第二个问题，方便解惑一下吗？

**Comment by Yanyan-Wang** [comment]
正常情况下应该是两个参数都需要的，不过当时这个类型可能是为了让 draw 方法更自由一些，也可以从 this 拿到不同的图形分组去 addShape。严格一些的话，应该改为不可选
