### ISSUE TITLE
registerCombo中第一个anchorpoint会异常消失

### ISSUE THREAD

**Issue by ly1991** [antvis/G6#3573]
### 问题描述

combo状态变动后，内部第一个锚点就会丢失不再显示
但是combo.getAnchorPoints()依旧可以获取到所有锚点的数据

### 重现链接

https://codesandbox.io/s/empty-cache-f1sjpm?file=/index.js

### 重现步骤

1. 直接拖动combo（或者先后点击combo和画布来切换状态）
2. combo的第一个锚点丢失

### 预期行为

锚点显示正常

### 平台

- 操作系统: [Linux]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.5.3]

**Comment by Yanyan-Wang** [comment]
尝试给 anchorPoint 不同的 name，比如在后面加 index

**Comment by ly1991** [comment]
> 



> 尝试给 anchorPoint 不同的 name，比如在后面加 index



> 尝试给 anchorPoint 不同的 name，比如在后面加 index

尝试了一下，还是会丢失

**Comment by Yanyan-Wang** [comment]
![image](https://user-images.githubusercontent.com/29593318/157804216-22909248-8aca-46ba-906a-a3ea5b2e5b9c.png)


我在这里加了之后就不会了

**Comment by ly1991** [comment]
sorry...我本地的devServer有点问题，重启后发现确实解决了，非常感谢。
