### ISSUE TITLE
图例legend自定义过滤方法filterFunctions在关闭过滤时无法被调用

### ISSUE THREAD

**Issue by 12138mICHAEL1111** [antvis/G6#3574]
### 问题描述

filterFunctions只在第一次点击图例，则开启过滤时被调用，关闭过滤时不会被调用

### 重现链接

https://codesandbox.io/s/filter-issue-v93t5f?file=/index.js

### 重现步骤

代码第39-41行 开启过滤控制台打印111，关闭时不会打印

### 预期行为

期望在关闭过滤时支持调用filterFunctions自定义方法

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
关闭过滤时当然不会调用 filterFunctions 啦

**Comment by 12138mICHAEL1111** [comment]
图例过滤默认是高亮节点，如果我想过滤是使节点消失，需要在filterFunctions调用hide()方法，但是在关闭过滤时，节点并不会重新显示，请问这有什么好的解决方法吗，谢谢🙏

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
