### ISSUE TITLE
Documentation  > Combos  -- `comboCombined` is missing in documentation

### ISSUE THREAD

**Issue by cliffordfajardo** [antvis/G6#3581]
### Describe the bug
The `comboCombined` layout is currently not documented in the G6 docs

### Steps to Reproduce the Bug or Issue
Search for `comboCombined` in the current documentation website: https://g6.antv.vision/en

Specifically:
1. Create a new page entry for `comboCombined` ([similar to `ComboForce` page](https://g6.antv.vision/en/docs/api/graphLayout/comboForce#gatsby-focus-wrapper)) so user's understand how it works and when to use it

2. Add information of the different types of combo layouts of the combo overview page (Graph Elements > Combos)
   - https://g6.antv.vision/en/docs/manual/middle/elements/combos/defaultCombo

### Expected behavior
As a user reading the documentation, i'm not shown that there are different types of combo layouts to use. I accdentally found out about it by reading at the source code while debugging something else unrelated.

### Screenshots or Videos
![CleanShot 2022-03-15 at 07 40 55@2x](https://user-images.githubusercontent.com/6743796/158402821-f5fef2f8-9892-40aa-9560-fcfceed33b72.png)

**Comment by cliffordfajardo** [comment]
I created this issue so I don't forget to revisit this

**Comment by Yanyan-Wang** [comment]
Just updated~ 

https://g6.antv.vision/en/docs/api/graphLayout/comboCombined
