### ISSUE TITLE
请问g6可以获取边的中心位置吗？因为我想在中心点上创建一个 节点

### ISSUE THREAD

**Issue by xueshixiang** [antvis/G6#3583]
### 问题描述

<img width="288" alt="image" src="https://user-images.githubusercontent.com/39337448/158563444-32385082-511a-4c19-b315-d49a15b1d542.png">
请问g6可以获取边的中心位置吗？因为我想在中心点上创建一个 节点。
因为上次问过是，G6 不支持节点去连接边，所以想曲线动态生成一个节点用于连接。
如果是直线中心点很好计算，但是如果多边的情况不知道如何计算了

### 重现链接

无

### 重现步骤

请问g6可以获取边的中心位置吗？因为我想在中心点上创建一个 节点

### 预期行为

获取坐标

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]
macOS,Chrome

**Comment by Yanyan-Wang** [comment]
https://g6.antv.vision/zh/examples/item/customEdge#extraShape
