### ISSUE TITLE
启用 web-worker 后，全局动画丢失

### ISSUE THREAD

**Issue by nishuer** [antvis/G6#3587]
### 问题描述

启用 web-worker 后，全局动画丢失，切换布局或者重新布局，不执行补间动画

### 重现链接

http://10.249.105.67:8099

### 重现步骤

切换布局或者重新布局

### 预期行为

期望启用 web-worker 动画正常，实际没有动画

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
webworker 异步计算，目前没有为它计算完成后增加动画。欢迎社区小伙伴共建

**Comment by Yanyan-Wang** [comment]
当前版本在配置 graph 实例 animate: true 且布局 workerEnabled: true 时，切换布局等会有补间动画～可以在这个 demo 尝试为各个布局加上 workerEnabled: true
https://g6.antv.antgroup.com/examples/net/layoutMechanism/#layoutTranslate
