### ISSUE TITLE
想实现combo不能拖动出父combo范围

### ISSUE THREAD

**Issue by luokerenGIT** [antvis/G6#3589]
### Describe the bug

drag-node事件的设置combo有边界，node按照设想不能拖出去，但是当鼠标移出去之后，combo大小自动变化了，导致node出去了。。
有没有办法不写死combo大小的情况下，鼠标移动出去，不改变combo大小

### Your Example Website or App

https://g6.antv.vision/zh/docs/manual/middle/states/defaultBehavior/#drag-combo

### Steps to Reproduce the Bug or Issue

drag-node事件的设置combo有边界，node按照设想不能拖出去，但是当鼠标移出去之后，combo大小自动变化了，导致node出去了。。
有没有办法不写死combo大小的情况下，鼠标移动出去，不改变combo大小

### Expected behavior

有没有办法不写死combo大小的情况下，鼠标移动出去，不改变combo大小

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/53746488/158952038-edb58f59-800a-4142-81e9-728911347a0a.png)

https://user-images.githubusercontent.com/53746488/158951984-9ba5a577-277f-439a-a794-9a81faf0821e.mp4

### Platform

"@antv/g6": "^4.5.2",

**Comment by luokerenGIT** [comment]
还有个问题shouldBegin事件第一个参数，e的x,y是相对于什么的？例如我的combo里面有一个·node,我拖动node他的y按我的理解一般应该是大于combo的Y的 。为什么刚开始拖动会进入这里？
![image](https://user-images.githubusercontent.com/53746488/158979303-9609c5e9-e4e9-4057-90c6-2568eaccda67.png)

**Comment by Yanyan-Wang** [comment]
drag-node 有参数的呀，onlyChangeComboSize。不用写那么多判断

**Comment by luokerenGIT** [comment]
> drag-node 有参数的呀，onlyChangeComboSize。不用写那么多判断

收到 感谢
