### ISSUE TITLE
canvas渲染模式有办法定义iframe或者携带视频资源的节点吗？

### ISSUE THREAD

**Issue by hushaoyu** [antvis/G6#3592]
### 问题描述

想自定义一类型节点，节点内部可以插入视频资源，或者可以插入展示iframe的节点，但是目前好像没有看到相关的案例，请问有办法实现吗，canvas渲染模式？

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
不支持。另外写个 DOM 浮在 canvas 上面吧。定位方法详见：https://g6.antv.vision/zh/docs/manual/advanced/coordinate-system
