### ISSUE TITLE
star updateLinkPoints 方法在更新link-point-right-bottom时有误

### ISSUE THREAD

**Issue by zylking** [antvis/G6#3593]
### Describe the bug

var markRightBottom = group['shapeMap']['link-point-left-bottom'] || group.find(function (element) {
      return element.get('className') === 'link-point-right-bottom';
    });

if (markRightBottom) {
      if (!rightBottom && rightBottom !== undefined) {
        markLeftBottom.remove();
        delete group['shapeMap']['link-point-right-bottom'];
      } else {
        markRightBottom.attr(__assign(__assign({}, styles), {
          x: x,
          y: -y
        }));
      }
    }

### Your Example Website or App

no

### Steps to Reproduce the Bug or Issue

1.可以先全部显示star的linkPoints
2.在全部隐藏即可发现问题

### Expected behavior

这里就不写了

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 4.6.1]  很多版本都有这个问题

**Comment by Yanyan-Wang** [comment]
感谢报告，会尽快修复

**Comment by Yanyan-Wang** [comment]
v4.6.11 已修复
