### ISSUE TITLE
使用react方式自定义节点时，zIndex和next属性不生效

### ISSUE THREAD

**Issue by foreverfirst** [antvis/G6#3594]
### 问题描述

根据官方文档和示例，使用@antv/g6-react-node包定义自定义节点，发现zIndex和inline属性不生效；

### 重现链接

https://codesandbox.io/s/divine-smoke-k149xx?file=/App.jsx

### 重现步骤

根据官方文档和示例，使用@antv/g6-react-node包定义自定义节点：
1、在两个并列的<Circle/>元素之间，想要通过zIndex属性来改变渲染的层级，结果不生效；
2、在两个并列的<Text/>元素上设置 next:inline 属性，想要达到文本并排的效果，结果不生效（在父元素上使用flex布局有效）；

### 预期行为

元素并没有按照zIndex排序，而是保持代码中的定义顺序 ；

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by mxz96102** [comment]
因为自动布局 next已经失效，请使用flex布局实现，
zIndex在g中的渲染会通过group.sort才生效，所以目前只能按照渲染顺序进行排序

**Comment by iShawnWang** [comment]
same issue here

**Comment by wangxin6688** [comment]
同样不起作用

**Comment by iShawnWang** [comment]
shit bot ~
