### ISSUE TITLE
为什么我在官网扫钉钉二维码不给通过加入呢?需要什么验证吗???

### ISSUE THREAD

**Issue by ATaoyoyo** [antvis/G6#3596]
### 问题描述

扫了两天了,都不给通过,想进去交流学习一下都不行....

### 重现链接

https://g6.antv.vision/zh/docs/manual/introduction#g6-%E5%9B%BE%E5%8F%AF%E8%A7%86%E5%8C%96%E4%BA%A4%E6%B5%81%E7%BE%A4

### 重现步骤

1.进入antv官网
2.在教程简介中找到钉钉群交流二维码
3.打开手机钉钉点击扫码
4.没任何反应- -,拒绝理由都无...

### 预期行为

期望加群,结果无果- -

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by mwh1209** [comment]
是呢是呢

**Comment by ATaoyoyo** [comment]
> 是呢是呢

需要什么验证哇？

**Comment by Yanyan-Wang** [comment]
钉钉群满了哈，并且钉钉群目前不提供答疑呢，都是社区同学自己在讨论。大家使用过程遇到 bug 可以通过 issue 来提哈

**Comment by meiliujun** [comment]
G6 大数据渲染优化类的问题 应该怎么参与进来呢？

**Comment by Yanyan-Wang** [comment]
已更新钉钉二维码
