### ISSUE TITLE
参考 #3478 issue的做法，无法取消水印

### ISSUE THREAD

**Issue by hushaoyu** [antvis/G6#3597]
### 问题描述

参考了 #3478 的做法，但是还是无法手动取消水印。

### 重现链接

https://codesandbox.io/s/crsunz?file=/index.js

### 重现步骤

鼠标移入节点，可以添加水印，但是鼠标移出时，水印无法取消。

### 预期行为

可以正常移除水印。

### 平台

- 操作系统: Windows
- 网页浏览器: Google Chrome 98.0.4758.102
- G6 版本: 本地环境 G6 4.3.4

**Comment by Yanyan-Wang** [comment]
加一行这个试试：
  document.getElementsByClassName('g6-graph-watermarker')[0].remove()

**Comment by hushaoyu** [comment]
> 加一行这个试试： document.getElementsByClassName('g6-graph-watermarker')[0].remove()

可以了，感谢。
