### ISSUE TITLE
force力导向布局拖拽bug

### ISSUE THREAD

**Issue by gongpingwa00** [antvis/G6#3599]
### Describe the bug

![1648193693(1)](https://user-images.githubusercontent.com/23349869/160075570-6df4bff2-d4da-48e3-8755-50afca853219.jpg)

1.官方例子拖拽节点,拖着拖着就不动了,怎样才能让其一直动起来,代码里面在dragstart时用了一次layout,这个layout执行完了就不动了,如果让其一直动,感觉在drag过程中执行layout也不科学,频繁触发layout也是相当耗性能,如果用定时器,由于layout是一个从快到慢的过程,就会出现一腾一腾的样子
2.该例子向下拖拽画布之后,节点不能回到拖拽后画布的位置,比如一个节点开始在画布中间,拖拽后怎样才能让其平滑过渡到中间呢,
3.拖拽节点,如果鼠标移到画布外面去了松开鼠标,再移回画布,目前鼠标是松开状态,但是节点还会跟着鼠标走

### Your Example Website or App

https://antv-g6.gitee.io/zh/examples/case/newsDemo#christmasBubbles

### Steps to Reproduce the Bug or Issue

官方例子
![image](https://user-images.githubusercontent.com/23349869/160075925-e0a8c407-e530-4bda-bf4d-5329744dca3c.png)

### Expected behavior

官方例子![image](https://user-images.githubusercontent.com/23349869/160075925-e0a8c407-e530-4bda-bf4d-5329744dca3c.png)

### Screenshots or Videos

官方例子![image](https://user-images.githubusercontent.com/23349869/160075925-e0a8c407-e530-4bda-bf4d-5329744dca3c.png)

### Platform

chrome

### Additional context

a

**Comment by mxz96102** [comment]
如果要force一直进行不重新调用的话，可以尝试使用alphaMin: -Infinity,这样的配置，只要alphaMin永远都达不到，就会一直tick下去，不需要重新layout

**Comment by Yanyan-Wang** [comment]
看这个例子：https://g6.antv.vision/zh/examples/net/forceDirected#basicForceDirected

或想固定被拖拽的节点，其他节点跟随布局的话，看这个例子：https://g6.antv.vision/zh/examples/net/forceDirected#basicForceDirectedDragFix
