### ISSUE TITLE
新版本去掉了Tooltip了吗？

### ISSUE THREAD

**Issue by liekkas** [antvis/g6#360]
1.0版本还有tooltip，新版本是去掉这个功能了？以后会添加回来吗？

* **G6 Version**: 2.0.4-beta
* **Platform**: MAC OS 10
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by TomHuangCN** [comment]
会，正在加

**Comment by liekkas** [comment]
正用到这块功能，有发布时间吗？太长我就自己做了，谢谢了！

**Comment by TomHuangCN** [comment]
明天会上
