### ISSUE TITLE
使用iconfont自定义节点的时候，和树图嵌套使用的时候，树图怎么设置锚点，以及锚点样式怎么自定义

### ISSUE THREAD

**Issue by luokerenGIT** [antvis/G6#3603]
### 问题描述

使用iconfont自定义节点的时候，和树图嵌套使用的时候，树图怎么设置锚点，以及锚点样式怎么自定义
![image](https://user-images.githubusercontent.com/53746488/160770822-091b9656-3b37-43e3-8612-a1f205ae4ca5.png)

### 重现链接

https://g6.antv.vision/zh/docs/manual/middle/elements/shape/shape-keyshape

### 重现步骤

使用iconfont自定义节点的时候，和树图嵌套使用的时候，树图怎么设置锚点，以及锚点样式怎么自定义

### 预期行为

![image](https://user-images.githubusercontent.com/53746488/160771056-aafb7abc-5ad9-4375-9380-9e848e9d6a41.png)
xi'wang希望通过自定义锚点，结合树形结构实现如图功能

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by luokerenGIT** [comment]
我看了下用getAnchorPoints可以设置锚点，但是好像和我的需求不一样，有没有什么建议，node里面还有很多连接点，用什么方式实现？
用 group.addShape('marker', {
        attrs: {
          x: 80 - w / 2,
          y: 52 - h / 2,
          r: 6,
          stroke: '#ff4d4f',
          cursor: 'pointer',
          symbol: COLLAPSE_ICON,
        },
        name: 'remove-item',
      });这个搞会不会太麻烦，每一个点都要自己画出来

**Comment by luokerenGIT** [comment]
研究了好久，终于解决了，我把思路在这分享下吧。
1.首先要自定义锚点，给每个边设置锚点
![image](https://user-images.githubusercontent.com/53746488/161878348-fecd8d7b-7b69-452b-a1a6-136b749fc56d.png)
2.锚点是没有样式的，只是一个逻辑概念，所以需要在锚点的位置，自定义样式
根据数量，自己算出每个锚点的位置，我这里是分为上下，然后间距等分的算的
![image](https://user-images.githubusercontent.com/53746488/161878469-6ce5451d-89a4-49a1-ad28-c403389c8a1b.png)
3.感谢antv团队，文档如果再细致点就更好了

**Comment by luokerenGIT** [comment]
这个是效果
![image](https://user-images.githubusercontent.com/53746488/161878873-ecd6d8bf-e99f-464e-b1f4-77ef5e747edd.png)

**Comment by MingTang-cn** [comment]
你好，可以分享个连接吗？
