### ISSUE TITLE
dagre布局中设置controlPoints: true后，希望拖动节点时polyline连线的拐点跟着动

### ISSUE THREAD

**Issue by dxchen00** [antvis/G6#3606]
### 问题描述

在dagre布局中，polyline连线设置controlPoints: true后，拐点controlPoints不会随着节点拖动而重新计算拐点位置，导致连线会干扰周围的节点。所以在polyline连线设置controlPoints: true后，如何在节点移动时重新计算controlPoints?

### 重现链接

https://g6.antv.vision/zh/examples/net/dagreFlow#lrDagreUL

### 重现步骤

1.在dagre布局，设置controlPoints: true，使用polyline连线
<img width="552" alt="QQ20220402-112409@2x" src="https://user-images.githubusercontent.com/15138901/161365124-af7b407f-e449-4a66-9454-0459513d6a88.png">

2.拖动节点，连线的拐点不会重新计算位置，导致连线会干扰其他线或节点
<img width="541" alt="QQ20220402-112544@2x" src="https://user-images.githubusercontent.com/15138901/161365126-be1c678e-be52-4730-8a58-151bbddb93e8.png">

3.若设置controlPoints: false，连线不顺畅不自然
<img width="484" alt="image" src="https://user-images.githubusercontent.com/15138901/161365215-cae1eda9-a654-4565-9f17-c7bf06fdb9f0.png">

### 预期行为

希望设置controlPoints: true后，在节点移动时重新计算polyline连线的controlPoints。
（在连线的afterUpdate方法中尝试使用 this.getControlPoints(cfg) 方法计算出来的controlPoints还是旧的）

### 平台

- 操作系统: macOS
- 网页浏览器: Google Chrome
- G6 版本: 4.3.2

**Comment by dxchen00** [comment]
有尝试controlPoints: true之下的其他连线，譬如cubic-horizontal和quadratic，在节点移动时，连线的拐点都会跟着重新计算。
是否是因为polyline没有重写getControlPoints方法？

**Comment by mxz96102** [comment]
polyline在edge如果有controlPoints的情况下不会自己计算controlPoints

而dagre布局直接在算的时候就把controlPoints算进去了，所以解决方案应该是在布局的时候不采用dagre给的定点,controlPoints: false然后根据自己需要重写一下polyline

这里有一段我自己用的
```js
G6.registerEdge(
    'logic-line',
    {
      getPath(points: IPoint[]): (string | number)[][] {
        const startPoint = points[0];
        const endPoint = points[1];
        const deltaY = endPoint.y - startPoint.y;
        return [
          ['M', startPoint.x, startPoint.y],
          ['L', startPoint.x, startPoint.y + deltaY / 2],
          ['L', endPoint.x, startPoint.y + deltaY / 2],
          ['L', endPoint.x, endPoint.y],
        ];
      },
    },
    'line',
  );
```

**Comment by dxchen00** [comment]
自己重写polyline和不使用布局自带的controlPoints效果差不多，都没有dagre布局规划的好看。
我可以在拖动节点时将连线的controlPoints设置为undefined，然后重新计算值吗？

**Comment by mxz96102** [comment]
需要单独去重新布局，不过现在dagre并不支持指定位置布局，我们开发一下试试，或者单独把路径算法抽出来

**Comment by dxchen00** [comment]
> 需要单独去重新布局，不过现在dagre并不支持指定位置布局，我们开发一下试试，或者单独把路径算法抽出来

我可以实现“单独把路径算法抽出来”吗？
是哪部分代码呀

**Comment by Yanyan-Wang** [comment]
> 我可以在拖动节点时将连线的controlPoints设置为undefined，然后重新计算值吗？

这样这些被设置为 undefined 的边应该会使用内置这线的巡径算法，其他没有设置 undefined 还会保留布局为其计算的 controlPoints

 > 3.若设置controlPoints: false，连线不顺畅不自然
 这个是因为这线拐点的半径太大超过了两个节点的间距，可以尝试把 radius 调小点

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
