### ISSUE TITLE
afterrender调用时机问题

### ISSUE THREAD

**Issue by ghost** [antvis/G6#3608]
### 问题描述

目前发现，在初始化`G6.Graph`时，如果指定layout布局，`graph.render()`后会触发`afterrender`事件，但是当不指定任何layout时，`graph.render()`后，并不会触发`afterrender`事件。

请问以下，这个afterrender的触发时机，是有什么说法吗，我看文档中并没有对该事件有更多的描述？对这种行为，也感到有点奇怪。

### 重现链接

无

### 重现步骤

无

### 预期行为

期望可以向API描述的那样，任何时候，调用render后都会触发afterrender事件

### 平台

操作系统: Windows
网页浏览器: Chrome
G6 版本: 4.6.4

**Comment by Yanyan-Wang** [comment]
看了下代码，是在布局完成后调用的，而没有布局的时候，没有完成的时机所以没有调用。这是不合理的，没有布局也应该调用 afterrender。感谢报告，会尽快解决

**Comment by Yanyan-Wang** [comment]
当前版本已无上述问题。记得在 graph.render() 之前进行 graph.on('afterrender', fn) 的绑定噢
