### ISSUE TITLE
关于combo和节点位置的问题

### ISSUE THREAD

**Issue by PeiJM** [antvis/G6#3616]
### 问题描述

查看节点的x和y 和 包裹着节点的combo x和y 对应不上 ，如何获取rect combo四个角的位置，或者是如果节点是相对于combo的话 如何计算 节点的位置！
![image](https://user-images.githubusercontent.com/67719338/162383821-a5cffdc6-babe-4d5c-9d99-2efa37da032b.png)
![image](https://user-images.githubusercontent.com/67719338/162383836-899082a1-17c5-4cc1-b51f-f7e66b8f6c59.png)

### 重现链接

0

### 重现步骤

conbo 内部包裹节点 节点的 x和y 有的不在 combo的 x和y  和x+width 或者y+height 的区间

### 预期行为

想获取节点和 combo的四个角的位置

### 平台

0

**Comment by Yanyan-Wang** [comment]
节点位置和 combo 位置都是相对于画布的，它们的 x y 不是相对的。你的原始需求是什么呢？如果是想获取 combo 的包围盒，可以用 combo.getCanvasBBox() 得到

**Comment by PeiJM** [comment]
> 节点位置和 combo 位置都是相对于画布的，它们的 x y 不是相对的。你的原始需求是什么呢？如果是想获取 combo 的包围盒，可以用 combo.getCanvasBBox() 得到

节点位置和 combo 不都是相对于画布的吧，看下我打印的combo的xy点，上边node的 xy 已经不在combo的坐标范围内了，  我是在做2D 通过 算法转换 计算出 2.5D的坐标点 可以做出伪2.5d的视角， 所以希望了解combo和node的xy的关系，得到combo和Node相对于画布的点，

**Comment by Yanyan-Wang** [comment]
目前的机制是，子元素（子节点/子 combo）、父元素（父 combo）谁最后被更新位置，则另一方跟随变化。例如，在节点数据中设置了` x: nodeX, y: nodeY`，首次渲染，combo 将根据其子节点位置算出能够包裹它们的一个位置 `x: comboX, y: comboY`。后续通过 `graph.updateItem(combo, { x: comboNewX, y: comboNewY })` 更新了父 combo 的位置，那么子节点将按照更新前与 combo 的相对关系，被更新到新的位置上，大概是 `x: comboNewX + comboX - nodeX, y: comboNewY + comboY - node`

如果使用了布局算法，不同的布局可能对不同的元素进行操作。例如 comboCombined ，先计算每个 combo 内部子元素的位置，然后再计算 combo 的位置，所以它的赋值顺序是先内部元素、再 combo。再如 comboForce，它只对所有节点位置赋值，而不控制 combo 位置。

**Comment by Yanyan-Wang** [comment]
比较好奇伪 2.5d 做出来是什么效果？方便分享 demo 吗？也许可以加入到官网中

**Comment by PeiJM** [comment]
> 比较好奇伪 2.5d 做出来是什么效果？方便分享 demo 吗？也许可以加入到官网中

**Comment by PeiJM** [comment]
> 比较好奇伪 2.5d 做出来是什么效果？方便分享 demo 吗？也许可以加入到官网中

![demo](https://user-images.githubusercontent.com/67719338/208287250-1c9f4f6e-ff8a-4dd5-a91b-ba31a62e8baf.jpg)
如果需要的话 可能需要时间整理 因为现在掺杂在项目中。在2D模式下 转换位置后，我项目中不需要改动位置，所以未解决转换后改变位置的问题，转换后拖动会导致边变形，如果需要的话，可以联系我，我抽时间整理！

**Comment by pomelo-nwu** [comment]
@PeiJM 2.5D的效果看起来不错，可以抽取出来吗？
