### ISSUE TITLE
绘制图中对重复节点的支持

### ISSUE THREAD

**Issue by furaul** [antvis/G6#3617]
### 问题描述

我正在使用G6绘制我的场景图，我的场景是绘制整个部门的应用依赖关系。
当前应用依赖环境不能避免出现重复节点。
例如 A->B->C->D->B.
当图加载到第二个B的时候就抛出异常了。
但是我这里希望能够绘制出上述的图，请问有什么配置可以支持吗？
或者在后续版本中打算支持吗？
对于当前G6的源码基本没有阅读，期望解答。

### 重现链接

如问题描述

### 重现步骤

如问题描述

### 预期行为

能够支持重复节点绘制。

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.5.1 ... ]

**Comment by garygao12580** [comment]
这里区分两个概念：图中的节点 和 业务中的部门 是两个维度的概念，也就是 节点ID 和 部门ID 是两个不同的属性。而G6要求图中每一个节点Id唯一，而你恰好直接拿部门ID作为节点ID，因此出现了重复。其实很简单，节点Id和部门ID做一层映射，即生成节点时，让节点ID 等于 部门Id + uuid即可，这样可以保持节点ID的唯一。 如果说这样无法根据节点ID 拿到 部门Id，可以把节点Id和部门ID的关系存起来，比如`{nodeId: departmentId}` ，这样就可以拿到了部门ID了

**Comment by Yanyan-Wang** [comment]
楼上小伙伴正解
