### ISSUE TITLE
计算吸附功能，松开鼠标，矩形位置移动偏移位置

### ISSUE THREAD

**Issue by Summer-Lin** [antvis/G6#3618]
### 问题描述

采用 node:drag 事件进行监听，更新矩形坐标，但松开鼠标的时候，矩形会另外更新坐标数据，达不到吸附效果，请问松开鼠标怎么阻止自动更新坐标

### 重现链接

https://codesandbox.io/s/icy-sound-2isqlv?file=/index.js

### 重现步骤

点击Node2矩形，往Node1矩形的右边靠，判断当接近Node1，则更新Node2的坐标数据，达到吸附效果，但松开鼠标后，Node2会自动更新位置，导致偏离了吸附效果

### 预期行为

松开鼠标怎么阻止自动更新坐标

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome,]
- G6 版本: [4.6.4 ]

**Comment by leekoho** [comment]
前段时间碰到了这个问题，我是在`node:dragend`事件中，把`node:drag`的逻辑再执行了一次解决的

![](https://tva1.sinaimg.cn/large/e6c9d24egy1h15rgpkd43j20yc0rwacy.jpg)

**Comment by Summer-Lin** [comment]
> 前段时间碰到了这个问题，我是在`node:dragend`事件中，把`node:drag`的逻辑再执行了一次解决的
> 
> ![](https://camo.githubusercontent.com/55e4a20c1d09c124e3acbfb391170796f4e488bdf8d4d0d276cb26a7a6d5e720/68747470733a2f2f747661312e73696e61696d672e636e2f6c617267652f65366339643234656779316831357267706b6434336a323079633072776163792e6a7067)

我想到的方案也是在 node:dragend  重新更新一遍坐标数据，但感觉比较鸡肋， 看看作者有没有更好的解决方案

**Comment by Yanyan-Wang** [comment]
我理解这个是脱离原有 drag-node 这个行为的设计的，是否这种情况下就不再使用内置的 drag-node，自己控制节点的拖拽，graph.on('node:drag', e => { graph.updateItem(e.item, { x: e.pointX, y: e.pointY })}); 或者自定义行为完成拖拽和吸附的一系列操作，会更好些。自定义行为文档：https://g6.antv.vision/zh/docs/manual/middle/states/custom-behavior

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
