### ISSUE TITLE
scroll-canvas如何取消按下指定键滚轮切换为缩放

### ISSUE THREAD

**Issue by AT-study2** [antvis/G6#3619]
### 问题描述

使用scroll-canvas时发现按下ctrl会切换为滚轮缩放，有什么办法可以取消掉这个行为吗。（只想要滚动画布，不想要滚动缩放）

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: Windows
- 网页浏览器: Google Chrome
- G6 版本: 4.5.3

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
