### ISSUE TITLE
使用force布局，点击节点进行扩展节点的时候，有一部分边会飞的特别远

### ISSUE THREAD

**Issue by SakiMJ** [antvis/G6#3621]
### 问题描述

使用force布局，点击节点进行扩展节点的时候，有一部分边会飞的特别远，甚至会超过两三个屏幕的距离

### 重现链接

http://kg-inc.igancao.cn:3000/

### 重现步骤

1、进入页面点击搜索节点
2、随机双击节点扩展，观察

### 预期行为

我期望看到 扩展的节点距离图形中心点不超过一个屏幕的距离

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.3.11 ... ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/31894246/162702996-71b49fd4-ee40-497f-a177-f795dcf1cf67.png)

**Comment by whathave** [comment]
> 这里用的什么布局？看起来布局计算没有收敛就被停止了。需要看下你的布局是怎么配置的

您好，我也出现这情况，是force布局，在进行下钻的时候，如果原来画布上江某个节点拖动的比较远，那么新生成的节点就会飞，如何可以避免呀（可以让新生成的节点围绕当前点击的节点）

**Comment by whathave** [comment]
> ### 问题描述
> 使用force布局，点击节点进行扩展节点的时候，有一部分边会飞的特别远，甚至会超过两三个屏幕的距离
> 
> ### 重现链接
> http://kg-inc.igancao.cn:3000/
> 
> ### 重现步骤
> 1、进入页面点击搜索节点 2、随机双击节点扩展，观察
> 
> ### 预期行为
> 我期望看到 扩展的节点距离图形中心点不超过一个屏幕的距离
> 
> ### 平台
> * 操作系统: [macOS, Windows, Linux, React Native ...]
> * 网页浏览器: [Google Chrome, Safari, Firefox]
> * G6 版本: [4.3.11 ... ]
> 
> ### 屏幕截图或视频（可选）
> ![image](https://user-images.githubusercontent.com/31894246/162702996-71b49fd4-ee40-497f-a177-f795dcf1cf67.png)
> 
> ### 补充说明（可选）
> _No response_

您好，我也遇到了该问题，能咨询一下您吗？

**Comment by Yanyan-Wang** [comment]
近期新增了 force2 布局，效果和性能更好，欢迎试用
- demo：https://g6.antv.antgroup.com/examples/net/forceDirected/#basicForce2
- api：https://g6.antv.antgroup.com/api/graphlayout/force2
