### ISSUE TITLE
G6.registerEdge如何根据node节点参数动态修改边的颜色

### ISSUE THREAD

**Issue by kaqiinono** [antvis/G6#3623]
### 问题描述

registerEdge回调函数中并没有注入node节点源数据，无法根据源数据中的状态值动态修改线条颜色

### 重现链接

https://codesandbox.io/s/v26ejx

### 重现步骤

见https://codesandbox.io/s/v26ejx

### 预期行为

节点与节点间的线和箭头颜色，由节点中的源数据状态决定，线的颜色可以通过registerEdge修改，但是registerEdge回调函数中传递的参数中没有node节点源数据(构建图形的树形结构数据中的某一个对象数据)，无法获取节点状态

### 平台

- 操作系统: macOS
- 网页浏览器: Chrome
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/11257690/162884989-c90859c1-47a4-4cc8-b1fc-514ac57c17dc.png)

**Comment by kaqiinono** [comment]
> 

初始化的时候就需要根据数据状态进行颜色的赋值，不同状态使用不同边的颜色，而不是在状态变化的时候修改。

**Comment by garygao12580** [comment]
> 

边在draw方法里是可以拿到 sourceNode 和 targetNode的，这样就可以根据不同的属性、状态设置不同的边信息呀

**Comment by garygao12580** [comment]
> 

在初始化时的 draw方法里，是可以拿到 sourceNode 和 targetNode的，是不是可以解决你的问题
``` 
draw(config) {
  const  {targetNode} = config;
  const targetModel = targetNode?.getModel() as INode;
}
```

**Comment by kaqiinono** [comment]
> 

自定义边不是反而更复杂了吗，还需要自己定义路径

**Comment by garygao12580** [comment]
你这个场景不想调用 `graph.edge`，也就只能自定义draw方法了呀。
自定义边是可以继承已有边的，看你的图 你可以继承  cubic边，然后 拷贝下 源码中 cubic边的draw方法，里面加入自己的逻辑。

**Comment by Yanyan-Wang** [comment]
> 你这个场景不想调用 `graph.edge`，也就只能自定义draw方法了呀。 自定义边是可以继承已有边的，看你的图 你可以继承 cubic边，然后 拷贝下 源码中 cubic边的draw方法，里面加入自己的逻辑。

不需要拷贝代码哈，只需要继承 cubic 之后，把自己的逻辑写在 afterDraw 里面

**Comment by Yanyan-Wang** [comment]
> > 
> 
> 初始化的时候就需要根据数据状态进行颜色的赋值，不同状态使用不同边的颜色，而不是在状态变化的时候修改。

初始化时边颜色随节点颜色，我理解可以做一下简单的数据处理，根据边的 target 找到节点，设置边数据的 style。后面的更新可以根据 @garygao12580 说的两种方法

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
