### ISSUE TITLE
brush-select mousemove冲突

### ISSUE THREAD

**Issue by Summer-Lin** [antvis/G6#3625]
### 问题描述

实例设置了brush-select属性，graph.on监听了 mousedown  ， mousemove， mousemove事件无法触发

### 重现链接

https://codesandbox.io/s/focused-gauss-hoyqcf?file=/index.js

### 重现步骤

1.在空白鼠标左键点击，鼠标左键不松手
2.鼠标移动
3.不松手的情况下，在控制台打印不出mousemove
4.将 brush-select 属性注释掉，重复 1-2步骤，则可以控制台能打印出 mousemove

### 预期行为

brush-select 和 mousemove 能通过某种设置为不冲突

### 平台

- 操作系统: [ Windows]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.6.4 ]

**Comment by Yanyan-Wang** [comment]
拖拽过程中的事件是 dragstart drag dragend
