### ISSUE TITLE
可以禁止节点或combo加入到combo吗

### ISSUE THREAD

**Issue by chen-i** [antvis/G6#3628]
### 问题描述

现在拖动节点或combo到combo里面，会自动加入combo,有没有办法禁止某些节点或combo加入combo?

### 重现链接

无

### 重现步骤

无

### 预期行为

可以禁止节点或combo加入到combo

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by cliffordfajardo** [comment]
I have not tried this before, but I believe what you need to do is:
- setup an event listener for `combo:dragenter`
- inside the event listener, check if the item that is being dragged meets your criteria & if not, prevent the node from being dropped in the combo

Again, I have not tried this out, but I recall reading about this a few weeks ago

**Comment by chen-i** [comment]
> I have not tried this before, but I believe what you need to do is:
> 
> * setup an event listener for `combo:dragenter`
> * inside the event listener, check if the item that is being dragged meets your criteria & if not, prevent the node from being dropped in the combo
> 
> Again, I have not tried this out, but I recall reading about this a few weeks ago
> 
> ## References
> * https://g6.antv.vision/en/docs/manual/middle/elements/combos/defaultCombo#drag-combo
> * https://g6.antv.vision/en/docs/api/Event#combo-interaction-event


Thanks,  I've solved this problem. There's a configuration in the Behavior
[https://g6.antv.vision/en/docs/manual/middle/states/defaultBehavior#drag-node](url)

```
   graph.on('combo:dragenter', (e) => {
        if (condition) {
          console.log('cannot drop')
          .
          .
          .
          graph.updateBehavior(
            'drag-node',
            { onlyChangeComboSize: true },
            'default'
          )
        } else {
          graph.updateBehavior(
            'drag-node',
            { onlyChangeComboSize: false },
            'default'
          )
        }
      })
```
