### ISSUE TITLE
Adjustment of pipes doesn't work.

### ISSUE THREAD

**Issue by mostopalove** [antvis/G6#3629]
### 问题描述

There is no way to automatically align pipes. Determining the starting position does not solve the problem in case of dynamic pipe resizing. If the content of the graph changes, this causes an overlap. (adding new nodes or changing a layer)

The issue was previously described in this [issue](https://github.com/antvis/G6/issues/3434). its solution does not exist.

### 重现链接

https://codepen.io/mostopalove/pen/yLzRJKK

### 重现步骤

1. Go to the site with a live example.
2. Look at the result.

### 预期行为

As a user, I expect different chart layouts to be separate from each other. But they overlap.

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.3.11 ]

**Comment by Yanyan-Wang** [comment]
Hi, sorry for replying late, so busy recently. Please try the new layout 'comboCombined' to see if it meets your requirements: https://codepen.io/Yanyan-Wang/pen/QWQjbpv

The inner and outer layouts could be assign to any other layout algorithms in G6. 

P.S. please upgrade the @antv/g6 and @antv/layout to the latest version.

**Comment by mostopalove** [comment]
@Yanyan-Wang Thank you! This is REALLY cool feature!
I will work right now with this and will write here in the comments all the problems or incomprehensible moments.

From your example, how to understand where is this `comboPadding: 30`?

<img width="664" alt="Снимок экрана 2022-05-14 в 17 39 28" src="https://user-images.githubusercontent.com/49098339/168432935-df08db85-7fde-45e3-841a-e5730f48999f.png">

**Comment by mostopalove** [comment]
@Yanyan-Wang Hello! Do you know how to solve the issue?

**Comment by mostopalove** [comment]
@Yanyan-Wang Hey! Are you here? Help me please or answer something

**Comment by Yanyan-Wang** [comment]
> 1. about comboPadding: 30
the comboPadding means the padding space inside the combo, from the content to the border
![image](https://user-images.githubusercontent.com/29593318/181679247-963c6c88-bda9-49ae-95c3-2999800e8f35.png)

> 2. Can I define own layout for each combo? (In my case I want to change nodes and layout into combo by click, something like collapse-expand but short/full info about nodes)

Did not support that yet. But I think you just want to add some information for collapsed combo? Maybe just update the combo label after combo collapsed. Or see the new feature to add a image for a collapsed combo: https://g6.antv.vision/en/examples/net/comboLayout#comboCombined

> 3. Can I define own layout for each combo? (In my case I want to change nodes and layout into combo by click, something like collapse-expand but short/full info about nodes)

`collapse-expand` is a behavior for TreeGraph. There is another behavior for collapsing/expanding combo named `collapse-expand-combo`, see docs here: https://g6.antv.vision/en/docs/manual/middle/states/defaultBehavior#collapse-expand-combo

**Comment by Yanyan-Wang** [comment]
Hi, dear user. Since there was no response for a long time, we cannot figure out the answer of the problem you described. If there is new progress, feel free to open a new issue.
