### ISSUE TITLE
升级@angular-devkit/build-angular后，节点显示不正常

### ISSUE THREAD

**Issue by CubeAirShip** [antvis/G6#3631]
### 问题描述

前段时间我们项目升级了@angular-devkit/build-angular依赖包，发现画布上节点显示成一个圆点，尝试了从0.802.0-next.0后的所有版本，都有这个问题，请教下是什么原因

### 重现链接

内部系统无法提供

### 重现步骤

1.进入页面
2.拖拽出节点
3.节点显示成一个圆点

### 预期行为

正常显示
![Uploading image.png…]()

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome]
- G6 版本: [3.5.7]

### 屏幕截图或视频（可选）

![Uploading image.png…]()

**Comment by Yanyan-Wang** [comment]
图片显示不出来呢，没有遇到过这个情况，尝试升级 G6 呢？

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
