### ISSUE TITLE
是否支持iconfont symbol 引用

### ISSUE THREAD

**Issue by huxiaoyun** [antvis/G6#3632]
### 问题描述

看官网有 fontfamily 形式，但只支持单色 icon ，symbol 引入的iconfont 可以支持多色icon，不清楚 g6 是否支持，如果支持，可否提供一个demo

https://g6.antv.vision/zh/docs/manual/advanced/iconfont

https://www.iconfont.cn/help/detail?spm=a313x.7781069.1998910419.d8d11a391&helptype=code

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
