### ISSUE TITLE
自定义节点  添加dom 类型 Shape 页面报错

### ISSUE THREAD

**Issue by huxiaoyun** [antvis/G6#3633]
### Describe the bug

页面报错
![image](https://user-images.githubusercontent.com/4345248/163784529-d8931a09-579d-4885-9517-93bdbf7d23c2.png)

![image](https://user-images.githubusercontent.com/4345248/163784846-3fbf04b8-85b5-4aba-9c09-6810ebc06c61.png)

关键代码

![image](https://user-images.githubusercontent.com/4345248/163785046-4a33c1dc-46dd-423b-a7f9-b77061927e27.png)

### Your Example Website or App

https://codesandbox.io/s/sweet-bush-1qkzjs?file=/index.html

### Steps to Reproduce the Bug or Issue

无

### Expected behavior

期望正常展示 dom 元素

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
是不是渲染器设置错了，dom 节点只能在 renderer: 'svg' 生效。但还是建议不要用 svg 和 dom，用 canvas 可以绘制任意图形且性能高很多

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
