### ISSUE TITLE
activate-relations交互模式是否支持对Combo及其子节点关系进行高亮效果

### ISSUE THREAD

**Issue by zhangxilong-43** [antvis/G6#3634]
### 问题描述

activate-relations交互模式默认为：当鼠标移到某节点时，突出显示该节点以及与其直接关联的节点和连线；对于Combo及其子节点的关系是否可以同样支持突出显示。例如，当鼠标移到某节点时突出显示该节点以及与其直接关联的节点和连线，以及其所在的Combo；当鼠标移到某Combo时突出显示该Combo以及其直接关联的节点和连线，以及其内部的子节点。

### 重现链接

https://g6.antv.vision/zh/examples/net/comboForce#basicComboForce

### 重现步骤

1、进入页面https://g6.antv.vision/zh/examples/net/comboForce#basicComboForce
2、将modes.default中添加改'activate-relations'
3、鼠标移到某节点/当鼠标移到某Combo

### 预期行为

鼠标移到某节点-->高亮其Combo以及其直接关联的节点和连线
当鼠标移到某Combo-->高亮其内部node以及其直接关联的节点和连线

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome, Edge]
- G6 版本: [4.6.3]

### 屏幕截图或视频（可选）

无

### 补充说明（可选）

无

**Comment by Yanyan-Wang** [comment]
目前 activate-relations 已经支持 combo 的高亮
