### ISSUE TITLE
清除节点状态或者设置节点状态为false后，缩放画布和拖拽画布节点状态又重现未被清除

### ISSUE THREAD

**Issue by superqueengirl** [antvis/G6#3635]
### Describe the bug

官网图表示例的这个示例即可复现该问题
https://antv-g6.gitee.io/zh/examples/case/largeGraph#index
第一步：打开链接，随便扩展出来一个聚合节点
第二步：随便点击一个真实节点，此时该节点被设置了focus状态，然后滚轮放大或缩小画布，再然后点击画布空白处，focus状态取消。这步没异常。
第三步：再将画布放大或者缩小，然后再点击另一个节点（与上次点击的节点不是同一个），另一个节点有了focus状态。此时再去放大或缩小画布，第一次点击的节点的focus状态又重现出来了。
画布滚轮缩放和拖拽画布都有此现象

### Your Example Website or App

website

### Steps to Reproduce the Bug or Issue

官网图表示例的这个示例即可而且每次必复现该问题
https://antv-g6.gitee.io/zh/examples/case/largeGraph#index
第一步：打开链接，随便扩展出来一个聚合节点
第二步：随便点击一个真实节点，此时该节点被设置了focus状态，然后滚轮放大或缩小画布，再然后点击画布空白处，focus状态取消。这步没异常。
第三步：再将画布放大或者缩小，然后再点击另一个节点（与上次点击的节点不是同一个），另一个节点有了focus状态。此时再去放大或缩小画布，第一次点击的节点的focus状态又重现出来了。

### Expected behavior

官网图表示例的这个示例即可复现该问题
https://antv-g6.gitee.io/zh/examples/case/largeGraph#index
第一步：打开链接，随便扩展出来一个聚合节点
第二步：随便点击一个真实节点，此时该节点被设置了focus状态，然后滚轮放大或缩小画布，再然后点击画布空白处，focus状态取消。这步没异常。
第三步：再将画布放大或者缩小，然后再点击另一个节点（与上次点击的节点不是同一个），另一个节点有了focus状态。此时再去放大或缩小画布，第一次点击的节点的focus状态又重现出来了。
画布滚轮缩放和拖拽画布都有此现象
期望：正常情况下，一个节点被取消focus状态后，那无论画布缩放还是拖拽之类的，该节点的focus状态不应再出现。

### Platform

- OS: [Windows]
- Browser: [Chrome]
- Version: [4.5.5及最新版本都有此问题]

**Comment by ZTaer** [comment]
哎~我就是踩的这个坑
