### ISSUE TITLE
自定义边或节点时如何复用基类型的方法实现

### ISSUE THREAD

**Issue by alistuff** [antvis/G6#3640]
### 问题描述

您好：
**问题描述**
   我这里有一个需求，就是通过自定义边的方式实现边的动画，具体就是在边上添加一个小圆圈，在鼠标移动到节点时这些关联的边的小圆圈就播放沿着边路径移动的动画。

   目前通过了解G6开发文档和https://codesandbox.io/s/woohwy 的例子实现了以上的动画效果和一些交互行为，但在实现自定义交互状态时存在一些实现上的疑惑，希望作者或其他有经验的朋友能解惑一下。

**具体实现**
通过G6.registerEdge自定义边，从cubir-horizontal类型继承，其中setState方法实现如下：
```javascript
const group = item.getContainer()
const keyShape = item.get('keyShape')
const circleShape = group.find((elm) => elm.get('name') === 'circle-shape')

// 自定义的状态
if (name === 'running') {
	if (value) {
		circleShape.show()
		circleShape.animate(
			(ratio) => {
				const tempPoint = keyShape.getPoint(ratio)
				return {
					x: tempPoint.x,
					y: tempPoint.y
				}
			}, {
				repeat: true,
				duration: 3000
			}
		)
	} else {
		circleShape.hide()
		circleShape.stopAnimate()
		const startPoint = keyShape.getPoint(0)
		circleShape.attr('x', startPoint.x)
		circleShape.attr('y', startPoint.y)
	}
}

if (name === 'highlight') {
	// 
}

// 如何调用基类型 'cubic-horizontal'的setState方法实现代码复用
// 而不用在这里复写一些通用的边高亮highlight、边激活active、边选中selected的状态实现
```

### 重现链接

https://codesandbox.io/s/woohwy

### 重现步骤

暂无

### 预期行为

1.我期望在setState方法中调用基类型的setState方法以便复用框架内置实现的一些通用的状态交互行为，但我从官网API或者其他issuse中无法找到类似的问题的解决方案。

2.同时我想了解自定义状态切换时如何实现样式的批量应用和恢复的最佳实践（同时设置颜色、线宽度等多个样式），在官方文档中没有找到相应的如何恢复初始样式状态的实现方法，如果需要通过阅读源码实现的话可能比较低效，而且我觉得这种实现需求是非常常见的，应该有一种比较规范的实现方法。

希望问题能得到解答，谢谢。

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
你说的这种情况确实现在还不支持，只能整个方法复写或者不复写即为继承。所以我理解你这里的需求可以通过更新机制来完成，graph.updateItem(edge, { running: true }); 然后在自定义边中复写 afterUpdate 来实现动画的开关。下个大版本正在考虑更好的自定义继承机制。

如果是状态样式，配置的默认样式和状态样式是可以快速应用和恢复的，状态样式的管理比较复杂，在 G6 内部包装掉了。状态样式配置文档 https://g6.antv.vision/zh/docs/manual/advanced/state-new

**Comment by alistuff** [comment]
感谢回复，我尝试用您提供的思路实现一下
