### ISSUE TITLE
数据量较大时 G6 如何做滚动加载？

### ISSUE THREAD

**Issue by He110te4m** [antvis/G6#3641]
### 问题描述

RT，实际场景中有十几万节点，布局为 4 * n 的矩阵，所有节点会连接到一个根节点中，即边也会有十几万条，此场景下 G6 较为卡顿，有没有相关案例可以做滚动加载？（点击加载更多交互暂不适用）

### 重现链接

无

### 重现步骤

正常渲染数据，数据量较大 G6 卡顿丢帧

### 预期行为

G6 正常渲染不卡顿，不添加额外交互逻辑

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
十几万节点，画出来也完全没法看吧，还是做分页吧，一次性给到 G6 的数据少一些。滚动加载我理解逻辑和分页也一样的，只是鼠标点击换页还是鼠标滚动换页的区别，就是在换页的时候用 graph.changeData 切换数据

**Comment by He110te4m** [comment]
已解决，改用 div + 虚拟滚动

**Comment by kingrome2017** [comment]
大哥，请问有demo吗？改用 div + 虚拟滚动  我也遇到了同样的问题

**Comment by He110te4m** [comment]
> 十几万节点，画出来也完全没法看吧，还是做分页吧，一次性给到 G6 的数据少一些。滚动加载我理解逻辑和分页也一样的，只是鼠标点击换页还是鼠标滚动换页的区别，就是在换页的时候用 graph.changeData 切换数据

从实现角度来说，滚动跟分页可以是一样的，但是体验不一样，滚动是可以同时展示不同页码的数据。

十几万节点的需求是展示，但是会有滚动条。有点像预览 pdf 一样，每页都是一个 canvas，但是滚动时才渲染

**Comment by He110te4m** [comment]
> 大哥，请问有demo吗？改用 div + 虚拟滚动 我也遇到了同样的问题

我直接放弃了 G6，纯 div 渲染

**Comment by kingrome2017** [comment]
> > 大哥，请问有demo吗？改用 div + 虚拟滚动 我也遇到了同样的问题
> 
> 我直接放弃了 G6，纯 div 渲染

大哥纯div的渲染实例 有demo吗，或者实现代码，实在是不知道怎么搞

**Comment by He110te4m** [comment]
> > > 大哥，请问有demo吗？改用 div + 虚拟滚动 我也遇到了同样的问题
> > 
> > 
> > 我直接放弃了 G6，纯 div 渲染
> 
> 大哥纯div的渲染实例 有demo吗，或者实现代码，实在是不知道怎么搞

看看 https://github.com/TanStack/virtual ，里面有很多示例，vue 跟 react 的都有，把数据传进去，然后 for 一下遍历就行
