### ISSUE TITLE
用G6画树状图，拖动画布或者缩放画布，画布上会残留部分拖动前的图的痕迹

### ISSUE THREAD

**Issue by Liwenxiaotao** [antvis/G6#3643]
### 问题描述

用G6画树状图，拖动画布或者缩放画布，画布上会残留部分拖动前或者缩放前的图的痕迹

### 重现链接

无

### 重现步骤

无

### 预期行为

拖动或者缩放画布时，不会残留操作前的树状图

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![微信图片_20220424181343](https://user-images.githubusercontent.com/23007975/164971628-1a16351c-56c4-41f5-ad5c-a3a808cfadc6.jpg)

**Comment by zhaomenglu** [comment]
> 是自定义节点吗？看下节点中的图形有没有非法值的属性呢

我也是这样，就是用汉字，好像就会出现这种情况。
而且初次渲染这样
![image](https://user-images.githubusercontent.com/39189837/170658678-082daa61-8232-4063-b9cd-3cdc32f217a2.png)
拖动一下前边变好了后边会这样
![image](https://user-images.githubusercontent.com/39189837/170658789-ee8f37d4-0c37-4809-a081-f15d0bff2e47.png)
和这个里边一样的用法，https://antv-g6.gitee.io/zh/examples/tree/compactBox#basicCompactBox，就是字变成了汉字和数字的

**Comment by Yanyan-Wang** [comment]
图形中的 x/y/width/height/fontSize 等与图形大小/位置相关的数值型属性若存在小数，也可能造成以上问题。在自定义节点中可以尽量时候 Math.round Math.ceil 等方法取整

**Comment by huabulai** [comment]
> 

no,I let the combo hide ,then the label of the combo will be residual
![image](https://user-images.githubusercontent.com/46225303/182517362-f0d1ac85-550a-4570-95cd-3de259942f2b.png)
![image](https://user-images.githubusercontent.com/46225303/182517417-68a5c295-39ff-4ce3-83a0-334d659d9bdf.png)

my code below:
![image](https://user-images.githubusercontent.com/46225303/182517574-46fd7263-9374-4759-bd41-3701eaa5786c.png)
![image](https://user-images.githubusercontent.com/46225303/182517633-17c3f034-9e78-43a0-8d16-1c3a170cb3f5.png)

**Comment by yuyi919** [comment]
已确认使用中文字符可能会出现此问题
把字体改为monospace问题消失，但不是长久之计

**Comment by Yanyan-Wang** [comment]
遇到以上问题，尝试几个解决方案：
1. 检查节点中的图形，包括文本图形，样式配置中是否存在非法值，例如 null NaN 等；
2. 尽量使用整数座位数值型的样式值，例如 r width height fontSize 等
3. 使用浏览器字体作为 labelCfg.style.fontFamily
4. 给文本增加白色描边，如
labelCfg: {
  style: {
    stroke: '#fff',
    lineWidth: 4
  }
}

5. 以上方法都不奏效，关闭局部渲染 graph.get('canvas').set('localRefresh', false);  这个方法可能导致性能有所降低
