### ISSUE TITLE
自定义节点中tooltip用在节点上的某个shape，formatText不会每次都执行

### ISSUE THREAD

**Issue by JacobMa1996** [antvis/G6#3647]
### 问题描述

![image](https://user-images.githubusercontent.com/13243784/165060215-27652b43-3c64-4d35-bb2c-a356717af77f.png)

### 重现链接

暂无

### 重现步骤

自定义节点中画了某个shape，在tooltip的shouldBegin中可以监听到，但formatText不会每次都执行，导致tooltip展示的数据是错误的

### 预期行为

希望formatText和shoulBegin同步执行

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
formatText 是在 node:mouseenter 的时候执行的哈，它不会冒泡，也就是一进入节点就会执行。你试一下 plugin 的 tooltip，它的 getContent 是在 node:mousemove 的时候会执行，是冒泡的。

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
