### ISSUE TITLE
火狐浏览器上无法正常展示自定义节点

### ISSUE THREAD

**Issue by lcy813306986** [antvis/G6#3648]
### 问题描述

预期在第一次以及后面请求新的数据，火狐浏览器能够正常展示自定义节点，
1.第一次可以正常展示数据；
2.当再次请求数据，更新数据时，自定义节点无法正常展示；数据渲染逻辑：
` if (this.graph) {
      this.graph.read(data)
      this.onResize()
    } else {
      customNode()
      customBehavior({
        onAchorClick: this.onAchorClick,
        onNodeClick: this.onNodeClick,
        onRender: callback
      })
      this.graph = new G6.Graph(this.config);
      this.graph.data(data);
      this.graph.render();
    }`
但是第二次火狐浏览器上无法正常展示数据；

### 重现链接

无

### 重现步骤

![image](https://user-images.githubusercontent.com/18637001/164663506-6fdebb2b-b3a7-478c-928b-5efad8e17353.png)
![2](https://user-images.githubusercontent.com/18637001/164660124-c3a39de8-08b3-46dd-97df-b8175cf878ae.png)
![1](https://user-images.githubusercontent.com/18637001/164660030-6c0d1c0e-c5dd-42ae-8aa4-46b320b164d9.png)

### 预期行为

幸苦帮忙解答一下，万分感谢；

### 平台

- 操作系统: [ Windows]
- 网页浏览器: [Firefox]
- G6 版本: [4.3.4]

**Comment by Yanyan-Wang** [comment]
这个是 svg 渲染器吗？建议用 canvas 哈，svg 可能在火狐存在问题

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
