### ISSUE TITLE
在树状图下,怎么在边的信息里获取targetNode的内容

### ISSUE THREAD

**Issue by web-xp** [antvis/G6#3653]
### 问题描述

![image](https://user-images.githubusercontent.com/59134195/165672987-1d21cbbf-aa68-4880-bb0d-f7d470f5b9ee.png)
![image](https://user-images.githubusercontent.com/59134195/165673077-3b42f51e-27bd-42a0-a284-f55ff452eb0e.png)

获取到空的内容
![image](https://user-images.githubusercontent.com/59134195/165673123-bcfc660c-ba3e-4f19-a7ff-93c8fd71a5bc.png)

### 重现链接

上面描述

### 重现步骤

上面描述

### 预期行为

上面描述

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
原始需求是什么？

**Comment by mjw-git** [comment]
> 
我这边也有这个需求，要求根据targetNode的某个属性值来修改边的颜色，但是获取不到targetNode

**Comment by Yanyan-Wang** [comment]
尽量使用官网上开放的 API，不使用未开放的对象属性

graph.getEdges().forEach(edge => {
  const target = edge.getTarget();
  graph.updateItem(edge, {......})
})
