### ISSUE TITLE
怎么在rect中使用antd的组件

### ISSUE THREAD

**Issue by qiaomusi** [antvis/G6#3654]
### 问题描述

我想要在节点中添加antd的进度条，要怎么做
![image](https://user-images.githubusercontent.com/55944286/165708778-319f3393-7454-4056-8b08-f6d6d565969a.png)

### 重现链接

暂无

### 重现步骤

暂无

### 预期行为

使用antd组件

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
暂不支持哈，也许尝试用 canvas 绘制图形完成

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
