### ISSUE TITLE
Knots leave a trail when moved

### ISSUE THREAD

**Issue by verron16** [antvis/G6#3657]
### Describe the bug

Sometimes, quite often, when nodes are moved, they leave traces like this on the canvas. With what it can be connected? Marked with a red mark

### Your Example Website or App

-

### Steps to Reproduce the Bug or Issue

Add nodes to canvas and move around

### Expected behavior

![image](https://user-images.githubusercontent.com/61470621/166164593-8186e0b7-a6ef-4a21-8eb6-949cd2bd3069.png)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
please check out the attributes for shapes in the custom nodes to avoid invalid values. If it does not work, try:
1. add a bigger white rect as container for a custom node, 1-2 px bigger is enough.
2. if 1 does not work, turn off the local refresh: graph.get('canvas').set('localRefresh', false)

**Comment by Yanyan-Wang** [comment]
It might relates to the non-integer width/height/x/y, maybe you could use Math.ceil to make them be integer

**Comment by Yanyan-Wang** [comment]
Hi, dear user. Since there was no response for a long time, we cannot figure out the answer of the problem you described. If there is new progress, feel free to open a new issue.
