### ISSUE TITLE
4以后的版本按照官网处理IE兼容有问题？ 换成4以下的版本 自定义的edge无法正常显示？

### ISSUE THREAD

**Issue by mwh1209** [antvis/G6#3659]
### 问题描述

4以后的版本按照官网处理IE兼容有问题？ 换成4以下的版本 自定义的edge无法正常显示？

### 重现链接

在自己的项目

### 重现步骤

ie空白 报错 [object Error]{description: "语法错误", message: "语法错误", name: "SyntaxError", number: -2146827286

### 预期行为

正常展示

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [ IE ]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
比较低版本的 IE 应该是无法兼容的…

**Comment by mwh1209** [comment]
ie11唉 4.3版本按照官网的处理方式没生效

**Comment by Yanyan-Wang** [comment]
IE 宣布永久关闭，将来 G6 应该不会再考虑 IE 兼容……
