### ISSUE TITLE
Combo collapse / expand breaks combo-drag mode

### ISSUE THREAD

**Issue by Lc0rE** [antvis/G6#3660]
### Describe the bug

When both modes "collapse-expand-combo" and "drag-combo" are active, the graph is not working properly.
If a combo is collapsed, dragging it will break the whole layout. Also, the connections of the edges will not follow the dragged node.

### Your Example Website or App

https://codesandbox.io/s/friendly-waterfall-n0yxbb?file=/index.js

### Steps to Reproduce the Bug or Issue

1. Go to CodeSandbox example
2. Double click on Combo "Combo D" to collapse it
3. Drag the Combo D node 
4. Notice how the edged are not being rendered correctly when the node is being dragged
5. Notice how the layout is brokenedges

### Expected behavior

As a user, I expect the edged of the node to follow the node I'm dragging.
As a user, I expect that dragging a collapsed combo will not break my layout.

### Original Layout
![image](https://user-images.githubusercontent.com/7023628/166881066-dcf103cc-2c7d-4dc4-bf51-16bf0778cb56.png)

### Collapsed Combo (Combo D)
![image](https://user-images.githubusercontent.com/7023628/166881142-ea3e519a-bc3f-4350-ad1f-4dd3b220e19a.png)

### After-dragging Layout
![image](https://user-images.githubusercontent.com/7023628/166881185-307e7d2c-4eb0-416f-9e56-4e780c2d87f9.png)

### Platform

- OS: Windows / Linux
- Browser: Chrome / Edge (Chromium)
- Version: 100

**Comment by Yanyan-Wang** [comment]
Thanks for reporting.

First, the edges related to combos are updated after dragend with debounce to enhance the performance. We will consider to open the option for user to toggle it in later versions.

Second, could you describe more detailedly how to reproduced the broken layout? I collapsed combo D and drag and drop it all around, did not reproduce the problem

**Comment by Lc0rE** [comment]
Thank you for your answer. Sure, you can find a short capture of what I'm doing at: https://www.loom.com/share/a3a071b9dffe4a729af2409a01f04229

Basically, I'm just collapsing Combo D and slightly dragging it to the right, inside Combo B. But I notice the same behavior (with different results though) when I'm dragging it outside the scope of Combo B.

Any suggestion?

**Comment by Lc0rE** [comment]
Hello. Is there any feedback about this? Could you confirm that it's unexpected behavior and, thence, a bug?

**Comment by cliffordfajardo** [comment]
In case the loom video goes down / I downloaded it and dragged the MP4 file here (github supports mp4 video drops)
https://user-images.githubusercontent.com/6743796/168927667-5a61a224-fcc2-4cfb-ab21-ea12e623f0f8.mp4

**Comment by Yanyan-Wang** [comment]
Hey, v4.6.8 just published. I think the breaking layout problem is solved. And we got a new feature for combo https://g6.antv.vision/en/docs/manual/middle/elements/combos/defaultCombo#collapsedsubstituteicon
