### ISSUE TITLE
circle-running 与 endArrow箭头共存 导致动画偏移

### ISSUE THREAD

**Issue by world56** [antvis/G6#3663]
### 问题描述

```
    type: "circle-running",
    style: {
      stroke: "#0e32ab",
      lineWidth: 1,
      strokeOpacity: 0.4,
      endArrow: { path: G6.Arrow.vee(6, 6, 22), d: 22, fill: "#C9CBD2" },
    },
```

动画球体与箭头同时存在，运动的球体在接近箭头时会偏离运动轨道。

### 重现链接

https://codesandbox.io/s/frosty-bush-ox9z58?file=/src/App.js

### 重现步骤

代码例子已写好

### 预期行为

如果解决此类问题？

### 平台

- 操作系统:macOS
- 网页浏览器: Chrome
- G6 版本: ^4.6.4

### 屏幕截图或视频（可选）

<img width="498" alt="WX20220506-212915@2x" src="https://user-images.githubusercontent.com/37354312/167141063-a0c40e72-b915-41c3-b2c5-466bcaab5dd6.png">

**Comment by xiziliang** [comment]
` { path: G6.Arrow.vee(6, 6, 0), d: 0, fill: "#C9CBD2" }`可以把d去掉

**Comment by world56** [comment]
> ` { path: G6.Arrow.vee(6, 6, 0), d: 0, fill: "#C9CBD2" }`可以把d去掉

<img width="537" alt="image" src="https://user-images.githubusercontent.com/37354312/169755738-93c8c32b-6f39-42ef-90a1-7632d71d155a.png">
箭头又飘逸了

**Comment by xiziliang** [comment]
`{ path: G6.Arrow.vee(6, 6, 0), d: 0, fill: "#C9CBD2" }`这个代码复制过去

**Comment by world56** [comment]
> `{ path: G6.Arrow.vee(6, 6, 0), d: 0, fill: "#C9CBD2" }`这个代码复制过去

牛逼，感谢大佬指点🙏
