### ISSUE TITLE
collapsed:true的节点展开后子节点没有连线

### ISSUE THREAD

**Issue by changxia** [antvis/g6#367]
g6-editor 2.0 mind如果初始数据中有collapsed:true，节点展开后，edge没有

![image](https://user-images.githubusercontent.com/17564143/42669481-4f83ef9e-8688-11e8-987e-43e1d0a8f889.png)

debug发现是底层g6代码edge.js中，getTarget判断逻辑导致子节点返回的target都是parent，在画线时不会画子节点的连线

**Comment by TomHuangCN** [comment]
2.0.4 已经解决
