### ISSUE TITLE
fitView不生效

### ISSUE THREAD

**Issue by TrumanDu** [antvis/G6#3672]
### Describe the bug

```
onClick={() => {
                setFocusIndex(index);
                try {
                  setMindMapObj(JSON.parse(item.data));
                  const { graph } = graphinRef.current;
                  graph.changeData(JSON.parse(item.data));
                  graph.paint();
                  graph.fitView(20);
                } catch (error) {
                  console.error(error, item);
                }
              }}
```

需要点击两次才可生效

### Your Example Website or App

https://github.com/TrumanDu/TDA/blob/main/src/renderer/MindMap/index.tsx#L375

### Steps to Reproduce the Bug or Issue

无
![Animation](https://user-images.githubusercontent.com/16727775/167424496-5b5348f3-c9a7-4284-b390-b609c164cfd4.gif)

### Expected behavior

点击一次即可生效

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
"@antv/graphin": "^2.6.5",

**Comment by gotounix** [comment]
我从4.5.5版本升级到4.6.x版本后，发现 `GraphOptions.fitView` 和 `GraphOptions.fitCenter` 设置为 `true`，都无效了。

是取消了这个特性吗？

**Comment by xiziliang** [comment]
@Yanyan-Wang

**Comment by Yanyan-Wang** [comment]
因为 treeGraph 有动画，在动画完成之前，fitView 时计算的图大小一定是不准确的。在TreeGraph实例上配置 fitView: true，或绑定时机监听在动画完成后 fitView

graph.on('afteranimate', () => graph.fitView())

**Comment by TrumanDu** [comment]
问题在于异步，通过其他方式已经解决
