### ISSUE TITLE
关于Fruchterman布局在部分机器上显示错误的问题

### ISSUE THREAD

**Issue by SimNull1307** [antvis/G6#3673]
### 问题描述

当G6使用Fruchterman布局之后,在部分机器(windows,mac)上会显示错乱,包括官网的demo也是这个情况，如下图
请问有什么办法解决吗

![lQLPDhtpG95923TNBaDNCgCwE3oRsP09iFUCfOIxIEA9AA_2560_1440](https://user-images.githubusercontent.com/16277261/167584626-74d72d94-54ab-47be-94ad-64b872caef44.png)

### 重现链接

https://g6.antv.vision/zh/examples/net/gpuLayout#fruchtermanComplexData

### 重现步骤

进入页面

### 预期行为

正常情况应该是这样子

![image](https://user-images.githubusercontent.com/16277261/167584437-84567168-509a-4007-be6a-004468df49a9.png)

### 平台

- 操作系统: [macOS, Windows]
- 网页浏览器: [Google Chrome, Safari]
- G6 版本: [4.5.0 ]

**Comment by Yanyan-Wang** [comment]
只有 gpuEnabled true 时会出现，有可能是不同显卡 GPU 的并行逻辑差异导致的

**Comment by yfzm01** [comment]
> 只有 gpuEnabled true 时会出现，有可能是不同显卡 GPU 的并行逻辑差异导致的

设置了gpuEnabled: false也会这样
