### ISSUE TITLE
graph.fitView 设置数组拖动问题

### ISSUE THREAD

**Issue by lizhongkun** [antvis/G6#3674]
### Describe the bug

![image](https://user-images.githubusercontent.com/41602501/167752796-1c75b867-7a68-452f-8f07-2fc483fd7701.png)
![image](https://user-images.githubusercontent.com/41602501/167752819-e8156a49-a000-461e-b1dd-210576cb0c93.png)
graph.fitView([50, 0, 20, -width / 2]);拖动时有阴影；
graph.fitView(50)正常

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

graph.fitView([50, 0, 20, -width / 2]);

### Expected behavior

graph.fitView([50, 0, 20, -width / 2]);无阴影

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by lizhongkun** [comment]
![image](https://user-images.githubusercontent.com/41602501/168256807-37e5c1e8-d085-4545-be08-d210bd32435b.png)
官网示例也有这种问题

**Comment by Yanyan-Wang** [comment]
有可能是因为节点内部图形的宽、高等数据不是整数导致的。可以用 Math.ceil 来取个整

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
