### ISSUE TITLE
元素很多时 downloadFullImage 导出图片失败

### ISSUE THREAD

**Issue by webmrxu** [antvis/G6#3675]
### 问题描述

#2980 查看了这个issues 已经关闭了，但项目中数据量大导出图片还是空白。

g6 版本：4.5.0
浏览器版本： chrome 87.0.4280.66
layout.type:    compactBox 树
节点数量： 319 个
每个节点高宽：width：240 height：90
container入器高宽：width: 1102 height: 517 , 可拖动和缩放
导出图片文件，用window系统图片查看器打开图片提示：windows 照片查看器无法显示此图片，因为该文件是空的。

### 重现链接

无

### 重现步骤

layout.type:    compactBox 树
节点数量： 319 个
每个节点高宽：width：240 height：90
渲染正常，导出图片空白

### 预期行为

导出图片正常

### 平台

- 操作系统: [ Windows ]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.5.0 ]

### 补充说明（可选）

浏览器控制台中没有任何报错

**Comment by webmrxu** [comment]
debugger 源码发下 toDataUrl 返回 "data:,"
是不是以下问题，可以参考下
https://stackoverflow.com/questions/30079423/canvas-todataurl-returns-data

**Comment by Yanyan-Wang** [comment]
可以给个复现 demo 吗

**Comment by Yanyan-Wang** [comment]
v4.6.8 在导出图片时设置了兼容大小，不确定是否能修复上述问题

https://github.com/antvis/G6/blob/778720cc89866ba150ad6aeeb8695d5b41b4636f/packages/pc/src/graph/graph.ts#L217

**Comment by webmrxu** [comment]
目前项目中解决方式是：

限制节点数量，导出数据量大时，限制用户只能选择一个颗子树进行导出图片
