### ISSUE TITLE
怎么样实现鼠标移动到节点自动显示column信息？或 怎么样实现鼠标点击到节点显示column信息？

### ISSUE THREAD

**Issue by LucasssXiao** [antvis/G6#3676]
### 问题描述

怎么样实现鼠标移动到节点自动显示column信息？
或 
怎么样实现鼠标点击到节点显示column信息？

### 重现链接

CodeSandbox

### 重现步骤

怎么样实现鼠标移动到节点自动显示column信息？或 怎么样实现鼠标点击到节点显示column信息？

### 预期行为

怎么样实现鼠标移动到节点自动显示column信息？或 怎么样实现鼠标点击到节点显示column信息？

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
什么 column？没 get 到你说的是什么

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
