### ISSUE TITLE
如何使用dagre布局的layoutCfg.nodeOrder？

### ISSUE THREAD

**Issue by Rebornnn** [antvis/G6#3679]
### 问题描述

文档中只有dagre布局的layoutCfg.nodeOrder字段说明，找不到任何相关例子，不知道如何正确使用

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Rebornnn** [comment]
自己已经解决

**Comment by Brown000** [comment]
可以发个教程吗？我也遇到了这个问题

**Comment by AndySpider** [comment]
@Rebornnn 自己弄清楚了吗？能否给个样例说明，也方便后面也遇到同样问题的其他人。

**Comment by Rebornnn** [comment]
直接在配置`options`设置不生效，在`afterrender`事件中通过`updateLayout`是实现：
```
graph.updateLayout({
    nodeOrder: orders,
});
```
其中orders得是节点的id

**Comment by S1rine** [comment]
```javascript
new G6.Graph({
  ......
  layout: {
    type: 'dagre',
    rankdir: 'LR',
    nodeOrder: data.nodes.map(node => node.id)
  }
})
```
直接在初始化的时候设置也可以，也可以参考一下这个[链接](https://github.com/antvis/layout/blob/e780b551cb079cb7ca7b343bf8146613fe3421af/__tests__/g6/dagre-g6-test.ts#L507)。
