### ISSUE TITLE
自定义节点，设置fill为渐变色，定制动画后，fill颜色不生效

### ISSUE THREAD

**Issue by momogugu** [antvis/G6#3680]
### 问题描述

把render设置为svg
自定义节点no-animation，定义动画为width从0～100，fill设置为 fill: `l(0) 0:#f0f0f0 1:#108ee9`
背景色仅在第一次渲染时生效，后续数据更新，背景色为白色

### 重现链接

https://codesandbox.io/s/svg-render-6ypl33

### 重现步骤

sandbox可复现

### 预期行为

期望数据更新时，保持渐变色动画

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
更新数据 graph.changeData。看起来没有问题

https://codesandbox.io/s/svg-render-forked-edm5rl
