### ISSUE TITLE
创建子主题 如果标题中是 测试标题A<B  5<A 等类似这样 会报错 

### ISSUE THREAD

**Issue by zhoubaishuai** [antvis/G6#3681]
### 问题描述

创建子标题如果有运算符有字母存在 会出现错误

### 重现链接

测试标题A<B

### 重现步骤

1.输入标题名称测试标题A<B
2.画布错误 提示S[i] 不是有效的函数

### 预期行为

测试标题A<B 能够正常保存

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by zhoubaishuai** [comment]
1

**Comment by Yanyan-Wang** [comment]
什么标题？什么子主题？是不是走错片场了😳

**Comment by zhoubaishuai** [comment]
新建节点 输入节点名称 7<L<=10，回调的时候控制台报错，我这边是给<转换为&lt; 这样才不报错。
第一次提问题 可能描述的方式不是很对，抱歉。
![WechatIMG3438](https://user-images.githubusercontent.com/58590976/174025807-b142a075-402a-42dc-99cf-c9c433313a9f.png)

**Comment by zhoubaishuai** [comment]
<img width="154" alt="image" src="https://user-images.githubusercontent.com/58590976/174026228-8424eb64-08d6-4902-8cea-e26c952a79cd.png">
输入节点名称7 < L < = 10 ,保存后，控制台报错，提示S[i] 不是有效的函数
![WechatIMG3438](https://user-images.githubusercontent.com/58590976/174026404-9fc066f4-f0f1-4d29-be29-91671995b1a9.png)
附带下载xml 里面提示的截图
<img width="643" alt="image" src="https://user-images.githubusercontent.com/58590976/174026698-b3c8fcbb-5ab7-42df-9b64-e19f9cc2271e.png">

**Comment by zhoubaishuai** [comment]
<img width="138" alt="image" src="https://user-images.githubusercontent.com/58590976/174026941-c522c460-455c-4eed-9cc9-4d3336bb2d7e.png">

输入截图的名称，保存后提示S[i] 不是有效的函数

![WechatIMG3438](https://user-images.githubusercontent.com/58590976/174026989-c185dea9-7c86-476a-9a96-738492e3529e.png)

目前我这边是将< 进行转义，才能正常。

**Comment by Yanyan-Wang** [comment]
这个输入到哪里啊？能不能描述清楚一些？

**Comment by zhoubaishuai** [comment]
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/58590976/175223405-4a66b96e-1b09-4937-919a-062f528f390f.png">

这样是否能够理解？

**Comment by Yanyan-Wang** [comment]
在官网中没能复现这个问题，可能需要具体结合你这里自定义节点的方式来看

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
