### ISSUE TITLE
g6使用forceAtlas2静态布局时，根据展开后续节点时新增的节点位置问题

### ISSUE THREAD

**Issue by ZeroTo1024** [antvis/G6#3682]
### 问题描述

![1](https://user-images.githubusercontent.com/42179338/168248803-381a6d28-b71a-4aa7-ad7e-cd1095d45795.png)
![2](https://user-images.githubusercontent.com/42179338/168248817-8086acc2-2427-442c-bc49-90f44e4cd53e.png)
![3](https://user-images.githubusercontent.com/42179338/168248825-17ba2fb5-c99c-4c99-a93e-09e9b7d6fef0.png)

目前在学习G6，遇到了一个问题，现在是做了一个简单的节点展开demo，使用在不改变原数据位置使用graph.destroyLayout()后再调用changeData改变数据后，节点的位置需要自己写方法计算吗，有内置的的方法实现吗？或者工具类来计算后续新增的节点位置，还是必须要自己去写算法做计算的？目前自己设置x,y后，总是出现重叠或者布局不美观的问题，可以使用原有的Layout布局的属性有方法自动计算后续节点位置的工具类吗？

### 重现链接

http://

### 重现步骤

创建一个简单的forceAtlas2图谱然后双击节点展示后续节点

### 预期行为

是先一开始只展示3个节点，后续双击展示后续与他连接节点，保持原以展示的位置不变，添加节点，或者提供一个方法类，我传入nodes，edges，然后给我返回所有节点位置，我根据这个位置慢慢展示节点也可以

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]
windows

### 屏幕截图或视频（可选）

![1](https://user-images.githubusercontent.com/42179338/168252447-3a5fcf2a-d551-407e-81fe-0c656ea82a41.png)
![2](https://user-images.githubusercontent.com/42179338/168252457-0adedb31-ebcf-4661-930e-80cf0d8428dc.png)
![3](https://user-images.githubusercontent.com/42179338/168252460-bd4efe75-e3b6-47f0-96b2-5849e5ed7a42.png)

**Comment by Yanyan-Wang** [comment]
新数据进入，要有合理布局，一定是需要布局算法的。destroyLayout 之后，图上就没有布局算法了。建议不要这么做，可以用 gForce、force、fruchterman 这三种布局算法，并给已经存在的节点 fx fy，类似这样：
https://g6.antv.vision/zh/examples/net/forceDirected#gForceFix
https://g6.antv.vision/zh/examples/net/forceDirected#basicForceDirectedDragFix

将已有节点完全固定位置，也有一个缺点，就是可能无法腾出位置给新增节点，所以也可以使用 gForce 的 getMass 来给定已有节点比较大的质量，那么这些节点并不是完全不动，而是“比较难被其它力拉动”，看起来尽可能不动。https://g6.antv.vision/zh/docs/api/graphLayout/gforce#layoutcfggetmass

**Comment by ZeroTo1024** [comment]
最近发现forceAtlas2的效率比gForce更高一些，forceAtlas2能否支持设置fx、fy，或者后续forceAtlas2会不会添加此功能？

**Comment by Yanyan-Wang** [comment]
> 最近发现forceAtlas2的效率比gForce更高一些，forceAtlas2能否支持设置fx、fy，或者后续forceAtlas2会不会添加此功能？

欢迎社区小伙伴共建。那么这个 issue 就先关闭咯，新的问题可以新开 issue
