### ISSUE TITLE
關於TreeGraph類型圖的數據的取出

### ISSUE THREAD

**Issue by xjx0106** [antvis/G6#3684]
### 问题描述

當我init該圖數據的時候，我加載的數據是樹狀數據是這樣子的：
`mockData = [
  {
    id: "g1",
    children:
      [
        { id: "g11", children: [] },
        { id: "g12", children: [] },
      ]
  }
]`

當我編輯完想以樹狀數據保存，以便以後再次渲染和編輯，應該要有一個可以返回這種樹狀數據的方法吧？
而不是graph.getNodes() 這樣，得到的變成了一個扁平化數組。

### 重现链接

null

### 重现步骤

null

### 预期行为

我想獲得樹圖的原始結構樣子的數據。

我看到了：
console.log(graph.getNodes());
// [Node, Node, Node, Node]

我希望看到
console.log(graph.getTraaData());
// [Node] (從根節點開始的樹狀節點)

### 平台

null

**Comment by Yanyan-Wang** [comment]
graph.save() 
https://g6.antv.vision/zh/docs/api/graphFunc/data#graphsave

graph.get('data')
