### ISSUE TITLE
镜像文档格式问题

### ISSUE THREAD

**Issue by dev-itsheng** [antvis/G6#3685]
### Describe the bug

在镜像文档中，表格的格式出现了问题，其中一个参考链接请看[这里](https://antv-g6.gitee.io/zh/examples/tree/customItemTree#customTree) 。

下面是图：

<img width="837" alt="image" src="https://user-images.githubusercontent.com/10683193/168492989-32a6243b-17c0-4fa0-9a4b-0c2f6dfdef87.png">

我原以为是文档格式出了问题，结果官方文档是正常的，对应的链接在[这里](https://g6.antv.vision/zh/examples/tree/customItemTree#customTree)。

下面是图：

<img width="858" alt="image" src="https://user-images.githubusercontent.com/10683193/168493023-9fd66ff1-4641-47b6-b82f-287b6719271b.png">

辛苦帮忙排查一下。

### Your Example Website or App

--

### Steps to Reproduce the Bug or Issue

--

### Expected behavior

--

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
好的，感谢报告，可能是没有同步过去，我手动同步下看

**Comment by Yanyan-Wang** [comment]
官网内容迁移至新域名：https://g6.antv.antgroup.com/

超级快，不需要国内镜像了
