### ISSUE TITLE
自定义行为事件触发有问题

### ISSUE THREAD

**Issue by xiao-2** [antvis/G6#3686]
### 问题描述

在进行节点拖拽时，其他图形分组都能正确进行拖拽，但是底层的图形不能正常拖拽。
![1652687846(1)](https://user-images.githubusercontent.com/59162043/168546178-0a50f629-8ec1-42b7-9209-a6df1a2c851f.jpg)

图上红色可以正常拖拽
![image](https://user-images.githubusercontent.com/59162043/168546505-6bd5b76b-01c2-4465-b901-1a1d58aef412.png)

但是图中蓝色部分(底层图形部分)不能正常拖拽

正常拖拽演示图
![动画1](https://user-images.githubusercontent.com/59162043/168547702-8e3c26b1-30d2-4fac-b2c4-0c6ebcbc0950.gif)
错误拖拽演示图   
![动画2](https://user-images.githubusercontent.com/59162043/168547704-d1205847-4f1c-4c1e-a8bb-0d7da3da0765.gif)

### 重现链接

https://g6.antv.vision/zh/docs/api/Behavior

### 重现步骤

 onMousedown(event) {

    if (event.target.attrs.isOutPoint || event.target.attrs.isOutPointOut) {
      this.graph.setMode('addEdge')
    } else {
      this.graph.setMode('moveNode')
    }
触发鼠标按下事件后，切换行为，但是没有触发自定义行为的mousemove事件

  getEvents() {
    return {
      // 'node:mousedown': 'onMousedown',
      'mousemove': 'onMousemove',
      'mouseup': 'onMouseup',
      'canvas:mouseleave': 'onOutOfRange'
    }
  },

  onMousemove(event) {
    if (!this.origin) {
     this.getNode(event)
    }
    if(!this.isDrag){
      return
    }
    if (!this.get('shouldUpdate').call(this, event)) {
      return
    }
    this._update(this.target, event, this.nodeEvent, true)
  },
  

### 预期行为

底层图形也应该正常拖拽

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
这个是内置的节点类型 modelRect 吗？如果是自定义节点，在图形上要配置 draggable: true 哦

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
