### ISSUE TITLE
combo 初始化的时候可以通过某个选项配置默认收起吗

### ISSUE THREAD

**Issue by xiaoyixin-cmd** [antvis/G6#3687]
### 问题描述

combo 初始化的时候 自动展开

### 重现链接

暂无

### 重现步骤

进入页面combo是收起状态

### 预期行为

combo 初始化的时候可以通过某个选项配置默认收起

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.6.4 ]

**Comment by xiziliang** [comment]
combo不是可以控制显示和隐藏，初始化时候隐藏不久可以，通过某个按钮点击再显示

**Comment by user-lihai** [comment]
同问，我是初始化后遍历隐藏的

**Comment by Yanyan-Wang** [comment]
combo 数据中若有 collapsed: true ，该 combo 初次渲染时默认收起

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
