### ISSUE TITLE
force 布局用了 forceSimulation 之后，workerEnabled 没有生效？

### ISSUE THREAD

**Issue by nanhualyq** [antvis/G6#3688]
### 问题描述

如题，我对比了下，注释 forceSimulation 部分之后，workerEnabled 的作用很明显，开启后约1~2秒，关闭后约10秒。
但打开 forceSimulation 之后，workerEnabled 好像没有作用，不管开关整个过程大概都是10多秒。
请问这是BUG，还是我哪里用得不对，多谢指教。

### 重现链接

https://stackblitz.com/edit/react-pmkylv?file=index.js

### 重现步骤

打开demo链接即可看到

### 预期行为

期望 workerEnabled 能够像没有 forceSimulation 的时候一样提高渲染速度

### 平台

- 操作系统: Linux
- 网页浏览器: Firefox
- G6 版本: 4.6.4

**Comment by Yanyan-Wang** [comment]
worker 是不会提升布局计算性能的，只是不会阻塞主页面而已。打开你这里的 demo，好像差不多就是 2s 达到稳定状态？

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
