### ISSUE TITLE
仓库在apple-m1设备上安装依赖报错

### ISSUE THREAD

**Issue by hotWater-me** [antvis/G6#3689]
### 问题描述

源代码clone，yarn安装依赖之后，在m1设备上报错。

### 重现链接

https://github.com/lovell/sharp/issues/2994

### 重现步骤

1. yarn
2. 报错

### 预期行为

正常安装依赖

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.6.4 ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/56283392/168602674-0bb731d2-b99a-48ff-8b80-c9982cee14b1.png)

### 补充说明（可选）

经排查是sharp包的问题，npm ls 显示的版本是sharp^0.27.0，这个版本在apple-m1上有问题，相关[issue](https://github.com/lovell/sharp/issues/2994)
sharp给出了解决方案，需要升级到v0.29.0之上，[sharp文档](https://sharp.pixelplumbing.com/install#apple-m1)。我在根目录的resolutions，统一升到了^0.30.4，就正常了。

**Comment by Yanyan-Wang** [comment]
G6 v4.6.8 也已经在 resolutions 升级 sharp，感谢报告
