### ISSUE TITLE
Angular7 + G6 v4，编译打包后启动错误（本地启动没问题）

### ISSUE THREAD

**Issue by liuyiffan** [antvis/G6#3691]
### 问题描述

项目上是使用的Angular7，最近引入了G6，本地开发是没问题的，但是编译打包之后启动会报错
`Uncaught TypeError: Super expression must either be null or a function`

尝试过在tsconfig中加入skipLibCheck: true  [2796](https://github.com/antvis/G6/issues/2796)
也尝试过2个不同的G6版本（4.6.4、3.8.3）
都是一样的报错信息

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- Angular 7
- G6 4.6.4
- 浏览器 Chrome

### 屏幕截图或视频（可选）

<img width="720" alt="图片" src="https://user-images.githubusercontent.com/14682969/168848606-f8ada704-6f0c-495a-b267-82999f6abeeb.png">

**Comment by Yanyan-Wang** [comment]
https://g6.antv.vision/zh/docs/manual/FAQ/angular-support

**Comment by Yanyan-Wang** [comment]
非常抱歉，当前版本(3.x、4.x)依赖的底层渲染引擎暂时不会考虑 SVG 问题的修复，渲染引擎目前正在大升级，我们也将在新版本接入新渲染引擎，届时应当可以解决 SVG 各种 bug
