### ISSUE TITLE
官网案例---从端点上的子图形拖拽 ，当label的position不为center时，连线的起始点不在自定义的锚点上

### ISSUE THREAD

**Issue by feng842268973** [antvis/G6#3692]
### Describe the bug

官网案例---从端点上的子图形拖拽 ，当label的position不为center时，连线的起始点不在自定义的锚点上
![image](https://user-images.githubusercontent.com/18651289/168954138-a50ae3af-ddd5-4937-82fd-fb6a95996324.png)

### Your Example Website or App

https://g6.antv.vision/zh/examples/interaction/createEdge#drag-link-point

### Steps to Reproduce the Bug or Issue

修改defaultNode的labelCfg的position属性为bottom

### Expected behavior

希望可以连接到自定义的锚点上

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
因为这个 demo 是自定义节点，114 行给定这些圆点 x y 时根据的是整个节点图形分组 group 的 bbox。如果有文本在下面，图形分组范围就变大了。要是想要只出现在矩形四周，那 bbox 就取矩形的就好了
