### ISSUE TITLE
自定义节点时，节点被线遮挡

### ISSUE THREAD

**Issue by xiziliang** [antvis/G6#3693]
### 问题描述

在使用自定义节点和多边(quadratic)时，节点会被线遮挡，然后把`groupByTypes：false;node.toFront();`,还是会被线遮挡；

### 重现链接

https://codesandbox.io/s/wandering-framework-zjmwdt?file=/index.js

### 重现步骤

直接点击链接

### 预期行为

线不会遮挡节点

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.6.4 ]

### 屏幕截图或视频（可选）

<img width="474" alt="image" src="https://user-images.githubusercontent.com/54427136/168963391-bdc12c00-225e-46cf-8012-93b55d76ceb3.png">

**Comment by xiziliang** [comment]
@Yanyan-Wang 帮忙看看呗

**Comment by xiziliang** [comment]
在使用`G6.Util.processParallelEdges`计算线的开始坐标和结束坐标时会有问题，如果`{ source: "a", target: "b" }, { source: "b", target: "a" }`这两种线都有的话，这两条线的a的开始节点 ！= b的结束节点，看上去画的线很不协调

**Comment by Yanyan-Wang** [comment]
额，看起来有遮挡是因为你的节点填充是有透明度的，其实边是在下面的，但是节点透明的没盖住。你用不透明的填充色即可

**Comment by Yanyan-Wang** [comment]
> 在使用`G6.Util.processParallelEdges`计算线的开始坐标和结束坐标时会有问题，如果`{ source: "a", target: "b" }, { source: "b", target: "a" }`这两种线都有的话，这两条线的a的开始节点 ！= b的结束节点，看上去画的线很不协调

另外开个 issue，贴一下 demo 呗

**Comment by xiziliang** [comment]
> 额，看起来有遮挡是因为你的节点填充是有透明度的，其实边是在下面的，但是节点透明的没盖住。你用不透明的填充色即可

确实是因为透明度的问题
