### ISSUE TITLE
对combo的操作没有进入操作栈

### ISSUE THREAD

**Issue by liujiaqi222** [antvis/G6#3695]
### Describe the bug

对combo的操作没有进入操作栈
![image](https://user-images.githubusercontent.com/51473151/169431835-22fa49f5-8f72-4e7a-a402-5403df9038b4.png)

而这里普通的node和edge，有操作栈的选项

![image](https://user-images.githubusercontent.com/51473151/169431960-662a94fb-b2e5-4117-8b0e-dbea72a1f43a.png)

### Your Example Website or App

无需

### Steps to Reproduce the Bug or Issue

见上面

### Expected behavior

希望combo也能进入操作栈

### Platform

windows

**Comment by Yanyan-Wang** [comment]
v4.7.17 已支持 createCombo 和 uncombo 的入栈
