### ISSUE TITLE
G64.6.4在编译运行时，控制台打印依赖解析错误

### ISSUE THREAD

**Issue by zmbxy** [antvis/G6#3696]
### 问题描述

使用create-react-app5.0.1创建的项目，在编译运行时会出现依赖包解析错误的告警输出

### 重现链接

''

### 重现步骤

无

### 预期行为

能在mac m1下正常运行

### 平台

- 操作系统: [macOS M1]
- G6 版本: [4.6.4]
- react: [18.0.1]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/103547464/169438957-ca02cb59-e20f-4955-ad3e-c5c7392d46b7.png)

![image](https://user-images.githubusercontent.com/103547464/169438994-10788a40-da5a-4077-a02a-6ee7f54af6a9.png)

**Comment by zmbxy** [comment]
使用create-react-app 5.0.1创建项目，在windows下和mac下都有这个问题。

**Comment by Yanyan-Wang** [comment]
看起来是 graphin 报出来的？在 graphin 仓库提下 issue 呢？

**Comment by zmbxy** [comment]
我是用create-react-app创建的项目，没有引如graphin，就是G6。
在开启生成source map的情况，目前看是必定出现的，关闭source map就没有事情了。

**Comment by Yanyan-Wang** [comment]
好像是少了 dagre-compound 这个布局，检查一下安装的 @antv/layout 包是不是最新的

**Comment by zmbxy** [comment]
依赖里面看着好像没什么问题，@antv/layout是0,2,4的，依赖的dagre-compound是0.0.11版本的

**Comment by Yanyan-Wang** [comment]
感觉是生成 source map 的时候，没有引用到最新的 @antv/layout

**Comment by wsh085** [comment]
请问楼主这个问题解决了吗？遇到了相同问题

**Comment by matianxiang** [comment]
有解决办法吗，这个问题还是存在
