### ISSUE TITLE
GraphOptions.width、GraphOptions.height 太大导致渲染异常

### ISSUE THREAD

**Issue by webmrxu** [antvis/G6#3697]
### 问题描述

项目中需要有滚动条，使用changeSize 改变canvas的width,height 大小，数据量大时导致渲染异常，多次调试后发现width 和height 好像有临界值，超过了临界值就渲染异常了。

在官方文档中，快速开始改变width和height 发现有同样的问题，以下代码在官方文档快速开始中复制下来的，宽高设置为width: 10000, height: 10000, 然后就异常了。

查看官方文档的width和height配置，并没有临界值的描述。

代码如下

`import G6 from "@antv/g6";

const data = {
  nodes: [
    {
      id: "node1",
      label: "Circle1",
      x: 150,
      y: 150
    },
    {
      id: "node2",
      label: "Circle2",
      x: 400,
      y: 150
    }
  ],
  edges: [
    {
      source: "node1",
      target: "node2"
    }
  ]
};

const graph = new G6.Graph({
  container: "container",
  width: 10000,
  height: 10000,
  defaultNode: {
    shape: "circle",
    size: [100],
    color: "#5B8FF9",
    style: {
      fill: "#9EC9FF",
      lineWidth: 3
    },
    labelCfg: {
      style: {
        fill: "#fff",
        fontSize: 20
      }
    }
  },
  defaultEdge: {
    style: {
      stroke: "#e2e2e2"
    }
  }
});

graph.data(data);
graph.render();
`

### 重现链接

无

### 重现步骤

1、官方文档，快速开始
2、修改快速开始的代码，width: 10000, height: 10000
3、然后可以看到渲染空白了

### 预期行为

渲染正常

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.5.0]

### 屏幕截图或视频（可选）

<img width="1290" alt="WechatIMG612" src="https://user-images.githubusercontent.com/26652828/169487867-012ddda5-f4b5-4842-9a7c-1d5c01ad0a98.png">

**Comment by Yanyan-Wang** [comment]
canvas 没必要太大，和容器一样大小就行了，通过拖拽画布进行查看。画布合理大小，我们在画布外会做渲染裁剪提升性能。
