### ISSUE TITLE
drag-node有enableStack的选项，但是drag-combo没有！

### ISSUE THREAD

**Issue by liujiaqi222** [antvis/G6#3699]
### 问题描述

我拖动了一下combo，然后就超级多入栈了。
![image](https://user-images.githubusercontent.com/51473151/169652921-64cd3c73-79d5-4779-8b2e-bc37b0830f37.png)

### 重现链接

https://codesandbox.io/s/currying-waterfall-94drdn?file=/src/components/HelloWorld.vue

### 重现步骤

1.当点击节点梁赞会产生combo，
2.然后拖动combo，
3.就可以看到控制台中的stack的变化

### 预期行为

希望drag-combo增加不入栈的选项，就像drag-node那样。

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
感谢报告，我们会尽快修复
