### ISSUE TITLE
能否提供一些示例

### ISSUE THREAD

**Issue by itsmyturn** [antvis/g6#37]
![image](https://user-images.githubusercontent.com/11573322/28743141-41021732-7475-11e7-82c3-81b7c399cc21.png)
官网能否提供一些示例，包括前进，后退，文本输入

**Comment by TomHuangCN** [comment]
建议看文档解决：

https://antv-pre.site.alipay.net/g6/api/net.html

https://antv-pre.site.alipay.net/g6/doc/tutorial/start/net.html

**Comment by itsmyturn** [comment]
好的，上面的连接打不开，还有就是文档里面的demo连接有的也打不开，这几天一直在看文档，如果能再消息点就更好了

**Comment by itsmyturn** [comment]
我想做的效果是通过锚点的颜色提示是输入什么和输出什么，通过插入html
![image](https://user-images.githubusercontent.com/11573322/28760493-36183e94-75da-11e7-99e4-629e6989109d.png)，用html标签代替锚点连接，不知道可否实现

**Comment by TomHuangCN** [comment]
1. 通过拿到锚点的坐标，自己在外面用html 做提示信息
1. https://antv.alipay.com/g6/doc/tutorial/start/custom-shape.html 见更详尽的锚点文档。
