### ISSUE TITLE
Context Menu displays far from expected position

### ISSUE THREAD

**Issue by javadmoradii** [antvis/G6#3700]
### Describe the bug

I want the context menu to open on the mouse position. I tried to set offsetX and offsetY to show the context menu next to the mouse position. When the node has space to show the context menu at the bottom, the context menu is shown correctly. But when the node is at the bottom of the page, the menu is shown far from the node.

### Your Example Website or App

https://stackblitz.com/edit/react-xz8ght-tudse6?file=index.html,index.js

### Steps to Reproduce the Bug or Issue

1. hover mouse on node
2. right click on mouse

### Expected behavior

I expect the context menu to open on the mouse position.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/40931773/169688798-185bdb9b-5586-47b4-8df4-00c23aca1f5b.png)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
It is affected by the description div on the top, changing the parent element to the graph container's parentElement or the document.body solves the problem

document.body.appendChild(descriptionDiv);

![image](https://user-images.githubusercontent.com/29593318/181729073-8512b33d-31ee-41f1-8c52-492e316956f1.png)
