### ISSUE TITLE
cannot zoom in to the maxZoom or zoom out to the minZoom

### ISSUE THREAD

**Issue by daichaofan** [antvis/G6#3702]
### Describe the bug

初始化画布时设置缩放的最小值和最大值，无法通过缩放达到最大值或者最小值

### Your Example Website or App

https://codesandbox.io/s/focused-tdd-m7n3y5?file=/src/App.vue

### Steps to Reproduce the Bug or Issue

1、缩放画布至最大
2、查看左侧滑块缩放倍数，无法达到设置的最大值10
3、缩小画布至最小
4、查看左侧滑块缩放倍数，无法达到设置的最小值0.5

### Expected behavior

可以通过缩放达到设置的最大值或最小值

### Platform

- OS: Windows
- Browser: Chrome
- Version: 4.6.4

**Comment by JoeWrights** [comment]
遇到同样的问题，请问解决了吗

**Comment by Yanyan-Wang** [comment]
graph 层也需要配置 minZoom 和 maxZoom，默认 minZoom 是 0.1， maxZoom 是 10。看到 demo 里面你为 zoom-canvas behavior 配置了 minZoom 和 maxZoom，但是没有为 graph 实例配置。zoom-canvas 只管通过滚轮交互缩放这个操作
