### ISSUE TITLE
calling changeData(data, false) with collapsed combos cause operation stack to have unexpected `visibility` actions

### ISSUE THREAD

**Issue by mpodgorny** [antvis/G6#3704]
### Describe the bug

Hello!

I'm currently implementing Combos in our G6 app.  We're using redo/undo stack (cool feature!), but we found an issue causing our stack to have things we don't expect to have. 

We're passing `combos: [{..., collapsed: true}]` (alongside with nodes and edges)  to `graph.changeData()`, with `stack` set to `false`. Those combos have collapsed property set to `true`, which pushes `action: visibility` to the stack. I think ideally we wouldn't have that, especially with `stack: false` in `ChangeData()` 

I believe that `graph.data()` with the same data also causes `visibility` actions in the stack, which probably is also unexpected behaviour - I think we don't want any stack action after calling `graph.data()`.
 
I've added small codesandbox example, you can see that after one `changeData(data, false)` stack have two `visibility` actions. (logs in console) 

### Your Example Website or App

https://codesandbox.io/s/stack-combo-issue-y4c3vf?file=/src/App.js:1393-1415

### Steps to Reproduce the Bug or Issue

1. Have clean graph with empty operation stack.
2. Call `graph.changeData(data, false)` function, where `data` contains combos with `collapsed: true` property
3. Check the operation stack that `visibility` action is present there.

### Expected behavior

I expect operation stack to still be empty. 

### Platform

- OS: macOS
- Browser: Chrome
- Version: 101

**Comment by Yanyan-Wang** [comment]
Thanks for reporting, we will fix it ASAP

**Comment by Yanyan-Wang** [comment]
v4.6.8 fixed it
