### ISSUE TITLE
legend激活样式不生效，plugin/src/legend/index.ts第211行lengedStateStyles拼写错误

### ISSUE THREAD

**Issue by zhangyanbing-inspur** [antvis/G6#3705]
### Describe the bug

legend激活样式不生效，plugin/src/legend/index.ts第211行lengedStateStyles拼写错误，应为legendStateStyles

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

正常设置legendStateStyles即可复现

### Expected behavior

期望设置legendStateStyles生效

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/72586399/170168747-8063357e-d319-4cfd-b6a4-211687896467.png)
![image](https://user-images.githubusercontent.com/72586399/170168823-6f25bf20-cef7-4fc6-ab81-309e10239ef0.png)

### Platform

- OS: Windows
- Browser: Chrome
- Version: 77.0

**Comment by Yanyan-Wang** [comment]
感谢报告，我们会尽快修复
