### ISSUE TITLE
初始化 options 中指定某布局方式，后续再通过 updateLayout 设置为该布局时，布局不生效

### ISSUE THREAD

**Issue by Enivia** [antvis/G6#3706]
### 问题描述

初始化 options 中指定某布局方式，后续再通过 updateLayout 设置为该布局时，布局不生效

### 重现链接

https://codesandbox.io/s/layout-bug-y0u3dr

### 重现步骤

1. 初始化 graph 实体，`options` 配置 layout 为 `{ type: "grid" }`
2. 调用 `graph.updateLayout({ type: 'concentric' })`，布局生效
3. 再调用 `graph.updateLayout({ type: 'grid' })` ，布局未生效

### 预期行为

调用 `graph.updateLayout({ type: 'grid' })` ，能成功切换为网格布局

### 平台

- 操作系统: Windows
- 网页浏览器: Chrome
- G6 版本: 4.6.4

### 屏幕截图或视频（可选）

![layout](https://user-images.githubusercontent.com/23496031/170172212-90900d54-7ced-4299-b539-240647f050a6.gif)

**Comment by daichaofan** [comment]
可以暂时参考这个问题的解决方法 #3520
