### ISSUE TITLE
当画布缩放时，边的大小和标签不随画布缩放的变化而变化有解决方法吗？

### ISSUE THREAD

**Issue by gpxCode** [antvis/G6#3709]
### 问题描述

'zoom-canvas'的fixSelectedItems设置项只能控制edge的label控制不了边的样式。。
### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by liujiaqi222** [comment]
获取到缩放比率后，然后遍历所有节点，改变他们的size

**Comment by ricenoddle** [comment]
你说的是这个demo 吧 https://g6.antv.vision/zh/examples/interaction/zoomCanvasFixItem#fixItem

**Comment by Yanyan-Wang** [comment]
楼上 demo 配置 fixLineWidth 就可以设置固定线宽
