### ISSUE TITLE
G6官方API文档“事件绑定/解绑”章节参数描述错误

### ISSUE THREAD

**Issue by happyyangyuan** [antvis/G6#3710]
### Describe the bug

只是一个文档API参数类型描述的小错误

连接：
https://g6.antv.vision/zh/docs/api/graphFunc/on_off#graphoneventname-handler

截图：
<img width="1791" alt="image" src="https://user-images.githubusercontent.com/9134975/170607539-dcc0750c-1369-4a38-9f57-c62c7ec3dbe5.png">

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

无

### Expected behavior

无

### Screenshots or Videos

截图：
<img width="1791" alt="image" src="https://user-images.githubusercontent.com/9134975/170607539-dcc0750c-1369-4a38-9f57-c62c7ec3dbe5.png">

### Platform

- Browser:  Chrome

### Additional context

无

**Comment by Yanyan-Wang** [comment]
感谢报告，我们会尽快修正

**Comment by Yanyan-Wang** [comment]
已修正，再次感谢
