### ISSUE TITLE
实例化Grid时，配置了img属性，但是没有根据图片数据生成对应的网格

### ISSUE THREAD

**Issue by hushaoyu** [antvis/G6#3717]
### 问题描述

用本地网格图片生成base64格式的数据后，在实例化Grid时，配置了img属性，但是G6图中没有生成对应的网格，查看DOM元素，发现g6-grid元素没有background-image属性。不指定img属性时可以正常生成默认的网格背景。

### 重现链接

如图所示

### 重现步骤

如图所示

### 预期行为

可以通过配置img属性数据，生成对应的网格背景。

### 平台

- 操作系统: Windows
- 网页浏览器: Google Chrome 98.0.4758.102
- G6 版本: 本地环境 G6 4.3.4

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/25758091/172138175-0681cc4b-b648-467c-bef1-6358b8c4ddab.png)
![image](https://user-images.githubusercontent.com/25758091/172138279-c1614dfe-d944-46e5-873b-a2fb7212e3fa.png)

**Comment by Yanyan-Wang** [comment]
base64 字符串前面还需要加 url(，对应末尾加 )。下个小版本我会兼容下
