### ISSUE TITLE
自定义一个node和edge组合的 图形作为node

### ISSUE THREAD

**Issue by chenlikun-sy** [antvis/G6#3719]
### 问题描述

自定义一个node和edge组合的 图形作为node。目前没看实例参考node和edge怎么注册到一个图形里。

### 重现链接

无

### 重现步骤

无

### 预期行为

希望能看到node和edge作为一个整体注册为一个node使用

### 平台

- 操作系统: [ Windows]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
我理解你想做一个自定义节点，包括一个圆+一个路径。图形和 node、edge 不是一个层级的概念，需要先区分一下，自定义节点是在组装图形：
https://g6.antv.vision/zh/docs/manual/middle/elements/shape/shape-keyshape
https://g6.antv.vision/zh/docs/manual/middle/elements/shape/graphics-group

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
