### ISSUE TITLE
legend中获取stateStyles样式参数拼写lengedStateStyles，应该为legendStateStyles

### ISSUE THREAD

**Issue by LinXibei** [antvis/G6#3724]
### Describe the bug

编写legend中
`filter: {
		enable: true,
		multiple: true,
		trigger: 'click',
		legendStateStyles: {
			active: {
				lineWidth: 5,
				strokeOpacity: 0.5,
				stroke: '#f00'
			},
			inactive: {
				lineWidth: 100,
				strokeOpacity: 0.5,
				stroke: 'blue'
			},
		},
}`的自定义的active和inactive没有生效，
源码中
`const stateStyles = filter?.lengedStateStyles || {};

    const legendInactive = stateStyles?.inactive || {
      opacity: 0.5,
      'text-shape': {
        opacity: 0.5,
      }
    };` 应该是拼写错误吧

### Your Example Website or App

http://localhost:8001/

### Steps to Reproduce the Bug or Issue

编写legend中
`filter: {
		enable: true,
		multiple: true,
		trigger: 'click',
		legendStateStyles: {
			active: {
				lineWidth: 5,
				strokeOpacity: 0.5,
				stroke: '#f00'
			},
			inactive: {
				lineWidth: 100,
				strokeOpacity: 0.5,
				stroke: 'blue'
			},
		},
}`的自定义的active和inactive没有生效，
源码中
`const stateStyles = filter?.lengedStateStyles || {};

    const legendInactive = stateStyles?.inactive || {
      opacity: 0.5,
      'text-shape': {
        opacity: 0.5,
      }
    };` 应该是拼写错误吧

### Expected behavior

filter中编写的legendStateStyles的active和inactive可以生效

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
感谢报告，我们会尽快修复

**Comment by Yanyan-Wang** [comment]
duplicated to https://github.com/antvis/G6/issues/3724

**Comment by Richard-vip** [comment]
![image](https://user-images.githubusercontent.com/102498666/176395932-c42d2458-90c0-4f20-b1cb-633a635826f2.png)

这个文档这里标注一下？
