### ISSUE TITLE
官方demo 子图布局force改为radial布局未生效

### ISSUE THREAD

**Issue by chenxiaobaic** [antvis/G6#3725]
### 问题描述

![image](https://user-images.githubusercontent.com/40561372/173525712-9c0bec72-5877-4ebc-9d59-90c7c29bb621.png)

### 重现链接

https://g6.antv.vision/zh/examples/net/layoutMechanism#subgraphLayout

### 重现步骤

  const subForceLayout = new G6.Layout.force({
    center: [nodes[0].x, nodes[0].y],
    linkDistance: 70,
    preventOverlap: true,
    nodeSize: 20,
    tick: function tick() {
      // the tick function to show the animation of layout process
      graph.refreshPositions();
    },
  });改为  const subForceLayout = new G6.Layout.radial({
    center: [nodes[0].x, nodes[0].y],
    tick: function tick() {
      // the tick function to show the animation of layout process
      graph.refreshPositions();
    },
  });子布局未生效

### 预期行为

子布局变更为radial

### 平台

- 操作系统: [Windows, vue]
- 网页浏览器: [Google Chrome, ]
- G6 版本: [4.6.4 ... ]

**Comment by chenxiaobaic** [comment]
将force改为circular等其他布局也没有生效

**Comment by Yanyan-Wang** [comment]
force 是每个迭代更新位置达到模拟力动画的过程，所以在 tick 里面写的 refreshPositions，radial 算法没有这个概念，要计算完后更新位置。
可以看下这个视频 2 分 41 秒：
https://www.bilibili.com/video/BV1mv4y1K7nb?spm_id_from=333.999.0.0&vd_source=49df598f9a516023271b790c7c5d81d8
