### ISSUE TITLE
destroyLayout报错

### ISSUE THREAD

**Issue by chenxiaobaic** [antvis/G6#3727]
### 问题描述

按照官方文档用法

![image](https://user-images.githubusercontent.com/40561372/173547122-96e72cfe-325f-4568-9c57-bec20eb34e50.png)

销毁布局报错

### 重现链接

https://g6.antv.vision/zh/examples/net/forceDirected#basicForceDirected

### 重现步骤

将代码替换为
import G6 from '@antv/g6';

const container = document.getElementById('container');
const width = container.scrollWidth;
const height = container.scrollHeight || 500;
const graph = new G6.Graph({
  container: 'container',
  width,
  height,
  layout: {
    type: 'force',
  },
  defaultNode: {
    size: 15,
  },
});
const data = {nodes:[{id:"1"}, {id:"2"}], edges: [{source: '1', target: '2'}]}
graph.data(data)
graph.render()
graph.destroyLayout()
点击运行 报错

### 预期行为

销毁布局

### 平台

- 操作系统: [ Windows, vue]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.6.4 ... ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/40561372/173547046-7f19ce74-bf4f-47ac-8684-416db382fce9.png)

**Comment by Yanyan-Wang** [comment]
感谢报告，我们会尽快修复
