### ISSUE TITLE
combo 在拖动的时候 或者点击的时候出现白色背景及蓝色边框 (v4.6.4)

### ISSUE THREAD

**Issue by user-lihai** [antvis/G6#3728]
### 问题描述

在拖动或者点击combo的过程中出现白色背景及蓝色边框，像是默认的样式，但是无法去覆盖，在相关点击拖动事件中修改样式仍无法彻底解决

### 重现链接

暂无

### 重现步骤

1. 创建combo
2. 配置好style
3. 正常拖动点击

### 预期行为

解决方案或者时机，目前尝试过平台上的方法，无效

### 平台

vue 
chrome
g6 v4.6.4

**Comment by Yanyan-Wang** [comment]
如果有用 click-select， 配置它的 selectedState 为非 'selected' 字符串。或者在 nodeStateStyles 里面把 selected 样式复写掉。因为默认情况下 click-select 在点击节点时会将节点状态设置为 selected true，然后内置有 selected 的样式，所以看起来是视频中的效果。

**Comment by user-lihai** [comment]
好的，感谢！还有个问题就是nodeStateStyle 优先级的问题，如果使用自定义的node, 复写了一遍setState 是不是 nodeStateStyle就不生效了，当前我使用的场景是，为了更好的管理动画效果就在setState里面自定义了一个状态，但是在new G6配置全局的时候 nodeStateStyle中的hover就无效了，那是不是自定义之后，就不采用 nodeStateStyle了，需要重新写一遍

**Comment by Yanyan-Wang** [comment]
setState 就把内置的状态逻辑管理全部覆盖了，完全由自己来控制。不过在 setState 里面应该也可以拿到 cfg 中的 stateStyles，根据其中内容来更新元素样式即可
