### ISSUE TITLE
使用 G6.Util.processParallelEdges处理边后，边的展示效果不符合期望

### ISSUE THREAD

**Issue by xiziliang** [antvis/G6#3729]
### 问题描述

当绘制多条边且有箭头时，用到了G6.Util.processParallelEdges，但是效果和期望的有所差别，举个例子，如果一条边的数据是`
{ source: 'a', target: 'b' }`,另一条边的数据是`{ source: 'b', target: 'a' `},我们期望绘制后第一条边的终点是第二条边的起点，但是实际上不是这样的，需要我们再遍历一遍数据， 把`{ source: 'a', target: 'b' } 和 { source: 'b', target: 'a' } 的数据都改为 { source: 'a', target: 'b' }`，才是想要的效果；

### 重现链接

https://codesandbox.io/s/wandering-framework-zjmwdt?file=/index.js:1115-1144

### 重现步骤

demo中我有写processData函数，是我当前用来解决这个问题的方法，被注释的代码解开后，就是期望的效果，注释上以后就是默认效果；

### 预期行为

期望在processParallelEdges中解决问题

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

默认效果：
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/54427136/174027873-d2d5fe41-6087-4871-9104-0bebd6083d7f.png">
期望效果：
<img width="594" alt="image" src="https://user-images.githubusercontent.com/54427136/174029505-d5946df9-003b-4975-b8bd-682942d80bd5.png">

**Comment by Yanyan-Wang** [comment]
应该只是因为这些边的连接到节点的 anchorPoints 不一致。在 defaultNode 里配置 
    anchorPoints: [
      [1, 0.5],
      [0, 0.5]
    ] 
即可

**Comment by Joker0219** [comment]
如果不设置 anchorPoints， 以及fitCenter 为 false 时，
针对自定义的 nodes ，这个问题也会出现。
如果用默认的 nodes， 这个问题就不会出现。
