### ISSUE TITLE
启用特定属性时，边的文本与文本背景相对位置出现异常

### ISSUE THREAD

**Issue by hushaoyu** [antvis/G6#3731]
### 问题描述

1、初始化设置了边的文本标签内容及背景。
2、通过面板设置文本的position属性，文本与背景的相对位置出现异常，关闭属性时，样式正常。
3、切换autoRotate属性，文本内容不更新位置，只有背景跟随autoRotate属性实时变化。
4、将autoRotate属性变化后的数据保存后重新加载，文本内容和背景都显示正常了。

### 重现链接

如图

### 重现步骤

![边文本与背景位置异常](https://user-images.githubusercontent.com/25758091/174215457-1c933f3c-0eb2-4f7c-a884-8697b9d0de84.gif)

### 预期行为

1、设置文本的position属性时，文本内容应正常显示在文本背景的正上方。
2、动态设置文本的autoRotate属性时，文本内容与背景能正常实时更新。

### 平台

- 操作系统: Windows
- 网页浏览器: Google Chrome 98.0.4758.102
- G6 版本: 本地环境 G6 4.3.4

**Comment by Yanyan-Wang** [comment]
请给一个在线复现 demo

**Comment by hushaoyu** [comment]
> 请给一个在线复现 demo

G6版本是4.3.4。
复现DEMO：https://codesandbox.io/s/nifty-feistel-df2rsf

**Comment by Yanyan-Wang** [comment]
升级到最新版本即可
