### ISSUE TITLE
当布局是fruchterman的时候，toolbar的redo和undo失效

### ISSUE THREAD

**Issue by Tsai5277** [antvis/G6#3732]
### Describe the bug

当布局是fruchterman的时候，toolbar的redo和undo失效，其他功能可以用，同样的问题，发现在force布局下也不可用

### Your Example Website or App

https://codesandbox.io/s/toolbar-redo-undo-vhkuhm?file=/index.js

### Steps to Reproduce the Bug or Issue

1.渲染完成
2.拖拽几个节点远离当前位置
3.点击toolbar的undo，发现并没有起作用

### Expected behavior

希望在fruchterman和force布局下也能使用toolbar的redo和undo功能

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
跟你用什么布局没关系，你在这个 demo 试过别的布局吗？一样的没有效果。是因为开启 redo undo 栈，必须为图实例配置 enabledStack: true

https://g6.antv.vision/zh/docs/api/Graph/#graphoptionsenabledstack
