### ISSUE TITLE
Event name capitalized - is it intended?

### ISSUE THREAD

**Issue by dukesun99** [antvis/G6#3736]
### Describe the bug

This [line](https://github.com/antvis/G6/blob/90f1264b25b4b37864cca4511a39645595f4b799/packages/core/src/types/index.ts#L155) of TS declaration, declared the event name `nodeselectChange`, in which the C is capitalized, and across the other parts of the code, the C is in lower case. 

### Your Example Website or App

N/A

### Steps to Reproduce the Bug or Issue

1. run Graphin build

### Expected behavior

This caused the TS check to fail for Graphin build. I expect it to be consistent.

### Platform

N/A

**Comment by Yanyan-Wang** [comment]
Thank you for reporting, I will fix it ASAP
