### ISSUE TITLE
可否在render时指定一个渲染中心

### ISSUE THREAD

**Issue by varShears** [antvis/G6#3737]
### 问题描述

目前操作每次修改数据重新render图像，g6会将中心放到整个内容的中心上，此时使用focusItem或者moveTo会造成画面闪动

### 重现链接

https://stackblitz.com/edit/vue-cwafeq?file=src/App.vue

### 重现步骤

1.进入页面
2.点击render
3.会看到图像视口会很快的先对准图形中心然后对准focusItem指定的元素
4.页面在上述过程中会闪动

### 预期行为

希望的是能够渲染到某个指定地点或者节点，不要先渲染到默认位置然后再移动到指定位置

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
在 afterlayout 监听里面去做这件事情
![image](https://user-images.githubusercontent.com/29593318/174944032-4dd22388-1c8c-457d-bcb3-aab51652db7a.png)
