### ISSUE TITLE
dagre和fruchterman

### ISSUE THREAD

**Issue by grainnn** [antvis/G6#3738]
### 问题描述

关于布局问题：未开启GPU加速，在['fruchterman', 'dagre']两种布局模式间切换时，fruchterman布局无法恢复到初次渲染的状态；而dagre可以。

### 重现链接

https://codesandbox.io/s/stupefied-keldysh-jvk0q3?file=/index.js

### 重现步骤

初次渲染，fruchterman布局正常；点击“切换布局”按钮，切换至dagre布局；在dagre布局渲染完成之后，再次点击“切换布局”切换至frucherman布局，fruchterman布局和初次渲染效果不一致。

### 预期行为

希望fruchterman布局再次渲染时与初次渲染效果一致。

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Firefox]
- 版本: [101.0.1 (64 位)]

其他浏览器下应该也是一样

### 补充说明（可选）

G6试用测试

**Comment by Yanyan-Wang** [comment]
因为这种力导向家族的布局，都很依赖节点初始位置的，切换到 dagre 之后再切换到 fruchterman，实际上初始位置就是 dagre 的结果了，所以它在 dagre 的布局的结果基础上进行的计算。想要去除 dagre 的影响，加一段：

![image](https://user-images.githubusercontent.com/29593318/174565106-65b2248c-4046-461c-8fc0-549665107a28.png)

**Comment by jinfei-lab** [comment]
> 因为这种力导向家族的布局，都很依赖节点初始位置的，切换到 dagre 之后再切换到 fruchterman，实际上初始位置就是 dagre 的结果了，所以它在 dagre 的布局的结果基础上进行的计算。想要去除 dagre 的影响，加一段：
> 
> ![image](https://user-images.githubusercontent.com/29593318/174565106-65b2248c-4046-461c-8fc0-549665107a28.png)

你好，请问这一段代码是写在切换布局前还是切换布局后

**Comment by grainnn** [comment]
> > 因为这种力导向家族的布局，都很依赖节点初始位置的，切换到 dagre 之后再切换到 fruchterman，实际上初始位置就是 dagre 的结果了，所以它在 dagre 的布局的结果基础上进行的计算。想要去除 dagre 的影响，加一段：
> > ![image](https://user-images.githubusercontent.com/29593318/174565106-65b2248c-4046-461c-8fc0-549665107a28.png)
> 
> 你好，请问这一段代码是写在切换布局前还是切换布局后

切到fruchterman之前，手动删除掉节点的x,y

**Comment by grainnn** [comment]
@

> > 因为这种力导向家族的布局，都很依赖节点初始位置的，切换到 dagre 之后再切换到 fruchterman，实际上初始位置就是 dagre 的结果了，所以它在 dagre 的布局的结果基础上进行的计算。想要去除 dagre 的影响，加一段：
> > ![image](https://user-images.githubusercontent.com/29593318/174565106-65b2248c-4046-461c-8fc0-549665107a28.png)
> 
> 你好，请问这一段代码是写在切换布局前还是切换布局后


因为这种力导向家族的布局，都很依赖节点初始位置的，切换到 dagre 之后再切换到 fruchterman，实际上初始位置就是 dagre 的结果了，所以它在 dagre 的布局的结果基础上进行的计算。想要去除 dagre 的影响，加一段：
image

你好，请问这一段代码是写在切换布局前还是切换布局后

切到fruchterman之前，手动删除掉节点的x,y @jinfei-lab
