### ISSUE TITLE
官方示例不能拖动

### ISSUE THREAD

**Issue by wulinsheng123** [antvis/G6#3739]
### Describe the bug

html示例不能多动，

### Your Example Website or App

https://g6.antv.vision/zh/examples/item/customNode#svgDom

### Steps to Reproduce the Bug or Issue

https://g6.antv.vision/zh/examples/item/customNode#svgDom

### Expected behavior

能拖动节点

### Platform

- OS: [e.g. macOS, ]
- Browser: [e.g. Chrome,]
- Version: [e.g.100]

**Comment by wulinsheng123** [comment]
已经增加default: ['drag-node']属性

**Comment by Yanyan-Wang** [comment]
DOM 类型节点只能接收原生事件，不支持 G6 的交互 https://g6.antv.vision/zh/docs/api/shapeProperties#dom-svg。建议使用这种方式自定义节点：https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/jsx-node
会自动转换为 canvas 绘制，可以使用 G6 所有内置事件

**Comment by wulinsheng123** [comment]
我想做移动端的流程图，请问有办法实现吗。我看了下如果用jsx这种移动端上很多时间不能触发
