### ISSUE TITLE
文档错误 graph.fitView.rules

### ISSUE THREAD

**Issue by kaocong** [antvis/G6#3741]
### 问题描述

![image](https://user-images.githubusercontent.com/50489475/174697248-907df75b-82fd-4e65-9a1e-53e5dcd3c75f.png)

### 重现链接

/

### 重现步骤

/

### 预期行为

/

### 平台

/

**Comment by Yanyan-Wang** [comment]
感谢报告，我们会尽快修正

**Comment by Yanyan-Wang** [comment]
已修正
