### ISSUE TITLE
嵌套Combo拖动渲染异常

### ISSUE THREAD

**Issue by menghaoG** [antvis/G6#3742]
### Describe the bug

组件化后的嵌套combo，在拖动的时候，画布出现拖动残影，即使添加了拖动时刷新的API“graph.refreshPositions();”也没用。

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

1.使用Vue封装一个嵌套combo组件
2.获取到源数据后，在画布渲染出嵌套combo
3.拖动combo后，偶发性出现残影

### Expected behavior

拖动combo不会出现残影

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/87536545/174701335-7b5087f1-501d-4cb6-9190-bb0f11330322.png)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
一般是因为自定义节点中的图形有非法的样式属性值，先排查一下是不是有 NaN、null 等值。没找到的话提供以下复现在线 demo

**Comment by Yanyan-Wang** [comment]
> > 一般是因为自定义节点中的图形有非法的样式属性值，先排查一下是不是有 NaN、null 等值。没找到的话提供以下复现在线 demo
> 
> 问题已经解决了，在拖拽Combo事件中使用graph.changeSize不断地刷新画布的大小

这个方法不太好，建议还是找下根因，一般是图形的属性有问题

**Comment by menghaoG** [comment]
> > > 一般是因为自定义节点中的图形有非法的样式属性值，先排查一下是不是有 NaN、null 等值。没找到的话提供以下复现在线 demo
> > 
> > 
> > 问题已经解决了，在拖拽Combo事件中使用graph.changeSize不断地刷新画布的大小
> 
> 这个方法不太好，建议还是找下根因，一般是图形的属性有问题

好的，我大概知道一些原因了感谢您的答疑。
对了，我还有一个问题想请教您一下，怎样可以获取到combo展开和折叠的状态信息

**Comment by cliffordfajardo** [comment]
@menghaoG - would you be able to create a minimal code reproduction via a codesandbox to showcase the bug?
This would help the G6 team see and assess the buggy behavior more quickly when they revisit this Github issue thread
This is a codesandbox template you can "fork" and edit 😄 
- https://codesandbox.io/s/g607fp

**Comment by Yanyan-Wang** [comment]
> > > > 一般是因为自定义节点中的图形有非法的样式属性值，先排查一下是不是有 NaN、null 等值。没找到的话提供以下复现在线 demo
> > > 
> > > 
> > > 问题已经解决了，在拖拽Combo事件中使用graph.changeSize不断地刷新画布的大小
> > 
> > 
> > 这个方法不太好，建议还是找下根因，一般是图形的属性有问题
> 
> 好的，我大概知道一些原因了感谢您的答疑。 对了，我还有一个问题想请教您一下，怎样可以获取到combo展开和折叠的状态信息

combo.getModel().collapsed 标识的是是否处于收起状态
