### ISSUE TITLE
combo是否支持自定义为平行四边形

### ISSUE THREAD

**Issue by chenxiaobaic** [antvis/G6#3743]
### 问题描述

自定义combo为平行四边形

### 重现链接

无

### 重现步骤

无

### 预期行为

自定义combo分组样式为平行四边形

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome6]
- G6 版本: [4.6.6 ... ]

**Comment by chenxiaobaic** [comment]
暂时用扩展rect实现了  在combo左右两边添加两个三角形遮

**Comment by qq1170623178** [comment]
可否贴出来代码看看

**Comment by chenxiaobaic** [comment]
function registerParallelogramCombo() {
  // 注册平行四边形combo
  G6.registerCombo(
    'parallelogram',
    {
      drawShape: function(cfg: any, group: any) {
        // 倾斜角 根据倾角计算两侧三角形的底边长 	将角度乘以 0.017453293 （2PI/360）即可转换为弧度
        const angle = cfg.angle || 50
        const self = this
        const style = self.getShapeStyle(cfg)
        const bottomLine = style.height / Math.tan(angle * 0.017453293)
        cfg.padding = cfg.padding || [20, 10, 10, 10]
        cfg.canvasColor = cfg.canvasColor || '#ffffff'
        const x = -style.width / 2 - (cfg.padding[3] - cfg.padding[1]) / 2
        const y = -style.height / 2 - (cfg.padding[0] - cfg.padding[2]) / 2
        const polygonShape = group.addShape('rect', {
          attrs: {
            ...style,
            x,
            y,
            width: style.width,
            height: style.height,
            lineWidth: 0,
            strokeOpacity: 0,
          },
          draggable: true,
          name: 'combo-keyShape',
        })

        group.addShape('polygon', {
          attrs: {
            points: [
              [x, y],
              [x, y + style.height],
              [x - bottomLine, y + style.height],
              [x - bottomLine, y + style.height],
            ],
            fill: cfg.style.fill,
            lineWidth: 0,
            strokeOpacity: 0,
            opacity: cfg.style.opacity,
          },
          name: 'left-polygon',
          draggable: true,
        })
        group.addShape('polygon', {
          attrs: {
            points: [
              [x + style.width, y],
              [x + style.width, y + style.height],
              [x + style.width + bottomLine, y],
              [x + style.width + bottomLine, y],
            ],
            fill: cfg.style.fill,
            lineWidth: 0,
            strokeOpacity: 0,
            opacity: cfg.style.opacity,
          },
          name: 'right-polygon',
          draggable: true,
        })
        return polygonShape
      },
      // 定义新增的两侧三角形的位置更新逻辑
      afterUpdate: function afterUpdate(cfg: any, combo: any) {
        const self = this
        const style = self.getShapeStyle(cfg)
        const group = combo.get('group')
        const angle = cfg.angle || 50
        const bottomLine =
          (cfg.style.height + cfg.padding[0] + cfg.padding[2]) /
          Math.tan(angle * 0.017453293)
        // 更新左侧三角形位置
        // 在该 Combo 的图形分组根据 name 找到左侧图形
        const leftPolygon = group.find(
          (ele: any) => ele.get('name') === 'left-polygon',
        )
        leftPolygon.attr({
          // cfg.style.width 与 cfg.style.heigth 对应 rect Combo 位置说明图中的 innerWidth 与 innerHeight
          ...style,
          lineWidth: 0,
          strokeOpacity: 0,
          fill: cfg.style.fill,
          points: [
            [
              -(cfg.style.width / 2 + cfg.padding[3]),
              -cfg.style.height / 2 - cfg.padding[0],
            ],
            [
              -(cfg.style.width / 2 + cfg.padding[3]),
              cfg.style.height / 2 + cfg.padding[2],
            ],
            [
              -(cfg.style.width / 2 + cfg.padding[3]) - bottomLine,
              cfg.style.height / 2 + cfg.padding[2],
            ],
            [
              -(cfg.style.width / 2 + cfg.padding[3]),
              -cfg.style.height / 2 - cfg.padding[0],
            ],
          ],
        })
        // 更新右侧三角形位置
        // 在该 Combo 的图形分组根据 name 找到右侧图形
        const rightPolygon = group.find(
          (ele: any) => ele.get('name') === 'right-polygon',
        )
        rightPolygon.attr({
          // cfg.style.width 与 cfg.style.heigth 对应 rect Combo 位置说明图中的 innerWidth 与 innerHeight
          ...style,
          lineWidth: 0,
          strokeOpacity: 0,
          fill: cfg.style.fill,
          points: [
            [
              cfg.style.width / 2 + cfg.padding[1],
              -cfg.style.height / 2 - cfg.padding[0],
            ],
            [
              cfg.style.width / 2 + cfg.padding[1],
              cfg.style.height / 2 + cfg.padding[2],
            ],
            [
              cfg.style.width / 2 + cfg.padding[1] + bottomLine,
              -cfg.style.height / 2 - cfg.padding[0],
            ],
            [
              cfg.style.width / 2 + cfg.padding[1],
              -cfg.style.height / 2 - cfg.padding[0],
            ],
          ],
        })
      },
    },
    'rect',
  )
}

**Comment by 584sentiment** [comment]
也可以通过path来画一个平行四边形
```js
G6.registerCombo('layer', {
  drawShape(cfg, group) {
    const width = cfg.style?.width || 100; // Combo 的宽度，默认为 100
    const height = cfg.style?.height || 60; // Combo 的高度，默认为 60
    const x = -width / 2; // Combo 的 x 坐标
    const y = -height / 2; // Combo 的 y 坐标
    // 绘制平行四边形的路径
    const path = [
      ['M', x, y],
      ['L', x + width, y],
      ['L', x - width * 0.5, y + height],
      ['L', x - width * 1.5, y + height],
      ['Z'],
    ];
    // 添加平行四边形的图形
    const shape = group.addShape('path', {
      attrs: {
        path,
        fill: '#e6f7ff', // 填充色
        stroke: '#1890ff', // 边框颜色
        lineWidth: 2, // 边框宽度
        opacity: 1, // 透明度
      },
      draggable: true, // 是否可拖拽
    });
    return shape;
  }
}, 'rect');
```
