### ISSUE TITLE
fruchterman布局下，更新节点的icon.show，布局抖动

### ISSUE THREAD

**Issue by grainnn** [antvis/G6#3746]
### 问题描述

在fruchterman布局模式下，通过node.update更新节点的icon.show: true -> false，节点的布局发生了改变

### 重现链接

https://codesandbox.io/s/stupefied-keldysh-jvk0q3?file=/index.js

### 重现步骤

1. 鼠标hover到某个节点上，通过node.update隐藏不相关的节点；
2. 节点的布局发生了改变

### 预期行为

期望node.update执行后，节点位置不改变

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Firefox]
- G6 版本: [4.6.6]

**Comment by Yanyan-Wang** [comment]
更新局部不需要调用 graph.render，它会触发全局渲染+布局。对图元素的所有等操作一律收口到 graph 上，如 graph.updateItem
