### ISSUE TITLE
combo中的label设置居中

### ISSUE THREAD

**Issue by xiziliang** [antvis/G6#3750]
### 问题描述

目前看到只有设置`position: 'center'`时，label会水平和垂直居中且不能通过refY和refX进行修改，但是大多数时候只用到水平或者垂直，再通过refY和refX细微调整，而不是两个居中都用到。

### 重现链接

无

### 重现步骤

无

### 预期行为

期望能把`position: 'center'`拆成垂直和水平居中。

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
欢迎社区小伙伴共建

**Comment by yanhan569046480** [comment]
同问
![image](https://user-images.githubusercontent.com/1505382/180734959-bbfbc71d-26b5-4694-8dec-30fcd604bd10.png)
![image](https://user-images.githubusercontent.com/1505382/180735025-26c5fd66-ab8b-4f62-a11a-a3b9a9457af8.png)
![image](https://user-images.githubusercontent.com/1505382/180735297-2697c378-ea6f-4bb5-ac2b-d632101c0ff0.png)
想实现如上图1所示的效果，combo的label居中显示并且上下有一些间距，还有节点下面的文字也与上方有些间距，按图3设置了一圈没有变化，不知道写法不对还是不支持？

**Comment by xiziliang** [comment]
> 
combo的文字目前没有单独的水平居中，我用的是`position: 'top',`, `refY`,`refX`,来实现的

**Comment by yanhan569046480** [comment]
> > 
> 
> combo的文字目前没有单独的水平居中，我用的是`position: 'top',`, `refY`,`refX`,来实现的

![image](https://user-images.githubusercontent.com/1505382/180917233-be00672c-cc61-4b89-8599-fb0eb9420b9a.png)
![image](https://user-images.githubusercontent.com/1505382/180917275-4c001efa-ee35-484c-84c6-5bfeb1928d1d.png)
我也按你说的这样设置了，没什么效果，版本是最新的

**Comment by xiziliang** [comment]
> > > 
> > 
> > 
> > combo的文字目前没有单独的水平居中，我用的是`position: 'top',`, `refY`,`refX`,来实现的
> 
> ![image](https://user-images.githubusercontent.com/1505382/180917233-be00672c-cc61-4b89-8599-fb0eb9420b9a.png) ![image](https://user-images.githubusercontent.com/1505382/180917275-4c001efa-ee35-484c-84c6-5bfeb1928d1d.png) 我也按你说的这样设置了，没什么效果，不仅label没有居中，内边距也是纹丝不动，版本是最新的

https://codesandbox.io/s/cranky-jasper-2v98j7?file=/index.js
我在最新版上也是正常的

**Comment by yanhan569046480** [comment]
> 

好的，谢谢，我换个写法试试

**Comment by yanhan569046480** [comment]
![image](https://user-images.githubusercontent.com/1505382/180944120-af3cf070-091f-4c70-878d-d40c88eec781.png)
![image](https://user-images.githubusercontent.com/1505382/180945960-27cd57b6-8fc0-4cfb-856d-9e2f8580ddcc.png)
我又折腾了半天，没啥效果，我这里用的graphin，掘金上说graphin已经是数据驱动的了，可以根据数据的变化自动更新图表，但是我这里咋没有用呢？我把数据更新和graphinRef.current.graph.data(graphinDataCopy)都加上了，图表并不会随着数据更新而变化，什么原因呢？

**Comment by xiziliang** [comment]
<img width="681" alt="image" src="https://user-images.githubusercontent.com/54427136/181413696-fb915f60-5720-4703-9054-bc6d94bc0933.png">

或者试试监听到数据变化，销毁画布，重新在画一遍

**Comment by yanhan569046480** [comment]
> 

好的，已解决，谢谢

**Comment by Yanyan-Wang** [comment]
v4.7.17 已支持，rect 类型的 combo 在 labelCfg.position 配置 'top-center'
