### ISSUE TITLE
defaultEdge 能否设置getControlPoints函数？期望动态计算，而不是一个节点一节点设置

### ISSUE THREAD

**Issue by yinhunfeixue** [antvis/G6#3752]
### 问题描述

![image](https://user-images.githubusercontent.com/29660825/175754858-992367c9-8998-4a65-aa97-08c330f733f4.png)

如上图设置是无效的，请问是否可设置，需要在哪里设置？

### 重现链接

暂无

### 重现步骤

暂无

### 预期行为

期望getControlPoints有效，但实际无效

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
可以继承内置边，进行自定义：

https://g6.antv.vision/zh/examples/item/customEdge#customPolyline
