### ISSUE TITLE
comboCombined布局下innerLayout的grid中sortBy不生效

### ISSUE THREAD

**Issue by person001** [antvis/G6#3753]
### 问题描述

g6版本4.6.6，再内网环境下，使用comboCombined做整体布局，innerLayout使用的是grid布局。sortBy不生效。
代码： layout: {
  type: 'comboCombined',
  innerLayout: new G6.layout['grid']({
     sortBy: 'cluster'
    })}

### 重现链接

CodeSandbox

### 重现步骤

页面直接显示

### 预期行为

应该是有规则的排序，但并没有出现

### 平台

- 操作系统: [Windows.]
- 网页浏览器: Google Chrome
- G6 版本: [4.6.6  ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/34431484/175769872-952d1f9e-e210-4627-aa4e-844b355a800d.png)

### 补充说明（可选）

如图所示，前面的数字是排序的sortby，但是并没有出现预期的效果

**Comment by person001** [comment]
![微信图片_20220625184425](https://user-images.githubusercontent.com/34431484/175770198-6e9b3d1a-6b8e-45ec-a175-ce0b5133b468.png)
修改官网demo，出现了同样的情况，希望能够得到回复！

**Comment by Yanyan-Wang** [comment]
请将 @antv/layout 升级到 0.2.5 即可解决

**Comment by person001** [comment]
收到，有效果，谢谢大佬@Yanyan-Wang
