### ISSUE TITLE
运行后报出错误

### ISSUE THREAD

**Issue by xiao-2** [antvis/G6#3754]
### 问题描述

运行后报错，
![image](https://user-images.githubusercontent.com/59162043/175818521-a049fc71-ebfb-427d-b5be-0c51f475b102.png)
但是我不确定是ts的问题还是其他问题

### 重现链接

https://g6.antv.vision/zh/docs/api/Behavior

### 重现步骤

运行后，不报错误

### 预期行为

不报错误

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
感谢报告，是类型问题，今天会发小版本修复

**Comment by Yanyan-Wang** [comment]
v4.6.10 已修复
