### ISSUE TITLE
g6-core依赖升级0.6.8之后出现layout布局错误

### ISSUE THREAD

**Issue by JunJianSyu** [antvis/G6#3756]
### 问题描述

relayout failed TypeError: Cannot set properties of undefined (setting 'onLayoutEnd') at eval 
https://github.com/antvis/G6/commit/778720cc89866ba150ad6aeeb8695d5b41b4636f 
改动commit 定位问题在layout

### 重现链接

https://github.com/antvis/G6/commit/778720cc89866ba150ad6aeeb8695d5b41b4636f

### 重现步骤

graph.updateItem(nodeId, data) 或者 graph.layout() 之后
relayout failed TypeError: Cannot set properties of undefined (setting 'onLayoutEnd') at eval 

### 预期行为

无报错，正常渲染画布

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 补充说明（可选）

"@antv/g6-core": "0.6.6" 无此问题

**Comment by Yanyan-Wang** [comment]
v4.6.10 已修复
