### ISSUE TITLE
如何实现小地图minimap的点击事件获取？

### ISSUE THREAD

**Issue by zwb234** [antvis/G6#3757]
### 问题描述

如题，想实现小地图minimap类似于在画布空白处点击的blank:click点击事件，并可以抛出，如何实现？

### 重现链接

无

### 重现步骤

无

### 预期行为

预期抛出对应的事件，例如minimap:click等

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
minimap.get('canvas').on('click', e => { e.target 表示被点击的图形/画布 })

**Comment by Yanyan-Wang** [comment]
考虑抛出 minimap 的各类事件

**Comment by NotACoder2001** [comment]
> minimap.get('canvas').on('click', e => { e.target 表示被点击的图形/画布 })

由于minimap对应Canvas上有一个小的div遮挡，导致无法获取真正的minimap事件，因此应该是用如下方法在这个小的div添加事件：
 minimap.getContainer().addEventListener("dragend",evt=>{
      evt.target ...
    })

**Comment by NotACoder2001** [comment]
> minimap.get('canvas').on('click', e => { e.target 表示被点击的图形/画布 })



由于minimap对应Canvas被一个小的div遮挡，导致无法获取真正的minimap事件。可以考虑采用如下方法直接在minimap的容器div添加事件监听：
minimap.getContainer().addEventListener("click",evt=>{
evt.target ...
})
