### ISSUE TITLE
实例化时候，Combo.addChild(node)添加节点给Combo，随后讲该节点拖动离开Combo，但是节点还跟Combo互相绑定

### ISSUE THREAD

**Issue by GiannaJun1030** [antvis/G6#3761]
### 问题描述

实例化时候，Combo.addChild(node)添加节点给Combo，随后讲该节点拖动离开Combo，但是节点还跟Combo互相绑定

### 重现链接

..

### 重现步骤

1、初始化，
2、讲节点移出容器（Combo）
3、拖动Combo，发现节点跟着容器移动，未解绑

### 预期行为

预期首次初始化后，Combo.addChild 添加节点到该容器上，后面拖动节点移出容器，可以解绑

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.6.8 ... ]

import G6 from '@antv/g6';

const data = {
  nodes: [
    {
      id: 'node2',
      x: 350,
      y: 150,
    },
    {
      id: 'node4',
      x: 450,
      y: 300,
    },
  ],
  combos: [
    {
      id: 'combo',
      label: 'Combo',
      size:[300,300],
      x: 450,
      y: 300,
    },
  ],
};

console.log(G6.version)

const width = document.getElementById('container').scrollWidth;
const height = document.getElementById('container').scrollHeight || 500;
const graph = new G6.Graph({
  container: 'container',
  width,
  height,
  // translate the graph to align the canvas's center, support by v3.5.1
  fitCenter: true,
  // Set groupByTypes to false to get rendering result with reasonable visual zIndex for combos
  groupByTypes: false,
  modes: {
    default: ['drag-canvas', 'drag-node', 'drag-combo', 'collapse-expand-combo'],
  },
  defaultCombo: {
    type: 'rect',
    /* The minimum size of the combo. combo 最小大小 */
    size: [50, 50],
    /* style for the keyShape */
    // style: {
    //   lineWidth: 1,
    // },
    labelCfg: {
      position: 'top',
    },
  },
});

graph.data(data);
graph.render();
graph.getNodes().forEach(node=>{
  node.toFront()
  graph.getCombos()[0].addChild(node)
});

graph.on('combo:mouseenter', (evt) => {
  const { item } = evt;
  graph.setItemState(item, 'active', true);
});

graph.on('combo:mouseleave', (evt) => {
  const { item } = evt;
  graph.setItemState(item, 'active', false);
});
graph.on('combo:click', (evt) => {
  const { item } = evt;
  graph.setItemState(item, 'selected', true);
});
graph.on('canvas:click', (evt) => {
  graph.getCombos().forEach((combo) => {
    graph.clearItemStates(combo);
  });
});

### 屏幕截图或视频（可选）

Uploading 2022-06-28 18-44-47.mp4…

**Comment by GiannaJun1030** [comment]
目前暂时找到的解决方法   就是 在这个监听事件里面做回调 dragnodeend

**Comment by Yanyan-Wang** [comment]
使用 graph 的 API 来进行所有元素的操作 https://g6.antv.vision/zh/docs/api/graphFunc/item#graphupdatecombotreeitem-parentid

**Comment by willow001** [comment]
请问树图支持平行边吗

**Comment by GiannaJun1030** [comment]
> 使用 graph 的 API 来进行所有元素的操作 https://g6.antv.vision/zh/docs/api/graphFunc/item#graphupdatecombotreeitem-parentid

谢谢

**Comment by cliffordfajardo** [comment]
Hi @GiannaJun1030 - is this issue resolved with the new information that @Yanyan-Wang  provided?
if so, can you mark it as closed?

**Comment by Yanyan-Wang** [comment]
Hi, dear user. Since there was no response for a long time, we cannot figure out the answer of the problem you described. If there is new progress, feel free to open a new issue.
