### ISSUE TITLE
如何提前计算坐标但不进行前端渲染

### ISSUE THREAD

**Issue by JiangGeGe123** [antvis/G6#3762]
### 问题描述

我的图谱在3000个节点时达到了惊人的60s布局时间，这显然无法让客户满意。尽管我们已经用了各种优化方式，并且开启了gForce的GPU，但还是降不到20s以下。所以我们想将坐标缓存下来。
但我们发现坐标的计算和前端渲染是连在一起的，根本无法分开。文档上也招不到相关api。
请问是否有后端纯计算坐标、不渲染的方法？

![image](https://user-images.githubusercontent.com/9131591/176336742-29139e0c-5200-4218-9ca1-04fdd7640c7a.png)

### 重现链接

https://codesandbox.io/s/demo-forked-7jd8lh?file=/index.js:914-926

### 重现步骤

render执行完毕后存储坐标

### 预期行为

希望能够将render()的步骤拆成两步，一步计算坐标，一步渲染

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.6.4]

**Comment by Yanyan-Wang** [comment]
> 但我们发现坐标的计算和前端渲染是连在一起的，根本无法分开

并不是连在一起的。

不配置 layout 到 graph 上，在后端产出数据的时候算好坐标给到每个节点的数据中的 x y 上，传到前端给 graph 渲染即可。G6 在没有配置 layout 的情况下，会根据数据中的 x y 进行渲染节点。如果数据中没有 x y，将会被初始化为格子布局。

**Comment by JiangGeGe123** [comment]
@Yanyan-Wang  这个我们已经知道，问题是后端产出数据的时候如何算好坐标？ gForce的算法是否有接口供调用？ 目前只能在第一次渲染后，从graph.save()中拿到坐标。能否跳过前端渲染这一步，直接调用内置运算函数，不显示图谱就能拿到坐标？

**Comment by Yanyan-Wang** [comment]
后端可以用自己的算法去算布局，也可以尝试在服务端调用 G6 的布局算法，使用类似：https://g6.antv.vision/zh/docs/manual/middle/layout/sub-layout

或者直接使用 G6 底层的布局库 @antv/layout

**Comment by willow001** [comment]
请问树图，支持平行边吗

**Comment by JiangGeGe123** [comment]
@Yanyan-Wang 
还有一点，execute()后，只有nodes上附着了坐标，edges上面并没有起始点的坐标，这可能无法满足需要

**Comment by Yanyan-Wang** [comment]
> 请问树图，支持平行边吗

不支持

**Comment by Yanyan-Wang** [comment]
> @Yanyan-Wang 打扰！ const subgraphLayout = new G6.Layout[layoutConfig.type]({ center: [width / 2, height / 2], }); subgraphLayout.init(normalizedData); subgraphLayout.execute(); 我按这个方法进行布局运算，3000个节点一般graph.render()只需要2分钟就可以出结果，可换成这个不render的方法，却20分钟了还卡在那里，也不报错。
> 
> 为何execute()比render()还慢？

给个复现 demo？

**Comment by Yanyan-Wang** [comment]
> @Yanyan-Wang 还有一点，execute()后，只有nodes上附着了坐标，edges上面并没有起始点的坐标，这可能无法满足需要

边上没有必要需要坐标，它绘制的时候会去找到起点终点坐标来决定自己的绘制方式

**Comment by Yanyan-Wang** [comment]
4.7.0-beta.2 推出新的力导布局 force2
该布局性能大幅度提升，可以尝试看是否能够满足中等规模的前端实时布局计算

尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
