### ISSUE TITLE
如何获取节点自定义属性

### ISSUE THREAD

**Issue by luokeqiang** [antvis/G6#3764]
### 问题描述

比如我的节点是这种格式：
nodes = [
    {
        id: 'node-0',
        label: '组织一',
        category: '0', // 自定义属性
    } 
]
当我使用 item.getModel().category 时取不到自定义的属性数据

### 重现链接

无

### 重现步骤

无

### 预期行为

item.getModel().category === ‘0’

### 平台

- 操作系统: Windows
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.6.4 ... ]

**Comment by Yanyan-Wang** [comment]
应该是可以的，具体要看下是怎么实现的，提供一下在线复现 demo
