### ISSUE TITLE
changeSize后再fitview，无效

### ISSUE THREAD

**Issue by yinhunfeixue** [antvis/G6#3766]
### Describe the bug

 window.addEventListener('resize', ()=>{
   graph.changeSize(container.offsetWidth, container.offsetHeight)

})

button.onclick = ()=>{
   graph.fitview()
}

直接点按钮，可以看到所有结点；先调整浏览器尺寸，再点击按钮，看不到所有结点。

### Your Example Website or App

暂无

### Steps to Reproduce the Bug or Issue

暂无

### Expected behavior

暂无

### Platform

chrome,  edge

**Comment by Yanyan-Wang** [comment]
请给出在线复现 demo

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
