### ISSUE TITLE
drawBackground的一个bug

### ISSUE THREAD

**Issue by zwb234** [antvis/G6#3767]
### 问题描述

使用两次drawBackground()方法，如果两次drawBackground()间隔时间短导致前一次drawBackground()未执行完，则最终生效的是第一个drawBackground()，而不是第二个drawBackground()。

### 重现链接

无

### 重现步骤

this.drawBackground({
  size: width_1,
  color: color_1,
  image: image_1,
})
this.drawBackground({
  size: width_2,
  color: color_2,
  image: image_2,
})
直接执行，最终页面的背景是color_1，image_1。

### 预期行为

我期望看到的背景是color_2，image_2，但我看到的是color_1，image_1。

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
drawBackground 是什么？不是 G6 中的方法。请提供准确描述并给出在线复现 demo 再新建 issue 哈。这个 issue 就先关闭了

**Comment by zwb234** [comment]
> drawBackground 是什么？不是 G6 中的方法。请提供准确描述并给出在线复现 demo 再新建 issue 哈。这个 issue 就先关闭了

这个问题我已经解决了哈，感谢~~
