### ISSUE TITLE
ant tabs组件中使用g6，无法准确的操作当前tab中的g6组件

### ISSUE THREAD

**Issue by ksl594303117** [antvis/G6#3768]
### Describe the bug

场景：使用ant - tabs组件，并且各tab拥有独立的g6组件，此时无法正常更新当前tab中g6数据源。

### Your Example Website or App

公司项目，不太方便写，备注中有相关代码

### Steps to Reproduce the Bug or Issue

复现问题：假设打开tab1，tab2，此时切换回tab1，并且动态更新g6数据源，此时tab1没有更新，但是tab2更新。经排查多个tab时，会用最新tab中的g6 graph去更新数据。

### Expected behavior

期望结果：可以正常更新当前tab的数据源

### Platform

- OS: macOS
- Browser:Chrome
- Version: 102.0.5005.61

### Additional context

目前解决：切换tab时只保留当前tab的g6组件，其他页签不展示。

问题：上述解决方法是否正确？如果不使用上述方法，这个问题怎么解决呢？求大佬解惑🙏

备注：每个tab中有两个组件，一般的ant组件数据处理正确，g6组件数据处理不正确，所以初步排查是g6组件问题。

相关代码：
1、父组件 home.jsx
![image](https://user-images.githubusercontent.com/20100608/176659380-7b392d34-6ad9-453c-9457-5ba7ec9950b6.png)

2、子组件 Relations.jsx
![image](https://user-images.githubusercontent.com/20100608/176659806-c647e71a-e835-40c7-b0ca-f2224892ce56.png)

3、g6组件 G6Node.js
常规使用 new G6.Graph() 进行创建

**Comment by ksl594303117** [comment]
不知道为什么【相关代码】中1有些空白，补一下：
resHtml = <TabPane tab={title} key={feKey} closable={closable}>
               < Relations tabDataSource={tabDataSource} />
              </TabPane>

**Comment by Yanyan-Wang** [comment]
确保不同 tab 中的 graph 实例以及数据是独立的不是共享的，并确保更新的数据源是传入正确的子组件。非必要情况下不触发其它 tab 的更新。G6 与框架无关，我想这是你的 React 代码问题，和 G6 关系不大。

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
