### ISSUE TITLE
滚轮缩放后将节点拖进画布发现位置会发生偏移，是否有改进方案

### ISSUE THREAD

**Issue by onlinegenerator** [antvis/g6#377]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by TomHuangCN** [comment]
轻按模版详细描述问题

**Comment by nameliuqi** [comment]
之前做过类似的，需要把画布同时做适当的平移，保证当前鼠标位置相对于屏幕的绝对位置不变，就是你想要的结果
