### ISSUE TITLE
Brush-Select is not selecting the nodes inside the area

### ISSUE THREAD

**Issue by masosky** [antvis/G6#3775]
### Describe the bug

When we try to select nodes using the `brush-select` nodes, sometimes the nodes are not selected, and sometimes yes. We provide a video of when this behavior is happening.
It is like sometimes the callbacks `onSelect` and `onDeselect` are not called

### Your Example Website or App

https://stackblitz.com/edit/react-ts-gz9d4w?file=package.json,index.tsx

### Steps to Reproduce the Bug or Issue

1. Go to https://stackblitz.com/edit/react-ts-gz9d4w?file=package.json,index.tsx
2. Try to select both nodes using `shift` key
3. Sometimes the nodes are not selected and sometimes yes.

### Expected behavior

We expected that when selecting, the nodes inside the area are selected. But nowadays it is like sometimes it is not happening

### Screenshots or Videos

https://user-images.githubusercontent.com/25633662/177149238-01522fa5-a6ef-4349-b96b-00563c581df2.mov

### Platform

- https://stackblitz.com/edit/react-ts-gz9d4w?file=package.json,index.tsx
- G6 Version: 4.6.15
- Chrome Version 104.0.5112.101 (Official Build) (arm64)
- macOS Monterey 12.5
- Chip: Apple M1 Pro

**Comment by masosky** [comment]
Hi guys,

Do you have any update?

Thanks!

**Comment by Yanyan-Wang** [comment]
did not reproduce it on your demo. I checked the source code, is it possible that you released the 'shift' before mouseup?

**Comment by masosky** [comment]
Actually, I can make it using the shift key. But sometimes is not working as well

**Comment by Yanyan-Wang** [comment]
What is your OS and browser? Make sure release shift key before releasing your mouse

**Comment by masosky** [comment]
Chrome Version 104.0.5112.101 (Official Build) (arm64)

**Comment by masosky** [comment]
Actually, you are right. If I release the mouse first works. But if I release the shift first is not working

**Comment by Yanyan-Wang** [comment]
I think it is in line with expectations.  Shift is the key you configured for the brush-select. Releasing the key before the behavior(drag process: mousedown mousemove mouseup) finished, means the behavior is interrupted and canceled.
