### ISSUE TITLE
error linking program with vertex shader  fragment shader unknown

### ISSUE THREAD

**Issue by zxw394** [antvis/G6#3776]
### 问题描述

**浏览器版本chrome81**
G6树，在展开第四级节点后（7k条数据）报如上错误，并且始终是loading状态
`
    function updateAll() {
      let nodes = this.datas.nodes.filter(r => r.show)
      let edges = this.datas.edges.filter(r => r.show)
      graph.data({
        nodes: nodes,
        edges: edges,
      })
      graph.render()
    }
`
以上是更新的方法

### 重现链接

项目地址

### 重现步骤

G6树，在展开第四级节点后（7k条数据）报如上错误，并且始终是loading状态

### 预期行为

与最新chrome浏览器一样能正常展示

### 平台

windows 10

**Comment by Yanyan-Wang** [comment]
看起来并不是 G6 报出来的错误？提供一下在线复现 demo

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
