### ISSUE TITLE
G6 中布局node节点设置x、y,又设置layout，layout会覆盖node节点的x、y位置，有没有办法，可以使两者共存，互不影响

### ISSUE THREAD

**Issue by g6success** [antvis/G6#3779]
### 问题描述

G6 中布局node节点设置x、y,又设置layout，layout会覆盖node节点的x、y位置，有没有办法，可以使两者共存，互不影响
![image](https://user-images.githubusercontent.com/108798881/177525036-4274d0db-92ed-4b26-9933-21ef64b01af7.png)
![image](https://user-images.githubusercontent.com/108798881/177525115-705c1b1f-2970-4857-9858-6de807db3a8b.png)

### 重现链接

无

### 重现步骤

![image](https://user-images.githubusercontent.com/108798881/177525036-4274d0db-92ed-4b26-9933-21ef64b01af7.png)
![image](https://user-images.githubusercontent.com/108798881/177525115-705c1b1f-2970-4857-9858-6de807db3a8b.png)

### 预期行为

我希望看到layout设置不会影响node节点中的x、y位置的设置

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]
Windows

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/108798881/177525036-4274d0db-92ed-4b26-9933-21ef64b01af7.png)
![image](https://user-images.githubusercontent.com/108798881/177525115-705c1b1f-2970-4857-9858-6de807db3a8b.png)

### 补充说明（可选）

左右两侧柱状图固定，中间显示一点点位信息和柱子相连

**Comment by Yanyan-Wang** [comment]
不可以，一旦配置了布局，计算的优先级高于数据中的位置。我理解你这里可以在布局完成之后去更新你想要固定的节点位置，比如 graph.on('afterlayout', e => { graph.updateItem(xxnode, { x: 10, y: 10})})

**Comment by SimNull1307** [comment]
考虑一下fx,fy,不知是否符合你的需求

**Comment by Yanyan-Wang** [comment]
fx fy 仅在力导家族布局中生效

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。

**Comment by g6success** [comment]
> 不可以，一旦配置了布局，计算的优先级高于数据中的位置。我理解你这里可以在布局完成之后去更新你想要固定的节点位置，比如 graph.on('afterlayout', e => { graph.updateItem(xxnode, { x: 10, y: 10})})

谢谢~，我这边用的自定义布局解决的

**Comment by g6success** [comment]
> 考虑一下fx,fy,不知是否符合你的需求

谢谢~，我这边用的自定义布局解决的

**Comment by onecaihong** [comment]
自定义布局有例子吗
