### ISSUE TITLE
拖拽、放大

### ISSUE THREAD

**Issue by chaodiangen** [antvis/G6#3780]
### Describe the bug

1、点击节点能够获取节点的size 和中心圆的坐标，拖拽之后中心元的左边可以跟着改变吗？
2、放大之后获取当前节点的size

### Your Example Website or App

 https://stackblitz.com/

### Steps to Reproduce the Bug or Issue

1、放大、拖拽 无法计算节点中心坐标和size

### Expected behavior

1、拖拽之后节点或者画布，可以一个节点，可以获取拖拽之后的位置
2、放大或缩小可以获取节点的size

### Platform

- OS: [e.g.  Windows]
- Browser: [e.g. Chrome]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
没懂什么意思

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
