### ISSUE TITLE
r[s] is not a function

### ISSUE THREAD

**Issue by dafulala** [antvis/G6#3781]
### 问题描述

在拖动一次后，就会出现下面的错误，然后点的动画消失，不知道是不是和这个错误有关系

### 重现链接

https://codesandbox.io/embed/black-hooks-5x64yg?fontsize=14&hidenavigation=1&theme=dark

### 重现步骤

直接拖动一个点，拖动第二个点时动画失效

### 预期行为

动画不应该失效，但是在CodeSandbox内没有报错，

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

<img width="830" alt="WX20220707-105232@2x" src="https://user-images.githubusercontent.com/29862602/177680455-ce617820-4e04-49f5-a793-0885261363ed.png">

**Comment by Yanyan-Wang** [comment]
demo 中没有复现错误。动画是因为在布局过程中，第二次拖拽节点没动画了，应该只是因为布局计算结束了。是符合预期的

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
