### ISSUE TITLE
shouldEnd 的 item为null

### ISSUE THREAD

**Issue by 344089386** [antvis/G6#3783]
### 问题描述

version：4.6.15
我拖拽节点的时候 shouldEnd 方法的  e.item 为null，请问这个是什么问题？

![image](https://user-images.githubusercontent.com/22017199/177724997-66f7cc27-ba1f-4c1f-b99b-7196bc3a3e95.png)

const graph = new G6.Graph({
        container: 'mountNode',
        groupByTypes: false,
        modes: {
            default: ["zoom-canvas", "drag-canvas", {
                type: 'drag-node',
                enableDelegate: true,
                shouldBegin: (e) => {
                    dragNodeItem = null;
                    if (e.item) {
                        dragNodeItem = e.item.getModel();
                        return true;
                    }
                    return false;
                },
                shouldEnd: (e, item) => {
                    debugger
                    if (dragNodeItem) {
                        var node = dragNodeItem;
                        service.updateLocation(node.id, e.x, e.y);
                    }
                    return true;
                }
            }, {
                type: 'drag-combo',
                enableDelegate: true,
                shouldUpdate: (e) => {
                    return true;
                },
                shouldEnd: (e, newParent) => {
                    debugger
                    if (e.item) {
                        var combo = e.item.getModel();
                        service.updateLocation(combo.id, e.x, e.y);
                    }
                    return true;
                }
            }]
        },
        defaultNode: {
            shape: "rect",
            size: [100, 50]
        },
        defaultCombo: {
            type: 'layoutRect',
            style: {
                fill: '#fff',
                stroke: '#fd7e14',
                lineWidth: 2,
                fillOpacity: 0.7
            },
        },
        nodeStateStyles: {
            click: {
                lineWidth: 3,
            }
        }
    });

### 重现链接

https://bdt4w6.csb.app/%E7%B4%A2%E5%BC%95.html

### 重现步骤

1、拖拽节点

### 预期行为

报错的地方应该不是null 才对吧？

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.6.15]

**Comment by cliffordfajardo** [comment]
@344089386  - would you be able to create a minimal code reproduction via a codesandbox to showcase the bug?
This would help the G6 team see and assess the buggy behavior more quickly?
This is a codesandbox template you can "fork" and edit 😄 
- https://codesandbox.io/s/g607fp

**Comment by 344089386** [comment]
> @344089386 - 你能通过代码沙箱创建一个最小的代码复制来展示这个错误吗？ 这将有助于 G6 团队更快地查看和评估错误行为吗？ 这是一个您可以“分叉”和编辑的代码框模板😄
> 
> * https://codesandbox.io/s/g607fp


This link can reproduce the error:

https://bdt4w6.csb.app/%E7%B4%A2%E5%BC%95.html

**Comment by Yanyan-Wang** [comment]
drop 事件接收的对象是“被释放到”的元素，例如节点 A 释放到节点 B 上，那么 B 接收到 drop 事件。你截图中 item 是 null，应该是因为 drop 到了画布上，canvas 接收的 drop 事件

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
