### ISSUE TITLE
文字右侧有一段空白

### ISSUE THREAD

**Issue by yinhunfeixue** [antvis/G6#3785]
### Describe the bug

```
  <Rect style={{ stroke: '#ff0000' }}>
                                <Text style={{ ...useTextStyle, fontFamily: 'iconfont', fontSize: 16 }}>{unescape('%ue6c5')} {count ? count.toString() : '0'}</Text>
</Rect>
```

![image](https://user-images.githubusercontent.com/29660825/178096210-19292660-ca64-4129-a456-5b749f5314e5.png)

未设置右侧间距，但是渲染出来却有一段空白

### Your Example Website or App

暂无

### Steps to Reproduce the Bug or Issue

见上图

### Expected behavior

见上图

### Platform

- OS: macos
- Browser: chrome

**Comment by Yanyan-Wang** [comment]
Text 设置 textAlign: 'center'

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
