### ISSUE TITLE
导出图片无法导出完整

### ISSUE THREAD

**Issue by seven00000** [antvis/G6#3786]
### Describe the bug

导出功能，节点数过多，会报错，无法导出完整的图片

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

试一下节点数很多的情况下去进行导出

### Expected behavior

我希望导出功能可以导出完整的图片

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by seven00000** [comment]
No data returned.
https://codesandbox.io/s/adoring-wilbur-7b6r1r?file=/index.js




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/G6"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月21日(星期四) 下午4:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [antvis/G6] 导出图片无法导出完整 (Issue #3786)





 
@seven00000 - would you be able to create a minimal code reproduction via a codesandbox to showcase the bug?
 This would help the G6 team see and assess the buggy behavior more quickly?
 This is a codesandbox template you can "fork" and edit 😄
  
https://codesandbox.io/s/g607fp

**Comment by Yanyan-Wang** [comment]
导出内容过大，canvas 原生 API 导出如此巨大的图片会失败。考虑将图范围缩小后导出，例如使缩小画布、布局更紧凑、仅导出部分等

**Comment by seven00000** [comment]
“考虑将图范围缩小后导出，例如使缩小画布、布局更紧凑、仅导出部分等”，这些办法都尝试过，不仅导出的图片很模糊，而且仍然存在导出失败的情况。这个还有解决的余地吗？

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/G6"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月29日(星期五) 上午10:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [antvis/G6] 导出图片无法导出完整 (Issue #3786)





 
导出内容过大，canvas 原生 API 导出如此巨大的图片会失败。考虑将图范围缩小后导出，例如使缩小画布、布局更紧凑、仅导出部分等

**Comment by Yanyan-Wang** [comment]
图片模糊尝试通过 graph.get('canvas').set('pixelRatio', x) 设置 x 为一个比较大的值。导出之后恢复到  window.devicePixelRatio

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
