### ISSUE TITLE
树图节点是rect型时，宽度不一致时如何左/右对齐，而不是默认居中对齐？

### ISSUE THREAD

**Issue by tusikongkong** [antvis/G6#3787]
### 问题描述

https://g6.antv.vision/zh/examples/tree/customItemTree#customTree
期望像这个示例的缩略图一样宽度不一致的rect节点右对齐，现状是居中对齐，且没找到合适的配置

### 重现链接

null

### 重现步骤

null

### 预期行为

期望rect型节点的树图像示例的缩略图一样，宽度不一致右对齐

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
你是希望节点左对齐？自定义节点中，内置 rect 以及示例中的自定义节点，draw 方法中添加的所有图形的 x y 均为整个节点宽高的一半（见该示例的 Line32-41）。如果你希望左对齐，需要在你的自定义节点中，draw 方法中添加的所有图形以 x: 0, y: 0 为原点进行偏移

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
