### ISSUE TITLE
vite 引入g6 v3.5.2, 运行报错

### ISSUE THREAD

**Issue by huangyiman** [antvis/G6#3789]
[npm引入g6 v3.8.3, 运行报错

> (this will be run only when your dependencies or config have changed)
 > node_modules/@antv/matrix-util/esm/vec2.js:3:5: error: Cannot assign to import "angle"
    3 │ vec2.angle = function (v1, v2) {
      ╵      ~~~~~

 > node_modules/@antv/matrix-util/esm/vec2.js:13:5: error: Cannot assign to import "direction"
    13 │ vec2.direction = function (v1, v2) {
       ╵      ~~~~~~~~~

 > node_modules/@antv/matrix-util/esm/vec2.js:16:5: error: Cannot assign to import "angleTo"
    16 │ vec2.angleTo = function (v1, v2, direct) {
       ╵      ~~~~~~~

 > node_modules/@antv/matrix-util/esm/mat3.js:2:5: error: Cannot assign to import "translate"
    2 │ mat3.translate = function (out, a, v) {
      ╵      ~~~~~~~~~

 > node_modules/@antv/matrix-util/esm/mat3.js:7:5: error: Cannot assign to import "rotate"
    7 │ mat3.rotate = function (out, a, rad) {
      ╵      ~~~~~~

 > node_modules/@antv/matrix-util/esm/mat3.js:12:5: error: Cannot assign to import "scale"
    12 │ mat3.scale = function (out, a, v) {
       ╵      ~~~~~

 > node_modules/@antv/matrix-util/esm/mat3.js:17:5: error: Cannot assign to import "transform"
    17 │ mat3.transform = function (m, actions) {
       ╵      ~~~~~~~~~

 > node_modules/@antv/matrix-util/esm/vec2.js:30:5: error: Cannot assign to import "vertical"
    30 │ vec2.vertical = function (out, v, flag) {
       ╵      ~~~~~~~~

error when starting dev server:
Error: Build failed with 8 errors:
node_modules/@antv/matrix-util/esm/mat3.js:2:5: error: Cannot assign to import "translate"
node_modules/@antv/matrix-util/esm/mat3.js:7:5: error: Cannot assign to import "rotate"
node_modules/@antv/matrix-util/esm/mat3.js:12:5: error: Cannot assign to import "scale"
node_modules/@antv/matrix-util/esm/mat3.js:17:5: error: Cannot assign to import "transform"
node_modules/@antv/matrix-util/esm/vec2.js:3:5: error: Cannot assign to import "angle"
...
    at failureErrorWithLog (D:\workspace\zy_admin\zy_admin_ui\node_modules\esbuild\lib\main.js:1493:15)
    at D:\workspace\zy_admin\zy_admin_ui\node_modules\esbuild\lib\main.js:1151:28
    at runOnEndCallbacks (D:\workspace\zy_admin\zy_admin_ui\node_modules\esbuild\lib\main.js:941:63)
    at buildResponseToResult (D:\workspace\zy_admin\zy_admin_ui\node_modules\esbuild\lib\main.js:1149:7)
    at D:\workspace\zy_admin\zy_admin_ui\node_modules\esbuild\lib\main.js:1258:14
    at D:\workspace\zy_admin\zy_admin_ui\node_modules\esbuild\lib\main.js:629:9
    at handleIncomingPacket (D:\workspace\zy_admin\zy_admin_ui\node_modules\esbuild\lib\main.js:726:9)
    at Socket.readFromStdout (D:\workspace\zy_admin\zy_admin_ui\node_modules\esbuild\lib\main.js:596:7)
    at Socket.emit (events.js:375:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)

_Originally posted by @namewhat in https://github.com/antvis/G6/issues/3240#issuecomment-939223056_](https://github.com/antvis/G6/issues/3240#issuecomment-939223056)

**Comment by huangyiman** [comment]
徒手把@antv下用的util等包的代码扒了下来，解决了问题

**Comment by namewhat** [comment]
改哪里呢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月14日(周四) 上午8:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [antvis/G6] vite 引入g6 v3.5.2, 运行报错 (Issue #3789)




 
***@***.***下用的util等包的代码扒了下来，解决了问题

**Comment by raotaohub** [comment]
同问下，如何解决的

**Comment by raotaohub** [comment]
> 徒手把@AntV下用的util等包的代码扒了下来，解决了问题

可以请教下具体是如何解决的

**Comment by nickyzhang-fe** [comment]
> 徒手把@AntV下用的util等包的代码扒了下来，解决了问题

import G6 from '@antv/g6/dist/g6.min' 改成这样就可以了
