### ISSUE TITLE
节点的双击事件触发之前会先触发graph上的点击事件，然后触发节点单击事件

### ISSUE THREAD

**Issue by KylenXu** [antvis/g6#379]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by KylenXu** [comment]
graph的点击事件和节点单击事件会触发两次，最后才触发双击事件

**Comment by TomHuangCN** [comment]
这个没问题，原生 dom 事件也是这么做的
