### ISSUE TITLE
当我使用changeData时，出现了问题

### ISSUE THREAD

**Issue by DomineCore** [antvis/G6#3795]
### Describe the bug

Uncaught TypeError: Cannot read properties of null (reading 'source'）
![image](https://user-images.githubusercontent.com/50765823/179196231-2da2e321-35eb-4a1e-ad69-a127d2c25070.png)

### Your Example Website or App

no

### Steps to Reproduce the Bug or Issue

changeData

### Expected behavior

changeData

### Platform

- OS: macos
- Browser: chrome
- Version: 91.1

**Comment by Yanyan-Wang** [comment]
首先检查数据中是否有重复的/数字型 id，G6 要求所有节点/combo 的 id 是唯一的 string。然后检查 edges 里面是否有 source 和 target 不存在于 nodes。都没有问题的话，请提供在线复现 demo

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
