### ISSUE TITLE
smoothArrow连接固定不变

### ISSUE THREAD

**Issue by itsmyturn** [antvis/g6#38]
![image](https://user-images.githubusercontent.com/11573322/28743228-497ede2a-7477-11e7-8635-82a751408db1.png)
针对自定义的图形，是不是在使用smoothArrow连接两个图形的锚点时，图形的位置发生改变，但是线的连接点连接的还是当初的锚点，不会跟着一起改变

**Comment by TomHuangCN** [comment]
连到确定的锚点上就会一直固定该锚点不变。反之，不会固定

**Comment by itsmyturn** [comment]
好的，谢谢
