### ISSUE TITLE
`drag-combo` does not add combo update to the stack

### ISSUE THREAD

**Issue by mpodgorny** [antvis/G6#3801]
### Describe the bug

Hello,

I'm using `drag-combo` behaviour with option `onlyChangeComboSize: true`. I'd still expect combo drag end to push `update` action to the stack, if stack on that graph is enabled, but the stack is empty. 

I can see that `onDragEnd` implementation from `drag-combo` file doesn't have code meant to push drag end to the stack, but the `drag-node` have it. Would implementing it similar way as it is in the `drag-node` solve this issue? 

Thanks for all the help! 

### Your Example Website or App

https://codesandbox.io/s/stack-drag-combo-issue-6vypcr

### Steps to Reproduce the Bug or Issue

1. Have graph with stack enabled, `drag-combo` behaviour with `onlyChangeComboSize: true` property and a Combo on the canvas.
2. Drag the combo around.
3.  Check that the undo stack is empty.

### Expected behavior

As a user, I'd expect to drag combo action be undoable. 

### Platform

Chrome  103.0.5
MacOS

**Comment by cliffordfajardo** [comment]
Adding this image of the codesandbox for more context ^
![CleanShot 2022-07-21 at 01 07 45@2x](https://user-images.githubusercontent.com/6743796/180163345-86df54c1-4cd4-4285-917e-cdfb7c523a10.png)

https://user-images.githubusercontent.com/6743796/180163613-ba178db7-904e-41ca-9381-e1c107b430d6.mp4

**Comment by Yanyan-Wang** [comment]
Thanks, we will improve it ASAP
