### ISSUE TITLE
changeSize uncaught TypeError: plugin.get is not a function

### ISSUE THREAD

**Issue by Jesseszhang** [antvis/G6#3802]
### Describe the bug

window  resize  graph.changeSize uncaught TypeError: plugin.get is not a function   version4.6.15

### Your Example Website or App

changeSize uncaught TypeError: plugin.get is not a function

### Steps to Reproduce the Bug or Issue

changeSize uncaught TypeError: plugin.get is not a function

### Expected behavior

changeSize uncaught TypeError: plugin.get is not a function

### Screenshots or Videos

changeSize uncaught TypeError: plugin.get is not a function

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
-chorme

### Additional context

changeSize uncaught TypeError: plugin.get is not a function   view.js plugin.get('gridContainer') error

**Comment by cliffordfajardo** [comment]
@Jesseszhang - would you be able to create a minimal code reproduction via a codesandbox to showcase the bug?
This would help the G6 team see and assess the buggy behavior more quickly?
This is a codesandbox template you can "fork" and edit 😄 
- https://codesandbox.io/s/g607fp

**Comment by Yanyan-Wang** [comment]
Hi, dear user. Since there was no response for a long time, we cannot figure out the answer of the problem you described. If there is new progress, feel free to open a new issue.
