### ISSUE TITLE
请教下svg怎么转自定义path函数呀

### ISSUE THREAD

**Issue by wzc570738205** [antvis/G6#3807]
### 问题描述

官网有类似的symbol path函数
```
const expandIcon = (x, y, r) => {
  return [
    ['M', x - r, y],
    ['a', r, r, 0, 1, 0, r * 2, 0],
    ['a', r, r, 0, 1, 0, -r * 2, 0],
    ['M', x - r + 4, y],
    ['L', x - r + 2 * r - 4, y],
    ['M', x - r + r, y - r + 4],
    ['L', x, y + r - 4],
  ];
};

```
想请教下如何把svg转换为上述的函数呢？

### 重现链接

无

### 重现步骤

无

### 预期行为

提供svg转换path function方法

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
SVG path 的路径定义应该是和这个格式差不多的一个字符串，但是里面是具体的数字，我理解只是需要根据你自己需要，把里面的数字参数化就好了

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
