### ISSUE TITLE
react 组件方式自定义节点如何设置连线的anchorPoints？

### ISSUE THREAD

**Issue by asevenm** [antvis/G6#3809]
### 问题描述

如题描述，文档中没找到相关的说明。另：重现链接中的例子是官方的demo，但是有报错

### 重现链接

https://codesandbox.io/s/gallant-moser-xudzst?file=/ReactNode/demo.tsx

### 重现步骤

请查看demo

### 预期行为

有方式可以配置节点的anchorPoints

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: 4+

**Comment by asevenm** [comment]
https://codesandbox.io/s/gallant-moser-xudzst?file=/App.jsx
<img width="582" alt="image" src="https://user-images.githubusercontent.com/22423693/180638135-66768879-f642-44d2-a2ac-8443623cf900.png">
目前发现这样处理可以满足需求，但是anchorPoints的属性应该是传给了最后一个元素（如截图中的Rect)，这样的话自定义节点的时候都需要在最后加上一个“虚拟元素”来让连线显示正常

**Comment by Yanyan-Wang** [comment]
好的谢谢，我排查一下

**Comment by asevenm** [comment]
> 好的谢谢，我排查一下

大佬，这个错误有安排处理吗，我们业务中更新节点属性的时候

**Comment by asevenm** [comment]
> 好的谢谢，我排查一下

您好，这个有安排处理了吗？我们业务中需要使用react自定义节点，但是这个报错，还用不起来
![image](https://user-images.githubusercontent.com/22423693/188053288-b024161a-809c-4021-b45e-edafa096b4fc.png)
