### ISSUE TITLE
drag-combo设置enableDelegate: true时，拖动位置较大时，combo实际落点位置和虚线预设的落点位置相差较大

### ISSUE THREAD

**Issue by hualinzhang** [antvis/G6#3810]
### 问题描述

drag-combo设置enableDelegate: true时，拖动位置较大时，combo实际落点位置和虚线预设的落点位置相差较大

### 重现链接

https://g6.antv.vision/zh/examples/net/dagreFlow#dagreCombo

### 重现步骤

1. 进入示例：https://g6.antv.vision/zh/examples/net/dagreFlow#dagreCombo
2. 将 modes 中的 "drag-combo" 改为 {type: "drag-combo",enableDelegate: true,}

### 预期行为

我期望，combo拖动结束后的实际位置 和 拖动过程中临时生成的图形位置重合，
但我看到了：位置相差较大

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

https://user-images.githubusercontent.com/38073079/180740740-1722820b-f46a-4d8c-adc0-1ab7e4e1e183.mp4

**Comment by Yanyan-Wang** [comment]
收到，我们会尽快修复
