### ISSUE TITLE
【求助】Dagre布局下，如何合并线

### ISSUE THREAD

**Issue by mark3h** [antvis/G6#3811]
### 问题描述

![image](https://user-images.githubusercontent.com/16110230/180755358-4bd96c68-b557-4fe5-a6f5-0a3d3f0530fd.png)

如何将2和3的线合并，然后各自指向4和5？

实现类似效果：
![image](https://user-images.githubusercontent.com/16110230/180755802-9ad59bbf-5c57-437a-8a5f-dd8ed2cf281d.png)

### 重现链接

https://codesandbox.io/s/optimistic-keldysh-giiym9?file=/index.js

### 重现步骤

问题在于，我想要获取到4和5的中间值坐标，然后根据registerEdge画出path。

但是在4的draw回调中，无法获取到5的位置，求解。

### 预期行为

将2和3的线合并

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
为什么在节点的 draw 方法中去考虑这件事呢？不应该在自定义边的时候考虑么？registerEdge draw 的参数 cfg 里面可以拿到 startPoint endPoint

**Comment by mark3h** [comment]
> 为什么在节点的 draw 方法中去考虑这件事呢？不应该在自定义边的时候考虑么？registerEdge draw 的参数 cfg 里面可以拿到 startPoint endPoint

2在连接4和5的时候，是要中间重合，然后连向4和5。

2在连接4的时候，startPoint endPoint对应的是4的startPoint endPoint，并不知道5的startPoint endPoint，但是因为要重合，所以在连接4的时候，要知道5的位置，才可以计算出中间位置的值

**Comment by mark3h** [comment]
> 为什么在节点的 draw 方法中去考虑这件事呢？不应该在自定义边的时候考虑么？registerEdge draw 的参数 cfg 里面可以拿到 startPoint endPoint

<img width="419" alt="image" src="https://user-images.githubusercontent.com/16110230/182061787-f753b025-4f71-4160-bb64-024e040e9a52.png">

**Comment by Yanyan-Wang** [comment]
也许比较适合在布局、绘制完成之后做一个后处理，在外部为每条边计算出 controlPoints，比如在 graph.on('afterlayout', e => {}) 里面，这样可以拿到全部的节点位置。然后通过 graph.updateItem(edge, { controlPoints }) 的方式更新到边上，更新后，边就会使用新的 controlPoints 去绘制路径。

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
