### ISSUE TITLE
需要一份离线文档

### ISSUE THREAD

**Issue by name-trouble** [antvis/G6#3812]
### 问题描述

G6的4.6.15版本缺少对应的离线文档，希望官方能够发布一份文档代码用于离线查阅文档。目前的https://github.com/antvis/g6-3.2.x-site已经落后了

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]
无

**Comment by Yanyan-Wang** [comment]
这里的文档就是最新的 https://github.com/antvis/G6/tree/master/packages/site
