### ISSUE TITLE
Combo.prototype.addChild报异常

### ISSUE THREAD

**Issue by yanhan569046480** [antvis/G6#3815]
### Describe the bug

![image](https://user-images.githubusercontent.com/1505382/181204941-6f41c50e-b6c3-408d-b863-184e8193710f.png)
![image](https://user-images.githubusercontent.com/1505382/181205041-19605659-8b24-4a05-b1ea-e1e4922b162a.png)
响应表单的操作给graphin传数据，常常出现上图的异常，数据看起来是符合规范的，也加了防抖处理

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

无

### Expected behavior

不报错

### Platform

- OS: Windows
- Browser: Chrome, 
- Version: 105.0.5148.2（正式版本） （64 位）

**Comment by Yanyan-Wang** [comment]
节点 id 需要是唯一的 string

**Comment by yanhan569046480** [comment]
> 

好的，已解决，谢谢
