### ISSUE TITLE
脑图树 生成3000个节点 浏览器很卡顿

### ISSUE THREAD

**Issue by Mrqi215** [antvis/G6#3816]
### Describe the bug

脑图树 生成3000节点 chrome 会卡顿  是否有解决方案

### Your Example Website or App

https://codesandbox.io/s/small-sea-902h1c?file=/src/components/HelloWorld.vue

### Steps to Reproduce the Bug or Issue

无法滚动 配合minMap 会非常卡

### Expected behavior

解决方案

### Screenshots or Videos

![Uploading image.png…]()

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
在我的电脑上还挺流畅的。不过有一些优化方法：
1. 若拖拽画布/缩放画布卡顿，可以开启 enableOptimize: true，例如，behavior 中的 "drag-canvas" 更换为 { type: "drag-canvas", enableOptimize: true }。'zoom-canvas' 同理
2. 若初始化/展开/收起时动画卡顿，可以在必要的时候关闭动画，在图实例上配置 ainmate: false 或在其它地方 graph.set('animate', false)
3. minimap 默认情况下会复制画布上所有的内容，相当于所有的渲染和更新都有两倍的开销，建议在比较大的图上，配置 minimap 的 type 为 keyShape 或者 delegate，这样能够减少 minimap 的渲染性能开销

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。

**Comment by LLLuojp** [comment]
> 在我的电脑上还挺流畅的。不过有一些优化方法：
> 
> 1. 若拖拽画布/缩放画布卡顿，可以开启 enableOptimize: true，例如，behavior 中的 "drag-canvas" 更换为 { type: "drag-canvas", enableOptimize: true }。'zoom-canvas' 同理
> 2. 若初始化/展开/收起时动画卡顿，可以在必要的时候关闭动画，在图实例上配置 ainmate: false 或在其它地方 graph.set('animate', false)
> 3. minimap 默认情况下会复制画布上所有的内容，相当于所有的渲染和更新都有两倍的开销，建议在比较大的图上，配置 minimap 的 type 为 keyShape 或者 delegate，这样能够减少 minimap 的渲染性能开销

你好，这些优化方法都用了，但是当节点数量更多的时候还是会很卡顿，这是正常现象吗？在数据量过多时就会有卡顿。
