### ISSUE TITLE
缩放时固定节点大小不变

### ISSUE THREAD

**Issue by dingyang9642** [antvis/G6#3817]
### 问题描述

在画布缩放过程中，如何做到节点可视化大小效果不变（即节点大小不随着缩放变化）？

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
fixSelectedItems

https://g6.antv.vision/zh/docs/manual/middle/states/defaultBehavior#zoom-canvas

**Comment by dingyang9642** [comment]
> fixSelectedItems
> 
> https://g6.antv.vision/zh/docs/manual/middle/states/defaultBehavior#zoom-canvas

fixSelectedItems 这个参数只是针对缩小的时候固定不变，放大的时候怎么控制呢？

**Comment by Yanyan-Wang** [comment]
duplicated to #3831
