### ISSUE TITLE
Graphin自定义combo添加text拓扑图卡死

### ISSUE THREAD

**Issue by yanhan569046480** [antvis/G6#3818]
### 问题描述

在自定义combo中试图像node那样加个二级文本，结果加是加上了，图表卡死，难道自定义combo不支持加文本？

### 重现链接

无

### 重现步骤

![image](https://user-images.githubusercontent.com/1505382/181707618-57cfae34-c8e9-4b51-b9bb-c3f9dc92d9e5.png)
![image](https://user-images.githubusercontent.com/1505382/181707683-cb6a0eda-b008-4adb-9216-0de90138c8b5.png)

### 预期行为

无

### 平台

- 操作系统: Windows
- 网页浏览器: Google Chrome
- G6 版本: 105.0.5148.2

**Comment by Yanyan-Wang** [comment]
请提供 G6 的在线复现 demo

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
