### ISSUE TITLE
力导向布局怎么避免边重合

### ISSUE THREAD

**Issue by dearbady** [antvis/G6#3823]
### 问题描述

设置了点不重合，但是数据量大时，有的边会重合在一条直线上

### 重现链接

https://g6.antv.vision/zh/examples/net/forceDirected#basicForceDirected

### 重现步骤

![image](https://user-images.githubusercontent.com/23444708/182064002-77744bf1-0778-4e8a-b213-f4ffec58a84f.png)

### 预期行为

希望点和边都不重合

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.6.4]

**Comment by Yanyan-Wang** [comment]
duplicate to #3871
