### ISSUE TITLE
在 dragend 事件中执行 removeItem 报错

### ISSUE THREAD

**Issue by Alessandro-Pang** [antvis/G6#3824]
### 问题描述

在 node:dragend 事件中执行 removeItem 报错。

``` Uncaught TypeError: Cannot read properties of null (reading 'model') ```

元素删除后，再次点击屏幕会报以上问题

### 重现链接

https://codesandbox.io/s/g6-tuo-zhuai-shan-chu-r9kl7t

### 重现步骤

1.进入页面
2.拖拽其中一个节点到屏幕最下方 “灰色区域”，此时会执行删除
3.此时控制台会报错，如果没有报错，拖拽另一个节点就会报错，同时页面事件会失效

### 预期行为

正常删除节点，不会影响其他功能执行

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/42641570/182084402-aa2606b7-454c-49a7-b8ad-9cf2979c3afd.png)

### 补充说明（可选）

我在执行 removeItem 时加了一个定时器，可以临时处理此问题，但我觉得这种方法似乎有问题

```js
const timer = setTimeout(() => {
  graph.removeItem(node)
  clearTimeout(timer)
}, 100)
```

**Comment by Yanyan-Wang** [comment]
改成监听 node:dragend

因为 drag-node behavior 里面在 node:dragend 后还要对被拖拽节点有操作。如果你监听的是 dragend，可能会在 drag-node 的 node:dragend 之前执行，导致里面使用到被拖拽节点的时候访问到被销毁的元素。

**Comment by Yanyan-Wang** [comment]
另外，节点要有唯一的 string id

**Comment by Alessandro-Pang** [comment]
> 改成监听节点：dragend
> 
> 因为拖拽节点的行为在节点里面：拖拽节点之后对被拖节点有操作。如果你监听到拖拽节点的节点：拖拽节点的执行，导致里面使用到被拖节点的之前什么时候访问到被那个元素。

非常感谢您的回答
