### ISSUE TITLE
是否可以自定义vue节点

### ISSUE THREAD

**Issue by Mrqi215** [antvis/G6#3826]
### 问题描述

自定义vue节点

### 重现链接

null

### 重现步骤

自定义vue节点

### 预期行为

自定义vue节点

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Alessandro-Pang** [comment]
理论上是可行的，你可以试试，他是支持自定义 DOM 节点的

https://antv-g6.gitee.io/zh/docs/manual/middle/elements/nodes/custom-node/#5-%E4%BD%BF%E7%94%A8-dom-%E8%87%AA%E5%AE%9A%E4%B9%89%E8%8A%82%E7%82%B9

**Comment by Mrqi215** [comment]
我想用vue components 去换替换实现节点自定义 是否可行 我看x6的功能里是有的

**Comment by Yanyan-Wang** [comment]
没有官方支持，社区有小伙伴如果实现了，可以分享一下 demo～

**Comment by zhang-maxwell** [comment]
@Yanyan-Wang 现在G6支持Vue自定义节点了嘛？😂现在官方http://g6.antv.antgroup.com/manual/middle/elements/nodes/custom-node上还是只看到JSX、React形式来自定义节点。只不过，现在很多项目是Vue项目，更.vue组件实现自定义节点更顺手一些。

**Comment by hsbtr** [comment]
各位有实现这个功能吗
