### ISSUE TITLE
边怎么在两nodes中间连接

### ISSUE THREAD

**Issue by sun1719244578** [antvis/G6#3827]
### 问题描述

设置了 layout: {
          type: "dendrogram",
          direction: "TB"}

我想要边位于两个node的中间

### 重现链接

1111

### 重现步骤

设置了 layout: {
          type: "dendrogram",
          direction: "TB"}

我想要边位于两个node的中间

### 预期行为

希望给个提示

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![011e6dd033ae46073b51ee03722627b](https://user-images.githubusercontent.com/33944541/182140203-8816f9cc-4252-4736-bffb-30219a3df638.png)

**Comment by Yanyan-Wang** [comment]
你看下是不是哪里设置了 anchorPoints，删掉。

**Comment by Alessandro-Pang** [comment]
> 你看下是不是哪里设置了 anchorPoints，删掉。

您好，我也有类似的问题，我也确实设置了 anchorPoints，但是我不能删掉他，因为我需要手动连线，这种问题可以处理吗

**Comment by sun1719244578** [comment]
谢谢&nbsp;大佬&nbsp; 才接手这个项目&nbsp; 好多属性&nbsp; 感觉都不是很好理解呢&nbsp;&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月2日(星期二) 中午11:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [antvis/G6] 边怎么在两nodes中间连接 (Issue #3827)





  
你看下是不是哪里设置了 anchorPoints，删掉。
  
您好，我也有类似的问题，我也确实设置了 anchorPoints，但是我不能删掉他，因为我需要手动连线，这种问题可以处理吗

**Comment by Yanyan-Wang** [comment]
> 谢谢&nbsp;大佬&nbsp; 才接手这个项目&nbsp; 好多属性&nbsp; 感觉都不是很好理解呢&nbsp;&nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年8月2日(星期二) 中午11:00 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [antvis/G6] 边怎么在两nodes中间连接 (Issue #3827) 你看下是不是哪里设置了 anchorPoints，删掉。 您好，我也有类似的问题，我也确实设置了 anchorPoints，但是我不能删掉他，因为我需要手动连线，这种问题可以处理吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

多看文档

**Comment by Yanyan-Wang** [comment]
> > 你看下是不是哪里设置了 anchorPoints，删掉。
> 
> 您好，我也有类似的问题，我也确实设置了 anchorPoints，但是我不能删掉他，因为我需要手动连线，这种问题可以处理吗

手动连线的时候要连到 anchorPoints，其它情况为什么不想连到 anchorPoints？

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
