### ISSUE TITLE
自定义布局之后，如何主动触发一次自定义behavior的执行

### ISSUE THREAD

**Issue by dingyang9642** [antvis/G6#3828]
### 问题描述

业务场景：单击某个节点会重新执行一次布局计算，然后布局
期望效果：自动布局后，主动触发一次自定义的behavior，因为布局后希望触发一次mouse-move执行，对应的节点/边展示其高亮样式
现状：并不会触发期望效果，单击节点布局后还是展示上一次的item的state状态

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
那直接调用 setItemState 就好了？在 afterlayout 监听里面

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
