### ISSUE TITLE
缩放固定节点大小

### ISSUE THREAD

**Issue by dingyang9642** [antvis/G6#3831]
### 问题描述

在画布缩放过程中，如何做到节点可视化大小效果不变（即节点大小不随着缩放变化）？

问题：fixSelectedItems只能控制缩小时固定节点大小，并不能放大时也进行固定

该如何保证放大缩小时都固定节点大小呢？

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
不支持，可模拟内置 zoom-canvas 自定义交互

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
