### ISSUE TITLE
要求按数据展示节点的层次关系，使用了层次布局，设置layer方式实现时出现一些问题

### ISSUE THREAD

**Issue by FengQian007** [antvis/G6#3832]
### 问题描述

需求：展示数据的层级关系
   * 问题1：最低层级（如最低是0）有多个时，它的第一个节点的位置出现在0-1之间，期望能保持一致
   * 问题2：只有节点的时候，它的layer最多是0和1，如果按顺序出现了大于1的，布局就会崩掉，什么都不展示
   * 问题3：举例：边最大指向的层级是1，这时候如果有层级3出现，页面也会坏掉

### 重现链接

https://codesandbox.io/s/kind-visvesvaraya-rfrjsq?file=/src/App.js

### 重现步骤

1.直接进入链接，数据展示的是问题1
2.把data文件的edges设为[]，复现问题2
3. 把data文件的nodes最后一条数据放出来，复现问题3

### 预期行为

期望节点层级正常展示

### 平台

- 操作系统: [macOS, Windows]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.6.15]

**Comment by Yanyan-Wang** [comment]
暂时通过把所有节点的 layer /= 2 可以解决上述三个问题。具体原因我这边找时间看下

**Comment by Yanyan-Wang** [comment]
已修复
