### ISSUE TITLE
使用addItem添加节点的时候，添加的节点位置错乱

### ISSUE THREAD

**Issue by daisy0123** [antvis/G6#3834]
### Describe the bug

当前使用的布局是
` 
type: "dagre",
rankdir: "LR",
align: "UL",
controlPoints: true,
 nodesep: 10,
ranksep: 50,
`
当使用addItem 添加节点后，节点不是根据新增节点的source起点绘制，而是在容器的开头绘制了。
![image](https://user-images.githubusercontent.com/11910330/182614646-bb377402-c69b-45d0-bdbe-29206b439579.png)

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

如上

### Expected behavior

希望不要错乱，希望是如图下：
![image](https://user-images.githubusercontent.com/11910330/182615128-b8a52f32-de7c-46c9-a97c-7bdcea813f38.png)

### Platform

- OS: [macOS
- Browser: Chrome
- Version: 103.0.5060.134

**Comment by Yanyan-Wang** [comment]
请提供在线复现 demo

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。

**Comment by daisy0123** [comment]
> 尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。

https://codesandbox.io/s/keen-wilbur-h96u4n?file=/index.js  你好麻烦帮忙看看，这个之前有g6的同事帮忙解决了，目前4.6.18版本是没有问题的，但是新版本有问题，应该是4.6.18版本的代码没有更新到最新版本
