### ISSUE TITLE
comboCombined如果combo没有连接节点，在逐级展开的时候和combo内部的node连接的edge会消失

### ISSUE THREAD

**Issue by soapyu** [antvis/G6#3839]
### Describe the bug

comboCombined的layout，三层嵌套，combo a->combo b -> node ，combo与其他节点无连接，内层的node和其他节点有连接，默认所有combo都关闭的情况下，逐级展开的时候，再展开combo a之后，连接线消失。默认combo都开启的情况下，全部关闭后再逐级展开，也会复现。

另外，edge上的label,需要内部节点显示才会展现，这个是否有配置可控制？

### Your Example Website or App

https://7qfmqo.csb.app/

### Steps to Reproduce the Bug or Issue

1、收起combo b
2、收起combo a
3、展开combo a

comob内部的节点和其他node的edge会消失

### Expected behavior

无论如何展开收起，连接线不消失

### Platform

- OS: [macOS 10.15.7]
- Browser: [Chrome 103.0.5060.134]
- Version: [latest]

**Comment by cliffordfajardo** [comment]
Hi @soapyu,
I tried to view your combo layout inside your codesandbox, but I am not seeing anything rendering
Is this happening for you too?

![CleanShot 2022-08-06 at 05 49 02@2x](https://user-images.githubusercontent.com/6743796/183249566-beda91fe-b235-4e65-9d65-9939c85c21e2.png)

**Comment by soapyu** [comment]
> Hi @soapyu, I tried to view your combo layout inside your codesandbox, but I am not seeing anything rendering Is this happening for you too?
> 
> ![CleanShot 2022-08-06 at 05 49 02@2x](https://user-images.githubusercontent.com/6743796/183249566-beda91fe-b235-4e65-9d65-9939c85c21e2.png)

sorry, has updated the example url

**Comment by Yanyan-Wang** [comment]
感谢报告，我们会尽快修复
