### ISSUE TITLE
3.X版本的registerNode在ie浏览器中报错

### ISSUE THREAD

**Issue by liuqing519** [antvis/G6#3844]
### 问题描述

3.X版本的registerNode在ie浏览器中报错，有没有哪位大佬遇到过，怎么解决的

### 重现链接

。。。

### 重现步骤

。。。

### 预期行为

....

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [IE]
- G6 版本: [3.X ... ]

**Comment by Yanyan-Wang** [comment]
IE 浏览器下线了，不兼容
