### ISSUE TITLE
动态新增子combo到父combo中，使用graph.addItem(),会强制relayout

### ISSUE THREAD

**Issue by angelrong520** [antvis/G6#3846]
### 问题描述

动态新增子combo到父combo中，使用graph.addItem(),会强制relayout。

### 重现链接

。

### 重现步骤

    graph.addItem('combo', {
      id: new Date().getTime().toString(),
      label: new Date().getTime().toString(),
      itemType: 'combo',
      parentId: combo.id,
    });

### 预期行为

不要强行relayout。保持我现在的布局位置。仅被操作combo内部刷新即可

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by fanggz2017** [comment]
const matrix = graph.getGroup().getMatrix();
graph.addItem('combo', {
  id: new Date().getTime().toString(),
  label: new Date().getTime().toString(),
  itemType: 'combo',
  parentId: combo.id,
});
graph.getGroup().setMatrix(matrix);
这样对你有效果吗

**Comment by angelrong520** [comment]
> 

还是relayout了……

**Comment by angelrong520** [comment]
> getGroup

graph.getGroup(), graph.getGroup().getMatrix() 这俩值 都是null
我尝试过 addItem changeData 但是 全部relayout了 源码emit了relayout 会强行做这件事

**Comment by angelrong520** [comment]
![image](https://user-images.githubusercontent.com/1809360/183417340-45f55474-1abd-4750-858e-6d9a03f33cb4.png)
想问为什么源码里面所有创建类的方法，都会假设节点是已经存在的？

**Comment by angelrong520** [comment]
![image](https://user-images.githubusercontent.com/1809360/183420978-e01e44b7-9c38-48b8-b7da-60922080a2e7.png)
所以这个代码是写了一个寂寞？？？

**Comment by Yanyan-Wang** [comment]
> ![image](https://user-images.githubusercontent.com/1809360/183420978-e01e44b7-9c38-48b8-b7da-60922080a2e7.png) 所以这个代码是写了一个寂寞？？？

combo 继承 node，该方法需要复写掉 node 的逻辑

**Comment by Yanyan-Wang** [comment]
不重新布局，怎么腾出位置给新的元素呢？

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
