### ISSUE TITLE
更新 ModelRect 节点类型 的 linkPoints 的 cursor 属性无效

### ISSUE THREAD

**Issue by Mr-giraff** [antvis/G6#3847]
### 问题描述

更新 ModelRect 节点类型 的 linkPoints 的 cursor 属性无效

### 重现链接

https://g6.antv.vision/zh/examples/item/defaultNodes#modelRect

### 重现步骤

替换最后一段代码

``` js
graph.on('node:mouseenter', (evt) => {
  const { item } = evt;
  graph.setItemState(item, 'hover', true);
  item.update({
    linkPoints: {
        top: true,
        cursor: 'pointer',
    },
  })
});

graph.on('node:mouseleave', (evt) => {
  const { item } = evt;
  graph.setItemState(item, 'hover', false);
    item.update({
    linkPoints: {
        top: false,
    },
  })
});
```

### 预期行为

我期望看到鼠标 hover 到节点时，出现连接点时，并且连接点 hover 时显示为手型，但我看到了连接点，但 hover 时 cursor 不生效

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.6.18]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/18570167/183405792-3ce377d1-4105-47df-b466-310465bc921d.png)

**Comment by Yanyan-Wang** [comment]
在图示例的 defaultNode.linkPoints 里面配置 cursor: 'pointer' 就好

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
