### ISSUE TITLE
项目中同时使用1.x跟4.x，无法兼容么？

### ISSUE THREAD

**Issue by aiyun1010** [antvis/G6#3856]
### 问题描述

想从1.x升级至4.x，但是项目中很多地方使用了1.x，暂时不方便一起升级，新功能想使用最新版，所以就安装了两个不同版本的依赖，但是安装后项目无法启动

安装两个版本的g6：
![image](https://user-images.githubusercontent.com/20297519/183884437-8f0ae1ee-effb-4580-be12-3de3e893f6a6.png)

启动报错：
![image](https://user-images.githubusercontent.com/20297519/183885141-8e607a45-8fdc-4044-8331-4526ad55b5ce.png)

index.d.ts中也声明了：
![image](https://user-images.githubusercontent.com/20297519/183885245-7bcbf09f-1704-4cad-ba13-3b162c0715b9.png)

### 重现链接

无

### 重现步骤

无

### 预期行为

1.x跟4.x在同一项目中兼容

### 平台

windows

**Comment by Yanyan-Wang** [comment]
这个地方报错应该是因为你项目配置的 ts 版本太低，不认识这种写法

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
