### ISSUE TITLE
节点和边的 tooltip 离节点远

### ISSUE THREAD

**Issue by xuoutput** [antvis/G6#3859]
### Describe the bug

<img width="656" alt="image" src="https://user-images.githubusercontent.com/16385443/184086614-bfd50c6f-f810-4fb6-aada-05ed6cd4c9ed.png">

![edge](https://gw.alipayobjects.com/mdn/rms_f8c6a0/afts/img/A*Uk10SYFNNi8AAAAAAAAAAABkARQnAQ)

### Your Example Website or App

https://codepen.io/Yanyan-Wang/pen/mdbYZvZ

### Steps to Reproduce the Bug or Issue

用的 demo 是 https://codepen.io/Yanyan-Wang/pen/mdbYZvZ 但效果不一样

### Expected behavior

和 demo 保持一致

### Platform

- OS: [macOS 12.2.1]
- Browser: [Version 103.0.5060.53 (Official Build) (arm64)]
"@antv/g6": "^4.6.18",

**Comment by Yanyan-Wang** [comment]
demo 中正常，请提供在线复现 demo

**Comment by xuoutput** [comment]
我在样式中增加了错误的相对定位导致的
