### ISSUE TITLE
使用类 JSX 语法定义 G6 节点 ${FULL} 未定义

### ISSUE THREAD

**Issue by xuoutput** [antvis/G6#3862]
### Describe the bug

FULL 变量没用到, 应该是一个字符串 https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/jsx-node

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/16385443/184303681-dccc9cc6-8d48-4f1f-b9d4-2053b8139118.png">
<img width="618" alt="image" src="https://user-images.githubusercontent.com/16385443/184303799-08fc3b8a-8383-45a8-979a-a092ab675430.png">

### Your Example Website or App

1

### Steps to Reproduce the Bug or Issue

1

### Expected behavior

文档更新

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
FULL 应该是这个例子中外部的常量，代码块中没申明。文档会尽快修正，谢谢报告

**Comment by Yanyan-Wang** [comment]
文档已更正
