### ISSUE TITLE
用canvas绘制的自定义节点高亮效果无效

### ISSUE THREAD

**Issue by harekuer** [antvis/G6#3864]
### 问题描述

自定义节点的demo：https://antv-g6.gitee.io/zh/examples/item/customNode#card
与高亮效果demo结合：https://antv-g6.gitee.io/zh/examples/interaction/highlight#highlightDark
发现edge高亮正常，而node高亮效果无效

### 重现链接

无

### 重现步骤

1、给定自定节点添加高亮效果
2、edge高亮正常，而node高亮效果无效

### 预期行为

高亮效果正常显示

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
1. demo 中的自定义节点复写了 setState，意味着所有的状态样式由自定义节点的 setState 函数处理，G6 内置的默认逻辑将不再生效

2. 注释掉 demo 中 registerNode 的 setState，状态样式看起来还没有生效。这是因为，状态样式默认情况下反映在节点的 keyShape 上，也就是 registerNode draw 方法 return 的那个图形。这个 demo 中 return 的 container 可能被其他图形遮挡

3. P.S. type: demo 中 line65 heigh -> height，我们会尽快修正
