### ISSUE TITLE
g6 最新版本包里面居然有开发留下 console.log 没有移除

### ISSUE THREAD

**Issue by csspmini-web** [antvis/G6#3865]
### 问题描述

g6 最新版本包里面居然有开发留下 console.log 没有移除

问题文件： packages/pc/src/behavior/drag-combo.ts

```js
/**
   *
   * @param item 当前正在拖动的元素
   * @param evt
   */
  updateSingleItem(item: INode | ICombo, evt: IG6GraphEvent, restore: boolean) {
    const { origin } = this;
    const graph: IGraph = this.graph;
    const model = item.getModel() as ComboConfig;
    const itemId = item.get('id');

    if (!this.point[itemId]) {
      this.point[itemId] = {
        x: model.x,
        y: model.y,
      };
    }

    let x: number = evt.x - origin.x + this.point[itemId].x;
    let y: number = evt.y - origin.y + this.point[itemId].y;

    console.log('restore', restore);
    if (restore) {
      x += origin.x - evt.x;
      y += origin.y - evt.y;
    }

    graph.updateItem(item, { x, y }, false);
    // item.getEdges()?.forEach(edge => edge.refresh());
  },
```

### 重现链接

无

### 重现步骤

1.打开控制台
2.引入 drag-combo 内置行为
3.拖动 combo

### 预期行为

应该移除  g6 库中开发时留下的   console.log('restore', restore);

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.6.18 ... ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/70122856/184542861-558578ba-ae86-41d7-95e3-a8b822261de8.png)

**Comment by Yanyan-Wang** [comment]
v4.7.0-beta.2 已清除，正式版近期会发布
