### ISSUE TITLE
二维码都已过期

### ISSUE THREAD

**Issue by xuoutput** [antvis/G6#3866]
### Describe the bug

![Uploading image.png…]()

### Your Example Website or App

0

### Steps to Reproduce the Bug or Issue

0

### Expected behavior

进群

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
已更新
