### ISSUE TITLE
自定义节点 JSX 语法下, next: inline 是加到哪里?

### ISSUE THREAD

**Issue by xuoutput** [antvis/G6#3867]
### Describe the bug

https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/jsx-node
<img width="799" alt="image" src="https://user-images.githubusercontent.com/16385443/184584761-60d9c494-d06d-4987-bb15-0127b20c5662.png">

### Your Example Website or App

0

### Steps to Reproduce the Bug or Issue

1

### Expected behavior

文档补全用法

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
A、B 要横向排列，A 在前 B 在后的话，A 的 style 中配置 next: 'inline'

          <text style={{  next: 'inline' }}>A</text>
          <text style={{}}>B</text>

**Comment by ScalaFirst** [comment]
只支持 text 吗
