### ISSUE TITLE
gForce layout, fitView配置和afterrender事件在web worker和GPU启用的情况下不work

### ISSUE THREAD

**Issue by ouyuran** [antvis/G6#3868]
### Describe the bug

gForce layout, fitView配置和afterrender事件在web worker和GPU启用的情况下不work

当仅仅关闭web worker后，都可以work了

### Your Example Website or App

https://codesandbox.io/s/frosty-rain-8965vw?file=/index.js

### Steps to Reproduce the Bug or Issue

从上面的demo link可以看出

- fitView不工作
- afterrender不工作

workerEnabled设为false后，都可正常工作

### Expected behavior

workerEnabled设为true时，fitView和afterrender应该可以正常工作

### Platform

- OS: macOS
- Browser: Chrome Version 103.0.5060.114 (Official Build) (x86_64)
- Version: Antv G6 4.6.4

**Comment by Yanyan-Wang** [comment]
👍👍👍欢迎社区 pr

**Comment by Yanyan-Wang** [comment]
4.7.0 已发布
