### ISSUE TITLE
item.hide()性能问题

### ISSUE THREAD

**Issue by dingyang9642** [antvis/G6#3869]
### 问题描述

在自定义布局时会给每个node以及相关edge标记__show属性，再afterlayout之后需要对__show：false的node以及edge集合进行隐藏，如果存在几百个需要隐藏的要素时，遍历调用hide会造成很大的性能开销，有没有批量更新的方法呢？

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
从浏览器 performance 确定性能瓶颈是出在隐藏这一步吗？hide 应该开销不大

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
