### ISSUE TITLE
Wrong type declarations are imported when using with `dagre`

### ISSUE THREAD

**Issue by sklinov** [antvis/G6#3870]
### Describe the bug

When I have both `G6` and `dagre` in my project typescript declarations reference `dagre-compound` instead of `@types/dagre` and that causes an error:
```
Argument of type '{ width: number; height: number; }' is not assignable to parameter of type 'GraphOptions'.
```

I suspect that `G6` overrides module declaration for `dagre`.
Note, that I'm not using G6's built-in algorithms and use custom node positioning.

### Your Example Website or App

https://codesandbox.io/s/imports-conflict-g6-dagre-pxmy7s?file=/src/App.tsx

### Steps to Reproduce the Bug or Issue

Hover over `g.setGraph({ width, height });` to see type error

### Expected behavior

I expect types to be imported from `@types/dagre` and not from `dagre-compound` package.

### Platform

- OS: MacOS
- Browser: Chrome
- Version: 103

**Comment by simplejason** [comment]
`dagre-compound` does override module declaration of `dagre` to support hierarchically nested DAG layout,  I'll check it and solve this problem :)

**Comment by sklinov** [comment]
@simplejason Thank you for your assistance! Looking forward to those changes

**Comment by simplejason** [comment]
> @simplejason Thank you for your assistance! Looking forward to those changes

I will try to use types of dagre instead of declared by `dagre-compound`, the previous types definition of dagre was missing some necessary properties so I override the declaration. But now it seems to have updated `@types/dagre`, so I will try to remove the declaration in `dagre-compound` to check if it still can work :)

**Comment by sklinov** [comment]
@simplejason Awesome! Let me know if I can help with testing it

**Comment by sklinov** [comment]
Hey, @simplejason! Any updates on this issue?
Unfortunately, `dagre-compound` doesn't seem to be an open source lib, otherwise I could have provided a PR myself

**Comment by simplejason** [comment]
> Hey, @simplejason! Any updates on this issue? Unfortunately, `dagre-compound` doesn't seem to be an open source lib, otherwise I could have provided a PR myself

Sorry for this :( I plan to finish it in this week (of course I will try my best to resolve it ASAP)

**Comment by simplejason** [comment]
> Hey, @simplejason! Any updates on this issue? Unfortunately, `dagre-compound` doesn't seem to be an open source lib, otherwise I could have provided a PR myself

Hi @sklinov you can install dagre-compound@0.0.12-beta.0 to check if it can work as except, I will release v0.12.0 after all things work well :)

**Comment by simplejason** [comment]
Hi @sklinov Please check `dagre-compound` under version `0.0.12` can work well in your project(or just re-install `G6`), I will close this issue after if there are no other problems :)

**Comment by sklinov** [comment]
@simplejason Thanks a lot! I'll try to do this within a day and get back to you with my feedback

**Comment by sklinov** [comment]
@simplejason Looks good to me in the sandbox with latest versions of `G6` and `dagre-compound` 👍

**Comment by simplejason** [comment]
> @simplejason Looks good to me in the sandbox with latest versions of `G6` and `dagre-compound` 👍

Cool, so I will close this issue :)
