### ISSUE TITLE
请教个问题，力导向图怎么避免边重叠？

### ISSUE THREAD

**Issue by dearbady** [antvis/G6#3871]
### 问题描述

布局用的力导向，拓展的时候，以某个点为起始点，其他点和这个点的连线会重叠

### 重现链接

https://g6.antv.vision/zh/examples/net/forceDirected#basicForceDirected

### 重现步骤

例如：以0为主点（起始点），6、7、8和0连线时重叠了，分不清除6连接的是7还是0
![image](https://user-images.githubusercontent.com/23444708/184627396-5b519dcf-eea6-4345-8b2d-a14471241522.png)

### 预期行为

希望同一起始点，其他点和主点的连线不重叠

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
这种重叠的巧合比较大概率出现在 ‘0’ 这个点四周的空间不够，nodeSize 和 linkDistance 基本上把这个区域占满，导致了重叠可能性增加。考虑根据节点的度数调整 linkDistance，比如 ‘0’ 相关的 linkDistance 大一些
https://g6.antv.vision/zh/docs/api/graphLayout/force#layoutcfglinkdistance

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
