### ISSUE TITLE
开启gpu后丢失节点

### ISSUE THREAD

**Issue by tianxiumei** [antvis/G6#3874]
### 问题描述

fruchterman 布局设置 gpuEnabled为true 节点数量为19个第一个点会画不出来

### 重现链接

https://codesandbox.io/s/sweet-water-hp6rdd?file=/index.js

### 重现步骤

直接进去就可以看到

### 预期行为

不丢失点

### 平台

macOS m1
g6 最新版本

### 屏幕截图或视频（可选）

<img width="1232" alt="image" src="https://user-images.githubusercontent.com/38803966/185050688-5d06e485-4054-4a6c-b5b7-616295b84e2c.png">

**Comment by Yanyan-Wang** [comment]
没有丢失，为图配置 fitView: true，可以看到有些点在很远的地方。这里应该有计算问题，感谢报告我们会尽快修复。可以先使用其它布局 gForce 也可以使用 gpu
