### ISSUE TITLE
自定义带 group的节点, hover false 后会消失

### ISSUE THREAD

**Issue by xuoutput** [antvis/G6#3875]
### Describe the bug

<img width="1033" alt="image" src="https://user-images.githubusercontent.com/16385443/185062487-387bdc9e-0dde-43bd-afea-cc8027956299.png">
<img width="503" alt="image" src="https://user-images.githubusercontent.com/16385443/185062542-dcaf03cf-a719-4a0a-b363-2aa5d2420a8b.png">
如果定义节点的时候返回的是按 group 的
```
    const mainGroup = group.addGroup({
      id: 'main-group',
    });
    const keyShape = mainGroup.addShape('rect', {
      attrs: {
        x: 0,
        y: 0,
        width: 100 + 60 * cfg.values.length,
        height: 50,
        fill: '#C6E5FF',
      },
      name: 'key-rect-shape',
    });
```

那么出发下面这种 鼠标 hover, 节点就没了
```
graph.on('node:mouseenter', (e) => {
  const nodeItem = e.item; // 获取鼠标进入的节点元素对象
  graph.setItemState(nodeItem, 'hover', true); // 设置当前节点的 hover 状态为 true
});
/** 鼠标离开节点 */
graph.on('node:mouseleave', (e) => {
  const nodeItem = e.item; // 获取鼠标离开的节点元素对象
  graph.setItemState(nodeItem, 'hover', false); // 设置当前节点的 hover 状态为 false
});
```

### Your Example Website or App

 1

### Steps to Reproduce the Bug or Issue

1

### Expected behavior

是 bug 还是使用方式不对?

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
请给出在线复现 demo

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
