### ISSUE TITLE
图例插件，节点形状不支持五角星等

### ISSUE THREAD

**Issue by gouzixing** [antvis/G6#3876]
### Describe the bug

节点的样式为diamond、ellipse、triangle、star等不支持且白屏

### Your Example Website or App

https://codesandbox.io/s/dank-water-5vy6yu?file=/index.js

### Steps to Reproduce the Bug or Issue

legendData的节点type为diamond，会报ShapeBase[shapeType] is not a constructor错误；

### Expected behavior

希望框架能支持不同形状的节点图例展示

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
感谢报告，我们会尽快修复
