### ISSUE TITLE
边的labelCfg 如何设置 state

### ISSUE THREAD

**Issue by xuoutput** [antvis/G6#3877]
### Describe the bug

边的labelCfg 如何设置 state, 比如 active 的时候修改下 label 的文案或者 bg

### Your Example Website or App

1

### Steps to Reproduce the Bug or Issue

1

### Expected behavior

提供配置demo

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
https://g6.antv.vision/zh/docs/manual/advanced/state-new#%E5%AD%90%E5%9B%BE%E5%BD%A2%E7%8A%B6%E6%80%81%E6%A0%B7%E5%BC%8F

用需要更改样式的图形 name 来作为 key 指定。不知道 name 的可以把边的图形分组打印出来看下内部有哪些图形，及其 name: console.log(edge.getContainer())
