### ISSUE TITLE
自定义 state的时候, 如何配置 click 后, 鼠标移出时不触发鼠标移出的状态

### ISSUE THREAD

**Issue by xuoutput** [antvis/G6#3878]
### Describe the bug

<img width="574" alt="image" src="https://user-images.githubusercontent.com/16385443/185303040-c84de509-8b4b-4cdf-a6dd-bbe2b2f892fd.png">
比如这个 demo, click 后,鼠标移出, 颜色恢复为最初的

### Your Example Website or App

1

### Steps to Reproduce the Bug or Issue

1

### Expected behavior

提供 demo 文档

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
没太明白，鼠标移出的时候不要调用 graph.setItemState(edge, 'active', false) 就好了

**Comment by xuoutput** [comment]
做了两个功能, 一个是鼠标移入的时候, 触发 边的 active 状态, 一个是点击 边 的 selected 状态, 
流程是 , 我鼠标 hover 边, 那么边的 active 在 mouse:enter 后 leave 的时候触发, 这个符合预期

问题在 点击边这里, 点击后 触发 edge 的 selected 状态, 此时鼠标还在边上, 没问题, 但如果我把鼠标移出边, 此时就触发了 鼠标的 leaveout, 所以边的样式就变为 active 为 false 的状态了

**Comment by Yanyan-Wang** [comment]
那你在 mouseleave 的时候判断 edge.hasState('selected') 的话就不要 setItemState(edge, 'active', false)
