### ISSUE TITLE
G6.Menu不支持移动端点击事件

### ISSUE THREAD

**Issue by JiangGeGe123** [antvis/G6#3879]
### Describe the bug

版本："@antv/g6": "^4.6.6",
代码：
new G6.Menu({
    ...
    trigger: "touchstart", 
});
不生效

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

trigger中无论绑定click还是 touchstart都无法在移动端生效

### Expected behavior

trigger:"touchstart"的能够在移动端正常触发

### Platform

所有移动端

**Comment by Yanyan-Wang** [comment]
欢迎社区 pr
