### ISSUE TITLE
自定义 edge, lineAppendWidth 不生效

### ISSUE THREAD

**Issue by xuoutput** [antvis/G6#3880]
### Describe the bug

lineAppendWidth 不生效

### Your Example Website or App

 1

### Steps to Reproduce the Bug or Issue

1

### Expected behavior

修复

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
是否没有配置到图形上？请给出复现在线 demo

**Comment by xuoutput** [comment]
demo 链接 https://codesandbox.io/s/tender-haslett-pcm7lg?file=/index.js
基于下面这个例子改造的
<img width="1369" alt="image" src="https://user-images.githubusercontent.com/16385443/185832629-f9a683b7-92f5-4a56-9f03-7dd480767c64.png">

**Comment by Yanyan-Wang** [comment]
这个是样式属性，要配到 style 里面，你放错位置了
