### ISSUE TITLE
如何设置在 canvas 的区域 鼠标的样式

### ISSUE THREAD

**Issue by xuoutput** [antvis/G6#3881]
### Describe the bug

在非node 和 edge 的地方, 空白画布处 , 设置鼠标样式

### Your Example Website or App

1

### Steps to Reproduce the Bug or Issue

1

### Expected behavior

配置 demo

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
graph.on('canvas:mousemove', e => {
  if (!graph.get('canvas').get('el').style.cursor !== 'move') graph.get('canvas').get('el').style.cursor = 'move'
});
