### ISSUE TITLE
画布上绑定双击和单击事件, 如何在双击的时候不触发单击的

### ISSUE THREAD

**Issue by xuoutput** [antvis/G6#3882]
### Describe the bug

<img width="179" alt="image" src="https://user-images.githubusercontent.com/16385443/185362449-b0f488fc-655b-42b8-b305-abd6a3b1b030.png">
<img width="627" alt="image" src="https://user-images.githubusercontent.com/16385443/185362511-884d8108-7330-4dbc-ad7a-36fdcd39bf4c.png">

### Your Example Website or App

1

### Steps to Reproduce the Bug or Issue

1

### Expected behavior

双击的时候不触发单击的

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
MDN 标准是双击也会触发两次单击。可以通过单击的时候 setTimeout 来判断短时间内如果没有第二次触发就是单击，否则清空计时器且不触发单击的响应逻辑
