### ISSUE TITLE
shape更新属性后,再使用setItemState更改node的状态[hover],shape新属性不生效

### ISSUE THREAD

**Issue by fromIceWorld** [antvis/G6#3884]
### 问题描述

graph.setItemState()函数在合并属性时，并没有拿到shape的最新属性

### 重现链接

无

### 重现步骤

0. graph.setItemState(item, 'hover', true),hover节点
1. node:click事件时：使用shape.attr(key, value)更新shape的属性
2. graph.setItemState(item, 'hover', false),取消hover；
3. shape的属性不是最新的属性

### 预期行为

graph.setItemState()在合并属性时拿到shape的最新属性。

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome,]
- G6 版本: [4.5.15]

### 补充说明（可选）

import G6 from '@antv/g6';
G6.registerNode(
    'input',
    {
        options: {
            size: [270, 40],
            style: {
                stroke: '#FFFFFF',
            },
        },
        afterDraw(cfg, group) {
            group.addShape('text', {
                attrs: {
                    text: 'test',
                    x: -130,
                    y: 0,
                    fontSize: 14,
                    textAlign: 'left',
                    textBaseline: 'middle',
                    fill: '#0000D9',
                },
                // must be assigned in G6 3.3 and later versions. it can be any value you want
                name: 'text-shape',
            });
        },
    },
    'rect'
);
let graph;

const container = document.getElementById('container');
const width = container.scrollWidth;
const height = container.scrollHeight || 500;
graph = new G6.Graph({
  container: 'container',
  width,
  height,
  // translate the graph to align the canvas's center, support by v3.5.1
  fitCenter: true,
  defaultNode: {
            type: 'input',
        },
  modes: {
    default: [],
  },
  nodeStateStyles: {
            hover: {
                lineWidth: 2,
                stroke: '#1890ff',
                fill: '#e6f7ff',
            },
        },
});

const data = {
  nodes: [
    {
      name: 'cardNodeApp',
      ip: '127.0.0.1',
      nodeError: true,
      dataType: 'root',
      keyInfo: 'this is a card node info',
      x: 100,
      y: 50,
    },   
  ],
  edges: [],
};
graph.on('node:click',evt=>{
  const shape = evt.shape;
  shape.attr('text', 'tw');
})
graph.on('node:mouseenter', (evt) => {
        const { item } = evt;
        graph.setItemState(item, 'hover', true);
    });
graph.on('node:mouseleave', (evt) => {
    const { item } = evt;
    graph.setItemState(item, 'hover', false);
});
graph.data(data);
graph.render();

**Comment by Yanyan-Wang** [comment]
需要通过 G6 的 API graph.updateItem 来更新节点属性，从而触发自定义节点中图形样式的更新，G6 才能统一管理样式。不能跳过 graph 的管理，直接用图形的 API 来更新样式。例如你这里的例子，把 shape.attr('text', 'tw') 换成 graph.updateItem(evt.item, { textValue: 'tw' }) 并且在定义这个图形的时候 text 属性使用 cfg.textValue，就能符合预期。

另外，因为你的自定义节点继承了 rect，更新时会复用到 rect 的 update 方法。可以复写 update 方法来相应你这里 cfg 的变更。改完后完整示例如下：
https://codesandbox.io/s/updateitem-instead-of-shape-attr-s4ssyf

**Comment by fromIceWorld** [comment]
谢谢解答😁
