### ISSUE TITLE
4.7.0 G6.TreeGraph 中 plugins G6.Grid无效 

### ISSUE THREAD

**Issue by ZombieBrand** [antvis/G6#3888]
### Describe the bug

版本4.7.0中 G6.TreeGraph 组件使用  plugins G6.Grid 无效

### Your Example Website or App

https://codesandbox.io/s/distracted-sea-jhndvn?file=/index.js

### Steps to Reproduce the Bug or Issue

官网实例加入grid plugins

### Expected behavior

正常显示grid

### Platform

- OS: macOS
- Browser: Chrome
- Version: 104

**Comment by Yanyan-Wang** [comment]
import G6, { Grid } from '@antv/g6';

`Plugin` -> `plugins`
