### ISSUE TITLE
接口报404

### ISSUE THREAD

**Issue by zhytang** [antvis/G6#3889]
### 问题描述

大数据量的树图，数据404

### 重现链接

http://antv.antfin.com/zh-cn/g6/3.x/demo/tree/cloudatlas-tree.html

### 重现步骤

打开即可

### 预期行为

可以正常显示

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
这个是 3.x 的官网已经不维护了，看 4.x 官网 https://g6.antv.vision/zh
