### ISSUE TITLE
树图的自定义节点宽度动态，如何展开收起到父节点中心

### ISSUE THREAD

**Issue by binnayao** [antvis/G6#3890]
### 问题描述

在紧凑树图中，我使用了自定义节点，自定义节点的宽度是动态变化的，然后使用了树图的全局动画，但是在我展开收起较宽的节点时候，子节点回到了父节点的左上角，我想让这些节点回到父节点的中心位置

另外我该如何自定义树图的展开收起动画（在收起的时候，节点直接销毁了）

![image](https://user-images.githubusercontent.com/19571809/186355367-80ab69d5-86bb-41ca-948e-4be0ef83d474.png)

### 重现链接

https://codesandbox.io/s/g6-guan-xi-tu-0tg3cf?file=/src/data.ts

### 重现步骤

1. 进入页面
2. 点击较宽的节点
3. 子节点以父节点的左上角动画

### 预期行为

希望以节点中心来做展开收起动画

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
自定义节点的 x y 各减去宽高的一半，相当于将节点的重心平移到自身坐标系的坐标原点

![image](https://user-images.githubusercontent.com/29593318/188124780-07282cd8-4216-49a5-a35d-d1ff2625e957.png)

**Comment by binnayao** [comment]
修改xy将节点中心和坐标原点重合后，布局变了，表现在宽节点的子节点

![image](https://user-images.githubusercontent.com/19571809/189798010-1cc7972a-aa8a-4047-a70f-3307b7bb37b0.png)

下面是代码链接：
https://codesandbox.io/s/g6-guan-xi-tu-forked-ihmw1y?file=/src/App.tsx
