### ISSUE TITLE
alt+tab健切换窗口后，画布不能拖动

### ISSUE THREAD

**Issue by WispYs** [antvis/G6#3892]
### 问题描述

alt+tab健切换窗口后，画布不能拖动

### 重现链接

https://codepen.io/LH_CHEN/pen/MWjQaKQ

### 重现步骤

使用alt+tab键切换窗口后，返回原页面G6画布不能拖动，再次按下tab键就可以拖动了

### 预期行为

推测应该是切换窗口的时候页面失焦导致的bug

### 平台

- 操作系统: [window 10]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [ 3.2.0 ]

**Comment by Yanyan-Wang** [comment]
更新到最新版本试试。上面链接失效了
