### ISSUE TITLE
shadow is not cleared when clearing selection, using SVG renderer

### ISSUE THREAD

**Issue by ensconced** [antvis/G6#3894]
### 问题描述

The node shadow is not cleared when a node is de-selected. 

### 重现链接

https://stackblitz.com/edit/react-btcnz7-srwe1e?file=index.js

### 重现步骤

1. Click the node to select it - the shadow appears
2. Click the canvas to de-select the node 

### 预期行为

I expected the shadow to disappear when clicking the empty canvas to de-select the node. But instead it remains there.

### 平台

-macOS
- tested Chrome and Firefox - the issue is present on both
- G6 4.7.0

### 屏幕截图或视频（可选）

![blur-bug](https://user-images.githubusercontent.com/29077863/187020940-f3aa55a9-0d68-43b6-ae5e-6ca3ec7137d0.gif)

**Comment by Yanyan-Wang** [comment]
Yes, there are some problems still remain in SVG renderer. But I'm afraid they could not be solved recently. we suggest to use canvas renderer instead.
