### ISSUE TITLE
edge disappears on selection, using SVG renderer

### ISSUE THREAD

**Issue by ensconced** [antvis/G6#3895]
### Describe the bug

When using the SVG renderer, selecting an edge causes it to disappear.

### Your Example Website or App

https://stackblitz.com/edit/react-btcnz7-eevgj8?file=index.js,index.html

### Steps to Reproduce the Bug or Issue

1. open the stackblitz link
2. click the "select edge" button 
3. the edge disappears

### Expected behavior

The behaviour should be the same as with the canvas renderer; the edge should remain visible and be displayed with the default selection styles.

### Screenshots or Videos

![edge](https://user-images.githubusercontent.com/29077863/187022781-955f5d1b-ad2e-4504-af8b-169d64d5b8ae.gif)

### Platform

- OS: macOS
- Browser: tested on chrome and firefox - the issue is present on both
- Version: chrome 104.0.5112.101, @antv/g6 4.7.0

**Comment by Yanyan-Wang** [comment]
Yes, there are some problems still remain in SVG renderer. But I'm afraid they could not be solved recently. we suggest to use canvas renderer instead.

**Comment by ensconced** [comment]
@Yanyan-Wang should we upgrade the version of g-svg that G6 is using? Is there any reason why we shouldn't do that?

**Comment by songhn233** [comment]
> Yes, there are some problems still remain in SVG renderer. But I'm afraid they could not be solved recently. we suggest to use canvas renderer instead.

Nowadays, svg rendering looks a lot more inconsistent than canvas, and it's harder to debug.
Are there any optimisations planned for this area?

**Comment by ensconced** [comment]
@songhn233 apparently the plan is to upgrade the SVG renderer some time soon https://github.com/antvis/G6/issues/2859#issuecomment-1364958051 🤞

**Comment by songhn233** [comment]
> @songhn233 apparently the plan is to upgrade the renderer some time soon [#2859 (comment)](https://github.com/antvis/G6/issues/2859#issuecomment-1364958051) 🤞

@ensconced Thanks for the reply, but it will be a while before the 5.0 plan is actually implemented, and the debugging costs for compatibility with 4.x and migration are likely to be greater.

I will prioritise other ways to support the need for custom HTML/React nodes.

**Comment by Aarebecca** [comment]
In the latest G6 5.0, this issue has been fixed. (By ClickElement behavior)
