### ISSUE TITLE
image shape onload后会覆盖其他层级高的shape

### ISSUE THREAD

**Issue by harekuer** [antvis/G6#3897]
### 问题描述

/* 先绘制的image图层 */
  group.addShape('image', {
    attrs: {
      x: 7 + offsetX,
      y: 7 + offsetY,
      height: 30,
      width: 30,
      img: config.icon
    },
    draggable: true,
    name: ‘main-icon'
  })
/* 其次才是斜线 */
 group.addShape('marker', {
    attrs: {
      x: offsetX,
      y: offsetY,
      r: 0,
      symbol: function(x, y, r) {
        return [['M', x, 45 + y], ['L', x + 45, y]]
      },
      stroke: '#fe0000',
      lineWidth: 2
    }
  })
初次渲染效果如下：
![image](https://user-images.githubusercontent.com/19220699/187149547-96159c82-5a24-4921-8b49-1d29066be925.png)

### 重现链接

无需

### 重现步骤

1、正常情况下marker层级是高于image，实际由于image http请求需要时间；
2、待Image返回，image层级会高于marker
3、缩放后或其它操作，重新渲染时图片读取的缓存，可以正常渲染

### 预期行为

![image](https://user-images.githubusercontent.com/19220699/187149624-1f48906b-3aa4-4554-82f6-c59592cc3b4e.png)

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
请提供一下在线复现的 demo

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
