### ISSUE TITLE
compactBox树图布局 内容过多线段错乱

### ISSUE THREAD

**Issue by makabaka29** [antvis/G6#3898]
### 问题描述

使用compactBox树图当内容过多时，polyline线段连接时靠近父级的节点与线段不会重叠，展示错乱。
![image](https://user-images.githubusercontent.com/83913456/187167500-5e73b94d-448d-4df8-969c-426386f43362.png)

### 重现链接

https://stackblitz.com/edit/vue-rntmb5?file=src%2FApp.vue

### 重现步骤

进入示例连接[https://stackblitz.com/edit/vue-rntmb5?file=src%2FApp.vue](url)

### 预期行为

我期望看到线段重叠不突出错乱

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google]
- G6 版本: [... ]
@

**Comment by Yanyan-Wang** [comment]
内置 polyline 在没有配置 controlPoints 的时候是自动寻径的，每条边都是根据自身情况寻找到最合适的路径，不会考虑到其它路径是怎么画的。如果你想要这些边在统一的水平位置合并，可以在布局完成之后每条边根据两端节点的 x y 计算一下 controlPoints 更新到边上 graph.updateItem(edge, {controlPoints: [....]})，这样就能自己控制边的弯折位置。

或者自定义折线边，原理也是一样，根据两端位置计算折线路径
https://g6.antv.vision/zh/examples/item/customEdge#customPolyline

**Comment by makabaka29** [comment]
感谢您的回复，我这边使用您说的自定义折线边，已经初步解决了边路径不合并的问题。
但是使用之后节点初次向下的三分之一处的y轴直线未显示，我初步分析认为是自定义布局的问题，在官网找到树形自定义布局后使用仍然无法显示三分之一直线边，这是自定义布局、自定义边或者自定义节点谁问题吗？
![1662446690111](https://user-images.githubusercontent.com/83913456/188565312-dfc3f0d2-f25f-4ef5-bf3d-681d0363bd2a.jpg)

**Comment by makabaka29** [comment]
> 你把现在的代码放到在线复现的 demo 链接里面，我看下。
https://stackblitz.com/edit/vue-rntmb5?file=src%2FApp.vue

**Comment by Yanyan-Wang** [comment]
要根据你这里需求和布局情况来计算哈，你 demo 里 path 计算得不对，你写的这个， startPoint.y / 3 + (2 / 3) * startPoint.y 不就是 startPoint.y 吗？而且这里两个控制点应该都在 1/2 位置比较合理
```
[
  ['M', startPoint.x, startPoint.y],
  ['L', endPoint.x, startPoint.y / 3 + (2 / 3) * startPoint.y], // 三分之一处
  ['L', endPoint.x, endPoint.y / 3 + (2 / 3) * startPoint.y], // 三分之二处
  ['L', endPoint.x, endPoint.y],
]
```

正确的是

![image](https://user-images.githubusercontent.com/29593318/208019786-03abb646-e1dd-4ad6-81c4-d8e5287bdb91.png)

另外，在图实例配置里面统一一下连接点位置
![image](https://user-images.githubusercontent.com/29593318/208019873-66f84474-c291-4f97-9236-c63559326c29.png)


完整的修改后 demo：https://stackblitz.com/edit/vue-3sjrvy?file=src%2FApp.vue
