### ISSUE TITLE
当我想在registerEdge中draw时，cfg中无法拿到节点信息，那我如何能根据节点文本来绘制线的不同style？

### ISSUE THREAD

**Issue by Yee-Guo** [antvis/G6#3899]
### 问题描述

当我想在registerEdge中draw时，
cfg中是包含source和target的，而registerNode中，我可以通过cfg拿到节点文本。
那我如何能根据节点文本来绘制线的不同style应该如何处理，因为我想通过判断条件重写 myline.attr({})中的属性

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]
无

**Comment by Yanyan-Wang** [comment]
可以在数据处理的时候把相关信息放到边数据上

或者在初次渲染完成之后，通过 updateItem 的方式更新边的样式， graph.once('afterrender', e => {}) 在 graph.render() 之前调用，相当于绑定一次性监听

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
