### ISSUE TITLE
 npm install failed

### ISSUE THREAD

**Issue by loveJasmine** [antvis/G6#3903]
### 问题描述

react-graph\g6> npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: g6@undefined
npm ERR! Found: tslint@6.1.3
npm ERR! node_modules/tslint
npm ERR!   tslint@"^6.1.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer tslint@"^5.11.0" from tslint-config-airbnb@5.11.2
npm ERR! node_modules/tslint-config-airbnb
npm ERR!   tslint-config-airbnb@"^5.11.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\xx\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xx\AppData\Local\npm-cache\_logs\2022-08-31T07_53_18_666Z-debug-0.log

### 重现链接

no

### 重现步骤

 npm install

### 预期行为

failed！

### 平台

win10

**Comment by Yanyan-Wang** [comment]
删掉 node_modules 使用 yarn install 试试

**Comment by loveJasmine** [comment]
还是一样的

**Comment by ensconced** [comment]
I am seeing the same with npm version 8.11.0. Is the suggestion to use yarn instead of npm? If so, the readme should be updated. And for either npm or yarn, shouldn't the lockfile be checked in?

**Comment by loveJasmine** [comment]
fixed

**Comment by ensconced** [comment]
@loveJasmine how did you fix it?

**Comment by loveJasmine** [comment]
update to the code repo

**Comment by vellengs** [comment]
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/5743338/205789459-7ac77098-f3ac-428a-be8b-f2084891ce08.png">

**Comment by vellengs** [comment]
npm install electron --verbose
一样存在这个问题，看样子是 electron 的依赖包出问题了。

**Comment by vellengs** [comment]
<img width="912" alt="image" src="https://user-images.githubusercontent.com/5743338/205807215-651d93a5-1f73-42ce-9ac2-4cd94193f390.png">
yarn 安装依旧还有这个问题。
