### ISSUE TITLE
npm run build:all failed

### ISSUE THREAD

**Issue by loveJasmine** [antvis/G6#3904]
### 问题描述

PS C:\react-graph\g6> npm run build:all

。。。。

Transform to esm for C:/react-graph/g6/packages/element/lib/src/nodes/rect.js
Transform to esm for C:/react-graph/g6/packages/element/lib/src/nodes/star.js
Transform to esm for C:/react-graph/g6/packages/element/lib/src/nodes/triangle.js

> build:plugin
> cd ./packages/plugin && npm run build

> @antv/g6-plugin@0.7.0 build
> npm run clean && father build

> @antv/g6-plugin@0.7.0 clean
> rimraf es esm lib dist

Clean dist directory
Build cjs with babel
Clean lib directory
src\bundling\index.ts(225,31): error TS2839: This condition will always return 'false' since JavaScript compares objects by reference, not value.
Transform to cjs for C:/react-graph/g6/packages/plugin/src/base.js
Transform to cjs for C:/react-graph/g6/packages/plugin/src/index.js
Transform to cjs for C:/react-graph/g6/packages/plugin/src/edgeFilterLens/index.js
Transform to cjs for C:/react-graph/g6/packages/plugin/src/bundling/index.js
Transform to cjs for C:/react-graph/g6/packages/plugin/src/imageMinimap/index.js
Transform to cjs for C:/react-graph/g6/packages/plugin/src/minimap/index.js
Transform to cjs for C:/react-graph/g6/packages/plugin/src/fisheye/index.js
Transform to cjs for C:/react-graph/g6/packages/plugin/src/grid/index.js
Transform to cjs for C:/react-graph/g6/packages/plugin/src/legend/index.js
Transform to cjs for C:/react-graph/g6/packages/plugin/src/menu/index.js
Transform to cjs for C:/react-graph/g6/packages/plugin/src/snapline/index.js
Transform to cjs for C:/react-graph/g6/packages/plugin/src/toolBar/index.js
Transform to cjs for C:/react-graph/g6/packages/plugin/src/tooltip/index.js
Transform to cjs for C:/react-graph/g6/packages/plugin/src/timeBar/constant.js
Transform to cjs for C:/react-graph/g6/packages/plugin/src/timeBar/controllerBtn.js
Transform to cjs for C:/react-graph/g6/packages/plugin/src/timeBar/handler.js
Transform to cjs for C:/react-graph/g6/packages/plugin/src/timeBar/index.js
Transform to cjs for C:/react-graph/g6/packages/plugin/src/timeBar/path.js
Transform to cjs for C:/react-graph/g6/packages/plugin/src/timeBar/timeBarSlice.js
Transform to cjs for C:/react-graph/g6/packages/plugin/src/timeBar/timeBarTooltip.js
Transform to cjs for C:/react-graph/g6/packages/plugin/src/timeBar/timeButton.js
Transform to cjs for C:/react-graph/g6/packages/plugin/src/timeBar/trend.js
Transform to cjs for C:/react-graph/g6/packages/plugin/src/timeBar/trendTimeBar.js
TypeScript: 1 semantic error
TypeScript: emit succeeded (with errors)
node:events:498
      throw er; // Unhandled 'error' event
      ^

Error: TypeScript: Compilation failed
    at Output.mightFinish (C:\react-graph\g6\node_modules\gulp-typescript\release\output.js:130:43)
    at C:\react-graph\g6\node_modules\gulp-typescript\release\output.js:65:22
Emitted 'error' event on Duplexify instance at:
    at Duplexify._destroy (C:\react-graph\g6\node_modules\duplexify\index.js:191:15)
    at C:\react-graph\g6\node_modules\duplexify\index.js:182:10
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
npm ERR! Lifecycle script `build` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: @antv/g6-plugin@0.7.0
npm ERR!   at location: C:\react-graph\g6\packages\plugin
PS C:\react-graph\g6>

### 重现链接

no

### 重现步骤

\g6> npm run build:all

### 预期行为

pass

### 平台

windows

**Comment by Yanyan-Wang** [comment]
你的 TS 版本是？

**Comment by loveJasmine** [comment]
PS C:\react-graph\g6> tsc -v
Version 4.8.2

**Comment by Yanyan-Wang** [comment]
拉一下最新代码，src\bundling\index.ts(225,31) 的 ts 问题解决了

**Comment by zmcode** [comment]
![image](https://github.com/antvis/G6/assets/48686959/7024252b-a1bc-4528-9718-8f4fa84243a5)
我有同样的问题

> 拉一下最新代码，src\bundling\index.ts(225,31) 的 ts 问题解决了

**Comment by Aarebecca** [comment]
请参考这个 issue https://github.com/antvis/G6/issues/5182
