### ISSUE TITLE
动态创建连线，更新连线的箭头失败

### ISSUE THREAD

**Issue by yanliang-code** [antvis/G6#3905]
### 问题描述

点击节点连线后，通过updateItem无法增加线两端的箭头

### 重现链接

https://codepen.io/yanliang-code/pen/xxjKYEe

### 重现步骤

1.点击节点连线
2.观察线变化

### 预期行为

线颜色变了，但是箭头未渲染出来

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
linkCenter: true 让边连到了节点中心，箭头被节点挡住了，调低节点透明度就可以看到了。需要使用 `d` 让箭头“往后退”一些，https://g6.antv.vision/zh/docs/manual/middle/elements/edges/arrow#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95-1

例如在你的例子里使用
```
endArrow: {
    path: G6.Arrow.triangle(10, 10, 10), // 使用内置箭头路径函数，参数为箭头的 宽度、长度、偏移量（默认为 0，与 d 对应）
    d: 10,
    fill: '#088'
  },
```

**Comment by yanliang-code** [comment]
![image](https://user-images.githubusercontent.com/60208330/188293742-3114556c-c90b-4119-944a-fa6874124a1b.png)
目前这个连线效果多条线，箭头会重叠；我看g6-editor连线效果如下不会重叠，能给些实现思路嘛，谢谢
![image](https://user-images.githubusercontent.com/60208330/188293770-d3e14fed-f138-41f2-b9aa-e08e99802441.png)

**Comment by yanliang-code** [comment]
> ![image](https://user-images.githubusercontent.com/60208330/188293742-3114556c-c90b-4119-944a-fa6874124a1b.png) 目前这个连线效果多条线，箭头会重叠；我看g6-editor连线效果如下不会重叠，能给些实现思路嘛，谢谢 ![image](https://user-images.githubusercontent.com/60208330/188293770-d3e14fed-f138-41f2-b9aa-e08e99802441.png)

现在想到的是graph配置设置 linkCenter: true，箭头使用 d 进行偏移，然后用processParallelEdges函数将offsetDiff设置大，不过还有其他情况处理不行
