### ISSUE TITLE
更新数据，原来的图无法重新渲染

### ISSUE THREAD

**Issue by Yee-Guo** [antvis/G6#3906]
### 问题描述

当我更新树的数据时，图并没有重新渲染。而后我尝试
 1、graph.refresh() graph.changeData(data) 失败 （大致出现了渲染出两张图的场景）
2、 graph.updateChildren(data) 失败
3、我将graph存到this.controllgraph数据中，在更改数据时，我 this.controllgraph.destroy() 然而此时传入的data可以打印出，但是却抛出错误Cannot set properties of null (setting 'data') 

我想更新数据并重新绘制树图 改如何处理?

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]
无

**Comment by Yanyan-Wang** [comment]
graph.changeData 即可，不行的话请给出在线复现 demo

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
