### ISSUE TITLE
使用additem添加点和边后，点无法移动。位置也不对

### ISSUE THREAD

**Issue by mosesyu95** [antvis/G6#3907]
### Describe the bug

使用additem添加33,44点后，拖动点时33,44无法移动。且添加的位置有点有点偏

### Your Example Website or App

https://codesandbox.io/s/87vp4w

### Steps to Reproduce the Bug or Issue

1、双击11 或者22
2、拖动11或者22
3、拖动33或者44

### Expected behavior

添加后期望11和22 位置不变，33,44可以和11、22一样可以移动。
和一次性加载所有点效果一样。

### Platform

- OS: macOS,
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
是否代码没保存？没看到你描述中的代码

**Comment by mosesyu95** [comment]
可以了，
![image](https://user-images.githubusercontent.com/22955185/188112168-fda7492d-3f8a-4177-be86-c23828fc5c1c.png)

**Comment by Yanyan-Wang** [comment]
1. 升级 G6 到 4.7.1
2. graph.layout 不用每添加一个元素就调用，可以在元素全部添加完成之后调用
3. 节点能够拖拽，需要在图实例上配置交互：modes: { default: ['drag-node'] }

**Comment by mosesyu95** [comment]
thx ,g6这个项目太好了，期待社区越来越好
