### ISSUE TITLE
两节点连接多条线，箭头会出现重叠效果，求个优化思路，谢谢

### ISSUE THREAD

**Issue by ByronYan01** [antvis/G6#3908]
### 问题描述

#3905 issue 情况下，节点连接多条线，箭头会出现重叠效果；看到g6-editor连线效果比较好，求个优化思路，谢谢

### 重现链接

https://codepen.io/yanliang-code/pen/xxjKYEe

### 重现步骤

节点连接多个线

### 预期行为

期望g6-editor连线效果

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by yanliang-code** [comment]
![image](https://user-images.githubusercontent.com/60208330/188423579-e1c7c645-31b6-488a-ac5d-b4d325515e34.png)

**Comment by Yanyan-Wang** [comment]
或者你就在图示例上配置 linkCenter: true ，然后配置箭头的时候通过 d 往外“退”：https://g6.antv.vision/zh/docs/manual/middle/elements/edges/arrow#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95-1

**Comment by yanliang-code** [comment]
> 或者你就在图示例上配置 linkCenter: true ，然后配置箭头的时候通过 d 往外“退”：https://g6.antv.vision/zh/docs/manual/middle/elements/edges/arrow#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95-1

我按照您这个思路，自定义一下箭头，但是如果两个节点距离远箭头与线连接处正常，但是离近了，就偏离了
现象见 ：https://codepen.io/yanliang-code/pen/xxjKYEe

**Comment by yanliang-code** [comment]
![Snipaste_2022-09-17_16-28-08](https://user-images.githubusercontent.com/60208330/190848018-109a0f8e-930b-48b9-93c5-a2382144e953.png)

**Comment by Yanyan-Wang** [comment]
![image](https://user-images.githubusercontent.com/29593318/190947244-ef89ae0b-1ff5-4ab1-bca3-25243528cf9c.png)


要用 d 往后“退”才能沿着路径退哈。你上面的写法是直接改了 path，这样不是沿着路径的

**Comment by yanliang-code** [comment]
> ![image](https://user-images.githubusercontent.com/29593318/190947244-ef89ae0b-1ff5-4ab1-bca3-25243528cf9c.png)
> 
> 要用 d 往后“退”才能沿着路径退哈。你上面的写法是直接改了 path，这样不是沿着路径的

按照您这边得说法我改了一下，我发现在拖动节点时，会出现画布被污染得情况，是我哪里使用得不对吗
https://codepen.io/yanliang-code/pen/xxjKYEe

**Comment by yanliang-code** [comment]
![image](https://user-images.githubusercontent.com/60208330/190963565-17961acc-fe64-4dd1-8236-1920295508b3.png)

**Comment by yanliang-code** [comment]
> > ![image](https://user-images.githubusercontent.com/29593318/190947244-ef89ae0b-1ff5-4ab1-bca3-25243528cf9c.png)
> > 要用 d 往后“退”才能沿着路径退哈。你上面的写法是直接改了 path，这样不是沿着路径的
> 
> 按照您这边得说法我改了一下，我发现在拖动节点时，会出现画布被污染得情况，是我哪里使用得不对吗 https://codepen.io/yanliang-code/pen/xxjKYEe

我这边看其他issue，发现 graph.get('canvas').set('localRefresh', false) 可以解决这个问题，但是我想了解一下，我设置这个后会有什么影响吗

**Comment by Yanyan-Wang** [comment]
小数据集上不会有什么问题，大规模数据时可能一定程度影响性能
