### ISSUE TITLE
当combo与nodes都设置的xy时， combo中的node 位置渲染不对。

### ISSUE THREAD

**Issue by PmcFizz** [antvis/G6#3909]
### 问题描述

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <title>Tutorial Demo</title>
  <style type="text/css">
    * {
      padding: 0;
      margin: 0;
    }
  </style>
</head>

<body>

  <div id="mountNode" style="border: 1px solid #ddd;height: 100vh;background-color: #009688"></div>

  <script src="https://gw.alipayobjects.com/os/lib/antv/g6/4.6.17/dist/g6.min.js"></script>

  <script>

    // 渲染数据
    function renderView() {
      const data = {}
      data.combos = [
        {
          id: 'businessSystem',
          padding: [0, 0, 0, 0],
          size: [500, 500],
          fixSize: [500, 500],
          x: 250,
          y: 250,
          label: '业务系统',
        }
      ]

      data.nodes = [
        {
          id: '12',
          comboId: 'businessSystem',
          type: 'rect',
          size: [50, 50],
          x: 0,
          y: 0
        }
      ]

      // 创建 G6 图实例
      const containerEl = document.querySelector("#mountNode")
      containerEl.scrollWidth
      const graph = new G6.Graph({
        container: 'mountNode', // 指定图画布的容器 id，与第 9 行的容器对应
        // 画布宽高
        width: containerEl.scrollWidth,
        height: containerEl.scrollHeight,
        groupByTypes: false,
        default: ['drag-canvas', 'zoom-canvas'],
        modes: {
          default: ['zoom-canvas', 'drag-canvas'],
        },
        defaultCombo: {
          type: 'rect',
          padding: [0, 0, 0, 0],
          style: {
            opacity: 0.6,
            stroke: '#C4C9DF',
            lineWidth: 1,
            lineDash: [2, 2],
          },
          labelCfg: {
            position: 'top',
          },
        },
        defaultNode: {
          type: 'rect',
          size: [50, 50],
          padding: [0, 0, 0, 0],
          labelCfg: {
            position: 'center',
          },
          anchorPoints: [
            [0, 0.5],
            [1, 0.5],
          ],
        },
        defaultEdge: {
          type: 'cubic-horizontal',
          style: {
            endArrow: {
              path: G6.Arrow.triangle(5, 5, 0),
            },
          },
        },
      });
      // 读取数据
      graph.data(data);
      // 渲染图
      graph.render();

    }

    renderView()

  </script>
</body>

</html>
```

![image](https://user-images.githubusercontent.com/13403284/188405758-afa5ad1d-b7d4-4a73-9035-c67ae39bda66.png)

节点的渲染  坐标不对。

### 重现链接

https://codesandbox.io/s/epic-https-tv0hjr?file=/index.html

### 重现步骤

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <title>Tutorial Demo</title>
  <style type="text/css">
    * {
      padding: 0;
      margin: 0;
    }
  </style>
</head>

<body>

  <div id="mountNode" style="border: 1px solid #ddd;height: 100vh;background-color: #009688"></div>

  <script src="https://gw.alipayobjects.com/os/lib/antv/g6/4.6.17/dist/g6.min.js"></script>

  <script>

    // 渲染数据
    function renderView() {
      const data = {}
      data.combos = [
        {
          id: 'businessSystem',
          padding: [0, 0, 0, 0],
          size: [500, 500],
          fixSize: [500, 500],
          x: 250,
          y: 250,
          label: '业务系统',
        }
      ]

      data.nodes = [
        {
          id: '12',
          comboId: 'businessSystem',
          type: 'rect',
          size: [50, 50],
          x: 0,
          y: 0
        }
      ]

      // 创建 G6 图实例
      const containerEl = document.querySelector("#mountNode")
      containerEl.scrollWidth
      const graph = new G6.Graph({
        container: 'mountNode', // 指定图画布的容器 id，与第 9 行的容器对应
        // 画布宽高
        width: containerEl.scrollWidth,
        height: containerEl.scrollHeight,
        groupByTypes: false,
        default: ['drag-canvas', 'zoom-canvas'],
        modes: {
          default: ['zoom-canvas', 'drag-canvas'],
        },
        defaultCombo: {
          type: 'rect',
          padding: [0, 0, 0, 0],
          style: {
            opacity: 0.6,
            stroke: '#C4C9DF',
            lineWidth: 1,
            lineDash: [2, 2],
          },
          labelCfg: {
            position: 'top',
          },
        },
        defaultNode: {
          type: 'rect',
          size: [50, 50],
          padding: [0, 0, 0, 0],
          labelCfg: {
            position: 'center',
          },
          anchorPoints: [
            [0, 0.5],
            [1, 0.5],
          ],
        },
        defaultEdge: {
          type: 'cubic-horizontal',
          style: {
            endArrow: {
              path: G6.Arrow.triangle(5, 5, 0),
            },
          },
        },
      });
      // 读取数据
      graph.data(data);
      // 渲染图
      graph.render();

    }

    renderView()

  </script>
</body>

</html>
```

根据节点设置的坐标信息 
        id: '12',
          comboId: 'businessSystem',
          type: 'rect',
          size: [50, 50],
          x: 0,
          y: 0

该节点应该渲染在左上角，而部署combo的中心。

### 预期行为

希望节点的坐标能够正确渲染。

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome,]
- G6 版本: [4.6.17]

**Comment by PmcFizz** [comment]
@lifesinger @yuanchuan @9renpoto @afc163 麻烦能看一下这个问题吗？ 已提供了 demo地址。 https://codesandbox.io/s/epic-https-tv0hjr?file=/index.html

节点位置渲染不对。

**Comment by PmcFizz** [comment]
> 符合预期，节点和 combo 的相对位置不会因为设置了节点和 combo 位置而发生改变。数据中节点和 combo 都有位置信息时，以 combo x y 为准。我理解你可能想让节点不要位于 combo 中心，那么应该通过 combo 的 padding 来实现

这一句话 “数据中节点和 combo 都有位置信息时，以 combo x y 为准”   我是不是可以这样理解？

当我给combo 设置了x，y坐标信息， 并且给combo 中的节点也也都设置了x，y坐标。那么这些节点的坐标信息将会被忽略。

如果是这样的话，那么combo 中的节点是如何布局的那？根据示例化的 GraphOptions.layout 参数来布局吗？

如果使用自定义布局能不能让combo以及combo中的 nodes的坐标信息都生效？
@Yanyan-Wang  感谢大佬百忙之中回复我的问题，最近一个月一直在研究g6，做一个自定义排版的数据血缘图。请问g6有没有官方交流群？ 再次感谢.

**Comment by Yanyan-Wang** [comment]
> 当我给combo 设置了x，y坐标信息， 并且给combo 中的节点也也都设置了x，y坐标。那么这些节点的坐标信息将会被忽略。

是的。

combo 内外的布局，可以使用 comboCombined，内部外部的布局可以分别配置
https://g6.antv.vision/zh/docs/api/graphLayout/comboCombined
https://g6.antv.vision/zh/examples/net/comboLayout#comboCombined

**Comment by PmcFizz** [comment]
> > 当我给combo 设置了x，y坐标信息， 并且给combo 中的节点也也都设置了x，y坐标。那么这些节点的坐标信息将会被忽略。
> 
> 是的。
> 
> combo 内外的布局，可以使用 comboCombined，内部外部的布局可以分别配置 https://g6.antv.vision/zh/docs/api/graphLayout/comboCombined https://g6.antv.vision/zh/examples/net/comboLayout#comboCombined

了解了。非常感谢。我去尝试一下。

**Comment by wangxiang666** [comment]
> > > 当我给combo 设置了x，y坐标信息， 并且给combo 中的节点也也都设置了x，y坐标。那么这些节点的坐标信息将会被忽略。
> > 
> > 
> > 是的。
> > combo 内外的布局，可以使用 comboCombined，内部外部的布局可以分别配置 https://g6.antv.vision/zh/docs/api/graphLayout/comboCombined https://g6.antv.vision/zh/examples/net/comboLayout#comboCombined
> 
> 了解了。非常感谢。我去尝试一下。


兄弟，我和你的场景极其相似，comboCombined布局未解决我的问题，你解决了这个问题了吗，希望有机会沟通交流

**Comment by PmcFizz** [comment]
> 

解决啦

**Comment by PmcFizz** [comment]
> > > > 当我给combo 设置了x，y坐标信息， 并且给combo 中的节点也也都设置了x，y坐标。那么这些节点的坐标信息将会被忽略。
> > > 
> > > 
> > > 是的。
> > > combo 内外的布局，可以使用 comboCombined，内部外部的布局可以分别配置 https://g6.antv.vision/zh/docs/api/graphLayout/comboCombined https://g6.antv.vision/zh/examples/net/comboLayout#comboCombined
> > 
> > 
> > 了解了。非常感谢。我去尝试一下。
> 
> 兄弟，我和你的场景极其相似，comboCombined布局未解决我的问题，你解决了这个问题了吗，希望有机会沟通交流

解决啦

**Comment by wangxiang666** [comment]
> > > > > 当我给combo 设置了x，y坐标信息， 并且给combo 中的节点也也都设置了x，y坐标。那么这些节点的坐标信息将会被忽略。
> > > > 
> > > > 
> > > > 是的。
> > > > combo 内外的布局，可以使用 comboCombined，内部外部的布局可以分别配置 https://g6.antv.vision/zh/docs/api/graphLayout/comboCombined https://g6.antv.vision/zh/examples/net/comboLayout#comboCombined
> > > 
> > > 
> > > 了解了。非常感谢。我去尝试一下。
> > 
> > 
> > 兄弟，我和你的场景极其相似，comboCombined布局未解决我的问题，你解决了这个问题了吗，希望有机会沟通交流
> 
> 解决啦

方便写下思路或者代码块嘛，感谢

**Comment by PmcFizz** [comment]
> > > > > > 当我给combo 设置了x，y坐标信息， 并且给combo 中的节点也也都设置了x，y坐标。那么这些节点的坐标信息将会被忽略。
> > > > > 
> > > > > 
> > > > > 是的。
> > > > > combo 内外的布局，可以使用 comboCombined，内部外部的布局可以分别配置 https://g6.antv.vision/zh/docs/api/graphLayout/comboCombined https://g6.antv.vision/zh/examples/net/comboLayout#comboCombined
> > > > 
> > > > 
> > > > 了解了。非常感谢。我去尝试一下。
> > > 
> > > 
> > > 兄弟，我和你的场景极其相似，comboCombined布局未解决我的问题，你解决了这个问题了吗，希望有机会沟通交流
> > 
> > 
> > 解决啦
> 
> 方便写下思路或者代码块嘛，感谢，或者建个群讨论一下,我除了xy还需要设置固定的combo大小，padding我也设置了[0,0,0,0]，但是总是会错位，combo我给的位置是对齐的 ![image](https://user-images.githubusercontent.com/52997798/219559184-e0e2e345-c00c-4255-8272-d02ce5026714.png)

最近很忙的😅。如果需要技术指导，可以帮你看看问题。 demon_0212

**Comment by Potato-X** [comment]
> > > > > > > 当我给combo 设置了x，y坐标信息， 并且给combo 中的节点也也都设置了x，y坐标。那么这些节点的坐标信息将会被忽略。
> > > > > > 
> > > > > > 
> > > > > > 是的。
> > > > > > combo 内外的布局，可以使用 comboCombined，内部外部的布局可以分别配置 https://g6.antv.vision/zh/docs/api/graphLayout/comboCombined https://g6.antv.vision/zh/examples/net/comboLayout#comboCombined
> > > > > 
> > > > > 
> > > > > 了解了。非常感谢。我去尝试一下。
> > > > 
> > > > 
> > > > 兄弟，我和你的场景极其相似，comboCombined布局未解决我的问题，你解决了这个问题了吗，希望有机会沟通交流
> > > 
> > > 
> > > 解决啦
> > 
> > 
> > 方便写下思路或者代码块嘛，感谢，或者建个群讨论一下,我除了xy还需要设置固定的combo大小，padding我也设置了[0,0,0,0]，但是总是会错位，combo我给的位置是对齐的 ![image](https://user-images.githubusercontent.com/52997798/219559184-e0e2e345-c00c-4255-8272-d02ce5026714.png)
> 
> 最近很忙的😅。如果需要技术指导，可以帮你看看问题。 demon_0212

兄弟，我这里遇到一个问题，就是那个combocombined里面的innerlayout如果type为dagre的时候，是不是在combo嵌套的情况下，区分不了内层的combo和节点啊。
![image](https://github.com/antvis/G6/assets/68857645/931819f2-f19b-4db4-9cef-42d9539fa06d)
我这里设置的是LR，但是，内层的这个combo连接状况却是垂直连接的

**Comment by b-ss** [comment]
> > > > > > 当我给combo 设置了x，y坐标信息， 并且给combo 中的节点也也都设置了x，y坐标。那么这些节点的坐标信息将会被忽略。
> > > > > 
> > > > > 
> > > > > 是的。
> > > > > combo 内外的布局，可以使用 comboCombined，内部外部的布局可以分别配置 https://g6.antv.vision/zh/docs/api/graphLayout/comboCombined https://g6.antv.vision/zh/examples/net/comboLayout#comboCombined
> > > > 
> > > > 
> > > > 了解了。非常感谢。我去尝试一下。
> > > 
> > > 
> > > 兄弟，我和你的场景极其相似，comboCombined布局未解决我的问题，你解决了这个问题了吗，希望有机会沟通交流
> > 
> > 
> > 解决啦
> 
> 方便写下思路或者代码块嘛，感谢，或者建个群讨论一下,我除了xy还需要设置固定的combo大小，padding我也设置了[0,0,0,0]，但是总是会错位，combo我给的位置是对齐的 ![image](https://user-images.githubusercontent.com/52997798/219559184-e0e2e345-c00c-4255-8272-d02ce5026714.png)

请问你这是用的comboCombined的布局吗？外层设置的dagre?内层是啥啊？方便告知下吗？

**Comment by Potato-X** [comment]
> > > > > > > 当我给combo 设置了x，y坐标信息， 并且给combo 中的节点也也都设置了x，y坐标。那么这些节点的坐标信息将会被忽略。
> > > > > > 
> > > > > > 
> > > > > > 是的。
> > > > > > combo 内外的布局，可以使用 comboCombined，内部外部的布局可以分别配置 https://g6.antv.vision/zh/docs/api/graphLayout/comboCombined https://g6.antv.vision/zh/examples/net/comboLayout#comboCombined
> > > > > 
> > > > > 
> > > > > 了解了。非常感谢。我去尝试一下。
> > > > 
> > > > 
> > > > 兄弟，我和你的场景极其相似，comboCombined布局未解决我的问题，你解决了这个问题了吗，希望有机会沟通交流
> > > 
> > > 
> > > 解决啦
> > 
> > 
> > 方便写下思路或者代码块嘛，感谢，或者建个群讨论一下,我除了xy还需要设置固定的combo大小，padding我也设置了[0,0,0,0]，但是总是会错位，combo我给的位置是对齐的 ![image](https://user-images.githubusercontent.com/52997798/219559184-e0e2e345-c00c-4255-8272-d02ce5026714.png)
> 
> 请问你这是用的comboCombined的布局吗？外层设置的dagre?内层是啥啊？方便告知下吗？

是用的comboCombined，我内外层之前都用的dagre，结果就出现内层combo嵌套的时候，区分不了内层的combo和节点

**Comment by b-ss** [comment]
> > > > > > > > 当我给combo 设置了x，y坐标信息， 并且给combo 中的节点也也都设置了x，y坐标。那么这些节点的坐标信息将会被忽略。
> > > > > > > 
> > > > > > > 
> > > > > > > 是的。
> > > > > > > combo 内外的布局，可以使用 comboCombined，内部外部的布局可以分别配置 https://g6.antv.vision/zh/docs/api/graphLayout/comboCombined https://g6.antv.vision/zh/examples/net/comboLayout#comboCombined
> > > > > > 
> > > > > > 
> > > > > > 了解了。非常感谢。我去尝试一下。
> > > > > 
> > > > > 
> > > > > 兄弟，我和你的场景极其相似，comboCombined布局未解决我的问题，你解决了这个问题了吗，希望有机会沟通交流
> > > > 
> > > > 
> > > > 解决啦
> > > 
> > > 
> > > 方便写下思路或者代码块嘛，感谢，或者建个群讨论一下,我除了xy还需要设置固定的combo大小，padding我也设置了[0,0,0,0]，但是总是会错位，combo我给的位置是对齐的 ![image](https://user-images.githubusercontent.com/52997798/219559184-e0e2e345-c00c-4255-8272-d02ce5026714.png)
> > 
> > 
> > 请问你这是用的comboCombined的布局吗？外层设置的dagre?内层是啥啊？方便告知下吗？
> 
> 是用的comboCombined，我内外层之前都用的dagre，结果就出现内层combo嵌套的时候，区分不了内层的combo和节点

我想请教下，这个图你是咋实现的啊？我设置的外层是dagre，内层是grid，所有的节点都被combol包裹，但是combol都是重叠的。。

**Comment by apankun** [comment]
> > > > > > > > 当我给combo 设置了x，y坐标信息， 并且给combo 中的节点也也都设置了x，y坐标。那么这些节点的坐标信息将会被忽略。
> > > > > > > 
> > > > > > > 
> > > > > > > 是的。
> > > > > > > combo 内外的布局，可以使用 comboCombined，内部外部的布局可以分别配置 https://g6.antv.vision/zh/docs/api/graphLayout/comboCombined https://g6.antv.vision/zh/examples/net/comboLayout#comboCombined
> > > > > > 
> > > > > > 
> > > > > > 了解了。非常感谢。我去尝试一下。
> > > > > 
> > > > > 
> > > > > 兄弟，我和你的场景极其相似，comboCombined布局未解决我的问题，你解决了这个问题了吗，希望有机会沟通交流
> > > > 
> > > > 
> > > > 解决啦
> > > 
> > > 
> > > 方便写下思路或者代码块嘛，感谢，或者建个群讨论一下,我除了xy还需要设置固定的combo大小，padding我也设置了[0,0,0,0]，但是总是会错位，combo我给的位置是对齐的 ![image](https://user-images.githubusercontent.com/52997798/219559184-e0e2e345-c00c-4255-8272-d02ce5026714.png)
> > 
> > 
> > 请问你这是用的comboCombined的布局吗？外层设置的dagre?内层是啥啊？方便告知下吗？
> 
> 是用的comboCombined，我内外层之前都用的dagre，结果就出现内层combo嵌套的时候，区分不了内层的combo和节点

你好，我也遇到了一样的问题，内层用dagre无法识别，请问你最后是怎么解决的
