### ISSUE TITLE
自定义节点有图片导致页面拖拽卡顿

### ISSUE THREAD

**Issue by simplexdq** [antvis/G6#3910]
### 问题描述

自定义复杂节点，有三个image-shape，当节点数达到150左右时，拖拽画布会有卡顿，使用其他内置节点则不会。
将节点中的image-shape去掉后，拖拽不再卡顿。
想问下有没有优化的方式？
（在拖拽时，没有触发节点的draw和update方法）

### 重现链接

none

### 重现步骤

节点是否加图片图形

### 预期行为

拖拽不卡顿

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.6.15 ]

**Comment by Yanyan-Wang** [comment]
拖拽节点要更新节点的位置，是会触发 update 的。你的自定义节点有没有实现 update 方法？如果没有的话，可以写一下，判断没有必要的情况下，不更新 image-shape

**Comment by simplexdq** [comment]
> 拖拽节点要更新节点的位置，是会触发 update 的。你的自定义节点有没有实现 update 方法？如果没有的话，可以写一下，判断没有必要的情况下，不更新 image-shape

我可能没有描述清楚。是拖拽整个画布，或者缩放的时候，会有卡顿。
节点内部有自定义的draw和update方法，但这个时候我打印了一下，没有触发自定义的draw和update方法。
所以想问下有没有优化方案～

**Comment by Yanyan-Wang** [comment]
drag-canvas 和 zoom-canvas 可以开启优化 enableOptimize，过程中会隐藏非 keyShape

https://g6.antv.vision/zh/docs/manual/middle/states/defaultBehavior#drag-canvas

**Comment by simplexdq** [comment]
> drag-canvas 和 zoom-canvas 可以开启优化 enableOptimize，过程中会隐藏非 keyShape
> 
> https://g6.antv.vision/zh/docs/manual/middle/states/defaultBehavior#drag-canvas

这个地方尝试了一下，不满足需求。因为图片被隐藏后，会导致拖拽时整个图都是黑的，没有节点展示，效果不好。
请问这里还有别的方式吗？或者后续是否会针对这一点进行修复呢？谢谢～

**Comment by Yanyan-Wang** [comment]
整个都是黑的，和自定义节点方式有关，keyShape 不会被隐藏，你的自定义节点里面使用那个能够代表这个节点的一个图形作为 keyShape，也就是 draw 方法返回的图形。

具体还有问题请提供一下在线复现 demo

**Comment by csspmini-web** [comment]
> > drag-canvas 和 zoom-canvas 可以开启优化 enableOptimize，过程中会隐藏非 keyShape
> > https://g6.antv.vision/zh/docs/manual/middle/states/defaultBehavior#drag-canvas
> 
> 这个地方尝试了一下，不满足需求。因为图片被隐藏后，会导致拖拽时整个图都是黑的，没有节点展示，效果不好。 请问这里还有别的方式吗？或者后续是否会针对这一点进行修复呢？谢谢～

建议你自己从 graph 实例上拿到 drag-canvas 的 对象，并将它的 updateViewport 函数 优化下，拖动过程中 这个函数时会执行非常多次，最终执行 graph.translate(dx, dy) 函数，如果你的图形很多很复杂，可以考虑将 这个过程中产生 updateViewport 调用 做一下节流防抖，这样可以避免大量计算

**Comment by Yanyan-Wang** [comment]
> > > drag-canvas 和 zoom-canvas 可以开启优化 enableOptimize，过程中会隐藏非 keyShape
> > > https://g6.antv.vision/zh/docs/manual/middle/states/defaultBehavior#drag-canvas
> > 
> > 
> > 这个地方尝试了一下，不满足需求。因为图片被隐藏后，会导致拖拽时整个图都是黑的，没有节点展示，效果不好。 请问这里还有别的方式吗？或者后续是否会针对这一点进行修复呢？谢谢～
> 
> 建议你自己从 graph 实例上拿到 drag-canvas 的 对象，并将它的 updateViewport 函数 优化下，拖动过程中 这个函数时会执行非常多次，最终执行 graph.translate(dx, dy) 函数，如果你的图形很多很复杂，可以考虑将 这个过程中产生 updateViewport 调用 做一下节流防抖，这样可以避免大量计算

应该不需要呀，drag-canvas 对图形的隐藏是在 dragstart 的时候做的，显示在 dragend 的时候做的。所以不会在拖拽过程中频繁地去执行隐藏和显示图形的

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
