### ISSUE TITLE
graph.get('vedges') gives empty array

### ISSUE THREAD

**Issue by ensconced** [antvis/G6#3912]
### Describe the bug

After using `graph.createCombo` to create some combos where there are edges between nodes in different combos, I expect `graph.get('vedges')` to return an array with length > 0. But it returns an empty array. If `graph.get('vedges')` is done in a setTimeout, the vedges are present, but I would expect them to be created synchronously.

### Your Example Website or App

https://stackblitz.com/edit/react-btcnz7-z4mbab?file=index.js

### Steps to Reproduce the Bug or Issue

1. see console output in stackblitz example

### Expected behavior

I expect `graph.get('vedges')` to contain the new vedges, when called immediately after `graph.createCombo`.

### Platform

- OS: macOS
- Browser: Chrome
- @antv/g6 4.7.0

**Comment by Yanyan-Wang** [comment]
fixed by 4.7.2
