### ISSUE TITLE
`type: polyline` can give strange edge shapes when used on vedges

### ISSUE THREAD

**Issue by ensconced** [antvis/G6#3913]
### Describe the bug

In this example using `type: "polyline"` on combo vedges, the edge has an unexpected shape - one segment of the line goes way off to the left.

### Your Example Website or App

https://stackblitz.com/edit/react-btcnz7-soojyu?file=index.js

### Steps to Reproduce the Bug or Issue

1. open the stackblitz example
2. the edge looks like this:

![Screenshot 2022-09-05 at 16 15 32](https://user-images.githubusercontent.com/29077863/188480125-0c5fb8bd-c80d-4419-8ff9-bd00db1f92ef.png)

### Expected behavior

the edge goes directly from the single node to the combo

### Platform

- OS: macOS
- Browser: chrome
- Version: @antv/g6 4.7.0

**Comment by Yanyan-Wang** [comment]
fixed by 4.7.2
