### ISSUE TITLE
g6自定义节点，数据只有一条时，节点显示过大

### ISSUE THREAD

**Issue by mrcluo** [antvis/G6#3915]
### 问题描述

g6自定义节点，数据较多时展示正常，数据只有一条时，节点宽度和canvas宽度一样大

### 重现链接

无

### 重现步骤

g6自定义节点，数据较多时展示正常
数据只有一条时，节点宽度和canvas宽度一样大

### 预期行为

数据只有一条时，节点宽度不要自适应，按照代码里设置的大小显示

### 平台

- 操作系统: Windows
- 网页浏览器: Google Chrome
- G6 版本: 4.7.0

### 屏幕截图或视频（可选）

**正常状态**
[
![image](https://user-images.githubusercontent.com/40492120/188572244-7dc9dd14-9c44-491d-844e-83efaac241f7.png)
](url)

**只有一条数据时显示**
[
![image](https://user-images.githubusercontent.com/40492120/188572338-d27d6158-f12c-47e9-ac3b-d84099a22320.png)
](url)

**核心代码**

[
![image](https://user-images.githubusercontent.com/40492120/188572448-28f67a97-86bf-4bc9-913a-6edb6fe70559.png)
](url)

### 补充说明（可选）

请大佬解答，官网api翻了2小时， 没有翻到对应解决方法

**Comment by mrcluo** [comment]
自适应画布
fitView
类型：Boolean；默认：'false'。图是否自适应画布。

应用：
new G6.Graph({
fitView: this.dataObj.nodes.length > 1
})

**Comment by caozhongran** [comment]
直接调整比例就好了

```
        fitView: true, // 启用视图自适应
        fitCenter: true, // 启用视图居中
        minZoom: 0.5, // 最小缩放比例
        maxZoom: 1.4, // 最大缩放比例
```
