### ISSUE TITLE
自定义dom节点报错，按照官网API例子写的

### ISSUE THREAD

**Issue by atuosizhanshen** [antvis/G6#3916]
### Describe the bug

报错信息如下
TypeError: ShapeBase[shapeType] is not a constructor
    at Container.addShape (container.js?330d:203:1)

我是这么注册使用
 G6.registerNode(
    'dom-node',
    {
      draw: (cfg, group) => {
        return group.addShape('dom', {
...

### Your Example Website or App

null

### Steps to Reproduce the Bug or Issue

页面直接加载

### Expected behavior

页面加载时

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
实例化图的时候，是不是没配置 renderer: 'svg'？

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。

**Comment by bendajun** [comment]
https://antv-g6.gitee.io/zh/docs/manual/middle/elements/nodes/custom-node#5-%E4%BD%BF%E7%94%A8-dom-%E8%87%AA%E5%AE%9A%E4%B9%89%E8%8A%82%E7%82%B9
官网的例子copy下来完全跑不起来，就是报上面这个错，其他地方又看不到例子，百度谷歌更是搜不到类似报错原因，直接劝退啊。
官网中的edges: [(source: 'node1'), (target: 'node2')]是上个什么东西...
