### ISSUE TITLE
使用g6-react-node,ts中报错

### ISSUE THREAD

**Issue by zhouxiny1** [antvis/G6#3919]
### 问题描述

在ts文件中使用g6-react-node会报错，然后运行项目也会报错![image](https://user-images.githubusercontent.com/111745349/188785786-3c4ce400-a11d-44bf-9040-3bfb182ab891.png)
![image](https://user-images.githubusercontent.com/111745349/188785883-3e1d0186-2a05-4d14-b077-e604a8e01cde.png)

### 重现链接

暂无

### 重现步骤

暂无

### 预期行为

能正常运行

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by wanghui94** [comment]
https://github.com/antvis/G6/pull/3790#issue-1303748890 这个中已修复，好像是没有发布新版本

**Comment by Yanyan-Wang** [comment]
> [#3790 (comment)](https://github.com/antvis/G6/pull/3790#issue-1303748890) 这个中已修复，好像是没有发布新版本

这个 pr 中没有看到相关的修改

我这边会尽快修改一下

**Comment by wanghui94** [comment]
> > [#3790 (comment)](https://github.com/antvis/G6/pull/3790#issue-1303748890) 这个中已修复，好像是没有发布新版本
> 
> 这个 pr 中没有看到相关的修改
> 
> 我这边会尽快修改一下

缺的就是 children 这个属性，难道不是这个？

<img width="865" alt="image" src="https://user-images.githubusercontent.com/37385554/200733746-3564e93e-5732-4816-b2d9-9700edca3b66.png">

**Comment by dapangxue** [comment]
> 

hello，请问这个问题解决了吗？我今天刚试了下，v1.4.5 版本也发现有这个问题，props 里面没有定义 children 属性。

**Comment by Aarebecca** [comment]
当前版本的 `g6-react-node` 已不再维护，后续我们会发布 `@antv/g6-extension-react`
