### ISSUE TITLE
TreeGraph是否支持任意画线

### ISSUE THREAD

**Issue by ChrisLiu01** [antvis/G6#3920]
### 问题描述

业务背景：
使用TreeGraph组织节点关系，并且允许用户来交互式地来创建一棵树，有以下特别的需求
1. 允许用户创建一个任意边，就比如现在有一颗树结构是这样的
```
     a
  /      \
b         c
| 
d 
```
上面是一个标准的树结构，但是现在允许用户添加一个从c指向d的虚边（使用虚线表示），表示c下面有一颗和d一样结构的子树（由于d可能比较复杂，这样做是为了简化配置），因此想看在TreeGraph下，能否自己再根据节点位置添加新的虚边，或者允许自己来添加一个Path到canvas上也行
2. 允许创建空的combo，看了下demo中的例子，combo是必须要指定其中的节点id的，现在是问题是在创建的时候，用户先创建出一个combo（不是节点，业务上同一个combo下的节点将会默认同一类属性），然后再创建、拖拽节点到其中以建立这种包含关系。这种需求下能允许自己来画一个空的框吗

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
1. TreeGraph 中的节点有且稚嫩更有一个父节点，如果存在回溯边，就不是 Tree 的数据结构。你可以用 Graph + dagre 布局

2. 可以创建空 combo。但 TreeGraph 不支持 combo

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
