### ISSUE TITLE
使用自定义节点时，自定义节点坐标错位

### ISSUE THREAD

**Issue by PmcFizz** [antvis/G6#3922]
### 问题描述

在一个g6图上，有二种节点，一种rect，一种基于rect的自定义节点。

想让自定义节点的宽度 等于 rect节点的宽度总和。
大致是这样的效果

![image](https://user-images.githubusercontent.com/13403284/188842798-86681dd8-0140-4f5c-aee5-b26720713364.png)

### 重现链接

https://codesandbox.io/s/morning-sunset-3wxlx8?file=/index.html

### 重现步骤

如果上下两列的节点类型都是 rect。则效果显示正确。
但如果底部的节点类型为 自定义节点 nonelayNode 时，则底部的节点 坐标渲染不对。

传入底部节点的 坐标值都是一样的。但结果却不一样。

交替 注释 81行和82行 可以查看二种结果
 https://codesandbox.io/s/morning-sunset-3wxlx8?file=/index.html 

底部节点为自定义节点
![image](https://user-images.githubusercontent.com/13403284/188844010-1549d83c-665d-4ece-9a49-aa556d9f0cb0.png)

底部节点为rect
![image](https://user-images.githubusercontent.com/13403284/188844142-637849ec-e4b9-496a-8fed-c1a01651dfda.png)

### 预期行为

自定义节点的坐标渲染正确。

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.6.18]

**Comment by PmcFizz** [comment]
@Yanyan-Wang  你好，能否抽时间看一下我的这个问题。是自定义节点写的有问题吗？

**Comment by Yanyan-Wang** [comment]
自定义节点内部所有图形的 x y 各减去节点宽高的一半，让自定义节点自身坐标系的原点对齐到节点中心
如，对于 rect
x: 0 - width / 2,
y: 0 - height / 2
