### ISSUE TITLE
error on vedge update in afteradditem listener

### ISSUE THREAD

**Issue by ensconced** [antvis/G6#3925]
### Describe the bug

When `vedge.update()` is used from within an `afteradditem` handler, an error can result:

```
Cannot read properties of null (reading 'model')
```

### Your Example Website or App

https://stackblitz.com/edit/react-btcnz7-2u4yyr?file=index.js

### Steps to Reproduce the Bug or Issue

1. open the stackblitz example https://stackblitz.com/edit/react-btcnz7-2u4yyr?file=index.js
2. see error: `Cannot read properties of null (reading 'model')`

### Expected behavior

No error, vedge should be updated successfully.

### Platform

- OS: macOS
- Browser: Chrome
- Version: @antv/g6 4.7.1

**Comment by Yanyan-Wang** [comment]
it caused by `graph.changeData(graph.save())`

**Comment by ensconced** [comment]
Is this expected then? What is the problem with doing `graph.changeData(graph.save())`?

**Comment by Yanyan-Wang** [comment]
solved by 4.7.17
