### ISSUE TITLE
graph的container不够大，导致卡片显示被遮挡

### ISSUE THREAD

**Issue by zwb234** [antvis/G6#3930]
### 问题描述

graph的container自动计算的大小不够，导致图的部分内容被遮挡。
请问用何种方式可以控制这个container的宽高？
下边有复现链接，也有操作指引。

### 重现链接

https://codesandbox.io/s/graphde-containerbu-gou-da-sn62dl

### 重现步骤

1、进入页面
2、拉到最下边的卡片
3、鼠标hover名为“老五”或者“老六”的卡片
4、一共有六个删除，分别是’删除1‘、’删除2‘、...‘删除6’。
5、但是最下边的删除只能显示到‘删除4’，无法全部展示。
6、排查原因发现是container的大小限制了显示，请问用何种方式可以控制这个container的宽高？

### 预期行为

期望看到全部工具栏，但实际上部分被遮挡。

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）
![image](https://user-images.githubusercontent.com/57169366/189122662-dd725a40-6874-4b5a-a21b-e861a116419a.png)

**Comment by Yanyan-Wang** [comment]
我看你的代码好像是用的 X6？到这里去提吧 https://github.com/antvis/x6
