### ISSUE TITLE
legend plugin 里面 legendCanvas 未销毁

### ISSUE THREAD

**Issue by siadou** [antvis/G6#3931]
### Describe the bug

https://github.com/antvis/G6/blob/master/packages/plugin/src/legend/index.ts#L345
legend在render的时候，生成一个新的canvas对象，在后面的代码里未出现对该对象的销毁操作。

### Your Example Website or App

https://codesandbox.io/s/restless-bush-qmvn0g

### Steps to Reproduce the Bug or Issue

1 new一个包含一个legend plugin的Graph
2. 调用graph.clear() graph.destroy()
3. 浏览器查看事件监听器body上绑定的mousemove事件，来自未销毁的legend plugin
4. 如果重复new 和destroy，body上的mousemove绑定事件数量持续增加。

### Expected behavior

graph.destroy之后body上不应该还有未解绑来自event-controller的事件。

### Platform

OS: [Windows]
Browser: [Chrome]
Version: [@antv/g6@4.7.0]

**Comment by Yanyan-Wang** [comment]
v4.7.3 已修复
