### ISSUE TITLE
自定义节点中使用image shape 在缩放和拖拽的过程中 有时会出现Failed to execute 'drawImage' on 'CanvasRenderingContext2D'这个报错

### ISSUE THREAD

**Issue by fanjiachangRyan** [antvis/G6#3936]
### 问题描述

在registerNode中只是简单的返回了一个rect shape 。
然后再afterDraw中 对这个node填加了一些附加的shape 
其中节点中的头像是用image shape 实现，在treeGraph 的zoom和drag过程中偶尔会出现图片绘制失败的情况，
（Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state.）
原因大概了解,但是怎么处理呢？
最开始是在 registerNode的draw方法中一次性完成了节点的所有图形绘制，除了keyShape其他的都放在了afterDraw中，单结果还是会有这种情况发生。
绘制imageShape的时候通过创建new Image 然后imageShape的img 使用的是 Image对象
image对象的onerror是给另一张默认图片：

const image = new Image
image.onerror = () => {
   image.src = placeHolder_img
}

### 重现链接

none

### 重现步骤

在treeGraph展开或者收起的时候 拖拽视图 大概率会出现图片绘制失败（Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state.）这个报错

### 预期行为

在收起或者展开的过程中拖拽不会影响到节点的绘制

### 平台

- 操作系统: macOS, Windows
- 网页浏览器:Google Chrome
- G6 版本: 4.6.4

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/52392864/189903672-6e8f00be-16ee-4bfb-adcf-d1272820b16b.png)

### 补充说明（可选）

期待回复

**Comment by Yanyan-Wang** [comment]
试试 img 使用 base64 是否有以上问题？

**Comment by fanjiachangRyan** [comment]
用的是别人的接口,返回的是jpg|png的图片，自己转换的话图片太多了，我试一下跟对接方沟通一下， 除了这种方式还有其他方法吗？
