### ISSUE TITLE
折叠收缩位置不正确

### ISSUE THREAD

**Issue by Tyh2001** [antvis/G6#3939]
### 问题描述

使用图表点击会折叠收缩，但是一旦一方数量过多的情况下，另一方并不会收缩到预期的位置上，如下图：

![c3f2868c2a28a73eb99aa5181ff30d3](https://user-images.githubusercontent.com/73180970/190306280-80d49f02-253e-40a6-b834-2d1b62705c49.jpg)

初始状态是上图，当点击右侧的菜单时候，下面的会进行收缩，但是收缩之后的位置会和左侧重合

![40248ab316d0de092c6ade7414c98d4](https://user-images.githubusercontent.com/73180970/190306416-6854527b-03f3-47d1-b726-ee3c5f6d9bb6.jpg)

红色代表预期应该折叠的位置，绿色是实际上到达的位置

### 重现链接

https://stackblitz.com/

### 重现步骤

见问题描述

### 预期行为

见问题描述

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
应该是这个边的走线让它看起来重叠了，节点位置考虑紧凑，应该是对的。
折线可以为 layout 配置 controlPoints: true，布局将规划 polyline 走线。或者，可以自定义折线的路径控制点，使之不要从节点的两侧出来，而是从一个节点的下方垂直向下走一段后再往两侧走，自定义折线例子：https://g6.antv.vision/zh/examples/item/customEdge#customPolyline

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
