### ISSUE TITLE
image节点 图片跨域

### ISSUE THREAD

**Issue by TThz-hz** [antvis/G6#3944]
### 问题描述

https://github.com/antvis/G/issues/40
https://github.com/antvis/G/pull/639
服务器图片未配置图片允许跨域时  ``` image.crossOrigin = "Anonymous" ``` 导致图片加载失败

### 重现链接

https://codesandbox.io/s/restless-fire-leg5qu?file=/index.js

### 重现步骤

见codesandbox

### 预期行为

希望可以配置 ``` image.crossOrigin = "Anonymous" ``` 是否执行； 以及 ```  image.crossOrigin ``` 的值

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/56644784/190436932-ec265908-1b2e-41a8-95a1-711c4de36343.png)

**Comment by gongpingwa00** [comment]
我也遇到这个问题,请问后来怎么解决的呢

**Comment by TThz-hz** [comment]
> 我也遇到过这个问题，请问以后怎么解决的呢
浏览器默认会缓存加载过的图片。使用js加载image 浏览器会直接读取缓存的图片, 而缓存中的图片没有设置 ``` image.crossOrigin = "Anonymous" ```，所以浏览器直接就拒绝了
首先服务器要允许图片跨域. 
1. 图片标签增加crossOrigin属性 ``` <img crossOrigin="anonymous"/> ```. 使用js加载image 设置 ``` image.crossOrigin = "Anonymous" ```
2. 使用js加载image时 在图片url后拼接随机字符串 ``` image.src = `${src}?t=${Date.now()}` ```, 阻止浏览器使用缓存的图片
