### ISSUE TITLE
toolbar的撤销重做点击没反应

### ISSUE THREAD

**Issue by zhouxiny1** [antvis/G6#3945]
### 问题描述

使用g6-react-node自定义的节点， layout: {type: 'dagre'},增加toolbar工具 撤销重做按钮不生效，放大缩小等功能正常

### 重现链接

暂无

### 重现步骤

无

### 预期行为

按钮功能正常

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
enabledStack 有打开吗，如

https://g6.antv.vision/zh/examples/tool/toolbar#toolbar  line85

**Comment by zhouxiny1** [comment]
![image](https://user-images.githubusercontent.com/111745349/190945213-e1dff5d9-eb4a-4fdc-a24a-7314db42e8e7.png)
这个值设为true 放大缩小之后撤销重做按钮还是灰色还不可用，设置为false颜色不是灰色但是还是同样点击也不可用

**Comment by Yanyan-Wang** [comment]
> ![image](https://user-images.githubusercontent.com/111745349/190945213-e1dff5d9-eb4a-4fdc-a24a-7314db42e8e7.png) 这个值设为true 放大缩小之后撤销重做按钮还是灰色还不可用，设置为false颜色不是灰色但是还是同样点击也不可用

打开之后置灰应该是因为当前图上没有东西可以撤销重做吧？做一些操作，撤销重做栈里有内容，就不会置灰了

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
