### ISSUE TITLE
\g6\packages\site build failed

### ISSUE THREAD

**Issue by loveJasmine** [antvis/G6#3949]
### Describe the bug

**PS C:\react-graph\g6\packages> npm start**

 _ERROR #98124  WEBPACK

Generating development SSR bundle failed

Can't resolve 'react-dom' in 'C:\react-graph\g6\node_modules\rc-motion\node_modules\rc-util\es\Dom'

If you're trying to use a package make sure that 'react-dom' is installed. If you're trying to use a local file make sure that the path is correct.

File: ..\..\node_modules\rc-motion\node_modules\rc-util\es\Dom\findDOMNode.js_

### Your Example Website or App

n/a

### Steps to Reproduce the Bug or Issue

please check and update

### Expected behavior

please check and update

### Platform

windows 10

**Comment by Yanyan-Wang** [comment]
yarn install
gatsby build
gatsby serve

**Comment by Yanyan-Wang** [comment]
we have migrated the website to dumi, the site could be start more easily

npm install
npm start

**Comment by loveJasmine** [comment]
@Yanyan-Wang 
it doesn't work!
