### ISSUE TITLE
Combo Collapse alignment issue

### ISSUE THREAD

**Issue by l4k5hm4n** [antvis/G6#3952]
### 问题描述

When implementing **collapse-expand-combo** mode in **dagre** layout the children of a combo when collapsed are aligning to the top always when it's supposed to maintain the **TB** rank direction. The hierarchy & layout of the **DAG** is getting misplaced for collapsed combos

### DAG layout without collapse - 
![Screen Shot 2022-09-21 at 11 03 57 AM](https://user-images.githubusercontent.com/38096064/191422366-a475b5af-2871-40f5-9f94-700a306dfe66.png)

### DAG layout when combo is collapsed - 
![Screen Shot 2022-09-21 at 11 04 07 AM](https://user-images.githubusercontent.com/38096064/191422380-e99e1d8e-1b84-4ea7-be5b-210f8a9fafaf.png)
**Expected behaviour:** nodes 2.1.1, 2.1.2 & 2.1.3 should be displayed to the bottom of combo node when collapsed.

### 重现链接

shared graph config in instructions

### 重现步骤

1. create a graph with **dagre** layout
2. create a combo with children nodes 
3. collapse the combo of children nodes to observe the issue

### 预期行为

All nodes in **dagre** layout should maintain the same rank direction even after a combo collapse/expand

### 平台

- macOS
- Google Chrome
- G6 4.7.4

### Graph config: 

    g6 = (data: GraphData | TreeGraphData | undefined) => {
        // For graph instantiation, at least the mounting container, width and height need to be set for the graph
        const graph = new G6.Graph({
            container: 'dag-ctr',
            width: 1600,
            height: 1000,
            groupByTypes: false,
            layout: {
                type: 'dagre',
                nodesepFunc: (d: any) => {
                    console.log(d);
                    // if (d.id === '3') {
                    //     return 50;
                    // }
                    return 60;
                },
                ranksep: 60,
                controlPoints: true,
                rankdir: 'TB',
                sortByCombo: true,
            },
            defaultNode: {
                type: 'customNode',
            },
            defaultEdge: {
                type: 'line',
                style: {
                    radius: 20,
                    offset: 45,
                    endArrow: true,
                    lineWidth: 2,
                    stroke: '#C2C8D5',
                },
            },
            nodeStateStyles: {
                selected: {
                    stroke: '#d9d9d9',
                    fill: '#5394ef',
                },
            },
            defaultCombo: {
                type: 'rect',
                style: {
                    fill: '#bae637',
                    stroke: '#eaff8f',
                    lineWidth: 1,
                },
            },
            modes: {
                default: ['drag-canvas', 'zoom-canvas', 'collapse-expand-combo'],
            },
            // fitView: true,
        });
        // Data loading and rendering of Graphs
        graph.data(data);
        graph.render();
    };

### Custom node

        G6.registerNode(
            'customNode',
            {
                drawShape(cfg, group) {
                    const rect = group.addShape('rect', {
                        attrs: {
                            x: -75,
                            y: -25,
                            width: 150,
                            height: 50,
                            radius: 10,
                            stroke: '#5B8FF9',
                            fill: '#C6E5FF',
                            lineWidth: 3,
                        },
                        name: 'rect-shape',
                    });
                    if (cfg.name) {
                        group.addShape('text', {
                            attrs: {
                                text: cfg.name,
                                x: 0,
                                y: 0,
                                fill: '#00287E',
                                fontSize: 14,
                                textAlign: 'center',
                                textBaseline: 'middle',
                                fontWeight: 'bold',
                            },
                            name: 'text-shape',
                        });
                    }
                    return rect;
                },
            },
            'single-node',
        );

### Data

    data = {
        nodes: [
            {
                id: '1',
                dataType: 'alps',
                name: 'start',
            },
            {
                id: '2',
                dataType: 'alps',
                name: '1',
            },
            {
                id: '3',
                dataType: 'alps',
                name: '2',
            },
            {
                id: '4',
                dataType: 'sql',
                name: '3',
            },
            {
                id: '5',
                dataType: 'sql',
                name: '1.1',
            },
            {
                id: '6',
                dataType: 'feature_etl',
                name: '1.2',
            },
            {
                id: '7',
                dataType: 'feature_etl',
                name: '1.3',
            },
            {
                id: '8',
                dataType: 'feature_extractor',
                name: '2.1',
                comboId: 'combo1',
            },
            {
                id: '9',
                dataType: 'feature_extractor',
                name: '2.2',
                comboId: 'combo1',
            },
            {
                id: '10',
                dataType: 'feature_extractor',
                name: '2.1.1',
            },
            {
                id: '11',
                dataType: 'feature_extractor',
                name: '2.1.2',
            },
            {
                id: '12',
                dataType: 'feature_extractor',
                name: '2.1.3',
            },
        ],
        edges: [
            {
                source: '1',
                target: '2',
            },
            {
                source: '1',
                target: '3',
            },
            {
                source: '1',
                target: '4',
            },
            {
                source: '2',
                target: '5',
            },
            {
                source: '2',
                target: '6',
            },
            {
                source: '2',
                target: '7',
            },
            {
                source: '3',
                target: '8',
            },
            {
                source: '3',
                target: '9',
            },
            {
                source: '8',
                target: '10',
            },
            {
                source: '8',
                target: '11',
            },
            {
                source: '8',
                target: '12',
            },
        ],
        combos: [{ id: 'combo1', label: 'Combo'}],
    };

**Comment by Yanyan-Wang** [comment]
solved by v4.7.15
