### ISSUE TITLE
changedata后全局动画闪烁问题

### ISSUE THREAD

**Issue by dingyang9642** [antvis/G6#3953]
### 问题描述

背景：changedata利用全局动画animate:true开启动画
问题描述：见视频中鼠标点击处（点击一个node之后，会首先执行一次changeData后最新数据的渲染，然后再进行动画的执行，此时就会有一个比较明显的闪烁问题）

### 重现链接

下面视频

### 重现步骤

见视频点击处，大约视频4s后的位置

### 预期行为

changedata后不要先执行绘制最新数据，应该是直接开启动画

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

https://user-images.githubusercontent.com/16871766/191657640-508d468a-edbc-4dc7-a2e9-42d81edc340a.mp4

**Comment by simplejason** [comment]
我遇到过类似的情况，之后采用 getNodes/getEdges 手动执行 item.update({}) 方法屏蔽。可能是 changeData 会重新触发重绘操作，导致视图元素刷新，update 方法应该仅触发 afterUpdate 生命周期

**Comment by dingyang9642** [comment]
@Yanyan-Wang

**Comment by Yanyan-Wang** [comment]
请提供一下在线复现的 demo？
