### ISSUE TITLE
如何实现树图嵌套层级的布局

### ISSUE THREAD

**Issue by 799531161** [antvis/G6#3954]
### 问题描述

如何实现树图嵌套层级的布局
如下图所示

### 重现链接

//

### 重现步骤

//

### 预期行为

  //

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![企业微信截图_1663827884989](https://user-images.githubusercontent.com/50687675/191705209-8f63b505-6c9d-4af8-b207-1a91bd3d1add.png)

**Comment by Yanyan-Wang** [comment]
可以用 Graph 然后自定义布局

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
