### ISSUE TITLE
Gforce图2200多个图元，启用activate-relations感觉非常卡顿

### ISSUE THREAD

**Issue by huabulai** [antvis/G6#3955]
### 问题描述

Gforce图，500个节点，1263条边，每个节点有一个文本label,2200多个图元，启用activate-relations后，鼠标移动到一个节点，有关联的节点要显示特定颜色，其他没关联的节点要变暗，改写了原本activate-relations交互的样式，感觉非常卡顿。并且使用了tooltip显示label.

### 重现链接

暂时无法上传源码

### 重现步骤

1 鼠标移动到相关节点
2 根据activate-relations改变相应节点的颜色
3 颜色高亮切换很卡顿
4 我看过官网的5000图元也很流畅，但是没使用到activate-relations。我于是去掉了activate-relations，当然拖动和缩放画布也顺畅很多。

### 预期行为

能否保证在这个数量级情况下，启用activate-relations交互，高亮切换顺畅，拖动和缩放画布顺畅

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome,]
- G6 版本: [4.7.4 ... ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/46225303/191906577-e605ac12-8a9d-47f4-a4a0-54e65f80f6cc.png)
![image](https://user-images.githubusercontent.com/46225303/191907221-d8645a6e-c5ac-4cae-8beb-1a565525ca0d.png)
![image](https://user-images.githubusercontent.com/46225303/191907585-fb7d1906-9a1a-4d22-8db8-b7ff06051475.png)

**Comment by Yanyan-Wang** [comment]
activate-relations 会高亮相关元素，置灰其它元素，相当于所有元素都在更新，性能消耗比较大。这种情况下，可以自定义交互，只高亮相关的元素，其他元素不变 ，这样消耗比较小

**Comment by huabulai** [comment]
> activate-relations 会高亮相关元素，置灰其它元素，相当于所有元素都在更新，性能消耗比较大。这种情况下，可以自定义交互，只高亮相关的元素，其他元素不变 ，这样消耗比较小

为啥同样的数量级，同样的交互，百度echart性能非常流畅，我已经改用echarts了

**Comment by feikerwu** [comment]
> activate-relations 会高亮相关元素，置灰其它元素，相当于所有元素都在更新，性能消耗比较大。这种情况下，可以自定义交互，只高亮相关的元素，其他元素不变 ，这样消耗比较小

这个内置优化的计划吗，翻了下 activate-relations 会对每个图元做 setState，进去打点发现，每次setState执行平均要1ms左右，而且是串行的，耗时为 图元数量 * 1ms，交互看着比较卡。这里setState能不能做批量的

**Comment by Yanyan-Wang** [comment]
> > activate-relations 会高亮相关元素，置灰其它元素，相当于所有元素都在更新，性能消耗比较大。这种情况下，可以自定义交互，只高亮相关的元素，其他元素不变 ，这样消耗比较小
> 
> 这个有内置优化的计划吗，翻了下 activate-relations 会对每个图元做 setState，进去打点发现，每次setState执行平均要1ms左右，而且是串行的，耗时为 图元数量 * 1ms，交互看着比较卡。这里setState能不能做批量的

非常好的建议，我尝试一下。

**Comment by Yanyan-Wang** [comment]
v4.7.11 active-relations 性能提升显著，官网 demo (https://g6.antv.vision/zh/examples/interaction/highlight#activateRelations) 从 2fps 提升至 60 fps，欢迎试用。

**Comment by Yanyan-Wang** [comment]
又优化了一版本，7200 节点，大约 2w 图元，可达到 50fps 以上（测试电脑 M1 mac）。v4.7.12 预计明后天发布，这一版优化修改详见：

https://github.com/antvis/G6/pull/4036/commits/9249eea00b300c5fa73bbbac38d7d661ec51e9dd

@feikerwu @huabulai
