### ISSUE TITLE
当使用自定义节点时阴影属性无法生效 style.shadowColor

### ISSUE THREAD

**Issue by PmcFizz** [antvis/G6#3958]
### 问题描述

定义了一个自定义节点，想要为该节点设置阴影，但无论在registerNode 中设置还是在nodes中，还是在defaultNode中设置阴影，都无法生效。如果不是自定义节点，则可以生效。

### 重现链接

https://codesandbox.io/s/frosty-shape-idvs3b?file=/index.html

### 重现步骤

1：进入页面，默认使用的自定义渲染图，阴影无法出现
2：注释第44行，修改节点类型为内置节点矩形
3：阴影出现

### 预期行为

期望在使用自定义节点时，阴影也能正常出现。

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.6.17]

**Comment by PmcFizz** [comment]
@yuanchuan 兄弟，有时间看一下我的这个问题，查了很久文档。没找到原因。

**Comment by PmcFizz** [comment]
@yuanchuan

**Comment by yuanchuan** [comment]
@PmcFizz Sorry 我还是在 2018 年用过 G6，你们就不要总是 @ 我了，我没有维护过这项目

**Comment by PmcFizz** [comment]
> @PmcFizz Sorry 我还是在 2018 年用过 G6，你们就不要总是 @ 我了，我没有维护过这项目

抱歉啊

**Comment by Yanyan-Wang** [comment]
group.addShape 的时候，阴影等属性都是写在 attrs 里面的，不要包一层 style
