### ISSUE TITLE
调用Graph.expandCombo(item) 展开combo与collapse-expand-combo交互效果不同

### ISSUE THREAD

**Issue by podf** [antvis/G6#3961]
### Describe the bug

调用Graph.expandCombo(item)会造成combo及其子元素同时展示，需要挪动其中一个元素后，combo才能渲染成功

### Your Example Website or App

https://stackoverflow.com/help/mcve。

### Steps to Reproduce the Bug or Issue

1.  数据中配置combo折叠
2. 通过G6.Menu配置邮件菜单-展开combo
3. 点击”展开combo“菜单， 调用Graph.expandCombo(item) 
4

### Expected behavior

与collapse-expand-combo交互效果

### Screenshots or Videos

<img width="594" alt="image" src="https://user-images.githubusercontent.com/31005064/192482363-ff39bbb6-401e-49f9-9d4b-c427473b6b79.png">

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
换成 graph.collapseExpandCombo 试试。不行的话提供一个在线复现的 demo 吧

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
