### ISSUE TITLE
紧凑树，如何折叠部分子节点

### ISSUE THREAD

**Issue by donghuizhou** [antvis/G6#3962]
### 问题描述

![image](https://user-images.githubusercontent.com/31002949/192508311-d421aca2-c6d0-49c4-b3b9-640f7559d09a.png)
如上图所示，紧凑树布局，想要点击【all】左边的按钮，收起/展开左边的节点，点击【all】右边的按钮，收起/展开右边的节点

### 重现链接

none

### 重现步骤

none

### 预期行为

如上所述

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by donghuizhou** [comment]
父节点的 `collapsed` 属性的改变，控制所有子节点的折叠/展开，所以本人采用如下解决方案：

点击左右两侧按钮时，遍历某个方向所有的节点，通过 `graph.showItem()` 和 `graph.hideItem()` 控制节点显示隐藏

_若有其他方式，欢迎交流_

**Comment by Yanyan-Wang** [comment]
楼上方案可行，也可以通过控制数据达到目的

**Comment by xicunyang** [comment]
> 父节点的 `collapsed` 属性的改变，控制所有子节点的折叠/展开，所以本人采用如下解决方案：
> 
> 点击左右两侧按钮时，遍历某个方向所有的节点，通过 `graph.showItem()` 和 `graph.hideItem()` 控制节点显示隐藏
> 
> _若有其他方式，欢迎交流_

来交流一下~  这种方式实现的话，父节点的位置并不会随着子节点的显示或者隐藏而变化，比如原来父节点距离比较远，是因为子节点比较多撑开的，这样当子节点隐藏了，此时父节点之间的间距还是如此，会比较奇怪。

**Comment by MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM** [comment]
> 楼上方案可行，也可以通过控制数据达到目的

如何通过控制数据实现，能给个思路嘛

**Comment by whathave** [comment]
这个实现了吗，求思路
