### ISSUE TITLE
====================建了个G6交流群，欢迎大家进群交流===============

### ISSUE THREAD

**Issue by donghuizhou** [antvis/G6#3965]
### 问题描述

![a4feb70aef20b3dd5037cd649d6136f](https://user-images.githubusercontent.com/31002949/192683491-8a86e83c-85ee-4df4-a7fb-e4ca27345342.jpg)

### 重现链接

none

### 重现步骤

无

### 预期行为

欢迎大家进群交流

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by siwenyu** [comment]
求拉
