### ISSUE TITLE
image 節點重複 update 造成 image 變成空白

### ISSUE THREAD

**Issue by Junlol** [antvis/G6#3966]
### 问题描述

初始一個 type=image 節點，透過 updateItem 更新 type=circle 再更新回 type=image，這部份表現正常

但如果連續透過 updateItem 更新 type=image，則 image 節點會變成空白

### 重现链接

https://codesandbox.io/s/eloquent-satoshi-2t1in9?file=/src/index.js

### 重现步骤

click change to image button twice.

### 预期行为

應該要保持 image，而不是變成一片空白

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome,]
- G6 版本: [4.7.4]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/19281094/192682967-d9688ed3-60c1-4a3a-b35e-2dbedd25fd34.png)
![image](https://user-images.githubusercontent.com/19281094/192682998-fc3c0100-3e93-4e05-99f0-076b2ef1aa52.png)

**Comment by Junlol** [comment]
看了一下 code，在 

https://github.com/antvis/G6/blob/master/packages/core/src/element/shapeBase.ts#L81

因為 updateType?.includes('bbox') 所以回傳 {}
造成 image node update 取得 mergeStyle 時是 {}

https://github.com/antvis/G6/blob/master/packages/element/src/nodes/image.ts#L141

以至於 image node update 後變空白

**Comment by Yanyan-Wang** [comment]
发现好像是 data 里面那个节点的 img 图片的问题，也许是太大了加载很慢？换成其他的就不会有这个问题了，比如 
https://gw.alipayobjects.com/mdn/rms_f8c6a0/afts/img/A*j-DwT4geW5kAAAAAAAAAAAAAARQnAQ
或者你写在 index.js 里面的那个 img https://miro.medium.com/max/1400/0*eSgp_38XKWxTTsg5

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
