### ISSUE TITLE
复合布局 ComboCombined，在所有的node都有combo时，combo实际展示的时候和布局计算的位置不同

### ISSUE THREAD

**Issue by hualinzhang** [antvis/G6#3968]
### 问题描述

复合布局 ComboCombined，在所有的node都有combo时，combo实际展示的时候和布局计算的位置不同

### 重现链接

https://g6.antv.vision/zh/docs/api/graphLayout/comboCombined

### 重现步骤

![企业微信截图_16643520263372](https://user-images.githubusercontent.com/38073079/192725040-e54aa1a4-172c-4da6-8028-841e6c7cf435.png)
![企业微信截图_16643521511674](https://user-images.githubusercontent.com/38073079/192725107-7a8996e3-f0f1-4772-9ff5-0eb7b5862d47.png)

### 预期行为

期望不管有没有单独的node，都希望布局之后的combo的位置是outerLayout布局计算的位置

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
请给一下在线复现的 demo

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
