### ISSUE TITLE
关于mapper变更的问题

### ISSUE THREAD

**Issue by hihl** [antvis/g6#397]
如果graph中使用mapper，mapper将是不可撤销的，如一开始设置graph.node({ label: model => model.id }); 一定操作后想要移除这个mapper，目前没有方法也没有办法做到，因为mapper会修改源数据，源数据已经被破坏了。
如下：
```js
var data = { nodes: [{ id: 'node1', x: 50, y: 50 }]};
...
graph = new G6.Graph(...);
graph.node({ label: model => model.id });
graph.read(data);
graph.destroy();
graph = new G6.Graph(...);
graph.read(data);  //  data has been changed
```

数据不是immutable的，即使destroy了，也会保留之前的mapper结果

我觉得内部实现的时候，是否应该保留一份originData?

**Comment by TomHuangCN** [comment]
由于 G6 有数据导出导入的需求。为了回显正确，没有做数据隔离层。如果原数据字段跟 G6 的保留字段有重复，建议传入 G6 是 clone 的数据。
