### ISSUE TITLE
关于G6节点/combo布局的两个需求

### ISSUE THREAD

**Issue by enigmacx** [antvis/G6#3971]
### 问题描述

目前G6是否支持如下两个潜在需求？
1）G6是否支持combo固定位置，combo内的节点在combo展开时按照某种预设算法在combo内部自动布局？
2）G6是否支持部分节点/combo使用预设位置，没有指定位置的节点/combo按照算法自动布局？

### 重现链接

N/A

### 重现步骤

N/A

### 预期行为

N/A

### 平台

N/A

**Comment by Yanyan-Wang** [comment]
自定义布局应该可以做到
