### ISSUE TITLE
边动画，箭头会受影响

### ISSUE THREAD

**Issue by yanliang-code** [antvis/G6#3973]
### 问题描述

鼠标移入节点，边动画开始后，由于箭头外层也有描边导致也有动画

### 重现链接

https://codesandbox.io/s/green-sun-vwv5fm?file=/index.js

### 重现步骤

鼠标移入节点，
放大画布
观察边箭头会存在波动效果

### 预期行为

边箭头会存在波动效果，希望边动画不影响边箭头

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
可以把箭头的透明度设置为 0
strokeOpacity: 0

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
