### ISSUE TITLE
数据更新之后，changeData报错， 的

### ISSUE THREAD

**Issue by Jackelson** [antvis/G6#3975]
### 问题描述

1.页面渲染完成之后，使用changeData对数据进行更改。在控制台报了一个source未定义的错误。
2.使用changeData刷新不成功之后。我尝试在warch里边观测渲染数据的变化，变化之后使用refrash进行刷新，没有效果。

### 重现链接

git@github.com:Jackelson/admin-app.git

### 重现步骤

直接将项目运行即可

### 预期行为

数据切换之后能够正常显示页面

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

<img width="548" alt="image" src="https://user-images.githubusercontent.com/95007281/193549312-84d29574-089c-487f-8789-56ed2b7edad9.png">

### 补充说明（可选）

复现链接是个github仓库地址，可对代码进行查看

**Comment by Jackelson** [comment]
找到原因了，经过对官网代码的运行和changeData打印。发现我项目中chanData和官网上边的changeData不一样。自我解决的原因如下：
由于我这个项目是使用vue3搭建的
在vue3中，this并不是直接指向实例对象，中间加了一层代理，我刚开始的时候把graph实例对象挂到vue实例上了（具体为什么指向的changeData不同，还在查找原因）。
知道了是这个问题，我就把graph放在了window上就解决了。
我在vue2也试了下，也可以正常运行。

**Comment by Yanyan-Wang** [comment]
看报错比较像是数据里面存在重复的 id，或者 id 非法（如非字符串、为空等）。G6 中节点和边的 id 要求是唯一的 string

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。

**Comment by lq2016** [comment]
graph.read()可以解决

**Comment by ifihavewings** [comment]
> ### 问题描述
> 
> 1.页面渲染完成之后，使用changeData对数据进行更改。在控制台报了一个source未定义的错误。
> 2.使用changeData刷新不成功之后。我尝试在warch里边观测渲染数据的变化，变化之后使用refrash进行刷新，没有效果。
> 
> ### 重现链接
> 
> git@github.com:Jackelson/admin-app.git
> 
> ### 重现步骤
> 
> 直接将项目运行即可
> 
> ### 预期行为
> 
> 数据切换之后能够正常显示页面
> 
> ### 平台
> 
> - 操作系统: [macOS, Windows, Linux, React Native ...]
> - 网页浏览器: [Google Chrome, Safari, Firefox]
> - G6 版本: [4.5.1 ... ]
> 
> 
> ### 屏幕截图或视频（可选）
> 
> <img width="548" alt="image" src="https://user-images.githubusercontent.com/95007281/193549312-84d29574-089c-487f-8789-56ed2b7edad9.png">
> 
> 
> ### 补充说明（可选）
> 
> 复现链接是个github仓库地址，可对代码进行查看

大佬我我没看明白那，我也是vue3， 用 graph.value.changeData, graph 是 vue3 ref创建的。报错的是 reading model，其他的一样。
