### ISSUE TITLE
自定义边过程遇到的问题

### ISSUE THREAD

**Issue by yanliang-code** [antvis/G6#3976]
### 问题描述

通过继承quadratic，在afterDraw中绘制其背景path，若发现背景path必须带箭头，若将endArrow置为false，则边就不在绘制背景中间位置

### 重现链接

https://codesandbox.io/s/cocky-night-4pz8c1?file=/index.js

### 重现步骤

打开重现链接
对第55行代码进行注释、取消注释
观察边在边背景中的位置

### 预期行为

希望endArrow置为false，边也在边背景的中间

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/60208330/193604270-cd27204a-bafe-4ed6-b8e8-406423e3772d.png)
![image](https://user-images.githubusercontent.com/60208330/193604310-721b2402-7dca-49fd-a402-4971b561967e.png)

### 补充说明（可选）

自身尝试好像是因为箭头有偏移导致的

**Comment by Yanyan-Wang** [comment]
原路径因为箭头的存在，路径有一定变化，若背景复制了原路径，又取消了箭头，导致路径与原路径不一致。可以这样处理，给背景的箭头设置为透明：
```
endArrow: {
            ...style.endArrow,
            opacity: 0
          }
```

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
