### ISSUE TITLE
边无法连接矩形节点的上下边

### ISSUE THREAD

**Issue by colaiven** [antvis/G6#3980]
### Describe the bug

![image](https://user-images.githubusercontent.com/46585176/194696036-8cc0c2c5-8b69-4237-8c78-6d917ee1d58c.png)
如图情况，此时个人觉得应该连接矩形的下边而不是左边，虽然设置linkCenter: true（使边连接节点的中心）可以解决此问题，但是这样不能正常显示边的箭头。我认为这是一个缺陷，俺建议设置linkCenter: true时，箭头能够自适应在节点的边上，不然设置linkCenter: true同时显示边的箭头没有什么意义。

### Your Example Website or App

如图所示

### Steps to Reproduce the Bug or Issue

See Describe

### Expected behavior

See Describe

### Platform

- OS: [all]
- Browser: [all]
- Version: [4.6.17]

**Comment by Yanyan-Wang** [comment]
linkCenter 为 true 的时候，箭头被节点挡住。endArrow 可以配置 d 来“退”出来一些，你截图中的 demo 应该有，可以参考一下。

如果不使用 linkCenter: true，可以配置节点的 anchorPoints 和边的 sourceAnchor / endAnchor 来制定连接的位置，参考 https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/anchorpoint
