### ISSUE TITLE
4.7.5版本中ER图例子存在：线条无法跟着内容一起滚动的bug

### ISSUE THREAD

**Issue by Max-EnjoyCode** [antvis/G6#3986]
### 问题描述

The ER diagram in version 4.3.2 is inconsistent with the ER diagram in the latest version. In the new version scrolling the content area, the lines cannot be scrolled together.

### 重现链接

https://g6.antv.vision/zh/examples/item/customNode#scrollNode

### 重现步骤

This is an example given by the official. It is obvious that the scrolling content area can be found, and the lines and arrows will not scroll with the content.

### 预期行为

I expect the ER diagram in the latest version to behave the same as the ER diagram in 4.3.2, but it seems to be buggy.

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.7.5 ]

**Comment by Yanyan-Wang** [comment]
https://g6.antv.antgroup.com/zh/examples/item/customNode#scrollNode
例子已修复，需要在滚动自定义交互里，更新节点滚动信息同时更新相关的边。G6 内部根据 graph.updateItem 传入的新的配置，决定是否自动更新相关边。只有涉及节点位置变更、大小变更的情况下，相关边会被更新。这样做的原因是在其他更新节点样式的情境下，避免更新边带来没必要的性能消耗。

但因为这里 demo 中更新的字段(startIndex, startX)都是完全自定义的，只在自定义节点、自定义交互等逻辑中被消费，G6 内部无法识别，所以需要手动更新一下。如 demo line175
