### ISSUE TITLE
4.7.5  G6.TreeGraph 中 plugins G6.Grid无效

### ISSUE THREAD

**Issue by podf** [antvis/G6#3987]
### Describe the bug

4.7.5  G6.TreeGraph 中 plugins G6.Grid无效

### Your Example Website or App

https://codesandbox.io/s/angry-brook-zusxwo?file=/index.js

### Steps to Reproduce the Bug or Issue

官网实例加入grid plugins

### Expected behavior

正常显示grid

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
审查一下元素是不是被盖住了， z-index 调整下

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
