### ISSUE TITLE
Graphics Group visibility documentation

### ISSUE THREAD

**Issue by eakl** [antvis/G6#3994]
### Describe the bug

According to the documentation, Graphics Group visibility is controlled by the `cfg` object [See here](https://g6.antv.vision/en/docs/api/Group#groupaddshapetype-cfgs).
Visibility doesn't appear in the Graphic Shape properties [see here](https://g6.antv.vision/en/docs/manual/middle/elements/shape/shape-and-properties#property).

However, Graphin implements visibility both in the `cfg` object AND in the `attrs` property [see here](https://github.com/antvis/Graphin/blob/master/packages/graphin/src/shape/graphin-circle.ts).

1. Are both visibility properties different? If yes, what are the difference? If no, why having 2 properties?
2. Documentation should reflect the existence AND the difference between the 2 properties

**Comment by Yanyan-Wang** [comment]
Hi @eakl , Both Graphics Group and Graphic Shape has configuration `visible`. e.g.
// adding a sub Graphic Group to a group
group.addGroup({
  visible: true, // or false
})
// adding a circle shape to a group
group.addShape('circle', {
  attrs: {...},
  visible: true, // or false
});


They are both controlled by the `cfg` but not `attrs`. I think Graphin has duplicated `visible` in `attrs` which will not take effect.
