### ISSUE TITLE
dagre布局节点位置调整

### ISSUE THREAD

**Issue by xiaojueji** [antvis/G6#3995]
### 问题描述

![image](https://user-images.githubusercontent.com/31124354/196331298-aecfa52d-84d5-4a69-b6f4-862236ec5815.png)
如上图的节点 我想节点往左一点 这个可以通过插件本身的API实现吗 用的是dagre布局。

画布的关键配置如下：
`      layout: {
        type: 'dagre',
        rankdir: 'TB',
        nodesep: 75,
        ranksep: 23
      },
      defaultNode: {
        type: NodeTypeEnum.AUDIT_NODE
      },
      defaultEdge: {
        type: 'customEdge',
        style: {
          lineWidth: 1,
          lineAppendWidth: 8,
          stroke: '#c2c7d1',
          cursor: 'pointer'
        }
      },
      fitCenter: true,
      modes: {
        default: [
          'drag-canvas'
        ]
      }`

### 重现链接

如上图描述

### 重现步骤

dagre布局节点位置调整，如上图描述

### 预期行为

希望变成这样：
![image](https://user-images.githubusercontent.com/31124354/196331972-a971b5a9-240e-4c19-a654-1e11bfdb2e40.png)

### 平台

- 操作系统: [macOS,]
- 网页浏览器: [Google 106.0.5249.119（正式版本） (arm64)]
- G6 版本: [4.6.16]

### 补充说明（可选）

连线的弯折是自定义的 用的折线：polyline

**Comment by xiaojueji** [comment]
这里是不是只能通过 节点间的水平间距 ranksepFunc 来实现

**Comment by xiaojueji** [comment]
> 
试了一下 不太行 可能需要知道一下 当布局设为居中的时候 实际的计算规则是怎么样的 包括其他的布局也存在 ”整体居中“的倾向

**Comment by xiaojueji** [comment]
![image](https://user-images.githubusercontent.com/31124354/199012104-26a26ce0-c6f7-471c-8f66-26cfa1d3fcca.png)
比如这个节点也没有跟上面的节点对齐 包含在”整体居中“的倾向里

**Comment by Yanyan-Wang** [comment]
这大概是算法认为合理的位置，它的基本原则是，一个节点的 x 是和上一层有关联的节点、下一层有关联的节点的平均中心。你想对齐的这个节点因为和和其他的上层节点有关联，所以它没有和你希望的上层节点对齐。

我理解如果在布局上面有一些业务语义，比如红框的节点是和想要对齐的那个节点是一个主链路，可以在布局完成之后做一些布局的后处理，比如
graph.on('afterlayout', e => {
// ... 在这里去根据自己的规则调整节点位置 graph.updateItem(node, { x: ..., y: ...})
})

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
