### ISSUE TITLE
timebar plugins在使用destroy销毁画布时提示TypeError: Cannot read properties of null (reading 'type')

### ISSUE THREAD

**Issue by forever-ph** [antvis/G6#3998]
### 问题描述

graph上添加了tooltip，timebar等插件，有需求需要销毁画布重新挂载实例
在执行destroy时提示找不到timbar的type，写法应该是没有问题的，具体可以看重现链接
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/61572069/196613269-c89a93b9-0f0a-4993-9414-95befeaa817c.png">

### 重现链接

https://codesandbox.io/s/blissful-dan-7urmf8?file=/index.js

### 重现步骤

1.重现链接里页面是正常渲染的，只添加的timebar一个插件
2.点击destroy按钮销毁画布时出现上述问题

### 预期行为

期望在添加timebar插件之后可以正常执行destroy销毁画布

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.7.8 ... ]

**Comment by Yanyan-Wang** [comment]
v4.7.11 已解决
