### ISSUE TITLE
交互模式'drag-node', 'drag-canvas'在特定条件下交互失效

### ISSUE THREAD

**Issue by singeonzz** [antvis/G6#3999]
### 问题描述

生成G6Graph实例的时候，设置交互模式为 ['drag-node', 'drag-canvas']。拖动点的时候按下鼠标右键，这个时候drag-canvas和drag-node的交互会失效。
虽然一般不会这么操作（ban掉鼠标默认的右键就不会有这个问题），但还是希望修复一下。

### 重现链接

https://codesandbox.io/s/dazzling-grass-uhjugm?file=/index.js

### 重现步骤

1. 生成Graph实例，并把交互模式设置为['drag-node', 'drag-canvas']
2. 鼠标拖动点的时候按下鼠标右键

### 预期行为

能正常拖拽node和canvas

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome 106]
- G6 版本: [4.7.5]

**Comment by Yanyan-Wang** [comment]
感谢报告。drag-node 拖拽过程中右键导致的后续拖拽节点失效问题 v4.7.11 已解决。下个版本看下 drag-canvas 相关问题

**Comment by Yanyan-Wang** [comment]
已解决
