### ISSUE TITLE
LabelStyle type 定义与文档不符

### ISSUE THREAD

**Issue by tianjunnew** [antvis/G6#4001]
### Describe the bug

文档中说，labelCfg.style 继承了所有 text 属性，而 text 属性又继承了所有通用属性。
但实际中 LabelStyle 是一个独立定义的 interface，因此缺失了很多属性。
举个简单的栗子，cursor 就没有。
造成的问题就是可以去配置一个 node 的 cursor，但无法配置 label 的 cursor，当鼠标移到 label 上时，就变成了 default。
目前解决方案只能是
```ts
{
  labelCfg: {
    style: {
      cursor: 'pointer'
    } as any // ugly
  }
}
```

### Your Example Website or App

-

### Steps to Reproduce the Bug or Issue

-

### Expected behavior

-

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
我理解你的意思是不是说 defaultNode.style.cursor 没有在 label 图形上生效？这个是正常的。一个节点上的各个图形样式是独立配置的，如果你配的是 
defaultNode: {
  style:{...}
}
这里实际上配置的是 keyShape 的样式，例如 circle 类型的节点就是那个圆形。要配置文本图形的样式就需要像你描述的那样配置。

如果你的意思是 labelCfg.style TS 类型有误，那可能是另外一个问题

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
