### ISSUE TITLE
如何为hull添加click事件

### ISSUE THREAD

**Issue by Dawnlee** [antvis/G6#4002]
### 问题描述

如何为hull添加click事件

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
目前没有支持 hull 的事件捕获。请问原始需求是？

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
