### ISSUE TITLE
collapsedSubstituteIcon 使用的时候图片下面会显示出来一个圆 怎么清除掉

### ISSUE THREAD

**Issue by chenlikun-sy** [antvis/G6#4004]
### 问题描述

 "combos": [
        {
            "id": "combo1",
            "type":"circle",
            "size":1,
            "collapsed": true,
            "alarmValue":0,
            "collapsedSubstituteIcon": {
                "show": true,
                "img": "http://10.10.85.190:9094/uiImage/topo/Cloud.svg",
                "width": 72,
                "height": 72
              }
        }
    ]

combo设置成图片的时候，会在图片下面显示一个基础图形

### 重现链接

无

### 重现步骤

无

### 预期行为

期望去掉combo图片下面的基础图形

### 平台

- 操作系统: [ Windows.]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.7.8 ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/49857058/197155836-a7018fe5-0d79-4f6a-a32c-73f8641862dd.png)

**Comment by Yanyan-Wang** [comment]
试一下 v4.7.11，配置了 collapsedSubstituteIcon 的话，collapse 的时候会把 keyShape 隐藏
