### ISSUE TITLE
comboCombined布局下，combo过多发生了combo重叠

### ISSUE THREAD

**Issue by person001** [antvis/G6#4007]
### 问题描述

G6版本4.6.6. 内网环境使用comboCombined布局，但是节点比较多，combo也比较多。绘图出来的结果是combo存在重叠

### 重现链接

https://codesandbox.io/s/floral-fast-mceznk?file=/index.js

### 重现步骤

绘图结束

### 预期行为

希望能有配置项避免combo重叠

### 平台

操作系统: [Windows,]
网页浏览器: [Google Chrome]
G6 版本: [4.6.6 ]

### 屏幕截图或视频（可选）

![183030469-f5e15e19-49e3-4210-8dd7-e1f37e827239](https://user-images.githubusercontent.com/34431484/197436793-3d50a7e4-b5f1-47e5-81f0-5e4c17863e52.jpg)

**Comment by Yanyan-Wang** [comment]
outerLayout 参数可以调整下

    outerLayout:new G6.Layout['force2']({
      factor: 5,
    })

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
