### ISSUE TITLE
radial 布局元素自定义size以后发生重叠

### ISSUE THREAD

**Issue by setWan** [antvis/G6#4008]
### 问题描述

G6版本4.7.8 使用radial布局自定义元素时，元素重叠属性preventOverlap不生效，元素依然重叠

### 重现链接

https://codesandbox.io/s/priceless-stitch-om2rjk

### 重现步骤

绘图结束

### 预期行为

期望元素不重叠

### 平台

- 操作系统: [macOS, Windows]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.7.8 ]

### 屏幕截图或视频（可选）

<img width="501" alt="WeChat2e2292eb43a37c6a732355c19d321b18" src="https://user-images.githubusercontent.com/31428016/197438944-18a68649-7abd-4dcd-8d1a-cbf6ab4af2c4.png">

**Comment by Yanyan-Wang** [comment]
unitRadius 是每一圈距离上一圈的半径，你的 demo 中写死了 100，改大点

**Comment by setWan** [comment]
@Yanyan-Wang 改大了也会乱，试过了

**Comment by Yanyan-Wang** [comment]
> @Yanyan-Wang 改大了也会乱，试过了

linkDistance 配合着修改，一般来说和 unitRadius 一样的值

**Comment by icodeajk** [comment]
@Yanyan-Wang 我使用force2布局也有类似的情况，node里面的size是不固定的，调整linkDistance等其他配置只能保证固定size下不重叠，一旦数据有size更大的点，那就可能会重叠。

**Comment by icodeajk** [comment]
我试了官方例子 https://g6.antv.antgroup.com/examples/net/forceDirected/#basicForce2，给一个node加size 100后并不会防止重叠。另外layout里配置nodeSize并不会生效，我看layout源码里是有这个配置的，但是计算出size后并没有用到
![image](https://github.com/antvis/G6/assets/33170146/173efae6-df12-4ed1-85b1-45dde0a2cc82)
