### ISSUE TITLE
dagre 布局下，有combo的情况下，为防止combo、combo外的node以及其它combo之间的重叠，增加了sortByCombo: true属性，图渲染就有问题

### ISSUE THREAD

**Issue by hualinzhang** [antvis/G6#4012]
### 问题描述

dagre 布局下，有combo的情况下，为防止combo、combo外的node以及其它combo之间的重叠，增加了sortByCombo: true属性，图渲染就有问题

### 重现链接

官方demo中:https://g6.antv.vision/zh/examples/net/dagreFlow#basicDagre

### 重现步骤

1. 将data改为下图中：
![image](https://user-images.githubusercontent.com/38073079/197723801-7c6d5aa2-27e6-4398-ab7a-fa5d140fc37e.png)
代码：
const data = {
  nodes: [
    {
      id: "8a804cc2816b0a9a018170412b180ca7-8a804cc282e8aa680182ed506db90670",
      layer: 0,
      name: "根节点",
    },
    {
      id: "8a804cc283ea578c0183ee15132910ca",
      layer: 1,
      name: "中间件服务器（123.11.1.1）",
    },
    {
      id: "8a804cc283f44c940183f44fde860434",
      layer: 2,
      name: "66redis",
    },
    {
      comboId: "8a804cc283f44c940183f4519e74074e",
      id: "8a804cc283f44c940183f4519e740752",
      layer: 2,
      name: "集群nacos测试(节点2)",
    },
    {
      comboId: "8a804cc283f44c940183f4519e74074e",
      id: "8a804cc283f44c940183f4519e980754",
      layer: 2,
      name: "集群nacos测试(节点3)",
    },
    {
      comboId: "8a804cc283f44c940183f4519e74074e",
      id: "8a804cc28407ea7301840dfcbcf91f4f",
      layer: 2,
      name: "集群nacos测试(节点1)",
    }
  ],
  combos: [
    { id: "8a804cc283f44c940183f4519e74074e", "label": "集群nacos测试" }
  ],
  edges: [
    {
      source: "8a804cc2816b0a9a018170412b180ca7-8a804cc282e8aa680182ed506db90670",
      target: "8a804cc283ea578c0183ee15132910ca"
    },
    {
      source: "8a804cc283ea578c0183ee15132910ca",
      target: "8a804cc283f44c940183f44fde860434"
    },
    {
      source: "8a804cc283ea578c0183ee15132910ca",
      target: "8a804cc283f44c940183f44fde860434"
    },
    {
      source: "8a804cc283ea578c0183ee15132910ca",
      target: "8a804cc283f44c940183f4519e740752"
    }
  ]
};
然后图能够正常显示：
![image](https://user-images.githubusercontent.com/38073079/197724037-6124d3c2-a7cb-4adb-b9cd-8b8cb2e61110.png)

2. 为了防止同层级之间的combo重叠，增加了属性：sortByCombo: true，如下图对应位置：
![image](https://user-images.githubusercontent.com/38073079/197724503-a5010b4c-78c3-4403-9ece-a9e09c0275b2.png)

### 预期行为

我期望：当节点数量很多的时候，同层级的相同combo的node挨着放，图能够正常渲染。
实际结果：图无法正常渲染，控制台打印data，其中node的位置y为NAN，如下图：
![image](https://user-images.githubusercontent.com/38073079/197725376-ff549eaf-fb92-4a10-8d93-4ff5beeba4d2.png)

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
在 antv/layout 修复了，重新安装一下即可更新到 antv/layout 最新版本 0.3.3
