### ISSUE TITLE
The legend dose not support node with typ of star and diamond/图例无法绘制五角星和棱形节点

### ISSUE THREAD

**Issue by hry625** [antvis/G6#4013]
### Describe the bug

图例无法绘制五角星和棱形节点

### Your Example Website or App

https://codesandbox.io/s/suspicious-sun-bc0rq7?file=/index.js

### Steps to Reproduce the Bug or Issue

更改图例的sample code中的typeConfigs.type1.type，选择star或者diamond，报错。且无法更改标签与图标的相对位置。

### Expected behavior

图例可以绘制五角星和棱形节点，并可自定义节点label和shape的相对位置。

### Screenshots or Videos

<img width="1183" alt="截屏2022-10-25 13 49 12" src="https://user-images.githubusercontent.com/10716480/197773348-f67c130a-d68a-4611-ae92-757db169b04b.png">

### Platform

- OS: [macOS]
- Browser: [Chrome]
- Version: [^4.5.1]

**Comment by Yanyan-Wang** [comment]
正在修复中，duplicate to https://github.com/antvis/G6/issues/3876
