### ISSUE TITLE
Graph中的modes属性在本地生效，打包后不生效，

### ISSUE THREAD

**Issue by zhangheruijun** [antvis/G6#4018]
### Describe the bug

Graph中的modes属性在本地生效，打包后不生效，

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

 const graph = new G6.Graph({
      container: 'g6editLine',
      width: this.width,
      height: this.height,
      plugins: [contextMenu],
      modes: {
        default: [
          // 为拖动节点配置shouldBegin，以避免节点在拖动锚点圆圈时移动
          {
            type: 'drag-node',
            shouldBegin: (e) => {
              if (e.target.get('name') === 'anchor-point') return false;
              return true;
            },
          },
]}
})
其中modes在本地生效，打包上线后无效

### Expected behavior

无

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
无

**Comment by Yanyan-Wang** [comment]
检查一下线上线下的版本号

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
