### ISSUE TITLE
当节点被拖出画布视野范围外以后，再拖拽画布视野内的节点，会出现卡顿的情况

### ISSUE THREAD

**Issue by chenlikun-sy** [antvis/G6#4019]
### 问题描述

当节点被拖出画布视野范围外以后，再拖拽画布视野内的节点，会出现卡顿的情况，在官方样例中也能复现这个卡的效果

### 重现链接

https://g6.antv.vision/zh/examples/net/dagreFlow#dagreCombo

### 重现步骤

1、进入demo
2、拖出画布视野一个node
3、再拖拽画布视野范围内的node

### 预期行为

希望当一个点被拖拽出画布视野外的时候，再拖拽其它点的时候不出现卡顿

### 平台

- 操作系统: [ Windows]
- 网页浏览器: [Google Chrome,]
- G6 版本: [4.7.8... ]

### 屏幕截图或视频（可选）

![Uploading image.png…]()

### 补充说明（可选）

这种情况下 当操作人将点拖出画布视野后，页面拖动就会异常的卡顿，这个在官网有些可复现，有些则没复现

**Comment by Yanyan-Wang** [comment]
好像没能复现，卡顿的时候控制台是否有报错？截图裂了看不到

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
