### ISSUE TITLE
add animate:true  tooltip error

### ISSUE THREAD

**Issue by BusyHe** [antvis/g6#402]
G6 version: 2.0.5-beta.9

let tree = new G6.Tree({
                container: 'mount-node',
                animate: true, // 设为true
                fitView: 'cc',
                plugins: [minimap, tooltip],
                modes: {
                    red: ['mouseEnterFillRed', 'mouseLeaveResetFill'],
                    green: ['mouseEnterFillGreen', 'mouseLeaveResetFill']
                },
                mode: 'green'
            });

**Comment by BusyHe** [comment]
![jietu20180730-111859-hd](https://user-images.githubusercontent.com/17348825/43375935-91aa8f8a-93ea-11e8-863e-58cd772ae7c0.gif)

**Comment by TomHuangCN** [comment]
need codepen
