### ISSUE TITLE
是否支持微信小程序

### ISSUE THREAD

**Issue by Leonard-W** [antvis/G6#4020]
### 问题描述

微信小程序

### 重现链接

 微信小程序

### 重现步骤

 微信小程序

### 预期行为

微信小程序

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]
- 微信小程序

**Comment by Yanyan-Wang** [comment]
可以了解一下 antv/f6 ，移动端的解决方案 https://f6.antv.vision/zh/
