### ISSUE TITLE
image节点的固定是方形无法改变

### ISSUE THREAD

**Issue by wufang95** [antvis/G6#4021]
### 问题描述

在使用image节点中，使用了圆形的节点，发现在节点连线的时候edges(边)始终无法连接到圆形图片上
使用了裁切
clipCfg: {
  show: true,
  type: 'circle',
  r: 10  // 裁切大小是正常的
}
之后，边线仍然是组成了一个方形区域，由此判断image节点始终是个方形的区域，请问有什么方法可以改变这种情况么？

### 重现链接

无

### 重现步骤

1，添加image节点，并选择一个圆形的图片
2，添加边线

### 预期行为

期望从视觉上来说，边线可以连接在圆形的图片上，而不是连接在不可见的方形区域上

### 平台

- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by Yanyan-Wang** [comment]
是的，只是增加裁剪没有改变它本身的形状。graph 可以设置 linkCenter: true，让边都连接到节点中心，然后再配置箭头的偏移量 `d` 让箭头“往外退”一些 https://g6.antv.vision/zh/docs/manual/middle/elements/edges/arrow

**Comment by wufang95** [comment]
> 是的，只是增加裁剪没有改变它本身的形状。graph 可以设置 linkCenter: true，让边都连接到节点中心，然后再配置箭头的偏移量 `d` 让箭头“往外退”一些 https://g6.antv.vision/zh/docs/manual/middle/elements/edges/arrow

那么请问一下，可以使用keyShape来处理这种情况吗？有没有示例可以参考下~谢谢

**Comment by Yanyan-Wang** [comment]
> > 是的，只是增加裁剪没有改变它本身的形状。graph 可以设置 linkCenter: true，让边都连接到节点中心，然后再配置箭头的偏移量 `d` 让箭头“往外退”一些 https://g6.antv.vision/zh/docs/manual/middle/elements/edges/arrow
> 
> 那么请问一下，可以使用keyShape来处理这种情况吗？有没有示例可以参考下~谢谢

内置的 image 节点 keyShape 就是这个图片图形，你可以自定义节点，加一个 image 图形，另外加一个圆形作为 keyShape，draw 方法返回它，自定义节点 demo：https://g6.antv.antgroup.com/examples/item/customNode/#pieChart
自定义节点文档：https://g6.antv.antgroup.com/manual/middle/elements/nodes/custom-node
