### ISSUE TITLE
GForce GPU layout, some edges very long

### ISSUE THREAD

**Issue by zhenya-zhu** [antvis/G6#4022]
### Describe the bug

Comparing CPU and GPU results of GForce layout in the same data set

There are some edges very long, and cause graph hard to use

### Your Example Website or App

https://stackblitz.com/~/github.com/zhenya-zhu/graph-playground

### Steps to Reproduce the Bug or Issue

1. go to `CPU` tab
2. go to `GPU` tab

### Expected behavior

GPU layout do not have very long edges

### Screenshots or Videos

GPU:
![image](https://user-images.githubusercontent.com/3053802/199153355-5ccda1c6-7d2f-406b-9178-8390dd328268.png)

CPU:
![image](https://user-images.githubusercontent.com/3053802/199153327-d7634c61-4a16-471e-9e50-1636497df48f.png)

### Platform

- OS: macOS 
- Browser: Chrome
- Version: 106.0.5249.119 (Official Build) (arm64)

**Comment by AgustinBanchio** [comment]
This appears to be the same problem we are having: https://github.com/antvis/G6/issues/3424

It affects both Fruchterman and GForce when GPU accelerated (maybe all GPU accelerated layouts?)

When the node and edge count becomes high enough, some edges become very stretched. Most of the time rendering the graph useless.

The only solution we have so far is disabling GPU acceleration, but the time to calculate becomes very long.

We see it happening in M1, M1Pro macs or Windows PCs with Nvidia Graphics, so it's probably not fully related to a specific hardware or OS.

**Comment by jadenmazzone** [comment]
Experiencing this as well on M1. Any timeline for when this will be fixed?
