### ISSUE TITLE
某些情况下边的起始点索引不生效

### ISSUE THREAD

**Issue by Alin2077** [antvis/G6#4024]
### Describe the bug

给自定义边设置了起始点索引，但部分渲染发生了错误

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

大致情况如下：
1.总共有4个节点。命名为A,B,C,D。
2.B设定了2个锚点，命名为1，2。
3.A指向B的1锚点，B的2锚点指向C,D；均有结束箭头。
bug现象：
A指向B1和B2指向D均正常。但是B2指向C却渲染出了B1指向C。

### Expected behavior

希望尽快修复

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Alin2077** [comment]
刚才又测试了一下。这个bug产生的原因是A节点和C节点的X坐标相同。

**Comment by Yanyan-Wang** [comment]
请给出复现的在线 demo
