### ISSUE TITLE
带有 Combo 的流程图dagreCombo附带的CodeSandBox官方示例一片空白

### ISSUE THREAD

**Issue by eat-the-red-pill** [antvis/G6#4025]
### 问题描述

[带有 Combo 的流程图dagreCombo](https://g6.antv.vision/zh/examples/net/dagreFlow#dagreCombo)附带的[CodeSandBox官方示例](https://codesandbox.io/s/74d1xo)一片空白，console没有报错，把项目下载到本地也是一片空白，无法复现教程所需。

### 重现链接

[CodeSandBox官方示例](https://codesandbox.io/s/74d1xo)

### 重现步骤

[CodeSandBox官方示例](https://codesandbox.io/s/74d1xo) 直接打开就发现一片空白，和[带有 Combo 的流程图dagreCombo](https://g6.antv.vision/zh/examples/net/dagreFlow#dagreCombo)官网文档所描述的不一样。

### 预期行为

我期待看到[带有 Combo 的流程图dagreCombo](https://g6.antv.vision/zh/examples/net/dagreFlow#dagreCombo)官网文档所描述的效果，但是打开 [CodeSandBox官方示例](https://codesandbox.io/s/74d1xo) 发现除了一个`Enable sortByCombo`框框之外就是一片空白，没有期待的效果图。

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.7.5 ]

**Comment by Yanyan-Wang** [comment]
graph 的 height 太小了，搞大点。先写死 width: 500, height: 500 就能看到图
