### ISSUE TITLE
类型为图片的节点，在画布里操作节点，节点显示异常

### ISSUE THREAD

**Issue by yuanbenmo** [antvis/G6#4034]
### 问题描述

拖入图片类型节点到画布，在画布点击节点或者拖动节点会出现一大片色块，

### 重现链接

无

### 重现步骤

1从左侧工具栏拖入图片类型节点
2点击toolbar的事件，点击选中事件，再点击节点，出现侧边栏弹窗，图片节点变成一个矩形色块，多次点击画布才正常
3拖入画布的节点后，在画布里拖动节点，节点轨迹变成一大片色块

### 预期行为

期望点击，拖动正常显示图片节点

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
麻烦提供一下在线复现 demo

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
