### ISSUE TITLE
请问该如何为G6的一些不具备layout动画的layout添加动画？

### ISSUE THREAD

**Issue by zhenya-zhu** [antvis/G6#4039]
### 问题描述

我想改源码 为GForce GPU实现像GForce CPU一样的layout动画。

请问下需要实现/调用什么接口？

### 重现链接

https://codesandbox.io/s/new

### 重现步骤

Null

### 预期行为

Null

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by zhenya-zhu** [comment]
好像懂了点
updatePosition()
refreshPositions()

**Comment by zhenya-zhu** [comment]
所以先让GForce GPU需要被调用tick
然后在每次拿到中间结果后，调用updatePosition
再执行tick，tick里面refreshPositions

**Comment by zhenya-zhu** [comment]
卡在 调用了refreshPositions但是没有触发绘制

**Comment by Yanyan-Wang** [comment]
force 一类有“力”相互作用的动画效果是因为在布局计算过程中，每一个迭代都拿到中间结果进行一次绘制。而 GPU 的计算没有办法在计算过程中不断渲染，因为计算过程中，中间数据都在显存上，如果每个迭代都让中间结果传给 CPU 绘制，那么传输将导致非常大的性能开销，甚至最后计算效果不如 CPU 计算。因此开启 GPU 计算的情况下，只能最后计算完成之后，进行一次插值动画，也就是配置图示例 animate: true，会在布局完成之后，所有节点位置从布局前的位置插值运动到新的位置上，原理上是通过 graph.positionAnimate() 更新节点位置

**Comment by Yanyan-Wang** [comment]
由于您的 issue 长时间没有回复，我们无法根据你提供的信息给出解答，所以暂时关闭这个 issue。若有新的进展，可随时新开 issue。
