### ISSUE TITLE
默认节点为ModelRect时，changeData()后渲染错误

### ISSUE THREAD

**Issue by chenbr17** [antvis/G6#4041]
### Describe the bug

默认节点配置为ModelRect，在触发changeData后，节点渲染错误，拖动节点出现残影及显示不全

### Your Example Website or App

https://codesandbox.io/s/gracious-mendeleev-9xvirh?file=/index.js

### Steps to Reproduce the Bug or Issue

1. 点击画布触发changeData
2. 节点渲染错误，拖动节点出现残影

### Expected behavior

正常渲染，拖动无错误

### Screenshots or Videos

![g6issue](https://user-images.githubusercontent.com/46919746/201023536-14488a95-ccb3-4c74-b883-dbd720cfbf0b.png)

### Platform

- OS: Windows
- Browser: Edge
- Version: 107.0.1418.35 

### Additional context

defaultNode中添加labelCfg.offset属性 问题消失

**Comment by Yanyan-Wang** [comment]
感谢报告，即将修复

**Comment by Yanyan-Wang** [comment]
v4.7.13 已修复
