### ISSUE TITLE
mouse events are fired twice on nodes

### ISSUE THREAD

**Issue by ensconced** [antvis/G6#4043]
### Describe the bug

When clicking on nodes, events are fired twice. The same seems to happen for other events, e.g. contextmenu.

### Your Example Website or App

https://stackblitz.com/edit/react-xoqsky?file=index.js

### Steps to Reproduce the Bug or Issue

- Click on the node
- Open the console
- See the click event is logged out twice

### Expected behavior

Click event should only be logged once

### Platform

MacOS, Chrome 107.0.5304.110 (Official Build) (arm64)

**Comment by ensconced** [comment]
This seems to be the reason https://github.com/antvis/G6/blob/master/packages/pc/src/graph/controller/event.ts#L136

The event fires on the Graph while bubbling up, then it fires on the Canvas, then on that line of code, the canvas emits the event again on the Graph. I don't understand why we do that though.

**Comment by ensconced** [comment]
As a workaround I'm just listening to events on the canvas object instead:

```
graph.get("canvas").on('click', () => {
  // ...
})
```

**Comment by Yanyan-Wang** [comment]
Try to listening specified events for different target. e.g. node:click, canvas:click

I will check out the problem later
