### ISSUE TITLE
modelRect节点交互时icon闪动如何解决

### ISSUE THREAD

**Issue by fzegg** [antvis/G6#4044]
### 问题描述

鼠标移入或移出节点时导致节点内icon闪动

### 重现链接

https://codesandbox.io/s/0jk87p

### 重现步骤

鼠标移入或移出节点

### 预期行为

期望icon的state默认不切换，表现为不闪动，实际上发生闪动

### 平台

- 操作系统: macOS
- 网页浏览器: Google Chrome,
- G6 版本: 4.7.12

### 补充说明（可选）

有类似issue，https://github.com/antvis/G6/issues/3645。
但是能否提供更详细的官方解决方案，或是在默认情况下不切换icon的state。另外想问一下，这个默认情况下存在的icon闪动问题在g6看来是可以接受的吗？

**Comment by Martin2037** [comment]
同问

**Comment by xiaohun254700** [comment]
同问，请问解决没，本想从jtopo往G6迁移，但是跑了几个demo，发现了这个问题，想问一下这个暂时的解决方案是什么？
