### ISSUE TITLE
“force2”布局，右键展开功能，偶现扩展的节点堆叠在一起，layout中nodeSpacing设置了50

### ISSUE THREAD

**Issue by xichao520** [antvis/G6#4045]
### Describe the bug

“force2”布局，右键展开功能，偶现扩展的节点堆叠在一起，layout中nodeSpacing设置了50

### Your Example Website or App

https://codesandbox.io/s/youthful-surf-jzjwh0?file=/src/App.js

### Steps to Reproduce the Bug or Issue

1.等待页面加载完成
2.随便找个结点，右键-》展开
3.然后再随便找个结点，右键-》展开，不断重复该操作即可复现

### Expected behavior

期望每次“右键-》展开“操作不会出现结点堆叠在一起的情况

### Screenshots or Videos

![微信图片_20221114142017](https://user-images.githubusercontent.com/8890755/201589164-3607f803-88d7-404f-878b-e8dfcf65656d.jpg)

### Platform

- OS: [Windows]
- Browser: [Chrome]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
maxSpeed 配置大一些，现在默认是 100，调整成 500 以上看看。我这里把默认参数调大些

**Comment by xichao520** [comment]
> maxSpeed 配置大一些，现在默认是 100，调整成 500 以上看看。我这里把默认参数调大些

经测试验证，maxSpeed调成500还是会偶现重叠的情况

**Comment by Yanyan-Wang** [comment]
有稳定复现的方式吗？

**Comment by xichao520** [comment]
右键》展开，该操作执行十次左右基本都能复现

> 有稳定复现的方式吗？
