### ISSUE TITLE
Chrome 下官网目录空白时UI异常

### ISSUE THREAD

**Issue by yusixian** [antvis/G6#4048]
### Describe the bug

目录空白的时候会有异常长条
![image](https://user-images.githubusercontent.com/43498495/201889590-e717fbfa-ce64-41ba-9419-517b9fee804d.png)

### Your Example Website or App

https://g6.antv.antgroup.com/manual/getting-started

### Steps to Reproduce the Bug or Issue

- 进页面后点击FAQ 或者任意没有目录的页面就会出现

### Expected behavior

- 存在空白目录时不应该有这个长条

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/43498495/201889590-e717fbfa-ce64-41ba-9419-517b9fee804d.png)

### Platform

- OS: macOS
- Browser: Chrome
- Version: 107.0.5304.110

**Comment by hustcc** [comment]
是不是已经修复了，我看已经没有了~

**Comment by yusixian** [comment]
> 是不是已经修复了，我看已经没有了~

还在，我是Chrome
![image](https://user-images.githubusercontent.com/43498495/202424745-88edaac7-c5c2-45cd-8e56-d1145a9e835e.png)
