### ISSUE TITLE
在设计体系页面，当滚动到底部，底部导航栏的宽度没有100% 并且右侧的导航会被底部导航遮盖住

### ISSUE THREAD

**Issue by SK-Luffa** [antvis/G6#4049]
### 问题描述

在设计体系页面，当滚动到底部，底部导航栏的宽度没有100% 并且右侧的导航会被底部导航遮盖住
![26ADC712DD1F651EDA8F6C772DC102B5](https://user-images.githubusercontent.com/52227746/201893147-a140b03a-b0ec-4dd2-a7fe-52360700a41e.jpg)

### 重现链接

https://g6.antv.antgroup.com/design/overview

### 重现步骤

1. 进入设计体系页面
2. 滑动到最底部
3. 可以观察到底部导航左侧没有的宽度没有100% 有点突兀
4. 右侧的导航会被底部导航给遮盖住

### 预期行为

底部导航展示100%
右侧不会被底部导航遮盖住，可以给一个高度或margin

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![26ADC712DD1F651EDA8F6C772DC102B5](https://user-images.githubusercontent.com/52227746/201893649-535edcf1-33c0-4877-bb6b-0baefddc7d95.jpg)

**Comment by hustcc** [comment]
> 可以观察到底部导航左侧没有的宽度没有100% 有点突兀
> 右侧的导航会被底部导航给遮盖住

这两个都符合预期，不作处理。
