### ISSUE TITLE
Chrome 下官网搜索跳转失效

### ISSUE THREAD

**Issue by yusixian** [antvis/G6#4050]
### Describe the bug

- 搜索跳转失效

### Your Example Website or App

https://g6.antv.antgroup.com/manual/getting-started

### Steps to Reproduce the Bug or Issue

- 搜索任意关键词跳转无效

### Expected behavior

- 正确跳转到搜索的页面

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/43498495/201893418-5814289a-6f69-42b3-b750-e787af6a9f5e.png)
跳转404
![image](https://user-images.githubusercontent.com/43498495/201894056-48b4bea9-0ee3-4574-9a4a-195f0e0f8dd0.png)

### Platform

- OS: macOS
- Browser: Chrome
- Version: 107.0.5304.110

**Comment by Yanyan-Wang** [comment]
解决咯
