### ISSUE TITLE
右上方导航部分的滚动条

### ISSUE THREAD

**Issue by xuepeng184** [antvis/G6#4051]
### 问题描述

拖动到最下方时出现横向滚动条，但是拖动没有反应，且没有纵向滚动条

### 重现链接

https://g6.antv.antgroup.com/manual/advanced/coordinate-system

### 重现步骤

进入页面后直接滚动到最下方，如果右方导航栏过高则会出现

### 预期行为

不应该出现横向滚动条，可能应该出现纵向滚动条

### 平台

- 操作系统: [,Windows]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

https://user-images.githubusercontent.com/73777958/201895465-d444ecd8-1f72-49c9-b38d-3c9630604608.mp4

**Comment by Yanyan-Wang** [comment]
解决咯
