### ISSUE TITLE
官网进行任何搜索都会进入404页面

### ISSUE THREAD

**Issue by RoyDust** [antvis/G6#4052]
### 问题描述

当用chorme浏览器访问官网搜索任何内容时，都会进入404页面

### 重现链接

https://g6.antv.antgroup.com/zh/docs/api/graphLayout/comboCombined/#gatsby-focus-wrapper

### 重现步骤

1.用chorme浏览器访问AntVG6官网
2.进行搜索
3.转跳到404页面

### 预期行为

我希望看到搜索内容，现在只出现了404页面

### 平台

- 操作系统: Windows
- 网页浏览器: Google Chrome
- G6 版本: [4.5.1 ... ]
- 时间：2022年11月15日

### 屏幕截图或视频（可选）

![QQ图片20221115182210](https://user-images.githubusercontent.com/50167909/201895279-3aa8944b-f585-44a4-b23f-c82469346d21.png)
![QQ图片20221115182213](https://user-images.githubusercontent.com/50167909/201895291-1cf76af9-9fb4-427d-a1f8-6b149a502494.png)

**Comment by BoyYangzai** [comment]
已经存在相同的issue https://github.com/antvis/G6/issues/4050
