### ISSUE TITLE
导航从右向左滑动到所有产品的文字部分（不是图标），无法触发下拉菜单

### ISSUE THREAD

**Issue by SK-Luffa** [antvis/G6#4059]
### 问题描述

导航从右向左滑动到所有产品的文字部分（不是图标），无法触发下拉菜单

### 重现链接

https://g6.antv.antgroup.com/design/overview

### 重现步骤

1. 进入主页
2. 鼠标移动到右上角菜单部分，向左移动，当移动到所有产品（不包含图标）时无法触发下拉菜单
![144EE148-E9DC-4FA4-A37F-354086E7097D](https://user-images.githubusercontent.com/52227746/202079999-2d563192-73d0-4382-96b7-c24d072544d4.png)

### 预期行为

请解决这个问题

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![Uploading 144EE148-E9DC-4FA4-A37F-354086E7097D.png…]()

**Comment by Yanyan-Wang** [comment]
太牛了。这么细都发现了
