### ISSUE TITLE
撤销重做这两个事件方法是什么？还是没有需要自己实现？

### ISSUE THREAD

**Issue by BusyHe** [antvis/g6#406]
version 2.0.5-beta.9

**Comment by TomHuangCN** [comment]
![image](https://user-images.githubusercontent.com/6113694/43568815-38af3928-9668-11e8-99b6-bd39ddd768d2.png)

这是 G6-Editor 里的方法。

**Comment by BusyHe** [comment]
用G6能不能实现呢

**Comment by TomHuangCN** [comment]
撤销重做，本质是套命令系统。G6 是底层渲染，不会内部继承。

**Comment by BusyHe** [comment]
那我操作一每操作一步创建或删除去save，存到list里面。执行撤销和重做时去read，这样可以吗？
我没有用edit，因为没有文档，所以直接用的G6
![image](https://user-images.githubusercontent.com/17348825/43569151-43125160-9669-11e8-901f-5becbbf5e67e.png)

**Comment by hihl** [comment]
@BusyHe remove和add就足够了，自己根据业务需要来做。
