### ISSUE TITLE
所有页面的标题 旁边都有一个可编辑的图标，点击进去404

### ISSUE THREAD

**Issue by SK-Luffa** [antvis/G6#4062]
### 问题描述

所有页面的标题 旁边都有一个可编辑的图标，点击进去404
![8E516939-367E-47AC-BC40-CB5EBA71DE4D](https://user-images.githubusercontent.com/52227746/202081890-b893e45a-b775-4e93-86d2-23348f7c97a9.png)

### 重现链接

https://g6.antv.antgroup.com/api/graph

### 重现步骤

1. 进入页面，导航栏里的任意文章 包括 教程 api等
2. 主标题旁边有一个 可编辑的图标
3. 点击进去404
4. 
![Uploading 8E516939-367E-47AC-BC40-CB5EBA71DE4D.png…]()

### 预期行为

请修改这个问题

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![8E516939-367E-47AC-BC40-CB5EBA71DE4D](https://user-images.githubusercontent.com/52227746/202082111-aa39f854-0c52-43f4-ae5d-543a438552a8.png)

**Comment by BoyYangzai** [comment]
已修复，待上线 https://github.com/antvis/dumi-theme-antv/pull/177

**Comment by SK-Luffa** [comment]
收到------------------------------------------------------------------
***@***.***>
日　期：2022年11月17日 10:24:30
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [antvis/G6] 所有页面的标题 旁边都有一个可编辑的图标，点击进去404 (Issue #4062)

已修复，待上线 antvis/dumi-theme-antv#177
