### ISSUE TITLE
g6 脑图性能优化

### ISSUE THREAD

**Issue by LLLuojp** [antvis/G6#4063]
### 问题描述

使用g6 实现脑图功能时，自定义的节点还有自定义的边（直线代替折线），当数据量很大，页面节点很多的时候，拖拽画布，或者移动小地图时，都会非常的卡顿。有没有什么办法可以优化一下呀？

### 重现链接

无

### 重现步骤

内网，无法展示

### 预期行为

1

### 平台

- 操作系统: [Windows, vue3]
- 网页浏览器: [Google Chrome,]
- G6 版本: [4.6.6 ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/41289147/202090478-b662b4a2-408d-4f89-9991-f24401a23d33.png)

页面就类似于这种，但是数据量要比这个多很多，满屏的那种。

**Comment by Yanyan-Wang** [comment]
1. 小地图使用 keyShape 模式。
2. 大数据缩小时简化图上内容，在例子缩小试试: http://g6.antv.antgroup.com/examples/case/treeDemos/#decisionTree

**Comment by LLLuojp** [comment]
> 1. 小地图使用 keyShape 模式。
> 2. 大数据缩小时简化图上内容，在例子缩小试试: http://g6.antv.antgroup.com/examples/case/treeDemos/#decisionTree

keyShape模式小地图上就没有脑图的大概轮廓了，只有一个矩形框，放大缩小的时候还好，不是很卡顿，主要是拖拽画布或者移动小地图的时候，交互很差。

**Comment by Yanyan-Wang** [comment]
> 



> > 1. 小地图使用 keyShape 模式。
> > 2. 大数据缩小时简化图上内容，在例子缩小试试: http://g6.antv.antgroup.com/examples/case/treeDemos/#decisionTree
> 
> keyShape模式小地图上就没有脑图的大概轮廓了，只有一个矩形框，放大缩小的时候还好，不是很卡顿，主要是拖拽画布或者移动小地图的时候，交互很差。

那可以用 delegate 模式，可以配置 delegate 的样式，这样起码不会是没有填充的矩形框看不清楚

**Comment by LLLuojp** [comment]
> > 
> 
> > > 1. 小地图使用 keyShape 模式。
> > > 2. 大数据缩小时简化图上内容，在例子缩小试试: http://g6.antv.antgroup.com/examples/case/treeDemos/#decisionTree
> > 
> > 
> > keyShape模式小地图上就没有脑图的大概轮廓了，只有一个矩形框，放大缩小的时候还好，不是很卡顿，主要是拖拽画布或者移动小地图的时候，交互很差。
> 
> 那可以用 delegate 模式，可以配置 delegate 的样式，这样起码不会是没有填充的矩形框看不清楚

现在最主要的问题是当节点很多的时候，其实就几百个节点的时候就已经开始卡了，拖动起来很不流畅。

**Comment by Yanyan-Wang** [comment]
> > > 
> > 
> > 
> > > > 1. 小地图使用 keyShape 模式。
> > > > 2. 大数据缩小时简化图上内容，在例子缩小试试: http://g6.antv.antgroup.com/examples/case/treeDemos/#decisionTree
> > > 
> > > 
> > > keyShape模式小地图上就没有脑图的大概轮廓了，只有一个矩形框，放大缩小的时候还好，不是很卡顿，主要是拖拽画布或者移动小地图的时候，交互很差。
> > 
> > 
> > 那可以用 delegate 模式，可以配置 delegate 的样式，这样起码不会是没有填充的矩形框看不清楚
> 
> 现在最主要的问题是当节点很多的时候，其实就几百个节点的时候就已经开始卡了，拖动起来很不流畅。


如果 minimap 是默认模式的话，相当于图上有两倍的开销。使用 keyShape 或者 delegate 可以减少很大一笔开销。
还可以给 drag-canvas 、zoom-canvas 配置一下 enableOptimize: true, 这样在拖拽和缩放过程中，非关键图形会被隐藏，避免频繁的渲染。

**Comment by LLLuojp** [comment]
> > > > 
> > > 
> > > 
> > > > > 1. 小地图使用 keyShape 模式。
> > > > > 2. 大数据缩小时简化图上内容，在例子缩小试试: http://g6.antv.antgroup.com/examples/case/treeDemos/#decisionTree
> > > > 
> > > > 
> > > > keyShape模式小地图上就没有脑图的大概轮廓了，只有一个矩形框，放大缩小的时候还好，不是很卡顿，主要是拖拽画布或者移动小地图的时候，交互很差。
> > > 
> > > 
> > > 那可以用 delegate 模式，可以配置 delegate 的样式，这样起码不会是没有填充的矩形框看不清楚
> > 
> > 
> > 现在最主要的问题是当节点很多的时候，其实就几百个节点的时候就已经开始卡了，拖动起来很不流畅。
> 
> 如果 minimap 是默认模式的话，相当于图上有两倍的开销。使用 keyShape 或者 delegate 可以减少很大一笔开销。 还可以给 drag-canvas 、zoom-canvas 配置一下 enableOptimize: true, 这样在拖拽和缩放过程中，非关键图形会被隐藏，避免频繁的渲染。

您说的这些我都设置了，而且就算把小地图关闭，节点数量300+的时候还是会很卡顿，拖拽画布，缩放的时候就像是有1秒的延时一样。我是自定义节点，不过并不复杂，都只是rect + text。 请问这种节点过多，出现卡顿的现象是正常的吗？

**Comment by Yanyan-Wang** [comment]
300 多个点，应该还好的，主要是文字多的话，开销会比较大。渲染的性能主要看图上图形的个数，可能你这里一个节点上有多个 rect 多个 text？具体你可以写一下在线 demo，我看下怎么优化

**Comment by songhn233** [comment]
> 渲染的性能主要看图上图形的个数

Hello，想确认一下，当前 G 作为渲染引擎，实际渲染到 Canvas 上的图元的个数是怎么确定的（好像没有暴露 API）

对于节点点击等可能会有交互，这种情况下会预设一个隐藏的 Shape，在 setState 时再调整 Shape 为可见。对于 `visibility: hidden` 和 `group.hide()` 我理解是一样的，这种处理下对于大量的数据是否会有问题。

以及设置 Shape `style` 中 `opacity: 0` 和上面的 hide 方法是不是等价的，还是说会有额外的损耗？建议用哪一种方式呢

**Comment by songhn233** [comment]
> 撞枪口上了，刚写了篇文章：http://g6.antv.antgroup.com/manual/faq/performance-opt

感谢，不过好奇 opacity 和 visibility 表现都是透明在实际渲染上主要区别在哪里？实际渲染走的是G，看源码定位有点复杂😂

**Comment by Yanyan-Wang** [comment]
> > 撞枪口上了，刚写了篇文章：http://g6.antv.antgroup.com/manual/faq/performance-opt
> 
> 感谢，不过好奇 opacity 和 visibility 表现都是透明在实际渲染上主要区别在哪里？渲染走的是G，看源码定位性能有点复杂😂

visibility false 的话 ，G 就不会渲染它。但是 opacity:0 的话，其实还是渲染的，和 opacity: 0.1 opacity:1 是一样的处理

**Comment by Yanyan-Wang** [comment]
minimap 最近支持了配置  hideEdge，配置为 true，则 minimap 上将不会渲染边，减少一些开销

**Comment by Yanyan-Wang** [comment]
还是有性能问题的话，新开 issue 发一下在线复现 demo 哈，我看下实现方式有没有问题。

尊敬的用户，您好。我们很重视您的 issue，但由于我们没有得到可追踪复现的 demo，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
