### ISSUE TITLE
dagre图使用layer指定节点层级 渲染很慢

### ISSUE THREAD

**Issue by zuoshengjie** [antvis/G6#4064]
### 问题描述

dagre布局 300多个节点，使用layer指定层级展示时渲染很慢，页面要卡顿20多秒才可以展示

### 重现链接

https://stackblitz.com/edit/web-platform-fncsgb?file=index.html

### 重现步骤

使用链接中数据时进入页面就会卡顿很久才能展示

### 预期行为

快速展示

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.7.5]

### 补充说明（可选）

使用链接中数据时进入页面就会卡顿很久才能展示

**Comment by zuoshengjie** [comment]
perf: improve the performance of dagre with layers
看到layout的更新了，本地改后试了试是可以的。
非常感谢 Yanyan-Wang

**Comment by Yanyan-Wang** [comment]
还没有发版本，这两天公司网络不好发不上去

**Comment by Yanyan-Wang** [comment]
更新 @antv/layout 到 0.3.4 或者重新安装 @antv/g6 即可

**Comment by Yanyan-Wang** [comment]
该案例 25s -> 200ms （测试环境：MAC M1）
