### ISSUE TITLE
react中使用布局插件时看不到效果

### ISSUE THREAD

**Issue by littleH1** [antvis/g6#407]
* **G6 Version**:2.0.4
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by littleH1** [comment]
import G6 from "@antv/g6/build/g6";
import '@antv/g6/build/plugins'
const dagre = new G6.Plugins['layout.dagre']({
            rankdir: "LR",
            nodesep: 100,
            ranksep: 100
        });
        const graph = new G6.Graph({
            id: 'flowChart',
            height: window.innerHeight,
            fitView: 'cc',
            plugin:[dagre],
        });

想看到自动布局的效果，但只看到所有点叠在一起了，在html中试过可以，请问是在react中使用的方法不对吗？

**Comment by TomHuangCN** [comment]
g6 是纯 js 框架。跟任何前端框架无关。

你看下 https://codepen.io/DoriTong/pen/pKbLVw 这里能不能运行
