### ISSUE TITLE
indented 布局节点高度不一致时会出现重叠的情况

### ISSUE THREAD

**Issue by hengistchan** [antvis/G6#4070]
### Describe the bug

indented 布局节点高度不一致时会出现重叠的情况
<img width="718" alt="image" src="https://user-images.githubusercontent.com/46242125/202368763-793fcfe0-cfef-468c-9f29-fe34b893dd93.png">

### Your Example Website or App

https://stackblitz.com/edit/react-ts-thygty?file=G6.tsx

### Steps to Reproduce the Bug or Issue

节点高度由每个节点自行配置，在 draw 函数中读取 height 属性并设置 container keyshape 高度

```js
{
  id: '2',
  label: '2',
  height: 34,
}
```

<img width="740" alt="image" src="https://user-images.githubusercontent.com/46242125/202369052-72712b43-6676-4ba8-9083-dee887fb05fc.png">
如上，这个框应该出现在下面
在 layout 配置中有配置了 getHeight 函数

```js
getHeight(cfg: any) {
  const height = cfg?.height;
  return height ?? 34;
}
```

### Expected behavior

自适应节点高度

### Platform

- OS: macOS
- Browser: Chrome
- Version: 版本 107.0.5304.110（正式版本） (arm64)

**Comment by Yanyan-Wang** [comment]
看起来好像是子节点的高度优先级高于自身 setHeight 返回值了，比如把 id 2 节点的子节点删掉就看起来符合预期了。目前的简单的解法可能是需要设置子节点高度之和 >= 父节点。算法里面的问题我回头排查下

**Comment by hengistchan** [comment]
好的感谢

**Comment by hengistchan** [comment]
是的，在点击展开最后一个子节点时，父节点和父节点的兄弟节点间才不会碰撞
