### ISSUE TITLE
调用afterlayout，返回undefined

### ISSUE THREAD

**Issue by guohaiping521** [antvis/G6#4071]
### 问题描述

![image](https://user-images.githubusercontent.com/15829415/202378998-216db6e4-9130-4b3f-84f9-d9ec8df0748e.png)
![image](https://user-images.githubusercontent.com/15829415/202379115-e76ee2f7-550c-4880-92d6-9d39fbc27d14.png)

### 重现链接

https://stackblitz.com/

### 重现步骤

如上面描述

### 预期行为

如上面描述

### 平台

macOS

**Comment by Yanyan-Wang** [comment]
这个事件的监听没有参数。你需要什么信息？原始需求是？

**Comment by guohaiping521** [comment]
![image](https://user-images.githubusercontent.com/15829415/202380686-98716398-5c5b-4148-8658-72573a340054.png)
我想后面这两个放到前面，所以想更新x,y的值

**Comment by Yanyan-Wang** [comment]
afterlayout 里面拿到 graph.getNodes() 每一项 node.getModel() 里面就有最新的 x y 了

**Comment by guohaiping521** [comment]
太感谢您了，还有一个小问题哈，如果我想每个节点的间距是一致的，但是现在有的节点 的name很长，就会影响下面节点的间距
![image](https://user-images.githubusercontent.com/15829415/202383034-3883d596-7909-4a8a-9cce-9d78df2519fe.png)
这个有什么直接的属性可以更改吗

**Comment by Yanyan-Wang** [comment]
内置节点，包括你这里用的 rect 类型，自身坐标系的原点在节点中央。因此每个节点的中央会对齐到它的 x y 上。如果你想要借点的左上角对齐到各自 x y 上面的话，需要自定义节点，在 addShape 的时候，各个图形的 x y 从 0 开始，这样意味着节点的原点在节点的左上角

**Comment by Yanyan-Wang** [comment]
先关闭了，新的问题另外开 issue 哈
