### ISSUE TITLE
文档错误：graph.downloadFullImage

### ISSUE THREAD

**Issue by auxshaw** [antvis/G6#4074]
### 问题描述

1、该方法的示例有误，给graph.downloadFullImage方法传了参数imageConfig，但没传参数type，导致传的参数imageConfig被当作参数type处理，进而导致报错。
![image](https://user-images.githubusercontent.com/43061495/202604956-b5c6174f-0195-4265-bb02-9cd9d13f3ae7.png)

2、似乎由于文档github仓库目录的变动，导致文档的"在GitHub编辑"按钮的跳转url有误，会跳到404页面
![image](https://user-images.githubusercontent.com/43061495/202605172-9c3354d3-816d-416e-b4b5-5e434638b639.png)

### 重现链接

https://g6.antv.vision/zh/docs/api/graphFunc/download#graphdownloadfullimagename-type-imageconfig

### 重现步骤

1. 访问https://g6.antv.vision/zh/docs/api/graphFunc/download#graphdownloadfullimagename-type-imageconfig
2. 复制graph.downloadFullImage的示例代码
3. 自行创建一个简单的Graph实例，并使用文档中graph.downloadFullImage的示例代码进行图片导出操作，会发现控制台报错。

4.点击导出图片标题右边的"在 GitHub 上编辑"图标，会跳转到404页面
![image](https://user-images.githubusercontent.com/43061495/202605172-9c3354d3-816d-416e-b4b5-5e434638b639.png)
![image](https://user-images.githubusercontent.com/43061495/202605355-9e372922-8de7-48f4-917f-c20178ec757c.png)

### 预期行为

期望文档示例正确，点击"在 GitHub 上编辑"图标跳转正常

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.7.13]

**Comment by Yanyan-Wang** [comment]
好的谢谢报告，会尽快更正

**Comment by Yanyan-Wang** [comment]
文档已修正
