### ISSUE TITLE
miniMap设了HGap但连接线依然有长有短

### ISSUE THREAD

**Issue by JiangGeGe123** [antvis/G6#4075]
### 问题描述

"@antv/g6": "^4.6.6",

![image](https://user-images.githubusercontent.com/9131591/202606503-4e93a7fc-a559-4b32-84cb-711600d3698f.png)
![image](https://user-images.githubusercontent.com/9131591/202606521-9f8cd65f-956c-49b3-b2f9-1cb8800e89ab.png)
什么原因？

### 重现链接

略

### 重现步骤

略

### 预期行为

相同层级在一个起点上，连接线长度相同

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome,]
- G6 版本: 4.6.6

**Comment by Yanyan-Wang** [comment]
getWidth 应该有所不同吧？
