### ISSUE TITLE
监听afterlayout方法，updateItem后，边没有进行更新

### ISSUE THREAD

**Issue by guohaiping521** [antvis/G6#4076]
### 问题描述

![image](https://user-images.githubusercontent.com/15829415/202647415-0055f5c7-67e3-401c-a897-32e261e10862.png)
![image](https://user-images.githubusercontent.com/15829415/202647528-05d84b45-a016-4341-afa2-46dcc42a80d9.png)

### 重现链接

https://stackblitz.com/

### 重现步骤

![image](https://user-images.githubusercontent.com/15829415/202647562-f0bf1f60-2a09-4ecf-8956-841bb9aaeda7.png)
结果如图2

### 预期行为

连接线不出现转折

### 平台

macOS

**Comment by Yanyan-Wang** [comment]
这个边的拐点是由布局计算出来的，可以更新一下相关边的 controlPoints。例如：
const diffX = newX - oldX;
node.getEdges().forEach(edge => {
  const currentControlPoints = edge.getModel().controlPoints;
  const newControlPoints = currentControlPoints.map(point => { 
    return {
      x: point.x - diffX,
      y: point.y
    };
 })
  graph.updateItem(edge, {
    controlPoints: newControlPoints
  })
})

可以按照你自己需求处理 controlPoints 的移动

**Comment by guohaiping521** [comment]
谢谢啦，按照您的方案，捣鼓了一下午，终于搞定了
