### ISSUE TITLE
🚀🚀🚀 新官网域名！超快der！A Faster New Website Domain！

### ISSUE THREAD

**Issue by Yanyan-Wang** [antvis/G6#4077]
### 问题描述

旧的官网域名访问缓慢，特别是在国内访问，简直上火上头，极大影响开发效率。
我们注册了新的域名，真的超级快！不信试试 🚀🚀🚀:

The loading speed of old domain of G6 slow down the developing process. We register a new website domain which is definitely faster and more stable:

中文：http://g6.antv.antgroup.com/
En：http://g6.antv.antgroup.com/en/

欢迎试用 + 右上角一键 Star 这个 G6 仓库！🚀🚀🚀
Welcome to try & star this repo on the top-right corner of this page 💪

### 重现链接

http://g6.antv.antgroup.com/

### 重现步骤

http://g6.antv.antgroup.com/

### 预期行为

http://g6.antv.antgroup.com/

### 平台

http://g6.antv.antgroup.com/

**Comment by Yanyan-Wang** [comment]
访问原 g6.antv.vision 域名将自动跳转到新域名

**Comment by ealldy** [comment]
还是很慢

**Comment by guidolx** [comment]
HI,
Just wanted to warn the users of G6. 
Beware of the following url looks like it is hosting an unofficial distribution which probably is malware.
https://g6-v3-2.antv.vision/en/docs/manual/advanced/custom-node/
