### ISSUE TITLE
自定义registerCombo 之后 设置modes ['drag-canvas','zoom-canvas' ]，无法拖拽combo区域去拖拽画布

### ISSUE THREAD

**Issue by klower** [antvis/G6#4079]
### 问题描述

自定义registerCombo 之后 设置modes ['drag-canvas','zoom-canvas' ]，无法拖拽combo区域去拖拽画布

### 重现链接

no

### 重现步骤

自定义registerCombo 之后 设置modes ['drag-canvas','zoom-canvas' ]，无法拖拽combo区域去拖拽画布

### 预期行为

自定义registerCombo 之后 设置modes ['drag-canvas','zoom-canvas' ]，可以拖拽combo区域去拖拽画布

### 平台

chrome

**Comment by Yanyan-Wang** [comment]
modes: {
  default: ['drag-canvas','zoom-canvas' ]
}

要在 combo 上拖拽画布，需要给 zoom-canvas 配置 allowDragOnItem，见文档 http://g6.antv.antgroup.com/manual/middle/states/defaultbehavior#drag-canvas
