### ISSUE TITLE
G6图片缩放的时候锯齿问题

### ISSUE THREAD

**Issue by Fadingvision** [antvis/G6#4081]
### Describe the bug

addShape('image') 图片缩放锯齿问题。
节点图片：
![image](https://user-images.githubusercontent.com/15011394/203281516-5b8ec8ce-8215-4e0d-ab44-697ed5e401bb.png)
原始图片：
![Ofac](https://user-images.githubusercontent.com/15011394/203284736-e56e4146-8fd5-4451-b947-ea89de1454d6.png)

### Your Example Website or App

null

### Steps to Reproduce the Bug or Issue

1. 通过addShape('image') 为节点添加图片，为了zoom的时候图片效果清晰，图片尺寸比节点大。
2. canvas缩放图片，导致锯齿严重。
3. 经过一番搜索[stackoverflow](https://stackoverflow.com/questions/17861447/html5-canvas-drawimage-how-to-apply-antialiasing/17862644#17862644)，尝试用下面的代码将`canvas`的`imageSmoothingQuality` 设为`high`, 但是每次设置完之后，重新布局这个值又被重置回`low`了。
```
const canvas = graph.get('canvas').cfg.el
const ctx = canvas.getContext('2d')
ctx.imageSmoothingQuality = 'high'
```

### Expected behavior

期望：
1. g6能够实现一个addShape图片缩小的算法，让大图缩小的时候不要有锯齿？
2. 能够默认将`imageSmoothingQuality`设为'high'，或者提供API选项控制？

### Platform

- OS: Windows
- Browser:chrome 107.0.5304.107
- Version:"@antv/g6": "^4.7.3",

**Comment by Yanyan-Wang** [comment]
> 尝试用下面的代码将 `canvas` 的 `imageSmoothingQuality` 设为 `high`

这个可以达到没有锯齿的效果吗？

我尝试设置后调用 graph.layout() 后打印 ctx.imageSmoothingQuality，似乎还是保持 high 的。可以提供一下你所说的重新布局会重置该值的 demo 吗？

**Comment by Fadingvision** [comment]
https://codesandbox.io/s/determined-lehmann-qo9l7s?file=/index.js 

@Yanyan-Wang 试下这个，我发现是因为调用了graph.changeSize方法就会导致context重置，不知道是不是这个方法内部重新初始化了context对象。
