### ISSUE TITLE
自定义节点的拖动问题

### ISSUE THREAD

**Issue by qtanran** [antvis/G6#4085]
### 问题描述

自定义的节点只有点击背景的时候才会触发拖动事件，而点击文字的时候却无法触发拖动事件。

### 重现链接

https://g6.antv.antgroup.com/zh/examples/tree/customItemTree/#customEdgeTree

### 重现步骤

1. 点击链接，进入页面
2. 在第 289 行增加 'drag-node'

### 预期行为

我期望我点击左侧的图片或文字区域也能触发 modes.default 中的交互事件

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.7.14]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/48440870/203522180-aa493709-66dc-4d53-b398-54dee8d319af.png)

**Comment by Yanyan-Wang** [comment]
自定义节点中需要响应拖拽的图形，在 addShape 的时候配置 draggable: true，和 attrs 平级。G6 默认只把 keyShape 设置了 draggable: true
