### ISSUE TITLE
节点重叠，连接线遮挡

### ISSUE THREAD

**Issue by guohaiping521** [antvis/G6#4088]
### 问题描述

![image](https://user-images.githubusercontent.com/15829415/203682919-da92ddef-894e-42b7-9428-5d7215c49745.png)
文案换行的时候，会出现节点重叠，连接线也会被遮挡
![image](https://user-images.githubusercontent.com/15829415/203683018-4e144936-e070-4c25-a0cb-830805dc50ff.png)
这个有什么好的解决方案吗,type 是dagre

### 重现链接

https://stackblitz.com/

### 重现步骤

如上图

### 预期行为

不重叠，自适应

### 平台

macOS

**Comment by Yanyan-Wang** [comment]
nodesepFunc 根据节点高度来返回？http://g6.antv.antgroup.com/api/graphlayout/dagre#layoutcfgnodesep

不行的话提供一下在线复现 demo

**Comment by guohaiping521** [comment]
只有内部需要换行的节点，才可能会出现重叠上面的情况，nodesepFunc 调整间距的话，我也不知道节点有没有重叠，我只能在重叠的时候才需要对其进行调整

**Comment by guohaiping521** [comment]
文案：【选做】李四\n(啦啦啦啦啦)\n(啦啦啦啦啦)\n(啦啦啦啦啦)
size: offsetWidth与offsetHeight计算

**Comment by guohaiping521** [comment]
![image](https://user-images.githubusercontent.com/15829415/203749523-480e93b3-d880-42dc-9ea2-7ea847626d40.png)
这样没问题
![image](https://user-images.githubusercontent.com/15829415/203749911-1723904b-5f03-4a17-a4db-3a5029af182d.png)
这样就有问题，因为有汇总节点

**Comment by Yanyan-Wang** [comment]
你可以在 nodesepFunc 中去判断当前节点数据中的文案有几行，来返回不同的高度。e.g.

nodesepFunc: nodeData => nodeData.label.split('\n').length * 14 

这里的换行逻辑计算方式根据自己的情况进行修改

**Comment by Yanyan-Wang** [comment]
汇总节点什么意思，给一下在线 demo
