### ISSUE TITLE
设置层级layer后，布局乱了

### ISSUE THREAD

**Issue by guohaiping521** [antvis/G6#4095]
### 问题描述

![image](https://user-images.githubusercontent.com/15829415/204092350-2ba12b41-8576-4239-ad4c-18c17118483b.png)
这是原先的样式，现如今想改成这种
![image](https://user-images.githubusercontent.com/15829415/204092374-f6156491-e57d-4a00-8ebe-3a4f03e6159a.png)
用afterlayout方法，调整node 的  x,y，发现调整了节点的x,y，连接线的x，y也要进行调整，之后发现上下间距也有问题，问题层出不穷，就放弃了这种方案
之后看文档中有layer这个属性，配置后发现，位置错乱了
![image](https://user-images.githubusercontent.com/15829415/204092485-4cbe8e3a-5518-4c36-b27b-ac4cb8d63121.png)
发现是每个节点的size不同造成的，有什么好的解决方式吗，困扰一周了，啊啊啊啊啊

### 重现链接

无

### 重现步骤

上述

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]
无

**Comment by Yanyan-Wang** [comment]
看起来好像没有什么问题？

**Comment by guohaiping521** [comment]
![image](https://user-images.githubusercontent.com/15829415/204177867-bacd14ca-1496-4004-82f1-c7cdb22ce0e3.png)
只是设置了层级，连接线应该和上面保持一致吧

**Comment by guohaiping521** [comment]
有什么方式可以和上面的保持一致吗，我只是想让张一与张8对齐，不想连接线也出错

**Comment by Yanyan-Wang** [comment]
考虑一下自定义折线：


G6.registerEdge(
  'custom-polyline',
  {
    getControlPoints(points) {
      const {startPoint, endPoint} = points;
      return [
        { x: (startPoint.x + endPoint.x) / 2, y: endPoint.y}
      ];
    },
  },
  'polyline',
);

也可以根据你的需求调整这里控制点，也就是弯折位置的逻辑
