### ISSUE TITLE
脑图能否实现节点之间的概括功能

### ISSUE THREAD

**Issue by lei28013** [antvis/G6#4098]
### 问题描述

脑图能否实现节点之间的概括功能

### 重现链接

https://g6.antv.antgroup.com/examples#tree-mindmap

### 重现步骤

脑图能否实现节点之间的概括功能

### 预期行为

脑图能否实现节点之间的概括功能

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
啥意思？需要更多描述

**Comment by lei28013** [comment]
![image](https://user-images.githubusercontent.com/5723504/207843150-d8ab89aa-a5a8-466e-9670-5c7f6136a240.png)
就是图中所标注的，对多节点的总结功能

**Comment by Yanyan-Wang** [comment]
因为它们不是节点也不是边，需要自己在画布上添加和管理这些图形。这里有一个 demo 给图上增加额外的图形，见 128 行：https://g6.antv.antgroup.com/examples/interaction/pagination/#treePagination
