### ISSUE TITLE
如何为combo指定位置

### ISSUE THREAD

**Issue by wuxt-dev** [antvis/G6#4101]
### 问题描述

无法为combo设置x，y值

### 重现链接

无

### 重现步骤

无

### 预期行为

需要实现将两个combo分别放置在画布左下角和右上角

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
graph.updateItem(combo, { x: xxx, y: yyy })

**Comment by wuxt-dev** [comment]
> graph.updateItem(combo, { x: xxx, y: yyy })

可是combo的配置项中不是没有x，y属性吗（试了一下没有效果）
![image](https://user-images.githubusercontent.com/87752447/204517527-fda37bc0-66c1-4c6d-a3fd-46dc0c0967ad.png)
