### ISSUE TITLE
自定义节点如何设置无边框，文本在下划线上

### ISSUE THREAD

**Issue by zcjpass** [antvis/G6#4102]
### 问题描述

TreeGraph mindmap 使用自定义节点
希望能达到下方截图这种效果，节点没有方框，只展示文本，但根据文本去设置labcfg 不生效

### 重现链接

无

### 重现步骤

无

### 预期行为

1

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

<img width="821" alt="企业微信截图_fa9af3b8-9602-4ec4-be7b-09b3a2772811" src="https://user-images.githubusercontent.com/40134043/204237491-8f51a822-14fa-4e8b-b58e-33eb9463c9ee.png">

目前的效果是这样的， 节点会卡在线中间，无法设置位置在上方，
<img width="465" alt="企业微信截图_dae4f3ed-a45f-4e6e-9dc2-8f6b9b658475" src="https://user-images.githubusercontent.com/40134043/204237825-82910ac3-3621-4790-82e6-9e151e08bffd.png">

**Comment by Yanyan-Wang** [comment]
自定义节点，参考 demo：
https://g6.antv.antgroup.com/examples/case/treeDemos/#indentedTree

**Comment by zcjpass** [comment]
> 

是说通过jsx 的方式自定义节点吗，目前我是使用的drawLabel那一套

**Comment by zcjpass** [comment]
> 自定义节点，参考 demo： https://g6.antv.antgroup.com/examples/case/treeDemos/#indentedTree

<img width="191" alt="image" src="https://user-images.githubusercontent.com/40134043/204557911-41447335-fcb7-4691-b22b-6ea8c0d5be5a.png">
请问点击编辑的时候会出现框跟文字重叠的情况，这种怎么处理

**Comment by zcjpass** [comment]
> 

<img width="629" alt="企业微信截图_3a1b4abc-2cb2-4246-a502-37cb5ee7b977" src="https://user-images.githubusercontent.com/40134043/205063732-18bcca25-61de-4173-901d-e35a30d44ba6.png">
<img width="569" alt="企业微信截图_949c4f6b-122c-4715-9aef-cc28f88d4268" src="https://user-images.githubusercontent.com/40134043/205063852-1a75fdd3-f22e-4cd9-882c-e0365d9a5d92.png">
当文本label的内容发生改变后，线会发生错乱， 调用refreshLayout()和changeData()也没起作用

**Comment by zcjpass** [comment]
> > 自定义节点，参考 demo： https://g6.antv.antgroup.com/examples/case/treeDemos/#indentedTree
> 
> <img alt="image" width="191" src="https://user-images.githubusercontent.com/40134043/204557911-41447335-fcb7-4691-b22b-6ea8c0d5be5a.png">
> 
> 请问点击编辑的时候会出现框跟文字重叠的情况，这种怎么处理

<img width="569" alt="企业微信截图_949c4f6b-122c-4715-9aef-cc28f88d4268" src="https://user-images.githubusercontent.com/40134043/205064185-6e9e7360-d303-40b3-a057-314c37734af2.png">

<img width="569" alt="企业微信截图_949c4f6b-122c-4715-9aef-cc28f88d4268" src="https://user-images.githubusercontent.com/40134043/205064191-9a8276da-6c80-45b8-8534-34403c60ad91.png">
当文本label的内容发生改变后，线会发生错乱， 调用refreshLayout()和changeData()也没起作用

**Comment by Yanyan-Wang** [comment]
> > 
> 
> 是说通过jsx 的方式自定义节点吗，目前我是使用的drawLabel那一套

不是啊，demo 里面有实现方法

**Comment by Yanyan-Wang** [comment]
> > 自定义节点，参考 demo： https://g6.antv.antgroup.com/examples/case/treeDemos/#indentedTree
> 
> <img alt="image" width="191" src="https://user-images.githubusercontent.com/40134043/204557911-41447335-fcb7-4691-b22b-6ea8c0d5be5a.png">
> 
> 请问点击编辑的时候会出现框跟文字重叠的情况，这种怎么处理

调整框大小和位置，或隐藏后面的文字

**Comment by Yanyan-Wang** [comment]
其他问题新开 demo 哈
