### ISSUE TITLE
单击后的效果——两个自定义的样式重叠

### ISSUE THREAD

**Issue by Glimpse597** [antvis/G6#4103]
### 问题描述

![image](https://user-images.githubusercontent.com/44827236/204412040-70fb8370-07f3-4116-af24-7566340ed139.png)
![image](https://user-images.githubusercontent.com/44827236/204412066-989d0acc-6e52-487b-80e4-b7479f557dcc.png)

### 重现链接

暂无

### 重现步骤

1.正常创建G6实例
2.就两个自定义shape继承于rect组成一个自定义节点 样式出问题

### 预期行为

单击和不单击都是如第三个

### 平台

- 操作系统: [ Windows]
- 网页浏览器: [Google Chrome, Edge]
- G6 版本: [4.7.14 ... ]

**Comment by Glimpse597** [comment]
![image](https://user-images.githubusercontent.com/44827236/204418714-4dab1ae8-09dd-40d8-a092-d8e34f9a480b.png)
![image](https://user-images.githubusercontent.com/44827236/204418745-5c33175f-919f-4fe9-93a6-b5087e476fed.png)
通过单击时响应状态变化不做处理可以避免该问题，但是我还是想了解下正确的解决办法

**Comment by Yanyan-Wang** [comment]
没有明白什么意思，哪两个东西重叠了？给一下在线复现的 demo 吧

**Comment by Glimpse597** [comment]
vue2
<div>
            <div id="flowchart"></div>
          </div>

import G6 from '@antv/g6'


  mounted() {
    this.initG6()
  },

  methods: {

    initG6() {
      var _that = this
      // 自定义节点（带删除按钮的长方形）
      G6.registerNode(
        'deletedRect',
        {
          afterDraw(cfg, group) {
            const x = 30
            const y = -20
            const bottomNode = group.addShape('rect', {
              attrs: {
                stroke: 'white',
                fill: 'white',
                x: x - 1,
                y: y - 4,
                width: 20,
                height: 20,
                zIndex: 0,
                capture: true,
                radius: 10,
                lineWidth: 1
              },
              name: 'deletedNode'
            })
            const deleteNode = group.addShape('path', {
              attrs: {
                stroke: '#000',
                zIndex: 2,
                path: [
                  ['M', 0 + x, 0 + y],
                  ['L', 10 + x, 10 + y],
                  ['M', 0 + x, 10 + y],
                  ['L', 10 + x, 0 + y]
                ],
                capture: true,
                lineWidth: 2
              },
              name: 'deletedNode'
            })
            return deleteNode, bottomNode
          },
        },
        'rect'
      )
      

      // 网格插件
      const grid = new G6.Grid()
      // 创建实例
      this.graph = new G6.Graph({
        container: 'flowchart',
        width: 1400,
        height: 450,
        scroller: {
          enabled: true,
          direction: 'x'
        },
        style: {
          overflow: 'auto'
        },
        modes: {
          default: [
            {
              type: 'drag-canvas', // 拖拽画布
              direction: 'x',
              scalableRange: -1
            },
            {
              type: 'scroll-canvas', // 拖拽画布
              direction: 'x',
              scalableRange: -1
            },
            // 'zoom-canvas', // 缩放画布
            'click-select' // 点击选中节点，再次点击节点或点击 Canvas 取消选中状态
            // 'activate-relations' // 当鼠标移到某节点时，突出显示该节点以及与其直接关联的节点和连线
          ]
        },
        // 节点
        defaultNode: {
          type: 'deletedRect',
          size: [100, 50],
          color: '#000',
          style: {
            fill: '#fff',
            lineWidth: 1,
            radius: 10
          },
          // 节点文字
          labelCfg: {
            style: {
              fill: '#40a9ff',
              fontSize: 16
            }
          }
        },
        // 连线
        defaultEdge: {
          style: {
            stroke: '#000',
            lineWidth: 1,
            endArrow: true
            // startArrow: true
          }
        },
        // 插件
        plugins: [grid]
      })


      // 读取数据
      this.graph.data(this.canvasData)
      // 渲染图
      this.graph.render()
    },
}

关于这流程图的代码 主要在于自定义节点的时候两个shape会有问题 单击节点再点击画布 导致自定义节点两个样式混乱了

**Comment by Yanyan-Wang** [comment]
同一个自定义节点中，尽量把图形的 name 设置成不同的哈，可能因为内部缓存样式使用 name 作为 key，所以相同 key 的 shape 可能拿不到正确的样式值。后面我在文档里面强调一下

**Comment by Yanyan-Wang** [comment]
文档已更新 https://g6.antv.antgroup.com/api/shapeproperties#name
