### ISSUE TITLE
双击节点，布局稳定

### ISSUE THREAD

**Issue by MinorN** [antvis/G6#4106]
### 问题描述

双击节点之后，从后端请求数据，加入到图中，但是不希望整体布局刷新，仅希望点击的节点以及新加入的节点进行布局

### 重现链接

none

### 重现步骤

none

### 预期行为

双击节点之后，从后端请求数据，加入到图中，但是不希望整体布局刷新，仅希望点击的节点以及新加入的节点进行布局

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome]

**Comment by Yanyan-Wang** [comment]
看是什么布局？如果是力导向，升级到最新版本，试用一下 force2 布局，应该会考虑上一次的布局结果。你也可以为已存在的节点数据增加 mass 值，相当于在布局中的质量更大，更不易被力影响。
如果是 dagre，应该默认会尽可能保持上一次结果。

具体的可以给出在线复现的 demo

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于我们没有得到可追踪复现的 demo，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
