### ISSUE TITLE
参照 文本超长 设置，节点信息展示不全了

### ISSUE THREAD

**Issue by Vivian-youyingying** [antvis/G6#4112]
### 问题描述

参照G6文档中的文本超长 进行设置，鼠标移入节点的时候，展示的节点label文字不全，都变成三个点了

### 重现链接

无

### 重现步骤

1、超长文本设置
2、鼠标移入，拿到节点信息，但是展示的节点信息不全

### 预期行为

我期望页面节点label能实现文本超长了，就溢出显示，然后鼠标移入事件中，我还能拿到完整的节点lebel信息。但是我现在通过G6文档中的文本超长 进行设置，节点信息就不全了。

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![1](https://user-images.githubusercontent.com/119553976/204971351-5649450d-131d-4911-82c3-808a6d9cb26f.png)
![2](https://user-images.githubusercontent.com/119553976/204971355-46ba3cc6-c5f1-45d3-b213-6abccfdb705b.png)
![3](https://user-images.githubusercontent.com/119553976/204971373-4440a28e-b985-43d4-8754-17a29298c22e.png)
![4](https://user-images.githubusercontent.com/119553976/204971381-8ce8426d-58c7-4526-bd7c-535854cfeda6.png)

**Comment by Yanyan-Wang** [comment]
缓存原始的 label 到数据上，mouseenter 的时候通过 graph.updateItem(e.item, { label: oriLabel }) 恢复，mouseleave 的时候变成省略的 graph.updateItem(e.item, {label: ellipsedLabel})

另外，gitee 域名网站更新有问题，现在可以访问新的域名了，速度很快 https://g6.antv.antgroup.com/zh/examples/item/label/#labelLen

**Comment by Vivian-youyingying** [comment]
缓存原始的 label 到数据上，怎么实现呢？
