### ISSUE TITLE
分别给两个circle类型combo设置上下padding，size变化不一致

### ISSUE THREAD

**Issue by wuxt-dev** [antvis/G6#4113]
### 问题描述

给一个combo设置上padding，另一个设置下padding，设置上padding的combo，size会变大，设置下padding的combo，size不变

### 重现链接

https://codepen.io/hao0yun/pen/poKOYBm

### 重现步骤

null

### 预期行为

两个combo变化一致

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
v4.7.17 已解决
