### ISSUE TITLE
>label 更改后节点和边位置会错乱

### ISSUE THREAD

**Issue by zcjpass** [antvis/G6#4114]
> 

<img width="629" alt="企业微信截图_3a1b4abc-2cb2-4246-a502-37cb5ee7b977" src="https://user-images.githubusercontent.com/40134043/205063732-18bcca25-61de-4173-901d-e35a30d44ba6.png">
<img width="569" alt="企业微信截图_949c4f6b-122c-4715-9aef-cc28f88d4268" src="https://user-images.githubusercontent.com/40134043/205063852-1a75fdd3-f22e-4cd9-882c-e0365d9a5d92.png">
当文本label的内容发生改变后，线会发生错乱， 调用refreshLayout()和changeData()也没起作用

_Originally posted by @zcjpass in https://github.com/antvis/G6/issues/4102#issuecomment-1333767102_

**Comment by Yanyan-Wang** [comment]
给个在线复现 demo？

**Comment by zcjpass** [comment]
> 给个在线复现 demo？

这个是使用自定义节点做的，将update设置为undefine 触发重新draw就可以了，但出现了个新问题，拖拽会不行

**Comment by Yanyan-Wang** [comment]
自定义节点中 addShape 的时候，给需要响应拖拽的图形增加 draggable: true ，和 attr、name 等平级

**Comment by zcjpass** [comment]
> 给个在线复现 demo？

没有在线demo，请教下为什么在update 里面调用 afterDraw就不会触发渲染更新呢，就会出现错乱的情况，将undefine设置为undefine触发draw就不会有这个问题，在draw每次都需要全局渲染，很影响性能

**Comment by Yanyan-Wang** [comment]
> > 给个在线复现 demo？
> 
> 没有在线demo，请教下为什么在update 里面调用 afterDraw就不会触发渲染更新呢，就会出现错乱的情况，将undefine设置为undefine触发draw就不会有这个问题，在draw每次都需要全局渲染，很影响性能

不同的生命周期，一般不会在 update 里面去调用 afterDraw 吧，就像你在 react 的 componentDidUpdate 里面不会去调用自己的 componentDidMount 一样。你说的问题，还是搞个在线 demo 吧，不然不清楚问题到底在哪里

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于我们没有得到可追踪复现的 demo，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
