### ISSUE TITLE
drag-canvas 与 zoom-canvas 行为冲突

### ISSUE THREAD

**Issue by ZENKI-CS** [antvis/G6#4115]
### 问题描述

```js
const defaultMode = [
    { 
        type:'drag-canvas',
        enableOptimize: true
    },
    { 
        type:'zoom-canvas',
        enableOptimize: true
    },
   // ...
]
```
drag-canvas 与 zoom-canvas 行为冲突，导致 drag-canvas 的 性能优化失效

### 重现链接

无

### 重现步骤

复现步骤：

1.内置行为 drag-canvas 与 zoom-canvas 同时使用 enableOptimize

2.构造 nodes 和 edges

3.【食指】按住鼠标【左键】开始拖动画布，观察 连线 和 非 keyShape 的 图形被隐藏

4.在拖动过程中，用【中指】滚动鼠标 【滚轮】出发 画布缩放，缩放结束后发现【被隐藏的连线 和 非 keyShape 图形】重新渲染出来了

### 预期行为

希望 在 复现步骤4 中， 缩放结束后【被隐藏的连线 和 非 keyShape 图形】仍然保持隐藏状态，直到 用户松开左键 才展示出来

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.7.16]

**Comment by Yanyan-Wang** [comment]
两个交互之间因为相互解耦，所以互相不会感知对方的状态。隐藏图形和显示图形的逻辑也一般会在各自交互开始和结束的时候被执行。所以好像没有很好的解法，这个操作也比较小众。看下社区同学有没有好的解法的建议
