### ISSUE TITLE
ToolBar的坐标位置配置能否灵活一些？

### ISSUE THREAD

**Issue by l-moondream** [antvis/G6#4118]
### 问题描述

使用ToolBar插件时，配置ToolBar的坐标位置，只支持{x,y}的形式，页面宽高变化时，怎样基于右上角|右下角|左下角定位呢？文档中没有说明，不知道是否支持。
![image](https://user-images.githubusercontent.com/53330236/205296214-b6bb3a9b-a83d-4e49-9af5-a06d979c2a52.png)

### 重现链接

https://g6.antv.antgroup.com/examples/tool/toolbar/#toolbar

### 重现步骤

无

### 预期行为

希望可以工具栏可以方便的配置位置

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome,]
- G6 版本: [4.6.18 ]

**Comment by Yanyan-Wang** [comment]
暂时不支持配置，欢迎社区共建。目前可以自己拿到 classname 是 g6-component-toolbar 的 DOM 改 CSS

**Comment by l-moondream** [comment]
谢谢回复，已通过改CSS实现

**Comment by l-moondream** [comment]
> 暂时不支持配置，欢迎社区共建。目前可以自己拿到 classname 是 g6-component-toolbar 的 DOM 改 CSS

谢谢回复，已通过改CSS样式实现
