### ISSUE TITLE
部分节点node:mouseenter事件不生效，tooltip提示框也不触发，

### ISSUE THREAD

**Issue by herohql521** [antvis/G6#4119]
### 问题描述

zoom-canvas 方法缩小放大之后，鼠标触控才会恢复正常。 测试20个点，左上方位置大约4-5个node 是无效的。

### 重现链接

xxxx

### 重现步骤

`<script setup lang="ts">
import { onMounted, ref } from 'vue'
import G6 from '@antv/g6'
import { useElementSize } from '@vueuse/core'
const mountNode = ref(null)
const { width, height } = useElementSize(mountNode)

const main = async () => {
  // 实例化 minimap 插件
  const minimap = new G6.Minimap({
    size: [100, 100],
    className: 'minimap',
    type: 'delegate'
  })

  const graph = new G6.Graph({
    container: 'mountNode',
    width: width.value,
    height: height.value,
    plugins: [minimap], // 将 minimap 实例配置到图上
    modes: {
      default: [
        // 'click-select',
        'drag-canvas',
        'zoom-canvas',
        // 'drag-node', // 允许拖拽画布、放缩画布、拖拽节点
        {
          type: 'tooltip', // 提示框
          formatText(model) {
            // 提示框文本内容
            const text = 'label: ' + model.label + '<br/> class: ' + model.class
            return text
          }
        }
      ]
    },
    layout: {
      // Object，可选，布局的方法及其配置项，默认为 random 布局。
      type: 'force', // 指定为力导向布局
      nodeSpacing: 30,
      // rankdir: 'LR',
      preventOverlap: true // 防止节点重叠
      // nodeSize: 30        // 节点大小，用于算法中防止节点重叠时的碰撞检测。由于已经在上一节的元素配置中设置了每个节点的 size 属性，则不需要在此设置 nodeSize。
    },
    defaultNode: {
      size: 30, // 节点大小
      // ...                 // 节点的其他配置
      // 节点样式配置
      style: {
        fill: 'skyblue', // 节点填充色
        stroke: 'yellow', // 节点描边色
        lineWidth: 1 // 节点描边粗细
      },
      // 节点上的标签文本配置
      labelCfg: {
        // 节点上的标签文本样式配置
        style: {
          fill: '#fff', // 节点标签文字颜色
          fontSize: 18
        }
      }
    },
    defaultEdge: {
      // ...                 // 边的其他配置
      // 边样式配置
      style: {
        opacity: 0.6, // 边透明度
        stroke: 'grey' // 边描边颜色
      },
      // 边上的标签文本配置
      labelCfg: {
        autoRotate: true // 边上的标签文本根据边的方向旋转
      },
      fontSize: 22
    },
    // 节点不同状态下的样式集合
    nodeStateStyles: {
      // 鼠标 hover 上节点，即 hover 状态为 true 时的样式
      hover: {
        fill: 'lightsteelblue'
      },
      // 鼠标点击节点，即 click 状态为 true 时的样式
      click: {
        stroke: '#000',
        lineWidth: 3
      },
      selected: {
        fill: 'green',
        stroke: 'red'
      }
    },
    // 边不同状态下的样式集合
    edgeStateStyles: {
      // 鼠标点击边，即 click 状态为 true 时的样式
      click: {
        stroke: 'steelblue'
      }
    }
  })
  const response = await fetch(
    'https://gw.alipayobjects.com/os/basement_prod/6cae02ab-4c29-44b2-b1fd-4005688febcb.json'
  )
  const remoteData = await response.json()
  const nodes = remoteData.nodes
  nodes.forEach((node) => {
    switch (
      node.class // 根据节点数据中的 class 属性配置图形
    ) {
      case 'c0': {
        node.type = 'circle' // class = 'c0' 时节点图形为 circle
        break
      }
      case 'c1': {
        node.type = 'rect' // class = 'c1' 时节点图形为 rect
        node.size = [80, 90] // class = 'c1' 时节点大小
        break
      }
      case 'c2': {
        node.type = 'ellipse' // class = 'c2' 时节点图形为 ellipse
        node.size = [120, 120] // class = 'c2' 时节点大小
        break
      }
    }
  })

  // 遍历边数据
  const edges = remoteData.edges
  edges.forEach((edge) => {
    if (!edge.style) {
      edge.style = {}
    }
    edge.style.lineWidth = edge.weight // 边的粗细映射边数据中的 weight 属性数值
  })

  graph.data(remoteData)
  graph.render()

  // 鼠标进入节点
  graph.on('node:mouseenter', (e) => {
    const { item }: any = e // 获取鼠标进入的节点元素对象
    graph.setItemState(item, 'hover', true) // 设置当前节点的 hover 状态为 true
  })

  // 鼠标离开节点
  graph.on('node:mouseleave', (e) => {
    const nodeItem: any = e.item // 获取鼠标离开的节点元素对象
    graph.setItemState(nodeItem, 'hover', false) // 设置当前节点的 hover 状态为 false
  })

  // 点击节点
  graph.on('node:click', (e) => {
    // 先将所有当前是 click 状态的节点置为非 click 状态
    const clickNodes = graph.findAllByState('node', 'click')
    clickNodes.forEach((cn) => {
      graph.setItemState(cn, 'click', false)
    })
    const nodeItem: any = e.item // 获取被点击的节点元素对象
    console.log(e?.item?._cfg?.id)
    graph.setItemState(nodeItem, 'click', true) // 设置当前节点的 click 状态为 true
  })

  // 点击边
  graph.on('edge:click', (e) => {
    // 先将所有当前是 click 状态的边置为非 click 状态
    const clickEdges = graph.findAllByState('edge', 'click')
    clickEdges.forEach((ce) => {
      graph.setItemState(ce, 'click', false)
    })
    const edgeItem: any = e.item // 获取被点击的边元素对象
    graph.setItemState(edgeItem, 'click', true) // 设置当前边的 click 状态为 true
  })

  //点空白
  // graph.on('canvas:click', (ev) => {
  //   const clickNodes = graph.findAllByState('node', 'click')
  //   const clickEdges = graph.findAllByState('edge', 'click')
  //   clickNodes.forEach((cn) => {
  //     graph.setItemState(cn, 'click', false)
  //   })
  //   clickEdges.forEach((cn) => {
  //     graph.setItemState(cn, 'click', false)
  //   })
  // })

  // 当 click-select 选中的元素集合发生变化时将会触发下面时机事件，evt 中包含相关信息
  // graph.on('nodeselectchange', (e) => {
  //   // 当前操作的 item
  //   console.log(e.target)
  //   // 当前操作后，所有被选中的 items 集合
  //   console.log(e.selectedItems)
  //   // 当前操作时选中(true)还是取消选中(false)
  //   console.log(e.select)
  // })
}

onMounted(() => {
  main()
})
</script>`

### 预期行为

应该所有node都可以鼠标触控，而不是大部分好使，小部分无效

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by gefeiyanga** [comment]
+1  g6-react-node 中 onMouseEnter不生效，原因好像是
![image](https://user-images.githubusercontent.com/30728843/205586280-99b74800-6a9e-4173-b36a-cd8abe88b9d6.png)

**Comment by Yanyan-Wang** [comment]
给个在线 demo？copy 到官网上没有复现。左上角有问题的话是不是上层有 dom 遮挡？

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于我们没有得到可追踪复现的 demo，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。

**Comment by JoeWrights** [comment]
遇到同样的问题，缩放画布后部分节点的tooltip hover不显示，而且节点的hover样式也没出来

**Comment by git-hongxia** [comment]
> 遇到同样的问题，缩放画布后部分节点的tooltip hover不显示，而且节点的hover样式也没出来

改了没，咋改的？
