### ISSUE TITLE
紧凑树节点间水平间距如何自适应

### ISSUE THREAD

**Issue by donghuizhou** [antvis/G6#4120]
### 问题描述

下图中的是左右布局的紧凑树，原本需求是自定义节点图形的宽度是固定的，所以节点间水平间距能较好地控制（通过`getHGap` 方法）。
但是现在需求改为了自定义节点的宽度随文本内容自适应，想问节点间水平间距如何自适应
![1670234446392](https://user-images.githubusercontent.com/31002949/205609239-69a5f649-d3ff-4d28-b53b-f86472d026c8.png)

### 重现链接

none

### 重现步骤

如上

### 预期行为

节点间水平间距自适应

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
getHGap 根据文本长度返回不同值呢？
