### ISSUE TITLE
鼠标移入之后怎么给节点label 加方框

### ISSUE THREAD

**Issue by zcjpass** [antvis/G6#4123]
### 问题描述

<img width="187" alt="image" src="https://user-images.githubusercontent.com/40134043/205923991-9b7ac2d7-199d-424e-8ab3-1c8f0955b116.png">
请问如何可以达到这个效果，鼠标移入之后给节点label 加上方框
<img width="721" alt="企业微信截图_363625d7-f70e-4664-afc4-160fe5ccebb4" src="https://user-images.githubusercontent.com/40134043/205924320-35682b53-fff4-4291-bad3-df36938549a0.png">
尝试增加rect,但不生效，求指导

### 重现链接

无

### 重现步骤

无

### 预期行为

如上面图片所示

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Fadingvision** [comment]
你在事件里面加边框肯定不行吧，应该在draw里面加，然后根据状态判断是否显示

**Comment by zcjpass** [comment]
> 你在事件里面加边框肯定不行吧，应该在draw里面加，然后根据状态判断是否显示

在afterdraw里面加吗，可是状态变化并不会触发draw 或者afterDraw吧

**Comment by Fadingvision** [comment]
> > 你在事件里面加边框肯定不行吧，应该在draw里面加，然后根据状态判断是否显示
> 
> 在afterdraw里面加吗，可是状态变化并不会触发draw 或者afterDraw吧

@zcjpass 状态变化在setState里面去设置，可以先在draw里面画一个透明的或者宽度为0的矩形边框，然后再setState里面响应状态变化，只需要改边框的颜色就行了

**Comment by Yanyan-Wang** [comment]
楼上正解。提前在 draw 方法里面定义好图形，并 opacity: 0 。如果继承了内置的节点，就会继承 setState，这样你可以在图实例的 nodeStateStyles 里面定义一个状态的样式，node:mouseenter 和 node:mouseleave 的时候 graph.setItemState 来控制状态，nodeStateStyles 里面对应的样式就会作为响应。如果没有继承内置节点，就要自己实现 setState，捕获状态的变化，做出不同响应，比如 'active' 状态为 true 时，将提前定义好的方框图形 opacity: 1

状态最佳实践文档：http://g6.antv.antgroup.com/manual/advanced/state-new
