### ISSUE TITLE
双击节点之后，所有节点都无法拖拽，并且报错

### ISSUE THREAD

**Issue by zhangqi11** [antvis/G6#4124]
### Describe the bug

双击其中一个节点，整个界面无法拖拽，里面的节点也无法拖拽，并且报如下错误：
![image](https://user-images.githubusercontent.com/26050832/206124588-a47547c3-75f2-4eb6-a23b-0c45f27caccb.png)

### Your Example Website or App

Website

### Steps to Reproduce the Bug or Issue

1.双击节点
2.界面和界面无法拖动，并且报错

### Expected behavior

无

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
给一个在线复现的 demo？

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于我们没有得到可追踪复现的 demo，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
