### ISSUE TITLE
lable 修改内容后，调用layout 后线不会更新，导致错乱

### ISSUE THREAD

**Issue by zcjpass** [antvis/G6#4125]
### 问题描述

<img width="524" alt="企业微信截图_335cfda0-410b-42ff-9577-7121707919b1" src="https://user-images.githubusercontent.com/40134043/206149570-fab8587d-8c74-4db3-aa86-12877e66659a.png">

编辑文本，调用graph.layout(fasle), 布局并不会更新，如上图，线的位置没变

### 重现步骤
const config = {
    
      draw: (cfg, group) => {
        const { id, label, collapsed, selected, children, depth } = cfg;
        const rootNode = depth === 0;
        const hasChildren = children && children.length !== 0;
        console.log('test111', 111)
        const {
          childCountWidth,
          countMarginLeft,
          itemPadding,
          selectedIconWidth,
          nameMarginLeft,
          rootPadding,
        } = BaseConfig;

        let width = 0;
        const height = 42;
        const x = 0;
        const y = -height / 2;

        // 名称文本
        const text = group.addShape('text', {
          attrs: {
            text: optimizeMultilineText(label, '', '3', maxWidth),
            // text: label,
            x: x * 2,
            y,
            textAlign: 'center',
            textBaseline: 'top',
            fontFamily: 'PingFangSC-Regular',
          },
          cursor: 'pointer',
          className: 'node-label1',
          draggable: true,
        });
        const textWidth = text.getBBox().width;
        width = textWidth + itemPadding + nameMarginLeft;
        width = width < minWidth ? minWidth : width;

        if (!rootNode) {
          if(hasChildren) {
            width += countMarginLeft;
            width += childCountWidth;
          } else {
            // width += countMarginLeft;
          }
        } 
        const labelWidth = G6.Util.getTextSize(cfg.label, BaseConfig.nameFontSize)[0];
        let highLevel = parseInt(labelWidth/maxTextLength)
        // console.log('text', textWidth, label, width, highLevel, labelWidth)
        if (width > maxWidth + 20) {
          width = maxWidth
        }
        if (highLevel >= 3) {
          highLevel = 2
        }

        cfg.width = width;
        cfg.height = height;
        cfg.highLevel = highLevel;

        const keyShapeAttrs = {
          x,
          y,
          width,
          height,
          radius:2
        };

        // keyShape根节点选中样式
        if (rootNode && selected) {
          keyShapeAttrs.fill = '#e8f7ff';
          keyShapeAttrs.stroke = '#e8f7ff';
        }
        const keyShape = group.addShape('rect', {
          attrs: keyShapeAttrs,
          className: 'root-shape',
          draggable: true,
        });

        if (!rootNode) {
          group.addShape('path', {
            attrs: {
              path: [
                ['M', x - 1, 0],
                ['L', width, 0],
              ],
              stroke: '#AAB7C4',
              lineWidth: 2,
            },
            className: 'node-path-shape',
            draggable: true,
          });
        }
        const mainX = x - 10;
        const mainY = -height + 15;

        if (rootNode) {
          group.addShape('rect', {
            attrs: {
              x: mainX,
              y: mainY,
              width: width + 20,
              height: height + 10,
              radius: 4,
              fill: '#e8f7ff',
              cursor: 'pointer',
            },
            className: 'main-shape',
          });
        }

        let nameColor = 'rgba(0, 0, 0, .65)';
        if (selected) {
          nameColor = '#40A8FF';
        }
        // 名称
        if (rootNode) {
          console.log('rootText', width)
          group.addShape('text', {
            attrs: {
              text: optimizeMultilineText(label, '', '3', 250),
              x: mainX + rootPadding,
              y: 1,
              textAlign: 'left',
              textBaseline: 'middle',
              fill: nameColor,
              fontSize: 14,
              fontFamily: 'PingFangSC-Regular',
              cursor: 'pointer',
            },
            className: 'root-text-shape',
            draggable: true,
          });
        } else {
          let textX = 0
          if(cfg.side === "left") {
            textX = x + 50;
          } else {
            textX = mainX + 2
          }
          group.addShape('text', {
              attrs: {
                text: optimizeMultilineText(label, '', '3', maxWidth),
                // text: label,
                x: textX ,
                y: y + 2 - highLevel * 14,
                textAlign: 'left',
                textBaseline: 'top',
                fill: nameColor,
                fontSize: 14,
                fontFamily: 'PingFangSC-Regular',
                cursor: 'pointer',
              },
              className: 'node-label',
              draggable: true,
            });
            cfg.textX = textX
          }
        return keyShape
      },
      update(model, group) {
            
      },

      getAnchorPoints() {
        return [
            [0, 0.5],
            [1, 0.5],
          ];
      },
    };

这是我的draw()方法

let tmpConfig =  {
        
        afterDraw(cfg, group) {
            const item = group.cfg.item;
            let model
            try {
                model = item.getModel();
            } catch (e) {
                console.log('eee', e)
                // return
            }
           if(model.isRoot) {
            return;
           }
          
            const label = group.findByClassName('node-label');
          
            const labelBox = label.getBBox();
            // console.log('labelBox', model.label, labelBox)
            let width = labelBox.width;
            const { height } = labelBox;
            width = width + BaseConfig.itemPadding + BaseConfig.nameMarginLeft;
            width = width < minWidth ? minWidth : width;
            if (!model.isRoot) {
              if(model.children && model.children?.length > 0) {
                width += BaseConfig.countMarginLeft;
                width += BaseConfig.childCountWidth;
              } else {
                // width += countMarginLeft;
            }
        }
            if (width > maxWidth) {
              width = maxWidth
            }
            // const x = -width / 2;
            // const y = -height / 2;
            const labelWidth = G6.Util.getTextSize(cfg.label, BaseConfig.nameFontSize)[0];
            let highLevel = parseInt(labelWidth/maxTextLength)
            if (highLevel > 3) {
              highLevel = 3
            }
            let x = -35
            if(cfg.side === 'left') {
              x = -5
            } else {
              if(model.parent === nodeId) {
                x = -25
              }
            }

           
            const y = (-42 / 2) + 2 - highLevel * 14
            

            const { type, collapsed, children, caseRes, priority, imageList, caseSelect, multiCaseRes, filterRes, isRecommand } = model;
            
            if (children && children.length > 0) {
                if(!(children.length === 1 && children[0].id === "add_node")) {
                    group.addShape('image', {
                        className: collapse_class_name,
                        draggable: true,
                        attrs: {
                            img: collapsed ? PLUS_URL : MINUS_URL,
                            x: x -  ICON_SIZE ,
                            y: y ,
                            width: ICON_SIZE,
                            height: ICON_SIZE,
                            style: 'cursor: pointer',
                        },
                    });
                }
            }
            this.setLabelText(model, group);
        },

这是我的afterDraw()方法

自定义节点

 <Fragment>
            <RegisterNode name="mind-base" config={config} />
            <RegisterNode name="custom-node" config={tmpConfig} extend = "mind-base"  />
 </Fragment>

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

<img width="524" alt="企业微信截图_335cfda0-410b-42ff-9577-7121707919b1" src="https://user-images.githubusercontent.com/40134043/206151355-e47294a9-4869-402c-a166-49266f958739.png">

**Comment by Yanyan-Wang** [comment]
给一个在线复现的 demo？

**Comment by zcjpass** [comment]
> 给一个在线复现的 demo？

没有在线的，不懂怎么弄个在线demo,不好意思哈，麻烦辛苦看下代码？

**Comment by zcjpass** [comment]
> 给一个在线复现的 demo？

看了下，节点的位置坐标是更新了的，但边没有跟着更新

**Comment by Yanyan-Wang** [comment]
> 给一个在线复现的 demo？

把你代码放到  https://codesandbox.io/dashboard/recent?workspace=48f77660-106a-4df1-9b1a-d5635c4bb3a4

你这里贴一串代码文本没法看

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于我们没有得到可追踪复现的 demo，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
