### ISSUE TITLE
updateLayout之后重新render, graph.destroy报错

### ISSUE THREAD

**Issue by Fadingvision** [antvis/G6#4126]
### 问题描述

复现demo: https://codesandbox.io/s/elegant-chatelet-ghkj6g?file=/index.js

![image](https://user-images.githubusercontent.com/15011394/206167388-fcdac05a-e350-4e0b-ab4c-466405ba7742.png)
这样写会报错
```js
graph.on('afterrender', async () => {
                
                    console.log('afterrender')
                    this.graph.updateLayout({
                        animate: true
                    })
            })
```

如果放到setTimeout里面执行就是正常的
```js
graph.on('afterrender', async () => {
                
                setTimeout(() => {
                    console.log('afterrender')
                    this.graph.updateLayout({
                        animate: true
                    })
                }, 0)
            })

```
### 重现链接

 https://codesandbox.io/s/elegant-chatelet-ghkj6g?file=/index.js

### 重现步骤

见demo

### 预期行为

不报错

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
v4.8.0 已修复
