### ISSUE TITLE
![image](https://user-images.githubusercontent.com/1481188/205837320-f1715abd-e60b-48ab-a455-397a176a3357.png)

### ISSUE THREAD

**Issue by gplin** [antvis/G6#4127]
![image](https://user-images.githubusercontent.com/1481188/205837320-f1715abd-e60b-48ab-a455-397a176a3357.png)

"@antv/g6": "^4.7.16",

_Originally posted by @gplin in https://github.com/antvis/G6/discussions/4122_

**Comment by simplejason** [comment]
Can you check if you have installed `dagre-compound` in your project? Or remove node_modules and try to excute `npm i` again
