### ISSUE TITLE
轮廓包裹可否支持标签之类的属性,显示在轮廓边缘或者中间

### ISSUE THREAD

**Issue by Aicmortal** [antvis/G6#4130]
### 问题描述

轮廓包裹可否支持标签之类的属性,显示在轮廓边缘或者中间

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
暂不支持，欢迎社区共建～
