### ISSUE TITLE
请问可以支持文本主动换行吗，比如ctrl + enter 换行

### ISSUE THREAD

**Issue by zcjpass** [antvis/G6#4131]
### 问题描述

请问可以支持文本主动换行吗，比如ctrl + enter 换行

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
给文本加换行符即可 http://g6.antv.antgroup.com/examples/item/label/#labelLen1

**Comment by zcjpass** [comment]
> 给文本加换行符即可 http://g6.antv.antgroup.com/examples/item/label/#labelLen1

主动换行怎么实现呢，想要实现ctrl + enter 换行
