### ISSUE TITLE
在combo默认关闭下，点击打开combo，combo会跳。打开动画，是一个过渡效果

### ISSUE THREAD

**Issue by person001** [antvis/G6#4133]
### 问题描述

https://codesandbox.io/s/aged-waterfall-88pflq?file=/index.js

### 重现链接

https://codesandbox.io/s/aged-waterfall-88pflq?file=/index.js

### 重现步骤

双击打开combo，combo会向下跳一格

### 预期行为

在原来位置打开

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
没有看懂你这个 demo 怎么复现你的问题啊？

**Comment by person001** [comment]
https://codesandbox.io/s/aged-waterfall-88pflq?file=/index.js
@Yanyan-Wang 不好意思，之前的demo没有写全。现在可以了，直接点击单个combo既可以复现，谢谢大佬

**Comment by Yanyan-Wang** [comment]
> https://codesandbox.io/s/aged-waterfall-88pflq?file=/index.js @Yanyan-Wang 不好意思，之前的demo没有写全。现在可以了，直接点击单个combo既可以复现，谢谢大佬

这个 demo 还是没变化啊，单击也没有效果，你是不是修改了没保存？

**Comment by person001** [comment]
https://codesandbox.io/s/priceless-tesla-kpuqt9?file=/index.js @Yanyan-Wang 不好意思，确实没有保存，重新保存了一下，麻烦大佬看一下。

**Comment by Yanyan-Wang** [comment]
可以给图实例配置 animate: true 打开动画。这儿为什么通过 updateLayout 和 onLayoutEnd 来设置布局？图实例上可以配置 layout，如果想要一个随机的预布局可以给 layout 里面配置 preset:{ type: 'random' }。但是不配置这个其实初始化也是 random。可以设置成别的 preset
