### ISSUE TITLE
dagre 布局是否可以支持居中

### ISSUE THREAD

**Issue by xuoutput** [antvis/G6#4135]
### 问题描述

![image](https://user-images.githubusercontent.com/16385443/203935939-a6671bb2-a940-4a97-90bb-33779b5ec123.png)
是否可以支持, 画布左右居中, 上下居中的配置

### 重现链接

无

### 重现步骤

是否可以支持, 画布左右居中, 上下居中的配置

### 预期行为

是否可以支持, 画布左右居中, 上下居中的配置

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.7.15 ... ]

**Comment by Yanyan-Wang** [comment]
给图实例配置 fitCenter: true 或者 fitView: true

**Comment by xuoutput** [comment]
> fitView: true

`fitView: true` 是 autozoom 功能, 图片自适应展示了
`fitview` 是 自动适配画布大小 这个看效果是不 autozoom 的居中, 不缩小, 但视图还是在图片中间, 看起来怪怪的

https://codesandbox.io/s/fitview-rweo7q
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/16385443/211248447-207e9326-704e-4254-a06d-5560f038dabb.png">

**Comment by Aarebecca** [comment]
目前 dagre 布局已经与 `dagre.js` 对其，相关可配置项请参考： https://github.com/dagrejs/dagre/wiki
