### ISSUE TITLE
自定义节点宽度不等时，如何保持父子层级间距相同

### ISSUE THREAD

**Issue by donghuizhou** [antvis/G6#4136]
### 问题描述

如下图所示，截了官网一张示例，在自定义节点宽度不一致时，如何保持各父子层级间距相同，不然有的长，有的短的，体验不好
![image](https://user-images.githubusercontent.com/31002949/207212376-45f20be3-067e-4f19-9952-610e06471fb2.png)

### 重现链接

无

### 重现步骤

https://g6.antv.antgroup.com/examples/tree/customItemTree/#customTree 可参考官网实例

### 预期行为

希望各父子层级间距一致

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
compactBox 布局配置 

getWidth: function getWidth(d) {
      return G6.Util.getTextSize(d.id, 15)[0];
    },

**Comment by donghuizhou** [comment]
我试下，感谢
