### ISSUE TITLE
元素很多时 downloadFullImage 导出图片失败

### ISSUE THREAD

**Issue by yxc1** [antvis/G6#4137]
### 问题描述

https://github.com/antvis/G6/issues/2980 https://github.com/antvis/G6/issues/3675 查看了这两个issues 已经关闭了，但项目中数据量大导出图片还是会报错。
g6 版本：4.7.11
浏览器版本： chrome 108.0.5359.98
layout.type: compactBox 树
节点数量： 500+
每个节点高宽：width：200 height：100
container入器高宽: html宽高 , 可拖动和缩放
导出图片时,会报错

### 重现链接

无

### 重现步骤

layout.type: compactBox 树
节点数量： 500+
每个节点高宽：width：200 height：100
渲染正常，导出图片有时能成功,但是图片打不开,有时就会报错.

### 预期行为

导出图片正常

### 平台

- 操作系统: [macOS, Windows]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.7.11 ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/86400488/207240645-023230f7-68fe-4dc1-a258-53f8ebd968bf.png)
![image](https://user-images.githubusercontent.com/86400488/207240753-16287dd0-d9d9-4d1e-9566-2de467062476.png)

### 补充说明（可选）

目前的解决办法是 graph.zoomTo(0.1) 缩放到0.1倍,图片能正常下载,但是实在是太模糊.

**Comment by donghuizhou** [comment]
你导出的是什么格式，如果是png的话，试试jpeg格式

**Comment by yxc1** [comment]
> 你导出的是什么格式，如果是png的话，试试jpeg格式

没有用,换成其他格式的也会报错.    缩放到0.1再下载的,什么格式都模糊.没用的...........

**Comment by Yanyan-Wang** [comment]
缩放以后，调大 pixelRatio，如 graph.get('canvas').set('pixelRatio', 5)，再下载。下载完成后调整回去（在次之前缓存原始 pixelRatio graph.get('canvas').get('pixelRatio')）

**Comment by yxc1** [comment]
> graph.get('canvas').set('pixelRatio', 5)

感谢回复。但是按您的方法试了,没有什么作用......

**Comment by JoeWrights** [comment]
我这边遇到了相同的问题 
![image](https://user-images.githubusercontent.com/38278949/216013140-e2b7152c-496b-4b8f-9fe4-6b6daf8edbb8.png)
在Firefox下会报错，但是在Chrome下是正常的，Chrome版本为：108.0.5359.124 (正式版本)

**Comment by keminu** [comment]
同样的问题，图片太大下载不了
