### ISSUE TITLE
不同层级的子节点如何避让

### ISSUE THREAD

**Issue by donghuizhou** [antvis/G6#4138]
### 问题描述

如下图所示，相同父级的节点，他们的子节点展开时，会相互避让，不同父级的节点，他们的子节点展开时，线和节点会重叠，这个问题怎么处理呢
![image](https://user-images.githubusercontent.com/31002949/207255403-8f56381e-8719-4fcd-b86d-41695dfeb54f.png)

### 重现链接

https://codesandbox.io/s/rg0uf4?file=/index.js

### 重现步骤

进页面查看

### 预期行为

希望不同父级的节点，他们的子级展开时，会相互避让

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
可以换成 mindmap，参数相应调整下
