### ISSUE TITLE
版本升级后，自定义节点间连线展现形式不同

### ISSUE THREAD

**Issue by xlslucky** [antvis/G6#4140]
### 问题描述

4.7.5，连线正常显示
4.7.16，连线的开始、结束距离节点有间隙，在4.7.16版本把lineWidth删除，就不会有这个问题
代码
<img width="497" alt="image" src="https://user-images.githubusercontent.com/17557871/207491877-c5f888b0-13d7-4dba-b84f-2b294b2bb3c3.png">
4.7.5
<img width="242" alt="QQ20221213-205733@2x" src="https://user-images.githubusercontent.com/17557871/207491994-b0a29fb5-1a8f-474a-ac0a-5209507fde84.png">
4.7.16
<img width="202" alt="QQ20221213-205757@2x" src="https://user-images.githubusercontent.com/17557871/207492038-40f075a4-ad57-40a0-bd53-2053739fb130.png">

### 重现链接

无

### 重现步骤

如描述

### 预期行为

期望4.7.16以后版本，在设置lineWidth的情况下，连线和节点之间没有间隙，或者有其他的办法解决这个间隙

尝试把lineWidth改成stroke，是不会出现间隙了，但是视觉体验没有lineWidth好

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
给个在线复现 demo，这样看不出来问题在哪里。这个连线位置是根据 keyShape 的 bbox 来决定的，看下你的 keyShape 是哪个图形

**Comment by xlslucky** [comment]
https://codesandbox.io/s/festive-monad-xvdlxg
@Yanyan-Wang 线上demo，辛苦看一下，在4.7.11和4.7.12版本之间切换就能看到区别。
如果不算是bug，麻烦帮指出应该怎么修改才不会出现这个间隙。

**Comment by Yanyan-Wang** [comment]
lineWidth 的值是数字，你这里给的字符串 '3' '1'

**Comment by xlslucky** [comment]
改成数字类型了，感谢
