### ISSUE TITLE
节点拖拽bug

### ISSUE THREAD

**Issue by Arthre** [antvis/G6#4141]
### 问题描述

当画布容器的兄弟被选中时，再去拖拽节点就会出现的bug。

### 重现链接

https://codesandbox.io/s/blue-cdn-7m4zws?file=/src/App.vue

### 重现步骤

1. 选中左上角的无序列表、或者按下ctrl+a
2. 拖拽节点

### 预期行为

期望的结果：当我拖拽节点松开鼠标后，节点应该停止在我松开鼠标的地方

实际的结果：当我拖拽节点松开鼠标后，节点任跟随着鼠标移动，当我再次点击时才停止鼠标的跟随。然后拖拽任何节点时都没有反应了。当点击页面空白的地方后又能再次拖拽了。

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome 版本 108.0.5359.99（正式版本） （64 位）]
- G6 版本: [4.7.13]

**Comment by 54zhaojing** [comment]
请问找到解决方法了吗？

**Comment by Aarebecca** [comment]
根据你反馈的复现Demo，暂未发现相关异常。如果仍然存在问题，请提供更多细节。
