### ISSUE TITLE
comboId字段无法自定义吗?

### ISSUE THREAD

**Issue by Aicmortal** [antvis/G6#4144]
### 问题描述

comboId字段无法自定义吗?,如果后端返回的数据不同,数据多的话,前端遍历一遍添加修改属性会又不必要的性能支出
![微信截图_20221215175943](https://user-images.githubusercontent.com/16420004/207829965-ca80acce-8bd7-40f1-8b94-827a58c014c8.png)

### 重现链接

https://g6.antv.antgroup.com/manual/middle/elements/combos/defaultcombo

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
不支持，这些字段都是固定的
