### ISSUE TITLE
关于combocombined布局，元素坐标不生效的问题

### ISSUE THREAD

**Issue by weimengdexiaolaohu-8** [antvis/G6#4145]
### 问题描述

layout:
  type:'combocombined',
preventNodeOverlap:true,
spacing:10,
outerLayout:new G6.Layout['dagre']({
rankdir:"LR",
nodesep:100,
ranksep:100
}),
innerLayout:new G6.Layout['dagre']({
rankdir:"LR",
nodesep:20,
ranksep:100
}),
}
以上是layout的布局配置。
我通过按钮绑定一个保存事件，调用graph.save()方法获取拖动后的所有元素坐标等相关数据后，保存。然后再回来拿取刚刚存的数据渲染，结果元素的位置没有任何改变，还是初始化时的默认配置。

我的需求就是想用户在图中拖拉拽后，能够保存图中元素的位置信息。以便下次能够按照用户调整的布局展示。

### 重现链接

无

### 重现步骤

无

### 预期行为

想用户在图中拖拉拽后，能够保存图中元素的位置信息。以便下次能够按照用户调整的布局展示。

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
想要使用数据中的位置信息，不要配置 layout，否则会使用布局重新计算

**Comment by weimengdexiaolaohu-8** [comment]
> 

目前调整了很多布局方案，只有这个combocombined布局满足需求，是否有不重新计算布局的方式。这里只要满足可以保存位置信息即可，下次课利用渲染！

**Comment by yonghengdeanjing** [comment]
> 想要使用数据中的位置信息，不要配置 layout，否则会使用布局重新计算

意思是new Graph时不传入layout配置，然后直接graph.read含有位置信息的data么

**Comment by Yanyan-Wang** [comment]
> > 想要使用数据中的位置信息，不要配置 layout，否则会使用布局重新计算
> 
> 意思是new Graph时不传入layout配置，然后直接graph.read含有位置信息的data么

对。在已经有 graph 实例的情况下，也可以通过 graph.destroyLayout() 先销毁布局，再 graph.changeData 读入节点、combo 中有 x y 信息的数据

**Comment by Yanyan-Wang** [comment]
> > 
> 
> 目前调整了很多布局方案，只有这个combocombined布局满足需求，是否有不重新计算布局的方式。这里只要满足可以保存位置信息即可，下次课利用渲染！

按照上面方案改就可以

**Comment by ClearLuvMoki** [comment]
但是我这边预先保存的数据都是无法正常渲染，每次打开还是默认的位置；
```jsx
mind = new G6.TreeGraph({
      container: $container.current,
      width: $container.current.scrollWidth,
      height: ($container.current.scrollHeight || 500) - 20,
      fitView: true,
      fitViewPadding: [10, 20],
      layout: {},
      minZoom: 0.5,
      modes: {
        default: ['drag-canvas', 'zoom-canvas', 'drag-node'],
      },
    });
    if (data) {
      mind.destroyLayout();
      console.log(JSON.parse(data), 'data')
      mind.read(JSON.parse(data))
      mind.changeData(JSON.parse(data))
      mind.render()
      // mind.refresh()
      // mind.layout(false);
    } else {
      mind.data(dataTransform(rawData));
      mind.render();
    }
```

**Comment by weimengdexiaolaohu-8** [comment]
去掉layout布局熟悉





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/G6"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月6日(星期一) 下午3:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [antvis/G6] 关于combocombined布局，元素坐标不生效的问题 (Issue #4145)





 
但是我这边预先保存的数据都是无法正常渲染，每次打开还是默认的位置；
 mind = new G6.TreeGraph({       container: $container.current,       width: $container.current.scrollWidth,       height: ($container.current.scrollHeight || 500) - 20,       fitView: true,       fitViewPadding: [10, 20],       layout: {},       minZoom: 0.5,       modes: {         default: ['drag-canvas', 'zoom-canvas', 'drag-node'],       },     });     if (data) {       mind.destroyLayout();       console.log(JSON.parse(data), 'data')       mind.read(JSON.parse(data))       mind.changeData(JSON.parse(data))       mind.render()       // mind.refresh()       // mind.layout(false);     } else {       mind.data(dataTransform(rawData));       mind.render();     }

**Comment by ClearLuvMoki** [comment]
![image](https://user-images.githubusercontent.com/61321768/223061394-f00c6bbd-9c19-4667-94d6-78c121794aff.png)
我已经设置`layout`为空了，但是直接去掉`layout`属性会出现上述错误
