### ISSUE TITLE
含有combo的dagre布局，怎样使收起combo时combo的起始x y坐标不变

### ISSUE THREAD

**Issue by yonghengdeanjing** [antvis/G6#4146]
### 问题描述

含有combo的dagre布局中，
问题1：使用graph.collapseExpandCombo收起某个combo后，该combo的order发生变化，会跳到同层级的第一个，怎样能使收起combo时这个combo的起始x 和y坐标不变，但是同层级后面的combo位置相应前移。
问题2：defaultCombo配置中，指定collapsed: true，进入页面后，所有的combo会叠在一块，怎么处理

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
给下在线复现的 demo

**Comment by chengwenxin** [comment]
m

**Comment by apankun** [comment]
请问有结论吗，遇到同样问题
