### ISSUE TITLE
如何让跨层级的edge与父子层级的edge重合

### ISSUE THREAD

**Issue by donghuizhou** [antvis/G6#4147]
### 问题描述

如下图所示，dagre布局，defaultEdge: { type: 'polyline' }，图中蓝色线是从【第三层的节点连到了第五层的节点】，但是它的走线却没有和【第三层节点连到第四层节点的连线】重合，而是另外的走线，显得不好看，如何优化
![image](https://user-images.githubusercontent.com/31002949/208007076-b8c073d2-751c-48f7-8be9-d99d68864b8b.png)

### 重现链接

无

### 重现步骤

如图

### 预期行为

预期如下图，【跨层级的连线】能和【不跨层级的连线】有部分重合，
![image](https://user-images.githubusercontent.com/31002949/208007903-0fef5165-0042-4795-8376-48f5957da396.png)

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by donghuizhou** [comment]
上面的问题有办法处理吗？或者换个思路，像上面那样节点有连线的，可能是前一层指向后一层，也可能跨多层级连线，这种哪个布局比较好，总觉得dagre布局是一层层依次连下去的

**Comment by donghuizhou** [comment]
@Yanyan-Wang 这个有办法优化吗

**Comment by Yanyan-Wang** [comment]
给 dagre 配置 controlPoints: true 看下效果可以吗。不行的话，可以自定义折线，参考：https://g6.antv.antgroup.com/examples/item/customEdge/#customPolyline2
