### ISSUE TITLE
图例Legend 插件，过长会超出，不会自动换行

### ISSUE THREAD

**Issue by MinorN** [antvis/G6#4148]
### 问题描述

使用图例，过长会超出，不会自动换行

### 重现链接

none

### 重现步骤

none

### 预期行为

能够自动换行

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
给个在线复现 demo？不是很清楚什么地方过长超出
