### ISSUE TITLE
activate-relations line active的样式问题

### ISSUE THREAD

**Issue by theDoinb** [antvis/G6#4149]
### 问题描述

我需要读取后台的颜色生成线的颜色，所以在 `data` 每条 `line` 数据下配置了:
```
style: {
   stroke: item.color
},
```
但是 `active` 状态下，线的颜色没有继承 `data` 里的颜色，是一个默认的浅蓝色
我该如何配置 `active` 状态下，保持一样的样式结果呢？

### 重现链接

https://g6.antv.antgroup.com/manual/middle/states/state

### 重现步骤

```
style: {
   stroke: item.color
},
```

### 预期行为

`active` 状态下，保持一样的样式

### 平台

- 操作系统: Windows
- 网页浏览器: Google Chrome
- G6 版本: 4.7.16

**Comment by theDoinb** [comment]
有这种需求是因为，我们需要根据一定规则，来决定 `line` 的颜色，并且是可配置化的。

还有个问题就是，数据配置里面 `labelCfg` 是有 `background` 配置的，但是 `edgeStateStyles` 的 `inactive` 里面确没有这项配置，例如图上信息过于杂乱，我想聚焦与某个节点的相关节点，其他节点及线的透明度可设置，对于 `background` ，我没法降低其设置透明度，只能通过事件去调用 `showItem` 和 `hideItem` 以达到差不多的效果

**Comment by Yanyan-Wang** [comment]
配置 nodeStateStyles, 详见文档：https://g6.antv.antgroup.com/manual/advanced/state-new#%E4%BF%AE%E6%94%B9%E7%8A%B6%E6%80%81%E6%A0%B7%E5%BC%8F%E9%85%8D%E7%BD%AE

**Comment by theDoinb** [comment]
@Yanyan-Wang 

我是想 activate-relations 点击某个节点，相连的 `Line` 是处于 active ，我 `data` 里一根线设置了红色，但当它活跃状态时却是蓝色（默认色），而我并没有去配置 `edgeStateStyles`，你确定是配置 `nodeStateStyles`？

**Comment by Yanyan-Wang** [comment]
一些常见的状态，例如 selected highlight 等，内置有默认的状态样式
