### ISSUE TITLE
拖拽节点,其他节点没有跟着被拖拽节点的运动轨迹走

### ISSUE THREAD

**Issue by gongpingwa00** [antvis/G6#4150]
### 问题描述

https://g6.antv.antgroup.com/zh/examples/net/forceDirected#basicForceDirectedDragFix
![image](https://user-images.githubusercontent.com/23349869/208366535-eee7e8f0-c0a7-4b4a-80de-12d0bd7a60a9.png)
拖拽0节点,其他节点没有跟着0节点移动,而是向着反方向跑,固定每条边长度linkDistance也不行.
怎么样才能实现其他节点总是在被拖拽节点的周围边长距离的位置

### 重现链接

https://g6.antv.antgroup.com/zh/examples/net/forceDirected#basicForceDirectedDragFix

### 重现步骤

进入示例
![image](https://user-images.githubusercontent.com/23349869/208368341-b0996110-b9d3-467c-b6bc-39b664ef14ac.png)

### 预期行为

我期望看到:其他节点总是在被拖拽节点的周围边长距离的位置,比如边长固定150,其他节点总是在被拖拽节点150的地方,均匀散布在周围,但是目前其他节点都都朝着反方向走,边长设置的150都没效果

### 平台

- 操作系统: [ Windows]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
可以用 force2，需要动画就设置布局 animate: true，并且在拖拽过程中也触发 graph.layout。参考这个例子：https://g6.antv.antgroup.com/zh/examples/net/forceDirected/#basicForce2
