### ISSUE TITLE
4.8.0G6 小地图minimap没有可拖拽的框框

### ISSUE THREAD

**Issue by dabanheiji** [antvis/G6#4152]
### 问题描述

使用小地图插件后小地图上只有一个点，没有可拖拽快速查看全局节点的框框
![image](https://user-images.githubusercontent.com/63705496/208377215-a444663c-e084-4daa-b3a0-0b793e8dbc48.png)

期望结果：
![image](https://user-images.githubusercontent.com/63705496/208378707-59783e05-0b12-4596-bf4c-ca399a587556.png)

### 重现链接

https://codesandbox.io/s/sleepy-violet-lqy5n7?file=/src/App.js

### 重现步骤

点击codesandbox链接，待画布渲染完毕之后，小地图上只有当前位置在画布上的点，没有可拖拽预览点框。

### 预期行为

![image](https://user-images.githubusercontent.com/63705496/208379063-ca57483b-ac18-4542-a67a-3c1c5dd1f438.png)

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.8.0 ]

**Comment by Yanyan-Wang** [comment]
原因是 graph 上没有配置 width 或者 height，minimap 没有拿到正确的值进行计算，4.8.1 做了兼容，发布之前可以尝试给你的 graph 加上正确的 width
