### ISSUE TITLE
combo与edge的连接点错位

### ISSUE THREAD

**Issue by zonejay** [antvis/G6#4153]
### 问题描述

当combo设置fixSize或者fixCollapseSize后，与combo相连的边的位置错位
![image](https://user-images.githubusercontent.com/8100236/208570848-28b18a9c-b061-4835-96cd-1c4701904ad7.png)
起始点都设置有箭头，edge终点的箭头被combo遮挡，源点的箭头位置错位

### 重现链接

https://codesandbox.io/s/combo-size-example-i4heob?file=/index.js

### 重现步骤

1. 不设置combo的size属性
2. 设置combo的fixSize或者fixCollapseSize属性

### 预期行为

edge链接点位置不在combo中，而是在combo的border上

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
v4.8.1 已解决

**Comment by zonejay** [comment]
大佬，当combo的size/fixSize/fixCollapseSize设置过大时，也会出现连接点错位的bug，截图中的size大小为60
![image](https://user-images.githubusercontent.com/8100236/210321475-6278a523-6c4d-4f87-b64a-4d56ca13e591.png)

**Comment by zonejay** [comment]
> v4.8.1 已解决
谢谢大佬

**Comment by zonejay** [comment]
大佬，当combo的size/fixSize/fixCollapseSize超过一定大小时，连接点也会错位
![image](https://user-images.githubusercontent.com/8100236/210477999-874299d3-262d-46b3-be1a-0ded06120389.png)
![image](https://user-images.githubusercontent.com/8100236/210478061-8e79731c-c308-4897-a6a4-f281bc798a82.png)
