### ISSUE TITLE
使用update更新node width及height 边线显示错乱

### ISSUE THREAD

**Issue by bluexuchun** [antvis/G6#4156]
### 问题描述

使用自定义节点，update node的width及height为原先的1.5倍大小后，
边线连接点错乱了，放大后线连接的是原本正常的点，恢复原本正常的点后又连接到放大后的点上了

### 重现链接

https://codesandbox.io/s/g6-test-nv3w4z?file=/src/App.js

### 重现步骤

1、进入页面
2、鼠标移入至某个节点再移开就能复现

### 预期行为

希望节点连线正常

### 平台

- 操作系统: Windows
- 网页浏览器: Chrome
- G6 版本: 4.8.0

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/22693912/208810327-4a346f03-b035-42cc-b580-6ce9d10f045d.png)
![image](https://user-images.githubusercontent.com/22693912/208810352-e350825c-5c0c-4741-99f3-26ead1450394.png)

**Comment by bluexuchun** [comment]
@Yanyan-Wang 大佬 求帮助

**Comment by Yanyan-Wang** [comment]
animate 加一个 callback：
```
callback: () => {
  item.refresh();
  item.getEdges().forEach(edge => edge.refresh())
}
```

内置的逻辑是，updateItem 节点的同时，相关边都会去 refresh。但是这时候因为你加了 animate，所以在节点 updateItem 的那一刻拿到的节点 bbox 并不准确。需要在动画结束后才能拿到正确的 bbox

**Comment by bluexuchun** [comment]
> animate 加一个 callback：
> 
> ```
> callback: () => {
>   item.refresh();
>   item.getEdges().forEach(edge => edge.refresh())
> }
> ```
> 
> 内置的逻辑是，updateItem 节点的同时，相关边都会去 refresh。但是这时候因为你加了 animate，所以在节点 updateItem 的那一刻拿到的节点 bbox 并不准确。需要在动画结束后才能拿到正确的 bbox

谢谢大佬
