### ISSUE TITLE
自定义节点中的文本图形在状态取消后，不会回到默认位置，行为与其他图形不一致

### ISSUE THREAD

**Issue by wuxt-dev** [antvis/G6#4158]
### 问题描述

当自定义节点中赋予文本图形状态并取消后，该文本图形不会回到默认位置，而是会自动跳到节点中心位置，行为与设置相同属性的矩形图形不一致

### 重现链接

https://codepen.io/hao0yun/pen/KKBdPMY?editors=1010

### 重现步骤

点击节点，文本和红色矩形同时上移，
点击画布空白处，可以看到红色矩形回到空白位置，而文本偏移到节点中心偏上的位置

### 预期行为

期望看到文本和红色矩形位置变化一致，即回到初始位置

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
自定义节点复写 update 方法为 undefined，或者自己写 update 的逻辑。因为你的 demo 中自定义节点继承了内置的 'circle' 类型节点，所以会继承它的 draw、update 等方法。而 'circle' 的 update 方法可能和你的 draw 逻辑不统一。
