### ISSUE TITLE
有没有监听事件可以监听整个canvas已经完全绘制到dom节点上，afterrender触发时，canvas可能还没有渲染到dom上

### ISSUE THREAD

**Issue by 405go** [antvis/g6#416]
有没有监听事件可以监听整个canvas已经完全绘制到dom节点上，afterrender触发时，canvas可能还没有渲染到dom上？

**Comment by 405go** [comment]
我目前的情况是在绘制完后立即转成图片，可是有些canvas中的数据还没有完全放置在dom节点上，所以导出的图片是一片空白，现在需要的是有一个监听可以监听canvas完全加载到dom上的事件

**Comment by TomHuangCN** [comment]
没这个事件，写个 setTimeout 吧

**Comment by Huichifangqiu** [comment]
求助，解决没，就是用的setTimeout 吗
