### ISSUE TITLE
如何保证新增的数据渲染时始终在当前视口的中心位置

### ISSUE THREAD

**Issue by songxiaoyu321** [antvis/G6#4160]
### 问题描述

1.前置：只有点，没有边
2.渲染点出的多个点布局大概是个圆形（我用gForce配置实现）
3.我的问题来了，第一次接口请求数据渲染图后，图是在当前屏幕的中心位置，这时候我拖拽画布到一个空白位置，如何让第二次接口请求的数据渲染到新的屏幕中心，旧的点维持位置不变

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![WechatIMG1](https://user-images.githubusercontent.com/51144045/209518715-86ba069d-7d12-4a8c-86ff-7207b4b21325.jpeg)

**Comment by Yanyan-Wang** [comment]
给旧节点设置 fx fy 让它们固定位置。重新布局后使用 graph.focusItem 聚焦到某个新节点

**Comment by songxiaoyu321** [comment]
> 给旧节点设置 fx fy 让它们固定位置。重新布局后使用 graph.focusItem 聚焦到某个新节点

用fx,fy固定位置这个可以实现，重新布局这个我不太理解？我该怎么做呢，我目前是第二次搜索出数据之后还是应用的原有布局，只是和第一次数据拼接了一下，形成一个总数据重新渲染图，这样做第二次搜索出来的点还是在第一次点的周围的，我希望的是如果我拖拽画布（第一次的点拖拽后已经不在画面内），第二次点是在我拖拽后的空白位置生成的，离第一次的点很远，我该如何实现呢，是第二次的时候应该用子图布局吗？布局里配置一个新的中心点？那拖拽后的这个中心点我该如何获取？

**Comment by Yanyan-Wang** [comment]
用不用子图布局都可以，如果不用子图布局，新数据加入后还是整个图布局的话，就用 fx fy 把原有节点位置固定，然后 graph.updateLayout 更新新的 center，当前视口的中心可以用 API getViewPortCenter http://g6.antv.antgroup.com/api/graphfunc/coordinate#graphgetviewportcenterpoint

用子图布局的话，就不需要 fx fy 了，直接新的那部分进行布局，同样的设置子图布局的中心
