### ISSUE TITLE
G6插件gird当画布缩放太小时看不见格子导致看起来像空白，如何解决即使缩放很小也能看到网格

### ISSUE THREAD

**Issue by songxiaoyu321** [antvis/G6#4161]
### 问题描述

G6插件gird当画布缩放太小时看不见格子导致看起来像空白，如何解决即使缩放很小也能看到网格

### 重现链接

无

### 重现步骤

无

### 预期行为

G6插件gird当画布缩放太小时看不见格子导致看起来像空白，如何解决即使缩放很小也能看到网格

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
可以自己配置格子比较大的网格图片给到 Grid 插件

**Comment by songxiaoyu321** [comment]
> 可以自己配置格子比较大的网格图片给到 Grid 插件

谢谢，可以了，问题4160还有个疑问，您方便的时候帮我看下，十分感谢
