### ISSUE TITLE
切换布局时，会继承上一个布局的设定

### ISSUE THREAD

**Issue by yushin1010** [antvis/G6#4162]
### 问题描述

切换不同布局时，即使无额外设定，仍会继承上一个布局的设定，若有适用的参数也会套用效果。

### 重现链接

https://codesandbox.io/s/practical-heisenberg-q8lwvw?file=/index.js:4151-4181

### 重现步骤

1. 进入页面
2. 点击「切换preventOverlap为true的force」按钮
3. 点击「切换无额外设定的concentric」按钮，可以看到有 preventOverlap 为 true 的效果
4. 点击「切换preventOverlap为false的force」按钮
5. 点击「切换无额外设定的concentric」按钮，可以看到 preventOverlap 为 false 的效果

### 预期行为

期望看到无设定的布局被切换时，应维持初始设定状态，而非继承上个布局的参数。

### 平台

- 网页浏览器: [Google Chrome]
- G6 版本: [4.8.0]

### 屏幕截图或视频（可选）

preventOverlap 为 true 时
![image](https://user-images.githubusercontent.com/96538943/209532114-6c4b63ef-1bf0-43a8-b30c-f9a9eb5042a3.png)

preventOverlap 为 false 时，可以看到节点重叠
![image](https://user-images.githubusercontent.com/96538943/209532178-9c127fe7-5d52-4106-9c0e-16fb158b1748.png)

**Comment by Yanyan-Wang** [comment]
这个是符合预期的，graph.updateLayout 传什么就更新什么，不传就用之前设置好的。这里如果你想要每次 concentric 效果都一样的话，预设一套 concentric 的参数作为常量，每次切换都全部放进去 updateLayout 就好

**Comment by XiaoRIGE** [comment]
我这边出现了类似的问题，当我第一次进入时使用的布局是通过pipes配置了两种grid布局，切换布局后使用的是全部采用concentric。但是出现的问题是当我切换到concentric布局后，依然有一部分节点按照pipes[1]中的布局方式进行布局。
