### ISSUE TITLE
如何获取边与节点图形的相交点并且实现动态更新边端点的位置

### ISSUE THREAD

**Issue by alistuff** [antvis/G6#4163]
### 问题描述

您好：
我想知道怎么动态计算连接边的末端位置，以便实现在linkCenter模式下，边的末端箭头始终指向节点形状的边缘，而不是被节点覆盖。

![QQ截图20221226172241](https://user-images.githubusercontent.com/7888295/209532370-ce7c2863-b8cf-4a19-8a73-cbae0cbaa806.png)

实现思路是：
1.在拖动节点时获取节点相关入度或出度的边数据
2.计算边线段与节点图形的相交点，并更新边线段的末端位置

我从相关文档中无法获得如何动态计算边的端点位置的方法，想请教下以上的需求该如何实现，能提供类似的实现案例吗？谢谢。

### 重现链接

暂无

### 重现步骤

暂无

### 预期行为

暂无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
应该不需要这么麻烦，给箭头配置 d 让它沿路径“退”出来一些就好 http://g6.antv.antgroup.com/manual/middle/elements/edges/arrow#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95-1

**Comment by alistuff** [comment]
我已经发现使用antv/x6更合适实现我的流程编辑器功能，感谢上面的回复，有时间我可以尝试一下，如果能解决我再在这里追加回复，以便提供其他人实现类似功能的思路和方法。
