### ISSUE TITLE
节点内容超出

### ISSUE THREAD

**Issue by yazhang-wed** [antvis/G6#4164]
### 问题描述

![image](https://user-images.githubusercontent.com/54184726/209615921-8e0ba453-0aa2-4736-b820-de0c91eea38d.png)

### 重现链接

https://x6.antv.antgroup.com/examples/showcase/practices/#er

### 重现步骤

无

### 预期行为

超出内容加三个点，或者换行

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
是不是找错 repo 了，在 X6 issue 里面提下？
