### ISSUE TITLE
dagre布局开启zoom-canvas和drag-canvas后图边缘被裁减

### ISSUE THREAD

**Issue by CheyenneRowe** [antvis/G6#4166]
### 问题描述

dagre布局开启zoom-canvas和drag-canvas后图边缘被裁减

### 重现链接

无

### 重现步骤

初始渲染是正常的：
<img width="474" alt="image" src="https://user-images.githubusercontent.com/18679459/209639693-d75c6636-0e16-49ed-b2ce-2cfd80538ffc.png">
缩放/拖动后：
<img width="466" alt="image" src="https://user-images.githubusercontent.com/18679459/209639874-14c6119e-3b77-4d34-8d3e-65ba79949718.png">

图的配置如下：
```javascript
new G6.Graph({
    container: ref.current,
    width: 1000,
    height: 400,
    fitView: true,
    defaultNode: {....},
    minZoom: 1,
    maxZoom: 3,
    defaultEdge: {
        shape: 'polyline',
        labelCfg: {
            autoRotate: true,
            refY: 10,
            style: {
                fill: 'transparent',
                fontSize: 12
            }
        },
    },
    layout: {
        type: 'dagre',
        rankdir: 'LR',
        nodesep: 50,
        ranksep: 150,
        preventOverlap: true
    },
    modes: {
        default: [{
            type: 'zoom-canvas',
            enableOptimize: true,
            sensitivity: 1,
        },
        {
            type: 'drag-canvas',
            enableOptimize: true,
            allowDragOnItem: true,
        }
        ],
    },
});
```

### 预期行为

渲染正常

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.7.16]

**Comment by Yanyan-Wang** [comment]
关于渲染残影问题： http://g6.antv.antgroup.com/manual/faq/faq#%E6%B8%B2%E6%9F%93%E6%AE%8B%E5%BD%B1%E9%97%AE%E9%A2%98

给个在线复现的 demo 吧，具体问题才好排查
