### ISSUE TITLE
如何设置g6 中A节点到A节点自身的边？

### ISSUE THREAD

**Issue by ahong007007** [antvis/G6#4167]
### 问题描述

edges: [
    { source: 'A', target: 'A', type: 'line', label: 'line' },
]

设置节点A指向A的节点，不能正常显示

请教一下，G6支持节点自身的边的显示？谢谢。

### 重现链接

https://codesandbox.io/s/new

### 重现步骤

1.接入界面
2.设置边的显示

edges: [
    { source: 'A', target: 'A', type: 'line', label: 'line' },
]

### 预期行为

期望有A-A的边显示，实际没有

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
这种边的 type 设置为 'loop'
