### ISSUE TITLE
如何设置画布跟随浏览器窗口的缩放自动缩放

### ISSUE THREAD

**Issue by wuxt-dev** [antvis/G6#4168]
### 问题描述

监听浏览器窗口缩放事件后，尝试用changeSize修改画布大小，然后用refresh、patint、render、layout重新绘制均没有效果

### 重现链接

null

### 重现步骤

null

### 预期行为

null

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
你是说希望图内容能够随着缩放？graph.fitView() ，或者自己更精准地控制 graph.zoomTo()
