### ISSUE TITLE
图形元素opacity设置为0时仍可以响应鼠标事件

### ISSUE THREAD

**Issue by wuxt-dev** [antvis/G6#4169]
### 问题描述

图形元素opacity设置为0时仍可以响应鼠标事件

### 重现链接

null

### 重现步骤

null

### 预期行为

图形元素opacity设置为0时不响应鼠标事件

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
opacity 为 0，但是它还是存在画布上的，所以可以响应是符合预期的。我理解你的场景如果是整个节点或者边的话，通过 graph.hideItem(node) graph.showItem(edge) 来控制显示隐藏，如果是图形的话，在自定义节点里面根据逻辑进行 shape.show() 和 shape.hide()。

**Comment by wuxt-dev** [comment]
> opacity 为 0，但是它还是存在画布上的，所以可以响应是符合预期的。我理解你的场景如果是整个节点或者边的话，通过 graph.hideItem(node) graph.showItem(edge) 来控制显示隐藏，如果是图形的话，在自定义节点里面根据逻辑进行 shape.show() 和 shape.hide()。

好的，谢谢大佬
