### ISSUE TITLE
edge边实现流向动画效果，自定义节点无法随边旋转？

### ISSUE THREAD

**Issue by xtito** [antvis/G6#4170]
### 问题描述

需求：实现连接两个节点的边动画效果，水滴流向效果如示例。最好是实现效果支持带弧度曲线。

问题：目前通过动画结合添加自定义节点（图片）实现，但是自定义图片无法随边旋转，期望能随边旋转。

期望：
希望专家能指导下如何达到我的预期，最好是能够支持在曲线edge情况下，也能有流向效果，先谢过

![image](https://user-images.githubusercontent.com/8833358/209798512-652b7c4a-a28a-4717-82da-996b02599d70.png)

### 重现链接

https://codesandbox.io/s/broken-architecture-xvmmn7?file=/index.js

### 重现步骤

1、进入页面即可查看到示例；
2、示例中左侧为问题效果、右侧部分为期望效果（Node 4 和 Node 3是提供的希望效果，最好支持曲线）；

### 预期行为

期望达到示例中 Node 4 和 Node 3是的效果，希望支持曲线

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.8.0]

### 屏幕截图或视频（可选）

<img width="542" alt="WeChatd2fc40628f887f7618585b339736a9f7" src="https://user-images.githubusercontent.com/8833358/209799629-f6866087-3aa7-4a01-af5a-2bd90132d361.png">

期望曲线情况下也有类似效果，参考图如下：

<img width="970" alt="WeChat597a297fc85bb40d4100b1f5f07bfda4" src="https://user-images.githubusercontent.com/8833358/209800684-98522c8b-9ddf-4f54-a04d-923740ce9cc7.png">

**Comment by xtito** [comment]
@Yanyan-Wang 求大神解惑

**Comment by Yanyan-Wang** [comment]
参考这个例子
http://g6.antv.antgroup.com/examples/scatter/edge/#arrowAnimate

**Comment by xtito** [comment]
@Yanyan-Wang 这个示例如何能够实现箭头尾部带光效、光晕或阴影效果？让动画看起来带了个小尾巴一样，当然我更想要的效果是看起来是水滴带光晕小尾巴？

烦请您看一个示例链接，万分感谢：http://192.144.199.210:8080/editor/index.html?chart_id=i76xD0-HxqzbxomC

烦请修改134、135行代码，可以修改参数放大效果
<img width="450" alt="WeChat4a1c4920a34bf9566fb87b2ae7346f87" src="https://user-images.githubusercontent.com/8833358/209929918-50ae0a3a-10c4-4369-a376-6d5f00381c65.png">

**Comment by Yanyan-Wang** [comment]
我看你在问题描述里面已经用图片实现了，你就用你的实现，只是参考这里箭头的旋转和移动动画就好了

**Comment by xtito** [comment]
> 我看你在问题描述里面已经用图片实现了，你就用你的实现，只是参考这里箭头的旋转和移动动画就好了

@Yanyan-Wang 您好，图片实现效果始终不佳（曲线的话就不行了），请问支持通过API实现光晕效果吗？，还请指点一下，感谢

**Comment by xtito** [comment]
期待大佬回复

**Comment by Yanyan-Wang** [comment]
不能完全还原，这样看起来比较像，你可以再调整下：
https://codesandbox.io/s/stupefied-voice-gz3ky7?file=/index.js

用到渐变色填充 http://g6.antv.antgroup.com/api/shape-properties#fill
和 shadowBlur shadowColor

**Comment by xtito** [comment]
非常感谢您的帮助，能达到这种效果也可以。
