### ISSUE TITLE
Keep labels constant size

### ISSUE THREAD

**Issue by spacemolly** [antvis/G6#4171]
### 问题描述

Currently when zooming a canvas in our out the labels scale in the same way as the nodes and edges. My question is if it is possible to keep text constant size when zooming, making it constant in size no matter the zoom but keep aligned to nodes in the same way? 

### 重现链接

None

### 重现步骤

Create a zoomable graph

### 预期行为

None

### 平台

None

### 屏幕截图或视频（可选）

None

**Comment by Yanyan-Wang** [comment]
http://g6.antv.antgroup.com/manual/middle/states/defaultbehavior#zoom-canvas

`fixSelectedItems`. Assign `fixSelectedItems.fixLabel` to true, and maybe set `fixSelectedItems.fixState` to some custom string and set all the nodes and edges to that state.

**Comment by spacemolly** [comment]
Thanks! It's in this direction but has multiple issues, setting `fixSelectedItems.fixLabel` and using a state is only temporary while that state is on so it stops you from using states for other things and it doesn't have any effect on zoom in, just zoom out, so result is still huge labels.

Is using a custom node an option?

**Comment by Yanyan-Wang** [comment]
> Is using a custom node an option?

Of course. But the node drawing and the graph is decoupled, you have to update the current zoom ratio to the node items while zooming. Maybe like:

```
 graph.on('viewportchange', e => { 
  if (e.action === 'zoom' ) {
    const currentZoom = graph.getZoom();
    graph.getNodes().forEach(node => graph.updateItem(node, { zoomRatio: currentZoom }))
  }
})
````

And update the label shape's fontSize in the custom node's update function.
