### ISSUE TITLE
changeData更改数据时,数据内的边指向一个不存在的节点会出现警告

### ISSUE THREAD

**Issue by Aicmortal** [antvis/G6#4172]
### 问题描述

changeData更改数据时,数据内的边指向一个不存在的节点会出现警告,并且无法更新数据,我感觉应该允许更新数据才对,节点变化,错误的边不进行绘制就行了

### 重现链接

https://stackblitz.com/edit/react-uguwms?file=index.js

### 重现步骤

https://stackblitz.com/edit/react-uguwms?file=index.js

### 预期行为

改变数据

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]
G6 4.8.1

**Comment by Yanyan-Wang** [comment]
需要通过数据校验才可以，否则后续对不存在的内容进行操作可能出现更多问题。

**Comment by Aicmortal** [comment]
> 需要通过数据校验才可以，否则后续对不存在的内容进行操作可能出现更多问题。

好的
