### ISSUE TITLE
如何在容器外触发撤销对图中元素点击的操作

### ISSUE THREAD

**Issue by Chenshiwei1** [antvis/G6#4174]
### 问题描述

能否在graph外部添加一个按钮，执行撤销图中点击边和节点的操作？

### 重现链接

https://codepen.io/Chenshiwei1/pen/WNKwEYj

### 重现步骤

进入页面，随意点击节点或者边，点击撤销按钮，图返回上一次点击的状态

### 预期行为

图返回上一次点击的状态

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
自己维护一个状态的栈，点撤销的时候通过 graph.setItemState(node, 'selected', true / false) 来控制就好
