### ISSUE TITLE
请问如何实现线的弹性动画和互斥效果？

### ISSUE THREAD

**Issue by songxiaoyu321** [antvis/G6#4177]
### 问题描述

问题1.拖动节点时线会往拖动方向产生一个力，来回弹动，力逐渐减小，弹动幅度也越来越小最后停止。
问题2.拖动节点时经过另一个线，经过的线会产生斥力，会有小幅度弹动

### 重现链接

无

### 重现步骤

问题2完全不知道如何实现
问题1我尝试改变边的curveOffset，确实可以左右动，但是不是我要的效果
Path.animate(
            (ratio) => {
              if ((ratio > 0 && ratio <= 0.25) || (ratio > 0.5 && ratio <= 0.75)) {
                lastCurveOffset += 2
              } else {
                lastCurveOffset -= 2
              }
              graph.updateItem(edge, { curveOffset: lastCurveOffset })
            },
            {
              duration: 3000,
              repeat: false,
              easing: 'easeCubic'
            }
          )

### 预期行为

1.觉得自己写这个效果很难，g6可不可以考虑加配置就可以直接实现这种效果（现在有这种配置吗？如果有请问如何配置）
2.如果目前不可以配置，该如何写，可以提供一些建议吗

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

Uploading 2_1672382061.mp4…

**Comment by Yanyan-Wang** [comment]
效果过于梦幻，官方不考虑支持
