### ISSUE TITLE
有没有方法把某个Shape图形移除了，并且更新页面

### ISSUE THREAD

**Issue by 2510340910** [antvis/G6#4180]
### 问题描述

带有折叠点collapsed-icon的自定义节点， 通过 treeGraph.removeChild(id_node)将孩子节点删除，孩子节点删除完，折叠点应该被删除或者隐藏，但是我试着更改折叠点的attr中属性stroke、fill、r让其变成透明，但是效果不是很满意，在同一个地方，删除，页面更新出来，有时候可以变透明，有时候变不了；想怎样可以将这个折叠点删除了，查了操作相关shape，group.removeChild(xxx)也没成功

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![1672741260278](https://user-images.githubusercontent.com/112143316/210338818-6f09e009-180c-4d0a-8242-675458888694.png)

### 补充说明（可选）

![图片](https://user-images.githubusercontent.com/112143316/210338983-ffbad3a3-147f-4c2f-950a-295183e4a86a.png)

**Comment by Yanyan-Wang** [comment]
应该在自定义节点里面去控制，children 为空时，不绘制这个图形，或者 shape.hide() 隐藏掉，有 children 的时候 shape.show 显示出来

**Comment by 2510340910** [comment]
> 应该在自定义节点里面去控制，children 为空时，不绘制这个图形，或者 shape.hide() 隐藏掉，有 children 的时候 shape.show 显示出来

我试了，用hide(),就是效果和之前两种想法一样，有；但是偶尔页面不灵
1. 这是原页面
![图片](https://user-images.githubusercontent.com/112143316/210355935-1e4a3d75-19f9-449d-9810-ec7f679e4cc8.png)
2. 这是成功删除的页面(节点8的孩子删完了，折叠点删除了/隐藏了)
![图片](https://user-images.githubusercontent.com/112143316/210356078-d4c566f6-a870-4378-acb8-90e4bf3306c4.png)
3. 这是失败的页面(节点8的孩子删完了，折叠点没删除/隐藏了)
![图片](https://user-images.githubusercontent.com/112143316/210356273-42544a4b-94b6-468d-b727-c1c053eb951b.png)

1. 自定义节点相关代码
![图片](https://user-images.githubusercontent.com/112143316/210356369-0d04ee9d-ea9b-48a8-b435-d5937fa97aeb.png)
2. 刚刚修改的代码
![图片](https://user-images.githubusercontent.com/112143316/210356443-3a28561e-6022-4f6d-a4a9-372694dd1d71.png)

主要是同样一份代码，删除节点8下的所有孩子节点，他的那个折叠点有时候会消失，有时候不会，就很离谱，不知道是什么问题
