### ISSUE TITLE
关于Combo分组，如何用鼠标自由拖动改变Combo分组框的大小

### ISSUE THREAD

**Issue by weimengdexiaolaohu-8** [antvis/G6#4181]
### 问题描述

关于Combo分组，如何用鼠标自由拖动改变Combo分组框的大小。就像一个窗口，当鼠标放置窗口边缘即可拖拽缩放大小。也想将鼠标放置Combo分组框边缘拖拽缩放其大小！

### 重现链接

无

### 重现步骤

无

### 预期行为

像一个窗口，当鼠标放置窗口边缘即可拖拽缩放大小。也想将鼠标放置Combo分组框边缘拖拽缩放其大小！

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![Uploading 45971672741930_.pic.jpg…]()

**Comment by Yanyan-Wang** [comment]
监听 combo 拖拽事件，更新 combo 的 fixSize。
这一类强编辑的需求，推荐用 AntV X6  http://x6.antv.antgroup.com/

**Comment by SKT1yang** [comment]
> Referenc

版本4.8.17 文档里没有提供更新fixSize的api，属于被动更新。

**Comment by SKT1yang** [comment]
> 监听 combo 拖拽事件，更新 combo 的 fixSize。 这一类强编辑的需求，推荐用 AntV X6 http://x6.antv.antgroup.com/

版本4.8.17 文档里没有提供更新fixSize的api，属于被动更新。
