### ISSUE TITLE
@antv/g6-react-node 部分组件的 typescript 类型缺失

### ISSUE THREAD

**Issue by whinc** [antvis/G6#4187]
### Describe the bug

按照语雀上这篇 [在G6中使用React定义的节点](https://www.yuque.com/antv/g6-blog/osythv?) 文章定义节点，过程中发现部分组件的 ts 类型提示缺失，主要体现在 Group 组件的 keyshape、style 和 onXXX 事件

![image](https://user-images.githubusercontent.com/5096493/210530400-07d0f2d1-95ea-473e-889b-d2179e6438dc.png)

### Your Example Website or App

https://codesandbox.io/s/antv-g6-react-node-demo-mtfu6m?file=/src/registerNodes.tsx

### Steps to Reproduce the Bug or Issue

查看 registerNodes.tsx 文件，ts 类型会提示找不到相关类型

### Expected behavior

期望没有 ts 类型错误

### Platform

- OS: Windows
- Browser: Chrome
- Version: 107

**Comment by dapangxue** [comment]
hello，请问这个问题解决了吗？我今天刚试了下，v1.4.5 版本也发现有这个问题，props 里面没有定义 children 属性。

**Comment by Aarebecca** [comment]
@antv/g6-react-node 已不再维护，请使用 @antv/g6-extension-react (需要 G6 版本 >= 5.0)
