### ISSUE TITLE
将一个节点A/子树A，拖拽到节点B下，节点B不能即时展现出新添加的节点A/子树A

### ISSUE THREAD

**Issue by 2510340910** [antvis/G6#4191]
### 问题描述

将一个节点A/子树A，拖拽到节点B下，节点B不能即时展现出新添加的节点A/子树A

### 重现链接

无

### 重现步骤

1. 进入页面
2. 拖拽节点A/子树A到节点B下
3. 节点B展现出刚刚新添加的节点A/子树A

### 预期行为

我期望看到拖拽节点A到节点B,鼠标键松的那一刻，节点B展现出刚刚新添加的节点A/子树A，但是没有，需要点击折叠点两次，才能展现出来；查看data数据，数据中已经满足关系，但是页面不能即时展现效果

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

# 实际结果
https://user-images.githubusercontent.com/112143316/210770148-859813a8-b4fd-4e5d-8ad4-b0bebd3bf1a7.mp4
# 预期结果
https://user-images.githubusercontent.com/112143316/210770658-631fc12a-07bb-4076-a357-8d19dd8e04db.mp4

# 对应代码
![6HY5F37ZBYR%EIIFQDSD~EC](https://user-images.githubusercontent.com/112143316/210773329-57f27a0c-b759-4a75-a5e2-02f8ebc6605c.png)

**Comment by Yanyan-Wang** [comment]
给个在线复现的 demo 吧。不需要 sourceNodeParentItem.update targetNodeParentItem.update
