### ISSUE TITLE
图算法：最短路径添加参数true设置为有向图的模式，运算不成功

### ISSUE THREAD

**Issue by SunQiDong1999** [antvis/G6#4195]
### 问题描述

如题

### 重现链接

https://g6.antv.antgroup.com/examples/algorithm/algoDemos/#shortestPath

### 重现步骤

把算法相关代码修改为
`      const { findShortestPath } = G6.Algorithm;
      // path 为其中一条最短路径，allPath 为所有的最短路径
      const { path, allPath } = findShortestPath(
        data,
        selectedNodes[0].getID(),
        selectedNodes[1].getID(),
        true
      );`

### 预期行为

设置为有向图应该可以正常运行

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/45733296/211147983-70479221-8185-48a1-b701-fdbea4411820.png)
![image](https://user-images.githubusercontent.com/45733296/211147993-050bc261-4b06-487c-ac0a-ab03683acdcc.png)

**Comment by Yanyan-Wang** [comment]
报错应该和算法无关，是没有计算出结果，path 为 undefined，demo 里面还遍历了 path 所以报错。只需要在后面包一个 if (path) {} 就可以避免。不过这里因为是无向图的例子，const selectedNodes = graph.findAllByState('node', 'selected'); 拿到的顺序不是点击节点的顺序，所以看起来有些在 directed 下应该有结果的，却没有计算出来。把 selectedNodes 这个换成按照点击顺序存储就好
