### ISSUE TITLE
自定义节点在focusItem时无法获取到矩形，getMatrix为null

### ISSUE THREAD

**Issue by lmm2022** [antvis/G6#4198]
### Describe the bug

![image](https://user-images.githubusercontent.com/44827236/211451668-0441db1b-f845-4d8f-8f92-a0f4c24b7a11.png)
![image](https://user-images.githubusercontent.com/44827236/211451698-514ace6f-5c06-4488-a27f-b3c476cb0884.png)
自定义节点代码
// 自定义节点（带删除按钮的长方形）
      G6.registerNode(
        'deletedRect',
        {
          afterDraw(cfg, group) {
            const x = 30
            const y = -20
            const bottomNode = group.addShape('rect', {
              attrs: {
                stroke: 'white',
                fill: 'white',
                x: x - 1,
                y: y - 4,
                width: 20,
                height: 20,
                zIndex: 0,
                capture: true,
                radius: 10,
                lineWidth: 1
              },
              name: 'deletedNode'
            })
            const deleteNode = group.addShape('path', {
              attrs: {
                stroke: '#000',
                zIndex: 2,
                path: [
                  ['M', 0 + x, 0 + y],
                  ['L', 10 + x, 10 + y],
                  ['M', 0 + x, 10 + y],
                  ['L', 10 + x, 0 + y]
                ],
                capture: true,
                lineWidth: 2
              },
              name: 'deletedNode'
            })
            return deleteNode, bottomNode
          },
          // 响应状态变化（修复单击后样式重叠的官方bug 勿动）
          setState(name, value, item) {
            const group = item.getContainer()
            const shape = group.get('children')[0] // 顺序根据 draw 时确定
          }
        },
        'rect'

### Your Example Website or App

暂无

### Steps to Reproduce the Bug or Issue

在上面截图和自定义节点代码显现

### Expected behavior

我不清除我是不是还需要定义matrix 但是看官方文档那是3.3版本 我现在是处于4.7.14版本的antv/G6

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by lmm2022** [comment]
@Yanyan-Wang 你好，能否抽时间看一下我的这个问题嘛？是我自定义节点写的有问题吗？

**Comment by lmm2022** [comment]
或者请问能支持自定义手动修改画布中心嘛

**Comment by Yanyan-Wang** [comment]
给个在线复现的 demo

**Comment by lmm2022** [comment]
我这边放了一份关于自定义节点以及事件的vue和视频
https://github.com/lmm2022/G6-jiedian
谢谢~

**Comment by lmm2022** [comment]
通过断点源码我有两种想法，一种是我自定义的节点缺少matrix 试过通过setMatrix添加但是断点到定位的源码还是为null 另一种可能是我每次添加节点新数据都需要重新渲染 中心点变化导致定位坐标不正确
想听听作者大大的看法~

**Comment by Yanyan-Wang** [comment]
getMatrix 默认值是 null 没错的。没看到你的例子里面错误在哪里？什么结果不符合预期？在 codesandbox.io 写成最简单的在线 demo 吧，不清楚你的问题究竟是什么？
