### ISSUE TITLE
请教一下，dagre布局不同节点高度不一样，怎么设置不同节点间距一致了？

### ISSUE THREAD

**Issue by wanghong628101** [antvis/G6#4199]
### 问题描述

nodesepFunc根据节点类型设置不同间距，但是找不到什么规律了，这个间距到底是指从哪里到哪里的距离了，我的节点中心在左上角，另外想请教一下rankdir：‘LR'，怎么让左右根据中间节点对称分布了，如果把节点中心设置在中间点，间距可以调整到合适，但是左右右完全不对称？

### 重现链接

无

### 重现步骤

自定义节点设置间距

### 预期行为

希望不同节点根据类型设置不同高度，最终所有节点竖直方向上间距一致，节点能够根据中间节点左右对称分布

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![1571673321410_ pic](https://user-images.githubusercontent.com/76779908/211455727-0b618287-e94b-443c-b904-2da429b7950f.jpg)

**Comment by Yanyan-Wang** [comment]
dagre 计算过程没有考虑对称，它也没有”中间节点“的概念，都是按层级从左到右，或者从上到下去计算的

**Comment by wanghong628101** [comment]
另外想问一下节点高度不同，怎么设置每个节点间距一样了，防止重叠，用nodesepFunc根据节点高度设置不行了，还是会重叠

**Comment by Yanyan-Wang** [comment]
你把节点大小写在节点数据的 size 上，布局会自动拿这个 size 来计算空间
