### ISSUE TITLE
在哪可以看到G6Editor的源码呢

### ISSUE THREAD

**Issue by xinggangling** [antvis/g6#420]
hello ～，
      我想阅读G6Editor的源码，请问在哪可以看到呢

**Comment by nameliuqi** [comment]
目前不开源

**Comment by nameliuqi** [comment]
但是业务真的很需要啊

**Comment by TomHuangCN** [comment]
努力中，争取明年年初开源。

**Comment by caoyu48** [comment]
http://62.234.69.136/

**Comment by baizn** [comment]
目前没有在维护了， 可以参考社区的实现：https://www.yuque.com/antv/g6/intro#uu3gy。
