### ISSUE TITLE
indented tree 节点大小不一样时，同级节点上下会被覆盖

### ISSUE THREAD

**Issue by rainLeaf888** [antvis/G6#4200]
### Describe the bug

同级节点相互被覆盖了，如下：
![image](https://user-images.githubusercontent.com/24802442/211475157-33ac4870-7682-4bba-acf3-5d72cd330c0b.png)

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

layout的type = ‘indented’，树的第一层、第四层大小跟第一层、第三层不一样，且第四层后面还有子节点，直接渲染

### Expected behavior

同级节点不被覆盖，如下
![image](https://user-images.githubusercontent.com/24802442/211475059-d5a3214c-9003-485f-ad1b-2dbdef2e949e.png)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

更改 hierarchy/src/layout/indented.js 中的positionNode node.y的坐标计算方式
 if (previousNode) {
    var y = previousNode.y + previousNode.height
    // 上个节点及当前节点不是在同一层级时
    if (node.parent.id !== previousNode.parent.id) {
      var index = node.parent.children.findIndex(n => n.id === node.id)
      var preNode = node.parent.children[index-1]
      var preY = preNode.y + preNode.height
      node.y = preY > y ? preY : y;
    } else {
      node.y = y;
    }
  } else {
    node.y = 0;
  }

**Comment by rainLeaf888** [comment]
上述 贴的代码是我目前实现可以解决这个问题的，期望官方可以看看，是否收录然后发正式版本

**Comment by Yanyan-Wang** [comment]
感谢报告，已根据你的建议进行修改，更新 @antv/hierarchy 到 0.6.9，或重装依赖即可

https://github.com/antvis/hierarchy/pull/20/files
