### ISSUE TITLE
image类型的shape使用setClip()进行裁剪，页面渲染是有裁剪的，但在通过graph.downloadFullImage()方法导出的图片里该shape是没有进行裁剪处理的

### ISSUE THREAD

**Issue by auxshaw** [antvis/G6#4201]
### 问题描述

在自定义节点里添加一个image类型的shape，并使用setClip()进行裁剪成圆形，页面里渲染出来的效果是进行裁剪处理的，但在通过graph.downloadFullImage()方法导出的图片里，会发现image类型的shape没有进行裁剪处理，与页面渲染的效果不一致。
<br>
页面渲染的效果，image类型的shape被裁剪成圆形，如下所示：
![image](https://user-images.githubusercontent.com/43061495/211478260-5d5661ad-8310-4964-a374-b22f95110871.png)
<br>
通过graph.downloadFullImage()方法导出的图片，image类型的shape没有进行裁剪处理，如下所示：
![image](https://user-images.githubusercontent.com/43061495/211478569-6358cd05-184a-4f2c-a4f0-0c1288746e5d.png)

### 重现链接

https://codesandbox.io/s/g6-shape-image-clip-gt4wps?file=/src/App.vue

### 重现步骤

1. 进入页面 （https://codesandbox.io/s/g6-shape-image-clip-gt4wps?file=/src/App.vue）
2. 等待页面加载完成，点击导出graph的按钮
3. 下载通过graph.downloadFullImage()方法导出的graph图片并点开，会发现image类型的shape没有像页面里渲染的那样被裁剪。

### 预期行为

期望导出图片里的image类型的shape像页面里渲染的那样被裁剪，比如像示例一样裁剪成圆形。

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.8.3]

**Comment by auxshaw** [comment]
@Yanyan-Wang 想问下这个问题能修复下吗？

**Comment by auxshaw** [comment]
另一种处理方案：先用canvas将图片裁剪成圆形，将canvas传给image类型的shape去展示和导出

**Comment by Yanyan-Wang** [comment]
4.8.5 应该已经修复，可以更新到最新版本试试看

**Comment by changshaoying** [comment]
setClip()，这个方法现在还存在吗？为什么我会报 xxx.setClip is not a function 的错误
