### ISSUE TITLE
treeGrapth.removeChild(id)导致连接线崩溃问题

### ISSUE THREAD

**Issue by 2510340910** [antvis/G6#4203]
### 问题描述

假如节点A有多个孩子节点，通过treeGrapth.removeChild(id)删除其中一个孩子节点，节点A和其他孩子节点的连接路径会崩溃，更奇怪的是，这种问题还不是一定会出现，删除成功几次，然后下一次就崩溃了；
其中使用了graph.refreshItem(item)、graph.refreshPositions()都没用
想用graph.removeItem(item, stack)代替，但是树图data里面没删除成功，而且连接线样式也不会计算，仅仅删除一个节点一根线，孩子节点都都停留在上面
想用graph.hideItem(item, stack)、hide()隐藏该节点，效果也是不尽人意

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![$0S4NT CER{GILY2$NGS}NT](https://user-images.githubusercontent.com/112143316/211548785-4e6b888d-c9e6-4d55-923c-5b3e0e758007.png)

**Comment by Yanyan-Wang** [comment]
给个在线复现的 demo？
