### ISSUE TITLE
dagre布局，节点信息中指定layer层级，连线的控制点controlPoints有问题

### ISSUE THREAD

**Issue by yonghengdeanjing** [antvis/G6#4204]
### 问题描述

dagre布局，如果在节点信息中指定layer层级，连线的控制点controlPoints，有些时候为0，有些时候位置不对，导致连线穿过节点了。
示例中，issueData和issueLayerData的nodes数据和edges数据一样，只不过issueLayerData中指定了layer层级，dagre布局后，使用issueLayerData的布局，controlPoints就不太对：controlPoints为空，或者controlPoints会与节点重叠。

指定了layer的在线demo:
https://stackblitz.com/edit/react-gtrsxk-mu6xz1?file=index.js
没有指定layer的在线demo:
https://stackblitz.com/edit/react-gtrsxk-vycyps?file=index.js

指定了layer，节点2_2的入边：
![image](https://user-images.githubusercontent.com/30465367/211704780-cd27b513-7674-4cb3-9af1-f99815a9255b.png)
![image](https://user-images.githubusercontent.com/30465367/211704892-3fca8d12-bacc-4114-abf3-58040af05bc9.png)

没有指定layer的情况下，节点2_2的入边：
![image](https://user-images.githubusercontent.com/30465367/211705415-989d15d1-c017-47d8-a815-6e32899843ae.png)
![image](https://user-images.githubusercontent.com/30465367/211705451-f62167d5-40c1-45b0-b1b0-6c3199f6248a.png)

指定了layer，节点57_4的入边：
![image](https://user-images.githubusercontent.com/30465367/211705043-ed834b97-85b4-42a8-bd64-4c82170ca6d6.png)
![image](https://user-images.githubusercontent.com/30465367/211705098-bb10203f-adfd-453c-a47f-bacc3a3c3bd1.png)

没有指定layer的情况下，节点57_4的入边：
![image](https://user-images.githubusercontent.com/30465367/211705594-5e4eb86f-1721-4a41-b321-596d46c2fc1c.png)
![image](https://user-images.githubusercontent.com/30465367/211705646-589ff02e-f036-4ffb-9acd-3bf3ca96a04e.png)

### 重现链接

https://stackblitz.com/edit/react-gtrsxk-mu6xz1?file=index.js

### 重现步骤

如上

### 预期行为

期望指定了layer层级后的dagre布局，controlPoints正常

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.8.3 ... ]

**Comment by yonghengdeanjing** [comment]
项目比较紧急，求个修复时间呢~

**Comment by yonghengdeanjing** [comment]
项目比较紧急，求个修复时间呢~

**Comment by Yanyan-Wang** [comment]
简单修复了一个版本，重新安装一下依赖试试，效果不行的话下周我再看看

**Comment by yonghengdeanjing** [comment]
试了一下4.8.5版本，还是有问题呢
