### ISSUE TITLE
使用dagre布局时，layer控制节点层级布局错乱

### ISSUE THREAD

**Issue by zhl0916** [antvis/G6#4207]
### Describe the bug

使用dagre布局，layer控制节点层级，首次出现同级节点之间有连线的会导致布局失败

### Your Example Website or App

https://g6.antv.antgroup.com/manual/middle/elements/methods/multi-line#gatsby-focus-wrapper

### Steps to Reproduce the Bug or Issue

无

### Expected behavior

布局失败
![image](https://user-images.githubusercontent.com/86824254/211970363-f940dc73-7b0a-4f4c-8c8f-ab4dc7f6d3d3.png)
![image](https://user-images.githubusercontent.com/86824254/211970429-4b01be4a-d648-45d6-88e5-bce0aa203fb7.png)
期望结果
![image](https://user-images.githubusercontent.com/86824254/211970491-a2778031-6abb-46de-ad65-3390cc21b115.png)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by fishyu199** [comment]
我也遇到了，希望修复

**Comment by zhl0916** [comment]
项目比较紧急，求个修复时间呢~

**Comment by WangHanZ** [comment]
dagre布局的layer本身就是source的layer必须小于target的layer
