### ISSUE TITLE
请问treeGraph下click-select，对于一直按着shift，鼠标点击不能获取到多选结果

### ISSUE THREAD

**Issue by bbaduser** [antvis/G6#4208]
### 问题描述

经测试，treeGraph下一直按着shift，鼠标点击不能获取到多选结果；
相反如果是按下shift，选中后松开，第二次选择再次按下能够多选

### 重现链接

https://codesandbox.io/s/nifty-monad-xkqqwy?file=/index.js

### 重现步骤

按住shift，点击树节点

### 预期行为

打印的nodes为多个

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
因为 G6 的交互监听的 keydown 是当前页面上的事件，像 codesandbox 这样的代码部分和显示部分是不同的 iframe，相当于是不同的页面。demo 中在没有点击画布所在的 iframe 之前，按下 shift，没有被当前 iframe 监听到，此时去点击节点，click-select 认为你没有按下过 shift。如果你在选择节点之前，先让焦点在画布所在的 iframe 上，再按下 shift 后进行选择节点，就可以多选了。

不发生在当前页面上的事件不应被 graph 接收，这个是符合预期的。

**Comment by bbaduser** [comment]
好的 感谢
新年快乐～

**Comment by bbaduser** [comment]
@Yanyan-Wang 感谢回复 新年快乐～
