### ISSUE TITLE
TreeGraphData 中 id 和 label 字段共存，label 的值被 id 替换

### ISSUE THREAD

**Issue by Innei** [antvis/G6#4209]
### Describe the bug

传入 graph data 的如果同时存在 id 和 label，应该是优先显示 label 的。官网文档有提。但是却显示了 id 的值。又排查下来是传入的 data 中的 label 的值都被替换成了 id 的值。

<img width="1345" alt="image" src="https://user-images.githubusercontent.com/41265413/212289621-487112e0-ce7a-44d3-bfcb-be68bb5a4ebb.png">

### Your Example Website or App

https://codesandbox.io/s/suspicious-hoover-9yev6m?file=/src/index.js

### Steps to Reproduce the Bug or Issue

1. Open reproduction https://codesandbox.io/s/suspicious-hoover-9yev6m?file=/src/index.js

### Expected behavior

优先显示 label 的值，不应该替换 label 的值。

### Platform

- OS: macOS
- Browser: Chrome 109

**Comment by Yanyan-Wang** [comment]
你贴的 demo 中，70 行指定了 label 为 id
