### ISSUE TITLE
自定义折线弧度会导致交叉

### ISSUE THREAD

**Issue by zcjpass** [antvis/G6#4210]
### 问题描述

<img width="552" alt="企业微信截图_86a23a6e-699f-4407-8625-27d94ad692d2" src="https://user-images.githubusercontent.com/40134043/212522435-f4b4c1b9-8cdf-4b4e-a0f5-a1cded653d22.png">

自定义折线弧度计算导致出现交叉，请问下这里可以怎么修改

代码如下
function getDistance(p1, p2) {
  return Math.abs(p1.x - p2.x) + Math.abs(p1.y - p2.y);
}

/** 获取圆角控制点，用来绘制圆角 */
function getBorderRadiusPoints(p0, p1, p2, r: number) {
  const d0 = getDistance(p0, p1);
  const d1 = getDistance(p2, p1);

  if (d0 < r) {
    r = d0;
  }

  if (d1 < r) {
    r = d1;
  }

  const ps = {
    x: p1.x - (r / d0) * (p1.x - p0.x),
    y: p1.y - (r / d0) * (p1.y - p0.y),
  };
  const pt = {
    x: p1.x - (r / d1) * (p1.x - p2.x),
    y: p1.y - (r / d1) * (p1.y - p2.y),
  };
  return [ps, pt];
}

/** 获取附带圆角的完整path */
function getPathWithBorderRadius(startPoint, endPoint) {
  //获取两个连接锚点之间所有可连接的合法点（可连为连线折点的点，
  //目前连线方向设置为横向和纵向，所以可以取各横线和纵线连线的交点
  const controlPoints = [
    startPoint,
    {
      x: endPoint.x / 3 + (2 / 3) * startPoint.x,
      y: startPoint.y,
    },
    {
      x: endPoint.x / 3 + (2 / 3) * startPoint.x,
      y: endPoint.y,
    },
    endPoint,
  ];
  let path = [['M', startPoint.x, startPoint.y]];
  controlPoints.forEach((currentPoint, idx) => {
    const p1 = controlPoints[idx + 1];
    const p2 = controlPoints[idx + 2];
    if (!p1 || !p2) return;
    // 在中点增加一个矩形，注意矩形的原点在其左上角
    const radiusPoint = getBorderRadiusPoints(currentPoint, p1, p2, 12);
    const [ps, pt] = radiusPoint;
    path = path.concat([
      ['L', ps.x, ps.y],
      ['Q', p1.x, p1.y, pt.x, pt.y],
      ['L', pt.x, pt.y],
    ]);
  });
  path.push(['L', endPoint.x, endPoint.y]);
  return path;
}

const bizMindEdge: CustomEdge = {
  options: {
    style: {
      stroke: '#ccc1d8',
      lineWidth: 4,
      shadowColor: null,
      shadowBlur: 0,
      position: 'middle',
    },
    stateStyles: {
      [ItemState.Selected]: {
        stroke: '#5aaaff',
        shadowColor: '#5aaaff',
        shadowBlur: 24,
      },
      [ItemState.HighLight]: {
        stroke: '#5aaaff',
        shadowColor: '#5aaaff',
        shadowBlur: 24,
      },
    },
  },
  draw(config: ModelConfig, group: any): any {
    const startPoint = config.startPoint;
    const endPoint = config.endPoint;
    const path = getPathWithBorderRadius(startPoint, endPoint);
    // 在中点增加一个矩形，注意矩形的原点在其左上角
    const keyShape = group.addShape('path', {
      attrs: {
        stroke: '#9CA1BA',
        lineWidth: 2,
        path,
        lineAppendWidth: 20,
        cursor: 'pointer',
      },
      draggable: true,
      className: 'edge-shape',
    });
    return keyShape;
  },

  setState(name, value, item) {
    const shape: GShape = item.get('keyShape');

    if (!shape) {
      return;
    }

    const { style, stateStyles } = this.options;

    const stateStyle = stateStyles[name];

    if (!stateStyle) {
      return;
    }

    if (value) {
      shape.attr({
        ...style,
        ...stateStyle,
      });
    } else {
      shape.attr(style);
    }
  },
};

G6.registerEdge('bizMindEdge', bizMindEdge);

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
建议折线拐点曲线的起点位置，根据上一个曲线的终点进行动态调整，例如：

```javascript
/** 获取附带圆角的完整path */
function getPathWithBorderRadius(startPoint, endPoint) {
  //获取两个连接锚点之间所有可连接的合法点（可连为连线折点的点，
  //目前连线方向设置为横向和纵向，所以可以取各横线和纵线连线的交点
  const controlPoints = [
    startPoint,
    {
      x: endPoint.x / 3 + (2 / 3) * startPoint.x,
      y: startPoint.y,
    },
    {
      x: endPoint.x / 3 + (2 / 3) * startPoint.x,
      y: endPoint.y,
    },
    endPoint,
  ];
  let path = [['M', startPoint.x, startPoint.y]];
  // 缓存上一个曲线的结束为止
  let lastEnd;
  controlPoints.forEach((currentPoint, idx) => {
    const p1 = controlPoints[idx + 1];
    const p2 = controlPoints[idx + 2];
    if (!p1 || !p2) return;
    // 在中点增加一个矩形，注意矩形的原点在其左上角
    const radiusPoint = getBorderRadiusPoints(currentPoint, p1, p2, 12);
    const [ps, pt] = radiusPoint;
    // 计算当前曲线起点与上个曲线结束为止的 y 轴距离
    const distToLastEnd = lastEnd ? Math.abs(ps.y - lastEnd.y) : Infinity
    // 如果距离过小（小于曲线半径），则使用上个曲线的结束为止，作为当前曲线的起点
    const start = distToLastEnd < 12 ? lastEnd || ps : ps;
    path = path.concat([
      ['L', start.x, start.y],
      ['Q', p1.x, p1.y, pt.x, pt.y],
      ['L', pt.x, pt.y],
    ]);
    lastEnd = pt;
  });
  path.push(['L', endPoint.x, endPoint.y]);
  return path;
}
```
