### ISSUE TITLE
dagre布局，请问如何让图形在水平居中，垂直不居中

### ISSUE THREAD

**Issue by doublestar2017** [antvis/G6#4211]
### 问题描述

我使用的dagre布局，请问如何配置可以让图形位于整个画布，在水平方位居中，但垂直方位不居中？非常感谢

### 重现链接

截图所示

### 重现步骤

截图所示

### 预期行为

截图所示

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.7.6 ... ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/28668703/212587772-f455d74f-72d4-4a0a-af1c-ab2c30de99a8.png)

**Comment by Yanyan-Wang** [comment]
dagre 布局可以配置 begin http://g6.antv.antgroup.com/api/graphlayout/dagre

graph.getViewPortCenterPoint() 可以获取当前画布的中心点坐标 http://g6.antv.antgroup.com/api/graphfunc/coordinate#graphgetviewportcenterpoint

**Comment by doublestar2017** [comment]
非常感谢

**Comment by doublestar2017** [comment]
已解决

**Comment by LeeeeeeM** [comment]
graph.data(data);
      graph.render();
      requestAnimationFrame(() => {
        const graphCenter = graph.getGraphCenterPoint();
        const viewCenter = graph.getViewPortCenterPoint();
        graph.translate(viewCenter.x - graphCenter.x, 0);
      });
