### ISSUE TITLE
使用流水线子图布局时能否启用 web-worker

### ISSUE THREAD

**Issue by wuxt-dev** [antvis/G6#4213]
### 问题描述

使用流水线子图布局时能否启用 web-worker

### 重现链接

null

### 重现步骤

null

### 预期行为

null

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
每个布局应该可以配置 workerEnabled

**Comment by wuxt-dev** [comment]
谢谢大佬！
