### ISSUE TITLE
节点名称包含 <   或者  > 会报错

### ISSUE THREAD

**Issue by wu0211** [antvis/G6#4215]
### Describe the bug

在树形图中，界面名称包含   < 或者  > 会报错

名称例如：UGD<UGS(off)

<img width="641" alt="image" src="https://user-images.githubusercontent.com/34398833/212843439-ebf5700b-f2c9-400e-9c2b-427764acb734.png">

<img width="605" alt="image" src="https://user-images.githubusercontent.com/34398833/212843311-e81c587e-0f34-49c4-b5eb-a676d86cb2f9.png">

### Your Example Website or App

no

### Steps to Reproduce the Bug or Issue

数据渲染

### Expected behavior

数据渲染

### Platform

引入的库版本
<script
      type="text/javascript"
      charset="utf-8"
      src="https://gw.alipayobjects.com/os/lib/antv/g6/4.5.0/dist/g6.min.js"
    ></script>

**Comment by Yanyan-Wang** [comment]
在官网上没有复现，使用最新版本试试 https://gw.alipayobjects.com/os/lib/antv/g6/4.8.2/dist/g6.min.js

不行的话提供一下在线复现的 demo
