### ISSUE TITLE
"contextmenu" event strange behavior in Chrome/Safari on OSX M1 (not Firefox)

### ISSUE THREAD

**Issue by pl7y** [antvis/G6#4221]
### Describe the bug

When you right-click on a node, the system context menu opens correctly; when you click outside to discard the context menu and move the mouse, the mouse starts dragging around the node on which you initially opened the context menu.

### Your Example Website or App

https://g6.antv.antgroup.com/en/examples/net/radialLayout#interactRadial and the older https://antv-g6.gitee.io/en/examples/net/radialLayout#interactRadial

### Steps to Reproduce the Bug or Issue

1. Open official G6 examples;
2. Go to ["Interactively Expand a Node" example](https://g6.antv.antgroup.com/en/examples/net/radialLayout#interactRadial); in this sample, you can select nodes with a click and drag them keeping the left button down and moving the mouse;
3. Right click on a node and watch the browser context menu open;
4. Click somewhere else on the graph and watch the browser context menu close;
5. Now mouse interaction with the graph is corrupted: moving the mouse causes the node to be dragged around even if no mouse button is pressed; if you single click another node, you don't select it but instead you start dragging it even if no mouse button is pressed; If you double click the graph, the mouse behavior sometimes appears to reset and graph starts behaving like in bullet 2, but things may start to behave weirdly (e.g. more than one node can have the selected status, a thing that doesn't happen in the initial condition of bullet 2).

### Expected behavior

As a user, I expected that opening the context menu doesn't corrupt mouse interaction with the graph (i.e. that you can continue to select nodes with a click and drag them keeping the left button down and moving the mouse).

### Screenshots or Videos

https://user-images.githubusercontent.com/10465876/214839219-cb14a612-8788-456f-b2de-a17e013d4a02.mov

### Platform

- OS: macOS Ventura 13.1 (22C65)
- Browser: Chrome Version 108.0.5359.124 (Official build) (arm64), Chrome 109.0.5414.119 (Official build) (arm64), Safari Version 16.2 (18614.3.7.1.5)
- Version: 4.3.2, 4.8.5

**Comment by Yanyan-Wang** [comment]
Demos and docs on the domain https://antv-g6.gitee.io is outdated, and we are not able to update it currently. See the demo on https://g6.antv.antgroup.com/en/examples/net/radialLayout#interactRadial

And it is correct as expected

**Comment by pl7y** [comment]
Thanks for the reply. You are correct, the demo at your link works correctly so the issue can be closed.
Do you have any hint on what can cause that problem?

**Comment by pl7y** [comment]
> Thanks for the reply. You are correct, the demo at your link works correctly so the issue can be closed. Anyway I still have the same issue in an application I am writing, even using 4.8.5, so I suspect it's something else than G6; in case you have any hint on what can cause the problem on the https://antv-g6.gitee.io/ sample, please reply. Thanks anyway!

Sorry, I rushed the test in reply to your post didn't realise that I was using Firefox; both https://antv-g6.gitee.io/en/examples/net/radialLayout#interactRadial and https://g6.antv.antgroup.com/en/examples/net/radialLayout#interactRadial using Chrome Version 109.0.5414.119 (Official build) (arm64) do fail in the same way as the video. So they do in Safari Version 16.2 (18614.3.7.1.5). Firefox 108.0.2 (64 bit) instead works.

**Comment by Yanyan-Wang** [comment]
The problem is already solved by 4.8.x. You could see the demo here https://codesandbox.io/s/epic-wescoff-t41ve9 
(codesandbox has the latest dependencies by default)

G6's website depends on @antv/g6@4.7.x now, I will upgrade the it ASAP. You could upgrade @antv/g6 in your project to see whether the problem still exist.

**Comment by Yanyan-Wang** [comment]
Upgrade g6 to v4.8.7 in your project and try again pls.

P.S. the g6 website's dependency is not updated yet, so you might not get the latest result on the website currently. I will update it ASAP

**Comment by pl7y** [comment]
I am sticking to 4.8.1 as when I install 4.8.7 in an Angular app I get the following error on `ng serve` (using typescript 4.8.2), so I thought typings were broken in latest releases:

```
Error: node_modules/@antv/g6-pc/lib/graph/tree-graph.d.ts:124:5 - error TS2416: Property 'data' in type 'TreeGraph' is not assignable to the same property in base type 'ITreeGraph'.
  Type '(data?: TreeGraphData | undefined) => void' is not assignable to type '(data?: TreeGraphData | GraphData | undefined) => void'.
    Types of parameters 'data' and 'data' are incompatible.
      Type 'TreeGraphData | GraphData | undefined' is not assignable to type 'TreeGraphData | undefined'.
        Property 'id' is missing in type 'GraphData' but required in type 'TreeGraphData'.

124     data(data?: TreeGraphData): void;
        ~~~~

  node_modules/@antv/g6-core/lib/types/index.d.ts:386:5
    386     id: string;
            ~~
    'id' is declared here.
```

**Comment by pl7y** [comment]
I manually applied the Typescript definition fixes of PR https://github.com/antvis/G6/pull/4312 to test 4.8.7, and still context menu doesn't work properly.

Even in the official example https://g6.antv.antgroup.com/en/examples/net/radialLayout#interactRadial in Chrome 109.0.5414.119 (Official build) (arm64), if one opens the context menu then mouse clicks begin to behave strangely (nodes can't be dragged, or you can select multiple nodes, and so on). 4.8.7 seems to fix only the fact that after closing the context menu the right-clicked node is not dragged on mousemove.
