### ISSUE TITLE
TreeGraph updateChildren当子节点超过一定数量时, 丢失原节点

### ISSUE THREAD

**Issue by qingmuAdore** [antvis/G6#4226]
### 问题描述

采用TreeGraph 绘制树图.  测试updateChildren, 实测在1~3k绘图正常, 当新增的子节点在4000+时, 绘图将丢失原有节点

### 重现链接

https://codepen.io/qingmuAdore/pen/ExppNzm

### 重现步骤

1.  设置添加的节点数量4000
2.  点击添加按钮

### 预期行为

我期望看到不影响原有的节点

### 平台

- 操作系统: win11
- 网页浏览器: [Google Chrome]
- G6 版本: [4.8.2]

### 屏幕截图或视频（可选）

![异常图](https://user-images.githubusercontent.com/7962582/215316933-2f30dded-104e-4a58-9706-5ef49704d6c0.png)
![正常](https://user-images.githubusercontent.com/7962582/215316938-47c4c1d7-cbf9-4fdc-bc00-b43017225240.png)

**Comment by qingmuAdore** [comment]
异常现象

**Comment by Yanyan-Wang** [comment]
你发的 demo 里面好像没有发现节点丢失呢

**Comment by qingmuAdore** [comment]
@Yanyan-Wang 
汗!!  我这边4000设置会一直复现. 要不你这边刷新浏览器后,值设置大一点如: 1w或更多试试
