### ISSUE TITLE
legend插件如何自动更新

### ISSUE THREAD

**Issue by MinorN** [antvis/G6#4227]
### 问题描述

动态修改图中内容，希望图例插件也会随之变动

### 重现链接

none

### 重现步骤

none

### 预期行为

动态修改图中内容，希望图例插件也会随之变动

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
legend 的数据是实例化的时候传给它的，不是根据 graph 数据生成的，通过 legend.changeData 可以更新

**Comment by MinorN** [comment]
已解决，谢谢
