### ISSUE TITLE
indented tree 节点大小不一样时，第一个节点默认展开其他节点收起，展开收起的节点会覆盖上层节点

### ISSUE THREAD

**Issue by rainLeaf888** [antvis/G6#4228]
### Describe the bug

layout的type = ‘indented, https://github.com/antvis/G6/issues/4200解决同级大小不一样时，节点覆盖问题 ，升级到@antv/hierarchy@0.6.9 当第一个节点展开，同级节点收起时，再展同级节点收起的节点时，子节点会覆盖如图：
![image](https://user-images.githubusercontent.com/24802442/215461757-e7117878-21f6-42df-a5db-a54e483e2eb1.png)

![image](https://user-images.githubusercontent.com/24802442/215461640-8da95984-ce18-4a87-8941-89c1d09dc443.png)

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

根节点下的第一个节点默认展开，其他节点收起，第一个展开的节点与第二个收起的节点间距应该是第一个展开子节点的所有高度和

### Expected behavior

期望打开节点时，不存在覆盖情况

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
给个在线复现的 demo？感觉应该和 getHeight 返回值、自定义节点原点位置有关

**Comment by rainLeaf888** [comment]
https://codesandbox.io/s/dry-water-61gtfk?file=/index.js
默认「广告位」这个节点展开，其他子节点收起，在点开 「客户一级行业」 节点展开就会覆盖，麻烦看看是不是我哪里有问题
如果「10004」这个节点没有子节点时，「客户一级行业」这个节点位置展示正常，有子节点之后 「客户一级行业」位置就不太对

**Comment by Yanyan-Wang** [comment]
目前是否和 https://github.com/antvis/G6/issues/4261 同一个问题？是的话这个就先关掉了。试下 @antv/hierarchy 0.6.11
