### ISSUE TITLE
G6文档api页无法查看'Graph 实例方法'和'图布局 Graph Layout'内容

### ISSUE THREAD

**Issue by Jalery521** [antvis/G6#4232]
### 问题描述

如标题所述

### 重现链接

https://g6.antv.antgroup.com/api/graph

### 重现步骤

点击左侧navBar的'Graph 实例方法'或'图布局 Graph Layout'会重定向到'图配置 G6.Graph(cfg)'页面

### 预期行为

修复文档页面问题

### 平台

- 操作系统:Windows
- 网页浏览器: Google Chrome
- G6 版本: 4.8.4

**Comment by Aicmortal** [comment]
+1

**Comment by OmegaChan** [comment]
+1

**Comment by Yanyan-Wang** [comment]
抱歉，今晚可修复

**Comment by Yanyan-Wang** [comment]
已修复
