### ISSUE TITLE
想通过translate和moveTo来平移画布 需要获取某个时刻画布的具体坐标

### ISSUE THREAD

**Issue by xiaojueji** [antvis/G6#4235]
### 问题描述

具体操作如下：画布初始化渲染后 拖动鼠标移动画布，此时需要记录画布的一个位置（x,y 的坐标？）然后在符合某个条件时通过translate或moveTo API将画布移动到跟初始记录的位置一样的地方 但是现在没有明显的api来获取画布平移后的具体位置信息
或者有没有其他的思路和方法 多谢解答！

### 重现链接

如描述

### 重现步骤

如描述

### 预期行为

如描述

### 平台

- 操作系统: [macOS.]
- 网页浏览器: [Google Chrome]
- G6 版本: [^4.6.16 ]

**Comment by Yanyan-Wang** [comment]
`graph.getGraphCenterPoint()` 获取当前图内容的中心绘制坐标，比如在初始时记录当前的中心坐标 center1, 后面再想回到原来位置的时候，再次用这个 API 获取当前中心坐标 center2，相对移动向量就是 center1 - center2, 然后用  `graph.translate`  移动这个向量
