### ISSUE TITLE
通过emit触发的节点点击事件，回调函数中的fitView不能正常执行

### ISSUE THREAD

**Issue by wuxt-dev** [antvis/G6#4238]
### 问题描述

通过鼠标点击触发的点击事件，可以正常调用graph.fitView
通过emit事件触发的节点点击事件，graph.fitView不能实现预期效果

### 重现链接

https://codesandbox.io/s/g6-fitviewpadding-m55i0y?file=/src/index.js:0-1055

### 重现步骤

进入页面，点击节点，graph.fitView实现预期效果
取消注释最后一行通过emit触发点击事件，从控制台可以看到点击事件被触发，但是graph.fitView没有效果

### 预期行为

通过emit触发和通过鼠标点击触发graph.fitView达到相同效果

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
pipe 布局是异步的，你这里渲染后立刻调用 emit，此时，布局还没有完成，所以拿不到正确的图大小，可以在 graph.on('afterlayout', e => {}) 里面去 emit

**Comment by wuxt-dev** [comment]
> pipe 布局是异步的，你这里渲染后立刻调用 emit，此时，布局还没有完成，所以拿不到正确的图大小，可以在 graph.on('afterlayout', e => {}) 里面去 emit

在afterlayout里触发节点点击后，fitView还是没有生效，还是需要手动点击才生效

**Comment by wuxt-dev** [comment]
> pipe 布局是异步的，你这里渲染后立刻调用 emit，此时，布局还没有完成，所以拿不到正确的图大小，可以在 graph.on('afterlayout', e => {}) 里面去 emit

原来是异步，谢谢大佬！
