### ISSUE TITLE
链接跳转异常

### ISSUE THREAD

**Issue by OmegaChan** [antvis/G6#4244]
### 问题描述

1.图布局 Graph Layout中的导览及使用中的内置布局导览链接跳转异常
2.API介绍缺少图例，而大多API都跟图可视化息息相关，希望适当增加，增加阅读性

### 重现链接

/api/graph-layout/guide/random

### 重现步骤

同问题描述

### 预期行为

同问题描述

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/48882058/216253900-95d575dc-271d-4d60-a49b-326d0cfb7590.png)

### 补充说明（可选）

无

**Comment by Yanyan-Wang** [comment]
你说的图例是指？

**Comment by Yanyan-Wang** [comment]
链接跳转问题已修复，感谢报告

**Comment by bbaduser** [comment]
> 链接跳转问题已修复，感谢报告

G6文档中 很多时常点过去页面404 了

**Comment by Yanyan-Wang** [comment]
上周修复了一波，如果还有出现 404 方便的话麻烦贴一下

**Comment by bbaduser** [comment]
> 上周修复了一波，如果还有出现 404 方便的话麻烦贴一下

6666

**Comment by bbaduser** [comment]
> 上周修复了一波，如果还有出现 404 方便的话麻烦贴一下

@Yanyan-Wang  点击实践会404
https://antv-g6.gitee.io/zh/docs/api/graphFunc/state/#graphsetitemstateitem-state-value
<img width="1333" alt="image" src="https://user-images.githubusercontent.com/120174736/221522779-ba9da959-df31-415c-b8db-1227bb3f5465.png">

**Comment by Yanyan-Wang** [comment]
都用 https://g6.antv.antgroup.com 这个域名哈，gitee 域名不再更新了。对应的文档地址：
https://g6.antv.antgroup.com/api/graph-func/state#graphsetitemstateitem-state-value
