### ISSUE TITLE
 节点数量多，切换布局卡死

### ISSUE THREAD

**Issue by Caesar1226** [antvis/G6#4248]
### 问题描述

节点有2000个，线1000个，grid布局，切换为辐射布局，页面卡死

### 重现链接

 1

### 重现步骤

1

### 预期行为

1

### 平台

- 操作系统: [macOS, Windows]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
给一个在线复现的 demo 看看？
可以跟着这个教程优化看看：http://g6.antv.antgroup.com/manual/faq/performance-opt

**Comment by Tina75** [comment]
同遇到这个问题，1000个节点就卡住了，要至少2秒才能加载出来
