### ISSUE TITLE
使用antv G6 TreeGraph  direction:TB绘制树形图表；预期：二级子节点纵向排列；

### ISSUE THREAD

**Issue by siwenyu** [antvis/G6#4249]
### 问题描述

问题背景：
使用antv G6 TreeGraph 绘制树形图表；二级子节点纵向排列；
求助：
源码在这里：https://codesandbox.io/s/jolly-star-j340do?file=/src/components/H1.vue

### 重现链接

https://codesandbox.io/s/jolly-star-j340do?file=/src/components/H1.vue

### 重现步骤

进入页面，随便修改一行代码，保存。
点击加号可复现

### 预期行为

希望叶子节点纵向对齐

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]
macOS  网页；版本：4.8.5

### 屏幕截图或视频（可选）

<img width="817" alt="image" src="https://user-images.githubusercontent.com/9636014/216933410-9bd4e1d9-fdd7-40e0-99f4-b562811f194a.png">

**Comment by Yanyan-Wang** [comment]
没有内置布局直接支持，可以自定义树图布局，TreeGraph 的 layout 配置：
layout: data => {
  // 这里可以使用 @antv/hierarchy 的不同布局，对不同子树计算
// 算出位置后 x y 给到相应的节点数据上，然后返回数据
return calculatedData
}
