### ISSUE TITLE
文档上 基础事件-->canvas:mousemove描述错误

### ISSUE THREAD

**Issue by yi8wen8san8bu8zhi** [antvis/G6#4250]
### 问题描述

文档原文：| canvas:mousemove | 鼠标在画布内部移到时不断触发，不能通过键盘触发 |，描述错误

### 重现链接

https://g6.antv.antgroup.com/api/event

### 重现步骤

1，进入基础事件页面，https://g6.antv.antgroup.com/api/event
2，基础事件下的Canvas 交互事件
3，canvas:mousemove事件的描述

### 预期行为

| canvas:mousemove | 鼠标在画布内部移动时不断触发，不能通过键盘触发 |

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/44592455/216899468-1195e496-7ebf-4d80-a502-75a6b3ff3846.png">

**Comment by Yanyan-Wang** [comment]
好的，移到 -> 移动

**Comment by Yanyan-Wang** [comment]
已解决
