### ISSUE TITLE
wrong jump page in keywords-search result of G6 document

### ISSUE THREAD

**Issue by hi-sunshine** [antvis/G6#4252]
### Describe the bug

when you want to search some keywords in G6 document，the right related result will show you. But if you click the item in search result， it always jump to the wrong page.

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/16054648/216955280-fd607d5e-5c32-4d62-814d-7bf95cb5019c.png">

### Your Example Website or App

G6 Official Website

### Steps to Reproduce the Bug or Issue

1、search a keyword in G6 doc search input
2、click a item in result list
3、it jump to wrong page

### Expected behavior

click the keywords-search result item, ant it jump to the related page

### Screenshots or Videos

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/16054648/216955280-fd607d5e-5c32-4d62-814d-7bf95cb5019c.png">

### Platform

platform Independent

**Comment by Yanyan-Wang** [comment]
We are still applying algolia docsearch for the new domain .antgroup now. It maybe ready in 2 weeks.

**Comment by Yanyan-Wang** [comment]
fixed, thanks for reporting
