### ISSUE TITLE
zoomTo 方法未指定 center 参数时，进行缩放会产生位移

### ISSUE THREAD

**Issue by yinjialu** [antvis/G6#4254]
### Describe the bug

参考官网案例：https://g6.antv.antgroup.com/zh/examples/tool/toolbar/#toolbar

即使通过 getViewPortCenterPoint 获取视口中心绘制坐标设置为 center 依然会出现位移

### Your Example Website or App

https://g6.antv.antgroup.com/zh/examples/tool/toolbar/#toolbar

### Steps to Reproduce the Bug or Issue

1. 点击放大按钮
2. 视图放大，同时出现位移

### Expected behavior

放大功能只缩放图形，不产生位移

zoom-canvas 模式下以当前鼠标所在点为圆心进行放大
使用 toolbar 时预期以视口中心为圆形进行放大，不产生平移

### Platform

- OS: [e.g. macOS, Windows, Linux] MacOS
- Browser: [e.g. Chrome, Safari, Firefox] Chrome
- Version: [e.g. 91.1] 109.0.5414.119

**Comment by Yanyan-Wang** [comment]
可以自己给 zoomTo 指定 center，否则缩放中心可能在左上角，所以看起来好像有位移，但并不是真正的位移。获取当前视口中心的绘制坐标：http://g6.antv.antgroup.com/api/graph-func/coordinate#graphgetviewportcenterpoint

**Comment by yinjialu** [comment]
```js
const viewPortCenterPoint = graphInstance.getViewPortCenterPoint();
graphInstance.zoomTo(z, viewPortCenterPoint, true);
```
尝试通过 `getViewPortCenterPoint` 获取视口中心的坐标用于 `zoomTo` 的 center，但还是有位移

**Comment by Yanyan-Wang** [comment]
可能你图内容的中心不在视口中心？用图内容的中心 `graph.getGraphCenterPoint()`

可以理解一下这几个中心的含义，就会比较清楚

http://g6.antv.antgroup.com/api/graph-func/coordinate

**Comment by yinjialu** [comment]
今天又试了下，还是用的 `getViewPortCenterPoint` 居然可以了，感谢支持
