### ISSUE TITLE
孙节点或后代节点如何改变左右方向？

### ISSUE THREAD

**Issue by 1326058321** [antvis/G6#4258]
### 问题描述

孙节点或后代节点如何改变左右方向？

### 重现链接

孙节点或后代节点如何改变左右方向？

### 重现步骤

孙节点或后代节点如何改变左右方向？

### 预期行为

孙节点或后代节点如何改变左右方向？

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![1](https://user-images.githubusercontent.com/66524961/217457536-7f2f4849-5323-40eb-bc87-358c3dfc9f34.png)

**Comment by Yanyan-Wang** [comment]
只支持根节点的第一层子节点设置 getSide。你也可以自定义布局，TreeGraph 的 layout 配函数，参数是数据，给每个节点算好 x y 写进数据再返回就好
