### ISSUE TITLE
indented tree 节点大小不一样时,  后续节点收起，再展开收起节点时会存在覆盖

### ISSUE THREAD

**Issue by rainLeaf888** [antvis/G6#4261]
### 问题描述

![image](https://user-images.githubusercontent.com/24802442/217988433-5390e12f-cbcc-42a0-b495-e1042db3477e.png)

![image](https://user-images.githubusercontent.com/24802442/217988302-029b0c4f-f6df-45da-9de6-bd08ff6539ad.png)
图1中，1的坐标位置 = 3的坐标y+高度 ， 因为 3是折叠起来的，最终1的坐标位置 < 2的坐标位置+2的高度, 再次展开1时，1节点后的子节点y跟1节点一样，就会覆盖2节点。

### 重现链接

https://codesandbox.io/s/dry-water-61gtfk?file=/index.js

### 重现步骤

初始化1节点坐标y就不对, demo 中 「客户一级行业」初始化位置不对，展开「平台」之后，「客户一级行业」位置就正确了

### 预期行为

期望1节点的子节点展开，不会覆盖2节点

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by rainLeaf888** [comment]
@Yanyan-Wang 麻烦抽空帮忙看看， @antv/hierarchy 的 0.6.9版本的  hierarchy/src/layout/indented.js 中的positionNode node.y的坐标计算方式还有不完成，尤其树底层节点是折叠起来的时候

**Comment by rainLeaf888** [comment]
@Yanyan-Wang 
以下贴的代码是我目前实现可以解决此问题的，期望官方可以看看，是否收录然后发正式版本
更改 hierarchy/src/layout/indented.js 中的positionNode计算node.y 的坐标
代码如下：
 if (previousNode) {
    var _previousNode$parent;
    node.y = previousNode.y + util.getHeight(previousNode, node, align);
    if (node.parent.id !== ((_previousNode$parent = previousNode.parent) == null ? void 0 : _previousNode$parent.id)) {
      // previous node has different parent
      var index = node.parent.children.findIndex(function (n) {
        return n.id === node.id;
      });
      var preNode = node.parent.children[index - 1];
      if (preNode) {
        var preY = preNode.y + util.getHeight(preNode, node, align);
        
        var preChildNode = preNode.children.slice(-1)[0]
        // 中间有间隔节点
        if (preChildNode.id !== previousNode.id) {
          var ny = preChildNode.y + util.getHeight(preChildNode, node, align)
          node.y = ny > preY && ny > node.y ? ny : (preY > node.y ? preY : node.y);
        } else {
        node.y = preY > node.y ? preY : node.y;
      }
      }
    }
  } else {
    node.y = 0;
  }

**Comment by Yanyan-Wang** [comment]
@antv/hierarchy 0.6.11 试一下
