### ISSUE TITLE
使用G6生成图表的几个疑问,望能解答

### ISSUE THREAD

**Issue by auuunya** [antvis/G6#4262]
### 问题描述

疑问：一开始就使用addItem去添加节点与边,然后调用refresh()刷新,如果layout指定了常见的布局方案,所有节点都重叠在一块,而且边连线消失,只有移动相关联的两个节点边线才会出现,在此期间没有使用graph.data与graph.render.
这种情况是不是需要去自定义布局才可以解决？

### 重现链接

rt

### 重现步骤

rt

### 预期行为

rt

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
addItem 后不需要调用 refresh()。新增节点不会触发重新布局，如果需要重新布局，调用 graph.layout()

**Comment by auuunya** [comment]
@Yanyan-Wang 谢谢您的回答
