### ISSUE TITLE
开发环境和生产环境图表展示状态不一致

### ISSUE THREAD

**Issue by Tyh2001** [antvis/G6#4263]
### 问题描述

开发环境和生产环境图表展示状态不一致

### 重现链接

无

### 重现步骤

无

### 预期行为

开发环境和生产环境图表展示状态不一致

### 平台

windows 11 chrome

### 屏幕截图或视频（可选）

![1bf582a21120a5f65b2a11c932ded0e](https://user-images.githubusercontent.com/73180970/217994911-e5f1098c-0fbf-48ef-9d88-a5268b4459b6.png)
![8d17e699556e7fa1c8a09e599146cd6](https://user-images.githubusercontent.com/73180970/217994925-c1f6ef7d-b12b-4c21-8061-1a965e11da81.png)

**Comment by Yanyan-Wang** [comment]
看下本地和线上版本的区别

**Comment by Tyh2001** [comment]
> 看下本地和线上版本的区别

更新最新版本已经解决
