### ISSUE TITLE
addItem新增后的点坐标有没有一个合适的算法啊，因为需求是点击一个点远程搜索出相关联的其他点来进行连线展示，目前遇到的问题就是新增加点的坐标没法计算导致整个布局很丑

### ISSUE THREAD

**Issue by 18714984191** [antvis/G6#4266]
### 问题描述

addItem新增后的点坐标有没有一个合适的算法啊，因为需求是点击一个点远程搜索出相关联的其他点来进行连线展示，目前遇到的问题就是新增加点的坐标没法计算导致整个布局很丑

### 重现链接

https://codepen.io/JF12345/pen/qByeXxz

### 重现步骤

1.点击任意一个点后新增n个点并创建边
2.查看新增点位置

### 预期行为

希望可以合适布局，不会遮挡其他已存在的点位

### 平台

- 操作系统: [Windows.]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.7.1]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/54229220/218251211-14fadc5d-8204-4bf5-9ccb-f6dabf0ac172.png)

### 补充说明（可选）

业务场景：点击某个节点搜索出与这个点有关联的其他点并进行连线，要求已出现的点位置不变

**Comment by Yanyan-Wang** [comment]
你的 demo 里面压根没给 graph 配置布局。graph 配置合适的 layout https://g6.antv.antgroup.com/api/graph-layout/guide，然后新增完节点之后也要重新调用一下 graph.layout

**Comment by 18714984191** [comment]
> 你的 demo 里面压根没给 graph 配置布局。graph 配置合适的 layout [https://g6.antv.antgroup.com/api/graph-layout/guide，然后新增完节点之后也要重新调用一下](https://g6.antv.antgroup.com/api/graph-layout/guide%EF%BC%8C%E7%84%B6%E5%90%8E%E6%96%B0%E5%A2%9E%E5%AE%8C%E8%8A%82%E7%82%B9%E4%B9%8B%E5%90%8E%E4%B9%9F%E8%A6%81%E9%87%8D%E6%96%B0%E8%B0%83%E7%94%A8%E4%B8%80%E4%B8%8B) graph.layout

感谢解答，已经解决了，先把原先画布上存在的点位置给记录下来，用的changeData的时候再把已存在的点位置固定
