### ISSUE TITLE
在设置fitViewPadding为0时，为什么有些情况下fitView会充满整个画布，有些情况下画布周边会有留白

### ISSUE THREAD

**Issue by wuxt-dev** [antvis/G6#4267]
### 问题描述

在设置fitViewPadding为0时，为什么有些情况下fitView会充满整个画布，有些情况下画布周边会有留白

### 重现链接

null

### 重现步骤

null

### 预期行为

null

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
给个在线复现 demo 看看
