### ISSUE TITLE
在使用自定义元素 注册节点的时候 如果有text节点那么 minimap的大小会出问题

### ISSUE THREAD

**Issue by kkeyubin** [antvis/G6#4268]
### 问题描述

在使用自定义元素 注册节点的时候 如果有text节点那么 minimap的大小会出问题，在CodeSandbox中如果注册 text 节点则minimap中所有节点均变小 无法看清

### 重现链接

https://codesandbox.io/s/g6-minimap-nz6ig8?file=/src/GraphMixins.js

### 重现步骤

1.进入页面将文档拉到最下方 看到minimap 此时minimap完全无法看清。
2.注释掉49行的代码 刷新页面 minimap可以看清且一切功能正常

### 预期行为

希望看到完整的minimap

### 平台

- 操作系统: [ Windows]
- 网页浏览器: [Google Chrome]
- G6 版本:  "@antv/g6": "^4.8.4",

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/76641542/218355670-c7267387-f9bc-4b9d-ad00-37189f9253bb.png)
![image](https://user-images.githubusercontent.com/76641542/218355741-3d899c17-0e23-4d18-80f5-bb94ae85cd18.png)

**Comment by Yanyan-Wang** [comment]
你这里 label 图形 attrs 有问题：1. 没给 x；2. fontSize 是 number 类型
