### ISSUE TITLE
配置fx,fy 节点防重叠失效

### ISSUE THREAD

**Issue by songxiaoyu321** [antvis/G6#4269]
### 问题描述

搜索出第一批点，动画结束后给点固定fx,fy（）
![WechatIMG1](https://user-images.githubusercontent.com/51144045/218360386-00f10d62-e8ee-468f-b0ed-b42045359800.jpeg)
搜索出第二批点，动画结束后给点固定fx,fy
![WechatIMG2](https://user-images.githubusercontent.com/51144045/218360438-589d26b0-31eb-488e-b972-30fd91d69d26.jpeg)
搜索出第三批点，动画结束后给点固定fx,fy
![WechatIMG3](https://user-images.githubusercontent.com/51144045/218360464-e0775d0c-ae3f-485d-bc7e-a1dabf314c89.jpeg)
以次类推，点重叠的会越来越多
// layout 配置
export const layout = {
  type: 'gForce',
  preventOverlap: true, // 防止重叠
  nodeSize: 160, // 防止重叠，必须属性 nodeSize,
  gravity: 50
}
发现配置了fx，fy时preventOverlap失效，如何解决呢？
因为每次搜索出来的点，新的点出来时，不希望改变之前点的位置，所以无法去掉fx,fy

### 重现链接

无

### 重现步骤

同问题描述

### 预期行为

同问题描述

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
给个在线复现的 demo 看看
