### ISSUE TITLE
新版搜索无法搜到

### ISSUE THREAD

**Issue by bbaduser** [antvis/G6#4272]
### 问题描述

<img width="1322" alt="image" src="https://user-images.githubusercontent.com/120174736/218373599-b3a27313-7671-4a45-9904-7bcc052751d7.png">

### 重现链接

https://g6.antv.antgroup.com/

### 重现步骤

搜索 modelRect

### 预期行为

<img width="532" alt="image" src="https://user-images.githubusercontent.com/120174736/218373665-5c6483a5-4d30-4913-9fc4-741cba06c4bf.png">

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.8.5 ... ]

**Comment by Yanyan-Wang** [comment]
已修复

**Comment by bbaduser** [comment]
> 已修复

![image](https://user-images.githubusercontent.com/120174736/218456623-e57bf7e4-5fdb-471e-bde6-d0507c250c41.png)

description 在新版中也搜不到

**Comment by lvzero535** [comment]
![image](https://github.com/antvis/G6/assets/26265241/74fd9cb4-dad7-4661-9b1d-b73ca8ea46c1)

没有显示graph.setAutoPaint方法，那个显示只是其中一个描述

![image](https://github.com/antvis/G6/assets/26265241/2573db23-3892-4f1d-8c11-824029a9035d)

没有显示graph.paint方法
