### ISSUE TITLE
边的labelCfg,position只支持'start'，'middle'，'end'

### ISSUE THREAD

**Issue by songxiaoyu321** [antvis/G6#4273]
### 问题描述

项目需求需要在边的某一段位置随机配置，比如0.2-0.8的范围内，请问如何配置呢

### 重现链接

无

### 重现步骤

同问题描述

### 预期行为

同问题描述

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
refX refY 可以调整偏移量

**Comment by songxiaoyu321** [comment]
> 
设置偏移量，比如100
![WechatIMG4](https://user-images.githubusercontent.com/51144045/218622567-5cbe69c5-e53d-4265-ae65-29c21af72efe.jpeg)，
当拖动节点线变短，标签会出去越来越多
![WechatIMG5](https://user-images.githubusercontent.com/51144045/218622649-c6c1d21b-7aa7-4f7d-8cc9-9257c4be19d5.jpeg)

**Comment by Yanyan-Wang** [comment]
目前只支持这样配置，准备在正在开发的 5.x 版本中支持配置 0-1 作为路径上的百分比位置放置文本。

**Comment by Aarebecca** [comment]
你好，G6 5.0 现已支持，你可通过配置 labelPlacement 为 0-1 的数值来设置位置
