### ISSUE TITLE
调用graph.hideItem()隐藏节点之后在画布上还会占据位置

### ISSUE THREAD

**Issue by zcjpass** [antvis/G6#4275]
### 问题描述

调用graph.hideItem()隐藏节点之后在画布上还会占据位置
<img width="520" alt="企业微信截图_c5ddcc18-274e-4044-ba66-384c665200d1" src="https://user-images.githubusercontent.com/40134043/218399835-548981f0-ffdf-46a3-a6ee-2c5495aafe84.png">

隐藏节点之后还会在画布上占据位置，导致未隐藏的节点的绕来绕去

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
隐藏后调用 graph.layout() 重新布局

**Comment by zcjpass** [comment]
> 

调用了layout 后还是会

**Comment by Yanyan-Wang** [comment]
给个最小复现的 demo？
