### ISSUE TITLE
请问 description 支持动态显示吗

### ISSUE THREAD

**Issue by bbaduser** [antvis/G6#4276]
### 问题描述

请问在使用 graph.node(nodeFn) 配置 > 数据中动态配置 > 实例化图时全局配置这三种方式中，是否支持读取node中的数据动态显示，顺便想请问全局配置这种方式中是否能够拿到node节点？

### 重现链接

https://antv-g6.gitee.io/zh/docs/manual/middle/elements/nodes/built-in/modelRect#%E6%8F%8F%E8%BF%B0%E6%96%87%E6%9C%AC%E9%85%8D%E7%BD%AE--descriptioncfg

### 预期行为

直接通过node节点进行配置，如下图所示的layoutcfg那样
<img width="582" alt="image" src="https://user-images.githubusercontent.com/120174736/218410913-5b8ececa-d038-4b34-9a5a-e37b8d0972e8.png">

**Comment by Yanyan-Wang** [comment]
nodeFn 的参数就是一个节点的数据

**Comment by bbaduser** [comment]
嗯 不过感觉更希望能在全局配置时拿到节点

**Comment by Yanyan-Wang** [comment]
> 嗯 不过感觉更希望能在全局配置时拿到节点

目前不支持，准备在正在开发的 5.0 版本中支持

**Comment by bbaduser** [comment]
> > 嗯 不过感觉更希望能在全局配置时拿到节点
> 
> 目前不支持，准备在正在开发的 5.0 版本中支持

期待期待

**Comment by Aarebecca** [comment]
G6 5.0 中可通过 `graph.getNodeData` 获取全部节点数据
