### ISSUE TITLE
G6中ToolBar插件 event.pathwen

### ISSUE THREAD

**Issue by songkangle08** [antvis/G6#4277]
### 问题描述

G6版本：3.8.1
2023年，谷歌浏览器109版本把event上的path属性删除，改成event.composedPath()来代替，导致代码运行报错

### 重现链接

无连接

### 重现步骤

event.path问题

### 预期行为

event.path  改成 (event.path || (event.composedPath && event.composedPath()) )

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
新版 G6 里面应该没有这个了，升级一下，最新 4.8.6

升级指南：https://github.com/antvis/G6/issues/2525

**Comment by songkangle08** [comment]
好的
