### ISSUE TITLE
ts问题：监听nodeselectchange时，ts报错

### ISSUE THREAD

**Issue by bbaduser** [antvis/G6#4278]
### 问题描述

背景：使用nodeselectchange监听单选多选tree中的各个节点，拿到选中节点的值
问题：无法取到nodes
<img width="515" alt="image" src="https://user-images.githubusercontent.com/120174736/218636248-5dc2d742-96f3-495b-9694-7f2bb7fc3abb.png">
<img width="527" alt="image" src="https://user-images.githubusercontent.com/120174736/218637019-26b9f5e6-5ffa-4e7b-bf69-7a5bef73016c.png">

期望：是否有办法解决，有没有优雅写法

**Comment by bbaduser** [comment]
如果选择分开监听的方式，怎么监听多选的呢
<img width="697" alt="image" src="https://user-images.githubusercontent.com/120174736/218639085-9e7354db-6aad-49a7-bea0-a7d02e44b297.png">

**Comment by Yanyan-Wang** [comment]
先 ts-ignore 一下，后面我们修复下类型问题
