### ISSUE TITLE
移动端下node:click 无法触发

### ISSUE THREAD

**Issue by Yuners** [antvis/G6#4279]
### 问题描述

移动端如果配置了drag-canvas、zoom-canvas、drag-node等任意交互模式后node:click都无法触发

### 重现链接

https://g6.antv.antgroup.com/zh/examples/tree/customItemTree/#customEdgeTree

### 重现步骤

1、进入页面切换到移动端
2、在node:click添加console.log(111)
3、点击后控制台无打印信息
4、将modes配置全部删除后可以点击

### 预期行为

移动端存在modes配置也可以进行node:click

### 平台

移动端

**Comment by morningYxx** [comment]
请问一下如何解决的？目前项目也遇到同样问题

**Comment by HuColin** [comment]
同样遇到这个问题
