### ISSUE TITLE
自定义注册节点，只有定义节点名字为 icon-node  改成其他名字注册元素方法不执行

### ISSUE THREAD

**Issue by YSLg** [antvis/G6#4280]
### 问题描述

自定义注册节点，只有定义节点名字为 icon-node  改成其他名字注册元素方法不执行

### 重现链接

https://gitee.com/antv-g6_1/antv-g6-demo1

### 重现步骤

命名为： icon-node
![image](https://user-images.githubusercontent.com/40992116/218684221-8f4c5f7d-99d4-4373-adc3-64dc0d56d0f7.png)
![image](https://user-images.githubusercontent.com/40992116/218684309-17951e12-2682-458f-b1a5-02ffc038396a.png)
![image](https://user-images.githubusercontent.com/40992116/218684350-078f48e6-ca78-4c2e-9581-1a52e501c737.png)
命名为: chain-node
![image](https://user-images.githubusercontent.com/40992116/218684729-645a15da-c331-4b4c-987c-9dcd4c44f447.png)
![image](https://user-images.githubusercontent.com/40992116/218684790-770c0156-8b07-46dd-9aee-b9c7435dfd06.png)
![image](https://user-images.githubusercontent.com/40992116/218684819-2adb3f95-b162-4e54-b522-ecb2329eeda0.png)
代码在上述仓库里可复现

### 预期行为

希望可以正常命名，因为我需要一个页面展示多个图，相同的命名会导致样式冲突

### 平台

- 操作系统: macOS
- 网页浏览器: Google Chrome
- G6 版本: 4.8.2

**Comment by zhoustudent** [comment]
如果需要使用多个不同类型的自定义节点是，可在data数据中增加type属性，来进行区分，如：data的内容
`[{id: 1, name: 1, type: 'icon-node'}, {id: 2, name: 2, type: 'chain-node'}]` <br/>(树状图的数据一样，增加type属性)

**Comment by YSLg** [comment]
> 

我知道了两个图我用的是一个data, 当一个图渲染之后会把他的节点属性添加到data上，导致两个图的样式污染了
