### ISSUE TITLE
固定zoom的前提下使用scroll-canvas，如何禁止canvas画布无限滚动

### ISSUE THREAD

**Issue by zhoustudent** [antvis/G6#4283]
### 问题描述

在固定zoom后，且只允许画布y方向使用scroll-canvas，会发现在上下滑动时，可以无限滚动
寻求：
1. 是否可以当上下滑动时，展示出节点的第一个元素或最后一个元素就停止滚动
2. 滚动式无法看到滚动条，无法进行页面的其他操作（如页面的上下滚动）

### 重现链接

https://codesandbox.io/s/elated-babycat-zbyulh?file=/src/App.js

### 重现步骤

任意一个图表，使用modes为scroll-canvas
`{
              type: 'scroll-canvas',
              direction: 'y',
            },`

### 预期行为

当滑动时，如果视图框内没有节点就让它停止滑动

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.8.5 ]

**Comment by yonghengdeanjing** [comment]
没太看懂scalableRange应该怎么设置值，可以给个示例么

**Comment by AprilTong** [comment]
> https://g6.antv.antgroup.com/manual/middle/states/default-behavior#scroll-canvas
> 
> scalableRange

设置了好像没有用的样子，-1、0、1 三个值都试了，似乎没啥变化，版本4.8.10。<img width="531" alt="image" src="https://github.com/antvis/G6/assets/24354441/03ef69ad-340e-44f6-9eda-39c02dad93c7">

**Comment by Aarebecca** [comment]
整数值目前有点小问题，可以尝试传入一个极小值，例如 `-0.999` ` -0.001` `0.001` `0.999`

**Comment by JohnRyanTsai** [comment]
有同样的问题，请问下解决了吗？ 设置scalableRange 不生效

**Comment by strawberrydot** [comment]
同样遇到了画布无限滚动，设置scalableRange 不生效，这个问题到底怎么解决呀？求求求求求求

**Comment by strawberrydot** [comment]
> 整数值目前有点小问题，可以尝试传入一个极小值，例如 `-0.999` ` -0.001` `0.001` `0.999`

4.X版本，设置了还是不生效欸。。。。
