### ISSUE TITLE
updateLayout方法切换布局导致图位置跑偏

### ISSUE THREAD

**Issue by xiohao** [antvis/G6#4284]
### Describe the bug

![image](https://user-images.githubusercontent.com/125447477/218983402-9314c555-fe7d-471c-b742-f4e2333b4639.png)
![image](https://user-images.githubusercontent.com/125447477/218983558-8eca67e2-3b69-483b-a768-24d3421fb4fb.png)
![image](https://user-images.githubusercontent.com/125447477/218983775-2f9898a6-7a2b-4693-a55e-accd404335d2.png)
![image](https://user-images.githubusercontent.com/125447477/218983859-f3bb987a-06ab-43e9-8411-ef11623f2ec6.png)
点击切换后图跑偏了

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

111

### Expected behavior

期望图更新在画布中间位置，使用this.graph.set('fitView', true)也无效

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

请问知道有什么解决办法吗

**Comment by Yanyan-Wang** [comment]
给个在线复现的 demo 看看？

**Comment by Shalomw** [comment]
emm我也有类似问题，但不是跑偏而是会转动
