### ISSUE TITLE
collapse-expand折叠或者展开在单击双击时都执行，如何屏蔽双击折叠展开呢？？？

### ISSUE THREAD

**Issue by lihao0923** [antvis/G6#4287]
### 问题描述

我用了trigger字段了，设置为‘click’，但是双击依然会触发折叠和展开，我无法屏蔽双击折叠展开的逻辑。请问大家有什么方法没？？？详情看图片！！

### 重现链接

https://antv-g6.gitee.io/zh

### 重现步骤

紧凑树单双击

### 预期行为

紧凑树单双击

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![QQ20230215-0](https://user-images.githubusercontent.com/83899538/219076459-9d1d5d38-1495-477f-bd13-d1ef6d5f0d03.png)
![QQ20230215-1222](https://user-images.githubusercontent.com/83899538/219076528-862a6c59-0f9e-4921-9535-b801685ed027.png)

![QQ20230215-042424](https://user-images.githubusercontent.com/83899538/219079222-6bc8503f-5f98-46b2-a97c-a29b4543876a.png)

### 补充说明（可选）

网上的说法我都用过了，但是只能阻止单双击里面的逻辑，无法阻止双击展开或者折叠

**Comment by Yanyan-Wang** [comment]
新发布了 4.8.7，drag-node 配置 click 的时候，将通过定时器不响应 dblclick

**Comment by lihao0923** [comment]
问题已解决，通过setTimeout配合相应的设置，实现了单击收起折叠，双击触发收起折叠操作。感谢！
