### ISSUE TITLE
拖动元素到画布区域之外drop后，再次回到画布区域拖拽出现各种事件错乱问题

### ISSUE THREAD

**Issue by wangsfine** [antvis/G6#4290]
### 问题描述

拖拽画布中节点到画布区域之外至出现文本框选之后drop，再次回到画布区域拖拽其他节点，就会出现拖拽事件错乱，如：拖拽drop 松开鼠标之后节点才会移动

### 重现链接

https://antv-g6.gitee.io/zh/examples/net/radialLayout#preventOverlapRadial

### 重现步骤

1，选中一个节点向左拖拽至画布区域之外，出现下图所示的文本选中样式
![image](https://user-images.githubusercontent.com/14818720/219254772-a9a6eb41-f132-44ea-8a77-df798e356ff1.png)
2，返回画布区域拖拽其他节点

### 预期行为

期望拖拽事件正常进行

### 平台

- 操作系统: Windows
- 网页浏览器: Google Chrome
- G6 版本: 4.3.2

**Comment by Yanyan-Wang** [comment]
升级到最新版本试试？另外我们现在无法更新 gitee 域名的官网内容，这上面内容已经比较老旧，建议访问这个域名，也非常快：https://g6.antv.antgroup.com/

**Comment by TalentJY** [comment]
我最新版本 也是拖到外面 之后 有些奇怪的问题

**Comment by Yanyan-Wang** [comment]
> 我最新版本 也是拖到外面 之后 有些奇怪的问题

新发了一个 4.8.7 版本，drag-node 监听了 window 的 mouseup 事件结束拖拽，可以试试看
