### ISSUE TITLE
Edge position not update when trigger changeData method to update nodes & edges, only nodes position updated

### ISSUE THREAD

**Issue by fangbinghz** [antvis/G6#4291]
### Describe the bug

![image](https://user-images.githubusercontent.com/113875802/219269588-334b5c73-c820-486b-a599-8e57a10632f7.png)

### Your Example Website or App

skyharbor.certik.com

### Steps to Reproduce the Bug or Issue

1. click risk inspector  menu 
2. select case manage
3. select one address 
4. enter flow analyzer
5. click collapse icon to find this issue

### Expected behavior

edge position not update when nodes position update

### Platform

- Browser

**Comment by Yanyan-Wang** [comment]
Please provide a smallest online reproducing demo
