### ISSUE TITLE
存在combo的自定义布局，使用changeData增加数据之后，再次执行布局不正确

### ISSUE THREAD

**Issue by brosegu** [antvis/G6#4292]
### 问题描述

背景：
  g1使用darge布局，对等g2使用g1布局之后的坐标记录，进行自定义布局设置combo位置。
问题：
  在changeData({nodes,edges,combos})增加节点之后，g1得到预期，再次记录位置，执行g2的自定义布局**（发现所有node全部进入到了hiddenNodes中）**，结果坐标获取正确，但是combo没有根据node进行位置更新！！！为什么？
![image](https://user-images.githubusercontent.com/12181144/219282388-b7e58076-e179-48e3-8833-5f7496a71c78.png)

  

### 重现链接

xxx

### 重现步骤

定位node之后como位置没更新，

### 预期行为

期望changeData之后执行的布局，能够正常

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
提供个在线复现的 demo 看看

**Comment by brosegu** [comment]
> 提供个在线复现的 demo 看看

demo外网实现有些复杂，我们代码都在内网，
其实本质需求就是：
官网示例中的dagre布局中的每个元素，在我这里都是combo，而不是node，所以应用dagre无效，不对combo起作用。
不知道有没有好的办法，让dagre对combo也起作用？

我自己的笨办法：先用node应用dagre布局，然后记录位置，在使用combo复现坐标。可以实现，但是性能就下降了一倍

**Comment by Yanyan-Wang** [comment]
dagre 的 sortByCombo 无法满足吗？或者就拿 dagre 当作一个算法来使用，计算完成之后给到 combo ，和你这里思路类似，但没必要真正给 G6 节点去渲染临时的 dagre。可以实现一个最简单的复现 demo 看下。

**Comment by brosegu** [comment]
> dagre 的 sortByCombo 无法满足吗？或者就拿 dagre 当作一个算法来使用，计算完成之后给到 combo ，和你这里思路类似，但没必要真正给 G6 节点去渲染临时的 dagre。可以实现一个最简单的复现 demo 看下。

先感谢您能回复，我想知道这个“当作一个算法来用”是怎么个操作，有这个api吗？我当初想过那darge源码来改，但是感觉难度有些大

**Comment by brosegu** [comment]
> dagre 的 sortByCombo 无法满足吗？或者就拿 dagre 当作一个算法来使用，计算完成之后给到 combo ，和你这里思路类似，但没必要真正给 G6 节点去渲染临时的 dagre。可以实现一个最简单的复现 demo 看下。
知道怎么使用了。谢谢，G6.Layout.dagre可以拿到布局结果，不需要渲染了。谢谢！
不过有个问题，新版本4.8.5中如果单独在引入@antv/layout 会出问题，应该这个版本不能单独使用把

**Comment by brosegu** [comment]
> dagre 的 sortByCombo 无法满足吗？或者就拿 dagre 当作一个算法来使用，计算完成之后给到 combo ，和你这里思路类似，但没必要真正给 G6 节点去渲染临时的 dagre。可以实现一个最简单的复现 demo 看下。

知道怎么使用了。谢谢点拨~ G6.Layout.dagre可以拿到布局结果，不需要渲染了。谢谢！
不过有个问题，新版本4.8.5中如果单独在引入@antv/layout 会出问题，应该这个版本不能单独使用把
