### ISSUE TITLE
应该只需要调用 `graph.updateItem('comboA', { x, y })` 即可，不需要先更新节点再更新 combo。combo 和子节点谁最后更新，另一方就会跟随。另外，因为元素和 graph 以及其他元素是解耦的，所以图的所有操作尽量都使用 graph 的 API，而不是单个元素，这样 graph 可以统筹管理。

### ISSUE THREAD

**Issue by wangxiang666** [antvis/G6#4293]
应该只需要调用 `graph.updateItem('comboA', { x, y })` 即可，不需要先更新节点再更新 combo。combo 和子节点谁最后更新，另一方就会跟随。另外，因为元素和 graph 以及其他元素是解耦的，所以图的所有操作尽量都使用 graph 的 API，而不是单个元素，这样 graph 可以统筹管理。

_Originally posted by @Yanyan-Wang in https://github.com/antvis/G6/issues/4082#issuecomment-1348118188_
        

“combo 和子节点谁最后更新，另一方就会跟随”这个机制有办法绕过吗
我为combo和其子节点都设置了固定位置x、y和固定大小size，（数据均是从X6编辑好，拿到G6做渲染），但combo和nodes其中一个总会有一个有偏差，节点位置渲染正确combo就会错位（因为自动更新），反之节点会错位，使用comboCombined布局，内外布局均为自定义布局（布局中使节点和combo位置大小信息都采用我预置数据），结果依旧

**Comment by Yanyan-Wang** [comment]
提供一个在线复现 demo 看看
