### ISSUE TITLE
scroll-canvas和zoom-canvas同时开启时，用mac的触控板滚动时同时会缩放，怎么阻止滚动的时候缩放

### ISSUE THREAD

**Issue by tuhongwei** [antvis/G6#4294]
### 问题描述

scroll-canvas和zoom-canvas同时开启时，mac触控板滚动不应缩放

### 重现链接

https://cvgp3s.csb.app/

### 重现步骤

1.进入页面
2.mac 触控板滚动
3.滚动和缩放都有

### 预期行为

我期望看到滚动，但我看到了缩放

### 平台

- 操作系统: [macOS,]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
这个和用户使用习惯有关，交互组合之间的冲突需要应用的开发者来调整。你可以给 zoom-canvas 配置 shouldBegin，根据当前情况返回 false 或者 true，false 就不会响应这个交互了
