### ISSUE TITLE
边的渐变色问题

### ISSUE THREAD

**Issue by songxiaoyu321** [antvis/G6#4295]
### 问题描述

节点A蓝色，节点B黄色，线的source:A,target:B;
边的渐变 stroke: 'l(0) 0:#1C77FF 1:#DB8F17'，
当蓝节点在左，黄节点在右，边是从蓝到黄的渐变
但是当我拖动节点A，黄节点在左，蓝节点在右，边就变成了从黄到蓝，
我希望拖动节点边的渐变不要变化，始终是source颜色到target颜色，请问如何配置
![Uploading WechatIMG3.jpeg…]()
![Uploading WechatIMG4.jpeg…]()

### 重现链接

无

### 重现步骤

同问题描述

### 预期行为

同问题描述

### 平台

同问题描述

**Comment by Yanyan-Wang** [comment]
可以自定义边，继承内置，复写 afterUpdate，根据起点终点的左右关系，决定渐变色方向
```
G6.registerEdge('custom-edge', {
  afterUpdate: (cfg, item) => {
    const { startPoint = {}, endPoint = {} } = cfg;
    const stroke = startPoint.x < endPoint.x ? 'l(0) 0:#ffffff 0.5:#7ec2f3 1:#1890ff' : 'l(0) 0:#1890ff 0.5:#7ec2f3 1:#ffffff';
    const keyShape = item.getKeyShape();
    keyShape.attr('stroke', stroke);
  }
}, 'line');
```
