### ISSUE TITLE
使用节点动画animate时，无法停止

### ISSUE THREAD

**Issue by TalentJY** [antvis/G6#4296]
### 问题描述

const group = item.get('group');
const image = group.getFirst()
    image.animate(
        (ratio) => {
            return {
                xxx
            }
        },
        {
            repeat: true, // 动画重复
            duration: 2000,
            easing: 'easeLinear'
        }
    )

然后我使用graph.isAnimating()判断是否存在动画时，为false，
group.stopAnimate()   or  graph.stopAnimate()也无法清除动画

### 重现链接

暂无

### 重现步骤

无

### 预期行为

期望能使用stopAnimate 停止动画，但是没有停止，并且isAnimating 结果也为false

### 平台

- 操作系统: Linux
- 网页浏览器: [Google Chrome,]
- G6 版本: [4.8.5 ... ]

**Comment by Yanyan-Wang** [comment]
image.stopAnimate()

在什么图形上加的动画，需要在这个图形上操作停止
