### ISSUE TITLE
changeData更新时会使动画失效

### ISSUE THREAD

**Issue by 13866368297** [antvis/G6#4297]
### 问题描述

官方示例：使用changeData更新时会使动画失效，而updateLayout更新方式动画确实正常的

### 重现链接

https://codesandbox.io/s/strange-julien-x4q1ds?file=/index.html

### 重现步骤

1.进入页面2s后节点更新，没有动画

### 预期行为

changeData更新时动画正常

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

changeData更新效果

https://user-images.githubusercontent.com/26242869/219608605-375ed5a1-f4c9-4ba9-903d-a85b1bd0cd82.mp4

updateLayout更新效果

https://user-images.githubusercontent.com/26242869/219608700-057a2a8f-a8f3-4300-a8db-c90e6b5ff980.mp4

**Comment by Yanyan-Wang** [comment]
目前不支持 changeData 的动画，欢迎社区共建
