### ISSUE TITLE
不同节点个数下宽高显示问题

### ISSUE THREAD

**Issue by bbaduser** [antvis/G6#4298]
### 问题描述

当节点为一时，节点非常大
![image](https://user-images.githubusercontent.com/120174736/219608158-a4b28136-480f-4222-88ae-cca64595a32a.png)
当节点比较多的时候，显示就比较正常
![image](https://user-images.githubusercontent.com/120174736/219608646-d71f675d-3e8f-4f8a-a1c2-76218bfabade.png)

猜测是开了fitview的原因吗？
如果希望一个节点时也维持多节点时比较小的状态，请问应该如何处理呢

**Comment by Yanyan-Wang** [comment]
那就 fitView: false，自己根据数据量的多少再调用 graph.fitView
