### ISSUE TITLE
如何在两个节点之间绘制多条不重合的边？

### ISSUE THREAD

**Issue by Cmaxd** [antvis/g6#430]
1.x版本的G6在遇到两个node之间有多条边的情况，会导致边重合在一起，现在有这样的需求，请问有没有办法画出下图这样的效果？（前提是自动生成布局，无需手动添加控制点）
![image](https://user-images.githubusercontent.com/26359629/44307094-f0012f00-a3ce-11e8-8cf9-f52a4331197a.png)

2.x版本中有二阶贝塞尔曲线的插件，对于两个node之间有朝向不同的两条线时，会画出下面这样的图，但是如果两条线朝向一样的话也会重合在一起。
![image](https://user-images.githubusercontent.com/26359629/44307189-841fc600-a3d0-11e8-837e-eb6247c39263.png)

**Comment by TomHuangCN** [comment]
暂时没有对画同源同向边比较好的解发，建议从设计层面避免。

**Comment by chinachuner** [comment]
我也遇到了这种问题，现在新版本支持多条边了吗 @TomHuangCN
