### ISSUE TITLE
需求需要自定义ToolBar，深度定制目前new G6.ToolBar  只能在getContent设置样式吗

### ISSUE THREAD

**Issue by YSLg** [antvis/G6#4300]
### 问题描述

![image](https://user-images.githubusercontent.com/40992116/220086107-db6ab841-7dcb-44b0-840e-79f8680320d7.png)
需求需要功能之间是有关系的，比如点击A, A可置成选中样式吗

### 重现链接

暂未实现

### 重现步骤

暂未实现

### 预期行为

暂未实现

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
可以完全自己写一个组件不用 G6 提供的，只是每个 按钮的监听里面调用 G6 的 API 做相应的事情就好

**Comment by yonglijia** [comment]
可以使用react定义组件吗？必须得使用原生dom去写吗？
