### ISSUE TITLE
Angular14安装G6报TS类型错误

### ISSUE THREAD

**Issue by Eve-Sama** [antvis/G6#4301]
### 问题描述

新建的Angular项目, 安装G6后跑不起来, 提示node_modules中的G6类型错误

### 重现链接

https://github.com/Eve-Sama/x6-angular-shape

### 重现步骤

clone https://github.com/Eve-Sama/x6-angular-shape
yarn
npm start

### 预期行为

正常执行

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.8.6 ]

### 屏幕截图或视频（可选）

<img width="1501" alt="图片" src="https://user-images.githubusercontent.com/30228406/220125031-96dc7c4e-97b3-480c-b721-53d450eb6323.png">
<img width="1102" alt="图片" src="https://user-images.githubusercontent.com/30228406/220125080-a18648e4-fe39-465b-b8cb-c5b46ec85497.png">

### 补充说明（可选）

虽然项目名字是X6, 但是这个项目里面有X6也有G6. 所以不用在意项目名字.

package.json
```json
{
  "name": "x6-angular-shape",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test",
    "deploy": "ng deploy --base-href=\"./\" --no-silent"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^14.2.0",
    "@angular/common": "^14.2.0",
    "@angular/compiler": "^14.2.0",
    "@angular/core": "^14.2.0",
    "@angular/forms": "^14.2.0",
    "@angular/platform-browser": "^14.2.0",
    "@angular/platform-browser-dynamic": "^14.2.0",
    "@angular/router": "^14.2.0",
    "@antv/g6": "^4.8.6",
    "@antv/x6": "^2.4.0",
    "lodash-es": "^4.17.21",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^14.2.10",
    "@angular/cli": "~14.2.10",
    "@angular/compiler-cli": "^14.2.0",
    "@types/jasmine": "~4.0.0",
    "@types/lodash-es": "^4.17.6",
    "angular-cli-ghpages": "^1.0.5",
    "typescript": "~4.7.2"
  }
}

```

**Comment by Yanyan-Wang** [comment]
试一下 v4.8.8

**Comment by Eve-Sama** [comment]
没问题了, 谢谢
