### ISSUE TITLE
自环节点被拖拽后 自环边定位异常

### ISSUE THREAD

**Issue by chi-gao** [antvis/G6#4303]
### Describe the bug

源自官网demo，修改某条边为自环边。 当拖拽 包含自环边的节点后，自环边定位异常，跑到了很远的地方。
![image](https://user-images.githubusercontent.com/24784430/220242668-2944ec13-bb1a-4608-b9d3-de0eba1ea32f.png)

### Your Example Website or App

https://dagre-1.stackblitz.io/

### Steps to Reproduce the Bug or Issue

1. after graph render, drag the node with self loop edge;
2. you will see the position of self loop edge is strange.

### Expected behavior

follow the dragging node

### Platform

- OS: macOS
- Browser: Chrome
- Version: lastest

**Comment by Yanyan-Wang** [comment]
v4.8.7 已修复
