### ISSUE TITLE
treegraph树形图折叠展开或者拖拽的时候节点label会留下类似重影效果的痕迹，如何优化去除这个现象呢？

### ISSUE THREAD

**Issue by lihao0923** [antvis/G6#4309]
### 问题描述

treegraph树形图折叠展开或者拖拽的时候节点label会留下类似重影效果的痕迹，如何优化去除这个现象呢？

### 重现链接

无

### 重现步骤

treegraph树形图折叠展开或者拖拽

### 预期行为

希望不要留下重影的效果

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）
![220864952-365c164a-df73-4a32-9f2d-0ecaa2ce10c6](https://user-images.githubusercontent.com/83899538/220925082-36bbe42a-5270-4c64-8f07-d823dae0b04a.png)

_No response_

### 补充说明（可选）

我希望在折叠展开，或者是拖拽treegraph树形图的时候不会留下重影的痕迹！但是现在偶尔会出现这个现象。

**Comment by ttthing111** [comment]
我之前也遇到了这个问题，然后再过往的一个issue找到了解决办法，好像是 关闭 localrefresh
记得那个issue里提到好像提到会在5.x的版本里解决

**Comment by bbaduser** [comment]
graph.get('canvas').set('localRefresh', false);
