### ISSUE TITLE
force2防止节点重叠不生效

### ISSUE THREAD

**Issue by huangxians** [antvis/G6#4313]
### 问题描述

使用官网的在线示例http://g6.antv.antgroup.com/zh/examples/net/forceDirected#forceDirectedPreventOverlap
改变布局方式为force2,节点大小增加100,即可浮现
![image](https://user-images.githubusercontent.com/52060357/221144523-5faa5002-a5e5-40bb-a4b9-8facbe036e91.png)
请问怎么解决,边长及节点引力都设置过了,还是会重叠,只有使用force布局才不会重叠,但是force的其他配置没有force2好用,希望大佬给解决一下

### 重现链接

http://g6.antv.antgroup.com/zh/examples/net/forceDirected#forceDirectedPreventOverlap

### 重现步骤

改变布局方式为force2
节点大小增加100

### 预期行为

节点不重叠

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
coulombDisScale: 0.001 可以让图更松散些
