### ISSUE TITLE
是否支持单击进行多选

### ISSUE THREAD

**Issue by bbaduser** [antvis/G6#4314]
### 问题描述

期望：单击就能进行多选
<img width="773" alt="image" src="https://user-images.githubusercontent.com/120174736/221151040-6f6247c7-cf03-403d-882d-0594831a7bf4.png">
请问有支持方法吗

**Comment by Yanyan-Wang** [comment]
内置交互不支持，可以自己监听 graph.on('node:click', e => {}) 设置状态。或者我们也欢迎社区 PR，给 click-select 增加这个 feature
