### ISSUE TITLE
拖动节点时，点的快会导致鼠标并不在节点上

### ISSUE THREAD

**Issue by TalentJY** [antvis/G6#4315]
### 问题描述

https://user-images.githubusercontent.com/82206115/221350775-c80805a3-3a1c-4e1f-969e-cbabd09f6766.mp4

### 重现链接

暂无

### 重现步骤

暂无

### 预期行为

快速点击 节点拖动时候，鼠标没有指在节点上，官方例子里也是这样，有一种不灵敏的感觉，有什么优化方案吗吗

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
为了更好的性能，drag-node 增加了 debounce 限流。欢迎社区 pr 来优化
