### ISSUE TITLE
实现双击修改label的方案有哪些

### ISSUE THREAD

**Issue by TalentJY** [antvis/G6#4317]
### 问题描述

1.想要实现双击节点，就能在label对应位置修改节点名称。很多类似的库是支持的，但G6似乎不支持？
目前我知道的实现方案是写一个input隐藏，然后双击的时候显示，再覆盖掉节点的label所在的位置，修改后再应用到节点的label上

但总感觉这样的实现方式并不是非常的优雅？
有其他更好的实现方式吗？

2.同时 ，啥时候能支持 label中只修改部分字体的颜色大小啊？目前看到的修改label的颜色大小，都是对整个label生效。

### 重现链接

暂无

### 重现步骤

暂无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
1. 重编辑需求可以用 AntV X6，一般这种图编辑的库是基于 SVG。G6 这样 canvas 的库，要实现这种功能，也就是用 input 的方式，挂载方式参考：https://g6.antv.antgroup.com/manual/advanced/coordinate-system

2. canvas 的文字不支持这种需求，可以自定义节点增加多个 text 图形

**Comment by zzzhanga** [comment]
> 1. 重编辑需求可以用 AntV X6，一般这种图编辑的库是基于 SVG。G6 这样 canvas 的库，要实现这种功能，也就是用 input 的方式，挂载方式参考：https://g6.antv.antgroup.com/manual/advanced/coordinate-system
> 2. canvas 的文字不支持这种需求，可以自定义节点增加多个 text 图形

x6也没看到双击直接修改节点label的方式啊
