### ISSUE TITLE
新版本的node.toBack不生效

### ISSUE THREAD

**Issue by xicunyang** [antvis/G6#4318]
### Describe the bug

![image](https://user-images.githubusercontent.com/40530112/221511680-e2053cc3-ffbd-42ba-90b9-713742cdf9e9.png)

我需要这个三角形（是在edge上的哈，我自定义了一个连线，连线中间有一个图片）的图片的层级高于node节点，就像上图一样。

但是我的代码运行在4.8.7版本的时候，是无效的，
当我将版本降到4.6.12之后，就可以了，

复现的demo在这个地址里，可以切换一下g6的版本，就可以复现这个问题。
我猜测是版本升级之后有新的使用姿势？但是我没找到对应的说明。

测试地址在这里：https://codesandbox.io/s/twilight-snowflake-5kk4s0?file=/index.js

### Your Example Website or App

https://codesandbox.io/s/twilight-snowflake-5kk4s0?file=/index.js

### Steps to Reproduce the Bug or Issue

1. 先打开页面，看到三角形的图片
2. 切换g6的版本，上面描述了两个版本，在这两个版本之间切换
3. 就可以看到图片的层级出现不一致了

### Expected behavior

我希望可以让三角形图片层级高于node节点

### Platform

- OS: [macOS]
- Browser: [Chrome]
- Version: [110.0.5481.100]

**Comment by Yanyan-Wang** [comment]
把 toFront 逻辑放在 afterlayout 监听里面，因为布局后会调整节点的位置、combo 的位置以及层级

graph.on('afterlayout', e => { ... })

**Comment by xicunyang** [comment]
> 把 toFront 逻辑放在 afterlayout 监听里面，因为布局后会调整节点的位置、combo 的位置以及层级
> 
> graph.on('afterlayout', e => { ... })

不好意思，我刚才试了一下，还是不可以的，没有效果。你可以使用上面的 demo 试一下哈。

**Comment by Yanyan-Wang** [comment]
我在你 demo 里试的是可以的，这个监听绑在 graph.render 之前

**Comment by mangwu** [comment]
我也遇到了类似的问题，我的解决方法是渲染完成后调用一次graph.refresh，然后监听aftergraphrefresh事件，进行元素的toFront和toBack操作。如果还是不行，就用setTimeout，强制在图像渲染完毕之后异步进行元素的toFront和toBack操作，但是setTimeout的时间不好确认。
