### ISSUE TITLE
火狐zoom-canvas兼容

### ISSUE THREAD

**Issue by mioxs** [antvis/G6#4319]
### 问题描述

zoom-canvas火狐无法滚动，希望可以提供解决方案

### 重现链接

https://g6.antv.antgroup.com/zh/examples/net/gridLayout/#basicGrid

### 重现步骤

火狐zoom-canvas无法使用

### 预期行为

希望可以缩放

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Firefox]
- G6 版本: [4.8.5]

**Comment by Yanyan-Wang** [comment]
我这里没有复现，是不是滚动之前鼠标没聚焦到画布上？

**Comment by mioxs** [comment]
火狐版本52.3
