### ISSUE TITLE
节点起始点更改

### ISSUE THREAD

**Issue by ealldy** [antvis/G6#4323]
### 问题描述

我有两个高度不同的矩形节点，连接线设置的锚点在两个节点的左右居中位置，但两个节点高度不同，导致连接线有曲折的效果出现。请问如何对节点起始点进行位置偏移？或者整个group如何进行位置的移动，看了文档没看到group可以进行位置更改。如果对每一个shape都进行位移貌似能实现效果，但这样太麻烦了，我的group里有非常多个shape，每一个都要改位置，以及各种交互。而且我看group的描述，不是说对其进行操作就能影响其下的元素么，怎么不能改。

### 重现链接

可以看图片

### 重现步骤

可以看图片

### 预期行为

![af48dda2fd4c747478ebc437fafa423a](https://user-images.githubusercontent.com/41937421/222055674-b2c0e0af-8b7d-4690-948f-e0407bbe8a1d.png)

### 平台

- 操作系统:  Windows
- 网页浏览器: Google Chrome
- G6 版本: 4.8.6

**Comment by ealldy** [comment]
#3559 需求跟这个issues一样，需要变动节点的位置使其居中对齐，具体不知道如何操作

**Comment by ealldy** [comment]
@yuanchuan 大佬帮忙看看

**Comment by Yanyan-Wang** [comment]
自定义节点自身坐标系原点移动到中心，例如 keyShape 是 rect 的话，rect 图形的 x y 各减去宽高一半 { x: -width / 2, y: -height / 2 }，其他图形也相对移动一下。

**Comment by ealldy** [comment]
只能所有图形都进行移动吗，有没有可以一次性对所有图形移动的方法

**Comment by Yanyan-Wang** [comment]
> 只能所有图形都进行移动吗，有没有可以一次性对所有图形移动的方法

自定义节点的 draw 方法里面改了以后，所有生成的节点都会执行这个方法，不就都改了么
