### ISSUE TITLE
Fruchterman布局 节点重叠

### ISSUE THREAD

**Issue by wuwuxi** [antvis/G6#4326]
### 问题描述

当图布局 使用Fruchterman布局时  大量节点重叠

### 重现链接

(https://codesandbox.io/s/new

### 重现步骤

展开后节点重叠

### 预期行为

期望节点散开

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.8.5]

### 屏幕截图或视频（可选）

![A$1)UQE{OAWJ8@U~2FAQ_BB](https://user-images.githubusercontent.com/27846587/222105070-7b5d3d45-b4b7-4af4-a46f-6ab279068016.png)
![image](https://user-images.githubusercontent.com/27846587/222105317-01129c94-3132-44dc-aa29-2c448e517c0d.png)

### 补充说明（可选）

把重现步骤里面的数据复制到官网的 图表示列 里就能看到效果，里面的坐标是自动生成的

**Comment by chaoranfeng** [comment]
试试把重力调小一点, 能散开一点

**Comment by wuwuxi** [comment]
并不能解决这个问题，只能说是稍微好点， 我想要的是Forec那种散开的效果，并且设置的聚类也没成功

**Comment by Yanyan-Wang** [comment]
尝试这个解法，先试试 beta 版：https://github.com/antvis/G6/issues/4333

**Comment by wuwuxi** [comment]
请问 如果force2布局我自己计算节点位置 有什么好的计算方法推荐吗，或者现场的插件
