### ISSUE TITLE
钉钉技术交流群一直加不进去，怎么办呢

### ISSUE THREAD

**Issue by xiaohouzi007** [antvis/G6#4329]
### 问题描述

钉钉技术交流群一直加不进去，怎么办呢

### 重现链接

钉钉技术交流群一直加不进去，怎么办呢

### 重现步骤

钉钉技术交流群一直加不进去，怎么办呢

### 预期行为

钉钉技术交流群一直加不进去，怎么办呢

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
可以在 github 交流，交流群人满了，里面也没有提供答疑哈
