### ISSUE TITLE
怎么更新tootip

### ISSUE THREAD

**Issue by BusyHe** [antvis/g6#433]
![image](https://user-images.githubusercontent.com/17348825/44347879-97638c00-a4cb-11e8-89fb-250994625741.png)
```
this.tree.update(this.nowEv.item.id, model)
```
用了update节点已经鞥更新

**Comment by BusyHe** [comment]
![image](https://user-images.githubusercontent.com/17348825/44348407-e6f68780-a4cc-11e8-9ed1-2890bc67c9ee.png)
![image](https://user-images.githubusercontent.com/17348825/44348427-f1b11c80-a4cc-11e8-8f4b-df75ff27a211.png)
![image](https://user-images.githubusercontent.com/17348825/44348466-14433580-a4cd-11e8-9c74-c8112148e8ea.png)

**Comment by TomHuangCN** [comment]
写 codepen https://codepen.io/DoriTong/pen/pKbLVw

**Comment by BusyHe** [comment]
@TomHuangCN 
https://codepen.io/BusyHe/pen/JaoPXv
http://7xs9qc.com1.z0.glb.clouddn.com/Jietu20180821-201117-HD.gif
1. 先点击一个node节点获取id
2.input输入内容更新label和data.title
3.tooltip没有更新

**Comment by TomHuangCN** [comment]
已修复
