### ISSUE TITLE
关于大数据量性能优化请教

### ISSUE THREAD

**Issue by chaoranfeng** [antvis/G6#4333]
### 问题描述

大概有三个性能相关问题, 关于交互与布局方面的优化:
**一、交互如何优化?**
      目前在做一个公司员工的关系图, 小到 100+, 大到 1~10 万+数据量, 目前发现了一个很大的性能瓶颈就是->节点/边的遍历;
因为产品的交互比较定制化,所以没有采用 g6 内部提供的Behavior, 例如典型的activate-relations,鼠标移入移出效果, 而是采用了节点监听事件(node:mouseenter / node:mouseleave),来达到鼠标移入移出效果, 我的处理是:  鼠标移入时, 遍历所有 nodes, 然后高亮nodeItem,以及 nodeItem.getNeighbors()..., 然后其他节点全部淡出,  类似的这种操作还有很多, 例如点击选中节点,也是如此,需要遍历整个 nodes;
      请问这种场景应该如何处理, 可以达到性能更优? 因为目前 1000+的时候, 就明显感觉到了有一些掉帧

**二、setItemState / updateItem**
     我目前处理交互是使用setItemState来控制不同的样式变化, 还未尝试使用updateItem, 请问这两种哪一种性能更优,更推荐来做交互操作?

**三、布局性能**
       在这篇文章中: http://g6.antv.antgroup.com/manual/faq/performance-opt 我看您说 force2性能优秀,  fruchterman性能较差, 实际几种布局我都尝试过, 在数据量 3000+(node: 1000, edge:2000)的时候,  force2布局在开启了 animate 的情况下. 节点初始位置展示出来只用了1s左右, 但是在不断的布局计算过程, 动画一直持续了 30s+, 才完成最后的布局(动画停止), 也就是说,如果不开启animate, 页面将会有 30s 的白屏, 才会显示出图; 而在使用fruchterman布局,  render 过程大概有 2s 左右的白屏, 然后就完成了布局,  这个性能差距巨大,  是我设置有误还是理解有误, 为何fruchterman会性能好这么多?
      以我的项目来说, 布局很纠结, 我测试的**三种布局的优缺点:**
      1.  force2, 布局计算持续 30s, 节点一直在不断移动, **时间太久**, 但是**布局完成后,节点不会重叠在一起**;
      2. force 性能适中, 节点动画移动较快, 可以接受动画的时间, 节点也不会重叠,  但是**动画无法取消**;
      3. fruchterman, 布局最快, 但是布局完成后,节点重叠gravity/clusterGravity已经设置了很小的值,  关系较为频繁的**节点还是会重叠**;
      所以对于布局, 目前从性能角度选择了fruchterman, 但节点会重叠..所以很纠结

请老师指教~

### 重现链接

无

### 重现步骤

暂无

### 预期行为

暂无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![Uploading image.png…]()
![Uploading image.png…]()

### 补充说明（可选）

 暂无

**Comment by chaoranfeng** [comment]
<img width="776" alt="g6-gitissus@2x" src="https://user-images.githubusercontent.com/30174442/222654613-339bbfe3-445b-477a-bc15-4f5899418d3b.png">
<img width="678" alt="g6" src="https://user-images.githubusercontent.com/30174442/222654841-8c9b69d5-f948-46a6-b947-4ba60e771e91.png">
图片没传上来, 重新传了下!

**Comment by wuwuxi** [comment]
同样遇到fruchterman布局节点重叠，设置clustering聚类布局无效的情况，有解决办法 可以互相交流一下

**Comment by Yanyan-Wang** [comment]
fruchterman 支持 GPU 布局，在比较大规模的数据时，支持 GPU 布局的性能是最好的。小规模数据反而 GPU 的性能没有那么好。force2 慢的问题，因为力导的收敛速度和结果非常依赖初始输入的位置，有一个好的初始位置的话，布局会很快就结束，可以通过 layout 的 preset 给 force2 配置一个预布局。我刚刚发了一个 beta 版本 4.8.8-beta.0，支持了 preset 配置 gpuEnabled，这样你可以把 fruchterman 的 gpu 版本作为 preset，然后再运行 force2，可以加速很多。

另外，force2 的参数也很可能影响速度，我 mock 了一个 3k 节点的数据，在这个配置下速度比较快：
`
layout: {
        preset: {
          type: 'fruchterman',
          gpuEnabled: true,
          gravity: 1,
          width: 1000,
          height: 1000,
        },
        type: 'force2',
        animate: true,
        linkDistance: 50,
        maxSpeed: 2000,
        damping: 0.3,
        interval: 0.05,
        minMovement: 5,
      },
`

**Comment by lx1996627** [comment]
我试着用了你给的这个配置  我的节点数量是540个 还是有上述的2个问题  ：1.节点重叠  2.动画计算过程很长  超30S

**Comment by lx1996627** [comment]
我试着用了你给的这个配置  还是有上述的2个问题  ：1.节点重叠  2.动画计算过程很长  超30S

**Comment by lx1996627** [comment]
必须要你最新的beta吗？😂😂😂我好像用的是4.8.7



---原始邮件---
发件人: "Yanyan ***@***.***&gt;
发送时间: 2023年3月14日(周二) 下午5:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [antvis/G6] 关于大数据量性能优化请教 (Issue #4333)




  
我试着用了你给的这个配置 我的节点数量是540个 还是有上述的2个问题 ：1.节点重叠 2.动画计算过程很长 超30S
  
用的是不是 beta ***@***.******@***.***
 还没发正式版，直接重装的话是装不到的

**Comment by Yanyan-Wang** [comment]
> 必须要你最新的beta吗？😂😂😂我好像用的是4.8.7
> […](#)
> ---原始邮件--- 发件人: "Yanyan ***@***.***&gt; 发送时间: 2023年3月14日(周二) 下午5:57 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [antvis/G6] 关于大数据量性能优化请教 (Issue #4333) 我试着用了你给的这个配置 我的节点数量是540个 还是有上述的2个问题 ：1.节点重叠 2.动画计算过程很长 超30S 用的是不是 beta ***@***.******@***.*** 还没发正式版，直接重装的话是装不到的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

当然啦，beta 版刚刚支持的呀，正式版本还没更新

**Comment by lx1996627** [comment]
关于部分布局&nbsp; 例如combocombined布局的workerenabled属性在某些布局api中有显示&nbsp; 实际却无法使用&nbsp; 会报错&nbsp; &nbsp;这个问题你们有关注吗？



---原始邮件---
发件人: "Yanyan ***@***.***&gt;
发送时间: 2023年3月20日(周一) 中午11:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [antvis/G6] 关于大数据量性能优化请教 (Issue #4333)




  
必须要你最新的beta吗？😂😂😂我好像用的是4.8.7
 …
 ---原始邮件--- 发件人: "Yanyan @.&gt; 发送时间: 2023年3月14日(周二) 下午5:57 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [antvis/G6] 关于大数据量性能优化请教 (Issue #4333) 我试着用了你给的这个配置 我的节点数量是540个 还是有上述的2个问题 ：1.节点重叠 2.动画计算过程很长 超30S 用的是不是 beta @.@. 还没发正式版，直接重装的话是装不到的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
当然啦，beta 版刚刚支持的呀，正式版本还没更新

**Comment by ephraimrothschild** [comment]
@Yanyan-Wang Are there plans to enable GPU support for the comboCombined layout? I've been trying to get comboCombined working for a large graph that is several combos deep, and it seems to just give up after a few seconds and display nothing (it works when the graph is small though)

**Comment by Yanyan-Wang** [comment]
> @Yanyan-Wang Are there plans to enable GPU support for the comboCombined layout? I've been trying to get comboCombined working for a large graph that is several combos deep, and it seems to just give up after a few seconds and display nothing (it works when the graph is small though)

Could you pls give me a demo and I will check out the reason

**Comment by wuwuxi** [comment]
因为有部分用户电脑不支持gpuEnabled 的布局，通过layout 的 preset 给 force2 配置fruchterman 预布局也会严重变形，请问在force2 布局的情况下 有更好的办法吗，ps：我们的数据量比较大 节点自定义图形比较多，用force2布局有时候要几分钟才能计算完成

**Comment by chaoranfeng** [comment]
> fruchterman 支持 GPU 布局，在比较大规模的数据时，支持 GPU 布局的性能是最好的。小规模数据反而 GPU 的性能没有那么好。force2 慢的问题，因为力导的收敛速度和结果非常依赖初始输入的位置，有一个好的初始位置的话，布局会很快就结束，可以通过 layout 的 preset 给 force2 配置一个预布局。**我刚刚发了一个 beta 版本 @antv/g6@4.8.8-beta.0，支持了 preset 配置 gpuEnabled**（之前的版本 preset 无法运行 gpuEnabled 的布局），这样你可以把 fruchterman 的 gpu 版本作为 preset，然后再运行 force2，可以加速很多。
> 
> 另外，force2 的参数也很可能影响速度，我 mock 了一个 3k 节点的数据，在这个配置下速度比较快：
> 
> ```
> layout: {
>         preset: {
>           type: 'fruchterman',
>           gpuEnabled: true,
>           gravity: 1,
>           width: 1000,
>           height: 1000,
>         },
>         type: 'force2',
>         animate: true,
>         linkDistance: 50,
>         maxSpeed: 2000,
>         damping: 0.3,
>         interval: 0.05,
>         minMovement: 5,
>       },
> ```

非常感谢, 目前这样配置, force2性能会比单纯的fruchterman 性能更快一些, 且节点机会不会重叠,  多谢多谢!

**Comment by kevindurant-source** [comment]
这个布局，我这里在mac电脑布局和windows电脑布局不一样，差距很大， mac电脑的布局节点离的很远
