### ISSUE TITLE
选中多个节点的情况下，node-drag Behavior 的 shoudEnd 方法中，有办法拿到实际拖动结点的实例吗？

### ISSUE THREAD

**Issue by dapangxue** [antvis/G6#4334]
### 问题描述

比如在 Graph 中同时选中了 1 2 3 4 5 号结点，拖动 3 号结点触发 shouldEnd 回调后，希望有属性可以拿到 3 号节点的实例。

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
drag-node 的 shouldEnd 第三个参数 self 是该交互对象，behavior.targets 是正在拖拽的实例。
https://g6.antv.antgroup.com/manual/middle/states/default-behavior#drag-node

**Comment by dapangxue** [comment]
已解决，感谢
