### ISSUE TITLE
多次打开depth小的combo，会导致depth小的combo覆盖depth大的combo

### ISSUE THREAD

**Issue by ThePrestiger** [antvis/G6#4335]
### 问题描述

多次打开depth小的combo，会导致depth小的combo覆盖depth大的combo

### 重现链接

多次打开depth小的combo，会导致depth小的combo覆盖depth大的combo

### 重现步骤

1、新增两个默认关闭的combo： comboA comboB；
2、渲染结束后，comboA.getModel().depth < comboB.getModel().depth
3、comboA拖到画布空白区域后，双击打开comboA，拖动comboA到comboB上，然后双击关闭comboA；
4、重复步骤3 comboB.getModel().depth - comboA.getModel().depth次，会出现，comboA层级高于comboB

### 预期行为

comboB的层级应该始终高于comboA

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）
![Snipaste_2023-03-04_14-16-00](https://user-images.githubusercontent.com/22299121/222879557-e5b72fec-4985-476c-8c76-85de7943aec4.png)

**Comment by Yanyan-Wang** [comment]
可以通过 combo.toFront() 提升层级

**Comment by mugo1993-ss** [comment]
> 可以通过 combo.toFront() 提升层级
combo.toFront()跟node使用一样吗？为什么不生效呢
