### ISSUE TITLE
关于同方向的边重叠问题

### ISSUE THREAD

**Issue by weimengdexiaolaohu-8** [antvis/G6#4337]
### 问题描述

[在公司项目中在做流程图的需求，在渲染的时候，对于同一方向的边相互重叠，导致图看起来节点之间只有一个线，其实底部还有一根线。如上传视频中，未开始至进行中有一根线，未开始至已完成也有一根线，但在初始化或者添加边时，却没有明显的展示，边重叠了。请问是否有什么方法将线绕过节点连线，或者将线分开。查看文档虽然有个 util 方法 processParallelEdges插件，但只能解决两节点双向的情况，却不能很好的适应间隔一个节点间通向边的重叠问题，还请指教！

### 重现链接

无

### 重现步骤

无

### 预期行为

希望线不要重叠

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

Uploading 4621_1678085991.mp4…

**Comment by Yanyan-Wang** [comment]
没有看到视频，可能没上传成功。给一个在线复现的 demo 吧

**Comment by weimengdexiaolaohu-8** [comment]
https://user-images.githubusercontent.com/83323349/223345476-68ae716f-3d90-4070-8971-d7c3f2dd6531.mp4
我重新上传了视频连接，麻烦查看下！

**Comment by weimengdexiaolaohu-8** [comment]
github上已经重新上传了视频，请查看！





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/G6"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月7日(星期二) 下午2:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [antvis/G6] 关于同方向的边重叠问题 (Issue #4337)





 
没有看到视频，可能没上传成功。给一个在线复现的 demo 吧

**Comment by Yanyan-Wang** [comment]
使用 dagre 布局，把配置项 controlPoints 打开，并使用 polyline 作为边类型
