### ISSUE TITLE
画布渲染，出现残影，在不使用localRefresh=false请况下，有其他解决方案么

### ISSUE THREAD

**Issue by tohuyanluanyu** [antvis/G6#4338]
### 问题描述

![20230306-150803](https://user-images.githubusercontent.com/17723442/223043196-db105ac3-0e47-4c57-93ff-25caf33d5fc5.jpeg)

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
https://g6.antv.antgroup.com/manual/faq/faq#%E6%B8%B2%E6%9F%93%E6%AE%8B%E5%BD%B1%E9%97%AE%E9%A2%98
