### ISSUE TITLE
非多次迭代布局也需要支持过渡动画

### ISSUE THREAD

**Issue by xiaoiver** [antvis/G6#4339]
* 所有布局都支持过渡动画，动画相关配置和 G、G2 保持一致
* 手动更新节点位置的需求：不新增 API，完全通过自定义布局实现，当然也自然支持过渡动画

## 不包含迭代布局的过渡动画

对于包含多次迭代的布局算法例如 Force，在 onTick 中重绘即可实现平滑的动画过渡效果，即在每次迭代中更新节点位置。
那么对于不包含多次迭代布局的算法，当 `animated` 选项开启时，也需要提供一个布局前后的过渡效果，例如：

```js
graph.layout({
  type: 'circular',
  center: [250, 250],
  radius: 100,
  animated: true,
  animationEffectTiming: {
    duration: 1000,
    easing: 'linear',
  },
});
```

### [EffectTiming](https://developer.mozilla.org/en-US/docs/Web/API/EffectTiming) 动画描述

需要注意的是，对于带多次迭代的布局，`animationEffectTiming` 会被忽略，例如无法通过 duration 控制具体过渡的时间。但对于不带多次迭代的布局，则可以完全控制，甚至指定缓动函数。相比 G6 4.0，可以直接使用 G 的动画配置好处多多：
1. 更多符合 WAAPI 的标准配置项，例如 `delay`，`endDelay`，`easing` 内置了[更多的缓动函数](https://g.antv.antgroup.com/api/animation/waapi#easing-1)，支持[自定义缓动函数](https://g.antv.antgroup.com/api/animation/waapi#easingfunction)等
2. 与同样使用 G 动画描述的 G2 保持一致

详见：
https://g.antv.antgroup.com/api/animation/waapi#effecttiming

### 动画过程控制

执行一组连续的布局变换，前两个带动画，最后一个不带：

```js
await graph.layout({
  type: 'circular',
  center: [250, 250],
  radius: 100,
  animated: true,
  animationEffectTiming: {
    duration: 1000,
    easing: 'in-out-bounce',
  },
});
await graph.layout({
  type: 'random',
  animated: true,
  animationEffectTiming: {
    duration: 1000,
  },
});
await graph.layout({
  type: 'circular',
  center: [250, 250],
  radius: 200,
});
```

![Mar-07-2023 14-58-50](https://user-images.githubusercontent.com/3608471/223347651-0b2f0bb3-7784-4d9b-a36b-2c67e046c636.gif)

在动画过程中同样也可以通过 `stopLayout` 停止：

```js
graph.layout({
  type: 'circular',
  center: [250, 250],
  radius: 100,
  animated: true,
  animationEffectTiming: {
    duration: 1000,
    easing: 'linear',
  },
});

graph.stopLayout();
```

## 手动指定节点位置

在 G6 4.0 中会在 Graph 上提供一个通用的动画方法，用户可以手动更新 model 中各个节点的位置，调用 `positionsAnimate` 开始执行过渡动画：
https://g6.antv.antgroup.com/api/graph-func/animation
https://github.com/antvis/G6/blob/08504333507a86b61acdf3c7c38286b4d2b6b9f2/packages/core/src/graph/graph.ts#L2347

```js
// 更新节点位置
data.nodes.forEach(node => {
  node.x = Math.random() * 100;
  node.y = Math.random() * 100;
});

// 提供过渡动画
graph.positionsAnimate();
graph.stopAnimate();
```

在 G6 5.0 中，我们当然也可以效仿之前的做法，让用户通过如下方式更新图模型节点、边的位置数据，然后提供类似 API 开始动画：

```js
graph.updateData('node', [
  {
    id: 'node1',
    data: {
      x: 350,
      y: 350,
    },
  },
  // 省略其他节点
]);
```

### 通过自定义布局实现

但我们希望尽可能减少 Graph 上的 API，并且这种行为实际上就是一种自定义布局，如果能纳入现有的 layout 使用方式是更好的选择，用户可以选择实现一个自定义布局：

```js
class MyCustomLayout implements Layout<{}> {
  async assign(graph: Graph, options?: {}): Promise<void> {
    throw new Error('Method not implemented.');
  }
  async execute(graph: Graph, options?: {}): Promise<LayoutMapping> {
    const nodes = graph.getAllNodes();
    return {
      nodes: nodes.map((node) => ({
        id: node.id,
        data: {
          x: 0,
          y: 0,
        },
      })),
      edges: [],
    };
  }
  options: {};
  id: 'myCustomLayout';
}

// 注册自定义布局
stdLib.layouts['myCustomLayout'] = MyCustomLayout;

await graph.layout({
  type: 'myCustomLayout',
  animated: true, // 开启过渡动画
  animationEffectTiming: { // 动画配置同上
    duration: 1000,
    easing: 'linear',
  },
});
graph.stopLayout(); // 停止布局动画
```

当然如果觉得注册自定义布局这种完整的行为太重，毕竟一个“临时”的布局仅需要使用一次。因此我们提供一种快捷方式，类似 IIFE（Immediately Invoked Function Expression），不需要注册布局，仅需要提供布局计算逻辑：

```js
await graph.layout({
  // type: 'myCustomLayout',
  execute: async (graph) => {
// 自定义布局逻辑，提供 graph 上下文，最后返回 LayoutMapping 即可
    const nodes = graph.getAllNodes();
    return {
      nodes: nodes.map((node) => ({
        id: node.id,
        data: {
          x: 0,
          y: 0,
        },
      })),
      edges: [],
    };
  },
  animated: true, // 开启过渡动画
  animationEffectTiming: { // 动画配置同上
    duration: 1000,
    easing: 'linear',
  },
});
```

**Comment by TonyZhang1993** [comment]
@xiaoiver 你好，fruchterman / radial 布局支持动画效果吗？现想 在双击节点，展开后继节点的时候，增加动画效果；展开后继节点方式通过changeData；目前效果是瞬间出现效果，不存在中间动画；
layout中配置
    animated: true,
    animationEffectTiming: {
      duration: 1000,
      easing: 'linear',
    },
也无效果。
望建议或指正，谢谢

**Comment by xiaoiver** [comment]
> @xiaoiver 你好，fruchterman / radial 布局支持动画效果吗？现想 在双击节点，展开后继节点的时候，增加动画效果；展开后继节点方式通过changeData；目前效果是瞬间出现效果，不存在中间动画； layout中配置 animated: true, animationEffectTiming: { duration: 1000, easing: 'linear', }, 也无效果。版本4.3.11 望建议或指正，谢谢

感谢您的关注，这个特性目前我们在 5.x 新版中实现，旧版受限于 API 设计暂不支持。

**Comment by TonyZhang1993** [comment]
你好，你的邮件已收到，我会尽快给您回复。
