### ISSUE TITLE
多次重复调用net.update方法时节点无法实时重绘

### ISSUE THREAD

**Issue by onlinegenerator** [antvis/g6#434]
* **G6 Version**:1.0.*
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

重复步骤：连续调用多次net.update方法，以修改多个节点，实现节点间连续变化的效果

结果，达不到预期效果，到最后所有节点才一起重绘

**Comment by TomHuangCN** [comment]
写个 codepen
