### ISSUE TITLE
节点调用graph.hideItem() 后会占用画布位置，节点变得稀疏

### ISSUE THREAD

**Issue by zcjpass** [antvis/G6#4340]
### 问题描述

节点调用graph.hideItem() 后会占用画布位置，节点变得稀疏

<img width="1411" alt="企业微信截图_8550fad9-58a4-49f8-810e-0b3e39cb951d" src="https://user-images.githubusercontent.com/40134043/223137974-2794cc9b-095f-4901-8dca-8bb4398cdb36.png">

### 重现链接

https://g6.antv.antgroup.com/zh/examples/case/treeDemos/#mindmap

### 重现步骤

tree.getNodes().forEach(node => {
  if (node.get('id') == '0-1-4' || node.get('id') == '0-1-3') {
    tree.hideItem(node.get('id'))
  }
  tree.layout()
})

### 预期行为

1

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by zcjpass** [comment]
> 请尝试 4.8.8，并为树图布局配置 excludeInvisibles: true
使用了，但hideItem之后进行添加/删除节点或者折叠展开/拖拽等操作画布就会乱了

**Comment by Yanyan-Wang** [comment]
更新到 4.8.9 ，修复了
