### ISSUE TITLE
G6中的combo布局是否有碰撞算法呢？

### ISSUE THREAD

**Issue by AmandaKitten** [antvis/G6#4341]
### 问题描述

![image](https://user-images.githubusercontent.com/18146419/223160735-94291245-4b19-400b-8629-1dc5cbe294fe.png)

请问使用comboCombined布局的时候，combo是否可以拥有类似官网的【图表决策】样例中node的不重叠效果？

或者说，我是否能有办法获取到当前combo不管是开启还是关闭状态下的实时半径去自行计算碰撞呢？

参考【图标决策】中，使用  `nodeSize: (d) => { return d.size / 2 + 5; },` 来获取nodeSize，但是API中指示的nodeSize仅为Number类型，在comboCombined布局中使用箭头函数写法也无法打印出任何数据。不太明白这个d来源于哪里。是否可以协助我拿到当前combo的实时半径

### 重现链接

https://g6.antv.antgroup.com/examples/case/graphDemos/#decisionBubbles

### 重现步骤

探索新写法，重现链接是我参照的官网【图标决策】样例链接

### 预期行为

我希望能寻求到设置combo可以进行碰撞检测或者可以拿到combo的当前R值。

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
comboCombined 算法已经考虑了 combo 的大小进行力导计算，以方式重叠
文档：http://g6.antv.antgroup.com/api/graph-layout/combo-combined
源码：https://github.com/antvis/layout/blob/f6ee2bd6ea3d2e26994b72eec75419516d67694d/src/layout/comboCombined.ts#L117
