### ISSUE TITLE
调用updateItem 修改隐藏的节点的值会报错

### ISSUE THREAD

**Issue by zcjpass** [antvis/G6#4342]
### 问题描述

对于隐藏的节点，调用updateItem 修改会报错，有没有办法可以修改隐藏的节点

### 重现链接

无

### 重现步骤

1

### 预期行为

1

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
给一个在线复现的 demo 呢？

**Comment by zcjpass** [comment]
> 给一个在线复现的 demo 呢？

https://g6.antv.antgroup.com/zh/examples/case/treeDemos/#mindmap

**Comment by zcjpass** [comment]
> > 给一个在线复现的 demo 呢？
> 
> https://g6.antv.antgroup.com/zh/examples/case/treeDemos/#mindmap

<img width="566" alt="企业微信截图_3f5fbb0a-fb57-4161-b8f2-9b1285e57609" src="https://user-images.githubusercontent.com/40134043/223338128-8ff764be-7dc5-4819-a637-9baf31695e14.png">

<img width="411" alt="企业微信截图_385c94c5-f3a8-4b43-92eb-fefb7c7ca73a" src="https://user-images.githubusercontent.com/40134043/223338219-8c3e93e2-3636-4965-8f89-a43227cb96dd.png">

<img width="790" alt="企业微信截图_0effc24c-c0bf-457b-9a1d-cfd715c0805f" src="https://user-images.githubusercontent.com/40134043/223338342-1f158be1-3a4e-4d24-9834-149bf00371ae.png">



如上图，折叠状态下调用udpateItem 会报错

**Comment by zcjpass** [comment]
> 给一个在线复现的 demo 呢？

有没有办法可以不展开就可以更新折叠的节点数据呢，等点击展开的时候就显示最新的数据

**Comment by Yanyan-Wang** [comment]
树图的 collapse 并不是隐藏节点，而是移除了被收起的节点，没有 item 所以不能调用它的方法。我理解你的需求就在 collapse-expand 的 onChange 里面去更新数据就好了
