### ISSUE TITLE
Dagre Layout布局下，同一层次节点重合

### ISSUE THREAD

**Issue by zhl0916** [antvis/G6#4347]
### Describe the bug

![image](https://user-images.githubusercontent.com/86824254/223412121-5d8243e9-e1d9-491e-8e91-c91fa1d5279b.png)
![image](https://user-images.githubusercontent.com/86824254/223412174-6ec4ce9e-3fa7-460e-9709-8a26e97c2d36.png)
以上配置导致两个节点重合

### Your Example Website or App

https://codesandbox.io/s/naughty-blackburn-2kzuo7?file=/index.js

### Steps to Reproduce the Bug or Issue

层次布局下，按照配置，节点位置会出现错乱

### Expected behavior

节点均匀分布

### Platform

- OS: [ Windows]
- Browser: [Chrome]
- Version: [105.0.5195.102]

**Comment by Sunxinqiang** [comment]
![WX20230322-195437](https://user-images.githubusercontent.com/17586453/226897632-50f79e21-6f40-4876-a4ac-bc42232309ef.png)

**Comment by zhl0916** [comment]
那Dagre布局下，相同层次的节点之间就不能有连线了吗

**Comment by zhang867dong** [comment]
那Dagre布局下，相同层次的节点之间就不能有连线了吗

**Comment by Aarebecca** [comment]
> 那Dagre布局下，相同层次的节点之间就不能有连线了吗

是的，这种特殊情况需要自行进行布局定制

**Comment by zhang867dong** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
