### ISSUE TITLE
拖拽节点时，偶现只触发了dragStart,不触发dragEnd

### ISSUE THREAD

**Issue by ljhnhlh** [antvis/G6#4349]
### 问题描述

<img width="1823" alt="image" src="https://user-images.githubusercontent.com/31660141/223680864-127a3a19-381c-4994-bf18-1f299b5e1e5d.png">

### 重现链接

无

### 重现步骤

1.拖动节点，移动到某节点后面
2. 放下节点

### 预期行为

放下节点时触发dragEnd动作，

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.x]

### 屏幕截图或视频（可选）

<img width="1823" alt="image" src="https://user-images.githubusercontent.com/31660141/223681257-482bdfc4-6b5d-46b4-a036-d94c079f171c.png">

**Comment by Yanyan-Wang** [comment]
实际上在拖拽 delegate 吧，就是那个半透明虚线框矩形，所以 dragend 没有在 node 上发生

**Comment by ljhnhlh** [comment]
> 实际上在拖拽 delegate 吧，就是那个半透明虚线框矩形，所以 dragend 没有在 node 上发生

但是 dragend不是拖起后释放鼠标就会触发嘛，正常情况下我拖delegate到空白画布处也是有dragend的回调的
