### ISSUE TITLE
自定义节点，要如何update呢？

### ISSUE THREAD

**Issue by SilenceCarrot** [antvis/g6#435]
自定义的节点，无法update。但是换成自定义的节点就没有问题。有点绝望。。。
`
G6.registerNode('hexagon', {
  draw: function draw(item) {
    let vertexPosition = calculateHexagonVertex(30);
    let xs = vertexPosition.xs;
    let ys = vertexPosition.ys;

    const group = item.getGraphicGroup();

    group.addShape('path', {
      attrs: {
        path: `m ${xs[0]},${ys[0]} l ${xs[1]},${ys[1]} l ${xs[2]},${ys[2]} l ${xs[3]},${ys[3]} l ${xs[4]},${ys[4]} l ${xs[5]},${ys[5]} z`,
        lineWidth: 2,
        lineJoin: 'round',
        stroke: '#54BECC',
        anchor: [[0, 0.5], [1, 0.5]],
      }
    });

    return group.addShape('text', {
      attrs: {
        x: -55,
        y: 10,
        fill: '#333',
        text: item.model.label
      }
    });
  }
});

  onNodeMouseenter = e => {
    const item = e.item;
    const node = this.graph.find(item.id);
    this.graph.update(node, {
      // lineWidth: 5
      color: 'green'
    });
  };
`
同样是这个自定义节点，我想要使用onNodeClick事件，但是发现点击到text才出发事件，点击到六边形的空白区域(非text区域)，根本不会出发click事件。怎嘛办。。。。

**Comment by TomHuangCN** [comment]
写个 codepen
