### ISSUE TITLE
dagre布局拓扑图如何更改图算法为BreadthFirstSearch(BFS)广度搜索算法？

### ISSUE THREAD

**Issue by lanadelrayy** [antvis/G6#4351]
### 问题描述

请问在4.6.18版本下，dagre布局绘制的拓扑图所渲染的图样式不太符合预期，希望更改为BreadthFirstSearch（BFS）广度搜索算法，具体该怎么实现呢？官网的图算法样例代码过于简略了，不是很理解

### 重现链接

无

### 重现步骤

1、dagre布局绘制了拓扑图，调用真实数据后发现线路交叉、相邻节点间距太远等渲染问题，希望更改图算法来优化渲染显示

### 预期行为

通过广度搜索算法优化拓扑图渲染效果，减少线路交叉、缩进相邻节点距离、层次布局更加合理。

### 平台

- 操作系统: [ Windows]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.6.18 ]

**Comment by Yanyan-Wang** [comment]
dagre 跟 BFS 有啥关联？我建议通过调整布局的节点间距参数、打开 controlPoints，边使用 polyline 的方式来调整布局。想要重新写布局的话成本很高，你可以看看 dagre 的代码量：

https://github.com/antvis/layout/tree/master/src/layout/dagre

或者按照你的业务逻辑，可以自己设计一个布局算法，通过自定义布局来实现。

**Comment by lanadelrayy** [comment]
感谢回答，我用dagre做的拓扑图，然后你建议的这些点我也都设置了，但是最后效果不是理想状态，所以猜测会不会是图算法的问题，想着更改算法效果会不会好一点

**Comment by Yanyan-Wang** [comment]
效果差的截图，以及期望的效果，可以放图看看

**Comment by caohonghai** [comment]
> dagre 跟 BFS 有啥关联？我建议通过调整布局的节点间距参数、打开 controlPoints，边使用 polyline 的方式来调整布局。想要重新写布局的话成本很高，你可以看看 dagre 的代码量：
> 
> https://github.com/antvis/layout/tree/master/src/layout/dagre
> 
> 或者按照你的业务逻辑，可以自己设计一个布局算法，通过自定义布局来实现。

麻烦请问下，目前我正在调研 G6，自定义布局算法，是否需要通过修改您所给出的 https://github.com/antvis/layout/tree/master/src/layout/dagre 这部分代码进行修改重新打包呢？还是 G6 已经对外暴露了相关函数接口呢？

**Comment by Yanyan-Wang** [comment]
> > dagre 跟 BFS 有啥关联？我建议通过调整布局的节点间距参数、打开 controlPoints，边使用 polyline 的方式来调整布局。想要重新写布局的话成本很高，你可以看看 dagre 的代码量：
> > https://github.com/antvis/layout/tree/master/src/layout/dagre
> > 或者按照你的业务逻辑，可以自己设计一个布局算法，通过自定义布局来实现。
> 
> 麻烦请问下，目前我正在调研 G6，自定义布局算法，是否需要通过修改您所给出的 https://github.com/antvis/layout/tree/master/src/layout/dagre 这部分代码进行修改重新打包呢？还是 G6 已经对外暴露了相关函数接口呢？

如果是完全自研的算法，直接通过 G6.registerLayout 来写一个新的就好。现在自定义布局不能继承，但你可以在 registerLayout 里面执行 dagre，然后在它的布局结果上进行修改，本质上就是修改数据的 x y

**Comment by dbl520** [comment]
如果想调整下排序，然后在使用dagre布局，有啥思路吗
