### ISSUE TITLE
4.8.5版本打包编译报错

### ISSUE THREAD

**Issue by lx1996627** [antvis/G6#4352]
### 问题描述

在将G6版本改为4.8.5版本后  
![image](https://user-images.githubusercontent.com/53219722/223939012-a0421d00-08fb-4831-afaa-189350cca70e.png)
该部分文件TS定义  在编译时  无法通过编译

![image](https://user-images.githubusercontent.com/53219722/223939495-14e0f6b9-fdb7-412d-8456-3529edc9feb8.png)
我将该部分TS定义改为这样之后  编译可通过  但该方法不是长久之计  

### 重现链接

CodeSandbox

### 重现步骤

nodejs  npm run build

### 预期行为

编译成功

### 平台

- 操作系统: [ Windows, Nodejs 14.19.0 ]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.8.5 ... ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/53219722/223938838-c9ce969c-6563-4204-9567-39e95577d494.png)

**Comment by Yanyan-Wang** [comment]
升级一下 ts 版本

**Comment by lx1996627** [comment]
好的&nbsp; 谢谢解答！



---原始邮件---
发件人: "Yanyan ***@***.***&gt;
发送时间: 2023年3月14日(周二) 下午5:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [antvis/G6] 4.8.5版本打包编译报错 (Issue #4352)




 
升级一下 ts 版本
