### ISSUE TITLE
如何动态设置右键菜单

### ISSUE THREAD

**Issue by wuwuxi** [antvis/G6#4353]
### 问题描述

我想动态设置右键菜单

### 重现链接

无

### 重现步骤

无

### 预期行为

试了两中方式都没有实现

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![1678260834581_942B0C53-639C-4df4-80CA-794107020A8E](https://user-images.githubusercontent.com/27846587/223684242-d0af7442-a0fa-4d86-adfe-4a10cffb7097.png)
![image](https://user-images.githubusercontent.com/27846587/223684312-cf1ffbec-7ba4-4083-bebb-9c6ee8aef1be.png)

**Comment by wuwuxi** [comment]
已解决

**Comment by Yanyan-Wang** [comment]
可以自定义 dom 作为右键菜单，挂载方式参考：https://g6.antv.antgroup.com/manual/advanced/coordinate-system

**Comment by Yanyan-Wang** [comment]
已解决的话，就先关闭了，再有问题就再开个新的
