### ISSUE TITLE
force2布局，自定义节点，拖动事件问题

### ISSUE THREAD

**Issue by Tina75** [antvis/G6#4354]
### Describe the bug

1、快速拖动时，在还没有停止布局情况下截屏，Alt + Shift(必须) + A后
2、拖动会出现点击实体，实体就跟着移动了，而且整个画布会有小手的图标

### Your Example Website or App

website

### Steps to Reproduce the Bug or Issue

1、快速拖动时，在还没有停止布局情况下截屏，Alt + Shift(必须) + A后
2、拖动会出现点击实体，实体就跟着移动了，而且整个画布会有小手的图标

### Expected behavior

只有拖动实体时，实体才跟着被拖动

### Platform

- OS: Windows,
- Browser: Chrome 110
- Version: "@antv/g6": "4.8.2"

**Comment by Yanyan-Wang** [comment]
给个在线复现 demo？

**Comment by Tina75** [comment]
https://codesandbox.io/p/github/Tina75/graph-test/master?file=%2FREADME.md&workspace=%257B%2522activeFileId%2522%253A%2522clf90ceal0053g4g20h8k5ypo%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clf90chvp000x3n6snid14i6r%2522%253A%257B%2522key%2522%253A%2522clf90chvp000x3n6snid14i6r%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522key%2522%253A%2522clf90chvp000y3n6sgi9xc2zj%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522key%2522%253A%2522clf90cmyt008p3n6swfxtwdtp%2522%252C%2522isMinimized%2522%253Afalse%252C%2522path%2522%253A%2522%252F%2523%252Fg6demo%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522clf90ckuj00643n6sjzepflke%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clf90chvp000x3n6snid14i6r%2522%252C%2522spacesOrder%2522%253A%255B%2522clf90chvp000x3n6snid14i6r%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D

**Comment by Yanyan-Wang** [comment]
试了一下好像没有出现这个问题，我的操作步骤是：拖拽一个节点，释放时马上 shift+command+A 截图，取消截图。有什么复现诀窍？

**Comment by Tina75** [comment]
快速拖动的时候不要释放，立马截图。我是微信截图的，复现概率很大
