### ISSUE TITLE
自定义节点，拖动时，节点会跑的比线快

### ISSUE THREAD

**Issue by Tina75** [antvis/G6#4358]
### Describe the bug

![微信图片_20230314151059](https://user-images.githubusercontent.com/26056312/224923117-7ff68c34-7574-4033-ba76-7d790bf740d3.png)

### Your Example Website or App

https://gitee.com/tina_75/graph-study.git

### Steps to Reproduce the Bug or Issue

1、选择g6demo路由
2、拖动中间节点，线不会立刻跟着动，会有偏离

### Expected behavior

我希望线跟着节点快速移动，不然感觉不流畅

### Platform

- OS: Windows
- Browser: Chrome,
- Version:"@antv/g6": "4.8.2"

**Comment by Yanyan-Wang** [comment]
给个在线复现 demo？

**Comment by Tina75** [comment]
https://codesandbox.io/p/github/Tina75/graph-test/master?file=%2FREADME.md&workspace=%257B%2522activeFileId%2522%253A%2522clf90ceal0053g4g20h8k5ypo%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clf90chvp000x3n6snid14i6r%2522%253A%257B%2522key%2522%253A%2522clf90chvp000x3n6snid14i6r%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522key%2522%253A%2522clf90chvp000y3n6sgi9xc2zj%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522key%2522%253A%2522clf90cmyt008p3n6swfxtwdtp%2522%252C%2522isMinimized%2522%253Afalse%252C%2522path%2522%253A%2522%252F%2523%252Fg6demo%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522clf90ckuj00643n6sjzepflke%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clf90chvp000x3n6snid14i6r%2522%252C%2522spacesOrder%2522%253A%255B%2522clf90chvp000x3n6snid14i6r%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D

**Comment by Yanyan-Wang** [comment]
因为在 node:drag 监听里面已经做了类似 drag node 的更新节点位置的逻辑，所以交互里面再配有 drag-node，可能会产生累加的效果，把 modes default 里面的 drag-node 去掉试试

**Comment by Tina75** [comment]
谢谢，是这个原因，已经解决
