### ISSUE TITLE
移动节点时获取相交的节点

### ISSUE THREAD

**Issue by avrinfly** [antvis/G6#4359]
### 问题描述

请问，我如何在移动节点的时候获取相交的节点

G6里有没有类似X6里getNodesUnderNode功能的api

![image](https://user-images.githubusercontent.com/30068005/224928744-eaaf12a5-27c7-4f9f-9ae6-4511eea6b93e.png)

### 重现链接

https://g6.antv.antgroup.com/examples/case/graphDemos#decisionBubbles

### 重现步骤

探索新写法，重现链接是我参照的官网【图标决策】样例链接

### 预期行为

我希望能在我移动节点的时候，获取相交的节点和combo

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
没有，但我理解你可以监听 node:dragover 事件中的 item 就是正在被「拖拽的节点经过」的节点
