### ISSUE TITLE
error TS2416

### ISSUE THREAD

**Issue by GUEThe** [antvis/G6#4361]
### 问题描述

![image](https://user-images.githubusercontent.com/19553651/225238593-5769e42e-8d93-4e7f-9912-3093579df81f.png)

### 重现链接

https://codesandbox.io/s/new

### 重现步骤

typescript 4.6.4
@antv/g6 4.8.7

### 预期行为

无构建报错

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: 4.8.7

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/19553651/225238593-5769e42e-8d93-4e7f-9912-3093579df81f.png)

**Comment by Yanyan-Wang** [comment]
试一下 v4.8.8
