### ISSUE TITLE
drag 拖到其他元素就会导致无法停止拖拽，鼠标停不下来

### ISSUE THREAD

**Issue by zcjpass** [antvis/G6#4362]
### 问题描述

drag 拖到其他元素就会导致无法停止拖拽，鼠标停不下来

<img width="912" alt="image" src="https://user-images.githubusercontent.com/40134043/225244324-411cdf85-014e-4306-94e3-50ea3c2eb3a9.png">

### 重现链接

无

### 重现步骤

<img width="912" alt="image" src="https://user-images.githubusercontent.com/40134043/225244340-d7e399b3-d259-47fa-ae52-4be90a941c1d.png">

### 预期行为

希望不影响拖拽

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
更新到最新版本试试

**Comment by zcjpass** [comment]
> 

4.0版本，最新版本是有做了什么优化吗

**Comment by zcjpass** [comment]
> 目前用的什么版本？更新到最新版本试试

4.0版本，最新版本是有做了什么优化吗

**Comment by Yanyan-Wang** [comment]
> > 目前用的什么版本？更新到最新版本试试
> 
> 4.0版本，最新版本是有做了什么优化吗

4.0 有点老了，现在最新 4.8.7，中间应该处理过类似的问题，不确定你这里是不是同样的问题，先试试看

**Comment by zcjpass** [comment]
> > > 目前用的什么版本？更新到最新版本试试
> > 
> > 
> > 4.0版本，最新版本是有做了什么优化吗
> 
> 4.0 有点老了，现在最新 4.8.7，中间应该处理过类似的问题，不确定你这里是不是同样的问题，先试试看

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/40134043/231108787-db478940-8cfc-490f-a065-a9de2f80facc.png">
换了最新版本还是会
