### ISSUE TITLE
设置定时器每秒使用 changeDate 修改部分节点颜色，鼠标悬浮的状态消失没有保存

### ISSUE THREAD

**Issue by sishen654** [antvis/G6#4363]
### Describe the bug

每秒变化部分节点颜色，但是鼠标悬停后我想继续变，但是结果是并没有保持住我鼠标悬停时的状态（线条活跃，其他线条变淡），我只能在悬停时将颜色改变停止掉
不知道是不是 bug，翻阅了文档并没有找到解决方案：
![动画](https://user-images.githubusercontent.com/65691266/225247238-57cc0651-35d6-4b16-a031-629ee0800612.gif)

### Your Example Website or App

暂时没有

### Steps to Reproduce the Bug or Issue

暂时没有

### Expected behavior

线条的明暗悬浮状态保持住，字体也可以正常修改颜色

### Platform

G6 4.3

**Comment by Yanyan-Wang** [comment]
changeData 就相当于全量更新数据了。如果你想保留状态，通过 graph.updateItem 来局部更新样式

**Comment by sishen654** [comment]
> changeData 就相当于全量更新数据了。如果你想保留状态，通过 graph.updateItem 来局部更新样式

可以我去试下，看下会不会把我鼠标悬浮状态清除掉

**Comment by Yanyan-Wang** [comment]
解决了吗

**Comment by sishen654** [comment]
> 解决了吗

解决了，用老哥说的  graph.updateItem ，或者 item.update 都可以
