### ISSUE TITLE
动态添加节点 展开收缩 不正常

### ISSUE THREAD

**Issue by luosijie** [antvis/G6#4372]
### 问题描述

动态添加节点数据后
节点展开一半又自动收缩回去
第2次点击正常打开

官方案例有这个问题 
个人的案例测试也会

### 重现链接

https://g6.antv.antgroup.com/zh/examples/interaction/treeBehavior#changeData

### 重现步骤

![自定义树图交互 _ G6 和另外 6 个页面 - 用户配置 1 - Microsoft​ Edge 2023-03-21 14-26-13 00_00_00-00_00_30](https://user-images.githubusercontent.com/16912206/226534069-340fe008-529b-49e3-be5d-5c130cdff0b7.gif)

### 预期行为

正常展开动态节点

### 平台

- 操作系统: Windows
- 网页浏览器: Edge
- G6 版本: 4.8.7

**Comment by Yanyan-Wang** [comment]
你是不是双击？collapse-expand 的默认触发方式是单击，如果你要改成双击，就配置 collapse-expand 的 trigger: 'dblclick'

https://g6.antv.antgroup.com/en/manual/middle/states/default-behavior#collapse-expand

**Comment by luosijie** [comment]
我是单击操作

**Comment by Yanyan-Wang** [comment]
看了一下应该是因为 node:click 里面给节点增加子树 changeData 的操作，和 collapse-expand 冲突了。单击节点时，没有 children 的节点实际上是 collapsed: false 的状态，collapse-expand 使它收起，此时又通过 changeData 给它加了子节点，所以看起来是展开又收起。只要在 graph.node 函数里面，把无 children 的节点 collapsed 设置为 true 即可：
collapsed: node.children?.length ? false : true

这个 demo 我更新一下
