### ISSUE TITLE
固定边出发锚点不变

### ISSUE THREAD

**Issue by 37-Ricardo** [antvis/G6#4374]
### 问题描述

当去拖拽其中一个节点的时候，，不论换到哪个方向，始终是取两个节点之最近的锚点来进行连线最近距离进行绘制，这样就会使边的出发锚点和结束锚点不断变化，如何能做到使得边的锚点在实例化后在拖拽过程中就保持不变

### 重现链接

暂无

### 重现步骤

1、拖拽节点
2、边开始锚点和结束锚点的位置发生变化

### 预期行为

无论怎么拖拽节点，边的锚点位置始终不变

### 平台

- 操作系统: Windows
- 网页浏览器: Google Chrome
- G6 版本: 4.5.1

**Comment by Yanyan-Wang** [comment]
给边数据写 sourceAnchor 和 targetAnchor  https://g6.antv.antgroup.com/api/items/edge-properties#sourceanchor

**Comment by 37-Ricardo** [comment]
这是来自QQ邮箱的自动回复邮件。你好，我最近正忙，无法亲自回复你的邮件。我将在解决手头的事情后，尽快给你回复。

**Comment by 37-Ricardo** [comment]
感谢，问题解决了

**Comment by J-Django-Github** [comment]
我设置了sourceAnchor 和 targetAnchor 还是无效，两个锚点上的有效，四个锚点的上面无效

**Comment by 37-Ricardo** [comment]
这是来自QQ邮箱的自动回复邮件。你好，我最近正忙，无法亲自回复你的邮件。我将在解决手头的事情后，尽快给你回复。
