### ISSUE TITLE
自定义节点 文本位置 无法准确定位

### ISSUE THREAD

**Issue by avrinfly** [antvis/G6#4375]
### 问题描述

我自定义了一个节点，在设置节点位置的时候，本想跟内置节点一样，根据labelCfg里的position来确定文本位置，我也看到文档里有个labelPosition，但我实际写入自定义节点后发现不生效

核心代码见
![20230322-161811](https://user-images.githubusercontent.com/30068005/226841119-0cb7ef0d-9551-492e-9887-c9976dcadd63.jpg)
，麻烦确认一下，是我的写法有问题还是什么情况

ps:我在源码里有看到 node本身是有getLabelStyleByPosition这个方法的，注释也有写明，不希望扩展的节点复写

### 重现链接

见描述

### 重现步骤

见描述

### 预期行为

见描述

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
position 是传入内置节点之后，根据这个值计算的 label 图形的 x y，你这儿是自己写的 label，x y 写死了 0 0 了。你可以试一下调用 this. getLabelStyleByPosition 拿到内置 circle（你继承的）类型节点计算逻辑的到 style，然后给到你这里的 label 的样式。


如果要完全自定义的话就需要自己根据 position 的计算 x y，参考内置写法：https://github.com/antvis/G6/blob/34eae7da9466377e767f4211c40687ffacd12c38/packages/core/src/element/node.ts#L51

**Comment by avrinfly** [comment]
我尝试过，我在draw里调用的，提示getLabelStyleByPosition 这个方法不存在，我就是把内置的写法又复写了一遍，就可以了。
