### ISSUE TITLE
想了解一下这种图的实现思路

### ISSUE THREAD

**Issue by 1998feng** [antvis/G6#4376]
### 问题描述

这种图该怎么用g6来实现？主要不清楚如何控制子节点向下排列
![image](https://user-images.githubusercontent.com/49889959/226843625-6998226c-976a-472a-9fe0-305114330743.png)

### 重现链接

求教

### 重现步骤

求教

### 预期行为

求教

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
参考

https://g6.antv.antgroup.com/examples/case/treeDemos#indentedTree
https://g6.antv.antgroup.com/examples/case/treeDemos#decisionTree

**Comment by 1998feng** [comment]
大佬，想不明白了。。缩进树怎么和紧凑树配合使用呀。。

**Comment by Yanyan-Wang** [comment]
这里有一个自定义树图布局的例子，结合两种树图布局算法：
https://codesandbox.io/s/focused-neumann-tn9uo2?file=/index.js
