### ISSUE TITLE
How to assign different length for each edge?

### ISSUE THREAD

**Issue by yech1990** [antvis/g6#438]
By reading the documentation, I found demos for editing edge color, width and shape. 
But I have a heterogeneous data set with different branch length across nodes. 
I can't find any examples for customizing edge length.
Could you show me a short example?  @TomHuangCN 

BTW, will g6 support parsing newick data format directly?

**Comment by TomHuangCN** [comment]
1. https://codepen.io/DoriTong/pen/PdmGxd?editors=1010
2. G6 will not format it

**Comment by yech1990** [comment]
Thanks you @TomHuangCN
