### ISSUE TITLE
combo内采用grid布局，行之间间距过大

### ISSUE THREAD

**Issue by 37-Ricardo** [antvis/G6#4381]
### 问题描述

combo内布局采用grid，但是发现行与行之间的间距过大，是否有方法可以使grid布局的行与行之间的间距缩小

### 重现链接

暂无

### 重现步骤

暂无

### 预期行为

grid布局节点行之间间距缩小

### 平台

- 操作系统: Windows
- 网页浏览器: Google Chrome
- G6 版本: 4.5.1

**Comment by Yanyan-Wang** [comment]
如果用的子图布局，可以给 grid 布局配置 width height

**Comment by 37-Ricardo** [comment]
这是来自QQ邮箱的自动回复邮件。你好，我最近正忙，无法亲自回复你的邮件。我将在解决手头的事情后，尽快给你回复。
