### ISSUE TITLE
改变层级的两个方法不生效

### ISSUE THREAD

**Issue by avrinfly** [antvis/G6#4384]
### 问题描述

在开发中，发现调用toFront()方法，改变元素的层级时，发现不生效

### 重现链接

https://codepen.io/avrinfly/pen/GRXvRzW

### 重现步骤

如demo所见，在调用toFront将所有edge层级提高后，左侧edge还是被遮挡

### 预期行为

期望可以正常使用该方法，并希望提供能修改准确层级的api

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
默认情况下，所有节点所在的 group 高于所有边所在的 group，如果你要打破这个层级关系，给 graph 配置 groupByTypes: false

https://g6.antv.antgroup.com/api/graph#graphoptionsgroupbytypes
