### ISSUE TITLE
树图中indented布局方式，如何调整不同列的indent？

### ISSUE THREAD

**Issue by 1998feng** [antvis/G6#4385]
### 问题描述

比如第一列为80，第二列为40，第三列为20

因为节点的大小不一样，小一些的节点之间希望间距也更小一点。

### 重现链接

树图中indented布局方式，如何调整不同列的indent？

### 重现步骤

树图中indented布局方式，如何调整不同列的indent？

### 预期行为

可以接受一个函数或者其他形式？

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by ali081809** [comment]
这个解决了吗？

**Comment by 1998feng** [comment]
解决了，indent 本身就是一个函数

**Comment by ali081809** [comment]
怎么解决的 可以贴一下代码不

**Comment by 1998feng** [comment]
![image](https://github.com/antvis/G6/assets/49889959/4ba22238-1e01-454f-97bf-a76153d9032c)

**Comment by ali081809** [comment]
好滴 谢谢啦~~
