### ISSUE TITLE
在视图很小的时候只有两个节点的Fruchterman布局节点会重叠在一起

### ISSUE THREAD

**Issue by tianxiumei** [antvis/G6#4393]
### Describe the bug

Fruchterman在视图很小的时候，节点会重叠在一起

### Your Example Website or App

https://codesandbox.io/s/sad-yonath-xx0tk8?file=/package.json

### Steps to Reproduce the Bug or Issue

1、进去例子
2、缩小图区域大小
3、节点一节点二重叠
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/38803966/227829360-e6f9acf3-7e5e-40af-832f-d856701bc778.png">

### Expected behavior

节点不重叠

### Platform

- OS: [e.g. macOS, Windows, Linux] mac
- Browser: [e.g. Chrome, Safari, Firefox] chrome
- Version: [e.g. 91.1] 最新

**Comment by tianxiumei** [comment]
宽度只弄成200，你这个宽度很宽了

**Comment by Yanyan-Wang** [comment]
可以给 layout 加一个预布局解决这个问题：

layout: {
  type: 'fruchterman',
  preset: {
      type: 'circular',
      width: 200,
      height: 200,
    },
  // ... 其他参数
}
