### ISSUE TITLE
开启 web-worker控制台报错

### ISSUE THREAD

**Issue by wuwuxi** [antvis/G6#4394]
### 问题描述

force布局开启 web-worker后控制台报错

### 重现链接

/

### 重现步骤

![image](https://user-images.githubusercontent.com/27846587/227839668-16bfb350-aee3-4ae2-a76d-ef7b0e8e8e58.png)

### 预期行为

节点较多在计算时也能实现交互效果

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
给一下 force 的参数。检查一下这里的注意事项：
https://g6.antv.antgroup.com/api/graph-layout/force#layoutcfgworkerenabled

**Comment by wuwuxi** [comment]
preset: {
              type: 'circular',
              width: 1000,
              height: 1000,
            },
            type: 'force2',
            animate: true,
            maxSpeed: 2000,
            maxIteration: 300,
            damping: 0.3,
            interval: 0.05,
            minMovement: 5,
            clustering: true, // 可选
            nodeClusterBy: '_type',
            clusterNodeStrength: 300,
            preventOverlap: true,
            linkDistance: 180, //边的长度
            workerEnabled: true,

**Comment by wuwuxi** [comment]
还有 这种参数设置 之后 节点会重叠是为什么？
