### ISSUE TITLE
G6节点中 defaultNode的type失效问题

### ISSUE THREAD

**Issue by daidaic** [antvis/G6#4397]
### Describe the bug

我在项目中使用节点链 发现设置的defaultNode的type失效 一直为圆形

### Your Example Website or App

抱歉 我自己写的demo文件是正常的 但引用在我的项目中会失效

### Steps to Reproduce the Bug or Issue

 代码示例如图 后面两张图是我对应的项目依赖 前两张图为我写的代码demo 第三张图为效果图 
<img width="454" alt="image" src="https://user-images.githubusercontent.com/47729929/228110903-715c12a2-327a-4094-8344-cdc626711c3b.png">
<img width="380" alt="image" src="https://user-images.githubusercontent.com/47729929/228111012-496b4c98-29eb-407d-952f-3af5ae3fd794.png">
<img width="855" alt="image" src="https://user-images.githubusercontent.com/47729929/228111318-64575825-dfce-4414-9807-39dae1410658.png">

<img width="392" alt="image" src="https://user-images.githubusercontent.com/47729929/228111075-8ad733fc-07d8-4920-a2e2-82c76bbdf1ac.png">
<img width="355" alt="image" src="https://user-images.githubusercontent.com/47729929/228111132-0ed8312c-a432-4ca4-b393-8c52146522e6.png">

### Expected behavior

希望能排查解决此问题

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
macOS 13.1
Chrome 111.0.5563.110（正式版本） (x86_64)

**Comment by daidaic** [comment]
感谢解答,我自己打印了下返回的graph 都有返回 type:'modelRect' 但此type并未生效 就很奇怪
<img width="1804" alt="image" src="https://user-images.githubusercontent.com/47729929/228407439-7adf75f6-33b2-4a83-ada5-d008616bcd85.png">
<img width="1618" alt="image" src="https://user-images.githubusercontent.com/47729929/228407709-92b7e224-6343-4354-9bcc-2c8dab5d1388.png">

**Comment by daidaic** [comment]
> 节点配置的优先级： graph.node > 数据 > graph 的 defaultNode 配置
> 
> 看下图片中你折叠起来的 graph.node 是不是没有返回 type: 'modelRect'

感谢解答,我自己打印了下返回的graph 都有返回 type:'modelRect' 但此type并未生效 就很奇怪
![image](https://user-images.githubusercontent.com/47729929/228457955-06380a99-0d16-4525-96c3-5994226580fc.png)
![image](https://user-images.githubusercontent.com/47729929/228458003-a998a117-49c5-48e6-8270-8f0cbe81dc7b.png)

**Comment by Yanyan-Wang** [comment]
从你截图中打印的内容来看数据里面并没有正确的 type，type 是 node，应该是 modelRect。currentShape 不是 G6 能识别的字段，那个是没用的
