### ISSUE TITLE
updateItem的一个问题

### ISSUE THREAD

**Issue by theDoinb** [antvis/G6#4399]
### 问题描述

我想要动态变更节点的背景颜色，所以我在【教程 > 交互与事件 > 状态state > 更新状态样式配置】看到有关于stateStyles的写法，
```
graph.updateItem(item, {
  style: {
    fill: '#1890ff',
  },
  stateStyles: {
    selected: {
      fill: '#1890ff'
    },
  },
});
```
执行后，节点本身的默认背景颜色没有变化，只有选中态的背景颜色变更了，

为什么要修改选中态的颜色？因为我是选中某个节点后去变更配置。

如果去掉`stateStyles`，倒是能正常变色，但是因为选中了所以当前节点还是选中态的样式，我总不能变更样式后去掉焦点吧...

### 重现链接

https://codesandbox.io/s/ce-shi-nn9pys?file=/demo.js

### 重现步骤

如上所述

### 预期行为

期望能正确的变更

### 平台

- 操作系统: Windows
- 网页浏览器: Google Chrome
- G6 版本: 4.8.8

### 补充说明（可选）

是因为样式叠加的关系？我也尝试了标签的编辑，fontSize、fontStyle、fill没问题，唯独fontWeight也是有同样的问题,,,

**Comment by Yanyan-Wang** [comment]
没明白，原始需求是什么？

**Comment by theDoinb** [comment]
> 没明白，原始需求是什么？给个在线复现 demo 看下？

已经加了个 demo，看看？

**Comment by theDoinb** [comment]
再问问个东西....
现在 `updateLayout` 可以基于已选的节点，来进行重新布局，而不是全部节点吗？

**Comment by Yanyan-Wang** [comment]
可以分为两步来更新暂时解决这个问题：

graph.updateItem(clickInfo, {
      style: {
        fill: rgba
      }
    });
graph.updateItem(clickInfo, {
    stateStyles: {
      selected: {
        fill: rgba
      }
    }
  });

按照 demo 中放在一起更新有问题，晚点我排查一下

**Comment by Yanyan-Wang** [comment]
> 再问问个东西.... 现在 `updateLayout` 可以基于已选的节点，来进行重新布局，而不是全部节点吗？

看一下子图布局：https://g6.antv.antgroup.com/examples/net/layoutMechanism/#subgraphLayout

**Comment by theDoinb** [comment]
好的，感谢。
