### ISSUE TITLE
Force layouts don't seem to work when using ComboCombined

### ISSUE THREAD

**Issue by ephraimrothschild** [antvis/G6#4400]
### Describe the bug

I am trying to display a graph that, on page load, only shows combos (by default, all combos are collapsed). Upon expanding the combos (some of them nested several layers deep), it should display the nodes and their edges. 

However on page load the goal is to only show collapsed combos, and have it act similarly to the [Christmas Bubbles Example](https://g6.antv.antgroup.com/en/examples/case/graphDemos#christmasBubbles). After several days of trying to debug why I couldn't seem to get this working, I discovered that it appears that when using `ComboCombined` or `ComboForce` as the layout, none of the force directed layouts work properly on the combos or nodes displayed. Even when `preventOverlap` is enabled, none of the nodes or combos seem to have an effect on pushing the others around it.

As an example, I took the Christmas Bubbles examples given in the documentation, and modified it so that it uses the `comboCombined` layout, and placed its `force` layout into the `outerLayout` configuration (I also added the `drag-node` mode to make dragging work). With only that change, the "force" part of the force layout no longer seems to have an effect, and nodes are neither drawn closer to each other, nor pushed away when dragging one node on top of another.

### Your Example Website or App

https://codesandbox.io/s/cool-worker-y9mmtg

### Steps to Reproduce the Bug or Issue

As above

### Expected behavior

When dragging nodes or combos that have an `outerLayout` of `force`, it should act the same as the [ChristmasBubbles](https://g6.antv.antgroup.com/en/examples/case/graphDemos#christmasBubbles) example, and push other nodes/combos away when dragging one node/combo over another.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
Could you give me the demo with your combo data? I saw the data in the demo now is from Christmas bubbles

**Comment by ephraimrothschild** [comment]
@Yanyan-Wang Here's a demo with similar data to what I'm using: https://codesandbox.io/s/modest-http-pwttr9
