### ISSUE TITLE
afterlayout后fitCenter无效，或者只能通过setTimeout设置居中

### ISSUE THREAD

**Issue by jinfei-lab** [antvis/G6#4401]
### 问题描述

我在updateLayout后想把布局fitCenter，但是目前遇到dagre布局和grid布局在afterlayout后写fitCenter发现无效，只能通过setTimeout设置延时来fitCenter，这个原因是因为这两个布局没有完成吗？能否有一个更好的办法来代替这种setTimeout方案，因为这样会导致布局闪动

### 重现链接

https://codesandbox.io/s/afterlayouthou-fitcenter-0s6e1f?file=/index.js

### 重现步骤

1.进入页面分别点击三个布局按钮
2.发现fitCenter无效，布局无法居中

### 预期行为

期望在切换布局后可以是用fitCenter()居中

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.7.1]

**Comment by Tina75** [comment]
遇到同样问题了

**Comment by jinfei-lab** [comment]
> 遇到同样问题了

今天要发版了，我现在切换布局没用updateLayout了，直接先销毁布局然后在重新new Graph😂

**Comment by Yanyan-Wang** [comment]
因为有动画，布局完成的时候触发了 afterlayout，但是因为动画没完成，所以节点并没有运动到最终的位置上，这时候去 fitCenter，会导致计算图内容的大小和位置不准确。可以把 graph 上配置的 animate 去掉，如果想要有一些动画的效果可以在 fitCenter 配置第一个参数(animate) 为 true，这样 fitCenter 的过程中会有动画。如果 graph 的 animate 不去掉，那就把 afterlayout 监听改为 afteranimate。并且注意如果希望第一次渲染的时候就触发这个监听，那么这个监听需要在 graph.render() 之前绑定

**Comment by jinfei-lab** [comment]
> 因为有动画，布局完成的时候触发了 afterlayout，但是因为动画没完成，所以节点并没有运动到最终的位置上，这时候去 fitCenter，会导致计算图内容的大小和位置不准确。可以把 graph 上配置的 animate 去掉，如果想要有一些动画的效果可以在 fitCenter 配置第一个参数(animate) 为 true，这样 fitCenter 的过程中会有动画。如果 graph 的 animate 不去掉，那就把 afterlayout 监听改为 afteranimate。并且注意如果希望第一次渲染的时候就触发这个监听，那么这个监听需要在 graph.render() 之前绑定

感谢耐心解答，已解决问题👍
