### ISSUE TITLE
怎么动态更新afterdraw上添加的shape和动画

### ISSUE THREAD

**Issue by CoronaAustralis** [antvis/G6#4402]
### 问题描述

现在需要动态更新动画，但是看文档上只有通过update和setState更新keyshape的，没有动态更新afterdraw上添加的shape和动画的。

### 重现链接

暂时没有

### 重现步骤

update里面只能改keyshape

### 预期行为

期望可以更改

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
动画参考 https://g6.antv.antgroup.com/examples/scatter/node/#node
开关动画通过 cfg 传入 afterDraw ，根据 cfg 决定是否添加动画或停止动画。如果继承了内置节点，那么 updateItem 将触发 update 和 afterUpdate，afterDraw 只会在第一次渲染完成后进入
