### ISSUE TITLE
使用addItem添加边，自定义边内获取不到起始点和结束点

### ISSUE THREAD

**Issue by auuunya** [antvis/G6#4403]
### 问题描述

使用darge布局, 节点和边使用addItem添加,节点的数据还好,自定义边的draw方法获取到的startPoint和endPoint都是0,0的数据,

### 重现链接

https://codesandbox.io/s/flamboyant-danny-se6l11?file=/index.js

### 重现步骤

rt

### 预期行为

我不知道在自定义边draw绘制的时候如何拿到节点位置的startPoint和endPoint,因为我需要在边上做一些自定义的功能点

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by auuunya** [comment]
重现Demo中 拿到的startPoint和endPoint都是 NAN和0 0 也差不多

**Comment by Yanyan-Wang** [comment]
第一次渲染的时候，因为节点还没有得到 x y，所以边的 startPoint 和 endPoint 也拿不到对应坐标。当布局结束后，节点有了坐标信息，G6 内部会通过 graph.updateItem 来更新相应的边，这时边的参数中才有了起点和终点的坐标。因为你的自定义边继承了内置的 single-edge，所以在 graph.updateItem 触发的更新中会调用继承基类（single-edge）的 update 方法，如果你复写 update 方法，在 update 方法中去打印 startPoint 和 endPoint ，就可以看到布局后的坐标了

**Comment by auuunya** [comment]
谢谢
