### ISSUE TITLE
树图-子节点包裹框

### ISSUE THREAD

**Issue by justforliving** [antvis/G6#4404]
### 问题描述

【问题】生成树图的时候对同类型子节点生成包裹框
【现状】参考案例 - 节点分页器 
在鼠标悬浮的时候在父节点添加一个矩形框包裹子节点

### 重现链接

https://codesandbox.io/s/wonderful-moon-v6080l?file=/src/App.vue

### 重现步骤

鼠标悬浮到节点

### 预期行为

直接显示包裹框

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome]
- G6 版本: [3.2.10]

**Comment by Yanyan-Wang** [comment]
监听 graph.on('node:mouseenter' ，创建 hull https://g6.antv.antgroup.com/api/graph-func/hull#createhullcfg-hullcfg
