### ISSUE TITLE
切换交互模式后，连线不消失

### ISSUE THREAD

**Issue by huang-yf3160** [antvis/G6#4406]
### Describe the bug

点击ADD EDGE模式，点击一个节点，然后出现连线
此时把交互模式切换到默认模式
发现连线没有消失

### Your Example Website or App

https://codepen.io/Yanyan-Wang/pen/qBBNaye

### Steps to Reproduce the Bug or Issue

https://codepen.io/Yanyan-Wang/pen/qBBNaye

### Expected behavior

连线消失

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by huang-yf3160** [comment]
有没有什么规避方案呢？

**Comment by Yanyan-Wang** [comment]
在你自定义的 click-add-edge 交互中，getEvents 增加 beforemodechange 的监听，触发当前正在新增边的移除
