### ISSUE TITLE
dagre 布局中设置 begin 参数后连线的控制点有误

### ISSUE THREAD

**Issue by xiaoiver** [antvis/G6#4407]
### Describe the bug

dagre 布局中设置 begin 参数后，连线的控制点绘制有误。

### Your Example Website or App

https://g6.antv.antgroup.com/en/examples/net/dagreFlow/#basicDagre

### Steps to Reproduce the Bug or Issue

使用这个 DEMO：
https://g6.antv.antgroup.com/en/examples/net/dagreFlow/#basicDagre

设置 begin 为 `[0, 0]` 意为 layout 左上角，此时发现连线的控制点有误：
<img width="747" alt="截屏2023-03-30 下午5 39 38" src="https://user-images.githubusercontent.com/3608471/228796856-aae45ce4-dd79-49b7-a7c3-eda72f4f4a1f.png">

### Expected behavior

控制点坐标正常，连线绘制正常。

### Platform

- OS: macOS
- Browser: Chrome
- Version: 4.8.7

**Comment by Yanyan-Wang** [comment]
更新 @antv/layout 到 0.3.20，已经解决
