### ISSUE TITLE
Dagre 布局下，节点之间的连线被节点遮挡问题

### ISSUE THREAD

**Issue by caohonghai** [antvis/G6#4408]
### 问题描述

在自定义节点、采用 dagre 布局条件下，拖动节点时，执行的算法会在某些特定情况下寻找不了正确的路径。可以查看下面所录制的视频。

补充一个询问：
由于存在大量的节点，根据这篇文章所提到的优化方式 [从卡掉渣到满帧需要几步](https://g6.antv.antgroup.com/manual/faq/performance-opt#%E5%90%88%E7%90%86%E4%BD%BF%E7%94%A8%E6%8A%98%E7%BA%BF%E8%BE%B9-polyline)，因此我用了 [自定义边折线](https://g6.antv.antgroup.com/examples/item/customEdge/#customPolyline)，如何能够让自定义折线也不被节点遮挡。

### 重现链接

无

### 重现步骤

1. 自定义节点。
2. 采用 dagre 布局。
3. 拖动节点重合。

### 预期行为

能够找到合理的连线，连线不被节点遮挡。

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.2.0 ]

### 屏幕截图或视频（可选）

**默认折线被遮挡**

https://user-images.githubusercontent.com/43627226/228840261-eb42a08f-57a7-4490-8284-3bd8631b1cd9.mov

**自定义折线被遮挡**

https://user-images.githubusercontent.com/43627226/228839470-5eb2919a-0e43-4a91-baf9-3eb6eb11d61e.mov

### 补充说明（可选）

> 目前刚接触 G6 ，如是我操作问题所导致的，请指出，谢谢。

**Comment by Yanyan-Wang** [comment]
内置 polyline 修改配置 routeCfg.gridSize 和 offset 试试 https://g6.antv.antgroup.com/manual/middle/elements/edges/built-in/polyline#%E9%85%8D%E7%BD%AE%E9%A1%B9%E8%AF%B4%E6%98%8E
