### ISSUE TITLE
fruchterman布局在数量只有17个点到25个点的时候设置fitView:true布局会变的很离谱

### ISSUE THREAD

**Issue by jinfei-lab** [antvis/G6#4409]
### 问题描述

RT

### 重现链接

https://codesandbox.io/s/pedantic-lamport-qq99z5?file=/index.js

### 重现步骤

当数量为17个点到25个点的时候且设置fitView:true布局会发生问题

### 预期行为

期望布局大概可以一致，但是目前点的布局差距太大了

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.7.1]

### 屏幕截图或视频（可选）

数量为17个点到25个点的时候的布局
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/54229220/229045228-07d7fca2-a97e-4ebb-a867-54bf591a3bed.png">

上述点数量以外的布局
<img width="1486" alt="image" src="https://user-images.githubusercontent.com/54229220/229045482-97a75b8d-cf7e-458f-871a-bbf3646eaa75.png">

**Comment by Yanyan-Wang** [comment]
GPU 计算问题, 请 @xiaoiver 关注
