### ISSUE TITLE
[Plugin: Tooltip]: 当 Tooltip 高度稍微大点时，tooltip 会错位隐藏，不能完全展示！

### ISSUE THREAD

**Issue by hipi** [antvis/G6#4410]
### Describe the bug

codesandbox： https://codesandbox.io/s/jolly-ioana-5qiy7l

![image](https://user-images.githubusercontent.com/22478003/229044962-c6e2418f-4ebb-47cd-abd3-679bb3cd7790.png)
![image](https://user-images.githubusercontent.com/22478003/229045005-e93427a8-f501-4327-ac99-aee2f75efdbf.png)

### Your Example Website or App

https://codesandbox.io/s/jolly-ioana-5qiy7l

### Steps to Reproduce the Bug or Issue

1. tooltip 高度设值大一点时

### Expected behavior

预期：tooltip 能完整可见。

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by hipi** [comment]
应该是判断临界值问题，应当给个临界值，top 不能 小于 0

**Comment by hipi** [comment]
#4411 , 提了个 pr

**Comment by Yanyan-Wang** [comment]
感谢 PR，合并到 4.8.9 已发布
