### ISSUE TITLE
Node links are breaking when used custum node for dagre with combos

### ISSUE THREAD

**Issue by Rakesh678219** [antvis/G6#4412]
### Describe the bug

Sometimes the dagre links are breaking , when moved , It is occuring only with custom nodes 

### Your Example Website or App

no url

### Steps to Reproduce the Bug or Issue

Go to https://g6.antv.antgroup.com/en/examples/net/dagreFlow#dagreCombo

Create a custom node instead of default

### Expected behavior

Expected should be that the links should not break when dragging

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
Give me an online produced code pls? I did not found the problem on the demo
