### ISSUE TITLE
自定义布局中getDefaultCfg 不生效

### ISSUE THREAD

**Issue by SummerXIAhaha** [antvis/G6#4413]
### 问题描述

自定义布局中getDefaultCfg 不生效，execute中获取不到getDefaultCfg返回的数据

### 重现链接

https://stackblitz.com/edit/vue-oer8cb?file=src%2FApp.vue

### 重现步骤

自定义布局中getDefaultCfg 不生效，
将默认数据放在layout数据中才会生效，（放开layout属性中的注释部分页面正常展示）

### 预期行为

希望getDefaultCfg能够生效

### 平台

操作系统: [macOS]
网页浏览器: [Google Chrome]
G6 版本: [4.8.7 ]

**Comment by Yanyan-Wang** [comment]
升级一下 @antv/layout 即可
