### ISSUE TITLE
自定义拖动事件，只有一个节点时，拖动无反应

### ISSUE THREAD

**Issue by Tina75** [antvis/G6#4414]
### Describe the bug

自己写的拖动事件，然后只有一个节点时，节点就不能拖；大于一个时，就拖动正常

### Your Example Website or App

https://codesandbox.io/p/github/Tina75/graph-test/master?file=%2FREADME.md&workspace=%257B%2522activeFilepath%2522%253A%2522%252FREADME.md%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clf90chvp000x3n6snid14i6r%2522%253A%257B%2522key%2522%253A%2522clf90chvp000x3n6snid14i6r%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522key%2522%253A%2522clg4gaax3000x3n6ixle6sfg8%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522key%2522%253A%2522clg4g1hyx006c3n6ij1rscuva%2522%252C%2522isMinimized%2522%253Afalse%252C%2522path%2522%253A%2522%252F%2523%252Fg6demo%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522clg4g1gfp00343n6i7876lyjb%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clf90chvp000x3n6snid14i6r%2522%252C%2522spacesOrder%2522%253A%255B%2522clf90chvp000x3n6snid14i6r%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D

### Steps to Reproduce the Bug or Issue

1、选择g6Demo路由，拖动节点

### Expected behavior

该节点能够跟着鼠标正常拖动

### Platform

- OS:  Windows
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Tina75** [comment]
还有既然自己写的拖动，那么enableOptimize这个属性怎么加上呢，这个加上可以隐藏线，提升性能。

**Comment by Yanyan-Wang** [comment]
自己写的原因是内置的 drag-node 有什么不满足需求的吗？要自己实现 enableOptimize 挺麻烦的

**Comment by Yanyan-Wang** [comment]
这里没拖动的原因：
1. refreshDragNodePosition 里面没调用 API 更新节点位置，例如 graph.updateItem(nodeId, { x: e.x, y: e.y });
2. dragstart 发生在节点上，所以 node:dragstart 接收到了，但是鼠标比较快，拖的过程中鼠标超出节点范围，导致 drag 事件没有发生在节点上，node:drag 是不会被触发的，需要在 node:dragstart 的时候去记录正在被拖拽的元素，在 'drag' 事件里面去移动这些元素，'dragend' 的时候还要清空一下。自己写这些交互的话就是要维护比较多状态，可以参考内置 drag-node 的写法：https://github.com/antvis/G6/blob/master/packages/pc/src/behavior/drag-node.ts
3. 不要给一些非法的属性，比如你在 defaultNode 里面给了 fill 和 stroke 是空字符串。如果你想要 keyShape 看不见，可以给白色，或者给 opacity: 0 ，但是不要给这样非法的值

**Comment by Tina75** [comment]
> 自己写的原因是内置的 drag-node 有什么不满足需求的吗？要自己实现 enableOptimize 挺麻烦的

因为节点可以手动锁死，就不给他拖动

**Comment by Tina75** [comment]
> 自己写的原因是内置的 drag-node 有什么不满足需求的吗？要自己实现 enableOptimize 挺麻烦的

官网的例子，一个节点也是拖不动的，如果不自己写拖动事件，那f2布局时，拖动节点别的节点也不能跟着移动

**Comment by Yanyan-Wang** [comment]
> > 自己写的原因是内置的 drag-node 有什么不满足需求的吗？要自己实现 enableOptimize 挺麻烦的
> 
> 因为节点可以手动锁死，就不给他拖动

希望某系节点不响应 drag-node，可以给 drag-node 配置 shouldBegin，根据参数里面的元素 e.item 来 return true 或 false。文档：https://g6.antv.antgroup.com/manual/middle/states/default-behavior#drag-node

**Comment by danieljd** [comment]
@Yanyan-Wang 请问下如果是自定义的dom类型的node 是没办法drag-node吗
