### ISSUE TITLE
G6 combo+子图布局 鼠标

### ISSUE THREAD

**Issue by wanghaoying1995** [antvis/G6#4415]
### 问题描述

当鼠标滚轮放大的时候，如何获取到当前canvas内的节点及关系重新绘制，要达到的效果是：随着鼠标滚轮放大，页面随之重绘

### 重现链接

http://localhost:8009/#/neo4jTest

### 重现步骤

11 

### 预期行为

· 

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]Windows
- 网页浏览器: [Google Chrome, Safari, Firefox]Chrome
- G6 版本: [4.5.1 ... ]4.5.1

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/70082298/230311261-41ebad49-e066-4e15-bef5-2d48373a72ab.png)

**Comment by Yanyan-Wang** [comment]
获取所有节点 graph.getEdges() 获取所有边 graph.getEdges()

我理解滚轮缩放等级不同，图上数据要更新？如果是局部更新，就是每个节点/边 graph.updateItem
如果是整个数据的更新，就 graph.changeData
