### ISSUE TITLE
timeBar 在画布模式为树图TreeGraph类型时，会报错

### ISSUE THREAD

**Issue by yinglcs** [antvis/G6#4417]
### 问题描述

![image](https://user-images.githubusercontent.com/58580062/230576931-2233cc7b-d43e-4cbb-a313-bb589a7a4d51.png)

### 重现链接

https://g6.antv.vision/zh/examples/tool/timebar#timebar

### 重现步骤

![image](https://user-images.githubusercontent.com/58580062/230577016-796f7d93-8c4c-48b0-acc0-04ce550ab77a.png)

### 预期行为

正常渲染

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
TimeBar 暂不支持 TreeGraph，或许用 Graph + Dagre 布局替代树图？
