### ISSUE TITLE
sortByCombo不生效

### ISSUE THREAD

**Issue by V1nnnnnnn** [antvis/G6#4418]
### 问题描述

我使用了DagreLayout去给我的节点计算x,y的位置，想通过同层节点数据加入了comboId（值为数字number），希望控制他的排序问题，但是无法生效。

### 重现链接

暂无

### 重现步骤

`
import { DagreLayout } from '@antv/layout';

const dagreLayout = new DagreLayout({
  rankdir: 'LR',
  nodesep: 50, // 可选
  ranksep: 50,
  preventOverlap: true,
  sortByCombo: true,
});

const model = {
    nodes: nodes2.map((i) => {
      return {
        id: i.id,
        comboId: i?.data?.comboId,
      };
    }),
    edges,
  };

  const newModel = dagreLayout.layout(model);

`

### 预期行为

无法生效

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
id 需要为唯一的 string，还不行的话给个复现 demo 看看
