### ISSUE TITLE
紧凑树是否可以实现点击加载数据？

### ISSUE THREAD

**Issue by anshengme** [antvis/g6#442]
类似ECharts中的Tree：http://echarts.baidu.com/examples/editor.html?c=tree-basic

点击一个Item会加载这个Item下面的列表

**Comment by TomHuangCN** [comment]
1. 可以加载全量数据通过展开折叠显示：
```js
tree.update(node, {
  collapsed: true
});
```
2. 也可以部分加载
```js
tree.update(node, {
  children, // 子元素集合
});
```
