### ISSUE TITLE
dagre自适应布局，节点高度不一致时无法自动居中对齐

### ISSUE THREAD

**Issue by Kygo4** [antvis/G6#4420]
### 问题描述

![image](https://user-images.githubusercontent.com/18324510/230821348-46fecb0d-ea73-4108-b5cd-b605e932ac34.png)
如图，dagre布局，设置了fitView: true，当节点高度不一致时，无法完全居中对齐
相关代码如下：
![image](https://user-images.githubusercontent.com/18324510/230820912-1a2152f6-ae85-41d5-aced-97d90711e3aa.png)

### 重现链接

暂无

### 重现步骤

暂无

### 预期行为

希望可以自适应布局下可以完全居中对齐

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.5.1]

**Comment by Yanyan-Wang** [comment]
自定义节点的时候把节点自身坐标系的原点移动到其中心，比如节点宽高是 width height，则所有的图形的 x 都减去 width / 2，y 都减去 height / 2.
还是不行的话给个在线复现 demo 看看

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
