### ISSUE TITLE
调用registerBehavior自定义behavior的时候，直接使用drag，dragstart，dragend不触发

### ISSUE THREAD

**Issue by lavenderMF** [antvis/G6#4421]
### 问题描述

![image](https://user-images.githubusercontent.com/19815805/230880943-3a5fb4cf-df21-4cde-ac5b-0878681bc798.png)
调用registerBehavior自定义behavior的时候，直接使用drag，dragstart，dragend不触发，
同时发现官方文档https://g6.antv.antgroup.com/manual/middle/states/default-behavior#brush-select
缺少参数includeCombos
![image](https://user-images.githubusercontent.com/19815805/230881565-ab741d57-d3e1-4dbe-8c54-85840e32edc1.png)

### 重现链接

https://g6.antv.antgroup.com/zh/examples/interaction/customBehavior/#dragCanvasTwoFingers

### 重现步骤

https://g6.antv.antgroup.com/zh/examples/interaction/customBehavior/#dragCanvasTwoFingers
官方自定义交互直接getEvents添加dragstart

### 预期行为

drag，dragstart，dragend触发

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.8.7 ... ]

**Comment by lavenderMF** [comment]
重新尝试了下是可以触发的，应该是自身业务代码有问题
补充下官方文档
https://g6.antv.antgroup.com/manual/middle/states/default-behavior#brush-select
缺少了参数includeCombos

**Comment by Yanyan-Wang** [comment]
好的非常感谢
