### ISSUE TITLE
自定义节点updateItem 后 原样式未被覆盖

### ISSUE THREAD

**Issue by avrinfly** [antvis/G6#4422]
### 问题描述

调用自定义节点后，原有样式无法清除

![image](https://user-images.githubusercontent.com/30068005/231098629-5a2ca73e-2ad0-43fa-b02e-2fe55ff6b254.png)

我也有使用graph.freshenItem 也没生效

我理解如果没写update的话，会复用draw方法，所以不太理解是我哪个地方写的有问题，还请大佬指教

### 重现链接

无

### 重现步骤

见补充说明

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 补充说明（可选）

```
// 自定义节点
G6.registerNode('once-node', {
  labelPosition: 'top',
  draw: (cfg, group) => {
    const isCenter = !!cfg.isRoot;
    const color = '#80B1FF';
    const size = cfg.size || 40;
    const samllRadius = size / 2 * .75;
    const bigRadius = size / 2;
    const hlRadius = size / 2 * 1.5;
    const stroke = cfg.style ? cfg.style.stroke || color : color;
    const fill = cfg.style ? cfg.style.fill || color : color;
    const fz = cfg?.style?.fontSize || cfg?.labelCfg?.style?.fontSize;

    // big circle
    const keyShape = group.addShape('circle', {
      attrs: {
        x: 0,
        y: 0,
        r: bigRadius,
        fillOpacity: 0,
        stroke: stroke,
        lineWidth: size * 2 / 30
      },
      name: 'big-circle',
      className: 'big-circle'
    });

    // small circle
    group.addShape('circle', {
      attrs: {
        x: 0,
        y: 0,
        r: samllRadius,
        fill: fill
      },
      name: 'small-circle',
      className: 'small-circle'
    });

    // highlight circle
    group.addShape('circle', {
      attrs: {
        x: 0,
        y: 0,
        r: hlRadius,
        fillOpacity: isCenter ? .08 : 0,
        strokeOpacity: isCenter ? .2 : 0,
        // fill: 'rgba(255,255,255,.08)',
        // stroke: 'rgba(255,255,255,.2)',
        fill: '#FFF',
        stroke: '#FFF',
        lineWidth: size * 2 / 30
      },
      name: 'highlight-circle',
      className: 'highlight-circle'
    })

    const labelPosition = cfg?.labelCfg?.position || 'center';
    const labelStyle = getLableStyleByPosition(labelPosition, cfg);

    const label = group.addShape('text', {
      attrs: {
        x: 0, // 居中
        y: 0,
        textAlign: 'center',
        textBaseline: 'middle',
        text: cfg.label,
        fill: cfg?.labelCfg?.style?.color || '#fff',
        fontSize: fz,
        ...labelStyle
      },
      labelRelated: true,
      // must be assigned in G6 3.3 and later versions. it can be any value you want
      name: 'text-shape',
      className: 'text-shape'
    })

    // 返回 keyshape
    return keyShape;
  },
}, 'circle');

// 初始化
this.graph = new G6.Graph({
        container: 'container',
        width: width,
        height: height,
        autoPaint: true,
        defaultNode: {
          type: "once-node",
          labelCfg: {
            position: "bottom",
            style: {
              fill: '#FFF',
              fontSize: 14
            }
          }
        },
}）


// 更新的地方
this.graph.on('canvas:click', e => {
      const layoutType = this.graph.get('layout').type;
      console.log('layout after layout: ' + layoutType);
      let nodes = this.graph.getNodes();
      nodes.forEach(node => {
        console.log('after layout node: ', node);
        
        const nModel = node.getModel();
        nModel.labelCfg.position = 'top';
        this.graph.updateItem(node, nModel);
        this.graph.refreshItem(node)
      })
    })
```

**Comment by avrinfly** [comment]
> ### 问题描述
> 调用自定义节点后，原有样式无法清除
> 
> ![image](https://user-images.githubusercontent.com/30068005/231098629-5a2ca73e-2ad0-43fa-b02e-2fe55ff6b254.png)
> 
> 我也有使用graph.freshenItem 也没生效
> 
> 我理解如果没写update的话，会复用draw方法，所以不太理解是我哪个地方写的有问题，还请大佬指教
> 
> ### 重现链接
> 无
> 
> ### 重现步骤
> 见补充说明
> 
> ### 预期行为
> 无
> 
> ### 平台
> * 操作系统: [macOS, Windows, Linux, React Native ...]
> * 网页浏览器: [Google Chrome, Safari, Firefox]
> * G6 版本: [4.5.1 ... ]
> 
> ### 屏幕截图或视频（可选）
> _No response_
> 
> ### 补充说明（可选）
> ```
> // 自定义节点
> G6.registerNode('once-node', {
>   labelPosition: 'top',
>   draw: (cfg, group) => {
>     const isCenter = !!cfg.isRoot;
>     const color = '#80B1FF';
>     const size = cfg.size || 40;
>     const samllRadius = size / 2 * .75;
>     const bigRadius = size / 2;
>     const hlRadius = size / 2 * 1.5;
>     const stroke = cfg.style ? cfg.style.stroke || color : color;
>     const fill = cfg.style ? cfg.style.fill || color : color;
>     const fz = cfg?.style?.fontSize || cfg?.labelCfg?.style?.fontSize;
> 
>     // big circle
>     const keyShape = group.addShape('circle', {
>       attrs: {
>         x: 0,
>         y: 0,
>         r: bigRadius,
>         fillOpacity: 0,
>         stroke: stroke,
>         lineWidth: size * 2 / 30
>       },
>       name: 'big-circle',
>       className: 'big-circle'
>     });
> 
>     // small circle
>     group.addShape('circle', {
>       attrs: {
>         x: 0,
>         y: 0,
>         r: samllRadius,
>         fill: fill
>       },
>       name: 'small-circle',
>       className: 'small-circle'
>     });
> 
>     // highlight circle
>     group.addShape('circle', {
>       attrs: {
>         x: 0,
>         y: 0,
>         r: hlRadius,
>         fillOpacity: isCenter ? .08 : 0,
>         strokeOpacity: isCenter ? .2 : 0,
>         // fill: 'rgba(255,255,255,.08)',
>         // stroke: 'rgba(255,255,255,.2)',
>         fill: '#FFF',
>         stroke: '#FFF',
>         lineWidth: size * 2 / 30
>       },
>       name: 'highlight-circle',
>       className: 'highlight-circle'
>     })
> 
>     const labelPosition = cfg?.labelCfg?.position || 'center';
>     const labelStyle = getLableStyleByPosition(labelPosition, cfg);
> 
>     const label = group.addShape('text', {
>       attrs: {
>         x: 0, // 居中
>         y: 0,
>         textAlign: 'center',
>         textBaseline: 'middle',
>         text: cfg.label,
>         fill: cfg?.labelCfg?.style?.color || '#fff',
>         fontSize: fz,
>         ...labelStyle
>       },
>       labelRelated: true,
>       // must be assigned in G6 3.3 and later versions. it can be any value you want
>       name: 'text-shape',
>       className: 'text-shape'
>     })
> 
>     // 返回 keyshape
>     return keyShape;
>   },
> }, 'circle');
> 
> // 初始化
> this.graph = new G6.Graph({
>         container: 'container',
>         width: width,
>         height: height,
>         autoPaint: true,
>         defaultNode: {
>           type: "once-node",
>           labelCfg: {
>             position: "bottom",
>             style: {
>               fill: '#FFF',
>               fontSize: 14
>             }
>           }
>         },
> }）
> 
> 
> // 更新的地方
> this.graph.on('canvas:click', e => {
>       const layoutType = this.graph.get('layout').type;
>       console.log('layout after layout: ' + layoutType);
>       let nodes = this.graph.getNodes();
>       nodes.forEach(node => {
>         console.log('after layout node: ', node);
>         
>         const nModel = node.getModel();
>         nModel.labelCfg.position = 'top';
>         this.graph.updateItem(node, nModel);
>         this.graph.refreshItem(node)
>       })
>     })
> ```

解决了，在自定义节点里边重写update方法就好了

**Comment by MingTang-cn** [comment]
怎么重写的啊老哥~

**Comment by MingTang-cn** [comment]
> 怎么重写的啊老哥~
把update 设置为undefined 即可，`update: undefined,`；
原来是直接在update内部调用的draw，看来不好用，谁能解释下吗？update设置为undefined 不是也走的draw吗？设为undefined内部重新new的group（现在直接调应该是包含原来的shape）？
```
            update(cfg, item, updateType) {
                let group = item.getContainer();
                this.draw(cfg, group);
            },
```

**Comment by MingTang-cn** [comment]
> > 怎么重写的啊老哥~
> 
> 把update 设置为undefined 即可，`update: undefined,`； 原来是直接在update内部调用的draw，看来不好用，谁能解释下吗？update设置为undefined 不是也走的draw吗？设为undefined内部重新new的group（现在直接调应该是包含原来的shape）？
> 
> ```
>             update(cfg, item, updateType) {
>                 let group = item.getContainer();
>                 this.draw(cfg, group);
>             },
> ```

把默认的覆盖：
```
update:undefined,
```
