### ISSUE TITLE
请问, 能否实现多棵树的紧凑树

### ISSUE THREAD

**Issue by chaoranfeng** [antvis/G6#4425]
### 问题描述

目前存在多颗紧凑树, 想绘制在一张图上, 请问 g6 是否支持(看了您以往的 issue,  创建虚拟的 root, 连接多个树, 然后隐藏 root, 因为我的树图方向是 LR, 这种办法生成的多颗树, 是水平方向排列的,  需求想要多棵树从上到下排列,  所以这样就无法模拟实现 ), 请问官方是否计划支持多棵树?或者有没有什么实现的方法

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.8.8 ]

**Comment by Yanyan-Wang** [comment]
4.x 可能不会考虑实现这种森林，也许可以通过拆分到多个 tree graph 上来实现？

**Comment by Yanyan-Wang** [comment]
或者参考这种解法：https://github.com/antvis/G6/issues/4558#issuecomment-1575946623

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
