### ISSUE TITLE
请问darge布局能否实现每层设置最大高度

### ISSUE THREAD

**Issue by songxiaoyu321** [antvis/G6#4426]
### 问题描述

比如darge布局的某一层有300个节点，全部竖向展开高度太高，假设竖向高度最多有大约100个节点，如何设置让这一层的竖向排列在这个高度范围内呢（节点可以重叠一部分），darge可以实现吗？还是需要自定义布局

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

无

**Comment by Yanyan-Wang** [comment]
需要自定义布局，但在自定义布局中可以调用 @antv/layout 的 dagre 布局作为前置布局，然后在它的基础上做一些修改

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。

**Comment by swshuji** [comment]
> 需要自定义布局，但在自定义布局中可以调用 @antv/layout 的 dagre 布局作为前置布局，然后在它的基础上做一些修改

请问这个该如何使用?当前使用dagre布局,同层级节点数太多导致布局撑得很大,考虑使用自定义布局,但是又想要dagre的算法
