### ISSUE TITLE
请问如何修改边的text的样式？实现如下的展示效果

### ISSUE THREAD

**Issue by chenzilong0828** [antvis/G6#4427]
### 问题描述

![image](https://user-images.githubusercontent.com/41404880/231445726-8666a252-89d3-46cc-b5ce-43b6efbe3c93.png)

尝试了修改labelCfg里的style，但是在官方文档中，貌似找不到padding属性来实现这样的效果。
### 重现链接

无

### 重现步骤

无

### 预期行为

展示如图效果

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/41404880/231445917-59ef7da1-1980-4b22-9a59-7a578cd426af.png)

**Comment by Yanyan-Wang** [comment]
https://g6.antv.antgroup.com/examples/item/labelBg/#edgeBg

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
