### ISSUE TITLE
拖动节点，自定义边上的图片图形会闪烁

### ISSUE THREAD

**Issue by yinjialu** [antvis/G6#4428]
### Describe the bug

在自定义边上添加额外图形，使用图片图形，拖动节点的过程中，自定义边上的图片图形会闪烁

### Your Example Website or App

https://codesandbox.io/s/jee5f4

### Steps to Reproduce the Bug or Issue

1. 自定义边添加图形
2. 添加图片图形
3. 拖动节点，图片图形出现闪烁

### Expected behavior

图片不闪烁

### Screenshots or Videos

https://user-images.githubusercontent.com/37073056/231632082-f2823a88-f7db-45a9-a1b7-c0f6ff058852.mov

_No response_

### Platform

- OS: macOS
- Browser: Chrome
- Version: 112.0.5615.49

**Comment by leo1u777** [comment]
同样遇到了，请问解决了吗

**Comment by manmanhunhun** [comment]
请问解决了吗
