### ISSUE TITLE
有没有behaviour和mode的装载卸载的钩子函数

### ISSUE THREAD

**Issue by ALIEN96** [antvis/g6#443]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

场景如下：
需要实现类似g6-editor的功能，使用到自定义behaviour 和mode。
比如我自定义了一个叫edit的mode，要在退出edit模式时销毁一些辅助dom，例如销毁改变item大小的控制器，请问这个要怎么实现，我在文档中没有查到行为加载和卸载的生命周期钩子函数。

tks...

**Comment by TomHuangCN** [comment]
1. 暂时没有这个功能，也没遇到其它类似需求。
2. 我理解如果你是用 changeMode 切换模式的画，应该模式变更前后要做什么事情，你都能控制。
3. 如果是个强需求，可以再起一个 issue 详细描述一下场景和期望的 `事件名` 、 `回调事件对象` 和 `触发时机`。
