### ISSUE TITLE
一个节点的label样式咋自定义呢 比如G6 G是蓝色6是红色

### ISSUE THREAD

**Issue by HeHongWei666** [antvis/G6#4431]
### 问题描述

一个节点的label样式咋自定义呢 比如G6 G是蓝色6是红色

### 重现链接

一个节点的label样式咋自定义呢 比如G6 G是蓝色6是红色

### 重现步骤

一个节点的label样式咋自定义呢 比如G6 G是蓝色6是红色

### 预期行为

一个节点的label样式咋自定义呢 比如G6 G是蓝色6是红色

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
需要自定义节点，加两个文本

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
