### ISSUE TITLE
边按照优先级显示

### ISSUE THREAD

**Issue by justforliving** [antvis/G6#4432]
### 问题描述

想要边按照优先级显示

### 重现链接

https://codesandbox.io/s/naughty-lalande-9esxo4?file=/src/components/HelloWorld.vue

### 重现步骤

1、进入页面

### 预期行为

1、边按照优先级显示
2、悬浮的时候 将当前边置顶

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome]
- G6 版本: [2.3.10]

**Comment by Yanyan-Wang** [comment]
graph.on('edge:mouseenter', e => {
  e.item.toFront()
})

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
