### ISSUE TITLE
react自定义节点在流程图显示问题

### ISSUE THREAD

**Issue by Sharang-heng** [antvis/G6#4435]
### 问题描述

使用了react自定义组件，dagre布局与polyline，并设置了controlPoints，但是在只有一条流程的情况下还是显示了拐点以及不居中的情况，看了其他issue感觉需要设置x,y，但是我用的是react自定义组件不知道在怎么设置

### 重现链接

无

### 重现步骤

无

### 预期行为

居中显示且不显示拐点

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![issue](https://user-images.githubusercontent.com/69613396/231934829-f1f37440-2071-49d7-8c79-5120715f0a1f.png)

**Comment by Sharang-heng** [comment]
即使宽度一致仍然会有拐点
![Snipaste_2023-04-14_11-39-14](https://user-images.githubusercontent.com/69613396/231935663-b9ff3224-e78e-43ef-bce4-058f631cd7ae.png)

**Comment by Yanyan-Wang** [comment]
给个复现 demo？

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
