### ISSUE TITLE
浏览器通过document.body.style.zoom来进行页面自适应后，图表绘制完后鼠标的各种事件出现错位或偏移问题

### ISSUE THREAD

**Issue by SuyarAyoM** [antvis/G6#4436]
### 问题描述

问题原因：使用谷歌浏览器，将页面缩放显示放大超过100%，然后使用web页面的高宽进行计算得到市面上现在正常的分辨率（1920*1080）缩放比，通过document.body.style.zoom设置后，再进行图形绘制出现鼠标的各种事件出现错位或偏移问题。
以下是设置分辨率代码：
        const {offsetWidth, offsetHeight} = document.body;
        const scale = offsetWidth / 1920
        if(scale < 1){
            document.body.style.zoom = scale;
            document.body.style['transform-origin'] = `0 0`;
            document.body.style.height = (offsetHeight / scale)+'px';
        }
目前通过测试发现360浏览器，火狐浏览器没有问题，谷歌浏览器出现偏移问题

### 重现链接

-

### 重现步骤

-

### 预期行为

-

### 平台

-操作系统: Windows
- 网页浏览器: [Google Chrome]
- G6 版本: [4.2.4]

**Comment by Yanyan-Wang** [comment]
啊？为什么要这么做？这样改变长宽比的话页面上的东西不会变扁了吗？
如果你只是想让 graph 适配视口区域，可以使用 graph.fitView()，在布局完成后调用

**Comment by SuyarAyoM** [comment]
是想着页面不管在什么情况都能够适应1920*1080分辨率，页面不会变形，使用fitView一样会存在偏差，这种感觉不是视口区域的问题

**Comment by Yanyan-Wang** [comment]
> 是想着页面不管在什么情况都能够适应1920*1080分辨率，页面不会变形，使用fitView一样会存在偏差，这种感觉不是视口区域的问题

偏差是指什么？

**Comment by wakakakk** [comment]
你的问题解决了吗？我遇到的问题跟你一样

**Comment by Yanyan-Wang** [comment]
能给我一个在线复现 demo 不

**Comment by wakakakk** [comment]
https://codesandbox.io/s/currying-glitter-yd6lp6?file=/public/index.html

**Comment by wakakakk** [comment]
![image](https://github.com/antvis/G6/assets/66005999/42630b6a-276f-4cf0-89f1-c23a860af9b5)
如果任意父元素设置了zoom的话，节点就点击不了

**Comment by SuyarAyoM** [comment]
> 你的问题解决了吗？我遇到的问题跟你一样

没有，试过了各种办法都没解决，最后去掉了使用zoom

**Comment by Yanyan-Wang** [comment]
嗯嗯我理解这个需求应该可以通过默认的 zoom 来解决？就在 graph.render 后调用 graph.zoom(0.7)
