### ISSUE TITLE
当使用了G6.Util.processParallelEdges 时是否无法使用‘边自定义’功能了

### ISSUE THREAD

**Issue by yoZerY** [antvis/G6#4437]
### 问题描述

发现使用了G6.Util.processParallelEdges 时是不会进入自定义边的draw函数

### 重现链接

录有视频

### 重现步骤

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2023.04.14-21_45_42.webm](https://user-images.githubusercontent.com/45114578/232061056-a70cf497-349e-4423-a3ab-3df80ccd0b86.webm)

### 预期行为

使用G6.Util.processParallelEdges  后怎么才能进行 边自定义

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

[Uploading screencast-bpconcjcammlapcogcnnelfmaeghhagj-2023.04.14-21_45_42.webm…]()

**Comment by Martin2037** [comment]
同问

**Comment by opensourcex123** [comment]
同问

**Comment by Yanyan-Wang** [comment]
默认情况下 processParallelEdges 会把边处理成 quadratic，可以配置第三个参数为你的自定义边类型，processParallelEdges 的参数和默认值如下
processParallelEdges(
  edges, // 传入的边数据
  offsetDiff = 15, // 平行边之间的控制点间距
  multiEdgeType: string = 'quadratic', // 存在平行边时使用的边类型
  singleEdgeType: string = undefined, // 不存在平行边时使用的边类型
  loopEdgeType: string = undefined // 自环边类型
)

但这个方法本质上是在配置边上的 curveOffset 属性，如果你的自定义边是完全自己写的，没有用到这个属性的话，processParallelEdges 对你来说就是无效的

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
