### ISSUE TITLE
combo的布局有考虑实现圆堆图吗？？

### ISSUE THREAD

**Issue by AmandaKitten** [antvis/G6#4438]
### 问题描述

目前的combo相关布局都没办法很好的解决嵌套combo之间的覆盖问题，请问是否能考虑引入圆堆图算法呢？这个很好的解决的combo之间的覆盖问题，只需要类似comboCombied布局一样分开设置node的内层布局方式即可

### 重现链接

https://zhuanlan.zhihu.com/p/65200118

### 重现步骤

<img width="690" alt="image" src="https://user-images.githubusercontent.com/18146419/232320718-fa97327e-4f7f-48e8-ba28-151df0de0257.png">

### 预期行为

圆堆图实现

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
暂不支持，非常欢迎社区小伙伴共建～
