### ISSUE TITLE
dagre 布局如何实现图中节点位置

### ISSUE THREAD

**Issue by minikinl** [antvis/G6#4440]
### 问题描述

[官网例子](https://antv-g6.gitee.io/zh/examples/net/dagreFlow#lrDagreUL)修改节点数据如下：

```js
const data = {
  nodes: [
    { id: "1", label: "1" },
    { id: "2", label: "2" },
    { id: "3", label: "3" },
    { id: "4", label: "4" },
    { id: "5", label: "5" },
  ],
  edges: [
    { source: "1", target: "2" },
    { source: "2", target: "3" },
    { source: "1", target: "4" },
    { source: "4", target: "5" },
    { source: "3", target: "5" },
  ],
};

```

得到的默认节点位置是：
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/11417330/232455445-3918c451-8b60-4a46-a86f-a177915189d3.png">

但实际希望的效果是：
<img width="724" alt="image" src="https://user-images.githubusercontent.com/11417330/232455650-ee36a35e-318c-496f-aa4a-d60cba914c13.png">

### 重现链接

https://antv-g6.gitee.io/zh/examples/net/dagreFlow#lrDagreUL

### 重现步骤

1. 进入[页面](https://antv-g6.gitee.io/zh/examples/net/dagreFlow#lrDagreUL)
2. 修改节点数据如上

### 预期行为

希望节点【2】和【4】在同一水平位置上，理由是两个节点都是【1】的直接子节点，属于同一 rank。

若要实现此效果，应如何调整参数呢？

谢谢～

### 平台

- 操作系统: macOS
- 网页浏览器: Google Chrome
- G6 版本: 4.3.2

### 补充说明（可选）

其实效果更接近「紧凑树」，但因为树布局不能单独使用，因此考虑 dagre 布局算法。

使用[https://github.com/dagrejs/dagre](https://github.com/dagrejs/dagre)布局也会遇到这个问题。

**Comment by minikinl** [comment]
谢谢～

**Comment by minikinl** [comment]
@Yanyan-Wang 

请问同时使用 layer 和 nodeOrder 时布局未按预期显示怎么处理呢？

**case 1: 无 layer ，无 nodeOrder:**

<img width="1103" alt="image" src="https://user-images.githubusercontent.com/11417330/236096276-07b346c4-0dbe-4598-8371-381c4b8eabff.png">


**case 2: 添加 layer 选项后：**
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/11417330/236096169-a9fee6e5-f5c9-43cb-adda-f6d73d3bd425.png">

**case 3: 同时使用 layer + nodeOrder:**
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/11417330/236096365-7fd57784-4151-473c-8a0b-d4e95ad63987.png">

**预期行为（手动拖拽节点后实现的效果）：**
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/11417330/236096573-5923c25c-05a7-465c-8592-347cc527728b.png">




在[官网例子](https://g6.antv.antgroup.com/examples/net/dagreFlow/#basicDagre)中使用如下代码：

```ts
import G6 from '@antv/g6';

const container = document.getElementById('container');
const width = container.scrollWidth;
const height = container.scrollHeight || 500;
const graph = new G6.Graph({
  container: 'container',
  width,
  height,
  layout: {
    type: 'dagre',
    ranksep: 70,
    controlPoints: true,
    noderOrder: ["1", "2", "3", "4"],
  },
  modes: {
    default: [
      'drag-canvas',
      'drag-node',
      'zoom-canvas',
      'click-select',
    ],
  },
  fitView: true,
});
graph.data({
  nodes: [
    {
      id: "1",
      label: "1",
      // layer: 1,
    },
    {
      id: "2",
      label: "2",
      // layer: 1,
    },
    {
      id: "3",
      label: "3",
      // layer: 2,
    },
    {
      id: "4",
      label: "4",
      // layer: 3,
    },
  ],
  edges: [
    {
      source: "1",
      target: "4",
    },
    {
      source: "2",
      target: "3",
    },
    {
      source: "3",
      target: "4",
    },
  ],
});
graph.render();

if (typeof window !== 'undefined')
  window.onresize = () => {
    if (!graph || graph.get('destroyed')) return;
    if (!container || !container.scrollWidth || !container.scrollHeight) return;
    graph.changeSize(container.scrollWidth, container.scrollHeight);
  };
```

**Comment by Yanyan-Wang** [comment]
这个问题应该修复过，官网暂时还没有安装最新版本，你可以在其他在线代码沙箱比如 codesandbox 或者本地试试，确定安装的 @antv/layout 版本是 0.3.20 及以上

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
