### ISSUE TITLE
关于设置Combo的相对位置

### ISSUE THREAD

**Issue by homo-du** [antvis/G6#4442]
### 问题描述

希望实现基于Combo的“书架式”布局，即所有Combo宽度一致（比如都是画布宽度的100%），垂直对齐且互不重叠。

问题：
设置了所有Combo的宽度一致之后，应该是由于节点的布局，导致Combo之间也不能对齐。且设置Combo的x=0也不生效

### 重现链接

https://stackblitz.com/edit/react-qr3gj9?file=index.js

### 重现步骤

1. 在官方“带有 Combo 的流程图”修改各节点所属combo，并使节点8、11不属于任何combo
2. 渲染后如下尝试修改位置
```
graph.getCombos().forEach((combo) => {
    // 获取 Combo 中包含的节点和边的范围
    const bbox = combo.getBBox();

    // 计算 Combo 的高度
    const h = bbox.maxY - bbox.minY;

    // 设置 Combo 的大小
    combo.update({
      size: [600, h],
      x: 0,
    });
});
```

### 预期行为

- 预期
![image](https://user-images.githubusercontent.com/77880051/232647297-d4b00cf6-24ed-4787-ae0e-9cc580d99780.png)
三个Combo完全对齐，最好是combo之间没有缝隙完全贴合。而节点8、11则在任意合理位置

- 实际
![image](https://user-images.githubusercontent.com/77880051/232646767-215cc448-1604-4429-9c44-75025e057bd2.png)

### 平台

- 操作系统: Windows10
- 网页浏览器: Google Chrome
- G6 版本:4.8.7

### 补充说明（可选）
尝试过ComboCombined布局，但是由于有不属于任何combo节点，不能实现我的需求。

**Comment by Yanyan-Wang** [comment]
1. 在 afterlayout 中更新 combo 位置，保证对 combo 位置的更新在布局完成（节点位置更新）之后
2. 使用 graph 的 API 来更新元素，而不是 combo、node、edge 自己的 API，这样可以保证 graph 能统筹管理一个元素及其相关的其他元素。在这个例子中就是使用 graph.updateItem 替代 combo.update

修改后的 demo：
https://stackblitz.com/edit/react-qr3gj9-se2uxu?file=index.js

**Comment by homo-du** [comment]
> 1. 在 afterlayout 中更新 combo 位置，保证对 combo 位置的更新在布局完成（节点位置更新）之后
> 2. 使用 graph 的 API 来更新元素，而不是 combo、node、edge 自己的 API，这样可以保证 graph 能统筹管理一个元素及其相关的其他元素。在这个例子中就是使用 graph.updateItem 替代 combo.update
> 
> 修改后的 demo： https://stackblitz.com/edit/react-qr3gj9-se2uxu?file=index.js

如何实现combo不重叠呢，尝试在layout配置preventOverlap和sortByCombo，都没有效果
```js
  layout: {
    type: 'dagre',
    sortByCombo: false,
    ranksep: 10,
    nodesep: 10,
    preventOverlap: true,
    sortByCombo: true,
  },
```

![image](https://github.com/antvis/G6/assets/77880051/e447640e-7bf2-4887-af0f-4a448fe531ae)

**Comment by Yanyan-Wang** [comment]
> > 1. 在 afterlayout 中更新 combo 位置，保证对 combo 位置的更新在布局完成（节点位置更新）之后
> > 2. 使用 graph 的 API 来更新元素，而不是 combo、node、edge 自己的 API，这样可以保证 graph 能统筹管理一个元素及其相关的其他元素。在这个例子中就是使用 graph.updateItem 替代 combo.update
> > 
> > 修改后的 demo： https://stackblitz.com/edit/react-qr3gj9-se2uxu?file=index.js
> 
> 如何实现combo不重叠呢，尝试在layout配置preventOverlap和sortByCombo，都没有效果
> 
> ```js
>   layout: {
>     type: 'dagre',
>     sortByCombo: false,
>     ranksep: 10,
>     nodesep: 10,
>     preventOverlap: true,
>     sortByCombo: true,
>   },
> ```
> 
> ![image](https://user-images.githubusercontent.com/77880051/237557326-e447640e-7bf2-4887-af0f-4a448fe531ae.png)

这里是不同层之间的 combo 重叠，需要把层高设置大一下，ranksep 或者 ranksepFunc，文档：https://g6.antv.antgroup.com/api/graph-layout/dagre#layoutcfgranksep

**Comment by homo-du** [comment]
> > > 1. 在 afterlayout 中更新 combo 位置，保证对 combo 位置的更新在布局完成（节点位置更新）之后
> > > 2. 使用 graph 的 API 来更新元素，而不是 combo、node、edge 自己的 API，这样可以保证 graph 能统筹管理一个元素及其相关的其他元素。在这个例子中就是使用 graph.updateItem 替代 combo.update
> > > 
> > > 修改后的 demo： https://stackblitz.com/edit/react-qr3gj9-se2uxu?file=index.js
> > 
> > 
> > 如何实现combo不重叠呢，尝试在layout配置preventOverlap和sortByCombo，都没有效果
> > ```js
> >   layout: {
> >     type: 'dagre',
> >     sortByCombo: false,
> >     ranksep: 10,
> >     nodesep: 10,
> >     preventOverlap: true,
> >     sortByCombo: true,
> >   },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://user-images.githubusercontent.com/77880051/237557326-e447640e-7bf2-4887-af0f-4a448fe531ae.png)
> 
> 这里是不同层之间的 combo 重叠，需要把层高设置大一下，ranksep 或者 ranksepFunc，文档：https://g6.antv.antgroup.com/api/graph-layout/dagre#layoutcfgranksep

感谢，问题解决了

**Comment by brian95827** [comment]
问下新版本v5咋设置呢 @Yanyan-Wang
