### ISSUE TITLE
node:mouseleave 无法触发

### ISSUE THREAD

**Issue by zznba** [antvis/G6#4444]
### Describe the bug

node:mouseleave事件无法正常触发

### Your Example Website or App

https://codesandbox.io/p/sandbox/sad-hoover-8n0fw6?file=%2Fsrc%2FApp.vue

### Steps to Reproduce the Bug or Issue

1、鼠标进入节点上可以正常触发node:mouseenter
2、鼠标离开节点时node:mouseleave事件不生效

### Expected behavior

鼠标离开节点时node:mouseleave事件正常触发

### Platform

- OS: macOS13.2.1
- Browser: Microsoft Edge
- Version: 112.0.1722.39 (Official build) (arm64)

**Comment by avrinfly** [comment]
我也遇到类似的问题了，请教一下，你是怎么解决的

**Comment by zznba** [comment]
> 我也遇到类似的问题了，请教一下，你是怎么解决的

[https://codesandbox.io/p/sandbox/sad-hoover-8n0fw6?file=%2Fsrc%2FApp.vue%3A58%2C13-58%2C28](https://codesandbox.io/p/sandbox/sad-hoover-8n0fw6?file=%2Fsrc%2FApp.vue%3A58%2C13-58%2C28)

**Comment by joohs** [comment]
vue2使用shallowRef来解决
