### ISSUE TITLE
在beforerender和afterrender之间加loading状态无效

### ISSUE THREAD

**Issue by liutao1992** [antvis/G6#4445]
### 问题描述

我在beforerender和afterrender之间加了loading状态值。在渲染期间，加入loading提示框。如果布局使用的是force，则该提示框可以出来，若布局是其他的，该提示框则不会出来。排查了好久，一直找不到问题原因。希望作者指点一二，谢谢。

### 重现链接

https://codesandbox.io/p/sandbox/tender-lamarr-vkj23g?file=%2Fsrc%2Fcomponents%2FgraphContainer.vue&selection=%5B%7B%22endColumn%22%3A11%2C%22endLineNumber%22%3A5%2C%22startColumn%22%3A11%2C%22startLineNumber%22%3A5%7D%5D

### 重现步骤

修改布局为辐射布局，或者其他，loading提示框不会显示。

### 预期行为

不管任何布局，凡是一旦渲染，loading状态变化后，loading提示框都会有对应的变化。

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.7.14]

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
