### ISSUE TITLE
自定义节点自环边

### ISSUE THREAD

**Issue by 2691018635** [antvis/G6#4446]
### 问题描述

我在使用自定义节点是发现将边的type设置为loop后图像消失了，我该如何实现自定义节点的自环边呢

### 重现链接

无

### 重现步骤

无

### 预期行为

我希望能够提供一个可行的解决方法

### 平台

- 操作系统:Windows
- 网页浏览器: Google Chrome
- G6 版本: 4.5.1

**Comment by Yanyan-Wang** [comment]
是不是把非自环的边也设置成 type: 'loop' 了？判断一下 source === target 的时候再设置

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
