### ISSUE TITLE
Disable timebar slice resize abilites

### ISSUE THREAD

**Issue by bsansone** [antvis/G6#4447]
### Describe the bug

Unable to disable resizing of TimeBarSlice

### Your Example Website or App

N/A

### Steps to Reproduce the Bug or Issue

N/A

### Expected behavior

We want to use the TimeBar but dont want the user to be able to resize the TimeBarSlice, the slice should be a static size. Is there a way to do this? Thank you.

### Platform

- OS: Ubuntu 22.04.2 LTS x86_64
- Browser: Chrome 111.0.5563.64 (Official Build) (64-bit) 
- Version: @antv/g6 4.8.9

**Comment by Yanyan-Wang** [comment]
Did not support yet. Maybe someone from community could contribute to it?  😃
