### ISSUE TITLE
hull中的节点怎么样才能展示tooltip

### ISSUE THREAD

**Issue by tianxiumei** [antvis/G6#4448]
### 问题描述

在聚类里面的一些节点无法展示tooltip

### 重现链接

无

### 重现步骤

<img width="599" alt="image" src="https://user-images.githubusercontent.com/38803966/233324310-2e1bbeed-78d3-4f63-88f0-8a63df03973c.png">
这个节点可以展示描述信息

### 预期行为

希望在聚类里面的一些节点可以展示tooltip

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
