### ISSUE TITLE
image节点设置fill，会覆盖父容器shape

### ISSUE THREAD

**Issue by ChenKun1997** [antvis/G6#4451]
### Describe the bug

image节点设置fill，会覆盖父容器shape样式

### Your Example Website or App

https://g6.antv.antgroup.com/examples/tree/customItemTree#customEdgeTree

### Steps to Reproduce the Bug or Issue

1. 在146行 `group.addShape('image', {` 下面的attrs里面加上fill: 'red',效果如图：
![image](https://user-images.githubusercontent.com/24249578/233603421-8029846d-541e-476a-b4e9-35f96062b404.png)

### Expected behavior

希望如果image节点设置了fill属性，G6内部可以把fill属性omit掉

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/24249578/233603760-6d7ee765-ac61-4bea-826a-9bdb20d02d23.png)

![image](https://user-images.githubusercontent.com/24249578/233603823-f9dfa89a-b517-4b27-a5e4-177b6ddfb430.png)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by ChenKun1997** [comment]
> 给 image 配置 fill 和 fillOpacity 可以有一个颜色蒙层的效果，还是有点用的，应该不会忽略掉这个样式

加蒙层可以理解，但是范围太大了，这个蒙层得大小不是image节点得大小，而是它容器shape的大小，这有点不合理吧

**Comment by Yanyan-Wang** [comment]
> > 给 image 配置 fill 和 fillOpacity 可以有一个颜色蒙层的效果，还是有点用的，应该不会忽略掉这个样式
> 
> 加蒙层可以理解，但是范围太大了，这个蒙层的大小不是image节点得大小，而是它容器shape的大小，这有点不合理吧

应该就是图片大小吧？

**Comment by ChenKun1997** [comment]
> > > 给 image 配置 fill 和 fillOpacity 可以有一个颜色蒙层的效果，还是有点用的，应该不会忽略掉这个样式
> > 
> > 
> > 加蒙层可以理解，但是范围太大了，这个蒙层的大小不是image节点得大小，而是它容器shape的大小，这有点不合理吧
> 
> 应该就是图片大小吧？

不是的，你看我给的官网的例子，图片很小，image shape给了fill属性的话，会填充image shape的容器shape，也就是下图中的rect shape
![image](https://user-images.githubusercontent.com/24249578/236611326-74838060-0b45-42af-bfeb-1381d018daab.png)

**Comment by Yanyan-Wang** [comment]
发现确实是有这个问题……
