### ISSUE TITLE
将近500个combos渲染卡顿问题

### ISSUE THREAD

**Issue by mugo1993-ss** [antvis/G6#4455]
### 问题描述

1.7000个节点，9000多条边，500个combo渲染很慢，并且渲染完成后，操作非常卡顿，除了节点有连线，combo之间也有连线
![image](https://user-images.githubusercontent.com/73928245/233823066-e7cf3e39-d2fe-4507-85be-4edea5f90284.png)

### 重现链接

无

### 重现步骤

1.进入页面，渲染时间长

### 预期行为

希望能支持大数据渲染

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
combo 多确实很消耗性能，因为有很多层级关系需要计算，可以给个例子我看下怎么优化。
这里有一些优化思路：https://g6.antv.antgroup.com/manual/faq/performance-opt
