### ISSUE TITLE
gForce模式下动态使用changeData动态增加节点，节点会从外飞进来

### ISSUE THREAD

**Issue by MorningStarHu** [antvis/G6#4456]
### 问题描述

我现在想在gForce模式下动态增加节点。
但是使用changeData动态增加节点，节点会从外飞进来。请问是我的使用方法不对吗？

### 重现链接

无

### 重现步骤
拖动一下节点，然后再点击节点任意节点，
在线链接。https://codesandbox.io/s/vigilant-hopper-pewg68?file=/index.js

### 预期行为

期望新增的节点能直接添加在有边关联的节点附近

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by MorningStarHu** [comment]
在线链接。https://codesandbox.io/s/vigilant-hopper-pewg68?file=/index.js

**Comment by Yanyan-Wang** [comment]
你可以给新节点一个初始的 x y，等于已存在的相关节点的 x y 加一点 random

https://codesandbox.io/s/distracted-mclaren-16b7jq?file=/index.js
