### ISSUE TITLE
Dagre流程图布局中调用addItems导致两个流程位置调换

### ISSUE THREAD

**Issue by li1615882553** [antvis/G6#4458]
### 问题描述

Dagre流程图维护了两个流程，通过点击节点，会新增后续流程节点，但是某种特殊情况下，会导致两个流程上下位置调换，请问怎么保持两个流程上下位置关系？

### 重现链接

https://codesandbox.io/p/sandbox/goofy-tesla-f414ys?file=%2Fsrc%2FApp.vue&selection=%5B%7B%22endColumn%22%3A19%2C%22endLineNumber%22%3A57%2C%22startColumn%22%3A14%2C%22startLineNumber%22%3A57%7D%5D

### 重现步骤

点点击rect2，后点击rect1，然后再点击node6节点，这样两个流程上下位置会发生调换

### 预期行为

两个流程上下位置不发生调换

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.8.5]

**Comment by li1615882553** [comment]
每次布局的时候更新下preset就可以了

**Comment by hzy1735** [comment]
能详细说一下如何更新preset，或者提供一下文档链接么，没找到对应的内容
