### ISSUE TITLE
离散节点，一个节点去碰另外的节点，节点会整体往下掉

### ISSUE THREAD

**Issue by Tina75** [antvis/G6#4459]
### Describe the bug

1、选择g6demo这个路由
2、离散节点，一个节点去碰另外的节点，节点会整体往下掉，而且经常复现

### Your Example Website or App

https://codesandbox.io/p/github/Tina75/graph-test/master?workspaceId=03db8cd6-1640-4908-a79c-36d13e69e577

### Steps to Reproduce the Bug or Issue

1、节点移动碰到第二个节点，两个节点都会往下掉

### Expected behavior

我希望两个节点不要往下掉，这样用户看了很费解

### Screenshots or Videos

https://user-images.githubusercontent.com/26056312/233891210-81d310a9-9dc1-4f00-b9a4-4c23308c1452.mp4

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Tina75** [comment]
https://codesandbox.io/p/github/Tina75/graph-test/master?layout=%257B%2522activeFilepath%2522%253Anull%252C%2522openFiles%2522%253A%255B%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522fullScreenDevtools%2522%253Afalse%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522vertical%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522DEVTOOLS_PANELS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clgu6hlfo000a3n6j1prbhdv9%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clgu6hlfo000a3n6j1prbhdv9%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clgu6hlfo00083n6j9usz0cf1%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522id%2522%253A%2522clgu6hlfo00093n6jxjnqtw1s%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clgu6hlfo000a3n6j1prbhdv9%2522%252C%2522activeTabId%2522%253A%2522clgu6hlfo00083n6j9usz0cf1%2522%257D%257D%252C%2522showSidebar%2522%253Atrue%252C%2522showDevtools%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%252C%2522editorPanelSize%2522%253A50%252C%2522devtoolsPanelSize%2522%253A35%257D

**Comment by Tina75** [comment]
看评论链接

**Comment by Yanyan-Wang** [comment]
可以把布局的 gravity 关掉，gravity: 0

**Comment by Tina75** [comment]
关掉了，还是存在这个现象，怎么半，拖动就会往下掉

**Comment by Yanyan-Wang** [comment]
目前看这个 demo 应该是正常的，因为要防止重叠，所以一个节点靠近的时候，另外一个节点会弹开。如果你不希望拖拽一个节点的时候其他节点动，那就不要在拖拽监听里面重启布局

![image](https://github.com/antvis/G6/assets/29593318/424bc1fb-6fc5-486b-9e98-4a20275f13d2)
