### ISSUE TITLE
G6 会发送出一个未知的 GET 请求!!!

### ISSUE THREAD

**Issue by glud123** [antvis/g6#446]
* **G6 Version**:1.2.8
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

Network 中会出现如下 GET 请求

`
http://127.0.0.1:3003/?BIProfile=merge&d=%5B%7B%22pg%22%3A%22http%3A%2F%2F127.0.0.1%3A3003%2F%23%2F%22%2C%22r%22%3A1535963170442%2C%22g6%22%3Atrue%2C%22version%22%3A%221.2.8%22%2C%22page_type%22%3A%22syslog%22%7D%5D
`

具体请求参数如下

```
BIProfile: merge
d：[{"pg":"http://127.0.0.1:3003/#/","r":1535963170442,"g6":true,"version":"1.2.8","page_type":"syslog"}]
```

能说明下这个GET 请求的目的么？
通过怎样的配置或者怎样修改可以去掉这个 GET 请求？

**Comment by TomHuangCN** [comment]
https://www.yuque.com/antv/g6/quick-start#_%E4%BD%93%E9%AA%8C%E6%94%B9%E8%BF%9B%E8%AE%A1%E5%88%92%E8%AF%B4%E6%98%8E
