### ISSUE TITLE
如何确定两个节点之间是存在多条边的？

### ISSUE THREAD

**Issue by auuunya** [antvis/G6#4460]
### 问题描述

目前的开发中遇到一个棘手的问题，在自定义边的时候会出现两个节点之间出现两条或以上的边，所以我想要获取到某个节点到另一个节点他两之间是否连接了多条边，如果有就修改边的样式，现在在文档中找了一下，好像没有找到这个方法，只有item.getEdges()这个api又是获取所有边的。

### 重现链接

rt

### 重现步骤

rt

### 预期行为

rt

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
起点 item.getEdges() 终点 item.getEdges()  二者取交集
