### ISSUE TITLE
gForce布局下拖动节点后想通过其他事件固定节点，节点会偏移

### ISSUE THREAD

**Issue by MorningStarHu** [antvis/G6#4461]
### Describe the bug

官网的demo 在gForce布局下拖动节点后固定没有问题，但是想通过其他事件固定节点，节点会产生偏移，我在想使用的鼠标右键点击固定，

### Your Example Website or App

https://codesandbox.io/s/649wns?file=/index.js

### Steps to Reproduce the Bug or Issue

1、使用官方demo https://g6.antv.antgroup.com/zh/examples/net/forceDirected#gForceFix
2、原先的refreshDragedNodePosition函数改为
`refreshDragedNodePosition(e) {
  const model = e.item.get('model');
  model.x = e.x;
  model.y = e.y;
}`
为了方便查看 我把nodeStrength改为了800，nodesize：40
2、在原有的代码上添加右键点击固定的逻辑
`graph.on('node:contextmenu', function (e) {
      const model = e.item.get('model');
        model.fx = e.x;
        model.fy = e.y;
      graph.layout()
    });`
    

### Expected behavior

右键点击后节点固定不偏移

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by MorningStarHu** [comment]
@Yanyan-Wang 求大佬指教

**Comment by Yanyan-Wang** [comment]
如果你说的是，固定节点之后，其他操作导致原先被固定的节点开始移动，那么需要把 gForce 的动画配置开启
layout: {
  type: 'gForce',
  animate: true,
 // ...其他配置
}
或者你希望首次渲染没有布局动画，那上面的 animate 不要开启，而是在第一次拖拽的时候把布局更新为带动画的
graph.updateLayout({ animate: true })


如果你说的是右键点击节点的时候，当前节点被固定在有一些偏移的位置上，那么是因为鼠标右键的位置不在这个节点的圆心，也就是说事件的 e.x e.y 不等于当前这个节点的坐标，而更新节点位置到 e.x e.y 就会让节点从原先的位置移动到 e.x e.y 上。如果你想要解除这个微小的移动影响，你可以直接设置 model.fx = model.x; model.fy = model.y; 也就是让节点固定在当前自己的位置上。
