### ISSUE TITLE
自定义图形在放大情况下拖动节点，画布有残影

### ISSUE THREAD

**Issue by xtito** [antvis/G6#4462]
### Describe the bug

在使用G6-4.8.6版本过程中，自定义图片节点在放大的情况下，拖动节点时，label文字会留下残影

### Your Example Website or App

https://stackblitz.com/edit/js-g1m2pu?file=index.js

### Steps to Reproduce the Bug or Issue

**说明：目前不仅是自定义节点有该问题，内置节点在拖动时偶尔也有残影，尤其是矩形节点**

复现步骤：
1、自定义图片节点；
2、定义节点数据；
3、实例化G6，G6 配置参数设置 maxZoom 为 3；
4、放大画布，放至最大
5、拖动节点，尤其是向上拖动节点最为明显。

demo示例详情见：https://stackblitz.com/edit/js-g1m2pu?file=index.js

![image](https://user-images.githubusercontent.com/8833358/233956398-98bdd157-cbc9-41ad-8ff5-04e3872771b4.png)

### Expected behavior

画布节点正常渲染，且在拖动节点时没有残影

### Screenshots or Videos

![1682328355002](https://user-images.githubusercontent.com/8833358/233956991-d43d8616-6f30-4f73-96d7-98aaa8feecaf.jpg)

### Platform

- OS: macOS
- Browser: Chrome 103.0.5060.134 版本
- Version: G6 4.8.6

**Comment by zhuhengtan** [comment]
https://g6.antv.antgroup.com/manual/faq/faq#%E6%B8%B2%E6%9F%93%E6%AE%8B%E5%BD%B1%E9%97%AE%E9%A2%98

我文字有残影，加白边好了，你试试呢

**Comment by xtito** [comment]
> https://g6.antv.antgroup.com/manual/faq/faq#%E6%B8%B2%E6%9F%93%E6%AE%8B%E5%BD%B1%E9%97%AE%E9%A2%98
> 
> 我文字有残影，加白边好了，你试试呢

感谢您的回复。是的，加白边可以解决这个问题；使用graph.get('canvas').set('localRefresh', false); 也可以解决这个问题，期待5.x版本彻底解决该问题
