### ISSUE TITLE
自定义折线设置radius不生效

### ISSUE THREAD

**Issue by Sharang-heng** [antvis/G6#4463]
### 问题描述

想设置折线的曲率不生效，90度的折线不太好看    
G6.registerEdge('line-arrow', {
      draw(cfg, group) {
        const startPoint = cfg.startPoint;
        const endPoint = cfg.endPoint;
        const shape = group.addShape('path', {
          attrs: {
            stroke: '#C0C4CC',
            radius: 10,
            lineWidth: 1,
            path: [
              ['M', startPoint.x, startPoint.y],
              ['L', startPoint.x, endPoint.y - 40],
              ['L', endPoint.x, endPoint.y - 40],
              ['L', endPoint.x, endPoint.y],
            ],
            endArrow: true,
          },
          name: 'path-shape',
        });
        if (cfg.label) {
          group.addShape('text', {
            attrs: {
              text: cfg.label,
              fill: '#595959',
              textAlign: 'center',
              textBaseline: 'middle',
              x: endPoint.x,
              y: endPoint.y - 40,
            },
            name: 'right-text-shape',
          });
        }
        return shape;
      },
    });

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/69613396/233965118-f8152a26-a47d-4799-b17c-4b6580385152.png)

**Comment by foreverfirst** [comment]
> 配置 radius 实现的圆角折线是 G6 中做的额外处理，你这个例子应该可以继承内置的折线（registerEdge 的第三个参数写 'polyline'），只复写 getControlPoints 返回自己定义的中间控制点即可，这样还是会走 G6 内部的折线处理和绘制逻辑，就可以处理 radius。还需要自定义文本的话，复写 drawLabel。
我需要自定义附带圆角的折线边，按照你的提示继承 polyline 并重写了getControlPoints方法，返回了边的两个中间节点，并且在每个数据node中设置了anchorPoints 为 [  [0, 0.5], [1, 0.5]  ]，但是自定义边的 startPoint 似乎并不会自动识别、分布在起始节点的两侧。
Graphin.registerEdge(
  'hvh',
  {
    getControlPoints(cfg) {
      const { startPoint, endPoint } = cfg;
      const { x: sx, y: sy } = startPoint;
      const { x: ex, y: ey } = endPoint;
      const mPoint = sx < ex ? sx + 10 : sx - 10;
      return [
        { x: mPoint, y: sy },
        { x: mPoint, y: ey },
      ];
    },
  },
  'polyline',
);

![image](https://user-images.githubusercontent.com/42527218/234795444-def158bf-19f9-46fe-8069-a0216bb86701.png)

**Comment by foreverfirst** [comment]
> 我需要自定义附带圆角的折线边，按照你的提示继承 polyline 并重写了getControlPoints方法，返回了边的两个中间节点，并且在每个数据node中设置了anchorPoints 为 [ [0, 0.5], [1, 0.5] ]，但是自定义边的 startPoint 似乎并不会自动识别、分布在起始节点的两侧。
> Graphin.registerEdge(
> 'hvh',
> {
> getControlPoints(cfg) {
> const { startPoint, endPoint } = cfg;
> const { x: sx, y: sy } = startPoint;
> const { x: ex, y: ey } = endPoint;
> const mPoint = sx < ex ? sx + 10 : sx - 10;
> return [
> { x: mPoint, y: sy },
> { x: mPoint, y: ey },
> ];
> },
> },
> 'polyline',
> );

我需要自定义附带圆角的折线边，按照你的提示继承 polyline 并重写了getControlPoints方法，返回了边的两个中间节点，并且在每个数据node中设置了anchorPoints 为 [ [0, 0.5], [1, 0.5] ]，但是自定义边的 startPoint 似乎并不会自动识别、分布在起始节点的两侧。
Graphin.registerEdge(
'hvh',
{
getControlPoints(cfg) {
const { startPoint, endPoint } = cfg;
const { x: sx, y: sy } = startPoint;
const { x: ex, y: ey } = endPoint;
const mPoint = sx < ex ? sx + 10 : sx - 10;
return [
{ x: mPoint, y: sy },
{ x: mPoint, y: ey },
];
},
},
'polyline',
);
![image](https://user-images.githubusercontent.com/42527218/234796265-217b2384-16ee-4806-a133-457d1735a8df.png)

**Comment by foreverfirst** [comment]
> 配置 radius 实现的圆角折线是 G6 中做的额外处理，你这个例子应该可以继承内置的折线（registerEdge 的第三个参数写 'polyline'），只复写 getControlPoints 返回自己定义的中间控制点即可，这样还是会走 G6 内部的折线处理和绘制逻辑，就可以处理 radius。还需要自定义文本的话，复写 drawLabel。

我需要自定义附带圆角的折线边，按照你的提示继承 polyline 并重写了getControlPoints方法，返回了边的两个中间节点，并且在每个数据node中设置了anchorPoints 为 [ [0, 0.5], [1, 0.5] ]，但是自定义边的 startPoint 似乎并不会自动识别、分布在起始节点的两侧。
Graphin.registerEdge(
'hvh',
{
getControlPoints(cfg) {
const { startPoint, endPoint } = cfg;
const { x: sx, y: sy } = startPoint;
const { x: ex, y: ey } = endPoint;
const mPoint = sx < ex ? sx + 10 : sx - 10;
return [
{ x: mPoint, y: sy },
{ x: mPoint, y: ey },
];
},
},
'polyline',
);
![image](https://user-images.githubusercontent.com/42527218/234796367-0b5f754d-76af-4aad-9e34-f8226366284a.png)

**Comment by foreverfirst** [comment]
> 配置 radius 实现的圆角折线是 G6 中做的额外处理，你这个例子应该可以继承内置的折线（registerEdge 的第三个参数写 'polyline'），只复写 getControlPoints 返回自己定义的中间控制点即可，这样还是会走 G6 内部的折线处理和绘制逻辑，就可以处理 radius。还需要自定义文本的话，复写 drawLabel。

@Yanyan-Wang 
我需要自定义附带圆角的折线边，按照你的提示继承 polyline 并重写了getControlPoints方法，返回了边的两个中间节点，并且在每个数据node中设置了anchorPoints 为 [ [0, 0.5], [1, 0.5] ]，但是自定义边的 startPoint 似乎并不会自动识别、分布在起始节点的两侧。
Graphin.registerEdge(
'hvh',
{
getControlPoints(cfg) {
const { startPoint, endPoint } = cfg;
const { x: sx, y: sy } = startPoint;
const { x: ex, y: ey } = endPoint;
const mPoint = sx < ex ? sx + 10 : sx - 10;
return [
{ x: mPoint, y: sy },
{ x: mPoint, y: ey },
];
},
},
'polyline',
);
![image](https://user-images.githubusercontent.com/42527218/234796831-b47bc2e9-5c72-4960-b4ac-c9f0b80cce80.png)

**Comment by Yanyan-Wang** [comment]
这个需要配置节点的 anchorPoints 和边的 sourceAnchor targetAnchor https://g6.antv.antgroup.com/manual/middle/elements/nodes/anchorpoint
