### ISSUE TITLE
矩形节点扩散动画效果如何实现？现有圆形效果无法转换为矩形

### ISSUE THREAD

**Issue by xtito** [antvis/G6#4464]
### 问题描述

期望实现矩形的扩散动效，在官方示例中：https://g6.antv.antgroup.com/examples/scatter/node/#node ，节点动画图形：Background Animation，实现了的光圈扩散的动效，但是尝试将圆（circle）换成矩形（rect）不生效

### 重现链接

https://stackblitz.com/edit/js-2byutt?file=index.js

### 重现步骤

1、自定义节点；
2、渲染节点

### 预期行为

期望矩形能有扩散效果

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome 103]
- G6 版本: [4.8.6 ]

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/8833358/233988500-6038e8c0-4261-4583-99f5-8664a8a11265.png)

**Comment by xtito** [comment]
@Yanyan-Wang 恳请大佬指点

**Comment by Yanyan-Wang** [comment]
https://codesandbox.io/s/competent-bell-51t6cg?file=/index.js

**Comment by xtito** [comment]
> https://stackblitz.com/edit/js-2byutt?file=index.js

非常感谢您的回复
