### ISSUE TITLE
antv G6 更改图片类型的节点大小，图片不停闪烁

### ISSUE THREAD

**Issue by lclong** [antvis/G6#4466]
### 问题描述

您好，在G6中创建了一个图片类型的node节点，并开发了使用鼠标拖拽通过updateItem() 方法改变节点大小的功能。但是在鼠标拖拽过程中，节点不停闪烁，应该是节点不停销毁重建造成的，请问有什么解决办法吗？谢谢

### 重现链接

无

### 重现步骤

无

### 预期行为

我期望看到：图片节点元素可以正常改变大小，不闪烁。
实际看到：    图片节点元素大小改变，但不停闪烁

### 平台

- 操作系统: Windows
- 网页浏览器: Google Chrome
- G6 版本: 4.8.5

### 屏幕截图或视频（可选）

https://user-images.githubusercontent.com/6212279/234153525-a6a85ae4-563c-4fee-9c10-da190b20e7a2.mp4

**Comment by Martin2037** [comment]
同问

**Comment by Yanyan-Wang** [comment]
不是节点在销毁重建，应该是 image 图形的渲染更新过于频繁。我发现拖拽监听加一个 debounce 就好了

https://codesandbox.io/s/dry-wood-6t576y?file=/index.js

**Comment by lclong** [comment]
@Yanyan-Wang 你好，我试过debounce方法，效果好了一些，闪烁没有那么频繁了，但是在每次触发debounce回调的时候，图片还是会闪一下。请问有没有更新图片元素大小，但是不让图片闪烁的方法呢？谢谢

**Comment by Yanyan-Wang** [comment]
你 fork 我的 demo 复现一下看看

**Comment by lclong** [comment]
https://github.com/antvis/G6/assets/6212279/9d61397e-84e1-456d-bfd3-fca8a15c6d03

@Yanyan-Wang 你好，我直接用的你的示例。有时也会产生闪烁的现象

**Comment by lclong** [comment]
@Yanyan-Wang 刚试了下，打开控制台，拖拽时就会闪烁。关闭控制台一般就不闪烁。

**Comment by Yanyan-Wang** [comment]
> @Yanyan-Wang 刚试了下，打开控制台，拖拽时就会闪烁。关闭控制台一般就不闪烁。

这样啊，那用户用的时候一般不会开控制台

**Comment by lclong** [comment]
好的，谢谢
