### ISSUE TITLE
手机端 onClick事件无效

### ISSUE THREAD

**Issue by guoguozhang** [antvis/G6#4468]
### 问题描述

手机端所有的相关事件都是无效的
graph.on('click', (ev) => {
  const shape = ev.target;
  const item = ev.item;
  if (item) {
    const type = item.getType();
  }
});

### 重现链接

手机端的问题

### 重现步骤

进入界面，点击任何区域

### 预期行为

希望手机端是有效的

### 平台

IOS

**Comment by TThz-hz** [comment]
试试 antv/F6, 或者自定义behavior模拟click

**Comment by LeaveZzz** [comment]
node:touchstart | 在触控屏上，当节点开始被触碰的时候触发的事件
