### ISSUE TITLE
怎么更新线的颜色

### ISSUE THREAD

**Issue by pangchao21** [antvis/G6#4469]
### 问题描述

group.addShape('path', { attrs: { stroke: '#CCC', path:... } })
1.在我监听线的鼠标移入移出事件时，怎么更新线的颜色呢？
2.箭头怎么可以设置成实心的？

### 重现链接

无

### 重现步骤

无

### 预期行为

![image](https://user-images.githubusercontent.com/25843968/234535844-22dcabf2-4bb7-418f-9301-ceb4e385d8a4.png)

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
箭头：https://g6.antv.antgroup.com/examples/item/arrows/#built-in-arrows

状态样式：https://g6.antv.antgroup.com/manual/advanced/state-new
