### ISSUE TITLE
当animate为true时, mouseleave事件会错误触发

### ISSUE THREAD

**Issue by ah-peplink** [antvis/g6#447]
* **G6 Version**: 2.1.0
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodeSandbox Link**: https://codesandbox.io/s/x2m7xv7wqz

更新为2.1.0版本后尝试使用高亮子图插件, 并为节点添加mouseenter及mouseleave事件, 但发现mouseleave事件会在mouseenter事件触发后立即触发, 但鼠标并没有离开目标节点, 并且只会在animate为true时发生

**Comment by TomHuangCN** [comment]
下个版本修复

**Comment by TomHuangCN** [comment]
https://codesandbox.io/s/8pw1lkov0

最新版错误问题已经解决了，动画还没做的很好，建议先关闭动画
