### ISSUE TITLE
如何用G6实现d3.forceRadial 布局和radius方法

### ISSUE THREAD

**Issue by wicked9tailfox** [antvis/G6#4471]
### 问题描述

目前项目需要用G6替换d3，但是发现G6好像没有类似forceRadial 的方法，同时希望有radius方法，能控制节点处在哪一个圈层

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
给个例子看看？目测可以试试 https://g6.antv.antgroup.com/api/graph-layout/dagre#%E6%8C%87%E5%AE%9A%E8%8A%82%E7%82%B9%E5%B1%82%E7%BA%A7

然后给它配置 radial: true  （这个参数暂时没在文档透出）
