### ISSUE TITLE
自定义edge线后 无法改变样式

### ISSUE THREAD

**Issue by 542473232** [antvis/G6#4472]
### 问题描述

我在自定义了一个edge后，想通过节点的鼠标移入/移出事件，来改变相关线的样式，默认使用的‘quadratic’，只有这个自定义的线没有改变样式

这个是图表
![image](https://user-images.githubusercontent.com/65716967/234759494-98221a76-9b37-4518-88c7-be56f98b1322.png)

### 重现链接

暂无

### 重现步骤

这个是我定义的代码
![image](https://user-images.githubusercontent.com/65716967/234759308-e061cd94-cf9e-483b-a14f-5cd63b6fcc03.png)

### 预期行为

我期望能将这个问题解决，并查明原因

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
自定义边继承一下内置边，比如是自环的话继承 loop，这样会继承内置的响应状态的方法。不行的话给个在线复现的 demo 吧？

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。

**Comment by 542473232** [comment]
我用其他方式 解决了个这个问题 如果我想通过已有的路径 展示一个小球的运动轨迹 有什么方案嘛

**Comment by Yanyan-Wang** [comment]
这个？：https://g6.antv.antgroup.com/examples/scatter/edge/#pointInLine

**Comment by 542473232** [comment]
嗯嗯 这个如果数据量非常大的话 比如千万级数据 动画会卡顿吗
