### ISSUE TITLE
The product text expound a word problems

### ISSUE THREAD

**Issue by 17835287598** [antvis/G6#4474]
### 问题描述

When I was using drag and drop events, met the article drag drag words writing errors.

### 重现链接

https://antv-g6.gitee.io/zh/docs/api/Event/#%E9%80%9A%E7%94%A8%E4%BA%A4%E4%BA%92%E4%BA%8B%E4%BB%B6

### 重现步骤

Basis of common events dragstart method described, drag and drop the dragged into a drag, so the words wrong

### 预期行为

Basis of common events dragstart method described, drag and drop the dragged into a drag, so the words wrong

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

Basis of common events dragstart method described, drag and drop the dragged into a drag, so the words wrong.

**Comment by Yanyan-Wang** [comment]
Did not get the problem you met, please give me an online reproducing demo.
