### ISSUE TITLE
请问官网首页上这个的交互的图有demo吗？

### ISSUE THREAD

**Issue by MorningStarHu** [antvis/G6#4476]
### 问题描述

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/31729631/235083877-e4dc80e2-601f-422c-a6d2-557454f96d00.png">
这个探索节点的交互逻辑感觉很棒，直接从探索节点中弹出来新的节点，请问有这个demo吗

### 重现链接

https://g6.antv.antgroup.com/design/global/interactive

### 重现步骤

看图

### 预期行为

有这个图上的demo或者给个思路？

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
监听双击节点事件，然后 graph.changeData 更换数据即可

**Comment by MorningStarHu** [comment]
> 监听双击节点事件，然后 graph.changeData 更换数据即可

不需要自定义写动画吗大佬

**Comment by MorningStarHu** [comment]
> 监听双击节点事件，然后 graph.changeData 更换数据即可

想要新增的节点从刚点击的节点中直接弹出来的动画效果

**Comment by Yanyan-Wang** [comment]
如果用的 force2 布局，并开启布局配置的 animate: true，那么就会有“动画”效果，其实是布局计算过程同时渲染。在切换数据的时候，把原有数据里面的 x y 给到新数据里面相同的节点，并且把新增的节点 x y 设置在被双击节点的 x y 附近，差不多就会有这个效果

**Comment by MorningStarHu** [comment]
感谢大佬指教！
