### ISSUE TITLE
请问怎么拖拽一个节点覆盖另外一个节点并且交换内容？

### ISSUE THREAD

**Issue by addriumruss** [antvis/G6#4477]
### 问题描述

请问怎么实现这个功能：
1，同一个画布内，  拖拽一个节点覆盖另外一个节点并且交换内容？
2，两个画布之间， 拖拽一个画布的节点覆盖另外一个画布的节点并且交换内容？

谢谢！

### 重现链接

..

### 重现步骤

..

### 预期行为

..

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]
Chrome, g6最新版

**Comment by addriumruss** [comment]
发错类型了，重发

**Comment by Yanyan-Wang** [comment]
监听 node:drop 方法，“被释放到”的那个节点会触发这个事件，然后通过 graph.updateItem 更新数据

**Comment by addriumruss** [comment]
@Yanyan-Wang 应该可行，我试下先，多谢~
