### ISSUE TITLE
G6 时间轴组件拖动文字出现重影

### ISSUE THREAD

**Issue by stella1997** [antvis/G6#4479]
### 问题描述

G6拖动时间轴文字出现重影
![image](https://user-images.githubusercontent.com/48305123/236369957-4c61881f-22b1-4655-9064-b7e82c0b8e50.png)

### 重现链接

无

### 重现步骤

拖动时间轴 文字出现重影

### 预期行为

希望不要留下重影的效果
已尝试加入 graph.get('canvas').set('localRefresh', false); 没有效果

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.8.7 ... ]

**Comment by Yanyan-Wang** [comment]
给一下 G6 安装的版本号呢？

**Comment by stella1997** [comment]
G6安装的是4.8.7版本

**Comment by Yanyan-Wang** [comment]
好的，给个在线复现的 demo 我看看吧？

**Comment by stella1997** [comment]
> 好的，给个在线复现的 demo 我看看吧？

node 16.16.0会出现issue中的问题，降级node为v12.13.1 14.17.0问题解决

**Comment by Aarebecca** [comment]
该问题系底层渲染引擎脏矩阵擦除不彻底导致，请尝试使用 G6 5.0
