### ISSUE TITLE
The ‘zoom-canvas’ mode is set on the Firefox browser, but the zoom is disabled. The official website can be reproduced 

### ISSUE THREAD

**Issue by 000215** [antvis/G6#4483]
### 问题描述

"@antv/g6": "^4.8.10"
在谷歌浏览器可以正常使用zoom-canvas，在火狐浏览器只能放大，缩小功能失效

### 重现链接

https://stackblitz.com/

### 重现步骤

使用zoom-canvas谷歌浏览器正常缩放，火狐中缩放失效

### 预期行为

火狐浏览器能同样实现缩小功能

### 平台

- 操作系统: [ Windows]
- 网页浏览器: [Google Chrome, Firefox]
- G6 版本: "^4.8.10"

**Comment by Yanyan-Wang** [comment]
试了下 windows firefox 没有复现该问题，看下控制台是否有报错

**Comment by 000215** [comment]
无报错，在Chrome中放大缩小都生效，在firefox 中只能放大，达到maxZoom后放大缩小都失效

**Comment by 000215** [comment]
在"@antv/g6":4.7.17版本中可以在Chrome和firefox 正常使用；
在"@antv/g6": "^4.8.10"版本中还是会有firefox 无法缩小问题

**Comment by Yanyan-Wang** [comment]
试一下 4.8.16
