### ISSUE TITLE
拖拽然后交换两个节点内容, updateItem似乎不太对

### ISSUE THREAD

**Issue by addriumruss** [antvis/G6#4484]
### 问题描述

拖拽一个节点到另一个节点上方，在node:drop事件中交换两个节点内容，
使用
updateItem(item1, model2ObjectCopy);
updateItem(item2, model1ObjectCopy);
graph.refresh();
graph.layout();
第一次显示对的，多个节点相互试几次就完全不对。打出日志发现节点的model似乎根本没有改变。
对象拷贝采用Object.assign函数，甚至采用{}完全重新定义新对象，结果都一样不对。
请问代码问题出在哪里？
谢谢！

### 重现链接

。。

### 重现步骤

。。

### 预期行为

。。

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]
g6 4.9 , chrome

**Comment by Yanyan-Wang** [comment]
给个在线复现 demo 看看

**Comment by HogoZhang** [comment]
4.x的updateItem好像支持将节点的type从改为rect吗，如果不支持该如何实现局部的节点类型切换
