### ISSUE TITLE
CompactBoxTree配合polyline-round,在数据不对称时渲染有

### ISSUE THREAD

**Issue by josietan** [antvis/g6#449]
* **G6 Version**:2.1.0
* **Platform**:
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/22770676/45008539-d3ebc780-b035-11e8-87fb-5ec73b09638e.png)

* **CodePen Link**:

**Comment by josietan** [comment]
CompactBoxTree配合polyline-round，如果数据不对称，折线渲染有问题

**Comment by TomHuangCN** [comment]
这种比较固定的场景，自定义一个 VHV 吧

https://codepen.io/DoriTong/pen/QVjzja?editors=1010

**Comment by lcyh** [comment]
用的react 框架报错:Cannot read property 'CompactBoxTree' of undefined,请问怎么解决
