### ISSUE TITLE
G6有实现度中心性，接近中心性和中介中心性的算法吗

### ISSUE THREAD

**Issue by kevindurant-source** [antvis/G6#4490]
### 问题描述

![image](https://github.com/antvis/G6/assets/67896847/089b0a2d-216d-49e3-8768-165e76499f30)

### 重现链接

无

### 重现步骤

度中心性，接近中心性和中介中心性

### 预期行为

度中心性，接近中心性和中介中心性

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![image](https://github.com/antvis/G6/assets/67896847/6124c1c3-3bec-4827-9a4e-07d0f9e2a1ba)

### 补充说明（可选）

度中心性，接近中心性和中介中心性

**Comment by Yanyan-Wang** [comment]
目前只有度中心性和 Page Rank

https://github.com/antvis/algorithm


pagerank 用法：https://g6.antv.antgroup.com/api/algorithm#pagerank
度中心性其实就是计算节点的度数，参数可以看这里：https://github.com/antvis/algorithm/blob/edcb0e3983a5de026dadf112fcb187f5a2998cee/packages/graph/src/degree.ts#L3
