### ISSUE TITLE
设置layer之后布局错乱

### ISSUE THREAD

**Issue by zhengjun924** [antvis/G6#4491]
### 问题描述

图一是想要的布局，但是最后一个节点layer的值必须大于8，若是设置为8之后就是图二了

### 重现链接

无

### 重现步骤

是用的https://g6.antv.antgroup.com/examples/net/dagreFlow/#basicDagre这个例子

### 预期行为

<img width="1145" alt="image" src="https://github.com/antvis/G6/assets/41844304/937b80e6-8495-43a7-b74e-b93495b3c8e4">

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

<img width="1321" alt="image" src="https://github.com/antvis/G6/assets/41844304/4a8edca4-82e3-4106-a124-8cab943fa82f">
<img width="1293" alt="image" src="https://github.com/antvis/G6/assets/41844304/5212f2c0-24ce-4f38-85f8-088037adc194">

**Comment by zhengjun924** [comment]
。

**Comment by Yanyan-Wang** [comment]
没太明白，可能图片顺序问题，看起来好像还挺符合预期的？

**Comment by zhengjun924** [comment]
> 没太明白，可能图片顺序问题，看起来好像还挺符合预期的？

如果把最高的流程图放在第二列，那第五列的最后一个节点就错位了，
