### ISSUE TITLE
https://unpkg.com/@antv/layout@1.2.0/dist/layout.min.js访问不到了

### ISSUE THREAD

**Issue by hixzhang** [antvis/G6#4493]
### Describe the bug

![image](https://github.com/antvis/G6/assets/54297068/6ee09dde-91e0-45a5-b576-2a78a0ae9f65)
![image](https://github.com/antvis/G6/assets/54297068/38b14203-0edb-47c4-a245-4b15ecc48b35)

### Your Example Website or App

官方问题

### Steps to Reproduce the Bug or Issue

直接访问https://unpkg.com/@antv/layout@1.2.0/dist/layout.min.js

### Expected behavior

https://unpkg.com/@antv/layout@1.2.0/dist/layout.min.js可访问

### Platform

- OS: macOS
- Browser: Chrome
- Version: all

**Comment by albcunha** [comment]
Same

**Comment by rabsondev** [comment]
Same

**Comment by zylee8** [comment]
workerEnabled: true,的时候在layout中加workerScriptURL:"https://cdn.jsdelivr.net/npm/@antv/layout/dist/layout.min.js" 可以正常加载

**Comment by tuhongwei** [comment]
layout中配置workerScriptURL: 'https://unpkg.com/@antv/layout'

**Comment by Yanyan-Wang** [comment]
重新安装一下，解决了
