### ISSUE TITLE
https://unpkg.com/@antv/layout@1.2.0/dist/layout.min.js (Cannot find "/dist/layout.min.js" in @antv/layout@1.2.0)

### ISSUE THREAD

**Issue by rabsondev** [antvis/G6#4496]
### 问题描述

We're experiencing this issue with the library and it's affecting us. Has the issue been prioritized?

![237619240-6ee09dde-91e0-45a5-b576-2a78a0ae9f65](https://github.com/antvis/G6/assets/121631800/38b32d62-5f7a-454e-9b46-6b4ca29baea8)

### 重现链接

https://unpkg.com/@antv/layout@1.2.0/dist/layout.min.js

### 重现步骤

1. Render the graph.
2. The rendering fails.

### 预期行为

The desired outcome is for the script to be found at [https://unpkg.com/@antv/layout@1.2.0/dist/layout.min.js](https://unpkg.com/@antv/layout@1.2.0/dist/layout.min.js) and the graph should render.

However, the resource is not found at [https://unpkg.com/@antv/layout@1.2.0/dist/layout.min.js](https://unpkg.com/@antv/layout@1.2.0/dist/layout.min.js) (Cannot find "/dist/layout.min.js" in @antv/layout@1.2.0). This is because [https://unpkg.com/@antv/layout@1.2.0/dist/layout.min.js](https://unpkg.com/@antv/layout@1.2.0/dist/layout.min.js) was moved to [https://unpkg.com/@antv/layout@1.2.0/dist/index.min.js](https://unpkg.com/@antv/layout@1.2.0/dist/index.min.js). However, the **G6** library is still trying to fetch the resource using [https://unpkg.com/@antv/layout@1.2.0/dist/layout.min.js](https://unpkg.com/@antv/layout@1.2.0/dist/layout.min.js) instead of the new [https://unpkg.com/@antv/layout@1.2.0/dist/index.min.js](https://unpkg.com/@antv/layout@1.2.0/dist/index.min.js).

### 平台

- Web

### 屏幕截图或视频（可选）

![237619240-6ee09dde-91e0-45a5-b576-2a78a0ae9f65](https://github.com/antvis/G6/assets/121631800/f95f46a1-4751-49be-b215-09f25615887e)

### 补充说明（可选）

The bug is always present.

**Comment by tuhongwei** [comment]
layout里面配置 workerScriptURL: 'https://unpkg.com/@antv/layout'

**Comment by rabsondev** [comment]
> layout里面配置 workerScriptURL: 'https://unpkg.com/@antv/layout'

Never mid, it's working. Thanks!

**Comment by ziijiawen** [comment]
<img width="1052" alt="image" src="https://github.com/antvis/G6/assets/21236855/b6965501-d5bf-415e-b6c4-98106896eee8">

Encountered the same error, the problem is still not resolved！！！
