### ISSUE TITLE
拖动部分节点时，出现拖影

### ISSUE THREAD

**Issue by forgaoshang** [antvis/G6#4499]
### 问题描述

在画板添加元素后，拖动元素可能会出现残影
画板的缩放可将残影消除
![image](https://github.com/antvis/G6/assets/114203694/bc654a6b-b2ed-4f3e-b11d-8b965b9d94c4)

### 重现链接

https://g6.antv.antgroup.com/zh/examples/item/customCombo#cCircle

### 重现步骤

1.进入页面直接将 “combo3”向下方拖动

### 预期行为

我期望看到被拖动的元素被拖动到指定位置且 画布整洁无拖影
但我看到 画布有拖影，且无法自动消除

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome, Edge]
- G6 版本: [4.8.7]

### 屏幕截图或视频（可选）

![20230512151509_rec_](https://github.com/antvis/G6/assets/114203694/0821c619-d4bf-4e99-ac77-7f201f646922)

**Comment by Wang-yubo** [comment]
我也发现了类似的问题，补充一下：
![image](https://github.com/antvis/G6/assets/59524432/2250dcde-a91f-43d5-bf85-ade8297de341)
知识图谱树再收起子树的时候出现了残影，并且此时移动也会产生残影。单独移动画布部分子树也会产生残影。目前这个问题仅在window10的电脑上发发现了，mac的电脑没出现。

**Comment by Wang-yubo** [comment]
![image](https://github.com/antvis/G6/assets/59524432/7ac88404-f2d6-4feb-8827-603f0a206d9f)
