### ISSUE TITLE
箭头不能随着线段一起在原锚点转动转动

### ISSUE THREAD

**Issue by itsmyturn** [antvis/g6#45]
![image](https://user-images.githubusercontent.com/11573322/28810227-3e5aff06-76bb-11e7-9ee5-ac6f37cedfa6.png)

**Comment by TomHuangCN** [comment]
有一个比较基础的接口，可以自定义箭头 https://antv.alipay.com/g6/doc/tutorial/start/custom-shape.html

**Comment by itsmyturn** [comment]
![image](https://user-images.githubusercontent.com/11573322/28817914-3c50407e-76dc-11e7-962e-3aea842364ef.png)
里面好像并没有说这个箭头具体是怎么定义出来的，能不能详细说明一下，谢谢
