### ISSUE TITLE
自定义tooltip不显示

### ISSUE THREAD

**Issue by BigKongfuPanda** [antvis/G6#4501]
### 问题描述

G6的数据源来自接口请求的时候，通过plugins: [tooltip, menu]的方式加载自定义tooltip ，鼠标划过节点，tooltip 不展示；
但是将数据源改为假数据，不从接口请求的时候，tooltip 能够展示
假数据和远程请求的数据，是一模一样的

### 重现链接

无，代码如下

### 重现步骤

![image](https://github.com/antvis/G6/assets/16985024/3faa7041-22df-4931-8db2-7282ab0e9cc4)
![image](https://github.com/antvis/G6/assets/16985024/ae812e83-e31c-496d-ab64-f9e7d6712bf7)

### 预期行为

期望动态数据请求的时候，鼠标划过节点，能够看到tooltip

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.5.1 ... ]

**Comment by BigKongfuPanda** [comment]
找到原因了，接口请求回来之前，props.data 为 {}，判断条件 if(!props.data)  为false，即无数据的情况下，执行了G6的实例化。将这个逻辑改为 if (!props?.data?.nodes?.length && !props?.data?.edges?.length) { return;} 就可以显示 tooltip 和 menu 了

**Comment by BigKongfuPanda** [comment]
> 找到原因了，接口请求回来之前，props.data 为 {}，判断条件 if(!props.data) 为false，即无数据的情况下，执行了G6的实例化。将这个逻辑改为 if (!props?.data?.nodes?.length && !props?.data?.edges?.length) { return;} 就可以显示 tooltip 和 menu 了

上面的原因不真实。发现使用新数据（并不是空的）更新G6的图，采用的更新方式是重新实例化G6，此时 tooltip和menu不显示。

**Comment by Yanyan-Wang** [comment]
给个在线复现 demo？

**Comment by Yanyan-Wang** [comment]
tooltip 和 menu 暂不支持 await 动态数据，可以自定义 DOM，挂载方式见：https://g6.antv.antgroup.com/manual/advanced/coordinate-system
