### ISSUE TITLE
Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://unpkg.com/@antv/layout@latest/dist/layout.min.js' failed to load.

### ISSUE THREAD

**Issue by 4yp** [antvis/G6#4502]
### 问题描述

```
Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://unpkg.com/@antv/layout@latest/dist/layout.min.js' failed to load.
```
I have searched the closed issues and found one https://github.com/antvis/G6/issues/2919 , but it can't solve my problem, because the [resource](https://unpkg.com/@antv/layout@1.2.0/dist/layout.min.js) has been deleted.
But Why? And How to solve this problem ?

### 重现链接

https://unpkg.com/@antv/layout@1.2.0/dist/layout.min.js

### 重现步骤

just run you code

### 预期行为

expect it to layout correctly, but nope.

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.8.8]

**Comment by Yanyan-Wang** [comment]
Has been resolved, please reinstall the dependencies.
