### ISSUE TITLE
changeData更新视图后监听的时机事件

### ISSUE THREAD

**Issue by wangxiang666** [antvis/G6#4503]
### 问题描述

图没有使用布局layout，完全自定义，如果用changeData去更新视图的话，想在画布元素渲染完成后执行方法，应该监听哪个时机事件呢，因为没有使用布局，afterlayout无法使用，afterrender只会触发一次，求指导

### 重现链接

无

### 重现步骤

无

### 预期行为

能够监听changeData更新视图后渲染完成的事件

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
有一个 afterchangedata 事件，文档上好像漏了，我补充一下
