### ISSUE TITLE
antv/g6-react-node定义的节点 怎么设置连接点的位置

### ISSUE THREAD

**Issue by wangxin6688** [antvis/G6#4505]
### 问题描述

antv/g6-react-node定义的节点 怎么设置连接点的位置

### 重现链接

antv/g6-react-node定义的节点 怎么设置连接点的位置

### 重现步骤

antv/g6-react-node定义的节点 怎么设置连接点的位置

### 预期行为

antv/g6-react-node定义的节点 怎么设置连接点的位置

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
不是很明白这个问题？

**Comment by Aarebecca** [comment]
见：https://g6.antv.antgroup.com/api/items/node-properties#anchorpoints
