### ISSUE TITLE
新手求教：类似脑图左右布局+Combo的问题

### ISSUE THREAD

**Issue by Huuuuuub** [antvis/G6#4509]
### 问题描述

您好，我查看了一些Issues，有个回答是2021年的，说树图布局不支持Combo，现在貌似仍然不支持，尝试了很多方式没能实现。
我现在有一个绘图需求，如下图，A是主节点，B，C，D，E（还可能有F,G等）左右布局，且有Combo将相同的节点分组，查看了很多天文档，仍然不确定是否可以利用现成的布局Layout实现，或者需要完全的自定义，由于刚入前端，很多地方理解有些吃力，希望得到帮助。谢谢。
<img width="555" alt="截屏2023-05-17 14 54 36" src="https://github.com/antvis/G6/assets/83939900/21c7c63a-bd60-436e-aff4-4f5737a600d6">

### 重现链接

无

### 重现步骤

无

### 预期行为

希望得到解决方式或者思路，谢谢

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
或许你可以不用 TreeGraph，就用 graph 的 dagre 布局 加 combo

**Comment by Yanyan-Wang** [comment]
> > 或许你可以不用 TreeGraph，就用 graph 的 dagre 布局 加 combo
> 
> 没，没画combo, 还是使用的TreeGraph. 如果自己算布局，交付日期前搞不出来。。。

Graph + dagre 布局 + combo ，不用自己算布局
