### ISSUE TITLE
拖动有img Shape且Text会变化的Node时，img会发生闪烁

### ISSUE THREAD

**Issue by spengjie** [antvis/g6#451]
Node中通过addShape添加了Text显示当前坐标，以及img。当拖动Node时，Node中的img会发生闪烁。
https://codepen.io/anon/pen/jvwKbo

**Comment by TomHuangCN** [comment]
需要加载已经 load 好的图片：https://codepen.io/DoriTong/pen/eLRxPB?editors=1010

**Comment by spengjie** [comment]
多谢。问题通过使用load好的图片解决。
