### ISSUE TITLE
gForce Layout中通过addItem增加的节点，新添加进来的节点都是在最左上的位置，怎么在updateItem后让它按照开始的布局分布

### ISSUE THREAD

**Issue by 000215** [antvis/G6#4513]
### 问题描述

gForce Layout中通过addItem增加的节点，新添加进来的节点都是在最左上的位置，怎么在updateItem后让它按照开始的布局分布，尝试过用graph.layout(),但是渲染会很卡顿，直接通过graph.update更新的节点布局正常，通过graph.addItem增加的节点更新完会丢失原来布局，该如何实现通过addItem新增的节点保留原来的布局

### 重现链接

https://stackblitz.com/

### 重现步骤

1.graph.addItem增加节点
2.graph.update更新新节点
3.节点分布与原来gForce布局不同，新加节点所有都在左上方

### 预期行为

节点分布与原有分布相同

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.7.17  ]

**Comment by auuunya** [comment]
graph.layout 重新布局

**Comment by Yanyan-Wang** [comment]
楼上正解

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
