### ISSUE TITLE
g6 节点拖拽问题

### ISSUE THREAD

**Issue by 13540675414** [antvis/G6#4514]
### 问题描述

g6 从3.2.x 版本升级到最新版本后，出现节点不能拖拽到问题

### 重现链接

无

### 重现步骤

无

### 预期行为

节点正常拖动

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
给个在线复现 demo？猜测是自定义节点图形没有加 draggable: true，和 attrs 平级

**Comment by 13540675414** [comment]
> 给个在线复现 demo？猜测是自定义节点图形没有加 draggable: true，和 attrs 平级

问题已经解决了，谢谢。是自定义的事件问题。
