### ISSUE TITLE
G6.Tooltip自定义一个流程图展示，没有展示成功

### ISSUE THREAD

**Issue by Debian350** [antvis/G6#4516]
### Describe the bug

我看了一下，plugins中tooltip自定义中，只能去自定义一个列表消息，提示什么。我想点击node节点在tooltip中再去展示详细的流程图，并没有成功。求大佬来解答一下

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

我看了一下，plugins中tooltip自定义中，只能去自定义一个列表消息，提示什么。我想点击node节点在tooltip中再去展示详细的流程图，并没有成功。求大佬来解答一下

### Expected behavior

我看了一下，plugins中tooltip自定义中，只能去自定义一个列表消息，提示什么。我想点击node节点在tooltip中再去展示详细的流程图，并没有成功。求大佬来解答一下

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [4.8.9]

**Comment by Yanyan-Wang** [comment]
给个在线复现 demo
