### ISSUE TITLE
getInEdges和getOutEdges返回空数组

### ISSUE THREAD

**Issue by prettystone** [antvis/g6#452]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

下面这两个函数，filter的判断是否应该改为判断id相等？

getInEdges() {
    return this.edges.filter(edge => {
      return edge.target === this;
    });
  }
  getOutEdges() {
    return this.edges.filter(edge => {
      return edge.source === this;
    });
  }

**Comment by TomHuangCN** [comment]
不是，这个是 itemEdge

**Comment by TomHuangCN** [comment]
写个 codepen

**Comment by TomHuangCN** [comment]
https://codepen.io/DoriTong/pen/pKbLVw
