### ISSUE TITLE
树图的画布无法拖动

### ISSUE THREAD

**Issue by ljhnhlh** [antvis/G6#4524]
### 问题描述

Windows下，有时候树图的画布无法拖动，但是滚动鼠标，图还是能上下移动，想请问的是
控制画布拖动是g6的哪部分功能，有没有解决的方向

### 重现链接

https://codesandbox.io/s/new

### 重现步骤

Windows下：
缩放窗口后，会有概率无法拖动画布

### 预期行为

画布能够拖动

### 平台

Windows

**Comment by auuunya** [comment]
plugins: ['drag-canvas']

**Comment by Yanyan-Wang** [comment]
有没有配置了拖拽画布的交互？modes: { default: ['drag-node'] }

**Comment by Yanyan-Wang** [comment]
> plugins: ['drag-canvas']

不是在 plugins 里面配哈

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
