### ISSUE TITLE
【Bug】@antv/g6-react-node该依赖中图形的属性都缺少了Position的TS声明

### ISSUE THREAD

**Issue by XinBaoCode** [antvis/G6#4525]
### Describe the bug

图片显示如下（个人使用）：
<img width="613" alt="image" src="https://github.com/antvis/G6/assets/54706013/5c4c30e4-eb29-4f8d-b370-dc29b3701129">
我看[文档](https://dicegraph.github.io/g6-react-node)中是有使用position的例子的
<img width="934" alt="image" src="https://github.com/antvis/G6/assets/54706013/5c95142c-ff2e-42e4-93bb-25574797052f">
但是文档中对参数的定义中却没有position，我看源码里也没有position的声明，希望可以加上。

### Your Example Website or App

https://codesandbox.io/s/divine-smoke-k149xx?file=/App.jsx

### Steps to Reproduce the Bug or Issue

可以看到positon没有定义。

### Expected behavior

希望可以加上position的声明

### Platform

- Browser: [e.g. Chrome]

**Comment by Yanyan-Wang** [comment]
有没有社区小伙伴贡献一下代码

**Comment by Aarebecca** [comment]
`@antv/g6-react-node` 已不再维护，请尝试使用 `@antv/g6-extension-react`，需要 G6 >= 5.0
