### ISSUE TITLE
请问combo目前能否实现antd x6的群组功能，移动内部图元坐标后，combo的坐标保持不变

### ISSUE THREAD

**Issue by chris1299** [antvis/G6#4526]
### 问题描述

类似于antd x6的群组功能，移动内部图元坐标后，combo的坐标保持不变

### 重现链接

无

### 重现步骤

无

### 预期行为

类似于antd x6的群组功能
![A_4YxDQ712eyEAAAAAAAAAAAAAARQnAQ](https://github.com/antvis/G6/assets/52238483/b5b0c367-880d-4407-bb0b-298233949efa)

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
目前不支持，只有拖拽过程中 combo 跟随放大和缩小，drag-node 配置 onlyChangeComboSize: true

**Comment by chris1299** [comment]
谢谢回复，再请教一下，后期有计划实现这个功能么

**Comment by Yanyan-Wang** [comment]
> 谢谢回复，再请教一下，后期有计划实现这个功能么

可能会在 5.0 中支持，看看社区小伙伴有没有感兴趣的可以来贡献这个功能到 4.x
