### ISSUE TITLE
设置了边的透明度的时候，边的颜色和箭头的颜色不一致。

### ISSUE THREAD

**Issue by Fadingvision** [antvis/G6#4527]
### 问题描述

设置了边的透明度的时候，边的颜色和箭头的颜色不一致。

### 重现链接

https://codesandbox.io/s/practical-feynman-nisk8k

### 重现步骤

设置了边的透明度的时候，边的颜色和箭头的颜色不一致。
边和箭头的颜色设置为一样的颜色，同样的0.3透明度，边和箭头的颜色不一样。
![image](https://github.com/antvis/G6/assets/15011394/1b9b02d3-5587-4443-9c3a-10b899a4f80b)

如果手动设置箭头的opacity为0.55, 颜色才一样。

### 预期行为

设置了边的透明度的时候，边的颜色和箭头的颜色一致。

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
因为边有透明度，箭头没有给透明度，都有透明度之后看起来有重叠， 可以通过缩进解决，我改了一下：
https://codesandbox.io/s/naughty-pasteur-74ywkr

**Comment by Fadingvision** [comment]
> 因为边有透明度，箭头没有给透明度，都有透明度之后看起来有重叠， 可以通过缩进解决，我改了一下： https://codesandbox.io/s/naughty-pasteur-74ywkr

@Yanyan-Wang 问题是就算都给0.3的透明度，箭头和边的颜色也不一样（不看重叠的部分，只看箭头吐出来的颜色和边的主体颜色）

**Comment by Yanyan-Wang** [comment]
好像确实有这个问题，只能暂时通过设置不同的值来平衡一下
