### ISSUE TITLE
如何绘制两点的延长线？

### ISSUE THREAD

**Issue by LeaveZzz** [antvis/G6#4530]
### 问题描述

目前通过两点坐标计算出延长线两点坐标，但是效果不理想，拖拽节点时延长线会抖动。

### 重现链接

https://codesandbox.io/s/morning-monad-szy77t?file=/index.js

### 重现步骤

1.进入页面
2.拖拽灰色节点

### 预期行为

希望拖拽节点时延长线不抖动。

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
改了一下，利用了 G6 的箭头缩进：https://codesandbox.io/s/pensive-cache-1nx2r8?file=/index.js

**Comment by LeaveZzz** [comment]
> 改了一下，利用了 G6 的箭头缩进：https://codesandbox.io/s/pensive-cache-1nx2r8?file=/index.js

感谢!
