### ISSUE TITLE
Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.

### ISSUE THREAD

**Issue by dapangxue** [antvis/G6#4531]
### 问题描述

参照 https://g6.antv.antgroup.com/api/plugins#tooltip 实现 tooltip 后，偶现的会抛出这样的错误，导致 tooltip 消失。

![image](https://github.com/antvis/G6/assets/29461265/01a9c3a0-64f7-4efa-a7a0-74f6d2487aad)
![image](https://github.com/antvis/G6/assets/29461265/15d8f9ad-9db8-456c-9f01-d5cc82bd6b1b)

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
给个在线复现 demo？
