### ISSUE TITLE
tooltip 在有滚动条的时候显示位置不准确

### ISSUE THREAD

**Issue by git-hongxia** [antvis/G6#4533]
### 问题描述

tooltip 在有滚动条的时候显示位置不准确

### 重现链接

无

### 重现步骤

无

### 预期行为

tooltip 在滚动的前提下也能正常显示

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![25d653fb3d16d536745e5ff083fab3c](https://github.com/antvis/G6/assets/57702551/3ac15a55-569f-460b-94c4-9bf56059d722)

箭头处为设置的tooltip显示位置  当滚动条滚动时  tooltip位置发生偏移   滚动条滚动距离大  tooltip不显示（应该是便宜位置远着不着了）

![b9827be609d85a9a4cca386a95463de](https://github.com/antvis/G6/assets/57702551/e4d95282-764d-4c16-be1c-60f9539b9476)

**Comment by icemanjin** [comment]
有解决方法了吗

**Comment by icemanjin** [comment]
const jtoolTip: HTMLDivElement = document.createElement('div')
      jtoolTip.classList.add('g6-component-tooltip')
      const tipContainer = document.querySelector('#drag') as HTMLDivElement
      graph.value.on('node:mouseover', (evt: any) => {
        const { item } = evt
        const model = item.getModel()
        const zoom = graph.value.getZoom()
        const canvas = graph.value.get('canvas')
        const canvasBBox = canvas.getCanvasBBox()
        const canvasLeft = canvasBBox.minX
        const canvasTop = canvasBBox.minY
        jtoolTip.innerHTML = model.name
        jtoolTip.style.position = 'absolute'
        jtoolTip.style.top = (evt.clientY + canvasTop - 8) * zoom + 'px'
        jtoolTip.style.left =
          (canvasLeft + model.x + model.size[0] + 6) * zoom + 'px'
        if (tipContainer.childNodes.length <= 1) {
          tipContainer.appendChild(jtoolTip)
        } else {
          jtoolTip.style.display = ''
        }
      })

      // 监听鼠标离开节点事件
      graph.value.on('node:mouseout', () => {
        jtoolTip.style.display = 'none'
      })
可以先这样处理

**Comment by Yanyan-Wang** [comment]
自定义 DOM 作为 tooltip 看看是否可行，挂载方式：https://g6.antv.antgroup.com/manual/advanced/coordinate-system
