### ISSUE TITLE
combo展开时，设置toFront不生效

### ISSUE THREAD

**Issue by mugo1993-ss** [antvis/G6#4534]
### 问题描述

1.根据组合式布局，让所有combo收起渲染，设置groupByTypes: true
2.展开depth低的combo,并且设置toFront，其他的combo还是展示在展开的combo上了
![image](https://github.com/antvis/G6/assets/73928245/f08d1c55-e430-4491-a248-1500e6921546)
![image](https://github.com/antvis/G6/assets/73928245/a522352f-5e61-4e62-b95b-7b9bc3b96623)

### 重现链接

无

### 重现步骤

groupByTypes: true,
      layout: {
        type: 'comboCombined',
        spacing: 20,
        outerLayout: new G6.Layout['dagre']({
          // center: [width / 2, height / 2],
          // linkDistance: 50,
          // nodeStrength: 50,
          // edgeStrength: 0.1,
          rankdir: 'LR', // 可选，默认为图的中心
          align: 'DL', // 可选
          nodesep: -100, // 可选
          ranksep: -100, // 可选
          nodesepFunc: (d) => {
            if (d.isbreakCombo) {
              return 10
            } else {
              return -150
            }
          },
        }),
      },

state.graph.on('beforecollapseexpandcombo ', (action, combo) => {
      if (action === 'expand') {
        combo.toFront()
      }
     
      state.graph.refresh()
    })

### 预期行为

希望展开的combo在最顶层

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
在 aftercollapseexpandcombo 里 toFront 能否生效？因为 G6 需要控制 combo、节点、边的层级，才能让子节点/边看起来在对应的父 combo 中，所以内部会有 sort 的逻辑

**Comment by mugo1993-ss** [comment]
也不生效的，试过了

**Comment by mugo1993-ss** [comment]
能不能分享下最新的群二维码啊 想进群交流一下

**Comment by Blakko** [comment]
I'm facing the same issue. I have an expanded combo and a node, if I try the following code, the combo remains behind the node
```javascript
console.log('combo to front');
const combo = graph.findById('combo-0');
combo.toFront();
const node1 = graph.findById('node-1');
node1.toBack();
//graph.refresh(); // tried with and without this
```
![image](https://github.com/antvis/G6/assets/2861371/666bf9e0-fe00-4e8e-a026-fafc84896308)

I even tried manually setting the z-indexes like this with no result
```javascript
const combo = graph.findById('combo-0');
 const comboGroup = combo.get('group') as Group;
comboGroup.setZIndex(10);
 const node1 = graph.findById('node-1');
 const nodeGroup = node1.get('group') as Group;
nodeGroup.setZIndex(1);
//graph.refresh(); // tried with and without this
```
