### ISSUE TITLE
能否在一个图中绘制多个不同布局的treeGraph

### ISSUE THREAD

**Issue by EdwardChoe** [antvis/G6#4536]
### 问题描述

我需要在一个图中绘制不同layout配置的树图，并且在这些树的节点之间会有交互，类似于下图的效果。但是现有api中一个图只能有一个layout属性。

### 重现链接

如下图所示

### 重现步骤

如图类似的效果

### 预期行为

![image](https://github.com/antvis/G6/assets/20028119/eacfa7c7-9c13-48ac-a5ef-22f395a45a05)
希望在一个图中实现左右布局和右左布局的两棵树。

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![image](https://github.com/antvis/G6/assets/20028119/d1301950-67f2-437e-8b91-a35e564ddbb2)

**Comment by Yanyan-Wang** [comment]
应该需要自定义布局组合多个布局，自定义殊树图布局的例子：https://codesandbox.io/s/fast-shape-xjqmwv?file=/index.js

**Comment by pitilesszgw** [comment]
> 应该需要自定义布局组合多个布局，自定义殊树图布局的例子：https://codesandbox.io/s/fast-shape-xjqmwv?file=/index.js

自定义布局组合多个布局，上下布局的话这种也能采用么
