### ISSUE TITLE
本地运行源码报错Cannot find module 'autoprefixer'

### ISSUE THREAD

**Issue by Janet-wj** [antvis/G6#4540]
### Describe the bug

Cannot find module 'autoprefixer'

### Your Example Website or App

http://localhost:8000/

### Steps to Reproduce the Bug or Issue

yarn install
npm run bootstrap
npm run build:all

### Expected behavior

代码正常运行且能调试site/examples下的功能源码

### Screenshots or Videos

![image](https://github.com/antvis/G6/assets/76807365/2aab21d4-e406-42cf-8bb1-02e5941773c4)

### Platform

node: v16.14.0
g6：4.8.11

**Comment by Yanyan-Wang** [comment]
你是运行 site 吗？

npm install
npm start
