### ISSUE TITLE
G6有类似echarts resize的自适应函数吗？

### ISSUE THREAD

**Issue by LeaveZzz** [antvis/G6#4543]
### 问题描述

窗口放大缩小时g6画布无法自适应，导致布局错乱。

### 重现链接

无

### 重现步骤

无

### 预期行为

希望g6画布能跟随窗口大小变化而变化。

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by auuunya** [comment]
changeSize 使用 observe监听变化，或者自己写个dom的监听方法

**Comment by LeaveZzz** [comment]
> changeSize 使用 observe监听变化，或者自己写个dom的监听方法

好的，谢谢

**Comment by Yanyan-Wang** [comment]
graph.changeSize 修改画布大小，graph.fitView 图内容适配画布大小

**Comment by hustcc** [comment]
v5 将内置对于 window.resize 事件的监听。
