### ISSUE TITLE
在react中使用antv/g6,启动项目很多警告

### ISSUE THREAD

**Issue by zx-zx22** [antvis/G6#4546]
### 问题描述

antv/g6 版本 4.8.14
启动项目很多警告
![image](https://github.com/antvis/G6/assets/62274094/e57fdefb-82e2-47b9-a0de-020f22f2850e)

### 重现链接

1

### 重现步骤

1

### 预期行为

没有警告

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
删掉 lock 文件再安装试试？sourcemap 找不到，不过应该不影响运行

**Comment by zx-zx22** [comment]
试过了也不能解决，确实不影响运行，但是警告信息太多了，试了一些办法也没有忽略掉这个警告。

**Comment by Yanyan-Wang** [comment]
tsconfig 陪一下 "skipLibCheck": true 呢

**Comment by zx-zx22** [comment]
tsconfig 是有这个配置的

**Comment by resetsix** [comment]
> 我也是遇到这个问题， `g6`是纯 `JS` 库，在 `TS` 项目中就会提示那些 `warning` 。
> 
> `源代码映射文件（source map）问题，未能找到对应的源文件`。
> 
> 请问解决了吗

在`.env`文件中加入
```
GENERATE_SOURCEMAP=false
```
就行了
