### ISSUE TITLE
g6 不使用旋转，如何实现节点文本纵向排列

### ISSUE THREAD

**Issue by guoliuqing123** [antvis/G6#4548]
### 问题描述

g6 不使用旋转，如何实现节点文本纵向排列

### 重现链接

无

### 重现步骤

![QQ截图20230530154135](https://github.com/antvis/G6/assets/105954867/b67438a1-624e-4d3f-a16d-7155191c7ecc)

### 预期行为

期望节点文字是竖着的 不是现在的横着的

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by PmcFizz** [comment]
如果节点时 dom元素的话，试一下 css 的属性  writing-mode: tb;

**Comment by Yanyan-Wang** [comment]
一个字一行的效果？可以给文字加 \n 换行
