### ISSUE TITLE
一张画布中渲染多棵树，未超出画布范围的情况下，鼠标滚动树，部分节点被挡住了

### ISSUE THREAD

**Issue by guoliuqing123** [antvis/G6#4551]
### 问题描述

一张画布中渲染多棵树，未超出画布范围的情况下，鼠标滚动树，部分节点被挡住了

https://github.com/antvis/G6/assets/105954867/ddbbe343-d7f8-49f0-a050-c3bee8d81cf5

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]
无

**Comment by aWhver** [comment]
你是怎么在一个画布中渲染多棵树的
