### ISSUE TITLE
A 404 error found in Combo page

### ISSUE THREAD

**Issue by zqqcee** [antvis/G6#4552]
### Describe the bug

![image](https://github.com/antvis/G6/assets/55946653/9539298a-e27a-459b-92a0-92422c840e0d)

This URL is 404 not found, I don't know which demo do you want to display.

### Your Example Website or App

https://g6.antv.antgroup.com/manual/middle/elements/combos/default-combo

### Steps to Reproduce the Bug or Issue

1. visit the https://g6.antv.antgroup.com/manual/middle/elements/combos/default-combo
2. click the link: "Demo" located here
![image](https://github.com/antvis/G6/assets/55946653/9539298a-e27a-459b-92a0-92422c840e0d)
3. 404 not found error

### Expected behavior

I want to see a simple combo demo.

### Screenshots or Videos

![image](https://github.com/antvis/G6/assets/55946653/9539298a-e27a-459b-92a0-92422c840e0d)
![image](https://github.com/antvis/G6/assets/55946653/115ce2e2-2117-409f-9caf-6cbb7e3c040f)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
Thanks for reporting, the demo is: https://g6.antv.antgroup.com/examples/net/comboLayout/#comboCombined

I will update the website ASAP
