### ISSUE TITLE
canvas及其父级元素设置所有属性都被清理了 没法设置鼠标样式

### ISSUE THREAD

**Issue by ABCDdouyaer** [antvis/G6#4556]
### 问题描述

demo: https://stackblitz.com/edit/typescript-9x1cf6?file=index.ts,index.html,style.less
<img width="567" alt="image" src="https://github.com/antvis/G6/assets/31639964/ae320c44-5748-4e80-afcc-4dcfd2d6f326">
<img width="329" alt="image" src="https://github.com/antvis/G6/assets/31639964/7e7ebb62-d744-4028-ad7b-a4e4a1a0754f">

直接给canvas改样式 和 修改父级class都会被重置掉

### 重现链接

https://stackblitz.com/edit/typescript-9x1cf6?file=index.ts,index.html,style.less

### 重现步骤

鼠标移动到节点鼠标样式无变化

### 预期行为

鼠标样式修改

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本:  "@antv/g6": "^4.8.14",

**Comment by Yanyan-Wang** [comment]
节点上的 cursor 在节点的图形样式上设置，改了一下：https://stackblitz.com/edit/typescript-f9owte?file=index.ts,index.html,style.less

**Comment by ABCDdouyaer** [comment]
@Yanyan-Wang 感谢 问题已解决
