### ISSUE TITLE
不同画布的树图节点，能不能相互拖动、替换？

### ISSUE THREAD

**Issue by addriumruss** [antvis/G6#4557]
### 问题描述

每个div放置一个树图, 多个div容器并列排布，
不同树图的节点希望能相互拖动、替换，
请问有没有办法实现？

### 重现链接

。。

### 重现步骤

。。

### 预期行为

。。

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]
win10, chrome

**Comment by guoliuqing123** [comment]
大佬，请教下您是如何将多个树图渲染在多个画布中的呢

**Comment by addriumruss** [comment]
一个div容器放一个graph，多个div自然就能画多个，然后display:flex并排放就行

**Comment by Yanyan-Wang** [comment]
建议写一个悬浮的 DOM ，拖动节点的时候出现，当作代替的元素，这样它才能同时浮在多个 DOM 上方。
