### ISSUE TITLE
g6支持一张画布渲染多棵树吗

### ISSUE THREAD

**Issue by guoliuqing123** [antvis/G6#4558]
### 问题描述

g6支持一张画布渲染多棵树吗

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]
无

**Comment by PmcFizz** [comment]
具体是怎样的效果？可以看看下面的例子。
https://g6.antv.antgroup.com/examples/case/treeDemos#mindmap

**Comment by Yanyan-Wang** [comment]
目前不支持一个画布多个 TreeGraph，实现该需求一般会用一个 TreeGraph，然后隐藏根节点，graph.hideItem，这样看起来多个一级子节点就是多个树的根节点了
