### ISSUE TITLE
请问线条过多，线条重叠，节点文字和线条重叠，怎么去优化？

### ISSUE THREAD

**Issue by wwwing123** [antvis/G6#4561]
### Issue Hunt Program (optional)

- [ ] This issue will participate in the Issue Hunt Program

### Issue Difficulty

None

### Describe the bug

使用Fruchterman布局时，我本身节点并不多，但线条比较多，节点文字重叠（有些还比较长），应该怎么去优化

### Your Example Website or App

截图

### Steps to Reproduce the Bug or Issue

初始化进来

### Expected behavior

重叠尽量减少

### Screenshots or Videos

![微信123](https://github.com/antvis/G6/assets/24401391/58b51b6f-b904-49cc-b3fd-947c63f38360)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by PmcFizz** [comment]
可以尝试将节点之间的距离调大些。

**Comment by wwwing123** [comment]
调过了，效果不太理想，主要是线条太多了，不会自己去避让计算，大佬你那里有布局可以参考一下吗

**Comment by wwwing123** [comment]
这里还有个问题，为什么间距会越来越大
![123](https://github.com/antvis/G6/assets/24401391/d8ec06ad-2504-4ea3-933f-f55588bba6df)

**Comment by zqqcee** [comment]
1. 如果可以接受的话，可以把文字做成tooltip 悬浮框的形式展示，鼠标hover到某个节点，展示对应的节点信息。
2. 或者还有一个方式，如果只需要展示一个属性的话，可以把所有文字的opacity调成0.1到0.5，绑定mouseEnter事件，鼠标滑入时将透明度变为1。

**Comment by Yanyan-Wang** [comment]
用 force2 布局，可以调整 nodeSize 大一些，这样节点间距比较大。目前没有节点和边之间相互避让的方式。

**Comment by neolee6053** [comment]
> 这里还有个问题，为什么间距会越来越大 ![123](https://user-images.githubusercontent.com/24401391/243183809-d8ec06ad-2504-4ea3-933f-f55588bba6df.jpg)

我也遇到同样的问题。我用 force. 因为其他的都太慢了

**Comment by HogoZhang** [comment]
你好，请问你解决了吗
