### ISSUE TITLE
tooltip插件鼠标离开node有时不消失

### ISSUE THREAD

**Issue by cj321** [antvis/G6#4562]
### 问题描述

描述：用法直接使用官网的实例，不过我的Node是自定义拼装的node。tooltip可以正常显示，但是鼠标离开tooltip有时不消失，g6-component-tooltip类名的dom元素样式依然是visibility: visible;display: unset。
尝试方法：监听node:mouseleave事件来找寻dom元素进行隐藏，无效。

### 重现链接

无

### 重现步骤

无

### 预期行为

希望看到方案解决

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.8.13 ]

### 屏幕截图或视频（可选）

![微信截图_20230602094644](https://github.com/antvis/G6/assets/32116365/092f11a3-dcd2-4284-ae39-41e924b7783a)
![1685670430111](https://github.com/antvis/G6/assets/32116365/da41545c-647f-4f22-aa72-a3838021fa20)

**Comment by cj321** [comment]
目前通过定位是发现鼠标离开事件触发机制不精准，导致tooltip一直不消失。
不知是不是因为自定义node的原因。

**Comment by cj321** [comment]
问题得到解决，方案是采用监听node:mouseout移除事件，来强制将元素隐藏

**Comment by 584sentiment** [comment]
我也遇到这个问题，但是好气为什么官方示例没有这样的问题？是因为官方示例节点太少？我尝试使用内置的节点，但是问题仍然存在，所以应该不是自定义节点的问题。不知道官方能不能修复
