### ISSUE TITLE
通过addItem添加combo 动画消失了

### ISSUE THREAD

**Issue by ONwaiting** [antvis/G6#4565]
### Describe the bug

通过addItem添加combo 动画消失了

### Your Example Website or App

https://stackblitz.com/

### Steps to Reproduce the Bug or Issue

if (type === 'module') {
    const combos = {
      id: +new Date() + '',
      type: 'cRect',
      label: '组件',
      x,
      y,
    }
    graph.addItem('combo', combos)

### Expected behavior

期望addItem 添加的combo和data初始化的combo保持一致

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by ONwaiting** [comment]
将节点拖到组合里面，组合的缓慢变大的渐变动画

**Comment by ONwaiting** [comment]
graph.addItem('combo'
请问这个方法有没有配置项可以打开动画

**Comment by Yanyan-Wang** [comment]
通过这个方式加的 combo 动画默认关闭，尝试 combo.set('animate', true)
