### ISSUE TITLE
为什么开了gpu选项布局变成这样

### ISSUE THREAD

**Issue by wwwing123** [antvis/G6#4566]
### 问题描述

开gpu加速后布局被无限拉伸

### 重现链接

截图

### 重现步骤

布局参数
{
type: 'fruchterman',
gpuEnabled: true,
preventOverlap: true,
width: 900,
height: 500,
gravity: 5,
}

### 预期行为

布局不要错乱

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![112](https://github.com/antvis/G6/assets/24401391/08f35b6a-42ad-4190-b454-c03ac2565b49)
![111](https://github.com/antvis/G6/assets/24401391/1eb61cc7-8fcb-41cf-9aa8-bb03552b4934)

**Comment by Yanyan-Wang** [comment]
给个在线复现 demo 呢？数据量小的话可以不用 gpu，或者换 force2 相对比较快

**Comment by GuokrSun** [comment]
个别电脑会出现这种情况，而且换GPU驱动也不行

**Comment by leo1u777** [comment]
我也出现这种情况

**Comment by DIVADING** [comment]
我也出现这种情况。关了gpu就好了
