### ISSUE TITLE
桑基图拖动节点时，边重新渲染不跟随

### ISSUE THREAD

**Issue by CJrZhang** [antvis/G6#4567]
### 问题描述

**桑基图拖动节点时，边重新渲染不跟随**

### 重现链接

https://codesandbox.io/s/runtime-shadow-rllk0u?file=/index.js

### 重现步骤

demo是基于官方旧版的桑基图示例改动的，在拖动中间的几个节点时会发现明显的Path不跟随现象

### 预期行为

Path能正常跟随节点位置

### 平台

Windows

### 屏幕截图或视频（可选）

<img width="960" alt="5_29桑基图path不跟随 性能分析1" src="https://github.com/antvis/G6/assets/39872522/c5e5619a-fe5c-4167-8ea7-fdcda41e6484">
浏览器性能分析截图

**Comment by Yanyan-Wang** [comment]
内部有一个逻辑为了更好的性能，做了边更新的 debounce ，可能是导致这个有瞬间边没有跟上的情况。如果追求高刷新率，可以加一个强制更新：

graph.on("drag", (e) => {
  graph.getEdges().forEach((edge) => edge.refresh());
});

**Comment by CJrZhang** [comment]
收到，问题已解决，谢谢解答
