### ISSUE TITLE
【讨论】如何实现这种布局？

### ISSUE THREAD

**Issue by mugo1993-ss** [antvis/G6#4569]
### 问题描述

1.根据领导要求需要实现下图的布局。
![image](https://github.com/antvis/G6/assets/73928245/71ddc9b8-a652-4699-8af8-6f923a6cda9b)
2.目前采用的force2布局，但结果不是很理想，如何优化呢？
![image](https://github.com/antvis/G6/assets/73928245/28d0b2a8-7363-4dd7-887a-cdfea45e5fd3)

### 重现链接

无

### 重现步骤

无

### 预期行为

1.希望能得到大家的建议

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
看下目前 force2 的参数配置。如果节点数据中没有 size 字段，可以给 force2 配置 nodeSize 大一些，默认是 30。minMovement 调整小一些，这会让迭代停止的条件严格一些。

**Comment by Yanyan-Wang** [comment]
修改了一下：https://stackblitz.com/edit/vue-rkcjrv?file=src%2FApp.vue

**Comment by mugo1993-ss** [comment]
谢谢大佬 ヾ(≧▽≦*)oヾ(≧▽≦*)o
