### ISSUE TITLE
边类型迁移 - quadratic 类型

### ISSUE THREAD

**Issue by Yanyan-Wang** [antvis/G6#4576]
### Issue Hunt 计划（可选）

- [x] 我同意将这个 Issue 参与 Issue Hunt 计划

### Issue 难度

中低难度

### 悬赏

请在 2023 年 7 月 1 日之前完成 PR，7 月 15 日之前完成全部 CR 意见的修改。

AntV 将支付 $5 (汇率按结算当日计)

### 问题描述

将 [G6 4.x 中的 quadratic 类型边](https://github.com/antvis/G6/blob/34f2265030a55f425e365bc61c5d8c2b3175b62a/packages/core/src/element/edge.ts#L466) 迁移到 5.0 中，注意：

- 5.0 中的图形定义、缓存、插入方式有所不同，参考 5.0 line 的实现：[https://github.com/antvis/G6/blob/v5/packages/g6/src/stdlib/item/edge/line.ts](https://github.com/antvis/G6/blob/v5/packages/g6/src/stdlib/item/edge/line.ts)

- 继承 line；

- 类似 line，支持文本、文本背景、icon、其他图形；

- 类似 line，支持状态样式响应、动画、主题等。

### 重现链接

https://github.com/antvis/G6/blob/v5/packages/g6/src/stdlib/item/edge/line.ts

### 重现步骤

1. clone  g6 代码

```
git clone https://github.com/antvis/G6.git
```

2. 拉取所有线上分支

```
git fetch
```

3. 切换到 v5 分支

```
git checkout v5
```

4. 进入 g6 包

```
cd packages/g6
```

5. 安装依赖 

```
npm install
```

6. 启动 demo

```
npm run dev
```

7. 实现功能、新增 demo 以测试

demo 位于 packages/g6/tests/integration

8. 提交代码，等待 CR

9. 根据（多次） CR 建议修改

10. 等待合并入 v5 分支后，管理员支付奖金

### 预期行为

将 [G6 4.x 中的 quadratic 类型边](https://github.com/antvis/G6/blob/34f2265030a55f425e365bc61c5d8c2b3175b62a/packages/core/src/element/edge.ts#L466) 迁移到 5.0 中，注意：

- 5.0 中的图形定义、缓存、插入方式有所不同，参考 5.0 line 的实现：https://github.com/antvis/G6/blob/v5/packages/g6/src/stdlib/item/edge/line.ts

- 类似 line，支持文本、文本背景、icon、其他图形；

- 类似 line，支持状态样式响应、动画、主题等。

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [5.0.0-alpha]

**Comment by zqqcee** [comment]
## Issue 认领 / Issue Claim

**贡献者/Contributor**

>  zqqcee

**预计完成时间/Estimated Completion Date**

> 2023-06-20

**联系方式/Contact Information**

> 例如：zqqcee@163.com

**其他信息/Additional Information**

> 无

**Comment by zqqcee** [comment]
> 这次v5还是打算使用v4的这三个属性吗？
> 
> <img alt="image" width="887" src="https://user-images.githubusercontent.com/55946653/245716244-2e30a60a-6148-473c-936e-7fe35b76b819.png">
> 发现类型检查并不允许我传入这三个属性

如果分了`cubic`和`quadratic`的话，那是不是quadratic是不是只允许用户传入一个控制点和偏移量比较好一些呢？

**Comment by Yanyan-Wang** [comment]
> > 这次v5还是打算使用v4的这三个属性吗？
> > <img alt="image" width="887" src="https://user-images.githubusercontent.com/55946653/245716244-2e30a60a-6148-473c-936e-7fe35b76b819.png">
> > 发现类型检查并不允许我传入这三个属性
> 
> 如果分了`cubic`和`quadratic`的话，那是不是quadratic是不是只允许用户传入一个控制点和偏移量比较好一些呢？

是的～

**Comment by Yanyan-Wang** [comment]
感谢 @zqqcee 完成该项功能～

**Comment by Yanyan-Wang** [comment]
悬赏金已支付，与 https://github.com/antvis/G6/issues/4574 同一笔支付宝支付～ 此 issue 关闭～
