### ISSUE TITLE
UI 插件迁移 - Tooltip

### ISSUE THREAD

**Issue by Yanyan-Wang** [antvis/G6#4578]
### Issue Hunt 计划（可选）

- [X] 我同意将这个 Issue 参与 Issue Hunt 计划

### Issue 难度

中低难度

### 悬赏

请在 2023 年 7 月 1 日之前完成 PR，7 月 15 日之前完成全部 CR 意见的修改。

AntV 将支付 $6 (汇率按结算当日计)

### 问题描述

将 [G6 4.x 中的 Tooltip 插件](https://github.com/antvis/G6/blob/master/packages/plugin/src/tooltip/index.ts) 迁移到 5.0 中，注意：

4.x 的 plugin 在 5.0 属于自由插件模块，参考 5.0 Minimap 的实现：https://github.com/antvis/G6/blob/v5/packages/g6/src/stdlib/plugin/minimap/index.ts

- 继承 Base Plugin；

- 保留 4.x tooltip 所有能力和配置；

- 新增：支持动态数据；

### 重现链接

https://github.com/antvis/G6/blob/v5/packages/g6/src/stdlib/plugin/minimap/index.ts

### 重现步骤

1. clone  g6 代码

```
git clone https://github.com/antvis/G6.git
```

2. 拉取所有线上分支

```
git fetch
```

3. 切换到 v5 分支

```
git checkout v5
```

4. 进入 g6 包

```
cd packages/g6
```

5. 安装依赖 

```
npm install
```

6. 启动 demo

```
npm run dev
```

7. 实现功能、新增 demo 以测试

demo 位于 packages/g6/tests/integration

8. 提交代码，等待 CR

9. 根据（多次） CR 建议修改

10. 等待合并入 v5 分支后，管理员支付奖金

### 预期行为

将 [G6 4.x 中的 Tooltip 插件](https://github.com/antvis/G6/blob/master/packages/plugin/src/tooltip/index.ts) 迁移到 5.0 中，注意：

4.x 的 plugin 在 5.0 属于自由插件模块，参考 5.0 Minimap 的实现：https://github.com/antvis/G6/blob/v5/packages/g6/src/stdlib/plugin/minimap/index.ts

- 继承 Base Plugin；

- 保留 4.x tooltip 所有能力和配置；

- 新增：支持动态数据；

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [5.0.0-alpha]

**Comment by zqqcee** [comment]
## Issue 认领 / Issue Claim

**贡献者/Contributor**

>  zqqcee

**预计完成时间/Estimated Completion Date**

> 2023-06-30

**联系方式/Contact Information**

> 例如：zqqcee@163.com

**其他信息/Additional Information**

> 无

**Comment by Yanyan-Wang** [comment]
恭喜完成～悬赏金已支付～
