### ISSUE TITLE
UI 插件迁移 - TimeBar

### ISSUE THREAD

**Issue by Yanyan-Wang** [antvis/G6#4587]
### Issue Hunt 计划（可选）

- [X] 我同意将这个 Issue 参与 Issue Hunt 计划

### Issue 难度

中等难度

### 悬赏

请在 2023 年 7 月 1 日之前完成 PR，7 月 15 日之前完成全部 CR 意见的修改。

AntV 将支付 $35 (汇率按结算当日计)

### 问题描述

将 [G6 4.x 中的 TimeBar 插件](https://github.com/antvis/G6/tree/master/packages/plugin/src/timeBar) 迁移到 5.0 中，注意：

- 4.x 的 plugin 在 5.0 属于自由插件模块，参考 5.0 Minimap 的实现：https://github.com/antvis/G6/blob/v5/packages/g6/src/stdlib/plugin/minimap/index.ts

- 继承 Base Plugin；

- 保留 4.x TimeBar 所有能力和配置；

### 重现链接

https://github.com/antvis/G6/blob/v5/packages/g6/src/stdlib/plugin/minimap/index.ts

### 重现步骤

1. clone  g6 代码

```
git clone https://github.com/antvis/G6.git
```

2. 拉取所有线上分支

```
git fetch
```

3. 切换到 v5 分支

```
git checkout v5
```

4. 进入 g6 包

```
cd packages/g6
```

5. 安装依赖 

```
npm install
```

6. 启动 demo

```
npm run dev
```

7. 实现功能、新增 demo 以测试

demo 位于 packages/g6/tests/integration

8. 提交代码，等待 CR

9. 根据（多次） CR 建议修改

10. 等待合并入 v5 分支后，管理员支付奖金

### 预期行为

将 [G6 4.x 中的 TimeBar 插件](https://github.com/antvis/G6/tree/master/packages/plugin/src/timeBar) 迁移到 5.0 中，注意：

- 4.x 的 plugin 在 5.0 属于自由插件模块，参考 5.0 Minimap 的实现：https://github.com/antvis/G6/blob/v5/packages/g6/src/stdlib/plugin/minimap/index.ts

- 继承 Base Plugin；

- 保留 4.x TimeBar 所有能力和配置；

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by ColdGun1998** [comment]
## Issue 认领 / Issue Claim

> 归休

> 2023-07-01

> 1744849839@qq.com

**Comment by Yanyan-Wang** [comment]
这个还挺复杂的哈，加钉钉猎人群，有问题可以问

![image](https://github.com/antvis/G6/assets/29593318/eee083db-2b64-4cde-a85b-05b577d5739e)

**Comment by Aarebecca** [comment]
**建议**：
建议将 [Timebar](https://github.com/antvis/G6/blob/bb65cae51819d31f75dac06f9490b1cfc8d16e65/packages/plugin/src/timeBar/index.ts) 中部分工具方法抽出以解耦。
这有助于你更快理解 Timebar 逻辑并缩短开发时间，并且可以帮助第三方 Timebar 组件更好地与 G6 协作。

* 数据过滤
> 根据时间范围筛选出相应的数据
```ts
// range 元素值为时间戳，为 `number` 时表示单一时间，为元组时表示时间范围
type Range = number | [number, number];
// 用于从数据项中取出并标准化时间属性
type TimeGetter = {
  edge?: (edge: Edge) => number;
  node?: (node: Node) => number;
}
type FilterFn = (data: GraphData, range: Range, timeGetter: TimeGetter) => GraphData;
```

* 画布更新
> 将过滤得到的数据应用到画布中
```ts
type RenderFn = (graph: Graph, data: GraphData) => Promise<void>;
```

* 播放
> 结合上述方法，定时进行计算新数据并更新到画布
```ts
type PlayOptions = {
  initRange: Range; // 默认范围
  initState: 'play' | 'pause'; // 默认状态：播放、暂停
  speed: number;  // 播放速率，每秒更新的次数
  sliding: number;  // 每次更新时 Range 的变量。`>0`时正放，`<0` 时倒放
}
// 返回值为 播放、暂停、恢复、前进、后退 的操作函数
type PlayFn = (graph: Graph, options: PlayOptions) => {
  play: () => void,  // 播放
  pause: () => void,  // 暂停
  resume: () => void,  // 恢复
  forward: () => void,  // 前进
  backward: () => void  // 后退
}
```

上述定义仅供参考，如果有更好的设计也欢迎提 PR

相关逻辑参考： https://github.com/antvis/G6/blob/bb65cae51819d31f75dac06f9490b1cfc8d16e65/packages/plugin/src/timeBar/index.ts#L407-L438

**Comment by Yanyan-Wang** [comment]
@Aarebecca 已接替完成～
