### ISSUE TITLE
hideItem 调用隐藏节点和边后，重新layout 后，边位置没变化

### ISSUE THREAD

**Issue by chensanjia** [antvis/G6#4588]
### 问题描述

excludeInvisibles: true 的 layout 下，拖拽（或增减元素）会隐藏的节点导致边位置变化后，hideItem 调用隐藏节点和边后，重新layout 后，边位置没有变化，未连接至 anchorPoint

### 重现链接

https://stackblitz.com/edit/react-7h3wbh?file=index.js

### 重现步骤

1. 拖拽 Consensus 节点
2. 点击左上角“筛选”按钮

### 预期行为

期望看到Modeling Methods 和  Consensus 的连接线正常连接，实际未连接到Consensus上

### 平台

- G6 版本: [4.8.15]

### 屏幕截图或视频（可选）

![image](https://github.com/antvis/G6/assets/135619517/be7e23a4-5bed-4a00-9913-ea45da93bed7)

**Comment by Yanyan-Wang** [comment]
graph.layout 放在循环结束后哈，不然每遍历到一个节点都会 layout 一遍，动画产生冲突

<img width="617" alt="image" src="https://github.com/antvis/G6/assets/29593318/082ecb76-cc01-4c90-aea9-9f8b50c831d6">

**Comment by chensanjia** [comment]
> graph.layout 放在循环结束后哈，不然每遍历到一个节点都会 layout 一遍，动画产生冲突
> 
> <img alt="image" width="617" src="https://user-images.githubusercontent.com/29593318/243382764-082ecb76-cc01-4c90-aea9-9f8b50c831d6.png">

我的错，layout放在循环结束后确实没这样的现象，然而我又看到一个新的问题
点击“筛选“后，隐藏节点，拖拽 “Consensus”后，再点击”还原“按钮，重新显示节点，边虽然连接在节点上，但不在 anchorPoint
![image](https://github.com/antvis/G6/assets/135619517/4e369992-a660-41ad-8c0f-976e8728c3ca)
此时再稍稍拖动隐藏过的节点，如”Classifier selection“，节点到了父节点的左边，anchorPoint 起始和结束似乎反了

**Comment by Yanyan-Wang** [comment]
边的 sourceAnchor targetAnchor 指定下呢？配置到边里，比如
targetAnchor: 0,
sourceAnchor: 1,

**Comment by Yanyan-Wang** [comment]
这个怎么复现？

**Comment by chensanjia** [comment]
1. 点击”筛选“按钮，隐藏节点
2. 点击”还原“按钮，重新显示节点
3. 稍稍拖动隐藏的节点”Classifier selection“，出现节点跳到父节点左侧
4. 再拖回到父节点右侧较近的位置
5. 再次点击”筛选“，再次点击”还原“，出现图上现象
