### ISSUE TITLE
🔥🔥G6 5.0 Alpha 已发布，欢迎尝鲜🔥🔥

### ISSUE THREAD

**Issue by Yanyan-Wang** [antvis/G6#4589]
## G6 5.0 Alpha 特性

G6 作为一款专业的图可视化引擎，具有以下特性：

- 易扩展：七大插件化模块（见下图）；
- 样式、动画规范，信息分层（见下图）；
- 内置亮色、暗色主题，主题可自定义；动画易配置（见下图）；
- 高性能布局：内置了 10+ 常用的图布局，支持 GPU、Rust 并行计算，支持自定义布局；
- 可控的交互：内置 10+ 交互行为，支持自定义交互；
- 友好的体验：根据用户需求分层梳理文档，支持 TypeScript 类型推断；
- 运行时切换多渲染器：Canvas、SVG、WebGL；
- 3D 大图：

GIF 未完整加载，[点此看原图](https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*qPrmQrdV77gAAAAAAAAAAAAADmJ7AQ/original)

<img src="https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*IUOnSbLisyoAAAAAAAAAAAAADmJ7AQ/original" width=600 height=334 alt='' />

> 3D 大图

GIF 未完整加载，[点此看原图](https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*1BFvQ4r3P7UAAAAAAAAAAAAADmJ7AQ/original)

<img src="https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*tPPGSokdSYsAAAAAAAAAAAAADmJ7AQ/original" width=600 height=367 alt='' />

## 发布会回顾

https://mp.weixin.qq.com/s/2hVjFX-oHRob634Cd6nr-w

## 最简单的 Demo

<img src="https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*M-MTRaLiZN0AAAAAAAAAAAAADmJ7AQ/original" width=437 height=138 alt='' />

[![Edit compassionate-lalande-5lxm7](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/musing-matan-q255po?fontsize=14&hidenavigation=1&theme=dark)

## 赏金猎人计划

做开源还能赚钱？

https://github.com/antvis/G6/blob/v5/ISSUEHUNT.md

<img width="854" alt="image" src="https://github.com/antvis/G6/assets/29593318/3e9600ff-11a0-40ab-abe5-f127853d68ee">

**Comment by pomelo-nwu** [comment]
![image](https://github.com/antvis/G6/assets/10703060/1c060a79-ff72-4636-9fe1-ac9e38b80bd2)
每天有2000人访问 G6 github 首页，感觉也可以提个 PR 到 README

**Comment by JS-mark** [comment]
bang  bang bang（(๑•̀ㅂ•́)و✧） ！！！

**Comment by OlderFeng** [comment]
节点支持gif动图么？
