### ISSUE TITLE
缩略图插件中不能正常显示icon图标

### ISSUE THREAD

**Issue by mxszs** [antvis/g6#459]
使用缩略图插件，然后在画布上使用dom元素为节点时，dom元素是icon图标组成，在画布上icon正常显示，在缩略图中以小黑框的形式出现
* **CodePen Link**: [CodePen地址](https://codepen.io/mxszs/pen/gdGbaP)

**Comment by TomHuangCN** [comment]
预加载好图片再渲染即可
