### ISSUE TITLE
Bug:  A TypeError occurred while writing a test demo

### ISSUE THREAD

**Issue by zqqcee** [antvis/G6#4596]
### Describe the bug

Recently, I found an TypeError during creating a test demo to develop [RectNode](https://github.com/antvis/G6/issues/4574)

### Your Example Website or App

http://127.0.0.1:8080/?name=bugReproduceDemo (local)

### Steps to Reproduce the Bug or Issue

1. run `npm run dev`
2. select bugReproduceDemo
3. open console
4. you will see this bug

### Expected behavior

A circle node appears in canvas

### Screenshots or Videos

<img width="1507" alt="image" src="https://github.com/antvis/G6/assets/55946653/8257663d-c445-48ff-97e4-250feccbde0a">

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

I will fix this bug in two days

**Comment by Yanyan-Wang** [comment]
I think this problem is caused by that you configure type 'rect' to node.data, but 'rect' is not registered to userLib yet.

**Comment by zqqcee** [comment]
I've created a new PR to solve this problem. #4599

**Comment by zqqcee** [comment]
This issue will be closed, The reason for this: #4599
