### ISSUE TITLE
官网时间轴Demo播放bug

### ISSUE THREAD

**Issue by xhx12577** [antvis/G6#4598]
### Describe the bug

1. 趋势时间轴和简易时间轴，选择单个时间，连续点击 preBtn 播放，到第一个时间点后，代码报错 `Uncaught TypeError: Cannot read properties of undefined (reading 'date')`
2. 刻度时间轴，选择单个刻度，连续点击 nextBtn 播放，到最后一个刻度后，代码报错 `Uncaught TypeError: Cannot read properties of undefined (reading 'rect')`

### Your Example Website or App

https://g6.antv.antgroup.com/zh/examples/tool/timebar/#timebar

### Steps to Reproduce the Bug or Issue

Bug 复现过程如描述

### Expected behavior

1. 趋势时间轴和简易时间轴，选择单个时间，连续点击 preBtn 播放，到第一个时间点后，点击 preBtn 不再进行播放，代码不报错
2. 刻度时间轴，选择单个刻度，连续点击 nextBtn 播放，到最后一个刻度后，点击 nextBtn 不再进行播放，代码不报错

### Platform

- OS: Windows
- Browser: Chrome
- Version: 114.0.5735.110

**Comment by Yanyan-Wang** [comment]
给个在线复现 demo？还是说官网这个 demo 能复现？

**Comment by xhx12577** [comment]
官网demo就可以复现

在 2023-06-07 09:59:05，"Yanyan Wang" ***@***.***> 写道：


给个在线复现 demo？还是说官网这个 demo 能复现？

**Comment by Yanyan-Wang** [comment]
好的复现了，我排查下

**Comment by xhx12577** [comment]
@Yanyan-Wang 我看到你这边已经解决了是吧，这个是随4.8.16版本发布吗？请问下大概的发布时间是什么时候呢？
