### ISSUE TITLE
节点阴影实现

### ISSUE THREAD

**Issue by wwwing123** [antvis/G6#4600]
### 问题描述

请问这种阴影效果怎么实现？

### 重现链接

截图

### 重现步骤

截图

### 预期行为

想要在节点上通过样式shadow实现这种高亮效果，在不使用自定义节点的情况能通过shadow样式实现吗？请问有spread的选项可以放大阴影的大小吗？类似css的写法，box-shadow: 0 0 5px 0 #000

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 补充说明（可选）

![aaa](https://github.com/antvis/G6/assets/24401391/ab2e4bee-423e-4982-a286-a301615c3b9c)
这个是效果图，目前阴影只有4个值可选，shadowColor、shadowBlur、shadowOffsetX、shadowOffsetY,还有其他值可以选吗，例如css里拓展阴影大小

**Comment by Yanyan-Wang** [comment]
只有这四个～也许你可以把 shadowColor 设置深一些，然后 shadowBlur 大一些

**Comment by wwwing123** [comment]
不太行，太模糊了，可能要自定义节点了

**Comment by wwwing123** [comment]
这个效果不太理想，不想要模糊的，我意思是专门加多一个圆形的shape去实现我上面截图的效果

**Comment by pomelo-nwu** [comment]
@wwwing123 你截图的效果需要专门增加一个shape 去实现的，一般这个shape我们叫它 「光晕」halo，你可以访问：https://insight.antv.antgroup.com/#/dataset/case 随便创建一个画布体验下效果：
![image](https://github.com/antvis/G6/assets/10703060/d53000bf-b4ce-409e-92b0-fcf19b41e593)

具体的代码实现可以参考：https://github.com/antvis/Graphin/blob/master/packages/graphin/src/shape/graphin-circle.ts#L32

**Comment by Yanyan-Wang** [comment]
类似中间这个，把动画去掉就好

https://g6.antv.antgroup.com/examples/scatter/node/#node

**Comment by wwwing123** [comment]
好的，非常感谢

**Comment by pomelo-nwu** [comment]
@wwwing123 如果有帮助，还望给我们点个 star 哦～ 让更多人看到这个项目
