### ISSUE TITLE
render dom 节点，当发生拖拽、缩放事件时，会重新appendDom

### ISSUE THREAD

**Issue by hnsylitao** [antvis/G6#4601]
### 问题描述

render dom 节点，当发生拖拽、缩放事件时，会重新appendDom

### 重现链接

https://codesandbox.io/s/743nwi

### 重现步骤

1. 进入页面，打开console 观察
2. 拖拽时重新触发dom重新插入

### 预期行为

希望不触发dom插入

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
是的，这个目前是底层渲染引擎的实现方式，不太合理但是可能短时间内不会改变。demo 中节点可以考虑用 canvas 实现，性能也会更好
