### ISSUE TITLE
why  when drag edge label can't trigger edge:drag event

### ISSUE THREAD

**Issue by wpsumsun** [antvis/G6#4612]
### 问题描述

拖拽边的文本是无法触发边的拖拽事件

### 重现链接

-

### 重现步骤

-

### 预期行为

-

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by pomelo-nwu** [comment]
@wpsumsun 还麻烦给个codesandbox 方便复现问题。「拖拽边的文本是无法触发边的拖拽事件」我理解事件的触发绑定在边的keyshape上而非 label 上

**Comment by wpsumsun** [comment]
> @wpsumsun 还麻烦给个codesandbox 方便复现问题。「拖拽边的文本是无法触发边的拖拽事件」我理解事件的触发绑定在边的keyshape上而非 label 上

https://codesandbox.io/s/elastic-snowflake-6nvmzp?file=/src/App.vue
当我的拖拽点是在边的文本上时，无法触发drag或者edge:drag事件，但是可以触发edge:mousedown等事件

**Comment by Yanyan-Wang** [comment]
应该是因为内置实现的时候没有给边的文本图形加上 draggable: true，下个小版本加一下
