### ISSUE TITLE
根据节点的多少展开收起节点，画布的高度也跟随改变

### ISSUE THREAD

**Issue by zhxzhx** [antvis/G6#4618]
### 问题描述

graph.on('afteranimate', () = {
  const graphBBox = graph.getGroup().getCanvasBBox();
  const height = graphBBox.maxY - graphBBox.minY;
  const width = graph.getWidth();
  graph.changeSize(width, height)
});

为什么这段代码加上了以后，点击展开收起的时候屏幕会闪一下呢，收起的时候闪一下流程图没有了，然后又渲染出来了，展开的时候也是流程图没有了，又渲染出来了

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

无

### 补充说明（可选）

无

**Comment by Yanyan-Wang** [comment]
给个在线复现 demo 看看
