### ISSUE TITLE
g6 legend api不支持图片和自定义节点，可通过其他方式实现吗？

### ISSUE THREAD

**Issue by laibin-wang** [antvis/G6#4620]
### 问题描述

自定义得节点在图列上显示不对

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![image](https://github.com/antvis/G6/assets/58844831/2b8dfb80-7e7f-479a-9dec-b8863cc1c6f2)

### 补充说明（可选）

![image](https://github.com/antvis/G6/assets/58844831/b3cac49d-da11-4281-a381-4c08ecf1050e)

**Comment by Yanyan-Wang** [comment]
暂时不支持，看看有没有社区小伙伴愿意贡献一下～

其他的实现方法比如自己写个 DOM……

**Comment by xiongchengqing** [comment]
增加一点代码可以实现

```js
    addVertexIcon(legend) {
      const iconSet = ['./dis.svg', './dis.svg', './dis.svg', './dis.svg', './dis.svg', './dis.svg'];
      const { margin, padding, itemsData } = legend._cfgs;
      const canvas = legend.getContainer().querySelector("canvas");
      const ctx = canvas.getContext('2d');
      itemsData.nodes.forEach((node, index) => {
        const width = node.size;
        const height = node.size;
        const x = 0;
        const y = index * node.size + index * 12;
        const img = new Image();
        img.src = iconSet[index];
        img.onload = function () {
          ctx.drawImage(img, x, y, width, height);
        };
      });
    },
```

效果看起来是这样, 具体根据参数 `layout `, `margin`, `padding`, `vertiSep`, `horiSep` 调整 image `x`, 'y' 值的计算方式。效果看起来是这样：

<img width="383" alt="image" src="https://github.com/antvis/G6/assets/1636616/594af92d-41b5-4f2b-a5cc-29ad3a030e6d">

**Comment by laibin-wang** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by laibin-wang** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
