### ISSUE TITLE
如何保持节点不动的情况下，让视图移动使节点处于视图中心位置 求帮助

### ISSUE THREAD

**Issue by ABCDdouyaer** [antvis/G6#4625]
### 问题描述

<img width="821" alt="image" src="https://github.com/antvis/G6/assets/31639964/509dd6de-0250-4808-a8a5-b0f3460162c5">

这块我实在不知道如何转换坐标 不明白节点用的point位置还是啥，然后moveTo移动端到中心用的啥位置

### 重现链接

https://stackblitz.com/edit/typescript-9x1cf6?file=index.ts,index.html,style.less

### 重现步骤

描述中

### 预期行为

移动视图让节点处于中间

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
如果是数据变更，就数据变更完成后、布局完成后(graph.on('afterlayout', e => {}) 再调用 graph.focusItem 。如果 graph 配置了 animate: true，就在动画完成后做调用 graph.on('afteranimate', e => {})
