### ISSUE TITLE
点击节点或者路径时 如何让edge上的label样式发生改变

### ISSUE THREAD

**Issue by History-1024** [antvis/G6#4629]
### 问题描述

在点击节点或者路径时 如何让edge上的label样式发生改变，见下图，我现在通过点击事件让edge改变了颜色
![image](https://github.com/antvis/G6/assets/65716967/523d63d8-a7f8-4ece-aa04-84cfe3c87767)
` 
 bindEvent () {
      const { graph } = this;

      graph.on("node:click", ({ e, node, view }) => {
        if (node.store?.data.type === "lane-rect") {

          graph.getEdges().forEach(edge => {
            edge.zIndex = 1;
            edge.attr({
              line: {
                stroke: "#409EFF",
              },
            });
          })

          graph.getNodes().forEach(node => {
            if (node._parent) {
              node.zIndex = 1;
              node.attr({
                body: {
                  stroke: "rgba(0,0,0,0)",
                  strokeWidth: 2,
                },
              });
            }
          })
          const nodeId = node.getProp("id");
          node.attr({
            body: {
              stroke: "orange",
              strokeWidth: 4,
            },
          });
          graph
            .getEdges()
            .filter((edge) => {
              return (
                edge.getSource().cell == nodeId
              );
            })
            .forEach((edge) => {
              edge.zIndex = 2;
              edge.attr({
                line: {
                  stroke: "orange",
                },
              });
        }
      });
 
    },`

### 重现链接

见描述

### 重现步骤

暂无，见问题描述

### 预期行为

我期望看到当点击节点或者路径时 label会改变颜色 选择其他路径或者节点时 之前改变的label样式会复原，新的会改变

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by yvonneyx** [comment]
改变边的 label 颜色可以通过修改边配置项 `labelcfg`，贴一个官方文档~
https://g6.antv.antgroup.com/api/items/edge-properties#labelcfg

**Comment by 542473232** [comment]
好的，谢谢，我研究一下。还有一个问题，如图下，我有三个节点的label 展示在了一条线上，导致我不知道label 对应的是那条路径，这个如何解决呢？
![86E43F22-5F35-4496-9363-1CF856695218](https://github.com/antvis/G6/assets/65716967/b3edd070-648e-4b8f-9eb8-c549b99235cf)

**Comment by 542473232** [comment]
![image](https://github.com/antvis/G6/assets/65716967/010afa98-41ec-45dc-aadc-de8bbb786384)
gai'bu'fe该部分代码 labelCfg 我配置了 但是没有变化 ，是因为这个泳道图的自定义路径原因吗

**Comment by Yanyan-Wang** [comment]
看楼主的代码完全不是 G6 的写法呢，建议先看看文档
