### ISSUE TITLE
G6.TreeGraph bug

### ISSUE THREAD

**Issue by xiumubai** [antvis/G6#4630]
### Describe the bug

bug预览地址：https://codesandbox.io/s/gb7gc3
该demo为官方自己提供的demo
bug描述：
- 当第一次点击展示子节点的时候会闪现一下chilren节点，然后消息，第二次点击正常显示。
- 版本："@antv/g6": "latest"

### Your Example Website or App

https://codesandbox.io/s/gb7gc3

### Steps to Reproduce the Bug or Issue

https://codesandbox.io/s/gb7gc3

### Expected behavior

https://codesandbox.io/s/gb7gc3

### Screenshots or Videos

https://codesandbox.io/s/gb7gc3

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
https://codesandbox.io/s/gb7gc3

### Additional context

https://codesandbox.io/s/gb7gc3

**Comment by Yanyan-Wang** [comment]
官网 demo 更新了哈：https://g6.antv.antgroup.com/examples/interaction/treeBehavior/#loadTreeData
