### ISSUE TITLE
require() of ES Module not supported

### ISSUE THREAD

**Issue by sunface** [antvis/G6#4646]
### Describe the bug

你好，我在nextjs + react18 + typescript的环境下，使用时报如下错误，无论如何都解决不了，最后只能把对应的 require 屏蔽掉。

Error: require() of ES Module /Users/sunfei/development/MyStarship/starship/ui/node_modules/d3-interpolate/src/index.js from /Users/sunfei/development/MyStarship/starship/ui/node_modules/@antv/g-base/lib/animate/timeline.js not supported.
Instead change the require of index.js in /Users/sunfei/development/MyStarship/starship/ui/node_modules/@antv/g-base/lib/animate/timeline.js to a dynamic import() which is available in all CommonJS modules.

### Your Example Website or App

null

### Steps to Reproduce the Bug or Issue

null

### Expected behavior

null

### Platform

- OS: [macOS]
- Browser: [Chrome, safari]
- Version: [e.g. 91.1]

**Comment by xiaoiver** [comment]
我去写个例子尝试复现下，看起来像是 d3-interpolate 的问题

**Comment by sunface** [comment]
我对照下你的例子，试试先，感谢兄弟 :D

**Comment by sunface** [comment]
你好，我感觉像是 typescript 的问题，你可以试试编译运行我的项目 : https://github.com/datavisions/datav   ui 目录下， npm run dev 运行，不用启动服务器端也可以复现报错( 不启动服务器端，没有 UI 画面)

**Comment by xiaoiver** [comment]
我也复现这个问题了：
<img width="451" alt="截屏2023-06-16 上午10 16 15" src="https://github.com/antvis/G6/assets/3608471/e8497ca6-d9ef-427a-9dc6-da90ab88581c">

**Comment by xiaoiver** [comment]
可以参考 G2 之前的解决办法：
https://github.com/antvis/G2/issues/4493

**Comment by sunface** [comment]
试了下，可以了 ：） 那使用旧版本的这个解决方案会影响哪个方面？我提前做好心理准备

**Comment by xiaoiver** [comment]
> 试了下，可以了 ：） 那使用旧版本的这个解决方案会影响哪个方面？我提前做好心理准备

d3-interpolate 2.x 依赖 d3-color 2.x，该版本存在安全漏洞：
https://security.snyk.io/vuln/?search=d3-color

另外我以前在知乎看到过您写的关于 Rust 的文章，我最近也在学习，在 [@antv/layout ](https://github.com/antvis/layout/tree/v5/packages/layout-wasm)和 algorithm 里实现了一些简单的布局和分析算法，以后可以多交流哈。

**Comment by sunface** [comment]
好的，好的，谢谢兄弟，以后有机会可以多交流

**Comment by sunface** [comment]
对了，这个项目真的很棒，产品体验和性能都很强！
