### ISSUE TITLE
请问可以实现x6的dnd拖拽插件拖拽g6的节点吗

### ISSUE THREAD

**Issue by Oceannnnnnnn** [antvis/G6#4654]
### 问题描述

请问可以实现x6的dnd拖拽插件拖拽g6的节点吗

### 重现链接

1

### 重现步骤

1

### 预期行为

1

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by pomelo-nwu** [comment]
- 得自己写 dom 拖拽的时候，追踪位置，在dragend的时候addNode

**Comment by Oceannnnnnnn** [comment]
> * 得自己写 dom 拖拽的时候，追踪位置，在dragend的时候addNode

请问是在x6中使用dnd插件本身就要进行这些操作吗 我还没有操作过这个插件

**Comment by pomelo-nwu** [comment]
> > * 得自己写 dom 拖拽的时候，追踪位置，在dragend的时候addNode
> 
> 请问是在x6中使用dnd插件本身就要进行这些操作吗 我还没有操作过这个插件

X6 的issue空间在这里：https://github.com/antvis/X6/issues

**Comment by maquannene** [comment]
不懂为什么这么常用的功能，到现在还没有个官方的最佳实战。
