### ISSUE TITLE
G6 Dagre布局中 controlPoints:为true时，拖动节点所属的combo，节点上的edge连接点出现飘移

### ISSUE THREAD

**Issue by PLS-ToNy** [antvis/G6#4655]
### 问题描述

G6 Dagre布局中 controlPoints:为true时，拖动自定义节点所属的自定义combo，自定义节点上的自定义edge连接点出现飘移
节点与节点间存在多条连线的情况，故使用了controlPoints
在自定义edge中使用getPath也会出现该问题
`getPath(cfg) {
          console.log('🐻', '====GetPathCfg====', cfg);
          const startPoint = cfg[0];
          const endPoint = cfg[1];
          const deltaY = endPoint.y - startPoint.y;
          return [
            ['M', startPoint.x, startPoint.y],
            ['L', endPoint.x, endPoint.y],
          ];
        },`

### 重现链接

无

### 重现步骤

https://github.com/antvis/G6/assets/62326846/242bd8dd-dece-4dbb-8088-b8ba535c38dc

### 预期行为

https://github.com/antvis/G6/assets/62326846/d1bfb184-638f-458a-a94d-dc053796b270

希望可以解决飘移问题
或
提供不使用controlPoints也可显示两个节点间多条连线的方法（尽量不使用有弧度的连线）

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.8.15 ]

**Comment by Yanyan-Wang** [comment]
可以给 graph 配置 linkCenter: true 试试，这样就始终连接到节点中心

**Comment by PLS-ToNy** [comment]
使用 linkCenter: true 可以解决漂移问题但是两个节点间的多条连线无法展示了
![image](https://github.com/antvis/G6/assets/62326846/5db721cc-d9de-4cd5-ab82-a54889de7bfa)
![image](https://github.com/antvis/G6/assets/62326846/c020b50f-23df-449c-92f6-58bd0e359a51)

**Comment by Yanyan-Wang** [comment]
给个在线复现 demo？
