### ISSUE TITLE
state管理箭头样式时报错

### ISSUE THREAD

**Issue by lovelyGFR** [antvis/G6#4658]
### 问题描述

若取消注释，在交互发生的时候，程序出错

### 重现链接

https://codesandbox.io/s/quizzical-alex-36cjyg?file=/index.js

### 重现步骤

若取消注释，在交互发生的时候，程序出错

### 预期行为

预期想要箭头也变色

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
箭头的状态样式里面也写一下 path 哈，path: G6.Arrow.triangle(10, 10), 
具体原因我回头排查下看

**Comment by lovelyGFR** [comment]
> 箭头的状态样式里面也写一下 path 哈，path: G6.Arrow.triangle(10, 10), 具体原因我回头排查下看

好滴好滴~，希望可以优化一下尽量少些重复代码（辛苦！）
