### ISSUE TITLE
G6中嵌入的G2图形tooltip显示错误

### ISSUE THREAD

**Issue by YiXunOc** [antvis/G6#4661]
### 问题描述

G6版本：4.8.16
G2版本：@antv/g2 4.2.9
G6嵌入G2的插件版本@antv/chart-node-g6:  0.0.4

采用基于View的方式，将G2嵌入G6中，G2的tooltip显示位置不正确。
示例连接：https://codesandbox.io/s/gallant-christian-y3yvpx?file=/index.js
（树的根节点的面积图可展示tooltip）

### 重现链接

https://codesandbox.io/s/gallant-christian-y3yvpx?file=/index.js

### 重现步骤

鼠标移入 树 根节点的面积图中，tooltip展示
但是所展示的tooltip信息并不是鼠标所处位置的x值和y值

如下图中，鼠标在1的位置，但是展示是位置2的数据
![1687142372989](https://github.com/antvis/G6/assets/49229531/c3143d94-755e-4114-9c93-c751e062b301)

### 预期行为

这里有三个问题：
  1、这个问题在之后的哪个版本上有修复么？
  2、如果使用@antv/chart-node-g6这个插件进行G6嵌入G2，tooltip也是无法显示的，由于无法调试代码，所以暂时没有定位到问题原因；
  3、在帮助文档中提到，嵌入G2的region位置是通过canvas计算出来的，和canvas大小强相关，那么 region  和 canvas的关系是什么？ 如何设置才能正确的显示G2在G6中的位置并且能够正确的显示tooltip？

### 平台

- 操作系统: Windows
- 网页浏览器: Chrome 104以上
- G6 版本: 4.8.16

### 屏幕截图或视频（可选）

![1687142372989](https://github.com/antvis/G6/assets/49229531/bec1040f-e27d-4e8a-9d6c-be3c7428439b)

### 补充说明（可选）

另：
  G2已经维护到了5.x的版本，且已经改版了，是已经不支持直接调用View创建G2图形了吗？
  G6 4.8.16嵌入G2是否可以使用G2的5.x版本？有示例连接吗？
谢

**Comment by Aarebecca** [comment]
请查看我们最新的示例，G6 5.0 已接入 G2 5.0

https://g6-next.antv.antgroup.com/examples/element/custom-node/#g2-bar-chart
