### ISSUE TITLE
箭头设置透明度后的显示问题（配图）

### ISSUE THREAD

**Issue by lovelyGFR** [antvis/G6#4665]
### 问题描述

<img width="1240" alt="image" src="https://github.com/antvis/G6/assets/48376890/56413d4d-08d0-4bb6-a35b-f928731d4bfa">

理论上设置完之后箭头内应该看不到线了吧，一样的颜色（透明度0.3）

### 重现链接

1

### 重现步骤

1

### 预期行为

1

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by LeaveZzz** [comment]
[https://github.com/antvis/G6/issues/4527](url)
