### ISSUE TITLE
antv g6的内置交互drag-canvas鼠标左键事件是否可以更换成鼠标滚轮

### ISSUE THREAD

**Issue by huzhigao** [antvis/G6#4668]
### 问题描述

antv g6的内置交互drag-canvas鼠标左键事件是否可以更换成鼠标滚轮

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by yangzy0603** [comment]
交互可以自定义，参考下这个文档：https://g6.antv.antgroup.com/manual/middle/states/custom-behavior
另外不太明白这个交互的逻辑，是用鼠标滚轮滚动来拖拽画布吗？这样的话左右拖拽的交互貌似无法满足，可以更详细的描述下你的诉求嘛？@huzhigao

**Comment by Yanyan-Wang** [comment]
有一个内置的交互通过滚轮滚动画布，scroll-canvas https://g6.antv.antgroup.com/manual/middle/states/default-behavior#scroll-canvas

**Comment by huzhigao** [comment]
就是scroll-canvas这个交互，感谢
