### ISSUE TITLE
最大生成树plugin.template.maxSpanningForest报错Cannot read property 'links' of undefined

### ISSUE THREAD

**Issue by Nemo0915** [antvis/g6#467]
* **G6 Version**: 2.1.0
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

具体代码如下：

import * as G6 from '@antv/g6';
import '@antv/g6/build/plugin.template.maxSpanningForest';

const MaxSpanningForestPlugin = G6.Plugins['template.maxSpanningForest'];
const maxSpanningForest = new MaxSpanningForestPlugin({
    layoutCfg: {
        maxIteration: 600,
        kg: 10,
        prevOverlapping: true
    }
});

const data = {
    nodes: [{
        id: 'node1',
        info: 'test',
        parent: 'group1',
        x: 100,
        y: 200
    }, {
        id: 'node2',
        parent: 'group2',
        x: 300,
        y: 200
    }, {
        id: 'node3',
        parent: 'group1',
        x: 100,
        y: 250
    }],
    edges: [{
        id: 'edge1',
        target: 'group2',
        source: 'group1'
    }],
    groups: [{
        id: 'group1',
        index: 1
    }, {
        id: 'group2',
        index: 2
    }]
};

const graph = {
    renderer: 'svg',
    width: 500,
    height: 500,
    fitView: 'cc',
    fitViewPadding: true,
    data,
    plugins: [maxSpanningForest],
    onClick: (ev, graphy) => {
        console.log('click', ev, graphy);
    }
};

export default class DataLineage extends PureComponent {
    render() {
        return (
            <Graph {...graph}>
                <Group {...group}/>
                <Node {...node}/>
            </Graph>
        );
    }
}
浏览器报错，Cannot read property 'links' of undefined

**Comment by Yanyan-Wang** [comment]
这个代码是 react 下的吧？这样我们没法排查问题。能写一个能独立运行的 codepen 吗？ https://codepen.io

**Comment by Nemo0915** [comment]
请问可以给一个关于这个插件使用的例子吗？我看1.X版本似乎是有一个例子的，但是点进去之后就重定向到yuque上去了，2.X版本的文档中并未提供关于这个插件的示例代码。
