### ISSUE TITLE
Combo with bottom hanging label gets stuck to the canvas when dragging the combo

### ISSUE THREAD

**Issue by bsansone** [antvis/G6#4671]
### Describe the bug

When a combo has a label that is positioned to the bottom and textbaseline set to `hanging` the labels will be stuck to the screen when dragging the combo.

### Your Example Website or App

https://codesandbox.io/s/drag-combo-label-bug-mwcqgx?file=/src/App.vue

### Steps to Reproduce the Bug or Issue

1. Go to https://codesandbox.io/s/drag-combo-label-bug-mwcqgx?file=/src/App.vue
2. Drag the combo around
3. Notice the label displays correctly
4. Uncomment the line `// textBaseline: "hanging",`
5. Drag the combo around
6. Notice the label leaves behind a trail of itself stuck to the screen

### Expected behavior

When dragging a combo with a bottom hanging label, it should not leave behind traces of itself on the canvas.

### Screenshots or Videos

# Video recording
[Screencast from 06-22-2023 09:37:27 AM.webm](https://github.com/antvis/G6/assets/16868336/9bcbb034-6abe-455a-ba0d-5445d6b0eccc)

# Screenshot

![image](https://github.com/antvis/G6/assets/16868336/6eec0f0e-e61d-49fe-93e3-d257612f844d)

### Platform

- OS: Linux Ubuntu 22.04.2 LTS x86_64
- Browser: Google Chrome 114.0.5735.133 (Official Build) (64-bit) 
- Version: @antv/g6 4.8.17

**Comment by Yanyan-Wang** [comment]
Sorry, G6 does not support 'hanging' for textBaseline, 'top' | 'bottom' | 'middle' are available.

**Comment by bsansone** [comment]
> Sorry, G6 does not support 'hanging' for textBaseline, 'top' | 'bottom' | 'middle' are available.

I think the docs need to be updated then 
<img width="886" alt="image" src="https://github.com/antvis/G6/assets/16868336/f831b3fa-1ae0-4f3e-b24d-5b1be3416cb4">

**Comment by Yanyan-Wang** [comment]
Yes, it should be corrected ASAP. Thanks
