### ISSUE TITLE
如何设置layout?

### ISSUE THREAD

**Issue by neolee6053** [antvis/G6#4673]
### 问题描述

这是vis-network.可以看见周边的节点会跟着我拖拉的节点移动，而且大概围绕着它。
![vis](https://github.com/antvis/G6/assets/135953327/05a704e3-035a-4ebd-a77f-23138e448da6)

但G6的周边的节点会离我拖拉的节点越来越远。
layout: {
    type: "force",
    preventOverlap: true,
    nodeSpacing: 1,
    linkDistance: 50,  
    nodeStrength: -150,  
  },
![g6](https://github.com/antvis/G6/assets/135953327/2b24dad5-0a5c-4579-9871-b1054fadc2d9)

这是100个节点的效果
Vis
![image](https://github.com/antvis/G6/assets/135953327/f581cb7a-5795-40e0-b6f6-0049d3eb4628)
G6
![image](https://github.com/antvis/G6/assets/135953327/3ffa6673-2b13-49e6-814b-fddeac27c96c)

### 重现链接

https://codesandbox.io/s/g6-forked-46sws3?file=/index.js

### 重现步骤

如上

### 预期行为

如上

### 平台

- 操作系统: [ Windows]
- 网页浏览器: [Google Chrome,]
- G6 版本: [4.8.15 ]

**Comment by Yanyan-Wang** [comment]
换 force2 试试，改过的 demo：https://codesandbox.io/s/g6-forked-4d36sv

force 好像是因为默认配有向心力

**Comment by neolee6053** [comment]
> 换 force2 试试，改过的 demo：https://codesandbox.io/s/g6-forked-4d36sv
> 
> force 好像是因为默认配有向心力

谢谢，我换了一换data.如何可以把节点更靠近一点呢？
![image](https://github.com/antvis/G6/assets/135953327/d11a0494-71a7-4636-8d31-f9ea9fd07740)

**Comment by neolee6053** [comment]
G6的force是用d3的吗？ 可能我想要达到的比较类似cola.
https://marvl.infotech.monash.edu/webcola/#:~:text=js%20(A.K.A.,js%2C%20svg.

**Comment by Yanyan-Wang** [comment]
是的，force 是引用的 d3。force2 是 G6 实现的，我理解你是想要度数大的节点之间距离远一些，可以根据节点度数返回不同的 linkDistance https://g6.antv.antgroup.com/api/graph-layout/force2#layoutcfglinkdistance
