### ISSUE TITLE
Legend插件如何更改节点文字的样式？

### ISSUE THREAD

**Issue by charle004** [antvis/G6#4677]
### 问题描述

根据官网Legend插件的第一个示例实例，然后结合文档，目测 nodeStateStyles 下的 activeByLegend  只能配置节点相关的样式，而节点文字的配置似乎不可以，我尝试过不行，有什么其他解决方法吗？ 在过滤图的节点时，节点文字却不能过滤，不太友好

### 重现链接

https://g6.antv.antgroup.com/zh/examples/tool/legend/#legend

### 重现步骤

根据官网Legend插件的第一个示例实例，然后结合文档，目测 nodeStateStyles 下的 activeByLegend  只能配置节点相关的样式

### 预期行为

我希望Legend插件可以配置节点同时配置节点文字的样式

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.3.11]

**Comment by charle004** [comment]
![Snipaste_2023-06-25_23-54-55](https://github.com/antvis/G6/assets/57860770/762090e7-e0ab-46a0-971e-cdabd459d768)

**Comment by Yanyan-Wang** [comment]
nodeStateStyles 可以配置子图形的状态样式 

看这里的子图形状态样式 https://g6.antv.antgroup.com/manual/advanced/state-new

**Comment by charle004** [comment]
> nodeStateStyles 可以配置子图形的状态样式
> 
> 看这里的子图形状态样式 https://g6.antv.antgroup.com/manual/advanced/state-new

意思是 文字是节点的子元素吗？ 我按下述配置试过了 不生效的

`			nodeStateStyles: {
				activeByLegend: {
					lineWidth: 10,
					strokeOpacity: 0.5,
				},
				inactiveByLegend: {
					opacity: 0.1,

					//下述配置是不生效的
					labelCfg: {
						style:{
							opacity: 0.1
						}
					}

				}
			},`

**Comment by charle004** [comment]
`
			nodeStateStyles: {
				activeByLegend: {
					lineWidth: 10,
					strokeOpacity: 0.5,
				},
				inactiveByLegend: {
					opacity: 0.1,

					//下述配置是不生效的
					labelCfg: {
						style:{
							opacity: 0.1
						}
					}

				}
			}

`

**Comment by Yanyan-Wang** [comment]
看下文档，在状态样式配置中，key 是子图形的 name，如果是内置节点，文本图形的 name 是 text-shape，所以可以写成

inactiveByLegend: {
  'text-shape': {
    opacity: 0.1
  }
}
