### ISSUE TITLE
想请教下antv g6 edge设置不同样式的多个标签

### ISSUE THREAD

**Issue by 000215** [antvis/G6#4678]
### 问题描述

实现edge边上多个样式不同的label
直接用内置的label好像无法单独写样式
自定义label在拖动节点时，节点有时会覆盖到label的数据如：https://g6.antv.antgroup.com/zh/examples/item/customEdge/#edgeMulLabel

### 重现链接

https://g6.antv.antgroup.com/zh/examples/item/customEdge/#edgeMulLabel

### 重现步骤

进入页面单独控制edge上多个label，不同情况下在边左中右展示，单独设置样式

### 预期行为

单独控制多个label，在移动拖拽不会覆盖被节点覆盖

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome, Firefox]
- G6 版本: [4.7.17]

**Comment by Yanyan-Wang** [comment]
需要自定义边，参考https://g6.antv.antgroup.com/examples/item/customEdge/#edgeMulLabel
