### ISSUE TITLE
在不同视口比例下 combo的rect类型边框颜色和粗细不一致

### ISSUE THREAD

**Issue by lywhzy** [antvis/G6#4688]
### 问题描述

期望效果：rect类型的边框在不同视口比例下线的颜色和粗细应是一致的。

### 重现链接

https://codesandbox.io/s/vigilant-glade-x9pr7j?file=/index.js

### 重现步骤

1.进入到页面后缩放视口
2.可以发现矩形边框的粗细和颜色会发生细微的变化，这种变化并不会作用到所有的边框上

### 预期行为

期望效果：rect类型的边框在不同视口比例下线的颜色和粗细应是一致的。

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![测试](https://github.com/antvis/G6/assets/48398427/d44dc8ad-f5a0-49e7-b3fa-b8fbaa10d5f8)

**Comment by Yanyan-Wang** [comment]
![image](https://github.com/antvis/G6/assets/29593318/6da1d4c0-dcc8-433b-a79c-b2e58d31031b)


浏览器的缩放 DOM 也会有这样的问题哈，就是浏览器自身的渲染会这样
