### ISSUE TITLE
导出图片时，图表放大接着执行graph.setTextWaterMarker、 graph.downloadFullImage，会报错

### ISSUE THREAD

**Issue by yinglcs** [antvis/G6#4689]
### 问题描述

![image](https://github.com/antvis/G6/assets/58580062/115885fb-9541-4477-ab9d-7133a85e8d96)
![image](https://github.com/antvis/G6/assets/58580062/041ef84c-5c9f-4b37-9346-953d321c178d)

### 重现链接

https://codesandbox.io/s/new

### 重现步骤

我尝试先把执行graph.fitView()在导出操作之前，则可避免报错

### 预期行为

正常导出，不需要执行fitView

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

 //graph.fitView();

    graph.set('pixelRatio', 6);
    graph.setTextWaterMarker([waterText], {
        width: 80,
        height: 80,
        text: {
            x: 0,
            y: 35,
            lineHeight: 20,
            rotate: 20,
            fontSize: 12
        }
    });
    graph.downloadFullImage(cardTitle.value, 'image/jpeg', {
        backgroundColor: '#fff',
        padding: [30, 15, 15, 15]
    });

### 补充说明（可选）

![image](https://github.com/antvis/G6/assets/58580062/dce671db-c8ab-4273-ab45-8e3e68c50218)

**Comment by Yanyan-Wang** [comment]
给个在线复现 demo 看看？

**Comment by yeyusama** [comment]
是否已解决  请问解决办法是什么
