### ISSUE TITLE
最大生成树插件是否支持自定义dom元素，浏览器报错cannot read property 'getBBox' of undefined

### ISSUE THREAD

**Issue by Nemo0915** [antvis/g6#469]
* **G6 Version**: 2.1.0
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:  https://codepen.io/yisuoyanyu/pen/oPyNNR

最大生成树插件中设置node的shape为自定义dom时，一直报错，注释掉Graph.node({shape: 'CUSTOM_SHAPE'})后，恢复正常

**Comment by TomHuangCN** [comment]
这个代码片段貌似没 G6

**Comment by Nemo0915** [comment]
https://codepen.io/yisuoyanyu/pen/oPyNNR
已更新，注释掉
graph.node({
  shape: 'databaseNode'
});
这段代码，就可以正常显示了
麻烦帮忙看一下，是否是因为自定义了dom元素，导致无法渲染

**Comment by TomHuangCN** [comment]
没有 ReactDom

看报错信息呀

**Comment by Nemo0915** [comment]
抱歉，手误，已经更新https://codepen.io/yisuoyanyu/pen/oPyNNR
