### ISSUE TITLE
dagre布局节点过多页面撑高

### ISSUE THREAD

**Issue by swshuji** [antvis/G6#4690]
### 问题描述

darge布局的某一层有很多个节点，默认全部竖向展开导致高度太高,是否能配置节点数或者高度让其换列适应呢

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]
- Windows

**Comment by CAILeiz** [comment]
同~

**Comment by Yanyan-Wang** [comment]
尝试分页？https://g6.antv.antgroup.com/examples/interaction/pagination/#dagrePagination
