### ISSUE TITLE
请问G6的树布局使用的什么算法实现？

### ISSUE THREAD

**Issue by NanShanJi** [antvis/G6#4691]
### 问题描述

不使用G6树布局，限制有点多，所以想自己实现个树布局，请问下G6树布局结点位置计算用的什么算法？

### 重现链接

https://antv-g6.gitee.io/zh/examples/tree/customItemTree#customEdgeTree

### 重现步骤

纯询问-无重现步骤

### 预期行为

纯询问-无预期行为

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.5.1]

**Comment by Yanyan-Wang** [comment]
文档列出的这几个算法：https://g6.antv.antgroup.com/api/tree-graph-layout/guide

树图的布局算法仓库：https://github.com/antvis/hierarchy

感兴趣的话可以共建到这个仓库中

**Comment by NanShanJi** [comment]
> 文档列出的这几个算法：https://g6.antv.antgroup.com/api/tree-graph-layout/guide
> 
> 树图的布局算法仓库：https://github.com/antvis/hierarchy
> 
> 感兴趣的话可以共建到这个仓库中

谢谢，这解决了我的疑问
