### ISSUE TITLE
企业关系图谱遇到的问题

### ISSUE THREAD

**Issue by renchengwei** [antvis/G6#4692]
### Describe the bug

我在使用G6的compactBox布局创建企业关系图谱，遇到2个问题：
1、树形节点在展开的时候，当前节点和上下相邻节点之间的间距变的很大，出现的大量的空白，不知道该如何避免，我希望在节点展开的时候，上下间距不要发生变化。
![image](https://github.com/antvis/G6/assets/12431521/bca5b616-9e36-4bd6-a974-7ecf9db6143e)
2、如何能够保证当前展开节点的连线避免和同级的其它节点重叠？
![image](https://github.com/antvis/G6/assets/12431521/4716d75d-19c8-4e9e-bac1-428b923d67fe)

### Your Example Website or App

https://codesandbox.io/s/g6-forked-ltpp7y?file=/index.js

### Steps to Reproduce the Bug or Issue

1、打开实例。
2、点击高管-郑素方

### Expected behavior

1、节点在展开的时候，上下相邻节点和当前节点间距不变。
2、节点在展开的时候，保证子节点在同级节点外，即当前节点和子节点之间的折线能够自适应。

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
1. 不行呀，展开子树需要腾出空间给到它
2. 加大层间距 https://g6.antv.antgroup.com/api/tree-graph-layout/compact-box#layoutcfggethgap

**Comment by renchengwei** [comment]
> 1. 不行呀，展开子树需要腾出空间给到它
> 2. 加大层间距 https://g6.antv.antgroup.com/api/tree-graph-layout/compact-box#layoutcfggethgap

1、展开子树的时候我想控制子树节点的位置能够在当前节点之外，类似下面这个例子，在这个例子中，子树的展开没有影响到当前节点上下级的位置
![image](https://github.com/antvis/G6/assets/12431521/8c8fe8f3-6221-4500-a6c7-132f212ca454)

2、由于每个节点的文本是企业名称，我无法提前确定企业名称的长度，从而也无法提前确定HGap的值，所以HGap能够根据自适应吗？我感觉固定值无法满足我的需求。

哪位大神能够指点一下，谢谢！

**Comment by HuColin** [comment]
https://github.com/antvis/hierarchy/issues/16

你看看第一个问题是不是和这个问题是同一个

**Comment by HuColin** [comment]
> 2、由于每个节点的文本是企业名称，我无法提前确定企业名称的长度，从而也无法提前确定HGap的值，所以HGap能够根据自适应吗？我感觉固定值无法满足我的需求。


第二个问题建议做成固定节点宽度+超出tooltip，不然容易出现展开某一层级后，页面内容整体向右移动
