### ISSUE TITLE
文档有误

### ISSUE THREAD

**Issue by Hemomoo** [antvis/G6#4698]
### Describe the bug

文档没有G6.Util.mix 这个方法
<img width="692" alt="image" src="https://github.com/antvis/G6/assets/33367187/0b994b79-8045-445d-9d05-6acdad8c70cd">

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

无

### Expected behavior

希望文档正确

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
- 无

**Comment by Yanyan-Wang** [comment]
这个应该用 Object.assign({}, a, b) 也是一样的，就没有抛出

**Comment by Sunxinqiang** [comment]
https://g6.antv.antgroup.com/api/register-layout 自定义布局的文档 也 写了 Util.mix 望修正 @Yanyan-Wang
