### ISSUE TITLE
节点删除

### ISSUE THREAD

**Issue by guoliuqing123** [antvis/G6#4699]
### 问题描述

树图展开两层节点，通过id 查找到第三层下的节点，然后删除该节点，删除不了，控制台打印的是undefined,
树图展开三层节点，通过id 查找到第三层下的节点，然后删除该节点，可以删除。
-------咨询下，这是什么原因呀（如果未展开第三层节点的情况下，我该如何删除第三层的节点呢）

### 重现链接

无

### 重现步骤

无

### 预期行为

（如果未展开第三层节点的情况下，我该如何删除第三层的节点呢）

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]
无

### 屏幕截图或视频（可选）

无

### 补充说明（可选）

无

**Comment by Yanyan-Wang** [comment]
用的什么方法删除节点？未展开的节点是没有元素对象的，可以通过更新 children 的方式删掉那个节点的数据 https://g6.antv.antgroup.com/api/tree-methods#updatechildrendata-parentid
