### ISSUE TITLE
Mac下开启scroll-canvas以后无法关闭zoom-canvas

### ISSUE THREAD

**Issue by fanggz2017** [antvis/G6#4700]
### 问题描述

Mac设置了scroll-canvas，不设置zoom-canvas，默认会开启双指放大缩小，只能单独开启zoom-canvas,貌似无法单独关闭。有办法开启scroll-canvas的时候，关闭双指缩放吗？在zoom-canvas的设置shouldUpdate设置false也不管用

### 重现链接

https://codesandbox.io/s/winter-sound-66vw9p?file=/src/App.js

### 重现步骤

1. Mac下开启scroll-canvas；
2. 不设置zoom-canvas，默认双指可以放大缩小；
3. 有办法在开启scroll-canvas的时候禁用双指放大缩小吗？

### 预期行为

预期看到只设置scroll-canvas的时候，zoom-canvas默认能不生效，或者有办法禁止zoom-canvas

### 平台

- 操作系统:  macOS
- 网页浏览器: Google Chrome
- G6 版本:  4.8.13

**Comment by Yanyan-Wang** [comment]
可以把 zoomKey 配置为 'meta'，这样按住 meta 键才可以缩放

{
  type: 'scroll-canvas',
  zoomKey: 'meta'
}

或者传入

allowDrag: (e) => {
  if (e.ctrlKey) return false;
  return true;
}

相当于 scroll-canvas 的 shouldBegin，文档应该更新
