### ISSUE TITLE
使用jsx绘制的宽高不同的两个节点如何设置居中对齐

### ISSUE THREAD

**Issue by htyaw** [antvis/G6#4701]
### 问题描述

尝试draw方法绘制设置x,y是生效的。
但是使用jsx绘制自定义节点，在宽高不同的情况下无法居中对齐 尝试设置style={{x:${x},y:${y} }} 并不生效；
想问jsx绘制的节点如何控制其居中对齐。

### 重现链接

无

### 重现步骤

无

### 预期行为

节点居中对齐

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![image](https://github.com/antvis/G6/assets/71117770/c0c6fe56-f680-4b2e-8b61-cee15eddc6db)

**Comment by Yanyan-Wang** [comment]
目前效果的截图放一下？最好放一下在线复现的 demo

**Comment by htyaw** [comment]
> 目前效果的截图放一下？最好放一下在线复现的 demo

您好 写了一个示例您看一下：[https://codesandbox.io/s/dreamy-silence-r5gz38](url)

期望：这连个自定义元素能够居中对齐
![image](https://github.com/antvis/G6/assets/71117770/06504a30-d5eb-4ebd-9ddf-496aa4ef2ded)

**Comment by Yanyan-Wang** [comment]
得用 marginLeft marginTop 代替 x y

https://codesandbox.io/s/naughty-morning-5c74zq?file=/src/App.js
