### ISSUE TITLE
Grid plugin bug?

### ISSUE THREAD

**Issue by neolee6053** [antvis/G6#4706]
### 问题描述

![image](https://github.com/antvis/G6/assets/135953327/93a9f754-14f9-435b-8365-6f6d6bcdb394)

有些线不见了？只在我的program有这样的问题。codesandbox上没有。有人遇见过类似的问题吗？
其中一个我想到的原因可能是我更改了z-index。因为不知道什么原因，我的grid会因为z-index = -1而看不见。可能是angular + ngZorro tab 的关系。

我不得已的做了以下修改

//Fix for z-index for grid
    this.linkViewInstance?.on("beforerender", (e: IG6GraphEvent) => {
      const children = Array.from(this.linkView?.nativeElement?.children);
      children.forEach(c => {
        if (c.className === '.g6-grid-container') {
          (c as HTMLElement).style.zIndex = '1';
        } else {
          (c as HTMLElement).style.zIndex = '2';
        }
      });
      this.minimap.nativeElement.style.zIndex = '2';
      const canvas = this.linkView?.nativeElement?.querySelector('canvas') as HTMLElement;
      if (canvas) {
        canvas.style.position = "relative";
      }
    });

### 重现链接

如上

### 重现步骤

如上

### 预期行为

如上

### 平台

- 操作系统: [ Windows.]
- 网页浏览器: [Firefox]
- G6 版本: [4.8.15 ]

**Comment by Yanyan-Wang** [comment]
你的浏览器有缩放或者容器有缩放？

**Comment by neolee6053** [comment]
> 你的浏览器有缩放或者容器有缩放？

default: [
          {
            type: "zoom-canvas",
            enableOptimize: true
          },

有这个，就是放大放小几次后，就出现了。通常是zoom out 后才出现

**Comment by Yanyan-Wang** [comment]
感觉跟这个问题一样：https://github.com/antvis/G6/issues/4688

可以换成别的图片作为 grid 看看

**Comment by neolee6053** [comment]
> 感觉跟这个问题一样：#4688
> 
> 可以换成别的图片作为 grid 看看

哦。。原来如此。。将来 G6团队会修吗？
