### ISSUE TITLE
在active的状态下的节点第二次hover的状态不符合预期

### ISSUE THREAD

**Issue by lovelyGFR** [antvis/G6#4707]
### 问题描述
![iShot_2023-06-30_09 33 01](https://github.com/antvis/G6/assets/48376890/ec4597b8-72e2-4555-b242-81126a95d95f)

先Select左边的节点,此时右边的节点是active状态,然后hover右边节点,
第一次hover的时候会显示小图标,
但第二次hover的时候不会显示小图标

### 重现链接

https://codesandbox.io/s/hardcore-david-d8ppj8?file=/index.js
### 重现步骤

同上

### 预期行为

mouseenter的时候hover状态覆盖active状态，mouseleave的时候仍然保留active状态
即第二次hover的时候也应该显示小图标

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.5.5]

**Comment by lovelyGFR** [comment]
@Yanyan-Wang 请问一下这个有解法嘛~还是说实现方式有问题哎

**Comment by Yanyan-Wang** [comment]
应该是内部有 bug，我排查一下

**Comment by lovelyGFR** [comment]
> 应该是内部有 bug，我排查一下

修复的是4.8版本的嘛，4.5版本的是不是还是有这个bug呀
