### ISSUE TITLE
在独立显卡的机器上，树状图的性能比集成显卡的机器差很多

### ISSUE THREAD

**Issue by ksy2019** [antvis/G6#4708]
### 问题描述

程序是在集显机器上开发的，开始是可以支持1W个节点
但是在独立显卡的机器上（只有独立显卡，没有集显），1000个节点时就拖动和放大就开始出现卡顿；
layout中woker和enableGpt关闭之后会好一些

### 重现链接

https://codesandbox.io/s/exciting-sound-6kdplz?file=/index.js

### 重现步骤

在集成显卡的电脑拖动和放大
在独立显卡的电脑拖动和放大

### 预期行为

在独立显卡的电脑拖动和放大也不卡

### 平台

- 操作系统: [,Windows]
- 网页浏览器: [Google Chrome,]
- G6 版本: [4.5.1]

**Comment by Yanyan-Wang** [comment]
TreeGraph 的布局没有 gpuEnabled 和 workerEnabled 的选项，如果这两个配置开关对 TreeGraph 性能有影响，可能是别的地方造成的问题而不是树图本身

**Comment by ksy2019** [comment]
有可能只是感觉的变好了，不过codesandbox上的示例在集显机器和独显机器上差别很多，只是官方的demo加了一些数据而已

**Comment by ksy2019** [comment]
![image](https://github.com/antvis/G6/assets/53902755/9db0f785-14e3-4a14-87d1-5c050378535e)
![image](https://github.com/antvis/G6/assets/53902755/0c7d5b06-9226-4da9-8b58-6a9e001d7b03)

遇到了大问题，独立显卡卡很多
技术拙略，能否提供下优化思路或问题的原因。这个问题困扰了好几天😩

**Comment by ksy2019** [comment]
@Yanyan-Wang 有方案吗😬

**Comment by ksy2019** [comment]
@Yanyan-Wang 请问这个问题是与G6库有关吗，换个方式说--gpu运算是由程序控制的吗?  拜托了，如果能回复下就解决了我们的大问题；如果gpu运算不是g6控制的，我们就采取其他的优化方案

**Comment by Yanyan-Wang** [comment]
但问题是，TreeGraph 都没有 GPU 计算呀。看下耗时长的是哪个方法？

**Comment by ksy2019** [comment]
解决了，但是感觉可能还是G6的问题，仔细看了源码，发现G6是有局部更新，理论上大数据多节点也没问题，但是在局部更新时会更新屏幕中节点的兄弟节点（未完全验证）；所以遇到一个父节点下有1万个子节点时，子节点在屏幕中，就会卡顿。然后我们实际需求节点不会那么多，就没继续研究了
