### ISSUE TITLE
如何做到G6vP的edge的效果

### ISSUE THREAD

**Issue by neolee6053** [antvis/G6#4709]
### 问题描述

![image](https://github.com/antvis/G6/assets/135953327/e7398fe1-872b-46b1-8fd1-6edaa33fcc25)

但 hover 时，如何呈现这样的效果？不是G6原本就有的？

### 重现链接

https://codesandbox.io/s/g6-forked-mmyxcy?file=/index.js

### 重现步骤

如上

### 预期行为

如上

### 平台

- 操作系统: [ Windows]
- 网页浏览器: [ Firefox]
- G6 版本: [4.8.15]

**Comment by Yanyan-Wang** [comment]
需要自定义边：https://codesandbox.io/s/naughty-bhaskara-v2qpd8?file=/index.js

**Comment by neolee6053** [comment]
> 需要自定义边：https://codesandbox.io/s/naughty-bhaskara-v2qpd8?file=/index.js

漂亮！
