### ISSUE TITLE
请问一下，按照G绘图设置自定义图形的addshape中的zIndex不生效

### ISSUE THREAD

**Issue by Fled8617** [antvis/g6#471]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by spengjie** [comment]
设置zIndex后不会自动调整zIndex。需要调用group.sort()。

**Comment by TomHuangCN** [comment]
尽量不要通过 zIndex 控制图层，尽量用添加图形的先后控制顺序，这样能省去排序的性能
