### ISSUE TITLE
如何重画refresh?

### ISSUE THREAD

**Issue by neolee6053** [antvis/G6#4710]
### 问题描述

graph.refresh()
graph.refreshPositions()
graph.render()
graph.layout()

都不可以。难道要再从新load data才能重画？ 

### 重现链接

https://codesandbox.io/s/g6-forked-mmyxcy?file=/index.js

### 重现步骤

如上

### 预期行为

如上

### 平台

- 操作系统: [ Windows.]
- 网页浏览器: [ Firefox]
- G6 版本: [4.8.15. ]

**Comment by Yanyan-Wang** [comment]
什么情况下需要 refresh ？

**Comment by neolee6053** [comment]
> 什么情况下需要 refresh ？

有时候当你做了太多的拖拽，变动，纯粹想重新来过

**Comment by Yanyan-Wang** [comment]
graph.layout() 就可以

**Comment by neolee6053** [comment]
> graph.layout()

不能，可能是因为fx ,fy已更改了

refreshDragedNodePosition(e: IG6GraphEvent) {
    const nodes = this.linkViewInstance?.findAllByState('node', 'selected');
    if (nodes && nodes.length > 0) {
      nodes.forEach(n => {
        const model = n.get("model");      
        model.fx = model.x;        
        model.fy = model.y;
      })
    }   
    const model = e.item?.get("model");   
    model.fx = e.x;
    model.fy = e.y;
  }

**Comment by neolee6053** [comment]
对不起，是我搞错了。graph.render()是可以的

**Comment by Yanyan-Wang** [comment]
graph.layout 不影响有 fx fy 的节点，还是会被固定。你是想要重置的时候固定节点被恢复不固定状态？那就把对应数据中的 fx fy 去掉即可
