### ISSUE TITLE
边的起点和终点位置不在节点正中间

### ISSUE THREAD

**Issue by liyanana** [antvis/G6#4715]
### 问题描述

![image](https://github.com/antvis/G6/assets/35280437/3c43f487-0106-4cec-97f8-b27975b32668)
不知道为什么边的起始点终点都靠上，设置什么锚点的配置都不太管用。这些节点使用自定义节点做的，不知道和这个有没有关系

### 重现链接

暂无

### 重现步骤

不知道为什么边的起始点终点都靠上，设置什么锚点的配置都不太管用。这些节点使用自定义节点做的，不知道和这个有没有关系

### 预期行为

希望边在中间的位置，但是目前位置不居中

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by liyanana** [comment]
已解决。

**Comment by tsuyoii** [comment]
> 已解决。

您好，想请教一下大佬怎么解决的，我现在也遇到了 这个问题

**Comment by Yovven** [comment]
同问，怎么解决的
