### ISSUE TITLE
不同层级节点出现遮挡的问题

### ISSUE THREAD

**Issue by liyanana** [antvis/G6#4721]
### 问题描述

某一层的节点太长，会遮挡到下一层的节点
![image](https://github.com/antvis/G6/assets/35280437/a784b393-fd13-468a-98b4-5fbe5afccf9c)

### 重现链接

暂无

### 重现步骤

暂无

### 预期行为

希望可以实现不遮挡

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
加大层间距
