### ISSUE TITLE
tooltip 展示问题

### ISSUE THREAD

**Issue by guohaiping521** [antvis/G6#4724]
### 问题描述

![image](https://github.com/antvis/G6/assets/15829415/e0bd9f57-fb0a-40d8-863e-bb6274332536)
![image](https://github.com/antvis/G6/assets/15829415/f5a6ae7d-5392-4d37-9552-123fba862d13)
鼠标滑动到节点1，展示是ok的，滑动到节点3，希望tooltip能展示到该节点的左边，但是却遮住了节点，这个有自适应的方法吗

### 重现链接

https://stackblitz.com/

### 重现步骤

鼠标滑动上去

### 预期行为

希望自适应

### 平台

Mac

**Comment by auuunya** [comment]
fixToNode 或者offsetX/Y

**Comment by guohaiping521** [comment]
1.fixToNode不行，最后一个如果比较长，会像上面的图片显示的那样，节点右边的边为起始，遮盖住节点
2.offsetX 会造成tooltip展示不固定

**Comment by Yanyan-Wang** [comment]
暂时没有支持这种自动适应，可以自定义 DOM 浮层作为 tooltip，挂载方式：https://g6.antv.antgroup.com/manual/advanced/coordinate-system

**Comment by chw-2021** [comment]
canvas容器的父元素设置相对定位
