### ISSUE TITLE
force/force2 用作子图布局时，有时候并未真正执行布局算法（或者是执行了，没有刷新画布）

### ISSUE THREAD

**Issue by SevenNorth** [antvis/G6#4725]
### force/force2 用作子图布局
subLayoutData2： 新数据不涉及原有数据
subLayoutData2：新数据有一个边指向原有数据
#### force 布局
1. 新增的子图的数据中， 某个边的从新节点指向图谱存在的节点时，子图布局没有执行， 新增节点在右上角， tick函数没有执行；该问题在demo中不稳定复现， 在项目实际使用时100%复现。建议强制刷新之后，先点击 “subLayoutData2” 按钮
![image](https://github.com/antvis/G6/assets/53900832/c6ca5cbf-cb92-4602-9c69-b4c3f63efa95)

3. 新增的子图的数据中，不涉及原有节点，表现正常

#### force2 布局
1. 新增的子图的数据中， 某个边的从新节点指向图谱存在的节点时，报错， 拖拽时有残影
![image](https://github.com/antvis/G6/assets/53900832/888f5b87-34cd-47ff-a3d1-736c522f9066)
2. 新增的子图的数据中，不涉及原有节点，表现算是正常
![image](https://github.com/antvis/G6/assets/53900832/bdd1ca1d-aab7-4387-8985-61727d641afc)

### Your Example Website or App

https://codesandbox.io/s/sublayloutbu-ju-wen-ti-5s85gx?file=/index.html

### Steps to Reproduce the Bug or Issue

1. 点击subLayoutData1
2. 强制刷新页面
3. 点击subLayoutData2
4. 修改layoutType为 "force2"
5. 点击subLayoutData1
6. 点击subLayoutData2

### Expected behavior

期望 force布局执行sublayout的时候，不论新增数据与原有的数据有无关联都能正常进行布局

### Platform

- OS: [Windows]
- Browser: [Chrome]
- Version: [114.0.5735.199]

**Comment by GemT27** [comment]
看了一下, 应该是你执行布局传的数据不完整

**Comment by GemT27** [comment]
试试 ```subLayout.init(graph.save());```,
当然官方也有提供更换布局的API ```graph.updateLayout```.

**Comment by GemT27** [comment]
拖拽时有残影可以试试 ```graph.get('canvas').set('localRefresh', false)```

**Comment by SevenNorth** [comment]
> 

晚点尝试一下

**Comment by Yanyan-Wang** [comment]
控制台有 warning 哈，subData 里面有一条边指向的 node4 不存在。去掉 node4 可以正常运行 
![image](https://github.com/antvis/G6/assets/29593318/982fc26e-b05d-45f9-b1ce-72498f0d74ba)


如果你要指向原来数据里的一个节点，要把这个节点也放到布局里面去计算
