### ISSUE TITLE
使用addItem添加节点的时候，添加的节点位置错乱

### ISSUE THREAD

**Issue by daisy0123** [antvis/G6#4726]
### Describe the bug

当前使用的布局是
 type: "dagre", rankdir: "LR", align: "UL", controlPoints: true, nodesep: 10, ranksep: 50,
当使用addItem 添加节点后，节点不是根据新增节点的source起点绘制，而是在容器的开头绘制了。
![image](https://github.com/antvis/G6/assets/11910330/839e7b32-d181-4008-99d7-547b9d4f0622)

demo地址：https://codesandbox.io/s/keen-wilbur-h96u4n?file=/index.js 麻烦帮忙看看，这个之前有g6的同事帮忙解决了，目前4.6.18版本是没有问题的，但是新版本有问题，应该是4.6.18版本的代码没有更新到最新版本

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

如上

### Expected behavior

希望不要错乱，希望是如图下：
![image](https://github.com/antvis/G6/assets/11910330/83da09e5-2fea-48eb-9855-5756007e9580)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
addItem 完后，调用重新布局 graph.layout

**Comment by daisy0123** [comment]
> addItem 完后，调用重新布局 graph.layout

![image](https://github.com/antvis/G6/assets/11910330/89ee354d-340e-4ee9-b623-de2d365c68aa)
有调用重新布局 graph.layout，demo地址：https://codesandbox.io/s/keen-wilbur-h96u4n?file=/index.js
