### ISSUE TITLE
如何定义一个（圆角平行四边形的）combo，他的大小和位置由内部的元素的分布决定。

### ISSUE THREAD

**Issue by 584sentiment** [antvis/G6#4728]
### 问题描述

我通过自定义布局已经设置好了各个节点的位置，我想让自定义的combo根据节点布局去显示，这样我不用去关注combo的位置和宽高。但是我自定义combo不能自动包裹住所有节点。

### 重现链接

无

### 重现步骤

无

### 预期行为

我期望看到combo完全包裹住内部的元素，并且根据元素的位置显示。但是实际上combo的宽高都丢失了

### 平台

- 操作系统: Windows
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
给个在线复现 demo 看看

**Comment by 584sentiment** [comment]
该问题已经解决，一开始我想在drawShape方法中去得到combo内部元素的包围盒，但是不知道如何获取，后来在update（afterUpdate也行）中通过`combo._cfg.model.style`获取到了元素撑开之后的combo宽高。已经解决了我的需求

**Comment by Rongbbbb** [comment]
> 该问题已经解决，一开始我想在drawShape方法中去得到combo内部元素的包围盒，但是不知道如何获取，后来在update（afterUpdate也行）中通过`combo._cfg.model.style`获取到了元素撑开之后的combo宽高。已经解决了我的需求

有代码看下嘛，遇到了同样问题
