### ISSUE TITLE
折线是错乱的

### ISSUE THREAD

**Issue by hezhongfeng** [antvis/G6#4730]
### 问题描述

根据例子中的“决策树2”进行改造样式，结果折现不符合预期
data在左右对称的时候没有问题，但是数据是变化的，折线不符合预期

### 重现链接

https://codesandbox.io/s/distracted-tereshkova-sjwn2q?file=/index.js

### 重现步骤

直接显示

### 预期行为

折现不需要绕圈

### 平台

- 操作系统: [macOS,]
- 网页浏览器: [Google Chrome,]
- G6 版本: [4.8.19 ]

### 屏幕截图或视频（可选）

<img width="736" alt="image" src="https://github.com/antvis/G6/assets/12163050/b2d190c3-a76e-4286-b495-25a81d5c1ca3">

**Comment by hezhongfeng** [comment]
<img width="450" alt="image" src="https://github.com/antvis/G6/assets/12163050/0a3d3fb5-ccf1-48f4-8ebf-1df26ee7ec8c">

**Comment by Yanyan-Wang** [comment]
自定寻径不一定符合预期，可以使用这个自定义边，简单的控制点逻辑：https://g6.antv.antgroup.com/zh/examples/item/customEdge/#customPolyline2

**Comment by hezhongfeng** [comment]
好的，谢谢
