### ISSUE TITLE
使用updateChildren更新子节点会导致画布位移

### ISSUE THREAD

**Issue by 799531161** [antvis/G6#4731]
### 问题描述

使用updateChildren更新子节点会导致画布位移，如果我用graph.focusItem不是原来得画布位置
使用graph.focusItem(model.id, true)配合graph.getGroup().setMatrix(getMatrix);有一瞬间得画布拖拉感觉，如果解决

### 重现链接

https://

### 重现步骤

点击节点使用updateChildren更新子树

### 预期行为

画布发生严重位移，期望画布位置保持点击时得

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
给个在线复现demo？
