### ISSUE TITLE
初始化节点过多的时候TreeGraph.innerAddChild报错

### ISSUE THREAD

**Issue by DragonKing686** [antvis/G6#4732]
### 问题描述

第二层节点有20个，使用树布局，节点是自定义的图片，渲染的时候报错
![image](https://github.com/antvis/G6/assets/76863764/4b761d7d-e416-4466-8a2a-44e2f4cac236)

### 重现链接

https://codesandbox.io/s/vigilant-wind-pkyx7s?file=/src/App.js

### 重现步骤

data的第二层有20个

### 预期行为

能够正常渲染

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by GemT27** [comment]
A11节点重复了,在A1的children中
