### ISSUE TITLE
子级Combo收缩或者展开时父级Combo包裹范围异常

### ISSUE THREAD

**Issue by youbins** [antvis/G6#4734]
### 问题描述

问题：
1、子级Combo右键展开或者收缩后，其上级Combo包裹范围异常。
2、事件aftercollapseexpandcombo实际调用时机不对，如：
Combo右键点击展开/收缩分组，aftercollapseexpandcombo事件实际上在Combo没展开/收缩的时候就已经执行了。
![image](https://github.com/antvis/G6/assets/22154447/1e88f001-b17d-4f17-9047-bbab75a5b1fb)

### 重现链接

https://codesandbox.io/s/vigilant-chaum-4yv27v?file=/index.js:4898-4922

### 重现步骤

1、进入页面右键Combo3，点击展开分组。
2、右键Combo3，点击收缩分组。

### 预期行为

1、右键Combo3，点击展开分组后，Combo1能够包裹住Combo3。
2、右键Combo3，点击收缩分组后，Combo1能够在Combo3收缩后，缩写包裹范围。

### 平台

- 操作系统: Windows
- 网页浏览器: Google Chrome
- G6 版本: latest

**Comment by Yanyan-Wang** [comment]
先锁一下版本 4.8.3。 我修复一下

**Comment by Yanyan-Wang** [comment]
4.8.20 已修复
