### ISSUE TITLE
自定义 Combo 无法绘画边界半径的 rect 和 加载网络上的图片

### ISSUE THREAD

**Issue by CodesAreHonest** [antvis/G6#4735]
### 问题描述

如题，自定义 Combo 无法绘画拥有边界半径 (border radius) 的 rect 和 image 无法加载网络上的图片

### 重现链接

https://codesandbox.io/s/g6-rect-image-bug-llsyzw?file=/src/register-combo.ts

### 重现步骤

1. 进入重现链接
2. 打开 register-combo.ts 文件

### 预期行为

1. 我期望绘画拥有边界半径的 rect, 可是 rect 的边角并没有实现圆角
2. 我期望 image 现实网络上的图片，可是 browser console 显示 CORS 的问题。

### 平台

- 操作系统: 全部
- 网页浏览器: 全部
- G6 版本: 4.8.17

### 屏幕截图或视频（可选）

![Screenshot 2023-07-12 at 8 27 39 PM](https://github.com/antvis/G6/assets/25884538/df9a3587-2251-42ab-8441-90b35b7c75d6)

**Comment by ravengao** [comment]
rect的边界半径不是由rx/ry来决定的，而是`radius`
```
group.addShape("rect", {
     attrs: {
          radius: 20,
          // rx: 20, won't work
          // ry: 20, won't work
         ...
```

**Comment by CodesAreHonest** [comment]
> rect的边界半径不是由rx/ry来决定的，而是`radius`

感谢！

---

关于图片方面的问题，请问有什么建议让用户可以根据图片链接显示图片吗？

**Comment by CodesAreHonest** [comment]
> rect的边界半径不是由rx/ry来决定的，而是`radius`

感谢！

**Comment by Yanyan-Wang** [comment]
你 demo 中的图片链接直接访问也访问不到呀，你要给能访问的地址，比如 https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*wkIaQ43O3ssAAAAAAAAAAAAADmJ7AQ/original 就能访问到

**Comment by Yanyan-Wang** [comment]
另外就是你注册的自定义 combo 类型没有配置到图上，defaultCombo: { type: 'custom-combo' }

**Comment by CodesAreHonest** [comment]
@Yanyan-Wang  都明白了，非常感谢。
