### ISSUE TITLE
存在combo时，edge图层为什么会在node之上呢

### ISSUE THREAD

**Issue by zhang-yanglong** [antvis/G6#4738]
### Describe the bug

graph配置中开启linkCenter
在有combo的情况下，edge线条的图层在node节点（节点不在combo中）之下
而没有combo的情况下，edge线条的的图层却在node节点（节点不在combo中）之上
按教程中Group处说的，https://antv-g6.gitee.io/zh/docs/manual/middle/elements/shape/graphics-group
nodeGroup图层应该保持比edgeGroup图层更高才对

### Your Example Website or App

https://g6.antv.antgroup.com/examples/item/defaultCombos/#rect

### Steps to Reproduce the Bug or Issue

import G6 from '@antv/g6';

const data = {
  nodes: [
    {
      id: 'node1',
      size: 40,
    },
    {
      id: 'node2',
      size: 40,
    },
  ],
  combos: [
    {
      id: 'combo',
      label: 'Combo',
    },
  ],
  edges: [
    {
      source: 'node1',
      target: 'node2',
    },
  ]
};

const width = document.getElementById('container').scrollWidth;
const height = document.getElementById('container').scrollHeight || 500;
const graph = new G6.Graph({
  container: 'container',
  width,
  height,
  fitCenter: true,
  groupByTypes: false,
  modes: {
    default: ['drag-canvas', 'drag-node', 'drag-combo'],
  },
  linkCenter: true,
});

graph.data(data);
graph.render();

### Expected behavior

![image](https://github.com/antvis/G6/assets/46065599/31f5b4e0-87bc-420f-a2b5-a762942d9d5a)
![image](https://github.com/antvis/G6/assets/46065599/a0982cca-f842-4767-a0fb-28816d582ef3)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by GemT27** [comment]
节点配置comboId下看看呢

**Comment by youbins** [comment]
遇到同样的问题，未解决！
![动画](https://github.com/antvis/G6/assets/22154447/ce993432-c58c-4449-8578-f5f559257380)
https://codesandbox.io/s/bold-sun-49z5tw?file=/index.js

**Comment by MusicTen** [comment]
使用combo布局，combo 图上节点、边、combo 的层级符合常规逻辑，需要将 groupByTypes 设置为 false。导致节点的nodeGroup 和边的 edgeGroup 不存在。所有节点和边在同一个分组，它们的层级根据生成的顺序决定。
参考：[节点与边的层级](https://g6.antv.antgroup.com/manual/middle/elements/methods/element-index#%E5%8F%82%E6%95%B0%E6%8F%8F%E8%BF%B0)
