### ISSUE TITLE
如何用addItem添加自定义节点

### ISSUE THREAD

**Issue by neolee6053** [antvis/G6#4741]
### 问题描述

G6.registerNode( 'aggregated-node',{});
graph.addItem('aggregated-node', {})；

有什么办法可以加自定义节点？难道一定要changeData()才可以？ 

参考
https://g6.antv.antgroup.com/en/examples/case/graphDemos#largeGraph
https://g6.antv.antgroup.com/en/examples/case/graphDemos#simplifyCluster

### 重现链接

https://codesandbox.io/s/new

### 重现步骤

如上

### 预期行为

如上

### 平台

- 操作系统: [ Windows]
- 网页浏览器: [Firefox]
- G6 版本: [4.8.15 ]

**Comment by GemT27** [comment]
graph.addItem('node', {type: 'aggregated-node'});

**Comment by neolee6053** [comment]
> graph.addItem('node', {type: 'aggregated-node'});

我觉得我笨了
