### ISSUE TITLE
提问：redo和undo只能通过toolbar调用吗？

### ISSUE THREAD

**Issue by Wang-yubo** [antvis/G6#4742]
### 问题描述

redo和undo只能通过toolbar调用吗？graph实例方法没找到对应的方法

### 重现链接

http://g6.antv.antgroup.com/api/plugins#toolbar

### 重现步骤

无

### 预期行为

期望可以使用graph.redo()和graph.undo();

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

无

### 补充说明（可选）

没有new toolbar的需求，但是期望可以使用redo和undo

**Comment by GemT27** [comment]
加键盘快捷键呢

**Comment by Yanyan-Wang** [comment]
可以调用 toolbar 实例的 redo undo 方法。或者按照它的实现来写自己的 redo undo

https://github.com/antvis/G6/blob/36708955bd53f6cf79e4a78cf0654e01df95a031/packages/plugin/src/toolBar/index.ts#L334

**Comment by Wang-yubo** [comment]
> 

明白了，已经实现了，感谢。
