### ISSUE TITLE
能否通过修改 edgeStateStyles 来 修改 edge-label 的样式

### ISSUE THREAD

**Issue by bmw-0101** [antvis/G6#4744]
### 问题描述

![image](https://github.com/antvis/G6/assets/70594427/d1bdd95b-2fad-4f3a-905c-d6fb9e22fef6)
无效写法

### 重现链接

无

### 重现步骤

无

### 预期行为

能够修改 edge-label 成透明度

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
https://g6.antv.antgroup.com/manual/advanced/state-new#%E5%AE%9A%E4%B9%89%E7%8A%B6%E6%80%81

可以，子图形状态样式。内置的边 label 图形名为：text-shape
