### ISSUE TITLE
拖拽画布时出现没有清除的数据

### ISSUE THREAD

**Issue by tipsxBase** [antvis/G6#4746]
### Describe the bug

G6版本^4.8.14
使用的是自定义布局，拖拽画布时会出现这种情况
![image](https://github.com/antvis/G6/assets/16009561/32954bb2-b1bd-4715-83bb-38ba23de9464)

### Your Example Website or App

暂无

### Steps to Reproduce the Bug or Issue

当大数量大的时候就会出现

### Expected behavior

拖拽时可以正常展示

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by tipsxBase** [comment]
自定义布局，自定义节点，自定义边

**Comment by Yanyan-Wang** [comment]
给个在线复现 demo，大概率是数据有重复 id，或非 string id

**Comment by tipsxBase** [comment]
https://stackblitz.com/edit/stackblitz-starters-dszk1p?file=src%2FDataLineage%2Flib%2FDataLineage.ts

**Comment by tipsxBase** [comment]
> 给个在线复现 demo，大概率是数据有重复 id，或非 string id

https://stackblitz.com/edit/stackblitz-starters-dszk1p?file=src%2FDataLineage%2Flib%2FDataLineage.ts

**Comment by tipsxBase** [comment]
麻烦帮忙看看

**Comment by tipsxBase** [comment]
初步排查了一下，连边的时候如果边的sourceAnchor 是 'sort' 时。会导致 startPoint 变成 sort 函数

**Comment by tipsxBase** [comment]
> 加个这个呢 `this.graph.get('canvas').set('localRefresh', false);`

这个是可以解决问题，但是我在调试时发现是由于那个startAnchor = sort导致的，如果我把sort修改成别的就不会有问题
