### ISSUE TITLE
@ant-design/charts 中使用关系图配置 scroll-canvas 后 鼠标滚轮不能滚动页面

### ISSUE THREAD

**Issue by lanxiaojia** [antvis/G6#4749]
### 问题描述

import { DecompositionTreeGraph } from '@ant-design/charts';

// 配置
 behaviors: [
      'drag-canvas',
      {
        type: 'scroll-canvas',
        scalableRange: -0.9,
      },
    ],

开启  scroll-canvas  只能在画布上进行滚动，滚到顶部时不能自动切换成滚动页面

### 重现链接

https://codesandbox.io/s/mystifying-sunset-ncnwpv?file=/index.js

### 重现步骤

import { DecompositionTreeGraph } from '@ant-design/charts';

// 配置
 behaviors: [
      'drag-canvas',
      {
        type: 'scroll-canvas',
        scalableRange: -0.9,
      },
    ],

开启  scroll-canvas  只能在画布上进行滚动，滚到顶部时不能自动切换成滚动页面

### 预期行为

在画布滚动到顶部后 自动切换开始滚动页面

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

操作系统:  macOS

 网页浏览器: Google Chrome,

"@ant-design/charts": "^1.4.2"

**Comment by Yanyan-Wang** [comment]
因为画布上的滚轮事件禁止了默认事件 evt.preventDefault()

如果你需要到顶部或底部的时候，开始响应默认事件，可以自己给 canvas dom 绑定滚轮监听

**Comment by lanxiaojia** [comment]
> 因为可用性上的滚轮事件禁止了违约事件 evt.preventDefault()
> 
> 如果你需要到顶部或底部的时候，开始响应默认事件，可以自己给canvas dom绑定滚轮监听
好的 感谢 我先去试试

**Comment by lanxiaojia** [comment]
@Yanyan-Wang 你好，我这边试了下，没太成功。
