### ISSUE TITLE
演示实例点击后报错 

### ISSUE THREAD

**Issue by kekezjqqqqq** [antvis/G6#4752]
### Describe the bug

![image](https://github.com/antvis/G6/assets/137025257/a4e1282b-ad34-4e9e-8453-de4efcb3f3e1)
上图点击之后出现如下报错
![image](https://github.com/antvis/G6/assets/137025257/ca6e2658-2e8c-4153-945c-a584d099051c)

### Your Example Website or App

谷歌

### Steps to Reproduce the Bug or Issue

![image](https://github.com/antvis/G6/assets/137025257/a4e1282b-ad34-4e9e-8453-de4efcb3f3e1)
上图点击之后出现如下报错
![image](https://github.com/antvis/G6/assets/137025257/ca6e2658-2e8c-4153-945c-a584d099051c)

### Expected behavior

![image](https://github.com/antvis/G6/assets/137025257/a4e1282b-ad34-4e9e-8453-de4efcb3f3e1)
上图点击之后出现如下报错
![image](https://github.com/antvis/G6/assets/137025257/ca6e2658-2e8c-4153-945c-a584d099051c)

### Platform

- OS:Windows
- Browser: Chrome
- Version: [e.g. 91.1]

**Comment by Aarebecca** [comment]
暂未发现相关问题
