### ISSUE TITLE
小地图minimap可以添加点击事件，点击到哪视图自动移动到哪里

### ISSUE THREAD

**Issue by xiaozhanghui** [antvis/G6#4753]
### 问题描述

可以实现吗

### 重现链接

可以实现吗

### 重现步骤

可以实现吗

### 预期行为

可以实现吗

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by jia-zh** [comment]
期待更新
