### ISSUE TITLE
页面卡顿

### ISSUE THREAD

**Issue by CodingJzy** [antvis/G6#4757]
### 问题描述

打开页面，控制台会这个消息会一直变多，而且刷的很快，然后页面会很卡，掉帧，即使我离开了这个页面，也会卡。刷新也会。除非打开一个新的页面
![image](https://github.com/antvis/G6/assets/44855157/6a82242c-3e2a-4bcf-b9b6-3f8a0c1a51ba)

### 重现链接

1

### 重现步骤

1

### 预期行为

1

### 平台

- 操作系统: Windows, Linu
- 网页浏览器: Google Chrome、edge

### 屏幕截图或视频（可选）

1

### 补充说明（可选）

1

**Comment by hustcc** [comment]
有具体的最小复现 DEMO 吗？不然没有办法复现和调试。
