### ISSUE TITLE
入门教程里插件与工具项里的Image MinimapGIF出错了，和tooltip 节点提示框的GIF一样了。

### ISSUE THREAD

**Issue by zhulandashuiguai** [antvis/G6#4759]
### 问题描述

入门教程里插件与工具项里的Image Minimap演示GIF出错了，和tooltip 节点提示框的GIF一样了，我不知道Image Minimap是什么样的。

### 重现链接

https://g6.antv.antgroup.com/manual/tutorial/plugins

### 重现步骤

1.就在现在的官网文档入门教程里

### 预期行为

我期望看到Image Minimap的正确演示GIF，而不是和tooltip 节点提示框一样的演示GIF，还是说这两者是一样的？

### 平台

- 操作系统:  Windows
- 网页浏览器: Google Chrome
- G6 版本: 最新网页版文档

### 屏幕截图或视频（可选）

<img width="515" alt="image" src="https://github.com/antvis/G6/assets/91361410/884bc0a3-be13-49a6-9562-31816dcbe303">
<img width="515" alt="image" src="https://github.com/antvis/G6/assets/91361410/2ec328cc-c5ef-4088-83af-5d9404d24f94">

### 补充说明（可选）

只是看入门教程时看到这两个案例让我感到疑惑。

**Comment by Yanyan-Wang** [comment]
嗷，感谢报告，我们会尽快改掉。这个效果应该和上面普通的 minimap 一样。不过 image minimap 要求提前给好静态图片
