### ISSUE TITLE
mindmap中label文本方向的问题

### ISSUE THREAD

**Issue by pycodev** [antvis/g6#476]
* **G6 Version**: 2.1.1-beta
* **Platform**: mac
* **Mini Showcase(like screenshots)**: null
* **CodePen Link**: null

你好，我在用g6中的tree和minmap布局写一个 思维导图。

开始是参考demo中的实现，label文本的方向是根据 与父节点坐标比较以判断左右 调用`label.translate`将文本偏移、。该部分逻辑位于`afterchange`事件的回调中。

但因为我的应用的功能中包含 *缩放*
这个实现遇到了问题：**当缩放后不回触发`afterchange`事件，导致文本位置失效**。

考虑过将 设置label位置 的逻辑放到`afterdraw`生命周期里，但是该周期中无法获得坐标，故无法判断节点在左边还是右边。

`labelOffsetX`只会接收到 model，似乎也不行。

虽然似乎可以在缩放事件的相关回调中，再调用该逻辑，但是这样就太被动了。

--------

基于以上，希望可以指导下解决方案。

谢谢 ：）

**Comment by TomHuangCN** [comment]
这里可能用 `afterlayout` 时间更合理一点。

> 当缩放后不回触发afterchange事件，导致文本位置失效。

这句话没懂

加 minimap 我大概写了下
