### ISSUE TITLE
如何复制节点文本？

### ISSUE THREAD

**Issue by huihui925** [antvis/G6#4767]
### 问题描述

请问如何复制节点文本？g6支持复制功能吗？

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by guoliuqing123** [comment]
我是这样写的复制功能                 let model = [item.getModel()];
                that.ctrlcModel = JSON.parse(JSON.stringify(model));                
that.$message.success('复制成功');

**Comment by guoliuqing123** [comment]
然后取  that.ctrlcModel[0].label

**Comment by Yanyan-Wang** [comment]
监听点击事件，然后拿到正在被点击的节点 label，然后用前端常规的方式复制就好
