### ISSUE TITLE
with node-label of selected of nodeStateStyles has unexpected error when change state

### ISSUE THREAD

**Issue by cdx111** [antvis/G6#4770]
### Describe the bug

with node-label of selected of nodeStateStyles has unexpected error when change state
<img width="619" alt="image" src="https://github.com/antvis/G6/assets/39432333/29a8bcdf-8595-44aa-b965-761b0a4636f0">

### Your Example Website or App

https://stackblitz.com/edit/react-iungh6?file=index.js,index.html

### Steps to Reproduce the Bug or Issue

select a node then other will happen error

### Expected behavior

normally change state

### Platform

- OS: macOS
- Browser:Chrome
- Version: 115.0.5790.114

**Comment by Yanyan-Wang** [comment]
Use 'text-shape' instead of 'node-label'. It is the name of the label text shape, which is no good specification for the shapes' naming, and makes users confuse.

Since this might be a breaking change, we are trying to avoid this problem in v5.
