### ISSUE TITLE
IE11下语法错误，导致白屏

### ISSUE THREAD

**Issue by gaolongge** [antvis/G6#4771]
### 问题描述

使用G6的时候，在IE报错；参照https://g6.antv.antgroup.com/manual/faq/support-ie配置后，还是无法转化G6包里面d3-color.js的模版语法。 
版本："@antv/g6": "^4.7.16"
错误如下：
![IMG_5605](https://github.com/antvis/G6/assets/24975204/ec9395e2-67d7-41ef-85dd-3eae1b87b765)
![IMG_5606](https://github.com/antvis/G6/assets/24975204/953903ce-01b0-4aef-977f-baeff66eb437)
求解，如何使用babel编译里面的包？

### 重现链接

https

### 重现步骤

使用G6的时候，
打包后，在IE报错；参照https://g6.antv.antgroup.com/manual/faq/support-ie配置后，还是无法转化G6包里面d3-color.js的模版语法。 
版本："@antv/g6": "^4.7.16"
错误如下：
![IMG_5605](https://github.com/antvis/G6/assets/24975204/ec9395e2-67d7-41ef-85dd-3eae1b87b765)
![IMG_5606](https://github.com/antvis/G6/assets/24975204/953903ce-01b0-4aef-977f-baeff66eb437)
求解，如何使用babel编译里面的包？

### 预期行为

希望兼容IE11

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
IE 下线了～～不再考虑支持
