### ISSUE TITLE
自定义节点使用了setstate方法后，之前设置的样式全部失效了

### ISSUE THREAD

**Issue by wSh-zm** [antvis/G6#4774]
### 问题描述

自定义节点使用了setstate方法后，之前设置的样式全部失效了

### 重现链接

无

### 重现步骤

无

### 预期行为

自定义节点setstat方法只对方法中单独设置的样式更改

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
不是很明白问题，请给个在线复现的 demo 吧
