### ISSUE TITLE
combo 收起状态节点 edge 宽度展示问题

### ISSUE THREAD

**Issue by MusicTen** [antvis/G6#4776]
### Describe the bug

combo 收起状态下，两个combo间的edge连线宽度展示过粗。

### Your Example Website or App

https://g6.antv.antgroup.com/zh/examples/interaction/combo/#rect

### Steps to Reproduce the Bug or Issue

// 调整 edges 连线宽度
edges: [
    { source: 'node1', target: 'node2',size: 2 },
    { source: 'node1', target: 'node3', size: 10 },
    { source: 'combo1', target: 'node3', size: 8 },
],

### Expected behavior

收起 combo1，combo1 与 combo3 的连线展示过粗。

### Screenshots or Videos

![image](https://github.com/antvis/G6/assets/37668403/1999377c-7db6-466b-9639-0a06f354b2f5)

### Platform

- OS: [macOS]
- Browser: [Chrome]
- Version: [115.0.5790.114]

**Comment by bsansone** [comment]
Set the edge style lineWidth to 1:

```
defaultEdge: {
    style: {
      lineWidth: 1,
    }
},
  ```

**Comment by MusicTen** [comment]
> Set the edge style lineWidth to 1:
> 
> ```
> defaultEdge: {
>     style: {
>       lineWidth: 1,
>     }
> },
> ```
