### ISSUE TITLE
官网提供的拖动事件，拖动到画布外，拖动就异常了

### ISSUE THREAD

**Issue by Tina75** [antvis/G6#4780]
### 问题描述

1、g6提供的拖动事件'drag-node'
2、自己写拖动事件
都存在拖动到画布外，拖动就有一场：节点会一直跟着鼠标或者会拖动页面其他元素
一下给的例子是官网实例

### 重现链接

https://g6.antv.antgroup.com/zh/examples/net/forceDirected/#basicForce2

### 重现步骤

1、进入页面
2、拖动任意节点到画布外，画布外元素被选中后
3、拖动其他画布内的节点  问题1：画布外别的元素被拖动   问题2：节点拖动一场，节点会一直跟着鼠标，无法停止

### 预期行为

我期望看到节点正常拖动，但是现在拖动异常：问题1：画布外别的元素被拖动   问题2：节点拖动一场，节点会一直跟着鼠标，无法停止

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

https://github.com/antvis/G6/assets/26056312/8706a3c3-b77f-4c19-9f23-edc2d31e7c75

**Comment by ZhOUCFff** [comment]
给canvas的外层容器添加css：
`user-select:none`

**Comment by Tina75** [comment]
> 给canvas的外层容器添加css： `user-select:none`

优秀，解决了
