### ISSUE TITLE
自定义circle更新半径后，边的箭头如何更新位置？

### ISSUE THREAD

**Issue by ouzhou** [antvis/G6#4789]
### 问题描述

使用G6.registerNode定义了一个不继承任何图形的类型，返回一个circle keyShape
```
const nodes = graph.getNodes();
nodes.forEach(node=>{  node.attr({ r: 20 }) })
```
使用 node.attr({ r: 20 })后，圆的大小确实更新了，但是bbox没有更新，导致边的箭头没更新，就产生了错误的表现

### 重现链接

https://codesandbox.io/s/new?file=/src/App.js

### 重现步骤

点击更新按钮

### 预期行为

边的箭头应该指向圆的边缘

### 平台

- 操作系统: [macOS.]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.5.1]

**Comment by Yanyan-Wang** [comment]
不要这样更新图形样式哈，通过 graph.updateItem 来更新节点大小配置 https://g6.antv.antgroup.com/api/graph-func/item#graphupdateitemitem-model-stack

节点配置项：https://g6.antv.antgroup.com/manual/middle/elements/nodes/default-node
