### ISSUE TITLE
是否有接口可以设置全局的配置

### ISSUE THREAD

**Issue by 584sentiment** [antvis/G6#4790]
### 问题描述

在我的项目中有四个tab页，他们使用了同一个graph实例，但是他们使用的布局、节点类型、combo、边都不相同。除了初始化graph可以指定layout、defaultNode、defaultCombo外，还有其他方法可以去更新或者修改元素的相关类型吗？
如果没有的话？通过遍历元素，去给每一个节点添加type来指定元素的类型和使用新的layout、defaultNode、defaultCombo重新new 一个graph实例更推荐哪一个呢？

### 重现链接

无

### 重现步骤

无

### 预期行为

我希望能够直接设置我要渲染的所有节点的type，但是只能一个一个设置

### 平台

- 操作系统:  Windows
- 网页浏览器: Google Chrome
- G6 版本: 4.8.10

**Comment by Yanyan-Wang** [comment]
布局更新 graph.updateLayout
节点更新 单独更新 graph.updateItem

但是为什么四个 tab 页不能用四个 graph 实例呢？

**Comment by 584sentiment** [comment]
你的意思是更推荐new一个新的graph实例，通过defaultNode、defaultcombo来指定各个元素类型和配置，然后传递数据进行渲染吗？

**Comment by Yanyan-Wang** [comment]
嗯嗯，是的，defaultNode、defaultcombo 是全局配置，也可以给单个数据单独做一些配置
