### ISSUE TITLE
钉钉二维码失效了

### ISSUE THREAD

**Issue by chuangfengdehua** [antvis/G6#4792]
### 问题描述

editor g6 不可以设置单个连接节点，还有默认的连接节点样式

### 重现链接

https://stackblitz.com

### 重现步骤

editor g6 可以像 g6一样编辑

### 预期行为

editor g6 可以像 g6一样编辑

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
g6-editor 吗，已经没有在维护了，如果旧文档里没有的话，应该就是没有～ 强烈建议升级到新版 G6
