### ISSUE TITLE
Timebar 支持自定义的过滤 function 吗？

### ISSUE THREAD

**Issue by neolee6053** [antvis/G6#4794]
### 问题描述

当前timebar似乎能够隐藏或显示符合条件的边，但无法过滤边的数据。
例如，当我移动timebar时，边的数 (count) 会不同, 如何办到呢？
因为我的数据里，不同的时间，边的label (count) 会增加或减少。
https://codesandbox.io/s/rytqxm?file=/index.js

如果我华语不够好
the current timebar seems to able to hide or show the edge that matches the condition, but it cannot filter the data of the edge. 
for example, i want to achieve so that when i move the timebar, the count of the edge will be different. how can i do that

### 重现链接

https://codesandbox.io/s/rytqxm?file=/index.js

### 重现步骤

如上

### 预期行为

如上

### 平台

- 操作系统: [ Windows]
- 网页浏览器: [Firefox]
- G6 版本: [4.8.15 ]

**Comment by Yanyan-Wang** [comment]
Try `filterItemTypes` and config it with  ['node', 'edge']

https://g6.antv.antgroup.com/en/api/plugins#timebar

**Comment by neolee6053** [comment]
我的意思是改变边上的数，而不是直接隐藏整条边。
![image](https://github.com/antvis/G6/assets/135953327/ef1a5825-9e4f-4f5c-929e-70923d48d825)
