### ISSUE TITLE
我这边出现了类似的问题，当我第一次进入时使用的布局是通过pipes配置了两种grid布局，切换布局后使用的是全部采用concentric。但是出现的问题是当我切换到concentric布局后，依然有一部分节点按照pipes[1]中的布局方式进行布局。

### ISSUE THREAD

**Issue by XiaoRIGE** [antvis/G6#4801]
我这边出现了类似的问题，当我第一次进入时使用的布局是通过pipes配置了两种grid布局，切换布局后使用的是全部采用concentric。但是出现的问题是当我切换到concentric布局后，依然有一部分节点按照pipes[1]中的布局方式进行布局。

_Originally posted by @XiaoRIGE in https://github.com/antvis/G6/issues/4162#issuecomment-1670606505_

**Comment by Yanyan-Wang** [comment]
给个在线复现 demo 呢
