### ISSUE TITLE
自定义节点后，点击node不能收缩

### ISSUE THREAD

**Issue by jinkin1995** [antvis/G6#4804]
### 问题描述

自定义节点后，点击node不能收缩

### 重现链接

https://codesandbox.io/s/zealous-surf-52nj6p?file=/src/App.vue

### 重现步骤

注册自定义节点，
type使用该节点

### 预期行为

期望看到跟没有使用自定义节点那样正常收缩

### 平台

- 操作系统: macOS
- 网页浏览器: Chrome
- G6 版本: 4.8.21

**Comment by Yanyan-Wang** [comment]
DOM 类型的图形不能接收 G6 的各种事件，这里的自定义节点也不复杂，建议使用 canvas 的 circle 代替。
