### ISSUE TITLE
menu高度过高，显示会被遮挡

### ISSUE THREAD

**Issue by Tina75** [antvis/G6#4806]
### 问题描述

右击显示菜单时，菜单内容过高，内容会被遮挡

### 重现链接

https://g6.antv.antgroup.com/examples/tool/contextMenu/#contextMenu

### 重现步骤

1、进入页面
2、getContent方法，让Li多显示几条，例：如下
getContent(evt) {
    let header;
    if (evt.target && evt.target.isCanvas && evt.target.isCanvas()) {
      header = 'Canvas ContextMenu';
    } else if (evt.item) {
      const itemType = evt.item.getType();
      header = `${itemType.toUpperCase()} ContextMenu`;
    }
    return `
    <h3>${header}</h3>
    <ul>
      <li title='1'>li 1</li>
      <li title='2'>li 2</li>
      <li>li 3</li>
      <li>li 4</li>
      <li>li 5</li>
      <li title='1'>li 1</li>
      <li title='2'>li 2</li>
      <li>li 3</li>
      <li>li 4</li>
      <li>li 5</li>
      <li title='1'>li 1</li>
      <li title='2'>li 2</li>
      <li>li 3</li>
      <li>li 4</li>
      <li>li 5</li>
      <li title='1'>li 1</li>
      <li title='2'>li 2</li>
      <li>li 3</li>
      <li>li 4</li>
      <li>li 5</li>
    </ul>`;
  },
3、右键显示菜单,每个节点都右键试一下，基本上是必现的

### 预期行为

菜单不被遮挡，或者css中top是负数时，用户可以有入口，改变tup的值

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![image](https://github.com/antvis/G6/assets/26056312/89008902-338c-49ed-91a6-c71aac41a978)

**Comment by Tina75** [comment]
预期行为，有个错别字，菜单不被遮挡，或者css中top是负数时，用户可以有入口，改变top的值

**Comment by Yanyan-Wang** [comment]
确实有这个问题，看看有没有社区的朋友愿意来贡献一下

**Comment by Tina75** [comment]
> 确实有这个问题，看看有没有社区的朋友愿意来贡献一下

这个什么时间能修复呢，可以给个大概时间嘛

**Comment by hipi** [comment]
#4942

**Comment by Yanyan-Wang** [comment]
@hipi  牛哇，已经合并并发版：v4.8.22 @Tina75
