### ISSUE TITLE
dagre布局如何实现折叠/展开子节点

### ISSUE THREAD

**Issue by donghuizhou** [antvis/G6#4808]
### 问题描述

目前项目中需要dagre布局中，若节点有下一级，则在节点右边渲染个按钮，可展开/折叠下一级，请问如何实现

### 重现链接

none

### 重现步骤

none

### 预期行为

如上所述

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
这个展开收起并不能像树图那样简单，例如和节点 A 同级节点 B，C 是 A 的下一层级节点，但是 C 和 B 有边，那么理论上点击 A 就不能收起 C。可以重新考虑一下这个需求看看

**Comment by zyh0yh** [comment]
可以自己编写一个查找一个节点的链路方法，查找到这个节点所有相关的链接，然后动态控制链路里的节点显隐来达到折叠/展开的效果，参考代码如下：

**Comment by seifenk** [comment]
> 这个展开收起并不能像树图那样简单，例如和节点 A 同级节点 B，C 是 A 的下一层级节点，但是 C 和 B 有边，那么理论上点击 A 就不能收起 C。可以重新考虑一下这个需求看看

同样有这个需求
