### ISSUE TITLE
force2 未支持 nodeSpacing 参数

### ISSUE THREAD

**Issue by baranwang** [antvis/G6#4809]
### Describe the bug

force2 未支持 nodeSpacing 参数

### Your Example Website or App

https://stackblitz.com/edit/react-nv6psf?file=index.js

### Steps to Reproduce the Bug or Issue

增加 nodeSpacing 配置，未生效

### Expected behavior

配置生效

### Platform

- OS: macOS
- Browser: Chrome
- Version: 4.8.21

**Comment by Yanyan-Wang** [comment]
好像确实没有真正使用到这个配置，后面更新一下。你这里有什么需求因为这个满足不了的么

**Comment by baranwang** [comment]
内部设计规范中有要求节点的间距，但是设置了没生效，我看文档说 force2 会比 force 的效率高，所以是想用 force2 作为布局的

**Comment by Axpeykie** [comment]
现在是2023年10月31日。这个属性得到支持了吗？ @Yanyan-Wang
