### ISSUE TITLE
定义registerEdge边为流动效果，在shape: 'polyline-round'失效

### ISSUE THREAD

**Issue by wlc534** [antvis/g6#481]
* **G6 Version**:2.1.2
* **Platform**:Mac OS
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

G6.registerEdge('flowingEdge', {
  afterDraw: function afterDraw(item) {
    var keyShape = item.getKeyShape();
    keyShape.attr('lineDash', [10, 10]);
    keyShape.attr('lineDashOffset', 0);
    keyShape.animate({
      lineDashOffset: -20,
      repeat: true
    }, 500);
  }
});
https://antv.alipay.com/zh-cn/g6/1.x/demo/flow/work-flow.html

**Comment by TomHuangCN** [comment]
请附上示例片段
https://codepen.io/DoriTong/pen/pKbLVw
