### ISSUE TITLE
卡顿，60个节点。有动画有锚点

### ISSUE THREAD

**Issue by 539917729** [antvis/G6#4818]
### 问题描述

节点上加了7个image、rect、circle 还有动画

### 重现链接

无

### 重现步骤

无

### 预期行为

我从哪些方面去做性能优化

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.6.4 ]

**Comment by 539917729** [comment]
希望能提供一些优化思路

**Comment by Yanyan-Wang** [comment]
https://g6.antv.antgroup.com/manual/faq/performance-opt

**Comment by keminu** [comment]
虽然官方提供一些优化的手段，一定程度解决了部分问题，但是这样用户体验及其不好，还需要从框架的源头进行优化。
比如渲染缓存、离屏渲染、拖动时局部渲染。参考jointjs，完全使用svg都不会有很大的性能问题；gojs使用的canvas更没有发现性能问题。
