### ISSUE TITLE
g6树图布局垂直排布设置排版顺序

### ISSUE THREAD

**Issue by pitilesszgw** [antvis/G6#4819]
### 问题描述

是用g6树图布局，当direction设置为V或H时，上下或者左右的节点是自动分配的 如何设置固定节点在顶部，其他节点在底部这个操作

### 重现链接

https://codesandbox.io/s/vue-g6-treegraph-pphmkw?file=/src/Demo.vue

### 重现步骤

如demo里，我想让c1和c2展示在顶部，其他兄弟节点在底部展示

### 预期行为

自定义设置节点位置

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by pitilesszgw** [comment]
或者是否支持两个树图组合c1 c2 company属于一个树图 其他的属于另外一个树图 分别使用direction为TB和BT来达到目的

**Comment by Yanyan-Wang** [comment]
getSide 

https://g6.antv.antgroup.com/api/tree-graph-layout/compact-box#layoutcfggetside

**Comment by pitilesszgw** [comment]
> getSide
> 
> https://g6.antv.antgroup.com/api/tree-graph-layout/compact-box#layoutcfggetside

这个只能设置左右吧 我想实现上下的判断，比如上面的节点是父节点，下面的是子节点，自身节点在中间
![image](https://github.com/antvis/G6/assets/30107688/2cda9821-847e-410d-9e8c-d3a6501e526e)
![image](https://github.com/antvis/G6/assets/30107688/7e15a011-4ff9-4a38-8137-f408370ac2f5)

**Comment by zhangxianglive88** [comment]
老铁，这个最后怎么解决的呀 @pitilesszgw
