### ISSUE TITLE
在shape: 'polyline-round'设置下，edge显示异常，覆盖node、线条暴露拼接状

### ISSUE THREAD

**Issue by wlc534** [antvis/g6#482]
* **G6 Version**:2.1.2
* **Platform**:Mac OS
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

<img width="462" alt="2018-09-20 11 45 08" src="https://user-images.githubusercontent.com/26006959/45795150-b9b81780-bccc-11e8-9413-af63510165a5.png">
data数据结构
var data = {
  nodes: [{
    id: '收集日志'
  }, {
    id: '入 es 集群'
  }, {
    id: '入 hdfs'
  }, {
    id: 'hive 计算'
  }, {
    id: 'report'
  },{
    id: 'report1'
  }],
  edges: [{
    source: '收集日志',
    target: '入 es 集群'
  }, {
    source: '收集日志',
    target: '入 hdfs',
    // shape: 'flowingEdge',
  }, {
    source: '入 hdfs',
    target: 'hive 计算'
  }, {
    source: '入 es 集群',
    target: 'hive 计算'
  }, {
    source: 'hive 计算',
    target: 'report'
  },
  {
    source: '收集日志',
    target: 'hive 计算'
  },
   {
    source: 'hive 计算',
    target: '收集日志'
  },
  {
    source: '入 es 集群',
    target: 'report'
  },
   ]
};
https://antv.alipay.com/zh-cn/g6/1.x/demo/flow/work-flow.html

**Comment by TomHuangCN** [comment]
这种边路由的算法目前只能解决一部分场景，而不是一个所有场景都通用的解决方案，详见：https://www.yuque.com/antv/blog/eyi70n
