### ISSUE TITLE
在展开的时候节点错乱   kayout:mindmap

### ISSUE THREAD

**Issue by wu0211** [antvis/G6#4821]
### 问题描述

<img width="752" alt="image" src="https://github.com/antvis/G6/assets/34398833/570cbb79-cd6a-47f5-aa1e-6e026a509aca">

### 重现链接

no

### 重现步骤

展开时候错乱
<img width="752" alt="image" src="https://github.com/antvis/G6/assets/34398833/62679957-f237-45ba-a2bf-4cd6a69e9dca">

### 预期行为

正常连接

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by 20100507** [comment]
你们做了搜索了；可以给出代码参考一下么？

**Comment by wu0211** [comment]
> 你们做了搜索了；可以给出代码参考一下么？

你指的是什么搜索

**Comment by 20100507** [comment]
给出节点上的关键字；有一个搜索框；在搜索框给出关键字；然后搜索节点；并且将节点移动到中央；高亮选中；

**Comment by Yanyan-Wang** [comment]
这个问题一般出现在节点没有正确的 id 时，每个节点必须要有唯一的、string id。可以先检查一下数据问题。不行的话，提供一个在线复现的 demo 看看
