### ISSUE TITLE
把官网实例工作流实例中node改成自定义DOM节点，布局显示异常

### ISSUE THREAD

**Issue by wlc534** [antvis/g6#483]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

把实例的node 切换成自定义的DOM节点，并renderer: 'svg',
 `draw(item){
      const group = item.getGraphicGroup();
      const html = G6.Util.createDOM('<div class="node">HTML 节点</div>');
      return group.addShape('dom', {
        attrs: {
          x: 0,
          y: 0,
          width: 100,
          height: 24,
          html
        }
      });
    }`

css:
.node{width: 100px;height:40px;border: 2px solid seagreen}

官网截图：
<img width="351" alt="2018-09-20 17 13 00" src="https://user-images.githubusercontent.com/26006959/45808828-585a6d80-bcf9-11e8-9fb0-af57b96a162b.png">

异常截图：
<img width="323" alt="2018-09-20 17 12 32" src="https://user-images.githubusercontent.com/26006959/45808849-627c6c00-bcf9-11e8-850b-98d8a565fde2.png">

https://antv.alipay.com/zh-cn/g6/1.x/demo/flow/work-flow.html

**Comment by TomHuangCN** [comment]
请贴上异常示例的代码片段：https://codepen.io/DoriTong/pen/pKbLVw
