### ISSUE TITLE
当我们使用changeLayout后，节点的layoutType错误导致显示异常

### ISSUE THREAD

**Issue by XiaoRIGE** [antvis/G6#4830]
### Describe the bug

我们从子图布局pipes:['grid','grid']切换到concentric布局，展示正常。然后我们从concentric切换回pipes布局后，发现实例上的layoutType并没有发生更新。导致下一次的渲染异常

### Your Example Website or App

www.test.com

### Steps to Reproduce the Bug or Issue

1.点击切换布局，从子图布局切换到同心圆布局
2.再次点击切换布局，从同心圆布局切换回子图布局，发现layoutType值未发生更新，导致下次调用changeLayout，判断layoutController.isLayoutTypeSame(layoutCfg)时出错（本来应该是不同的layoutType切换效果，但是由于切换过程中layoutType值未正确更新，导致后续异常）

### Expected behavior

layoutType值在任何时候都能正确的更新

### Screenshots or Videos

![微信截图_20230817162109](https://github.com/antvis/G6/assets/33147011/038dfb94-dc73-4cac-af17-dcf9ef8d331f)
![微信图片_20230817154227](https://github.com/antvis/G6/assets/33147011/840e3874-a2dc-4fc1-8bf6-9760205cc8ca)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
给个在线复现 demo？

**Comment by XiaoRIGE** [comment]
https://2v91939682.goho.co/

**Comment by Yanyan-Wang** [comment]
无法访问。需要能够看到代码的最简复现 demo
