### ISSUE TITLE
画布元素过多情况下拖拽或缩放画布会卡顿

### ISSUE THREAD

**Issue by hailinlu** [antvis/G6#4833]
### 问题描述

当页面元素超过一定数量后，使用内置指令drag-canvas和zoom-canvas页面会有卡顿现象

### 重现链接

无

### 重现步骤

无

### 预期行为

我期望看到页面能较为平滑的拖动和缩放，目前能看到的是页面会稍作卡顿以后然后才有动作

### 平台

- 操作系统: [macOS,]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.8.17 ]

### 补充说明（可选）

建议：是否可以参考fabric或者其他库的做法，先将画布内容转存为为图片，然后隐藏元素，对图片进行缩放和平移，等结束之后再将元素在对应位置显示，移出图片

**Comment by Yanyan-Wang** [comment]
> 建议：是否可以参考fabric或者其他库的做法，先将画布内容转存为为图片，然后隐藏元素，对图片进行缩放和平移，等结束之后再将元素在对应位置显示，移出图片

这个有类似的优化的，比如 drag-canvas，zoom-canvas 的 enableOptimize 配置
https://g6.antv.antgroup.com/manual/middle/states/default-behavior#drag-canvas

**Comment by Yanyan-Wang** [comment]
另外性能优化可以参考：https://g6.antv.antgroup.com/manual/faq/performance-opt

**Comment by hailinlu** [comment]
> > 建议：是否可以参考fabric或者其他库的做法，先将画布内容转存为为图片，然后隐藏元素，对图片进行缩放和平移，等结束之后再将元素在对应位置显示，移出图片
> 
> 这个有类似的优化的，比如 drag-canvas，zoom-canvas 的 enableOptimize 配置 https://g6.antv.antgroup.com/manual/middle/states/default-behavior#drag-canvas

这个方案之前已经尝试过了，隐藏了非keyShape的元素和边，确实可以使平移和缩放更平滑一点，但考虑用户体验的话，用户可能并不会接受这种方式，目前在尝试自定义拖拽和缩放的交互，就是元素多的时候生成图片会比较慢，不知有没有好的建议

**Comment by Yanyan-Wang** [comment]
生成图片慢，而且如果画布内容范围很大的话，生成图片还有可能崩溃

**Comment by Yanyan-Wang** [comment]
现在有多少点边，也许可以考虑 5.0 的 webgl 渲染。但目前 5.0 还在 beta 阶段
 https://g6-next.antv.antgroup.com/zh/examples/performance/perf/#evaWebGL

**Comment by hailinlu** [comment]
> 生成图片慢，而且如果画布内容范围很大的话，生成图片还有可能崩溃

这个确实会有这个问题，暂时还是使用的 [https://g6.antv.antgroup.com/manual/middle/states/default-behavior#drag-canvas](https://g6.antv.antgroup.com/manual/middle/states/default-behavior#drag-canvas) 这个方案

**Comment by hailinlu** [comment]
> 现在有多少点边，也许可以考虑 5.0 的 webgl 渲染。但目前 5.0 还在 beta 阶段 https://g6-next.antv.antgroup.com/zh/examples/performance/perf/#evaWebGL

好的，我尝试一下
