### ISSUE TITLE
combo之间和无combo层级关系问题

### ISSUE THREAD

**Issue by Soulycoris** [antvis/G6#4836]
### 问题描述

1、通过 graph.read(data) 创建的combo的层级关系是按先后顺序的层级关系，但是通过createCombo创建的combo又会在他们的下面，怎么改变他们间的层级关系呢，只能通过组合（updateComboTree）然后拆开改变吗？
如下图的combo3就是通过createCombo创建的，其他两个是data定义的

2、有combo的node和无combo的node之间的层级关系，无combo的node通过toFront到顶层后，后续通过graph.addItem添加一个新的node，又会回到比combo层级低。

### 重现链接

https://codesandbox.io/s/brave-panna-9gkntw?file=/index.js

### 重现步骤

问题1直接进入页面就是，

问题2先注释addItem方法里的graph.addItem方法，点击页面上的add按钮，可以发现rect节点是能在combo的上面，但是取消注释graph.addItem方法后点击页面上的add按钮，新添加一个node，就会使rect节点重新回到底层。

### 预期行为

1、combo有没有更精准的控制层级的方法，（暂时发现save方法保存的时候改变data里combos顺序再渲染时能按照顺序）

2、无combo的node能不在combo里但是在combo层级上面吗。

### 平台

- 操作系统: Windows
- 网页浏览器: Google Chrome, Firefox
- G6 版本: 4.8

### 屏幕截图或视频（可选）

![20230821173550](https://github.com/antvis/G6/assets/19385756/078fe95a-d91d-4498-8c25-d5689438fb64)

**Comment by Yanyan-Wang** [comment]
在有 combo 的情况下，节点/combo/边的图形层级是由内部逻辑来控制的，来保证每次更新数据的时候，都能有合理的上下图形层级关系

**Comment by Yanyan-Wang** [comment]
目前没有提供在 combo 图上控制图形层级的方式，由 graph 统一管理。

**Comment by Soulycoris** [comment]
所以就只能够在更新结束的时候再使用toFront才能维持在顶层这样吗？

**Comment by Yanyan-Wang** [comment]
目前是这样的
