### ISSUE TITLE
Graph外层DOM具有scale transform时会发生点击区域漂移

### ISSUE THREAD

**Issue by SwingCosmic** [antvis/G6#4838]
### 问题描述

如果TreeGraph所在的canvas被放置在一个具有scale值的transform的dom节点中，Node的点击触发区域会偏离Node的显示位置，且
1. scale值越大，漂移越大。
2. 当设为`scale(1)`时不再发生偏移。
3. 是否漂移可以从鼠标指针是否为手型判断

### 重现链接

https://g6.antv.antgroup.com/zh/examples/tree/customItemTree#customEdgeTree

### 重现步骤

1. 打开官方示例
2. 给`div.playgroundCodeContainer`增加样式`transform: scale(1.1);`
3. 点击运行按钮确保重新渲染
4. 所有加减号不再可点击，用鼠标滚轮缩放到约1.5倍大
5. 鼠标移到c1-2房子图标最右侧柱子上，发现变成了手型，此时点击触发了加号的逻辑（详细位置以变成手型的位置为准）
6. 其它节点也各自发生了一定程度的漂移，例如c1-2-2在图标的屋顶位置，c3-1在图标最左侧柱子
7. 将scale改成1，点击运行
8. 加减号功能恢复

### 预期行为

预期在在缩放后的DOM内使用Graph，节点可以正常点击，实际上节点点击区域偏离了渲染区域

### 平台

- 操作系统: Windows 10 
- 网页浏览器: 360极速浏览器X(Chrome95)、Edge(Chrome115)
- G6 版本: 代码是4.7.11，官方示例是4.8.19

**Comment by Yanyan-Wang** [comment]
通过 graph 的 zoom 进行缩放，不要改变容器的 transform
