### ISSUE TITLE
comboCombined布局下的innerLayout grid布局其cols和rows配置项仅能生效一次

### ISSUE THREAD

**Issue by zhang-yanglong** [antvis/G6#4841]
### Describe the bug

comboCombined布局下的innerLayout grid布局其cols和rows配置项仅能生效一次
https://github.com/antvis/layout/blob/c93ce1c453d268447a495b9e864825b4b909230a/src/layout/comboCombined.ts#L346
在改行处加断点，第一次暂停时，innerGraphLayout的行列值还是innerLayout 里配置的
之后暂时却是上一次自适应后的行列值
最终效果非常差，同样是只有5个node的combo，有的是横着排列的，有的确是竖着排列的
应该每个combo的innerLayout 都按配置里的来才对，而且自适应时也应尽量保持配置里的行列比例
（如：
https://codesandbox.io/s/nostalgic-wilson-r3shhj?file=/index.js:40-35297
里的行列比6比9，5个节点的应该是2行3列更接近该比例，而不是1行5列或者5行1列）

### Your Example Website or App

https://codesandbox.io/s/nostalgic-wilson-r3shhj?file=/index.js:40-35297

### Steps to Reproduce the Bug or Issue

1、打开https://codesandbox.io/s/nostalgic-wilson-r3shhj?file=/index.js:40-35297
2、f12 ctrl+shift+f 输入“innerGraphLayout.layout(innerGraphData);”进行搜索
3、左键跳转至comboCombined.js 303行添加断点
4、刷新右侧网页进入断点
...

### Expected behavior

每次暂停时innerGraphData的cols和rows始终为new G6.Graph 时配置的值

### Platform

- OS: Windows
- Browser: Chrome

**Comment by Yanyan-Wang** [comment]
收到问题，我们尽快排查

**Comment by WangHanZ** [comment]
你好，请问这个问题解决了吗
