### ISSUE TITLE
如何创建一个圆环图，节点分布等距分布在圆周上

### ISSUE THREAD

**Issue by chi-gao** [antvis/G6#4842]
### 问题描述

如下图，想实现一个标准的有向圆环图， 各节点均匀分布在圆周上。
![image](https://github.com/antvis/G6/assets/24784430/af97b468-c0fd-4b1f-9ae0-9bdf958f5298)

尝试了布局采用`circular` 布局， 另外边采用了 `arc` 边， 但是实现的效果不是很令人满意。
![image](https://github.com/antvis/G6/assets/24784430/e44e5325-237b-466d-8cff-4ff2ed37d82f)

遇到的问题有：
1. 动态节点数量，如何实现节点均匀分布在圆周上？
2. arc边的箭头方向如何确定？ 箭头好像是歪的，
3. 节点的 `anchorPoint`如何确定？ 因为每条边的 `sourceAnchor`和`targetAnchor`不确定
4. 如何保证`circular`布局 和 `arc`边的弧度保持一致，设置布局的`radius` 和 `arc`边的`curveOffset` 数值一样就可以嘛？

### 重现链接

https://stackblitz.com/edit/react-7havyv?file=index.js

### 重现步骤

打开链接即可看到

### 预期行为

实现一个标准的圆环图

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
改改 curveOffset
https://g6.antv.antgroup.com/manual/middle/elements/edges/built-in/arc#%E7%89%B9%E6%AE%8A%E5%B1%9E%E6%80%A7%E5%BC%A7%E5%BA%A6-curveoffset
