### ISSUE TITLE
polyline的显示问题

### ISSUE THREAD

**Issue by justiceti** [antvis/G6#4843]
### 问题描述

edge type为polyline
在VGap较小时连接会从下方连接，期望是从上方连接
目前：
![image](https://github.com/antvis/G6/assets/13634238/61692798-9233-4a40-923a-13340bc4bd24)
期望：
![image](https://github.com/antvis/G6/assets/13634238/18d8c682-bc81-4d90-98dd-e62bf0ac52b2)
我应该如何设置才能保证在间距较小的时候让线从上方连接到节点呢？

### 重现链接

暂无

### 重现步骤

如上

### 预期行为

如上

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by 539917729** [comment]
你可以试试节点上增加锚点，再通过锚点连线

<img width="929" alt="截屏2023-08-23 下午4 10 44" src="https://github.com/antvis/G6/assets/25071002/2c82ddb1-8acc-43c6-b1c9-dfa37cd71d6f">
