### ISSUE TITLE
边的箭头怎么能放到中间呢?

### ISSUE THREAD

**Issue by CurseMundi** [antvis/G6#4850]
### 问题描述

你好,我想问下,边的箭头可以不可以放到中间,目前我看到有个d的参数,但是这个d只能是固定的值,导致拖拽节点的时候,位置还是会变

### 重现链接

https://codesandbox.io/s/xenodochial-bouman-xlpnp7?file=/index.js

### 重现步骤

拖拽节点时,红箭头的位置在起始位置

### 预期行为

想让箭头在label文字附近,并且拖拽节点的时候相对位置不变

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）
想要的效果是这样的:
拖拽前
![2023-08-25_101101](https://github.com/antvis/G6/assets/8308332/704a9dc3-933c-4991-9618-1b1c1612adcc)
拖拽后
![2023-08-25_101138](https://github.com/antvis/G6/assets/8308332/896e3666-cd82-4c3c-8864-1d92b37d9cff)

_No response_

**Comment by Yanyan-Wang** [comment]
可以自定义节点在边的百分比位置加图形 https://g6.antv.antgroup.com/examples/item/customEdge/#extraShape

**Comment by CurseMundi** [comment]
尝试了,但是添加了三角形marker后,在移动节点时,三角形方向不会进行旋转, 用transform旋转也没有效果..而且拉长边的时候marker与文字背景的距离也会变动...这个有什么好的办法么?

**Comment by Ourydy** [comment]
> 尝试了,但是添加了三角形marker后,在移动节点时,三角形方向不会进行旋转, 用transform旋转也没有效果..而且拉长边的时候marker与文字背景的距离也会变动...这个有什么好的办法么?

请问解决了吗？有什么办法吗？

**Comment by tigershinny** [comment]
有Workaround办法吗？
