### ISSUE TITLE
antv g6 gForce 出现节点重叠，坐标完全一样的问题

### ISSUE THREAD

**Issue by 000215** [antvis/G6#4859]
### Describe the bug

antv g6 gForce布局首次渲染节点正常，原节点条件渲染会出现节点重合（筛选出来节点数不同，有些会出现重叠坐标完全一样），坐标完全一样的问题

### Your Example Website or App

https://g6.antv.antgroup.com/zh/examples/item/customEdge/#edgeMulLabel

### Steps to Reproduce the Bug or Issue

原节点筛选出新节点出现坐标完全一样的问题
例如：原来10个节点，筛选出3个节点出现有两个节点坐标完全一样的情况，但是筛选出五个节点可能就不会出现这个问题

### Expected behavior

希望增删改节点，不会出现重叠的情况

### Screenshots or Videos

![696170734808233133](https://github.com/antvis/G6/assets/65844538/25b909ff-edd4-49cb-bcc0-e339acd1efa7)

### Platform

- OS: [ Windows]
- Browser: [e.g. Chrome, Firefox]
- Version: [e.g. 4.8.21]

**Comment by 000215** [comment]
配置gpuEnabled就会出现这个问题

**Comment by Yanyan-Wang** [comment]
看不太懂，给个在线复现 demo 吧
