### ISSUE TITLE
Util中的方法extract和graph实例的方法unhighlightGraph未找到和未定义是什么原因？

### ISSUE THREAD

**Issue by sy13277072001** [antvis/g6#486]
codepen地址：[https://codepen.io/DoriTong/pen/LJWRMe?editors=1010](url)
想实现以上的效果；
自己在项目中使用g6时，会遇到下图的错误；g6的版本试过几个了，都不行，不知道问题在哪里，谢谢解答疑惑；
![image](https://user-images.githubusercontent.com/25413638/46065723-731f5d00-c1a5-11e8-92e9-97200c91fe38.png)

**Comment by TomHuangCN** [comment]
使用这些方法，要引入插件：

```js
<!-- 引入 G6  -->
<script src="https://unpkg.com/@antv/g6/build/g6.js"></script>
<!-- 引入 Plugins -->
<script src="https://unpkg.com/@antv/g6/build/plugins.js"></script>
```

**Comment by sy13277072001** [comment]
> 使用这些方法，要引入插件：
> 
> ```js
> 
> <script src="https://unpkg.com/@antv/g6/build/g6.js"></script>
> 
> <script src="https://unpkg.com/@antv/g6/build/plugins.js"></script>
> ```

我通过npm i 的方式引入了，plugins插件已经在引入的g6中了；
也在控制台打印了Util下面的方法，没有extract方法，所以以为是g6版本的问题；
![image](https://user-images.githubusercontent.com/25413638/46073376-555af380-c1b7-11e8-8694-deeacd093fd2.png)
![image](https://user-images.githubusercontent.com/25413638/46073681-2f821e80-c1b8-11e8-8978-b1c06b57eb9c.png)
![image](https://user-images.githubusercontent.com/25413638/46073835-999ac380-c1b8-11e8-8396-5c0f99e95d2d.png)

**Comment by TomHuangCN** [comment]
npm 也需要引入插件
```js
const G6 = require('@antv/g6');
require('@antv/g6/build/plugins');
```

**Comment by sy13277072001** [comment]
> npm 也需要引入插件
> 
> ```js
> const G6 = require('@antv/g6');
> require('@antv/g6/build/plugins');
> ```

谢谢，问题已经解决了。
