### ISSUE TITLE
Combo内部的节点折叠又展开之后，如何重新让其进入当前的combo

### ISSUE THREAD

**Issue by DragonKing686** [antvis/G6#4860]
### 问题描述

![b](https://github.com/antvis/G6/assets/76863764/73862145-60c0-4210-9094-d3f5487ee88b)
我是分了两个组，节点收缩之后graph.getNodes()是拿不到这个收起来的节点的，然后再展开的时候，我希望能够把这个节点重新放进这个combo中，请问该如何操作，我试过combos.addChild(item2);这个方法，发现加不进去，然后用graph.updateCombo(combos);或者graph.updateCombos();也没有效果
```js 
const combos = graph.findById(item);
          if (combos) {
            // 加入新的节点
            groupedNodes[item].forEach(item2 => {
              combos.addChild(item2);
            });
            // graph.layout();
            graph.updateCombo(combos);
          }
```

### 重现链接

https://

### 重现步骤

如上诉的动图所示，收起来展开之后，节点加入不了combo

### 预期行为

希望能够让节点加入combo

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![Uploading b.gif…]()

**Comment by Yanyan-Wang** [comment]
给个在线复现 demo 吧

**Comment by DragonKing686** [comment]
> 

https://codesandbox.io/s/sparkling-cdn-h5fyg5?file=/src/App.js

**Comment by DragonKing686** [comment]
https://codesandbox.io/s/sparkling-cdn-h5fyg5?file=/src/App.js


我希望节点收缩之后再展开能够重新放到之前的combo里面，现在我是直接吧combo删掉，然后重新加的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/G6"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月30日(星期三) 上午10:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [antvis/G6] Combo内部的节点折叠又展开之后，如何重新让其进入当前的combo (Issue #4860)





 
给个在线复现 demo 吧

**Comment by Yanyan-Wang** [comment]
我理解这里是不是需要使用 graph.updateComboTree ，把收起之前存在于 combo 的元素加回去啊

![image](https://github.com/antvis/G6/assets/29593318/1d3a7248-0e38-4284-a4b9-209314176674)


https://g6.antv.antgroup.com/api/graph-func/combo#graphupdatecombotreeitem-parentid
