### ISSUE TITLE
紧凑树节点收起再次展开后报错

### ISSUE THREAD

**Issue by jakejedrn** [antvis/G6#4869]
### 问题描述

全部节点展开后 点击三级节点收起子节点 然后再点击三级节点展开子节点报错

### 重现链接

无

### 重现步骤

![image](https://github.com/antvis/G6/assets/59231229/fff9fc10-4aed-4095-8ece-8d40ad5210d4)

### 预期行为

展开节点不报错

### 平台

- 操作系统: [Windows, .]
- 网页浏览器: [Google Chrome,]
- G6 版本: [4.8.21]

### 屏幕截图或视频（可选）

![image](https://github.com/antvis/G6/assets/59231229/ee4d5050-24df-4568-bcc6-ffb53b638f9a)

**Comment by Yanyan-Wang** [comment]
给个在线复现 demo 吧，先检查一下数据中每个节点是否都有唯一的 string id
