### ISSUE TITLE
调用节点的hide方法后，再使用fitview，剩余节点没有居中

### ISSUE THREAD

**Issue by XiaoRIGE** [antvis/G6#4872]
### Describe the bug

点击dom,调用节点的hide方法，然后使用fitview,节点位置向右偏移

### Your Example Website or App

www.test.com

### Steps to Reproduce the Bug or Issue

1.调用hide
2.调用fitview
3.剩余节点没有居中

### Expected behavior

期待调用fitview后剩余节点能够实现居中效果

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
可以使用 graph.focusItems，参数参考 graph.focusItem 第一个参数改为数组

https://g6.antv.antgroup.com/api/graph-func/transform#graphfocusitemitem-animate-animatecfg

**Comment by XiaoRIGE** [comment]
使用graph.focusItem能够达到居中效果，但是我们在页面其他地方比如ToolBar中也会调用fitview,我不能每个地方都换为foscsItems，然后传递当前画布没有隐藏的值啊。有更合适的解决方案吗？或者如何可以解决这个hide后不居中的问题？

**Comment by Yanyan-Wang** [comment]
不是不可以，graph.getNodes().filter(node =>  node.visible())，传给 focusItems
