### ISSUE TITLE
pathFinder方法计算严重耗时，超过10s

### ISSUE THREAD

**Issue by yagang94** [antvis/G6#4874]
### 问题描述

<img width="888" alt="image" src="https://github.com/antvis/G6/assets/50126022/bc93a9fc-19c3-4f29-b7bf-7e22fbb96ab5">

同一套配置，数据，只是一个是组件形式打开的，一个是应用里面用npm包形式打开的，在应用里面是卡顿的，在组件库里面直接打开是正常的

### 重现链接

🈚️

### 重现步骤

页面分析得到

### 预期行为

不卡顿

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by yagang94** [comment]
@Yanyan-Wang 大佬，帮忙看下呗，紧急～

**Comment by yagang94** [comment]
使用的@ant-design/graphs OrganizationGraph组织架构图，数据量较大的时候会出现计算卡顿的问题，目前需求场景时自定义折线是实现不了的

**Comment by yagang94** [comment]
奇怪的是同一套配置，数据，只是一个是组件形式打开的，一个是应用里面用npm包形式打开的，在应用里面是卡顿的，在组件库里面直接打开是正常的

**Comment by Yanyan-Wang** [comment]
先确认一下版本是否一致，然后看下你的应用有没有重复渲染的情况
