### ISSUE TITLE
我想吐血啊！~

### ISSUE THREAD

**Issue by zz-fe** [antvis/g6#488]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

1. 去年我们是基于1.16版本开发的编辑器,开发了一年、 你们现在又出了 编辑器、 瞬间感到扎心了

**Comment by TomHuangCN** [comment]
旧版线上还有，文档也还在，能照常使用：https://antvis.github.io/g6/doc/index.html
