### ISSUE TITLE
1.x版本的 能否平滑过渡到2.x版本

### ISSUE THREAD

**Issue by zz-fe** [antvis/g6#489]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by zz-fe** [comment]
当初是用的外联的方式进行开发的！~

**Comment by TomHuangCN** [comment]
![image](https://user-images.githubusercontent.com/6113694/46126201-e1742600-c25e-11e8-9516-f9d3d63dceb3.png)

2.x 做了大的架构调整。 G6 沉到底层。目前没有所谓平滑过度的方式。
