### ISSUE TITLE
鼠标悬浮在某个节点上通过滚轮缩放后，鼠标离开该节点进行其他操作后该节点的悬浮状态会显示出来

### ISSUE THREAD

**Issue by 539917729** [antvis/G6#4895]
### 问题描述

鼠标悬浮在某个节点上通过滚轮缩放后，鼠标离开该节点进行其他操作后该节点的悬浮状态会显示出来

### 重现链接

1

### 重现步骤

1

### 预期行为

不显示悬浮状态

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
给个在线复现 demo 呢？

**Comment by 539917729** [comment]
enableOptimize 去掉这个属性后就正常了

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
