### ISSUE TITLE
锚点连接问题

### ISSUE THREAD

**Issue by itsmyturn** [antvis/g6#49]
能不能处理以下两种情况
1，一个锚点连接过一次就不能进行第二次连接了
2，控制一个图形左侧的锚点不能和另外一个图形左侧的锚点进行连接

**Comment by TomHuangCN** [comment]
### 目前没有较便利的解决办法
### 可以参考下述逻辑

1. 将锚点信息存入数据模型 
2. 通过判断锚点的索引确定锚点

参考：

https://codepen.io/DoriTong/pen/JOvMBx?editors=1010
