### ISSUE TITLE
导出图片文件名后跟着格式名

### ISSUE THREAD

**Issue by iahu** [antvis/G6#4913]
### 问题描述

比如调用 `graph.downloadImage('hello-world', 'image/png')` 弹出的保存文件的对话框里文件名会是 `hello-worldpng`

### 重现链接

https://codesandbox.io/s/friendly-hill-npk2zx?file=/src/App.js

### 重现步骤

点击 'Download Image' 按钮

### 预期行为

不要附带格式名

### 平台

- 操作系统: macOS
- 网页浏览器: Google Chrome
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
感谢报告，欢迎社区 PR https://github.com/antvis/G6/blob/86057cadf3f5eafe1562534c8e81f2abcf094a90/packages/pc/src/graph/graph.ts#L419

**Comment by iahu** [comment]
> 感谢报告，欢迎社区 PR
> 
> https://github.com/antvis/G6/blob/86057cadf3f5eafe1562534c8e81f2abcf094a90/packages/pc/src/graph/graph.ts#L419

ok

**Comment by iahu** [comment]
我编译不过你们的项目，你们有时间自己改一下吧。

**Comment by iahu** [comment]
hi @Yanyan-Wang ，这个问题有进展吗

**Comment by Yanyan-Wang** [comment]
你提的 pr 已经发布了小版本🎉～ v4.8.22
