### ISSUE TITLE
能不能让activate-relations这个behavior能够实现第二次点击取消选中效果？

### ISSUE THREAD

**Issue by XiaoRIGE** [antvis/G6#4917]
### 问题描述

我使用了activate-relations，但是希望能够在第二次点击的时候取消所有的active效果

### 重现链接

www.test.com

### 重现步骤

1.第一次点击高亮和点击节点有关联的节点和边
2.第二次点击没有任何改变

### 预期行为

1.第一次点击高亮和点击节点有关联的节点和边
2.第二次点击期望能够清除所有点击效果

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
目前不支持～ 欢迎社区同学贡献代码，可加一个配置项作为开关：https://github.com/antvis/G6/blob/master/packages/pc/src/behavior/activate-relations.ts
