### ISSUE TITLE
3D 元素 - cube-node 类型节点

### ISSUE THREAD

**Issue by Yanyan-Wang** [antvis/G6#4918]
### Issue Hunt 计划（可选）

- [X] 我同意将这个 Issue 参与 Issue Hunt 计划

### Issue 难度

中等难度

### 悬赏

请在 2023 年 9 月 30 日之前完成 PR，10 月 15 日之前完成全部 CR 意见的修改。
AntV 将支付 $15 (汇率按结算当日计)

### 问题描述

在 v5 实现 cube-node 类型的节点。v5 目前已经实现了 sphere-node 圆形的 3D 节点，[DEMO](https://g6-next.antv.antgroup.com/examples/feature/features/#webgl3d)，[代码](https://github.com/antvis/G6/blob/v5/packages/g6/src/stdlib/item/node/sphere.ts)。请实现方形的 3D 节点名为 'cube-node'，使用[底层渲染引擎 G 的 cube 图形](https://g.antv.antgroup.com/examples/3d/geometry/#cube)作为 keyShape。

需要注意：
- 继承自 [base3d](https://github.com/antvis/G6/blob/v5/packages/g6/src/stdlib/item/node/base3d.ts)；
- 参考 sphere-node，可正常绘制 keyShape、labelShape、iconShape、haloShape、badgeShapes

### 重现链接

https://g6-next.antv.antgroup.com/examples/feature/features/#webgl3d

### 重现步骤

1. clone  g6 代码

```
git clone https://github.com/antvis/G6.git
```

2. 拉取所有线上分支

```
git fetch
```

3. 切换到 v5 分支

```
git checkout v5
```

4. 进入 g6 包

```
cd packages/g6
```

5. 安装依赖 

```
npm install
```

6. 启动 demo

```
npm run dev
```

7. 实现功能、新增 demo 以测试

demo 位于 packages/g6/tests/integration

测试用例的编写以及测试方式参考：https://github.com/antvis/G6/pull/4793

8. 提交代码，等待 CR

9. 根据（多次） CR 建议修改

10. 等待合并入 v5 分支后，管理员支付奖金

### 预期行为

可通过 extend 方式将 cube-node 引入到 Graph 中，然后可使用 type: 'cube-node' 来指定节点类型，并在 renderer: 'webgl-3d' 时渲染该类型图形。

PR 中应当包含测试用例、集成测试截图、效果截图等

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [5.0-beta]

**Comment by fisherLLCy** [comment]
## Issue 认领 / Issue Claim

**贡献者/Contributor**

fisherLLcy

**预计完成时间/Estimated Completion Date**

2023-09-30

**联系方式/Contact Information**

fisherlcy@163.com

**其他信息/Additional Information**

**Comment by Yanyan-Wang** [comment]
已完成：https://github.com/antvis/G6/pull/4993
已转账～
