### ISSUE TITLE
UI 插件 - 水印

### ISSUE THREAD

**Issue by Yanyan-Wang** [antvis/G6#4919]
### Issue Hunt 计划（可选）

- [X] 我同意将这个 Issue 参与 Issue Hunt 计划

### Issue 难度

低难度

### 悬赏

请在 2023 年 9 月 30 日之前完成 PR，10 月 15 日之前完成全部 CR 意见的修改。
AntV 将支付 $10 (汇率按结算当日计)

### 问题描述

在 v5 中新增水印插件 watermaker plugin：

- 该插件为 v5 新增，代替 v4 graph API 中的：
  - [graph.setImageWaterMarker](https://github.com/antvis/G6/blob/86057cadf3f5eafe1562534c8e81f2abcf094a90/packages/pc/src/graph/graph.ts#L510) 设置图片水印
  - [graph.setTextWaterMarker](https://github.com/antvis/G6/blob/86057cadf3f5eafe1562534c8e81f2abcf094a90/packages/pc/src/graph/graph.ts#L594) 设置文本水印

- 4.x 的 plugin 在 5.0 属于自由插件模块，参考 5.0 Minimap 的实现：https://github.com/antvis/G6/blob/v5/packages/g6/src/stdlib/plugin/minimap/index.ts

- 继承 Base Plugin；

### 重现链接

https://github.com/antvis/G6/blob/86057cadf3f5eafe1562534c8e81f2abcf094a90/packages/pc/src/graph/graph.ts#L510

### 重现步骤

1. clone  g6 代码

```
git clone https://github.com/antvis/G6.git
```

2. 拉取所有线上分支

```
git fetch
```

3. 切换到 v5 分支

```
git checkout v5
```

4. 进入 g6 包

```
cd packages/g6
```

5. 安装依赖 

```
npm install
```

6. 启动 demo

```
npm run dev
```

7. 实现功能、新增 demo 以测试

demo 位于 packages/g6/tests/integration

测试用例的编写以及测试方式参考：https://github.com/antvis/G6/pull/4793

8. 提交代码，等待 CR

9. 根据（多次） CR 建议修改

10. 等待合并入 v5 分支后，管理员支付奖金

### 预期行为

可通过 extend 方式将 watermarker 插件引入到 Graph 中，然后可在图配置的 plugins 中使用该插件。引入和注册可参考：https://g6-next.antv.antgroup.com/zh/examples/tool/tooltip/#tooltipPlugin

PR 中应当包含测试用例、集成测试截图、效果截图等

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [5.0-beta]

**Comment by fisherLLCy** [comment]
## Issue 认领 / Issue Claim

**贡献者/Contributor**

fisherLLcy

**预计完成时间/Estimated Completion Date**

2023-09-30

**联系方式/Contact Information**

fisherlcy@163.com

**其他信息/Additional Information**

**Comment by Yanyan-Wang** [comment]
已完成：https://github.com/antvis/G6/pull/4967
已转账～
