### ISSUE TITLE
官网箭头的 demo 有分歧

### ISSUE THREAD

**Issue by tolerance-go** [antvis/g6#492]
这是一个文档上的 bug
文档原文地址 https://www.yuque.com/antv/g6/custom-edge#8iprqg
实际代码演示地址 https://codesandbox.io/s/qvx2wxy3n4

2个问题

- 假设我的使用没有问题的话，那么 demo 的代码没有生效，因为并没有箭头出现
- path 返回的参数很复杂，我也没有发现相关文档=。=

**Comment by TomHuangCN** [comment]
没 bug 没有贴完整的代码片段而已。完整示例： https://codepen.io/DoriTong/pen/zmrXLo?editors=1010
