### ISSUE TITLE
图算法 findAllPath 如何开启webworker

### ISSUE THREAD

**Issue by kevindurant-source** [antvis/G6#4931]
### 问题描述

我看以前有个issue说目前已经支持web weoker，但是没看见相关文档说明，看了下图算法的源码，有一个findAllPathAsync 但是运行会直接报错
![image](https://github.com/antvis/G6/assets/67896847/801c2fa0-1e45-4b38-9c1a-b69378cd3abb)
![image](https://github.com/antvis/G6/assets/67896847/f1c447fc-7b44-464a-a254-c5055095e962)

### 重现链接

无

### 重现步骤

const { findAllPathAsync, findAllPath } = Algorithm;

    findAllPathAsync(graphData, findEntity[0]?.vid, findEntity[1]?.vid, false);

### 预期行为

算法异步运行

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
给个在线复现的 demo 我来看看
