### ISSUE TITLE
布局 - Pipe 流水线机制

### ISSUE THREAD

**Issue by Yanyan-Wang** [antvis/G6#4933]
### Issue Hunt 计划（可选）

- [X] 我同意将这个 Issue 参与 Issue Hunt 计划

### Issue 难度

中等难度

### 悬赏

请在 2023 年 9 月 30 日之前完成 PR，10 月 15 日之前完成全部 CR 意见的修改。
AntV 将支付 $20 (汇率按结算当日计)

### 问题描述

将 v4 的流水线布局机制迁移到 v5。

v4: https://github.com/antvis/G6/blob/master/packages/pc/src/graph/controller/layout.ts
v5: https://github.com/antvis/G6/blob/v5/packages/g6/src/runtime/controller/layout.ts

### 重现链接

https://github.com/antvis/G6/blob/master/packages/pc/src/graph/controller/layout.ts

### 重现步骤

1. clone  g6 代码

```
git clone https://github.com/antvis/G6.git
```

2. 拉取所有线上分支

```
git fetch
```

3. 切换到 v5 分支

```
git checkout v5
```

4. 进入 g6 包

```
cd packages/g6
```

5. 安装依赖 

```
npm install
```

6. 启动 demo

```
npm run dev
```

7. 实现功能、新增 demo 以测试

demo 位于 packages/g6/tests/integration

测试用例的编写以及测试方式参考：https://github.com/antvis/G6/pull/4793

8. 提交代码，等待 CR

9. 根据（多次） CR 建议修改

10. 等待合并入 v5 分支后，管理员支付奖金

### 预期行为

可通过配置 layout 进行流水线布局。PR 中应当包含测试用例、集成测试截图、效果截图等

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [5.0-beta]

**Comment by Yanyan-Wang** [comment]
@ColinChen2 已认领～

**Comment by kel66** [comment]
想请问下g6的流水线pipe布局在v5中发布了吗? 如果待发布，可否告知下计划发布的版本分支和时间计划? 语雀社区的待办列表显示，pipeline布局目前处于社区已认领的状态，会根据(多次)CR建议进行修改，等待合并入v5分支。
详见https://www.yuque.com/antv/g6/qlew63zmylpsifi1
