### ISSUE TITLE
vue项目中，安装使用5.0版本，会报很多跟webpack有关的错

### ISSUE THREAD

**Issue by OMGkillerMao** [antvis/G6#4940]
### 问题描述

在vue项目里安装antvG6的5.0版本，安装完后运行项目报错

### 重现链接

无

### 重现步骤

就简单的vue项目里按照教程安装5.0的g6,然后运行项目就报错

### 预期行为

复现

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome]
- G6 版本: [^5.0.0-beta.4]

### 屏幕截图或视频（可选）

![image](https://github.com/antvis/G6/assets/40884491/22673694-7dc0-421d-924c-fd205a7e6723)

**Comment by Yanyan-Wang** [comment]
给个在线复现 demo 呢？

**Comment by GitHub-Wyatt** [comment]
> ### 问题描述
> 在vue项目里安装antvG6的5.0版本，安装完后运行项目报错
> 
> ### 重现链接
> 无
> 
> ### 重现步骤
> 就简单的vue项目里按照教程安装5.0的g6,然后运行项目就报错
> 
> ### 预期行为
> 复现
> 
> ### 平台
> * 操作系统: [Windows]
> * 网页浏览器: [Google Chrome]
> * G6 版本: [^5.0.0-beta.4]
> 
> ### 屏幕截图或视频（可选）
> ![image](https://user-images.githubusercontent.com/40884491/266250677-22673694-7dc0-421d-924c-fd205a7e6723.png)
> 
> ### 补充说明（可选）
> _No response_

请问解决了嘛，如何处理

**Comment by OMGkillerMao** [comment]
> > ### 问题描述
> > 在vue项目里安装antvG6的5.0版本，安装完后运行项目报错
> > ### 重现链接
> > 无
> > ### 重现步骤
> > 就简单的vue项目里按照教程安装5.0的g6,然后运行项目就报错
> > ### 预期行为
> > 复现
> > ### 平台
> > 
> > * 操作系统: [Windows]
> > * 网页浏览器: [Google Chrome]
> > * G6 版本: [^5.0.0-beta.4]
> > 
> > ### 屏幕截图或视频（可选）
> > ![image](https://user-images.githubusercontent.com/40884491/266250677-22673694-7dc0-421d-924c-fd205a7e6723.png)
> > ### 补充说明（可选）
> > _No response_
> 
> 请问解决了嘛，如何处理

我们老项目的webpack还是1.X的，很老，应该是不兼容，网上也没找到啥有效的办法，直接升级到4.X就行了。。。

**Comment by fklove** [comment]
我也遇到同样问题了，我webpack@4.46.0，请问有什么办法解决吗？
