### ISSUE TITLE
想知道源码中拖拽节点后锚点位置更新的逻辑，因为在拖拽自定义节点的过程中，两个锚点的位置并不是两节点最近的连接方式

### ISSUE THREAD

**Issue by XiaoRIGE** [antvis/G6#4941]
### 问题描述

在拖拽自定义节点过程中，两个节点上的锚点没有匹配到我期望的位置（两节点最近的两个锚点相连接）

### 重现链接

www.test.com

### 重现步骤

目前找到的代码时g6-core中node.js里边在Node原型上定义的getLinkPoint方法，请问拖拽过程中锚点的更新是通过这个方法实现的吗？

### 预期行为

期望效果是不管怎么拖拽，两节点连选中的锚点是连线最短的两个锚点。

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![image](https://github.com/antvis/G6/assets/33147011/28b95685-8359-4f5d-a2b9-5d6192ea73f5)
![image](https://github.com/antvis/G6/assets/33147011/7342d596-bd3a-46ee-8506-b88085291d49)
![image](https://github.com/antvis/G6/assets/33147011/df4acb89-76c4-4baf-9585-01ee56685084)

**Comment by Yanyan-Wang** [comment]
这个是自定义节点吗？

**Comment by XiaoRIGE** [comment]
是自定义节点，相关自定义代码如下
`
G6.registerNode(
    'System',
    {
      size: 200,
      drawShape: function drawShape(cfg, group) {
        const colorInfo = getSystemColor(cfg.catalogName)
        // todo 目前是通过字段改变style中的opacity实现透明度不同，后期改为通过某个状态控制筛选状态
        // const opacity = getOpacityByNodeStatus(cfg.nodeStatus)
        // const opacity = 1
        // rect background
        const shape = group.addShape('rect', {
          attrs: {
            x: 0,
            y: 0,
            height: 136,
            width: 230,
            radius: 2,
            stroke: colorInfo[0],
            fill: colorInfo[0],
            // cursor: 'zoom-in',
            // // opacity,
          },
          name: 'System-rect-bg',
          draggable: true,
        })
        // tags
        const tagsLength = cfg.tags?.length || 0
        group.addShape('text', {
          attrs: {
            textBaseline: 'top',
            x: 114,
            y: 16,
            text: fittingStringEllipsis(cfg.name, 215, 16),
            fill: colorInfo[2],
            fontSize: 16,
            fontWeight: 600,
            lineHeight: 24,
            textAlign: 'center',
            fontFamily: 'Daimler CS',
            // // opacity,
          },
          name: `System-${cfg.name}`,
          draggable: true,
        })

        group.addShape('text', {
          attrs: {
            // textBaseline: 'top',
            x: 110,
            y: 46, // 40,
            text: '[software system]',
            fill: colorInfo[2],
            fontSize: 12,
            fontWeight: 400,
            lineHeight: 12,
            textAlign: 'center',
            fontFamily: 'Daimler CS',
            // // opacity,
          },
          name: `System-desc`,
          draggable: true,
        })

        group.addShape('text', {
          attrs: {
            textBaseline: 'top',
            y: 60,
            // y: 72,
            x: 116,
            text: fittingString(cfg.description, 215, 12),
            fill: colorInfo[2],
            fontSize: 12,
            fontWeight: 400,
            lineHeight: 16,
            textAlign: 'center',
            fontFamily: 'Daimler CS',
            // // opacity,
          },
          name: `System-${cfg.content}`,
          draggable: true,
        })
        if (tagsLength !== 2) {
          cfg.tags.forEach((item, index) => {
            const textWidth =
              tagsLength === 1 ? getLetterWidth(item, 12) + 16 : 56
            const formatTextWidth = textWidth > 180 ? 180 : textWidth
            if (index <= 2) {
              group.addShape('rect', {
                attrs: {
                  y: 100,
                  x:
                    tagsLength === 1
                      ? (220 - formatTextWidth) / 2 + index * 64 + 4
                      : 18 + index * 64 + 4,
                  height: 20,
                  width: formatTextWidth,
                  radius: 2,
                  stroke: colorInfo[1],
                  //   fill: colorInfo[1],
                  // // opacity,
                },
                name: `System-index-rect-${index}`,
                draggable: true,
              })

              group.addShape('text', {
                attrs: {
                  textBaseline: 'top',
                  y: 106,
                  x:
                    tagsLength === 1
                      ? (233 - formatTextWidth) / 2 + index * 64 + 4
                      : 22 + index * 64 + 4,
                  fontWeight: 400,
                  lineHeight: 12,
                  fontSize: 12,
                  text: fittingStringEllipsis(item, formatTextWidth, 12),
                  fill: colorInfo[2],
                  fontFamily: 'Daimler CS',
                  // // opacity,
                },
                // must be assigned in G6 3.3 and later versions. it can be any string you want, but should be unique in a custom item type
                name: `System-index-value-${index}`,
                draggable: true,
              })
            }
          })
        } else {
          let formatTextWidthTwo = 0
          cfg.tags.forEach((item, index) => {
            const textWidth =
              tagsLength === 1 ? getLetterWidth(item, 12) + 16 : 56
            const formatTextWidth = textWidth > 180 ? 180 : textWidth
            formatTextWidthTwo += formatTextWidth
            if (index <= 2) {
              group.addShape('rect', {
                attrs: {
                  y: 100,
                  x:
                    index === 0
                      ? formatTextWidthTwo - 8
                      : formatTextWidthTwo + 4,
                  height: 20,
                  width: formatTextWidth + 8,
                  radius: 2,
                  stroke: colorInfo[1],
                  //   fill: colorInfo[1],
                  // // opacity,
                },
                name: `System-index-rect-${index}`,
                draggable: true,
              })

              group.addShape('text', {
                attrs: {
                  textBaseline: 'top',
                  y: 106,
                  x: index === 0 ? formatTextWidthTwo : formatTextWidthTwo + 8,
                  fontWeight: 400,
                  lineHeight: 12,
                  fontSize: 12,
                  text: fittingStringEllipsis(item, formatTextWidth, 12),
                  fill: colorInfo[2],
                  fontFamily: 'Daimler CS',
                  // // opacity,
                },
                name: `System-index-value-${index}`,
                draggable: true,
              })
            }
          })
        }

        return shape
      },
      getAnchorPoints() {
        return systemAnchorPoints
      },
      setState: setActiveState,
    },
    'rect'
  )
`

**Comment by XiaoRIGE** [comment]
测试发现只要是自定义节点都会有点偏移

**Comment by XiaoRIGE** [comment]
发现如果自定义图形使用全局配置linkCenter:true，线的位置就是我所期望的位置，但是有个问题是我希望在edge结束的地方设置箭头，如果我配置了linkCenter，那箭头信息就会被盖住。请问能不能不配置linkCenter，也达到这个效果（两节点之前的连线一定是最近的）？或者说linkcenter只配置在source边上？

**Comment by Yanyan-Wang** [comment]
自定义节点如果是矩形作为 keyShape，应该需要把这个图形的 x y 分别减去宽高的一半，保证自身坐标系的原点位于矩形的中心：
x: -width / 2,
y: -height / 2

尝试一下，然后锚点文档可以参考：https://g6.antv.antgroup.com/api/items/node-properties#anchorpoints

**Comment by XiaoRIGE** [comment]
> 自定义节点如果是矩形作为 keyShape，应该需要把这个图形的 x y 分别减去宽高的一半，保证自身坐标系的原点位于矩形的中心： x: -width / 2, y: -height / 2
> 
> 尝试一下，然后锚点文档可以参考：https://g6.antv.antgroup.com/api/items/node-properties#anchorpoints

成功解决了我的问题，非常感谢！
