### ISSUE TITLE
Item.getBBox invoke error

### ISSUE THREAD

**Issue by tolerance-go** [antvis/g6#495]
[![Edit y3l87y22zz](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/y3l87y22zz)

**Comment by tolerance-go** [comment]
调用时机错误，还没有加入 canvas

**Comment by tolerance-go** [comment]
建议优化一下报错

**Comment by daskyrk** [comment]
知道了，想把anchor放在节点中间，可以通过在registerNode时设置anchor属性实现
