### ISSUE TITLE
报错Cannot read properties of undefined (reading 'on')

### ISSUE THREAD

**Issue by 7hao123** [antvis/G6#4952]
### 问题描述

使用相同的代码，有的页面可以将数据渲染出来，有的页面不能渲染出来，不能渲染的页面报错Cannot read properties of undefined (reading 'on')，怀疑是数据出错，可能是样例数据的label不能全为空吗？或者是不能指向多条边

### 重现链接

无

### 重现步骤

数据 "nodes": [
            {
                "id": "7",
                "label": null,
                "icon": null,
                "x": 0.0,
                "y": 0.0,
            
            },
            {
                "id": "24",
                "label": null,
                "icon": null,
                "x": 0.0,
                "y": 0.0,
            
            },
            {
                "id": "73",
                "label": null,
                "icon": null,
                "x": 0.0,
                "y": 0.0,
           
            },
            {
                "id": "61",
                "label": null,
                "icon": null,
                "x": 0.0,
                "y": 0.0,
         
            }
        ],
        "edges": [
            {
                "id": "20",
                "label": null,
                "source": "73",
                "target": "7",
            
            },
            {
                "id": "46",
                "label": null,
                "source": "61",
                "target": "7",
           
            },
            {
                "id": "48",
                "label": null,
                "source": "24",
                "target": "7",
         
            }
        ]
    

### 预期行为

我希望得到为什么出现这个bug的问题，以及解决方案

### 平台

- 操作系统: [ Windows,.]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.8.17 ]

**Comment by Yanyan-Wang** [comment]
给个在线复现 demo

**Comment by Yanyan-Wang** [comment]
![image](https://github.com/antvis/G6/assets/29593318/88ad6406-e4be-4822-8cee-9641bbee110e)

这里问题就是节点没有四个图形呀，所以  const imgShape = group.getChildByIndex(3); 拿到的是 undefined。这里我理解做一下判断就好了吧

**Comment by 7hao123** [comment]
我觉得不像是这里的问题，即使我把afterDraw的代码全部注释了仍然不能正确渲染
![MLOKLAZ(F _2RKM01ZQ%IVE](https://github.com/antvis/G6/assets/140493327/84696bcf-476a-4261-9ef3-25f7340d77d0)

**Comment by Yanyan-Wang** [comment]
我这里可以的。注释掉之后，不要热更新，手动刷新
