### ISSUE TITLE
createEdge后，clear清空画布重新读取数据，锚点改变

### ISSUE THREAD

**Issue by chyhshqx** [antvis/G6#4954]
### 问题描述

通过接连锚点创建边，边也连接在锚点上，如果设置linkCenter： true，可以实现不变，但是创建边的时候会自动吸附到中心点，二不会在锚点上
1.刚开始边连接的位置挺好的
![image](https://github.com/antvis/G6/assets/26618775/40edd4fa-a953-46aa-96cb-2b269e06d1e1)
2.在另一数据中手动创建边
![image](https://github.com/antvis/G6/assets/26618775/84c4ab9a-6422-4de4-98b6-b5f2c675f210)
3.重新切换到图二目录，图形歪了，锚点位置不知道怎么切换的
![image](https://github.com/antvis/G6/assets/26618775/103ecce1-0c14-4ea1-a8f9-198cf726502d)

### 重现链接

wu

### 重现步骤

wu

### 预期行为

创建边后，希望不会影响别的图

### 平台

- 操作系统: [ Windows, React ]
- 网页浏览器: [Google Chrome, S]
- G6 版本: [4.8.1 ... ]

**Comment by Yanyan-Wang** [comment]
给个在线复现的 demo 我看看呢

**Comment by chyhshqx** [comment]
您好，有事正在忙，如果看到邮件会第一时间回复

**Comment by Yanyan-Wang** [comment]
默认是没有 linkCenter:true 的

**Comment by chyhshqx** [comment]
您好，有事正在忙，如果看到邮件会第一时间回复
