### ISSUE TITLE
Canvas 下拖拽自定义节点产生残影

### ISSUE THREAD

**Issue by xiaoiver** [antvis/G6#4956]
### Describe the bug

拖拽自定义节点会产生残影：

<img width="554" alt="截屏2023-09-12 下午1 50 35" src="https://github.com/antvis/G6/assets/3608471/e4894b39-d887-4664-b7a2-aa659c3c7c80">

https://github.com/antvis/G/issues/1530

### Your Example Website or App

https://g6-next.antv.antgroup.com/zh/examples/item/customNode/#cardNode

### Steps to Reproduce the Bug or Issue

1. 访问 https://g6-next.antv.antgroup.com/zh/examples/item/customNode/#cardNode
2. 快速拖拽节点

### Expected behavior

正常无残影

### Platform

- OS: [macOS]
- Browser: [Chrome]
- Version: [116]

**Comment by Yanyan-Wang** [comment]
🤖

**Comment by xiaoiver** [comment]
已修复。
![Oct-08-2023 10-12-53](https://github.com/antvis/G6/assets/3608471/442e22ff-710f-43f4-b0f7-e5947c33be5e)

**Comment by nanfb** [comment]
> 已修复。更新至`@antv/g-canvas@1.11.17`修复方式为增加了几何的padding，上下左右各增加了2px ![2023年10月8日 53年10月12日](https://private-user-images.githubusercontent.com/3608471/273421347-442e22ff-710f-43f4-b0f7-e5947c33be5e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MjczMDcsIm5iZiI6MTcwMTkyNzAwNywicGF0aCI6Ii8zNjA4NDcxLzI3MzQyMTM0Ny00NDJlMjJmZi03MTBmLTQzZjQtYjBmNy1lNTk0N2MzM2JlNWUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDdUMDUzMDA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWE2YmQ4M2VmNjBhNmIwYjRiYWY1OTMxZTcyODVjZGU0OGQ4MWVlN2E4ZDYwNzIwYzc5MzE5NTQ3Mzg1YmRlMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nrg4c0_fOwaugBbhzJLvBm3jkgveYPId2n0feEN-VLI) [ ![Oct-08-2023 10-12-53](https://private-user-images.githubusercontent.com/3608471/273421347-442e22ff-710f-43f4-b0f7-e5947c33be5e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MjczMDcsIm5iZiI6MTcwMTkyNzAwNywicGF0aCI6Ii8zNjA4NDcxLzI3MzQyMTM0Ny00NDJlMjJmZi03MTBmLTQzZjQtYjBmNy1lNTk0N2MzM2JlNWUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDdUMDUzMDA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWE2YmQ4M2VmNjBhNmIwYjRiYWY1OTMxZTcyODVjZGU0OGQ4MWVlN2E4ZDYwNzIwYzc5MzE5NTQ3Mzg1YmRlMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nrg4c0_fOwaugBbhzJLvBm3jkgveYPId2n0feEN-VLI) ](https://private-user-images.githubusercontent.com/3608471/273421347-442e22ff-710f-43f4-b0f7-e5947c33be5e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MjczMDcsIm5iZiI6MTcwMTkyNzAwNywicGF0aCI6Ii8zNjA4NDcxLzI3MzQyMTM0Ny00NDJlMjJmZi03MTBmLTQzZjQtYjBmNy1lNTk0N2MzM2JlNWUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDdUMDUzMDA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWE2YmQ4M2VmNjBhNmIwYjRiYWY1OTMxZTcyODVjZGU0OGQ4MWVlN2E4ZDYwNzIwYzc5MzE5NTQ3Mzg1YmRlMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nrg4c0_fOwaugBbhzJLvBm3jkgveYPId2n0feEN-VLI) [ ](https://private-user-images.githubusercontent.com/3608471/273421347-442e22ff-710f-43f4-b0f7-e5947c33be5e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MjczMDcsIm5iZiI6MTcwMTkyNzAwNywicGF0aCI6Ii8zNjA4NDcxLzI3MzQyMTM0Ny00NDJlMjJmZi03MTBmLTQzZjQtYjBmNy1lNTk0N2MzM2JlNWUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDdUMDUzMDA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWE2YmQ4M2VmNjBhNmIwYjRiYWY1OTMxZTcyODVjZGU0OGQ4MWVlN2E4ZDYwNzIwYzc5MzE5NTQ3Mzg1YmRlMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nrg4c0_fOwaugBbhzJLvBm3jkgveYPId2n0feEN-VLI)



> 已修复。更新至`@antv/g-canvas@1.11.17`修复方式为增加了几何的padding，上下左右各增加了2px ![2023年10月8日 53年10月12日](https://private-user-images.githubusercontent.com/3608471/273421347-442e22ff-710f-43f4-b0f7-e5947c33be5e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MjczMDcsIm5iZiI6MTcwMTkyNzAwNywicGF0aCI6Ii8zNjA4NDcxLzI3MzQyMTM0Ny00NDJlMjJmZi03MTBmLTQzZjQtYjBmNy1lNTk0N2MzM2JlNWUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDdUMDUzMDA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWE2YmQ4M2VmNjBhNmIwYjRiYWY1OTMxZTcyODVjZGU0OGQ4MWVlN2E4ZDYwNzIwYzc5MzE5NTQ3Mzg1YmRlMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nrg4c0_fOwaugBbhzJLvBm3jkgveYPId2n0feEN-VLI) [ ![2023年10月8日 53年10月12日](https://private-user-images.githubusercontent.com/3608471/273421347-442e22ff-710f-43f4-b0f7-e5947c33be5e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MjczMDcsIm5iZiI6MTcwMTkyNzAwNywicGF0aCI6Ii8zNjA4NDcxLzI3MzQyMTM0Ny00NDJlMjJmZi03MTBmLTQzZjQtYjBmNy1lNTk0N2MzM2JlNWUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDdUMDUzMDA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWE2YmQ4M2VmNjBhNmIwYjRiYWY1OTMxZTcyODVjZGU0OGQ4MWVlN2E4ZDYwNzIwYzc5MzE5NTQ3Mzg1YmRlMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nrg4c0_fOwaugBbhzJLvBm3jkgveYPId2n0feEN-VLI) ](https://private-user-images.githubusercontent.com/3608471/273421347-442e22ff-710f-43f4-b0f7-e5947c33be5e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MjczMDcsIm5iZiI6MTcwMTkyNzAwNywicGF0aCI6Ii8zNjA4NDcxLzI3MzQyMTM0Ny00NDJlMjJmZi03MTBmLTQzZjQtYjBmNy1lNTk0N2MzM2JlNWUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDdUMDUzMDA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWE2YmQ4M2VmNjBhNmIwYjRiYWY1OTMxZTcyODVjZGU0OGQ4MWVlN2E4ZDYwNzIwYzc5MzE5NTQ3Mzg1YmRlMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nrg4c0_fOwaugBbhzJLvBm3jkgveYPId2n0feEN-VLI) [ ](https://private-user-images.githubusercontent.com/3608471/273421347-442e22ff-710f-43f4-b0f7-e5947c33be5e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MjczMDcsIm5iZiI6MTcwMTkyNzAwNywicGF0aCI6Ii8zNjA4NDcxLzI3MzQyMTM0Ny00NDJlMjJmZi03MTBmLTQzZjQtYjBmNy1lNTk0N2MzM2JlNWUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDdUMDUzMDA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWE2YmQ4M2VmNjBhNmIwYjRiYWY1OTMxZTcyODVjZGU0OGQ4MWVlN2E4ZDYwNzIwYzc5MzE5NTQ3Mzg1YmRlMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nrg4c0_fOwaugBbhzJLvBm3jkgveYPId2n0feEN-VLI)

在哪里添加的padding
