### ISSUE TITLE
darge布局不管怎么调整都会很分散，能不能让同一层的节点从左到右去布局呢

### ISSUE THREAD

**Issue by XiaoRIGE** [antvis/G6#4958]
### 问题描述

使用darge布局，每一层的节点都会有很多空余位置，能否让节点展示更紧凑呢？

### 重现链接

www.test.com

### 重现步骤

1.使用darge布局
2.同层节点有空间浪费

### 预期行为

1.使用darge布局
2.最终整体效果较为紧凑

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
给个效果图？描述略显抽象

**Comment by XiaoRIGE** [comment]
![微信截图_20230913151912](https://github.com/antvis/G6/assets/33147011/33062a2e-6e21-4fc2-9784-bcb7636f3078)
不好意思，可能是我描述问题。我希望的是能不能让同层的节点先把红色框中部分排满再往右侧去平铺

**Comment by Yanyan-Wang** [comment]
这个布局计算的位置，是为了综合来看边的长度最短。如果从左到右均匀排满，可能就会带来新的问题哟，就是边很长、交错很多。align 这个参数能够微调 https://g6.antv.antgroup.com/api/graph-layout/dagre#layoutcfgalign

**Comment by XiaoRIGE** [comment]
可是给出的几种使用后都达不到期望效果。请教一可以darge布局基础上调整特定节点的位置吗？
