### ISSUE TITLE
咨询一下g6两条线相交时如何创建跳线，g6图当有x,y坐标时用xy坐标，没坐标就用layout布局，这两种情况同时存在要如何处理呀

### ISSUE THREAD

**Issue by frontpan** [antvis/G6#4964]
### 问题描述

大佬，咨询一下g6两条线相交时如何创建跳线，g6图当有x,y坐标时用xy坐标，没坐标就用layout布局，这两种情况同时存在要如何处理呀？

### 重现链接

https://codesandbox.io/s/new

### 重现步骤

希望能解答一下，万分感谢，代表公司感谢您们。

### 预期行为

希望能解答一下，万分感谢，代表公司感谢您们。

### 平台

- 操作系统: [macOS, Windows, Linux, React Native]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ]

### 屏幕截图或视频（可选）

1

**Comment by Yanyan-Wang** [comment]
啥是跳线？

**Comment by changanbug** [comment]
@Yanyan-Wang 就是当两条线相交时，会有一条线从直线变成半圆型。就是这种
![1](https://github.com/antvis/G6/assets/148412772/aaad6f83-e053-462e-90c5-9ba5bcce92bb)
