### ISSUE TITLE
自定义combo 自定义rect 自定义edge 数据量达到1万以上 页面拖拽卡顿

### ISSUE THREAD

**Issue by kingrome2017** [antvis/G6#4968]
### 问题描述

自定义combo 自定义rect 自定义edge 数据量达到1万以上 页面拖拽卡顿

### 重现链接

无

### 重现步骤

自定义combo 自定义rect 自定义edge 数据量达到1万以上 页面拖拽卡顿，目前用了 modes: {
    default: [
      {
        type: 'zoom-canvas',
        enableOptimize: true,
        optimizeZoom: 0.9,
      },
      {
        type: 'drag-canvas',
        enableOptimize: true,
      },
      'drag-node',
      'brush-select',
    ],
  },

### 预期行为

自定义combo 自定义rect 自定义edge 数据量达到1万以上 页面拖拽卡顿  期望能平顺拖动

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
看看是否有帮助： https://g6.antv.antgroup.com/manual/faq/performance-opt
