### ISSUE TITLE
如果一个combo中所有的节点都通过hideItem隐藏了，combo依然会显示在界面上？

### ISSUE THREAD

**Issue by XiaoRIGE** [antvis/G6#4974]
### 问题描述

把combo中所有的节点都隐藏后，combo依然会展示出来

### 重现链接

www.test.com

### 重现步骤

1.调用节点的hideItem方法
2.combo依然会显示在界面上

### 预期行为

期望在combo中所有的节点都隐藏后，combo不要展示了

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
是的，父亲自身的显示隐藏与内部子元素显示隐藏无关，但父元素隐藏将同时隐藏子元素。可尝试 graph.hideItem 隐藏父 comgo
