### ISSUE TITLE
使用时间轴的自动播放或者手动拖动触发rangeChange方法时，minValue和maxValue会多次重复

### ISSUE THREAD

**Issue by hx8321** [antvis/G6#4975]
### Describe the bug

![image](https://github.com/antvis/G6/assets/24654315/abc923d4-f932-4cda-8e00-65f0f02ccfa9)

### Your Example Website or App

https://stackblitz.com/edit/react-gkb1vy?file=index.js

### Steps to Reproduce the Bug or Issue

.

### Expected behavior

期望自动播放或者手动拖动时触发rangeChange，minValue和maxValue不会多次重复，应该根据所处在的刻度值返回开始和结束值

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
好像是有这个问题，这里可以先尝试给 rangeChange 的函数包一个 throttle。后面内部排查一下，也欢迎社区 PR～
