### ISSUE TITLE
 TimeBar 组件 的type: 'simple '可以使用tickLabelFormatter和tooltipFomatter这个两个方法自定刻度和tooltip么

### ISSUE THREAD

**Issue by hx8321** [antvis/G6#4976]
### Describe the bug

![image](https://github.com/antvis/G6/assets/24654315/11845532-124b-4983-ab9b-1e2bf02735f3)

### Your Example Website or App

https://stackblitz.com/edit/react-awqm8u?file=index.js

### Steps to Reproduce the Bug or Issue

.

### Expected behavior

期望可以和刻度时间轴一样自定义刻度和tooltip

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
tickLabelFormatter 可以的，但是 simple 是没有 tooltip 的所以没有 tooltipFormatter

https://stackblitz.com/edit/react-awqm8u-zvgkk3?file=index.js
