### ISSUE TITLE
点击combo不需要任何效果需要如何配置？

### ISSUE THREAD

**Issue by XiaoRIGE** [antvis/G6#4977]
### 问题描述

点击combo后，目前貌似会给combo设置一个active状态，我尝试手动在combo:click回调中设置graph.setItemState(item, 'active', false)，combo的active状态没了，但是周边其余节点似乎被蒙层挡住了一样，我能否配置点击combo不需要任何交互效果？

### 重现链接

www.test.com

### 重现步骤

同上

### 预期行为

点击combo,没有任何交互效果

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
click-select 交互配置 selectCombo: false

**Comment by XiaoRIGE** [comment]
之前是并没有配置click-select的，使用到的是activate-relations，配置是：
```
 type: 'activate-relations',
 trigger: 'click',
 resetSelected: true,
```
发现如果配置了activate-relations的trigger为click,click-select配置了selectCombo也不会生效

**Comment by XiaoRIGE** [comment]
感谢提供了方向，现在通过新增
```
{
    type: 'click-select',
    selectCombo: false,
 },
{
    type: 'activate-relations',
    trigger: 'click',
    resetSelected: true,
    shouldUpdate: (item) => {
      if (item._cfg.type === 'combo') return false
        return true
    },
},
```
解决了问题

**Comment by Yanyan-Wang** [comment]
是的，禁止这些交互触发 combo 的状态就好
