### ISSUE TITLE
有没有办法能够获取到dagre布局后，横向和纵向的节点数量？

### ISSUE THREAD

**Issue by XiaoRIGE** [antvis/G6#4979]
### 问题描述

希望分别获取到dagre布局后横向和纵向的节点数量

### 重现链接

www.test.com

### 重现步骤

1.使用dagre布局，
2.想要获取dagre布局后横向和纵向的节点数量

### 预期行为

想要获取dagre布局后横向和纵向的节点数量

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
没太明白，哪些属于横向节点哪些属于纵向节点？

**Comment by XiaoRIGE** [comment]
假设我们的布局配置是
```
type: 'dagre',
rankdir: 'TB', 
align: 'DL',
```
能不能在布局完成前获取到横排/纵排的最大节点数量

**Comment by Yanyan-Wang** [comment]
不能，布局完成后你可以通过坐标去判断

**Comment by XiaoRIGE** [comment]
dagre配置中的nodesep是如何计算的？单位是px吗？为什么最后的展示效果会感觉有的节点明显是偏的
![4f9f39018d7430144b7a403996fb8b5](https://github.com/antvis/G6/assets/33147011/d44fe182-c2d2-458c-84c7-797d626b5981)

**Comment by Yanyan-Wang** [comment]
从上至下/从下至上的情况下，nodesep 是同行节点之间的水平间距，不会考虑和其他行节点的水平间距

**Comment by XiaoRIGE** [comment]
请教下如果想要在此基础上调整是修改layout/dagre/src/position/index.js中的positionX方法吗？
