### ISSUE TITLE
在Combo嵌套场景中使用ComboCombined布局，innerLayout使用dagre布局与正常使用dagre布局效果不一致

### ISSUE THREAD

**Issue by fzegg** [antvis/G6#4982]
### Describe the bug

innerLayout中使用dagre
![image](https://github.com/antvis/G6/assets/66486674/cdfc140f-1276-4193-8e07-0aecf74ff974)
直接使用dagre布局
![image](https://github.com/antvis/G6/assets/66486674/4788373a-b487-45aa-ae65-c68884a2631b)

### Your Example Website or App

https://codesandbox.io/s/0jk87p

### Steps to Reproduce the Bug or Issue

1.使用ComboCombined布局，其中innerLayout布局使用dagre
2.直接使用dagre布局

### Expected behavior

使用两个布局的效果一致

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
comboCombined 会把每个 combo 内部也使用 innerLayout 进行布局，理论上和直接只用 dagre 是会有差别的。但是看第一张图好像也不太对。你提供的 demo 链接跟你截图不同哈，看看是不是修改了没保存
