### ISSUE TITLE
能不能实现子图布局中部分布局依赖第一种布局完成后的宽高进行layout?

### ISSUE THREAD

**Issue by XiaoRIGE** [antvis/G6#4983]
### 问题描述

我们希望核心布局是darge,然后其余节点能够以网格布局分布在darge布局所组成的combo附近

### 重现链接

www.test.com

### 重现步骤

1.使用darge布局
2.其余grid布局依赖darge布局的结果进行layout

### 预期行为

期望能让子图布局依赖其余布局方式的结果

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
可以自定义布局来组合各种布局，在 registerLayout 里面 new dagre 算法，放入局部数据，进行布局，布局完成后计算这些节点的坐标范围，然后再使用其他布局根据上面坐标范围进行计算。

自定义布局本质上就是将计算后的 x y 写入到节点数据中，例如下面例子：
https://g6.antv.antgroup.com/examples/net/layoutMechanism/#customBigraph

**Comment by Yanyan-Wang** [comment]
引用布局和 new 布局算法的方法可以参考：https://g6.antv.antgroup.com/zh/examples/net/layoutMechanism/#subgraphLayout

就是把这些逻辑放到 registerLayout 里面。其实不在 registerLayout 里，在数据给到 G6 之前用这种方式计算好 x y 放到节点数据里给 G6 渲染也是可以的
