### ISSUE TITLE
使用Dagre布局的时候，如果有环形关系，布局展示异常

### ISSUE THREAD

**Issue by XiaoRIGE** [antvis/G6#4984]
### Describe the bug

使用Dagre布局的时候，如果有环形关系，布局展示异常
![c45b33664ee9fb20cd6af714b158937](https://github.com/antvis/G6/assets/33147011/bc499543-e411-424b-b41d-12546bc4dea0)

### Your Example Website or App

[(https://stackblitz.com/edit/vue-qpyddk?file=src%2FApp.vue)](https://stackblitz.com/edit/vue-qpyddk?file=src%2FApp.vue)

### Steps to Reproduce the Bug or Issue

使用dagre布局，如果有环形数据，就会展示异常

### Expected behavior

使用dagre布局，如果有环形数据，展示依然正常

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
给个在线复现 demo 吧

**Comment by XiaoRIGE** [comment]
发现配置了align: 'DL'就会出现该bug

**Comment by XiaoRIGE** [comment]
> 给个在线复现 demo 吧

demo链接更新在example中

**Comment by Yanyan-Wang** [comment]
应该是数据中指定的 layer 和图结构冲突导致的：

https://g6.antv.antgroup.com/api/graph-layout/dagre#%E6%8C%87%E5%AE%9A%E8%8A%82%E7%82%B9%E5%B1%82%E7%BA%A7

![image](https://github.com/antvis/G6/assets/29593318/53238f3f-7ba9-4b05-a1d1-ee6172d51cb8)

**Comment by XiaoRIGE** [comment]
如果我们将d的layer改为1，那么c=>d这个edge也是违背了原则（每一条边的起点的 layer 一定小于终点的 layer 值），c的layer为2，d的layer为1，为啥能正常展示呢？
