### ISSUE TITLE
为什么 rect 无法显示icon呢？

### ISSUE THREAD

**Issue by ywcr** [antvis/G6#4985]
### Describe the bug

为什么 rect 无法显示icon呢？

官网的例子也没有显示icon 是需要配置点啥吗 还是不支持

### Your Example Website or App

https://g6.antv.antgroup.com/zh/examples/item/defaultNodes/#rect

### Steps to Reproduce the Bug or Issue

https://g6.antv.antgroup.com/zh/examples/item/defaultNodes/#rect

### Expected behavior

希望能正常显示icon

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
4.x 的 rect 没有设计绘制 icon https://github.com/antvis/G6/blob/master/packages/element/src/nodes/rect.ts

欢迎社区 PR ～ 或者用 5.0：https://g6-next.antv.antgroup.com/zh/examples/item/defaultNodes/#rect
