### ISSUE TITLE
不同combo中有同一个node，combo重叠了

### ISSUE THREAD

**Issue by Ourydy** [antvis/G6#4987]
### 问题描述

nodes中的节点如下
{
      id: '111',
      label:'分组',
      comboId: 'combo1',
 },
{
      id: '333',
      label:'其他分组',
      comboId: 'combo1',
 }
,{
      id: '333',
      label:'其他分组',
      comboId: 'combo2',
 },
这时候combo1和combo2会重叠

### 重现链接

无

### 重现步骤

无

### 预期行为

不想让他们重叠

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
不支持同个节点存在两个 combo 中。考虑用轮廓包裹：https://g6.antv.antgroup.com/zh/examples/interaction/hull/#hull

**Comment by Fmajor** [comment]
能否增加一种combo类型，使得他的视觉效果和hull一样？
我本来尝试手动对每一个combo组增加hull，但是发现拖动combo时hull的更新出了问题。(#2584)
hull比起combo视觉上更为漂亮
