### ISSUE TITLE
G6如何渲染Latex的节点

### ISSUE THREAD

**Issue by CyNotes** [antvis/G6#4995]
### 问题描述

我现在希望引入mathjax来渲染数学公式latex, 但G6的自定义节点似乎没法支持mathjax产生的jsx, 怎样才能渲染latex呢?

### 重现链接

https://codesandbox.io/s/eloquent-bird-wlhy75?file=/src/App.js

### 重现步骤

我现在希望引入mathjax来渲染数学公式latex, 但G6的自定义节点似乎没法支持mathjax产生的jsx, 怎样才能渲染latex呢?

### 预期行为

如何才能渲染latex?

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
不支持～ 也许只能转为图片渲染

**Comment by CyNotes** [comment]
> 不支持～ 也许只能转为图片渲染

感谢回复!  转化成图片是一种好办法

**Comment by CyNotes** [comment]
mathjax渲染暂时放弃了
