### ISSUE TITLE
能否配置darge中相同layer层级的排序规则？

### ISSUE THREAD

**Issue by XiaoRIGE** [antvis/G6#4997]
### 问题描述

在文档中有发现两种方式，一种是配置nodeOrder，但是值应该如何配置，看不出来效果？还有是配置preset,也是不知道如何配置能生效。

### 重现链接

www.test.com

### 重现步骤

在文档中有发现两种方式，一种是配置nodeOrder，但是值应该如何配置，看不出来效果？还有是配置preset,也是不知道如何配置能生效。

### 预期行为

在文档中有发现两种方式，一种是配置nodeOrder，但是值应该如何配置，看不出来效果？还有是配置preset,也是不知道如何配置能生效。

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
nodeOrder 是 id 的数组，数据顺序是排序顺序。不生效的话给个例子？
