### ISSUE TITLE
配置brush-select，无法选中combo内的节点

### ISSUE THREAD

**Issue by XiaoRIGE** [antvis/G6#4999]
### 问题描述

界面中需要有圈选节点的功能，但是如果节点数据在combo里边，当鼠标在combo内部，我们无法进行圈选动作，只有将鼠标移出combo区域才可以进行圈选操作

### 重现链接

www.test.com

### 重现步骤

界面中需要有圈选节点的功能，但是如果节点数据在combo里边，当鼠标在combo内部，我们无法进行圈选动作，只有将鼠标移出combo区域才可以进行圈选操作

### 预期行为

界面中需要有圈选节点的功能，但是如果节点数据在combo里边，当鼠标在combo内部，我们无法进行圈选动作，只有将鼠标移出combo区域才可以进行圈选操作

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
是的，combo 和节点类似，在它上面产生的拖拽不会发生 brush，具体在源码的这个位置限制的：
https://github.com/antvis/G6/blob/abca3c0845182c636b43163257f9439aa3d7e738/packages/pc/src/behavior/brush-select.ts#L57

也许可以来贡献一下代码加一个配置项， item.getType() === 'combo' 的时候可以响应？🤔

或者也可以参考这个内置的 brush-select 自定义一个交互，自定义交互参考 demo：https://g6.antv.antgroup.com/examples/interaction/customBehavior/#dragCanvasTwoFingers

**Comment by XiaoRIGE** [comment]
加了这个判断（ item.getType() === 'combo' ），可以实现combo内框选。但是发现会和drag-combo冲突，即我框选的过程会导致combo也在移动。

**Comment by Yanyan-Wang** [comment]
那我理解你如果有这个诉求，就不让 drag-combo 吧？或者通过交互模式切换来解决这个交互冲突

**Comment by XiaoRIGE** [comment]
暂时先通过不使用 drag-combo 满足需求

**Comment by Yanyan-Wang** [comment]
4.8.23 发布了你贡献的功能，感谢～
