### ISSUE TITLE
G6中如何实现标尺功能？

### ISSUE THREAD

**Issue by LeaveZzz** [antvis/G6#5004]
### 问题描述

请问如何在G6中实现类似下图效果的标尺？标尺刻度与画布中的坐标对应，并且需要在拖拽画布、缩放画布时标尺刻度随之变化。
![1](https://github.com/antvis/G6/assets/51640689/d0ea0527-e011-49b9-8577-999fcece99c3)
![2](https://github.com/antvis/G6/assets/51640689/99c25f25-8fdb-4134-8f00-3b86b83ec237)

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
参考 Grid 的实现：

Grid 文档：https://g6.antv.antgroup.com/api/plugins#grid
源码：https://github.com/antvis/G6/blob/master/packages/plugin/src/grid/index.ts

**Comment by LeaveZzz** [comment]
> 参考 Grid 的实现：
> 
> Grid 文档：https://g6.antv.antgroup.com/api/plugins#grid 源码：https://github.com/antvis/G6/blob/master/packages/plugin/src/grid/index.ts

感谢提供思路，已解决。
