### ISSUE TITLE
G6怎么创建子流程节点，节点可以展开收缩

### ISSUE THREAD

**Issue by n-knight** [antvis/G6#5005]
### 问题描述

请问下G6中怎么创建子流程节点，节点可以展开收缩，子流程节点之间也可以添加edge信息，子流程节点内部不可编辑

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
dagre布局，通过数据变更控制展开收起

**Comment by n-knight** [comment]
> dagre布局，通过数据变更控制展开收起

请问下有没有类似的demo可以参考下的，万分感谢

**Comment by n-knight** [comment]
流程图里引用子流程，子流程内部节点不允增改节点/连线，支持展开/收起子流程；允许子流程之间通过节点连线，子流程之间的连线可以自选起点节点和终点节点 ，大概希望实现这样的效果。

**Comment by Yanyan-Wang** [comment]
这个就是一个点击节点通过 changeData 增加了子图的 demo，只是可能需要使用不同的布局

https://g6.antv.antgroup.com/examples/net/radialLayout/#interactRadial
