### ISSUE TITLE
Canvas 渲染模式下无法正常显示Apng格式的图片

### ISSUE THREAD

**Issue by suzukaovo** [antvis/G6#5008]
### 问题描述

版本：^4.8.8
问题：在canvas渲染模式下使用Apng格式的动态图片，无法正常显示图片的动画，SVG渲染模式下可以正常显示，但是因为业务需求无法使用SVG渲染模式进行开发，希望能在canvas渲染模式下也支持显示apng格式的图片

### 重现链接

https://codesandbox.io/p/sandbox/charming-thompson-4vqx2k?file=%2Fsrc%2FApp.vue%3A4%2C1

### 重现步骤

进入页面

### 预期行为

apng格式的图片能在canvas渲染模式下正常显示其动画效果，但是当前不可以

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.8.8 ]

**Comment by Yanyan-Wang** [comment]
暂不支持，欢迎共建～
