### ISSUE TITLE
使用linkcenter后，某些线条的箭头被节点遮挡

### ISSUE THREAD

**Issue by nodiff-229** [antvis/G6#5010]
### 问题描述

使用linkcenter后，某些线条的箭头被节点遮挡，比如图中的rect和eclipse节点

### 重现链接

无

### 重现步骤

无

### 预期行为

希望箭头指向节点中心，但应在接触到节点外轮廓时停止

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![WX20230925-154132@2x](https://github.com/antvis/G6/assets/44941306/fc02e1a9-16a2-4b6a-9c40-5115804a0569)

**Comment by nodiff-229** [comment]
`const graph = new G6.Graph({
    container: containerId,
    width: overviewGraphContainer.clientWidth,
    height: overviewGraphContainer.clientHeight,
    modes: {
      default: ["drag-canvas", "zoom-canvas", "drag-node"],
    },
    layout: {
      type: "gForce",
      preventOverlap: true,
      gravity: 10,


      linkDistance: (d) => {
        return 100 + (d.source.size + d.target.size) / 2;

      },
    },
    defaultNode: {
      size: 30,
      style: {
        lineWidth: 2,
        fill: "#C6E5FF",
        stroke: "#5B8FF9",
      },
      stateStyles: {
        dim: {
          opacity: 0.2,
        },
      },
    },
    defaultEdge: {
      type:'quadratic',
      labelCfg: {
        autoRotate: true,
      },
      style: {

        stroke: "#C0C4CC",
        lineWidth: 2,
        endArrow: {
          path: G6.Arrow.triangle(3, 10, 15),
          d: 15,
          opacity: 0.5,
        },


      },
    },
    maxZoom: 1.5, // 最大缩放比例
    linkCenter: true,// 指定边是否连入节点中心
    // 启用tooltip，悬浮时展示边信息，暂时不用，注释掉了
    plugins: [
      // new G6.Tooltip({
      //   getContent(evt) {
      //     const {item} = evt;
      //     const model = item.getModel();
      //     return getTooltip(model);
      //   },
      //   offsetX: 10,
      //   offsetY: 20,
      //   itemTypes: ["node", "edge"],
      // }),
    ],
  });`

**Comment by nodiff-229** [comment]
```
const graph = new G6.Graph({
    container: containerId,
    width: overviewGraphContainer.clientWidth,
    height: overviewGraphContainer.clientHeight,
    modes: {
      default: ["drag-canvas", "zoom-canvas", "drag-node"],
    },
    layout: {
      type: "gForce",
      preventOverlap: true,
      gravity: 10,


      linkDistance: (d) => {
        return 100 + (d.source.size + d.target.size) / 2;

      },
    },
    defaultNode: {
      size: 30,
      style: {
        lineWidth: 2,
        fill: "#C6E5FF",
        stroke: "#5B8FF9",
      },
      stateStyles: {
        dim: {
          opacity: 0.2,
        },
      },
    },
    defaultEdge: {
      type:'quadratic',
      labelCfg: {
        autoRotate: true,
      },
      style: {

        stroke: "#C0C4CC",
        lineWidth: 2,
        endArrow: {
          path: G6.Arrow.triangle(3, 10, 15),
          d: 15,
          opacity: 0.5,
        },


      },
    },
    maxZoom: 1.5, // 最大缩放比例
    linkCenter: true,// 指定边是否连入节点中心
    // 启用tooltip，悬浮时展示边信息，暂时不用，注释掉了
    plugins: [
      // new G6.Tooltip({
      //   getContent(evt) {
      //     const {item} = evt;
      //     const model = item.getModel();
      //     return getTooltip(model);
      //   },
      //   offsetX: 10,
      //   offsetY: 20,
      //   itemTypes: ["node", "edge"],
      // }),
    ],
  });
```

**Comment by Yanyan-Wang** [comment]
因为形状不是规则的，所以一个节点使用相同的缩进 d 会导致这个问题。也许可以尝试指定几个连入位置：https://g6.antv.antgroup.com/manual/middle/elements/nodes/anchorpoint

**Comment by Yanyan-Wang** [comment]
不设置 linkCenter 、箭头的 d、anchorPoints，会自动寻找节点边缘的最近位置：

![image](https://github.com/antvis/G6/assets/29593318/c49f6a87-3cf6-4c2b-9502-0b3c330ba81f)
