### ISSUE TITLE
两层dagre

### ISSUE THREAD

**Issue by neolee6053** [antvis/G6#5011]
### 问题描述

Dagre, 如何能做到这样？ :)
![image](https://github.com/antvis/G6/assets/135953327/24797bb5-d423-40e4-9401-890bc6f476f9)

### 重现链接

https://codesandbox.io/s/new

### 重现步骤

如上

### 预期行为

如上

### 平台

- 操作系统: [ Windows]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.8.17 ]

**Comment by Yanyan-Wang** [comment]
自定义布局里面使用两次 dagre，后一次依赖上一次的结果进行一定的平移

**Comment by neolee6053** [comment]
好的，让我试试
