### ISSUE TITLE
请问是否支持单独设置linkCenter

### ISSUE THREAD

**Issue by sunrisexl** [antvis/G6#5015]
### 问题描述

目前只找到了在graph中全局设置linkCenter，请问是否有针对不同的连线单独设置linkCenter的功能，我该如何实现？

### 重现链接

https://g6.antv.antgroup.com/zh/examples/item/defaultEdges/#arc

### 重现步骤

修改 linkCenter: false,
无法单独设置某条连线的linkCenter

### 预期行为

单独设置某条连线的linkCenter

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
不同节点可以设置不同的 anchorPoints（边连入位置）：https://g6.antv.antgroup.com/manual/middle/elements/nodes/anchorpoint
