### ISSUE TITLE
V5 不提供控制点情况下，折线无法显示尾部箭头

### ISSUE THREAD

**Issue by Cat1007** [antvis/G6#5017]
### Describe the bug

在不指定控制点的情况下，无法渲染箭头

### Your Example Website or App

https://g6-next.antv.antgroup.com/zh/examples/item/defaultEdges/#polyline3

### Steps to Reproduce the Bug or Issue

https://g6-next.antv.antgroup.com/zh/examples/item/defaultEdges/#polyline3

### Expected behavior

https://g6-next.antv.antgroup.com/zh/examples/item/defaultEdges/#polyline3

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
@yvonneyx 看看这个问题

**Comment by Aarebecca** [comment]
正式版已解决该问题
