### ISSUE TITLE
树图使用indented布局，direction为H，dropCap为false时，如何设置每一列的的节点上下间距

### ISSUE THREAD

**Issue by ali081809** [antvis/G6#5020]
### 问题描述

如下图

### 重现链接

无

### 重现步骤

无

### 预期行为

希望能够单独的设置间距，如何去修改呢，还是底层源码就不支持？

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![image](https://github.com/antvis/G6/assets/56957948/03a29126-1fda-4095-9d2a-4c67faa0f212)

**Comment by Yanyan-Wang** [comment]
暂不支持。可以在布局后手动 graph.updateItem 调整节点 x y
