### ISSUE TITLE
edge 有multiple select 吗？ 

### ISSUE THREAD

**Issue by neolee6053** [antvis/G6#5021]
### 问题描述

用brush-select可以框选节点,虽然有includeEdges的选项，但好像没什么作为。
如何能同时框选edge而不包括节点呢？
![selectedge](https://github.com/antvis/G6/assets/135953327/fdce3559-b228-456b-9ee0-bfa39efe2e40)

### 重现链接

https://codesandbox.io/s/g6-forked-jy3cvl?file=/index.js

### 重现步骤

如上

### 预期行为

如上

### 平台

- 操作系统: [ Windows]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.8.15 ]

**Comment by Yanyan-Wang** [comment]
https://g6.antv.antgroup.com/examples/interaction/select/#brush

希望选中边有响应，需要给边配置状态样式。并且选中边的条件是两个端点都被框住。如果需要像视频那样只框住边的一部分即可选中边，内置交互暂不支持，可以提 PR 增加配置项，但这样需要计算边是否穿过框选区域，直线边比较好计算，如果是曲线、折线会比较麻烦。如果你的场景中只有直线，也可以自定义交互来实现这个功能
