### ISSUE TITLE
V5 当 selected 状态触发后，自定义节点文本渲染不正常

### ISSUE THREAD

**Issue by Cat1007** [antvis/G6#5027]
### Describe the bug

当进入selected状态后，部分文本会丢失，但是看 shapeMap 中存在该元素
且，触发一次selected以后，被影响后的节点，在拖动画布时，没消失的文本会出现字体加深模糊的情况
通过 https://g6-next.antv.antgroup.com/examples/interaction/highlight/#activateRelations 这个示例 触发的 selected

### Your Example Website or App

none

### Steps to Reproduce the Bug or Issue

同上

### Expected behavior

希望能够正确渲染文本

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
这个 demo 看起来没有配置文本也
