### ISSUE TITLE
节点的选中效果怎么加啊？我之前看过一个issues，找不到了。

### ISSUE THREAD

**Issue by BusyHe** [antvis/g6#503]
![image](https://user-images.githubusercontent.com/17348825/47005947-68823300-d167-11e8-9e59-d56b014f0192.png)

![image](https://user-images.githubusercontent.com/17348825/47005883-48eb0a80-d167-11e8-8831-4688534ded22.png)
然后这样有个问题，点击第一个正常，点击第二个后，鼠标拖拽节点松开后会跟随一段，很奇怪。

**Comment by TomHuangCN** [comment]
贴个 codepen https://codepen.io/DoriTong/pen/pKbLVw

**Comment by BusyHe** [comment]
@TomHuangCN 我上面这种方法对吗

**Comment by TomHuangCN** [comment]
严格讲不能调用文档上没有抛的接口。哪怕你想复用内部节点的定义，也应该把代码再拷贝一份

不过你描述的问题应该跟这段定义的代码无关

**Comment by BusyHe** [comment]
明白了，我是把changeNodeActive方法删了，拖拽就可以了。后面我再追是什么引起了。有什么好的方法来实现的我的需求，求指点
