### ISSUE TITLE
Settting the inner and outer layout for a ComboCombined layout causes the combos to overlap even when relayout is true 

### ISSUE THREAD

**Issue by bsansone** [antvis/G6#5030]
### Describe the bug

Settting the inner and outer layout for a ComboCombined layout causes the combos to overlap even when relayout is true 

### Your Example Website or App

https://codesandbox.io/s/combo-combined-prevent-overlap-yqjtps

### Steps to Reproduce the Bug or Issue

1. Go to https://codesandbox.io/s/combo-combined-prevent-overlap-yqjtps
2. Double click on a combo to expand it
3. Notice that it overlaps the other nodes and combos, it also does not seem to relayout many of the nodes at all

### Expected behavior

I expect that when a combo is expanded, it should prevent intself from overlapping other nodes and combos when `relayout` is set to `true`. This seems to work "ok" when you have the layout type set to just `comboCombined` without using `outerLayout` and `innerLayout`.

### Screenshots or Videos

[Screencast from 10-05-2023 10:43:31 AM.webm](https://github.com/antvis/G6/assets/16868336/fb2df043-ef2b-4831-88a8-53bcac83a14e)

### Platform

- OS: Ubuntu Linux
- Browser: Chrome
- Version: 116.0.5845.187 (Official Build) (64-bit)

**Comment by Yanyan-Wang** [comment]
Try this configuration for outerLayout:


    outerLayout: new G6.Layout["gForce"]({
      gravity: 1,
      factor: 4,
      linkDistance: (edge, source, target) => {
        const nodeSize = ((source.size?.[0] || 30) + (target.size?.[0] || 30)) / 2;
        return Math.min(nodeSize * 1.5, 700);
      }
    })
