### ISSUE TITLE
G6 creates canvas elements with style position: fixed

### ISSUE THREAD

**Issue by lfkpoa** [antvis/G6#5031]
### Describe the bug

Hello,

There seems to be a problem in Beta 5 regarding the position of the canvas elements.
They are being created with position: fixed, which makes their position fixed with regards to the screen.
I think the correct would be position: absolute, which makes their position fixed with regards to the parent container.
It ends up staying at a fixed place on the page instead of scrolling with the page.
And I think something is wrong when detecting the container height too.

### Your Example Website or App

https://zhcfkr.csb.app/

### Steps to Reproduce the Bug or Issue

1. open https://zhcfkr.csb.app/
2. resize the window

### Expected behavior

I would expect the canvas to scroll with the page

### Platform

- OS: Windows
- Browser: Chrome
- Version: 117.0.5938.63 64 bits

**Comment by lfkpoa** [comment]
The page is based on the webgl 3d example.
The sandbox is https://codesandbox.io/s/youthful-oskar-zhcfkr

**Comment by xiaoiver** [comment]
Since `$container` already has `position: relative`, we should use `absolute` instead of `fixed` here.

**Comment by Yanyan-Wang** [comment]
pls try 5.0.0-beta.20, issue fixed. And its new features:

- map view plugin: https://g6-next.antv.antgroup.com/en/examples/feature/features/#mapView
- performance enhanced(try to zoom or drag after tiled rendering finished): https://g6-next.antv.antgroup.com/en/examples/feature/features/#moreDataWebGL
