### ISSUE TITLE
G6有没有搜查功能？search node?

### ISSUE THREAD

**Issue by neolee6053** [antvis/G6#5032]
### 问题描述

G6有没有搜查功能？search node?

### 重现链接

https://codesandbox.io/s/new

### 重现步骤

如上

### 预期行为

如上

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.8.17 ]

**Comment by bsansone** [comment]
Not built-in, you would need to implement it yourself, maybe something like:
```
const matchesSearchTerm = (nodeLabel) => {
    return nodeLabel.toLowerCase().includes(searchTerm.toLowerCase());
};
const filterNodes = () => {
    const nodes = graph.getNodes().filter(node => matchesSearchTerm(node.label));
    const edges = graph.getEdges().filter(edge => {
        return nodes.some(node => [edge.source, edge.target].includes(node.id));
    });
    graph.changeData({ nodes, edges });
};
```

**Comment by Yanyan-Wang** [comment]
如果你想搜索后定位，首先确认节点 id，然后通过 graph.focusItem(id) 进行定位
https://g6.antv.antgroup.com/api/graph-func/transform#graphfocusitemitem-animate-animatecfg

**Comment by neolee6053** [comment]
👍谢谢
