### ISSUE TITLE
自定义更新动画无效的问题

### ISSUE THREAD

**Issue by mengxiong10** [antvis/g6#504]
* **G6 Version**: 2.1.3

* 自定义进入和离开动画是OK的, 但是更新动画是无效的, 源码定义了可以自定义的接口但是没有使用, 我想这是个Bug. 目前在用`tree.set('_updateAnimate', () => {})`

![image](https://user-images.githubusercontent.com/14135808/47006342-3d4c1380-d168-11e8-8951-e2d6e94cefa2.png)

![image](https://user-images.githubusercontent.com/14135808/47006227-0544d080-d168-11e8-95ea-517e0b8d4b1e.png)

*  设置了动画后, 比如新增一个节点都必须延迟执行, 这里有没有办法提供接口修改成throttle 或 自定义,谢谢!
![image](https://user-images.githubusercontent.com/14135808/47006569-c95e3b00-d168-11e8-8fe8-23d2c5831a09.png)

**Comment by TomHuangCN** [comment]
原始需求是什么？做树的展开折叠动画？

**Comment by mengxiong10** [comment]
是的, 新增节点 和 展开的时候 总会 延迟 感觉有点怪

**Comment by TomHuangCN** [comment]
定义更新动画接口没想好怎么抛，要做这个动画，整个动画机制要重构一下

**Comment by mengxiong10** [comment]
现在动画是没问题, 但是因为这个debounce, 让动画有延迟, 有没有好的方法?

**Comment by TomHuangCN** [comment]
没那么容易的，用 throttle 也会有问题，你可以把项目拉到本地，改源码试试

**Comment by mengxiong10** [comment]
动画的触发和结束是不是应该有事件发出来?  动画执行中不重新渲染而不是用debounce 是不是才是比较正确的做法?

**Comment by TomHuangCN** [comment]
已在最新版本解决
