### ISSUE TITLE
graph.setTextWaterMarker 设置文字水印后  如何调整水印文字的颜色大小之类的

### ISSUE THREAD

**Issue by yeyusama** [antvis/G6#5042]
### 问题描述

graph.setTextWaterMarker(['xxxxxxxxx', 'xxxxxxxxxxxxxxxx']); 

graph.setTextWaterMarker 设置文字水印后  如何调整水印文字的颜色或者大小呢

看似乎有第三个参数 但是具体是如何配置的呢

### 重现链接

https://github.com/antvis/G6/issues/new?assignees=&labels=&projects=&template=bug_report_chinese.yml

### 重现步骤

https://github.com/antvis/G6/issues/new?assignees=&labels=&projects=&template=bug_report_chinese.yml

### 预期行为

调整水印文字的颜色或者大小

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
https://g6.antv.antgroup.com/api/graph-func/watermarker#graphsettextwatermarkertexts-config

第二个参数的 text 可以设置文本样式，在表格中有例子

**Comment by yeyusama** [comment]
感谢 已解决
