### ISSUE TITLE
TimeBar simple 类型下 Handler 高亮颜色默认为空导致 `mouseenter` 事件穿透到下层元素

### ISSUE THREAD

**Issue by iahu** [antvis/G6#5049]
### Describe the bug

TimeBar simple 类型下 Handler 高亮颜色默认为空导致 `mouseenter` 事件穿透到下层 `oreground` 元素，从而导致 Handler 的悬停状态未被正确捕获。

### Your Example Website or App

https://codesandbox.io/s/confident-ully-fc2xgc?file=/src/App.js

### Steps to Reproduce the Bug or Issue

1. 鼠标移动到滑块上
2. 观察滑块上的背景色变化

### Expected behavior

正确设置背景色，从而事件不穿透。

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
4.8.23 发布了你贡献的代码，感谢～
