### ISSUE TITLE
树图，文本（text）是否可以设置点击事件

### ISSUE THREAD

**Issue by AxinIcon** [antvis/G6#5051]
### 问题描述

![image](https://github.com/antvis/G6/assets/128690680/b4c245a4-8fed-4981-bc33-8b593b86ecdc)

### 重现链接

https://g6.antv.antgroup.com/zh/examples/tree/indented#intendAlignTop

### 重现步骤

https://g6.antv.antgroup.com/zh/examples/tree/indented#intendAlignTop

### 预期行为

![image](https://github.com/antvis/G6/assets/128690680/b4c245a4-8fed-4981-bc33-8b593b86ecdc)

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
https://g6.antv.antgroup.com/examples/interaction/partialResponse/#partialNode

**Comment by AxinIcon** [comment]
> https://g6.antv.antgroup.com/examples/interaction/partialResponse/#partialNode

感谢感谢 看懂了
