### ISSUE TITLE
contextmenu-shouldbegin

### ISSUE THREAD

**Issue by GitHub-Wyatt** [antvis/G6#5059]
### 问题描述

点击shouldbegin=false的节点上，上一次出现的菜单没有关闭

### 重现链接

https://g6.antv.antgroup.com/zh/examples/tool/contextMenu/#contextMenu

### 重现步骤

调整示例：
shouldBegin(evt) {
    const {item} = evt;
    const model = item.getModel();
    if (model.id === 'node1') {
      return true;
    }
    return false;
  },
1、点击shouldbegin=true的节点上，正确出现菜单
2、点击shouldbegin=false的节点上，步骤1的菜单没有消失

### 预期行为

新的点击行为，之前的菜单会消失

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.8.23]

### 屏幕截图或视频（可选）

![Uploading 1.png…]()

**Comment by Yanyan-Wang** [comment]
确实，其实两种表现都合理。可以来个 PR 共建一下呢，在上下文菜单的插件中，判断 shouldbegin 是 false 的地方调用一下隐藏菜单的 API 就好，代码在这里：https://github.com/antvis/G6/tree/master/packages/plugin/src/menu
