### ISSUE TITLE
v5 官方示例menu的trigger 改为click时无效

### ISSUE THREAD

**Issue by lightlib** [antvis/G6#5061]
### Describe the bug

v5 官方示例menu的trigger 改为click时无效

### Your Example Website or App

https://g6-next.antv.antgroup.com/zh/examples/tool/contextMenu/#contextMenu

### Steps to Reproduce the Bug or Issue

![image](https://github.com/antvis/G6/assets/5072407/693858a5-3769-4e05-9277-5687740f6019)

### Expected behavior

应当跟v4一样

### Platform

v5

**Comment by Yanyan-Wang** [comment]
@antv/g6@5.0.0-beta.26 修复啦
