### ISSUE TITLE
树状布局TB状态下，子节点希望可以支持自定义布局

### ISSUE THREAD

**Issue by KTBOY** [antvis/G6#5062]
### 问题描述

这段代码对子节点自定义布局没有效果
`      treeGraph.node(function (node) {
      return {
        label: node.id,
        labelCfg: {
          offset: 10,
          position: node.children && node.children.length > 0 ? "" : "right"
        }
      };
    });`

### 重现链接

https://codesandbox.io/embed/sleepy-khorana-8jqxhd?fontsize=14&hidenavigation=1&theme=dark

### 重现步骤

1.点击进行页面
2.搜索treeGraph.node

### 预期行为

类似实现效果图1：![image](https://github.com/antvis/G6/assets/52773276/ff619a18-8ffa-413b-adb3-5361ba356f92)

效果图2：https://user-images.githubusercontent.com/52773276/274475868-e0f9f42c-5992-44c6-9fe7-bf6e0297d88d.png

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
树图的自定义布局可以这么做：https://codesandbox.io/s/ecstatic-phoebe-95kxjg

**Comment by KTBOY** [comment]
还是这样，多谢大佬了

**Comment by zhangyang-igloo** [comment]
> 树图的自定义布局可以这么做：https://codesandbox.io/s/ecstatic-phoebe-95kxjg

求问，如果我想从depth=2的节点开始应用缩进树的配置应该怎么修改？
