### ISSUE TITLE
内置交互 drag-canvas 怎么实现通过鼠标其他按键（如中键）拖拽移动画布

### ISSUE THREAD

**Issue by AndySpider** [antvis/G6#5063]
### 问题描述

drag-canvas 实现了通过鼠标左键拖拽移动画布，能否自定义成其他按键，比如中键、右键？

### 重现链接

无

### 重现步骤

无

### 预期行为

能配置成鼠标中键拖拽

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
确实还不支持，欢迎来个 PR 共建这个功能～
