### ISSUE TITLE
antv  G6 的findAllPath方法是不是点和边都不能重复

### ISSUE THREAD

**Issue by kevindurant-source** [antvis/G6#5064]
### 问题描述

antv  G6 的findAllPath方法是不是点和边都不能重复，能否支持点重复边不能重复

### 重现链接

antv  G6 的findAllPath方法是不是点和边都不能重复

### 重现步骤

antv  G6 的findAllPath方法是不是点和边都不能重复

### 预期行为

antv  G6 的findAllPath方法是不是点和边都不能重复

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

antv  G6 的findAllPath方法是不是点和边都不能重复

### 补充说明（可选）

antv  G6 的findAllPath方法是不是点和边都不能重复

**Comment by Yanyan-Wang** [comment]
你说的是返回值中的不同路径的边有重复吗？这个应该是符合预期的吧因为多个路径可能会有重叠部分路径
