### ISSUE TITLE
G6的edge能否支持绕过combo,目前的走线会穿过combo

### ISSUE THREAD

**Issue by hwanpenn** [antvis/G6#5066]
### 问题描述

和连线穿过节点类型，combo收起状态下，连线会穿过combo，有没有什么办法可以绕过节点，或者相关的文档可以参考的

### 重现链接

https://g6.antv.antgroup.com/examples/net/dagreFlow#dagreCombo

### 重现步骤

整几成combo关系，可以看到走线会穿过combo

### 预期行为

希望可以提供绕过收起后combo的方法或者文档

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![A31F2B85-A948-4030-8C2C-18A259AD4DC9](https://github.com/antvis/G6/assets/26617702/5c826ece-cc18-4d86-a152-20b934d1e1b6)

**Comment by Yanyan-Wang** [comment]
暂不支持～ v4 版本的折线不支持自动避障。v5 版本支持：https://g6-next.antv.antgroup.com/zh/examples/item/defaultEdges/#polyline3

**Comment by yangyili** [comment]
> 暂不支持～ v4 版本的折线不支持自动避障。v5 版本支持：https://g6-next.antv.antgroup.com/zh/examples/item/defaultEdges/#polyline3
当前链接打开页面空白。issue里给的好多链接都访问不了
