### ISSUE TITLE
在 DvaJS 构建的项目中使用 G6 时报错，错误为 `TypeError: __WEBPACK_IMPORTED_MODULE_0_flru___default(...) is not a function`

### ISSUE THREAD

**Issue by wenmin92** [antvis/G6#5068]
### 问题描述

有一个使用 DvaJS 构建的老项目，需要使用树图，观察到 G6 在自定义方面的优势，遂决定用之。
引入后，仅仅简单的调用即报错。后来，使用 CRA 重新创建一个起始项目，发现无问题，使用 DvaJS 重新创建一个起始项目，遇到同样的问题。然而，技术有限，没能找出合适的办法。
  
  
(下方“重现链接”没能复现，可能我操作/设置有问题，本地会出现这个bug)

### 重现链接

https://stackblitz.com/edit/dva-g6-issue-siuvwe98?file=package.json

### 重现步骤

1. 使用 `dva-cli` 创建一个新项目
2. 添加 `@antv/g6`, 并导入使用
3. 启动服务
4. 浏览器访问，报错

### 预期行为

应该可以正常运行，访问正常；实际结果却是访问报错

### 平台

- 操作系统: Windows 10 22H2
- 网页浏览器: Edge 118.0.2088.46
- G6 版本: 4.8.23

### 屏幕截图或视频（可选）

![2023-10-17_112722](https://github.com/antvis/G6/assets/6901815/15fb7fa7-df6c-4ee7-ab5f-4a0b8f5347c4)

**Comment by hustcc** [comment]
@wenmin92 清空一下依赖在安装，也检查一下 lock 文件，保证 @antv/util 版本为 [3.3.5](https://github.com/antvis/util/pull/108).

**Comment by wenmin92** [comment]
> @wenmin92 清空一下依赖在安装，也检查一下 lock 文件，保证 @antv/util 版本为 [3.3.5](https://github.com/antvis/util/pull/108).

@hustcc 感谢您的回复。
我使用的是新建项目。安装 @antv/g6 时，默认 @antv/util 的版本为 2.0.17。为了达到您说的要求，我额外安装了 @antv/g6，此时，版本变为 3.3.5。但是，不论哪种情况，清空依赖，重新安装后，报错还都是一样的，并没有消除 bug。

**Comment by hustcc** [comment]
看起来应该是项目项目中有多个地方有 antv/util 。

**Comment by wenmin92** [comment]
> 看起来应该是项目项目中有多个地方有 antv/util 。

项目是新建的，直接依赖只有 `react`, `react-dom`, `dva`, `@antv/g6` 这几个。
我测试了，4.x 都不行，降到 3.8.5 可以。
