### ISSUE TITLE
V5 入门-快速上手-CDN方式引入，示例代码无法运行

### ISSUE THREAD

**Issue by jmcdjyu** [antvis/G6#5069]
### 问题描述

V5 入门-快速上手-CDN方式实例代码无法运行，报错：Uncaught ReferenceError: G6 is not defined
文档中，完整代码中引用的G6库为：
https://gw.alipayobjects.com/os/lib/antv/g6/5.0.0-beta.21/dist/g6.min.js

### 重现链接

不会用，没有

### 重现步骤

1. 复制 https://g6-next.antv.antgroup.com/manual/getting-started#完整代码 这个URL中的代码
2. 保存为本地index.html，去掉 /* 图的画布容器 */ 和 /* 引入 G6 */ 这两个注释
3. 用chrome或edge浏览器打开index.html

### 预期行为

我期望看到图显示，但是看到了白屏页面，F12进入调试模式，发现报错。

### 平台

- 操作系统:  Windows 10
- 网页浏览器: Google Chrome
- G6 版本: 5.0-alpha

### 屏幕截图或视频（可选）

![image](https://github.com/antvis/G6/assets/21144594/ec414d1b-c02c-450d-bdf9-64718d1292a4)
![image](https://github.com/antvis/G6/assets/21144594/d4e1ab7d-210e-465b-9016-35104c657767)

**Comment by hustcc** [comment]
@jmcdjyu 应该是需要把代码中的 G6 改成 G6V5，5.0 版本当前打包的 umd 挂在全局变量名为 G6V5。

**Comment by slimming-fat** [comment]
> @jmcdjyu 应该是需要把代码中的 G6 改成 G6V5，5.0 版本当前打包的 umd 挂在全局变量名为 G6V5。

还是报错
![image](https://github.com/antvis/G6/assets/126549527/a219d405-f39b-4359-bcab-1b40d7bdc5b8)

**Comment by slimming-fat** [comment]
> https://gw.alipayobjects.com/os/lib/antv/g6/5.0.0-beta.21/dist/g6.min.js

@jmcdjyu 使用这个js：https://gw.alipayobjects.com/os/lib/antv/g6/4.8.23/dist/g6.min.js
