### ISSUE TITLE
树图，graph.data()+graph.refresh()更新数据导致节点collapsed第二次点击失效，改如何编写代码规避该问题

### ISSUE THREAD

**Issue by easylu** [antvis/G6#5070]
### 问题描述

需求：树图，编辑数据时，需要更新整个树图的数据，但不期望缩放、位置、定制节点和边的当前样式不变。
实现方式：更新数据使用了 graph.data(newData) + graph.refresh() 刷新；点击节点，监听是否点击的收折图标来变更节点的 collapsed属性
问题：
1、更新数据前，点击节点的收折图标都能正确收折。
2、点击节点触发数据更新（codesandbox中用点击节点主体触发数据更新）
3、然后点击收折按钮，第一次成功响应收折了，第二次点击就无效了，有看到collapsed属性更新是正确的

### 重现链接

https://codesandbox.io/s/flamboyant-rgb-h4c3kj?file=/index.js

### 重现步骤

1、更新数据前，点击节点的收折图标都能正确收折。
2、点击节点触发数据更新（codesandbox中用点击节点主体触发数据更新）
3、然后点击收折按钮，第一次成功响应收折了，第二次点击就无效了，有看到collapsed属性更新是正确的

### 预期行为

树图数据更新后，点击收折有效

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
更换数据应该使用 graph.changeData

不需要 graph.refresh() 这个 API 已经无用

**Comment by easylu** [comment]
> 更换数据应该使用 graph.changeData
> 
> 不需要 graph.refresh() 这个 API 已经无用

graph.changeData 会重新渲染，导致拓扑树的位置、缩放、收折、点边的自定义样式状态等丢失，看API手册提到了 refresh() 只刷新数据不重新渲染才使用的。不知是否有更好的实现方式
