### ISSUE TITLE
使用registerEdge创建边线，在afterDraw里面动态设置箭头显示和隐藏没有生效

### ISSUE THREAD

**Issue by hx8321** [antvis/G6#5072]
### 问题描述

![image](https://github.com/antvis/G6/assets/24654315/5ef1644a-8226-497a-8f78-d4830ff97950)

### 重现链接

https://codesandbox.io/s/amazing-gould-3dm7nl?file=/index.js:331-340

### 重现步骤

![image](https://github.com/antvis/G6/assets/24654315/0cf63b40-4e7a-4ee2-b810-4b33818bf349)

### 预期行为

有什么办法可以动态设置边线的箭头显示和隐藏

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
draw、afterDraw 这些方法已经消费了配置绘制了图形，不应该在这些方法里面去修改配置，因为绘制的时候已经感知不到了。可以拿到图形直接修改样式
const keyShape = group.get('children')[0]
const endArrow = keyShape.attr('endArrow');
keyShape.attr({ endArrow: { ...endArrow, opacity: 0.8 } })
