### ISSUE TITLE
关系图的数据，但要根据业务的某个属性进行分层展示，请问可以用什么布局？

### ISSUE THREAD

**Issue by xiaoSS-developer** [antvis/G6#5074]
### 问题描述

如题

### 重现链接

https://codesandbox.io/s/focused-sid-s69qxq?file=/index.js

### 重现步骤

需求：
总体布局要是一个层级结构，类似书架式的；但是数据是关系型的；
要求每行展示10个节点，多了要折行；
且点击某个节点的时候要进行动态请求，把请求后的节点和边的数据重新渲染到布局中；还要保持原有数据位置不变；

实现：
我现在是用ComboCombined的布局方式，外层自定义了一个布局，内层是用的grid；
问题：
但每次动态请求了之后，其他节点位置会变；
gird内的布局也会突然变化，就是无法做到设定的列数；
而且想让combo的默认样式都隐藏，包括hover、active样式都不出现；
界面明明设置了padding，为什么节点距离combo的边还是那么近；

所以不禁怀疑我用的布局是否是对的？是不是自己去计算每个节点的位置更合理？以及这些问题能用什么解决？
万分感谢能给解惑！

### 预期行为

1、使用的布局是否合理？
2、基于那个布局，产生的问题该用什么合理的方式能解决？

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.8.22 ... ]

**Comment by Yanyan-Wang** [comment]
看下这里修改后的配置是否可行：https://codesandbox.io/s/misty-snow-ryg3r5
