### ISSUE TITLE
g6 树状图 自定义节点hover时，如何修改文本样式？

### ISSUE THREAD

**Issue by DCX-329** [antvis/G6#5076]
### 问题描述

自定义节点增加交互时，不知如何修改当前hover节点的文本样式，hover更改当前节点的rect样式是没问题的

### 重现链接

https://g6.antv.antgroup.com/api/items/item-methods#itemgetcurrentstatesstyle

### 重现步骤

文档只提供获取当前节点样式的方法，不知如何重写

### 预期行为

希望文档能提供方法，如果更改节点文本样式

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
如果你的自定义节点没有复写 setState，可以沿用内置节点配置状态样式的方法，指定图形名称设置其状态样式，看这个文档的“子图形状态样式” 部分

https://g6.antv.antgroup.com/manual/advanced/state-new#%E5%AE%9A%E4%B9%89%E7%8A%B6%E6%80%81
