### ISSUE TITLE
v5 演示代码报错，请检查

### ISSUE THREAD

**Issue by kingyue737** [antvis/G6#5078]
### 问题描述

很多官网示例无法运行

### 重现链接

https://g6-next.antv.antgroup.com/zh/examples/tool/toolbar/#toolbar

### 重现步骤

1.进入页面
2.报错 

### 预期行为

v4 的文档没有这个问题  

### 平台

- 操作系统: [Windows 11]
- 网页浏览器: [Edge 118.0.2088.46]
- G6 版本: [5.0 beta]

### 屏幕截图或视频（可选）

![image](https://github.com/antvis/G6/assets/40021217/0394a192-8ad9-430a-8eae-c7b4fd80f915)

**Comment by Yanyan-Wang** [comment]
beta 暂时略不稳定，火热开发中。更新了一波，demo 走查了一遍，刷新看看～有问题烦请随时提 issue
