### ISSUE TITLE
missing CONTRIBUTING.md

### ISSUE THREAD

**Issue by curious-broccoli** [antvis/G6#5081]
### Describe the bug

When creating a pull request the following template for it is shown and mentions a CONTRIBUTING.md guide which doesn't exist.

> Thank you for your pull request. Please review below requirements.Bug fixes and new features should include tests and possibly benchmarks.
Contributors guide: https://github.com/antvis/g6/blob/master/CONTRIBUTING.md感谢您贡献代码。请确认下列 checklist 的完成情况。Bug 修复和新功能必须包含测试，必要时请附上性能测试
Contributors guide: https://github.com/antvis/g6/blob/master/CONTRIBUTING.md 

### Your Example Website or App

N/A

### Steps to Reproduce the Bug or Issue

1. open pull request

### Expected behavior

a CONTRIBUTING guide should exist

### Platform

any

**Comment by Yanyan-Wang** [comment]
Thanks for reporting. We will fix it ASAP. For now, you could follow the guid here:

- v5: https://github.com/antvis/G6/blob/v5/README.en-US.md#development-50-alpha
- v4: https://github.com/antvis/G6/blob/master/README.zh-US.md#development
