### ISSUE TITLE
V5-beta26 版本 WebGL模式下，layout为force时渲染有问题，部分节点或边渲染不正确。

### ISSUE THREAD

**Issue by lightlib** [antvis/G6#5084]
### 问题描述

布局为force，当然其他的布局也有可能影响没有完全验证。节点或边渲染不正确或直接不显示，官网示例可验证
![image](https://github.com/antvis/G6/assets/5072407/bda24427-b89d-4f7a-b0ce-35fae5d43bdc)

### 重现链接

https://g6-next.antv.antgroup.com/zh/examples/feature/features/#lodStrategy

### 重现步骤

修改render为webgl
![image](https://github.com/antvis/G6/assets/5072407/4441b2cf-84e8-467d-9710-9cbd6b925910)

### 预期行为

应该正常渲染吧，拿到webgl就是不能用layout？？

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by lightlib** [comment]
似乎样式也有出入，，
![image](https://github.com/antvis/G6/assets/5072407/fa639a31-ea16-49e7-9279-50bd2fdebade)
[图片]

**Comment by Yanyan-Wang** [comment]
有 bug ～，更新了，刷新官网看看

**Comment by lightlib** [comment]
更新到beta27后，在vue3 中使用 graph.value.changeData(data); 时仍然不行
 ![image](https://github.com/antvis/G6/assets/5072407/16c94e4e-0f61-4a68-b339-21d6f52a8687)
[图片]

**Comment by Yanyan-Wang** [comment]
可以给个在线复现 demo 吗

**Comment by lightlib** [comment]
https://codesandbox.io/p/sandbox/nostalgic-leaf-slxgx9?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cloiee8yc000a356h8ju0w9bm%2522%252C%2522sizes%2522%253A%255B66.05522682445759%252C33.94477317554241%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cloiee8yb0003356h5xwwq4n4%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cloiee8yb0007356h38spubph%2522%257D%252C%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cloiekb5i01fq356hgcee9wz5%2522%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cloiee8yc0009356hsecmk1an%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cloiee8yb0003356h5xwwq4n4%2522%253A%257B%2522id%2522%253A%2522cloiee8yb0003356h5xwwq4n4%2522%252C%2522activeTabId%2522%253A%2522cloief0x500c3356hb2etbrtq%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cloiee8yb0002356hwd004buq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522cloieepa9007t356hgcfnd13j%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522id%2522%253A%2522cloief0x500c3356hb2etbrtq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522id%2522%253A%2522cloiejfkz00w6356hu3i0ag5t%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522cloiee8yc0009356hsecmk1an%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cloiee8yc0008356h8x6jhlea%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252Fabout%2522%257D%255D%252C%2522id%2522%253A%2522cloiee8yc0009356hsecmk1an%2522%252C%2522activeTabId%2522%253A%2522cloiee8yc0008356h8x6jhlea%2522%257D%252C%2522cloiee8yb0007356h38spubph%2522%253A%257B%2522id%2522%253A%2522cloiee8yb0007356h38spubph%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cloiee8yb0004356h88zj8yqm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522cloiee8yb0006356hrtba2wxd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522preview%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cloiee8yb0004356h88zj8yqm%2522%257D%252C%2522cloiekb5i01fq356hgcee9wz5%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cloiek8ms01fm356hqimf3iqw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cloiekbsr00fjegd93hv6hwlo%2522%257D%255D%252C%2522id%2522%253A%2522cloiekb5i01fq356hgcee9wz5%2522%252C%2522activeTabId%2522%253A%2522cloiek8ms01fm356hqimf3iqw%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D
