### ISSUE TITLE
内网请求不到https://unpkg.com/@antv/layout@0.3.23/dist/layout.min.js

### ISSUE THREAD

**Issue by purpletastes** [antvis/G6#5085]
### 问题描述

请教一个问题：我用的g6.Graph但是在打包的文件中会有https://unpkg.com/@antv/layout@0.3.23/dist/layout.min.js 这个路径，在内网云桌面会没有网络，加载这个文件报错，导致图形渲染不正常，但是有网络的时候是正常的，因为这个资源没有加载成功导致报错。请问这个怎么处理呢？

### 重现链接

暂无

### 重现步骤

![image](https://github.com/antvis/G6/assets/19222357/1ad938aa-b382-41ae-84ca-2f6474ede74e)

### 预期行为

我期望图形是正常显示的，但是不是

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by simpleoo0o** [comment]
https://g6.antv.antgroup.com/manual/middle/layout/webworker

**Comment by Yanyan-Wang** [comment]
这个是放在外网的，如果你访问不到，需要下载之后上传到你内网可访问的 cdn 上
