### ISSUE TITLE
plugin menu异步加载数据

### ISSUE THREAD

**Issue by gtx-titanx** [antvis/G6#5086]
### 问题描述

您好，想请问下需求是右键点击节点展示菜单，菜单数据是通过ajax获取，第一次点击时发出请求获取到数据，但是菜单没能加载到数据，再点击一次才能正确的加载刚刚获取的菜单数据，这种情况要怎么解决

### 重现链接

无

### 重现步骤

无

### 预期行为

希望右击节点调取ajax数据能正确加载到菜单上

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

https://github.com/antvis/G6/assets/50905648/feb87535-13b7-4753-a944-c5aa243194c2

**Comment by Yanyan-Wang** [comment]
v4 不支持～ v5 支持，v5 正在 beta 中，欢迎试用：https://g6-next.antv.antgroup.com/zh/examples/tool/contextMenu/#contextMenu
<img width="456" alt="image" src="https://github.com/antvis/G6/assets/29593318/4a7717f8-d1cb-47a3-bab4-665b3f7d677b">


当然也欢迎社区朋友给 v4 提 PR 共建～

**Comment by zyh0yh** [comment]
我也出现同样的问题，我返回了一个带有slot的 div外层盒子，并给slot 传递了节点的data，第一次点击菜单拿不到传递的data，第二次才生效
