### ISSUE TITLE
trendTimeBar 的 SliderOption['handlerStyle'] 类型声明与实际不符

### ISSUE THREAD

**Issue by iahu** [antvis/G6#5095]
### 问题描述

在 `SliderOption` [类型定义](https://github.com/antvis/G6/blob/master/packages/plugin/src/timeBar/trendTimeBar.ts#L66)中， handlerStyle 还有一个 [`style?: ShapeStyle`](https://github.com/antvis/G6/blob/master/packages/plugin/src/timeBar/trendTimeBar.ts#L75) 属性，从这个定义可以推测出应该使用 style 属性来设置  handler 的样式。

```ts
handlerStyle?: {
    width?: number;
    height?: number;
    style?: ShapeStyle;
};
```

但在代码中，实际上[代码](https://github.com/antvis/G6/blob/master/packages/plugin/src/timeBar/trendTimeBar.ts#L454)里是将  `handlerStyle` 当成 `style` 对象来使用和传递的。从而导致设置 `handlerStyle.style` 不生效。

### 重现链接

https://github.com/antvis/G6/blob/master/packages/plugin/src/timeBar/trendTimeBar.ts

### 重现步骤

查看 [266](https://github.com/antvis/G6/blob/master/packages/plugin/src/timeBar/trendTimeBar.ts#L266) 和 [454](https://github.com/antvis/G6/blob/master/packages/plugin/src/timeBar/trendTimeBar.ts#L454)

### 预期行为

修改类型定义或代码逻辑

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yanyan-Wang** [comment]
可以来个 PR 共建一波～～
