### ISSUE TITLE
dagre布局，自定义node时（jsx或者react组件）,边位置错乱

### ISSUE THREAD

**Issue by yongchaoo** [antvis/G6#5096]
### Describe the bug

dagre布局，自定义node时（jsx或者react组件）有问题：
- 边位置错乱
- 有时边折线拐弯

如图：

![WeChatWorkScreenshot_63c4dab2-d8ef-4082-902a-32e3f27a31e2](https://github.com/antvis/G6/assets/26200085/204d55f8-bd4c-4acc-9021-0c3baf2ca931)

![Snipaste_2023-10-30_18-01-06](https://github.com/antvis/G6/assets/26200085/87e11818-0e7f-4e75-a182-42271e6bc96b)

和这个问题类似，他的问题我也遇到过：https://github.com/antvis/G6/issues/4435

### Your Example Website or App

https://jsfiddle.net/xiaohei001/0jt97cxk/43/

### Steps to Reproduce the Bug or Issue

https://jsfiddle.net/xiaohei001/0jt97cxk/43/

### Expected behavior

边能完整画出来，有三角，位置正确

### Platform

- OS: [e.g. macOS]
- Browser: [e.g. Chrome]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
我这里看到的你发的 demo 每个节点左侧有一大块空白，像是边没连到位，原因是箭头的偏移量设置问题，直线缩短给箭头的偏移量留出位置导致。如下修改：
<img width="1069" alt="image" src="https://github.com/antvis/G6/assets/29593318/921a7b1e-c587-43c1-be8f-d26dcf0f151a">


如果是你截图中的问题，尝试给节点设置 anchorPoints，即边连入的位置，边也可以设置选择对应的连入位置，参考文档：https://g6.antv.antgroup.com/manual/middle/elements/nodes/anchorpoint

<img width="393" alt="image" src="https://github.com/antvis/G6/assets/29593318/5c0e8448-6b0b-4a34-9b37-e3f9a24764f9">

**Comment by Dawnwangzi** [comment]
@Yanyan-Wang 我也有同样的问题，然后在例子里试了一下，试出来的效果跟你的不太一样，可以帮忙看看是差在哪里吗？
怎么能让连线分布的比较均匀？
![111111](https://github.com/antvis/G6/assets/20938424/c677209e-643a-436f-9048-cdce6a666843)

**Comment by yongchaoo** [comment]
> 我这里看到的你发的 demo 每个节点左侧有一大块空白，像是边没连到位，原因是箭头的偏移量设置问题，直线缩短给箭头的偏移量留出位置导致。如下修改： <img alt="image" width="1069" src="https://user-images.githubusercontent.com/29593318/279917441-921a7b1e-c587-43c1-be8f-d26dcf0f151a.png">
> 
> 如果是你截图中的问题，尝试给节点设置 anchorPoints，即边连入的位置，边也可以设置选择对应的连入位置，参考文档：https://g6.antv.antgroup.com/manual/middle/elements/nodes/anchorpoint
> 
> <img alt="image" width="393" src="https://user-images.githubusercontent.com/29593318/279917715-5c0e8448-6b0b-4a34-9b37-e3f9a24764f9.png">



> 我这里看到的你发的 demo 每个节点左侧有一大块空白，像是边没连到位，原因是箭头的偏移量设置问题，直线缩短给箭头的偏移量留出位置导致。如下修改： <img alt="image" width="1069" src="https://user-images.githubusercontent.com/29593318/279917441-921a7b1e-c587-43c1-be8f-d26dcf0f151a.png">
> 
> 如果是你截图中的问题，尝试给节点设置 anchorPoints，即边连入的位置，边也可以设置选择对应的连入位置，参考文档：https://g6.antv.antgroup.com/manual/middle/elements/nodes/anchorpoint
> 
> <img alt="image" width="393" src="https://user-images.githubusercontent.com/29593318/279917715-5c0e8448-6b0b-4a34-9b37-e3f9a24764f9.png">

似乎不好使
