### ISSUE TITLE
nodeSate， 如果在data中设置了node的keyShape 的style，graph.setItemState时，state状态样式无效

### ISSUE THREAD

**Issue by rudyzou** [antvis/G6#5099]
### Describe the bug

nodeSate， 如果在data中设置了node的keyShape 的style，graph.setItemState时，state状态样式无效

### Your Example Website or App

官网demo

### Steps to Reproduce the Bug or Issue

1.在初始化data中设置node的keyShape的style，如fill
2. 定义在nodeState中定义 node的keyShape的状态样式
3.在调用graph.setItemState()时，keyShape的样式无法变更为nodeState中定义的样式

### Expected behavior

1.在初始化data中设置node的keyShape的style，如fill
2. 定义在nodeState中定义 node的keyShape的状态样式
3.在调用graph.setItemState()时，keyShape的样式可以变更为nodeState中定义的样式

### Platform

- OS: Windows
- Browser:Chrome
- Version: 5.0.0-beta.26

**Comment by Yanyan-Wang** [comment]
给个在线 demo 看看？
