### ISSUE TITLE
G6 脑图changeData()更新数据之后 无法拖拽,控制台有报错

### ISSUE THREAD

**Issue by huifeidekaola** [antvis/G6#5102]
### 问题描述

<img width="502" alt="image" src="https://github.com/antvis/G6/assets/44389022/2cd7d73f-0240-4f9b-b402-0055c14def61">
在使用changeData()更新数据之后，对脑图进行删除节点，无法拖拽脑图，控制台报错如下
数据确认是没问题的；看着报错觉得是视图更新的问题，求助解答。

### 重现链接

无

### 重现步骤

1.

### 预期行为

期望可以正常拖拽

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![1698815916433](https://github.com/antvis/G6/assets/44389022/4f59b8ef-9e5c-45e6-84a5-bcbe01c60158)

**Comment by huifeidekaola** [comment]
更新数据之后看到了控制台的这两个提示
![image](https://github.com/antvis/G6/assets/44389022/41acbe5b-fd5d-4950-90f5-cc5eff33a797)



![image](https://github.com/antvis/G6/assets/44389022/6041dc2d-6693-4c8c-a35d-c580f37c1f90)

**Comment by Yanyan-Wang** [comment]
从报错来看，是不是树图没有配置 layout？树图必须要配置布局哈。还有可以检查一下数据里面每个节点都有唯一的 string id 吗。都没有问题的话，给个在线复现 demo 看看吧
