### ISSUE TITLE
如何过滤？ how to filter data? 

### ISSUE THREAD

**Issue by neolee6053** [antvis/G6#5104]
### 问题描述

https://github.com/antvis/G6/issues/2837
我看见两年前有人问过，答案是用 hideItem()
请问现在，还是一样吗？ 有没有setData之类的function? :)

### 重现链接

https://codesandbox.io/s/new

### 重现步骤

如上

### 预期行为

如上

### 平台

- 操作系统: [ Window]
- 网页浏览器: [Google Chrome,x]
- G6 版本: [4.8.17 ]

**Comment by Yanyan-Wang** [comment]
不太清楚你这里筛选数据的原始需求，可以通过 changeData 来更换数据

**Comment by neolee6053** [comment]
太好了！
