### ISSUE TITLE
如何阻止节点拖入combo？

### ISSUE THREAD

**Issue by toddmark** [antvis/G6#5106]
### 问题描述

在我的场景中，有些节点不允许被拖入combo中，请问该如何使用相关API？

### 重现链接

https://stackblitz.com/

### 重现步骤

在我的场景中，有些节点不允许被拖入combo中，请问该如何使用相关API？

### 预期行为

期望能够控制节点能否被拖入combo中的行为。

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by xiaoSS-developer** [comment]
https://g6.antv.antgroup.com/manual/middle/states/default-behavior#drag-node 这里面有个onlyChangeComboSize可以配置不将节点从 Combo 中拖出或将节点拖入到 Combo 中，设置为true就行。
不知道能不能解决你的问题

**Comment by Yanyan-Wang** [comment]
楼上的方法是对的～，另外 drag-node 的 shouldEnd 和 shouldBegin 也可以尝试一下

**Comment by AntarcticPresident** [comment]
> https://g6.antv.antgroup.com/manual/middle/states/default-behavior#drag-node 这里面有个onlyChangeComboSize可以配置不将节点从 Combo 中拖出或将节点拖入到 Combo 中，设置为true就行。 不知道能不能解决你的问题

hi，请问一下，这个参数有倒是有，怎么修改啊？
给的例子就是default，具体的参数在哪里改？
谢谢~

**Comment by toddmark** [comment]
@xiaoSS-developer onlyChangeComboSize 这个属性是有效的。不过没有完全解决我的问题。我在拖某类节点A时，需要禁止拖入Combo的行为，但我在拖某类节点B时，需要允许拖入Combo的行为。

由此，如果使用onlyChangeComboSize直接禁用。不满足我拖动B类节点行为。这就带来一个新的问题：需要动态修改 drag-node的配置，可惜，我在setMode中没有找到相关方案。请问如何动态修改 setMode 的配置呢？比如： setMode("drag-node", {test: true}}
