### ISSUE TITLE
能否在graph实例创建完成后再注册timebar插件？

### ISSUE THREAD

**Issue by XiaoRIGE** [antvis/G6#5109]
### 问题描述

创建graph实例的时候有可能没有nodes的数据，后续特定操作完成后通过changedata改变了界面数据，可以再拿到数据的时候再注册timebar插件吗

### 重现链接

www.test.com

### 重现步骤

1.进入页面，画布通过接口获取部分数据，此时没有timebar依赖数据
2.点击按钮，获取新数据，
3.期望再拿到新数据后再注册timebar插件，应该如何做

### 预期行为

1.进入页面，画布通过接口获取部分数据，此时没有timebar依赖数据
2.点击按钮，获取新数据，
3.期望再拿到新数据后再注册timebar插件，应该如何做

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Yangyoung-max** [comment]
同问，怎么实时更新timeBar里面的data

**Comment by AF-Klara** [comment]
可以使用graph.addPlugin/removePlugin添加移除插件
