### ISSUE TITLE
如何获取canvas真实宽度，目前是自适应。

### ISSUE THREAD

**Issue by yucccc** [antvis/g6#511]
目前需要在父盒子加一个滚动条 所以需要设置canvas的宽度 让内容撑满出现滚动条

**Comment by TomHuangCN** [comment]
graph.getWidth();

**Comment by yucccc** [comment]
可能是我表述有问题 我是想获取canvas里面内容的真实宽度 @TomHuangCN

**Comment by Rico1900** [comment]
@yucccc 的意思可能是autoSize这个fitView没有了，我也遇到了这个问题，请问怎么解决？

**Comment by TomHuangCN** [comment]
autoSize 有时会出现画布超大，从而导致严重的性能问题，2.0 不再提供了。

**Comment by guohaiping521** [comment]
这个问题解决了吗，我也是在父盒子加一个滚动条，需要知道这个 canvas的真实宽度，现在是我自个计算的每个node与line的宽度，然后相加，给canvas设置的宽度，但是有很多问题，官方有这样的方法吗
