### ISSUE TITLE
缩进树图折线线条粗细不均

### ISSUE THREAD

**Issue by weinibear** [antvis/G6#5114]
### 问题描述

参照官方缩进树树图demo绘制树图，初始绘制出来的缩进树折线线条粗细不均。（没有经过缩放）。发现官方的demo绘制出来的折线就存在粗细不均情况 https://g6.antv.antgroup.com/zh/examples/tree/indented/#filesystem。数据多的时候大屏下展示非常明显

### 重现链接

官方demohttps://g6.antv.antgroup.com/zh/examples/tree/indented/#filesystem

### 重现步骤

查看官方demo，即可看到绘制的线条粗细不均，不明显的话可以将线条颜色改为红色，以及多添加点数据即可看得很明显。需要重复画的路径线条更粗，颜色更深，好像叠加绘制了一样。

### 预期行为

折线线条应该不同部分粗细也保持一样

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.8.17 ]

### 屏幕截图或视频（可选）

![image](https://github.com/antvis/G6/assets/35034336/f58fdb37-4e32-4d59-8592-caacacf5ec51)

**Comment by oo10** [comment]
你好 请问解决了吗

**Comment by lemonliu2023** [comment]
有解决方案吗
