### ISSUE TITLE
G6 5.0.0-beta.27   cursor: pointer 问题

### ISSUE THREAD

**Issue by opensourcex123** [antvis/G6#5119]
### Describe the bug

在节点的keyshape中设置cursor:pointer时，只有在鼠标长按在节点上时才会生效，而不是hover生效，5.0的文档中的实例几乎都有这个问题。

### Your Example Website or App

none

### Steps to Reproduce the Bug or Issue

1.在节点的keyshape中配置cursor：pointer属性
2.鼠标hover在节点上不生效
3.鼠标长按在节点上生效

### Expected behavior

我希望鼠标放在节点上就显示cursor:pointer属性而不是长按

### Platform

- OS: MacOS
- Browser: Chrome
- Version: 5.0.0-beta.27

**Comment by Aarebecca** [comment]
你好，我们会尽快解决这个问题

**Comment by Aarebecca** [comment]
你好，G6 5.0 正式版已结局该问题
