### ISSUE TITLE
@antv/g6@beta版本下，拖拽、滚动或缩放画布时，node.getBBox没有变化

### ISSUE THREAD

**Issue by k644606347** [antvis/G6#5125]
### Describe the bug
在@antv/g6@5.0.0-beta.27版本下，
拖拽、滚动或缩放画布时，node.getBBox没有变化
![Large GIF (1124x672)](https://github.com/antvis/G6/assets/6951527/52e1a881-54ba-475f-a021-10ddaedda562)
<img width="718" alt="image" src="https://github.com/antvis/G6/assets/6951527/4608fe76-f319-4aa8-9842-407366d22c05">
这会导致调用getBBox的程序异常，辛苦看下。

### Your Example Website or App

https://codesandbox.io/s/test-item-bbox-lldf2l?file=/index.js

### Steps to Reproduce the Bug or Issue

https://codesandbox.io/s/test-item-bbox-lldf2l?file=/index.js

### Expected behavior

我记得v4里的```node.getBBox```会随画布移动而变化，请看下v5这里实现是否有bug

### Platform

- OS: [macOS]
- Browser: [Chrome]
- Version: [119]

**Comment by yk329** [comment]
这个问题有没有好的解决方法啊！我也遇到了

**Comment by Aarebecca** [comment]
你好，初步判定这应该是一个 Bug，我们会尽快修复

**Comment by Aarebecca** [comment]
正式版 G6 5.0 已解决，可参考：https://g6-next.antv.antgroup.com/examples/element/custom-node/#react-g
