### ISSUE TITLE
缩小和放大画布会导致tooltip的定位发生偏移

### ISSUE THREAD

**Issue by zyh0yh** [antvis/G6#5126]
### Describe the bug

缩小和放大画布会导致tooltip的定位发生偏移

### Your Example Website or App

https://g6-next.antv.antgroup.com/examples/tool/tooltip/#tooltipPlugin

### Steps to Reproduce the Bug or Issue

1.打开5.0示例文档中提示框示例
2.在 modes配置中增加 'zoom-canvas','drag-canvas'，使示例可缩放和拖拽
3.先不进行任何操作，将鼠标移入节点查看和记录tooltip的postion位置
4.进行缩放，再次鼠标移入节点查看和记录tooltip的postion位置

### Expected behavior

tooltip 的 fixtoNode 可以不受画布缩放和拖拽的影响，更灵活的配置，并且希望增加一个topcenter，center等 定位参数

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [5.0.0-beta.27]

**Comment by fatyrify** [comment]
遇到了相似的问题，G6.TreeGraph changeSize api调用后，Tooltip的offset发生偏差，鼠标直接出现在了Tooltip里，导致鼠标一致悬停tooltip不再自动隐藏

**Comment by mxluomx** [comment]
我也遇到了，你们怎么解决的

**Comment by unclepan** [comment]
1:定义个ref
const tooltipRef = useRef(null);

2:将你的插件赋值以便于后面使用
const tooltip = tooltipFn();
tooltipRef.current = tooltip;

3:在node:mouseenter事件上监听，动态改变 tooltip的offsetX和offsetY
graph.on('node:mouseenter', (evt) => {
      const graph = graphRef.current;
      const zoom = graph.getZoom();
      tooltipRef.current._cfgs.offsetX = -(36 * zoom);
      tooltipRef.current._cfgs.offsetY = 38 * zoom;
});

**Comment by unclepan** [comment]
> 我也遇到了，你们怎么解决的

1:定义个ref
const tooltipRef = useRef(null);

2:将你的插件赋值以便于后面使用
const tooltip = tooltipFn();
tooltipRef.current = tooltip;

3:在node:mouseenter事件上监听，动态改变 tooltip的offsetX和offsetY
graph.on('node:mouseenter', (evt) => {
const graph = graphRef.current;
const zoom = graph.getZoom();
tooltipRef.current._cfgs.offsetX = -(36 * zoom);
tooltipRef.current._cfgs.offsetY = 38 * zoom;
});
