### ISSUE TITLE
记录节点位置和缩放比例再次渲染

### ISSUE THREAD

**Issue by AF-Klara** [antvis/G6#5128]
### 问题描述

我想记录一份节点的x、y位置和画布的缩放比比例，当我再次进来时展示我上一次的操作后的状态，
但我发现当缩放和平移画布是会导致出现不可控的偏移，无法正确的复原之前的操作

### 重现链接

https://codesandbox.io/s/damp-sky-3cnryw?file=/src/App.vue

### 重现步骤

1. 拖动节点时
 初始状态
![image](https://github.com/antvis/G6/assets/74236806/f6a057e5-8b8d-486b-b91c-7f2d67f13e57)
只拖动节点
![image](https://github.com/antvis/G6/assets/74236806/89008bbc-a76a-4947-9457-281496dafb1e)
 点击记录
 点击复原(展示符合预期)

2. 拖动节点与缩放画布
![image](https://github.com/antvis/G6/assets/74236806/a25d65f9-a77c-4567-a33a-7fa9e4448a1e)
点击记录
点击复原(位置偏移)
![image](https://github.com/antvis/G6/assets/74236806/e2007269-b4b7-43c3-91d4-9681d3397442)

### 预期行为

节点/节点和画布同时进行操作时，点击复原能还原记录时的状态

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

https://github.com/antvis/G6/assets/74236806/4c4a28ab-09e2-4579-8f7c-5835b4c8574a

### 补充说明（可选）

对数据进行排列组合

**Comment by GemT27** [comment]
通过矩阵matrix来实现吧
https://codesandbox.io/p/sandbox/upbeat-marco-sp9xvx?file=%2Fsrc%2FApp.vue

**Comment by GemT27** [comment]
画布缩放和平移画布可以通过matrix记录复位；节点位置你则需要监听node:drag事件保存相对应的节点位置吧
