### ISSUE TITLE
G6系统图能画成下面这样的吗？有什么建议的吗

### ISSUE THREAD

**Issue by jingslunt** [antvis/g6#513]
![](http://ww1.sinaimg.cn/large/6e557adaly1fvrc4ifq7qj210q0tqn28.jpg)

**Comment by TomHuangCN** [comment]
那么好看的图，数据贴下，我来画

**Comment by jingslunt** [comment]
@TomHuangCN 没数据  不过还是喜欢这类图文结合的图
