### ISSUE TITLE
scroll-canvas中 direction: 'x' 不生效。

### ISSUE THREAD

**Issue by Nightsky-Dec** [antvis/G6#5145]
### 问题描述

{
  type: 'scroll-canvas',
  direction: 'x',
},
direction为X方向时，滚动不起作用。
方向为Y时，滚动可以正常起作用。

### 重现链接

https://stackblitz.com/edit/react-t16utk?file=index.js

### 重现步骤

1.进入页面
2.在图中使用滚动轴，滚动无效

### 预期行为

滚动轴可使页面基于X轴滚动，或者有横向滚动条可使用。

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by yvonneyx** [comment]
![Kapture 2023-11-15 at 18 39 37](https://github.com/antvis/G6/assets/55794321/c9f63658-ed28-41c6-a3c7-44508326576c)
提供的 demo 中基于 x 轴滚动是生效的，再试下？

**Comment by Nightsky-Dec** [comment]
你好。你说的demo是指我发的？还是官方demo(https://g6.antv.antgroup.com/examples/tree/compactBox/#basicCompactBox)？
我试的都不行，能不能把你这个能正常使用的代码发个链接看一下。

**Comment by RealRio** [comment]
> 你好。你说的demo是指我发的？还是官方demo([https://g6.antv.antgroup.com/examples/tree/compactBox/#basicCompactBox)？](https://g6.antv.antgroup.com/examples/tree/compactBox/#basicCompactBox)%EF%BC%9F) 我试的都不行，能不能把你这个能正常使用的代码发个链接看一下。

你是windows设备，windows设备就是不能在x轴上左右滚动，这看起来是个bug。

**Comment by k644606347** [comment]
感觉跟硬件设备相关吧，用触摸板可以做到多向滚动，外接鼠标的话只能上下滚动了，无论是mac/linux/windows外接了鼠标都有限制；建议搭配drag-canvas，使用拖拽方式补充左右滚动交互
