### ISSUE TITLE
dagre自动布局，该如何让第一层级的节点初始位置固定在左侧某个固定的坐标

### ISSUE THREAD

**Issue by treeSmile** [antvis/G6#5149]
### 问题描述

dagre自动布局，需要让第一层级的节点初始位置固定在左侧某个固定的坐标，然如何设置

### 重现链接

https://stackblitz.com/edit/react-gkyeqg?file=index.js

### 重现步骤

<img width="1064" alt="g6" src="https://github.com/antvis/G6/assets/63891409/83792062-52da-4f75-a713-0102569935ef">
1、进入重现链接，
2、查看代码
3、如何实现从第一个节点固定在左侧摸个固定的坐标，后续的节点继续按照dagre自动布局

### 预期行为

dagre自动布局，希望让第一层级的节点初始位置固定在左侧某个固定的坐标，同时其余层级继续按dagre自动布局

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

不知道为啥无法添加图片

需求就是想要初始渲染完成后，从第一个节点固定在左侧摸个固定的坐标，后续的节点继续按照dagre自动布局

**Comment by treeSmile** [comment]
尝试了使用moveTo的方法，这样x轴是可以定位到的，但是y轴就不行了，感觉moveTo应该是基于生成的整个图表去定位的；
主要是想x轴固定100px,y轴居中，应该用什么方法呢

**Comment by jsercom** [comment]
设置X,Y，禁用 layout

**Comment by treeSmile** [comment]
怎么设置x,y能达到dagre自动布局的效果呢
