### ISSUE TITLE
使用downloadFullImage下载图片时，报错提示内存不足 

### ISSUE THREAD

**Issue by yeyusama** [antvis/G6#5154]
### 问题描述

如果不进行缩放限制 缩放到最大的话会更大 直接下载不了

但若缩小的太多又会导致下载的图片不清晰

目前1.5倍率也会有点不太清晰  

目前数据量较多 1.5倍的情况下 会直接报错  偶尔也会下载下来一个空的图片
![image](https://github.com/antvis/G6/assets/43950611/10367389-4801-4405-959c-3fc1c1c9d5c3)
![image](https://github.com/antvis/G6/assets/43950611/e3f56395-255f-4fc8-ab93-1479b9644bf7)

### 重现链接

https://github.com/antvis/G6/issues/new?assignees=&labels=&projects=&template=bug_report_chinese.yml

### 重现步骤

![image](https://github.com/antvis/G6/assets/43950611/6d774c2b-a177-4a32-b7f1-ffa20be7ea77)

### 预期行为

能否不进行倍率限制 也能够正常下载 

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![image](https://github.com/antvis/G6/assets/43950611/29fb234a-6025-46b2-b72f-9d9370efae28)
![922dc2b160d9c62139c20ad204a1812](https://github.com/antvis/G6/assets/43950611/6303d401-2998-46f8-ba75-3db33c428075)

### 补充说明（可选）

![image](https://github.com/antvis/G6/assets/43950611/5937f405-f49a-4a57-9d64-c15bd155480e)

**Comment by Sunxinqiang** [comment]
遇到的了同样的问题 在windows系统上，图片过大下载下来就是size为0的空图片

**Comment by keminu** [comment]
遇到同样的问题

**Comment by Sunxinqiang** [comment]
应该是浏览器有大小限制，目前我的处理是图片宽高超出13000时，降低清晰度，以保证可以下载
