### ISSUE TITLE
如果在添加数据时切换到其他标签页，然后再切回来，可能会导致图表渲染的问题

### ISSUE THREAD

**Issue by yeyusama** [antvis/G6#5155]
### 问题描述

![image](https://github.com/antvis/G6/assets/43950611/ca9ead06-a1c2-4f1a-9853-ed75f5920a03)
![1700124458486](https://github.com/antvis/G6/assets/43950611/d1b9c028-bf64-4495-b953-cd5ec0e810b6)

在点击加载新增子节点的时候 会去请求后台接口 再去渲染页面 这个过程需要时间，当我在等待加载的时候切换到了另外一个TAB页面去浏览其他的内容  过了一段时间再切换回原页面的时候，这时候请求已经返回。但是 加载出来的数据渲染出来错位了是为什么呢？
如果在加载数据时切换到其他标签页，然后再切回来，可能会导致图表渲染的问题。
这种问题应该如何解决

### 重现链接

https://github.com/antvis/G6/issues/new?assignees=&labels=&projects=&template=bug_report_chinese.yml

### 重现步骤

![image](https://github.com/antvis/G6/assets/43950611/ca9ead06-a1c2-4f1a-9853-ed75f5920a03)

### 预期行为

期望能够正常渲染

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![1700124458486](https://github.com/antvis/G6/assets/43950611/b680ab59-156d-4223-bc89-d8e7bb845a0a)

**Comment by yeyusama** [comment]
有人知道这个问题如何解决吗

**Comment by Aarebecca** [comment]
该问题可能与浏览器策略有关，暂无相关解决方式，你可以通过监听浏览器事件，在当前tab激活的情况下才执行渲染
