### ISSUE TITLE
G6的5.0版本什么时候发布正式版本？Graphin什么时候接入5.0版本？

### ISSUE THREAD

**Issue by fengbozhi** [antvis/G6#5159]
### 问题描述

G6的5.0版本什么时候发布正式版本？Graphin什么时候接入5.0版本？

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

无

**Comment by zzjjbbaa** [comment]
> 你好，G5 6.0预计明年最迟中旬发布正式版本，Graphin会同步跟进

不是5.0吗？
