### ISSUE TITLE
IE11兼容问题-不支持edges边属性？

### ISSUE THREAD

**Issue by sunkangke** [antvis/g6#516]
**官网复制示例“默认-边”到本地运行，google和FireFox两个浏览器正常显示，但IE11只能显示node节点，但边都不能显示，IE是需要有单独的设置还是G6目前就是对IE11支持不是太完善？
IE报错信息如下：**

> DOM7011: 此页上的代码禁用了反向和正向缓存。有关详细信息，请参阅: http://go.microsoft.com/fwlink/?LinkID=291337
> edges.html
> HTML1300: 进行了导航。
> edges.html
> SCRIPT438: 对象不支持“sign”属性或方法
> g6.js (7,92385)
> SCRIPT5007: 无法获取未定义或 null 引用的属性“shape”
> g6.js (7,112584)

**Comment by TomHuangCN** [comment]
写个 codepen： https://codepen.io/DoriTong/pen/pKbLVw

**Comment by TomHuangCN** [comment]
有这个问题，正在排查
