### ISSUE TITLE
graph.updateLayout 之后 自定义的 G6.registerEdge( 'line-dash', ....) 失效了

### ISSUE THREAD

**Issue by RainyNight9** [antvis/G6#5160]
### 问题描述

在用 graph.updateLayout 切换布局之后 
默认自定义的 G6.registerEdge( 'line-dash', ....) 失效了
表现为：在边上自定义了 run 动画，以及箭头，但是在切换布局之后，动画没了，箭头留在的初始位置。

### 重现链接

https://g6.antv.antgroup.com/manual/middle/animation#%E8%99%9A%E7%BA%BF%E8%BF%90%E5%8A%A8%E7%9A%84%E6%95%88%E6%9E%9C

### 重现步骤

`layoutConfig = {
      type: 'circular',
      radius: 300,
      workerEnabled: true
  }
graph.updateLayout(layoutConfig);
graph.layout(true)
`

![image](https://github.com/antvis/G6/assets/20129035/3106ee0f-c7cd-436d-904c-82dc52d8a124)

![image](https://github.com/antvis/G6/assets/20129035/4f24c662-eae8-49d3-8b07-77673520a4a1)

### 预期行为

希望 默认的 自定义边不失效。

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Ourydy** [comment]
请问后来怎么解决的？

**Comment by WangHanZ** [comment]
兄弟解决了吗后来

**Comment by WangHanZ** [comment]
可以监听布局切换，在beforelayout的时候加一个这个        this.graph.edge((edge) => {
          return {
            edge
          }
        })

**Comment by RainyNight9** [comment]
> 兄弟解决了吗后来

绕道似的解决，其实也叫做没解决。就是切换模式重新去渲染。相当于初始渲染。想听听官方人员针对此问题，有什么好的解决办法吗？感觉这个应该算是 bug

**Comment by WangHanZ** [comment]
兄弟切换模式是咋搞得 能说说不

**Comment by RainyNight9** [comment]
> 兄弟切换模式是咋搞得 能说说不

就是切换模式后，重新去渲染，重新初始化.....,最 low 的办法，但是也是能正常加载的办法。。。无奈之举。

**Comment by WangHanZ** [comment]
后面通过new一个layout实例，调用它的init和execute方法可以解决
