### ISSUE TITLE
"electron": "^21.4.4",  plugins中的grid不展示

### ISSUE THREAD

**Issue by guagezuishuai** [antvis/G6#5173]
### 问题描述

用的electron-egg，绘制流程图设置背景网格，背景网格不展示，代码测试过了没问题，放到这个项目里就不行了。

### 重现链接

应用程序没有链接

### 重现步骤

1、下载electron-egg 
2、再项目的frontend中引入g6初始化配置plugins加上grid
3、结果不展示背景网格

### 预期行为

可以看到网格背景

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]  window
- 网页浏览器: [Google Chrome, Safari, Firefox]  electron-egg项目
- G6 版本: [4.5.1 ... ] 4.3.11

**Comment by Aarebecca** [comment]
你好，请提供更多细节和Demo
