### ISSUE TITLE
节点上添加icon为img图片，想让图片呈圆形展示（类似于原生圆角属性）

### ISSUE THREAD

**Issue by Yangyoung-max** [antvis/G6#5207]
### 问题描述

节点上添加icon为img图片，想让图片呈圆形展示（类似于原生圆角属性）

### 重现链接

icon实现圆角效果

### 重现步骤

icon实现圆角效果

### 预期行为

icon实现圆角效果

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![image](https://github.com/antvis/G6/assets/57350459/ef5d9e70-b0fc-4025-b372-790ee8ff6e58)

**Comment by Aarebecca** [comment]
你好，可以尝试使用 clipPath 来对图片进行裁切

**Comment by Yangyoung-max** [comment]
我不是要裁剪节点，而是circle节点上的icon。脱离了框架，我试过图片（icon）onload之后利用canvas进行了裁剪，将icon变圆，但是icon量大还是不可行

**Comment by Yangyoung-max** [comment]
是circle节点上的icon。我试过图片（icon）onload之后利用canvas进行了裁剪，将icon变圆，但是icon量大还是不可行。
也不能运用image的节点，因为节点有的有icon的src，有的没有icon的src，而且src也会存在过期的情况，结合场景就是用circle节点比较好，但是这个icon没办法优雅的变圆。

**Comment by Yangyoung-max** [comment]
之间用的是cytoscape，现在用这个算是迁移了，可是这个icon连个圆角的配置都没有吗。。

**Comment by Yangyoung-max** [comment]
是circle节点上的icon。我试过图片（icon）onload之后利用canvas进行了裁剪，将icon变圆，但是icon量大还是不可行。
也不能运用image的节点，因为节点有的有icon的src，有的没有icon的src，而且src也会存在过期的情况，结合场景就是用circle节点比较好，但是这个icon没办法优雅的变圆。
！！！！！之间用的是cytoscape，现在用这个算是迁移了，可是这个icon连个圆角的配置都没有吗。。。
