### ISSUE TITLE
能否新增一个遮罩层，只凸显选中的节点/边/combo，其他没选中的也能看到

### ISSUE THREAD

**Issue by Ourydy** [antvis/G6#5208]
### 问题描述

现在只有隐藏和显示的方法，隐藏后就看不到整体的布局了

### 重现链接

无

### 重现步骤

无

### 预期行为

数据过多时，想凸显鼠标移入或者选中的边或节点，其他的边和节点用遮罩层遮罩，不至于完全看不到
![QQ截图20231129180234](https://github.com/antvis/G6/assets/104473720/405fbd16-2b14-4814-b81a-03de42d829b7)

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by yvonneyx** [comment]
可以参考高亮相邻节点示例：https://g6-next.antv.antgroup.com/zh/examples/interaction/highlight/#highlightDark

这边先关闭啦，若使用过程中还有任何疑问或问题，请随时再次开启 issue
