### ISSUE TITLE
v5 3d-node 材质纹理贴图

### ISSUE THREAD

**Issue by GemT27** [antvis/G6#5212]
### 问题描述

不知道对于给3d节点设置纹理贴图之后有这个想法吗, 目前我看都是共享着material

> 

### 重现链接

https://g6-next.antv.antgroup.com/examples/item/defaultNodes/#3d-node

### 重现步骤

因为都是共享着material，给某一个节点设置贴图那其他节点也会有贴图

### 预期行为

没有贴图或者和有相同贴图的分别创建Material进行共享

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- G6 版本: [5.0 ]

**Comment by Aarebecca** [comment]
后面会新增这个 feature 的

**Comment by GemT27** [comment]
> 后面会新增这个 feature 的

写了一点，我发现不用共享后自己new Material,会在界面上显示不出来😶

**Comment by Aarebecca** [comment]
> > 后面会新增这个 feature 的
> 
> 写了一点，我发现不用共享后自己new Material,会在界面上显示不出来😶

提供一下具体的代码吧

**Comment by Aarebecca** [comment]
参考该示例，可以给不同的节点设置纹理贴图：https://g6-next.antv.antgroup.com/examples/feature/default/#lite-solar-system
