### ISSUE TITLE
V4.8.23 在设置 modes.default=['drag-node', 'drag-canvas', 'zoom-canvas']后， 浏览器手机浏览模式 graph.on('node:click', ()=>{ }) 不生效

### ISSUE THREAD

**Issue by mountain-has-tree** [antvis/G6#5216]
### Describe the bug
V4.8.23 在设置 `modes.default=['drag-node', 'drag-canvas', 'zoom-canvas'] `（或者数组其中一个）后，监听事件`graph.on('node:click', ()=>{ })` ，点击 node 触发不了事件，无任何反应，
在这样的情况下，如果点击 edge， 会报错：`n.hasLocked is not a function`
![image](https://github.com/antvis/G6/assets/79303988/8847dc33-0e59-46d8-a46d-4d2cea2b1928)
以下为代码，开在G6官网事例页面粘贴生效：
```javascript
import G6 from '@antv/g6';

const container = document.getElementById('container');
const width = container.scrollWidth;
const height = container.scrollHeight || 500;
const graph = new G6.Graph({
  container: 'container',
  width,
  height,
  layout: {
    type: 'force',
    linkDistance: 200
  },
  modes: {
    default: ['drag-node', 'drag-canvas', 'zoom-canvas']
  },
  defaultNode: {
    size: 15,
  },
});

fetch('https://gw.alipayobjects.com/os/antvdemo/assets/data/relations.json')
  .then((res) => res.json())
  .then((data) => {
    graph.data({
      nodes: data.nodes,
      edges: data.edges.map(function (edge, i) {
        edge.id = 'edge' + i;
        edge.label = i;
        return Object.assign({}, edge);
      }),
    });
    graph.render();

    graph.on('node:click', function (e) {
      console.log(e, 'handle-click-node')
    });

    if (typeof window !== 'undefined')
      window.onresize = () => {
        if (!graph || graph.get('destroyed')) return;
        if (!container || !container.scrollWidth || !container.scrollHeight) return;
        graph.changeSize(container.scrollWidth, container.scrollHeight);
      };
  });

```

### Your Example Website or App

https://codesandbox.io/p/sandbox/vigorous-bose-66kwsp?file=%2Fsrc%2FApp.jsx

### Steps to Reproduce the Bug or Issue

1. 在G6 [官网页面](https://g6.antv.antgroup.com/examples/net/forceDirected/#basicForceDirected) 粘贴 Describe the bug 中的代码
2. 打开控制台， 将浏览器切换为手机浏览模式
3. canvas渲染出来后， 点击 node 和点击 edge 
或者
4. 打开 [codesandbox](https://codesandbox.io/p/sandbox/vigorous-bose-66kwsp?file=%2Fsrc%2FApp.jsx)
5. 打开控制台， 将浏览器切换为手机浏览模式
6. 点击 node 和点击 edge

### Expected behavior

期待在v4的版本中可以修复

### Platform

- OS: [ macOS, Windows]
- Browser: [Chrome]
- Version: [4.8.23]

**Comment by mountain-has-tree** [comment]
该情况是在浏览器切换为手机浏览模式下生效的

**Comment by Rikka-S** [comment]
tooltip 自定义交互registerBehavior 也失效了

**Comment by HuColin** [comment]
darw-canvas 的内置 Behavior 里面 preventDefault 了，可以基于 内置 Behavior 去掉 preventDefault 试试
