### ISSUE TITLE
能不能配置让非combo内的节点不能拖入combo，或者在布局的时候实现非combo内的节点一定在combo外部？

### ISSUE THREAD

**Issue by XiaoRIGE** [antvis/G6#5221]
### 问题描述

使用dagre布局，不同layer的节点可能属于同一个combo，希望将相同combo的节点放在一起，保障combo内的节点一定是有相同group字段的。

### 重现链接

www.test.com

### 重现步骤

1.使用dagre布局;
2.依据数据的group字段生成combo;
3.会出现combo圈中不相关的节点的情况

### 预期行为

1.使用dagre布局;
2.依据数据的group字段生成combo;
3.保障combo内节点都有相同的group

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by AntarcticPresident** [comment]
非组内的节点一定在combo外。只不过重叠了。

**Comment by neolee6053** [comment]
我也想知道，如何让非combo内的节点不能拖入combo

**Comment by neolee6053** [comment]
找到了，onlyChangeComboSize。 而且 drag-node 和 drag-combo 都要加

https://github.com/antvis/G6/issues/5106
