### ISSUE TITLE
"@antv/g6": "5.0.0-beta.2"  安装不了，有可用的版本能告知一下吗？

### ISSUE THREAD

**Issue by kingrome2017** [antvis/G6#5228]
### 问题描述

"dependencies": {
    "@antv/g6": "5.0.0-beta.2",
    "core-js": "^3.8.3",
    "vue": "^2.6.14"
  },

npm install --save @antv/g6@5.0.0

以上两种方式都试过，安装不成功

### 重现链接

无

### 重现步骤

"dependencies": {
    "@antv/g6": "5.0.0-beta.2",
    "core-js": "^3.8.3",
    "vue": "^2.6.14"
  },

npm install --save @antv/g6@5.0.0

以上两种方式都试过，安装不成功

### 预期行为

"dependencies": {
    "@antv/g6": "5.0.0-beta.2",
    "core-js": "^3.8.3",
    "vue": "^2.6.14"
  },

npm install --save @antv/g6@5.0.0

以上两种方式都试过，安装不成功

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Aarebecca** [comment]
你好，安装不成功的具体表现是什么
