### ISSUE TITLE
5.0.0 教程中 cdn 链接 404 not found, 从 cdnjs 找了一个但无法使用

### ISSUE THREAD

**Issue by WindBrush** [antvis/G6#5229]
### Describe the bug

- 按照教程中通过 cdn 从 html 直接引入 g6.js
```html
 <script src="https://gw.alipayobjects.com/os/lib/antv/g6/5.0.0/dist/g6.min.js"></script>
```
- 显示链接 404
![cdn404](https://github.com/antvis/G6/assets/22806554/feb166a5-6b10-48d8-8064-15ec5a86dd4e)
- 然后去 cdnjs.com 找了一个 beta 测最新版但无法使用
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Tutorial Demo</title>
  </head>
  <body>
    <!-- 引入 G6 5.0 beta -->
    <!-- <script src="https://gw.alipayobjects.com/os/lib/antv/g6/5.0.0/dist/g6.min.js"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/antv-g6/5.0.0-beta.27/g6.min.js" 
    integrity="sha512-8vio8ib6CD8EbAYKI+Ab3abxV0F25lnbaHhYd01kMbXUN2Q165dJY7g3ILJag3q3zzPa/UzOhmBx0IOWZ19WCQ==" 
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script>
      console.log(G6);
    </script>
  </body>
</html>
```
- console 显示 G6 is not defined
![notwork](https://github.com/antvis/G6/assets/22806554/7eef6b1f-ca5e-429e-9b03-76f90ff2a611)

### Your Example Website or App

just local html demo 

### Steps to Reproduce the Bug or Issue

1. 按照 [5.0.0 教程](https://g6-next.antv.antgroup.com/manual/tutorial/quick-start) 中从 html 引入 g6.js 即可

### Expected behavior

成功从 html 引入 g6.js

### Platform

- OS: Windows10
- Browser: Chrome
- Version: 5.0.0

**Comment by Aarebecca** [comment]
你好，非常抱歉，这是最新的 cdn 地址：https://gw.alipayobjects.com/os/lib/antv/g6/5.0.0-beta.27/dist/g6.min.js
我们会尽快更新相关文档
