### ISSUE TITLE
tree anchor 树节点之间增加额外的连接线

### ISSUE THREAD

**Issue by xxShawn** [antvis/g6#523]
再常规的脑图之外， 需要从某个节点到另外一个节点之间连线。

1. 点击节点如何显示anchor呢
2. 然后从一个节点的anchor连到另外一个节点的anchor

**Comment by xxShawn** [comment]
![_15410583925051](https://user-images.githubusercontent.com/16178276/47839327-5d790500-dded-11e8-9c69-71e3cec91365.png)

**Comment by TomHuangCN** [comment]
没这个特性
