### ISSUE TITLE
G6 v5.0 transform: scale() 导致位置偏移

### ISSUE THREAD

**Issue by Anye7** [antvis/G6#5233]
### 问题描述

scale() 导致定位偏移 在4.x版本可以使用graph.get('canvas').set('supportCSSTransform', true)消除影响  在5.0版本中应该怎么去解决

### 重现链接

无

### 重现步骤

页面使用transform: scale() 导致图渲染位置偏移

### 预期行为

在排除原页面反缩放等方法外 其他类似G6配置相关的解决方法

### 平台

- 操作系统: Windows
- 网页浏览器: Google Chrome
- G6 版本: [5.0.0 ]

**Comment by Aarebecca** [comment]
你好，请提供更详细的说明及示例
