### ISSUE TITLE
节点锁定后，切换布局，该节点还是会参与到布局的计算，导致2个锁定的节点位置变化

### ISSUE THREAD

**Issue by xueshixiang** [antvis/G6#5238]
### Issue Hunt 计划（可选）

- [X] 我同意将这个 Issue 参与 Issue Hunt 计划

### Issue 难度

中等难度

### 问题描述

节点锁定后，切换布局，该节点还是会参与到布局的计算，导致2个锁定的节点位置变化

### 重现链接

无

### 重现步骤

节点锁定后，切换布局，该节点还是会参与到布局的计算，导致2个锁定的节点位置变化

### 预期行为

希望锁定的节点不参与布局的计算

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.5.1 ... ]

**Comment by Aarebecca** [comment]
这不是一个规范的 Issue 类型，请选择 Bug 类型的 Issue
