### ISSUE TITLE
graph.update 更新 edge style 问题

### ISSUE THREAD

**Issue by yacan8** [antvis/g6#524]
如题，v2.1.0版本之后，graph.update更新edge的style没反应

demo:  [https://codepen.io/yacan8/pen/OBKOvO](https://codepen.io/yacan8/pen/OBKOvO)

**Comment by TomHuangCN** [comment]
映射的优先级更高，另起一个字段，更新这个字段，在映射分支里处理

**Comment by oooofeiger** [comment]
> 映射的优先级更高，另起一个字段，更新这个字段，在映射分支里处理
可以说的详细点吗，另起一个新字段？映射分支里处理是怎么处理？

**Comment by oooofeiger** [comment]
我也遇到这个问题了，更新node的样式和label没有反应

**Comment by TomHuangCN** [comment]
就是在写了映射的情况下，把所有这个字段更新的逻辑都放到映射的回掉函数里，用其它有含义的字段做区分。比如：
```js
graph.node(
  color(model) {
    if (mode.error)  return 'red';
     return 'blue';
  }
);
graph.update(node, {
  error: true
});
```

**Comment by oooofeiger** [comment]
> 就是在写了映射的情况下，把所有这个字段更新的逻辑都放到映射的回掉函数里，用其它有含义的字段做区分。比如：
> 
> ```js
> graph.node(
>   color(model) {
>     if (mode.error)  return 'red';
>      return 'blue';
>   }
> );
> graph.update(node, {
>   error: true
> });
> ```

我的update方法不触发graph.node（）方法为什么

**Comment by oooofeiger** [comment]
> 就是在写了映射的情况下，把所有这个字段更新的逻辑都放到映射的回掉函数里，用其它有含义的字段做区分。比如：
> 
> ```js
> graph.node(
>   color(model) {
>     if (mode.error)  return 'red';
>      return 'blue';
>   }
> );
> graph.update(node, {
>   error: true
> });
> ```

感谢回复~
