### ISSUE TITLE
🥰 AntV OSCP 计划，快来参与吧 🥰 

### ISSUE THREAD

**Issue by Aarebecca** [antvis/G6#5245]
### AntV Open Source Contribution Plan（可选/Optional）

- [X] 我同意将这个 Issue 参与 OSCP 计划 / I agree to participate in the OSCP plan

### Issue 类型 / Issue Type

None

### 任务介绍 / Task Description

![286882885-64320c9c-94a0-4330-bf4c-28bec261666e](https://github.com/antvis/G6/assets/25787943/a73c039f-6521-4e20-91f8-34ed6f7988f4)

继 Issue Hunt 计划之后，我们推出了 OSCP（开源社区贡献计划），旨在为开发者提供更多参与开源社区建设的机会。
> AntV is excited to announce the OSCP (Open Source Community Contribution Program) to provide developers with even more opportunities to contribute to the open-source community.

作为回馈，我们将不定期为积极参与社区建设的开发者寄送礼品并颁发荣誉证书，以表彰您的贡献。
> As a token of appreciation, we will periodically send gifts and issue honorary certificates to developers actively contributing to community development.

<img width="995" alt="286882331-791148ed-bb56-4114-9d26-fbc78f94e9e7" src="https://github.com/antvis/G6/assets/25787943/94ea6113-5208-4554-b451-a4f93b55fb23">

首期 OSCP 计划欢迎您通过以下方式积极参与：
> In the inaugural phase of the OSCP program, we invite you to participate actively through the following avenues:

1. 协助解决和修复 G6 的 Bug / Assist in identifying and fixing bugs in G6
2. 为 G6 5.0 提供新的功能特性 / Contribute new feature enhancements to G6 5.0
3. 提出富有创意的演示案例 / Submit creative demonstration cases
4. 参与我们不定期发布的 OSCP 计划任务 / Engage in OSCP program tasks that we periodically release

AntV 的 OSCP 计划，助您更深入地融入开源社区，一同让 G6 变得更好！
> AntV's OSCP program helps you integrate even more deeply into the open-source community as we work together to make G6 even better!

### 参与说明

1. 协助解决和修复 G6 的 Bug / Assist in identifying and fixing bugs in G6

您可以自行查找和修复 G6 中的缺陷，并创建 Pull Request（PR）。我们将根据缺陷的严重程度和修复难度等因素对任务进行评级。符合初级任务要求的 PR 将自动纳入到 OSCP 计划中。

> You can independently identify and resolve bugs in G6, then create a Pull Request (PR). We will rate tasks based on the severity of the bug and the difficulty of the fix. PRs that meet the criteria for beginner-level tasks will automatically be included in the OSCP program.

2. 为 G6 5.0 提供新的功能特性 / Contribute new feature enhancements to G6 5.0

在开始具体工作之前，请在 [Discussions](https://github.com/antvis/G6/discussions/categories/ideas) 中提出您的创意。我们将对这些创意进行评估，并为获得认可的创意创建相应的 OSCP 计划并确定评级。

> Before you start working, please propose your ideas in [Discussions](https://github.com/antvis/G6/discussions/categories/ideas). We will evaluate these ideas and create corresponding OSCP plans with ratings for those that are approved.

3. 提出富有创意的演示案例 / Submit creative demonstration cases

您可以分享富有创意的想法或与具体开发相关的设计案例。对于那些具有独创性并通过我们审核的案例，我们会在提供的案例中注明作者的ID。

> You can provide us with creative ideas or relevant design cases from your development work. For cases that are both original and pass our review, we will credit the author's ID within the provided case.

4. 参与我们不定期发布的 OSCP 计划任务 / Engage in OSCP program tasks that we periodically release

我们将不定期在问题（Issue）中发布 OSCP 计划任务，包括但不限于问题、功能等任务。您可以在相关问题下方回复以认领任务。

> We will periodically post OSCP program tasks in issues, including but not limited to issues and feature-related tasks. You can reply below the relevant issue to claim a task.

**Comment by hustcc** [comment]
所有可参入的任务在这里可以看到： [AntV OSCP Project](https://github.com/antvis/G6/issues?q=is%3Aopen%20is%3Aissue%20project%3Aantvis%2F25)。

**Comment by nhfgCSSA** [comment]
G6 v5 现有的文档太简单了, 从 v4 想要迁移过来, 寸步难行, 没能迁移成功, 又退回去了. 希望官方能够重视文档.

**Comment by Xling-web** [comment]
G6 v5中Element元素生成image时src是svg文件路径，该如何在点击时或者通过style修改svg文件颜色

**Comment by Linkodt** [comment]
> 所有可参入的任务在这里可以看到： [AntV OSCP Project](https://github.com/antvis/G6/issues?q=is%3Aopen%20is%3Aissue%20project%3Aantvis%2F25)。

这里面没有任务 对于简单的issue问题 是否有good first issue的标签呢？
