### ISSUE TITLE
G6有什么办法可以实现X6边上的操作点vertical 功能吗？

### ISSUE THREAD

**Issue by nanfb** [antvis/G6#5247]
### 问题描述

因为需要的节点很多，X6性能又不是很行，想把X6上的一些功能移植到G6上

### 重现链接

/

### 重现步骤

/

### 预期行为

/

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Aarebecca** [comment]
可以提供更多的特性描述吗

**Comment by nanfb** [comment]
https://github.com/antvis/G6/issues/5247#issuecomment-1850290909
大概是这个功能，G6提供的编辑边的功能太少了，只支持在点的位置弯折，获取我可以参考X6是怎么实现的，然后通过坐标转换在G6上实现？

**Comment by nanfb** [comment]
> 可以提供更多的特性描述吗

[](https://github.com/antvis/G6/issues/5247#issuecomment-1850290909)
大概是这个功能，G6提供的编辑边的功能太少了，只支持在点的位置弯折，获取我可以参考X6是怎么实现的，然后通过坐标转换在G6上实现？

**Comment by nanfb** [comment]
[](https://x6.antv.vision/zh/examples/edge/tool#vertices)

**Comment by nanfb** [comment]
[链接](https://x6.antv.vision/zh/examples/edge/tool#vertices)
大概是这个功能，G6提供的编辑边的功能太少了，只支持在点的位置弯折，获取我可以参考X6是怎么实现的，然后通过坐标转换在G6上实现？

**Comment by nanfb** [comment]
> 可以提供更多的特性描述吗

[链接](https://x6.antv.vision/zh/examples/edge/tool#vertices)
大概是这个功能，G6提供的编辑边的功能太少了，只支持在点的位置弯折，获取我可以参考X6是怎么实现的，然后通过坐标转换在G6上实现？

**Comment by Aarebecca** [comment]
> > 可以提供更多的特性描述吗
> 
> [链接](https://x6.antv.vision/zh/examples/edge/tool#vertices) 大概是这个功能，G6提供的编辑边的功能太少了，只支持在点的位置弯折，获取我可以参考X6是怎么实现的，然后通过坐标转换在G6上实现？

目前 G6 内置的边还不支持这项能力，不过可以使用自定义边的形式，参考案例：https://g6-next.antv.antgroup.com/zh/examples/item/customEdge/#customPolyline

需要注意的点是，G6 的常用场景都会进行图布局，因此边上的控制点位置都不是使用绝对坐标描述的

<img width="542" alt="image" src="https://github.com/antvis/G6/assets/25787943/653826a7-1b62-4a00-a3a9-498f5dc95c09">

在上面的例子中，边的起点、终点以及中间的拐点都是基于连接的节点而定的，这是和 X6 使用场景上一个明显的差异
