### ISSUE TITLE
G6 多条边交叉，可以实现跳线效果吗

### ISSUE THREAD

**Issue by xavierLee92** [antvis/G6#5248]
### 问题描述

两条线有交叉且无连接，使用什么方式可以实现跳线

### 重现链接

/

### 重现步骤

/

### 预期行为

/

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by xavierLee92** [comment]
G6 可以使用X6连线的跳线效果吗，或者G6中如何使用X6连线

**Comment by Aarebecca** [comment]
目前支持[自动寻径](https://g6-next.antv.antgroup.com/examples/item/defaultEdges/#polyline3) 来尽可能避免边重叠，如果要实现跳线效果，需要自定义边才行
