### ISSUE TITLE
G6 5.0.0-beta.27版本tooltip使用预定义DOM元素无法正常显示

### ISSUE THREAD

**Issue by l-besiege-l** [antvis/G6#5251]
### 问题描述

G6 5.0.0-beta.27版本tooltip的getContent回调函数使用预定义的DOM元素作为返回值，导致tooltip无法正常显示，tooltip直接把图的画布给挤占了，而G6 4.8.23版本tooltip可以在正确的节点/边的位置上显示预定义的DOM元素，下面的图是不同版本下鼠标悬浮在节点上tooltip的显示情况：
### 5.0.0-beta.27版：
![image](https://github.com/antvis/G6/assets/52117792/17375a34-b761-413b-883f-3e74c9b86fd1)
### 4.8.23版：
![image](https://github.com/antvis/G6/assets/52117792/68baf60e-73ed-4b1f-aaa9-87341b44696d)

### 重现步骤

如复现链接所示

### 预期行为

期望5.0.0-beta.27版tooltip可以使用预定义的DOM元素作为显示的元素

### 平台

- 操作系统: [Windows]
- 网页浏览器: [edge]
- G6 版本: [ 5.0.0-beta.27]

**Comment by uhobnil** [comment]
v5版本需要return outDiv.outerHTML
