### ISSUE TITLE
v5 树图交互 残影+瞬移

### ISSUE THREAD

**Issue by kingyue737** [antvis/G6#5257]
### Describe the bug

v5官方紧凑树示例，点击节点后会产生残影。并且可以注意到有些子节点有过渡动画，有些子节点则是瞬移过去的。
![g6](https://github.com/antvis/G6/assets/40021217/3b027d37-ecc2-43a9-94e7-bf711fffdad5)

### Your Example Website or App

https://g6-next.antv.antgroup.com/examples/net/compactBox#basicCompactBox

### Steps to Reproduce the Bug or Issue

点击示例中任一父节点

### Expected behavior

应该像v4示例中一样有丝滑的动画。另外，v4在收起子节点时会有变紧凑的动画，v5则是整个树静止不动，我不知道是v5没有实装还是bug。
![g6v4](https://github.com/antvis/G6/assets/40021217/ee504f91-d706-4ddf-b153-f1dcc448f504)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

g6新手，刚刚接触，目前还处于调研阶段，不知道选择v4还是直接学习v5 。v5我看到有很多重要的功能，比如tree-shaking和暗色模式。但看起来v5的示例多多少少都有问题，貌似离能上production还有较远的距离。刚想试下流程图，官方例子看着也很怪。。
![dagre](https://github.com/antvis/G6/assets/40021217/ebdfa5ee-f8c2-4776-ab2f-42975c5dae42)

**Comment by davis-hd** [comment]
残影问题可以修改一下渲染引擎试一下，上面的例子改成webgl看是没有出现的

**Comment by Aarebecca** [comment]
类似问题会先行关闭，后续底层引擎会统一修复
