### ISSUE TITLE
v5 整个节点的旋转 有解决方案吗？

### ISSUE THREAD

**Issue by zzjjbbaa** [antvis/G6#5259]
### 问题描述

v5 整个节点的旋转 有解决方案吗？

### 重现链接

无

### 重现步骤

无

### 预期行为

v5 可以实现整个节点的旋转

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Aarebecca** [comment]
<img width="1410" alt="image" src="https://github.com/antvis/G6/assets/25787943/2b0133f3-aba7-4108-96db-0491c9af1ac4">

在这里例子中，使用 `transform: "rotate(45)"` 来让节点进行旋转，使用 `transformOrigin` 来设置旋转中心，不过目前在 G6 5.0 内置节点的设计上还存在一点问题，还不支持整体节点的旋转，后续会对这块进行优化

**Comment by Aarebecca** [comment]
relative issue: https://github.com/antvis/G6/issues/5048

**Comment by zzjjbbaa** [comment]
> <img alt="image" width="1410" src="https://private-user-images.githubusercontent.com/25787943/289858004-2b0133f3-aba7-4108-96db-0491c9af1ac4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNzQ2NzEsIm5iZiI6MTcwNjA3NDM3MSwicGF0aCI6Ii8yNTc4Nzk0My8yODk4NTgwMDQtMmIwMTMzZjMtYWJhNy00MTA4LTk2ZGItMDQ5MWM5YWYxYWM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA1MzI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4N2Q4ZjM4N2I0NzI4YTBiMTA2NWY1MDY4NDYzYzYyNmE1NzdjNzVmZjAwZjdjYzNlZjRhMmZjYTc5MDFkY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-llbBEIZ4r2oeho8c7hHGW1nQxdq7U7dOmML7hBhn4g">
> 在这里例子中，使用 `transform: "rotate(45)"` 来让节点进行旋转，使用 `transformOrigin` 来设置旋转中心，不过目前在 G6 5.0 内置节点的设计上还存在一点问题，还不支持整体节点的旋转，后续会对这块进行优化

有进展了吗
