### ISSUE TITLE
v5 官网demo 交互\创建边 新增典型案例 

### ISSUE THREAD

**Issue by zzjjbbaa** [antvis/G6#5261]
### 问题描述

希望新增创建边的demo，结合自定义节点的drawAnchorShapes 创建边

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Aarebecca** [comment]
可以更详细的描述下这个场景

**Comment by zzjjbbaa** [comment]
> 可以更详细的描述下这个场景

我觉得一些不规则node（非圆），通过连接桩创建边，应该是个很常见的需求吧

**Comment by Aarebecca** [comment]
> > 可以更详细的描述下这个场景
> 
> 我觉得一些不规则node（非圆），通过连接桩创建边，应该是个很常见的需求吧

明白，后续我们会加上这个例子

**Comment by zzjjbbaa** [comment]
> > > 可以更详细的描述下这个场景
> > 
> > 
> > 我觉得一些不规则node（非圆），通过连接桩创建边，应该是个很常见的需求吧
> 
> 明白，后续我们会加上这个例子

赞
