### ISSUE TITLE
antd pro中使用G6 以及@antv/g6-react-node 提示找不到 @antv/g6-react-node

### ISSUE THREAD

**Issue by qiuyulc** [antvis/G6#5266]
### G6 Version

4.x

### Describe the bug

在antdPro 中使用G6时 安装 @antv/g6-react-node 然后运行项目就会提示下面的错误
不知道这是什么原因造成的，是我需要修改一个其他的配置吗？
![image](https://github.com/antvis/G6/assets/139320701/b0fc13b9-ef37-470e-9e6e-e2788fa3dd40)

### Your Example Website or App

__

### Steps to Reproduce the Bug or Issue

__

### Expected behavior

__

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
- G6:^4.8.21
- @antv/g6-react-node: "^1.4.6"

**Comment by Aarebecca** [comment]
你好，该问题已经解决，请重新尝试安装

**Comment by Aarebecca** [comment]
你好，请尝试更新到最新的 1.4.8 版本

**Comment by qiuyulc** [comment]
> 你好，请尝试更新到最新的 1.4.8 版本
你好 抱歉 我没有找到 1.4.8版本
版本列表中只有以下的版本
![image](https://github.com/antvis/G6/assets/139320701/ad448f83-d131-498a-a0cf-c46d1b7bb10b)
