### ISSUE TITLE
解决折线重叠，避开节点，出现递归调用错误

### ISSUE THREAD

**Issue by xwaptx4869** [antvis/G6#5271]
### G6 版本

4.x

### 问题描述

使用自定义节点，折线与节点重叠，通过布局完成钩子函数更新节点数据
<img width="446" alt="image" src="https://github.com/antvis/G6/assets/36848753/b3bf9165-c79b-4ba2-a078-68fd64802384">

自定义节点折叠展开(官网示例，决策树)：
<img width="687" alt="image" src="https://github.com/antvis/G6/assets/36848753/ca026f8c-07bc-4b59-9ed0-f97cacddf819">

二者共存时，点击折叠会引发递归错误(先点展开无误，先点折叠报错，再展开也报错)，请问如何解决？
<img width="894" alt="image" src="https://github.com/antvis/G6/assets/36848753/1b4a90ac-3812-4a20-977d-eed1294dad4b">

### 重现链接

no

### 重现步骤

更新节点边配置与折叠展开共存时
点击折叠、展开

### 预期行为

无错误

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.8.23 ... ]

### 屏幕截图或视频（可选）

https://github.com/antvis/G6/assets/36848753/d34bce8c-a837-41de-8956-1a034167c77c

**Comment by xwaptx4869** [comment]
哥哥们回复一下哇

**Comment by xwaptx4869** [comment]
https://codesandbox.io/s/laughing-kare-l8pzhn?file=/index.js

**Comment by xwaptx4869** [comment]
在线复现地址已更新

**Comment by Aarebecca** [comment]
> 在线复现地址已更新

你好，这个demo不可用。
