### ISSUE TITLE
设置连线动画时，线段末端箭头也执行了动画。

### ISSUE THREAD

**Issue by htyaw** [antvis/G6#5272]
### G6 版本

4.x

### 问题描述

设置连线动画时，线段末端箭头也执行了动画。
![image](https://github.com/antvis/G6/assets/71117770/a68e945b-1980-4e4a-bf2a-1ee40b6c800d)

### 重现链接

无

### 重现步骤

无

### 预期行为

动画执行范围不包含箭头。

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![动画](https://github.com/antvis/G6/assets/71117770/26786247-1e85-406e-b232-72d3c71a7c18)

**Comment by xiaoiver** [comment]
应该是动画时箭头端点也应用了 lineDash 样式

**Comment by htyaw** [comment]
> 应该是动画时箭头端点也应用了 lineDash 样式

是的 请问这个该如何解决

**Comment by zcz1998** [comment]
<img width="251" alt="Snipaste_2023-12-21_15-34-57" src="https://github.com/antvis/G6/assets/54663113/7b5ffe78-3712-4d0e-9e18-97206445919b">
边样式的endArrow添加lineDash:[0,0]

**Comment by htyaw** [comment]
> <img alt="Snipaste_2023-12-21_15-34-57" width="251" src="https://private-user-images.githubusercontent.com/54663113/292127170-7b5ffe78-3712-4d0e-9e18-97206445919b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNDUxNzAsIm5iZiI6MTcwMzE0NDg3MCwicGF0aCI6Ii81NDY2MzExMy8yOTIxMjcxNzAtN2I1ZmZlNzgtMzcxMi00ZDBlLTllMTgtOTcyMDY0NDU5MTliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDA3NDc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyNWRjZWVlNTZhMDY5OTBiMzE0MWEwZmMxYWZjZGUxNmE4MWU1M2EyNTRlMDRhOWEyYTZiZjIzYTIwYTA5NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WSafTzw2BzwQOBCoiRZQojhj4rC_2UT7mu-UW-vf2PE"> 边样式的endArrow添加lineDash:[0,0]

可以了 感谢！
