### ISSUE TITLE
V5 版本对齐线样式设置无效

### ISSUE THREAD

**Issue by holddididi** [antvis/G6#5273]
### G6 版本

5.x

### 问题描述

V5版本snapLine对齐线样式设置之后不生效，对齐线在拖动完成之后是否能自动消失？

### 重现链接

暂无

### 重现步骤

...
 plugins: [
    {
         key: "default-snapline",
          type: "snapline",
          line: {
            stroke: "#ccc",
            lineDash: [5, 5],
         },
....
    }
 ],

### 预期行为

1.设置灰色虚线对齐线
2.拖拽结束后对齐线消失

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [5 ]

**Comment by Aarebecca** [comment]
这是一个已知的 Bug，后续会进行修复
