### ISSUE TITLE
建议Graph实例加一个获取Behaviors实例的方法

### ISSUE THREAD

**Issue by qishenliang** [antvis/G6#5275]
### G6 版本

4.x

### 问题描述

实际使用场景中，业务代码可能会调用Behaviors实例里面的方法，比如“activate-relations”，需要主动清理inactive状态，直接调用seft.throttleClearActiveState(e, seft)即可

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: Windows
- 网页浏览器: Google Chrome
- G6 版本: 4.8.23

**Comment by Aarebecca** [comment]
切换状态建议使用 [setItemState](https://g6.antv.antgroup.com/api/graph-func/state#graphsetitemstateitem-state-value) 方法。
