### ISSUE TITLE
关于edge中箭头的动画问题？

### ISSUE THREAD

**Issue by Jarryham** [antvis/g6#528]
是否支持连线中箭头动画，我想做成这样的效果：
![111](https://user-images.githubusercontent.com/18054284/48123102-fc9d7100-e2b3-11e8-8f71-10157ea8da03.gif)
我的思路是在自定义边时，加上path然后施加动画效果，但是这样有个问题，path貌似被我写死了，指向不能根据节点变化，会导致下面的效果：
![333 gif](https://user-images.githubusercontent.com/18054284/48123555-3622ac00-e2b5-11e8-9d3b-e96db88d3e90.gif)
具体详情请看codepen：
https://codepen.io/jarryham/pen/QJjYPo
有没有一个好的办法去实现箭头的动画效果，而且方向会根据线的方向保持一致？

**Comment by Jarryham** [comment]
> 楼主发现好的方法了么？我也在做这个效果，还有曲线的箭头动画。

没太多时间去研究，最笨的办法就是每条写死

**Comment by TomHuangCN** [comment]
我 TM 点进这个 codepen 是好的啊。

你是要我夸夸你么 =。=

**Comment by Jarryham** [comment]
> 我 TM 点进这个 codepen 是好的啊。
> 
> 你是要我夸夸你么 =。=

抱歉，后面自己弄了，没来得更新回复下
