### ISSUE TITLE
v5.0.0-beta.28 画布初始化位置异常

### ISSUE THREAD

**Issue by liuchangheng** [antvis/G6#5283]
### G6 版本

5.x

### 问题描述

canvas模式下面（其他没做测试），初始化时， 画布像又偏移容器一半的宽度

### 重现链接

https://codesandbox.io/p/sandbox/quizzical-sammet-dq5lv5?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqatxomg00063b6ii3ua0uq7%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqatxomg00023b6i1btksahk%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqatxomg00033b6i5lw6pmqp%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqatxomg00053b6ic5g6qolb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B51.06722481706119%252C48.93277518293881%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqatxomg00023b6i1btksahk%2522%253A%257B%2522id%2522%253A%2522clqatxomg00023b6i1btksahk%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqbvjgwn00023b6ia4kw0non%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A184%252C%2522startColumn%2522%253A39%252C%2522endLineNumber%2522%253A184%252C%2522endColumn%2522%253A39%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponents%252FHelloWorld.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqbvjgwn00023b6ia4kw0non%2522%257D%252C%2522clqatxomg00053b6ic5g6qolb%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqatxomg00043b6i7us6992g%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqatxomg00053b6ic5g6qolb%2522%252C%2522activeTabId%2522%253A%2522clqatxomg00043b6i7us6992g%2522%257D%252C%2522clqatxomg00033b6i5lw6pmqp%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqatxomg00033b6i5lw6pmqp%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A16.460834762721547%257D

### 重现步骤

1.进入页面
2.查看初始化样式

### 预期行为

我希望不出现滚动条

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- G6 版本: [5.0.0-beta.28]

### 屏幕截图或视频（可选）

<img width="1059" alt="image" src="https://github.com/antvis/G6/assets/49780270/d26078e1-ebe9-4978-bf7d-bc362ff1d945">
<img width="1053" alt="image" src="https://github.com/antvis/G6/assets/49780270/22846147-e144-4f7f-bddd-1e56db897eb4">

**Comment by Aarebecca** [comment]
暂未发现导致该问题的确切原因，这边可以先行通过设置容器样式来避免该问题：

<img width="551" alt="image" src="https://github.com/antvis/G6/assets/25787943/69a59634-39c0-41a7-b32d-a2c1fcb0b34a">

**Comment by liuchangheng** [comment]
> 暂未发现导致该问题的确切原因，这边可以先行通过设置容器样式来避免该问题：
> 
> <img alt="image" width="551" src="https://private-user-images.githubusercontent.com/25787943/291766669-69a59634-39c0-41a7-b32d-a2c1fcb0b34a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNDE0NTAsIm5iZiI6MTcwMzA0MTE1MCwicGF0aCI6Ii8yNTc4Nzk0My8yOTE3NjY2NjktNjlhNTk2MzQtMzljMC00MWE3LWIzMmQtYTJjMWZjYjBiMzRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDAyNTkxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3MGJkZjNiMzBlNDJkNDk3YTE5YzNiNTU0ZWUyNjQwZDdkOWJlMTJlNTRkYjI5ZjI1NzFhMWQzYmUyMjdhZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ROl4Hlgza3QR0x4frjRPWl1ae8N4qD09mpWJ8UesjLU">

目前我这边针对 canvas层直接设置样式，确实是没有任何问题

<img width="175" alt="image" src="https://github.com/antvis/G6/assets/49780270/8a8b90eb-6bae-484e-9ce6-cb8e4d856ba7">
