### ISSUE TITLE
文字怎么自动换行

### ISSUE THREAD

**Issue by Fzt1120** [antvis/G6#5286]
### G6 版本

5.x

### 问题描述

怎么可以让文字自动换行啊，除了\n换行符，vue3用的JSX自定义的节点，文字过长的话就会向右超出节点，设置过最大宽度，都不管用，还不能超出省略，好难为什么没有这个功能！

### 重现链接

.

### 重现步骤

需要给节点加个滚动条，超出文字自动换行

### 预期行为

需要给节点加个滚动条，超出文字自动换行

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

需要给节点加个滚动条，超出文字自动换行

### 补充说明（可选）

需要给节点加个滚动条，超出文字自动换行

**Comment by yvonneyx** [comment]
自动换行可以参考一下官网示例：https://g6-next.antv.antgroup.com/examples/item/label/#labelLen1

使用过程中还有任何疑问或问题，请随时再次开启 issue
