### ISSUE TITLE
linkCenter为false情况下，处理平行边时候，边两边会出现相交情况

### ISSUE THREAD

**Issue by helanya** [antvis/G6#5298]
### G6 版本

4.x

### 问题描述

linkCenter为false情况下，处理平行边时候，如果方向不一样的边两边会出现相交情况，因为其他需求，linkCenter 需要设置为false

### 重现链接

[重现链接
](https://codesandbox.io/p/sandbox/restless-flower-cp52kk?file=%2Findex.html%3A1%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqng158u00063b6hc05zyuy2%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqng158u00023b6hxs0m9i52%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqng158u00033b6htcdgll7h%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqng158u00053b6hdpjv1bbk%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqng158u00023b6hxs0m9i52%2522%253A%257B%2522id%2522%253A%2522clqng158u00023b6hxs0m9i52%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqngbkhg00023b6hsojrdo36%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A1%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A1%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqngbkhg00023b6hsojrdo36%2522%257D%252C%2522clqng158u00053b6hdpjv1bbk%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqng158u00043b6h206k6teo%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqng158u00053b6hdpjv1bbk%2522%252C%2522activeTabId%2522%253A%2522clqng158u00043b6h206k6teo%2522%257D%252C%2522clqng158u00033b6htcdgll7h%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqng158u00033b6htcdgll7h%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### 重现步骤

以 [官网例子](https://g6.antv.antgroup.com/zh/examples/interaction/createEdge/#click) 为例：
设置 linkCenter 为false，并创建两条边，两条边的方向一条像左，一条向右
```
import G6 from "@antv/g6";

const data = {
  nodes: [
    { id: "node1", x: 350, y: 200 },
    { id: "node2", x: 350, y: 250 },
    { id: "node3", x: 100, y: 200 },
  ],
  edges: [
    { id: "edge2", target: "node2", source: "node1", type: "quadratic" },
    { id: "edge1", target: "node1", source: "node2", type: "quadratic" },
  ],
};
const descriptionDiv = document.createElement("div");
descriptionDiv.innerHTML =
  "Drag from a source node to a target node to create a new edge. Note that in trigger: 'drag' mode cannot create a self-loop edge";
const container = document.getElementById("container");
container.appendChild(descriptionDiv);

const width = container.scrollWidth;
const height = (container.scrollHeight || 500) - 20;
const graph = new G6.Graph({
  container: "container",
  width,
  height,
  linkCenter: false,
  modes: {
    default: [
      {
        type: "create-edge",
        trigger: "drag", // 'click' by default. options: 'drag', 'click'
      },
    ],
  },
  defaultEdge: {
    style: {
      stroke: "#F6BD16",
      lineWidth: 2,
    },
  },
});

graph.data(data);
graph.render();

graph.on("aftercreateedge", (e) => {
  const edges = graph.save().edges;
  G6.Util.processParallelEdges(edges);
  graph.getEdges().forEach((edge, i) => {
    graph.updateItem(edge, {
      curveOffset: edges[i].curveOffset,
      curvePosition: edges[i].curvePosition,
    });
  });
});

if (typeof window !== "undefined")
  window.onresize = () => {
    if (!graph || graph.get("destroyed")) return;
    if (!container || !container.scrollWidth || !container.scrollHeight) return;
    graph.changeSize(container.scrollWidth, container.scrollHeight - 20);
  };
```

### 预期行为

处理平行边时是否能够控制边的两头端点在一个点

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.8.23 ... ]

### 屏幕截图或视频（可选）

<img width="429" alt="image" src="https://github.com/antvis/G6/assets/20741045/eb61d685-d578-46ba-a25e-343fd1ef220b">

**Comment by helanya** [comment]
通过重写 processParallelEdges 处理可以解决

**Comment by DIVADING** [comment]
> 通过重写 processParallelEdges 处理可以解决

请问是怎么重写or处理这个的，我也遇到了这个问题

**Comment by helanya** [comment]
> > 通过重写 processParallelEdges 处理可以解决
> 
> 请问是怎么重写or处理这个的，我也遇到了这个问题

我的大致思路是，先将不同方向的连线分个类排个序，然后再设置连线的 curveOffset；
比如：
	A、B 节点连线有5条: [a->b, b->a, a->b, a->b, b->a],
	然后排个序：[a->b, a->b, a ->b, b->a, b->a],将相同方向连线放在一起，最后根据这个排序后的连线设置他的 curveOffset 即可。
