### ISSUE TITLE
cfg.x和cfg.origin.x有什么区别

### ISSUE THREAD

**Issue by itsmyturn** [antvis/g6#53]
cfg.x和cfg.origin.x有什么区别

**Comment by TomHuangCN** [comment]
* cfg.origin.x 比较容易理解就是原始数据的 x 。
* cfg.x y 这个比较难解释，cfg.x 和 cfg.y 现在都是 0，因为其x, y已经附到其父元素的变换中去了。自定义形简单理解，cfg.x cfg.y 就是其原始数据的 x, y
