### ISSUE TITLE
使用svg模式渲染时，在mac屏幕下，由于devicePixelRadio=2，导致画布尺寸初始化异常

### ISSUE THREAD

**Issue by phantomlution** [antvis/g6#531]
# 代码
```
const graph = new G6.Graph({
      container: 'mountNode', 
      fitView: 'cc',
      renderer: 'svg',
      height: window.innerHeight
});
```
代码执行后，在mac上，打开谷歌调试器，发现画布尺寸异常
![1541644996834](https://user-images.githubusercontent.com/29418758/48174490-2ce02080-e343-11e8-8d2e-3339b32c7812.jpg)
# 异常
svg 的宽和高都被放大真实高度的2倍
# 原因
mac 屏幕下 devicePixelRatio = 2
# 期待的方案
在svg渲染模式下，svg的  pixelRatio为1，不读取系统的devicePixelRatio

**Comment by TomHuangCN** [comment]
2.1.5

**Comment by rogueRabbit** [comment]
@phantomlution 请问最终有解决吗？

**Comment by rogueRabbit** [comment]
@TomHuangCN 你好，我现在更新到g6的2.2.2版本，画类似与官网上小米关系的图，其中renderer:'canvas',但是在Mac上canvas的比例还是会放大1倍，请问有解决方法吗？麻烦看到，请回复下，谢谢
