### ISSUE TITLE
渲染文本缺失

### ISSUE THREAD

**Issue by Wanglintc** [antvis/G6#5313]
### G6 版本

4.x

### 问题描述

group.addShape渲染文本后，把他hide，后续再把它show，文本渲染会出现问题。

### 重现链接

https://codesandbox.io/p/sandbox/heuristic-framework-29jkh2?file=%2Findex.js%3A230%2C20-230%2C34

### 重现步骤

文本节点hide，鼠标移入节点，节点的某个文本show，渲染会出现问题。

### 预期行为

文本渲染正常。

### 平台

- 操作系统: Windows,]
- 网页浏览器: [Google Chrome,]
- G6 版本: [4.5.1 ... ]

**Comment by Xzeffort** [comment]
`graph.get('canvas').set('localRefresh', false);  `设置一下就好了
