### ISSUE TITLE
v5 文档错误

### ISSUE THREAD

**Issue by zzjjbbaa** [antvis/G6#5321]
### G6 Version

5.x

### Describe the bug

![image](https://github.com/antvis/G6/assets/54572770/7c201753-05ce-46bf-8f71-5033bc9c6aff)

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

无

### Expected behavior

无

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Aarebecca** [comment]
🌹 This spelling will be fixed soon / 我们会尽快修复这个错误

**Comment by zzjjbbaa** [comment]
> 🌹 This spelling will be fixed soon / 我们会尽快修复这个错误

大哥，v5预计好久能出正式版啊

**Comment by Aarebecca** [comment]
> > 🌹 This spelling will be fixed soon / 我们会尽快修复这个错误
> 
> 大哥，v5预计好久能出正式版啊

预计 3 月推出稳定版，API 和 Spec 就都不会再改变了，6 月会发正式版。

**Comment by hustcc** [comment]
[初级任务] 欢迎认领。

**Comment by wt258967** [comment]
> > > 🌹 This spelling will be fixed soon / 我们会尽快修复这个错误
> > 
> > 
> > 大哥，v5预计好久能出正式版啊
> 
> 预计 3 月推出稳定版，API 和 Spec 就都不会再改变了，6 月会发正式版。

能不能解决下5.0.0-beta.28版本3d模式下 节点label和边的label 边的箭头 显示bug

**Comment by Gatekeeper95** [comment]
认领

**Comment by hustcc** [comment]
@Gatekeeper95 还没有来 PR，本周不来就关闭了。

**Comment by njshuisheng** [comment]
@hustcc 我可以认领吗

**Comment by Aarebecca** [comment]
> @hustcc 我可以认领吗

目前已经在重新编写文档，这个任务会关闭。欢迎认领其他任务。
