### ISSUE TITLE
v5 废弃api

### ISSUE THREAD

**Issue by zzjjbbaa** [antvis/G6#5326]
### G6 版本

5.x

### 问题描述

v5 会废弃updateItem这些操作node或edge的api吗

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]
无

**Comment by Aarebecca** [comment]
https://www.yuque.com/antv/g6/fzhacrkc6pd46mb4#HWoWG 这是目前提出的 API 调整草案。基于数据驱动的方式，因此要更新 node/edge/combo 将需要使用下列方式：

```ts
graph.updateData({ nodes: [...], edges: [...], combos: [...] });
// 语法糖
graph.updateNodeData([...]);
graph.updateEdgeData([...]);
graph.updateComboData([...]);
```

**Comment by zzjjbbaa** [comment]
> https://www.yuque.com/antv/g6/fzhacrkc6pd46mb4#HWoWG 这是目前提出的 API 调整草案。基于数据驱动的方式，因此要更新 node/edge/combo 将需要使用下列方式：
> 
> ```ts
> graph.updateData({ nodes: [...], edges: [...], combos: [...] });
> // 语法糖
> graph.updateNodeData([...]);
> graph.updateEdgeData([...]);
> graph.updateComboData([...]);
> ```
这样都是批量更新吧，不能单独更新某个node或edge了

**Comment by hustcc** [comment]
https://github.com/antvis/G6/pull/5546 已经发布一个新的版本，试试 API。
