### ISSUE TITLE
自定义节点中部分img不显示问题

### ISSUE THREAD

**Issue by donghuizhou** [antvis/G6#5327]
### G6 版本

4.x

### 问题描述

如下图所示，自定义节点中放置了用户头像，但是在页面初始化时，部分节点的头像不显示，需要对画布做一些操作（如移动画布），头像才会显示
![image](https://github.com/antvis/G6/assets/31002949/c9b32c65-a687-4e2e-a91a-bef0c646333c)
![image](https://github.com/antvis/G6/assets/31002949/b6e366d7-cd1a-4e0a-8b48-8518c2e1c210)
**自定义节点中添加img方法**
```javascript
G6.registerNode('xxxxx', {
    draw (cfg, group) {
        // .......
        let img = new Image()
        img.src = '后端返回的img地址'
        group.addShape('image', {
            attrs: {
                x:  xx,
                y:  xx,
                width: xx,
                height: xx,
                img
            }
        })
        // ......
    }
})
```

### 重现链接

如上所示

### 重现步骤

如上所示

### 预期行为

画布初始化时，所有自定节点的头像img能正常显示，无需用户对画布做操作

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Aarebecca** [comment]
可以尝试以下列方式设置图片 url，这两种理论上是一样的。官网案例中并没有出现你描述的首次加载无法显示的问题。如果仍然无法解决，请提供线上可复现 demo

```ts
G6.registerNode('xxxxx', {
    draw (cfg, group) {
        // .......
        group.addShape('image', {
            attrs: {
                x:  xx,
                y:  xx,
                width: xx,
                height: xx,
                img: 'url'
            }
        })
        // ......
    }
})
```

**Comment by donghuizhou** [comment]
> 可以尝试以下列方式设置图片 url，这两种理论上是一样的。官网案例中并没有出现你描述的首次加载无法显示的问题。如果仍然无法解决，请提供线上可复现 demo
> 
> ```ts
> G6.registerNode('xxxxx', {
>     draw (cfg, group) {
>         // .......
>         group.addShape('image', {
>             attrs: {
>                 x:  xx,
>                 y:  xx,
>                 width: xx,
>                 height: xx,
>                 img: 'url'
>             }
>         })
>         // ......
>     }
> })
> ```

用这种方式报跨域，我们的图片地址是钉钉的地址
