### ISSUE TITLE
在zrender svg 模式下   事件对象不准确

### ISSUE THREAD

**Issue by mylvlin** [antvis/g6#533]
* **G6 Version**:^2
* **Platform**:浏览器
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![tim 20181111140504](https://user-images.githubusercontent.com/6387913/48309728-d5e48080-e5ba-11e8-8881-2ecc4b45371c.png)

如图 在SVG 模式下 即使没有点击到边 但是事件对象target 还是包含了边

**Comment by TomHuangCN** [comment]
需写 codepen 复现
