### ISSUE TITLE
为什么使用自定义节点创建dom一直报错呢

### ISSUE THREAD

**Issue by Fz1120** [antvis/G6#5330]
### G6 版本

4.x

### 问题描述

为什么使用 
G6.registerNode('dom-node', {
        draw(cfg, group) {
            console.log(cfg);
            const shape = group.addShape('dom', {
                attrs: {
                    width: 200,
                    height: 100,
                    html: `<div style="border:1px solid red;"></div>`
                }
            })
            return shape
        }
    })
自定义节点会报Uncaught TypeError: ShapeBase3[shapeType] is not a constructor

### 重现链接

0

### 重现步骤

0

### 预期行为

想通过自定义dom节点更好的去决定样式，但是一直报错

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![Snipaste_2024-01-05_10-29-56](https://github.com/antvis/G6/assets/142639288/584d9188-71c3-4f3e-a463-dbdcbd3c3570)

**Comment by Aarebecca** [comment]
你好，请提供完整示例 demo

**Comment by Fz1120** [comment]
`<template>
    <div ref="container"></div>
</template>

<script setup lang="ts">
import { onMounted, ref } from 'vue'
import G6 from '@antv/g6'
const data = {
    nodes: [
        {
            id: "node1",
            label: "node1",
        },
        {
            id: "node2",
            label: "node2",
        },
        {
            id: "e1",
            label: "e1",
            type: "dom-node",
        },
        {
            id: "e2",
            label: "e2",
            type: "dom-node",
        },
    ],
    edges: [
        {
            source: "node1",
            target: "e1",
        },
        {
            source: "node2",
            target: "e2"
        }
    ],
}
const container = ref()

onMounted(() => {

    const graph = new G6.Graph({
        container: container.value,
        width: 1000,
        height: 600,
        modes: {
            default: ["drag-canvas", "zoom-canvas"]
        },
        defaultNode: {
            type: "rect"
        },
    })
    G6.registerNode('dom-node', {
        draw(cfg, group) {
            console.log(cfg);
            const dom = group.addShape("dom", {
                attrs: {
                    width: 200,
                    height: 100,
                    html: `<div style="border:1px solid red"></div>`
                }
            })
            return dom
        }
    })

    graph.read(data)
})
</script>

<style scoped></style>`

> 你好，请提供完整示例 demo

**Comment by Fz1120** [comment]
![1](https://github.com/antvis/G6/assets/142639288/e82f23f5-c073-437a-9749-703245a67fda)
![2](https://github.com/antvis/G6/assets/142639288/e4369c67-ebe1-4acf-b549-bc4d0051e82c)
![3](https://github.com/antvis/G6/assets/142639288/52ab1c83-1aae-4885-8d5f-39be3a02ff1e)
![4](https://github.com/antvis/G6/assets/142639288/02107b09-5f17-4fe9-87a9-2f8c16a9c853)

**Comment by Fz1120** [comment]
![Uploading 报错.png…]()

**Comment by Fz1120** [comment]
![报错](https://github.com/antvis/G6/assets/142639288/9a22f917-81c8-4b56-8b97-10335da0bc29)

**Comment by Aarebecca** [comment]
这个案例在官网环境下是可以正常绘制的，需要自行诊断下是否使用了不正确的 G6 版本

**Comment by Fz1120** [comment]
目前用的是4.8.24的版本，按理说是可以正常运行的吧

**Comment by Fz1120** [comment]
谢谢哈

> 这个案例在官网环境下是可以正常绘制的，需要自行诊断下是否使用了不正确的 G6 版本

**Comment by Aarebecca** [comment]
> 目前用的是4.8.24的版本，按理说是可以正常运行的吧

理论上是可以的，在官网运行环境也是正常的，需要排查下本地环境原因哈

**Comment by Fzt1120** [comment]
> > 目前用的是4.8.24的版本，按理说是可以正常运行的吧
> 
> 理论上是可以的，在官网运行环境也是正常的，需要排查下本地环境原因哈

好的，已经解决了

**Comment by cxyxxx0924** [comment]
> > > 目前用的是4.8.24的版本，按理说是可以正常运行的吧
> > 
> > 
> > 理论上是可以的，在官网运行环境也是正常的，需要排查下本地环境原因哈
> 
> 好的，已经解决了

兄弟，你是怎么解决的？？？我也遇到了同样的错误
