### ISSUE TITLE
Icon Type Image Opacity Low

### ISSUE THREAD

**Issue by RackweLLizm** [antvis/G6#5332]
### G6 Version

5.x

### Describe the bug

Image Opacity Low

### Your Example Website or App

localhost

### Steps to Reproduce the Bug or Issue

İcon Type Image Opacity Lower

### Expected behavior

Image Opacity Low ActiveRelation

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

I use G6 and Graphin libraries together. I use IMAGE type as Icon in my nodes and when there are activeRelations, the opacity of the icons in the image type does not decrease. This prevents ActiveRelations from doing its job.

let x = { ...node.getModel().style }
x.icon.opacity = 0.1;
graph.updateItem(node.getModel().data.id, {
...x
})

I can interfere with this from the library with a similar solution. But this is very costly and when there are 1000 or more nodes on the page, there is a crash.

A less costly Graphin or G6 based solution to overcome this problem would be much appreciated.

Regards

**Comment by hustcc** [comment]
@RackweLLizm Thank you for the feedback. We will take this issue into consideration during the iteration of version 5.

**Comment by RackweLLizm** [comment]
@hustcc Is there any development on this for v5
