### ISSUE TITLE
v5 webgl-3d无法正确渲染节点的标签文本

### ISSUE THREAD

**Issue by TerryXu-97** [antvis/G6#5334]
### G6 版本

5.x

### 问题描述

v5版本使用webgl-3d渲染时无法正确渲染节点的标签文本

### 重现链接

https://stackblitz.com/edit/react-xjaw6n?file=index.js

### 重现步骤

进入页面，等待编译完成，G6配置项中配置了node的label字段，但是在浏览器中渲染出来的效果没有label或label无法正确被显示。

### 预期行为

期望看到正确渲染节点的标签文本，但是看到了错误的效果

### 平台

- 操作系统: [macOS]
- 网页浏览器: [edge]
- G6 版本: [5.0.0-beta.27]

### 屏幕截图或视频（可选）

<img width="1761" alt="截屏2024-01-08 11 21 20" src="https://github.com/antvis/G6/assets/73343288/1d387657-3184-4fe3-a45f-aef2920d608a">

<img width="1028" alt="截屏2024-01-08 11 24 27" src="https://github.com/antvis/G6/assets/73343288/dc5f57af-9dd5-4426-ab83-8e53f709edbf">

**Comment by wt258967** [comment]
我也遇到了这个问题，发现5.0.-beta.26版本是可以正确渲染的

**Comment by Aarebecca** [comment]
你好，可以参考该示例：https://g6-next.antv.antgroup.com/examples/element/node/#3d-node

**Comment by Aarebecca** [comment]
> 我也遇到了这个问题，发现5.0.0-beta.26版本是可以正确渲染的，而且设置的箭头也无法正确显示

3D 场景中暂未加入箭头支持，你可以通过自定义边创建一个锥体来表示箭头
