### ISSUE TITLE
鼠标悬浮某一节点，高亮显示当前节点的所有上级和下级

### ISSUE THREAD

**Issue by zhou-fuhao** [antvis/G6#5335]
### AntV Open Source Contribution Plan（可选/Optional）

- [X] 我同意将这个 Issue 参与 OSCP 计划 / I agree to participate in the OSCP plan

### Issue 类型 / Issue Type

None

### 任务介绍 / Task Description

鼠标悬浮某一节点，高亮显示当前节点的所有上级和下级
![高亮](https://github.com/antvis/G6/assets/74893937/6ecda9db-8a63-418a-8166-752c6968cb2a)

### 参考说明 / Reference Description

https://codesandbox.io/p/sandbox/gao-liang-xian-shi-suo-you-shang-xia-ji-6c2pkt?file=%2Findex.js%3A12%2C5

**Comment by stakjun** [comment]
您好！，节点数据过多的会报栈溢出错误
