### ISSUE TITLE
Dagre流程图布局切换显示问题

### ISSUE THREAD

**Issue by pleiades-embers** [antvis/G6#5339]
### G6 Version

5.x

### Describe the bug

<img width="945" alt="image" src="https://github.com/antvis/G6/assets/44309088/59a9341f-c1dd-430f-9ffd-e5550e26b42f">

### Your Example Website or App

https://g6-next.antv.antgroup.com/zh/examples/net/dagreFlow/#dagre

### Steps to Reproduce the Bug or Issue

1. 点击LR 布局 在点击Default布局

### Expected behavior

点击Default 布局可以还原，为初始化的布局

### Platform

- OS: [e.g. macOS]
- Browser: [e.g. Chrome,]
- Version: [e.g. 120.0.6099.109]

**Comment by hustcc** [comment]
@pleiades-embers 感谢反馈，我们在迭代中处理下这个问题。
