### ISSUE TITLE
V5 自定义工具栏不展示

### ISSUE THREAD

**Issue by pleiades-embers** [antvis/G6#5340]
### G6 Version

5.x

### Describe the bug

v5文档的自定义工具不显示
<img width="950" alt="image" src="https://github.com/antvis/G6/assets/44309088/717057fe-2798-4bce-a422-a57fcc08eed8">

### Your Example Website or App

https://g6-next.antv.antgroup.com/zh/examples/tool/toolbar/#self-toolbar

### Steps to Reproduce the Bug or Issue

#

### Expected behavior

#

### Platform

- OS: [macOS]
- Browser: [Chrome]

**Comment by hustcc** [comment]
最新已解决。
