### ISSUE TITLE
getAllCombosData 获取的数据为空，getAllNodesData获取的数据包含combo数据

### ISSUE THREAD

**Issue by xyzgy** [antvis/G6#5341]
### G6 版本

5.x

### 问题描述

1、getAllCombosData 获取的数据为空，getAllNodesData获取的数据包含combo数据
2、labelShape 中 position 属性仅支持单一属性 'left-top'等未生效

### 重现链接

https://g6-next.antv.antgroup.com/zh/examples/item/defaultCombos/#rect

### 重现步骤

直接控制台打印  
  console.log(graph.getAllNodesData())
    console.log(graph.getAllCombosData())

### 预期行为

正常输出结果

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [5.x  ]

### 屏幕截图或视频（可选）

![image](https://github.com/antvis/G6/assets/21964169/06dac1a9-8231-4244-a769-ea68867c99c5)

**Comment by Aarebecca** [comment]
你好，这是两个已知的 Bug，我们后续会进行修复

**Comment by Aarebecca** [comment]
> Any updated? This problem still exists.

In the latest G6 5.0, We have solved the problem
