### ISSUE TITLE
4.8.21版本，带有collapsedSubstituteIcon属性的combo，折叠状态下没有选中效果，之前使用的4.6.18版本是有的

### ISSUE THREAD

**Issue by lvvgang** [antvis/G6#5349]
### 问题描述

4.8.21版本，带有collapsedSubstituteIcon属性的combo，折叠状态下没有选中效果，之前使用的4.6.18版本是有的

### 重现链接

https://g6.antv.antgroup.com/zh/examples/item/defaultCombos/#rect

### 重现步骤

1. combo设置
```javascript
combos: [
    {
      id: 'combo2',
      label: 'with substitute icon while collapsed',
      collapsed: true,
      collapsedSubstituteIcon: {
        show: true,
        img: 'https://gw.alipayobjects.com/mdn/rms_f8c6a0/afts/img/A*IEQFS5VtXX8AAAAAAAAAAABkARQnAQ',
        width: 72,
        height: 72
      }
    },
  ],
```
2. 点击图片，没有选中效果

### 预期行为

带有collapsedSubstituteIcon属性的combo，折叠状态下要有选中效果

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by dangwoshimeng** [comment]
使用4.8.21版本遇到了同样的问题，现在有解决方案吗？ @Aarebecca
