### ISSUE TITLE
通过graph.updateItem更新combo的collapsedSubstituteIcon属性不生效

### ISSUE THREAD

**Issue by lvvgang** [antvis/G6#5351]
### 问题描述

通过graph.updateItem更新combo的collapsedSubstituteIcon属性不生效

### 重现链接

https://g6.antv.antgroup.com/zh/examples/item/defaultCombos/#rect

### 重现步骤

1. 设置combo

```javascript
combos: [
    {
      id: 'combo2',
      label: 'with substitute icon while collapsed',
      collapsed: true,
      collapsedSubstituteIcon: {
        show: true,
        img: 'https://gw.alipayobjects.com/mdn/rms_f8c6a0/afts/img/A*IEQFS5VtXX8AAAAAAAAAAABkARQnAQ',
        width: 72,
        height: 72
      }
    },
  ]
```

2. 更新collapsedSubstituteIcon属性

```
graph.updateItem(item.id, {
    label: item.label,
    status: item.status,
    collapsedSubstituteIcon: {
        img: 'https://gw.alipayobjects.com/os/s/prod/antv/assets/image/logo-with-text-73b8a.svg'
    }
});
```

### 预期行为

调用updateItem后更新为新的图片

### 平台

- 操作系统: Windows
- 网页浏览器: Google Chrome
- G6 版本: 4.8.21

**Comment by SUMIT6409** [comment]
i am also facing the same issue

**Comment by SUMIT6409** [comment]
@Yanyan-Wang please help here.

**Comment by SUMIT6409** [comment]
@Yanyan-Wang please reply here, ill be really grateful

**Comment by sunrisexl** [comment]
遇到了同样的问题

**Comment by sunrisexl** [comment]
> > Encountered the same problem
> > use graph.read(yourdata) after update item operation. the update will take effect

It worked. Thank you.
