### ISSUE TITLE
右侧导航遮住底部导航

### ISSUE THREAD

**Issue by leixus** [antvis/G6#5355]
### 问题描述

右侧导航遮住底部导航

### 重现链接

https://antv-g6.gitee.io/zh/docs/manual/middle/elements/edges/defaultEdge#gatsby-focus-wrapper

### 重现步骤

滑动到底部

### 预期行为

不遮住

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![image](https://github.com/antvis/G6/assets/24884532/f951118b-a32b-40a7-a9d0-04be73793cfe)

**Comment by hustcc** [comment]
了解了，一个体验问题，有兴趣来做一个 PR 吗？

**Comment by Aarebecca** [comment]
新版 G6 5.0 站点已解决该问题
