### ISSUE TITLE
toolTip类型声明错误

### ISSUE THREAD

**Issue by Shen120** [antvis/G6#5358]
### 问题描述

https://github.com/antvis/G6/blob/ab461c1e27681c7a9db0966470f0ba172f93a474/packages/plugin/src/tooltip/index.ts#L186
![image](https://github.com/antvis/G6/assets/33613409/1598a359-fca4-4feb-b4dc-2d088483ff75)

这个地方文档上写的是返回HTMLDivElement，但是实际代码只能为string，不像上面那样判断过
https://github.com/antvis/G6/blob/ab461c1e27681c7a9db0966470f0ba172f93a474/packages/pc/src/behavior/tooltip-base.ts#L40
![image](https://github.com/antvis/G6/assets/33613409/765e2d07-69e3-4de5-aaff-bdf215397f71)

改一下噻

### 重现链接

https://github.com/antvis/G6/blob/ab461c1e27681c7a9db0966470f0ba172f93a474/packages/pc/src/behavior/tooltip-base.ts#L40

### 重现步骤

看代码

### 预期行为

类型正常或者兼容处理

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome]
- G6 版本: [4.5.1 ... ]

**Comment by hustcc** [comment]
感谢提交问题，有兴趣来个 PR 修复一下吗？

**Comment by Shen120** [comment]
> 感谢提交问题，有兴趣来个 PR 修复一下吗？

已提交
