### ISSUE TITLE
@antv/g6@5.0.0-beta.28 版本节点内容可滚动需要如何实现

### ISSUE THREAD

**Issue by liuchangheng** [antvis/G6#5367]
### 问题描述

@antv/g6@5.0.0-beta.28 版本节点内容可滚动需要如何实现， 我尝试使用otherShapes来实现，但是无法像 v4 版本一样生成 Group ，我使用appendChild 方法来为当前shape添加子节点，但是添加的子节点无法显示，是否有其他方式来实现

### 重现链接

https://g6-next.antv.antgroup.com/zh/examples/item/customNode/#card

### 重现步骤

使用otherShapes 创建一个类似于 group的图形，然后使用setClip方法， 最后将子节点添加到其父节点中

### 预期行为

我希望达成这样的效果 https://g6.antv.antgroup.com/examples/item/customNode/#scrollNode

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [@antv/g6@5.0.0-beta.28]

**Comment by Aarebecca** [comment]
创建一个容器，使用 [clipPath](https://g.antv.antgroup.com/api/basic/display-object#clippath) 进行窗口裁切。
或者你可以直接使用 React 节点
