### ISSUE TITLE
vue2版本导入5.0后报错

### ISSUE THREAD

**Issue by zzr1001** [antvis/G6#5368]
### 问题描述

导入G6的5.0版后，项目编译无法通过

### 重现链接

no

### 重现步骤

1.使用npm安装npm install --save @antv/g6@5.0.0-beta.28
2.导入g6

### 预期行为

导入后还没有使用，项目编译就会报错，像是依赖的问题，但我不知道怎么处理

### 平台

- 操作系统: win11
- 网页浏览器: Google 
- G6 版本:5.0.0-beta.28

### 屏幕截图或视频（可选）

![Snipaste_2024-01-25_16-03-58](https://github.com/antvis/G6/assets/78641054/c97dc793-cfd5-4ef7-b695-193a1ddc3915)

**Comment by lstgithub578** [comment]
依赖使用了类的私有属性，加入这两个babel插件试试
![image](https://github.com/antvis/G6/assets/55378864/46bd45a7-c99f-471b-a73b-222c3a515dec)
https://www.babeljs.cn/docs/babel-plugin-transform-private-property-in-object

**Comment by zzr1001** [comment]
依赖问题我通过配置transpileDependencies解决了，现在还存在layout插件内部文件似乎编译报错。
![image](https://github.com/antvis/G6/assets/78641054/33c8af58-8ad3-45e1-8f1b-e9f915854207)
那两个插件已经安装并且添加进babel.config.js，好像对出现的问题不起作用
![image](https://github.com/antvis/G6/assets/78641054/f49965f8-13db-4939-8b5a-adbf56a02bd4)

> 依赖使用了类的属性，加入这两个babel插件尝试https://www.babeljs.cn/docs/babel-plugin-transform-private-property-in-object ![图像](https://private-user-images.githubusercontent.com/55378864/299598236-46bd45a7-c99f-471b-a73b-222c3a515dec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNzM2NTYsIm5iZiI6MTcwNjE3MzM1NiwicGF0aCI6Ii81NTM3ODg2NC8yOTk1OTgyMzYtNDZiZDQ1YTctYzk5Zi00NzFiLWE3M2ItMjIyYzNhNTE1ZGVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDA5MDIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzNDViZjA2NWUyYmY5YzJmNGQ2ZjhhNmVlZGY3NzljMzdmYmMwODQ1ZTI5ODc5YWU0ZDZkMDhlZTFlZGMzZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lwkhqmg_IS0IqFQMsBNZMxbli93HUtQwHjHsUZq9WNs) [](https://www.babeljs.cn/docs/babel-plugin-transform-private-property-in-object)

**Comment by lstgithub578** [comment]
> 依赖问题我通过配置transpileDependencies解决了，现在还存在layout插件内部文件似乎编译报错。 ![image](https://private-user-images.githubusercontent.com/78641054/299602443-33c8af58-8ad3-45e1-8f1b-e9f915854207.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNzYxNzcsIm5iZiI6MTcwNjE3NTg3NywicGF0aCI6Ii83ODY0MTA1NC8yOTk2MDI0NDMtMzNjOGFmNTgtOGFkMy00NWUxLThmMWItZTlmOTE1ODU0MjA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDA5NDQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5MmI1YTQ4MTFhZDYwMmQ0YjNhNTZkZGRlYjRlMWMwNjI4ZGNlYzM1ZDAxYzg5NWEyODUzZTdjMWEzMTgyNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V6Ehbihsl5BidFamL8kwtcu9zEOWvddRreCq5GNSIM0) 那两个插件已经安装并且添加进babel.config.js，好像对出现的问题不起作用 ![image](https://private-user-images.githubusercontent.com/78641054/299602843-f49965f8-13db-4939-8b5a-adbf56a02bd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNzYxNzcsIm5iZiI6MTcwNjE3NTg3NywicGF0aCI6Ii83ODY0MTA1NC8yOTk2MDI4NDMtZjQ5OTY1ZjgtMTNkYi00OTM5LThiNWEtYWRiZjU2YTAyYmQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDA5NDQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiNjc2OTFiM2JkZTM4NTNiY2RjODZkZDdkNmM3ZmRmOGQwNTIwODg2MjU5NDIyMDE4Yjc2NzI1Y2FkMzA4ZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bKz7J2Rdany6O98nDlkgnjmlMha3TYp6bZSwBdsNPBA)
> 
> > 依赖使用了类的属性，加入这两个babel插件尝试https://www.babeljs.cn/docs/babel-plugin-transform-private-property-in-object ![图像](https://private-user-images.githubusercontent.com/55378864/299598236-46bd45a7-c99f-471b-a73b-222c3a515dec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNzM2NTYsIm5iZiI6MTcwNjE3MzM1NiwicGF0aCI6Ii81NTM3ODg2NC8yOTk1OTgyMzYtNDZiZDQ1YTctYzk5Zi00NzFiLWE3M2ItMjIyYzNhNTE1ZGVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDA5MDIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzNDViZjA2NWUyYmY5YzJmNGQ2ZjhhNmVlZGY3NzljMzdmYmMwODQ1ZTI5ODc5YWU0ZDZkMDhlZTFlZGMzZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lwkhqmg_IS0IqFQMsBNZMxbli93HUtQwHjHsUZq9WNs)

我试了一下用了那两个babel后没问题
![image](https://github.com/antvis/G6/assets/55378864/c0094543-2b54-4ff5-b7bf-5963f761d19b)
![image](https://github.com/antvis/G6/assets/55378864/8bf1d11e-a1c1-4e69-b821-11236b724ad9)

**Comment by zzr1001** [comment]
> 我试了一下用了那两个babel可以正常运行 ![image](https://private-user-images.githubusercontent.com/55378864/299614596-a9c6757f-fde9-4a35-b4f4-6eb51f591335.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNzk1NzgsIm5iZiI6MTcwNjE3OTI3OCwicGF0aCI6Ii81NTM3ODg2NC8yOTk2MTQ1OTYtYTljNjc1N2YtZmRlOS00YTM1LWI0ZjQtNmViNTFmNTkxMzM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDEwNDExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0MjU1MTNjNzFmNWY5ODkxNWZiNmYzOWE0NjM1NjdmZGRlMWU2NjgyMGM4YWFjYjhkOTYzOWI5MGMxNzAyZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6VMs_S73hqstQNrVI0AV5xpS7Ug0FfV-IciGkoQLNXE) ![image](https://private-user-images.githubusercontent.com/55378864/299614658-3fe6515b-a1d6-417a-8b50-47de5c97906f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNzk1NzgsIm5iZiI6MTcwNjE3OTI3OCwicGF0aCI6Ii81NTM3ODg2NC8yOTk2MTQ2NTgtM2ZlNjUxNWItYTFkNi00MTdhLThiNTAtNDdkZTVjOTc5MDZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDEwNDExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzMjZkZDA3NGEzMGM0ZGJiNTJhN2I0OWRmZjg1YjFiM2ExZDg4ZTlmYTM1YjY0OGNlYjgxYmRlODVhMDZlM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ewrvBN8kssVRMcOIpx4rOI8YA81S6JPmcu6QT6y04jY)

能打包给我其他文件，我研究下是哪里配置的问题

**Comment by lstgithub578** [comment]
> > 我试了一下用了那两个babel可以正常运行 ![image](https://private-user-images.githubusercontent.com/55378864/299614596-a9c6757f-fde9-4a35-b4f4-6eb51f591335.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNzk1NzgsIm5iZiI6MTcwNjE3OTI3OCwicGF0aCI6Ii81NTM3ODg2NC8yOTk2MTQ1OTYtYTljNjc1N2YtZmRlOS00YTM1LWI0ZjQtNmViNTFmNTkxMzM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDEwNDExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0MjU1MTNjNzFmNWY5ODkxNWZiNmYzOWE0NjM1NjdmZGRlMWU2NjgyMGM4YWFjYjhkOTYzOWI5MGMxNzAyZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6VMs_S73hqstQNrVI0AV5xpS7Ug0FfV-IciGkoQLNXE) ![image](https://private-user-images.githubusercontent.com/55378864/299614658-3fe6515b-a1d6-417a-8b50-47de5c97906f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNzk1NzgsIm5iZiI6MTcwNjE3OTI3OCwicGF0aCI6Ii81NTM3ODg2NC8yOTk2MTQ2NTgtM2ZlNjUxNWItYTFkNi00MTdhLThiNTAtNDdkZTVjOTc5MDZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDEwNDExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzMjZkZDA3NGEzMGM0ZGJiNTJhN2I0OWRmZjg1YjFiM2ExZDg4ZTlmYTM1YjY0OGNlYjgxYmRlODVhMDZlM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ewrvBN8kssVRMcOIpx4rOI8YA81S6JPmcu6QT6y04jY)
> 
> 能打包给我其他文件，我研究下是哪里配置的问题

[g6@5_demo.zip](https://github.com/antvis/G6/files/14059748/g6%405_demo.zip)
我是用脚手架新建的项目

**Comment by zzr1001** [comment]
> > > 我试了一下用了那两个babel可以正常运行 ![image](https://private-user-images.githubusercontent.com/55378864/299614596-a9c6757f-fde9-4a35-b4f4-6eb51f591335.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNzk1NzgsIm5iZiI6MTcwNjE3OTI3OCwicGF0aCI6Ii81NTM3ODg2NC8yOTk2MTQ1OTYtYTljNjc1N2YtZmRlOS00YTM1LWI0ZjQtNmViNTFmNTkxMzM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDEwNDExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0MjU1MTNjNzFmNWY5ODkxNWZiNmYzOWE0NjM1NjdmZGRlMWU2NjgyMGM4YWFjYjhkOTYzOWI5MGMxNzAyZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6VMs_S73hqstQNrVI0AV5xpS7Ug0FfV-IciGkoQLNXE) ![image](https://private-user-images.githubusercontent.com/55378864/299614658-3fe6515b-a1d6-417a-8b50-47de5c97906f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNzk1NzgsIm5iZiI6MTcwNjE3OTI3OCwicGF0aCI6Ii81NTM3ODg2NC8yOTk2MTQ2NTgtM2ZlNjUxNWItYTFkNi00MTdhLThiNTAtNDdkZTVjOTc5MDZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDEwNDExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzMjZkZDA3NGEzMGM0ZGJiNTJhN2I0OWRmZjg1YjFiM2ExZDg4ZTlmYTM1YjY0OGNlYjgxYmRlODVhMDZlM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ewrvBN8kssVRMcOIpx4rOI8YA81S6JPmcu6QT6y04jY)
> > 
> > 
> > 能打包给我其他文件，我研究下是哪里配置的问题
> 
> [g6@5_demo.zip](https://github.com/antvis/G6/files/14059748/g6%405_demo.zip) 我是用脚手架新建的项目

谢谢，解决了。需要vue-cli5.x创建的项目,我这个旧项目是之前使用4.x的版本创建的项目。升级到5.x后就好了

**Comment by hustcc** [comment]
欢迎大家去封装一些 vue 的 G6 组件，这样开源出来，其他人可以直接使用了。

**Comment by 673575554** [comment]
我这边也碰到这个情况了，安装了插件也没有作用，必须要升级vue-cli嘛

**Comment by 673575554** [comment]
换成4的版本成功了

**Comment by JishuaiWang** [comment]
必须换4的版本或者升级vue-cli吗？
