### ISSUE TITLE
G6的文档什么时候能完善/改版下？还不如旧版的好用！

### ISSUE THREAD

**Issue by beautycss** [antvis/g6#537]
现在的文档看起来好费劲，要实现个简单功能文档要找半天！

举例：
我现在要实现一个基本的树形流图，然后第一个和第二个节点有不同的颜色，期望的效果是下图这样。
![image](https://user-images.githubusercontent.com/16473160/48688750-7ada0b80-ec02-11e8-9720-6108f012a564.png)

1. 树形很好实现，有demo。
2. 圆角矩形也好弄，参看了基础demo。
3. 颜色，实现这个花费了最主要的时间：
  1) 看自定义节点的demo，发现没用。
  2) 看API > Node的文档，没有。
  3) 看API > Item的文档，没有。
  4) 看API > Tree的文档，没有。
  5) 看API > Graph > Node的文档，终于发现了color属性。

![image](https://user-images.githubusercontent.com/16473160/48689118-ff795980-ec03-11e8-98f2-b7e5f296f0d0.png)

如最上面的效果图，想实现第一个和第二个颜色自定义，其他默认颜色，这时我需要使用function，然而文档的color在使用function情况下没写出参数是什么。
经过实践发现，有且只有一个参数，是当前的数据项。

至此，这一个简单的树形图才实现。
部分代码如下：
```
graph.node({
    size: 8,
    shape: 'rect',
    color: function color(model) {
      return model.color || '#3B85BA'; // 默认颜色
    },
    label: function label(model) {
      if (model.children && model.children.length > 0) {
        return {
          fill: '#fff',
          text: model.name
        };
      }
      return {
        fill: '#fff',
        text: model.name
      };
    },
    labelOffsetX: function labelOffsetX(model) {
      if (model.children && model.children.length > 0) {
        return -10;
      }
      return 10;
    } 
  });
```

可能有人会说，要把Graph的文档全部了解清楚，才能更好的去实现想要的东西。但是人都有遗忘周期的，而且g6相对于g2等其他图表使用相对较少。即使这次弄清楚，下次用g6的时候可能就记不清了，又要重新各种找。

所以，我认为目前的文档至少要从以下几方面改进：
1. 增加搜索功能。这个是最重要的，也许我找那么久，用一个搜索就能搜出color在哪。
2. 完善API属性，包括参数之类的。
3. 期望能改成像g2的文档那样，上面有toc，右侧也有子导航，清晰容易查找。像[旧版G6文档](https://antvis.github.io/g6/api/graph.html)的上面就有toc，更容易查找。

![image](https://user-images.githubusercontent.com/16473160/48688871-fb990780-ec02-11e8-8566-eaa122cdd560.png)

**Comment by xxShawn** [comment]
如果节点内容过长， 矩形要自动适应是怎么做的？

**Comment by beautycss** [comment]
> 如果节点内容过长， 矩形要自动适应是怎么做的？

还没有处理这个问题。

**Comment by TomHuangCN** [comment]
1. 语雀文档有搜索功能
2. 感谢反馈文档问题，已改进
