### ISSUE TITLE
求助：收起combo，内部的全部连线汇总连线到combo的这条线是否可以不生成

### ISSUE THREAD

**Issue by TabCrazy** [antvis/G6#5372]
### Describe the bug

收起combo，内部的全部连线汇总连线到combo的这条线是否可以不生成

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

收起combo，内部的全部连线汇总连线到combo的这条线是否可以不生成

### Expected behavior

可配置、或者操作
收起combo，内部的全部连线汇总连线到combo的这条线是否可以不生成

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
Windows

**Comment by hustcc** [comment]
能有具体的截图案例吗？

**Comment by Aarebecca** [comment]
你的诉求目前只能够通过自定义数据处理逻辑实现
