### ISSUE TITLE
5.0.0版本普通图数据使用compactBox树图布局根节点位置出错

### ISSUE THREAD

**Issue by l-besiege-l** [antvis/G6#5387]
### 问题描述

普通图数据使用compactBox树图布局时，根节点没有位于最末端
![image](https://github.com/antvis/G6/assets/52117792/e7edcc69-2566-4e12-bd35-a43ab64f8302)
添加树图布局的节点展开及收缩代码，点击根节点无法全部收缩，图实例疑似把最左边的节点视为了根节点（即使它不是所有节点的出发点），点击最左边节点会全部收缩，而点击根节点只会把它布局右边的节点收缩起来
```javascript
graph.on("node:click", (e) => {
  const { itemId } = e;
  const nodeData = graph.getNodeData(itemId);
  if (nodeData) {
    if (isExpanded) {
      graph.collapse(itemId);
      isExpanded = false;
      console.log("折叠");
    } else {
      graph.expand(itemId);
      isExpanded = true;
      console.log("展开");
    }
  }
});
```
![image](https://github.com/antvis/G6/assets/52117792/7ee4ff41-fa5a-43b4-937c-10bdc3febf06)

### 重现链接

https://dgf2xp.csb.app/

### 重现步骤

点击重现链接即可

### 预期行为

期望看到树图布局中节点的层级关系能正确显示

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Edge]
- G6 版本: [5.0.0-beta.28]

**Comment by Aarebecca** [comment]
在正式版中已解决该问题，可参考：https://g6-next.antv.antgroup.com/examples/layout/mindmap/#auto-side
