### ISSUE TITLE
v4.8.21版本移动产生残影

### ISSUE THREAD

**Issue by wczdsg** [antvis/G6#5392]
### 问题描述

移动整个图，顶部出现残影，怀疑当图最上方为text时移动会出现残影

### 重现链接

https://g6.antv.vision/examples/scatter/node/#node

### 重现步骤

1.进入页面
2.graph的配置里加上modes:{default:['drag-canvas']}使图可拖拽
3.最上方文字出现残影

### 预期行为

没有残影

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.8.21 ... ]

### 屏幕截图或视频（可选）

![image](https://github.com/antvis/G6/assets/73579422/2a550b40-7a09-467c-972d-3a82081eec6e)

**Comment by hustcc** [comment]
设置 localRefresh 为 false。
