### ISSUE TITLE
dagre布局生成后里面的节点位置怎么自我调整

### ISSUE THREAD

**Issue by AthrunLLH** [antvis/G6#5403]
### 问题描述

![Snipaste_2024-01-31_18-34-30](https://github.com/antvis/G6/assets/133658227/94fb289d-56c4-4377-8f5b-6dc3d43e5ab1)
![Snipaste_2024-01-31_18-36-07](https://github.com/antvis/G6/assets/133658227/5f62f808-cc6b-4a8d-9dcb-63a48aca2863)
combo的位置没有很好的对齐，然后我需要放的流程位置也不是很正常

### 重现链接

暂无

### 重现步骤

输入了对应的节点信息以及连线，然后使用了dagre布局

### 预期行为

我希望调整之后是像图二一样的，在代码中应该如何去设置呢

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by yangyili** [comment]
可以通过调整节点的顺序来实现。比如将红色框里的”采购项目委托“的节点对应的数据，放在”采购方案“对应的节点数据后面

**Comment by Aarebecca** [comment]
试下这个配置呢：https://g6.antv.antgroup.com/api/graph-layout/dagre#layoutcfgnodeorder

**Comment by seifenk** [comment]
> 可以通过调整节点的顺序来实现。比如将红色框里的”采购项目委托“的节点对应的数据，放在”采购方案“对应的节点数据后面

这不是自欺欺人吗
