### ISSUE TITLE
为什么我使用g6的元素实例方法item.hide()就正常，item.changeVisibility()就报错呢？？

### ISSUE THREAD

**Issue by Fzt1120** [antvis/G6#5409]
### 问题描述

为什么我使用g6的元素实例方法item.hide()就正常，item.changeVisibility()就报错呢？？

### 重现链接

.

### 重现步骤

.

### 预期行为

.

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![Snipaste_2024-02-01_17-24-31](https://github.com/antvis/G6/assets/142973826/e5b7f302-1b4e-432f-8d62-2ae764ebfca9)
![Uploading Snipaste_2024-02-01_17-25-01.png…]()
![Snipaste_2024-02-01_17-25-16](https://github.com/antvis/G6/assets/142973826/5f9284df-aec6-4328-9ed0-35e47430b770)

**Comment by Fzt1120** [comment]
![Snipaste_2024-02-01_17-25-01](https://github.com/antvis/G6/assets/142973826/4b7edc2d-9a9a-40f2-9a17-636364caf447)

**Comment by ravengao** [comment]
从你的代码看，`buttons`和`buttonParents`似乎是图形（Shape），而不是元素（item，比如node，combo、edge）
操作图形显示/隐藏只能通过shape.hide(), shape.show()达成

参考图形（Shape）的Typescript type: `IShape extends IElement`, IElement存在hide/show定义，但没有changeVisibility
