### ISSUE TITLE
请问changeData和read的区别是啥？

### ISSUE THREAD

**Issue by GitHubJackson** [antvis/G6#5429]
### 问题描述

似乎文档里看不出这两者的区别，我在实际项目中使用changeData，但是数据的节点删掉了一些后，我看图里仍然保留了之前的节点，这里很困惑。用read就正常了

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Aarebecca** [comment]
这是 4.x 时期的设计，本意是期望在初始化的时候使用 `read` 来代替 `data` + `render`，更新过程中使用 `changeData`，不过这种设计已经过时了，G6 5.0 会使用新的数据操纵API，提供 `setData` `getData` `addData` `updateData` `removeData` API
