### ISSUE TITLE
addshape text 文字换行有没有支持，紧凑树的V型布局能不能控制谁上谁下

### ISSUE THREAD

**Issue by orGancode** [antvis/g6#543]
你们好，使用过程中有两个困难点。
1、在注册节点时绘制文字 ，当文字过长会溢出，目前有没有支持换行的参数配置；
2、紧凑树V方向的布局会自动分配一上一下的两棵树，有没有方法可以限制子级在上面或者在下面呢。
烦请解答，谢谢。

**Comment by TomHuangCN** [comment]
1. \n 是换行符
2. 没有，需要你自己写布局
