### ISSUE TITLE
[v5] 调用 ```graph.setItemState``` 不能触发自定义Node时复写的```setState```方法

### ISSUE THREAD

**Issue by zzjjbbaa** [antvis/G6#5459]
### Describe the bug

[v5] 调用 ```graph.setItemState``` 不能触发自定义Node时复写的setState方法

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

[v5] 调用 ```graph.setItemState``` 不能触发自定义Node时复写的setState方法

### Expected behavior

[v5] 调用 ```graph.setItemState``` 不能触发自定义Node时复写的setState方法

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Aarebecca** [comment]
使用的最新的分支代码复现的吗

**Comment by Aarebecca** [comment]
这边使用的 5.0.0-beta 还是最新分支代码的内容

**Comment by zzjjbbaa** [comment]
> 这边使用的 5.0.0-beta 还是最新分支代码的内容

### beta28

**Comment by Aarebecca** [comment]
目前自定义节点已经移除了相关方法，请参考最新的 G6 5.0 进行调整

**Comment by coyzeng** [comment]
移除至少写一下replacement的文档啊，或者这个issue里备注下

**Comment by coyzeng** [comment]
> 目前自定义节点已经移除了相关方法，请参考最新的 G6 5.0 进行调整


移除至少写一下replacement的文档啊，或者这个issue里备注下

**Comment by hentailong** [comment]
> 目前自定义节点已经移除了相关方法，请参考最新的 G6 5.0 进行调整

所以现在该用什么代替
