### ISSUE TITLE
文档中，拖拽、拖曳具体有什么区别吗

### ISSUE THREAD

**Issue by anguof** [antvis/G6#5461]
### 问题描述

文档中，拖拽、拖曳具体有什么区别吗
![image](https://github.com/antvis/G6/assets/34739658/4a87b900-0578-46ff-941d-58902bf85483)

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Aarebecca** [comment]
系笔误，没有区别，后续会订正。
