### ISSUE TITLE
exports is not defined

### ISSUE THREAD

**Issue by jcz-sudo** [antvis/G6#5466]
### 问题描述

<img width="755" alt="antv" src="https://github.com/antvis/G6/assets/70131290/691645f7-a30c-414b-aeb1-e0e57bcf51df">

### 重现链接

无

### 重现步骤

在页面引入了@antv/g6

### 预期行为

提示exports未定义

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome]
- G6 版本: [^5.0.0-beta.28 ]

**Comment by hustcc** [comment]
https://github.com/antvis/G6/pull/5546 已经发布一个 beta 版本，应该修复了这个问题，近期会大量做一些小的体验和 bugfix。
