### ISSUE TITLE
[V5-Beta28]  官网提供的示例代码：三层拓扑模型，数据源中的x,y,z坐标是如何计算的

### ISSUE THREAD

**Issue by xichao520** [antvis/G6#5478]
### 问题描述

三层拓扑模型示例，其中数据源中的x,y,z坐标是如何计算的，有没有提供相关的计算方法？

### 重现链接

https://g6-next.antv.antgroup.com/zh/examples/feature/features#layerTopology

### 重现步骤

直接访问https://g6-next.antv.antgroup.com/zh/examples/feature/features#layerTopology

### 预期行为

期望能否尽快看到像V4一样比较详细的V5文档

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [5.0.0 ]

**Comment by Aarebecca** [comment]
该示例由社区用户提供，你可以向其咨询
