### ISSUE TITLE
[v5] 官方示例无法跑通 

### ISSUE THREAD

**Issue by Amigosen** [antvis/G6#5480]
### 问题描述

（使用 React 写法创建自定义 G 节点）此例子 第二行报错 import { createReactNode } from '@antv/g6-react-node';  
模块“"@antv/g6-react-node"”没有导出的成员“createReactNode”。
"@antv/g6-react-node": "^1.4.8",

### 重现链接

https://g6-next.antv.antgroup.com/examples/item/customNode#react-node

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by hustcc** [comment]
G6 5.0 在对 API 进行一些调整，三月我们会对官网的 DEMO 进行 review 一下，到时候一起处理这个问题。

**Comment by Aarebecca** [comment]
你好，现在可以使用 g6 5.0 正式版了，已经解决上述问题
