### ISSUE TITLE
v4.8.21内存泄漏问题

### ISSUE THREAD

**Issue by wczdsg** [antvis/G6#5495]
### 问题描述

在实际开发中发现销毁图形后，内存并没有被释放干净，于是去测官方案例，打开性能案例菜单的 “50000+图元”，加载完成后退出到上一个页面，再次打开加载退出，重复三次，内存占用达到1.2G无法释放

### 重现链接

https://g6.antv.vision/examples#performance-perf

### 重现步骤

1.打开页面选择性能测试-性能案例-50000+图元
2.等待数据加载完成，后退
3.多重复几次
4.查看内存占用

### 预期行为

期望内存释放

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.8.21 ... ]

### 屏幕截图或视频（可选）

![image](https://github.com/antvis/G6/assets/73579422/744a00f6-708f-436f-9133-fdf0f29b118f)

**Comment by dangwoshimeng** [comment]
遇到了同样的问题，怀疑是动画引起的，4.8.21还会有后续补丁版本解决此问题吗？

**Comment by alaAicy** [comment]
I also met the same problem, how did you solve it

**Comment by Aarebecca** [comment]
> 遇到了同样的问题，怀疑是动画引起的，4.8.21还会有后续补丁版本解决此问题吗？

4.x 后续暂不会处理该问题
