### ISSUE TITLE
如何理解ev.item中节点和ev.shape的概念，能否具体讲一下区别

### ISSUE THREAD

**Issue by itsmyturn** [antvis/g6#55]
![image](https://user-images.githubusercontent.com/11573322/28904494-f4f60eee-783d-11e7-911a-df8ba3846add.png)

**Comment by TomHuangCN** [comment]
ev.shape 是具体的图形，是绘图引擎层的概念。 ev.item 是抽象的节点或边，是 Graph 图的概念

**Comment by itsmyturn** [comment]
好的，非常感谢
