### ISSUE TITLE
G6的群组支持自定义背景颜色吗？

### ISSUE THREAD

**Issue by luoandy** [antvis/g6#551]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by awebird** [comment]
支持，配置 style: { fill: 'rgba(246,243,172,1)' }

**Comment by luoandy** [comment]
> 支持，配置 style: { fill: 'rgba(246,243,172,1)' }

好的  非常感谢
