### ISSUE TITLE
G6是否有按需引入功能

### ISSUE THREAD

**Issue by lukemora** [antvis/G6#5512]
### 问题描述

G6 Version: 4.6.3

Platform:
无
Mini Showcase(like screenshots):
无
CodePen Link:
无

### 重现链接

无

### 重现步骤

无

### 预期行为

实现按需引入，最大程度减少打包体积

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ] 4.6.3

**Comment by hustcc** [comment]
v5会有按需加载，且会处理好副作用代码，自己扩展包，让在乎包大小的能自行构建。

v4 现有架构不会去处理！
