### ISSUE TITLE
Mindmap 脑图树，多个根结点情况下，垂直方向的间距在递增，导致分布不均匀

### ISSUE THREAD

**Issue by 819slw** [antvis/G6#5515]
### 问题描述

Mindmap 脑图树，多个根结点情况下，垂直方向的间距在递增，导致分布不均匀.

从npm的安装包中的dist文件中拿到的min.js文件 

### 重现链接

http://lc-OyT08TxX.cn-n1.lcfile.com/6niA1qv4nvknu4jwplOxSYFbTH05pijm/index.html

### 重现步骤

进入界面即可重现

### 预期行为

垂直方向上多个根节点能够均匀分布

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- G6 版本: [5.0.0-beta.27]

### 屏幕截图或视频（可选）

![WeChat834182183c7f9e38ad516d3de2d87d9d](https://github.com/antvis/G6/assets/30892272/21798eed-fda3-4355-bd98-e3a26d9a07f6)

**Comment by Aarebecca** [comment]
duplicate with https://github.com/antvis/G6/issues/5516
