### ISSUE TITLE
树的闭环渲染

### ISSUE THREAD

**Issue by skyfore** [antvis/G6#5520]
### 问题描述

想要实现树的闭环渲染，比如这种

<img src="https://github.com/antvis/G6/assets/7485049/8c197781-14f1-40b1-b1ce-7b2976b686db" height="200" width="200">

或者这种

<img src="https://github.com/antvis/G6/assets/7485049/17648484-4f21-4590-856a-c62f7821e52c" height="200" width="200">

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Aarebecca** [comment]
使用 dagre 布局即可 [Demo](https://g6.antv.antgroup.com/examples/net/dagreFlow/#basicDagre)

**Comment by skyfore** [comment]
感谢，我看下是否可行 @Aarebecca
