### ISSUE TITLE
G6的节点如何使用背景图片呢？支持使用背景图片么？

### ISSUE THREAD

**Issue by 12345678starry** [antvis/g6#553]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by Jarryham** [comment]
用自定义节点，然后在注册节点的时候，直接 group.addShape('image', {attrs: {}})

**Comment by dongongfeiyu** [comment]
这个可以使用动态图吗？

**Comment by Jarryham** [comment]
> group.addShape('image', {attrs: {}}) 这里image 的src 是直接写在attrs里面么？想要节点是圆，圆里是图片，按照你说的简单写了一下不可以，能麻烦您给一个具体一点的例子么？感谢

https://codepen.io/jarryham/pen/QzgJBO   链接是写在attrs里面的，在img: XXXX里，你可以看看这个，配置项写得具体点https://github.com/antvis/g

**Comment by Jarryham** [comment]
> 这个可以使用动态图吗？
可以用html节点 https://codepen.io/jarryham/pen/GPEPMO

**Comment by yuanchuan** [comment]
还要注意这个坑：https://github.com/antvis/g6/issues/451

**Comment by fallowu** [comment]
> 还要注意这个坑：#451

请问下，自定义注册图片节点类型，只注册一次。那么多个图片节点怎么实现预加载呢？

**Comment by baizn** [comment]
和一个图片节点方式类似，图片都先加载进来，draw的时候根据具体情况处理。
