### ISSUE TITLE
自定义节点样式，多个shape，怎么调整前后层级？

### ISSUE THREAD

**Issue by awebird** [antvis/g6#554]
* **G6 Version**: 2.2.0
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://codepen.io/awebird/pen/roVqdY

如codepen所示，希望左上角circle图层在rect之前 （但是仍然以rect为keyShape）
如果根据zIndex，sort()加在哪里？
如果因为性能原因不用sort()，按其它issue回复，先add rect，后add circle，那怎么设置先加的rect为keyShape （考虑锚点和其它功能，需要rect为keyShape）?

**Comment by yuanchuan** [comment]
在 `draw()` 当中试试这样：

```js
draw() {
  let rect = group.addShape('rect', { ... });
  let circle = group.addShape('circle', { });
  
  return rect;
}
```

**Comment by awebird** [comment]
> 在 `draw()` 当中试试这样：
> 
> ```js
> draw() {
>   let rect = group.addShape('rect', { ... });
>   let circle = group.addShape('circle', { });
>   
>   return rect;
> }
> ```

多谢，赞！
