### ISSUE TITLE
[v5][插件] 画布背景支持设置图片

### ISSUE THREAD

**Issue by yvonneyx** [antvis/G6#5542]
### 问题描述

目前画布背景支持颜色设置，正在计划进一步扩展此功能，例如增加对背景图片的支持

### 重现链接

/

### 重现步骤

-

### 预期行为

/

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by hustcc** [comment]
这个 能力在 watermark 中已经支持，未来如果要单独做 background，再开启。
