### ISSUE TITLE
Migrate ClickSelect Behavior

### ISSUE THREAD

**Issue by Aarebecca** [antvis/G6#5549]
### AntV Open Source Contribution Plan（可选/Optional）

- [X] 我同意将这个 Issue 参与 OSCP 计划 / I agree to participate in the OSCP plan

### Issue 类型 / Issue Type

中级任务 / Intermediate Task

### 任务介绍 / Task Description

迁移`点击选择`交互 [Demo](https://g6-next.antv.antgroup.com/zh/examples/interaction/select/#click)

---

Migrate `Click Select` behavior [Demo](https://g6-next.antv.antgroup.com/zh/examples/interaction/select/#click)

### 参考说明 / Reference Description

您可以参考[旧代码](https://github.com/antvis/G6/blob/v5-old/packages/g6/src/stdlib/behavior/click-select.ts)并考虑复用其中的部分逻辑。但请注意以下几点：

* 需要调整配置项的命名，以保持与当前交互命名风格的一致性。
* 根据您的理解，您可以对部分逻辑进行修改或优化。
* 不要迁移 History 相关的逻辑（例如：`graph.startHistoryBatch`）

在正式开始之前，建议您简要了解新版交互实现的逻辑和配置项命名风格，例如：[Drag Canvas](https://github.com/antvis/G6/blob/v5/packages/g6/src/behaviors/drag-canvas.ts)和[Drag Element](https://github.com/antvis/G6/blob/v5/packages/g6/src/behaviors/drag-element.ts)。

在迁移过程中，如果遇到任何问题，欢迎在Issues区留言寻求帮助。

---

You are encouraged to consult the [old code](https://github.com/antvis/G6/blob/v5-old/packages/g6/src/stdlib/behavior/click-select.ts) and consider reusing some of its logic. However, please keep in mind the following points:

* The naming of configuration items needs to be adjusted to remain consistent with the current interaction naming conventions.
* Based on your understanding, you are welcome to modify or enhance parts of the logic as you see fit.
* Do not migrate History related logic (e.g. `graph.startHistoryBatch`)

Before you begin, it is advisable to familiarize yourself briefly with the logic and naming conventions of configuration items used in the newer versions of interaction implementations, such as: [Drag Canvas](https://github.com/antvis/G6/blob/v5/packages/g6/src/behaviors/drag-canvas.ts) and [Drag Element](https://github.com/antvis/G6/blob/v5/packages/g6/src/behaviors/drag-element.ts).

Should any issues arise during the migration process, you are welcome to seek assistance by posting a message in the Issues section.

**Comment by yvonneyx** [comment]
认领~

**Comment by yvonneyx** [comment]
#5636
