### ISSUE TITLE
G6自定义节点多个shape有什么方法可以获取非keyShape的图形？

### ISSUE THREAD

**Issue by awebird** [antvis/G6#555]
* **G6 Version**: 2.2.0
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://codepen.io/awebird/pen/pqgaXE

比如codePen示例里，如果想在afterDraw里给非keyShape的circle原点做动画，怎么能获取到并处理？

**Comment by awebird** [comment]
单纯实现这个需求，可以直接在draw方法里addShape后加animate
如果是在定义之后实现类似功能，是否考虑addShape时加id，item可以根据getShape by id再处理

**Comment by dongongfeiyu** [comment]
您好，我们可以把一个svg的动态图片通过自定义节点的方式画出来吗？

**Comment by awebird** [comment]
扒拉了G的源码，在group中用find方法勉强实现了 参考 https://codepen.io/awebird/pen/MZGOQR
