### ISSUE TITLE
Implement FocusElement Behavior

### ISSUE THREAD

**Issue by Aarebecca** [antvis/G6#5554]
### AntV Open Source Contribution Plan（可选/Optional）

- [X] 我同意将这个 Issue 参与 OSCP 计划 / I agree to participate in the OSCP plan

### Issue 类型 / Issue Type

初级任务 / Primary Task

### 任务介绍 / Task Description

实现 `聚焦元素`交互

聚焦元素可以通过单击或双击元素，来将元素置为激活状态(`setElementState`)并移动至画布中心(`focusElement`)

---

Implement `FocusElement` behavior

Focus elements can be placed in the active state (`setElementState`) and moved to the center of the canvas (`focusElement`) by clicking or double-clicking an element.

### 参考说明 / Reference Description

在正式开始之前，建议您简要了解新版交互实现的逻辑和配置项命名风格，例如：[Drag Canvas](https://github.com/antvis/G6/blob/v5/packages/g6/src/behaviors/drag-canvas.ts)和[Drag Element](https://github.com/antvis/G6/blob/v5/packages/g6/src/behaviors/drag-element.ts)。

在迁移过程中，如果遇到任何问题，欢迎在Issues区留言寻求帮助。

---

Before you begin, it is advisable to familiarize yourself briefly with the logic and naming conventions of configuration items used in the newer versions of interaction implementations, such as: [Drag Canvas](https://github.com/antvis/G6/blob/v5/packages/g6/src/behaviors/drag-canvas.ts) and [Drag Element](https://github.com/antvis/G6/blob/v5/packages/g6/src/behaviors/drag-element.ts).

Should any issues arise during the migration process, you are welcome to seek assistance by posting a message in the Issues section.

**Comment by ai-qing-hai** [comment]
1

**Comment by ai-qing-hai** [comment]
@Aarebecca
