### ISSUE TITLE
注册节点不兼容ie11,是有这样的问题吗

### ISSUE THREAD

**Issue by chuncuiwuyou** [antvis/G6#556]
G6.registerNode('customHtml1', {
	draw(item){
      const group = item.getGraphicGroup();
      return group.addShape('rect', {
      attrs: {
        x: 0,
        y: 0,
        width: 100,
        height: 100,
        stroke: 'red'
      }
    });
  }
});

加上注册的节点火狐上是可以显示，但是ie11不显示，去掉的话，ie11就可以显示了，是否现在的大部分功能都不兼容ie11

**Comment by baizn** [comment]
IE11 不支持 这种写法。
```
G6.registerNode('customHtml1', {
draw(item){
const group = item.getGraphicGroup();
return group.addShape('rect', {
attrs: {
x: 0,
y: 0,
width: 100,
height: 100,
stroke: 'red'
}
});
}
});
```
换成这种：
```
G6.registerNode('customHtml1', {
draw: function draw(item){
const group = item.getGraphicGroup();
return group.addShape('rect', {
attrs: {
x: 0,
y: 0,
width: 100,
height: 100,
stroke: 'red'
}
});
}
});
```
