### ISSUE TITLE
Contribute Toolbar Plugin

### ISSUE THREAD

**Issue by Aarebecca** [antvis/G6#5562]
### AntV Open Source Contribution Plan（可选/Optional）

- [x] 我同意将这个 Issue 参与 OSCP 计划 / I agree to participate in the OSCP plan

### Issue 类型 / Issue Type

高级任务 / Advanced Task

### 任务介绍 / Task Description

<img width="137" alt="image" src="https://github.com/antvis/G6/assets/25787943/a148f925-4703-4536-a5d7-613b8ac3ba02">

开发 `工具条` 插件

---

Develop `Toolbar` plugin

### 参考说明 / Reference Description

这是一个新的插件，我们决定不再复用旧的插件，因此您可以根据自己的理解来设计和开发。

在正式开始之前，建议您简要了解新版插件实现的逻辑和配置项命名风格，例如：[GridLine](https://github.com/antvis/G6/blob/v5/packages/g6/src/plugins/grid-line.ts)。

在迁移过程中，如果遇到任何问题，欢迎在Issues区留言寻求帮助。

---
This is a new plugin and we have decided not to reuse the old one, so you can design and develop it according to your own understanding.

Before you begin, it is advisable to familiarize yourself briefly with the logic and naming conventions of configuration items used in the newer versions of plugin implementations, such as: [GridLine](https://github.com/antvis/G6/blob/v5/packages/g6/src/plugins/grid-line.ts).

Should any issues arise during the migration process, you are welcome to seek assistance by posting a message in the Issues section.

**Comment by hustcc** [comment]
- 之前的 demo：https://g6-next.antv.antgroup.com/zh/examples/tool/toolbar/#toolbar
- 旧代码：https://github.com/antvis/G6/blob/v5-old/packages/g6/src/stdlib/plugin/toolbar/index.ts
