### ISSUE TITLE
Contribute Tooltip Plugin

### ISSUE THREAD

**Issue by Aarebecca** [antvis/G6#5563]
### AntV Open Source Contribution Plan（可选/Optional）

- [X] 我同意将这个 Issue 参与 OSCP 计划 / I agree to participate in the OSCP plan

### Issue 类型 / Issue Type

中级任务 / Intermediate Task

### 任务介绍 / Task Description

开发 `提示框` 插件

---

Develop `Tooltip` plugin

### 参考说明 / Reference Description

请使用 [@antv/component](https://github.com/antvis/component) 提供的 Tooltip 工具进行封装

在正式开始之前，建议您简要了解新版插件实现的逻辑和配置项命名风格，例如：[GridLine](https://github.com/antvis/G6/blob/v5/packages/g6/src/plugins/grid-line.ts)。

在迁移过程中，如果遇到任何问题，欢迎在Issues区留言寻求帮助。

---
Please use the [@antv/component](https://github.com/antvis/component) tools for encapsulation provides the Tooltip

This is a new plugin and we have decided not to reuse the old one, so you can design and develop it according to your own understanding.

Before you begin, it is advisable to familiarize yourself briefly with the logic and naming conventions of configuration items used in the newer versions of plugin implementations, such as: [GridLine](https://github.com/antvis/G6/blob/v5/packages/g6/src/plugins/grid-line.ts).

Should any issues arise during the migration process, you are welcome to seek assistance by posting a message in the Issues section.

**Comment by hustcc** [comment]
@lxfu1  认领

**Comment by Aarebecca** [comment]
https://github.com/antvis/G6/pull/5573
