### ISSUE TITLE
Migrate Donut Node

### ISSUE THREAD

**Issue by Aarebecca** [antvis/G6#5566]
### AntV Open Source Contribution Plan（可选/Optional）

- [X] 我同意将这个 Issue 参与 OSCP 计划 / I agree to participate in the OSCP plan

### Issue 类型 / Issue Type

中级任务 / Intermediate Task

### 任务介绍 / Task Description

迁移`甜甜圈`节点元素 [Demo](https://g6-next.antv.antgroup.com/zh/examples/item/defaultNodes/#donut)

---

Migrate `Donut` node element [Demo](https://g6-next.antv.antgroup.com/zh/examples/item/defaultNodes/#donut)

**Comment by ai-qing-hai** [comment]
@Aarebecca  认领
