### ISSUE TITLE
G6 2.2.2绘制dom图像报错

### ISSUE THREAD

**Issue by chuncuiwuyou** [antvis/g6#557]
G6.registerNode('customHtml1', {
	draw(item){
      const group = item.getGraphicGroup();
      const html = G6.Util.createDOM('<div>HTML 节点</div>');
      return group.addShape('dom', {
        attrs: {
          x: 0,
          y: 0,
          width: 100,
          height: 24,
          html
        }
      });
    }
});
const data = {
  "nodes": [
    {
      "id": "node1",
      "x": 50,
      "y": 170,
      "shape": "customHtml1"
    },
    {
      "id": "node2",
      "x": 180,
      "y": 170,
      "shape": "customHtml1"
    },
	
    {
      "id": "node3",
      "x": 180,
      "y": 270,
	  "flagA" : '',
      "shape": "customHtml1"
    }
  ],
  "edges": [
    {
      "source": "node1",
      "id": "edge1",
      "target": "node2"
    }
  ]
};
const graph = new G6.Graph({
    container: 'mountNode',  // 容器ID
    fitView: 'cc',
    
    height: window.innerHeight
  });
  
  graph.read(data);
错误提示：
error in draw canvas, detail as: g6.js:13
TypeError: "Argument 1 of CanvasRenderingContext2D.drawImage could not be converted to any of: HTMLImageElement, SVGImageElement, HTMLCanvasElement, HTMLVideoElement, ImageBitmap."

请问是否最新版本更改了方式还是有什么其他原因。

**Comment by baizn** [comment]
建议升级到G6 3.x最新版本，2.x的没有人力在维护了。
