### ISSUE TITLE
site包  pnpm run build 报错  .ts 扩展不支持

### ISSUE THREAD

**Issue by vaynevayne** [antvis/G6#5570]
### 问题描述

<img width="1052" alt="image" src="https://github.com/antvis/G6/assets/124666577/6f580934-e77c-4a76-aa89-dd2928287b06">

### 重现链接

https://codesandbox.io/s/new)

### 重现步骤

执行 
```jsx
cd packages/site`
pnpm run build
```

### 预期行为

正常构建

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...] macos
- 网页浏览器: [Google Chrome, Safari, Firefox] 
- G6 版本: [4.5.1 ... ] 5.0.0-beta.29

**Comment by Aarebecca** [comment]
检查下 ts-node 环境

**Comment by vaynevayne** [comment]
`System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1
    Memory: 114.34 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
    `
    指这个吗?

**Comment by Aarebecca** [comment]
> `System: OS: macOS 12.0.1 CPU: (8) arm64 Apple M1 Memory: 114.34 MB / 16.00 GB Shell: 5.8 - /bin/zsh ` 指这个吗?

你执行下 `ts-node -v` 看看有没有输出

**Comment by vaynevayne** [comment]
`pnpm exec ts-node -v`  v10.9.2
`ts-node -v` 没输出

**Comment by Aarebecca** [comment]
应该是你的 `ts-node` 环境导致的，使用 `npm i ts-node -g` 安装后再尝试下

**Comment by vaynevayne** [comment]
好, 
```jsx
tsx -v   // zsh:  command not found: tsx
 pnpm exec tsx -v //  tsx v4.7.1
```
