### ISSUE TITLE
Graph实例方法，在代码里检索不到啊？

### ISSUE THREAD

**Issue by invokerzaa** [antvis/G6#5572]
### 问题描述

https://g6-next.antv.antgroup.com/apis/graph/graph文档中的Graph实例方法，在代码里检索不到啊

### 重现链接

https://g6-next.antv.antgroup.com/apis/graph/graph

### 重现步骤

1、下载gitlab最新版本代码
2、检索drawTransient

### 预期行为

能搜到相应代码

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by hustcc** [comment]
官网文档还没有匹配到最新的代码。

**Comment by Aarebecca** [comment]
可访问最新官网查看文档：https://g6-next.antv.antgroup.com/api/graph/method
