### ISSUE TITLE
[v5.beta] label 的显示行为很怪异

### ISSUE THREAD

**Issue by 724493602** [antvis/G6#5575]
### 问题描述

1. 缩放的一定程度就不显示了，即使position 是center
2. 同一缩放大小，移动位置，就不显示了，即使空间很大，没有遮挡节点
3. 能不能有参数控制，自定义常显示

### 重现链接

无

### 重现步骤

官网示例

### 预期行为

正确的显示label

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- G6 版本: [5.0.0-beta.28]

### 屏幕截图或视频（可选）

![20240320172803](https://github.com/antvis/G6/assets/25702664/3d9bd8e1-8f87-4ed3-9d35-c61767f233ef)
![20240320172842](https://github.com/antvis/G6/assets/25702664/5713fc63-11f8-4afe-b712-419c9203b529)

**Comment by hustcc** [comment]
官网的 demo 还是 beta 27 的，建议你可以 clone 项目，然后本地运行。参考[贡献文档](https://github.com/antvis/G6/blob/v5/CONTRIBUTING.md)来本地启动。
