### ISSUE TITLE
windows环境下scroll-canvas在x轴上失效

### ISSUE THREAD

**Issue by RealRio** [antvis/G6#5576]
### Describe the bug

mac设备可以正常执行，均执行在chrome下，但是windows上无法在x轴上滚动canvas。

### Your Example Website or App

https://g6.antv.antgroup.com/examples/case/graphDemos/#edgeBundling

### Steps to Reproduce the Bug or Issue

直接使用官方的实例，在modes里添加scroll-canvas即可复现此问题

### Expected behavior

期望windows能和mac下一致，实现x轴的canvas滚动

### Platform

- OS: [Windows]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Aarebecca** [comment]
Windows 中的 x 轴滚动是通过何种方式触发的，触控板还是键盘或者鼠标？
