### ISSUE TITLE
自定义节点中有多个图形，graph.on('node:mouseenter')鼠标移入事件会触发多次？

### ISSUE THREAD

**Issue by Jonathan-Rao** [antvis/G6#5582]
### 问题描述

我自定义的节点中，有多个图形，然后我监听节点的鼠标移入事件，想要触发某个图形的显示隐藏，但是鼠标移入当前node节点中的其它图形，也会触发node:mouseenter 事件，请问既然所有图形都在一个节点中，难道不是应该共享同一个node:mouseenter 事件吗？为什么每个图象都是响应鼠标移入移出事件？

### 重现链接

https://stackblitz.com/edit/vitejs-vite-jjlss1?file=src%2FApp.vue

### 重现步骤

进入页面

### 预期行为

希望可以鼠标移入node节点区域范围内 只响应一次graph.on('node:mouseenter')鼠标移入事件

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Jonathan-Rao** [comment]
发现问题了，因为第一个图象没有设置fill背景的时候，就只是一个框而已，中间是空的，所以会造成让人感觉节点内的图形都是独立的，才会触发多次事件

**Comment by hustcc** [comment]
使用 mouseover 应该可以解决。
