### ISSUE TITLE
G6文档页面comboCombined API无法访问404

### ISSUE THREAD

**Issue by lintu1** [antvis/G6#5596]
### 问题描述

G6文档页面访问comboCombined显示404，无该页面

### 重现链接

https://antv-g6.gitee.io/zh/docs/api/Items/comboProperties

### 重现步骤

1.进入https://antv-g6.gitee.io/zh/docs/api/Graph
2.在搜索栏中搜索comboCombined
3.选择comboCombined复合布局
4.显示404

### 预期行为

应该访问到comboCombined相关的API界面，实际返回404

### 平台

- 操作系统: Windows
- 网页浏览器: Google Chrome
- G6 版本: 4.8.17

### 屏幕截图或视频（可选）

![1711524287687](https://github.com/antvis/G6/assets/96677891/7b0e6852-cc0b-48b1-b853-6ecc6ef85c26)

**Comment by Aarebecca** [comment]
这是官方站点：https://g6.antv.antgroup.com/api/graph-layout/combo-combined
