### ISSUE TITLE
禁止锚点连接示例中想确定一下出现以下情况是不是bug

### ISSUE THREAD

**Issue by itsmyturn** [antvis/g6#56]
![image](https://user-images.githubusercontent.com/11573322/28907171-518dff52-784f-11e7-8b7f-e3f533dfdb94.png)
https://antv.alipay.com/g6/demo/04-editor/perventLink.html
![image](https://user-images.githubusercontent.com/11573322/28959489-3a260a92-792d-11e7-810c-5c4f9e789ee1.png)

**Comment by TomHuangCN** [comment]
可能是bug，描述一下交互，我复现一下

**Comment by itsmyturn** [comment]
从锚点边缘拉出一条线经常出现这个问题，而且这个问题是频繁出现的，多试几个不同方向的锚点

**Comment by feng5** [comment]
这个demo找不到了，删除了？
