### ISSUE TITLE
文档描述有误https://g6.antv.antgroup.com/api/tree-graph-layout/guide

### ISSUE THREAD

**Issue by lhb2631225005** [antvis/G6#5608]
### 问题描述

文档里对于layoutconfig的type属性值提供有误
不知道为什么图片我一直粘贴上传失败  所以提供链接地址
https://g6.antv.antgroup.com/api/tree-graph-layout/guide
直接ctrl+f搜索indeted  即可    indeted属性值应改为indented
(indeted会直接报错layoutConfig没有这个type，而且左侧目录栏也是indented)

### 重现链接

https://g6.antv.antgroup.com/api/tree-graph-layout/guide

### 重现步骤

https://g6.antv.antgroup.com/api/tree-graph-layout/guide
直接ctrl+f搜索indeted  即可    indeted属性值应改为indented
(indeted会直接报错layoutConfig没有这个type，而且左侧目录栏也是indented)

### 预期行为

https://g6.antv.antgroup.com/api/tree-graph-layout/guide
直接ctrl+f搜索indeted  即可    indeted属性值应改为indented
(indeted会直接报错layoutConfig没有这个type，而且左侧目录栏也是indented)

### 平台

文档错误

**Comment by hustcc** [comment]
这是个拼写错误，来个 pr 直接解决掉吧。

**Comment by lhb2631225005** [comment]
不好意思  我不清楚文档的代码仓在哪里  我fork了G6-5的代码仓  全局搜索没有indeted   抱歉

**Comment by hustcc** [comment]
没事，一回生二回熟。代码在 master 分支。

**Comment by lhb2631225005** [comment]
呼 终于弄好了哥  感谢您给我机会   在编程上我只是个小白  哈哈  没想到有一天还能给开源代码提pr

**Comment by hustcc** [comment]
> 呼 终于弄好了哥  感谢您给我机会   在编程上我只是个小白  哈哈  没想到有一天还能给开源代码提pr

已经合并了，后面有遇到问题也可以自己尝试下，逐步深入。

**Comment by lhb2631225005** [comment]
好的哥
