### ISSUE TITLE
分组连线

### ISSUE THREAD

**Issue by dongongfeiyu** [antvis/g6#561]
您好，2.x有没有分组手动连线的例子？

**Comment by yuanchuan** [comment]
官方文档里好像没有分组连线的例子。以下是我有限使用经验：

1. 尽量使用自定义 `node`,`edge` 和 `group`，方便改写
2. 在自定义分组(group) 当中添加一个 `rect` shape，可以设置背景和边框、圆角等
3. 连线与节点是一样的，可以设置 `anchors`。把分组的 `id` 放在 edge 的 `target`  或者 `source` 属性里就是建立连接

**Comment by dongongfeiyu** [comment]
您好，有demo可以参考下吗？谢谢

**Comment by mengayng** [comment]
同要求，要一个手动连线的例子

**Comment by mengayng** [comment]
@yuanchuan 想问下怎么使锚点显示和隐藏啊？研究了好久锚点就是无法显示。

**Comment by yuanchuan** [comment]
默认提供的 node/group 是没有锚点的形状，需要自己自定义实现，然后通过一个内部变量的状态来显示/隐藏

**Comment by mengayng** [comment]
@yuanchuan 意思是用自定义节点当作锚点实现吗？

**Comment by yuanchuan** [comment]
@mengayng 看最近的代码提交，应该更快就会支持锚点了。可以关注一下 https://github.com/antvis/g6/pull/577

**Comment by mengayng** [comment]
@yuanchuan ，好的，谢谢了，我会关注的。

**Comment by baizn** [comment]
@mengayng @dongongfeiyu 手动连线的Demo请参考[这里](https://www.yuque.com/antv/g6/interaction)，2.x的没在维护了，建议升级到3.x。

@yuanchuan 锚点是否是否加到G6中，目前意见还没有统一，后续可以开个issue征求下大家的意见。
