### ISSUE TITLE
能否像X6，来一组泳道图的demo

### ISSUE THREAD

**Issue by weijiatan456** [antvis/G6#5615]
### 问题描述

把demo写到图表示例

### 重现链接

https://x6.antv.antgroup.com/examples/showcase/practices/#swimlane

### 重现步骤

打开链接即可看到

### 预期行为

X6在节点非常多，可能会卡顿，所以想G6应该能够解决

### 平台

任意浏览器

**Comment by Aarebecca** [comment]
泳道图并非 G6 的常见场景，如果有兴趣，欢迎提 PR 恭喜
