### ISSUE TITLE
线和线交叉能实现圆弧效果吗

### ISSUE THREAD

**Issue by Wangjing991** [antvis/G6#5621]
### 问题描述

多条线交叉能实现圆弧效果吗？ru如下图
![微信截图_20240407161849](https://github.com/antvis/G6/assets/19301714/74558fdf-564b-4602-b643-38df54465278)

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Aarebecca** [comment]
暂不支持，要实现需要自定义边
