### ISSUE TITLE
官网的自定义边，如果节点是垂直方向，自定义连接线路径有错误

### ISSUE THREAD

**Issue by Shen120** [antvis/G6#5622]
### 问题描述

![image](https://github.com/antvis/G6/assets/33613409/c34784df-a003-43d8-87da-0988163e7837)
图中只是处理了横向连接线的路径，但是垂直走向就是错误的；正常情况应该是这样的：
![image](https://github.com/antvis/G6/assets/33613409/497ca40e-a417-4723-a213-ed97059d87d9)
；请问如何计算？

### 重现链接

https://g6.antv.antgroup.com/zh/examples/item/customEdge/#customPolyline

### 重现步骤

打开页面拖动节点，进行垂直摆放

### 预期行为

正确的路径走向

### 平台

- 操作系统: Windows 10
- 网页浏览器: Chrome
- G6 版本: 4.8.21

**Comment by Aarebecca** [comment]
<img width="695" alt="image" src="https://github.com/antvis/G6/assets/25787943/8c1f2e83-5afc-4e90-b9b7-b25c96aa5e44">

看着没什么问题呢

**Comment by Shen120** [comment]
> <img alt="image" width="695" src="https://private-user-images.githubusercontent.com/25787943/320270171-8c1f2e83-5afc-4e90-b9b7-b25c96aa5e44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NjEzODAsIm5iZiI6MTcxMjU2MTA4MCwicGF0aCI6Ii8yNTc4Nzk0My8zMjAyNzAxNzEtOGMxZjJlODMtNWFmYy00ZTkwLWI5YjctYjI1Yzk2YWE1ZTQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDA3MjQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmMTMzZGIwY2EyMTM3MzRlNWRiMjg3MTkwZWE3MzI0OTFhODQ2ODEyZTM1YTUyZjg1ZmVjZmUzMTVkM2RmMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tpsBEQuMiSSkauRUsGJURuzgr-QMGHLReDVqOIGVVLY">
> 看着没什么问题呢
> 
> ```ts
>   getPath(points) {
>       const { x: x1, y: y1 } = points[0];
>       const { x: x2, y: y2 } = points[1];
>       const [width, height] = [x2 - x1, y2 - y1];
>       return [
>         ['M', x1, y1],
>         ['L', x1, y1 + height / 2],
>         ['L', x2, y1 + height / 2],
>         ['L', x2, y2],
>       ];
>     }
> ```

能否实现自动变化路径呢，以适配各种方向的节点，搞不明白这

**Comment by Aarebecca** [comment]
G6 中 Path 遵守 SVG [Path](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/d) 规范，不过使用的是数组形式表达。
自动寻径能力仅 5.x 版本可用，[Demo](https://g6-next.antv.antgroup.com/examples/item/defaultEdges/#polyline3)
