### ISSUE TITLE
[v5:5.0.0-beta.29] extend对象整哪去了

### ISSUE THREAD

**Issue by AnqingYou-GitHub** [antvis/G6#5633]
### 问题描述

beta.28之后的版本extend对象哪去了

### 重现链接

无

### 重现步骤

extend对象功能整合到哪里去了

### 预期行为

extend功能不见了

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [5.0.0-beta.29 ]

### 屏幕截图或视频（可选）

<img width="591" alt="image" src="https://github.com/antvis/G6/assets/83051587/9f691493-3209-45d2-80f8-4f0a9e60d08a">

**Comment by zzjjbbaa** [comment]
bata版本慎用生产环境哦，28后的版本变化有点大

**Comment by hustcc** [comment]
去掉了，这个api设计，让使用者变得更麻烦了。
