### ISSUE TITLE
[5.0.0-beta.32]如何渲染自定义节点

### ISSUE THREAD

**Issue by cidre07** [antvis/G6#5634]
### 问题描述

[5.0.0-beta.32]代码和g5官网示例不符，drawOtherShapes方法消失了，base-node.ts的render方法里面只有draw keyshape、badgeshapes、portshapes、haloshapes，请问如果添加自定义形状呢？复写render方法也比较麻烦，icon、label这些形状都没有export。

### 重现链接

https://codesandbox.io/p/sandbox/competent-mopsa-mn2l3g

### 重现步骤

https://g6-next.antv.antgroup.com/examples/item/customNode/#card 切到最新版g5跑不通

### 预期行为

希望提供drawOtherShapes方法

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Aarebecca** [comment]
覆写 `render` 是可以的

```ts
{
  render(attributes, container){
    super.render(attributes, container);
    this.drawMyShapes(attributes, container);
  }

  // 自定义的绘制函数，命名自定
  drawMyShapes(attributes, container) {
      this.upsert(...);
  }
}

```

**Comment by cidre07** [comment]
> 覆写 `render` 是可以的
> 
> ```ts
> {
>   render(attributes, container){
>     super.render(attributes, container);
>     this.drawMyShapes(attributes, container);
>   }
> 
>   // 自定义的绘制函数，命名自定
>   drawMyShapes(attributes, container) {
>       this.upsert(...);
>   }
> }
> ```
你好，
base-node.ts的render方法里面渲染icon和label的方法用到的Icon和Label都没有export，请问该怎么复写呢？

`
    this.upsert('icon', Icon, this.getIconStyle(attributes), container);
`
`
    this.upsert('label', Label, this.getLabelStyle(attributes), container);
`

**Comment by cidre07** [comment]
非常感谢！
