### ISSUE TITLE
Migrate Timebar Plugin

### ISSUE THREAD

**Issue by Aarebecca** [antvis/G6#5640]
### AntV Open Source Contribution Plan（可选/Optional）

- [X] 我同意将这个 Issue 参与 OSCP 计划 / I agree to participate in the OSCP plan

### Issue 类型 / Issue Type

None

### 任务介绍 / Task Description

迁移 `Timebar` 插件 [Demo](https://g6-next.antv.antgroup.com/examples/tool/timebar/#timebar-time)

---

Migrate `Timebar` Plugin [Demo](https://g6-next.antv.antgroup.com/examples/tool/timebar/#timebar-time)

### 参考说明 / Reference Description

参考代码/Reference Code：https://github.com/antvis/G6/pull/4899

**Comment by ai-qing-hai** [comment]
认领
