### ISSUE TITLE
https://unpkg.com/@antv/layout@latest/dist/layout.min.js. G6源码中有用到这个cdn，这个cdn现在资源被移除了，导致线上项目崩溃

### ISSUE THREAD

**Issue by cqg001** [antvis/G6#5642]
### Describe the bug

https://unpkg.com/@antv/layout@latest/dist/layout.min.js
https://unpkg.com/@antv/layout@latest/dist/layout.min.js. G6源码中有用到这个cdn，这个cdn现在资源被移除了，导致线上项目崩溃

### Your Example Website or App

https://unpkg.com/@antv/layout@latest/dist/layout.min.js. G6源码中有用到这个cdn，这个cdn现在资源被移除了，导致线上项目崩溃

### Steps to Reproduce the Bug or Issue

https://unpkg.com/@antv/layout@latest/dist/layout.min.js. G6源码中有用到这个cdn，这个cdn现在资源被移除了，导致线上项目崩溃

### Expected behavior

https://unpkg.com/@antv/layout@latest/dist/layout.min.js. G6源码中有用到这个cdn，这个cdn现在资源被移除了，导致线上项目崩溃

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Aarebecca** [comment]
看起来是 unpkg 服务器的问题，尝试使用 jsdelivr : https://cdn.jsdelivr.net/npm/@antv/layout@latest/dist/layout.min.js

**Comment by haoqi0818** [comment]
> 看起来是 unpkg 服务器的问题，尝试使用:
> 
> * jsdelivr : https://cdn.jsdelivr.net/npm/@antv/layout@latest/dist/layout.min.js
> * npmmirror: https://registry.npmmirror.com/@antv/layout/latest/files/dist/layout.min.js

并不是unpkg服务问题，而是@antv/layout这个包，在0.x的版本是存在layout.min.js文件的，但是latest版本1.x目前文件被移除了。
所以可以配置layout的workerScriptURL属性为：
* https://unpkg.com/@antv/layout@0.x/dist/layout.min.js
* jsdelivr : https://cdn.jsdelivr.net/npm/@antv/layout@0.x/dist/layout.min.js
* npmmirror: https://registry.npmmirror.com/@antv/layout/0.x/files/dist/layout.min.js

也可以改成使用本地worker：
```
new G6.Graph({
  ...,
  layout: {
    ...
    workerScriptURL: new URL('@antv/layout/dist/layout.min.js', import.meta.url).toString(),
  }
});
```
