### ISSUE TITLE
[v5] drag-element 对于关联的edge（polyline）端点坐标计算异常

### ISSUE THREAD

**Issue by zzjjbbaa** [antvis/G6#5644]
### Describe the bug

edge已经配置了style.targetPort和style.sourcePort
这是正常的，终点应该是bottom-center port
![image](https://github.com/antvis/G6/assets/54572770/28b36c34-60f7-40c9-a43e-859d6c1481ff)
当targetNode移动到sourceNode下方后，就变成了这样
![image](https://github.com/antvis/G6/assets/54572770/6f30f9dd-7b9d-46e0-8a2c-f1a6a8b097b9)

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

无

### Expected behavior

无

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by yvonneyx** [comment]
看截图是自动吸附到距离更近的连接桩了，建议先检查一下连接桩设置是否正确。如果还是存在问题，请提供一个在线示例链接，方便排查定位问题~

**Comment by zzjjbbaa** [comment]
> 看截图是自动吸附到距离更近的连接桩了，建议先检查一下连接桩设置是否正确。如果还是存在问题，请提供一个在线示例链接，方便排查定位问题~

不好意思，在线没问题，没复现出来；我的估计问题出在我自定义node时，复写的getPortXY方法有问题，先关闭吧
