### ISSUE TITLE
[v5] 事件监听失败 ```AFTER_ELEMENT_TRANSLATE```

### ISSUE THREAD

**Issue by zzjjbbaa** [antvis/G6#5687]
### Describe the bug

![image](https://github.com/antvis/G6/assets/54572770/e40825c7-dc9f-462a-b9d4-8301e3d249b6)

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

监听不响应

### Expected behavior

无

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

无

**Comment by Aarebecca** [comment]
这个事件即将被移除，可以通过监听 `AFTER_ELEMENT_UPDATE` 中元素数据中坐标值是否发生变化来判断元素是否平移

**Comment by zzjjbbaa** [comment]
> 这个事件即将被移除，可以通过监听 `AFTER_ELEMENT_UPDATE` 中元素数据中坐标值是否发生变化来判断元素是否平移
> 
> 不过平移过程中这个事件会频繁触发，所以需要进行防抖处理

当前```AFTER_ELEMENT_UPDATE```事件的回调参数中只有更新后的data，而没有更新前的data，怎么判断呢？

**Comment by zzjjbbaa** [comment]
> > 这个事件即将被移除，可以通过监听 `AFTER_ELEMENT_UPDATE` 中元素数据中坐标值是否发生变化来判断元素是否平移
> > 不过平移过程中这个事件会频繁触发，所以需要进行防抖处理
> 
> 当前`AFTER_ELEMENT_UPDATE`事件的回调参数中只有更新后的data，而没有更新前的data，怎么判断呢？

结合```BEFORE_ELEMENT_UPDATE```来判断？
