### ISSUE TITLE
请问如何设置整个画布的背景颜色？

### ISSUE THREAD

**Issue by lth707** [antvis/g6#569]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by elaine1234** [comment]
可以在graph的container上加`background-color`

**Comment by warryy** [comment]
这样的话, 我下载canvas图片还是没有背景色

**Comment by warryy** [comment]
> 可以在graph的container上加`background-color`
这样的话, 我下载canvas图片还是没有背景色

**Comment by warryy** [comment]
> 可以在graph的container上加`background-color`

这样的话, 我下载canvas图片还是没有背景色

**Comment by Yanyan-Wang** [comment]
> > 可以在graph的container上加`background-color`
> 
> 这样的话, 我下载canvas图片还是没有背景色

下载的 API 可以配置画布颜色
http://g6.antv.antgroup.com/api/graphFunc/download#graphdownloadfullimagename-type-imageconfig
