### ISSUE TITLE
g6怎么实现锚点的显现和隐藏啊

### ISSUE THREAD

**Issue by mengayng** [antvis/g6#570]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by guozhaolong** [comment]
需要自己添加锚点图形，然后通过node:mouseenter等事件去控制显示和隐藏，我也在做这块，最后发现必须要自定义一个锚点的Item才能在Behavior中监听到anchor:dragenter这种事件

**Comment by baizn** [comment]
@mengayng 目前可以@guozhaolong提供的思路来实现。
@guozhaolong  是的，目前G6 3.x没有内置锚点，需要通过Item扩展，至于G6是否默认就提供锚点，还没有达成统一意见，大家有其他想法可以开个issue一起讨论。

**Comment by chens97** [comment]
get
