### ISSUE TITLE
G6 V5 Use React

### ISSUE THREAD

**Issue by RackweLLizm** [antvis/G6#5700]
### 问题描述

I'm trying to use React 18 and G6 V5 together. I found an old example.
https://stackblitz.com/edit/react-ts-b4iajh?file=index.tsx
I wrote my own codes similar to this. But I couldn't get it to work. I would be glad if you could help me.

```
import { Graph } from '@antv/g6';
import React, { useEffect } from 'react'
type GraphData = {
 nodes: NodeModel[];
 edges: EdgeModel[];
};
type NodeModel = {
 id: string;
 data: {
 type?: string; // node type, e.g. circle-node, rect-node
 x?:number;
 y?: number;
 z?: number;
 parentId?: string; // parent combo's id
 label?: string; //label content
 anchorPoints?: number[][];
 badges?: {
 type: 'icon' | 'text';
 text:string;
 position: string;
 }[];
 icon?: {
 type: 'icon' | 'text';
 text?: string;
 img?: string;
 };
 [key: string]: unknown; // other properties
 };
};
type EdgeModel = {
 id: string;
 source: string;
 target: string;
 data: {
 type?: string; // edge type, e.g. line-edge
 label?: string; //label content
 sourceAnchor?: number;
 targetAnchor?: number;
 icon?: {
 type: 'icon' | 'text';
 text?: string;
 img?: string;
 };
 badge?: {
 type: 'icon' | 'text';
 text:string;
 };
 [key: string]: unknown; // other properties
 };
};
const G6V5 = () => {
 const ref = React.useRef(null);
 let graph = null;
 const data: GraphData = {
 nodes: [{
 id: "1",
 data: {
 label: "Test 1 Node",

 }
 },
 {
 id: "2",
 data: {
 label: "Test 2 Node",

 }
 }],
 edges: [{
 id: "1",
 source: "1",
 target: "2",
 data: {
 label: "Edge Test"
 }

 }]
 };
 useEffect(() => {
 if (!graph) {
 const graph = new Graph({
 data: data,
 container: ref.current as any,
 });
 graph.on('node:click', (e) => {
 // the clicked item's type and id
 console.log("Node Click", e);
 });
 // graph.render();
 }
 console.log("graph",graph);

 }, []);

 return <div ref={ref}></div>;
}

export default G6V5
```

### 重现链接

https://stackblitz.com/edit/react-ts-b4iajh?file=index.tsx

### 重现步骤

.

### 预期行为

I'm getting graph null error

### 平台

- 操作系统: [Windows.]
- 网页浏览器: [Google Chrome]
- G6 版本: [V5. ]

**Comment by RackweLLizm** [comment]
@Aarebecca 

https://g6-next.antv.antgroup.com/en/examples/feature/features/#moreDataWebGL
When I try to implement the example in the link
import { Graph, Extensions, extend } from '@antv/g6';
'"@antv/g6"' has no exported member named 'Extensions'. Did you mean 'getExtensions'?ts(2724)
Module '"@antv/g6"' has no exported member 'extend'.ts(2305)

I'm getting the error. You said above that the examples will be updated. Do I have to wait a bit or is it my fault?

Package.Json:
 "@antv/g6": "^5.0.0-beta.35",

**Comment by hustcc** [comment]
You can use G6 in react with this package. https://www.npmjs.com/package/react-g6

**Comment by Rey-Wang** [comment]
@hustcc the repository was missed. Is there a page where we can follow the process of the documentation updates?
