### ISSUE TITLE
请问可以动态切换显示grid吗？

### ISSUE THREAD

**Issue by 1234567845246** [antvis/G6#5701]
### 问题描述

你好，我现在有一个需求就是可以自己配置grid(new Grid({follow:true}))的显隐，但我看这个对象好像没有这个的API，我现在的做法是直接销毁，重新绘制一棵树

### 重现链接

...

### 重现步骤

正常的生成Grid和TreeGraph,能够切换网格

### 预期行为

希望能动态切换grid

### 平台

- 操作系统: [Windows,]
- 网页浏览器: [electron]
- G6 版本: [4.5.1 ... ]

**Comment by Aarebecca** [comment]
使用 G6 5.0 版本支持该特性
