### ISSUE TITLE
V5 Quick start demo example doesn't work

### ISSUE THREAD

**Issue by xnd1124** [antvis/G6#5705]
### Describe the bug

Result of rendering HTML file from demo example doesn't  render graph 

### Your Example Website or App

https://g6-next.antv.antgroup.com/en/manual/tutorial/quick-start

### Steps to Reproduce the Bug or Issue

1. Go to https://g6-next.antv.antgroup.com/en/manual/tutorial/quick-start
2. Copy code from "G6 in vanilla HTML" in empty HTML file
3. Replace "https://gw.alipayobjects.com/os/lib/antv/g6/5.0.0-beta.28/dist/g6.min.js" on "https://gw.alipayobjects.com/os/lib/antv/g6/5.0.0-beta.35/dist/g6.min.js"
4. Open HTML file in browser
There is error "Graph is not defined
![image](https://github.com/antvis/G6/assets/6578710/47eac6ed-6bce-4476-8cd5-d7861ebf942e)

Ok.
5.Replace "new Graph"  on "new G6.Graph"
6. Reopen HTML file in browser
No errors, but no result
![image](https://github.com/antvis/G6/assets/6578710/05847311-06b6-4a6b-93f1-68384b0e590c)

### Expected behavior

As a user, I expect a rendered page with a graph

### Platform

- OS:  Windows 10
- Browser: Chrome 124.0.6367.119
- Version: 5.0.0-beta.35

**Comment by Aarebecca** [comment]
The current official website provides incorrect examples, so please do not refer to the sample code provided there. We will prioritize updating the documentation and examples as soon as possible within this week. Thank you for your understanding and patience.

After the beta.28 version, G6 underwent a significant change. You can now use it in the following way:

```ts
import { Graph } from '@antv/g6';

const graph = new Graph({
  container: 'container',
  width: 400,
  height: 400,
  data: {
    nodes: [{ id: 'node-1' }, { id: 'node-2' }],
    edges: [{ source: 'node-1', target: 'node-2' }],
  },
  behaviors: ['zoom-canvas', 'drag-canvas', 'drag-element'],
  layout: {
    type: 'grid',
  },
});

graph.render();
```

**Comment by Aarebecca** [comment]
Here is an [online demo](https://codesandbox.io/p/sandbox/using-g6-from-npm-d9spnr) of CodeSandbox that you can refer to.

**Comment by xnd1124** [comment]
Thank you for the example, will wait for the documentation update
