### ISSUE TITLE
希望 tooltip 增加配置延迟显示功能

### ISSUE THREAD

**Issue by Anan-GitHub** [antvis/G6#5709]
### 问题描述

tooltip 展示的数据需要从后端获取 不想鼠标一滑动就获取展示 tooltip ，当鼠标不动的一段时间后展示tooltip。希望 tooltip 增加配置延迟显示功能

### 重现链接

 无

### 重现步骤

  无

### 预期行为

  无

### 平台

无

**Comment by hustcc** [comment]
可以参考 Tooltip 的实现，实现一个自己业务需要的 Tooltip，和内置的区别应该在于事件触发的逻辑。
