### ISSUE TITLE
CompactBox 紧凑树TB布局，连接线不居中对齐

### ISSUE THREAD

**Issue by Jcode-11** [antvis/G6#5714]
### 问题描述

多个子节点连接父节点的时候，用了四个点组成的线去连接，理想状态是居中对齐，但是表现的效果是没有对齐的状态
![image](https://github.com/antvis/G6/assets/97071751/d53a522f-50d4-4065-820d-a9c95600bf27)

### 重现链接

https://codesandbox.io/p/sandbox/smoosh-bush-4k3sn8?file=%2Findex.js%3A15%2C9

### 重现步骤

增加或者减少子节点节点的数量，可以更为直观的发现问题

### 预期行为

怎么实现让他们自动对齐？

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![image](https://github.com/antvis/G6/assets/97071751/2b354d88-b98a-42de-b399-db0ac0b7814a)

**Comment by keminu** [comment]
无解
