### ISSUE TITLE
使用g6编辑器做好的图。能导出为页面放在网页上显示吗？

### ISSUE THREAD

**Issue by tgy3300** [antvis/g6#572]
如题，使用g6编辑器做好的图。能导出为页面放在网页上显示吗？

**Comment by baizn** [comment]
只能到处png图片或数据，不支持导出成页面，但你可以通过ifream将做好的图引入到其他网页中使用。

**Comment by tdida** [comment]
@baizn 请教下如果把 canvas 内全部内容导出成 png，使用canvas 的 toDataURL 只能导出可视区域的
