### ISSUE TITLE
create-edge交互

### ISSUE THREAD

**Issue by fanyanke** [antvis/G6#5721]
### 问题描述

node:click交互可以通过touchstart等事件间接处理，但是这个内置的create-edge看了源码也是监听了click事件，导致移动设备不触发，有什么解决方案吗？

### 重现链接

https://g6.antv.antgroup.com/examples/interaction/setMode#setMode

### 重现步骤

重现链接是用的自定义交互实现创建边，pc点击节点正常展示边线且可随鼠标移动，切换到移动设备后点击节点边线不出现但可正常连接边线。
我使用的内置的create-edge方式，移动设备点击节点不出现边线并且不能正常连接

### 预期行为

移动端与pc端都可点击节点出现边线并跟随手指或鼠标移动

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

### 屏幕截图或视频（可选）

![98f8b72110464f2ab88c73014cb0418](https://github.com/antvis/G6/assets/109951194/b8dfc14e-51b8-47b9-ad68-437b07c92849)

![c582dd297fdbcfedc55bdafa5f4d2d9](https://github.com/antvis/G6/assets/109951194/8a8334d9-d778-40d7-a09a-91bb016cc039)

**Comment by Aarebecca** [comment]
因为边实际上的基于当前指针 pointermove 事件触发更新，在移动端上并不会触发这个事件，也没有针对移动端的适配工作。所以建议考虑自定义实现该交互
