### ISSUE TITLE
文档底部漂移

### ISSUE THREAD

**Issue by direwolf512** [antvis/G6#5730]
### 问题描述

当右侧导航超长，滚动到底部是，footer和导航重叠

### 重现链接

https://g6.antv.antgroup.com/api/graph

### 重现步骤

进入[图配置 G6.Graph(cfg)](https://g6.antv.antgroup.com/api/graph)；
滚动到底部。

### 预期行为

footer和导航分离显示

### 平台

- 操作系统: macOS
- 网页浏览器: Google Chrome
- G6 版本: [4.8.21]

**Comment by direwolf512** [comment]
![bug](https://github.com/antvis/G6/assets/28618574/f1fd1369-02af-4bb9-941d-ed0230044481)

**Comment by Aarebecca** [comment]
新版 G6 5.0 官网已解决该问题，旧站点暂不会更新
