### ISSUE TITLE
V5 beta 官网文档中react 沙箱在线示例运行报错

### ISSUE THREAD

**Issue by podf** [antvis/G6#5732]
### 问题描述

官网文档教程-快速开始中react 沙箱在线示例运行报错

https://g6-next.antv.antgroup.com/manual/tutorial/quick-start

### 重现链接

https://codesandbox.io/p/sandbox/g6-5-0-demo-hqjs9w?file=%2Fsrc%2FApp.js%3A27%2C1

### 重现步骤

1. 进入官网-快速开始， 
2. 打开“在 React 中使用”-在线DEMO

### 预期行为

正常运行

### 平台

- 操作系统: [macOS,]
- 网页浏览器: [Google Chrome]
- G6 版本: [5.0.0-beta.27 ]

### 屏幕截图或视频（可选）

![截屏2024-05-13 15 52 17](https://github.com/antvis/G6/assets/31005064/baa51eee-b4c8-4a6e-8081-c5182037f0f9)

**Comment by Aarebecca** [comment]
请访问最新的示例：https://g6-next.antv.antgroup.com/manual/getting-started/integration/react
