### ISSUE TITLE
 官网实例代码不可用

### ISSUE THREAD

**Issue by AntarcticPresident** [antvis/G6#5739]
### 问题描述

https://g6.antv.antgroup.com/examples
你们确定这里面的例子都能用吗？
右面页面是空的

### 重现链接

https://codesandbox.io/p/sandbox/cocky-haze-hlvu1u?file=%2Findex.html%3A1%2C23

### 重现步骤

1、进入页面

### 预期行为

我期望看到图，但实际上是空的

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome]
- G6 版本: [官网上的]

### 屏幕截图或视频（可选）

![image](https://github.com/antvis/G6/assets/12134408/b50bd2e4-e213-484b-90f6-bc7275a2f9c8)

**Comment by Aarebecca** [comment]
手动设置下容器宽高
<img width="1233" alt="image" src="https://github.com/antvis/G6/assets/25787943/9b29379a-a584-4041-927e-b5786007a178">
