### ISSUE TITLE
Tree 如何鼠标滚轮放大缩小，鼠标左键拖动

### ISSUE THREAD

**Issue by aBlackCatAndDog** [antvis/g6#575]
* **G6 Version**: ^2.1.1-beta
* **Platform**: Windows Chrome
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

使用 antv/g6 做了一个树形层级图，图中数据节点太多了，自动缩放，图就变的很小，无法看清楚，怎么能让这个树图基于鼠标滚轮放大缩小，鼠标左键拖动呢？

**Comment by elaine1234** [comment]
请使用3.0版本， 文档可见：https://www.yuque.com/antv/g6/treegraph
实例化 graph 时定义行为`drag-canvas`和`zoom-canvas`
