### ISSUE TITLE
graph disappers ( "@antv/g6": "^4.8.5",)

### ISSUE THREAD

**Issue by eaynait** [antvis/G6#5753]
### Describe the bug

In Chrome, switching tabs within the same window causes the graph to disappear (it does not happen when switching between different windows). However, the graph reappears when any action is taken, such as clicking on a node or other buttons on the page. Meanwhile, This bug does not occur in Safari.

### Your Example Website or App

//

### Steps to Reproduce the Bug or Issue

//

### Expected behavior

//

### Platform

- OS: [macOS, Windows, Linux]
- Browser: [Chrome, Safari]

**Comment by eaynait** [comment]
> https://issues.chromium.org/issues/328755781
it seems to be a common issue caused by chrome, maybe G6 can do something to fix it.

**Comment by hustcc** [comment]
@eaynait May we should waiting for Google to fix, or implement additional handling outside of G6 in the code.
