### ISSUE TITLE
【v5】节点/边/组合如何获取元素数据

### ISSUE THREAD

**Issue by zhouyuyong** [antvis/G6#5767]
### Describe the bug

当点击节点是希望获取到此节点的数据，该如何获取，看了文档也打印了分析了event，没有找到获取的方法，只能获取到节点ID，通过ID确实可以通过遍历获取到节点数据，感觉不太优雅，是否有其他方法

### Your Example Website or App

无

### Steps to Reproduce the Bug or Issue

graph.on(`node:${NodeEvent.CLICK}`, (event) => {
  const { target, originalTarget } = event;
  console.log(event)
});

### Expected behavior

节点数据：{id:"test",data:{name:"test",type:"some"}}

点击节点、边、组合时可以获取元素数据

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [5.0.37]

**Comment by Aarebecca** [comment]
可以使用 [getNodeData](https://g6-next.antv.antgroup.com/api/graph/method#graphgetnodedataid) / [getEdgeData](https://g6-next.antv.antgroup.com/api/graph/method#graphgetedgedataid) / [getComboData](https://g6-next.antv.antgroup.com/api/graph/method#graphgetcombodata) API 获取数据

例如 `getNodeData('node-1')` 即可返回 ID 为 `node-1` 的数据，如果要获取多个节点，可以传入数组形式：`getNodeData(['node-1', 'node-2'])` 即返回 ID 为 `node-1` `node-2` 的数据数组

**Comment by zhouyuyong** [comment]
> 可以使用 [getNodeData](https://g6-next.antv.antgroup.com/api/graph/method#graphgetnodedataid) / [getEdgeData](https://g6-next.antv.antgroup.com/api/graph/method#graphgetedgedataid) / [getComboData](https://g6-next.antv.antgroup.com/api/graph/method#graphgetcombodata) API 获取数据
> 
> 例如 `getNodeData('node-1')` 即可返回 ID 为 `node-1` 的数据，如果要获取多个节点，可以传入数组形式：`getNodeData(['node-1', 'node-2'])` 即返回 ID 为 `node-1` `node-2` 的数据数组

可以获取到了，谢谢
