### ISSUE TITLE
【V5】Contextmenu插件点击菜单无响应

### ISSUE THREAD

**Issue by zhouyuyong** [antvis/G6#5769]
### Describe the bug

![image](https://github.com/antvis/G6/assets/7124402/b6b5ed5e-7342-45dc-b395-b3fe56a9d15a)
如图点击菜单项无反应

本地开发环境一样点击菜单项无反应

### Your Example Website or App

https://g6-next.antv.antgroup.com/api/plugins/contextmenu

### Steps to Reproduce the Bug or Issue

    {
      type: 'contextmenu',
      trigger: 'contextmenu', // 'click' or 'contextmenu'
      onClick: (v) => {
        alert('You have clicked the「' + v + '」item');
      },
      getItems: () => {
        return [
          { name: '展开一度关系', value: 'spread' },
          { name: '查看详情', value: 'detail' },
        ];
      },
      enable: (e) => e.targetType === 'node',
    },

### Expected behavior

修复此问题

### Platform

- OS: [ macOS]
- Browser: [Chrome]
- Version: [5.0.37]

**Comment by zhouyuyong** [comment]
![image](https://github.com/antvis/G6/assets/7124402/b8f17500-3ca3-4206-b506-eb0180b1e1de)
在画布上点击也能显示菜单

https://g6-next.antv.antgroup.com/examples/plugin/contextMenu/#basic
这个示例正常

**Comment by zhouyuyong** [comment]
![image](https://github.com/antvis/G6/assets/7124402/227c0921-2f53-4c43-8c06-96399d05b747)
本地意识这样，且点击菜单项无任何响应，控制台也未报错

**Comment by zhouyuyong** [comment]
> ![image](https://private-user-images.githubusercontent.com/7124402/333520079-b8f17500-3ca3-4206-b506-eb0180b1e1de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3ODY5MDEsIm5iZiI6MTcxNjc4NjYwMSwicGF0aCI6Ii83MTI0NDAyLzMzMzUyMDA3OS1iOGYxNzUwMC0zY2EzLTQyMDYtYjUwNi1lYjAxODBiMWUxZGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjdUMDUxMDAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzNjZTY5MGFkM2NlMjQxYTdhZDc0YjE1YjdkZjIxZDA4MWYwZTcxOWUwYTYyMDYzZjVhNmM3ZmI3ZGJmOGRhMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.iofZ8C4aL_mFyUprQS6IIW6nLdyWSVTaeKQNttSk9vU) 在画布上点击也能显示菜单
> 
> https://g6-next.antv.antgroup.com/examples/plugin/contextMenu/#basic 这个示例正常

在画布上点击也出来菜单的问题是因为调试时把enable设置为true了，这个问题忽略

**Comment by Aarebecca** [comment]
你好，该问题会尽快修复

**Comment by zhouyuyong** [comment]
补充：此问题是在vue3中发生的，经过反复试验发现在布局组件中添加了事件修饰符.stop ,导致click事件无法传递到g6，目前将.stop事件修饰符去掉问题解决
