### ISSUE TITLE
antvis / G6 v5.0无法配置label样式

### ISSUE THREAD

**Issue by whl1207** [antvis/G6#5773]
### 问题描述

antvis / G6 v5.0无法配置label样式

### 重现链接

无

### 重现步骤

antvis / G6 v5.0无法配置label样式，api中也查不到

### 预期行为

antvis / G6 v5.0配置label样式

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [5.0 ]

**Comment by yvonneyx** [comment]
5.0 中元素样式配置已拍平，直接设置 label{TextStyleProps} 和 labelBackground{RectStyleProps} 就可以啦~ api 文档可以查看 https://g6-next.antv.antgroup.com/api/elements/nodes/base-node#prefixlabel-nodelabelstyleprops
