### ISSUE TITLE
地铁范例无法运行

### ISSUE THREAD

**Issue by chaoji90** [antvis/G6#5777]
### 问题描述

请问[地铁范例](https://g6-v3-2.antv.vision/zh/examples/case/metroLines)，在当前环境下无法运行是因为什么问题？是版本问题么？当前运行结果如下：
![image](https://github.com/antvis/G6/assets/50789276/aafdb7be-c5fd-4deb-895d-3e202e8b749a)

### 重现链接

https://codesandbox.io/p/sandbox/charming-leaf-kpm55u

### 重现步骤

直接在上述连接的右侧面板即可看到运行结果，这个结果与在我机器上跑得结果一样

### 预期行为

![image](https://github.com/antvis/G6/assets/50789276/91d340a4-f464-4a2c-ae48-3eba9de1227e)

https://g6-v3-2.antv.vision/zh/examples/case/metroLines

### 平台

- 操作系统: [Linux]
- 网页浏览器: [Chrome,
- G6 版本: [4.5.1 ]

### 屏幕截图或视频（可选）

![image](https://github.com/antvis/G6/assets/50789276/1dbaeef1-3656-4817-9a49-7641f9dfaa35)

**Comment by Aarebecca** [comment]
可访问 4.0 示例：https://g6.antv.antgroup.com/examples/case/others/#metroLines

3.0 已不在维护
