### ISSUE TITLE
[V5] React自定义节点缩放后再进行拖拽，连线位置错误

### ISSUE THREAD

**Issue by liwx2000** [antvis/G6#5781]
### 问题描述

React实现自定义节点，画布缩放后，再对任意React自定义节点进行拖拽操作，节点间的连线位置会错乱。

### 重现链接

https://g6-next.antv.antgroup.com/zh/examples/element/custom-node/#react-node

### 重现步骤

1. 用React实现自定义节点，渲染两个点和两个点之间的边
2. graph开启zoom-canvas和drag-element的行为
3. 对画布进行缩放操作
4. 拖拽节点，观察节点间连线

### 预期行为

预期连线两端的点始终保持在节点上，实际连线两端指向空白位置。官方示例：https://g6-next.antv.antgroup.com/zh/examples/element/custom-node/#react-node，按步骤操作就可以复现问题。

### 平台

- 操作系统: macOS Sonoma 14.5
- 网页浏览器: Arc 1.44.1
- G6 版本: 5.0.0-beta.37

### 屏幕截图或视频（可选）

https://github.com/antvis/G6/assets/3276204/853bcd08-c95d-4a29-9701-be1f91a75a77

**Comment by Aarebecca** [comment]
你好，这边会尽快排查问题原因

**Comment by hh1412** [comment]
@liwx2000 https://github.com/antvis/G6/issues/5946#issue-2377808959 好像两者有联系

**Comment by WsAzraa** [comment]
V5自定义html节点+自定义边在使用zoomTo后拖拽节点边的定位会不准确

**Comment by Aarebecca** [comment]
最新版已解决，清除 node_modules 后重新安装依赖即可

**Comment by disslk** [comment]
你好，升级到了最新版本，清除 node_modules 后重新安装依赖，上述问题仍然出现，缩放画布后，拖动节点展示一场
