### ISSUE TITLE
node:click event does not provide information about edges connected to the node.

### ISSUE THREAD

**Issue by RackweLLizm** [antvis/G6#5783]
### 问题描述

I was previously using G6 with Graphin and when I clicked on a node, I could see the edges connected to the node in the model. Currently, when I click on a node in the G6 v5Beta version, I cannot see which edges are connected to this node. Is there something I missed?
![Ekran görüntüsü 2024-05-29 105402](https://github.com/antvis/G6/assets/52632318/314ff56f-349e-4c1b-ba8b-7ccbdaa06385)

### 重现链接

notFound

### 重现步骤

notFound

### 预期行为

When you click on the node, the edges connected to the node should be visible.

### 平台

- 操作系统: Windows]
- 网页浏览器: [Google Chrome]
- G6 版本: [v5 beta ]

**Comment by Aarebecca** [comment]
You can get the connected edges by [Graph.getRelatedEdgesData](https://g6-next.antv.antgroup.com/en/api/graph/method#graphgetrelatededgesdataid-direction)

```ts
(event) => {
  graph.getRelatedEdgesData(event.target.id);
}
```
