### ISSUE TITLE
自定义节点能否增加cursor属性

### ISSUE THREAD

**Issue by huliyou** [antvis/g6#579]
能否支持cursor属性，当指针移入节点时，改变指针显示

**Comment by huliyou** [comment]
customNode.attr({
        style: 'cursor: nwse-resize',
})
可以通过attr方法设置style解决

**Comment by luoandy** [comment]
![image](https://user-images.githubusercontent.com/20121275/51240432-a127e780-19b6-11e9-8efb-2f389464dfe3.png)
 这样没效果

**Comment by luoandy** [comment]
@huliyou   老哥你的版本多少

**Comment by McCarthey** [comment]
![image](https://user-images.githubusercontent.com/24711467/56780785-3dae2100-6813-11e9-80ff-3db303ac8aba.png)
@luoandy 版本3.0.1
