### ISSUE TITLE
drag-canvas and brush select do not work properly together.

### ISSUE THREAD

**Issue by RackweLLizm** [antvis/G6#5793]
### Describe the bug

```
behaviors: [
 {
 type: 'click-element',
 multiple: true,
 trigger: ['shift']
 },
 {
 key: 'brush-select',
 type: 'brush-select',
 mode: 'diff',
 trigger: 'shift',
 style: {
 fill: '#00f',
 fillOpacity: 0.2,
 stroke: '#0ff',
 },
 },
 {
 type: 'create-edge',
 key: 'create-edge',
 trigger: 'click',
 enable: false,
 animation: true
 },
 'zoom-canvas',
 // 'drag-canvas',
 'drag-element'
 ],
```

When drag-canvas and brush select are opened at the same time, brush select does not work properly in the graphic.

### Your Example Website or App

notFound

### Steps to Reproduce the Bug or Issue

1-) Brush Select Active
2-) Drag Canvas Active 

Try to make a selection with the Shift key on the canvas, it will not work properly.

### Expected behavior

brush select should work

### Platform

Windows
Chrome 124
 "@antv/g6": "^5.0.0-beta.37",

**Comment by Aarebecca** [comment]
Thanks, I will verify the problem soon

**Comment by RackweLLizm** [comment]
@Aarebecca This error still persists in version 5.0.1. Is there any progress?

**Comment by RackweLLizm** [comment]
@hustcc 
https://stackblitz.com/edit/rackwellizm?file=index.html,index.js
Here is an example from stackbilitz. Selection can be made with the shift key.

**Comment by RackweLLizm** [comment]
@Aarebecca 
https://github.com/antvis/G6/pull/6125
I think the above commit solves this problem too.
