### ISSUE TITLE
【V5】linkCenter和fontFamily和其他

### ISSUE THREAD

**Issue by theDoinb** [antvis/G6#5796]
### 问题描述

1. `linkCenter`能不能加回去，节点加了icon后，因为icon又不一定是圆的，不连到中心太丑了。

2. 字体之前会继承父级的，现在不会，也没看到哪有设置。

3. 像`label`样式，选中状态能否初始化时继承下默认配置，大多数情况下，并不需要去对`label`做选中状态。

4. 目前节点选中时，选中的边框会使`combo`撑大。

5. `cursor`鼠标手挺好的，就是能否监听下鼠标按住时，由`grab` -> `grabbing`

### 重现链接

https://g6-next.antv.antgroup.com/manual/upgrade

### 重现步骤

如上

### 预期行为

如上

### 平台

- 操作系统: Windows
- 网页浏览器: Google Chrome
- G6 版本: v5

**Comment by Aarebecca** [comment]
1. 见 [ports](https://g6-next.antv.antgroup.com/api/elements/nodes/base-node#ports) 设置连接点
```ts
ports: [ {placement: 'center'}]
```

2. 在 style 中设置字体，如设置标签字体：`labelFontFamily`
如果使用 Typescript 开发，你直接在 style 中输入 fontFamily 就能列出所有可配置字体部分
<img width="267" alt="image" src="https://github.com/antvis/G6/assets/25787943/d145bbbc-351d-4368-804a-0836382fbb6e">

3. 状态样式是在默认样式的基础上计算得到的
4. 这是目前的计算逻辑所决定的，当前计算的包围盒会考虑边框宽度。后续根据社区反馈再决定是否要调整。
5. 这个后面会进行修正

**Comment by theDoinb** [comment]
> 1. 见 [ports](https://g6-next.antv.antgroup.com/api/elements/nodes/base-node#ports) 设置连接点
> 
> ```ts
> ports: [ {placement: 'center'}]
> ```
> 
> 2. 在 style 中设置字体，如设置标签字体：`labelFontFamily`
>    如果使用 Typescript 开发，你直接在 style 中输入 fontFamily 就能列出所有可配置字体部分
> 
> <img alt="image" width="267" src="https://private-user-images.githubusercontent.com/25787943/335476044-d145bbbc-351d-4368-804a-0836382fbb6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMzk5MTMsIm5iZiI6MTcxNzEzOTYxMywicGF0aCI6Ii8yNTc4Nzk0My8zMzU0NzYwNDQtZDE0NWJiYmMtMzUxZC00MzY4LTgwNGEtMDgzNjM4MmZiYjZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDA3MTMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwMTU3OTYwMjcwM2E4ZTU5MzAzODY1NDllODJlODI3MDc5NjA0M2NkZTI1Y2NmNGI1MGM1M2ZmZGI2M2E1NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ao4JIGLqd_HAj5d0LZKfo6MTwRwqtjmeQr9ZTAzENr4">
> 3. 状态样式是在默认样式的基础上计算得到的
> 4. 这是目前的计算逻辑所决定的，当前计算的包围盒会考虑边框宽度。后续根据社区反馈再决定是否要调整。
> 5. 这个后面会进行修正

可以看看我写的demo，就3的，我选中node或combo时，`label`字号会变化，combo也会变化，而且我本地还有选中时combo飘移的。
[codesandbox](https://codesandbox.io/p/sandbox/elated-wood-l6wdct?file=%2Findex.js%3A13%2C19)

顺便吐槽下，你们这官网图表实例，hover那个codesandbox按钮，tooltip导致滚动来回出现，没法点击。

**Comment by Aarebecca** [comment]
> > 1. 见 [ports](https://g6-next.antv.antgroup.com/api/elements/nodes/base-node#ports) 设置连接点
> > 
> > ```ts
> > ports: [ {placement: 'center'}]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. 在 style 中设置字体，如设置标签字体：`labelFontFamily`
> >    如果使用 Typescript 开发，你直接在 style 中输入 fontFamily 就能列出所有可配置字体部分
> > 
> > <img alt="image" width="267" src="https://private-user-images.githubusercontent.com/25787943/335476044-d145bbbc-351d-4368-804a-0836382fbb6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMzk5MTMsIm5iZiI6MTcxNzEzOTYxMywicGF0aCI6Ii8yNTc4Nzk0My8zMzU0NzYwNDQtZDE0NWJiYmMtMzUxZC00MzY4LTgwNGEtMDgzNjM4MmZiYjZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDA3MTMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwMTU3OTYwMjcwM2E4ZTU5MzAzODY1NDllODJlODI3MDc5NjA0M2NkZTI1Y2NmNGI1MGM1M2ZmZGI2M2E1NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ao4JIGLqd_HAj5d0LZKfo6MTwRwqtjmeQr9ZTAzENr4">
> > 3. 状态样式是在默认样式的基础上计算得到的
> > 4. 这是目前的计算逻辑所决定的，当前计算的包围盒会考虑边框宽度。后续根据社区反馈再决定是否要调整。
> > 5. 这个后面会进行修正
> 
> 可以看看我写的demo，就3的，我选中node或combo时，`label`字号会变化，combo也会变化，而且我本地还有选中时combo飘移的。 [codesandbox](https://codesandbox.io/p/sandbox/elated-wood-l6wdct?file=%2Findex.js%3A13%2C19)
> 
> 顺便吐槽下，你们这官网图表实例，hover那个codesandbox按钮，tooltip导致滚动来回出现，没法点击。

你提供的示例无法打开。另外你提到的按钮滚动的问题应该是模版的问题，麻烦去这里提个 Issue 呢：https://github.com/antvis/dumi-theme-antv/  这个问题应该跟显示设备有关系

**Comment by theDoinb** [comment]
> > > 1. 见 [ports](https://g6-next.antv.antgroup.com/api/elements/nodes/base-node#ports) 设置连接点
> > > 
> > > ```ts
> > > ports: [ {placement: 'center'}]
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 
> > > 2. 在 style 中设置字体，如设置标签字体：`labelFontFamily`
> > >    如果使用 Typescript 开发，你直接在 style 中输入 fontFamily 就能列出所有可配置字体部分
> > > 
> > > <img alt="image" width="267" src="https://private-user-images.githubusercontent.com/25787943/335476044-d145bbbc-351d-4368-804a-0836382fbb6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMzk5MTMsIm5iZiI6MTcxNzEzOTYxMywicGF0aCI6Ii8yNTc4Nzk0My8zMzU0NzYwNDQtZDE0NWJiYmMtMzUxZC00MzY4LTgwNGEtMDgzNjM4MmZiYjZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDA3MTMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwMTU3OTYwMjcwM2E4ZTU5MzAzODY1NDllODJlODI3MDc5NjA0M2NkZTI1Y2NmNGI1MGM1M2ZmZGI2M2E1NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ao4JIGLqd_HAj5d0LZKfo6MTwRwqtjmeQr9ZTAzENr4">
> > > 3. 状态样式是在默认样式的基础上计算得到的
> > > 4. 这是目前的计算逻辑所决定的，当前计算的包围盒会考虑边框宽度。后续根据社区反馈再决定是否要调整。
> > > 5. 这个后面会进行修正
> > 
> > 
> > 可以看看我写的demo，就3的，我选中node或combo时，`label`字号会变化，combo也会变化，而且我本地还有选中时combo飘移的。 [codesandbox](https://codesandbox.io/p/sandbox/elated-wood-l6wdct?file=%2Findex.js%3A13%2C19)
> > 顺便吐槽下，你们这官网图表实例，hover那个codesandbox按钮，tooltip导致滚动来回出现，没法点击。
> 
> 你提供的示例无法打开。另外你提到的按钮滚动的问题应该是模版的问题，麻烦去这里提个 Issue 呢：https://github.com/antvis/dumi-theme-antv/ 这个问题应该跟显示设备有关系

好的，示例忘放开了：[codesandbox](https://codesandbox.io/p/sandbox/laughing-jones-935cp8?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwucvpda00063j6g8rfrgusx%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwucvpda00023j6gsu9ixmvu%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwucvpda00033j6gm7a2w2yg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwucvpda00053j6gliw3dcue%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwucvpda00023j6gsu9ixmvu%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwucvpd900013j6gjjfwsrs7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A13%252C%2522startColumn%2522%253A19%252C%2522endLineNumber%2522%253A13%252C%2522endColumn%2522%253A19%257D%255D%257D%255D%252C%2522id%2522%253A%2522clwucvpda00023j6gsu9ixmvu%2522%252C%2522activeTabId%2522%253A%2522clwucvpd900013j6gjjfwsrs7%2522%257D%252C%2522clwucvpda00053j6gliw3dcue%2522%253A%257B%2522id%2522%253A%2522clwucvpda00053j6gliw3dcue%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwucvpda00043j6gi129s2fp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clwucvpda00043j6gi129s2fp%2522%257D%252C%2522clwucvpda00033j6gm7a2w2yg%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clwucvpda00033j6gm7a2w2yg%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
