### ISSUE TITLE
怎么能做到画布缩放，节点不缩放？

### ISSUE THREAD

**Issue by mabelyong** [antvis/g6#580]
目前缩放画布，node节点也跟着缩放了，现在想要的效果是画布缩放node节点的大小不变，相当于是原来密集的点随画布变大变得稀疏，缩小变得密集，但节点大小是不发生变化的。使用maxZoom或minZoom会限制画布的缩放。求高手指点一下怎么做，看了文档上没有相关的介绍。

**Comment by elaine1234** [comment]
G6当中画布缩放，节点必定会随着一起缩放。
这个效果其实应该是布局算法要解决问题，布局得紧密就是紧密。
