### ISSUE TITLE
用来渲染图例的同一份数据，只是edges中几条数据位置有变化，使用dagre插件之后绘制出的图中元素的位置也会发生改变

### ISSUE THREAD

**Issue by mxszs** [antvis/g6#582]
* G6 Version:2.1.0-beta.20
* Platform:Web
* G6 ：用来渲染图例的同一份数据，只是edges中几条数据位置有变化，使用dagre插件之后绘制出的图中元素的位置也会发生改变
* codepen地址 https://codepen.io/mxszs/project/editor/ZzBwEk

**Comment by mxszs** [comment]
每次渲染前对数据进行排序，这个方法可以解决部分问题，对与动态获取到的数据，还是会有问题

**Comment by elaine1234** [comment]
dagre 重新布局是不会考虑之前的节点位置的，如果只是edge变化，希望节点不变，建议直接修改需要变动的 edge 实例数据
