### ISSUE TITLE
【V5】Node 的层级无论如何设置层级永远比 Combo的层级高

### ISSUE THREAD

**Issue by wulianpu** [antvis/G6#5821]
Node 的层级无论如何设置层级永远比 Combo的层级高
具体示例可见：https://g6-next.antv.antgroup.com/examples/layout/dagre/#antv-dagre-combo
<img width="778" alt="image" src="https://github.com/antvis/G6/assets/44516614/e7b1d6cb-66d5-4563-8658-b86c5b918cb1">
但在4.X版本是可以控制的，这是有什么其他考虑吗

**Comment by Aarebecca** [comment]
目前节点、边、组合是划分到三个分组中的，并且层级顺序是 node > edge > combo，确实会导致上述问题。后续会进行一下调整。

相关 Issue: https://github.com/antvis/G6/issues/5836
