### ISSUE TITLE
问下， 使用darge 布局，如何自定义中线位置

### ISSUE THREAD

**Issue by dbl520** [antvis/G6#5822]
### 问题描述

![image](https://github.com/antvis/G6/assets/17171011/d5a2a212-6e4a-4dd2-91b2-6b93ae952854)
进入页面，初始化，希望中线根据节点最长的连线，作为中线布局

### 重现链接

https://codesandbox.io/p/sandbox/eloquent-leftpad-84l24m?file=%2Findex.js%3A1%2C1-370%2C1

### 重现步骤

进入页面，初始化，希望中线根据节点最长的连线，作为中线布局

### 预期行为

希望划红框部分布局在中线上

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.8.24 ]

**Comment by Aarebecca** [comment]
非问题反馈请到 Discussion 讨论 / Please go to Discussion for non-question feedback
