### ISSUE TITLE
如何折叠或展开部分子节点

### ISSUE THREAD

**Issue by MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM** [antvis/G6#5829]
### 问题描述

如何实现   点击跟节点左侧mark折叠或者展开左侧树，点击右侧mark  折叠或者展开右侧子树，而不是改变根节点的collapsed，左右全都折叠或者展开，这个应该是很常用的需求功能，但是没找到相应的官方案例

![1717652250800](https://github.com/antvis/G6/assets/33676254/165bb7ed-9b01-4e4b-b3f4-6b2e4acd8f12)

### 重现链接

无

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by Aarebecca** [comment]
非问题反馈请到 Discussion 讨论 / Please go to Discussion for non-question feedback

**Comment by jsbiggod** [comment]
这垃圾文档，这个问题解决了吗？

**Comment by jsbiggod** [comment]
> 非问题反馈请到 Discussion 讨论 / Please go to Discussion for non-question feedback

你管人鸟事
