### ISSUE TITLE
请问类似于流图的交叉连接怎么做

### ISSUE THREAD

**Issue by 2012shenghua** [antvis/G6#583]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

https://codepen.io/DoriTong/pen/QVjzja 类似于这样的，需要子节点也要交叉连接

**Comment by wflixu** [comment]
链接打不开了，现在

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于我们没有得到可追踪复现的 demo，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
