### ISSUE TITLE
离线文档

### ISSUE THREAD

**Issue by mioxs** [antvis/G6#5834]
### 问题描述

文档是否可以支持完全离线，想vue一样完全离线的文档不使用cdn

### 重现链接

https://stackblitz.com/

### 重现步骤

离线文档

### 预期行为

离线文档

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
- G6 版本: [4.5.1 ... ]

**Comment by hanfengcan** [comment]
仓库里面就有文档的分支，下载后，部署到Nginx就可以了

**Comment by hustcc** [comment]
目前应该只有 demo  的截图是使用 cdn，但是这个不影响使用。
