### ISSUE TITLE
[V5] Plugin Legend does not remain static.

### ISSUE THREAD

**Issue by RackweLLizm** [antvis/G6#5838]
### 问题描述

Legend plugin moves with the canvas when zooming in and zooming out on the canvas. It does not remain in a fixed area.
![image](https://github.com/antvis/G6/assets/52632318/6b703910-3167-45e8-8d88-defe4dc3553a)

### 重现链接

notFound

### 重现步骤

notFound

### 预期行为

Legend plugin must have a static value. For example, when zooming in and zooming out on the top-right canvas, it should remain in the specified static area.

### 平台

Windows
Chrome 124
"@antv/g6": "^5.0.0-beta.40",

**Comment by Aarebecca** [comment]
In current, the legend plugin was painted in the same canvas with G6 elements, so will be affected when the camera is changed.
The advantage of the above approach is that the legend can be included in the exported image

we will evaluate the best  way to set the legend later.
