### ISSUE TITLE
请问，自定义边edge的时候label文字的背景是白色，能否设置成透明的

### ISSUE THREAD

**Issue by 2012shenghua** [antvis/g6#584]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by awebird** [comment]
edge增加 labelRectStyle: { opacity: 0 }

**Comment by JiangJun1994** [comment]
请问你是用的2.0还是3.0版本自定义edge呢？

**Comment by JiangJun1994** [comment]
您好，能否看看您自定义边的代码呢？

**Comment by 2012shenghua** [comment]
我用的是2.0版本的，背景颜色设置不了，可以设置透明度，如上面老哥所说

**Comment by awebird** [comment]
https://codepen.io/awebird/pen/jJVjrZ

**Comment by awebird** [comment]
https://github.com/antvis/g6/blob/master/src/shape/edges/common.js
L109
`const style = model.labelRectStyle ? Util.mix({}, defaultStyle, model.labelRectStyle) : defaultStyle;`
g6的文档暴露的参数较少，建议需要高阶配置的时候只能翻下源码

**Comment by JiangJun1994** [comment]
> edge增加 labelRectStyle: { opacity: 0 }

> https://github.com/antvis/g6/blob/master/src/shape/edges/common.js

谢谢

**Comment by JiangJun1994** [comment]
> 我用的是2.0版本的，背景颜色设置不了，可以设置透明度，如上面老哥所说

谢谢
