### ISSUE TITLE
pnpm add  @antv/g6-extension-react@0.1.1 显示警告

### ISSUE THREAD

**Issue by wanghui2021** [antvis/G6#5843]
### Describe the bug / 问题描述

<img width="411" alt="image" src="https://github.com/antvis/G6/assets/37385554/c0162c11-3ce9-4713-badc-becd8c56b8b0">

可能的原因：
https://github.com/antvis/G/blob/277abff24936ef6f7c43407a16c5bc9260992511/packages/react-g/package.json#L56

### Steps to Reproduce the Bug or Issue / 重现步骤

`pnpm add  @antv/g6-extension-react@0.1.1 `

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
不影响使用，忽略即可
