### ISSUE TITLE
mindmap (react 自定义节点)  使用 collapse-expand 时，边发生错位

### ISSUE THREAD

**Issue by wanghui2021** [antvis/G6#5844]
### Describe the bug / 问题描述

点击 Consensus 之前
<img width="989" alt="image" src="https://github.com/antvis/G6/assets/37385554/16427fd2-ca8a-4bae-9f68-198347faa498">

点击 Consensus 之后
<img width="986" alt="image" src="https://github.com/antvis/G6/assets/37385554/082cda09-eeb6-4a66-9ed5-aba966e965ba">

### Reproduction link / 重现链接

https://stackblitz.com/edit/react-vr47b5?file=index.js

### Steps to Reproduce the Bug or Issue / 重现步骤

点击 Consensus

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

### Additional context / 补充说明

1. 节点使用 React 自定义
2. 使用 SVG 渲染

**Comment by yvonneyx** [comment]
此问题已修复，请更新到最新版本进行验证
