### ISSUE TITLE
官方文档提供的自定义边的示例异常

### ISSUE THREAD

**Issue by wanghui2021** [antvis/G6#5846]
### Describe the bug / 问题描述

官方文档提供的自定义边的示例异常
<img width="614" alt="image" src="https://github.com/antvis/G6/assets/37385554/9c4f191d-5101-451c-9b31-9b52be1bc2a0">

### Reproduction link / 重现链接

https://g6-next.antv.antgroup.com/manual/custom-extension/element#%E5%AE%9E%E7%8E%B0%E8%BE%B9

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
会尽快更新相关文档
