### ISSUE TITLE
After the device topology is rendered, the image is misplaced when the collapse button is clicked.

### ISSUE THREAD

**Issue by Mysticsstar** [antvis/G6#5847]
### AntV Open Source Contribution Plan（可选/Optional）

- [ ] 我同意将这个 Issue 参与 OSCP 计划 / I agree to participate in the OSCP plan

### Issue 类型 / Issue Type

None

### 任务介绍 / Task Description

Upgrade antv/g6 from version 4.6.18 to 4.8.21
After the device topology is rendered, the image is misplaced when the collapse button is clicked.
![topo1](https://github.com/antvis/G6/assets/43193192/a6661cce-8ff5-4bd7-92f3-9aeaea7d6ebb)
![topo2](https://github.com/antvis/G6/assets/43193192/1e168236-8d2b-46f0-8896-14eee9c2b7bd)

**Comment by Aarebecca** [comment]
You have selected the wrong question template, we are sorry to close this issue. You'd better create a new question and provide more information about your question
