### ISSUE TITLE
[v5.0.1]polyline edge绘制bug，style中没有controlPoints，绘制结果却有拐点

### ISSUE THREAD

**Issue by zzjjbbaa** [antvis/G6#5848]
### Describe the bug / 问题描述

https://github.com/antvis/G6/assets/54572770/f7698069-ce3c-47ae-bce0-f1b9b55a65f6

**根据视频中演示；**
1.生成了两条polyline,上面一条的polyline.style.controlPoints不是空的；另一条的controlPoints是空的。
2.但是最终的渲染效果,两条edge共用了上面一条的controlPoints。
**附上两个edge的数据：**
![image](https://github.com/antvis/G6/assets/54572770/f87a8963-4ec0-4bed-bedd-16fb55caad7f)
**附上两个edge的渲染效果**
![image](https://github.com/antvis/G6/assets/54572770/7225e7e0-3203-4ca8-aac2-1c665ef69099)

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Edge

### Additional context / 补充说明

无

**Comment by zzjjbbaa** [comment]
更新下一个临时解决方案，在生成edge时，必须默认指定```controlPoints:[]```

**Comment by Aarebecca** [comment]
duplicated with https://github.com/antvis/G6/issues/5849
