### ISSUE TITLE
[v5.0.1] polyline中如果controlPoints未undfined,绘制不出边

### ISSUE THREAD

**Issue by zzjjbbaa** [antvis/G6#5849]
### Describe the bug / 问题描述

**bad**
![image](https://github.com/antvis/G6/assets/54572770/3f48e243-1c82-49a9-9f60-659357294477)
**good**
![image](https://github.com/antvis/G6/assets/54572770/eacde349-d28b-4a0b-ba39-4633c3d13c90)

### Reproduction link / 重现链接

https://stackblitz.com/edit/react-zh29y4?file=index.js

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

### Additional context / 补充说明

希望没有controlPoints也能正常绘制

**Comment by Aarebecca** [comment]
`controlPoints`  是具有默认值 `[]` 的，你这里的问题是因为 edge.style.controlPoints 传入了 `undefined` 覆盖了默认值，正确的写法应该是：
```ts
controlPoints: (d) => d.style.controlPoints || []
```
