### ISSUE TITLE
G6 v5没有字符超出省略功能

### ISSUE THREAD

**Issue by mioxs** [antvis/G6#5858]
v4功能
Util.getTextSize和Util.getLetterWidth

**Comment by Aarebecca** [comment]
通过如下配置即可开启文本省略：
```
{
  labelWordWrap: true,
  labelWordWrapWidth: 100
}
```
<img width="133" alt="image" src="https://github.com/antvis/G6/assets/25787943/160757c0-c674-4ad8-a641-6783039d2038">


参考：https://g.antv.antgroup.com/api/basic/text#wordwrapwidth
