### ISSUE TITLE
导出 util 目录下的函数

### ISSUE THREAD

**Issue by wanghui2021** [antvis/G6#5859]
### Describe the bug / 问题描述

希望导出 util 目录下的函数。在自定义元素的情况下，需要部分转化函数。例如：`parsePath` 等

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
由于导出后会增加维护成本并导致变更风险，所以暂时不会导出这部分工具方法。你可以参考 G6 代码实现一份。
