### ISSUE TITLE
怎么自定义流程节点参数?

### ISSUE THREAD

**Issue by top-soft** [antvis/g6#586]
看到社区插件GGEditor，发现还是基于G6，看了API没找到自定义节点参数
在GGEditor 写了详细的描述
https://github.com/gaoli/GGEditor/issues/156#issue-396417626

**Comment by baizn** [comment]
G6 2.x自定义节点参考[这里](https://www.yuque.com/antv/g6/custom-node)，目前2.x没在维护了，使用G6时建议升级到最新版。
