### ISSUE TITLE
iconText从div的属性获取导致渲染不正确

### ISSUE THREAD

**Issue by zhangsai521314** [antvis/G6#5862]
### Describe the bug / 问题描述

1：定义一个div：<div id="ssss" iconUnicode='\ue602'>
2：使用document.getElementById('ssss').getAttribute('iconUnicode')获取值赋值给iconText
3：icon显示为字符

### Reproduction link / 重现链接

https://stackblitz.com/edit/react-dvck84?file=index.js

### Steps to Reproduce the Bug or Issue / 重现步骤

1：定义一个div：<div id="ssss" iconUnicode='\ue602'>
2：使用document.getElementById('ssss').getAttribute('iconUnicode')获取值赋值给iconText
3：icon显示为字符

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Firefox

**Comment by Aarebecca** [comment]
```
document.getElementById('ssss').getAttribute('iconUnicode') === '\ue602'
```
> \>\> false

字符编码问题请自行解决
