### ISSUE TITLE
300+节点、500+边大图缩放时卡顿

### ISSUE THREAD

**Issue by yvonneyx** [antvis/G6#5864]
### Describe the bug / 问题描述

300+节点、500+边大图缩放时卡顿

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by keminu** [comment]
1、https://g6.antv.antgroup.com/api/plugins#minimap  type配置为keyShpape会好很多
2、https://g6.antv.antgroup.com/api/plugins#minimap hideEdge 一般不需要看到，可以配置为ture
3、条件允许，开启gpu渲染、canvas渲染
4、减少自定义节点 https://g6.antv.antgroup.com/manual/faq/performance-opt
