### ISSUE TITLE
官网报错无法访问 https://g6.antv.vision

### ISSUE THREAD

**Issue by yubo9807** [antvis/G6#5866]
### Describe the bug / 问题描述

![image](https://github.com/antvis/G6/assets/95408465/6e3a4376-4103-4f4b-91b2-bd661c877794)

### G6 Version / G6 版本

4.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
请访问：https://g6.antv.antgroup.com/
