### ISSUE TITLE
mindmap 试用边样式 “polyline”, 布局错误

### ISSUE THREAD

**Issue by SevenNorth** [antvis/G6#5869]
### Describe the bug / 问题描述

使用脑图布局， 试用折线边的时候， 布局及绘制错误
![image](https://github.com/antvis/G6/assets/53900832/93e47f7a-be9a-4b22-8179-5fad18ea8496)

### Reproduction link / 重现链接

https://codesandbox.io/p/sandbox/polished-flower-96tntv

### Steps to Reproduce the Bug or Issue / 重现步骤

运行代码即可

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
感谢反馈，该问题已确认，会尽快修复

**Comment by yvonneyx** [comment]
该问题现已修复 ❤️
