### ISSUE TITLE
Dagre使用group，group位置错误

### ISSUE THREAD

**Issue by BusyHe** [antvis/G6#587]
https://codesandbox.io/s/3r4v9ml44q
![image](https://user-images.githubusercontent.com/17348825/50816532-d94a7d00-135b-11e9-8704-e57170f027dd.png)

**Comment by BusyHe** [comment]
这是个bug还是一个正常、还是不解决了。怎么样的处理方法，我是一直用G6。我希望这个也越来越好，希望给出回应，如果描述的不详细，我可以补充

**Comment by dxq613** [comment]
这个在 3.0 中解决，敬请等待！

**Comment by BusyHe** [comment]
@dxq613 好的，期待3.0 加油

**Comment by BusyHe** [comment]
@dxq613 3.0没有找到群组，我如果按照你说的算法我怎么计算呢，能给出demo吗？

**Comment by baizn** [comment]
@BusyHe G6 3.x 的群组功能目前正在开发中。计算的话 就是先使用dagre布局，得到带有坐标信息的数据，将这个数据输入到G6中进行渲染。

**Comment by wxy1995** [comment]
@baizn @dxq613 只要在 layout/dagre.js `const g = new dagre.graphlib.Graph();` 中，增加一个配置 `compound`，允许用户自己配置为 `true`，就能解决这个问题了。相关文档在 [graphlib](https://github.com/dagrejs/graphlib/wiki/API-Reference#graph-concepts)，这个有考虑增加吗？

**Comment by Yanyan-Wang** [comment]
带有全新节点分组 Combo 机制的 v3.5 发布了。demos：
内置 combos: https://g6.antv.vision/zh/examples/item/defaultCombos
自定义 combos: https://g6.antv.vision/zh/examples/item/customCombo
Combo 的布局: https://g6.antv.vision/zh/examples/net/comboForce
Combo 的交互: https://g6.antv.vision/zh/examples/interaction/combo

文档可以通过 [G6 官网](https://g6.antv.vision/zh) 上方的搜索栏搜索“combo”查看。
