### ISSUE TITLE
【V5】取消了drawOtherShapes 方法之后，vue 如何实现ReactNode的自定义节点？

### ISSUE THREAD

**Issue by zyh0yh** [antvis/G6#5871]
### AntV Open Source Contribution Plan（可选/Optional）

- [ ] 我同意将这个 Issue 参与 OSCP 计划 / I agree to participate in the OSCP plan

### Issue 类型 / Issue Type

None

### 任务介绍 / Task Description

目前正在做项目的V4升级V5工作，V4的时候使用drawOtherShapes进行的自定义节点配置，V5 我查看了一下文档，发现没有drawOtherShapes方法，且图表示例中只存在JSX和react自定义节点的案例，目前需要VUE 自定义节点的一个方案，或者是一些帮助！

**Comment by Aarebecca** [comment]
提问（非 issue）请移至 [discussion](https://github.com/antvis/G6/discussions)
