### ISSUE TITLE
[V5]使用setData&render更新数据，combo数据会报Node not found for id: xx

### ISSUE THREAD

**Issue by qishenliang** [antvis/G6#5880]
### Describe the bug / 问题描述

第一次更新数据没问题，第二次开始，只要更换了combos的数据（与原来有差异）的时候，就会报错，报错代码在graphlib的getNode()函数，在获取combo时，nodeMap里面node已经被删除

### Reproduction link / 重现链接

https://stackblitz.com/edit/react-ihejga?file=index.html,index.js

### Steps to Reproduce the Bug or Issue / 重现步骤

等待第二秒定时器就会报错

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
render 是异步方法，所以不要使用 `setInterval` ，你可以使用
```ts
graph.render().then(()=>{
  // ...
})
```

或者
```ts
await graph.render();

// ...
```

**Comment by qishenliang** [comment]
> render 是异步方法，所以不要使用 `setInterval` ，你可以使用
> 
> ```ts
> graph.render().then(()=>{
>   // ...
> })
> ```
> 
> 或者
> 
> ```ts
> await graph.render();
> 
> // ...
> ```

我更新了demo代码，麻烦您再看下，实际场景就是通过交互更新data
