### ISSUE TITLE
g6 v5版本拖拽node或combo后经常会出现node/combo的边框线条

### ISSUE THREAD

**Issue by tomorrowcheng** [antvis/G6#5884]
### Describe the bug / 问题描述

1、v5版本拖拽node或combo后经常会出现node/combo的边框线条
2、用graph.removeNodeData、graph.layout后，重新布局也会出现线条

### Reproduction link / 重现链接

https://g6-next.antv.antgroup.com/zh/examples/layout/dagre/#antv-dagre-combo

### Steps to Reproduce the Bug or Issue / 重现步骤

<img width="1466" alt="企业微信截图_6cdaf956-b101-4d45-a39d-f43ff40d2ca3" src="https://github.com/antvis/G6/assets/42925114/62004c87-c6fb-45fa-aafe-d872d984e5de">
1、拖动上面链接上的Combo能复现上面的问题

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
这个是由于底层渲染引擎脏矩形擦除不干净导致，可以先切换到 SVG 渲染器。Canvas 下近期无法修复该问题

**Comment by tomorrowcheng** [comment]
> 这个是由于底层渲染引擎脏矩形擦除不干净导致，可以先切换到 SVG 渲染器。Canvas 下近期无法修复该问题

关闭动画就没有问题了；切换到svg渲染在大数据量下会有性能问题吧？
