### ISSUE TITLE
使用setData&render更新数据，combo数据会报Node not found for id: xx

### ISSUE THREAD

**Issue by qishenliang** [antvis/G6#5885]
### Describe the bug / 问题描述

第一次更新数据没问题，第二次开始，只要更换了combos的数据（与原来有差异）的时候，就会报错，报错代码在graphlib的getNode()函数，在获取combo时，nodeMap里面node已经被删除

### Reproduction link / 重现链接

https://stackblitz.com/edit/react-ihejga?file=index.html,index.js

### Steps to Reproduce the Bug or Issue / 重现步骤

第二次点击按钮就报错

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

### Additional context / 补充说明

昨天提过issues，使用定时器演示被告知是异步的问题，可是我换点击动作出发还是报错，原谅我重新提一次

**Comment by Aarebecca** [comment]
这个例子中的异常应该是由 Bug 导致，后续会进行修复

**Comment by Aarebecca** [comment]
相关问题已修复，预计 0619 发布 5.0.2 版本后可用
