### ISSUE TITLE
G6 V3版本 文档地址是否已经停止维护了

### ISSUE THREAD

**Issue by NidhoggDJoking** [antvis/G6#5886]
###  `https://g6-v3-2.antv.vision/` 无法正常打开了
>  国内gh-pages站点也失效（gitee pages 服务关闭了）

![微信截图_20240619095919](https://github.com/antvis/G6/assets/38490462/205f487c-a384-4f4e-bbd9-aa74818778c8)

### Reproduction link / 重现链接

https://g6-v3-2.antv.vision/

### Steps to Reproduce the Bug or Issue / 重现步骤

接手老项目使用G6 3.x版本 功能调整需要查阅文档，

或者是否有G6 3x 升级 4.x的升级指南

### G6 Version / G6 版本

3.x or below / 3.x 或更低版本

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
3.x 站点部署在 Github Pages，国内用户访问可能较为缓慢
