### ISSUE TITLE
Antv G6 5.0.1 after removeNode/EdgeData render() throw error deleted node/edge could not be found

### ISSUE THREAD

**Issue by HappyColour** [antvis/G6#5889]
### Describe the bug / 问题描述

Antv G6 5.0.1
问题：删除节点/边 后，调用render()函数报错找不到被删除的节点/边的id

### Reproduction link / 重现链接

https://codesandbox.io/p/devbox/antv-g6-render-kwy265?file=%2Fsrc%2FApp.vue%3A35%2C31&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxl7jyjs00073b6jt9fenbg5%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxl7jyjs00023b6jgluag8em%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxl7jyjs00043b6j49kzgehv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxl7jyjs00063b6j8gcn8j86%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxl7jyjs00023b6jgluag8em%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxl7jyjr00013b6jhdd8ezdx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clxl8007x00023b6ipun9hs3b%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A35%252C%2522startColumn%2522%253A31%252C%2522endLineNumber%2522%253A35%252C%2522endColumn%2522%253A31%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxl7jyjs00023b6jgluag8em%2522%252C%2522activeTabId%2522%253A%2522clxl8007x00023b6ipun9hs3b%2522%257D%252C%2522clxl7jyjs00063b6j8gcn8j86%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxl7jyjs00053b6je4dp2cmp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxl7jyjs00063b6j8gcn8j86%2522%252C%2522activeTabId%2522%253A%2522clxl7jyjs00053b6je4dp2cmp%2522%257D%252C%2522clxl7jyjs00043b6j49kzgehv%2522%253A%257B%2522id%2522%253A%2522clxl7jyjs00043b6j49kzgehv%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxl7jyjs00033b6jm3x1cn6d%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clxl7jyjs00033b6jm3x1cn6d%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to Reproduce the Bug or Issue / 重现步骤

1. 打开控制台
2. 鼠标移入节点
3. 右键节点
4. 点击删除
5. 查看控制台报错

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by qishenliang** [comment]
兄弟你的问题跟我差不多，对元素Data进行删除后render，会报找不到删除元素，看了源码，实际元素的data在get前已经被delete

**Comment by HappyColour** [comment]
> 兄弟你的问题跟我差不多，对元素Data进行删除后render，会报找不到删除元素，看了源码，实际元素的data在get前已经被delete

先用draw函数渲染，后续会修改这个bug

**Comment by qishenliang** [comment]
> > 兄弟你的问题跟我差不多，对元素Data进行删除后render，会报找不到删除元素，看了源码，实际元素的data在get前已经被delete
> 
> 先用draw函数渲染，后续会修改这个bug

如何涉及combo数据改动，用draw也不行，可以参考这个[https://stackblitz.com/edit/react-ihejga?file=index.html,index.js](demo)

**Comment by HappyColour** [comment]
> > > 兄弟你的问题跟我差不多，对元素Data进行删除后render，会报找不到删除元素，看了源码，实际元素的data在get前已经被delete
> > 
> > 
> > 先用draw函数渲染，后续会修改这个bug
> 
> 如何涉及combo数据改动，用draw也不行，可以参考这个[https://stackblitz.com/edit/react-ihejga?file=index.html,index.js](demo)

@Aarebecca  请关注

**Comment by Aarebecca** [comment]
相关问题已修复，预计 0619 发布 5.0.2 版本后可用

**Comment by HappyColour** [comment]
> 相关问题已修复，预计 0619 发布 5.0.2 版本后可用

删除 node/edge 之后会导致 behaviors 的 collapse-expand 抛出异常 node/edge not found 也请注意
