### ISSUE TITLE
鼠标拖动到定义div盒子边距外侧的BUG

### ISSUE THREAD

**Issue by rickyhexiang** [antvis/G6#5890]
### Describe the bug / 问题描述

https://antv-2018.alipay.com/zh-cn/g6/3.x/demo/case/voucher-transfer.html
以此官网demo为例，会有有个bug需求寻求解决方案
操作步骤如下：①鼠标左键按住拖动，拉到定义div盒子边距外边后，松开鼠标左键；②把鼠标光标移回盒子内部，节点树会随着鼠标移动而移动，直至再次点击鼠标左键才会失去该功能。

### G6 Version / G6 版本

3.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
G6 3.x 已停止维护
