### ISSUE TITLE
[V5]运行graph.getCanvas().transient.removeChild(line);删除line时，没有生效

### ISSUE THREAD

**Issue by k644606347** [antvis/G6#5892]
### Describe the bug / 问题描述

我正在为V5版本，制作一个叫snapline的插件，用于在节点间生成对齐线，[简单的demo](https://codesandbox.io/p/sandbox/fast-wood-5l2p9v?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxlfuv8200063b6mxnxenwkz%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxlfuv8100023b6m41yna8zc%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxlfuv8100033b6my1ya56ys%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxlfuv8100053b6ml6qer51b%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxlfuv8100023b6m41yna8zc%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxlfuv8100013b6msqzl3la8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxlfuv8100023b6m41yna8zc%2522%252C%2522activeTabId%2522%253A%2522clxlfuv8100013b6msqzl3la8%2522%257D%252C%2522clxlfuv8100053b6ml6qer51b%2522%253A%257B%2522id%2522%253A%2522clxlfuv8100053b6ml6qer51b%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxlfuv8100043b6mkl0tt5xh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clxlfuv8100043b6mkl0tt5xh%2522%257D%252C%2522clxlfuv8100033b6my1ya56ys%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clxlfuv8100033b6my1ya56ys%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)，遇到了一些问题：

1. 当节点间相互远离时，我会运行graph.getCanvas().transient.removeChild(line);删除对齐线，但没有生效；
<img width="1713" alt="image" src="https://github.com/antvis/G6/assets/6951527/5705ed09-c891-43b4-bf59-76243f7558e7">

2. 我需要获取到所有node的size，或者上下左右4个点位的坐标，来更精确的布局对齐线(比如在node左右侧位置设置对齐线)，但通过graph.getNodeData()[0].style.size没有获取到，不知道有什么方法吗；
<img width="810" alt="image" src="https://github.com/antvis/G6/assets/6951527/7b664c32-809a-4f08-9773-677b241385d4">

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
首先非常感谢你的贡献，针对你提到的问题：
1. 分层渲染是 G6 5.0 的初步设想，但并未完全实现，因此当前所有插入到画布中的节点都位于主画布（即 `graph.getCanvas().main`）。因此你可以先通过 `graph.getCanvas().main.removeChild(line);` 进行删除。
2. 如果要获取节点的尺寸，比较准确的方式是直接从元素中获取，以下是相关步骤
> 假定你的开发的 snapline 是一个插件(Plugin)，那么你应该可以访问到 Graph 上下文（即 context，或者你可以先临时通过 graph.context） 访问。
```ts
const { element } = context; // element 是一个用于管理元素绘制的模块
const node = element.getElement('xxx'); // 参数为元素 ID
```
针对节点的尺寸有两种情况：
 a. 如果期望是对节点整体对齐（包括节点的标签文本、徽标等），那么你可以直接通过 `node.getBounds()` 获取其尺寸
 b. 如果期望对节点的主图形(key)进对齐，那么可以使用 `node.getShape('key').getBounds()` 获取主图形尺寸

**Comment by k644606347** [comment]
> 首先非常感谢你的贡献，针对你提到的问题：
> 
> 1.  分层渲染是 G6 5.0 的初步设想，但并未完全实现，因此当前所有插入到画布中的节点都位于主画布（即 `graph.getCanvas().main`）。因此你可以先通过 `graph.getCanvas().main.removeChild(line);` 进行删除。
> 2.  如果要获取节点的尺寸，比较准确的方式是直接从元素中获取，以下是相关步骤
> 
> > 假定你的开发的 snapline 是一个插件(Plugin)，那么你应该可以访问到 Graph 上下文（即 context，或者你可以先临时通过 graph.context） 访问。
> 
> ```ts
> const { element } = context; // element 是一个用于管理元素绘制的模块
> const node = element.getElement('xxx'); // 参数为元素 ID
> ```
> 
> 针对节点的尺寸有两种情况： a. 如果期望是对节点整体对齐（包括节点的标签文本、徽标等），那么你可以直接通过 `node.getBounds()` 获取其尺寸 b. 如果期望对节点的主图形(key)进对齐，那么可以使用 `node.getShape('key').getBounds()` 获取主图形尺寸

感谢回复，好使！
