### ISSUE TITLE
【V5】 自定义节点，如何获取状态

### ISSUE THREAD

**Issue by ada87** [antvis/G6#5898]
### Describe the bug / 问题描述

在先前的 【beta版本】里面，我是这样获取的：

```typescript
class CustomNode extends Extensions.BaseNode {
  fn(){
      const state = this.graph.getItemState(id, STATE_NAME);
  }
}
```

现在到正式V5.0.1版本了，确找不到相关的功能了

需要在 `getKeyStyle(attrs: Required<BaseNodeStyleProps>)`  这个方法里面根据不同状态返回样式如何办

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
元素中可以通过 `this.attributes.context.graph` 访问 `Graph` 实例
API：[getElementState](https://g6-next.antv.antgroup.com/api/graph/method#graphgetelementstateid)
