### ISSUE TITLE
一个点连接以后就不能在连接了，有没有相关配置

### ISSUE THREAD

**Issue by itsmyturn** [antvis/g6#59]
![image](https://user-images.githubusercontent.com/11573322/28960813-95dfb4dc-7932-11e7-9d75-322990fea840.png)

**Comment by TomHuangCN** [comment]
暂时没有相关配置，不过下个版本会把锚点的相关的接口抛一下，应该能实现类似需求。

**Comment by itsmyturn** [comment]
嗯，最近会出新版本吗，还有dragedgeend和dragnodeend偶尔会出现拖拽节点结束会混淆到拖拽边结束

**Comment by itsmyturn** [comment]
现在在做相关功能，很期待能出来新版本，api也更新了

**Comment by TomHuangCN** [comment]
按理不会呀， 不过 dragnodeend 这个事件应该没有抛吧

**Comment by itsmyturn** [comment]
![image](https://user-images.githubusercontent.com/11573322/29019728-0bd211e2-7b92-11e7-86ee-0c9b3bd89b46.png)

**Comment by TomHuangCN** [comment]
dragnodeend 没发布不要使用。 dragedgeend 会在拖动边端点后触发
