### ISSUE TITLE
How to set label by defining node by createNodeFromReact

### ISSUE THREAD

**Issue by eaynait** [antvis/G6#5900]
### Describe the bug / 问题描述

How to set label by defining node through createNodeFromReact

### G6 Version / G6 版本

4.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
Older versions are no longer supported. Please use @antv/g6-extension-react

**Comment by eaynait** [comment]
Can you share some documentation or tutorials? I can't find any on the official website.

**Comment by eaynait** [comment]
> Older versions are no longer supported. Please use @antv/g6-extension-react

Can you share some documentation or tutorials? I can't find any on the official website.
