### ISSUE TITLE
h5 安卓下正常，ios环境下边位置错乱（脑图，svg渲染，dom自定义节点），请问是什么原因造成的，版本：4.8.24

### ISSUE THREAD

**Issue by yangguanglei** [antvis/G6#5905]
![微信图片_20240620160150](https://github.com/antvis/G6/assets/43629261/95d3d7e6-4cd6-4c9e-be30-f184a6d491fb)

**Comment by Aarebecca** [comment]
自定义的节点需要调整位置，添加 `x: width/2, y: height/2`
