### ISSUE TITLE
[V5] typescript EdgeData和NodeData 提供泛型

### ISSUE THREAD

**Issue by mioxs** [antvis/G6#5909]
EdgeData和NodeData 应提供style和data泛型保证数据类型一致。

**Comment by Aarebecca** [comment]
可以提供以下你的使用示例吗，我们正在评估给包括数据及API提供范型的形式

**Comment by mioxs** [comment]
![IMG_20240621_102115_edit_2530066147060294.jpg](https://github.com/antvis/G6/assets/49021590/ed4c6192-808f-4148-9275-27fb31af3fe3)

![IMG_20240621_102301_edit_2530173197586319.jpg](https://github.com/antvis/G6/assets/49021590/b291c550-cd35-4b1e-bb87-a91380773436)

**Comment by mioxs** [comment]
主要是通过graph.getNodeData和graph.getEdgeData返回指定类型也应提供泛型

**Comment by Aarebecca** [comment]
在最初版的实现中其实我们采用了类似的泛型设计，不过后来简化了，我们后续会评估重新加上泛型的必要性

**Comment by zzjjbbaa** [comment]
![image](https://github.com/antvis/G6/assets/54572770/d95d62e5-a010-4987-9f2d-acae46729b69)
我觉得这样更方便吧，还不用每个地方去传泛型类型

**Comment by Aarebecca** [comment]
> ![image](https://private-user-images.githubusercontent.com/54572770/342194836-d95d62e5-a010-4987-9f2d-acae46729b69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMTA0OTUsIm5iZiI6MTcxOTIxMDE5NSwicGF0aCI6Ii81NDU3Mjc3MC8zNDIxOTQ4MzYtZDk1ZDYyZTUtYTAxMC00OTg3LTlmMmQtYWNhZTQ2NzI5YjY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDA2MjMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3N2YyNjJjYTZhZTcxOTVkNGNhOWIyMDYxNGY2ZmJiMTViYzNmNjNjMDI1YjVmYmE4YzViOTljMTRiNzcwZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9kCVWoHSHxVQcc0gueQNaPtdVzJrI9-DZyPJVNVCBFM) 我觉得这样更方便吧，还不用每个地方去传泛型类型

这也不失为一种解决方式，正式版没有加上泛型的主要原因就是以为需要传泛型的地方太多了，会比较繁琐

**Comment by mioxs** [comment]
这不是必须项，可以通过extends Omit 重新自定义属性，
如果类型包含[key：string]：unknown Omit会过滤所以属性。

![IMG_20240625_095727_edit_2748375501093649.jpg](https://github.com/antvis/G6/assets/49021590/22a758c8-1a88-4818-9d50-401b7a5713d5)
