### ISSUE TITLE
G6是否支持自定义组合布局

### ISSUE THREAD

**Issue by WangHanZ** [antvis/G6#5911]
### Describe the bug / 问题描述

数据中存在combo的情况下希望可以自定义组合布局达到combo 不展开的时候combo的位置不根据combo内部节点来计算的效果

### G6 Version / G6 版本

4.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
见：https://g6.antv.antgroup.com/api/graph-layout/combo-combined
