### ISSUE TITLE
G6可以在label这里再画条线出来么？

### ISSUE THREAD

**Issue by luoandy** [antvis/g6#592]
* **G6 Version**:g6-2.2.0
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:
![image](https://user-images.githubusercontent.com/20121275/50883244-7bcd3380-1422-11e9-9cd0-2f7f90ba7097.png)

**Comment by sparkle777** [comment]
可以考虑用guide实现

**Comment by guozhaolong** [comment]
这个你重写draw就可以啊，随便加图形
