### ISSUE TITLE
graph的鼠标事件前缀只能是node，edge，group，guide这四个吗

### ISSUE THREAD

**Issue by mengayng** [antvis/g6#593]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by mengayng** [comment]
我前缀写成anchor:mouseenter,但是没有起作用。

**Comment by dxq613** [comment]
目前是的， anchor 没有实现成单个 Item ,所以不会触发这个事件。关注 3.0 ，这个在3.0 中正在讨论和实现。
