### ISSUE TITLE
[V5] create-dege 无法获取具体子元素

### ISSUE THREAD

**Issue by mioxs** [antvis/G6#5931]
create-edge和drag-element事件target和originalTgarget无法获取具体子图形

**Comment by mioxs** [comment]
> v4使用示例
> ![IMG_20240625_153326_edit_2767027430159553.jpg](https://github.com/antvis/G6/assets/49021590/43541ad9-caf8-49cf-a2a2-817b74147278)
> 
> v5版本create-edge无法获取具体子元素，没有shouldEnd功能
![IMG_20240625_154100_edit_2767496389781356.jpg](https://github.com/antvis/G6/assets/49021590/4fcbc670-f4b3-4b6b-8f66-b5db161a9078)


> 
>

**Comment by zzjjbbaa** [comment]
我猜你想要的是这个 #5619

**Comment by mioxs** [comment]
差不多的问题，目前v4迁移就差这一块。
