### ISSUE TITLE
[V5]build时tsc报错

### ISSUE THREAD

**Issue by Fly-Potato** [antvis/G6#5932]
### Describe the bug / 问题描述

版本：5.0.4
运行npm run build 报错，build失败
使用npm run dev 运行时无异常
tsconfig是默认设置

![image](https://github.com/antvis/G6/assets/25278365/9db583a1-2294-4205-92f4-93cd35ffe0c7)
![image](https://github.com/antvis/G6/assets/25278365/c574b09e-c95b-4ae0-9863-3c4043f4ab03)

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Linux

### Browser / 浏览器

Edge

**Comment by Fly-Potato** [comment]
tsconfig
```json
{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,

    /* Bundler mode */
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",

    /* Linting */
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true,
    "baseUrl": ".",
    "paths": {
      "@/*": [
        "./src/*"
      ]
    }
  },
  "include": ["src"],
  "references": [{ "path": "./tsconfig.node.json" }]
}
```

**Comment by Aarebecca** [comment]
在 "compilerOptions" 下加入下列配置：

```json
"experimentalDecorators": true,
```

**Comment by Fly-Potato** [comment]
> 在 "compilerOptions" 下加入下列配置：
> 
> ```json
> "experimentalDecorators": true,
> ```
> 
> 移除
> 
> ```json
> "noUnusedLocals": true,
> "noUnusedParameters": true,
> ```
> 
> 建议使用 eslint

谢谢，我照做了，但还有3个报错
![image](https://github.com/antvis/G6/assets/25278365/82f7ec3a-84de-4d8f-896d-db14d8bfcb72)

**Comment by mioxs** [comment]
skipLibCheck打包应该会不检查库

**Comment by Fly-Potato** [comment]
已解决
