### ISSUE TITLE
【v5】g6 v5.0.1版本 如何获取画布元素高度，重置画布大小

### ISSUE THREAD

**Issue by Nancy2013** [antvis/G6#5938]
afterlayout 要在 render 之前调用。否则 render 中布局已经执行完了才绑上监听就会监听不到。
```
graph.on('afterlayout', () => {
const group = graph.get('group');
const box = group.getCanvasBBox();
graph.changeSize(box.width, box.height);
})
```

在g6 v5.0.1版本中，使用graph.get('group')方法，提示方法不存在，如何获取画布内容元素的全部高度，重置画布大小

**Comment by Aarebecca** [comment]
获取画布内容宽高：`graph.getCanvas().getBounds()`
获取视口尺寸：`graph.getSize()`
