### ISSUE TITLE
缩小后，调用fitView或fitCenter 效果不正确

### ISSUE THREAD

**Issue by zhangsai521314** [antvis/G6#5943]
### Describe the bug / 问题描述

缩小画布后再多次点击fitView和fitCenter得不到想要的效果，节点元素会飞出画布外面

### Reproduction link / 重现链接

https://stackblitz.com/edit/react-t3qewq?file=index.js

### Steps to Reproduce the Bug or Issue / 重现步骤

1：使用鼠标缩小画布2次
2：点击fitCenter2次
3：点击fitView1次
4：点击fitCenter1次，无效果。

另外也缩放后随机点击fitCenter和fitView测试效果

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Firefox

**Comment by Aarebecca** [comment]
初步分析应该是视口动画导致异常
