### ISSUE TITLE
浏览器中执行耗时问题

### ISSUE THREAD

**Issue by qiugongkai** [antvis/G6#5944]
### Describe the bug / 问题描述

我们在做鸿蒙系统下浏览器执行耗时分析，想了解一下性能大数量分类中的三个图，主要执行耗时点在哪里？
![image](https://github.com/antvis/G6/assets/17262504/243e8a00-8536-4ed7-ac1e-91797f110550)
我们在Windows下抓了一个js执行图，但是有一些函数被匿名

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
这部分是底层渲染引擎的逻辑，具体见：https://github.com/antvis/g

**Comment by qiugongkai** [comment]
我们发现会调用大量的这样函数，请问这里是调用了哪些浏览器渲染引擎的接口？
![image](https://github.com/antvis/G6/assets/17262504/0b17ef28-331f-4a34-982b-2d7081ff9ce7)
