### ISSUE TITLE
[v5] layout 方法报不存在

### ISSUE THREAD

**Issue by liseri** [antvis/G6#5945]
### Describe the bug / 问题描述

1. 需求或目的：想不渲染只执行布局，从而通过getData()方法获取布局后的x,y坐标
2. 述求：实现只布局不渲染，通过getData()方法获取布局后的x,y坐标
3. 图表例子链接： https://g6-next.antv.antgroup.com/zh/examples/layout/dagre/#antv-dagre-combo
4. 文档链接： https://g6-next.antv.antgroup.com/api/graph/method#graphlayout
5. 版本：v5.0
6. 问题描述：graph.layout()方法报方法找不到
7. 问题截图：
![image](https://github.com/antvis/G6/assets/2908276/31a6a353-89d6-42cc-9643-c3cc64915251)

### Reproduction link / 重现链接

https://g6-next.antv.antgroup.com/zh/examples/layout/dagre/#antv-dagre-combo

### Steps to Reproduce the Bug or Issue / 重现步骤

- https://g6-next.antv.antgroup.com/zh/examples/layout/dagre/#antv-dagre-combo
- 修改graph.render()为 graph.layout()， 其它的都没有改

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
如果你只想获取布局结果，建议直接使用 `@antv/layout`

**Comment by hsingh-ds** [comment]
@liseri try to call layout inside a timeout function with 100ms delay.
