### ISSUE TITLE
V5 给node添加一个角度 则连接桩的点会径向往外移动

### ISSUE THREAD

**Issue by hh1412** [antvis/G6#5946]
### Describe the bug / 问题描述

V5 给node添加一个角度 则连接桩的点会径向往外移动
浏览器版本 chrome 126.0.6478.116（正式版本） （64 位）
操作系统win10 64位

### Reproduction link / 重现链接

https://g6-next.antv.antgroup.com/examples/element/node/#port

### Steps to Reproduce the Bug or Issue / 重现步骤

打开https://g6-next.antv.antgroup.com/examples/element/node/#port
![image](https://github.com/antvis/G6/assets/100757902/6f6a5412-c551-4c02-9594-922ef9f6c1bf)
在19行处增加2行代码
portR: 3,
transform: 'rotate(45deg)'

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by hh1412** [comment]
可能跟 https://github.com/antvis/G6/issues/5781#issue-2322519581 有关系

**Comment by Aarebecca** [comment]
> 可能跟 [#5781 (comment)](https://github.com/antvis/G6/issues/5781#issue-2322519581) 有关系

这两者是不同的原因导致的。后面会排查修复

**Comment by mioxs** [comment]
暂时可以通过portTransform反向旋转。
