### ISSUE TITLE
G6支持更新节点的图形属性吗，怎么更新自定义的节点图片logo？

### ISSUE THREAD

**Issue by wangzhixin445** [antvis/g6#595]
// 状态 logo
          group.addShape('image', {
            attrs: {
                x: 150+200,
                y: 150,
                img: 'https://zos.alipayobjects.com/rmsportal/FDWrsEmamcNvtEf.png'
            }
          });
注册节点后，怎么能动态更新img的路径呢？graph.update能实现吗

**Comment by awebird** [comment]
可以参考我的这个issue, 给shape加id，后面用的时候getGraphicGroup，然后findById再设置attr https://github.com/antvis/g6/issues/555

**Comment by wangzhixin445** [comment]
> 可以参考我的这个issue, 给shape加id，后面用的时候getGraphicGroup，然后findById再设置attr #555

好的，我试下，感谢回复！
