### ISSUE TITLE
dagre布局问题

### ISSUE THREAD

**Issue by WKingIce** [antvis/G6#5950]
使用dagre布局后，拖拽画布中的节点后，改变布局位置了，此时，点击按钮添加节点，可以在保持原先布局的情况下，将节点还是通过dagre布局添加到画布中吗？

**Comment by Aarebecca** [comment]
描述需求只能通过自定义布局实现，布局前先记录拖拽节点的位置，然后执行 dagre 布局，并根据布局结果仅调整未拖拽以及新增节点的位置
