### ISSUE TITLE
[v5] behaviors [collapse-expand] 报错

### ISSUE THREAD

**Issue by liseri** [antvis/G6#5951]
### Describe the bug / 问题描述

1. 图表示例：https://g6-next.antv.antgroup.com/zh/examples/layout/dagre/#antv-dagre-combo
2. 版本：v5
3. 问题描述：示子中增加 behaviors [collapse-expand] ，双击A combo时 报错，如下图：

![image](https://github.com/antvis/G6/assets/2908276/447b2dde-7246-4c99-8889-ddbf2979a96d)

### Reproduction link / 重现链接

https://g6-next.antv.antgroup.com/zh/examples/layout/dagre/#antv-dagre-combo

### Steps to Reproduce the Bug or Issue / 重现步骤

1. 代码中添加 behaviors [collapse-expand]
2. 双击 A combo
3. 报错

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
问题原因已定位，会尽快修复
