### ISSUE TITLE
polyline 连接线不正确的问题

### ISSUE THREAD

**Issue by ProsperLee** [antvis/G6#5952]
### Describe the bug / 问题描述

![image](https://github.com/antvis/G6/assets/37255760/19159d9a-a224-42ad-a367-ea2a83653f54)

polyline 连接线不正确的问题

【期望连接形式】

![image](https://github.com/antvis/G6/assets/37255760/ed4d5ad1-3586-4630-993f-dd1fb0241f2d)

### Steps to Reproduce the Bug or Issue / 重现步骤

```
node: {
  style: {
      size: [240, isDetail ? (550 - 100) : 150],
      type: 'tree-node',
      component: (data: never) => <TreeNode data={data} theme={theme} isDetail={isDetail} openCV={openCV}/>,
      port: true,
      ports: [{placement: 'top'}, {placement: 'bottom'}],
  },
},
edge: {
    type: 'polyline',
    style: {
        stroke: theme === 'dark' ? '#595959' : '#D9D9D9',
        lineWidth: 1,
        router: true,
        routerPadding: 0,
    }
},
```

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
麻烦提供一个复现链接
