### ISSUE TITLE
[v5]无法复现4.8.1中的comboCombined布局效果

### ISSUE THREAD

**Issue by liseri** [antvis/G6#5953]
### Describe the bug / 问题描述

1. v5.0的示例： https://g6-next.antv.antgroup.com/zh/examples/layout/combo-layout/#combo-combined
2. v4.8的示例： https://g6.antv.antgroup.com/zh/examples/net/comboLayout#comboCombined
3. 述求：想在5.0中复现4.8的布局效果， 但有差异，5.0中两combo有重叠，如下图：
![image](https://github.com/antvis/G6/assets/2908276/607caf2e-331e-4544-8550-0dedfbb33235)

### Reproduction link / 重现链接

https://g6-next.antv.antgroup.com/zh/examples/layout/combo-layout/#combo-combined

### Steps to Reproduce the Bug or Issue / 重现步骤

1. 打开v4.8的示例：https://g6.antv.antgroup.com/zh/examples/net/comboLayout#comboCombined ，不做任何代码修改
2. 打开v5.0的示例：https://g6-next.antv.antgroup.com/zh/examples/layout/combo-layout/#combo-combined
3. 在5.0的示例代码中 添加 outerLayout 设置，如上图
4. 两者的combo效果有差异

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
下半年我们会重新实现一版 Combo Combined 在 G6 5.0 中使用
