### ISSUE TITLE
[V5] 自定义元素如何设置子元素id和name

### ISSUE THREAD

**Issue by mioxs** [antvis/G6#5963]
![IMG_20240701_170136_edit_3134977287843512.jpg](https://github.com/antvis/G6/assets/49021590/041b1f4b-f9ff-462b-bf14-1559eaa71510)

upsert无法设置id

**Comment by rtpacks** [comment]
你好，请问你解决这个问题了吗？文档好像没提到怎么设置自定义元素的id，只有 nodes 数据才能显示指定

**Comment by mivui** [comment]
> 你好，请问你解决这个问题了吗？文档好像没提到怎么设置自定义元素的id，只有 nodes 数据才能显示指定

通过子元素获取根节点数据
