### ISSUE TITLE
【V5】事件处理陷入无限循环，导致页面假死

### ISSUE THREAD

**Issue by wulianpu** [antvis/G6#5964]
事件处理代码见：https://github.com/antvis/G/blob/ffdef423496adc3b663f9fa3eb70da53d76931d0/packages/g-lite/src/services/EventService.ts#L386-L400
~~~ js
while (leaveEvent.target &&!e.composedPath().includes(leaveEvent.target)) {
  leaveEvent.currentTarget = leaveEvent.target;

  this.notifyTarget(leaveEvent);
  if (isMouse) {
    this.notifyTarget(leaveEvent, 'mouseleave');
  }

  if (Node.isNode(leaveEvent.target)) {
    leaveEvent.target = leaveEvent.target.parentNode;
  }
}
~~~
如果 `leaveEvent.target` 不是Node，就会导致一直在循环

**Comment by Aarebecca** [comment]
反馈的问题在 G6 中有所体现吗

**Comment by wulianpu** [comment]
> 反馈的问题在 G6 中有所体现吗

有的，我之前试过用最小代码来复现，但一直没成功...

**Comment by Aarebecca** [comment]
麻烦提供一个复现 demo 呢

**Comment by wulianpu** [comment]
> 麻烦提供一个复现 demo 呢

https://codesandbox.io/p/devbox/g6-demo-vue3-9w9pjz

**Comment by Aarebecca** [comment]
问题出现在底层渲染引擎的事件系统，可能需要到对应的仓库提下 issue：https://github.com/antvis/g

**Comment by Aarebecca** [comment]
transfer to: https://github.com/antvis/G/issues/1725
