### ISSUE TITLE
ContextMenu 在使用getContent构建菜单内容时，内容为追加，而非将菜单清空后构建。

### ISSUE THREAD

**Issue by Nciae-Zyh** [antvis/G6#5965]
### Describe the bug / 问题描述

ContextMenu 在使用getContent构建菜单内容时，内容为追加，而非将菜单清空后构建。通过研究源码发现贵方在[@antv/g6/src/plugins/contextmenu/index.ts,128-132]代码如下
    if (content instanceof HTMLElement) {
      this.$element.appendChild(content);
    } else {
      this.$element.innerHTML = content;
    }
显示为若返回HTMLElement类型，则是追加子元素而非重新渲染。是否是我使用的不规范。或者是说有其他方法可以我需要的自定义菜单。

### Steps to Reproduce the Bug or Issue / 重现步骤

将getContent设置为handleContextMenu，渲染出多个不同的Node，通过在Node节点间点击，则可以实现重复渲染。

const handleContextMenu = async (event: IElementEvent) => {
  // 创建一个临时的 div 元素
  const tempDiv = document.createElement('div');

  // 创建一个 Vue 应用实例并挂载到临时的 div 元素上
  const app = createApp({
    render() {
      return h('div', '123');
    }
  });

  app.mount(tempDiv);
  // 返回包含已渲染组件的 div
  return tempDiv;
}，
1.
![image](https://github.com/antvis/G6/assets/75648776/62bfc1fe-bc63-4686-ba69-5c6ae62bb6f9)
2.
![image](https://github.com/antvis/G6/assets/75648776/34c8f0d7-1d5a-480d-b020-fdf2111ed8bc)
3.
![image](https://github.com/antvis/G6/assets/75648776/02b6e6ee-3877-490f-9a68-dfb1f5908b7a)

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Linux

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
我看了下，确实是实现上有问题，这边会尽快修复
