### ISSUE TITLE
V5 在vue2.x项目内，升级g6版本到5.0.4时启动报错

### ISSUE THREAD

**Issue by xiaoSS-developer** [antvis/G6#5967]
### Describe the bug / 问题描述

想把项目中的g6版本从4.8.*升级到5.0.4，但启动一直报错。希望能得到解答，谢谢。
node版本：16.13.0
vue版本：2.15.4

### Steps to Reproduce the Bug or Issue / 重现步骤

本地package.json：
[package.json](https://github.com/user-attachments/files/16061077/package.json)
报错日志：
![Uploading image.png…]()

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by JishuaiWang** [comment]
@xiaoSS-developer 请问最后如何解决了？
