### ISSUE TITLE
v4 版本存在内存泄露

### ISSUE THREAD

**Issue by cccRaim** [antvis/G6#5970]
https://github.com/antvis/G6/blob/ab461c1e27681c7a9db0966470f0ba172f93a474/packages/core/src/behavior/behaviorOption.ts#L58
![image](https://github.com/antvis/G6/assets/7681138/2de70e00-0c19-4d93-b0d6-d0fec13106b6)

卸载后没有移除事件监听，this一直存在对Graph的引用，导致内存泄露。
影响：在图很大的时候，反复卸载会导致内存持续上升，如页面内存占用3G+等，内存GC会造成CPU负担，导致整体页面性能下降。

期望：
- 在unmount的时候移除该监听器

**Comment by Aarebecca** [comment]
有兴趣提个 PR 修复该问题吗

**Comment by cccRaim** [comment]
> 有兴趣提个 PR 修复该问题吗

应该提到哪个分支？

**Comment by Aarebecca** [comment]
> > 有兴趣提个 PR 修复该问题吗
> 
> 应该提到哪个分支？

提到 master 分支即可～

**Comment by cccRaim** [comment]
> > > 有兴趣提个 PR 修复该问题吗
> > 
> > 
> > 应该提到哪个分支？
> 
> 提到 master 分支即可～

看了一下，Behavior影响的地方有点多，不敢乱改
