### ISSUE TITLE
力导向图网格效果，多次点击播放越来越慢

### ISSUE THREAD

**Issue by guapizyq** [antvis/G6#5971]
### Describe the bug / 问题描述

随着执行次数增加，JS调用绘制函数调用onclick次数增加，导致耗时增加 越来越卡

### Reproduction link / 重现链接

https://g6-next.antv.antgroup.com/zh/examples/layout/force-directed/#mesh

### Steps to Reproduce the Bug or Issue / 重现步骤

多次点击右侧执行代码，网格展开速度越来越慢

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

### Additional context / 补充说明

同上

**Comment by guapizyq** [comment]
![image](https://github.com/antvis/G6/assets/31994565/52731a85-4af2-4480-852f-c52dd7a0db36)

**Comment by Aarebecca** [comment]
官网运行重播按钮非真实使用环境，本地开发不存在该问题
