### ISSUE TITLE
G6 文档 图布局 Graph Layout 部分出现单词错误

### ISSUE THREAD

**Issue by NidhoggDJoking** [antvis/G6#5977]
### Describe the bug / 问题描述

[文档编写单词错误](https://g6.antv.antgroup.com/api/graph-layout/grid)
![1720001359629](https://github.com/antvis/G6/assets/38490462/2b291923-00a9-436a-b716-5fc8f5f34ff5)

### Reproduction link / 重现链接

https://g6.antv.antgroup.com/api/graph-layout/grid

### Steps to Reproduce the Bug or Issue / 重现步骤

文档单词还是注意下，不然直接复制一部分代码调试半天才发现复制的字段有问题

这个还是个历史问题哦

https://github.com/antvis/G6/issues/3588
![1720001714517](https://github.com/antvis/G6/assets/38490462/e7bbf350-6fe1-4d5b-9269-98e7fd325524)

### G6 Version / G6 版本

4.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by hustcc** [comment]
感谢提醒，有兴趣来一个提交直接改掉吗？

**Comment by NidhoggDJoking** [comment]
> 感谢提醒，有兴趣来一个提交直接改掉吗？

https://github.com/antvis/G6/pull/5982/files
