### ISSUE TITLE
[v5] v4 版本中 dagre 指定层级的属性 layer 被移除了，v5 中有替代方案吗？

### ISSUE THREAD

**Issue by xiongchengqing** [antvis/G6#5989]
### Describe the bug / 问题描述

[v5] v4 版本中 dagre 指定层级的属性 layer 被移除了，v5 中有替代方案吗？

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
V5 中 antv-dagre 为原 4.x dagre

**Comment by xiongchengqing** [comment]
> V5 中 antv-dagre 为原 4.x dagre
但是在 node 或 combo 中设置了 layer 并不起作用呢

**Comment by seifenk** [comment]
> > V5 中 antv-dagre 为原 4.x dagre
> > 但是在 node 或 combo 中设置了 layer 并不起作用呢

解决了吗

**Comment by seifenk** [comment]
> > V5 中 antv-dagre 为原 4.x dagre
> > 但是在 node 或 combo 中设置了 layer 并不起作用呢

测试了起作用
