### ISSUE TITLE
【V5】tooltip 移出节点后未隐藏

### ISSUE THREAD

**Issue by MusicTen** [antvis/G6#5995]
### Describe the bug / 问题描述

存在 combo 时，设置 enable 判断 node 时启用 tooltip。鼠标移入能展示，移出时未主动隐藏。

### Reproduction link / 重现链接

https://stackblitz.com/edit/react-djypq8?file=index.js

#### 1.data
设置 combos 数据
#### 2.plugins
判断节点启用 tooltip，`enable: (event) => event.targetType === 'node'`
#### 3.复现问题
鼠标移入展示 tooltip，移出时未主动隐藏

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
```ts
enable: (event) =>
        event.targetType === 'node' || event.targetType === 'canvas'
```

**Comment by MusicTen** [comment]
> ```ts
> enable: (event) =>
>         event.targetType === 'node' || event.targetType === 'canvas'
> ```

这样只能解决鼠标移入空白画布时，tooltip被隐藏，在鼠标移出node在combo内部时，tooltip依旧还展示

**Comment by lhuazai** [comment]
> > ```ts
> > enable: (event) =>
> >         event.targetType === 'node' || event.targetType === 'canvas'
> > ```
> 
> 这样只能解决鼠标移入空白画布时，tooltip被隐藏，在鼠标移出node在combo内部时，tooltip依旧还展示

遇到同样的问题，解决了吗

**Comment by lessonli** [comment]
加1 解决了吗

**Comment by zmm2015** [comment]
加1 解决了吗
