### ISSUE TITLE
zoom-canvas失效

### ISSUE THREAD

**Issue by Aolef** [antvis/G6#5996]
### Describe the bug / 问题描述

同时支持drag-canvas和zoom-canvas交互，点击某个实体节点后接着进行微信截图，截图后zoom-canvas失效，官网示例便能复现

### Reproduction link / 重现链接

https://g6-next.antv.antgroup.com/zh/examples/layout/mindmap#right-side

### Steps to Reproduce the Bug or Issue / 重现步骤

点击某个节点，后立即进行微信截图或其他使浏览器失去焦点的事件，再回到浏览器，zoom-canvas失效

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
问题已经收集复现，会尽快修复
