### ISSUE TITLE
[v5] toDataURL 导出图片的背景不能设置，固定为白色

### ISSUE THREAD

**Issue by zzjjbbaa** [antvis/G6#5998]
### Describe the bug / 问题描述

![image](https://github.com/antvis/G6/assets/54572770/7d16fadc-21c3-4bc6-81e4-60d7b3c6268d)
希望可以像v4版本一样，可以自定义导出图片的背景色。

### Reproduction link / 重现链接

https://stackblitz.com/edit/react-fvxok2?file=index.js

### Steps to Reproduce the Bug or Issue / 重现步骤

无

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS, Windows, Linux, Others / 其他

### Browser / 浏览器

Chrome, Edge

### Additional context / 补充说明

无

**Comment by Aarebecca** [comment]
导出背景图片需要设置到 background 上

**Comment by zzjjbbaa** [comment]
> 导出背景图片需要设置到 background 上



> 导出背景图片需要设置到 background 上

👍👍👍
