### ISSUE TITLE
能否将节点的文本编辑功能实现提前

### ISSUE THREAD

**Issue by zjsxfly** [antvis/g6#6]
现有关系图在文字编辑上面实现比较麻烦，而且没有官方的统一设计方案或接口，是否可以将此功能提前，谢谢。

**Comment by TomHuangCN** [comment]
会将该需求优先级提前，实现了会通知你。

**Comment by zjsxfly** [comment]
@TomHuangCN 能否告知大概的时间段，比如按月按季度都可以

**Comment by TomHuangCN** [comment]
3月中旬

**Comment by TomHuangCN** [comment]
这个功能内部讨论后，暂时不集成到框架内。暂时在外部实现，3月底 G6 1.0 在发布时会附上相应的Demo

**Comment by zjsxfly** [comment]
@TomHuangCN 那外部是不是不能使用，还是通过demo可以实现相应功能。

**Comment by TomHuangCN** [comment]
通过demo实现

**Comment by TomHuangCN** [comment]
外部实现可参考这个 demo

https://antv.alipay.com/g6/demo/02-tree/mind.html
