### ISSUE TITLE
树图在编辑内容的问题

### ISSUE THREAD

**Issue by xiaohuangor** [antvis/G6#6000]
![image](https://github.com/antvis/G6/assets/67271329/eac91c5f-83a0-4064-a7d5-740e4eedfb36)
当前编辑的div是用的定位，当我输入过多内容时，如何让底下的蓝色区域内容高度根据输入的内容做变更，还有与其他元素之间的间距也有所改变

**Comment by Aarebecca** [comment]
1. 监听 div 事件，然后更新节点高度（不推荐，因为可能会影响布局）
2. 更好的方式是为 div 容器设置滚动
