### ISSUE TITLE
toolBar 中的 zoomIn/Out code 语义不符

### ISSUE THREAD

**Issue by Laffery** [antvis/G6#6001]
### Describe the bug / 问题描述

toolbar zoomIn/Out 的语义反了，会对开发者带来困惑

### Reproduction link / 重现链接

https://g6.antv.antgroup.com/examples/tool/toolbar/#toolbar

### Steps to Reproduce the Bug or Issue / 重现步骤

F12 打开 Elements，可以看到放大图标的 code 为 `zoomOut`，行为为放大，而 zoomOut 意为缩小；`zoomIn` 同理

<img width="1493" alt="image" src="https://github.com/antvis/G6/assets/49607541/52bac9f6-e8eb-47d0-bc3e-e1f2016d63b1">

### G6 Version / G6 版本

4.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
有兴趣的话欢迎提个 PR 修正下，G6 4.0 现在官方不对非功能性问题进行修复了，主要精力集中在 5.0
