### ISSUE TITLE
[V5] 版本从5.0.4升级到5.0.5后拖动/缩放画布失效

### ISSUE THREAD

**Issue by Fly-Potato** [antvis/G6#6003]
### Describe the bug / 问题描述

在5.0.4上都运行正常，升级到5.0.5或5.0.6后均出现上述问题，测试了下，事件能触发，但是画布没动

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Edge

**Comment by Aarebecca** [comment]
duplicated with: https://github.com/antvis/G6/issues/5996
正在修复中
