### ISSUE TITLE
官网搜索不可用

### ISSUE THREAD

**Issue by CoolRice** [antvis/G6#6009]
### Describe the bug / 问题描述

http://g6-v3-2.antv.vision/zh/docs/manual/introduction
官网搜索不可用，随便搜什么都显示404

### Steps to Reproduce the Bug or Issue / 重现步骤

进入 http://g6-v3-2.antv.vision/zh/docs/manual/introduction
输入 anch
点击出来的第一个链接

### G6 Version / G6 版本

3.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
3.x 官网已停用，3.x 已停止维护
