### ISSUE TITLE
使用G6 React Node插件时，绑定onMouseEnter事件无法生效

### ISSUE THREAD

**Issue by md-liuxiao** [antvis/G6#6010]
![b99dacd8de7f20909ef8544584b0d6c](https://github.com/antvis/G6/assets/39038828/adbee5c9-c691-4196-b509-e35757fa718d)

**Comment by Aarebecca** [comment]
See: https://github.com/antvis/G/blob/f340e6294300f36afe0bb8211ed5812535b02c3e/packages/react-g/src/types.ts#L27-L59

**Comment by md-liuxiao** [comment]
![12c2e96735f4d5bc4ee6a5d0feb0992](https://github.com/antvis/G6/assets/39038828/1984854a-f63c-40d9-a794-a612ead7a569)
![31dc22203e835e36e827c2d46c3098d](https://github.com/antvis/G6/assets/39038828/66ca2ba3-1b20-4a98-83de-22a0b63cee67)

用onMouseenter绑定事件，还是无法触发
