### ISSUE TITLE
请问继承现有图形，自定义节点后，点击节点时，如何获取数据的id？

### ISSUE THREAD

**Issue by Aolef** [antvis/G6#6012]
### Describe the bug / 问题描述

扩展现有图形，自定义节点后，点击节点时，获取不到数据的id

### Steps to Reproduce the Bug or Issue / 重现步骤

![建图](https://github.com/antvis/G6/assets/27433002/e3a98b71-c0b9-4fbf-a905-5427de214a7d)
![自定义节点](https://github.com/antvis/G6/assets/27433002/5b4ac991-2f87-4c9b-919a-2c1c216e6cad)

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
事件对象： `event.target.id`
元素中：`this.id`

**Comment by Aolef** [comment]
第一张图里， event.target.id拿到的是空字符串，但是应该是有值的，是需要继承的时候做什么操作吗
