### ISSUE TITLE
自定义节点G6.registerNode，在draw函数中打印cfg.x和cfg.y，值是undefined

### ISSUE THREAD

**Issue by md-liuxiao** [antvis/G6#6026]
![1bbf18a4a6fd021a7f4f3e5b439b27a](https://github.com/antvis/G6/assets/39038828/c62d90ae-5d9d-4208-b2a4-2df3497136bb)
![ab7ba335a7866cf90b1f0568cb4b784](https://github.com/antvis/G6/assets/39038828/5125c4ea-a79c-48ca-ad4b-ae49b6fefc5f)

**Comment by Aarebecca** [comment]
这个例子中并没有你提到的问题：
https://codesandbox.io/p/sandbox/busy-khorana-h47hzl?file=%2Fpackage.json

<img width="374" alt="image" src="https://github.com/antvis/G6/assets/25787943/c84cf4a8-c4a6-4567-9ee6-b2d3340c279e">

建议提供线上复现 demo
