### ISSUE TITLE
V5 版本官网中Combo 的流程图 拖拽Combo的时候出现虚影的线条

### ISSUE THREAD

**Issue by yanghui0101** [antvis/G6#6027]
### Describe the bug / 问题描述

![Uploading image.png…]()

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by yanghui0101** [comment]
https://g6-next.antv.antgroup.com/zh/examples/layout/dagre#antv-dagre-combo
![Uploading bug.jpg…]()

**Comment by Aarebecca** [comment]
脏矩形擦除问题，先行通过使用 SVG 渲染器跳过，后续等渲染引擎层修复

**Comment by yanghui0101** [comment]
SVG 渲染器跳过怎么做？ 请问有相关的demo或者api吗
