### ISSUE TITLE
如何恢复被批量更新的自定义节点的样式

### ISSUE THREAD

**Issue by ltdys** [antvis/G6#6028]
### Describe the bug / 问题描述

批量更新自定义节点后（每个自定义节点的样式都是不一样的，比如背景颜色），如何将这些自定义节点的样式(比如背景颜色)都恢复成更新前的样子

### G6 Version / G6 版本

4.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
请详细描述更新过程，并提供相关 demo

**Comment by ltdys** [comment]
找到办法解决了，谢谢
