### ISSUE TITLE
树图TreeGraph首次render时先触发了afterrender事件

### ISSUE THREAD

**Issue by ZTao-z** [antvis/G6#6036]
### Describe the bug / 问题描述

<img width="472" alt="image" src="https://github.com/user-attachments/assets/3c7d9961-5ada-4c8a-9d3e-a29c7b6cf0e1">

树图首次渲染时，clear函数应该传入avoidEmit=true，避免触发 ’afterrender‘ 事件

### G6 Version / G6 版本

4.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
有兴趣提个 PR 修复该问题吗？
