### ISSUE TITLE
文字换行问题

### ISSUE THREAD

**Issue by huliyou** [antvis/g6#604]
1. 给定文字宽度，超出宽度能自动换行。
2. 多个连续\n，能显示多个换行，支持white-spacd: pre。

举例：
例如 text 内容为："超长文字超长文字超长文字↵↵↵\n↵\n↵文字"
希望展示为：
![image](https://user-images.githubusercontent.com/3860373/51089545-f347ed80-17a9-11e9-86a2-770f91b03c80.png)
实际渲染为：
![image](https://user-images.githubusercontent.com/3860373/51089549-ffcc4600-17a9-11e9-9445-ca68034391d9.png)

**Comment by dxq613** [comment]
这一类需求需要自己定义 shape，因为没有一种通用的方式，多个属性之间的优先级判断策略不一致。例如：
* 图形的默认宽度问题，
* 图形是适应文本，还是文本适应图形自动换行
* 文本超出后是自动换行，还是阶段显示省略

等等一系列的权衡，很难放到底层统一处理。我们正在重构 3.0 版本，可能会提供不同 shape 来满足这类需求：
* rect-auto-fit
* rect-text-wrap
* rect-text-overflow
之类的，也可能会按照约定的方式增加配置项，例如：
```js
{
  type: 'custom-rect',
  labelCfg: {
    textOverflow: 'ellipsis'
  }
},
{
 type: 'custom-rect1',
 autoFitLabel: true
}
```
这些功能的实现更多的是以最佳实践的方式呈现。

**Comment by ynztyl10** [comment]
求问下，shape的自适应文本，这个现在有没有最佳实践啊？现在addShape时，需要制定width和height，但是文本过长会出现问题，同时由于制定了x、y坐标，超长之后其他图形的位置也会受到影响
