### ISSUE TITLE
V5.0.9 自定义节点展开 收缩有问题

### ISSUE THREAD

**Issue by PromiseYo** [antvis/G6#6058]
### Describe the bug / 问题描述

收缩之后 点击自定义节点无法展开 线条样式错乱

### Reproduction link / 重现链接

https://stackblitz.com/edit/react-1sfavs-pz8auw?file=index.js

### Steps to Reproduce the Bug or Issue / 重现步骤

先收缩节点 再点击无法展开

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
你的例子是 4.x 的吧

**Comment by PromiseYo** [comment]
> 你的例子是 4.x 的吧
不好意思 是这个
https://stackblitz.com/edit/react-1sfavs-npreny?file=index.js

**Comment by Aarebecca** [comment]
更新至最新版，该问题已解决
