### ISSUE TITLE
树布局中如何在getWidth中获取节点的宽高

### ISSUE THREAD

**Issue by warriorhj** [antvis/G6#6061]
### Describe the bug / 问题描述

在layout初始化当中getWidth方法只能获取如下信息
![image](https://github.com/user-attachments/assets/590032ad-c7fe-40c2-a738-566294f799cf)
我的目的是为了解决自定义节点时，不同节点具有不同宽度，在渲染后不会重叠

### G6 Version / G6 版本

4.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
根据 id 调用 graph api 获取即可

**Comment by warriorhj** [comment]
在初始化树图布局时是无法通过api来得到每个节点的宽高，对于自定义节点，具有不同的宽高，无论是CompactBox和Dendrogram都会存在节点相互遮挡问题
