### ISSUE TITLE
[V5] hover-activate behavior makes expand/collapse combo breaking

### ISSUE THREAD

**Issue by hongwei0417** [antvis/G6#6063]
### Describe the bug / 问题描述

When using `collapse-expand` and `hover-acvitvate` at the same time, triggering the expand/collapse animation will cause an error and prevent other interactions, see below steps.
<img width="1235" alt="image" src="https://github.com/user-attachments/assets/0b7b674c-14cd-4e28-a1dd-73c29b0adb8f">

### Reproduction link / 重现链接

https://g6-next.antv.antgroup.com/zh/examples/element/combo#circle

### Steps to Reproduce the Bug or Issue / 重现步骤

1. Add `collapse-expand` and `hover-activate` behaviors.
2. Double click any combo to trigger collapse or expand.
3. Quick move pointer and hover on element when combo is running animation.

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS, Windows

### Browser / 浏览器

Chrome, Edge, Others / 其他

**Comment by Aarebecca** [comment]
Thank for your feedback, We have reproduced the issue and will fix it soon
