### ISSUE TITLE
[V5]拖动Custom React Node后，连线错乱

### ISSUE THREAD

**Issue by Rey-Wang** [antvis/G6#6066]
### Describe the bug / 问题描述

拖动 Custom React Node,连线的起始位置和结束位置都会错误，我尝试使用了 SVG 和 WebGL 的 renderer 都有这个问题
<img width="901" alt="image" src="https://github.com/user-attachments/assets/975bf0f8-302d-4fd6-af01-0163ccbd68a4">

### Reproduction link / 重现链接

https://codesandbox.io/p/sandbox/antd-g6-react-node-48sr7h

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome, Edge

**Comment by Aarebecca** [comment]
该问题已知，需待后续修复
