### ISSUE TITLE
combocombined布局，innerlayout使用concentric，布局错位

### ISSUE THREAD

**Issue by willysako** [antvis/G6#6069]
### Describe the bug / 问题描述

combocombined布局，innerlayout使用concentric，布局错位

combo父子结构示意：
```javascript
combos: [
  {
    id: "combo-0",
  },
  {
    id: "combo-1",
    parentId: "combo-0",
  },
  {
    id: "combo-2",
    parentId: "combo-1",
  },
],
```
其中combo0的sortby失效，combo1布局错位，相同的sortby未分布到一个同心圆上

### Reproduction link / 重现链接

https://codesandbox.io/p/sandbox/quirky-drake-t47ps6

### G6 Version / G6 版本

4.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by yvonneyx** [comment]
看到数据中有设置 combo 的 fixSize 属性，这意味着 combo 的尺寸不再由其内部元素的布局决定，这也导致了 combo-1 错位。建议根据实际需求选择移除这一属性或调整 concentric 布局参数来解决这个问题。

我们现在将关闭此 issue。如果您后续还有任何疑问或需要进一步的帮助，请随时重新打开它~

**Comment by willysako** [comment]
我在demo中注释了fize，依然存在错位的问题

**Comment by willysako** [comment]
@yvonneyx demo中是最新的代码
