### ISSUE TITLE
【V5】5.0.10 节点内置状态 inactive 切换后 badge 未还原

### ISSUE THREAD

**Issue by MusicTen** [antvis/G6#6072]
### Describe the bug / 问题描述

节点内置状态 inactive 切换后 badge 透明度未恢复正常

### Reproduction link / 重现链接

https://stackblitz.com/edit/react-myhydq?file=index.js

### Steps to Reproduce the Bug or Issue / 重现步骤

1. 点击节点
2. 观察 badge 状态

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by yvonneyx** [comment]
应该是主题配置的节点默认样式中遗漏了 `badgeBackgroundOpacity: 1`。可以通过在 node.style 中手动指定这个属性来解决。另外，有兴趣给 G6 提个 PR 来直接修复这个问题嘛？

**Comment by MusicTen** [comment]
好的
