### ISSUE TITLE
自定义节点，节点上下之间的间距设定为相等的固定值，无效果

### ISSUE THREAD

**Issue by GhostYDFQ** [antvis/G6#6073]
### 浏览器 Chrome

我希望连接线可以不对称，但是上下之间的间距必须是要相同。于是，我设置了节点之间的间距为一个定值。实际上还是不生效的。

 getVGap: function getVGap(d) {
       return 200;
 }

实际上节点之间的上下间距还是大小不一

**Comment by yvonneyx** [comment]
请提供一个可以复现问题的最小案例代码，方便我们定位问题哦~

**Comment by GhostYDFQ** [comment]
首先我的图是一个两层的结构，由左向右。
我选择了   type: 'compactBox' 这个布局

一下是我的自定义节点。首先根节点无所谓，主要是叶子节点
initCustomNode() {
      const that = this;
      G6.registerNode('custom-node', {
        draw(cfg, group) {

          if (cfg.depth === 0) {
            return that.drawRootNode(cfg, group);
          }
          return that.drawOtherNode(cfg, group);
        },
        getAnchorPoints() {
          return [
            [0, 0.5], 
            [0.98, 0.5], 
          ];
        },
      })
    }
    
    
    // 绘制叶子节点。
   drawOtherNode(cfg, group) {
      const width = 220;
      let height = cfg.calcHeight || cfg.height || 134;  // 这里的高度决定了每一个叶子节点的高度是彼此不同的

      const shape = group.addShape('rect', {
        attrs: {
          x: -width / 2,
          y: -height / 2,
          width,
          height,
          fill: 'l(0) 0:#DBF1FF 0.3:#E8F6FF 1:#F6FBFF',
          radius: 8,
          lineWidth: 0,
        },
      });
      return shape;
    }
    
    此后我希望每一个叶子节点与上一个和下一个叶子节点之间的空白部分间距是相等的。我发现此时设置的
    getVGap: function getVGap(d) {
return 200;
}
不生效。仅仅是两个叶子节点之间的连接线的末端上下间距是相等的

**Comment by GhostYDFQ** [comment]
> 请提供一个可以复现问题的最小案例代码，方便我们定位问题哦~



> 请提供一个可以复现问题的最小案例代码，方便我们定位问题哦~

首先，我的需求是一个自左向右的二层树结构。有1个根节点和5 - 8个不定的子节点

**Comment by GhostYDFQ** [comment]
首先我的需求是一个自左向右的树结构，有一个根节点和 5 - 8个不定的子节点。
因此，在布局上我选择了 compactBox 布局的形式。因为根节点本身无所谓。主要是子节点

以下是我的自定义节点
```
initCustomNode() {
   const that = this;
   G6.registerNode('custom-node', {
      draw(cfg, group) {
        if (cfg.depth === 0) {
           return that.drawRootNode(cfg, group);
         }
         return that.drawOtherNode(cfg, group);
      },
       getAnchorPoints() {
          return [
            [0, 0.5], // 左边中心点
            [0.98, 0.5], // 右边中心点
          ];
        },
      })
    },
```

```
drawOtherNode(cfg, group) {
   const width = 220;
   const height = cfg.height; // 这里的每个子节点高度都是不等的
   
   const shape = group.addShape('rect', {
       attrs: {
          x: -width / 2,
          y: -height / 2,
          width,
          height,
          fill: 'l(0) 0:#DBF1FF 0.3:#E8F6FF 1:#F6FBFF',
          radius: 8,
          lineWidth: 0,
       }
   });
    return shape;
}
```
- 然后我设置了垂直间距
```
getVGap: function getVGap(d) {
   return 200;
}
```
结果是这个垂直间距是不生效的

**Comment by GhostYDFQ** [comment]
我的预期是希望子节点上下之间的空白间距为一个定值。但是实际结果却并非如此

**Comment by Aarebecca** [comment]
现有布局暂不支持该诉求，目前仅能通过自定义布局实现
