### ISSUE TITLE
我创建的力导向图，自定义的节点间的连线，起止位置不是从节点周边开始，而是从节点周围的方形位置起止

### ISSUE THREAD

**Issue by jindazhen** [antvis/G6#6076]
### Describe the bug / 问题描述

<img width="267" alt="Snode" src="https://github.com/user-attachments/assets/f62c3f10-106a-4311-9466-9abb0623461c">
![image](https://github.com/user-attachments/assets/0c19514f-7df4-4325-8162-e021325fc218)
这种问题后续会有优化吗，我尝试了使用edgeAnchor 使用函数在registerNode中重置连线的起止位置，但是这个配置的函数中debugger根本没起作用。还有一种anchorPoints使用后连线是从固定的点起止的，不是从节点圆心出发，真个图显得不自然，有方案提供吗

### G6 Version / G6 版本

4.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by jindazhen** [comment]
![image](https://github.com/user-attachments/assets/de44f680-5ce3-47f8-add3-ec8cb647113f)

**Comment by yvonneyx** [comment]
可以通过指定 `anchorPoints: [[0.5, 0.5]]` 使得边连接到节点中心~

我们现在将关闭此 issue。如果您后续还有任何疑问或需要进一步的帮助，请随时重新打开它~
