### ISSUE TITLE
 绘制图片，拖动时出现Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by xconline** [antvis/g6#608]
G6 Version：2.2.6
现象：绘制图片成功，拖动时卡顿并报错
报错如下：
g6.js:7 Uncaught RangeError: Maximum call stack size exceeded
    at t (g6.js:7)
    at t (g6.js:7)
    at t (g6.js:7)
    at t (g6.js:7)
    at t (g6.js:7)
    at t (g6.js:7)
    at t (g6.js:7)
    at t (g6.js:7)
    at t (g6.js:7)
    at t (g6.js:7)
    at t (g6.js:7)

**Comment by xconline** [comment]
draw函数使用错误

**Comment by JeffreyCheungGit** [comment]
版本4.8.24，出现相同的问题！！图片类型
`defaultNode: {
          type: 'image'
        }`
只要节点预设了x，y坐标，拖拽节点时就会报错，应该是递归算法有问题，进入了死循环！
xy坐标如果没有数据，初次渲染就报错内存溢出，代码没有做数据真假判断，健壮性偏低，希望改进

**Comment by JeffreyCheungGit** [comment]
找了两天的虫子，终于找到问题所在了，希望能帮助到相同问题的人，是因为G6没有对参数进行分离，还保留引用关系，导致Vue的遍历函数把整个nodes和edges实例对象遍历了个遍，导致内存溢出，所以在调用Graph.data()方法时，要脱离对象引用关系
`Graph.data(JSON.parse(JSON.stringify(data)))`
data就是要渲染的节点和线
