### ISSUE TITLE
请问这个antv g6 5.0 最低兼容到什么浏览器版本，可以有办法兼容低浏览器版本吗？

### ISSUE THREAD

**Issue by carrotming** [antvis/G6#6083]
### AntV Open Source Contribution Plan（可选/Optional）

- [x] 我同意将这个 Issue 参与 OSCP 计划 / I agree to participate in the OSCP plan

### Issue 类型 / Issue Type

None

**Comment by Aarebecca** [comment]
请使用正确的issue模板，非问题反馈请移至discussion

**Comment by hustcc** [comment]
@carrotming 已经在 https://github.com/antvis/component/pull/319 中解决。

**Comment by carrotming** [comment]
> @carrotming 已经在 [antvis/component#319](https://github.com/antvis/component/pull/319) 中解决。

好的大佬。谢谢大佬们。
