### ISSUE TITLE
是否能实现右键按下拖拽

### ISSUE THREAD

**Issue by STofone** [antvis/G6#6084]
如题，是否能实现仅右键按下拖拽
左键用来框选，右键用来拖拽

**Comment by Aarebecca** [comment]
建议参考内置交互实现，自行注册交互，安装你的需求绑定事件监听

**Comment by STofone** [comment]
> 建议参考内置交互实现，自行注册交互，安装你的需求绑定事件监听

DragCanvas的属性都是private，根本继承不了，难道要从零自己实现拖拽吗？

**Comment by STofone** [comment]
> 建议参考内置交互实现，自行注册交互，安装你的需求绑定事件监听

DragCanvas全是private，根本没法继承

**Comment by STofone** [comment]
直接修改enable，判断event.buttons===2就行了
