### ISSUE TITLE
force2”布局，500节点及以上，自定义布局，给节点加上图片这些，加载贼慢，有时候超过十分钟都加载不出来，经常导致浏览器崩溃，有什么好解决的办法吗

### ISSUE THREAD

**Issue by ali081809** [antvis/G6#6086]
### Describe the bug / 问题描述

force2”布局，500节点及以上，自定义布局，给节点加上图片这些，加载贼慢，有时候超过十分钟都加载不出来，经常导致浏览器崩溃，有什么好解决的办法吗

### G6 Version / G6 版本

4.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by yvonneyx** [comment]
不影响到布局结构的图形可以先隐藏，等布局结束之后再加载？比如说节点上图片、边

**Comment by yvonneyx** [comment]
我们已经对该问题进行了初步调查，并提供了一些建议来解决您遇到的情况。由于目前没有进一步的信息，我们将暂时关闭此问题。如果您在尝试我们的建议后仍然遇到问题，或者有更多的细节可以提供，请随时重新打开此 issue，或者发起一个新的，我们将很乐意进一步协助您 ❤️
