### ISSUE TITLE
v5.0 util如何使用呢

### ISSUE THREAD

**Issue by Pancake-Q** [antvis/G6#6089]
### Describe the bug / 问题描述

v5.0 没找到util的使用说明比如在大规模图下钻式探索的案例中的G6.Util.processParallelEdges(edges, 12.5, 'quadratic', 'custom-line')

### Reproduction link / 重现链接

[大规模图下钻式探索](https://g6.antv.antgroup.com/examples/case/graphDemos/#largeGraph)

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
1. 对于一般[工具方法](https://g6-next.antv.antgroup.com/api/reference/g6#%E5%87%BD%E6%95%B0)，直接从 G6 引入调用即可，以 `idOf` 为例

```ts
import { idOf } from '@antv/g6';

const id = idOf({ source: 'node-1', target: 'node-2' });
```

2. 如果你需要使用平行边，参考案例：https://g6-next.antv.antgroup.com/examples/element/custom-edge/#parallel-edges

**Comment by songxiaoyu321** [comment]
> 1. 对于一般[工具方法](https://g6-next.antv.antgroup.com/api/reference/g6#%E5%87%BD%E6%95%B0)，直接从 G6 引入调用即可，以 `idOf` 为例
> 
> ```ts
> import { idOf } from '@antv/g6';
> 
> const id = idOf({ source: 'node-1', target: 'node-2' });
> ```
> 
> 2. 如果你需要使用平行边，参考案例：https://g6-next.antv.antgroup.com/examples/element/custom-edge/#parallel-edges

请问V5处理平行边如果需要自定义边类型怎么处理呢？
