### ISSUE TITLE
iconClipPath 无效

### ISSUE THREAD

**Issue by abc3660170** [antvis/G6#6098]
### Describe the bug / 问题描述

1. 5.0.10 版本,  nodes[0]->style->iconClipPath中正确了设置了DisplayObject， 不仅不会出现裁切效果，还会导致icon消失

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
clipPath 目前采用的全局坐标系（系底层渲染引擎问题，导致使用有所不便），因此导致 icon 被裁切掉了，后面会优化该问题

**Comment by abc3660170** [comment]
如果是底层渲染引擎问题，那这个会在@antv/g 中优化是吧

**Comment by abc3660170** [comment]
我感觉80%以上的需求通过IconRadius就能解决了，矩形的照片在圆形节点中为裁切的情况下实在是绷不住。
