### ISSUE TITLE
G6布局问题反馈

### ISSUE THREAD

**Issue by GhostYDFQ** [antvis/G6#6099]
###  问题描述

我有一个三层的树结构，最外层的节点高度是不确定的，但是，确定是不相等的，我期望每个最外层节点的间距是相等的。实际上似乎做不到

### 重现链接

https://codesandbox.io/p/sandbox/g6-demo-m4cynn?file=%2Findex.js

###  重现步骤

查看我的实例，我期望蓝色块彼此之间的间距可以是一个定值 getVGap 似乎是做不到的

###  G6 版本

4.x

###  操作系统

Windows

### 浏览器

Chrome

**Comment by Aarebecca** [comment]
目前布局暂无法满足所需效果，建议考虑自定义布局实现

**Comment by GhostYDFQ** [comment]
自定义布局可以实现吗？
我之前有个思路是 根据最外层的最上面的一个为基准，其他节点做偏移。结果发现偏移之后，root 节点 和 中间节点的布局会乱掉。

**Comment by Aarebecca** [comment]
> 自定义布局可以实现吗？ 我之前有个思路是 根据最外层第一个蓝色节点为基准，其他节点做偏移。结果发现偏移之后，root 节点 和 中间节点的布局会乱掉。但是确实可以做到等间距

自定义布局相当于完全由你自己来进行元素排布，如果有能力的话可以考虑这种方式
