### ISSUE TITLE
请问如何对node插入自定义动画

### ISSUE THREAD

**Issue by tengruime** [antvis/g6#610]
我需要一些node的折叠动画，tree无法满足我绘图的要求。node插入动画我在api里面和git上找了几天了，貌似没有看见，请教一下该如何处置。

**Comment by tengruime** [comment]
自己找了下，貌似只能用d3.js。你们的这个g6的资料整理的太简单了。我摸索了好久，你们的学习链不仅仅只有这个不全的g6文档、还有g、然后就是d3。入坑了～还不如用百度的。

**Comment by powerProgrammerMa** [comment]
百度有类似g6-editor这种制作流程图或者脑图的插件吗？可否分享一下
