### ISSUE TITLE
V5 版本 Polyline 自动避障功能最新版被移除

### ISSUE THREAD

**Issue by lvren** [antvis/G6#6105]
### Describe the bug / 问题描述

翻看之前的 ISSUE 和 PR , Polyline 之前版本是支持自动避障的，现在正式版发布之后，发现这个功能被移除了，后续有计划继续支持吗？

PR：https://github.com/antvis/G6/pull/4802
Issue：https://github.com/antvis/G6/issues/5066

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
你好，这个功能后续会排期支持的

**Comment by Aarebecca** [comment]
目前 5.0.16 版本已经支持
