### ISSUE TITLE
【V5】html 类型节点缩放画布后，拖动节点展示异常

### ISSUE THREAD

**Issue by MusicTen** [antvis/G6#6106]
### Describe the bug / 问题描述

![image](https://github.com/user-attachments/assets/6cfe075c-b284-451a-99b5-abf282b874c6)

### Reproduction link / 重现链接

https://stackblitz.com/edit/react-zu8p31?file=index.js

### Steps to Reproduce the Bug or Issue / 重现步骤

1. 配置一个 html 类型节点
2. 设置画布可缩放
3. 缩放画布，拖动该节点
4. 节点展示区域变小，被隐藏

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome, Edge

### Additional context / 补充说明

g-canvas-camera 缩放 transform 计算偏差导致

**Comment by Aarebecca** [comment]
与 https://github.com/antvis/G6/issues/5781 描述为同一问题，确实是 g 相机缩放导致的

**Comment by Aarebecca** [comment]
最新版本该问题已修复
