### ISSUE TITLE
【建议】Tooltip 插件增加异步渲染的支持

### ISSUE THREAD

**Issue by zmbxy** [antvis/G6#6111]
### Describe the bug / 问题描述

我搜索了一下，发现最早提出该问题是在2022年，但有两个类似的issue都被关闭了。

我觉得这个异步的支持的需求，还是很常见的，直接关闭不是很合适，还是希望可以考虑增加该特性，能够更灵活的定制显示内容。

### G6 Version / G6 版本

4.x

### Operating System / 操作系统

macOS, Windows

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
目前 G6 4.x 已停止维护，仅对严重问题进行修复。如果有需要，我们欢迎社区开发者参与维护。
我们目前的开发重心在新版 G6 5.0 中，我们关注你的诉求，会在 5.0 中支持相关异步渲染的特性。
