### ISSUE TITLE
Node的Icon图标类型无法切换

### ISSUE THREAD

**Issue by abc3660170** [antvis/G6#6123]
### Describe the bug / 问题描述

如果在初始化Node的Icon类型是iconText，使用updateNodeData([{ iconText: undefined, iconSrc: 图片流URL}])无法生效。目前为了实现此功能我先移除此节点再重新创建。

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

### Additional context / 补充说明

使用场景：我有一批欧洲文艺复兴时期的画家的数据节点，节点数据只包含姓名，艺术家的照片我就使用iconfont上半身字体图标代替，节点右键菜单中有“获取wiki照片”可以获取维基百科照片的功能。

**Comment by Aarebecca** [comment]
如果更新单个节点的样式属性， `updateNodeData` 更新时需要指定数据 id

**Comment by abc3660170** [comment]
> 如果更新单个节点的样式属性， `updateNodeData` 更新时需要指定数据 id

是指定了id的，不然ts类型推导都不会通过的，可能我上面描述的不够清楚

**Comment by abc3660170** [comment]
我可以更新iconText为其他图标，就是不能通过update关掉iconText。
我没有研究过源码，我猜测 iconText 和 iconSrc是互斥生效且iconText优先级高于iconSrc，iconText不能重新更新为undefined，那么iconSrc就不能生效（我猜的

**Comment by Aarebecca** [comment]
> 我可以更新iconText为其他图标，就是不能通过update关掉iconText。 我没有研究过源码，我猜测 iconText 和 iconSrc是互斥生效且iconText优先级高于iconSrc，iconText不能更新为undefined，那么iconSrc就不能生效（我猜的

如果指定了 `iconSrc` 的话，就会作为图片图标，其优先级高于 `iconText`。对于这两个属性而已，当你不需要使用时，可以将其置为空字符串或者 `null`，设置为 `undefined` 是不会生效的

**Comment by abc3660170** [comment]
[在线demo](https://stackblitz.com/edit/react-vqdqdc-hsuex2?file=index.js)，您看下我这边写的例子，达尔文的头像在3秒后并没有按照预期的结果被替换

**Comment by Aarebecca** [comment]
初步排查应该是一个潜在问题导致的，这边会尽快修复

**Comment by abc3660170** [comment]
@Aarebecca 已验证解决 👍
