### ISSUE TITLE
【V5】5.0.11 设置 drag-element + drag-canvas 后，拖动节点画布也会被拖动了

### ISSUE THREAD

**Issue by MusicTen** [antvis/G6#6124]
### Describe the bug / 问题描述

设置 `behaviors: ['drag-element', 'drag-canvas']` 后，拖动节点，会触发画布的拖动事件了

### Reproduction link / 重现链接

https://stackblitz.com/edit/react-7kfztw?file=index.js

### Steps to Reproduce the Bug or Issue / 重现步骤

1. 设置 drag-element + drag-canvas 两个 behavior
2. 拖动节点
3. 画布也被拖动

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by North-City** [comment]
5.0.13版本修复了这个问题,,为啥14版本就又出现了啊?
