### ISSUE TITLE
drag-canvas与brush-select(trigger:'shift')同时存在时，框选会触发画布拖拽

### ISSUE THREAD

**Issue by zyh0yh** [antvis/G6#6126]
### Describe the bug / 问题描述

drag-canvas与brush-select(trigger:'shift')同时存在时，框选会触发画布拖拽

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

### Additional context / 补充说明

drag-canvas与brush-select(trigger:'shift')同时存在时，框选会触发画布拖拽，有什么方式可以同时满足两个条件，框选时画布拖拽失效

**Comment by Aarebecca** [comment]
https://github.com/antvis/G6/pull/6125 已修复，今天会发布新版本

**Comment by zyh0yh** [comment]
当前已更新5.0.11，并再次测试，发现还是会存在同时触发的情况

**Comment by zzjjbbaa** [comment]
> 当前已更新5.0.11，并再次测试，发现还是会存在同时触发的情况

5.017也存在

**Comment by zyh0yh** [comment]
5.0.19还存在问题

**Comment by changxuexu** [comment]
5.0.25还存在问题,有没有解决的案例呢？
