### ISSUE TITLE
【V5】ReactNode节点的size应该怎么自适应。

### ISSUE THREAD

**Issue by Wu-Yao** [antvis/G6#6134]
### Describe the bug / 问题描述

![image](https://github.com/user-attachments/assets/b47b6c06-a0d3-4851-82af-6c2f5c4d9067)
使用g6-extension-react自定义节点后，root元素有32px的默认宽高，导致port位置不符合预期，期望root节点为自定义元素的宽高。

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
为了保证数据一致性，你需要在 node.style 中同步设置 size

**Comment by Wu-Yao** [comment]
> 为了保证数据一致性，你需要在 node.style 中同步设置 size
但size只支持number，期望是fit-content

**Comment by Aarebecca** [comment]
@Wu-Yao 目前还不支持这样，因为会影响边连接以及布局的计算，除非说你的图完全不使用边或者布局
