### ISSUE TITLE
【V5】5.0.12版本 tooltip plugins 渲染字符串模版失效

### ISSUE THREAD

**Issue by MusicTen** [antvis/G6#6138]
### Describe the bug / 问题描述

![image](https://github.com/user-attachments/assets/77bf8531-4752-463b-a93a-b7c22079045a)

### Reproduction link / 重现链接

https://stackblitz.com/run?file=index.js

### Steps to Reproduce the Bug or Issue / 重现步骤

1. 通过 getContent 设置 tooltip 自定义内容
2. 渲染自定义字符串模板未能成功加载

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
duplicated with https://github.com/antvis/G6/issues/6135
会尽快修复
