### ISSUE TITLE
After re-Render, Some events throws Error

### ISSUE THREAD

**Issue by longzou** [antvis/G6#6140]
### Describe the bug / 问题描述

通过 addNodeData加入一些新节点后，需要执行draw, 或render方法来显示，如下。      
this.graph.addNodeData([nodeItem]);
this.graph.draw();
然后，新增加的节点，以及旧的节点的事件都会报错。然后应用完全卡死。

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome, Edge

**Comment by Aarebecca** [comment]
请提供相关复现 demo
