### ISSUE TITLE
[V5] Performance Issue - Multiple selection is delayed when rendering large number of nodes

### ISSUE THREAD

**Issue by hongwei0417** [antvis/G6#6143]
### Describe the bug / 问题描述

When rendering 1000 nodes and select multiple nodes
There will be a delay of a few seconds before the node status changes (as below)

I found that the bottleneck may be caused by `updateNodeData()`, which will compare the data changes of each node, for reference.
https://github.com/antvis/G6/blob/7ce727aacd7ee9df434cdb6fd62da20f717ffebc/packages/g6/src/runtime/data.ts#L425

![Arc_lch4RIUAdV](https://github.com/user-attachments/assets/55fd0270-cec8-4348-96ac-e69da8d84dee)

### Steps to Reproduce the Bug or Issue / 重现步骤

1. Render more than 1000 natvie nodes
2. Enable `click-select` behavior
3. Click and select multiple nodes

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS, Windows

### Browser / 浏览器

Chrome, Edge, Others / 其他

**Comment by Aarebecca** [comment]
Thanks for the feedback, we will optimize for this situation
