### ISSUE TITLE
Contextmenu插件点击菜单无响应

### ISSUE THREAD

**Issue by Hheihi** [antvis/G6#6150]
### Describe the bug / 问题描述

<img width="547" alt="image" src="https://github.com/user-attachments/assets/82eb1668-a3e9-4bf3-9953-f643a8588632">

点击菜单无法触发click事件

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by Hheihi** [comment]
![image](https://github.com/user-attachments/assets/d3f06ae3-d52f-4390-bf52-ac0e38e63d5f)
官网上的例子为什么alert变成console之后还是会弹窗

**Comment by Aarebecca** [comment]
这是由于官网执行环境没有正常秩序销毁流程导致的，在正常开发过程中不会有这种问题
