### ISSUE TITLE
【V5】自定义节点的选中状态无法触发

### ISSUE THREAD

**Issue by Wu-Yao** [antvis/G6#6151]
### Describe the bug / 问题描述

点击自定义React节点，不会高亮当前节点及其直接相邻的节点和边。

### Reproduction link / 重现链接

https://stackblitz.com/edit/react-kddz3c?file=index.js

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
React 状态样式需自行实现，状态获取方式为：
```jsx
// data.status
component: (data) => <Node data={data} />
```

'click-select' 暂不适用 React 节点
