### ISSUE TITLE
使用自定义combo后 node节点不在combo内了

### ISSUE THREAD

**Issue by BDN233** [antvis/G6#6155]
### Describe the bug / 问题描述

![微信图片_20240808134007](https://github.com/user-attachments/assets/052b9e67-f966-4212-a89a-bdc9f5e5390e)

### Steps to Reproduce the Bug or Issue / 重现步骤

G6.registerCombo('cloud-combo', {
        drawShape(cfg, group) {
            const shape = group.addShape('path', {
                attrs: {
                    path: 'M 250 300 A 50 50 0 1 1 500 300 A 50 50 0 1 1 500 450 L 200 450 A 100 50 0 1 1 200 450 A 50 50 0 1 1 250 300Z',
                    fill: '#C6E5FF',
                    stroke: '#1890FF',
                    lineWidth: 2,
                    opacity: 0.8,
                }
            });

            return shape;
        }
    }, 'rect');

### G6 Version / G6 版本

4.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by lhz7695001** [comment]
请问，这个问题最后如何解决的呢？
