### ISSUE TITLE
antv G6 树图节点元素移出画布范围后该节点周边添加的子元素未移出画布范围而树图节点移出画布范围 致使整个元素都消失了

### ISSUE THREAD

**Issue by NidhoggDJoking** [antvis/G6#6156]
### Describe the bug / 问题描述

antv G6 树图节点元素移出画布范围后元素删除（SVG模式下为隐藏）

导致 我在该节点周边添加的子元素未移出画布范围而树图节点移出画布范围 致使整个都消失了

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by NidhoggDJoking** [comment]
![image](https://github.com/user-attachments/assets/21e4077d-f22d-4263-9503-48b67bf02317)


![image](https://github.com/user-attachments/assets/c0c7945f-fb8c-43a2-b5c5-b0c601e2a985)


SVG渲染模式下树图里的一个节点上我绘制了一些元素 当节点移出视图范围后（绘制的元素还在范围内） 整体被“hidden”了 ，导致 还在范围内的元素也消失不见

**Comment by Aarebecca** [comment]
请提供复现 demo
