### ISSUE TITLE
官网demo加载不出来

### ISSUE THREAD

**Issue by Tamcony** [antvis/G6#6162]
### Describe the bug / 问题描述

![image](https://github.com/user-attachments/assets/51f92c4e-be11-47be-8fa5-bee48e2fc68b)
信息如图所示

### Reproduction link / 重现链接

https://g6.antv.antgroup.com/g6v5

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Edge

**Comment by Aarebecca** [comment]
The site of G6 5.0: https://g6-next.antv.antgroup.com/
