### ISSUE TITLE
使用 React 定义节点如何给节点中的某一个元素指定为keyShape

### ISSUE THREAD

**Issue by songxiaoyu321** [antvis/G6#6163]
现在react定义节点(createNodeFromReact)默认最外层Group为keyShape，我希望可以指定Group里的某一个子元素为keyShape，比如里边的某个Rect,请问如何设置？

**Comment by Aarebecca** [comment]
目前暂不支持

**Comment by songxiaoyu321** [comment]
> 目前暂不支持，这么做的目的是？

![image](https://github.com/user-attachments/assets/16fa5048-47b7-45a2-a566-e1b865547973)
比如会有这种场景，keyshape是最外层，就会导致线和Rect连接不上

**Comment by Aarebecca** [comment]
@songxiaoyu321 这种情况你可以手动指定连接桩的位置解决
