### ISSUE TITLE
框选和拖拽画布冲突

### ISSUE THREAD

**Issue by North-City** [antvis/G6#6165]
### Describe the bug / 问题描述

框选和拖拽画布冲突,和问题#6126问题一致

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS, Windows

### Browser / 浏览器

Chrome, Edge

### Additional context / 补充说明

版本。5.0.13

**Comment by Aarebecca** [comment]
参考说明：[交互有冲突如何解决
](https://github.com/antvis/G6/blob/v5/packages/site/docs/manual/faq.zh.md#%E4%BA%A4%E4%BA%92%E6%9C%89%E5%86%B2%E7%AA%81%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3)
