### ISSUE TITLE
zoom canvas 交互会阻塞原生的scroll行为

### ISSUE THREAD

**Issue by axe-axe** [antvis/G6#6167]
### Describe the bug / 问题描述

zoom canvas 交互会阻塞原生的scroll行为

### Reproduction link / 重现链接

https://stackblitz.com/edit/react-dnwat1?file=index.js

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by summerDan** [comment]
[G6 - AntV]很好的东西 为什么api 文档 要托管给yuque  yuque 的api 文档写的乱七八糟 看不懂 毫无逻辑 也找不到  最差的 没有之一  各种问题

**Comment by summerDan** [comment]
希望G6团队可以自己管理起API 文档 yuque写的评价下面全部都是差评 说写的乱 看不懂 希望可以去了解下

**Comment by Aarebecca** [comment]
> [G6 - AntV]很好的东西 为什么api 文档 要托管给yuque yuque 的api 文档写的乱七八糟 看不懂 毫无逻辑 也找不到 最差的 没有之一 各种问题

不明白你指的语雀文档是哪篇。G6 从未使用语雀文档作为 API 文档对外，我们仅使用该文档存放了发布文章以及一些设计文稿。

**Comment by summerDan** [comment]
非常感觉您的回复 
现在点击https://antv-2018.alipay.com/zh-cn/g6/3.x/index  G6官网 api 文档是直接跳转 yuque  让我很难受 再也看不到 G6自己官方自己维护的APi 文档了





****************************************************************************

重要通知：本信息仅供发送至目的个人或实体使用。该信息可能包含在适用法律下享有特权、保密和免于披露的信息。如果您不是本信息的预期接收者，也不是负责将本信息传递给预期接收者的员工或代理人，请注意，任何传播、分发或复制本信息的行为均严格禁止。
IMPORTANT NOTICE: This message is intended only for the use of the individual or entity to which it is addressed. The message may contain information that is privileged, confidential and exempt from disclosure under applicable law. If the reader of this message is not the intended recipient, or the employee or agent responsible for delivering the message to the intended recipient, you are notified that any dissemination, distribution or copying of this communication is strictly prohibited.
****************************************************************************




发件人：Aaron ***@***.***>
发送日期：2024-08-15 10:51:14
收件人：antvis/G6 ***@***.***>
抄送人：summerDan ***@***.***>,Comment ***@***.***>
主题：Re: [antvis/G6] zoom canvas 交互会阻塞原生的scroll行为 (Issue #6167)

[G6 - AntV]很好的东西 为什么api 文档 要托管给yuque yuque 的api 文档写的乱七八糟 看不懂 毫无逻辑 也找不到 最差的 没有之一 各种问题
不明白你指的语雀文档是哪篇。G6 从未使用语雀文档作为 API 文档对外，我们仅使用该文档存放了发布文章以及一些设计文稿。

**Comment by Aarebecca** [comment]
@summerDan 你所访问的站点是较早期的 G6 版本官网了，下面是目前可用版本的 G6 官网。你所提到的官网后续我们会进行下架或跳转处理。
G6 4.x 官网：https://g6.antv.antgroup.com/
G6 5.x 官网(最新)：https://g6-next.antv.antgroup.com/

**Comment by Aarebecca** [comment]
下个版本(5.0.16)，你可以通过传入 `preventDefault: false` 给 zoom canvas 交互来避免阻止默认 scroll 事件
