### ISSUE TITLE
v5 工具栏使用问题

### ISSUE THREAD

**Issue by PromiseYo** [antvis/G6#6177]
### Describe the bug / 问题描述

5.0.13 版本 工具栏使用 api 文档是不是没更新。 图例中的 按钮点击默认只有弹窗，没有事件效果，放大缩小这些默认事件也需要自己实现吗

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
是的，需要自行在 onClick 中绑定对应的处理方法
