### ISSUE TITLE
【v5】 图例 支持固定位置显示 画布拖动 能够和工具栏一样固定位置

### ISSUE THREAD

**Issue by PromiseYo** [antvis/G6#6179]
### Describe the bug / 问题描述

 图例 支持固定位置显示 画布拖动 能够和工具栏一样固定位置

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
最新版本已解决该问题
