### ISSUE TITLE
隐藏实体,依旧占据画布位置,参与相关的操作

### ISSUE THREAD

**Issue by North-City** [antvis/G6#6180]
### Describe the bug / 问题描述

通过调用API, setElementVisibility方法后隐藏的节点虽然表面上不显示在画布上面. 但依旧参与相关的操作.例如布局切换,会导致布局结果显示不连贯,隐藏的节点参与布局,只是不显示

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS, Windows

### Browser / 浏览器

Chrome, Edge

### Additional context / 补充说明

版本是最新的15版本

**Comment by Aarebecca** [comment]
This is the same as how elements behave in CSS; if you don't want this part of the element to participate in the layout, either remove it outright or filter it in the layout via a nodeFilter.

> 这与 CSS 中元素的表现形式是一样的，如果你不希望这部分元素参与布局，要么直接将其删除，要么在布局中通过 nodeFilter 将其过滤。

**Comment by North-City** [comment]
布局的问题可以通过nodeFilter 过滤掉. 其他操作也是会影响的,如 自适应视口依旧会考虑隐藏的节点. 你提到的删除元素这种方案也不是最佳的解决方法,好多业务操作,只是需要隐藏掉节点,而不是删除.并且隐藏的节点不参与画布任何操作的.我记得4版本的是使用visible吧.还是比较好使的.
