### ISSUE TITLE
【V5】 react 节点开启 autoFix center 文字模糊

### ISSUE THREAD

**Issue by He110te4m** [antvis/G6#6185]
### Describe the bug / 问题描述

react 节点，包括 HTML 节点，在开启 autoFit center 的时候，都会发生字体模糊

### Steps to Reproduce the Bug or Issue / 重现步骤

在图表示例中运行如下代码，即可看到如图所示问题

> 开启 autoFit center
![image](https://github.com/user-attachments/assets/42012824-1b8d-438d-85b1-0f73e260a7c5)

> 未开启 autoFit center
![image](https://github.com/user-attachments/assets/6a532a76-959e-4bfc-bde5-c410f5a63626)

```js
import { DatabaseFilled } from '@ant-design/icons';
import { ExtensionCategory, Graph, register } from '@antv/g6';
import { ReactNode } from '@antv/g6-extension-react';
import { Badge, Flex, Input, Tag, Typography } from 'antd';
import { useEffect, useRef } from 'react';
import { createRoot } from 'react-dom/client';

const { Text } = Typography;

register(ExtensionCategory.NODE, 'react', ReactNode);

const Node = ({ data, onChange }) => {
  const { status, type } = data.data;

  return (
    <Flex
      style={{
        width: '100%',
        height: '100%',
        background: '#fff',
        padding: 10,
        borderRadius: 5,
        border: '1px solid gray',
      }}
      vertical
    >
      <Flex align="center" justify="space-between">
        <Text>
          <DatabaseFilled />
          Server
          <Tag>{type}</Tag>
        </Text>
        <Badge status={status} />
      </Flex>
      <Text type="secondary">{data.id}</Text>
      <Flex align="center">
        <Text style={{ flexShrink: 0 }}>
          <Text type="danger">*</Text>URL:
        </Text>
        <Input
          style={{ borderRadius: 0, borderBottom: '1px solid #d9d9d9' }}
          variant="borderless"
          value={data.data?.url}
          onChange={(event) => {
            const url = event.target.value;
            onChange?.(url);
          }}
        />
      </Flex>
    </Flex>
  );
};

export const ReactNodeDemo = () => {
  const containerRef = useRef();

  useEffect(() => {
    const graph = new Graph({
      container: containerRef.current,
      autoFit: 'center',
      data: {
        nodes: [
          {
            id: 'local-server-1',
            data: { status: 'success', type: 'local', url: 'http://localhost:3000' },
            style: { x: 50, y: 50 },
          },
          {
            id: 'remote-server-1',
            data: { status: 'warning', type: 'remote' },
            style: { x: 350, y: 50 },
          },
        ],
        edges: [{ source: 'local-server-1', target: 'remote-server-1' }],
      },
      node: {
        type: 'react',
        style: {
          size: [240, 100],
          component: (data) => <Node data={data} />,
        },
      },
      behaviors: ['drag-element', 'zoom-canvas', 'drag-canvas'],
    });

    graph.render();
  }, []);

  return <div style={{ width: '100%', height: '100%' }} ref={containerRef}></div>;
};

const root = createRoot(document.getElementById('container'));
root.render(<ReactNodeDemo />);

```

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
这边暂没有复现你提到的问题，不排除是使用显示器分辨率的原因。
另外，React 节点缩放是通过 Transform 实现的，因此如果放大倍率较高的话是会出现模型的情况，这是无法避免的。

**Comment by He110te4m** [comment]
> React 节点缩放是通过 Transform 实现的，因此如果放大倍率较高的话是会出现模型的情况，这是无法避免的。

并未进行缩放，仅将 graph 设置为 autoFit center ，官网示例以及本地项目都复现了此问题，截图中也能看到

**Comment by He110te4m** [comment]
@Aarebecca 尝试多种方案后，发现给 g-canvas-camera 加上 will-change 能大幅改善此问题，可能是由于电脑性能问题导致的此问题，是否考虑在项目内添加此样式呢？

**Comment by ohhoney1** [comment]
> [@Aarebecca](https://github.com/Aarebecca) 尝试多种方案后，发现给 g-canvas-camera 加上 will-change 能大幅改善此问题，可能是由于电脑性能问题导致的此问题，是否考虑在项目内添加此样式呢？

你好，怎么添加的呢？4.x 可以通过设置 imageSmoothingQuality 为 high

**Comment by He110te4m** [comment]
> > [@Aarebecca](https://github.com/Aarebecca) 尝试多种方案后，发现给 g-canvas-camera 加上 will-change 能大幅改善此问题，可能是由于电脑性能问题导致的此问题，是否考虑在项目内添加此样式呢？
> 
> 你好，怎么添加的呢？4.x 可以通过设置 imageSmoothingQuality 为 high

找到 g-canvas-camera 这个类，我记不太清哪些属性会变了，可能得看下哪些属性被挂 style 上，然后给这个类添加 will-change 即可，比如 `.g-canvas-camera { will-change: width; }` ，具体写法看 MDN

想到另一个方案可能是渲染的锐化问题，但是没有验证，如果 will-change 不能解决的话，可以往 `image-rendering: pixelated;` 这块去尝试，目前已知的应该是 Window 浏览器渲染的问题。

**Comment by yym-yumeng123** [comment]
这个在用的时候, 确实 react 定义节点, 会字体锯齿现状严重, 我设置了 hover: transform: scale 效果, 放到节点上就清晰了, 不知道怎么改善初始清晰度

**Comment by He110te4m** [comment]
> 这个在用的时候, 确实 react 定义节点, 会字体锯齿现状严重, 我设置了 hover: transform: scale 效果, 放到节点上就清晰了, 不知道怎么改善初始清晰度

感觉是 Chrome 的渲染器的问题，我之前没有试过其他浏览器，现在已经不处理这块业务了没法验证，你可以试试换 Firefox ，但是我知道的就是 Windows 的 Chrome 是有问题的，感觉是 Chrome 的 bug

**Comment by ohhoney1** [comment]
> 这个在用的时候, 确实 react 定义节点, 会字体锯齿现状严重, 我设置了 hover: transform: scale 效果, 放到节点上就清晰了, 不知道怎么改善初始清晰度

```css
#g-canvas-camera {
      .key {
        // hack. 解决 react 节点不清晰问题
        will-change: auto !important;
      }
}
```

**Comment by yym-yumeng123** [comment]
> > 这个在用的时候, 确实 react 定义节点, 会字体锯齿现状严重, 我设置了 hover: transform: scale 效果, 放到节点上就清晰了, 不知道怎么改善初始清晰度
> 
> #g-canvas-camera {
>       .key {
>         // hack. 解决 react 节点不清晰问题
>         will-change: auto !important;
>       }
> }

<img width="2101" height="940" alt="Image" src="https://github.com/user-attachments/assets/6caa7bf2-9ad5-4a64-8577-24066a3fcfbc" /> 好像差点, 先这样用吧, 大不了后面使用 自定义节点,

**Comment by He110te4m** [comment]
话说官方是真的一点都不管了？只要没复现就没问题，即使一堆人遇到 @Aarebecca

**Comment by yym-yumeng123** [comment]
> 话说官方是真的一点都不管了？只要没复现就没问题，即使一堆人遇到 [@Aarebecca](https://github.com/Aarebecca)

不用复现, windows 电脑看网站例子, 都看到出来, 

<img width="1671" height="932" alt="Image" src="https://github.com/user-attachments/assets/61fc54c2-24fa-4ff8-a5d1-e1c0a3aa8463" />

**Comment by He110te4m** [comment]
> > 话说官方是真的一点都不管了？只要没复现就没问题，即使一堆人遇到 [@Aarebecca](https://github.com/Aarebecca)
> 
> 不用复现, windows 电脑看网站例子, 都看到出来,
> 
> <img alt="Image" width="1671" height="932" src="https://private-user-images.githubusercontent.com/28480209/478337259-61fc54c2-24fa-4ff8-a5d1-e1c0a3aa8463.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTUyNjQzNzMsIm5iZiI6MTc1NTI2NDA3MywicGF0aCI6Ii8yODQ4MDIwOS80NzgzMzcyNTktNjFmYzU0YzItMjRmYS00ZmY4LWE1ZDEtZTFjMGEzYWE4NDYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODE1VDEzMjExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlMGM1MzNhOTkzMmQ1MzBlYzRlMDRhNjcwNjFjMGYwYzJjZDZiZTAwNDFkMjdiMzBlMDgyMDRmYjY1MTY4MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.q107pt5P6lBeTzAo_c16bjFSXQkc8XpkPAA3C34cVSo">

不是我说的复现不了，可以看 [楼上](https://github.com/antvis/G6/issues/6185#issuecomment-2291091016) ，这 issue 关闭的理由就是说他们复现不了完了就关了，我连 reopen 权限也没有，完了现在看来还是有很多人遇到问题

**Comment by zhao-fw** [comment]
1. 在mac中也有模糊的问题

<img width="802" alt="Image" src="https://github.com/user-attachments/assets/721ce00b-8119-43fb-a38c-311326810f9d" />

2. 在所有的#g-canvas-camera > .key元素上都存在will-change: transform的属性，是否可以去掉这个属性呢，如果节点太多，层叠层数会太多吧

**Comment by He110te4m** [comment]
我注意到一个比较有趣的现象，可以跟 G6 的初始化放到一起实现，在最初的时候给所有的 key 添加 `will-change: content !important;` ，等到初始化完成后移除 `will-change` ，可以使用 `unset !important` ，只要没有新的数据渲染或者 graph 更新，正常来说都不需要再 will-change 了（本身 transform 的性能就不会很差），看起来有点像元素与内容的渲染不同步，导致内容模糊，也许跟 render 的执行时机有关系

**Comment by yym-yumeng123** [comment]
> 我注意到一个比较有趣的现象，可以跟 G6 的初始化放到一起实现，在最初的时候给所有的 key 添加 `will-change: content !important;` ，等到初始化完成后移除 `will-change` ，可以使用 `unset !important` ，只要没有新的数据渲染或者 graph 更新，正常来说都不需要再 will-change 了（本身 transform 的性能就不会很差），看起来有点像元素与内容的渲染不同步，导致内容模糊，也许跟 render 的执行时机有关系

已经切换为 react flow , 非常丝滑
