### ISSUE TITLE
toFullDataURL 导出图片，元素没有裁剪为圆形

### ISSUE THREAD

**Issue by hechenguo** [antvis/G6#6186]
### Describe the bug / 问题描述

画布上有一个圆形头像，导出后变成了正方形。
本人已排查过代码，应该是在 这一行 [https://github.com/antvis/G6/blob/4.8.21/packages/pc/src/graph/graph.ts#L278](https://github.com/antvis/G6/blob/4.8.21/packages/pc/src/graph/graph.ts#L278) 。

```
// 旧的代码
// const vGroup = group.clone();
// 应该替换为下面这一行
const vGroup = cloneGElement(group);
```

### G6 Version / G6 版本

4.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
Hello, 有兴趣提个 PR 参与贡献吗
