### ISSUE TITLE
隐藏显示Node和预期不一致

### ISSUE THREAD

**Issue by abc3660170** [antvis/G6#6187]
### Describe the bug / 问题描述

调用 调用showElement 方法只能显示keyShape，其余图形都不显示，是API调整了吗？

### Steps to Reproduce the Bug or Issue / 重现步骤

先使用hideElement再使用showElement 

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

### Additional context / 补充说明

是v5.0.13 ->  v5.0.14 中引入的问题，之前版本都不存在问题

**Comment by Aarebecca** [comment]
应该是个 Bug ，会尽快修复

**Comment by abc3660170** [comment]
已修复 https://github.com/antvis/G6/commit/81551032421c299df6cff9e4e8dd1903b47f7efb
