### ISSUE TITLE
setFitView 计算整个图形的大小 是不是应该忽略没有渲染的图形(visible: false)

### ISSUE THREAD

**Issue by mengxiong10** [antvis/g6#619]
* **G6 Version**: 2.2.6

如题, 现在开发的一个树组件, 将某个很大的子树收起来以后, 整个树就直接跑到屏幕看不见的地方, setFitView('cc') 也没用, 因为现在是计算了隐藏的图形.

**Comment by elaine1234** [comment]
建议使用~3.0.0-beta.15版本的G6，文档可见[TreeGraph](https://www.yuque.com/antv/g6/treegraph)，配合系统内置的收缩行为使用
