### ISSUE TITLE
g6的API文档不全，很怀疑官方文档的地址是不是正确的。

### ISSUE THREAD

**Issue by YYmmlin** [antvis/g6#62]
g6的API文档不全啊  很多配置方法都找不到，但是看案例那里确是有使用的。这个文档看得很辛苦啊！
https://antv.alipay.com/g6/api/index.html

比如
![image](https://user-images.githubusercontent.com/12744546/29203428-549acdec-7ea3-11e7-9c0a-3f02f93bf8c0.png)

**Comment by TomHuangCN** [comment]
这两部分，文档都是有的，不过找起来确实麻烦了点。文档信息结构有点问题，抱歉。

https://antv.alipay.com/g6/api/index.html#registNode

https://antv.alipay.com/g6/api/canvas.html#文本——text

**Comment by YYmmlin** [comment]
那有没有删除item后的回调方法？ 
还有del的用法是怎么用的？我各种调用都试了，也都没有实现效果。

**Comment by TomHuangCN** [comment]
del 会删除在激活状态下的元素
