### ISSUE TITLE
有G6编辑器的源码DEMO吗？

### ISSUE THREAD

**Issue by wanmeng8888** [antvis/g6#620]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by elaine1234** [comment]
G6-editor目前没有开源，demo可见：https://antv.alipay.com/zh-cn/g6/2.x/demo/index.html#_%E7%BC%96%E8%BE%91%E5%99%A8

**Comment by caoyu48** [comment]
http://62.234.69.136/

**Comment by baizn** [comment]
目前没有在维护了， 可以参考社区的实现：https://www.yuque.com/antv/g6/intro#uu3gy。
