### ISSUE TITLE
 graph.getPluginInstance('fullscreen') return undefined ,the graph is a instance of Graph

### ISSUE THREAD

**Issue by Yuhemei** [antvis/G6#6206]
### Describe the bug / 问题描述

const fullScreenPlugin: Fullscreen = graph.getPluginInstance('fullscreen');
console.log(fullScreenPlugin);//undefined
fullScreenPlugin.request();

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
Did you config fullscreen plugin in graph options? Could you provide the codes.

**Comment by Yuhemei** [comment]
```
const fullScreenPlugin: Fullscreen = graph.getPluginInstance(
    'plugin-fullscreen-0',
  );
  fullScreenPlugin.request();
```
生效了。
原因是 graph.context.plugin.extensionMap是`plugin-fullscreen-0`不是`fullscreen`
但是用起来很别扭，期待团队早日更新

**Comment by Yuhemei** [comment]
> Did you config fullscreen plugin in graph options? Could you provide the codes.

Yes,this is my code
```
plugins: [
      'minimap',
      'fullscreen',
      ...
]
```
my dependencies version is "@antv/g6": "^5.0.16",
you can try it.

**Comment by Aarebecca** [comment]
The main reason is that once you do not assign a key for the plugin, G6 will generate one automatically. Hence, if you want to get the plugin instance, you'd better configure as follows:

Graph options:
```ts
plugins: [
  'minimap',
  {
    type: 'fullscreen',
    key: 'fullscreen'
  }
]

```

Use:
```ts
import type { Fullscreen } from '@antv/g6';

const fullscreen = graph.getPluginInstance<Fullscreen>('fullscreen');
```

**Comment by Aarebecca** [comment]
@Yuhemei Hi, we enhanced the `getPluginInstance` API in https://github.com/antvis/G6/pull/6215, you can use it in the next version, but its return is ambiguous, so it will print a warning in console.
