### ISSUE TITLE
Edge setting arrow style issue

### ISSUE THREAD

**Issue by WKingIce** [antvis/G6#6219]
<img width="853" src="https://github.com/user-attachments/assets/b4ae953f-bd60-4d10-8fb3-8f4ef229a54e">
官网例子里面，当设置lineWidth比较大时，startArrow样式跟endArrow显示不一样

**Comment by yvonneyx** [comment]
The issue has been reported to G. Please stay tuned for updates on https://github.com/antvis/G/issues/1760.
