### ISSUE TITLE
触摸板手势交互问题(mac电脑)

### ISSUE THREAD

**Issue by chokyff** [antvis/G6#6221]
### Describe the bug / 问题描述

我添加了如下交互行为代码:
modes: {
     default: ['drag-canvas', 'zoom-canvas'],
},
我发现双指上下滑动触摸板, 也是缩放画布, 而不是移动画布.

### G6 Version / G6 版本

4.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
移动画布请使用 Drag 操作
