### ISSUE TITLE
edge 为 cubic-horizontal时，节点的anchorPoints不生效，导致节点拖拽时箭头显示有问题

### ISSUE THREAD

**Issue by liweipeng20** [antvis/G6#6225]
### Describe the bug / 问题描述

edge 为 cubic-horizontal时，节点的anchorPoints不生效，如果一个节点既有以此为终点的线，也有以此为起点的线，终点和起点都在一个位置上，那么视觉上很容易造成混淆。因为指向位置，导致节点拖拽时箭头显示也会有问题。
![1](https://github.com/user-attachments/assets/827b7b83-1407-4095-897b-8ebc52e93f5e)

### Steps to Reproduce the Bug or Issue / 重现步骤

没设置线的类型的话，设置的anchorPoints就会生效
![2](https://github.com/user-attachments/assets/c35d7f04-6e88-42e2-85dd-c59b498a2be9)

### G6 Version / G6 版本

4.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by yvonneyx** [comment]
If the `anchorPoints` of `cubic-horizontal` are not working in version 4.x, it is recommended to implement your requirements by customizing the edge.
