### ISSUE TITLE
【v5】自定义节点，如何在drawKeyShape时，获取原始节点数据

### ISSUE THREAD

**Issue by zmbxy** [antvis/G6#6226]
### Describe the bug / 问题描述

```js
class Svg extends BaseNode {

  protected nodeMap: Record<string, string>;

  constructor(options: RouterNodeStyleProps) {
    super(options);
    this.nodeMap = {};
  }

  protected drawKeyShape(attributes: Required<RouterNodeStyleProps>, container: Group) {
    console.log('container: ', container);
    console.log('attributes: ', attributes);
    return undefined;
  }

}
```

以这段代码为例，如果想在drawKeyShape时拿到原始节点数据，根据原始节点中的业务配置数据进行绘制图形，我应该怎么做？

### Reproduction link / 重现链接

无

### Steps to Reproduce the Bug or Issue / 重现步骤

无

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS, Windows

### Browser / 浏览器

Chrome, Firefox

**Comment by Aarebecca** [comment]
自定义元素中可以通过 `this.context.graph` 来访问 `Graph` 实例，你可以通过以下方式获取节点数据：

```ts
const data = this.context.graph.getNodeData(this.id);
```
