### ISSUE TITLE
刚开始接触G6，发现一个小问题

### ISSUE THREAD

**Issue by HawtinZeng** [antvis/G6#6227]
### Describe the bug / 问题描述

文档默认的G6版本与npm拉取的默认版本不一致

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Others / 其他

### Browser / 浏览器

Chrome

### Additional context / 补充说明

![image](https://github.com/user-attachments/assets/b49d2950-6673-4dd5-ae05-c9ebf4a364e3)
![image](https://github.com/user-attachments/assets/6e43cf43-8df9-445f-821b-fbedbc4c67fb)

**Comment by Aarebecca** [comment]
你查看的文档为 4.x 版本，目前 G6 最新版为 5.X，官网：https://g6-next.antv.antgroup.com/

**Comment by HawtinZeng** [comment]
好



---Original---
From: ***@***.***&gt;
Sent at: 2024年8月22日(Thu) Evening8:23
To: ***@***.***&gt;;
Cc: "Hawtin ***@***.******@***.***&gt;;
Subject: Re: [antvis/G6] 刚开始接触G6，发现一个小问题 (Issue #6227)




 
你查看的文档为 4.x 版本，目前 G6 最新版为 5.X，官网：https://g6-next.antv.antgroup.com/
