### ISSUE TITLE
[V5] Edge arrow offset behaves inconsistently

### ISSUE THREAD

**Issue by hongwei0417** [antvis/G6#6233]
### Describe the bug / 问题描述

**The edge is not connected correctly to the start arrow**

![image](https://github.com/user-attachments/assets/36f90f17-1a53-4cf7-845a-d39b47a7b9b4)

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS, Windows

### Browser / 浏览器

Chrome, Edge, Others / 其他

**Comment by Aarebecca** [comment]
This issue was caused by the renderer: https://github.com/antvis/G/issues/1760
