### ISSUE TITLE
The react custom node cannot be connected to the edge after scaling

### ISSUE THREAD

**Issue by Tzng** [antvis/G6#6241]
### Describe the bug / 问题描述

如图所示，在进行缩放加拖拽之后，边无法连接到节点
![image](https://github.com/user-attachments/assets/907e8061-5c7d-4acd-94fb-a8d9235e315b)

### Steps to Reproduce the Bug or Issue / 重现步骤

1，打开示例代码：https://g6-next.antv.antgroup.com/zh/examples/element/custom-node/#react-node
2，进行拖拽操作
3，进行缩放操作

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Edge

**Comment by Aarebecca** [comment]
The latest version has been resolved, clear node modules and reinstall the dependency
