### ISSUE TITLE
V5.0.4 / V5.0.17 zoom-canvas scaling exception

### ISSUE THREAD

**Issue by hh1412** [antvis/G6#6243]
### Describe the bug / 问题描述

V5.0.4 缩放有bug 点击一个元素选中后 切到别的地方 然后失焦 再切回去就缩放不了 估计是失焦了状态没有续上

在Sandbox上 V5.0.4的失效 但是V5.0.17的正常   在本地的V5.0.4 和V5.0.17的缩放都失效

https://github.com/user-attachments/assets/9903c731-a1e0-4a8b-9ba8-7ca5dfe6e3d6

### Reproduction link / 重现链接

https://codesandbox.io/p/sandbox/test-g6-zoom-canvas-zsmzrn

### Steps to Reproduce the Bug or Issue / 重现步骤

点击一个元素选中后 切到别的地方 再切回去就缩放不了

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

### Additional context / 补充说明

在Sandbox上 V5.0.4的失效 但是V5.0.17的正常   在本地的V5.0.4 和V5.0.17的缩放都失效

**Comment by hh1412** [comment]
点击一下画布 然后再切到别的东西 再切回来 也不能再进行zoom-canvas

**Comment by Aarebecca** [comment]
@hh1412 5.0.17 版本本地和 codesandbox 均未复现该问题
