### ISSUE TITLE
g6自定义的dom节点ie不支持？

### ISSUE THREAD

**Issue by kongxiaochen** [antvis/g6#625]
看了下，自定义绘制dom的时候，是把dom元素塞在foreignObject这个标签中的，
而这个标签在ie下是不支持的，导致dom元素展现不出来，该如何处理呢？

* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by SOMOFEELGOOD** [comment]
请问解决了吗  分享以下

**Comment by nielinjie** [comment]
g6 v3.0不支持html节点了哎。楼主可否共享下代码？

**Comment by elaine1234** [comment]
我们在是否支持`html`节点时一直都很纠结。因为视口转换，图片导出，缩略图，数据持久化等等方面都会存在很大问题，所以最后还是决定不在`html`节点上花大力气，可以看下这个文档：https://www.yuque.com/antv/g6/xm2ek3 。
另：canvas 的浏览器兼容性到 IE9，foreignObject 也是如此。

**Comment by SOMOFEELGOOD** [comment]
foreignObject 都不支持ie  我们已经放弃了，把需求实现通过其他方式实现，虽然代码量增加很多。
