### ISSUE TITLE
In version 5.x, there is an afterimage in the image drag

### ISSUE THREAD

**Issue by byMyWill** [antvis/G6#6251]
### Describe the bug / 问题描述

![image](https://github.com/user-attachments/assets/9cfcdc09-f4ee-49d4-b4eb-70ed9442a3bd)
官网demo就可复现

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
底层渲染引擎问题，后续解决

**Comment by byMyWill** [comment]
ok




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/G6"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月29日(星期四) 下午4:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [antvis/G6] In version 5.x, there is an afterimage in the image drag (Issue #6251)





 
底层渲染引擎问题，后续解决

**Comment by litlezqk** [comment]
仍然存在
