### ISSUE TITLE
How do I use the features of antv/g6 5.x JSX custom nodes on Vue3.x?

### ISSUE THREAD

**Issue by smallsun0122** [antvis/G6#6255]
### Describe the bug / 问题描述

参考官网的案例，在 Vue3.x 版本上使用会报错，
![WechatIMG29](https://github.com/user-attachments/assets/3394c686-4901-40d0-8af7-e6c6c9bd2a42)

https://g6-next.antv.antgroup.com/zh/examples/element/custom-node#react-g

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
该特性依赖 React 环境，在 Vue 下暂不可用
