### ISSUE TITLE
Export PNG blank, no content

### ISSUE THREAD

**Issue by binliuli** [antvis/G6#6256]
### Describe the bug / 问题描述

win11电脑，谷歌浏览器106版本，导出的png图片，存在空白无内容情况；方法：graph.downloadFullImage(name, type, imageConfig)；G6.TreeGraph

### G6 Version / G6 版本

4.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

### Additional context / 补充说明

同一版本浏览器，不同电脑出现导出png无内容空白情况，概率事件

**Comment by Aarebecca** [comment]
建议先参考看是否能解决 https://github.com/antvis/G6/issues/2980
