### ISSUE TITLE
G6 3.0 beta版的节点和边的层级如何设置，比如让边显示在节点上方

### ISSUE THREAD

**Issue by lee107** [antvis/g6#626]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

节点调用了toBack()方法，还是显示在边的上面

**Comment by xd19831203** [comment]
同问 遇到了这个个问题解决不了，文档上也找不着

**Comment by baizn** [comment]
> 同问 遇到了这个个问题解决不了，文档上也找不着

https://www.yuque.com/antv/g6/item#l6YrE
