### ISSUE TITLE
G6流程图自定义节点复写draw方法展示问题

### ISSUE THREAD

**Issue by luckyxutao** [antvis/G6#627]
![image](https://user-images.githubusercontent.com/1294316/53283369-5e5cea80-3780-11e9-88c2-e9fb67210e6d.png)
用的是layout.dagre布局，demo自定义节点只复写了getPath方法是正常的，复写draw后显示就不正常了，可能是什么原因呢？感激不尽

![image](https://user-images.githubusercontent.com/1294316/53283394-beec2780-3780-11e9-89f5-fc489c637a9d.png)

**Comment by dxq613** [comment]
用的哪个版本？

**Comment by luckyxutao** [comment]
G6 2.2.6,  https://antv.alipay.com/zh-cn/g6/2.x/demo/flow/work-flow.html   也是同样错误

**Comment by luckyxutao** [comment]
@dxq613 找到原因了么？

**Comment by Yanyan-Wang** [comment]
自定义节点的 rect 的 x 和 y 要各减去 width 和 height 的一半，因为在 G6 中处理的矩形的 （0，0）在其中点。
