### ISSUE TITLE
V5 @antv/g6-extension-react is not compatible with versions below React 18 and above 16

### ISSUE THREAD

**Issue by minjie946** [antvis/G6#6273]
### Describe the bug / 问题描述

- 自定义节点的时候，用React 的形式使用，但是在注册时候提示 Cannot find module 'react-dom/client'
![image](https://github.com/user-attachments/assets/b29b59d4-9544-4696-9265-99755261d1cd)

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
该扩展使用了 react 18 提供的 createRoot API，因此在更低版本 React 下不兼容。
