### ISSUE TITLE
Double-clicking on an element is partially invalid

### ISSUE THREAD

**Issue by North-City** [antvis/G6#6274]
### Describe the bug / 问题描述

上图后的实体,连接线元素在双击的时候有时候会没有触发双击效果. eg: 在监听点的双击事件后,多次尝试双击时触发监听的回调函数不是100%触发. 是内部做过防抖的操作吗?

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS, Windows

### Browser / 浏览器

Chrome, Edge

**Comment by North-City** [comment]
> 点击的间隔时长不超过 2

有时候感觉也不是这个间隔时长的问题.总是有情况会不触发,请看一下下面的demo,多个节点切换点击试试.
https://codesandbox.io/p/sandbox/throbbing-night-nfp2lm?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm0ov4p4o00063b6ib8d8uj6x%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm0ov4p4o00023b6it0k4vrvv%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm0ov4p4o00033b6i7ahzl6en%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm0ov4p4o00053b6iappbhknz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm0ov4p4o00023b6it0k4vrvv%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0ov4p4o00013b6ic3gaivqt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%257D%255D%252C%2522id%2522%253A%2522cm0ov4p4o00023b6it0k4vrvv%2522%252C%2522activeTabId%2522%253A%2522cm0ov4p4o00013b6ic3gaivqt%2522%257D%252C%2522cm0ov4p4o00053b6iappbhknz%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0ov4p4o00043b6iuj8u29m8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cm0ov4p4o00053b6iappbhknz%2522%252C%2522activeTabId%2522%253A%2522cm0ov4p4o00043b6iuj8u29m8%2522%257D%252C%2522cm0ov4p4o00033b6i7ahzl6en%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm0ov4p4o00033b6i7ahzl6en%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by North-City** [comment]
> 目前双击事件的命中规则是前后两次点击的间隔时长不超过 200ms
请尝试下面的demo 看看.多个节点切换,多次.后面总会有些问题.
https://codesandbox.io/p/sandbox/autumn-tdd-7nngk4?file=%2Findex.js%3A20%2C11

**Comment by Aarebecca** [comment]
@North-City 我尝试了下没有发现你描述的问题，可能是有时候点击到了 Halo 区域，这个部分是不响应事件的

**Comment by North-City** [comment]
> 候点击到了 Halo 区域，这个部分是不响应事件的

了解.可能是双击间隔超了吧. 感谢感谢!
