### ISSUE TITLE
If Layout is set to tree, setting edge to polyline is invalid.

### ISSUE THREAD

**Issue by AGG-an** [antvis/G6#6277]
### Describe the bug / 问题描述

当为树类型的edge设置了
`edge: {
        type: 'polyline',
        style: {
          router: {
            type: 'orth',
          },
          stroke: '#C0C0C0',
        },
      },`
会出现错误：
![image](https://github.com/user-attachments/assets/e61f4cdf-7a50-4df7-b742-10937fbf845e)

其实 我想实现的效果也很简单：
![image](https://github.com/user-attachments/assets/6e4628e6-b3c6-4f55-9683-57a951c64618)

左右树结构，只是边不是曲线的；为实现这种效果 需要怎么配置？

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by AGG-an** [comment]
使用的CDN引入，版本5.0.19
![image](https://github.com/user-attachments/assets/8597781e-8b21-4a49-a965-2ca9b357c61b)

**Comment by yvonneyx** [comment]
Fixed in 5.0.21

**Comment by yvonneyx** [comment]
可以参考官网示例 https://g6-next.antv.antgroup.com/examples/scene-case/default/#performance-diagnosis-flowchart
