### ISSUE TITLE
Switching to version 5.0 on the official website and using the search function will cause the page to freeze

### ISSUE THREAD

**Issue by potato-sauce** [antvis/G6#6281]
### Describe the bug / 问题描述

https://g6-next.antv.antgroup.com
4.x版本可以正常使用搜索，用5.0版本搜的时候会触发一堆网络请求直接把页面卡住了
<img width="400" alt="image" src="https://github.com/user-attachments/assets/5689c09a-ea35-4727-858b-86bd0c4426c9">

### Steps to Reproduce the Bug or Issue / 重现步骤

mac和win的新版chrome都会，无痕浏览器下也会这样，应该不是浏览器插件导致的，看上去是个很容易复现的问题

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by resetsix** [comment]
> 目前已经发现这个问题了，会尽快解决

是因为build出来全是js文件的原因吗

<img width="979" alt="图片" src="https://github.com/user-attachments/assets/fb6a0539-a6ba-4f34-9793-545772bf76be">

**Comment by Aarebecca** [comment]
@resetsix 因为官网使用的 dumi 进行开发，应该是 dumi 升级导致的问题

**Comment by resetsix** [comment]
> @resetsix 因为官网使用的 dumi 进行开发，应该是 dumi 升级导致的问题

我昨天拉下源码在本地测试，搜索功能是正常的响应速度很快，也不会发送任何网络请求。

的确没有用过 dumi 来写文档，我看g6 依赖的 dumi 版本也是最新的，所以我不知道为什么 v4 正常但是 v5 不正确。看了下 udmi.ts 配置，确实没有排查的思路。我觉得 [docsearchOptions](https://github.com/antvis/G6/blob/64ad30737f6a6dc91af87eb74bd193edd5a2a5b8/packages/site/.dumirc.ts#L47C5-L47C21) 配置比较可疑，但 dumi 文档没有这个 api 信息。

**Comment by Aarebecca** [comment]
> > @resetsix 因为官网使用的 dumi 进行开发，应该是 dumi 升级导致的问题
> 
> 我昨天拉下源码在本地测试，搜索功能是正常的响应速度很快，也不会发送任何网络请求。
> 
> 的确没有用过 dumi 来写文档，我看g6 依赖的 dumi 版本也是最新的，所以我不知道为什么 v4 正常但是 v5 不正确。看了下 udmi.ts 配置，确实没有排查的思路。我觉得 [docsearchOptions](https://github.com/antvis/G6/blob/64ad30737f6a6dc91af87eb74bd193edd5a2a5b8/packages/site/.dumirc.ts#L47C5-L47C21) 配置比较可疑，但 dumi 文档没有这个 api 信息。

已经联系 dumi 的开发者修复了

**Comment by Aarebecca** [comment]
已经修复：https://github.com/antvis/G6/pull/6420
