### ISSUE TITLE
drag-element After shadow is enabled, there is an afterimage during dragging

### ISSUE THREAD

**Issue by izhl2020** [antvis/G6#6287]
### Describe the bug / 问题描述

![1725592631907](https://github.com/user-attachments/assets/c006a316-d693-438e-ac2e-a91d289e115b)
随意拖拽一个节点，在画布上出现残影

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by resetsix** [comment]
参考

https://github.com/antvis/G6/issues/5257#issuecomment-1852026557

[常见使用问题汇总](https://g6.antv.antgroup.com/manual/faq/faq#%E6%B8%B2%E6%9F%93%E6%AE%8B%E5%BD%B1%E9%97%AE%E9%A2%98)
