### ISSUE TITLE
graph.setElementState performance issues

### ISSUE THREAD

**Issue by songxiaoyu321** [antvis/G6#6313]
### Describe the bug / 问题描述

页面有400个节点，批量设置选中状态
console.log( new Date().getTime())
graph.setElementState(visibleRecord);
console.log( new Date().getTime())
看了下时间要574ms,明显感觉卡顿，点数量更多时更明显
V4没有这个问题，请问有什么解决办法

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
有更新到最新版吗，近期优化过，更新 1000 节点状态在 100ms 左右

**Comment by songxiaoyu321** [comment]
> 有更新到最新版吗，近期优化过，更新 1000 节点状态在 100ms 左右

是最新版 5.0.21

**Comment by Aarebecca** [comment]
@songxiaoyu321 建议提供下你的用例我这边测试一下

**Comment by Aarebecca** [comment]
@songxiaoyu321 你可以尝试关闭动画，当画布中元素较多时，打开动画可能会导致严重的卡顿现象。

**Comment by youyinnn** [comment]
你好，想请问下setElementState到底怎么用？我看不懂Record是什么，你的visibleRecord对象是怎么构建的？
