### ISSUE TITLE
The mindmap collapse-expand-tree in the v5 scenario instance is not available

### ISSUE THREAD

**Issue by citrusjunoss** [antvis/G6#6329]
### Describe the bug / 问题描述

v5场景实例中的的mindmap collapse-expand-tree不可用

https://g6-next.antv.antgroup.com/examples/scene-case/default/#mindmap

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
正确的交互名为：'collapse-expand'，会尽快更新官网 demo 代码

**Comment by citrusjunoss** [comment]
> 正确的交互名为：'collapse-expand'，会尽快更新官网 demo 代码

收到改了代码后，触发collapse-expand的行为是双击，而不是单击，预期行为是这样的

**Comment by Aarebecca** [comment]
@citrusjunoss Sorry 我刚确认了下可能是定制交互的问题，如果你使用内置的 `collapse-expand` 可以参考： https://g6-next.antv.antgroup.com/api/behaviors/collapse-expand#trigger 进行配置

**Comment by citrusjunoss** [comment]
> @citrusjunoss Sorry 我刚确认了下可能是定制交互的问题，如果你使用内置的 `collapse-expand` 可以参考： https://g6-next.antv.antgroup.com/api/behaviors/collapse-expand#trigger 进行配置

请问，如果我想使用定制折叠交互要怎么修改
