### ISSUE TITLE
When you expand an element, the layout collapses!

### ISSUE THREAD

**Issue by AGG-an** [antvis/G6#6332]
### Describe the bug / 问题描述

https://github.com/user-attachments/assets/e055cbbb-cfb0-44d8-9ea1-811dc1b1e066

在展开数据的时候，会出现布局异常的现象；观察到出现异常的时候都是数据量较多的数据；所以我设置完数据之后隔了1秒时间在调用更新布局，依旧没有作用，数据能保证ID唯一：
`graph.updateChildren(listData, parent.id);
await sleep(1000)
graph.changeData();
graph.layout();`

后面我将渲染模式设置为canvas；发现这个问题就不存在了；但是canvas不支持使用html渲染元素 并不能满足样式需求；所以看看这是什么问题导致的 或者说有什么办法解决或者缓解也行！

### G6 Version / G6 版本

4.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
你尝试先关掉动画看下

**Comment by AGG-an** [comment]
关掉动画之后基本不会出现了

**Comment by AGG-an** [comment]
这个问题会处理吗？

**Comment by Aarebecca** [comment]
@AGG-an 大概可能是打开动画之后机器性能不够导致掉帧然后最后几帧没有生效导致的。目前暂不会处理

**Comment by AGG-an** [comment]
好的
