### ISSUE TITLE
tabs may appear to be frozen when render the mindmap  with vue 

### ISSUE THREAD

**Issue by citrusjunoss** [antvis/G6#6334]
### Describe the bug / 问题描述

1. 参考官网场景示例 [mindmap](https://g6-next.antv.antgroup.com/examples/scene-case/default/#mindmap)， 删除了addNode 相关逻辑。
2. 在vue3 + vite 场景中会出现事件无效的问题，会有两种表现。其一，collapse-expand 不生效（同样demo中，原生js 没有问题，）。 其二 多次频繁点击Node 节点，或者页面刚渲染完成拖拽canvas。

<img width="1211" alt="image" src="https://github.com/user-attachments/assets/fc605a35-676d-475c-b9c7-4400e23050c1">

抱歉可能是vite 编译消耗性能的原因，demo 无法在stackblitz 或者其他的在线demo 上运行。附上github 仓库链接。

另外在vite 中，产生sourcemap貌似有问题，源码是g-lite/dist/index.esm.js, sourcemap 会指向g-lite/dist/services/EventService.d.ts 声明中导致无法调试

### Reproduction link / 重现链接

https://github.com/citrusjunoss/g6-midmap-vue3

### Steps to Reproduce the Bug or Issue / 重现步骤

1.  npm install 
2. npm run dev
3. drag-canvas or   frequent click node

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by resetsix** [comment]
我也没什么思路，你大概可以先这么排查：

1、是否关闭严格模式
2、组件卸载时是否清除上一次画布实例

tips：在线示例可以部署到`Github Page`，`Cloudflare`，`Vercel`，`Netlify`，`Fastly`

**Comment by citrusjunoss** [comment]
> 我也没什么思路，你大概可以先这么排查：
> 
> 1、是否关闭严格模式 2、组件卸载时是否清除上一次画布实例
> 
> tips：在线示例可以部署到`Github Page`，`Cloudflare`，`Vercel`，`Netlify`，`Fastly`

1. 严格模式是指什么？js的么，es6 之后默认严格模式吧。
2. 组件卸载销毁了。
3. 部署了不能编辑感觉不太好用，不如直接拉代码。部署地址https://citrusjunoss.github.io/g6-midmap-vue3/

**Comment by Aarebecca** [comment]
@citrusjunoss 严格模式是 React 下的一种模式，你提到组件销毁了是指出现了创建两次 Graph 的情况吗？
你可以创建 codesandbox 线上demo

**Comment by resetsix** [comment]
> @resetsix
> 
> > 我也没什么思路，你大概可以先这么排查：
> > 1、是否关闭严格模式 2、组件卸载时是否清除上一次画布实例
> > tips：在线示例可以部署到`Github Page`，`Cloudflare`，`Vercel`，`Netlify`，`Fastly`
> 
>     1. 严格模式是指什么？js的么，es6 之后默认严格模式吧。
> 
>     2. 组件卸载销毁了。
> 
>     3. 部署了不能编辑感觉不太好用，不如直接拉代码。部署地址https://citrusjunoss.github.io/g6-midmap-vue3/

Q1：什么是严格模式？

A1：严格模式(Strict Mode)是开发环境下的一种可选模式，在 React 中是默认开启的。Vue 我了解不是很多，但查阅后好像在 v3 后也会默认开启，具体用处可参考图片。

<img width="900" alt="图片" src="https://github.com/user-attachments/assets/2fcaec93-671b-4312-bf5a-67fef7aff9ef">

Q2：antv/g6 源码sourcemap映射有问题

A2：参考https://github.com/antvis/G6/discussions/6327#discussion-7171331

> 这个方法仅仅只能关闭警告信息，无法解决不能调试问题。具体G6映射问题还是需要楼上官方来解答。

Q3：demo 无法在 stackblitz 或者其他的在线 demo 上运行

A3：你可以尝试给出 **能复现问题的最小 demo** 在线示例，无需在stackblitz、codesandbox 上安装 vite。

**Comment by xiuyuan-wang** [comment]
我也遇到了
Describe the bug / 问题描述：
就是节点新增后，拖拽后就是报错，节点按钮事件也不生效。
![Uploading WechatIMG5.jpeg…]()

**Comment by citrusjunoss** [comment]
> @citrusjunoss 严格模式是 React 下的一种模式，你提到组件销毁了是指出现了创建两次 Graph 的情况吗？ 你可以创建 codesandbox 线上demo

线上创建了一直编译不出来，上面有说

**Comment by citrusjunoss** [comment]
> > @resetsix
> > > 我也没什么思路，你大概可以先这么排查：
> > > 1、是否关闭严格模式 2、组件卸载时是否清除上一次画布实例
> > > tips：在线示例可以部署到`Github Page`，`Cloudflare`，`Vercel`，`Netlify`，`Fastly`
> > 
> > 
> > ```
> > 1. 严格模式是指什么？js的么，es6 之后默认严格模式吧。
> > 
> > 2. 组件卸载销毁了。
> > 
> > 3. 部署了不能编辑感觉不太好用，不如直接拉代码。部署地址https://citrusjunoss.github.io/g6-midmap-vue3/
> > ```
> 
> Q1：什么是严格模式？
> 
> A1：严格模式(Strict Mode)是开发环境下的一种可选模式，在 React 中是默认开启的。Vue 我了解不是很多，但查阅后好像在 v3 后也会默认开启，具体用处可参考图片。
> 
> <img alt="图片" width="900" src="https://private-user-images.githubusercontent.com/85431995/367246090-2fcaec93-671b-4312-bf5a-67fef7aff9ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMzA4NTIsIm5iZiI6MTcyNjIzMDU1MiwicGF0aCI6Ii84NTQzMTk5NS8zNjcyNDYwOTAtMmZjYWVjOTMtNjcxYi00MzEyLWJmNWEtNjdmZWY3YWZmOWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDEyMjkxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0YzczNzg4NDc5NTZlZjNjZjdiOWQ2M2M1ZTA4MmI3ZTU4YzQ5YjRmOGNjYjY0NTA2MGYzOTliOGE0ZDQxOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A0wibV_WdWZWvRIV-bSiQvyTeLCN9BSG66hYogpeuYo">
> Q2：antv/g6 源码sourcemap映射有问题
> 
> A2：参考[#6327 (comment)](https://github.com/antvis/G6/discussions/6327#discussion-7171331)
> 
> > 这个方法仅仅只能关闭警告信息，无法解决不能调试问题。具体G6映射问题还是需要楼上官方来解答。
> 
> Q3：demo 无法在 stackblitz 或者其他的在线 demo 上运行
> 
> A3：你可以尝试给出 **能复现问题的最小 demo** 在线示例，无需在stackblitz、codesandbox 上安装 vite。

你说GitHub page 不是这个么

> 我也没什么思路，你大概可以先这么排查：
> 
> 1、是否关闭严格模式 2、组件卸载时是否清除上一次画布实例
> 
> tips：在线示例可以部署到`Github Page`，`Cloudflare`，`Vercel`，`Netlify`，`Fastly`

这个就是Github page 的地址https://citrusjunoss.github.io/g6-midmap-vue3/

**Comment by citrusjunoss** [comment]
> @citrusjunoss 严格模式是 React 下的一种模式，你提到组件销毁了是指出现了创建两次 Graph 的情况吗？ 你可以创建 codesandbox 线上demo
  组件销毁，是指我在vue组件卸载的时候销毁了Graph实例，回复@resetsix 排查的方案的。

下面是codesandbox 的在线示例。也可以复现的，只要点击节点多次，或者拖拽就会报错。然后浏览器就直接卡死了
https://codesandbox.io/p/sandbox/kkpz99?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm11gi2g800063b6ignt7cgnz%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm11gi2g800023b6idk0ye6lf%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm11gi2g800033b6ieo1cqyka%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm11gi2g800053b6iwzybse2l%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm11gi2g800023b6idk0ye6lf%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm11gi2g800013b6i6kjr5l98%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cm11h28g900023b6ibdiggi9t%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A14%252C%2522startColumn%2522%253A5%252C%2522endLineNumber%2522%253A14%252C%2522endColumn%2522%253A5%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cm11h6jif00023b6ibrwoe1bb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A180%252C%2522startColumn%2522%253A12%252C%2522endLineNumber%2522%253A180%252C%2522endColumn%2522%253A12%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cm11gi2g800023b6idk0ye6lf%2522%252C%2522activeTabId%2522%253A%2522cm11h6jif00023b6ibrwoe1bb%2522%257D%252C%2522cm11gi2g800053b6iwzybse2l%2522%253A%257B%2522id%2522%253A%2522cm11gi2g800053b6iwzybse2l%2522%252C%2522activeTabId%2522%253A%2522cm11gtil5006j3b6imndaoi2g%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm11gi2g800043b6iwyjlyw9x%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522cm11gtil5006j3b6imndaoi2g%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cm11gi2g800033b6ieo1cqyka%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm11gi2g800033b6ieo1cqyka%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by uhobnil** [comment]
看起来和vue的响应式有关，graph改成普通变量不会报错卡死

**Comment by Aarebecca** [comment]
> 看起来和vue的响应式有关，graph改成普通变量不会报错卡死

@citrusjunoss 是的，graph 是一个相当大的对象，所以不用使用 vue 的响应式系统来拦截 graph 对象

**Comment by citrusjunoss** [comment]
> > 看起来和vue的响应式有关，graph改成普通变量不会报错卡死
> 
> @citrusjunoss 是的，graph 是一个相当大的对象，所以不用使用 vue 的响应式系统来拦截 graph 对象

普通变量确实可以工作
