### ISSUE TITLE
graph.updateLayout

### ISSUE THREAD

**Issue by aixinlian** [antvis/G6#6340]
### Describe the bug / 问题描述

graph.updateLayout is not a function,找不到这个方法怎么解决啊

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by uhobnil** [comment]
[升级到5.0](https://g6-next.antv.antgroup.com/manual/upgrade) updateLayout变更为了setLayout
