### ISSUE TITLE
After the canvas accent color is changed, the minimap accent color remains unchanged

### ISSUE THREAD

**Issue by Zzm0809** [antvis/G6#6344]
### Describe the bug / 问题描述

画布主题色改变之后 缩略图(minimap) 主题色未改变

### Steps to Reproduce the Bug or Issue / 重现步骤

如图:

<img width="882" alt="image" src="https://github.com/user-attachments/assets/654f009d-49c0-4e31-9d47-6344f8626c1f">

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by resetsix** [comment]
目前部分插件未完全适配主题色，后续会进行该工作。

参考：https://github.com/antvis/G6/discussions/6311
