### ISSUE TITLE
Window.getComputedStyle: Argument 1 is not an object.

### ISSUE THREAD

**Issue by addriumruss** [antvis/G6#6345]
### Describe the bug / 问题描述

Uncaught runtime errors:
ERROR
Window.getComputedStyle: Argument 1 is not an object.
getContainerSize@webpack-internal:///./node_modules/.pnpm/@antv+g6@5.0.22_workerize-loader@2.0.2_webpack@5.94.0_/node_modules/@antv/g6/esm/utils/dom.js:17:33
sizeOf@webpack-internal:///./node_modules/.pnpm/@antv+g6@5.0.22_workerize-loader@2.0.2_webpack@5.94.0_/node_modules/@antv/g6/esm/utils/dom.js:32:61
initCanvas@webpack-internal:///./node_modules/.pnpm/@antv+g6@5.0.22_workerize-loader@2.0.2_webpack@5.94.0_/node_modules/@antv/g6/esm/runtime/graph.js:809:79
prepare@webpack-internal:///./node_modules/.pnpm/@antv+g6@5.0.22_workerize-loader@2.0.2_webpack@5.94.0_/node_modules/@antv/g6/esm/runtime/graph.js:868:16
ERROR
Window.getComputedStyle: Argument 1 is not an object.
getContainerSize@webpack-internal:///./node_modules/.pnpm/@antv+g6@5.0.22_workerize-loader@2.0.2_webpack@5.94.0_/node_modules/@antv/g6/esm/utils/dom.js:17:33
sizeOf@webpack-internal:///./node_modules/.pnpm/@antv+g6@5.0.22_workerize-loader@2.0.2_webpack@5.94.0_/node_modules/@antv/g6/esm/utils/dom.js:32:61
initCanvas@webpack-internal:///./node_modules/.pnpm/@antv+g6@5.0.22_workerize-loader@2.0.2_webpack@5.94.0_/node_modules/@antv/g6/esm/runtime/graph.js:809:79
prepare@webpack-internal:///./node_modules/.pnpm/@antv+g6@5.0.22_workerize-loader@2.0.2_webpack@5.94.0_/node_modules/@antv/g6/esm/runtime/graph.js:868:16
async*render@webpack-internal:///./node_modules/.pnpm/@antv+g6@5.0.22_workerize-loader@2.0.2_webpack@5.94.0_/node_modules/@antv/g6/esm/runtime/graph.js:886:16
initGraph@webpack-internal:///./node_modules/.pnpm/babel-loader@8.4.1_@babel+core@7.25.2_webpack@5.94.0/node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/.pnpm/vue-loader@15.11.1_@vue+compiler-sfc@3.5.6_css-loader@6.11.0_webpack@5.94.0__lodash@4.17.21_v_nlqk7vo2zc6ayaxamjxrjj553y/node_modules/vue-loader/lib/index.js??vue-loader-options!./src/components/HelloWorld.vue?vue&type=script&lang=js:104:13
mounted@webpack-internal:///./node_modules/.pnpm/babel-loader@8.4.1_@babel+core@7.25.2_webpack@5.94.0/node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/.pnpm/vue-loader@15.11.1_@vue+compiler-sfc@3.5.6_css-loader@6.11.0_webpack@5.94.0__lodash@4.17.21_v_nlqk7vo2zc6ayaxamjxrjj553y/node_modules/vue-loader/lib/index.js??vue-loader-options!./src/components/HelloWorld.vue?vue&type=script&lang=js:108:10
invokeWithErrorHandling@webpack-internal:///./node_modules/.pnpm/vue@2.7.16/node_modules/vue/dist/vue.runtime.esm.js:2924:57
callHook$1@webpack-internal:///./node_modules/.pnpm/vue@2.7.16/node_modules/vue/dist/vue.runtime.esm.js:3896:30
insert@webpack-internal:///./node_modules/.pnpm/vue@2.7.16/node_modules/vue/dist/vue.runtime.esm.js:4263:17
invokeInsertHook@webpack-internal:///./node_modules/.pnpm/vue@2.7.16/node_modules/vue/dist/vue.runtime.esm.js:6555:30
patch@webpack-internal:///./node_modules/.pnpm/vue@2.7.16/node_modules/vue/dist/vue.runtime.esm.js:6746:21
lifecycleMixin/Vue.prototype._update@webpack-internal:///./node_modules/.pnpm/vue@2.7.16/node_modules/vue/dist/vue.runtime.esm.js:3639:19
updateComponent@webpack-internal:///./node_modules/.pnpm/vue@2.7.16/node_modules/vue/dist/vue.runtime.esm.js:3736:10
Watcher</Watcher.prototype.get@webpack-internal:///./node_modules/.pnpm/vue@2.7.16/node_modules/vue/dist/vue.runtime.esm.js:3330:27
Watcher</Watcher.prototype.run@webpack-internal:///./node_modules/.pnpm/vue@2.7.16/node_modules/vue/dist/vue.runtime.esm.js:3401:24
flushSchedulerQueue@webpack-internal:///./node_modules/.pnpm/vue@2.7.16/node_modules/vue/dist/vue.runtime.esm.js:3986:13
nextTick/<@webpack-internal:///./node_modules/.pnpm/vue@2.7.16/node_modules/vue/dist/vue.runtime.esm.js:3043:12
flushCallbacks@webpack-internal:///./node_modules/.pnpm/vue@2.7.16/node_modules/vue/dist/vue.runtime.esm.js:2971:14
promise callback*timerFunc@webpack-internal:///./node_modules/.pnpm/vue@2.7.16/node_modules/vue/dist/vue.runtime.esm.js:2996:9
nextTick@webpack-internal:///./node_modules/.pnpm/vue@2.7.16/node_modules/vue/dist/vue.runtime.esm.js:3053:5
queueWatcher@webpack-internal:///./node_modules/.pnpm/vue@2.7.16/node_modules/vue/dist/vue.runtime.esm.js:4068:13
Watcher</Watcher.prototype.update@webpack-internal:///./node_modules/.pnpm/vue@2.7.16/node_modules/vue/dist/vue.runtime.esm.js:3392:19
lifecycleMixin/Vue.prototype.$forceUpdate@webpack-internal:///./node_modules/.pnpm/vue@2.7.16/node_modules/vue/dist/vue.runtime.esm.js:3661:19
exports.reload</<@webpack-internal:///./node_modules/.pnpm/vue-hot-reload-api@2.3.4/node_modules/vue-hot-reload-api/dist/index.js:234:31
exports.reload<@webpack-internal:///./node_modules/.pnpm/vue-hot-reload-api@2.3.4/node_modules/vue-hot-reload-api/dist/index.js:232:28
tryWrap/<@webpack-internal:///./node_modules/.pnpm/vue-hot-reload-api@2.3.4/node_modules/vue-hot-reload-api/dist/index.js:114:9
@webpack-internal:///./src/components/HelloWorld.vue:34:11
./src/components/HelloWorld.vue@http://localhost:8080/js/app.js:107:1
__webpack_require__@http://localhost:8080/js/app.js:255:32
_requireSelf@http://localhost:8080/js/app.js:545:34
apply@http://localhost:8080/js/app.js:1244:22
internalApply/<@http://localhost:8080/js/app.js:785:36
internalApply@http://localhost:8080/js/app.js:783:21
hotCheck/</</</<@http://localhost:8080/js/app.js:721:26
waitForBlockingPromises@http://localhost:8080/js/app.js:676:48
hotCheck/</</<@http://localhost:8080/js/app.js:719:24
promise callback*hotCheck/</<@http://localhost:8080/js/app.js:718:18
promise callback*hotCheck/<@http://localhost:8080/js/app.js:699:43
promise callback*hotCheck@http://localhost:8080/js/app.js:690:15
check@webpack-internal:///./node_modules/.pnpm/webpack@5.94.0/node_modules/webpack/hot/dev-server.js:15:5
@webpack-internal:///./node_modules/.pnpm/webpack@5.94.0/node_modules/webpack/hot/dev-server.js:69:4
emit@webpack-internal:///./node_modules/.pnpm/events@3.3.0/node_modules/events/events.js:127:17
reloadApp@webpack-internal:///./node_modules/.pnpm/webpack-dev-server@4.15.2_debug@4.3.7_webpack@5.94.0/node_modules/webpack-dev-server/client/utils/reloadApp.js:42:67
ok@webpack-internal:///./node_modules/.pnpm/webpack-dev-server@4.15.2_debug@4.3.7_webpack@5.94.0/node_modules/webpack-dev-server/client/index.js?protocol=ws&hostname=192.168.1.5&port=8080&pathname=%2Fws&logging=none&progress=true&overlay=%7B%22errors%22%3Atrue%2C%22warnings%22%3Afalse%7D&reconnect=10&hot=true&live-reload=true:286:68
initSocket/<@webpack-internal:///./node_modules/.pnpm/webpack-dev-server@4.15.2_debug@4.3.7_webpack@5.94.0/node_modules/webpack-dev-server/client/socket.js:69:29
onMessage/this.client.onmessage@webpack-internal:///./node_modules/.pnpm/webpack-dev-server@4.15.2_debug@4.3.7_webpack@5.94.0/node_modules/webpack-dev-server/client/clients/WebSocketClient.js:81:10

### Steps to Reproduce the Bug or Issue / 重现步骤

使用vue2新建一个项目， pnpm add @antv/g6，随便显示一个g6图，编译，运行，出错

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Firefox

**Comment by resetsix** [comment]
为了更好地帮助您解决问题，我们需要更多的信息和一个可以复现问题的在线示例。这将使我们能够更快、更准确地诊断和解决问题。

请您提供以下内容：

1、 一个可以在线运行的最小化示例，比如使用 CodeSandbox、StackBlitz 等平台。

我初步判断是你没有给画布容器或画布父容器指定**宽高**。

**Comment by Aarebecca** [comment]
如上所示，大概率是没有传入容器，或者没有容器尺寸
