### ISSUE TITLE
Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.

### ISSUE THREAD

**Issue by sunsou1** [antvis/G6#6349]
### Describe the bug / 问题描述

Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.

### Reproduction link / 重现链接

https://codesandbox.io/p/sandbox/epic-stonebraker-33rrv6?file=%2Findex.js%3A16%2C26

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by sunsou1** [comment]
![image](https://github.com/user-attachments/assets/9f762855-c3b5-4aaa-9f89-a4883b38caa9)
我看官网上这个node里配置的innerHTML属性。
我如果放到数据里，怎么配置呢？

**Comment by sunsou1** [comment]
@resetsix 
![image](https://github.com/user-attachments/assets/184d8cb6-0607-4d6e-997a-2d03e4b0ba0d)
我参考的这个。

**Comment by resetsix** [comment]
> 我如果放到数据里，怎么配置呢？

`innerHTML`的位置你放错了。

✅正确位置应该是：
```tsx
const graph = new Graph({
  container: xxx,
  data:xxx,
  node: {
    type: xxx,
    size: xxx,
    style: {
      innerHTML
    },
  },
});
```

❌而你放在了data属性里：
```tsx
const graph = new Graph({
  container: xxx,
  data:{
    nodes:[innerHTML],
    edges:[],
  },
  node: {
    type: xxx,
    size: xxx,
    style: {
      //...
    },
  },
});
```

data 数据下的 `nodes` 和 样式对象 `node` 区别请阅读文档：

- [Data - 数据](https://g6-next.antv.antgroup.com/manual/core-concept/data)
- [State - 状态](https://g6-next.antv.antgroup.com/manual/core-concept/state)

---

项目报错的原因应该也是因为`innerHTML`位置不正确导致。
