### ISSUE TITLE
G63.0版本如何做到鼠标移入某节点时高亮所有相邻的节点

### ISSUE THREAD

**Issue by mingugu** [antvis/g6#635]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by elaine1234** [comment]
```js
graph.on('node:mouseenter', e => {
  const item = e.item;
  // 获取该节点所有连线
  const edges =item.getEdges();
  edges.forEach(edge => {、
   // 获取相邻节点，高亮
    if (edge.getSource() === item) {
      graph.setItemState(edge.getTarget(), 'active', true);
    } else {
      graph.setItemState(edge.getSource(), 'active', false);
    }
  });
});
// 监听mouseout事件，重置节点状态逻辑同上
```

**Comment by mingugu** [comment]
> ```js
> graph.on('node:mouseenter', e => {
>   const item = e.item;
>   // 获取该节点所有连线
>   const edges =item.getEdges();
>   edges.forEach(edge => {、
>    // 获取相邻节点，高亮
>     if (edge.getSource() === item) {
>       graph.setItemState(edge.getTarget(), 'active', true);
>     } else {
>       graph.setItemState(edge.getSource(), 'active', false);
>     }
>   });
> });
> // 监听mouseout事件，重置节点状态逻辑同上
> ```

是不是需要声明一个state为active？按照您的步骤加上去没有效果呢

**Comment by elaine1234** [comment]
https://www.yuque.com/antv/g6/gq1m6a

**Comment by loveJasmine** [comment]
4.7.0版本好像不可以呢
