### ISSUE TITLE
After using a custom React node, the layout of the edges is skewed

### ISSUE THREAD

**Issue by resetsix** [antvis/G6#6352]
## 背景描述

在使用自定义 React 节点和内置的 dagre 布局算法时,发现边的布局效果与预期不符。具体表现为:

1. 使用内置节点时,边的控制点折线后是水平的。
2. 使用自定义 React 节点后,边的控制点折线后变成了斜线。

## 预期效果

（使用自定义节点）边的布局效果应与使用内置节点时相同,控制点折线后应为水平线。

<img width="934" alt="图片" src="https://github.com/user-attachments/assets/e1d21b35-47aa-4770-a631-f730c3fca77e">

## 实际效果

边的控制点折线后呈斜线,与预期不符。

<img width="961" alt="图片" src="https://github.com/user-attachments/assets/2d2b6a80-32c7-4f67-b59a-fbcd6845cf84">

### Reproduction link / 重现链接

https://codesandbox.io/p/sandbox/73mjj4

### Steps to Reproduce the Bug or Issue / 重现步骤

1. 使用 `@antv/g6-extension-react` 中的 `ReactNode` 创建自定义节点
2. 在图配置中设置 `node.type: "reactNode"`
3. 使用 `antv-dagre` 布局,设置 `rankdir: "LR"`
4. 渲染图形

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome, Firefox

**Comment by yvonneyx** [comment]
html 节点原点在左上角，这里需要额外处理一下，添加属性 `{ "dx": -size[0]/2, "dy": -size[1]/2 }`

**Comment by resetsix** [comment]
> html 节点原点在左上角，这里需要额外处理一下，添加属性 `{ "dx": -size[0]/2, "dy": -size[1]/2 }`

好的解决了。感觉跟 https://github.com/antvis/G6/issues/6351 问题很像，都是自定义节点后 edge 出现问题
