### ISSUE TITLE
How do I dynamically add new edges like in 4.x?

### ISSUE THREAD

**Issue by ZhouYC404** [antvis/G6#6357]
### Describe the bug / 问题描述

![image](https://github.com/user-attachments/assets/dfff1bfe-d5d1-4151-b756-2d759ecf974a)

请问如何通过上下文菜单来新增边，而不是默认的behavior那样通过点击和拖拽新增？

本来想像4.x的demo那样手写监听事件的方式来实现，但是监听canvas:pointermove事件的时候每次都要调用graph.draw方法不然edge不会实时更新位置，但是这样页面就会很卡顿；而且edge的target也不能像4.x那样直接指向一个坐标了，必须指向一个node的id。

内置的新增边功能还有一个bug，就是新增边后，在页面第一帧时，edge会飞到canvas的左上角去：

![image](https://github.com/user-attachments/assets/6f259680-4c3f-417f-803f-f2be60cba64d)

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by ZhouYC404** [comment]
把源码中的create-edge代码抽出来魔改了一个自定义的新增边，也算解决问题了。

**Comment by Aarebecca** [comment]
> 内置的新增边功能还有一个bug，就是新增边后，在页面第一帧时，edge会飞到canvas的左上角去

这个问题目前已经解决
