### ISSUE TITLE
[V5] When using antv-dagre layout, you can't scroll down to the middle, you can only drag and drop to the node at the bottom.

### ISSUE THREAD

**Issue by xigua1994** [antvis/G6#6358]
### Describe the bug / 问题描述

[V5] 使用antv-dagre layout时滚动到中间就无法滚动下去，只能用拖拽画布拉到底部的node。

### Reproduction link / 重现链接

https://codesandbox.io/p/sandbox/nostalgic-julien-c2mtdd?file=%2Findex.jsx%3A209%2C12

### Steps to Reproduce the Bug or Issue / 重现步骤

使用鼠标滚动到画布的一半就卡住了，只能拖拽画布拉到底部才能看到剩下的node.

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by uhobnil** [comment]
[scroll canvas有个配置 range](https://g6-next.antv.antgroup.com/api/behaviors/scroll-canvas#range) ，配置成1应该可以解决
 
文档和代码不对应，代码默认值是0.5，文档中写的是1

**Comment by xigua1994** [comment]
> [scroll canvas有个配置 range](https://g6-next.antv.antgroup.com/api/behaviors/scroll-canvas#range) ，配置成1应该可以解决
> 
> 文档和代码不对应，代码默认值是0.5，文档中写的是1

设置成1还是不行，得设置成画布实际高度/画布容器高度才行。

**Comment by uhobnil** [comment]
> > [scroll canvas有个配置 range](https://g6-next.antv.antgroup.com/api/behaviors/scroll-canvas#range) ，配置成1应该可以解决
> > 文档和代码不对应，代码默认值是0.5，文档中写的是1
> 
> 设置成1还是不行，得设置成画布实际高度/画布容器高度才行。

那设置成Infinity吧

**Comment by xigua1994** [comment]
> > > [scroll canvas有个配置 range](https://g6-next.antv.antgroup.com/api/behaviors/scroll-canvas#range) ，配置成1应该可以解决
> > > 文档和代码不对应，代码默认值是0.5，文档中写的是1
> > 
> > 
> > 设置成1还是不行，得设置成画布实际高度/画布容器高度才行。
> 
> 那设置成Infinity吧，但滚动过远距离会很难找回来....

是的，所以设置成画布实际高度/画布容器高度 附近比较好

**Comment by uhobnil** [comment]
> > > > [scroll canvas有个配置 range](https://g6-next.antv.antgroup.com/api/behaviors/scroll-canvas#range) ，配置成1应该可以解决
> > > > 文档和代码不对应，代码默认值是0.5，文档中写的是1
> > > 
> > > 
> > > 设置成1还是不行，得设置成画布实际高度/画布容器高度才行。
> > 
> > 
> > 那设置成Infinity吧，但滚动过远距离会很难找回来....
> 
> 是的，所以设置成画布实际高度/画布容器高度 附近比较好

range如果支持传入一个方法，根据dx,dy和所有node的坐标计算出具体的range就好了

**Comment by Aarebecca** [comment]
ScrollCanvas range 先设置为 Infinity，G6 后面会更新一下默认值为 Infinity
