### ISSUE TITLE
v5 collapse-expand doesn't work

### ISSUE THREAD

**Issue by priesty** [antvis/G6#6372]
### Describe the bug / 问题描述

官网示例https://g6-next.antv.antgroup.com/zh/examples/layout/mindmap/#right-side 属性collapse-expand不起作用，很偶尔地会触发收起，基本不起作用，4.x没问题

### Reproduction link / 重现链接

https://g6-next.antv.antgroup.com/zh/examples/layout/mindmap/#right-side

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
具体描述下复现路径

**Comment by priesty** [comment]
> 具体描述下复现路径

https://g6-next.antv.antgroup.com/zh/examples/layout/mindmap/#right-side 就这个链接，单双击都没有反应

**Comment by yvonneyx** [comment]
默认触发方式是双击节点，我这边是ok的，你再试下？

**Comment by priesty** [comment]
> 默认触发方式是双击节点，我这边是ok的，你再试下？

不行，换浏览器也没用，想了解下大概会跟啥有关呢

**Comment by zhangkb** [comment]
默认的双击，官网的案例可以触发，但是会比较难触发。不过我将触发方式修改为click之后效果就很顺滑

**Comment by priesty** [comment]
> 默认的双击，官网的案例可以触发，但是会比较难触发。不过我将触发方式修改为click之后效果就很顺滑

怎么改呀，有例子么

**Comment by zhangkb** [comment]
你把trigger修改为click就行了

**Comment by yvonneyx** [comment]
交互相关配置项可以参考 https://g6-next.antv.antgroup.com/api/behaviors/collapse-expand
如果能解决你的问题，记得关一下 issue 哦~
