### ISSUE TITLE
V5 translateTo is wrong when zoom is not equal to 1

### ISSUE THREAD

**Issue by hh1412** [antvis/G6#6373]
### Describe the bug / 问题描述

当我知道图的位置和缩放状态1 我拖拽图改变位置到状态2 当我想使用translateTo回复到状态1时 位置不对  当zoom=1时 位置回复是正常的 也就是说当 zoom不等于1时 调用translateTo 图的位置不对

https://github.com/user-attachments/assets/9025bf95-f025-42d9-9c53-6c8613f2b549

### Steps to Reproduce the Bug or Issue / 重现步骤

graph.zoomTo(0.5)
let a = graph.getPosition()
拖拽到另一个位置
let b = graph.getPosition()
graph.translateTo(a)
位置不对
https://github.com/user-attachments/assets/9025bf95-f025-42d9-9c53-6c8613f2b549

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
graph 位置和元素位置不是一回事，如果你是想将画布中心移动到某个元素上，直接调用 `focusElement` 即可

**Comment by hh1412** [comment]
> graph 位置和元素位置不是一回事，如果你想将收购中心移动到某个元素上，直接调用`focusElement`即可

不是 focusElement满足不了 我是想拖拽了graph 然后再复原回上一步的位置

**Comment by Rey-Wang** [comment]
@hh1412 history的插件？history.undo

**Comment by Mnikley** [comment]
still an issue as of today with v5.0.47. The only fix is to memorize the zoom, set the zoom to 1, translate to a position, and to restore the zoom.

https://jsfiddle.net/jsqo9mkt/

**Comment by WebGeniusLT** [comment]
> still an issue as of today with v5.0.47. The only fix is to memorize the zoom, set the zoom to 1, translate to a position, and to restore the zoom.
> 
> https://jsfiddle.net/jsqo9mkt/
I also encountered this problem, and the solution above helped me resolve it.
