### ISSUE TITLE
[V5] Behavior change of 'Hover activate' from the version succeeding 5.0.21

### ISSUE THREAD

**Issue by bartoval** [antvis/G6#6377]
### Describe the bug / 问题描述

I implemented a similar behaviour to this example https://g6-next.antv.antgroup.com/en/examples/behavior/highlight-element/#config-params . However, my case it's slightly different: When I mouseout, the default situation is restored.
  
My behavior works up to the version 5.021, but, in subsequent versions, the mouseover effect is maintained even when I mouse out the element (as in the example).

Has something changed from the version **succeeding 5.0.21?**

This is my configuration:

```const HOVER_ACTIVATE_BEHAVIOR = {
  HOVER_DEGREE_0_NODE: {
    // state for the node with state hover
    key: 'hover-activate-single-node',
    type: 'hover-activate',
    degree: 0,
    state: GraphElementStates.HoverNode, // highlight the node
    enable: ({ targetType }: IPointerEvent) => targetType === 'node'
  },

  HOVER_DEGREE_1_NODE: {
    // state for the rest of the nodes
    key: 'hover-activate',
    type: 'hover-activate',
    degree: 1,
    state: GraphElementStates.Visible, // keep visible nodes without highlighting them
    inactiveState: GraphElementStates.Hidden, // hide neighbors nodes
    enable: ({ targetType }: IPointerEvent) => targetType === 'node'
  },

  HOVER_DEGREE_0_EDGE: {
    // state for the edge with state hover
    key: 'hover-activate-single-edge',
    type: 'hover-activate',
    degree: 0,
    state: GraphElementStates.HoverEdge, // just highlight the edge. No behavior change for nodes
    enable: ({ targetType }: IPointerEvent) => targetType === 'edge'
  }
}
```

I've noticed that in versions up to 5.0.21,  if I remove the '**enable**' property from my configuration, I can restore the initial situation when I exit the elements. However, I've encountered a few issues without using "enable":

-  When I highlight edges, I don't want any changes to occur with the nodes. I only want to highlight the edge.
-  Now Combos are currently involved in these behaviors (They should not). When I mouse over a combo, the edges disappear and the nodes become semi-transparent.

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Linux

### Browser / 浏览器

Chrome

**Comment by yvonneyx** [comment]
To handle events when the mouse moves over the canvas, try modifying the code to `enable: (event) => ['node', 'canvas'].includes(event.targetType)`
