### ISSUE TITLE
[V5] html node implements saving coordinates, which are automatically positioned the next time they are rendered

### ISSUE THREAD

**Issue by xl4ng** [antvis/G6#6378]
### Describe the bug / 问题描述

请问G6如何实现html节点拖动后保存坐标，下次渲染时节点自动定位？目前通过保存e.canvas.x、e.canvas.y，在下次渲染时均会便宜。

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by yvonneyx** [comment]
根据您的需求分析，建议保存两个位置：节点位置和当前视口中心位置

**Comment by yvonneyx** [comment]
由于目前没有进一步的信息，我们将暂时关闭此 issue。如果您在尝试我们的建议后仍然遇到问题，或者有更多的细节可以提供，请随时重新打开 🌹
