### ISSUE TITLE
G6 automatic layout, I set the layout layout: { type: 'antv-dagre', rankdir: 'RL'}, when setting the rankdir attribute to RL, type: 'cubic-horizontal', it will not work and become the default straight line, it is no problem to set it to LR.

### ISSUE THREAD

**Issue by brq666** [antvis/G6#6388]
### Describe the bug / 问题描述

G6自动布局，我设置布局layout: { type: 'antv-dagre', rankdir: 'RL'},  在设置rankdir属性为RL的时候，type: 'cubic-horizontal',就失效变成默认的直线了，设置为LR是没问题。

### Steps to Reproduce the Bug or Issue / 重现步骤

G6自动布局，我设置布局layout: { type: 'antv-dagre', rankdir: 'RL'},  在设置rankdir属性为RL的时候，type: 'cubic-horizontal',就失效变成默认的直线了，设置为LR是没问题。

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

### Additional context / 补充说明

G6自动布局，我设置布局layout: { type: 'antv-dagre', rankdir: 'RL'},  在设置rankdir属性为RL的时候，type: 'cubic-horizontal',就失效变成默认的直线了，设置为LR是没问题。

**Comment by yvonneyx** [comment]
我这里没有复现你提到的问题，请贴一个复现链接方便我们定位问题~

**Comment by yvonneyx** [comment]
我们已经对该问题进行了初步排查，并没有复现相关缺陷。由于目前没有进一步的信息，我们将暂时关闭此问题。如果您有有更多的细节可以提供，请随时重新打开此 issue，或者发起一个新的 🌹
