### ISSUE TITLE
3.0版本开发树图时怎么设置边的label ？

### ISSUE THREAD

**Issue by JiangJun1994** [antvis/g6#639]
我用下面这个方法实现合适吗？    
this.graph.getEdges().forEach(edge => {
      edge.get("model").shape = "cubic-horizontal";
      edge.get("model").label = "1234";
      edge.get("model").labelCfg = {
        autoRotate: true,
        position: 'center',
        style: {
          stroke: 'white',
          lineWidth: 43,
          width: '43px',
          height: '23px',
          cursor: 'pointer',
        }
      }
    });

**Comment by elaine1234** [comment]
可以这么实现的。
有个小问题：G6里面，`width`或`height`都不支持指定字符串，直接用数字就可以。

**Comment by JiangJun1994** [comment]
> 可以这么实现的。
> 有个小问题：G6里面，`width`或`height`都不支持指定字符串，直接用数字就可以。

我按照上面的方法有效果，但是有个问题，我收缩节点的时候会有报错：
![image](https://user-images.githubusercontent.com/25809468/53871703-bd9be400-4037-11e9-82b9-6d27cf716543.png)

**Comment by elaine1234** [comment]
问题已找到，在beta.16版本中修复。

**Comment by dd1994** [comment]
你真是个天才，想到了这种方法
