### ISSUE TITLE
Home page is not working

### ISSUE THREAD

**Issue by vikramparihar** [antvis/G6#6393]
Please check your website home page:
http://g6-v3-2.antv.vision/en/docs/manual/getting-started

I have tried many ways but still unable to plot the chart.

**Comment by yvonneyx** [comment]
The latest G6 5.0 official website is https://g6-next.antv.antgroup.com/manual/getting-started/quick-start

If you need to view examples for version 3.x, you need to manually switch the dependency package version. By default, the latest version is loaded, which causes the demo to fail.
