### ISSUE TITLE
The layout using antv-dagre and orthogonal routing for flowcharts generates unnecessary control points.

### ISSUE THREAD

**Issue by Cay222** [antvis/G6#6397]
### Describe the bug / 问题描述

![image](https://github.com/user-attachments/assets/6d60a7ac-a705-467b-89bf-e4abeca09039)
流程图对从WF7-002节指向WF8-004节点的这条边产生了多余的控制点，我希望可以实现红色箭头的效果。

### Reproduction link / 重现链接

https://codesandbox.io/p/sandbox/vrtql6

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by yvonneyx** [comment]
试下调整布局参数 nodeSize

**Comment by Cay222** [comment]
![调整布局参数nodeSize](https://github.com/user-attachments/assets/64bcea16-71a8-4292-a3ed-8a48e84a1a0f)
我是这样设置的 `nodeSize`，不知道为什么没有生效，还是有一样的问题。

**Comment by yvonneyx** [comment]
贴一个在线演示链接吧

**Comment by yvonneyx** [comment]
这是由于 dagre 布局计算出来的控制点在节点两侧，没在节点中心轴上导致的。

![image](https://github.com/user-attachments/assets/9d4be7aa-1b6a-4095-a496-d991fd47fe8d)

有两种方式来解决：
1. 基于 dagre 自定义布局，复写控制点计算逻辑，效果可控
2. 忽略布局计算的控制点，借助折线的正交路由来绘制，效果不可控

```
  edge: {
    type: 'polyline',
    style: {
      endArrow: true,
      controlPoints: [],
      router: {
        type: 'orth',
        padding: 30
      }
    },
  },
```

**Comment by Cay222** [comment]
非常感谢！问题已解决。👍👍👍
