### ISSUE TITLE
registNode是html格式的时候，节点的外框样式可以自定义的么？或者隐藏节点的外框？

### ISSUE THREAD

**Issue by YYmmlin** [antvis/g6#64]
![image](https://user-images.githubusercontent.com/12744546/29309334-d379faee-81db-11e7-95e4-f78f123e07a8.png)

registNode是html格式的时候，外框是默认上图的样式。
那么我想问 ，节点格式为HTML的外框样式可以自定义的么？或者隐藏节点的外框？

**Comment by TomHuangCN** [comment]
net.node().style({stroke: null});
