### ISSUE TITLE
force-atlas2 layout does not works well

### ISSUE THREAD

**Issue by abc3660170** [antvis/G6#6402]
### Describe the bug / 问题描述

force-atlas2 布局下，如果大量source节点连接一个target节点布局会失败，反之一个source连接大量target节点则不会有问题

### Reproduction link / 重现链接

https://stackblitz.com/edit/react-vqdqdc-owsw1w?file=package.json,index.js

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by yvonneyx** [comment]
上述提到的行为受到多种因素的影响，包括布局算法的内部实现、布局配置参数以及数据本身的特性。如果布局效果不满意，可以调整参数或者根据数据特征选择合适的布局

https://g6-next.antv.antgroup.com/api/layouts/force-atlas2-layout#%E9%85%8D%E7%BD%AE%E9%A1%B9
