### ISSUE TITLE
G6编辑器开发底层

### ISSUE THREAD

**Issue by SKY-Hao** [antvis/g6#641]
您好！
打扰了，想问您这边下
G6编辑器是用什么开发的？nodeJs吗？
我自己一个练习项目中用的是SpringBoot做的，不知道能不能集成过来G6？
如果可以集成的话是不是要做前后端分离？

**Comment by guozhaolong** [comment]
大哥。。。你问的这个问题暴露了很多问题啊，springboot是后端框架，跟前端没关系啊

**Comment by dxq613** [comment]
建议使用最新的 g6 3.0 自己开发一个编辑器。

**Comment by SKY-Hao** [comment]
主要是我不会前端




| |
黄
邮箱：hth_swp@163.com
|

签名由 网易邮箱大师 定制

在2019年03月28日 16:50，dong 写道：

Closed #641.
