### ISSUE TITLE
collapse-expand does not take effect, version 5.0.24

### ISSUE THREAD

**Issue by halaproliu** [antvis/G6#6412]
### Describe the bug / 问题描述

使用collapse-expand插件，展开收缩不生效

### Reproduction link / 重现链接

https://stackblitz.com/edit/vitejs-vite-cnvaiy?file=src%2FApp.vue

### Steps to Reproduce the Bug or Issue / 重现步骤

复现链接中有

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

### Additional context / 补充说明

麻烦帮忙看下

**Comment by yvonneyx** [comment]
`collapse-expand` 交互会去处理节点数据中的 children 字段，请先检查数据中是否包含此字段

```ts
interface NodeData {
    id: ID;
    type: string;
    data?: Record<string, unknown>;
    children?: ID[];
}
```

**Comment by halaproliu** [comment]
> `collapse-expand` 交互会去处理节点数据中的 children 字段，请先检查数据中是否包含此字段
> 
> ```ts
> interface NodeData {
>     id: ID;
>     type: string;
>     data?: Record<string, unknown>;
>     children?: ID[];
> }
> ```

https://g6-next.antv.antgroup.com/zh/examples/scene-case/default#organization-chart组织架构图的这个demo数据是不含children字段的，所以这种图标是不能折叠展开的嘛

**Comment by yvonneyx** [comment]
直接加交互肯定是没办法生效的呀，需要再处理一下数据~

**Comment by halaproliu** [comment]
> 直接加交互肯定是没办法生效的呀，需要再处理一下数据~

其实相当于是，如果数据结构是带children的，插件会自动处理。但是如果没有带的话，需要自己通过onCollpse和onExpand函数去处理吧？

**Comment by yvonneyx** [comment]
无论是使用内置的 `collapse-expand `交互，还是使用 graph API `expandElement` 和 `collapseElement`，都需要消费 children 字段，以告知哪些元素需要被展开或收起。否则，从数据层面很难推断出需要展开或收起的元素。

**Comment by halaproliu** [comment]
> 无论是使用内置的 `collapse-expand `交互，还是使用 graph API `expandElement` 和 `collapseElement`，都需要消费 children 字段，以告知哪些元素需要被展开或收起。否则，从数据层面很难推断出需要展开或收起的元素。

目前dagre布局，所使用的data结构是GraphData类型的，是否意味着这种布局无法使用collapse-expand组件？

**Comment by yvonneyx** [comment]
你预处理一下数据不就可以了？

halapro.liu ***@***.***>于2024年10月24日 周四17:49写道：
