### ISSUE TITLE
firefox下svg模式label文字偏移

### ISSUE THREAD

**Issue by awebird** [antvis/G6#642]
* **G6 Version**:2.2.6
* **Platform**:Firefox 65.0.2 - windows
* **Mini Showcase(like screenshots)**: 
![offset](https://user-images.githubusercontent.com/2157377/53945671-0e294500-40fd-11e9-8bb7-a7b7a35f382d.png)

* **CodePen Link**: https://codepen.io/awebird/pen/GeWjqv

firefox下svg模式label文字偏移, 如图所示

**Comment by PineappleBeer** [comment]
这个问题一上手就遇到了，试了各种方法，查遍了G文档都没用。

**Comment by awebird** [comment]
[@antv/g的issue，alignment-baseline在firefox不支持](https://github.com/antvis/g/issues/119)

**Comment by Yanyan-Wang** [comment]
目测新版本已经没有这个问题 https://codepen.io/Yanyan-Wang/pen/zYKEeZJ?editors=0010
