### ISSUE TITLE
[V5] Wrong custom arrow style

### ISSUE THREAD

**Issue by IceLeach** [antvis/G6#6425]
### Describe the bug / 问题描述

使用style.endArrowD自定义箭头，箭头显示位置不正确
![image](https://github.com/user-attachments/assets/8f4940d8-1b65-4dd9-8947-d8b6b30d7a6e)

### Reproduction link / 重现链接

https://stackblitz.com/edit/react-1xbp7e?file=index.js

### Steps to Reproduce the Bug or Issue / 重现步骤

拖动节点，如图所示

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by yvonneyx** [comment]
自定义箭头需要确保箭头形状对于 x 轴对称，可以调整为下述代码块：

```ts
{
    endArrowD: 'M-14,0 L-4,-4 L0,-14 L4,-4 L14,0 L4,4 L0,14 L-4,4 Z',
    endArrowOffset: 14,
}
```
