### ISSUE TITLE
optimize-viewport-transform is reported when using the fund-flow example on the official website, causing the canvas to fail to drag

### ISSUE THREAD

**Issue by mini2s** [antvis/G6#6429]
### Describe the bug / 问题描述

![image](https://github.com/user-attachments/assets/aa9f3f0c-3a73-4812-af72-8aad4f9c6e6d)
![image](https://github.com/user-attachments/assets/be907290-baf5-4d40-b24f-587d5031ee7e)

### Steps to Reproduce the Bug or Issue / 重现步骤

1. 打开官网 demo ：https://g6-next.antv.antgroup.com/zh/examples/scene-case/default/#fund-flow

2. 添加 optimize-viewport-transform 行为
<img width="311" alt="image" src="https://github.com/user-attachments/assets/1efd7862-2be6-4f0a-8172-3be48792300f">

3.尝试拖动画布

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome, Edge, Firefox

**Comment by yvonneyx** [comment]
好的，我们会尽快排查定位问题

**Comment by mini2s** [comment]
好的 谢谢，大概什么时候会修复，最近刚好在用😂

**Comment by yvonneyx** [comment]
已经修复并发版了，升级后可验证~

**Comment by yvonneyx** [comment]
由于此 issue 长时间没有回复，我们将其关闭。如果还有问题，请重新打开或者创建新的 issue ❤️
