### ISSUE TITLE
vue3.xxx G6 error is introduced

### ISSUE THREAD

**Issue by worldstop** [antvis/G6#6435]
### Describe the bug / 问题描述

		"vite": "^5.1.6",
		"vue": "^3.4.31",

SyntaxError: The requested module '/node_modules/.vite/deps/@antv_g6.js?v=27861aa6' does not provide an export named 'default' (at flowTrajectory.vue:52:1)

### G6 Version / G6 版本

4.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by yvonneyx** [comment]
哪个版本的 g6？

**Comment by worldstop** [comment]
> 哪个版本的 g6？
4.8.24
