### ISSUE TITLE
鼠标移出节点后触发node:mouseleave事件但是视图中鼠标状态却不刷新

### ISSUE THREAD

**Issue by aqiongbei** [antvis/g6#644]
* **G6 Version**: 3.0.0-beta.15
* **Platform**: Window10  chrome 72.0.3626.121（正式版本） （64 位）
* **Mini Showcase(like screenshots)**: 
![link](https://user-images.githubusercontent.com/20841215/54111457-d7b23980-441e-11e9-9757-02f1145554ca.gif)

* **CodePen Link**: https://codepen.io/aqiongbei/pen/drzdPG

使用自定义节点的时候，鼠标移出节点后触发node:mouseleave事件，在事件的处理方法中修改鼠标的状态和节点颜色，但是视图中节点颜色改变，鼠标状态却不改变。

注：codepen中引用的g6可能不能work。

**Comment by elaine1234** [comment]
在`3.0.0-rc.1`中修复

**Comment by SwordSealCity** [comment]
我想问下3.0.2版本怎么实现呢？
鼠标移入移出时改变指针状态。

**Comment by SwordSealCity** [comment]
找到了
defaultNode: {
              shape: 'circle', 
              size: 16,
              anchorPoints: [[0, 0.5], [1, 0.5]],
              style:{
                cursor: 'pointer'
              }
            },
