### ISSUE TITLE
When the edge type is quadratic and the edge width is set to be wider, the edge's arrow and point connections are unexpected

### ISSUE THREAD

**Issue by songxiaoyu321** [antvis/G6#6445]
### Describe the bug / 问题描述

![image](https://github.com/user-attachments/assets/b7540077-969c-43d5-8671-a1799e560236)
可以用官网例子修改
import { Graph, iconfont } from '@antv/g6';

const style = document.createElement('style');
style.innerHTML = `@import url('${iconfont.css}');`;
document.head.appendChild(style);

fetch('https://assets.antv.antgroup.com/g6/element-edges.json')
  .then((res) => res.json())
  .then((data) => {
    const graph = new Graph({
      container: 'container',
      data,
      edge: {
        type: 'quadratic',
        style: {
          lineWidth: 20,
          labelText: (d) => d.id,
          labelBackground: true,
          endArrow: true,
          badge: true,
          badgeText: '\ue603',
          badgeFontFamily: 'iconfont',
          badgeBackgroundWidth: 12,
          badgeBackgroundHeight: 12,
        },
      },
      layout: {
        type: 'radial',
        unitRadius: 220,
        linkDistance: 220,
      },
    });

    graph.render();
  });

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by yvonneyx** [comment]
https://github.com/antvis/G/issues/1809

**Comment by yvonneyx** [comment]
已修复，reinstall 一下~
