### ISSUE TITLE
Setting the combo size does not take effect

### ISSUE THREAD

**Issue by lvsheshamo** [antvis/G6#6446]
### Describe the bug / 问题描述

使用官网例子，设置combo size不生效

import { Graph } from '@antv/g6';

const data = {
  nodes: [
    { id: 'node1', combo: 'combo1', style: { x: 250, y: 150,size:100 } },
    { id: 'node2', combo: 'combo1', style: { x: 350, y: 150 } },
    { id: 'node3', combo: 'combo2', style: { x: 250, y: 300 } },
  ],
  edges: [],
  combos: [{ id: 'combo1', combo: 'combo2' }, { id: 'combo2',style:{size:[400,200]} }],
};

const graph = new Graph({
  container: 'container',
  data,
  node: {
    style: {
      labelText: (d) => d.id,
    },
  },
  combo: {
    type: 'rect',
     fixSize:[200,800],
    style: {
      padding: 20,
     
    },
  },
  behaviors: ['drag-element', 'collapse-expand'],
});

graph.render();

### G6 Version / G6 版本

🆕 5.0.26

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by yvonneyx** [comment]
Combo 有收起态和展开态两种状态。展开态的大小会根据子节点的大小和布局自动计算，而收起态的大小可以通过属性 `collapsedSize` 指定。

目前，内置功能不支持指定展开态的大小，但可以通过自定义 combo 并复写 `getExpandedKeySize` 方法来实现。
