### ISSUE TITLE
When the width and height are small, the G6 compact tree is very blurry

### ISSUE THREAD

**Issue by worldstop** [antvis/G6#6447]
### Describe the bug / 问题描述

宽高很小的时候G6紧凑树 显示的很模糊  
		"@antv/g6": "^4.8.24",
vue3
![1730167887816](https://github.com/user-attachments/assets/b83787b6-8b63-4ebf-b9de-7c3a9fe4f176)

![1730167887816](https://github.com/user-attachments/assets/0090eff1-2600-4e62-a8fe-9de6ef70f414)

### G6 Version / G6 版本

4.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by yvonneyx** [comment]
换个思路？调整容器大小而不是画布大小，然后进行自适应？
