### ISSUE TITLE
Error in Server Side Rendering. Need a valid ESM entry

### ISSUE THREAD

**Issue by kingyue737** [antvis/G6#6449]
### Describe the bug / 问题描述

According to README, G6 supported SSR. But this is **NOT** the case.

See #5205

### Reproduction link / 重现链接

ignore

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
We will publish the `@antv/g6-ssr` package today

**Comment by Aarebecca** [comment]
Here [@antv/g6-ssr](https://www.npmjs.com/package/@antv/g6-ssr) is available
