### ISSUE TITLE
3.0版本实现手动连线思路请教

### ISSUE THREAD

**Issue by aqiongbei** [antvis/g6#645]
* **G6 Version**: 3.0
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

要实现形如[antv/g6-editor](https://antv.alipay.com/zh-cn/g6/2.x/demo/editor/model-graph.html)的功能，看了antv/g6文档之后还是茫茫然，对于如何实现手动连线还是不知道所措。所以来请教。
要是实现的效果如下：
![link](https://user-images.githubusercontent.com/20841215/54113056-6eccc080-4422-11e9-92bb-b3912dc47c83.gif)

现在已有的思路是：
1. 鼠标移入节点的时候显示锚点
2. 从锚点开始拖拽连线，记录下鼠标开始时候的节点
3. 获取鼠标松开时候判断有没有触碰到某个节点，有节点的话就获取对用节点，构造一条边push进edge.
4. 更新视图

现在的问题卡在第一步。鼠标移入的时候不知道怎么显示锚点，也不知道这个锚点怎么构建才能实现类似效果。
希望有人可以帮忙，告诉我去看那一块的文档，或者代码，或者实现方式上有什么调整或者别的。

**Comment by elaine1234** [comment]
目前 G6 3.0 版本中的 anchorPoints 仅是作为计算连线交点时的约束条件，并没有真正绘制出来。建议通过 `registerNode` 自行绘制带锚点的节点: https://www.yuque.com/antv/g6/xp4nym。在绘制的时候隐藏节点`opacity: 0` 或 `shape.hide()`，在鼠标移入的时候显示出来。

**Comment by aqiongbei** [comment]
copy that

**Comment by hqzh** [comment]
> 目前 G6 3.0 版本中的 anchorPoints 仅是作为计算连线交点时的约束条件，并没有真正绘制出来。建议通过 `registerNode` 自行绘制带锚点的节点: [https://www.yuque.com/antv/g6/xp4nym。在绘制的时候隐藏节点`opacity](https://www.yuque.com/antv/g6/xp4nym%E3%80%82%E5%9C%A8%E7%BB%98%E5%88%B6%E7%9A%84%E6%97%B6%E5%80%99%E9%9A%90%E8%97%8F%E8%8A%82%E7%82%B9%60opacity): 0`或`shape.hide()`，在鼠标移入的时候显示出来。
页面404了

**Comment by xialvjun** [comment]
@aqiongbei But it's not open source. https://github.com/antvis/g6-editor/issues/126

**Comment by baizn** [comment]
参考这里 https://g6.antv.vision/zh/examples/interaction/setMode

**Comment by fengyulong113** [comment]
> https://g6.antv.vision/zh/examples/interaction/setMode

访问不了了
