### ISSUE TITLE
Fix element size error when the element invisible

### ISSUE THREAD

**Issue by hongwei0417** [antvis/G6#6450]
### Describe the bug / 问题描述

The issue come from #6416 
![image](https://github.com/user-attachments/assets/64bbe691-c86f-4a0d-a39a-cc97ed91d4a0)

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS, Windows, Others / 其他

### Browser / 浏览器

Chrome

**Comment by yvonneyx** [comment]
今天会发个版~

**Comment by yvonneyx** [comment]
https://github.com/antvis/G6/pull/6451 合并后可进行验证 ❤️

**Comment by hongwei0417** [comment]
Thanks. 😄
