### ISSUE TITLE
Can you enrich the documentation, the 5.0 documentation is rubbish, compared to the 4.0 API changes so much...

### ISSUE THREAD

**Issue by liuyonghu** [antvis/G6#6459]
### Describe the bug / 问题描述

能不能把文档丰富好，5.0 文档简直垃圾，相比4.0 api 改动有那么大... ,

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

### Additional context / 补充说明

能不能把文档丰富好，5.0 文档简直垃圾

**Comment by rmd1710714107** [comment]
can‘t agree more. Enrich the document,  plz

**Comment by yvonneyx** [comment]
如果对官网文档有意见，可以具体指出哪些部分需要优化，并指出其中的问题。我们会陆续进行更新和补充，而不是仅仅表达不满的情绪哦~

**Comment by Aarebecca** [comment]
> can‘t agree more. Enrich the document, plz

Regarding the documentation, you can inform us where there are doubts or where improvements are needed.

**Comment by liuyonghu** [comment]
> 如果对官网文档有意见，可以具体指出哪些部分需要优化以及问题。我们会陆续进行更新和补充，而不是仅仅表达不满的情绪哦~

那简直不要太多。比方说 nodeoptions 的 配置项 解释， 比方说里边的 type ，你看看官网写的都是啥 ？ string ？ 自己不看文档的吗？还要举例子 -。- 。

4.0 de  defautNode 配置 和 5.0 node 配置改动 ，很小吗？？不破坏？类似的很少吗？唉 ，非得一个个说说出来吗？

阿里是不是裁员太严重没空维护了呀,看看 echarts 的文档 ，真的目前没法比

**Comment by Aarebecca** [comment]
> > 如果对官网文档有意见，可以具体指出哪些部分需要优化以及问题。我们会陆续进行更新和补充，而不是仅仅表达不满的情绪哦~
> 
> 那简直不要太多。比方说 nodeoptions 的 配置项 解释， 比方说里边的 type ，你看看官网写的都是啥 ？ string ？ 自己不看文档的吗？还要举例子 -。- 。
> 
> 4.0 de defautNode 配置 和 5.0 node 配置改动 ，很小吗？？不破坏？类似的很少吗？唉 ，非得一个个说说出来吗？
> 
> 阿里是不是裁员太严重没空维护了呀,看看 echarts 的文档 ，真的目前没法比

G6 5.0 和 4.0 相比是一个全新的版本，不要以同样的思维去审视完全不同的事物。

**Comment by liuyonghu** [comment]
> > > 如果对官网文档有意见，可以具体指出哪些部分需要优化以及问题。我们会陆续进行更新和补充，而不是仅仅表达不满的情绪哦~
> > 
> > 
> > 那简直不要太多。比方说 nodeoptions 的 配置项 解释， 比方说里边的 type ，你看看官网写的都是啥 ？ string ？ 自己不看文档的吗？还要举例子 -。- 。
> > 4.0 de defautNode 配置 和 5.0 node 配置改动 ，很小吗？？不破坏？类似的很少吗？唉 ，非得一个个说说出来吗？
> > 阿里是不是裁员太严重没空维护了呀,看看 echarts 的文档 ，真的目前没法比
> 
> G6 5.0 和 4.0 相比是一个全新的版本，不要以同样的思维去审视完全不同的事物。

不要避重就轻，希望快点丰富文档吧
