### ISSUE TITLE
The ReactNode node cannot export the image when exporting

### ISSUE THREAD

**Issue by songxiaoyu321** [antvis/G6#6461]
### Describe the bug / 问题描述

导出时发现ReactNode节点导出图片时空白，其它点和边正常，请问如何解决

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
目前 ReactNode 暂不支持导入到图片中，如有相关需求，需使用原生节点开发

**Comment by kevinmatr** [comment]
> 目前 ReactNode 暂不支持导入到图片中，如有相关需求，需使用原生节点开发

后续有考虑支持吗？如果有的话大概什么时候会支持呢？
