### ISSUE TITLE
graph图形  node节点color属性不生效

### ISSUE THREAD

**Issue by wangxueliang** [antvis/g6#647]
版本：v2.2.6
环境：mac chorme 72.0.3626.119
https://antv.alipay.com/zh-cn/g6/2.x/demo/flow/work-flow.html
官方这个demo，当设置node的color属性，并没有生效，麻烦看一下，谢谢

**Comment by elaine1234** [comment]
在代码第 66 行指定了`fill: '#92949F'` ，节点上的样式优先级比较高

**Comment by wangxueliang** [comment]
我想设置字体颜色，不是背景色，麻烦再看下
