### ISSUE TITLE
[V5] Click to select (click-select) does not take effect in linux+chrome environment

### ISSUE THREAD

**Issue by Panpanpie** [antvis/G6#6471]
### Describe the bug / 问题描述

使用linux+chrome120，打开v5文档示例中"交互-选中"示例，点击节点无法实现选中。
如下自定义点击事件，也无法生效打印。
`graph.on('click', (event) => {
    console.log('event click=====>', event)
  });`
linux+FireFox，windows均可正常响应。

### Reproduction link / 重现链接

https://g6.antv.antgroup.com/examples/behavior/select/#click

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Linux

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
由于我们没有相关操作系统的设备，因此可能无法复现你提到的问题。
你可以尝试下[实例](https://g.antv.antgroup.com/zh/examples/event/picking/#circle)看下交互是否正常？
以及 `DragElement` `DragCanvas` 在你的设备上是否正常。

**Comment by Panpanpie** [comment]
DragElement DragCanvas 这这些drag事件都正常，只有click相关事件无法响应

**Comment by Aarebecca** [comment]
> DragElement DragCanvas 这这些drag事件都正常，只有click相关事件无法响应

理论上这几个事件都是基于 `pointerdown` `pointermove` `pointerup` 事件实现的，不应该 drag 事件正常而 click事件不正常
