### ISSUE TITLE
graph.updateNodeData

### ISSUE THREAD

**Issue by HHH-bot-code** [antvis/G6#6474]
### Describe the bug / 问题描述

The updateNodeData in the website example does not take effect without using updateNodeData in local vue projects

### Reproduction link / 重现链接

https://g6.antv.antgroup.com/examples/behavior/inner-event/#basic

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by HHH-bot-code** [comment]
The updateNodeData in the website example does not effect local vue project have effect

**Comment by Aarebecca** [comment]
Could you please provide more details about your problem

**Comment by HHH-bot-code** [comment]
Click no effect
![image](https://github.com/user-attachments/assets/69ed8d86-046e-4e3d-8f1f-036078457282)

**Comment by HHH-bot-code** [comment]
Click no effect
![image](https://github.com/user-attachments/assets/4a2e9a56-9c8f-493c-bc91-2f223ca3b351)

**Comment by HHH-bot-code** [comment]
> Could you please provide more details about your problem
Click no effect
![image](https://github.com/user-attachments/assets/0e38a4c2-45dc-4fbe-8e93-6c1bc66c722a)

**Comment by Aarebecca** [comment]
There is a bug in the example, you can refer to the following code modification, we will fix it as soon as possible:

```
graph.on(NodeEvent.CLICK, (event) => {
  const { target, originalTarget } = event;
  console.log('click', originalTarget);
  if (originalTarget.className === 'light') { // use className
    graph.updateNodeData([{ id: target.id, states: ['selected'], style: { labelText: 'Clicked!' } }]);
    graph.draw();
  }
});
```
