### ISSUE TITLE
G6 can't draw images on Android in Uniapp.

### ISSUE THREAD

**Issue by he-jiahao** [antvis/G6#6476]
### Describe the bug / 问题描述

我使用uniapp开发一个安卓端的app，在这只中使用G6来绘制一个方便缩放的点线图。但是完成基本例子的引入之后，发现在浏览器端运行能绘制图像，但是运行到app端，图像没有显示，也没有报错。这是否有一些不兼容的部分。

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows, Others / 其他

### Browser / 浏览器

Others / 其他

**Comment by Aarebecca** [comment]
目前尚未对 uniapp 进行适配，可能是设备存在部分 API 尚未完全实现。
建议尝试切换到 SVG 渲染器看下能否正常显示。

**Comment by he-jiahao** [comment]
好的 感谢
