### ISSUE TITLE
SyntaxError: The requested module '/node_modules/.vite/deps/@antv_g6.js?v=75648447' does not provide an export named 'default'

### ISSUE THREAD

**Issue by Sloth9527** [antvis/G6#6485]
### Describe the bug / 问题描述

![image](https://github.com/user-attachments/assets/8a42edec-7cbe-4fce-a5ac-d3276f031807)

vue3 按照文档引入后 报错

![image](https://github.com/user-attachments/assets/e8c2d7e2-28aa-4028-af65-a9fea92fabd8)

![image](https://github.com/user-attachments/assets/56b4135c-e9e4-4f35-849a-565ff761de0a)

![image](https://github.com/user-attachments/assets/2c3f6e17-0aa9-4ced-9fc2-a26d6ce1596b)

### Reproduction link / 重现链接

https://codesandbox.io/p/live/c35cbe0d-2f51-413a-bac4-e27679b440da

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
没有发现你所描述的问题，Vue 使用 G6 可以参考：https://codesandbox.io/p/sandbox/g6-vue-xzf7pg?file=%2Fsrc%2FApp.vue%3A9%2C1

**Comment by Sloth9527** [comment]
> 没有发现你所描述的问题，Vue 使用 G6 可以参考：https://codesandbox.io/p/sandbox/g6-vue-xzf7pg?file=%2Fsrc%2FApp.vue%3A9%2C1

用vue3却不用vite是真没想到，那就是vite需要怎么配置能支持g6
https://codesandbox.io/p/devbox/goofy-elion-29lqrv

**Comment by Aarebecca** [comment]
@Sloth9527 我们的开发环境也是有用到 vite 的，且也存在其他的 vue 用户，并没有反应你提到的问题。建议检查自身开发环境。

**Comment by jannicaTan** [comment]
> > 没有发现你所描述的问题，Vue 使用 G6 可以参考：https://codesandbox.io/p/sandbox/g6-vue-xzf7pg?file=%2Fsrc%2FApp.vue%3A9%2C1
> 
> 用vue3却不用vite是真没想到，那就是vite需要怎么配置能支持g6 https://codesandbox.io/p/devbox/goofy-elion-29lqrv

请问解决了吗？我也是同样的问题 同样的引入方式💦

**Comment by JiaQi-0827** [comment]
@jannicaTan https://github.com/vitejs/vite/issues/17727

**Comment by gigizhaoo** [comment]
试试自己安装 dagre,

vite.config.js
```js
  resolve: {
      alias: {
        dagre: 'dagre/dist/dagre.min.js',
      },
    },
```
