### ISSUE TITLE
Graph.updateNodeData modifying fill is invalid

### ISSUE THREAD

**Issue by ping40** [antvis/G6#6496]
### Describe the bug / 问题描述

构建图的时候，如果指定了fill的值，则导致 updateNodeData fill的时候无效。

`Graph({
      container: 'container',
      autoFit: 'view',
      data: treeToGraphData(data),
      behaviors: ['drag-canvas', 'zoom-canvas', 'drag-element'],
      node: {
        style: {
          labelText: (d) => d.id,
          //fill: '#909399',   --》 这一行
          labelBackground: true,
        },
        animation: {
          enter: false,
        },
      },`

### Reproduction link / 重现链接

https://stackblitz.com/edit/p5kmma?file=index.js

### Steps to Reproduce the Bug or Issue / 重现步骤

打开或者 屏蔽 第16行，然后鼠标移动到节点上看fill的变化。

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

Windows, Others / 其他

### Browser / 浏览器

Chrome, Firefox

**Comment by Aarebecca** [comment]
可以参考这里：https://g6.antv.antgroup.com/manual/faq#%E6%95%B0%E6%8D%AE%E4%B8%AD%E7%9A%84%E6%A0%B7%E5%BC%8F%E4%B8%8D%E7%94%9F%E6%95%88

**Comment by ping40** [comment]
谢谢，这种概念方法可行。

但是跟常识有点不匹配。
