### ISSUE TITLE
In V5, how do I set the coordinates of a node by obtaining the bounding box of the node when drawing a node?

### ISSUE THREAD

**Issue by lhz7695001** [antvis/G6#6498]
### Describe the bug / 问题描述

![image](https://github.com/user-attachments/assets/4eed7c48-092e-4919-936a-fbe4c8ef70ab)
这个是我写的，但是会调用两次upsert方法，有更好的方法吗

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
这么写是可以的， upsert 会检查该图形是否存在，不存在则创建，存在则刷新。因此这里调用两次不会导致重新创建元素

**Comment by lhz7695001** [comment]
> 这么写是可以的， upsert 会检查该图形是否存在，不存在则创建，存在则更新。因此这里调用两次不会导致重新创建元素

好的，感谢~~
