### ISSUE TITLE
如何定位某节点

### ISSUE THREAD

**Issue by zhuzhuxiapeiqi** [antvis/g6#65]
想要将某节点定位在可视区域的中心，用focusPoint方法还是不能准确定到屏幕中心，而且focusPoint（）之后，画布不能再拖动了，请问有什么解决方案吗？

**Comment by TomHuangCN** [comment]
按理不会，无法定位问题，写个 codepen？ https://codepen.io/

**Comment by zhuzhuxiapeiqi** [comment]
3qu～问题已经解决了，原来我是直接graph.focusPoint([chooseNode.x, chooseNode.y]); 改成graph.focusPoint(node)就行了
