### ISSUE TITLE
G6 version: V5 How to set stroke for rect, which edge to assign to the stroke?

### ISSUE THREAD

**Issue by lhz7695001** [antvis/G6#6502]
### Describe the bug / 问题描述

![image](https://github.com/user-attachments/assets/40bb50a1-5ab8-4367-800a-0a71d63a1770)

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
目前不支持这个能力，如果你要实现类似效果，需要通过自行在两端手动添加直线来模拟描边

**Comment by lhz7695001** [comment]
感谢

**Comment by lhz7695001** [comment]
close
