### ISSUE TITLE
G6 V5: How do I set the location of a custom node in a custom combo?

### ISSUE THREAD

**Issue by lhz7695001** [antvis/G6#6507]
### Describe the bug / 问题描述

![image](https://github.com/user-attachments/assets/244931d5-491f-4ab8-a2fd-f459007b113c)
![image](https://github.com/user-attachments/assets/72864245-a0c0-4bb6-8c02-7a99501ccec3)
![image](https://github.com/user-attachments/assets/16fa632a-cbcb-440e-8704-d4126e0748e4)

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by yvonneyx** [comment]
设置节点坐标遵循此格式 `{ id: 'node-1', style: { x: 42, y: 42 }}`  另外 combo 位置由内部元素决定

**Comment by lhz7695001** [comment]
> style: { x: 42, y: 42 }

![image](https://github.com/user-attachments/assets/16fc76de-1fc2-4161-a7c6-37b13303acc0)
我就是这样设置的，改变node的x,y坐标，和所在combo的相对位置不发生变化，变化的知识combo的位置，很奇怪

**Comment by Aarebecca** [comment]
combo与其内部的节点相对位置无法精确调整，只能通过设置padding
