### ISSUE TITLE
Production Environment Error: Cannot read properties of undefined (reading 'Graph')

### ISSUE THREAD

**Issue by hls-1992** [antvis/G6#6512]
### Describe the bug / 问题描述

In DEV environment, everything is ok.
In PROD environmnet, Cannot read properties of undefined (reading 'Graph')

### Steps to Reproduce the Bug or Issue / 重现步骤

Just vue3 + vite
import { Graph } from '@antv/g6'

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by hls-1992** [comment]
vite 2.x version

**Comment by Aarebecca** [comment]
I created a vue app and used G6, and the built product worked without the problem you described. You can provide more information.

**Comment by hls-1992** [comment]
> I created a vue app and used G6, and the built product worked without the problem you described. You can provide more information.

I think it is caused by the lower version vite(2.6)

**Comment by hls-1992** [comment]
> I created a vue app and used G6, and the built product worked without the problem you described. You can provide more information.

In vite 4.x version, everything is ok

**Comment by penouc** [comment]
Hello! May I ask what caused this?

**Comment by zS1m** [comment]
Same problem here

**Comment by zxymgl** [comment]
How can this problem be solved ？
