### ISSUE TITLE
How can I set the label of an edge to cover the edge? , no instructions were found in the documentation

### ISSUE THREAD

**Issue by lhz7695001** [antvis/G6#6518]
### Describe the bug / 问题描述

例如实现这样的效果
![image](https://github.com/user-attachments/assets/41633b0f-7db0-42b4-b81b-fbe9b8a5a4f7)

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
设置 labelBackground: true 启用背景， labelBackgroundFill 设置背景色

**Comment by lhz7695001** [comment]
可以变相实现
