### ISSUE TITLE
链接无效，直接跳回主页了

### ISSUE THREAD

**Issue by j717273419** [antvis/g6#653]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

https://antv.alipay.com/zh-cn/g6/1.x/index.html

链接无效，直接跳回主页了

**Comment by elaine1234** [comment]
- 1.x 文档: https://antvis.github.io/g6/doc/index.html
- 2.x 文档: https://www.yuque.com/antv/g6/introduce
- 3.x 文档: https://www.yuque.com/antv/g6/intro
