### ISSUE TITLE
How to customize the location of the label

### ISSUE THREAD

**Issue by werbug** [antvis/G6#6536]
### Describe the bug / 问题描述

labelCfg中，position加offset只能单一改变x或者y方向的位置，如何能够同时更改label的x,y

### G6 Version / G6 版本

4.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by yvonneyx** [comment]
4.0 内置 label 不支持同时更改 xy 需要自定义

**Comment by werbug** [comment]
ok
