### ISSUE TITLE
关于结点复加自定义属性问题--描点连线后，复加属性被清空的问题

### ISSUE THREAD

**Issue by winken168** [antvis/g6#654]
* **G6 Version**: g6": "^2.2.6"  g6-editor": "^1.2.0"
* **Platform**: osx
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

 我想给结点model添加个“activetype”的属性，但在结点描点连线时，定义的“activetype”的属性会被清空， 复加属性定义（ data-activetype="start"）如下：  
 < i m g
            draggable="false"
            src="。。。"
            data-type="node"
            data-shape="flow-circle"
            data-size="72*72"
            data-color="#FA8C16"
            data-label="开始结点"
            data-activetype="start"
            class="getItem"
          />
描点连线操作过程结点属性值变化如下：
hoveranchor:beforeaddedge activetype---> start
2editor.vue?7b20:255 hoveranchor:beforeaddedge activetype---> start
4editor.vue?7b20:245 hoveranchor:beforeaddedge activetype---> start
editor.vue?7b20:255 hoveranchor:beforeaddedge activetype---> start
editor.vue?7b20:277 dragedge:beforeshowanchor-activetype-> start
editor.vue?7b20:278 dragedge:beforeshowanchor-activetype-> start
editor.vue?7b20:277 dragedge:beforeshowanchor-activetype-> 
editor.vue?7b20:278 dragedge:beforeshowanchor-activetype-> 
editor.vue?7b20:277 dragedge:beforeshowanchor-activetype-> 
editor.vue?7b20:278 dragedge:beforeshowanchor-activetype-> 
editor.vue?7b20:277 dragedge:beforeshowanchor-activetype-> 
editor.vue?7b20:278 dragedge:beforeshowanchor-activetype-> 
editor.vue?7b20:277 dragedge:beforeshowanchor-activetype-> 
editor.vue?7b20:278 dragedge:beforeshowanchor-activetype-> start
editor.vue?7b20:277 dragedge:beforeshowanchor-activetype-> 
editor.vue?7b20:278 dragedge:beforeshowanchor-activetype-> 
editor.vue?7b20:277 dragedge:beforeshowanchor-activetype-> 
editor.vue?7b20:278 dragedge:beforeshowanchor-activetype-> 
editor.vue?7b20:277 dragedge:beforeshowanchor-activetype-> 
editor.vue?7b20:278 dragedge:beforeshowanchor-activetype-> 

请问如何避免复加属于的值在描点连线时被清空，谢谢！

**Comment by baizn** [comment]
把自定义属性添加到时数据中应该就没问题，另外2.x没在维护了，建议升级到3.x。
