### ISSUE TITLE
Tree map? Configure collapsed: false in the parent node data that needs to be shrunk by default

### ISSUE THREAD

**Issue by WANGXIAOYU1995** [antvis/G6#6542]
树图吗？在需要默认收缩的父节点数据中配置 collapsed: false 即可

_Originally posted by @Yanyan-Wang in https://github.com/antvis/G6/issues/1325#issuecomment-601031557_
            此方法没生效

**Comment by yvonneyx** [comment]
使用的是哪个版本的 g6？

**Comment by WANGXIAOYU1995** [comment]
5.0.30
________________________________
发件人: Yuxin ***@***.***>
发送时间: 2024年11月25日 11:37
收件人: antvis/G6 ***@***.***>
抄送: WANGXIAOYU1995 ***@***.***>; Author ***@***.***>
主题: Re: [antvis/G6] Tree map? Configure collapsed: false in the parent node data that needs to be shrunk by default (Issue #6542)


使用的是哪个版本的 g6？

―

**Comment by WANGXIAOYU1995** [comment]
大哥 我的G6是新版本 5.0.30，默认收缩不生效后我尝试了遍历取id 手动调 graph.collapseElement方法。收缩是生效了 但是带来的弊端自定义节点的展开收缩不生效，有很多bug，点击没反应，控制台也报错 
![image](https://github.com/user-attachments/assets/6dd989ea-ac9d-4647-b1c8-c276e40075d2)
还是先看看官方有没有类似的collapsed: true 类似的配置

**Comment by yvonneyx** [comment]
设置 node.style.collapsed 即可

WANGXIAOYU1995 ***@***.***>于2024年11月25日 周一11:50写道：

**Comment by WANGXIAOYU1995** [comment]
![image](https://github.com/user-attachments/assets/07ef96c9-f825-44ec-9387-490fa53bb1f5)
您好  是这里的node style吗 我改了没生效呢

**Comment by yvonneyx** [comment]
哦哦 我是指 数据中修改 nodeDatum.style.collapsed

**Comment by WANGXIAOYU1995** [comment]
是我愚钝了。。这样写是生效的  感谢大佬 大佬一生平安~~
