### ISSUE TITLE
V5 version: Use the tooltip plug-in, move the mouse into the floating window, the floating window will disappear, how to set the mouse to move to the floating window, the floating window will not disappear?

### ISSUE THREAD

**Issue by lhz7695001** [antvis/G6#6543]
### Describe the bug / 问题描述

![image](https://github.com/user-attachments/assets/3fc05141-3dd4-4eb5-bec5-a9cd71da73fe)
如何设置鼠标移动到浮窗里面，浮窗不会消失呢？

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
配置 `enterable: true` 即可，后续会完善相关文档

**Comment by lhz7695001** [comment]
感谢~

**Comment by lhz7695001** [comment]
已解决
