### ISSUE TITLE
The context cannot be obtained after the toDataURL is called

### ISSUE THREAD

**Issue by xiaoxiaofu1** [antvis/G6#6545]
### Describe the bug / 问题描述

export class LinearEdge extends Quadratic {
  render(attributes, container) {
    console.log(this.context)
    super.render(attributes);
  }
}
调用.toDataURL()后报错，获取不到context了，点之前都正常
![image](https://github.com/user-attachments/assets/a50a1489-312b-4128-afa0-aa779405844f)
![image](https://github.com/user-attachments/assets/bb51e5c2-ebac-4794-a19b-bc45332f3f18)

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
删除 node_modules 重新安装尝试下

**Comment by xiaoxiaofu1** [comment]
> 删除 node_modules 重新安装尝试下

可以了 十分感谢
