### ISSUE TITLE
Is the insert type abnormal?

### ISSUE THREAD

**Issue by zzjjbbaa** [antvis/G6#6546]
### Describe the bug / 问题描述

![image](https://github.com/user-attachments/assets/b930e03a-9324-428f-8cd6-27d5a88a0ffa)
怎么解决ts的类型报错（`Rect`是从`antv/g`中导出的**shape**）

### Reproduction link / 重现链接

无

### Steps to Reproduce the Bug or Issue / 重现步骤

无

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS, Windows, Linux, Others / 其他

### Browser / 浏览器

Chrome, Edge

**Comment by Aarebecca** [comment]
你可以先使用 `this.upsert(shapeId, 'rect', attributes, container)` 来避免类型检查。
其中 Rect 已经注册到内部，可以使用 'rect' 别名

**Comment by Aarebecca** [comment]
不过目前并没有发现类型异常，可以检查下依赖项版本

**Comment by zzjjbbaa** [comment]
> 你可以先使用 `this.upsert(shapeId, 'rect', attributes, container)` 来避免类型检查。 其中 Rect 已经注册到内部，可以使用 'rect' 别名

有shape清单嘛，`group`有嘛？

**Comment by zzjjbbaa** [comment]
> 不过目前并没有发现类型异常，可以检查下依赖项版本

antv/g的版本？

**Comment by Aarebecca** [comment]
> > 你可以先使用 `this.upsert(shapeId, 'rect', attributes, container)` 来避免类型检查。 其中 Rect 已经注册到内部，可以使用 'rect' 别名
> 
> 有shape清单嘛，`group`有嘛？

常见的都有，详见：

https://github.com/antvis/G6/blob/6d01a5583135041cef73835ce046c33a88969396/packages/g6/src/registry/build-in.ts#L223-L237
