### ISSUE TITLE
On Mac, Safari 16+ ~ 18+'s drag-canvas drag distance is very short, much shorter than that of Chrome for Mac, which makes it feel difficult to drag

### ISSUE THREAD

**Issue by mini2s** [antvis/G6#6548]
### Describe the bug / 问题描述

在 mac 上 safari 16+ ~ 18+ 的 drag-canvas 拖动距离很短，比 mac 版 chrome 拖起来短太多，让人感觉很难拖动

### Steps to Reproduce the Bug or Issue / 重现步骤

1.在 macos 上打开 chrome 和 safari 
2.两个浏览器同时打开  https://g6.antv.antgroup.com/examples/performance/massive-data/#5000
3.拖住画布鼠标不要松开，然后左右甩动鼠标

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Safari (Limited support / 有限支持)

**Comment by Aarebecca** [comment]
目前我们适配的浏览器主要为使用 chromium 内核的浏览器(如 Chrome、Microsoft Edge等)，Safari 浏览器存在某些非标准实现，可能会导致交互异常。

**Comment by mini2s** [comment]
> 目前我们适配的浏览器主要为使用 chromium 内核的浏览器(如 Chrome、Microsoft Edge等)，Safari 浏览器存在某些非标准实现，可能会导致交互异常。

😁 好的那我就只能提示用户一下推荐使用 Chrome、Microsoft Edge、firefox 获得更好体验了，

Safari 真是 现代版的IE
