### ISSUE TITLE
antv g6 v5 Graph.updateNodeData(data) and then need to Graph.draw again, can't you update it directly?

### ISSUE THREAD

**Issue by lhz7695001** [antvis/G6#6552]
### Describe the bug / 问题描述

![image](https://github.com/user-attachments/assets/526874a6-5b30-411a-87f4-8b02c861f5f6)
![image](https://github.com/user-attachments/assets/5583cb27-ff55-44cb-840e-dd791afeed20)

### G6 Version / G6 版本

🆕 5.x

### Operating System / 操作系统

macOS

### Browser / 浏览器

Chrome

**Comment by Aarebecca** [comment]
这样的设计是为了避免多次更新数据时重复渲染，提高绘制效率。
