### ISSUE TITLE
能否将编辑器设置成只读（禁止编辑）？

### ISSUE THREAD

**Issue by lingjieee** [antvis/g6#656]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by CathyLX** [comment]
我也是半天没找到怎么设置只读，现在的处理方式是重新注册命令。比如：
Command.registerCommand('delete', {
  enable() {
    return fasle;
  }
})
那就不能删除了。

**Comment by TsangTszKin** [comment]
可以把canvas转为base64图片显示，这样就禁止编辑了

**Comment by guozhaolong** [comment]
通过setMode设置编辑或浏览状态应该是最优雅的
