### ISSUE TITLE
Data changes view updates

### ISSUE THREAD

**Issue by Yi-Wo-Zuo** [antvis/G6#6561]
我有个自定义html类型的节点，默认只展示一条数据，里面有个一下拉按钮，点击这个按钮展示所有数据。我给这个按钮添加一个click事件，这个事件功能就是找的对应数据吧一个变量isExpand是否展开的变量改成true，然后期望图表可以刷新。
![1732615122151](https://github.com/user-attachments/assets/a600dc3c-f23d-45fb-91e8-d588f0f470a6)

**Comment by yvonneyx** [comment]
数据变更可以调用 graph.draw() 来重绘元素

**Comment by yvonneyx** [comment]
由于此 issue 长时间没有回复，我们将其关闭。如果还有问题，请重新打开或者创建新的 issue ❤️
