### ISSUE TITLE
[Bug]: The fillOpacity of the custom node is invalid

### ISSUE THREAD

**Issue by xieyangxing** [antvis/G6#6582]
### Describe the bug / 问题描述

![79E3F8E0-0411-4548-8145-A159E601B278](https://github.com/user-attachments/assets/a414009f-6ce1-4c26-99d7-b33cc67e2091)

### G6 Version / G6 版本

Please select / 请选择

### OS / 操作系统

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] Others / 其他

### Browser / 浏览器

- [X] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Safari (Limited support / 有限支持)
- [ ] IE (Nonsupport / 不支持)
- [ ] Others / 其他

**Comment by yvonneyx** [comment]
jsx 直接修改样式即可

**Comment by xieyangxing** [comment]
@yvonneyx  其实不单单这个属性不生效，追踪原因会发现自定义元素的很多属性都不生效。在往上会导致方法都也生效，比如自定义元素的setElementState。

**Comment by hustcc** [comment]
使用自定义的节点的时候，配置的 style 会透传给节点，但是自定义的节点不一定会消费，比如 fillOpacity 属性是给 canvas 中节点使用的。

**Comment by yvonneyx** [comment]
> @yvonneyx 其实不单单这个属性不生效，追踪原因会发现自定义元素的很多属性都不生效。在往上会导致方法都也不生效，比如自定义元素的setElementState。,getEdgeData（获取边信息）都不生效

嗯嗯，html 节点目前只支持 dx, dy, innerHTML, pointerEvents, cursor 属性，其他样式属性不生效。比如说想修改填充色透明度，可以直接修改 innerHTML 的 div 元素样式，对应的应该是background 字段用rgba赋值。

另外状态也是基于数据驱动，可以从 innerHTML 回调的参数中获取到实时的状态标识，自定义对应的样式配置

<img width="1430" alt="image" src="https://github.com/user-attachments/assets/eb2c136c-94db-482f-be78-28d597444ba5">

**Comment by xieyangxing** [comment]
@yvonneyx 感谢您耐心细致的回答
