### ISSUE TITLE
[Bug]: How to set the rendering visual level of Combo and child nodes in G6 use

### ISSUE THREAD

**Issue by lhz7695001** [antvis/G6#6586]
### Describe the bug / 问题描述

![image](https://github.com/user-attachments/assets/3d899bfb-7922-4550-b4f0-c7117e006c7e)

### G6 Version / G6 版本

🆕 5.x

### OS / 操作系统

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] Others / 其他

### Browser / 浏览器

- [X] Chrome
- [ ] Edge
- [ ] Firefox
- [X] Safari (Limited support / 有限支持)
- [ ] IE (Nonsupport / 不支持)
- [ ] Others / 其他

**Comment by yvonneyx** [comment]
动态调整元素层级 api
