### ISSUE TITLE
[Bug]: getZoom is undefined

### ISSUE THREAD

**Issue by rmd1710714107** [antvis/G6#6589]
### Describe the bug / 问题描述

初始化图实例后立即调用`getZoom`函数报错：
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getZoom')`

### Steps to Reproduce the Bug or Issue / 重现步骤

```
let graph = new Graph({       
     ...
});
console.log(graph.getZoom());
```

### G6 Version / G6 版本

🆕 5.x

### OS / 操作系统

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] Others / 其他

### Browser / 浏览器

- [X] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Safari (Limited support / 有限支持)
- [ ] IE (Nonsupport / 不支持)
- [ ] Others / 其他

**Comment by yvonneyx** [comment]
`render` 为异步操作，先 await 再调用 `getZoom()`
