### ISSUE TITLE
版本：3.0.0  1：node节点click事件失效；2：节点设置state，拖拽之后，状态消失

### ISSUE THREAD

**Issue by ChenGuanYin** [antvis/g6#659]
* **G6 Version**:  3.0.0
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:  https://codepen.io/ChenGuanYin/pen/PLLGJd

1：节点设置状态；
2：拖拽该节点；
3：节点的状态消失；

**Comment by elaine1234** [comment]
1: node 节点 click 事件失效。
这个 codePen 中的事件没有失效，是否有步骤可以复现？
![image](https://user-images.githubusercontent.com/8325822/54917970-fe509400-4f37-11e9-887d-ee55bef9aa95.png)

2. 节点设置 state， 拖拽之后，状态消失。
已定位到问题，将在下版本修复，感谢反馈。

**Comment by ChenGuanYin** [comment]
抱歉，节点失效这个应该是缓存的问题。

**Comment by lirumeng** [comment]
为什么我点击仍然是无效的？

**Comment by ChenGuanYin** [comment]
如果说强刷还不可以的话，建议换一个浏览器试一下
