### ISSUE TITLE
[Bug]: The edge edge is animated with the flow direction, but the custom node can't rotate with the edge?

### ISSUE THREAD

**Issue by lhz7695001** [antvis/G6#6590]
### Describe the bug / 问题描述

需求：V5版本实现连接两个节点的边动画效果，水滴流向效果如示例。最好是实现效果支持带弧度曲线。

问题：目前通过动画结合添加自定义节点实现，但是自定义marker无法随边旋转，期望能随边旋转。

期望：
希望专家能指导下如何达到我的预期，最好是能够支持在曲线edge情况下，也能有流向效果，先谢过

### Steps to Reproduce the Bug or Issue / 重现步骤

![image](https://github.com/user-attachments/assets/a3e756d3-9bbb-4d4c-85f9-0582a57abe4a)
这是我目前的代码
![image](https://github.com/user-attachments/assets/4b9ba9a6-0d8f-4700-8c10-508c86b96d2d)
![image](https://github.com/user-attachments/assets/811760bd-1fbe-4abb-a079-7fab50346b2a)

### G6 Version / G6 版本

Please select / 请选择

### OS / 操作系统

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] Others / 其他

### Browser / 浏览器

- [ ] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Safari (Limited support / 有限支持)
- [ ] IE (Nonsupport / 不支持)
- [ ] Others / 其他

**Comment by Aarebecca** [comment]
讨论请到 Discussion

**Comment by lhz7695001** [comment]
1
