### ISSUE TITLE
At present, it is achieved by adding custom nodes in combination with animation, but the custom marker cannot be rotated with the edge, and it is expected to rotate with the edge.

### ISSUE THREAD

**Issue by lhz7695001** [antvis/G6#6595]
### Describe the bug / 问题描述

这个我写的演变动画，但是无法实现随边旋转 

https://github.com/user-attachments/assets/6647c6bf-9f53-4b22-9eb3-4c5dcd504d68

### Steps to Reproduce the Bug or Issue / 重现步骤

这个我写的演变动画，但是无法实现随边旋转

![image](https://github.com/user-attachments/assets/6659d1b3-9dd3-4f44-958f-e72998784769)
![image](https://github.com/user-attachments/assets/33aeaea2-0486-4586-b5bc-b0fd7ec75956)

### G6 Version / G6 版本

🆕 5.x

### OS / 操作系统

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] Others / 其他

### Browser / 浏览器

- [X] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Safari (Limited support / 有限支持)
- [ ] IE (Nonsupport / 不支持)
- [ ] Others / 其他

**Comment by Aarebecca** [comment]
标题麻烦按照规范

**Comment by lhz7695001** [comment]
@

**Comment by lhz7695001** [comment]
1
