### ISSUE TITLE
[Feat]: How to implement the overflow prompt of the combo label text? (combo's label text is displayed beyond the width...) ）

### ISSUE THREAD

**Issue by Cherry860** [antvis/G6#6611]
### Describe the feature / 功能描述

If the combo text is too long, an ellipsis (ellipsis) is displayed when it exceeds a certain width.
1、使用label配置未生效。Currently, the labelCfgStyle configuration fails.
style: {
fill: '# 666',
width: 100,
overflow: 'hidden',
textOverflow: 'ellipsis'
}
2、Labels are customized based on rect. The label cannot be rewritten during document display.
基于rect类型自定义combos, 无法覆盖原有label, 
官网原文：_**在 drawShape 方法中不需要为 label 增加图形，父类方法将会自动增加默认的 label，可以通过配置的方式指定 label 的位置和样式；**_

### Are you willing to contribute? / 是否愿意参与贡献？

Please select / 请选择

**Comment by Cherry860** [comment]
Can combo labels of the Rect type be rewritten?

**Comment by yvonneyx** [comment]
4.0? 4.0 无法通过配置处理超长文本，可参考：https://g6-v4.antv.vision/zh/examples/item/label/#labelLen

**Comment by yvonneyx** [comment]
5.0 中现已支持 https://g6.antv.antgroup.com/examples/element/label/#ellipsis，推荐升级~
