### ISSUE TITLE
[Bug]: 'Orthogonal Line with Control Point' on the official website

### ISSUE THREAD

**Issue by donhonli** [antvis/G6#6621]
### Describe the bug / 问题描述

见附件

### Reproduction link / 复现链接

https://g6.antv.antgroup.com/zh/examples/element/edge/#polyline-orth-with-cps

### Steps to Reproduce the Bug or Issue / 重现步骤

拖拽‘控制点’，  线不会动

### G6 Version / G6 版本

🆕 5.x

### OS / 操作系统

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] Others / 其他

### Browser / 浏览器

- [X] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Safari (Limited support / 有限支持)
- [ ] IE (Nonsupport / 不支持)
- [ ] Others / 其他

**Comment by yvonneyx** [comment]
这里的控制点仅作为示意点，并未与折线的控制点双向绑定，因此拖动控制点不会影响折线的绘制
