### ISSUE TITLE
[Bug]: The endpoint setting sourcePort and targetPort lines are occluded

### ISSUE THREAD

**Issue by vxow** [antvis/G6#6629]
### Describe the bug / 问题描述

设置线的端点，线会被节点遮挡
type: 'polyline'
router设置'orth'、'shortest-path'都会出现遮挡

### Reproduction link / 复现链接

https://codesandbox.io/p/sandbox/y4s8t7

### G6 Version / G6 版本

🆕 5.x

### OS / 操作系统

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] Others / 其他

### Browser / 浏览器

- [X] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Safari (Limited support / 有限支持)
- [ ] IE (Nonsupport / 不支持)
- [ ] Others / 其他

**Comment by vxow** [comment]
@yvonneyx 有什么好办法解决这种遮挡问题么

**Comment by yvonneyx** [comment]
这是由于 dagre 布局会同时返回节点位置和控制点结果，折线的正交路由会将控制点计算在内。你可以手动将控制点清空，以便路由算法重新计算拐点。

```ts]
 edge: {
    type: "polyline",
    style: {
      router: {
        type: "orth",
      },
      controlPoints: [],
    },
  },
```

**Comment by vxow** [comment]
@yvonneyx 试过这个办法，效果是改善了一些，但是还是会出现遮挡，有什么自定义的方法能够弥补么。

<img width="669" alt="image" src="https://github.com/user-attachments/assets/76918507-ba66-4fe5-be85-14088a0ea9f8" />

**Comment by yvonneyx** [comment]
可以选择自定义边来实现：https://g6.antv.antgroup.com/manual/custom-extension/element#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%BE%B9
