### ISSUE TITLE
minimap加载图形无关的字体库导致性能问题

### ISSUE THREAD

**Issue by phantomlution** [antvis/G6#663]
* **G6 Version**:
2.1.5
* **Platform**:
Mac Chrome
* **Mini Showcase(like screenshots)**:
![WechatIMG241](https://user-images.githubusercontent.com/29418758/55132492-8cf22a80-515d-11e9-93f3-ca5cd030b217.jpeg)

<hr />

背景：页面采用svg模式进行渲染，使用了minimap控件

问题：（页面采用SPA开发）minimap控件渲染group的时候，会抓取页面上所有的font-face，导致大量的性能浪费在获取字体库上

问题代码块：
![WechatIMG242](https://user-images.githubusercontent.com/29418758/55132668-1dc90600-515e-11e9-9e61-d23647474ee8.jpeg)

但是：代码中可以通过shouldProcess绕过字体库，所以想问有没有办法配置自己的shouldProcess函数呢，不知道有没有什么workaround?

**Comment by scaletimes** [comment]
@phantomlution 目前minimap支持三种渲染模式，建议使用keyshap的模式来
