### ISSUE TITLE
Shape[shapeType] is not a constructor

### ISSUE THREAD

**Issue by guozhaolong** [antvis/g6#664]
* **G6 Version**: 3.0.0
* **Platform**: macOS
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![1](https://user-images.githubusercontent.com/1046601/55139095-e8c5af00-516f-11e9-8b05-4c90bada1865.png)
我注册了两个node，然后在第一个node的draw下面addShape(第二个自定义node)就会报这个错误，上图是我跟踪最终源码报错信息的位置

**Comment by elaine1234** [comment]
方便的话 codepen 贴一下你的代码？这个错误看起来像没注册节点就在代码中用了对应的节点

**Comment by guozhaolong** [comment]
@elaine1234 
`const data = {
  nodes: [{ id: 'node1', x: 100, y: 200, label: 'test1', shape: 'a', },
    { id: 'node2', x: 300, y: 200, label: 'test2', shape: 'circle', },]
};
G6.registerNode('a', {
  draw(cfg, group) {
    group.addShape('b', {
      attrs: {
        x: width/2,
        y: 0,
      }
    });
  }
});
G6.registerNode('b', {
  shapeType: 'b',
  getShapeStyle(cfg) {
    return {
      x: cfg.x,
      y: cfg.y,
      r: 4,
      stroke: '#037aff',
      fill: '#fff',
      cursor: 'crosshair',
    };
  },
},'circle');
`

**Comment by guozhaolong** [comment]
@elaine1234 不知道为啥不能上传图片了，我只能把代码贴上来了。。。我看了一下源码应该是在自定义节点里不能addShape自定义节点
const data = {
  nodes: [{ id: 'node1', x: 100, y: 200, label: 'test1', shape: 'a', },
    { id: 'node2', x: 300, y: 200, label: 'test2', shape: 'circle', },]
};
G6.registerNode('a', {
  draw(cfg, group) {
    group.addShape('b', {
      attrs: {
        x: width/2,
        y: 0,
      }
    });
  }
});
G6.registerNode('b', {
  shapeType: 'b',
  getShapeStyle(cfg) {
    return {
      x: cfg.x,
      y: cfg.y,
      r: 4,
      stroke: '#037aff',
      fill: '#fff',
      cursor: 'crosshair',
    };
  },
},'circle');

**Comment by guozhaolong** [comment]
@elaine1234 我的需求是要设计一个类似g6-editor中流程节点的锚点，我想把锚点定义为一个新的node，这样我就可以设置锚点的state了，否则我只能在我的流程节点下添加几个circle代表锚点，然后当我要设置锚点状态的时候，我只能通过在流程节点中找到所有的锚点挨个循环去设置，很麻烦

**Comment by guozhaolong** [comment]
@elaine1234 在draw方法里的group.addShape只能是@antv/g下面的那几些图形，G6.registerNode只是能注册新的node，不能是新的shape，我是这么感觉的，也就是说在G6.registerNode的draw方法中不能调用其他注册的节点

**Comment by elaine1234** [comment]
group.addShape 是 G 的接口，是用来绘制基础图形的。
一个节点在绘制的时候并不能感知别的节点配置。

**Comment by guozhaolong** [comment]
@elaine1234 多谢，了解了

**Comment by xiaosongxiaosong** [comment]
我在使用最新版本的 G6 自定义 Dom 会报这个错误

demo代码位置：
https://codesandbox.io/s/g6-dom-node-demo-9w6gsi

代码来源：
https://antv-g6.gitee.io/zh/docs/manual/middle/elements/nodes/custom-node#5-%E4%BD%BF%E7%94%A8-dom-%E8%87%AA%E5%AE%9A%E4%B9%89%E8%8A%82%E7%82%B9

报错
![image](https://user-images.githubusercontent.com/2703455/206142702-34da6612-b3b1-4592-a9cc-4fd8ad476a2c.png)

**Comment by VladislavMaksimov** [comment]
> group.addShape is the interface of G, which is used to draw basic graphics.
> A node cannot perceive other node configurations when drawing.

I have the same error. Did you find the solution?

**Comment by Hareis** [comment]
I have the same error. Did you find the solution?

**Comment by JackFang-3** [comment]
实例化图的时候，配置一下 renderer: 'svg'，我是看官方发的评论，亲测有用
new Graph({
renderer:'svg'})
