### ISSUE TITLE
[Bug]: When the mouse is placed on a custom node, the action wheel cannot zoom in and out of the canvas

### ISSUE THREAD

**Issue by irelib** [antvis/G6#6664]
### Describe the bug / 问题描述

鼠标放在自定义节点上，操作滚轮无法对画布进行缩放

### G6 Version / G6 版本

🆕 5.x

### OS / 操作系统

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] Others / 其他

### Browser / 浏览器

- [X] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Safari (Limited support / 有限支持)
- [ ] IE (Nonsupport / 不支持)
- [ ] Others / 其他

**Comment by Aarebecca** [comment]
如果是 HTML/React 节点，需要自行将节点 `pointerEvents` 设为 `none`

**Comment by Rey-Wang** [comment]
@Aarebecca 除了配置pointerEvents 外，有其他的方法吗？因为 react 节点有自己的 button，graph 也有节点点击的业务，需要处各自理自己的业务逻辑
