### ISSUE TITLE
[Bug]: Custom nodes blur when the canvas is zoomed in

### ISSUE THREAD

**Issue by irelib** [antvis/G6#6666]
### Describe the bug / 问题描述

画布放大后，自定义节点会模糊
![F247CAB6-D6C8-4f44-B585-C91DDD708991](https://github.com/user-attachments/assets/a2a4a7ec-3955-452a-8fa3-8d057cb2edf2)

### G6 Version / G6 版本

Please select / 请选择

### OS / 操作系统

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] Others / 其他

### Browser / 浏览器

- [X] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Safari (Limited support / 有限支持)
- [ ] IE (Nonsupport / 不支持)
- [ ] Others / 其他

**Comment by chris-deng** [comment]
I have the same problem, custom node rendered by html

**Comment by Aarebecca** [comment]
这是因为 HTML(包括 React)节点在缩放过程中是通过 `transform` 实现的，这并非 Bug，而是实现逻辑导致的。你可以尝试将节点尺寸设置为一个较大的值。
