### ISSUE TITLE
如何扩展Item？

### ISSUE THREAD

**Issue by guozhaolong** [antvis/g6#668]
* **G6 Version**: 3.0.0
* **Platform**: macos
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![image](https://user-images.githubusercontent.com/1046601/55315366-c351e180-549e-11e9-9fbc-0d6e3b6eeb4e.png)
我想扩展一个锚点的Item出来，但new Anchor的时候提示我`Class constructor Item cannot be invoked without 'new'`，我试了在config.js中增加extraBabelIncludes也不好使

**Comment by elaine1234** [comment]
Item 目前不提供对外扩展机制，我们会考虑支持。如果目前要用，可以自行扩展 graph 实现
