### ISSUE TITLE
如何去掉图片的边框

### ISSUE THREAD

**Issue by yushengming** [antvis/g6#67]
G6.registNode('customHtml1', {
        getHtml: function(cfg){
          var model = cfg.model;
          var dom = Util.createDOM('<img src="C:/Users/C/Desktop/test/first_right.png" style="border:0 !important;">');
          console.log(dom);
          return dom;
        }
      }, 'html');

**Comment by TomHuangCN** [comment]
net.node().style({stroke:null})
