### ISSUE TITLE
G63.0 graph中流程图的初始缩放程度能设置吗，单个节点很大 

### ISSUE THREAD

**Issue by stevemoons** [antvis/g6#670]
G63.0 graph中流程图的初始缩放程度能设置吗，node是根据画布大小去自适应的，但是这种情况下，节点比较少的时候，节点显示很大，比较影响用户体验，请问这个如何解决？

**Comment by elaine1234** [comment]
可以的不要用`fitView()`，在画布渲染完成后你可以取一个`node`实例，用`node.getBBox()`取到当前节点的宽高，在graph 上用`zoom`方法缩放到你觉得合适的大小

**Comment by Rain20199** [comment]
zoom怎么页面居中？
