### ISSUE TITLE
3.0版本怎么给边添加箭头

### ISSUE THREAD

**Issue by notomorow** [antvis/g6#673]
2.0的文档里是有怎么定义箭头的，可是把相关代码在3.0里无效了。好像3.0的文档里并没有说怎么取定义箭头。ps:现在官网文档给的好多例子貌似都跑步起来了。

**Comment by elaine1234** [comment]
3.0 箭头的声明与 2.x 相同，如果有问题请附 codepen 链接。
官网 demo 列表：https://antv.alipay.com/zh-cn/g6/3.x/demo/index.html。我刚刚检查了一遍没有问题。如果哪个例子有问题请贴链接

**Comment by notomorow** [comment]
哦，怎么设置箭头我找到了。在node的style里设置endArrow: true就能看到箭头了。2.0文档里的“自定义边”一节中的示例片段https://codepen.io/DoriTong/pen/zmrXLo?editors=1010 打开就跑不通，控制台下面看到报错了。

**Comment by elaine1234** [comment]
G6 3.0 是不兼容版本，2.x 的版本 demo 需要制定一下版本 2.2.6 。
