### ISSUE TITLE
请问浏览器中canvas尺寸超出上限的情况有办法解决吗?

### ISSUE THREAD

**Issue by lyrstar** [antvis/g6#674]
因为canvas本身在浏览器中是有最大尺寸限制的, 要显示的数据比较多的时候会有一部分内容显示不出来, 请问有什么办法可以解决这个问题呢?

**Comment by elaine1234** [comment]
canavs固定一个大小，G6 支持拖拽平移画布，见例子： https://antv.alipay.com/zh-cn/g6/3.x/demo/flow/dagre.html
