### ISSUE TITLE
G6 editor 在编辑文本时，删除到最后一个字符时，会自动恢复

### ISSUE THREAD

**Issue by elvisxiao** [antvis/g6#675]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

测试地址如下：
https://antv.alipay.com/assets/dist/3.0.0/g6/1.x/editor/base.html
测试环境：
macbook pro 下的chrome Version 72.0.3626.109 (Official Build) (64-bit)
操作流程：
1. 拉入一个起始节点
2. 尝试更改起始节点名字，不全选，直接用delete按键往前删除即可。

**Comment by dxq613** [comment]
G6-Editor 不再对外提供支持。见谅！可以使用 G6 自己封装自己的 editor
