### ISSUE TITLE
监听 spreadout 事件，无法获取到展开节点。

### ISSUE THREAD

**Issue by no5no6** [antvis/g6#676]
G6版本：1.2.8
已经阅读过 issue 和 文档，未发现解决方案，请劳烦指出，谢谢。
[
<img width="1078" alt="问题" src="https://user-images.githubusercontent.com/5174886/55777088-72ab3b80-5ad1-11e9-92b9-8e1f37805e75.png">
](url)

代码如下：
```
this.tree.on('spreadout', ev => {
    // 在这个事件触发的时候我想获取当前展开的节点信息。
});
```

**Comment by baizn** [comment]
建议升级到3.x版本吧，1.x这个没人维护了。
