### ISSUE TITLE
v3.0.1 node:click edge:click all don't work

### ISSUE THREAD

**Issue by lirumeng** [antvis/g6#677]
* **G6 Version**: 3.0.1
* **Platform**: Chrome 73
* **Mini Showcase(like screenshots)**:
github demos is work: 
![image](https://user-images.githubusercontent.com/19973004/55778620-f0714600-5ad5-11e9-8a5d-dea2e86d4a5e.png)

but, codepen.io is not work
![image](https://user-images.githubusercontent.com/19973004/55778759-578efa80-5ad6-11e9-812a-1c1757413853.png)

* **CodePen Link**:
https://codepen.io/lirumeng/pen/JVbxNj?editors=0010

**Comment by lirumeng** [comment]
为啥不稳定，刚才点击有没有反应了

**Comment by elaine1234** [comment]
建议清空一下浏览器缓存

**Comment by lirumeng** [comment]
@elaine1234 清除缓存也无反应，在别人电脑上看的也无反应

**Comment by wellingfine** [comment]
确实有毒，遇到同样的问题，可以确定的一点是：当焦点不在浏览器内，直接点击的时候，node:click接收不到事件。但有时又很奇怪，刷新页面不行，需要重新打包一遍  
刚切到到3.0.5 beta版，发现node:click 事件完全没用了。。要看下源码是不是删掉了

**Comment by Shawn-Cui** [comment]
@lirumeng 现在我也遇到这样的问题了，不知道有没有比较靠谱的解决方案？
在Mac上还没有遇到点击没反应的情况，但是有些windows电脑上隔段时间会复现，复现的时候怎么点击都没反应
G6版本：3.0.4
