### ISSUE TITLE
箭头被隐藏

### ISSUE THREAD

**Issue by tengzhiqiang** [antvis/g6#678]
如题：我在尝试使用箭头的时候，箭头指向node的中心，导致node覆盖了箭头

![image](https://user-images.githubusercontent.com/17583643/55794044-d72cc180-5af6-11e9-8295-f772640a5bd0.png)

* **G6 Version**: 2.0
* **Platform**: windows
* **CodePen Link**: 代码在附件中
[code.txt](https://github.com/antvis/g6/files/3058455/code.txt)

**Comment by elaine1234** [comment]
3.0 版本解决了箭头这个问题。如果说功能不复杂建议升级到 3.0 版本，这里有 3.0 版本如何进行力导布局的文档https://www.yuque.com/antv/g6/qopkkg#4d221473
