### ISSUE TITLE
Behavior问题： drag-canvas和drag-node

### ISSUE THREAD

**Issue by ChenGuanYin** [antvis/g6#679]
* **G6 Version**: 3.0
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

1： 在画布上按下鼠标，进行拖拽画布。
2：鼠标不放开，移动到画布的外面，并且松开鼠标按键
3： 鼠标移动到画布里面，在不按下鼠标的情况下，画布依然处于拖拽事件中。

**Comment by elaine1234** [comment]
这个不能说是问题。我们在设计 G6 的时候就考虑到了这个点。这个地方的 drag 在鼠标离开 canvas 的时候有两种情况：
- 离开后画布仍能响应拖拽。
- 离开后拖拽结束。

我们没有办法限定死用户只能用哪种行为，所以在这里是默认选择的第一种模式。在鼠标回到画布后，可以点击一下画布取消拖拽行为。如果说想实现第二种效果，可以监听 canvas 的 mouseleave 事件，配合 behavior 的 shouldBegin, shouldUpdate 实现。
