### ISSUE TITLE
【建议】鉴于v3和v2的api完全不兼容，建议出个升级指南，另外v2还在维护吗？

### ISSUE THREAD

**Issue by xiadd** [antvis/g6#681]
如果v2不再维护了，升级或者换库是必然选择

**Comment by elaine1234** [comment]
2.x 版本只会做重大的，影响使用的 bug 维护，不会再有新 feature 了。鉴于 3.0 版本是不兼容更新，对于 2.x 的老项目升级代价有点高。我们的建议是已经由 2.x 版本实现的业务，在需求满足的情况下不需要升级。对于新项目，鼓励用 3.0 来做开发。
