### ISSUE TITLE
image节点怎么使用本地图片资源？

### ISSUE THREAD

**Issue by pma934** [antvis/g6#684]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by dxq613** [comment]
直接通过 base64 的编码就可以了。支持的类型也比较多：
https://www.yuque.com/antv/g6/smhvyn#7572d9ba

**Comment by supportlss** [comment]
除了base64，具体要怎么写路径才能显示出来？

**Comment by zhangmengyi** [comment]
> 除了base64，具体要怎么写路径才能显示出来？
> 我用 img: './images/success.png‘ 不能显示出来

同问，请问有什么方法吗

**Comment by chenbj2333** [comment]
> > 除了base64，具体要怎么写路径才能显示出来？
> > 我用 img: './images/success.png‘ 不能显示出来
> 
> 同问，请问有什么方法吗
import center from '@/assets/center.png';

{
...
    type: 'image',
    img: center,
...
}

我是这样导的

**Comment by sandszhouSZ** [comment]
base64 怎么编码？
