### ISSUE TITLE
有没有获取graph的位移translate值的方法？

### ISSUE THREAD

**Issue by lirumeng** [antvis/g6#685]
* **G6 Version**: @3.0.1
* **Platform**: Window 10 Chrome 73
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by dxq613** [comment]
目前没有，不过可以通过内置的方法获取到。看一下 translate 的代码：
https://github.com/antvis/g6/blob/master/src/graph/graph.js#L524

**Comment by lirumeng** [comment]
好的，谢谢~
希望之后的版本里考虑加一下

我这样解决的，暂时在这里存个档：

> public computeTranslate(): Coord {
const x = this.graph._cfg.group.getMatrix()[6]
const y = this.graph._cfg.group.getMatrix()[7]
return { x, y }
}
