### ISSUE TITLE
G6.registerNode中用afterDraw修改shape为图片，但是afterDraw中group一直为undefined，只有cfg有值

### ISSUE THREAD

**Issue by foxcorrect** [antvis/g6#686]
* **G6 Version**:3.10
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:
![image](https://user-images.githubusercontent.com/21187318/56210559-a9142800-6088-11e9-94cb-59145d074032.png)
![image](https://user-images.githubusercontent.com/21187318/56210593-b7624400-6088-11e9-8cd3-5d42d68e4b20.png)
G6.registerNode('HW', {
    afterDraw: function afterDraw(cfg, group) {
        console.log(cfg, group)
    }
}, 'rect')
真的不知道为什么group一直是undefined，这样的话就无法addShape，就不能把图片加上去了

**Comment by dxq613** [comment]
我在这个页面里面试了试是可以打印出 group 来的：
https://antv.alipay.com/zh-cn/g6/3.x/demo/other/default-shapes.html

![image](https://user-images.githubusercontent.com/1264678/56259080-714ac600-6104-11e9-8373-6fad44f8e71e.png)
