### ISSUE TITLE
node自定义图片的问题

### ISSUE THREAD

**Issue by aimaodeyuer** [antvis/g6#69]
let nodes = [{
      x: ESB_X,
      y: ESB_Y,
      id: 'esb',
      shape: 'http://localhost:8090/img/server.png',
      size: APP_NODE_SIZE,
      label: 'ESB',
      nodeType: ESB
    }]
其中shape属性写http开头的链接就可以显示图片，但是写img/server.png就显示不了。引用路径肯定是没问题，不知道是为什么。或者有什么其他的写法？

**Comment by aimaodeyuer** [comment]
@TomHuangCN 求助

**Comment by TomHuangCN** [comment]
不妨试用html节点实现图片 https://antv.alipay.com/g6/demo/06-other/htmlnode.html

**Comment by aimaodeyuer** [comment]
感谢！我还是使用了http链接方式，动态获取host显示图片了，用html显示也是个方法，待会儿试试。
