### ISSUE TITLE
拖拽回调事件对象大概率拿不到item对象

### ISSUE THREAD

**Issue by iBlackPi** [antvis/g6#690]
问题描述：拖拽节点，或者放大缩小节点时，回调事件对象，大概率获取不到item对象，节点size经常出现与拖拽后尺寸不相符的现象
demo测试地址：https://antvis.github.io/g6/tools/index.html

**Comment by guozhaolong** [comment]
代码放上来看一下，你的问题是两件事么？一个是回调取不到item，一个是拖拽后size发生变化？

**Comment by iBlackPi** [comment]
`const data = {
      nodes: [
        {
          x: 140,
          y: 210,
          size: [
            69,
            69,
          ],
          id: 'node1',
        },
        {
          x: 270,
          y: 210,
          id: 'node2',
        },
      ],
      edges: [
        {
          source: 'node1',
          id: 'edge1',
          target: 'node2',
        },
      ],
    };
    // 第四步：配置G6画布
    // eslint-disable-next-line
    this.net = new G6.Net({
      id: 'mxClient', // 容器ID
      mode: 'edit',
      width: 500, // 画布宽
      height: 500, // 画布高
    });
    // 第五步：载入数据
    this.net.source(data.nodes, data.edges);
    // 第六步：渲染关系图
    this.net.render();
    this.net.on('dragend', (e) => {
      console.log(e);
    });`
拖拽结束后，在e对象里面有时有item，有时没有

**Comment by guozhaolong** [comment]
你把dragend改为node:dragend试一下

**Comment by iBlackPi** [comment]
监听不到事件，我用的是官网上的1.2.8版本   https://antvis.github.io/g6/doc/tutorial/start/base.html

**Comment by guozhaolong** [comment]
我一直在用3.0.0版本，建议你也更新到最新版本别用老的了

**Comment by iBlackPi** [comment]
好吧，因为我看到你们官方羽雀说明文档上说【https://www.yuque.com/antv/g6/intro      1、3.0 版本正在开发中，详细的文档在后面逐步放出    2、beta 版本 bug 比较多，慎用】所以就干脆用了老版本

**Comment by guozhaolong** [comment]
大哥，我也是使用者，不是官方的，3.0正式版早就出了啊

**Comment by babyyage** [comment]
大哥  你这个问题后来解决了么    item 或targetItem 有时都拿不到
