### ISSUE TITLE
点击力导图节点，push data图没有更新，但是clear(),data(),render()都执行了，求解

### ISSUE THREAD

**Issue by it5200** [antvis/g6#691]

**Comment by it5200** [comment]
使用了addItem()可以，但是感觉很别扭

**Comment by elaine1234** [comment]
G6 不支持数据双向绑定，并不会跟着你数据的变化而刷新视图，添加节点请使用`graph.addItem` 或 `graph.changeData`

**Comment by xsfxtsxxr** [comment]
// 1.如果用的是class component，就在componentWillUnmount里面重置数据
componentWillUnmount(){
  graph = null
  nodes = []
  edges = []
}
// 2.如果用的是function component，就在useEffect里面清除，第二参数空数组，相当于componentDidMount，只开始执行一次，里面return相当于componentWillUnmount
useEffect(() => {
  // ....
  return () => {
    graph = null
    nodes = []
    edges = []
  }
},[])

// 这样一来，再次进入页面的时候会重新调用graph = new G6.Graph({...})，重新生成canvas画布
