### ISSUE TITLE
G6 3.0的Grid插件水平方向会超出画布范围？

### ISSUE THREAD

**Issue by SongOfLightAndShadow** [antvis/g6#698]
![G63 0bug](https://user-images.githubusercontent.com/24238531/56787578-8f64a480-682f-11e9-998f-37ea87748744.jpg)

**Comment by elaine1234** [comment]
可以提供一下复现的 demo 吗？

**Comment by SongOfLightAndShadow** [comment]
> 可以提供一下复现的 demo 吗？
你好,这是demo的压缩包，使用的是G6 3.0.2
[G6BUG.zip](https://github.com/antvis/g6/files/3125828/G6BUG.zip)

**Comment by elaine1234** [comment]
网格是根据 canvas 的父元素来定大小的，可以给 G6.Graph 的 container 增加 css 指定宽高为 graph 的宽高
