### ISSUE TITLE
我想问一下React支持G6吗？

### ISSUE THREAD

**Issue by xuxiaoqiang33** [antvis/g6#70]

**Comment by TomHuangCN** [comment]
g6 基于原生js写的，支持任何前端框架

**Comment by xuxiaoqiang33** [comment]
好的，非常感谢

**Comment by dodio** [comment]
请问如何销毁实例呢？

**Comment by dodio** [comment]
@xuxiaoqiang33

**Comment by mawienan123** [comment]
react怎么引用g6呢

**Comment by TomHuangCN** [comment]
g6 可以在react框架下运行，不过 g6 暂时没有基于 react 的封装。需要用户比较理解react组建的生命周期。将 G6 的生命周期融到 rc 组建的生命周期里。

**Comment by bnerDY** [comment]
@TomHuangCN 那未来会有类似于react通用组件的g6封装么，现在的话基本上是用一个图就自己定制一下了
