### ISSUE TITLE
G6 1.0 如何画一个自调用的线

### ISSUE THREAD

**Issue by Domy** [antvis/g6#705]
类似3.0的效果
![image](https://user-images.githubusercontent.com/3655223/57450224-80024400-7290-11e9-9942-1c680634d885.png)

**Comment by SongOfLightAndShadow** [comment]
大哥，花几天重构代码换到3.0吧....

**Comment by elaine1234** [comment]
3.0 源码中 util 下有自环计算逻辑，可以在你的代码中实现
