### ISSUE TITLE
3.0.4版本在chrome浏览器，edge:click点击事件有时会失效

### ISSUE THREAD

**Issue by lmooc** [antvis/g6#708]
3.0.4版本在chrome浏览器，edge:click点击事件有时会失效，浏览器打断点也无法走到

* **G6 Version**:3.0.4
* **Platform**:Chrome浏览器
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by elaine1234** [comment]
请提供一下 demo

**Comment by tm-roamer** [comment]
我遇到了这个情况g6v3.0.1， vue3.0cli全家桶开发， registerBehavior的监听在chrome v68, v70版本偶现交互监听没有绑定成功，chrome打断点debug不进入，devServer模式/npm run build模式（dist）都有问题。

window10 64位的开发环境（若干机器测试都有此现象）

代码结构如下
let graph = new G6.Graph()
// 官方实例， 点击节点添加连线的那个例子
G6.registerBehavior()


就会出现绑定不上的情况， 

排查： 
   1 webpack打包构建缓存的锅， npm run build还是出现
   1 怀疑是vue的mounted钩子没有触发（mounted调用的g6）， 实际测试还是每次都会触发。
