### ISSUE TITLE
beginAdd后需要做些操作要监听什么事件？

### ISSUE THREAD

**Issue by zarte** [antvis/g6#709]
net弄的编辑器，需要实现连续添加线，现在的情况是，添加一次后就不能继续添加了，要重新点击事先绑定的按钮触发beginAdd操作才能继续添加。  
想在mouseup里自动调用beginAdd发现不可以，虽然触发了对应的方法仍，会变成拖拽节点的框  
用的是1.2.8的版本

**Comment by baizn** [comment]
建议升级到3.x，连续连线的操作可以通过切换mode实现。
