### ISSUE TITLE
more document & source code

### ISSUE THREAD

**Issue by wbpmrck** [antvis/g6#71]
RT,could you please show the source code of G6 please? want to know more details about the implemetation.

and the docs is still poor,especially the tree graph.

thx!

**Comment by bq-hentai** [comment]
I tried `G6` yesterday And I want to use it in my project. But no source map so I am not sure I can use it. So could u pls share the source map or even the source code ? Thx :)

**Comment by TomHuangCN** [comment]
there is no g6 open source plan recently
