### ISSUE TITLE
环形树数据如果设置了collapsed，点击会一直报错

### ISSUE THREAD

**Issue by gonenoob** [antvis/g6#710]
在示例页面 https://antv.alipay.com/zh-cn/g6/3.x/demo/tree/radial-tree.html
对data数据操作
```
let {children=[] } = data

children.map(child => {
  if(child.children) {
   	child.collapsed = true
  }
})

```

运行后点击节点，会一直报get的错误

**Comment by elaine1234** [comment]
官网的 g6 版本没有及时更新，树图数据直接操作是从 3.0.4 开始支持的
