### ISSUE TITLE
初始时把子节点收起时，显示异常

### ISSUE THREAD

**Issue by gonenoob** [antvis/g6#713]
https://codepen.io/gonenoob/pen/NVdwzb
当我把子节点收起时，渲染出来的节点特别小。这时候该怎么调整才能正常显示呢？

**Comment by elaine1234** [comment]
graph.fitView() 可以缩放图形到适应当前视窗大小。如果就是想改节点大小，在节点上设置 size

**Comment by gonenoob** [comment]
> graph.fitView() 可以缩放图形到适应当前视窗大小。如果就是想改节点大小，在节点上设置 size

我设置了 fitView额，显示还是不正常的啊

**Comment by gonenoob** [comment]
> graph.fitView() 可以缩放图形到适应当前视窗大小。如果就是想改节点大小，在节点上设置 size

我只要把数据里collapsed设置成false，显示是正常的。设置成true，适配的就有问题
