### ISSUE TITLE
zoom-canvas监听的鼠标滚轮事件放大缩小与用户习惯不一致

### ISSUE THREAD

**Issue by lanzhenxiang** [antvis/g6#714]
滚轮事件放大，缩小，一般情况下，鼠标滚轮向上是缩小，向下是放大，插件实现的方式正好相反
![image](https://user-images.githubusercontent.com/27193912/57761401-048d1080-7730-11e9-8f56-022a2a99f584.png)
可通过修改缩放比例计算方式修复(src/behavior/zoom-canvas.js)

**Comment by SongOfLightAndShadow** [comment]
用负数就行...

**Comment by lanzhenxiang** [comment]
感谢您的回复，问题已解决，
![image](https://user-images.githubusercontent.com/27193912/57821239-65fdbf80-77c2-11e9-8057-6681b87c014c.png)
