### ISSUE TITLE
g6 3+如何实现g6-editor功能

### ISSUE THREAD

**Issue by liuqiyu** [antvis/g6#715]
请问新版的g6有没有实现g6-editor的案例。因为之前文档说会给新版的g6支持实现editor，希望能给一些提示或者案例。非常非常谢谢

**Comment by SongOfLightAndShadow** [comment]
你把3.0的文档看一遍基本就能自己实现了...

**Comment by liuqiyu** [comment]
> 你把3.0的文档看一遍基本就能自己实现了...
这么强么。能指导下么

**Comment by linvinglor** [comment]
同求,好多G6新版本的功能 g6-editor都用不了

**Comment by Cyrilszq** [comment]
https://github.com/antvis/g6-editor
可以看下这里更新的 README，提供更多原子能力由开发者自行组装其实更加灵活。利用 G6 3.0 现有的 API 其实已经可以方便的实现一个流程图编辑器。
最近写了个非常简单的例子可以参考下：
https://github.com/Cyrilszq/g6-flow-editor
http://g6.demo.cyrilszq.cn

**Comment by garyganyang** [comment]
要用G6去重新实现一遍G6Editor的所有功能例如右键菜单, addGroup, unGroup等也着实感觉重复造轮子, 不知道有什么好的办法

**Comment by caoyu48** [comment]
http://62.234.69.136/  vue+g6 3.x

**Comment by lulei90** [comment]
同求，想知道新版本该如何编辑节点文本修改文字内容
