### ISSUE TITLE
fitView在默认collapsed:true时处理有问题

### ISSUE THREAD

**Issue by gonenoob** [antvis/G6#717]
https://codepen.io/gonenoob/pen/NVdwzb
可以看到，数据子节点中collapsed:true，已设置fitView，但是显示的整体图特别小
如果将collapsed改为false，显示正常

**Comment by elaine1234** [comment]
没明白你说的问题。。collapse 为 true 时是怎么样的，你预期应该是怎么样的？

**Comment by gonenoob** [comment]
@elaine1234 预期是显示的点会和  collapse 为false的大小一致，或者更大一点。现在collapse  true的时候显示的点比false更小

**Comment by baizn** [comment]
你参考下这个[示例](https://antv.alipay.com/zh-cn/g6/3.x/demo/tree/radial-tree.html)呢，收起展开是OK的。

**Comment by gonenoob** [comment]
> 示例

但是初始时候默认收起是有问题的

**Comment by Yanyan-Wang** [comment]
最新版本应该是没问题的：https://codepen.io/Yanyan-Wang/pen/bGdLQYY
