### ISSUE TITLE
请问vue中可以使用gg-editor吗？如果想要实现界面编辑，有那些方法呢？

### ISSUE THREAD

**Issue by lymi1022** [antvis/g6#721]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by linvinglor** [comment]
同求

**Comment by elaine1234** [comment]
请移步：[GGEditor repo](https://github.com/gaoli/GGEditor)

**Comment by caoyu48** [comment]
http://62.234.69.136/
