### ISSUE TITLE
Treegraph如果节点collapsed默认为true则无法正常展开

### ISSUE THREAD

**Issue by cpa0701** [antvis/g6#722]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

如题，样例中collapsed为true则无法展开，只有当collapsed为false时才能正常显示，同样情况还发生在节点已经折叠后新增子节点同样报错
![image](https://user-images.githubusercontent.com/24648209/58232177-720df200-7d6b-11e9-876e-a46a22d2f983.png)

**Comment by ayiaq1** [comment]
你G6版本是多少，我们也遇到这个问题，你们如何解决的

**Comment by elaine1234** [comment]
官网 demo 没有同步更新。collapse 为 true 时默认折叠是在 ~3.0.4 版本后才支持的，文档请见：https://www.yuque.com/antv/g6/treegraph#7e82459c。
