### ISSUE TITLE
3.0.1 registerBehavior的监听在chrome v68, v70偶现交互监听没有绑定成功

### ISSUE THREAD

**Issue by tm-roamer** [antvis/g6#724]
* **G6 Version**:  3.0.1
* **Platform**: window 10 x64  chrome v68， chrome v70
* **Mini Showcase(like screenshots)**:  无
* **CodePen Link**:  无

---------------- 检索了关闭的issues, 都并未实质解决， 希望能重视此类问题 ------------------
之前的同学都有类似的问题出现，是偶现的，不容易复现
#677 v3.0.1 node:click edge:click all don't work  
#700 v3.0.2 的graph中设置node:click 无效，在chrome 
#708 v3.0.4版本在chrome浏览器，edge:click点击事件有时会失效

-----------------------
我使用vue3.0cli全家桶开发， registerBehavior的监听在chrome v68, v70版本偶现交互监听没有绑定成功，chrome打断点debug不进入，devServer模式/npm run build模式（dist）都有问题。

window10 64位的开发环境（若干同window系统环境，机器测试都有此现象）

伪代码结构如下
let graph = new G6.Graph()
// 官方实例，点击节点添加连线的那个例子
G6.registerBehavior()
偶尔就会出现绑定不上的情况，

排查：
1 怀疑是webpack打包构建缓存的锅， npm run build还是出现，不是webpack的问题
2 怀疑是vue的mounted钩子没有触发（mounted调用的g6）， 实际测试mounted每次都会触发。

**Comment by elaine1234** [comment]
click 不 work 与注册行为没有关联。click 问题是电脑触摸板 force touch 等会出现，是已知问题。behavior 绑定问题请附源码 codepen

**Comment by baizn** [comment]
的确存在这个问题，原因是底层对事件处理那块考虑不全，后面会发一个版本，发布了后通知你，再更新下G就可以了

**Comment by baizn** [comment]
更新G版本到3.4.6

**Comment by wxy1995** [comment]
@baizn @elaine1234 更新G到3.4.6。使用内置behavior: click-select，仍然会出现onClick偶尔没有触发。
环境是 MacOS 10.14.2, Chrome 75。
但是在macbook touch上，tap to click 没有问题，click 会出现问题。

**Comment by baizn** [comment]
@wxy1995 G外网还没有发布新版本，你可以先按这个[#pr](https://github.com/antvis/g/pull/125/files)改下node_modules中G对应的文件，你关注下G的版本，发布了后你更新下就OK了。

**Comment by avennn** [comment]
@baizn 什么时候g6 release一个新版解决这个问题？

**Comment by Manjushaka** [comment]
这个问题什么时候修复呢

**Comment by Raywh** [comment]
。。。

**Comment by baizn** [comment]
> @baizn 什么时候g6 release一个新版解决这个问题？

目前G4.0正在在开发中, G6下个大版本会升级底层渲染引擎G。

**Comment by Shawn-Cui** [comment]
@baizn G6啥时候升级大版本啊？😂

**Comment by baizn** [comment]
请关注开发计划[文档](https://www.yuque.com/antv/g6/zrdoi3)，后续的发布计划都会更新进去的。

**Comment by Yanyan-Wang** [comment]
G6 3.4 已经发布，底层 G 已经升级。
