### ISSUE TITLE
自环问题

### ISSUE THREAD

**Issue by lmooc** [antvis/g6#725]
边是自环时，setState没有起作用，自环应该怎样设置边的动画呢？

* **G6 Version**:G6 3.0
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by elaine1234** [comment]
描述不明确，请附复现 codepen

**Comment by lmooc** [comment]
连接单个节点自身的边,可以设置边的动画吗？

**Comment by elaine1234** [comment]
https://antv.alipay.com/zh-cn/g6/3.x/demo/scatter/hover-animate.html

**Comment by lmooc** [comment]
我描述的是单个节点形成的自环，自环边设置动画
