### ISSUE TITLE
节点选中时，颜色会变深，这个有 API 可以设置的么？

### ISSUE THREAD

**Issue by c0hb1rd** [antvis/g6#727]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

场景是这样子的，我先加载了预先保留过的节点和边，然后同态的根据后端的返回结果来改变节点的颜色（一个轮询的批量节点颜色更新），但是发现这样子改后，节点的颜色会变深，鼠标移上去再移出来颜色就变正常了，跟选中时颜色变深有点类似，请问有没有办法可以固定颜色呢？

**Comment by baizn** [comment]
根据结果处理后的颜色设置成hover上去的颜色，另外你确认下根据后端返回结果处理后变深了的颜色值是哪里设置的？

**Comment by IMlixingwang** [comment]
自定义节点可以通过 重写  getSelectedStyle  getActivedStyle getSelectedOutterStyle  getStyle 这些方法来改变节点激活选中时颜色
