### ISSUE TITLE
脑图如何控制节点显示的方位

### ISSUE THREAD

**Issue by tolerance-go** [antvis/g6#728]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by tolerance-go** [comment]
某些节点在左侧，某些在右侧

**Comment by elaine1234** [comment]
mindmap 有个选项 `getSide`。见https://www.yuque.com/antv/g6/treegraph，提issue 前请先仔细检索文档
