### ISSUE TITLE
请问能拖动edge属性到画布吗

### ISSUE THREAD

**Issue by liuqiyu** [antvis/g6#729]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by liuqiyu** [comment]
@yuanchuan @RaoHai

**Comment by yuanchuan** [comment]
@liuqiyu  我并不是 Antvis 成员，以前用到过 g6 这个库，也在 issues 列表中回答过几个问题，可能是你 at 我的原因。

很感谢 Antvis 开源 g6，不过通过他们对待 issue 的态度，和版本的迭代方式，不是很推荐使用 g6。你这个问题 90% 也不会有人理的

**Comment by baizn** [comment]
拖动Edge属性到画布？  你的具体需求和操作是怎样的呢，麻烦稍微描述详细一点，多谢！

**Comment by liuqiyu** [comment]
@baizn 你好。就是想做一个editor，单纯的拖拉一条边线到画布上面。类似这种
![image](https://user-images.githubusercontent.com/19789062/59001052-c15e2300-883f-11e9-9b90-bfca68c2933f.png)

**Comment by liuqiyu** [comment]
@yuanchuan 哈哈 不好意思。

**Comment by baizn** [comment]
@liuqiyu 可以的，拖动过去addShape('line', { attrs: { ... } })就可以了
