### ISSUE TITLE
constom-tree 代码报错“Uncaught TypeError: Cannot read property 'get' of undefined”

### ISSUE THREAD

**Issue by sshien** [antvis/g6#730]
[官方示例](https://antv.alipay.com/zh-cn/g6/3.x/demo/tree/custom-tree.html)
这个链接里的自定义树，总报错“Uncaught TypeError: Cannot read property 'get' of undefined”

* **G6 3.0.4**:
* **Web**:

**Comment by sshien** [comment]
我的数据错了

**Comment by MutelyMilo** [comment]
请问数据格式
{"name":"Modeling Methods","children":[{"name":"Classification"}]}
这也有问题吗？？？？

**Comment by MutelyMilo** [comment]
> 我的数据错了

请问 您现在的数据格式什么样子呢

**Comment by suwu150** [comment]
我集成到react中,能够正常显示树,但一直会报这个错.我查看官方示例,刚开始使用的是如下版本:
```
 "@antv/g6": "^3.0.5-beta.7",
    "@antv/hierarchy": "^0.5.0",
```
打开时就报错,这个错误,当我将版本修改为演示案例中的版本时:`    "@antv/g6": "3.0.2",
    "@antv/hierarchy": "0.4.0",`打开时不会报错了,但是当我点击的时候,还是会提示如下错误.请问怎么解决?
![image](https://user-images.githubusercontent.com/20339760/62940813-f4f09700-be06-11e9-8a79-d6dfdf056ed5.png)
