### ISSUE TITLE
6月5号重新npm install g6 后节点数据结构变化，并且渲染进入死循环导致浏览器卡死

### ISSUE THREAD

**Issue by comll18** [antvis/g6#731]
之前数据结构：
![image](https://user-images.githubusercontent.com/18279634/58927593-c6f53380-8781-11e9-8c8f-28982b4a1f41.png)

重新安装后：
![image](https://user-images.githubusercontent.com/18279634/58927537-97dec200-8781-11e9-81cc-9fc0866202ff.png)

数据结构中没有data，并且渲染完成后浏览器卡死

**Comment by dxq613** [comment]
锁定一下版本号试试，看看是哪个版本的问题。我们在定位一下

**Comment by elaine1234** [comment]
请见文档说明：https://www.yuque.com/antv/g6/treegraph#7e82459c
<img width="777" alt="屏幕快照 2019-06-06 上午10 13 13" src="https://user-images.githubusercontent.com/8325822/59002078-c02ef500-8843-11e9-87f1-f25e7fe61adf.png">
