### ISSUE TITLE
[BUG]节点点击事件不一定能被捕获到

### ISSUE THREAD

**Issue by ObservedObserver** [antvis/g6#732]
* **G6 3.0.4**:
* **Platform Chrome**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

节点的点击事件不一定能够被捕获到。(回调函数没有被调用)

Demo: 官网给出的参考样例就可以复现该问题 https://antv.alipay.com/zh-cn/g6/3.x/demo/tree/custom-tree.html。

点击节点，有一定概率节点不会收缩。

**Comment by zudashuai** [comment]
我也有发现相同问题，求解，这个问题不解决，估计就不考虑用G6了。

**Comment by ObservedObserver** [comment]
是G6依赖的G的问题，修复方式可见 https://github.com/antvis/g/pull/126

**Comment by baizn** [comment]
更新G到最新版本
