### ISSUE TITLE
g6会支持手机移动端?

### ISSUE THREAD

**Issue by j787701730** [antvis/g6#737]
g6会支持手机移动端? 我写了touchstart事件触发不了this.g6Graph.on('canvas:touchstart', function () {}; this.g6Graph.on('touchstart', function () {}; 两种写法.

**Comment by baizn** [comment]
支持的
```
el.addEventListener('touchstart', e => {
      if (!Util.isEmpty(e.touches)) {
        self._triggerEvent('touchstart', e.touches[0]);
      }
    }, false);
```

也可以在graph上面绑定的话使用click事件来实现。
