### ISSUE TITLE
G6的展示图中，是如何实现选中节点，在节点旁显示相关操作的？

### ISSUE THREAD

**Issue by yuaiqaing** [antvis/g6#740]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

[图片]

**Comment by yuaiqaing** [comment]
![image](https://user-images.githubusercontent.com/43852626/59651897-290c5a80-91be-11e9-992f-68d86a1d6c12.png)

**Comment by baizn** [comment]
```
graph.on('node:contextmenu', evt => {
    // 在这里定位你要操作内容的DOM容器，left = evt.x + 'px'， top = evt.y + 'px'
  })
```

**Comment by yuaiqaing** [comment]
哦哦，谢谢
