### ISSUE TITLE
treegraph删除任意节点，伸缩其他任何节点时，执行freshLayout()报错，如何解决

### ISSUE THREAD

**Issue by yuaiqaing** [antvis/g6#741]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![image](https://user-images.githubusercontent.com/43852626/59735623-e2376700-9288-11e9-9be6-873cc3fa3291.png)
![image](https://user-images.githubusercontent.com/43852626/59735656-0dba5180-9289-11e9-8742-4c32bfc68d46.png)
![image](https://user-images.githubusercontent.com/43852626/59735663-16128c80-9289-11e9-9df3-4bf8c8670688.png)

**Comment by yuaiqaing** [comment]
补充：删除一个节点，点击另一个节点，伸缩。再次执行freshLayout时报错
![image](https://user-images.githubusercontent.com/43852626/59735689-40644a00-9289-11e9-8d48-16c25bd492b4.png)

**Comment by yuaiqaing** [comment]
注册的伸缩行为      
G6.registerBehavior('clickNode', {
          getDefaultCfg() {
            return {
              //发生收缩扩展的回调
              onChange() {
              }
            };
          },
          getEvents() {
            return {
              'node:click': 'onNodeClick'
            };
          },
          onNodeClick(e) {
            const item = e.item;
            const graph = this.graph;
            //如果节点进行过更新，model会进行merge，直接改model不能改布局，所以需要去改源数据
            const sourceData = graph.findDataById(item.get('id'));
            const children = sourceData.children;
            //叶子节点的收缩和展开没有意义
            if (!children || children.length === 0) {
              return;
            }
            ;
            const collapsed = !sourceData.collapsed;
            if (!this.shouldBegin(e, collapsed)) {
              return;
            }
            ;
            sourceData.collapsed = collapsed;
            graph.emit('itemcollapsed', {
              item: e.item,
              collapsed
            });
            if (!this.shouldUpdate(e, collapsed)) {
              return;
            }
            ;
            try {
              this.onChange(item, collapsed);
            } catch (e) {
              console.warn('');
            }
            //检测是否删除子节点
            console.log('已删除节点',item._cfg.children[0].destroyed)
            debugger
           //此处报错
            graph.refreshLayout();
            debugger
            this.updateShape(item);
          },
          updateShape(item) {
            const graph = this.graph;
            if (item.getModel().children.length != 0) {
              item.getOutEdges().forEach(edge => {
                const copyEdge = edge.getModel();
                graph.update(graph.findById(copyEdge.id), {
                  shape: 'cubic-horizontal'
                });
              });
              item.getModel().children.forEach(child => {
                if (child.children != undefined) {
                  if (child.children.length != 0) {
                    this.updateShape(graph.findById(child.id));
                  }
                }
                ;
              });
            }
          }
        });

**Comment by scaletimes** [comment]
麻烦提供下 CodePen 链接

**Comment by yuaiqaing** [comment]
额，不好意思。之前没用过codepen，我用的vue，从后台读取的数据，试了一下，放在codepen里，还没成功。请问还有其他办法吗，主要是freshLayout函数报错。

**Comment by yuaiqaing** [comment]
我重新写个demo，发出来。可能会晚一点，不好意思。

**Comment by yuaiqaing** [comment]
![image](https://user-images.githubusercontent.com/43852626/59765657-1df61f00-92d1-11e9-8768-7d2613be4496.png)
![image](https://user-images.githubusercontent.com/43852626/59765689-2ea69500-92d1-11e9-8946-6688abb2e8c2.png)
我把调好的demo放到codepen，on那个方法好像执行失败了。第一次用这个，水平有限，还请大佬帮我看看：    https://codepen.io/yuaiqaing/pen/JQRzXG?editors=1111

**Comment by yuaiqaing** [comment]
顺便请问下，g6的撤销方法，是调用的哪个

**Comment by yuaiqaing** [comment]
报错出现在：右键任意节点，弹出菜单，删除选中节点，再次单击节点，收缩子节点时报错。
demo最终报错截图
![image](https://user-images.githubusercontent.com/43852626/59766549-0c157b80-92d3-11e9-9fe3-f145a48c128e.png)

**Comment by scaletimes** [comment]
@yuaiqaing 可以看下这个文档，然后调整下你的实现就好了  https://www.yuque.com/antv/g6/yinbck

**Comment by yuaiqaing** [comment]
![image](https://user-images.githubusercontent.com/43852626/59768475-0326a900-92d7-11e9-909e-db058e4560a9.png)
请问这个有例子可以借鉴吗，不是很明白这一块的内容
![image](https://user-images.githubusercontent.com/43852626/59768548-22bdd180-92d7-11e9-99ab-243d01f281c8.png)

**Comment by johe-a** [comment]
@yuaiqaing 请问您最终是怎么解决的呢 我在大数据量的情况下也遇到这个错误
