### ISSUE TITLE
如何获取节点位置

### ISSUE THREAD

**Issue by justb** [antvis/g6#743]
* **G6 Version**: 3.0.4
* **Platform**: All
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/22002343/59828604-f4d79c00-936d-11e9-8a08-ca60dce79f34.png)
![image](https://user-images.githubusercontent.com/22002343/59828644-0ae55c80-936e-11e9-8e6b-92a4054be1d6.png)

需求是让根节点处于canvas中心，现在有focusPoint的替代品吗？ https://github.com/antvis/g6/issues/65

**Comment by baizn** [comment]
获取节点的坐标：node.getBBox()。
![image](https://user-images.githubusercontent.com/9443867/59851095-5283dc80-939e-11e9-8487-4543fd363029.png)

移动到画布中心用[graph.focusItem()](https://www.yuque.com/antv/g6/graph#b1paw)方法。

**Comment by justb** [comment]
感谢 @baizn ，graph.focusItem()解决了我的问题，node.getBBox()获取的是画布坐标吧，文档更新的也更详细了！
