### ISSUE TITLE
g6 3.0.4版本 事件监听无法监听到节点

### ISSUE THREAD

**Issue by lQei** [antvis/G6#744]
#724 
当前g3.4.6版本

在click事件中item为空
node:click事件无法监听到

还是有时候可以监听到

this.graphData = {
nodes: [{
id: 'node1',
shape:'circle',
label: 'START',
x: 100,
y: 100,
labelCfg:{

		    }
		 },{
		    id: 'node2',
		    shape:'rect',
		    x: 100,
		    y: 200
		 },{
			 	id: 'node3',
			 	shape:'rect',
		    x: 200,
		    y: 200
		  },{
		  	id: 'node4',
		  	shape:'circle',
		  	label: 'END',
		  	size: 60,
		    x: 100,
		    y: 300,
		    style: {
		      lineWidth: 2
		    }
		  }],
		  edges: [
		  	{source: 'node1',target: 'node2'},
		  	{source: 'node2',target: 'node3'},
		  	{source: 'node2',target: 'node4'}
		  ]
		};
		var graph = new G6.Graph({
		  container: 'mountNode',
		  width: 500,
		  height: 500
		});
		graph.read(this.graphData);
		graph.on('node:click', ev => {
			console.log('node:click',ev)
			//that.clickGraphItem(ev)
		});
		graph.on('click', ev => {
			console.log('click',ev,ev.item)
		  const shape = ev.target;
		  const node = ev.item;
		  if(node){
		  	this.clickGraphItem(node)
		  }
		});

**Comment by baizn** [comment]
参考这个 #724
