### ISSUE TITLE
g6 3.0.5 beta6 changSize()后 图形会变大bug

### ISSUE THREAD

**Issue by j787701730** [antvis/g6#745]
g6 3.0.5 beta6 调用changSize()后 图形会变大bug

**Comment by anywhy** [comment]
遇到同样的问题了，npm仓库中的3.0.5 beta6版本，changSize(),会调用自适应视口 fitView()方法, 目前的我的解决方式是不直接调用```graph.changSize()```，调用```viewController```的```changSize()```之后重绘。
```
        graph.get('viewController').changeSize(clientWidth, clientHeight);
        graph.autoPaint();
```
