### ISSUE TITLE
G6的定位

### ISSUE THREAD

**Issue by tianxuzhang** [antvis/g6#748]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

建议职责分明：G2只考虑基础图表。G6把树状和图状都Cover住。所以G6最好加上旭日图和TreeMap等。

**Comment by baizn** [comment]
感谢建议，树图G6中已经添加了。
G6的定位是图可视化引擎，专注于由节点和边构成的关系图方面。
