### ISSUE TITLE
canvas:click 和 node:click 事件同时绑定时，有时点node时，触发canvas点击事件未触发node的点击事件

### ISSUE THREAD

**Issue by Robinbiao** [antvis/g6#749]
问题描述： 
    1.canvas:click 和 node:click 事件同时绑定时，有时点node时，触发canvas的点击事件未触发node的点击事件（偶现bug）。
出现条件： 
   1. window谷歌浏览器偶尔出现 ， mac系统 从未出现 。
   2.在g/event.js line:156  mousedownShape = null 导致点击target判定为canvas。

**Comment by successdream** [comment]
我绑定node:click不触发，不晓得怎么回事

**Comment by baizn** [comment]
G6和G的版本都更新到最新版本。
G：3.4.6 。
