### ISSUE TITLE
当前版本是3+了在Electron-vue中报错invalid container

### ISSUE THREAD

**Issue by MutelyMilo** [antvis/g6#750]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by MutelyMilo** [comment]
在快速上手稳定copy出来的代码 在vue项目中使用就报错了 没有尝试在 html中使用

**Comment by baizn** [comment]
在new G6.Graph之前，确保DOM已经渲染完成了。
