### ISSUE TITLE
如何在页面变动时调整显示效果？

### ISSUE THREAD

**Issue by SwordSealCity** [antvis/g6#751]
* **G6 Version: 3.0.2**:
* **Google Chrome**:
* **https://codepen.io/DoriTong/pen/pKbLVw**:
当页面大小有变动的时候如何再次渲染G6？或者刷新？
就是在window.onresize的时候触发
还有G6初始化的时候如何定义缩放的大小？
比如我想让树图按画布的60%来初始化，该如何写呢？谢谢。

**Comment by SwordSealCity** [comment]
graph.fitView(20);

**Comment by baizn** [comment]
使用[zoom](https://www.yuque.com/antv/g6/graph#EVpX2)及[changeSize](https://www.yuque.com/antv/g6/graph#zqQPf)方法。
graph.zoom(0.6)
![image](https://user-images.githubusercontent.com/9443867/61442744-c7850a80-a97a-11e9-8fca-a80590a0f6ea.png)

**Comment by serenehaly** [comment]
> 使用[zoom](https://www.yuque.com/antv/g6/graph#EVpX2)及[changeSize](https://www.yuque.com/antv/g6/graph#zqQPf)方法。
> graph.zoom(0.6)
> ![image](https://user-images.githubusercontent.com/9443867/61442744-c7850a80-a97a-11e9-8fca-a80590a0f6ea.png)

请问调用changeSize之后还需要做什么吗？我也要监听浏览器视图宽度改变画布大小，调用changeSize，能看到有执行这个事件，但是实际画布大小没有改变。。

![image](https://user-images.githubusercontent.com/14230501/82801501-fb409300-9eaf-11ea-8639-cbcd02a66a35.png)
