### ISSUE TITLE
treegraph是否支持撤销？请问如果可以，具体的接口是什么；如果不能，使用removeChild和addChild模拟时,addChild会把子节点放到父节点的子节点数组的最后的问题

### ISSUE THREAD

**Issue by yuaiqaing** [antvis/g6#754]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

treegraph是否支持撤销？如果不能，使用removeChild和addChild模拟时,addChild会把子节点放到父节点的子节点数组的最后的问题

**Comment by baizn** [comment]
undo redo这种问题请参考类似这种[文档](https://cloud.tencent.com/developer/news/123433)，TreeGraph没这种功能。
