### ISSUE TITLE
TreeGraph 是否有计划支持给边加上 label 文字信息

### ISSUE THREAD

**Issue by dd1994** [antvis/g6#759]
https://www.yuque.com/antv/g6/treegraph 文档下的评论里很多人都在问是否能支持

**Comment by baizn** [comment]
边上加label，之前也沟通过，不好加，定制性太强，暂无计划添加，业务上你可以根据实际情况自定义边，自定义边的时候加上label就可以了。

**Comment by seed008** [comment]
大佬怎么在TreeGraph的自定义边上添加文字
