### ISSUE TITLE
支持残影动画效果嘛？

### ISSUE THREAD

**Issue by mtsee** [antvis/g6#76]
没看到动画里面能支持残影效果呢？不支持吗？

**Comment by TomHuangCN** [comment]
1. 没有现有接口支持
1. 可在[自定义 Shape ](https://antv.alipay.com/zh-cn/g6/1.x/tutorial/custom-shape.html)的时候，使用绘图引擎动画接口自己实现：https://antv.alipay.com/zh-cn/g6/1.x/api/canvas.html#_%E5%8A%A8%E7%94%BB-animate
