### ISSUE TITLE
demo 上的树图改成3.0.4版本后 label 消失了

### ISSUE THREAD

**Issue by dd1994** [antvis/g6#760]
https://antv.alipay.com/zh-cn/g6/3.x/demo/tree/tree-compact-box.html 将 demo 中的 g6 版本号从 3.0.2 升级成 3.0.4 后 node 的 label 消失了

**Comment by baizn** [comment]
升级到最新版本试下

**Comment by dd1994** [comment]
@baizn 升级到最新的 3.0.5-beta.6 也不行

**Comment by baizn** [comment]
检查下你的数据，还是不行的话提供个demo吧

**Comment by dd1994** [comment]
@baizn 
如何重现：
1. 打开 <https://antv.alipay.com/zh-cn/g6/3.x/demo/tree/tree-compact-box.html>
2. 把 G6 的版本号改成 3.0.4, 如下图所示
![WeChatWorkScreenshot_27f97447-044d-46c5-a808-36c68f7517ab](https://user-images.githubusercontent.com/4121510/61625700-eacaf500-acad-11e9-9770-025337ef648a.png)
3. 点击运行按钮，如下图所示
![WeChatWorkScreenshot_28d0dcec-e192-4967-aff4-433eaa8c3082](https://user-images.githubusercontent.com/4121510/61625780-1948d000-acae-11e9-9ff5-0ce7db2d0db6.png)

**Comment by mengayng** [comment]
再添加完label之后在渲染一次，label就出来了

    if (model.children && model.children.length > 0) {
        model.labelCfg.position = 'left';
      } else {
        model.labelCfg.position = 'right';
      }
      console.log(node);
    });
    graph.render();   //在渲染一次
    graph.refresh();
    graph.fitView();

**Comment by baizn** [comment]
升级到最新版本后，也可以使用[graph.node(fn)](https://www.yuque.com/antv/g6/graph#1nq3A)方法
