### ISSUE TITLE
自定义节点时，调用addShape新增一个shape，直接监听无效

### ISSUE THREAD

**Issue by zhaiyuzhai** [antvis/g6#761]
* **G6 Version**: 2.2.6
* **Platform**: Windows
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

自定义的节点，调用addShape的api，但是如果直接在上面调用on监听click事件不生效，似乎只能在graph上面调用监听click事件才行

**Comment by baizn** [comment]
所有事件都在graph上面监听。
