### ISSUE TITLE
关于antv-g6容器自动根据文字大小拉伸宽度

### ISSUE THREAD

**Issue by yangfuhui** [antvis/g6#764]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

antv-g6如何让节点宽度、高度自适应节点内文字的大小、长度？

**Comment by baizn** [comment]
可以在draw方法中绘制之前获取到文字的长度和高度，使用计算出来的这个值设置节点的大小，但一般都不会这样去做。

**Comment by yangfuhui** [comment]
你说的这种情况下是要设置labelCfg相关的样式才能根据这个来处理吧，目前难道就没有自适应的




------------------ 原始邮件 ------------------
发件人: "Moyee"<notifications@github.com>; 
发送时间: 2019年7月22日(星期一) 下午4:03
收件人: "antvis/g6"<g6@noreply.github.com>; 
抄送: "清"<451824853@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [antvis/g6] 关于antv-g6容器自动根据文字大小拉伸宽度 (#764)




可以在draw方法中绘制之前获取到文字的长度和高度，使用计算出来的这个值设置节点的大小，但一般都不会这样去做。

**Comment by baizn** [comment]
没有的

**Comment by yangfuhui** [comment]
有没有好的想法或者demo参考下




------------------ 原始邮件 ------------------
发件人: "Moyee"<notifications@github.com>; 
发送时间: 2019年7月22日(星期一) 下午4:15
收件人: "antvis/g6"<g6@noreply.github.com>; 
抄送: "清"<451824853@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [antvis/g6] 关于antv-g6容器自动根据文字大小拉伸宽度 (#764)




没有的

**Comment by mengxiong10** [comment]
@yangfuhui 
自定义一个节点, 实现的, 先把文字画出来, 然后计算文字的大小, 再画边框
```
draw(cfg, group) {
      const paddingValue = 10;
      const { label } = cfg;
      const { nodeStyle } = options;

      const labelObj = group.addShape('text', {
        attrs: {
          x: paddingValue,
          y: paddingValue,
          text: label,
          textAlign: 'left',
          textBaseline: 'top',
          lineHeight: 1
        }
      });
      const labelBox = labelObj.getBBox();
      const width = labelBox.maxX + paddingValue;
      const height = labelBox.maxY + paddingValue;

      group.addShape('rect', {
        attrs: {
          width,
          height,
          x: -width / 2,
          y: -height / 2,
          radius: 4,
          ...nodeStyle
        }
      });

      labelObj.translate(-width / 2, -height / 2);
      labelObj.toFront();
      return group;
    },

```

**Comment by SakuraYou** [comment]
现在支持了吗？4.x 了，在文档中没看到可不可以
