### ISSUE TITLE
ERROR TypeError: Cannot read property 'compactBox' of undefined

### ISSUE THREAD

**Issue by mengayng** [antvis/g6#765]
Unresolved function or method compactBox() 

* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by mengayng** [comment]
import {AfterViewInit, Component, ElementRef, ViewChild} from '@angular/core';
import * as G6 from '@antv/g6';
import { Hierarchy } from '@antv/hierarchy';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements AfterViewInit {
  @ViewChild('chartView', {static: true}) chartView: ElementRef;

  constructor() {
  }

  ngAfterViewInit(): void {
    setTimeout(() => {
      this.tree();
    });
  }

  tree() {
    const data = [
      {id: 'Modeling Methods',
        chaldren: [
          {
            id: 'Classification',
            chaldren: [
              {
                id: 'Logistic regression',
              },
              {
                id: 'Linear discriminant analysis',
              },
              {
                id: 'Rules',
              },
              {
                id: 'Decision trees',
              }
            ]
          },
          {
            id: 'Consensus',
            chaldren: [
              {
                id: 'Logistic regression',
              },
              {
                id: 'Linear discriminant analysis',
              },
              {
                id: 'Rules',
              },
              {
                id: 'Decision trees',
              }
            ]
          },
          {
            id: 'Regression',
            chaldren: [
              {
                id: 'Logistic regression',
              },
              {
                id: 'Linear discriminant analysis',
              },
              {
                id: 'Rules',
              },
              {
                id: 'Decision trees',
              }
            ]
          }
        ]
      }
      ];
    const graph = new G6.TreeGraph({
      container: this.chartView.nativeElement,
      width: window.innerWidth,
      height: window.innerHeight,
      pixelRatio: 2,
      modes: {
        default: [{
          type: 'collapse-expand',
          onChange: function onChange(item, collapsed) {
            const modeldata = item.get('model').data;
            modeldata.collapsed = collapsed;
            return true;
          }
        }, 'drag-canvas', 'zoom-canvas']
      },
      defaultNode: {
        size: 16,
        anchorPoints: [[0, 0.5], [1, 0.5]]
      },
      defaultEdge: {
        shape: 'cubic-horizontal'
      },
      nodeStyle: {
        default: {
          fill: '#40a9ff',
          stroke: '#096dd9'
        }
      },
      edgeStyle: {
        default: {
          stroke: '#A3B1BF'
        }
      },
      layout: function layout(data) {
        return Hierarchy.compactBox(data, {
          direction: 'LR',
          getId: function getId(d) {
            return d.id;
          },
          getHeight: function getHeight() {
            return 16;
          },
          getWidth: function getWidth() {
            return 16;
          },
          getVGap: function getVGap() {
            return 10;
          },
          getHGap: function getHGap() {
            return 100;
          }
        });
      }
    });
    graph.data(data);
    graph.render();
    graph.getNodes().forEach(function (node) {
      const model = node.get('model');
      model.label = model.data.id;
      model.labelCfg = {
        offset: 10,
        style: {
          fill: '#666'
        }
      };
      if (model.children && model.children.length > 0) {
        model.labelCfg.position = 'left';
      } else {
        model.labelCfg.position = 'right';
      }
    });
    graph.refresh();
    graph.fitView();
  }
}
我的代码如上，不知道哪错了

**Comment by baizn** [comment]
使用下面这种方式试下，参考[文档](https://www.yuque.com/antv/g6/treegraph#a000b8e6)。
```
const graph = new G6.TreeGraph({
    container: 'mountNode',
    modes: {
      default: [{
        type: 'collapse-expand',                    // 定义收缩/展开行为
        onChange(item, collapsed) {                 
         console.log('graph now is going to do layout');
        }
      }, 'drag-canvas', 'zoom-canvas']
    },
    layout: {
      type: 'compactBox',
      direction: 'LR', // H / V / LR / RL / TB / BT
      // ...
    }
  ...cfgs
 });
```

**Comment by mengayng** [comment]
好的，谢谢了

**Comment by mengayng** [comment]
> 使用下面这种方式试下，参考[文档](https://www.yuque.com/antv/g6/treegraph#a000b8e6)。
> 
> ```
> const graph = new G6.TreeGraph({
>     container: 'mountNode',
>     modes: {
>       default: [{
>         type: 'collapse-expand',                    // 定义收缩/展开行为
>         onChange(item, collapsed) {                 
>          console.log('graph now is going to do layout');
>         }
>       }, 'drag-canvas', 'zoom-canvas']
>     },
>     layout: {
>       type: 'compactBox',
>       direction: 'LR', // H / V / LR / RL / TB / BT
>       // ...
>     }
>   ...cfgs
>  });
> ```
