### ISSUE TITLE
g6动态效果，切换到浏览器其他页签一段时间后，返回改动态效果图的问题（reopen）

### ISSUE THREAD

**Issue by deke1521** [antvis/G6#767]
140的bug在版本_antv.g6-3.0.2中又复现。
如打开http://antv.alipay.com/zh-cn/g6/3.x/demo/tree/custom-tree.html ，在切换到其他页面一段时间后返回，将不再能进行折叠。
140: https://github.com/antvis/g6/issues/140

**Comment by Yanyan-Wang** [comment]
新版本中应该已经不存在这个问题：https://g6.antv.vision/zh/examples/tree/customItemTree#customTree
