### ISSUE TITLE
treegraph是否支持居左操作

### ISSUE THREAD

**Issue by yuaiqaing** [antvis/g6#771]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![image](https://user-images.githubusercontent.com/43852626/61920118-09214100-af8b-11e9-8187-ac34deedf537.png)
如图，请问是否可以将tree，放到屏幕的左边

**Comment by yuaiqaing** [comment]
使用了fitViewPadding，
![image](https://user-images.githubusercontent.com/43852626/61923467-b3eb2c80-af96-11e9-9cd7-ca67d23e211f.png)
还是没有效果

**Comment by baizn** [comment]
从右边向左排列？ 根节点在右侧 ？

**Comment by yuaiqaing** [comment]
根节点在左边，整棵树移到屏幕的左侧，根节点距离画布左边边大概100px的距离

**Comment by yuaiqaing** [comment]
我把缩略图放到右下角了，所以希望可以把整棵树往左边挪一挪

**Comment by yuaiqaing** [comment]
翻了文档，感觉fitViewPadding是可以实现的，但是我传一个数组作为参数，整棵树还是关于画布中心对称显示

**Comment by baizn** [comment]
![image](https://user-images.githubusercontent.com/9443867/62131819-81cb2900-b30e-11e9-95ca-e1e43a34e181.png)

**Comment by baizn** [comment]
@yuaiqaing  fitViewPadding是从中间开始计算的，你可以试下看通过设置容器位置（CSS改变left值）可以达到你要的效果不。

**Comment by mastercbhw** [comment]
版本3.5.1, 在changeData()后，使用moveTo(0,0)，可以实现图例在左上角。
