### ISSUE TITLE
请问@ali/g6这个包合适能对外部开放下载？

### ISSUE THREAD

**Issue by chaserstrong** [antvis/g6#772]
目前@antv/g6下的功能无法满足我的需求，想用@ali/g6的包，但是我看官网内提示暂时不提供外部下载呢。ps： 我如果先用min压缩包代替，会有版权问题吗？
http://antvis.github.io/g6/doc/

**Comment by baizn** [comment]
安装@antv/g6 2.x版本的就可以了， @ali/g6是g6 2.x的版本。
不能满足的需求是什么需求呢？
