### ISSUE TITLE
treegraph 点击 节点 收缩 怎么一会正常，一会不正常的

### ISSUE THREAD

**Issue by junob** [antvis/G6#776]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by dd1994** [comment]
俺也一样

**Comment by suwu150** [comment]
@dd1994 @junob 你们都是不正常在哪里?是缺失还是报其他错误?

**Comment by baizn** [comment]
具体表示是咋样的呢？ 报错 还是 ？

**Comment by Raywh** [comment]
> 具体表示是咋样的呢？ 报错 还是 ？

graph.on

**Comment by Raywh** [comment]
> > 具体表示是咋样的呢？ 报错 还是 ？
> 
> graph.on
有时有用 有时没有。。。。。。。。。。。。

**Comment by morelearn1990** [comment]
这个bug是我在使用过程中发现的，我查看官方示例的时候发现也有同样的问题，
以下是官方示例地址：https://antv.alipay.com/zh-cn/g6/3.x/demo/tree/cloudatlas-tree.html

bug 复现的步骤是：
先点击一个有 children 的节点，然后再点击另外一个有 children 的节点的后面的展开收起图标，发现第一次点击的节点的 children 同时被收起来了。

**Comment by morelearn1990** [comment]
@Raywh

**Comment by morelearn1990** [comment]
可以试一下这样的各种交叉点击，就会发现展开和收缩的表现都不一样。

**Comment by morelearn1990** [comment]
我看了一下 collapse-expand 的源码发现，点击节点的时候节点的 sourceData 的 collapsed 已经发生改变了，但是 shouldUpdate 返回的 false，canvas 就没有进行刷新绘图，当点击另外一个节点的收缩按钮后返回了 true ，于是第一步点击的节点也同时进行了 draw 动作后刷新了。
这儿应该将  shouldUpdate 提前到改变 collapsed 的代码之前应该就没有问题了。

**Comment by morelearn1990** [comment]
上面我写的示例代码里面的 shouldUpdate 用成 shouldBegin 就好了。

**Comment by Raywh** [comment]
> 上面我写的示例地址里面的代码 shouldUpdate 用成 shouldBegin 就好了。

已搞定，谢谢

**Comment by Yanyan-Wang** [comment]
新版本应该不存在这个问题了，主要原因是 demo 里面的 collapse-expand 行为需要根据被点击的图形判断一下是否进行折叠：https://g6.antv.vision/zh/examples/tree/customItemTree#treeWithLargeData
