### ISSUE TITLE
API 文档无法访问

### ISSUE THREAD

**Issue by kaigekong** [antvis/g6#778]
https://www.yuque.com/antv/g6/

![image](https://user-images.githubusercontent.com/10705930/62424550-a7877200-b702-11e9-9b6f-198f3df1256c.png)

啥情况～

**Comment by kaigekong** [comment]
![image](https://user-images.githubusercontent.com/10705930/62424581-195fbb80-b703-11e9-9889-634781e2083d.png)

**Comment by baizn** [comment]
https://www.yuque.com/antv/g6/default-node
![image](https://user-images.githubusercontent.com/9443867/62431585-3cb65500-b75b-11e9-9208-5a143414f2e2.png)
可以访问啊，你看下是不是网络问题呢

**Comment by kaigekong** [comment]
嗯，早上6点多看已经正常了。
截屏提示的不是网络问题哦，谢谢回复。
