### ISSUE TITLE
请问如何节点显示多个label

### ISSUE THREAD

**Issue by loongmxbt** [antvis/g6#781]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

请问如何在节点上显示多个label，比如一个label在节点圆形的内部，用来标注节点的id，另一个label在节点的上方，用来显示一些数据。

查看文档已经实现tooltip显示数据文字。但能否直接使用label实现显示额外文字，而非鼠标onhover显示。

谢谢！

**Comment by loongmxbt** [comment]
https://antv.alipay.com/zh-cn/g6/3.x/demo/other/multipleNodeLable.html
找到实例了。

**Comment by dengxianMo** [comment]
可以

> https://antv.alipay.com/zh-cn/g6/3.x/demo/other/multipleNodeLable.html
> 找到实例了。

可以发下你的代码吗，链接已经看不到了

**Comment by Hinsssss** [comment]
> https://antv.alipay.com/zh-cn/g6/3.x/demo/other/multipleNodeLable.html 找到实例了。

能重新贴一下实例吗，这个网址过期了
