### ISSUE TITLE
Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by MutelyMilo** [antvis/g6#782]
`import G6 from '@antv/g6'
  import Hierarchy from '@antv/hierarchy'
	export default {
  name: "ReduceCom",
  components: {
    ChildrenReduceCom: (resolve) => {
      require(['../components/ChildrenReduceCom.vue'], resolve)
    }
    },
  data() {
    return {
      list:[
        {
        	show: true,
        	showInput: false,
          title: "Root",
          level: 1,
          key: 1,
          parent: null,
          children:[],
        }
      ]
    }
  },
  methods: {
	  printTree() {
	  	console.log(this.list);
      //
		  var COLLAPSE_ICON = function COLLAPSE_ICON(x, y, r) {
			  return [['M', x, y], ['a', r, r, 0, 1, 0, r * 2, 0], ['a', r, r, 0, 1, 0, -r * 2, 0], ['M', x + 2, y], ['L', x + 2 * r - 2, y]];
		  };
		  var EXPAND_ICON = function EXPAND_ICON(x, y, r) {
			  return [['M', x, y], ['a', r, r, 0, 1, 0, r * 2, 0], ['a', r, r, 0, 1, 0, -r * 2, 0], ['M', x + 2, y], ['L', x + 2 * r - 2, y], ['M', x + r, y - r + 2], ['L', x + r, y + r - 2]];
		  };
		  G6.registerNode('tree-node', {
			  drawShape: function drawShape(cfg, group) {
				  var rect = group.addShape('rect', {
					  attrs: {
						  fill: '#fff',
						  stroke: '#666'
					  }
				  });
				  var content = cfg.data.name.replace(/(.{19})/g, '$1\n');
				  var text = group.addShape('text', {
					  attrs: {
						  text: content,
						  x: 0,
						  y: 0,
						  textAlign: 'left',
						  textBaseline: 'middle',
						  fill: '#666'
					  }
				  });
				  var bbox = text.getBBox();
				  var hasChildren = cfg.data.children && cfg.data.children.length > 0;
				  if (hasChildren) {
					  group.addShape('marker', {
						  attrs: {
							  x: bbox.maxX + 6,
							  y: bbox.minX + bbox.height / 2 - 6,
							  r: 6,
							  symbol: COLLAPSE_ICON,
							  stroke: '#666',
							  lineWidth: 2
						  },
						  className: 'collapse-icon'
					  });
				  }
				  rect.attr({
					  x: bbox.minX - 4,
					  y: bbox.minY - 6,
					  width: bbox.width + (hasChildren ? 26 : 8),
					  height: bbox.height + 12
				  });
				  return rect;
			  }
		  }, 'single-shape');
		  var graph = new G6.TreeGraph({
			  container: 'mountNode',
			  modes: {
				  default: [{
					  type: 'collapse-expand',                    // 定义收缩/展开行为
					  onChange(item, collapsed) {
						  console.log('graph now is going to do layout');
					  }
				  }, 'drag-canvas', 'zoom-canvas']
			  },
			  defaultNode: {
				  shape: 'tree-node',
				  anchorPoints: [[0, 0.5], [1, 0.5]]
			  },
			  defaultEdge: {
				  shape: 'cubic-horizontal'
			  },
			  edgeStyle: {
				  default: {
					  stroke: '#A3B1BF'
				  }
			  },
			  layout: function layout(data) {
				  return Hierarchy.compactBox(data, {
					  direction: 'LR',
					  getId: function getId(d) {
						  return d.id;
					  },
					  getHeight: function getHeight() {
						  return 16;
					  },
					  getWidth: function getWidth() {
						  return 16;
					  },
					  getVGap: function getVGap() {
						  return 20;
					  },
					  getHGap: function getHGap() {
						  return 80;
					  }
				  });
			  }
		  });
		  let data = {data: {"name":"Modeling Methods","children":[{data: {"name":"Classification"}}]}}
		  // let data = {"name":"Modeling Methods","children":[{"name":"Classification"}]}

		  G6.Util.traverseTree(data, function(item) {
		  	console.log(item)
        item.id = item.name;
      });
      graph.data(data);
      graph.render();
      graph.fitView();
    }
  }
}`
对应实例是那个自定义tree，还请帮忙解决

**Comment by baizn** [comment]
麻烦提供了可复现的demo。

**Comment by MutelyMilo** [comment]
https://gitee.com/PhoenixMilo/study-vue.git
仓库地址  进入 go treelist 这个组件 然后 get new tree

**Comment by baizn** [comment]
> https://gitee.com/PhoenixMilo/study-vue.git
> 仓库地址 进入 go treelist 这个组件 然后 get new tree

麻烦提供个在线demo，[codepen](https://codepen.io)上可复现的demo。
