### ISSUE TITLE
3.0.5 布局问题

### ISSUE THREAD

**Issue by mengxiong10** [antvis/g6#783]
* **G6 Version**: 3.0.5
自带了@antv/hierarchy@0.5.0版本, demo是0.4.0版本, 下图的问题

![深度录屏_选择区域_20190807145048](https://user-images.githubusercontent.com/14135808/62601613-58208c00-b924-11e9-9964-8275d21a581c.gif)

**Comment by baizn** [comment]
[hierarchy](https://github.com/antvis/hierarchy/commit/798dac741596d39871120c30b224781b5a3ea46e)里面默认位置处理成(0, 0)了，我处理下hierarchy中的方式。

**Comment by baizn** [comment]
hierarchy 更新到0.6.0，或者下个G6版本（本周内发布）会更新。
