### ISSUE TITLE
通过双击 node 添加关系的节点

### ISSUE THREAD

**Issue by 13540675414** [antvis/g6#787]
通过addItem 方法添加node和edges,用refresh()刷新数据。
现象：添加的点在左上方，并且没有连线显示。
注明：node里面没有坐标数据。

**Comment by guozhaolong** [comment]
没有坐标数据显示在左上方不是很正常么。。。

**Comment by 13540675414** [comment]
因为我第一次接触G6还有好多不明白的，那也就是addItem 这个方法是必须加上坐标信息么。还有就是连线没显示会是什么问题呢？谢谢

**Comment by baizn** [comment]
绘制节点要么指定坐标数据，要么使用布局，参考这个[demo](https://antv.alipay.com/zh-cn/g6/3.x/demo/other/default-shapes.html)。
