### ISSUE TITLE
html定义图形的bug

### ISSUE THREAD

**Issue by ayiaq1** [antvis/g6#79]
http://antv.alipay.com/g6/demo/06-other/html2canvas.html
shape类型为html的 设置宽高之后 描点的宽高还是默认的大小，无法和自定义的html容器大小一致
![image](https://user-images.githubusercontent.com/3860498/31535243-fe82bd32-b02c-11e7-955e-80b0bd5b1ca8.png)

**Comment by TomHuangCN** [comment]
将于 1.2.0 修复

**Comment by TomHuangCN** [comment]
已修复
