### ISSUE TITLE
G6 3.0 如何自适应宽度？

### ISSUE THREAD

**Issue by dd1994** [antvis/g6#790]
<img width="390" alt="Screen Shot 2019-08-12 at 21 23 43" src="https://user-images.githubusercontent.com/4121510/62868158-90223780-bd47-11e9-9d9c-b16bd1ee2a28.png">

我看2.0的文档有写如果宽高不设置则自适应，

但是 [3.0 graph 初始化的文档里](https://www.yuque.com/antv/g6/graph)没有提到任何自适应宽高相关的东西，并且我测试了如果不写宽高也不能自适应

**Comment by baizn** [comment]
3.0需要指定宽高，没有自适应功能。
