### ISSUE TITLE
g6 3.0 能否使用icon，TreeGraph中节点和线能否自定义？

### ISSUE THREAD

**Issue by silvia-YQY** [antvis/g6#791]
* **G6 Version**: 3.0 
* **Platform**: Chrome
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

问题：
1. 3.0版本中，节点能否使用icon？2.0的版本可以使用dom元素自定义，但是3.0的文档没看到类似的功能？？
2. TreeGraph，节点是否能像graph一样自定义节点和线？我在id同一层添加shape没有任何效果。

**Comment by baizn** [comment]
1、可以使用image，可参考[这里](https://www.yuque.com/antv/g6/smhvyn#38d1e00e)；
2、可以自定义节点和边，具体参考这个[Demo](https://antv.alipay.com/zh-cn/g6/3.x/demo/tree/cloudatlas-tree.html)。
