### ISSUE TITLE
 Cannot read property 'x' of null

### ISSUE THREAD

**Issue by 13540675414** [antvis/g6#793]
G6.registerEdge('self-line', {
      autoRotate: true,
      drawLabel: function drawLabel(cfg, group) {
        const labelCfg = cfg.labelCfg || {};
**//执行下面的时候报  Cannot read property 'x' of null 异常
        const labelStyle = this.getLabelStyle(cfg, labelCfg, group);**

        const text = group.addShape('text', {
          attrs: Object.assign(labelStyle , {
            text: cfg.label,
            fontSize: 12,
            lineWidth: 5
          })
        });
        return text;
      }
    }, 'line');

注：用的是force 布局，在nodes 是里面是没有设置坐标属性的。
帮忙解答一下谢谢！

**Comment by baizn** [comment]
layout时节点的x、y坐标要计算正确， 不要出现NaN的情况。

**Comment by 13540675414** [comment]
嗯 谢谢
