### ISSUE TITLE
演示系统中,tooltipt提示undefined.

### ISSUE THREAD

**Issue by suwu150** [antvis/g6#794]
演示系统中,tooltip提示undefined.
* **G6 Version**:g6-3.0.2
* **Chrome**
* **CodePen Link**:[https://antv.alipay.com/zh-cn/g6/3.x/demo/tree/cloudatlas-tree.html](https://antv.alipay.com/zh-cn/g6/3.x/demo/tree/cloudatlas-tree.html)

**Comment by baizn** [comment]
好的，感谢，下次更新修复。

**Comment by suwu150** [comment]
目前我使用了另一种方案,使用对象配置回调函数的方法去替代,如下面代码 type: "tooltip",实现,应急的可以采用这种方案.:
```
...
modes: {
        default: [
          {
            type: "collapse-expand",
            shouldUpdate: (e) => {
              return e.target.get("className") === "collapse-icon";
            },
            onChange: (item, collapsed) => {
              this.selectedItem = item;
              const icon = item.get("group").findByClassName("collapse-icon");
              if (collapsed) {
                icon.attr("symbol", EXPAND_ICON);
              } else {
                icon.attr("symbol", COLLAPSE_ICON);
              }
            }
          },
          {
            type: "tooltip",
            formatText: (item, target) => {
              return item ?.data ?. name;
            }
          },
          {
            type: "drag-canvas",
            shouldUpdate: () => {
              return true;
            },
            shouldEnd: () => {
              return true;
            }
          }
        ]
      },
...
```

**Comment by selbest** [comment]
> 目前我使用了另一种方案,使用对象配置回调函数的方法去替代,如下面代码 type: "tooltip",实现,应急的可以采用这种方案.:
> 
> ```
> ...
> modes: {
>         default: [
>           {
>             type: "collapse-expand",
>             shouldUpdate: (e) => {
>               return e.target.get("className") === "collapse-icon";
>             },
>             onChange: (item, collapsed) => {
>               this.selectedItem = item;
>               const icon = item.get("group").findByClassName("collapse-icon");
>               if (collapsed) {
>                 icon.attr("symbol", EXPAND_ICON);
>               } else {
>                 icon.attr("symbol", COLLAPSE_ICON);
>               }
>             }
>           },
>           {
>             type: "tooltip",
>             formatText: (item, target) => {
>               return item ?.data ?. name;
>             }
>           },
>           {
>             type: "drag-canvas",
>             shouldUpdate: () => {
>               return true;
>             },
>             shouldEnd: () => {
>               return true;
>             }
>           }
>         ]
>       },
> ...
> ```

可以设置tooltip的样式吗？ 比如背景颜色，字体大小等等

**Comment by baizn** [comment]
已修复。
