### ISSUE TITLE
引用g6包后里面代码重写了window._方法

### ISSUE THREAD

**Issue by zwStar** [antvis/g6#798]
* **G6 Version**: 3.0.5-beta.7
* **Platform**: 
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

因为项目用了全局的_函数，在某个组件引入 g6后，发现该方法被重写
在build/g6.js代码里面的10921行有这么一句代码 
```
Ne._ = On
```

这里的Ne指向window， On为一个压缩名为lr的函数， 在g6源代码中并没有搜到对 _ 重写，所以应该是webpack的原因，麻烦协助看下

**Comment by baizn** [comment]
好的，我看下。

**Comment by zwStar** [comment]
> 好的，我看下。

大佬，查出原因了吗

**Comment by baizn** [comment]
G6中没有重写_这个方法，`_ `应该是引用了lodash的原因。
