### ISSUE TITLE
g6 Graph 能否固定指定节点

### ISSUE THREAD

**Issue by 13540675414** [antvis/G6#799]
我设置的画布是可以拖动，节点可以拖动，缩放等功能。我现在想固定某些节点不跟随画布移动、也不随其他节点缩放。是否能实现呢？

**Comment by baizn** [comment]
G6 3.0中现在内置功能不支持这个功能，要实现的话可以通过自定义这些Behavior，下个版本升级中这个功能会加进去。

**Comment by 13540675414** [comment]
那请问一下下一个版本什么时候发布呢？

**Comment by DaaMeiling** [comment]
希望树图的root不会动，拖动或者缩放、折叠收缩子节点都可以不动。
fixedRoot没看到效果..

**Comment by CoderLim** [comment]
什么版本支持呢，试了一下 3.1.3 貌似还不行

**Comment by Yanyan-Wang** [comment]
非树图的节点固定看这个教程：https://g6.antv.vision/zh/docs/manual/advanced/lock-node

**Comment by Yanyan-Wang** [comment]
树图根节点固定问题 v3.4.2 已修复。默认情况下会固定根节点位置。在图实例化时 layout 里面通过配置 fixedRoot 可以控制。

**Comment by gouzixing** [comment]
> 非树图的节点固定看这个教程：https://g6.antv.vision/zh/docs/manual/advanced/lock-node

请问一下有边的情况节点固定的解决方案，这个只能教程的边不会移动
