### ISSUE TITLE
g6.js?07cd:1 Uncaught TypeError: Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by suwu150** [antvis/g6#800]
treegraph使用时:

有时候(选中了父节点再去收缩子节点,然后再展开父节点),会出现上面这个提示,然后不能够将子节点收缩起来.
![image](https://user-images.githubusercontent.com/20339760/63233660-136dec80-c264-11e9-9adf-ab784b3a7f3f.png)

**Comment by baizn** [comment]
没太看懂，点击父节点时候它的子节点应该全都是收起来了的，麻烦能提供个demo不，或者官网上哪个demo也可以。
