### ISSUE TITLE
G6.registerBehavior方法的作用域只存在该函数内，vue项目中无法获取到data声明的变量

### ISSUE THREAD

**Issue by yuaiqaing** [antvis/g6#802]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![image](https://user-images.githubusercontent.com/43852626/63268880-c7549380-c2c7-11e9-841b-c33c2c1153b2.png)
![image](https://user-images.githubusercontent.com/43852626/63268903-d20f2880-c2c7-11e9-8f13-7d04fb3f47e8.png)
请问如何将onclick函数里的值更新到data中声明的变量里

**Comment by yuaiqaing** [comment]
![image](https://user-images.githubusercontent.com/43852626/63269276-71ccb680-c2c8-11e9-8a32-e5861ff08d3a.png)

**Comment by baizn** [comment]
onClick里面能否拿到值呢？ 能拿到的话通过传参数传进去。

**Comment by yuaiqaing** [comment]
虽然无法获取到data里的数据，但是可以获取到script下定义的数据
