### ISSUE TITLE
G6 3.x 自定义节点，如何在点击更换图片？

### ISSUE THREAD

**Issue by bluce** [antvis/g6#803]
* **G6 Version**:  3.0.4
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by baizn** [comment]
点击时候，获取节点的keyShape，修改keyShape的img属性。

**Comment by baizn** [comment]
参考新上的[Demo](https://antv.alipay.com/zh-cn/g6/3.x/demo/interaction/toggle-node-img.html)。

**Comment by chaserstrong** [comment]
补充一下：
可以通过以下代码，修改circle的lable的显示
graph.on('node:click', function(evt) {
      evt.item.get('model').label = 'fdsa';
      graph.updateItem(evt.item, evt.item.get('model'))
});
