### ISSUE TITLE
vue使用G6树图初始化不展示节点名称如何解决？

### ISSUE THREAD

**Issue by xiao-fe** [antvis/g6#804]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by xiao-fe** [comment]
![image](https://user-images.githubusercontent.com/54273267/63434519-d79b7880-c457-11e9-97ca-8c7ac66ff675.png)

**Comment by baizn** [comment]
你参考这个[Demo](https://antv.alipay.com/zh-cn/g6/3.x/demo/tree/tree-compact-box.html)，确定下是否是vue影响的？

**Comment by baizn** [comment]
升级到最新版本，参考下面方法解决：
```
graph.node(function(node) {
      return {
        size: 26,
        style: {
          fill: '#40a9ff',
          stroke: '#096dd9'
        },
        label: node.id,
        labelCfg: {
          position: node.children && node.children.length > 0 ? 'left' : 'right'
        }
      };
    });
```
