### ISSUE TITLE
求问g6的节点怎么画一个1/4圆呢

### ISSUE THREAD

**Issue by zhoustudent** [antvis/g6#805]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by baizn** [comment]
通过自定义节点，参考代码如下：
```
G6.registerNode('fannode', {
  draw(cfg, group) {
    const keyShape = group.addShape('fan', {
      attrs: {
        x: 50,
        y: 50,
        re: 40,
        rs: 30,
        startAngle: 1/2*Math.PI,
        endAngle: Math.PI,
        clockwise: false,
        fill: 'red'
      }
    })
    return keyShape
  }
})
```
效果如下图：
![image](https://user-images.githubusercontent.com/9443867/63570443-c9607000-c5af-11e9-858c-a52d57fdc941.png)

具体文档可参考[这里](https://www.yuque.com/antv/g6/smhvyn#df4d4c58)。
![image](https://user-images.githubusercontent.com/9443867/63570461-e9902f00-c5af-11e9-8641-18e558b946c7.png)
