### ISSUE TITLE
edge的位置有一些是画出从节点的右边，有一些是从节点的中间画出

### ISSUE THREAD

**Issue by zwStar** [antvis/g6#810]
* **G6 Version**: 3.0.5-beta.7
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

利用TreeGraph画出的线，某些线是从节点的右边画出，某些是从节点的中间位置画出，中间节点画出导致线盖住节点文字，这种位置差别是什么原因导致的

**Comment by baizn** [comment]
设置一下文本的层级试下，`text.toFront()`。
