### ISSUE TITLE
关于treeGraph的addChild方法bug

### ISSUE THREAD

**Issue by yuaiqaing** [antvis/G6#811]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![image](https://user-images.githubusercontent.com/43852626/63647675-69a4c900-c757-11e9-86d3-ad2ab4787394.png)
![image](https://user-images.githubusercontent.com/43852626/63647678-80e3b680-c757-11e9-944f-fe309e784ecc.png)
![image](https://user-images.githubusercontent.com/43852626/63647698-b25c8200-c757-11e9-8b2f-8f3a8d01fa2e.png)
![image](https://user-images.githubusercontent.com/43852626/63647716-ec2d8880-c757-11e9-901c-8bbef7c55047.png)
![image](https://user-images.githubusercontent.com/43852626/63647731-1bdc9080-c758-11e9-99a5-356b0e9019b7.png)
![image](https://user-images.githubusercontent.com/43852626/63647747-74ac2900-c758-11e9-8fca-851711e489da.png)
![image](https://user-images.githubusercontent.com/43852626/63647773-ca80d100-c758-11e9-82d9-d0632b4bf72a.png)
![image](https://user-images.githubusercontent.com/43852626/63647786-f308cb00-c758-11e9-821c-4e3fe8913f91.png)

**Comment by baizn** [comment]
动态添加数据后，需要调用`graph.refreshLayout()`，重新刷新下布局的。

**Comment by yuaiqaing** [comment]
![image](https://user-images.githubusercontent.com/43852626/63824516-05b61680-c98a-11e9-8ad6-f923d22bfdd4.png)
我这边刷新了的

**Comment by baizn** [comment]
点击没有children的节点，需要动态加载数据，我这里模拟了下，你看下这个[demo](https://codepen.io/baizn/pen/xxKdQMz)。
你的relatedData是需要添加到parNode中的数据吗？ 如果是需要添加到parNode节点后面的话，可以通过`graph.addChildren(relatedData, parNode)`一次性加进去的。

**Comment by yuaiqaing** [comment]
谢谢，我先试试看

**Comment by yuaiqaing** [comment]
![image](https://user-images.githubusercontent.com/43852626/63987113-77689e80-cb09-11e9-867d-29be43d4343b.png)
![image](https://user-images.githubusercontent.com/43852626/63987149-a1ba5c00-cb09-11e9-8e04-15afbe1bbdfe.png)
我用的是3.0.4，里面没有addChildren，只有addchild。那个demo里childData是一个对象，添加数组的话会出错
![image](https://user-images.githubusercontent.com/43852626/63987476-fc07ec80-cb0a-11e9-8835-b2a6e101bab3.png)
![image](https://user-images.githubusercontent.com/43852626/63987539-34a7c600-cb0b-11e9-9198-cabb7db03459.png)
![image](https://user-images.githubusercontent.com/43852626/63987562-48532c80-cb0b-11e9-9b4f-d76274a7670d.png)
![image](https://user-images.githubusercontent.com/43852626/63987603-70db2680-cb0b-11e9-97be-d3c2a086892c.png)

**Comment by yuaiqaing** [comment]
![image](https://user-images.githubusercontent.com/43852626/63987654-a97b0000-cb0b-11e9-99a5-7a56b60158fd.png

**Comment by baizn** [comment]
如果一次是添加多条的话，使用changeData，看这个[Demo](https://codepen.io/baizn/pen/xxKdQMz)。

**Comment by yuaiqaing** [comment]
![image](https://user-images.githubusercontent.com/43852626/63989618-82283100-cb13-11e9-8661-8187fe0743ff.png)
![image](https://user-images.githubusercontent.com/43852626/63989696-e0551400-cb13-11e9-9118-9232b91f63d4.png)
请问这个有推荐的问题排查方向吗

**Comment by baizn** [comment]
检查下layout的配置有问题没呢？
```
layout: {
      type: 'compactBox',
      direction: 'LR',
      defalutPosition: [],
      getId(d) { return d.id; },
      getHeight() { return 16 },
      getWidth() { return 16 },
      getVGap() { return 50 },
      getHGap() { return 100 }
    }
```
各个配置项参考[文档](https://www.yuque.com/antv/g6/treegraph#Messb)。

**Comment by yuaiqaing** [comment]
![image](https://user-images.githubusercontent.com/43852626/63990115-5c039080-cb15-11e9-83e6-5e029e0933e1.png)
是这样的

**Comment by zhengbigbig** [comment]
同样遇到这个问题  请问解决了吗  不考虑changeData

**Comment by yuaiqaing** [comment]
未解决

**Comment by baizn** [comment]
@yuaiqaing  @zhengbigbig  如果一次性添加多条数据，建议使用changeData，参考[这里](https://codepen.io/baizn/pen/xxKdQMz)；如果只添加一条，使用addChild。
出现相互遮挡这个问题，很有可能是数据中ID重复或ID为undefined导致的，检查下数据。

**Comment by gaodun2018** [comment]
参考线对齐有Bug。放大后看其实是歪的。测试了很多次了。确认是bug。望修复

**Comment by Yanyan-Wang** [comment]
考虑是 addChild 的时候新子节点的 id 重复导致的，这里 demo 是没问题的

https://codepen.io/Yanyan-Wang/pen/wvayQQy

**Comment by hellodr333** [comment]
这个bug 我也遇到了，你们是怎么解决的呢？我感觉问题没有解决啊怎么就关闭了
