### ISSUE TITLE
G6文档优化建议收集

### ISSUE THREAD

**Issue by baizn** [antvis/G6#815]
G6的文档，在今年6月份梳理了一遍，分别为[教程](https://www.yuque.com/antv/g6/default-node)和[API文档](https://www.yuque.com/antv/g6/api-global)，其中教程部分分为：基础教程、进阶教程、综合应用及源码系列。从大家使用的反馈情况来看，效果并不好，吐槽的也比较多，主要表现为：想要找的配置属性找不到、找到了的配置属性不知道如何使用。针对G6文档存在的文档，接下来我们会大力去改进，在此之前，想**征求下大家的意见**，了解一下大家心目中比较好用的G6文档应该是什么样子，**希望大家能够将自己的建议和看法分享出来**，同时，也非常欢迎大家能够加入到G6的文档完善中来，**一起共建G6的文档**，最终能够提供一份好用的文档。

我先抛砖引玉：
1、G6文档中不再透传出G的概念，Shape、文本、image等所有配置项均可在G6文档中查找到，提供一份全量的配置项手册；
2、API文档提供使用方式的示例代码；
3、提供丰富的案例教程：针对有代表性的案例，进行完整的说明，不能只是放一个demo，如[列表节点](https://antv.alipay.com/zh-cn/g6/3.x/demo/shape/listNode.html)、[卡片节点](https://antv.alipay.com/zh-cn/g6/3.x/demo/shape/cardNode.html)，要有对应的教程来讲如何使用G6从头实现。

特别感谢！

**Comment by caoyu48** [comment]
一定要有全文搜索功能 真的很蛋疼

**Comment by caoyu48** [comment]
参考一下vue的官方文档 由浅入深 由易到难 总体目录非常重要 能在那里说清楚的 最好别让我们自己去找 比如现在的文档，到处都是自己去看G啊什么的  还有就是例子 容易出问题的地方 等等 G6是个非常好用的东西，就是文档实在是让人欲仙欲死~希望尽快完善，同时感谢阿里开源，感谢各位大佬开发出这么好的东西

**Comment by OXOYO** [comment]
文档的引导作用欠缺，希望可以由浅入深的进行，并辅以相应的demo。文档可以划分为指南、api、demo几部分，针对各个api的基本配置、具体使用希望可以更清晰、丰富一些。
谢谢。

**Comment by caoyu48** [comment]
还有就是缺少教程 来套视频教程吧 从理论到实践 其实这个东西市场需求很旺盛

**Comment by caoyu48** [comment]
大佬们带我飞。。。

**Comment by caoyu48** [comment]
缺少交流群（社区） 官方开几个交流群什么的？不然有问题github上提啊 或者语雀上留言什么的效率太低，心里没底。。。官方团队就拿几个人，任务又多，哪有那么多时间解答小白那么多问题哦，还是要发动人民群众的力量

**Comment by AK081KA** [comment]
主要还是文档存在大量的问题，没人解答。建议交流群+demo丰富，每个api尽可能有对应demo，不然太抽象难以理解。

**Comment by suwu150** [comment]
1.演示代码尽量专一化,简单一些
2.对于文档中属性,尽量说明会有什么效果

**Comment by foolzhang** [comment]
目前还是得结合文档，然后看源码才能清楚绘制流程，欢迎大家已来讨论 。
demo了一个小例子 ，涵盖自定义节点，自定边，自定义行为 ，状态、样式修改，欢迎一起讨论 https://github.com/foolzhang/data-source-visualization

**Comment by baizn** [comment]
G6 图可视化交流群，欢迎加入。
https://www.yuque.com/antv/g6/intro#a2i8f
![image](https://user-images.githubusercontent.com/9443867/67007896-f9913e80-f11a-11e9-9150-af3bd488d6aa.png)

**Comment by Veath** [comment]
建议G的文档更详细一些。 shape 能提供demo更好了

**Comment by valenzhou** [comment]
希望能有一个类似于 echarts gallery 的交流区。

**Comment by lulei90** [comment]
建议做一下归类，经常查一些配置项要去到各个教程下面找很奇怪，建议参考下echarts的文档结构

**Comment by baizn** [comment]
> 建议做一下归类，经常查一些配置项要去到各个教程下面找很奇怪，建议参考下echarts的文档结构

恩，我们在归类处理，但 G6 和 Echarts 差别还是挺大的，文档上面组织起来可能会有点不一样。

**Comment by baizn** [comment]
> 希望能有一个类似于 echarts gallery 的交流区。

有一个交流群，gallery 交流区后面会考虑，目前 G6 群体还不够大。

**Comment by baizn** [comment]
> 1.演示代码尽量专一化,简单一些
> 2.对于文档中属性,尽量说明会有什么效果,如果能添加动画或者图像说明更好,(可能会占用大量时间)

新官网中的 Demo 会针对配置做一些

**Comment by baizn** [comment]
> 一定要有全文搜索功能 真的很蛋疼

新官网上线后会有搜索功能的，敬请关注 1122 AntV 品牌日。

**Comment by seujzhang** [comment]
最直观的就是想找一个东西很难找，我都是在chrome里面搜G6 XXX，然后进的语雀。

**Comment by baizn** [comment]
> 最直观的就是想找一个东西很难找，我都是在chrome里面搜G6 XXX，然后进的语雀。

新官网 1122 上线后就有全局搜索能力了。

**Comment by HJWAJ** [comment]
1.希望像element ui、antd的文档那样，每个api都有一个对应的demo和效果展示。
2.希望graph edge node等有详细的属性、方法列表，都汇聚在一起，特别是修改时调用什么方法，能设置哪些属性。
3.不要分什么初级中级高级文档了，没必要，反而让同一类的资料散落在各个地方，外加语雀没搜索，真的很蛋疼。

**Comment by baizn** [comment]
G6新官网已上线，支持搜索，https://g6.antv.vision/zh。
第2、3点认同，关于第一点 G6 和 antd 不是同一类的东西。

> PS: antd 偏右 亲自开发的官网模板。

**Comment by Yankj** [comment]
“文档实在是让人欲仙欲死” +1，
- 某一个属性的介绍常常要找好几个地方还不能搞清楚。
- 文档搜索很鸡肋，搜索结果都是去AntV，G6的内容却没搜到呢

**Comment by crystalwm** [comment]
希望有概念的比较。类似于vue.js中的计算属性（https://cn.vuejs.org/v2/guide/computed.html）
图中有一些交互操作，这时需要重新渲染视图。不是特别了解什么时候用什么方法性能最好，全靠看demo示例，哪个能够达到我想要的效果，我就用那个了。比如下面这几个方法。
```js
this.graph.paint();
this.graph.refresh();
this.graph.get('canvas')
          .draw();
this.graph.changeData(data);

```

**Comment by EmiyaYang** [comment]
在文档上找个 API 还是很费劲, 最后还是看`d.ts`找到的.

**Comment by Yanyan-Wang** [comment]
> 在文档上找个 API 还是很费劲, 最后还是看`d.ts`找到的.

官网上方的搜索功能可以搜到吗？还是缺了什么 API 吗？

**Comment by xjx0106** [comment]
就比如，新的g6圖是定義在某個方法裏面，那麽如果我要在另一個方法裏用graph.refresh(), 應該怎麽辦？

**Comment by Yanyan-Wang** [comment]
超级快的新官网上线了：http://g6.antv.antgroup.com/

**Comment by Yanyan-Wang** [comment]
> 就比如，新的g6圖是定義在某個方法裏面，那麽如果我要在另一個方法裏用graph.refresh(), 應該怎麽辦？

要操作图对象，需要能够访问到它。可能放到全局变量里？
