### ISSUE TITLE
Node can't be deleted when adding a line to itself

### ISSUE THREAD

**Issue by lancelixiang** [antvis/g6#82]
I add a line from b to b, when I delete the node b, there is a error show as blow.

![image](https://user-images.githubusercontent.com/9601858/31801350-33e9f4ac-b57a-11e7-879f-3bed91b9f7e1.png)

Demo: https://codepen.io/LanceLixiang/pen/WZmQQy?editors=1111

**Comment by TomHuangCN** [comment]
will fix it in next version

**Comment by TomHuangCN** [comment]
fixed in 1.2.0
