### ISSUE TITLE
双箭头时箭头与线条端点的空白间距该如何解决

### ISSUE THREAD

**Issue by OXOYO** [antvis/G6#821]
* **G6 Version**:  3.0.5-beta.7 
* **Platform**: Chrom 76
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**以下是单双箭头在不同d下的表现：**
```
// 箭头path
path: 'M10,0 L-10,10 L-10.707,9.293 L8.568,0 L-10.707,-9.293 L-10,-10 Z',
```
----
* **双箭头效果：**
  d: 15
![C$Z2BMA20_}L1ESZFXHJ FK](https://user-images.githubusercontent.com/5074207/64141610-51aa0500-ce3b-11e9-827e-0d91d4673df0.png)

  d: 10
![({0TT0IJQU(WO4 7@`UNE(B](https://user-images.githubusercontent.com/5074207/64141647-7900d200-ce3b-11e9-9db0-8792a8c73ae6.png)

  d: 5
![@__C_$3()_R2BBQGD7$Q`81](https://user-images.githubusercontent.com/5074207/64141575-33440980-ce3b-11e9-958b-12c5eec82610.png)

* **单箭头效果：**
  d: 15
![RMFR9MCHY@YWY`{NPJ((@ZS](https://user-images.githubusercontent.com/5074207/64141193-bc5a4100-ce39-11e9-88a3-63345e35f851.png)

  d: 10
![W5)%SY6DB8GF67KO(IM%{C0](https://user-images.githubusercontent.com/5074207/64141162-a51b5380-ce39-11e9-8292-b9136891f029.png)

  d: 5
![3SEWOY_%CCXY3GC9H@JI7](https://user-images.githubusercontent.com/5074207/64141199-bebc9b00-ce39-11e9-8d95-24fed1a28542.png)

**G相关源码：**
![{Q1WD{0)2SY~ELL){}2665X](https://user-images.githubusercontent.com/5074207/64141411-810c4200-ce3a-11e9-95fd-fa384f758b5b.png)
![903%FFPNJF5QJGRBH X@1V3](https://user-images.githubusercontent.com/5074207/64141414-823d6f00-ce3a-11e9-82f0-bd4c420dd0df.png)

现在理解的是d肯定是需要和M的距离相同，否则就会出现箭头插入图形(d: 5)或者箭头远离图形(d: 15)的情况。

**问题：**
1.双箭头时`箭头`与`线条`端点的空白间距该如何解决？

**Comment by baizn** [comment]
可以分别定义startArrow和endArrow，参考这个[Demo](https://antv.alipay.com/zh-cn/g6/3.x/demo/shape/polyline.html)。

**Comment by OXOYO** [comment]
> 可以分别定义startArrow和endArrow，参考这个[Demo](https://antv.alipay.com/zh-cn/g6/3.x/demo/shape/polyline.html)。

定义是可以，现在的问题是箭头和线有一段空白，如下图：
![QT~@%EJJIGH%2EW1Q6HO3`F](https://user-images.githubusercontent.com/5074207/64153682-ecb5d580-ce61-11e9-80a9-ccd20794dc18.png)

怎么消除这段空白呢？

**Comment by 957739315** [comment]
我也遇到存在间距的问题，请问这个怎么解决
