### ISSUE TITLE
请问要如何引用到实例中流程图的dagre呢？

### ISSUE THREAD

**Issue by CrabSAMA** [antvis/g6#822]
如题，我尝试过直接import是做不到的，我想在vue项目中实现G6流图中的流程图

**Comment by CrabSAMA** [comment]
运用的是npm引入

**Comment by baizn** [comment]
使用方法参考[这里](https://www.yuque.com/antv/g6/qopkkg#a824cd6a-1)，参考这个[Demo](https://antv.alipay.com/zh-cn/g6/3.x/demo/flow/node-flow.html)

**Comment by yangyipeng888** [comment]
流程图怎么没api说明文档，dagre可以像treeGraph那样addChild removeChild吗

**Comment by baizn** [comment]
dagre是一个布局的库而已，G6 3.1.0 内置了多种布局，可以直接使用内置的布局。https://www.yuque.com/antv/g6/agbmu2
