### ISSUE TITLE
设置 renderer 为 svg， lineAppendWidth 失效

### ISSUE THREAD

**Issue by viewweiwu** [antvis/g6#825]
* **G6 Version**: g6@3.0.5-beta.10
* **Platform**: chrome 76
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:  https://codepen.io/viewweiwu/pen/YzKEZPe?editors=0010

如题，设置 renderer 为 svg， lineAppendWidth 失效。如果有效的话鼠标的 cursor 应该是个小手。

**Comment by baizn** [comment]
是个BUG，请关注 这个 [Issue](https://github.com/antvis/g/issues/167)。
