### ISSUE TITLE
bug: two inter-group edges will become only one after a series of expanding and collapsing actions

### ISSUE THREAD

**Issue by lazyethan** [antvis/g6#828]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

dev305 7b81e55
chrome

fck and node2 are in group1, and node3 is in group2. And there are edges fck-node3 and node2-node3. After collapsing and expanding actions, node2-node3 is no longer shown.

Sample code as below:
        const data = {
            nodes: [
              {
                id: 'node6',
                groupId: 'group3',
                label: 'rect',
                x: 100,
                y: 300
              },
              {
                id: 'node1',
                label: 'fck',
                groupId: 'group1',
                x: 100,
                y: 100
              },
              {
                id: 'node9',
                label: 'noGroup1',
                groupId: 'p1',
                x: 300,
                y: 210
              },
              {
                id: 'node2',
                label: 'node2',
                groupId: 'group1',
                x: 150,
                y: 200
              },
              {
                id: 'node3',
                label: 'node3',
                groupId: 'group2',
                x: 300,
                y: 100
              },
              {
                id: 'node7',
                groupId: 'p1',
                label: 'node7-p1',
                x: 200,
                y: 200
              },
              {
                id: 'node10',
                label: 'noGroup',
                groupId: 'p2',
                x: 300,
                y: 210
              }
            ],
            edges: [
              {
                source: 'node1',
                target: 'node2'
              },
              {
                source: 'node2',
                target: 'node3'
              },
              {
                source: 'node1',
                target: 'node3'
              }
            ],
            groups: [
              {
                id: 'group1',
                title: '1',
                label: 'group1',
                parentId: 'p1'
              },
              {
                id: 'group2',
                title: '2',
                parentId: 'p1'
              },
              {
                id: 'group3',
                title: '2',
                parentId: 'p2'
              },
              {
                id: 'p1',
                title: '3'
              },
              {
                id: 'p2',
                title: '3'
              }
            ]
          };
          
          const graph = new G6.Graph({
            container: this._containerNodeId,
            width: 1000,
            height: 600,
            //pixelRatio: 2,
            modes: {
              default: [ 'drag-group', 'collapse-expand-group', 'drag-node-with-group' ]
            },
            defaultNode: {
              shape: 'circleNode'
            },
            defaultEdge: {
              color: '#bae7ff'
            }
          });
          
          graph.data(data);
          graph.render();

**Comment by baizn** [comment]
3.0.5-beta.11版本已修复，感谢。
