### ISSUE TITLE
G6 3.0.4 Item监听setState的逻辑是不是有问题？

### ISSUE THREAD

**Issue by bluce** [antvis/g6#829]
* **G6 Version**: 3.0.4
* **Platform**:Chrome
* **Mini Showcase(like screenshots)**:https://raw.githubusercontent.com/wiki/bluce/images/g6setState.png
* **CodePen Link**:

框1的判断，只要是有这个state，就直接return了，应该判断state对应的值是不是一样才return吧？

不然无法走到框2，上层监听的setState呢？

是不是BUG？

**Comment by bluce** [comment]
每次设置state必须先要把值重置，然后才能设置新的值

**Comment by baizn** [comment]
状态管理这块还需要再讨论下，目前的设计的确存在一些问题。

**Comment by bluce** [comment]
> 有这个 state， 并且 enable 是 true 的时候才直接 return 的，逻辑上是没问题的。

enable 不一定只是boolean类型的呢，如果我先传了1，然后再传2，这个2就没法更新

**Comment by baizn** [comment]
> > 有这个 state， 并且 enable 是 true 的时候才直接 return 的，逻辑上是没问题的。
> 
> enable 不一定只是boolean类型的呢，如果我先传了1，然后再传2，这个2就没法更新

这种情况可以使用两个不同的 state 来处理，假设值1为A，值2为B，则这样处理：
```
nodeStateStyles: {
   A: {},
   B: {}
}
```
再通过 graph.setItemState(item, 'A', true)   graph.setItemState(item, 'A', true) 更新。
