### ISSUE TITLE
G6 3.X 版本能否添加节点文本编辑示例？

### ISSUE THREAD

**Issue by lulei90** [antvis/g6#832]
* **G6 Version**:3.0.5-beta.7
* **Platform**:Chrom 76
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:
文档中事件对应的keydown和keyup事件不知道在哪些元素上能触发，能否对text节点加强编辑功能

**Comment by baizn** [comment]
keydown和keyup在所有元素上都会触发，3.x后续会侧重于图分析领域。
