### ISSUE TITLE
afterDraw shape getTotalLength 返回NaN

### ISSUE THREAD

**Issue by SamPeng87** [antvis/g6#835]
在和d3配合的时候。长度获取时机太早了。d3未渲染出正确的图形出来之前。开始点和结束点是一个不正确的值

**Comment by baizn** [comment]
afterDraw中一般是绘制完成后的一些附加处理，正常情况下进入到这个方法中，说明基础的绘制已经完成了，你这个case，麻烦提供个复现的Demo，多谢！

**Comment by dingyang9642** [comment]
赞同，是有这个问题
