### ISSUE TITLE
graph.clearItemStates(node)并没有按预期清除node的所有state

### ISSUE THREAD

**Issue by lokialone** [antvis/G6#836]
* **G6 Version**:   3.0.5-beta.9
* **Platform**: pc
* **Mini Showcase(like screenshots)**:   
* **CodePen Link**:

源码item ==> item.js下的函数clearStates, 当我没传入states, 仅会删掉原有的第一个状态而不是所有状
`var originStates = self.getStates();
    var shapeFactory = self.get('shapeFactory');
    var shape = self.get('model').shape;

    if (!states) {
      self.set('states', []);
      console.log(originStates);
      shapeFactory.setState(shape, originStates[0], false, self);
      return;
    }`

**Comment by baizn** [comment]
状态管理这块目前还在考虑，现在的处理方式还有很大的优化空间。
目前的处理方式是：需要传入清除的状态值，如果不传，默认只会清除第一个，你要全部清除的话，把states值传进来就行了。

**Comment by lokialone** [comment]
> 状态管理这块目前还在考虑，现在的处理方式还有很大的优化空间。
> 目前的处理方式是：需要传入清除的状态值，如果不传，默认只会清除第一个，你要全部清除的话，把states值传进来就行了。

主要是文档上写的与实现效果不一致。所以至少改下文档，不要误导之后的人0.0

**Comment by baizn** [comment]
> > 状态管理这块目前还在考虑，现在的处理方式还有很大的优化空间。
> > 目前的处理方式是：需要传入清除的状态值，如果不传，默认只会清除第一个，你要全部清除的话，把states值传进来就行了。
> 
> 主要是文档上写的与实现效果不一致。所以至少改下文档，不要误导之后的人0.0

👌

**Comment by Yanyan-Wang** [comment]
v3.4 已发布，graph.clearItemStates(node) 可以清除该节点上所有状态了
