### ISSUE TITLE
官方文档中并没有对节点样式有详细的说明，在节点中换行，有可能出现文字超出节点的情况

### ISSUE THREAD

**Issue by Knight0325** [antvis/g6#837]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by baizn** [comment]
节点中的样式，参看这个[文档](https://www.yuque.com/antv/g6/ffzwfp)，文本过长的话一般有两种处理方式：换行和省略后面过长的内容，使用省略号代替，具体参考[这里](https://antv.alipay.com/zh-cn/g6/3.x/demo/index.html#_%E6%96%87%E6%9C%AC)。
