### ISSUE TITLE
tooltip在空白区域出现，node的监听事件错乱

### ISSUE THREAD

**Issue by zhaiyuzhai** [antvis/g6#838]
* **G6 Version**: 2.2.6
* **Platform**: Windows
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

引入了tooltip, 在graph.read()读取数据之后，结果鼠标在空白区域的时候同样出现了tooltip。同时监听node:click的事件也会莫名其妙的触发，查不出什么原因导致的。正常情况下读取的数据不会出现这种情况。但是偶发，同时也对比了data，发现并没有什么不同
![20190910160514](https://user-images.githubusercontent.com/27955857/64595988-a1617100-d3e5-11e9-87d6-f0d2bc1772b8.png)

**Comment by baizn** [comment]
建议升级到3.x，2.x目前没有人力维护。
