### ISSUE TITLE
Unexpected token: keyword «const»

### ISSUE THREAD

**Issue by thinkmai** [antvis/g6#839]
* **G6 Version**:3.0.5
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:
build的时候报Unexpected token: keyword «const»，用3.0.5.beta.7没问题，请问这个是什么引起的呢？

**Comment by baizn** [comment]
能提供详细的保存信息吗，刚试了下本地build没报错。

**Comment by thinkmai** [comment]
https://github.com/thinkmai/g6lib.git,如果将版本改成3.0.5-beta.7，build可以通过，改成其他版本有问题，还请帮忙看看啥问题

**Comment by baizn** [comment]
你参考[https://github.com/yeyan1996/vue-template/issues/2](https://github.com/yeyan1996/vue-template/issues/2)这个看下，uglifyjs-webpack-plugin插件不支持ES6 [https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/362](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/362)，建议将uglifyjs-webpack-plugin换成uglify-js

**Comment by thinkmai** [comment]
谢谢，已经解决

**Comment by yesmeck** [comment]
这个问题还存在的，构建出来的文件里包含 const，低版本浏览器里无法运行。

**Comment by baizn** [comment]
3.4.9 版本修复了 https://github.com/antvis/G6/pull/1541
