### ISSUE TITLE
急救：3.0.4 treegraph,仅在mode中定义tooltip和style中定义.g6-tooltip，无法使用

### ISSUE THREAD

**Issue by yuaiqaing** [antvis/g6#843]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![image](https://user-images.githubusercontent.com/43852626/64920817-38676800-d7ee-11e9-961a-2ccee5125266.png)
![image](https://user-images.githubusercontent.com/43852626/64920825-5af98100-d7ee-11e9-99e0-f12c6b5e63ea.png)
请问还需要添加什么，看了以前的好像使用的net，我用的是TreeGraph
![image](https://user-images.githubusercontent.com/43852626/64920837-7b294000-d7ee-11e9-9a75-ad6d5c6bc63d.png)

**Comment by baizn** [comment]
参考这个[Demo](https://antv.alipay.com/zh-cn/g6/3.x/demo/net/interactive-force.html)

**Comment by yuaiqaing** [comment]
![image](https://user-images.githubusercontent.com/43852626/64936698-c93f5180-d889-11e9-8d6c-8ff0d26a2a13.png)
请问如何修改tooltip的位置

**Comment by baizn** [comment]
现在不支持改变tooltip的位置，要自定义位置的话，你可以参考[这个做法](https://antv.alipay.com/zh-cn/g6/3.x/demo/other/contextMenu.html)，拿到节点或鼠标位置，渲染自定义的tooltip组件。
