### ISSUE TITLE
请问如何获取画布的中心坐标？

### ISSUE THREAD

**Issue by mmmmmmmxl** [antvis/g6#846]
* **G6 Version**: 3.0.4
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:
请问如何找到当前画布的中心节点？
想要实现一个保存上次用户最后缩放的功能，在保存的时候使用
var zoom = graph.getZoom() 获取缩放比例
在新打开页面使用
按照我的理解获取画布中心点point
var matrix = graph.get('group').getMatrix();
var point = {
      x: matrix[6],
      y: matrix[7]
 };
graph.zoomTo(zoom, point);
试图恢复到保存前的状态 但是位置不太对，不知是我画布的中心点获取姿势不太对还是我代码的用法不对。。。

**Comment by baizn** [comment]
是获取画布的中心点？
```
var viewCenter = {
    x: width / 2,
    y: height / 2
};
var modelCenter = graph.getPointByCanvas(viewCenter.x, viewCenter.y);
```
width和height表示画布的高度和宽度，需要将Canvas坐标转成视口坐标。
你试下上面的方式可以不呢，不行的话提供一个在线demo。

**Comment by Lipingchang** [comment]
`graph.getPointByCanvas(viewCenter);`
他收的是一个对象。。
不然返回的都是`{x:NaN, y:NaN}`
