### ISSUE TITLE
提个bug，drag-node事件，拖动的时候，框的位置与鼠标的位置有偏差，

### ISSUE THREAD

**Issue by bluce** [antvis/g6#848]
* **G6 Version**:3.0.4
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

将drag-node.js第120行，
shape.attr({ x: x - bbox.width / 2, y: y - bbox.height / 2 });
改成
shape.attr({ x: x, y: y });

**Comment by RicoyWang** [comment]
官网的示例也有这个问题，不知道是有什么考量

**Comment by baizn** [comment]
我试了下没偏差啊，下面这个图是拖动node时的运行效果：
![3](https://user-images.githubusercontent.com/9443867/65853916-9d45c500-e38d-11e9-80e5-d9cdcde5c7c6.gif)

如果改成`shape.attr({ x: x, y: y })`的后效果如下图：
![3](https://user-images.githubusercontent.com/9443867/65853961-c0707480-e38d-11e9-9a72-1a4ecc770e45.gif)

**Comment by bluce** [comment]
> 我试了下没偏差啊，下面这个图是拖动node时的运行效果：
> ![3](https://user-images.githubusercontent.com/9443867/65853916-9d45c500-e38d-11e9-80e5-d9cdcde5c7c6.gif)
> 
> 如果改成`shape.attr({ x: x, y: y })`的后效果如下图：
> ![3](https://user-images.githubusercontent.com/9443867/65853961-c0707480-e38d-11e9-9a72-1a4ecc770e45.gif)

3.0.4版本的

**Comment by baizn** [comment]
3.0.4版本的也没问题啊， https://antv.alipay.com/zh-cn/g6/3.x/demo/other/registerArrow.html  这里你改下看下呢 ，还不行的话建议升级到最新版本（最近会发3.1版本，有些配置项会有改动），都是兼容的。
![image](https://user-images.githubusercontent.com/9443867/65858765-5e1d7100-e399-11e9-9b52-e12a8d50c7ec.png)

**Comment by bluce** [comment]
例子测试没问题，不过在项目中有这个问题，升级暂时还不敢升，本来想改下源码的，我在上层做了处理，暂时修复了，过段时间看下升级版本，感谢答复

**Comment by RicoyWang** [comment]
自定义shape>卡片节点，我在代码上加了drag-node事件就有偏差，正常的rect没偏差，用的`3.0.7-beta.1`

**Comment by RicoyWang** [comment]
> > 我试了下没偏差啊，下面这个图是拖动node时的运行效果：
> > ![3](https://user-images.githubusercontent.com/9443867/65853916-9d45c500-e38d-11e9-80e5-d9cdcde5c7c6.gif)
> > 如果改成`shape.attr({ x: x, y: y })`的后效果如下图：
> > ![3](https://user-images.githubusercontent.com/9443867/65853961-c0707480-e38d-11e9-9a72-1a4ecc770e45.gif)
> 
> 3.0.4版本的

可以关注下 自定义shape 的拖动，节点的宽高不确定，和rect不一样

**Comment by bluce** [comment]
> 自定义shape>卡片节点，我在官网例子上的代码编辑上加了drag-node事件就有偏差，正常的rect没偏差，本地使用的`3.0.7-beta.1`

原来是因为自定义节点的问题，我们在上层重定义的了drag-node事件

**Comment by baizn** [comment]
@RicoyWang  由于demo中的自定义节点没有实现update方法，临时可以通过重定义drag-node来fix这个问题，215-127行代码：
```
this.shape.attr({
    x: x - bbox.width / 2,
    y: y - bbox.height / 2
 });
```
改成
```
this.shape.attr({
    x,
    y
 });
```
具体原因我们后面查一下。

**Comment by baizn** [comment]
3.1.0中已修复。
