### ISSUE TITLE
请问g6最低支持到ie几啊

### ISSUE THREAD

**Issue by 18714984191** [antvis/G6#851]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by baizn** [comment]
现在没有一个全面的测试结果，不能确定IE的兼容程度。
能麻烦提供一个G6在IE下的运行情况不？

**Comment by sunnyShining** [comment]
渐变色不支持，label不支持，还有dom shape不支持

**Comment by yuaiqaing** [comment]
ie11里面，整个treegraph都没了

**Comment by deankwankkk** [comment]
G6 Version: ~3.3.6
Platform: win10 IE11
react项目进行打包测试环境运行，报语法错误，报错行数属于G6模块编译后的代码

**Comment by JyotsnaC** [comment]
Do we know the cross browser support ?

**Comment by richardchen85** [comment]
依赖的 d3-force 中 link 函数有一个箭头函数，导致IE下全灭

**Comment by richardchen85** [comment]
刚看了 d3-force 上的 issue，d3-force@2 已经不支持IE了，要想兼容IE得回到 d3-force@1

**Comment by Yanyan-Wang** [comment]
不再考虑兼容 IE ，因为 IE 已经下架啦
