### ISSUE TITLE
使用SVG模式渲染HTML，foreignObject不支持IE11及以下版本，请问有兼容方案吗

### ISSUE THREAD

**Issue by Linkontoask** [antvis/g6#852]
* **G6 Version**: all
* **Platform**: IE11
* **Mini Showcase(like screenshots)**: 
* **CodePen Link**:
[foreignObject](https://developer.mozilla.org/zh-CN/docs/Web/SVG/Element/foreignObject)

**Comment by baizn** [comment]
3.x 不支持 HTML 节点，不建议使用 svg 渲染，后续只会支持canvas渲染。
