### ISSUE TITLE
【bug】设置getHGap和getVGap为固定值，若节点的展示值长度过长，导致相互遮挡

### ISSUE THREAD

**Issue by yongshangmoli** [antvis/g6#853]
* **G6 Version: 3.0.8-beta.1:
* **Platform: all
* **Mini Showcase: 
![image](https://user-images.githubusercontent.com/10692981/65862580-1f8bb480-e3a1-11e9-852f-986939c8da8a.png)

* **Link: https://antv.alipay.com/zh-cn/g6/3.x/demo/tree/custom-tree.html

直接将官网示例中的参数改为如下，就出现了遮挡
![image](https://user-images.githubusercontent.com/10692981/65862614-35997500-e3a1-11e9-8f13-b15e728a2c61.png)

期待效果：不遮挡，正常展示
![image](https://user-images.githubusercontent.com/10692981/65862917-c4a68d00-e3a1-11e9-9879-b7fa5ef34e30.png)

**Comment by Yanyan-Wang** [comment]
这个不算 bug，您可以通过合理的布局配置实现您想要的效果。

您可以尝试对不同的节点返回不同的数值。
      getWidth: function getWidth(d) {
        return d.name.length * 10;
      }

同样的，getHeight、getVGap、getHGap 这些函数都可以根据节点的某些属性进行设置。

**Comment by yongshangmoli** [comment]
> 这个不算 bug，您可以通过合理的布局配置实现您想要的效果。
> 
> 您可以尝试对不同的节点返回不同的数值。
> getWidth: function getWidth(d) {
> return d.name.length * 10;
> }
> 
> 同样的，getHeight、getVGap、getHGap 这些函数都可以根据节点的某些属性进行设置。

我尝试了仍然失败。
所以能否就这个示例而言，给出不遮挡的设置代码

**Comment by mage3k** [comment]
+1
在 getVGap 中根据 node 的属性进行设置并没有生效

**Comment by Yanyan-Wang** [comment]
> > 这个不算 bug，您可以通过合理的布局配置实现您想要的效果。
> > 您可以尝试对不同的节点返回不同的数值。
> > getWidth: function getWidth(d) {
> > return d.name.length * 10;
> > }
> > 同样的，getHeight、getVGap、getHGap 这些函数都可以根据节点的某些属性进行设置。
> 
> 我尝试了仍然失败。
> 所以能否就这个示例而言，给出不遮挡的设置代码

有效果的呀，你尝试改改这个 demo 里面的 getWidth 的返回值：
https://g6.antv.vision/zh/examples/tree/customItemTree#customTree

**Comment by Yanyan-Wang** [comment]
> +1
> 在 getVGap 中根据 node 的属性进行设置并没有生效


有效果的呀，你尝试改改这个 demo 里面的 getVGap 的返回值：
https://g6.antv.vision/zh/examples/tree/customItemTree#customTree

**Comment by mage3k** [comment]
> > +1
> > 在 getVGap 中根据 node 的属性进行设置并没有生效
> 
> 有效果的呀，你尝试改改这个 demo 里面的 getVGap 的返回值：
> https://g6.antv.vision/zh/examples/tree/customItemTree#customTree

不清楚是不是新版修复了这个问题，demo 中是可以的
另外，终于有个像样的文档了 👍

**Comment by lhyzxc** [comment]
> 这个不算 bug，您可以通过合理的布局配置实现您想要的效果。
> 
> 您可以尝试对不同的节点返回不同的数值。
> getWidth: function getWidth(d) {
> return d.name.length * 10;
> }
> 
> 同样的，getHeight、getVGap、getHGap 这些函数都可以根据节点的某些属性进行设置。

试了下3.4.4中 根据node中的属性来判断getVGap、getHGap 的返回值不起作用

**Comment by Yanyan-Wang** [comment]
![image](https://user-images.githubusercontent.com/29593318/78623386-19c7dc00-78ba-11ea-856f-788fec341fd8.png)

有效果呀

**Comment by lhyzxc** [comment]
> ![image](https://user-images.githubusercontent.com/29593318/78623386-19c7dc00-78ba-11ea-856f-788fec341fd8.png)
> 
> 有效果呀

![image](https://user-images.githubusercontent.com/20706166/78624110-65c75080-78bb-11ea-89bc-34d4b01fa7ad.png)
我这里节点样式做了修改 ‘更多‘节点的线重叠了 但是我根据id来改这个节点HGap确实不起作用
