### ISSUE TITLE
G6.registerLayout报错，如何升级到3.1.0版本？

### ISSUE THREAD

**Issue by mabelyong** [antvis/g6#856]
使用npm目前只能装3.0.7-beta.1，此版本G6.registerLayout这个方法报错，目前克隆项目打包后的版本是3.1.0，能正常使用该方法

希望能使用npm能直接安装到3.1.0版本

**Comment by baizn** [comment]
3.1 的包还没正式发布，先把文档更新了一下，节后第一时间发布3.1包，十分抱歉。
向国庆期间还在加班的同学致敬！

**Comment by baizn** [comment]
3.1.0版本已发布，直接更新即可。

**Comment by richard1225** [comment]
> 3.1.0版本已发布，直接更新即可。

请问3.1如何升级?

**Comment by baizn** [comment]
> > 3.1.0版本已发布，直接更新即可。
> 
> 请问3.1如何升级?

升级npm包 这个问题有点过分了……

**Comment by richard1225** [comment]
> > > 3.1.0版本已发布，直接更新即可。
> > 
> > 
> > 请问3.1如何升级?
> 
> 升级npm包 这个问题有点过分了……
我直接用npm更新最高只能到3.0.1

**Comment by baizn** [comment]
你看下 是不是 你的 `package.json` 中锁定了版本
