### ISSUE TITLE
【bug】动态修改树状图文字内容后，内容遮挡anchor设置失效

### ISSUE THREAD

**Issue by yongshangmoli** [antvis/G6#858]
* **G6 Version**: 3.0.5-beta.12
* **Platform**: chrome
* **Mini Showcase(like screenshots)**: 
![image](https://user-images.githubusercontent.com/10692981/66371817-05705880-e9d7-11e9-9e92-d7ebef5a0475.png)
![image](https://user-images.githubusercontent.com/10692981/66371828-115c1a80-e9d7-11e9-97b2-b7c9008e76e1.png)
![image](https://user-images.githubusercontent.com/10692981/66372096-c098f180-e9d7-11e9-8ec5-e3205c88130f.png)

* **CodePen Link**:  https://codepen.io/yongshangmoli/pen/zYYxaKp

新建了一颗紧凑树，在点击某个节点时，支持节点展开与收缩，同时更新节点的内容
当新的节点内容长度小于原节点内容长度时，展示正常，且点击节点能正常收缩
而当新的节点内容长度大于原节点内容长度时，原图如图一，点击第二层第一个节点，节点收缩后出现了遮挡（如图二），再次点击选中节点，节点的锚点被定位到了最开始（如图三）

期待效果，正常展示

**Comment by Yanyan-Wang** [comment]
- 被遮挡是由于布局配置里面设置了 getHeight getWidth 是固定值，布局的时候就默认每一个节点的宽高是固定的。需要动态根据节点大小给 getHeight  getWidth 返回合理的值。

-  边设置一下 sourceAnchor 和 targetAnchor 即可解决连接位置错误的问题：
```javascript
      this.myTree.edge(() => {
         return {
           shape: 'cubic-horizontal',
           sourceAnchor: 1,
           targetAnchor: 0,
         }
      })
```
在 render 之前调用

**Comment by luokerenGIT** [comment]
> ```js
> myTree
> ```

如果想在树图中动态设置sourceAnchor，targetAnchor要怎么处理
