### ISSUE TITLE
请教如何给树图增加额外的边？

### ISSUE THREAD

**Issue by yyz841875845** [antvis/g6#860]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by yyz841875845** [comment]
![image](https://user-images.githubusercontent.com/44571912/66534199-0d9bd580-eb48-11e9-81b5-1d5d48d82f3f.png)
 类似这样的

**Comment by baizn** [comment]
这种已经不属于树图了，使用一般图就可以，布局G6都内置好了的，具体参考[这里](https://www.yuque.com/antv/g6/agbmu2)。

**Comment by yyz841875845** [comment]
> 这种已经不属于树图了，使用一般图就可以，布局G6都内置好了的，具体参考[这里](https://www.yuque.com/antv/g6/agbmu2)。

谢谢，那我只能用degre布局了
