### ISSUE TITLE
请教如何给节点设置通过点击锚点用边连接其他节点？

### ISSUE THREAD

**Issue by bt-1120161955** [antvis/g6#862]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by bt-1120161955** [comment]
初学g6，在官方文档中完全找不到关于通过点击来动态的用边连接两个节点的相关内容

**Comment by bt-1120161955** [comment]
就像是通过鼠标左键点击锚点然后生成一条线段跟随鼠标拖动到另外一个节点的锚点，形成两个节点之间的边

**Comment by baizn** [comment]
这个不是 吗？ https://www.yuque.com/antv/g6/interaction

**Comment by bt-1120161955** [comment]
> 这个不是 吗？ https://www.yuque.com/antv/g6/interaction

哦哦，非常感谢🙏，之前没在这部分中找
