### ISSUE TITLE
是否支持右键选中复制节点和边的文本内容

### ISSUE THREAD

**Issue by dd1994** [antvis/g6#864]
![Screen Shot 2019-10-12 at 15 40 23](https://user-images.githubusercontent.com/4121510/66697283-b7c15c00-ed06-11e9-88c3-8fa706b1b2dd.png)

就是跟浏览器其它文本内容一样选中复制。比如上图中的节点 label，如果不支持复制的话手动输入太难了。。

**Comment by baizn** [comment]
这个功能不适合做到 G6 里面，右键点击你拿到文本内容后，调用复制内容的接口即可，具体可参考这里：https://juejin.im/post/5a94f8eff265da4e9b593c29
