### ISSUE TITLE
TreeGraph layout, indeted does't work

### ISSUE THREAD

**Issue by seekhow** [antvis/g6#866]
* **G6 Version**: 3.1.1
* **Platform**: MacOS Chrome77
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/31029342/66735473-06066480-ee99-11e9-89ab-efa865d3d8c2.png)
dendrogram/compactBox works normally
* **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
Do you mean 'indented' ? Try type='indented' instead of 'indeted'.
Demo: https://antv.alipay.com/zh-cn/g6/3.x/demo/tree/tree-indented.html
