### ISSUE TITLE
Uncaught Error: only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by wangwenbin023** [antvis/g6#870]
baizn <576375879@qq.com>
你给我出来
你导入babel-polyfill我们使用的时候还怎么导入babel-polyfill
Uncaught Error: only one instance of babel-polyfill is allowed

**Comment by hustcc** [comment]
底层依赖，不要引入 polyfill 这些代码，都在业务层去做。demo 要兼容浏览器，就在 demo 代码中去引入。

不然上层业务没法玩。

**Comment by baizn** [comment]
抱歉，已移除，麻烦更新下版本！
