### ISSUE TITLE
g6所画的图是否可以相对于画布居中呢

### ISSUE THREAD

**Issue by purpletastes** [antvis/G6#873]
g6所画的图是否可以相对于画布居中呢

**Comment by baizn** [comment]
可以，第一种方式使用 graph.fitView()，另一种使用布局时，把中心点设置到画布中心。

**Comment by CherishDing** [comment]
> 可以，第一种方式使用 graph.fitView()，另一种使用布局时，把中心点设置到画布中心。

使用graph.fitView()时，能让节点不自动适应画布，只将canvas居中吗？我使用的dagre布局，但设置center没有用，使用tanslate或者moveto,canvas都不是相对于画布居中

**Comment by Yanyan-Wang** [comment]
一个比较直接简单的方法，在 render 之后或监听 afterlayout ，遍历节点，计算所有节点的平均中心 [sum(节点的x) /节点个数，sum(节点的y) /节点个数]，然后计算该平均中心到画布中心的差距 [dx, dy]，将 [dx, dy] 加到所有节点位置上，最后重绘一下图。

**Comment by mmfjx** [comment]
可以设置maxZoom为1，fitView就不会放大，只是居中，fitView的缩放比例受限于最大最小缩放比例，不过后面要缩放的时候，需要重新设置下最大最小缩放比例，之前也遇到这个问题，不想fitView的时候放大图形，希望能帮到大家：）

**Comment by leecj** [comment]
刚刚解决这个问题，参照官方的fitView代码，重写一下就好了
```javascript
      const width = graph.get("width");
      const height = graph.get("height");
      const group = graph.get("group");
      group.resetMatrix();
      const bbox = group.getCanvasBBox();

      if (bbox.width === 0 || bbox.height === 0) return;
      const viewCenter = {
        x: width / 2,
        y: height / 2,
      };

      const groupCenter = {
        x: bbox.x + bbox.width / 2,
        y: bbox.y + bbox.height / 2,
      };
      graph.translate(viewCenter.x - groupCenter.x, viewCenter.y - groupCenter.y);
      // ...省略了 zoom代码

```
