### ISSUE TITLE
在stateStyles中如何写 labelCfg？现在写的只对node生效，label的颜色想改变一下

### ISSUE THREAD

**Issue by yyz841875845** [antvis/g6#875]
* **G6 Version**: 3.1.0
* **Platform**:
* **Mini Showcase(like screenshots)**:  stateStyles: {
     
      active: {
        fillOpacity: 0.8
      },
     
      inactive: {
        lineWidth: 3
      }
    }
* **CodePen Link**:

**Comment by baizn** [comment]
stateStyles 中的样式只针对 keyShape的 状态起作用，要修改其他元素的样式 通过 `graph.updateItem` 或 拿到label元素后 `label.attr()`方式实现。

**Comment by yyz841875845** [comment]
> stateStyles 中的样式只针对 keyShape的 状态起作用，要修改其他元素的样式 通过 `graph.updateItem` 或 拿到label元素后 `label.attr()`方式实现。

解决了，谢谢

**Comment by Yiliayouyou** [comment]
请问之后是否可以考虑通过stateStyles改变labelCfg

**Comment by JohnnyLuv** [comment]
请问之后是否可以考虑通过stateStyles改变labelCfg

**Comment by mooction** [comment]
已经解决，参见 #3052
