### ISSUE TITLE
使用downloadImage下载图片，文件过大时谷歌浏览器提示网络错误

### ISSUE THREAD

**Issue by lulei90** [antvis/g6#876]
v3.1.1
使用downloadImage下载图片，文件过大时谷歌浏览器提示网络错误

**Comment by baizn** [comment]
多大的文件呢？ 确定不是网络问题的话 提供 个 在线 demo，我们排查一下。

**Comment by lulei90** [comment]
> 多大的文件呢？ 确定不是网络问题的话 提供 个 在线 demo，我们排查一下。
已解决，转成blob后在用URL.createObjectURL能正常下载 大小在3.4M左右
建议优化下downloadImage

**Comment by lulei90** [comment]
@baizn  看了下源码 对canvas渲染的是有做转blob处理  我这采用的svg渲染

**Comment by FrankBGao** [comment]
能给一个关于downloadImage例子吗？不会用呀

**Comment by baizn** [comment]
@FrankBGao  `graph.downloadImage(filename)`
