### ISSUE TITLE
TreeGraph的布局layout的配置 fixedRoot 无效

### ISSUE THREAD

**Issue by DaaMeiling** [antvis/G6#879]
let graph = new G6.TreeGraph({
          container: 'vitrual_tree',
          height,
          width,
          fitView:'autoZoom',
          modes: {
            default: [{
              type: 'collapse-expand',
              onChange: function onChange(item, collapsed) {
                var data = item.get('model');
                var icon = item.get('group').findByClassName('collapse-icon');
                if (collapsed) {
                  icon.attr('symbol', EXPAND_ICON);
                } else {
                  icon.attr('symbol', COLLAPSE_ICON);
                }
                data.collapsed = collapsed;
                return true;
              }
          },'behavior-name']

          },
          defaultNode: {
            size: 16,
            anchorPoints: [[0, 0.5], [1, 0.5]],
            style: {
              fill: '#C0DC4F',
              stroke: 'rgba(186, 222, 37, 0.5)',
              strokeWidth: 3
            }
          },
          defaultEdge: {
            shape: 'cubic-horizontal',
            style: {
              stroke: '#A3B1BF'
            }
          },
          layout: {
            type: 'compactBox',
            direction: 'LR',
            fixedRoot: true,
            getId: function getId(d) {
              return d.id;
            },
            getHeight: function getHeight() {
              return 16;
            },
            getWidth: function getWidth() {
              return 16;
            },
            getVGap: function getVGap() {
              return 20;
            },
            getHGap: function getHGap() {
              return 35;
            }
          }
        });
![image](https://user-images.githubusercontent.com/43836282/67181294-c7c7f280-f40e-11e9-854d-4e9df6c14bde.png)

官方demo树图加入配置，root节点还是收缩至图层左上角

**Comment by DaaMeiling** [comment]
G6 Version: 3.1.3

**Comment by baizn** [comment]
你本地是什么效果呢？ 我们排查一下，同样的代码 在本地和官网上表现不一样。

**Comment by persuitHappy** [comment]
一棵向右延伸的树，给根节点添加子节点，根节点会向下移动，预期想让子节点以根节点为中心扩展开，fixedRoot不生效，求助

**Comment by AILINGANGEL** [comment]
升级到最新版依然没看到生效，但是为什么官网给的例子看起来是生效的？

**Comment by Yanyan-Wang** [comment]
v3.4.2 已发布，已修复。
