### ISSUE TITLE
minimap 自定义节点中的图片预加载之后，画完图之后还显示不出来，需要点击一下画布，图就出来了

### ISSUE THREAD

**Issue by CherishDing** [antvis/g6#882]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by baizn** [comment]
自定义节点后需要调用一下 graph.paint()

**Comment by CherishDing** [comment]
> 自定义节点后需要调用一下 graph.paint()

使用了graph.paint()，还是不起作用
