### ISSUE TITLE
vue部署后报Cannot read property 'getPoint' of null

### ISSUE THREAD

**Issue by qm8956** [antvis/g6#883]
本地开发正常，打包部署后出现一下错误：
g6.js:9 Uncaught (in promise) TypeError: Cannot read property 'getPoint' of null
    at Object.getLabelPosition (g6.js:9)
    at Object.getLabelStyleByPosition (g6.js:9)
    at Object.getLabelStyle (g6.js:9)
    at Object.drawLabel (g6.js:9)
    at Object.update (g6.js:9)
    at Object.update (g6.js:1)
    at e.updateShape (g6.js:9)
    at e.refresh (g6.js:9)
    at g6.js:9
    at Object.t.exports [as each] (g6.js:1)
我换了3.0.0， 3.0.5， 3.1.3都是同样问题，3.1.3本地开发也出同样问题
当前我无法确定问题所在，希望可以得到帮助，谢谢
补充：
鼠标点击画布移动一下就出来了，貌似只有再特定环境下才会出来，我本地调试好的，本地部署也是好的，部署到服务器上就回出现这种问题，本地是window,服务器为linux
再补充一下：
// 不对 pathShape 进行判空，如果线不存在，说明有问题了
 const pathShape = group.findByClassName(CLS_SHAPE);
现在确实pathShape为null，但源码这么写，说明有啥问题了，能指导一下吗

**Comment by baizn** [comment]
className的参数存在不？ 能提供个在线的demo吗？

**Comment by qm8956** [comment]
@baizn 无法提供在线demo，我也无法确定在线demo是否会复现同样的问题，根据我自己调试，我本地开发，在我本地打包部署也是好的，就是部署到服务器上时才会出如此问题。当前问题已经解决，我将版本切换到3.1.3，切到3.1.3后本地开发就现同样的问题，根据最新的文档，我发现有一个概念也许我理解错了
`/**
 * 自定义简单折线
 */
G6.registerEdge('simple-line', {
  draw: function draw(cfg, group) {
    const { startPoint, endPoint, sourceAnchor, targetAnchor, label } = cfg;
    const points = [['M', startPoint.x, startPoint.y], ['L', endPoint.x, endPoint.y]];
    if (sourceAnchor % 2 !== targetAnchor % 2) {
      let middle = ['L', startPoint.x, endPoint.y];
      if (sourceAnchor % 2) {
        middle = ['L', endPoint.x, startPoint.y];
      }
      points.splice(1, 0, middle);
    }
    const shape = group.addShape('path', {
      attrs: {
        path: points,
        stroke: '#ccc',
        lineWidth: 3,
        endArrow: {
          path: 'M 6,0 L -6,-6 L -6,6 Z',
          d: 6,
        },
      },
    });
    let x = startPoint.x - (label.length / 2) * fontBaseSize;
    let y = startPoint.y - 25;
    switch (sourceAnchor) {
      case 1:
        x = startPoint.x + 25;
        y = startPoint.y + (fontBaseSize / 2 - 2);
        break;
      case 2:
        y = startPoint.y + 25;
        break;
      case 3:
        x = startPoint.x - label.length * 12 - 25;
        y = startPoint.y + (fontBaseSize / 2 - 2);
        break;
    }
    group.addShape('rect', {
      attrs: {
        x: x - 8,
        y: y - 14,
        width: label.length * fontBaseSize + 16,
        height: fontBaseSize + 8,
        fill: '#FFF',
        stroke: '#d2d2d2',
      },
    });
    group.addShape('text', {
      attrs: {
        text: label,
        fill: '#999',
        textAlign: 'start',
        textBaseline: 'center',
        x,
        y,
      },
    });
    return shape;
  },
}, 'line');`
我觉得这个也许不是扩展先有的边，而是自定义边。所以我就将最后‘line’删掉了，之后重启电脑(这个是次要，因为我电脑太卡了)以后发现问题不出现了，我当前也不能确定问题真正在出在什么地方

**Comment by woleicom** [comment]
我也碰到了这个问题，不扩展现有边居然就好了

**Comment by woleicom** [comment]
@baizn @baizn 我找到了问题的所在，是因为文件`lib/util/graphic.js`里调用的getPoint()
```
exports.getLoopCfgs = getLoopCfgs;

var getLabelPosition = function getLabelPosition(pathShape, percent, refX, refY, rotate) {
  var TAN_OFFSET = 0.0001;
  var vector = [];
  var point = pathShape.getPoint(percent);
```
以及文件`lib/shape/edge.js`里获取的pathState为空
```
getLabelStyleByPosition: function getLabelStyleByPosition(cfg, labelCfg, group) {
    var labelPosition = labelCfg.position || this.labelPosition; // 文本的位置用户可以传入

    var style = {};
    var pathShape = group && group.find(function (element) {
      return element.get('className') === CLS_SHAPE;
    }); // 不对 pathShape 进行判空，如果线不存在，说明有问题了

```
因为代码默认取shape的className属性，而新版本的文档是用的name属性作为key，导致pathShape根本获取不到为空，并且没有判断pathShape对象是否存在，null调用getPoint函数导致报错

临时解决办法：自定义edge的draw函数里的图形可以同时添加name和className属性，即可解决
