### ISSUE TITLE
setItemState未定义

### ISSUE THREAD

**Issue by yuaiqaing** [antvis/g6#884]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:
![image](https://user-images.githubusercontent.com/43852626/67484952-b0516980-f69b-11e9-9a2e-95a39608028b.png)
![image](https://user-images.githubusercontent.com/43852626/67484985-c2330c80-f69b-11e9-9620-656243e3e480.png)
原来的插件版本是3.0.4，删除了重新下载了个3.1.3版本的，但是现实setItemState未定义，
![image](https://user-images.githubusercontent.com/43852626/67485105-fe666d00-f69b-11e9-9825-645d75d498a8.png)
![image](https://user-images.githubusercontent.com/43852626/67485173-1ccc6880-f69c-11e9-9c85-d5cd5cf459ad.png)

这是配置节点样式的配置和导入，请问还要再添加其他东西了吗

**Comment by baizn** [comment]
![image](https://user-images.githubusercontent.com/9443867/67486969-9fa2f280-f69f-11e9-9d43-b7a5b429c164.png)
这里的self都不对了，定义到最外面。
