### ISSUE TITLE
节点不支持gif动图

### ISSUE THREAD

**Issue by Carlos0204** [antvis/g6#888]
最近项目有个需求，用gif来表示节点，但是目前渲染出来的是静态图片，怎么来解决这个问题呢？

**Comment by baizn** [comment]
目前不支持设置gif，你看下能否通过 动画 来实现呢 https://www.yuque.com/antv/g6/base-animate#lZ9tM

**Comment by junmer** [comment]
```
new G6.Graph({
  renderer: "svg",
  ...
})
```
