### ISSUE TITLE
numericjs not found

### ISSUE THREAD

**Issue by Robinbiao** [antvis/G6#889]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

安装最新版 3.1.3， /node_modules/@antv/g6/src/layout/mds.js  里面引用numericjs了，package.json 里面没此包，导致Can't resolve 'numericjs' 错误

**Comment by baizn** [comment]
有的吧，三个月就加进去的 。
![image](https://user-images.githubusercontent.com/9443867/67754562-a2bc2b00-fa71-11e9-9ec9-6fde7ff10f52.png)

**Comment by Robinbiao** [comment]
确实在node_modules/numeric 下，包存在 ，但编绎时
![image](https://user-images.githubusercontent.com/18207227/67756781-98039500-fa75-11e9-91de-cc0e8fa4aea2.png)，报错找不到包(yarn安装)

**Comment by baizn** [comment]
更新到 3.2.3 应该就没这个问题了。
