### ISSUE TITLE
在dagre布局里，当某一个节点过大时，如何控制节点不重叠，或者如何控制两个节点之间的距离

### ISSUE THREAD

**Issue by CherishDing** [antvis/g6#894]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
G6 当前版本（3.1.3）中的 dagre 只能支持数值型 nodesep （节点间距）和 ranksep （层间距）的设置，以及数组型的 nodeSize（节点大小）的设置。这些变量对于所有节点都是统一的。请见教程：https://www.yuque.com/antv/g6/fkhp3c

在下个版本中，将会提供 nodesep 和 ranksep 的回调函数形式，可以根据节点的信息设置不同的节点间距和层间距。还将会根据数据中节点 size 属性动态调整布局，可以保证没有节点重叠。

**Comment by Yanyan-Wang** [comment]
G6 3.1.6 版本已发布，支持 nodesepFunc ranksepFunc 两个参数可以设置不同节点的节点间距和层间距。
