### ISSUE TITLE
在vue2.0cli中 build的时候 报错

### ISSUE THREAD

**Issue by jjshe** [antvis/G6#895]
* **G6 Version**: 3.1.*
* **Platform**: vuecli 
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

[1m[31mERROR in static/js/vendor.872a64db059f500a48a2.js from UglifyJs
Invalid assignment [./node_modules/@antv/g6/build/g6.js:9,251657][static/js/vendor.872a64db059f500a48a2.js:155810,251708][39m[22m

  Build failed with errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! creditservices@1.0.0 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR!

**Comment by curiosity-hyf** [comment]
same error

**Comment by JeroenWang** [comment]
me too!!!

**Comment by simon-yxl** [comment]
me too!!

**Comment by hstarorg** [comment]
Duplicate of #960

**Comment by hstarorg** [comment]
大家能否提供下可复现的demo（或者build配置）呢，采用vuecli搭建项目进行了确认，可以正常  build。

**Comment by baizn** [comment]
这个先关了 ，和 #960 是同样问题。
