### ISSUE TITLE
请问下发布了新版本，然而新版本对应的js又不上线，是怎么回事呢，js路径打开是404的

### ISSUE THREAD

**Issue by qikong333** [antvis/g6#899]
@

* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by baizn** [comment]
“发布了新版本，然而新版本对应的js又不上线” 指什么？  哪里是 404 ？

**Comment by qikong333** [comment]
3.1.4
feat: supports g6 types file
fix: set brush-select trigger param to ctrl not work
fix: when set fitView to true, drag-group Behavior not get desired positon

https://gw.alipayobjects.com/os/antv/pkg/_antv.g6-3.1.4/build/g6.js
3.1.4对应的js打开是404的，不是这个地址吗

**Comment by baizn** [comment]
用这个，最新是 https://gw.alipayobjects.com/os/antv/pkg/_antv.g6-3.1.5/build/g6.js
