### ISSUE TITLE
不支持在分组 中 使用 dagre、force等内置布局

### ISSUE THREAD

**Issue by susanyyy** [antvis/G6#901]
G6.Graph({
            container: 'mount-node',
                width: 800,
                height: 600,
                fitViewPadding: 20,
                fitView: true,
                groupType: 'rect',
                modes: {
                    default: ['drag-group', 'drag-node-with-group', 'collapse-expand-group']
                },
              layout: { // Object，可选，布局的方法及其配置项，默认为 random 布局。
                    type: 'dagre',
                    preventOverlap: true,
                    rankdir: 'LR',
                    nodesep: 40,
                    ranksep: 100,
                    align: 'UR'
                },   
  });

// 数据不方便透露引用官方文档数据

var data = {
    nodes: [{
      id: 'node6',
      groupId: 'group3',
      label: 'node6-group3'
  }, {
      id: 'node1',
      label: 'node1-group1',
      groupId: 'group1'
  }, {
      id: 'node2',
      label: 'node2-group2',
      groupId: 'p2'
  }, {
      id: 'node3',
      label: 'node3-group2',
      groupId: 'group2',
  }],
    edges: [{
      source: 'node1',
      target: 'node2'
  }, {
      source: 'node2',
      target: 'node3'
  }, {
      source: 'node1',
      target: 'node3'
  }, {
      source: 'node6',
      target: 'node1'
  }],
    groups: [{
      id: 'group3',
      title: '2',
      parentId: 'p2'
  }, {
      id: 'p2',
      title: '3'
  }]
  };

  graph.data(data);
  graph.render();

**Comment by Yanyan-Wang** [comment]
目前暂时还不支持呢。

**Comment by VajraFate** [comment]
请问groups有支持的内置布局吗？ 或者内置方法做到node随机分布且node之间， groups之间不重叠？

**Comment by baizn** [comment]
3.2.3 版本可以对group中的节点使用 dagre、force 等布局。

> 请问groups有支持的内置布局吗？ 或者内置方法做到node随机分布且node之间， groups之间不重叠？

暂时没有。

**Comment by Yanyan-Wang** [comment]
带有全新节点分组 Combo 机制的 v3.5 发布了。demos：
内置 combos: https://g6.antv.vision/zh/examples/item/defaultCombos
自定义 combos: https://g6.antv.vision/zh/examples/item/customCombo
Combo 的布局: https://g6.antv.vision/zh/examples/net/comboForce
Combo 的交互: https://g6.antv.vision/zh/examples/interaction/combo

文档可以通过 [G6 官网](https://g6.antv.vision/zh) 上方的搜索栏搜索“combo”查看。
