### ISSUE TITLE
拖动似乎有bug？

### ISSUE THREAD

**Issue by chaserstrong** [antvis/G6#903]
任意一个[demo地址](https://antv.alipay.com/zh-cn/g6/3.x/demo/tree/tree-mindmap.html)。

复现：
在树图中单击左键拖拽，拖到树图渲染的容器div的外侧，抬起左键。 再移入到容器div内。 图仍旧会随着鼠标移动。（用的触控板，会有影响？）

预期结果：
正常应该结束这个拖拽事件呀。

设备：mac 10.13.4
浏览器：chrome最新版本

**Comment by gaodun2018** [comment]
的确。而且参考线对齐其实也是不准的

**Comment by RanQiwu** [comment]
不灵敏，鼠标在移动的过程中去点击某个元素，是点击不上的，所以给人的感觉性能不好，一卡一卡的。
策略有些问题。

**Comment by chaserstrong** [comment]
> 不灵敏，鼠标在移动的过程中去点击某个元素，是点击不上的，所以给人的感觉性能不好，一卡一卡的。
> 策略有些问题。

啥意思，你是在节点上触发移动事件吧？

**Comment by baizn** [comment]
G 3.x 事件的问题，接下来我们会升级到 G 4.0，这个问题就会解决的。

**Comment by Yanyan-Wang** [comment]
2.17 发布的 G6 3.3 已解决该问题。3.11 已发布 G6 3.4.

**Comment by ShawLyon** [comment]
> 2.17 发布的 G6 3.3 已解决该问题。3.11 已发布 G6 3.4.

我的版本是3.4.3，还是有这个bug
