### ISSUE TITLE
是否有办法一个图中画多个树图？

### ISSUE THREAD

**Issue by chaserstrong** [antvis/g6#904]
正常树图一般都只有一个根节点。
现在需求上需要在一个图中展示多个根节点，各个根节点都有自己的一棵树。 
本来以为可以通过自定义layout复制多个树图展示就行了，但是看了下自定义layout的文档，似乎是需要完全自己自定义各个节点/边的位置。
所以，能提供一些思路吗？

**Comment by chaserstrong** [comment]
@baizn help~~~

**Comment by baizn** [comment]
现在不支持这种

**Comment by Yanyan-Wang** [comment]
如果你用的是 Graph ，是没关系的，会当作不联通的图进行布局。如果你用的是 TreeGraph ，只能处理一棵树，如果需要用 TreeGraph 绘制多棵树，可以实例化多个 TreeGraph。

**Comment by chaserstrong** [comment]
> 如果你用的是 Graph ，是没关系的，会当作不联通的图进行布局。如果你用的是 TreeGraph ，只能处理一棵树，如果需要用 TreeGraph 绘制多棵树，可以实例化多个 TreeGraph。

我最后用了一个取巧的办法，在多颗树上，再加一个父节点。 当做一个树来渲染，然后再隐藏这个父节点。

**Comment by areyouse7en** [comment]
> 如果你用的是 Graph ，是没关系的，会当作不联通的图进行布局。如果你用的是 TreeGraph ，只能处理一棵树，如果需要用 TreeGraph 绘制多棵树，可以实例化多个 TreeGraph。

怎么实例化多个TreeGraph？

**Comment by eyea** [comment]
> > 如果你用的是 Graph ，是没关系的，会当作不联通的图进行布局。如果你用的是 TreeGraph ，只能处理一棵树，如果需要用 TreeGraph 绘制多棵树，可以实例化多个 TreeGraph。
> 
> 我最后用了一个取巧的办法，在多颗树上，再加一个父节点。 当做一个树来渲染，然后再隐藏这个父节点。

请问下这个对应的隐藏父节点和子节点之间的曲线是怎么隐藏的呢？

**Comment by 19990101wb** [comment]
@chaserstrong  您好 请问一下父节点怎么隐藏呢

**Comment by 19990101wb** [comment]
@chaserstrong  help help

**Comment by lmh-code** [comment]
@19990101wb 隐藏父节点参考元素操作的删除元素
https://g6.antv.antgroup.com/api/graph-func/item
