### ISSUE TITLE
针对可以Collapse的树图，是否可以提供一个设置默认显示层数的配置项？

### ISSUE THREAD

**Issue by liuqiao1** [antvis/g6#91]
##我的问题：
       可以Collapse的树图，目前的情况是：渲染完毕即显示所有的节点，但是当节点很多的时候，这样做会导致节点密集，看不清楚。

##我的期望：
    我希望有一个设置默认扩展层级的配置项，比如
`Graph.tree({
defaultExpand: 2
})`
    样当用户初次打开图，不管根节点有多少子子孙孙，都只显示到根节点的孙子那一层。
如果用户需要看更晚的晚辈，再通过Collapse实现。

**Comment by TomHuangCN** [comment]
原数据里有 `isCollapsed ` 字段可以配置节点的展开折叠

https://antv.alipay.com/zh-cn/g6/1.x/api/tree.html#_source

**Comment by meisuTJU** [comment]
想请教下楼主，G6里面Tree首次加载默认不展开所有节点解决了吗？

**Comment by yisish** [comment]
有木有解决哦

**Comment by weijiegao** [comment]
> 想请教下楼主，G6里面Tree首次加载默认不展开所有节点解决了吗？

data中跟id同级写上collapsed:true，可以控制当前id分支处于折叠状态
