### ISSUE TITLE
手动添加多个连线的控制点，如何判断控制点的顺序？

### ISSUE THREAD

**Issue by Aragornzero** [antvis/G6#916]
现在我有一个需求，就是双击线段，就在双击的位置添加一个控制点，控制点的渲染是按照数组的顺序来的。那么，我在双击线段往数组中插入控制点时，如何判断应该插入到数组那个位置呢？

仅仅按顺序插入，比如我新加入的控制点，但是它更接近source的话，线段就会变得很奇怪了。

**Comment by baizn** [comment]
添加到数组的最后面就可以，同步更新 edge 中的 sourceAnchor 和 TargetAnchor 就可以了。

**Comment by Aragornzero** [comment]
> 添加到数组的最后面就可以，同步更新 edge 中的 sourceAnchor 和 TargetAnchor 就可以了。

问题是. 我新添加的一个控制点在数组排序上(不是x,y的坐标值)更靠近sourceAnchor呢? 如果都添加在数组最后,那么那控制点会更靠近TargetAnchor. 

添加控制点时我只有x,y坐标值,我不知道如何判断它在数组上的排序...是更高进souorceAnchor还是targetAnchor

**Comment by Yanyan-Wang** [comment]
你说的控制点是 polyline 的控制点吗？描述看得不是很明白，最好有图，或在线 demo

**Comment by Yanyan-Wang** [comment]
尊敬的用户，您好。我们很重视您的 issue，但由于长时间没有答复，我们暂时认为这个问题已经解决。如果还有任何问题，请随时根据 issue 模版再开启新的 issue。
