### ISSUE TITLE
bug 树状图节点伸展动画后缩到一起了

### ISSUE THREAD

**Issue by AriwFeng** [antvis/G6#922]
graph.read(data);
graph.fitView();
树状图展开动画后有一定几率缩在一起
![image](https://user-images.githubusercontent.com/40487947/68743652-e2684280-062d-11ea-8740-7ce2b2535ad2.png)
![image](https://user-images.githubusercontent.com/40487947/68743680-edbb6e00-062d-11ea-9572-39398a2a0a4d.png)

**Comment by baizn** [comment]
给提供个在线demo，我们排查下。

**Comment by Yanyan-Wang** [comment]
考虑是否在展开动画结束之前调用了其他的动画

**Comment by Yanyan-Wang** [comment]
类似问题曾经出现在节点有重复 id 的 case 中。
