### ISSUE TITLE
V3 是否支持group自定义

### ISSUE THREAD

**Issue by pzf0000** [antvis/g6#923]
做流程图的泳道，希望能自定义group形状，文档中写的是只能支持circle和rect，但是在源码中找到了customGroup.js，请问能重绘group的外框吗？画成泳道的形状，在侧边加上label

**Comment by baizn** [comment]
目前不支持

**Comment by velpc** [comment]
现在是否已经支持自定义group外框？

**Comment by baizn** [comment]
> 现在是否已经支持自定义group外框？

现在不支持，预计到 3.4 版本支持。

**Comment by weijiatan456** [comment]
请问这个有后续了吗？X6有泳道，G6有泳道吗？
