### ISSUE TITLE
3.1.6 版本group效果有问题

### ISSUE THREAD

**Issue by chenzhiwei199** [antvis/g6#925]
* **G6 Version**:
3.1.6
* **Platform**:
mac
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/20192061/68876826-087e0780-0740-11ea-809b-eb70376b3b11.png)

* **CodePen Link**:

3.1.1版本是正常的

**Comment by baizn** [comment]
更新到最新版本呢？

**Comment by hanai** [comment]
3.2 版本的也有这个问题

**Comment by baizn** [comment]
复现步骤是怎样的呢？ 我看了下旧版官网和新版都没这个问题啊
旧版的：
![image](https://user-images.githubusercontent.com/9443867/69532557-096d2f80-0fb1-11ea-8776-0cf876dbcb1d.png)

新版的：https://g6.antv.vision/zh/examples/interaction/nodeGroup
![image](https://user-images.githubusercontent.com/9443867/69532655-3faaaf00-0fb1-11ea-8c8d-db20d48d6b81.png)

**Comment by hanai** [comment]
https://codesandbox.io/s/boring-worker-kob0y?fontsize=14&hidenavigation=1&theme=dark

**Comment by baizn** [comment]
已修复，感谢！ https://codesandbox.io/s/boring-worker-kob0y?fontsize=14&hidenavigation=1&theme=dark
