### ISSUE TITLE
空画布时调用fitView报错

### ISSUE THREAD

**Issue by richard-chen-1985** [antvis/g6#926]
* **G6 Version**: 3.1.6
* **Platform**: OSX
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

在画布没有任何内容的时候，调用graph的fitView时会报错

**Comment by baizn** [comment]
是下面这样的吗？ 我测了下没报错。
```
var data = {
  };

  var graph = new G6.Graph({
    container: 'mountNode',
    width: window.innerWidth,
    height: window.innerHeight
  });
  graph.data(data);
  graph.render();
  graph.fitView()
```

**Comment by richard-chen-1985** [comment]
我是看的快速上手里友情链接里几个案例都是这样的，比如 https://guozhaolong.github.io/wfd/

**Comment by Yanyan-Wang** [comment]
经过测试发现 G6 不会报错，应该是这些案例上层实现时的问题。
