### ISSUE TITLE
treeGraph，fixedRoot不生效

### ISSUE THREAD

**Issue by persuitHappy** [antvis/G6#927]
tree向右，给根节点增加子节点，有没有办法让根节点不要向下移动，改成子节点以根节点为中心向两侧延伸。现在的效果是：增加一个子节点，主干向下移动一个单位。

**Comment by Yanyan-Wang** [comment]
v3.4.2 可以试一下，已经没有这个问题。默认情况下会固定根节点位置。在图实例化时 layout 里面通过配置 fixedRoot 可以控制。

**Comment by seed008** [comment]
我用的是4.1.11，但是fixedTree不好使，然后lock也不好使
