### ISSUE TITLE
minimap 缩略图显示不全

### ISSUE THREAD

**Issue by MIAOOOU** [antvis/g6#934]
* **G6 V3.1.6**:
* **chrome**:

minimap 缩略图显示不全，导致通过minimap无法查看全部内容

https://antv.alipay.com/zh-cn/g6/3.x/demo/tool/minimap.html

![image](https://user-images.githubusercontent.com/24906436/69133635-33c27700-0af1-11ea-9a3c-84d6c61fc6db.png)

**Comment by baizn** [comment]
今天会发一个版本，修复这个问题，详见 https://github.com/antvis/g6/pulls?q=is%3Apr+is%3Aclosed。
