### ISSUE TITLE
连续点击两次父节点，子节点没有展开

### ISSUE THREAD

**Issue by SuperKieran** [antvis/g6#937]
https://antv.alipay.com/zh-cn/g6/3.x/demo/tree/tree-indented.html

连续点击两次父节点，子节点没有展开

**Comment by baizn** [comment]
双击是可以展开的，如果连续两次，中间时间间隔稍微长点，就相当于是展开收起了 。

**Comment by SuperKieran** [comment]
双击中间时间隔的短一点，展开了 但是子节点不显示了  这不是bug吗 🤣

**Comment by hellodr333** [comment]
为什么问题被关闭了，我也出现了这样的问题，怎么解决呢？
