### ISSUE TITLE
在type: 'dagre'类型下 只有一个元素的时候 会变得超级大 

### ISSUE THREAD

**Issue by Tsite2007** [antvis/g6#938]
在type: 'dagre'类型下 只有一个元素的时候 会变得超级大 ，size指定了 宽高但是并没有起作用
`width: _width,
                height: 600,
                renderer: 'svg',
                fitView: true,
                fitViewPadding: [ 20, 40, 50, 20 ],
                layout: {
                    type: 'dagre'
                },
                defaultNode: {
                    size: [150, 30],
                    shape: 'rect',
                    style: {
                        fill: '#fff',
                        stroke: '#000000',
                        lineWidth: 1,
                        fontSize: 12
                    },
                    labelCfg: {
                        style: {
                            fill: '#000000'
                        }
                    }
                },`

**Comment by Yanyan-Wang** [comment]
因为你使用了 fitView ，会自动将当前图放缩、平移适配到画布上上
