### ISSUE TITLE
ModelRect  的内置省略号如何去掉

### ISSUE THREAD

**Issue by JslinSir** [antvis/g6#939]
* **G6 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by baizn** [comment]
目前只能复写 drawLabel 方法，今天会发个小版本，文本长度由用户自己控制。

**Comment by JslinSir** [comment]
grap实例没法拿到这个drawLabel方法

**Comment by baizn** [comment]
graph 不需要拿这个方法的，在数据里面控制文本长度。

已修复，麻烦更新到最新版本，多谢！

**Comment by phnessu4** [comment]
@baizn 最新版本，文档上没写参数。控制文本长度的，我要把省略号去掉用什么参数？
