### ISSUE TITLE
拖动miniMap图形不见了

### ISSUE THREAD

**Issue by homeoffriends** [antvis/G6#943]
* **G6 Version**:
3.2.0
* **Platform**:
拖动miniMap图形不见了
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/18474250/69321814-bc225280-0c7e-11ea-990f-881a43a8804b.png)

* **CodePen Link**:

**Comment by hstarorg** [comment]
遇到同样问题，当前是降级版本到 `3.1.4-beta.1` 临时解决的

**Comment by Arlisol** [comment]
> 遇到同样问题，当前是降级版本到 `3.1.4-beta.1` 临时解决的

原来使用 **3.1.x** 的时候没有问题，升级到了 **3.2.3** 出现了这个问题，降级回 **原版本** 和 **3.1.4-beta.1** 依旧出现这个了问题，请问这个问题还有什么临时的解决方案

**Comment by hstarorg** [comment]
@Arlisol 清理下 node_modules，然后锁版本为 3.1.4-beta.1，注意需要锁定版本，'@antv/g6':'3.1.4-beta.1'

**Comment by Arlisol** [comment]
> @Arlisol 清理下 node_modules，然后锁版本为 3.1.4-beta.1，注意需要锁定版本，'@antv/g6':'3.1.4-beta.1'

好的，之前没有锁定版本，现在已经可以了，感谢

**Comment by scaletimes** [comment]
目前解决了下，见 https://github.com/antvis/G6/pull/1043
