### ISSUE TITLE
layout的nodesep属性无效

### ISSUE THREAD

**Issue by homeoffriends** [antvis/g6#944]
* **G6 Version**:
3.2.0
* **Platform**:
layout为“dagre”时nodesep属性无效
* **Mini Showcase(like screenshots)**:
修改nodesep，节点间距不变
        layout: {
          // Object，可选，布局的方法及其配置项，默认为 random 布局。
          type: 'dagre', // 层次布局
          preventOverlap: true, // 防止节点重叠
          rankdir: 'LR',
          nodesep:10
        }
![image](https://user-images.githubusercontent.com/18474250/69322096-3652d700-0c7f-11ea-9586-5242343c21d3.png)

* **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
nodesep 在 rankdir: 'LR' 时代表的时上下节点间距，如果你想在 rankdir: 'LR'  这个方向布局的情况下加大红色箭头的间距，应该用 ranksep 层间距来控制。

在 rankdir: 'TB' 之上而下的 dagre 布局时，nodesep 才代表的是两个节点的水平间距，ranksep 代表层间（竖直的）的间距。

这一点确实文档里面没描述清楚，这就补充一下。
