### ISSUE TITLE
treeGraph怎么通过state改变group的hover和click状态。

### ISSUE THREAD

**Issue by persuitHappy** [antvis/G6#946]
group里面有A(keyshape),B,C,D...通过更改state貌似只能改keyshape的状态。目前我采用的做法是监听node的mouseEnter、mouseLeave事件来遍历group里的每个的shape，用attrs()来更改样式去实现hover效果，请问咱们现在支持用state来改group的状态吗？？？？

**Comment by baizn** [comment]
现在不支持，目前的state只针对keyShape起作用。

**Comment by Yanyan-Wang** [comment]
最新版本 G6 可以支持对非 keyShape 进行状态样式的设置了。详见文档：https://g6.antv.vision/zh/docs/manual/middle/states/state#%E9%85%8D%E7%BD%AE-state-%E6%A0%B7%E5%BC%8F
