### ISSUE TITLE
希望有一个切换树布局的方法~

### ISSUE THREAD

**Issue by liuqiao1** [antvis/g6#95]
我的问题：
       现在树布局方案很丰富： B， V, LR等。但是用户不能根据自己的需要在随时切换布局。

我的期望：
       `function changeLayout(){
    let layout;
    if(tree.get('layoutCfg').dtrection == 'H'){
        layout = vLayout;
    }else{
        layout = hLayout;
    }

    tree.set('layoutCfg', layout);`

或者tree.changeLayout(newLaoutCfg)也行~

**Comment by liuqiao1** [comment]
我现在的做法是：
先把容器内容清空： document.getElementById('container')
然后再重新绘制。

**Comment by TomHuangCN** [comment]
有专门销毁方法的 tree.destroy() 。销毁后重新渲染吧，其实可以这么弄
