### ISSUE TITLE
使用destroy销毁画布时没有清除画布下的tooltip

### ISSUE THREAD

**Issue by Arlisol** [antvis/g6#950]
* **G6 Version**:
3.2.0

* **Platform**:
OSX

* **Mini Showcase(like screenshots)**:
使用 destroy 销毁画布时，没有清除相关画布下的 tooltip，查看文档知道 tooltip 实际上是一个悬浮的div标签。因此在销毁画布时需要手动清除tooltip，希望增加销毁功能对清除tooltip的支持。

* **CodePen Link**:
https://codepen.io/zzy328897847/pen/gOOyPaj

**Comment by baizn** [comment]
Tooltip 接下来可能会重新设计，你可以参考[这种做法](https://g6.antv.vision/zh/docs/manual/middle/g6InReact)来做，更灵活一点，不需要使用内置的 tooltip 的 Behavior。

**Comment by Arlisol** [comment]
> Tooltip 接下来可能会重新设计，你可以参考[这种做法](https://g6.antv.vision/zh/docs/manual/middle/g6InReact)来做，更灵活一点，不需要使用内置的 tooltip 的 Behavior。

好的，感谢
