### ISSUE TITLE
突然出现的一个。。

### ISSUE THREAD

**Issue by Shaxin742** [antvis/g6#951]
13点后突然出现的问题

* **G6 Version**: 最新
* **Platform**: window 
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/23325831/69402144-eaad3580-0d31-11ea-99fd-e80394a35605.png)
* **CodePen Link**: no code

**Comment by baizn** [comment]
之前应该一直是这样，你先手动安装下 numericjs 这个库，下个版本修复，见 #952
