### ISSUE TITLE
typescript类型定义有问题，项目跑起来直接报错呀

### ISSUE THREAD

**Issue by crystalwm** [antvis/G6#955]
* **G6 Version**:3.2.0
* **Platform**:
* **Mini Showcase(like screenshots)**:
ERROR in /Users/xxxnode_modules/@antv/g6/types/index.d.ts(22,8):
TS7016: Could not find a declaration file for module '@antv/util'. '/Users/xxxx/node_modules/@antv/util/build/util.js' implicitly has an 'any
' type.
  Try `npm install @types/antv__util` if it exists or add a new declaration (.d.ts) file containing `declare module '@antv/util';`

根据出错信息，跟antv__util有关，G6现在改动很多，每个版本的类型可能都有不同，我感觉现在类型可以不用定义的特别细致，可以只定义一些主要的方法，比如TreeGraph ， registerEdge 等，config中的细节可以先暂时用any代替，后面版本稳定以后，再定义细粒度的
* **CodePen Link**:

我在项目中，之前有自己定义一些G6的类型，现在更新最新的G6以后，项目报错，显示类型定义有问题，查看G6里面有定义type（之前G6没有定义type的），但是这个type有问题呀，项目跑不起来

下面是我自己之前定义的类型
```
declare module '@antv/g6' {
  export class TreeGraph {
    constructor(options: any);
    [index: string]: any;
  }

  export function registerEdge(node: string, options: any, shape: string) :void;
  export function registerNode(node: string, options: any, shape: string) :void;
  export function registerBehavior(node: string, options: any) :void;
}

```

**Comment by tizzybec** [comment]
碰到同样的问题，@antv/util新版本已经是typescript声明了，g6这边如果把依赖版本升级一下，就不会出现@antv/util无ts类型声明的问题了，或者声明@antv/util为peerdDependancies也是可以的。

**Comment by baizn** [comment]
3.2.2 已临时修复了，接下来会使用 TS 来重构 G6，后面就不会存在类似问题了，感谢！

**Comment by crystalwm** [comment]
还是有一些问题
![image](https://user-images.githubusercontent.com/7902025/69694334-536e2680-1113-11ea-9b97-1af39f3cc7bb.png)
需要  declare module '@antv/util'; 
还有一个地方需要修改的，我来提一个pr吧

**Comment by hstarorg** [comment]
@crystalwm 感谢，确实忽略了这个。

**Comment by hstarorg** [comment]
#973

**Comment by crystalwm** [comment]
感谢，下个G6版本我可以愉快的升级。这个库真心不错

**Comment by crystalwm** [comment]
typescript在version 3.2.4 上可以work了， 感谢~

**Comment by hstarorg** [comment]
@crystalwm 问题解决了，也麻烦 close 下 issue

**Comment by Neur1n** [comment]
请问要用typescript写的话，是另外安装@antv/util就可以了吗

**Comment by crystalwm** [comment]
> 请问要用typescript写的话，是另外安装@antv/util就可以了吗

不需要，g6的版本是3.2.4以上就可以了
