### ISSUE TITLE
希望可以根据需要修改部分节点的lable 样式

### ISSUE THREAD

**Issue by liuqiao1** [antvis/g6#96]
![image](https://user-images.githubusercontent.com/16732082/33167460-927105ec-d078-11e7-9432-d32f6b616a79.png)

现有的G6.Global.nodeLabelStyle配置项，会将对所有的lable生效。
希望可以有一个API，传入节点和lable样式，就会去修改这个节点的lable样式。

**Comment by TomHuangCN** [comment]
节点映射里可以返回

参考这个： https://codepen.io/DoriTong/pen/eeKdeG?editors=1010
