### ISSUE TITLE
build出现错误

### ISSUE THREAD

**Issue by JeroenWang** [antvis/G6#960]
* **G6 Version:3.1.0:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

build时候出现这个错误，请问怎么解决。vue-cli2.0
![image](https://user-images.githubusercontent.com/23203172/69423511-3fb47000-0d61-11ea-99f6-9bfaeba89156.png)

**Comment by baizn** [comment]
更新到最新版本，兼容3.1.0的

**Comment by hstarorg** [comment]
看起来是 UglifyJS 压缩报错，先升级尝试

**Comment by wjh31461** [comment]
更新到3.2.1 build时还是报这个错

**Comment by baizn** [comment]
> 更新到3.2.1 build时还是报这个错

不是升级 G6，是处理 UglifyJS 压缩的错误，按照这里修改下配置：https://blog.csdn.net/dream19921216/article/details/77963471

**Comment by simon-yxl** [comment]
解决了吗，遇到了同样的错误，配置了babel还是不生效

**Comment by wjh31461** [comment]
加上了这个
![image](https://user-images.githubusercontent.com/41609334/69609796-54e11580-1065-11ea-9453-78ce29e56039.png)

build成功了
![image](https://user-images.githubusercontent.com/41609334/69609994-c9b44f80-1065-11ea-89f3-b49255cc5c47.png)

但是dev时控制台又报错了
![image](https://user-images.githubusercontent.com/41609334/69609875-8528b400-1065-11ea-9c8c-bcc1f544da14.png)

**Comment by baizn** [comment]
> 但是dev时控制台又报错了

`import G6 from '@antv/g6'` 后 G6 是 undefined ？

**Comment by wjh31461** [comment]
是的

**Comment by baizn** [comment]
@wjh31461 你报的这个错是 `transform-remove-strict-mode` 插件的问题啊。

**Comment by simon-yxl** [comment]
@baizn 我配置了babel的include也没效果，打包的时候还是报楼主的错误，之前用g2和f2的时候同样的babel和webpack配置也一直没有出现过这个问题

**Comment by hstarorg** [comment]
能否一个最小可重现demo呢？从异常信息来看，和打包配置的关系比较大

**Comment by hstarorg** [comment]
采用 vue-cli@2 使用 webpack 模块（runtime 模式），可直接构建成功。
![image](https://user-images.githubusercontent.com/4043284/69692933-9c6fac00-110e-11ea-804b-fa1cbc88a941.png)

**Comment by wjh31461** [comment]
页面
![image](https://user-images.githubusercontent.com/41609334/69773125-e5863580-11cc-11ea-8626-f047ab57d1bb.png)
![image](https://user-images.githubusercontent.com/41609334/69773181-09497b80-11cd-11ea-8ed4-317a5daa69d7.png)
build后报楼主的错

然后webpack.base.conf.js中添加
![image](https://user-images.githubusercontent.com/41609334/69773249-46ae0900-11cd-11ea-8d08-ede158a4be69.png)
dev和build都报错：
![image](https://user-images.githubusercontent.com/41609334/69773647-59750d80-11ce-11ea-83c9-7f983676b0fa.png)

**Comment by hstarorg** [comment]
@wjh31461 能否提供下具体的可重现demo？或者是vue的build相关配置

**Comment by wjh31461** [comment]
我把
![image](https://user-images.githubusercontent.com/41609334/69800606-8cd88c00-1210-11ea-9cc4-ed90abb2d90f.png)
改成
![image](https://user-images.githubusercontent.com/41609334/69800643-a083f280-1210-11ea-9d3c-4da190f4691b.png)
可以dev也可以build啦
可能是项目中某处改动了这个preset

**Comment by wjh31461** [comment]
关于这个报错
![](https://user-images.githubusercontent.com/41609334/69773647-59750d80-11ce-11ea-83c9-7f983676b0fa.png)

我把g6包中的.babelrc
![image](https://user-images.githubusercontent.com/41609334/69800918-26a03900-1211-11ea-8a4a-7cd7922bcb43.png)
改成
![image](https://user-images.githubusercontent.com/41609334/69800951-391a7280-1211-11ea-9efe-0221cac06214.png)

就没报错啦 可以dev 也可以build
可能是项目中某处改动了preset

**Comment by Yanyan-Wang** [comment]
有小伙伴这样解决的：

主要还是因为G6依赖中包含了非es5的语法，导致打包编译失败，我找了两个解决方法：
一：不改变npm引包方式，在webpack中加入
         {
  es5ImcompatibleVersions: true,
     extraBabelIncludes:[
                 "node_modules/@antv/g6"
             ]
         }
二：改换为CDN引用G6

TA 用的第二种方法，这个方法打包的文件要比第一种打包文件小0.3M
