### ISSUE TITLE
G6 状态切换动画在节点过多时候很卡

### ISSUE THREAD

**Issue by GeoLibra** [antvis/G6#962]
* **G6 Version**:3.2.1
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:https://codesandbox.io/s/determined-rubin-zmr1z?fontsize=14&hidenavigation=1&theme=dark
* ** 官网Demo链接**:https://g6.antv.vision/zh/examples/scatter/stateChange
1、请问当当两边的节点过多时，动画会很卡，你们这边有什么好的解决方法？谢谢！
2、另外我想通过离屏渲染的方式来使用G6绘制的应该如何使用，离屏渲染传递的是canvas，但是G6 初始化是挂在在一个dom上。
```javascript
const graph=new G6.Graph({
     container: "domid",
})
```
所以，想问下如何才能把G6放到离屏canvas里面绘制，有没有例子参考，谢谢

**Comment by baizn** [comment]
对超过150个节点同时做动画的时候是有点卡，接下来会升级底层渲染引擎到 G4.0。
可以通过 `graph.get('canvas')` 拿到 Canvas 实例。

**Comment by GeoLibra** [comment]
请问什么时候升级到4.0？谢谢

**Comment by Yanyan-Wang** [comment]
G6 3.3 已经在 2.17 发布，已经升级到 G4.0，性能大幅度提升。G6 3.4 在 3.11 已发布 。
