### ISSUE TITLE
Retrieve array of elements based on hierarchical/dagre-forced edges sequence

### ISSUE THREAD

**Issue by calebeaires** [antvis/G6#967]
* **G6 Version**: 3.04
* **CodePen Link**: https://codesandbox.io/s/youthful-pond-jty49

Given that a node has its source and target edge and we are using a Dagre mode, I am looking a way to when we save the graph `graph.save()`, the result node array will be sorted on a topological sorting (ex.: Depth-first search - https://en.wikipedia.org/wiki/Topological_sorting).

Given that the source array to `graph.data(array); graph.render();` is this one:

```js
  nodes: [
    {
      id: '3',
      label: '3'
    },{
    id: '0',
    label: '0'
  },
  {
    id: '2',
    label: '2'
  },
  {
    id: '1',
    label: '1'
  }]
```

**edges
```js
edges: [{
    source: '0',
    target: '1'
  },
  {
    source: '0',
    target: '2'
  },
  {
    source: '0',
    target: '3'
  },
  {
    source: '2',
    target: '3'
  }]
```

With this canvas

![Screen Shot 2019-11-25 at 17 50 53](https://user-images.githubusercontent.com/794195/69576983-2d7a4200-0fac-11ea-89b0-19a31e15e5b1.png)

And after `graph.save()`, the nodes list will be like this:

** final nodes
```js
  nodes: [{
    id: '0',
    label: '0'
  },
{
    id: '1',
    label: '1'
  },
  {
    id: '2',
    label: '2'
  },
    {
      id: '3',
      label: '3'
    }]
```

**Comment by Yanyan-Wang** [comment]
For now, G6 does not integrate the ordering algorithms like depth-first search. But we plan to implement basic graph analysis algorithms in the next step.

There is a simple way to order the nodes according to the layout: sort the array of nodes according to the positions of nodes after layout.

**Comment by zhaoqize** [comment]
It gives me the idea of the sequence problem，cool

**Comment by calebeaires** [comment]
To those that are looking to a solution, AntVis/G6 team launch this:

https://github.com/antvis/G6/blob/master/docs/api/Algorithm.en.md
