### ISSUE TITLE
Drag virtual edges to create real ones

### ISSUE THREAD

**Issue by calebeaires** [antvis/G6#968]
* **G6 Version**: 3.04
* **Feature Request**

Creates handles on nodes that can be dragged to create edges between nodes, like this picture

![Screen Shot 2019-11-25 at 17 58 17](https://user-images.githubusercontent.com/794195/69577935-34a24f80-0fae-11ea-81dd-651c6d194253.png)

**Comment by Yanyan-Wang** [comment]
Checkout this demo: https://codepen.io/Yanyan-Wang/pen/qBBNaye
