### ISSUE TITLE
html节点可以加监听事件吗？或者节点如何交互

### ISSUE THREAD

**Issue by wb-xiaoduan** [antvis/g6#97]
`G6.registNode('customHtml3', {
    cssSize: true,
    getHtml(cfg){
      const model = cfg.model;
      const dom = Util.createDOM('<ul class="customNode2"><li><a href="javacript:alert(1)">html节点</a></li><li>'+model.id+'</li><li>x:'+model.x+'</li><li>y:'+model.y+'</li></ul>');
      return dom;
    }
  }, 'html');`

DOM里有个a标签，我想它点击后，能回调出来。

**Comment by wb-xiaoduan** [comment]
最终选了一个比较暴力的办法
$("#canvas_2").remove();

**Comment by TomHuangCN** [comment]
呃，其实把里头要点击的元素 z-index 设大就行了

https://antv.alipay.com/zh-cn/g6/1.x/demo/flow/saoma.html
