### ISSUE TITLE
tree的Bug, 给边添加update生命周期，动态增加节点会找不到锚点

### ISSUE THREAD

**Issue by persuitHappy** [antvis/G6#972]
`
        G6.registerEdge('line-arrow', {
            update: () => null,
            draw: function draw(cfg, group) {
                const startPoint = cfg.startPoint;
                const endPoint = cfg.endPoint;
                const keyShape = group.addShape('path', {
                    attrs: {
                        path: [
                            ['M', startPoint.x, startPoint.y],
                            ['L', 1 / 3 * endPoint.x  + 2 / 3 * startPoint.x, startPoint.y],
                            ['L', 1 / 3 * endPoint.x  + 2 / 3 * startPoint.x, endPoint.y],
                            ['L', endPoint.x, endPoint.y]
                        ],
                        stroke: '#BBB',
                        lineWidth: 1,
                        className: 'edge-shape'
                    }
                });
                return keyShape;
            }
        });
`

**Comment by persuitHappy** [comment]
G6.registerEdge('line-arrow', {
            update: () => null,
            draw: function draw(cfg, group) {
                const startPoint = cfg.startPoint;
                const endPoint = cfg.endPoint;
                const keyShape = group.addShape('path', {
                    attrs: {
                        path: [
                            ['M', startPoint.x, startPoint.y],
                            ['L', 1 / 3 * endPoint.x  + 2 / 3 * startPoint.x, startPoint.y],
                            ['L', 1 / 3 * endPoint.x  + 2 / 3 * startPoint.x, endPoint.y],
                            ['L', endPoint.x, endPoint.y]
                        ],
                        stroke: '#BBB',
                        lineWidth: 1,
                        className: 'edge-shape'
                    }
                });
                return keyShape;
            }
        });

**Comment by baizn** [comment]
update 方法 返回 null 了还怎么找得到呢？

在这里使用 你自定义的 边 测试 下，动态加载数据没问题，收起再展开需要实现update方法，或者不要加update，使用默认的，https://g6.antv.vision/zh/examples/interaction/loadData#loadTreeData

> demo 中只建议在 叶子节点上面动态加载数据。

```
import G6 from '@antv/g6';

G6.registerEdge('line-arrow', {
        update: () => null,
        draw: function draw(cfg, group) {
            const startPoint = cfg.startPoint;
            const endPoint = cfg.endPoint;
            const keyShape = group.addShape('path', {
                attrs: {
                    path: [
                        ['M', startPoint.x, startPoint.y],
                        ['L', 1 / 3 * endPoint.x  + 2 / 3 * startPoint.x, startPoint.y],
                        ['L', 1 / 3 * endPoint.x  + 2 / 3 * startPoint.x, endPoint.y],
                        ['L', endPoint.x, endPoint.y]
                    ],
                    stroke: '#BBB',
                    lineWidth: 1,
                    className: 'edge-shape'
                }
            });
            return keyShape;
        }
    });

 /**
   * 该案例演示，当点击叶子节点时，如何向树图中动态添加数据。
   * 主要演示addChild和refreshLayout的用法。
   */
const width = document.getElementById('container').scrollWidth;
const height = document.getElementById('container').scrollHeight || 500;
const graph = new G6.TreeGraph({
  container: 'container',
  width,
  height,
  pixelRatio: 2,
  renderer: 'svg',
  modes: {
    default: [ 'collapse-expand', 'drag-canvas' ]
  },
  fitView: true,
  layout: {
    type: 'compactBox',
    direction: 'LR',
    defalutPosition: [],
    getId: function getId(d) {
      return d.id;
    },
    getHeight: function getHeight() {
      return 16;
    },
    getWidth: function getWidth() {
      return 16;
    },
    getVGap: function getVGap() {
      return 50;
    },
    getHGap: function getHGap() {
      return 100;
    }
  }
});
graph.node(function(node) {
  return {
    size: 16,
    anchorPoints: [[ 0, 0.5 ], [ 1, 0.5 ]],
    style: {
      fill: '#DEE9FF',
      stroke: '#5B8FF9'
    },
    label: node.id,
    labelCfg: {
      position: node.children && node.children.length > 0 ? 'left' : 'right'
    }
  };
});

graph.edge(function() {
  return {
    shape: 'line-arrow',
    color: '#A3B1BF'
  };
});

const data = {
  isRoot: true,
  id: 'Root',
  style: {
    fill: 'red'
  },
  children: [{
    id: 'SubTreeNode1',
    raw: {},
    children: [{
      id: 'SubTreeNode1.1'
    }, {
      id: 'SubTreeNode1.2',
      children: [{
        id: 'SubTreeNode1.2.1'
      }, {
        id: 'SubTreeNode1.2.2'
      }, {
        id: 'SubTreeNode1.2.3'
      }]
    }]
  }, {
    id: 'SubTreeNode2',
    children: [{
      id: 'SubTreeNode2.1'
    }]
  }, {
    id: 'SubTreeNode3',
    children: [{
      id: 'SubTreeNode3.1'
    }, {
      id: 'SubTreeNode3.2'
    }, {
      id: 'SubTreeNode3.3'
    }]
  }, {
    id: 'SubTreeNode4'
  }, {
    id: 'SubTreeNode5'
  }, {
    id: 'SubTreeNode6'
  }]
};
graph.data(data);
graph.render();

let count = 0;

graph.on('node:click', function(evt) {
  const item = evt.item;

  const nodeId = item.get('id');
  const model = item.getModel();
  const children = model.children;
  if (!children || children.length === 0) {
    const childData = {
      id: 'child-data-' + count,
      shape: 'rect',
      children: [{
        id: 'x-' + count
      }, {
        id: 'y-' + count
      }]
    };
    graph.addChild(childData, nodeId);
    count++;
    graph.refreshLayout();
  }
});
```

**Comment by persuitHappy** [comment]
> update 方法 返回 null 了还怎么找得到呢？
> 
> 在这里使用 你自定义的 边 测试 下，动态加载数据没问题，收起再展开需要实现update方法，或者不要加update，使用默认的，https://g6.antv.vision/zh/examples/interaction/loadData#loadTreeData
> 
> > demo 中只建议在 叶子节点上面动态加载数据。
> 
> ```
> import G6 from '@antv/g6';
> 
> G6.registerEdge('line-arrow', {
>         update: () => null,
>         draw: function draw(cfg, group) {
>             const startPoint = cfg.startPoint;
>             const endPoint = cfg.endPoint;
>             const keyShape = group.addShape('path', {
>                 attrs: {
>                     path: [
>                         ['M', startPoint.x, startPoint.y],
>                         ['L', 1 / 3 * endPoint.x  + 2 / 3 * startPoint.x, startPoint.y],
>                         ['L', 1 / 3 * endPoint.x  + 2 / 3 * startPoint.x, endPoint.y],
>                         ['L', endPoint.x, endPoint.y]
>                     ],
>                     stroke: '#BBB',
>                     lineWidth: 1,
>                     className: 'edge-shape'
>                 }
>             });
>             return keyShape;
>         }
>     });
> 
>  /**
>    * 该案例演示，当点击叶子节点时，如何向树图中动态添加数据。
>    * 主要演示addChild和refreshLayout的用法。
>    */
> const width = document.getElementById('container').scrollWidth;
> const height = document.getElementById('container').scrollHeight || 500;
> const graph = new G6.TreeGraph({
>   container: 'container',
>   width,
>   height,
>   pixelRatio: 2,
>   renderer: 'svg',
>   modes: {
>     default: [ 'collapse-expand', 'drag-canvas' ]
>   },
>   fitView: true,
>   layout: {
>     type: 'compactBox',
>     direction: 'LR',
>     defalutPosition: [],
>     getId: function getId(d) {
>       return d.id;
>     },
>     getHeight: function getHeight() {
>       return 16;
>     },
>     getWidth: function getWidth() {
>       return 16;
>     },
>     getVGap: function getVGap() {
>       return 50;
>     },
>     getHGap: function getHGap() {
>       return 100;
>     }
>   }
> });
> graph.node(function(node) {
>   return {
>     size: 16,
>     anchorPoints: [[ 0, 0.5 ], [ 1, 0.5 ]],
>     style: {
>       fill: '#DEE9FF',
>       stroke: '#5B8FF9'
>     },
>     label: node.id,
>     labelCfg: {
>       position: node.children && node.children.length > 0 ? 'left' : 'right'
>     }
>   };
> });
> 
> graph.edge(function() {
>   return {
>     shape: 'line-arrow',
>     color: '#A3B1BF'
>   };
> });
> 
> const data = {
>   isRoot: true,
>   id: 'Root',
>   style: {
>     fill: 'red'
>   },
>   children: [{
>     id: 'SubTreeNode1',
>     raw: {},
>     children: [{
>       id: 'SubTreeNode1.1'
>     }, {
>       id: 'SubTreeNode1.2',
>       children: [{
>         id: 'SubTreeNode1.2.1'
>       }, {
>         id: 'SubTreeNode1.2.2'
>       }, {
>         id: 'SubTreeNode1.2.3'
>       }]
>     }]
>   }, {
>     id: 'SubTreeNode2',
>     children: [{
>       id: 'SubTreeNode2.1'
>     }]
>   }, {
>     id: 'SubTreeNode3',
>     children: [{
>       id: 'SubTreeNode3.1'
>     }, {
>       id: 'SubTreeNode3.2'
>     }, {
>       id: 'SubTreeNode3.3'
>     }]
>   }, {
>     id: 'SubTreeNode4'
>   }, {
>     id: 'SubTreeNode5'
>   }, {
>     id: 'SubTreeNode6'
>   }]
> };
> graph.data(data);
> graph.render();
> 
> let count = 0;
> 
> graph.on('node:click', function(evt) {
>   const item = evt.item;
> 
>   const nodeId = item.get('id');
>   const model = item.getModel();
>   const children = model.children;
>   if (!children || children.length === 0) {
>     const childData = {
>       id: 'child-data-' + count,
>       shape: 'rect',
>       children: [{
>         id: 'x-' + count
>       }, {
>         id: 'y-' + count
>       }]
>     };
>     graph.addChild(childData, nodeId);
>     count++;
>     graph.refreshLayout();
>   }
> });
> ```

谢谢小姐姐解答，我这给自定义边添加update生命周期就会遇到找不到锚点问题，如果把update生命周期去掉就会是正常的效果。我本想通过调用updateItem('边id')来触发update周期去改变边的颜色，这种方法可以修改边颜色，但是动态增加子节点会找不到锚点（样式乱了55555）。然后尝试了去掉update周期，用updateItem('边id',{style:{stroke:'#f00'}})，没有效果。请问还有其他的方法吗？

**Comment by baizn** [comment]
update方法你要实现一下啊 ，不能直接返回null。

**Comment by persuitHappy** [comment]
> update方法你要实现一下啊 ，不能直接返回null。

感谢解决了

**Comment by baizn** [comment]
@persuitHappy  你把解决方式在这里回复下，后面有遇到同样问题的同学就可以参考了。

**Comment by persuitHappy** [comment]
G6.registerEdge('line-arrow', {
        update: () => {
                // 这个重新把path设置一下就好了
        },
        draw: function draw(cfg, group) {
            const startPoint = cfg.startPoint;
            const endPoint = cfg.endPoint;
            const keyShape = group.addShape('path', {
                attrs: {
                    path: [
                        ['M', startPoint.x, startPoint.y],
                        ['L', 1 / 3 * endPoint.x  + 2 / 3 * startPoint.x, startPoint.y],
                        ['L', 1 / 3 * endPoint.x  + 2 / 3 * startPoint.x, endPoint.y],
                        ['L', endPoint.x, endPoint.y]
                    ],
                    stroke: '#BBB',
                    lineWidth: 1,
                    className: 'edge-shape'
                }
            });
            return keyShape;
        }
    });

**Comment by cjinhuo** [comment]
> path
update: () => {
// 这个重新把path设置一下就好了
},

这个path是怎么设置的可以放一下代码 我遇到了和你类似的问题
