### ISSUE TITLE
Failed to minify the code

### ISSUE THREAD

**Issue by xwzpp** [antvis/g6#974]
* **G6 Version**:  3.1.9
* **Platform**: mac
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/7036549/69720056-c34cd300-114c-11ea-91eb-9133fc03af23.png)
* **CodePen Link**:

**Comment by baizn** [comment]
和 https://github.com/antvis/g6/issues/960 属于同一个问题，参考这里，修改下你项目配置。
