### ISSUE TITLE
切换mode时，tooltip卡死。

### ISSUE THREAD

**Issue by mcdyzg** [antvis/G6#986]
* **G6 Version**: 3.1.6
* **Platform**: chrome
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://codepen.io/mcdyzg/pen/YzPKKNE

1. 点击图形，tooltip固定不能移动
2. 点击空白区域，然后hover到rect上，又出现一个tooltip

**Comment by baizn** [comment]
使用这种方式，https://g6.antv.vision/zh/docs/manual/middle/g6InReact， 目前内置的 Behavior 形式后面会重新设计。

**Comment by mcdyzg** [comment]
@baizn 404了
