### ISSUE TITLE
自定义线条使用动画系统卡慢

### ISSUE THREAD

**Issue by ZeroJsus** [antvis/G6#988]
* **G6 Version**:3.1.5
* **Platform**:mac
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: http://apprx.cn/demo/

      使用g6在自定义的线条上创建动画效果的时候(afterDraw)，当前系统中的CPU和GPU占用会非常的高。 导致在使用其他程序的时候产生卡顿或者页面无相应。

**Comment by baizn** [comment]
和 这个 https://github.com/antvis/G6/issues/962 是同一个问题。

**Comment by ZeroJsus** [comment]
问题是 现在没有超过150个节点啊
