### ISSUE TITLE
升级到1.2.0后，自定义的G6.Global.nodeAcitveBoxStyle失效

### ISSUE THREAD

**Issue by wsdqr001** [antvis/g6#99]
升级到1.2.0后，自定义的G6.Global.nodeAcitveBoxStyle失效，还是默认效果。

**Comment by TomHuangCN** [comment]
1.2.0 修正了部分属性名的拼写错误

https://antv.alipay.com/zh-cn/g6/1.x/tutorial/updateDoc.html#_拼写错误

**Comment by wsdqr001** [comment]
thx!
