### ISSUE TITLE
npm run build 打包之后报错

### ISSUE THREAD

**Issue by 499127061** [antvis/G6#994]
npm run dev 运行的时候没问题，
npm run build 打包就报错，不知道哪里的问题，看评论有说g6里面有非es5语法，打包时就会出错，该怎么改呢，求教！ @

**Comment by baizn** [comment]
node_modules 删掉重新装一下，还不行的话你把错误截图发出来看下呢？

**Comment by liper** [comment]
我也遇到了和你差不多的问题，我是编译的时候就说有扩展符，解析不了

**Comment by baizn** [comment]
> 我也遇到了和你差不多的问题，我是编译的时候就说有扩展符，解析不了

截图发一下呢

**Comment by Yanyan-Wang** [comment]
升级到 V3.2.4 试一试？ 刚刚发布了一个小版本尝试修复了一下

**Comment by baizn** [comment]
@499127061  还报错吗  没问题的话麻烦关闭下。

**Comment by 475533819** [comment]
@baizn 我也出现类似的问题，我是把版本3.0.4升级到3.2.3，无法npm run build；
![image](https://user-images.githubusercontent.com/35600665/70596227-47f52200-1c20-11ea-9a9a-8abbdd09fa92.png)

**Comment by 499127061** [comment]
改了全局引用，就好了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"475533819"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月11日(星期三) 下午2:12
收件人:&nbsp;"antvis/G6"<G6@noreply.github.com&gt;;
抄送:&nbsp;"当年明月"<499127061@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [antvis/G6] npm run build 打包之后报错 (#994)




@baizn 我也出现类似的问题，我是把版本3.0.4升级到3.2.3，无法npm run build；

**Comment by 475533819** [comment]
![image](https://user-images.githubusercontent.com/35600665/70596305-88ed3680-1c20-11ea-9a31-1cbe46209a09.png)
webpack可以改吗

**Comment by 475533819** [comment]
@499127061 那原来的包需要卸载吗

**Comment by 499127061** [comment]
谢谢，已经解决了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Moyee"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月2日(星期一) 晚上9:21
收件人:&nbsp;"antvis/G6"<G6@noreply.github.com&gt;;
抄送:&nbsp;"当年明月"<499127061@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [antvis/G6] npm run build 打包之后报错 (#994)



 
我也遇到了和你差不多的问题，我是编译的时候就说有扩展符，解析不了
  
截图发一下呢

**Comment by 499127061** [comment]
全局引用，文件里的注释掉就好了

**Comment by 499127061** [comment]
全局引用


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"嗨多磨"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月2日(星期一) 下午5:33
收件人:&nbsp;"antvis/G6"<G6@noreply.github.com&gt;;
抄送:&nbsp;"当年明月"<499127061@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [antvis/G6] npm run build 打包之后报错 (#994)




我也遇到了和你差不多的问题，我是编译的时候就说有扩展符，解析不了

**Comment by flyaaaaaaaa** [comment]
webpack里面和你这个一样，怎么改成全局的，我改成全局的为什么说找不到包

**Comment by 499127061** [comment]
你是？问的是什么问题？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"BLANE"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月20日(星期四) 下午5:55
收件人:&nbsp;"antvis/G6"<G6@noreply.github.com&gt;;
抄送:&nbsp;"当年明月"<499127061@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [antvis/G6] npm run build 打包之后报错 (#994)




webpack里面和你这个一样，怎么改成全局的，我改成全局的为什么说找不到包

**Comment by flyaaaaaaaa** [comment]
也是这个问题Failed to minify the bundle. Error: 3.1b1eb306.async.js from UglifyJs，
![image](https://user-images.githubusercontent.com/39297257/74922759-a7369600-540a-11ea-83b7-9b931ceb7772.png)
现在改成这样后，这里面的包怎么引用啊，报这个错误module not found: Can't resolve '@antv/g6/es/g6' in

**Comment by 499127061** [comment]
不是有上传的截图么？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "BLANE"<notifications@github.com&gt;; 
发送时间: 2020年2月20日(星期四) 下午5:59
收件人: "antvis/G6"<G6@noreply.github.com&gt;; 
抄送: "当年明月"<499127061@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [antvis/G6] npm run build 打包之后报错 (#994)




也是这个问题Failed to minify the bundle. Error: 3.1b1eb306.async.js from UglifyJs，
 
 现在改成这样后，这里面的包怎么引用啊，报这个错误module not found: Can't resolve '@antv/g6/es/g6' in

**Comment by flyaaaaaaaa** [comment]
那个截图看了，extraBabelPlugins按照那个配置么，然后G6的包从哪里引用

**Comment by 499127061** [comment]
我是文件引入的






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "BLANE"<notifications@github.com&gt;; 
发送时间: 2020年2月20日(星期四) 晚上6:03
收件人: "antvis/G6"<G6@noreply.github.com&gt;; 
抄送: "当年明月"<499127061@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [antvis/G6] npm run build 打包之后报错 (#994)




那个截图看了，extraBabelPlugins按照那个配置么，然后G6的包从哪里引用

**Comment by flyaaaaaaaa** [comment]
不能直接import G6 from '@antv/g6';引入吧，文件引入这个要怎么做

**Comment by 499127061** [comment]
我用import引入有问题，我就用这个了，直接引入这个链接就好了https://gw.alipayobjects.com/os/antv/pkg/_antv.g6-3.2.3/build/g6.js




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "BLANE"<notifications@github.com&gt;; 
发送时间: 2020年2月20日(星期四) 晚上6:09
收件人: "antvis/G6"<G6@noreply.github.com&gt;; 
抄送: "当年明月"<499127061@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [antvis/G6] npm run build 打包之后报错 (#994)




不能直接import G6 from '@antv/g6';引入吧，文件引入这个要怎么做

**Comment by flyaaaaaaaa** [comment]
好的，谢谢了
